; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -passes=loop-vectorize < %s | FileCheck %s

; The step of pointer iv is not live-in.
; Check this doesn't crash optimizeInductionExitUsers.
define void @ham(ptr %arg, i32 %arg1) {
; CHECK-LABEL: define void @ham(
; CHECK-SAME: ptr [[ARG:%.*]], i32 [[ARG1:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr null, align 8
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[LOAD]] to i64
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PHI1:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[GEP:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[ADD]] = add i32 [[PHI0]], -1
; CHECK-NEXT:    [[GEP]] = getelementptr i8, ptr [[PHI1]], i64 [[ZEXT]]
; CHECK-NEXT:    store ptr [[GEP]], ptr [[PHI1]], align 8
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[ADD]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[PHI2:%.*]] = phi ptr [ [[PHI1]], %[[LOOP]] ]
; CHECK-NEXT:    ret void
;
entry:
  %load = load i32, ptr null, align 8
  %zext = zext i32 %load to i64
  br label %loop

loop:
  %phi0 = phi i32 [ 0, %entry ], [ %add, %loop ]
  %phi1 = phi ptr [ null, %entry ], [ %gep, %loop ]
  %add = add i32 %phi0, -1
  %gep = getelementptr i8, ptr %phi1, i64 %zext
  store ptr %gep, ptr %phi1, align 8
  %cond = icmp eq i32 %add, 0
  br i1 %cond, label %exit, label %loop

exit:
  %phi2 = phi ptr [ %phi1, %loop ]
  ret void
}

