; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize  -S < %s | FileCheck %s

%struct.ImageParameters = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, float, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32**, i32**, i32, i32***, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [9 x [16 x [16 x i16]]], [5 x [16 x [16 x i16]]], [9 x [8 x [8 x i16]]], [2 x [4 x [16 x [16 x i16]]]], [16 x [16 x i16]], [16 x [16 x i32]], i32****, i32***, %struct.Picture*, %struct.Slice*, %struct.macroblock*, [1200 x %struct.syntaxelement], i32*, i32*, i32, i32, i32, i32, [4 x [4 x i32]], i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i16******, i16******, i16******, i16******, [15 x i16], i32, i32, i32, i32, i32, i32, i32, i32, [6 x [15 x i32]], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [1 x i32], i32, i32, [2 x i32], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, %struct.DecRefPicMarking_s*, i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i32, i32, i32, double*, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [2 x i32], i32, i32, i32 }
%struct.Picture = type { i32, i32, [100 x %struct.Slice*], i32, float, float, float }
%struct.Slice = type { i32, i32, i32, i32, i32, i32, %struct.datapartition*, %struct.MotionInfoContexts*, %struct.TextureInfoContexts*, %struct.RMPNIbuffer_s*, i32, i32*, i32*, i32*, i32, i32*, i32*, i32*, i32 (i32)*, [3 x [2 x i32]] }
%struct.datapartition = type { %struct.Bitstream*, %struct.EncodingEnvironment, i32 (%struct.syntaxelement*, %struct.datapartition*)* }
%struct.Bitstream = type { i32, i32, i8, i32, i32, i8, i8, i32, i32, i8*, i32 }
%struct.EncodingEnvironment = type { i32, i32, i32, i32, i32, i8*, i32*, i32, i32, i32, i32, i32, i8*, i32*, i32, i32, i32, i32, i32, i32 }
%struct.syntaxelement = type { i32, i32, i32, i32, i32, i32, i32, i32, void (i32, i32, i32*, i32*)*, void (%struct.syntaxelement*, %struct.EncodingEnvironment*)* }
%struct.MotionInfoContexts = type { [3 x [11 x %struct.BiContextType]], [2 x [9 x %struct.BiContextType]], [2 x [10 x %struct.BiContextType]], [2 x [6 x %struct.BiContextType]], [4 x %struct.BiContextType], [4 x %struct.BiContextType], [3 x %struct.BiContextType] }
%struct.BiContextType = type { i16, i8, i64 }
%struct.TextureInfoContexts = type { [2 x %struct.BiContextType], [4 x %struct.BiContextType], [3 x [4 x %struct.BiContextType]], [10 x [4 x %struct.BiContextType]], [10 x [15 x %struct.BiContextType]], [10 x [15 x %struct.BiContextType]], [10 x [5 x %struct.BiContextType]], [10 x [5 x %struct.BiContextType]], [10 x [15 x %struct.BiContextType]], [10 x [15 x %struct.BiContextType]] }
%struct.RMPNIbuffer_s = type { i32, i32, %struct.RMPNIbuffer_s* }
%struct.macroblock = type { i32, i32, i32, i32, i32, [8 x i32], %struct.macroblock*, %struct.macroblock*, i32, [2 x [4 x [4 x [2 x i32]]]], [16 x i32], [16 x i32], i32, i64, [4 x i32], [4 x i32], i64, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.DecRefPicMarking_s = type { i32, i32, i32, i32, i32, %struct.DecRefPicMarking_s* }

@probability = dso_local global [128 x double] [double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 0.000000e+00, double 5.000000e-01, double 4.746090e-01, double 4.505070e-01, double 4.276290e-01, double 4.059120e-01, double 3.852990e-01, double 3.657320e-01, double 3.471590e-01, double 3.295300e-01, double 3.127950e-01, double 2.969110e-01, double 2.818330e-01, double 2.675200e-01, double 2.539350e-01, double 2.410390e-01, double 2.287990e-01, double 2.171800e-01, double 2.061510e-01, double 1.956820e-01, double 1.857440e-01, double 1.763120e-01, double 1.673580e-01, double 1.588590e-01, double 1.507920e-01, double 1.431340e-01, double 1.358660e-01, double 1.289660e-01, double 1.224170e-01, double 1.162000e-01, double 1.102990e-01, double 1.046980e-01, double 0x3FB9710880D801B4, double 9.433400e-02, double 0x3FB6EC4A4095F245, double 8.499600e-02, double 8.068000e-02, double 0x3FB39AF1886DF82B, double 0x3FB29C12F09D8C6D, double 0x3FB1AA1D755BCCAF, double 6.549800e-02, double 6.217200e-02, double 5.901400e-02, double 5.601800e-02, double 5.317300e-02, double 5.047300e-02, double 4.790900e-02, double 4.547600e-02, double 4.316700e-02, double 4.097500e-02, double 3.889400e-02, double 3.691900e-02, double 3.504400e-02, double 3.326400e-02, double 3.157500e-02, double 2.997200e-02, double 2.845000e-02, double 2.700500e-02, double 2.563300e-02, double 2.433200e-02, double 2.309600e-02, double 2.192300e-02, double 2.081000e-02, double 1.975300e-02, double 1.875000e-02], align 8
@img = external dso_local global %struct.ImageParameters*, align 8
@entropy = dso_local global [128 x double] zeroinitializer, align 8
@INIT_MB_TYPE_I = internal constant [1 x [3 x [11 x [2 x i32]]]] [[3 x [11 x [2 x i32]]] [[11 x [2 x i32]] [[2 x i32] [i32 20, i32 -15], [2 x i32] [i32 2, i32 54], [2 x i32] [i32 3, i32 74], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 -28, i32 127], [2 x i32] [i32 -23, i32 104], [2 x i32] [i32 -6, i32 53], [2 x i32] [i32 -1, i32 54], [2 x i32] [i32 7, i32 51], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64]], [11 x [2 x i32]] [[2 x i32] [i32 20, i32 -15], [2 x i32] [i32 2, i32 54], [2 x i32] [i32 3, i32 74], [2 x i32] [i32 20, i32 -15], [2 x i32] [i32 2, i32 54], [2 x i32] [i32 3, i32 74], [2 x i32] [i32 -28, i32 127], [2 x i32] [i32 -23, i32 104], [2 x i32] [i32 -6, i32 53], [2 x i32] [i32 -1, i32 54], [2 x i32] [i32 7, i32 51]], [11 x [2 x i32]] [[2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64]]]], align 8
@INIT_MB_TYPE_P = internal constant [3 x [3 x [11 x [2 x i32]]]] [[3 x [11 x [2 x i32]]] [[11 x [2 x i32]] [[2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64]], [11 x [2 x i32]] [[2 x i32] [i32 23, i32 33], [2 x i32] [i32 23, i32 2], [2 x i32] [i32 21, i32 0], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 1, i32 9], [2 x i32] [i32 0, i32 49], [2 x i32] [i32 -37, i32 118], [2 x i32] [i32 5, i32 57], [2 x i32] [i32 -13, i32 78], [2 x i32] [i32 -11, i32 65], [2 x i32] [i32 1, i32 62]], [11 x [2 x i32]] [[2 x i32] [i32 26, i32 67], [2 x i32] [i32 16, i32 90], [2 x i32] [i32 9, i32 104], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 -46, i32 127], [2 x i32] [i32 -20, i32 104], [2 x i32] [i32 1, i32 67], [2 x i32] [i32 18, i32 64], [2 x i32] [i32 9, i32 43], [2 x i32] [i32 29, i32 0], [2 x i32] [i32 0, i32 64]]], [3 x [11 x [2 x i32]]] [[11 x [2 x i32]] [[2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64]], [11 x [2 x i32]] [[2 x i32] [i32 22, i32 25], [2 x i32] [i32 34, i32 0], [2 x i32] [i32 16, i32 0], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 -2, i32 9], [2 x i32] [i32 4, i32 41], [2 x i32] [i32 -29, i32 118], [2 x i32] [i32 2, i32 65], [2 x i32] [i32 -6, i32 71], [2 x i32] [i32 -13, i32 79], [2 x i32] [i32 5, i32 52]], [11 x [2 x i32]] [[2 x i32] [i32 57, i32 2], [2 x i32] [i32 41, i32 36], [2 x i32] [i32 26, i32 69], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 -45, i32 127], [2 x i32] [i32 -15, i32 101], [2 x i32] [i32 -4, i32 76], [2 x i32] [i32 26, i32 34], [2 x i32] [i32 19, i32 22], [2 x i32] [i32 40, i32 0], [2 x i32] [i32 0, i32 64]]], [3 x [11 x [2 x i32]]] [[11 x [2 x i32]] [[2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 0, i32 64]], [11 x [2 x i32]] [[2 x i32] [i32 29, i32 16], [2 x i32] [i32 25, i32 0], [2 x i32] [i32 14, i32 0], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 -10, i32 51], [2 x i32] [i32 -3, i32 62], [2 x i32] [i32 -27, i32 99], [2 x i32] [i32 26, i32 16], [2 x i32] [i32 -4, i32 85], [2 x i32] [i32 -24, i32 102], [2 x i32] [i32 5, i32 57]], [11 x [2 x i32]] [[2 x i32] [i32 54, i32 0], [2 x i32] [i32 37, i32 42], [2 x i32] [i32 12, i32 97], [2 x i32] [i32 0, i32 64], [2 x i32] [i32 -32, i32 127], [2 x i32] [i32 -22, i32 117], [2 x i32] [i32 -2, i32 74], [2 x i32] [i32 20, i32 40], [2 x i32] [i32 20, i32 10], [2 x i32] [i32 29, i32 0], [2 x i32] [i32 0, i32 64]]]], align 8
@num_mb_per_slice = dso_local global i32 0, align 4
@number_of_slices = dso_local global i32 0, align 4
@initialized = dso_local global i32*** null, align 8
@model_number = dso_local global i32*** null, align 8
; Function Attrs: nofree norecurse nosync nounwind
define dso_local void @GetCtxModelNumber(i32* nocapture noundef writeonly %mnumber, %struct.MotionInfoContexts* nocapture noundef readonly %mc, %struct.TextureInfoContexts* nocapture noundef readnone %tc) local_unnamed_addr #1 {
; CHECK-LABEL: @GetCtxModelNumber(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @img, align 8, !tbaa [[TBAA4:![0-9]+]]
; CHECK-NEXT:    [[TYPE:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS:%.*]], ptr [[TMP0]], i64 0, i32 6
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TYPE]], align 8, !tbaa [[TBAA8:![0-9]+]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[TMP1]], 2
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[CMP]], i64 1, i64 3
; CHECK-NEXT:    [[QP1_I66:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP0]], i64 0, i32 10
; CHECK-NEXT:    br label [[FOR_COND2_PREHEADER:%.*]]
; CHECK:       for.cond2.preheader:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i32 [ [[TMP1]], [[ENTRY:%.*]] ], [ [[DOTPRE:%.*]], [[FOR_INC39_FOR_COND2_PREHEADER_CRIT_EDGE:%.*]] ]
; CHECK-NEXT:    [[INDVARS_IV124:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDVARS_IV_NEXT125:%.*]], [[FOR_INC39_FOR_COND2_PREHEADER_CRIT_EDGE]] ]
; CHECK-NEXT:    [[MIN_XR_0109:%.*]] = phi double [ 1.000000e+30, [[ENTRY]] ], [ [[MIN_XR_1:%.*]], [[FOR_INC39_FOR_COND2_PREHEADER_CRIT_EDGE]] ]
; CHECK-NEXT:    [[CMP9:%.*]] = icmp eq i32 [[TMP2]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[QP1_I66]], align 8, !tbaa [[TBAA13:![0-9]+]]
; CHECK-NEXT:    [[TMP4:%.*]] = icmp sgt i32 [[TMP3]], 0
; CHECK-NEXT:    [[SPEC_SELECT_I_US_US:%.*]] = select i1 [[TMP4]], i32 [[TMP3]], i32 0
; CHECK-NEXT:    br i1 [[CMP9]], label [[FOR_BODY7_US_US_PREHEADER:%.*]], label [[FOR_BODY7_PREHEADER:%.*]]
; CHECK:       for.body7.preheader:
; CHECK-NEXT:    br label [[FOR_BODY7:%.*]]
; CHECK:       for.body7.us.us.preheader:
; CHECK-NEXT:    br label [[FOR_BODY7_US_US:%.*]]
; CHECK:       for.body7.us.us:
; CHECK-NEXT:    [[INDVARS_IV116:%.*]] = phi i64 [ [[INDVARS_IV_NEXT117:%.*]], [[FOR_BODY7_US_US]] ], [ 0, [[FOR_BODY7_US_US_PREHEADER]] ]
; CHECK-NEXT:    [[XR_1103_US_US:%.*]] = phi double [ [[XR_2_US_US:%.*]], [[FOR_BODY7_US_US]] ], [ 0.000000e+00, [[FOR_BODY7_US_US_PREHEADER]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_I, i64 0, i64 0, i64 0, i64 [[INDVARS_IV116]], i64 0
; CHECK-NEXT:    [[COUNT_I_US_US:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS:%.*]], ptr [[MC:%.*]], i64 0, i32 0, i64 0, i64 [[INDVARS_IV116]], i32 2
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[COUNT_I_US_US]], align 8, !tbaa [[TBAA14:![0-9]+]]
; CHECK-NEXT:    [[CONV_I_US_US:%.*]] = uitofp i64 [[TMP6]] to double
; CHECK-NEXT:    [[DIV_I_US_US:%.*]] = fmul fast double [[CONV_I_US_US]], 3.125000e-02
; CHECK-NEXT:    [[CMP3_I_US_US:%.*]] = fcmp fast ogt double [[DIV_I_US_US]], 1.000000e+00
; CHECK-NEXT:    [[COND11_I_US_US:%.*]] = select fast i1 [[CMP3_I_US_US]], double 1.000000e+00, double [[DIV_I_US_US]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP5]], align 8, !tbaa [[TBAA16:![0-9]+]]
; CHECK-NEXT:    [[MUL_I_US_US:%.*]] = mul nsw i32 [[TMP7]], [[SPEC_SELECT_I_US_US]]
; CHECK-NEXT:    [[SHR_I_US_US:%.*]] = ashr i32 [[MUL_I_US_US]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_I, i64 0, i64 0, i64 0, i64 [[INDVARS_IV116]], i64 1
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP8]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ADD_I_US_US:%.*]] = add nsw i32 [[SHR_I_US_US]], [[TMP9]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp sgt i32 [[ADD_I_US_US]], 0
; CHECK-NEXT:    [[COND18_I_US_US:%.*]] = select i1 [[TMP10]], i32 [[ADD_I_US_US]], i32 0
; CHECK-NEXT:    [[CMP19_I_US_US:%.*]] = icmp ult i32 [[COND18_I_US_US]], 127
; CHECK-NEXT:    [[COND30_I_US_US:%.*]] = select i1 [[CMP19_I_US_US]], i32 [[COND18_I_US_US]], i32 127
; CHECK-NEXT:    [[MPS_I_US_US:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 0, i64 [[INDVARS_IV116]], i32 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[MPS_I_US_US]], align 2, !tbaa [[TBAA18:![0-9]+]]
; CHECK-NEXT:    [[TOBOOL_NOT_I_US_US:%.*]] = icmp eq i8 [[TMP11]], 0
; CHECK-NEXT:    [[STATE36_I_US_US:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 0, i64 [[INDVARS_IV116]], i32 0
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[STATE36_I_US_US]], align 8, !tbaa [[TBAA20:![0-9]+]]
; CHECK-NEXT:    [[CONV37_I_US_US:%.*]] = zext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[ADD34_I_US_US:%.*]] = add nuw nsw i32 [[CONV37_I_US_US]], 64
; CHECK-NEXT:    [[SUB_I_US_US:%.*]] = sub nsw i32 63, [[CONV37_I_US_US]]
; CHECK-NEXT:    [[COND39_I_US_US:%.*]] = select i1 [[TOBOOL_NOT_I_US_US]], i32 [[SUB_I_US_US]], i32 [[ADD34_I_US_US]]
; CHECK-NEXT:    [[IDXPROM_I_US_US:%.*]] = sext i32 [[COND39_I_US_US]] to i64
; CHECK-NEXT:    [[ARRAYIDX40_I_US_US:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM_I_US_US]]
; CHECK-NEXT:    [[TMP13:%.*]] = load double, ptr [[ARRAYIDX40_I_US_US]], align 8, !tbaa [[TBAA24:![0-9]+]]
; CHECK-NEXT:    [[IDXPROM42_I_US_US:%.*]] = zext i32 [[COND30_I_US_US]] to i64
; CHECK-NEXT:    [[ARRAYIDX43_I_US_US:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM42_I_US_US]]
; CHECK-NEXT:    [[TMP14:%.*]] = load double, ptr [[ARRAYIDX43_I_US_US]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[TMP15:%.*]] = fneg fast double [[COND11_I_US_US]]
; CHECK-NEXT:    [[TMP16:%.*]] = fmul fast double [[TMP13]], [[TMP15]]
; CHECK-NEXT:    [[SUB45_I_US_US:%.*]] = fmul fast double [[TMP16]], [[TMP14]]
; CHECK-NEXT:    [[SUB46_I_US_US:%.*]] = sub nsw i32 127, [[COND39_I_US_US]]
; CHECK-NEXT:    [[IDXPROM47_I_US_US:%.*]] = sext i32 [[SUB46_I_US_US]] to i64
; CHECK-NEXT:    [[ARRAYIDX48_I_US_US:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM47_I_US_US]]
; CHECK-NEXT:    [[TMP17:%.*]] = load double, ptr [[ARRAYIDX48_I_US_US]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL49_I_US_US:%.*]] = fmul fast double [[TMP17]], [[COND11_I_US_US]]
; CHECK-NEXT:    [[SUB50_I_US_US:%.*]] = xor i32 [[COND30_I_US_US]], 127
; CHECK-NEXT:    [[IDXPROM51_I_US_US:%.*]] = zext i32 [[SUB50_I_US_US]] to i64
; CHECK-NEXT:    [[ARRAYIDX52_I_US_US:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM51_I_US_US]]
; CHECK-NEXT:    [[TMP18:%.*]] = load double, ptr [[ARRAYIDX52_I_US_US]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL53_I_US_US:%.*]] = fmul fast double [[MUL49_I_US_US]], [[TMP18]]
; CHECK-NEXT:    [[SUB54_I_US_US:%.*]] = fsub fast double [[SUB45_I_US_US]], [[MUL53_I_US_US]]
; CHECK-NEXT:    [[XR_2_US_US]] = fadd fast double [[SUB54_I_US_US]], [[XR_1103_US_US]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT117]] = add nuw nsw i64 [[INDVARS_IV116]], 1
; CHECK-NEXT:    [[EXITCOND119_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT117]], 11
; CHECK-NEXT:    br i1 [[EXITCOND119_NOT]], label [[FOR_BODY7_US_US_1_PREHEADER:%.*]], label [[FOR_BODY7_US_US]], !llvm.loop [[LOOP25:![0-9]+]]
; CHECK:       for.body7.us.us.1.preheader:
; CHECK-NEXT:    [[XR_2_US_US_LCSSA:%.*]] = phi double [ [[XR_2_US_US]], [[FOR_BODY7_US_US]] ]
; CHECK-NEXT:    br label [[FOR_BODY7_US_US_1:%.*]]
; CHECK:       for.body7.us.us.1:
; CHECK-NEXT:    [[INDVARS_IV116_1:%.*]] = phi i64 [ [[INDVARS_IV_NEXT117_1:%.*]], [[FOR_BODY7_US_US_1]] ], [ 0, [[FOR_BODY7_US_US_1_PREHEADER]] ]
; CHECK-NEXT:    [[XR_1103_US_US_1:%.*]] = phi double [ [[XR_2_US_US_1:%.*]], [[FOR_BODY7_US_US_1]] ], [ [[XR_2_US_US_LCSSA]], [[FOR_BODY7_US_US_1_PREHEADER]] ]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_I, i64 0, i64 0, i64 1, i64 [[INDVARS_IV116_1]], i64 0
; CHECK-NEXT:    [[COUNT_I_US_US_1:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 1, i64 [[INDVARS_IV116_1]], i32 2
; CHECK-NEXT:    [[TMP20:%.*]] = load i64, ptr [[COUNT_I_US_US_1]], align 8, !tbaa [[TBAA14]]
; CHECK-NEXT:    [[CONV_I_US_US_1:%.*]] = uitofp i64 [[TMP20]] to double
; CHECK-NEXT:    [[DIV_I_US_US_1:%.*]] = fmul fast double [[CONV_I_US_US_1]], 3.125000e-02
; CHECK-NEXT:    [[CMP3_I_US_US_1:%.*]] = fcmp fast ogt double [[DIV_I_US_US_1]], 1.000000e+00
; CHECK-NEXT:    [[COND11_I_US_US_1:%.*]] = select fast i1 [[CMP3_I_US_US_1]], double 1.000000e+00, double [[DIV_I_US_US_1]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[TMP19]], align 8, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL_I_US_US_1:%.*]] = mul nsw i32 [[TMP21]], [[SPEC_SELECT_I_US_US]]
; CHECK-NEXT:    [[SHR_I_US_US_1:%.*]] = ashr i32 [[MUL_I_US_US_1]], 4
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_I, i64 0, i64 0, i64 1, i64 [[INDVARS_IV116_1]], i64 1
; CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[TMP22]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ADD_I_US_US_1:%.*]] = add nsw i32 [[SHR_I_US_US_1]], [[TMP23]]
; CHECK-NEXT:    [[TMP24:%.*]] = icmp sgt i32 [[ADD_I_US_US_1]], 0
; CHECK-NEXT:    [[COND18_I_US_US_1:%.*]] = select i1 [[TMP24]], i32 [[ADD_I_US_US_1]], i32 0
; CHECK-NEXT:    [[CMP19_I_US_US_1:%.*]] = icmp ult i32 [[COND18_I_US_US_1]], 127
; CHECK-NEXT:    [[COND30_I_US_US_1:%.*]] = select i1 [[CMP19_I_US_US_1]], i32 [[COND18_I_US_US_1]], i32 127
; CHECK-NEXT:    [[MPS_I_US_US_1:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 1, i64 [[INDVARS_IV116_1]], i32 1
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[MPS_I_US_US_1]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TOBOOL_NOT_I_US_US_1:%.*]] = icmp eq i8 [[TMP25]], 0
; CHECK-NEXT:    [[STATE36_I_US_US_1:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 1, i64 [[INDVARS_IV116_1]], i32 0
; CHECK-NEXT:    [[TMP26:%.*]] = load i16, ptr [[STATE36_I_US_US_1]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37_I_US_US_1:%.*]] = zext i16 [[TMP26]] to i32
; CHECK-NEXT:    [[ADD34_I_US_US_1:%.*]] = add nuw nsw i32 [[CONV37_I_US_US_1]], 64
; CHECK-NEXT:    [[SUB_I_US_US_1:%.*]] = sub nsw i32 63, [[CONV37_I_US_US_1]]
; CHECK-NEXT:    [[COND39_I_US_US_1:%.*]] = select i1 [[TOBOOL_NOT_I_US_US_1]], i32 [[SUB_I_US_US_1]], i32 [[ADD34_I_US_US_1]]
; CHECK-NEXT:    [[IDXPROM_I_US_US_1:%.*]] = sext i32 [[COND39_I_US_US_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX40_I_US_US_1:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM_I_US_US_1]]
; CHECK-NEXT:    [[TMP27:%.*]] = load double, ptr [[ARRAYIDX40_I_US_US_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[IDXPROM42_I_US_US_1:%.*]] = zext i32 [[COND30_I_US_US_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX43_I_US_US_1:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM42_I_US_US_1]]
; CHECK-NEXT:    [[TMP28:%.*]] = load double, ptr [[ARRAYIDX43_I_US_US_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[TMP29:%.*]] = fneg fast double [[COND11_I_US_US_1]]
; CHECK-NEXT:    [[TMP30:%.*]] = fmul fast double [[TMP27]], [[TMP29]]
; CHECK-NEXT:    [[SUB45_I_US_US_1:%.*]] = fmul fast double [[TMP30]], [[TMP28]]
; CHECK-NEXT:    [[SUB46_I_US_US_1:%.*]] = sub nsw i32 127, [[COND39_I_US_US_1]]
; CHECK-NEXT:    [[IDXPROM47_I_US_US_1:%.*]] = sext i32 [[SUB46_I_US_US_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX48_I_US_US_1:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM47_I_US_US_1]]
; CHECK-NEXT:    [[TMP31:%.*]] = load double, ptr [[ARRAYIDX48_I_US_US_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL49_I_US_US_1:%.*]] = fmul fast double [[TMP31]], [[COND11_I_US_US_1]]
; CHECK-NEXT:    [[SUB50_I_US_US_1:%.*]] = xor i32 [[COND30_I_US_US_1]], 127
; CHECK-NEXT:    [[IDXPROM51_I_US_US_1:%.*]] = zext i32 [[SUB50_I_US_US_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX52_I_US_US_1:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM51_I_US_US_1]]
; CHECK-NEXT:    [[TMP32:%.*]] = load double, ptr [[ARRAYIDX52_I_US_US_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL53_I_US_US_1:%.*]] = fmul fast double [[MUL49_I_US_US_1]], [[TMP32]]
; CHECK-NEXT:    [[SUB54_I_US_US_1:%.*]] = fsub fast double [[SUB45_I_US_US_1]], [[MUL53_I_US_US_1]]
; CHECK-NEXT:    [[XR_2_US_US_1]] = fadd fast double [[SUB54_I_US_US_1]], [[XR_1103_US_US_1]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT117_1]] = add nuw nsw i64 [[INDVARS_IV116_1]], 1
; CHECK-NEXT:    [[EXITCOND119_1_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT117_1]], 11
; CHECK-NEXT:    br i1 [[EXITCOND119_1_NOT]], label [[FOR_BODY7_US_US_2_PREHEADER:%.*]], label [[FOR_BODY7_US_US_1]], !llvm.loop [[LOOP25]]
; CHECK:       for.body7.us.us.2.preheader:
; CHECK-NEXT:    [[XR_2_US_US_1_LCSSA:%.*]] = phi double [ [[XR_2_US_US_1]], [[FOR_BODY7_US_US_1]] ]
; CHECK-NEXT:    br label [[FOR_BODY7_US_US_2:%.*]]
; CHECK:       for.body7.us.us.2:
; CHECK-NEXT:    [[INDVARS_IV116_2:%.*]] = phi i64 [ [[INDVARS_IV_NEXT117_2:%.*]], [[FOR_BODY7_US_US_2]] ], [ 0, [[FOR_BODY7_US_US_2_PREHEADER]] ]
; CHECK-NEXT:    [[XR_1103_US_US_2:%.*]] = phi double [ [[XR_2_US_US_2:%.*]], [[FOR_BODY7_US_US_2]] ], [ [[XR_2_US_US_1_LCSSA]], [[FOR_BODY7_US_US_2_PREHEADER]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_I, i64 0, i64 0, i64 2, i64 [[INDVARS_IV116_2]], i64 0
; CHECK-NEXT:    [[COUNT_I_US_US_2:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 2, i64 [[INDVARS_IV116_2]], i32 2
; CHECK-NEXT:    [[TMP34:%.*]] = load i64, ptr [[COUNT_I_US_US_2]], align 8, !tbaa [[TBAA14]]
; CHECK-NEXT:    [[CONV_I_US_US_2:%.*]] = uitofp i64 [[TMP34]] to double
; CHECK-NEXT:    [[DIV_I_US_US_2:%.*]] = fmul fast double [[CONV_I_US_US_2]], 3.125000e-02
; CHECK-NEXT:    [[CMP3_I_US_US_2:%.*]] = fcmp fast ogt double [[DIV_I_US_US_2]], 1.000000e+00
; CHECK-NEXT:    [[COND11_I_US_US_2:%.*]] = select fast i1 [[CMP3_I_US_US_2]], double 1.000000e+00, double [[DIV_I_US_US_2]]
; CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr [[TMP33]], align 8, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL_I_US_US_2:%.*]] = mul nsw i32 [[TMP35]], [[SPEC_SELECT_I_US_US]]
; CHECK-NEXT:    [[SHR_I_US_US_2:%.*]] = ashr i32 [[MUL_I_US_US_2]], 4
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_I, i64 0, i64 0, i64 2, i64 [[INDVARS_IV116_2]], i64 1
; CHECK-NEXT:    [[TMP37:%.*]] = load i32, ptr [[TMP36]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ADD_I_US_US_2:%.*]] = add nsw i32 [[SHR_I_US_US_2]], [[TMP37]]
; CHECK-NEXT:    [[TMP38:%.*]] = icmp sgt i32 [[ADD_I_US_US_2]], 0
; CHECK-NEXT:    [[COND18_I_US_US_2:%.*]] = select i1 [[TMP38]], i32 [[ADD_I_US_US_2]], i32 0
; CHECK-NEXT:    [[CMP19_I_US_US_2:%.*]] = icmp ult i32 [[COND18_I_US_US_2]], 127
; CHECK-NEXT:    [[COND30_I_US_US_2:%.*]] = select i1 [[CMP19_I_US_US_2]], i32 [[COND18_I_US_US_2]], i32 127
; CHECK-NEXT:    [[MPS_I_US_US_2:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 2, i64 [[INDVARS_IV116_2]], i32 1
; CHECK-NEXT:    [[TMP39:%.*]] = load i8, ptr [[MPS_I_US_US_2]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TOBOOL_NOT_I_US_US_2:%.*]] = icmp eq i8 [[TMP39]], 0
; CHECK-NEXT:    [[STATE36_I_US_US_2:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 2, i64 [[INDVARS_IV116_2]], i32 0
; CHECK-NEXT:    [[TMP40:%.*]] = load i16, ptr [[STATE36_I_US_US_2]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37_I_US_US_2:%.*]] = zext i16 [[TMP40]] to i32
; CHECK-NEXT:    [[ADD34_I_US_US_2:%.*]] = add nuw nsw i32 [[CONV37_I_US_US_2]], 64
; CHECK-NEXT:    [[SUB_I_US_US_2:%.*]] = sub nsw i32 63, [[CONV37_I_US_US_2]]
; CHECK-NEXT:    [[COND39_I_US_US_2:%.*]] = select i1 [[TOBOOL_NOT_I_US_US_2]], i32 [[SUB_I_US_US_2]], i32 [[ADD34_I_US_US_2]]
; CHECK-NEXT:    [[IDXPROM_I_US_US_2:%.*]] = sext i32 [[COND39_I_US_US_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX40_I_US_US_2:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM_I_US_US_2]]
; CHECK-NEXT:    [[TMP41:%.*]] = load double, ptr [[ARRAYIDX40_I_US_US_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[IDXPROM42_I_US_US_2:%.*]] = zext i32 [[COND30_I_US_US_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX43_I_US_US_2:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM42_I_US_US_2]]
; CHECK-NEXT:    [[TMP42:%.*]] = load double, ptr [[ARRAYIDX43_I_US_US_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[TMP43:%.*]] = fneg fast double [[COND11_I_US_US_2]]
; CHECK-NEXT:    [[TMP44:%.*]] = fmul fast double [[TMP41]], [[TMP43]]
; CHECK-NEXT:    [[SUB45_I_US_US_2:%.*]] = fmul fast double [[TMP44]], [[TMP42]]
; CHECK-NEXT:    [[SUB46_I_US_US_2:%.*]] = sub nsw i32 127, [[COND39_I_US_US_2]]
; CHECK-NEXT:    [[IDXPROM47_I_US_US_2:%.*]] = sext i32 [[SUB46_I_US_US_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX48_I_US_US_2:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM47_I_US_US_2]]
; CHECK-NEXT:    [[TMP45:%.*]] = load double, ptr [[ARRAYIDX48_I_US_US_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL49_I_US_US_2:%.*]] = fmul fast double [[TMP45]], [[COND11_I_US_US_2]]
; CHECK-NEXT:    [[SUB50_I_US_US_2:%.*]] = xor i32 [[COND30_I_US_US_2]], 127
; CHECK-NEXT:    [[IDXPROM51_I_US_US_2:%.*]] = zext i32 [[SUB50_I_US_US_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX52_I_US_US_2:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM51_I_US_US_2]]
; CHECK-NEXT:    [[TMP46:%.*]] = load double, ptr [[ARRAYIDX52_I_US_US_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL53_I_US_US_2:%.*]] = fmul fast double [[MUL49_I_US_US_2]], [[TMP46]]
; CHECK-NEXT:    [[SUB54_I_US_US_2:%.*]] = fsub fast double [[SUB45_I_US_US_2]], [[MUL53_I_US_US_2]]
; CHECK-NEXT:    [[XR_2_US_US_2]] = fadd fast double [[SUB54_I_US_US_2]], [[XR_1103_US_US_2]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT117_2]] = add nuw nsw i64 [[INDVARS_IV116_2]], 1
; CHECK-NEXT:    [[EXITCOND119_2_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT117_2]], 11
; CHECK-NEXT:    br i1 [[EXITCOND119_2_NOT]], label [[FOR_END35_LOOPEXIT:%.*]], label [[FOR_BODY7_US_US_2]], !llvm.loop [[LOOP25]]
; CHECK:       for.body7:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY7]] ], [ 0, [[FOR_BODY7_PREHEADER]] ]
; CHECK-NEXT:    [[XR_1103:%.*]] = phi double [ [[XR_2:%.*]], [[FOR_BODY7]] ], [ 0.000000e+00, [[FOR_BODY7_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX30:%.*]] = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_P, i64 0, i64 [[INDVARS_IV124]], i64 0, i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[COUNT_I68:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 0, i64 [[INDVARS_IV]], i32 2
; CHECK-NEXT:    [[TMP47:%.*]] = load i64, ptr [[COUNT_I68]], align 8, !tbaa [[TBAA14]]
; CHECK-NEXT:    [[CONV_I69:%.*]] = uitofp i64 [[TMP47]] to double
; CHECK-NEXT:    [[DIV_I70:%.*]] = fmul fast double [[CONV_I69]], 3.125000e-02
; CHECK-NEXT:    [[CMP3_I71:%.*]] = fcmp fast ogt double [[DIV_I70]], 1.000000e+00
; CHECK-NEXT:    [[COND11_I72:%.*]] = select fast i1 [[CMP3_I71]], double 1.000000e+00, double [[DIV_I70]]
; CHECK-NEXT:    [[TMP48:%.*]] = load i32, ptr [[ARRAYIDX30]], align 8, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL_I73:%.*]] = mul nsw i32 [[TMP48]], [[SPEC_SELECT_I_US_US]]
; CHECK-NEXT:    [[SHR_I74:%.*]] = ashr i32 [[MUL_I73]], 4
; CHECK-NEXT:    [[ARRAYIDX12_I75:%.*]] = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_P, i64 0, i64 [[INDVARS_IV124]], i64 0, i64 [[INDVARS_IV]], i64 1
; CHECK-NEXT:    [[TMP49:%.*]] = load i32, ptr [[ARRAYIDX12_I75]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ADD_I76:%.*]] = add nsw i32 [[SHR_I74]], [[TMP49]]
; CHECK-NEXT:    [[TMP50:%.*]] = icmp sgt i32 [[ADD_I76]], 0
; CHECK-NEXT:    [[COND18_I77:%.*]] = select i1 [[TMP50]], i32 [[ADD_I76]], i32 0
; CHECK-NEXT:    [[CMP19_I78:%.*]] = icmp ult i32 [[COND18_I77]], 127
; CHECK-NEXT:    [[COND30_I79:%.*]] = select i1 [[CMP19_I78]], i32 [[COND18_I77]], i32 127
; CHECK-NEXT:    [[MPS_I80:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 0, i64 [[INDVARS_IV]], i32 1
; CHECK-NEXT:    [[TMP51:%.*]] = load i8, ptr [[MPS_I80]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TOBOOL_NOT_I81:%.*]] = icmp eq i8 [[TMP51]], 0
; CHECK-NEXT:    [[STATE36_I82:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 0, i64 [[INDVARS_IV]], i32 0
; CHECK-NEXT:    [[TMP52:%.*]] = load i16, ptr [[STATE36_I82]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37_I83:%.*]] = zext i16 [[TMP52]] to i32
; CHECK-NEXT:    [[ADD34_I84:%.*]] = add nuw nsw i32 [[CONV37_I83]], 64
; CHECK-NEXT:    [[SUB_I85:%.*]] = sub nsw i32 63, [[CONV37_I83]]
; CHECK-NEXT:    [[COND39_I86:%.*]] = select i1 [[TOBOOL_NOT_I81]], i32 [[SUB_I85]], i32 [[ADD34_I84]]
; CHECK-NEXT:    [[IDXPROM_I87:%.*]] = sext i32 [[COND39_I86]] to i64
; CHECK-NEXT:    [[ARRAYIDX40_I88:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM_I87]]
; CHECK-NEXT:    [[TMP53:%.*]] = load double, ptr [[ARRAYIDX40_I88]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[IDXPROM42_I89:%.*]] = zext i32 [[COND30_I79]] to i64
; CHECK-NEXT:    [[ARRAYIDX43_I90:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM42_I89]]
; CHECK-NEXT:    [[TMP54:%.*]] = load double, ptr [[ARRAYIDX43_I90]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[TMP55:%.*]] = fneg fast double [[COND11_I72]]
; CHECK-NEXT:    [[TMP56:%.*]] = fmul fast double [[TMP53]], [[TMP55]]
; CHECK-NEXT:    [[SUB45_I91:%.*]] = fmul fast double [[TMP56]], [[TMP54]]
; CHECK-NEXT:    [[SUB46_I92:%.*]] = sub nsw i32 127, [[COND39_I86]]
; CHECK-NEXT:    [[IDXPROM47_I93:%.*]] = sext i32 [[SUB46_I92]] to i64
; CHECK-NEXT:    [[ARRAYIDX48_I94:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM47_I93]]
; CHECK-NEXT:    [[TMP57:%.*]] = load double, ptr [[ARRAYIDX48_I94]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL49_I95:%.*]] = fmul fast double [[TMP57]], [[COND11_I72]]
; CHECK-NEXT:    [[SUB50_I96:%.*]] = xor i32 [[COND30_I79]], 127
; CHECK-NEXT:    [[IDXPROM51_I97:%.*]] = zext i32 [[SUB50_I96]] to i64
; CHECK-NEXT:    [[ARRAYIDX52_I98:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM51_I97]]
; CHECK-NEXT:    [[TMP58:%.*]] = load double, ptr [[ARRAYIDX52_I98]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL53_I99:%.*]] = fmul fast double [[MUL49_I95]], [[TMP58]]
; CHECK-NEXT:    [[SUB54_I100:%.*]] = fsub fast double [[SUB45_I91]], [[MUL53_I99]]
; CHECK-NEXT:    [[XR_2]] = fadd fast double [[SUB54_I100]], [[XR_1103]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 11
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_BODY7_1_PREHEADER:%.*]], label [[FOR_BODY7]], !llvm.loop [[LOOP25]]
; CHECK:       for.body7.1.preheader:
; CHECK-NEXT:    [[XR_2_LCSSA:%.*]] = phi double [ [[XR_2]], [[FOR_BODY7]] ]
; CHECK-NEXT:    br label [[FOR_BODY7_1:%.*]]
; CHECK:       for.body7.1:
; CHECK-NEXT:    [[INDVARS_IV_1:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_1:%.*]], [[FOR_BODY7_1]] ], [ 0, [[FOR_BODY7_1_PREHEADER]] ]
; CHECK-NEXT:    [[XR_1103_1:%.*]] = phi double [ [[XR_2_1:%.*]], [[FOR_BODY7_1]] ], [ [[XR_2_LCSSA]], [[FOR_BODY7_1_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX30_1:%.*]] = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_P, i64 0, i64 [[INDVARS_IV124]], i64 1, i64 [[INDVARS_IV_1]], i64 0
; CHECK-NEXT:    [[COUNT_I68_1:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 1, i64 [[INDVARS_IV_1]], i32 2
; CHECK-NEXT:    [[TMP59:%.*]] = load i64, ptr [[COUNT_I68_1]], align 8, !tbaa [[TBAA14]]
; CHECK-NEXT:    [[CONV_I69_1:%.*]] = uitofp i64 [[TMP59]] to double
; CHECK-NEXT:    [[DIV_I70_1:%.*]] = fmul fast double [[CONV_I69_1]], 3.125000e-02
; CHECK-NEXT:    [[CMP3_I71_1:%.*]] = fcmp fast ogt double [[DIV_I70_1]], 1.000000e+00
; CHECK-NEXT:    [[COND11_I72_1:%.*]] = select fast i1 [[CMP3_I71_1]], double 1.000000e+00, double [[DIV_I70_1]]
; CHECK-NEXT:    [[TMP60:%.*]] = load i32, ptr [[ARRAYIDX30_1]], align 8, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL_I73_1:%.*]] = mul nsw i32 [[TMP60]], [[SPEC_SELECT_I_US_US]]
; CHECK-NEXT:    [[SHR_I74_1:%.*]] = ashr i32 [[MUL_I73_1]], 4
; CHECK-NEXT:    [[ARRAYIDX12_I75_1:%.*]] = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_P, i64 0, i64 [[INDVARS_IV124]], i64 1, i64 [[INDVARS_IV_1]], i64 1
; CHECK-NEXT:    [[TMP61:%.*]] = load i32, ptr [[ARRAYIDX12_I75_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ADD_I76_1:%.*]] = add nsw i32 [[SHR_I74_1]], [[TMP61]]
; CHECK-NEXT:    [[TMP62:%.*]] = icmp sgt i32 [[ADD_I76_1]], 0
; CHECK-NEXT:    [[COND18_I77_1:%.*]] = select i1 [[TMP62]], i32 [[ADD_I76_1]], i32 0
; CHECK-NEXT:    [[CMP19_I78_1:%.*]] = icmp ult i32 [[COND18_I77_1]], 127
; CHECK-NEXT:    [[COND30_I79_1:%.*]] = select i1 [[CMP19_I78_1]], i32 [[COND18_I77_1]], i32 127
; CHECK-NEXT:    [[MPS_I80_1:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 1, i64 [[INDVARS_IV_1]], i32 1
; CHECK-NEXT:    [[TMP63:%.*]] = load i8, ptr [[MPS_I80_1]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TOBOOL_NOT_I81_1:%.*]] = icmp eq i8 [[TMP63]], 0
; CHECK-NEXT:    [[STATE36_I82_1:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 1, i64 [[INDVARS_IV_1]], i32 0
; CHECK-NEXT:    [[TMP64:%.*]] = load i16, ptr [[STATE36_I82_1]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37_I83_1:%.*]] = zext i16 [[TMP64]] to i32
; CHECK-NEXT:    [[ADD34_I84_1:%.*]] = add nuw nsw i32 [[CONV37_I83_1]], 64
; CHECK-NEXT:    [[SUB_I85_1:%.*]] = sub nsw i32 63, [[CONV37_I83_1]]
; CHECK-NEXT:    [[COND39_I86_1:%.*]] = select i1 [[TOBOOL_NOT_I81_1]], i32 [[SUB_I85_1]], i32 [[ADD34_I84_1]]
; CHECK-NEXT:    [[IDXPROM_I87_1:%.*]] = sext i32 [[COND39_I86_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX40_I88_1:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM_I87_1]]
; CHECK-NEXT:    [[TMP65:%.*]] = load double, ptr [[ARRAYIDX40_I88_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[IDXPROM42_I89_1:%.*]] = zext i32 [[COND30_I79_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX43_I90_1:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM42_I89_1]]
; CHECK-NEXT:    [[TMP66:%.*]] = load double, ptr [[ARRAYIDX43_I90_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[TMP67:%.*]] = fneg fast double [[COND11_I72_1]]
; CHECK-NEXT:    [[TMP68:%.*]] = fmul fast double [[TMP65]], [[TMP67]]
; CHECK-NEXT:    [[SUB45_I91_1:%.*]] = fmul fast double [[TMP68]], [[TMP66]]
; CHECK-NEXT:    [[SUB46_I92_1:%.*]] = sub nsw i32 127, [[COND39_I86_1]]
; CHECK-NEXT:    [[IDXPROM47_I93_1:%.*]] = sext i32 [[SUB46_I92_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX48_I94_1:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM47_I93_1]]
; CHECK-NEXT:    [[TMP69:%.*]] = load double, ptr [[ARRAYIDX48_I94_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL49_I95_1:%.*]] = fmul fast double [[TMP69]], [[COND11_I72_1]]
; CHECK-NEXT:    [[SUB50_I96_1:%.*]] = xor i32 [[COND30_I79_1]], 127
; CHECK-NEXT:    [[IDXPROM51_I97_1:%.*]] = zext i32 [[SUB50_I96_1]] to i64
; CHECK-NEXT:    [[ARRAYIDX52_I98_1:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM51_I97_1]]
; CHECK-NEXT:    [[TMP70:%.*]] = load double, ptr [[ARRAYIDX52_I98_1]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL53_I99_1:%.*]] = fmul fast double [[MUL49_I95_1]], [[TMP70]]
; CHECK-NEXT:    [[SUB54_I100_1:%.*]] = fsub fast double [[SUB45_I91_1]], [[MUL53_I99_1]]
; CHECK-NEXT:    [[XR_2_1]] = fadd fast double [[SUB54_I100_1]], [[XR_1103_1]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_1]] = add nuw nsw i64 [[INDVARS_IV_1]], 1
; CHECK-NEXT:    [[EXITCOND_1_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT_1]], 11
; CHECK-NEXT:    br i1 [[EXITCOND_1_NOT]], label [[FOR_BODY7_2_PREHEADER:%.*]], label [[FOR_BODY7_1]], !llvm.loop [[LOOP25]]
; CHECK:       for.body7.2.preheader:
; CHECK-NEXT:    [[XR_2_1_LCSSA:%.*]] = phi double [ [[XR_2_1]], [[FOR_BODY7_1]] ]
; CHECK-NEXT:    br label [[FOR_BODY7_2:%.*]]
; CHECK:       for.body7.2:
; CHECK-NEXT:    [[INDVARS_IV_2:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_2:%.*]], [[FOR_BODY7_2]] ], [ 0, [[FOR_BODY7_2_PREHEADER]] ]
; CHECK-NEXT:    [[XR_1103_2:%.*]] = phi double [ [[XR_2_2:%.*]], [[FOR_BODY7_2]] ], [ [[XR_2_1_LCSSA]], [[FOR_BODY7_2_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX30_2:%.*]] = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_P, i64 0, i64 [[INDVARS_IV124]], i64 2, i64 [[INDVARS_IV_2]], i64 0
; CHECK-NEXT:    [[COUNT_I68_2:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 2, i64 [[INDVARS_IV_2]], i32 2
; CHECK-NEXT:    [[TMP71:%.*]] = load i64, ptr [[COUNT_I68_2]], align 8, !tbaa [[TBAA14]]
; CHECK-NEXT:    [[CONV_I69_2:%.*]] = uitofp i64 [[TMP71]] to double
; CHECK-NEXT:    [[DIV_I70_2:%.*]] = fmul fast double [[CONV_I69_2]], 3.125000e-02
; CHECK-NEXT:    [[CMP3_I71_2:%.*]] = fcmp fast ogt double [[DIV_I70_2]], 1.000000e+00
; CHECK-NEXT:    [[COND11_I72_2:%.*]] = select fast i1 [[CMP3_I71_2]], double 1.000000e+00, double [[DIV_I70_2]]
; CHECK-NEXT:    [[TMP72:%.*]] = load i32, ptr [[ARRAYIDX30_2]], align 8, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[MUL_I73_2:%.*]] = mul nsw i32 [[TMP72]], [[SPEC_SELECT_I_US_US]]
; CHECK-NEXT:    [[SHR_I74_2:%.*]] = ashr i32 [[MUL_I73_2]], 4
; CHECK-NEXT:    [[ARRAYIDX12_I75_2:%.*]] = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], ptr @INIT_MB_TYPE_P, i64 0, i64 [[INDVARS_IV124]], i64 2, i64 [[INDVARS_IV_2]], i64 1
; CHECK-NEXT:    [[TMP73:%.*]] = load i32, ptr [[ARRAYIDX12_I75_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ADD_I76_2:%.*]] = add nsw i32 [[SHR_I74_2]], [[TMP73]]
; CHECK-NEXT:    [[TMP74:%.*]] = icmp sgt i32 [[ADD_I76_2]], 0
; CHECK-NEXT:    [[COND18_I77_2:%.*]] = select i1 [[TMP74]], i32 [[ADD_I76_2]], i32 0
; CHECK-NEXT:    [[CMP19_I78_2:%.*]] = icmp ult i32 [[COND18_I77_2]], 127
; CHECK-NEXT:    [[COND30_I79_2:%.*]] = select i1 [[CMP19_I78_2]], i32 [[COND18_I77_2]], i32 127
; CHECK-NEXT:    [[MPS_I80_2:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 2, i64 [[INDVARS_IV_2]], i32 1
; CHECK-NEXT:    [[TMP75:%.*]] = load i8, ptr [[MPS_I80_2]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TOBOOL_NOT_I81_2:%.*]] = icmp eq i8 [[TMP75]], 0
; CHECK-NEXT:    [[STATE36_I82_2:%.*]] = getelementptr inbounds [[STRUCT_MOTIONINFOCONTEXTS]], ptr [[MC]], i64 0, i32 0, i64 2, i64 [[INDVARS_IV_2]], i32 0
; CHECK-NEXT:    [[TMP76:%.*]] = load i16, ptr [[STATE36_I82_2]], align 8, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37_I83_2:%.*]] = zext i16 [[TMP76]] to i32
; CHECK-NEXT:    [[ADD34_I84_2:%.*]] = add nuw nsw i32 [[CONV37_I83_2]], 64
; CHECK-NEXT:    [[SUB_I85_2:%.*]] = sub nsw i32 63, [[CONV37_I83_2]]
; CHECK-NEXT:    [[COND39_I86_2:%.*]] = select i1 [[TOBOOL_NOT_I81_2]], i32 [[SUB_I85_2]], i32 [[ADD34_I84_2]]
; CHECK-NEXT:    [[IDXPROM_I87_2:%.*]] = sext i32 [[COND39_I86_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX40_I88_2:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM_I87_2]]
; CHECK-NEXT:    [[TMP77:%.*]] = load double, ptr [[ARRAYIDX40_I88_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[IDXPROM42_I89_2:%.*]] = zext i32 [[COND30_I79_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX43_I90_2:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM42_I89_2]]
; CHECK-NEXT:    [[TMP78:%.*]] = load double, ptr [[ARRAYIDX43_I90_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[TMP79:%.*]] = fneg fast double [[COND11_I72_2]]
; CHECK-NEXT:    [[TMP80:%.*]] = fmul fast double [[TMP77]], [[TMP79]]
; CHECK-NEXT:    [[SUB45_I91_2:%.*]] = fmul fast double [[TMP80]], [[TMP78]]
; CHECK-NEXT:    [[SUB46_I92_2:%.*]] = sub nsw i32 127, [[COND39_I86_2]]
; CHECK-NEXT:    [[IDXPROM47_I93_2:%.*]] = sext i32 [[SUB46_I92_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX48_I94_2:%.*]] = getelementptr inbounds [128 x double], ptr @probability, i64 0, i64 [[IDXPROM47_I93_2]]
; CHECK-NEXT:    [[TMP81:%.*]] = load double, ptr [[ARRAYIDX48_I94_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL49_I95_2:%.*]] = fmul fast double [[TMP81]], [[COND11_I72_2]]
; CHECK-NEXT:    [[SUB50_I96_2:%.*]] = xor i32 [[COND30_I79_2]], 127
; CHECK-NEXT:    [[IDXPROM51_I97_2:%.*]] = zext i32 [[SUB50_I96_2]] to i64
; CHECK-NEXT:    [[ARRAYIDX52_I98_2:%.*]] = getelementptr inbounds [128 x double], ptr @entropy, i64 0, i64 [[IDXPROM51_I97_2]]
; CHECK-NEXT:    [[TMP82:%.*]] = load double, ptr [[ARRAYIDX52_I98_2]], align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[MUL53_I99_2:%.*]] = fmul fast double [[MUL49_I95_2]], [[TMP82]]
; CHECK-NEXT:    [[SUB54_I100_2:%.*]] = fsub fast double [[SUB45_I91_2]], [[MUL53_I99_2]]
; CHECK-NEXT:    [[XR_2_2]] = fadd fast double [[SUB54_I100_2]], [[XR_1103_2]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_2]] = add nuw nsw i64 [[INDVARS_IV_2]], 1
; CHECK-NEXT:    [[EXITCOND_2_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT_2]], 11
; CHECK-NEXT:    br i1 [[EXITCOND_2_NOT]], label [[FOR_END35_LOOPEXIT129:%.*]], label [[FOR_BODY7_2]], !llvm.loop [[LOOP25]]
; CHECK:       for.end35.loopexit:
; CHECK-NEXT:    [[XR_2_US_US_2_LCSSA:%.*]] = phi double [ [[XR_2_US_US_2]], [[FOR_BODY7_US_US_2]] ]
; CHECK-NEXT:    br label [[FOR_END35:%.*]]
; CHECK:       for.end35.loopexit129:
; CHECK-NEXT:    [[XR_2_2_LCSSA:%.*]] = phi double [ [[XR_2_2]], [[FOR_BODY7_2]] ]
; CHECK-NEXT:    br label [[FOR_END35]]
; CHECK:       for.end35:
; CHECK-NEXT:    [[DOTUS_PHI106:%.*]] = phi double [ [[XR_2_US_US_2_LCSSA]], [[FOR_END35_LOOPEXIT]] ], [ [[XR_2_2_LCSSA]], [[FOR_END35_LOOPEXIT129]] ]
; CHECK-NEXT:    [[CMP36:%.*]] = fcmp fast olt double [[DOTUS_PHI106]], [[MIN_XR_0109]]
; CHECK-NEXT:    br i1 [[CMP36]], label [[IF_THEN37:%.*]], label [[FOR_INC39:%.*]]
; CHECK:       if.then37:
; CHECK-NEXT:    [[TMP83:%.*]] = trunc i64 [[INDVARS_IV124]] to i32
; CHECK-NEXT:    store i32 [[TMP83]], ptr [[MNUMBER:%.*]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    br label [[FOR_INC39]]
; CHECK:       for.inc39:
; CHECK-NEXT:    [[MIN_XR_1]] = phi double [ [[DOTUS_PHI106]], [[IF_THEN37]] ], [ [[MIN_XR_0109]], [[FOR_END35]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT125]] = add nuw nsw i64 [[INDVARS_IV124]], 1
; CHECK-NEXT:    [[EXITCOND127_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT125]], [[COND]]
; CHECK-NEXT:    br i1 [[EXITCOND127_NOT]], label [[FOR_END41:%.*]], label [[FOR_INC39_FOR_COND2_PREHEADER_CRIT_EDGE]], !llvm.loop [[LOOP27:![0-9]+]]
; CHECK:       for.inc39.for.cond2.preheader_crit_edge:
; CHECK-NEXT:    [[DOTPRE]] = load i32, ptr [[TYPE]], align 8, !tbaa [[TBAA8]]
; CHECK-NEXT:    br label [[FOR_COND2_PREHEADER]]
; CHECK:       for.end41:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load %struct.ImageParameters*, %struct.ImageParameters** @img, align 8, !tbaa !4
  %type = getelementptr inbounds %struct.ImageParameters, %struct.ImageParameters* %0, i64 0, i32 6
  %1 = load i32, i32* %type, align 8, !tbaa !21
  %cmp = icmp eq i32 %1, 2
  %cond = select i1 %cmp, i64 1, i64 3
  %qp1.i66 = getelementptr inbounds %struct.ImageParameters, %struct.ImageParameters* %0, i64 0, i32 10
  br label %for.cond2.preheader

for.cond2.preheader:                              ; preds = %for.inc39.for.cond2.preheader_crit_edge, %entry
  %2 = phi i32 [ %1, %entry ], [ %.pre, %for.inc39.for.cond2.preheader_crit_edge ]
  %indvars.iv124 = phi i64 [ 0, %entry ], [ %indvars.iv.next125, %for.inc39.for.cond2.preheader_crit_edge ]
  %min_xr.0109 = phi double [ 1.000000e+30, %entry ], [ %min_xr.1, %for.inc39.for.cond2.preheader_crit_edge ]
  %cmp9 = icmp eq i32 %2, 2
  %3 = load i32, i32* %qp1.i66, align 8, !tbaa !8
  %4 = icmp sgt i32 %3, 0
  %spec.select.i.us.us = select i1 %4, i32 %3, i32 0
  br i1 %cmp9, label %for.body7.us.us.preheader, label %for.body7.preheader

for.body7.preheader:                              ; preds = %for.cond2.preheader
  br label %for.body7

for.body7.us.us.preheader:                        ; preds = %for.cond2.preheader
  br label %for.body7.us.us

for.body7.us.us:                                  ; preds = %for.body7.us.us.preheader, %for.body7.us.us
  %indvars.iv116 = phi i64 [ %indvars.iv.next117, %for.body7.us.us ], [ 0, %for.body7.us.us.preheader ]
  %xr.1103.us.us = phi double [ %xr.2.us.us, %for.body7.us.us ], [ 0.000000e+00, %for.body7.us.us.preheader ]
  %5 = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], [1 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_I, i64 0, i64 0, i64 0, i64 %indvars.iv116, i64 0
  %count.i.us.us = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 0, i64 %indvars.iv116, i32 2
  %6 = load i64, i64* %count.i.us.us, align 8, !tbaa !13
  %conv.i.us.us = uitofp i64 %6 to double
  %div.i.us.us = fmul fast double %conv.i.us.us, 3.125000e-02
  %cmp3.i.us.us = fcmp fast ogt double %div.i.us.us, 1.000000e+00
  %cond11.i.us.us = select fast i1 %cmp3.i.us.us, double 1.000000e+00, double %div.i.us.us
  %7 = load i32, i32* %5, align 8, !tbaa !17
  %mul.i.us.us = mul nsw i32 %7, %spec.select.i.us.us
  %shr.i.us.us = ashr i32 %mul.i.us.us, 4
  %8 = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], [1 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_I, i64 0, i64 0, i64 0, i64 %indvars.iv116, i64 1
  %9 = load i32, i32* %8, align 4, !tbaa !17
  %add.i.us.us = add nsw i32 %shr.i.us.us, %9
  %10 = icmp sgt i32 %add.i.us.us, 0
  %cond18.i.us.us = select i1 %10, i32 %add.i.us.us, i32 0
  %cmp19.i.us.us = icmp ult i32 %cond18.i.us.us, 127
  %cond30.i.us.us = select i1 %cmp19.i.us.us, i32 %cond18.i.us.us, i32 127
  %MPS.i.us.us = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 0, i64 %indvars.iv116, i32 1
  %11 = load i8, i8* %MPS.i.us.us, align 2, !tbaa !18
  %tobool.not.i.us.us = icmp eq i8 %11, 0
  %state36.i.us.us = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 0, i64 %indvars.iv116, i32 0
  %12 = load i16, i16* %state36.i.us.us, align 8, !tbaa !19
  %conv37.i.us.us = zext i16 %12 to i32
  %add34.i.us.us = add nuw nsw i32 %conv37.i.us.us, 64
  %sub.i.us.us = sub nsw i32 63, %conv37.i.us.us
  %cond39.i.us.us = select i1 %tobool.not.i.us.us, i32 %sub.i.us.us, i32 %add34.i.us.us
  %idxprom.i.us.us = sext i32 %cond39.i.us.us to i64
  %arrayidx40.i.us.us = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom.i.us.us
  %13 = load double, double* %arrayidx40.i.us.us, align 8, !tbaa !20
  %idxprom42.i.us.us = zext i32 %cond30.i.us.us to i64
  %arrayidx43.i.us.us = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom42.i.us.us
  %14 = load double, double* %arrayidx43.i.us.us, align 8, !tbaa !20
  %15 = fneg fast double %cond11.i.us.us
  %16 = fmul fast double %13, %15
  %sub45.i.us.us = fmul fast double %16, %14
  %sub46.i.us.us = sub nsw i32 127, %cond39.i.us.us
  %idxprom47.i.us.us = sext i32 %sub46.i.us.us to i64
  %arrayidx48.i.us.us = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom47.i.us.us
  %17 = load double, double* %arrayidx48.i.us.us, align 8, !tbaa !20
  %mul49.i.us.us = fmul fast double %17, %cond11.i.us.us
  %sub50.i.us.us = xor i32 %cond30.i.us.us, 127
  %idxprom51.i.us.us = zext i32 %sub50.i.us.us to i64
  %arrayidx52.i.us.us = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom51.i.us.us
  %18 = load double, double* %arrayidx52.i.us.us, align 8, !tbaa !20
  %mul53.i.us.us = fmul fast double %mul49.i.us.us, %18
  %sub54.i.us.us = fsub fast double %sub45.i.us.us, %mul53.i.us.us
  %xr.2.us.us = fadd fast double %sub54.i.us.us, %xr.1103.us.us
  %indvars.iv.next117 = add nuw nsw i64 %indvars.iv116, 1
  %exitcond119.not = icmp eq i64 %indvars.iv.next117, 11
  br i1 %exitcond119.not, label %for.body7.us.us.1.preheader, label %for.body7.us.us, !llvm.loop !22

for.body7.us.us.1.preheader:                      ; preds = %for.body7.us.us
  %xr.2.us.us.lcssa = phi double [ %xr.2.us.us, %for.body7.us.us ]
  br label %for.body7.us.us.1

for.body7.us.us.1:                                ; preds = %for.body7.us.us.1.preheader, %for.body7.us.us.1
  %indvars.iv116.1 = phi i64 [ %indvars.iv.next117.1, %for.body7.us.us.1 ], [ 0, %for.body7.us.us.1.preheader ]
  %xr.1103.us.us.1 = phi double [ %xr.2.us.us.1, %for.body7.us.us.1 ], [ %xr.2.us.us.lcssa, %for.body7.us.us.1.preheader ]
  %19 = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], [1 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_I, i64 0, i64 0, i64 1, i64 %indvars.iv116.1, i64 0
  %count.i.us.us.1 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 1, i64 %indvars.iv116.1, i32 2
  %20 = load i64, i64* %count.i.us.us.1, align 8, !tbaa !13
  %conv.i.us.us.1 = uitofp i64 %20 to double
  %div.i.us.us.1 = fmul fast double %conv.i.us.us.1, 3.125000e-02
  %cmp3.i.us.us.1 = fcmp fast ogt double %div.i.us.us.1, 1.000000e+00
  %cond11.i.us.us.1 = select fast i1 %cmp3.i.us.us.1, double 1.000000e+00, double %div.i.us.us.1
  %21 = load i32, i32* %19, align 8, !tbaa !17
  %mul.i.us.us.1 = mul nsw i32 %21, %spec.select.i.us.us
  %shr.i.us.us.1 = ashr i32 %mul.i.us.us.1, 4
  %22 = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], [1 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_I, i64 0, i64 0, i64 1, i64 %indvars.iv116.1, i64 1
  %23 = load i32, i32* %22, align 4, !tbaa !17
  %add.i.us.us.1 = add nsw i32 %shr.i.us.us.1, %23
  %24 = icmp sgt i32 %add.i.us.us.1, 0
  %cond18.i.us.us.1 = select i1 %24, i32 %add.i.us.us.1, i32 0
  %cmp19.i.us.us.1 = icmp ult i32 %cond18.i.us.us.1, 127
  %cond30.i.us.us.1 = select i1 %cmp19.i.us.us.1, i32 %cond18.i.us.us.1, i32 127
  %MPS.i.us.us.1 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 1, i64 %indvars.iv116.1, i32 1
  %25 = load i8, i8* %MPS.i.us.us.1, align 2, !tbaa !18
  %tobool.not.i.us.us.1 = icmp eq i8 %25, 0
  %state36.i.us.us.1 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 1, i64 %indvars.iv116.1, i32 0
  %26 = load i16, i16* %state36.i.us.us.1, align 8, !tbaa !19
  %conv37.i.us.us.1 = zext i16 %26 to i32
  %add34.i.us.us.1 = add nuw nsw i32 %conv37.i.us.us.1, 64
  %sub.i.us.us.1 = sub nsw i32 63, %conv37.i.us.us.1
  %cond39.i.us.us.1 = select i1 %tobool.not.i.us.us.1, i32 %sub.i.us.us.1, i32 %add34.i.us.us.1
  %idxprom.i.us.us.1 = sext i32 %cond39.i.us.us.1 to i64
  %arrayidx40.i.us.us.1 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom.i.us.us.1
  %27 = load double, double* %arrayidx40.i.us.us.1, align 8, !tbaa !20
  %idxprom42.i.us.us.1 = zext i32 %cond30.i.us.us.1 to i64
  %arrayidx43.i.us.us.1 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom42.i.us.us.1
  %28 = load double, double* %arrayidx43.i.us.us.1, align 8, !tbaa !20
  %29 = fneg fast double %cond11.i.us.us.1
  %30 = fmul fast double %27, %29
  %sub45.i.us.us.1 = fmul fast double %30, %28
  %sub46.i.us.us.1 = sub nsw i32 127, %cond39.i.us.us.1
  %idxprom47.i.us.us.1 = sext i32 %sub46.i.us.us.1 to i64
  %arrayidx48.i.us.us.1 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom47.i.us.us.1
  %31 = load double, double* %arrayidx48.i.us.us.1, align 8, !tbaa !20
  %mul49.i.us.us.1 = fmul fast double %31, %cond11.i.us.us.1
  %sub50.i.us.us.1 = xor i32 %cond30.i.us.us.1, 127
  %idxprom51.i.us.us.1 = zext i32 %sub50.i.us.us.1 to i64
  %arrayidx52.i.us.us.1 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom51.i.us.us.1
  %32 = load double, double* %arrayidx52.i.us.us.1, align 8, !tbaa !20
  %mul53.i.us.us.1 = fmul fast double %mul49.i.us.us.1, %32
  %sub54.i.us.us.1 = fsub fast double %sub45.i.us.us.1, %mul53.i.us.us.1
  %xr.2.us.us.1 = fadd fast double %sub54.i.us.us.1, %xr.1103.us.us.1
  %indvars.iv.next117.1 = add nuw nsw i64 %indvars.iv116.1, 1
  %exitcond119.1.not = icmp eq i64 %indvars.iv.next117.1, 11
  br i1 %exitcond119.1.not, label %for.body7.us.us.2.preheader, label %for.body7.us.us.1, !llvm.loop !22

for.body7.us.us.2.preheader:                      ; preds = %for.body7.us.us.1
  %xr.2.us.us.1.lcssa = phi double [ %xr.2.us.us.1, %for.body7.us.us.1 ]
  br label %for.body7.us.us.2

for.body7.us.us.2:                                ; preds = %for.body7.us.us.2.preheader, %for.body7.us.us.2
  %indvars.iv116.2 = phi i64 [ %indvars.iv.next117.2, %for.body7.us.us.2 ], [ 0, %for.body7.us.us.2.preheader ]
  %xr.1103.us.us.2 = phi double [ %xr.2.us.us.2, %for.body7.us.us.2 ], [ %xr.2.us.us.1.lcssa, %for.body7.us.us.2.preheader ]
  %33 = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], [1 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_I, i64 0, i64 0, i64 2, i64 %indvars.iv116.2, i64 0
  %count.i.us.us.2 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 2, i64 %indvars.iv116.2, i32 2
  %34 = load i64, i64* %count.i.us.us.2, align 8, !tbaa !13
  %conv.i.us.us.2 = uitofp i64 %34 to double
  %div.i.us.us.2 = fmul fast double %conv.i.us.us.2, 3.125000e-02
  %cmp3.i.us.us.2 = fcmp fast ogt double %div.i.us.us.2, 1.000000e+00
  %cond11.i.us.us.2 = select fast i1 %cmp3.i.us.us.2, double 1.000000e+00, double %div.i.us.us.2
  %35 = load i32, i32* %33, align 8, !tbaa !17
  %mul.i.us.us.2 = mul nsw i32 %35, %spec.select.i.us.us
  %shr.i.us.us.2 = ashr i32 %mul.i.us.us.2, 4
  %36 = getelementptr inbounds [1 x [3 x [11 x [2 x i32]]]], [1 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_I, i64 0, i64 0, i64 2, i64 %indvars.iv116.2, i64 1
  %37 = load i32, i32* %36, align 4, !tbaa !17
  %add.i.us.us.2 = add nsw i32 %shr.i.us.us.2, %37
  %38 = icmp sgt i32 %add.i.us.us.2, 0
  %cond18.i.us.us.2 = select i1 %38, i32 %add.i.us.us.2, i32 0
  %cmp19.i.us.us.2 = icmp ult i32 %cond18.i.us.us.2, 127
  %cond30.i.us.us.2 = select i1 %cmp19.i.us.us.2, i32 %cond18.i.us.us.2, i32 127
  %MPS.i.us.us.2 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 2, i64 %indvars.iv116.2, i32 1
  %39 = load i8, i8* %MPS.i.us.us.2, align 2, !tbaa !18
  %tobool.not.i.us.us.2 = icmp eq i8 %39, 0
  %state36.i.us.us.2 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 2, i64 %indvars.iv116.2, i32 0
  %40 = load i16, i16* %state36.i.us.us.2, align 8, !tbaa !19
  %conv37.i.us.us.2 = zext i16 %40 to i32
  %add34.i.us.us.2 = add nuw nsw i32 %conv37.i.us.us.2, 64
  %sub.i.us.us.2 = sub nsw i32 63, %conv37.i.us.us.2
  %cond39.i.us.us.2 = select i1 %tobool.not.i.us.us.2, i32 %sub.i.us.us.2, i32 %add34.i.us.us.2
  %idxprom.i.us.us.2 = sext i32 %cond39.i.us.us.2 to i64
  %arrayidx40.i.us.us.2 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom.i.us.us.2
  %41 = load double, double* %arrayidx40.i.us.us.2, align 8, !tbaa !20
  %idxprom42.i.us.us.2 = zext i32 %cond30.i.us.us.2 to i64
  %arrayidx43.i.us.us.2 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom42.i.us.us.2
  %42 = load double, double* %arrayidx43.i.us.us.2, align 8, !tbaa !20
  %43 = fneg fast double %cond11.i.us.us.2
  %44 = fmul fast double %41, %43
  %sub45.i.us.us.2 = fmul fast double %44, %42
  %sub46.i.us.us.2 = sub nsw i32 127, %cond39.i.us.us.2
  %idxprom47.i.us.us.2 = sext i32 %sub46.i.us.us.2 to i64
  %arrayidx48.i.us.us.2 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom47.i.us.us.2
  %45 = load double, double* %arrayidx48.i.us.us.2, align 8, !tbaa !20
  %mul49.i.us.us.2 = fmul fast double %45, %cond11.i.us.us.2
  %sub50.i.us.us.2 = xor i32 %cond30.i.us.us.2, 127
  %idxprom51.i.us.us.2 = zext i32 %sub50.i.us.us.2 to i64
  %arrayidx52.i.us.us.2 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom51.i.us.us.2
  %46 = load double, double* %arrayidx52.i.us.us.2, align 8, !tbaa !20
  %mul53.i.us.us.2 = fmul fast double %mul49.i.us.us.2, %46
  %sub54.i.us.us.2 = fsub fast double %sub45.i.us.us.2, %mul53.i.us.us.2
  %xr.2.us.us.2 = fadd fast double %sub54.i.us.us.2, %xr.1103.us.us.2
  %indvars.iv.next117.2 = add nuw nsw i64 %indvars.iv116.2, 1
  %exitcond119.2.not = icmp eq i64 %indvars.iv.next117.2, 11
  br i1 %exitcond119.2.not, label %for.end35.loopexit, label %for.body7.us.us.2, !llvm.loop !22

for.body7:                                        ; preds = %for.body7.preheader, %for.body7
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body7 ], [ 0, %for.body7.preheader ]
  %xr.1103 = phi double [ %xr.2, %for.body7 ], [ 0.000000e+00, %for.body7.preheader ]
  %arrayidx30 = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], [3 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_P, i64 0, i64 %indvars.iv124, i64 0, i64 %indvars.iv, i64 0
  %count.i68 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 0, i64 %indvars.iv, i32 2
  %47 = load i64, i64* %count.i68, align 8, !tbaa !13
  %conv.i69 = uitofp i64 %47 to double
  %div.i70 = fmul fast double %conv.i69, 3.125000e-02
  %cmp3.i71 = fcmp fast ogt double %div.i70, 1.000000e+00
  %cond11.i72 = select fast i1 %cmp3.i71, double 1.000000e+00, double %div.i70
  %48 = load i32, i32* %arrayidx30, align 8, !tbaa !17
  %mul.i73 = mul nsw i32 %48, %spec.select.i.us.us
  %shr.i74 = ashr i32 %mul.i73, 4
  %arrayidx12.i75 = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], [3 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_P, i64 0, i64 %indvars.iv124, i64 0, i64 %indvars.iv, i64 1
  %49 = load i32, i32* %arrayidx12.i75, align 4, !tbaa !17
  %add.i76 = add nsw i32 %shr.i74, %49
  %50 = icmp sgt i32 %add.i76, 0
  %cond18.i77 = select i1 %50, i32 %add.i76, i32 0
  %cmp19.i78 = icmp ult i32 %cond18.i77, 127
  %cond30.i79 = select i1 %cmp19.i78, i32 %cond18.i77, i32 127
  %MPS.i80 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 0, i64 %indvars.iv, i32 1
  %51 = load i8, i8* %MPS.i80, align 2, !tbaa !18
  %tobool.not.i81 = icmp eq i8 %51, 0
  %state36.i82 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 0, i64 %indvars.iv, i32 0
  %52 = load i16, i16* %state36.i82, align 8, !tbaa !19
  %conv37.i83 = zext i16 %52 to i32
  %add34.i84 = add nuw nsw i32 %conv37.i83, 64
  %sub.i85 = sub nsw i32 63, %conv37.i83
  %cond39.i86 = select i1 %tobool.not.i81, i32 %sub.i85, i32 %add34.i84
  %idxprom.i87 = sext i32 %cond39.i86 to i64
  %arrayidx40.i88 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom.i87
  %53 = load double, double* %arrayidx40.i88, align 8, !tbaa !20
  %idxprom42.i89 = zext i32 %cond30.i79 to i64
  %arrayidx43.i90 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom42.i89
  %54 = load double, double* %arrayidx43.i90, align 8, !tbaa !20
  %55 = fneg fast double %cond11.i72
  %56 = fmul fast double %53, %55
  %sub45.i91 = fmul fast double %56, %54
  %sub46.i92 = sub nsw i32 127, %cond39.i86
  %idxprom47.i93 = sext i32 %sub46.i92 to i64
  %arrayidx48.i94 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom47.i93
  %57 = load double, double* %arrayidx48.i94, align 8, !tbaa !20
  %mul49.i95 = fmul fast double %57, %cond11.i72
  %sub50.i96 = xor i32 %cond30.i79, 127
  %idxprom51.i97 = zext i32 %sub50.i96 to i64
  %arrayidx52.i98 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom51.i97
  %58 = load double, double* %arrayidx52.i98, align 8, !tbaa !20
  %mul53.i99 = fmul fast double %mul49.i95, %58
  %sub54.i100 = fsub fast double %sub45.i91, %mul53.i99
  %xr.2 = fadd fast double %sub54.i100, %xr.1103
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 11
  br i1 %exitcond.not, label %for.body7.1.preheader, label %for.body7, !llvm.loop !22

for.body7.1.preheader:                            ; preds = %for.body7
  %xr.2.lcssa = phi double [ %xr.2, %for.body7 ]
  br label %for.body7.1

for.body7.1:                                      ; preds = %for.body7.1.preheader, %for.body7.1
  %indvars.iv.1 = phi i64 [ %indvars.iv.next.1, %for.body7.1 ], [ 0, %for.body7.1.preheader ]
  %xr.1103.1 = phi double [ %xr.2.1, %for.body7.1 ], [ %xr.2.lcssa, %for.body7.1.preheader ]
  %arrayidx30.1 = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], [3 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_P, i64 0, i64 %indvars.iv124, i64 1, i64 %indvars.iv.1, i64 0
  %count.i68.1 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 1, i64 %indvars.iv.1, i32 2
  %59 = load i64, i64* %count.i68.1, align 8, !tbaa !13
  %conv.i69.1 = uitofp i64 %59 to double
  %div.i70.1 = fmul fast double %conv.i69.1, 3.125000e-02
  %cmp3.i71.1 = fcmp fast ogt double %div.i70.1, 1.000000e+00
  %cond11.i72.1 = select fast i1 %cmp3.i71.1, double 1.000000e+00, double %div.i70.1
  %60 = load i32, i32* %arrayidx30.1, align 8, !tbaa !17
  %mul.i73.1 = mul nsw i32 %60, %spec.select.i.us.us
  %shr.i74.1 = ashr i32 %mul.i73.1, 4
  %arrayidx12.i75.1 = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], [3 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_P, i64 0, i64 %indvars.iv124, i64 1, i64 %indvars.iv.1, i64 1
  %61 = load i32, i32* %arrayidx12.i75.1, align 4, !tbaa !17
  %add.i76.1 = add nsw i32 %shr.i74.1, %61
  %62 = icmp sgt i32 %add.i76.1, 0
  %cond18.i77.1 = select i1 %62, i32 %add.i76.1, i32 0
  %cmp19.i78.1 = icmp ult i32 %cond18.i77.1, 127
  %cond30.i79.1 = select i1 %cmp19.i78.1, i32 %cond18.i77.1, i32 127
  %MPS.i80.1 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 1, i64 %indvars.iv.1, i32 1
  %63 = load i8, i8* %MPS.i80.1, align 2, !tbaa !18
  %tobool.not.i81.1 = icmp eq i8 %63, 0
  %state36.i82.1 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 1, i64 %indvars.iv.1, i32 0
  %64 = load i16, i16* %state36.i82.1, align 8, !tbaa !19
  %conv37.i83.1 = zext i16 %64 to i32
  %add34.i84.1 = add nuw nsw i32 %conv37.i83.1, 64
  %sub.i85.1 = sub nsw i32 63, %conv37.i83.1
  %cond39.i86.1 = select i1 %tobool.not.i81.1, i32 %sub.i85.1, i32 %add34.i84.1
  %idxprom.i87.1 = sext i32 %cond39.i86.1 to i64
  %arrayidx40.i88.1 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom.i87.1
  %65 = load double, double* %arrayidx40.i88.1, align 8, !tbaa !20
  %idxprom42.i89.1 = zext i32 %cond30.i79.1 to i64
  %arrayidx43.i90.1 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom42.i89.1
  %66 = load double, double* %arrayidx43.i90.1, align 8, !tbaa !20
  %67 = fneg fast double %cond11.i72.1
  %68 = fmul fast double %65, %67
  %sub45.i91.1 = fmul fast double %68, %66
  %sub46.i92.1 = sub nsw i32 127, %cond39.i86.1
  %idxprom47.i93.1 = sext i32 %sub46.i92.1 to i64
  %arrayidx48.i94.1 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom47.i93.1
  %69 = load double, double* %arrayidx48.i94.1, align 8, !tbaa !20
  %mul49.i95.1 = fmul fast double %69, %cond11.i72.1
  %sub50.i96.1 = xor i32 %cond30.i79.1, 127
  %idxprom51.i97.1 = zext i32 %sub50.i96.1 to i64
  %arrayidx52.i98.1 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom51.i97.1
  %70 = load double, double* %arrayidx52.i98.1, align 8, !tbaa !20
  %mul53.i99.1 = fmul fast double %mul49.i95.1, %70
  %sub54.i100.1 = fsub fast double %sub45.i91.1, %mul53.i99.1
  %xr.2.1 = fadd fast double %sub54.i100.1, %xr.1103.1
  %indvars.iv.next.1 = add nuw nsw i64 %indvars.iv.1, 1
  %exitcond.1.not = icmp eq i64 %indvars.iv.next.1, 11
  br i1 %exitcond.1.not, label %for.body7.2.preheader, label %for.body7.1, !llvm.loop !22

for.body7.2.preheader:                            ; preds = %for.body7.1
  %xr.2.1.lcssa = phi double [ %xr.2.1, %for.body7.1 ]
  br label %for.body7.2

for.body7.2:                                      ; preds = %for.body7.2.preheader, %for.body7.2
  %indvars.iv.2 = phi i64 [ %indvars.iv.next.2, %for.body7.2 ], [ 0, %for.body7.2.preheader ]
  %xr.1103.2 = phi double [ %xr.2.2, %for.body7.2 ], [ %xr.2.1.lcssa, %for.body7.2.preheader ]
  %arrayidx30.2 = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], [3 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_P, i64 0, i64 %indvars.iv124, i64 2, i64 %indvars.iv.2, i64 0
  %count.i68.2 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 2, i64 %indvars.iv.2, i32 2
  %71 = load i64, i64* %count.i68.2, align 8, !tbaa !13
  %conv.i69.2 = uitofp i64 %71 to double
  %div.i70.2 = fmul fast double %conv.i69.2, 3.125000e-02
  %cmp3.i71.2 = fcmp fast ogt double %div.i70.2, 1.000000e+00
  %cond11.i72.2 = select fast i1 %cmp3.i71.2, double 1.000000e+00, double %div.i70.2
  %72 = load i32, i32* %arrayidx30.2, align 8, !tbaa !17
  %mul.i73.2 = mul nsw i32 %72, %spec.select.i.us.us
  %shr.i74.2 = ashr i32 %mul.i73.2, 4
  %arrayidx12.i75.2 = getelementptr inbounds [3 x [3 x [11 x [2 x i32]]]], [3 x [3 x [11 x [2 x i32]]]]* @INIT_MB_TYPE_P, i64 0, i64 %indvars.iv124, i64 2, i64 %indvars.iv.2, i64 1
  %73 = load i32, i32* %arrayidx12.i75.2, align 4, !tbaa !17
  %add.i76.2 = add nsw i32 %shr.i74.2, %73
  %74 = icmp sgt i32 %add.i76.2, 0
  %cond18.i77.2 = select i1 %74, i32 %add.i76.2, i32 0
  %cmp19.i78.2 = icmp ult i32 %cond18.i77.2, 127
  %cond30.i79.2 = select i1 %cmp19.i78.2, i32 %cond18.i77.2, i32 127
  %MPS.i80.2 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 2, i64 %indvars.iv.2, i32 1
  %75 = load i8, i8* %MPS.i80.2, align 2, !tbaa !18
  %tobool.not.i81.2 = icmp eq i8 %75, 0
  %state36.i82.2 = getelementptr inbounds %struct.MotionInfoContexts, %struct.MotionInfoContexts* %mc, i64 0, i32 0, i64 2, i64 %indvars.iv.2, i32 0
  %76 = load i16, i16* %state36.i82.2, align 8, !tbaa !19
  %conv37.i83.2 = zext i16 %76 to i32
  %add34.i84.2 = add nuw nsw i32 %conv37.i83.2, 64
  %sub.i85.2 = sub nsw i32 63, %conv37.i83.2
  %cond39.i86.2 = select i1 %tobool.not.i81.2, i32 %sub.i85.2, i32 %add34.i84.2
  %idxprom.i87.2 = sext i32 %cond39.i86.2 to i64
  %arrayidx40.i88.2 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom.i87.2
  %77 = load double, double* %arrayidx40.i88.2, align 8, !tbaa !20
  %idxprom42.i89.2 = zext i32 %cond30.i79.2 to i64
  %arrayidx43.i90.2 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom42.i89.2
  %78 = load double, double* %arrayidx43.i90.2, align 8, !tbaa !20
  %79 = fneg fast double %cond11.i72.2
  %80 = fmul fast double %77, %79
  %sub45.i91.2 = fmul fast double %80, %78
  %sub46.i92.2 = sub nsw i32 127, %cond39.i86.2
  %idxprom47.i93.2 = sext i32 %sub46.i92.2 to i64
  %arrayidx48.i94.2 = getelementptr inbounds [128 x double], [128 x double]* @probability, i64 0, i64 %idxprom47.i93.2
  %81 = load double, double* %arrayidx48.i94.2, align 8, !tbaa !20
  %mul49.i95.2 = fmul fast double %81, %cond11.i72.2
  %sub50.i96.2 = xor i32 %cond30.i79.2, 127
  %idxprom51.i97.2 = zext i32 %sub50.i96.2 to i64
  %arrayidx52.i98.2 = getelementptr inbounds [128 x double], [128 x double]* @entropy, i64 0, i64 %idxprom51.i97.2
  %82 = load double, double* %arrayidx52.i98.2, align 8, !tbaa !20
  %mul53.i99.2 = fmul fast double %mul49.i95.2, %82
  %sub54.i100.2 = fsub fast double %sub45.i91.2, %mul53.i99.2
  %xr.2.2 = fadd fast double %sub54.i100.2, %xr.1103.2
  %indvars.iv.next.2 = add nuw nsw i64 %indvars.iv.2, 1
  %exitcond.2.not = icmp eq i64 %indvars.iv.next.2, 11
  br i1 %exitcond.2.not, label %for.end35.loopexit129, label %for.body7.2, !llvm.loop !22

for.end35.loopexit:                               ; preds = %for.body7.us.us.2
  %xr.2.us.us.2.lcssa = phi double [ %xr.2.us.us.2, %for.body7.us.us.2 ]
  br label %for.end35

for.end35.loopexit129:                            ; preds = %for.body7.2
  %xr.2.2.lcssa = phi double [ %xr.2.2, %for.body7.2 ]
  br label %for.end35

for.end35:                                        ; preds = %for.end35.loopexit129, %for.end35.loopexit
  %.us-phi106 = phi double [ %xr.2.us.us.2.lcssa, %for.end35.loopexit ], [ %xr.2.2.lcssa, %for.end35.loopexit129 ]
  %cmp36 = fcmp fast olt double %.us-phi106, %min_xr.0109
  br i1 %cmp36, label %if.then37, label %for.inc39

if.then37:                                        ; preds = %for.end35
  %83 = trunc i64 %indvars.iv124 to i32
  store i32 %83, i32* %mnumber, align 4, !tbaa !17
  br label %for.inc39

for.inc39:                                        ; preds = %for.end35, %if.then37
  %min_xr.1 = phi double [ %.us-phi106, %if.then37 ], [ %min_xr.0109, %for.end35 ]
  %indvars.iv.next125 = add nuw nsw i64 %indvars.iv124, 1
  %exitcond127.not = icmp eq i64 %indvars.iv.next125, %cond
  br i1 %exitcond127.not, label %for.end41, label %for.inc39.for.cond2.preheader_crit_edge, !llvm.loop !24

for.inc39.for.cond2.preheader_crit_edge:          ; preds = %for.inc39
  %.pre = load i32, i32* %type, align 8, !tbaa !21
  br label %for.cond2.preheader

for.end41:                                        ; preds = %for.inc39
  ret void
}

attributes #0 = { nounwind "approx-func-fp-math"="true" "frame-pointer"="none" "min-legal-vector-width"="0" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sifive-x280" "target-features"="+64bit,+a,+c,+d,+zvfh,+f,+m,+v,+xsfvfhbfmin,+xsfvqmaccqoq,+zba,+zbb,+zfh,+zicsr,+zifencei,+zvl128b,+zvl256b,+zvl32b,+zvl512b,+zvl64b" "unsafe-fp-math"="true" }
attributes #1 = { argmemonly nofree nosync nounwind willreturn }
attributes #2 = { nounwind }

!llvm.module.flags = !{!0, !1, !2}
!llvm.ident = !{!3}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"lp64d"}
!2 = !{i32 1, !"SmallDataLimit", i32 8}
!3 = !{!"clang version 15.0.0 (git@github.com:sifive/riscv-llvm-internal.git 4f609aecbee1ec41dd4f650bc6913550908fe264)"}
!4 = !{!5, !5, i64 0}
!5 = !{!"any pointer", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C/C++ TBAA"}
!8 = !{!9, !9, i64 0}
!9 = !{!"double", !6, i64 0}
!10 = !{!11, !12, i64 40}
!11 = !{!"", !12, i64 0, !12, i64 4, !12, i64 8, !12, i64 12, !12, i64 16, !12, i64 20, !12, i64 24, !12, i64 28, !12, i64 32, !12, i64 36, !12, i64 40, !12, i64 44, !13, i64 48, !12, i64 52, !12, i64 56, !12, i64 60, !12, i64 64, !12, i64 68, !12, i64 72, !12, i64 76, !12, i64 80, !12, i64 84, !12, i64 88, !12, i64 92, !12, i64 96, !5, i64 104, !5, i64 112, !12, i64 120, !5, i64 128, !12, i64 136, !12, i64 140, !12, i64 144, !12, i64 148, !12, i64 152, !12, i64 156, !12, i64 160, !12, i64 164, !12, i64 168, !12, i64 172, !12, i64 176, !12, i64 180, !6, i64 184, !6, i64 4792, !6, i64 7352, !6, i64 8504, !6, i64 12600, !6, i64 13112, !5, i64 14136, !5, i64 14144, !5, i64 14152, !5, i64 14160, !5, i64 14168, !6, i64 14176, !5, i64 71776, !5, i64 71784, !12, i64 71792, !12, i64 71796, !12, i64 71800, !12, i64 71804, !6, i64 71808, !12, i64 71872, !12, i64 71876, !12, i64 71880, !12, i64 71884, !12, i64 71888, !9, i64 71896, !12, i64 71904, !12, i64 71908, !12, i64 71912, !12, i64 71916, !5, i64 71920, !5, i64 71928, !5, i64 71936, !5, i64 71944, !6, i64 71952, !12, i64 71984, !12, i64 71988, !12, i64 71992, !12, i64 71996, !12, i64 72000, !12, i64 72004, !12, i64 72008, !12, i64 72012, !6, i64 72016, !12, i64 72376, !12, i64 72380, !12, i64 72384, !12, i64 72388, !12, i64 72392, !12, i64 72396, !12, i64 72400, !12, i64 72404, !12, i64 72408, !12, i64 72412, !12, i64 72416, !12, i64 72420, !6, i64 72424, !12, i64 72428, !12, i64 72432, !6, i64 72436, !12, i64 72444, !12, i64 72448, !12, i64 72452, !12, i64 72456, !12, i64 72460, !12, i64 72464, !12, i64 72468, !12, i64 72472, !12, i64 72476, !12, i64 72480, !12, i64 72484, !12, i64 72488, !12, i64 72492, !12, i64 72496, !12, i64 72500, !12, i64 72504, !12, i64 72508, !5, i64 72512, !12, i64 72520, !12, i64 72524, !12, i64 72528, !12, i64 72532, !12, i64 72536, !9, i64 72544, !12, i64 72552, !12, i64 72556, !12, i64 72560, !12, i64 72564, !12, i64 72568, !12, i64 72572, !12, i64 72576, !5, i64 72584, !12, i64 72592, !12, i64 72596, !12, i64 72600, !12, i64 72604, !12, i64 72608, !12, i64 72612, !12, i64 72616, !12, i64 72620, !12, i64 72624, !12, i64 72628, !12, i64 72632, !12, i64 72636, !12, i64 72640, !12, i64 72644, !12, i64 72648, !12, i64 72652, !12, i64 72656, !12, i64 72660, !12, i64 72664, !12, i64 72668, !12, i64 72672, !12, i64 72676, !12, i64 72680, !12, i64 72684, !12, i64 72688, !12, i64 72692, !12, i64 72696, !12, i64 72700, !12, i64 72704, !12, i64 72708, !12, i64 72712, !6, i64 72716, !12, i64 72724, !12, i64 72728, !12, i64 72732}
!12 = !{!"int", !6, i64 0}
!13 = !{!"float", !6, i64 0}
!14 = !{!12, !12, i64 0}
!15 = !{!16, !18, i64 8}
!16 = !{!"", !17, i64 0, !6, i64 2, !18, i64 8}
!17 = !{!"short", !6, i64 0}
!18 = !{!"long", !6, i64 0}
!19 = !{!16, !6, i64 2}
!20 = !{!16, !17, i64 0}
!21 = !{!11, !12, i64 24}
!22 = distinct !{!22, !23}
!23 = !{!"llvm.loop.mustprogress"}
!24 = distinct !{!24, !23}
!25 = distinct !{!25, !23}
