; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=loop-vectorize -riscv-use-vla-vectorizer -S -mtriple riscv64 -mattr=+v | FileCheck %s

define void @reverse_reverse(i64 %arg) {
; CHECK-LABEL: @reverse_reverse(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[ARG:%.*]], 1
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP0]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = sub i64 [[ARG]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr null, i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 0, [[TMP7]]
; CHECK-NEXT:    [[TMP19:%.*]] = sub i64 [[TMP7]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = mul i64 -1, [[TMP19]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i32, ptr [[TMP6]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i32, ptr [[TMP10]], i64 [[TMP9]]
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr align 4 [[TMP11]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP13:%.*]] = mul i64 0, [[TMP12]]
; CHECK-NEXT:    [[TMP20:%.*]] = sub i64 [[TMP12]], 1
; CHECK-NEXT:    [[TMP14:%.*]] = mul i64 -1, [[TMP20]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i32, ptr [[TMP6]], i64 [[TMP13]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i32, ptr [[TMP15]], i64 [[TMP14]]
; CHECK-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> [[VP_OP_LOAD]], ptr align 4 [[TMP16]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP17:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP17]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP0]]
; CHECK-NEXT:    br i1 [[TMP18]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[ARG]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], -1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr null, i64 [[IV]]
; CHECK-NEXT:    [[DATA:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    store i32 [[DATA]], ptr [[GEP]], align 4
; CHECK-NEXT:    [[COND:%.*]] = icmp ne i64 [[IV]], 0
; CHECK-NEXT:    br i1 [[COND]], label [[LOOP]], label [[EXIT]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop
loop:
  %iv = phi i64 [ %arg, %entry ], [ %iv.next, %loop ]
  %iv.next = add i64 %iv, -1
  %gep = getelementptr i32, ptr null, i64 %iv
  %data = load i32, ptr %gep, align 4
  store i32 %data, ptr %gep, align 4
  %cond = icmp ne i64 %iv, 0
  br i1 %cond, label %loop, label %exit
exit:
  ret void
}

define void @reverse_binop_reverse(i64 %arg, i32 %alpha) {
; CHECK-LABEL: @reverse_binop_reverse(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[ARG:%.*]], 1
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[ALPHA:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP0]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = sub i64 [[ARG]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr null, i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 0, [[TMP7]]
; CHECK-NEXT:    [[TMP19:%.*]] = sub i64 [[TMP7]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = mul i64 -1, [[TMP19]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i32, ptr [[TMP6]], i64 [[TMP8]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i32, ptr [[TMP10]], i64 [[TMP9]]
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr align 4 [[TMP11]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> [[BROADCAST_SPLAT]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP13:%.*]] = mul i64 0, [[TMP12]]
; CHECK-NEXT:    [[TMP20:%.*]] = sub i64 [[TMP12]], 1
; CHECK-NEXT:    [[TMP14:%.*]] = mul i64 -1, [[TMP20]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i32, ptr [[TMP6]], i64 [[TMP13]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i32, ptr [[TMP15]], i64 [[TMP14]]
; CHECK-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> [[VP_OP]], ptr align 4 [[TMP16]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP17:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP17]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP0]]
; CHECK-NEXT:    br i1 [[TMP18]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[ARG]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], -1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr null, i64 [[IV]]
; CHECK-NEXT:    [[DATA:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[C:%.*]] = add i32 [[DATA]], [[ALPHA]]
; CHECK-NEXT:    store i32 [[C]], ptr [[GEP]], align 4
; CHECK-NEXT:    [[COND:%.*]] = icmp ne i64 [[IV]], 0
; CHECK-NEXT:    br i1 [[COND]], label [[LOOP]], label [[EXIT]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop
loop:
  %iv = phi i64 [ %arg, %entry ], [ %iv.next, %loop ]
  %iv.next = add i64 %iv, -1
  %gep = getelementptr i32, ptr null, i64 %iv
  %data = load i32, ptr %gep, align 4
  %c = add i32 %data, %alpha
  store i32 %c, ptr %gep, align 4
  %cond = icmp ne i64 %iv, 0
  br i1 %cond, label %loop, label %exit
exit:
  ret void
}
