; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=insert-loop-count-profiling -mtriple=riscv64 -sifive-enable-loop-count-profiler < %s | FileCheck %s
; ModuleID = 'check.c'
;target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
; Check global counter declarations.
; CHECK: @__llvm_loop_profile_runtime = external global i32
; CHECK: @ExitCounter = private global [1 x i64] zeroinitializer, section "__llvm_loop_prof_data"
; CHECK: @LatchCounter = private global [1 x i64] zeroinitializer, section "__llvm_loop_prof_data"
; CHECK: @MinLatchCounter = private global [1 x i64] [i64 9223372036854775807], section "__llvm_loop_prof_data"
; CHECK: @MaxLatchCounter = private global [1 x i64] zeroinitializer, section "__llvm_loop_prof_data"
; CHECK: @ExecutedFlag = private global [1 x i64] zeroinitializer, section "__llvm_loop_prof_data"
; CHECK: @.loopnames = private global [1 x %0] [%0 { ptr @0 }], section "__llvm_loop_prof_data"
; The data structure of anchor {5 x ptr of counter array, ptr of loopnames, # of loops in this module, ptr of Executed Flag}
; CHECK: @Anchor = private global %loop_profile_loc { ptr @ExitCounter, ptr @LatchCounter, ptr @LatchCounter, ptr @MinLatchCounter, ptr @MaxLatchCounter, ptr @.loopnames, i32 1, ptr @ExecutedFlag }, section "__llvm_loop_prof"

; Function Attrs: noinline nounwind optnone uwtable
define dso_local signext i32 @loop() {
; CHECK-LABEL: define dso_local signext i32 @loop() {
; Check the local counter will be allocate at begin of function.
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = alloca i64
; Check counter will be added in latch block.
; CHECK:       for.cond:
; CHECK:         [[TMP1:%.*]] = load i64, ptr [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[TMP1]], 1
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP0]]
; CHECK:       for.body:
; CHECK:       for.inc:
; Check the runtime function which will update counter in exit block.
; CHECK:       for.end:
; CHECK-NEXT:    [[TMP7:%.*]] = load i64, ptr [[TMP0]]
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @__loop_prof_info_collection(ptr @Anchor, i32 0, i64 [[TMP7]])
; CHECK-NEXT:    store i64 0, ptr [[TMP0]]
;
entry:
  %ret = alloca i32, align 4
  %i = alloca i32, align 4
  store i32 0, ptr %ret, align 4
  store i32 0, ptr %i, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load i32, ptr %i, align 4
  %cmp = icmp slt i32 %0, 100
  br i1 %cmp, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %1 = load i32, ptr %i, align 4
  %2 = load i32, ptr %ret, align 4
  %add = add nsw i32 %2, %1
  store i32 %add, ptr %ret, align 4
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %3 = load i32, ptr %i, align 4
  %inc = add nsw i32 %3, 1
  store i32 %inc, ptr %i, align 4
  br label %for.cond

for.end:                                          ; preds = %for.cond
  %4 = load i32, ptr %ret, align 4
  ret i32 %4
}
