; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes='loop-simplify,loop-distribute' -enable-loop-distribute -S < %s | FileCheck %s

%union.31.33 = type { %struct.30.32 }
%struct.30.32 = type { i64 }

@d = external global i16, align 1

define void @f(%union.31.33* %agg.result) {
; CHECK-LABEL: define void @f(
; CHECK-SAME: ptr [[AGG_RESULT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast ptr [[AGG_RESULT]] to ptr
; CHECK-NEXT:    br i1 undef, label %[[ENTRY_SPLIT_US:.*]], label %[[CLEANUP_CONT_US:.*]]
; CHECK:       [[CLEANUP_CONT_US]]:
; CHECK-NEXT:    br label %[[LBL1_LVER_CHECK:.*]]
; CHECK:       [[ENTRY_SPLIT_US]]:
; CHECK-NEXT:    br label %[[LBL1_US:.*]]
; CHECK:       [[LBL1_US]]:
; CHECK-NEXT:    br label %[[CLEANUP4_LOOPEXIT_US:.*]]
; CHECK:       [[CLEANUP_CONT_US1:.*:]]
; CHECK-NEXT:    br label %[[FOR_END_US:.*]]
; CHECK:       [[FOR_END_US]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[CLEANUP4_LOOPEXIT_US]]:
; CHECK-NEXT:    br label %[[CLEANUP4_US:.*]]
; CHECK:       [[CLEANUP4_US]]:
; CHECK-NEXT:    br i1 false, label %[[LBL1_US]], label %[[RETURN_US_LCSSA_US:.*]]
; CHECK:       [[RETURN_US_LCSSA_US]]:
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[LBL1_LVER_CHECK]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[TMP0]], i64 4
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr @d, [[SCEVGEP]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[TMP0]], getelementptr inbounds (i8, ptr @d, i64 2)
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[LBL1_PH_LVER_ORIG:.*]], label %[[LBL1_PH_LDIST1:.*]]
; CHECK:       [[LBL1_PH_LVER_ORIG]]:
; CHECK-NEXT:    br label %[[LBL1_LVER_ORIG:.*]]
; CHECK:       [[LBL1_LVER_ORIG]]:
; CHECK-NEXT:    [[D_PROMOTED_LVER_ORIG:%.*]] = load i16, ptr @d, align 1
; CHECK-NEXT:    br label %[[FOR_END_LVER_ORIG:.*]]
; CHECK:       [[FOR_END_LVER_ORIG]]:
; CHECK-NEXT:    store i16 undef, ptr @d, align 1
; CHECK-NEXT:    store i32 undef, ptr [[TMP0]], align 1
; CHECK-NEXT:    br label %[[CLEANUP_CONT:.*]]
; CHECK:       [[CLEANUP_CONT]]:
; CHECK-NEXT:    br i1 false, label %[[LBL1_LVER_ORIG]], label %[[RETURN_US_LCSSA_LOOPEXIT:.*]]
; CHECK:       [[LBL1_PH_LDIST1]]:
; CHECK-NEXT:    br label %[[LBL1_LDIST1:.*]]
; CHECK:       [[LBL1_LDIST1]]:
; CHECK-NEXT:    [[D_PROMOTED_LDIST1:%.*]] = load i16, ptr @d, align 1, !alias.scope [[META0:![0-9]+]], !noalias [[META3:![0-9]+]]
; CHECK-NEXT:    br label %[[FOR_END_LDIST1:.*]]
; CHECK:       [[FOR_END_LDIST1]]:
; CHECK-NEXT:    store i16 undef, ptr @d, align 1, !alias.scope [[META0]], !noalias [[META3]]
; CHECK-NEXT:    br label %[[CLEANUP4_LDIST1:.*]]
; CHECK:       [[CLEANUP4_LDIST1]]:
; CHECK-NEXT:    br i1 false, label %[[LBL1_LDIST1]], label %[[LBL1_PH:.*]]
; CHECK:       [[LBL1_PH]]:
; CHECK-NEXT:    br label %[[LBL1:.*]]
; CHECK:       [[LBL1]]:
; CHECK-NEXT:    br label %[[CLEANUP4_LOOPEXIT:.*]]
; CHECK:       [[CLEANUP_CONT1:.*:]]
; CHECK-NEXT:    unreachable
; CHECK:       [[CLEANUP4_LOOPEXIT]]:
; CHECK-NEXT:    store i32 undef, ptr [[TMP0]], align 1, !alias.scope [[META3]]
; CHECK-NEXT:    br label %[[CLEANUP4:.*]]
; CHECK:       [[CLEANUP4_LOOPEXIT1:.*:]]
; CHECK-NEXT:    unreachable
; CHECK:       [[CLEANUP4]]:
; CHECK-NEXT:    br i1 false, label %[[LBL1]], label %[[RETURN_US_LCSSA_LOOPEXIT1:.*]]
; CHECK:       [[RETURN_US_LCSSA_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN_US_LCSSA:.*]]
; CHECK:       [[RETURN_US_LCSSA_LOOPEXIT1]]:
; CHECK-NEXT:    br label %[[RETURN_US_LCSSA]]
; CHECK:       [[RETURN_US_LCSSA]]:
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast %union.31.33* %agg.result to i32*
  br i1 undef, label %entry.split.us, label %entry.entry.split_crit_edge

entry.entry.split_crit_edge:                      ; preds = %entry
  br label %entry.split

entry.split.us:                                   ; preds = %entry
  br label %lbl1.us

lbl1.us:                                          ; preds = %cleanup4.us, %entry.split.us
  br label %cleanup4.loopexit.us

cleanup.cont.us:                                  ; No predecessors!
  br label %for.end.us

for.end.us:                                       ; preds = %cleanup.cont.us
  br label %cleanup4.us

cleanup4.loopexit.us:                             ; preds = %lbl1.us
  br label %cleanup4.us

cleanup4.us:                                      ; preds = %cleanup4.loopexit.us, %for.end.us
  br i1 undef, label %lbl1.us, label %return.us-lcssa.us

return.us-lcssa.us:                               ; preds = %cleanup4.us
  br label %return

entry.split:                                      ; preds = %entry.entry.split_crit_edge
  br label %lbl1

lbl1:                                             ; preds = %cleanup4, %entry.split
  %d.promoted = load i16, i16* @d, align 1
  br label %for.end

cleanup.cont:                                     ; No predecessors!
  br label %for.end

for.end:                                          ; preds = %cleanup.cont, %lbl1
  store i16 undef, i16* @d, align 1
  store i32 undef, i32* %0, align 1
  br label %cleanup4

cleanup4.loopexit:                                ; No predecessors!
  br label %cleanup4

cleanup4:                                         ; preds = %cleanup4.loopexit, %for.end
  %1 = phi i16 [ undef, %for.end ], [ 0, %cleanup4.loopexit ]
  br i1 false, label %lbl1, label %return.us-lcssa

return.us-lcssa:                                  ; preds = %cleanup4
  br label %return

return:                                           ; preds = %return.us-lcssa, %return.us-lcssa.us
  ret void
}
;.
; CHECK: [[META0]] = !{[[META1:![0-9]+]]}
; CHECK: [[META1]] = distinct !{[[META1]], [[META2:![0-9]+]]}
; CHECK: [[META2]] = distinct !{[[META2]], !"LVerDomain"}
; CHECK: [[META3]] = !{[[META4:![0-9]+]]}
; CHECK: [[META4]] = distinct !{[[META4]], [[META2]]}
;.
