; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -passes=lower-constant-intrinsics -S | FileCheck %s

; riscv.is.splat should fold to false and remove land.lhs.true.i.
define void @test_not_splat(i8* nocapture readonly %in, i8* nocapture readonly %v, i8* nocapture %out) {
; CHECK-LABEL: @test_not_splat(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast ptr [[IN:%.*]] to ptr
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, ptr [[TMP0]], i64 16)
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast ptr [[V:%.*]] to ptr
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, ptr [[TMP2]], i64 16)
; CHECK-NEXT:    br label [[IF_ELSE_I:%.*]]
; CHECK:       if.else.i:
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP3]], i8 127, i64 16)
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP3]], i8 7, i64 16)
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP1]], <vscale x 16 x i8> [[TMP3]], i64 16)
; CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP6]], i8 0, <vscale x 16 x i1> [[TMP5]], i64 16)
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP3]], i8 -7, i64 16)
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP3]], i8 0, i64 16)
; CHECK-NEXT:    [[TMP10:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP1]], <vscale x 16 x i8> [[TMP9]], i64 16)
; CHECK-NEXT:    [[TMP11:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP10]], i8 0, <vscale x 16 x i1> [[TMP8]], i64 16)
; CHECK-NEXT:    [[TMP12:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP7]], <vscale x 16 x i8> [[TMP11]], <vscale x 16 x i1> [[TMP4]], i64 16)
; CHECK-NEXT:    br label [[VSHLQ_U8_EXIT:%.*]]
; CHECK:       vshlq_u8.exit:
; CHECK-NEXT:    [[TMP13:%.*]] = bitcast ptr [[OUT:%.*]] to ptr
; CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> [[TMP12]], ptr [[TMP13]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 16 x i8>*
  %1 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8>* %0, i64 16)
  %2 = bitcast i8* %v to <vscale x 16 x i8>*
  %3 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8>* %2, i64 16)
  %4 = call i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8> %3)
  br i1 %4, label %land.lhs.true.i, label %if.else.i

land.lhs.true.i:                                  ; preds = %entry
  %5 = call <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8> %3, i8 0, i64 16)
  %6 = call i64 @llvm.riscv.vfirst.nxv16i1.i64(<vscale x 16 x i1> %5, i64 16)
  %cmp.i = icmp slt i64 %6, 0
  br i1 %cmp.i, label %vshlq_u8.exit, label %if.else.i

if.else.i:                                        ; preds = %land.lhs.true.i, %entry
  %7 = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> %3, i8 127, i64 16)
  %8 = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> %3, i8 7, i64 16)
  %9 = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %1, <vscale x 16 x i8> %3, i64 16)
  %10 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %9, i8 0, <vscale x 16 x i1> %8, i64 16)
  %11 = call <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8> %3, i8 -7, i64 16)
  %12 = call <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %3, i8 0, i64 16)
  %13 = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %1, <vscale x 16 x i8> %12, i64 16)
  %14 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %13, i8 0, <vscale x 16 x i1> %11, i64 16)
  %15 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %10, <vscale x 16 x i8> %14, <vscale x 16 x i1> %7, i64 16)
  br label %vshlq_u8.exit

vshlq_u8.exit:                                    ; preds = %land.lhs.true.i, %if.else.i
  %temp_2.0.i = phi <vscale x 16 x i8> [ %15, %if.else.i ], [ %1, %land.lhs.true.i ]
  %16 = bitcast i8* %out to <vscale x 16 x i8>*
  call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> %temp_2.0.i, <vscale x 16 x i8>* %16, i64 16)
  ret void
}

; is.splat should fold to true.
define void @test_splat(i8* nocapture readonly %in, i8 signext %v, i8* nocapture %out) {
; CHECK-LABEL: @test_splat(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast ptr [[IN:%.*]] to ptr
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, ptr [[TMP0]], i64 16)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 [[V:%.*]], i64 16)
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i8 [[V]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[VSHLQ_U8_EXIT:%.*]], label [[IF_ELSE_I:%.*]]
; CHECK:       if.else.i:
; CHECK-NEXT:    [[TMP3:%.*]] = zext i8 [[V]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.i64.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP1]], i64 [[TMP3]], i64 16)
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 0, i64 16)
; CHECK-NEXT:    [[TMP6:%.*]] = icmp ugt i8 [[V]], 7
; CHECK-NEXT:    [[TMP7:%.*]] = select i1 [[TMP6]], <vscale x 16 x i8> [[TMP5]], <vscale x 16 x i8> [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = sub i8 0, [[V]]
; CHECK-NEXT:    [[TMP9:%.*]] = zext i8 [[TMP8]] to i64
; CHECK-NEXT:    [[TMP10:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.i64.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP1]], i64 [[TMP9]], i64 16)
; CHECK-NEXT:    [[TMP11:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 0, i64 16)
; CHECK-NEXT:    [[TMP12:%.*]] = icmp ult i8 [[V]], -7
; CHECK-NEXT:    [[TMP13:%.*]] = select i1 [[TMP12]], <vscale x 16 x i8> [[TMP11]], <vscale x 16 x i8> [[TMP10]]
; CHECK-NEXT:    [[TMP14:%.*]] = icmp slt i8 [[V]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = select i1 [[TMP14]], <vscale x 16 x i8> [[TMP13]], <vscale x 16 x i8> [[TMP7]]
; CHECK-NEXT:    br label [[VSHLQ_U8_EXIT]]
; CHECK:       vshlq_u8.exit:
; CHECK-NEXT:    [[TEMP_2_0_I:%.*]] = phi <vscale x 16 x i8> [ [[TMP15]], [[IF_ELSE_I]] ], [ [[TMP1]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast ptr [[OUT:%.*]] to ptr
; CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> [[TEMP_2_0_I]], ptr [[TMP16]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 16 x i8>*
  %1 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8>* %0, i64 16)
  %2 = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 %v, i64 16)
  %3 = call i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8> %2)
  %.not = icmp eq i8 %v, 0
  %or.cond = select i1 %3, i1 %.not, i1 false
  br i1 %or.cond, label %vshlq_u8.exit, label %if.else.i

if.else.i:                                        ; preds = %entry
  %4 = zext i8 %v to i64
  %5 = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.i64.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %1, i64 %4, i64 16)
  %6 = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 0, i64 16)
  %7 = icmp ugt i8 %v, 7
  %8 = select i1 %7, <vscale x 16 x i8> %6, <vscale x 16 x i8> %5
  %9 = sub i8 0, %v
  %10 = zext i8 %9 to i64
  %11 = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.i64.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %1, i64 %10, i64 16)
  %12 = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 0, i64 16)
  %13 = icmp ult i8 %v, -7
  %14 = select i1 %13, <vscale x 16 x i8> %12, <vscale x 16 x i8> %11
  %15 = icmp slt i8 %v, 0
  %16 = select i1 %15, <vscale x 16 x i8> %14, <vscale x 16 x i8> %8
  br label %vshlq_u8.exit

vshlq_u8.exit:                                    ; preds = %entry, %if.else.i
  %temp_2.0.i = phi <vscale x 16 x i8> [ %16, %if.else.i ], [ %1, %entry ]
  %17 = bitcast i8* %out to <vscale x 16 x i8>*
  call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> %temp_2.0.i, <vscale x 16 x i8>* %17, i64 16)
  ret void
}

declare void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>* nocapture, i64)
declare i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8>)
declare <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8>, i8, i64)
declare i64 @llvm.riscv.vfirst.nxv16i1.i64(<vscale x 16 x i1>, i64)
declare <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, i64)
declare <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, i8, <vscale x 16 x i1>, i64)
declare <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, i64)
declare <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i1>, i64)
declare <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>* nocapture, i64)
declare <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.i64.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, i64, i64)
declare <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.i64.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, i64, i64)
