; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-unroll -S -mtriple riscv64-unknown-linux-gnu -mattr="+v" < %s | FileCheck %s

; Function Attrs: nofree noreturn nounwind
define void @WriteProfile(i32* nocapture readnone %M, float*** nocapture readnone %mat214, i32 %0, i32 %1, float** nocapture readnone %2, i64 %indvars.iv382, float** nocapture readnone %arrayidx216, float* nocapture readnone %3, float* nocapture readnone %arrayidx218, float %4, i64 %wide.trip.count, float %conv223) local_unnamed_addr #0 {
; CHECK-LABEL: @WriteProfile(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[INDVARS_IV382:%.*]], 1
; CHECK-NEXT:    br label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT6:%.*]] = insertelement <vscale x 4 x float> poison, float [[TMP4:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT7:%.*]] = shufflevector <vscale x 4 x float> [[BROADCAST_SPLATINSERT6]], <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ zeroinitializer, [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = sub i64 [[TMP5]], [[INDEX]]
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP8:%.*]] = shl i64 [[TMP7]], 2
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP6]], i64 [[TMP8]])
; CHECK-NEXT:    [[TMP9:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP10:%.*]] = trunc i64 [[TMP9]] to i32
; CHECK-NEXT:    [[VP_OP:%.*]] = call fast <vscale x 4 x float> @llvm.vp.fadd.nxv4f32(<vscale x 4 x float> [[VEC_PHI]], <vscale x 4 x float> [[BROADCAST_SPLAT7]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP10]])
; CHECK-NEXT:    [[EVL_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[TMP10]], i64 0
; CHECK-NEXT:    [[EVL_SPLAT:%.*]] = shufflevector <vscale x 4 x i32> [[EVL_SPLATINSERT]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    [[STEP_VEC:%.*]] = call <vscale x 4 x i32> @llvm.stepvector.nxv4i32()
; CHECK-NEXT:    [[EVL_MASK:%.*]] = icmp ult <vscale x 4 x i32> [[STEP_VEC]], [[EVL_SPLAT]]
; CHECK-NEXT:    [[TMP11]] = select <vscale x 4 x i1> [[EVL_MASK]], <vscale x 4 x float> [[VP_OP]], <vscale x 4 x float> [[VEC_PHI]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP9]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[TMP5]]
; CHECK-NEXT:    br i1 [[TMP12]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi <vscale x 4 x float> [ [[TMP11]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = call fast float @llvm.vector.reduce.fadd.nxv4f32(float -0.000000e+00, <vscale x 4 x float> [[DOTLCSSA]])
; CHECK-NEXT:    [[CONV225:%.*]] = fptosi float [[TMP13]] to i32
; CHECK-NEXT:    br label [[VECTOR_PH]]
;
entry:
  %5 = add i64 %indvars.iv382, 1
  br label %vector.ph

vector.ph:                                        ; preds = %entry, %middle.block
  %broadcast.splatinsert6 = insertelement <vscale x 4 x float> poison, float %4, i64 0
  %broadcast.splat7 = shufflevector <vscale x 4 x float> %broadcast.splatinsert6, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %vec.phi = phi <vscale x 4 x float> [ insertelement (<vscale x 4 x float> zeroinitializer, float 0.000000e+00, i32 0), %vector.ph ], [ %11, %vector.body ]
  %6 = sub i64 %5, %index
  %7 = call i64 @llvm.vscale.i64()
  %8 = shl i64 %7, 2
  %rvl = call i64 @llvm.umin.i64(i64 %6, i64 %8)
  %9 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %10 = trunc i64 %9 to i32
  %vp.op = call fast <vscale x 4 x float> @llvm.vp.fadd.nxv4f32(<vscale x 4 x float> %vec.phi, <vscale x 4 x float> %broadcast.splat7, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %10)
  %evl.splatinsert = insertelement <vscale x 4 x i32> poison, i32 %10, i64 0
  %evl.splat = shufflevector <vscale x 4 x i32> %evl.splatinsert, <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
  %step.vec = call <vscale x 4 x i32> @llvm.experimental.stepvector.nxv4i32()
  %evl.mask = icmp ult <vscale x 4 x i32> %step.vec, %evl.splat
  %11 = select <vscale x 4 x i1> %evl.mask, <vscale x 4 x float> %vp.op, <vscale x 4 x float> %vec.phi
  %index.next = add i64 %index, %9
  %12 = icmp eq i64 %index.next, %5
  br i1 %12, label %middle.block, label %vector.body, !llvm.loop !0

middle.block:                                     ; preds = %vector.body
  %13 = call fast float @llvm.vector.reduce.fadd.nxv4f32(float -0.000000e+00, <vscale x 4 x float> %11)
  %conv225 = fptosi float %13 to i32
  br label %vector.ph
}

; Function Attrs: nofree nosync nounwind readnone willreturn
declare i64 @llvm.vscale.i64() #2

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare i64 @llvm.umin.i64(i64, i64) #3

; Function Attrs: nounwind
declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg) #4

; Function Attrs: nofree nosync nounwind readnone speculatable willreturn
declare <vscale x 4 x float> @llvm.vp.fadd.nxv4f32(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x i1>, i32) #3

; Function Attrs: nofree nosync nounwind readnone willreturn
declare <vscale x 4 x i32> @llvm.experimental.stepvector.nxv4i32() #2

; Function Attrs: nofree nosync nounwind readnone willreturn
declare float @llvm.vector.reduce.fadd.nxv4f32(float, <vscale x 4 x float>) #2

attributes #0 = { nofree noreturn nounwind }
attributes #2 = { nofree nosync nounwind readnone willreturn }
attributes #3 = { nofree nosync nounwind readnone speculatable willreturn }
attributes #4 = { nounwind }

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.isvectorized", i32 1}
