; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -passes=loop-unroll -mtriple riscv64 -unroll-runtime-epilog=true  | FileCheck %s -check-prefix=GENERIC-EPILOG
; RUN: opt < %s -S -passes=loop-unroll -mtriple riscv64 -unroll-runtime-epilog=false  | FileCheck %s -check-prefix=GENERIC-PROLOG
; RUN: opt < %s -S -passes=loop-unroll -mtriple riscv64 -mcpu=sifive-x280 -unroll-runtime-epilog=false | FileCheck %s -check-prefix=X280-EPILOG
; RUN: opt < %s -S -passes=loop-unroll -mtriple riscv64 -mcpu=sifive-x280 -unroll-runtime-epilog=true | FileCheck %s -check-prefix=X280-PROLOG
; RUN: opt < %s -S -passes=loop-unroll -mtriple riscv64 -mcpu=sifive-p470 -unroll-runtime-epilog=true  | FileCheck %s -check-prefix=P470-EPILOG
; RUN: opt < %s -S -passes=loop-unroll -mtriple riscv64 -mcpu=sifive-p470 -unroll-runtime-epilog=false | FileCheck %s -check-prefix=P470-PROLOG

; Tests for unrolling loops with run-time trip counts

define i32 @test(ptr nocapture %a, i32 %n) nounwind uwtable readonly {
; GENERIC-EPILOG-LABEL: define i32 @test(
; GENERIC-EPILOG-SAME: ptr nocapture [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; GENERIC-EPILOG-NEXT:  [[ENTRY:.*]]:
; GENERIC-EPILOG-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; GENERIC-EPILOG-NEXT:    br i1 [[CMP1]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; GENERIC-EPILOG:       [[FOR_BODY_PREHEADER]]:
; GENERIC-EPILOG-NEXT:    br label %[[FOR_BODY:.*]]
; GENERIC-EPILOG:       [[FOR_BODY]]:
; GENERIC-EPILOG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; GENERIC-EPILOG-NEXT:    [[SUM_02:%.*]] = phi i32 [ [[ADD:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; GENERIC-EPILOG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; GENERIC-EPILOG-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; GENERIC-EPILOG-NEXT:    [[ADD]] = add nsw i32 [[TMP0]], [[SUM_02]]
; GENERIC-EPILOG-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 1
; GENERIC-EPILOG-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; GENERIC-EPILOG-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], [[N]]
; GENERIC-EPILOG-NEXT:    br i1 [[EXITCOND]], label %[[FOR_END_LOOPEXIT:.*]], label %[[FOR_BODY]]
; GENERIC-EPILOG:       [[FOR_END_LOOPEXIT]]:
; GENERIC-EPILOG-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[FOR_BODY]] ]
; GENERIC-EPILOG-NEXT:    br label %[[FOR_END]]
; GENERIC-EPILOG:       [[FOR_END]]:
; GENERIC-EPILOG-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD_LCSSA]], %[[FOR_END_LOOPEXIT]] ]
; GENERIC-EPILOG-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
; GENERIC-PROLOG-LABEL: define i32 @test(
; GENERIC-PROLOG-SAME: ptr nocapture [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; GENERIC-PROLOG-NEXT:  [[ENTRY:.*]]:
; GENERIC-PROLOG-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; GENERIC-PROLOG-NEXT:    br i1 [[CMP1]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; GENERIC-PROLOG:       [[FOR_BODY_PREHEADER]]:
; GENERIC-PROLOG-NEXT:    br label %[[FOR_BODY:.*]]
; GENERIC-PROLOG:       [[FOR_BODY]]:
; GENERIC-PROLOG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; GENERIC-PROLOG-NEXT:    [[SUM_02:%.*]] = phi i32 [ [[ADD:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; GENERIC-PROLOG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; GENERIC-PROLOG-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; GENERIC-PROLOG-NEXT:    [[ADD]] = add nsw i32 [[TMP0]], [[SUM_02]]
; GENERIC-PROLOG-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 1
; GENERIC-PROLOG-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; GENERIC-PROLOG-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], [[N]]
; GENERIC-PROLOG-NEXT:    br i1 [[EXITCOND]], label %[[FOR_END_LOOPEXIT:.*]], label %[[FOR_BODY]]
; GENERIC-PROLOG:       [[FOR_END_LOOPEXIT]]:
; GENERIC-PROLOG-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[FOR_BODY]] ]
; GENERIC-PROLOG-NEXT:    br label %[[FOR_END]]
; GENERIC-PROLOG:       [[FOR_END]]:
; GENERIC-PROLOG-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD_LCSSA]], %[[FOR_END_LOOPEXIT]] ]
; GENERIC-PROLOG-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
; X280-EPILOG-LABEL: define i32 @test(
; X280-EPILOG-SAME: ptr nocapture [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; X280-EPILOG-NEXT:  [[ENTRY:.*]]:
; X280-EPILOG-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; X280-EPILOG-NEXT:    br i1 [[CMP1]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; X280-EPILOG:       [[FOR_BODY_PREHEADER]]:
; X280-EPILOG-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; X280-EPILOG-NEXT:    [[XTRAITER:%.*]] = and i32 [[N]], 7
; X280-EPILOG-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i32 [[XTRAITER]], 0
; X280-EPILOG-NEXT:    br i1 [[LCMP_MOD]], label %[[FOR_BODY_PROL_PREHEADER:.*]], label %[[FOR_BODY_PROL_LOOPEXIT:.*]]
; X280-EPILOG:       [[FOR_BODY_PROL_PREHEADER]]:
; X280-EPILOG-NEXT:    br label %[[FOR_BODY_PROL:.*]]
; X280-EPILOG:       [[FOR_BODY_PROL]]:
; X280-EPILOG-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A]], align 4
; X280-EPILOG-NEXT:    [[PROL_ITER_CMP:%.*]] = icmp ne i32 1, [[XTRAITER]]
; X280-EPILOG-NEXT:    br i1 [[PROL_ITER_CMP]], label %[[FOR_BODY_PROL_1:.*]], label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA:.*]]
; X280-EPILOG:       [[FOR_BODY_PROL_1]]:
; X280-EPILOG-NEXT:    [[ARRAYIDX_PROL_1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 1
; X280-EPILOG-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX_PROL_1]], align 4
; X280-EPILOG-NEXT:    [[ADD_PROL_1:%.*]] = add nsw i32 [[TMP2]], [[TMP1]]
; X280-EPILOG-NEXT:    [[PROL_ITER_CMP_1:%.*]] = icmp ne i32 2, [[XTRAITER]]
; X280-EPILOG-NEXT:    br i1 [[PROL_ITER_CMP_1]], label %[[FOR_BODY_PROL_2:.*]], label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]
; X280-EPILOG:       [[FOR_BODY_PROL_2]]:
; X280-EPILOG-NEXT:    [[ARRAYIDX_PROL_2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 2
; X280-EPILOG-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX_PROL_2]], align 4
; X280-EPILOG-NEXT:    [[ADD_PROL_2:%.*]] = add nsw i32 [[TMP3]], [[ADD_PROL_1]]
; X280-EPILOG-NEXT:    [[PROL_ITER_CMP_2:%.*]] = icmp ne i32 3, [[XTRAITER]]
; X280-EPILOG-NEXT:    br i1 [[PROL_ITER_CMP_2]], label %[[FOR_BODY_PROL_3:.*]], label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]
; X280-EPILOG:       [[FOR_BODY_PROL_3]]:
; X280-EPILOG-NEXT:    [[ARRAYIDX_PROL_3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 3
; X280-EPILOG-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX_PROL_3]], align 4
; X280-EPILOG-NEXT:    [[ADD_PROL_3:%.*]] = add nsw i32 [[TMP4]], [[ADD_PROL_2]]
; X280-EPILOG-NEXT:    [[PROL_ITER_CMP_3:%.*]] = icmp ne i32 4, [[XTRAITER]]
; X280-EPILOG-NEXT:    br i1 [[PROL_ITER_CMP_3]], label %[[FOR_BODY_PROL_4:.*]], label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]
; X280-EPILOG:       [[FOR_BODY_PROL_4]]:
; X280-EPILOG-NEXT:    [[ARRAYIDX_PROL_4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 4
; X280-EPILOG-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX_PROL_4]], align 4
; X280-EPILOG-NEXT:    [[ADD_PROL_4:%.*]] = add nsw i32 [[TMP5]], [[ADD_PROL_3]]
; X280-EPILOG-NEXT:    [[PROL_ITER_CMP_4:%.*]] = icmp ne i32 5, [[XTRAITER]]
; X280-EPILOG-NEXT:    br i1 [[PROL_ITER_CMP_4]], label %[[FOR_BODY_PROL_5:.*]], label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]
; X280-EPILOG:       [[FOR_BODY_PROL_5]]:
; X280-EPILOG-NEXT:    [[ARRAYIDX_PROL_5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 5
; X280-EPILOG-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX_PROL_5]], align 4
; X280-EPILOG-NEXT:    [[ADD_PROL_5:%.*]] = add nsw i32 [[TMP6]], [[ADD_PROL_4]]
; X280-EPILOG-NEXT:    [[PROL_ITER_CMP_5:%.*]] = icmp ne i32 6, [[XTRAITER]]
; X280-EPILOG-NEXT:    br i1 [[PROL_ITER_CMP_5]], label %[[FOR_BODY_PROL_6:.*]], label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]
; X280-EPILOG:       [[FOR_BODY_PROL_6]]:
; X280-EPILOG-NEXT:    [[ARRAYIDX_PROL_6:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 6
; X280-EPILOG-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX_PROL_6]], align 4
; X280-EPILOG-NEXT:    [[ADD_PROL_6:%.*]] = add nsw i32 [[TMP7]], [[ADD_PROL_5]]
; X280-EPILOG-NEXT:    br label %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]
; X280-EPILOG:       [[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]]:
; X280-EPILOG-NEXT:    [[ADD_LCSSA_UNR_PH:%.*]] = phi i32 [ [[TMP1]], %[[FOR_BODY_PROL]] ], [ [[ADD_PROL_1]], %[[FOR_BODY_PROL_1]] ], [ [[ADD_PROL_2]], %[[FOR_BODY_PROL_2]] ], [ [[ADD_PROL_3]], %[[FOR_BODY_PROL_3]] ], [ [[ADD_PROL_4]], %[[FOR_BODY_PROL_4]] ], [ [[ADD_PROL_5]], %[[FOR_BODY_PROL_5]] ], [ [[ADD_PROL_6]], %[[FOR_BODY_PROL_6]] ]
; X280-EPILOG-NEXT:    [[INDVARS_IV_UNR_PH:%.*]] = phi i64 [ 1, %[[FOR_BODY_PROL]] ], [ 2, %[[FOR_BODY_PROL_1]] ], [ 3, %[[FOR_BODY_PROL_2]] ], [ 4, %[[FOR_BODY_PROL_3]] ], [ 5, %[[FOR_BODY_PROL_4]] ], [ 6, %[[FOR_BODY_PROL_5]] ], [ 7, %[[FOR_BODY_PROL_6]] ]
; X280-EPILOG-NEXT:    [[SUM_02_UNR_PH:%.*]] = phi i32 [ [[TMP1]], %[[FOR_BODY_PROL]] ], [ [[ADD_PROL_1]], %[[FOR_BODY_PROL_1]] ], [ [[ADD_PROL_2]], %[[FOR_BODY_PROL_2]] ], [ [[ADD_PROL_3]], %[[FOR_BODY_PROL_3]] ], [ [[ADD_PROL_4]], %[[FOR_BODY_PROL_4]] ], [ [[ADD_PROL_5]], %[[FOR_BODY_PROL_5]] ], [ [[ADD_PROL_6]], %[[FOR_BODY_PROL_6]] ]
; X280-EPILOG-NEXT:    br label %[[FOR_BODY_PROL_LOOPEXIT]]
; X280-EPILOG:       [[FOR_BODY_PROL_LOOPEXIT]]:
; X280-EPILOG-NEXT:    [[ADD_LCSSA_UNR:%.*]] = phi i32 [ poison, %[[FOR_BODY_PREHEADER]] ], [ [[ADD_LCSSA_UNR_PH]], %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]] ]
; X280-EPILOG-NEXT:    [[INDVARS_IV_UNR:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_UNR_PH]], %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]] ]
; X280-EPILOG-NEXT:    [[SUM_02_UNR:%.*]] = phi i32 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[SUM_02_UNR_PH]], %[[FOR_BODY_PROL_LOOPEXIT_UNR_LCSSA]] ]
; X280-EPILOG-NEXT:    [[TMP8:%.*]] = icmp ult i32 [[TMP0]], 7
; X280-EPILOG-NEXT:    br i1 [[TMP8]], label %[[FOR_END_LOOPEXIT:.*]], label %[[FOR_BODY_PREHEADER_NEW:.*]]
; X280-EPILOG:       [[FOR_BODY_PREHEADER_NEW]]:
; X280-EPILOG-NEXT:    br label %[[FOR_BODY:.*]]
; X280-EPILOG:       [[FOR_BODY]]:
; X280-EPILOG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_UNR]], %[[FOR_BODY_PREHEADER_NEW]] ], [ [[INDVARS_IV_NEXT_7:%.*]], %[[FOR_BODY]] ]
; X280-EPILOG-NEXT:    [[SUM_02:%.*]] = phi i32 [ [[SUM_02_UNR]], %[[FOR_BODY_PREHEADER_NEW]] ], [ [[ADD_7:%.*]], %[[FOR_BODY]] ]
; X280-EPILOG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; X280-EPILOG-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; X280-EPILOG-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP9]], [[SUM_02]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add i64 [[INDVARS_IV]], 1
; X280-EPILOG-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT]]
; X280-EPILOG-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARRAYIDX_1]], align 4
; X280-EPILOG-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[TMP10]], [[ADD]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_1:%.*]] = add i64 [[INDVARS_IV]], 2
; X280-EPILOG-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_1]]
; X280-EPILOG-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX_2]], align 4
; X280-EPILOG-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[TMP11]], [[ADD_1]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_2:%.*]] = add i64 [[INDVARS_IV]], 3
; X280-EPILOG-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_2]]
; X280-EPILOG-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX_3]], align 4
; X280-EPILOG-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[TMP12]], [[ADD_2]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_3:%.*]] = add i64 [[INDVARS_IV]], 4
; X280-EPILOG-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_3]]
; X280-EPILOG-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX_4]], align 4
; X280-EPILOG-NEXT:    [[ADD_4:%.*]] = add nsw i32 [[TMP13]], [[ADD_3]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_4:%.*]] = add i64 [[INDVARS_IV]], 5
; X280-EPILOG-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_4]]
; X280-EPILOG-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX_5]], align 4
; X280-EPILOG-NEXT:    [[ADD_5:%.*]] = add nsw i32 [[TMP14]], [[ADD_4]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_5:%.*]] = add i64 [[INDVARS_IV]], 6
; X280-EPILOG-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_5]]
; X280-EPILOG-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX_6]], align 4
; X280-EPILOG-NEXT:    [[ADD_6:%.*]] = add nsw i32 [[TMP15]], [[ADD_5]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_6:%.*]] = add i64 [[INDVARS_IV]], 7
; X280-EPILOG-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_6]]
; X280-EPILOG-NEXT:    [[TMP16:%.*]] = load i32, ptr [[ARRAYIDX_7]], align 4
; X280-EPILOG-NEXT:    [[ADD_7]] = add nsw i32 [[TMP16]], [[ADD_6]]
; X280-EPILOG-NEXT:    [[INDVARS_IV_NEXT_7]] = add i64 [[INDVARS_IV]], 8
; X280-EPILOG-NEXT:    [[LFTR_WIDEIV_7:%.*]] = trunc i64 [[INDVARS_IV_NEXT_7]] to i32
; X280-EPILOG-NEXT:    [[EXITCOND_7:%.*]] = icmp eq i32 [[LFTR_WIDEIV_7]], [[N]]
; X280-EPILOG-NEXT:    br i1 [[EXITCOND_7]], label %[[FOR_END_LOOPEXIT_UNR_LCSSA:.*]], label %[[FOR_BODY]]
; X280-EPILOG:       [[FOR_END_LOOPEXIT_UNR_LCSSA]]:
; X280-EPILOG-NEXT:    [[ADD_LCSSA_PH:%.*]] = phi i32 [ [[ADD_7]], %[[FOR_BODY]] ]
; X280-EPILOG-NEXT:    br label %[[FOR_END_LOOPEXIT]]
; X280-EPILOG:       [[FOR_END_LOOPEXIT]]:
; X280-EPILOG-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD_LCSSA_UNR]], %[[FOR_BODY_PROL_LOOPEXIT]] ], [ [[ADD_LCSSA_PH]], %[[FOR_END_LOOPEXIT_UNR_LCSSA]] ]
; X280-EPILOG-NEXT:    br label %[[FOR_END]]
; X280-EPILOG:       [[FOR_END]]:
; X280-EPILOG-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD_LCSSA]], %[[FOR_END_LOOPEXIT]] ]
; X280-EPILOG-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
; X280-PROLOG-LABEL: define i32 @test(
; X280-PROLOG-SAME: ptr nocapture [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; X280-PROLOG-NEXT:  [[ENTRY:.*]]:
; X280-PROLOG-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; X280-PROLOG-NEXT:    br i1 [[CMP1]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; X280-PROLOG:       [[FOR_BODY_PREHEADER]]:
; X280-PROLOG-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; X280-PROLOG-NEXT:    [[XTRAITER:%.*]] = and i32 [[N]], 7
; X280-PROLOG-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[TMP0]], 7
; X280-PROLOG-NEXT:    br i1 [[TMP1]], label %[[FOR_END_LOOPEXIT_UNR_LCSSA:.*]], label %[[FOR_BODY_PREHEADER_NEW:.*]]
; X280-PROLOG:       [[FOR_BODY_PREHEADER_NEW]]:
; X280-PROLOG-NEXT:    [[UNROLL_ITER:%.*]] = sub i32 [[N]], [[XTRAITER]]
; X280-PROLOG-NEXT:    br label %[[FOR_BODY:.*]]
; X280-PROLOG:       [[FOR_BODY]]:
; X280-PROLOG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER_NEW]] ], [ [[INDVARS_IV_NEXT_7:%.*]], %[[FOR_BODY]] ]
; X280-PROLOG-NEXT:    [[SUM_02:%.*]] = phi i32 [ 0, %[[FOR_BODY_PREHEADER_NEW]] ], [ [[ADD_7:%.*]], %[[FOR_BODY]] ]
; X280-PROLOG-NEXT:    [[NITER:%.*]] = phi i32 [ 0, %[[FOR_BODY_PREHEADER_NEW]] ], [ [[NITER_NEXT_7:%.*]], %[[FOR_BODY]] ]
; X280-PROLOG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; X280-PROLOG-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; X280-PROLOG-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP2]], [[SUM_02]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 1
; X280-PROLOG-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT]]
; X280-PROLOG-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX_1]], align 4
; X280-PROLOG-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[TMP3]], [[ADD]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_1:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 2
; X280-PROLOG-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_1]]
; X280-PROLOG-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX_2]], align 4
; X280-PROLOG-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[TMP4]], [[ADD_1]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_2:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 3
; X280-PROLOG-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_2]]
; X280-PROLOG-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX_3]], align 4
; X280-PROLOG-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[TMP5]], [[ADD_2]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_3:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 4
; X280-PROLOG-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_3]]
; X280-PROLOG-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX_4]], align 4
; X280-PROLOG-NEXT:    [[ADD_4:%.*]] = add nsw i32 [[TMP6]], [[ADD_3]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_4:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 5
; X280-PROLOG-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_4]]
; X280-PROLOG-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX_5]], align 4
; X280-PROLOG-NEXT:    [[ADD_5:%.*]] = add nsw i32 [[TMP7]], [[ADD_4]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_5:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 6
; X280-PROLOG-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_5]]
; X280-PROLOG-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX_6]], align 4
; X280-PROLOG-NEXT:    [[ADD_6:%.*]] = add nsw i32 [[TMP8]], [[ADD_5]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_6:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 7
; X280-PROLOG-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_6]]
; X280-PROLOG-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX_7]], align 4
; X280-PROLOG-NEXT:    [[ADD_7]] = add nsw i32 [[TMP9]], [[ADD_6]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_7]] = add nuw nsw i64 [[INDVARS_IV]], 8
; X280-PROLOG-NEXT:    [[NITER_NEXT_7]] = add i32 [[NITER]], 8
; X280-PROLOG-NEXT:    [[NITER_NCMP_7:%.*]] = icmp eq i32 [[NITER_NEXT_7]], [[UNROLL_ITER]]
; X280-PROLOG-NEXT:    br i1 [[NITER_NCMP_7]], label %[[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT:.*]], label %[[FOR_BODY]]
; X280-PROLOG:       [[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]]:
; X280-PROLOG-NEXT:    [[ADD_LCSSA_PH_PH:%.*]] = phi i32 [ [[ADD_7]], %[[FOR_BODY]] ]
; X280-PROLOG-NEXT:    [[INDVARS_IV_UNR_PH:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_7]], %[[FOR_BODY]] ]
; X280-PROLOG-NEXT:    [[SUM_02_UNR_PH:%.*]] = phi i32 [ [[ADD_7]], %[[FOR_BODY]] ]
; X280-PROLOG-NEXT:    br label %[[FOR_END_LOOPEXIT_UNR_LCSSA]]
; X280-PROLOG:       [[FOR_END_LOOPEXIT_UNR_LCSSA]]:
; X280-PROLOG-NEXT:    [[ADD_LCSSA_PH:%.*]] = phi i32 [ poison, %[[FOR_BODY_PREHEADER]] ], [ [[ADD_LCSSA_PH_PH]], %[[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]] ]
; X280-PROLOG-NEXT:    [[INDVARS_IV_UNR:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_UNR_PH]], %[[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]] ]
; X280-PROLOG-NEXT:    [[SUM_02_UNR:%.*]] = phi i32 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[SUM_02_UNR_PH]], %[[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]] ]
; X280-PROLOG-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i32 [[XTRAITER]], 0
; X280-PROLOG-NEXT:    br i1 [[LCMP_MOD]], label %[[FOR_BODY_EPIL_PREHEADER:.*]], label %[[FOR_END_LOOPEXIT:.*]]
; X280-PROLOG:       [[FOR_BODY_EPIL_PREHEADER]]:
; X280-PROLOG-NEXT:    br label %[[FOR_BODY_EPIL:.*]]
; X280-PROLOG:       [[FOR_BODY_EPIL]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_UNR]]
; X280-PROLOG-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARRAYIDX_EPIL]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL:%.*]] = add nsw i32 [[TMP10]], [[SUM_02_UNR]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_EPIL:%.*]] = add i64 [[INDVARS_IV_UNR]], 1
; X280-PROLOG-NEXT:    [[EPIL_ITER_CMP:%.*]] = icmp ne i32 1, [[XTRAITER]]
; X280-PROLOG-NEXT:    br i1 [[EPIL_ITER_CMP]], label %[[FOR_BODY_EPIL_1:.*]], label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA:.*]]
; X280-PROLOG:       [[FOR_BODY_EPIL_1]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_EPIL]]
; X280-PROLOG-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX_EPIL_1]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL_1:%.*]] = add nsw i32 [[TMP11]], [[ADD_EPIL]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_EPIL_1:%.*]] = add i64 [[INDVARS_IV_UNR]], 2
; X280-PROLOG-NEXT:    [[EPIL_ITER_CMP_1:%.*]] = icmp ne i32 2, [[XTRAITER]]
; X280-PROLOG-NEXT:    br i1 [[EPIL_ITER_CMP_1]], label %[[FOR_BODY_EPIL_2:.*]], label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]]
; X280-PROLOG:       [[FOR_BODY_EPIL_2]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_EPIL_1]]
; X280-PROLOG-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX_EPIL_2]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL_2:%.*]] = add nsw i32 [[TMP12]], [[ADD_EPIL_1]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_EPIL_2:%.*]] = add i64 [[INDVARS_IV_UNR]], 3
; X280-PROLOG-NEXT:    [[EPIL_ITER_CMP_2:%.*]] = icmp ne i32 3, [[XTRAITER]]
; X280-PROLOG-NEXT:    br i1 [[EPIL_ITER_CMP_2]], label %[[FOR_BODY_EPIL_3:.*]], label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]]
; X280-PROLOG:       [[FOR_BODY_EPIL_3]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL_3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_EPIL_2]]
; X280-PROLOG-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX_EPIL_3]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL_3:%.*]] = add nsw i32 [[TMP13]], [[ADD_EPIL_2]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_EPIL_3:%.*]] = add i64 [[INDVARS_IV_UNR]], 4
; X280-PROLOG-NEXT:    [[EPIL_ITER_CMP_3:%.*]] = icmp ne i32 4, [[XTRAITER]]
; X280-PROLOG-NEXT:    br i1 [[EPIL_ITER_CMP_3]], label %[[FOR_BODY_EPIL_4:.*]], label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]]
; X280-PROLOG:       [[FOR_BODY_EPIL_4]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL_4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_EPIL_3]]
; X280-PROLOG-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX_EPIL_4]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL_4:%.*]] = add nsw i32 [[TMP14]], [[ADD_EPIL_3]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_EPIL_4:%.*]] = add i64 [[INDVARS_IV_UNR]], 5
; X280-PROLOG-NEXT:    [[EPIL_ITER_CMP_4:%.*]] = icmp ne i32 5, [[XTRAITER]]
; X280-PROLOG-NEXT:    br i1 [[EPIL_ITER_CMP_4]], label %[[FOR_BODY_EPIL_5:.*]], label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]]
; X280-PROLOG:       [[FOR_BODY_EPIL_5]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL_5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_EPIL_4]]
; X280-PROLOG-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX_EPIL_5]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL_5:%.*]] = add nsw i32 [[TMP15]], [[ADD_EPIL_4]]
; X280-PROLOG-NEXT:    [[INDVARS_IV_NEXT_EPIL_5:%.*]] = add i64 [[INDVARS_IV_UNR]], 6
; X280-PROLOG-NEXT:    [[EPIL_ITER_CMP_5:%.*]] = icmp ne i32 6, [[XTRAITER]]
; X280-PROLOG-NEXT:    br i1 [[EPIL_ITER_CMP_5]], label %[[FOR_BODY_EPIL_6:.*]], label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]]
; X280-PROLOG:       [[FOR_BODY_EPIL_6]]:
; X280-PROLOG-NEXT:    [[ARRAYIDX_EPIL_6:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_EPIL_5]]
; X280-PROLOG-NEXT:    [[TMP16:%.*]] = load i32, ptr [[ARRAYIDX_EPIL_6]], align 4
; X280-PROLOG-NEXT:    [[ADD_EPIL_6:%.*]] = add nsw i32 [[TMP16]], [[ADD_EPIL_5]]
; X280-PROLOG-NEXT:    br label %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]]
; X280-PROLOG:       [[FOR_END_LOOPEXIT_EPILOG_LCSSA]]:
; X280-PROLOG-NEXT:    [[ADD_LCSSA_PH1:%.*]] = phi i32 [ [[ADD_EPIL]], %[[FOR_BODY_EPIL]] ], [ [[ADD_EPIL_1]], %[[FOR_BODY_EPIL_1]] ], [ [[ADD_EPIL_2]], %[[FOR_BODY_EPIL_2]] ], [ [[ADD_EPIL_3]], %[[FOR_BODY_EPIL_3]] ], [ [[ADD_EPIL_4]], %[[FOR_BODY_EPIL_4]] ], [ [[ADD_EPIL_5]], %[[FOR_BODY_EPIL_5]] ], [ [[ADD_EPIL_6]], %[[FOR_BODY_EPIL_6]] ]
; X280-PROLOG-NEXT:    br label %[[FOR_END_LOOPEXIT]]
; X280-PROLOG:       [[FOR_END_LOOPEXIT]]:
; X280-PROLOG-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD_LCSSA_PH]], %[[FOR_END_LOOPEXIT_UNR_LCSSA]] ], [ [[ADD_LCSSA_PH1]], %[[FOR_END_LOOPEXIT_EPILOG_LCSSA]] ]
; X280-PROLOG-NEXT:    br label %[[FOR_END]]
; X280-PROLOG:       [[FOR_END]]:
; X280-PROLOG-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD_LCSSA]], %[[FOR_END_LOOPEXIT]] ]
; X280-PROLOG-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
; P470-EPILOG-LABEL: define i32 @test(
; P470-EPILOG-SAME: ptr nocapture [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; P470-EPILOG-NEXT:  [[ENTRY:.*]]:
; P470-EPILOG-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; P470-EPILOG-NEXT:    br i1 [[CMP1]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; P470-EPILOG:       [[FOR_BODY_PREHEADER]]:
; P470-EPILOG-NEXT:    br label %[[FOR_BODY:.*]]
; P470-EPILOG:       [[FOR_BODY]]:
; P470-EPILOG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; P470-EPILOG-NEXT:    [[SUM_02:%.*]] = phi i32 [ [[ADD:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; P470-EPILOG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; P470-EPILOG-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; P470-EPILOG-NEXT:    [[ADD]] = add nsw i32 [[TMP0]], [[SUM_02]]
; P470-EPILOG-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 1
; P470-EPILOG-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; P470-EPILOG-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], [[N]]
; P470-EPILOG-NEXT:    br i1 [[EXITCOND]], label %[[FOR_END_LOOPEXIT:.*]], label %[[FOR_BODY]]
; P470-EPILOG:       [[FOR_END_LOOPEXIT]]:
; P470-EPILOG-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[FOR_BODY]] ]
; P470-EPILOG-NEXT:    br label %[[FOR_END]]
; P470-EPILOG:       [[FOR_END]]:
; P470-EPILOG-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD_LCSSA]], %[[FOR_END_LOOPEXIT]] ]
; P470-EPILOG-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
; P470-PROLOG-LABEL: define i32 @test(
; P470-PROLOG-SAME: ptr nocapture [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; P470-PROLOG-NEXT:  [[ENTRY:.*]]:
; P470-PROLOG-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; P470-PROLOG-NEXT:    br i1 [[CMP1]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; P470-PROLOG:       [[FOR_BODY_PREHEADER]]:
; P470-PROLOG-NEXT:    br label %[[FOR_BODY:.*]]
; P470-PROLOG:       [[FOR_BODY]]:
; P470-PROLOG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; P470-PROLOG-NEXT:    [[SUM_02:%.*]] = phi i32 [ [[ADD:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; P470-PROLOG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; P470-PROLOG-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; P470-PROLOG-NEXT:    [[ADD]] = add nsw i32 [[TMP0]], [[SUM_02]]
; P470-PROLOG-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 1
; P470-PROLOG-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; P470-PROLOG-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], [[N]]
; P470-PROLOG-NEXT:    br i1 [[EXITCOND]], label %[[FOR_END_LOOPEXIT:.*]], label %[[FOR_BODY]]
; P470-PROLOG:       [[FOR_END_LOOPEXIT]]:
; P470-PROLOG-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], %[[FOR_BODY]] ]
; P470-PROLOG-NEXT:    br label %[[FOR_END]]
; P470-PROLOG:       [[FOR_END]]:
; P470-PROLOG-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD_LCSSA]], %[[FOR_END_LOOPEXIT]] ]
; P470-PROLOG-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
entry:
  %cmp1 = icmp eq i32 %n, 0
  br i1 %cmp1, label %for.end, label %for.body

for.body:                                         ; preds = %for.body, %entry
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body ], [ 0, %entry ]
  %sum.02 = phi i32 [ %add, %for.body ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i32, ptr %a, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %0, %sum.02
  %indvars.iv.next = add i64 %indvars.iv, 1
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:                                          ; preds = %for.body, %entry
  %sum.0.lcssa = phi i32 [ 0, %entry ], [ %add, %for.body ]
  ret i32 %sum.0.lcssa
}


