; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -passes=loop-unroll -mtriple=riscv64 -allow-epilog-peeling -verify-dom-info | FileCheck %s

declare void @f1()

; Test that we only peel off iterations if it simplifies a condition in the
; loop body after peeling at most MaxPeelCount iterations.  This is a false
; positive for epilog peeling.
define void @test1_epilog_peeling(i32 %k) {
; CHECK-LABEL: @test1_epilog_peeling(
; CHECK-NEXT:  for.body.lr.ph:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_05:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[I_05]], 9999
; CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; CHECK:       if.then:
; CHECK-NEXT:    call void @f1()
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INC]] = add nsw i32 [[I_05]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[INC]], [[K:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END:%.*]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
for.body.lr.ph:
  br label %for.body

for.body:
  %i.05 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.inc ]
  %cmp1 = icmp ult i32 %i.05, 9999
  br i1 %cmp1, label %if.then, label %for.inc

if.then:
  call void @f1()
  br label %for.inc

for.inc:
  %inc = add nsw i32 %i.05, 1
  %cmp = icmp slt i32 %inc, %k
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

; Test epilog peeling for a condition that does not resolve in SE
; for determining if the predicate is known, this is a false positive until
; another method is found to reconcile the backedge taken count against
; the right hand scev as a known predicate.
; peeling iterations within MaxPeelCount iterations of the exit condition.
define void @test2_epilog_peeling(i32 %k) {
; CHECK-LABEL: @test2_epilog_peeling(
; CHECK-NEXT:  for.body.lr.ph:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[TMP3:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH:%.*]] ], [ [[DOTPH:%.*]], [[FOR_END_PEEL_BEGIN_LOOPEXIT1:%.*]] ]
; CHECK-NEXT:    [[CMP1_PEEL:%.*]] = icmp ult i32 [[TMP3]], [[K1:%.*]]
; CHECK-NEXT:    br i1 [[CMP1_PEEL]], label [[IF_THEN:%.*]], label [[FOR_END_PEEL_BEGIN_LOOPEXIT1]]
; CHECK:       if.then:
; CHECK-NEXT:    call void @f1()
; CHECK-NEXT:    br label [[FOR_END_PEEL_BEGIN_LOOPEXIT1]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[DOTPH]] = add nsw i32 [[TMP3]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[DOTPH]], [[K1]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END:%.*]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
for.body.lr.ph:
  br label %for.body

for.body:
  %i.05 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.inc ]
  %cmp1 = icmp ult i32 %i.05, %k
  br i1 %cmp1, label %if.then, label %for.inc

if.then:
  call void @f1()
  br label %for.inc

for.inc:
  %inc = add nsw i32 %i.05, 1
  %cmp = icmp ne i32 %inc, %k
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

; Test compare to eliminate algorithm for peeling as false positive with
; SE having issues with trip increment larger than 1.
define void @test3_epilog_peeling(i32 %k) {
; CHECK-LABEL: @test3_epilog_peeling(
; CHECK-NEXT:  for.body.lr.ph:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_05:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[I_05]], 2147483644
; CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; CHECK:       if.then:
; CHECK-NEXT:    call void @f1()
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INC]] = add nsw i32 [[I_05]], 2
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[INC]], [[K:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END:%.*]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
for.body.lr.ph:
  br label %for.body

for.body:
  %i.05 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.inc ]
  %cmp1 = icmp ult i32 %i.05, 2147483644
  br i1 %cmp1, label %if.then, label %for.inc

if.then:
  call void @f1()
  br label %for.inc

for.inc:
  %inc = add nsw i32 %i.05, 2
  %cmp = icmp slt i32 %inc, %k
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

; Test compare to eliminate algorithm for peeling as false positive with
; SE having issues with negative trip increments.
define void @test4_epilog_peeling(i32 %k) {
; CHECK-LABEL: @test4_epilog_peeling(
; CHECK-NEXT:  for.body.lr.ph:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_05:%.*]] = phi i32 [ [[K:%.*]], [[FOR_BODY_LR_PH:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i32 [[I_05]], 2
; CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; CHECK:       if.then:
; CHECK-NEXT:    call void @f1()
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INC]] = add nsw i32 [[I_05]], -1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INC]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END:%.*]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
for.body.lr.ph:
  br label %for.body

for.body:
  %i.05 = phi i32 [ %k, %for.body.lr.ph ], [ %inc, %for.inc ]
  %cmp1 = icmp ult i32 %i.05, 2
  br i1 %cmp1, label %if.then, label %for.inc

if.then:
  call void @f1()
  br label %for.inc

for.inc:
  %inc = add nsw i32 %i.05, -1
  %cmp = icmp ne i32 %inc, 0
  br i1 %cmp, label %for.body, label %for.end

for.end:
  ret void
}

; Test epilog peeling for a condition that will simplify the loop by
; peeling iterations within MaxPeelCount iterations of the exit condition while
; implementing folds for the bounds in an inner loop.
define void @test5_epilog_peeling(i32 noundef signext %L, ptr noundef %hmm, ptr noundef %M, ptr noundef %tsc) {
; CHECK-LABEL: @test5_epilog_peeling(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BOUNDS:%.*]] = load i32, ptr [[M:%.*]], align 8
; CHECK-NEXT:    [[I24:%.*]] = load ptr, ptr [[TSC:%.*]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[BOUNDS]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP4]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i64 [[TMP1]], -2
; CHECK-NEXT:    br label [[FOR_OUTER:%.*]]
; CHECK:       for.outer:
; CHECK-NEXT:    [[IV_OUTER:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[IV_OUTER_NEXT:%.*]], [[FOR_INC_OUTER:%.*]] ]
; CHECK-NEXT:    [[SEXT:%.*]] = sext i32 [[BOUNDS]] to i64
; CHECK-NEXT:    [[BOUNDS_INC:%.*]] = add i32 [[BOUNDS]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[BOUNDS]], 1
; CHECK-NEXT:    br i1 [[CMP1]], label [[FOR_INC_OUTER]], label [[FOR_INNER_PREHEADER:%.*]]
; CHECK:       for.inner.preheader:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[BOUNDS_INC]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ne i64 [[TMP2]], 0
; CHECK-NEXT:    br i1 [[TMP3]], label [[FOR_INNER_PREHEADER_SPLIT:%.*]], label [[FOR_INNER_PEEL:%.*]]
; CHECK:       for.inner.preheader.split:
; CHECK-NEXT:    br label [[FOR_INNER:%.*]]
; CHECK:       for.inner:
; CHECK-NEXT:    [[IV_INNER:%.*]] = phi i64 [ 1, [[FOR_INNER_PREHEADER_SPLIT]] ], [ [[IV_INNER_NEXT:%.*]], [[FOR_INC_INNER:%.*]] ]
; CHECK-NEXT:    br i1 true, label [[IF_THEN:%.*]], label [[FOR_INC_INNER]]
; CHECK:       if.then:
; CHECK-NEXT:    [[ARRAYIDX174:%.*]] = getelementptr inbounds i32, ptr [[I24]], i64 [[IV_INNER]]
; CHECK-NEXT:    store i32 1, ptr [[ARRAYIDX174]], align 4
; CHECK-NEXT:    br label [[FOR_INC_INNER]]
; CHECK:       for.inc.inner:
; CHECK-NEXT:    [[IV_INNER_NEXT]] = add nuw nsw i64 [[IV_INNER]], 1
; CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[BOUNDS]] to i64
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[IV_INNER_NEXT]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_INNER]], label [[FOR_INNER_LOOPEXIT_PEEL_BEGIN_LOOPEXIT:%.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       for.inner.loopexit.peel.begin.loopexit:
; CHECK-NEXT:    [[LABEL:%.*]] = phi i64 [ [[IV_INNER_NEXT]], [[FOR_INC_INNER]] ]
; CHECK-NEXT:    br label [[FOR_INNER_PEEL]]
; CHECK:       for.inner.loopexit.peel.begin:
; CHECK-NEXT:    [[TMP5:%.*]] = phi i64 [ 1, [[FOR_INNER_PREHEADER]] ], [ [[LABEL]], [[FOR_INNER_LOOPEXIT_PEEL_BEGIN_LOOPEXIT]] ]
; CHECK-NEXT:    br label [[FOR_INNER_PEEL1:%.*]]
; CHECK:       for.inner.peel:
; CHECK-NEXT:    [[CMP2_PEEL:%.*]] = icmp slt i64 [[TMP5]], [[SEXT]]
; CHECK-NEXT:    br i1 [[CMP2_PEEL]], label [[IF_THEN_PEEL:%.*]], label [[FOR_INC_INNER_PEEL:%.*]]
; CHECK:       if.then.peel:
; CHECK-NEXT:    [[ARRAYIDX174_PEEL:%.*]] = getelementptr inbounds i32, ptr [[I24]], i64 [[TMP5]]
; CHECK-NEXT:    store i32 1, ptr [[ARRAYIDX174_PEEL]], align 4
; CHECK-NEXT:    br label [[FOR_INC_INNER_PEEL]]
; CHECK:       for.inc.inner.peel:
; CHECK-NEXT:    [[IV_INNER_NEXT_PEEL:%.*]] = add nuw nsw i64 [[TMP5]], 1
; CHECK-NEXT:    [[EXITCOND_PEEL:%.*]] = icmp ne i64 [[IV_INNER_NEXT_PEEL]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND_PEEL]], label [[FOR_INNER_LOOPEXIT_PEEL_NEXT:%.*]], label [[FOR_INNER_LOOPEXIT_PEEL_NEXT]]
; CHECK:       for.inner.loopexit.peel.next:
; CHECK-NEXT:    br label [[FOR_INNER_PEEL_NEXT:%.*]]
; CHECK:       for.inner.peel.next:
; CHECK-NEXT:    br label [[FOR_INNER_LOOPEXIT:%.*]]
; CHECK:       for.inner.loopexit:
; CHECK-NEXT:    br label [[FOR_INC_OUTER]]
; CHECK:       for.inc.outer:
; CHECK-NEXT:    [[IV_OUTER_NEXT]] = add nuw nsw i32 [[IV_OUTER]], 1
; CHECK-NEXT:    [[CMP37_NOT_NOT:%.*]] = icmp slt i32 [[IV_OUTER]], [[L:%.*]]
; CHECK-NEXT:    br i1 [[CMP37_NOT_NOT]], label [[FOR_OUTER]], label [[EXIT_OUTER:%.*]]
; CHECK:       exit.outer:
; CHECK-NEXT:    ret void
;
entry:
  %bounds = load i32, ptr %M, align 8
  %i24 = load ptr, ptr %tsc, align 8
  br label %for.outer

for.outer:
  %iv.outer = phi i32 [ 1, %entry ], [ %iv.outer.next, %for.inc.outer ]
  %sext = sext i32 %bounds to i64
  %bounds.inc = add i32 %bounds, 1
  %cmp1 = icmp slt i32 %bounds, 1
  br i1 %cmp1, label %for.inc.outer, label %for.inner.preheader

for.inner.preheader:
  %wide.trip.count = zext i32 %bounds.inc to i64
  br label %for.inner

for.inner:
  %iv.inner = phi i64 [ 1, %for.inner.preheader ], [ %iv.inner.next, %for.inc.inner ]
  %cmp2 = icmp slt i64 %iv.inner, %sext
  br i1 %cmp2, label %if.then, label %for.inc.inner

if.then:
  %arrayidx174 = getelementptr inbounds i32, ptr %i24, i64 %iv.inner
  store i32 1, ptr %arrayidx174, align 4
  br label %for.inc.inner

for.inc.inner:
  %iv.inner.next = add nuw nsw i64 %iv.inner, 1
  %exitcond = icmp ne i64 %iv.inner.next, %wide.trip.count
  br i1 %exitcond, label %for.inner, label %for.inner.loopexit

for.inner.loopexit:
  br label %for.inc.outer

for.inc.outer:
  %iv.outer.next = add nuw nsw i32 %iv.outer, 1
  %cmp37.not.not = icmp slt i32 %iv.outer, %L
  br i1 %cmp37.not.not, label %for.outer, label %exit.outer

exit.outer:
  ret void
}

; test epilog peeling not crashing on this loop
define void @SetCoeffAndReconstruction8x8(i64 %indvars.iv383) !prof !0 {
; CHECK-LABEL: @SetCoeffAndReconstruction8x8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND394_PREHEADER_LOOPEXIT1:%.*]]
; CHECK:       for.cond394.preheader.loopexit:
; CHECK-NEXT:    br label [[FOR_COND394_PREHEADER_LOOPEXIT1]]
; CHECK:       for.cond394.preheader:
; CHECK-NEXT:    br label [[FOR_BODY405_PEEL2:%.*]]
; CHECK:       for.body405:
; CHECK-NEXT:    [[INDVARS_IV_NEXT384_PEEL:%.*]] = phi i64 [ [[INDVARS_IV_NEXT384_PEEL4:%.*]], [[FOR_BODY405_PEEL2]] ], [ 0, [[FOR_COND394_PREHEADER_LOOPEXIT1]] ]
; CHECK-NEXT:    [[ARRAYIDX413_PEEL3:%.*]] = getelementptr i32, ptr null, i64 [[INDVARS_IV383:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr null, align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT384_PEEL4]] = add i64 [[INDVARS_IV_NEXT384_PEEL]], 1
; CHECK-NEXT:    [[EXITCOND386_NOT_PEEL5:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT384_PEEL4]], 65
; CHECK-NEXT:    br i1 [[EXITCOND386_NOT_PEEL5]], label [[FOR_COND394_PREHEADER_LOOPEXIT:%.*]], label [[FOR_BODY405_PEEL2]], !prof [[PROF3:![0-9]+]]
;
entry:
  br label %for.cond394.preheader

for.cond394.preheader:                            ; preds = %for.body405, %entry
  br label %for.body405

for.body405:                                      ; preds = %for.body405, %for.cond394.preheader
  %indvars.iv3831 = phi i64 [ %indvars.iv.next384, %for.body405 ], [ 0, %for.cond394.preheader ]
  %arrayidx413 = getelementptr i32, ptr null, i64 %indvars.iv383
  %0 = load i32, ptr null, align 4
  %indvars.iv.next384 = add i64 %indvars.iv3831, 1
  %exitcond386.not = icmp eq i64 %indvars.iv.next384, 65
  br i1 %exitcond386.not, label %for.cond394.preheader, label %for.body405, !prof !1
}

!0 = !{!"function_entry_count", i64 112759}
!1 = !{!"branch_weights", i32 5412433, i32 5412433}
