; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -passes=loop-unroll -allow-epilog-peeling -mtriple=riscv64 -verify-dom-info | FileCheck %s

; Test case that prohibits epilog peeling when cmp operands source a value is regularly
; unknown.

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @foo(i32 %0, i32 %1)

; Function Attrs: mustprogress nounwind uwtable
define dso_local void @_Z4s276PiS_S_S_i(ptr nocapture noundef %a, ptr nocapture noundef readonly %b, ptr nocapture noundef readonly %c, ptr nocapture noundef readonly %d, i32 noundef signext %len) {
; CHECK-LABEL: define dso_local void @_Z4s276PiS_S_S_i(
; CHECK-SAME: ptr noundef captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]], ptr noundef readonly captures(none) [[C:%.*]], ptr noundef readonly captures(none) [[D:%.*]], i32 noundef signext [[LEN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CALL:%.*]] = call i32 @foo(i32 [[LEN]], i32 2)
; CHECK-NEXT:    [[X:%.*]] = zext i32 [[CALL]] to i64
; CHECK-NEXT:    [[X2:%.*]] = zext i32 [[LEN]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i64 [[INDVARS_IV_NEXT]], [[X]]
; CHECK-NEXT:    br i1 [[CMP1]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i32, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds nuw i32, ptr [[C]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i32, ptr [[ARRAYIDX3]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 [[LD1]], [[LD2]]
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds nuw i32, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LD3:%.*]] = load i32, ptr [[ARRAYIDX5]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ADD6:%.*]] = add nsw i32 [[SUB]], [[LD3]]
; CHECK-NEXT:    store i32 [[ADD6]], ptr [[ARRAYIDX5]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[FOR_INC]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds nuw i32, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LD4:%.*]] = load i32, ptr [[ARRAYIDX8]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds nuw i32, ptr [[D]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LD5:%.*]] = load i32, ptr [[ARRAYIDX10]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[SUB11:%.*]] = sub i32 [[LD4]], [[LD5]]
; CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds nuw i32, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[LD6:%.*]] = load i32, ptr [[ARRAYIDX13]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ADD14:%.*]] = add nsw i32 [[SUB11]], [[LD6]]
; CHECK-NEXT:    store i32 [[ADD14]], ptr [[ARRAYIDX13]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[FOR_INC]]
; CHECK:       [[FOR_INC]]:
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT]], [[X2]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[FOR_BODY]], label %[[FOR_END:.*]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  %call = call i32 @foo(i32 %len, i32 2)
  %x = zext i32 %call to i64
  %x2 = zext i32 %len to i64
  br label %for.body

for.body:                                         ; preds = %entry, %for.inc
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.inc ]
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %cmp1 = icmp ult i64 %indvars.iv.next, %x
  br i1 %cmp1, label %if.then, label %if.else

if.then:                                          ; preds = %for.body
  %arrayidx = getelementptr inbounds nuw i32, ptr %b, i64 %indvars.iv
  %ld1 = load i32, ptr %arrayidx, align 4, !tbaa !9
  %arrayidx3 = getelementptr inbounds nuw i32, ptr %c, i64 %indvars.iv
  %ld2 = load i32, ptr %arrayidx3, align 4, !tbaa !9
  %sub = sub i32 %ld1, %ld2
  %arrayidx5 = getelementptr inbounds nuw i32, ptr %a, i64 %indvars.iv
  %ld3 = load i32, ptr %arrayidx5, align 4, !tbaa !9
  %add6 = add nsw i32 %sub, %ld3
  store i32 %add6, ptr %arrayidx5, align 4, !tbaa !9
  br label %for.inc

if.else:                                          ; preds = %for.body
  %arrayidx8 = getelementptr inbounds nuw i32, ptr %b, i64 %indvars.iv
  %ld4 = load i32, ptr %arrayidx8, align 4, !tbaa !9
  %arrayidx10 = getelementptr inbounds nuw i32, ptr %d, i64 %indvars.iv
  %ld5 = load i32, ptr %arrayidx10, align 4, !tbaa !9
  %sub11 = sub i32 %ld4, %ld5
  %arrayidx13 = getelementptr inbounds nuw i32, ptr %a, i64 %indvars.iv
  %ld6 = load i32, ptr %arrayidx13, align 4, !tbaa !9
  %add14 = add nsw i32 %sub11, %ld6
  store i32 %add14, ptr %arrayidx13, align 4, !tbaa !9
  br label %for.inc

for.inc:                                          ; preds = %if.then, %if.else
  %exitcond = icmp ne i64 %indvars.iv.next, %x2
  br i1 %exitcond, label %for.body, label %for.end, !llvm.loop !13

for.end:                                          ; preds = %for.inc
  ret void
}

!9 = !{!10, !10, i64 0}
!10 = !{!"int", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = distinct !{!13, !14}
!14 = !{!"llvm.loop.mustprogress"}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"int", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"Simple C++ TBAA"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]]}
; CHECK: [[META5]] = !{!"llvm.loop.mustprogress"}
;.
