; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -passes=loop-unroll -mtriple=riscv64 -verify-dom-info | FileCheck %s

; Test case where epilog peeling is prohibited by cmp operands which source a non loop phi,
; making the value difficult to evaluate.

%struct.b2Vec2 = type { float, float }

$_ZTI7b2Shape = comdat any
$_ZTS7b2Shape = comdat any

@.str = private unnamed_addr constant [25 x i8] c"3 <= count && count <= 8\00", align 1
@.str.1 = private unnamed_addr constant [60 x i8] c"third_party/box2d/Box2D/Collision/Shapes/b2PolygonShape.cpp\00", align 1
@__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i = private unnamed_addr constant [48 x i8] c"void b2PolygonShape::Set(const b2Vec2 *, int32)\00", align 1
@.str.2 = private unnamed_addr constant [6 x i8] c"false\00", align 1
@.str.3 = private unnamed_addr constant [6 x i8] c"m < 8\00", align 1
@.str.4 = private unnamed_addr constant [55 x i8] c"edge.LengthSquared() > 1.19209290e-7F * 1.19209290e-7F\00", align 1
@.str.5 = private unnamed_addr constant [44 x i8] c"0.0f <= lower && lower <= input.maxFraction\00", align 1
@__PRETTY_FUNCTION__._ZNK14b2PolygonShape7RayCastEP15b2RayCastOutputRK14b2RayCastInputRK11b2Transformi = private unnamed_addr constant [114 x i8] c"virtual bool b2PolygonShape::RayCast(b2RayCastOutput *, const b2RayCastInput &, const b2Transform &, int32) const\00", align 1
@.str.6 = private unnamed_addr constant [13 x i8] c"m_count >= 3\00", align 1
@__PRETTY_FUNCTION__._ZNK14b2PolygonShape11ComputeMassEP10b2MassDataf = private unnamed_addr constant [70 x i8] c"virtual void b2PolygonShape::ComputeMass(b2MassData *, float32) const\00", align 1
@.str.7 = private unnamed_addr constant [22 x i8] c"area > 1.19209290e-7F\00", align 1
@_ZTI14b2PolygonShape = hidden constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS14b2PolygonShape, ptr @_ZTI7b2Shape }, align 8
@_ZTVN10__cxxabiv120__si_class_type_infoE = external global [0 x ptr]
@_ZTS14b2PolygonShape = hidden constant [17 x i8] c"14b2PolygonShape\00", align 1
@_ZTI7b2Shape = linkonce_odr hidden constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS7b2Shape }, comdat, align 8
@_ZTVN10__cxxabiv117__class_type_infoE = external global [0 x ptr]
@_ZTS7b2Shape = linkonce_odr hidden constant [9 x i8] c"7b2Shape\00", comdat, align 1
@__PRETTY_FUNCTION__._ZL15ComputeCentroidPK6b2Vec2i = private unnamed_addr constant [46 x i8] c"b2Vec2 ComputeCentroid(const b2Vec2 *, int32)\00", align 1

define hidden void @_ZN14b2PolygonShape3SetEPK6b2Vec2i(ptr nocapture noundef nonnull align 8 dereferenceable(156) %this, ptr nocapture noundef readonly %vertices, i32 noundef signext %count) align 2 {
; CHECK-LABEL: define hidden void @_ZN14b2PolygonShape3SetEPK6b2Vec2i(
; CHECK-SAME: ptr noundef nonnull align 8 captures(none) dereferenceable(156) [[THIS:%.*]], ptr noundef readonly captures(none) [[VERTICES:%.*]], i32 noundef signext [[COUNT:%.*]]) align 2 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[PS:%.*]] = alloca [8 x %struct.b2Vec2], align 8
; CHECK-NEXT:    [[HULL:%.*]] = alloca [8 x i32], align 8
; CHECK-NEXT:    [[I:%.*]] = add i32 [[COUNT]], -3
; CHECK-NEXT:    [[I1:%.*]] = icmp ult i32 [[I]], 6
; CHECK-NEXT:    br i1 [[I1]], label %[[IF_END:.*]], label %[[COND_FALSE:.*]]
; CHECK:       [[COND_FALSE]]:
; CHECK-NEXT:    tail call void @__assert_fail(ptr noundef nonnull @.str, ptr noundef nonnull @.str.1, i32 noundef signext 122, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
; CHECK-NEXT:    unreachable
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 64, ptr nonnull [[PS]])
; CHECK-NEXT:    br label %[[FOR_COND_PREHEADER:.*]]
; CHECK:       [[FOR_COND_PREHEADER]]:
; CHECK-NEXT:    [[CMP492:%.*]] = icmp sgt i32 [[COUNT]], 0
; CHECK-NEXT:    br i1 [[CMP492]], label %[[FOR_BODY_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT125:%.*]] = zext i32 [[COUNT]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT:.*]]:
; CHECK-NEXT:    [[TEMPCOUNT_1_LCSSA:%.*]] = phi i32 [ [[TEMPCOUNT_1:%.*]], %[[IF_END19:.*]] ]
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[TEMPCOUNT_0_LCSSA:%.*]] = phi i32 [ 0, %[[FOR_COND_PREHEADER]] ], [ [[TEMPCOUNT_1_LCSSA]], %[[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[CMP24:%.*]] = icmp slt i32 [[TEMPCOUNT_0_LCSSA]], 3
; CHECK-NEXT:    br i1 [[CMP24]], label %[[IF_THEN25:.*]], label %[[IF_END26:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV122:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT123:%.*]], %[[IF_END19]] ]
; CHECK-NEXT:    [[TEMPCOUNT_094:%.*]] = phi i32 [ [[TEMPCOUNT_1]], %[[IF_END19]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_B2VEC2:%.*]], ptr [[VERTICES]], i64 [[INDVARS_IV122]]
; CHECK-NEXT:    [[I2:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX]], i64 4
; CHECK-NEXT:    [[I3:%.*]] = load i32, ptr [[ARRAYIDX_SROA_IDX]], align 4
; CHECK-NEXT:    [[I4:%.*]] = bitcast i32 [[I2]] to float
; CHECK-NEXT:    [[I5:%.*]] = bitcast i32 [[I3]] to float
; CHECK-NEXT:    [[CMP690:%.*]] = icmp sgt i32 [[TEMPCOUNT_094]], 0
; CHECK-NEXT:    br i1 [[CMP690]], label %[[FOR_BODY8_PREHEADER:.*]], label %[[IF_THEN15_CRITEDGE:.*]]
; CHECK:       [[FOR_BODY8_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[TEMPCOUNT_094]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY8:.*]]
; CHECK:       [[FOR_COND5:.*]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nuw nsw i64 [[INDVARS_IV:%.*]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[FOR_BODY8]], label %[[IF_THEN15_CRITEDGE_LOOPEXIT:.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[FOR_BODY8]]:
; CHECK-NEXT:    [[INDVARS_IV]] = phi i64 [ 0, %[[FOR_BODY8_PREHEADER]] ], [ [[INDVARS_IV_NEXT]], %[[FOR_COND5]] ]
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[I6:%.*]] = load float, ptr [[ARRAYIDX10]], align 4, !tbaa [[TBAA2:![0-9]+]]
; CHECK-NEXT:    [[SUB_I_I:%.*]] = fsub fast float [[I4]], [[I6]]
; CHECK-NEXT:    [[Y2_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX10]], i64 4
; CHECK-NEXT:    [[I7:%.*]] = load float, ptr [[Y2_I_I]], align 4, !tbaa [[TBAA7:![0-9]+]]
; CHECK-NEXT:    [[SUB3_I_I:%.*]] = fsub fast float [[I5]], [[I7]]
; CHECK-NEXT:    [[MUL_I_I:%.*]] = fmul fast float [[SUB_I_I]], [[SUB_I_I]]
; CHECK-NEXT:    [[MUL3_I_I:%.*]] = fmul fast float [[SUB3_I_I]], [[SUB3_I_I]]
; CHECK-NEXT:    [[ADD_I_I:%.*]] = fadd fast float [[MUL3_I_I]], [[MUL_I_I]]
; CHECK-NEXT:    [[CMP12:%.*]] = fcmp fast olt float [[ADD_I_I]], 0x3EDA36E2E0000000
; CHECK-NEXT:    br i1 [[CMP12]], label %[[IF_END19_LOOPEXIT:.*]], label %[[FOR_COND5]]
; CHECK:       [[IF_THEN15_CRITEDGE_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[IF_THEN15_CRITEDGE]]
; CHECK:       [[IF_THEN15_CRITEDGE]]:
; CHECK-NEXT:    [[INC16:%.*]] = add nsw i32 [[TEMPCOUNT_094]], 1
; CHECK-NEXT:    [[IDXPROM17:%.*]] = sext i32 [[TEMPCOUNT_094]] to i64
; CHECK-NEXT:    [[ARRAYIDX18:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[IDXPROM17]]
; CHECK-NEXT:    store i32 [[I2]], ptr [[ARRAYIDX18]], align 8
; CHECK-NEXT:    [[ARRAYIDX18_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX18]], i64 4
; CHECK-NEXT:    store i32 [[I3]], ptr [[ARRAYIDX18_SROA_IDX]], align 4
; CHECK-NEXT:    br label %[[IF_END19]]
; CHECK:       [[IF_END19_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[IF_END19]]
; CHECK:       [[IF_END19]]:
; CHECK-NEXT:    [[TEMPCOUNT_1]] = phi i32 [ [[INC16]], %[[IF_THEN15_CRITEDGE]] ], [ [[TEMPCOUNT_094]], %[[IF_END19_LOOPEXIT]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT123]] = add nuw nsw i64 [[INDVARS_IV122]], 1
; CHECK-NEXT:    [[EXITCOND126:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT123]], [[WIDE_TRIP_COUNT125]]
; CHECK-NEXT:    br i1 [[EXITCOND126]], label %[[FOR_BODY]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[IF_THEN25]]:
; CHECK-NEXT:    tail call void @__assert_fail(ptr noundef nonnull @.str.2, ptr noundef nonnull @.str.1, i32 noundef signext 158, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
; CHECK-NEXT:    unreachable
; CHECK:       [[IF_END26]]:
; CHECK-NEXT:    [[I8:%.*]] = load float, ptr [[PS]], align 8, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[WIDE_TRIP_COUNT130:%.*]] = zext i32 [[TEMPCOUNT_0_LCSSA]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY32:.*]]
; CHECK:       [[FOR_COND_CLEANUP31:.*]]:
; CHECK-NEXT:    [[I0_1_LCSSA:%.*]] = phi i32 [ [[I0_1:%.*]], %[[IF_END46:.*]] ]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[HULL]])
; CHECK-NEXT:    br i1 true, label %[[FOR_COND51_US_PREHEADER:.*]], label %[[FOR_COND_CLEANUP31_SPLIT:.*]]
; CHECK:       [[FOR_COND51_US_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_COND51_US:.*]]
; CHECK:       [[FOR_COND51_US]]:
; CHECK-NEXT:    [[INDVARS_IV137:%.*]] = phi i64 [ 0, %[[FOR_COND51_US_PREHEADER]] ], [ [[INDVARS_IV_NEXT138:%.*]], %[[FOR_COND59_FOR_COND_CLEANUP61_CRIT_EDGE_US:.*]] ]
; CHECK-NEXT:    [[IH_0_US:%.*]] = phi i32 [ [[IE_3_US_LCSSA:%.*]], %[[FOR_COND59_FOR_COND_CLEANUP61_CRIT_EDGE_US]] ], [ [[I0_1_LCSSA]], %[[FOR_COND51_US_PREHEADER]] ]
; CHECK-NEXT:    [[EXITCOND140:%.*]] = icmp ne i64 [[INDVARS_IV137]], 8
; CHECK-NEXT:    br i1 [[EXITCOND140]], label %[[COND_END55_US:.*]], label %[[COND_FALSE54_LOOPEXIT:.*]]
; CHECK:       [[COND_END55_US]]:
; CHECK-NEXT:    [[ARRAYIDX57_US:%.*]] = getelementptr inbounds [8 x i32], ptr [[HULL]], i64 0, i64 [[INDVARS_IV137]]
; CHECK-NEXT:    store i32 [[IH_0_US]], ptr [[ARRAYIDX57_US]], align 4, !tbaa [[TBAA9:![0-9]+]]
; CHECK-NEXT:    [[IDXPROM70_US:%.*]] = sext i32 [[IH_0_US]] to i64
; CHECK-NEXT:    [[ARRAYIDX71_US:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[IDXPROM70_US]]
; CHECK-NEXT:    [[Y2_I_US:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX71_US]], i64 4
; CHECK-NEXT:    [[WIDE_TRIP_COUNT135:%.*]] = zext i32 [[TEMPCOUNT_0_LCSSA]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY62_US:.*]]
; CHECK:       [[FOR_BODY62_US]]:
; CHECK-NEXT:    [[INDVARS_IV132:%.*]] = phi i64 [ 1, %[[COND_END55_US]] ], [ [[INDVARS_IV_NEXT133:%.*]], %[[FOR_INC92_US:.*]] ]
; CHECK-NEXT:    [[IE_099_US:%.*]] = phi i32 [ 0, %[[COND_END55_US]] ], [ [[IE_3_US:%.*]], %[[FOR_INC92_US]] ]
; CHECK-NEXT:    [[CMP63_US:%.*]] = icmp eq i32 [[IE_099_US]], [[IH_0_US]]
; CHECK-NEXT:    [[I9:%.*]] = trunc nuw nsw i64 [[INDVARS_IV132]] to i32
; CHECK-NEXT:    br i1 [[CMP63_US]], label %[[FOR_INC92_US]], label %[[IF_END65_US:.*]]
; CHECK:       [[IF_END65_US]]:
; CHECK-NEXT:    [[IDXPROM66_US:%.*]] = sext i32 [[IE_099_US]] to i64
; CHECK-NEXT:    [[ARRAYIDX67_US:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[IDXPROM66_US]]
; CHECK-NEXT:    [[I10:%.*]] = load float, ptr [[ARRAYIDX67_US]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[I11:%.*]] = load float, ptr [[ARRAYIDX71_US]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[SUB_I_US:%.*]] = fsub fast float [[I10]], [[I11]]
; CHECK-NEXT:    [[Y_I_US:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX67_US]], i64 4
; CHECK-NEXT:    [[I12:%.*]] = load float, ptr [[Y_I_US]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[I13:%.*]] = load float, ptr [[Y2_I_US]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[SUB3_I_US:%.*]] = fsub fast float [[I12]], [[I13]]
; CHECK-NEXT:    [[ARRAYIDX75_US:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[INDVARS_IV132]]
; CHECK-NEXT:    [[I14:%.*]] = load float, ptr [[ARRAYIDX75_US]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[SUB_I51_US:%.*]] = fsub fast float [[I14]], [[I11]]
; CHECK-NEXT:    [[Y_I52_US:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX75_US]], i64 4
; CHECK-NEXT:    [[I15:%.*]] = load float, ptr [[Y_I52_US]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[SUB3_I54_US:%.*]] = fsub fast float [[I15]], [[I13]]
; CHECK-NEXT:    [[MUL_I_US:%.*]] = fmul fast float [[SUB3_I54_US]], [[SUB_I_US]]
; CHECK-NEXT:    [[MUL3_I_US:%.*]] = fmul fast float [[SUB_I51_US]], [[SUB3_I_US]]
; CHECK-NEXT:    [[SUB_I56_US:%.*]] = fsub fast float [[MUL_I_US]], [[MUL3_I_US]]
; CHECK-NEXT:    [[CMP82_US:%.*]] = fcmp fast olt float [[SUB_I56_US]], 0.000000e+00
; CHECK-NEXT:    [[I16:%.*]] = trunc nuw nsw i64 [[INDVARS_IV132]] to i32
; CHECK-NEXT:    [[IE_1_US:%.*]] = select i1 [[CMP82_US]], i32 [[I16]], i32 [[IE_099_US]]
; CHECK-NEXT:    [[CMP85_US:%.*]] = fcmp fast oeq float [[SUB_I56_US]], 0.000000e+00
; CHECK-NEXT:    br i1 [[CMP85_US]], label %[[LAND_LHS_TRUE86_US:.*]], label %[[FOR_INC92_US]]
; CHECK:       [[LAND_LHS_TRUE86_US]]:
; CHECK-NEXT:    [[MUL_I57_US:%.*]] = fmul fast float [[SUB_I51_US]], [[SUB_I51_US]]
; CHECK-NEXT:    [[MUL4_I_US:%.*]] = fmul fast float [[SUB3_I54_US]], [[SUB3_I54_US]]
; CHECK-NEXT:    [[ADD_I_US:%.*]] = fadd fast float [[MUL4_I_US]], [[MUL_I57_US]]
; CHECK-NEXT:    [[MUL_I59_US:%.*]] = fmul fast float [[SUB_I_US]], [[SUB_I_US]]
; CHECK-NEXT:    [[MUL4_I61_US:%.*]] = fmul fast float [[SUB3_I_US]], [[SUB3_I_US]]
; CHECK-NEXT:    [[ADD_I62_US:%.*]] = fadd fast float [[MUL4_I61_US]], [[MUL_I59_US]]
; CHECK-NEXT:    [[CMP89_US:%.*]] = fcmp fast ogt float [[ADD_I_US]], [[ADD_I62_US]]
; CHECK-NEXT:    br i1 [[CMP89_US]], label %[[IF_THEN90_US:.*]], label %[[FOR_INC92_US]]
; CHECK:       [[IF_THEN90_US]]:
; CHECK-NEXT:    br label %[[FOR_INC92_US]]
; CHECK:       [[FOR_INC92_US]]:
; CHECK-NEXT:    [[IE_3_US]] = phi i32 [ [[I9]], %[[FOR_BODY62_US]] ], [ [[I9]], %[[IF_THEN90_US]] ], [ [[IE_1_US]], %[[LAND_LHS_TRUE86_US]] ], [ [[IE_1_US]], %[[IF_END65_US]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT133]] = add nuw nsw i64 [[INDVARS_IV132]], 1
; CHECK-NEXT:    [[EXITCOND136:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT133]], [[WIDE_TRIP_COUNT135]]
; CHECK-NEXT:    br i1 [[EXITCOND136]], label %[[FOR_BODY62_US]], label %[[FOR_COND59_FOR_COND_CLEANUP61_CRIT_EDGE_US]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[FOR_COND59_FOR_COND_CLEANUP61_CRIT_EDGE_US]]:
; CHECK-NEXT:    [[IE_3_US_LCSSA]] = phi i32 [ [[IE_3_US]], %[[FOR_INC92_US]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT138]] = add nuw nsw i64 [[INDVARS_IV137]], 1
; CHECK-NEXT:    [[CMP97_US:%.*]] = icmp eq i32 [[IE_3_US_LCSSA]], [[I0_1_LCSSA]]
; CHECK-NEXT:    br i1 [[CMP97_US]], label %[[FOR_END101_LOOPEXIT:.*]], label %[[FOR_COND51_US]]
; CHECK:       [[FOR_COND_CLEANUP31_SPLIT]]:
; CHECK-NEXT:    br i1 poison, label %[[FOR_COND51_US103:.*]], label %[[COND_END55_PREHEADER:.*]]
; CHECK:       [[COND_END55_PREHEADER]]:
; CHECK-NEXT:    br label %[[COND_FALSE54_LOOPEXIT119:.*]]
; CHECK:       [[FOR_COND51_US103]]:
; CHECK-NEXT:    br i1 true, label %[[COND_END55_US107:.*]], label %[[COND_FALSE54:.*]]
; CHECK:       [[COND_END55_US107]]:
; CHECK-NEXT:    br label %[[FOR_END101:.*]]
; CHECK:       [[FOR_BODY32]]:
; CHECK-NEXT:    [[INDVARS_IV127:%.*]] = phi i64 [ 1, %[[IF_END26]] ], [ [[INDVARS_IV_NEXT128:%.*]], %[[IF_END46]] ]
; CHECK-NEXT:    [[I0_097:%.*]] = phi i32 [ 0, %[[IF_END26]] ], [ [[I0_1]], %[[IF_END46]] ]
; CHECK-NEXT:    [[X0_096:%.*]] = phi float [ [[I8]], %[[IF_END26]] ], [ [[X0_1:%.*]], %[[IF_END46]] ]
; CHECK-NEXT:    [[ARRAYIDX35:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[INDVARS_IV127]]
; CHECK-NEXT:    [[I17:%.*]] = load float, ptr [[ARRAYIDX35]], align 8, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[CMP37:%.*]] = fcmp fast ogt float [[I17]], [[X0_096]]
; CHECK-NEXT:    br i1 [[CMP37]], label %[[IF_THEN45:.*]], label %[[LOR_LHS_FALSE:.*]]
; CHECK:       [[LOR_LHS_FALSE]]:
; CHECK-NEXT:    [[CMP38:%.*]] = fcmp fast oeq float [[I17]], [[X0_096]]
; CHECK-NEXT:    br i1 [[CMP38]], label %[[LAND_LHS_TRUE:.*]], label %[[IF_END46]]
; CHECK:       [[LAND_LHS_TRUE]]:
; CHECK-NEXT:    [[Y:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX35]], i64 4
; CHECK-NEXT:    [[I18:%.*]] = load float, ptr [[Y]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[IDXPROM41:%.*]] = sext i32 [[I0_097]] to i64
; CHECK-NEXT:    [[Y43:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[IDXPROM41]], i32 1
; CHECK-NEXT:    [[I19:%.*]] = load float, ptr [[Y43]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[CMP44:%.*]] = fcmp fast olt float [[I18]], [[I19]]
; CHECK-NEXT:    br i1 [[CMP44]], label %[[IF_THEN45]], label %[[IF_END46]]
; CHECK:       [[IF_THEN45]]:
; CHECK-NEXT:    [[I20:%.*]] = trunc nuw nsw i64 [[INDVARS_IV127]] to i32
; CHECK-NEXT:    br label %[[IF_END46]]
; CHECK:       [[IF_END46]]:
; CHECK-NEXT:    [[X0_1]] = phi nsz float [ [[I17]], %[[IF_THEN45]] ], [ [[X0_096]], %[[LAND_LHS_TRUE]] ], [ [[X0_096]], %[[LOR_LHS_FALSE]] ]
; CHECK-NEXT:    [[I0_1]] = phi i32 [ [[I20]], %[[IF_THEN45]] ], [ [[I0_097]], %[[LAND_LHS_TRUE]] ], [ [[I0_097]], %[[LOR_LHS_FALSE]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT128]] = add nuw nsw i64 [[INDVARS_IV127]], 1
; CHECK-NEXT:    [[EXITCOND131:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT128]], [[WIDE_TRIP_COUNT130]]
; CHECK-NEXT:    br i1 [[EXITCOND131]], label %[[FOR_BODY32]], label %[[FOR_COND_CLEANUP31]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[COND_FALSE54_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[COND_FALSE54]]
; CHECK:       [[COND_FALSE54_LOOPEXIT119]]:
; CHECK-NEXT:    br label %[[COND_FALSE54]]
; CHECK:       [[COND_FALSE54]]:
; CHECK-NEXT:    tail call void @__assert_fail(ptr noundef nonnull @.str.3, ptr noundef nonnull @.str.1, i32 noundef signext 185, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
; CHECK-NEXT:    unreachable
; CHECK:       [[FOR_END101_LOOPEXIT]]:
; CHECK-NEXT:    [[INC96_US_LCSSA_WIDE:%.*]] = phi i64 [ [[INDVARS_IV_NEXT138]], %[[FOR_COND59_FOR_COND_CLEANUP61_CRIT_EDGE_US]] ]
; CHECK-NEXT:    [[M_0_US_LCSSA120_WIDE:%.*]] = phi i64 [ [[INDVARS_IV137]], %[[FOR_COND59_FOR_COND_CLEANUP61_CRIT_EDGE_US]] ]
; CHECK-NEXT:    [[I21:%.*]] = trunc nuw nsw i64 [[M_0_US_LCSSA120_WIDE]] to i32
; CHECK-NEXT:    [[I22:%.*]] = trunc nuw nsw i64 [[INC96_US_LCSSA_WIDE]] to i32
; CHECK-NEXT:    br label %[[FOR_END101]]
; CHECK:       [[FOR_END101]]:
; CHECK-NEXT:    [[DOTUS_PHI:%.*]] = phi i32 [ poison, %[[COND_END55_US107]] ], [ [[I22]], %[[FOR_END101_LOOPEXIT]] ]
; CHECK-NEXT:    [[DOTUS_PHI102:%.*]] = phi i32 [ poison, %[[COND_END55_US107]] ], [ [[I21]], %[[FOR_END101_LOOPEXIT]] ]
; CHECK-NEXT:    [[CMP102:%.*]] = icmp samesign ult i32 [[DOTUS_PHI102]], 2
; CHECK-NEXT:    br i1 [[CMP102]], label %[[IF_THEN103:.*]], label %[[IF_END104:.*]]
; CHECK:       [[IF_THEN103]]:
; CHECK-NEXT:    tail call void @__assert_fail(ptr noundef nonnull @.str.2, ptr noundef nonnull @.str.1, i32 noundef signext 224, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
; CHECK-NEXT:    unreachable
; CHECK:       [[IF_END104]]:
; CHECK-NEXT:    [[M_COUNT:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 152
; CHECK-NEXT:    store i32 [[DOTUS_PHI]], ptr [[M_COUNT]], align 8, !tbaa [[TBAA13:![0-9]+]]
; CHECK-NEXT:    [[M_VERTICES:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 24
; CHECK-NEXT:    br label %[[FOR_BODY109:.*]]
; CHECK:       [[FOR_COND121_PREHEADER:.*]]:
; CHECK-NEXT:    [[M_VERTICES130:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 24
; CHECK-NEXT:    [[M_NORMALS:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 88
; CHECK-NEXT:    br label %[[FOR_BODY124:.*]]
; CHECK:       [[FOR_BODY109]]:
; CHECK-NEXT:    [[I105_0117:%.*]] = phi i32 [ 0, %[[IF_END104]] ], [ [[INC117:%.*]], %[[FOR_BODY109]] ]
; CHECK-NEXT:    [[IDXPROM110:%.*]] = zext nneg i32 [[I105_0117]] to i64
; CHECK-NEXT:    [[ARRAYIDX111:%.*]] = getelementptr inbounds [8 x i32], ptr [[HULL]], i64 0, i64 [[IDXPROM110]]
; CHECK-NEXT:    [[I23:%.*]] = load i32, ptr [[ARRAYIDX111]], align 4, !tbaa [[TBAA9]]
; CHECK-NEXT:    [[IDXPROM112:%.*]] = sext i32 [[I23]] to i64
; CHECK-NEXT:    [[ARRAYIDX113:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[PS]], i64 0, i64 [[IDXPROM112]]
; CHECK-NEXT:    [[ARRAYIDX115:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[M_VERTICES]], i64 0, i64 [[IDXPROM110]]
; CHECK-NEXT:    [[I24:%.*]] = load i64, ptr [[ARRAYIDX113]], align 8
; CHECK-NEXT:    store i64 [[I24]], ptr [[ARRAYIDX115]], align 8
; CHECK-NEXT:    [[INC117]] = add nuw nsw i32 [[I105_0117]], 1
; CHECK-NEXT:    [[CMP107_NOT_NOT:%.*]] = icmp ult i32 [[I105_0117]], [[DOTUS_PHI102]]
; CHECK-NEXT:    br i1 [[CMP107_NOT_NOT]], label %[[FOR_BODY109]], label %[[FOR_COND121_PREHEADER]], !llvm.loop [[LOOP17:![0-9]+]]
; CHECK:       [[FOR_COND_CLEANUP123:.*]]:
; CHECK-NEXT:    [[M_VERTICES154:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 24
; CHECK-NEXT:    [[I25:%.*]] = zext nneg i32 [[DOTUS_PHI]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY_I:.*]]
; CHECK:       [[FOR_COND_CLEANUP_I:.*]]:
; CHECK-NEXT:    [[ADD12_I_LCSSA:%.*]] = phi float [ [[ADD12_I:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[ADD_I28_I_LCSSA:%.*]] = phi float [ [[ADD_I28_I:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[ADD4_I_I_LCSSA:%.*]] = phi float [ [[ADD4_I_I:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[CMP19_I:%.*]] = fcmp fast ogt float [[ADD12_I_LCSSA]], 0x3E80000000000000
; CHECK-NEXT:    br i1 [[CMP19_I]], label %[[_ZL15COMPUTECENTROIDPK6B2VEC2I_EXIT:.*]], label %[[COND_FALSE21_I:.*]]
; CHECK:       [[FOR_BODY_I]]:
; CHECK-NEXT:    [[INDVARS_IV_I:%.*]] = phi i64 [ 0, %[[FOR_COND_CLEANUP123]] ], [ [[INDVARS_IV_NEXT_I:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[AREA_047_I:%.*]] = phi float [ 0.000000e+00, %[[FOR_COND_CLEANUP123]] ], [ [[ADD12_I]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[RETVAL_SROA_6_045_I:%.*]] = phi float [ 0.000000e+00, %[[FOR_COND_CLEANUP123]] ], [ [[ADD4_I_I]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[RETVAL_SROA_0_044_I:%.*]] = phi float [ 0.000000e+00, %[[FOR_COND_CLEANUP123]] ], [ [[ADD_I28_I]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds [[STRUCT_B2VEC2]], ptr [[M_VERTICES154]], i64 [[INDVARS_IV_I]]
; CHECK-NEXT:    [[I26:%.*]] = load float, ptr [[ARRAYIDX_I]], align 4
; CHECK-NEXT:    [[ARRAYIDX_SROA_IDX_I:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_I]], i64 4
; CHECK-NEXT:    [[I27:%.*]] = load float, ptr [[ARRAYIDX_SROA_IDX_I]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I]] = add nuw nsw i64 [[INDVARS_IV_I]], 1
; CHECK-NEXT:    [[CMP2_I:%.*]] = icmp samesign ult i64 [[INDVARS_IV_NEXT_I]], [[I25]]
; CHECK-NEXT:    [[I28:%.*]] = and i64 [[INDVARS_IV_NEXT_I]], 4294967295
; CHECK-NEXT:    [[COND_IDX_I:%.*]] = select i1 [[CMP2_I]], i64 [[I28]], i64 0
; CHECK-NEXT:    [[COND_I63:%.*]] = getelementptr inbounds [[STRUCT_B2VEC2]], ptr [[M_VERTICES154]], i64 [[COND_IDX_I]]
; CHECK-NEXT:    [[I29:%.*]] = load float, ptr [[COND_I63]], align 4
; CHECK-NEXT:    [[COND_SROA_IDX_I:%.*]] = getelementptr inbounds i8, ptr [[COND_I63]], i64 4
; CHECK-NEXT:    [[I30:%.*]] = load float, ptr [[COND_SROA_IDX_I]], align 4
; CHECK-NEXT:    [[MUL_I_I64:%.*]] = fmul fast float [[I30]], [[I26]]
; CHECK-NEXT:    [[MUL3_I_I65:%.*]] = fmul fast float [[I29]], [[I27]]
; CHECK-NEXT:    [[SUB_I19_I:%.*]] = fsub fast float [[MUL_I_I64]], [[MUL3_I_I65]]
; CHECK-NEXT:    [[MUL_I66:%.*]] = fmul fast float [[SUB_I19_I]], 5.000000e-01
; CHECK-NEXT:    [[ADD12_I]] = fadd fast float [[MUL_I66]], [[AREA_047_I]]
; CHECK-NEXT:    [[MUL13_I:%.*]] = fmul fast float [[SUB_I19_I]], 0x3FC5555560000000
; CHECK-NEXT:    [[ADD_I22_I:%.*]] = fadd fast float [[I29]], [[I26]]
; CHECK-NEXT:    [[ADD3_I25_I:%.*]] = fadd fast float [[I30]], [[I27]]
; CHECK-NEXT:    [[MUL_I26_I:%.*]] = fmul fast float [[MUL13_I]], [[ADD_I22_I]]
; CHECK-NEXT:    [[MUL1_I_I:%.*]] = fmul fast float [[MUL13_I]], [[ADD3_I25_I]]
; CHECK-NEXT:    [[ADD_I28_I]] = fadd fast float [[MUL_I26_I]], [[RETVAL_SROA_0_044_I]]
; CHECK-NEXT:    [[ADD4_I_I]] = fadd fast float [[MUL1_I_I]], [[RETVAL_SROA_6_045_I]]
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT_I]], [[I25]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label %[[FOR_COND_CLEANUP_I]], label %[[FOR_BODY_I]], !llvm.loop [[LOOP18:![0-9]+]]
; CHECK:       [[COND_FALSE21_I]]:
; CHECK-NEXT:    tail call void @__assert_fail(ptr noundef nonnull @.str.7, ptr noundef nonnull @.str.1, i32 noundef signext 115, ptr noundef nonnull @__PRETTY_FUNCTION__._ZL15ComputeCentroidPK6b2Vec2i)
; CHECK-NEXT:    unreachable
; CHECK:       [[_ZL15COMPUTECENTROIDPK6B2VEC2I_EXIT]]:
; CHECK-NEXT:    [[DIV_I:%.*]] = fdiv fast float 1.000000e+00, [[ADD12_I_LCSSA]]
; CHECK-NEXT:    [[MUL_I30_I:%.*]] = fmul fast float [[DIV_I]], [[ADD_I28_I_LCSSA]]
; CHECK-NEXT:    [[MUL2_I_I:%.*]] = fmul fast float [[DIV_I]], [[ADD4_I_I_LCSSA]]
; CHECK-NEXT:    [[M_CENTROID:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 16
; CHECK-NEXT:    store float [[MUL_I30_I]], ptr [[M_CENTROID]], align 8, !tbaa [[TBAA19:![0-9]+]]
; CHECK-NEXT:    [[REF_TMP153_SROA_4_0_M_CENTROID_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[THIS]], i64 20
; CHECK-NEXT:    store float [[MUL2_I_I]], ptr [[REF_TMP153_SROA_4_0_M_CENTROID_SROA_IDX]], align 4, !tbaa [[TBAA19]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[HULL]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 64, ptr nonnull [[PS]])
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY124]]:
; CHECK-NEXT:    [[I120_0118:%.*]] = phi i32 [ 0, %[[FOR_COND121_PREHEADER]] ], [ [[ADD:%.*]], %[[_ZN6B2VEC29NORMALIZEEV_EXIT:.*]] ]
; CHECK-NEXT:    [[ADD]] = add nuw nsw i32 [[I120_0118]], 1
; CHECK-NEXT:    [[CMP125:%.*]] = icmp samesign ult i32 [[I120_0118]], [[DOTUS_PHI102]]
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[CMP125]], i32 [[ADD]], i32 0
; CHECK-NEXT:    [[IDXPROM131:%.*]] = zext nneg i32 [[COND]] to i64
; CHECK-NEXT:    [[ARRAYIDX132:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[M_VERTICES130]], i64 0, i64 [[IDXPROM131]]
; CHECK-NEXT:    [[IDXPROM134:%.*]] = zext nneg i32 [[I120_0118]] to i64
; CHECK-NEXT:    [[ARRAYIDX135:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[M_VERTICES130]], i64 0, i64 [[IDXPROM134]]
; CHECK-NEXT:    [[I31:%.*]] = load float, ptr [[ARRAYIDX132]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[I32:%.*]] = load float, ptr [[ARRAYIDX135]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[SUB_I67:%.*]] = fsub fast float [[I31]], [[I32]]
; CHECK-NEXT:    [[Y_I68:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX132]], i64 4
; CHECK-NEXT:    [[I33:%.*]] = load float, ptr [[Y_I68]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[Y2_I69:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX135]], i64 4
; CHECK-NEXT:    [[I34:%.*]] = load float, ptr [[Y2_I69]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[SUB3_I70:%.*]] = fsub fast float [[I33]], [[I34]]
; CHECK-NEXT:    [[MUL_I71:%.*]] = fmul fast float [[SUB_I67]], [[SUB_I67]]
; CHECK-NEXT:    [[MUL4_I73:%.*]] = fmul fast float [[SUB3_I70]], [[SUB3_I70]]
; CHECK-NEXT:    [[ADD_I74:%.*]] = fadd fast float [[MUL4_I73]], [[MUL_I71]]
; CHECK-NEXT:    [[CMP138:%.*]] = fcmp fast ogt float [[ADD_I74]], 0x3D10000000000000
; CHECK-NEXT:    br i1 [[CMP138]], label %[[COND_END141:.*]], label %[[COND_FALSE140:.*]]
; CHECK:       [[COND_FALSE140]]:
; CHECK-NEXT:    tail call void @__assert_fail(ptr noundef nonnull @.str.4, ptr noundef nonnull @.str.1, i32 noundef signext 243, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
; CHECK-NEXT:    unreachable
; CHECK:       [[COND_END141]]:
; CHECK-NEXT:    [[MUL1_I:%.*]] = fneg fast float [[SUB_I67]]
; CHECK-NEXT:    [[ARRAYIDX144:%.*]] = getelementptr inbounds [8 x %struct.b2Vec2], ptr [[M_NORMALS]], i64 0, i64 [[IDXPROM134]]
; CHECK-NEXT:    store float [[SUB3_I70]], ptr [[ARRAYIDX144]], align 8, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[REF_TMP_SROA_4_0_ARRAYIDX144_SROA_IDX:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX144]], i64 4
; CHECK-NEXT:    store float [[MUL1_I]], ptr [[REF_TMP_SROA_4_0_ARRAYIDX144_SROA_IDX]], align 4, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[MUL4_I_I:%.*]] = fmul fast float [[SUB_I67]], [[SUB_I67]]
; CHECK-NEXT:    [[ADD_I_I79:%.*]] = fadd fast float [[MUL4_I73]], [[MUL4_I_I]]
; CHECK-NEXT:    [[I35:%.*]] = tail call fast noundef float @llvm.sqrt.f32(float [[ADD_I_I79]])
; CHECK-NEXT:    [[CMP_I:%.*]] = fcmp fast olt float [[I35]], 0x3E80000000000000
; CHECK-NEXT:    br i1 [[CMP_I]], label %[[_ZN6B2VEC29NORMALIZEEV_EXIT]], label %[[IF_END_I:.*]]
; CHECK:       [[IF_END_I]]:
; CHECK-NEXT:    [[DIV_I80:%.*]] = fdiv fast float 1.000000e+00, [[I35]]
; CHECK-NEXT:    [[MUL_I81:%.*]] = fmul fast float [[DIV_I80]], [[SUB3_I70]]
; CHECK-NEXT:    store float [[MUL_I81]], ptr [[ARRAYIDX144]], align 4, !tbaa [[TBAA2]]
; CHECK-NEXT:    [[MUL2_I:%.*]] = fmul fast float [[DIV_I80]], [[MUL1_I]]
; CHECK-NEXT:    store float [[MUL2_I]], ptr [[REF_TMP_SROA_4_0_ARRAYIDX144_SROA_IDX]], align 4, !tbaa [[TBAA7]]
; CHECK-NEXT:    br label %[[_ZN6B2VEC29NORMALIZEEV_EXIT]]
; CHECK:       [[_ZN6B2VEC29NORMALIZEEV_EXIT]]:
; CHECK-NEXT:    [[CMP122_NOT_NOT:%.*]] = icmp ult i32 [[I120_0118]], [[DOTUS_PHI102]]
; CHECK-NEXT:    br i1 [[CMP122_NOT_NOT]], label %[[FOR_BODY124]], label %[[FOR_COND_CLEANUP123]], !llvm.loop [[LOOP20:![0-9]+]]
;
entry:
  %ps = alloca [8 x %struct.b2Vec2], align 8
  %hull = alloca [8 x i32], align 8
  %i = add i32 %count, -3
  %i1 = icmp ult i32 %i, 6
  br i1 %i1, label %if.end, label %cond.false

cond.false:                                       ; preds = %entry
  tail call void @__assert_fail(ptr noundef nonnull @.str, ptr noundef nonnull @.str.1, i32 noundef signext 122, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
  unreachable

if.end:                                           ; preds = %entry
  call void @llvm.lifetime.start.p0(i64 64, ptr nonnull %ps)
  br label %for.cond.preheader

for.cond.preheader:                               ; preds = %if.end
  %cmp492 = icmp sgt i32 %count, 0
  br i1 %cmp492, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %for.cond.preheader
  %wide.trip.count125 = zext i32 %count to i64
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %if.end19
  %tempCount.1.lcssa = phi i32 [ %tempCount.1, %if.end19 ]
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %for.cond.preheader
  %tempCount.0.lcssa = phi i32 [ 0, %for.cond.preheader ], [ %tempCount.1.lcssa, %for.cond.cleanup.loopexit ]
  %cmp24 = icmp slt i32 %tempCount.0.lcssa, 3
  br i1 %cmp24, label %if.then25, label %if.end26

for.body:                                         ; preds = %if.end19, %for.body.preheader
  %indvars.iv122 = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next123, %if.end19 ]
  %tempCount.094 = phi i32 [ %tempCount.1, %if.end19 ], [ 0, %for.body.preheader ]
  %arrayidx = getelementptr inbounds %struct.b2Vec2, ptr %vertices, i64 %indvars.iv122
  %i2 = load i32, ptr %arrayidx, align 4
  %arrayidx.sroa_idx = getelementptr inbounds i8, ptr %arrayidx, i64 4
  %i3 = load i32, ptr %arrayidx.sroa_idx, align 4
  %i4 = bitcast i32 %i2 to float
  %i5 = bitcast i32 %i3 to float
  %cmp690 = icmp sgt i32 %tempCount.094, 0
  br i1 %cmp690, label %for.body8.preheader, label %if.then15.critedge

for.body8.preheader:                              ; preds = %for.body
  %wide.trip.count = zext i32 %tempCount.094 to i64
  br label %for.body8

for.cond5:                                        ; preds = %for.body8
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp ne i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond, label %for.body8, label %if.then15.critedge.loopexit, !llvm.loop !0

for.body8:                                        ; preds = %for.cond5, %for.body8.preheader
  %indvars.iv = phi i64 [ 0, %for.body8.preheader ], [ %indvars.iv.next, %for.cond5 ]
  %arrayidx10 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %indvars.iv
  %i6 = load float, ptr %arrayidx10, align 4, !tbaa !2
  %sub.i.i = fsub fast float %i4, %i6
  %y2.i.i = getelementptr inbounds nuw i8, ptr %arrayidx10, i64 4
  %i7 = load float, ptr %y2.i.i, align 4, !tbaa !7
  %sub3.i.i = fsub fast float %i5, %i7
  %mul.i.i = fmul fast float %sub.i.i, %sub.i.i
  %mul3.i.i = fmul fast float %sub3.i.i, %sub3.i.i
  %add.i.i = fadd fast float %mul3.i.i, %mul.i.i
  %cmp12 = fcmp fast olt float %add.i.i, 0x3EDA36E2E0000000
  br i1 %cmp12, label %if.end19.loopexit, label %for.cond5

if.then15.critedge.loopexit:                      ; preds = %for.cond5
  br label %if.then15.critedge

if.then15.critedge:                               ; preds = %if.then15.critedge.loopexit, %for.body
  %inc16 = add nsw i32 %tempCount.094, 1
  %idxprom17 = sext i32 %tempCount.094 to i64
  %arrayidx18 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %idxprom17
  store i32 %i2, ptr %arrayidx18, align 8
  %arrayidx18.sroa_idx = getelementptr inbounds i8, ptr %arrayidx18, i64 4
  store i32 %i3, ptr %arrayidx18.sroa_idx, align 4
  br label %if.end19

if.end19.loopexit:                                ; preds = %for.body8
  br label %if.end19

if.end19:                                         ; preds = %if.end19.loopexit, %if.then15.critedge
  %tempCount.1 = phi i32 [ %inc16, %if.then15.critedge ], [ %tempCount.094, %if.end19.loopexit ]
  %indvars.iv.next123 = add nuw nsw i64 %indvars.iv122, 1
  %exitcond126 = icmp ne i64 %indvars.iv.next123, %wide.trip.count125
  br i1 %exitcond126, label %for.body, label %for.cond.cleanup.loopexit, !llvm.loop !8

if.then25:                                        ; preds = %for.cond.cleanup
  tail call void @__assert_fail(ptr noundef nonnull @.str.2, ptr noundef nonnull @.str.1, i32 noundef signext 158, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
  unreachable

if.end26:                                         ; preds = %for.cond.cleanup
  %i8 = load float, ptr %ps, align 8, !tbaa !2
  %wide.trip.count130 = zext i32 %tempCount.0.lcssa to i64
  br label %for.body32

for.cond.cleanup31:                               ; preds = %if.end46
  %i0.1.lcssa = phi i32 [ %i0.1, %if.end46 ]
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %hull)
  br i1 true, label %for.cond51.us.preheader, label %for.cond.cleanup31.split

for.cond51.us.preheader:                          ; preds = %for.cond.cleanup31
  br label %for.cond51.us

for.cond51.us:                                    ; preds = %for.cond59.for.cond.cleanup61_crit_edge.us, %for.cond51.us.preheader
  %indvars.iv137 = phi i64 [ 0, %for.cond51.us.preheader ], [ %indvars.iv.next138, %for.cond59.for.cond.cleanup61_crit_edge.us ]
  %ih.0.us = phi i32 [ %ie.3.us.lcssa, %for.cond59.for.cond.cleanup61_crit_edge.us ], [ %i0.1.lcssa, %for.cond51.us.preheader ]
  %exitcond140 = icmp ne i64 %indvars.iv137, 8
  br i1 %exitcond140, label %cond.end55.us, label %cond.false54.loopexit

cond.end55.us:                                    ; preds = %for.cond51.us
  %arrayidx57.us = getelementptr inbounds [8 x i32], ptr %hull, i64 0, i64 %indvars.iv137
  store i32 %ih.0.us, ptr %arrayidx57.us, align 4, !tbaa !9
  %idxprom70.us = sext i32 %ih.0.us to i64
  %arrayidx71.us = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %idxprom70.us
  %y2.i.us = getelementptr inbounds nuw i8, ptr %arrayidx71.us, i64 4
  %wide.trip.count135 = zext i32 %tempCount.0.lcssa to i64
  br label %for.body62.us

for.body62.us:                                    ; preds = %for.inc92.us, %cond.end55.us
  %indvars.iv132 = phi i64 [ 1, %cond.end55.us ], [ %indvars.iv.next133, %for.inc92.us ]
  %ie.099.us = phi i32 [ 0, %cond.end55.us ], [ %ie.3.us, %for.inc92.us ]
  %cmp63.us = icmp eq i32 %ie.099.us, %ih.0.us
  %i9 = trunc nuw nsw i64 %indvars.iv132 to i32
  br i1 %cmp63.us, label %for.inc92.us, label %if.end65.us

if.end65.us:                                      ; preds = %for.body62.us
  %idxprom66.us = sext i32 %ie.099.us to i64
  %arrayidx67.us = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %idxprom66.us
  %i10 = load float, ptr %arrayidx67.us, align 4, !tbaa !2
  %i11 = load float, ptr %arrayidx71.us, align 4, !tbaa !2
  %sub.i.us = fsub fast float %i10, %i11
  %y.i.us = getelementptr inbounds nuw i8, ptr %arrayidx67.us, i64 4
  %i12 = load float, ptr %y.i.us, align 4, !tbaa !7
  %i13 = load float, ptr %y2.i.us, align 4, !tbaa !7
  %sub3.i.us = fsub fast float %i12, %i13
  %arrayidx75.us = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %indvars.iv132
  %i14 = load float, ptr %arrayidx75.us, align 4, !tbaa !2
  %sub.i51.us = fsub fast float %i14, %i11
  %y.i52.us = getelementptr inbounds nuw i8, ptr %arrayidx75.us, i64 4
  %i15 = load float, ptr %y.i52.us, align 4, !tbaa !7
  %sub3.i54.us = fsub fast float %i15, %i13
  %mul.i.us = fmul fast float %sub3.i54.us, %sub.i.us
  %mul3.i.us = fmul fast float %sub.i51.us, %sub3.i.us
  %sub.i56.us = fsub fast float %mul.i.us, %mul3.i.us
  %cmp82.us = fcmp fast olt float %sub.i56.us, 0.000000e+00
  %i16 = trunc nuw nsw i64 %indvars.iv132 to i32
  %ie.1.us = select i1 %cmp82.us, i32 %i16, i32 %ie.099.us
  %cmp85.us = fcmp fast oeq float %sub.i56.us, 0.000000e+00
  br i1 %cmp85.us, label %land.lhs.true86.us, label %for.inc92.us

land.lhs.true86.us:                               ; preds = %if.end65.us
  %mul.i57.us = fmul fast float %sub.i51.us, %sub.i51.us
  %mul4.i.us = fmul fast float %sub3.i54.us, %sub3.i54.us
  %add.i.us = fadd fast float %mul4.i.us, %mul.i57.us
  %mul.i59.us = fmul fast float %sub.i.us, %sub.i.us
  %mul4.i61.us = fmul fast float %sub3.i.us, %sub3.i.us
  %add.i62.us = fadd fast float %mul4.i61.us, %mul.i59.us
  %cmp89.us = fcmp fast ogt float %add.i.us, %add.i62.us
  br i1 %cmp89.us, label %if.then90.us, label %for.inc92.us

if.then90.us:                                     ; preds = %land.lhs.true86.us
  br label %for.inc92.us

for.inc92.us:                                     ; preds = %if.then90.us, %land.lhs.true86.us, %if.end65.us, %for.body62.us
  %ie.3.us = phi i32 [ %i9, %for.body62.us ], [ %i9, %if.then90.us ], [ %ie.1.us, %land.lhs.true86.us ], [ %ie.1.us, %if.end65.us ]
  %indvars.iv.next133 = add nuw nsw i64 %indvars.iv132, 1
  %exitcond136 = icmp ne i64 %indvars.iv.next133, %wide.trip.count135
  br i1 %exitcond136, label %for.body62.us, label %for.cond59.for.cond.cleanup61_crit_edge.us, !llvm.loop !11

for.cond59.for.cond.cleanup61_crit_edge.us:       ; preds = %for.inc92.us
  %ie.3.us.lcssa = phi i32 [ %ie.3.us, %for.inc92.us ]
  %indvars.iv.next138 = add nuw nsw i64 %indvars.iv137, 1
  %cmp97.us = icmp eq i32 %ie.3.us.lcssa, %i0.1.lcssa
  br i1 %cmp97.us, label %for.end101.loopexit, label %for.cond51.us

for.cond.cleanup31.split:                         ; preds = %for.cond.cleanup31
  br i1 poison, label %for.cond51.us103, label %cond.end55.preheader

cond.end55.preheader:                             ; preds = %for.cond.cleanup31.split
  br label %cond.false54.loopexit119

for.cond51.us103:                                 ; preds = %for.cond.cleanup31.split
  br i1 true, label %cond.end55.us107, label %cond.false54

cond.end55.us107:                                 ; preds = %for.cond51.us103
  br label %for.end101

for.body32:                                       ; preds = %if.end46, %if.end26
  %indvars.iv127 = phi i64 [ 1, %if.end26 ], [ %indvars.iv.next128, %if.end46 ]
  %i0.097 = phi i32 [ 0, %if.end26 ], [ %i0.1, %if.end46 ]
  %x0.096 = phi float [ %i8, %if.end26 ], [ %x0.1, %if.end46 ]
  %arrayidx35 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %indvars.iv127
  %i17 = load float, ptr %arrayidx35, align 8, !tbaa !2
  %cmp37 = fcmp fast ogt float %i17, %x0.096
  br i1 %cmp37, label %if.then45, label %lor.lhs.false

lor.lhs.false:                                    ; preds = %for.body32
  %cmp38 = fcmp fast oeq float %i17, %x0.096
  br i1 %cmp38, label %land.lhs.true, label %if.end46

land.lhs.true:                                    ; preds = %lor.lhs.false
  %y = getelementptr inbounds nuw i8, ptr %arrayidx35, i64 4
  %i18 = load float, ptr %y, align 4, !tbaa !7
  %idxprom41 = sext i32 %i0.097 to i64
  %y43 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %idxprom41, i32 1
  %i19 = load float, ptr %y43, align 4, !tbaa !7
  %cmp44 = fcmp fast olt float %i18, %i19
  br i1 %cmp44, label %if.then45, label %if.end46

if.then45:                                        ; preds = %land.lhs.true, %for.body32
  %i20 = trunc nuw nsw i64 %indvars.iv127 to i32
  br label %if.end46

if.end46:                                         ; preds = %if.then45, %land.lhs.true, %lor.lhs.false
  %x0.1 = phi nsz float [ %i17, %if.then45 ], [ %x0.096, %land.lhs.true ], [ %x0.096, %lor.lhs.false ]
  %i0.1 = phi i32 [ %i20, %if.then45 ], [ %i0.097, %land.lhs.true ], [ %i0.097, %lor.lhs.false ]
  %indvars.iv.next128 = add nuw nsw i64 %indvars.iv127, 1
  %exitcond131 = icmp ne i64 %indvars.iv.next128, %wide.trip.count130
  br i1 %exitcond131, label %for.body32, label %for.cond.cleanup31, !llvm.loop !12

cond.false54.loopexit:                            ; preds = %for.cond51.us
  br label %cond.false54

cond.false54.loopexit119:                         ; preds = %cond.end55.preheader
  br label %cond.false54

cond.false54:                                     ; preds = %cond.false54.loopexit119, %cond.false54.loopexit, %for.cond51.us103
  tail call void @__assert_fail(ptr noundef nonnull @.str.3, ptr noundef nonnull @.str.1, i32 noundef signext 185, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
  unreachable

for.end101.loopexit:                              ; preds = %for.cond59.for.cond.cleanup61_crit_edge.us
  %inc96.us.lcssa.wide = phi i64 [ %indvars.iv.next138, %for.cond59.for.cond.cleanup61_crit_edge.us ]
  %m.0.us.lcssa120.wide = phi i64 [ %indvars.iv137, %for.cond59.for.cond.cleanup61_crit_edge.us ]
  %i21 = trunc nuw nsw i64 %m.0.us.lcssa120.wide to i32
  %i22 = trunc nuw nsw i64 %inc96.us.lcssa.wide to i32
  br label %for.end101

for.end101:                                       ; preds = %for.end101.loopexit, %cond.end55.us107
  %.us-phi = phi i32 [ poison, %cond.end55.us107 ], [ %i22, %for.end101.loopexit ]
  %.us-phi102 = phi i32 [ poison, %cond.end55.us107 ], [ %i21, %for.end101.loopexit ]
  %cmp102 = icmp samesign ult i32 %.us-phi102, 2
  br i1 %cmp102, label %if.then103, label %if.end104

if.then103:                                       ; preds = %for.end101
  tail call void @__assert_fail(ptr noundef nonnull @.str.2, ptr noundef nonnull @.str.1, i32 noundef signext 224, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
  unreachable

if.end104:                                        ; preds = %for.end101
  %m_count = getelementptr inbounds nuw i8, ptr %this, i64 152
  store i32 %.us-phi, ptr %m_count, align 8, !tbaa !13
  %m_vertices = getelementptr inbounds nuw i8, ptr %this, i64 24
  br label %for.body109

for.cond121.preheader:                            ; preds = %for.body109
  %m_vertices130 = getelementptr inbounds nuw i8, ptr %this, i64 24
  %m_normals = getelementptr inbounds nuw i8, ptr %this, i64 88
  br label %for.body124

for.body109:                                      ; preds = %for.body109, %if.end104
  %i105.0117 = phi i32 [ 0, %if.end104 ], [ %inc117, %for.body109 ]
  %idxprom110 = zext nneg i32 %i105.0117 to i64
  %arrayidx111 = getelementptr inbounds [8 x i32], ptr %hull, i64 0, i64 %idxprom110
  %i23 = load i32, ptr %arrayidx111, align 4, !tbaa !9
  %idxprom112 = sext i32 %i23 to i64
  %arrayidx113 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %ps, i64 0, i64 %idxprom112
  %arrayidx115 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %m_vertices, i64 0, i64 %idxprom110
  %i24 = load i64, ptr %arrayidx113, align 8
  store i64 %i24, ptr %arrayidx115, align 8
  %inc117 = add nuw nsw i32 %i105.0117, 1
  %cmp107.not.not = icmp ult i32 %i105.0117, %.us-phi102
  br i1 %cmp107.not.not, label %for.body109, label %for.cond121.preheader, !llvm.loop !17

for.cond.cleanup123:                              ; preds = %_ZN6b2Vec29NormalizeEv.exit
  %m_vertices154 = getelementptr inbounds nuw i8, ptr %this, i64 24
  %i25 = zext nneg i32 %.us-phi to i64
  br label %for.body.i

for.cond.cleanup.i:                               ; preds = %for.body.i
  %add12.i.lcssa = phi float [ %add12.i, %for.body.i ]
  %add.i28.i.lcssa = phi float [ %add.i28.i, %for.body.i ]
  %add4.i.i.lcssa = phi float [ %add4.i.i, %for.body.i ]
  %cmp19.i = fcmp fast ogt float %add12.i.lcssa, 0x3E80000000000000
  br i1 %cmp19.i, label %_ZL15ComputeCentroidPK6b2Vec2i.exit, label %cond.false21.i

for.body.i:                                       ; preds = %for.body.i, %for.cond.cleanup123
  %indvars.iv.i = phi i64 [ 0, %for.cond.cleanup123 ], [ %indvars.iv.next.i, %for.body.i ]
  %area.047.i = phi float [ 0.000000e+00, %for.cond.cleanup123 ], [ %add12.i, %for.body.i ]
  %retval.sroa.6.045.i = phi float [ 0.000000e+00, %for.cond.cleanup123 ], [ %add4.i.i, %for.body.i ]
  %retval.sroa.0.044.i = phi float [ 0.000000e+00, %for.cond.cleanup123 ], [ %add.i28.i, %for.body.i ]
  %arrayidx.i = getelementptr inbounds %struct.b2Vec2, ptr %m_vertices154, i64 %indvars.iv.i
  %i26 = load float, ptr %arrayidx.i, align 4
  %arrayidx.sroa_idx.i = getelementptr inbounds i8, ptr %arrayidx.i, i64 4
  %i27 = load float, ptr %arrayidx.sroa_idx.i, align 4
  %indvars.iv.next.i = add nuw nsw i64 %indvars.iv.i, 1
  %cmp2.i = icmp samesign ult i64 %indvars.iv.next.i, %i25
  %i28 = and i64 %indvars.iv.next.i, 4294967295
  %cond.idx.i = select i1 %cmp2.i, i64 %i28, i64 0
  %cond.i63 = getelementptr inbounds %struct.b2Vec2, ptr %m_vertices154, i64 %cond.idx.i
  %i29 = load float, ptr %cond.i63, align 4
  %cond.sroa_idx.i = getelementptr inbounds i8, ptr %cond.i63, i64 4
  %i30 = load float, ptr %cond.sroa_idx.i, align 4
  %mul.i.i64 = fmul fast float %i30, %i26
  %mul3.i.i65 = fmul fast float %i29, %i27
  %sub.i19.i = fsub fast float %mul.i.i64, %mul3.i.i65
  %mul.i66 = fmul fast float %sub.i19.i, 5.000000e-01
  %add12.i = fadd fast float %mul.i66, %area.047.i
  %mul13.i = fmul fast float %sub.i19.i, 0x3FC5555560000000
  %add.i22.i = fadd fast float %i29, %i26
  %add3.i25.i = fadd fast float %i30, %i27
  %mul.i26.i = fmul fast float %mul13.i, %add.i22.i
  %mul1.i.i = fmul fast float %mul13.i, %add3.i25.i
  %add.i28.i = fadd fast float %mul.i26.i, %retval.sroa.0.044.i
  %add4.i.i = fadd fast float %mul1.i.i, %retval.sroa.6.045.i
  %exitcond.not.i = icmp eq i64 %indvars.iv.next.i, %i25
  br i1 %exitcond.not.i, label %for.cond.cleanup.i, label %for.body.i, !llvm.loop !18

cond.false21.i:                                   ; preds = %for.cond.cleanup.i
  tail call void @__assert_fail(ptr noundef nonnull @.str.7, ptr noundef nonnull @.str.1, i32 noundef signext 115, ptr noundef nonnull @__PRETTY_FUNCTION__._ZL15ComputeCentroidPK6b2Vec2i)
  unreachable

_ZL15ComputeCentroidPK6b2Vec2i.exit:              ; preds = %for.cond.cleanup.i
  %div.i = fdiv fast float 1.000000e+00, %add12.i.lcssa
  %mul.i30.i = fmul fast float %div.i, %add.i28.i.lcssa
  %mul2.i.i = fmul fast float %div.i, %add4.i.i.lcssa
  %m_centroid = getelementptr inbounds nuw i8, ptr %this, i64 16
  store float %mul.i30.i, ptr %m_centroid, align 8, !tbaa !19
  %ref.tmp153.sroa.4.0.m_centroid.sroa_idx = getelementptr inbounds i8, ptr %this, i64 20
  store float %mul2.i.i, ptr %ref.tmp153.sroa.4.0.m_centroid.sroa_idx, align 4, !tbaa !19
  call void @llvm.lifetime.end.p0(i64 32, ptr nonnull %hull)
  call void @llvm.lifetime.end.p0(i64 64, ptr nonnull %ps)
  ret void

for.body124:                                      ; preds = %_ZN6b2Vec29NormalizeEv.exit, %for.cond121.preheader
  %i120.0118 = phi i32 [ 0, %for.cond121.preheader ], [ %add, %_ZN6b2Vec29NormalizeEv.exit ]
  %add = add nuw nsw i32 %i120.0118, 1
  %cmp125 = icmp samesign ult i32 %i120.0118, %.us-phi102
  %cond = select i1 %cmp125, i32 %add, i32 0
  %idxprom131 = zext nneg i32 %cond to i64
  %arrayidx132 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %m_vertices130, i64 0, i64 %idxprom131
  %idxprom134 = zext nneg i32 %i120.0118 to i64
  %arrayidx135 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %m_vertices130, i64 0, i64 %idxprom134
  %i31 = load float, ptr %arrayidx132, align 4, !tbaa !2
  %i32 = load float, ptr %arrayidx135, align 4, !tbaa !2
  %sub.i67 = fsub fast float %i31, %i32
  %y.i68 = getelementptr inbounds nuw i8, ptr %arrayidx132, i64 4
  %i33 = load float, ptr %y.i68, align 4, !tbaa !7
  %y2.i69 = getelementptr inbounds nuw i8, ptr %arrayidx135, i64 4
  %i34 = load float, ptr %y2.i69, align 4, !tbaa !7
  %sub3.i70 = fsub fast float %i33, %i34
  %mul.i71 = fmul fast float %sub.i67, %sub.i67
  %mul4.i73 = fmul fast float %sub3.i70, %sub3.i70
  %add.i74 = fadd fast float %mul4.i73, %mul.i71
  %cmp138 = fcmp fast ogt float %add.i74, 0x3D10000000000000
  br i1 %cmp138, label %cond.end141, label %cond.false140

cond.false140:                                    ; preds = %for.body124
  tail call void @__assert_fail(ptr noundef nonnull @.str.4, ptr noundef nonnull @.str.1, i32 noundef signext 243, ptr noundef nonnull @__PRETTY_FUNCTION__._ZN14b2PolygonShape3SetEPK6b2Vec2i)
  unreachable

cond.end141:                                      ; preds = %for.body124
  %mul1.i = fneg fast float %sub.i67
  %arrayidx144 = getelementptr inbounds [8 x %struct.b2Vec2], ptr %m_normals, i64 0, i64 %idxprom134
  store float %sub3.i70, ptr %arrayidx144, align 8, !tbaa !19
  %ref.tmp.sroa.4.0.arrayidx144.sroa_idx = getelementptr inbounds i8, ptr %arrayidx144, i64 4
  store float %mul1.i, ptr %ref.tmp.sroa.4.0.arrayidx144.sroa_idx, align 4, !tbaa !19
  %mul4.i.i = fmul fast float %sub.i67, %sub.i67
  %add.i.i79 = fadd fast float %mul4.i73, %mul4.i.i
  %i35 = tail call fast noundef float @llvm.sqrt.f32(float %add.i.i79)
  %cmp.i = fcmp fast olt float %i35, 0x3E80000000000000
  br i1 %cmp.i, label %_ZN6b2Vec29NormalizeEv.exit, label %if.end.i

if.end.i:                                         ; preds = %cond.end141
  %div.i80 = fdiv fast float 1.000000e+00, %i35
  %mul.i81 = fmul fast float %div.i80, %sub3.i70
  store float %mul.i81, ptr %arrayidx144, align 4, !tbaa !2
  %mul2.i = fmul fast float %div.i80, %mul1.i
  store float %mul2.i, ptr %ref.tmp.sroa.4.0.arrayidx144.sroa_idx, align 4, !tbaa !7
  br label %_ZN6b2Vec29NormalizeEv.exit

_ZN6b2Vec29NormalizeEv.exit:                      ; preds = %if.end.i, %cond.end141
  %cmp122.not.not = icmp ult i32 %i120.0118, %.us-phi102
  br i1 %cmp122.not.not, label %for.body124, label %for.cond.cleanup123, !llvm.loop !20
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.sqrt.f32(float)

declare void @__assert_fail(ptr noundef, ptr noundef, i32 noundef signext, ptr noundef) local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!3, !4, i64 0}
!3 = !{!"_ZTS6b2Vec2", !4, i64 0, !4, i64 4}
!4 = !{!"float", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}
!7 = !{!3, !4, i64 4}
!8 = distinct !{!8, !1}
!9 = !{!10, !10, i64 0}
!10 = !{!"int", !5, i64 0}
!11 = distinct !{!11, !1}
!12 = distinct !{!12, !1}
!13 = !{!14, !10, i64 152}
!14 = !{!"_ZTS14b2PolygonShape", !15, i64 0, !3, i64 16, !5, i64 24, !5, i64 88, !10, i64 152}
!15 = !{!"_ZTS7b2Shape", !16, i64 8, !4, i64 12}
!16 = !{!"_ZTSN7b2Shape4TypeE", !5, i64 0}
!17 = distinct !{!17, !1}
!18 = distinct !{!18, !1}
!19 = !{!4, !4, i64 0}
!20 = distinct !{!20, !1}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[TBAA2]] = !{[[META3:![0-9]+]], [[META4:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"_ZTS6b2Vec2", [[META4]], i64 0, [[META4]], i64 4}
; CHECK: [[META4]] = !{!"float", [[META5:![0-9]+]], i64 0}
; CHECK: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
; CHECK: [[META6]] = !{!"Simple C++ TBAA"}
; CHECK: [[TBAA7]] = !{[[META3]], [[META4]], i64 4}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META1]]}
; CHECK: [[TBAA9]] = !{[[META10:![0-9]+]], [[META10]], i64 0}
; CHECK: [[META10]] = !{!"int", [[META5]], i64 0}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META1]]}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META1]]}
; CHECK: [[TBAA13]] = !{[[META14:![0-9]+]], [[META10]], i64 152}
; CHECK: [[META14]] = !{!"_ZTS14b2PolygonShape", [[META15:![0-9]+]], i64 0, [[META3]], i64 16, [[META5]], i64 24, [[META5]], i64 88, [[META10]], i64 152}
; CHECK: [[META15]] = !{!"_ZTS7b2Shape", [[META16:![0-9]+]], i64 8, [[META4]], i64 12}
; CHECK: [[META16]] = !{!"_ZTSN7b2Shape4TypeE", [[META5]], i64 0}
; CHECK: [[LOOP17]] = distinct !{[[LOOP17]], [[META1]]}
; CHECK: [[LOOP18]] = distinct !{[[LOOP18]], [[META1]]}
; CHECK: [[TBAA19]] = !{[[META4]], [[META4]], i64 0}
; CHECK: [[LOOP20]] = distinct !{[[LOOP20]], [[META1]]}
;.
