; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -passes="default<O1>" -mtriple riscv64 | FileCheck %s -check-prefix=CHECK-GENERIC
; RUN: opt < %s -S -passes="default<O1>" -mtriple riscv64 -mcpu=sifive-x280 | FileCheck %s -check-prefix=CHECK-X280
; RUN: opt < %s -S -passes="default<O1>" -mtriple riscv64 -mcpu=sifive-p470 | FileCheck %s -check-prefix=CHECK-P470

; Testing that, while runtime unrolling is performed on in-order cores (such as the sifve-p470), it is not performed when -mcpu is not specified
define void @runtime_unroll_generic(i32 %arg_0, ptr %arg_1, ptr %arg_2, ptr %arg_3) {
; CHECK-GENERIC-LABEL: @runtime_unroll_generic(
; CHECK-GENERIC-NEXT:  entry:
; CHECK-GENERIC-NEXT:    [[CMP52_NOT:%.*]] = icmp eq i32 [[ARG_0:%.*]], 0
; CHECK-GENERIC-NEXT:    br i1 [[CMP52_NOT]], label [[FOR_END:%.*]], label [[FOR_BODY6_PREHEADER:%.*]]
; CHECK-GENERIC:       for.body6.preheader:
; CHECK-GENERIC-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[ARG_0]] to i64
; CHECK-GENERIC-NEXT:    br label [[FOR_BODY6:%.*]]
; CHECK-GENERIC:       for.body6:
; CHECK-GENERIC-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY6_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY6]] ]
; CHECK-GENERIC-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds i16, ptr [[ARG_2:%.*]], i64 [[INDVARS_IV]]
; CHECK-GENERIC-NEXT:    [[TMP0:%.*]] = load i16, ptr [[ARRAYIDX10]], align 2
; CHECK-GENERIC-NEXT:    [[CONV:%.*]] = sext i16 [[TMP0]] to i32
; CHECK-GENERIC-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i16, ptr [[ARG_3:%.*]], i64 [[INDVARS_IV]]
; CHECK-GENERIC-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX14]], align 2
; CHECK-GENERIC-NEXT:    [[CONV15:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-GENERIC-NEXT:    [[MUL16:%.*]] = mul nsw i32 [[CONV15]], [[CONV]]
; CHECK-GENERIC-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i32, ptr [[ARG_1:%.*]], i64 [[INDVARS_IV]]
; CHECK-GENERIC-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX20]], align 4
; CHECK-GENERIC-NEXT:    [[ADD21:%.*]] = add nsw i32 [[MUL16]], [[TMP2]]
; CHECK-GENERIC-NEXT:    store i32 [[ADD21]], ptr [[ARRAYIDX20]], align 4
; CHECK-GENERIC-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-GENERIC-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-GENERIC-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_END]], label [[FOR_BODY6]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-GENERIC:       for.end:
; CHECK-GENERIC-NEXT:    ret void
;
; CHECK-X280-LABEL: @runtime_unroll_generic(
; CHECK-X280-NEXT:  entry:
; CHECK-X280-NEXT:    [[CMP52_NOT:%.*]] = icmp eq i32 [[ARG_0:%.*]], 0
; CHECK-X280-NEXT:    br i1 [[CMP52_NOT]], label [[FOR_END:%.*]], label [[FOR_BODY6_PREHEADER:%.*]]
; CHECK-X280:       for.body6.preheader:
; CHECK-X280-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[ARG_0]] to i64
; CHECK-X280-NEXT:    [[XTRAITER:%.*]] = and i64 [[WIDE_TRIP_COUNT]], 7
; CHECK-X280-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[ARG_0]], 8
; CHECK-X280-NEXT:    br i1 [[TMP0]], label [[FOR_END_LOOPEXIT_UNR_LCSSA:%.*]], label [[FOR_BODY6_PREHEADER_NEW:%.*]]
; CHECK-X280:       for.body6.preheader.new:
; CHECK-X280-NEXT:    [[UNROLL_ITER:%.*]] = and i64 [[WIDE_TRIP_COUNT]], 4294967288
; CHECK-X280-NEXT:    br label [[FOR_BODY6:%.*]]
; CHECK-X280:       for.body6:
; CHECK-X280-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY6_PREHEADER_NEW]] ], [ [[INDVARS_IV_NEXT_7:%.*]], [[FOR_BODY6]] ]
; CHECK-X280-NEXT:    [[NITER:%.*]] = phi i64 [ 0, [[FOR_BODY6_PREHEADER_NEW]] ], [ [[NITER_NEXT_7:%.*]], [[FOR_BODY6]] ]
; CHECK-X280-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds i16, ptr [[ARG_2:%.*]], i64 [[INDVARS_IV]]
; CHECK-X280-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX10]], align 2
; CHECK-X280-NEXT:    [[CONV:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i16, ptr [[ARG_3:%.*]], i64 [[INDVARS_IV]]
; CHECK-X280-NEXT:    [[TMP2:%.*]] = load i16, ptr [[ARRAYIDX14]], align 2
; CHECK-X280-NEXT:    [[CONV15:%.*]] = sext i16 [[TMP2]] to i32
; CHECK-X280-NEXT:    [[MUL16:%.*]] = mul nsw i32 [[CONV15]], [[CONV]]
; CHECK-X280-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i32, ptr [[ARG_1:%.*]], i64 [[INDVARS_IV]]
; CHECK-X280-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX20]], align 4
; CHECK-X280-NEXT:    [[ADD21:%.*]] = add nsw i32 [[MUL16]], [[TMP3]]
; CHECK-X280-NEXT:    store i32 [[ADD21]], ptr [[ARRAYIDX20]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT:%.*]] = or disjoint i64 [[INDVARS_IV]], 1
; CHECK-X280-NEXT:    [[ARRAYIDX10_1:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT]]
; CHECK-X280-NEXT:    [[TMP4:%.*]] = load i16, ptr [[ARRAYIDX10_1]], align 2
; CHECK-X280-NEXT:    [[CONV_1:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_1:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT]]
; CHECK-X280-NEXT:    [[TMP5:%.*]] = load i16, ptr [[ARRAYIDX14_1]], align 2
; CHECK-X280-NEXT:    [[CONV15_1:%.*]] = sext i16 [[TMP5]] to i32
; CHECK-X280-NEXT:    [[MUL16_1:%.*]] = mul nsw i32 [[CONV15_1]], [[CONV_1]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_1:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT]]
; CHECK-X280-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX20_1]], align 4
; CHECK-X280-NEXT:    [[ADD21_1:%.*]] = add nsw i32 [[MUL16_1]], [[TMP6]]
; CHECK-X280-NEXT:    store i32 [[ADD21_1]], ptr [[ARRAYIDX20_1]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_1:%.*]] = or disjoint i64 [[INDVARS_IV]], 2
; CHECK-X280-NEXT:    [[ARRAYIDX10_2:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_1]]
; CHECK-X280-NEXT:    [[TMP7:%.*]] = load i16, ptr [[ARRAYIDX10_2]], align 2
; CHECK-X280-NEXT:    [[CONV_2:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_2:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_1]]
; CHECK-X280-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX14_2]], align 2
; CHECK-X280-NEXT:    [[CONV15_2:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-X280-NEXT:    [[MUL16_2:%.*]] = mul nsw i32 [[CONV15_2]], [[CONV_2]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_2:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_1]]
; CHECK-X280-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX20_2]], align 4
; CHECK-X280-NEXT:    [[ADD21_2:%.*]] = add nsw i32 [[MUL16_2]], [[TMP9]]
; CHECK-X280-NEXT:    store i32 [[ADD21_2]], ptr [[ARRAYIDX20_2]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_2:%.*]] = or disjoint i64 [[INDVARS_IV]], 3
; CHECK-X280-NEXT:    [[ARRAYIDX10_3:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_2]]
; CHECK-X280-NEXT:    [[TMP10:%.*]] = load i16, ptr [[ARRAYIDX10_3]], align 2
; CHECK-X280-NEXT:    [[CONV_3:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_3:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_2]]
; CHECK-X280-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX14_3]], align 2
; CHECK-X280-NEXT:    [[CONV15_3:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-X280-NEXT:    [[MUL16_3:%.*]] = mul nsw i32 [[CONV15_3]], [[CONV_3]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_3:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_2]]
; CHECK-X280-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX20_3]], align 4
; CHECK-X280-NEXT:    [[ADD21_3:%.*]] = add nsw i32 [[MUL16_3]], [[TMP12]]
; CHECK-X280-NEXT:    store i32 [[ADD21_3]], ptr [[ARRAYIDX20_3]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_3:%.*]] = or disjoint i64 [[INDVARS_IV]], 4
; CHECK-X280-NEXT:    [[ARRAYIDX10_4:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_3]]
; CHECK-X280-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX10_4]], align 2
; CHECK-X280-NEXT:    [[CONV_4:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_4:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_3]]
; CHECK-X280-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX14_4]], align 2
; CHECK-X280-NEXT:    [[CONV15_4:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-X280-NEXT:    [[MUL16_4:%.*]] = mul nsw i32 [[CONV15_4]], [[CONV_4]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_4:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_3]]
; CHECK-X280-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX20_4]], align 4
; CHECK-X280-NEXT:    [[ADD21_4:%.*]] = add nsw i32 [[MUL16_4]], [[TMP15]]
; CHECK-X280-NEXT:    store i32 [[ADD21_4]], ptr [[ARRAYIDX20_4]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_4:%.*]] = or disjoint i64 [[INDVARS_IV]], 5
; CHECK-X280-NEXT:    [[ARRAYIDX10_5:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_4]]
; CHECK-X280-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX10_5]], align 2
; CHECK-X280-NEXT:    [[CONV_5:%.*]] = sext i16 [[TMP16]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_5:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_4]]
; CHECK-X280-NEXT:    [[TMP17:%.*]] = load i16, ptr [[ARRAYIDX14_5]], align 2
; CHECK-X280-NEXT:    [[CONV15_5:%.*]] = sext i16 [[TMP17]] to i32
; CHECK-X280-NEXT:    [[MUL16_5:%.*]] = mul nsw i32 [[CONV15_5]], [[CONV_5]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_5:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_4]]
; CHECK-X280-NEXT:    [[TMP18:%.*]] = load i32, ptr [[ARRAYIDX20_5]], align 4
; CHECK-X280-NEXT:    [[ADD21_5:%.*]] = add nsw i32 [[MUL16_5]], [[TMP18]]
; CHECK-X280-NEXT:    store i32 [[ADD21_5]], ptr [[ARRAYIDX20_5]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_5:%.*]] = or disjoint i64 [[INDVARS_IV]], 6
; CHECK-X280-NEXT:    [[ARRAYIDX10_6:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_5]]
; CHECK-X280-NEXT:    [[TMP19:%.*]] = load i16, ptr [[ARRAYIDX10_6]], align 2
; CHECK-X280-NEXT:    [[CONV_6:%.*]] = sext i16 [[TMP19]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_6:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_5]]
; CHECK-X280-NEXT:    [[TMP20:%.*]] = load i16, ptr [[ARRAYIDX14_6]], align 2
; CHECK-X280-NEXT:    [[CONV15_6:%.*]] = sext i16 [[TMP20]] to i32
; CHECK-X280-NEXT:    [[MUL16_6:%.*]] = mul nsw i32 [[CONV15_6]], [[CONV_6]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_6:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_5]]
; CHECK-X280-NEXT:    [[TMP21:%.*]] = load i32, ptr [[ARRAYIDX20_6]], align 4
; CHECK-X280-NEXT:    [[ADD21_6:%.*]] = add nsw i32 [[MUL16_6]], [[TMP21]]
; CHECK-X280-NEXT:    store i32 [[ADD21_6]], ptr [[ARRAYIDX20_6]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_6:%.*]] = or disjoint i64 [[INDVARS_IV]], 7
; CHECK-X280-NEXT:    [[ARRAYIDX10_7:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_6]]
; CHECK-X280-NEXT:    [[TMP22:%.*]] = load i16, ptr [[ARRAYIDX10_7]], align 2
; CHECK-X280-NEXT:    [[CONV_7:%.*]] = sext i16 [[TMP22]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_7:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_6]]
; CHECK-X280-NEXT:    [[TMP23:%.*]] = load i16, ptr [[ARRAYIDX14_7]], align 2
; CHECK-X280-NEXT:    [[CONV15_7:%.*]] = sext i16 [[TMP23]] to i32
; CHECK-X280-NEXT:    [[MUL16_7:%.*]] = mul nsw i32 [[CONV15_7]], [[CONV_7]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_7:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_6]]
; CHECK-X280-NEXT:    [[TMP24:%.*]] = load i32, ptr [[ARRAYIDX20_7]], align 4
; CHECK-X280-NEXT:    [[ADD21_7:%.*]] = add nsw i32 [[MUL16_7]], [[TMP24]]
; CHECK-X280-NEXT:    store i32 [[ADD21_7]], ptr [[ARRAYIDX20_7]], align 4
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_7]] = add nuw nsw i64 [[INDVARS_IV]], 8
; CHECK-X280-NEXT:    [[NITER_NEXT_7]] = add i64 [[NITER]], 8
; CHECK-X280-NEXT:    [[NITER_NCMP_7:%.*]] = icmp eq i64 [[NITER_NEXT_7]], [[UNROLL_ITER]]
; CHECK-X280-NEXT:    br i1 [[NITER_NCMP_7]], label [[FOR_END_LOOPEXIT_UNR_LCSSA]], label [[FOR_BODY6]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-X280:       for.end.loopexit.unr-lcssa:
; CHECK-X280-NEXT:    [[INDVARS_IV_UNR:%.*]] = phi i64 [ 0, [[FOR_BODY6_PREHEADER]] ], [ [[INDVARS_IV_NEXT_7]], [[FOR_BODY6]] ]
; CHECK-X280-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0
; CHECK-X280-NEXT:    br i1 [[LCMP_MOD_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL:%.*]]
; CHECK-X280:       for.body6.epil:
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_UNR]]
; CHECK-X280-NEXT:    [[TMP25:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL:%.*]] = sext i16 [[TMP25]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_UNR]]
; CHECK-X280-NEXT:    [[TMP26:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL:%.*]] = sext i16 [[TMP26]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL:%.*]] = mul nsw i32 [[CONV15_EPIL]], [[CONV_EPIL]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_UNR]]
; CHECK-X280-NEXT:    [[TMP27:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL:%.*]] = add nsw i32 [[MUL16_EPIL]], [[TMP27]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL]], ptr [[ARRAYIDX20_EPIL]], align 4
; CHECK-X280-NEXT:    [[EPIL_ITER_CMP_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 1
; CHECK-X280-NEXT:    br i1 [[EPIL_ITER_CMP_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL_1:%.*]]
; CHECK-X280:       for.body6.epil.1:
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_EPIL:%.*]] = add nuw nsw i64 [[INDVARS_IV_UNR]], 1
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL_1:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_EPIL]]
; CHECK-X280-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL_1]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL_1:%.*]] = sext i16 [[TMP28]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL_1:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_EPIL]]
; CHECK-X280-NEXT:    [[TMP29:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL_1]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL_1:%.*]] = sext i16 [[TMP29]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL_1:%.*]] = mul nsw i32 [[CONV15_EPIL_1]], [[CONV_EPIL_1]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_EPIL]]
; CHECK-X280-NEXT:    [[TMP30:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL_1]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL_1:%.*]] = add nsw i32 [[MUL16_EPIL_1]], [[TMP30]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL_1]], ptr [[ARRAYIDX20_EPIL_1]], align 4
; CHECK-X280-NEXT:    [[EPIL_ITER_CMP_1_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 2
; CHECK-X280-NEXT:    br i1 [[EPIL_ITER_CMP_1_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL_2:%.*]]
; CHECK-X280:       for.body6.epil.2:
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_EPIL_1:%.*]] = add nuw nsw i64 [[INDVARS_IV_UNR]], 2
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL_2:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_EPIL_1]]
; CHECK-X280-NEXT:    [[TMP31:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL_2]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL_2:%.*]] = sext i16 [[TMP31]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL_2:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_EPIL_1]]
; CHECK-X280-NEXT:    [[TMP32:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL_2]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL_2:%.*]] = sext i16 [[TMP32]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL_2:%.*]] = mul nsw i32 [[CONV15_EPIL_2]], [[CONV_EPIL_2]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_EPIL_1]]
; CHECK-X280-NEXT:    [[TMP33:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL_2]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL_2:%.*]] = add nsw i32 [[MUL16_EPIL_2]], [[TMP33]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL_2]], ptr [[ARRAYIDX20_EPIL_2]], align 4
; CHECK-X280-NEXT:    [[EPIL_ITER_CMP_2_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 3
; CHECK-X280-NEXT:    br i1 [[EPIL_ITER_CMP_2_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL_3:%.*]]
; CHECK-X280:       for.body6.epil.3:
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_EPIL_2:%.*]] = add nuw nsw i64 [[INDVARS_IV_UNR]], 3
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL_3:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_EPIL_2]]
; CHECK-X280-NEXT:    [[TMP34:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL_3]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL_3:%.*]] = sext i16 [[TMP34]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL_3:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_EPIL_2]]
; CHECK-X280-NEXT:    [[TMP35:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL_3]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL_3:%.*]] = sext i16 [[TMP35]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL_3:%.*]] = mul nsw i32 [[CONV15_EPIL_3]], [[CONV_EPIL_3]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL_3:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_EPIL_2]]
; CHECK-X280-NEXT:    [[TMP36:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL_3]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL_3:%.*]] = add nsw i32 [[MUL16_EPIL_3]], [[TMP36]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL_3]], ptr [[ARRAYIDX20_EPIL_3]], align 4
; CHECK-X280-NEXT:    [[EPIL_ITER_CMP_3_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 4
; CHECK-X280-NEXT:    br i1 [[EPIL_ITER_CMP_3_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL_4:%.*]]
; CHECK-X280:       for.body6.epil.4:
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_EPIL_3:%.*]] = add nuw nsw i64 [[INDVARS_IV_UNR]], 4
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL_4:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_EPIL_3]]
; CHECK-X280-NEXT:    [[TMP37:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL_4]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL_4:%.*]] = sext i16 [[TMP37]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL_4:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_EPIL_3]]
; CHECK-X280-NEXT:    [[TMP38:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL_4]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL_4:%.*]] = sext i16 [[TMP38]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL_4:%.*]] = mul nsw i32 [[CONV15_EPIL_4]], [[CONV_EPIL_4]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL_4:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_EPIL_3]]
; CHECK-X280-NEXT:    [[TMP39:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL_4]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL_4:%.*]] = add nsw i32 [[MUL16_EPIL_4]], [[TMP39]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL_4]], ptr [[ARRAYIDX20_EPIL_4]], align 4
; CHECK-X280-NEXT:    [[EPIL_ITER_CMP_4_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 5
; CHECK-X280-NEXT:    br i1 [[EPIL_ITER_CMP_4_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL_5:%.*]]
; CHECK-X280:       for.body6.epil.5:
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_EPIL_4:%.*]] = add nuw nsw i64 [[INDVARS_IV_UNR]], 5
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL_5:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_EPIL_4]]
; CHECK-X280-NEXT:    [[TMP40:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL_5]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL_5:%.*]] = sext i16 [[TMP40]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL_5:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_EPIL_4]]
; CHECK-X280-NEXT:    [[TMP41:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL_5]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL_5:%.*]] = sext i16 [[TMP41]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL_5:%.*]] = mul nsw i32 [[CONV15_EPIL_5]], [[CONV_EPIL_5]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL_5:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_EPIL_4]]
; CHECK-X280-NEXT:    [[TMP42:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL_5]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL_5:%.*]] = add nsw i32 [[MUL16_EPIL_5]], [[TMP42]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL_5]], ptr [[ARRAYIDX20_EPIL_5]], align 4
; CHECK-X280-NEXT:    [[EPIL_ITER_CMP_5_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 6
; CHECK-X280-NEXT:    br i1 [[EPIL_ITER_CMP_5_NOT]], label [[FOR_END]], label [[FOR_BODY6_EPIL_6:%.*]]
; CHECK-X280:       for.body6.epil.6:
; CHECK-X280-NEXT:    [[INDVARS_IV_NEXT_EPIL_5:%.*]] = add nuw nsw i64 [[INDVARS_IV_UNR]], 6
; CHECK-X280-NEXT:    [[ARRAYIDX10_EPIL_6:%.*]] = getelementptr inbounds i16, ptr [[ARG_2]], i64 [[INDVARS_IV_NEXT_EPIL_5]]
; CHECK-X280-NEXT:    [[TMP43:%.*]] = load i16, ptr [[ARRAYIDX10_EPIL_6]], align 2
; CHECK-X280-NEXT:    [[CONV_EPIL_6:%.*]] = sext i16 [[TMP43]] to i32
; CHECK-X280-NEXT:    [[ARRAYIDX14_EPIL_6:%.*]] = getelementptr inbounds i16, ptr [[ARG_3]], i64 [[INDVARS_IV_NEXT_EPIL_5]]
; CHECK-X280-NEXT:    [[TMP44:%.*]] = load i16, ptr [[ARRAYIDX14_EPIL_6]], align 2
; CHECK-X280-NEXT:    [[CONV15_EPIL_6:%.*]] = sext i16 [[TMP44]] to i32
; CHECK-X280-NEXT:    [[MUL16_EPIL_6:%.*]] = mul nsw i32 [[CONV15_EPIL_6]], [[CONV_EPIL_6]]
; CHECK-X280-NEXT:    [[ARRAYIDX20_EPIL_6:%.*]] = getelementptr inbounds i32, ptr [[ARG_1]], i64 [[INDVARS_IV_NEXT_EPIL_5]]
; CHECK-X280-NEXT:    [[TMP45:%.*]] = load i32, ptr [[ARRAYIDX20_EPIL_6]], align 4
; CHECK-X280-NEXT:    [[ADD21_EPIL_6:%.*]] = add nsw i32 [[MUL16_EPIL_6]], [[TMP45]]
; CHECK-X280-NEXT:    store i32 [[ADD21_EPIL_6]], ptr [[ARRAYIDX20_EPIL_6]], align 4
; CHECK-X280-NEXT:    br label [[FOR_END]]
; CHECK-X280:       for.end:
; CHECK-X280-NEXT:    ret void
;
; CHECK-P470-LABEL: @runtime_unroll_generic(
; CHECK-P470-NEXT:  entry:
; CHECK-P470-NEXT:    [[CMP52_NOT:%.*]] = icmp eq i32 [[ARG_0:%.*]], 0
; CHECK-P470-NEXT:    br i1 [[CMP52_NOT]], label [[FOR_END:%.*]], label [[FOR_BODY6_PREHEADER:%.*]]
; CHECK-P470:       for.body6.preheader:
; CHECK-P470-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[ARG_0]] to i64
; CHECK-P470-NEXT:    br label [[FOR_BODY6:%.*]]
; CHECK-P470:       for.body6:
; CHECK-P470-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY6_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY6]] ]
; CHECK-P470-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds i16, ptr [[ARG_2:%.*]], i64 [[INDVARS_IV]]
; CHECK-P470-NEXT:    [[TMP0:%.*]] = load i16, ptr [[ARRAYIDX10]], align 2
; CHECK-P470-NEXT:    [[CONV:%.*]] = sext i16 [[TMP0]] to i32
; CHECK-P470-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i16, ptr [[ARG_3:%.*]], i64 [[INDVARS_IV]]
; CHECK-P470-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX14]], align 2
; CHECK-P470-NEXT:    [[CONV15:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-P470-NEXT:    [[MUL16:%.*]] = mul nsw i32 [[CONV15]], [[CONV]]
; CHECK-P470-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i32, ptr [[ARG_1:%.*]], i64 [[INDVARS_IV]]
; CHECK-P470-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX20]], align 4
; CHECK-P470-NEXT:    [[ADD21:%.*]] = add nsw i32 [[MUL16]], [[TMP2]]
; CHECK-P470-NEXT:    store i32 [[ADD21]], ptr [[ARRAYIDX20]], align 4
; CHECK-P470-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-P470-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-P470-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_END]], label [[FOR_BODY6]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-P470:       for.end:
; CHECK-P470-NEXT:    ret void
;
entry:
  %arg_0.addr = alloca i32, align 4
  %arg_1.addr = alloca ptr, align 8
  %arg_2.addr = alloca ptr, align 8
  %arg_3.addr = alloca ptr, align 8
  %k = alloca i32, align 4
  store i32 %arg_0, ptr %arg_0.addr, align 4
  store ptr %arg_1, ptr %arg_1.addr, align 8
  store ptr %arg_2, ptr %arg_2.addr, align 8
  store ptr %arg_3, ptr %arg_3.addr, align 8
  br label %for.cond

for.cond:                                         ; preds = %entry
  br label %for.body

for.body:                                         ; preds = %for.cond
  br label %for.cond1

for.cond1:                                        ; preds = %for.body
  br label %for.body3

for.body3:                                        ; preds = %for.cond1
  store i32 0, ptr %k, align 4
  br label %for.cond4

for.cond4:                                        ; preds = %for.inc, %for.body3
  %0 = load i32, ptr %k, align 4
  %1 = load i32, ptr %arg_0.addr, align 4
  %cmp5 = icmp ult i32 %0, %1
  br i1 %cmp5, label %for.body6, label %for.end

for.body6:                                        ; preds = %for.cond4
  %2 = load ptr, ptr %arg_2.addr, align 8
  %idx.ext = zext i32 %0 to i64
  %arrayidx10 = getelementptr inbounds i16, ptr %2, i64 %idx.ext
  %3 = load i16, ptr %arrayidx10, align 2
  %conv = sext i16 %3 to i32
  %4 = load ptr, ptr %arg_3.addr, align 8
  %arrayidx14 = getelementptr inbounds i16, ptr %4, i64 %idx.ext
  %5 = load i16, ptr %arrayidx14, align 2
  %conv15 = sext i16 %5 to i32
  %mul16 = mul nsw i32 %conv, %conv15
  %6 = load ptr, ptr %arg_1.addr, align 8
  %arrayidx20 = getelementptr inbounds i32, ptr %6, i64 %idx.ext
  %7 = load i32, ptr %arrayidx20, align 4
  %add21 = add nsw i32 %7, %mul16
  store i32 %add21, ptr %arrayidx20, align 4
  br label %for.inc

for.inc:                                          ; preds = %for.body6
  %8 = load i32, ptr %k, align 4
  %inc = add i32 %8, 1
  store i32 %inc, ptr %k, align 4
  br label %for.cond4, !llvm.loop !0

for.end:                                          ; preds = %for.cond4
  ret void
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.mustprogress"}
