// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -target-feature +experimental-zvkb \
// RUN:  -target-feature +experimental-zvkg -target-feature +experimental-zvknha \
// RUN:  -target-feature +experimental-zvknhb -target-feature +experimental-zvkns \
// RUN:  -target-feature +experimental-zvksed -target-feature +experimental-zvksh \
// RUN:  -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf4_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.nxv1bf16.nxv1f32.i64(<vscale x 1 x bfloat> [[MASKEDOFF:%.*]], <vscale x 1 x float> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_sf_vfncvt_bf16_f_w_bf16mf4_tu(vbfloat16mf4_t maskedoff, vfloat32mf2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf2_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.nxv2bf16.nxv2f32.i64(<vscale x 2 x bfloat> [[MASKEDOFF:%.*]], <vscale x 2 x float> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_sf_vfncvt_bf16_f_w_bf16mf2_tu(vbfloat16mf2_t maskedoff, vfloat32m1_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m1_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.nxv4bf16.nxv4f32.i64(<vscale x 4 x bfloat> [[MASKEDOFF:%.*]], <vscale x 4 x float> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_sf_vfncvt_bf16_f_w_bf16m1_tu(vbfloat16m1_t maskedoff, vfloat32m2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m2_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.nxv8bf16.nxv8f32.i64(<vscale x 8 x bfloat> [[MASKEDOFF:%.*]], <vscale x 8 x float> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_sf_vfncvt_bf16_f_w_bf16m2_tu(vbfloat16m2_t maskedoff, vfloat32m4_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m4_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.nxv16bf16.nxv16f32.i64(<vscale x 16 x bfloat> [[MASKEDOFF:%.*]], <vscale x 16 x float> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_sf_vfncvt_bf16_f_w_bf16m4_tu(vbfloat16m4_t maskedoff, vfloat32m8_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf4_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv1bf16.nxv1f32.i64(<vscale x 1 x bfloat> [[MASKEDOFF:%.*]], <vscale x 1 x float> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_sf_vfncvt_bf16_f_w_bf16mf4_tum(vbool64_t mask, vbfloat16mf4_t maskedoff, vfloat32mf2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf2_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv2bf16.nxv2f32.i64(<vscale x 2 x bfloat> [[MASKEDOFF:%.*]], <vscale x 2 x float> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_sf_vfncvt_bf16_f_w_bf16mf2_tum(vbool32_t mask, vbfloat16mf2_t maskedoff, vfloat32m1_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m1_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv4bf16.nxv4f32.i64(<vscale x 4 x bfloat> [[MASKEDOFF:%.*]], <vscale x 4 x float> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_sf_vfncvt_bf16_f_w_bf16m1_tum(vbool16_t mask, vbfloat16m1_t maskedoff, vfloat32m2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m2_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv8bf16.nxv8f32.i64(<vscale x 8 x bfloat> [[MASKEDOFF:%.*]], <vscale x 8 x float> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_sf_vfncvt_bf16_f_w_bf16m2_tum(vbool8_t mask, vbfloat16m2_t maskedoff, vfloat32m4_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m4_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv16bf16.nxv16f32.i64(<vscale x 16 x bfloat> [[MASKEDOFF:%.*]], <vscale x 16 x float> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_sf_vfncvt_bf16_f_w_bf16m4_tum(vbool4_t mask, vbfloat16m4_t maskedoff, vfloat32m8_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf4_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv1bf16.nxv1f32.i64(<vscale x 1 x bfloat> [[MASKEDOFF:%.*]], <vscale x 1 x float> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_sf_vfncvt_bf16_f_w_bf16mf4_tumu(vbool64_t mask, vbfloat16mf4_t maskedoff, vfloat32mf2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf2_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv2bf16.nxv2f32.i64(<vscale x 2 x bfloat> [[MASKEDOFF:%.*]], <vscale x 2 x float> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_sf_vfncvt_bf16_f_w_bf16mf2_tumu(vbool32_t mask, vbfloat16mf2_t maskedoff, vfloat32m1_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m1_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv4bf16.nxv4f32.i64(<vscale x 4 x bfloat> [[MASKEDOFF:%.*]], <vscale x 4 x float> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_sf_vfncvt_bf16_f_w_bf16m1_tumu(vbool16_t mask, vbfloat16m1_t maskedoff, vfloat32m2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m2_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv8bf16.nxv8f32.i64(<vscale x 8 x bfloat> [[MASKEDOFF:%.*]], <vscale x 8 x float> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_sf_vfncvt_bf16_f_w_bf16m2_tumu(vbool8_t mask, vbfloat16m2_t maskedoff, vfloat32m4_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m4_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv16bf16.nxv16f32.i64(<vscale x 16 x bfloat> [[MASKEDOFF:%.*]], <vscale x 16 x float> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_sf_vfncvt_bf16_f_w_bf16m4_tumu(vbool4_t mask, vbfloat16m4_t maskedoff, vfloat32m8_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf4_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv1bf16.nxv1f32.i64(<vscale x 1 x bfloat> [[MASKEDOFF:%.*]], <vscale x 1 x float> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 1 x bfloat> [[TMP0]]
//
vbfloat16mf4_t test_sf_vfncvt_bf16_f_w_bf16mf4_mu(vbool64_t mask, vbfloat16mf4_t maskedoff, vfloat32mf2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16mf2_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv2bf16.nxv2f32.i64(<vscale x 2 x bfloat> [[MASKEDOFF:%.*]], <vscale x 2 x float> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 2 x bfloat> [[TMP0]]
//
vbfloat16mf2_t test_sf_vfncvt_bf16_f_w_bf16mf2_mu(vbool32_t mask, vbfloat16mf2_t maskedoff, vfloat32m1_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m1_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv4bf16.nxv4f32.i64(<vscale x 4 x bfloat> [[MASKEDOFF:%.*]], <vscale x 4 x float> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 4 x bfloat> [[TMP0]]
//
vbfloat16m1_t test_sf_vfncvt_bf16_f_w_bf16m1_mu(vbool16_t mask, vbfloat16m1_t maskedoff, vfloat32m2_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m2_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv8bf16.nxv8f32.i64(<vscale x 8 x bfloat> [[MASKEDOFF:%.*]], <vscale x 8 x float> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 8 x bfloat> [[TMP0]]
//
vbfloat16m2_t test_sf_vfncvt_bf16_f_w_bf16m2_mu(vbool8_t mask, vbfloat16m2_t maskedoff, vfloat32m4_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfncvt_bf16_f_w_bf16m4_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x bfloat> @llvm.riscv.sf.vfncvt.bf16.f.w.mask.nxv16bf16.nxv16f32.i64(<vscale x 16 x bfloat> [[MASKEDOFF:%.*]], <vscale x 16 x float> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 16 x bfloat> [[TMP0]]
//
vbfloat16m4_t test_sf_vfncvt_bf16_f_w_bf16m4_mu(vbool4_t mask, vbfloat16m4_t maskedoff, vfloat32m8_t src, size_t vl) {
  return __riscv_sf_vfncvt_bf16_mu(mask, maskedoff, src, vl);
}

