; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple riscv64 -mcpu=sifive-p670 -S -passes='loop-vectorize,loop-mssa(licm)' < %s | FileCheck %s

; Same exit block for both exiting blocks
; Make sure this doesn't crash in fixupIVUsers
define void @foo(ptr %arg1, i64 %arg2) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: ptr [[ARG1:%.*]], i64 [[ARG2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ARG11:%.*]] = ptrtoint ptr [[ARG1]] to i64
; CHECK-NEXT:    [[GETP1:%.*]] = getelementptr i8, ptr [[ARG1]], i64 [[ARG2]]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[ARG2]], [[ARG11]]
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[ARG11]], 1
; CHECK-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP0]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 [[UMAX]], [[ARG11]]
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ule i64 [[TMP2]], 10
; CHECK-NEXT:    br i1 [[TMP3]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[ARG1]], i64 [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP6:%.*]] = mul nuw i64 [[TMP5]], 16
; CHECK-NEXT:    [[TMP7:%.*]] = mul i64 [[TMP6]], 0
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP7]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; CHECK-NEXT:    [[TMP9:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = mul <vscale x 16 x i64> [[TMP9]], splat (i64 1)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[ARG1]], %[[VECTOR_PH]] ], [ [[PTR_IND:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP10]]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP2]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP11:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP11]], i32 16, i1 true)
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[TMP13]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP14]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP12]])
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = zext i32 [[TMP15]] to i64
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP17]], <vscale x 16 x i8> splat (i8 37), metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP15]])
; CHECK-NEXT:    [[TMP24:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP15]])
; CHECK-NEXT:    [[TMP19:%.*]] = icmp sge i32 [[TMP24]], 0
; CHECK-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP15]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP18]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP20:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP2]]
; CHECK-NEXT:    [[DOTREASS:%.*]] = mul i64 [[TMP16]], 1
; CHECK-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[DOTREASS]]
; CHECK-NEXT:    [[TMP21:%.*]] = or i1 [[TMP19]], [[TMP20]]
; CHECK-NEXT:    br i1 [[TMP21]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_SPLIT]]:
; CHECK-NEXT:    [[TMP22:%.*]] = phi i64 [ [[EVL_BASED_IV]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[DOTLCSSA2:%.*]] = phi i32 [ [[TMP24]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi i1 [ [[TMP19]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    br i1 [[DOTLCSSA]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    [[INDEX_LCSSA:%.*]] = zext i32 [[DOTLCSSA2]] to i64
; CHECK-NEXT:    [[TMP23:%.*]] = add i64 [[TMP22]], [[INDEX_LCSSA]]
; CHECK-NEXT:    [[IND_EARLY_ESCAPE:%.*]] = getelementptr i8, ptr [[ARG1]], i64 [[TMP23]]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[ARG1]], %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI1:%.*]] = phi ptr [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[GEP2:%.*]], %[[LOOP_NEXT:.*]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, ptr [[PHI1]], align 1
; CHECK-NEXT:    [[ICMP1:%.*]] = icmp eq i8 [[LOAD]], 37
; CHECK-NEXT:    br i1 [[ICMP1]], label %[[EXIT_LOOPEXIT:.*]], label %[[LOOP_NEXT]]
; CHECK:       [[LOOP_NEXT]]:
; CHECK-NEXT:    [[GEP2]] = getelementptr i8, ptr [[PHI1]], i64 1
; CHECK-NEXT:    [[ICMP2:%.*]] = icmp ult ptr [[GEP2]], [[GETP1]]
; CHECK-NEXT:    br i1 [[ICMP2]], label %[[LOOP]], label %[[EXIT_LOOPEXIT]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[EXIT_LOOPEXIT]]:
; CHECK-NEXT:    [[PHI2_PH:%.*]] = phi ptr [ [[PHI1]], %[[LOOP]] ], [ [[GEP2]], %[[LOOP_NEXT]] ]
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[PHI2:%.*]] = phi ptr [ [[TMP4]], %[[MIDDLE_BLOCK]] ], [ [[IND_EARLY_ESCAPE]], %[[VECTOR_EARLY_EXIT]] ], [ [[PHI2_PH]], %[[EXIT_LOOPEXIT]] ]
; CHECK-NEXT:    ret void
;
entry:
  %getp1 = getelementptr i8, ptr %arg1, i64 %arg2
  br label %loop

loop:
  %phi1 = phi ptr [ %arg1, %entry ], [ %gep2, %loop.next ]
  %load = load i8, ptr %phi1, align 1
  %icmp1 = icmp eq i8 %load, 37
  br i1 %icmp1, label %exit, label %loop.next

loop.next:
  %gep2 = getelementptr i8, ptr %phi1, i64 1
  %icmp2 = icmp ult ptr %gep2, %getp1
  br i1 %icmp2, label %loop, label %exit

exit:
  %phi2 = phi ptr [ %gep2, %loop.next ], [ %phi1, %loop ]
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
