; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple riscv64 -mcpu=sifive-p670 -S -passes='loop-vectorize,loop-mssa(licm)' < %s | FileCheck %s

; Ensure LoopInfo remains accurate and the vectorized loop does not crash during LICM.
define i64 @x86_Convert(ptr %data, i64 %size, i32 %ip, ptr %state, i32 %encoding) #0 {
; CHECK-LABEL: define i64 @x86_Convert(
; CHECK-SAME: ptr [[DATA:%.*]], i64 [[SIZE:%.*]], i32 [[IP:%.*]], ptr [[STATE:%.*]], i32 [[ENCODING:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ADD_PTR2:%.*]] = getelementptr i8, ptr null, i64 -4
; CHECK-NEXT:    br label %[[FOR_BODY_LR_PH:.*]]
; CHECK:       [[FOR_BODY_LR_PH_LOOPEXIT_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY_LR_PH_LOOPEXIT:.*]]
; CHECK:       [[FOR_BODY_LR_PH_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_BODY_LR_PH]]
; CHECK:       [[FOR_BODY_LR_PH]]:
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 -4, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP4]], i32 32, i1 true)
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr null, i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[GEP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.and.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 -2), <vscale x 32 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 -24), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[TMP17:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[TMP12:%.*]] = icmp sge i32 [[TMP17]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP8]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP11]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], -4
; CHECK-NEXT:    [[TMP14:%.*]] = or i1 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_SPLIT]]:
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi i1 [ [[TMP12]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    br i1 [[DOTLCSSA]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[FOR_END128:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[FOR_BODY_LR_PH_LOOPEXIT]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ null, %[[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[P_083:%.*]] = phi ptr [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], %[[FOR_INC:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_083]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = and i8 [[TMP0]], -2
; CHECK-NEXT:    [[CMP6:%.*]] = icmp eq i8 [[TMP1]], -24
; CHECK-NEXT:    br i1 [[CMP6]], label %[[FOR_BODY_LR_PH_LOOPEXIT_LOOPEXIT]], label %[[FOR_INC]]
; CHECK:       [[FOR_INC]]:
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr i8, ptr [[P_083]], i64 1
; CHECK-NEXT:    [[CMP4:%.*]] = icmp ult ptr [[INCDEC_PTR]], [[ADD_PTR2]]
; CHECK-NEXT:    br i1 [[CMP4]], label %[[FOR_BODY]], label %[[FOR_END128_LOOPEXIT:.*]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[FOR_END128_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_END128]]
; CHECK:       [[FOR_END128]]:
; CHECK-NEXT:    ret i64 0
;
entry:
  %add.ptr2 = getelementptr i8, ptr null, i64 -4
  br label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %for.body, %entry
  br label %for.body

for.body:                                         ; preds = %for.inc, %for.body.lr.ph
  %p.083 = phi ptr [ null, %for.body.lr.ph ], [ %incdec.ptr, %for.inc ]
  %0 = load i8, ptr %p.083, align 1
  %1 = and i8 %0, -2
  %cmp6 = icmp eq i8 %1, -24
  br i1 %cmp6, label %for.body.lr.ph, label %for.inc

for.inc:                                          ; preds = %for.body
  %incdec.ptr = getelementptr i8, ptr %p.083, i64 1
  %cmp4 = icmp ult ptr %incdec.ptr, %add.ptr2
  br i1 %cmp4, label %for.body, label %for.end128

for.end128:                                       ; preds = %for.inc
  ret i64 0
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
