; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=stress < %s | FileCheck %s
; RUN: opt -S -passes=loop-vectorize -mtriple=riscv64 -mcpu=sifive-p470 < %s | FileCheck %s --check-prefix=P470

; int* my_find(int* first, int* last, const int& value) {
;   for (; first != last; ++first) {
;     if (*first == value) {
;       return first;
;     }
;   }
;   return last;
; }

define ptr @find(ptr %first, ptr %last, ptr %value) {
; CHECK-LABEL: @find(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[FIRST4:%.*]] = ptrtoint ptr [[FIRST:%.*]] to i64
; CHECK-NEXT:    [[LAST3:%.*]] = ptrtoint ptr [[LAST:%.*]] to i64
; CHECK-NEXT:    [[FIRST2:%.*]] = ptrtoint ptr [[FIRST]] to i64
; CHECK-NEXT:    [[LAST1:%.*]] = ptrtoint ptr [[LAST]] to i64
; CHECK-NEXT:    [[CMP_NOT6:%.*]] = icmp eq ptr [[FIRST]], [[LAST]]
; CHECK-NEXT:    br i1 [[CMP_NOT6]], label [[RETURN:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[LAST3]], -4
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 [[TMP1]], [[FIRST4]]
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i64 [[TMP2]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = add nuw nsw i64 [[TMP3]], 1
; CHECK-NEXT:    br label [[VECTOR_SCEVCHECK:%.*]]
; CHECK:       vector.scevcheck:
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[LAST1]] to i2
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i64 [[FIRST2]] to i2
; CHECK-NEXT:    [[TMP7:%.*]] = sub i2 [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = zext i2 [[TMP7]] to i64
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[IDENT_CHECK]], label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[TMP0]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP4]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP17:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP18:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP17]], i32 2, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[FIRST]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i32, ptr [[TMP19]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 2 x i32>, i32 } @llvm.vp.load.ff.nxv2i32.p0(ptr align 4 [[TMP20]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP18]])
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <vscale x 2 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <vscale x 2 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[TMP23]], <vscale x 2 x i32> [[BROADCAST_SPLAT]], metadata !"eq", <vscale x 2 x i1> splat (i1 true), i32 [[TMP21]])
; CHECK-NEXT:    [[TMP34:%.*]] = call i32 @llvm.vp.first.nxv2i1(<vscale x 2 x i1> [[VP_OP_ICMP]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP21]])
; CHECK-NEXT:    [[TMP25:%.*]] = icmp sge i32 [[TMP34]], 0
; CHECK-NEXT:    [[TMP24:%.*]] = zext i32 [[TMP21]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP24]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP26:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP4]]
; CHECK-NEXT:    [[TMP29:%.*]] = or i1 [[TMP25]], [[TMP26]]
; CHECK-NEXT:    br i1 [[TMP29]], label [[MIDDLE_SPLIT:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.split:
; CHECK-NEXT:    br i1 [[TMP25]], label [[VECTOR_EARLY_EXIT:%.*]], label [[VEC_UNCOUNTABLE_MIDDLE_BLOCK:%.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[RETURN_LOOPEXIT:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    [[TMP30:%.*]] = zext i32 [[TMP34]] to i64
; CHECK-NEXT:    [[TMP31:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP30]]
; CHECK-NEXT:    [[TMP32:%.*]] = mul i64 [[TMP31]], 4
; CHECK-NEXT:    [[IND_EARLY_ESCAPE:%.*]] = getelementptr i8, ptr [[FIRST]], i64 [[TMP32]]
; CHECK-NEXT:    br label [[RETURN_LOOPEXIT]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[FIRST]], [[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    br label [[FOR_BODY1:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[BC_RESUME_VAL]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[FIRST_ADDR_07]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP33]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT]], label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY1]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       return.loopexit:
; CHECK-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY1]] ], [ [[LAST]], [[FOR_INC]] ], [ [[LAST]], [[VEC_UNCOUNTABLE_MIDDLE_BLOCK]] ], [ [[IND_EARLY_ESCAPE]], [[VECTOR_EARLY_EXIT]] ]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ [[FIRST]], [[ENTRY:%.*]] ], [ [[RETVAL_0_PH]], [[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret ptr [[RETVAL_0]]
;
; P470-LABEL: @find(
; P470-NEXT:  entry:
; P470-NEXT:    [[FIRST4:%.*]] = ptrtoint ptr [[FIRST:%.*]] to i64
; P470-NEXT:    [[LAST3:%.*]] = ptrtoint ptr [[LAST:%.*]] to i64
; P470-NEXT:    [[FIRST2:%.*]] = ptrtoint ptr [[FIRST]] to i64
; P470-NEXT:    [[LAST1:%.*]] = ptrtoint ptr [[LAST]] to i64
; P470-NEXT:    [[CMP_NOT6:%.*]] = icmp eq ptr [[FIRST]], [[LAST]]
; P470-NEXT:    br i1 [[CMP_NOT6]], label [[RETURN:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; P470:       for.body.lr.ph:
; P470-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; P470-NEXT:    [[TMP1:%.*]] = add i64 [[LAST3]], -4
; P470-NEXT:    [[TMP2:%.*]] = sub i64 [[TMP1]], [[FIRST4]]
; P470-NEXT:    [[TMP3:%.*]] = lshr i64 [[TMP2]], 2
; P470-NEXT:    [[TMP4:%.*]] = add nuw nsw i64 [[TMP3]], 1
; P470-NEXT:    br label [[VECTOR_SCEVCHECK:%.*]]
; P470:       vector.scevcheck:
; P470-NEXT:    [[TMP5:%.*]] = trunc i64 [[LAST1]] to i2
; P470-NEXT:    [[TMP6:%.*]] = trunc i64 [[FIRST2]] to i2
; P470-NEXT:    [[TMP7:%.*]] = sub i2 [[TMP5]], [[TMP6]]
; P470-NEXT:    [[TMP8:%.*]] = zext i2 [[TMP7]] to i64
; P470-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP8]], 0
; P470-NEXT:    br i1 [[IDENT_CHECK]], label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; P470:       vector.ph:
; P470-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i32> poison, i32 [[TMP0]], i64 0
; P470-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       vector.body:
; P470-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_BODY]] ]
; P470-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[FOR_BODY]] ]
; P470-NEXT:    [[AVL:%.*]] = sub i64 [[TMP4]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP17:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; P470-NEXT:    [[TMP18:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP17]], i32 8, i1 true)
; P470-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; P470-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[FIRST]], i64 [[OFFSET_IDX]]
; P470-NEXT:    [[TMP20:%.*]] = getelementptr i32, ptr [[TMP19]], i32 0
; P470-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP20]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP18]])
; P470-NEXT:    [[TMP21:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; P470-NEXT:    [[TMP23:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; P470-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP23]], <vscale x 8 x i32> [[BROADCAST_SPLAT]], metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP21]])
; P470-NEXT:    [[TMP34:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP21]])
; P470-NEXT:    [[TMP25:%.*]] = icmp sge i32 [[TMP34]], 0
; P470-NEXT:    [[TMP24:%.*]] = zext i32 [[TMP21]] to i64
; P470-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP24]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP26:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP4]]
; P470-NEXT:    [[TMP29:%.*]] = or i1 [[TMP25]], [[TMP26]]
; P470-NEXT:    br i1 [[TMP29]], label [[MIDDLE_SPLIT:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; P470:       middle.split:
; P470-NEXT:    br i1 [[TMP25]], label [[VECTOR_EARLY_EXIT:%.*]], label [[VEC_UNCOUNTABLE_MIDDLE_BLOCK:%.*]]
; P470:       middle.block:
; P470-NEXT:    br label [[RETURN_LOOPEXIT:%.*]]
; P470:       vector.early.exit:
; P470-NEXT:    [[TMP30:%.*]] = zext i32 [[TMP34]] to i64
; P470-NEXT:    [[TMP31:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP30]]
; P470-NEXT:    [[TMP32:%.*]] = mul i64 [[TMP31]], 4
; P470-NEXT:    [[IND_EARLY_ESCAPE:%.*]] = getelementptr i8, ptr [[FIRST]], i64 [[TMP32]]
; P470-NEXT:    br label [[RETURN_LOOPEXIT]]
; P470:       scalar.ph:
; P470-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[FIRST]], [[VECTOR_SCEVCHECK]] ]
; P470-NEXT:    br label [[FOR_BODY1:%.*]]
; P470:       for.body:
; P470-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[BC_RESUME_VAL]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC:%.*]] ]
; P470-NEXT:    [[TMP33:%.*]] = load i32, ptr [[FIRST_ADDR_07]], align 4
; P470-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP33]], [[TMP0]]
; P470-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT]], label [[FOR_INC]]
; P470:       for.inc:
; P470-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; P470-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST]]
; P470-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY1]], !llvm.loop [[LOOP4:![0-9]+]]
; P470:       return.loopexit:
; P470-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY1]] ], [ [[LAST]], [[FOR_INC]] ], [ [[LAST]], [[VEC_UNCOUNTABLE_MIDDLE_BLOCK]] ], [ [[IND_EARLY_ESCAPE]], [[VECTOR_EARLY_EXIT]] ]
; P470-NEXT:    br label [[RETURN]]
; P470:       return:
; P470-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ [[FIRST]], [[ENTRY:%.*]] ], [ [[RETVAL_0_PH]], [[RETURN_LOOPEXIT]] ]
; P470-NEXT:    ret ptr [[RETVAL_0]]
;
entry:
  %cmp.not6 = icmp eq ptr %first, %last
  br i1 %cmp.not6, label %return, label %for.body.lr.ph

for.body.lr.ph:
  %0 = load i32, ptr %value, align 4
  br label %for.body

for.body:
  %first.addr.07 = phi ptr [ %first, %for.body.lr.ph ], [ %incdec.ptr, %for.inc ]
  %1 = load i32, ptr %first.addr.07, align 4
  %cmp1 = icmp eq i32 %1, %0
  br i1 %cmp1, label %return.loopexit, label %for.inc

for.inc:
  %incdec.ptr = getelementptr inbounds i32, ptr %first.addr.07, i64 1
  %cmp.not = icmp eq ptr %incdec.ptr, %last
  br i1 %cmp.not, label %return.loopexit, label %for.body

return.loopexit:
  %retval.0.ph = phi ptr [ %first.addr.07, %for.body ], [ %last, %for.inc ]
  br label %return

return:
  %retval.0 = phi ptr [ %first, %entry ], [ %retval.0.ph, %return.loopexit ]
  ret ptr %retval.0
}

; Support speculative exiting condition at the latch block
define ptr @find2(ptr %first, ptr %last, ptr %value) {
; CHECK-LABEL: @find2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[FIRST:%.*]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_BODY2:%.*]] ]
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST:%.*]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_BODY2]]
; CHECK:       for.body2:
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[INCDEC_PTR]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY]]
; CHECK:       return.loopexit:
; CHECK-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY2]] ], [ [[LAST]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       return:
; CHECK-NEXT:    ret ptr [[RETVAL_0_PH]]
;
; P470-LABEL: @find2(
; P470-NEXT:  entry:
; P470-NEXT:    br label [[FOR_BODY_LR_PH:%.*]]
; P470:       for.body.lr.ph:
; P470-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[FIRST:%.*]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_BODY2:%.*]] ]
; P470-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; P470-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST:%.*]]
; P470-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_BODY2]]
; P470:       for.body2:
; P470-NEXT:    [[TMP1:%.*]] = load i32, ptr [[INCDEC_PTR]], align 4
; P470-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], [[TMP0]]
; P470-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY]]
; P470:       return.loopexit:
; P470-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY2]] ], [ [[LAST]], [[FOR_BODY]] ]
; P470-NEXT:    br label [[RETURN:%.*]]
; P470:       return:
; P470-NEXT:    ret ptr [[RETVAL_0_PH]]
;
entry:
  br label %for.body.lr.ph

for.body.lr.ph:
  %0 = load i32, ptr %value, align 4
  br label %for.body

for.body:
  %first.addr.07 = phi ptr [ %first, %for.body.lr.ph ], [ %incdec.ptr, %for.body2 ]
  %incdec.ptr = getelementptr inbounds i32, ptr %first.addr.07, i64 1
  %cmp.not = icmp eq ptr %incdec.ptr, %last
  br i1 %cmp.not, label %return.loopexit, label %for.body2

for.body2:
  %1 = load i32, ptr %incdec.ptr, align 4
  %cmp1 = icmp eq i32 %1, %0
  br i1 %cmp1, label %return.loopexit, label %for.body

return.loopexit:
  %retval.0.ph = phi ptr [ %first.addr.07, %for.body2 ], [ %last, %for.body ]
  br label %return

return:
  ret ptr %retval.0.ph
}

; This is not vectorized because ICMP_ULE needs a wider type to avoid overflow
define i1 @find3(ptr %first, ptr %last) {
; CHECK-LABEL: @find3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[FIRST_ADDR:%.*]] = phi ptr [ [[FIRST_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[FIRST:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, ptr [[FIRST_ADDR]], align 1
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i8 [[LOAD]], 32
; CHECK-NEXT:    br i1 [[ICMP]], label [[FOR_INC]], label [[RETURN_EARLY:%.*]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[FIRST_NEXT]] = getelementptr inbounds nuw i8, ptr [[FIRST_ADDR]], i64 1
; CHECK-NEXT:    [[ICMP6:%.*]] = icmp ugt ptr [[FIRST_NEXT]], [[LAST:%.*]]
; CHECK-NEXT:    br i1 [[ICMP6]], label [[RETURN:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       return.early:
; CHECK-NEXT:    ret i1 true
; CHECK:       return:
; CHECK-NEXT:    ret i1 false
;
; P470-LABEL: @find3(
; P470-NEXT:  entry:
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[FIRST_ADDR:%.*]] = phi ptr [ [[FIRST_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[FIRST:%.*]], [[ENTRY:%.*]] ]
; P470-NEXT:    [[LOAD:%.*]] = load i8, ptr [[FIRST_ADDR]], align 1
; P470-NEXT:    [[ICMP:%.*]] = icmp eq i8 [[LOAD]], 32
; P470-NEXT:    br i1 [[ICMP]], label [[FOR_INC]], label [[RETURN_EARLY:%.*]]
; P470:       for.inc:
; P470-NEXT:    [[FIRST_NEXT]] = getelementptr inbounds nuw i8, ptr [[FIRST_ADDR]], i64 1
; P470-NEXT:    [[ICMP6:%.*]] = icmp ugt ptr [[FIRST_NEXT]], [[LAST:%.*]]
; P470-NEXT:    br i1 [[ICMP6]], label [[RETURN:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; P470:       return.early:
; P470-NEXT:    ret i1 true
; P470:       return:
; P470-NEXT:    ret i1 false
;
entry:
  br label %for.body

for.body:
  %first.addr = phi ptr [ %first.next, %for.inc ], [ %first, %entry ]
  %load = load i8, ptr %first.addr, align 1
  %icmp = icmp eq i8 %load, 32
  br i1 %icmp, label %for.inc, label %return.early

for.inc:
  %first.next = getelementptr inbounds nuw i8, ptr %first.addr, i64 1
  %icmp6 = icmp ugt ptr %first.next, %last
  br i1 %icmp6, label %return, label %for.body, !llvm.loop !0

return.early:
  ret i1 true

return:
  ret i1 false
}
!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.mustprogress"}

; uncountable loop with two distinct exit blocks
define i64 @ham(ptr %arg, i64 %arg1, i32 %arg2, ptr %arg3, i32 %arg4) {
; CHECK-LABEL: @ham(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[GETELEMENTPTR6:%.*]] = getelementptr i8, ptr null, i64 -4
; CHECK-NEXT:    br label [[BB10:%.*]]
; CHECK:       bb10.loopexit:
; CHECK-NEXT:    br label [[BB10]]
; CHECK:       bb10:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[ARG:%.*]], [[BB:%.*]] ], [ null, [[BB10_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[PHI1:%.*]] = ptrtoint ptr [[PHI]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[PHI1]], 1
; CHECK-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP0]], i64 -4)
; CHECK-NEXT:    [[TMP1:%.*]] = sub i64 [[UMAX]], [[PHI1]]
; CHECK-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[BB13:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[BB13]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[BB13]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP1]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP9]], i32 8, i1 true)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[PHI]], i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[TMP11]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i8>, i32 } @llvm.vp.load.ff.nxv8i8.p0(ptr align 1 [[TMP12]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP10]])
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <vscale x 8 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <vscale x 8 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 8 x i8> @llvm.vp.and.nxv8i8(<vscale x 8 x i8> [[TMP15]], <vscale x 8 x i8> splat (i8 -2), <vscale x 8 x i1> splat (i1 true), i32 [[TMP13]])
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i8(<vscale x 8 x i8> [[VP_OP]], <vscale x 8 x i8> splat (i8 -24), metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP13]])
; CHECK-NEXT:    [[TMP22:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP13]])
; CHECK-NEXT:    [[TMP17:%.*]] = icmp sge i32 [[TMP22]], 0
; CHECK-NEXT:    [[TMP16:%.*]] = zext i32 [[TMP13]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP16]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP1]]
; CHECK-NEXT:    [[TMP21:%.*]] = or i1 [[TMP17]], [[TMP18]]
; CHECK-NEXT:    br i1 [[TMP21]], label [[MIDDLE_SPLIT:%.*]], label [[BB13]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       middle.split:
; CHECK-NEXT:    br i1 [[TMP17]], label [[VECTOR_EARLY_EXIT:%.*]], label [[MIDDLE_BLOCK:%.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[BB109:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    br label [[BB10_LOOPEXIT]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[PHI]], [[BB10]] ]
; CHECK-NEXT:    br label [[BB14:%.*]]
; CHECK:       bb13:
; CHECK-NEXT:    [[PHI14:%.*]] = phi ptr [ [[BC_RESUME_VAL]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[GETELEMENTPTR19:%.*]], [[BB18:%.*]] ]
; CHECK-NEXT:    [[LOAD15:%.*]] = load i8, ptr [[PHI14]], align 1
; CHECK-NEXT:    [[AND16:%.*]] = and i8 [[LOAD15]], -2
; CHECK-NEXT:    [[ICMP17:%.*]] = icmp eq i8 [[AND16]], -24
; CHECK-NEXT:    br i1 [[ICMP17]], label [[BB10_LOOPEXIT]], label [[BB18]]
; CHECK:       bb18:
; CHECK-NEXT:    [[GETELEMENTPTR19]] = getelementptr i8, ptr [[PHI14]], i64 1
; CHECK-NEXT:    [[ICMP20:%.*]] = icmp ult ptr [[GETELEMENTPTR19]], [[GETELEMENTPTR6]]
; CHECK-NEXT:    br i1 [[ICMP20]], label [[BB14]], label [[BB109]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       bb109:
; CHECK-NEXT:    ret i64 0
;
; P470-LABEL: @ham(
; P470-NEXT:  bb:
; P470-NEXT:    [[GETELEMENTPTR6:%.*]] = getelementptr i8, ptr null, i64 -4
; P470-NEXT:    br label [[BB10:%.*]]
; P470:       bb10.loopexit:
; P470-NEXT:    br label [[BB10]]
; P470:       bb10:
; P470-NEXT:    [[PHI:%.*]] = phi ptr [ [[ARG:%.*]], [[BB:%.*]] ], [ null, [[BB10_LOOPEXIT:%.*]] ]
; P470-NEXT:    [[PHI1:%.*]] = ptrtoint ptr [[PHI]] to i64
; P470-NEXT:    [[TMP0:%.*]] = add i64 [[PHI1]], 1
; P470-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP0]], i64 -4)
; P470-NEXT:    [[TMP1:%.*]] = sub i64 [[UMAX]], [[PHI1]]
; P470-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; P470:       vector.ph:
; P470-NEXT:    br label [[BB13:%.*]]
; P470:       vector.body:
; P470-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[BB13]] ]
; P470-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[BB13]] ]
; P470-NEXT:    [[AVL:%.*]] = sub i64 [[TMP1]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP9:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; P470-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP9]], i32 32, i1 true)
; P470-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[PHI]], i64 [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[TMP11]], i32 0
; P470-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP12]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP3]])
; P470-NEXT:    [[TMP13:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; P470-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; P470-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.and.nxv32i8(<vscale x 32 x i8> [[TMP6]], <vscale x 32 x i8> splat (i8 -2), <vscale x 32 x i1> splat (i1 true), i32 [[TMP13]])
; P470-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 -24), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP13]])
; P470-NEXT:    [[TMP22:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP13]])
; P470-NEXT:    [[TMP17:%.*]] = icmp sge i32 [[TMP22]], 0
; P470-NEXT:    [[TMP16:%.*]] = zext i32 [[TMP13]] to i64
; P470-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP16]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP1]]
; P470-NEXT:    [[TMP21:%.*]] = or i1 [[TMP17]], [[TMP18]]
; P470-NEXT:    br i1 [[TMP21]], label [[MIDDLE_SPLIT:%.*]], label [[BB13]], !llvm.loop [[LOOP7:![0-9]+]]
; P470:       middle.split:
; P470-NEXT:    br i1 [[TMP17]], label [[VECTOR_EARLY_EXIT:%.*]], label [[MIDDLE_BLOCK:%.*]]
; P470:       middle.block:
; P470-NEXT:    br label [[BB109:%.*]]
; P470:       vector.early.exit:
; P470-NEXT:    br label [[BB10_LOOPEXIT]]
; P470:       scalar.ph:
; P470-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[PHI]], [[BB10]] ]
; P470-NEXT:    br label [[BB14:%.*]]
; P470:       bb13:
; P470-NEXT:    [[PHI14:%.*]] = phi ptr [ [[BC_RESUME_VAL]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[GETELEMENTPTR19:%.*]], [[BB18:%.*]] ]
; P470-NEXT:    [[LOAD15:%.*]] = load i8, ptr [[PHI14]], align 1
; P470-NEXT:    [[AND16:%.*]] = and i8 [[LOAD15]], -2
; P470-NEXT:    [[ICMP17:%.*]] = icmp eq i8 [[AND16]], -24
; P470-NEXT:    br i1 [[ICMP17]], label [[BB10_LOOPEXIT]], label [[BB18]]
; P470:       bb18:
; P470-NEXT:    [[GETELEMENTPTR19]] = getelementptr i8, ptr [[PHI14]], i64 1
; P470-NEXT:    [[ICMP20:%.*]] = icmp ult ptr [[GETELEMENTPTR19]], [[GETELEMENTPTR6]]
; P470-NEXT:    br i1 [[ICMP20]], label [[BB14]], label [[BB109]], !llvm.loop [[LOOP8:![0-9]+]]
; P470:       bb109:
; P470-NEXT:    ret i64 0
;
bb:
  %getelementptr6 = getelementptr i8, ptr null, i64 -4
  br label %bb10

bb10:                                             ; preds = %bb13, %bb
  %phi = phi ptr [ %arg, %bb ], [ null, %bb13 ]
  br label %bb13

bb13:                                             ; preds = %bb18, %bb10
  %phi14 = phi ptr [ %phi, %bb10 ], [ %getelementptr19, %bb18 ]
  %load15 = load i8, ptr %phi14, align 1
  %and16 = and i8 %load15, -2
  %icmp17 = icmp eq i8 %and16, -24
  br i1 %icmp17, label %bb10, label %bb18

bb18:                                             ; preds = %bb13
  %getelementptr19 = getelementptr i8, ptr %phi14, i64 1
  %icmp20 = icmp ult ptr %getelementptr19, %getelementptr6
  br i1 %icmp20, label %bb13, label %bb109

bb109:                                            ; preds = %bb18
  ret i64 0
}


; support non-ptr-iv
define ptr @find_with_int_iv(ptr %first, ptr %last, i64 %count) {
; CHECK-LABEL: @find_with_int_iv(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[COUNT:%.*]], 1
; CHECK-NEXT:    [[SMIN:%.*]] = call i64 @llvm.smin.i64(i64 [[COUNT]], i64 1)
; CHECK-NEXT:    [[TMP1:%.*]] = sub i64 [[TMP0]], [[SMIN]]
; CHECK-NEXT:    br i1 false, label [[ENTRY:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 1 x ptr> poison, ptr [[LAST:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 1 x ptr> [[BROADCAST_SPLATINSERT]], <vscale x 1 x ptr> poison, <vscale x 1 x i32> zeroinitializer
; CHECK-NEXT:    br label [[FOR_BODY1:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP1]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP5:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP5]], i32 1, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 8
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[FIRST:%.*]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr ptr, ptr [[NEXT_GEP]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 1 x ptr>, i32 } @llvm.vp.load.ff.nxv1p0.p0(ptr align 8 [[TMP8]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 1 x ptr>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 1 x ptr>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 1 x i1> @llvm.vp.icmp.nxv1p0(<vscale x 1 x ptr> [[TMP10]], <vscale x 1 x ptr> [[BROADCAST_SPLAT]], metadata !"eq", <vscale x 1 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[TMP18:%.*]] = call i32 @llvm.vp.first.nxv1i1(<vscale x 1 x i1> [[VP_OP_ICMP]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[TMP12:%.*]] = icmp sge i32 [[TMP18]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP9]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP11]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP1]]
; CHECK-NEXT:    [[TMP13:%.*]] = or i1 [[TMP12]], [[TMP14]]
; CHECK-NEXT:    br i1 [[TMP13]], label [[MIDDLE_SPLIT:%.*]], label [[FOR_BODY1]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       middle.split:
; CHECK-NEXT:    br i1 [[TMP12]], label [[VECTOR_EARLY_EXIT:%.*]], label [[MIDDLE_BLOCK:%.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP18]] to i64
; CHECK-NEXT:    [[TMP16:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP15]]
; CHECK-NEXT:    [[TMP17:%.*]] = mul i64 [[TMP16]], 8
; CHECK-NEXT:    [[IND_EARLY_ESCAPE:%.*]] = getelementptr i8, ptr [[FIRST]], i64 [[TMP17]]
; CHECK-NEXT:    br label [[RETURN_EARLY:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[COUNT]], [[ENTRY1:%.*]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi ptr [ [[FIRST]], [[ENTRY1]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[REMAIN:%.*]] = phi i64 [ [[REMAIN_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[BC_RESUME_VAL]], [[ENTRY]] ]
; CHECK-NEXT:    [[ADDR:%.*]] = phi ptr [ [[ADDR_NEXT:%.*]], [[FOR_INC]] ], [ [[BC_RESUME_VAL2]], [[ENTRY]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[ADDR]], align 8
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq ptr [[LOAD]], [[LAST]]
; CHECK-NEXT:    br i1 [[ICMP]], label [[RETURN_EARLY]], label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[ADDR_NEXT]] = getelementptr inbounds nuw ptr, ptr [[ADDR]], i64 1
; CHECK-NEXT:    [[REMAIN_NEXT]] = add nsw i64 [[REMAIN]], -1
; CHECK-NEXT:    [[ICMP2:%.*]] = icmp sgt i64 [[REMAIN]], 1
; CHECK-NEXT:    br i1 [[ICMP2]], label [[FOR_BODY]], label [[RETURN]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       return.early:
; CHECK-NEXT:    [[RET:%.*]] = phi ptr [ [[ADDR]], [[FOR_BODY]] ], [ [[IND_EARLY_ESCAPE]], [[VECTOR_EARLY_EXIT]] ]
; CHECK-NEXT:    ret ptr [[RET]]
; CHECK:       return:
; CHECK-NEXT:    ret ptr [[LAST]]
;
; P470-LABEL: @find_with_int_iv(
; P470-NEXT:  entry:
; P470-NEXT:    [[TMP0:%.*]] = add i64 [[COUNT:%.*]], 1
; P470-NEXT:    [[SMIN:%.*]] = call i64 @llvm.smin.i64(i64 [[COUNT]], i64 1)
; P470-NEXT:    [[TMP1:%.*]] = sub i64 [[TMP0]], [[SMIN]]
; P470-NEXT:    br i1 false, label [[ENTRY:%.*]], label [[VECTOR_PH:%.*]]
; P470:       vector.ph:
; P470-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x ptr> poison, ptr [[LAST:%.*]], i64 0
; P470-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x ptr> [[BROADCAST_SPLATINSERT]], <vscale x 4 x ptr> poison, <vscale x 4 x i32> zeroinitializer
; P470-NEXT:    br label [[FOR_BODY1:%.*]]
; P470:       vector.body:
; P470-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_BODY1]] ]
; P470-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[FOR_BODY1]] ]
; P470-NEXT:    [[AVL:%.*]] = sub i64 [[TMP1]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP5:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; P470-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP5]], i32 4, i1 true)
; P470-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 8
; P470-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[FIRST:%.*]], i64 [[OFFSET_IDX]]
; P470-NEXT:    [[TMP8:%.*]] = getelementptr ptr, ptr [[NEXT_GEP]], i32 0
; P470-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 4 x ptr>, i32 } @llvm.vp.load.ff.nxv4p0.p0(ptr align 8 [[TMP8]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP6]])
; P470-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 4 x ptr>, i32 } [[VP_OP_LOAD_FF]], 1
; P470-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 4 x ptr>, i32 } [[VP_OP_LOAD_FF]], 0
; P470-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4p0(<vscale x 4 x ptr> [[TMP10]], <vscale x 4 x ptr> [[BROADCAST_SPLAT]], metadata !"eq", <vscale x 4 x i1> splat (i1 true), i32 [[TMP9]])
; P470-NEXT:    [[TMP18:%.*]] = call i32 @llvm.vp.first.nxv4i1(<vscale x 4 x i1> [[VP_OP_ICMP]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP9]])
; P470-NEXT:    [[TMP12:%.*]] = icmp sge i32 [[TMP18]], 0
; P470-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP9]] to i64
; P470-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP11]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP1]]
; P470-NEXT:    [[TMP13:%.*]] = or i1 [[TMP12]], [[TMP14]]
; P470-NEXT:    br i1 [[TMP13]], label [[MIDDLE_SPLIT:%.*]], label [[FOR_BODY1]], !llvm.loop [[LOOP9:![0-9]+]]
; P470:       middle.split:
; P470-NEXT:    br i1 [[TMP12]], label [[VECTOR_EARLY_EXIT:%.*]], label [[MIDDLE_BLOCK:%.*]]
; P470:       middle.block:
; P470-NEXT:    br label [[RETURN:%.*]]
; P470:       vector.early.exit:
; P470-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP18]] to i64
; P470-NEXT:    [[TMP16:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP15]]
; P470-NEXT:    [[TMP17:%.*]] = mul i64 [[TMP16]], 8
; P470-NEXT:    [[IND_EARLY_ESCAPE:%.*]] = getelementptr i8, ptr [[FIRST]], i64 [[TMP17]]
; P470-NEXT:    br label [[RETURN_EARLY:%.*]]
; P470:       scalar.ph:
; P470-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[COUNT]], [[ENTRY1:%.*]] ]
; P470-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi ptr [ [[FIRST]], [[ENTRY1]] ]
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[REMAIN:%.*]] = phi i64 [ [[REMAIN_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[BC_RESUME_VAL]], [[ENTRY]] ]
; P470-NEXT:    [[ADDR:%.*]] = phi ptr [ [[ADDR_NEXT:%.*]], [[FOR_INC]] ], [ [[BC_RESUME_VAL2]], [[ENTRY]] ]
; P470-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[ADDR]], align 8
; P470-NEXT:    [[ICMP:%.*]] = icmp eq ptr [[LOAD]], [[LAST]]
; P470-NEXT:    br i1 [[ICMP]], label [[RETURN_EARLY]], label [[FOR_INC]]
; P470:       for.inc:
; P470-NEXT:    [[ADDR_NEXT]] = getelementptr inbounds nuw ptr, ptr [[ADDR]], i64 1
; P470-NEXT:    [[REMAIN_NEXT]] = add nsw i64 [[REMAIN]], -1
; P470-NEXT:    [[ICMP2:%.*]] = icmp sgt i64 [[REMAIN]], 1
; P470-NEXT:    br i1 [[ICMP2]], label [[FOR_BODY]], label [[RETURN]], !llvm.loop [[LOOP10:![0-9]+]]
; P470:       return.early:
; P470-NEXT:    [[RET:%.*]] = phi ptr [ [[ADDR]], [[FOR_BODY]] ], [ [[IND_EARLY_ESCAPE]], [[VECTOR_EARLY_EXIT]] ]
; P470-NEXT:    ret ptr [[RET]]
; P470:       return:
; P470-NEXT:    ret ptr [[LAST]]
;
entry:
  br label %for.body
for.body:
  %remain = phi i64 [ %remain.next, %for.inc ], [ %count, %entry ]
  %addr = phi ptr [ %addr.next, %for.inc ], [ %first, %entry ]
  %load = load ptr, ptr %addr, align 8
  %icmp = icmp eq ptr %load, %last
  br i1 %icmp, label %return.early, label %for.inc

for.inc:
  %addr.next = getelementptr inbounds nuw ptr, ptr %addr, i64 1
  %remain.next = add nsw i64 %remain, -1
  %icmp2 = icmp sgt i64 %remain, 1
  br i1 %icmp2, label %for.body, label %return

return.early:
  %ret = phi ptr [ %addr, %for.body ]
  ret ptr %ret

return:
  ret ptr %last
}

; no live-out user
define i32 @find_no_liveout(ptr %p) {
; CHECK-LABEL: @find_no_liveout(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 60, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i32, ptr [[P:%.*]], i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP2]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 2 x i32>, i32 } @llvm.vp.load.ff.nxv2i32.p0(ptr align 4 [[TMP3]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 2 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <vscale x 2 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i32(<vscale x 2 x i32> [[TMP5]], <vscale x 2 x i32> splat (i32 62), metadata !"ne", <vscale x 2 x i1> splat (i1 true), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vp.first.nxv2i1(<vscale x 2 x i1> [[PRED_NOT]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP8:%.*]] = icmp sge i32 [[TMP7]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP4]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP12]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 60
; CHECK-NEXT:    [[TMP10:%.*]] = or i1 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[MIDDLE_SPLIT:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       middle.split:
; CHECK-NEXT:    br i1 [[TMP8]], label [[VECTOR_EARLY_EXIT:%.*]], label [[MIDDLE_BLOCK:%.*]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[CLEANUP:%.*]]
; CHECK:       vector.early.exit:
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND:%.*]] ]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i32, ptr [[P]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ADD_PTR]], align 4
; CHECK-NEXT:    [[CMP1_NOT:%.*]] = icmp eq i32 [[TMP11]], 62
; CHECK-NEXT:    br i1 [[CMP1_NOT]], label [[FOR_COND]], label [[CLEANUP]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 60
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       cleanup:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[FOR_BODY]] ], [ 1, [[FOR_COND]] ], [ 1, [[MIDDLE_BLOCK]] ], [ 0, [[VECTOR_EARLY_EXIT]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
; P470-LABEL: @find_no_liveout(
; P470-NEXT:  entry:
; P470-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; P470:       vector.ph:
; P470-NEXT:    br label [[VECTOR_BODY:%.*]]
; P470:       vector.body:
; P470-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; P470-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; P470-NEXT:    [[AVL:%.*]] = sub i64 60, [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP0:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; P470-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 8, i1 true)
; P470-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw i32, ptr [[P:%.*]], i64 [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP2]], i32 0
; P470-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP3]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP1]])
; P470-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; P470-NEXT:    [[TMP5:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; P470-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP5]], <vscale x 8 x i32> splat (i32 62), metadata !"ne", <vscale x 8 x i1> splat (i1 true), i32 [[TMP4]])
; P470-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[PRED_NOT]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP4]])
; P470-NEXT:    [[TMP8:%.*]] = icmp sge i32 [[TMP7]], 0
; P470-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP4]] to i64
; P470-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP12]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 60
; P470-NEXT:    [[TMP10:%.*]] = or i1 [[TMP8]], [[TMP9]]
; P470-NEXT:    br i1 [[TMP10]], label [[MIDDLE_SPLIT:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
; P470:       middle.split:
; P470-NEXT:    br i1 [[TMP8]], label [[VECTOR_EARLY_EXIT:%.*]], label [[MIDDLE_BLOCK:%.*]]
; P470:       middle.block:
; P470-NEXT:    br label [[CLEANUP:%.*]]
; P470:       vector.early.exit:
; P470-NEXT:    br label [[CLEANUP]]
; P470:       scalar.ph:
; P470-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND:%.*]] ]
; P470-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i32, ptr [[P]], i64 [[INDVARS_IV]]
; P470-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ADD_PTR]], align 4
; P470-NEXT:    [[CMP1_NOT:%.*]] = icmp eq i32 [[TMP11]], 62
; P470-NEXT:    br i1 [[CMP1_NOT]], label [[FOR_COND]], label [[CLEANUP]]
; P470:       for.cond:
; P470-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; P470-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 60
; P470-NEXT:    br i1 [[EXITCOND_NOT]], label [[CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; P470:       cleanup:
; P470-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[FOR_BODY]] ], [ 1, [[FOR_COND]] ], [ 1, [[MIDDLE_BLOCK]] ], [ 0, [[VECTOR_EARLY_EXIT]] ]
; P470-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  br label %for.body

for.body:
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.cond ]
  %add.ptr = getelementptr inbounds nuw i32, ptr %p, i64 %indvars.iv
  %0 = load i32, ptr %add.ptr, align 4
  %cmp1.not = icmp eq i32 %0, 62
  br i1 %cmp1.not, label %for.cond, label %cleanup

for.cond:
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 60
  br i1 %exitcond.not, label %cleanup, label %for.body

cleanup:
  %retval.0 = phi i32 [ 0, %for.body ], [ 1, %for.cond ]
  ret i32 %retval.0
}
