; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=stress < %s | FileCheck %s
; RUN: opt -S -passes=loop-vectorize -mtriple=riscv64 -mcpu=sifive-p470 < %s | FileCheck %s --check-prefix=P470

; int* my_find(int* first, int* last, const int& value) {
;   for (; first != last; ++first) {
;     if (*first == value) {
;       return first;
;     }
;   }
;   return last;
; }

define ptr @find(ptr %first, ptr %last, ptr %value) {
; CHECK-LABEL: @find(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT6:%.*]] = icmp eq ptr [[FIRST:%.*]], [[LAST:%.*]]
; CHECK-NEXT:    br i1 [[CMP_NOT6]], label [[RETURN:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[FIRST]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[FIRST_ADDR_07]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP33]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY]]
; CHECK:       return.loopexit:
; CHECK-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY]] ], [ [[LAST]], [[FOR_INC]] ]
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ [[FIRST]], [[ENTRY:%.*]] ], [ [[RETVAL_0_PH]], [[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret ptr [[RETVAL_0]]
;
; P470-LABEL: @find(
; P470-NEXT:  entry:
; P470-NEXT:    [[CMP_NOT6:%.*]] = icmp eq ptr [[FIRST:%.*]], [[LAST:%.*]]
; P470-NEXT:    br i1 [[CMP_NOT6]], label [[RETURN:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; P470:       for.body.lr.ph:
; P470-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[FIRST]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC:%.*]] ]
; P470-NEXT:    [[TMP33:%.*]] = load i32, ptr [[FIRST_ADDR_07]], align 4
; P470-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP33]], [[TMP0]]
; P470-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_INC]]
; P470:       for.inc:
; P470-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; P470-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST]]
; P470-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY]]
; P470:       return.loopexit:
; P470-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY]] ], [ [[LAST]], [[FOR_INC]] ]
; P470-NEXT:    br label [[RETURN]]
; P470:       return:
; P470-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ [[FIRST]], [[ENTRY:%.*]] ], [ [[RETVAL_0_PH]], [[RETURN_LOOPEXIT]] ]
; P470-NEXT:    ret ptr [[RETVAL_0]]
;
entry:
  %cmp.not6 = icmp eq ptr %first, %last
  br i1 %cmp.not6, label %return, label %for.body.lr.ph

for.body.lr.ph:
  %0 = load i32, ptr %value, align 4
  br label %for.body

for.body:
  %first.addr.07 = phi ptr [ %first, %for.body.lr.ph ], [ %incdec.ptr, %for.inc ]
  %1 = load i32, ptr %first.addr.07, align 4
  %cmp1 = icmp eq i32 %1, %0
  br i1 %cmp1, label %return.loopexit, label %for.inc

for.inc:
  %incdec.ptr = getelementptr inbounds i32, ptr %first.addr.07, i64 1
  %cmp.not = icmp eq ptr %incdec.ptr, %last
  br i1 %cmp.not, label %return.loopexit, label %for.body

return.loopexit:
  %retval.0.ph = phi ptr [ %first.addr.07, %for.body ], [ %last, %for.inc ]
  br label %return

return:
  %retval.0 = phi ptr [ %first, %entry ], [ %retval.0.ph, %return.loopexit ]
  ret ptr %retval.0
}

; Support speculative exiting condition at the latch block
define ptr @find2(ptr %first, ptr %last, ptr %value) {
; CHECK-LABEL: @find2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[FIRST:%.*]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_BODY2:%.*]] ]
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST:%.*]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_BODY2]]
; CHECK:       for.body2:
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[INCDEC_PTR]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY]]
; CHECK:       return.loopexit:
; CHECK-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY2]] ], [ [[LAST]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       return:
; CHECK-NEXT:    ret ptr [[RETVAL_0_PH]]
;
; P470-LABEL: @find2(
; P470-NEXT:  entry:
; P470-NEXT:    br label [[FOR_BODY_LR_PH:%.*]]
; P470:       for.body.lr.ph:
; P470-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE:%.*]], align 4
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[FIRST_ADDR_07:%.*]] = phi ptr [ [[FIRST:%.*]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_BODY2:%.*]] ]
; P470-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[FIRST_ADDR_07]], i64 1
; P470-NEXT:    [[CMP_NOT:%.*]] = icmp eq ptr [[INCDEC_PTR]], [[LAST:%.*]]
; P470-NEXT:    br i1 [[CMP_NOT]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_BODY2]]
; P470:       for.body2:
; P470-NEXT:    [[TMP1:%.*]] = load i32, ptr [[INCDEC_PTR]], align 4
; P470-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], [[TMP0]]
; P470-NEXT:    br i1 [[CMP1]], label [[RETURN_LOOPEXIT]], label [[FOR_BODY]]
; P470:       return.loopexit:
; P470-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[FIRST_ADDR_07]], [[FOR_BODY2]] ], [ [[LAST]], [[FOR_BODY]] ]
; P470-NEXT:    br label [[RETURN:%.*]]
; P470:       return:
; P470-NEXT:    ret ptr [[RETVAL_0_PH]]
;
entry:
  br label %for.body.lr.ph

for.body.lr.ph:
  %0 = load i32, ptr %value, align 4
  br label %for.body

for.body:
  %first.addr.07 = phi ptr [ %first, %for.body.lr.ph ], [ %incdec.ptr, %for.body2 ]
  %incdec.ptr = getelementptr inbounds i32, ptr %first.addr.07, i64 1
  %cmp.not = icmp eq ptr %incdec.ptr, %last
  br i1 %cmp.not, label %return.loopexit, label %for.body2

for.body2:
  %1 = load i32, ptr %incdec.ptr, align 4
  %cmp1 = icmp eq i32 %1, %0
  br i1 %cmp1, label %return.loopexit, label %for.body

return.loopexit:
  %retval.0.ph = phi ptr [ %first.addr.07, %for.body2 ], [ %last, %for.body ]
  br label %return

return:
  ret ptr %retval.0.ph
}

; This is not vectorized because ICMP_ULE needs a wider type to avoid overflow
define i1 @find3(ptr %first, ptr %last) {
; CHECK-LABEL: @find3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[FIRST_ADDR:%.*]] = phi ptr [ [[FIRST_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[FIRST:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, ptr [[FIRST_ADDR]], align 1
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i8 [[LOAD]], 32
; CHECK-NEXT:    br i1 [[ICMP]], label [[FOR_INC]], label [[RETURN_EARLY:%.*]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[FIRST_NEXT]] = getelementptr inbounds nuw i8, ptr [[FIRST_ADDR]], i64 1
; CHECK-NEXT:    [[ICMP6:%.*]] = icmp ugt ptr [[FIRST_NEXT]], [[LAST:%.*]]
; CHECK-NEXT:    br i1 [[ICMP6]], label [[RETURN:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       return.early:
; CHECK-NEXT:    ret i1 true
; CHECK:       return:
; CHECK-NEXT:    ret i1 false
;
; P470-LABEL: @find3(
; P470-NEXT:  entry:
; P470-NEXT:    br label [[FOR_BODY:%.*]]
; P470:       for.body:
; P470-NEXT:    [[FIRST_ADDR:%.*]] = phi ptr [ [[FIRST_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[FIRST:%.*]], [[ENTRY:%.*]] ]
; P470-NEXT:    [[LOAD:%.*]] = load i8, ptr [[FIRST_ADDR]], align 1
; P470-NEXT:    [[ICMP:%.*]] = icmp eq i8 [[LOAD]], 32
; P470-NEXT:    br i1 [[ICMP]], label [[FOR_INC]], label [[RETURN_EARLY:%.*]]
; P470:       for.inc:
; P470-NEXT:    [[FIRST_NEXT]] = getelementptr inbounds nuw i8, ptr [[FIRST_ADDR]], i64 1
; P470-NEXT:    [[ICMP6:%.*]] = icmp ugt ptr [[FIRST_NEXT]], [[LAST:%.*]]
; P470-NEXT:    br i1 [[ICMP6]], label [[RETURN:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; P470:       return.early:
; P470-NEXT:    ret i1 true
; P470:       return:
; P470-NEXT:    ret i1 false
;
entry:
  br label %for.body

for.body:
  %first.addr = phi ptr [ %first.next, %for.inc ], [ %first, %entry ]
  %load = load i8, ptr %first.addr, align 1
  %icmp = icmp eq i8 %load, 32
  br i1 %icmp, label %for.inc, label %return.early

for.inc:
  %first.next = getelementptr inbounds nuw i8, ptr %first.addr, i64 1
  %icmp6 = icmp ugt ptr %first.next, %last
  br i1 %icmp6, label %return, label %for.body, !llvm.loop !0

return.early:
  ret i1 true

return:
  ret i1 false
}
!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.mustprogress"}

; uncountable loop with two distinct exit blocks
define i64 @ham(ptr %arg, i64 %arg1, i32 %arg2, ptr %arg3, i32 %arg4) {
; CHECK-LABEL: @ham(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[GETELEMENTPTR6:%.*]] = getelementptr i8, ptr null, i64 -4
; CHECK-NEXT:    br label [[BB10:%.*]]
; CHECK:       bb10.loopexit:
; CHECK-NEXT:    br label [[BB10]]
; CHECK:       bb10:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[ARG:%.*]], [[BB:%.*]] ], [ null, [[BB10_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    br label [[BB13:%.*]]
; CHECK:       bb13:
; CHECK-NEXT:    [[PHI14:%.*]] = phi ptr [ [[PHI]], [[BB10]] ], [ [[GETELEMENTPTR19:%.*]], [[BB18:%.*]] ]
; CHECK-NEXT:    [[LOAD15:%.*]] = load i8, ptr [[PHI14]], align 1
; CHECK-NEXT:    [[AND16:%.*]] = and i8 [[LOAD15]], -2
; CHECK-NEXT:    [[ICMP17:%.*]] = icmp eq i8 [[AND16]], -24
; CHECK-NEXT:    br i1 [[ICMP17]], label [[BB10_LOOPEXIT]], label [[BB18]]
; CHECK:       bb18:
; CHECK-NEXT:    [[GETELEMENTPTR19]] = getelementptr i8, ptr [[PHI14]], i64 1
; CHECK-NEXT:    [[ICMP20:%.*]] = icmp ult ptr [[GETELEMENTPTR19]], [[GETELEMENTPTR6]]
; CHECK-NEXT:    br i1 [[ICMP20]], label [[BB13]], label [[BB109:%.*]]
; CHECK:       bb109:
; CHECK-NEXT:    ret i64 0
;
; P470-LABEL: @ham(
; P470-NEXT:  bb:
; P470-NEXT:    [[GETELEMENTPTR6:%.*]] = getelementptr i8, ptr null, i64 -4
; P470-NEXT:    br label [[BB10:%.*]]
; P470:       bb10.loopexit:
; P470-NEXT:    br label [[BB10]]
; P470:       bb10:
; P470-NEXT:    [[PHI:%.*]] = phi ptr [ [[ARG:%.*]], [[BB:%.*]] ], [ null, [[BB10_LOOPEXIT:%.*]] ]
; P470-NEXT:    br label [[BB13:%.*]]
; P470:       bb13:
; P470-NEXT:    [[PHI14:%.*]] = phi ptr [ [[PHI]], [[BB10]] ], [ [[GETELEMENTPTR19:%.*]], [[BB18:%.*]] ]
; P470-NEXT:    [[LOAD15:%.*]] = load i8, ptr [[PHI14]], align 1
; P470-NEXT:    [[AND16:%.*]] = and i8 [[LOAD15]], -2
; P470-NEXT:    [[ICMP17:%.*]] = icmp eq i8 [[AND16]], -24
; P470-NEXT:    br i1 [[ICMP17]], label [[BB10_LOOPEXIT]], label [[BB18]]
; P470:       bb18:
; P470-NEXT:    [[GETELEMENTPTR19]] = getelementptr i8, ptr [[PHI14]], i64 1
; P470-NEXT:    [[ICMP20:%.*]] = icmp ult ptr [[GETELEMENTPTR19]], [[GETELEMENTPTR6]]
; P470-NEXT:    br i1 [[ICMP20]], label [[BB13]], label [[BB109:%.*]]
; P470:       bb109:
; P470-NEXT:    ret i64 0
;
bb:
  %getelementptr6 = getelementptr i8, ptr null, i64 -4
  br label %bb10

bb10:                                             ; preds = %bb13, %bb
  %phi = phi ptr [ %arg, %bb ], [ null, %bb13 ]
  br label %bb13

bb13:                                             ; preds = %bb18, %bb10
  %phi14 = phi ptr [ %phi, %bb10 ], [ %getelementptr19, %bb18 ]
  %load15 = load i8, ptr %phi14, align 1
  %and16 = and i8 %load15, -2
  %icmp17 = icmp eq i8 %and16, -24
  br i1 %icmp17, label %bb10, label %bb18

bb18:                                             ; preds = %bb13
  %getelementptr19 = getelementptr i8, ptr %phi14, i64 1
  %icmp20 = icmp ult ptr %getelementptr19, %getelementptr6
  br i1 %icmp20, label %bb13, label %bb109

bb109:                                            ; preds = %bb18
  ret i64 0
}


; support non-ptr-iv
define ptr @find_with_int_iv(ptr %first, ptr %last, i64 %count) {
; CHECK-LABEL: @find_with_int_iv(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY1:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[REMAIN:%.*]] = phi i64 [ [[REMAIN_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[BC_RESUME_VAL:%.*]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[ADDR:%.*]] = phi ptr [ [[ADDR_NEXT:%.*]], [[FOR_INC]] ], [ [[BC_RESUME_VAL2:%.*]], [[ENTRY]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[ADDR]], align 8
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq ptr [[LOAD]], [[LAST:%.*]]
; CHECK-NEXT:    br i1 [[ICMP]], label [[RETURN_EARLY:%.*]], label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[ADDR_NEXT]] = getelementptr inbounds nuw ptr, ptr [[ADDR]], i64 1
; CHECK-NEXT:    [[REMAIN_NEXT]] = add nsw i64 [[REMAIN]], -1
; CHECK-NEXT:    [[ICMP2:%.*]] = icmp sgt i64 [[REMAIN]], 1
; CHECK-NEXT:    br i1 [[ICMP2]], label [[FOR_BODY1]], label [[RETURN:%.*]]
; CHECK:       return.early:
; CHECK-NEXT:    [[RET:%.*]] = phi ptr [ [[ADDR]], [[FOR_BODY1]] ]
; CHECK-NEXT:    ret ptr [[RET]]
; CHECK:       return:
; CHECK-NEXT:    ret ptr [[LAST]]
;
; P470-LABEL: @find_with_int_iv(
; P470-NEXT:  entry:
; P470-NEXT:    br label [[FOR_BODY1:%.*]]
; P470:       for.body:
; P470-NEXT:    [[REMAIN:%.*]] = phi i64 [ [[REMAIN_NEXT:%.*]], [[FOR_INC:%.*]] ], [ [[BC_RESUME_VAL:%.*]], [[ENTRY:%.*]] ]
; P470-NEXT:    [[ADDR:%.*]] = phi ptr [ [[ADDR_NEXT:%.*]], [[FOR_INC]] ], [ [[BC_RESUME_VAL2:%.*]], [[ENTRY]] ]
; P470-NEXT:    [[LOAD:%.*]] = load ptr, ptr [[ADDR]], align 8
; P470-NEXT:    [[ICMP:%.*]] = icmp eq ptr [[LOAD]], [[LAST:%.*]]
; P470-NEXT:    br i1 [[ICMP]], label [[RETURN_EARLY:%.*]], label [[FOR_INC]]
; P470:       for.inc:
; P470-NEXT:    [[ADDR_NEXT]] = getelementptr inbounds nuw ptr, ptr [[ADDR]], i64 1
; P470-NEXT:    [[REMAIN_NEXT]] = add nsw i64 [[REMAIN]], -1
; P470-NEXT:    [[ICMP2:%.*]] = icmp sgt i64 [[REMAIN]], 1
; P470-NEXT:    br i1 [[ICMP2]], label [[FOR_BODY1]], label [[RETURN:%.*]]
; P470:       return.early:
; P470-NEXT:    [[RET:%.*]] = phi ptr [ [[ADDR]], [[FOR_BODY1]] ]
; P470-NEXT:    ret ptr [[RET]]
; P470:       return:
; P470-NEXT:    ret ptr [[LAST]]
;
entry:
  br label %for.body
for.body:
  %remain = phi i64 [ %remain.next, %for.inc ], [ %count, %entry ]
  %addr = phi ptr [ %addr.next, %for.inc ], [ %first, %entry ]
  %load = load ptr, ptr %addr, align 8
  %icmp = icmp eq ptr %load, %last
  br i1 %icmp, label %return.early, label %for.inc

for.inc:
  %addr.next = getelementptr inbounds nuw ptr, ptr %addr, i64 1
  %remain.next = add nsw i64 %remain, -1
  %icmp2 = icmp sgt i64 %remain, 1
  br i1 %icmp2, label %for.body, label %return

return.early:
  %ret = phi ptr [ %addr, %for.body ]
  ret ptr %ret

return:
  ret ptr %last
}
