; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=on < %s | FileCheck %s

; #include <stdio.h>
; #include <string.h>

; void *my_memchr(const void *ptr, int c, size_t n) {
;     const unsigned char *p = ptr;
;     while (n-- > 0) {
;         if (*p == (unsigned char)c)
;             return (void *)p;
;         p++;
;     }
;     return NULL;
; }

define ptr @memchr(ptr noundef readonly %ptr, i32 noundef signext %c, i64 noundef %n) {
; CHECK-LABEL: @memchr(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT8:%.*]] = icmp eq i64 [[N:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT8]], label [[CLEANUP:%.*]], label [[WHILE_BODY_LR_PH:%.*]]
; CHECK:       while.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = trunc i32 [[C:%.*]] to i8
; CHECK-NEXT:    br label [[WHILE_BODY:%.*]]
; CHECK:       while.body:
; CHECK-NEXT:    [[DEC10_IN:%.*]] = phi i64 [ [[N]], [[WHILE_BODY_LR_PH]] ], [ [[DEC10:%.*]], [[IF_END:%.*]] ]
; CHECK-NEXT:    [[P_09:%.*]] = phi ptr [ [[PTR:%.*]], [[WHILE_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[IF_END]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_09]], align 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[TMP1]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP3]], label [[CLEANUP_LOOPEXIT:%.*]], label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[DEC10]] = add i64 [[DEC10_IN]], -1
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_09]], i64 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[DEC10]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[CLEANUP_LOOPEXIT]], label [[WHILE_BODY]]
; CHECK:       cleanup.loopexit:
; CHECK-NEXT:    [[RETVAL_0_PH:%.*]] = phi ptr [ [[P_09]], [[WHILE_BODY]] ], [ null, [[IF_END]] ]
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       cleanup:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ null, [[ENTRY:%.*]] ], [ [[RETVAL_0_PH]], [[CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    ret ptr [[RETVAL_0]]
;
entry:
  %cmp.not8 = icmp eq i64 %n, 0
  br i1 %cmp.not8, label %cleanup, label %while.body.lr.ph

while.body.lr.ph:                                 ; preds = %entry
  %0 = trunc i32 %c to i8
  br label %while.body

while.body:                                       ; preds = %while.body.lr.ph, %if.end
  %dec10.in = phi i64 [ %n, %while.body.lr.ph ], [ %dec10, %if.end ]
  %p.09 = phi ptr [ %ptr, %while.body.lr.ph ], [ %incdec.ptr, %if.end ]
  %1 = load i8, ptr %p.09, align 1
  %cmp3 = icmp eq i8 %1, %0
  br i1 %cmp3, label %cleanup.loopexit, label %if.end

if.end:                                           ; preds = %while.body
  %dec10 = add i64 %dec10.in, -1
  %incdec.ptr = getelementptr inbounds i8, ptr %p.09, i64 1
  %cmp.not = icmp eq i64 %dec10, 0
  br i1 %cmp.not, label %cleanup.loopexit, label %while.body

cleanup.loopexit:                                 ; preds = %if.end, %while.body
  %retval.0.ph = phi ptr [ %p.09, %while.body ], [ null, %if.end ]
  br label %cleanup

cleanup:                                          ; preds = %cleanup.loopexit, %entry
  %retval.0 = phi ptr [ null, %entry ], [ %retval.0.ph, %cleanup.loopexit ]
  ret ptr %retval.0
}
