; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=stress < %s | FileCheck %s

define i64 @search(ptr %start, i32 %v, i64 %n) {
; CHECK-LABEL: @search(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[IV]]
; CHECK-NEXT:    [[DATA:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[COND1:%.*]] = icmp eq i32 [[DATA]], [[V:%.*]]
; CHECK-NEXT:    [[COND2:%.*]] = icmp samesign ult i64 [[IV]], [[N:%.*]]
; CHECK-NEXT:    [[SELECT:%.*]] = select i1 [[COND1]], i1 [[COND2]], i1 false
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    br i1 [[SELECT]], label [[LOOP]], label [[EXIT:%.*]]
; CHECK:       exit:
; CHECK-NEXT:    [[IV_LCSSA:%.*]] = phi i64 [ [[IV]], [[LOOP]] ]
; CHECK-NEXT:    ret i64 [[IV_LCSSA]]
;
entry:
  br label %loop
loop:
  %iv = phi i64 [ %iv.next, %loop ], [ 0, %entry ]
  %gep = getelementptr inbounds nuw i32, ptr %start, i64 %iv
  %data = load i32, ptr %gep, align 4
  %cond1 = icmp eq i32 %data, %v
  %cond2 = icmp samesign ult i64 %iv, %n
  %select = select i1 %cond1, i1 %cond2, i1 false
  %iv.next = add nuw nsw i64 %iv, 1
  br i1 %select, label %loop, label %exit
exit:
  ret i64 %iv
}
