; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=on < %s | FileCheck %s

; void strcpy(char *__restrict dst, const char *src)
; {
;     while (1) {
;         *dst = *src;
;         if (*src == '\0') break;
;         src++; dst++;
;     }
; }

define void @strcpy(ptr %dst, ptr %src) {
; CHECK-LABEL: @strcpy(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC:%.*]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[DST:%.*]], align 1
; CHECK-NEXT:    [[CMP5:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[CMP5]], label [[WHILE_END:%.*]], label [[IF_END_PREHEADER:%.*]]
; CHECK:       if.end.preheader:
; CHECK-NEXT:    br label [[IF_END:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SRC_ADDR_07:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[IF_END]] ], [ [[SRC]], [[IF_END_PREHEADER]] ]
; CHECK-NEXT:    [[DST_ADDR_06:%.*]] = phi ptr [ [[INCDEC_PTR1:%.*]], [[IF_END]] ], [ [[DST]], [[IF_END_PREHEADER]] ]
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_07]], i64 1
; CHECK-NEXT:    [[INCDEC_PTR1]] = getelementptr inbounds i8, ptr [[DST_ADDR_06]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; CHECK-NEXT:    store i8 [[TMP1]], ptr [[INCDEC_PTR1]], align 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[WHILE_END_LOOPEXIT:%.*]], label [[IF_END]]
; CHECK:       while.end.loopexit:
; CHECK-NEXT:    br label [[WHILE_END]]
; CHECK:       while.end:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i8, ptr %src, align 1
  store i8 %0, ptr %dst, align 1
  %cmp5 = icmp eq i8 %0, 0
  br i1 %cmp5, label %while.end, label %if.end.preheader

if.end.preheader:
  br label %if.end

if.end:
  %src.addr.07 = phi ptr [ %incdec.ptr, %if.end ], [ %src, %if.end.preheader ]
  %dst.addr.06 = phi ptr [ %incdec.ptr1, %if.end ], [ %dst, %if.end.preheader ]
  %incdec.ptr = getelementptr inbounds i8, ptr %src.addr.07, i64 1
  %incdec.ptr1 = getelementptr inbounds i8, ptr %dst.addr.06, i64 1
  %1 = load i8, ptr %incdec.ptr, align 1
  store i8 %1, ptr %incdec.ptr1, align 1
  %cmp = icmp eq i8 %1, 0
  br i1 %cmp, label %while.end.loopexit, label %if.end

while.end.loopexit:
  br label %while.end

while.end:
  ret void
}
