; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=on < %s | FileCheck %s

; int strcmp(const char *s1, const char *s2) {
;     while (*s1 && (*s1 == *s2)) {
;         s1++;
;         s2++;
;     }
;     return *(const unsigned char *)s1 - *(const unsigned char *)s2;
; }

define i32 @strcmp(ptr %s1, ptr %s2) {
; CHECK-LABEL: @strcmp(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[S1:%.*]], align 1
; CHECK-NEXT:    [[TOBOOL_NOT10:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT10]], label [[WHILE_END:%.*]], label [[LAND_RHS_PREHEADER:%.*]]
; CHECK:       land.rhs.preheader:
; CHECK-NEXT:    br label [[LAND_RHS:%.*]]
; CHECK:       land.rhs:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i8 [ [[TMP3:%.*]], [[WHILE_BODY:%.*]] ], [ [[TMP0]], [[LAND_RHS_PREHEADER]] ]
; CHECK-NEXT:    [[S2_ADDR_012:%.*]] = phi ptr [ [[INCDEC_PTR2:%.*]], [[WHILE_BODY]] ], [ [[S2:%.*]], [[LAND_RHS_PREHEADER]] ]
; CHECK-NEXT:    [[S1_ADDR_011:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[WHILE_BODY]] ], [ [[S1]], [[LAND_RHS_PREHEADER]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[S2_ADDR_012]], align 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    br i1 [[CMP]], label [[WHILE_BODY]], label [[WHILE_END_LOOPEXIT:%.*]]
; CHECK:       while.body:
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S1_ADDR_011]], i64 1
; CHECK-NEXT:    [[INCDEC_PTR2]] = getelementptr inbounds i8, ptr [[S2_ADDR_012]], i64 1
; CHECK-NEXT:    [[TMP3]] = load i8, ptr [[INCDEC_PTR]], align 1
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i8 [[TMP3]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[WHILE_END_LOOPEXIT]], label [[LAND_RHS]]
; CHECK:       while.end.loopexit:
; CHECK-NEXT:    [[S2_ADDR_0_LCSSA_PH:%.*]] = phi ptr [ [[S2_ADDR_012]], [[LAND_RHS]] ], [ [[INCDEC_PTR2]], [[WHILE_BODY]] ]
; CHECK-NEXT:    [[DOTLCSSA_PH:%.*]] = phi i8 [ [[TMP1]], [[LAND_RHS]] ], [ 0, [[WHILE_BODY]] ]
; CHECK-NEXT:    br label [[WHILE_END]]
; CHECK:       while.end:
; CHECK-NEXT:    [[S2_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S2]], [[ENTRY:%.*]] ], [ [[S2_ADDR_0_LCSSA_PH]], [[WHILE_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi i8 [ 0, [[ENTRY]] ], [ [[DOTLCSSA_PH]], [[WHILE_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[CONV3:%.*]] = zext i8 [[DOTLCSSA]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[S2_ADDR_0_LCSSA]], align 1
; CHECK-NEXT:    [[CONV4:%.*]] = zext i8 [[TMP4]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[CONV3]], [[CONV4]]
; CHECK-NEXT:    ret i32 [[SUB]]
;
entry:
  %0 = load i8, ptr %s1, align 1
  %tobool.not10 = icmp eq i8 %0, 0
  br i1 %tobool.not10, label %while.end, label %land.rhs.preheader

land.rhs.preheader:
  br label %land.rhs

land.rhs:
  %1 = phi i8 [ %3, %while.body ], [ %0, %land.rhs.preheader ]
  %s2.addr.012 = phi ptr [ %incdec.ptr2, %while.body ], [ %s2, %land.rhs.preheader ]
  %s1.addr.011 = phi ptr [ %incdec.ptr, %while.body ], [ %s1, %land.rhs.preheader ]
  %2 = load i8, ptr %s2.addr.012, align 1
  %cmp = icmp eq i8 %1, %2
  br i1 %cmp, label %while.body, label %while.end.loopexit

while.body:
  %incdec.ptr = getelementptr inbounds i8, ptr %s1.addr.011, i64 1
  %incdec.ptr2 = getelementptr inbounds i8, ptr %s2.addr.012, i64 1
  %3 = load i8, ptr %incdec.ptr, align 1
  %tobool.not = icmp eq i8 %3, 0
  br i1 %tobool.not, label %while.end.loopexit, label %land.rhs

while.end.loopexit:
  %s2.addr.0.lcssa.ph = phi ptr [ %s2.addr.012, %land.rhs ], [ %incdec.ptr2, %while.body ]
  %.lcssa.ph = phi i8 [ %1, %land.rhs ], [ 0, %while.body ]
  br label %while.end

while.end:
  %s2.addr.0.lcssa = phi ptr [ %s2, %entry ], [ %s2.addr.0.lcssa.ph, %while.end.loopexit ]
  %.lcssa = phi i8 [ 0, %entry ], [ %.lcssa.ph, %while.end.loopexit ]
  %conv3 = zext i8 %.lcssa to i32
  %4 = load i8, ptr %s2.addr.0.lcssa, align 1
  %conv4 = zext i8 %4 to i32
  %sub = sub nsw i32 %conv3, %conv4
  ret i32 %sub
}
