; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=on < %s | FileCheck %s

; char *strchr(const char *str, int c) {
;     while (*str != (char)c) {
;         if (!*str++) {
;             return nullptr;
;         }
;     }
;     return (char *)str;
; }

define ptr @strchr(ptr noundef readonly %str, i32 noundef signext %c) {
; CHECK-LABEL: @strchr(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = trunc i32 [[C:%.*]] to i8
; CHECK-NEXT:    br label [[WHILE_COND:%.*]]
; CHECK:       while.cond:
; CHECK-NEXT:    [[STR_ADDR_0:%.*]] = phi ptr [ [[STR:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_BODY:%.*]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[STR_ADDR_0]], align 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[RETURN:%.*]], label [[WHILE_BODY]]
; CHECK:       while.body:
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[STR_ADDR_0]], i64 1
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[RETURN]], label [[WHILE_COND]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ null, [[WHILE_BODY]] ], [ [[STR_ADDR_0]], [[WHILE_COND]] ]
; CHECK-NEXT:    ret ptr [[RETVAL_0]]
;
entry:
  %0 = trunc i32 %c to i8
  br label %while.cond

while.cond:
  %str.addr.0 = phi ptr [ %str, %entry ], [ %incdec.ptr, %while.body ]
  %1 = load i8, ptr %str.addr.0, align 1
  %cmp.not = icmp eq i8 %1, %0
  br i1 %cmp.not, label %return, label %while.body

while.body:
  %incdec.ptr = getelementptr inbounds i8, ptr %str.addr.0, i64 1
  %tobool.not = icmp eq i8 %1, 0
  br i1 %tobool.not, label %return, label %while.cond

return:
  %retval.0 = phi ptr [ null, %while.body ], [ %str.addr.0, %while.cond ]
  ret ptr %retval.0
}
