; NOTE: Assertions have been autogenerated by utils/update_test_checks.py

; This test covers vectorization of strlen under various vectorization parameters. It is not a comprehensive test of IR variations and end-2-end test. Testing of IR variations is in another test. E2E tests are in llvm-test-suite.

; Test default
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 < %s | FileCheck %s --check-prefix=DEFAULT

; Test options
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -sifive-uncountable-loop-vectorization=on < %s | FileCheck %s --check-prefix=ON
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -sifive-uncountable-loop-vectorization=off < %s | FileCheck %s --check-prefix=OFF
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -sifive-uncountable-loop-vectorization=analysis-only < %s | FileCheck %s --check-prefix=ANALYSIS-ONLY
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -sifive-uncountable-loop-vectorization=stress < %s | FileCheck %s --check-prefix=stress

; Test VLS
; RUN: opt -S -riscv-use-vla-vectorizer=false -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 < %s | FileCheck %s --check-prefix=VLS

; Test interleaving factors IF=0,1,2
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -force-target-max-vector-interleave=0 < %s | FileCheck %s --check-prefix=IF0
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -force-target-max-vector-interleave=1 < %s | FileCheck %s --check-prefix=IF1
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -mcpu=sifive-p670 -force-target-max-vector-interleave=2 < %s | FileCheck %s --check-prefix=IF2

declare i8 @llvm.smax.i8(i8, i8)
declare i8 @unknown(i8, i8)

define i64 @strlen_i8(ptr %start) {
; DEFAULT-LABEL: @strlen_i8(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP4:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @strlen_i8(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP4:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @strlen_i8(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @strlen_i8(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @strlen_i8(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP4:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @strlen_i8(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @strlen_i8(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP4:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @strlen_i8(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP4:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @strlen_i8(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP4:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %cmp.not = icmp eq i8 %0, 0
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

define i64 @strlen_i16(ptr %start) {
; DEFAULT-LABEL: @strlen_i16(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; DEFAULT-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 2
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP1]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP3]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 2
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP11:%.*]] = load i16, ptr [[END_0]], align 2
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP11]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP6:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; ON-LABEL: @strlen_i16(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; ON-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 2
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP1]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP3]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 2
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP11:%.*]] = load i16, ptr [[END_0]], align 2
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP11]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP6:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; ON-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; OFF-LABEL: @strlen_i16(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i16, ptr [[END_0]], align 2
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP0]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; OFF-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; ANALYSIS-ONLY-LABEL: @strlen_i16(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i16, ptr [[END_0]], align 2
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; stress-LABEL: @strlen_i16(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; stress-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 2
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP1]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP3]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 2
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP11:%.*]] = load i16, ptr [[END_0]], align 2
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP11]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP6:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; stress-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; VLS-LABEL: @strlen_i16(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i16, ptr [[END_0]], align 2
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP0]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; VLS-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF0-LABEL: @strlen_i16(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF0-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 2
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP1]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP3]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 2
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP11:%.*]] = load i16, ptr [[END_0]], align 2
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP11]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP6:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; IF0-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF1-LABEL: @strlen_i16(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF1-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 2
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP1]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP3]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 2
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP11:%.*]] = load i16, ptr [[END_0]], align 2
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP11]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP6:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; IF1-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF2-LABEL: @strlen_i16(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF2-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 2
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i16, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP1]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP3]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 2
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP11:%.*]] = load i16, ptr [[END_0]], align 2
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i16 [[TMP11]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP6:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 1
; IF2-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i16, ptr %end.0, align 2
  %cmp.not = icmp eq i16 %0, 0
  %incdec.ptr = getelementptr inbounds i16, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  %sub.ptr.div = ashr exact i64 %sub.ptr.sub, 1
  ret i64 %sub.ptr.div
}

define i64 @strlen_i32(ptr %start) {
; DEFAULT-LABEL: @strlen_i32(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 8, i1 true)
; DEFAULT-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP1]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP3]], <vscale x 8 x i32> zeroinitializer, metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP11:%.*]] = load i32, ptr [[END_0]], align 4
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; ON-LABEL: @strlen_i32(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 8, i1 true)
; ON-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP1]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP3]], <vscale x 8 x i32> zeroinitializer, metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP11:%.*]] = load i32, ptr [[END_0]], align 4
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; ON-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; OFF-LABEL: @strlen_i32(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[END_0]], align 4
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; OFF-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; ANALYSIS-ONLY-LABEL: @strlen_i32(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[END_0]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; stress-LABEL: @strlen_i32(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 8, i1 true)
; stress-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP1]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP3]], <vscale x 8 x i32> zeroinitializer, metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP11:%.*]] = load i32, ptr [[END_0]], align 4
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; stress-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; VLS-LABEL: @strlen_i32(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[END_0]], align 4
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; VLS-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF0-LABEL: @strlen_i32(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 8, i1 true)
; IF0-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP1]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP3]], <vscale x 8 x i32> zeroinitializer, metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP11:%.*]] = load i32, ptr [[END_0]], align 4
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; IF0-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF1-LABEL: @strlen_i32(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 8, i1 true)
; IF1-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP1]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP3]], <vscale x 8 x i32> zeroinitializer, metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP11:%.*]] = load i32, ptr [[END_0]], align 4
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; IF1-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF2-LABEL: @strlen_i32(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 8, i1 true)
; IF2-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[OFFSET_IDX]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP1]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP3]], <vscale x 8 x i32> zeroinitializer, metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP9]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP11:%.*]] = load i32, ptr [[END_0]], align 4
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i32, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 2
; IF2-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i32, ptr %end.0, align 4
  %cmp.not = icmp eq i32 %0, 0
  %incdec.ptr = getelementptr inbounds i32, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  %sub.ptr.div = ashr exact i64 %sub.ptr.sub, 2
  ret i64 %sub.ptr.div
}

define i64 @strlen_i64(ptr %start) {
; DEFAULT-LABEL: @strlen_i64(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP11:%.*]] = load i64, ptr [[END_0]], align 4
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP11]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; ON-LABEL: @strlen_i64(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP11:%.*]] = load i64, ptr [[END_0]], align 4
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP11]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; ON-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; OFF-LABEL: @strlen_i64(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i64, ptr [[END_0]], align 4
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP0]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; OFF-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; ANALYSIS-ONLY-LABEL: @strlen_i64(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i64, ptr [[END_0]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; stress-LABEL: @strlen_i64(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP11:%.*]] = load i64, ptr [[END_0]], align 4
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP11]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; stress-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; VLS-LABEL: @strlen_i64(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i64, ptr [[END_0]], align 4
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP0]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; VLS-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF0-LABEL: @strlen_i64(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP11:%.*]] = load i64, ptr [[END_0]], align 4
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP11]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; IF0-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF1-LABEL: @strlen_i64(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP11:%.*]] = load i64, ptr [[END_0]], align 4
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP11]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; IF1-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
; IF2-LABEL: @strlen_i64(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP11:%.*]] = load i64, ptr [[END_0]], align 4
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP11]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i64, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    [[SUB_PTR_DIV:%.*]] = ashr exact i64 [[SUB_PTR_SUB]], 3
; IF2-NEXT:    ret i64 [[SUB_PTR_DIV]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i64, ptr %end.0, align 4
  %cmp.not = icmp eq i64 %0, 0
  %incdec.ptr = getelementptr inbounds i64, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  %sub.ptr.div = ashr exact i64 %sub.ptr.sub, 3
  ret i64 %sub.ptr.div
}

; Test safe calls
define i64 @SingleBlock0(ptr %start) {
; DEFAULT-LABEL: @SingleBlock0(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.smax.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 1), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 1), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP10]], i8 1)
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP10:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock0(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.smax.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 1), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 1), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP10]], i8 1)
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP10:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock0(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP0]], i8 1)
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock0(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP0]], i8 1)
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock0(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.smax.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 1), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 1), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP10]], i8 1)
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP10:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock0(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP0]], i8 1)
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock0(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.smax.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 1), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 1), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP10]], i8 1)
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP10:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock0(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.smax.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 1), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 1), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP10]], i8 1)
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP10:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock0(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.smax.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 1), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> splat (i8 1), metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[MAX:%.*]] = tail call i8 @llvm.smax.i8(i8 [[TMP10]], i8 1)
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP10:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %max = tail call i8 @llvm.smax.i8(i8 %0, i8 1)
  %cmp.not = icmp eq i8 %max, 1
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test unsafe calls
define i64 @SingleBlock1(ptr %start) {
; DEFAULT-LABEL: @SingleBlock1(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock1(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock1(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock1(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock1(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock1(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock1(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock1(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock1(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[MAX:%.*]] = tail call i8 @unknown(i8 [[TMP0]], i8 1)
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[MAX]], 1
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %max = tail call i8 @unknown(i8 %0, i8 1)
  %cmp.not = icmp eq i8 %max, 1
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test unsafe instructions
define i64 @SingleBlock2(ptr %start) {
; DEFAULT-LABEL: @SingleBlock2(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock2(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock2(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock2(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock2(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock2(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock2(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock2(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock2(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[TMP1:%.*]] = sdiv i8 1, [[TMP0]]
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %1 = sdiv i8 1, %0
  %cmp.not = icmp eq i8 %1, 1
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test safe "unsafe" instructions
define i64 @SingleBlock3(ptr %start) {
; DEFAULT-LABEL: @SingleBlock3(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock3(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock3(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock3(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock3(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock3(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock3(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock3(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock3(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[TMP1:%.*]] = sdiv i8 [[TMP0]], 2
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 1
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %1 = sdiv i8 %0, 2
  %cmp.not = icmp eq i8 %1, 1
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test ptr induction variables with external users of their last values
define i64 @SingleBlock4(ptr %start) {
; DEFAULT-LABEL: @SingleBlock4(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; DEFAULT-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; DEFAULT-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; DEFAULT-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; DEFAULT-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; DEFAULT-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 1)
; DEFAULT-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; DEFAULT-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; DEFAULT-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; DEFAULT-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; DEFAULT-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; DEFAULT-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; DEFAULT-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; DEFAULT-NEXT:    [[TMP16:%.*]] = icmp sge i32 [[TMP13]], 0
; DEFAULT-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP9]] to i64
; DEFAULT-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP10]], 1
; DEFAULT-NEXT:    [[TMP15:%.*]] = mul i64 1, [[TMP14]]
; DEFAULT-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP15]]
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP21]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP16]], label [[MIDDLE_BLOCK:%.*]], label [[FOR_COND]], !llvm.loop [[LOOP11:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = zext i32 [[TMP13]] to i64
; DEFAULT-NEXT:    [[TMP18:%.*]] = add i64 [[EVL_BASED_IV]], [[FIRST_ACTIVE_LANE]]
; DEFAULT-NEXT:    [[TMP22:%.*]] = add i64 [[TMP18]], 1
; DEFAULT-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP22]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP11:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP12:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND1]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock4(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; ON:       vector.ph:
; ON-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; ON-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; ON-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; ON-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; ON-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; ON-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; ON-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_COND]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[FOR_COND]] ]
; ON-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[FOR_COND]] ]
; ON-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 1)
; ON-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; ON-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; ON-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; ON-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; ON-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; ON-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; ON-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; ON-NEXT:    [[TMP16:%.*]] = icmp sge i32 [[TMP13]], 0
; ON-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP9]] to i64
; ON-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP10]], 1
; ON-NEXT:    [[TMP15:%.*]] = mul i64 1, [[TMP14]]
; ON-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP15]]
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP21]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP16]], label [[MIDDLE_BLOCK:%.*]], label [[FOR_COND]], !llvm.loop [[LOOP11:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = zext i32 [[TMP13]] to i64
; ON-NEXT:    [[TMP18:%.*]] = add i64 [[EVL_BASED_IV]], [[FIRST_ACTIVE_LANE]]
; ON-NEXT:    [[TMP22:%.*]] = add i64 [[TMP18]], 1
; ON-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP22]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP11:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP12:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND1]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock4(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock4(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock4(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; stress:       vector.ph:
; stress-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; stress-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; stress-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; stress-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; stress-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; stress-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; stress-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_COND]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[FOR_COND]] ]
; stress-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[FOR_COND]] ]
; stress-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 1)
; stress-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; stress-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; stress-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; stress-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; stress-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; stress-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; stress-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; stress-NEXT:    [[TMP16:%.*]] = icmp sge i32 [[TMP13]], 0
; stress-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP9]] to i64
; stress-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP10]], 1
; stress-NEXT:    [[TMP15:%.*]] = mul i64 1, [[TMP14]]
; stress-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP15]]
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP21]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP16]], label [[MIDDLE_BLOCK:%.*]], label [[FOR_COND]], !llvm.loop [[LOOP11:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = zext i32 [[TMP13]] to i64
; stress-NEXT:    [[TMP18:%.*]] = add i64 [[EVL_BASED_IV]], [[FIRST_ACTIVE_LANE]]
; stress-NEXT:    [[TMP22:%.*]] = add i64 [[TMP18]], 1
; stress-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP22]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP11:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP12:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND1]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock4(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock4(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IF0-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; IF0-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; IF0-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; IF0-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; IF0-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; IF0-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_COND]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[FOR_COND]] ]
; IF0-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[FOR_COND]] ]
; IF0-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 1)
; IF0-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; IF0-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF0-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; IF0-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; IF0-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; IF0-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; IF0-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; IF0-NEXT:    [[TMP16:%.*]] = icmp sge i32 [[TMP13]], 0
; IF0-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP9]] to i64
; IF0-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP10]], 1
; IF0-NEXT:    [[TMP15:%.*]] = mul i64 1, [[TMP14]]
; IF0-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP15]]
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP21]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP16]], label [[MIDDLE_BLOCK:%.*]], label [[FOR_COND]], !llvm.loop [[LOOP11:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = zext i32 [[TMP13]] to i64
; IF0-NEXT:    [[TMP18:%.*]] = add i64 [[EVL_BASED_IV]], [[FIRST_ACTIVE_LANE]]
; IF0-NEXT:    [[TMP22:%.*]] = add i64 [[TMP18]], 1
; IF0-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP22]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP11:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP12:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND1]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock4(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IF1-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; IF1-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; IF1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; IF1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; IF1-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; IF1-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_COND]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[FOR_COND]] ]
; IF1-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[FOR_COND]] ]
; IF1-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 1)
; IF1-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; IF1-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF1-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; IF1-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; IF1-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; IF1-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; IF1-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; IF1-NEXT:    [[TMP16:%.*]] = icmp sge i32 [[TMP13]], 0
; IF1-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP9]] to i64
; IF1-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP10]], 1
; IF1-NEXT:    [[TMP15:%.*]] = mul i64 1, [[TMP14]]
; IF1-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP15]]
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP21]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP16]], label [[MIDDLE_BLOCK:%.*]], label [[FOR_COND]], !llvm.loop [[LOOP11:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = zext i32 [[TMP13]] to i64
; IF1-NEXT:    [[TMP18:%.*]] = add i64 [[EVL_BASED_IV]], [[FIRST_ACTIVE_LANE]]
; IF1-NEXT:    [[TMP22:%.*]] = add i64 [[TMP18]], 1
; IF1-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP22]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP11:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP12:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND1]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock4(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IF2-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; IF2-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; IF2-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; IF2-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; IF2-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; IF2-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[FOR_COND]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[FOR_COND]] ]
; IF2-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[FOR_COND]] ]
; IF2-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 1)
; IF2-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; IF2-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF2-NEXT:    [[TMP7:%.*]] = extractelement <vscale x 16 x ptr> [[VECTOR_GEP]], i32 0
; IF2-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP7]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i8>, i32 } @llvm.vp.load.ff.nxv16i8.p0(ptr align 1 [[TMP8]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; IF2-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; IF2-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i8(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; IF2-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP9]])
; IF2-NEXT:    [[TMP16:%.*]] = icmp sge i32 [[TMP13]], 0
; IF2-NEXT:    [[TMP21:%.*]] = zext i32 [[TMP9]] to i64
; IF2-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP10]], 1
; IF2-NEXT:    [[TMP15:%.*]] = mul i64 1, [[TMP14]]
; IF2-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP15]]
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP21]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP16]], label [[MIDDLE_BLOCK:%.*]], label [[FOR_COND]], !llvm.loop [[LOOP11:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = zext i32 [[TMP13]] to i64
; IF2-NEXT:    [[TMP18:%.*]] = add i64 [[EVL_BASED_IV]], [[FIRST_ACTIVE_LANE]]
; IF2-NEXT:    [[TMP22:%.*]] = add i64 [[TMP18]], 1
; IF2-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP22]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP11:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP12:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR]], [[FOR_COND1]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %cmp.not = icmp eq i8 %0, 0
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %incdec.ptr.lcssa = phi ptr [ %incdec.ptr, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %incdec.ptr.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test ptr induction variables with external users of their penultimate values
define i64 @SingleBlock5(ptr %start) {
; DEFAULT-LABEL: @SingleBlock5(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP14:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock5(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP14:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock5(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock5(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock5(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP14:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock5(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock5(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP14:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock5(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP14:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock5(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP10]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP14:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[INCDEC_PTR_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[INCDEC_PTR_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %cmp.not = icmp eq i8 %0, 0
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %incdec.ptr.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %incdec.ptr.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test integer induction variables with external users of their penultimate values
define i32 @SingleBlock6(ptr %start) {
; DEFAULT-LABEL: @SingleBlock6(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; DEFAULT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; DEFAULT-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; DEFAULT-NEXT:    ret i32 [[TMP1]]
;
; ON-LABEL: @SingleBlock6(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; ON-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ON-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ON-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; ON:       for.end:
; ON-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ON-NEXT:    ret i32 [[TMP1]]
;
; OFF-LABEL: @SingleBlock6(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; OFF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; OFF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; OFF-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; OFF-NEXT:    ret i32 [[TMP1]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock6(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ANALYSIS-ONLY-NEXT:    ret i32 [[TMP1]]
;
; stress-LABEL: @SingleBlock6(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; stress-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; stress-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; stress-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; stress:       for.end:
; stress-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; stress-NEXT:    ret i32 [[TMP1]]
;
; VLS-LABEL: @SingleBlock6(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; VLS-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; VLS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; VLS-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; VLS-NEXT:    ret i32 [[TMP1]]
;
; IF0-LABEL: @SingleBlock6(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF0-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF0:       for.end:
; IF0-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF0-NEXT:    ret i32 [[TMP1]]
;
; IF1-LABEL: @SingleBlock6(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF1-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF1:       for.end:
; IF1-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF1-NEXT:    ret i32 [[TMP1]]
;
; IF2-LABEL: @SingleBlock6(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF2-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF2:       for.end:
; IF2-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF2-NEXT:    ret i32 [[TMP1]]
;
entry:
  br label %for.cond

for.cond:
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.cond ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i32, ptr %start, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx, align 4
  %cmp.not = icmp eq i32 %0, 0
  %indvars.iv.next = add nuw i64 %indvars.iv, 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %indvars.iv.lcssa = phi i64 [ %indvars.iv, %for.cond ]
  %1 = trunc i64 %indvars.iv.lcssa to i32
  ret i32 %1
}

; Test integer induction variables with external users of their last values
define i32 @SingleBlock7(ptr %start) {
; DEFAULT-LABEL: @SingleBlock7(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; DEFAULT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; DEFAULT-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; DEFAULT-NEXT:    ret i32 [[TMP1]]
;
; ON-LABEL: @SingleBlock7(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; ON-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ON-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ON-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; ON:       for.end:
; ON-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ON-NEXT:    ret i32 [[TMP1]]
;
; OFF-LABEL: @SingleBlock7(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; OFF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; OFF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; OFF-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; OFF-NEXT:    ret i32 [[TMP1]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock7(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ANALYSIS-ONLY-NEXT:    ret i32 [[TMP1]]
;
; stress-LABEL: @SingleBlock7(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; stress-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; stress-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; stress-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; stress:       for.end:
; stress-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; stress-NEXT:    ret i32 [[TMP1]]
;
; VLS-LABEL: @SingleBlock7(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; VLS-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; VLS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; VLS-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; VLS-NEXT:    ret i32 [[TMP1]]
;
; IF0-LABEL: @SingleBlock7(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF0-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF0:       for.end:
; IF0-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF0-NEXT:    ret i32 [[TMP1]]
;
; IF1-LABEL: @SingleBlock7(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF1-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF1:       for.end:
; IF1-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF1-NEXT:    ret i32 [[TMP1]]
;
; IF2-LABEL: @SingleBlock7(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND1]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF2-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND1]]
; IF2:       for.end:
; IF2-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF2-NEXT:    ret i32 [[TMP1]]
;
entry:
  br label %for.cond

for.cond:
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.cond ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i32, ptr %start, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx, align 4
  %cmp.not = icmp eq i32 %0, 0
  %indvars.iv.next = add nuw i64 %indvars.iv, 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %indvars.iv.lcssa = phi i64 [ %indvars.iv.next, %for.cond ]
  %1 = trunc i64 %indvars.iv.lcssa to i32
  ret i32 %1
}

; Test "unconditional" branches and infinite loops
define i32 @SingleBlock8(ptr %start) {
; DEFAULT-LABEL: @SingleBlock8(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; DEFAULT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; DEFAULT-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; DEFAULT-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; DEFAULT-NEXT:    ret i32 [[TMP1]]
;
; ON-LABEL: @SingleBlock8(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; ON-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ON-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ON-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ON-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       for.end:
; ON-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; ON-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ON-NEXT:    ret i32 [[TMP1]]
;
; OFF-LABEL: @SingleBlock8(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; OFF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; OFF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; OFF-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; OFF-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; OFF-NEXT:    ret i32 [[TMP1]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock8(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ANALYSIS-ONLY-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ANALYSIS-ONLY-NEXT:    ret i32 [[TMP1]]
;
; stress-LABEL: @SingleBlock8(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; stress-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; stress-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; stress-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; stress-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       for.end:
; stress-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; stress-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; stress-NEXT:    ret i32 [[TMP1]]
;
; VLS-LABEL: @SingleBlock8(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; VLS-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; VLS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; VLS-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; VLS-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; VLS-NEXT:    ret i32 [[TMP1]]
;
; IF0-LABEL: @SingleBlock8(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; IF0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF0-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF0-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       for.end:
; IF0-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; IF0-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF0-NEXT:    ret i32 [[TMP1]]
;
; IF1-LABEL: @SingleBlock8(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; IF1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF1-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF1-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       for.end:
; IF1-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; IF1-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF1-NEXT:    ret i32 [[TMP1]]
;
; IF2-LABEL: @SingleBlock8(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; IF2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[TMP0]], 0
; IF2-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF2-NEXT:    br i1 false, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       for.end:
; IF2-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; IF2-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF2-NEXT:    ret i32 [[TMP1]]
;
entry:
  br label %for.cond

for.cond:
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.cond ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i32, ptr %start, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx, align 4
  %cmp.not = icmp eq i32 %0, 0
  %indvars.iv.next = add nuw i64 %indvars.iv, 1
  br i1 false, label %for.end, label %for.cond

for.end:
  %indvars.iv.lcssa = phi i64 [ %indvars.iv.next, %for.cond ]
  %1 = trunc i64 %indvars.iv.lcssa to i32
  ret i32 %1
}

; Test duplicated sources
define i64 @SingleBlock9(ptr %start) {
; DEFAULT-LABEL: @SingleBlock9(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.add.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[TMP3]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; DEFAULT-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[FOR_COND1:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; DEFAULT-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; DEFAULT-NEXT:    [[TMP11:%.*]] = add i8 [[TMP10]], [[TMP10]]
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP16:![0-9]+]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; DEFAULT-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; DEFAULT-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ON-LABEL: @SingleBlock9(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.add.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[TMP3]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; ON-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[FOR_COND1:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; ON-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; ON-NEXT:    [[TMP11:%.*]] = add i8 [[TMP10]], [[TMP10]]
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP16:![0-9]+]]
; ON:       for.end:
; ON-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ON-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ON-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ON-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; OFF-LABEL: @SingleBlock9(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; OFF-NEXT:    [[TMP1:%.*]] = add i8 [[TMP0]], [[TMP0]]
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; OFF-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; OFF-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; OFF-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; OFF-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock9(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = add i8 [[TMP0]], [[TMP0]]
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; ANALYSIS-ONLY-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; stress-LABEL: @SingleBlock9(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.add.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[TMP3]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; stress-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[FOR_COND1:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; stress-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; stress-NEXT:    [[TMP11:%.*]] = add i8 [[TMP10]], [[TMP10]]
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP16:![0-9]+]]
; stress:       for.end:
; stress-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; stress-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; stress-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; stress-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; VLS-LABEL: @SingleBlock9(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[END_0:%.*]] = phi ptr [ [[START:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[END_0]], align 1
; VLS-NEXT:    [[TMP1:%.*]] = add i8 [[TMP0]], [[TMP0]]
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND]] ]
; VLS-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; VLS-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; VLS-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; VLS-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF0-LABEL: @SingleBlock9(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.add.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[TMP3]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF0-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[FOR_COND1:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF0-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF0-NEXT:    [[TMP11:%.*]] = add i8 [[TMP10]], [[TMP10]]
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP16:![0-9]+]]
; IF0:       for.end:
; IF0-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF0-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF1-LABEL: @SingleBlock9(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.add.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[TMP3]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF1-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[FOR_COND1:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF1-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF1-NEXT:    [[TMP11:%.*]] = add i8 [[TMP10]], [[TMP10]]
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP16:![0-9]+]]
; IF1:       for.end:
; IF1-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF1-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF1-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF1-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
; IF2-LABEL: @SingleBlock9(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[FOR_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[START:%.*]], i64 [[EVL_BASED_IV]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i8> @llvm.vp.add.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[TMP3]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[VP_OP]], <vscale x 32 x i8> zeroinitializer, metadata !"eq", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[START]], i64 [[TMP8]]
; IF2-NEXT:    br i1 true, label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[FOR_COND1:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[END_0:%.*]] = phi ptr [ [[START]], [[FOR_COND]] ], [ [[INCDEC_PTR:%.*]], [[FOR_COND1]] ]
; IF2-NEXT:    [[TMP10:%.*]] = load i8, ptr [[END_0]], align 1
; IF2-NEXT:    [[TMP11:%.*]] = add i8 [[TMP10]], [[TMP10]]
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP11]], 0
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END_0]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_COND1]], !llvm.loop [[LOOP16:![0-9]+]]
; IF2:       for.end:
; IF2-NEXT:    [[END_0_LCSSA:%.*]] = phi ptr [ [[END_0]], [[FOR_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[END_0_LCSSA]] to i64
; IF2-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[START]] to i64
; IF2-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]]
; IF2-NEXT:    ret i64 [[SUB_PTR_SUB]]
;
entry:
  br label %for.cond

for.cond:
  %end.0 = phi ptr [ %start, %entry ], [ %incdec.ptr, %for.cond ]
  %0 = load i8, ptr %end.0, align 1
  %1 = add i8 %0, %0
  %cmp.not = icmp eq i8 %1, 0
  %incdec.ptr = getelementptr inbounds i8, ptr %end.0, i64 1
  br i1 %cmp.not, label %for.end, label %for.cond

for.end:
  %end.0.lcssa = phi ptr [ %end.0, %for.cond ]
  %sub.ptr.lhs.cast = ptrtoint ptr %end.0.lcssa to i64
  %sub.ptr.rhs.cast = ptrtoint ptr %start to i64
  %sub.ptr.sub = sub i64 %sub.ptr.lhs.cast, %sub.ptr.rhs.cast
  ret i64 %sub.ptr.sub
}

; Test false positive uncountable loops
define i32 @SingleBlock10(i32 %N) {
; DEFAULT-LABEL: @SingleBlock10(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; DEFAULT-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; DEFAULT:       loop_inc:
; DEFAULT-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; DEFAULT-NEXT:    br label [[FOR_COND]]
; DEFAULT:       return:
; DEFAULT-NEXT:    ret i32 0
;
; ON-LABEL: @SingleBlock10(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; ON-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; ON-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; ON:       loop_inc:
; ON-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; ON-NEXT:    br label [[FOR_COND]]
; ON:       return:
; ON-NEXT:    ret i32 0
;
; OFF-LABEL: @SingleBlock10(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; OFF-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; OFF-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; OFF:       loop_inc:
; OFF-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; OFF-NEXT:    br label [[FOR_COND]]
; OFF:       return:
; OFF-NEXT:    ret i32 0
;
; ANALYSIS-ONLY-LABEL: @SingleBlock10(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; ANALYSIS-ONLY:       loop_inc:
; ANALYSIS-ONLY-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND]]
; ANALYSIS-ONLY:       return:
; ANALYSIS-ONLY-NEXT:    ret i32 0
;
; stress-LABEL: @SingleBlock10(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; stress-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; stress-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; stress:       loop_inc:
; stress-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; stress-NEXT:    br label [[FOR_COND]]
; stress:       return:
; stress-NEXT:    ret i32 0
;
; VLS-LABEL: @SingleBlock10(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; VLS-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; VLS-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; VLS:       loop_inc:
; VLS-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; VLS-NEXT:    br label [[FOR_COND]]
; VLS:       return:
; VLS-NEXT:    ret i32 0
;
; IF0-LABEL: @SingleBlock10(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; IF0-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; IF0-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; IF0:       loop_inc:
; IF0-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; IF0-NEXT:    br label [[FOR_COND]]
; IF0:       return:
; IF0-NEXT:    ret i32 0
;
; IF1-LABEL: @SingleBlock10(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; IF1-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; IF1-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; IF1:       loop_inc:
; IF1-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; IF1-NEXT:    br label [[FOR_COND]]
; IF1:       return:
; IF1-NEXT:    ret i32 0
;
; IF2-LABEL: @SingleBlock10(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[INDEX:%.*]] = phi i32 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[LOOP_INC:%.*]] ]
; IF2-NEXT:    [[CMP:%.*]] = icmp ne i32 [[INDEX]], [[N:%.*]]
; IF2-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[LOOP_INC]]
; IF2:       loop_inc:
; IF2-NEXT:    [[INC]] = add i32 [[INDEX]], 1
; IF2-NEXT:    br label [[FOR_COND]]
; IF2:       return:
; IF2-NEXT:    ret i32 0
;
entry:
  br label %for.cond

for.cond:
  %index = phi i32 [ 1, %entry ], [ %inc, %loop_inc ]
  %cmp = icmp ne i32 %index, %N
  br i1 %cmp, label %return, label %loop_inc

loop_inc:
  %inc = add i32 %index, 1
  br label %for.cond

return:
  ret i32 0
}

; Test flipped branch
define ptr @SingleBlock11(ptr %s) {
; DEFAULT-LABEL: @SingleBlock11(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[WHILE_COND:%.*]], label [[VECTOR_PH:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 [[EVL_BASED_IV]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 49), metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[S]], i64 [[TMP8]]
; DEFAULT-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[WHILE_COND]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[WHILE_COND1:%.*]]
; DEFAULT:       while.cond:
; DEFAULT-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S]], [[WHILE_COND]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; DEFAULT-NEXT:    [[TMP10:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP10]], 49
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP18:![0-9]+]]
; DEFAULT:       while.end:
; DEFAULT-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; ON-LABEL: @SingleBlock11(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[WHILE_COND:%.*]], label [[VECTOR_PH:%.*]]
; ON:       vector.ph:
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 [[EVL_BASED_IV]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 49), metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[S]], i64 [[TMP8]]
; ON-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[WHILE_COND]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[WHILE_COND1:%.*]]
; ON:       while.cond:
; ON-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S]], [[WHILE_COND]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; ON-NEXT:    [[TMP10:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; ON-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP10]], 49
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; ON-NEXT:    br i1 [[CMP]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP18:![0-9]+]]
; ON:       while.end:
; ON-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; OFF-LABEL: @SingleBlock11(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[WHILE_COND:%.*]]
; OFF:       while.cond:
; OFF-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; OFF-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP0]], 49
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; OFF-NEXT:    br i1 [[CMP]], label [[WHILE_COND]], label [[WHILE_END:%.*]]
; OFF:       while.end:
; OFF-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND]] ]
; OFF-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock11(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[WHILE_COND:%.*]]
; ANALYSIS-ONLY:       while.cond:
; ANALYSIS-ONLY-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP0]], 49
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP]], label [[WHILE_COND]], label [[WHILE_END:%.*]]
; ANALYSIS-ONLY:       while.end:
; ANALYSIS-ONLY-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; stress-LABEL: @SingleBlock11(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[WHILE_COND:%.*]], label [[VECTOR_PH:%.*]]
; stress:       vector.ph:
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 [[EVL_BASED_IV]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 49), metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[S]], i64 [[TMP8]]
; stress-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[WHILE_COND]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[WHILE_COND1:%.*]]
; stress:       while.cond:
; stress-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S]], [[WHILE_COND]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; stress-NEXT:    [[TMP10:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; stress-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP10]], 49
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; stress-NEXT:    br i1 [[CMP]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP18:![0-9]+]]
; stress:       while.end:
; stress-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; VLS-LABEL: @SingleBlock11(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[WHILE_COND:%.*]]
; VLS:       while.cond:
; VLS-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; VLS-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP0]], 49
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; VLS-NEXT:    br i1 [[CMP]], label [[WHILE_COND]], label [[WHILE_END:%.*]]
; VLS:       while.end:
; VLS-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND]] ]
; VLS-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; IF0-LABEL: @SingleBlock11(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[WHILE_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 [[EVL_BASED_IV]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 49), metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[S]], i64 [[TMP8]]
; IF0-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[WHILE_COND]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[WHILE_COND1:%.*]]
; IF0:       while.cond:
; IF0-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S]], [[WHILE_COND]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; IF0-NEXT:    [[TMP10:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; IF0-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP10]], 49
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; IF0-NEXT:    br i1 [[CMP]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP18:![0-9]+]]
; IF0:       while.end:
; IF0-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; IF1-LABEL: @SingleBlock11(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[WHILE_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 [[EVL_BASED_IV]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 49), metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[S]], i64 [[TMP8]]
; IF1-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[WHILE_COND]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[WHILE_COND1:%.*]]
; IF1:       while.cond:
; IF1-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S]], [[WHILE_COND]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; IF1-NEXT:    [[TMP10:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; IF1-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP10]], 49
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; IF1-NEXT:    br i1 [[CMP]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP18:![0-9]+]]
; IF1:       while.end:
; IF1-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
; IF2-LABEL: @SingleBlock11(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[WHILE_COND:%.*]], label [[VECTOR_PH:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 [[EVL_BASED_IV]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> splat (i8 49), metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[S]], i64 [[TMP8]]
; IF2-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[WHILE_COND]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[WHILE_COND1:%.*]]
; IF2:       while.cond:
; IF2-NEXT:    [[S_ADDR_0:%.*]] = phi ptr [ [[S]], [[WHILE_COND]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; IF2-NEXT:    [[TMP10:%.*]] = load i8, ptr [[S_ADDR_0]], align 1
; IF2-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP10]], 49
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[S_ADDR_0]], i64 1
; IF2-NEXT:    br i1 [[CMP]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP18:![0-9]+]]
; IF2:       while.end:
; IF2-NEXT:    [[S_ADDR_0_LCSSA:%.*]] = phi ptr [ [[S_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    ret ptr [[S_ADDR_0_LCSSA]]
;
entry:
  br label %while.cond

while.cond:
  %s.addr.0 = phi ptr [ %s, %entry ], [ %incdec.ptr, %while.cond ]
  %0 = load i8, ptr %s.addr.0, align 1
  %cmp = icmp eq i8 %0, 49
  %incdec.ptr = getelementptr inbounds i8, ptr %s.addr.0, i64 1
  br i1 %cmp, label %while.cond, label %while.end

while.end:
  %s.addr.0.lcssa = phi ptr [ %s.addr.0, %while.cond ]
  ret ptr %s.addr.0.lcssa
}

; Test reduction
define i8 @SingleBlock12(ptr %start) {
; DEFAULT-LABEL: @SingleBlock12(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_BODY:%.*]]
; DEFAULT:       for.body:
; DEFAULT-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; DEFAULT-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; DEFAULT-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; DEFAULT:       for.end.loopexit:
; DEFAULT-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; DEFAULT-NEXT:    ret i8 [[ADD_LCSSA]]
;
; ON-LABEL: @SingleBlock12(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_BODY:%.*]]
; ON:       for.body:
; ON-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; ON-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; ON-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; ON:       for.end.loopexit:
; ON-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; ON-NEXT:    ret i8 [[ADD_LCSSA]]
;
; OFF-LABEL: @SingleBlock12(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_BODY:%.*]]
; OFF:       for.body:
; OFF-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; OFF-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; OFF-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; OFF:       for.end.loopexit:
; OFF-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; OFF-NEXT:    ret i8 [[ADD_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock12(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_BODY:%.*]]
; ANALYSIS-ONLY:       for.body:
; ANALYSIS-ONLY-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; ANALYSIS-ONLY-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; ANALYSIS-ONLY:       for.end.loopexit:
; ANALYSIS-ONLY-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; ANALYSIS-ONLY-NEXT:    ret i8 [[ADD_LCSSA]]
;
; stress-LABEL: @SingleBlock12(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_BODY:%.*]]
; stress:       for.body:
; stress-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; stress-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; stress-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; stress:       for.end.loopexit:
; stress-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; stress-NEXT:    ret i8 [[ADD_LCSSA]]
;
; VLS-LABEL: @SingleBlock12(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_BODY:%.*]]
; VLS:       for.body:
; VLS-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; VLS-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; VLS-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; VLS:       for.end.loopexit:
; VLS-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; VLS-NEXT:    ret i8 [[ADD_LCSSA]]
;
; IF0-LABEL: @SingleBlock12(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_BODY:%.*]]
; IF0:       for.body:
; IF0-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; IF0-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; IF0-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF0:       for.end.loopexit:
; IF0-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; IF0-NEXT:    ret i8 [[ADD_LCSSA]]
;
; IF1-LABEL: @SingleBlock12(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_BODY:%.*]]
; IF1:       for.body:
; IF1-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; IF1-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; IF1-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF1:       for.end.loopexit:
; IF1-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; IF1-NEXT:    ret i8 [[ADD_LCSSA]]
;
; IF2-LABEL: @SingleBlock12(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_BODY:%.*]]
; IF2:       for.body:
; IF2-NEXT:    [[END:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY:%.*]] ]
; IF2-NEXT:    [[SUM:%.*]] = phi i8 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[END]], i64 1
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; IF2-NEXT:    [[ADD]] = add i8 [[TMP0]], [[SUM]]
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF2:       for.end.loopexit:
; IF2-NEXT:    [[ADD_LCSSA:%.*]] = phi i8 [ [[ADD]], [[FOR_BODY]] ]
; IF2-NEXT:    ret i8 [[ADD_LCSSA]]
;
entry:
  br label %for.body

for.body:
  %end = phi ptr [ %incdec.ptr, %for.body ], [ %start, %entry ]
  %sum = phi i8 [ %add, %for.body ], [ 0, %entry ]
  %incdec.ptr = getelementptr inbounds i8, ptr %end, i64 1
  %0 = load i8, ptr %incdec.ptr, align 1
  %add = add i8 %0, %sum
  %cmp.not = icmp eq i8 %0, 0
  br i1 %cmp.not, label %for.end.loopexit, label %for.body

for.end.loopexit:
  %add.lcssa = phi i8 [ %add, %for.body ]
  ret i8 %add.lcssa
}

; Test independent loads in speculative regions
define ptr @SingleBlock13(ptr %start, ptr %p) {
; DEFAULT-LABEL: @SingleBlock13(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; DEFAULT-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; DEFAULT-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; DEFAULT:       for.body.preheader:
; DEFAULT-NEXT:    br label [[FOR_BODY:%.*]]
; DEFAULT:       for.body:
; DEFAULT-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; DEFAULT-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; DEFAULT-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; DEFAULT-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; DEFAULT-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; DEFAULT-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; DEFAULT-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; DEFAULT:       for.end.loopexit:
; DEFAULT-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; DEFAULT-NEXT:    br label [[FOR_END]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; DEFAULT-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; ON-LABEL: @SingleBlock13(
; ON-NEXT:  entry:
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; ON-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; ON-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; ON:       for.body.preheader:
; ON-NEXT:    br label [[FOR_BODY:%.*]]
; ON:       for.body:
; ON-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; ON-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; ON-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; ON-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; ON-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; ON-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; ON-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; ON:       for.end.loopexit:
; ON-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; ON-NEXT:    br label [[FOR_END]]
; ON:       for.end:
; ON-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; ON-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; OFF-LABEL: @SingleBlock13(
; OFF-NEXT:  entry:
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; OFF-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; OFF:       for.body.preheader:
; OFF-NEXT:    br label [[FOR_BODY:%.*]]
; OFF:       for.body:
; OFF-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; OFF-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; OFF-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; OFF-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; OFF-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; OFF-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; OFF-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; OFF:       for.end.loopexit:
; OFF-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; OFF-NEXT:    br label [[FOR_END]]
; OFF:       for.end:
; OFF-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; OFF-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock13(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; ANALYSIS-ONLY:       for.body.preheader:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_BODY:%.*]]
; ANALYSIS-ONLY:       for.body:
; ANALYSIS-ONLY-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; ANALYSIS-ONLY-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; ANALYSIS-ONLY-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; ANALYSIS-ONLY-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; ANALYSIS-ONLY-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; ANALYSIS-ONLY:       for.end.loopexit:
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; ANALYSIS-ONLY-NEXT:    br label [[FOR_END]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; stress-LABEL: @SingleBlock13(
; stress-NEXT:  entry:
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; stress-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; stress-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; stress:       for.body.preheader:
; stress-NEXT:    br label [[FOR_BODY:%.*]]
; stress:       for.body:
; stress-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; stress-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; stress-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; stress-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; stress-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; stress-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; stress-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; stress:       for.end.loopexit:
; stress-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; stress-NEXT:    br label [[FOR_END]]
; stress:       for.end:
; stress-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; stress-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; VLS-LABEL: @SingleBlock13(
; VLS-NEXT:  entry:
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; VLS-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; VLS:       for.body.preheader:
; VLS-NEXT:    br label [[FOR_BODY:%.*]]
; VLS:       for.body:
; VLS-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; VLS-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; VLS-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; VLS-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; VLS-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; VLS-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; VLS-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; VLS:       for.end.loopexit:
; VLS-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; VLS-NEXT:    br label [[FOR_END]]
; VLS:       for.end:
; VLS-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; VLS-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; IF0-LABEL: @SingleBlock13(
; IF0-NEXT:  entry:
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; IF0-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; IF0-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; IF0:       for.body.preheader:
; IF0-NEXT:    br label [[FOR_BODY:%.*]]
; IF0:       for.body:
; IF0-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; IF0-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; IF0-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; IF0-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; IF0-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; IF0-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; IF0-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF0:       for.end.loopexit:
; IF0-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; IF0-NEXT:    br label [[FOR_END]]
; IF0:       for.end:
; IF0-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; IF0-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; IF1-LABEL: @SingleBlock13(
; IF1-NEXT:  entry:
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; IF1-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; IF1-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; IF1:       for.body.preheader:
; IF1-NEXT:    br label [[FOR_BODY:%.*]]
; IF1:       for.body:
; IF1-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; IF1-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; IF1-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; IF1-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; IF1-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; IF1-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; IF1-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF1:       for.end.loopexit:
; IF1-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; IF1-NEXT:    br label [[FOR_END]]
; IF1:       for.end:
; IF1-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; IF1-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
; IF2-LABEL: @SingleBlock13(
; IF2-NEXT:  entry:
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[START:%.*]], align 1
; IF2-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i8 [[TMP0]], 0
; IF2-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; IF2:       for.body.preheader:
; IF2-NEXT:    br label [[FOR_BODY:%.*]]
; IF2:       for.body:
; IF2-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[FOR_BODY_PREHEADER]] ]
; IF2-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR3:%.*]], [[FOR_BODY]] ], [ [[START]], [[FOR_BODY_PREHEADER]] ]
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 1
; IF2-NEXT:    [[TMP1:%.*]] = load i8, ptr [[P_ADDR]], align 1
; IF2-NEXT:    [[ADD:%.*]] = add i8 [[TMP1]], 1
; IF2-NEXT:    store i8 [[ADD]], ptr [[P_ADDR]], align 1
; IF2-NEXT:    [[INCDEC_PTR3]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; IF2-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP2]], 0
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF2:       for.end.loopexit:
; IF2-NEXT:    [[INCDEC_PTR3_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR3]], [[FOR_BODY]] ]
; IF2-NEXT:    br label [[FOR_END]]
; IF2:       for.end:
; IF2-NEXT:    [[START_ADDR_0_LCSSA:%.*]] = phi ptr [ [[START]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR3_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; IF2-NEXT:    ret ptr [[START_ADDR_0_LCSSA]]
;
entry:
  %0 = load i8, ptr %start, align 1
  %cmp.not6 = icmp eq i8 %0, 0
  br i1 %cmp.not6, label %for.end, label %for.body.preheader

for.body.preheader:
  br label %for.body

for.body:
  %p.addr = phi ptr [ %incdec.ptr, %for.body ], [ %p, %for.body.preheader ]
  %start.addr = phi ptr [ %incdec.ptr3, %for.body ], [ %start, %for.body.preheader ]
  %incdec.ptr = getelementptr inbounds i8, ptr %p.addr, i64 1
  %1 = load i8, ptr %p.addr, align 1
  %add = add i8 %1, 1
  store i8 %add, ptr %p.addr, align 1
  %incdec.ptr3 = getelementptr inbounds i8, ptr %start.addr, i64 1
  %2 = load i8, ptr %incdec.ptr3, align 1
  %cmp.not = icmp eq i8 %2, 0
  br i1 %cmp.not, label %for.end.loopexit, label %for.body

for.end.loopexit:
  %incdec.ptr3.lcssa = phi ptr [ %incdec.ptr3, %for.body ]
  br label %for.end

for.end:
  %start.addr.0.lcssa = phi ptr [ %start, %entry ], [ %incdec.ptr3.lcssa, %for.end.loopexit ]
  ret ptr %start.addr.0.lcssa
}

; Test branches with static constant conditions
define i32 @SingleBlock14(ptr %start) {
; DEFAULT-LABEL: @SingleBlock14(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; DEFAULT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; DEFAULT-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; DEFAULT-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; DEFAULT-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; DEFAULT-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; DEFAULT-NEXT:    ret i32 [[TMP1]]
;
; ON-LABEL: @SingleBlock14(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; ON-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ON-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ON-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; ON-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ON-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       for.end:
; ON-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; ON-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ON-NEXT:    ret i32 [[TMP1]]
;
; OFF-LABEL: @SingleBlock14(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; OFF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; OFF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; OFF-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; OFF-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; OFF-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; OFF-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; OFF-NEXT:    ret i32 [[TMP1]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock14(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; ANALYSIS-ONLY-NEXT:    ret i32 [[TMP1]]
;
; stress-LABEL: @SingleBlock14(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; stress-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; stress-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; stress-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; stress-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; stress-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       for.end:
; stress-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; stress-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; stress-NEXT:    ret i32 [[TMP1]]
;
; VLS-LABEL: @SingleBlock14(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; VLS-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; VLS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VLS-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; VLS-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; VLS-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; VLS-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; VLS-NEXT:    ret i32 [[TMP1]]
;
; IF0-LABEL: @SingleBlock14(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; IF0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF0-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; IF0-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF0-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       for.end:
; IF0-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; IF0-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF0-NEXT:    ret i32 [[TMP1]]
;
; IF1-LABEL: @SingleBlock14(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; IF1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF1-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF1-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; IF1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF1-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       for.end:
; IF1-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; IF1-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF1-NEXT:    ret i32 [[TMP1]]
;
; IF2-LABEL: @SingleBlock14(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_COND]] ], [ 0, [[ENTRY:%.*]] ]
; IF2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 [[INDVARS_IV]]
; IF2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF2-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 0, 0
; IF2-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i64 [[INDVARS_IV]], 1
; IF2-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       for.end:
; IF2-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[FOR_COND]] ]
; IF2-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV_LCSSA]] to i32
; IF2-NEXT:    ret i32 [[TMP1]]
;
entry:
  br label %for.cond

for.cond:
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.cond ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i32, ptr %start, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx, align 4
  %cmp.cond = icmp eq i32 0, 0
  %indvars.iv.next = add nuw i64 %indvars.iv, 1
  br i1 %cmp.cond, label %for.end, label %for.cond

for.end:
  %indvars.iv.lcssa = phi i64 [ %indvars.iv.next, %for.cond ]
  %1 = trunc i64 %indvars.iv.lcssa to i32
  ret i32 %1
}

; Test live outs not from an uncountable IV
define ptr @SingleBlock15(ptr %start.1, ptr %start.2, ptr %end) {
; DEFAULT-LABEL: @SingleBlock15(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; DEFAULT-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; DEFAULT-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; DEFAULT-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; DEFAULT-NEXT:    ret ptr [[RES_LCSSA]]
;
; ON-LABEL: @SingleBlock15(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; ON-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ON-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; ON-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; ON:       exit:
; ON-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; ON-NEXT:    ret ptr [[RES_LCSSA]]
;
; OFF-LABEL: @SingleBlock15(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; OFF-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; OFF-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; OFF:       exit:
; OFF-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; OFF-NEXT:    ret ptr [[RES_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock15(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[LOOP:%.*]]
; ANALYSIS-ONLY:       loop:
; ANALYSIS-ONLY-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; ANALYSIS-ONLY-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; ANALYSIS-ONLY:       exit:
; ANALYSIS-ONLY-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[RES_LCSSA]]
;
; stress-LABEL: @SingleBlock15(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[LOOP:%.*]]
; stress:       loop:
; stress-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; stress-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; stress-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; stress-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; stress:       exit:
; stress-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; stress-NEXT:    ret ptr [[RES_LCSSA]]
;
; VLS-LABEL: @SingleBlock15(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[LOOP:%.*]]
; VLS:       loop:
; VLS-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; VLS-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; VLS-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; VLS:       exit:
; VLS-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; VLS-NEXT:    ret ptr [[RES_LCSSA]]
;
; IF0-LABEL: @SingleBlock15(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[LOOP:%.*]]
; IF0:       loop:
; IF0-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; IF0-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF0-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; IF0-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; IF0:       exit:
; IF0-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; IF0-NEXT:    ret ptr [[RES_LCSSA]]
;
; IF1-LABEL: @SingleBlock15(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[LOOP:%.*]]
; IF1:       loop:
; IF1-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; IF1-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF1-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; IF1-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; IF1:       exit:
; IF1-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; IF1-NEXT:    ret ptr [[RES_LCSSA]]
;
; IF2-LABEL: @SingleBlock15(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[LOOP:%.*]]
; IF2:       loop:
; IF2-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; IF2-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF2-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; IF2-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; IF2:       exit:
; IF2-NEXT:    [[RES_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; IF2-NEXT:    ret ptr [[RES_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv.1 = phi ptr [ %start.1, %entry ], [ %iv.1.next, %loop ]
  %iv.2 = phi ptr [ %start.2, %entry ], [ %iv.2.next, %loop ]
  %0 = load i8, ptr %iv.2, align 1
  %cmp.not = icmp eq i8 %0, 0
  %iv.2.next = getelementptr inbounds ptr, ptr %iv.2, i64 1
  %iv.1.next = getelementptr inbounds ptr, ptr %iv.1, i64 1
  br i1 %cmp.not, label %exit, label %loop

exit:
  %res.lcssa = phi ptr [ %iv.1, %loop ]
  ret ptr %res.lcssa
}

; TODO: Test multiple live outs
define ptr @SingleBlock16(ptr %start.1, ptr %start.2, ptr %end) {
; DEFAULT-LABEL: @SingleBlock16(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; DEFAULT-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; DEFAULT-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; DEFAULT-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; DEFAULT-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; DEFAULT-NEXT:    ret ptr [[RES1_LCSSA]]
;
; ON-LABEL: @SingleBlock16(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; ON-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ON-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; ON-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; ON-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; ON:       exit:
; ON-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; ON-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; ON-NEXT:    ret ptr [[RES1_LCSSA]]
;
; OFF-LABEL: @SingleBlock16(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; OFF-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; OFF-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; OFF-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; OFF:       exit:
; OFF-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; OFF-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; OFF-NEXT:    ret ptr [[RES1_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock16(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[LOOP:%.*]]
; ANALYSIS-ONLY:       loop:
; ANALYSIS-ONLY-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; ANALYSIS-ONLY-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; ANALYSIS-ONLY:       exit:
; ANALYSIS-ONLY-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[RES1_LCSSA]]
;
; stress-LABEL: @SingleBlock16(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[LOOP:%.*]]
; stress:       loop:
; stress-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; stress-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; stress-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; stress-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; stress-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; stress:       exit:
; stress-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; stress-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; stress-NEXT:    ret ptr [[RES1_LCSSA]]
;
; VLS-LABEL: @SingleBlock16(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[LOOP:%.*]]
; VLS:       loop:
; VLS-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; VLS-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; VLS-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; VLS-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; VLS:       exit:
; VLS-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; VLS-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; VLS-NEXT:    ret ptr [[RES1_LCSSA]]
;
; IF0-LABEL: @SingleBlock16(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[LOOP:%.*]]
; IF0:       loop:
; IF0-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; IF0-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF0-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; IF0-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; IF0:       exit:
; IF0-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; IF0-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; IF0-NEXT:    ret ptr [[RES1_LCSSA]]
;
; IF1-LABEL: @SingleBlock16(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[LOOP:%.*]]
; IF1:       loop:
; IF1-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; IF1-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF1-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; IF1-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; IF1:       exit:
; IF1-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; IF1-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; IF1-NEXT:    ret ptr [[RES1_LCSSA]]
;
; IF2-LABEL: @SingleBlock16(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[LOOP:%.*]]
; IF2:       loop:
; IF2-NEXT:    [[IV_1:%.*]] = phi ptr [ [[START_1:%.*]], [[ENTRY:%.*]] ], [ [[IV_1_NEXT:%.*]], [[LOOP]] ]
; IF2-NEXT:    [[IV_2:%.*]] = phi ptr [ [[START_2:%.*]], [[ENTRY]] ], [ [[IV_2_NEXT:%.*]], [[LOOP]] ]
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IV_2]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; IF2-NEXT:    [[IV_2_NEXT]] = getelementptr inbounds ptr, ptr [[IV_2]], i64 1
; IF2-NEXT:    [[IV_1_NEXT]] = getelementptr inbounds ptr, ptr [[IV_1]], i64 1
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[EXIT:%.*]], label [[LOOP]]
; IF2:       exit:
; IF2-NEXT:    [[RES1_LCSSA:%.*]] = phi ptr [ [[IV_1]], [[LOOP]] ]
; IF2-NEXT:    [[RES2_LCSSA:%.*]] = phi ptr [ [[IV_2]], [[LOOP]] ]
; IF2-NEXT:    ret ptr [[RES1_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv.1 = phi ptr [ %start.1, %entry ], [ %iv.1.next, %loop ]
  %iv.2 = phi ptr [ %start.2, %entry ], [ %iv.2.next, %loop ]
  %0 = load i8, ptr %iv.2, align 1
  %cmp.not = icmp eq i8 %0, 0
  %iv.2.next = getelementptr inbounds ptr, ptr %iv.2, i64 1
  %iv.1.next = getelementptr inbounds ptr, ptr %iv.1, i64 1
  br i1 %cmp.not, label %exit, label %loop

exit:
  %res1.lcssa = phi ptr [ %iv.1, %loop ]
  %res2.lcssa = phi ptr [ %iv.2, %loop ]
  ret ptr %res1.lcssa
}

; Test no header phi
define ptr @SingleBlock17(ptr %start, ptr %end) {
; DEFAULT-LABEL: @SingleBlock17(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_COND:%.*]]
; DEFAULT:       for.cond:
; DEFAULT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; DEFAULT-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; DEFAULT-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; DEFAULT:       for.end:
; DEFAULT-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; DEFAULT-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; ON-LABEL: @SingleBlock17(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_COND:%.*]]
; ON:       for.cond:
; ON-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; ON-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ON-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; ON-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ON:       for.end:
; ON-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; ON-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; OFF-LABEL: @SingleBlock17(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_COND:%.*]]
; OFF:       for.cond:
; OFF-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; OFF-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; OFF-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; OFF-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; OFF:       for.end:
; OFF-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; OFF-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock17(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_COND:%.*]]
; ANALYSIS-ONLY:       for.cond:
; ANALYSIS-ONLY-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; ANALYSIS-ONLY-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; ANALYSIS-ONLY:       for.end:
; ANALYSIS-ONLY-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; stress-LABEL: @SingleBlock17(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_COND:%.*]]
; stress:       for.cond:
; stress-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; stress-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; stress-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; stress-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; stress:       for.end:
; stress-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; stress-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; VLS-LABEL: @SingleBlock17(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_COND:%.*]]
; VLS:       for.cond:
; VLS-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; VLS-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VLS-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; VLS-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; VLS:       for.end:
; VLS-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; VLS-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; IF0-LABEL: @SingleBlock17(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_COND:%.*]]
; IF0:       for.cond:
; IF0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; IF0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF0-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; IF0-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF0:       for.end:
; IF0-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; IF0-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; IF1-LABEL: @SingleBlock17(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_COND:%.*]]
; IF1:       for.cond:
; IF1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; IF1-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF1-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; IF1-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF1:       for.end:
; IF1-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; IF1-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
; IF2-LABEL: @SingleBlock17(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_COND:%.*]]
; IF2:       for.cond:
; IF2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[START:%.*]], i64 0
; IF2-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; IF2-NEXT:    [[CMP_COND:%.*]] = icmp eq i32 [[TMP0]], 0
; IF2-NEXT:    br i1 [[CMP_COND]], label [[FOR_END:%.*]], label [[FOR_COND]]
; IF2:       for.end:
; IF2-NEXT:    [[INDVARS_IV_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX]], [[FOR_COND]] ]
; IF2-NEXT:    ret ptr [[INDVARS_IV_LCSSA]]
;
entry:
  br label %for.cond

for.cond:
  %arrayidx = getelementptr inbounds i32, ptr %start, i64 0
  %0 = load i32, ptr %arrayidx, align 4
  %cmp.cond = icmp eq i32 %0, 0
  br i1 %cmp.cond, label %for.end, label %for.cond

for.end:
  %indvars.iv.lcssa = phi ptr [ %arrayidx, %for.cond ]
  ret ptr %indvars.iv.lcssa
}

; Test select
define ptr @SingleBlock18(ptr %start, ptr %p) {
; DEFAULT-LABEL: @SingleBlock18(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[FOR_BODY:%.*]]
; DEFAULT:       for.body:
; DEFAULT-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; DEFAULT-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; DEFAULT-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; DEFAULT-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; DEFAULT-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; DEFAULT-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; DEFAULT-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; DEFAULT-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; DEFAULT:       for.end.loopexit:
; DEFAULT-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; DEFAULT-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; ON-LABEL: @SingleBlock18(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[FOR_BODY:%.*]]
; ON:       for.body:
; ON-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; ON-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; ON-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; ON-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; ON-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; ON-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; ON-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; ON-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; ON-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; ON:       for.end.loopexit:
; ON-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; ON-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; OFF-LABEL: @SingleBlock18(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[FOR_BODY:%.*]]
; OFF:       for.body:
; OFF-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; OFF-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; OFF-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; OFF-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; OFF-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; OFF-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; OFF-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; OFF-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; OFF:       for.end.loopexit:
; OFF-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; OFF-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock18(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[FOR_BODY:%.*]]
; ANALYSIS-ONLY:       for.body:
; ANALYSIS-ONLY-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; ANALYSIS-ONLY-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; ANALYSIS-ONLY-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; ANALYSIS-ONLY-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; ANALYSIS-ONLY:       for.end.loopexit:
; ANALYSIS-ONLY-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; stress-LABEL: @SingleBlock18(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[FOR_BODY:%.*]]
; stress:       for.body:
; stress-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; stress-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; stress-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; stress-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; stress-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; stress-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; stress-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; stress-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; stress-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; stress:       for.end.loopexit:
; stress-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; stress-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; VLS-LABEL: @SingleBlock18(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[FOR_BODY:%.*]]
; VLS:       for.body:
; VLS-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; VLS-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; VLS-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; VLS-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; VLS-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; VLS-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; VLS-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; VLS-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; VLS:       for.end.loopexit:
; VLS-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; VLS-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; IF0-LABEL: @SingleBlock18(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[FOR_BODY:%.*]]
; IF0:       for.body:
; IF0-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; IF0-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; IF0-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; IF0-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; IF0-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; IF0-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; IF0-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; IF0-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; IF0-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF0:       for.end.loopexit:
; IF0-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; IF0-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; IF1-LABEL: @SingleBlock18(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[FOR_BODY:%.*]]
; IF1:       for.body:
; IF1-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; IF1-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; IF1-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; IF1-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; IF1-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; IF1-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; IF1-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; IF1-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; IF1-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF1:       for.end.loopexit:
; IF1-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; IF1-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
; IF2-LABEL: @SingleBlock18(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[FOR_BODY:%.*]]
; IF2:       for.body:
; IF2-NEXT:    [[P_ADDR:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ], [ [[P:%.*]], [[ENTRY:%.*]] ]
; IF2-NEXT:    [[START_ADDR:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], [[FOR_BODY]] ], [ [[START:%.*]], [[ENTRY]] ]
; IF2-NEXT:    [[TMP0:%.*]] = load i8, ptr [[P_ADDR]], align 1
; IF2-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[TMP0]], 49
; IF2-NEXT:    [[IDX_EXT:%.*]] = select i1 [[CMP2]], i64 1, i64 2
; IF2-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[P_ADDR]], i64 [[IDX_EXT]]
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[START_ADDR]], i64 1
; IF2-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; IF2-NEXT:    [[CMP_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; IF2-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; IF2:       for.end.loopexit:
; IF2-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR]], [[FOR_BODY]] ]
; IF2-NEXT:    ret ptr [[ADD_PTR_LCSSA]]
;
entry:
  br label %for.body

for.body:
  %p.addr = phi ptr [ %add.ptr, %for.body ], [ %p, %entry ]
  %start.addr = phi ptr [ %incdec.ptr, %for.body ], [ %start, %entry ]
  %0 = load i8, ptr %p.addr, align 1
  %cmp2 = icmp eq i8 %0, 49
  %idx.ext = select i1 %cmp2, i64 1, i64 2
  %add.ptr = getelementptr inbounds i8, ptr %p.addr, i64 %idx.ext
  %incdec.ptr = getelementptr inbounds i8, ptr %start.addr, i64 1
  %1 = load i8, ptr %incdec.ptr, align 1
  %cmp.not = icmp eq i8 %1, 0
  br i1 %cmp.not, label %for.end.loopexit, label %for.body

for.end.loopexit:
  %add.ptr.lcssa = phi ptr [ %add.ptr, %for.body ]
  ret ptr %add.ptr.lcssa
}

; Test composite conditions
define ptr @SingleBlock19(ptr %src, i8 %N) {
; DEFAULT-LABEL: @SingleBlock19(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 32 x i8> poison, i8 [[N:%.*]], i64 0
; DEFAULT-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 32 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 32 x i8> poison, <vscale x 32 x i32> zeroinitializer
; DEFAULT-NEXT:    br label [[WHILE_COND:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[WHILE_COND]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[WHILE_COND]] ]
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; DEFAULT-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC:%.*]], i64 [[EVL_BASED_IV]]
; DEFAULT-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; DEFAULT-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[VP_OP_ICMP1:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i1> @llvm.vp.and.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> [[VP_OP_ICMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 32 x i1> @llvm.vp.xor.nxv32i1(<vscale x 32 x i1> [[VP_OP]], <vscale x 32 x i1> splat (i1 true), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[PRED_NOT]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; DEFAULT-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP19:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; DEFAULT-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; DEFAULT-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP8]]
; DEFAULT-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[WHILE_COND1:%.*]]
; DEFAULT:       while.cond:
; DEFAULT-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; DEFAULT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; DEFAULT-NEXT:    [[TMP10:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; DEFAULT-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP10]], [[N]]
; DEFAULT-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP10]], 0
; DEFAULT-NEXT:    [[TMP11:%.*]] = and i1 [[CMP]], [[CMP3]]
; DEFAULT-NEXT:    br i1 [[TMP11]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP20:![0-9]+]]
; DEFAULT:       while.end:
; DEFAULT-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    ret ptr [[DOTLCSSA]]
;
; ON-LABEL: @SingleBlock19(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; ON:       vector.ph:
; ON-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 32 x i8> poison, i8 [[N:%.*]], i64 0
; ON-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 32 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 32 x i8> poison, <vscale x 32 x i32> zeroinitializer
; ON-NEXT:    br label [[WHILE_COND:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[WHILE_COND]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[WHILE_COND]] ]
; ON-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; ON-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC:%.*]], i64 [[EVL_BASED_IV]]
; ON-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; ON-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[VP_OP_ICMP1:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i1> @llvm.vp.and.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> [[VP_OP_ICMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 32 x i1> @llvm.vp.xor.nxv32i1(<vscale x 32 x i1> [[VP_OP]], <vscale x 32 x i1> splat (i1 true), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[PRED_NOT]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; ON-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; ON-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP19:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; ON-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; ON-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP8]]
; ON-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[WHILE_COND1:%.*]]
; ON:       while.cond:
; ON-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; ON-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; ON-NEXT:    [[TMP10:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; ON-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP10]], [[N]]
; ON-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP10]], 0
; ON-NEXT:    [[TMP11:%.*]] = and i1 [[CMP]], [[CMP3]]
; ON-NEXT:    br i1 [[TMP11]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP20:![0-9]+]]
; ON:       while.end:
; ON-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    ret ptr [[DOTLCSSA]]
;
; OFF-LABEL: @SingleBlock19(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[WHILE_COND:%.*]]
; OFF:       while.cond:
; OFF-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND]] ]
; OFF-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; OFF-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; OFF-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP0]], [[N:%.*]]
; OFF-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP0]], 0
; OFF-NEXT:    [[TMP1:%.*]] = and i1 [[CMP]], [[CMP3]]
; OFF-NEXT:    br i1 [[TMP1]], label [[WHILE_COND]], label [[WHILE_END:%.*]]
; OFF:       while.end:
; OFF-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND]] ]
; OFF-NEXT:    ret ptr [[DOTLCSSA]]
;
; ANALYSIS-ONLY-LABEL: @SingleBlock19(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[WHILE_COND:%.*]]
; ANALYSIS-ONLY:       while.cond:
; ANALYSIS-ONLY-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND]] ]
; ANALYSIS-ONLY-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; ANALYSIS-ONLY-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; ANALYSIS-ONLY-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP0]], [[N:%.*]]
; ANALYSIS-ONLY-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP0]], 0
; ANALYSIS-ONLY-NEXT:    [[TMP1:%.*]] = and i1 [[CMP]], [[CMP3]]
; ANALYSIS-ONLY-NEXT:    br i1 [[TMP1]], label [[WHILE_COND]], label [[WHILE_END:%.*]]
; ANALYSIS-ONLY:       while.end:
; ANALYSIS-ONLY-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND]] ]
; ANALYSIS-ONLY-NEXT:    ret ptr [[DOTLCSSA]]
;
; stress-LABEL: @SingleBlock19(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; stress:       vector.ph:
; stress-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 32 x i8> poison, i8 [[N:%.*]], i64 0
; stress-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 32 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 32 x i8> poison, <vscale x 32 x i32> zeroinitializer
; stress-NEXT:    br label [[WHILE_COND:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[WHILE_COND]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[WHILE_COND]] ]
; stress-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; stress-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC:%.*]], i64 [[EVL_BASED_IV]]
; stress-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; stress-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[VP_OP_ICMP1:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i1> @llvm.vp.and.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> [[VP_OP_ICMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 32 x i1> @llvm.vp.xor.nxv32i1(<vscale x 32 x i1> [[VP_OP]], <vscale x 32 x i1> splat (i1 true), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[PRED_NOT]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; stress-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; stress-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP19:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; stress-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; stress-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP8]]
; stress-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[WHILE_COND1:%.*]]
; stress:       while.cond:
; stress-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; stress-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; stress-NEXT:    [[TMP10:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; stress-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP10]], [[N]]
; stress-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP10]], 0
; stress-NEXT:    [[TMP11:%.*]] = and i1 [[CMP]], [[CMP3]]
; stress-NEXT:    br i1 [[TMP11]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP20:![0-9]+]]
; stress:       while.end:
; stress-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    ret ptr [[DOTLCSSA]]
;
; VLS-LABEL: @SingleBlock19(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[WHILE_COND:%.*]]
; VLS:       while.cond:
; VLS-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC:%.*]], [[ENTRY:%.*]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND]] ]
; VLS-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; VLS-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; VLS-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP0]], [[N:%.*]]
; VLS-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP0]], 0
; VLS-NEXT:    [[TMP1:%.*]] = and i1 [[CMP]], [[CMP3]]
; VLS-NEXT:    br i1 [[TMP1]], label [[WHILE_COND]], label [[WHILE_END:%.*]]
; VLS:       while.end:
; VLS-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND]] ]
; VLS-NEXT:    ret ptr [[DOTLCSSA]]
;
; IF0-LABEL: @SingleBlock19(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 32 x i8> poison, i8 [[N:%.*]], i64 0
; IF0-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 32 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 32 x i8> poison, <vscale x 32 x i32> zeroinitializer
; IF0-NEXT:    br label [[WHILE_COND:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[WHILE_COND]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[WHILE_COND]] ]
; IF0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF0-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC:%.*]], i64 [[EVL_BASED_IV]]
; IF0-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF0-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[VP_OP_ICMP1:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i1> @llvm.vp.and.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> [[VP_OP_ICMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 32 x i1> @llvm.vp.xor.nxv32i1(<vscale x 32 x i1> [[VP_OP]], <vscale x 32 x i1> splat (i1 true), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[PRED_NOT]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF0-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF0-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP19:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF0-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF0-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP8]]
; IF0-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[WHILE_COND1:%.*]]
; IF0:       while.cond:
; IF0-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; IF0-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; IF0-NEXT:    [[TMP10:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; IF0-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP10]], [[N]]
; IF0-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP10]], 0
; IF0-NEXT:    [[TMP11:%.*]] = and i1 [[CMP]], [[CMP3]]
; IF0-NEXT:    br i1 [[TMP11]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP20:![0-9]+]]
; IF0:       while.end:
; IF0-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    ret ptr [[DOTLCSSA]]
;
; IF1-LABEL: @SingleBlock19(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 32 x i8> poison, i8 [[N:%.*]], i64 0
; IF1-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 32 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 32 x i8> poison, <vscale x 32 x i32> zeroinitializer
; IF1-NEXT:    br label [[WHILE_COND:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[WHILE_COND]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[WHILE_COND]] ]
; IF1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF1-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC:%.*]], i64 [[EVL_BASED_IV]]
; IF1-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF1-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[VP_OP_ICMP1:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i1> @llvm.vp.and.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> [[VP_OP_ICMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 32 x i1> @llvm.vp.xor.nxv32i1(<vscale x 32 x i1> [[VP_OP]], <vscale x 32 x i1> splat (i1 true), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[PRED_NOT]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF1-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF1-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP19:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF1-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF1-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP8]]
; IF1-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[WHILE_COND1:%.*]]
; IF1:       while.cond:
; IF1-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; IF1-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; IF1-NEXT:    [[TMP10:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; IF1-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP10]], [[N]]
; IF1-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP10]], 0
; IF1-NEXT:    [[TMP11:%.*]] = and i1 [[CMP]], [[CMP3]]
; IF1-NEXT:    br i1 [[TMP11]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP20:![0-9]+]]
; IF1:       while.end:
; IF1-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    ret ptr [[DOTLCSSA]]
;
; IF2-LABEL: @SingleBlock19(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 32 x i8> poison, i8 [[N:%.*]], i64 0
; IF2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 32 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 32 x i8> poison, <vscale x 32 x i32> zeroinitializer
; IF2-NEXT:    br label [[WHILE_COND:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[WHILE_COND]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[WHILE_COND]] ]
; IF2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 32, i1 true)
; IF2-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[SRC:%.*]], i64 [[EVL_BASED_IV]]
; IF2-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 32 x i8>, i32 } @llvm.vp.load.ff.nxv32i8.p0(ptr align 1 [[TMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP0]])
; IF2-NEXT:    [[TMP2:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP3:%.*]] = extractvalue { <vscale x 32 x i8>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[VP_OP_ICMP1:%.*]] = call <vscale x 32 x i1> @llvm.vp.icmp.nxv32i8(<vscale x 32 x i8> [[TMP3]], <vscale x 32 x i8> zeroinitializer, metadata !"ne", <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[VP_OP:%.*]] = call <vscale x 32 x i1> @llvm.vp.and.nxv32i1(<vscale x 32 x i1> [[VP_OP_ICMP]], <vscale x 32 x i1> [[VP_OP_ICMP1]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 32 x i1> @llvm.vp.xor.nxv32i1(<vscale x 32 x i1> [[VP_OP]], <vscale x 32 x i1> splat (i1 true), <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP5:%.*]] = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> [[PRED_NOT]], <vscale x 32 x i1> splat (i1 true), i32 [[TMP2]])
; IF2-NEXT:    [[TMP6:%.*]] = icmp sge i32 [[TMP5]], 0
; IF2-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP2]] to i64
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[WHILE_COND]], !llvm.loop [[LOOP19:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP5]] to i64
; IF2-NEXT:    [[TMP8:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP7]]
; IF2-NEXT:    [[IND_ESCAPE:%.*]] = getelementptr i8, ptr [[SRC]], i64 [[TMP8]]
; IF2-NEXT:    br i1 true, label [[WHILE_END:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[WHILE_COND1:%.*]]
; IF2:       while.cond:
; IF2-NEXT:    [[SRC_ADDR_0:%.*]] = phi ptr [ [[SRC]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[WHILE_COND1]] ]
; IF2-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[SRC_ADDR_0]], i64 1
; IF2-NEXT:    [[TMP10:%.*]] = load i8, ptr [[SRC_ADDR_0]], align 1
; IF2-NEXT:    [[CMP:%.*]] = icmp ult i8 [[TMP10]], [[N]]
; IF2-NEXT:    [[CMP3:%.*]] = icmp ne i8 [[TMP10]], 0
; IF2-NEXT:    [[TMP11:%.*]] = and i1 [[CMP]], [[CMP3]]
; IF2-NEXT:    br i1 [[TMP11]], label [[WHILE_COND1]], label [[WHILE_END]], !llvm.loop [[LOOP20:![0-9]+]]
; IF2:       while.end:
; IF2-NEXT:    [[DOTLCSSA:%.*]] = phi ptr [ [[SRC_ADDR_0]], [[WHILE_COND1]] ], [ [[IND_ESCAPE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    ret ptr [[DOTLCSSA]]
;
entry:
  br label %while.cond

while.cond:
  %src.addr.0 = phi ptr [ %src, %entry ], [ %incdec.ptr, %while.cond ]
  %incdec.ptr = getelementptr inbounds i8, ptr %src.addr.0, i64 1
  %0 = load i8, ptr %src.addr.0, align 1
  %cmp = icmp ult i8 %0, %N
  %cmp3 = icmp ne i8 %0, 0
  %1 = and i1 %cmp, %cmp3
  br i1 %1, label %while.cond, label %while.end

while.end:
  %.lcssa = phi ptr [ %src.addr.0, %while.cond ]
  ret ptr %.lcssa
}

define i32 @strlen_i8_int_iv(ptr %start) {
; DEFAULT-LABEL: @strlen_i8_int_iv(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; DEFAULT-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; DEFAULT-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; DEFAULT-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; DEFAULT-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; DEFAULT-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; DEFAULT-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; DEFAULT-NEXT:    ret i32 [[IV_LCSSA]]
;
; ON-LABEL: @strlen_i8_int_iv(
; ON-NEXT:  entry:
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; ON-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; ON-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; ON-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; ON-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; ON-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; ON-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; ON:       exit:
; ON-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; ON-NEXT:    ret i32 [[IV_LCSSA]]
;
; OFF-LABEL: @strlen_i8_int_iv(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[ENTRY:%.*]] ]
; OFF-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; OFF-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; OFF-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; OFF-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; OFF-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; OFF-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; OFF:       exit:
; OFF-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; OFF-NEXT:    ret i32 [[IV_LCSSA]]
;
; ANALYSIS-ONLY-LABEL: @strlen_i8_int_iv(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[LOOP:%.*]]
; ANALYSIS-ONLY:       loop:
; ANALYSIS-ONLY-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; ANALYSIS-ONLY-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; ANALYSIS-ONLY-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; ANALYSIS-ONLY-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; ANALYSIS-ONLY-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; ANALYSIS-ONLY-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; ANALYSIS-ONLY:       exit:
; ANALYSIS-ONLY-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    ret i32 [[IV_LCSSA]]
;
; stress-LABEL: @strlen_i8_int_iv(
; stress-NEXT:  entry:
; stress-NEXT:    br label [[LOOP:%.*]]
; stress:       loop:
; stress-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; stress-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; stress-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; stress-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; stress-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; stress-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; stress-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; stress:       exit:
; stress-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; stress-NEXT:    ret i32 [[IV_LCSSA]]
;
; VLS-LABEL: @strlen_i8_int_iv(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[LOOP:%.*]]
; VLS:       loop:
; VLS-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[ENTRY:%.*]] ]
; VLS-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; VLS-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; VLS-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; VLS-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; VLS-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; VLS-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; VLS:       exit:
; VLS-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; VLS-NEXT:    ret i32 [[IV_LCSSA]]
;
; IF0-LABEL: @strlen_i8_int_iv(
; IF0-NEXT:  entry:
; IF0-NEXT:    br label [[LOOP:%.*]]
; IF0:       loop:
; IF0-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF0-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; IF0-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; IF0-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; IF0-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; IF0-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; IF0-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; IF0:       exit:
; IF0-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; IF0-NEXT:    ret i32 [[IV_LCSSA]]
;
; IF1-LABEL: @strlen_i8_int_iv(
; IF1-NEXT:  entry:
; IF1-NEXT:    br label [[LOOP:%.*]]
; IF1:       loop:
; IF1-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF1-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; IF1-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; IF1-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; IF1-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; IF1-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; IF1-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; IF1:       exit:
; IF1-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; IF1-NEXT:    ret i32 [[IV_LCSSA]]
;
; IF2-LABEL: @strlen_i8_int_iv(
; IF2-NEXT:  entry:
; IF2-NEXT:    br label [[LOOP:%.*]]
; IF2:       loop:
; IF2-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]] ]
; IF2-NEXT:    [[ZEXT:%.*]] = zext i32 [[IV]] to i64
; IF2-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i32, ptr [[START:%.*]], i64 [[ZEXT]]
; IF2-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GEP]], align 4
; IF2-NEXT:    [[COND:%.*]] = icmp eq i32 [[LOAD]], 0
; IF2-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; IF2-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; IF2:       exit:
; IF2-NEXT:    [[IV_LCSSA:%.*]] = phi i32 [ [[IV]], [[LOOP]] ]
; IF2-NEXT:    ret i32 [[IV_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ %iv.next, %loop ], [ 0, %entry ]
  %zext = zext i32 %iv to i64
  %gep = getelementptr inbounds nuw i32, ptr %start, i64 %zext
  %load = load i32, ptr %gep, align 4
  %cond = icmp eq i32 %load, 0
  %iv.next = add i32 %iv, 1
  br i1 %cond, label %exit, label %loop

exit:
  ret i32 %iv
}

define i64 @check_extract(ptr %datap) {
; DEFAULT-LABEL: @check_extract(
; DEFAULT-NEXT:  entry:
; DEFAULT-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; DEFAULT:       vector.ph:
; DEFAULT-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; DEFAULT-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; DEFAULT-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; DEFAULT-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; DEFAULT-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; DEFAULT-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; DEFAULT-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; DEFAULT-NEXT:    br label [[VECTOR_BODY:%.*]]
; DEFAULT:       vector.body:
; DEFAULT-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[DATAP:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; DEFAULT-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 2)
; DEFAULT-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; DEFAULT-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; DEFAULT-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i16, <vscale x 16 x ptr> [[VECTOR_GEP]], i64 1
; DEFAULT-NEXT:    [[TMP8:%.*]] = extractelement <vscale x 16 x ptr> [[TMP7]], i32 0
; DEFAULT-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i16, ptr [[TMP8]], i32 0
; DEFAULT-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP9]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; DEFAULT-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; DEFAULT-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; DEFAULT-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; DEFAULT-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP12]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; DEFAULT-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; DEFAULT-NEXT:    [[TMP14:%.*]] = icmp sge i32 [[TMP13]], 0
; DEFAULT-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP10]] to i64
; DEFAULT-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP11]], 1
; DEFAULT-NEXT:    [[TMP17:%.*]] = mul i64 2, [[TMP16]]
; DEFAULT-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP17]]
; DEFAULT-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP15]], [[EVL_BASED_IV]]
; DEFAULT-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP21:![0-9]+]]
; DEFAULT:       middle.block:
; DEFAULT-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP13]] to i64
; DEFAULT-NEXT:    [[TMP19:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP18]]
; DEFAULT-NEXT:    [[TMP20:%.*]] = add i64 [[TMP19]], 1
; DEFAULT-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 2
; DEFAULT-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[DATAP]], i64 [[TMP21]]
; DEFAULT-NEXT:    br i1 true, label [[EXIT:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; DEFAULT:       vec.uncountable.scalar.ph:
; DEFAULT-NEXT:    br label [[LOOP:%.*]]
; DEFAULT:       loop:
; DEFAULT-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ]
; DEFAULT-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; DEFAULT-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; DEFAULT-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; DEFAULT-NEXT:    br i1 [[COND]], label [[EXIT]], label [[LOOP]], !llvm.loop [[LOOP22:![0-9]+]]
; DEFAULT:       exit:
; DEFAULT-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; DEFAULT-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; DEFAULT-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; DEFAULT-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; DEFAULT-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; DEFAULT-NEXT:    ret i64 [[LSHR]]
;
; ON-LABEL: @check_extract(
; ON-NEXT:  entry:
; ON-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; ON:       vector.ph:
; ON-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; ON-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; ON-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; ON-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; ON-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; ON-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; ON-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; ON:       vector.body:
; ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[DATAP:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; ON-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 2)
; ON-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; ON-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; ON-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i16, <vscale x 16 x ptr> [[VECTOR_GEP]], i64 1
; ON-NEXT:    [[TMP8:%.*]] = extractelement <vscale x 16 x ptr> [[TMP7]], i32 0
; ON-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i16, ptr [[TMP8]], i32 0
; ON-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP9]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; ON-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; ON-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; ON-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; ON-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP12]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; ON-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; ON-NEXT:    [[TMP14:%.*]] = icmp sge i32 [[TMP13]], 0
; ON-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP10]] to i64
; ON-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP11]], 1
; ON-NEXT:    [[TMP17:%.*]] = mul i64 2, [[TMP16]]
; ON-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP17]]
; ON-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP15]], [[EVL_BASED_IV]]
; ON-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP21:![0-9]+]]
; ON:       middle.block:
; ON-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP13]] to i64
; ON-NEXT:    [[TMP19:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP18]]
; ON-NEXT:    [[TMP20:%.*]] = add i64 [[TMP19]], 1
; ON-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 2
; ON-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[DATAP]], i64 [[TMP21]]
; ON-NEXT:    br i1 true, label [[EXIT:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; ON:       vec.uncountable.scalar.ph:
; ON-NEXT:    br label [[LOOP:%.*]]
; ON:       loop:
; ON-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ]
; ON-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; ON-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; ON-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; ON-NEXT:    br i1 [[COND]], label [[EXIT]], label [[LOOP]], !llvm.loop [[LOOP22:![0-9]+]]
; ON:       exit:
; ON-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; ON-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; ON-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; ON-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; ON-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; ON-NEXT:    ret i64 [[LSHR]]
;
; OFF-LABEL: @check_extract(
; OFF-NEXT:  entry:
; OFF-NEXT:    br label [[LOOP:%.*]]
; OFF:       loop:
; OFF-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP:%.*]], [[ENTRY:%.*]] ]
; OFF-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; OFF-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; OFF-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; OFF-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; OFF:       exit:
; OFF-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ]
; OFF-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; OFF-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; OFF-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; OFF-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; OFF-NEXT:    ret i64 [[LSHR]]
;
; ANALYSIS-ONLY-LABEL: @check_extract(
; ANALYSIS-ONLY-NEXT:  entry:
; ANALYSIS-ONLY-NEXT:    br label [[LOOP:%.*]]
; ANALYSIS-ONLY:       loop:
; ANALYSIS-ONLY-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP:%.*]], [[ENTRY:%.*]] ]
; ANALYSIS-ONLY-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; ANALYSIS-ONLY-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; ANALYSIS-ONLY-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; ANALYSIS-ONLY-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; ANALYSIS-ONLY:       exit:
; ANALYSIS-ONLY-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ]
; ANALYSIS-ONLY-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; ANALYSIS-ONLY-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; ANALYSIS-ONLY-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; ANALYSIS-ONLY-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; ANALYSIS-ONLY-NEXT:    ret i64 [[LSHR]]
;
; stress-LABEL: @check_extract(
; stress-NEXT:  entry:
; stress-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; stress:       vector.ph:
; stress-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; stress-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; stress-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; stress-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; stress-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; stress-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; stress-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; stress-NEXT:    br label [[VECTOR_BODY:%.*]]
; stress:       vector.body:
; stress-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[DATAP:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; stress-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 2)
; stress-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; stress-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; stress-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i16, <vscale x 16 x ptr> [[VECTOR_GEP]], i64 1
; stress-NEXT:    [[TMP8:%.*]] = extractelement <vscale x 16 x ptr> [[TMP7]], i32 0
; stress-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i16, ptr [[TMP8]], i32 0
; stress-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP9]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; stress-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; stress-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; stress-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; stress-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP12]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; stress-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; stress-NEXT:    [[TMP14:%.*]] = icmp sge i32 [[TMP13]], 0
; stress-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP10]] to i64
; stress-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP11]], 1
; stress-NEXT:    [[TMP17:%.*]] = mul i64 2, [[TMP16]]
; stress-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP17]]
; stress-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP15]], [[EVL_BASED_IV]]
; stress-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP21:![0-9]+]]
; stress:       middle.block:
; stress-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP13]] to i64
; stress-NEXT:    [[TMP19:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP18]]
; stress-NEXT:    [[TMP20:%.*]] = add i64 [[TMP19]], 1
; stress-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 2
; stress-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[DATAP]], i64 [[TMP21]]
; stress-NEXT:    br i1 true, label [[EXIT:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; stress:       vec.uncountable.scalar.ph:
; stress-NEXT:    br label [[LOOP:%.*]]
; stress:       loop:
; stress-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ]
; stress-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; stress-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; stress-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; stress-NEXT:    br i1 [[COND]], label [[EXIT]], label [[LOOP]], !llvm.loop [[LOOP22:![0-9]+]]
; stress:       exit:
; stress-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; stress-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; stress-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; stress-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; stress-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; stress-NEXT:    ret i64 [[LSHR]]
;
; VLS-LABEL: @check_extract(
; VLS-NEXT:  entry:
; VLS-NEXT:    br label [[LOOP:%.*]]
; VLS:       loop:
; VLS-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP:%.*]], [[ENTRY:%.*]] ]
; VLS-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; VLS-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; VLS-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; VLS-NEXT:    br i1 [[COND]], label [[EXIT:%.*]], label [[LOOP]]
; VLS:       exit:
; VLS-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ]
; VLS-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; VLS-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; VLS-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; VLS-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; VLS-NEXT:    ret i64 [[LSHR]]
;
; IF0-LABEL: @check_extract(
; IF0-NEXT:  entry:
; IF0-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF0:       vector.ph:
; IF0-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IF0-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; IF0-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; IF0-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; IF0-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; IF0-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; IF0-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; IF0-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF0:       vector.body:
; IF0-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[DATAP:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; IF0-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 2)
; IF0-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; IF0-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i16, <vscale x 16 x ptr> [[VECTOR_GEP]], i64 1
; IF0-NEXT:    [[TMP8:%.*]] = extractelement <vscale x 16 x ptr> [[TMP7]], i32 0
; IF0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i16, ptr [[TMP8]], i32 0
; IF0-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP9]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; IF0-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; IF0-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; IF0-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; IF0-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP12]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; IF0-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; IF0-NEXT:    [[TMP14:%.*]] = icmp sge i32 [[TMP13]], 0
; IF0-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP10]] to i64
; IF0-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP11]], 1
; IF0-NEXT:    [[TMP17:%.*]] = mul i64 2, [[TMP16]]
; IF0-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP17]]
; IF0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP15]], [[EVL_BASED_IV]]
; IF0-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP21:![0-9]+]]
; IF0:       middle.block:
; IF0-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP13]] to i64
; IF0-NEXT:    [[TMP19:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP18]]
; IF0-NEXT:    [[TMP20:%.*]] = add i64 [[TMP19]], 1
; IF0-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 2
; IF0-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[DATAP]], i64 [[TMP21]]
; IF0-NEXT:    br i1 true, label [[EXIT:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF0:       vec.uncountable.scalar.ph:
; IF0-NEXT:    br label [[LOOP:%.*]]
; IF0:       loop:
; IF0-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ]
; IF0-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; IF0-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; IF0-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; IF0-NEXT:    br i1 [[COND]], label [[EXIT]], label [[LOOP]], !llvm.loop [[LOOP22:![0-9]+]]
; IF0:       exit:
; IF0-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; IF0-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; IF0-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; IF0-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; IF0-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; IF0-NEXT:    ret i64 [[LSHR]]
;
; IF1-LABEL: @check_extract(
; IF1-NEXT:  entry:
; IF1-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF1:       vector.ph:
; IF1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IF1-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; IF1-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; IF1-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; IF1-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; IF1-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; IF1-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; IF1-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF1:       vector.body:
; IF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[DATAP:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; IF1-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 2)
; IF1-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; IF1-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i16, <vscale x 16 x ptr> [[VECTOR_GEP]], i64 1
; IF1-NEXT:    [[TMP8:%.*]] = extractelement <vscale x 16 x ptr> [[TMP7]], i32 0
; IF1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i16, ptr [[TMP8]], i32 0
; IF1-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP9]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; IF1-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; IF1-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; IF1-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; IF1-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP12]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; IF1-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; IF1-NEXT:    [[TMP14:%.*]] = icmp sge i32 [[TMP13]], 0
; IF1-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP10]] to i64
; IF1-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP11]], 1
; IF1-NEXT:    [[TMP17:%.*]] = mul i64 2, [[TMP16]]
; IF1-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP17]]
; IF1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP15]], [[EVL_BASED_IV]]
; IF1-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP21:![0-9]+]]
; IF1:       middle.block:
; IF1-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP13]] to i64
; IF1-NEXT:    [[TMP19:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP18]]
; IF1-NEXT:    [[TMP20:%.*]] = add i64 [[TMP19]], 1
; IF1-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 2
; IF1-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[DATAP]], i64 [[TMP21]]
; IF1-NEXT:    br i1 true, label [[EXIT:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF1:       vec.uncountable.scalar.ph:
; IF1-NEXT:    br label [[LOOP:%.*]]
; IF1:       loop:
; IF1-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ]
; IF1-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; IF1-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; IF1-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; IF1-NEXT:    br i1 [[COND]], label [[EXIT]], label [[LOOP]], !llvm.loop [[LOOP22:![0-9]+]]
; IF1:       exit:
; IF1-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; IF1-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; IF1-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; IF1-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; IF1-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; IF1-NEXT:    ret i64 [[LSHR]]
;
; IF2-LABEL: @check_extract(
; IF2-NEXT:  entry:
; IF2-NEXT:    br i1 false, label [[VEC_UNCOUNTABLE_SCALAR_PH:%.*]], label [[ENTRY:%.*]]
; IF2:       vector.ph:
; IF2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IF2-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 16
; IF2-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 0
; IF2-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP2]], i64 0
; IF2-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; IF2-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; IF2-NEXT:    [[TMP4:%.*]] = add <vscale x 16 x i64> [[DOTSPLAT]], [[TMP3]]
; IF2-NEXT:    br label [[VECTOR_BODY:%.*]]
; IF2:       vector.body:
; IF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[DATAP:%.*]], [[ENTRY]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; IF2-NEXT:    [[TMP5:%.*]] = mul <vscale x 16 x i64> [[TMP4]], splat (i64 2)
; IF2-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 16 x i64> [[TMP5]]
; IF2-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 16, i1 true)
; IF2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i16, <vscale x 16 x ptr> [[VECTOR_GEP]], i64 1
; IF2-NEXT:    [[TMP8:%.*]] = extractelement <vscale x 16 x ptr> [[TMP7]], i32 0
; IF2-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i16, ptr [[TMP8]], i32 0
; IF2-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 16 x i16>, i32 } @llvm.vp.load.ff.nxv16i16.p0(ptr align 2 [[TMP9]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP6]])
; IF2-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 1
; IF2-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP10]] to i64
; IF2-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 16 x i16>, i32 } [[VP_OP_LOAD_FF]], 0
; IF2-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i16(<vscale x 16 x i16> [[TMP12]], <vscale x 16 x i16> zeroinitializer, metadata !"eq", <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; IF2-NEXT:    [[TMP13:%.*]] = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> [[VP_OP_ICMP]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; IF2-NEXT:    [[TMP14:%.*]] = icmp sge i32 [[TMP13]], 0
; IF2-NEXT:    [[TMP15:%.*]] = zext i32 [[TMP10]] to i64
; IF2-NEXT:    [[TMP16:%.*]] = mul i64 [[TMP11]], 1
; IF2-NEXT:    [[TMP17:%.*]] = mul i64 2, [[TMP16]]
; IF2-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP17]]
; IF2-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP15]], [[EVL_BASED_IV]]
; IF2-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP21:![0-9]+]]
; IF2:       middle.block:
; IF2-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP13]] to i64
; IF2-NEXT:    [[TMP19:%.*]] = add i64 [[EVL_BASED_IV]], [[TMP18]]
; IF2-NEXT:    [[TMP20:%.*]] = add i64 [[TMP19]], 1
; IF2-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 2
; IF2-NEXT:    [[EXIT_VALUE:%.*]] = getelementptr i8, ptr [[DATAP]], i64 [[TMP21]]
; IF2-NEXT:    br i1 true, label [[EXIT:%.*]], label [[VEC_UNCOUNTABLE_SCALAR_PH]]
; IF2:       vec.uncountable.scalar.ph:
; IF2-NEXT:    br label [[LOOP:%.*]]
; IF2:       loop:
; IF2-NEXT:    [[PTR_IV:%.*]] = phi ptr [ [[PTR_NEXT:%.*]], [[LOOP]] ], [ [[DATAP]], [[VEC_UNCOUNTABLE_SCALAR_PH]] ]
; IF2-NEXT:    [[PTR_NEXT]] = getelementptr inbounds nuw i16, ptr [[PTR_IV]], i64 1
; IF2-NEXT:    [[DATA:%.*]] = load i16, ptr [[PTR_NEXT]], align 2
; IF2-NEXT:    [[COND:%.*]] = icmp eq i16 [[DATA]], 0
; IF2-NEXT:    br i1 [[COND]], label [[EXIT]], label [[LOOP]], !llvm.loop [[LOOP22:![0-9]+]]
; IF2:       exit:
; IF2-NEXT:    [[PHI643:%.*]] = phi ptr [ [[PTR_NEXT]], [[LOOP]] ], [ [[EXIT_VALUE]], [[MIDDLE_BLOCK]] ]
; IF2-NEXT:    [[PTRTOINT:%.*]] = ptrtoint ptr [[PHI643]] to i64
; IF2-NEXT:    [[PTRTOINT644:%.*]] = ptrtoint ptr [[DATAP]] to i64
; IF2-NEXT:    [[SUB645:%.*]] = sub i64 [[PTRTOINT]], [[PTRTOINT644]]
; IF2-NEXT:    [[LSHR:%.*]] = lshr exact i64 [[SUB645]], 1
; IF2-NEXT:    ret i64 [[LSHR]]
;
entry:
  br label %loop

loop:
  %ptr.iv = phi ptr [ %ptr.next, %loop ], [ %datap, %entry]
  %ptr.next = getelementptr inbounds nuw i16, ptr %ptr.iv, i64 1
  %data = load i16, ptr %ptr.next, align 2
  %cond = icmp eq i16 %data, 0
  br i1 %cond, label %exit, label %loop

exit:
  %endp = phi ptr [ %ptr.next, %loop ]
  %endp64 = ptrtoint ptr %endp to i64
  %datap64 = ptrtoint ptr %datap to i64
  %sub = sub i64 %endp64, %datap64
  %lshr = lshr exact i64 %sub, 1
  ret i64 %lshr
}

