; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -riscv-use-vla-vectorizer -passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mattr=+v -sifive-uncountable-loop-vectorization=on < %s | FileCheck %s

define i32 @bt_find_func(i32 %len_limit, ptr %pb, ptr %cur) {
; CHECK-LABEL: @bt_find_func(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[LEN_LIMIT:%.*]], -1
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    br label [[WHILE_COND:%.*]]
; CHECK:       while.cond:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[WHILE_BODY:%.*]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[WHILE_END_LOOPEXIT:%.*]], label [[WHILE_BODY]]
; CHECK:       while.body:
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[IDXPROM:%.*]] = and i64 [[INDVARS_IV_NEXT]], 4294967295
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[PB:%.*]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[CUR:%.*]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; CHECK-NEXT:    [[CMP4_NOT:%.*]] = icmp eq i8 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    br i1 [[CMP4_NOT]], label [[WHILE_COND]], label [[WHILE_END_SPLIT_LOOP_EXIT:%.*]]
; CHECK:       while.end.split.loop.exit:
; CHECK-NEXT:    [[INDVARS_IV_NEXT_LCSSA:%.*]] = phi i64 [ [[INDVARS_IV_NEXT]], [[WHILE_BODY]] ]
; CHECK-NEXT:    [[INDVARS_LE:%.*]] = trunc i64 [[INDVARS_IV_NEXT_LCSSA]] to i32
; CHECK-NEXT:    br label [[WHILE_END:%.*]]
; CHECK:       while.end.loopexit:
; CHECK-NEXT:    br label [[WHILE_END]]
; CHECK:       while.end:
; CHECK-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INDVARS_LE]], [[WHILE_END_SPLIT_LOOP_EXIT]] ], [ [[LEN_LIMIT]], [[WHILE_END_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[INC_LCSSA]]
;
entry:
  %0 = add i32 %len_limit, -1
  %wide.trip.count = zext i32 %0 to i64
  br label %while.cond

while.cond:
  %indvars.iv = phi i64 [ %indvars.iv.next, %while.body ], [ 0, %entry ]
  %exitcond = icmp eq i64 %indvars.iv, %wide.trip.count
  br i1 %exitcond, label %while.end.loopexit, label %while.body

while.body:
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %idxprom = and i64 %indvars.iv.next, 4294967295
  %arrayidx = getelementptr inbounds i8, ptr %pb, i64 %idxprom
  %1 = load i8, ptr %arrayidx, align 1
  %arrayidx2 = getelementptr inbounds i8, ptr %cur, i64 %idxprom
  %2 = load i8, ptr %arrayidx2, align 1
  %cmp4.not = icmp eq i8 %1, %2
  br i1 %cmp4.not, label %while.cond, label %while.end.split.loop.exit

while.end.split.loop.exit:
  %indvars.iv.next.lcssa = phi i64 [ %indvars.iv.next, %while.body ]
  %indvars.le = trunc i64 %indvars.iv.next.lcssa to i32
  br label %while.end

while.end.loopexit:
  br label %while.end

while.end:
  %inc.lcssa = phi i32 [ %indvars.le, %while.end.split.loop.exit ], [ %len_limit, %while.end.loopexit ]
  ret i32 %inc.lcssa
}

define i32 @lzma_mf_bt4_find(i32 %len_limit, ptr %cur, i32 %delta2) {
; CHECK-LABEL: @lzma_mf_bt4_find(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT10:%.*]] = icmp eq i32 [[LEN_LIMIT:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT10]], label [[FOR_END:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[IDX_EXT1:%.*]] = zext i32 [[DELTA2:%.*]] to i64
; CHECK-NEXT:    [[IDX_NEG:%.*]] = sub nsw i64 0, [[IDX_EXT1]]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[LEN_BEST_011:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[IDX_EXT:%.*]] = zext i32 [[LEN_BEST_011]] to i64
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[CUR:%.*]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 [[IDX_NEG]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ADD_PTR2]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    [[CMP4_NOT:%.*]] = icmp eq i8 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP4_NOT]], label [[FOR_INC]], label [[FOR_END_LOOPEXIT:%.*]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INC]] = add nuw i32 [[LEN_BEST_011]], 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[INC]], [[LEN_LIMIT]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END_LOOPEXIT]], label [[FOR_BODY]]
; CHECK:       for.end.loopexit:
; CHECK-NEXT:    [[LEN_BEST_0_LCSSA_PH:%.*]] = phi i32 [ [[LEN_LIMIT]], [[FOR_INC]] ], [ [[LEN_BEST_011]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[FOR_END]]
; CHECK:       for.end:
; CHECK-NEXT:    [[LEN_BEST_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[LEN_BEST_0_LCSSA_PH]], [[FOR_END_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[LEN_BEST_0_LCSSA]]
;
entry:
  %cmp.not10 = icmp eq i32 %len_limit, 0
  br i1 %cmp.not10, label %for.end, label %for.body.lr.ph

for.body.lr.ph:
  %idx.ext1 = zext i32 %delta2 to i64
  %idx.neg = sub nsw i64 0, %idx.ext1
  br label %for.body

for.body:
  %len_best.011 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.inc ]
  %idx.ext = zext i32 %len_best.011 to i64
  %add.ptr = getelementptr inbounds i8, ptr %cur, i64 %idx.ext
  %add.ptr2 = getelementptr inbounds i8, ptr %add.ptr, i64 %idx.neg
  %0 = load i8, ptr %add.ptr2, align 1
  %1 = load i8, ptr %add.ptr, align 1
  %cmp4.not = icmp eq i8 %0, %1
  br i1 %cmp4.not, label %for.inc, label %for.end.loopexit

for.inc:
  %inc = add nuw i32 %len_best.011, 1
  %cmp.not = icmp eq i32 %inc, %len_limit
  br i1 %cmp.not, label %for.end.loopexit, label %for.body

for.end.loopexit:
  %len_best.0.lcssa.ph = phi i32 [ %len_limit, %for.inc ], [ %len_best.011, %for.body ]
  br label %for.end

for.end:
  %len_best.0.lcssa = phi i32 [ 0, %entry ], [ %len_best.0.lcssa.ph, %for.end.loopexit ]
  ret i32 %len_best.0.lcssa
}
