; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=slp-vectorizer -mtriple=riscv64 -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=CHECK-X280

; Scalar is better on X280
define i32 @redsum_vf16(ptr %ptr, ptr %ptr2) {
; CHECK-X280-LABEL: @redsum_vf16(
; CHECK-X280-NEXT:  entry:
; CHECK-X280-NEXT:    [[TMP0:%.*]] = load i32, ptr [[PTR:%.*]], align 4
; CHECK-X280-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 1
; CHECK-X280-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX1]], align 4
; CHECK-X280-NEXT:    [[ADD2:%.*]] = add nsw i32 [[TMP1]], [[TMP0]]
; CHECK-X280-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 2
; CHECK-X280-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX3]], align 4
; CHECK-X280-NEXT:    [[ADD4:%.*]] = add nsw i32 [[ADD2]], [[TMP2]]
; CHECK-X280-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 3
; CHECK-X280-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX5]], align 4
; CHECK-X280-NEXT:    [[ADD6:%.*]] = add nsw i32 [[ADD4]], [[TMP3]]
; CHECK-X280-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 4
; CHECK-X280-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX7]], align 4
; CHECK-X280-NEXT:    [[ADD8:%.*]] = add nsw i32 [[ADD6]], [[TMP4]]
; CHECK-X280-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 5
; CHECK-X280-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX9]], align 4
; CHECK-X280-NEXT:    [[ADD10:%.*]] = add nsw i32 [[ADD8]], [[TMP5]]
; CHECK-X280-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 6
; CHECK-X280-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX11]], align 4
; CHECK-X280-NEXT:    [[ADD12:%.*]] = add nsw i32 [[ADD10]], [[TMP6]]
; CHECK-X280-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 7
; CHECK-X280-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX13]], align 4
; CHECK-X280-NEXT:    [[ADD14:%.*]] = add nsw i32 [[ADD12]], [[TMP7]]
; CHECK-X280-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 8
; CHECK-X280-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX15]], align 4
; CHECK-X280-NEXT:    [[ADD16:%.*]] = add nsw i32 [[ADD14]], [[TMP8]]
; CHECK-X280-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 9
; CHECK-X280-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX17]], align 4
; CHECK-X280-NEXT:    [[ADD18:%.*]] = add nsw i32 [[ADD16]], [[TMP9]]
; CHECK-X280-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 10
; CHECK-X280-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARRAYIDX19]], align 4
; CHECK-X280-NEXT:    [[ADD20:%.*]] = add nsw i32 [[ADD18]], [[TMP10]]
; CHECK-X280-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 11
; CHECK-X280-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX21]], align 4
; CHECK-X280-NEXT:    [[ADD22:%.*]] = add nsw i32 [[ADD20]], [[TMP11]]
; CHECK-X280-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 12
; CHECK-X280-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX23]], align 4
; CHECK-X280-NEXT:    [[ADD24:%.*]] = add nsw i32 [[ADD22]], [[TMP12]]
; CHECK-X280-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 13
; CHECK-X280-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX25]], align 4
; CHECK-X280-NEXT:    [[ADD26:%.*]] = add nsw i32 [[ADD24]], [[TMP13]]
; CHECK-X280-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 14
; CHECK-X280-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX27]], align 4
; CHECK-X280-NEXT:    [[ADD28:%.*]] = add nsw i32 [[ADD26]], [[TMP14]]
; CHECK-X280-NEXT:    [[ARRAYIDX29:%.*]] = getelementptr inbounds i32, ptr [[PTR]], i64 15
; CHECK-X280-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX29]], align 4
; CHECK-X280-NEXT:    [[ADD30:%.*]] = add nsw i32 [[ADD28]], [[TMP15]]
; CHECK-X280-NEXT:    ret i32 [[ADD30]]
;
entry:
  %0 = load i32, ptr %ptr, align 4
  %arrayidx1 = getelementptr inbounds i32, ptr %ptr, i64 1
  %1 = load i32, ptr %arrayidx1, align 4
  %add2 = add nsw i32 %1, %0
  %arrayidx3 = getelementptr inbounds i32, ptr %ptr, i64 2
  %2 = load i32, ptr %arrayidx3, align 4
  %add4 = add nsw i32 %add2, %2
  %arrayidx5 = getelementptr inbounds i32, ptr %ptr, i64 3
  %3 = load i32, ptr %arrayidx5, align 4
  %add6 = add nsw i32 %add4, %3
  %arrayidx7 = getelementptr inbounds i32, ptr %ptr, i64 4
  %4 = load i32, ptr %arrayidx7, align 4
  %add8 = add nsw i32 %add6, %4
  %arrayidx9 = getelementptr inbounds i32, ptr %ptr, i64 5
  %5 = load i32, ptr %arrayidx9, align 4
  %add10 = add nsw i32 %add8, %5
  %arrayidx11 = getelementptr inbounds i32, ptr %ptr, i64 6
  %6 = load i32, ptr %arrayidx11, align 4
  %add12 = add nsw i32 %add10, %6
  %arrayidx13 = getelementptr inbounds i32, ptr %ptr, i64 7
  %7 = load i32, ptr %arrayidx13, align 4
  %add14 = add nsw i32 %add12, %7
  %arrayidx15 = getelementptr inbounds i32, ptr %ptr, i64 8
  %8 = load i32, ptr %arrayidx15, align 4
  %add16 = add nsw i32 %add14, %8
  %arrayidx17 = getelementptr inbounds i32, ptr %ptr, i64 9
  %9 = load i32, ptr %arrayidx17, align 4
  %add18 = add nsw i32 %add16, %9
  %arrayidx19 = getelementptr inbounds i32, ptr %ptr, i64 10
  %10 = load i32, ptr %arrayidx19, align 4
  %add20 = add nsw i32 %add18, %10
  %arrayidx21 = getelementptr inbounds i32, ptr %ptr, i64 11
  %11 = load i32, ptr %arrayidx21, align 4
  %add22 = add nsw i32 %add20, %11
  %arrayidx23 = getelementptr inbounds i32, ptr %ptr, i64 12
  %12 = load i32, ptr %arrayidx23, align 4
  %add24 = add nsw i32 %add22, %12
  %arrayidx25 = getelementptr inbounds i32, ptr %ptr, i64 13
  %13 = load i32, ptr %arrayidx25, align 4
  %add26 = add nsw i32 %add24, %13
  %arrayidx27 = getelementptr inbounds i32, ptr %ptr, i64 14
  %14 = load i32, ptr %arrayidx27, align 4
  %add28 = add nsw i32 %add26, %14
  %arrayidx29 = getelementptr inbounds i32, ptr %ptr, i64 15
  %15 = load i32, ptr %arrayidx29, align 4
  %add30 = add nsw i32 %add28, %15
  ret i32 %add30
}

; Vector is better on X280
define i32 @redsum_vf32(ptr %ptr, ptr %ptr2) {
; CHECK-X280-LABEL: @redsum_vf32(
; CHECK-X280-NEXT:  entry:
; CHECK-X280-NEXT:    [[TMP0:%.*]] = load <32 x i32>, ptr [[PTR:%.*]], align 4
; CHECK-X280-NEXT:    [[TMP1:%.*]] = call i32 @llvm.vector.reduce.add.v32i32(<32 x i32> [[TMP0]])
; CHECK-X280-NEXT:    ret i32 [[TMP1]]
;
entry:
  %0 = load i32, ptr %ptr, align 4
  %arrayidx1 = getelementptr inbounds i32, ptr %ptr, i64 1
  %1 = load i32, ptr %arrayidx1, align 4
  %add2 = add nsw i32 %1, %0
  %arrayidx3 = getelementptr inbounds i32, ptr %ptr, i64 2
  %2 = load i32, ptr %arrayidx3, align 4
  %add4 = add nsw i32 %add2, %2
  %arrayidx5 = getelementptr inbounds i32, ptr %ptr, i64 3
  %3 = load i32, ptr %arrayidx5, align 4
  %add6 = add nsw i32 %add4, %3
  %arrayidx7 = getelementptr inbounds i32, ptr %ptr, i64 4
  %4 = load i32, ptr %arrayidx7, align 4
  %add8 = add nsw i32 %add6, %4
  %arrayidx9 = getelementptr inbounds i32, ptr %ptr, i64 5
  %5 = load i32, ptr %arrayidx9, align 4
  %add10 = add nsw i32 %add8, %5
  %arrayidx11 = getelementptr inbounds i32, ptr %ptr, i64 6
  %6 = load i32, ptr %arrayidx11, align 4
  %add12 = add nsw i32 %add10, %6
  %arrayidx13 = getelementptr inbounds i32, ptr %ptr, i64 7
  %7 = load i32, ptr %arrayidx13, align 4
  %add14 = add nsw i32 %add12, %7
  %arrayidx15 = getelementptr inbounds i32, ptr %ptr, i64 8
  %8 = load i32, ptr %arrayidx15, align 4
  %add16 = add nsw i32 %add14, %8
  %arrayidx17 = getelementptr inbounds i32, ptr %ptr, i64 9
  %9 = load i32, ptr %arrayidx17, align 4
  %add18 = add nsw i32 %add16, %9
  %arrayidx19 = getelementptr inbounds i32, ptr %ptr, i64 10
  %10 = load i32, ptr %arrayidx19, align 4
  %add20 = add nsw i32 %add18, %10
  %arrayidx21 = getelementptr inbounds i32, ptr %ptr, i64 11
  %11 = load i32, ptr %arrayidx21, align 4
  %add22 = add nsw i32 %add20, %11
  %arrayidx23 = getelementptr inbounds i32, ptr %ptr, i64 12
  %12 = load i32, ptr %arrayidx23, align 4
  %add24 = add nsw i32 %add22, %12
  %arrayidx25 = getelementptr inbounds i32, ptr %ptr, i64 13
  %13 = load i32, ptr %arrayidx25, align 4
  %add26 = add nsw i32 %add24, %13
  %arrayidx27 = getelementptr inbounds i32, ptr %ptr, i64 14
  %14 = load i32, ptr %arrayidx27, align 4
  %add28 = add nsw i32 %add26, %14
  %arrayidx29 = getelementptr inbounds i32, ptr %ptr, i64 15
  %15 = load i32, ptr %arrayidx29, align 4
  %add30 = add nsw i32 %add28, %15
  %arrayidx31 = getelementptr inbounds i32, ptr %ptr, i64 16
  %16 = load i32, ptr %arrayidx31, align 4
  %add32 = add nsw i32 %add30, %16
  %arrayidx33 = getelementptr inbounds i32, ptr %ptr, i64 17
  %17 = load i32, ptr %arrayidx33, align 4
  %add34 = add nsw i32 %add32, %17
  %arrayidx35 = getelementptr inbounds i32, ptr %ptr, i64 18
  %18 = load i32, ptr %arrayidx35, align 4
  %add36 = add nsw i32 %add34, %18
  %arrayidx37 = getelementptr inbounds i32, ptr %ptr, i64 19
  %19 = load i32, ptr %arrayidx37, align 4
  %add38 = add nsw i32 %add36, %19
  %arrayidx39 = getelementptr inbounds i32, ptr %ptr, i64 20
  %20 = load i32, ptr %arrayidx39, align 4
  %add40 = add nsw i32 %add38, %20
  %arrayidx41 = getelementptr inbounds i32, ptr %ptr, i64 21
  %21 = load i32, ptr %arrayidx41, align 4
  %add42 = add nsw i32 %add40, %21
  %arrayidx43 = getelementptr inbounds i32, ptr %ptr, i64 22
  %22 = load i32, ptr %arrayidx43, align 4
  %add44 = add nsw i32 %add42, %22
  %arrayidx45 = getelementptr inbounds i32, ptr %ptr, i64 23
  %23 = load i32, ptr %arrayidx45, align 4
  %add46 = add nsw i32 %add44, %23
  %arrayidx47 = getelementptr inbounds i32, ptr %ptr, i64 24
  %24 = load i32, ptr %arrayidx47, align 4
  %add48 = add nsw i32 %add46, %24
  %arrayidx49 = getelementptr inbounds i32, ptr %ptr, i64 25
  %25 = load i32, ptr %arrayidx49, align 4
  %add50 = add nsw i32 %add48, %25
  %arrayidx51 = getelementptr inbounds i32, ptr %ptr, i64 26
  %26 = load i32, ptr %arrayidx51, align 4
  %add52 = add nsw i32 %add50, %26
  %arrayidx53 = getelementptr inbounds i32, ptr %ptr, i64 27
  %27 = load i32, ptr %arrayidx53, align 4
  %add54 = add nsw i32 %add52, %27
  %arrayidx55 = getelementptr inbounds i32, ptr %ptr, i64 28
  %28 = load i32, ptr %arrayidx55, align 4
  %add56 = add nsw i32 %add54, %28
  %arrayidx57 = getelementptr inbounds i32, ptr %ptr, i64 29
  %29 = load i32, ptr %arrayidx57, align 4
  %add58 = add nsw i32 %add56, %29
  %arrayidx59 = getelementptr inbounds i32, ptr %ptr, i64 30
  %30 = load i32, ptr %arrayidx59, align 4
  %add60 = add nsw i32 %add58, %30
  %arrayidx61 = getelementptr inbounds i32, ptr %ptr, i64 31
  %31 = load i32, ptr %arrayidx61, align 4
  %add62 = add nsw i32 %add60, %31
  ret i32 %add62
}
