; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -passes=loop-data-layout -loop-data-layout-enable -mtriple=riscv64-unknown-linux-gnu | FileCheck %s

; This file tests tracking allocation splits for translating
; structs to fields in loop-data-layout
%struct.quantum_reg_struct = type { i32, i32, i32, ptr, ptr }
%struct.quantum_reg_node_struct = type { { float, float }, i64 }

@quantum_memman.mem = internal unnamed_addr global i64 0, align 8
@quantum_memman.max = internal unnamed_addr global i64 0, align 8
@.str.11 = private unnamed_addr constant [50 x i8] c"Not enough memory for %i-sized quantum register!\0A\00", align 1
@seedi = internal unnamed_addr global i32 0, align 4

; Function Attrs: mustprogress nofree nounwind willreturn allockind("alloc,zeroed") allocsize(0,1) memory(inaccessiblemem: readwrite)
declare dso_local noalias noundef ptr @calloc(i64 noundef, i64 noundef)

; Function Attrs: nofree nounwind
declare dso_local noundef signext i32 @printf(ptr nocapture noundef readonly, ...)

; Function Attrs: nofree noreturn nounwind
declare dso_local void @exit(i32 noundef signext)

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.sqrt.f64(double)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i64> @llvm.vp.shl.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i1>, i32)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i64> @llvm.vp.add.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i1>, i32)

; Function Attrs: mustprogress nounwind willreturn allockind("free") memory(argmem: readwrite, inaccessiblemem: readwrite)
declare dso_local void @free(ptr allocptr nocapture noundef)

; Function Attrs: nounwind uwtable vscale_range(2,2)
declare dso_local signext range(i32 0, 2) i32 @quantum_objcode_put(i8 noundef zeroext range(i8 0, -126))

; Function Attrs: nounwind uwtable vscale_range(2,2)
define internal fastcc signext range(i32 0, 2) i32 @bmeasure(i32 noundef signext %arg, ptr nocapture noundef nonnull %arg1) align 8 {
; CHECK-LABEL: define internal fastcc signext range(i32 0, 2) i32 @bmeasure(
; CHECK-SAME: i32 noundef signext [[ARG:%.*]], ptr noundef nonnull captures(none) [[ARG1:%.*]]) align 8 {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[I:%.*]] = alloca [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA:%.*]], align 8
; CHECK-NEXT:    [[I2:%.*]] = alloca [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[I]])
; CHECK-NEXT:    [[I3:%.*]] = tail call signext i32 (i8, ...) @quantum_objcode_put(i8 noundef zeroext -127, i32 noundef signext [[ARG]])
; CHECK-NEXT:    [[I4:%.*]] = icmp eq i32 [[I3]], 0
; CHECK-NEXT:    br i1 [[I4]], label %[[BB5:.*]], label %[[BB337:.*]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[I6:%.*]] = zext nneg i32 [[ARG]] to i64
; CHECK-NEXT:    [[I7:%.*]] = shl nuw i64 1, [[I6]]
; CHECK-NEXT:    [[I8:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 1
; CHECK-NEXT:    [[I9:%.*]] = load i32, ptr [[I8]], align 4, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[I10:%.*]] = icmp sgt i32 [[I9]], 0
; CHECK-NEXT:    br i1 [[I10]], label %[[BB11:.*]], label %[[BB36:.*]]
; CHECK:       [[BB11]]:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 6
; CHECK-NEXT:    [[I12:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 5
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[I13:%.*]] = load ptr, ptr [[I12]], align 8, !tbaa [[TBAA8:![0-9]+]]
; CHECK-NEXT:    [[I14:%.*]] = zext nneg i32 [[I9]] to i64
; CHECK-NEXT:    br label %[[BB15:.*]]
; CHECK:       [[BB15]]:
; CHECK-NEXT:    [[I16:%.*]] = phi i64 [ 0, %[[BB11]] ], [ [[I34:%.*]], %[[BB32:.*]] ]
; CHECK-NEXT:    [[I17:%.*]] = phi double [ 0.000000e+00, %[[BB11]] ], [ [[I33:%.*]], %[[BB32]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i64, ptr [[TMP1]], i64 [[I16]]
; CHECK-NEXT:    [[I19:%.*]] = load i64, ptr [[TMP2]], align 8, !tbaa [[TBAA9:![0-9]+]]
; CHECK-NEXT:    [[I20:%.*]] = and i64 [[I19]], [[I7]]
; CHECK-NEXT:    [[I21:%.*]] = icmp eq i64 [[I20]], 0
; CHECK-NEXT:    br i1 [[I21]], label %[[BB22:.*]], label %[[BB32]]
; CHECK:       [[BB22]]:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds { float, float }, ptr [[I13]], i64 [[I16]]
; CHECK-NEXT:    [[I24:%.*]] = load float, ptr [[TMP3]], align 8
; CHECK-NEXT:    [[I25:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP3]], i64 0, i32 1
; CHECK-NEXT:    [[I26:%.*]] = load float, ptr [[I25]], align 4
; CHECK-NEXT:    [[I27:%.*]] = fmul fast float [[I24]], [[I24]]
; CHECK-NEXT:    [[I28:%.*]] = fmul fast float [[I26]], [[I26]]
; CHECK-NEXT:    [[I29:%.*]] = fadd fast float [[I28]], [[I27]]
; CHECK-NEXT:    [[I30:%.*]] = fpext float [[I29]] to double
; CHECK-NEXT:    [[I31:%.*]] = fadd fast double [[I17]], [[I30]]
; CHECK-NEXT:    br label %[[BB32]]
; CHECK:       [[BB32]]:
; CHECK-NEXT:    [[I33]] = phi nsz double [ [[I17]], %[[BB15]] ], [ [[I31]], %[[BB22]] ]
; CHECK-NEXT:    [[I34]] = add nuw nsw i64 [[I16]], 1
; CHECK-NEXT:    [[I35:%.*]] = icmp eq i64 [[I34]], [[I14]]
; CHECK-NEXT:    br i1 [[I35]], label %[[BB36]], label %[[BB15]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[BB36]]:
; CHECK-NEXT:    [[I37:%.*]] = phi double [ 0.000000e+00, %[[BB5]] ], [ [[I33]], %[[BB32]] ]
; CHECK-NEXT:    [[I38:%.*]] = load i32, ptr @seedi, align 4, !tbaa [[TBAA14:![0-9]+]]
; CHECK-NEXT:    [[I39:%.*]] = freeze i32 [[I38]]
; CHECK-NEXT:    [[I40:%.*]] = sdiv i32 [[I39]], 127773
; CHECK-NEXT:    [[I41:%.*]] = mul i32 [[I40]], -127773
; CHECK-NEXT:    [[I42:%.*]] = add i32 [[I41]], [[I39]]
; CHECK-NEXT:    [[I43:%.*]] = mul nsw i32 [[I42]], 16807
; CHECK-NEXT:    [[I44:%.*]] = mul nsw i32 [[I40]], -2836
; CHECK-NEXT:    [[I45:%.*]] = add i32 [[I43]], [[I44]]
; CHECK-NEXT:    [[I46:%.*]] = icmp sgt i32 [[I45]], 0
; CHECK-NEXT:    [[I47:%.*]] = add i32 [[I45]], 2147483647
; CHECK-NEXT:    [[I48:%.*]] = select i1 [[I46]], i32 [[I45]], i32 [[I47]]
; CHECK-NEXT:    store i32 [[I48]], ptr @seedi, align 4, !tbaa [[TBAA14]]
; CHECK-NEXT:    [[I49:%.*]] = sitofp i32 [[I48]] to double
; CHECK-NEXT:    [[I50:%.*]] = fmul fast double [[I49]], 0x3E00000000200000
; CHECK-NEXT:    [[I51:%.*]] = fcmp fast ogt double [[I50]], [[I37]]
; CHECK-NEXT:    [[I52:%.*]] = zext i1 [[I51]] to i32
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[I2]])
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(48) [[I2]], ptr noundef nonnull align 8 dereferenceable(48) [[ARG1]], i64 48, i1 false), !tbaa [[TBAA15:![0-9]+]], !tbaa.struct [[TBAA_STRUCT16:![0-9]+]]
; CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META19:![0-9]+]])
; CHECK-NEXT:    [[I53:%.*]] = zext i32 [[ARG]] to i64
; CHECK-NEXT:    [[I54:%.*]] = shl nuw i64 1, [[I53]]
; CHECK-NEXT:    [[I55:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 1
; CHECK-NEXT:    [[I56:%.*]] = load i32, ptr [[I55]], align 4, !tbaa [[TBAA0]], !noalias [[META19]]
; CHECK-NEXT:    [[I57:%.*]] = icmp sgt i32 [[I56]], 0
; CHECK-NEXT:    br i1 [[I57]], label %[[BB58:.*]], label %[[BB87:.*]]
; CHECK:       [[BB58]]:
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 6
; CHECK-NEXT:    [[I59:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 5
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[I60:%.*]] = load ptr, ptr [[I59]], align 8, !tbaa [[TBAA8]], !noalias [[META19]]
; CHECK-NEXT:    [[I61:%.*]] = zext nneg i32 [[I56]] to i64
; CHECK-NEXT:    br label %[[BB62:.*]]
; CHECK:       [[BB62]]:
; CHECK-NEXT:    [[I63:%.*]] = phi i64 [ 0, %[[BB58]] ], [ [[I85:%.*]], %[[BB82:.*]] ]
; CHECK-NEXT:    [[I64:%.*]] = phi double [ 0.000000e+00, %[[BB58]] ], [ [[I84:%.*]], %[[BB82]] ]
; CHECK-NEXT:    [[I65:%.*]] = phi i32 [ 0, %[[BB58]] ], [ [[I83:%.*]], %[[BB82]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP5]], i64 [[I63]]
; CHECK-NEXT:    [[I67:%.*]] = load i64, ptr [[TMP6]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[I68:%.*]] = and i64 [[I67]], [[I54]]
; CHECK-NEXT:    [[I69:%.*]] = icmp ne i64 [[I68]], 0
; CHECK-NEXT:    [[I70:%.*]] = xor i1 [[I51]], [[I69]]
; CHECK-NEXT:    br i1 [[I70]], label %[[BB82]], label %[[BB71:.*]]
; CHECK:       [[BB71]]:
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds { float, float }, ptr [[I60]], i64 [[I63]]
; CHECK-NEXT:    [[I73:%.*]] = load float, ptr [[TMP7]], align 8, !noalias [[META19]]
; CHECK-NEXT:    [[I74:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP7]], i64 0, i32 1
; CHECK-NEXT:    [[I75:%.*]] = load float, ptr [[I74]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I76:%.*]] = fmul fast float [[I73]], [[I73]]
; CHECK-NEXT:    [[I77:%.*]] = fmul fast float [[I75]], [[I75]]
; CHECK-NEXT:    [[I78:%.*]] = fadd fast float [[I77]], [[I76]]
; CHECK-NEXT:    [[I79:%.*]] = fpext float [[I78]] to double
; CHECK-NEXT:    [[I80:%.*]] = fadd fast double [[I64]], [[I79]]
; CHECK-NEXT:    [[I81:%.*]] = add nsw i32 [[I65]], 1
; CHECK-NEXT:    br label %[[BB82]]
; CHECK:       [[BB82]]:
; CHECK-NEXT:    [[I83]] = phi i32 [ [[I81]], %[[BB71]] ], [ [[I65]], %[[BB62]] ]
; CHECK-NEXT:    [[I84]] = phi nsz double [ [[I80]], %[[BB71]] ], [ [[I64]], %[[BB62]] ]
; CHECK-NEXT:    [[I85]] = add nuw nsw i64 [[I63]], 1
; CHECK-NEXT:    [[I86:%.*]] = icmp eq i64 [[I85]], [[I61]]
; CHECK-NEXT:    br i1 [[I86]], label %[[BB87]], label %[[BB62]], !llvm.loop [[LOOP22:![0-9]+]]
; CHECK:       [[BB87]]:
; CHECK-NEXT:    [[I88:%.*]] = phi i32 [ 0, %[[BB36]] ], [ [[I83]], %[[BB82]] ]
; CHECK-NEXT:    [[I89:%.*]] = phi double [ 0.000000e+00, %[[BB36]] ], [ [[I84]], %[[BB82]] ]
; CHECK-NEXT:    [[I90:%.*]] = load i32, ptr [[I2]], align 8, !tbaa [[TBAA23:![0-9]+]], !noalias [[META19]]
; CHECK-NEXT:    [[I91:%.*]] = add nsw i32 [[I90]], -1
; CHECK-NEXT:    store i32 [[I91]], ptr [[I]], align 8, !tbaa [[TBAA23]], !alias.scope [[META19]]
; CHECK-NEXT:    [[I92:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I]], i64 0, i32 1
; CHECK-NEXT:    store i32 [[I88]], ptr [[I92]], align 4, !tbaa [[TBAA0]], !alias.scope [[META19]]
; CHECK-NEXT:    [[I93:%.*]] = sext i32 [[I88]] to i64
; CHECK-NEXT:    [[I94:%.*]] = tail call noalias ptr @calloc(i64 noundef [[I93]], i64 noundef 8)
; CHECK-NEXT:    [[TMP8:%.*]] = tail call noalias ptr @calloc(i64 noundef [[I93]], i64 noundef 8)
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I]], i64 0, i32 6
; CHECK-NEXT:    [[I95:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I]], i64 0, i32 5
; CHECK-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
; CHECK-NEXT:    store ptr [[I94]], ptr [[I95]], align 8, !tbaa [[TBAA8]], !alias.scope [[META19]]
; CHECK-NEXT:    [[I96:%.*]] = icmp eq ptr [[I94]], null
; CHECK-NEXT:    br i1 [[I96]], label %[[BB97:.*]], label %[[BB99:.*]]
; CHECK:       [[BB97]]:
; CHECK-NEXT:    [[I98:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.11, i32 noundef signext [[I88]]), !noalias [[META19]]
; CHECK-NEXT:    tail call void @exit(i32 noundef signext 1), !noalias [[META19]]
; CHECK-NEXT:    unreachable
; CHECK:       [[BB99]]:
; CHECK-NEXT:    [[I100:%.*]] = shl nsw i64 [[I93]], 4
; CHECK-NEXT:    [[I101:%.*]] = load i64, ptr @quantum_memman.mem, align 8, !tbaa [[TBAA24:![0-9]+]], !noalias [[META19]]
; CHECK-NEXT:    [[I102:%.*]] = add nsw i64 [[I101]], [[I100]]
; CHECK-NEXT:    store i64 [[I102]], ptr @quantum_memman.mem, align 8, !tbaa [[TBAA24]], !noalias [[META19]]
; CHECK-NEXT:    [[I103:%.*]] = load i64, ptr @quantum_memman.max, align 8, !tbaa [[TBAA24]], !noalias [[META19]]
; CHECK-NEXT:    [[I104:%.*]] = icmp sgt i64 [[I102]], [[I103]]
; CHECK-NEXT:    br i1 [[I104]], label %[[BB105:.*]], label %[[BB106:.*]]
; CHECK:       [[BB105]]:
; CHECK-NEXT:    store i64 [[I102]], ptr @quantum_memman.max, align 8, !tbaa [[TBAA24]], !noalias [[META19]]
; CHECK-NEXT:    br label %[[BB106]]
; CHECK:       [[BB106]]:
; CHECK-NEXT:    [[I107:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 2
; CHECK-NEXT:    [[I108:%.*]] = load i32, ptr [[I107]], align 8, !tbaa [[TBAA26:![0-9]+]], !noalias [[META19]]
; CHECK-NEXT:    [[I109:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I]], i64 0, i32 2
; CHECK-NEXT:    store i32 [[I108]], ptr [[I109]], align 8, !tbaa [[TBAA26]], !alias.scope [[META19]]
; CHECK-NEXT:    [[I110:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 4
; CHECK-NEXT:    [[I111:%.*]] = load ptr, ptr [[I110]], align 8, !tbaa [[TBAA27:![0-9]+]], !noalias [[META19]]
; CHECK-NEXT:    [[I112:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I]], i64 0, i32 4
; CHECK-NEXT:    store ptr [[I111]], ptr [[I112]], align 8, !tbaa [[TBAA27]], !alias.scope [[META19]]
; CHECK-NEXT:    [[I113:%.*]] = load i32, ptr [[I55]], align 4, !tbaa [[TBAA0]], !noalias [[META19]]
; CHECK-NEXT:    [[I114:%.*]] = icmp sgt i32 [[I113]], 0
; CHECK-NEXT:    br i1 [[I114]], label %[[BB115:.*]], label %[[BB323:.*]]
; CHECK:       [[BB115]]:
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 6
; CHECK-NEXT:    [[I116:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[I2]], i64 0, i32 5
; CHECK-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
; CHECK-NEXT:    [[I117:%.*]] = load ptr, ptr [[I116]], align 8, !tbaa [[TBAA8]], !noalias [[META19]]
; CHECK-NEXT:    [[I118:%.*]] = icmp sgt i32 [[ARG]], 0
; CHECK-NEXT:    [[I119:%.*]] = icmp slt i32 [[ARG]], 63
; CHECK-NEXT:    [[I120:%.*]] = tail call fast double @llvm.sqrt.f64(double [[I89]])
; CHECK-NEXT:    [[I121:%.*]] = fptrunc double [[I120]] to float
; CHECK-NEXT:    [[I122:%.*]] = fdiv fast float 1.000000e+00, [[I121]]
; CHECK-NEXT:    [[I123:%.*]] = zext nneg i32 [[I113]] to i64
; CHECK-NEXT:    br i1 [[I119]], label %[[BB127:.*]], label %[[BB124:.*]]
; CHECK:       [[BB124]]:
; CHECK-NEXT:    [[I125:%.*]] = and i64 [[I53]], 7
; CHECK-NEXT:    [[I126:%.*]] = and i64 [[I53]], 2147483640
; CHECK-NEXT:    br label %[[BB277:.*]]
; CHECK:       [[BB127]]:
; CHECK-NEXT:    [[I128:%.*]] = sub i32 63, [[ARG]]
; CHECK-NEXT:    [[I129:%.*]] = icmp ult i32 [[I128]], 13
; CHECK-NEXT:    br i1 [[I129]], label %[[BB134:.*]], label %[[BB130:.*]]
; CHECK:       [[BB130]]:
; CHECK-NEXT:    [[I131:%.*]] = and i64 [[I53]], 7
; CHECK-NEXT:    [[I132:%.*]] = icmp ult i32 [[ARG]], 8
; CHECK-NEXT:    [[I133:%.*]] = and i64 [[I53]], 2147483640
; CHECK-NEXT:    br label %[[BB202:.*]]
; CHECK:       [[BB134]]:
; CHECK-NEXT:    [[I135:%.*]] = and i64 [[I53]], 7
; CHECK-NEXT:    [[I136:%.*]] = icmp ult i32 [[ARG]], 8
; CHECK-NEXT:    [[I137:%.*]] = and i64 [[I53]], 2147483640
; CHECK-NEXT:    br label %[[BB138:.*]]
; CHECK:       [[BB138]]:
; CHECK-NEXT:    [[I139:%.*]] = phi i64 [ [[I167:%.*]], %[[BB165:.*]] ], [ 0, %[[BB134]] ]
; CHECK-NEXT:    [[I140:%.*]] = phi i32 [ [[I166:%.*]], %[[BB165]] ], [ 0, %[[BB134]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i64, ptr [[TMP11]], i64 [[I139]]
; CHECK-NEXT:    [[I142:%.*]] = load i64, ptr [[TMP12]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[I143:%.*]] = and i64 [[I142]], [[I54]]
; CHECK-NEXT:    [[I144:%.*]] = icmp ne i64 [[I143]], 0
; CHECK-NEXT:    [[I145:%.*]] = xor i1 [[I51]], [[I144]]
; CHECK-NEXT:    br i1 [[I145]], label %[[BB165]], label %[[BB146:.*]]
; CHECK:       [[BB146]]:
; CHECK-NEXT:    br i1 [[I118]], label %[[BB147:.*]], label %[[BB184:.*]]
; CHECK:       [[BB147]]:
; CHECK-NEXT:    br i1 [[I136]], label %[[BB169:.*]], label %[[BB148:.*]]
; CHECK:       [[BB148]]:
; CHECK-NEXT:    [[I149:%.*]] = phi i64 [ [[I154:%.*]], %[[BB148]] ], [ 0, %[[BB147]] ]
; CHECK-NEXT:    [[I150:%.*]] = phi i64 [ [[I153:%.*]], %[[BB148]] ], [ 0, %[[BB147]] ]
; CHECK-NEXT:    [[I151:%.*]] = phi i64 [ [[I155:%.*]], %[[BB148]] ], [ 0, %[[BB147]] ]
; CHECK-NEXT:    [[I152:%.*]] = shl i64 255, [[I149]]
; CHECK-NEXT:    [[I153]] = add i64 [[I152]], [[I150]]
; CHECK-NEXT:    [[I154]] = add nuw nsw i64 [[I149]], 8
; CHECK-NEXT:    [[I155]] = add i64 [[I151]], 8
; CHECK-NEXT:    [[I156:%.*]] = icmp eq i64 [[I155]], [[I137]]
; CHECK-NEXT:    br i1 [[I156]], label %[[BB169]], label %[[BB148]], !llvm.loop [[LOOP28:![0-9]+]]
; CHECK:       [[BB157:.*]]:
; CHECK-NEXT:    [[I158:%.*]] = phi i32 [ 63, %[[BB184]] ], [ [[I163:%.*]], %[[BB157]] ]
; CHECK-NEXT:    [[I159:%.*]] = phi i64 [ 0, %[[BB184]] ], [ [[I162:%.*]], %[[BB157]] ]
; CHECK-NEXT:    [[I160:%.*]] = zext nneg i32 [[I158]] to i64
; CHECK-NEXT:    [[I161:%.*]] = shl nuw i64 1, [[I160]]
; CHECK-NEXT:    [[I162]] = add i64 [[I161]], [[I159]]
; CHECK-NEXT:    [[I163]] = add nsw i32 [[I158]], -1
; CHECK-NEXT:    [[I164:%.*]] = icmp sgt i32 [[I163]], [[ARG]]
; CHECK-NEXT:    br i1 [[I164]], label %[[BB157]], label %[[BB186:.*]], !llvm.loop [[LOOP29:![0-9]+]]
; CHECK:       [[BB165]]:
; CHECK-NEXT:    [[I166]] = phi i32 [ [[I201:%.*]], %[[BB186]] ], [ [[I140]], %[[BB138]] ]
; CHECK-NEXT:    [[I167]] = add nuw nsw i64 [[I139]], 1
; CHECK-NEXT:    [[I168:%.*]] = icmp eq i64 [[I167]], [[I123]]
; CHECK-NEXT:    br i1 [[I168]], label %[[BB323]], label %[[BB138]], !llvm.loop [[LOOP32:![0-9]+]]
; CHECK:       [[BB169]]:
; CHECK-NEXT:    [[I170:%.*]] = phi i64 [ poison, %[[BB147]] ], [ [[I153]], %[[BB148]] ]
; CHECK-NEXT:    [[I171:%.*]] = phi i64 [ 0, %[[BB147]] ], [ [[I154]], %[[BB148]] ]
; CHECK-NEXT:    [[I172:%.*]] = phi i64 [ 0, %[[BB147]] ], [ [[I153]], %[[BB148]] ]
; CHECK-NEXT:    switch i64 [[I135]], label %[[BB173:.*]] [
; CHECK-NEXT:      i64 0, label %[[BB184]]
; CHECK-NEXT:      i64 1, label %[[BB180:.*]]
; CHECK-NEXT:      i64 2, label %[[BB175:.*]]
; CHECK-NEXT:      i64 3, label %[[BB176:.*]]
; CHECK-NEXT:      i64 4, label %[[BB177:.*]]
; CHECK-NEXT:      i64 5, label %[[BB178:.*]]
; CHECK-NEXT:      i64 6, label %[[BB179:.*]]
; CHECK-NEXT:      i64 7, label %[[BB174:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[BB173]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[BB174]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB175]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB176]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB177]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB178]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB179]]:
; CHECK-NEXT:    br label %[[BB180]]
; CHECK:       [[BB180]]:
; CHECK-NEXT:    [[I181:%.*]] = phi i64 [ 127, %[[BB174]] ], [ 1, %[[BB169]] ], [ 3, %[[BB175]] ], [ 7, %[[BB176]] ], [ 15, %[[BB177]] ], [ 31, %[[BB178]] ], [ 63, %[[BB179]] ]
; CHECK-NEXT:    [[I182:%.*]] = shl i64 [[I181]], [[I171]]
; CHECK-NEXT:    [[I183:%.*]] = add i64 [[I182]], [[I172]]
; CHECK-NEXT:    br label %[[BB184]]
; CHECK:       [[BB184]]:
; CHECK-NEXT:    [[I185:%.*]] = phi i64 [ 0, %[[BB146]] ], [ [[I170]], %[[BB169]] ], [ [[I183]], %[[BB180]] ]
; CHECK-NEXT:    br label %[[BB157]]
; CHECK:       [[BB186]]:
; CHECK-NEXT:    [[I187:%.*]] = and i64 [[I185]], [[I142]]
; CHECK-NEXT:    [[I188:%.*]] = and i64 [[I162]], [[I142]]
; CHECK-NEXT:    [[I189:%.*]] = lshr i64 [[I188]], 1
; CHECK-NEXT:    [[I190:%.*]] = or i64 [[I189]], [[I187]]
; CHECK-NEXT:    [[I191:%.*]] = sext i32 [[I140]] to i64
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[TMP8]], i64 0, i32 6
; CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[TMP13]], align 8
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[TMP17]], i64 [[I191]]
; CHECK-NEXT:    store i64 [[I190]], ptr [[TMP28]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds { float, float }, ptr [[I117]], i64 [[I139]]
; CHECK-NEXT:    [[I194:%.*]] = load float, ptr [[TMP14]], align 8, !noalias [[META19]]
; CHECK-NEXT:    [[I195:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP14]], i64 0, i32 1
; CHECK-NEXT:    [[I196:%.*]] = load float, ptr [[I195]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I197:%.*]] = fmul fast float [[I194]], [[I122]]
; CHECK-NEXT:    [[I198:%.*]] = fmul fast float [[I196]], [[I122]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds { float, float }, ptr [[I94]], i64 [[I191]]
; CHECK-NEXT:    [[I200:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP15]], i64 0, i32 1
; CHECK-NEXT:    store float [[I197]], ptr [[TMP15]], align 8, !noalias [[META19]]
; CHECK-NEXT:    store float [[I198]], ptr [[I200]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I201]] = add nsw i32 [[I140]], 1
; CHECK-NEXT:    br label %[[BB165]]
; CHECK:       [[BB202]]:
; CHECK-NEXT:    [[I203:%.*]] = phi i64 [ [[I273:%.*]], %[[BB271:.*]] ], [ 0, %[[BB130]] ]
; CHECK-NEXT:    [[I204:%.*]] = phi i32 [ [[I272:%.*]], %[[BB271]] ], [ 0, %[[BB130]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[TMP11]], i64 [[I203]]
; CHECK-NEXT:    [[I206:%.*]] = load i64, ptr [[TMP16]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[I207:%.*]] = and i64 [[I206]], [[I54]]
; CHECK-NEXT:    [[I208:%.*]] = icmp ne i64 [[I207]], 0
; CHECK-NEXT:    [[I209:%.*]] = xor i1 [[I51]], [[I208]]
; CHECK-NEXT:    br i1 [[I209]], label %[[BB271]], label %[[BB275:.*]]
; CHECK:       [[BB210:.*]]:
; CHECK-NEXT:    [[I211:%.*]] = phi i64 [ poison, %[[BB276:.*]] ], [ [[I267:%.*]], %[[BB262:.*]] ]
; CHECK-NEXT:    [[I212:%.*]] = phi i64 [ 0, %[[BB276]] ], [ [[I268:%.*]], %[[BB262]] ]
; CHECK-NEXT:    [[I213:%.*]] = phi i64 [ 0, %[[BB276]] ], [ [[I267]], %[[BB262]] ]
; CHECK-NEXT:    switch i64 [[I131]], label %[[BB173]] [
; CHECK-NEXT:      i64 0, label %[[BB224:.*]]
; CHECK-NEXT:      i64 1, label %[[BB220:.*]]
; CHECK-NEXT:      i64 2, label %[[BB215:.*]]
; CHECK-NEXT:      i64 3, label %[[BB216:.*]]
; CHECK-NEXT:      i64 4, label %[[BB217:.*]]
; CHECK-NEXT:      i64 5, label %[[BB218:.*]]
; CHECK-NEXT:      i64 6, label %[[BB219:.*]]
; CHECK-NEXT:      i64 7, label %[[BB214:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[BB214]]:
; CHECK-NEXT:    br label %[[BB220]]
; CHECK:       [[BB215]]:
; CHECK-NEXT:    br label %[[BB220]]
; CHECK:       [[BB216]]:
; CHECK-NEXT:    br label %[[BB220]]
; CHECK:       [[BB217]]:
; CHECK-NEXT:    br label %[[BB220]]
; CHECK:       [[BB218]]:
; CHECK-NEXT:    br label %[[BB220]]
; CHECK:       [[BB219]]:
; CHECK-NEXT:    br label %[[BB220]]
; CHECK:       [[BB220]]:
; CHECK-NEXT:    [[I221:%.*]] = phi i64 [ 127, %[[BB214]] ], [ 1, %[[BB210]] ], [ 3, %[[BB215]] ], [ 7, %[[BB216]] ], [ 15, %[[BB217]] ], [ 31, %[[BB218]] ], [ 63, %[[BB219]] ]
; CHECK-NEXT:    [[I222:%.*]] = shl i64 [[I221]], [[I212]]
; CHECK-NEXT:    [[I223:%.*]] = add i64 [[I222]], [[I213]]
; CHECK-NEXT:    br label %[[BB224]]
; CHECK:       [[BB224]]:
; CHECK-NEXT:    [[I225:%.*]] = phi i64 [ 0, %[[BB275]] ], [ [[I211]], %[[BB210]] ], [ [[I223]], %[[BB220]] ]
; CHECK-NEXT:    [[I226:%.*]] = tail call i32 @llvm.experimental.get.vector.length.i32(i32 [[I128]], i32 4, i1 true)
; CHECK-NEXT:    [[I227:%.*]] = tail call <vscale x 4 x i32> @llvm.stepvector.nxv4i32()
; CHECK-NEXT:    [[I228:%.*]] = sub <vscale x 4 x i32> splat (i32 63), [[I227]]
; CHECK-NEXT:    br label %[[BB229:.*]]
; CHECK:       [[BB229]]:
; CHECK-NEXT:    [[I230:%.*]] = phi i32 [ 0, %[[BB224]] ], [ [[I239:%.*]], %[[BB229]] ]
; CHECK-NEXT:    [[I231:%.*]] = phi <vscale x 4 x i32> [ [[I228]], %[[BB224]] ], [ [[I243:%.*]], %[[BB229]] ]
; CHECK-NEXT:    [[I232:%.*]] = phi <vscale x 4 x i64> [ zeroinitializer, %[[BB224]] ], [ [[I238:%.*]], %[[BB229]] ]
; CHECK-NEXT:    [[I233:%.*]] = sub i32 [[I128]], [[I230]]
; CHECK-NEXT:    [[I234:%.*]] = tail call i32 @llvm.experimental.get.vector.length.i32(i32 [[I233]], i32 4, i1 true)
; CHECK-NEXT:    [[I235:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.zext.nxv4i64.nxv4i32(<vscale x 4 x i32> [[I231]], <vscale x 4 x i1> splat (i1 true), i32 [[I234]])
; CHECK-NEXT:    [[I236:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.shl.nxv4i64(<vscale x 4 x i64> splat (i64 1), <vscale x 4 x i64> [[I235]], <vscale x 4 x i1> splat (i1 true), i32 [[I234]])
; CHECK-NEXT:    [[I237:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.add.nxv4i64(<vscale x 4 x i64> [[I236]], <vscale x 4 x i64> [[I232]], <vscale x 4 x i1> splat (i1 true), i32 [[I234]])
; CHECK-NEXT:    [[I238]] = tail call <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i64> [[I237]], <vscale x 4 x i64> [[I232]], i32 [[I234]])
; CHECK-NEXT:    [[I239]] = add i32 [[I234]], [[I230]]
; CHECK-NEXT:    [[I240:%.*]] = sub i32 0, [[I234]]
; CHECK-NEXT:    [[I241:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[I240]], i64 0
; CHECK-NEXT:    [[I242:%.*]] = shufflevector <vscale x 4 x i32> [[I241]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    [[I243]] = tail call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[I231]], <vscale x 4 x i32> [[I242]], <vscale x 4 x i1> splat (i1 true), i32 [[I234]])
; CHECK-NEXT:    [[I244:%.*]] = icmp eq i32 [[I239]], [[I128]]
; CHECK-NEXT:    br i1 [[I244]], label %[[BB245:.*]], label %[[BB229]], !llvm.loop [[LOOP33:![0-9]+]]
; CHECK:       [[BB245]]:
; CHECK-NEXT:    [[I246:%.*]] = tail call i64 @llvm.vp.reduce.add.nxv4i64(i64 0, <vscale x 4 x i64> [[I238]], <vscale x 4 x i1> splat (i1 true), i32 [[I226]])
; CHECK-NEXT:    [[I247:%.*]] = and i64 [[I225]], [[I206]]
; CHECK-NEXT:    [[I248:%.*]] = and i64 [[I246]], [[I206]]
; CHECK-NEXT:    [[I249:%.*]] = lshr i64 [[I248]], 1
; CHECK-NEXT:    [[I250:%.*]] = or i64 [[I249]], [[I247]]
; CHECK-NEXT:    [[I251:%.*]] = sext i32 [[I204]] to i64
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[TMP8]], i64 0, i32 6
; CHECK-NEXT:    [[TMP30:%.*]] = load ptr, ptr [[TMP29]], align 8
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i64, ptr [[TMP30]], i64 [[I251]]
; CHECK-NEXT:    store i64 [[I250]], ptr [[TMP21]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds { float, float }, ptr [[I117]], i64 [[I203]]
; CHECK-NEXT:    [[I254:%.*]] = load float, ptr [[TMP18]], align 8, !noalias [[META19]]
; CHECK-NEXT:    [[I255:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP18]], i64 0, i32 1
; CHECK-NEXT:    [[I256:%.*]] = load float, ptr [[I255]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I257:%.*]] = fmul fast float [[I254]], [[I122]]
; CHECK-NEXT:    [[I258:%.*]] = fmul fast float [[I256]], [[I122]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds { float, float }, ptr [[I94]], i64 [[I251]]
; CHECK-NEXT:    [[I260:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP19]], i64 0, i32 1
; CHECK-NEXT:    store float [[I257]], ptr [[TMP19]], align 8, !noalias [[META19]]
; CHECK-NEXT:    store float [[I258]], ptr [[I260]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I261:%.*]] = add nsw i32 [[I204]], 1
; CHECK-NEXT:    br label %[[BB271]]
; CHECK:       [[BB262]]:
; CHECK-NEXT:    [[I263:%.*]] = phi i64 [ [[I268]], %[[BB262]] ], [ 0, %[[BB276]] ]
; CHECK-NEXT:    [[I264:%.*]] = phi i64 [ [[I267]], %[[BB262]] ], [ 0, %[[BB276]] ]
; CHECK-NEXT:    [[I265:%.*]] = phi i64 [ [[I269:%.*]], %[[BB262]] ], [ 0, %[[BB276]] ]
; CHECK-NEXT:    [[I266:%.*]] = shl i64 255, [[I263]]
; CHECK-NEXT:    [[I267]] = add i64 [[I266]], [[I264]]
; CHECK-NEXT:    [[I268]] = add nuw nsw i64 [[I263]], 8
; CHECK-NEXT:    [[I269]] = add i64 [[I265]], 8
; CHECK-NEXT:    [[I270:%.*]] = icmp eq i64 [[I269]], [[I133]]
; CHECK-NEXT:    br i1 [[I270]], label %[[BB210]], label %[[BB262]], !llvm.loop [[LOOP28]]
; CHECK:       [[BB271]]:
; CHECK-NEXT:    [[I272]] = phi i32 [ [[I261]], %[[BB245]] ], [ [[I204]], %[[BB202]] ]
; CHECK-NEXT:    [[I273]] = add nuw nsw i64 [[I203]], 1
; CHECK-NEXT:    [[I274:%.*]] = icmp eq i64 [[I273]], [[I123]]
; CHECK-NEXT:    br i1 [[I274]], label %[[BB323]], label %[[BB202]], !llvm.loop [[LOOP32]]
; CHECK:       [[BB275]]:
; CHECK-NEXT:    br i1 [[I118]], label %[[BB276]], label %[[BB224]]
; CHECK:       [[BB276]]:
; CHECK-NEXT:    br i1 [[I132]], label %[[BB210]], label %[[BB262]]
; CHECK:       [[BB277]]:
; CHECK-NEXT:    [[I278:%.*]] = phi i64 [ [[I296:%.*]], %[[BB294:.*]] ], [ 0, %[[BB124]] ]
; CHECK-NEXT:    [[I279:%.*]] = phi i32 [ [[I295:%.*]], %[[BB294]] ], [ 0, %[[BB124]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i64, ptr [[TMP11]], i64 [[I278]]
; CHECK-NEXT:    [[I281:%.*]] = load i64, ptr [[TMP20]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[I282:%.*]] = and i64 [[I281]], [[I54]]
; CHECK-NEXT:    [[I283:%.*]] = icmp ne i64 [[I282]], 0
; CHECK-NEXT:    [[I284:%.*]] = xor i1 [[I51]], [[I283]]
; CHECK-NEXT:    br i1 [[I284]], label %[[BB294]], label %[[BB285:.*]]
; CHECK:       [[BB285]]:
; CHECK-NEXT:    [[I286:%.*]] = phi i64 [ [[I291:%.*]], %[[BB285]] ], [ 0, %[[BB277]] ]
; CHECK-NEXT:    [[I287:%.*]] = phi i64 [ [[I290:%.*]], %[[BB285]] ], [ 0, %[[BB277]] ]
; CHECK-NEXT:    [[I288:%.*]] = phi i64 [ [[I292:%.*]], %[[BB285]] ], [ 0, %[[BB277]] ]
; CHECK-NEXT:    [[I289:%.*]] = shl i64 255, [[I286]]
; CHECK-NEXT:    [[I290]] = add i64 [[I289]], [[I287]]
; CHECK-NEXT:    [[I291]] = add nuw nsw i64 [[I286]], 8
; CHECK-NEXT:    [[I292]] = add nuw nsw i64 [[I288]], 8
; CHECK-NEXT:    [[I293:%.*]] = icmp eq i64 [[I292]], [[I126]]
; CHECK-NEXT:    br i1 [[I293]], label %[[BB298:.*]], label %[[BB285]], !llvm.loop [[LOOP28]]
; CHECK:       [[BB294]]:
; CHECK-NEXT:    [[I295]] = phi i32 [ [[I322:%.*]], %[[BB309:.*]] ], [ [[I279]], %[[BB277]] ]
; CHECK-NEXT:    [[I296]] = add nuw nsw i64 [[I278]], 1
; CHECK-NEXT:    [[I297:%.*]] = icmp eq i64 [[I296]], [[I123]]
; CHECK-NEXT:    br i1 [[I297]], label %[[BB323]], label %[[BB277]], !llvm.loop [[LOOP32]]
; CHECK:       [[BB298]]:
; CHECK-NEXT:    switch i64 [[I125]], label %[[BB173]] [
; CHECK-NEXT:      i64 0, label %[[BB309]]
; CHECK-NEXT:      i64 1, label %[[BB305:.*]]
; CHECK-NEXT:      i64 2, label %[[BB300:.*]]
; CHECK-NEXT:      i64 3, label %[[BB301:.*]]
; CHECK-NEXT:      i64 4, label %[[BB302:.*]]
; CHECK-NEXT:      i64 5, label %[[BB303:.*]]
; CHECK-NEXT:      i64 6, label %[[BB304:.*]]
; CHECK-NEXT:      i64 7, label %[[BB299:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[BB299]]:
; CHECK-NEXT:    br label %[[BB305]]
; CHECK:       [[BB300]]:
; CHECK-NEXT:    br label %[[BB305]]
; CHECK:       [[BB301]]:
; CHECK-NEXT:    br label %[[BB305]]
; CHECK:       [[BB302]]:
; CHECK-NEXT:    br label %[[BB305]]
; CHECK:       [[BB303]]:
; CHECK-NEXT:    br label %[[BB305]]
; CHECK:       [[BB304]]:
; CHECK-NEXT:    br label %[[BB305]]
; CHECK:       [[BB305]]:
; CHECK-NEXT:    [[I306:%.*]] = phi i64 [ 127, %[[BB299]] ], [ 1, %[[BB298]] ], [ 3, %[[BB300]] ], [ 7, %[[BB301]] ], [ 15, %[[BB302]] ], [ 31, %[[BB303]] ], [ 63, %[[BB304]] ]
; CHECK-NEXT:    [[I307:%.*]] = shl i64 [[I306]], [[I291]]
; CHECK-NEXT:    [[I308:%.*]] = add i64 [[I307]], [[I290]]
; CHECK-NEXT:    br label %[[BB309]]
; CHECK:       [[BB309]]:
; CHECK-NEXT:    [[I310:%.*]] = phi i64 [ [[I290]], %[[BB298]] ], [ [[I308]], %[[BB305]] ]
; CHECK-NEXT:    [[I311:%.*]] = and i64 [[I310]], [[I281]]
; CHECK-NEXT:    [[I312:%.*]] = sext i32 [[I279]] to i64
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[TMP8]], i64 0, i32 6
; CHECK-NEXT:    [[TMP26:%.*]] = load ptr, ptr [[TMP31]], align 8
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i64, ptr [[TMP26]], i64 [[I312]]
; CHECK-NEXT:    store i64 [[I311]], ptr [[TMP27]], align 8, !tbaa [[TBAA9]], !noalias [[META19]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds { float, float }, ptr [[I117]], i64 [[I278]]
; CHECK-NEXT:    [[I315:%.*]] = load float, ptr [[TMP22]], align 8, !noalias [[META19]]
; CHECK-NEXT:    [[I316:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP22]], i64 0, i32 1
; CHECK-NEXT:    [[I317:%.*]] = load float, ptr [[I316]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I318:%.*]] = fmul fast float [[I315]], [[I122]]
; CHECK-NEXT:    [[I319:%.*]] = fmul fast float [[I317]], [[I122]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds { float, float }, ptr [[I94]], i64 [[I312]]
; CHECK-NEXT:    [[I321:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[TMP23]], i64 0, i32 1
; CHECK-NEXT:    store float [[I318]], ptr [[TMP23]], align 8, !noalias [[META19]]
; CHECK-NEXT:    store float [[I319]], ptr [[I321]], align 4, !noalias [[META19]]
; CHECK-NEXT:    [[I322]] = add nsw i32 [[I279]], 1
; CHECK-NEXT:    br label %[[BB294]]
; CHECK:       [[BB323]]:
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[I2]])
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 6
; CHECK-NEXT:    [[I324:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 5
; CHECK-NEXT:    [[I325:%.*]] = load ptr, ptr [[I324]], align 8, !tbaa [[TBAA8]]
; CHECK-NEXT:    [[TMP25:%.*]] = load ptr, ptr [[TMP24]], align 8
; CHECK-NEXT:    tail call void @free(ptr noundef [[I325]])
; CHECK-NEXT:    tail call void @free(ptr noundef [[TMP25]])
; CHECK-NEXT:    [[I326:%.*]] = getelementptr inbounds nuw [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 1
; CHECK-NEXT:    [[I327:%.*]] = load i32, ptr [[I326]], align 4, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[I328:%.*]] = sub nsw i32 0, [[I327]]
; CHECK-NEXT:    [[I329:%.*]] = sext i32 [[I328]] to i64
; CHECK-NEXT:    [[I330:%.*]] = shl nsw i64 [[I329]], 4
; CHECK-NEXT:    [[I331:%.*]] = load i64, ptr @quantum_memman.mem, align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[I332:%.*]] = add nsw i64 [[I330]], [[I331]]
; CHECK-NEXT:    store i64 [[I332]], ptr @quantum_memman.mem, align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[I333:%.*]] = load i64, ptr @quantum_memman.max, align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    [[I334:%.*]] = icmp sgt i64 [[I332]], [[I333]]
; CHECK-NEXT:    br i1 [[I334]], label %[[BB335:.*]], label %[[BB336:.*]]
; CHECK:       [[BB335]]:
; CHECK-NEXT:    store i64 [[I332]], ptr @quantum_memman.max, align 8, !tbaa [[TBAA24]]
; CHECK-NEXT:    br label %[[BB336]]
; CHECK:       [[BB336]]:
; CHECK-NEXT:    store ptr null, ptr [[TMP24]], align 8
; CHECK-NEXT:    store ptr null, ptr [[I324]], align 8, !tbaa [[TBAA8]]
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(48) [[ARG1]], ptr noundef nonnull align 8 dereferenceable(48) [[I]], i64 48, i1 false), !tbaa [[TBAA15]], !tbaa.struct [[TBAA_STRUCT16]]
; CHECK-NEXT:    br label %[[BB337]]
; CHECK:       [[BB337]]:
; CHECK-NEXT:    [[I338:%.*]] = phi i32 [ [[I52]], %[[BB336]] ], [ 0, %[[BB]] ]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[I]])
; CHECK-NEXT:    ret i32 [[I338]]
;
bb:
  %i = alloca %struct.quantum_reg_struct, align 8
  %i2 = alloca %struct.quantum_reg_struct, align 8
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %i)
  %i3 = tail call signext i32 (i8, ...) @quantum_objcode_put(i8 noundef zeroext -127, i32 noundef signext %arg) #14
  %i4 = icmp eq i32 %i3, 0
  br i1 %i4, label %bb5, label %bb337

bb5:                                              ; preds = %bb
  %i6 = zext nneg i32 %arg to i64
  %i7 = shl nuw i64 1, %i6
  %i8 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 1
  %i9 = load i32, ptr %i8, align 4, !tbaa !11
  %i10 = icmp sgt i32 %i9, 0
  br i1 %i10, label %bb11, label %bb36

bb11:                                             ; preds = %bb5
  %i12 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 3
  %i13 = load ptr, ptr %i12, align 8, !tbaa !19
  %i14 = zext nneg i32 %i9 to i64
  br label %bb15

bb15:                                             ; preds = %bb32, %bb11
  %i16 = phi i64 [ 0, %bb11 ], [ %i34, %bb32 ]
  %i17 = phi double [ 0.000000e+00, %bb11 ], [ %i33, %bb32 ]
  %i18 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i13, i64 %i16, i32 1
  %i19 = load i64, ptr %i18, align 8, !tbaa !20
  %i20 = and i64 %i19, %i7
  %i21 = icmp eq i64 %i20, 0
  br i1 %i21, label %bb22, label %bb32

bb22:                                             ; preds = %bb15
  %i23 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i13, i64 %i16
  %i24 = load float, ptr %i23, align 8
  %i25 = getelementptr inbounds nuw { float, float }, ptr %i23, i64 0, i32 1
  %i26 = load float, ptr %i25, align 4
  %i27 = fmul fast float %i24, %i24
  %i28 = fmul fast float %i26, %i26
  %i29 = fadd fast float %i28, %i27
  %i30 = fpext float %i29 to double
  %i31 = fadd fast double %i17, %i30
  br label %bb32

bb32:                                             ; preds = %bb22, %bb15
  %i33 = phi nsz double [ %i17, %bb15 ], [ %i31, %bb22 ]
  %i34 = add nuw nsw i64 %i16, 1
  %i35 = icmp eq i64 %i34, %i14
  br i1 %i35, label %bb36, label %bb15, !llvm.loop !23

bb36:                                             ; preds = %bb32, %bb5
  %i37 = phi double [ 0.000000e+00, %bb5 ], [ %i33, %bb32 ]
  %i38 = load i32, ptr @seedi, align 4, !tbaa !25
  %i39 = freeze i32 %i38
  %i40 = sdiv i32 %i39, 127773
  %i41 = mul i32 %i40, -127773
  %i42 = add i32 %i41, %i39
  %i43 = mul nsw i32 %i42, 16807
  %i44 = mul nsw i32 %i40, -2836
  %i45 = add i32 %i43, %i44
  %i46 = icmp sgt i32 %i45, 0
  %i47 = add i32 %i45, 2147483647
  %i48 = select i1 %i46, i32 %i45, i32 %i47
  store i32 %i48, ptr @seedi, align 4, !tbaa !25
  %i49 = sitofp i32 %i48 to double
  %i50 = fmul fast double %i49, 0x3E00000000200000
  %i51 = fcmp fast ogt double %i50, %i37
  %i52 = zext i1 %i51 to i32
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %i2) #14
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) %i2, ptr noundef nonnull align 8 dereferenceable(32) %arg1, i64 32, i1 false), !tbaa !26, !tbaa.struct !27
  tail call void @llvm.experimental.noalias.scope.decl(metadata !30)
  %i53 = zext i32 %arg to i64
  %i54 = shl nuw i64 1, %i53
  %i55 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i2, i64 0, i32 1
  %i56 = load i32, ptr %i55, align 4, !tbaa !11, !noalias !30
  %i57 = icmp sgt i32 %i56, 0
  br i1 %i57, label %bb58, label %bb87

bb58:                                             ; preds = %bb36
  %i59 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i2, i64 0, i32 3
  %i60 = load ptr, ptr %i59, align 8, !tbaa !19, !noalias !30
  %i61 = zext nneg i32 %i56 to i64
  br label %bb62

bb62:                                             ; preds = %bb82, %bb58
  %i63 = phi i64 [ 0, %bb58 ], [ %i85, %bb82 ]
  %i64 = phi double [ 0.000000e+00, %bb58 ], [ %i84, %bb82 ]
  %i65 = phi i32 [ 0, %bb58 ], [ %i83, %bb82 ]
  %i66 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i60, i64 %i63, i32 1
  %i67 = load i64, ptr %i66, align 8, !tbaa !20, !noalias !30
  %i68 = and i64 %i67, %i54
  %i69 = icmp ne i64 %i68, 0
  %i70 = xor i1 %i51, %i69
  br i1 %i70, label %bb82, label %bb71

bb71:                                             ; preds = %bb62
  %i72 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i60, i64 %i63
  %i73 = load float, ptr %i72, align 8, !noalias !30
  %i74 = getelementptr inbounds nuw { float, float }, ptr %i72, i64 0, i32 1
  %i75 = load float, ptr %i74, align 4, !noalias !30
  %i76 = fmul fast float %i73, %i73
  %i77 = fmul fast float %i75, %i75
  %i78 = fadd fast float %i77, %i76
  %i79 = fpext float %i78 to double
  %i80 = fadd fast double %i64, %i79
  %i81 = add nsw i32 %i65, 1
  br label %bb82

bb82:                                             ; preds = %bb71, %bb62
  %i83 = phi i32 [ %i81, %bb71 ], [ %i65, %bb62 ]
  %i84 = phi nsz double [ %i80, %bb71 ], [ %i64, %bb62 ]
  %i85 = add nuw nsw i64 %i63, 1
  %i86 = icmp eq i64 %i85, %i61
  br i1 %i86, label %bb87, label %bb62, !llvm.loop !33

bb87:                                             ; preds = %bb82, %bb36
  %i88 = phi i32 [ 0, %bb36 ], [ %i83, %bb82 ]
  %i89 = phi double [ 0.000000e+00, %bb36 ], [ %i84, %bb82 ]
  %i90 = load i32, ptr %i2, align 8, !tbaa !34, !noalias !30
  %i91 = add nsw i32 %i90, -1
  store i32 %i91, ptr %i, align 8, !tbaa !34, !alias.scope !30
  %i92 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i, i64 0, i32 1
  store i32 %i88, ptr %i92, align 4, !tbaa !11, !alias.scope !30
  %i93 = sext i32 %i88 to i64
  %i94 = tail call noalias ptr @calloc(i64 noundef %i93, i64 noundef 16) #15
  %i95 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i, i64 0, i32 3
  store ptr %i94, ptr %i95, align 8, !tbaa !19, !alias.scope !30
  %i96 = icmp eq ptr %i94, null
  br i1 %i96, label %bb97, label %bb99

bb97:                                             ; preds = %bb87
  %i98 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.11, i32 noundef signext %i88), !noalias !30
  tail call void @exit(i32 noundef signext 1) #16, !noalias !30
  unreachable

bb99:                                             ; preds = %bb87
  %i100 = shl nsw i64 %i93, 4
  %i101 = load i64, ptr @quantum_memman.mem, align 8, !tbaa !35, !noalias !30
  %i102 = add nsw i64 %i101, %i100
  store i64 %i102, ptr @quantum_memman.mem, align 8, !tbaa !35, !noalias !30
  %i103 = load i64, ptr @quantum_memman.max, align 8, !tbaa !35, !noalias !30
  %i104 = icmp sgt i64 %i102, %i103
  br i1 %i104, label %bb105, label %bb106

bb105:                                            ; preds = %bb99
  store i64 %i102, ptr @quantum_memman.max, align 8, !tbaa !35, !noalias !30
  br label %bb106

bb106:                                            ; preds = %bb105, %bb99
  %i107 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i2, i64 0, i32 2
  %i108 = load i32, ptr %i107, align 8, !tbaa !37, !noalias !30
  %i109 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i, i64 0, i32 2
  store i32 %i108, ptr %i109, align 8, !tbaa !37, !alias.scope !30
  %i110 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i2, i64 0, i32 4
  %i111 = load ptr, ptr %i110, align 8, !tbaa !38, !noalias !30
  %i112 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i, i64 0, i32 4
  store ptr %i111, ptr %i112, align 8, !tbaa !38, !alias.scope !30
  %i113 = load i32, ptr %i55, align 4, !tbaa !11, !noalias !30
  %i114 = icmp sgt i32 %i113, 0
  br i1 %i114, label %bb115, label %bb323

bb115:                                            ; preds = %bb106
  %i116 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %i2, i64 0, i32 3
  %i117 = load ptr, ptr %i116, align 8, !tbaa !19, !noalias !30
  %i118 = icmp sgt i32 %arg, 0
  %i119 = icmp slt i32 %arg, 63
  %i120 = tail call fast double @llvm.sqrt.f64(double %i89)
  %i121 = fptrunc double %i120 to float
  %i122 = fdiv fast float 1.000000e+00, %i121
  %i123 = zext nneg i32 %i113 to i64
  br i1 %i119, label %bb127, label %bb124

bb124:                                            ; preds = %bb115
  %i125 = and i64 %i53, 7
  %i126 = and i64 %i53, 2147483640
  br label %bb277

bb127:                                            ; preds = %bb115
  %i128 = sub i32 63, %arg
  %i129 = icmp ult i32 %i128, 13
  br i1 %i129, label %bb134, label %bb130

bb130:                                            ; preds = %bb127
  %i131 = and i64 %i53, 7
  %i132 = icmp ult i32 %arg, 8
  %i133 = and i64 %i53, 2147483640
  br label %bb202

bb134:                                            ; preds = %bb127
  %i135 = and i64 %i53, 7
  %i136 = icmp ult i32 %arg, 8
  %i137 = and i64 %i53, 2147483640
  br label %bb138

bb138:                                            ; preds = %bb165, %bb134
  %i139 = phi i64 [ %i167, %bb165 ], [ 0, %bb134 ]
  %i140 = phi i32 [ %i166, %bb165 ], [ 0, %bb134 ]
  %i141 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i117, i64 %i139, i32 1
  %i142 = load i64, ptr %i141, align 8, !tbaa !20, !noalias !30
  %i143 = and i64 %i142, %i54
  %i144 = icmp ne i64 %i143, 0
  %i145 = xor i1 %i51, %i144
  br i1 %i145, label %bb165, label %bb146

bb146:                                            ; preds = %bb138
  br i1 %i118, label %bb147, label %bb184

bb147:                                            ; preds = %bb146
  br i1 %i136, label %bb169, label %bb148

bb148:                                            ; preds = %bb148, %bb147
  %i149 = phi i64 [ %i154, %bb148 ], [ 0, %bb147 ]
  %i150 = phi i64 [ %i153, %bb148 ], [ 0, %bb147 ]
  %i151 = phi i64 [ %i155, %bb148 ], [ 0, %bb147 ]
  %i152 = shl i64 255, %i149
  %i153 = add i64 %i152, %i150
  %i154 = add nuw nsw i64 %i149, 8
  %i155 = add i64 %i151, 8
  %i156 = icmp eq i64 %i155, %i137
  br i1 %i156, label %bb169, label %bb148, !llvm.loop !39

bb157:                                            ; preds = %bb184, %bb157
  %i158 = phi i32 [ 63, %bb184 ], [ %i163, %bb157 ]
  %i159 = phi i64 [ 0, %bb184 ], [ %i162, %bb157 ]
  %i160 = zext nneg i32 %i158 to i64
  %i161 = shl nuw i64 1, %i160
  %i162 = add i64 %i161, %i159
  %i163 = add nsw i32 %i158, -1
  %i164 = icmp sgt i32 %i163, %arg
  br i1 %i164, label %bb157, label %bb186, !llvm.loop !40

bb165:                                            ; preds = %bb186, %bb138
  %i166 = phi i32 [ %i201, %bb186 ], [ %i140, %bb138 ]
  %i167 = add nuw nsw i64 %i139, 1
  %i168 = icmp eq i64 %i167, %i123
  br i1 %i168, label %bb323, label %bb138, !llvm.loop !43

bb169:                                            ; preds = %bb148, %bb147
  %i170 = phi i64 [ poison, %bb147 ], [ %i153, %bb148 ]
  %i171 = phi i64 [ 0, %bb147 ], [ %i154, %bb148 ]
  %i172 = phi i64 [ 0, %bb147 ], [ %i153, %bb148 ]
  switch i64 %i135, label %bb173 [
  i64 0, label %bb184
  i64 1, label %bb180
  i64 2, label %bb175
  i64 3, label %bb176
  i64 4, label %bb177
  i64 5, label %bb178
  i64 6, label %bb179
  i64 7, label %bb174
  ]

bb173:                                            ; preds = %bb298, %bb210, %bb169
  unreachable

bb174:                                            ; preds = %bb169
  br label %bb180

bb175:                                            ; preds = %bb169
  br label %bb180

bb176:                                            ; preds = %bb169
  br label %bb180

bb177:                                            ; preds = %bb169
  br label %bb180

bb178:                                            ; preds = %bb169
  br label %bb180

bb179:                                            ; preds = %bb169
  br label %bb180

bb180:                                            ; preds = %bb179, %bb178, %bb177, %bb176, %bb175, %bb174, %bb169
  %i181 = phi i64 [ 127, %bb174 ], [ 1, %bb169 ], [ 3, %bb175 ], [ 7, %bb176 ], [ 15, %bb177 ], [ 31, %bb178 ], [ 63, %bb179 ]
  %i182 = shl i64 %i181, %i171
  %i183 = add i64 %i182, %i172
  br label %bb184

bb184:                                            ; preds = %bb180, %bb169, %bb146
  %i185 = phi i64 [ 0, %bb146 ], [ %i170, %bb169 ], [ %i183, %bb180 ]
  br label %bb157

bb186:                                            ; preds = %bb157
  %i187 = and i64 %i185, %i142
  %i188 = and i64 %i162, %i142
  %i189 = lshr i64 %i188, 1
  %i190 = or i64 %i189, %i187
  %i191 = sext i32 %i140 to i64
  %i192 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i94, i64 %i191, i32 1
  store i64 %i190, ptr %i192, align 8, !tbaa !20, !noalias !30
  %i193 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i117, i64 %i139
  %i194 = load float, ptr %i193, align 8, !noalias !30
  %i195 = getelementptr inbounds nuw { float, float }, ptr %i193, i64 0, i32 1
  %i196 = load float, ptr %i195, align 4, !noalias !30
  %i197 = fmul fast float %i194, %i122
  %i198 = fmul fast float %i196, %i122
  %i199 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i94, i64 %i191
  %i200 = getelementptr inbounds nuw { float, float }, ptr %i199, i64 0, i32 1
  store float %i197, ptr %i199, align 8, !noalias !30
  store float %i198, ptr %i200, align 4, !noalias !30
  %i201 = add nsw i32 %i140, 1
  br label %bb165

bb202:                                            ; preds = %bb271, %bb130
  %i203 = phi i64 [ %i273, %bb271 ], [ 0, %bb130 ]
  %i204 = phi i32 [ %i272, %bb271 ], [ 0, %bb130 ]
  %i205 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i117, i64 %i203, i32 1
  %i206 = load i64, ptr %i205, align 8, !tbaa !20, !noalias !30
  %i207 = and i64 %i206, %i54
  %i208 = icmp ne i64 %i207, 0
  %i209 = xor i1 %i51, %i208
  br i1 %i209, label %bb271, label %bb275

bb210:                                            ; preds = %bb276, %bb262
  %i211 = phi i64 [ poison, %bb276 ], [ %i267, %bb262 ]
  %i212 = phi i64 [ 0, %bb276 ], [ %i268, %bb262 ]
  %i213 = phi i64 [ 0, %bb276 ], [ %i267, %bb262 ]
  switch i64 %i131, label %bb173 [
  i64 0, label %bb224
  i64 1, label %bb220
  i64 2, label %bb215
  i64 3, label %bb216
  i64 4, label %bb217
  i64 5, label %bb218
  i64 6, label %bb219
  i64 7, label %bb214
  ]

bb214:                                            ; preds = %bb210
  br label %bb220

bb215:                                            ; preds = %bb210
  br label %bb220

bb216:                                            ; preds = %bb210
  br label %bb220

bb217:                                            ; preds = %bb210
  br label %bb220

bb218:                                            ; preds = %bb210
  br label %bb220

bb219:                                            ; preds = %bb210
  br label %bb220

bb220:                                            ; preds = %bb219, %bb218, %bb217, %bb216, %bb215, %bb214, %bb210
  %i221 = phi i64 [ 127, %bb214 ], [ 1, %bb210 ], [ 3, %bb215 ], [ 7, %bb216 ], [ 15, %bb217 ], [ 31, %bb218 ], [ 63, %bb219 ]
  %i222 = shl i64 %i221, %i212
  %i223 = add i64 %i222, %i213
  br label %bb224

bb224:                                            ; preds = %bb275, %bb220, %bb210
  %i225 = phi i64 [ 0, %bb275 ], [ %i211, %bb210 ], [ %i223, %bb220 ]
  %i226 = tail call i32 @llvm.experimental.get.vector.length.i32(i32 %i128, i32 4, i1 true)
  %i227 = tail call <vscale x 4 x i32> @llvm.stepvector.nxv4i32()
  %i228 = sub <vscale x 4 x i32> shufflevector (<vscale x 4 x i32> insertelement (<vscale x 4 x i32> poison, i32 63, i64 0), <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer), %i227
  br label %bb229

bb229:                                            ; preds = %bb229, %bb224
  %i230 = phi i32 [ 0, %bb224 ], [ %i239, %bb229 ]
  %i231 = phi <vscale x 4 x i32> [ %i228, %bb224 ], [ %i243, %bb229 ]
  %i232 = phi <vscale x 4 x i64> [ zeroinitializer, %bb224 ], [ %i238, %bb229 ]
  %i233 = sub i32 %i128, %i230
  %i234 = tail call i32 @llvm.experimental.get.vector.length.i32(i32 %i233, i32 4, i1 true)
  %i235 = tail call <vscale x 4 x i64> @llvm.vp.zext.nxv4i64.nxv4i32(<vscale x 4 x i32> %i231, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %i234)
  %i236 = tail call <vscale x 4 x i64> @llvm.vp.shl.nxv4i64(<vscale x 4 x i64> shufflevector (<vscale x 4 x i64> insertelement (<vscale x 4 x i64> poison, i64 1, i64 0), <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer), <vscale x 4 x i64> %i235, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %i234)
  %i237 = tail call <vscale x 4 x i64> @llvm.vp.add.nxv4i64(<vscale x 4 x i64> %i236, <vscale x 4 x i64> %i232, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %i234)
  %i238 = tail call <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), <vscale x 4 x i64> %i237, <vscale x 4 x i64> %i232, i32 %i234)
  %i239 = add i32 %i234, %i230
  %i240 = sub i32 0, %i234
  %i241 = insertelement <vscale x 4 x i32> poison, i32 %i240, i64 0
  %i242 = shufflevector <vscale x 4 x i32> %i241, <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
  %i243 = tail call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %i231, <vscale x 4 x i32> %i242, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %i234)
  %i244 = icmp eq i32 %i239, %i128
  br i1 %i244, label %bb245, label %bb229, !llvm.loop !44

bb245:                                            ; preds = %bb229
  %i246 = tail call i64 @llvm.vp.reduce.add.nxv4i64(i64 0, <vscale x 4 x i64> %i238, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %i226)
  %i247 = and i64 %i225, %i206
  %i248 = and i64 %i246, %i206
  %i249 = lshr i64 %i248, 1
  %i250 = or i64 %i249, %i247
  %i251 = sext i32 %i204 to i64
  %i252 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i94, i64 %i251, i32 1
  store i64 %i250, ptr %i252, align 8, !tbaa !20, !noalias !30
  %i253 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i117, i64 %i203
  %i254 = load float, ptr %i253, align 8, !noalias !30
  %i255 = getelementptr inbounds nuw { float, float }, ptr %i253, i64 0, i32 1
  %i256 = load float, ptr %i255, align 4, !noalias !30
  %i257 = fmul fast float %i254, %i122
  %i258 = fmul fast float %i256, %i122
  %i259 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i94, i64 %i251
  %i260 = getelementptr inbounds nuw { float, float }, ptr %i259, i64 0, i32 1
  store float %i257, ptr %i259, align 8, !noalias !30
  store float %i258, ptr %i260, align 4, !noalias !30
  %i261 = add nsw i32 %i204, 1
  br label %bb271

bb262:                                            ; preds = %bb276, %bb262
  %i263 = phi i64 [ %i268, %bb262 ], [ 0, %bb276 ]
  %i264 = phi i64 [ %i267, %bb262 ], [ 0, %bb276 ]
  %i265 = phi i64 [ %i269, %bb262 ], [ 0, %bb276 ]
  %i266 = shl i64 255, %i263
  %i267 = add i64 %i266, %i264
  %i268 = add nuw nsw i64 %i263, 8
  %i269 = add i64 %i265, 8
  %i270 = icmp eq i64 %i269, %i133
  br i1 %i270, label %bb210, label %bb262, !llvm.loop !39

bb271:                                            ; preds = %bb245, %bb202
  %i272 = phi i32 [ %i261, %bb245 ], [ %i204, %bb202 ]
  %i273 = add nuw nsw i64 %i203, 1
  %i274 = icmp eq i64 %i273, %i123
  br i1 %i274, label %bb323, label %bb202, !llvm.loop !43

bb275:                                            ; preds = %bb202
  br i1 %i118, label %bb276, label %bb224

bb276:                                            ; preds = %bb275
  br i1 %i132, label %bb210, label %bb262

bb277:                                            ; preds = %bb294, %bb124
  %i278 = phi i64 [ %i296, %bb294 ], [ 0, %bb124 ]
  %i279 = phi i32 [ %i295, %bb294 ], [ 0, %bb124 ]
  %i280 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i117, i64 %i278, i32 1
  %i281 = load i64, ptr %i280, align 8, !tbaa !20, !noalias !30
  %i282 = and i64 %i281, %i54
  %i283 = icmp ne i64 %i282, 0
  %i284 = xor i1 %i51, %i283
  br i1 %i284, label %bb294, label %bb285

bb285:                                            ; preds = %bb285, %bb277
  %i286 = phi i64 [ %i291, %bb285 ], [ 0, %bb277 ]
  %i287 = phi i64 [ %i290, %bb285 ], [ 0, %bb277 ]
  %i288 = phi i64 [ %i292, %bb285 ], [ 0, %bb277 ]
  %i289 = shl i64 255, %i286
  %i290 = add i64 %i289, %i287
  %i291 = add nuw nsw i64 %i286, 8
  %i292 = add nuw nsw i64 %i288, 8
  %i293 = icmp eq i64 %i292, %i126
  br i1 %i293, label %bb298, label %bb285, !llvm.loop !39

bb294:                                            ; preds = %bb309, %bb277
  %i295 = phi i32 [ %i322, %bb309 ], [ %i279, %bb277 ]
  %i296 = add nuw nsw i64 %i278, 1
  %i297 = icmp eq i64 %i296, %i123
  br i1 %i297, label %bb323, label %bb277, !llvm.loop !43

bb298:                                            ; preds = %bb285
  switch i64 %i125, label %bb173 [
  i64 0, label %bb309
  i64 1, label %bb305
  i64 2, label %bb300
  i64 3, label %bb301
  i64 4, label %bb302
  i64 5, label %bb303
  i64 6, label %bb304
  i64 7, label %bb299
  ]

bb299:                                            ; preds = %bb298
  br label %bb305

bb300:                                            ; preds = %bb298
  br label %bb305

bb301:                                            ; preds = %bb298
  br label %bb305

bb302:                                            ; preds = %bb298
  br label %bb305

bb303:                                            ; preds = %bb298
  br label %bb305

bb304:                                            ; preds = %bb298
  br label %bb305

bb305:                                            ; preds = %bb304, %bb303, %bb302, %bb301, %bb300, %bb299, %bb298
  %i306 = phi i64 [ 127, %bb299 ], [ 1, %bb298 ], [ 3, %bb300 ], [ 7, %bb301 ], [ 15, %bb302 ], [ 31, %bb303 ], [ 63, %bb304 ]
  %i307 = shl i64 %i306, %i291
  %i308 = add i64 %i307, %i290
  br label %bb309

bb309:                                            ; preds = %bb305, %bb298
  %i310 = phi i64 [ %i290, %bb298 ], [ %i308, %bb305 ]
  %i311 = and i64 %i310, %i281
  %i312 = sext i32 %i279 to i64
  %i313 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i94, i64 %i312, i32 1
  store i64 %i311, ptr %i313, align 8, !tbaa !20, !noalias !30
  %i314 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i117, i64 %i278
  %i315 = load float, ptr %i314, align 8, !noalias !30
  %i316 = getelementptr inbounds nuw { float, float }, ptr %i314, i64 0, i32 1
  %i317 = load float, ptr %i316, align 4, !noalias !30
  %i318 = fmul fast float %i315, %i122
  %i319 = fmul fast float %i317, %i122
  %i320 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i94, i64 %i312
  %i321 = getelementptr inbounds nuw { float, float }, ptr %i320, i64 0, i32 1
  store float %i318, ptr %i320, align 8, !noalias !30
  store float %i319, ptr %i321, align 4, !noalias !30
  %i322 = add nsw i32 %i279, 1
  br label %bb294

bb323:                                            ; preds = %bb294, %bb271, %bb165, %bb106
  call void @llvm.lifetime.end.p0(i64 32, ptr nonnull %i2) #14
  %i324 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 3
  %i325 = load ptr, ptr %i324, align 8, !tbaa !19
  tail call void @free(ptr noundef %i325) #14
  %i326 = getelementptr inbounds nuw %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 1
  %i327 = load i32, ptr %i326, align 4, !tbaa !11
  %i328 = sub nsw i32 0, %i327
  %i329 = sext i32 %i328 to i64
  %i330 = shl nsw i64 %i329, 4
  %i331 = load i64, ptr @quantum_memman.mem, align 8, !tbaa !35
  %i332 = add nsw i64 %i330, %i331
  store i64 %i332, ptr @quantum_memman.mem, align 8, !tbaa !35
  %i333 = load i64, ptr @quantum_memman.max, align 8, !tbaa !35
  %i334 = icmp sgt i64 %i332, %i333
  br i1 %i334, label %bb335, label %bb336

bb335:                                            ; preds = %bb323
  store i64 %i332, ptr @quantum_memman.max, align 8, !tbaa !35
  br label %bb336

bb336:                                            ; preds = %bb335, %bb323
  store ptr null, ptr %i324, align 8, !tbaa !19
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) %arg1, ptr noundef nonnull align 8 dereferenceable(32) %i, i64 32, i1 false), !tbaa !26, !tbaa.struct !27
  br label %bb337

bb337:                                            ; preds = %bb336, %bb
  %i338 = phi i32 [ %i52, %bb336 ], [ 0, %bb ]
  call void @llvm.lifetime.end.p0(i64 32, ptr nonnull %i)
  ret i32 %i338
}

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.experimental.get.vector.length.i32(i32, i32 immarg, i1 immarg)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i32> @llvm.stepvector.nxv4i32()

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i64> @llvm.vp.zext.nxv4i64.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i1>, i32)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1>, <vscale x 4 x i64>, <vscale x 4 x i64>, i32)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare i64 @llvm.vp.reduce.add.nxv4i64(i64, <vscale x 4 x i64>, <vscale x 4 x i1>, i32)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)
declare void @llvm.experimental.noalias.scope.decl(metadata)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

!11 = !{!12, !15, i64 4, i64 4}
!12 = !{!13, i64 32, !"quantum_reg_struct", !15, i64 0, i64 4, !15, i64 4, i64 4, !15, i64 8, i64 4, !16, i64 16, i64 8, !18, i64 24, i64 8}
!13 = !{!14, i64 1, !"omnipotent char"}
!14 = !{!"Simple C/C++ TBAA"}
!15 = !{!13, i64 4, !"int"}
!16 = !{!17, i64 8, !"p1 struct quantum_reg_node_struct"}
!17 = !{!13, i64 8, !"any pointer"}
!18 = !{!17, i64 8, !"p1 int"}
!19 = !{!12, !16, i64 16, i64 8}
!20 = !{!21, !22, i64 8, i64 8}
!21 = !{!13, i64 16, !"quantum_reg_node_struct", !13, i64 0, i64 8, !22, i64 8, i64 8}
!22 = !{!13, i64 8, !"long long"}
!23 = distinct !{!23, !24}
!24 = !{!"llvm.loop.mustprogress"}
!25 = !{!15, !15, i64 0, i64 4}
!26 = !{!12, !12, i64 0, i64 32}
!27 = !{i64 0, i64 4, !25, i64 4, i64 4, !25, i64 8, i64 4, !25, i64 16, i64 8, !28, i64 24, i64 8, !29}
!28 = !{!16, !16, i64 0, i64 8}
!29 = !{!18, !18, i64 0, i64 8}
!30 = !{!31}
!31 = distinct !{!31, !32, !"quantum_state_collapse: argument 0"}
!32 = distinct !{!32, !"quantum_state_collapse"}
!33 = distinct !{!33, !24}
!34 = !{!12, !15, i64 0, i64 4}
!35 = !{!36, !36, i64 0, i64 8}
!36 = !{!13, i64 8, !"long"}
!37 = !{!12, !15, i64 8, i64 4}
!38 = !{!12, !18, i64 24, i64 8}
!39 = distinct !{!39, !24}
!40 = distinct !{!40, !24, !41, !42}
!41 = !{!"llvm.loop.unroll.runtime.disable"}
!42 = !{!"llvm.loop.isvectorized", i32 1}
!43 = distinct !{!43, !24}
!44 = distinct !{!44, !24, !42, !41}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META4:![0-9]+]], i64 4, i64 4}
; CHECK: [[META1]] = !{[[META2:![0-9]+]], i64 32, !"quantum_reg_struct", [[META4]], i64 0, i64 4, [[META4]], i64 4, i64 4, [[META4]], i64 8, i64 4, [[META5:![0-9]+]], i64 16, i64 8, [[META7:![0-9]+]], i64 24, i64 8}
; CHECK: [[META2]] = !{[[META3:![0-9]+]], i64 1, !"omnipotent char"}
; CHECK: [[META3]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[META4]] = !{[[META2]], i64 4, !"int"}
; CHECK: [[META5]] = !{[[META6:![0-9]+]], i64 8, !"p1 struct quantum_reg_node_struct"}
; CHECK: [[META6]] = !{[[META2]], i64 8, !"any pointer"}
; CHECK: [[META7]] = !{[[META6]], i64 8, !"p1 int"}
; CHECK: [[TBAA8]] = !{[[META1]], [[META5]], i64 16, i64 8}
; CHECK: [[TBAA9]] = !{[[META10:![0-9]+]], [[META11:![0-9]+]], i64 8, i64 8}
; CHECK: [[META10]] = !{[[META2]], i64 16, !"quantum_reg_node_struct", [[META2]], i64 0, i64 8, [[META11]], i64 8, i64 8}
; CHECK: [[META11]] = !{[[META2]], i64 8, !"long long"}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META13:![0-9]+]]}
; CHECK: [[META13]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[TBAA14]] = !{[[META4]], [[META4]], i64 0, i64 4}
; CHECK: [[TBAA15]] = !{[[META1]], [[META1]], i64 0, i64 32}
; CHECK: [[TBAA_STRUCT16]] = !{i64 0, i64 4, [[TBAA14]], i64 4, i64 4, [[TBAA14]], i64 8, i64 4, [[TBAA14]], i64 16, i64 8, [[META17:![0-9]+]], i64 24, i64 8, [[META18:![0-9]+]]}
; CHECK: [[META17]] = !{[[META5]], [[META5]], i64 0, i64 8}
; CHECK: [[META18]] = !{[[META7]], [[META7]], i64 0, i64 8}
; CHECK: [[META19]] = !{[[META20:![0-9]+]]}
; CHECK: [[META20]] = distinct !{[[META20]], [[META21:![0-9]+]], !"quantum_state_collapse: argument 0"}
; CHECK: [[META21]] = distinct !{[[META21]], !"quantum_state_collapse"}
; CHECK: [[LOOP22]] = distinct !{[[LOOP22]], [[META13]]}
; CHECK: [[TBAA23]] = !{[[META1]], [[META4]], i64 0, i64 4}
; CHECK: [[TBAA24]] = !{[[META25:![0-9]+]], [[META25]], i64 0, i64 8}
; CHECK: [[META25]] = !{[[META2]], i64 8, !"long"}
; CHECK: [[TBAA26]] = !{[[META1]], [[META4]], i64 8, i64 4}
; CHECK: [[TBAA27]] = !{[[META1]], [[META7]], i64 24, i64 8}
; CHECK: [[LOOP28]] = distinct !{[[LOOP28]], [[META13]]}
; CHECK: [[LOOP29]] = distinct !{[[LOOP29]], [[META13]], [[META30:![0-9]+]], [[META31:![0-9]+]]}
; CHECK: [[META30]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[META31]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[LOOP32]] = distinct !{[[LOOP32]], [[META13]]}
; CHECK: [[LOOP33]] = distinct !{[[LOOP33]], [[META13]], [[META31]], [[META30]]}
;.
