; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -passes=loop-data-layout -loop-data-layout-enable -mtriple=riscv64-unknown-linux-gnu | FileCheck %s
; Case fails with illegal transformation, leaving the input code as output

%struct.qtm_stream = type { i32, [42 x i32], [65 x %struct.qtm_modelsym] }
%struct.qtm_modelsym = type { i16, i16 }

define internal fastcc i32 @qtm_decompress(ptr %qtm) {
; CHECK-LABEL: @qtm_decompress(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SYMS:%.*]] = getelementptr inbounds [[STRUCT_QTM_STREAM:%.*]], ptr [[QTM:%.*]], i64 0, i32 2, i32 2
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[SYMS]], align 8
; CHECK-NEXT:    br label [[FOR_BODY146:%.*]]
; CHECK:       for.body146:
; CHECK-NEXT:    [[CUMFREQ150:%.*]] = getelementptr inbounds [[STRUCT_QTM_MODELSYM:%.*]], ptr [[TMP0]], i64 0, i32 1
; CHECK-NEXT:    br label [[FOR_BODY146]]
; CHECK:       do.body699:
; CHECK-NEXT:    [[ARRAYIDX1565:%.*]] = getelementptr [[STRUCT_QTM_STREAM]], ptr [[QTM]], i64 0, i32 1, i64 poison
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX1565]], align 4
; CHECK-NEXT:    ret i32 0
;
entry:
  %syms = getelementptr inbounds %struct.qtm_stream, ptr %qtm, i64 0, i32 2, i32 2
  %0 = load ptr, ptr %syms, align 8
  br label %for.body146

for.body146:
  %cumfreq150 = getelementptr inbounds %struct.qtm_modelsym, ptr %0, i64 0, i32 1
  br label %for.body146

do.body699:
  %arrayidx1565 = getelementptr %struct.qtm_stream, ptr %qtm, i64 0, i32 1, i64 poison
  %1 = load i32, ptr %arrayidx1565, align 4
  ret i32 0
}
