; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -S -passes=loop-data-layout -loop-data-layout-enable -mtriple=riscv64-unknown-linux-gnu | FileCheck %s
; RUN: opt < %s -S -passes=loop-data-layout -loop-data-layout-enable -mtriple=riscv64-unknown-linux-gnu | FileCheck %s
; This test verifies that we have deterministic output, run the same input twice
; and expect no divergence in output.

%struct.quantum_matrix_struct = type { i32, i32, ptr }
%struct.quantum_reg_struct = type { i32, i32, i32, ptr, ptr }
%struct.quantum_reg_node_struct = type { { float, float }, i64 }

@str = private unnamed_addr constant [28 x i8] c"Matrix is not a 2x2 matrix!\00", align 1
@.str.3 = private unnamed_addr constant [39 x i8] c"Not enough memory for %i bytes array!\0A\00", align 1
@quantum_gate_counter.counter = internal unnamed_addr global i32 0, align 4
@quantum_memman.mem = internal unnamed_addr global i64 0, align 8
@quantum_memman.max = internal unnamed_addr global i64 0, align 8
@.str = private unnamed_addr constant [35 x i8] c"Not enogh memory for %ix%i-Matrix!\00", align 1
@.str.1.23 = private unnamed_addr constant [39 x i8] c"Not enough memory for %i-sized qubit!\0A\00", align 1

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
declare dso_local noundef i32 @puts(ptr nocapture noundef readonly)
declare dso_local void @exit(i32 noundef signext)
declare dso_local noalias noundef ptr @realloc(ptr allocptr nocapture noundef, i64 noundef)
declare dso_local noundef signext i32 @printf(ptr nocapture noundef readonly, ...)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)
declare dso_local noalias noundef ptr @calloc(i64 noundef, i64 noundef)
declare dso_local void @free(ptr allocptr nocapture noundef)

; Function Attrs: nounwind uwtable vscale_range(8,1024)
define internal fastcc void @quantum_hadamard(i32 noundef signext %arg, ptr nocapture noundef %arg1, i32 %arg2) align 8 {
; CHECK-LABEL: define internal fastcc void @quantum_hadamard
; CHECK-SAME: (i32 noundef signext [[ARG:%.*]], ptr noundef captures(none) [[ARG1:%.*]], i32 [[ARG2:%.*]]) align 8 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[I:%.*]] = alloca [[STRUCT_QUANTUM_MATRIX_STRUCT:%.*]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr nonnull [[I]])
; CHECK-NEXT:    [[I3:%.*]] = add nsw i32 [[ARG2]], 1
; CHECK-NEXT:    [[I4:%.*]] = icmp eq i32 [[I3]], 0
; CHECK-NEXT:    br i1 [[I4]], label [[BB:%.*]], label [[BB744:%.*]]
; CHECK:       bb:
; CHECK-NEXT:    [[I5:%.*]] = tail call noalias dereferenceable_or_null(32) ptr @calloc(i64 noundef 4, i64 noundef 8)
; CHECK-NEXT:    [[I6:%.*]] = icmp eq ptr [[I5]], null
; CHECK-NEXT:    br i1 [[I6]], label [[BB7:%.*]], label [[BB9:%.*]]
; CHECK:       bb7:
; CHECK-NEXT:    [[I8:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str, i32 noundef signext 2, i32 noundef signext 2)
; CHECK-NEXT:    tail call void @exit(i32 noundef signext 1)
; CHECK-NEXT:    unreachable
; CHECK:       bb9:
; CHECK-NEXT:    [[I10:%.*]] = load i64, ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I11:%.*]] = add nsw i64 [[I10]], 32
; CHECK-NEXT:    store i64 [[I11]], ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I12:%.*]] = load i64, ptr @quantum_memman.max, align 8
; CHECK-NEXT:    [[I13:%.*]] = icmp sgt i64 [[I11]], [[I12]]
; CHECK-NEXT:    br i1 [[I13]], label [[BB14:%.*]], label [[BB15:%.*]]
; CHECK:       bb14:
; CHECK-NEXT:    store i64 [[I11]], ptr @quantum_memman.max, align 8
; CHECK-NEXT:    br label [[BB15]]
; CHECK:       bb15:
; CHECK-NEXT:    [[I16:%.*]] = ptrtoint ptr [[I5]] to i64
; CHECK-NEXT:    store i64 8589934594, ptr [[I]], align 8
; CHECK-NEXT:    [[I17:%.*]] = getelementptr inbounds i8, ptr [[I]], i64 8
; CHECK-NEXT:    store i64 [[I16]], ptr [[I17]], align 8
; CHECK-NEXT:    [[I18:%.*]] = getelementptr inbounds { float, float }, ptr [[I5]], i64 0, i32 1
; CHECK-NEXT:    store float 0x3FE6A09E60000000, ptr [[I5]], align 4
; CHECK-NEXT:    store float 0.000000e+00, ptr [[I18]], align 4
; CHECK-NEXT:    [[I19:%.*]] = getelementptr inbounds { float, float }, ptr [[I5]], i64 1
; CHECK-NEXT:    [[I20:%.*]] = getelementptr inbounds { float, float }, ptr [[I5]], i64 1, i32 1
; CHECK-NEXT:    store float 0x3FE6A09E60000000, ptr [[I19]], align 4
; CHECK-NEXT:    store float 0.000000e+00, ptr [[I20]], align 4
; CHECK-NEXT:    [[I21:%.*]] = load ptr, ptr [[I17]], align 8
; CHECK-NEXT:    [[I22:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 2
; CHECK-NEXT:    [[I23:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 2, i32 1
; CHECK-NEXT:    store float 0x3FE6A09E60000000, ptr [[I22]], align 4
; CHECK-NEXT:    store float 0.000000e+00, ptr [[I23]], align 4
; CHECK-NEXT:    [[I24:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 3
; CHECK-NEXT:    [[I25:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 3, i32 1
; CHECK-NEXT:    store float 0xBFE6A09E60000000, ptr [[I24]], align 4
; CHECK-NEXT:    store float 0.000000e+00, ptr [[I25]], align 4
; CHECK-NEXT:    [[I26:%.*]] = load i64, ptr [[I]], align 8
; CHECK-NEXT:    [[I27:%.*]] = icmp eq i64 [[I26]], 8589934594
; CHECK-NEXT:    br i1 [[I27]], label [[BB28:%.*]], label [[BB35:%.*]]
; CHECK:       bb28:
; CHECK-NEXT:    [[I29:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA:%.*]], ptr [[ARG1]], i64 0, i32 2
; CHECK-NEXT:    [[I30:%.*]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I31:%.*]] = icmp eq i32 [[I30]], 31
; CHECK-NEXT:    br i1 [[I31]], label [[BB37:%.*]], label [[BB32:%.*]]
; CHECK:       bb32:
; CHECK-NEXT:    [[I33:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 4
; CHECK-NEXT:    [[I34:%.*]] = load ptr, ptr [[I33]], align 8
; CHECK-NEXT:    br label [[BB47:%.*]]
; CHECK:       bb35:
; CHECK-NEXT:    [[I36:%.*]] = tail call i32 @puts(ptr nonnull dereferenceable(1) @str)
; CHECK-NEXT:    tail call void @exit(i32 noundef signext 1)
; CHECK-NEXT:    unreachable
; CHECK:       bb37:
; CHECK-NEXT:    [[I38:%.*]] = phi i32 [ 31, [[BB28]] ], [ [[I51:%.*]], [[BB47]] ], [ [[I58:%.*]], [[BB55:%.*]] ], [ [[I65:%.*]], [[BB62:%.*]] ], [ [[I72:%.*]], [[BB69:%.*]] ], [ [[I79:%.*]], [[BB76:%.*]] ], [ [[I86:%.*]], [[BB83:%.*]] ], [ [[I93:%.*]], [[BB90:%.*]] ], [ [[I100:%.*]], [[BB97:%.*]] ]
; CHECK-NEXT:    [[I39:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 1
; CHECK-NEXT:    [[I40:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I41:%.*]] = icmp sgt i32 [[I40]], 0
; CHECK-NEXT:    br i1 [[I41]], label [[BB42:%.*]], label [[BB106:%.*]]
; CHECK:       bb42:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 6
; CHECK-NEXT:    [[I43:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 5
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[I44:%.*]] = load ptr, ptr [[I43]], align 8
; CHECK-NEXT:    [[I45:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 4
; CHECK-NEXT:    [[I46:%.*]] = load ptr, ptr [[I45]], align 8
; CHECK-NEXT:    br label [[BB125:%.*]]
; CHECK:       bb47:
; CHECK-NEXT:    [[I48:%.*]] = phi i64 [ 0, [[BB32]] ], [ [[I99:%.*]], [[BB97]] ]
; CHECK-NEXT:    [[I49:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I48]]
; CHECK-NEXT:    store i32 0, ptr [[I49]], align 4
; CHECK-NEXT:    [[I50:%.*]] = or i64 [[I48]], 1
; CHECK-NEXT:    [[I51]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I52:%.*]] = shl nuw i32 1, [[I51]]
; CHECK-NEXT:    [[I53:%.*]] = sext i32 [[I52]] to i64
; CHECK-NEXT:    [[I54:%.*]] = icmp slt i64 [[I50]], [[I53]]
; CHECK-NEXT:    br i1 [[I54]], label [[BB55]], label [[BB37]]
; CHECK:       bb55:
; CHECK-NEXT:    [[I56:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I50]]
; CHECK-NEXT:    store i32 0, ptr [[I56]], align 4
; CHECK-NEXT:    [[I57:%.*]] = or i64 [[I48]], 2
; CHECK-NEXT:    [[I58]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I59:%.*]] = shl nuw i32 1, [[I58]]
; CHECK-NEXT:    [[I60:%.*]] = sext i32 [[I59]] to i64
; CHECK-NEXT:    [[I61:%.*]] = icmp slt i64 [[I57]], [[I60]]
; CHECK-NEXT:    br i1 [[I61]], label [[BB62]], label [[BB37]]
; CHECK:       bb62:
; CHECK-NEXT:    [[I63:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I57]]
; CHECK-NEXT:    store i32 0, ptr [[I63]], align 4
; CHECK-NEXT:    [[I64:%.*]] = or i64 [[I48]], 3
; CHECK-NEXT:    [[I65]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I66:%.*]] = shl nuw i32 1, [[I65]]
; CHECK-NEXT:    [[I67:%.*]] = sext i32 [[I66]] to i64
; CHECK-NEXT:    [[I68:%.*]] = icmp slt i64 [[I64]], [[I67]]
; CHECK-NEXT:    br i1 [[I68]], label [[BB69]], label [[BB37]]
; CHECK:       bb69:
; CHECK-NEXT:    [[I70:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I64]]
; CHECK-NEXT:    store i32 0, ptr [[I70]], align 4
; CHECK-NEXT:    [[I71:%.*]] = or i64 [[I48]], 4
; CHECK-NEXT:    [[I72]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I73:%.*]] = shl nuw i32 1, [[I72]]
; CHECK-NEXT:    [[I74:%.*]] = sext i32 [[I73]] to i64
; CHECK-NEXT:    [[I75:%.*]] = icmp slt i64 [[I71]], [[I74]]
; CHECK-NEXT:    br i1 [[I75]], label [[BB76]], label [[BB37]]
; CHECK:       bb76:
; CHECK-NEXT:    [[I77:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I71]]
; CHECK-NEXT:    store i32 0, ptr [[I77]], align 4
; CHECK-NEXT:    [[I78:%.*]] = or i64 [[I48]], 5
; CHECK-NEXT:    [[I79]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I80:%.*]] = shl nuw i32 1, [[I79]]
; CHECK-NEXT:    [[I81:%.*]] = sext i32 [[I80]] to i64
; CHECK-NEXT:    [[I82:%.*]] = icmp slt i64 [[I78]], [[I81]]
; CHECK-NEXT:    br i1 [[I82]], label [[BB83]], label [[BB37]]
; CHECK:       bb83:
; CHECK-NEXT:    [[I84:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I78]]
; CHECK-NEXT:    store i32 0, ptr [[I84]], align 4
; CHECK-NEXT:    [[I85:%.*]] = or i64 [[I48]], 6
; CHECK-NEXT:    [[I86]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I87:%.*]] = shl nuw i32 1, [[I86]]
; CHECK-NEXT:    [[I88:%.*]] = sext i32 [[I87]] to i64
; CHECK-NEXT:    [[I89:%.*]] = icmp slt i64 [[I85]], [[I88]]
; CHECK-NEXT:    br i1 [[I89]], label [[BB90]], label [[BB37]]
; CHECK:       bb90:
; CHECK-NEXT:    [[I91:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I85]]
; CHECK-NEXT:    store i32 0, ptr [[I91]], align 4
; CHECK-NEXT:    [[I92:%.*]] = or i64 [[I48]], 7
; CHECK-NEXT:    [[I93]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I94:%.*]] = shl nuw i32 1, [[I93]]
; CHECK-NEXT:    [[I95:%.*]] = sext i32 [[I94]] to i64
; CHECK-NEXT:    [[I96:%.*]] = icmp slt i64 [[I92]], [[I95]]
; CHECK-NEXT:    br i1 [[I96]], label [[BB97]], label [[BB37]]
; CHECK:       bb97:
; CHECK-NEXT:    [[I98:%.*]] = getelementptr inbounds i32, ptr [[I34]], i64 [[I92]]
; CHECK-NEXT:    store i32 0, ptr [[I98]], align 4
; CHECK-NEXT:    [[I99]] = add nuw nsw i64 [[I48]], 8
; CHECK-NEXT:    [[I100]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I101:%.*]] = shl nuw i32 1, [[I100]]
; CHECK-NEXT:    [[I102:%.*]] = sext i32 [[I101]] to i64
; CHECK-NEXT:    [[I103:%.*]] = icmp slt i64 [[I99]], [[I102]]
; CHECK-NEXT:    br i1 [[I103]], label [[BB47]], label [[BB37]]
; CHECK:       bb104:
; CHECK-NEXT:    [[I105:%.*]] = icmp sgt i32 [[I211:%.*]], 0
; CHECK-NEXT:    br i1 [[I105]], label [[BB110:%.*]], label [[BB106]]
; CHECK:       bb106:
; CHECK-NEXT:    [[I107:%.*]] = phi i32 [ [[I211]], [[BB104:%.*]] ], [ [[I40]], [[BB37]] ]
; CHECK-NEXT:    [[I108:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 5
; CHECK-NEXT:    [[I109:%.*]] = load ptr, ptr [[I108]], align 8
; CHECK-NEXT:    br label [[BB275:%.*]]
; CHECK:       bb110:
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 6
; CHECK-NEXT:    [[I111:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 5
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-NEXT:    [[I112:%.*]] = load ptr, ptr [[I111]], align 8
; CHECK-NEXT:    [[I113:%.*]] = zext i32 [[ARG]] to i64
; CHECK-NEXT:    [[I114:%.*]] = shl nuw i64 1, [[I113]]
; CHECK-NEXT:    [[I115:%.*]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I116:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 24
; CHECK-NEXT:    [[I117:%.*]] = load ptr, ptr [[I116]], align 8
; CHECK-NEXT:    [[I118:%.*]] = sub nsw i32 32, [[I115]]
; CHECK-NEXT:    [[I119:%.*]] = shl nuw i32 1, [[I115]]
; CHECK-NEXT:    [[I120:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 1
; CHECK-NEXT:    [[I121:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 1, i32 1
; CHECK-NEXT:    [[I122:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 2
; CHECK-NEXT:    [[I123:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 2, i32 1
; CHECK-NEXT:    [[I124:%.*]] = zext i32 [[I211]] to i64
; CHECK-NEXT:    br label [[BB216:%.*]]
; CHECK:       bb125:
; CHECK-NEXT:    [[I126:%.*]] = phi i32 [ [[I38]], [[BB42]] ], [ [[I215:%.*]], [[BB214:%.*]] ]
; CHECK-NEXT:    [[I127:%.*]] = phi i64 [ 0, [[BB42]] ], [ [[I209:%.*]], [[BB214]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[TMP1]], i64 [[I127]]
; CHECK-NEXT:    [[I129:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    [[I130:%.*]] = lshr i64 [[I129]], 32
; CHECK-NEXT:    [[I131:%.*]] = xor i64 [[I130]], [[I129]]
; CHECK-NEXT:    [[I132:%.*]] = trunc i64 [[I131]] to i32
; CHECK-NEXT:    [[I133:%.*]] = mul i32 [[I132]], -1640562687
; CHECK-NEXT:    [[I134:%.*]] = sub nsw i32 32, [[I126]]
; CHECK-NEXT:    [[I135:%.*]] = lshr i32 [[I133]], [[I134]]
; CHECK-NEXT:    [[I136:%.*]] = sext i32 [[I135]] to i64
; CHECK-NEXT:    [[I137:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I136]]
; CHECK-NEXT:    [[I138:%.*]] = load i32, ptr [[I137]], align 4
; CHECK-NEXT:    [[I139:%.*]] = icmp eq i32 [[I138]], 0
; CHECK-NEXT:    br i1 [[I139]], label [[BB207:%.*]], label [[BB140:%.*]]
; CHECK:       bb140:
; CHECK-NEXT:    [[I141:%.*]] = shl nuw i32 1, [[I126]]
; CHECK-NEXT:    br label [[BB142:%.*]]
; CHECK:       bb142:
; CHECK-NEXT:    [[I143:%.*]] = phi i32 [ [[I135]], [[BB140]] ], [ [[I202:%.*]], [[BB199:%.*]] ]
; CHECK-NEXT:    [[I144:%.*]] = add nsw i32 [[I143]], 1
; CHECK-NEXT:    [[I145:%.*]] = icmp eq i32 [[I144]], [[I141]]
; CHECK-NEXT:    [[I146:%.*]] = select i1 [[I145]], i32 0, i32 [[I144]]
; CHECK-NEXT:    [[I147:%.*]] = sext i32 [[I146]] to i64
; CHECK-NEXT:    [[I148:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I147]]
; CHECK-NEXT:    [[I149:%.*]] = load i32, ptr [[I148]], align 4
; CHECK-NEXT:    [[I150:%.*]] = icmp eq i32 [[I149]], 0
; CHECK-NEXT:    br i1 [[I150]], label [[BB207]], label [[BB151:%.*]]
; CHECK:       bb151:
; CHECK-NEXT:    [[I152:%.*]] = add nsw i32 [[I146]], 1
; CHECK-NEXT:    [[I153:%.*]] = icmp eq i32 [[I152]], [[I141]]
; CHECK-NEXT:    [[I154:%.*]] = select i1 [[I153]], i32 0, i32 [[I152]]
; CHECK-NEXT:    [[I155:%.*]] = sext i32 [[I154]] to i64
; CHECK-NEXT:    [[I156:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I155]]
; CHECK-NEXT:    [[I157:%.*]] = load i32, ptr [[I156]], align 4
; CHECK-NEXT:    [[I158:%.*]] = icmp eq i32 [[I157]], 0
; CHECK-NEXT:    br i1 [[I158]], label [[BB207]], label [[BB159:%.*]]
; CHECK:       bb159:
; CHECK-NEXT:    [[I160:%.*]] = add nsw i32 [[I154]], 1
; CHECK-NEXT:    [[I161:%.*]] = icmp eq i32 [[I160]], [[I141]]
; CHECK-NEXT:    [[I162:%.*]] = select i1 [[I161]], i32 0, i32 [[I160]]
; CHECK-NEXT:    [[I163:%.*]] = sext i32 [[I162]] to i64
; CHECK-NEXT:    [[I164:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I163]]
; CHECK-NEXT:    [[I165:%.*]] = load i32, ptr [[I164]], align 4
; CHECK-NEXT:    [[I166:%.*]] = icmp eq i32 [[I165]], 0
; CHECK-NEXT:    br i1 [[I166]], label [[BB207]], label [[BB167:%.*]]
; CHECK:       bb167:
; CHECK-NEXT:    [[I168:%.*]] = add nsw i32 [[I162]], 1
; CHECK-NEXT:    [[I169:%.*]] = icmp eq i32 [[I168]], [[I141]]
; CHECK-NEXT:    [[I170:%.*]] = select i1 [[I169]], i32 0, i32 [[I168]]
; CHECK-NEXT:    [[I171:%.*]] = sext i32 [[I170]] to i64
; CHECK-NEXT:    [[I172:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I171]]
; CHECK-NEXT:    [[I173:%.*]] = load i32, ptr [[I172]], align 4
; CHECK-NEXT:    [[I174:%.*]] = icmp eq i32 [[I173]], 0
; CHECK-NEXT:    br i1 [[I174]], label [[BB207]], label [[BB175:%.*]]
; CHECK:       bb175:
; CHECK-NEXT:    [[I176:%.*]] = add nsw i32 [[I170]], 1
; CHECK-NEXT:    [[I177:%.*]] = icmp eq i32 [[I176]], [[I141]]
; CHECK-NEXT:    [[I178:%.*]] = select i1 [[I177]], i32 0, i32 [[I176]]
; CHECK-NEXT:    [[I179:%.*]] = sext i32 [[I178]] to i64
; CHECK-NEXT:    [[I180:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I179]]
; CHECK-NEXT:    [[I181:%.*]] = load i32, ptr [[I180]], align 4
; CHECK-NEXT:    [[I182:%.*]] = icmp eq i32 [[I181]], 0
; CHECK-NEXT:    br i1 [[I182]], label [[BB207]], label [[BB183:%.*]]
; CHECK:       bb183:
; CHECK-NEXT:    [[I184:%.*]] = add nsw i32 [[I178]], 1
; CHECK-NEXT:    [[I185:%.*]] = icmp eq i32 [[I184]], [[I141]]
; CHECK-NEXT:    [[I186:%.*]] = select i1 [[I185]], i32 0, i32 [[I184]]
; CHECK-NEXT:    [[I187:%.*]] = sext i32 [[I186]] to i64
; CHECK-NEXT:    [[I188:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I187]]
; CHECK-NEXT:    [[I189:%.*]] = load i32, ptr [[I188]], align 4
; CHECK-NEXT:    [[I190:%.*]] = icmp eq i32 [[I189]], 0
; CHECK-NEXT:    br i1 [[I190]], label [[BB207]], label [[BB191:%.*]]
; CHECK:       bb191:
; CHECK-NEXT:    [[I192:%.*]] = add nsw i32 [[I186]], 1
; CHECK-NEXT:    [[I193:%.*]] = icmp eq i32 [[I192]], [[I141]]
; CHECK-NEXT:    [[I194:%.*]] = select i1 [[I193]], i32 0, i32 [[I192]]
; CHECK-NEXT:    [[I195:%.*]] = sext i32 [[I194]] to i64
; CHECK-NEXT:    [[I196:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I195]]
; CHECK-NEXT:    [[I197:%.*]] = load i32, ptr [[I196]], align 4
; CHECK-NEXT:    [[I198:%.*]] = icmp eq i32 [[I197]], 0
; CHECK-NEXT:    br i1 [[I198]], label [[BB207]], label [[BB199]]
; CHECK:       bb199:
; CHECK-NEXT:    [[I200:%.*]] = add nsw i32 [[I194]], 1
; CHECK-NEXT:    [[I201:%.*]] = icmp eq i32 [[I200]], [[I141]]
; CHECK-NEXT:    [[I202]] = select i1 [[I201]], i32 0, i32 [[I200]]
; CHECK-NEXT:    [[I203:%.*]] = sext i32 [[I202]] to i64
; CHECK-NEXT:    [[I204:%.*]] = getelementptr inbounds i32, ptr [[I46]], i64 [[I203]]
; CHECK-NEXT:    [[I205:%.*]] = load i32, ptr [[I204]], align 4
; CHECK-NEXT:    [[I206:%.*]] = icmp eq i32 [[I205]], 0
; CHECK-NEXT:    br i1 [[I206]], label [[BB207]], label [[BB142]]
; CHECK:       bb207:
; CHECK-NEXT:    [[I208:%.*]] = phi ptr [ [[I137]], [[BB125]] ], [ [[I148]], [[BB142]] ], [ [[I156]], [[BB151]] ], [ [[I164]], [[BB159]] ], [ [[I172]], [[BB167]] ], [ [[I180]], [[BB175]] ], [ [[I188]], [[BB183]] ], [ [[I196]], [[BB191]] ], [ [[I204]], [[BB199]] ]
; CHECK-NEXT:    [[I209]] = add nuw nsw i64 [[I127]], 1
; CHECK-NEXT:    [[I210:%.*]] = trunc i64 [[I209]] to i32
; CHECK-NEXT:    store i32 [[I210]], ptr [[I208]], align 4
; CHECK-NEXT:    [[I211]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I212:%.*]] = sext i32 [[I211]] to i64
; CHECK-NEXT:    [[I213:%.*]] = icmp slt i64 [[I209]], [[I212]]
; CHECK-NEXT:    br i1 [[I213]], label [[BB214]], label [[BB104]]
; CHECK:       bb214:
; CHECK-NEXT:    [[I215]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    br label [[BB125]]
; CHECK:       bb216:
; CHECK-NEXT:    [[I217:%.*]] = phi i64 [ 0, [[BB110]] ], [ [[I273:%.*]], [[BB271:%.*]] ]
; CHECK-NEXT:    [[I218:%.*]] = phi i32 [ 0, [[BB110]] ], [ [[I272:%.*]], [[BB271]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[TMP3]], i64 [[I217]]
; CHECK-NEXT:    [[I220:%.*]] = load i64, ptr [[TMP5]], align 8
; CHECK-NEXT:    [[I221:%.*]] = xor i64 [[I220]], [[I114]]
; CHECK-NEXT:    [[I222:%.*]] = lshr i64 [[I221]], 32
; CHECK-NEXT:    [[I223:%.*]] = xor i64 [[I222]], [[I221]]
; CHECK-NEXT:    [[I224:%.*]] = trunc i64 [[I223]] to i32
; CHECK-NEXT:    [[I225:%.*]] = mul i32 [[I224]], -1640562687
; CHECK-NEXT:    [[I226:%.*]] = lshr i32 [[I225]], [[I118]]
; CHECK-NEXT:    [[I227:%.*]] = sext i32 [[I226]] to i64
; CHECK-NEXT:    [[I228:%.*]] = getelementptr inbounds i32, ptr [[I117]], i64 [[I227]]
; CHECK-NEXT:    [[I229:%.*]] = load i32, ptr [[I228]], align 4
; CHECK-NEXT:    [[I230:%.*]] = icmp eq i32 [[I229]], 0
; CHECK-NEXT:    br i1 [[I230]], label [[BB247:%.*]], label [[BB231:%.*]]
; CHECK:       bb231:
; CHECK-NEXT:    [[I232:%.*]] = phi i32 [ [[I245:%.*]], [[BB239:%.*]] ], [ [[I229]], [[BB216]] ]
; CHECK-NEXT:    [[I233:%.*]] = phi i32 [ [[I242:%.*]], [[BB239]] ], [ [[I226]], [[BB216]] ]
; CHECK-NEXT:    [[I234:%.*]] = add nsw i32 [[I232]], -1
; CHECK-NEXT:    [[I235:%.*]] = sext i32 [[I234]] to i64
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP3]], i64 [[I235]]
; CHECK-NEXT:    [[I237:%.*]] = load i64, ptr [[TMP6]], align 8
; CHECK-NEXT:    [[I238:%.*]] = icmp eq i64 [[I237]], [[I221]]
; CHECK-NEXT:    br i1 [[I238]], label [[BB271]], label [[BB239]]
; CHECK:       bb239:
; CHECK-NEXT:    [[I240:%.*]] = add nsw i32 [[I233]], 1
; CHECK-NEXT:    [[I241:%.*]] = icmp eq i32 [[I240]], [[I119]]
; CHECK-NEXT:    [[I242]] = select i1 [[I241]], i32 0, i32 [[I240]]
; CHECK-NEXT:    [[I243:%.*]] = sext i32 [[I242]] to i64
; CHECK-NEXT:    [[I244:%.*]] = getelementptr inbounds i32, ptr [[I117]], i64 [[I243]]
; CHECK-NEXT:    [[I245]] = load i32, ptr [[I244]], align 4
; CHECK-NEXT:    [[I246:%.*]] = icmp eq i32 [[I245]], 0
; CHECK-NEXT:    br i1 [[I246]], label [[BB247]], label [[BB231]]
; CHECK:       bb247:
; CHECK-NEXT:    [[I248:%.*]] = load float, ptr [[I120]], align 4
; CHECK-NEXT:    [[I249:%.*]] = load float, ptr [[I121]], align 4
; CHECK-NEXT:    [[I250:%.*]] = fmul fast float [[I248]], [[I248]]
; CHECK-NEXT:    [[I251:%.*]] = fmul fast float [[I249]], [[I249]]
; CHECK-NEXT:    [[I252:%.*]] = fadd fast float [[I251]], [[I250]]
; CHECK-NEXT:    [[I253:%.*]] = fpext float [[I252]] to double
; CHECK-NEXT:    [[I254:%.*]] = fcmp fast ogt double [[I253]], 1.000000e-09
; CHECK-NEXT:    [[I255:%.*]] = and i64 [[I220]], [[I114]]
; CHECK-NEXT:    [[I256:%.*]] = icmp ne i64 [[I255]], 0
; CHECK-NEXT:    [[I257:%.*]] = select i1 [[I254]], i1 [[I256]], i1 false
; CHECK-NEXT:    [[I258:%.*]] = zext i1 [[I257]] to i32
; CHECK-NEXT:    [[I259:%.*]] = add nsw i32 [[I218]], [[I258]]
; CHECK-NEXT:    [[I260:%.*]] = load float, ptr [[I122]], align 4
; CHECK-NEXT:    [[I261:%.*]] = load float, ptr [[I123]], align 4
; CHECK-NEXT:    [[I262:%.*]] = fmul fast float [[I260]], [[I260]]
; CHECK-NEXT:    [[I263:%.*]] = fmul fast float [[I261]], [[I261]]
; CHECK-NEXT:    [[I264:%.*]] = fadd fast float [[I263]], [[I262]]
; CHECK-NEXT:    [[I265:%.*]] = fpext float [[I264]] to double
; CHECK-NEXT:    [[I266:%.*]] = fcmp fast ogt double [[I265]], 1.000000e-09
; CHECK-NEXT:    br i1 [[I266]], label [[BB267:%.*]], label [[BB271]]
; CHECK:       bb267:
; CHECK-NEXT:    [[I268:%.*]] = icmp eq i64 [[I255]], 0
; CHECK-NEXT:    [[I269:%.*]] = zext i1 [[I268]] to i32
; CHECK-NEXT:    [[I270:%.*]] = add nsw i32 [[I259]], [[I269]]
; CHECK-NEXT:    br label [[BB271]]
; CHECK:       bb271:
; CHECK-NEXT:    [[I272]] = phi i32 [ [[I259]], [[BB247]] ], [ [[I270]], [[BB267]] ], [ [[I218]], [[BB231]] ]
; CHECK-NEXT:    [[I273]] = add nuw nsw i64 [[I217]], 1
; CHECK-NEXT:    [[I274:%.*]] = icmp eq i64 [[I273]], [[I124]]
; CHECK-NEXT:    br i1 [[I274]], label [[BB275]], label [[BB216]]
; CHECK:       bb275:
; CHECK-NEXT:    [[I276:%.*]] = phi i32 [ [[I107]], [[BB106]] ], [ [[I211]], [[BB271]] ]
; CHECK-NEXT:    [[I277:%.*]] = phi ptr [ [[I109]], [[BB106]] ], [ [[I112]], [[BB271]] ]
; CHECK-NEXT:    [[I278:%.*]] = phi i32 [ 0, [[BB106]] ], [ [[I272]], [[BB271]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 6
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I279:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_REG_NODE_STRUCT_SOA]], ptr [[ARG1]], i64 0, i32 5
; CHECK-NEXT:    [[I280:%.*]] = add nsw i32 [[I278]], [[I276]]
; CHECK-NEXT:    [[I281:%.*]] = sext i32 [[I280]] to i64
; CHECK-NEXT:    [[I282:%.*]] = shl nsw i64 [[I281]], 4
; CHECK-NEXT:    [[TMP9:%.*]] = shl nsw i64 [[I281]], 3
; CHECK-NEXT:    [[TMP10:%.*]] = shl nsw i64 [[I281]], 3
; CHECK-NEXT:    [[I283:%.*]] = tail call ptr @realloc(ptr noundef [[I277]], i64 noundef [[TMP10]])
; CHECK-NEXT:    [[TMP11:%.*]] = tail call ptr @realloc(ptr noundef [[TMP8]], i64 noundef [[TMP9]])
; CHECK-NEXT:    store ptr [[TMP11]], ptr [[TMP7]], align 8
; CHECK-NEXT:    store ptr [[I283]], ptr [[I279]], align 8
; CHECK-NEXT:    [[I284:%.*]] = icmp eq ptr [[I283]], null
; CHECK-NEXT:    br i1 [[I284]], label [[BB285:%.*]], label [[BB289:%.*]]
; CHECK:       bb285:
; CHECK-NEXT:    [[I286:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I287:%.*]] = add nsw i32 [[I286]], [[I278]]
; CHECK-NEXT:    [[I288:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.1.23, i32 noundef signext [[I287]])
; CHECK-NEXT:    tail call void @exit(i32 noundef signext 1)
; CHECK-NEXT:    unreachable
; CHECK:       bb289:
; CHECK-NEXT:    [[I290:%.*]] = sext i32 [[I278]] to i64
; CHECK-NEXT:    [[I291:%.*]] = shl nsw i64 [[I290]], 4
; CHECK-NEXT:    [[I292:%.*]] = load i64, ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I293:%.*]] = add nsw i64 [[I292]], [[I291]]
; CHECK-NEXT:    store i64 [[I293]], ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I294:%.*]] = load i64, ptr @quantum_memman.max, align 8
; CHECK-NEXT:    [[I295:%.*]] = icmp sgt i64 [[I293]], [[I294]]
; CHECK-NEXT:    br i1 [[I295]], label [[BB296:%.*]], label [[BB297:%.*]]
; CHECK:       bb296:
; CHECK-NEXT:    store i64 [[I293]], ptr @quantum_memman.max, align 8
; CHECK-NEXT:    br label [[BB297]]
; CHECK:       bb297:
; CHECK-NEXT:    [[I298:%.*]] = icmp sgt i32 [[I278]], 0
; CHECK-NEXT:    br i1 [[I298]], label [[BB299:%.*]], label [[BB414:%.*]]
; CHECK:       bb299:
; CHECK-NEXT:    [[I300:%.*]] = and i32 [[I278]], 7
; CHECK-NEXT:    [[I301:%.*]] = icmp ult i32 [[I278]], 8
; CHECK-NEXT:    br i1 [[I301]], label [[BB357:%.*]], label [[BB302:%.*]]
; CHECK:       bb302:
; CHECK-NEXT:    [[I303:%.*]] = and i32 [[I278]], -8
; CHECK-NEXT:    br label [[BB304:%.*]]
; CHECK:       bb304:
; CHECK-NEXT:    [[I305:%.*]] = phi i32 [ 0, [[BB302]] ], [ [[I354:%.*]], [[BB304]] ]
; CHECK-NEXT:    [[I306:%.*]] = phi i32 [ 0, [[BB302]] ], [ [[I355:%.*]], [[BB304]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I307:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I308:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I309:%.*]] = add nsw i32 [[I308]], [[I305]]
; CHECK-NEXT:    [[I310:%.*]] = sext i32 [[I309]] to i64
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds { float, float }, ptr [[I307]], i64 [[I310]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I310]]
; CHECK-NEXT:    [[I312:%.*]] = or i32 [[I305]], 1
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP13]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP14]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I313:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I314:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I315:%.*]] = add nsw i32 [[I314]], [[I312]]
; CHECK-NEXT:    [[I316:%.*]] = sext i32 [[I315]] to i64
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds { float, float }, ptr [[I313]], i64 [[I316]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I316]]
; CHECK-NEXT:    [[I318:%.*]] = or i32 [[I305]], 2
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP15]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP16]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I319:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I320:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I321:%.*]] = add nsw i32 [[I320]], [[I318]]
; CHECK-NEXT:    [[I322:%.*]] = sext i32 [[I321]] to i64
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds { float, float }, ptr [[I319]], i64 [[I322]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I322]]
; CHECK-NEXT:    [[I324:%.*]] = or i32 [[I305]], 3
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP17]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP18]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I325:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I326:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I327:%.*]] = add nsw i32 [[I326]], [[I324]]
; CHECK-NEXT:    [[I328:%.*]] = sext i32 [[I327]] to i64
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds { float, float }, ptr [[I325]], i64 [[I328]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I328]]
; CHECK-NEXT:    [[I330:%.*]] = or i32 [[I305]], 4
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP19]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP20]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I331:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I332:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I333:%.*]] = add nsw i32 [[I332]], [[I330]]
; CHECK-NEXT:    [[I334:%.*]] = sext i32 [[I333]] to i64
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds { float, float }, ptr [[I331]], i64 [[I334]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I334]]
; CHECK-NEXT:    [[I336:%.*]] = or i32 [[I305]], 5
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP21]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP22]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I337:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I338:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I339:%.*]] = add nsw i32 [[I338]], [[I336]]
; CHECK-NEXT:    [[I340:%.*]] = sext i32 [[I339]] to i64
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds { float, float }, ptr [[I337]], i64 [[I340]]
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I340]]
; CHECK-NEXT:    [[I342:%.*]] = or i32 [[I305]], 6
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP23]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP24]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I343:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I344:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I345:%.*]] = add nsw i32 [[I344]], [[I342]]
; CHECK-NEXT:    [[I346:%.*]] = sext i32 [[I345]] to i64
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds { float, float }, ptr [[I343]], i64 [[I346]]
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I346]]
; CHECK-NEXT:    [[I348:%.*]] = or i32 [[I305]], 7
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP25]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP26]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I349:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I350:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I351:%.*]] = add nsw i32 [[I350]], [[I348]]
; CHECK-NEXT:    [[I352:%.*]] = sext i32 [[I351]] to i64
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds { float, float }, ptr [[I349]], i64 [[I352]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[TMP12]], i64 [[I352]]
; CHECK-NEXT:    [[I354]] = add nuw nsw i32 [[I305]], 8
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP27]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP28]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I355]] = add i32 [[I306]], 8
; CHECK-NEXT:    [[I356:%.*]] = icmp eq i32 [[I355]], [[I303]]
; CHECK-NEXT:    br i1 [[I356]], label [[BB357]], label [[BB304]]
; CHECK:       bb357:
; CHECK-NEXT:    [[I358:%.*]] = phi i32 [ 0, [[BB299]] ], [ [[I354]], [[BB304]] ]
; CHECK-NEXT:    [[I359:%.*]] = icmp eq i32 [[I300]], 0
; CHECK-NEXT:    br i1 [[I359]], label [[BB414]], label [[BB360:%.*]]
; CHECK:       bb360:
; CHECK-NEXT:    [[TMP29:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I361:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I362:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I363:%.*]] = add nsw i32 [[I362]], [[I358]]
; CHECK-NEXT:    [[I364:%.*]] = sext i32 [[I363]] to i64
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds { float, float }, ptr [[I361]], i64 [[I364]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i64, ptr [[TMP29]], i64 [[I364]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP30]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP31]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I366:%.*]] = icmp eq i32 [[I300]], 1
; CHECK-NEXT:    br i1 [[I366]], label [[BB414]], label [[BB367:%.*]]
; CHECK:       bb367:
; CHECK-NEXT:    [[I368:%.*]] = add nuw nsw i32 [[I358]], 1
; CHECK-NEXT:    [[TMP32:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I369:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I370:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I371:%.*]] = add nsw i32 [[I370]], [[I368]]
; CHECK-NEXT:    [[I372:%.*]] = sext i32 [[I371]] to i64
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds { float, float }, ptr [[I369]], i64 [[I372]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i64, ptr [[TMP32]], i64 [[I372]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP33]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP34]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I374:%.*]] = icmp eq i32 [[I300]], 2
; CHECK-NEXT:    br i1 [[I374]], label [[BB414]], label [[BB375:%.*]]
; CHECK:       bb375:
; CHECK-NEXT:    [[I376:%.*]] = add nuw nsw i32 [[I358]], 2
; CHECK-NEXT:    [[TMP35:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I377:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I378:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I379:%.*]] = add nsw i32 [[I378]], [[I376]]
; CHECK-NEXT:    [[I380:%.*]] = sext i32 [[I379]] to i64
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds { float, float }, ptr [[I377]], i64 [[I380]]
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i64, ptr [[TMP35]], i64 [[I380]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP36]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP37]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I382:%.*]] = icmp eq i32 [[I300]], 3
; CHECK-NEXT:    br i1 [[I382]], label [[BB414]], label [[BB383:%.*]]
; CHECK:       bb383:
; CHECK-NEXT:    [[I384:%.*]] = add nuw nsw i32 [[I358]], 3
; CHECK-NEXT:    [[TMP38:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I385:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I386:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I387:%.*]] = add nsw i32 [[I386]], [[I384]]
; CHECK-NEXT:    [[I388:%.*]] = sext i32 [[I387]] to i64
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds { float, float }, ptr [[I385]], i64 [[I388]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i64, ptr [[TMP38]], i64 [[I388]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP39]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP40]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I390:%.*]] = icmp eq i32 [[I300]], 4
; CHECK-NEXT:    br i1 [[I390]], label [[BB414]], label [[BB391:%.*]]
; CHECK:       bb391:
; CHECK-NEXT:    [[I392:%.*]] = add nuw nsw i32 [[I358]], 4
; CHECK-NEXT:    [[TMP41:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I393:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I394:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I395:%.*]] = add nsw i32 [[I394]], [[I392]]
; CHECK-NEXT:    [[I396:%.*]] = sext i32 [[I395]] to i64
; CHECK-NEXT:    [[TMP42:%.*]] = getelementptr inbounds { float, float }, ptr [[I393]], i64 [[I396]]
; CHECK-NEXT:    [[TMP43:%.*]] = getelementptr inbounds i64, ptr [[TMP41]], i64 [[I396]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP42]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP43]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I398:%.*]] = icmp eq i32 [[I300]], 5
; CHECK-NEXT:    br i1 [[I398]], label [[BB414]], label [[BB399:%.*]]
; CHECK:       bb399:
; CHECK-NEXT:    [[I400:%.*]] = add nuw nsw i32 [[I358]], 5
; CHECK-NEXT:    [[TMP44:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I401:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I402:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I403:%.*]] = add nsw i32 [[I402]], [[I400]]
; CHECK-NEXT:    [[I404:%.*]] = sext i32 [[I403]] to i64
; CHECK-NEXT:    [[TMP45:%.*]] = getelementptr inbounds { float, float }, ptr [[I401]], i64 [[I404]]
; CHECK-NEXT:    [[TMP46:%.*]] = getelementptr inbounds i64, ptr [[TMP44]], i64 [[I404]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP45]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP46]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    [[I406:%.*]] = icmp eq i32 [[I300]], 6
; CHECK-NEXT:    br i1 [[I406]], label [[BB414]], label [[BB407:%.*]]
; CHECK:       bb407:
; CHECK-NEXT:    [[I408:%.*]] = add nuw nsw i32 [[I358]], 6
; CHECK-NEXT:    [[TMP47:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I409:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I410:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I411:%.*]] = add nsw i32 [[I410]], [[I408]]
; CHECK-NEXT:    [[I412:%.*]] = sext i32 [[I411]] to i64
; CHECK-NEXT:    [[TMP48:%.*]] = getelementptr inbounds { float, float }, ptr [[I409]], i64 [[I412]]
; CHECK-NEXT:    [[TMP49:%.*]] = getelementptr inbounds i64, ptr [[TMP47]], i64 [[I412]]
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP48]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(8) [[TMP49]], i8 0, i64 8, i1 false)
; CHECK-NEXT:    br label [[BB414]]
; CHECK:       bb414:
; CHECK-NEXT:    [[I415:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I416:%.*]] = add nsw i32 [[I415]], [[I278]]
; CHECK-NEXT:    [[I417:%.*]] = sext i32 [[I416]] to i64
; CHECK-NEXT:    [[I418:%.*]] = tail call noalias ptr @calloc(i64 noundef [[I417]], i64 noundef 1)
; CHECK-NEXT:    [[I419:%.*]] = icmp eq ptr [[I418]], null
; CHECK-NEXT:    br i1 [[I419]], label [[BB420:%.*]], label [[BB422:%.*]]
; CHECK:       bb420:
; CHECK-NEXT:    [[I421:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.3, i64 noundef [[I417]])
; CHECK-NEXT:    tail call void @exit(i32 noundef signext 1)
; CHECK-NEXT:    unreachable
; CHECK:       bb422:
; CHECK-NEXT:    [[I423:%.*]] = sext i32 [[I415]] to i64
; CHECK-NEXT:    [[I424:%.*]] = add nsw i64 [[I423]], [[I290]]
; CHECK-NEXT:    [[I425:%.*]] = load i64, ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I426:%.*]] = add nsw i64 [[I425]], [[I424]]
; CHECK-NEXT:    store i64 [[I426]], ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I427:%.*]] = load i64, ptr @quantum_memman.max, align 8
; CHECK-NEXT:    [[I428:%.*]] = icmp sgt i64 [[I426]], [[I427]]
; CHECK-NEXT:    br i1 [[I428]], label [[BB429:%.*]], label [[BB430:%.*]]
; CHECK:       bb429:
; CHECK-NEXT:    store i64 [[I426]], ptr @quantum_memman.max, align 8
; CHECK-NEXT:    br label [[BB430]]
; CHECK:       bb430:
; CHECK-NEXT:    [[I431:%.*]] = load i32, ptr [[ARG1]], align 8
; CHECK-NEXT:    [[I432:%.*]] = zext i32 [[I431]] to i64
; CHECK-NEXT:    [[I433:%.*]] = shl nuw i64 1, [[I432]]
; CHECK-NEXT:    [[I434:%.*]] = uitofp i64 [[I433]] to double
; CHECK-NEXT:    [[I435:%.*]] = fdiv fast double 0x3EB0C6F7A0B5ED8D, [[I434]]
; CHECK-NEXT:    [[I436:%.*]] = fptrunc double [[I435]] to float
; CHECK-NEXT:    [[I437:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I438:%.*]] = icmp sgt i32 [[I437]], 0
; CHECK-NEXT:    br i1 [[I438]], label [[BB439:%.*]], label [[BB655:%.*]]
; CHECK:       bb439:
; CHECK-NEXT:    [[I440:%.*]] = zext i32 [[ARG]] to i64
; CHECK-NEXT:    [[I441:%.*]] = shl nuw i64 1, [[I440]]
; CHECK-NEXT:    [[I442:%.*]] = getelementptr inbounds i8, ptr [[ARG1]], i64 24
; CHECK-NEXT:    [[I443:%.*]] = and i64 [[I441]], 4294967295
; CHECK-NEXT:    [[I444:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 0, i32 1
; CHECK-NEXT:    [[I445:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 1
; CHECK-NEXT:    [[I446:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 1, i32 1
; CHECK-NEXT:    [[I447:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 2
; CHECK-NEXT:    [[I448:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 2, i32 1
; CHECK-NEXT:    [[I449:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 3
; CHECK-NEXT:    [[I450:%.*]] = getelementptr inbounds { float, float }, ptr [[I21]], i64 3, i32 1
; CHECK-NEXT:    br label [[BB451:%.*]]
; CHECK:       bb451:
; CHECK-NEXT:    [[I452:%.*]] = phi i8 [ 0, [[BB439]] ], [ [[I652:%.*]], [[BB650:%.*]] ]
; CHECK-NEXT:    [[I453:%.*]] = phi i64 [ 0, [[BB439]] ], [ [[I646:%.*]], [[BB650]] ]
; CHECK-NEXT:    [[I454:%.*]] = phi i32 [ [[I437]], [[BB439]] ], [ [[I645:%.*]], [[BB650]] ]
; CHECK-NEXT:    [[I455:%.*]] = icmp eq i8 [[I452]], 0
; CHECK-NEXT:    br i1 [[I455]], label [[BB456:%.*]], label [[BB644:%.*]]
; CHECK:       bb456:
; CHECK-NEXT:    [[TMP50:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I457:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[TMP51:%.*]] = getelementptr inbounds i64, ptr [[TMP50]], i64 [[I453]]
; CHECK-NEXT:    [[I459:%.*]] = load i64, ptr [[TMP51]], align 8
; CHECK-NEXT:    [[I460:%.*]] = xor i64 [[I459]], [[I441]]
; CHECK-NEXT:    [[I461:%.*]] = load i32, ptr [[I29]], align 8
; CHECK-NEXT:    [[I462:%.*]] = load ptr, ptr [[I442]], align 8
; CHECK-NEXT:    [[I463:%.*]] = lshr i64 [[I460]], 32
; CHECK-NEXT:    [[I464:%.*]] = xor i64 [[I463]], [[I460]]
; CHECK-NEXT:    [[I465:%.*]] = trunc i64 [[I464]] to i32
; CHECK-NEXT:    [[I466:%.*]] = mul i32 [[I465]], -1640562687
; CHECK-NEXT:    [[I467:%.*]] = sub nsw i32 32, [[I461]]
; CHECK-NEXT:    [[I468:%.*]] = lshr i32 [[I466]], [[I467]]
; CHECK-NEXT:    [[I469:%.*]] = sext i32 [[I468]] to i64
; CHECK-NEXT:    [[I470:%.*]] = getelementptr inbounds i32, ptr [[I462]], i64 [[I469]]
; CHECK-NEXT:    [[I471:%.*]] = load i32, ptr [[I470]], align 4
; CHECK-NEXT:    [[I472:%.*]] = icmp eq i32 [[I471]], 0
; CHECK-NEXT:    br i1 [[I472]], label [[BB491:%.*]], label [[BB473:%.*]]
; CHECK:       bb473:
; CHECK-NEXT:    [[I474:%.*]] = shl nuw i32 1, [[I461]]
; CHECK-NEXT:    br label [[BB475:%.*]]
; CHECK:       bb475:
; CHECK-NEXT:    [[I476:%.*]] = phi i32 [ [[I471]], [[BB473]] ], [ [[I489:%.*]], [[BB483:%.*]] ]
; CHECK-NEXT:    [[I477:%.*]] = phi i32 [ [[I468]], [[BB473]] ], [ [[I486:%.*]], [[BB483]] ]
; CHECK-NEXT:    [[I478:%.*]] = add nsw i32 [[I476]], -1
; CHECK-NEXT:    [[I479:%.*]] = sext i32 [[I478]] to i64
; CHECK-NEXT:    [[TMP52:%.*]] = getelementptr inbounds i64, ptr [[TMP50]], i64 [[I479]]
; CHECK-NEXT:    [[I481:%.*]] = load i64, ptr [[TMP52]], align 8
; CHECK-NEXT:    [[I482:%.*]] = icmp eq i64 [[I481]], [[I460]]
; CHECK-NEXT:    br i1 [[I482]], label [[BB496:%.*]], label [[BB483]]
; CHECK:       bb483:
; CHECK-NEXT:    [[I484:%.*]] = add nsw i32 [[I477]], 1
; CHECK-NEXT:    [[I485:%.*]] = icmp eq i32 [[I484]], [[I474]]
; CHECK-NEXT:    [[I486]] = select i1 [[I485]], i32 0, i32 [[I484]]
; CHECK-NEXT:    [[I487:%.*]] = sext i32 [[I486]] to i64
; CHECK-NEXT:    [[I488:%.*]] = getelementptr inbounds i32, ptr [[I462]], i64 [[I487]]
; CHECK-NEXT:    [[I489]] = load i32, ptr [[I488]], align 4
; CHECK-NEXT:    [[I490:%.*]] = icmp eq i32 [[I489]], 0
; CHECK-NEXT:    br i1 [[I490]], label [[BB491]], label [[BB475]]
; CHECK:       bb491:
; CHECK-NEXT:    [[TMP53:%.*]] = getelementptr inbounds { float, float }, ptr [[I457]], i64 [[I453]]
; CHECK-NEXT:    [[I493:%.*]] = load float, ptr [[TMP53]], align 8
; CHECK-NEXT:    [[I494:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP53]], i64 0, i32 1
; CHECK-NEXT:    [[I495:%.*]] = load float, ptr [[I494]], align 4
; CHECK-NEXT:    br label [[BB508:%.*]]
; CHECK:       bb496:
; CHECK-NEXT:    [[TMP54:%.*]] = getelementptr inbounds { float, float }, ptr [[I457]], i64 [[I453]]
; CHECK-NEXT:    [[I498:%.*]] = load float, ptr [[TMP54]], align 8
; CHECK-NEXT:    [[I499:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP54]], i64 0, i32 1
; CHECK-NEXT:    [[I500:%.*]] = load float, ptr [[I499]], align 4
; CHECK-NEXT:    [[I501:%.*]] = icmp sgt i32 [[I476]], 0
; CHECK-NEXT:    br i1 [[I501]], label [[BB502:%.*]], label [[BB508]]
; CHECK:       bb502:
; CHECK-NEXT:    [[I503:%.*]] = zext i32 [[I478]] to i64
; CHECK-NEXT:    [[TMP55:%.*]] = getelementptr inbounds { float, float }, ptr [[I457]], i64 [[I503]]
; CHECK-NEXT:    [[I505:%.*]] = load float, ptr [[TMP55]], align 8
; CHECK-NEXT:    [[I506:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP55]], i64 0, i32 1
; CHECK-NEXT:    [[I507:%.*]] = load float, ptr [[I506]], align 4
; CHECK-NEXT:    br label [[BB508]]
; CHECK:       bb508:
; CHECK-NEXT:    [[I509:%.*]] = phi i1 [ true, [[BB502]] ], [ false, [[BB496]] ], [ false, [[BB491]] ]
; CHECK-NEXT:    [[I510:%.*]] = phi float [ [[I500]], [[BB502]] ], [ [[I500]], [[BB496]] ], [ [[I495]], [[BB491]] ]
; CHECK-NEXT:    [[I511:%.*]] = phi ptr [ [[I499]], [[BB502]] ], [ [[I499]], [[BB496]] ], [ [[I494]], [[BB491]] ]
; CHECK-NEXT:    [[I512:%.*]] = phi float [ [[I498]], [[BB502]] ], [ [[I498]], [[BB496]] ], [ [[I493]], [[BB491]] ]
; CHECK-NEXT:    [[I513:%.*]] = phi ptr [ [[TMP54]], [[BB502]] ], [ [[TMP54]], [[BB496]] ], [ [[TMP53]], [[BB491]] ]
; CHECK-NEXT:    [[I514:%.*]] = phi i32 [ [[I478]], [[BB502]] ], [ [[I478]], [[BB496]] ], [ -1, [[BB491]] ]
; CHECK-NEXT:    [[I515:%.*]] = phi float [ [[I505]], [[BB502]] ], [ 0.000000e+00, [[BB496]] ], [ 0.000000e+00, [[BB491]] ]
; CHECK-NEXT:    [[I516:%.*]] = phi float [ [[I507]], [[BB502]] ], [ 0.000000e+00, [[BB496]] ], [ 0.000000e+00, [[BB491]] ]
; CHECK-NEXT:    [[I517:%.*]] = and i64 [[I443]], [[I459]]
; CHECK-NEXT:    [[I518:%.*]] = icmp ne i64 [[I517]], 0
; CHECK-NEXT:    br i1 [[I518]], label [[BB519:%.*]], label [[BB538:%.*]]
; CHECK:       bb519:
; CHECK-NEXT:    [[I520:%.*]] = load float, ptr [[I447]], align 4
; CHECK-NEXT:    [[I521:%.*]] = load float, ptr [[I448]], align 4
; CHECK-NEXT:    [[I522:%.*]] = fmul fast float [[I520]], [[I515]]
; CHECK-NEXT:    [[I523:%.*]] = fmul fast float [[I520]], [[I516]]
; CHECK-NEXT:    [[I524:%.*]] = fmul fast float [[I521]], [[I515]]
; CHECK-NEXT:    [[I525:%.*]] = fmul fast float [[I521]], [[I516]]
; CHECK-NEXT:    [[I526:%.*]] = load float, ptr [[I449]], align 4
; CHECK-NEXT:    [[I527:%.*]] = fmul fast float [[I526]], [[I510]]
; CHECK-NEXT:    [[I528:%.*]] = load float, ptr [[I450]], align 4
; CHECK-NEXT:    [[I529:%.*]] = fmul fast float [[I528]], [[I512]]
; CHECK-NEXT:    [[I530:%.*]] = fmul fast float [[I526]], [[I512]]
; CHECK-NEXT:    [[I531:%.*]] = fmul fast float [[I528]], [[I510]]
; CHECK-NEXT:    [[I532:%.*]] = fadd fast float [[I531]], [[I525]]
; CHECK-NEXT:    [[I533:%.*]] = fadd fast float [[I530]], [[I522]]
; CHECK-NEXT:    [[I534:%.*]] = fsub fast float [[I533]], [[I532]]
; CHECK-NEXT:    [[I535:%.*]] = fadd fast float [[I524]], [[I523]]
; CHECK-NEXT:    [[I536:%.*]] = fadd fast float [[I535]], [[I527]]
; CHECK-NEXT:    [[I537:%.*]] = fadd fast float [[I536]], [[I529]]
; CHECK-NEXT:    store float [[I534]], ptr [[I513]], align 8
; CHECK-NEXT:    store float [[I537]], ptr [[I511]], align 4
; CHECK-NEXT:    br i1 [[I509]], label [[BB557:%.*]], label [[BB603:%.*]]
; CHECK:       bb538:
; CHECK-NEXT:    [[I539:%.*]] = load float, ptr [[I21]], align 4
; CHECK-NEXT:    [[I540:%.*]] = load float, ptr [[I444]], align 4
; CHECK-NEXT:    [[I541:%.*]] = fmul fast float [[I539]], [[I512]]
; CHECK-NEXT:    [[I542:%.*]] = fmul fast float [[I539]], [[I510]]
; CHECK-NEXT:    [[I543:%.*]] = fmul fast float [[I540]], [[I512]]
; CHECK-NEXT:    [[I544:%.*]] = fmul fast float [[I540]], [[I510]]
; CHECK-NEXT:    [[I545:%.*]] = load float, ptr [[I445]], align 4
; CHECK-NEXT:    [[I546:%.*]] = fmul fast float [[I545]], [[I516]]
; CHECK-NEXT:    [[I547:%.*]] = load float, ptr [[I446]], align 4
; CHECK-NEXT:    [[I548:%.*]] = fmul fast float [[I547]], [[I515]]
; CHECK-NEXT:    [[I549:%.*]] = fmul fast float [[I545]], [[I515]]
; CHECK-NEXT:    [[I550:%.*]] = fmul fast float [[I547]], [[I516]]
; CHECK-NEXT:    [[I551:%.*]] = fadd fast float [[I550]], [[I544]]
; CHECK-NEXT:    [[I552:%.*]] = fadd fast float [[I549]], [[I541]]
; CHECK-NEXT:    [[I553:%.*]] = fsub fast float [[I552]], [[I551]]
; CHECK-NEXT:    [[I554:%.*]] = fadd fast float [[I543]], [[I542]]
; CHECK-NEXT:    [[I555:%.*]] = fadd fast float [[I554]], [[I546]]
; CHECK-NEXT:    [[I556:%.*]] = fadd fast float [[I555]], [[I548]]
; CHECK-NEXT:    store float [[I553]], ptr [[I513]], align 8
; CHECK-NEXT:    store float [[I556]], ptr [[I511]], align 4
; CHECK-NEXT:    br i1 [[I509]], label [[BB580:%.*]], label [[BB603]]
; CHECK:       bb557:
; CHECK-NEXT:    [[I558:%.*]] = load float, ptr [[I21]], align 4
; CHECK-NEXT:    [[I559:%.*]] = load float, ptr [[I444]], align 4
; CHECK-NEXT:    [[I560:%.*]] = fmul fast float [[I558]], [[I515]]
; CHECK-NEXT:    [[I561:%.*]] = fmul fast float [[I558]], [[I516]]
; CHECK-NEXT:    [[I562:%.*]] = fmul fast float [[I559]], [[I515]]
; CHECK-NEXT:    [[I563:%.*]] = fmul fast float [[I559]], [[I516]]
; CHECK-NEXT:    [[I564:%.*]] = load float, ptr [[I445]], align 4
; CHECK-NEXT:    [[I565:%.*]] = fmul fast float [[I564]], [[I510]]
; CHECK-NEXT:    [[I566:%.*]] = load float, ptr [[I446]], align 4
; CHECK-NEXT:    [[I567:%.*]] = fmul fast float [[I566]], [[I512]]
; CHECK-NEXT:    [[I568:%.*]] = fmul fast float [[I564]], [[I512]]
; CHECK-NEXT:    [[I569:%.*]] = fmul fast float [[I566]], [[I510]]
; CHECK-NEXT:    [[I570:%.*]] = fadd fast float [[I569]], [[I563]]
; CHECK-NEXT:    [[I571:%.*]] = fadd fast float [[I568]], [[I560]]
; CHECK-NEXT:    [[I572:%.*]] = fsub fast float [[I571]], [[I570]]
; CHECK-NEXT:    [[I573:%.*]] = fadd fast float [[I562]], [[I561]]
; CHECK-NEXT:    [[I574:%.*]] = fadd fast float [[I573]], [[I565]]
; CHECK-NEXT:    [[I575:%.*]] = fadd fast float [[I574]], [[I567]]
; CHECK-NEXT:    [[I576:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I577:%.*]] = zext i32 [[I514]] to i64
; CHECK-NEXT:    [[TMP56:%.*]] = getelementptr inbounds { float, float }, ptr [[I576]], i64 [[I577]]
; CHECK-NEXT:    [[I579:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP56]], i64 0, i32 1
; CHECK-NEXT:    store float [[I572]], ptr [[TMP56]], align 8
; CHECK-NEXT:    store float [[I575]], ptr [[I579]], align 4
; CHECK-NEXT:    br label [[BB641:%.*]]
; CHECK:       bb580:
; CHECK-NEXT:    [[I581:%.*]] = load float, ptr [[I447]], align 4
; CHECK-NEXT:    [[I582:%.*]] = load float, ptr [[I448]], align 4
; CHECK-NEXT:    [[I583:%.*]] = fmul fast float [[I581]], [[I512]]
; CHECK-NEXT:    [[I584:%.*]] = fmul fast float [[I581]], [[I510]]
; CHECK-NEXT:    [[I585:%.*]] = fmul fast float [[I582]], [[I512]]
; CHECK-NEXT:    [[I586:%.*]] = fmul fast float [[I582]], [[I510]]
; CHECK-NEXT:    [[I587:%.*]] = load float, ptr [[I449]], align 4
; CHECK-NEXT:    [[I588:%.*]] = fmul fast float [[I587]], [[I516]]
; CHECK-NEXT:    [[I589:%.*]] = load float, ptr [[I450]], align 4
; CHECK-NEXT:    [[I590:%.*]] = fmul fast float [[I589]], [[I515]]
; CHECK-NEXT:    [[I591:%.*]] = fmul fast float [[I587]], [[I515]]
; CHECK-NEXT:    [[I592:%.*]] = fmul fast float [[I589]], [[I516]]
; CHECK-NEXT:    [[I593:%.*]] = fadd fast float [[I592]], [[I586]]
; CHECK-NEXT:    [[I594:%.*]] = fadd fast float [[I591]], [[I583]]
; CHECK-NEXT:    [[I595:%.*]] = fsub fast float [[I594]], [[I593]]
; CHECK-NEXT:    [[I596:%.*]] = fadd fast float [[I585]], [[I584]]
; CHECK-NEXT:    [[I597:%.*]] = fadd fast float [[I596]], [[I588]]
; CHECK-NEXT:    [[I598:%.*]] = fadd fast float [[I597]], [[I590]]
; CHECK-NEXT:    [[I599:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I600:%.*]] = zext i32 [[I514]] to i64
; CHECK-NEXT:    [[TMP57:%.*]] = getelementptr inbounds { float, float }, ptr [[I599]], i64 [[I600]]
; CHECK-NEXT:    [[I602:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP57]], i64 0, i32 1
; CHECK-NEXT:    store float [[I595]], ptr [[TMP57]], align 8
; CHECK-NEXT:    store float [[I598]], ptr [[I602]], align 4
; CHECK-NEXT:    br label [[BB641]]
; CHECK:       bb603:
; CHECK-NEXT:    [[I604:%.*]] = load float, ptr [[I445]], align 4
; CHECK-NEXT:    [[I605:%.*]] = load float, ptr [[I446]], align 4
; CHECK-NEXT:    [[I606:%.*]] = fmul fast float [[I604]], [[I604]]
; CHECK-NEXT:    [[I607:%.*]] = fmul fast float [[I605]], [[I605]]
; CHECK-NEXT:    [[I608:%.*]] = fadd fast float [[I607]], [[I606]]
; CHECK-NEXT:    [[I609:%.*]] = fpext float [[I608]] to double
; CHECK-NEXT:    [[I610:%.*]] = fcmp fast olt double [[I609]], 1.000000e-09
; CHECK-NEXT:    [[I611:%.*]] = and i1 [[I518]], [[I610]]
; CHECK-NEXT:    br i1 [[I611]], label [[BB653:%.*]], label [[BB612:%.*]]
; CHECK:       bb612:
; CHECK-NEXT:    [[I613:%.*]] = load float, ptr [[I447]], align 4
; CHECK-NEXT:    [[I614:%.*]] = load float, ptr [[I448]], align 4
; CHECK-NEXT:    [[I615:%.*]] = fmul fast float [[I613]], [[I613]]
; CHECK-NEXT:    [[I616:%.*]] = fmul fast float [[I614]], [[I614]]
; CHECK-NEXT:    [[I617:%.*]] = fadd fast float [[I616]], [[I615]]
; CHECK-NEXT:    [[I618:%.*]] = fpext float [[I617]] to double
; CHECK-NEXT:    [[I619:%.*]] = fcmp fast uge double [[I618]], 1.000000e-09
; CHECK-NEXT:    [[I620:%.*]] = or i1 [[I518]], [[I619]]
; CHECK-NEXT:    br i1 [[I620]], label [[BB621:%.*]], label [[BB653]]
; CHECK:       bb621:
; CHECK-NEXT:    [[TMP58:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I622:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr inbounds i64, ptr [[TMP58]], i64 [[I453]]
; CHECK-NEXT:    [[I624:%.*]] = load i64, ptr [[TMP59]], align 8
; CHECK-NEXT:    [[I625:%.*]] = xor i64 [[I624]], [[I441]]
; CHECK-NEXT:    [[I626:%.*]] = sext i32 [[I454]] to i64
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr inbounds i64, ptr [[TMP58]], i64 [[I626]]
; CHECK-NEXT:    store i64 [[I625]], ptr [[TMP60]], align 8
; CHECK-NEXT:    [[TMP61:%.*]] = getelementptr inbounds { float, float }, ptr [[I622]], i64 [[I626]]
; CHECK-NEXT:    [[I629:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP61]], i64 0, i32 1
; CHECK-NEXT:    [[I630:%.*]] = select i1 [[I518]], ptr [[I445]], ptr [[I447]]
; CHECK-NEXT:    [[I631:%.*]] = select i1 [[I518]], ptr [[I446]], ptr [[I448]]
; CHECK-NEXT:    [[I632:%.*]] = load float, ptr [[I630]], align 4
; CHECK-NEXT:    [[I633:%.*]] = fmul fast float [[I632]], [[I510]]
; CHECK-NEXT:    [[I634:%.*]] = load float, ptr [[I631]], align 4
; CHECK-NEXT:    [[I635:%.*]] = fmul fast float [[I634]], [[I512]]
; CHECK-NEXT:    [[I636:%.*]] = fadd fast float [[I635]], [[I633]]
; CHECK-NEXT:    [[I637:%.*]] = fmul fast float [[I632]], [[I512]]
; CHECK-NEXT:    [[I638:%.*]] = fmul fast float [[I634]], [[I510]]
; CHECK-NEXT:    [[I639:%.*]] = fsub fast float [[I637]], [[I638]]
; CHECK-NEXT:    store float [[I639]], ptr [[TMP61]], align 8
; CHECK-NEXT:    store float [[I636]], ptr [[I629]], align 4
; CHECK-NEXT:    [[I640:%.*]] = add nsw i32 [[I454]], 1
; CHECK-NEXT:    br label [[BB644]]
; CHECK:       bb641:
; CHECK-NEXT:    [[I642:%.*]] = phi i64 [ [[I577]], [[BB557]] ], [ [[I600]], [[BB580]] ]
; CHECK-NEXT:    [[I643:%.*]] = getelementptr inbounds i8, ptr [[I418]], i64 [[I642]]
; CHECK-NEXT:    store i8 1, ptr [[I643]], align 1
; CHECK-NEXT:    br label [[BB644]]
; CHECK:       bb644:
; CHECK-NEXT:    [[I645]] = phi i32 [ [[I454]], [[BB451]] ], [ [[I454]], [[BB641]] ], [ [[I640]], [[BB621]] ]
; CHECK-NEXT:    [[I646]] = add nuw nsw i64 [[I453]], 1
; CHECK-NEXT:    [[I647:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I648:%.*]] = sext i32 [[I647]] to i64
; CHECK-NEXT:    [[I649:%.*]] = icmp slt i64 [[I646]], [[I648]]
; CHECK-NEXT:    br i1 [[I649]], label [[BB650]], label [[BB653]]
; CHECK:       bb650:
; CHECK-NEXT:    [[I651:%.*]] = getelementptr inbounds i8, ptr [[I418]], i64 [[I646]]
; CHECK-NEXT:    [[I652]] = load i8, ptr [[I651]], align 1
; CHECK-NEXT:    br label [[BB451]]
; CHECK:       bb653:
; CHECK-NEXT:    [[I654:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    br label [[BB655]]
; CHECK:       bb655:
; CHECK-NEXT:    [[I656:%.*]] = phi i32 [ [[I654]], [[BB653]] ], [ [[I437]], [[BB430]] ]
; CHECK-NEXT:    [[I657:%.*]] = add nsw i32 [[I656]], [[I278]]
; CHECK-NEXT:    store i32 [[I657]], ptr [[I39]], align 4
; CHECK-NEXT:    tail call void @free(ptr noundef [[I418]])
; CHECK-NEXT:    [[I658:%.*]] = sub nsw i32 0, [[I657]]
; CHECK-NEXT:    [[I659:%.*]] = sext i32 [[I658]] to i64
; CHECK-NEXT:    [[I660:%.*]] = load i64, ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I661:%.*]] = add nsw i64 [[I660]], [[I659]]
; CHECK-NEXT:    store i64 [[I661]], ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I662:%.*]] = load i64, ptr @quantum_memman.max, align 8
; CHECK-NEXT:    [[I663:%.*]] = icmp sgt i64 [[I661]], [[I662]]
; CHECK-NEXT:    br i1 [[I663]], label [[BB664:%.*]], label [[BB665:%.*]]
; CHECK:       bb664:
; CHECK-NEXT:    store i64 [[I661]], ptr @quantum_memman.max, align 8
; CHECK-NEXT:    br label [[BB665]]
; CHECK:       bb665:
; CHECK-NEXT:    [[I666:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I667:%.*]] = icmp sgt i32 [[I666]], 0
; CHECK-NEXT:    br i1 [[I667]], label [[BB668:%.*]], label [[BB726:%.*]]
; CHECK:       bb668:
; CHECK-NEXT:    [[I669:%.*]] = phi i32 [ [[I698:%.*]], [[BB697:%.*]] ], [ [[I666]], [[BB665]] ]
; CHECK-NEXT:    [[I670:%.*]] = phi i64 [ [[I701:%.*]], [[BB697]] ], [ 0, [[BB665]] ]
; CHECK-NEXT:    [[I671:%.*]] = phi i32 [ [[I700:%.*]], [[BB697]] ], [ 0, [[BB665]] ]
; CHECK-NEXT:    [[I672:%.*]] = phi i32 [ [[I699:%.*]], [[BB697]] ], [ 0, [[BB665]] ]
; CHECK-NEXT:    [[TMP62:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I673:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[TMP63:%.*]] = getelementptr inbounds { float, float }, ptr [[I673]], i64 [[I670]]
; CHECK-NEXT:    [[I675:%.*]] = load float, ptr [[TMP63]], align 8
; CHECK-NEXT:    [[I676:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP63]], i64 0, i32 1
; CHECK-NEXT:    [[I677:%.*]] = load float, ptr [[I676]], align 4
; CHECK-NEXT:    [[I678:%.*]] = fmul fast float [[I675]], [[I675]]
; CHECK-NEXT:    [[I679:%.*]] = fmul fast float [[I677]], [[I677]]
; CHECK-NEXT:    [[I680:%.*]] = fadd fast float [[I679]], [[I678]]
; CHECK-NEXT:    [[I681:%.*]] = fcmp fast olt float [[I680]], [[I436]]
; CHECK-NEXT:    br i1 [[I681]], label [[BB682:%.*]], label [[BB685:%.*]]
; CHECK:       bb682:
; CHECK-NEXT:    [[I683:%.*]] = add nsw i32 [[I671]], 1
; CHECK-NEXT:    [[I684:%.*]] = add nsw i32 [[I672]], 1
; CHECK-NEXT:    br label [[BB697]]
; CHECK:       bb685:
; CHECK-NEXT:    [[I686:%.*]] = icmp eq i32 [[I671]], 0
; CHECK-NEXT:    br i1 [[I686]], label [[BB697]], label [[BB687:%.*]]
; CHECK:       bb687:
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr inbounds i64, ptr [[TMP62]], i64 [[I670]]
; CHECK-NEXT:    [[I689:%.*]] = load i64, ptr [[TMP64]], align 8
; CHECK-NEXT:    [[I690:%.*]] = trunc i64 [[I670]] to i32
; CHECK-NEXT:    [[I691:%.*]] = sub nsw i32 [[I690]], [[I671]]
; CHECK-NEXT:    [[I692:%.*]] = sext i32 [[I691]] to i64
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds i64, ptr [[TMP62]], i64 [[I692]]
; CHECK-NEXT:    store i64 [[I689]], ptr [[TMP65]], align 8
; CHECK-NEXT:    [[TMP66:%.*]] = getelementptr inbounds { float, float }, ptr [[I673]], i64 [[I692]]
; CHECK-NEXT:    [[I695:%.*]] = getelementptr inbounds { float, float }, ptr [[TMP66]], i64 0, i32 1
; CHECK-NEXT:    store float [[I675]], ptr [[TMP66]], align 8
; CHECK-NEXT:    store float [[I677]], ptr [[I695]], align 4
; CHECK-NEXT:    [[I696:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    br label [[BB697]]
; CHECK:       bb697:
; CHECK-NEXT:    [[I698]] = phi i32 [ [[I669]], [[BB682]] ], [ [[I696]], [[BB687]] ], [ [[I669]], [[BB685]] ]
; CHECK-NEXT:    [[I699]] = phi i32 [ [[I684]], [[BB682]] ], [ [[I672]], [[BB687]] ], [ [[I672]], [[BB685]] ]
; CHECK-NEXT:    [[I700]] = phi i32 [ [[I683]], [[BB682]] ], [ [[I671]], [[BB687]] ], [ 0, [[BB685]] ]
; CHECK-NEXT:    [[I701]] = add nuw nsw i64 [[I670]], 1
; CHECK-NEXT:    [[I702:%.*]] = sext i32 [[I698]] to i64
; CHECK-NEXT:    [[I703:%.*]] = icmp slt i64 [[I701]], [[I702]]
; CHECK-NEXT:    br i1 [[I703]], label [[BB668]], label [[BB704:%.*]]
; CHECK:       bb704:
; CHECK-NEXT:    [[I705:%.*]] = icmp eq i32 [[I699]], 0
; CHECK-NEXT:    br i1 [[I705]], label [[BB726]], label [[BB706:%.*]]
; CHECK:       bb706:
; CHECK-NEXT:    [[I707:%.*]] = sub nsw i32 [[I698]], [[I699]]
; CHECK-NEXT:    store i32 [[I707]], ptr [[I39]], align 4
; CHECK-NEXT:    [[I708:%.*]] = load ptr, ptr [[I279]], align 8
; CHECK-NEXT:    [[I709:%.*]] = sext i32 [[I707]] to i64
; CHECK-NEXT:    [[I710:%.*]] = shl nsw i64 [[I709]], 4
; CHECK-NEXT:    [[TMP67:%.*]] = shl nsw i64 [[I709]], 3
; CHECK-NEXT:    [[TMP68:%.*]] = shl nsw i64 [[I709]], 3
; CHECK-NEXT:    [[TMP69:%.*]] = load ptr, ptr [[TMP7]], align 8
; CHECK-NEXT:    [[I711:%.*]] = tail call ptr @realloc(ptr noundef [[I708]], i64 noundef [[TMP68]])
; CHECK-NEXT:    [[TMP70:%.*]] = tail call ptr @realloc(ptr noundef [[TMP69]], i64 noundef [[TMP67]])
; CHECK-NEXT:    store ptr [[TMP70]], ptr [[TMP7]], align 8
; CHECK-NEXT:    store ptr [[I711]], ptr [[I279]], align 8
; CHECK-NEXT:    [[I712:%.*]] = icmp eq ptr [[I711]], null
; CHECK-NEXT:    br i1 [[I712]], label [[BB713:%.*]], label [[BB717:%.*]]
; CHECK:       bb713:
; CHECK-NEXT:    [[I714:%.*]] = load i32, ptr [[I39]], align 4
; CHECK-NEXT:    [[I715:%.*]] = add nsw i32 [[I714]], [[I278]]
; CHECK-NEXT:    [[I716:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.1.23, i32 noundef signext [[I715]])
; CHECK-NEXT:    tail call void @exit(i32 noundef signext 1)
; CHECK-NEXT:    unreachable
; CHECK:       bb717:
; CHECK-NEXT:    [[I718:%.*]] = sub nsw i32 0, [[I699]]
; CHECK-NEXT:    [[I719:%.*]] = sext i32 [[I718]] to i64
; CHECK-NEXT:    [[I720:%.*]] = shl nsw i64 [[I719]], 4
; CHECK-NEXT:    [[I721:%.*]] = load i64, ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I722:%.*]] = add nsw i64 [[I721]], [[I720]]
; CHECK-NEXT:    store i64 [[I722]], ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I723:%.*]] = load i64, ptr @quantum_memman.max, align 8
; CHECK-NEXT:    [[I724:%.*]] = icmp sgt i64 [[I722]], [[I723]]
; CHECK-NEXT:    br i1 [[I724]], label [[BB725:%.*]], label [[BB726]]
; CHECK:       bb725:
; CHECK-NEXT:    store i64 [[I722]], ptr @quantum_memman.max, align 8
; CHECK-NEXT:    br label [[BB726]]
; CHECK:       bb726:
; CHECK-NEXT:    [[I727:%.*]] = load i32, ptr @quantum_gate_counter.counter, align 4
; CHECK-NEXT:    [[I728:%.*]] = add nsw i32 [[I727]], 1
; CHECK-NEXT:    store i32 [[I728]], ptr @quantum_gate_counter.counter, align 4
; CHECK-NEXT:    [[I729:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_MATRIX_STRUCT]], ptr [[I]], i64 0, i32 2
; CHECK-NEXT:    [[I730:%.*]] = load ptr, ptr [[I729]], align 8
; CHECK-NEXT:    tail call void @free(ptr noundef [[I730]])
; CHECK-NEXT:    [[I731:%.*]] = getelementptr inbounds [[STRUCT_QUANTUM_MATRIX_STRUCT]], ptr [[I]], i64 0, i32 1
; CHECK-NEXT:    [[I732:%.*]] = load i32, ptr [[I731]], align 4
; CHECK-NEXT:    [[I733:%.*]] = sext i32 [[I732]] to i64
; CHECK-NEXT:    [[I734:%.*]] = mul nsw i64 [[I733]], -8
; CHECK-NEXT:    [[I735:%.*]] = load i32, ptr [[I]], align 8
; CHECK-NEXT:    [[I736:%.*]] = sext i32 [[I735]] to i64
; CHECK-NEXT:    [[I737:%.*]] = mul i64 [[I734]], [[I736]]
; CHECK-NEXT:    [[I738:%.*]] = load i64, ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I739:%.*]] = add nsw i64 [[I737]], [[I738]]
; CHECK-NEXT:    store i64 [[I739]], ptr @quantum_memman.mem, align 8
; CHECK-NEXT:    [[I740:%.*]] = load i64, ptr @quantum_memman.max, align 8
; CHECK-NEXT:    [[I741:%.*]] = icmp sgt i64 [[I739]], [[I740]]
; CHECK-NEXT:    br i1 [[I741]], label [[BB742:%.*]], label [[BB743:%.*]]
; CHECK:       bb742:
; CHECK-NEXT:    store i64 [[I739]], ptr @quantum_memman.max, align 8
; CHECK-NEXT:    br label [[BB743]]
; CHECK:       bb743:
; CHECK-NEXT:    store ptr null, ptr [[I729]], align 8
; CHECK-NEXT:    br label [[BB744]]
; CHECK:       bb744:
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr nonnull [[I]])
; CHECK-NEXT:    ret void
;
entry:
  %i = alloca %struct.quantum_matrix_struct, align 8
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %i)
  %i3 = add nsw i32 %arg2, 1
  %i4 = icmp eq i32 %i3, 0
  br i1 %i4, label %bb, label %bb744

bb:                                               ; preds = %entry
  %i5 = tail call noalias dereferenceable_or_null(32) ptr @calloc(i64 noundef 4, i64 noundef 8)
  %i6 = icmp eq ptr %i5, null
  br i1 %i6, label %bb7, label %bb9

bb7:                                              ; preds = %bb
  %i8 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str, i32 noundef signext 2, i32 noundef signext 2)
  tail call void @exit(i32 noundef signext 1)
  unreachable

bb9:                                              ; preds = %bb
  %i10 = load i64, ptr @quantum_memman.mem, align 8
  %i11 = add nsw i64 %i10, 32
  store i64 %i11, ptr @quantum_memman.mem, align 8
  %i12 = load i64, ptr @quantum_memman.max, align 8
  %i13 = icmp sgt i64 %i11, %i12
  br i1 %i13, label %bb14, label %bb15

bb14:                                             ; preds = %bb9
  store i64 %i11, ptr @quantum_memman.max, align 8
  br label %bb15

bb15:                                             ; preds = %bb14, %bb9
  %i16 = ptrtoint ptr %i5 to i64
  store i64 8589934594, ptr %i, align 8
  %i17 = getelementptr inbounds i8, ptr %i, i64 8
  store i64 %i16, ptr %i17, align 8
  %i18 = getelementptr inbounds { float, float }, ptr %i5, i64 0, i32 1
  store float 0x3FE6A09E60000000, ptr %i5, align 4
  store float 0.000000e+00, ptr %i18, align 4
  %i19 = getelementptr inbounds { float, float }, ptr %i5, i64 1
  %i20 = getelementptr inbounds { float, float }, ptr %i5, i64 1, i32 1
  store float 0x3FE6A09E60000000, ptr %i19, align 4
  store float 0.000000e+00, ptr %i20, align 4
  %i21 = load ptr, ptr %i17, align 8
  %i22 = getelementptr inbounds { float, float }, ptr %i21, i64 2
  %i23 = getelementptr inbounds { float, float }, ptr %i21, i64 2, i32 1
  store float 0x3FE6A09E60000000, ptr %i22, align 4
  store float 0.000000e+00, ptr %i23, align 4
  %i24 = getelementptr inbounds { float, float }, ptr %i21, i64 3
  %i25 = getelementptr inbounds { float, float }, ptr %i21, i64 3, i32 1
  store float 0xBFE6A09E60000000, ptr %i24, align 4
  store float 0.000000e+00, ptr %i25, align 4
  %i26 = load i64, ptr %i, align 8
  %i27 = icmp eq i64 %i26, 8589934594
  br i1 %i27, label %bb28, label %bb35

bb28:                                             ; preds = %bb15
  %i29 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 2
  %i30 = load i32, ptr %i29, align 8
  %i31 = icmp eq i32 %i30, 31
  br i1 %i31, label %bb37, label %bb32

bb32:                                             ; preds = %bb28
  %i33 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 4
  %i34 = load ptr, ptr %i33, align 8
  br label %bb47

bb35:                                             ; preds = %bb15
  %i36 = tail call i32 @puts(ptr nonnull dereferenceable(1) @str)
  tail call void @exit(i32 noundef signext 1)
  unreachable

bb37:                                             ; preds = %bb97, %bb90, %bb83, %bb76, %bb69, %bb62, %bb55, %bb47, %bb28
  %i38 = phi i32 [ 31, %bb28 ], [ %i51, %bb47 ], [ %i58, %bb55 ], [ %i65, %bb62 ], [ %i72, %bb69 ], [ %i79, %bb76 ], [ %i86, %bb83 ], [ %i93, %bb90 ], [ %i100, %bb97 ]
  %i39 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 1
  %i40 = load i32, ptr %i39, align 4
  %i41 = icmp sgt i32 %i40, 0
  br i1 %i41, label %bb42, label %bb106

bb42:                                             ; preds = %bb37
  %i43 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 3
  %i44 = load ptr, ptr %i43, align 8
  %i45 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 4
  %i46 = load ptr, ptr %i45, align 8
  br label %bb125

bb47:                                             ; preds = %bb97, %bb32
  %i48 = phi i64 [ 0, %bb32 ], [ %i99, %bb97 ]
  %i49 = getelementptr inbounds i32, ptr %i34, i64 %i48
  store i32 0, ptr %i49, align 4
  %i50 = or i64 %i48, 1
  %i51 = load i32, ptr %i29, align 8
  %i52 = shl nuw i32 1, %i51
  %i53 = sext i32 %i52 to i64
  %i54 = icmp slt i64 %i50, %i53
  br i1 %i54, label %bb55, label %bb37

bb55:                                             ; preds = %bb47
  %i56 = getelementptr inbounds i32, ptr %i34, i64 %i50
  store i32 0, ptr %i56, align 4
  %i57 = or i64 %i48, 2
  %i58 = load i32, ptr %i29, align 8
  %i59 = shl nuw i32 1, %i58
  %i60 = sext i32 %i59 to i64
  %i61 = icmp slt i64 %i57, %i60
  br i1 %i61, label %bb62, label %bb37

bb62:                                             ; preds = %bb55
  %i63 = getelementptr inbounds i32, ptr %i34, i64 %i57
  store i32 0, ptr %i63, align 4
  %i64 = or i64 %i48, 3
  %i65 = load i32, ptr %i29, align 8
  %i66 = shl nuw i32 1, %i65
  %i67 = sext i32 %i66 to i64
  %i68 = icmp slt i64 %i64, %i67
  br i1 %i68, label %bb69, label %bb37

bb69:                                             ; preds = %bb62
  %i70 = getelementptr inbounds i32, ptr %i34, i64 %i64
  store i32 0, ptr %i70, align 4
  %i71 = or i64 %i48, 4
  %i72 = load i32, ptr %i29, align 8
  %i73 = shl nuw i32 1, %i72
  %i74 = sext i32 %i73 to i64
  %i75 = icmp slt i64 %i71, %i74
  br i1 %i75, label %bb76, label %bb37

bb76:                                             ; preds = %bb69
  %i77 = getelementptr inbounds i32, ptr %i34, i64 %i71
  store i32 0, ptr %i77, align 4
  %i78 = or i64 %i48, 5
  %i79 = load i32, ptr %i29, align 8
  %i80 = shl nuw i32 1, %i79
  %i81 = sext i32 %i80 to i64
  %i82 = icmp slt i64 %i78, %i81
  br i1 %i82, label %bb83, label %bb37

bb83:                                             ; preds = %bb76
  %i84 = getelementptr inbounds i32, ptr %i34, i64 %i78
  store i32 0, ptr %i84, align 4
  %i85 = or i64 %i48, 6
  %i86 = load i32, ptr %i29, align 8
  %i87 = shl nuw i32 1, %i86
  %i88 = sext i32 %i87 to i64
  %i89 = icmp slt i64 %i85, %i88
  br i1 %i89, label %bb90, label %bb37

bb90:                                             ; preds = %bb83
  %i91 = getelementptr inbounds i32, ptr %i34, i64 %i85
  store i32 0, ptr %i91, align 4
  %i92 = or i64 %i48, 7
  %i93 = load i32, ptr %i29, align 8
  %i94 = shl nuw i32 1, %i93
  %i95 = sext i32 %i94 to i64
  %i96 = icmp slt i64 %i92, %i95
  br i1 %i96, label %bb97, label %bb37

bb97:                                             ; preds = %bb90
  %i98 = getelementptr inbounds i32, ptr %i34, i64 %i92
  store i32 0, ptr %i98, align 4
  %i99 = add nuw nsw i64 %i48, 8
  %i100 = load i32, ptr %i29, align 8
  %i101 = shl nuw i32 1, %i100
  %i102 = sext i32 %i101 to i64
  %i103 = icmp slt i64 %i99, %i102
  br i1 %i103, label %bb47, label %bb37

bb104:                                            ; preds = %bb207
  %i105 = icmp sgt i32 %i211, 0
  br i1 %i105, label %bb110, label %bb106

bb106:                                            ; preds = %bb104, %bb37
  %i107 = phi i32 [ %i211, %bb104 ], [ %i40, %bb37 ]
  %i108 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 3
  %i109 = load ptr, ptr %i108, align 8
  br label %bb275

bb110:                                            ; preds = %bb104
  %i111 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 3
  %i112 = load ptr, ptr %i111, align 8
  %i113 = zext i32 %arg to i64
  %i114 = shl nuw i64 1, %i113
  %i115 = load i32, ptr %i29, align 8
  %i116 = getelementptr inbounds i8, ptr %arg1, i64 24
  %i117 = load ptr, ptr %i116, align 8
  %i118 = sub nsw i32 32, %i115
  %i119 = shl nuw i32 1, %i115
  %i120 = getelementptr inbounds { float, float }, ptr %i21, i64 1
  %i121 = getelementptr inbounds { float, float }, ptr %i21, i64 1, i32 1
  %i122 = getelementptr inbounds { float, float }, ptr %i21, i64 2
  %i123 = getelementptr inbounds { float, float }, ptr %i21, i64 2, i32 1
  %i124 = zext i32 %i211 to i64
  br label %bb216

bb125:                                            ; preds = %bb214, %bb42
  %i126 = phi i32 [ %i38, %bb42 ], [ %i215, %bb214 ]
  %i127 = phi i64 [ 0, %bb42 ], [ %i209, %bb214 ]
  %i128 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i44, i64 %i127, i32 1
  %i129 = load i64, ptr %i128, align 8
  %i130 = lshr i64 %i129, 32
  %i131 = xor i64 %i130, %i129
  %i132 = trunc i64 %i131 to i32
  %i133 = mul i32 %i132, -1640562687
  %i134 = sub nsw i32 32, %i126
  %i135 = lshr i32 %i133, %i134
  %i136 = sext i32 %i135 to i64
  %i137 = getelementptr inbounds i32, ptr %i46, i64 %i136
  %i138 = load i32, ptr %i137, align 4
  %i139 = icmp eq i32 %i138, 0
  br i1 %i139, label %bb207, label %bb140

bb140:                                            ; preds = %bb125
  %i141 = shl nuw i32 1, %i126
  br label %bb142

bb142:                                            ; preds = %bb199, %bb140
  %i143 = phi i32 [ %i135, %bb140 ], [ %i202, %bb199 ]
  %i144 = add nsw i32 %i143, 1
  %i145 = icmp eq i32 %i144, %i141
  %i146 = select i1 %i145, i32 0, i32 %i144
  %i147 = sext i32 %i146 to i64
  %i148 = getelementptr inbounds i32, ptr %i46, i64 %i147
  %i149 = load i32, ptr %i148, align 4
  %i150 = icmp eq i32 %i149, 0
  br i1 %i150, label %bb207, label %bb151

bb151:                                            ; preds = %bb142
  %i152 = add nsw i32 %i146, 1
  %i153 = icmp eq i32 %i152, %i141
  %i154 = select i1 %i153, i32 0, i32 %i152
  %i155 = sext i32 %i154 to i64
  %i156 = getelementptr inbounds i32, ptr %i46, i64 %i155
  %i157 = load i32, ptr %i156, align 4
  %i158 = icmp eq i32 %i157, 0
  br i1 %i158, label %bb207, label %bb159

bb159:                                            ; preds = %bb151
  %i160 = add nsw i32 %i154, 1
  %i161 = icmp eq i32 %i160, %i141
  %i162 = select i1 %i161, i32 0, i32 %i160
  %i163 = sext i32 %i162 to i64
  %i164 = getelementptr inbounds i32, ptr %i46, i64 %i163
  %i165 = load i32, ptr %i164, align 4
  %i166 = icmp eq i32 %i165, 0
  br i1 %i166, label %bb207, label %bb167

bb167:                                            ; preds = %bb159
  %i168 = add nsw i32 %i162, 1
  %i169 = icmp eq i32 %i168, %i141
  %i170 = select i1 %i169, i32 0, i32 %i168
  %i171 = sext i32 %i170 to i64
  %i172 = getelementptr inbounds i32, ptr %i46, i64 %i171
  %i173 = load i32, ptr %i172, align 4
  %i174 = icmp eq i32 %i173, 0
  br i1 %i174, label %bb207, label %bb175

bb175:                                            ; preds = %bb167
  %i176 = add nsw i32 %i170, 1
  %i177 = icmp eq i32 %i176, %i141
  %i178 = select i1 %i177, i32 0, i32 %i176
  %i179 = sext i32 %i178 to i64
  %i180 = getelementptr inbounds i32, ptr %i46, i64 %i179
  %i181 = load i32, ptr %i180, align 4
  %i182 = icmp eq i32 %i181, 0
  br i1 %i182, label %bb207, label %bb183

bb183:                                            ; preds = %bb175
  %i184 = add nsw i32 %i178, 1
  %i185 = icmp eq i32 %i184, %i141
  %i186 = select i1 %i185, i32 0, i32 %i184
  %i187 = sext i32 %i186 to i64
  %i188 = getelementptr inbounds i32, ptr %i46, i64 %i187
  %i189 = load i32, ptr %i188, align 4
  %i190 = icmp eq i32 %i189, 0
  br i1 %i190, label %bb207, label %bb191

bb191:                                            ; preds = %bb183
  %i192 = add nsw i32 %i186, 1
  %i193 = icmp eq i32 %i192, %i141
  %i194 = select i1 %i193, i32 0, i32 %i192
  %i195 = sext i32 %i194 to i64
  %i196 = getelementptr inbounds i32, ptr %i46, i64 %i195
  %i197 = load i32, ptr %i196, align 4
  %i198 = icmp eq i32 %i197, 0
  br i1 %i198, label %bb207, label %bb199

bb199:                                            ; preds = %bb191
  %i200 = add nsw i32 %i194, 1
  %i201 = icmp eq i32 %i200, %i141
  %i202 = select i1 %i201, i32 0, i32 %i200
  %i203 = sext i32 %i202 to i64
  %i204 = getelementptr inbounds i32, ptr %i46, i64 %i203
  %i205 = load i32, ptr %i204, align 4
  %i206 = icmp eq i32 %i205, 0
  br i1 %i206, label %bb207, label %bb142

bb207:                                            ; preds = %bb199, %bb191, %bb183, %bb175, %bb167, %bb159, %bb151, %bb142, %bb125
  %i208 = phi ptr [ %i137, %bb125 ], [ %i148, %bb142 ], [ %i156, %bb151 ], [ %i164, %bb159 ], [ %i172, %bb167 ], [ %i180, %bb175 ], [ %i188, %bb183 ], [ %i196, %bb191 ], [ %i204, %bb199 ]
  %i209 = add nuw nsw i64 %i127, 1
  %i210 = trunc i64 %i209 to i32
  store i32 %i210, ptr %i208, align 4
  %i211 = load i32, ptr %i39, align 4
  %i212 = sext i32 %i211 to i64
  %i213 = icmp slt i64 %i209, %i212
  br i1 %i213, label %bb214, label %bb104

bb214:                                            ; preds = %bb207
  %i215 = load i32, ptr %i29, align 8
  br label %bb125

bb216:                                            ; preds = %bb271, %bb110
  %i217 = phi i64 [ 0, %bb110 ], [ %i273, %bb271 ]
  %i218 = phi i32 [ 0, %bb110 ], [ %i272, %bb271 ]
  %i219 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i112, i64 %i217, i32 1
  %i220 = load i64, ptr %i219, align 8
  %i221 = xor i64 %i220, %i114
  %i222 = lshr i64 %i221, 32
  %i223 = xor i64 %i222, %i221
  %i224 = trunc i64 %i223 to i32
  %i225 = mul i32 %i224, -1640562687
  %i226 = lshr i32 %i225, %i118
  %i227 = sext i32 %i226 to i64
  %i228 = getelementptr inbounds i32, ptr %i117, i64 %i227
  %i229 = load i32, ptr %i228, align 4
  %i230 = icmp eq i32 %i229, 0
  br i1 %i230, label %bb247, label %bb231

bb231:                                            ; preds = %bb239, %bb216
  %i232 = phi i32 [ %i245, %bb239 ], [ %i229, %bb216 ]
  %i233 = phi i32 [ %i242, %bb239 ], [ %i226, %bb216 ]
  %i234 = add nsw i32 %i232, -1
  %i235 = sext i32 %i234 to i64
  %i236 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i112, i64 %i235, i32 1
  %i237 = load i64, ptr %i236, align 8
  %i238 = icmp eq i64 %i237, %i221
  br i1 %i238, label %bb271, label %bb239

bb239:                                            ; preds = %bb231
  %i240 = add nsw i32 %i233, 1
  %i241 = icmp eq i32 %i240, %i119
  %i242 = select i1 %i241, i32 0, i32 %i240
  %i243 = sext i32 %i242 to i64
  %i244 = getelementptr inbounds i32, ptr %i117, i64 %i243
  %i245 = load i32, ptr %i244, align 4
  %i246 = icmp eq i32 %i245, 0
  br i1 %i246, label %bb247, label %bb231

bb247:                                            ; preds = %bb239, %bb216
  %i248 = load float, ptr %i120, align 4
  %i249 = load float, ptr %i121, align 4
  %i250 = fmul fast float %i248, %i248
  %i251 = fmul fast float %i249, %i249
  %i252 = fadd fast float %i251, %i250
  %i253 = fpext float %i252 to double
  %i254 = fcmp fast ogt double %i253, 1.000000e-09
  %i255 = and i64 %i220, %i114
  %i256 = icmp ne i64 %i255, 0
  %i257 = select i1 %i254, i1 %i256, i1 false
  %i258 = zext i1 %i257 to i32
  %i259 = add nsw i32 %i218, %i258
  %i260 = load float, ptr %i122, align 4
  %i261 = load float, ptr %i123, align 4
  %i262 = fmul fast float %i260, %i260
  %i263 = fmul fast float %i261, %i261
  %i264 = fadd fast float %i263, %i262
  %i265 = fpext float %i264 to double
  %i266 = fcmp fast ogt double %i265, 1.000000e-09
  br i1 %i266, label %bb267, label %bb271

bb267:                                            ; preds = %bb247
  %i268 = icmp eq i64 %i255, 0
  %i269 = zext i1 %i268 to i32
  %i270 = add nsw i32 %i259, %i269
  br label %bb271

bb271:                                            ; preds = %bb267, %bb247, %bb231
  %i272 = phi i32 [ %i259, %bb247 ], [ %i270, %bb267 ], [ %i218, %bb231 ]
  %i273 = add nuw nsw i64 %i217, 1
  %i274 = icmp eq i64 %i273, %i124
  br i1 %i274, label %bb275, label %bb216

bb275:                                            ; preds = %bb271, %bb106
  %i276 = phi i32 [ %i107, %bb106 ], [ %i211, %bb271 ]
  %i277 = phi ptr [ %i109, %bb106 ], [ %i112, %bb271 ]
  %i278 = phi i32 [ 0, %bb106 ], [ %i272, %bb271 ]
  %i279 = getelementptr inbounds %struct.quantum_reg_struct, ptr %arg1, i64 0, i32 3
  %i280 = add nsw i32 %i278, %i276
  %i281 = sext i32 %i280 to i64
  %i282 = shl nsw i64 %i281, 4
  %i283 = tail call ptr @realloc(ptr noundef %i277, i64 noundef %i282)
  store ptr %i283, ptr %i279, align 8
  %i284 = icmp eq ptr %i283, null
  br i1 %i284, label %bb285, label %bb289

bb285:                                            ; preds = %bb275
  %i286 = load i32, ptr %i39, align 4
  %i287 = add nsw i32 %i286, %i278
  %i288 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.1.23, i32 noundef signext %i287)
  tail call void @exit(i32 noundef signext 1)
  unreachable

bb289:                                            ; preds = %bb275
  %i290 = sext i32 %i278 to i64
  %i291 = shl nsw i64 %i290, 4
  %i292 = load i64, ptr @quantum_memman.mem, align 8
  %i293 = add nsw i64 %i292, %i291
  store i64 %i293, ptr @quantum_memman.mem, align 8
  %i294 = load i64, ptr @quantum_memman.max, align 8
  %i295 = icmp sgt i64 %i293, %i294
  br i1 %i295, label %bb296, label %bb297

bb296:                                            ; preds = %bb289
  store i64 %i293, ptr @quantum_memman.max, align 8
  br label %bb297

bb297:                                            ; preds = %bb296, %bb289
  %i298 = icmp sgt i32 %i278, 0
  br i1 %i298, label %bb299, label %bb414

bb299:                                            ; preds = %bb297
  %i300 = and i32 %i278, 7
  %i301 = icmp ult i32 %i278, 8
  br i1 %i301, label %bb357, label %bb302

bb302:                                            ; preds = %bb299
  %i303 = and i32 %i278, -8
  br label %bb304

bb304:                                            ; preds = %bb304, %bb302
  %i305 = phi i32 [ 0, %bb302 ], [ %i354, %bb304 ]
  %i306 = phi i32 [ 0, %bb302 ], [ %i355, %bb304 ]
  %i307 = load ptr, ptr %i279, align 8
  %i308 = load i32, ptr %i39, align 4
  %i309 = add nsw i32 %i308, %i305
  %i310 = sext i32 %i309 to i64
  %i311 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i307, i64 %i310
  %i312 = or i32 %i305, 1
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i311, i8 0, i64 16, i1 false)
  %i313 = load ptr, ptr %i279, align 8
  %i314 = load i32, ptr %i39, align 4
  %i315 = add nsw i32 %i314, %i312
  %i316 = sext i32 %i315 to i64
  %i317 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i313, i64 %i316
  %i318 = or i32 %i305, 2
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i317, i8 0, i64 16, i1 false)
  %i319 = load ptr, ptr %i279, align 8
  %i320 = load i32, ptr %i39, align 4
  %i321 = add nsw i32 %i320, %i318
  %i322 = sext i32 %i321 to i64
  %i323 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i319, i64 %i322
  %i324 = or i32 %i305, 3
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i323, i8 0, i64 16, i1 false)
  %i325 = load ptr, ptr %i279, align 8
  %i326 = load i32, ptr %i39, align 4
  %i327 = add nsw i32 %i326, %i324
  %i328 = sext i32 %i327 to i64
  %i329 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i325, i64 %i328
  %i330 = or i32 %i305, 4
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i329, i8 0, i64 16, i1 false)
  %i331 = load ptr, ptr %i279, align 8
  %i332 = load i32, ptr %i39, align 4
  %i333 = add nsw i32 %i332, %i330
  %i334 = sext i32 %i333 to i64
  %i335 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i331, i64 %i334
  %i336 = or i32 %i305, 5
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i335, i8 0, i64 16, i1 false)
  %i337 = load ptr, ptr %i279, align 8
  %i338 = load i32, ptr %i39, align 4
  %i339 = add nsw i32 %i338, %i336
  %i340 = sext i32 %i339 to i64
  %i341 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i337, i64 %i340
  %i342 = or i32 %i305, 6
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i341, i8 0, i64 16, i1 false)
  %i343 = load ptr, ptr %i279, align 8
  %i344 = load i32, ptr %i39, align 4
  %i345 = add nsw i32 %i344, %i342
  %i346 = sext i32 %i345 to i64
  %i347 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i343, i64 %i346
  %i348 = or i32 %i305, 7
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i347, i8 0, i64 16, i1 false)
  %i349 = load ptr, ptr %i279, align 8
  %i350 = load i32, ptr %i39, align 4
  %i351 = add nsw i32 %i350, %i348
  %i352 = sext i32 %i351 to i64
  %i353 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i349, i64 %i352
  %i354 = add nuw nsw i32 %i305, 8
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i353, i8 0, i64 16, i1 false)
  %i355 = add i32 %i306, 8
  %i356 = icmp eq i32 %i355, %i303
  br i1 %i356, label %bb357, label %bb304

bb357:                                            ; preds = %bb304, %bb299
  %i358 = phi i32 [ 0, %bb299 ], [ %i354, %bb304 ]
  %i359 = icmp eq i32 %i300, 0
  br i1 %i359, label %bb414, label %bb360

bb360:                                            ; preds = %bb357
  %i361 = load ptr, ptr %i279, align 8
  %i362 = load i32, ptr %i39, align 4
  %i363 = add nsw i32 %i362, %i358
  %i364 = sext i32 %i363 to i64
  %i365 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i361, i64 %i364
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i365, i8 0, i64 16, i1 false)
  %i366 = icmp eq i32 %i300, 1
  br i1 %i366, label %bb414, label %bb367

bb367:                                            ; preds = %bb360
  %i368 = add nuw nsw i32 %i358, 1
  %i369 = load ptr, ptr %i279, align 8
  %i370 = load i32, ptr %i39, align 4
  %i371 = add nsw i32 %i370, %i368
  %i372 = sext i32 %i371 to i64
  %i373 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i369, i64 %i372
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i373, i8 0, i64 16, i1 false)
  %i374 = icmp eq i32 %i300, 2
  br i1 %i374, label %bb414, label %bb375

bb375:                                            ; preds = %bb367
  %i376 = add nuw nsw i32 %i358, 2
  %i377 = load ptr, ptr %i279, align 8
  %i378 = load i32, ptr %i39, align 4
  %i379 = add nsw i32 %i378, %i376
  %i380 = sext i32 %i379 to i64
  %i381 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i377, i64 %i380
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i381, i8 0, i64 16, i1 false)
  %i382 = icmp eq i32 %i300, 3
  br i1 %i382, label %bb414, label %bb383

bb383:                                            ; preds = %bb375
  %i384 = add nuw nsw i32 %i358, 3
  %i385 = load ptr, ptr %i279, align 8
  %i386 = load i32, ptr %i39, align 4
  %i387 = add nsw i32 %i386, %i384
  %i388 = sext i32 %i387 to i64
  %i389 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i385, i64 %i388
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i389, i8 0, i64 16, i1 false)
  %i390 = icmp eq i32 %i300, 4
  br i1 %i390, label %bb414, label %bb391

bb391:                                            ; preds = %bb383
  %i392 = add nuw nsw i32 %i358, 4
  %i393 = load ptr, ptr %i279, align 8
  %i394 = load i32, ptr %i39, align 4
  %i395 = add nsw i32 %i394, %i392
  %i396 = sext i32 %i395 to i64
  %i397 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i393, i64 %i396
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i397, i8 0, i64 16, i1 false)
  %i398 = icmp eq i32 %i300, 5
  br i1 %i398, label %bb414, label %bb399

bb399:                                            ; preds = %bb391
  %i400 = add nuw nsw i32 %i358, 5
  %i401 = load ptr, ptr %i279, align 8
  %i402 = load i32, ptr %i39, align 4
  %i403 = add nsw i32 %i402, %i400
  %i404 = sext i32 %i403 to i64
  %i405 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i401, i64 %i404
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i405, i8 0, i64 16, i1 false)
  %i406 = icmp eq i32 %i300, 6
  br i1 %i406, label %bb414, label %bb407

bb407:                                            ; preds = %bb399
  %i408 = add nuw nsw i32 %i358, 6
  %i409 = load ptr, ptr %i279, align 8
  %i410 = load i32, ptr %i39, align 4
  %i411 = add nsw i32 %i410, %i408
  %i412 = sext i32 %i411 to i64
  %i413 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i409, i64 %i412
  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %i413, i8 0, i64 16, i1 false)
  br label %bb414

bb414:                                            ; preds = %bb407, %bb399, %bb391, %bb383, %bb375, %bb367, %bb360, %bb357, %bb297
  %i415 = load i32, ptr %i39, align 4
  %i416 = add nsw i32 %i415, %i278
  %i417 = sext i32 %i416 to i64
  %i418 = tail call noalias ptr @calloc(i64 noundef %i417, i64 noundef 1)
  %i419 = icmp eq ptr %i418, null
  br i1 %i419, label %bb420, label %bb422

bb420:                                            ; preds = %bb414
  %i421 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.3, i64 noundef %i417)
  tail call void @exit(i32 noundef signext 1)
  unreachable

bb422:                                            ; preds = %bb414
  %i423 = sext i32 %i415 to i64
  %i424 = add nsw i64 %i423, %i290
  %i425 = load i64, ptr @quantum_memman.mem, align 8
  %i426 = add nsw i64 %i425, %i424
  store i64 %i426, ptr @quantum_memman.mem, align 8
  %i427 = load i64, ptr @quantum_memman.max, align 8
  %i428 = icmp sgt i64 %i426, %i427
  br i1 %i428, label %bb429, label %bb430

bb429:                                            ; preds = %bb422
  store i64 %i426, ptr @quantum_memman.max, align 8
  br label %bb430

bb430:                                            ; preds = %bb429, %bb422
  %i431 = load i32, ptr %arg1, align 8
  %i432 = zext i32 %i431 to i64
  %i433 = shl nuw i64 1, %i432
  %i434 = uitofp i64 %i433 to double
  %i435 = fdiv fast double 0x3EB0C6F7A0B5ED8D, %i434
  %i436 = fptrunc double %i435 to float
  %i437 = load i32, ptr %i39, align 4
  %i438 = icmp sgt i32 %i437, 0
  br i1 %i438, label %bb439, label %bb655

bb439:                                            ; preds = %bb430
  %i440 = zext i32 %arg to i64
  %i441 = shl nuw i64 1, %i440
  %i442 = getelementptr inbounds i8, ptr %arg1, i64 24
  %i443 = and i64 %i441, 4294967295
  %i444 = getelementptr inbounds { float, float }, ptr %i21, i64 0, i32 1
  %i445 = getelementptr inbounds { float, float }, ptr %i21, i64 1
  %i446 = getelementptr inbounds { float, float }, ptr %i21, i64 1, i32 1
  %i447 = getelementptr inbounds { float, float }, ptr %i21, i64 2
  %i448 = getelementptr inbounds { float, float }, ptr %i21, i64 2, i32 1
  %i449 = getelementptr inbounds { float, float }, ptr %i21, i64 3
  %i450 = getelementptr inbounds { float, float }, ptr %i21, i64 3, i32 1
  br label %bb451

bb451:                                            ; preds = %bb650, %bb439
  %i452 = phi i8 [ 0, %bb439 ], [ %i652, %bb650 ]
  %i453 = phi i64 [ 0, %bb439 ], [ %i646, %bb650 ]
  %i454 = phi i32 [ %i437, %bb439 ], [ %i645, %bb650 ]
  %i455 = icmp eq i8 %i452, 0
  br i1 %i455, label %bb456, label %bb644

bb456:                                            ; preds = %bb451
  %i457 = load ptr, ptr %i279, align 8
  %i458 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i457, i64 %i453, i32 1
  %i459 = load i64, ptr %i458, align 8
  %i460 = xor i64 %i459, %i441
  %i461 = load i32, ptr %i29, align 8
  %i462 = load ptr, ptr %i442, align 8
  %i463 = lshr i64 %i460, 32
  %i464 = xor i64 %i463, %i460
  %i465 = trunc i64 %i464 to i32
  %i466 = mul i32 %i465, -1640562687
  %i467 = sub nsw i32 32, %i461
  %i468 = lshr i32 %i466, %i467
  %i469 = sext i32 %i468 to i64
  %i470 = getelementptr inbounds i32, ptr %i462, i64 %i469
  %i471 = load i32, ptr %i470, align 4
  %i472 = icmp eq i32 %i471, 0
  br i1 %i472, label %bb491, label %bb473

bb473:                                            ; preds = %bb456
  %i474 = shl nuw i32 1, %i461
  br label %bb475

bb475:                                            ; preds = %bb483, %bb473
  %i476 = phi i32 [ %i471, %bb473 ], [ %i489, %bb483 ]
  %i477 = phi i32 [ %i468, %bb473 ], [ %i486, %bb483 ]
  %i478 = add nsw i32 %i476, -1
  %i479 = sext i32 %i478 to i64
  %i480 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i457, i64 %i479, i32 1
  %i481 = load i64, ptr %i480, align 8
  %i482 = icmp eq i64 %i481, %i460
  br i1 %i482, label %bb496, label %bb483

bb483:                                            ; preds = %bb475
  %i484 = add nsw i32 %i477, 1
  %i485 = icmp eq i32 %i484, %i474
  %i486 = select i1 %i485, i32 0, i32 %i484
  %i487 = sext i32 %i486 to i64
  %i488 = getelementptr inbounds i32, ptr %i462, i64 %i487
  %i489 = load i32, ptr %i488, align 4
  %i490 = icmp eq i32 %i489, 0
  br i1 %i490, label %bb491, label %bb475

bb491:                                            ; preds = %bb483, %bb456
  %i492 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i457, i64 %i453
  %i493 = load float, ptr %i492, align 8
  %i494 = getelementptr inbounds { float, float }, ptr %i492, i64 0, i32 1
  %i495 = load float, ptr %i494, align 4
  br label %bb508

bb496:                                            ; preds = %bb475
  %i497 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i457, i64 %i453
  %i498 = load float, ptr %i497, align 8
  %i499 = getelementptr inbounds { float, float }, ptr %i497, i64 0, i32 1
  %i500 = load float, ptr %i499, align 4
  %i501 = icmp sgt i32 %i476, 0
  br i1 %i501, label %bb502, label %bb508

bb502:                                            ; preds = %bb496
  %i503 = zext i32 %i478 to i64
  %i504 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i457, i64 %i503
  %i505 = load float, ptr %i504, align 8
  %i506 = getelementptr inbounds { float, float }, ptr %i504, i64 0, i32 1
  %i507 = load float, ptr %i506, align 4
  br label %bb508

bb508:                                            ; preds = %bb502, %bb496, %bb491
  %i509 = phi i1 [ true, %bb502 ], [ false, %bb496 ], [ false, %bb491 ]
  %i510 = phi float [ %i500, %bb502 ], [ %i500, %bb496 ], [ %i495, %bb491 ]
  %i511 = phi ptr [ %i499, %bb502 ], [ %i499, %bb496 ], [ %i494, %bb491 ]
  %i512 = phi float [ %i498, %bb502 ], [ %i498, %bb496 ], [ %i493, %bb491 ]
  %i513 = phi ptr [ %i497, %bb502 ], [ %i497, %bb496 ], [ %i492, %bb491 ]
  %i514 = phi i32 [ %i478, %bb502 ], [ %i478, %bb496 ], [ -1, %bb491 ]
  %i515 = phi float [ %i505, %bb502 ], [ 0.000000e+00, %bb496 ], [ 0.000000e+00, %bb491 ]
  %i516 = phi float [ %i507, %bb502 ], [ 0.000000e+00, %bb496 ], [ 0.000000e+00, %bb491 ]
  %i517 = and i64 %i443, %i459
  %i518 = icmp ne i64 %i517, 0
  br i1 %i518, label %bb519, label %bb538

bb519:                                            ; preds = %bb508
  %i520 = load float, ptr %i447, align 4
  %i521 = load float, ptr %i448, align 4
  %i522 = fmul fast float %i520, %i515
  %i523 = fmul fast float %i520, %i516
  %i524 = fmul fast float %i521, %i515
  %i525 = fmul fast float %i521, %i516
  %i526 = load float, ptr %i449, align 4
  %i527 = fmul fast float %i526, %i510
  %i528 = load float, ptr %i450, align 4
  %i529 = fmul fast float %i528, %i512
  %i530 = fmul fast float %i526, %i512
  %i531 = fmul fast float %i528, %i510
  %i532 = fadd fast float %i531, %i525
  %i533 = fadd fast float %i530, %i522
  %i534 = fsub fast float %i533, %i532
  %i535 = fadd fast float %i524, %i523
  %i536 = fadd fast float %i535, %i527
  %i537 = fadd fast float %i536, %i529
  store float %i534, ptr %i513, align 8
  store float %i537, ptr %i511, align 4
  br i1 %i509, label %bb557, label %bb603

bb538:                                            ; preds = %bb508
  %i539 = load float, ptr %i21, align 4
  %i540 = load float, ptr %i444, align 4
  %i541 = fmul fast float %i539, %i512
  %i542 = fmul fast float %i539, %i510
  %i543 = fmul fast float %i540, %i512
  %i544 = fmul fast float %i540, %i510
  %i545 = load float, ptr %i445, align 4
  %i546 = fmul fast float %i545, %i516
  %i547 = load float, ptr %i446, align 4
  %i548 = fmul fast float %i547, %i515
  %i549 = fmul fast float %i545, %i515
  %i550 = fmul fast float %i547, %i516
  %i551 = fadd fast float %i550, %i544
  %i552 = fadd fast float %i549, %i541
  %i553 = fsub fast float %i552, %i551
  %i554 = fadd fast float %i543, %i542
  %i555 = fadd fast float %i554, %i546
  %i556 = fadd fast float %i555, %i548
  store float %i553, ptr %i513, align 8
  store float %i556, ptr %i511, align 4
  br i1 %i509, label %bb580, label %bb603

bb557:                                            ; preds = %bb519
  %i558 = load float, ptr %i21, align 4
  %i559 = load float, ptr %i444, align 4
  %i560 = fmul fast float %i558, %i515
  %i561 = fmul fast float %i558, %i516
  %i562 = fmul fast float %i559, %i515
  %i563 = fmul fast float %i559, %i516
  %i564 = load float, ptr %i445, align 4
  %i565 = fmul fast float %i564, %i510
  %i566 = load float, ptr %i446, align 4
  %i567 = fmul fast float %i566, %i512
  %i568 = fmul fast float %i564, %i512
  %i569 = fmul fast float %i566, %i510
  %i570 = fadd fast float %i569, %i563
  %i571 = fadd fast float %i568, %i560
  %i572 = fsub fast float %i571, %i570
  %i573 = fadd fast float %i562, %i561
  %i574 = fadd fast float %i573, %i565
  %i575 = fadd fast float %i574, %i567
  %i576 = load ptr, ptr %i279, align 8
  %i577 = zext i32 %i514 to i64
  %i578 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i576, i64 %i577
  %i579 = getelementptr inbounds { float, float }, ptr %i578, i64 0, i32 1
  store float %i572, ptr %i578, align 8
  store float %i575, ptr %i579, align 4
  br label %bb641

bb580:                                            ; preds = %bb538
  %i581 = load float, ptr %i447, align 4
  %i582 = load float, ptr %i448, align 4
  %i583 = fmul fast float %i581, %i512
  %i584 = fmul fast float %i581, %i510
  %i585 = fmul fast float %i582, %i512
  %i586 = fmul fast float %i582, %i510
  %i587 = load float, ptr %i449, align 4
  %i588 = fmul fast float %i587, %i516
  %i589 = load float, ptr %i450, align 4
  %i590 = fmul fast float %i589, %i515
  %i591 = fmul fast float %i587, %i515
  %i592 = fmul fast float %i589, %i516
  %i593 = fadd fast float %i592, %i586
  %i594 = fadd fast float %i591, %i583
  %i595 = fsub fast float %i594, %i593
  %i596 = fadd fast float %i585, %i584
  %i597 = fadd fast float %i596, %i588
  %i598 = fadd fast float %i597, %i590
  %i599 = load ptr, ptr %i279, align 8
  %i600 = zext i32 %i514 to i64
  %i601 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i599, i64 %i600
  %i602 = getelementptr inbounds { float, float }, ptr %i601, i64 0, i32 1
  store float %i595, ptr %i601, align 8
  store float %i598, ptr %i602, align 4
  br label %bb641

bb603:                                            ; preds = %bb538, %bb519
  %i604 = load float, ptr %i445, align 4
  %i605 = load float, ptr %i446, align 4
  %i606 = fmul fast float %i604, %i604
  %i607 = fmul fast float %i605, %i605
  %i608 = fadd fast float %i607, %i606
  %i609 = fpext float %i608 to double
  %i610 = fcmp fast olt double %i609, 1.000000e-09
  %i611 = and i1 %i518, %i610
  br i1 %i611, label %bb653, label %bb612

bb612:                                            ; preds = %bb603
  %i613 = load float, ptr %i447, align 4
  %i614 = load float, ptr %i448, align 4
  %i615 = fmul fast float %i613, %i613
  %i616 = fmul fast float %i614, %i614
  %i617 = fadd fast float %i616, %i615
  %i618 = fpext float %i617 to double
  %i619 = fcmp fast uge double %i618, 1.000000e-09
  %i620 = or i1 %i518, %i619
  br i1 %i620, label %bb621, label %bb653

bb621:                                            ; preds = %bb612
  %i622 = load ptr, ptr %i279, align 8
  %i623 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i622, i64 %i453, i32 1
  %i624 = load i64, ptr %i623, align 8
  %i625 = xor i64 %i624, %i441
  %i626 = sext i32 %i454 to i64
  %i627 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i622, i64 %i626, i32 1
  store i64 %i625, ptr %i627, align 8
  %i628 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i622, i64 %i626
  %i629 = getelementptr inbounds { float, float }, ptr %i628, i64 0, i32 1
  %i630 = select i1 %i518, ptr %i445, ptr %i447
  %i631 = select i1 %i518, ptr %i446, ptr %i448
  %i632 = load float, ptr %i630, align 4
  %i633 = fmul fast float %i632, %i510
  %i634 = load float, ptr %i631, align 4
  %i635 = fmul fast float %i634, %i512
  %i636 = fadd fast float %i635, %i633
  %i637 = fmul fast float %i632, %i512
  %i638 = fmul fast float %i634, %i510
  %i639 = fsub fast float %i637, %i638
  store float %i639, ptr %i628, align 8
  store float %i636, ptr %i629, align 4
  %i640 = add nsw i32 %i454, 1
  br label %bb644

bb641:                                            ; preds = %bb580, %bb557
  %i642 = phi i64 [ %i577, %bb557 ], [ %i600, %bb580 ]
  %i643 = getelementptr inbounds i8, ptr %i418, i64 %i642
  store i8 1, ptr %i643, align 1
  br label %bb644

bb644:                                            ; preds = %bb641, %bb621, %bb451
  %i645 = phi i32 [ %i454, %bb451 ], [ %i454, %bb641 ], [ %i640, %bb621 ]
  %i646 = add nuw nsw i64 %i453, 1
  %i647 = load i32, ptr %i39, align 4
  %i648 = sext i32 %i647 to i64
  %i649 = icmp slt i64 %i646, %i648
  br i1 %i649, label %bb650, label %bb653

bb650:                                            ; preds = %bb644
  %i651 = getelementptr inbounds i8, ptr %i418, i64 %i646
  %i652 = load i8, ptr %i651, align 1
  br label %bb451

bb653:                                            ; preds = %bb644, %bb612, %bb603
  %i654 = load i32, ptr %i39, align 4
  br label %bb655

bb655:                                            ; preds = %bb653, %bb430
  %i656 = phi i32 [ %i654, %bb653 ], [ %i437, %bb430 ]
  %i657 = add nsw i32 %i656, %i278
  store i32 %i657, ptr %i39, align 4
  tail call void @free(ptr noundef %i418)
  %i658 = sub nsw i32 0, %i657
  %i659 = sext i32 %i658 to i64
  %i660 = load i64, ptr @quantum_memman.mem, align 8
  %i661 = add nsw i64 %i660, %i659
  store i64 %i661, ptr @quantum_memman.mem, align 8
  %i662 = load i64, ptr @quantum_memman.max, align 8
  %i663 = icmp sgt i64 %i661, %i662
  br i1 %i663, label %bb664, label %bb665

bb664:                                            ; preds = %bb655
  store i64 %i661, ptr @quantum_memman.max, align 8
  br label %bb665

bb665:                                            ; preds = %bb664, %bb655
  %i666 = load i32, ptr %i39, align 4
  %i667 = icmp sgt i32 %i666, 0
  br i1 %i667, label %bb668, label %bb726

bb668:                                            ; preds = %bb697, %bb665
  %i669 = phi i32 [ %i698, %bb697 ], [ %i666, %bb665 ]
  %i670 = phi i64 [ %i701, %bb697 ], [ 0, %bb665 ]
  %i671 = phi i32 [ %i700, %bb697 ], [ 0, %bb665 ]
  %i672 = phi i32 [ %i699, %bb697 ], [ 0, %bb665 ]
  %i673 = load ptr, ptr %i279, align 8
  %i674 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i673, i64 %i670
  %i675 = load float, ptr %i674, align 8
  %i676 = getelementptr inbounds { float, float }, ptr %i674, i64 0, i32 1
  %i677 = load float, ptr %i676, align 4
  %i678 = fmul fast float %i675, %i675
  %i679 = fmul fast float %i677, %i677
  %i680 = fadd fast float %i679, %i678
  %i681 = fcmp fast olt float %i680, %i436
  br i1 %i681, label %bb682, label %bb685

bb682:                                            ; preds = %bb668
  %i683 = add nsw i32 %i671, 1
  %i684 = add nsw i32 %i672, 1
  br label %bb697

bb685:                                            ; preds = %bb668
  %i686 = icmp eq i32 %i671, 0
  br i1 %i686, label %bb697, label %bb687

bb687:                                            ; preds = %bb685
  %i688 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i673, i64 %i670, i32 1
  %i689 = load i64, ptr %i688, align 8
  %i690 = trunc i64 %i670 to i32
  %i691 = sub nsw i32 %i690, %i671
  %i692 = sext i32 %i691 to i64
  %i693 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i673, i64 %i692, i32 1
  store i64 %i689, ptr %i693, align 8
  %i694 = getelementptr inbounds %struct.quantum_reg_node_struct, ptr %i673, i64 %i692
  %i695 = getelementptr inbounds { float, float }, ptr %i694, i64 0, i32 1
  store float %i675, ptr %i694, align 8
  store float %i677, ptr %i695, align 4
  %i696 = load i32, ptr %i39, align 4
  br label %bb697

bb697:                                            ; preds = %bb687, %bb685, %bb682
  %i698 = phi i32 [ %i669, %bb682 ], [ %i696, %bb687 ], [ %i669, %bb685 ]
  %i699 = phi i32 [ %i684, %bb682 ], [ %i672, %bb687 ], [ %i672, %bb685 ]
  %i700 = phi i32 [ %i683, %bb682 ], [ %i671, %bb687 ], [ 0, %bb685 ]
  %i701 = add nuw nsw i64 %i670, 1
  %i702 = sext i32 %i698 to i64
  %i703 = icmp slt i64 %i701, %i702
  br i1 %i703, label %bb668, label %bb704

bb704:                                            ; preds = %bb697
  %i705 = icmp eq i32 %i699, 0
  br i1 %i705, label %bb726, label %bb706

bb706:                                            ; preds = %bb704
  %i707 = sub nsw i32 %i698, %i699
  store i32 %i707, ptr %i39, align 4
  %i708 = load ptr, ptr %i279, align 8
  %i709 = sext i32 %i707 to i64
  %i710 = shl nsw i64 %i709, 4
  %i711 = tail call ptr @realloc(ptr noundef %i708, i64 noundef %i710)
  store ptr %i711, ptr %i279, align 8
  %i712 = icmp eq ptr %i711, null
  br i1 %i712, label %bb713, label %bb717

bb713:                                            ; preds = %bb706
  %i714 = load i32, ptr %i39, align 4
  %i715 = add nsw i32 %i714, %i278
  %i716 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.1.23, i32 noundef signext %i715)
  tail call void @exit(i32 noundef signext 1)
  unreachable

bb717:                                            ; preds = %bb706
  %i718 = sub nsw i32 0, %i699
  %i719 = sext i32 %i718 to i64
  %i720 = shl nsw i64 %i719, 4
  %i721 = load i64, ptr @quantum_memman.mem, align 8
  %i722 = add nsw i64 %i721, %i720
  store i64 %i722, ptr @quantum_memman.mem, align 8
  %i723 = load i64, ptr @quantum_memman.max, align 8
  %i724 = icmp sgt i64 %i722, %i723
  br i1 %i724, label %bb725, label %bb726

bb725:                                            ; preds = %bb717
  store i64 %i722, ptr @quantum_memman.max, align 8
  br label %bb726

bb726:                                            ; preds = %bb725, %bb717, %bb704, %bb665
  %i727 = load i32, ptr @quantum_gate_counter.counter, align 4
  %i728 = add nsw i32 %i727, 1
  store i32 %i728, ptr @quantum_gate_counter.counter, align 4
  %i729 = getelementptr inbounds %struct.quantum_matrix_struct, ptr %i, i64 0, i32 2
  %i730 = load ptr, ptr %i729, align 8
  tail call void @free(ptr noundef %i730)
  %i731 = getelementptr inbounds %struct.quantum_matrix_struct, ptr %i, i64 0, i32 1
  %i732 = load i32, ptr %i731, align 4
  %i733 = sext i32 %i732 to i64
  %i734 = mul nsw i64 %i733, -8
  %i735 = load i32, ptr %i, align 8
  %i736 = sext i32 %i735 to i64
  %i737 = mul i64 %i734, %i736
  %i738 = load i64, ptr @quantum_memman.mem, align 8
  %i739 = add nsw i64 %i737, %i738
  store i64 %i739, ptr @quantum_memman.mem, align 8
  %i740 = load i64, ptr @quantum_memman.max, align 8
  %i741 = icmp sgt i64 %i739, %i740
  br i1 %i741, label %bb742, label %bb743

bb742:                                            ; preds = %bb726
  store i64 %i739, ptr @quantum_memman.max, align 8
  br label %bb743

bb743:                                            ; preds = %bb742, %bb726
  store ptr null, ptr %i729, align 8
  br label %bb744

bb744:                                            ; preds = %bb743, %entry
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %i)
  ret void
}
