; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=sroa -S | FileCheck %s

%struct.vfloat4 = type { <4 x float> }
%struct.vmask4 = type { <4 x i32> }

define <4 x i32> @foo([2 x i64] %cond.coerce) {
; CHECK-LABEL: define <4 x i32> @foo(
; CHECK-SAME: [2 x i64] [[COND_COERCE:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[COND_COERCE_FCA_0_EXTRACT:%.*]] = extractvalue [2 x i64] [[COND_COERCE]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64 [[COND_COERCE_FCA_0_EXTRACT]] to <2 x i32>
; CHECK-NEXT:    [[COND_SROA_0_0_VEC_EXPAND:%.*]] = shufflevector <2 x i32> [[TMP0]], <2 x i32> poison, <4 x i32> <i32 0, i32 1, i32 poison, i32 poison>
; CHECK-NEXT:    [[COND_SROA_0_0_VECBLEND:%.*]] = select <4 x i1> <i1 true, i1 true, i1 false, i1 false>, <4 x i32> [[COND_SROA_0_0_VEC_EXPAND]], <4 x i32> undef
; CHECK-NEXT:    [[COND_COERCE_FCA_1_EXTRACT:%.*]] = extractvalue [2 x i64] [[COND_COERCE]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[COND_COERCE_FCA_1_EXTRACT]] to <2 x i32>
; CHECK-NEXT:    [[COND_SROA_0_8_VEC_EXPAND:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> poison, <4 x i32> <i32 poison, i32 poison, i32 0, i32 1>
; CHECK-NEXT:    [[COND_SROA_0_8_VECBLEND:%.*]] = select <4 x i1> <i1 false, i1 false, i1 true, i1 true>, <4 x i32> [[COND_SROA_0_8_VEC_EXPAND]], <4 x i32> [[COND_SROA_0_0_VECBLEND]]
; CHECK-NEXT:    ret <4 x i32> [[COND_SROA_0_8_VECBLEND]]
;
entry:
  %cond = alloca %struct.vmask4, align 8
  %coerce.dive2 = getelementptr inbounds %struct.vmask4, ptr %cond, i32 0, i32 0
  store [2 x i64] %cond.coerce, ptr %coerce.dive2, align 8
  %m5 = getelementptr inbounds %struct.vmask4, ptr %cond, i32 0, i32 0
  %2 = load <4 x i32>, ptr %m5, align 8
  ret <4 x i32> %2
}
