; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=gvn -enable-load-pre -enable-pre -S < %s | FileCheck %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

%"union.xalanc_1_10::DoubleSupport::NumberUnion" = type { double }
%"struct.xalanc_1_10::NodeSorter::VectorEntry" = type <{ ptr, i32, [4 x i8] }>
%"struct.__gnu_cxx::__ops::_Val_comp_iter" = type { %"struct.xalanc_1_10::NodeSorter::NodeSortKeyCompare" }
%"struct.xalanc_1_10::NodeSorter::NodeSortKeyCompare" = type { ptr, ptr, ptr, ptr }
%"class.xalanc_1_10::NodeSortKey" = type { ptr, ptr, i8, i8, i32, ptr, ptr }

$_ZSt16__insertion_sortIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops15_Iter_comp_iterINS1_18NodeSortKeyCompareEEEEvT_S9_T0_ = comdat any
@_ZN11xalanc_1_1013DoubleSupport5s_NaNE = external global %"union.xalanc_1_10::DoubleSupport::NumberUnion", align 8

declare noundef zeroext i1 @_ZN11xalanc_1_1013DoubleSupport8lessThanEdd(double noundef nofpclass(nan inf), double noundef nofpclass(nan inf))
declare noundef nofpclass(nan inf) double @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getNumberResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr nocapture noundef nonnull readonly align 8 dereferenceable(32), ptr nocapture noundef nonnull readonly align 8 dereferenceable(40), i32 noundef signext, ptr nocapture noundef nonnull readonly align 8 dereferenceable(12)) align 2
declare noundef nonnull align 8 dereferenceable(36) ptr @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getStringResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr nocapture noundef nonnull readonly align 8 dereferenceable(32), ptr nocapture noundef nonnull readonly align 8 dereferenceable(40), i32 noundef signext, ptr nocapture noundef nonnull readonly align 8 dereferenceable(12)) align 2
declare noundef signext i32 @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j(ptr nocapture noundef nonnull readonly align 8 dereferenceable(32), ptr nocapture noundef nonnull readonly align 8 dereferenceable(12), ptr nocapture noundef nonnull readonly align 8 dereferenceable(12), i32 noundef signext) align 2
declare noundef zeroext i1 @_ZN11xalanc_1_1013DoubleSupport11greaterThanEdd(double noundef nofpclass(nan inf), double noundef nofpclass(nan inf))
declare void @llvm.memmove.p0.p0.i64(ptr nocapture writeonly, ptr nocapture readonly, i64, i1 immarg)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)

; Do not pre a load and two geps in if.else
; We need the inner and outer loops plus data flow to stage this.

define linkonce_odr dso_local void @_ZSt16__insertion_sortIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops15_Iter_comp_iterINS1_18NodeSortKeyCompareEEEEvT_S9_T0_(ptr noundef %__first, ptr noundef %__last, ptr noundef %__comp) comdat {
; CHECK-LABEL: @_ZSt16__insertion_sortIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops15_Iter_comp_iterINS1_18NodeSortKeyCompareEEEEvT_S9_T0_(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[__VAL_I:%.*]] = alloca %"struct.xalanc_1_10::NodeSorter::VectorEntry", align 8
; CHECK-NEXT:    [[__VAL:%.*]] = alloca %"struct.xalanc_1_10::NodeSorter::VectorEntry", align 8
; CHECK-NEXT:    [[AGG_TMP:%.*]] = alloca %"struct.__gnu_cxx::__ops::_Val_comp_iter", align 8
; CHECK-NEXT:    [[AGG_TMP5_SROA_0:%.*]] = alloca %"struct.xalanc_1_10::NodeSorter::NodeSortKeyCompare", align 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[__FIRST:%.*]], [[__LAST:%.*]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_END:%.*]], label [[FOR_COND_PREHEADER:%.*]]
; CHECK:       for.cond.preheader:
; CHECK-NEXT:    [[__I_026:%.*]] = getelementptr inbounds i8, ptr [[__FIRST]], i64 16
; CHECK-NEXT:    [[CMP1_NOT27:%.*]] = icmp eq ptr [[__I_026]], [[__LAST]]
; CHECK-NEXT:    br i1 [[CMP1_NOT27]], label [[FOR_END]], label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[SUB_PTR_RHS_CAST_I_I_I_I_I:%.*]] = ptrtoint ptr [[__FIRST]] to i64
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[__I_029:%.*]] = phi ptr [ [[__I_026]], [[FOR_BODY_LR_PH]] ], [ [[__I_0:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[__FIRST_PN28:%.*]] = phi ptr [ [[__FIRST]], [[FOR_BODY_LR_PH]] ], [ [[__I_029]], [[FOR_INC]] ]
; CHECK-NEXT:    [[CALL_I_I:%.*]] = tail call noundef signext i32 @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j(ptr noundef nonnull align 8 dereferenceable(32) [[__COMP:%.*]], ptr noundef nonnull align 8 dereferenceable(12) [[__I_029]], ptr noundef nonnull align 8 dereferenceable(12) [[__FIRST]], i32 noundef signext 0)
; CHECK-NEXT:    [[CMP_I_I:%.*]] = icmp slt i32 [[CALL_I_I]], 0
; CHECK-NEXT:    br i1 [[CMP_I_I]], label [[IF_THEN2:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then2:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[__VAL]])
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) [[__VAL]], ptr noundef nonnull align 8 dereferenceable(16) [[__I_029]], i64 16, i1 false), !tbaa [[TBAA0:![0-9]+]], !tbaa.struct [[TBAA_STRUCT7:![0-9]+]]
; CHECK-NEXT:    [[SUB_PTR_LHS_CAST_I_I_I_I_I:%.*]] = ptrtoint ptr [[__I_029]] to i64
; CHECK-NEXT:    [[SUB_PTR_SUB_I_I_I_I_I:%.*]] = sub i64 [[SUB_PTR_LHS_CAST_I_I_I_I_I]], [[SUB_PTR_RHS_CAST_I_I_I_I_I]]
; CHECK-NEXT:    [[SUB_PTR_DIV_I_I_I_I_I:%.*]] = ashr exact i64 [[SUB_PTR_SUB_I_I_I_I_I]], 4
; CHECK-NEXT:    [[CMP_I_I_I_I_I:%.*]] = icmp sgt i64 [[SUB_PTR_DIV_I_I_I_I_I]], 1
; CHECK-NEXT:    br i1 [[CMP_I_I_I_I_I]], label [[IF_THEN_I_I_I_I_I:%.*]], label [[IF_ELSE_I_I_I_I_I:%.*]], !prof [[PROF10:![0-9]+]]
; CHECK:       if.then.i.i.i.i.i:
; CHECK-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds i8, ptr [[__FIRST_PN28]], i64 32
; CHECK-NEXT:    [[IDX_NEG_I_I_I_I_I:%.*]] = sub nsw i64 0, [[SUB_PTR_DIV_I_I_I_I_I]]
; CHECK-NEXT:    [[ADD_PTR_I_I_I_I_I:%.*]] = getelementptr inbounds %"struct.xalanc_1_10::NodeSorter::VectorEntry", ptr [[ADD_PTR3]], i64 [[IDX_NEG_I_I_I_I_I]]
; CHECK-NEXT:    tail call void @llvm.memmove.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(1) [[ADD_PTR_I_I_I_I_I]], ptr noundef nonnull align 8 dereferenceable(1) [[__FIRST]], i64 [[SUB_PTR_SUB_I_I_I_I_I]], i1 false)
; CHECK-NEXT:    br label [[_ZST13MOVE_BACKWARDIPN11XALANC_1_1010NODESORTER11VECTORENTRYES3_ET0_T_S5_S4__EXIT:%.*]]
; CHECK:       if.else.i.i.i.i.i:
; CHECK-NEXT:    [[CMP1_I_I_I_I_I:%.*]] = icmp eq i64 [[SUB_PTR_SUB_I_I_I_I_I]], 16
; CHECK-NEXT:    br i1 [[CMP1_I_I_I_I_I]], label [[IF_THEN2_I_I_I_I_I:%.*]], label [[_ZST13MOVE_BACKWARDIPN11XALANC_1_1010NODESORTER11VECTORENTRYES3_ET0_T_S5_S4__EXIT]]
; CHECK:       if.then2.i.i.i.i.i:
; CHECK-NEXT:    [[ADD_PTR3_I_I_I_I_I:%.*]] = getelementptr inbounds i8, ptr [[__FIRST_PN28]], i64 16
; CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) [[ADD_PTR3_I_I_I_I_I]], ptr noundef nonnull align 8 dereferenceable(12) [[__FIRST]], i64 12, i1 false), !tbaa [[TBAA0]], !tbaa.struct [[TBAA_STRUCT7]]
; CHECK-NEXT:    br label [[_ZST13MOVE_BACKWARDIPN11XALANC_1_1010NODESORTER11VECTORENTRYES3_ET0_T_S5_S4__EXIT]]
; CHECK:       _ZSt13move_backwardIPN11xalanc_1_1010NodeSorter11VectorEntryES3_ET0_T_S5_S4_.exit:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) [[__FIRST]], ptr noundef nonnull align 8 dereferenceable(12) [[__VAL]], i64 12, i1 false), !tbaa [[TBAA0]], !tbaa.struct [[TBAA_STRUCT7]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[__VAL]])
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       if.else:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) [[AGG_TMP5_SROA_0]], ptr noundef nonnull align 8 dereferenceable(32) [[__COMP]], i64 32, i1 false), !tbaa [[TBAA11:![0-9]+]]
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) [[AGG_TMP]], ptr noundef nonnull align 8 dereferenceable(32) [[AGG_TMP5_SROA_0]], i64 32, i1 false), !tbaa [[TBAA18:![0-9]+]]
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr nonnull [[__VAL_I]])
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) [[__VAL_I]], ptr noundef nonnull align 8 dereferenceable(16) [[__I_029]], i64 16, i1 false), !tbaa [[TBAA0]], !tbaa.struct [[TBAA_STRUCT7]]
; CHECK-NEXT:    [[M_NODESORTKEYS_PHI_TRANS_INSERT_I:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TMP]], i64 24
; CHECK-NEXT:    [[DOTPRE_I:%.*]] = load ptr, ptr [[M_NODESORTKEYS_PHI_TRANS_INSERT_I]], align 8, !tbaa [[TBAA19:![0-9]+]]
; CHECK-NEXT:    [[M_DATA_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[DOTPRE_I]], i64 24
; CHECK-NEXT:    [[I:%.*]] = load ptr, ptr [[AGG_TMP]], align 8
; CHECK-NEXT:    [[M_SIZE_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[DOTPRE_I]], i64 8
; CHECK-NEXT:    br label [[WHILE_COND_I:%.*]]
; CHECK:       while.cond.i:
; CHECK-NEXT:    [[__LAST_ADDR_0_I:%.*]] = phi ptr [ [[__I_029]], [[IF_ELSE]] ], [ [[__NEXT_0_I:%.*]], [[WHILE_BODY_I:%.*]] ]
; CHECK-NEXT:    [[__NEXT_0_I]] = getelementptr inbounds i8, ptr [[__LAST_ADDR_0_I]], i64 -16
; CHECK-NEXT:    br label [[TAILRECURSE_I:%.*]]
; CHECK:       tailrecurse.i:
; CHECK-NEXT:    [[THEKEYINDEX_TR_I:%.*]] = phi i32 [ 0, [[WHILE_COND_I]] ], [ [[ADD_I:%.*]], [[IF_ELSE46_I:%.*]] ]
; CHECK-NEXT:    [[CONV_I:%.*]] = zext i32 [[THEKEYINDEX_TR_I]] to i64
; CHECK-NEXT:    [[I1:%.*]] = load ptr, ptr [[M_DATA_I_I]], align 8, !tbaa [[TBAA20:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX_I_I:%.*]] = getelementptr inbounds %"class.xalanc_1_10::NodeSortKey", ptr [[I1]], i64 [[CONV_I]]
; CHECK-NEXT:    [[M_TREATASNUMBERS_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_I_I]], i64 16
; CHECK-NEXT:    [[I2:%.*]] = load i8, ptr [[M_TREATASNUMBERS_I_I]], align 8, !tbaa [[TBAA25:![0-9]+]], !range [[RNG33:![0-9]+]], !noundef [[META34:![0-9]+]]
; CHECK-NEXT:    [[LOADEDV_I_I:%.*]] = trunc nuw i8 [[I2]] to i1
; CHECK-NEXT:    br i1 [[LOADEDV_I_I]], label [[IF_ELSE_I:%.*]], label [[IF_THEN_I:%.*]]
; CHECK:       if.then.i:
; CHECK-NEXT:    [[CALL4_I:%.*]] = call noundef nonnull align 8 dereferenceable(36) ptr @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getStringResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) [[AGG_TMP]], ptr noundef nonnull align 8 dereferenceable(40) [[ARRAYIDX_I_I]], i32 noundef signext [[THEKEYINDEX_TR_I]], ptr noundef nonnull readonly align 8 dereferenceable(12) [[__VAL_I]])
; CHECK-NEXT:    [[CALL5_I:%.*]] = call noundef nonnull align 8 dereferenceable(36) ptr @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getStringResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) [[AGG_TMP]], ptr noundef nonnull align 8 dereferenceable(40) [[ARRAYIDX_I_I]], i32 noundef signext [[THEKEYINDEX_TR_I]], ptr noundef nonnull readonly align 8 dereferenceable(12) [[__NEXT_0_I]])
; CHECK-NEXT:    [[M_LANGUAGESTRING_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_I_I]], i64 32
; CHECK-NEXT:    [[I3:%.*]] = load ptr, ptr [[M_LANGUAGESTRING_I_I]], align 8, !tbaa [[TBAA35:![0-9]+]]
; CHECK-NEXT:    [[M_CASEORDER_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_I_I]], i64 20
; CHECK-NEXT:    [[I4:%.*]] = load i32, ptr [[M_CASEORDER_I_I]], align 4, !tbaa [[TBAA36:![0-9]+]]
; CHECK-NEXT:    [[M_SIZE_I_I_I_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[I3]], i64 32
; CHECK-NEXT:    [[I5:%.*]] = load i32, ptr [[M_SIZE_I_I_I_I_I]], align 8, !tbaa [[TBAA37:![0-9]+]]
; CHECK-NEXT:    [[CMP_I_I18:%.*]] = icmp eq i32 [[I5]], 0
; CHECK-NEXT:    [[VTABLE_I_I:%.*]] = load ptr, ptr [[I]], align 8, !tbaa [[TBAA41:![0-9]+]]
; CHECK-NEXT:    br i1 [[CMP_I_I18]], label [[IF_THEN_I_I:%.*]], label [[IF_ELSE_I_I:%.*]]
; CHECK:       if.then.i.i:
; CHECK-NEXT:    [[VFN_I_I:%.*]] = getelementptr inbounds i8, ptr [[VTABLE_I_I]], i64 1144
; CHECK-NEXT:    [[I6:%.*]] = load ptr, ptr [[VFN_I_I]], align 8
; CHECK-NEXT:    [[CALL1_I_I:%.*]] = tail call noundef signext i32 [[I6]](ptr noundef nonnull align 8 dereferenceable(24) [[I]], ptr noundef nonnull align 8 dereferenceable(36) [[CALL4_I]], ptr noundef nonnull align 8 dereferenceable(36) [[CALL5_I]], i32 noundef signext [[I4]])
; CHECK-NEXT:    br label [[IF_END38_I:%.*]]
; CHECK:       if.else.i.i:
; CHECK-NEXT:    [[VFN3_I_I:%.*]] = getelementptr inbounds i8, ptr [[VTABLE_I_I]], i64 1152
; CHECK-NEXT:    [[I7:%.*]] = load ptr, ptr [[VFN3_I_I]], align 8
; CHECK-NEXT:    [[CALL4_I_I:%.*]] = tail call noundef signext i32 [[I7]](ptr noundef nonnull align 8 dereferenceable(24) [[I]], ptr noundef nonnull align 8 dereferenceable(36) [[CALL4_I]], ptr noundef nonnull align 8 dereferenceable(36) [[CALL5_I]], ptr noundef nonnull align 8 dereferenceable(36) [[I3]], i32 noundef signext [[I4]])
; CHECK-NEXT:    br label [[IF_END38_I]]
; CHECK:       if.else.i:
; CHECK-NEXT:    [[CALL9_I:%.*]] = call fast noundef nofpclass(nan inf) double @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getNumberResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) [[AGG_TMP]], ptr noundef nonnull align 8 dereferenceable(40) [[ARRAYIDX_I_I]], i32 noundef signext [[THEKEYINDEX_TR_I]], ptr noundef nonnull readonly align 8 dereferenceable(12) [[__VAL_I]])
; CHECK-NEXT:    [[CALL10_I:%.*]] = call fast noundef nofpclass(nan inf) double @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getNumberResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) [[AGG_TMP]], ptr noundef nonnull align 8 dereferenceable(40) [[ARRAYIDX_I_I]], i32 noundef signext [[THEKEYINDEX_TR_I]], ptr noundef nonnull readonly align 8 dereferenceable(12) [[__NEXT_0_I]])
; CHECK-NEXT:    [[I8:%.*]] = load i32, ptr @_ZN11xalanc_1_1013DoubleSupport5s_NaNE, align 8, !tbaa [[TBAA43:![0-9]+]]
; CHECK-NEXT:    [[I9:%.*]] = bitcast double [[CALL9_I]] to i64
; CHECK-NEXT:    [[TEMP_SROA_0_0_EXTRACT_TRUNC_I_I_I:%.*]] = trunc i64 [[I9]] to i32
; CHECK-NEXT:    [[CMP_I_I_I19:%.*]] = icmp eq i32 [[I8]], [[TEMP_SROA_0_0_EXTRACT_TRUNC_I_I_I]]
; CHECK-NEXT:    [[I10:%.*]] = load i32, ptr getelementptr inbounds nuw (i8, ptr @_ZN11xalanc_1_1013DoubleSupport5s_NaNE, i64 4), align 4
; CHECK-NEXT:    [[TEMP_SROA_0_4_EXTRACT_SHIFT_I_I_I:%.*]] = lshr i64 [[I9]], 32
; CHECK-NEXT:    [[TEMP_SROA_0_4_EXTRACT_TRUNC_I_I_I:%.*]] = trunc nuw i64 [[TEMP_SROA_0_4_EXTRACT_SHIFT_I_I_I]] to i32
; CHECK-NEXT:    [[CMP4_I_I_I:%.*]] = icmp eq i32 [[I10]], [[TEMP_SROA_0_4_EXTRACT_TRUNC_I_I_I]]
; CHECK-NEXT:    [[I11:%.*]] = select i1 [[CMP_I_I_I19]], i1 [[CMP4_I_I_I]], i1 false
; CHECK-NEXT:    [[I12:%.*]] = bitcast double [[CALL10_I]] to i64
; CHECK-NEXT:    [[TEMP_SROA_0_0_EXTRACT_TRUNC_I_I82_I:%.*]] = trunc i64 [[I12]] to i32
; CHECK-NEXT:    [[CMP_I_I83_I:%.*]] = icmp eq i32 [[I8]], [[TEMP_SROA_0_0_EXTRACT_TRUNC_I_I82_I]]
; CHECK-NEXT:    [[TEMP_SROA_0_4_EXTRACT_SHIFT_I_I84_I:%.*]] = lshr i64 [[I12]], 32
; CHECK-NEXT:    [[TEMP_SROA_0_4_EXTRACT_TRUNC_I_I85_I:%.*]] = trunc nuw i64 [[TEMP_SROA_0_4_EXTRACT_SHIFT_I_I84_I]] to i32
; CHECK-NEXT:    [[CMP4_I_I86_I:%.*]] = icmp eq i32 [[I10]], [[TEMP_SROA_0_4_EXTRACT_TRUNC_I_I85_I]]
; CHECK-NEXT:    [[I13:%.*]] = select i1 [[CMP_I_I83_I]], i1 [[CMP4_I_I86_I]], i1 false
; CHECK-NEXT:    br i1 [[I11]], label [[IF_THEN14_I:%.*]], label [[IF_ELSE19_I:%.*]]
; CHECK:       if.then14.i:
; CHECK-NEXT:    br i1 [[I13]], label [[IF_ELSE46_I]], label [[_ZNK11XALANC_1_1010NODESORTER18NODESORTKEYCOMPARE7COMPAREERKNS0_11VECTORENTRYES4_J_EXIT:%.*]]
; CHECK:       if.else19.i:
; CHECK-NEXT:    br i1 [[I13]], label [[_ZNK11XALANC_1_1010NODESORTER18NODESORTKEYCOMPARE7COMPAREERKNS0_11VECTORENTRYES4_J_EXIT]], label [[IF_ELSE24_I:%.*]]
; CHECK:       if.else24.i:
; CHECK-NEXT:    [[CALL25_I:%.*]] = tail call noundef zeroext i1 @_ZN11xalanc_1_1013DoubleSupport8lessThanEdd(double noundef nofpclass(nan inf) [[CALL9_I]], double noundef nofpclass(nan inf) [[CALL10_I]])
; CHECK-NEXT:    br i1 [[CALL25_I]], label [[_ZNK11XALANC_1_1010NODESORTER18NODESORTKEYCOMPARE7COMPAREERKNS0_11VECTORENTRYES4_J_EXIT]], label [[IF_ELSE29_I:%.*]]
; CHECK:       if.else29.i:
; CHECK-NEXT:    [[CALL30_I:%.*]] = tail call noundef zeroext i1 @_ZN11xalanc_1_1013DoubleSupport11greaterThanEdd(double noundef nofpclass(nan inf) [[CALL9_I]], double noundef nofpclass(nan inf) [[CALL10_I]])
; CHECK-NEXT:    br i1 [[CALL30_I]], label [[_ZNK11XALANC_1_1010NODESORTER18NODESORTKEYCOMPARE7COMPAREERKNS0_11VECTORENTRYES4_J_EXIT]], label [[IF_ELSE46_I]]
; CHECK:       if.end38.i:
; CHECK-NEXT:    [[THERESULT_1_I:%.*]] = phi i32 [ [[CALL1_I_I]], [[IF_THEN_I_I]] ], [ [[CALL4_I_I]], [[IF_ELSE_I_I]] ]
; CHECK-NEXT:    [[CMP39_NOT_I:%.*]] = icmp eq i32 [[THERESULT_1_I]], 0
; CHECK-NEXT:    br i1 [[CMP39_NOT_I]], label [[IF_ELSE46_I]], label [[_ZNK11XALANC_1_1010NODESORTER18NODESORTKEYCOMPARE7COMPAREERKNS0_11VECTORENTRYES4_J_EXIT]]
; CHECK:       if.else46.i:
; CHECK-NEXT:    [[ADD_I]] = add i32 [[THEKEYINDEX_TR_I]], 1
; CHECK-NEXT:    [[CONV47_I:%.*]] = zext i32 [[ADD_I]] to i64
; CHECK-NEXT:    [[I14:%.*]] = load i64, ptr [[M_SIZE_I_I]], align 8, !tbaa [[TBAA44:![0-9]+]]
; CHECK-NEXT:    [[CMP50_I:%.*]] = icmp ugt i64 [[I14]], [[CONV47_I]]
; CHECK-NEXT:    br i1 [[CMP50_I]], label [[TAILRECURSE_I]], label [[_ZST25__UNGUARDED_LINEAR_INSERTIPN11XALANC_1_1010NODESORTER11VECTORENTRYEN9__GNU_CXX5__OPS14_VAL_COMP_ITERINS1_18NODESORTKEYCOMPAREEEEEVT_T0__EXIT_LOOPEXIT:%.*]]
; CHECK:       _ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit:
; CHECK-NEXT:    [[THERESULT_196_I:%.*]] = phi i32 [ [[THERESULT_1_I]], [[IF_END38_I]] ], [ -1, [[IF_ELSE24_I]] ], [ 1, [[IF_ELSE19_I]] ], [ -1, [[IF_THEN14_I]] ], [ 1, [[IF_ELSE29_I]] ]
; CHECK-NEXT:    [[M_DESCENDING_I_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_I_I]], i64 17
; CHECK-NEXT:    [[I15:%.*]] = load i8, ptr [[M_DESCENDING_I_I]], align 1, !tbaa [[TBAA45:![0-9]+]], !range [[RNG33]], !noundef [[META34]]
; CHECK-NEXT:    [[LOADEDV_I92_I:%.*]] = trunc nuw i8 [[I15]] to i1
; CHECK-NEXT:    [[SUB_I:%.*]] = sub nsw i32 0, [[THERESULT_196_I]]
; CHECK-NEXT:    [[SPEC_SELECT81_I:%.*]] = select i1 [[LOADEDV_I92_I]], i32 [[SUB_I]], i32 [[THERESULT_196_I]]
; CHECK-NEXT:    [[CMP_I_I_I:%.*]] = icmp slt i32 [[SPEC_SELECT81_I]], 0
; CHECK-NEXT:    br i1 [[CMP_I_I_I]], label [[WHILE_BODY_I]], label [[_ZST25__UNGUARDED_LINEAR_INSERTIPN11XALANC_1_1010NODESORTER11VECTORENTRYEN9__GNU_CXX5__OPS14_VAL_COMP_ITERINS1_18NODESORTKEYCOMPAREEEEEVT_T0__EXIT_LOOPEXIT30:%.*]]
; CHECK:       while.body.i:
; CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) [[__LAST_ADDR_0_I]], ptr noundef nonnull align 8 dereferenceable(12) [[__NEXT_0_I]], i64 12, i1 false), !tbaa [[TBAA0]], !tbaa.struct [[TBAA_STRUCT7]]
; CHECK-NEXT:    br label [[WHILE_COND_I]], !llvm.loop [[LOOP46:![0-9]+]]
; CHECK:       _ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit:
; CHECK-NEXT:    br label [[_ZST25__UNGUARDED_LINEAR_INSERTIPN11XALANC_1_1010NODESORTER11VECTORENTRYEN9__GNU_CXX5__OPS14_VAL_COMP_ITERINS1_18NODESORTKEYCOMPAREEEEEVT_T0__EXIT:%.*]]
; CHECK:       _ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit30:
; CHECK-NEXT:    br label [[_ZST25__UNGUARDED_LINEAR_INSERTIPN11XALANC_1_1010NODESORTER11VECTORENTRYEN9__GNU_CXX5__OPS14_VAL_COMP_ITERINS1_18NODESORTKEYCOMPAREEEEEVT_T0__EXIT]]
; CHECK:       _ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) [[__LAST_ADDR_0_I]], ptr noundef nonnull align 8 dereferenceable(12) [[__VAL_I]], i64 12, i1 false), !tbaa [[TBAA0]], !tbaa.struct [[TBAA_STRUCT7]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr nonnull [[__VAL_I]])
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[__I_0]] = getelementptr inbounds i8, ptr [[__I_029]], i64 16
; CHECK-NEXT:    [[CMP1_NOT:%.*]] = icmp eq ptr [[__I_0]], [[__LAST]]
; CHECK-NEXT:    br i1 [[CMP1_NOT]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP48:![0-9]+]]
; CHECK:       for.end.loopexit:
; CHECK-NEXT:    br label [[FOR_END]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  %__val.i = alloca %"struct.xalanc_1_10::NodeSorter::VectorEntry", align 8
  %__val = alloca %"struct.xalanc_1_10::NodeSorter::VectorEntry", align 8
  %agg.tmp = alloca %"struct.__gnu_cxx::__ops::_Val_comp_iter", align 8
  %agg.tmp5.sroa.0 = alloca %"struct.xalanc_1_10::NodeSorter::NodeSortKeyCompare", align 8
  %cmp = icmp eq ptr %__first, %__last
  br i1 %cmp, label %for.end, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %__i.026 = getelementptr inbounds i8, ptr %__first, i64 16
  %cmp1.not27 = icmp eq ptr %__i.026, %__last
  br i1 %cmp1.not27, label %for.end, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %for.cond.preheader
  %sub.ptr.rhs.cast.i.i.i.i.i = ptrtoint ptr %__first to i64
  br label %for.body

for.body:                                         ; preds = %for.inc, %for.body.lr.ph
  %__i.029 = phi ptr [ %__i.026, %for.body.lr.ph ], [ %__i.0, %for.inc ]
  %__first.pn28 = phi ptr [ %__first, %for.body.lr.ph ], [ %__i.029, %for.inc ]
  %call.i.i = tail call noundef signext i32 @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j(ptr noundef nonnull align 8 dereferenceable(32) %__comp, ptr noundef nonnull align 8 dereferenceable(12) %__i.029, ptr noundef nonnull align 8 dereferenceable(12) %__first, i32 noundef signext 0)
  %cmp.i.i = icmp slt i32 %call.i.i, 0
  br i1 %cmp.i.i, label %if.then2, label %if.else

if.then2:                                         ; preds = %for.body
  call void @llvm.lifetime.start.p0(i64 16, ptr %__val)
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %__val, ptr noundef nonnull align 8 dereferenceable(16) %__i.029, i64 16, i1 false), !tbaa !11, !tbaa.struct !18
  %sub.ptr.lhs.cast.i.i.i.i.i = ptrtoint ptr %__i.029 to i64
  %sub.ptr.sub.i.i.i.i.i = sub i64 %sub.ptr.lhs.cast.i.i.i.i.i, %sub.ptr.rhs.cast.i.i.i.i.i
  %sub.ptr.div.i.i.i.i.i = ashr exact i64 %sub.ptr.sub.i.i.i.i.i, 4
  %cmp.i.i.i.i.i = icmp sgt i64 %sub.ptr.div.i.i.i.i.i, 1
  br i1 %cmp.i.i.i.i.i, label %if.then.i.i.i.i.i, label %if.else.i.i.i.i.i, !prof !21

if.then.i.i.i.i.i:                                ; preds = %if.then2
  %add.ptr3 = getelementptr inbounds i8, ptr %__first.pn28, i64 32
  %idx.neg.i.i.i.i.i = sub nsw i64 0, %sub.ptr.div.i.i.i.i.i
  %add.ptr.i.i.i.i.i = getelementptr inbounds %"struct.xalanc_1_10::NodeSorter::VectorEntry", ptr %add.ptr3, i64 %idx.neg.i.i.i.i.i
  tail call void @llvm.memmove.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(1) %add.ptr.i.i.i.i.i, ptr noundef nonnull align 8 dereferenceable(1) %__first, i64 %sub.ptr.sub.i.i.i.i.i, i1 false)
  br label %_ZSt13move_backwardIPN11xalanc_1_1010NodeSorter11VectorEntryES3_ET0_T_S5_S4_.exit

if.else.i.i.i.i.i:                                ; preds = %if.then2
  %cmp1.i.i.i.i.i = icmp eq i64 %sub.ptr.sub.i.i.i.i.i, 16
  br i1 %cmp1.i.i.i.i.i, label %if.then2.i.i.i.i.i, label %_ZSt13move_backwardIPN11xalanc_1_1010NodeSorter11VectorEntryES3_ET0_T_S5_S4_.exit

if.then2.i.i.i.i.i:                               ; preds = %if.else.i.i.i.i.i
  %add.ptr3.i.i.i.i.i = getelementptr inbounds i8, ptr %__first.pn28, i64 16
  tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) %add.ptr3.i.i.i.i.i, ptr noundef nonnull align 8 dereferenceable(12) %__first, i64 12, i1 false), !tbaa !11, !tbaa.struct !18
  br label %_ZSt13move_backwardIPN11xalanc_1_1010NodeSorter11VectorEntryES3_ET0_T_S5_S4_.exit

_ZSt13move_backwardIPN11xalanc_1_1010NodeSorter11VectorEntryES3_ET0_T_S5_S4_.exit: ; preds = %if.then2.i.i.i.i.i, %if.else.i.i.i.i.i, %if.then.i.i.i.i.i
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) %__first, ptr noundef nonnull align 8 dereferenceable(12) %__val, i64 12, i1 false), !tbaa !11, !tbaa.struct !18
  call void @llvm.lifetime.end.p0(i64 16, ptr %__val)
  br label %for.inc

if.else:                                          ; preds = %for.body
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) %agg.tmp5.sroa.0, ptr noundef nonnull align 8 dereferenceable(32) %__comp, i64 32, i1 false), !tbaa !22
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) %agg.tmp, ptr noundef nonnull align 8 dereferenceable(32) %agg.tmp5.sroa.0, i64 32, i1 false), !tbaa !29
  call void @llvm.lifetime.start.p0(i64 16, ptr nonnull %__val.i) #10
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) %__val.i, ptr noundef nonnull align 8 dereferenceable(16) %__i.029, i64 16, i1 false), !tbaa !11, !tbaa.struct !18
  %m_nodeSortKeys.phi.trans.insert.i = getelementptr inbounds nuw i8, ptr %agg.tmp, i64 24
  %.pre.i = load ptr, ptr %m_nodeSortKeys.phi.trans.insert.i, align 8, !tbaa !30
  %m_data.i.i = getelementptr inbounds nuw i8, ptr %.pre.i, i64 24
  %i = load ptr, ptr %agg.tmp, align 8
  %m_size.i.i = getelementptr inbounds nuw i8, ptr %.pre.i, i64 8
  br label %while.cond.i

while.cond.i:                                     ; preds = %while.body.i, %if.else
  %__last.addr.0.i = phi ptr [ %__i.029, %if.else ], [ %__next.0.i, %while.body.i ]
  %__next.0.i = getelementptr inbounds i8, ptr %__last.addr.0.i, i64 -16
  br label %tailrecurse.i

tailrecurse.i:                                    ; preds = %if.else46.i, %while.cond.i
  %theKeyIndex.tr.i = phi i32 [ 0, %while.cond.i ], [ %add.i, %if.else46.i ]
  %conv.i = zext i32 %theKeyIndex.tr.i to i64
  %i1 = load ptr, ptr %m_data.i.i, align 8, !tbaa !31
  %arrayidx.i.i = getelementptr inbounds %"class.xalanc_1_10::NodeSortKey", ptr %i1, i64 %conv.i
  %m_treatAsNumbers.i.i = getelementptr inbounds nuw i8, ptr %arrayidx.i.i, i64 16
  %i2 = load i8, ptr %m_treatAsNumbers.i.i, align 8, !tbaa !36, !range !44, !noundef !45
  %loadedv.i.i = trunc nuw i8 %i2 to i1
  br i1 %loadedv.i.i, label %if.else.i, label %if.then.i

if.then.i:                                        ; preds = %tailrecurse.i
  %call4.i = call noundef nonnull align 8 dereferenceable(36) ptr @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getStringResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) %agg.tmp, ptr noundef nonnull align 8 dereferenceable(40) %arrayidx.i.i, i32 noundef signext %theKeyIndex.tr.i, ptr noundef nonnull readonly align 8 dereferenceable(12) %__val.i)
  %call5.i = call noundef nonnull align 8 dereferenceable(36) ptr @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getStringResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) %agg.tmp, ptr noundef nonnull align 8 dereferenceable(40) %arrayidx.i.i, i32 noundef signext %theKeyIndex.tr.i, ptr noundef nonnull readonly align 8 dereferenceable(12) %__next.0.i)
  %m_languageString.i.i = getelementptr inbounds nuw i8, ptr %arrayidx.i.i, i64 32
  %i3 = load ptr, ptr %m_languageString.i.i, align 8, !tbaa !46
  %m_caseOrder.i.i = getelementptr inbounds nuw i8, ptr %arrayidx.i.i, i64 20
  %i4 = load i32, ptr %m_caseOrder.i.i, align 4, !tbaa !47
  %m_size.i.i.i.i.i = getelementptr inbounds nuw i8, ptr %i3, i64 32
  %i5 = load i32, ptr %m_size.i.i.i.i.i, align 8, !tbaa !48
  %cmp.i.i18 = icmp eq i32 %i5, 0
  %vtable.i.i = load ptr, ptr %i, align 8, !tbaa !52
  br i1 %cmp.i.i18, label %if.then.i.i, label %if.else.i.i

if.then.i.i:                                      ; preds = %if.then.i
  %vfn.i.i = getelementptr inbounds i8, ptr %vtable.i.i, i64 1144
  %i6 = load ptr, ptr %vfn.i.i, align 8
  %call1.i.i = tail call noundef signext i32 %i6(ptr noundef nonnull align 8 dereferenceable(24) %i, ptr noundef nonnull align 8 dereferenceable(36) %call4.i, ptr noundef nonnull align 8 dereferenceable(36) %call5.i, i32 noundef signext %i4)
  br label %if.end38.i

if.else.i.i:                                      ; preds = %if.then.i
  %vfn3.i.i = getelementptr inbounds i8, ptr %vtable.i.i, i64 1152
  %i7 = load ptr, ptr %vfn3.i.i, align 8
  %call4.i.i = tail call noundef signext i32 %i7(ptr noundef nonnull align 8 dereferenceable(24) %i, ptr noundef nonnull align 8 dereferenceable(36) %call4.i, ptr noundef nonnull align 8 dereferenceable(36) %call5.i, ptr noundef nonnull align 8 dereferenceable(36) %i3, i32 noundef signext %i4)
  br label %if.end38.i

if.else.i:                                        ; preds = %tailrecurse.i
  %call9.i = call fast noundef nofpclass(nan inf) double @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getNumberResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) %agg.tmp, ptr noundef nonnull align 8 dereferenceable(40) %arrayidx.i.i, i32 noundef signext %theKeyIndex.tr.i, ptr noundef nonnull readonly align 8 dereferenceable(12) %__val.i)
  %call10.i = call fast noundef nofpclass(nan inf) double @_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare15getNumberResultERKNS_11NodeSortKeyEjRKNS0_11VectorEntryE(ptr noundef nonnull readonly align 8 dereferenceable(32) %agg.tmp, ptr noundef nonnull align 8 dereferenceable(40) %arrayidx.i.i, i32 noundef signext %theKeyIndex.tr.i, ptr noundef nonnull readonly align 8 dereferenceable(12) %__next.0.i)
  %i8 = load i32, ptr @_ZN11xalanc_1_1013DoubleSupport5s_NaNE, align 8, !tbaa !54
  %i9 = bitcast double %call9.i to i64
  %temp.sroa.0.0.extract.trunc.i.i.i = trunc i64 %i9 to i32
  %cmp.i.i.i19 = icmp eq i32 %i8, %temp.sroa.0.0.extract.trunc.i.i.i
  %i10 = load i32, ptr getelementptr inbounds nuw (i8, ptr @_ZN11xalanc_1_1013DoubleSupport5s_NaNE, i64 4), align 4
  %temp.sroa.0.4.extract.shift.i.i.i = lshr i64 %i9, 32
  %temp.sroa.0.4.extract.trunc.i.i.i = trunc nuw i64 %temp.sroa.0.4.extract.shift.i.i.i to i32
  %cmp4.i.i.i = icmp eq i32 %i10, %temp.sroa.0.4.extract.trunc.i.i.i
  %i11 = select i1 %cmp.i.i.i19, i1 %cmp4.i.i.i, i1 false
  %i12 = bitcast double %call10.i to i64
  %temp.sroa.0.0.extract.trunc.i.i82.i = trunc i64 %i12 to i32
  %cmp.i.i83.i = icmp eq i32 %i8, %temp.sroa.0.0.extract.trunc.i.i82.i
  %temp.sroa.0.4.extract.shift.i.i84.i = lshr i64 %i12, 32
  %temp.sroa.0.4.extract.trunc.i.i85.i = trunc nuw i64 %temp.sroa.0.4.extract.shift.i.i84.i to i32
  %cmp4.i.i86.i = icmp eq i32 %i10, %temp.sroa.0.4.extract.trunc.i.i85.i
  %i13 = select i1 %cmp.i.i83.i, i1 %cmp4.i.i86.i, i1 false
  br i1 %i11, label %if.then14.i, label %if.else19.i

if.then14.i:                                      ; preds = %if.else.i
  br i1 %i13, label %if.else46.i, label %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit

if.else19.i:                                      ; preds = %if.else.i
  br i1 %i13, label %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit, label %if.else24.i

if.else24.i:                                      ; preds = %if.else19.i
  %call25.i = tail call noundef zeroext i1 @_ZN11xalanc_1_1013DoubleSupport8lessThanEdd(double noundef nofpclass(nan inf) %call9.i, double noundef nofpclass(nan inf) %call10.i)
  br i1 %call25.i, label %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit, label %if.else29.i

if.else29.i:                                      ; preds = %if.else24.i
  %call30.i = tail call noundef zeroext i1 @_ZN11xalanc_1_1013DoubleSupport11greaterThanEdd(double noundef nofpclass(nan inf) %call9.i, double noundef nofpclass(nan inf) %call10.i)
  br i1 %call30.i, label %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit, label %if.else46.i

if.end38.i:                                       ; preds = %if.else.i.i, %if.then.i.i
  %theResult.1.i = phi i32 [ %call1.i.i, %if.then.i.i ], [ %call4.i.i, %if.else.i.i ]
  %cmp39.not.i = icmp eq i32 %theResult.1.i, 0
  br i1 %cmp39.not.i, label %if.else46.i, label %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit

if.else46.i:                                      ; preds = %if.end38.i, %if.else29.i, %if.then14.i
  %add.i = add i32 %theKeyIndex.tr.i, 1
  %conv47.i = zext i32 %add.i to i64
  %i14 = load i64, ptr %m_size.i.i, align 8, !tbaa !55
  %cmp50.i = icmp ugt i64 %i14, %conv47.i
  br i1 %cmp50.i, label %tailrecurse.i, label %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit

_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit: ; preds = %if.end38.i, %if.else29.i, %if.else24.i, %if.else19.i, %if.then14.i
  %arrayidx.i.i.lcssa = phi ptr [ %arrayidx.i.i, %if.then14.i ], [ %arrayidx.i.i, %if.else19.i ], [ %arrayidx.i.i, %if.else24.i ], [ %arrayidx.i.i, %if.else29.i ], [ %arrayidx.i.i, %if.end38.i ]
  %theResult.196.i = phi i32 [ %theResult.1.i, %if.end38.i ], [ -1, %if.else24.i ], [ 1, %if.else19.i ], [ -1, %if.then14.i ], [ 1, %if.else29.i ]
  %m_descending.i.i = getelementptr inbounds nuw i8, ptr %arrayidx.i.i.lcssa, i64 17
  %i15 = load i8, ptr %m_descending.i.i, align 1, !tbaa !56, !range !44, !noundef !45
  %loadedv.i92.i = trunc nuw i8 %i15 to i1
  %sub.i = sub nsw i32 0, %theResult.196.i
  %spec.select81.i = select i1 %loadedv.i92.i, i32 %sub.i, i32 %theResult.196.i
  %cmp.i.i.i = icmp slt i32 %spec.select81.i, 0
  br i1 %cmp.i.i.i, label %while.body.i, label %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit30

while.body.i:                                     ; preds = %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit
  tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) %__last.addr.0.i, ptr noundef nonnull align 8 dereferenceable(12) %__next.0.i, i64 12, i1 false), !tbaa !11, !tbaa.struct !18
  br label %while.cond.i, !llvm.loop !57

_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit: ; preds = %if.else46.i
  %__last.addr.0.i.lcssa32 = phi ptr [ %__last.addr.0.i, %if.else46.i ]
  br label %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit

_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit30: ; preds = %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit
  %__last.addr.0.i.lcssa = phi ptr [ %__last.addr.0.i, %_ZNK11xalanc_1_1010NodeSorter18NodeSortKeyCompare7compareERKNS0_11VectorEntryES4_j.exit ]
  br label %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit

_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit: ; preds = %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit30, %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit
  %__last.addr.0.i33 = phi ptr [ %__last.addr.0.i.lcssa, %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit30 ], [ %__last.addr.0.i.lcssa32, %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit.loopexit ]
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(12) %__last.addr.0.i33, ptr noundef nonnull align 8 dereferenceable(12) %__val.i, i64 12, i1 false), !tbaa !11, !tbaa.struct !18
  call void @llvm.lifetime.end.p0(i64 16, ptr nonnull %__val.i) #10
  br label %for.inc

for.inc:                                          ; preds = %_ZSt25__unguarded_linear_insertIPN11xalanc_1_1010NodeSorter11VectorEntryEN9__gnu_cxx5__ops14_Val_comp_iterINS1_18NodeSortKeyCompareEEEEvT_T0_.exit, %_ZSt13move_backwardIPN11xalanc_1_1010NodeSorter11VectorEntryES3_ET0_T_S5_S4_.exit
  %__i.0 = getelementptr inbounds i8, ptr %__i.029, i64 16
  %cmp1.not = icmp eq ptr %__i.0, %__last
  br i1 %cmp1.not, label %for.end.loopexit, label %for.body, !llvm.loop !59

for.end.loopexit:                                 ; preds = %for.inc
  br label %for.end

for.end:                                          ; preds = %for.end.loopexit, %for.cond.preheader, %entry
  ret void
}

!11 = !{!12, !12, i64 0, i64 16}
!12 = !{!13, i64 16, !"_ZTSN11xalanc_1_1010NodeSorter11VectorEntryE", !15, i64 0, i64 8, !17, i64 8, i64 4}
!13 = !{!14, i64 1, !"omnipotent char"}
!14 = !{!"Simple C++ TBAA"}
!15 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_109XalanNodeE"}
!16 = !{!13, i64 8, !"any pointer"}
!17 = !{!13, i64 4, !"int"}
!18 = !{i64 0, i64 8, !19, i64 8, i64 4, !20}
!19 = !{!15, !15, i64 0, i64 8}
!20 = !{!17, !17, i64 0, i64 4}
!21 = !{!"branch_weights", !"expected", i32 2000, i32 1}
!22 = !{!23, !23, i64 0, i64 32}
!23 = !{!13, i64 32, !"_ZTSN9__gnu_cxx5__ops15_Iter_comp_iterIN11xalanc_1_1010NodeSorter18NodeSortKeyCompareEEE", !24, i64 0, i64 32}
!24 = !{!13, i64 32, !"_ZTSN11xalanc_1_1010NodeSorter18NodeSortKeyCompareE", !25, i64 0, i64 8, !26, i64 8, i64 8, !27, i64 16, i64 8, !28, i64 24, i64 8}
!25 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1026StylesheetExecutionContextE"}
!26 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1010NodeSorterE"}
!27 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1011XalanVectorINS_10NodeSorter11VectorEntryENS_31MemoryManagedConstructionTraitsIS2_EEEE"}
!28 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1011XalanVectorINS_11NodeSortKeyENS_31MemoryManagedConstructionTraitsIS1_EEEE"}
!29 = !{!24, !24, i64 0, i64 32}
!30 = !{!24, !28, i64 24, i64 8}
!31 = !{!32, !35, i64 24, i64 8}
!32 = !{!13, i64 32, !"_ZTSN11xalanc_1_1011XalanVectorINS_11NodeSortKeyENS_31MemoryManagedConstructionTraitsIS1_EEEE", !33, i64 0, i64 8, !34, i64 8, i64 8, !34, i64 16, i64 8, !35, i64 24, i64 8}
!33 = !{!16, i64 8, !"p1 class _ZTSN11xercesc_2_713MemoryManagerE"}
!34 = !{!13, i64 8, !"long"}
!35 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1011NodeSortKeyE"}
!36 = !{!37, !40, i64 16, i64 1}
!37 = !{!13, i64 40, !"_ZTSN11xalanc_1_1011NodeSortKeyE", !38, i64 0, i64 8, !39, i64 8, i64 8, !40, i64 16, i64 1, !40, i64 17, i64 1, !41, i64 20, i64 4, !42, i64 24, i64 8, !43, i64 32, i64 8}
!38 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1016ExecutionContextE"}
!39 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_105XPathE"}
!40 = !{!13, i64 1, !"bool"}
!41 = !{!13, i64 4, !"_ZTSN11xalanc_1_1022XalanCollationServices10eCaseOrderE"}
!42 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1014PrefixResolverE"}
!43 = !{!16, i64 8, !"p1 class _ZTSN11xalanc_1_1014XalanDOMStringE"}
!44 = !{i8 0, i8 2}
!45 = !{}
!46 = !{!37, !43, i64 32, i64 8}
!47 = !{!37, !41, i64 20, i64 4}
!48 = !{!49, !17, i64 32, i64 4}
!49 = !{!13, i64 40, !"_ZTSN11xalanc_1_1014XalanDOMStringE", !50, i64 0, i64 32, !17, i64 32, i64 4}
!50 = !{!13, i64 32, !"_ZTSN11xalanc_1_1011XalanVectorItNS_31MemoryManagedConstructionTraitsItEEEE", !33, i64 0, i64 8, !34, i64 8, i64 8, !34, i64 16, i64 8, !51, i64 24, i64 8}
!51 = !{!16, i64 8, !"p1 short"}
!52 = !{!53, !53, i64 0, i64 8}
!53 = !{!14, i64 8, !"vtable pointer"}
!54 = !{!13, !13, i64 0, i64 0}
!55 = !{!32, !34, i64 8, i64 8}
!56 = !{!37, !40, i64 17, i64 1}
!57 = distinct !{!57, !58}
!58 = !{!"llvm.loop.mustprogress"}
!59 = distinct !{!59, !58}
