; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=gvn -enable-load-pre -enable-pre -S < %s | FileCheck %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

%struct.rtx_def = type { i32, [1 x %union.rtunion_def] }
%union.rtunion_def = type { i64 }
%struct.rtvec_def = type { i32, [1 x ptr] }

@rtx_length = external local_unnamed_addr constant [153 x i8], align 8
@rtx_format = external local_unnamed_addr constant [153 x ptr], align 8

declare ptr @rtx_alloc(i32 noundef signext)
declare ptr @rtvec_alloc(i32 noundef signext)

; %i6 = load i8, ptr %arrayidx64, align 1, !tbaa !3
; is mayalias and passes through the legacy path with nomodref,
; causing GVN to create a crit edge for sw.epilog with the load hoisted to it.

declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg) #0

define dso_local noundef ptr @copy_rtx_if_shared(ptr noundef %orig) local_unnamed_addr align 8 {
; CHECK-LABEL: define dso_local noundef ptr @copy_rtx_if_shared(
; CHECK-SAME: ptr noundef [[ORIG:%.*]]) local_unnamed_addr align 8 {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[ORIG]], null
; CHECK-NEXT:    br i1 [[CMP]], label %[[CLEANUP:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[BF_LOAD:%.*]] = load i32, ptr [[ORIG]], align 8
; CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i32 [[BF_LOAD]], 65535
; CHECK-NEXT:    [[TRUNC:%.*]] = trunc i32 [[BF_LOAD]] to i16
; CHECK-NEXT:    switch i16 [[TRUNC]], label %[[SW_EPILOG:.*]] [
; CHECK-NEXT:      i16 61, label %[[CLEANUP]]
; CHECK-NEXT:      i16 71, label %[[CLEANUP]]
; CHECK-NEXT:      i16 54, label %[[CLEANUP]]
; CHECK-NEXT:      i16 55, label %[[CLEANUP]]
; CHECK-NEXT:      i16 56, label %[[CLEANUP]]
; CHECK-NEXT:      i16 68, label %[[CLEANUP]]
; CHECK-NEXT:      i16 36, label %[[CLEANUP]]
; CHECK-NEXT:      i16 59, label %[[CLEANUP]]
; CHECK-NEXT:      i16 69, label %[[CLEANUP]]
; CHECK-NEXT:      i16 62, label %[[CLEANUP]]
; CHECK-NEXT:      i16 58, label %[[SW_BB1:.*]]
; CHECK-NEXT:      i16 32, label %[[CLEANUP]]
; CHECK-NEXT:      i16 33, label %[[CLEANUP]]
; CHECK-NEXT:      i16 34, label %[[CLEANUP]]
; CHECK-NEXT:      i16 37, label %[[CLEANUP]]
; CHECK-NEXT:      i16 35, label %[[CLEANUP]]
; CHECK-NEXT:      i16 66, label %[[SW_BB23:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1]]:
; CHECK-NEXT:    [[FLD:%.*]] = getelementptr inbounds nuw [[STRUCT_RTX_DEF:%.*]], ptr [[ORIG]], i64 0, i32 1
; CHECK-NEXT:    [[I:%.*]] = load ptr, ptr [[FLD]], align 8, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[BF_LOAD2:%.*]] = load i32, ptr [[I]], align 8
; CHECK-NEXT:    [[BF_CLEAR3:%.*]] = and i32 [[BF_LOAD2]], 65535
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[BF_CLEAR3]], 75
; CHECK-NEXT:    br i1 [[CMP4]], label %[[LAND_LHS_TRUE:.*]], label %[[SW_EPILOG]]
; CHECK:       [[LAND_LHS_TRUE]]:
; CHECK-NEXT:    [[FLD7:%.*]] = getelementptr inbounds nuw [[STRUCT_RTX_DEF]], ptr [[I]], i64 0, i32 1
; CHECK-NEXT:    [[I1:%.*]] = load ptr, ptr [[FLD7]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[BF_LOAD9:%.*]] = load i32, ptr [[I1]], align 8
; CHECK-NEXT:    [[BF_CLEAR10:%.*]] = and i32 [[BF_LOAD9]], 65535
; CHECK-NEXT:    [[CMP11:%.*]] = icmp eq i32 [[BF_CLEAR10]], 68
; CHECK-NEXT:    br i1 [[CMP11]], label %[[LAND_LHS_TRUE12:.*]], label %[[SW_EPILOG]]
; CHECK:       [[LAND_LHS_TRUE12]]:
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds [[STRUCT_RTX_DEF]], ptr [[I]], i64 1
; CHECK-NEXT:    [[I2:%.*]] = load ptr, ptr [[ARRAYIDX16]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[BF_LOAD17:%.*]] = load i32, ptr [[I2]], align 8
; CHECK-NEXT:    [[BF_CLEAR18:%.*]] = and i32 [[BF_LOAD17]], 65535
; CHECK-NEXT:    [[CMP19:%.*]] = icmp eq i32 [[BF_CLEAR18]], 54
; CHECK-NEXT:    br i1 [[CMP19]], label %[[CLEANUP]], label %[[SW_EPILOG]]
; CHECK:       [[SW_BB23]]:
; CHECK-NEXT:    [[FLD24:%.*]] = getelementptr inbounds nuw [[STRUCT_RTX_DEF]], ptr [[ORIG]], i64 0, i32 1
; CHECK-NEXT:    [[I3:%.*]] = load ptr, ptr [[FLD24]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[BF_LOAD26:%.*]] = load i32, ptr [[I3]], align 8
; CHECK-NEXT:    [[TRUNC46:%.*]] = trunc i32 [[BF_LOAD26]] to i16
; CHECK-NEXT:    switch i16 [[TRUNC46]], label %[[SW_EPILOG]] [
; CHECK-NEXT:      i16 67, label %[[CLEANUP]]
; CHECK-NEXT:      i16 68, label %[[CLEANUP]]
; CHECK-NEXT:      i16 54, label %[[CLEANUP]]
; CHECK-NEXT:      i16 58, label %[[CLEANUP]]
; CHECK-NEXT:      i16 55, label %[[CLEANUP]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_EPILOG]]:
; CHECK-NEXT:    [[I4:%.*]] = and i32 [[BF_LOAD]], 536870912
; CHECK-NEXT:    [[TOBOOL_NOT_NOT:%.*]] = icmp eq i32 [[I4]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT_NOT]], label %[[SW_EPILOG_IF_END58_CRIT_EDGE:.*]], label %[[IF_THEN56:.*]]
; CHECK:       [[SW_EPILOG_IF_END58_CRIT_EDGE]]:
; CHECK-NEXT:    [[IDXPROM61_PHI_TRANS_INSERT:%.*]] = zext i32 [[BF_CLEAR]] to i64
; CHECK-NEXT:    [[ARRAYIDX64_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds [153 x i8], ptr @rtx_length, i64 0, i64 [[IDXPROM61_PHI_TRANS_INSERT]]
; CHECK-NEXT:    [[I6_PRE:%.*]] = load i8, ptr [[ARRAYIDX64_PHI_TRANS_INSERT]], align 1, !tbaa [[TBAA3:![0-9]+]]
; CHECK-NEXT:    br label %[[IF_END58:.*]]
; CHECK:       [[IF_THEN56]]:
; CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @rtx_alloc(i32 noundef signext [[BF_CLEAR]])
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext nneg i32 [[BF_CLEAR]] to i64
; CHECK-NEXT:    [[ARRAYIDX57:%.*]] = getelementptr inbounds [153 x i8], ptr @rtx_length, i64 0, i64 [[IDXPROM]]
; CHECK-NEXT:    [[I5:%.*]] = load i8, ptr [[ARRAYIDX57]], align 1, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[I5]] to i64
; CHECK-NEXT:    [[MUL:%.*]] = shl nuw nsw i64 [[CONV]], 3
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw i64 [[MUL]], 8
; CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(1) [[CALL]], ptr noundef nonnull align 8 dereferenceable(1) [[ORIG]], i64 [[ADD]], i1 false)
; CHECK-NEXT:    [[BF_LOAD59_PRE:%.*]] = load i32, ptr [[CALL]], align 8
; CHECK-NEXT:    br label %[[IF_END58]]
; CHECK:       [[IF_END58]]:
; CHECK-NEXT:    [[IDXPROM61_PRE_PHI:%.*]] = phi i64 [ [[IDXPROM61_PHI_TRANS_INSERT]], %[[SW_EPILOG_IF_END58_CRIT_EDGE]] ], [ [[IDXPROM]], %[[IF_THEN56]] ]
; CHECK-NEXT:    [[I6:%.*]] = phi i8 [ [[I5]], %[[IF_THEN56]] ], [ [[I6_PRE]], %[[SW_EPILOG_IF_END58_CRIT_EDGE]] ]
; CHECK-NEXT:    [[BF_LOAD59:%.*]] = phi i32 [ [[BF_LOAD59_PRE]], %[[IF_THEN56]] ], [ [[BF_LOAD]], %[[SW_EPILOG_IF_END58_CRIT_EDGE]] ]
; CHECK-NEXT:    [[X_0:%.*]] = phi ptr [ [[CALL]], %[[IF_THEN56]] ], [ [[ORIG]], %[[SW_EPILOG_IF_END58_CRIT_EDGE]] ]
; CHECK-NEXT:    [[BF_SET:%.*]] = or i32 [[BF_LOAD59]], 536870912
; CHECK-NEXT:    store i32 [[BF_SET]], ptr [[X_0]], align 8
; CHECK-NEXT:    [[ARRAYIDX64:%.*]] = getelementptr inbounds [153 x i8], ptr @rtx_length, i64 0, i64 [[IDXPROM61_PRE_PHI]]
; CHECK-NEXT:    [[CONV65:%.*]] = zext i8 [[I6]] to i32
; CHECK-NEXT:    [[CMP6649_NOT:%.*]] = icmp eq i8 [[I6]], 0
; CHECK-NEXT:    br i1 [[CMP6649_NOT]], label %[[CLEANUP]], label %[[FOR_BODY_LR_PH:.*]]
; CHECK:       [[FOR_BODY_LR_PH]]:
; CHECK-NEXT:    [[ARRAYIDX62:%.*]] = getelementptr inbounds [153 x ptr], ptr @rtx_format, i64 0, i64 [[IDXPROM61_PRE_PHI]]
; CHECK-NEXT:    [[I7:%.*]] = load ptr, ptr [[ARRAYIDX62]], align 8, !tbaa [[TBAA4:![0-9]+]]
; CHECK-NEXT:    br i1 [[TOBOOL_NOT_NOT]], label %[[FOR_BODY_US_PREHEADER:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT57:%.*]] = zext i32 [[CONV65]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY_US_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT67:%.*]] = zext i32 [[CONV65]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY_US:.*]]
; CHECK:       [[FOR_BODY_US]]:
; CHECK-NEXT:    [[INDVARS_IV64:%.*]] = phi i64 [ 0, %[[FOR_BODY_US_PREHEADER]] ], [ [[INDVARS_IV_NEXT65:%.*]], %[[FOR_INC119_US:.*]] ]
; CHECK-NEXT:    [[FORMAT_PTR_051_US:%.*]] = phi ptr [ [[INCDEC_PTR_US:%.*]], %[[FOR_INC119_US]] ], [ [[I7]], %[[FOR_BODY_US_PREHEADER]] ]
; CHECK-NEXT:    [[INCDEC_PTR_US]] = getelementptr inbounds i8, ptr [[FORMAT_PTR_051_US]], i64 1
; CHECK-NEXT:    [[I8:%.*]] = load i8, ptr [[FORMAT_PTR_051_US]], align 1, !tbaa [[TBAA3]]
; CHECK-NEXT:    switch i8 [[I8]], label %[[FOR_INC119_US]] [
; CHECK-NEXT:      i8 101, label %[[SW_BB69_US:.*]]
; CHECK-NEXT:      i8 69, label %[[SW_BB77_US:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB77_US]]:
; CHECK-NEXT:    [[ARRAYIDX80_US:%.*]] = getelementptr inbounds [[STRUCT_RTX_DEF]], ptr [[X_0]], i64 0, i32 1, i64 [[INDVARS_IV64]]
; CHECK-NEXT:    [[I9:%.*]] = load ptr, ptr [[ARRAYIDX80_US]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CMP81_NOT_US:%.*]] = icmp eq ptr [[I9]], null
; CHECK-NEXT:    br i1 [[CMP81_NOT_US]], label %[[FOR_INC119_US]], label %[[IF_THEN83_US:.*]]
; CHECK:       [[IF_THEN83_US]]:
; CHECK-NEXT:    [[I10:%.*]] = load i32, ptr [[I9]], align 8, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[CMP10147_US:%.*]] = icmp sgt i32 [[I10]], 0
; CHECK-NEXT:    br i1 [[CMP10147_US]], label %[[FOR_BODY103_US_PREHEADER:.*]], label %[[FOR_INC119_US]]
; CHECK:       [[FOR_BODY103_US_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT62:%.*]] = zext i32 [[I10]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY103_US:.*]]
; CHECK:       [[FOR_BODY103_US]]:
; CHECK-NEXT:    [[INDVARS_IV59:%.*]] = phi i64 [ 0, %[[FOR_BODY103_US_PREHEADER]] ], [ [[INDVARS_IV_NEXT60:%.*]], %[[FOR_BODY103_US]] ]
; CHECK-NEXT:    [[I11:%.*]] = load ptr, ptr [[ARRAYIDX80_US]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX109_US:%.*]] = getelementptr inbounds [[STRUCT_RTVEC_DEF:%.*]], ptr [[I11]], i64 0, i32 1, i64 [[INDVARS_IV59]]
; CHECK-NEXT:    [[I12:%.*]] = load ptr, ptr [[ARRAYIDX109_US]], align 8, !tbaa [[TBAA10:![0-9]+]]
; CHECK-NEXT:    [[CALL110_US:%.*]] = tail call ptr @copy_rtx_if_shared(ptr noundef [[I12]])
; CHECK-NEXT:    [[I13:%.*]] = load ptr, ptr [[ARRAYIDX80_US]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX116_US:%.*]] = getelementptr inbounds [[STRUCT_RTVEC_DEF]], ptr [[I13]], i64 0, i32 1, i64 [[INDVARS_IV59]]
; CHECK-NEXT:    store ptr [[CALL110_US]], ptr [[ARRAYIDX116_US]], align 8, !tbaa [[TBAA10]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT60]] = add nuw nsw i64 [[INDVARS_IV59]], 1
; CHECK-NEXT:    [[EXITCOND63:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT60]], [[WIDE_TRIP_COUNT62]]
; CHECK-NEXT:    br i1 [[EXITCOND63]], label %[[FOR_BODY103_US]], label %[[FOR_INC119_US_LOOPEXIT:.*]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[SW_BB69_US]]:
; CHECK-NEXT:    [[ARRAYIDX72_US:%.*]] = getelementptr inbounds [[STRUCT_RTX_DEF]], ptr [[X_0]], i64 0, i32 1, i64 [[INDVARS_IV64]]
; CHECK-NEXT:    [[I14:%.*]] = load ptr, ptr [[ARRAYIDX72_US]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CALL73_US:%.*]] = tail call ptr @copy_rtx_if_shared(ptr noundef [[I14]])
; CHECK-NEXT:    store ptr [[CALL73_US]], ptr [[ARRAYIDX72_US]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[FOR_INC119_US]]
; CHECK:       [[FOR_INC119_US_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_INC119_US]]
; CHECK:       [[FOR_INC119_US]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT65]] = add nuw nsw i64 [[INDVARS_IV64]], 1
; CHECK-NEXT:    [[EXITCOND68:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT65]], [[WIDE_TRIP_COUNT67]]
; CHECK-NEXT:    br i1 [[EXITCOND68]], label %[[FOR_BODY_US]], label %[[CLEANUP_LOOPEXIT:.*]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV54:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT55:%.*]], %[[FOR_INC119:.*]] ]
; CHECK-NEXT:    [[FORMAT_PTR_051:%.*]] = phi ptr [ [[INCDEC_PTR:%.*]], %[[FOR_INC119]] ], [ [[I7]], %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[FORMAT_PTR_051]], i64 1
; CHECK-NEXT:    [[I15:%.*]] = load i8, ptr [[FORMAT_PTR_051]], align 1, !tbaa [[TBAA3]]
; CHECK-NEXT:    switch i8 [[I15]], label %[[FOR_INC119]] [
; CHECK-NEXT:      i8 101, label %[[SW_BB69:.*]]
; CHECK-NEXT:      i8 69, label %[[SW_BB77:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB69]]:
; CHECK-NEXT:    [[ARRAYIDX72:%.*]] = getelementptr inbounds [[STRUCT_RTX_DEF]], ptr [[X_0]], i64 0, i32 1, i64 [[INDVARS_IV54]]
; CHECK-NEXT:    [[I16:%.*]] = load ptr, ptr [[ARRAYIDX72]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CALL73:%.*]] = tail call ptr @copy_rtx_if_shared(ptr noundef [[I16]])
; CHECK-NEXT:    store ptr [[CALL73]], ptr [[ARRAYIDX72]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[FOR_INC119]]
; CHECK:       [[SW_BB77]]:
; CHECK-NEXT:    [[ARRAYIDX80:%.*]] = getelementptr inbounds [[STRUCT_RTX_DEF]], ptr [[X_0]], i64 0, i32 1, i64 [[INDVARS_IV54]]
; CHECK-NEXT:    [[I17:%.*]] = load ptr, ptr [[ARRAYIDX80]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CMP81_NOT:%.*]] = icmp eq ptr [[I17]], null
; CHECK-NEXT:    br i1 [[CMP81_NOT]], label %[[FOR_INC119]], label %[[IF_THEN83:.*]]
; CHECK:       [[IF_THEN83]]:
; CHECK-NEXT:    [[I18:%.*]] = load i32, ptr [[I17]], align 8, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CMP89:%.*]] = icmp sgt i32 [[I18]], 0
; CHECK-NEXT:    br i1 [[CMP89]], label %[[FOR_BODY_PREHEADER_I:.*]], label %[[IF_END99:.*]]
; CHECK:       [[FOR_BODY_PREHEADER_I]]:
; CHECK-NEXT:    [[ELEM:%.*]] = getelementptr [[STRUCT_RTVEC_DEF]], ptr [[I17]], i64 0, i32 1
; CHECK-NEXT:    [[CALL_I:%.*]] = tail call ptr @rtvec_alloc(i32 noundef signext [[I18]])
; CHECK-NEXT:    [[WIDE_TRIP_COUNT_I:%.*]] = zext nneg i32 [[I18]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY_I:.*]]
; CHECK:       [[FOR_BODY_I]]:
; CHECK-NEXT:    [[INDVARS_IV_I:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER_I]] ], [ [[INDVARS_IV_NEXT_I:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[ARGP_ADDR_07_I:%.*]] = phi ptr [ [[ELEM]], %[[FOR_BODY_PREHEADER_I]] ], [ [[INCDEC_PTR_I:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[INCDEC_PTR_I]] = getelementptr inbounds ptr, ptr [[ARGP_ADDR_07_I]], i64 1
; CHECK-NEXT:    [[I19:%.*]] = load ptr, ptr [[ARGP_ADDR_07_I]], align 8, !tbaa [[TBAA10]]
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds [[STRUCT_RTVEC_DEF]], ptr [[CALL_I]], i64 0, i32 1, i64 [[INDVARS_IV_I]]
; CHECK-NEXT:    store ptr [[I19]], ptr [[ARRAYIDX_I]], align 8, !tbaa [[TBAA10]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I]] = add nuw nsw i64 [[INDVARS_IV_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT_I]], [[WIDE_TRIP_COUNT_I]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label %[[GEN_RTVEC_V_EXIT:.*]], label %[[FOR_BODY_I]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[GEN_RTVEC_V_EXIT]]:
; CHECK-NEXT:    store ptr [[CALL_I]], ptr [[ARRAYIDX80]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    br label %[[IF_END99]]
; CHECK:       [[IF_END99]]:
; CHECK-NEXT:    br i1 [[CMP89]], label %[[FOR_BODY103_PREHEADER:.*]], label %[[FOR_INC119]]
; CHECK:       [[FOR_BODY103_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[I18]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY103:.*]]
; CHECK:       [[FOR_BODY103]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[FOR_BODY103_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY103]] ]
; CHECK-NEXT:    [[I20:%.*]] = load ptr, ptr [[ARRAYIDX80]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX109:%.*]] = getelementptr inbounds [[STRUCT_RTVEC_DEF]], ptr [[I20]], i64 0, i32 1, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[I21:%.*]] = load ptr, ptr [[ARRAYIDX109]], align 8, !tbaa [[TBAA10]]
; CHECK-NEXT:    [[CALL110:%.*]] = tail call ptr @copy_rtx_if_shared(ptr noundef [[I21]])
; CHECK-NEXT:    [[I22:%.*]] = load ptr, ptr [[ARRAYIDX80]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[ARRAYIDX116:%.*]] = getelementptr inbounds [[STRUCT_RTVEC_DEF]], ptr [[I22]], i64 0, i32 1, i64 [[INDVARS_IV]]
; CHECK-NEXT:    store ptr [[CALL110]], ptr [[ARRAYIDX116]], align 8, !tbaa [[TBAA10]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[FOR_BODY103]], label %[[FOR_INC119_LOOPEXIT:.*]], !llvm.loop [[LOOP11]]
; CHECK:       [[FOR_INC119_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_INC119]]
; CHECK:       [[FOR_INC119]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT55]] = add nuw nsw i64 [[INDVARS_IV54]], 1
; CHECK-NEXT:    [[EXITCOND58:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT55]], [[WIDE_TRIP_COUNT57]]
; CHECK-NEXT:    br i1 [[EXITCOND58]], label %[[FOR_BODY]], label %[[CLEANUP_LOOPEXIT52:.*]], !llvm.loop [[LOOP13]]
; CHECK:       [[CLEANUP_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP_LOOPEXIT52]]:
; CHECK-NEXT:    br label %[[CLEANUP]]
; CHECK:       [[CLEANUP]]:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi ptr [ null, %[[ENTRY]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[LAND_LHS_TRUE12]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[IF_END]] ], [ [[ORIG]], %[[SW_BB23]] ], [ [[ORIG]], %[[SW_BB23]] ], [ [[ORIG]], %[[SW_BB23]] ], [ [[ORIG]], %[[SW_BB23]] ], [ [[ORIG]], %[[SW_BB23]] ], [ [[X_0]], %[[IF_END58]] ], [ [[X_0]], %[[CLEANUP_LOOPEXIT]] ], [ [[X_0]], %[[CLEANUP_LOOPEXIT52]] ]
; CHECK-NEXT:    ret ptr [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %orig, null
  br i1 %cmp, label %cleanup, label %if.end

if.end:                                           ; preds = %entry
  %bf.load = load i32, ptr %orig, align 8
  %bf.clear = and i32 %bf.load, 65535
  %trunc = trunc i32 %bf.load to i16
  switch i16 %trunc, label %sw.epilog [
  i16 61, label %cleanup
  i16 71, label %cleanup
  i16 54, label %cleanup
  i16 55, label %cleanup
  i16 56, label %cleanup
  i16 68, label %cleanup
  i16 36, label %cleanup
  i16 59, label %cleanup
  i16 69, label %cleanup
  i16 62, label %cleanup
  i16 58, label %sw.bb1
  i16 32, label %cleanup
  i16 33, label %cleanup
  i16 34, label %cleanup
  i16 37, label %cleanup
  i16 35, label %cleanup
  i16 66, label %sw.bb23
  ]

sw.bb1:                                           ; preds = %if.end
  %fld = getelementptr inbounds nuw %struct.rtx_def, ptr %orig, i64 0, i32 1
  %i = load ptr, ptr %fld, align 8, !tbaa !0
  %bf.load2 = load i32, ptr %i, align 8
  %bf.clear3 = and i32 %bf.load2, 65535
  %cmp4 = icmp eq i32 %bf.clear3, 75
  br i1 %cmp4, label %land.lhs.true, label %sw.epilog

land.lhs.true:                                    ; preds = %sw.bb1
  %fld7 = getelementptr inbounds nuw %struct.rtx_def, ptr %i, i64 0, i32 1
  %i1 = load ptr, ptr %fld7, align 8, !tbaa !0
  %bf.load9 = load i32, ptr %i1, align 8
  %bf.clear10 = and i32 %bf.load9, 65535
  %cmp11 = icmp eq i32 %bf.clear10, 68
  br i1 %cmp11, label %land.lhs.true12, label %sw.epilog

land.lhs.true12:                                  ; preds = %land.lhs.true
  %arrayidx16 = getelementptr inbounds %struct.rtx_def, ptr %i, i64 1
  %i2 = load ptr, ptr %arrayidx16, align 8, !tbaa !0
  %bf.load17 = load i32, ptr %i2, align 8
  %bf.clear18 = and i32 %bf.load17, 65535
  %cmp19 = icmp eq i32 %bf.clear18, 54
  br i1 %cmp19, label %cleanup, label %sw.epilog

sw.bb23:                                          ; preds = %if.end
  %fld24 = getelementptr inbounds nuw %struct.rtx_def, ptr %orig, i64 0, i32 1
  %i3 = load ptr, ptr %fld24, align 8, !tbaa !0
  %bf.load26 = load i32, ptr %i3, align 8
  %trunc46 = trunc i32 %bf.load26 to i16
  switch i16 %trunc46, label %sw.epilog [
  i16 67, label %cleanup
  i16 68, label %cleanup
  i16 54, label %cleanup
  i16 58, label %cleanup
  i16 55, label %cleanup
  ]

sw.epilog:                                        ; preds = %sw.bb23, %land.lhs.true12, %land.lhs.true, %sw.bb1, %if.end
  %i4 = and i32 %bf.load, 536870912
  %tobool.not.not = icmp eq i32 %i4, 0
  br i1 %tobool.not.not, label %if.end58, label %if.then56

if.then56:                                        ; preds = %sw.epilog
  %call = tail call ptr @rtx_alloc(i32 noundef signext %bf.clear)
  %idxprom = zext nneg i32 %bf.clear to i64
  %arrayidx57 = getelementptr inbounds [153 x i8], ptr @rtx_length, i64 0, i64 %idxprom
  %i5 = load i8, ptr %arrayidx57, align 1, !tbaa !3
  %conv = zext i8 %i5 to i64
  %mul = shl nuw nsw i64 %conv, 3
  %add = add nuw nsw i64 %mul, 8
  tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(1) %call, ptr noundef nonnull align 8 dereferenceable(1) %orig, i64 %add, i1 false)
  br label %if.end58

if.end58:                                         ; preds = %if.then56, %sw.epilog
  %x.0 = phi ptr [ %call, %if.then56 ], [ %orig, %sw.epilog ]
  %bf.load59 = load i32, ptr %x.0, align 8
  %bf.set = or i32 %bf.load59, 536870912
  store i32 %bf.set, ptr %x.0, align 8
  %idxprom61 = zext nneg i32 %bf.clear to i64
  %arrayidx64 = getelementptr inbounds [153 x i8], ptr @rtx_length, i64 0, i64 %idxprom61
  %i6 = load i8, ptr %arrayidx64, align 1, !tbaa !3
  %conv65 = zext i8 %i6 to i32
  %cmp6649.not = icmp eq i8 %i6, 0
  br i1 %cmp6649.not, label %cleanup, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %if.end58
  %arrayidx62 = getelementptr inbounds [153 x ptr], ptr @rtx_format, i64 0, i64 %idxprom61
  %i7 = load ptr, ptr %arrayidx62, align 8, !tbaa !4
  br i1 %tobool.not.not, label %for.body.us.preheader, label %for.body.preheader

for.body.preheader:                               ; preds = %for.body.lr.ph
  %wide.trip.count57 = zext i32 %conv65 to i64
  br label %for.body

for.body.us.preheader:                            ; preds = %for.body.lr.ph
  %wide.trip.count67 = zext i32 %conv65 to i64
  br label %for.body.us

for.body.us:                                      ; preds = %for.inc119.us, %for.body.us.preheader
  %indvars.iv64 = phi i64 [ 0, %for.body.us.preheader ], [ %indvars.iv.next65, %for.inc119.us ]
  %format_ptr.051.us = phi ptr [ %incdec.ptr.us, %for.inc119.us ], [ %i7, %for.body.us.preheader ]
  %incdec.ptr.us = getelementptr inbounds i8, ptr %format_ptr.051.us, i64 1
  %i8 = load i8, ptr %format_ptr.051.us, align 1, !tbaa !3
  switch i8 %i8, label %for.inc119.us [
  i8 101, label %sw.bb69.us
  i8 69, label %sw.bb77.us
  ]

sw.bb77.us:                                       ; preds = %for.body.us
  %arrayidx80.us = getelementptr inbounds %struct.rtx_def, ptr %x.0, i64 0, i32 1, i64 %indvars.iv64
  %i9 = load ptr, ptr %arrayidx80.us, align 8, !tbaa !0
  %cmp81.not.us = icmp eq ptr %i9, null
  br i1 %cmp81.not.us, label %for.inc119.us, label %if.then83.us

if.then83.us:                                     ; preds = %sw.bb77.us
  %i10 = load i32, ptr %i9, align 8, !tbaa !6
  %cmp10147.us = icmp sgt i32 %i10, 0
  br i1 %cmp10147.us, label %for.body103.us.preheader, label %for.inc119.us

for.body103.us.preheader:                         ; preds = %if.then83.us
  %wide.trip.count62 = zext i32 %i10 to i64
  br label %for.body103.us

for.body103.us:                                   ; preds = %for.body103.us, %for.body103.us.preheader
  %indvars.iv59 = phi i64 [ 0, %for.body103.us.preheader ], [ %indvars.iv.next60, %for.body103.us ]
  %i11 = load ptr, ptr %arrayidx80.us, align 8, !tbaa !0
  %arrayidx109.us = getelementptr inbounds %struct.rtvec_def, ptr %i11, i64 0, i32 1, i64 %indvars.iv59
  %i12 = load ptr, ptr %arrayidx109.us, align 8, !tbaa !10
  %call110.us = tail call ptr @copy_rtx_if_shared(ptr noundef %i12)
  %i13 = load ptr, ptr %arrayidx80.us, align 8, !tbaa !0
  %arrayidx116.us = getelementptr inbounds %struct.rtvec_def, ptr %i13, i64 0, i32 1, i64 %indvars.iv59
  store ptr %call110.us, ptr %arrayidx116.us, align 8, !tbaa !10
  %indvars.iv.next60 = add nuw nsw i64 %indvars.iv59, 1
  %exitcond63 = icmp ne i64 %indvars.iv.next60, %wide.trip.count62
  br i1 %exitcond63, label %for.body103.us, label %for.inc119.us.loopexit, !llvm.loop !11

sw.bb69.us:                                       ; preds = %for.body.us
  %arrayidx72.us = getelementptr inbounds %struct.rtx_def, ptr %x.0, i64 0, i32 1, i64 %indvars.iv64
  %i14 = load ptr, ptr %arrayidx72.us, align 8, !tbaa !0
  %call73.us = tail call ptr @copy_rtx_if_shared(ptr noundef %i14)
  store ptr %call73.us, ptr %arrayidx72.us, align 8, !tbaa !0
  br label %for.inc119.us

for.inc119.us.loopexit:                           ; preds = %for.body103.us
  br label %for.inc119.us

for.inc119.us:                                    ; preds = %for.inc119.us.loopexit, %sw.bb69.us, %if.then83.us, %sw.bb77.us, %for.body.us
  %indvars.iv.next65 = add nuw nsw i64 %indvars.iv64, 1
  %exitcond68 = icmp ne i64 %indvars.iv.next65, %wide.trip.count67
  br i1 %exitcond68, label %for.body.us, label %cleanup.loopexit, !llvm.loop !13

for.body:                                         ; preds = %for.inc119, %for.body.preheader
  %indvars.iv54 = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next55, %for.inc119 ]
  %format_ptr.051 = phi ptr [ %incdec.ptr, %for.inc119 ], [ %i7, %for.body.preheader ]
  %incdec.ptr = getelementptr inbounds i8, ptr %format_ptr.051, i64 1
  %i15 = load i8, ptr %format_ptr.051, align 1, !tbaa !3
  switch i8 %i15, label %for.inc119 [
  i8 101, label %sw.bb69
  i8 69, label %sw.bb77
  ]

sw.bb69:                                          ; preds = %for.body
  %arrayidx72 = getelementptr inbounds %struct.rtx_def, ptr %x.0, i64 0, i32 1, i64 %indvars.iv54
  %i16 = load ptr, ptr %arrayidx72, align 8, !tbaa !0
  %call73 = tail call ptr @copy_rtx_if_shared(ptr noundef %i16)
  store ptr %call73, ptr %arrayidx72, align 8, !tbaa !0
  br label %for.inc119

sw.bb77:                                          ; preds = %for.body
  %arrayidx80 = getelementptr inbounds %struct.rtx_def, ptr %x.0, i64 0, i32 1, i64 %indvars.iv54
  %i17 = load ptr, ptr %arrayidx80, align 8, !tbaa !0
  %cmp81.not = icmp eq ptr %i17, null
  br i1 %cmp81.not, label %for.inc119, label %if.then83

if.then83:                                        ; preds = %sw.bb77
  %i18 = load i32, ptr %i17, align 8, !tbaa !6
  %cmp89 = icmp sgt i32 %i18, 0
  br i1 %cmp89, label %for.body.preheader.i, label %if.end99

for.body.preheader.i:                             ; preds = %if.then83
  %elem = getelementptr %struct.rtvec_def, ptr %i17, i64 0, i32 1
  %call.i = tail call ptr @rtvec_alloc(i32 noundef signext %i18)
  %wide.trip.count.i = zext nneg i32 %i18 to i64
  br label %for.body.i

for.body.i:                                       ; preds = %for.body.i, %for.body.preheader.i
  %indvars.iv.i = phi i64 [ 0, %for.body.preheader.i ], [ %indvars.iv.next.i, %for.body.i ]
  %argp.addr.07.i = phi ptr [ %elem, %for.body.preheader.i ], [ %incdec.ptr.i, %for.body.i ]
  %incdec.ptr.i = getelementptr inbounds ptr, ptr %argp.addr.07.i, i64 1
  %i19 = load ptr, ptr %argp.addr.07.i, align 8, !tbaa !10
  %arrayidx.i = getelementptr inbounds %struct.rtvec_def, ptr %call.i, i64 0, i32 1, i64 %indvars.iv.i
  store ptr %i19, ptr %arrayidx.i, align 8, !tbaa !10
  %indvars.iv.next.i = add nuw nsw i64 %indvars.iv.i, 1
  %exitcond.not.i = icmp eq i64 %indvars.iv.next.i, %wide.trip.count.i
  br i1 %exitcond.not.i, label %gen_rtvec_v.exit, label %for.body.i, !llvm.loop !14

gen_rtvec_v.exit:                                 ; preds = %for.body.i
  store ptr %call.i, ptr %arrayidx80, align 8, !tbaa !0
  br label %if.end99

if.end99:                                         ; preds = %gen_rtvec_v.exit, %if.then83
  %cmp10147 = icmp sgt i32 %i18, 0
  br i1 %cmp10147, label %for.body103.preheader, label %for.inc119

for.body103.preheader:                            ; preds = %if.end99
  %wide.trip.count = zext i32 %i18 to i64
  br label %for.body103

for.body103:                                      ; preds = %for.body103, %for.body103.preheader
  %indvars.iv = phi i64 [ 0, %for.body103.preheader ], [ %indvars.iv.next, %for.body103 ]
  %i20 = load ptr, ptr %arrayidx80, align 8, !tbaa !0
  %arrayidx109 = getelementptr inbounds %struct.rtvec_def, ptr %i20, i64 0, i32 1, i64 %indvars.iv
  %i21 = load ptr, ptr %arrayidx109, align 8, !tbaa !10
  %call110 = tail call ptr @copy_rtx_if_shared(ptr noundef %i21)
  %i22 = load ptr, ptr %arrayidx80, align 8, !tbaa !0
  %arrayidx116 = getelementptr inbounds %struct.rtvec_def, ptr %i22, i64 0, i32 1, i64 %indvars.iv
  store ptr %call110, ptr %arrayidx116, align 8, !tbaa !10
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond = icmp ne i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond, label %for.body103, label %for.inc119.loopexit, !llvm.loop !11

for.inc119.loopexit:                              ; preds = %for.body103
  br label %for.inc119

for.inc119:                                       ; preds = %for.inc119.loopexit, %if.end99, %sw.bb77, %sw.bb69, %for.body
  %indvars.iv.next55 = add nuw nsw i64 %indvars.iv54, 1
  %exitcond58 = icmp ne i64 %indvars.iv.next55, %wide.trip.count57
  br i1 %exitcond58, label %for.body, label %cleanup.loopexit52, !llvm.loop !13

cleanup.loopexit:                                 ; preds = %for.inc119.us
  br label %cleanup

cleanup.loopexit52:                               ; preds = %for.inc119
  br label %cleanup

cleanup:                                          ; preds = %cleanup.loopexit52, %cleanup.loopexit, %if.end58, %sw.bb23, %sw.bb23, %sw.bb23, %sw.bb23, %sw.bb23, %land.lhs.true12, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %if.end, %entry
  %retval.0 = phi ptr [ null, %entry ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %land.lhs.true12 ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %if.end ], [ %orig, %sw.bb23 ], [ %orig, %sw.bb23 ], [ %orig, %sw.bb23 ], [ %orig, %sw.bb23 ], [ %orig, %sw.bb23 ], [ %x.0, %if.end58 ], [ %x.0, %cleanup.loopexit ], [ %x.0, %cleanup.loopexit52 ]
  ret ptr %retval.0
}

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }

!0 = !{!1, !1, i64 0, i64 0}
!1 = !{!2, i64 1, !"omnipotent char"}
!2 = !{!"Simple C/C++ TBAA"}
!3 = !{!1, !1, i64 0, i64 1}
!4 = !{!5, !5, i64 0, i64 8}
!5 = !{!1, i64 8, !"any pointer"}
!6 = !{!7, !8, i64 0, i64 4}
!7 = !{!1, i64 16, !"rtvec_def", !8, i64 0, i64 4, !9, i64 8, i64 8}
!8 = !{!1, i64 4, !"int"}
!9 = !{!5, i64 8, !"p1 struct rtx_def"}
!10 = !{!9, !9, i64 0, i64 8}
!11 = distinct !{!11, !12}
!12 = !{!"llvm.loop.mustprogress"}
!13 = distinct !{!13, !12}
!14 = distinct !{!14, !12}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0, i64 0}
; CHECK: [[META1]] = !{[[META2:![0-9]+]], i64 1, !"omnipotent char"}
; CHECK: [[META2]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[TBAA3]] = !{[[META1]], [[META1]], i64 0, i64 1}
; CHECK: [[TBAA4]] = !{[[META5:![0-9]+]], [[META5]], i64 0, i64 8}
; CHECK: [[META5]] = !{[[META1]], i64 8, !"any pointer"}
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META8:![0-9]+]], i64 0, i64 4}
; CHECK: [[META7]] = !{[[META1]], i64 16, !"rtvec_def", [[META8]], i64 0, i64 4, [[META9:![0-9]+]], i64 8, i64 8}
; CHECK: [[META8]] = !{[[META1]], i64 4, !"int"}
; CHECK: [[META9]] = !{[[META5]], i64 8, !"p1 struct rtx_def"}
; CHECK: [[TBAA10]] = !{[[META9]], [[META9]], i64 0, i64 8}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META12:![0-9]+]]}
; CHECK: [[META12]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META12]]}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META12]]}
;.
