; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=aggressive-instcombine -S %s | FileCheck %s

define i8 @blend(i8 %0, i8 %1, i8 %2) {
; CHECK-LABEL: @blend(
; CHECK-NEXT:    [[TMP4:%.*]] = zext i8 [[TMP2:%.*]] to i16
; CHECK-NEXT:    [[TMP5:%.*]] = xor i16 [[TMP4]], 255
; CHECK-NEXT:    [[TMP6:%.*]] = zext i8 [[TMP0:%.*]] to i16
; CHECK-NEXT:    [[TMP9:%.*]] = mul i16 [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = zext i8 [[TMP1:%.*]] to i16
; CHECK-NEXT:    [[TMP7:%.*]] = mul i16 [[TMP5]], [[TMP8]]
; CHECK-NEXT:    [[TMP10:%.*]] = add i16 [[TMP7]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = udiv i16 [[TMP10]], 255
; CHECK-NEXT:    [[TMP12:%.*]] = trunc i16 [[TMP11]] to i8
; CHECK-NEXT:    ret i8 [[TMP12]]
;
  %4 = zext i8 %2 to i32
  %5 = xor i32 %4, 255
  %6 = zext i8 %0 to i32
  %7 = mul i32 %4, %6
  %8 = zext i8 %1 to i32
  %9 = mul i32 %5, %8
  %10 = add i32 %9, %7
  %11 = udiv i32 %10, 255
  %12 = trunc i32 %11 to i8
  ret i8 %12
}
