// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +xsfsci -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV32
// RUN: %clang_cc1 -triple riscv64 -target-feature +xsfsci -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV64

#include <sifive_sci.h>
#include <stdint.h>

#if __riscv_xlen == 32
// RV32-LABEL: @test__riscv_sf_sci_x_xx_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sf.sci.3.r.x.xx.i32(i32 0, i32 127, i32 [[X:%.*]], i32 [[Y:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test__riscv_sf_sci_x_xx_32(uint32_t x, uint32_t y) {
  return __riscv_sf_sci_x_xx_32(0, 127, x, y);
}

// RV32-LABEL: @test__riscv_sf_sci_x_xx_se_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sf.sci.3.r.x.xx.se.i32(i32 0, i32 127, i32 [[X:%.*]], i32 [[Y:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test__riscv_sf_sci_x_xx_se_32(uint32_t x, uint32_t y) {
  return __riscv_sf_sci_x_xx_se_32(0, 127, x, y);
}

// RV32-LABEL: @test__riscv_sf_sci_xx_se_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    call void @llvm.riscv.sf.sci.3.r.xx.se.i32(i32 0, i32 127, i32 [[X:%.*]], i32 [[Y:%.*]])
// RV32-NEXT:    ret void
//
void test__riscv_sf_sci_xx_se_32(uint32_t x, uint32_t y) {
  __riscv_sf_sci_xx_se_32(0, 127, x, y);
}

// RV32-LABEL: @test__riscv_sf_sci_3_r_x_xx_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sf.sci.3.r.x.xx.i32(i32 0, i32 127, i32 [[X:%.*]], i32 [[Y:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test__riscv_sf_sci_3_r_x_xx_32(uint32_t x, uint32_t y) {
  return __riscv_sf_sci_3_r_x_xx_32(0, 127, x, y);
}

// RV32-LABEL: @test__riscv_sf_sci_3_r_x_xx_se_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sf.sci.3.r.x.xx.se.i32(i32 0, i32 127, i32 [[X:%.*]], i32 [[Y:%.*]])
// RV32-NEXT:    ret i32 [[TMP0]]
//
uint32_t test__riscv_sf_sci_3_r_x_xx_se_32(uint32_t x, uint32_t y) {
  return __riscv_sf_sci_3_r_x_xx_se_32(0, 127, x, y);
}

// RV32-LABEL: @test__riscv_sf_sci_3_r_xx_se_32(
// RV32-NEXT:  entry:
// RV32-NEXT:    call void @llvm.riscv.sf.sci.3.r.xx.se.i32(i32 0, i32 127, i32 [[X:%.*]], i32 [[Y:%.*]])
// RV32-NEXT:    ret void
//
void test__riscv_sf_sci_3_r_xx_se_32(uint32_t x, uint32_t y) {
  __riscv_sf_sci_3_r_xx_se_32(0, 127, x, y);
}
#endif

#if __riscv_xlen == 64
// RV64-LABEL: @test__riscv_sf_sci_x_xx_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sf.sci.3.r.x.xx.i64(i32 0, i32 127, i64 [[X:%.*]], i64 [[Y:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test__riscv_sf_sci_x_xx_64(uint64_t x, uint64_t y) {
  return __riscv_sf_sci_x_xx_64(0, 127, x, y);
}

// RV64-LABEL: @test__riscv_sf_sci_x_xx_se_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sf.sci.3.r.x.xx.se.i64(i32 0, i32 127, i64 [[X:%.*]], i64 [[Y:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test__riscv_sf_sci_x_xx_se_64(uint64_t x, uint64_t y) {
  return __riscv_sf_sci_x_xx_se_64(0, 127, x, y);
}

// RV64-LABEL: @test__riscv_sf_sci_xx_se_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    call void @llvm.riscv.sf.sci.3.r.xx.se.i64(i32 0, i32 127, i64 [[X:%.*]], i64 [[Y:%.*]])
// RV64-NEXT:    ret void
//
void test__riscv_sf_sci_xx_se_64(uint64_t x, uint64_t y) {
  __riscv_sf_sci_xx_se_64(0, 127, x, y);
}

// RV64-LABEL: @test__riscv_sf_sci_3_r_x_xx_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sf.sci.3.r.x.xx.i64(i32 0, i32 127, i64 [[X:%.*]], i64 [[Y:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test__riscv_sf_sci_3_r_x_xx_64(uint64_t x, uint64_t y) {
  return __riscv_sf_sci_3_r_x_xx_64(0, 127, x, y);
}

// RV64-LABEL: @test__riscv_sf_sci_3_r_x_xx_se_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.sf.sci.3.r.x.xx.se.i64(i32 0, i32 127, i64 [[X:%.*]], i64 [[Y:%.*]])
// RV64-NEXT:    ret i64 [[TMP0]]
//
uint64_t test__riscv_sf_sci_3_r_x_xx_se_64(uint64_t x, uint64_t y) {
  return __riscv_sf_sci_3_r_x_xx_se_64(0, 127, x, y);
}

// RV64-LABEL: @test__riscv_sf_sci_3_r_xx_se_64(
// RV64-NEXT:  entry:
// RV64-NEXT:    call void @llvm.riscv.sf.sci.3.r.xx.se.i64(i32 0, i32 127, i64 [[X:%.*]], i64 [[Y:%.*]])
// RV64-NEXT:    ret void
//
void test__riscv_sf_sci_3_r_xx_se_64(uint64_t x, uint64_t y) {
  __riscv_sf_sci_3_r_xx_se_64(0, 127, x, y);
}
#endif
