// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang -target riscv64 -march=rv64gc_zfh -msifive-recode=neon -Xclang -target-feature -Xclang +fullfp16 -Xclang -disable-O0-optnone -S -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck %s

#include<arm_fp16.h>

// CHECK-LABEL: @test_vcvtah_s16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.round.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptosi.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtah_s16_f16(float16_t in_0, int16_t *out)
{
out[0] = vcvtah_s16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtah_u16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.round.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptoui.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtah_u16_f16(float16_t in_0, uint16_t *out)
{
out[0] = vcvtah_u16_f16(in_0);
}

// CHECK-LABEL: @test_vcvth_s16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call i16 @llvm.fptosi.sat.i16.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP4]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvth_s16_f16(float16_t in_0, int16_t *out)
{
out[0] = vcvth_s16_f16(in_0);
}

// CHECK-LABEL: @test_vcvth_u16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call i16 @llvm.fptoui.sat.i16.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP4]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvth_u16_f16(float16_t in_0, uint16_t *out)
{
out[0] = vcvth_u16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtmh_s16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.floor.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptosi.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtmh_s16_f16(float16_t in_0, int16_t *out)
{
out[0] = vcvtmh_s16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtmh_u16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.floor.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptoui.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtmh_u16_f16(float16_t in_0, uint16_t *out)
{
out[0] = vcvtmh_u16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtnh_s16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.roundeven.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptosi.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtnh_s16_f16(float16_t in_0, int16_t *out)
{
out[0] = vcvtnh_s16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtnh_u16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.roundeven.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptoui.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtnh_u16_f16(float16_t in_0, uint16_t *out)
{
out[0] = vcvtnh_u16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtph_s16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.ceil.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptosi.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtph_s16_f16(float16_t in_0, int16_t *out)
{
out[0] = vcvtph_s16_f16(in_0);
}

// CHECK-LABEL: @test_vcvtph_u16_f16(
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.ceil.f16(half [[TMP0:%.*]])
// CHECK-NEXT:    [[TMP4:%.*]] = call i16 @llvm.fptoui.sat.i16.f16(half [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[TMP1:%.*]], i64 0
// CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP5]], align 2
// CHECK-NEXT:    ret void
//
void test_vcvtph_u16_f16(float16_t in_0, uint16_t *out)
{
out[0] = vcvtph_u16_f16(in_0);
}
