; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -passes="simplifycfg,instcombine<no-verify-fixpoint>" -preprocess-for-select -simplifycfg-require-and-preserve-domtree=1 -S | FileCheck %s

define i32 @test(ptr %arc, i32 %red_cost) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP2_NOT:%.*]] = icmp eq i32 [[RED_COST:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP2_NOT]], label [[IF_END:%.*]], label [[ELSE_IF:%.*]]
; CHECK:       else.if:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[RED_COST]], 0
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[CMP]], i32 1, i32 2
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARC:%.*]], i64 8
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ne i32 [[TMP0]], [[SPEC_SELECT]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ false, [[ENTRY:%.*]] ], [ [[CMP1]], [[ELSE_IF]] ]
; CHECK-NEXT:    [[RES:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  %cmp = icmp slt i32 %red_cost, 0
  br i1 %cmp, label %then, label %else.if

else.if:
  %cmp2 = icmp ne i32 %red_cost, 0
  br i1 %cmp2, label %then, label %if.end

then:
  %.sink8 = phi i32 [ 1, %entry ], [ 2, %else.if ]
  %arrayidx = getelementptr inbounds i32, ptr %arc, i64 2
  %0 = load i32, ptr %arrayidx, align 4
  %cmp1 = icmp ne i32 %0, %.sink8
  br label %if.end

if.end:
  %1 = phi i1 [ false, %else.if ], [ %cmp1, %then ]
  %res = zext i1 %1 to i32
  ret i32 %res
}

; Test case %entry branch to %then if its condition is poison.
define i32 @test2(ptr %arc, i32 %red_cost) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 true, label [[ELSE_IF:%.*]], label [[IF_END:%.*]]
; CHECK:       else.if:
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[RED_COST:%.*]], -1
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[CMP]], i32 1, i32 2
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARC:%.*]], i64 8
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ne i32 [[TMP0]], [[SPEC_SELECT]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i1 [ poison, [[ENTRY:%.*]] ], [ [[CMP1]], [[ELSE_IF]] ]
; CHECK-NEXT:    [[RES:%.*]] = zext i1 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  %cmp = icmp slt i32 %red_cost, 0
  br i1 %cmp, label %else.if, label %then

else.if:
  %cmp2 = icmp ne i32 %red_cost, 0
  br i1 %cmp2, label %then, label %if.end

then:
  %.sink8 = phi i32 [ 1, %entry ], [ 2, %else.if ]
  %arrayidx = getelementptr inbounds i32, ptr %arc, i64 2
  %0 = load i32, ptr %arrayidx, align 4
  %cmp1 = icmp ne i32 %0, %.sink8
  br label %if.end

if.end:
  %1 = phi i1 [ false, %else.if ], [ %cmp1, %then ]
  %res = zext i1 %1 to i32
  ret i32 %res
}

; Test case %else.if branch to %then if its condition is false.
define i32 @test3(ptr %arc, i32 %red_cost) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp slt i32 [[RED_COST:%.*]], 1
; CHECK-NEXT:    br i1 [[TMP0]], label [[ELSE_IF:%.*]], label [[IF_END:%.*]]
; CHECK:       else.if:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[RED_COST]], 0
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[CMP]], i32 1, i32 2
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARC:%.*]], i64 8
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ne i32 [[TMP1]], [[SPEC_SELECT]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, [[ENTRY:%.*]] ], [ [[CMP1]], [[ELSE_IF]] ]
; CHECK-NEXT:    [[RES:%.*]] = zext i1 [[TMP2]] to i32
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  %cmp = icmp slt i32 %red_cost, 0
  br i1 %cmp, label %then, label %else.if

else.if:
  %cmp2 = icmp ne i32 %red_cost, 0
  br i1 %cmp2, label %if.end, label %then

then:
  %.sink8 = phi i32 [ 1, %entry ], [ 2, %else.if ]
  %arrayidx = getelementptr inbounds i32, ptr %arc, i64 2
  %0 = load i32, ptr %arrayidx, align 4
  %cmp1 = icmp ne i32 %0, %.sink8
  br label %if.end

if.end:
  %1 = phi i1 [ false, %else.if ], [ %cmp1, %then ]
  %res = zext i1 %1 to i32
  ret i32 %res
}

; Test case %entry and %else.if branch to %then if their conditions is false.
define i32 @test4(ptr %arc, i32 %red_cost) {
; CHECK-LABEL: @test4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp slt i32 [[RED_COST:%.*]], 1
; CHECK-NEXT:    br i1 [[TMP0]], label [[ELSE_IF:%.*]], label [[IF_END:%.*]]
; CHECK:       else.if:
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[RED_COST]], 0
; CHECK-NEXT:    [[SPEC_SELECT:%.*]] = select i1 [[CMP]], i32 1, i32 2
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARC:%.*]], i64 8
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ne i32 [[TMP1]], [[SPEC_SELECT]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, [[ENTRY:%.*]] ], [ [[CMP1]], [[ELSE_IF]] ]
; CHECK-NEXT:    [[RES:%.*]] = zext i1 [[TMP2]] to i32
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  %cmp = icmp sge i32 %red_cost, 0
  br i1 %cmp, label %else.if, label %then

else.if:
  %cmp2 = icmp ne i32 %red_cost, 0
  br i1 %cmp2, label %if.end, label %then

then:
  %.sink8 = phi i32 [ 1, %entry ], [ 2, %else.if ]
  %arrayidx = getelementptr inbounds i32, ptr %arc, i64 2
  %0 = load i32, ptr %arrayidx, align 4
  %cmp1 = icmp ne i32 %0, %.sink8
  br label %if.end

if.end:
  %1 = phi i1 [ false, %else.if ], [ %cmp1, %then ]
  %res = zext i1 %1 to i32
  ret i32 %res
}
