; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=jump-threading -S < %s | FileCheck %s

; We want to thread for.cond and if.end to for.end instead of while.end.

define void @quux(ptr %arg, i64 %arg1, i64 %arg2, ptr %arg3) {
; CHECK-LABEL: define void @quux(
; CHECK-SAME: ptr [[ARG:%.*]], i64 [[ARG1:%.*]], i64 [[ARG2:%.*]], ptr [[ARG3:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr inbounds i8, ptr [[ARG]], i64 [[ARG2]]
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[ARG1]], -1
; CHECK-NEXT:    [[MUL:%.*]] = mul i64 [[ADD]], [[ARG2]]
; CHECK-NEXT:    [[GETELEMENTPTR4:%.*]] = getelementptr inbounds i8, ptr [[ARG]], i64 [[MUL]]
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 0, [[ARG2]]
; CHECK-NEXT:    br label [[FOR_COND:%.*]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[PHI:%.*]] = phi ptr [ [[GETELEMENTPTR]], [[ENTRY:%.*]] ], [ [[GETELEMENTPTR39:%.*]], [[IF_END2:%.*]] ]
; CHECK-NEXT:    [[PHI6:%.*]] = phi ptr [ [[GETELEMENTPTR4]], [[ENTRY]] ], [ [[GETELEMENTPTR40:%.*]], [[IF_END2]] ]
; CHECK-NEXT:    [[PHI7:%.*]] = phi ptr [ [[GETELEMENTPTR]], [[ENTRY]] ], [ [[PHI23:%.*]], [[IF_END2]] ]
; CHECK-NEXT:    [[PHI8:%.*]] = phi ptr [ [[GETELEMENTPTR4]], [[ENTRY]] ], [ [[PHI26:%.*]], [[IF_END2]] ]
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ugt ptr [[PHI]], [[PHI6]]
; CHECK-NEXT:    br i1 [[ICMP]], label [[WHILE_END:%.*]], label [[LAND_RHS:%.*]]
; CHECK:       land.rhs:
; CHECK-NEXT:    [[PHI10:%.*]] = phi ptr [ [[PHI18:%.*]], [[IF_END:%.*]] ], [ [[PHI7]], [[FOR_COND]] ]
; CHECK-NEXT:    [[PHI11:%.*]] = phi ptr [ [[GETELEMENTPTR19:%.*]], [[IF_END]] ], [ [[PHI]], [[FOR_COND]] ]
; CHECK-NEXT:    [[CALL:%.*]] = tail call signext i32 [[ARG3]](ptr [[PHI11]], ptr [[ARG]])
; CHECK-NEXT:    [[ICMP12:%.*]] = icmp slt i32 [[CALL]], 1
; CHECK-NEXT:    br i1 [[ICMP12]], label [[WHILE_BODY:%.*]], label [[WHILE_END]]
; CHECK:       while.body:
; CHECK-NEXT:    [[ICMP14:%.*]] = icmp eq i32 [[CALL]], 0
; CHECK-NEXT:    br i1 [[ICMP14]], label [[IF_THEN:%.*]], label [[IF_END]]
; CHECK:       if.then:
; CHECK-NEXT:    tail call void @spam(ptr [[PHI10]], ptr [[PHI11]])
; CHECK-NEXT:    [[GETELEMENTPTR16:%.*]] = getelementptr inbounds i8, ptr [[PHI10]], i64 [[ARG2]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[PHI18]] = phi ptr [ [[GETELEMENTPTR16]], [[IF_THEN]] ], [ [[PHI10]], [[WHILE_BODY]] ]
; CHECK-NEXT:    [[GETELEMENTPTR19]] = getelementptr inbounds i8, ptr [[PHI11]], i64 [[ARG2]]
; CHECK-NEXT:    [[ICMP20:%.*]] = icmp ugt ptr [[GETELEMENTPTR19]], [[PHI6]]
; CHECK-NEXT:    br i1 [[ICMP20]], label [[WHILE_END]], label [[LAND_RHS]]
; CHECK:       while.end:
; CHECK-NEXT:    [[PHI22:%.*]] = phi ptr [ [[PHI]], [[FOR_COND]] ], [ [[GETELEMENTPTR19]], [[IF_END]] ], [ [[PHI11]], [[LAND_RHS]] ]
; CHECK-NEXT:    [[PHI23]] = phi ptr [ [[PHI7]], [[FOR_COND]] ], [ [[PHI18]], [[IF_END]] ], [ [[PHI10]], [[LAND_RHS]] ]
; CHECK-NEXT:    [[ICMP24:%.*]] = icmp ugt ptr [[PHI22]], [[PHI6]]
; CHECK-NEXT:    br i1 [[ICMP24]], label [[FOR_END:%.*]], label [[LAND_RHS1:%.*]]
; CHECK:       land.rhs1:
; CHECK-NEXT:    [[PHI26]] = phi ptr [ [[PHI35:%.*]], [[IF_END1:%.*]] ], [ [[PHI8]], [[WHILE_END]] ]
; CHECK-NEXT:    [[PHI27:%.*]] = phi ptr [ [[GETELEMENTPTR36:%.*]], [[IF_END1]] ], [ [[PHI6]], [[WHILE_END]] ]
; CHECK-NEXT:    [[CALL28:%.*]] = tail call signext i32 [[ARG3]](ptr [[PHI27]], ptr [[ARG]])
; CHECK-NEXT:    [[ICMP29:%.*]] = icmp sgt i32 [[CALL28]], -1
; CHECK-NEXT:    br i1 [[ICMP29]], label [[WHILE_BODY1:%.*]], label [[IF_END2]]
; CHECK:       while.body1:
; CHECK-NEXT:    [[ICMP31:%.*]] = icmp eq i32 [[CALL28]], 0
; CHECK-NEXT:    br i1 [[ICMP31]], label [[IF_THEN1:%.*]], label [[IF_END1]]
; CHECK:       if.then1:
; CHECK-NEXT:    tail call void @spam(ptr [[PHI27]], ptr [[PHI26]])
; CHECK-NEXT:    [[GETELEMENTPTR33:%.*]] = getelementptr inbounds i8, ptr [[PHI26]], i64 [[SUB]]
; CHECK-NEXT:    br label [[IF_END1]]
; CHECK:       if.end1:
; CHECK-NEXT:    [[PHI35]] = phi ptr [ [[GETELEMENTPTR33]], [[IF_THEN1]] ], [ [[PHI26]], [[WHILE_BODY1]] ]
; CHECK-NEXT:    [[GETELEMENTPTR36]] = getelementptr inbounds i8, ptr [[PHI27]], i64 [[SUB]]
; CHECK-NEXT:    [[ICMP37:%.*]] = icmp ugt ptr [[PHI22]], [[GETELEMENTPTR36]]
; CHECK-NEXT:    br i1 [[ICMP37]], label [[FOR_END]], label [[LAND_RHS1]]
; CHECK:       if.end2:
; CHECK-NEXT:    tail call void @spam(ptr [[PHI22]], ptr [[PHI27]])
; CHECK-NEXT:    [[GETELEMENTPTR39]] = getelementptr inbounds i8, ptr [[PHI22]], i64 [[ARG2]]
; CHECK-NEXT:    [[GETELEMENTPTR40]] = getelementptr inbounds i8, ptr [[PHI27]], i64 [[SUB]]
; CHECK-NEXT:    br label [[FOR_COND]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  %getelementptr = getelementptr inbounds i8, ptr %arg, i64 %arg2
  %add = add i64 %arg1, -1
  %mul = mul i64 %add, %arg2
  %getelementptr4 = getelementptr inbounds i8, ptr %arg, i64 %mul
  %sub = sub i64 0, %arg2
  br label %for.cond

for.cond:                                         ; preds = %if.end2, %entry
  %phi = phi ptr [ %getelementptr, %entry ], [ %getelementptr39, %if.end2 ]
  %phi6 = phi ptr [ %getelementptr4, %entry ], [ %getelementptr40, %if.end2 ]
  %phi7 = phi ptr [ %getelementptr, %entry ], [ %phi23, %if.end2 ]
  %phi8 = phi ptr [ %getelementptr4, %entry ], [ %phi26, %if.end2 ]
  %icmp = icmp ugt ptr %phi, %phi6
  br i1 %icmp, label %while.end, label %land.rhs

land.rhs:                                         ; preds = %if.end, %for.cond
  %phi10 = phi ptr [ %phi18, %if.end ], [ %phi7, %for.cond ]
  %phi11 = phi ptr [ %getelementptr19, %if.end ], [ %phi, %for.cond ]
  %call = tail call signext i32 %arg3(ptr %phi11, ptr %arg)
  %icmp12 = icmp slt i32 %call, 1
  br i1 %icmp12, label %while.body, label %while.end

while.body:                                       ; preds = %land.rhs
  %icmp14 = icmp eq i32 %call, 0
  br i1 %icmp14, label %if.then, label %if.end

if.then:                                          ; preds = %while.body
  tail call void @spam(ptr %phi10, ptr %phi11)
  %getelementptr16 = getelementptr inbounds i8, ptr %phi10, i64 %arg2
  br label %if.end

if.end:                                           ; preds = %if.then, %while.body
  %phi18 = phi ptr [ %getelementptr16, %if.then ], [ %phi10, %while.body ]
  %getelementptr19 = getelementptr inbounds i8, ptr %phi11, i64 %arg2
  %icmp20 = icmp ugt ptr %getelementptr19, %phi6
  br i1 %icmp20, label %while.end, label %land.rhs

while.end:                                        ; preds = %if.end, %land.rhs, %for.cond
  %phi22 = phi ptr [ %phi, %for.cond ], [ %getelementptr19, %if.end ], [ %phi11, %land.rhs ]
  %phi23 = phi ptr [ %phi7, %for.cond ], [ %phi18, %if.end ], [ %phi10, %land.rhs ]
  %icmp24 = icmp ugt ptr %phi22, %phi6
  br i1 %icmp24, label %for.end, label %land.rhs1

land.rhs1:                                        ; preds = %if.end1, %while.end
  %phi26 = phi ptr [ %phi35, %if.end1 ], [ %phi8, %while.end ]
  %phi27 = phi ptr [ %getelementptr36, %if.end1 ], [ %phi6, %while.end ]
  %call28 = tail call signext i32 %arg3(ptr %phi27, ptr %arg)
  %icmp29 = icmp sgt i32 %call28, -1
  br i1 %icmp29, label %while.body1, label %if.end2

while.body1:                                      ; preds = %land.rhs1
  %icmp31 = icmp eq i32 %call28, 0
  br i1 %icmp31, label %if.then1, label %if.end1

if.then1:                                         ; preds = %while.body1
  tail call void @spam(ptr %phi27, ptr %phi26)
  %getelementptr33 = getelementptr inbounds i8, ptr %phi26, i64 %sub
  br label %if.end1

if.end1:                                          ; preds = %if.then1, %while.body1
  %phi35 = phi ptr [ %getelementptr33, %if.then1 ], [ %phi26, %while.body1 ]
  %getelementptr36 = getelementptr inbounds i8, ptr %phi27, i64 %sub
  %icmp37 = icmp ugt ptr %phi22, %getelementptr36
  br i1 %icmp37, label %for.end, label %land.rhs1

if.end2:                                          ; preds = %land.rhs1
  tail call void @spam(ptr %phi22, ptr %phi27)
  %getelementptr39 = getelementptr inbounds i8, ptr %phi22, i64 %arg2
  %getelementptr40 = getelementptr inbounds i8, ptr %phi27, i64 %sub
  br label %for.cond

for.end:                                          ; preds = %if.end1, %while.end
  ret void
}

declare void @spam(ptr, ptr)
