; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -vector-lmul-max=2 -scalable-vectorization=only -riscv-prefer-predicated-vector-ops -prefer-predicate-over-epilogue=predicate-dont-vectorize -gvn -loop-vectorize | FileCheck %s

@FCBUPFMAD = external global ptr
@TotalNumberofBasicUnit = external global i32
@PMADPictureC1 = external global double
@PMADPictureC2 = external global double

define i32 @updateQuantizationParameter(ptr %PMADPictureC1, ptr %FCBUPFMAD, ptr %TotalNumberofBasicUnit, i32 %0, i64 %1, ptr %2, i64 %indvars.iv.next142, ptr %arrayidx804, double %3, double %add806) {
; CHECK-LABEL: @updateQuantizationParameter(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i32 0, label [[IF_END1032:%.*]] [
; CHECK-NEXT:    i32 0, label [[LAND_LHS_TRUE321:%.*]]
; CHECK-NEXT:    ]
; CHECK:       land.lhs.true321:
; CHECK-NEXT:    switch i32 0, label [[IF_END1032]] [
; CHECK-NEXT:    i32 0, label [[IF_THEN535:%.*]]
; CHECK-NEXT:    ]
; CHECK:       if.then535:
; CHECK-NEXT:    br i1 true, label [[FOR_BODY_PREHEADER:%.*]], label [[IF_THEN535_IF_END831_CRIT_EDGE:%.*]]
; CHECK:       if.then535.if.end831_crit_edge:
; CHECK-NEXT:    br label [[IF_END831:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP4:%.*]] = sext i32 [[TMP0:%.*]] to i64
; CHECK-NEXT:    [[DOTPRE:%.*]] = load double, ptr [[PMADPICTUREC1:%.*]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[TMP1:%.*]], 1
; CHECK-NEXT:    [[SMIN:%.*]] = call i64 @llvm.smin.i64(i64 [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP6:%.*]] = sub i64 [[TMP5]], [[SMIN]]
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], 2
; CHECK-NEXT:    [[TMP9:%.*]] = sub i64 -1, [[TMP6]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ult i64 [[TMP9]], [[TMP8]]
; CHECK-NEXT:    br i1 [[TMP10]], label [[SCALAR_PH:%.*]], label [[VECTOR_MEMCHECK:%.*]]
; CHECK:       vector.memcheck:
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[PMADPICTUREC1]], i64 8
; CHECK-NEXT:    [[UGLYGEP1:%.*]] = getelementptr i8, ptr [[FCBUPFMAD:%.*]], i64 8
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[PMADPICTUREC1]], [[UGLYGEP1]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[FCBUPFMAD]], [[UGLYGEP]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label [[SCALAR_PH]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[IND_END:%.*]] = sub i64 [[TMP1]], [[TMP6]]
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <vscale x 2 x double> zeroinitializer, double [[DOTPRE]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT2:%.*]] = insertelement <vscale x 2 x ptr> poison, ptr [[FCBUPFMAD]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT3:%.*]] = shufflevector <vscale x 2 x ptr> [[BROADCAST_SPLATINSERT2]], <vscale x 2 x ptr> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 2 x double> [ [[TMP11]], [[VECTOR_PH]] ], [ [[VP_OP_SELECT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[INDEX]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP12:%.*]] = call <vscale x 2 x i64> @llvm.experimental.stepvector.nxv2i64()
; CHECK-NEXT:    [[TMP13:%.*]] = add <vscale x 2 x i64> zeroinitializer, [[TMP12]]
; CHECK-NEXT:    [[VEC_IV:%.*]] = add <vscale x 2 x i64> [[BROADCAST_SPLAT]], [[TMP13]]
; CHECK-NEXT:    [[TMP14:%.*]] = sub i64 [[TMP6]], [[INDEX]]
; CHECK-NEXT:    [[TMP15:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[TMP14]], i64 3, i64 1)
; CHECK-NEXT:    [[TMP16:%.*]] = trunc i64 [[TMP15]] to i32
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 2 x double> @llvm.vp.gather.nxv2f64.nxv2p0(<vscale x 2 x ptr> [[BROADCAST_SPLAT3]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call fast <vscale x 2 x double> @llvm.vp.fadd.nxv2f64(<vscale x 2 x double> [[VEC_PHI]], <vscale x 2 x double> [[VP_GATHER]], <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 [[TMP16]])
; CHECK-NEXT:    [[EVL_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[TMP16]], i32 0
; CHECK-NEXT:    [[EVL_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[EVL_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[STEP_VEC:%.*]] = call <vscale x 2 x i32> @llvm.experimental.stepvector.nxv2i32()
; CHECK-NEXT:    [[EVL_MASK:%.*]] = icmp ult <vscale x 2 x i32> [[STEP_VEC]], [[EVL_SPLAT]]
; CHECK-NEXT:    [[VP_OP_SELECT]] = call <vscale x 2 x double> @llvm.vp.merge.nxv2f64(<vscale x 2 x i1> [[EVL_MASK]], <vscale x 2 x double> [[VP_OP]], <vscale x 2 x double> [[VEC_PHI]], i32 [[TMP16]])
; CHECK-NEXT:    [[TMP17:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP18:%.*]] = mul i64 [[TMP17]], 2
; CHECK-NEXT:    [[TMP19:%.*]] = zext i32 [[TMP16]] to i64
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP19]]
; CHECK-NEXT:    [[TMP20:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[TMP6]]
; CHECK-NEXT:    br i1 [[TMP20]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP21:%.*]] = call fast double @llvm.vector.reduce.fadd.nxv2f64(double -0.000000e+00, <vscale x 2 x double> [[VP_OP_SELECT]])
; CHECK-NEXT:    store double [[TMP21]], ptr [[PMADPICTUREC1]], align 8
; CHECK-NEXT:    br i1 true, label [[IF_END831_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[IND_END]], [[MIDDLE_BLOCK]] ], [ [[TMP1]], [[FOR_BODY_PREHEADER]] ], [ [[TMP1]], [[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_MERGE_RDX:%.*]] = phi double [ [[DOTPRE]], [[VECTOR_MEMCHECK]] ], [ [[DOTPRE]], [[FOR_BODY_PREHEADER]] ], [ [[TMP21]], [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[TMP22:%.*]] = phi double [ [[BC_MERGE_RDX]], [[SCALAR_PH]] ], [ [[ADD808:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[INDVARS_IV141:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT1421:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT1421]] = add nsw i64 [[INDVARS_IV141]], -1
; CHECK-NEXT:    [[ARRAYIDX8042:%.*]] = getelementptr inbounds double, ptr [[TMP2:%.*]], i64 [[INDVARS_IV_NEXT142:%.*]]
; CHECK-NEXT:    [[MUL805:%.*]] = fmul fast double [[TMP3:%.*]], [[TMP3]]
; CHECK-NEXT:    [[TMP23:%.*]] = load double, ptr [[FCBUPFMAD]], align 8
; CHECK-NEXT:    [[ADD808]] = fadd fast double [[TMP22]], [[TMP23]]
; CHECK-NEXT:    store double [[ADD808]], ptr [[PMADPICTUREC1]], align 8
; CHECK-NEXT:    [[CMP801_NOT_NOT:%.*]] = icmp sgt i64 [[INDVARS_IV141]], 0
; CHECK-NEXT:    br i1 [[CMP801_NOT_NOT]], label [[FOR_BODY]], label [[IF_END831_LOOPEXIT]], !llvm.loop [[LOOP2:![0-9]+]]
; CHECK:       if.end831.loopexit:
; CHECK-NEXT:    br label [[IF_END831]]
; CHECK:       if.end831:
; CHECK-NEXT:    ret i32 0
; CHECK:       if.end1032:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %if.else312

if.else312:                                       ; preds = %entry
  %4 = load i32, ptr null, align 8
  switch i32 0, label %if.end1032 [
  i32 0, label %land.lhs.true321
  ]

land.lhs.true321:                                 ; preds = %if.else312
  br label %if.else330

if.else330:                                       ; preds = %land.lhs.true321
  switch i32 0, label %if.end1032 [
  i32 0, label %if.then535
  ]

if.then535:                                       ; preds = %if.else330
  br label %if.else588

if.else588:                                       ; preds = %if.then535
  %5 = load double, ptr %PMADPictureC1, align 8
  %6 = load double, ptr null, align 8
  %7 = load i32, ptr undef, align 4
  br label %if.else650

if.else650:                                       ; preds = %if.else588
  br label %if.else784

if.else784:                                       ; preds = %if.else650
  br label %land.lhs.true791

land.lhs.true791:                                 ; preds = %if.else784
  br label %if.then795

if.then795:                                       ; preds = %land.lhs.true791
  %8 = load ptr, ptr %PMADPictureC1, align 8
  %9 = load i32, ptr %PMADPictureC1, align 4
  %cmp801.not.not137 = icmp sgt i32 1, 0
  br i1 true, label %for.body.preheader, label %if.end831

for.body.preheader:                               ; preds = %if.then795
  %10 = sext i32 %0 to i64
  %11 = sext i32 0 to i64
  br label %for.body

for.body:                                         ; preds = %for.body, %for.body.preheader
  %indvars.iv141 = phi i64 [ %1, %for.body.preheader ], [ %indvars.iv.next1421, %for.body ]
  %indvars.iv.next1421 = add nsw i64 %indvars.iv141, -1
  %arrayidx8042 = getelementptr inbounds double, ptr %2, i64 %indvars.iv.next142
  %12 = load double, ptr %PMADPictureC1, align 8
  %mul805 = fmul fast double %3, %3
  %add8063 = fadd fast double %3, 0.000000e+00
  %mul807 = fmul fast double %3, 0.000000e+00
  %13 = load double, ptr %FCBUPFMAD, align 8
  %add808 = fadd fast double %12, %13
  store double %add808, ptr %PMADPictureC1, align 8
  %cmp801.not.not = icmp sgt i64 %indvars.iv141, 0
  br i1 %cmp801.not.not, label %for.body, label %if.end831

if.end831:                                        ; preds = %for.body, %if.then795
  ret i32 0

if.end1032:                                       ; preds = %if.else330, %if.else312
  ret i32 0
}

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare double @llvm.sqrt.f64(double) #0

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare i32 @llvm.smin.i32(i32, i32) #0

; Function Attrs: nocallback nofree nosync nounwind readnone speculatable willreturn
declare i32 @llvm.smax.i32(i32, i32) #0

attributes #0 = { nocallback nofree nosync nounwind readnone speculatable willreturn }
