; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-p550 -target-abi=lp64f \
;RUN:     | FileCheck %s
;RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 -target-abi=lp64f \
;RUN:     -mattr=+lui-addi-fusion | FileCheck %s --check-prefix=PRERA

@.str = private constant [4 x i8] c"%f\0A\00", align 1

define void @food(i32 signext %0, i32 signext %1) {
; CHECK-LABEL: food:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcvt.s.w fa0, a1
; CHECK-NEXT:    lui a0, %hi(.L.str)
; CHECK-NEXT:    addi a0, a0, %lo(.L.str)
; CHECK-NEXT:    tail bar
;
; PRERA-LABEL: food:
; PRERA:       # %bb.0:
; PRERA-NEXT:    fcvt.s.w fa0, a1
; PRERA-NEXT:    lui a0, %hi(.L.str)
; PRERA-NEXT:    addi a0, a0, %lo(.L.str)
; PRERA-NEXT:    tail bar
  %3 = sitofp i32 %1 to float
  tail call void @bar(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str, i64 0, i64 0), float %3)
  ret void
}

declare void @bar(i8*, float)
