; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -mtriple=riscv64 -experimental-riscv-simplifycfg-hoist-call=false -passes=simplifycfg -hoist-common-insts=true %s -S | FileCheck %s --check-prefixes=CHECK-NO-HOIST
; RUN: opt -mtriple=riscv64 -experimental-riscv-simplifycfg-hoist-call=true -passes=simplifycfg -hoist-common-insts=true %s -S | FileCheck %s --check-prefixes=CHECK-HOIST

define i32 @test(i32 %x, i32 %y, i32 %z) {
; CHECK-NO-HOIST-LABEL: define i32 @test
; CHECK-NO-HOIST-SAME: (i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NO-HOIST-NEXT:  entry:
; CHECK-NO-HOIST-NEXT:    [[CALL:%.*]] = call i32 @bar(i32 [[X]], i32 [[Y]])
; CHECK-NO-HOIST-NEXT:    [[CMP:%.*]] = icmp slt i32 [[CALL]], 0
; CHECK-NO-HOIST-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK-NO-HOIST:       if.then:
; CHECK-NO-HOIST-NEXT:    [[CALL1:%.*]] = call i32 @bar(i32 [[Y]], i32 [[Z]])
; CHECK-NO-HOIST-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[CALL1]], 0
; CHECK-NO-HOIST-NEXT:    br i1 [[CMP2]], label [[RETVAL:%.*]], label [[IF_END:%.*]]
; CHECK-NO-HOIST:       if.end:
; CHECK-NO-HOIST-NEXT:    call void @foo(i32 2)
; CHECK-NO-HOIST-NEXT:    br label [[RETVAL]]
; CHECK-NO-HOIST:       if.else:
; CHECK-NO-HOIST-NEXT:    [[CALL4:%.*]] = call i32 @bar(i32 [[Y]], i32 [[Z]])
; CHECK-NO-HOIST-NEXT:    [[CMP5:%.*]] = icmp sgt i32 [[CALL4]], 0
; CHECK-NO-HOIST-NEXT:    br i1 [[CMP5]], label [[IF_THEN6:%.*]], label [[RETVAL]]
; CHECK-NO-HOIST:       if.then6:
; CHECK-NO-HOIST-NEXT:    call void @foo(i32 1)
; CHECK-NO-HOIST-NEXT:    br label [[RETVAL]]
; CHECK-NO-HOIST:       retval:
; CHECK-NO-HOIST-NEXT:    [[RES:%.*]] = phi i32 [ 2, [[IF_END]] ], [ 6, [[IF_THEN6]] ], [ 0, [[IF_THEN]] ], [ 1, [[IF_ELSE]] ]
; CHECK-NO-HOIST-NEXT:    ret i32 [[RES]]
;
; CHECK-HOIST-LABEL: define i32 @test
; CHECK-HOIST-SAME: (i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-HOIST-NEXT:  entry:
; CHECK-HOIST-NEXT:    [[CALL:%.*]] = call i32 @bar(i32 [[X]], i32 [[Y]])
; CHECK-HOIST-NEXT:    [[CMP:%.*]] = icmp slt i32 [[CALL]], 0
; CHECK-HOIST-NEXT:    [[CALL1:%.*]] = call i32 @bar(i32 [[Y]], i32 [[Z]])
; CHECK-HOIST-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[CALL1]], 0
; CHECK-HOIST-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK-HOIST:       if.then:
; CHECK-HOIST-NEXT:    br i1 [[CMP2]], label [[RETVAL:%.*]], label [[IF_END:%.*]]
; CHECK-HOIST:       if.end:
; CHECK-HOIST-NEXT:    call void @foo(i32 2)
; CHECK-HOIST-NEXT:    br label [[RETVAL]]
; CHECK-HOIST:       if.else:
; CHECK-HOIST-NEXT:    br i1 [[CMP2]], label [[IF_THEN6:%.*]], label [[RETVAL]]
; CHECK-HOIST:       if.then6:
; CHECK-HOIST-NEXT:    call void @foo(i32 1)
; CHECK-HOIST-NEXT:    br label [[RETVAL]]
; CHECK-HOIST:       retval:
; CHECK-HOIST-NEXT:    [[RES:%.*]] = phi i32 [ 2, [[IF_END]] ], [ 6, [[IF_THEN6]] ], [ 0, [[IF_THEN]] ], [ 1, [[IF_ELSE]] ]
; CHECK-HOIST-NEXT:    ret i32 [[RES]]
;
entry:
  %call = call i32 @bar(i32 %x, i32 %y)
  %cmp = icmp slt i32 %call, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %call1 = call i32 @bar(i32 %y, i32 %z)
  %cmp2 = icmp sgt i32 %call1, 0
  br i1 %cmp2, label %if.then3, label %if.end

if.then3:                                         ; preds = %if.then
  br label %retval

if.end:                                           ; preds = %if.then
  call void @foo(i32 2)
  br label %retval

if.else:                                          ; preds = %entry
  %call4 = call i32 @bar(i32 %y, i32 %z)
  %cmp5 = icmp sgt i32 %call4, 0
  br i1 %cmp5, label %if.then6, label %if.end7

if.then6:                                         ; preds = %if.else
  call void @foo(i32 1)
  br label %retval

if.end7:                                          ; preds = %if.else
  br label %retval

retval:
  %res = phi i32 [0, %if.then3], [2, %if.end], [6, %if.then6], [1, %if.end7]
  ret i32 %res
}

declare i32 @bar(i32, i32)
declare void @foo(i32)
