; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mcpu=sifive-x280 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,SLOW,X280 %s
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p550 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,SLOW,P550 %s
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p450 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,FAST,P450 %s
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p470 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,FAST,P470 %s
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p650 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,FAST,P650 %s
; RUN: llc -mtriple=riscv64 -mcpu=sifive-p670 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,FAST,P670 %s
; RUN: llc -mtriple=riscv64 -mcpu=sifive-cheetah -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefixes=ALL,FAST,CHEETAH %s

; A collection of cases showing codegen for unaligned loads and stores

define i8 @load_i8(ptr %p) {
; ALL-LABEL: load_i8:
; ALL:       # %bb.0:
; ALL-NEXT:    lbu a0, 0(a0)
; ALL-NEXT:    ret
  %res = load i8, ptr %p, align 1
  ret i8 %res
}

define i16 @load_i16(ptr %p) {
; X280-LABEL: load_i16:
; X280:       # %bb.0:
; X280-NEXT:    lbu a1, 1(a0)
; X280-NEXT:    lbu a0, 0(a0)
; X280-NEXT:    slli a1, a1, 8
; X280-NEXT:    or a0, a0, a1
; X280-NEXT:    ret
;
; P550-LABEL: load_i16:
; P550:       # %bb.0:
; P550-NEXT:    lbu a1, 0(a0)
; P550-NEXT:    lbu a0, 1(a0)
; P550-NEXT:    slli a0, a0, 8
; P550-NEXT:    or a0, a0, a1
; P550-NEXT:    ret
;
; FAST-LABEL: load_i16:
; FAST:       # %bb.0:
; FAST-NEXT:    lh a0, 0(a0)
; FAST-NEXT:    ret
  %res = load i16, ptr %p, align 1
  ret i16 %res
}

define i24 @load_i24(ptr %p) {
; X280-LABEL: load_i24:
; X280:       # %bb.0:
; X280-NEXT:    lbu a1, 0(a0)
; X280-NEXT:    lbu a2, 1(a0)
; X280-NEXT:    lbu a0, 2(a0)
; X280-NEXT:    slli a2, a2, 8
; X280-NEXT:    or a1, a1, a2
; X280-NEXT:    slli a0, a0, 16
; X280-NEXT:    or a0, a0, a1
; X280-NEXT:    ret
;
; P550-LABEL: load_i24:
; P550:       # %bb.0:
; P550-NEXT:    lbu a1, 0(a0)
; P550-NEXT:    lbu a2, 1(a0)
; P550-NEXT:    slli a2, a2, 8
; P550-NEXT:    lbu a0, 2(a0)
; P550-NEXT:    slli a0, a0, 16
; P550-NEXT:    or a1, a1, a2
; P550-NEXT:    or a0, a0, a1
; P550-NEXT:    ret
;
; FAST-LABEL: load_i24:
; FAST:       # %bb.0:
; FAST-NEXT:    lhu a1, 0(a0)
; FAST-NEXT:    lbu a0, 2(a0)
; FAST-NEXT:    slli a0, a0, 16
; FAST-NEXT:    or a0, a0, a1
; FAST-NEXT:    ret
  %res = load i24, ptr %p, align 1
  ret i24 %res
}

define i32 @load_i32(ptr %p) {
; SLOW-LABEL: load_i32:
; SLOW:       # %bb.0:
; SLOW-NEXT:    lbu a1, 0(a0)
; SLOW-NEXT:    lbu a2, 1(a0)
; SLOW-NEXT:    lbu a3, 2(a0)
; SLOW-NEXT:    slli a2, a2, 8
; SLOW-NEXT:    lbu a0, 3(a0)
; SLOW-NEXT:    slli a3, a3, 16
; SLOW-NEXT:    slli a0, a0, 24
; SLOW-NEXT:    or a1, a1, a2
; SLOW-NEXT:    or a0, a0, a3
; SLOW-NEXT:    or a0, a0, a1
; SLOW-NEXT:    ret
;
; FAST-LABEL: load_i32:
; FAST:       # %bb.0:
; FAST-NEXT:    lw a0, 0(a0)
; FAST-NEXT:    ret
  %res = load i32, ptr %p, align 1
  ret i32 %res
}

define i64 @load_i64(ptr %p) {
; X280-LABEL: load_i64:
; X280:       # %bb.0:
; X280-NEXT:    lbu a1, 0(a0)
; X280-NEXT:    lbu a2, 1(a0)
; X280-NEXT:    lbu a6, 2(a0)
; X280-NEXT:    lbu a4, 3(a0)
; X280-NEXT:    slli a2, a2, 8
; X280-NEXT:    lbu a5, 4(a0)
; X280-NEXT:    or a1, a1, a2
; X280-NEXT:    lbu a3, 5(a0)
; X280-NEXT:    slli a6, a6, 16
; X280-NEXT:    lbu a2, 6(a0)
; X280-NEXT:    slli a3, a3, 8
; X280-NEXT:    lbu a0, 7(a0)
; X280-NEXT:    slli a2, a2, 16
; X280-NEXT:    slli a0, a0, 24
; X280-NEXT:    or a3, a3, a5
; X280-NEXT:    or a0, a0, a2
; X280-NEXT:    slli a4, a4, 24
; X280-NEXT:    or a2, a4, a6
; X280-NEXT:    or a0, a0, a3
; X280-NEXT:    or a1, a1, a2
; X280-NEXT:    slli a0, a0, 32
; X280-NEXT:    or a0, a0, a1
; X280-NEXT:    ret
;
; P550-LABEL: load_i64:
; P550:       # %bb.0:
; P550-NEXT:    lbu a1, 0(a0)
; P550-NEXT:    lbu a2, 1(a0)
; P550-NEXT:    lbu a3, 2(a0)
; P550-NEXT:    lbu a4, 3(a0)
; P550-NEXT:    slli a2, a2, 8
; P550-NEXT:    slli a3, a3, 16
; P550-NEXT:    slli a4, a4, 24
; P550-NEXT:    or a1, a1, a2
; P550-NEXT:    or a3, a3, a4
; P550-NEXT:    lbu a2, 4(a0)
; P550-NEXT:    lbu a4, 6(a0)
; P550-NEXT:    or a1, a1, a3
; P550-NEXT:    lbu a3, 5(a0)
; P550-NEXT:    slli a3, a3, 8
; P550-NEXT:    lbu a0, 7(a0)
; P550-NEXT:    slli a4, a4, 16
; P550-NEXT:    slli a0, a0, 24
; P550-NEXT:    or a2, a2, a3
; P550-NEXT:    or a0, a0, a4
; P550-NEXT:    or a0, a0, a2
; P550-NEXT:    slli a0, a0, 32
; P550-NEXT:    or a0, a0, a1
; P550-NEXT:    ret
;
; FAST-LABEL: load_i64:
; FAST:       # %bb.0:
; FAST-NEXT:    ld a0, 0(a0)
; FAST-NEXT:    ret
  %res = load i64, ptr %p, align 1
  ret i64 %res
}

define void @store_i8(ptr %p, i8 %v) {
; ALL-LABEL: store_i8:
; ALL:       # %bb.0:
; ALL-NEXT:    sb a1, 0(a0)
; ALL-NEXT:    ret
  store i8 %v, ptr %p, align 1
  ret void
}

define void @store_i16(ptr %p, i16 %v) {
; SLOW-LABEL: store_i16:
; SLOW:       # %bb.0:
; SLOW-NEXT:    srli a2, a1, 8
; SLOW-NEXT:    sb a1, 0(a0)
; SLOW-NEXT:    sb a2, 1(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: store_i16:
; FAST:       # %bb.0:
; FAST-NEXT:    sh a1, 0(a0)
; FAST-NEXT:    ret
  store i16 %v, ptr %p, align 1
  ret void
}

define void @store_i24(ptr %p, i24 %v) {
; X280-LABEL: store_i24:
; X280:       # %bb.0:
; X280-NEXT:    srli a2, a1, 8
; X280-NEXT:    sb a1, 0(a0)
; X280-NEXT:    srli a1, a1, 16
; X280-NEXT:    sb a2, 1(a0)
; X280-NEXT:    sb a1, 2(a0)
; X280-NEXT:    ret
;
; P550-LABEL: store_i24:
; P550:       # %bb.0:
; P550-NEXT:    srli a2, a1, 8
; P550-NEXT:    srli a3, a1, 16
; P550-NEXT:    sb a1, 0(a0)
; P550-NEXT:    sb a2, 1(a0)
; P550-NEXT:    sb a3, 2(a0)
; P550-NEXT:    ret
;
; FAST-LABEL: store_i24:
; FAST:       # %bb.0:
; FAST-NEXT:    srli a2, a1, 16
; FAST-NEXT:    sh a1, 0(a0)
; FAST-NEXT:    sb a2, 2(a0)
; FAST-NEXT:    ret
  store i24 %v, ptr %p, align 1
  ret void
}

define void @store_i32(ptr %p, i32 %v) {
; X280-LABEL: store_i32:
; X280:       # %bb.0:
; X280-NEXT:    srli a2, a1, 8
; X280-NEXT:    sb a1, 0(a0)
; X280-NEXT:    srli a3, a1, 16
; X280-NEXT:    srli a1, a1, 24
; X280-NEXT:    sb a2, 1(a0)
; X280-NEXT:    sb a3, 2(a0)
; X280-NEXT:    sb a1, 3(a0)
; X280-NEXT:    ret
;
; P550-LABEL: store_i32:
; P550:       # %bb.0:
; P550-NEXT:    srli a2, a1, 24
; P550-NEXT:    srli a3, a1, 16
; P550-NEXT:    srli a4, a1, 8
; P550-NEXT:    sb a1, 0(a0)
; P550-NEXT:    sb a4, 1(a0)
; P550-NEXT:    sb a3, 2(a0)
; P550-NEXT:    sb a2, 3(a0)
; P550-NEXT:    ret
;
; FAST-LABEL: store_i32:
; FAST:       # %bb.0:
; FAST-NEXT:    sw a1, 0(a0)
; FAST-NEXT:    ret
  store i32 %v, ptr %p, align 1
  ret void
}

define void @store_i64(ptr %p, i64 %v) {
; X280-LABEL: store_i64:
; X280:       # %bb.0:
; X280-NEXT:    srli a2, a1, 8
; X280-NEXT:    srli a3, a1, 16
; X280-NEXT:    sb a1, 0(a0)
; X280-NEXT:    sb a2, 1(a0)
; X280-NEXT:    srli a2, a1, 24
; X280-NEXT:    sb a3, 2(a0)
; X280-NEXT:    srli a3, a1, 32
; X280-NEXT:    sb a2, 3(a0)
; X280-NEXT:    srli a2, a1, 40
; X280-NEXT:    sb a3, 4(a0)
; X280-NEXT:    srli a3, a1, 48
; X280-NEXT:    srli a1, a1, 56
; X280-NEXT:    sb a2, 5(a0)
; X280-NEXT:    sb a3, 6(a0)
; X280-NEXT:    sb a1, 7(a0)
; X280-NEXT:    ret
;
; P550-LABEL: store_i64:
; P550:       # %bb.0:
; P550-NEXT:    srli a2, a1, 56
; P550-NEXT:    srli a3, a1, 48
; P550-NEXT:    srli a4, a1, 40
; P550-NEXT:    srli a5, a1, 32
; P550-NEXT:    sb a5, 4(a0)
; P550-NEXT:    sb a4, 5(a0)
; P550-NEXT:    sb a3, 6(a0)
; P550-NEXT:    sb a2, 7(a0)
; P550-NEXT:    srli a2, a1, 24
; P550-NEXT:    srli a3, a1, 16
; P550-NEXT:    srli a4, a1, 8
; P550-NEXT:    sb a1, 0(a0)
; P550-NEXT:    sb a4, 1(a0)
; P550-NEXT:    sb a3, 2(a0)
; P550-NEXT:    sb a2, 3(a0)
; P550-NEXT:    ret
;
; FAST-LABEL: store_i64:
; FAST:       # %bb.0:
; FAST-NEXT:    sd a1, 0(a0)
; FAST-NEXT:    ret
  store i64 %v, ptr %p, align 1
  ret void
}

define void @merge_stores_i8_i16(ptr %p) {
; SLOW-LABEL: merge_stores_i8_i16:
; SLOW:       # %bb.0:
; SLOW-NEXT:    sb zero, 0(a0)
; SLOW-NEXT:    sb zero, 1(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: merge_stores_i8_i16:
; FAST:       # %bb.0:
; FAST-NEXT:    sh zero, 0(a0)
; FAST-NEXT:    ret
  store i8 0, ptr %p
  %p2 = getelementptr i8, ptr %p, i32 1
  store i8 0, ptr %p2
  ret void
}

define void @merge_stores_i8_i32(ptr %p) {
; SLOW-LABEL: merge_stores_i8_i32:
; SLOW:       # %bb.0:
; SLOW-NEXT:    sb zero, 0(a0)
; SLOW-NEXT:    sb zero, 1(a0)
; SLOW-NEXT:    sb zero, 2(a0)
; SLOW-NEXT:    sb zero, 3(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: merge_stores_i8_i32:
; FAST:       # %bb.0:
; FAST-NEXT:    sw zero, 0(a0)
; FAST-NEXT:    ret
  store i8 0, ptr %p
  %p2 = getelementptr i8, ptr %p, i32 1
  store i8 0, ptr %p2
  %p3 = getelementptr i8, ptr %p, i32 2
  store i8 0, ptr %p3
  %p4 = getelementptr i8, ptr %p, i32 3
  store i8 0, ptr %p4
  ret void
}

define void @merge_stores_i8_i64(ptr %p) {
; SLOW-LABEL: merge_stores_i8_i64:
; SLOW:       # %bb.0:
; SLOW-NEXT:    sb zero, 0(a0)
; SLOW-NEXT:    sb zero, 1(a0)
; SLOW-NEXT:    sb zero, 2(a0)
; SLOW-NEXT:    sb zero, 3(a0)
; SLOW-NEXT:    sb zero, 4(a0)
; SLOW-NEXT:    sb zero, 5(a0)
; SLOW-NEXT:    sb zero, 6(a0)
; SLOW-NEXT:    sb zero, 7(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: merge_stores_i8_i64:
; FAST:       # %bb.0:
; FAST-NEXT:    sd zero, 0(a0)
; FAST-NEXT:    ret
  store i8 0, ptr %p
  %p2 = getelementptr i8, ptr %p, i32 1
  store i8 0, ptr %p2
  %p3 = getelementptr i8, ptr %p, i32 2
  store i8 0, ptr %p3
  %p4 = getelementptr i8, ptr %p, i32 3
  store i8 0, ptr %p4
  %p5 = getelementptr i8, ptr %p, i32 4
  store i8 0, ptr %p5
  %p6 = getelementptr i8, ptr %p, i32 5
  store i8 0, ptr %p6
  %p7 = getelementptr i8, ptr %p, i32 6
  store i8 0, ptr %p7
  %p8 = getelementptr i8, ptr %p, i32 7
  store i8 0, ptr %p8
  ret void
}

define void @merge_stores_i16_i32(ptr %p) {
; SLOW-LABEL: merge_stores_i16_i32:
; SLOW:       # %bb.0:
; SLOW-NEXT:    sh zero, 0(a0)
; SLOW-NEXT:    sh zero, 2(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: merge_stores_i16_i32:
; FAST:       # %bb.0:
; FAST-NEXT:    sw zero, 0(a0)
; FAST-NEXT:    ret
  store i16 0, ptr %p
  %p2 = getelementptr i16, ptr %p, i32 1
  store i16 0, ptr %p2
  ret void
}

define void @merge_stores_i16_i64(ptr %p) {
; SLOW-LABEL: merge_stores_i16_i64:
; SLOW:       # %bb.0:
; SLOW-NEXT:    sh zero, 0(a0)
; SLOW-NEXT:    sh zero, 2(a0)
; SLOW-NEXT:    sh zero, 4(a0)
; SLOW-NEXT:    sh zero, 6(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: merge_stores_i16_i64:
; FAST:       # %bb.0:
; FAST-NEXT:    sd zero, 0(a0)
; FAST-NEXT:    ret
  store i16 0, ptr %p
  %p2 = getelementptr i16, ptr %p, i32 1
  store i16 0, ptr %p2
  %p3 = getelementptr i16, ptr %p, i32 2
  store i16 0, ptr %p3
  %p4 = getelementptr i16, ptr %p, i32 3
  store i16 0, ptr %p4
  ret void
}

define void @merge_stores_i32_i64(ptr %p) {
; SLOW-LABEL: merge_stores_i32_i64:
; SLOW:       # %bb.0:
; SLOW-NEXT:    sw zero, 0(a0)
; SLOW-NEXT:    sw zero, 4(a0)
; SLOW-NEXT:    ret
;
; FAST-LABEL: merge_stores_i32_i64:
; FAST:       # %bb.0:
; FAST-NEXT:    sd zero, 0(a0)
; FAST-NEXT:    ret
  store i32 0, ptr %p
  %p2 = getelementptr i32, ptr %p, i32 1
  store i32 0, ptr %p2
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHEETAH: {{.*}}
; P450: {{.*}}
; P470: {{.*}}
; P650: {{.*}}
; P670: {{.*}}
