; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=128 -verify-machineinstrs | FileCheck %s

define <2 x i16> @or_shl_sext_zext_v2i8(<2 x i8> %a, <2 x i8> %b) {
; CHECK-LABEL: or_shl_sext_zext_v2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = sext <2 x i8> %a to <2 x i16>
  %1 = shl <2 x i16> %0, <i16 8, i16 8>
  %2 = zext <2 x i8> %b to <2 x i16>
  %3 = or <2 x i16> %1, %2
  ret <2 x i16> %3
}

define <2 x i16> @or_zext_shl_sext_v2i8(<2 x i8> %a, <2 x i8> %b) {
; CHECK-LABEL: or_zext_shl_sext_v2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = sext <2 x i8> %a to <2 x i16>
  %1 = shl <2 x i16> %0, <i16 8, i16 8>
  %2 = zext <2 x i8> %b to <2 x i16>
  %3 = or <2 x i16> %2, %1
  ret <2 x i16> %3
}

define <2 x i16> @or_shl_zext_zext_v2i8(<2 x i8> %a, <2 x i8> %b) {
; CHECK-LABEL: or_shl_zext_zext_v2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = zext <2 x i8> %a to <2 x i16>
  %1 = shl <2 x i16> %0, <i16 8, i16 8>
  %2 = zext <2 x i8> %b to <2 x i16>
  %3 = or <2 x i16> %1, %2
  ret <2 x i16> %3
}

define <2 x i16> @or_zext_shl_zext_v2i8(<2 x i8> %a, <2 x i8> %b) {
; CHECK-LABEL: or_zext_shl_zext_v2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = zext <2 x i8> %a to <2 x i16>
  %1 = shl <2 x i16> %0, <i16 8, i16 8>
  %2 = zext <2 x i8> %b to <2 x i16>
  %3 = or <2 x i16> %2, %1
  ret <2 x i16> %3
}

define <2 x i32> @or_shl_sext_zext_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: or_shl_sext_zext_v2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = sext <2 x i16> %a to <2 x i32>
  %1 = shl <2 x i32> %0, <i32 16, i32 16>
  %2 = zext <2 x i16> %b to <2 x i32>
  %3 = or <2 x i32> %1, %2
  ret <2 x i32> %3
}

define <2 x i32> @or_zext_shl_sext_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: or_zext_shl_sext_v2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = sext <2 x i16> %a to <2 x i32>
  %1 = shl <2 x i32> %0, <i32 16, i32 16>
  %2 = zext <2 x i16> %b to <2 x i32>
  %3 = or <2 x i32> %2, %1
  ret <2 x i32> %3
}

define <2 x i32> @or_shl_zext_zext_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: or_shl_zext_zext_v2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = zext <2 x i16> %a to <2 x i32>
  %1 = shl <2 x i32> %0, <i32 16, i32 16>
  %2 = zext <2 x i16> %b to <2 x i32>
  %3 = or <2 x i32> %1, %2
  ret <2 x i32> %3
}

define <2 x i32> @or_zext_shl_zext_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: or_zext_shl_zext_v2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = zext <2 x i16> %a to <2 x i32>
  %1 = shl <2 x i32> %0, <i32 16, i32 16>
  %2 = zext <2 x i16> %b to <2 x i32>
  %3 = or <2 x i32> %2, %1
  ret <2 x i32> %3
}

define <2 x i64> @or_shl_sext_zext_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: or_shl_sext_zext_v2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = sext <2 x i32> %a to <2 x i64>
  %1 = shl <2 x i64> %0, <i64 32, i64 32>
  %2 = zext <2 x i32> %b to <2 x i64>
  %3 = or <2 x i64> %1, %2
  ret <2 x i64> %3
}

define <2 x i64> @or_zext_shl_sext_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: or_zext_shl_sext_v2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = sext <2 x i32> %a to <2 x i64>
  %1 = shl <2 x i64> %0, <i64 32, i64 32>
  %2 = zext <2 x i32> %b to <2 x i64>
  %3 = or <2 x i64> %2, %1
  ret <2 x i64> %3
}

define <2 x i64> @or_shl_zext_zext_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: or_shl_zext_zext_v2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = zext <2 x i32> %a to <2 x i64>
  %1 = shl <2 x i64> %0, <i64 32, i64 32>
  %2 = zext <2 x i32> %b to <2 x i64>
  %3 = or <2 x i64> %1, %2
  ret <2 x i64> %3
}

define <2 x i64> @or_zext_shl_zext_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: or_zext_shl_zext_v2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v9, v8
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vwmaccu.vx v10, a0, v8
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = zext <2 x i32> %a to <2 x i64>
  %1 = shl <2 x i64> %0, <i64 32, i64 32>
  %2 = zext <2 x i32> %b to <2 x i64>
  %3 = or <2 x i64> %2, %1
  ret <2 x i64> %3
}
