; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+m | FileCheck %s --check-prefixes=RV32I
; RUN: llc < %s -mtriple=riscv64 -mattr=+m | FileCheck %s --check-prefixes=RV64I
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+zba | FileCheck %s --check-prefixes=RV32ZBA
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+zba | FileCheck %s --check-prefixes=RV64ZBA

; Make sure we reassociate the 2 from the add instruction into the load
; addressing mode. The default reassociation won't do it becaues the ADD has
; two users.
define signext i32 @test(i32* %x, i32* %y, i64 %n) {
; RV32I-LABEL: test:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a2, a2, 2
; RV32I-NEXT:    add a0, a2, a0
; RV32I-NEXT:    add a1, a2, a1
; RV32I-NEXT:    lw a0, 8(a0)
; RV32I-NEXT:    lw a1, 8(a1)
; RV32I-NEXT:    mul a0, a1, a0
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a2, a2, 2
; RV64I-NEXT:    add a0, a2, a0
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    lw a0, 8(a0)
; RV64I-NEXT:    lw a1, 8(a1)
; RV64I-NEXT:    mulw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV32ZBA-LABEL: test:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    sh2add a0, a2, a0
; RV32ZBA-NEXT:    sh2add a1, a2, a1
; RV32ZBA-NEXT:    lw a0, 8(a0)
; RV32ZBA-NEXT:    lw a1, 8(a1)
; RV32ZBA-NEXT:    mul a0, a1, a0
; RV32ZBA-NEXT:    ret
;
; RV64ZBA-LABEL: test:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    sh2add a0, a2, a0
; RV64ZBA-NEXT:    sh2add a1, a2, a1
; RV64ZBA-NEXT:    lw a0, 8(a0)
; RV64ZBA-NEXT:    lw a1, 8(a1)
; RV64ZBA-NEXT:    mulw a0, a1, a0
; RV64ZBA-NEXT:    ret
entry:
  %add = add i64 %n, 2
  %arrayidx = getelementptr inbounds i32, i32* %x, i64 %add
  %0 = load i32, i32* %arrayidx, align 4
  %arrayidx2 = getelementptr inbounds i32, i32* %y, i64 %add
  %1 = load i32, i32* %arrayidx2, align 4
  %mul = mul nsw i32 %1, %0
  ret i32 %mul
}

; Make sure can treat the OR as an ADD and reassociate its offset into th load
; addresses.
define signext i32 @test2(i32* %x, i32* %y, i64 %n) {
; RV32I-LABEL: test2:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    slli a2, a2, 3
; RV32I-NEXT:    add a0, a0, a2
; RV32I-NEXT:    add a1, a2, a1
; RV32I-NEXT:    lw a0, 4(a0)
; RV32I-NEXT:    lw a1, 4(a1)
; RV32I-NEXT:    mul a0, a1, a0
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test2:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    slli a2, a2, 3
; RV64I-NEXT:    add a0, a0, a2
; RV64I-NEXT:    add a1, a2, a1
; RV64I-NEXT:    lw a0, 4(a0)
; RV64I-NEXT:    lw a1, 4(a1)
; RV64I-NEXT:    mulw a0, a1, a0
; RV64I-NEXT:    ret
;
; RV32ZBA-LABEL: test2:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    sh3add a0, a2, a0
; RV32ZBA-NEXT:    sh3add a1, a2, a1
; RV32ZBA-NEXT:    lw a0, 4(a0)
; RV32ZBA-NEXT:    lw a1, 4(a1)
; RV32ZBA-NEXT:    mul a0, a1, a0
; RV32ZBA-NEXT:    ret
;
; RV64ZBA-LABEL: test2:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    sh3add a0, a2, a0
; RV64ZBA-NEXT:    sh3add a1, a2, a1
; RV64ZBA-NEXT:    lw a0, 4(a0)
; RV64ZBA-NEXT:    lw a1, 4(a1)
; RV64ZBA-NEXT:    mulw a0, a1, a0
; RV64ZBA-NEXT:    ret
entry:
  %mul = shl i64 %n, 1
  %add = or i64 %mul, 1
  %arrayidx = getelementptr inbounds i32, i32* %x, i64 %add
  %0 = load i32, i32* %arrayidx, align 4
  %arrayidx3 = getelementptr inbounds i32, i32* %y, i64 %add
  %1 = load i32, i32* %arrayidx3, align 4
  %mul4 = mul nsw i32 %1, %0
  ret i32 %mul4
}

; This test previously triggered an infinite loop.
define i64 @sct_1262([20 x i64]* %x) {
; RV32I-LABEL: sct_1262:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    addi a1, a0, 1920
; RV32I-NEXT:    lw a2, 1920(a0)
; RV32I-NEXT:    lw a3, 1924(a0)
; RV32I-NEXT:    lw a4, 152(a1)
; RV32I-NEXT:    lw a1, 156(a1)
; RV32I-NEXT:    mul a1, a2, a1
; RV32I-NEXT:    mulhu a5, a2, a4
; RV32I-NEXT:    mul a3, a3, a4
; RV32I-NEXT:    mul a2, a2, a4
; RV32I-NEXT:    lw a4, 152(a0)
; RV32I-NEXT:    lw a0, 156(a0)
; RV32I-NEXT:    add a1, a5, a1
; RV32I-NEXT:    mul a0, a2, a0
; RV32I-NEXT:    mulhu a5, a2, a4
; RV32I-NEXT:    add a1, a1, a3
; RV32I-NEXT:    add a0, a5, a0
; RV32I-NEXT:    mul a1, a1, a4
; RV32I-NEXT:    add a1, a0, a1
; RV32I-NEXT:    mul a0, a2, a4
; RV32I-NEXT:    ret
;
; RV64I-LABEL: sct_1262:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    addi a1, a0, 1920
; RV64I-NEXT:    ld a2, 1920(a0)
; RV64I-NEXT:    ld a1, 152(a1)
; RV64I-NEXT:    ld a0, 152(a0)
; RV64I-NEXT:    mul a0, a2, a0
; RV64I-NEXT:    mul a0, a0, a1
; RV64I-NEXT:    ret
;
; RV32ZBA-LABEL: sct_1262:
; RV32ZBA:       # %bb.0: # %entry
; RV32ZBA-NEXT:    addi a1, a0, 1920
; RV32ZBA-NEXT:    lw a2, 1920(a0)
; RV32ZBA-NEXT:    lw a3, 1924(a0)
; RV32ZBA-NEXT:    lw a4, 152(a1)
; RV32ZBA-NEXT:    lw a1, 156(a1)
; RV32ZBA-NEXT:    mul a1, a2, a1
; RV32ZBA-NEXT:    mulhu a5, a2, a4
; RV32ZBA-NEXT:    mul a3, a3, a4
; RV32ZBA-NEXT:    mul a2, a2, a4
; RV32ZBA-NEXT:    lw a4, 152(a0)
; RV32ZBA-NEXT:    lw a0, 156(a0)
; RV32ZBA-NEXT:    add a1, a5, a1
; RV32ZBA-NEXT:    mul a0, a2, a0
; RV32ZBA-NEXT:    mulhu a5, a2, a4
; RV32ZBA-NEXT:    add a1, a1, a3
; RV32ZBA-NEXT:    add a0, a5, a0
; RV32ZBA-NEXT:    mul a1, a1, a4
; RV32ZBA-NEXT:    add a1, a0, a1
; RV32ZBA-NEXT:    mul a0, a2, a4
; RV32ZBA-NEXT:    ret
;
; RV64ZBA-LABEL: sct_1262:
; RV64ZBA:       # %bb.0: # %entry
; RV64ZBA-NEXT:    addi a1, a0, 1920
; RV64ZBA-NEXT:    ld a2, 1920(a0)
; RV64ZBA-NEXT:    ld a1, 152(a1)
; RV64ZBA-NEXT:    ld a0, 152(a0)
; RV64ZBA-NEXT:    mul a0, a2, a0
; RV64ZBA-NEXT:    mul a0, a0, a1
; RV64ZBA-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds [20 x i64], [20 x i64]* %x, i64 12
  %arrayidx1 = getelementptr inbounds [20 x i64], [20 x i64]* %arrayidx, i64 0, i64 0
  %0 = load i64, i64* %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds [20 x i64], [20 x i64]* %x, i64 12
  %arrayidx3 = getelementptr inbounds [20 x i64], [20 x i64]* %arrayidx2, i64 0, i64 19
  %1 = load i64, i64* %arrayidx3, align 8
  %mul = mul nsw i64 %0, %1
  %arrayidx4 = getelementptr inbounds [20 x i64], [20 x i64]* %x, i64 0
  %arrayidx5 = getelementptr inbounds [20 x i64], [20 x i64]* %arrayidx4, i64 0, i64 19
  %2 = load i64, i64* %arrayidx5, align 8
  %mul6 = mul nsw i64 %mul, %2
  ret i64 %mul6
}
