# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc %s -mtriple=riscv64 -run-pass=riscv-merge-base-offset -verify-machineinstrs -o - | FileCheck %s

--- |
  @ga1 = dso_local global [32 x i32] zeroinitializer, align 4

  define ptr @foo(i1 %c) #0 {
    %a = getelementptr [32 x i32], ptr @ga1, i32 0, i32 31
    %b = select i1 %c, ptr null, ptr %a
    ret ptr %b
  }

  attributes #0 = { "target-cpu"="sifive-p670" }

...
---
name:            foo
alignment:       2
tracksRegLiveness: true
registers:
  - { id: 0, class: gpr }
  - { id: 1, class: gpr }
  - { id: 2, class: gpr }
  - { id: 3, class: gprnox0 }
  - { id: 4, class: gprnox0 }
  - { id: 5, class: gprnox0 }
liveins:
  - { reg: '$x10', virtual-reg: '%0' }
frameInfo:
  maxAlignment:    1
machineFunctionInfo:
  varArgsFrameIndex: 0
  varArgsSaveSize: 0
body:             |
  bb.0 (%ir-block.0):
    liveins: $x10

    ; CHECK-LABEL: name: foo
    ; CHECK: liveins: $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[ANDI:%[0-9]+]]:gpr = ANDI [[COPY]], 1
    ; CHECK-NEXT: [[PseudoMovAddr:%[0-9]+]]:gprnox0 = PseudoMovAddr target-flags(riscv-hi) @ga1 + 124, target-flags(riscv-lo) @ga1 + 124
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gprnox0 = COPY $x0
    ; CHECK-NEXT: [[PseudoCCMOVGPRNoX0_:%[0-9]+]]:gprnox0 = PseudoCCMOVGPRNoX0 killed [[ANDI]], [[COPY1]], 1, [[PseudoMovAddr]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[PseudoCCMOVGPRNoX0_]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gpr = COPY $x10
    %1:gpr = ANDI %0, 1
    %2:gpr = PseudoMovAddr target-flags(riscv-hi) @ga1, target-flags(riscv-lo) @ga1
    %3:gprnox0 = ADDI killed %2, 124
    %4:gprnox0 = COPY $x0
    %5:gprnox0 = PseudoCCMOVGPRNoX0 killed %1, %4, 1, %3, %4
    $x10 = COPY %5
    PseudoRET implicit $x10

...
