; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 -mattr=+m | FileCheck %s

define i32 @udiv_constant(i32 %x) {
; CHECK-LABEL: udiv_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %a = mul nuw i32 %x, 3
  %b = udiv i32 %a, 3
  ret i32 %b
}

define i32 @udiv_nonconstant(i32 %x, i32 %y) {
; CHECK-LABEL: udiv_nonconstant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %a = mul nuw i32 %x, %y
  %b = udiv i32 %a, %y
  ret i32 %b
}

define i32 @udiv_nonconstant_commute(i32 %x, i32 %y) {
; CHECK-LABEL: udiv_nonconstant_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = mul nuw i32 %x, %y
  %b = udiv i32 %a, %x
  ret i32 %b
}

define i32 @udiv_negative_test(i32 %x) {
; CHECK-LABEL: udiv_negative_test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a1, a0, 1
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    lui a1, 699051
; CHECK-NEXT:    addi a1, a1, -1365
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    slli a1, a1, 32
; CHECK-NEXT:    mulhu a0, a0, a1
; CHECK-NEXT:    srli a0, a0, 33
; CHECK-NEXT:    ret
  %a = mul i32 %x, 3
  %b = udiv i32 %a, 3
  ret i32 %b
}

define i32 @urem_constant(i32 %x) {
; CHECK-LABEL: urem_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %a = mul nuw i32 %x, 3
  %b = urem i32 %a, 3
  ret i32 %b
}

define i32 @urem_nonconstant(i32 %x, i32 %y) {
; CHECK-LABEL: urem_nonconstant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %a = mul nuw i32 %x, %y
  %b = urem i32 %a, %y
  ret i32 %b
}

define i32 @urem_nonconstant_commute(i32 %x, i32 %y) {
; CHECK-LABEL: urem_nonconstant_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %a = mul nuw i32 %x, %y
  %b = urem i32 %a, %x
  ret i32 %b
}

define i32 @urem_negative_test(i32 %x) {
; CHECK-LABEL: urem_negative_test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a1, a0, 1
; CHECK-NEXT:    lui a2, 699051
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    addi a1, a2, -1365
; CHECK-NEXT:    slli a2, a0, 32
; CHECK-NEXT:    slli a1, a1, 32
; CHECK-NEXT:    mulhu a1, a2, a1
; CHECK-NEXT:    srli a1, a1, 33
; CHECK-NEXT:    slli a2, a1, 1
; CHECK-NEXT:    add a1, a2, a1
; CHECK-NEXT:    subw a0, a0, a1
; CHECK-NEXT:    ret
  %a = mul i32 %x, 3
  %b = urem i32 %a, 3
  ret i32 %b
}

define i32 @sdiv_constant(i32 %x) {
; CHECK-LABEL: sdiv_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %a = mul nsw i32 %x, 3
  %b = sdiv i32 %a, 3
  ret i32 %b
}

define i32 @sdiv_nonconstant(i32 %x, i32 %y) {
; CHECK-LABEL: sdiv_nonconstant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %a = mul nsw i32 %x, %y
  %b = sdiv i32 %a, %y
  ret i32 %b
}

define i32 @sdiv_nonconstant_commute(i32 %x, i32 %y) {
; CHECK-LABEL: sdiv_nonconstant_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = mul nsw i32 %x, %y
  %b = sdiv i32 %a, %x
  ret i32 %b
}

define i32 @sdiv_negative_test(i32 %x) {
; CHECK-LABEL: sdiv_negative_test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a1, a0, 1
; CHECK-NEXT:    addw a0, a1, a0
; CHECK-NEXT:    lui a1, 349525
; CHECK-NEXT:    addiw a1, a1, 1366
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    srli a1, a0, 63
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    addw a0, a0, a1
; CHECK-NEXT:    ret
  %a = mul i32 %x, 3
  %b = sdiv i32 %a, 3
  ret i32 %b
}

define i32 @srem_constant(i32 %x) {
; CHECK-LABEL: srem_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %a = mul nsw i32 %x, 3
  %b = srem i32 %a, 3
  ret i32 %b
}

define i32 @srem_nonconstant(i32 %x, i32 %y) {
; CHECK-LABEL: srem_nonconstant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %a = mul nsw i32 %x, %y
  %b = srem i32 %a, %y
  ret i32 %b
}

define i32 @srem_nonconstant_commute(i32 %x, i32 %y) {
; CHECK-LABEL: srem_nonconstant_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  %a = mul nsw i32 %x, %y
  %b = srem i32 %a, %x
  ret i32 %b
}

define i32 @srem_negative_test(i32 %x) {
; CHECK-LABEL: srem_negative_test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slli a1, a0, 1
; CHECK-NEXT:    lui a2, 349525
; CHECK-NEXT:    addw a0, a1, a0
; CHECK-NEXT:    addiw a1, a2, 1366
; CHECK-NEXT:    mul a1, a0, a1
; CHECK-NEXT:    srli a2, a1, 63
; CHECK-NEXT:    srli a1, a1, 32
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    slli a2, a1, 1
; CHECK-NEXT:    add a1, a2, a1
; CHECK-NEXT:    subw a0, a0, a1
; CHECK-NEXT:    ret
  %a = mul i32 %x, 3
  %b = srem i32 %a, 3
  ret i32 %b
}
