; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+c,+conditional-cmv-fusion -verify-machineinstrs < %s | FileCheck %s

; InstCombine canonicalizes (c ? x | y : x) to (x | (c ? y : 0)) similar for
; other binary operations using their identity value as the constant.

; We can reverse this for and/or/xor. Allowing us to pull the binop into
; the basic block we create when we expand select.

define signext i32 @and_select_all_ones_i32(i1 zeroext %c, i32 signext %x, i32 signext %y) {
; CHECK-LABEL: and_select_all_ones_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:    bnez a0, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i32 %x, i32 -1
  %b = and i32 %a, %y
  ret i32 %b
}

define i64 @and_select_all_ones_i64(i1 zeroext %c, i64 %x, i64 %y) {
; CHECK-LABEL: and_select_all_ones_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:    beqz a0, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i64 -1, i64 %x
  %b = and i64 %y, %a
  ret i64 %b
}

define signext i32 @or_select_all_zeros_i32(i1 zeroext %c, i32 signext %x, i32 signext %y) {
; CHECK-LABEL: or_select_all_zeros_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or a1, a1, a2
; CHECK-NEXT:    bnez a0, .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i32 %x, i32 0
  %b = or i32 %y, %a
  ret i32 %b
}

define i64 @or_select_all_zeros_i64(i1 zeroext %c, i64 %x, i64 %y) {
; CHECK-LABEL: or_select_all_zeros_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or a1, a1, a2
; CHECK-NEXT:    beqz a0, .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i64 0, i64 %x
  %b = or i64 %a, %y
  ret i64 %b
}

define signext i32 @xor_select_all_zeros_i32(i1 zeroext %c, i32 signext %x, i32 signext %y) {
; CHECK-LABEL: xor_select_all_zeros_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xor a1, a1, a2
; CHECK-NEXT:    beqz a0, .LBB4_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i32 0, i32 %x
  %b = xor i32 %y, %a
  ret i32 %b
}

define i64 @xor_select_all_zeros_i64(i1 zeroext %c, i64 %x, i64 %y) {
; CHECK-LABEL: xor_select_all_zeros_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xor a1, a1, a2
; CHECK-NEXT:    bnez a0, .LBB5_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i64 %x, i64 0
  %b = xor i64 %a, %y
  ret i64 %b
}

define signext i32 @add_select_all_zeros_i32(i1 zeroext %c, i32 signext %x, i32 signext %y) {
; CHECK-LABEL: add_select_all_zeros_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addw a1, a1, a2
; CHECK-NEXT:    beqz a0, .LBB6_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB6_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i32 0, i32 %x
  %b = add i32 %y, %a
  ret i32 %b
}

define i64 @add_select_all_zeros_i64(i1 zeroext %c, i64 %x, i64 %y) {
; CHECK-LABEL: add_select_all_zeros_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    bnez a0, .LBB7_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB7_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i64 %x, i64 0
  %b = add i64 %a, %y
  ret i64 %b
}

define signext i32 @sub_select_all_zeros_i32(i1 zeroext %c, i32 signext %x, i32 signext %y) {
; CHECK-LABEL: sub_select_all_zeros_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subw a1, a2, a1
; CHECK-NEXT:    beqz a0, .LBB8_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i32 0, i32 %x
  %b = sub i32 %y, %a
  ret i32 %b
}

define i64 @sub_select_all_zeros_i64(i1 zeroext %c, i64 %x, i64 %y) {
; CHECK-LABEL: sub_select_all_zeros_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sub a1, a2, a1
; CHECK-NEXT:    bnez a0, .LBB9_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a1, a2
; CHECK-NEXT:  .LBB9_2:
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
  %a = select i1 %c, i64 %x, i64 0
  %b = sub i64 %y, %a
  ret i64 %b
}
