; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-x280n -mattr=+v -riscv-force-tail-undisturbed -enable-subreg-liveness | FileCheck %s -check-prefix=X280
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-x280 -mattr=+v -riscv-force-tail-undisturbed -enable-subreg-liveness | FileCheck %s -check-prefix=X280N

; Function Attrs: nounwind vscale_range(8,1024)
define dso_local void @radix4(ptr noalias noundef %twi1, ptr noalias noundef %twi2, ptr noalias noundef %twi3, ptr noalias noundef %x0, ptr noalias noundef %x1, ptr noalias noundef %x2, ptr noalias noundef %x3, ptr noalias noundef %y0, ptr noalias noundef %y1, ptr noalias noundef %y2, ptr noalias noundef %y3, i64 noundef %cnt) #0 {
; X280-LABEL: radix4:
; X280:       # %bb.0: # %entry
; X280-NEXT:    addi sp, sp, -16
; X280-NEXT:    csrr t0, vlenb
; X280-NEXT:    slli t0, t0, 2
; X280-NEXT:    sub sp, sp, t0
; X280-NEXT:    vsetvli t1, zero, e32, m2, tu, ma
; X280-NEXT:    vlseg2e32.v v8, (a0)
; X280-NEXT:    csrr t2, vlenb
; X280-NEXT:    addi a0, sp, 16
; X280-NEXT:    li t0, 0
; X280-NEXT:    slli t2, t2, 1
; X280-NEXT:    vlseg2e32.v v12, (a1)
; X280-NEXT:    vs2r.v v8, (a0) # vscale x 16-byte Folded Spill
; X280-NEXT:    add a0, a0, t2
; X280-NEXT:    vs2r.v v10, (a0) # vscale x 16-byte Folded Spill
; X280-NEXT:    csrr a0, vlenb
; X280-NEXT:    vlseg2e32.v v16, (a2)
; X280-NEXT:    sh2add a0, a0, sp
; X280-NEXT:    ld t2, 40(a0)
; X280-NEXT:    csrr a0, vlenb
; X280-NEXT:    sh2add a0, a0, sp
; X280-NEXT:    ld a1, 32(a0)
; X280-NEXT:    csrr a0, vlenb
; X280-NEXT:    sh2add a0, a0, sp
; X280-NEXT:    ld a2, 24(a0)
; X280-NEXT:    csrr a0, vlenb
; X280-NEXT:    sh2add a0, a0, sp
; X280-NEXT:    ld a0, 16(a0)
; X280-NEXT:    beqz t2, .LBB0_2
; X280-NEXT:  .LBB0_1: # %for.body
; X280-NEXT:    # =>This Inner Loop Header: Depth=1
; X280-NEXT:    vlseg2e32.v v22, (a4)
; X280-NEXT:    csrr t4, vlenb
; X280-NEXT:    addi t3, sp, 16
; X280-NEXT:    sh3add a4, t1, a4
; X280-NEXT:    addi t0, t0, 1
; X280-NEXT:    slli t4, t4, 1
; X280-NEXT:    vl2r.v v8, (t3) # vscale x 16-byte Folded Reload
; X280-NEXT:    add t3, t3, t4
; X280-NEXT:    vl2r.v v10, (t3) # vscale x 16-byte Folded Reload
; X280-NEXT:    vfmul.vv v20, v22, v8
; X280-NEXT:    vlseg2e32.v v2, (a5)
; X280-NEXT:    sh3add a5, t1, a5
; X280-NEXT:    vfmul.vv v28, v22, v10
; X280-NEXT:    vfnmsac.vv v20, v24, v10
; X280-NEXT:    vfmacc.vv v28, v24, v8
; X280-NEXT:    vlseg2e32.v v24, (a6)
; X280-NEXT:    sh3add a6, t1, a6
; X280-NEXT:    vfmul.vv v22, v2, v12
; X280-NEXT:    vfmul.vv v6, v2, v14
; X280-NEXT:    vlseg2e32.v v8, (a3)
; X280-NEXT:    sh3add a3, t1, a3
; X280-NEXT:    vfnmsac.vv v22, v4, v14
; X280-NEXT:    vfmacc.vv v6, v4, v12
; X280-NEXT:    vfmul.vv v4, v24, v16
; X280-NEXT:    vfmul.vv v2, v24, v18
; X280-NEXT:    vfnmsac.vv v4, v26, v18
; X280-NEXT:    vfmacc.vv v2, v26, v16
; X280-NEXT:    vfadd.vv v30, v8, v22
; X280-NEXT:    vfadd.vv v0, v10, v6
; X280-NEXT:    vfsub.vv v26, v8, v22
; X280-NEXT:    vfsub.vv v6, v10, v6
; X280-NEXT:    vfadd.vv v8, v20, v4
; X280-NEXT:    vfadd.vv v10, v28, v2
; X280-NEXT:    vfadd.vv v22, v30, v8
; X280-NEXT:    vfadd.vv v24, v0, v10
; X280-NEXT:    vfsub.vv v28, v28, v2
; X280-NEXT:    vfsub.vv v20, v20, v4
; X280-NEXT:    vsseg2e32.v v22, (a7)
; X280-NEXT:    sh3add a7, t1, a7
; X280-NEXT:    vfadd.vv v22, v26, v28
; X280-NEXT:    vfadd.vv v24, v6, v20
; X280-NEXT:    vfsub.vv v8, v30, v8
; X280-NEXT:    vsseg2e32.v v22, (a0)
; X280-NEXT:    sh3add a0, t1, a0
; X280-NEXT:    vfsub.vv v10, v0, v10
; X280-NEXT:    vfsub.vv v22, v26, v28
; X280-NEXT:    vfsub.vv v24, v6, v20
; X280-NEXT:    vsseg2e32.v v8, (a2)
; X280-NEXT:    sh3add a2, t1, a2
; X280-NEXT:    vsseg2e32.v v22, (a1)
; X280-NEXT:    sh3add a1, t1, a1
; X280-NEXT:    bltu t0, t2, .LBB0_1
; X280-NEXT:  .LBB0_2: # %for.cond.cleanup
; X280-NEXT:    csrr a0, vlenb
; X280-NEXT:    sh2add sp, a0, sp
; X280-NEXT:    addi sp, sp, 16
; X280-NEXT:    ret
;
; X280N-LABEL: radix4:
; X280N:       # %bb.0: # %entry
; X280N-NEXT:    addi sp, sp, -16
; X280N-NEXT:    csrr t0, vlenb
; X280N-NEXT:    slli t0, t0, 2
; X280N-NEXT:    sub sp, sp, t0
; X280N-NEXT:    vsetvli t1, zero, e32, m2, tu, ma
; X280N-NEXT:    vlseg2e32.v v8, (a0)
; X280N-NEXT:    csrr t2, vlenb
; X280N-NEXT:    addi a0, sp, 16
; X280N-NEXT:    li t0, 0
; X280N-NEXT:    slli t2, t2, 1
; X280N-NEXT:    vlseg2e32.v v12, (a1)
; X280N-NEXT:    vs2r.v v8, (a0) # vscale x 16-byte Folded Spill
; X280N-NEXT:    add a0, a0, t2
; X280N-NEXT:    vs2r.v v10, (a0) # vscale x 16-byte Folded Spill
; X280N-NEXT:    csrr a0, vlenb
; X280N-NEXT:    vlseg2e32.v v16, (a2)
; X280N-NEXT:    sh2add a0, a0, sp
; X280N-NEXT:    ld t2, 40(a0)
; X280N-NEXT:    csrr a0, vlenb
; X280N-NEXT:    sh2add a0, a0, sp
; X280N-NEXT:    ld a1, 32(a0)
; X280N-NEXT:    csrr a0, vlenb
; X280N-NEXT:    sh2add a0, a0, sp
; X280N-NEXT:    ld a2, 24(a0)
; X280N-NEXT:    csrr a0, vlenb
; X280N-NEXT:    sh2add a0, a0, sp
; X280N-NEXT:    ld a0, 16(a0)
; X280N-NEXT:    beqz t2, .LBB0_2
; X280N-NEXT:  .LBB0_1: # %for.body
; X280N-NEXT:    # =>This Inner Loop Header: Depth=1
; X280N-NEXT:    vlseg2e32.v v22, (a4)
; X280N-NEXT:    csrr t4, vlenb
; X280N-NEXT:    addi t3, sp, 16
; X280N-NEXT:    sh3add a4, t1, a4
; X280N-NEXT:    addi t0, t0, 1
; X280N-NEXT:    slli t4, t4, 1
; X280N-NEXT:    vl2r.v v8, (t3) # vscale x 16-byte Folded Reload
; X280N-NEXT:    add t3, t3, t4
; X280N-NEXT:    vl2r.v v10, (t3) # vscale x 16-byte Folded Reload
; X280N-NEXT:    vfmul.vv v20, v22, v8
; X280N-NEXT:    vlseg2e32.v v2, (a5)
; X280N-NEXT:    sh3add a5, t1, a5
; X280N-NEXT:    vfmul.vv v28, v22, v10
; X280N-NEXT:    vfnmsac.vv v20, v24, v10
; X280N-NEXT:    vfmacc.vv v28, v24, v8
; X280N-NEXT:    vlseg2e32.v v24, (a6)
; X280N-NEXT:    sh3add a6, t1, a6
; X280N-NEXT:    vfmul.vv v22, v2, v12
; X280N-NEXT:    vfmul.vv v6, v2, v14
; X280N-NEXT:    vlseg2e32.v v8, (a3)
; X280N-NEXT:    sh3add a3, t1, a3
; X280N-NEXT:    vfnmsac.vv v22, v4, v14
; X280N-NEXT:    vfmacc.vv v6, v4, v12
; X280N-NEXT:    vfmul.vv v4, v24, v16
; X280N-NEXT:    vfmul.vv v2, v24, v18
; X280N-NEXT:    vfnmsac.vv v4, v26, v18
; X280N-NEXT:    vfmacc.vv v2, v26, v16
; X280N-NEXT:    vfadd.vv v30, v8, v22
; X280N-NEXT:    vfadd.vv v0, v10, v6
; X280N-NEXT:    vfsub.vv v26, v8, v22
; X280N-NEXT:    vfsub.vv v6, v10, v6
; X280N-NEXT:    vfadd.vv v8, v20, v4
; X280N-NEXT:    vfadd.vv v10, v28, v2
; X280N-NEXT:    vfadd.vv v22, v30, v8
; X280N-NEXT:    vfadd.vv v24, v0, v10
; X280N-NEXT:    vfsub.vv v28, v28, v2
; X280N-NEXT:    vfsub.vv v20, v20, v4
; X280N-NEXT:    vsseg2e32.v v22, (a7)
; X280N-NEXT:    sh3add a7, t1, a7
; X280N-NEXT:    vfadd.vv v22, v26, v28
; X280N-NEXT:    vfadd.vv v24, v6, v20
; X280N-NEXT:    vfsub.vv v8, v30, v8
; X280N-NEXT:    vsseg2e32.v v22, (a0)
; X280N-NEXT:    sh3add a0, t1, a0
; X280N-NEXT:    vfsub.vv v10, v0, v10
; X280N-NEXT:    vfsub.vv v22, v26, v28
; X280N-NEXT:    vfsub.vv v24, v6, v20
; X280N-NEXT:    vsseg2e32.v v8, (a2)
; X280N-NEXT:    sh3add a2, t1, a2
; X280N-NEXT:    vsseg2e32.v v22, (a1)
; X280N-NEXT:    sh3add a1, t1, a1
; X280N-NEXT:    bltu t0, t2, .LBB0_1
; X280N-NEXT:  .LBB0_2: # %for.cond.cleanup
; X280N-NEXT:    csrr a0, vlenb
; X280N-NEXT:    sh2add sp, a0, sp
; X280N-NEXT:    addi sp, sp, 16
; X280N-NEXT:    ret
entry:
  %i = call i64 @llvm.riscv.vsetvlimax.i64(i64 2, i64 1)
  %i1 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %twi1, i64 %i, i64 5)
  %i2 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i1, i32 0)
  %i3 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i1, i32 1)
  %i4 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %twi2, i64 %i, i64 5)
  %i5 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i4, i32 0)
  %i6 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i4, i32 1)
  %i7 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %twi3, i64 %i, i64 5)
  %i8 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i7, i32 0)
  %i9 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i7, i32 1)
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %y1.addr.0 = phi ptr [ %y1, %entry ], [ %add.ptr10, %for.inc ]
  %y0.addr.0 = phi ptr [ %y0, %entry ], [ %add.ptr8, %for.inc ]
  %x3.addr.0 = phi ptr [ %x3, %entry ], [ %add.ptr6, %for.inc ]
  %x2.addr.0 = phi ptr [ %x2, %entry ], [ %add.ptr4, %for.inc ]
  %x1.addr.0 = phi ptr [ %x1, %entry ], [ %add.ptr2, %for.inc ]
  %x0.addr.0 = phi ptr [ %x0, %entry ], [ %add.ptr, %for.inc ]
  %y2.addr.0 = phi ptr [ %y2, %entry ], [ %add.ptr12, %for.inc ]
  %y3.addr.0 = phi ptr [ %y3, %entry ], [ %add.ptr14, %for.inc ]
  %idx.0 = phi i64 [ 0, %entry ], [ %inc, %for.inc ]
  %cmp = icmp ult i64 %idx.0, %cnt
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  br label %for.end

for.body:                                         ; preds = %for.cond
  %i10 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %x0.addr.0, i64 %i, i64 5)
  %i11 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i10, i32 0)
  %i12 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i10, i32 1)
  %i13 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %x1.addr.0, i64 %i, i64 5)
  %i14 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i13, i32 0)
  %i15 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i13, i32 1)
  %i16 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %x2.addr.0, i64 %i, i64 5)
  %i17 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i16, i32 0)
  %i18 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i16, i32 1)
  %i19 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.vlseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, ptr %x3.addr.0, i64 %i, i64 5)
  %i20 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i19, i32 0)
  %i21 = call <vscale x 4 x float> @llvm.riscv.tuple.extract.nxv4f32.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i19, i32 1)
  %i22 = call fast <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i14, <vscale x 4 x float> %i2, i64 7, i64 %i)
  %i23 = call fast <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %i22, <vscale x 4 x float> %i15, <vscale x 4 x float> %i3, i64 7, i64 %i, i64 0)
  %i24 = call fast <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i14, <vscale x 4 x float> %i3, i64 7, i64 %i)
  %i25 = call fast <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %i24, <vscale x 4 x float> %i15, <vscale x 4 x float> %i2, i64 7, i64 %i, i64 0)
  %i26 = call fast <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i17, <vscale x 4 x float> %i5, i64 7, i64 %i)
  %i27 = call fast <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %i26, <vscale x 4 x float> %i18, <vscale x 4 x float> %i6, i64 7, i64 %i, i64 0)
  %i28 = call fast <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i17, <vscale x 4 x float> %i6, i64 7, i64 %i)
  %i29 = call fast <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %i28, <vscale x 4 x float> %i18, <vscale x 4 x float> %i5, i64 7, i64 %i, i64 0)
  %i30 = call fast <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i20, <vscale x 4 x float> %i8, i64 7, i64 %i)
  %i31 = call fast <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %i30, <vscale x 4 x float> %i21, <vscale x 4 x float> %i9, i64 7, i64 %i, i64 0)
  %i32 = call fast <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i20, <vscale x 4 x float> %i9, i64 7, i64 %i)
  %i33 = call fast <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %i32, <vscale x 4 x float> %i21, <vscale x 4 x float> %i8, i64 7, i64 %i, i64 0)
  %i34 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i11, <vscale x 4 x float> %i27, i64 7, i64 %i)
  %i35 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i12, <vscale x 4 x float> %i29, i64 7, i64 %i)
  %i36 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i11, <vscale x 4 x float> %i27, i64 7, i64 %i)
  %i37 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i12, <vscale x 4 x float> %i29, i64 7, i64 %i)
  %i38 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i23, <vscale x 4 x float> %i31, i64 7, i64 %i)
  %i39 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i25, <vscale x 4 x float> %i33, i64 7, i64 %i)
  %i40 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i23, <vscale x 4 x float> %i31, i64 7, i64 %i)
  %i41 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i25, <vscale x 4 x float> %i33, i64 7, i64 %i)
  %i42 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i34, <vscale x 4 x float> %i38, i64 7, i64 %i)
  %i43 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i35, <vscale x 4 x float> %i39, i64 7, i64 %i)
  %i44 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i34, <vscale x 4 x float> %i38, i64 7, i64 %i)
  %i45 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i35, <vscale x 4 x float> %i39, i64 7, i64 %i)
  %i46 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i36, <vscale x 4 x float> %i41, i64 7, i64 %i)
  %i47 = call fast <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i37, <vscale x 4 x float> %i40, i64 7, i64 %i)
  %i48 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i36, <vscale x 4 x float> %i41, i64 7, i64 %i)
  %i49 = call fast <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %i37, <vscale x 4 x float> %i40, i64 7, i64 %i)
  %i50 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, <vscale x 4 x float> %i42, i32 0)
  %i51 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i50, <vscale x 4 x float> %i43, i32 1)
  call void @llvm.riscv.vsseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i51, ptr %y0.addr.0, i64 %i, i64 5)
  %i52 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, <vscale x 4 x float> %i46, i32 0)
  %i53 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i52, <vscale x 4 x float> %i47, i32 1)
  call void @llvm.riscv.vsseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i53, ptr %y1.addr.0, i64 %i, i64 5)
  %i54 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, <vscale x 4 x float> %i44, i32 0)
  %i55 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i54, <vscale x 4 x float> %i45, i32 1)
  call void @llvm.riscv.vsseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i55, ptr %y2.addr.0, i64 %i, i64 5)
  %i56 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) poison, <vscale x 4 x float> %i48, i32 0)
  %i57 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 2) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_4t.nxv4f32(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i56, <vscale x 4 x float> %i49, i32 1)
  call void @llvm.riscv.vsseg2.triscv.vector.tuple_nxv16i8_2t(target("riscv.vector.tuple", <vscale x 16 x i8>, 2) %i57, ptr %y3.addr.0, i64 %i, i64 5)
  %mul = mul i64 2, %i
  %add.ptr = getelementptr inbounds float, ptr %x0.addr.0, i64 %mul
  %mul1 = mul i64 2, %i
  %add.ptr2 = getelementptr inbounds float, ptr %x1.addr.0, i64 %mul1
  %mul3 = mul i64 2, %i
  %add.ptr4 = getelementptr inbounds float, ptr %x2.addr.0, i64 %mul3
  %mul5 = mul i64 2, %i
  %add.ptr6 = getelementptr inbounds float, ptr %x3.addr.0, i64 %mul5
  %mul7 = mul i64 2, %i
  %add.ptr8 = getelementptr inbounds float, ptr %y0.addr.0, i64 %mul7
  %mul9 = mul i64 2, %i
  %add.ptr10 = getelementptr inbounds float, ptr %y1.addr.0, i64 %mul9
  %mul11 = mul i64 2, %i
  %add.ptr12 = getelementptr inbounds float, ptr %y2.addr.0, i64 %mul11
  %mul13 = mul i64 2, %i
  %add.ptr14 = getelementptr inbounds float, ptr %y3.addr.0, i64 %mul13
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %inc = add i64 %idx.0, 1
  br label %for.cond

for.end:                                          ; preds = %for.cond.cleanup
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

; Function Attrs: nounwind
declare i64 @llvm.riscv.vsetvlimax.i64(i64 immarg, i64 immarg)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64 immarg)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64 immarg)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)

attributes #0 = { nounwind vscale_range(8,1024) "approx-func-fp-math"="true" "frame-pointer"="none" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sifive-x280n" "target-features"="+64bit,+a,+c,+d,+zvfh,+f,+m,+relax,+v,+xsfvfhbfmin,+xsfvfnrclipxfqf,+xsfvfwmaccqqq,+xsfvqmaccqoq,+zba,+zbb,+zfh,+zicsr,+zifencei,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvl128b,+zvl256b,+zvl32b,+zvl512b,+zvl64b,-save-restore" "unsafe-fp-math"="true" }

