; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 \
; RUN:   | FileCheck %s --check-prefix=NOFUSION
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 -mattr=+fuse-bitfield-extract \
; RUN:   | FileCheck %s --check-prefix=FUSEUBFX

define i32 @test_ubfx_i32(i32 %x, i32 %y) {
; NOFUSION-LABEL: test_ubfx_i32:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 55
; NOFUSION-NEXT:    slli a1, a1, 41
; NOFUSION-NEXT:    srli a0, a0, 60
; NOFUSION-NEXT:    srli a1, a1, 58
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_ubfx_i32:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 55
; FUSEUBFX-NEXT:    srli a0, a0, 60
; FUSEUBFX-NEXT:    slli a1, a1, 41
; FUSEUBFX-NEXT:    srli a1, a1, 58
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = lshr i32 %x, 5
  %b = and i32 %a, 15
  %c = lshr i32 %y, 17
  %d = and i32 %c, 63
  %e = mul i32 %b, %d
  ret i32 %e
}

define i64 @test_ubfx_i64(i64 %x, i64 %y) {
; NOFUSION-LABEL: test_ubfx_i64:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 10
; NOFUSION-NEXT:    slli a1, a1, 34
; NOFUSION-NEXT:    srli a0, a0, 57
; NOFUSION-NEXT:    srli a1, a1, 54
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_ubfx_i64:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 10
; FUSEUBFX-NEXT:    srli a0, a0, 57
; FUSEUBFX-NEXT:    slli a1, a1, 34
; FUSEUBFX-NEXT:    srli a1, a1, 54
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = lshr i64 %x, 47
  %b = and i64 %a, 127
  %c = lshr i64 %y, 20
  %d = and i64 %c, 1023
  %e = mul i64 %b, %d
  ret i64 %e
}

define i32 @test_ubfx_i8(i8 %x, i8 %y) {
; NOFUSION-LABEL: test_ubfx_i8:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 56
; NOFUSION-NEXT:    slli a1, a1, 56
; NOFUSION-NEXT:    srli a0, a0, 61
; NOFUSION-NEXT:    srli a1, a1, 59
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_ubfx_i8:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 56
; FUSEUBFX-NEXT:    srli a0, a0, 61
; FUSEUBFX-NEXT:    slli a1, a1, 56
; FUSEUBFX-NEXT:    srli a1, a1, 59
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = lshr i8 %x, 5
  %b = lshr i8 %y, 3
  %c = zext i8 %a to i32
  %d = zext i8 %b to i32
  %e = mul i32 %c, %d
  ret i32 %e
}

define i32 @test_ubfx_i16(i16 %x, i16 %y) {
; NOFUSION-LABEL: test_ubfx_i16:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 48
; NOFUSION-NEXT:    slli a1, a1, 48
; NOFUSION-NEXT:    srli a0, a0, 58
; NOFUSION-NEXT:    srli a1, a1, 55
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_ubfx_i16:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 48
; FUSEUBFX-NEXT:    srli a0, a0, 58
; FUSEUBFX-NEXT:    slli a1, a1, 48
; FUSEUBFX-NEXT:    srli a1, a1, 55
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = lshr i16 %x, 10
  %b = lshr i16 %y, 7
  %c = zext i16 %a to i32
  %d = zext i16 %b to i32
  %e = mul i32 %c, %d
  ret i32 %e
}

define i32 @test_sbfx_i32(i32 %x, i32 %y) {
; NOFUSION-LABEL: test_sbfx_i32:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 55
; NOFUSION-NEXT:    slli a1, a1, 41
; NOFUSION-NEXT:    srai a0, a0, 60
; NOFUSION-NEXT:    srai a1, a1, 54
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sbfx_i32:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 55
; FUSEUBFX-NEXT:    srai a0, a0, 60
; FUSEUBFX-NEXT:    slli a1, a1, 41
; FUSEUBFX-NEXT:    srai a1, a1, 54
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = shl i32 %x, 23
  %b = ashr i32 %a, 28
  %c = shl i32 %y, 9
  %d = ashr i32 %c, 22
  %e = mul i32 %b, %d
  ret i32 %e
}

; Make sure we still prefer SRAIW over fusion.
define i32 @test_sraiw_i32(i32 %x) {
; NOFUSION-LABEL: test_sraiw_i32:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sraiw a0, a0, 22
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sraiw_i32:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    sraiw a0, a0, 22
; FUSEUBFX-NEXT:    ret
  %a = ashr i32 %x, 22
  ret i32 %a
}

define i64 @test_sbfx_i64(i64 %x, i64 %y) {
; NOFUSION-LABEL: test_sbfx_i64:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 10
; NOFUSION-NEXT:    slli a1, a1, 34
; NOFUSION-NEXT:    srai a0, a0, 57
; NOFUSION-NEXT:    srai a1, a1, 54
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sbfx_i64:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 10
; FUSEUBFX-NEXT:    srai a0, a0, 57
; FUSEUBFX-NEXT:    slli a1, a1, 34
; FUSEUBFX-NEXT:    srai a1, a1, 54
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = shl i64 %x, 10
  %b = ashr i64 %a, 57
  %c = shl i64 %y, 34
  %d = ashr i64 %c, 54
  %e = mul i64 %b, %d
  ret i64 %e
}

; Make sure we still prefer SRAIW over fusion.
define i64 @test_sraiw_i64(i64 %x) {
; NOFUSION-LABEL: test_sraiw_i64:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sraiw a0, a0, 5
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sraiw_i64:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    sraiw a0, a0, 5
; FUSEUBFX-NEXT:    ret
  %a = shl i64 %x, 32
  %b = ashr i64 %a, 37
  ret i64 %b
}

define i32 @test_sbfx_i8(i8 %x, i8 %y) {
; NOFUSION-LABEL: test_sbfx_i8:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a1, a1, 56
; NOFUSION-NEXT:    slli a0, a0, 56
; NOFUSION-NEXT:    srai a0, a0, 61
; NOFUSION-NEXT:    srai a1, a1, 59
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sbfx_i8:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 56
; FUSEUBFX-NEXT:    srai a0, a0, 61
; FUSEUBFX-NEXT:    slli a1, a1, 56
; FUSEUBFX-NEXT:    srai a1, a1, 59
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = ashr i8 %x, 5
  %b = ashr i8 %y, 3
  %c = sext i8 %a to i32
  %d = sext i8 %b to i32
  %e = mul i32 %c, %d
  ret i32 %e
}

define i32 @test_sbfx_i16(i16 %x, i16 %y) {
; NOFUSION-LABEL: test_sbfx_i16:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a1, a1, 48
; NOFUSION-NEXT:    slli a0, a0, 48
; NOFUSION-NEXT:    srai a0, a0, 58
; NOFUSION-NEXT:    srai a1, a1, 55
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sbfx_i16:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 48
; FUSEUBFX-NEXT:    srai a0, a0, 58
; FUSEUBFX-NEXT:    slli a1, a1, 48
; FUSEUBFX-NEXT:    srai a1, a1, 55
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = ashr i16 %x, 10
  %b = ashr i16 %y, 7
  %c = sext i16 %a to i32
  %d = sext i16 %b to i32
  %e = mul i32 %c, %d
  ret i32 %e
}

define i32 @test_ubfx_trailingones_mask_i32(i32 %x, i32 %y) {
; NOFUSION-LABEL: test_ubfx_trailingones_mask_i32:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 40
; NOFUSION-NEXT:    slli a1, a1, 51
; NOFUSION-NEXT:    srli a0, a0, 40
; NOFUSION-NEXT:    srli a1, a1, 51
; NOFUSION-NEXT:    mulw a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_ubfx_trailingones_mask_i32:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 40
; FUSEUBFX-NEXT:    srli a0, a0, 40
; FUSEUBFX-NEXT:    slli a1, a1, 51
; FUSEUBFX-NEXT:    srli a1, a1, 51
; FUSEUBFX-NEXT:    mulw a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = and i32 %x, 16777215
  %b = and i32 %y, 8191
  %c = mul i32 %a, %b
  ret i32 %c
}

define i64 @test_ubfx_trailingones_mask_i64(i64 %x, i64 %y) {
; NOFUSION-LABEL: test_ubfx_trailingones_mask_i64:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 40
; NOFUSION-NEXT:    slli a1, a1, 17
; NOFUSION-NEXT:    srli a0, a0, 40
; NOFUSION-NEXT:    srli a1, a1, 17
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_ubfx_trailingones_mask_i64:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 40
; FUSEUBFX-NEXT:    srli a0, a0, 40
; FUSEUBFX-NEXT:    slli a1, a1, 17
; FUSEUBFX-NEXT:    srli a1, a1, 17
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = and i64 %x, 16777215
  %b = and i64 %y, 140737488355327
  %c = mul i64 %a, %b
  ret i64 %c
}

define i32 @test_sbfx_sext_i32(i32 %x, i32 %y) {
; NOFUSION-LABEL: test_sbfx_sext_i32:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 55
; NOFUSION-NEXT:    slli a1, a1, 41
; NOFUSION-NEXT:    srai a0, a0, 55
; NOFUSION-NEXT:    srai a1, a1, 41
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sbfx_sext_i32:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 55
; FUSEUBFX-NEXT:    srai a0, a0, 55
; FUSEUBFX-NEXT:    slli a1, a1, 41
; FUSEUBFX-NEXT:    srai a1, a1, 41
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = shl i32 %x, 23
  %b = ashr i32 %a, 23
  %c = shl i32 %y, 9
  %d = ashr i32 %c, 9
  %e = mul i32 %b, %d
  ret i32 %e
}

define i64 @test_sbfx_sext_i64(i64 %x, i64 %y) {
; NOFUSION-LABEL: test_sbfx_sext_i64:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a0, a0, 23
; NOFUSION-NEXT:    slli a1, a1, 9
; NOFUSION-NEXT:    srai a0, a0, 23
; NOFUSION-NEXT:    srai a1, a1, 9
; NOFUSION-NEXT:    mul a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEUBFX-LABEL: test_sbfx_sext_i64:
; FUSEUBFX:       # %bb.0:
; FUSEUBFX-NEXT:    slli a0, a0, 23
; FUSEUBFX-NEXT:    srai a0, a0, 23
; FUSEUBFX-NEXT:    slli a1, a1, 9
; FUSEUBFX-NEXT:    srai a1, a1, 9
; FUSEUBFX-NEXT:    mul a0, a0, a1
; FUSEUBFX-NEXT:    ret
  %a = shl i64 %x, 23
  %b = ashr i64 %a, 23
  %c = shl i64 %y, 9
  %d = ashr i64 %c, 9
  %e = mul i64 %b, %d
  ret i64 %e
}

