; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74n \
; RUN:   | FileCheck %s --check-prefix=NOFUSION
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74n -mattr=+fuse-arith-eqz \
; RUN:   | FileCheck %s --check-prefix=FUSION

declare void @bar(i1 zeroext, i32 signext)
declare void @baz(i1 zeroext, i64)

define void @xor_snez(i32 signext %0, i32 signext %1) {
; NOFUSION-LABEL: xor_snez:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    xor a2, a0, a1
; NOFUSION-NEXT:    mulw a1, a1, a0
; NOFUSION-NEXT:    snez a0, a2
; NOFUSION-NEXT:    tail bar
;
; FUSION-LABEL: xor_snez:
; FUSION:       # %bb.0:
; FUSION-NEXT:    xor a2, a0, a1
; FUSION-NEXT:    snez a2, a2
; FUSION-NEXT:    mulw a1, a1, a0
; FUSION-NEXT:    mv a0, a2
; FUSION-NEXT:    tail bar
  %3 = mul i32 %1, %0
  %4 = icmp ne i32 %0, %1
  tail call void @bar(i1 zeroext %4, i32 signext %3)
  ret void
}

define void @xor_seqz(i32 signext %0, i32 signext %1) {
; NOFUSION-LABEL: xor_seqz:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    xor a2, a0, a1
; NOFUSION-NEXT:    mulw a1, a1, a0
; NOFUSION-NEXT:    seqz a0, a2
; NOFUSION-NEXT:    tail bar
;
; FUSION-LABEL: xor_seqz:
; FUSION:       # %bb.0:
; FUSION-NEXT:    xor a2, a0, a1
; FUSION-NEXT:    seqz a2, a2
; FUSION-NEXT:    mulw a1, a1, a0
; FUSION-NEXT:    mv a0, a2
; FUSION-NEXT:    tail bar
  %3 = mul i32 %1, %0
  %4 = icmp eq i32 %0, %1
  tail call void @bar(i1 zeroext %4, i32 signext %3)
  ret void
}

define void @addi_seqz(i32 signext %0, i32 signext %1) {
; NOFUSION-LABEL: addi_seqz:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    addi a2, a0, -5
; NOFUSION-NEXT:    mulw a1, a1, a0
; NOFUSION-NEXT:    seqz a0, a2
; NOFUSION-NEXT:    tail bar
;
; FUSION-LABEL: addi_seqz:
; FUSION:       # %bb.0:
; FUSION-NEXT:    addi a2, a0, -5
; FUSION-NEXT:    seqz a2, a2
; FUSION-NEXT:    mulw a1, a1, a0
; FUSION-NEXT:    mv a0, a2
; FUSION-NEXT:    tail bar
  %3 = mul i32 %1, %0
  %4 = icmp eq i32 %0, 5
  tail call void @bar(i1 zeroext %4, i32 signext %3)
  ret void
}

define void @addi_snez(i32 signext %0, i32 signext %1) {
; NOFUSION-LABEL: addi_snez:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    addi a2, a0, -5
; NOFUSION-NEXT:    mulw a1, a1, a0
; NOFUSION-NEXT:    snez a0, a2
; NOFUSION-NEXT:    tail bar
;
; FUSION-LABEL: addi_snez:
; FUSION:       # %bb.0:
; FUSION-NEXT:    addi a2, a0, -5
; FUSION-NEXT:    snez a2, a2
; FUSION-NEXT:    mulw a1, a1, a0
; FUSION-NEXT:    mv a0, a2
; FUSION-NEXT:    tail bar
  %3 = mul i32 %1, %0
  %4 = icmp ne i32 %0, 5
  tail call void @bar(i1 zeroext %4, i32 signext %3)
  ret void
}

define void @sub_snez(i64 %0, i64 %1, i64 %2, i64 %3) {
; NOFUSION-LABEL: sub_snez:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    mul a2, a1, a2
; NOFUSION-NEXT:    sub a3, a3, a0
; NOFUSION-NEXT:    snez a0, a3
; NOFUSION-NEXT:    mul a1, a2, a1
; NOFUSION-NEXT:    tail baz
;
; FUSION-LABEL: sub_snez:
; FUSION:       # %bb.0:
; FUSION-NEXT:    mul a2, a1, a2
; FUSION-NEXT:    sub a3, a3, a0
; FUSION-NEXT:    snez a0, a3
; FUSION-NEXT:    mul a1, a2, a1
; FUSION-NEXT:    tail baz
  %5 = sub i64 %3, %0
  %6 = mul i64 %1, %2
  %7 = icmp ne i64 %5, 0
  %8 = mul i64 %6, %1
  tail call void @baz(i1 zeroext %7, i64 %8)
  ret void
}
