; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S -mtriple=riscv64 -mattr='+d,+v' -riscv-codegenprepare < %s | FileCheck %s

define float @vpreduce_fadd_nxv4f32(float %s, <vscale x 4 x float> %v) {
; CHECK-LABEL: define float @vpreduce_fadd_nxv4f32(
; CHECK-SAME: float [[S:%.*]], <vscale x 4 x float> [[V:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.s.f.nxv4f32.i64(<vscale x 4 x float> poison, float [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP2]], i64 7, i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP3]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call reassoc float @llvm.vp.reduce.fadd.nxv4f32(float %s, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

; -0.0 should be canonicalized into 0.0 when nsz is present.
define float @vpreduce_fadd_nxv4f32_nsz(<vscale x 4 x float> %v) {
; CHECK-LABEL: define float @vpreduce_fadd_nxv4f32_nsz(
; CHECK-SAME: <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call nsz float @llvm.vp.reduce.fadd.nxv4f32(float 0.000000e+00, <vscale x 4 x float> [[V]], <vscale x 4 x i1> splat (i1 true), i32 32)
; CHECK-NEXT:    ret float [[R]]
;
  %r = call nsz float @llvm.vp.reduce.fadd.nxv4f32(float -0.0, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define float @vpreduce_fmax_nxv4f32(float %s, <vscale x 4 x float> %v) {
; CHECK-LABEL: define float @vpreduce_fmax_nxv4f32(
; CHECK-SAME: float [[S:%.*]], <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.s.f.nxv4f32.i64(<vscale x 4 x float> poison, float [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredmax.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP3]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call float @llvm.vp.reduce.fmax.nxv4f32(float %s, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define float @vpreduce_fmax_neutral_nxv4f32(<vscale x 4 x float> %v) {
  ; neutral = -QNaN
; CHECK-LABEL: define float @vpreduce_fmax_neutral_nxv4f32(
; CHECK-SAME: <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredmax.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP2]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call float @llvm.vp.reduce.fmax.nxv4f32(float 0xFFF8000000000000, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define float @vpreduce_fmax_neutral_nnan_nxv4f32(<vscale x 4 x float> %v) {
  ; neutral = -Inf
; CHECK-LABEL: define float @vpreduce_fmax_neutral_nnan_nxv4f32(
; CHECK-SAME: <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredmax.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP2]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call nnan float @llvm.vp.reduce.fmax.nxv4f32(float 0xFFF0000000000000, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define float @vpreduce_fmin_nxv4f32(float %s, <vscale x 4 x float> %v) {
; CHECK-LABEL: define float @vpreduce_fmin_nxv4f32(
; CHECK-SAME: float [[S:%.*]], <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.s.f.nxv4f32.i64(<vscale x 4 x float> poison, float [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredmin.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP3]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call float @llvm.vp.reduce.fmin.nxv4f32(float %s, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define float @vpreduce_fmin_neutral_nxv4f32(<vscale x 4 x float> %v) {
  ; neutral = QNaN
; CHECK-LABEL: define float @vpreduce_fmin_neutral_nxv4f32(
; CHECK-SAME: <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredmin.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP2]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call float @llvm.vp.reduce.fmin.nxv4f32(float 0x7FF8000000000000, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define float @vpreduce_fmin_neutral_nnan_nxv4f32(<vscale x 4 x float> %v) {
  ; neutral = Inf
; CHECK-LABEL: define float @vpreduce_fmin_neutral_nnan_nxv4f32(
; CHECK-SAME: <vscale x 4 x float> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredmin.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP2]], i64 0
; CHECK-NEXT:    ret float [[R]]
;
  %r = call nnan float @llvm.vp.reduce.fmin.nxv4f32(float 0x7FF0000000000000, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret float %r
}

define i32 @vpreduce_add_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_add_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.add.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_smax_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_smax_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredmax.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.smax.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_smax_neutral_nxv4i32(<vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_smax_neutral_nxv4i32(
; CHECK-SAME: <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[V]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredmax.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.smax.nxv4i32(i32 -2147483648, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_umax_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_umax_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredmaxu.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.umax.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_umax_neutral_nxv4i32(<vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_umax_neutral_nxv4i32(
; CHECK-SAME: <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredmaxu.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP2]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.umax.nxv4i32(i32 0, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_smin_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_smin_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredmin.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.smin.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_smin_neutral_nxv4i32(<vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_smin_neutral_nxv4i32(
; CHECK-SAME: <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[V]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredmin.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.smin.nxv4i32(i32 2147483647, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_umin_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_umin_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredminu.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.umin.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_umin_neutral_nxv4i32(<vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_umin_neutral_nxv4i32(
; CHECK-SAME: <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredminu.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP2]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.umin.nxv4i32(i32 -1, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_and_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_and_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredand.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.and.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_and_neutral_nxv4i32(<vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_and_neutral_nxv4i32(
; CHECK-SAME: <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[V]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredand.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP1]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP2]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.and.nxv4i32(i32 -1, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_or_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_or_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredor.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.or.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

define i32 @vpreduce_xor_nxv4i32(i32 %s, <vscale x 4 x i32> %v) {
; CHECK-LABEL: define i32 @vpreduce_xor_nxv4i32(
; CHECK-SAME: i32 [[S:%.*]], <vscale x 4 x i32> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.s.x.nxv4i32.i64(<vscale x 4 x i32> poison, i32 [[S]], i64 32)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv4i32(<vscale x 4 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredxor.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> poison, <vscale x 4 x i32> [[V]], <vscale x 2 x i32> [[TMP2]], i64 32)
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x i32> [[TMP3]], i64 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %r = call i32 @llvm.vp.reduce.xor.nxv4i32(i32 %s, <vscale x 4 x i32> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i32 %r
}

; Make sure the optimization kicks in for VL that is proved non-zero in another basic block.
define float @vpreduce_cross_bb(float %s, <vscale x 4 x float> %v, i32 %evl) {
; CHECK-LABEL: define float @vpreduce_cross_bb(
; CHECK-SAME: float [[S:%.*]], <vscale x 4 x float> [[V:%.*]], i32 [[EVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[COND:%.*]] = icmp ugt i32 [[EVL]], 0
; CHECK-NEXT:    br i1 [[COND]], label [[BB0:%.*]], label [[BB1:%.*]]
; CHECK:       bb0:
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[EVL]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.s.f.nxv4f32.i64(<vscale x 4 x float> poison, float [[S]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x float> @llvm.vector.extract.nxv2f32.nxv4f32(<vscale x 4 x float> [[TMP2]], i64 0)
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv4f32.i64(<vscale x 2 x float> poison, <vscale x 4 x float> [[V]], <vscale x 2 x float> [[TMP3]], i64 7, i64 [[TMP1]])
; CHECK-NEXT:    [[R:%.*]] = extractelement <vscale x 2 x float> [[TMP4]], i64 0
; CHECK-NEXT:    br label [[BB_END:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br label [[BB_END]]
; CHECK:       bb_end:
; CHECK-NEXT:    [[K:%.*]] = phi float [ [[R]], [[BB0]] ], [ 0.000000e+00, [[BB1]] ]
; CHECK-NEXT:    ret float [[K]]
;
  %cond = icmp ugt i32 %evl, 0
  br i1 %cond, label %bb0, label %bb1

bb0:
  %r = call reassoc float @llvm.vp.reduce.fadd.nxv4f32(float %s, <vscale x 4 x float> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 %evl)
  br label %bb_end

bb1:
  br label %bb_end

bb_end:
  %k = phi float [%r, %bb0], [0.0, %bb1]
  ret float %k
}

; Bool vector is not a valid candidate
define i1 @vpreduce_or_nxv4i1(i1 %s, <vscale x 4 x i1> %v) {
; CHECK-LABEL: define i1 @vpreduce_or_nxv4i1(
; CHECK-SAME: i1 [[S:%.*]], <vscale x 4 x i1> [[V:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[R:%.*]] = call i1 @llvm.vp.reduce.or.nxv4i1(i1 [[S]], <vscale x 4 x i1> [[V]], <vscale x 4 x i1> splat (i1 true), i32 32)
; CHECK-NEXT:    ret i1 [[R]]
;
  %r = call i1 @llvm.vp.reduce.or.nxv4i1(i1 %s, <vscale x 4 x i1> %v,
  <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer),
  i32 32)
  ret i1 %r
}

declare float @llvm.vp.reduce.fadd.nxv4f32(float, <vscale x 4 x float>, <vscale x 4 x i1>, i32)
declare float @llvm.vp.reduce.fmin.nxv4f32(float, <vscale x 4 x float>, <vscale x 4 x i1>, i32)
declare float @llvm.vp.reduce.fmax.nxv4f32(float, <vscale x 4 x float>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.add.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.smax.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.umax.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.smin.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.umin.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.and.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.or.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare i1 @llvm.vp.reduce.or.nxv4i1(i1, <vscale x 4 x i1>, <vscale x 4 x i1>, i32)
declare i32 @llvm.vp.reduce.xor.nxv4i32(i32, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
