; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -riscv-type-promotion -S | FileCheck %s

target triple = "riscv64"

define void @test_smax(i32* %arg) {
; CHECK-LABEL: @test_smax(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[I:%.*]] = icmp sgt i64 [[I7:%.*]], 0
; CHECK-NEXT:    br i1 [[I]], label [[BB10:%.*]], label [[BB11:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[I3:%.*]] = phi i64 [ 0, [[BB:%.*]] ], [ [[I8:%.*]], [[BB2]] ]
; CHECK-NEXT:    [[I4:%.*]] = phi i64 [ -2147483648, [[BB]] ], [ [[I7]], [[BB2]] ]
; CHECK-NEXT:    [[I5:%.*]] = getelementptr inbounds i32, ptr [[ARG:%.*]], i64 [[I3]]
; CHECK-NEXT:    [[I6:%.*]] = load i32, ptr [[I5]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = sext i32 [[I6]] to i64
; CHECK-NEXT:    [[I7]] = tail call i64 @llvm.smax.i64(i64 [[TMP0]], i64 [[I4]])
; CHECK-NEXT:    [[I8]] = add nuw nsw i64 [[I3]], 1
; CHECK-NEXT:    [[I9:%.*]] = icmp eq i64 [[I8]], 1024
; CHECK-NEXT:    br i1 [[I9]], label [[BB1:%.*]], label [[BB2]]
; CHECK:       bb10:
; CHECK-NEXT:    tail call void @bar()
; CHECK-NEXT:    br label [[BB11]]
; CHECK:       bb11:
; CHECK-NEXT:    ret void
;
bb:
  br label %bb2

bb1:                                              ; preds = %bb2
  %i = icmp sgt i32 %i7, 0
  br i1 %i, label %bb10, label %bb11

bb2:                                              ; preds = %bb2, %bb
  %i3 = phi i64 [ 0, %bb ], [ %i8, %bb2 ]
  %i4 = phi i32 [ -2147483648, %bb ], [ %i7, %bb2 ]
  %i5 = getelementptr inbounds i32, i32* %arg, i64 %i3
  %i6 = load i32, i32* %i5, align 4
  %i7 = tail call i32 @llvm.smax.i32(i32 %i6, i32 %i4)
  %i8 = add nuw nsw i64 %i3, 1
  %i9 = icmp eq i64 %i8, 1024
  br i1 %i9, label %bb1, label %bb2

bb10:                                             ; preds = %bb1
  tail call void @bar()
  br label %bb11

bb11:                                             ; preds = %bb10, %bb1
  ret void
}

declare void @bar()

declare i32 @llvm.smax.i32(i32, i32)
