; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 | FileCheck %s

define i32 @foo(i32 %x) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srli a1, a0, 15
; CHECK-NEXT:    lui a2, 16
; CHECK-NEXT:    addi a2, a2, 1
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:    slli a2, a1, 16
; CHECK-NEXT:    subw a2, a2, a1
; CHECK-NEXT:    addw a0, a0, a2
; CHECK-NEXT:    xor a0, a0, a2
; CHECK-NEXT:    ret
  %a = lshr i32 %x, 15
  %b = and i32 %a, 65537
  %c = mul i32 %b, 65535
  %d = add i32 %x, %c
  %e = xor i32 %d, %c
  ret i32 %e
}
