; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-p550 \
; RUN:   | FileCheck %s --check-prefix=NoAA
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-p550 -riscv-use-aa \
; RUN:   | FileCheck %s --check-prefix=UseAA

%class.reg1 = type { i32, i32, i8, ptr }
%class.reg2 = type { ptr, i32, i32 }

define void @test_aa(ptr nocapture readonly align 8 dereferenceable(24) %this, ptr nocapture  writeonly %region) align 2 {
; NoAA-LABEL: test_aa:
; NoAA:       # %bb.0: # %entry
; NoAA-NEXT:    ld a0, 0(a0)
; NoAA-NEXT:    rori a0, a0, 32
; NoAA-NEXT:    sd a0, 8(a1)
; NoAA-NEXT:    ret
;
; UseAA-LABEL: test_aa:
; UseAA:       # %bb.0: # %entry
; UseAA-NEXT:    ld a0, 0(a0)
; UseAA-NEXT:    rori a0, a0, 32
; UseAA-NEXT:    sd a0, 8(a1)
; UseAA-NEXT:    ret
entry:
  %regnum = getelementptr inbounds %class.reg1, ptr %this, i64 0, i32 1
  %0 = load i32, ptr %regnum, align 4, !tbaa !4
  %fillnum = getelementptr inbounds %class.reg2, ptr %region, i64 0, i32 1
  store i32 %0, ptr %fillnum, align 8, !tbaa !11
  %1 = load i32, ptr %this, align 8, !tbaa !13
  %fillnum2 = getelementptr inbounds %class.reg2, ptr %region, i64 0, i32 2
  store i32 %1, ptr %fillnum2, align 4, !tbaa !14
  ret void
}

!4 = !{!5, !6, i64 4}
!5 = !{!"reg1", !6, i64 0, !6, i64 4, !9, i64 8, !10, i64 16}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C++ TBAA"}
!9 = !{!"bool", !7, i64 0}
!10 = !{!"any pointer", !7, i64 0}
!11 = !{!12, !6, i64 8}
!12 = !{!"reg2", !10, i64 0, !6, i64 8, !6, i64 12}
!13 = !{!5, !6, i64 0}
!14 = !{!12, !6, i64 12}
