; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+f,+d,+v,+zfh,+zvfh -riscv-v-vector-bits-min=128 -verify-machineinstrs | FileCheck %s

define void @test_0(ptr %in, ptr %out) {
; CHECK-LABEL: test_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 12(a0)
; CHECK-NEXT:    lbu a3, 13(a0)
; CHECK-NEXT:    lbu a4, 14(a0)
; CHECK-NEXT:    lbu a5, 15(a0)
; CHECK-NEXT:    lbu a6, 8(a0)
; CHECK-NEXT:    lbu a7, 9(a0)
; CHECK-NEXT:    lbu t0, 10(a0)
; CHECK-NEXT:    lbu t1, 11(a0)
; CHECK-NEXT:    lbu t2, 4(a0)
; CHECK-NEXT:    lbu t3, 5(a0)
; CHECK-NEXT:    lbu t4, 6(a0)
; CHECK-NEXT:    lbu t5, 7(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 1(a0)
; CHECK-NEXT:    lbu s1, 2(a0)
; CHECK-NEXT:    lbu a0, 3(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i8, ptr %in, i64 15
  %0 = load i8, ptr %arrayidx, align 1
  %vecinit = insertelement <16 x i8> undef, i8 %0, i64 0
  %arrayidx1 = getelementptr inbounds i8, ptr %in, i64 14
  %1 = load i8, ptr %arrayidx1, align 1
  %vecinit2 = insertelement <16 x i8> %vecinit, i8 %1, i64 1
  %arrayidx3 = getelementptr inbounds i8, ptr %in, i64 13
  %2 = load i8, ptr %arrayidx3, align 1
  %vecinit4 = insertelement <16 x i8> %vecinit2, i8 %2, i64 2
  %arrayidx5 = getelementptr inbounds i8, ptr %in, i64 12
  %3 = load i8, ptr %arrayidx5, align 1
  %vecinit6 = insertelement <16 x i8> %vecinit4, i8 %3, i64 3
  %arrayidx7 = getelementptr inbounds i8, ptr %in, i64 11
  %4 = load i8, ptr %arrayidx7, align 1
  %vecinit8 = insertelement <16 x i8> %vecinit6, i8 %4, i64 4
  %arrayidx9 = getelementptr inbounds i8, ptr %in, i64 10
  %5 = load i8, ptr %arrayidx9, align 1
  %vecinit10 = insertelement <16 x i8> %vecinit8, i8 %5, i64 5
  %arrayidx11 = getelementptr inbounds i8, ptr %in, i64 9
  %6 = load i8, ptr %arrayidx11, align 1
  %vecinit12 = insertelement <16 x i8> %vecinit10, i8 %6, i64 6
  %arrayidx13 = getelementptr inbounds i8, ptr %in, i64 8
  %7 = load i8, ptr %arrayidx13, align 1
  %vecinit14 = insertelement <16 x i8> %vecinit12, i8 %7, i64 7
  %arrayidx15 = getelementptr inbounds i8, ptr %in, i64 7
  %8 = load i8, ptr %arrayidx15, align 1
  %vecinit16 = insertelement <16 x i8> %vecinit14, i8 %8, i64 8
  %arrayidx17 = getelementptr inbounds i8, ptr %in, i64 6
  %9 = load i8, ptr %arrayidx17, align 1
  %vecinit18 = insertelement <16 x i8> %vecinit16, i8 %9, i64 9
  %arrayidx19 = getelementptr inbounds i8, ptr %in, i64 5
  %10 = load i8, ptr %arrayidx19, align 1
  %vecinit20 = insertelement <16 x i8> %vecinit18, i8 %10, i64 10
  %arrayidx21 = getelementptr inbounds i8, ptr %in, i64 4
  %11 = load i8, ptr %arrayidx21, align 1
  %vecinit22 = insertelement <16 x i8> %vecinit20, i8 %11, i64 11
  %arrayidx23 = getelementptr inbounds i8, ptr %in, i64 3
  %12 = load i8, ptr %arrayidx23, align 1
  %vecinit24 = insertelement <16 x i8> %vecinit22, i8 %12, i64 12
  %arrayidx25 = getelementptr inbounds i8, ptr %in, i64 2
  %13 = load i8, ptr %arrayidx25, align 1
  %vecinit26 = insertelement <16 x i8> %vecinit24, i8 %13, i64 13
  %arrayidx27 = getelementptr inbounds i8, ptr %in, i64 1
  %14 = load i8, ptr %arrayidx27, align 1
  %vecinit28 = insertelement <16 x i8> %vecinit26, i8 %14, i64 14
  %15 = load i8, ptr %in, align 1
  %vecinit30 = insertelement <16 x i8> %vecinit28, i8 %15, i64 15
  store <16 x i8> %vecinit30, ptr %out, align 1
  ret void
}

define void @test_1(ptr %in, ptr %out) {
; CHECK-LABEL: test_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lb a2, 4(a0)
; CHECK-NEXT:    lb a3, 5(a0)
; CHECK-NEXT:    lb a4, 6(a0)
; CHECK-NEXT:    lb a5, 7(a0)
; CHECK-NEXT:    lb a6, 0(a0)
; CHECK-NEXT:    lb a7, 1(a0)
; CHECK-NEXT:    lb t0, 2(a0)
; CHECK-NEXT:    lb a0, 3(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i8, ptr %in, i64 7
  %0 = load i8, ptr %arrayidx, align 1
  %conv = sext i8 %0 to i16
  %vecinit = insertelement <8 x i16> undef, i16 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i8, ptr %in, i64 6
  %1 = load i8, ptr %arrayidx1, align 1
  %conv2 = sext i8 %1 to i16
  %vecinit3 = insertelement <8 x i16> %vecinit, i16 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i8, ptr %in, i64 5
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = sext i8 %2 to i16
  %vecinit6 = insertelement <8 x i16> %vecinit3, i16 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i8, ptr %in, i64 4
  %3 = load i8, ptr %arrayidx7, align 1
  %conv8 = sext i8 %3 to i16
  %vecinit9 = insertelement <8 x i16> %vecinit6, i16 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i8, ptr %in, i64 3
  %4 = load i8, ptr %arrayidx10, align 1
  %conv11 = sext i8 %4 to i16
  %vecinit12 = insertelement <8 x i16> %vecinit9, i16 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i8, ptr %in, i64 2
  %5 = load i8, ptr %arrayidx13, align 1
  %conv14 = sext i8 %5 to i16
  %vecinit15 = insertelement <8 x i16> %vecinit12, i16 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i8, ptr %in, i64 1
  %6 = load i8, ptr %arrayidx16, align 1
  %conv17 = sext i8 %6 to i16
  %vecinit18 = insertelement <8 x i16> %vecinit15, i16 %conv17, i64 6
  %7 = load i8, ptr %in, align 1
  %conv20 = sext i8 %7 to i16
  %vecinit21 = insertelement <8 x i16> %vecinit18, i16 %conv20, i64 7
  store <8 x i16> %vecinit21, ptr %out, align 2
  ret void
}

define void @test_2(ptr %in, ptr %out) {
; CHECK-LABEL: test_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lb a2, 0(a0)
; CHECK-NEXT:    lb a3, 1(a0)
; CHECK-NEXT:    lb a4, 2(a0)
; CHECK-NEXT:    lb a0, 3(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i8, ptr %in, i64 3
  %0 = load i8, ptr %arrayidx, align 1
  %conv = sext i8 %0 to i32
  %vecinit = insertelement <4 x i32> undef, i32 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i8, ptr %in, i64 2
  %1 = load i8, ptr %arrayidx1, align 1
  %conv2 = sext i8 %1 to i32
  %vecinit3 = insertelement <4 x i32> %vecinit, i32 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i8, ptr %in, i64 1
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = sext i8 %2 to i32
  %vecinit6 = insertelement <4 x i32> %vecinit3, i32 %conv5, i64 2
  %3 = load i8, ptr %in, align 1
  %conv8 = sext i8 %3 to i32
  %vecinit9 = insertelement <4 x i32> %vecinit6, i32 %conv8, i64 3
  store <4 x i32> %vecinit9, ptr %out, align 4
  ret void
}

define void @test_4(ptr %in, ptr %out) {
; CHECK-LABEL: test_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 24(a0)
; CHECK-NEXT:    lbu a3, 26(a0)
; CHECK-NEXT:    lbu a4, 28(a0)
; CHECK-NEXT:    lbu a5, 30(a0)
; CHECK-NEXT:    lbu a6, 16(a0)
; CHECK-NEXT:    lbu a7, 18(a0)
; CHECK-NEXT:    lbu t0, 20(a0)
; CHECK-NEXT:    lbu t1, 22(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 10(a0)
; CHECK-NEXT:    lbu t4, 12(a0)
; CHECK-NEXT:    lbu t5, 14(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 2(a0)
; CHECK-NEXT:    lbu s1, 4(a0)
; CHECK-NEXT:    lbu a0, 6(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i16, ptr %in, i64 15
  %0 = load i16, ptr %arrayidx, align 2
  %conv = trunc i16 %0 to i8
  %vecinit = insertelement <16 x i8> undef, i8 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i16, ptr %in, i64 14
  %1 = load i16, ptr %arrayidx1, align 2
  %conv2 = trunc i16 %1 to i8
  %vecinit3 = insertelement <16 x i8> %vecinit, i8 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i16, ptr %in, i64 13
  %2 = load i16, ptr %arrayidx4, align 2
  %conv5 = trunc i16 %2 to i8
  %vecinit6 = insertelement <16 x i8> %vecinit3, i8 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i16, ptr %in, i64 12
  %3 = load i16, ptr %arrayidx7, align 2
  %conv8 = trunc i16 %3 to i8
  %vecinit9 = insertelement <16 x i8> %vecinit6, i8 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i16, ptr %in, i64 11
  %4 = load i16, ptr %arrayidx10, align 2
  %conv11 = trunc i16 %4 to i8
  %vecinit12 = insertelement <16 x i8> %vecinit9, i8 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i16, ptr %in, i64 10
  %5 = load i16, ptr %arrayidx13, align 2
  %conv14 = trunc i16 %5 to i8
  %vecinit15 = insertelement <16 x i8> %vecinit12, i8 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i16, ptr %in, i64 9
  %6 = load i16, ptr %arrayidx16, align 2
  %conv17 = trunc i16 %6 to i8
  %vecinit18 = insertelement <16 x i8> %vecinit15, i8 %conv17, i64 6
  %arrayidx19 = getelementptr inbounds i16, ptr %in, i64 8
  %7 = load i16, ptr %arrayidx19, align 2
  %conv20 = trunc i16 %7 to i8
  %vecinit21 = insertelement <16 x i8> %vecinit18, i8 %conv20, i64 7
  %arrayidx22 = getelementptr inbounds i16, ptr %in, i64 7
  %8 = load i16, ptr %arrayidx22, align 2
  %conv23 = trunc i16 %8 to i8
  %vecinit24 = insertelement <16 x i8> %vecinit21, i8 %conv23, i64 8
  %arrayidx25 = getelementptr inbounds i16, ptr %in, i64 6
  %9 = load i16, ptr %arrayidx25, align 2
  %conv26 = trunc i16 %9 to i8
  %vecinit27 = insertelement <16 x i8> %vecinit24, i8 %conv26, i64 9
  %arrayidx28 = getelementptr inbounds i16, ptr %in, i64 5
  %10 = load i16, ptr %arrayidx28, align 2
  %conv29 = trunc i16 %10 to i8
  %vecinit30 = insertelement <16 x i8> %vecinit27, i8 %conv29, i64 10
  %arrayidx31 = getelementptr inbounds i16, ptr %in, i64 4
  %11 = load i16, ptr %arrayidx31, align 2
  %conv32 = trunc i16 %11 to i8
  %vecinit33 = insertelement <16 x i8> %vecinit30, i8 %conv32, i64 11
  %arrayidx34 = getelementptr inbounds i16, ptr %in, i64 3
  %12 = load i16, ptr %arrayidx34, align 2
  %conv35 = trunc i16 %12 to i8
  %vecinit36 = insertelement <16 x i8> %vecinit33, i8 %conv35, i64 12
  %arrayidx37 = getelementptr inbounds i16, ptr %in, i64 2
  %13 = load i16, ptr %arrayidx37, align 2
  %conv38 = trunc i16 %13 to i8
  %vecinit39 = insertelement <16 x i8> %vecinit36, i8 %conv38, i64 13
  %arrayidx40 = getelementptr inbounds i16, ptr %in, i64 1
  %14 = load i16, ptr %arrayidx40, align 2
  %conv41 = trunc i16 %14 to i8
  %vecinit42 = insertelement <16 x i8> %vecinit39, i8 %conv41, i64 14
  %15 = load i16, ptr %in, align 2
  %conv44 = trunc i16 %15 to i8
  %vecinit45 = insertelement <16 x i8> %vecinit42, i8 %conv44, i64 15
  store <16 x i8> %vecinit45, ptr %out, align 1
  ret void
}

define void @test_5(ptr %in, ptr %out) {
; CHECK-LABEL: test_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 8(a0)
; CHECK-NEXT:    lh a3, 10(a0)
; CHECK-NEXT:    lh a4, 12(a0)
; CHECK-NEXT:    lh a5, 14(a0)
; CHECK-NEXT:    lh a6, 0(a0)
; CHECK-NEXT:    lh a7, 2(a0)
; CHECK-NEXT:    lh t0, 4(a0)
; CHECK-NEXT:    lh a0, 6(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i16, ptr %in, i64 7
  %0 = load i16, ptr %arrayidx, align 2
  %vecinit = insertelement <8 x i16> undef, i16 %0, i64 0
  %arrayidx1 = getelementptr inbounds i16, ptr %in, i64 6
  %1 = load i16, ptr %arrayidx1, align 2
  %vecinit2 = insertelement <8 x i16> %vecinit, i16 %1, i64 1
  %arrayidx3 = getelementptr inbounds i16, ptr %in, i64 5
  %2 = load i16, ptr %arrayidx3, align 2
  %vecinit4 = insertelement <8 x i16> %vecinit2, i16 %2, i64 2
  %arrayidx5 = getelementptr inbounds i16, ptr %in, i64 4
  %3 = load i16, ptr %arrayidx5, align 2
  %vecinit6 = insertelement <8 x i16> %vecinit4, i16 %3, i64 3
  %arrayidx7 = getelementptr inbounds i16, ptr %in, i64 3
  %4 = load i16, ptr %arrayidx7, align 2
  %vecinit8 = insertelement <8 x i16> %vecinit6, i16 %4, i64 4
  %arrayidx9 = getelementptr inbounds i16, ptr %in, i64 2
  %5 = load i16, ptr %arrayidx9, align 2
  %vecinit10 = insertelement <8 x i16> %vecinit8, i16 %5, i64 5
  %arrayidx11 = getelementptr inbounds i16, ptr %in, i64 1
  %6 = load i16, ptr %arrayidx11, align 2
  %vecinit12 = insertelement <8 x i16> %vecinit10, i16 %6, i64 6
  %7 = load i16, ptr %in, align 2
  %vecinit14 = insertelement <8 x i16> %vecinit12, i16 %7, i64 7
  store <8 x i16> %vecinit14, ptr %out, align 2
  ret void
}

define void @test_6(ptr %in, ptr %out) {
; CHECK-LABEL: test_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 0(a0)
; CHECK-NEXT:    lh a3, 2(a0)
; CHECK-NEXT:    lh a4, 4(a0)
; CHECK-NEXT:    lh a0, 6(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i16, ptr %in, i64 3
  %0 = load i16, ptr %arrayidx, align 2
  %conv = sext i16 %0 to i32
  %vecinit = insertelement <4 x i32> undef, i32 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i16, ptr %in, i64 2
  %1 = load i16, ptr %arrayidx1, align 2
  %conv2 = sext i16 %1 to i32
  %vecinit3 = insertelement <4 x i32> %vecinit, i32 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i16, ptr %in, i64 1
  %2 = load i16, ptr %arrayidx4, align 2
  %conv5 = sext i16 %2 to i32
  %vecinit6 = insertelement <4 x i32> %vecinit3, i32 %conv5, i64 2
  %3 = load i16, ptr %in, align 2
  %conv8 = sext i16 %3 to i32
  %vecinit9 = insertelement <4 x i32> %vecinit6, i32 %conv8, i64 3
  store <4 x i32> %vecinit9, ptr %out, align 4
  ret void
}

define void @test_8(ptr %in, ptr %out) {
; CHECK-LABEL: test_8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 48(a0)
; CHECK-NEXT:    lbu a3, 52(a0)
; CHECK-NEXT:    lbu a4, 56(a0)
; CHECK-NEXT:    lbu a5, 60(a0)
; CHECK-NEXT:    lbu a6, 32(a0)
; CHECK-NEXT:    lbu a7, 36(a0)
; CHECK-NEXT:    lbu t0, 40(a0)
; CHECK-NEXT:    lbu t1, 44(a0)
; CHECK-NEXT:    lbu t2, 16(a0)
; CHECK-NEXT:    lbu t3, 20(a0)
; CHECK-NEXT:    lbu t4, 24(a0)
; CHECK-NEXT:    lbu t5, 28(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 4(a0)
; CHECK-NEXT:    lbu s1, 8(a0)
; CHECK-NEXT:    lbu a0, 12(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i32, ptr %in, i64 15
  %0 = load i32, ptr %arrayidx, align 4
  %conv = trunc i32 %0 to i8
  %vecinit = insertelement <16 x i8> undef, i8 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i32, ptr %in, i64 14
  %1 = load i32, ptr %arrayidx1, align 4
  %conv2 = trunc i32 %1 to i8
  %vecinit3 = insertelement <16 x i8> %vecinit, i8 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i32, ptr %in, i64 13
  %2 = load i32, ptr %arrayidx4, align 4
  %conv5 = trunc i32 %2 to i8
  %vecinit6 = insertelement <16 x i8> %vecinit3, i8 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i32, ptr %in, i64 12
  %3 = load i32, ptr %arrayidx7, align 4
  %conv8 = trunc i32 %3 to i8
  %vecinit9 = insertelement <16 x i8> %vecinit6, i8 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i32, ptr %in, i64 11
  %4 = load i32, ptr %arrayidx10, align 4
  %conv11 = trunc i32 %4 to i8
  %vecinit12 = insertelement <16 x i8> %vecinit9, i8 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i32, ptr %in, i64 10
  %5 = load i32, ptr %arrayidx13, align 4
  %conv14 = trunc i32 %5 to i8
  %vecinit15 = insertelement <16 x i8> %vecinit12, i8 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i32, ptr %in, i64 9
  %6 = load i32, ptr %arrayidx16, align 4
  %conv17 = trunc i32 %6 to i8
  %vecinit18 = insertelement <16 x i8> %vecinit15, i8 %conv17, i64 6
  %arrayidx19 = getelementptr inbounds i32, ptr %in, i64 8
  %7 = load i32, ptr %arrayidx19, align 4
  %conv20 = trunc i32 %7 to i8
  %vecinit21 = insertelement <16 x i8> %vecinit18, i8 %conv20, i64 7
  %arrayidx22 = getelementptr inbounds i32, ptr %in, i64 7
  %8 = load i32, ptr %arrayidx22, align 4
  %conv23 = trunc i32 %8 to i8
  %vecinit24 = insertelement <16 x i8> %vecinit21, i8 %conv23, i64 8
  %arrayidx25 = getelementptr inbounds i32, ptr %in, i64 6
  %9 = load i32, ptr %arrayidx25, align 4
  %conv26 = trunc i32 %9 to i8
  %vecinit27 = insertelement <16 x i8> %vecinit24, i8 %conv26, i64 9
  %arrayidx28 = getelementptr inbounds i32, ptr %in, i64 5
  %10 = load i32, ptr %arrayidx28, align 4
  %conv29 = trunc i32 %10 to i8
  %vecinit30 = insertelement <16 x i8> %vecinit27, i8 %conv29, i64 10
  %arrayidx31 = getelementptr inbounds i32, ptr %in, i64 4
  %11 = load i32, ptr %arrayidx31, align 4
  %conv32 = trunc i32 %11 to i8
  %vecinit33 = insertelement <16 x i8> %vecinit30, i8 %conv32, i64 11
  %arrayidx34 = getelementptr inbounds i32, ptr %in, i64 3
  %12 = load i32, ptr %arrayidx34, align 4
  %conv35 = trunc i32 %12 to i8
  %vecinit36 = insertelement <16 x i8> %vecinit33, i8 %conv35, i64 12
  %arrayidx37 = getelementptr inbounds i32, ptr %in, i64 2
  %13 = load i32, ptr %arrayidx37, align 4
  %conv38 = trunc i32 %13 to i8
  %vecinit39 = insertelement <16 x i8> %vecinit36, i8 %conv38, i64 13
  %arrayidx40 = getelementptr inbounds i32, ptr %in, i64 1
  %14 = load i32, ptr %arrayidx40, align 4
  %conv41 = trunc i32 %14 to i8
  %vecinit42 = insertelement <16 x i8> %vecinit39, i8 %conv41, i64 14
  %15 = load i32, ptr %in, align 4
  %conv44 = trunc i32 %15 to i8
  %vecinit45 = insertelement <16 x i8> %vecinit42, i8 %conv44, i64 15
  store <16 x i8> %vecinit45, ptr %out, align 1
  ret void
}

define void @test_9(ptr %in, ptr %out) {
; CHECK-LABEL: test_9:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 16(a0)
; CHECK-NEXT:    lh a3, 20(a0)
; CHECK-NEXT:    lh a4, 24(a0)
; CHECK-NEXT:    lh a5, 28(a0)
; CHECK-NEXT:    lh a6, 0(a0)
; CHECK-NEXT:    lh a7, 4(a0)
; CHECK-NEXT:    lh t0, 8(a0)
; CHECK-NEXT:    lh a0, 12(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i32, ptr %in, i64 7
  %0 = load i32, ptr %arrayidx, align 4
  %conv = trunc i32 %0 to i16
  %vecinit = insertelement <8 x i16> undef, i16 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i32, ptr %in, i64 6
  %1 = load i32, ptr %arrayidx1, align 4
  %conv2 = trunc i32 %1 to i16
  %vecinit3 = insertelement <8 x i16> %vecinit, i16 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i32, ptr %in, i64 5
  %2 = load i32, ptr %arrayidx4, align 4
  %conv5 = trunc i32 %2 to i16
  %vecinit6 = insertelement <8 x i16> %vecinit3, i16 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i32, ptr %in, i64 4
  %3 = load i32, ptr %arrayidx7, align 4
  %conv8 = trunc i32 %3 to i16
  %vecinit9 = insertelement <8 x i16> %vecinit6, i16 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i32, ptr %in, i64 3
  %4 = load i32, ptr %arrayidx10, align 4
  %conv11 = trunc i32 %4 to i16
  %vecinit12 = insertelement <8 x i16> %vecinit9, i16 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i32, ptr %in, i64 2
  %5 = load i32, ptr %arrayidx13, align 4
  %conv14 = trunc i32 %5 to i16
  %vecinit15 = insertelement <8 x i16> %vecinit12, i16 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i32, ptr %in, i64 1
  %6 = load i32, ptr %arrayidx16, align 4
  %conv17 = trunc i32 %6 to i16
  %vecinit18 = insertelement <8 x i16> %vecinit15, i16 %conv17, i64 6
  %7 = load i32, ptr %in, align 4
  %conv20 = trunc i32 %7 to i16
  %vecinit21 = insertelement <8 x i16> %vecinit18, i16 %conv20, i64 7
  store <8 x i16> %vecinit21, ptr %out, align 2
  ret void
}

define void @test_10(ptr %in, ptr %out) {
; CHECK-LABEL: test_10:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lw a2, 0(a0)
; CHECK-NEXT:    lw a3, 4(a0)
; CHECK-NEXT:    lw a4, 8(a0)
; CHECK-NEXT:    lw a0, 12(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i32, ptr %in, i64 3
  %0 = load i32, ptr %arrayidx, align 4
  %vecinit = insertelement <4 x i32> undef, i32 %0, i64 0
  %arrayidx1 = getelementptr inbounds i32, ptr %in, i64 2
  %1 = load i32, ptr %arrayidx1, align 4
  %vecinit2 = insertelement <4 x i32> %vecinit, i32 %1, i64 1
  %arrayidx3 = getelementptr inbounds i32, ptr %in, i64 1
  %2 = load i32, ptr %arrayidx3, align 4
  %vecinit4 = insertelement <4 x i32> %vecinit2, i32 %2, i64 2
  %3 = load i32, ptr %in, align 4
  %vecinit6 = insertelement <4 x i32> %vecinit4, i32 %3, i64 3
  store <4 x i32> %vecinit6, ptr %out, align 4
  ret void
}

define void @test_12(ptr %in, ptr %out) {
; CHECK-LABEL: test_12:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 96(a0)
; CHECK-NEXT:    lbu a3, 104(a0)
; CHECK-NEXT:    lbu a4, 112(a0)
; CHECK-NEXT:    lbu a5, 120(a0)
; CHECK-NEXT:    lbu a6, 64(a0)
; CHECK-NEXT:    lbu a7, 72(a0)
; CHECK-NEXT:    lbu t0, 80(a0)
; CHECK-NEXT:    lbu t1, 88(a0)
; CHECK-NEXT:    lbu t2, 32(a0)
; CHECK-NEXT:    lbu t3, 40(a0)
; CHECK-NEXT:    lbu t4, 48(a0)
; CHECK-NEXT:    lbu t5, 56(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 8(a0)
; CHECK-NEXT:    lbu s1, 16(a0)
; CHECK-NEXT:    lbu a0, 24(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 15
  %0 = load i64, ptr %arrayidx, align 8
  %conv = trunc i64 %0 to i8
  %vecinit = insertelement <16 x i8> undef, i8 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i64, ptr %in, i64 14
  %1 = load i64, ptr %arrayidx1, align 8
  %conv2 = trunc i64 %1 to i8
  %vecinit3 = insertelement <16 x i8> %vecinit, i8 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i64, ptr %in, i64 13
  %2 = load i64, ptr %arrayidx4, align 8
  %conv5 = trunc i64 %2 to i8
  %vecinit6 = insertelement <16 x i8> %vecinit3, i8 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i64, ptr %in, i64 12
  %3 = load i64, ptr %arrayidx7, align 8
  %conv8 = trunc i64 %3 to i8
  %vecinit9 = insertelement <16 x i8> %vecinit6, i8 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i64, ptr %in, i64 11
  %4 = load i64, ptr %arrayidx10, align 8
  %conv11 = trunc i64 %4 to i8
  %vecinit12 = insertelement <16 x i8> %vecinit9, i8 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i64, ptr %in, i64 10
  %5 = load i64, ptr %arrayidx13, align 8
  %conv14 = trunc i64 %5 to i8
  %vecinit15 = insertelement <16 x i8> %vecinit12, i8 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i64, ptr %in, i64 9
  %6 = load i64, ptr %arrayidx16, align 8
  %conv17 = trunc i64 %6 to i8
  %vecinit18 = insertelement <16 x i8> %vecinit15, i8 %conv17, i64 6
  %arrayidx19 = getelementptr inbounds i64, ptr %in, i64 8
  %7 = load i64, ptr %arrayidx19, align 8
  %conv20 = trunc i64 %7 to i8
  %vecinit21 = insertelement <16 x i8> %vecinit18, i8 %conv20, i64 7
  %arrayidx22 = getelementptr inbounds i64, ptr %in, i64 7
  %8 = load i64, ptr %arrayidx22, align 8
  %conv23 = trunc i64 %8 to i8
  %vecinit24 = insertelement <16 x i8> %vecinit21, i8 %conv23, i64 8
  %arrayidx25 = getelementptr inbounds i64, ptr %in, i64 6
  %9 = load i64, ptr %arrayidx25, align 8
  %conv26 = trunc i64 %9 to i8
  %vecinit27 = insertelement <16 x i8> %vecinit24, i8 %conv26, i64 9
  %arrayidx28 = getelementptr inbounds i64, ptr %in, i64 5
  %10 = load i64, ptr %arrayidx28, align 8
  %conv29 = trunc i64 %10 to i8
  %vecinit30 = insertelement <16 x i8> %vecinit27, i8 %conv29, i64 10
  %arrayidx31 = getelementptr inbounds i64, ptr %in, i64 4
  %11 = load i64, ptr %arrayidx31, align 8
  %conv32 = trunc i64 %11 to i8
  %vecinit33 = insertelement <16 x i8> %vecinit30, i8 %conv32, i64 11
  %arrayidx34 = getelementptr inbounds i64, ptr %in, i64 3
  %12 = load i64, ptr %arrayidx34, align 8
  %conv35 = trunc i64 %12 to i8
  %vecinit36 = insertelement <16 x i8> %vecinit33, i8 %conv35, i64 12
  %arrayidx37 = getelementptr inbounds i64, ptr %in, i64 2
  %13 = load i64, ptr %arrayidx37, align 8
  %conv38 = trunc i64 %13 to i8
  %vecinit39 = insertelement <16 x i8> %vecinit36, i8 %conv38, i64 13
  %arrayidx40 = getelementptr inbounds i64, ptr %in, i64 1
  %14 = load i64, ptr %arrayidx40, align 8
  %conv41 = trunc i64 %14 to i8
  %vecinit42 = insertelement <16 x i8> %vecinit39, i8 %conv41, i64 14
  %15 = load i64, ptr %in, align 8
  %conv44 = trunc i64 %15 to i8
  %vecinit45 = insertelement <16 x i8> %vecinit42, i8 %conv44, i64 15
  store <16 x i8> %vecinit45, ptr %out, align 1
  ret void
}

define void @test_13(ptr %in, ptr %out) {
; CHECK-LABEL: test_13:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 32(a0)
; CHECK-NEXT:    lh a3, 40(a0)
; CHECK-NEXT:    lh a4, 48(a0)
; CHECK-NEXT:    lh a5, 56(a0)
; CHECK-NEXT:    lh a6, 0(a0)
; CHECK-NEXT:    lh a7, 8(a0)
; CHECK-NEXT:    lh t0, 16(a0)
; CHECK-NEXT:    lh a0, 24(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 7
  %0 = load i64, ptr %arrayidx, align 8
  %conv = trunc i64 %0 to i16
  %vecinit = insertelement <8 x i16> undef, i16 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i64, ptr %in, i64 6
  %1 = load i64, ptr %arrayidx1, align 8
  %conv2 = trunc i64 %1 to i16
  %vecinit3 = insertelement <8 x i16> %vecinit, i16 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i64, ptr %in, i64 5
  %2 = load i64, ptr %arrayidx4, align 8
  %conv5 = trunc i64 %2 to i16
  %vecinit6 = insertelement <8 x i16> %vecinit3, i16 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i64, ptr %in, i64 4
  %3 = load i64, ptr %arrayidx7, align 8
  %conv8 = trunc i64 %3 to i16
  %vecinit9 = insertelement <8 x i16> %vecinit6, i16 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i64, ptr %in, i64 3
  %4 = load i64, ptr %arrayidx10, align 8
  %conv11 = trunc i64 %4 to i16
  %vecinit12 = insertelement <8 x i16> %vecinit9, i16 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i64, ptr %in, i64 2
  %5 = load i64, ptr %arrayidx13, align 8
  %conv14 = trunc i64 %5 to i16
  %vecinit15 = insertelement <8 x i16> %vecinit12, i16 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i64, ptr %in, i64 1
  %6 = load i64, ptr %arrayidx16, align 8
  %conv17 = trunc i64 %6 to i16
  %vecinit18 = insertelement <8 x i16> %vecinit15, i16 %conv17, i64 6
  %7 = load i64, ptr %in, align 8
  %conv20 = trunc i64 %7 to i16
  %vecinit21 = insertelement <8 x i16> %vecinit18, i16 %conv20, i64 7
  store <8 x i16> %vecinit21, ptr %out, align 2
  ret void
}

define void @test_14(ptr %in, ptr %out) {
; CHECK-LABEL: test_14:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lw a2, 0(a0)
; CHECK-NEXT:    lw a3, 8(a0)
; CHECK-NEXT:    lw a4, 16(a0)
; CHECK-NEXT:    lw a0, 24(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 3
  %0 = load i64, ptr %arrayidx, align 8
  %conv = trunc i64 %0 to i32
  %vecinit = insertelement <4 x i32> undef, i32 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i64, ptr %in, i64 2
  %1 = load i64, ptr %arrayidx1, align 8
  %conv2 = trunc i64 %1 to i32
  %vecinit3 = insertelement <4 x i32> %vecinit, i32 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i64, ptr %in, i64 1
  %2 = load i64, ptr %arrayidx4, align 8
  %conv5 = trunc i64 %2 to i32
  %vecinit6 = insertelement <4 x i32> %vecinit3, i32 %conv5, i64 2
  %3 = load i64, ptr %in, align 8
  %conv8 = trunc i64 %3 to i32
  %vecinit9 = insertelement <4 x i32> %vecinit6, i32 %conv8, i64 3
  store <4 x i32> %vecinit9, ptr %out, align 4
  ret void
}

define void @test_15(ptr %in, ptr %out) {
; CHECK-LABEL: test_15:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 0(a0)
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    sd a2, 8(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 1
  %0 = load i64, ptr %arrayidx, align 8
  %vecinit = insertelement <2 x i64> undef, i64 %0, i64 0
  %1 = load i64, ptr %in, align 8
  %vecinit2 = insertelement <2 x i64> %vecinit, i64 %1, i64 1
  store <2 x i64> %vecinit2, ptr %out, align 8
  ret void
}

define void @test_16(ptr %in, ptr %out) {
; CHECK-LABEL: test_16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 12(a0)
; CHECK-NEXT:    lbu a3, 13(a0)
; CHECK-NEXT:    lbu a4, 14(a0)
; CHECK-NEXT:    lbu a5, 15(a0)
; CHECK-NEXT:    lbu a6, 8(a0)
; CHECK-NEXT:    lbu a7, 9(a0)
; CHECK-NEXT:    lbu t0, 10(a0)
; CHECK-NEXT:    lbu t1, 11(a0)
; CHECK-NEXT:    lbu t2, 4(a0)
; CHECK-NEXT:    lbu t3, 5(a0)
; CHECK-NEXT:    lbu t4, 6(a0)
; CHECK-NEXT:    lbu t5, 7(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 1(a0)
; CHECK-NEXT:    lbu s1, 2(a0)
; CHECK-NEXT:    lbu a0, 3(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i8, ptr %in, i64 15
  %0 = load i8, ptr %arrayidx, align 1
  %vecinit = insertelement <16 x i8> undef, i8 %0, i64 0
  %arrayidx1 = getelementptr inbounds i8, ptr %in, i64 14
  %1 = load i8, ptr %arrayidx1, align 1
  %vecinit2 = insertelement <16 x i8> %vecinit, i8 %1, i64 1
  %arrayidx3 = getelementptr inbounds i8, ptr %in, i64 13
  %2 = load i8, ptr %arrayidx3, align 1
  %vecinit4 = insertelement <16 x i8> %vecinit2, i8 %2, i64 2
  %arrayidx5 = getelementptr inbounds i8, ptr %in, i64 12
  %3 = load i8, ptr %arrayidx5, align 1
  %vecinit6 = insertelement <16 x i8> %vecinit4, i8 %3, i64 3
  %arrayidx7 = getelementptr inbounds i8, ptr %in, i64 11
  %4 = load i8, ptr %arrayidx7, align 1
  %vecinit8 = insertelement <16 x i8> %vecinit6, i8 %4, i64 4
  %arrayidx9 = getelementptr inbounds i8, ptr %in, i64 10
  %5 = load i8, ptr %arrayidx9, align 1
  %vecinit10 = insertelement <16 x i8> %vecinit8, i8 %5, i64 5
  %arrayidx11 = getelementptr inbounds i8, ptr %in, i64 9
  %6 = load i8, ptr %arrayidx11, align 1
  %vecinit12 = insertelement <16 x i8> %vecinit10, i8 %6, i64 6
  %arrayidx13 = getelementptr inbounds i8, ptr %in, i64 8
  %7 = load i8, ptr %arrayidx13, align 1
  %vecinit14 = insertelement <16 x i8> %vecinit12, i8 %7, i64 7
  %arrayidx15 = getelementptr inbounds i8, ptr %in, i64 7
  %8 = load i8, ptr %arrayidx15, align 1
  %vecinit16 = insertelement <16 x i8> %vecinit14, i8 %8, i64 8
  %arrayidx17 = getelementptr inbounds i8, ptr %in, i64 6
  %9 = load i8, ptr %arrayidx17, align 1
  %vecinit18 = insertelement <16 x i8> %vecinit16, i8 %9, i64 9
  %arrayidx19 = getelementptr inbounds i8, ptr %in, i64 5
  %10 = load i8, ptr %arrayidx19, align 1
  %vecinit20 = insertelement <16 x i8> %vecinit18, i8 %10, i64 10
  %arrayidx21 = getelementptr inbounds i8, ptr %in, i64 4
  %11 = load i8, ptr %arrayidx21, align 1
  %vecinit22 = insertelement <16 x i8> %vecinit20, i8 %11, i64 11
  %arrayidx23 = getelementptr inbounds i8, ptr %in, i64 3
  %12 = load i8, ptr %arrayidx23, align 1
  %vecinit24 = insertelement <16 x i8> %vecinit22, i8 %12, i64 12
  %arrayidx25 = getelementptr inbounds i8, ptr %in, i64 2
  %13 = load i8, ptr %arrayidx25, align 1
  %vecinit26 = insertelement <16 x i8> %vecinit24, i8 %13, i64 13
  %arrayidx27 = getelementptr inbounds i8, ptr %in, i64 1
  %14 = load i8, ptr %arrayidx27, align 1
  %vecinit28 = insertelement <16 x i8> %vecinit26, i8 %14, i64 14
  %15 = load i8, ptr %in, align 1
  %vecinit30 = insertelement <16 x i8> %vecinit28, i8 %15, i64 15
  store <16 x i8> %vecinit30, ptr %out, align 1
  ret void
}

define void @test_17(ptr %in, ptr %out) {
; CHECK-LABEL: test_17:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lbu a2, 4(a0)
; CHECK-NEXT:    lbu a3, 5(a0)
; CHECK-NEXT:    lbu a4, 6(a0)
; CHECK-NEXT:    lbu a5, 7(a0)
; CHECK-NEXT:    lbu a6, 0(a0)
; CHECK-NEXT:    lbu a7, 1(a0)
; CHECK-NEXT:    lbu t0, 2(a0)
; CHECK-NEXT:    lbu a0, 3(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i8, ptr %in, i64 7
  %0 = load i8, ptr %arrayidx, align 1
  %conv = zext i8 %0 to i16
  %vecinit = insertelement <8 x i16> undef, i16 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i8, ptr %in, i64 6
  %1 = load i8, ptr %arrayidx1, align 1
  %conv2 = zext i8 %1 to i16
  %vecinit3 = insertelement <8 x i16> %vecinit, i16 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i8, ptr %in, i64 5
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = zext i8 %2 to i16
  %vecinit6 = insertelement <8 x i16> %vecinit3, i16 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i8, ptr %in, i64 4
  %3 = load i8, ptr %arrayidx7, align 1
  %conv8 = zext i8 %3 to i16
  %vecinit9 = insertelement <8 x i16> %vecinit6, i16 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i8, ptr %in, i64 3
  %4 = load i8, ptr %arrayidx10, align 1
  %conv11 = zext i8 %4 to i16
  %vecinit12 = insertelement <8 x i16> %vecinit9, i16 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i8, ptr %in, i64 2
  %5 = load i8, ptr %arrayidx13, align 1
  %conv14 = zext i8 %5 to i16
  %vecinit15 = insertelement <8 x i16> %vecinit12, i16 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i8, ptr %in, i64 1
  %6 = load i8, ptr %arrayidx16, align 1
  %conv17 = zext i8 %6 to i16
  %vecinit18 = insertelement <8 x i16> %vecinit15, i16 %conv17, i64 6
  %7 = load i8, ptr %in, align 1
  %conv20 = zext i8 %7 to i16
  %vecinit21 = insertelement <8 x i16> %vecinit18, i16 %conv20, i64 7
  store <8 x i16> %vecinit21, ptr %out, align 2
  ret void
}

define void @test_18(ptr %in, ptr %out) {
; CHECK-LABEL: test_18:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lbu a2, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a0, 3(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i8, ptr %in, i64 3
  %0 = load i8, ptr %arrayidx, align 1
  %conv = zext i8 %0 to i32
  %vecinit = insertelement <4 x i32> undef, i32 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i8, ptr %in, i64 2
  %1 = load i8, ptr %arrayidx1, align 1
  %conv2 = zext i8 %1 to i32
  %vecinit3 = insertelement <4 x i32> %vecinit, i32 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i8, ptr %in, i64 1
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = zext i8 %2 to i32
  %vecinit6 = insertelement <4 x i32> %vecinit3, i32 %conv5, i64 2
  %3 = load i8, ptr %in, align 1
  %conv8 = zext i8 %3 to i32
  %vecinit9 = insertelement <4 x i32> %vecinit6, i32 %conv8, i64 3
  store <4 x i32> %vecinit9, ptr %out, align 4
  ret void
}

define void @test_20(ptr %in, ptr %out) {
; CHECK-LABEL: test_20:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 24(a0)
; CHECK-NEXT:    lbu a3, 26(a0)
; CHECK-NEXT:    lbu a4, 28(a0)
; CHECK-NEXT:    lbu a5, 30(a0)
; CHECK-NEXT:    lbu a6, 16(a0)
; CHECK-NEXT:    lbu a7, 18(a0)
; CHECK-NEXT:    lbu t0, 20(a0)
; CHECK-NEXT:    lbu t1, 22(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 10(a0)
; CHECK-NEXT:    lbu t4, 12(a0)
; CHECK-NEXT:    lbu t5, 14(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 2(a0)
; CHECK-NEXT:    lbu s1, 4(a0)
; CHECK-NEXT:    lbu a0, 6(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i16, ptr %in, i64 15
  %0 = load i16, ptr %arrayidx, align 2
  %conv = trunc i16 %0 to i8
  %vecinit = insertelement <16 x i8> undef, i8 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i16, ptr %in, i64 14
  %1 = load i16, ptr %arrayidx1, align 2
  %conv2 = trunc i16 %1 to i8
  %vecinit3 = insertelement <16 x i8> %vecinit, i8 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i16, ptr %in, i64 13
  %2 = load i16, ptr %arrayidx4, align 2
  %conv5 = trunc i16 %2 to i8
  %vecinit6 = insertelement <16 x i8> %vecinit3, i8 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i16, ptr %in, i64 12
  %3 = load i16, ptr %arrayidx7, align 2
  %conv8 = trunc i16 %3 to i8
  %vecinit9 = insertelement <16 x i8> %vecinit6, i8 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i16, ptr %in, i64 11
  %4 = load i16, ptr %arrayidx10, align 2
  %conv11 = trunc i16 %4 to i8
  %vecinit12 = insertelement <16 x i8> %vecinit9, i8 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i16, ptr %in, i64 10
  %5 = load i16, ptr %arrayidx13, align 2
  %conv14 = trunc i16 %5 to i8
  %vecinit15 = insertelement <16 x i8> %vecinit12, i8 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i16, ptr %in, i64 9
  %6 = load i16, ptr %arrayidx16, align 2
  %conv17 = trunc i16 %6 to i8
  %vecinit18 = insertelement <16 x i8> %vecinit15, i8 %conv17, i64 6
  %arrayidx19 = getelementptr inbounds i16, ptr %in, i64 8
  %7 = load i16, ptr %arrayidx19, align 2
  %conv20 = trunc i16 %7 to i8
  %vecinit21 = insertelement <16 x i8> %vecinit18, i8 %conv20, i64 7
  %arrayidx22 = getelementptr inbounds i16, ptr %in, i64 7
  %8 = load i16, ptr %arrayidx22, align 2
  %conv23 = trunc i16 %8 to i8
  %vecinit24 = insertelement <16 x i8> %vecinit21, i8 %conv23, i64 8
  %arrayidx25 = getelementptr inbounds i16, ptr %in, i64 6
  %9 = load i16, ptr %arrayidx25, align 2
  %conv26 = trunc i16 %9 to i8
  %vecinit27 = insertelement <16 x i8> %vecinit24, i8 %conv26, i64 9
  %arrayidx28 = getelementptr inbounds i16, ptr %in, i64 5
  %10 = load i16, ptr %arrayidx28, align 2
  %conv29 = trunc i16 %10 to i8
  %vecinit30 = insertelement <16 x i8> %vecinit27, i8 %conv29, i64 10
  %arrayidx31 = getelementptr inbounds i16, ptr %in, i64 4
  %11 = load i16, ptr %arrayidx31, align 2
  %conv32 = trunc i16 %11 to i8
  %vecinit33 = insertelement <16 x i8> %vecinit30, i8 %conv32, i64 11
  %arrayidx34 = getelementptr inbounds i16, ptr %in, i64 3
  %12 = load i16, ptr %arrayidx34, align 2
  %conv35 = trunc i16 %12 to i8
  %vecinit36 = insertelement <16 x i8> %vecinit33, i8 %conv35, i64 12
  %arrayidx37 = getelementptr inbounds i16, ptr %in, i64 2
  %13 = load i16, ptr %arrayidx37, align 2
  %conv38 = trunc i16 %13 to i8
  %vecinit39 = insertelement <16 x i8> %vecinit36, i8 %conv38, i64 13
  %arrayidx40 = getelementptr inbounds i16, ptr %in, i64 1
  %14 = load i16, ptr %arrayidx40, align 2
  %conv41 = trunc i16 %14 to i8
  %vecinit42 = insertelement <16 x i8> %vecinit39, i8 %conv41, i64 14
  %15 = load i16, ptr %in, align 2
  %conv44 = trunc i16 %15 to i8
  %vecinit45 = insertelement <16 x i8> %vecinit42, i8 %conv44, i64 15
  store <16 x i8> %vecinit45, ptr %out, align 1
  ret void
}

define void @test_21(ptr %in, ptr %out) {
; CHECK-LABEL: test_21:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 8(a0)
; CHECK-NEXT:    lh a3, 10(a0)
; CHECK-NEXT:    lh a4, 12(a0)
; CHECK-NEXT:    lh a5, 14(a0)
; CHECK-NEXT:    lh a6, 0(a0)
; CHECK-NEXT:    lh a7, 2(a0)
; CHECK-NEXT:    lh t0, 4(a0)
; CHECK-NEXT:    lh a0, 6(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i16, ptr %in, i64 7
  %0 = load i16, ptr %arrayidx, align 2
  %vecinit = insertelement <8 x i16> undef, i16 %0, i64 0
  %arrayidx1 = getelementptr inbounds i16, ptr %in, i64 6
  %1 = load i16, ptr %arrayidx1, align 2
  %vecinit2 = insertelement <8 x i16> %vecinit, i16 %1, i64 1
  %arrayidx3 = getelementptr inbounds i16, ptr %in, i64 5
  %2 = load i16, ptr %arrayidx3, align 2
  %vecinit4 = insertelement <8 x i16> %vecinit2, i16 %2, i64 2
  %arrayidx5 = getelementptr inbounds i16, ptr %in, i64 4
  %3 = load i16, ptr %arrayidx5, align 2
  %vecinit6 = insertelement <8 x i16> %vecinit4, i16 %3, i64 3
  %arrayidx7 = getelementptr inbounds i16, ptr %in, i64 3
  %4 = load i16, ptr %arrayidx7, align 2
  %vecinit8 = insertelement <8 x i16> %vecinit6, i16 %4, i64 4
  %arrayidx9 = getelementptr inbounds i16, ptr %in, i64 2
  %5 = load i16, ptr %arrayidx9, align 2
  %vecinit10 = insertelement <8 x i16> %vecinit8, i16 %5, i64 5
  %arrayidx11 = getelementptr inbounds i16, ptr %in, i64 1
  %6 = load i16, ptr %arrayidx11, align 2
  %vecinit12 = insertelement <8 x i16> %vecinit10, i16 %6, i64 6
  %7 = load i16, ptr %in, align 2
  %vecinit14 = insertelement <8 x i16> %vecinit12, i16 %7, i64 7
  store <8 x i16> %vecinit14, ptr %out, align 2
  ret void
}

define void @test_22(ptr %in, ptr %out) {
; CHECK-LABEL: test_22:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lhu a2, 0(a0)
; CHECK-NEXT:    lhu a3, 2(a0)
; CHECK-NEXT:    lhu a4, 4(a0)
; CHECK-NEXT:    lhu a0, 6(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i16, ptr %in, i64 3
  %0 = load i16, ptr %arrayidx, align 2
  %conv = zext i16 %0 to i32
  %vecinit = insertelement <4 x i32> undef, i32 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i16, ptr %in, i64 2
  %1 = load i16, ptr %arrayidx1, align 2
  %conv2 = zext i16 %1 to i32
  %vecinit3 = insertelement <4 x i32> %vecinit, i32 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i16, ptr %in, i64 1
  %2 = load i16, ptr %arrayidx4, align 2
  %conv5 = zext i16 %2 to i32
  %vecinit6 = insertelement <4 x i32> %vecinit3, i32 %conv5, i64 2
  %3 = load i16, ptr %in, align 2
  %conv8 = zext i16 %3 to i32
  %vecinit9 = insertelement <4 x i32> %vecinit6, i32 %conv8, i64 3
  store <4 x i32> %vecinit9, ptr %out, align 4
  ret void
}

define void @test_24(ptr %in, ptr %out) {
; CHECK-LABEL: test_24:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 48(a0)
; CHECK-NEXT:    lbu a3, 52(a0)
; CHECK-NEXT:    lbu a4, 56(a0)
; CHECK-NEXT:    lbu a5, 60(a0)
; CHECK-NEXT:    lbu a6, 32(a0)
; CHECK-NEXT:    lbu a7, 36(a0)
; CHECK-NEXT:    lbu t0, 40(a0)
; CHECK-NEXT:    lbu t1, 44(a0)
; CHECK-NEXT:    lbu t2, 16(a0)
; CHECK-NEXT:    lbu t3, 20(a0)
; CHECK-NEXT:    lbu t4, 24(a0)
; CHECK-NEXT:    lbu t5, 28(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 4(a0)
; CHECK-NEXT:    lbu s1, 8(a0)
; CHECK-NEXT:    lbu a0, 12(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i32, ptr %in, i64 15
  %0 = load i32, ptr %arrayidx, align 4
  %conv = trunc i32 %0 to i8
  %vecinit = insertelement <16 x i8> undef, i8 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i32, ptr %in, i64 14
  %1 = load i32, ptr %arrayidx1, align 4
  %conv2 = trunc i32 %1 to i8
  %vecinit3 = insertelement <16 x i8> %vecinit, i8 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i32, ptr %in, i64 13
  %2 = load i32, ptr %arrayidx4, align 4
  %conv5 = trunc i32 %2 to i8
  %vecinit6 = insertelement <16 x i8> %vecinit3, i8 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i32, ptr %in, i64 12
  %3 = load i32, ptr %arrayidx7, align 4
  %conv8 = trunc i32 %3 to i8
  %vecinit9 = insertelement <16 x i8> %vecinit6, i8 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i32, ptr %in, i64 11
  %4 = load i32, ptr %arrayidx10, align 4
  %conv11 = trunc i32 %4 to i8
  %vecinit12 = insertelement <16 x i8> %vecinit9, i8 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i32, ptr %in, i64 10
  %5 = load i32, ptr %arrayidx13, align 4
  %conv14 = trunc i32 %5 to i8
  %vecinit15 = insertelement <16 x i8> %vecinit12, i8 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i32, ptr %in, i64 9
  %6 = load i32, ptr %arrayidx16, align 4
  %conv17 = trunc i32 %6 to i8
  %vecinit18 = insertelement <16 x i8> %vecinit15, i8 %conv17, i64 6
  %arrayidx19 = getelementptr inbounds i32, ptr %in, i64 8
  %7 = load i32, ptr %arrayidx19, align 4
  %conv20 = trunc i32 %7 to i8
  %vecinit21 = insertelement <16 x i8> %vecinit18, i8 %conv20, i64 7
  %arrayidx22 = getelementptr inbounds i32, ptr %in, i64 7
  %8 = load i32, ptr %arrayidx22, align 4
  %conv23 = trunc i32 %8 to i8
  %vecinit24 = insertelement <16 x i8> %vecinit21, i8 %conv23, i64 8
  %arrayidx25 = getelementptr inbounds i32, ptr %in, i64 6
  %9 = load i32, ptr %arrayidx25, align 4
  %conv26 = trunc i32 %9 to i8
  %vecinit27 = insertelement <16 x i8> %vecinit24, i8 %conv26, i64 9
  %arrayidx28 = getelementptr inbounds i32, ptr %in, i64 5
  %10 = load i32, ptr %arrayidx28, align 4
  %conv29 = trunc i32 %10 to i8
  %vecinit30 = insertelement <16 x i8> %vecinit27, i8 %conv29, i64 10
  %arrayidx31 = getelementptr inbounds i32, ptr %in, i64 4
  %11 = load i32, ptr %arrayidx31, align 4
  %conv32 = trunc i32 %11 to i8
  %vecinit33 = insertelement <16 x i8> %vecinit30, i8 %conv32, i64 11
  %arrayidx34 = getelementptr inbounds i32, ptr %in, i64 3
  %12 = load i32, ptr %arrayidx34, align 4
  %conv35 = trunc i32 %12 to i8
  %vecinit36 = insertelement <16 x i8> %vecinit33, i8 %conv35, i64 12
  %arrayidx37 = getelementptr inbounds i32, ptr %in, i64 2
  %13 = load i32, ptr %arrayidx37, align 4
  %conv38 = trunc i32 %13 to i8
  %vecinit39 = insertelement <16 x i8> %vecinit36, i8 %conv38, i64 13
  %arrayidx40 = getelementptr inbounds i32, ptr %in, i64 1
  %14 = load i32, ptr %arrayidx40, align 4
  %conv41 = trunc i32 %14 to i8
  %vecinit42 = insertelement <16 x i8> %vecinit39, i8 %conv41, i64 14
  %15 = load i32, ptr %in, align 4
  %conv44 = trunc i32 %15 to i8
  %vecinit45 = insertelement <16 x i8> %vecinit42, i8 %conv44, i64 15
  store <16 x i8> %vecinit45, ptr %out, align 1
  ret void
}

define void @test_25(ptr %in, ptr %out) {
; CHECK-LABEL: test_25:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 16(a0)
; CHECK-NEXT:    lh a3, 20(a0)
; CHECK-NEXT:    lh a4, 24(a0)
; CHECK-NEXT:    lh a5, 28(a0)
; CHECK-NEXT:    lh a6, 0(a0)
; CHECK-NEXT:    lh a7, 4(a0)
; CHECK-NEXT:    lh t0, 8(a0)
; CHECK-NEXT:    lh a0, 12(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i32, ptr %in, i64 7
  %0 = load i32, ptr %arrayidx, align 4
  %conv = trunc i32 %0 to i16
  %vecinit = insertelement <8 x i16> undef, i16 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i32, ptr %in, i64 6
  %1 = load i32, ptr %arrayidx1, align 4
  %conv2 = trunc i32 %1 to i16
  %vecinit3 = insertelement <8 x i16> %vecinit, i16 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i32, ptr %in, i64 5
  %2 = load i32, ptr %arrayidx4, align 4
  %conv5 = trunc i32 %2 to i16
  %vecinit6 = insertelement <8 x i16> %vecinit3, i16 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i32, ptr %in, i64 4
  %3 = load i32, ptr %arrayidx7, align 4
  %conv8 = trunc i32 %3 to i16
  %vecinit9 = insertelement <8 x i16> %vecinit6, i16 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i32, ptr %in, i64 3
  %4 = load i32, ptr %arrayidx10, align 4
  %conv11 = trunc i32 %4 to i16
  %vecinit12 = insertelement <8 x i16> %vecinit9, i16 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i32, ptr %in, i64 2
  %5 = load i32, ptr %arrayidx13, align 4
  %conv14 = trunc i32 %5 to i16
  %vecinit15 = insertelement <8 x i16> %vecinit12, i16 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i32, ptr %in, i64 1
  %6 = load i32, ptr %arrayidx16, align 4
  %conv17 = trunc i32 %6 to i16
  %vecinit18 = insertelement <8 x i16> %vecinit15, i16 %conv17, i64 6
  %7 = load i32, ptr %in, align 4
  %conv20 = trunc i32 %7 to i16
  %vecinit21 = insertelement <8 x i16> %vecinit18, i16 %conv20, i64 7
  store <8 x i16> %vecinit21, ptr %out, align 2
  ret void
}

define void @test_26(ptr %in, ptr %out) {
; CHECK-LABEL: test_26:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lw a2, 0(a0)
; CHECK-NEXT:    lw a3, 4(a0)
; CHECK-NEXT:    lw a4, 8(a0)
; CHECK-NEXT:    lw a0, 12(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i32, ptr %in, i64 3
  %0 = load i32, ptr %arrayidx, align 4
  %vecinit = insertelement <4 x i32> undef, i32 %0, i64 0
  %arrayidx1 = getelementptr inbounds i32, ptr %in, i64 2
  %1 = load i32, ptr %arrayidx1, align 4
  %vecinit2 = insertelement <4 x i32> %vecinit, i32 %1, i64 1
  %arrayidx3 = getelementptr inbounds i32, ptr %in, i64 1
  %2 = load i32, ptr %arrayidx3, align 4
  %vecinit4 = insertelement <4 x i32> %vecinit2, i32 %2, i64 2
  %3 = load i32, ptr %in, align 4
  %vecinit6 = insertelement <4 x i32> %vecinit4, i32 %3, i64 3
  store <4 x i32> %vecinit6, ptr %out, align 4
  ret void
}

define void @test_28(ptr %in, ptr %out) {
; CHECK-LABEL: test_28:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    lbu a2, 96(a0)
; CHECK-NEXT:    lbu a3, 104(a0)
; CHECK-NEXT:    lbu a4, 112(a0)
; CHECK-NEXT:    lbu a5, 120(a0)
; CHECK-NEXT:    lbu a6, 64(a0)
; CHECK-NEXT:    lbu a7, 72(a0)
; CHECK-NEXT:    lbu t0, 80(a0)
; CHECK-NEXT:    lbu t1, 88(a0)
; CHECK-NEXT:    lbu t2, 32(a0)
; CHECK-NEXT:    lbu t3, 40(a0)
; CHECK-NEXT:    lbu t4, 48(a0)
; CHECK-NEXT:    lbu t5, 56(a0)
; CHECK-NEXT:    lbu t6, 0(a0)
; CHECK-NEXT:    lbu s0, 8(a0)
; CHECK-NEXT:    lbu s1, 16(a0)
; CHECK-NEXT:    lbu a0, 24(a0)
; CHECK-NEXT:    sb a0, 12(a1)
; CHECK-NEXT:    sb s1, 13(a1)
; CHECK-NEXT:    sb s0, 14(a1)
; CHECK-NEXT:    sb t6, 15(a1)
; CHECK-NEXT:    sb t5, 8(a1)
; CHECK-NEXT:    sb t4, 9(a1)
; CHECK-NEXT:    sb t3, 10(a1)
; CHECK-NEXT:    sb t2, 11(a1)
; CHECK-NEXT:    sb t1, 4(a1)
; CHECK-NEXT:    sb t0, 5(a1)
; CHECK-NEXT:    sb a7, 6(a1)
; CHECK-NEXT:    sb a6, 7(a1)
; CHECK-NEXT:    sb a5, 0(a1)
; CHECK-NEXT:    sb a4, 1(a1)
; CHECK-NEXT:    sb a3, 2(a1)
; CHECK-NEXT:    sb a2, 3(a1)
; CHECK-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 15
  %0 = load i64, ptr %arrayidx, align 8
  %conv = trunc i64 %0 to i8
  %vecinit = insertelement <16 x i8> undef, i8 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i64, ptr %in, i64 14
  %1 = load i64, ptr %arrayidx1, align 8
  %conv2 = trunc i64 %1 to i8
  %vecinit3 = insertelement <16 x i8> %vecinit, i8 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i64, ptr %in, i64 13
  %2 = load i64, ptr %arrayidx4, align 8
  %conv5 = trunc i64 %2 to i8
  %vecinit6 = insertelement <16 x i8> %vecinit3, i8 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i64, ptr %in, i64 12
  %3 = load i64, ptr %arrayidx7, align 8
  %conv8 = trunc i64 %3 to i8
  %vecinit9 = insertelement <16 x i8> %vecinit6, i8 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i64, ptr %in, i64 11
  %4 = load i64, ptr %arrayidx10, align 8
  %conv11 = trunc i64 %4 to i8
  %vecinit12 = insertelement <16 x i8> %vecinit9, i8 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i64, ptr %in, i64 10
  %5 = load i64, ptr %arrayidx13, align 8
  %conv14 = trunc i64 %5 to i8
  %vecinit15 = insertelement <16 x i8> %vecinit12, i8 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i64, ptr %in, i64 9
  %6 = load i64, ptr %arrayidx16, align 8
  %conv17 = trunc i64 %6 to i8
  %vecinit18 = insertelement <16 x i8> %vecinit15, i8 %conv17, i64 6
  %arrayidx19 = getelementptr inbounds i64, ptr %in, i64 8
  %7 = load i64, ptr %arrayidx19, align 8
  %conv20 = trunc i64 %7 to i8
  %vecinit21 = insertelement <16 x i8> %vecinit18, i8 %conv20, i64 7
  %arrayidx22 = getelementptr inbounds i64, ptr %in, i64 7
  %8 = load i64, ptr %arrayidx22, align 8
  %conv23 = trunc i64 %8 to i8
  %vecinit24 = insertelement <16 x i8> %vecinit21, i8 %conv23, i64 8
  %arrayidx25 = getelementptr inbounds i64, ptr %in, i64 6
  %9 = load i64, ptr %arrayidx25, align 8
  %conv26 = trunc i64 %9 to i8
  %vecinit27 = insertelement <16 x i8> %vecinit24, i8 %conv26, i64 9
  %arrayidx28 = getelementptr inbounds i64, ptr %in, i64 5
  %10 = load i64, ptr %arrayidx28, align 8
  %conv29 = trunc i64 %10 to i8
  %vecinit30 = insertelement <16 x i8> %vecinit27, i8 %conv29, i64 10
  %arrayidx31 = getelementptr inbounds i64, ptr %in, i64 4
  %11 = load i64, ptr %arrayidx31, align 8
  %conv32 = trunc i64 %11 to i8
  %vecinit33 = insertelement <16 x i8> %vecinit30, i8 %conv32, i64 11
  %arrayidx34 = getelementptr inbounds i64, ptr %in, i64 3
  %12 = load i64, ptr %arrayidx34, align 8
  %conv35 = trunc i64 %12 to i8
  %vecinit36 = insertelement <16 x i8> %vecinit33, i8 %conv35, i64 12
  %arrayidx37 = getelementptr inbounds i64, ptr %in, i64 2
  %13 = load i64, ptr %arrayidx37, align 8
  %conv38 = trunc i64 %13 to i8
  %vecinit39 = insertelement <16 x i8> %vecinit36, i8 %conv38, i64 13
  %arrayidx40 = getelementptr inbounds i64, ptr %in, i64 1
  %14 = load i64, ptr %arrayidx40, align 8
  %conv41 = trunc i64 %14 to i8
  %vecinit42 = insertelement <16 x i8> %vecinit39, i8 %conv41, i64 14
  %15 = load i64, ptr %in, align 8
  %conv44 = trunc i64 %15 to i8
  %vecinit45 = insertelement <16 x i8> %vecinit42, i8 %conv44, i64 15
  store <16 x i8> %vecinit45, ptr %out, align 1
  ret void
}

define void @test_29(ptr %in, ptr %out) {
; CHECK-LABEL: test_29:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a2, 32(a0)
; CHECK-NEXT:    lh a3, 40(a0)
; CHECK-NEXT:    lh a4, 48(a0)
; CHECK-NEXT:    lh a5, 56(a0)
; CHECK-NEXT:    lh a6, 0(a0)
; CHECK-NEXT:    lh a7, 8(a0)
; CHECK-NEXT:    lh t0, 16(a0)
; CHECK-NEXT:    lh a0, 24(a0)
; CHECK-NEXT:    sh a0, 8(a1)
; CHECK-NEXT:    sh t0, 10(a1)
; CHECK-NEXT:    sh a7, 12(a1)
; CHECK-NEXT:    sh a6, 14(a1)
; CHECK-NEXT:    sh a5, 0(a1)
; CHECK-NEXT:    sh a4, 2(a1)
; CHECK-NEXT:    sh a3, 4(a1)
; CHECK-NEXT:    sh a2, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 7
  %0 = load i64, ptr %arrayidx, align 8
  %conv = trunc i64 %0 to i16
  %vecinit = insertelement <8 x i16> undef, i16 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i64, ptr %in, i64 6
  %1 = load i64, ptr %arrayidx1, align 8
  %conv2 = trunc i64 %1 to i16
  %vecinit3 = insertelement <8 x i16> %vecinit, i16 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i64, ptr %in, i64 5
  %2 = load i64, ptr %arrayidx4, align 8
  %conv5 = trunc i64 %2 to i16
  %vecinit6 = insertelement <8 x i16> %vecinit3, i16 %conv5, i64 2
  %arrayidx7 = getelementptr inbounds i64, ptr %in, i64 4
  %3 = load i64, ptr %arrayidx7, align 8
  %conv8 = trunc i64 %3 to i16
  %vecinit9 = insertelement <8 x i16> %vecinit6, i16 %conv8, i64 3
  %arrayidx10 = getelementptr inbounds i64, ptr %in, i64 3
  %4 = load i64, ptr %arrayidx10, align 8
  %conv11 = trunc i64 %4 to i16
  %vecinit12 = insertelement <8 x i16> %vecinit9, i16 %conv11, i64 4
  %arrayidx13 = getelementptr inbounds i64, ptr %in, i64 2
  %5 = load i64, ptr %arrayidx13, align 8
  %conv14 = trunc i64 %5 to i16
  %vecinit15 = insertelement <8 x i16> %vecinit12, i16 %conv14, i64 5
  %arrayidx16 = getelementptr inbounds i64, ptr %in, i64 1
  %6 = load i64, ptr %arrayidx16, align 8
  %conv17 = trunc i64 %6 to i16
  %vecinit18 = insertelement <8 x i16> %vecinit15, i16 %conv17, i64 6
  %7 = load i64, ptr %in, align 8
  %conv20 = trunc i64 %7 to i16
  %vecinit21 = insertelement <8 x i16> %vecinit18, i16 %conv20, i64 7
  store <8 x i16> %vecinit21, ptr %out, align 2
  ret void
}

define void @test_30(ptr %in, ptr %out) {
; CHECK-LABEL: test_30:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lw a2, 0(a0)
; CHECK-NEXT:    lw a3, 8(a0)
; CHECK-NEXT:    lw a4, 16(a0)
; CHECK-NEXT:    lw a0, 24(a0)
; CHECK-NEXT:    sw a0, 0(a1)
; CHECK-NEXT:    sw a4, 4(a1)
; CHECK-NEXT:    sw a3, 8(a1)
; CHECK-NEXT:    sw a2, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 3
  %0 = load i64, ptr %arrayidx, align 8
  %conv = trunc i64 %0 to i32
  %vecinit = insertelement <4 x i32> undef, i32 %conv, i64 0
  %arrayidx1 = getelementptr inbounds i64, ptr %in, i64 2
  %1 = load i64, ptr %arrayidx1, align 8
  %conv2 = trunc i64 %1 to i32
  %vecinit3 = insertelement <4 x i32> %vecinit, i32 %conv2, i64 1
  %arrayidx4 = getelementptr inbounds i64, ptr %in, i64 1
  %2 = load i64, ptr %arrayidx4, align 8
  %conv5 = trunc i64 %2 to i32
  %vecinit6 = insertelement <4 x i32> %vecinit3, i32 %conv5, i64 2
  %3 = load i64, ptr %in, align 8
  %conv8 = trunc i64 %3 to i32
  %vecinit9 = insertelement <4 x i32> %vecinit6, i32 %conv8, i64 3
  store <4 x i32> %vecinit9, ptr %out, align 4
  ret void
}

define void @test_31(ptr %in, ptr %out) {
; CHECK-LABEL: test_31:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 0(a0)
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    sd a2, 8(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds i64, ptr %in, i64 1
  %0 = load i64, ptr %arrayidx, align 8
  %vecinit = insertelement <2 x i64> undef, i64 %0, i64 0
  %1 = load i64, ptr %in, align 8
  %vecinit2 = insertelement <2 x i64> %vecinit, i64 %1, i64 1
  store <2 x i64> %vecinit2, ptr %out, align 8
  ret void
}

define void @test_32(ptr %in, ptr %out) {
; CHECK-LABEL: test_32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    flh fa5, 8(a0)
; CHECK-NEXT:    flh fa4, 10(a0)
; CHECK-NEXT:    flh fa3, 12(a0)
; CHECK-NEXT:    flh fa2, 14(a0)
; CHECK-NEXT:    flh fa1, 0(a0)
; CHECK-NEXT:    flh fa0, 2(a0)
; CHECK-NEXT:    flh ft0, 4(a0)
; CHECK-NEXT:    flh ft1, 6(a0)
; CHECK-NEXT:    fsh ft1, 8(a1)
; CHECK-NEXT:    fsh ft0, 10(a1)
; CHECK-NEXT:    fsh fa0, 12(a1)
; CHECK-NEXT:    fsh fa1, 14(a1)
; CHECK-NEXT:    fsh fa2, 0(a1)
; CHECK-NEXT:    fsh fa3, 2(a1)
; CHECK-NEXT:    fsh fa4, 4(a1)
; CHECK-NEXT:    fsh fa5, 6(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds half, ptr %in, i64 7
  %0 = load half, ptr %arrayidx, align 2
  %vecinit = insertelement <8 x half> undef, half %0, i64 0
  %arrayidx1 = getelementptr inbounds half, ptr %in, i64 6
  %1 = load half, ptr %arrayidx1, align 2
  %vecinit2 = insertelement <8 x half> %vecinit, half %1, i64 1
  %arrayidx3 = getelementptr inbounds half, ptr %in, i64 5
  %2 = load half, ptr %arrayidx3, align 2
  %vecinit4 = insertelement <8 x half> %vecinit2, half %2, i64 2
  %arrayidx5 = getelementptr inbounds half, ptr %in, i64 4
  %3 = load half, ptr %arrayidx5, align 2
  %vecinit6 = insertelement <8 x half> %vecinit4, half %3, i64 3
  %arrayidx7 = getelementptr inbounds half, ptr %in, i64 3
  %4 = load half, ptr %arrayidx7, align 2
  %vecinit8 = insertelement <8 x half> %vecinit6, half %4, i64 4
  %arrayidx9 = getelementptr inbounds half, ptr %in, i64 2
  %5 = load half, ptr %arrayidx9, align 2
  %vecinit10 = insertelement <8 x half> %vecinit8, half %5, i64 5
  %arrayidx11 = getelementptr inbounds half, ptr %in, i64 1
  %6 = load half, ptr %arrayidx11, align 2
  %vecinit12 = insertelement <8 x half> %vecinit10, half %6, i64 6
  %7 = load half, ptr %in, align 2
  %vecinit14 = insertelement <8 x half> %vecinit12, half %7, i64 7
  store <8 x half> %vecinit14, ptr %out, align 2
  ret void
}

define void @test_36(ptr %in, ptr %out) {
; CHECK-LABEL: test_36:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    flw fa5, 0(a0)
; CHECK-NEXT:    flw fa4, 4(a0)
; CHECK-NEXT:    flw fa3, 8(a0)
; CHECK-NEXT:    flw fa2, 12(a0)
; CHECK-NEXT:    fsw fa2, 0(a1)
; CHECK-NEXT:    fsw fa3, 4(a1)
; CHECK-NEXT:    fsw fa4, 8(a1)
; CHECK-NEXT:    fsw fa5, 12(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds float, ptr %in, i64 3
  %0 = load float, ptr %arrayidx, align 4
  %vecinit = insertelement <4 x float> undef, float %0, i64 0
  %arrayidx1 = getelementptr inbounds float, ptr %in, i64 2
  %1 = load float, ptr %arrayidx1, align 4
  %vecinit2 = insertelement <4 x float> %vecinit, float %1, i64 1
  %arrayidx3 = getelementptr inbounds float, ptr %in, i64 1
  %2 = load float, ptr %arrayidx3, align 4
  %vecinit4 = insertelement <4 x float> %vecinit2, float %2, i64 2
  %3 = load float, ptr %in, align 4
  %vecinit6 = insertelement <4 x float> %vecinit4, float %3, i64 3
  store <4 x float> %vecinit6, ptr %out, align 4
  ret void
}

define void @test_40(ptr %in, ptr %out) {
; CHECK-LABEL: test_40:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fld fa5, 0(a0)
; CHECK-NEXT:    fld fa4, 8(a0)
; CHECK-NEXT:    fsd fa4, 0(a1)
; CHECK-NEXT:    fsd fa5, 8(a1)
; CHECK-NEXT:    ret
entry:
  %arrayidx = getelementptr inbounds double, ptr %in, i64 1
  %0 = load double, ptr %arrayidx, align 8
  %vecinit = insertelement <2 x double> undef, double %0, i64 0
  %1 = load double, ptr %in, align 8
  %vecinit2 = insertelement <2 x double> %vecinit, double %1, i64 1
  store <2 x double> %vecinit2, ptr %out, align 8
  ret void
}
