; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-x280 -riscv-force-tail-undisturbed | FileCheck %s -check-prefix=X280
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-x280n -riscv-force-tail-undisturbed | FileCheck %s -check-prefix=X280N

define void @skl_exp_f16(ptr nocapture noundef %y, ptr nocapture noundef readonly %x, i64 noundef %n) {
; X280-LABEL: skl_exp_f16:
; X280:       # %bb.0: # %entry
; X280-NEXT:    beqz a2, .LBB0_3
; X280-NEXT:  # %bb.1: # %for.body.preheader
; X280-NEXT:    lui a4, %hi(.LCPI0_0)
; X280-NEXT:    lui a5, %hi(.LCPI0_1)
; X280-NEXT:    lui a6, %hi(.LCPI0_2)
; X280-NEXT:    lui a7, %hi(.LCPI0_3)
; X280-NEXT:    li a3, 0
; X280-NEXT:    li t0, 15
; X280-NEXT:    flh fa5, %lo(.LCPI0_0)(a4)
; X280-NEXT:    lui a4, %hi(.LCPI0_6)
; X280-NEXT:    flh fa4, %lo(.LCPI0_1)(a5)
; X280-NEXT:    lui a5, %hi(.LCPI0_4)
; X280-NEXT:    flh fa3, %lo(.LCPI0_2)(a6)
; X280-NEXT:    lui a6, %hi(.LCPI0_5)
; X280-NEXT:    flh fa2, %lo(.LCPI0_3)(a7)
; X280-NEXT:    lui a7, %hi(.LCPI0_7)
; X280-NEXT:    flh fa1, %lo(.LCPI0_4)(a5)
; X280-NEXT:    addi a6, a6, %lo(.LCPI0_5)
; X280-NEXT:    flh fa0, %lo(.LCPI0_6)(a4)
; X280-NEXT:    addi a7, a7, %lo(.LCPI0_7)
; X280-NEXT:  .LBB0_2: # %for.body
; X280-NEXT:    # =>This Inner Loop Header: Depth=1
; X280-NEXT:    sh1add a4, a3, a1
; X280-NEXT:    sub a5, a2, a3
; X280-NEXT:    vsetvli a5, a5, e16, m8, tu, mu
; X280-NEXT:    vle16.v v8, (a4)
; X280-NEXT:    sh1add a4, a3, a0
; X280-NEXT:    add a3, a3, a5
; X280-NEXT:    vmfeq.vv v0, v8, v8
; X280-NEXT:    vfmax.vf v8, v8, fa5, v0.t
; X280-NEXT:    vfmin.vf v8, v8, fa4, v0.t
; X280-NEXT:    vfmul.vf v16, v8, fa3
; X280-NEXT:    vsetvli zero, zero, e8, m4, tu, ma
; X280-NEXT:    vfncvt.x.f.w v4, v16
; X280-NEXT:    vfwcvt.f.x.v v16, v4
; X280-NEXT:    vsetvli zero, zero, e16, m8, tu, ma
; X280-NEXT:    vlse16.v v24, (a7), zero
; X280-NEXT:    vfnmsac.vf v8, fa2, v16
; X280-NEXT:    vfnmsac.vf v8, fa1, v16
; X280-NEXT:    vlse16.v v16, (a6), zero
; X280-NEXT:    vfmacc.vf v16, fa0, v8
; X280-NEXT:    vfmadd.vv v16, v8, v24
; X280-NEXT:    vfmadd.vv v16, v8, v24
; X280-NEXT:    vsetvli zero, zero, e8, m4, tu, ma
; X280-NEXT:    vsra.vi v24, v4, 1
; X280-NEXT:    vsub.vv v12, v4, v24
; X280-NEXT:    vwadd.vx v8, v12, t0
; X280-NEXT:    vsetvli zero, zero, e16, m8, tu, ma
; X280-NEXT:    vsll.vi v8, v8, 10
; X280-NEXT:    vfmul.vv v8, v16, v8
; X280-NEXT:    vsetvli zero, zero, e8, m4, tu, ma
; X280-NEXT:    vwadd.vx v16, v24, t0
; X280-NEXT:    vsetvli zero, zero, e16, m8, tu, ma
; X280-NEXT:    vsll.vi v16, v16, 10
; X280-NEXT:    vfmul.vv v8, v8, v16
; X280-NEXT:    vse16.v v8, (a4)
; X280-NEXT:    bltu a3, a2, .LBB0_2
; X280-NEXT:  .LBB0_3: # %for.cond.cleanup
; X280-NEXT:    ret
;
; X280N-LABEL: skl_exp_f16:
; X280N:       # %bb.0: # %entry
; X280N-NEXT:    beqz a2, .LBB0_3
; X280N-NEXT:  # %bb.1: # %for.body.preheader
; X280N-NEXT:    lui a4, %hi(.LCPI0_0)
; X280N-NEXT:    lui a5, %hi(.LCPI0_1)
; X280N-NEXT:    lui a6, %hi(.LCPI0_2)
; X280N-NEXT:    lui a7, %hi(.LCPI0_3)
; X280N-NEXT:    li a3, 0
; X280N-NEXT:    li t0, 15
; X280N-NEXT:    flh fa5, %lo(.LCPI0_0)(a4)
; X280N-NEXT:    lui a4, %hi(.LCPI0_6)
; X280N-NEXT:    flh fa4, %lo(.LCPI0_1)(a5)
; X280N-NEXT:    lui a5, %hi(.LCPI0_4)
; X280N-NEXT:    flh fa3, %lo(.LCPI0_2)(a6)
; X280N-NEXT:    lui a6, %hi(.LCPI0_5)
; X280N-NEXT:    flh fa2, %lo(.LCPI0_3)(a7)
; X280N-NEXT:    lui a7, %hi(.LCPI0_7)
; X280N-NEXT:    flh fa1, %lo(.LCPI0_4)(a5)
; X280N-NEXT:    addi a6, a6, %lo(.LCPI0_5)
; X280N-NEXT:    flh fa0, %lo(.LCPI0_6)(a4)
; X280N-NEXT:    addi a7, a7, %lo(.LCPI0_7)
; X280N-NEXT:  .LBB0_2: # %for.body
; X280N-NEXT:    # =>This Inner Loop Header: Depth=1
; X280N-NEXT:    sh1add a4, a3, a1
; X280N-NEXT:    sub a5, a2, a3
; X280N-NEXT:    vsetvli a5, a5, e16, m8, tu, mu
; X280N-NEXT:    vle16.v v8, (a4)
; X280N-NEXT:    sh1add a4, a3, a0
; X280N-NEXT:    add a3, a3, a5
; X280N-NEXT:    vmfeq.vv v0, v8, v8
; X280N-NEXT:    vfmax.vf v8, v8, fa5, v0.t
; X280N-NEXT:    vfmin.vf v8, v8, fa4, v0.t
; X280N-NEXT:    vfmul.vf v16, v8, fa3
; X280N-NEXT:    vsetvli zero, zero, e8, m4, tu, ma
; X280N-NEXT:    vfncvt.x.f.w v4, v16
; X280N-NEXT:    vfwcvt.f.x.v v16, v4
; X280N-NEXT:    vsetvli zero, zero, e16, m8, tu, ma
; X280N-NEXT:    vlse16.v v24, (a7), zero
; X280N-NEXT:    vfnmsac.vf v8, fa2, v16
; X280N-NEXT:    vfnmsac.vf v8, fa1, v16
; X280N-NEXT:    vlse16.v v16, (a6), zero
; X280N-NEXT:    vfmacc.vf v16, fa0, v8
; X280N-NEXT:    vfmadd.vv v16, v8, v24
; X280N-NEXT:    vfmadd.vv v16, v8, v24
; X280N-NEXT:    vsetvli zero, zero, e8, m4, tu, ma
; X280N-NEXT:    vsra.vi v24, v4, 1
; X280N-NEXT:    vsub.vv v12, v4, v24
; X280N-NEXT:    vwadd.vx v8, v12, t0
; X280N-NEXT:    vsetvli zero, zero, e16, m8, tu, ma
; X280N-NEXT:    vsll.vi v8, v8, 10
; X280N-NEXT:    vfmul.vv v8, v16, v8
; X280N-NEXT:    vsetvli zero, zero, e8, m4, tu, ma
; X280N-NEXT:    vwadd.vx v16, v24, t0
; X280N-NEXT:    vsetvli zero, zero, e16, m8, tu, ma
; X280N-NEXT:    vsll.vi v16, v16, 10
; X280N-NEXT:    vfmul.vv v8, v8, v16
; X280N-NEXT:    vse16.v v8, (a4)
; X280N-NEXT:    bltu a3, a2, .LBB0_2
; X280N-NEXT:  .LBB0_3: # %for.cond.cleanup
; X280N-NEXT:    ret
entry:
  %cmp12.not = icmp eq i64 %n, 0
  br i1 %cmp12.not, label %for.cond.cleanup, label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.013 = phi i64 [ %add, %for.body ], [ 0, %entry ]
  %sub = sub i64 %n, %i.013
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %sub, i64 1, i64 3)
  %add.ptr = getelementptr inbounds half, ptr %x, i64 %i.013
  %1 = tail call contract <vscale x 32 x half> @llvm.riscv.vle.nxv32f16.i64(<vscale x 32 x half> poison, ptr %add.ptr, i64 %0)
  %2 = tail call <vscale x 32 x i1> @llvm.riscv.vmfeq.nxv32f16.nxv32f16.i64(<vscale x 32 x half> %1, <vscale x 32 x half> %1, i64 %0)
  %3 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmax.mask.nxv32f16.f16.i64(<vscale x 32 x half> %1, <vscale x 32 x half> %1, half 0xHCC56, <vscale x 32 x i1> %2, i64 %0, i64 1)
  %4 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmin.mask.nxv32f16.f16.i64(<vscale x 32 x half> %3, <vscale x 32 x half> %3, half 0xH498C, <vscale x 32 x i1> %2, i64 %0, i64 1)
  %5 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmul.nxv32f16.f16.i64(<vscale x 32 x half> poison, <vscale x 32 x half> %4, half 0xH3DC5, i64 7, i64 %0)
  %6 = tail call <vscale x 32 x i8> @llvm.riscv.vfncvt.x.f.w.nxv32i8.nxv32f16.i64(<vscale x 32 x i8> poison, <vscale x 32 x half> %5, i64 7, i64 %0)
  %7 = tail call contract <vscale x 32 x half> @llvm.riscv.vfwcvt.f.x.v.nxv32f16.nxv32i8.i64(<vscale x 32 x half> poison, <vscale x 32 x i8> %6, i64 %0)
  %8 = tail call contract <vscale x 32 x half> @llvm.riscv.vfnmsac.nxv32f16.f16.i64(<vscale x 32 x half> %4, half 0xH398C, <vscale x 32 x half> %7, i64 7, i64 %0, i64 3)
  %9 = tail call contract <vscale x 32 x half> @llvm.riscv.vfnmsub.nxv32f16.f16.i64(<vscale x 32 x half> %7, half 0xH8AF4, <vscale x 32 x half> %8, i64 7, i64 %0, i64 3)
  %10 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmv.v.f.nxv32f16.i64(<vscale x 32 x half> poison, half 0xH3809, i64 %0)
  %11 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmacc.nxv32f16.f16.i64(<vscale x 32 x half> %10, half 0xH315D, <vscale x 32 x half> %9, i64 7, i64 %0, i64 3)
  %12 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmv.v.f.nxv32f16.i64(<vscale x 32 x half> poison, half 0xH3C00, i64 %0)
  %13 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmadd.nxv32f16.nxv32f16.i64(<vscale x 32 x half> %11, <vscale x 32 x half> %9, <vscale x 32 x half> %12, i64 7, i64 %0, i64 3)
  %14 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmadd.nxv32f16.nxv32f16.i64(<vscale x 32 x half> %13, <vscale x 32 x half> %9, <vscale x 32 x half> %12, i64 7, i64 %0, i64 3)
  %15 = tail call <vscale x 32 x i8> @llvm.riscv.vsra.nxv32i8.i64.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> %6, i64 1, i64 %0)
  %16 = tail call <vscale x 32 x i8> @llvm.riscv.vsub.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> %6, <vscale x 32 x i8> %15, i64 %0)
  %17 = tail call <vscale x 32 x i16> @llvm.riscv.vwadd.nxv32i16.nxv32i8.i8.i64(<vscale x 32 x i16> poison, <vscale x 32 x i8> %16, i8 15, i64 %0)
  %18 = tail call <vscale x 32 x i16> @llvm.riscv.vsll.nxv32i16.i64.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> %17, i64 10, i64 %0)
  %19 = bitcast <vscale x 32 x i16> %18 to <vscale x 32 x half>
  %20 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmul.nxv32f16.nxv32f16.i64(<vscale x 32 x half> poison, <vscale x 32 x half> %14, <vscale x 32 x half> %19, i64 7, i64 %0)
  %21 = tail call <vscale x 32 x i16> @llvm.riscv.vwadd.nxv32i16.nxv32i8.i8.i64(<vscale x 32 x i16> poison, <vscale x 32 x i8> %15, i8 15, i64 %0)
  %22 = tail call <vscale x 32 x i16> @llvm.riscv.vsll.nxv32i16.i64.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> %21, i64 10, i64 %0)
  %23 = bitcast <vscale x 32 x i16> %22 to <vscale x 32 x half>
  %24 = tail call contract <vscale x 32 x half> @llvm.riscv.vfmul.nxv32f16.nxv32f16.i64(<vscale x 32 x half> poison, <vscale x 32 x half> %20, <vscale x 32 x half> %23, i64 7, i64 %0)
  %add.ptr3 = getelementptr inbounds half, ptr %y, i64 %i.013
  tail call void @llvm.riscv.vse.nxv32f16.i64(<vscale x 32 x half> %24, ptr %add.ptr3, i64 %0)
  %add = add i64 %0, %i.013
  %cmp = icmp ult i64 %add, %n
  br i1 %cmp, label %for.body, label %for.cond.cleanup
}

define void @skl_exp_f32(ptr nocapture noundef %y, ptr nocapture noundef readonly %x, i64 noundef %n) {
; X280-LABEL: skl_exp_f32:
; X280:       # %bb.0: # %entry
; X280-NEXT:    beqz a2, .LBB1_3
; X280-NEXT:  # %bb.1: # %for.body.preheader
; X280-NEXT:    lui a4, %hi(.LCPI1_0)
; X280-NEXT:    lui a5, %hi(.LCPI1_2)
; X280-NEXT:    lui a6, %hi(.LCPI1_1)
; X280-NEXT:    lui a7, %hi(.LCPI1_3)
; X280-NEXT:    lui t0, %hi(.LCPI1_8)
; X280-NEXT:    lui t1, %hi(.LCPI1_9)
; X280-NEXT:    flw fa5, %lo(.LCPI1_0)(a4)
; X280-NEXT:    lui a4, %hi(.LCPI1_4)
; X280-NEXT:    flw fa3, %lo(.LCPI1_2)(a5)
; X280-NEXT:    lui a5, %hi(.LCPI1_6)
; X280-NEXT:    flw fa4, %lo(.LCPI1_1)(a6)
; X280-NEXT:    lui a6, %hi(.LCPI1_5)
; X280-NEXT:    flw fa2, %lo(.LCPI1_3)(a7)
; X280-NEXT:    lui a7, %hi(.LCPI1_7)
; X280-NEXT:    lui t2, %hi(.LCPI1_10)
; X280-NEXT:    li a3, 0
; X280-NEXT:    flw fa1, %lo(.LCPI1_4)(a4)
; X280-NEXT:    addi a6, a6, %lo(.LCPI1_5)
; X280-NEXT:    flw fa0, %lo(.LCPI1_6)(a5)
; X280-NEXT:    addi a7, a7, %lo(.LCPI1_7)
; X280-NEXT:    addi t0, t0, %lo(.LCPI1_8)
; X280-NEXT:    addi t1, t1, %lo(.LCPI1_9)
; X280-NEXT:    addi t2, t2, %lo(.LCPI1_10)
; X280-NEXT:    li t3, 127
; X280-NEXT:  .LBB1_2: # %for.body
; X280-NEXT:    # =>This Inner Loop Header: Depth=1
; X280-NEXT:    sh2add a5, a3, a1
; X280-NEXT:    sub a4, a2, a3
; X280-NEXT:    vsetvli a4, a4, e32, m4, tu, mu
; X280-NEXT:    vle32.v v8, (a5)
; X280-NEXT:    sh2add a5, a3, a0
; X280-NEXT:    add a3, a3, a4
; X280-NEXT:    vmfeq.vv v0, v8, v8
; X280-NEXT:    vfmax.vf v8, v8, fa5, v0.t
; X280-NEXT:    vfmin.vf v8, v8, fa4, v0.t
; X280-NEXT:    vfmul.vf v12, v8, fa3
; X280-NEXT:    vsetvli zero, zero, e16, m2, tu, ma
; X280-NEXT:    vfncvt.x.f.w v20, v12
; X280-NEXT:    vfwcvt.f.x.v v12, v20
; X280-NEXT:    vsetvli zero, zero, e32, m4, tu, ma
; X280-NEXT:    vlse32.v v16, (a7), zero
; X280-NEXT:    vfnmsac.vf v8, fa2, v12
; X280-NEXT:    vfnmsac.vf v8, fa1, v12
; X280-NEXT:    vlse32.v v12, (a6), zero
; X280-NEXT:    vfmacc.vf v12, fa0, v8
; X280-NEXT:    vfmacc.vv v16, v8, v12
; X280-NEXT:    vlse32.v v12, (t0), zero
; X280-NEXT:    vfmacc.vv v12, v8, v16
; X280-NEXT:    vlse32.v v16, (t1), zero
; X280-NEXT:    vfmacc.vv v16, v8, v12
; X280-NEXT:    vlse32.v v12, (t2), zero
; X280-NEXT:    vfmadd.vv v16, v8, v12
; X280-NEXT:    vfmadd.vv v16, v8, v12
; X280-NEXT:    vsetvli zero, zero, e16, m2, tu, ma
; X280-NEXT:    vsra.vi v14, v20, 1
; X280-NEXT:    vsub.vv v10, v20, v14
; X280-NEXT:    vwadd.vx v8, v10, t3
; X280-NEXT:    vwadd.vx v12, v14, t3
; X280-NEXT:    vsetvli zero, zero, e32, m4, tu, ma
; X280-NEXT:    vsll.vi v8, v8, 23
; X280-NEXT:    vsll.vi v12, v12, 23
; X280-NEXT:    vfmul.vv v8, v16, v8
; X280-NEXT:    vfmul.vv v8, v8, v12
; X280-NEXT:    vse32.v v8, (a5)
; X280-NEXT:    bltu a3, a2, .LBB1_2
; X280-NEXT:  .LBB1_3: # %for.cond.cleanup
; X280-NEXT:    ret
;
; X280N-LABEL: skl_exp_f32:
; X280N:       # %bb.0: # %entry
; X280N-NEXT:    beqz a2, .LBB1_3
; X280N-NEXT:  # %bb.1: # %for.body.preheader
; X280N-NEXT:    lui a4, %hi(.LCPI1_0)
; X280N-NEXT:    lui a5, %hi(.LCPI1_2)
; X280N-NEXT:    lui a6, %hi(.LCPI1_1)
; X280N-NEXT:    lui a7, %hi(.LCPI1_3)
; X280N-NEXT:    lui t0, %hi(.LCPI1_8)
; X280N-NEXT:    lui t1, %hi(.LCPI1_9)
; X280N-NEXT:    flw fa5, %lo(.LCPI1_0)(a4)
; X280N-NEXT:    lui a4, %hi(.LCPI1_4)
; X280N-NEXT:    flw fa3, %lo(.LCPI1_2)(a5)
; X280N-NEXT:    lui a5, %hi(.LCPI1_6)
; X280N-NEXT:    flw fa4, %lo(.LCPI1_1)(a6)
; X280N-NEXT:    lui a6, %hi(.LCPI1_5)
; X280N-NEXT:    flw fa2, %lo(.LCPI1_3)(a7)
; X280N-NEXT:    lui a7, %hi(.LCPI1_7)
; X280N-NEXT:    lui t2, %hi(.LCPI1_10)
; X280N-NEXT:    li a3, 0
; X280N-NEXT:    flw fa1, %lo(.LCPI1_4)(a4)
; X280N-NEXT:    addi a6, a6, %lo(.LCPI1_5)
; X280N-NEXT:    flw fa0, %lo(.LCPI1_6)(a5)
; X280N-NEXT:    addi a7, a7, %lo(.LCPI1_7)
; X280N-NEXT:    addi t0, t0, %lo(.LCPI1_8)
; X280N-NEXT:    addi t1, t1, %lo(.LCPI1_9)
; X280N-NEXT:    addi t2, t2, %lo(.LCPI1_10)
; X280N-NEXT:    li t3, 127
; X280N-NEXT:  .LBB1_2: # %for.body
; X280N-NEXT:    # =>This Inner Loop Header: Depth=1
; X280N-NEXT:    sh2add a5, a3, a1
; X280N-NEXT:    sub a4, a2, a3
; X280N-NEXT:    vsetvli a4, a4, e32, m4, tu, mu
; X280N-NEXT:    vle32.v v8, (a5)
; X280N-NEXT:    sh2add a5, a3, a0
; X280N-NEXT:    add a3, a3, a4
; X280N-NEXT:    vmfeq.vv v0, v8, v8
; X280N-NEXT:    vfmax.vf v8, v8, fa5, v0.t
; X280N-NEXT:    vfmin.vf v8, v8, fa4, v0.t
; X280N-NEXT:    vfmul.vf v12, v8, fa3
; X280N-NEXT:    vsetvli zero, zero, e16, m2, tu, ma
; X280N-NEXT:    vfncvt.x.f.w v20, v12
; X280N-NEXT:    vfwcvt.f.x.v v12, v20
; X280N-NEXT:    vsetvli zero, zero, e32, m4, tu, ma
; X280N-NEXT:    vlse32.v v16, (a7), zero
; X280N-NEXT:    vfnmsac.vf v8, fa2, v12
; X280N-NEXT:    vfnmsac.vf v8, fa1, v12
; X280N-NEXT:    vlse32.v v12, (a6), zero
; X280N-NEXT:    vfmacc.vf v12, fa0, v8
; X280N-NEXT:    vfmacc.vv v16, v8, v12
; X280N-NEXT:    vlse32.v v12, (t0), zero
; X280N-NEXT:    vfmacc.vv v12, v8, v16
; X280N-NEXT:    vlse32.v v16, (t1), zero
; X280N-NEXT:    vfmacc.vv v16, v8, v12
; X280N-NEXT:    vlse32.v v12, (t2), zero
; X280N-NEXT:    vfmadd.vv v16, v8, v12
; X280N-NEXT:    vfmadd.vv v16, v8, v12
; X280N-NEXT:    vsetvli zero, zero, e16, m2, tu, ma
; X280N-NEXT:    vsra.vi v14, v20, 1
; X280N-NEXT:    vsub.vv v10, v20, v14
; X280N-NEXT:    vwadd.vx v8, v10, t3
; X280N-NEXT:    vwadd.vx v12, v14, t3
; X280N-NEXT:    vsetvli zero, zero, e32, m4, tu, ma
; X280N-NEXT:    vsll.vi v8, v8, 23
; X280N-NEXT:    vsll.vi v12, v12, 23
; X280N-NEXT:    vfmul.vv v8, v16, v8
; X280N-NEXT:    vfmul.vv v8, v8, v12
; X280N-NEXT:    vse32.v v8, (a5)
; X280N-NEXT:    bltu a3, a2, .LBB1_2
; X280N-NEXT:  .LBB1_3: # %for.cond.cleanup
; X280N-NEXT:    ret
entry:
  %cmp12.not = icmp eq i64 %n, 0
  br i1 %cmp12.not, label %for.cond.cleanup, label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.013 = phi i64 [ %add, %for.body ], [ 0, %entry ]
  %sub = sub i64 %n, %i.013
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %sub, i64 2, i64 2)
  %add.ptr = getelementptr inbounds float, ptr %x, i64 %i.013
  %1 = tail call contract <vscale x 8 x float> @llvm.riscv.vle.nxv8f32.i64(<vscale x 8 x float> poison, ptr %add.ptr, i64 %0)
  %2 = tail call <vscale x 8 x i1> @llvm.riscv.vmfeq.nxv8f32.nxv8f32.i64(<vscale x 8 x float> %1, <vscale x 8 x float> %1, i64 %0)
  %3 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmax.mask.nxv8f32.f32.i64(<vscale x 8 x float> %1, <vscale x 8 x float> %1, float 0xC059FE36A0000000, <vscale x 8 x i1> %2, i64 %0, i64 1)
  %4 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmin.mask.nxv8f32.f32.i64(<vscale x 8 x float> %3, <vscale x 8 x float> %3, float 0x40562E4300000000, <vscale x 8 x i1> %2, i64 %0, i64 1)
  %5 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmul.nxv8f32.f32.i64(<vscale x 8 x float> poison, <vscale x 8 x float> %4, float 0x3FF7154760000000, i64 7, i64 %0)
  %6 = tail call <vscale x 8 x i16> @llvm.riscv.vfncvt.x.f.w.nxv8i16.nxv8f32.i64(<vscale x 8 x i16> poison, <vscale x 8 x float> %5, i64 7, i64 %0)
  %7 = tail call contract <vscale x 8 x float> @llvm.riscv.vfwcvt.f.x.v.nxv8f32.nxv8i16.i64(<vscale x 8 x float> poison, <vscale x 8 x i16> %6, i64 %0)
  %8 = tail call contract <vscale x 8 x float> @llvm.riscv.vfnmsac.nxv8f32.f32.i64(<vscale x 8 x float> %4, float 0x3FE62E4000000000, <vscale x 8 x float> %7, i64 7, i64 %0, i64 3)
  %9 = tail call contract <vscale x 8 x float> @llvm.riscv.vfnmsac.nxv8f32.f32.i64(<vscale x 8 x float> %8, float 0x3EB7F7D1C0000000, <vscale x 8 x float> %7, i64 7, i64 %0, i64 3)
  %10 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmv.v.f.nxv8f32.i64(<vscale x 8 x float> poison, float 0x3F8123BCC0000000, i64 %0)
  %11 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmacc.nxv8f32.f32.i64(<vscale x 8 x float> %10, float 0x3F56850E40000000, <vscale x 8 x float> %9, i64 7, i64 %0, i64 3)
  %12 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmv.v.f.nxv8f32.i64(<vscale x 8 x float> poison, float 0x3FA555B980000000, i64 %0)
  %13 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmadd.nxv8f32.nxv8f32.i64(<vscale x 8 x float> %11, <vscale x 8 x float> %9, <vscale x 8 x float> %12, i64 7, i64 %0, i64 3)
  %14 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmv.v.f.nxv8f32.i64(<vscale x 8 x float> poison, float 0x3FC55548E0000000, i64 %0)
  %15 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmadd.nxv8f32.nxv8f32.i64(<vscale x 8 x float> %13, <vscale x 8 x float> %9, <vscale x 8 x float> %14, i64 7, i64 %0, i64 3)
  %16 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmv.v.f.nxv8f32.i64(<vscale x 8 x float> poison, float 0x3FDFFFFF80000000, i64 %0)
  %17 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmadd.nxv8f32.nxv8f32.i64(<vscale x 8 x float> %15, <vscale x 8 x float> %9, <vscale x 8 x float> %16, i64 7, i64 %0, i64 3)
  %18 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmv.v.f.nxv8f32.i64(<vscale x 8 x float> poison, float 1.000000e+00, i64 %0)
  %19 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmadd.nxv8f32.nxv8f32.i64(<vscale x 8 x float> %17, <vscale x 8 x float> %9, <vscale x 8 x float> %18, i64 7, i64 %0, i64 3)
  %20 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmadd.nxv8f32.nxv8f32.i64(<vscale x 8 x float> %19, <vscale x 8 x float> %9, <vscale x 8 x float> %18, i64 7, i64 %0, i64 3)
  %21 = tail call <vscale x 8 x i16> @llvm.riscv.vsra.nxv8i16.i64.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> %6, i64 1, i64 %0)
  %22 = tail call <vscale x 8 x i16> @llvm.riscv.vsub.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> %6, <vscale x 8 x i16> %21, i64 %0)
  %23 = tail call <vscale x 8 x i32> @llvm.riscv.vwadd.nxv8i32.nxv8i16.i16.i64(<vscale x 8 x i32> poison, <vscale x 8 x i16> %22, i16 127, i64 %0)
  %24 = tail call <vscale x 8 x i32> @llvm.riscv.vwadd.nxv8i32.nxv8i16.i16.i64(<vscale x 8 x i32> poison, <vscale x 8 x i16> %21, i16 127, i64 %0)
  %25 = tail call <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.i64.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> %23, i64 23, i64 %0)
  %26 = tail call <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.i64.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> %24, i64 23, i64 %0)
  %27 = bitcast <vscale x 8 x i32> %25 to <vscale x 8 x float>
  %28 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmul.nxv8f32.nxv8f32.i64(<vscale x 8 x float> poison, <vscale x 8 x float> %20, <vscale x 8 x float> %27, i64 7, i64 %0)
  %29 = bitcast <vscale x 8 x i32> %26 to <vscale x 8 x float>
  %30 = tail call contract <vscale x 8 x float> @llvm.riscv.vfmul.nxv8f32.nxv8f32.i64(<vscale x 8 x float> poison, <vscale x 8 x float> %28, <vscale x 8 x float> %29, i64 7, i64 %0)
  %add.ptr3 = getelementptr inbounds float, ptr %y, i64 %i.013
  tail call void @llvm.riscv.vse.nxv8f32.i64(<vscale x 8 x float> %30, ptr %add.ptr3, i64 %0)
  %add = add i64 %0, %i.013
  %cmp = icmp ult i64 %add, %n
  br i1 %cmp, label %for.body, label %for.cond.cleanup
}

define void @skl_exp_f64(ptr nocapture noundef %y, ptr nocapture noundef readonly %x, i64 noundef %n) {
; X280-LABEL: skl_exp_f64:
; X280:       # %bb.0: # %entry
; X280-NEXT:    beqz a2, .LBB2_4
; X280-NEXT:  # %bb.1: # %for.body.preheader
; X280-NEXT:    addi sp, sp, -32
; X280-NEXT:    .cfi_def_cfa_offset 32
; X280-NEXT:    sd s0, 24(sp) # 8-byte Folded Spill
; X280-NEXT:    sd s1, 16(sp) # 8-byte Folded Spill
; X280-NEXT:    sd s2, 8(sp) # 8-byte Folded Spill
; X280-NEXT:    sd s3, 0(sp) # 8-byte Folded Spill
; X280-NEXT:    .cfi_offset s0, -8
; X280-NEXT:    .cfi_offset s1, -16
; X280-NEXT:    .cfi_offset s2, -24
; X280-NEXT:    .cfi_offset s3, -32
; X280-NEXT:    lui a4, %hi(.LCPI2_0)
; X280-NEXT:    lui a5, %hi(.LCPI2_1)
; X280-NEXT:    lui s1, %hi(.LCPI2_2)
; X280-NEXT:    lui s0, %hi(.LCPI2_3)
; X280-NEXT:    lui a6, %hi(.LCPI2_5)
; X280-NEXT:    lui a7, %hi(.LCPI2_6)
; X280-NEXT:    fld fa5, %lo(.LCPI2_0)(a4)
; X280-NEXT:    lui a4, %hi(.LCPI2_4)
; X280-NEXT:    lui t0, %hi(.LCPI2_7)
; X280-NEXT:    lui t1, %hi(.LCPI2_8)
; X280-NEXT:    lui t2, %hi(.LCPI2_9)
; X280-NEXT:    lui t3, %hi(.LCPI2_10)
; X280-NEXT:    lui t4, %hi(.LCPI2_11)
; X280-NEXT:    lui t5, %hi(.LCPI2_12)
; X280-NEXT:    lui t6, %hi(.LCPI2_13)
; X280-NEXT:    lui s2, %hi(.LCPI2_14)
; X280-NEXT:    lui s3, %hi(.LCPI2_15)
; X280-NEXT:    li a3, 0
; X280-NEXT:    fld fa4, %lo(.LCPI2_1)(a5)
; X280-NEXT:    addi a6, a6, %lo(.LCPI2_5)
; X280-NEXT:    fld fa3, %lo(.LCPI2_2)(s1)
; X280-NEXT:    addi a7, a7, %lo(.LCPI2_6)
; X280-NEXT:    fld fa2, %lo(.LCPI2_3)(s0)
; X280-NEXT:    addi t0, t0, %lo(.LCPI2_7)
; X280-NEXT:    fld fa1, %lo(.LCPI2_4)(a4)
; X280-NEXT:    addi t1, t1, %lo(.LCPI2_8)
; X280-NEXT:    addi t2, t2, %lo(.LCPI2_9)
; X280-NEXT:    addi t3, t3, %lo(.LCPI2_10)
; X280-NEXT:    addi t4, t4, %lo(.LCPI2_11)
; X280-NEXT:    addi t5, t5, %lo(.LCPI2_12)
; X280-NEXT:    addi t6, t6, %lo(.LCPI2_13)
; X280-NEXT:    addi s2, s2, %lo(.LCPI2_14)
; X280-NEXT:    addi s3, s3, %lo(.LCPI2_15)
; X280-NEXT:    li s0, 1023
; X280-NEXT:    li s1, 52
; X280-NEXT:  .LBB2_2: # %for.body
; X280-NEXT:    # =>This Inner Loop Header: Depth=1
; X280-NEXT:    sh3add a4, a3, a1
; X280-NEXT:    sub a5, a2, a3
; X280-NEXT:    vsetvli a5, a5, e64, m4, tu, mu
; X280-NEXT:    vle64.v v8, (a4)
; X280-NEXT:    sh3add a4, a3, a0
; X280-NEXT:    add a3, a3, a5
; X280-NEXT:    vmfeq.vv v0, v8, v8
; X280-NEXT:    vfmax.vf v8, v8, fa5, v0.t
; X280-NEXT:    vfmin.vf v8, v8, fa4, v0.t
; X280-NEXT:    vfmul.vf v12, v8, fa3
; X280-NEXT:    vsetvli zero, zero, e32, m2, tu, ma
; X280-NEXT:    vfncvt.x.f.w v12, v12
; X280-NEXT:    vfwcvt.f.x.v v16, v12
; X280-NEXT:    vsetvli zero, zero, e64, m4, tu, ma
; X280-NEXT:    vlse64.v v20, (a6), zero
; X280-NEXT:    vfnmsac.vf v8, fa2, v16
; X280-NEXT:    vfnmsac.vf v8, fa1, v16
; X280-NEXT:    vlse64.v v16, (a7), zero
; X280-NEXT:    vfmacc.vv v16, v8, v20
; X280-NEXT:    vlse64.v v20, (t0), zero
; X280-NEXT:    vfmacc.vv v20, v8, v16
; X280-NEXT:    vlse64.v v16, (t1), zero
; X280-NEXT:    vfmacc.vv v16, v8, v20
; X280-NEXT:    vlse64.v v20, (t2), zero
; X280-NEXT:    vfmacc.vv v20, v8, v16
; X280-NEXT:    vlse64.v v16, (t3), zero
; X280-NEXT:    vfmacc.vv v16, v8, v20
; X280-NEXT:    vlse64.v v20, (t4), zero
; X280-NEXT:    vfmacc.vv v20, v8, v16
; X280-NEXT:    vlse64.v v16, (t5), zero
; X280-NEXT:    vfmacc.vv v16, v8, v20
; X280-NEXT:    vlse64.v v20, (t6), zero
; X280-NEXT:    vfmacc.vv v20, v8, v16
; X280-NEXT:    vlse64.v v16, (s2), zero
; X280-NEXT:    vfmacc.vv v16, v8, v20
; X280-NEXT:    vlse64.v v20, (s3), zero
; X280-NEXT:    vfmadd.vv v16, v8, v20
; X280-NEXT:    vfmadd.vv v16, v8, v20
; X280-NEXT:    vsetvli zero, zero, e32, m2, tu, ma
; X280-NEXT:    vsra.vi v14, v12, 1
; X280-NEXT:    vsub.vv v10, v12, v14
; X280-NEXT:    vwadd.vx v8, v10, s0
; X280-NEXT:    vsetvli zero, zero, e64, m4, tu, ma
; X280-NEXT:    vsll.vx v8, v8, s1
; X280-NEXT:    vfmul.vv v8, v16, v8
; X280-NEXT:    vsetvli zero, zero, e32, m2, tu, ma
; X280-NEXT:    vwadd.vx v12, v14, s0
; X280-NEXT:    vsetvli zero, zero, e64, m4, tu, ma
; X280-NEXT:    vsll.vx v12, v12, s1
; X280-NEXT:    vfmul.vv v8, v8, v12
; X280-NEXT:    vse64.v v8, (a4)
; X280-NEXT:    bltu a3, a2, .LBB2_2
; X280-NEXT:  # %bb.3:
; X280-NEXT:    ld s0, 24(sp) # 8-byte Folded Reload
; X280-NEXT:    ld s1, 16(sp) # 8-byte Folded Reload
; X280-NEXT:    ld s2, 8(sp) # 8-byte Folded Reload
; X280-NEXT:    ld s3, 0(sp) # 8-byte Folded Reload
; X280-NEXT:    .cfi_restore s0
; X280-NEXT:    .cfi_restore s1
; X280-NEXT:    .cfi_restore s2
; X280-NEXT:    .cfi_restore s3
; X280-NEXT:    addi sp, sp, 32
; X280-NEXT:    .cfi_def_cfa_offset 0
; X280-NEXT:  .LBB2_4: # %for.cond.cleanup
; X280-NEXT:    ret
;
; X280N-LABEL: skl_exp_f64:
; X280N:       # %bb.0: # %entry
; X280N-NEXT:    beqz a2, .LBB2_4
; X280N-NEXT:  # %bb.1: # %for.body.preheader
; X280N-NEXT:    addi sp, sp, -32
; X280N-NEXT:    .cfi_def_cfa_offset 32
; X280N-NEXT:    sd s0, 24(sp) # 8-byte Folded Spill
; X280N-NEXT:    sd s1, 16(sp) # 8-byte Folded Spill
; X280N-NEXT:    sd s2, 8(sp) # 8-byte Folded Spill
; X280N-NEXT:    sd s3, 0(sp) # 8-byte Folded Spill
; X280N-NEXT:    .cfi_offset s0, -8
; X280N-NEXT:    .cfi_offset s1, -16
; X280N-NEXT:    .cfi_offset s2, -24
; X280N-NEXT:    .cfi_offset s3, -32
; X280N-NEXT:    lui a4, %hi(.LCPI2_0)
; X280N-NEXT:    lui a5, %hi(.LCPI2_1)
; X280N-NEXT:    lui s1, %hi(.LCPI2_2)
; X280N-NEXT:    lui s0, %hi(.LCPI2_3)
; X280N-NEXT:    lui a6, %hi(.LCPI2_5)
; X280N-NEXT:    lui a7, %hi(.LCPI2_6)
; X280N-NEXT:    fld fa5, %lo(.LCPI2_0)(a4)
; X280N-NEXT:    lui a4, %hi(.LCPI2_4)
; X280N-NEXT:    lui t0, %hi(.LCPI2_7)
; X280N-NEXT:    lui t1, %hi(.LCPI2_8)
; X280N-NEXT:    lui t2, %hi(.LCPI2_9)
; X280N-NEXT:    lui t3, %hi(.LCPI2_10)
; X280N-NEXT:    lui t4, %hi(.LCPI2_11)
; X280N-NEXT:    lui t5, %hi(.LCPI2_12)
; X280N-NEXT:    lui t6, %hi(.LCPI2_13)
; X280N-NEXT:    lui s2, %hi(.LCPI2_14)
; X280N-NEXT:    lui s3, %hi(.LCPI2_15)
; X280N-NEXT:    li a3, 0
; X280N-NEXT:    fld fa4, %lo(.LCPI2_1)(a5)
; X280N-NEXT:    addi a6, a6, %lo(.LCPI2_5)
; X280N-NEXT:    fld fa3, %lo(.LCPI2_2)(s1)
; X280N-NEXT:    addi a7, a7, %lo(.LCPI2_6)
; X280N-NEXT:    fld fa2, %lo(.LCPI2_3)(s0)
; X280N-NEXT:    addi t0, t0, %lo(.LCPI2_7)
; X280N-NEXT:    fld fa1, %lo(.LCPI2_4)(a4)
; X280N-NEXT:    addi t1, t1, %lo(.LCPI2_8)
; X280N-NEXT:    addi t2, t2, %lo(.LCPI2_9)
; X280N-NEXT:    addi t3, t3, %lo(.LCPI2_10)
; X280N-NEXT:    addi t4, t4, %lo(.LCPI2_11)
; X280N-NEXT:    addi t5, t5, %lo(.LCPI2_12)
; X280N-NEXT:    addi t6, t6, %lo(.LCPI2_13)
; X280N-NEXT:    addi s2, s2, %lo(.LCPI2_14)
; X280N-NEXT:    addi s3, s3, %lo(.LCPI2_15)
; X280N-NEXT:    li s0, 1023
; X280N-NEXT:    li s1, 52
; X280N-NEXT:  .LBB2_2: # %for.body
; X280N-NEXT:    # =>This Inner Loop Header: Depth=1
; X280N-NEXT:    sh3add a4, a3, a1
; X280N-NEXT:    sub a5, a2, a3
; X280N-NEXT:    vsetvli a5, a5, e64, m4, tu, mu
; X280N-NEXT:    vle64.v v8, (a4)
; X280N-NEXT:    sh3add a4, a3, a0
; X280N-NEXT:    add a3, a3, a5
; X280N-NEXT:    vmfeq.vv v0, v8, v8
; X280N-NEXT:    vfmax.vf v8, v8, fa5, v0.t
; X280N-NEXT:    vfmin.vf v8, v8, fa4, v0.t
; X280N-NEXT:    vfmul.vf v12, v8, fa3
; X280N-NEXT:    vsetvli zero, zero, e32, m2, tu, ma
; X280N-NEXT:    vfncvt.x.f.w v12, v12
; X280N-NEXT:    vfwcvt.f.x.v v16, v12
; X280N-NEXT:    vsetvli zero, zero, e64, m4, tu, ma
; X280N-NEXT:    vlse64.v v20, (a6), zero
; X280N-NEXT:    vfnmsac.vf v8, fa2, v16
; X280N-NEXT:    vfnmsac.vf v8, fa1, v16
; X280N-NEXT:    vlse64.v v16, (a7), zero
; X280N-NEXT:    vfmacc.vv v16, v8, v20
; X280N-NEXT:    vlse64.v v20, (t0), zero
; X280N-NEXT:    vfmacc.vv v20, v8, v16
; X280N-NEXT:    vlse64.v v16, (t1), zero
; X280N-NEXT:    vfmacc.vv v16, v8, v20
; X280N-NEXT:    vlse64.v v20, (t2), zero
; X280N-NEXT:    vfmacc.vv v20, v8, v16
; X280N-NEXT:    vlse64.v v16, (t3), zero
; X280N-NEXT:    vfmacc.vv v16, v8, v20
; X280N-NEXT:    vlse64.v v20, (t4), zero
; X280N-NEXT:    vfmacc.vv v20, v8, v16
; X280N-NEXT:    vlse64.v v16, (t5), zero
; X280N-NEXT:    vfmacc.vv v16, v8, v20
; X280N-NEXT:    vlse64.v v20, (t6), zero
; X280N-NEXT:    vfmacc.vv v20, v8, v16
; X280N-NEXT:    vlse64.v v16, (s2), zero
; X280N-NEXT:    vfmacc.vv v16, v8, v20
; X280N-NEXT:    vlse64.v v20, (s3), zero
; X280N-NEXT:    vfmadd.vv v16, v8, v20
; X280N-NEXT:    vfmadd.vv v16, v8, v20
; X280N-NEXT:    vsetvli zero, zero, e32, m2, tu, ma
; X280N-NEXT:    vsra.vi v14, v12, 1
; X280N-NEXT:    vsub.vv v10, v12, v14
; X280N-NEXT:    vwadd.vx v8, v10, s0
; X280N-NEXT:    vsetvli zero, zero, e64, m4, tu, ma
; X280N-NEXT:    vsll.vx v8, v8, s1
; X280N-NEXT:    vfmul.vv v8, v16, v8
; X280N-NEXT:    vsetvli zero, zero, e32, m2, tu, ma
; X280N-NEXT:    vwadd.vx v12, v14, s0
; X280N-NEXT:    vsetvli zero, zero, e64, m4, tu, ma
; X280N-NEXT:    vsll.vx v12, v12, s1
; X280N-NEXT:    vfmul.vv v8, v8, v12
; X280N-NEXT:    vse64.v v8, (a4)
; X280N-NEXT:    bltu a3, a2, .LBB2_2
; X280N-NEXT:  # %bb.3:
; X280N-NEXT:    ld s0, 24(sp) # 8-byte Folded Reload
; X280N-NEXT:    ld s1, 16(sp) # 8-byte Folded Reload
; X280N-NEXT:    ld s2, 8(sp) # 8-byte Folded Reload
; X280N-NEXT:    ld s3, 0(sp) # 8-byte Folded Reload
; X280N-NEXT:    .cfi_restore s0
; X280N-NEXT:    .cfi_restore s1
; X280N-NEXT:    .cfi_restore s2
; X280N-NEXT:    .cfi_restore s3
; X280N-NEXT:    addi sp, sp, 32
; X280N-NEXT:    .cfi_def_cfa_offset 0
; X280N-NEXT:  .LBB2_4: # %for.cond.cleanup
; X280N-NEXT:    ret
entry:
  %cmp12.not = icmp eq i64 %n, 0
  br i1 %cmp12.not, label %for.cond.cleanup, label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.013 = phi i64 [ %add, %for.body ], [ 0, %entry ]
  %sub = sub i64 %n, %i.013
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %sub, i64 3, i64 2)
  %add.ptr = getelementptr inbounds double, ptr %x, i64 %i.013
  %1 = tail call contract <vscale x 4 x double> @llvm.riscv.vle.nxv4f64.i64(<vscale x 4 x double> poison, ptr %add.ptr, i64 %0)
  %2 = tail call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %1, <vscale x 4 x double> %1, i64 %0)
  %3 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmax.mask.nxv4f64.f64.i64(<vscale x 4 x double> %1, <vscale x 4 x double> %1, double 0xC0874910D52D3052, <vscale x 4 x i1> %2, i64 %0, i64 1)
  %4 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmin.mask.nxv4f64.f64.i64(<vscale x 4 x double> %3, <vscale x 4 x double> %3, double 0x40862E42FEFA39F0, <vscale x 4 x i1> %2, i64 %0, i64 1)
  %5 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmul.nxv4f64.f64.i64(<vscale x 4 x double> poison, <vscale x 4 x double> %4, double 0x3FF71547652B82FE, i64 7, i64 %0)
  %6 = tail call <vscale x 4 x i32> @llvm.riscv.vfncvt.x.f.w.nxv4i32.nxv4f64.i64(<vscale x 4 x i32> poison, <vscale x 4 x double> %5, i64 7, i64 %0)
  %7 = tail call contract <vscale x 4 x double> @llvm.riscv.vfwcvt.f.x.v.nxv4f64.nxv4i32.i64(<vscale x 4 x double> poison, <vscale x 4 x i32> %6, i64 %0)
  %8 = tail call contract <vscale x 4 x double> @llvm.riscv.vfnmsac.nxv4f64.f64.i64(<vscale x 4 x double> %4, double 0x3FE62E42FEFA3000, <vscale x 4 x double> %7, i64 7, i64 %0, i64 3)
  %9 = tail call contract <vscale x 4 x double> @llvm.riscv.vfnmsac.nxv4f64.f64.i64(<vscale x 4 x double> %8, double 0x3D53DE6AF278ECE6, <vscale x 4 x double> %7, i64 7, i64 %0, i64 3)
  %10 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3E5ADE1569CE2BDF, i64 %0)
  %11 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3E928AF3FCA213EA, i64 %0)
  %12 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %10, <vscale x 4 x double> %9, <vscale x 4 x double> %11, i64 7, i64 %0, i64 3)
  %13 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3EC71DEE62401315, i64 %0)
  %14 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %12, <vscale x 4 x double> %9, <vscale x 4 x double> %13, i64 7, i64 %0, i64 3)
  %15 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3EFA01997C89EB71, i64 %0)
  %16 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %14, <vscale x 4 x double> %9, <vscale x 4 x double> %15, i64 7, i64 %0, i64 3)
  %17 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3F2A01A014761F65, i64 %0)
  %18 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %16, <vscale x 4 x double> %9, <vscale x 4 x double> %17, i64 7, i64 %0, i64 3)
  %19 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3F56C16C1852B7AF, i64 %0)
  %20 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %18, <vscale x 4 x double> %9, <vscale x 4 x double> %19, i64 7, i64 %0, i64 3)
  %21 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3F81111111122322, i64 %0)
  %22 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %20, <vscale x 4 x double> %9, <vscale x 4 x double> %21, i64 7, i64 %0, i64 3)
  %23 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3FA55555555502A1, i64 %0)
  %24 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %22, <vscale x 4 x double> %9, <vscale x 4 x double> %23, i64 7, i64 %0, i64 3)
  %25 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3FC5555555555511, i64 %0)
  %26 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %24, <vscale x 4 x double> %9, <vscale x 4 x double> %25, i64 7, i64 %0, i64 3)
  %27 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 0x3FE000000000000B, i64 %0)
  %28 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %26, <vscale x 4 x double> %9, <vscale x 4 x double> %27, i64 7, i64 %0, i64 3)
  %29 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double> poison, double 1.000000e+00, i64 %0)
  %30 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %28, <vscale x 4 x double> %9, <vscale x 4 x double> %29, i64 7, i64 %0, i64 3)
  %31 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double> %30, <vscale x 4 x double> %9, <vscale x 4 x double> %29, i64 7, i64 %0, i64 3)
  %32 = tail call <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.i64.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> %6, i64 1, i64 %0)
  %33 = tail call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> %6, <vscale x 4 x i32> %32, i64 %0)
  %34 = tail call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> poison, <vscale x 4 x i32> %33, i32 1023, i64 %0)
  %35 = tail call <vscale x 4 x i64> @llvm.riscv.vsll.nxv4i64.i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> %34, i64 52, i64 %0)
  %36 = bitcast <vscale x 4 x i64> %35 to <vscale x 4 x double>
  %37 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmul.nxv4f64.nxv4f64.i64(<vscale x 4 x double> poison, <vscale x 4 x double> %31, <vscale x 4 x double> %36, i64 7, i64 %0)
  %38 = tail call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> poison, <vscale x 4 x i32> %32, i32 1023, i64 %0)
  %39 = tail call <vscale x 4 x i64> @llvm.riscv.vsll.nxv4i64.i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> %38, i64 52, i64 %0)
  %40 = bitcast <vscale x 4 x i64> %39 to <vscale x 4 x double>
  %41 = tail call contract <vscale x 4 x double> @llvm.riscv.vfmul.nxv4f64.nxv4f64.i64(<vscale x 4 x double> poison, <vscale x 4 x double> %37, <vscale x 4 x double> %40, i64 7, i64 %0)
  %add.ptr3 = getelementptr inbounds double, ptr %y, i64 %i.013
  tail call void @llvm.riscv.vse.nxv4f64.i64(<vscale x 4 x double> %41, ptr %add.ptr3, i64 %0)
  %add = add i64 %0, %i.013
  %cmp = icmp ult i64 %add, %n
  br i1 %cmp, label %for.body, label %for.cond.cleanup
}

; Function Attrs: nofree nosync nounwind memory(none)
declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(read)
declare <vscale x 32 x half> @llvm.riscv.vle.nxv32f16.i64(<vscale x 32 x half>, ptr nocapture, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.vse.nxv32f16.i64(<vscale x 32 x half>, ptr nocapture, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(read)
declare <vscale x 8 x float> @llvm.riscv.vle.nxv8f32.i64(<vscale x 8 x float>, ptr nocapture, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.vse.nxv8f32.i64(<vscale x 8 x float>, ptr nocapture, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(read)
declare <vscale x 4 x double> @llvm.riscv.vle.nxv4f64.i64(<vscale x 4 x double>, ptr nocapture, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.vse.nxv4f64.i64(<vscale x 4 x double>, ptr nocapture, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x i1> @llvm.riscv.vmfeq.nxv32f16.nxv32f16.i64(<vscale x 32 x half>, <vscale x 32 x half>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmax.mask.nxv32f16.f16.i64(<vscale x 32 x half>, <vscale x 32 x half>, half, <vscale x 32 x i1>, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmin.mask.nxv32f16.f16.i64(<vscale x 32 x half>, <vscale x 32 x half>, half, <vscale x 32 x i1>, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmul.nxv32f16.f16.i64(<vscale x 32 x half>, <vscale x 32 x half>, half, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x i8> @llvm.riscv.vfncvt.x.f.w.nxv32i8.nxv32f16.i64(<vscale x 32 x i8>, <vscale x 32 x half>, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfwcvt.f.x.v.nxv32f16.nxv32i8.i64(<vscale x 32 x half>, <vscale x 32 x i8>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfnmsac.nxv32f16.f16.i64(<vscale x 32 x half>, half, <vscale x 32 x half>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfnmsub.nxv32f16.f16.i64(<vscale x 32 x half>, half, <vscale x 32 x half>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmv.v.f.nxv32f16.i64(<vscale x 32 x half>, half, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmacc.nxv32f16.f16.i64(<vscale x 32 x half>, half, <vscale x 32 x half>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmadd.nxv32f16.nxv32f16.i64(<vscale x 32 x half>, <vscale x 32 x half>, <vscale x 32 x half>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x i8> @llvm.riscv.vsra.nxv32i8.i64.i64(<vscale x 32 x i8>, <vscale x 32 x i8>, i64, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x i8> @llvm.riscv.vsub.nxv32i8.nxv32i8.i64(<vscale x 32 x i8>, <vscale x 32 x i8>, <vscale x 32 x i8>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x i16> @llvm.riscv.vwadd.nxv32i16.nxv32i8.i8.i64(<vscale x 32 x i16>, <vscale x 32 x i8>, i8, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x i16> @llvm.riscv.vsll.nxv32i16.i64.i64(<vscale x 32 x i16>, <vscale x 32 x i16>, i64, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 32 x half> @llvm.riscv.vfmul.nxv32f16.nxv32f16.i64(<vscale x 32 x half>, <vscale x 32 x half>, <vscale x 32 x half>, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i1> @llvm.riscv.vmfeq.nxv8f32.nxv8f32.i64(<vscale x 8 x float>, <vscale x 8 x float>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmax.mask.nxv8f32.f32.i64(<vscale x 8 x float>, <vscale x 8 x float>, float, <vscale x 8 x i1>, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmin.mask.nxv8f32.f32.i64(<vscale x 8 x float>, <vscale x 8 x float>, float, <vscale x 8 x i1>, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmul.nxv8f32.f32.i64(<vscale x 8 x float>, <vscale x 8 x float>, float, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i16> @llvm.riscv.vfncvt.x.f.w.nxv8i16.nxv8f32.i64(<vscale x 8 x i16>, <vscale x 8 x float>, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfwcvt.f.x.v.nxv8f32.nxv8i16.i64(<vscale x 8 x float>, <vscale x 8 x i16>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfnmsac.nxv8f32.f32.i64(<vscale x 8 x float>, float, <vscale x 8 x float>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmv.v.f.nxv8f32.i64(<vscale x 8 x float>, float, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmacc.nxv8f32.f32.i64(<vscale x 8 x float>, float, <vscale x 8 x float>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmadd.nxv8f32.nxv8f32.i64(<vscale x 8 x float>, <vscale x 8 x float>, <vscale x 8 x float>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i16> @llvm.riscv.vsra.nxv8i16.i64.i64(<vscale x 8 x i16>, <vscale x 8 x i16>, i64, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i16> @llvm.riscv.vsub.nxv8i16.nxv8i16.i64(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i32> @llvm.riscv.vwadd.nxv8i32.nxv8i16.i16.i64(<vscale x 8 x i32>, <vscale x 8 x i16>, i16, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.i64.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, i64, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 8 x float> @llvm.riscv.vfmul.nxv8f32.nxv8f32.i64(<vscale x 8 x float>, <vscale x 8 x float>, <vscale x 8 x float>, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f64.nxv4f64.i64(<vscale x 4 x double>, <vscale x 4 x double>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfmax.mask.nxv4f64.f64.i64(<vscale x 4 x double>, <vscale x 4 x double>, double, <vscale x 4 x i1>, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfmin.mask.nxv4f64.f64.i64(<vscale x 4 x double>, <vscale x 4 x double>, double, <vscale x 4 x i1>, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfmul.nxv4f64.f64.i64(<vscale x 4 x double>, <vscale x 4 x double>, double, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i32> @llvm.riscv.vfncvt.x.f.w.nxv4i32.nxv4f64.i64(<vscale x 4 x i32>, <vscale x 4 x double>, i64 immarg, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfwcvt.f.x.v.nxv4f64.nxv4i32.i64(<vscale x 4 x double>, <vscale x 4 x i32>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfnmsac.nxv4f64.f64.i64(<vscale x 4 x double>, double, <vscale x 4 x double>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfmv.v.f.nxv4f64.i64(<vscale x 4 x double>, double, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfmadd.nxv4f64.nxv4f64.i64(<vscale x 4 x double>, <vscale x 4 x double>, <vscale x 4 x double>, i64 immarg, i64, i64 immarg)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.i64.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x i64> @llvm.riscv.vsll.nxv4i64.i64.i64(<vscale x 4 x i64>, <vscale x 4 x i64>, i64, i64)

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 4 x double> @llvm.riscv.vfmul.nxv4f64.nxv4f64.i64(<vscale x 4 x double>, <vscale x 4 x double>, <vscale x 4 x double>, i64 immarg, i64)
