; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+lui-addi-fusion -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I
; RUN: llc -mtriple=riscv64 -mattr=+lui-addi-fusion -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I

; Various tests for lui+addi fusion.

; Make sure the lui and addi use the same destination register on rv32.
; Without fusion the lui uses a0.
define i64 @imm64_shifted() nounwind {
; RV32I-LABEL: imm64_shifted:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a1, 74565
; RV32I-NEXT:    addi a1, a1, 1656
; RV32I-NEXT:    li a0, 0
; RV32I-NEXT:    ret
;
; RV64I-LABEL: imm64_shifted:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a0, 9321
; RV64I-NEXT:    addi a0, a0, -1329
; RV64I-NEXT:    slli a0, a0, 35
; RV64I-NEXT:    ret
  ret i64 1311768464867721216 ; 0x1234_5678_0000_0000
}

; Make sure the lui and addi use the same destination register on rv64.
; Without fusion the lui uses a0.
define i128 @imm128_shifted() nounwind {
; RV32I-LABEL: imm128_shifted:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a1, 74565
; RV32I-NEXT:    addi a1, a1, 1656
; RV32I-NEXT:    sw zero, 0(a0)
; RV32I-NEXT:    sw zero, 4(a0)
; RV32I-NEXT:    sw a1, 8(a0)
; RV32I-NEXT:    sw zero, 12(a0)
; RV32I-NEXT:    ret
;
; RV64I-LABEL: imm128_shifted:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a1, 74565
; RV64I-NEXT:    addi a1, a1, 1656
; RV64I-NEXT:    li a0, 0
; RV64I-NEXT:    ret
  %a = shl i128 305419896, 64 ; 0x1234_5678
  ret i128 %a
}

; Make sure we still fold addi into load/store offsets instead of fusing.
define i32 @lw_sw_constant(i32 %a) nounwind {
; RV32I-LABEL: lw_sw_constant:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a2, 912092
; RV32I-NEXT:    lw a1, -273(a2)
; RV32I-NEXT:    sw a0, -273(a2)
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    ret
;
; RV64I-LABEL: lw_sw_constant:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a1, 228023
; RV64I-NEXT:    slli a2, a1, 2
; RV64I-NEXT:    lw a1, -273(a2)
; RV64I-NEXT:    sw a0, -273(a2)
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    ret
  %1 = inttoptr i32 3735928559 to i32*
  %2 = load volatile i32, i32* %1
  store i32 %a, i32* %1
  ret i32 %2
}

%struct.S = type { [40 x i32], i32, i32, i32, [4100 x i32], i32, i32, i32 }
@s = common dso_local global %struct.S zeroinitializer, align 4
@g = global [1048576 x i8] zeroinitializer, align 1

; Make sure fusion doesn't interfere with the RISCVMergeBaseOffset pass.
; This test checks that the offset is reconstructed correctly when
; "addi" of the big offset has a negative immediate.
; without peephole this generates:
; lui  a1, %hi(g)
; addi a1, a0, %lo(g)
; lui  a0, 18     ---> offset
; addi a0, a0, -160
; add  a0, a0, a1  ---> base + offset.
define i8* @big_offset_neg_addi() nounwind {
; RV32I-LABEL: big_offset_neg_addi:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a0, %hi(g+73568)
; RV32I-NEXT:    addi a0, a0, %lo(g+73568)
; RV32I-NEXT:    ret
;
; RV64I-LABEL: big_offset_neg_addi:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a0, %hi(g+73568)
; RV64I-NEXT:    addi a0, a0, %lo(g+73568)
; RV64I-NEXT:    ret
  ret i8* getelementptr inbounds ([1048576 x i8], [1048576 x i8]* @g, i32 0, i32 73568)
}

define i32* @big_offset_one_use() local_unnamed_addr nounwind {
; RV32I-LABEL: big_offset_one_use:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    lui a0, %hi(s+16572)
; RV32I-NEXT:    addi a0, a0, %lo(s+16572)
; RV32I-NEXT:    ret
;
; RV64I-LABEL: big_offset_one_use:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    lui a0, %hi(s+16572)
; RV64I-NEXT:    addi a0, a0, %lo(s+16572)
; RV64I-NEXT:    ret
entry:
  ret i32* getelementptr inbounds (%struct.S, %struct.S* @s, i32 0, i32 5)
}
