; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 \
; RUN:   | FileCheck %s --check-prefix=NOFUSION
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 -mattr=+fuse-lui-load \
; RUN:   | FileCheck %s --check-prefix=FUSELUI

@vari8 = external global i8, align 1
@vari16 = external global i16, align 2
@vari32 = external global i32, align 4
@vari64 = external global i64, align 4

; Test fusing lui with a subsequent load instruction.

define i32 @test_lb() {
; NOFUSION-LABEL: test_lb:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari8)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    lb a0, %lo(vari8)(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_lb:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari8)
; FUSELUI-NEXT:    lb a1, %lo(vari8)(a1)
; FUSELUI-NEXT:    add a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i8, i8* getelementptr inbounds (i8, i8* @vari8, i8 0), align 1
  %b = sext i8 %a to i32
  %c = add i32 %b, 8192
  ret i32 %c
}

define i32 @test_lbu() {
; NOFUSION-LABEL: test_lbu:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari8)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    lbu a0, %lo(vari8)(a0)
; NOFUSION-NEXT:    or a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_lbu:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari8)
; FUSELUI-NEXT:    lbu a1, %lo(vari8)(a1)
; FUSELUI-NEXT:    or a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i8, i8* getelementptr inbounds (i8, i8* @vari8, i8 0), align 1
  %b = zext i8 %a to i32
  %c = add i32 %b, 8192
  ret i32 %c
}

define i32 @test_lh() {
; NOFUSION-LABEL: test_lh:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari16)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    lh a0, %lo(vari16)(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_lh:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari16)
; FUSELUI-NEXT:    lh a1, %lo(vari16)(a1)
; FUSELUI-NEXT:    add a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i16, i16* getelementptr inbounds (i16, i16* @vari16, i16 0), align 2
  %b = sext i16 %a to i32
  %c = add i32 %b, 8192
  ret i32 %c
}

define i32 @test_lhu() {
; NOFUSION-LABEL: test_lhu:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari16)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    lhu a0, %lo(vari16)(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_lhu:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari16)
; FUSELUI-NEXT:    lhu a1, %lo(vari16)(a1)
; FUSELUI-NEXT:    add a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i16, i16* getelementptr inbounds (i16, i16* @vari16, i16 0), align 2
  %b = zext i16 %a to i32
  %c = add i32 %b, 8192
  ret i32 %c
}

define i64 @test_lw() {
; NOFUSION-LABEL: test_lw:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari32)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    lw a0, %lo(vari32)(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_lw:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari32)
; FUSELUI-NEXT:    lw a1, %lo(vari32)(a1)
; FUSELUI-NEXT:    add a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i32, i32* getelementptr inbounds (i32, i32* @vari32, i32 0), align 4
  %b = sext i32 %a to i64
  %c = add i64 %b, 8192
  ret i64 %c
}

define i64 @test_lwu() {
; NOFUSION-LABEL: test_lwu:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari32)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    lwu a0, %lo(vari32)(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_lwu:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari32)
; FUSELUI-NEXT:    lwu a1, %lo(vari32)(a1)
; FUSELUI-NEXT:    add a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i32, i32* getelementptr inbounds (i32, i32* @vari32, i32 0), align 4
  %b = zext i32 %a to i64
  %c = add i64 %b, 8192
  ret i64 %c
}

define i64 @test_ld() {
; NOFUSION-LABEL: test_ld:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    lui a0, %hi(vari64)
; NOFUSION-NEXT:    lui a1, 2
; NOFUSION-NEXT:    ld a0, %lo(vari64)(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSELUI-LABEL: test_ld:
; FUSELUI:       # %bb.0:
; FUSELUI-NEXT:    lui a0, 2
; FUSELUI-NEXT:    lui a1, %hi(vari64)
; FUSELUI-NEXT:    ld a1, %lo(vari64)(a1)
; FUSELUI-NEXT:    add a0, a0, a1
; FUSELUI-NEXT:    ret
  %a = load i64, i64* getelementptr inbounds (i64, i64* @vari64, i64 0), align 8
  %b = add i64 %a, 8192
  ret i64 %b
}
