# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
# RUN: llc  %s -o - -mtriple=riscv64 -mattr=+v -run-pass=register-coalescer \
# RUN:  -verify-machineinstrs | FileCheck %s

---
name:            main
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: main
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $x10, $v8, $v10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead [[DEF:%[0-9]+]]:gpr = IMPLICIT_DEF
  ; CHECK-NEXT:   undef [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_0:vrn6m1nov0 = PseudoVMV_V_I_M1 undef [[PseudoVMV_V_I_M1_]].sub_vrm1_0, 0, -1, 3 /* e8 */, 0 /* tu, mu */, implicit $vl, implicit $vtype
  ; CHECK-NEXT:   undef [[DEF1:%[0-9]+]].sub_vrm1_5:vrn6m1 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_3:vrn6m1nov0 = COPY [[DEF1]].sub_vrm1_5
  ; CHECK-NEXT:   [[PseudoVMV_V_I_M1_:%[0-9]+]].sub_vrm1_4:vrn6m1nov0 = COPY undef [[PseudoVMV_V_I_M1_]].sub_vrm1_0
  ; CHECK-NEXT:   BNE undef [[DEF]], $x0, %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   BNE undef [[DEF]], $x0, %bb.3
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   dead [[DEF2:%[0-9]+]]:vr = IMPLICIT_DEF
  ; CHECK-NEXT:   early-clobber [[DEF1]].sub_vrm1_0:vrn6m1 = PseudoVRGATHER_VI_M1 undef [[DEF1]].sub_vrm1_0, [[PseudoVMV_V_I_M1_]].sub_vrm1_0, 0, 0, 3 /* e8 */, 0 /* tu, mu */, implicit $vl, implicit $vtype
  ; CHECK-NEXT:   PseudoVSSEG6E8_V_M1_MASK [[DEF1]], undef [[DEF]], killed undef $v0, 0, 3 /* e8 */, implicit $vl, implicit $vtype :: (store unknown-size, align 1)
  ; CHECK-NEXT:   PseudoRET
  bb.0:
    successors: %bb.3(0x40000000), %bb.1(0x40000000)
    liveins: $x10, $v8, $v10
    %0:gpr = IMPLICIT_DEF
    %1:vrnov0 = PseudoVMV_V_I_M1 undef %1, 0, -1, 3 /* e8 */, 0 /* tu, mu */, implicit $vl, implicit $vtype
    %2:vrnov0 = IMPLICIT_DEF
    undef %3.sub_vrm1_0:vrn6m1nov0 = COPY undef %1
    %3.sub_vrm1_3:vrn6m1nov0 = COPY %2
    %3.sub_vrm1_4:vrn6m1nov0 = COPY undef %1
    BNE undef %0, $x0, %bb.3
    PseudoBR %bb.1
  bb.1:
    successors: %bb.3(0x40000000), %bb.2(0x40000000)
    BNE killed undef %0, $x0, %bb.3
    PseudoBR %bb.2
  bb.2:
    successors: %bb.3(0x80000000)
  bb.3:
    %4:vr = IMPLICIT_DEF
    early-clobber %4:vr = PseudoVRGATHER_VI_M1 undef %4, killed %1, 0, 0, 3 /* e8 */, 0 /* tu, mu */, implicit $vl, implicit $vtype
    undef %5.sub_vrm1_0:vrn6m1 = COPY killed %4
    %5.sub_vrm1_5:vrn6m1 = COPY killed %2
    PseudoVSSEG6E8_V_M1_MASK killed %5, undef %0, killed undef $v0, 0, 3 /* e8 */, implicit $vl, implicit $vtype :: (store unknown-size, align 1)
    PseudoRET
...
