; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=riscv64 -mcpu=sifive-x280 < %s | FileCheck %s

; This test is used to prevent regressions against a bug that made
; RISCVMaskInstDAGMutation non-determininstic.

%struct.ham = type { i8, i8, i16, i32, [32 x i8] }

define void @baz(ptr %arg) {
; CHECK-LABEL: baz:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vsetvli a1, zero, e64, m8, ta, ma
; CHECK-NEXT:    vid.v v8
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    li a7, -65
; CHECK-NEXT:    li a6, 32
; CHECK-NEXT:    li t0, 26
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    minu a4, a2, a6
; CHECK-NEXT:    slli a1, a2, 3
; CHECK-NEXT:    maxu a3, a2, a6
; CHECK-NEXT:    sub a3, a3, a2
; CHECK-NEXT:    srli a2, a2, 3
; CHECK-NEXT:    vsll.vi v8, v8, 3
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vadd.vx v16, v8, a7
; CHECK-NEXT:    vmsltu.vx v0, v16, t0
; CHECK-NEXT:    vsetvli a5, zero, e64, m8, ta, ma
; CHECK-NEXT:    vadd.vx v16, v8, a1
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    li a1, -64
; CHECK-NEXT:    vadd.vx v24, v16, a7
; CHECK-NEXT:    vmsltu.vx v7, v24, t0
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vadd.vx v24, v8, a1
; CHECK-NEXT:    vmsltu.vx v6, v24, t0
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vadd.vx v24, v16, a1
; CHECK-NEXT:    li a1, -63
; CHECK-NEXT:    vmsltu.vx v24, v24, t0
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vadd.vx v8, v8, a1
; CHECK-NEXT:    vmsltu.vx v25, v8, t0
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vadd.vx v8, v16, a1
; CHECK-NEXT:    vmsltu.vx v16, v8, t0
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v7, a2
; CHECK-NEXT:    vsetvli zero, a6, e8, m2, ta, ma
; CHECK-NEXT:    vmorn.mm v9, v0, v0
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v6, v24, a2
; CHECK-NEXT:    vsetvli zero, a6, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vmand.mm v8, v9, v6
; CHECK-NEXT:    vor.vi v10, v10, 1
; CHECK-NEXT:    vmorn.mm v12, v8, v6
; CHECK-NEXT:    vse8.v v10, (a0), v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmand.mm v12, v12, v9
; CHECK-NEXT:    vmandn.mm v9, v8, v9
; CHECK-NEXT:    vmor.mm v9, v12, v9
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v25, v16, a2
; CHECK-NEXT:    vsetvli zero, a6, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vmand.mm v9, v9, v25
; CHECK-NEXT:    vor.vi v10, v10, 2
; CHECK-NEXT:    vse8.v v10, (a0), v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vor.vi v10, v10, 4
; CHECK-NEXT:    vse8.v v10, (a0), v0.t
; CHECK-NEXT:    ret
bb:
  %call = call <vscale x 16 x i64> @llvm.experimental.stepvector.nxv16i64()
  %shl = shl <vscale x 16 x i64> %call, shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 3, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer)
  %call1 = call <vscale x 16 x i64> @llvm.vp.add.nxv16i64(<vscale x 16 x i64> %shl, <vscale x 16 x i64> shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 -65, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call2 = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %call1, <vscale x 16 x i64> shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 26, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer), metadata !"ult", <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call3 = call <vscale x 16 x i1> @llvm.vp.xor.nxv16i1(<vscale x 16 x i1> %call2, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %getelementptr = getelementptr %struct.ham, ptr %arg, i64 0, i32 4, i64 0
  %call4 = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr align 1 %getelementptr, <vscale x 16 x i1> %call2, i32 32)
  %call5 = call <vscale x 16 x i8> @llvm.vp.or.nxv16i8(<vscale x 16 x i8> %call4, <vscale x 16 x i8> shufflevector (<vscale x 16 x i8> insertelement (<vscale x 16 x i8> poison, i8 1, i64 0), <vscale x 16 x i8> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  call void @llvm.vp.store.nxv16i8.p0(<vscale x 16 x i8> %call5, ptr align 1 %getelementptr, <vscale x 16 x i1> %call2, i32 32)
  %call6 = call <vscale x 16 x i1> @llvm.vp.or.nxv16i1(<vscale x 16 x i1> %call2, <vscale x 16 x i1> %call3, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call7 = call <vscale x 16 x i64> @llvm.vp.add.nxv16i64(<vscale x 16 x i64> %shl, <vscale x 16 x i64> shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 -64, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call8 = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %call7, <vscale x 16 x i64> shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 26, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer), metadata !"ult", <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call9 = call <vscale x 16 x i1> @llvm.vp.select.nxv16i1(<vscale x 16 x i1> %call6, <vscale x 16 x i1> %call8, <vscale x 16 x i1> zeroinitializer, i32 32)
  %call10 = call <vscale x 16 x i1> @llvm.vp.xor.nxv16i1(<vscale x 16 x i1> %call8, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call11 = call <vscale x 16 x i1> @llvm.vp.select.nxv16i1(<vscale x 16 x i1> %call6, <vscale x 16 x i1> %call10, <vscale x 16 x i1> zeroinitializer, i32 32)
  %getelementptr12 = getelementptr %struct.ham, ptr %arg, i64 0, i32 4, i64 0
  %call13 = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr align 1 %getelementptr12, <vscale x 16 x i1> %call9, i32 32)
  %call14 = call <vscale x 16 x i8> @llvm.vp.or.nxv16i8(<vscale x 16 x i8> %call13, <vscale x 16 x i8> shufflevector (<vscale x 16 x i8> insertelement (<vscale x 16 x i8> poison, i8 2, i64 0), <vscale x 16 x i8> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  call void @llvm.vp.store.nxv16i8.p0(<vscale x 16 x i8> %call14, ptr align 1 %getelementptr12, <vscale x 16 x i1> %call9, i32 32)
  %call15 = call <vscale x 16 x i1> @llvm.vp.or.nxv16i1(<vscale x 16 x i1> %call9, <vscale x 16 x i1> %call11, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call16 = call <vscale x 16 x i64> @llvm.vp.add.nxv16i64(<vscale x 16 x i64> %shl, <vscale x 16 x i64> shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 -63, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call17 = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %call16, <vscale x 16 x i64> shufflevector (<vscale x 16 x i64> insertelement (<vscale x 16 x i64> poison, i64 26, i64 0), <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer), metadata !"ult", <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call18 = call <vscale x 16 x i1> @llvm.vp.select.nxv16i1(<vscale x 16 x i1> %call15, <vscale x 16 x i1> %call17, <vscale x 16 x i1> zeroinitializer, i32 32)
  %call19 = call <vscale x 16 x i1> @llvm.vp.xor.nxv16i1(<vscale x 16 x i1> %call17, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  %call20 = call <vscale x 16 x i1> @llvm.vp.select.nxv16i1(<vscale x 16 x i1> %call15, <vscale x 16 x i1> %call19, <vscale x 16 x i1> zeroinitializer, i32 32)
  %getelementptr21 = getelementptr %struct.ham, ptr %arg, i64 0, i32 4, i64 0
  %call22 = call <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr align 1 %getelementptr21, <vscale x 16 x i1> %call18, i32 32)
  %call23 = call <vscale x 16 x i8> @llvm.vp.or.nxv16i8(<vscale x 16 x i8> %call22, <vscale x 16 x i8> shufflevector (<vscale x 16 x i8> insertelement (<vscale x 16 x i8> poison, i8 4, i64 0), <vscale x 16 x i8> poison, <vscale x 16 x i32> zeroinitializer), <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 32)
  call void @llvm.vp.store.nxv16i8.p0(<vscale x 16 x i8> %call23, ptr align 1 %getelementptr21, <vscale x 16 x i1> %call18, i32 32)
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i1> @llvm.vp.select.nxv16i1(<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i64> @llvm.experimental.stepvector.nxv16i64() #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i64> @llvm.vp.add.nxv16i64(<vscale x 16 x i64>, <vscale x 16 x i64>, <vscale x 16 x i1>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i1> @llvm.vp.xor.nxv16i1(<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: write)
declare void @llvm.vp.store.nxv16i8.p0(<vscale x 16 x i8>, ptr nocapture, <vscale x 16 x i1>, i32) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i1> @llvm.vp.or.nxv16i1(<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64>, <vscale x 16 x i64>, metadata, <vscale x 16 x i1>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(none)
declare <vscale x 16 x i8> @llvm.vp.or.nxv16i8(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i1>, i32) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: read)
declare <vscale x 16 x i8> @llvm.vp.load.nxv16i8.p0(ptr nocapture, <vscale x 16 x i1>, i32) #2

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: write) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(argmem: read) }

