; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=riscv64 < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr='+zbs' < %s | FileCheck %s --check-prefix=ZBS

define i64 @shift1(i64 %__n) {
; CHECK-LABEL: shift1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    srli a0, a0, 1
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    ret
;
; ZBS-LABEL: shift1:
; ZBS:       # %bb.0: # %entry
; ZBS-NEXT:    srli a0, a0, 1
; ZBS-NEXT:    bseti a0, a0, 63
; ZBS-NEXT:    ret
entry:
  %div81 = lshr i64 %__n, 1
  %sub10 = or disjoint i64 %div81, -9223372036854775808
  ret i64 %sub10
}

define i64 @shift2(i64 %__n) {
; CHECK-LABEL: shift2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    srli a0, a0, 2
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    ret
;
; ZBS-LABEL: shift2:
; ZBS:       # %bb.0: # %entry
; ZBS-NEXT:    not a0, a0
; ZBS-NEXT:    srli a0, a0, 2
; ZBS-NEXT:    not a0, a0
; ZBS-NEXT:    ret
entry:
  %div81 = lshr i64 %__n, 2
  %sub10 = or disjoint i64 %div81, -4611686018427387904
  ret i64 %sub10
}

define i64 @shift4(i64 %__n) {
; CHECK-LABEL: shift4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    srli a0, a0, 4
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    ret
;
; ZBS-LABEL: shift4:
; ZBS:       # %bb.0: # %entry
; ZBS-NEXT:    not a0, a0
; ZBS-NEXT:    srli a0, a0, 4
; ZBS-NEXT:    not a0, a0
; ZBS-NEXT:    ret
entry:
  %div81 = lshr i64 %__n, 4
  %sub10 = or disjoint i64 %div81, -1152921504606846976
  ret i64 %sub10
}

define i64 @invalid(i64 %__n) {
; CHECK-LABEL: invalid:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srli a0, a0, 4
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    slli a1, a1, 58
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    ret
;
; ZBS-LABEL: invalid:
; ZBS:       # %bb.0: # %entry
; ZBS-NEXT:    srli a0, a0, 4
; ZBS-NEXT:    li a1, 15
; ZBS-NEXT:    slli a1, a1, 58
; ZBS-NEXT:    or a0, a0, a1
; ZBS-NEXT:    ret
entry:
  %div81 = lshr i64 %__n, 4
  %sub10 = or disjoint i64 %div81, 4323455642275676160
  ret i64 %sub10
}

