; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v --riscv-v-vector-bits-min=128 -verify-machineinstrs | FileCheck %s

define i8 @extractelement_i8(ptr %in) {
; CHECK-LABEL: extractelement_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = extractelement <2 x i8> %1, i64 1
  ret i8 %2
}

define i16 @extractelement_sext_i8_i16(ptr %in) {
; CHECK-LABEL: extractelement_sext_i8_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lb a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = sext <2 x i8> %1 to <2 x i16>
  %3 = extractelement <2 x i16> %2, i64 1
  ret i16 %3
}

define i16 @extractelement_zext_i8_i16(ptr %in) {
; CHECK-LABEL: extractelement_zext_i8_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = zext <2 x i8> %1 to <2 x i16>
  %3 = extractelement <2 x i16> %2, i64 1
  ret i16 %3
}

define i32 @extractelement_sext_i8_i32(ptr %in) {
; CHECK-LABEL: extractelement_sext_i8_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lb a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = sext <2 x i8> %1 to <2 x i32>
  %3 = extractelement <2 x i32> %2, i64 1
  ret i32 %3
}

define i32 @extractelement_zext_i8_i32(ptr %in) {
; CHECK-LABEL: extractelement_zext_i8_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = zext <2 x i8> %1 to <2 x i32>
  %3 = extractelement <2 x i32> %2, i64 1
  ret i32 %3
}

define i64 @extractelement_sext_i8_i64(ptr %in) {
; CHECK-LABEL: extractelement_sext_i8_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lb a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = sext <2 x i8> %1 to <2 x i64>
  %3 = extractelement <2 x i64> %2, i64 1
  ret i64 %3
}

define i64 @extractelement_zext_i8_i64(ptr %in) {
; CHECK-LABEL: extractelement_zext_i8_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 1(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i8>, ptr %in, align 1
  %2 = zext <2 x i8> %1 to <2 x i64>
  %3 = extractelement <2 x i64> %2, i64 1
  ret i64 %3
}

define i16 @extractelement_i16(ptr %in) {
; CHECK-LABEL: extractelement_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh a0, 2(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i16>, ptr %in, align 2
  %2 = extractelement <2 x i16> %1, i64 1
  ret i16 %2
}

define i32 @extractelement_sext_i16_i32(ptr %in) {
; CHECK-LABEL: extractelement_sext_i16_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh a0, 2(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i16>, ptr %in, align 2
  %2 = sext <2 x i16> %1 to <2 x i32>
  %3 = extractelement <2 x i32> %2, i64 1
  ret i32 %3
}

define i32 @extractelement_zext_i16_i32(ptr %in) {
; CHECK-LABEL: extractelement_zext_i16_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhu a0, 2(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i16>, ptr %in, align 2
  %2 = zext <2 x i16> %1 to <2 x i32>
  %3 = extractelement <2 x i32> %2, i64 1
  ret i32 %3
}

define i64 @extractelement_sext_i16_i64(ptr %in) {
; CHECK-LABEL: extractelement_sext_i16_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh a0, 2(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i16>, ptr %in, align 2
  %2 = sext <2 x i16> %1 to <2 x i64>
  %3 = extractelement <2 x i64> %2, i64 1
  ret i64 %3
}

define i64 @extractelement_zext_i16_i64(ptr %in) {
; CHECK-LABEL: extractelement_zext_i16_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhu a0, 2(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i16>, ptr %in, align 2
  %2 = zext <2 x i16> %1 to <2 x i64>
  %3 = extractelement <2 x i64> %2, i64 1
  ret i64 %3
}

define i32 @extractelement_i32(ptr %in) {
; CHECK-LABEL: extractelement_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a0, 4(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i32>, ptr %in, align 4
  %2 = extractelement <2 x i32> %1, i64 1
  ret i32 %2
}

define i64 @extractelement_sext_i32_i64(ptr %in) {
; CHECK-LABEL: extractelement_sext_i32_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a0, 4(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i32>, ptr %in, align 4
  %2 = sext <2 x i32> %1 to <2 x i64>
  %3 = extractelement <2 x i64> %2, i64 1
  ret i64 %3
}

define i64 @extractelement_zext_i32_i64(ptr %in) {
; CHECK-LABEL: extractelement_zext_i32_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwu a0, 4(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i32>, ptr %in, align 4
  %2 = zext <2 x i32> %1 to <2 x i64>
  %3 = extractelement <2 x i64> %2, i64 1
  ret i64 %3
}

define i64 @extractelement_i64(ptr %in) {
; CHECK-LABEL: extractelement_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    ret
  %1 = load <2 x i64>, ptr %in, align 8
  %2 = extractelement <2 x i64> %1, i64 1
  ret i64 %2
}
