# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -o - %s -mtriple=riscv64 -verify-machineinstrs \
# RUN:   -run-pass=riscv-mc-constprop | FileCheck --check-prefix=RV64 %s
# RUN: llc -o - %s -mtriple=riscv32 -verify-machineinstrs \
# RUN:   -run-pass=riscv-mc-constprop | FileCheck --check-prefix=RV32 %s

--- |
  define void @case1_fold() { ret void }
  define void @case1_dont_fold() { ret void }
  define void @case2_fold() { ret void }
  define void @case2_dont_fold() { ret void }
  define void @case3_fold() { ret void }
  define void @case3_fold2() { ret void }
  define void @case3_fold_1() { ret void }
  define void @case3_fold2_1() { ret void }
  define void @case3_postpone_kill() { ret void }
  define void @case1_followed_by_case2() { ret void }
  define void @case3_twouse() { ret void }
  define void @inline_asm() { ret void }
...
---
name: case1_fold
body:             |
  bb.0:
    liveins: $x10
    ; RV64-LABEL: name: case1_fold
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x10 = LW killed renamable $x10, 24
    ; RV64-NEXT: renamable $x10 = XORI killed renamable $x10, 1
    ; RV64-NEXT: renamable $x10 = SLTIU killed renamable $x10, 1
    ; RV32-LABEL: name: case1_fold
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x10 = LW killed renamable $x10, 24
    ; RV32-NEXT: renamable $x10 = XORI killed renamable $x10, 1
    ; RV32-NEXT: renamable $x10 = SLTIU killed renamable $x10, 1
    renamable $x12 = ADDI $x0, 1
    renamable $x10 = LW killed renamable $x10, 24
    renamable $x10 = XOR killed renamable $x10, killed renamable $x12
    renamable $x10 = SLTIU killed renamable $x10, 1
...
---
name: case1_dont_fold
body:             |
  bb.0:
    liveins: $x10
    ; RV64-LABEL: name: case1_dont_fold
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x12 = ADDI $x0, 1
    ; RV64-NEXT: renamable $x10 = LW killed renamable $x10, 24
    ; RV64-NEXT: renamable $x11 = LW renamable $x12, 24
    ; RV64-NEXT: renamable $x10 = XOR killed renamable $x10, killed renamable $x12
    ; RV64-NEXT: renamable $x10 = SLTIU killed renamable $x10, 1
    ; RV32-LABEL: name: case1_dont_fold
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x12 = ADDI $x0, 1
    ; RV32-NEXT: renamable $x10 = LW killed renamable $x10, 24
    ; RV32-NEXT: renamable $x11 = LW renamable $x12, 24
    ; RV32-NEXT: renamable $x10 = XOR killed renamable $x10, killed renamable $x12
    ; RV32-NEXT: renamable $x10 = SLTIU killed renamable $x10, 1
    renamable $x12 = ADDI $x0, 1
    renamable $x10 = LW killed renamable $x10, 24
    renamable $x11 = LW renamable $x12, 24
    renamable $x10 = XOR killed renamable $x10, killed renamable $x12
    renamable $x10 = SLTIU killed renamable $x10, 1
...
---
name: case2_fold
tracksRegLiveness: true
body:             |
  bb.0:
    ; RV64-LABEL: name: case2_fold
    ; RV64: renamable $x13 = ADDI $x0, 14
    ; RV32-LABEL: name: case2_fold
    ; RV32: renamable $x13 = ADDI $x0, 14
    renamable $x10 = ADDI $x0, 7
    renamable $x13 = ADDI killed renamable $x10, 6
    renamable $x13 = nuw ADDI killed renamable $x13, 1
...
---
name: case2_dont_fold
tracksRegLiveness: true
body:             |
  bb.0:
    ; RV64-LABEL: name: case2_dont_fold
    ; RV64: renamable $x10 = ADDI $x0, 2040
    ; RV64-NEXT: renamable $x13 = ADDI killed renamable $x10, 8
    ; RV32-LABEL: name: case2_dont_fold
    ; RV32: renamable $x10 = ADDI $x0, 2040
    ; RV32-NEXT: renamable $x13 = ADDI killed renamable $x10, 8
    renamable $x10 = ADDI $x0, 2040
    renamable $x13 = ADDI killed renamable $x10, 8
...
---
name: case3_fold
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x6, $x13
    ; RV64-LABEL: name: case3_fold
    ; RV64: liveins: $x6, $x13
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x13 = ADD killed $x6, $x13
    ; RV64-NEXT: renamable $x13 = nuw ADDI killed renamable $x13, 1
    ; RV32-LABEL: name: case3_fold
    ; RV32: liveins: $x6, $x13
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x13 = ADD killed $x6, $x13
    ; RV32-NEXT: renamable $x13 = nuw ADDI killed renamable $x13, 1
    renamable $x10 = ADD $x0, killed $x6
    renamable $x13 = ADD killed renamable $x10, $x13
    renamable $x13 = nuw ADDI killed renamable $x13, 1
...
---
name: case3_fold2
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x6, $x13
    ; RV64-LABEL: name: case3_fold2
    ; RV64: liveins: $x6, $x13
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x13 = ORI killed $x6, 1
    ;
    ; RV32-LABEL: name: case3_fold2
    ; RV32: liveins: $x6, $x13
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x13 = ORI killed $x6, 1
    renamable $x10 = ADD $x0, killed $x6
    renamable $x13 = ORI killed renamable $x10, 1
...
---
name: case3_fold_1
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x6, $x13
    ; RV64-LABEL: name: case3_fold_1
    ; RV64: liveins: $x6, $x13
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x13 = ADD killed renamable $x6, $x13
    ; RV64-NEXT: renamable $x13 = nuw ADDI killed renamable $x13, 1
    ; RV32-LABEL: name: case3_fold_1
    ; RV32: liveins: $x6, $x13
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x13 = ADD killed renamable $x6, $x13
    ; RV32-NEXT: renamable $x13 = nuw ADDI killed renamable $x13, 1
    renamable $x10 = ADDI killed renamable $x6, 0
    renamable $x13 = ADD killed renamable $x10, $x13
    renamable $x13 = nuw ADDI killed renamable $x13, 1
...
---
name: case3_fold2_1
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x6, $x13
    ; RV64-LABEL: name: case3_fold2_1
    ; RV64: liveins: $x6, $x13
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x13 = ORI killed $x6, 1
    ; RV32-LABEL: name: case3_fold2_1
    ; RV32: liveins: $x6, $x13
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x13 = ORI killed $x6, 1
    renamable $x10 = ADDI killed $x6, 0
    renamable $x13 = ORI killed renamable $x10, 1
...
---
name: case3_postpone_kill
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x2, $x13
    ; RV64-LABEL: name: case3_postpone_kill
    ; RV64: liveins: $x2, $x13
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x11 = DIV $x13, $x2
    ; RV64-NEXT: renamable $x12 = ADD killed $x2, killed renamable $x11
    ; RV32-LABEL: name: case3_postpone_kill
    ; RV32: liveins: $x2, $x13
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x11 = DIV $x13, $x2
    ; RV32-NEXT: renamable $x12 = ADD killed $x2, killed renamable $x11
    renamable $x10 = ADD $x0, $x2
    renamable $x11 = DIV $x13, killed $x2
    renamable $x12 = ADD killed renamable $x10, killed renamable $x11
...
---
name: case1_followed_by_case2
tracksRegLiveness: true
body:             |
  bb.0:
    ; RV64-LABEL: name: case1_followed_by_case2
    ; RV64: renamable $x13 = ADDI $x0, 3
    ; RV32-LABEL: name: case1_followed_by_case2
    ; RV32: renamable $x13 = ADDI $x0, 3
    renamable $x10 = ADDI $x0, 1
    renamable $x11 = ADDI $x0, 2
    renamable $x13 = ADD killed renamable $x10, killed renamable $x11
...
---
name: case3_twouse
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10
    ; RV64-LABEL: name: case3_twouse
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x12 = ADD $x0, $x10
    ; RV64-NEXT: renamable $x10 = SH1ADD killed renamable $x12, renamable $x12
    ; RV32-LABEL: name: case3_twouse
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x12 = ADD $x0, $x10
    ; RV32-NEXT: renamable $x10 = SH1ADD killed renamable $x12, renamable $x12
    renamable $x12 = ADD $x0, $x10
    renamable $x10 = SH1ADD killed renamable $x12, renamable $x12
...
---
name: inline_asm
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10
    ; RV64-LABEL: name: inline_asm
    ; RV64: liveins: $x10
    ; RV64-NEXT: {{  $}}
    ; RV64-NEXT: renamable $x12 = ADDI $x0, 1
    ; RV64-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */, 10 /* regdef */, implicit-def $x12
    ; RV64-NEXT: renamable $x10 = XOR killed renamable $x10, killed renamable $x12
    ; RV32-LABEL: name: inline_asm
    ; RV32: liveins: $x10
    ; RV32-NEXT: {{  $}}
    ; RV32-NEXT: renamable $x12 = ADDI $x0, 1
    ; RV32-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */, 10 /* regdef */, implicit-def $x12
    ; RV32-NEXT: renamable $x10 = XOR killed renamable $x10, killed renamable $x12
    renamable $x12 = ADDI $x0, 1
    INLINEASM &"", 1, 10, implicit-def $x12
    renamable $x10 = XOR killed renamable $x10, killed renamable $x12
