; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv32 | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc < %s -mtriple=riscv64 | FileCheck %s --check-prefixes=CHECK,RV64

define signext i32 @test_i16(ptr %x, ptr %y) {
; CHECK-LABEL: test_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhu a0, 0(a0)
; CHECK-NEXT:    srli a0, a0, 2
; CHECK-NEXT:    andi a0, a0, -4
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    lw a0, 0(a0)
; CHECK-NEXT:    ret
  %a = load i16, ptr %x
  %b = lshr i16 %a, 4
  %c = zext nneg i16 %b to i64
  %d = getelementptr i32, ptr %y, i64 %c
  %e = load i32, ptr %d
  ret i32 %e
}

define signext i32 @test_i32(ptr %x, ptr %y) {
; RV32-LABEL: test_i32:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    srli a0, a0, 5
; RV32-NEXT:    andi a0, a0, -4
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    lw a0, 0(a0)
; RV32-NEXT:    ret
;
; RV64-LABEL: test_i32:
; RV64:       # %bb.0:
; RV64-NEXT:    lwu a0, 0(a0)
; RV64-NEXT:    srli a0, a0, 5
; RV64-NEXT:    andi a0, a0, -4
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    lw a0, 0(a0)
; RV64-NEXT:    ret
  %a = load i32, ptr %x
  %b = lshr i32 %a, 7
  %c = zext nneg i32 %b to i64
  %d = getelementptr i32, ptr %y, i64 %c
  %e = load i32, ptr %d
  ret i32 %e
}
