; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-x280n -misched-postra -enable-post-misched \
;RUN:     | FileCheck %s

@.str = private unnamed_addr constant [31 x i8] c"TESTCASES PROGRAM, 1'ST STRCPY\00", align 1
@.str.1 = private unnamed_addr constant [31 x i8] c"TESTCASES PROGRAM, 2'ND STRCPY\00", align 1

define signext i32 @main() {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -80
; CHECK-NEXT:    .cfi_def_cfa_offset 80
; CHECK-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    lui a2, %hi(.LCPI0_2)
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    lui a1, %hi(.LCPI0_1)
; CHECK-NEXT:    lui a3, 275749
; CHECK-NEXT:    lui a4, %hi(.LCPI0_3)
; CHECK-NEXT:    addi a3, a3, 1107
; CHECK-NEXT:    ld a2, %lo(.LCPI0_2)(a2)
; CHECK-NEXT:    sd a2, 56(sp)
; CHECK-NEXT:    lui a2, 6
; CHECK-NEXT:    ld a0, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    addi a2, a2, -1712
; CHECK-NEXT:    ld a1, %lo(.LCPI0_1)(a1)
; CHECK-NEXT:    sd a0, 40(sp)
; CHECK-NEXT:    sd a1, 48(sp)
; CHECK-NEXT:    sh a2, 36(sp)
; CHECK-NEXT:    sb zero, 38(sp)
; CHECK-NEXT:    ld a4, %lo(.LCPI0_3)(a4)
; CHECK-NEXT:    sd a0, 8(sp)
; CHECK-NEXT:    addi a0, sp, 40
; CHECK-NEXT:    sd a1, 16(sp)
; CHECK-NEXT:    addi a1, sp, 8
; CHECK-NEXT:    sw a3, 64(sp)
; CHECK-NEXT:    sh a2, 68(sp)
; CHECK-NEXT:    sb zero, 70(sp)
; CHECK-NEXT:    sd a4, 24(sp)
; CHECK-NEXT:    sw a3, 32(sp)
; CHECK-NEXT:    call foo
; CHECK-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    addi sp, sp, 80
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %Loc_1 = alloca [31 x i8], align 8
  %Loc_2 = alloca [31 x i8], align 8
  call void @llvm.lifetime.start.p0(i64 31, ptr nonnull %Loc_1)
  call void @llvm.lifetime.start.p0(i64 31, ptr nonnull %Loc_2)
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(31) %Loc_1, ptr noundef nonnull align 1 dereferenceable(31) @.str, i64 31, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(31) %Loc_2, ptr noundef nonnull align 1 dereferenceable(31) @.str.1, i64 31, i1 false)
  %call5 = call signext i32 @foo(ptr noundef nonnull %Loc_1, ptr noundef nonnull %Loc_2)
  call void @llvm.lifetime.end.p0(i64 31, ptr nonnull %Loc_2)
  call void @llvm.lifetime.end.p0(i64 31, ptr nonnull %Loc_1)
  ret i32 %call5
}

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare signext i32 @foo(ptr noundef, ptr noundef)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)
