; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -relocation-model=pic -code-model=compact < %s \
; RUN:   -mattr=+f -target-abi=lp64f | FileCheck %s --check-prefixes=PIC
; RUN: llc -mtriple=riscv64 -code-model=compact < %s \
; RUN:   | FileCheck %s --check-prefixes=NoPIC

@src = external global i32, align 4
@lsrc = internal global i32 0, align 4
@dst = external global i32, align 4
@ptr = external  global ptr, align 8

@unspecified = external thread_local global i32
@ld = external thread_local(localdynamic) global i32
@ie = external thread_local(initialexec) global i32
@le = external thread_local(localexec) global i32

define void @test1() {
; PIC-LABEL: test1:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi0:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi0)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a1, %got_gprel_hi(src)
; PIC-NEXT:    add a1, a0, a1, %got_gprel(src)
; PIC-NEXT:    ld a1, %got_gprel_lo(src)(a1)
; PIC-NEXT:    lw a1, 0(a1)
; PIC-NEXT:    lui a0, %got_gprel_hi(dst)
; PIC-NEXT:    add a0, a0, a0, %got_gprel(dst)
; PIC-NEXT:    ld a0, %got_gprel_lo(dst)(a0)
; PIC-NEXT:    sw a1, 0(a0)
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test1:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %got_gprel_hi(src)
; NoPIC-NEXT:    add a0, gp, a0, %got_gprel(src)
; NoPIC-NEXT:    ld a0, %got_gprel_lo(src)(a0)
; NoPIC-NEXT:    lw a0, 0(a0)
; NoPIC-NEXT:    lui a1, %got_gprel_hi(dst)
; NoPIC-NEXT:    add a1, gp, a1, %got_gprel(dst)
; NoPIC-NEXT:    ld a1, %got_gprel_lo(dst)(a1)
; NoPIC-NEXT:    sw a0, 0(a1)
; NoPIC-NEXT:    ret
entry:
  %0 = load i32, ptr @src, align 4
  store i32 %0, ptr @dst, align 4
  ret void
}

define void @test2() {
; PIC-LABEL: test2:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi1:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi1)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a1, %got_gprel_hi(ptr)
; PIC-NEXT:    add a1, a0, a1, %got_gprel(ptr)
; PIC-NEXT:    ld a1, %got_gprel_lo(ptr)(a1)
; PIC-NEXT:    lui a0, %got_gprel_hi(lsrc)
; PIC-NEXT:    add a0, a0, a0, %got_gprel(lsrc)
; PIC-NEXT:    ld a0, %got_gprel_lo(lsrc)(a0)
; PIC-NEXT:    sd a0, 0(a1)
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test2:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %got_gprel_hi(ptr)
; NoPIC-NEXT:    add a0, gp, a0, %got_gprel(ptr)
; NoPIC-NEXT:    ld a0, %got_gprel_lo(ptr)(a0)
; NoPIC-NEXT:    lui a1, %got_gprel_hi(lsrc)
; NoPIC-NEXT:    add a1, gp, a1, %got_gprel(lsrc)
; NoPIC-NEXT:    ld a1, %got_gprel_lo(lsrc)(a1)
; NoPIC-NEXT:    sd a1, 0(a0)
; NoPIC-NEXT:    ret
entry:
  store ptr @lsrc, ptr @ptr, align 8
  ret void
}

define void @test3() {
; PIC-LABEL: test3:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi2:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi2)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a1, %got_gprel_hi(ptr)
; PIC-NEXT:    add a1, a0, a1, %got_gprel(ptr)
; PIC-NEXT:    ld a1, %got_gprel_lo(ptr)(a1)
; PIC-NEXT:    lui a0, %got_gprel_hi(src)
; PIC-NEXT:    add a0, a0, a0, %got_gprel(src)
; PIC-NEXT:    ld a0, %got_gprel_lo(src)(a0)
; PIC-NEXT:    sd a0, 0(a1)
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test3:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %got_gprel_hi(ptr)
; NoPIC-NEXT:    add a0, gp, a0, %got_gprel(ptr)
; NoPIC-NEXT:    ld a0, %got_gprel_lo(ptr)(a0)
; NoPIC-NEXT:    lui a1, %got_gprel_hi(src)
; NoPIC-NEXT:    add a1, gp, a1, %got_gprel(src)
; NoPIC-NEXT:    ld a1, %got_gprel_lo(src)(a1)
; NoPIC-NEXT:    sd a1, 0(a0)
; NoPIC-NEXT:    ret
entry:
  store ptr @src, ptr @ptr, align 8
  ret void
}

define void @test4() {
; PIC-LABEL: test4:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi3:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi3)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui t1, %got_gprel_hi(foo)
; PIC-NEXT:    add t1, a0, t1, %got_gprel(foo)
; PIC-NEXT:    ld t1, %got_gprel_lo(foo)(t1)
; PIC-NEXT:    jr t1
;
; NoPIC-LABEL: test4:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui t1, %got_gprel_hi(foo)
; NoPIC-NEXT:    add t1, gp, t1, %got_gprel(foo)
; NoPIC-NEXT:    ld t1, %got_gprel_lo(foo)(t1)
; NoPIC-NEXT:    jr t1
entry:
  tail call void @foo()
  ret void
}

define i32* @test5() nounwind {
; PIC-LABEL: test5:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    addi sp, sp, -16
; PIC-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; PIC-NEXT:  .Lpcrel_hi4:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi4)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a1, %got_gprel_hi(__tls_get_addr)
; PIC-NEXT:    add a1, a0, a1, %got_gprel(__tls_get_addr)
; PIC-NEXT:    ld a1, %got_gprel_lo(__tls_get_addr)(a1)
; PIC-NEXT:    lui a0, %tls_gd_gprel_hi(unspecified)
; PIC-NEXT:    add a0, a0, a0, %tls_gd_gprel(unspecified)
; PIC-NEXT:    addi a0, a0, %tls_gd_gprel_lo(unspecified)
; PIC-NEXT:    jalr a1
; PIC-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; PIC-NEXT:    addi sp, sp, 16
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test5:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %tls_ie_gprel_hi(unspecified)
; NoPIC-NEXT:    add a0, gp, a0, %tls_ie_gprel(unspecified)
; NoPIC-NEXT:    ld a0, %tls_ie_gprel_lo(unspecified)(a0)
; NoPIC-NEXT:    add a0, a0, tp
; NoPIC-NEXT:    ret
entry:
  ret i32* @unspecified
}

define i32* @test6() nounwind {
; PIC-LABEL: test6:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    addi sp, sp, -16
; PIC-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; PIC-NEXT:  .Lpcrel_hi5:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi5)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a1, %got_gprel_hi(__tls_get_addr)
; PIC-NEXT:    add a1, a0, a1, %got_gprel(__tls_get_addr)
; PIC-NEXT:    ld a1, %got_gprel_lo(__tls_get_addr)(a1)
; PIC-NEXT:    lui a0, %tls_gd_gprel_hi(ld)
; PIC-NEXT:    add a0, a0, a0, %tls_gd_gprel(ld)
; PIC-NEXT:    addi a0, a0, %tls_gd_gprel_lo(ld)
; PIC-NEXT:    jalr a1
; PIC-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; PIC-NEXT:    addi sp, sp, 16
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test6:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %tls_ie_gprel_hi(ld)
; NoPIC-NEXT:    add a0, gp, a0, %tls_ie_gprel(ld)
; NoPIC-NEXT:    ld a0, %tls_ie_gprel_lo(ld)(a0)
; NoPIC-NEXT:    add a0, a0, tp
; NoPIC-NEXT:    ret
entry:
  ret i32* @ld
}

define i32* @test7() nounwind {
; PIC-LABEL: test7:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi6:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi6)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a0, %tls_ie_gprel_hi(ie)
; PIC-NEXT:    add a0, a0, a0, %tls_ie_gprel(ie)
; PIC-NEXT:    ld a0, %tls_ie_gprel_lo(ie)(a0)
; PIC-NEXT:    add a0, a0, tp
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test7:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %tls_ie_gprel_hi(ie)
; NoPIC-NEXT:    add a0, gp, a0, %tls_ie_gprel(ie)
; NoPIC-NEXT:    ld a0, %tls_ie_gprel_lo(ie)(a0)
; NoPIC-NEXT:    add a0, a0, tp
; NoPIC-NEXT:    ret
entry:
  ret i32* @ie
}

define i32* @test8() nounwind {
; PIC-LABEL: test8:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    lui a0, %tprel_hi(le)
; PIC-NEXT:    add a0, a0, tp, %tprel_add(le)
; PIC-NEXT:    addi a0, a0, %tprel_lo(le)
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test8:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %tprel_hi(le)
; NoPIC-NEXT:    add a0, a0, tp, %tprel_add(le)
; NoPIC-NEXT:    addi a0, a0, %tprel_lo(le)
; NoPIC-NEXT:    ret
entry:
  ret i32* @le
}

declare void @foo()

; Check lowering of blockaddresses

@addr = global i8* null

define void @lower_blockaddress() nounwind {
; PIC-LABEL: lower_blockaddress:
; PIC:       # %bb.0:
; PIC-NEXT:  .Lpcrel_hi7:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi7)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a0, %got_gprel_hi(addr)
; PIC-NEXT:    add a0, a0, a0, %got_gprel(addr)
; PIC-NEXT:    ld a0, %got_gprel_lo(addr)(a0)
; PIC-NEXT:    li a1, 1
; PIC-NEXT:    sd a1, 0(a0)
; PIC-NEXT:    ret
;
; NoPIC-LABEL: lower_blockaddress:
; NoPIC:       # %bb.0:
; NoPIC-NEXT:    lui a0, %got_gprel_hi(addr)
; NoPIC-NEXT:    add a0, gp, a0, %got_gprel(addr)
; NoPIC-NEXT:    ld a0, %got_gprel_lo(addr)(a0)
; NoPIC-NEXT:    li a1, 1
; NoPIC-NEXT:    sd a1, 0(a0)
; NoPIC-NEXT:    ret
  store volatile i8* blockaddress(@lower_blockaddress, %block), i8** @addr
  ret void

block:
  unreachable
}

; Check lowering of blockaddress that forces a displacement to be added

define signext i32 @lower_blockaddress_displ(i32 signext %w) nounwind {
; PIC-LABEL: lower_blockaddress_displ:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    addi sp, sp, -16
; PIC-NEXT:  .Lpcrel_hi8:
; PIC-NEXT:    auipc a1, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a1, a1, %pcrel_lo(.Lpcrel_hi8)
; PIC-NEXT:    ld a2, 0(a1)
; PIC-NEXT:    add a1, a1, a2
; PIC-NEXT:    lui a1, %got_gprel_hi(.Ltmp0)
; PIC-NEXT:    add a1, a1, a1, %got_gprel(.Ltmp0)
; PIC-NEXT:    ld a1, %got_gprel_lo(.Ltmp0)(a1)
; PIC-NEXT:    li a2, 101
; PIC-NEXT:    sd a1, 8(sp)
; PIC-NEXT:    blt a0, a2, .LBB9_3
; PIC-NEXT:  # %bb.1: # %if.then
; PIC-NEXT:    ld a0, 8(sp)
; PIC-NEXT:    jr a0
; PIC-NEXT:  .Ltmp0: # Block address taken
; PIC-NEXT:  .LBB9_2: # %return
; PIC-NEXT:    li a0, 4
; PIC-NEXT:    addi sp, sp, 16
; PIC-NEXT:    ret
; PIC-NEXT:  .LBB9_3: # %return.clone
; PIC-NEXT:    li a0, 3
; PIC-NEXT:    addi sp, sp, 16
; PIC-NEXT:    ret
;
; NoPIC-LABEL: lower_blockaddress_displ:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    addi sp, sp, -16
; NoPIC-NEXT:    lui a1, %got_gprel_hi(.Ltmp0)
; NoPIC-NEXT:    add a1, gp, a1, %got_gprel(.Ltmp0)
; NoPIC-NEXT:    ld a1, %got_gprel_lo(.Ltmp0)(a1)
; NoPIC-NEXT:    li a2, 101
; NoPIC-NEXT:    sd a1, 8(sp)
; NoPIC-NEXT:    blt a0, a2, .LBB9_3
; NoPIC-NEXT:  # %bb.1: # %if.then
; NoPIC-NEXT:    ld a0, 8(sp)
; NoPIC-NEXT:    jr a0
; NoPIC-NEXT:  .Ltmp0: # Block address taken
; NoPIC-NEXT:  .LBB9_2: # %return
; NoPIC-NEXT:    li a0, 4
; NoPIC-NEXT:    addi sp, sp, 16
; NoPIC-NEXT:    ret
; NoPIC-NEXT:  .LBB9_3: # %return.clone
; NoPIC-NEXT:    li a0, 3
; NoPIC-NEXT:    addi sp, sp, 16
; NoPIC-NEXT:    ret
entry:
  %x = alloca i8*, align 8
  store i8* blockaddress(@lower_blockaddress_displ, %test_block), i8** %x, align 8
  %cmp = icmp sgt i32 %w, 100
  br i1 %cmp, label %if.then, label %if.end

if.then:
  %addr = load i8*, i8** %x, align 8
  br label %indirectgoto

if.end:
  br label %return

test_block:
  br label %return

return:
  %retval = phi i32 [ 3, %if.end ], [ 4, %test_block ]
  ret i32 %retval

indirectgoto:
  indirectbr i8* %addr, [ label %test_block ]
}

; Check lowering of constantpools

define float @lower_constantpool(float %a) nounwind {
; PIC-LABEL: lower_constantpool:
; PIC:       # %bb.0:
; PIC-NEXT:    lui a0, 260096
; PIC-NEXT:    fmv.w.x fa5, a0
; PIC-NEXT:    fadd.s fa0, fa0, fa5
; PIC-NEXT:    ret
;
; NoPIC-LABEL: lower_constantpool:
; NoPIC:       # %bb.0:
; NoPIC-NEXT:    addi sp, sp, -16
; NoPIC-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; NoPIC-NEXT:    lui a2, %got_gprel_hi(__addsf3)
; NoPIC-NEXT:    add a2, gp, a2, %got_gprel(__addsf3)
; NoPIC-NEXT:    ld a2, %got_gprel_lo(__addsf3)(a2)
; NoPIC-NEXT:    lui a1, 260096
; NoPIC-NEXT:    jalr a2
; NoPIC-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; NoPIC-NEXT:    addi sp, sp, 16
; NoPIC-NEXT:    ret
  %1 = fadd float %a, 1.0
  ret float %1
}

; Check lowering of jump tables

define void @lower_jumptable(i32 %in, i32* %out) nounwind {
; PIC-LABEL: lower_jumptable:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi9:
; PIC-NEXT:    auipc a2, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a2, a2, %pcrel_lo(.Lpcrel_hi9)
; PIC-NEXT:    ld a3, 0(a2)
; PIC-NEXT:    sext.w a0, a0
; PIC-NEXT:    addi a0, a0, -1
; PIC-NEXT:    li a4, 5
; PIC-NEXT:    bltu a4, a0, .LBB11_9
; PIC-NEXT:  # %bb.1: # %entry
; PIC-NEXT:    add a2, a2, a3
; PIC-NEXT:    lui a2, %got_gprel_hi(.LJTI11_0)
; PIC-NEXT:    add a2, a2, a2, %got_gprel(.LJTI11_0)
; PIC-NEXT:    ld a2, %got_gprel_lo(.LJTI11_0)(a2)
; PIC-NEXT:    slli a0, a0, 2
; PIC-NEXT:    add a0, a2, a0
; PIC-NEXT:    lw a0, 0(a0)
; PIC-NEXT:    add a0, a2, a0
; PIC-NEXT:    jr a0
; PIC-NEXT:  .LBB11_2: # %bb1
; PIC-NEXT:    li a0, 4
; PIC-NEXT:    j .LBB11_8
; PIC-NEXT:  .LBB11_3: # %bb5
; PIC-NEXT:    li a0, 100
; PIC-NEXT:    j .LBB11_8
; PIC-NEXT:  .LBB11_4: # %bb3
; PIC-NEXT:    li a0, 2
; PIC-NEXT:    j .LBB11_8
; PIC-NEXT:  .LBB11_5: # %bb4
; PIC-NEXT:    li a0, 1
; PIC-NEXT:    j .LBB11_8
; PIC-NEXT:  .LBB11_6: # %bb2
; PIC-NEXT:    li a0, 3
; PIC-NEXT:    j .LBB11_8
; PIC-NEXT:  .LBB11_7: # %bb6
; PIC-NEXT:    li a0, 200
; PIC-NEXT:  .LBB11_8: # %exit
; PIC-NEXT:    sw a0, 0(a1)
; PIC-NEXT:  .LBB11_9: # %exit
; PIC-NEXT:    ret
;
; NoPIC-LABEL: lower_jumptable:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    sext.w a0, a0
; NoPIC-NEXT:    addi a0, a0, -1
; NoPIC-NEXT:    li a2, 5
; NoPIC-NEXT:    bltu a2, a0, .LBB11_9
; NoPIC-NEXT:  # %bb.1: # %entry
; NoPIC-NEXT:    lui a2, %got_gprel_hi(.LJTI11_0)
; NoPIC-NEXT:    add a2, gp, a2, %got_gprel(.LJTI11_0)
; NoPIC-NEXT:    ld a2, %got_gprel_lo(.LJTI11_0)(a2)
; NoPIC-NEXT:    slli a0, a0, 3
; NoPIC-NEXT:    add a0, a2, a0
; NoPIC-NEXT:    ld a0, 0(a0)
; NoPIC-NEXT:    jr a0
; NoPIC-NEXT:  .LBB11_2: # %bb1
; NoPIC-NEXT:    li a0, 4
; NoPIC-NEXT:    j .LBB11_8
; NoPIC-NEXT:  .LBB11_3: # %bb5
; NoPIC-NEXT:    li a0, 100
; NoPIC-NEXT:    j .LBB11_8
; NoPIC-NEXT:  .LBB11_4: # %bb3
; NoPIC-NEXT:    li a0, 2
; NoPIC-NEXT:    j .LBB11_8
; NoPIC-NEXT:  .LBB11_5: # %bb4
; NoPIC-NEXT:    li a0, 1
; NoPIC-NEXT:    j .LBB11_8
; NoPIC-NEXT:  .LBB11_6: # %bb2
; NoPIC-NEXT:    li a0, 3
; NoPIC-NEXT:    j .LBB11_8
; NoPIC-NEXT:  .LBB11_7: # %bb6
; NoPIC-NEXT:    li a0, 200
; NoPIC-NEXT:  .LBB11_8: # %exit
; NoPIC-NEXT:    sw a0, 0(a1)
; NoPIC-NEXT:  .LBB11_9: # %exit
; NoPIC-NEXT:    ret
entry:
  switch i32 %in, label %exit [
    i32 1, label %bb1
    i32 2, label %bb2
    i32 3, label %bb3
    i32 4, label %bb4
    i32 5, label %bb5
    i32 6, label %bb6
  ]
bb1:
  store i32 4, i32* %out
  br label %exit
bb2:
  store i32 3, i32* %out
  br label %exit
bb3:
  store i32 2, i32* %out
  br label %exit
bb4:
  store i32 1, i32* %out
  br label %exit
bb5:
  store i32 100, i32* %out
  br label %exit
bb6:
  store i32 200, i32* %out
  br label %exit
exit:
  ret void
}

define signext i32 @test_ptrtoint_ext() {
; PIC-LABEL: test_ptrtoint_ext:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi10:
; PIC-NEXT:    auipc a0, %pcrel_hi(__global_pointer__)
; PIC-NEXT:    addi a0, a0, %pcrel_lo(.Lpcrel_hi10)
; PIC-NEXT:    ld a1, 0(a0)
; PIC-NEXT:    add a0, a0, a1
; PIC-NEXT:    lui a0, %got_gprel_hi(src)
; PIC-NEXT:    add a0, a0, a0, %got_gprel(src)
; PIC-NEXT:    ld a0, %got_gprel_lo(src)(a0)
; PIC-NEXT:    sext.w a0, a0
; PIC-NEXT:    ret
;
; NoPIC-LABEL: test_ptrtoint_ext:
; NoPIC:       # %bb.0: # %entry
; NoPIC-NEXT:    lui a0, %got_gprel_hi(src)
; NoPIC-NEXT:    add a0, gp, a0, %got_gprel(src)
; NoPIC-NEXT:    ld a0, %got_gprel_lo(src)(a0)
; NoPIC-NEXT:    sext.w a0, a0
; NoPIC-NEXT:    ret
entry:
  %0 = ptrtoint ptr @src to i32
  ret i32 %0
}
