; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+zba,+zbb | FileCheck %s

; There should be no zext.h instructions emitted.

define void @spam(ptr %arg, ptr %arg1, i32 signext %arg2, i32 signext %arg3, ptr %arg4) {
; CHECK-LABEL: spam:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    blez a2, .LBB0_5
; CHECK-NEXT:  # %bb.1: # %bb5
; CHECK-NEXT:    addi a5, a1, 1
; CHECK-NEXT:    addi a0, a0, 2
; CHECK-NEXT:    addi a3, a3, 3
; CHECK-NEXT:    addi a2, a2, -1
; CHECK-NEXT:    sh2add.uw a1, a2, a1
; CHECK-NEXT:    lui a2, 8
; CHECK-NEXT:    addi a1, a1, 5
; CHECK-NEXT:    addi a2, a2, 129
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .LBB0_2: # %bb16
; CHECK-NEXT:    # in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    xori a7, a6, 255
; CHECK-NEXT:    lbu t0, -2(a0)
; CHECK-NEXT:    lbu t1, -1(a5)
; CHECK-NEXT:    lbu t2, -1(a0)
; CHECK-NEXT:    lbu t3, 0(a0)
; CHECK-NEXT:    mul t0, a7, t0
; CHECK-NEXT:    mul t1, t1, a6
; CHECK-NEXT:    add t0, t1, t0
; CHECK-NEXT:    mul t0, t0, a2
; CHECK-NEXT:    srli t0, t0, 23
; CHECK-NEXT:    sb t0, -2(a0)
; CHECK-NEXT:    lbu t0, 0(a5)
; CHECK-NEXT:    mul t1, a7, t2
; CHECK-NEXT:    mul t0, t0, a6
; CHECK-NEXT:    add t0, t0, t1
; CHECK-NEXT:    mul t0, t0, a2
; CHECK-NEXT:    srli t0, t0, 23
; CHECK-NEXT:    sb t0, -1(a0)
; CHECK-NEXT:    lbu t0, 1(a5)
; CHECK-NEXT:    mul a7, a7, t3
; CHECK-NEXT:    addi a5, a5, 4
; CHECK-NEXT:    mul a6, t0, a6
; CHECK-NEXT:    add a6, a6, a7
; CHECK-NEXT:    mul a6, a6, a2
; CHECK-NEXT:    srli a6, a6, 23
; CHECK-NEXT:    sb a6, 0(a0)
; CHECK-NEXT:    add a0, a0, a3
; CHECK-NEXT:    beq a5, a1, .LBB0_5
; CHECK-NEXT:  .LBB0_3: # %bb7
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lbu a6, 2(a5)
; CHECK-NEXT:    beqz a4, .LBB0_2
; CHECK-NEXT:  # %bb.4: # %bb12
; CHECK-NEXT:    # in Loop: Header=BB0_3 Depth=1
; CHECK-NEXT:    lbu a7, 0(a4)
; CHECK-NEXT:    addi a4, a4, 1
; CHECK-NEXT:    mul a6, a7, a6
; CHECK-NEXT:    mul a6, a6, a2
; CHECK-NEXT:    srli a6, a6, 23
; CHECK-NEXT:    j .LBB0_2
; CHECK-NEXT:  .LBB0_5: # %bb6
; CHECK-NEXT:    ret
bb:
  %icmp = icmp sgt i32 %arg2, 0
  br i1 %icmp, label %bb5, label %bb6

bb5:                                              ; preds = %bb
  %sext = sext i32 %arg3 to i64
  br label %bb7

bb6:                                              ; preds = %bb16, %bb
  ret void

bb7:                                              ; preds = %bb16, %bb5
  %phi = phi i32 [ 0, %bb5 ], [ %add53, %bb16 ]
  %phi8 = phi ptr [ %arg, %bb5 ], [ %getelementptr51, %bb16 ]
  %phi9 = phi ptr [ %arg4, %bb5 ], [ %phi17, %bb16 ]
  %phi10 = phi ptr [ %arg1, %bb5 ], [ %getelementptr52, %bb16 ]
  %icmp11 = icmp eq ptr %phi9, null
  %getelementptr = getelementptr inbounds i8, ptr %phi10, i64 3
  %load = load i8, ptr %getelementptr, align 1
  br i1 %icmp11, label %bb16, label %bb12

bb12:                                             ; preds = %bb7
  %zext = zext i8 %load to i16
  %getelementptr13 = getelementptr inbounds nuw i8, ptr %phi9, i64 1
  %load14 = load i8, ptr %phi9, align 1
  %zext15 = zext i8 %load14 to i16
  %mul = mul nuw i16 %zext15, %zext
  %udiv = udiv i16 %mul, 255
  %trunc = trunc nuw i16 %udiv to i8
  br label %bb16

bb16:                                             ; preds = %bb12, %bb7
  %phi17 = phi ptr [ %getelementptr13, %bb12 ], [ null, %bb7 ]
  %phi18 = phi i8 [ %trunc, %bb12 ], [ %load, %bb7 ]
  %zext19 = zext i8 %phi18 to i16
  %xor = xor i16 %zext19, 255
  %load20 = load i8, ptr %phi8, align 1
  %zext21 = zext i8 %load20 to i16
  %mul22 = mul nuw i16 %xor, %zext21
  %load23 = load i8, ptr %phi10, align 1
  %zext24 = zext i8 %load23 to i16
  %mul25 = mul nuw i16 %zext24, %zext19
  %add = add i16 %mul25, %mul22
  %udiv26 = udiv i16 %add, 255
  %trunc27 = trunc i16 %udiv26 to i8
  store i8 %trunc27, ptr %phi8, align 1
  %getelementptr28 = getelementptr inbounds nuw i8, ptr %phi8, i64 1
  %getelementptr29 = getelementptr inbounds nuw i8, ptr %phi10, i64 1
  %load30 = load i8, ptr %getelementptr28, align 1
  %zext31 = zext i8 %load30 to i16
  %mul32 = mul nuw i16 %xor, %zext31
  %load33 = load i8, ptr %getelementptr29, align 1
  %zext34 = zext i8 %load33 to i16
  %mul35 = mul nuw i16 %zext34, %zext19
  %add36 = add i16 %mul35, %mul32
  %udiv37 = udiv i16 %add36, 255
  %trunc38 = trunc i16 %udiv37 to i8
  store i8 %trunc38, ptr %getelementptr28, align 1
  %getelementptr39 = getelementptr inbounds nuw i8, ptr %phi8, i64 2
  %getelementptr40 = getelementptr inbounds nuw i8, ptr %phi10, i64 2
  %load41 = load i8, ptr %getelementptr39, align 1
  %zext42 = zext i8 %load41 to i16
  %mul43 = mul nuw i16 %xor, %zext42
  %load44 = load i8, ptr %getelementptr40, align 1
  %zext45 = zext i8 %load44 to i16
  %mul46 = mul nuw i16 %zext45, %zext19
  %add47 = add i16 %mul46, %mul43
  %udiv48 = udiv i16 %add47, 255
  %trunc49 = trunc i16 %udiv48 to i8
  store i8 %trunc49, ptr %getelementptr39, align 1
  %getelementptr50 = getelementptr inbounds nuw i8, ptr %phi8, i64 3
  %getelementptr51 = getelementptr inbounds i8, ptr %getelementptr50, i64 %sext
  %getelementptr52 = getelementptr inbounds nuw i8, ptr %phi10, i64 4
  %add53 = add nuw nsw i32 %phi, 1
  %icmp54 = icmp eq i32 %add53, %arg2
  br i1 %icmp54, label %bb6, label %bb7
}
