; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=riscv32 -mattr=+m | FileCheck %s --check-prefix=RV32
; RUN: llc < %s -mtriple=riscv64 -mattr=+m | FileCheck %s --check-prefix=RV64

define i8 @composite_basic(i8 %0, i8 %1, i8 %2) {
; RV32-LABEL: composite_basic:
; RV32:       # %bb.0:
; RV32-NEXT:    zext.b a2, a2
; RV32-NEXT:    zext.b a0, a0
; RV32-NEXT:    zext.b a1, a1
; RV32-NEXT:    lui a3, 4112
; RV32-NEXT:    mul a0, a2, a0
; RV32-NEXT:    xori a2, a2, 255
; RV32-NEXT:    mul a1, a2, a1
; RV32-NEXT:    add a0, a1, a0
; RV32-NEXT:    addi a1, a3, 258
; RV32-NEXT:    mulhu a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: composite_basic:
; RV64:       # %bb.0:
; RV64-NEXT:    zext.b a2, a2
; RV64-NEXT:    zext.b a0, a0
; RV64-NEXT:    zext.b a1, a1
; RV64-NEXT:    lui a3, 4112
; RV64-NEXT:    mul a0, a2, a0
; RV64-NEXT:    xori a2, a2, 255
; RV64-NEXT:    mul a1, a2, a1
; RV64-NEXT:    add a0, a1, a0
; RV64-NEXT:    addi a1, a3, 258
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    srli a0, a0, 32
; RV64-NEXT:    ret
  %4 = zext i8 %2 to i32
  %5 = xor i32 %4, 255
  %6 = zext i8 %0 to i32
  %7 = mul i32 %4, %6
  %8 = zext i8 %1 to i32
  %9 = mul i32 %5, %8
  %10 = add i32 %9, %7
  %11 = udiv i32 %10, 255
  %12 = trunc i32 %11 to i8
  ret i8 %12
}

define void @composite_loop(i32 signext %width, i32 signext %channels, ptr %other_row, ptr %this_row) {
; RV32-LABEL: composite_loop:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    blez a0, .LBB1_6
; RV32-NEXT:  # %bb.1: # %for.body.lr.ph
; RV32-NEXT:    blez a1, .LBB1_6
; RV32-NEXT:  # %bb.2: # %for.body.us.preheader
; RV32-NEXT:    li a4, 0
; RV32-NEXT:    lbu a5, 3(a2)
; RV32-NEXT:    add a1, a3, a1
; RV32-NEXT:    lui a7, 8
; RV32-NEXT:    xori a6, a5, 255
; RV32-NEXT:    addi a7, a7, 129
; RV32-NEXT:  .LBB1_3: # %for.body.us
; RV32-NEXT:    # =>This Loop Header: Depth=1
; RV32-NEXT:    # Child Loop BB1_4 Depth 2
; RV32-NEXT:    mv t0, a2
; RV32-NEXT:    mv t1, a3
; RV32-NEXT:  .LBB1_4: # %for.body5.us
; RV32-NEXT:    # Parent Loop BB1_3 Depth=1
; RV32-NEXT:    # => This Inner Loop Header: Depth=2
; RV32-NEXT:    lbu t2, 0(t0)
; RV32-NEXT:    lbu t3, 0(t1)
; RV32-NEXT:    mul t2, t2, a5
; RV32-NEXT:    mul t3, a6, t3
; RV32-NEXT:    add t2, t3, t2
; RV32-NEXT:    mul t2, t2, a7
; RV32-NEXT:    srli t2, t2, 23
; RV32-NEXT:    sb t2, 0(t1)
; RV32-NEXT:    addi t1, t1, 1
; RV32-NEXT:    addi t0, t0, 1
; RV32-NEXT:    bne t1, a1, .LBB1_4
; RV32-NEXT:  # %bb.5: # %for.cond1.for.cond.cleanup4_crit_edge.us
; RV32-NEXT:    # in Loop: Header=BB1_3 Depth=1
; RV32-NEXT:    addi a4, a4, 1
; RV32-NEXT:    bne a4, a0, .LBB1_3
; RV32-NEXT:  .LBB1_6: # %for.cond.cleanup
; RV32-NEXT:    ret
;
; RV64-LABEL: composite_loop:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    blez a0, .LBB1_6
; RV64-NEXT:  # %bb.1: # %for.body.lr.ph
; RV64-NEXT:    blez a1, .LBB1_6
; RV64-NEXT:  # %bb.2: # %for.body.us.preheader
; RV64-NEXT:    li a4, 0
; RV64-NEXT:    lbu a5, 3(a2)
; RV64-NEXT:    addi a1, a1, -1
; RV64-NEXT:    lui a7, 8
; RV64-NEXT:    slli a1, a1, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    add a1, a1, a3
; RV64-NEXT:    addi a1, a1, 1
; RV64-NEXT:    xori a6, a5, 255
; RV64-NEXT:    addi a7, a7, 129
; RV64-NEXT:  .LBB1_3: # %for.body.us
; RV64-NEXT:    # =>This Loop Header: Depth=1
; RV64-NEXT:    # Child Loop BB1_4 Depth 2
; RV64-NEXT:    mv t0, a2
; RV64-NEXT:    mv t1, a3
; RV64-NEXT:  .LBB1_4: # %for.body5.us
; RV64-NEXT:    # Parent Loop BB1_3 Depth=1
; RV64-NEXT:    # => This Inner Loop Header: Depth=2
; RV64-NEXT:    lbu t2, 0(t0)
; RV64-NEXT:    lbu t3, 0(t1)
; RV64-NEXT:    mul t2, t2, a5
; RV64-NEXT:    mul t3, a6, t3
; RV64-NEXT:    add t2, t3, t2
; RV64-NEXT:    mul t2, t2, a7
; RV64-NEXT:    srli t2, t2, 23
; RV64-NEXT:    sb t2, 0(t1)
; RV64-NEXT:    addi t1, t1, 1
; RV64-NEXT:    addi t0, t0, 1
; RV64-NEXT:    bne t1, a1, .LBB1_4
; RV64-NEXT:  # %bb.5: # %for.cond1.for.cond.cleanup4_crit_edge.us
; RV64-NEXT:    # in Loop: Header=BB1_3 Depth=1
; RV64-NEXT:    addiw a4, a4, 1
; RV64-NEXT:    bne a4, a0, .LBB1_3
; RV64-NEXT:  .LBB1_6: # %for.cond.cleanup
; RV64-NEXT:    ret
entry:
  %cmp28 = icmp sgt i32 %width, 0
  br i1 %cmp28, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %arrayidx = getelementptr inbounds i8, ptr %other_row, i32 3
  %0 = load i8, ptr %arrayidx, align 1
  %conv = zext i8 %0 to i16
  %sub = xor i16 %conv, 255
  %cmp226 = icmp sgt i32 %channels, 0
  br i1 %cmp226, label %for.body.us.preheader, label %for.cond.cleanup

for.body.us.preheader:                            ; preds = %for.body.lr.ph
  br label %for.body.us

for.body.us:                                      ; preds = %for.body.us.preheader, %for.cond1.for.cond.cleanup4_crit_edge.us
  %x.029.us = phi i32 [ %inc16.us, %for.cond1.for.cond.cleanup4_crit_edge.us ], [ 0, %for.body.us.preheader ]
  br label %for.body5.us

for.body5.us:                                     ; preds = %for.body.us, %for.body5.us
  %indvars.iv = phi i32 [ 0, %for.body.us ], [ %indvars.iv.next, %for.body5.us ]
  %arrayidx6.us = getelementptr inbounds i8, ptr %other_row, i32 %indvars.iv
  %1 = load i8, ptr %arrayidx6.us, align 1
  %conv7.us = zext i8 %1 to i16
  %mul.us = mul nuw i16 %conv7.us, %conv
  %arrayidx9.us = getelementptr inbounds i8, ptr %this_row, i32 %indvars.iv
  %2 = load i8, ptr %arrayidx9.us, align 1
  %conv10.us = zext i8 %2 to i16
  %mul11.us = mul nuw i16 %sub, %conv10.us
  %add.us = add i16 %mul11.us, %mul.us
  %div.us = udiv i16 %add.us, 255
  %conv12.us = trunc i16 %div.us to i8
  store i8 %conv12.us, ptr %arrayidx9.us, align 1
  %indvars.iv.next = add nuw nsw i32 %indvars.iv, 1
  %exitcond.not = icmp eq i32 %indvars.iv.next, %channels
  br i1 %exitcond.not, label %for.cond1.for.cond.cleanup4_crit_edge.us, label %for.body5.us

for.cond1.for.cond.cleanup4_crit_edge.us:         ; preds = %for.body5.us
  %inc16.us = add nuw nsw i32 %x.029.us, 1
  %exitcond32.not = icmp eq i32 %inc16.us, %width
  br i1 %exitcond32.not, label %for.cond.cleanup.loopexit, label %for.body.us

for.cond.cleanup.loopexit:                        ; preds = %for.cond1.for.cond.cleanup4_crit_edge.us
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %for.body.lr.ph, %entry
  ret void
}
