; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 | FileCheck %s

define signext i32 @signum_basic(i64 %x) {
; CHECK-LABEL: signum_basic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sgtz a1, a0
; CHECK-NEXT:    slti a0, a0, 0
; CHECK-NEXT:    sub a0, a1, a0
; CHECK-NEXT:    ret
  %a = icmp ne i64 %x, 0
  %b = sext i1 %a to i32
  %c = icmp sgt i64 %x, 0
  %d = select i1 %c, i32 1, i32 %b
  ret i32 %d
}

define signext i32 @signum_x_y(i64 %x, i64 %y) {
; CHECK-LABEL: signum_x_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    slt a2, a1, a0
; CHECK-NEXT:    slt a0, a0, a1
; CHECK-NEXT:    sub a0, a2, a0
; CHECK-NEXT:    ret
  %a = icmp ne i64 %x, %y
  %b = sext i1 %a to i32
  %c = icmp sgt i64 %x, %y
  %d = select i1 %c, i32 1, i32 %b
  ret i32 %d
}
