; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 | FileCheck %s --check-prefix=RV32I
; RUN: llc < %s -mtriple=riscv64 | FileCheck %s --check-prefix=RV64I
; RUN: llc < %s -mtriple=riscv32 -mattr=+zbb \
; RUN:   | FileCheck %s --check-prefix=RV32ZBB
; RUN: llc < %s -mtriple=riscv64 -mattr=+zbb \
; RUN:   | FileCheck %s --check-prefix=RV64ZBB

; Make sure we use a min with Zbb. Without Zbb we need to use the nsw
; flag to separate the add from the compare so we can sink it into
; the branch shadow.

define signext i32 @foo(i32 signext %px, i32 signext %y) {
; RV32I-LABEL: foo:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    bge a0, a1, .LBB0_2
; RV32I-NEXT:  # %bb.1: # %entry
; RV32I-NEXT:    addi a1, a0, 1
; RV32I-NEXT:  .LBB0_2: # %entry
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    ret
;
; RV64I-LABEL: foo:
; RV64I:       # %bb.0: # %entry
; RV64I-NEXT:    bge a0, a1, .LBB0_2
; RV64I-NEXT:  # %bb.1: # %entry
; RV64I-NEXT:    addiw a1, a0, 1
; RV64I-NEXT:  .LBB0_2: # %entry
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    ret
;
; RV32ZBB-LABEL: foo:
; RV32ZBB:       # %bb.0: # %entry
; RV32ZBB-NEXT:    addi a0, a0, 1
; RV32ZBB-NEXT:    min a0, a0, a1
; RV32ZBB-NEXT:    ret
;
; RV64ZBB-LABEL: foo:
; RV64ZBB:       # %bb.0: # %entry
; RV64ZBB-NEXT:    addiw a0, a0, 1
; RV64ZBB-NEXT:    min a0, a0, a1
; RV64ZBB-NEXT:    ret
entry:
  %add = add nsw i32 %px, 1
  %cmp = icmp sgt i32 %add, %y
  %spec.select = select i1 %cmp, i32 %y, i32 %add
  ret i32 %spec.select
}
