; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=riscv64 -mattr=+zba -disable-lsr | FileCheck %s

define void @sh1add(ptr %x, i64 %y, i64 %n) {
; CHECK-LABEL: sh1add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB0_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    sh1add a3, a1, a3
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %a = shl i64 %y, 1
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %phi, %a
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

define void @sh2add(ptr %x, i64 %y, i64 %n) {
; CHECK-LABEL: sh2add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB1_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    sh2add a3, a1, a3
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB1_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %a = shl i64 %y, 2
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %a, %phi
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

define void @sh3add(ptr %x, i64 %y, i64 %n) {
; CHECK-LABEL: sh3add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB2_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    sh3add a3, a1, a3
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB2_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %a = shl i64 %y, 3
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %phi, %a
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

define void @sh1add_uw(ptr %x, i32 %y, i64 %n) {
; CHECK-LABEL: sh1add_uw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB3_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    sh1add.uw a3, a1, a3
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB3_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %z = zext i32 %y to i64
  %a = shl i64 %z, 1
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %phi, %a
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

define void @sh2add_uw(ptr %x, i32 %y, i64 %n) {
; CHECK-LABEL: sh2add_uw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB4_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    sh2add.uw a3, a1, a3
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB4_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %z = zext i32 %y to i64
  %a = shl i64 %z, 2
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %a, %phi
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

define void @sh3add_uw(ptr %x, i32 %y, i64 %n) {
; CHECK-LABEL: sh3add_uw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB5_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    sh3add.uw a3, a1, a3
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB5_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %z = zext i32 %y to i64
  %a = shl i64 %z, 3
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %phi, %a
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

; negative tests

define void @negative_sh4add(ptr %x, i64 %y, i64 %n) {
; CHECK-LABEL: negative_sh4add:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    slli a1, a1, 4
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB6_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    add a3, a3, a1
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB6_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %a = shl i64 %y, 4
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %phi, %a
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

define void @negative_sh4add_uw(ptr %x, i32 %y, i64 %n) {
; CHECK-LABEL: negative_sh4add_uw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    slli.uw a1, a1, 4
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:  .LBB7_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    add a5, a0, a3
; CHECK-NEXT:    add a3, a3, a1
; CHECK-NEXT:    sb a4, 0(a5)
; CHECK-NEXT:    bne a3, a2, .LBB7_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %z = zext i32 %y to i64
  %a = shl i64 %z, 4
  br label %loop

loop:
  %phi = phi i64 [0, %entry], [%inc, %loop]
  %gep = getelementptr i8, ptr %x, i64 %phi
  store i8 1, ptr %gep
  %inc = add i64 %phi, %a
  %cmp = icmp eq i64 %inc, %n
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}
