; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 -mattr=+zba,+zfh \
; RUN:   | FileCheck %s --check-prefix=NOFUSION
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 -mattr=+zba,+zfh,+fuse-indexed-load \
; RUN:   | FileCheck %s --check-prefix=FUSEADD
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 -mattr=+zba,+zfh,+fuse-zba-load \
; RUN:   | FileCheck %s --check-prefix=FUSEZBA

; Test fusing add(.uw), shXadd(.uw) with a subsequent load instruction.

define signext i8 @load_i8(ptr %0, ptr %1, i64 %2) {
; NOFUSION-LABEL: load_i8:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    add a1, a1, a2
; NOFUSION-NEXT:    add a0, a0, a2
; NOFUSION-NEXT:    lbu a1, 0(a1)
; NOFUSION-NEXT:    lbu a0, 0(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    slli a0, a0, 56
; NOFUSION-NEXT:    srai a0, a0, 56
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i8:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    add a1, a1, a2
; FUSEADD-NEXT:    lbu a1, 0(a1)
; FUSEADD-NEXT:    add a0, a0, a2
; FUSEADD-NEXT:    lbu a0, 0(a0)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    slli a0, a0, 56
; FUSEADD-NEXT:    srai a0, a0, 56
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i8:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    add a1, a1, a2
; FUSEZBA-NEXT:    lbu a1, 0(a1)
; FUSEZBA-NEXT:    add a0, a0, a2
; FUSEZBA-NEXT:    lbu a0, 0(a0)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    slli a0, a0, 56
; FUSEZBA-NEXT:    srai a0, a0, 56
; FUSEZBA-NEXT:    ret
  %4 = getelementptr inbounds i8, ptr %0, i64 %2
  %5 = load i8, ptr %4, align 1
  %6 = getelementptr inbounds i8, ptr %1, i64 %2
  %7 = load i8, ptr %6, align 1
  %8 = add i8 %7, %5
  ret i8 %8
}

define signext i16 @load_i16(ptr %0, ptr %1, i64 %2) {
; NOFUSION-LABEL: load_i16:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sh1add a1, a2, a1
; NOFUSION-NEXT:    sh1add a0, a2, a0
; NOFUSION-NEXT:    lh a1, 0(a1)
; NOFUSION-NEXT:    lh a0, 0(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    slli a0, a0, 48
; NOFUSION-NEXT:    srai a0, a0, 48
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i16:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    sh1add a1, a2, a1
; FUSEADD-NEXT:    sh1add a0, a2, a0
; FUSEADD-NEXT:    lh a1, 0(a1)
; FUSEADD-NEXT:    lh a0, 0(a0)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    slli a0, a0, 48
; FUSEADD-NEXT:    srai a0, a0, 48
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i16:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    sh1add a1, a2, a1
; FUSEZBA-NEXT:    lh a1, 0(a1)
; FUSEZBA-NEXT:    sh1add a0, a2, a0
; FUSEZBA-NEXT:    lh a0, 0(a0)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    slli a0, a0, 48
; FUSEZBA-NEXT:    srai a0, a0, 48
; FUSEZBA-NEXT:    ret
  %4 = getelementptr inbounds i16, ptr %0, i64 %2
  %5 = load i16, ptr %4, align 2
  %6 = getelementptr inbounds i16, ptr %1, i64 %2
  %7 = load i16, ptr %6, align 2
  %8 = add i16 %7, %5
  ret i16 %8
}

define signext i32 @load_i32(ptr %0, ptr %1, i64 %2) {
; NOFUSION-LABEL: load_i32:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sh2add a1, a2, a1
; NOFUSION-NEXT:    sh2add a0, a2, a0
; NOFUSION-NEXT:    lw a1, 0(a1)
; NOFUSION-NEXT:    lw a0, 0(a0)
; NOFUSION-NEXT:    addw a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i32:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    sh2add a1, a2, a1
; FUSEADD-NEXT:    sh2add a0, a2, a0
; FUSEADD-NEXT:    lw a1, 0(a1)
; FUSEADD-NEXT:    lw a0, 0(a0)
; FUSEADD-NEXT:    addw a0, a0, a1
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i32:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    sh2add a1, a2, a1
; FUSEZBA-NEXT:    lw a1, 0(a1)
; FUSEZBA-NEXT:    sh2add a0, a2, a0
; FUSEZBA-NEXT:    lw a0, 0(a0)
; FUSEZBA-NEXT:    addw a0, a0, a1
; FUSEZBA-NEXT:    ret
  %4 = getelementptr inbounds i32, ptr %0, i64 %2
  %5 = load i32, ptr %4, align 4
  %6 = getelementptr inbounds i32, ptr %1, i64 %2
  %7 = load i32, ptr %6, align 4
  %8 = add i32 %7, %5
  ret i32 %8
}

define signext i64 @load_i64(ptr %0, ptr %1, i64 %2) {
; NOFUSION-LABEL: load_i64:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sh3add a1, a2, a1
; NOFUSION-NEXT:    sh3add a0, a2, a0
; NOFUSION-NEXT:    ld a1, 0(a1)
; NOFUSION-NEXT:    ld a0, 0(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i64:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    sh3add a1, a2, a1
; FUSEADD-NEXT:    sh3add a0, a2, a0
; FUSEADD-NEXT:    ld a1, 0(a1)
; FUSEADD-NEXT:    ld a0, 0(a0)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i64:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    sh3add a1, a2, a1
; FUSEZBA-NEXT:    ld a1, 0(a1)
; FUSEZBA-NEXT:    sh3add a0, a2, a0
; FUSEZBA-NEXT:    ld a0, 0(a0)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    ret
  %4 = getelementptr inbounds i64, ptr %0, i64 %2
  %5 = load i64, ptr %4, align 8
  %6 = getelementptr inbounds i64, ptr %1, i64 %2
  %7 = load i64, ptr %6, align 8
  %8 = add i64 %7, %5
  ret i64 %8
}

define signext i32 @load_i8_zext_index(ptr %0, ptr %1, i32 %2) {
; NOFUSION-LABEL: load_i8_zext_index:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    add.uw a1, a2, a1
; NOFUSION-NEXT:    add.uw a0, a2, a0
; NOFUSION-NEXT:    lbu a1, 0(a1)
; NOFUSION-NEXT:    lbu a0, 0(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i8_zext_index:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    add.uw a1, a2, a1
; FUSEADD-NEXT:    add.uw a0, a2, a0
; FUSEADD-NEXT:    lbu a1, 0(a1)
; FUSEADD-NEXT:    lbu a0, 0(a0)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i8_zext_index:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    add.uw a1, a2, a1
; FUSEZBA-NEXT:    lbu a1, 0(a1)
; FUSEZBA-NEXT:    add.uw a0, a2, a0
; FUSEZBA-NEXT:    lbu a0, 0(a0)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    ret
  %4 = zext i32 %2 to i64
  %5 = getelementptr inbounds i8, ptr %0, i64 %4
  %6 = load i8, ptr %5, align 1
  %7 = zext i8 %6 to i32
  %8 = getelementptr inbounds i8, ptr %1, i64 %4
  %9 = load i8, ptr %8, align 1
  %10 = zext i8 %9 to i32
  %11 = add i32 %10, %7
  ret i32 %11
}

define signext i32 @load_i16_zext_index(ptr %0, ptr %1, i32 %2) {
; NOFUSION-LABEL: load_i16_zext_index:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sh1add.uw a1, a2, a1
; NOFUSION-NEXT:    sh1add.uw a0, a2, a0
; NOFUSION-NEXT:    lhu a1, 0(a1)
; NOFUSION-NEXT:    lhu a0, 0(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i16_zext_index:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    sh1add.uw a1, a2, a1
; FUSEADD-NEXT:    sh1add.uw a0, a2, a0
; FUSEADD-NEXT:    lhu a1, 0(a1)
; FUSEADD-NEXT:    lhu a0, 0(a0)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i16_zext_index:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    sh1add.uw a1, a2, a1
; FUSEZBA-NEXT:    lhu a1, 0(a1)
; FUSEZBA-NEXT:    sh1add.uw a0, a2, a0
; FUSEZBA-NEXT:    lhu a0, 0(a0)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    ret
  %4 = zext i32 %2 to i64
  %5 = getelementptr inbounds i16, ptr %0, i64 %4
  %6 = load i16, ptr %5, align 2
  %7 = zext i16 %6 to i32
  %8 = getelementptr inbounds i16, ptr %1, i64 %4
  %9 = load i16, ptr %8, align 2
  %10 = zext i16 %9 to i32
  %11 = add i32 %10, %7
  ret i32 %11
}

define i64 @load_i32_zext_index(ptr %0, ptr %1, i32 %2) {
; NOFUSION-LABEL: load_i32_zext_index:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    sh2add.uw a1, a2, a1
; NOFUSION-NEXT:    sh2add.uw a0, a2, a0
; NOFUSION-NEXT:    lwu a1, 0(a1)
; NOFUSION-NEXT:    lwu a0, 0(a0)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i32_zext_index:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    sh2add.uw a1, a2, a1
; FUSEADD-NEXT:    sh2add.uw a0, a2, a0
; FUSEADD-NEXT:    lwu a1, 0(a1)
; FUSEADD-NEXT:    lwu a0, 0(a0)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i32_zext_index:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    sh2add.uw a1, a2, a1
; FUSEZBA-NEXT:    lwu a1, 0(a1)
; FUSEZBA-NEXT:    sh2add.uw a0, a2, a0
; FUSEZBA-NEXT:    lwu a0, 0(a0)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    ret
  %4 = zext i32 %2 to i64
  %5 = getelementptr inbounds i32, ptr %0, i64 %4
  %6 = load i32, ptr %5, align 4
  %7 = zext i32 %6 to i64
  %8 = getelementptr inbounds i32, ptr %1, i64 %4
  %9 = load i32, ptr %8, align 4
  %10 = zext i32 %9 to i64
  %11 = add i64 %10, %7
  ret i64 %11
}

define i64 @load_i64_zext_index(ptr %0, ptr %1, i32 %2) {
; NOFUSION-LABEL: load_i64_zext_index:
; NOFUSION:       # %bb.0:
; NOFUSION-NEXT:    slli a2, a2, 3
; NOFUSION-NEXT:    srli a2, a2, 3
; NOFUSION-NEXT:    sh3add.uw a0, a2, a0
; NOFUSION-NEXT:    sh3add.uw a1, a2, a1
; NOFUSION-NEXT:    ld a0, 0(a0)
; NOFUSION-NEXT:    ld a1, 0(a1)
; NOFUSION-NEXT:    add a0, a0, a1
; NOFUSION-NEXT:    ret
;
; FUSEADD-LABEL: load_i64_zext_index:
; FUSEADD:       # %bb.0:
; FUSEADD-NEXT:    slli a2, a2, 3
; FUSEADD-NEXT:    srli a2, a2, 3
; FUSEADD-NEXT:    sh3add.uw a0, a2, a0
; FUSEADD-NEXT:    sh3add.uw a1, a2, a1
; FUSEADD-NEXT:    ld a0, 0(a0)
; FUSEADD-NEXT:    ld a1, 0(a1)
; FUSEADD-NEXT:    add a0, a0, a1
; FUSEADD-NEXT:    ret
;
; FUSEZBA-LABEL: load_i64_zext_index:
; FUSEZBA:       # %bb.0:
; FUSEZBA-NEXT:    slli a2, a2, 3
; FUSEZBA-NEXT:    srli a2, a2, 3
; FUSEZBA-NEXT:    sh3add.uw a0, a2, a0
; FUSEZBA-NEXT:    ld a0, 0(a0)
; FUSEZBA-NEXT:    sh3add.uw a1, a2, a1
; FUSEZBA-NEXT:    ld a1, 0(a1)
; FUSEZBA-NEXT:    add a0, a0, a1
; FUSEZBA-NEXT:    ret
  %4 = zext i32 %2 to i64
  %5 = getelementptr inbounds i64, ptr %0, i64 %4
  %6 = load i64, ptr %5, align 8
  %7 = getelementptr inbounds i64, ptr %1, i64 %4
  %8 = load i64, ptr %7, align 8
  %9 = add i64 %8, %6
  ret i64 %9
}
