; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+d,+zfh \
; RUN:   -target-abi=lp64d -riscv-enable-machine-combiner -mcpu=sifive-u74 \
; RUN:   -O3 -machine-combiner-verify-pattern-order=true \
; RUN:   | FileCheck %s --check-prefixes=CHECK,U74
; RUN: llc < %s -mtriple=riscv64 -mattr=+d,+zfh \
; RUN:   -target-abi=lp64d -riscv-enable-machine-combiner -mcpu=sifive-p550 \
; RUN:   -O3 -machine-combiner-verify-pattern-order=true \
; RUN:   | FileCheck %s --check-prefixes=CHECK,P550

; Incremental updates of the instruction depths should be enough for this test
; case.
; RUN: llc < %s -mtriple=riscv64 -mattr=+d,+zfh \
; RUN:   -target-abi=lp64d -riscv-enable-machine-combiner -mcpu=sifive-u74 \
; RUN:   -machine-combiner-verify-pattern-order=true \
; RUN:   -O3 -machine-combiner-inc-threshold=0 \
; RUN:   | FileCheck %s --check-prefixes=CHECK,U74
; RUN: llc < %s -mtriple=riscv64 -mattr=+d,+zfh \
; RUN:   -target-abi=lp64d -riscv-enable-machine-combiner -mcpu=sifive-p550 \
; RUN:   -machine-combiner-verify-pattern-order=true \
; RUN:   -O3 -machine-combiner-inc-threshold=0 \
; RUN: | FileCheck %s --check-prefixes=CHECK,P550

; Verify that the first two adds are independent regardless of how the inputs are
; commuted. The destination registers are used as source registers for the third add.

define float @reassociate_adds1(float %x0, float %x1, float %x2, float %x3) {
; U74-LABEL: reassociate_adds1:
; U74:       # %bb.0:
; U74-NEXT:    fadd.s fa5, fa2, fa3
; U74-NEXT:    fadd.s fa4, fa0, fa1
; U74-NEXT:    fadd.s fa0, fa4, fa5
; U74-NEXT:    ret
;
; P550-LABEL: reassociate_adds1:
; P550:       # %bb.0:
; P550-NEXT:    fadd.s fa5, fa0, fa1
; P550-NEXT:    fadd.s fa4, fa2, fa3
; P550-NEXT:    fadd.s fa0, fa5, fa4
; P550-NEXT:    ret
  %t0 = fadd reassoc nsz float %x0, %x1
  %t1 = fadd reassoc nsz float %t0, %x2
  %t2 = fadd reassoc nsz float %t1, %x3
  ret float %t2
}

define float @reassociate_adds2(float %x0, float %x1, float %x2, float %x3) {
; U74-LABEL: reassociate_adds2:
; U74:       # %bb.0:
; U74-NEXT:    fadd.s fa5, fa2, fa3
; U74-NEXT:    fadd.s fa4, fa0, fa1
; U74-NEXT:    fadd.s fa0, fa5, fa4
; U74-NEXT:    ret
;
; P550-LABEL: reassociate_adds2:
; P550:       # %bb.0:
; P550-NEXT:    fadd.s fa5, fa0, fa1
; P550-NEXT:    fadd.s fa4, fa2, fa3
; P550-NEXT:    fadd.s fa0, fa4, fa5
; P550-NEXT:    ret
  %t0 = fadd reassoc nsz float %x0, %x1
  %t1 = fadd reassoc nsz float %x2, %t0
  %t2 = fadd reassoc nsz float %t1, %x3
  ret float %t2
}

define float @reassociate_adds3(float %x0, float %x1, float %x2, float %x3) {
; U74-LABEL: reassociate_adds3:
; U74:       # %bb.0:
; U74-NEXT:    fadd.s fa5, fa3, fa2
; U74-NEXT:    fadd.s fa4, fa0, fa1
; U74-NEXT:    fadd.s fa0, fa5, fa4
; U74-NEXT:    ret
;
; P550-LABEL: reassociate_adds3:
; P550:       # %bb.0:
; P550-NEXT:    fadd.s fa5, fa0, fa1
; P550-NEXT:    fadd.s fa4, fa3, fa2
; P550-NEXT:    fadd.s fa0, fa4, fa5
; P550-NEXT:    ret
  %t0 = fadd reassoc nsz float %x0, %x1
  %t1 = fadd reassoc nsz float %t0, %x2
  %t2 = fadd reassoc nsz float %x3, %t1
  ret float %t2
}

define float @reassociate_adds4(float %x0, float %x1, float %x2, float %x3) {
; U74-LABEL: reassociate_adds4:
; U74:       # %bb.0:
; U74-NEXT:    fadd.s fa5, fa3, fa2
; U74-NEXT:    fadd.s fa4, fa0, fa1
; U74-NEXT:    fadd.s fa0, fa5, fa4
; U74-NEXT:    ret
;
; P550-LABEL: reassociate_adds4:
; P550:       # %bb.0:
; P550-NEXT:    fadd.s fa5, fa0, fa1
; P550-NEXT:    fadd.s fa4, fa3, fa2
; P550-NEXT:    fadd.s fa0, fa4, fa5
; P550-NEXT:    ret
  %t0 = fadd reassoc nsz float %x0, %x1
  %t1 = fadd reassoc nsz float %x2, %t0
  %t2 = fadd reassoc nsz float %x3, %t1
  ret float %t2
}

; Verify that we reassociate some of these ops. The optimal balanced tree of adds is not
; produced because that would cost more compile time.

define float @reassociate_adds5(float %x0, float %x1, float %x2, float %x3, float %x4, float %x5, float %x6, float %x7) {
; U74-LABEL: reassociate_adds5:
; U74:       # %bb.0:
; U74-NEXT:    fadd.s fa5, fa4, fa5
; U74-NEXT:    fadd.s fa4, fa2, fa3
; U74-NEXT:    fadd.s fa3, fa0, fa1
; U74-NEXT:    fadd.s fa5, fa5, fa6
; U74-NEXT:    fadd.s fa4, fa3, fa4
; U74-NEXT:    fadd.s fa5, fa4, fa5
; U74-NEXT:    fadd.s fa0, fa5, fa7
; U74-NEXT:    ret
;
; P550-LABEL: reassociate_adds5:
; P550:       # %bb.0:
; P550-NEXT:    fadd.s fa1, fa0, fa1
; P550-NEXT:    fadd.s fa3, fa2, fa3
; P550-NEXT:    fadd.s fa5, fa4, fa5
; P550-NEXT:    fadd.s fa3, fa1, fa3
; P550-NEXT:    fadd.s fa5, fa5, fa6
; P550-NEXT:    fadd.s fa5, fa3, fa5
; P550-NEXT:    fadd.s fa0, fa5, fa7
; P550-NEXT:    ret
  %t0 = fadd reassoc nsz float %x0, %x1
  %t1 = fadd reassoc nsz float %t0, %x2
  %t2 = fadd reassoc nsz float %t1, %x3
  %t3 = fadd reassoc nsz float %t2, %x4
  %t4 = fadd reassoc nsz float %t3, %x5
  %t5 = fadd reassoc nsz float %t4, %x6
  %t6 = fadd reassoc nsz float %t5, %x7
  ret float %t6
}

; Verify that we only need two associative operations to reassociate the operands.
; Also, we should reassociate such that the result of the high latency division
; is used by the final 'add' rather than reassociating the %x3 operand with the
; division. The latter reassociation would not improve anything.

define float @reassociate_adds6(float %x0, float %x1, float %x2, float %x3) {
; CHECK-LABEL: reassociate_adds6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fdiv.s fa5, fa0, fa1
; CHECK-NEXT:    fadd.s fa4, fa3, fa2
; CHECK-NEXT:    fadd.s fa0, fa4, fa5
; CHECK-NEXT:    ret
  %t0 = fdiv reassoc nsz float %x0, %x1
  %t1 = fadd reassoc nsz float %x2, %t0
  %t2 = fadd reassoc nsz float %x3, %t1
  ret float %t2
}

; Verify that scalar single-precision multiplies are reassociated.

define float @reassociate_muls1(float %x0, float %x1, float %x2, float %x3) {
; CHECK-LABEL: reassociate_muls1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fdiv.s fa5, fa0, fa1
; CHECK-NEXT:    fmul.s fa4, fa3, fa2
; CHECK-NEXT:    fmul.s fa0, fa4, fa5
; CHECK-NEXT:    ret
  %t0 = fdiv reassoc nsz float %x0, %x1
  %t1 = fmul reassoc nsz float %x2, %t0
  %t2 = fmul reassoc nsz float %x3, %t1
  ret float %t2
}

; Verify that scalar double-precision adds are reassociated.

define double @reassociate_adds_double(double %x0, double %x1, double %x2, double %x3) {
; CHECK-LABEL: reassociate_adds_double:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fdiv.d fa5, fa0, fa1
; CHECK-NEXT:    fadd.d fa5, fa2, fa5
; CHECK-NEXT:    fadd.d fa0, fa3, fa5
; CHECK-NEXT:    ret
  %t0 = fdiv double %x0, %x1
  %t1 = fadd double %x2, %t0
  %t2 = fadd double %x3, %t1
  ret double %t2
}

; Verify that scalar double-precision multiplies are reassociated.

define double @reassociate_muls_double(double %x0, double %x1, double %x2, double %x3) {
; CHECK-LABEL: reassociate_muls_double:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fdiv.d fa5, fa0, fa1
; CHECK-NEXT:    fmul.d fa5, fa2, fa5
; CHECK-NEXT:    fmul.d fa0, fa3, fa5
; CHECK-NEXT:    ret
  %t0 = fdiv double %x0, %x1
  %t1 = fmul double %x2, %t0
  %t2 = fmul double %x3, %t1
  ret double %t2
}

; Verify that scalar half-precision adds are reassociated.

define half @reassociate_adds_half(half %x0, half %x1, half %x2, half %x3) {
; CHECK-LABEL: reassociate_adds_half:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fdiv.h fa5, fa0, fa1
; CHECK-NEXT:    fadd.h fa5, fa2, fa5
; CHECK-NEXT:    fadd.h fa0, fa3, fa5
; CHECK-NEXT:    ret
  %t0 = fdiv half %x0, %x1
  %t1 = fadd half %x2, %t0
  %t2 = fadd half %x3, %t1
  ret half %t2
}

; Verify that scalar half-precision multiplies are reassociated.

define half @reassociate_muls_half(half %x0, half %x1, half %x2, half %x3) {
; CHECK-LABEL: reassociate_muls_half:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fdiv.h fa5, fa0, fa1
; CHECK-NEXT:    fmul.h fa5, fa2, fa5
; CHECK-NEXT:    fmul.h fa0, fa3, fa5
; CHECK-NEXT:    ret
  %t0 = fdiv half %x0, %x1
  %t1 = fmul half %x2, %t0
  %t2 = fmul half %x3, %t1
  ret half %t2
}
