; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+zbb | FileCheck %s

declare i32 @llvm.bswap.i32(i32)
declare i32 @llvm.fshr.i32(i32, i32, i32)

; We want the srli a0, a0, 32 to be the only user of the rev8. This means the
; later srli with 3 should use the output of the srli 32 instead of being
; combined into an srli with 35.
define i32 @test(i32 %x) {
; CHECK-LABEL: test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    rev8 a0, a0
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    roriw a1, a0, 7
; CHECK-NEXT:    roriw a2, a0, 18
; CHECK-NEXT:    srli a3, a0, 3
; CHECK-NEXT:    xor a1, a1, a2
; CHECK-NEXT:    xor a1, a1, a3
; CHECK-NEXT:    add a1, a1, a0
; CHECK-NEXT:    mulw a0, a1, a0
; CHECK-NEXT:    ret
  %a = call i32 @llvm.bswap.i32(i32 %x)
  %b = call i32 @llvm.fshr.i32(i32 %a, i32 %a, i32 7)
  %c = call i32 @llvm.fshr.i32(i32 %a, i32 %a, i32 18)
  %d = lshr i32 %a, 3
  %e = xor i32 %b, %c
  %f = xor i32 %e, %d
  %g = add i32 %f, %a
  %h = mul i32 %g, %a
  ret i32 %h
}
