; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=riscv64 -mcpu=sifive-x280n -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK

define <vscale x 1 x float> @splat_vector() {
; CHECK-LABEL: splat_vector:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    vsetvli a1, zero, e32, mf2, ta, ma
; CHECK-NEXT:    addi a0, a0, %lo(.LCPI0_0)
; CHECK-NEXT:    vlse32.v v8, (a0), zero
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 1 x float> poison, float 1.0, i32 0
  %splat = shufflevector <vscale x 1 x float> %head, <vscale x 1 x float> poison, <vscale x 1 x i32> zeroinitializer
  ret <vscale x 1 x float> %splat
}

declare <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32(
  <vscale x 1 x float>,
  float,
  i64);

define <vscale x 1 x float> @riscv.vfmv.v.f(i64 %0) {
; CHECK-LABEL: riscv.vfmv.v.f:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI1_0)
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI1_0)
; CHECK-NEXT:    vlse32.v v8, (a1), zero
; CHECK-NEXT:    ret
  %splat = call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32(
    <vscale x 1 x float> undef,
    float 1.0,
    i64 %0)
  ret <vscale x 1 x float> %splat
}
