; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-zihintntl,+f,+d,+zfh,+c < %s | FileCheck %s -check-prefix=CHECK-RV64
; RUN: llc -mtriple=riscv32 -mattr=+experimental-zihintntl,+f,+d,+zfh,+c < %s | FileCheck %s -check-prefix=CHECK-RV32

define i64 @test_nontemporal_load_i64(i64* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 4(a0)
; CHECK-RV32-NEXT:    mv a0, a2
; CHECK-RV32-NEXT:    ret

  %1 = load i64, i64* %p, align 8, !nontemporal !0
  ret i64 %1
}

define i32 @test_nontemporal_load_i32(i32* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lw a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i32, i32* %p, align 8, !nontemporal !0
  ret i32 %1
}

define i16 @test_nontemporal_load_i16(i16* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lh a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lh a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i16, i16* %p, align 8, !nontemporal !0
  ret i16 %1
}

define i8 @test_nontemporal_load_i8(i8* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i8, i8* %p, align 8, !nontemporal !0
  ret i8 %1
}

define half @test_nontemporal_half(half *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    flh fa5, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    flh fa4, 6(a0)
; CHECK-RV64-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    flh fa5, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    flh fa4, 6(a0)
; CHECK-RV32-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV32-NEXT:    ret

  %1 = load half, half* %a, !nontemporal !0
  %2 = getelementptr half, half* %a, i32 3
  %3 = load half, half* %2, !nontemporal !0
; Use both loaded values in an FP op to ensure an flh is used, even for the
; soft half ABI
  %4 = fadd half %1, %3
  ret half %4
}

define float @test_nontemporal_load_float(float* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    flw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    flw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load float, float* %p, align 8, !nontemporal !0
  ret float %1
}

define double @test_nontemporal_load_double(double* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fld fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fld fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load double, double* %p, align 8, !nontemporal !0
  ret double %1
}

define dso_local i64 @test_nontemporal_load_unsigned_i8(i8 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_load_unsigned_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lbu a1, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_unsigned_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lbu a1, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i8, i8* %a, i32 4
  %2 = load i8, i8* %1, !nontemporal !0
  %3 = zext i8 %2 to i64
  %4 = load volatile i8, i8* %a, !nontemporal !0
  %5 = zext i8 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define dso_local i32 @test_nontemporal_load_unsigned_i16(i16 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_load_unsigned_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lhu a1, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lhu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_unsigned_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lhu a1, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lhu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i16, i16* %a, i32 5
  %2 = load i16, i16* %1, !nontemporal !0
  %3 = zext i16 %2 to i32
  %4 = load volatile i16, i16* %a, !nontemporal !0
  %5 = zext i16 %4 to i32
  %6 = add i32 %3, %5
  ret i32 %6
}

define dso_local i64 @test_nontemporal_load_unsigned_i32(i32 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_load_unsigned_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lwu a1, 24(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lwu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_unsigned_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 24(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i32, i32* %a, i32 6
  %2 = load i32, i32* %1, !nontemporal !0
  %3 = zext i32 %2 to i64
  %4 = load volatile i32, i32* %a, !nontemporal !0
  %5 = zext i32 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define <16 x i8> @test_nontemporal_load_v16i8(<16 x i8>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <16 x i8>, <16 x i8>* %p, align 16, !nontemporal !0
  ret <16 x i8> %1
}

define <8 x i16> @test_nontemporal_load_v8i16(<8 x i16>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <8 x i16>, <8 x i16>* %p, align 16, !nontemporal !0
  ret <8 x i16> %1
}

define <4 x i32> @test_nontemporal_load_v4i32(<4 x i32>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <4 x i32>, <4 x i32>* %p, align 16, !nontemporal !0
  ret <4 x i32> %1
}

define <2 x i64> @test_nontemporal_load_v2i64(<2 x i64>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_load_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 8(a0)
; CHECK-RV64-NEXT:    mv a0, a2
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_load_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <2 x i64>, <2 x i64>* %p, align 16, !nontemporal !0
  ret <2 x i64> %1
}

define void @test_nontemporal_store_i64(i64* %p, i64 %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i64 %v, i64* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_i32(i32* %p, i32 %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i32 %v, i32* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_i16(i16* %p, i16 %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i16 %v, i16* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_i8(i8* %p, i8 %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i8 %v, i8* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_half(half* %p, half %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fsh fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fsh fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store half %v, half* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_float(float* %p, float %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fsw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fsw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store float %v, float* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_double(double* %p, double %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fsd fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fsd fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store double %v, double* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_v16i8(<16 x i8>* %p, <16 x i8> %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    addi sp, sp, -16
; CHECK-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV64-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    .cfi_offset s0, -8
; CHECK-RV64-NEXT:    .cfi_offset s1, -16
; CHECK-RV64-NEXT:    lbu a6, 0(a1)
; CHECK-RV64-NEXT:    lbu a7, 8(a1)
; CHECK-RV64-NEXT:    lbu t0, 16(a1)
; CHECK-RV64-NEXT:    lbu t1, 24(a1)
; CHECK-RV64-NEXT:    lbu t2, 32(a1)
; CHECK-RV64-NEXT:    lbu t3, 40(a1)
; CHECK-RV64-NEXT:    lbu t4, 48(a1)
; CHECK-RV64-NEXT:    lbu t5, 56(a1)
; CHECK-RV64-NEXT:    lbu t6, 64(a1)
; CHECK-RV64-NEXT:    lbu a3, 72(a1)
; CHECK-RV64-NEXT:    lbu a4, 80(a1)
; CHECK-RV64-NEXT:    lbu a5, 88(a1)
; CHECK-RV64-NEXT:    lbu a2, 120(a1)
; CHECK-RV64-NEXT:    lbu s0, 112(a1)
; CHECK-RV64-NEXT:    lbu s1, 104(a1)
; CHECK-RV64-NEXT:    lbu a1, 96(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a2, 15(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb s0, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb s1, 13(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a1, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a5, 11(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a3, 9(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t6, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t5, 7(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t4, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t3, 5(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t2, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t1, 3(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t0, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a7, 1(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a6, 0(a0)
; CHECK-RV64-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    addi sp, sp, 16
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    addi sp, sp, -16
; CHECK-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    .cfi_offset s0, -4
; CHECK-RV32-NEXT:    .cfi_offset s1, -8
; CHECK-RV32-NEXT:    lbu a6, 0(a1)
; CHECK-RV32-NEXT:    lbu a7, 4(a1)
; CHECK-RV32-NEXT:    lbu t0, 8(a1)
; CHECK-RV32-NEXT:    lbu t1, 12(a1)
; CHECK-RV32-NEXT:    lbu t2, 16(a1)
; CHECK-RV32-NEXT:    lbu t3, 20(a1)
; CHECK-RV32-NEXT:    lbu t4, 24(a1)
; CHECK-RV32-NEXT:    lbu t5, 28(a1)
; CHECK-RV32-NEXT:    lbu t6, 32(a1)
; CHECK-RV32-NEXT:    lbu a3, 36(a1)
; CHECK-RV32-NEXT:    lbu a4, 40(a1)
; CHECK-RV32-NEXT:    lbu a5, 44(a1)
; CHECK-RV32-NEXT:    lbu a2, 60(a1)
; CHECK-RV32-NEXT:    lbu s0, 56(a1)
; CHECK-RV32-NEXT:    lbu s1, 52(a1)
; CHECK-RV32-NEXT:    lbu a1, 48(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a2, 15(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb s0, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb s1, 13(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a1, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a5, 11(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a3, 9(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t6, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t5, 7(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t4, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t3, 5(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t1, 3(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t0, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a7, 1(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a6, 0(a0)
; CHECK-RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    addi sp, sp, 16
; CHECK-RV32-NEXT:    ret

  store <16 x i8> %v, <16 x i8>* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_v8i16(<8 x i16>* %p, <8 x i16> %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lh a6, 0(a1)
; CHECK-RV64-NEXT:    lh a7, 8(a1)
; CHECK-RV64-NEXT:    lh t0, 16(a1)
; CHECK-RV64-NEXT:    lh a5, 24(a1)
; CHECK-RV64-NEXT:    lh a2, 56(a1)
; CHECK-RV64-NEXT:    lh a3, 48(a1)
; CHECK-RV64-NEXT:    lh a4, 40(a1)
; CHECK-RV64-NEXT:    lh a1, 32(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a2, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a3, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a1, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a5, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh t0, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a7, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a6, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lh a6, 0(a1)
; CHECK-RV32-NEXT:    lh a7, 4(a1)
; CHECK-RV32-NEXT:    lh t0, 8(a1)
; CHECK-RV32-NEXT:    lh a5, 12(a1)
; CHECK-RV32-NEXT:    lh a2, 28(a1)
; CHECK-RV32-NEXT:    lh a3, 24(a1)
; CHECK-RV32-NEXT:    lh a4, 20(a1)
; CHECK-RV32-NEXT:    lh a1, 16(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a2, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a3, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a1, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a5, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh t0, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a7, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a6, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <8 x i16> %v, <8 x i16>* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_v4i32(<4 x i32>* %p, <4 x i32> %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lw a2, 24(a1)
; CHECK-RV64-NEXT:    lw a3, 16(a1)
; CHECK-RV64-NEXT:    lw a4, 8(a1)
; CHECK-RV64-NEXT:    lw a1, 0(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a2, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a3, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a4, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <4 x i32> %v, <4 x i32>* %p, align 8, !nontemporal !0
  ret void
}

define void @test_nontemporal_store_v2i64(<2 x i64>* %p, <2 x i64> %v) {
; CHECK-RV64-LABEL: test_nontemporal_store_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_store_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <2 x i64> %v, <2 x i64>* %p, align 8, !nontemporal !0
  ret void
}

define i64 @test_nontemporal_P1_load_i64(i64* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a2, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a1, 4(a0)
; CHECK-RV32-NEXT:    mv a0, a2
; CHECK-RV32-NEXT:    ret

  %1 = load i64, i64* %p, align 8, !nontemporal !1
  ret i64 %1
}

define i32 @test_nontemporal_P1_load_i32(i32* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lw a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i32, i32* %p, align 8, !nontemporal !1
  ret i32 %1
}

define i16 @test_nontemporal_P1_load_i16(i16* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lh a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lh a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i16, i16* %p, align 8, !nontemporal !1
  ret i16 %1
}

define i8 @test_nontemporal_P1_load_i8(i8* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i8, i8* %p, align 8, !nontemporal !1
  ret i8 %1
}

define half @test_nontemporal_P1_half(half *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_P1_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    flh fa5, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    flh fa4, 6(a0)
; CHECK-RV64-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    flh fa5, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    flh fa4, 6(a0)
; CHECK-RV32-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV32-NEXT:    ret

  %1 = load half, half* %a, !nontemporal !1
  %2 = getelementptr half, half* %a, i32 3
  %3 = load half, half* %2, !nontemporal !1
; Use both loaded values in an FP op to ensure an flh is used, even for the
; soft half ABI
  %4 = fadd half %1, %3
  ret half %4
}

define float @test_nontemporal_P1_load_float(float* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    flw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    flw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load float, float* %p, align 8, !nontemporal !1
  ret float %1
}

define double @test_nontemporal_P1_load_double(double* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    fld fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    fld fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load double, double* %p, align 8, !nontemporal !1
  ret double %1
}

define dso_local i64 @test_nontemporal_P1_load_unsigned_i8(i8 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_unsigned_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lbu a1, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_unsigned_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lbu a1, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i8, i8* %a, i32 4
  %2 = load i8, i8* %1, !nontemporal !1
  %3 = zext i8 %2 to i64
  %4 = load volatile i8, i8* %a, !nontemporal !1
  %5 = zext i8 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define dso_local i32 @test_nontemporal_P1_load_unsigned_i16(i16 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_unsigned_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lhu a1, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lhu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_unsigned_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lhu a1, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lhu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i16, i16* %a, i32 5
  %2 = load i16, i16* %1, !nontemporal !1
  %3 = zext i16 %2 to i32
  %4 = load volatile i16, i16* %a, !nontemporal !1
  %5 = zext i16 %4 to i32
  %6 = add i32 %3, %5
  ret i32 %6
}

define dso_local i64 @test_nontemporal_P1_load_unsigned_i32(i32 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_unsigned_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lwu a1, 24(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    lwu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_unsigned_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a1, 24(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i32, i32* %a, i32 6
  %2 = load i32, i32* %1, !nontemporal !1
  %3 = zext i32 %2 to i64
  %4 = load volatile i32, i32* %a, !nontemporal !1
  %5 = zext i32 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define <16 x i8> @test_nontemporal_P1_load_v16i8(<16 x i8>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <16 x i8>, <16 x i8>* %p, align 16, !nontemporal !1
  ret <16 x i8> %1
}

define <8 x i16> @test_nontemporal_P1_load_v8i16(<8 x i16>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <8 x i16>, <8 x i16>* %p, align 16, !nontemporal !1
  ret <8 x i16> %1
}

define <4 x i32> @test_nontemporal_P1_load_v4i32(<4 x i32>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <4 x i32>, <4 x i32>* %p, align 16, !nontemporal !1
  ret <4 x i32> %1
}

define <2 x i64> @test_nontemporal_P1_load_v2i64(<2 x i64>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_P1_load_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a2, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    ld a1, 8(a0)
; CHECK-RV64-NEXT:    mv a0, a2
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_load_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <2 x i64>, <2 x i64>* %p, align 16, !nontemporal !1
  ret <2 x i64> %1
}

define void @test_nontemporal_P1_store_i64(i64* %p, i64 %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i64 %v, i64* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_i32(i32* %p, i32 %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i32 %v, i32* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_i16(i16* %p, i16 %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i16 %v, i16* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_i8(i8* %p, i8 %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i8 %v, i8* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_half(half* %p, half %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    fsh fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    fsh fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store half %v, half* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_float(float* %p, float %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    fsw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    fsw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store float %v, float* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_double(double* %p, double %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    fsd fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    fsd fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store double %v, double* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_v16i8(<16 x i8>* %p, <16 x i8> %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    addi sp, sp, -16
; CHECK-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV64-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    .cfi_offset s0, -8
; CHECK-RV64-NEXT:    .cfi_offset s1, -16
; CHECK-RV64-NEXT:    lbu a6, 0(a1)
; CHECK-RV64-NEXT:    lbu a7, 8(a1)
; CHECK-RV64-NEXT:    lbu t0, 16(a1)
; CHECK-RV64-NEXT:    lbu t1, 24(a1)
; CHECK-RV64-NEXT:    lbu t2, 32(a1)
; CHECK-RV64-NEXT:    lbu t3, 40(a1)
; CHECK-RV64-NEXT:    lbu t4, 48(a1)
; CHECK-RV64-NEXT:    lbu t5, 56(a1)
; CHECK-RV64-NEXT:    lbu t6, 64(a1)
; CHECK-RV64-NEXT:    lbu a3, 72(a1)
; CHECK-RV64-NEXT:    lbu a4, 80(a1)
; CHECK-RV64-NEXT:    lbu a5, 88(a1)
; CHECK-RV64-NEXT:    lbu a2, 120(a1)
; CHECK-RV64-NEXT:    lbu s0, 112(a1)
; CHECK-RV64-NEXT:    lbu s1, 104(a1)
; CHECK-RV64-NEXT:    lbu a1, 96(a1)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a2, 15(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb s0, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb s1, 13(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a1, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a5, 11(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a3, 9(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t6, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t5, 7(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t4, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t3, 5(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t2, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t1, 3(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb t0, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a7, 1(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sb a6, 0(a0)
; CHECK-RV64-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    addi sp, sp, 16
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    addi sp, sp, -16
; CHECK-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    .cfi_offset s0, -4
; CHECK-RV32-NEXT:    .cfi_offset s1, -8
; CHECK-RV32-NEXT:    lbu a6, 0(a1)
; CHECK-RV32-NEXT:    lbu a7, 4(a1)
; CHECK-RV32-NEXT:    lbu t0, 8(a1)
; CHECK-RV32-NEXT:    lbu t1, 12(a1)
; CHECK-RV32-NEXT:    lbu t2, 16(a1)
; CHECK-RV32-NEXT:    lbu t3, 20(a1)
; CHECK-RV32-NEXT:    lbu t4, 24(a1)
; CHECK-RV32-NEXT:    lbu t5, 28(a1)
; CHECK-RV32-NEXT:    lbu t6, 32(a1)
; CHECK-RV32-NEXT:    lbu a3, 36(a1)
; CHECK-RV32-NEXT:    lbu a4, 40(a1)
; CHECK-RV32-NEXT:    lbu a5, 44(a1)
; CHECK-RV32-NEXT:    lbu a2, 60(a1)
; CHECK-RV32-NEXT:    lbu s0, 56(a1)
; CHECK-RV32-NEXT:    lbu s1, 52(a1)
; CHECK-RV32-NEXT:    lbu a1, 48(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a2, 15(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb s0, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb s1, 13(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a1, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a5, 11(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a3, 9(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t6, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t5, 7(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t4, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t3, 5(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t1, 3(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb t0, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a7, 1(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sb a6, 0(a0)
; CHECK-RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    addi sp, sp, 16
; CHECK-RV32-NEXT:    ret

  store <16 x i8> %v, <16 x i8>* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_v8i16(<8 x i16>* %p, <8 x i16> %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lh a6, 0(a1)
; CHECK-RV64-NEXT:    lh a7, 8(a1)
; CHECK-RV64-NEXT:    lh t0, 16(a1)
; CHECK-RV64-NEXT:    lh a5, 24(a1)
; CHECK-RV64-NEXT:    lh a2, 56(a1)
; CHECK-RV64-NEXT:    lh a3, 48(a1)
; CHECK-RV64-NEXT:    lh a4, 40(a1)
; CHECK-RV64-NEXT:    lh a1, 32(a1)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a2, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a3, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a1, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a5, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh t0, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a7, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sh a6, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lh a6, 0(a1)
; CHECK-RV32-NEXT:    lh a7, 4(a1)
; CHECK-RV32-NEXT:    lh t0, 8(a1)
; CHECK-RV32-NEXT:    lh a5, 12(a1)
; CHECK-RV32-NEXT:    lh a2, 28(a1)
; CHECK-RV32-NEXT:    lh a3, 24(a1)
; CHECK-RV32-NEXT:    lh a4, 20(a1)
; CHECK-RV32-NEXT:    lh a1, 16(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a2, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a3, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a1, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a5, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh t0, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a7, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sh a6, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <8 x i16> %v, <8 x i16>* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_v4i32(<4 x i32>* %p, <4 x i32> %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lw a2, 24(a1)
; CHECK-RV64-NEXT:    lw a3, 16(a1)
; CHECK-RV64-NEXT:    lw a4, 8(a1)
; CHECK-RV64-NEXT:    lw a1, 0(a1)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sw a2, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sw a3, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sw a4, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <4 x i32> %v, <4 x i32>* %p, align 8, !nontemporal !1
  ret void
}

define void @test_nontemporal_P1_store_v2i64(<2 x i64>* %p, <2 x i64> %v) {
; CHECK-RV64-LABEL: test_nontemporal_P1_store_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.p1
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_P1_store_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.p1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <2 x i64> %v, <2 x i64>* %p, align 8, !nontemporal !1
  ret void
}

define i64 @test_nontemporal_PALL_load_i64(i64* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a2, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a1, 4(a0)
; CHECK-RV32-NEXT:    mv a0, a2
; CHECK-RV32-NEXT:    ret

  %1 = load i64, i64* %p, align 8, !nontemporal !2
  ret i64 %1
}

define i32 @test_nontemporal_PALL_load_i32(i32* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lw a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i32, i32* %p, align 8, !nontemporal !2
  ret i32 %1
}

define i16 @test_nontemporal_PALL_load_i16(i16* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lh a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lh a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i16, i16* %p, align 8, !nontemporal !2
  ret i16 %1
}

define i8 @test_nontemporal_PALL_load_i8(i8* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i8, i8* %p, align 8, !nontemporal !2
  ret i8 %1
}

define half @test_nontemporal_PALL_half(half *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_PALL_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    flh fa5, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    flh fa4, 6(a0)
; CHECK-RV64-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    flh fa5, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    flh fa4, 6(a0)
; CHECK-RV32-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV32-NEXT:    ret

  %1 = load half, half* %a, !nontemporal !2
  %2 = getelementptr half, half* %a, i32 3
  %3 = load half, half* %2, !nontemporal !2
; Use both loaded values in an FP op to ensure an flh is used, even for the
; soft half ABI
  %4 = fadd half %1, %3
  ret half %4
}

define float @test_nontemporal_PALL_load_float(float* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    flw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    flw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load float, float* %p, align 8, !nontemporal !2
  ret float %1
}

define double @test_nontemporal_PALL_load_double(double* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    fld fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    fld fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load double, double* %p, align 8, !nontemporal !2
  ret double %1
}

define dso_local i64 @test_nontemporal_PALL_load_unsigned_i8(i8 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_unsigned_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lbu a1, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_unsigned_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lbu a1, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i8, i8* %a, i32 4
  %2 = load i8, i8* %1, !nontemporal !2
  %3 = zext i8 %2 to i64
  %4 = load volatile i8, i8* %a, !nontemporal !2
  %5 = zext i8 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define dso_local i32 @test_nontemporal_PALL_load_unsigned_i16(i16 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_unsigned_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lhu a1, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lhu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_unsigned_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lhu a1, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lhu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i16, i16* %a, i32 5
  %2 = load i16, i16* %1, !nontemporal !2
  %3 = zext i16 %2 to i32
  %4 = load volatile i16, i16* %a, !nontemporal !2
  %5 = zext i16 %4 to i32
  %6 = add i32 %3, %5
  ret i32 %6
}

define dso_local i64 @test_nontemporal_PALL_load_unsigned_i32(i32 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_unsigned_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lwu a1, 24(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    lwu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_unsigned_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a1, 24(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i32, i32* %a, i32 6
  %2 = load i32, i32* %1, !nontemporal !2
  %3 = zext i32 %2 to i64
  %4 = load volatile i32, i32* %a, !nontemporal !2
  %5 = zext i32 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define <16 x i8> @test_nontemporal_PALL_load_v16i8(<16 x i8>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <16 x i8>, <16 x i8>* %p, align 16, !nontemporal !2
  ret <16 x i8> %1
}

define <8 x i16> @test_nontemporal_PALL_load_v8i16(<8 x i16>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <8 x i16>, <8 x i16>* %p, align 16, !nontemporal !2
  ret <8 x i16> %1
}

define <4 x i32> @test_nontemporal_PALL_load_v4i32(<4 x i32>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <4 x i32>, <4 x i32>* %p, align 16, !nontemporal !2
  ret <4 x i32> %1
}

define <2 x i64> @test_nontemporal_PALL_load_v2i64(<2 x i64>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_load_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a2, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    ld a1, 8(a0)
; CHECK-RV64-NEXT:    mv a0, a2
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_load_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <2 x i64>, <2 x i64>* %p, align 16, !nontemporal !2
  ret <2 x i64> %1
}

define void @test_nontemporal_PALL_store_i64(i64* %p, i64 %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i64 %v, i64* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_i32(i32* %p, i32 %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i32 %v, i32* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_i16(i16* %p, i16 %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i16 %v, i16* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_i8(i8* %p, i8 %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i8 %v, i8* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_half(half* %p, half %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    fsh fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    fsh fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store half %v, half* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_float(float* %p, float %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    fsw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    fsw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store float %v, float* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_double(double* %p, double %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    fsd fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    fsd fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store double %v, double* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_v16i8(<16 x i8>* %p, <16 x i8> %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    addi sp, sp, -16
; CHECK-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV64-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    .cfi_offset s0, -8
; CHECK-RV64-NEXT:    .cfi_offset s1, -16
; CHECK-RV64-NEXT:    lbu a6, 0(a1)
; CHECK-RV64-NEXT:    lbu a7, 8(a1)
; CHECK-RV64-NEXT:    lbu t0, 16(a1)
; CHECK-RV64-NEXT:    lbu t1, 24(a1)
; CHECK-RV64-NEXT:    lbu t2, 32(a1)
; CHECK-RV64-NEXT:    lbu t3, 40(a1)
; CHECK-RV64-NEXT:    lbu t4, 48(a1)
; CHECK-RV64-NEXT:    lbu t5, 56(a1)
; CHECK-RV64-NEXT:    lbu t6, 64(a1)
; CHECK-RV64-NEXT:    lbu a3, 72(a1)
; CHECK-RV64-NEXT:    lbu a4, 80(a1)
; CHECK-RV64-NEXT:    lbu a5, 88(a1)
; CHECK-RV64-NEXT:    lbu a2, 120(a1)
; CHECK-RV64-NEXT:    lbu s0, 112(a1)
; CHECK-RV64-NEXT:    lbu s1, 104(a1)
; CHECK-RV64-NEXT:    lbu a1, 96(a1)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a2, 15(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb s0, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb s1, 13(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a1, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a5, 11(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a3, 9(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t6, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t5, 7(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t4, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t3, 5(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t2, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t1, 3(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb t0, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a7, 1(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sb a6, 0(a0)
; CHECK-RV64-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    addi sp, sp, 16
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    addi sp, sp, -16
; CHECK-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    .cfi_offset s0, -4
; CHECK-RV32-NEXT:    .cfi_offset s1, -8
; CHECK-RV32-NEXT:    lbu a6, 0(a1)
; CHECK-RV32-NEXT:    lbu a7, 4(a1)
; CHECK-RV32-NEXT:    lbu t0, 8(a1)
; CHECK-RV32-NEXT:    lbu t1, 12(a1)
; CHECK-RV32-NEXT:    lbu t2, 16(a1)
; CHECK-RV32-NEXT:    lbu t3, 20(a1)
; CHECK-RV32-NEXT:    lbu t4, 24(a1)
; CHECK-RV32-NEXT:    lbu t5, 28(a1)
; CHECK-RV32-NEXT:    lbu t6, 32(a1)
; CHECK-RV32-NEXT:    lbu a3, 36(a1)
; CHECK-RV32-NEXT:    lbu a4, 40(a1)
; CHECK-RV32-NEXT:    lbu a5, 44(a1)
; CHECK-RV32-NEXT:    lbu a2, 60(a1)
; CHECK-RV32-NEXT:    lbu s0, 56(a1)
; CHECK-RV32-NEXT:    lbu s1, 52(a1)
; CHECK-RV32-NEXT:    lbu a1, 48(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a2, 15(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb s0, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb s1, 13(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a1, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a5, 11(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a3, 9(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t6, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t5, 7(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t4, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t3, 5(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t1, 3(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb t0, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a7, 1(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sb a6, 0(a0)
; CHECK-RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    addi sp, sp, 16
; CHECK-RV32-NEXT:    ret

  store <16 x i8> %v, <16 x i8>* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_v8i16(<8 x i16>* %p, <8 x i16> %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lh a6, 0(a1)
; CHECK-RV64-NEXT:    lh a7, 8(a1)
; CHECK-RV64-NEXT:    lh t0, 16(a1)
; CHECK-RV64-NEXT:    lh a5, 24(a1)
; CHECK-RV64-NEXT:    lh a2, 56(a1)
; CHECK-RV64-NEXT:    lh a3, 48(a1)
; CHECK-RV64-NEXT:    lh a4, 40(a1)
; CHECK-RV64-NEXT:    lh a1, 32(a1)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a2, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a3, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a1, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a5, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh t0, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a7, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sh a6, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lh a6, 0(a1)
; CHECK-RV32-NEXT:    lh a7, 4(a1)
; CHECK-RV32-NEXT:    lh t0, 8(a1)
; CHECK-RV32-NEXT:    lh a5, 12(a1)
; CHECK-RV32-NEXT:    lh a2, 28(a1)
; CHECK-RV32-NEXT:    lh a3, 24(a1)
; CHECK-RV32-NEXT:    lh a4, 20(a1)
; CHECK-RV32-NEXT:    lh a1, 16(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a2, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a3, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a1, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a5, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh t0, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a7, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sh a6, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <8 x i16> %v, <8 x i16>* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_v4i32(<4 x i32>* %p, <4 x i32> %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lw a2, 24(a1)
; CHECK-RV64-NEXT:    lw a3, 16(a1)
; CHECK-RV64-NEXT:    lw a4, 8(a1)
; CHECK-RV64-NEXT:    lw a1, 0(a1)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sw a2, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sw a3, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sw a4, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <4 x i32> %v, <4 x i32>* %p, align 8, !nontemporal !2
  ret void
}

define void @test_nontemporal_PALL_store_v2i64(<2 x i64>* %p, <2 x i64> %v) {
; CHECK-RV64-LABEL: test_nontemporal_PALL_store_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.pall
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_PALL_store_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.pall
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <2 x i64> %v, <2 x i64>* %p, align 8, !nontemporal !2
  ret void
}

define i64 @test_nontemporal_S1_load_i64(i64* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a2, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a1, 4(a0)
; CHECK-RV32-NEXT:    mv a0, a2
; CHECK-RV32-NEXT:    ret

  %1 = load i64, i64* %p, align 8, !nontemporal !3
  ret i64 %1
}

define i32 @test_nontemporal_S1_load_i32(i32* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lw a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i32, i32* %p, align 8, !nontemporal !3
  ret i32 %1
}

define i16 @test_nontemporal_S1_load_i16(i16* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lh a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lh a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i16, i16* %p, align 8, !nontemporal !3
  ret i16 %1
}

define i8 @test_nontemporal_S1_load_i8(i8* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i8, i8* %p, align 8, !nontemporal !3
  ret i8 %1
}

define half @test_nontemporal_S1_half(half *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_S1_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    flh fa5, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    flh fa4, 6(a0)
; CHECK-RV64-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    flh fa5, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    flh fa4, 6(a0)
; CHECK-RV32-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV32-NEXT:    ret

  %1 = load half, half* %a, !nontemporal !3
  %2 = getelementptr half, half* %a, i32 3
  %3 = load half, half* %2, !nontemporal !3
; Use both loaded values in an FP op to ensure an flh is used, even for the
; soft half ABI
  %4 = fadd half %1, %3
  ret half %4
}

define float @test_nontemporal_S1_load_float(float* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    flw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    flw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load float, float* %p, align 8, !nontemporal !3
  ret float %1
}

define double @test_nontemporal_S1_load_double(double* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    fld fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    fld fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load double, double* %p, align 8, !nontemporal !3
  ret double %1
}

define dso_local i64 @test_nontemporal_S1_load_unsigned_i8(i8 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_unsigned_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lbu a1, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_unsigned_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lbu a1, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i8, i8* %a, i32 4
  %2 = load i8, i8* %1, !nontemporal !3
  %3 = zext i8 %2 to i64
  %4 = load volatile i8, i8* %a, !nontemporal !3
  %5 = zext i8 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define dso_local i32 @test_nontemporal_S1_load_unsigned_i16(i16 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_unsigned_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lhu a1, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lhu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_unsigned_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lhu a1, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lhu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i16, i16* %a, i32 5
  %2 = load i16, i16* %1, !nontemporal !3
  %3 = zext i16 %2 to i32
  %4 = load volatile i16, i16* %a, !nontemporal !3
  %5 = zext i16 %4 to i32
  %6 = add i32 %3, %5
  ret i32 %6
}

define dso_local i64 @test_nontemporal_S1_load_unsigned_i32(i32 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_unsigned_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lwu a1, 24(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    lwu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_unsigned_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a1, 24(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i32, i32* %a, i32 6
  %2 = load i32, i32* %1, !nontemporal !3
  %3 = zext i32 %2 to i64
  %4 = load volatile i32, i32* %a, !nontemporal !3
  %5 = zext i32 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define <16 x i8> @test_nontemporal_S1_load_v16i8(<16 x i8>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <16 x i8>, <16 x i8>* %p, align 16, !nontemporal !3
  ret <16 x i8> %1
}

define <8 x i16> @test_nontemporal_S1_load_v8i16(<8 x i16>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <8 x i16>, <8 x i16>* %p, align 16, !nontemporal !3
  ret <8 x i16> %1
}

define <4 x i32> @test_nontemporal_S1_load_v4i32(<4 x i32>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <4 x i32>, <4 x i32>* %p, align 16, !nontemporal !3
  ret <4 x i32> %1
}

define <2 x i64> @test_nontemporal_S1_load_v2i64(<2 x i64>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_S1_load_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a2, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    ld a1, 8(a0)
; CHECK-RV64-NEXT:    mv a0, a2
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_load_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <2 x i64>, <2 x i64>* %p, align 16, !nontemporal !3
  ret <2 x i64> %1
}

define void @test_nontemporal_S1_store_i64(i64* %p, i64 %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i64 %v, i64* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_i32(i32* %p, i32 %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i32 %v, i32* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_i16(i16* %p, i16 %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i16 %v, i16* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_i8(i8* %p, i8 %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i8 %v, i8* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_half(half* %p, half %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    fsh fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    fsh fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store half %v, half* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_float(float* %p, float %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    fsw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    fsw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store float %v, float* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_double(double* %p, double %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    fsd fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    fsd fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store double %v, double* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_v16i8(<16 x i8>* %p, <16 x i8> %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    addi sp, sp, -16
; CHECK-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV64-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    .cfi_offset s0, -8
; CHECK-RV64-NEXT:    .cfi_offset s1, -16
; CHECK-RV64-NEXT:    lbu a6, 0(a1)
; CHECK-RV64-NEXT:    lbu a7, 8(a1)
; CHECK-RV64-NEXT:    lbu t0, 16(a1)
; CHECK-RV64-NEXT:    lbu t1, 24(a1)
; CHECK-RV64-NEXT:    lbu t2, 32(a1)
; CHECK-RV64-NEXT:    lbu t3, 40(a1)
; CHECK-RV64-NEXT:    lbu t4, 48(a1)
; CHECK-RV64-NEXT:    lbu t5, 56(a1)
; CHECK-RV64-NEXT:    lbu t6, 64(a1)
; CHECK-RV64-NEXT:    lbu a3, 72(a1)
; CHECK-RV64-NEXT:    lbu a4, 80(a1)
; CHECK-RV64-NEXT:    lbu a5, 88(a1)
; CHECK-RV64-NEXT:    lbu a2, 120(a1)
; CHECK-RV64-NEXT:    lbu s0, 112(a1)
; CHECK-RV64-NEXT:    lbu s1, 104(a1)
; CHECK-RV64-NEXT:    lbu a1, 96(a1)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a2, 15(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb s0, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb s1, 13(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a1, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a5, 11(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a3, 9(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t6, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t5, 7(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t4, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t3, 5(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t2, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t1, 3(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb t0, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a7, 1(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sb a6, 0(a0)
; CHECK-RV64-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    addi sp, sp, 16
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    addi sp, sp, -16
; CHECK-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    .cfi_offset s0, -4
; CHECK-RV32-NEXT:    .cfi_offset s1, -8
; CHECK-RV32-NEXT:    lbu a6, 0(a1)
; CHECK-RV32-NEXT:    lbu a7, 4(a1)
; CHECK-RV32-NEXT:    lbu t0, 8(a1)
; CHECK-RV32-NEXT:    lbu t1, 12(a1)
; CHECK-RV32-NEXT:    lbu t2, 16(a1)
; CHECK-RV32-NEXT:    lbu t3, 20(a1)
; CHECK-RV32-NEXT:    lbu t4, 24(a1)
; CHECK-RV32-NEXT:    lbu t5, 28(a1)
; CHECK-RV32-NEXT:    lbu t6, 32(a1)
; CHECK-RV32-NEXT:    lbu a3, 36(a1)
; CHECK-RV32-NEXT:    lbu a4, 40(a1)
; CHECK-RV32-NEXT:    lbu a5, 44(a1)
; CHECK-RV32-NEXT:    lbu a2, 60(a1)
; CHECK-RV32-NEXT:    lbu s0, 56(a1)
; CHECK-RV32-NEXT:    lbu s1, 52(a1)
; CHECK-RV32-NEXT:    lbu a1, 48(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a2, 15(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb s0, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb s1, 13(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a1, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a5, 11(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a3, 9(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t6, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t5, 7(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t4, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t3, 5(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t1, 3(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb t0, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a7, 1(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sb a6, 0(a0)
; CHECK-RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    addi sp, sp, 16
; CHECK-RV32-NEXT:    ret

  store <16 x i8> %v, <16 x i8>* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_v8i16(<8 x i16>* %p, <8 x i16> %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lh a6, 0(a1)
; CHECK-RV64-NEXT:    lh a7, 8(a1)
; CHECK-RV64-NEXT:    lh t0, 16(a1)
; CHECK-RV64-NEXT:    lh a5, 24(a1)
; CHECK-RV64-NEXT:    lh a2, 56(a1)
; CHECK-RV64-NEXT:    lh a3, 48(a1)
; CHECK-RV64-NEXT:    lh a4, 40(a1)
; CHECK-RV64-NEXT:    lh a1, 32(a1)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a2, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a3, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a1, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a5, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh t0, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a7, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sh a6, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lh a6, 0(a1)
; CHECK-RV32-NEXT:    lh a7, 4(a1)
; CHECK-RV32-NEXT:    lh t0, 8(a1)
; CHECK-RV32-NEXT:    lh a5, 12(a1)
; CHECK-RV32-NEXT:    lh a2, 28(a1)
; CHECK-RV32-NEXT:    lh a3, 24(a1)
; CHECK-RV32-NEXT:    lh a4, 20(a1)
; CHECK-RV32-NEXT:    lh a1, 16(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a2, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a3, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a1, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a5, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh t0, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a7, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sh a6, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <8 x i16> %v, <8 x i16>* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_v4i32(<4 x i32>* %p, <4 x i32> %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lw a2, 24(a1)
; CHECK-RV64-NEXT:    lw a3, 16(a1)
; CHECK-RV64-NEXT:    lw a4, 8(a1)
; CHECK-RV64-NEXT:    lw a1, 0(a1)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sw a2, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sw a3, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sw a4, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <4 x i32> %v, <4 x i32>* %p, align 8, !nontemporal !3
  ret void
}

define void @test_nontemporal_S1_store_v2i64(<2 x i64>* %p, <2 x i64> %v) {
; CHECK-RV64-LABEL: test_nontemporal_S1_store_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.s1
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_S1_store_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.s1
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <2 x i64> %v, <2 x i64>* %p, align 8, !nontemporal !3
  ret void
}

define i64 @test_nontemporal_ALL_load_i64(i64* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 4(a0)
; CHECK-RV32-NEXT:    mv a0, a2
; CHECK-RV32-NEXT:    ret

  %1 = load i64, i64* %p, align 8, !nontemporal !4
  ret i64 %1
}

define i32 @test_nontemporal_ALL_load_i32(i32* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lw a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i32, i32* %p, align 8, !nontemporal !4
  ret i32 %1
}

define i16 @test_nontemporal_ALL_load_i16(i16* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lh a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lh a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i16, i16* %p, align 8, !nontemporal !4
  ret i16 %1
}

define i8 @test_nontemporal_ALL_load_i8(i8* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load i8, i8* %p, align 8, !nontemporal !4
  ret i8 %1
}

define half @test_nontemporal_ALL_half(half *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_ALL_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    flh fa5, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    flh fa4, 6(a0)
; CHECK-RV64-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    flh fa5, 0(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    flh fa4, 6(a0)
; CHECK-RV32-NEXT:    fadd.h fa0, fa5, fa4
; CHECK-RV32-NEXT:    ret

  %1 = load half, half* %a, !nontemporal !4
  %2 = getelementptr half, half* %a, i32 3
  %3 = load half, half* %2, !nontemporal !4
; Use both loaded values in an FP op to ensure an flh is used, even for the
; soft half ABI
  %4 = fadd half %1, %3
  ret half %4
}

define float @test_nontemporal_ALL_load_float(float* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    flw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    flw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load float, float* %p, align 8, !nontemporal !4
  ret float %1
}

define double @test_nontemporal_ALL_load_double(double* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fld fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fld fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load double, double* %p, align 8, !nontemporal !4
  ret double %1
}

define dso_local i64 @test_nontemporal_ALL_load_unsigned_i8(i8 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_unsigned_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lbu a1, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lbu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_unsigned_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lbu a1, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lbu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i8, i8* %a, i32 4
  %2 = load i8, i8* %1, !nontemporal !4
  %3 = zext i8 %2 to i64
  %4 = load volatile i8, i8* %a, !nontemporal !4
  %5 = zext i8 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define dso_local i32 @test_nontemporal_ALL_load_unsigned_i16(i16 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_unsigned_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lhu a1, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lhu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_unsigned_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lhu a1, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lhu a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i16, i16* %a, i32 5
  %2 = load i16, i16* %1, !nontemporal !4
  %3 = zext i16 %2 to i32
  %4 = load volatile i16, i16* %a, !nontemporal !4
  %5 = zext i16 %4 to i32
  %6 = add i32 %3, %5
  ret i32 %6
}

define dso_local i64 @test_nontemporal_ALL_load_unsigned_i32(i32 *%a) nounwind {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_unsigned_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lwu a1, 24(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    lwu a0, 0(a0)
; CHECK-RV64-NEXT:    add a0, a0, a1
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_unsigned_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 24(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a0, 0(a0)
; CHECK-RV32-NEXT:    add a0, a0, a1
; CHECK-RV32-NEXT:    sltu a1, a0, a1
; CHECK-RV32-NEXT:    ret

  %1 = getelementptr i32, i32* %a, i32 6
  %2 = load i32, i32* %1, !nontemporal !4
  %3 = zext i32 %2 to i64
  %4 = load volatile i32, i32* %a, !nontemporal !4
  %5 = zext i32 %4 to i64
  %6 = add i64 %3, %5
  ret i64 %6
}

define <16 x i8> @test_nontemporal_ALL_load_v16i8(<16 x i8>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <16 x i8>, <16 x i8>* %p, align 16, !nontemporal !4
  ret <16 x i8> %1
}

define <8 x i16> @test_nontemporal_ALL_load_v8i16(<8 x i16>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <8 x i16>, <8 x i16>* %p, align 16, !nontemporal !4
  ret <8 x i16> %1
}

define <4 x i32> @test_nontemporal_ALL_load_v4i32(<4 x i32>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 8(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 0(a1)
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <4 x i32>, <4 x i32>* %p, align 16, !nontemporal !4
  ret <4 x i32> %1
}

define <2 x i64> @test_nontemporal_ALL_load_v2i64(<2 x i64>* %p) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_load_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a2, 0(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    ld a1, 8(a0)
; CHECK-RV64-NEXT:    mv a0, a2
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_load_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  %1 = load <2 x i64>, <2 x i64>* %p, align 16, !nontemporal !4
  ret <2 x i64> %1
}

define void @test_nontemporal_ALL_store_i64(i64* %p, i64 %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i64 %v, i64* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_i32(i32* %p, i32 %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i32 %v, i32* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_i16(i16* %p, i16 %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i16 %v, i16* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_i8(i8* %p, i8 %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store i8 %v, i8* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_half(half* %p, half %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_half:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fsh fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_half:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fsh fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store half %v, half* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_float(float* %p, float %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_float:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fsw fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_float:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fsw fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store float %v, float* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_double(double* %p, double %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_double:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    fsd fa0, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_double:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    fsd fa0, 0(a0)
; CHECK-RV32-NEXT:    ret

  store double %v, double* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_v16i8(<16 x i8>* %p, <16 x i8> %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_v16i8:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    addi sp, sp, -16
; CHECK-RV64-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV64-NEXT:    sd s0, 8(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    sd s1, 0(sp) # 8-byte Folded Spill
; CHECK-RV64-NEXT:    .cfi_offset s0, -8
; CHECK-RV64-NEXT:    .cfi_offset s1, -16
; CHECK-RV64-NEXT:    lbu a6, 0(a1)
; CHECK-RV64-NEXT:    lbu a7, 8(a1)
; CHECK-RV64-NEXT:    lbu t0, 16(a1)
; CHECK-RV64-NEXT:    lbu t1, 24(a1)
; CHECK-RV64-NEXT:    lbu t2, 32(a1)
; CHECK-RV64-NEXT:    lbu t3, 40(a1)
; CHECK-RV64-NEXT:    lbu t4, 48(a1)
; CHECK-RV64-NEXT:    lbu t5, 56(a1)
; CHECK-RV64-NEXT:    lbu t6, 64(a1)
; CHECK-RV64-NEXT:    lbu a3, 72(a1)
; CHECK-RV64-NEXT:    lbu a4, 80(a1)
; CHECK-RV64-NEXT:    lbu a5, 88(a1)
; CHECK-RV64-NEXT:    lbu a2, 120(a1)
; CHECK-RV64-NEXT:    lbu s0, 112(a1)
; CHECK-RV64-NEXT:    lbu s1, 104(a1)
; CHECK-RV64-NEXT:    lbu a1, 96(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a2, 15(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb s0, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb s1, 13(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a1, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a5, 11(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a3, 9(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t6, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t5, 7(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t4, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t3, 5(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t2, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t1, 3(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb t0, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a7, 1(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sb a6, 0(a0)
; CHECK-RV64-NEXT:    ld s0, 8(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    ld s1, 0(sp) # 8-byte Folded Reload
; CHECK-RV64-NEXT:    addi sp, sp, 16
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_v16i8:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    addi sp, sp, -16
; CHECK-RV32-NEXT:    .cfi_def_cfa_offset 16
; CHECK-RV32-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    sw s1, 8(sp) # 4-byte Folded Spill
; CHECK-RV32-NEXT:    .cfi_offset s0, -4
; CHECK-RV32-NEXT:    .cfi_offset s1, -8
; CHECK-RV32-NEXT:    lbu a6, 0(a1)
; CHECK-RV32-NEXT:    lbu a7, 4(a1)
; CHECK-RV32-NEXT:    lbu t0, 8(a1)
; CHECK-RV32-NEXT:    lbu t1, 12(a1)
; CHECK-RV32-NEXT:    lbu t2, 16(a1)
; CHECK-RV32-NEXT:    lbu t3, 20(a1)
; CHECK-RV32-NEXT:    lbu t4, 24(a1)
; CHECK-RV32-NEXT:    lbu t5, 28(a1)
; CHECK-RV32-NEXT:    lbu t6, 32(a1)
; CHECK-RV32-NEXT:    lbu a3, 36(a1)
; CHECK-RV32-NEXT:    lbu a4, 40(a1)
; CHECK-RV32-NEXT:    lbu a5, 44(a1)
; CHECK-RV32-NEXT:    lbu a2, 60(a1)
; CHECK-RV32-NEXT:    lbu s0, 56(a1)
; CHECK-RV32-NEXT:    lbu s1, 52(a1)
; CHECK-RV32-NEXT:    lbu a1, 48(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a2, 15(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb s0, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb s1, 13(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a1, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a5, 11(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a3, 9(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t6, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t5, 7(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t4, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t3, 5(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t2, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t1, 3(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb t0, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a7, 1(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sb a6, 0(a0)
; CHECK-RV32-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    lw s1, 8(sp) # 4-byte Folded Reload
; CHECK-RV32-NEXT:    addi sp, sp, 16
; CHECK-RV32-NEXT:    ret

  store <16 x i8> %v, <16 x i8>* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_v8i16(<8 x i16>* %p, <8 x i16> %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_v8i16:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lh a6, 0(a1)
; CHECK-RV64-NEXT:    lh a7, 8(a1)
; CHECK-RV64-NEXT:    lh t0, 16(a1)
; CHECK-RV64-NEXT:    lh a5, 24(a1)
; CHECK-RV64-NEXT:    lh a2, 56(a1)
; CHECK-RV64-NEXT:    lh a3, 48(a1)
; CHECK-RV64-NEXT:    lh a4, 40(a1)
; CHECK-RV64-NEXT:    lh a1, 32(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a2, 14(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a3, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a4, 10(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a1, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a5, 6(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh t0, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a7, 2(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sh a6, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_v8i16:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lh a6, 0(a1)
; CHECK-RV32-NEXT:    lh a7, 4(a1)
; CHECK-RV32-NEXT:    lh t0, 8(a1)
; CHECK-RV32-NEXT:    lh a5, 12(a1)
; CHECK-RV32-NEXT:    lh a2, 28(a1)
; CHECK-RV32-NEXT:    lh a3, 24(a1)
; CHECK-RV32-NEXT:    lh a4, 20(a1)
; CHECK-RV32-NEXT:    lh a1, 16(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a2, 14(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a3, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a4, 10(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a1, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a5, 6(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh t0, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a7, 2(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sh a6, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <8 x i16> %v, <8 x i16>* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_v4i32(<4 x i32>* %p, <4 x i32> %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_v4i32:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    lw a2, 24(a1)
; CHECK-RV64-NEXT:    lw a3, 16(a1)
; CHECK-RV64-NEXT:    lw a4, 8(a1)
; CHECK-RV64-NEXT:    lw a1, 0(a1)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a2, 12(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a3, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a4, 4(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sw a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_v4i32:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <4 x i32> %v, <4 x i32>* %p, align 8, !nontemporal !4
  ret void
}

define void @test_nontemporal_ALL_store_v2i64(<2 x i64>* %p, <2 x i64> %v) {
; CHECK-RV64-LABEL: test_nontemporal_ALL_store_v2i64:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sd a2, 8(a0)
; CHECK-RV64-NEXT:    c.ntl.all
; CHECK-RV64-NEXT:    sd a1, 0(a0)
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: test_nontemporal_ALL_store_v2i64:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    lw a2, 12(a1)
; CHECK-RV32-NEXT:    lw a3, 8(a1)
; CHECK-RV32-NEXT:    lw a4, 4(a1)
; CHECK-RV32-NEXT:    lw a1, 0(a1)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a2, 12(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a3, 8(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a4, 4(a0)
; CHECK-RV32-NEXT:    c.ntl.all
; CHECK-RV32-NEXT:    sw a1, 0(a0)
; CHECK-RV32-NEXT:    ret

  store <2 x i64> %v, <2 x i64>* %p, align 8, !nontemporal !4
  ret void
}

!0 = !{i32 1}
!1 = !{i32 2}
!2 = !{i32 3}
!3 = !{i32 4}
!4 = !{i32 5}
