; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple riscv64 -mattr=+zbb < %s | FileCheck %s

; We should not have any zext.h instructions in this function.

declare void @bar(...)
define void @foo(ptr %sp) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lh a0, 0(a0)
; CHECK-NEXT:    blez a0, .LBB0_4
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    beq a0, a1, .LBB0_3
; CHECK-NEXT:  # %bb.2: # %if.then.else
; CHECK-NEXT:    li a1, 6
; CHECK-NEXT:    bne a0, a1, .LBB0_4
; CHECK-NEXT:  .LBB0_3: # %if.then.then
; CHECK-NEXT:    tail bar
; CHECK-NEXT:  .LBB0_4: # %if.end
; CHECK-NEXT:    ret
entry:
  %0 = load i16, ptr %sp, align 2
  %cmp = icmp sgt i16 %0, 0
  br i1 %cmp, label %if.then, label %if.end

if.then:
  %cmp2 = icmp eq i16 %0, 3
  br i1 %cmp2, label %if.then.then, label %if.then.else

if.then.else:
  %cmp3 = icmp eq i16 %0, 6
  br i1 %cmp3, label %if.then.then, label %if.end

if.then.then:
  tail call void @bar()
  ret void

if.end:
  ret void
}
