; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=NO_JUMP_IS_CHEAP %s
; RUN: llc -mtriple=riscv64 -mattr=+jump-is-cheap -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=JUMP_IS_CHEAP %s

@Variant = external global i32, align 4
@kingcap = external global i32, align 4
@fcaptures = external global i32, align 4
@captures = external global i32, align 4

define signext i32 @foo() {
; NO_JUMP_IS_CHEAP-LABEL: foo:
; NO_JUMP_IS_CHEAP:       # %bb.0: # %entry
; NO_JUMP_IS_CHEAP-NEXT:    lui a0, %hi(Variant)
; NO_JUMP_IS_CHEAP-NEXT:    lw a1, %lo(Variant)(a0)
; NO_JUMP_IS_CHEAP-NEXT:    lui a0, %hi(kingcap)
; NO_JUMP_IS_CHEAP-NEXT:    lw a0, %lo(kingcap)(a0)
; NO_JUMP_IS_CHEAP-NEXT:    addi a2, a1, -3
; NO_JUMP_IS_CHEAP-NEXT:    seqz a2, a2
; NO_JUMP_IS_CHEAP-NEXT:    snez a0, a0
; NO_JUMP_IS_CHEAP-NEXT:    or a2, a2, a0
; NO_JUMP_IS_CHEAP-NEXT:    li a0, 1
; NO_JUMP_IS_CHEAP-NEXT:    beqz a2, .LBB0_4
; NO_JUMP_IS_CHEAP-NEXT:  # %bb.1: # %lor.lhs.false
; NO_JUMP_IS_CHEAP-NEXT:    li a2, 3
; NO_JUMP_IS_CHEAP-NEXT:    bne a1, a2, .LBB0_3
; NO_JUMP_IS_CHEAP-NEXT:  # %bb.2: # %land.lhs.true2
; NO_JUMP_IS_CHEAP-NEXT:    lui a1, %hi(fcaptures)
; NO_JUMP_IS_CHEAP-NEXT:    lw a1, %lo(fcaptures)(a1)
; NO_JUMP_IS_CHEAP-NEXT:    lui a2, %hi(captures)
; NO_JUMP_IS_CHEAP-NEXT:    lw a2, %lo(captures)(a2)
; NO_JUMP_IS_CHEAP-NEXT:    beq a1, a2, .LBB0_4
; NO_JUMP_IS_CHEAP-NEXT:  .LBB0_3: # %if.end
; NO_JUMP_IS_CHEAP-NEXT:    li a0, 0
; NO_JUMP_IS_CHEAP-NEXT:  .LBB0_4: # %return
; NO_JUMP_IS_CHEAP-NEXT:    ret
;
; JUMP_IS_CHEAP-LABEL: foo:
; JUMP_IS_CHEAP:       # %bb.0: # %entry
; JUMP_IS_CHEAP-NEXT:    lui a0, %hi(Variant)
; JUMP_IS_CHEAP-NEXT:    lw a1, %lo(Variant)(a0)
; JUMP_IS_CHEAP-NEXT:    li a2, 3
; JUMP_IS_CHEAP-NEXT:    li a0, 1
; JUMP_IS_CHEAP-NEXT:    beq a1, a2, .LBB0_3
; JUMP_IS_CHEAP-NEXT:  # %bb.1: # %entry
; JUMP_IS_CHEAP-NEXT:    lui a3, %hi(kingcap)
; JUMP_IS_CHEAP-NEXT:    lw a3, %lo(kingcap)(a3)
; JUMP_IS_CHEAP-NEXT:    bnez a3, .LBB0_3
; JUMP_IS_CHEAP-NEXT:  .LBB0_2: # %return
; JUMP_IS_CHEAP-NEXT:    ret
; JUMP_IS_CHEAP-NEXT:  .LBB0_3: # %lor.lhs.false
; JUMP_IS_CHEAP-NEXT:    bne a1, a2, .LBB0_5
; JUMP_IS_CHEAP-NEXT:  # %bb.4: # %land.lhs.true2
; JUMP_IS_CHEAP-NEXT:    lui a1, %hi(fcaptures)
; JUMP_IS_CHEAP-NEXT:    lw a1, %lo(fcaptures)(a1)
; JUMP_IS_CHEAP-NEXT:    lui a2, %hi(captures)
; JUMP_IS_CHEAP-NEXT:    lw a2, %lo(captures)(a2)
; JUMP_IS_CHEAP-NEXT:    beq a1, a2, .LBB0_2
; JUMP_IS_CHEAP-NEXT:  .LBB0_5: # %if.end
; JUMP_IS_CHEAP-NEXT:    li a0, 0
; JUMP_IS_CHEAP-NEXT:    ret
entry:
  %0 = load i32, i32* @Variant, align 4
  %cmp = icmp eq i32 %0, 3
  %1 = load i32, i32* @kingcap, align 4
  %tobool = icmp ne i32 %1, 0
  %or.cond = select i1 %cmp, i1 true, i1 %tobool
  br i1 %or.cond, label %lor.lhs.false, label %return

lor.lhs.false:
  br i1 %cmp, label %land.lhs.true2, label %if.end

land.lhs.true2:
  %2 = load i32, i32* @fcaptures, align 4
  %3 = load i32, i32* @captures, align 4
  %cmp3 = icmp eq i32 %2, %3
  br i1 %cmp3, label %return, label %if.end

if.end:
  br label %return

return:
  %retval.0 = phi i32 [ 0, %if.end ], [ 1, %entry ], [ 1, %land.lhs.true2 ]
  ret i32 %retval.0
}
