; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -experimental-riscv-simplifycfg-hoist-vector=false -passes=simplifycfg -hoist-common-insts=true %s -S -mtriple=riscv64 -mattr=+d,+v | FileCheck %s --check-prefixes=CHECK-NO-HOIST
; RUN: opt -experimental-riscv-simplifycfg-hoist-vector=true -passes=simplifycfg -hoist-common-insts=true %s -S -mtriple=riscv64 -mattr=+d,+v | FileCheck %s --check-prefixes=CHECK-HOIST

target triple = "riscv64"

; Check that vector operations (vfmul) are not hoisted by simplifycfg
define float @test1(i64 %n, float* nocapture %x, i64 %incx, float* nocapture %y, i64 %incy) nounwind {
; CHECK-NO-HOIST-LABEL: @test1(
; CHECK-NO-HOIST-NEXT:  entry:
; CHECK-NO-HOIST-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[N:%.*]], i64 2, i64 3)
; CHECK-NO-HOIST-NEXT:    [[CMP_NOT24:%.*]] = icmp eq i64 [[TMP0]], 0
; CHECK-NO-HOIST-NEXT:    br i1 [[CMP_NOT24]], label [[FOR_END:%.*]], label [[FOR_BODY:%.*]]
; CHECK-NO-HOIST:       for.body:
; CHECK-NO-HOIST-NEXT:    [[TMP1:%.*]] = phi i64 [ [[TMP9:%.*]], [[IF_END:%.*]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
; CHECK-NO-HOIST-NEXT:    [[ACCV_028:%.*]] = phi <vscale x 16 x float> [ [[ACCV_1:%.*]], [[IF_END]] ], [ undef, [[ENTRY]] ]
; CHECK-NO-HOIST-NEXT:    [[X_ADDR_027:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[IF_END]] ], [ [[X:%.*]], [[ENTRY]] ]
; CHECK-NO-HOIST-NEXT:    [[Y_ADDR_026:%.*]] = phi ptr [ [[ADD_PTR3:%.*]], [[IF_END]] ], [ [[Y:%.*]], [[ENTRY]] ]
; CHECK-NO-HOIST-NEXT:    [[LEFT_025:%.*]] = phi i64 [ [[SUB:%.*]], [[IF_END]] ], [ [[N]], [[ENTRY]] ]
; CHECK-NO-HOIST-NEXT:    [[TMP2:%.*]] = bitcast ptr [[X_ADDR_027]] to ptr
; CHECK-NO-HOIST-NEXT:    [[TMP3:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.p0.i64(<vscale x 16 x float> undef, ptr [[TMP2]], i64 [[TMP1]])
; CHECK-NO-HOIST-NEXT:    [[TMP4:%.*]] = bitcast ptr [[Y_ADDR_026]] to ptr
; CHECK-NO-HOIST-NEXT:    [[TMP5:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.p0.i64(<vscale x 16 x float> undef, ptr [[TMP4]], i64 [[TMP1]])
; CHECK-NO-HOIST-NEXT:    [[CMP1:%.*]] = icmp ult i64 [[LEFT_025]], [[N]]
; CHECK-NO-HOIST-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK-NO-HOIST:       if.then:
; CHECK-NO-HOIST-NEXT:    [[TMP6:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vfmul.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> [[TMP3]], <vscale x 16 x float> [[TMP5]], i64 7, i64 [[TMP1]])
; CHECK-NO-HOIST-NEXT:    [[TMP7:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vfadd.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> [[ACCV_028]], <vscale x 16 x float> [[TMP6]], i64 7, i64 [[TMP1]])
; CHECK-NO-HOIST-NEXT:    br label [[IF_END]]
; CHECK-NO-HOIST:       if.else:
; CHECK-NO-HOIST-NEXT:    [[TMP8:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vfmul.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> [[TMP3]], <vscale x 16 x float> [[TMP5]], i64 7, i64 [[TMP1]])
; CHECK-NO-HOIST-NEXT:    br label [[IF_END]]
; CHECK-NO-HOIST:       if.end:
; CHECK-NO-HOIST-NEXT:    [[ACCV_1]] = phi <vscale x 16 x float> [ [[TMP7]], [[IF_THEN]] ], [ [[TMP8]], [[IF_ELSE]] ]
; CHECK-NO-HOIST-NEXT:    [[MUL:%.*]] = mul i64 [[TMP1]], [[INCX:%.*]]
; CHECK-NO-HOIST-NEXT:    [[ADD_PTR]] = getelementptr inbounds float, ptr [[X_ADDR_027]], i64 [[MUL]]
; CHECK-NO-HOIST-NEXT:    [[MUL2:%.*]] = mul i64 [[TMP1]], [[INCY:%.*]]
; CHECK-NO-HOIST-NEXT:    [[ADD_PTR3]] = getelementptr inbounds float, ptr [[Y_ADDR_026]], i64 [[MUL2]]
; CHECK-NO-HOIST-NEXT:    [[SUB]] = sub i64 [[LEFT_025]], [[TMP1]]
; CHECK-NO-HOIST-NEXT:    [[TMP9]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[SUB]], i64 2, i64 3)
; CHECK-NO-HOIST-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP9]], 0
; CHECK-NO-HOIST-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_BODY]]
; CHECK-NO-HOIST:       for.end:
; CHECK-NO-HOIST-NEXT:    [[ACCV_0_LCSSA:%.*]] = phi <vscale x 16 x float> [ undef, [[ENTRY]] ], [ [[ACCV_1]], [[IF_END]] ]
; CHECK-NO-HOIST-NEXT:    [[TMP10:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[N]], i64 2, i64 0)
; CHECK-NO-HOIST-NEXT:    [[TMP11:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmv.v.x.nxv2i32.i64(<vscale x 2 x i32> undef, i32 0, i64 [[TMP10]])
; CHECK-NO-HOIST-NEXT:    [[TMP12:%.*]] = bitcast <vscale x 2 x i32> [[TMP11]] to <vscale x 2 x float>
; CHECK-NO-HOIST-NEXT:    [[TMP13:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[N]], i64 2, i64 3)
; CHECK-NO-HOIST-NEXT:    [[TMP14:%.*]] = tail call <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv16f32.i64(<vscale x 2 x float> [[TMP12]], <vscale x 16 x float> [[ACCV_0_LCSSA]], <vscale x 2 x float> [[TMP12]], i64 7, i64 [[TMP13]])
; CHECK-NO-HOIST-NEXT:    [[TMP15:%.*]] = tail call float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float> [[TMP14]])
; CHECK-NO-HOIST-NEXT:    ret float [[TMP15]]
;
; CHECK-HOIST-LABEL: @test1(
; CHECK-HOIST-NEXT:  entry:
; CHECK-HOIST-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[N:%.*]], i64 2, i64 3)
; CHECK-HOIST-NEXT:    [[CMP_NOT24:%.*]] = icmp eq i64 [[TMP0]], 0
; CHECK-HOIST-NEXT:    br i1 [[CMP_NOT24]], label [[FOR_END:%.*]], label [[FOR_BODY:%.*]]
; CHECK-HOIST:       for.body:
; CHECK-HOIST-NEXT:    [[TMP1:%.*]] = phi i64 [ [[TMP8:%.*]], [[IF_END:%.*]] ], [ [[TMP0]], [[ENTRY:%.*]] ]
; CHECK-HOIST-NEXT:    [[ACCV_028:%.*]] = phi <vscale x 16 x float> [ [[ACCV_1:%.*]], [[IF_END]] ], [ undef, [[ENTRY]] ]
; CHECK-HOIST-NEXT:    [[X_ADDR_027:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[IF_END]] ], [ [[X:%.*]], [[ENTRY]] ]
; CHECK-HOIST-NEXT:    [[Y_ADDR_026:%.*]] = phi ptr [ [[ADD_PTR3:%.*]], [[IF_END]] ], [ [[Y:%.*]], [[ENTRY]] ]
; CHECK-HOIST-NEXT:    [[LEFT_025:%.*]] = phi i64 [ [[SUB:%.*]], [[IF_END]] ], [ [[N]], [[ENTRY]] ]
; CHECK-HOIST-NEXT:    [[TMP2:%.*]] = bitcast ptr [[X_ADDR_027]] to ptr
; CHECK-HOIST-NEXT:    [[TMP3:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.p0.i64(<vscale x 16 x float> undef, ptr [[TMP2]], i64 [[TMP1]])
; CHECK-HOIST-NEXT:    [[TMP4:%.*]] = bitcast ptr [[Y_ADDR_026]] to ptr
; CHECK-HOIST-NEXT:    [[TMP5:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.p0.i64(<vscale x 16 x float> undef, ptr [[TMP4]], i64 [[TMP1]])
; CHECK-HOIST-NEXT:    [[CMP1:%.*]] = icmp ult i64 [[LEFT_025]], [[N]]
; CHECK-HOIST-NEXT:    [[TMP6:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vfmul.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> [[TMP3]], <vscale x 16 x float> [[TMP5]], i64 7, i64 [[TMP1]])
; CHECK-HOIST-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[IF_END]]
; CHECK-HOIST:       if.then:
; CHECK-HOIST-NEXT:    [[TMP7:%.*]] = tail call <vscale x 16 x float> @llvm.riscv.vfadd.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> [[ACCV_028]], <vscale x 16 x float> [[TMP6]], i64 7, i64 [[TMP1]])
; CHECK-HOIST-NEXT:    br label [[IF_END]]
; CHECK-HOIST:       if.end:
; CHECK-HOIST-NEXT:    [[ACCV_1]] = phi <vscale x 16 x float> [ [[TMP7]], [[IF_THEN]] ], [ [[TMP6]], [[FOR_BODY]] ]
; CHECK-HOIST-NEXT:    [[MUL:%.*]] = mul i64 [[TMP1]], [[INCX:%.*]]
; CHECK-HOIST-NEXT:    [[ADD_PTR]] = getelementptr inbounds float, ptr [[X_ADDR_027]], i64 [[MUL]]
; CHECK-HOIST-NEXT:    [[MUL2:%.*]] = mul i64 [[TMP1]], [[INCY:%.*]]
; CHECK-HOIST-NEXT:    [[ADD_PTR3]] = getelementptr inbounds float, ptr [[Y_ADDR_026]], i64 [[MUL2]]
; CHECK-HOIST-NEXT:    [[SUB]] = sub i64 [[LEFT_025]], [[TMP1]]
; CHECK-HOIST-NEXT:    [[TMP8]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[SUB]], i64 2, i64 3)
; CHECK-HOIST-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[TMP8]], 0
; CHECK-HOIST-NEXT:    br i1 [[CMP_NOT]], label [[FOR_END]], label [[FOR_BODY]]
; CHECK-HOIST:       for.end:
; CHECK-HOIST-NEXT:    [[ACCV_0_LCSSA:%.*]] = phi <vscale x 16 x float> [ undef, [[ENTRY]] ], [ [[ACCV_1]], [[IF_END]] ]
; CHECK-HOIST-NEXT:    [[TMP9:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[N]], i64 2, i64 0)
; CHECK-HOIST-NEXT:    [[TMP10:%.*]] = tail call <vscale x 2 x i32> @llvm.riscv.vmv.v.x.nxv2i32.i64(<vscale x 2 x i32> undef, i32 0, i64 [[TMP9]])
; CHECK-HOIST-NEXT:    [[TMP11:%.*]] = bitcast <vscale x 2 x i32> [[TMP10]] to <vscale x 2 x float>
; CHECK-HOIST-NEXT:    [[TMP12:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[N]], i64 2, i64 3)
; CHECK-HOIST-NEXT:    [[TMP13:%.*]] = tail call <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv16f32.i64(<vscale x 2 x float> [[TMP11]], <vscale x 16 x float> [[ACCV_0_LCSSA]], <vscale x 2 x float> [[TMP11]], i64 7, i64 [[TMP12]])
; CHECK-HOIST-NEXT:    [[TMP14:%.*]] = tail call float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float> [[TMP13]])
; CHECK-HOIST-NEXT:    ret float [[TMP14]]
;
entry:
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %n, i64 2, i64 3)
  %cmp.not24 = icmp eq i64 %0, 0
  br i1 %cmp.not24, label %for.end, label %for.body

for.body:                                         ; preds = %entry, %if.end
  %1 = phi i64 [ %9, %if.end ], [ %0, %entry ]
  %accv.028 = phi <vscale x 16 x float> [ %accv.1, %if.end ], [ undef, %entry ]
  %x.addr.027 = phi float* [ %add.ptr, %if.end ], [ %x, %entry ]
  %y.addr.026 = phi float* [ %add.ptr3, %if.end ], [ %y, %entry ]
  %left.025 = phi i64 [ %sub, %if.end ], [ %n, %entry ]
  %2 = bitcast float* %x.addr.027 to <vscale x 16 x float>*
  %3 = tail call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float>* %2, i64 %1)
  %4 = bitcast float* %y.addr.026 to <vscale x 16 x float>*
  %5 = tail call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float>* %4, i64 %1)
  %cmp1 = icmp ult i64 %left.025, %n
  br i1 %cmp1, label %if.then, label %if.else

if.then:                                          ; preds = %for.body
  %6 = tail call <vscale x 16 x float> @llvm.riscv.vfmul.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> %3, <vscale x 16 x float> %5, i64 7, i64 %1)
  %7 = tail call <vscale x 16 x float> @llvm.riscv.vfadd.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> %accv.028, <vscale x 16 x float> %6, i64 7, i64 %1)
  br label %if.end

if.else:                                          ; preds = %for.body
  %8 = tail call <vscale x 16 x float> @llvm.riscv.vfmul.nxv16f32.nxv16f32.i64(<vscale x 16 x float> undef, <vscale x 16 x float> %3, <vscale x 16 x float> %5, i64 7, i64 %1)
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %accv.1 = phi <vscale x 16 x float> [ %7, %if.then ], [ %8, %if.else ]
  %mul = mul i64 %1, %incx
  %add.ptr = getelementptr inbounds float, float* %x.addr.027, i64 %mul
  %mul2 = mul i64 %1, %incy
  %add.ptr3 = getelementptr inbounds float, float* %y.addr.026, i64 %mul2
  %sub = sub i64 %left.025, %1
  %9 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %sub, i64 2, i64 3)
  %cmp.not = icmp eq i64 %9, 0
  br i1 %cmp.not, label %for.end, label %for.body

for.end:                                          ; preds = %if.end, %entry
  %accv.0.lcssa = phi <vscale x 16 x float> [ undef, %entry ], [ %accv.1, %if.end ]
  %10 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %n, i64 2, i64 0)
  %11 = tail call <vscale x 2 x i32> @llvm.riscv.vmv.v.x.nxv2i32.i64(<vscale x 2 x i32> undef, i32 0, i64 %10)
  %12 = bitcast <vscale x 2 x i32> %11 to <vscale x 2 x float>
  %13 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %n, i64 2, i64 3)
  %14 = tail call <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv16f32.i64(<vscale x 2 x float> %12, <vscale x 16 x float> %accv.0.lcssa, <vscale x 2 x float> %12, i64 7, i64 %13)
  %15 = tail call float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float> %14)
  ret float %15
}

declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)
declare <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.i64(<vscale x 16 x float>, <vscale x 16 x float>* nocapture, i64)
declare <vscale x 16 x float> @llvm.riscv.vfmul.nxv16f32.nxv16f32.i64(<vscale x 16 x float>, <vscale x 16 x float>, <vscale x 16 x float>, i64, i64)
declare <vscale x 16 x float> @llvm.riscv.vfadd.nxv16f32.nxv16f32.i64(<vscale x 16 x float>, <vscale x 16 x float>, <vscale x 16 x float>, i64, i64)
declare <vscale x 2 x i32> @llvm.riscv.vmv.v.x.nxv2i32.i64(<vscale x 2 x i32>, i32, i64)
declare <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv16f32.i64(<vscale x 2 x float>, <vscale x 16 x float>, <vscale x 2 x float>, i64, i64)

declare float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float>)

