# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 2
# RUN: llc %s -mtriple=riscv64 -run-pass=riscv-opt-w-instrs -o - | FileCheck %s

...
---
name:            movgprnox0_1
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11, $x12, $x13
    ; CHECK-LABEL: name: movgprnox0_1
    ; CHECK: liveins: $x10, $x11, $x12, $x13
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprnox0 = COPY $x12
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gprnox0 = COPY $x13
    ; CHECK-NEXT: [[PseudoCCMOVGPRNoX0_:%[0-9]+]]:gprnox0 = PseudoCCMOVGPRNoX0 [[COPY]], [[COPY1]], 1, [[COPY2]], [[COPY3]]
    ; CHECK-NEXT: [[ADDIW:%[0-9]+]]:gpr = ADDIW [[PseudoCCMOVGPRNoX0_]], 0
    ; CHECK-NEXT: $x10 = COPY [[ADDIW]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gpr = COPY $x10
    %1:gpr = COPY $x11
    %2:gpr = COPY $x12
    %3:gpr = COPY $x13
    %4:gprnox0 = ADDIW %2, 0
    %5:gprnox0 = ADDIW %3, 0
    %6:gprnox0 = PseudoCCMOVGPRNoX0 %0, %1, 1, %4, %5
    %7:gpr = ADDIW %6, 0
    $x10 = COPY %7
    PseudoRET implicit $x10

...
---
name:            movgprnox0_2
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $x10, $x11, $x12, $x13
    ; CHECK-LABEL: name: movgprnox0_2
    ; CHECK: liveins: $x10, $x11, $x12, $x13
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr = COPY $x12
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gpr = COPY $x13
    ; CHECK-NEXT: [[SRAIW:%[0-9]+]]:gprnox0 = SRAIW [[COPY2]], 0
    ; CHECK-NEXT: [[SRAIW1:%[0-9]+]]:gprnox0 = SRAIW [[COPY3]], 0
    ; CHECK-NEXT: [[PseudoCCMOVGPRNoX0_:%[0-9]+]]:gprnox0 = PseudoCCMOVGPRNoX0 [[COPY]], [[COPY1]], 1, [[SRAIW]], [[SRAIW1]]
    ; CHECK-NEXT: $x10 = COPY [[PseudoCCMOVGPRNoX0_]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:gpr = COPY $x10
    %1:gpr = COPY $x11
    %2:gpr = COPY $x12
    %3:gpr = COPY $x13
    %4:gprnox0 = SRAIW %2, 0
    %5:gprnox0 = SRAIW %3, 0
    %6:gprnox0 = PseudoCCMOVGPRNoX0 %0, %1, 1, %4, %5
    %7:gpr = ADDIW %6, 0
    $x10 = COPY %7
    PseudoRET implicit $x10

...
