; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O3 -mtriple=riscv64 -riscv-slsr-opt -mattr=+m,+v -verify-machineinstrs \
; RUN:   < %s | FileCheck %s

define void @_Z8rvv_slsrPKammPammm(i8* nocapture  readonly %A, i64  %M, i64  %K, i8* nocapture  writeonly %A_pack, i64  %K_rem, i64  %K_block_rem, i64  %num_full_K_block_sets) {
; CHECK-LABEL: _Z8rvv_slsrPKammPammm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a1, .LBB0_7
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    beqz a6, .LBB0_7
; CHECK-NEXT:  # %bb.2: # %entry
; CHECK-NEXT:    beqz a4, .LBB0_7
; CHECK-NEXT:  # %bb.3: # %for.cond2.preheader.us.preheader
; CHECK-NEXT:    li a7, 0
; CHECK-NEXT:    slli t0, a6, 7
; CHECK-NEXT:    add a0, a0, t0
; CHECK-NEXT:    slli t0, a6, 9
; CHECK-NEXT:    add a3, a3, t0
; CHECK-NEXT:    add t0, a2, a2
; CHECK-NEXT:    # implicit-def: $v8m2
; CHECK-NEXT:  .LBB0_4: # %for.cond2.preheader.us
; CHECK-NEXT:    # =>This Loop Header: Depth=1
; CHECK-NEXT:    # Child Loop BB0_5 Depth 2
; CHECK-NEXT:    slli t4, a7, 2
; CHECK-NEXT:    mul t2, t4, a2
; CHECK-NEXT:    add t1, a0, t2
; CHECK-NEXT:    add t3, t2, a2
; CHECK-NEXT:    add t5, t2, t0
; CHECK-NEXT:    add t2, a0, t3
; CHECK-NEXT:    add t3, a0, t5
; CHECK-NEXT:    add t4, a3, t4
; CHECK-NEXT:    mv t5, a6
; CHECK-NEXT:  .LBB0_5: # %for.body5.us65
; CHECK-NEXT:    # Parent Loop BB0_4 Depth=1
; CHECK-NEXT:    # => This Inner Loop Header: Depth=2
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, tu, mu
; CHECK-NEXT:    vle8.v v8, (t1), v0.t
; CHECK-NEXT:    vle8.v v10, (t2), v0.t
; CHECK-NEXT:    vle8.v v12, (t3), v0.t
; CHECK-NEXT:    vmv2r.v v14, v12
; CHECK-NEXT:    vsetvli zero, a5, e64, m2, ta, ma
; CHECK-NEXT:    vsseg4e64.v v8, (t4)
; CHECK-NEXT:    addi t5, t5, -1
; CHECK-NEXT:    bnez t5, .LBB0_5
; CHECK-NEXT:  # %bb.6: # %for.cond2.for.cond.cleanup4_crit_edge.split.us69
; CHECK-NEXT:    # in Loop: Header=BB0_4 Depth=1
; CHECK-NEXT:    addi a7, a7, 1
; CHECK-NEXT:    bne a7, a1, .LBB0_4
; CHECK-NEXT:  .LBB0_7: # %for.cond.cleanup
; CHECK-NEXT:    ret
entry:
  %cmp.not = icmp eq i64 %K_rem, 0
  %mul7 = shl i64 %num_full_K_block_sets, 7
  %cmp160.not = icmp eq i64 %M, 0
  %cmp351.not = icmp eq i64 %num_full_K_block_sets, 0
  %or.cond = or i1 %cmp160.not, %cmp351.not
  %brmerge = or i1 %or.cond, %cmp.not
  br i1 %brmerge, label %for.cond.cleanup, label %for.cond2.preheader.us.preheader

for.cond2.preheader.us.preheader:                 ; preds = %entry
  %mul23 = shl i64 %num_full_K_block_sets, 9
  %add.ptr.us = getelementptr inbounds i8, i8* %A, i64 %mul7
  %add.ptr12.us = getelementptr inbounds i8, i8* %A, i64 %mul7
  %add.ptr18.us = getelementptr inbounds i8, i8* %A, i64 %mul7
  %add.ptr22.us = getelementptr inbounds i8, i8* %A_pack, i64 %mul23
  br label %for.cond2.preheader.us

for.cond2.preheader.us:                           ; preds = %for.cond2.preheader.us.preheader, %for.cond2.for.cond.cleanup4_crit_edge.split.us69
  %Apad0.064.us = phi <vscale x 16 x i8> [ %4, %for.cond2.for.cond.cleanup4_crit_edge.split.us69 ], [ undef, %for.cond2.preheader.us.preheader ]
  %Apad1.063.us = phi <vscale x 16 x i8> [ %5, %for.cond2.for.cond.cleanup4_crit_edge.split.us69 ], [ undef, %for.cond2.preheader.us.preheader ]
  %Apad2.062.us = phi <vscale x 16 x i8> [ %6, %for.cond2.for.cond.cleanup4_crit_edge.split.us69 ], [ undef, %for.cond2.preheader.us.preheader ]
  %mb.061.us = phi i64 [ %inc26.us, %for.cond2.for.cond.cleanup4_crit_edge.split.us69 ], [ 0, %for.cond2.preheader.us.preheader ]
  %mul.us = shl i64 %mb.061.us, 2
  %mul6.us = mul i64 %mul.us, %K
  %add.ptr8.us = getelementptr inbounds i8, i8* %add.ptr.us, i64 %mul6.us
  %add10.us = or i64 %mul.us, 1
  %mul11.us = mul i64 %add10.us, %K
  %add.ptr14.us = getelementptr inbounds i8, i8* %add.ptr12.us, i64 %mul11.us
  %add16.us = or i64 %mul.us, 2
  %mul17.us = mul i64 %add16.us, %K
  %add.ptr20.us = getelementptr inbounds i8, i8* %add.ptr18.us, i64 %mul17.us
  %add.ptr24.us = getelementptr inbounds i8, i8* %add.ptr22.us, i64 %mul.us
  %0 = bitcast i8* %add.ptr8.us to <vscale x 16 x i8>*
  %1 = bitcast i8* %add.ptr14.us to <vscale x 16 x i8>*
  %2 = bitcast i8* %add.ptr20.us to <vscale x 16 x i8>*
  %3 = bitcast i8* %add.ptr24.us to i64*
  br label %for.body5.us65

for.body5.us65:                                   ; preds = %for.cond2.preheader.us, %for.body5.us65
  %Apad0.155.us = phi <vscale x 16 x i8> [ %Apad0.064.us, %for.cond2.preheader.us ], [ %4, %for.body5.us65 ]
  %Apad1.154.us = phi <vscale x 16 x i8> [ %Apad1.063.us, %for.cond2.preheader.us ], [ %5, %for.body5.us65 ]
  %Apad2.153.us = phi <vscale x 16 x i8> [ %Apad2.062.us, %for.cond2.preheader.us ], [ %6, %for.body5.us65 ]
  %kbs.052.us66 = phi i64 [ 0, %for.cond2.preheader.us ], [ %inc.us67, %for.body5.us65 ]
  %4 = tail call <vscale x 16 x i8> @llvm.riscv.vle.mask.nxv16i8.i64(<vscale x 16 x i8> %Apad0.155.us, <vscale x 16 x i8>* %0, <vscale x 16 x i1> undef, i64 %K_rem, i64 0)
  %5 = tail call <vscale x 16 x i8> @llvm.riscv.vle.mask.nxv16i8.i64(<vscale x 16 x i8> %Apad1.154.us, <vscale x 16 x i8>* %1, <vscale x 16 x i1> undef, i64 %K_rem, i64 0)
  %6 = tail call <vscale x 16 x i8> @llvm.riscv.vle.mask.nxv16i8.i64(<vscale x 16 x i8> %Apad2.153.us, <vscale x 16 x i8>* %2, <vscale x 16 x i1> undef, i64 %K_rem, i64 0)
  %7 = bitcast <vscale x 16 x i8> %4 to <vscale x 2 x i64>
  %8 = bitcast <vscale x 16 x i8> %5 to <vscale x 2 x i64>
  %9 = bitcast <vscale x 16 x i8> %6 to <vscale x 2 x i64>
  %v_0 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 4) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_2t.nxv2i64(target("riscv.vector.tuple", <vscale x 16 x i8>, 4) poison, <vscale x 2 x i64> %7, i32 0)
  %v_1 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 4) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_2t.nxv2i64(target("riscv.vector.tuple", <vscale x 16 x i8>, 4) %v_0, <vscale x 2 x i64> %8, i32 1)
  %v_2 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 4) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_2t.nxv2i64(target("riscv.vector.tuple", <vscale x 16 x i8>, 4) %v_1, <vscale x 2 x i64> %9, i32 2)
  %v_3 = call target("riscv.vector.tuple", <vscale x 16 x i8>, 4) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_2t.nxv2i64(target("riscv.vector.tuple", <vscale x 16 x i8>, 4) %v_2, <vscale x 2 x i64> %9, i32 3)
  tail call void @llvm.riscv.vsseg4.triscv.vector.tuple_nxv16i8_4t(target("riscv.vector.tuple", <vscale x 16 x i8>, 4) %v_3, i64* %3, i64 %K_block_rem, i64 6) #2
  %inc.us67 = add nuw i64 %kbs.052.us66, 1
  %exitcond.not = icmp eq i64 %inc.us67, %num_full_K_block_sets
  br i1 %exitcond.not, label %for.cond2.for.cond.cleanup4_crit_edge.split.us69, label %for.body5.us65

for.cond2.for.cond.cleanup4_crit_edge.split.us69: ; preds = %for.body5.us65
  %inc26.us = add nuw i64 %mb.061.us, 1
  %exitcond75.not = icmp eq i64 %inc26.us, %M
  br i1 %exitcond75.not, label %for.cond.cleanup, label %for.cond2.preheader.us

for.cond.cleanup:                                 ; preds = %for.cond2.for.cond.cleanup4_crit_edge.split.us69, %entry
  ret void
}

declare <vscale x 16 x i8> @llvm.riscv.vle.mask.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>* nocapture, <vscale x 16 x i1>, i64, i64 immarg) #1
declare void @llvm.riscv.vsseg4.triscv.vector.tuple_nxv16i8_4t(target("riscv.vector.tuple", <vscale x 16 x i8>, 4), i64* nocapture, i64, i64) #2
