; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=riscv64 -S --passes='require<profile-summary>,function(codegenprepare)' < %s | FileCheck %s

define <vscale x 1 x double> @simple(<vscale x 1 x double> %v1, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl) {
; CHECK-LABEL: define <vscale x 1 x double> @simple(
; CHECK-SAME: <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i32 [[VL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = tail call fast <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> shufflevector (<vscale x 1 x double> insertelement (<vscale x 1 x double> poison, double 1.000000e+00, i64 0), <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x double> [[V2]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A0:%.*]] = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[V1]], <vscale x 1 x double> [[TMP1]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A1:%.*]] = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[A0]], <vscale x 1 x double> [[TMP1]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A2:%.*]] = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[A1]], <vscale x 1 x double> [[TMP1]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A3:%.*]] = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[A2]], <vscale x 1 x double> [[TMP1]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 1 x double> [[A3]]
;
  %a0 = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %v1, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s0 = tail call fast <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a0, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)
  %a1 = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %s0, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s1 = tail call fast <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a1, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)
  %a2 = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %s1, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s2 = tail call fast <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a2, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)
  %a3 = tail call fast <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %s2, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s3 = tail call fast <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a3, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)

  ret <vscale x 1 x double> %s3
}

define float @simple_scalar(float %a, float %b) {
; CHECK-LABEL: define float @simple_scalar(
; CHECK-SAME: float [[A:%.*]], float [[B:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = fsub fast float 1.000000e+00, [[B]]
; CHECK-NEXT:    [[T1:%.*]] = fadd fast float [[A]], [[TMP1]]
; CHECK-NEXT:    [[T2:%.*]] = fadd fast float [[T1]], [[TMP1]]
; CHECK-NEXT:    [[T3:%.*]] = fadd fast float [[T2]], [[TMP1]]
; CHECK-NEXT:    ret float [[T3]]
;
  %t1 = fadd fast float %a, 1.0
  %r1 = fsub fast float %t1, %b
  %t2 = fadd fast float %r1, 1.0
  %r2 = fsub fast float %t2, %b
  %t3 = fadd fast float %r2, 1.0
  %r3 = fsub fast float %t3, %b
  ret float %r3
}

; Negative tests

define <vscale x 1 x double> @no_reassc_flag(<vscale x 1 x double> %v1, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl) {
; CHECK-LABEL: define <vscale x 1 x double> @no_reassc_flag(
; CHECK-SAME: <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i32 [[VL:%.*]]) {
; CHECK-NEXT:    [[A0:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[V1]], <vscale x 1 x double> shufflevector (<vscale x 1 x double> insertelement (<vscale x 1 x double> poison, double 1.000000e+00, i64 0), <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[S0:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> [[A0]], <vscale x 1 x double> [[V2]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A1:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[S0]], <vscale x 1 x double> shufflevector (<vscale x 1 x double> insertelement (<vscale x 1 x double> poison, double 1.000000e+00, i64 0), <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[S1:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> [[A1]], <vscale x 1 x double> [[V2]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A2:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[S1]], <vscale x 1 x double> shufflevector (<vscale x 1 x double> insertelement (<vscale x 1 x double> poison, double 1.000000e+00, i64 0), <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[S2:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> [[A2]], <vscale x 1 x double> [[V2]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[A3:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> [[S2]], <vscale x 1 x double> shufflevector (<vscale x 1 x double> insertelement (<vscale x 1 x double> poison, double 1.000000e+00, i64 0), <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[S3:%.*]] = tail call <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> [[A3]], <vscale x 1 x double> [[V2]], <vscale x 1 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 1 x double> [[S3]]
;
  %a0 = tail call <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %v1, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s0 = tail call <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a0, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)
  %a1 = tail call <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %s0, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s1 = tail call <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a1, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)
  %a2 = tail call <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %s1, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s2 = tail call <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a2, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)
  %a3 = tail call <vscale x 1 x double> @llvm.vp.fadd.nx1f64(<vscale x 1 x double> %s2, <vscale x 1 x double> splat (double 1.0), <vscale x 1 x i1> %mask, i32 %vl)
  %s3 = tail call <vscale x 1 x double> @llvm.vp.fsub.nx1f64(<vscale x 1 x double> %a3, <vscale x 1 x double> %v2, <vscale x 1 x i1> %mask, i32 %vl)

  ret <vscale x 1 x double> %s3
}

define float @no_reassoc_flag_scalar(float %a, float %b) {
; CHECK-LABEL: define float @no_reassoc_flag_scalar(
; CHECK-SAME: float [[A:%.*]], float [[B:%.*]]) {
; CHECK-NEXT:    [[T1:%.*]] = fadd float [[A]], 1.000000e+00
; CHECK-NEXT:    [[R1:%.*]] = fsub float [[T1]], [[B]]
; CHECK-NEXT:    [[T2:%.*]] = fadd float [[R1]], 1.000000e+00
; CHECK-NEXT:    [[R2:%.*]] = fsub float [[T2]], [[B]]
; CHECK-NEXT:    [[T3:%.*]] = fadd float [[R2]], 1.000000e+00
; CHECK-NEXT:    [[R3:%.*]] = fsub float [[T3]], [[B]]
; CHECK-NEXT:    ret float [[R3]]
;
  %t1 = fadd float %a, 1.0
  %r1 = fsub float %t1, %b
  %t2 = fadd float %r1, 1.0
  %r2 = fsub float %t2, %b
  %t3 = fadd float %r2, 1.0
  %r3 = fsub float %t3, %b
  ret float %r3
}
