; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=riscv32 -riscv-insert-loop-nop | FileCheck %s --check-prefixes=CHECK,RV32,RV32-NOCPU
; RUN: llc < %s -mtriple=riscv64 -riscv-insert-loop-nop | FileCheck %s --check-prefixes=CHECK,RV64
; RUN: llc < %s -mtriple=riscv32 -mcpu=sifive-e76 | FileCheck %s --check-prefixes=CHECK,RV32,RV32-MCPU
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-u74 | FileCheck %s --check-prefixes=CHECK,RV64

define void @test1(ptr noundef %a, i32 signext %b) {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB0_1: # %while.cond
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw a2, 0(a0)
; CHECK-NEXT:    bne a2, a1, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %while.end
; CHECK-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i32, ptr %a, align 4
  %cmp.not = icmp eq i32 %0, %b
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}

define void @test2(ptr noundef %a) {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a1, 74565
; CHECK-NEXT:    addi a1, a1, 1656
; CHECK-NEXT:  .LBB1_1: # %while.cond
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lw a2, 0(a0)
; CHECK-NEXT:    bne a2, a1, .LBB1_1
; CHECK-NEXT:  # %bb.2: # %while.end
; CHECK-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i32, ptr %a, align 4
  %cmp.not = icmp eq i32 %0, 305419896
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}

define void @test3(ptr noundef %a, i16 signext %b) {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB2_1: # %while.cond
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lh a2, 0(a0)
; CHECK-NEXT:    bge a2, a1, .LBB2_1
; CHECK-NEXT:  # %bb.2: # %while.end
; CHECK-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i16, ptr %a, align 2
  %cmp.not = icmp slt i16 %0, %b
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}

define void @test4(ptr noundef %a, i16 zeroext %b) {
; CHECK-LABEL: test4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB3_1: # %while.cond
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lhu a2, 0(a0)
; CHECK-NEXT:    bgeu a2, a1, .LBB3_1
; CHECK-NEXT:  # %bb.2: # %while.end
; CHECK-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i16, ptr %a, align 2
  %cmp.not = icmp ult i16 %0, %b
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}

define void @test5(ptr noundef %a, i8 signext %b) {
; CHECK-LABEL: test5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB4_1: # %while.cond
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lb a2, 0(a0)
; CHECK-NEXT:    bge a1, a2, .LBB4_1
; CHECK-NEXT:  # %bb.2: # %while.end
; CHECK-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i8, ptr %a, align 1
  %cmp.not = icmp sgt i8 %0, %b
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}

define void @test6(ptr noundef %a, i8 signext %b) {
; CHECK-LABEL: test6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:  .LBB5_1: # %while.cond
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    nop
; CHECK-NEXT:    lbu a2, 0(a0)
; CHECK-NEXT:    bgeu a1, a2, .LBB5_1
; CHECK-NEXT:  # %bb.2: # %while.end
; CHECK-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i8, ptr %a, align 1
  %cmp.not = icmp ugt i8 %0, %b
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}

define void @test7(ptr noundef %a, i64 %b) {
; RV32-LABEL: test7:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:  .LBB6_1: # %while.cond
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    lw a3, 0(a0)
; RV32-NEXT:    lw a4, 4(a0)
; RV32-NEXT:    xor a3, a3, a1
; RV32-NEXT:    xor a4, a4, a2
; RV32-NEXT:    or a3, a3, a4
; RV32-NEXT:    beqz a3, .LBB6_1
; RV32-NEXT:  # %bb.2: # %while.end
; RV32-NEXT:    ret
;
; RV64-LABEL: test7:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:  .LBB6_1: # %while.cond
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    nop
; RV64-NEXT:    ld a2, 0(a0)
; RV64-NEXT:    beq a2, a1, .LBB6_1
; RV64-NEXT:  # %bb.2: # %while.end
; RV64-NEXT:    ret
entry:
  br label %while.cond

while.cond:                                       ; preds = %while.cond, %entry
  %0 = load volatile i64, ptr %a, align 8
  %cmp.not = icmp ne i64 %0, %b
  br i1 %cmp.not, label %while.end, label %while.cond

while.end:                                        ; preds = %while.cond
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32-MCPU: {{.*}}
; RV32-NOCPU: {{.*}}
