; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+m | FileCheck %s

define i64 @test_addw(i32* nocapture readonly %0, i32 %1) {
; CHECK-LABEL: test_addw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a0, 0(a0)
; CHECK-NEXT:    addw a0, a0, a1
; CHECK-NEXT:    ret
  %3 = load i32, i32* %0, align 4
  %4 = add nsw i32 %3, %1
  %5 = sext i32 %4 to i64
  ret i64 %5
}

define i64 @test_subw(i32* nocapture readonly %0, i32 %1) {
; CHECK-LABEL: test_subw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a0, 0(a0)
; CHECK-NEXT:    subw a0, a0, a1
; CHECK-NEXT:    ret
  %3 = load i32, i32* %0, align 4
  %4 = sub nsw i32 %3, %1
  %5 = sext i32 %4 to i64
  ret i64 %5
}

define i64 @test_mulw(i32* nocapture readonly %0, i32 %1) {
; CHECK-LABEL: test_mulw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a0, 0(a0)
; CHECK-NEXT:    mulw a0, a0, a1
; CHECK-NEXT:    ret
  %3 = load i32, i32* %0, align 4
  %4 = mul nsw i32 %3, %1
  %5 = sext i32 %4 to i64
  ret i64 %5
}

define i64 @test_shlw(i32* nocapture readonly %0, i32 %1) {
; CHECK-LABEL: test_shlw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lw a0, 0(a0)
; CHECK-NEXT:    sllw a0, a0, a1
; CHECK-NEXT:    ret
  %3 = load i32, i32* %0, align 4
  %4 = shl nsw i32 %3, %1
  %5 = sext i32 %4 to i64
  ret i64 %5
}
