; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=slp-vectorizer -S -mtriple=riscv64 -mcpu=sifive-x280n < %s | FileCheck %s

define void @reverse_store(ptr %a, ptr %b) {
  %1 = load i8, ptr %a, align 1, !tbaa !0
  %conv1 = sext i8 %1 to i32
  %dst1 = getelementptr inbounds i8, ptr %b, i64 12
  store i32 %conv1, ptr %dst1, align 4, !tbaa !5
  %src2 = getelementptr inbounds i8, ptr %a, i64 1
  %2 = load i8, ptr %src2, align 1, !tbaa !8
  %conv2 = sext i8 %2 to i32
  %dst2 = getelementptr inbounds i8, ptr %b, i64 8
  store i32 %conv2, ptr %dst2, align 4, !tbaa !9
  %src3 = getelementptr inbounds i8, ptr %a, i64 2
  %3 = load i8, ptr %src3, align 1, !tbaa !10
  %conv3 = sext i8 %3 to i32
  %dst3 = getelementptr inbounds i8, ptr %b, i64 4
  store i32 %conv3, ptr %dst3, align 4, !tbaa !11
  %src4 = getelementptr inbounds i8, ptr %a, i64 3
  %4 = load i8, ptr %src4, align 1, !tbaa !12
  %conv4 = sext i8 %4 to i32
  store i32 %conv4, ptr %b, align 4, !tbaa !13
  ret void
}

!0 = !{!1, !3, i64 0}
!1 = !{!"_ZTS1n", !2, i64 0}
!2 = !{!"_ZTS1m", !3, i64 0, !3, i64 1, !3, i64 2, !3, i64 3}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C++ TBAA"}
!5 = !{!6, !7, i64 12}
!6 = !{!"_ZTS1g", !7, i64 0, !7, i64 4, !7, i64 8, !7, i64 12}
!7 = !{!"int", !3, i64 0}
!8 = !{!1, !3, i64 1}
!9 = !{!6, !7, i64 8}
!10 = !{!1, !3, i64 2}
!11 = !{!6, !7, i64 4}
!12 = !{!1, !3, i64 3}
!13 = !{!6, !7, i64 0}
