; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE

%struct.RExC_state_t = type { i32, ptr, ptr, ptr, ptr, ptr, i32, ptr, ptr, i32, i32, i32, i32, i32, i32, i32, i32, i32 }

; FIXME: non-profitable SLP on p470,p670
; reduced from Perl_pregcomp@regcomp.c:1784
define void @Perl_pregcomp(ptr %RExC_state) {
; PROFITABLE-LABEL: define void @Perl_pregcomp
; PROFITABLE-SAME: (ptr [[REXC_STATE:%.*]]) #[[ATTR0:[0-9]+]] {
; PROFITABLE-NEXT:  entry:
; PROFITABLE-NEXT:    [[NAUGHTY:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T:%.*]], ptr [[REXC_STATE]], i64 0, i32 9
; PROFITABLE-NEXT:    [[SAWBACK:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T]], ptr [[REXC_STATE]], i64 0, i32 10
; PROFITABLE-NEXT:    [[SEEN:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T]], ptr [[REXC_STATE]], i64 0, i32 11
; PROFITABLE-NEXT:    [[SIZE:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T]], ptr [[REXC_STATE]], i64 0, i32 12
; PROFITABLE-NEXT:    store i32 0, ptr [[NAUGHTY]], align 8
; PROFITABLE-NEXT:    store i32 0, ptr [[SAWBACK]], align 4
; PROFITABLE-NEXT:    store i32 0, ptr [[SEEN]], align 8
; PROFITABLE-NEXT:    store i32 0, ptr [[SIZE]], align 4
; PROFITABLE-NEXT:    ret void
;
; NON-PROFITABLE-LABEL: define void @Perl_pregcomp
; NON-PROFITABLE-SAME: (ptr [[REXC_STATE:%.*]]) #[[ATTR0:[0-9]+]] {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    [[NAUGHTY:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T:%.*]], ptr [[REXC_STATE]], i64 0, i32 9
; NON-PROFITABLE-NEXT:    [[SAWBACK:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T]], ptr [[REXC_STATE]], i64 0, i32 10
; NON-PROFITABLE-NEXT:    [[SEEN:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T]], ptr [[REXC_STATE]], i64 0, i32 11
; NON-PROFITABLE-NEXT:    [[SIZE:%.*]] = getelementptr inbounds [[STRUCT_REXC_STATE_T]], ptr [[REXC_STATE]], i64 0, i32 12
; NON-PROFITABLE-NEXT:    store i32 0, ptr [[NAUGHTY]], align 8
; NON-PROFITABLE-NEXT:    store i32 0, ptr [[SAWBACK]], align 4
; NON-PROFITABLE-NEXT:    store i32 0, ptr [[SEEN]], align 8
; NON-PROFITABLE-NEXT:    store i32 0, ptr [[SIZE]], align 4
; NON-PROFITABLE-NEXT:    ret void
entry:
  %naughty = getelementptr inbounds %struct.RExC_state_t, ptr %RExC_state, i64 0, i32 9
  %sawback = getelementptr inbounds %struct.RExC_state_t, ptr %RExC_state, i64 0, i32 10
  %seen = getelementptr inbounds %struct.RExC_state_t, ptr %RExC_state, i64 0, i32 11
  %size = getelementptr inbounds %struct.RExC_state_t, ptr %RExC_state, i64 0, i32 12
  store i32 0, ptr %naughty, align 8
  store i32 0, ptr %sawback, align 4
  store i32 0, ptr %seen, align 8
  store i32 0, ptr %size, align 4
  ret void
}
