; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE

; non-profitable cases on x280, p470, and p670
; reduced from _ZN12_GLOBAL__N_116inpaint_internalERK5ImageIfERK9ImageMaskiiPS1_@src/geekbench/inpaint/inpaint.cpp:218
define fastcc void @_ZN12_GLOBAL__N_116inpaint_internalERK5ImageIfERK9ImageMaskiiPS1_(ptr %input, ptr %inpaint_domain_mask, i32 %inpaint_iterations, i32 %patchmatch_iterations, ptr %output) personality ptr null {
; NON-PROFITABLE-LABEL: define fastcc void @_ZN12_GLOBAL__N_116inpaint_internalERK5ImageIfERK9ImageMaskiiPS1_
; NON-PROFITABLE-SAME: (ptr [[INPUT:%.*]], ptr [[INPAINT_DOMAIN_MASK:%.*]], i32 [[INPAINT_ITERATIONS:%.*]], i32 [[PATCHMATCH_ITERATIONS:%.*]], ptr [[OUTPUT:%.*]]) #[[ATTR0:[0-9]+]] personality ptr null {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    br label [[FOR_COND2_PREHEADER_I:%.*]]
; NON-PROFITABLE:       for.cond2.preheader.i:
; NON-PROFITABLE-NEXT:    [[SC_SUM_G_085_I:%.*]] = phi float [ 0.000000e+00, [[ENTRY:%.*]] ], [ [[ADD23_6_I:%.*]], [[FOR_COND2_PREHEADER_I]] ]
; NON-PROFITABLE-NEXT:    [[SC_SUM_B_084_I:%.*]] = phi float [ 0.000000e+00, [[ENTRY]] ], [ [[ADD26_6_I:%.*]], [[FOR_COND2_PREHEADER_I]] ]
; NON-PROFITABLE-NEXT:    [[CALL14_1_I167:%.*]] = call float null(float 0.000000e+00)
; NON-PROFITABLE-NEXT:    [[I465:%.*]] = load float, ptr null, align 4
; NON-PROFITABLE-NEXT:    [[I466:%.*]] = load float, ptr null, align 4
; NON-PROFITABLE-NEXT:    [[CALL14_2_I168:%.*]] = call float null(float 0.000000e+00)
; NON-PROFITABLE-NEXT:    [[CALL14_3_I169:%.*]] = call float null(float 0.000000e+00)
; NON-PROFITABLE-NEXT:    [[CALL14_4_I170:%.*]] = call float null(float 0.000000e+00)
; NON-PROFITABLE-NEXT:    [[CALL14_5_I171:%.*]] = call float null(float 0.000000e+00)
; NON-PROFITABLE-NEXT:    [[CALL14_6_I172:%.*]] = call float null(float 0.000000e+00)
; NON-PROFITABLE-NEXT:    [[MUL25_5_I:%.*]] = fmul float 0.000000e+00, [[CALL14_5_I171]]
; NON-PROFITABLE-NEXT:    [[MUL25_4_I:%.*]] = fmul float 0.000000e+00, [[CALL14_4_I170]]
; NON-PROFITABLE-NEXT:    [[MUL25_3_I:%.*]] = fmul float 0.000000e+00, [[CALL14_3_I169]]
; NON-PROFITABLE-NEXT:    [[MUL25_2_I:%.*]] = fmul float 0.000000e+00, [[CALL14_2_I168]]
; NON-PROFITABLE-NEXT:    [[MUL25_1_I:%.*]] = fmul float [[I466]], [[CALL14_1_I167]]
; NON-PROFITABLE-NEXT:    [[MUL25_I:%.*]] = fmul float 0.000000e+00, 0.000000e+00
; NON-PROFITABLE-NEXT:    [[ADD26_I:%.*]] = fadd float [[MUL25_I]], [[SC_SUM_B_084_I]]
; NON-PROFITABLE-NEXT:    [[ADD26_1_I:%.*]] = fadd float [[ADD26_I]], [[MUL25_1_I]]
; NON-PROFITABLE-NEXT:    [[ADD26_2_I:%.*]] = fadd float [[ADD26_1_I]], [[MUL25_2_I]]
; NON-PROFITABLE-NEXT:    [[ADD26_3_I:%.*]] = fadd float [[ADD26_2_I]], [[MUL25_3_I]]
; NON-PROFITABLE-NEXT:    [[ADD26_4_I:%.*]] = fadd float [[ADD26_3_I]], [[MUL25_4_I]]
; NON-PROFITABLE-NEXT:    [[ADD26_5_I:%.*]] = fadd float [[ADD26_4_I]], [[MUL25_5_I]]
; NON-PROFITABLE-NEXT:    [[MUL22_5_I:%.*]] = fmul float 0.000000e+00, [[CALL14_5_I171]]
; NON-PROFITABLE-NEXT:    [[MUL22_4_I:%.*]] = fmul float 0.000000e+00, [[CALL14_4_I170]]
; NON-PROFITABLE-NEXT:    [[MUL22_3_I:%.*]] = fmul float 0.000000e+00, [[CALL14_3_I169]]
; NON-PROFITABLE-NEXT:    [[MUL22_2_I:%.*]] = fmul float 0.000000e+00, [[CALL14_2_I168]]
; NON-PROFITABLE-NEXT:    [[MUL22_1_I:%.*]] = fmul float [[I465]], [[CALL14_1_I167]]
; NON-PROFITABLE-NEXT:    [[MUL22_I:%.*]] = fmul float 0.000000e+00, 0.000000e+00
; NON-PROFITABLE-NEXT:    [[ADD23_I:%.*]] = fadd float [[MUL22_I]], [[SC_SUM_G_085_I]]
; NON-PROFITABLE-NEXT:    [[ADD23_1_I:%.*]] = fadd float [[ADD23_I]], [[MUL22_1_I]]
; NON-PROFITABLE-NEXT:    [[ADD23_2_I:%.*]] = fadd float [[ADD23_1_I]], [[MUL22_2_I]]
; NON-PROFITABLE-NEXT:    [[ADD23_3_I:%.*]] = fadd float [[ADD23_2_I]], [[MUL22_3_I]]
; NON-PROFITABLE-NEXT:    [[ADD23_4_I:%.*]] = fadd float [[ADD23_3_I]], [[MUL22_4_I]]
; NON-PROFITABLE-NEXT:    [[ADD23_5_I:%.*]] = fadd float [[ADD23_4_I]], [[MUL22_5_I]]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX21_6_I:%.*]] = getelementptr float, ptr null, i64 1
; NON-PROFITABLE-NEXT:    [[I515:%.*]] = load float, ptr [[ARRAYIDX21_6_I]], align 4
; NON-PROFITABLE-NEXT:    [[MUL22_6_I:%.*]] = fmul float [[I515]], [[CALL14_6_I172]]
; NON-PROFITABLE-NEXT:    [[ADD23_6_I]] = fadd float [[ADD23_5_I]], [[MUL22_6_I]]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX24_6_I:%.*]] = getelementptr float, ptr null, i64 2
; NON-PROFITABLE-NEXT:    [[I516:%.*]] = load float, ptr [[ARRAYIDX24_6_I]], align 4
; NON-PROFITABLE-NEXT:    [[MUL25_6_I:%.*]] = fmul float [[I516]], [[CALL14_6_I172]]
; NON-PROFITABLE-NEXT:    [[ADD26_6_I]] = fadd float [[ADD26_5_I]], [[MUL25_6_I]]
; NON-PROFITABLE-NEXT:    [[ADD27_6_I:%.*]] = fadd float 0.000000e+00, [[CALL14_6_I172]]
; NON-PROFITABLE-NEXT:    br i1 false, label [[INVOKE_CONT53:%.*]], label [[FOR_COND2_PREHEADER_I]]
; NON-PROFITABLE:       invoke.cont53:
; NON-PROFITABLE-NEXT:    [[DIV33_I:%.*]] = fdiv float [[ADD23_6_I]], [[ADD27_6_I]]
; NON-PROFITABLE-NEXT:    [[CMP1_I67_I:%.*]] = fcmp olt float [[DIV33_I]], 0.000000e+00
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I68_I:%.*]] = select i1 [[CMP1_I67_I]], float 0.000000e+00, float [[DIV33_I]]
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I6975_I:%.*]] = call float @llvm.minnum.f32(float [[MINIMUM_VALUE_VALUE_I68_I]], float 1.000000e+00)
; NON-PROFITABLE-NEXT:    [[ARRAYIDX35_I:%.*]] = getelementptr float, ptr null, i64 1
; NON-PROFITABLE-NEXT:    store float [[RETVAL_0_I6975_I]], ptr [[ARRAYIDX35_I]], align 4
; NON-PROFITABLE-NEXT:    [[DIV36_I:%.*]] = fdiv float [[ADD26_6_I]], [[ADD27_6_I]]
; NON-PROFITABLE-NEXT:    [[CMP1_I71_I:%.*]] = fcmp olt float [[DIV36_I]], 0.000000e+00
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I72_I:%.*]] = select i1 [[CMP1_I71_I]], float 0.000000e+00, float [[DIV36_I]]
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I7376_I:%.*]] = call float @llvm.minnum.f32(float [[MINIMUM_VALUE_VALUE_I72_I]], float 1.000000e+00)
; NON-PROFITABLE-NEXT:    [[ARRAYIDX38_I:%.*]] = getelementptr float, ptr null, i64 2
; NON-PROFITABLE-NEXT:    store float [[RETVAL_0_I7376_I]], ptr [[ARRAYIDX38_I]], align 4
; NON-PROFITABLE-NEXT:    ret void
;
entry:
  br label %for.cond2.preheader.i

for.cond2.preheader.i:
  %sc_sum_g.085.i = phi float [ 0.000000e+00, %entry ], [ %add23.6.i, %for.cond2.preheader.i ]
  %sc_sum_b.084.i = phi float [ 0.000000e+00, %entry ], [ %add26.6.i, %for.cond2.preheader.i ]
  %call14.1.i167 = call float null(float 0.000000e+00)
  %i465 = load float, ptr null, align 4
  %i466 = load float, ptr null, align 4
  %call14.2.i168 = call float null(float 0.000000e+00)
  %call14.3.i169 = call float null(float 0.000000e+00)
  %call14.4.i170 = call float null(float 0.000000e+00)
  %call14.5.i171 = call float null(float 0.000000e+00)
  %call14.6.i172 = call float null(float 0.000000e+00)
  %mul25.5.i = fmul float 0.000000e+00, %call14.5.i171
  %mul25.4.i = fmul float 0.000000e+00, %call14.4.i170
  %mul25.3.i = fmul float 0.000000e+00, %call14.3.i169
  %mul25.2.i = fmul float 0.000000e+00, %call14.2.i168
  %mul25.1.i = fmul float %i466, %call14.1.i167
  %mul25.i = fmul float 0.000000e+00, 0.000000e+00
  %add26.i = fadd float %mul25.i, %sc_sum_b.084.i
  %add26.1.i = fadd float %add26.i, %mul25.1.i
  %add26.2.i = fadd float %add26.1.i, %mul25.2.i
  %add26.3.i = fadd float %add26.2.i, %mul25.3.i
  %add26.4.i = fadd float %add26.3.i, %mul25.4.i
  %add26.5.i = fadd float %add26.4.i, %mul25.5.i
  %mul22.5.i = fmul float 0.000000e+00, %call14.5.i171
  %mul22.4.i = fmul float 0.000000e+00, %call14.4.i170
  %mul22.3.i = fmul float 0.000000e+00, %call14.3.i169
  %mul22.2.i = fmul float 0.000000e+00, %call14.2.i168
  %mul22.1.i = fmul float %i465, %call14.1.i167
  %mul22.i = fmul float 0.000000e+00, 0.000000e+00
  %add23.i = fadd float %mul22.i, %sc_sum_g.085.i
  %add23.1.i = fadd float %add23.i, %mul22.1.i
  %add23.2.i = fadd float %add23.1.i, %mul22.2.i
  %add23.3.i = fadd float %add23.2.i, %mul22.3.i
  %add23.4.i = fadd float %add23.3.i, %mul22.4.i
  %add23.5.i = fadd float %add23.4.i, %mul22.5.i
  %arrayidx21.6.i = getelementptr float, ptr null, i64 1
  %i515 = load float, ptr %arrayidx21.6.i, align 4
  %mul22.6.i = fmul float %i515, %call14.6.i172
  %add23.6.i = fadd float %add23.5.i, %mul22.6.i
  %arrayidx24.6.i = getelementptr float, ptr null, i64 2
  %i516 = load float, ptr %arrayidx24.6.i, align 4
  %mul25.6.i = fmul float %i516, %call14.6.i172
  %add26.6.i = fadd float %add26.5.i, %mul25.6.i
  %add27.6.i = fadd float 0.000000e+00, %call14.6.i172
  br i1 false, label %invoke.cont53, label %for.cond2.preheader.i

invoke.cont53:
  %div33.i = fdiv float %add23.6.i, %add27.6.i
  %cmp1.i67.i = fcmp olt float %div33.i, 0.000000e+00
  %minimum_value.value.i68.i = select i1 %cmp1.i67.i, float 0.000000e+00, float %div33.i
  %retval.0.i6975.i = call float @llvm.minnum.f32(float %minimum_value.value.i68.i, float 1.000000e+00)
  %arrayidx35.i = getelementptr float, ptr null, i64 1
  store float %retval.0.i6975.i, ptr %arrayidx35.i, align 4
  %div36.i = fdiv float %add26.6.i, %add27.6.i
  %cmp1.i71.i = fcmp olt float %div36.i, 0.000000e+00
  %minimum_value.value.i72.i = select i1 %cmp1.i71.i, float 0.000000e+00, float %div36.i
  %retval.0.i7376.i = call float @llvm.minnum.f32(float %minimum_value.value.i72.i, float 1.000000e+00)
  %arrayidx38.i = getelementptr float, ptr null, i64 2
  store float %retval.0.i7376.i, ptr %arrayidx38.i, align 4
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.minnum.f32(float, float)
