; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=riscv64-unknown-linux-gnu -mattr=+v -S -passes=slp-vectorizer < %s | FileCheck %s

define void @test(ptr noalias %p) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[TMP0:%.*]] = phi <4 x float> [ zeroinitializer, [[ENTRY:%.*]] ], [ [[TMP3:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr null, align 4
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
; CHECK-NEXT:    [[TMP3]] = fadd <4 x float> [[TMP2]], [[TMP0]]
; CHECK-NEXT:    br i1 false, label [[CLEANUP:%.*]], label [[FOR_BODY]]
; CHECK:       cleanup:
; CHECK-NEXT:    [[TMP4:%.*]] = fneg <4 x float> [[TMP3]]
; CHECK-NEXT:    store <4 x float> [[TMP4]], ptr [[P:%.*]], align 8
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %f.043 = phi float [ 0.000000e+00, %entry ], [ %add17, %for.body ]
  %c.042 = phi float [ 0.000000e+00, %entry ], [ %add12, %for.body ]
  %b.041 = phi float [ 0.000000e+00, %entry ], [ %add, %for.body ]
  %add73840 = phi float [ 0.000000e+00, %entry ], [ %add7, %for.body ]
  %0 = load float, ptr null, align 4
  %add = fadd float %b.041, %0
  %arrayidx6 = getelementptr float, ptr null, i64 1
  %1 = load float, ptr %arrayidx6, align 4
  %add7 = fadd float %1, %add73840
  %arrayidx11 = getelementptr float, ptr null, i64 2
  %2 = load float, ptr %arrayidx11, align 4
  %add12 = fadd float %c.042, %2
  %arrayidx16 = getelementptr float, ptr null, i64 3
  %3 = load float, ptr %arrayidx16, align 4
  %add17 = fadd float %f.043, %3
  br i1 false, label %cleanup, label %for.body

cleanup:
  %fneg = fneg float %add
  %bl = getelementptr float, ptr %p, i32 1
  store float %fneg, ptr %bl, align 4
  %fneg18 = fneg float %add7
  store float %fneg18, ptr %p, align 8
  %fneg19 = fneg float %add12
  %bh = getelementptr float, ptr %p, i32 3
  store float %fneg19, ptr %bh, align 4
  %fneg20 = fneg float %add17
  %f21 = getelementptr float, ptr %p, i32 2
  store float %fneg20, ptr %f21, align 8
  ret void
}
