; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S --passes=slp-vectorizer -slp-threshold=-50 -mtriple=riscv64-unknown-linux-gnu -mcpu=sifive-p670 < %s| FileCheck %s

%class.A = type { i32, i32 }

define void @test() {
; CHECK-LABEL: define void @test
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    [[ADD_I_I62_US:%.*]] = shl i64 0, 0
; CHECK-NEXT:    [[MUL_I_I63_US:%.*]] = or disjoint i64 [[ADD_I_I62_US]], 0
; CHECK-NEXT:    [[ADD_PTR_I_I_I64_US:%.*]] = getelementptr [[CLASS_A:%.*]], ptr null, i64 [[MUL_I_I63_US]]
; CHECK-NEXT:    [[SUB4_I_I65_US:%.*]] = or disjoint i64 0, 1
; CHECK-NEXT:    [[ADD_PTR_I63_I_I66_US:%.*]] = getelementptr [[CLASS_A]], ptr null, i64 [[SUB4_I_I65_US]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ADD_PTR_I63_I_I66_US]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i32> @llvm.experimental.vp.strided.load.v2i32.p0.i64(ptr align 4 [[ADD_PTR_I_I_I64_US]], i64 8, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ADD_PTR_I_I_I64_US]], align 4
; CHECK-NEXT:    [[CMP_I_I_I_I67_US:%.*]] = icmp slt i32 [[TMP2]], [[TMP0]]
; CHECK-NEXT:    [[SPEC_SELECT_I_I68_US:%.*]] = select i1 false, i64 [[SUB4_I_I65_US]], i64 0
; CHECK-NEXT:    br label [[BODY]]
;
entry:
  br label %body

body:
  %add.i.i62.us = shl i64 0, 0
  %mul.i.i63.us = or disjoint i64 %add.i.i62.us, 0
  %add.ptr.i.i.i64.us = getelementptr %class.A, ptr null, i64 %mul.i.i63.us
  %sub4.i.i65.us = or disjoint i64 0, 1
  %add.ptr.i63.i.i66.us = getelementptr %class.A, ptr null, i64 %sub4.i.i65.us
  %0 = load i32, ptr %add.ptr.i.i.i64.us, align 4
  %1 = load i32, ptr %add.ptr.i63.i.i66.us, align 4
  %cmp.i.i.i.i67.us = icmp slt i32 %0, %1
  %spec.select.i.i68.us = select i1 false, i64 %sub4.i.i65.us, i64 0
  br label %body
}

