; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S --passes=slp-vectorizer -mtriple=riscv64-unknown-linux-gnu -mattr=+v -slp-threshold=-1 < %s | FileCheck %s

define ptr @test() {
; CHECK-LABEL: define ptr @test(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr double, ptr null, i64 3
; CHECK-NEXT:    [[ARRAYIDX2_I3237:%.*]] = getelementptr double, ptr null, i64 1
; CHECK-NEXT:    [[ARRAYIDX6_I3238:%.*]] = getelementptr double, ptr null, i64 2
; CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[ARRAYIDX6_I3238]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = call <2 x double> @llvm.experimental.vp.strided.load.v2f64.p0.i64(ptr align 8 [[ARRAYIDX_I]], i64 -16, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    store <2 x double> [[TMP1]], ptr [[ARRAYIDX2_I3237]], align 8
; CHECK-NEXT:    ret ptr null
;
entry:
  %arrayidx.i = getelementptr double, ptr null, i64 3
  %0 = load double, ptr %arrayidx.i, align 8
  %arrayidx2.i3237 = getelementptr double, ptr null, i64 1
  %1 = load double, ptr %arrayidx2.i3237, align 8
  %arrayidx6.i3238 = getelementptr double, ptr null, i64 2
  %2 = load double, ptr %arrayidx6.i3238, align 8
  store double %0, ptr %arrayidx2.i3237, align 8
  store double %1, ptr %arrayidx6.i3238, align 8
  ret ptr null
}
