; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE

%struct.arc = type { i64, ptr, ptr, i32, ptr, ptr, i64, i64 }

; non-profitable SLP on p470,p670
; reduced from price_out_impl@implicit.c:154
define void @replace_weaker_arc(ptr %new, i64 %sub, i64 %sub22) {
; PROFITABLE-LABEL: define void @replace_weaker_arc
; PROFITABLE-SAME: (ptr [[NEW:%.*]], i64 [[SUB:%.*]], i64 [[SUB22:%.*]]) #[[ATTR0:[0-9]+]] {
; PROFITABLE-NEXT:  entry:
; PROFITABLE-NEXT:    [[TAIL21:%.*]] = getelementptr inbounds [[STRUCT_ARC:%.*]], ptr [[NEW]], i64 [[SUB]], i32 1
; PROFITABLE-NEXT:    [[TAIL24:%.*]] = getelementptr inbounds [[STRUCT_ARC]], ptr [[NEW]], i64 [[SUB22]], i32 1
; PROFITABLE-NEXT:    [[TMP0:%.*]] = load <2 x ptr>, ptr [[TAIL21]], align 8
; PROFITABLE-NEXT:    store <2 x ptr> [[TMP0]], ptr [[TAIL24]], align 8
; PROFITABLE-NEXT:    ret void
;
; NON-PROFITABLE-LABEL: define void @replace_weaker_arc
; NON-PROFITABLE-SAME: (ptr [[NEW:%.*]], i64 [[SUB:%.*]], i64 [[SUB22:%.*]]) #[[ATTR0:[0-9]+]] {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    [[TAIL21:%.*]] = getelementptr inbounds [[STRUCT_ARC:%.*]], ptr [[NEW]], i64 [[SUB]], i32 1
; NON-PROFITABLE-NEXT:    [[HEAD27:%.*]] = getelementptr inbounds [[STRUCT_ARC]], ptr [[NEW]], i64 [[SUB]], i32 2
; NON-PROFITABLE-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[TAIL21]], align 8
; NON-PROFITABLE-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[HEAD27]], align 8
; NON-PROFITABLE-NEXT:    [[TAIL24:%.*]] = getelementptr inbounds [[STRUCT_ARC]], ptr [[NEW]], i64 [[SUB22]], i32 1
; NON-PROFITABLE-NEXT:    [[HEAD30:%.*]] = getelementptr inbounds [[STRUCT_ARC]], ptr [[NEW]], i64 [[SUB22]], i32 2
; NON-PROFITABLE-NEXT:    store ptr [[TMP0]], ptr [[TAIL24]], align 8
; NON-PROFITABLE-NEXT:    store ptr [[TMP1]], ptr [[HEAD30]], align 8
; NON-PROFITABLE-NEXT:    ret void
;
entry:
  %tail21 = getelementptr inbounds %struct.arc, ptr %new, i64 %sub, i32 1
  %head27 = getelementptr inbounds %struct.arc, ptr %new, i64 %sub, i32 2
  %0 = load ptr, ptr %tail21, align 8
  %1 = load ptr, ptr %head27, align 8
  %tail24 = getelementptr inbounds %struct.arc, ptr %new, i64 %sub22, i32 1
  %head30 = getelementptr inbounds %struct.arc, ptr %new, i64 %sub22, i32 2
  store ptr %0, ptr %tail24, align 8
  store ptr %1, ptr %head30, align 8
  ret void
}
