; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=slp-vectorizer -S -mtriple=riscv64-unknown-linux-gnu -mcpu=sifive-x280 < %s | FileCheck %s

; Prevent non-profitable SLP store vectorization
define i32 @Proc_8(ptr %Arr_2_Par_Ref, i32 %Int_1_Par_Val) {
; CHECK-LABEL: @Proc_8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[INT_1_PAR_VAL:%.*]], 5
; CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[ADD]] to i64
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [50 x i32], ptr [[ARR_2_PAR_REF:%.*]], i64 [[IDXPROM]], i64 [[IDXPROM]]
; CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX3]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nsw i64 [[IDXPROM]], 1
; CHECK-NEXT:    [[ARRAYIDX3_1:%.*]] = getelementptr inbounds [50 x i32], ptr [[ARR_2_PAR_REF]], i64 [[IDXPROM]], i64 [[INDVARS_IV_NEXT]]
; CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX3_1]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[INT_1_PAR_VAL]], 4
; CHECK-NEXT:    [[IDXPROM6:%.*]] = sext i32 [[SUB]] to i64
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds [50 x i32], ptr [[ARR_2_PAR_REF]], i64 [[IDXPROM]], i64 [[IDXPROM6]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    [[ADD8:%.*]] = add nsw i32 [[TMP0]], 1
; CHECK-NEXT:    store i32 [[ADD8]], ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    ret i32 poison
;
entry:
  %add = add nsw i32 %Int_1_Par_Val, 5
  %idxprom = sext i32 %add to i64
  %arrayidx3 = getelementptr inbounds [50 x i32], ptr %Arr_2_Par_Ref, i64 %idxprom, i64 %idxprom
  store i32 %add, ptr %arrayidx3, align 4
  %indvars.iv.next = add nsw i64 %idxprom, 1
  %arrayidx3.1 = getelementptr inbounds [50 x i32], ptr %Arr_2_Par_Ref, i64 %idxprom, i64 %indvars.iv.next
  store i32 %add, ptr %arrayidx3.1, align 4
  %sub = add nsw i32 %Int_1_Par_Val, 4
  %idxprom6 = sext i32 %sub to i64
  %arrayidx7 = getelementptr inbounds [50 x i32], ptr %Arr_2_Par_Ref, i64 %idxprom, i64 %idxprom6
  %0 = load i32, ptr %arrayidx7, align 4
  %add8 = add nsw i32 %0, 1
  store i32 %add8, ptr %arrayidx7, align 4
  ret i32 poison
}
