; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=riscv64 -mcpu=sifive-x280 -passes=slp-vectorizer -S -slp-revec -slp-max-reg-size=1024 -slp-threshold=-100 %s | FileCheck %s

define void @test1(ptr %ptr0) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ALLOCA0:%.*]] = alloca [12 x float], i32 0, align 16
; CHECK-NEXT:    [[GETELEMENTPTR0:%.*]] = getelementptr inbounds i8, ptr [[ALLOCA0]], i64 32
; CHECK-NEXT:    [[GETELEMENTPTR1:%.*]] = getelementptr inbounds i8, ptr [[PTR0:%.*]], i64 128
; CHECK-NEXT:    [[LOAD0:%.*]] = load <4 x float>, ptr [[ALLOCA0]], align 16
; CHECK-NEXT:    [[LOAD1:%.*]] = load <4 x float>, ptr [[GETELEMENTPTR0]], align 16
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[GETELEMENTPTR1]], align 16
; CHECK-NEXT:    [[TMP1:%.*]] = call <8 x float> @llvm.vector.insert.v8f32.v4f32(<8 x float> poison, <4 x float> [[LOAD1]], i64 0)
; CHECK-NEXT:    [[TMP2:%.*]] = call <8 x float> @llvm.vector.insert.v8f32.v4f32(<8 x float> [[TMP1]], <4 x float> [[LOAD0]], i64 4)
; CHECK-NEXT:    [[TMP3:%.*]] = fmul <8 x float> [[TMP2]], [[TMP0]]
; CHECK-NEXT:    store <8 x float> [[TMP3]], ptr [[GETELEMENTPTR1]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %alloca0 = alloca [12 x float], i32 0, align 16
  %getelementptr0 = getelementptr inbounds i8, ptr %alloca0, i64 32
  %getelementptr1 = getelementptr inbounds i8, ptr %ptr0, i64 128
  %getelementptr2 = getelementptr inbounds i8, ptr %ptr0, i64 144
  %load0 = load <4 x float>, ptr %alloca0, align 16
  %load1 = load <4 x float>, ptr %getelementptr0, align 16
  %load2 = load <4 x float>, ptr %getelementptr1, align 16
  %load3 = load <4 x float>, ptr %getelementptr2, align 16
  %fmul0 = fmul <4 x float> %load1, %load2
  %fmul1 = fmul <4 x float> %load0, %load3
  store <4 x float> %fmul0, ptr %getelementptr1, align 16
  store <4 x float> %fmul1, ptr %getelementptr2, align 16
  ret void
}

define void @test2(ptr %s, i8 %0) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX11_I:%.*]] = getelementptr i8, ptr [[S:%.*]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x i8> poison, i8 [[TMP1]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x i8> [[TMP2]], <2 x i8> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = load <4 x i8>, ptr [[ARRAYIDX11_I]], align 1
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i8> [[TMP4]], <4 x i8> poison, <8 x i32> <i32 2, i32 3, i32 2, i32 3, i32 0, i32 1, i32 0, i32 1>
; CHECK-NEXT:    [[TMP6:%.*]] = call <2 x i8> @llvm.experimental.vp.strided.load.v2i8.p0.i64(ptr align 1 null, i64 4, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i8> [[TMP6]], i32 0
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x i8> [[TMP6]], i8 [[TMP0:%.*]], i32 1
; CHECK-NEXT:    [[TMP10:%.*]] = call <8 x i8> @llvm.vector.insert.v8i8.v2i8(<8 x i8> <i8 0, i8 0, i8 poison, i8 poison, i8 poison, i8 poison, i8 poison, i8 poison>, <2 x i8> [[TMP6]], i64 2)
; CHECK-NEXT:    [[TMP11:%.*]] = call <8 x i8> @llvm.vector.insert.v8i8.v2i8(<8 x i8> [[TMP10]], <2 x i8> [[TMP8]], i64 4)
; CHECK-NEXT:    [[TMP12:%.*]] = call <8 x i8> @llvm.vector.insert.v8i8.v2i8(<8 x i8> [[TMP11]], <2 x i8> [[TMP3]], i64 6)
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq <8 x i8> [[TMP12]], [[TMP5]]
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx11.i = getelementptr i8, ptr %s, i64 1
  %1 = load i8, ptr null, align 1
  %2 = load <2 x i8>, ptr %arrayidx11.i, align 1
  %3 = insertelement <2 x i8> poison, i8 %1, i32 0
  %4 = shufflevector <2 x i8> %3, <2 x i8> poison, <2 x i32> zeroinitializer
  %5 = icmp eq <2 x i8> %4, %2
  %arrayidx11.i.2 = getelementptr i8, ptr %s, i64 3
  %6 = load <2 x i8>, ptr %arrayidx11.i.2, align 1
  %7 = icmp eq <2 x i8> zeroinitializer, %6
  %8 = call <2 x i8> @llvm.experimental.vp.strided.load.v2i8.p0.i64(ptr align 1 null, i64 4, <2 x i1> <i1 true, i1 true>, i32 2)
  %9 = extractelement <2 x i8> %8, i32 0
  %10 = insertelement <2 x i8> %8, i8 %0, i32 1
  %11 = icmp eq <2 x i8> %10, %2
  %12 = icmp eq <2 x i8> %8, %6
  ret void
}

define void @test3(ptr %in_0, ptr %in_1, ptr %out) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds i32, ptr [[IN_0:%.*]], i64 0
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds i32, ptr [[IN_1:%.*]], i64 0
; CHECK-NEXT:    [[GEP8:%.*]] = getelementptr inbounds i32, ptr [[OUT:%.*]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[GEP0]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[GEP4]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = call <16 x float> @llvm.aarch64.neon.fmax.v16f32(<16 x float> [[TMP0]], <16 x float> [[TMP1]])
; CHECK-NEXT:    store <16 x float> [[TMP2]], ptr [[GEP8]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %gep0 = getelementptr inbounds i32, ptr %in_0, i64 0
  %gep1 = getelementptr inbounds i32, ptr %in_0, i64 4
  %gep2 = getelementptr inbounds i32, ptr %in_0, i64 8
  %gep3 = getelementptr inbounds i32, ptr %in_0, i64 12
  %gep4 = getelementptr inbounds i32, ptr %in_1, i64 0
  %gep5 = getelementptr inbounds i32, ptr %in_1, i64 4
  %gep6 = getelementptr inbounds i32, ptr %in_1, i64 8
  %gep7 = getelementptr inbounds i32, ptr %in_1, i64 12
  %load0 = load <4 x float>, ptr %gep0, align 4
  %load1 = load <4 x float>, ptr %gep1, align 4
  %load2 = load <4 x float>, ptr %gep2, align 4
  %load3 = load <4 x float>, ptr %gep3, align 4
  %load4 = load <4 x float>, ptr %gep4, align 4
  %load5 = load <4 x float>, ptr %gep5, align 4
  %load6 = load <4 x float>, ptr %gep6, align 4
  %load7 = load <4 x float>, ptr %gep7, align 4
  %fmax0 = tail call <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float> %load0, <4 x float> %load4)
  %fmax1 = tail call <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float> %load1, <4 x float> %load5)
  %fmax2 = tail call <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float> %load2, <4 x float> %load6)
  %fmax3 = tail call <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float> %load3, <4 x float> %load7)
  %gep8 = getelementptr inbounds i32, ptr %out, i64 0
  %gep9 = getelementptr inbounds i32, ptr %out, i64 4
  %gep10 = getelementptr inbounds i32, ptr %out, i64 8
  %gep11 = getelementptr inbounds i32, ptr %out, i64 12
  store <4 x float> %fmax0, ptr %gep8, align 4
  store <4 x float> %fmax1, ptr %gep9, align 4
  store <4 x float> %fmax2, ptr %gep10, align 4
  store <4 x float> %fmax3, ptr %gep11, align 4
  ret void
}
