; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE

; TODO: Evaluate this on p670, it is possible that p670 scalar is better

; non-profitable case on x280
; profitable case on p470

; This is reduced from GeekBench5 Speech Recognition ptm_mgau.c:195
define float @foo(ptr nocapture noundef readonly %a, ptr nocapture noundef readonly %b, ptr nocapture noundef readonly %var, i32 noundef signext %len, float noundef %thres, float noundef %d) {
; NON-PROFITABLE-LABEL: @foo(
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    [[CMP78:%.*]] = icmp sgt i32 [[LEN:%.*]], 0
; NON-PROFITABLE-NEXT:    [[CMP179:%.*]] = fcmp fast ogt float [[D:%.*]], [[THRES:%.*]]
; NON-PROFITABLE-NEXT:    [[TMP0:%.*]] = select i1 [[CMP78]], i1 [[CMP179]], i1 false
; NON-PROFITABLE-NEXT:    br i1 [[TMP0]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; NON-PROFITABLE:       for.body.preheader:
; NON-PROFITABLE-NEXT:    [[TMP1:%.*]] = zext i32 [[LEN]] to i64
; NON-PROFITABLE-NEXT:    br label [[FOR_BODY:%.*]]
; NON-PROFITABLE:       for.cond.cleanup:
; NON-PROFITABLE-NEXT:    [[D_ADDR_0_LCSSA:%.*]] = phi float [ [[D]], [[ENTRY:%.*]] ], [ [[SUB40:%.*]], [[FOR_BODY]] ]
; NON-PROFITABLE-NEXT:    ret float [[D_ADDR_0_LCSSA]]
; NON-PROFITABLE:       for.body:
; NON-PROFITABLE-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; NON-PROFITABLE-NEXT:    [[A_ADDR_084:%.*]] = phi ptr [ [[A:%.*]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_PTR:%.*]], [[FOR_BODY]] ]
; NON-PROFITABLE-NEXT:    [[B_ADDR_083:%.*]] = phi ptr [ [[B:%.*]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_PTR41:%.*]], [[FOR_BODY]] ]
; NON-PROFITABLE-NEXT:    [[VAR_ADDR_082:%.*]] = phi ptr [ [[VAR:%.*]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_PTR42:%.*]], [[FOR_BODY]] ]
; NON-PROFITABLE-NEXT:    [[D_ADDR_081:%.*]] = phi float [ [[D]], [[FOR_BODY_PREHEADER]] ], [ [[SUB40]], [[FOR_BODY]] ]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 [[INDVARS_IV]]
; NON-PROFITABLE-NEXT:    [[TMP2:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 [[INDVARS_IV]]
; NON-PROFITABLE-NEXT:    [[TMP3:%.*]] = load float, ptr [[ARRAYIDX4]], align 4
; NON-PROFITABLE-NEXT:    [[SUB:%.*]] = fsub fast float [[TMP2]], [[TMP3]]
; NON-PROFITABLE-NEXT:    [[TMP4:%.*]] = or disjoint i64 [[INDVARS_IV]], 1
; NON-PROFITABLE-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 [[TMP4]]
; NON-PROFITABLE-NEXT:    [[TMP5:%.*]] = load float, ptr [[ARRAYIDX7]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 [[TMP4]]
; NON-PROFITABLE-NEXT:    [[TMP6:%.*]] = load float, ptr [[ARRAYIDX10]], align 4
; NON-PROFITABLE-NEXT:    [[SUB11:%.*]] = fsub fast float [[TMP5]], [[TMP6]]
; NON-PROFITABLE-NEXT:    [[TMP7:%.*]] = or disjoint i64 [[INDVARS_IV]], 2
; NON-PROFITABLE-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 [[TMP7]]
; NON-PROFITABLE-NEXT:    [[TMP8:%.*]] = load float, ptr [[ARRAYIDX14]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX17:%.*]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 [[TMP7]]
; NON-PROFITABLE-NEXT:    [[TMP9:%.*]] = load float, ptr [[ARRAYIDX17]], align 4
; NON-PROFITABLE-NEXT:    [[SUB18:%.*]] = fsub fast float [[TMP8]], [[TMP9]]
; NON-PROFITABLE-NEXT:    [[TMP10:%.*]] = or disjoint i64 [[INDVARS_IV]], 3
; NON-PROFITABLE-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 [[TMP10]]
; NON-PROFITABLE-NEXT:    [[TMP11:%.*]] = load float, ptr [[ARRAYIDX21]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 [[TMP10]]
; NON-PROFITABLE-NEXT:    [[TMP12:%.*]] = load float, ptr [[ARRAYIDX24]], align 4
; NON-PROFITABLE-NEXT:    [[SUB25:%.*]] = fsub fast float [[TMP11]], [[TMP12]]
; NON-PROFITABLE-NEXT:    [[TMP13:%.*]] = load float, ptr [[VAR_ADDR_082]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX29:%.*]] = getelementptr inbounds float, ptr [[VAR_ADDR_082]], i64 1
; NON-PROFITABLE-NEXT:    [[TMP14:%.*]] = load float, ptr [[ARRAYIDX29]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX32:%.*]] = getelementptr inbounds float, ptr [[VAR_ADDR_082]], i64 2
; NON-PROFITABLE-NEXT:    [[TMP15:%.*]] = load float, ptr [[ARRAYIDX32]], align 4
; NON-PROFITABLE-NEXT:    [[ARRAYIDX35:%.*]] = getelementptr inbounds float, ptr [[VAR_ADDR_082]], i64 3
; NON-PROFITABLE-NEXT:    [[TMP16:%.*]] = load float, ptr [[ARRAYIDX35]], align 4
; NON-PROFITABLE-NEXT:    [[MUL27:%.*]] = fmul fast float [[SUB]], [[SUB]]
; NON-PROFITABLE-NEXT:    [[MUL27_NEG:%.*]] = fmul fast float [[MUL27]], [[TMP13]]
; NON-PROFITABLE-NEXT:    [[MUL30:%.*]] = fmul fast float [[SUB11]], [[SUB11]]
; NON-PROFITABLE-NEXT:    [[MUL30_NEG:%.*]] = fmul fast float [[MUL30]], [[TMP14]]
; NON-PROFITABLE-NEXT:    [[MUL33:%.*]] = fmul fast float [[SUB18]], [[SUB18]]
; NON-PROFITABLE-NEXT:    [[MUL33_NEG:%.*]] = fmul fast float [[MUL33]], [[TMP15]]
; NON-PROFITABLE-NEXT:    [[MUL36:%.*]] = fmul fast float [[SUB25]], [[SUB25]]
; NON-PROFITABLE-NEXT:    [[MUL36_NEG:%.*]] = fmul fast float [[MUL36]], [[TMP16]]
; NON-PROFITABLE-NEXT:    [[REASS_ADD:%.*]] = fadd fast float [[MUL30_NEG]], [[MUL27_NEG]]
; NON-PROFITABLE-NEXT:    [[REASS_ADD76:%.*]] = fadd fast float [[REASS_ADD]], [[MUL33_NEG]]
; NON-PROFITABLE-NEXT:    [[REASS_ADD77:%.*]] = fadd fast float [[REASS_ADD76]], [[MUL36_NEG]]
; NON-PROFITABLE-NEXT:    [[SUB40]] = fsub fast float [[D_ADDR_081]], [[REASS_ADD77]]
; NON-PROFITABLE-NEXT:    [[ADD_PTR]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 4
; NON-PROFITABLE-NEXT:    [[ADD_PTR41]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 4
; NON-PROFITABLE-NEXT:    [[ADD_PTR42]] = getelementptr inbounds float, ptr [[VAR_ADDR_082]], i64 4
; NON-PROFITABLE-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 4
; NON-PROFITABLE-NEXT:    [[CMP:%.*]] = icmp ult i64 [[INDVARS_IV_NEXT]], [[TMP1]]
; NON-PROFITABLE-NEXT:    [[CMP1:%.*]] = fcmp fast ogt float [[SUB40]], [[THRES]]
; NON-PROFITABLE-NEXT:    [[TMP17:%.*]] = select i1 [[CMP]], i1 [[CMP1]], i1 false
; NON-PROFITABLE-NEXT:    br i1 [[TMP17]], label [[FOR_BODY]], label [[FOR_COND_CLEANUP]]
;
; PROFITABLE-LABEL: @foo(
; PROFITABLE-NEXT:  entry:
; PROFITABLE-NEXT:    [[CMP78:%.*]] = icmp sgt i32 [[LEN:%.*]], 0
; PROFITABLE-NEXT:    [[CMP179:%.*]] = fcmp fast ogt float [[D:%.*]], [[THRES:%.*]]
; PROFITABLE-NEXT:    [[TMP0:%.*]] = select i1 [[CMP78]], i1 [[CMP179]], i1 false
; PROFITABLE-NEXT:    br i1 [[TMP0]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; PROFITABLE:       for.body.preheader:
; PROFITABLE-NEXT:    [[TMP1:%.*]] = zext i32 [[LEN]] to i64
; PROFITABLE-NEXT:    br label [[FOR_BODY:%.*]]
; PROFITABLE:       for.cond.cleanup:
; PROFITABLE-NEXT:    [[D_ADDR_0_LCSSA:%.*]] = phi float [ [[D]], [[ENTRY:%.*]] ], [ [[SUB40:%.*]], [[FOR_BODY]] ]
; PROFITABLE-NEXT:    ret float [[D_ADDR_0_LCSSA]]
; PROFITABLE:       for.body:
; PROFITABLE-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; PROFITABLE-NEXT:    [[A_ADDR_084:%.*]] = phi ptr [ [[A:%.*]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_PTR:%.*]], [[FOR_BODY]] ]
; PROFITABLE-NEXT:    [[B_ADDR_083:%.*]] = phi ptr [ [[B:%.*]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_PTR41:%.*]], [[FOR_BODY]] ]
; PROFITABLE-NEXT:    [[VAR_ADDR_082:%.*]] = phi ptr [ [[VAR:%.*]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_PTR42:%.*]], [[FOR_BODY]] ]
; PROFITABLE-NEXT:    [[D_ADDR_081:%.*]] = phi float [ [[D]], [[FOR_BODY_PREHEADER]] ], [ [[SUB40]], [[FOR_BODY]] ]
; PROFITABLE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 [[INDVARS_IV]]
; PROFITABLE-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 [[INDVARS_IV]]
; PROFITABLE-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[ARRAYIDX]], align 4
; PROFITABLE-NEXT:    [[TMP3:%.*]] = load <4 x float>, ptr [[ARRAYIDX4]], align 4
; PROFITABLE-NEXT:    [[TMP4:%.*]] = fsub fast <4 x float> [[TMP2]], [[TMP3]]
; PROFITABLE-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[VAR_ADDR_082]], align 4
; PROFITABLE-NEXT:    [[TMP6:%.*]] = fmul fast <4 x float> [[TMP4]], [[TMP4]]
; PROFITABLE-NEXT:    [[TMP7:%.*]] = fmul fast <4 x float> [[TMP6]], [[TMP5]]
; PROFITABLE-NEXT:    [[TMP8:%.*]] = call fast float @llvm.vector.reduce.fadd.v4f32(float 0.000000e+00, <4 x float> [[TMP7]])
; PROFITABLE-NEXT:    [[SUB40]] = fsub fast float [[D_ADDR_081]], [[TMP8]]
; PROFITABLE-NEXT:    [[ADD_PTR]] = getelementptr inbounds float, ptr [[A_ADDR_084]], i64 4
; PROFITABLE-NEXT:    [[ADD_PTR41]] = getelementptr inbounds float, ptr [[B_ADDR_083]], i64 4
; PROFITABLE-NEXT:    [[ADD_PTR42]] = getelementptr inbounds float, ptr [[VAR_ADDR_082]], i64 4
; PROFITABLE-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 4
; PROFITABLE-NEXT:    [[CMP:%.*]] = icmp ult i64 [[INDVARS_IV_NEXT]], [[TMP1]]
; PROFITABLE-NEXT:    [[CMP1:%.*]] = fcmp fast ogt float [[SUB40]], [[THRES]]
; PROFITABLE-NEXT:    [[TMP9:%.*]] = select i1 [[CMP]], i1 [[CMP1]], i1 false
; PROFITABLE-NEXT:    br i1 [[TMP9]], label [[FOR_BODY]], label [[FOR_COND_CLEANUP]]
;
entry:
  %cmp78 = icmp sgt i32 %len, 0
  %cmp179 = fcmp fast ogt float %d, %thres
  %0 = select i1 %cmp78, i1 %cmp179, i1 false
  br i1 %0, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %entry
  %1 = zext i32 %len to i64
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %d.addr.0.lcssa = phi float [ %d, %entry ], [ %sub40, %for.body ]
  ret float %d.addr.0.lcssa

for.body:                                         ; preds = %for.body.preheader, %for.body
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.body ]
  %a.addr.084 = phi ptr [ %a, %for.body.preheader ], [ %add.ptr, %for.body ]
  %b.addr.083 = phi ptr [ %b, %for.body.preheader ], [ %add.ptr41, %for.body ]
  %var.addr.082 = phi ptr [ %var, %for.body.preheader ], [ %add.ptr42, %for.body ]
  %d.addr.081 = phi float [ %d, %for.body.preheader ], [ %sub40, %for.body ]
  %arrayidx = getelementptr inbounds float, ptr %a.addr.084, i64 %indvars.iv
  %2 = load float, ptr %arrayidx, align 4
  %arrayidx4 = getelementptr inbounds float, ptr %b.addr.083, i64 %indvars.iv
  %3 = load float, ptr %arrayidx4, align 4
  %sub = fsub fast float %2, %3
  %4 = or disjoint i64 %indvars.iv, 1
  %arrayidx7 = getelementptr inbounds float, ptr %a.addr.084, i64 %4
  %5 = load float, ptr %arrayidx7, align 4
  %arrayidx10 = getelementptr inbounds float, ptr %b.addr.083, i64 %4
  %6 = load float, ptr %arrayidx10, align 4
  %sub11 = fsub fast float %5, %6
  %7 = or disjoint i64 %indvars.iv, 2
  %arrayidx14 = getelementptr inbounds float, ptr %a.addr.084, i64 %7
  %8 = load float, ptr %arrayidx14, align 4
  %arrayidx17 = getelementptr inbounds float, ptr %b.addr.083, i64 %7
  %9 = load float, ptr %arrayidx17, align 4
  %sub18 = fsub fast float %8, %9
  %10 = or disjoint i64 %indvars.iv, 3
  %arrayidx21 = getelementptr inbounds float, ptr %a.addr.084, i64 %10
  %11 = load float, ptr %arrayidx21, align 4
  %arrayidx24 = getelementptr inbounds float, ptr %b.addr.083, i64 %10
  %12 = load float, ptr %arrayidx24, align 4
  %sub25 = fsub fast float %11, %12
  %13 = load float, ptr %var.addr.082, align 4
  %arrayidx29 = getelementptr inbounds float, ptr %var.addr.082, i64 1
  %14 = load float, ptr %arrayidx29, align 4
  %arrayidx32 = getelementptr inbounds float, ptr %var.addr.082, i64 2
  %15 = load float, ptr %arrayidx32, align 4
  %arrayidx35 = getelementptr inbounds float, ptr %var.addr.082, i64 3
  %16 = load float, ptr %arrayidx35, align 4
  %mul27 = fmul fast float %sub, %sub
  %mul27.neg = fmul fast float %mul27, %13
  %mul30 = fmul fast float %sub11, %sub11
  %mul30.neg = fmul fast float %mul30, %14
  %mul33 = fmul fast float %sub18, %sub18
  %mul33.neg = fmul fast float %mul33, %15
  %mul36 = fmul fast float %sub25, %sub25
  %mul36.neg = fmul fast float %mul36, %16
  %reass.add = fadd fast float %mul30.neg, %mul27.neg
  %reass.add76 = fadd fast float %reass.add, %mul33.neg
  %reass.add77 = fadd fast float %reass.add76, %mul36.neg
  %sub40 = fsub fast float %d.addr.081, %reass.add77
  %add.ptr = getelementptr inbounds float, ptr %a.addr.084, i64 4
  %add.ptr41 = getelementptr inbounds float, ptr %b.addr.083, i64 4
  %add.ptr42 = getelementptr inbounds float, ptr %var.addr.082, i64 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 4
  %cmp = icmp ult i64 %indvars.iv.next, %1
  %cmp1 = fcmp fast ogt float %sub40, %thres
  %17 = select i1 %cmp, i1 %cmp1, i1 false
  br i1 %17, label %for.body, label %for.cond.cleanup
}
