; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=slp-vectorizer -S -mtriple=riscv64 -mcpu=sifive-x280 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -passes=slp-vectorizer -S -mtriple=riscv64 -mcpu=sifive-p470 < %s | FileCheck %s --check-prefixes=PROFITABLE
; RUN: opt -passes=slp-vectorizer -S -mtriple=riscv64 -mcpu=sifive-p670 < %s | FileCheck %s --check-prefixes=PROFITABLE

; FIXME: it is profitable on sifive-p470

; Reduced from gkb camera "src/base/image.cpp:413:20: remark: Stores SLP vectorized with cost -10 and with tree size 23"

; Prevent non-profitable SLP store vectorization from x280, p670
define void @foo(ptr align 8 %array, [2 x i64] %black_point.coerce, [2 x i64] %white_point.coerce) {
; NON-PROFITABLE-LABEL: define void @foo
; NON-PROFITABLE-SAME: (ptr align 8 [[ARRAY:%.*]], [2 x i64] [[BLACK_POINT_COERCE:%.*]], [2 x i64] [[WHITE_POINT_COERCE:%.*]]) #[[ATTR0:[0-9]+]] {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    [[WHITE_POINT_COERCE_FCA_0_EXTRACT:%.*]] = extractvalue [2 x i64] [[WHITE_POINT_COERCE]], 0
; NON-PROFITABLE-NEXT:    [[TMP0:%.*]] = extractvalue [2 x i64] [[WHITE_POINT_COERCE]], 1
; NON-PROFITABLE-NEXT:    [[WHITE_POINT_SROA_0_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[WHITE_POINT_COERCE_FCA_0_EXTRACT]] to i32
; NON-PROFITABLE-NEXT:    [[WHITE_POINT_SROA_2_0_EXTRACT_SHIFT:%.*]] = lshr i64 [[WHITE_POINT_COERCE_FCA_0_EXTRACT]], 32
; NON-PROFITABLE-NEXT:    [[WHITE_POINT_SROA_2_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[WHITE_POINT_SROA_2_0_EXTRACT_SHIFT]] to i32
; NON-PROFITABLE-NEXT:    [[TMP_COERCE2_SROA_2_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[TMP0]] to i32
; NON-PROFITABLE-NEXT:    [[TMP1:%.*]] = bitcast i32 [[TMP_COERCE2_SROA_2_0_EXTRACT_TRUNC]] to float
; NON-PROFITABLE-NEXT:    [[TMP2:%.*]] = bitcast i32 [[WHITE_POINT_SROA_2_0_EXTRACT_TRUNC]] to float
; NON-PROFITABLE-NEXT:    [[TMP3:%.*]] = bitcast i32 [[WHITE_POINT_SROA_0_0_EXTRACT_TRUNC]] to float
; NON-PROFITABLE-NEXT:    [[BLACK_POINT_COERCE_FCA_0_EXTRACT:%.*]] = extractvalue [2 x i64] [[BLACK_POINT_COERCE]], 0
; NON-PROFITABLE-NEXT:    [[BLACK_POINT_COERCE_FCA_1_EXTRACT:%.*]] = extractvalue [2 x i64] [[BLACK_POINT_COERCE]], 1
; NON-PROFITABLE-NEXT:    [[BLACK_POINT_SROA_0_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[BLACK_POINT_COERCE_FCA_0_EXTRACT]] to i32
; NON-PROFITABLE-NEXT:    [[BLACK_POINT_SROA_2_0_EXTRACT_SHIFT:%.*]] = lshr i64 [[BLACK_POINT_COERCE_FCA_0_EXTRACT]], 32
; NON-PROFITABLE-NEXT:    [[BLACK_POINT_SROA_2_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[BLACK_POINT_SROA_2_0_EXTRACT_SHIFT]] to i32
; NON-PROFITABLE-NEXT:    [[TMP_COERCE_SROA_2_0_EXTRACT_TRUNC:%.*]] = trunc i64 [[BLACK_POINT_COERCE_FCA_1_EXTRACT]] to i32
; NON-PROFITABLE-NEXT:    [[TMP4:%.*]] = bitcast i32 [[TMP_COERCE_SROA_2_0_EXTRACT_TRUNC]] to float
; NON-PROFITABLE-NEXT:    [[TMP5:%.*]] = bitcast i32 [[BLACK_POINT_SROA_2_0_EXTRACT_TRUNC]] to float
; NON-PROFITABLE-NEXT:    [[TMP6:%.*]] = bitcast i32 [[BLACK_POINT_SROA_0_0_EXTRACT_TRUNC]] to float
; NON-PROFITABLE-NEXT:    [[SUB:%.*]] = fsub fast float [[TMP3]], [[TMP6]]
; NON-PROFITABLE-NEXT:    [[SUB_1:%.*]] = fsub fast float [[TMP2]], [[TMP5]]
; NON-PROFITABLE-NEXT:    [[SUB_2:%.*]] = fsub fast float [[TMP1]], [[TMP4]]
; NON-PROFITABLE-NEXT:    [[DIV:%.*]] = fdiv fast float 1.000000e+00, [[SUB]]
; NON-PROFITABLE-NEXT:    [[DIV_1:%.*]] = fdiv fast float 1.000000e+00, [[SUB_1]]
; NON-PROFITABLE-NEXT:    [[DIV_2:%.*]] = fdiv fast float 1.000000e+00, [[SUB_2]]
; NON-PROFITABLE-NEXT:    [[MUL:%.*]] = fmul fast float [[TMP6]], 2.550000e+02
; NON-PROFITABLE-NEXT:    [[MUL_1:%.*]] = fmul fast float [[TMP5]], 2.550000e+02
; NON-PROFITABLE-NEXT:    [[MUL_2:%.*]] = fmul fast float [[TMP4]], 2.550000e+02
; NON-PROFITABLE-NEXT:    [[ARRAYIDX_0:%.*]] = getelementptr inbounds i8, ptr [[ARRAY]], i64 0
; NON-PROFITABLE-NEXT:    [[A14:%.*]] = load i8, ptr [[ARRAYIDX_0]], align 1
; NON-PROFITABLE-NEXT:    [[CONV26:%.*]] = uitofp i8 [[A14]] to float
; NON-PROFITABLE-NEXT:    [[SUB29:%.*]] = fsub fast float [[CONV26]], [[MUL]]
; NON-PROFITABLE-NEXT:    [[MUL32:%.*]] = fmul fast float [[SUB29]], [[DIV]]
; NON-PROFITABLE-NEXT:    [[CMP1_I:%.*]] = fcmp fast olt float [[MUL32]], 0.000000e+00
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I:%.*]] = select i1 [[CMP1_I]], float 0.000000e+00, float [[MUL32]]
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I70:%.*]] = tail call fast float @llvm.minnum.f32(float [[MINIMUM_VALUE_VALUE_I]], float 2.550000e+02)
; NON-PROFITABLE-NEXT:    [[CONV34:%.*]] = fptoui float [[RETVAL_0_I70]] to i8
; NON-PROFITABLE-NEXT:    store i8 [[CONV34]], ptr [[ARRAYIDX_0]], align 1
; NON-PROFITABLE-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAY]], i64 1
; NON-PROFITABLE-NEXT:    [[A15:%.*]] = load i8, ptr [[ARRAYIDX_1]], align 1
; NON-PROFITABLE-NEXT:    [[CONV26_1:%.*]] = uitofp i8 [[A15]] to float
; NON-PROFITABLE-NEXT:    [[SUB29_1:%.*]] = fsub fast float [[CONV26_1]], [[MUL_1]]
; NON-PROFITABLE-NEXT:    [[MUL32_1:%.*]] = fmul fast float [[SUB29_1]], [[DIV_1]]
; NON-PROFITABLE-NEXT:    [[CMP1_I_1:%.*]] = fcmp fast olt float [[MUL32_1]], 0.000000e+00
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I_1:%.*]] = select i1 [[CMP1_I_1]], float 0.000000e+00, float [[MUL32_1]]
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I70_1:%.*]] = tail call fast float @llvm.minnum.f32(float [[MINIMUM_VALUE_VALUE_I_1]], float 2.550000e+02)
; NON-PROFITABLE-NEXT:    [[CONV34_1:%.*]] = fptoui float [[RETVAL_0_I70_1]] to i8
; NON-PROFITABLE-NEXT:    store i8 [[CONV34_1]], ptr [[ARRAYIDX_1]], align 1
; NON-PROFITABLE-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i8, ptr [[ARRAY]], i64 2
; NON-PROFITABLE-NEXT:    [[A16:%.*]] = load i8, ptr [[ARRAYIDX_2]], align 1
; NON-PROFITABLE-NEXT:    [[CONV26_2:%.*]] = uitofp i8 [[A16]] to float
; NON-PROFITABLE-NEXT:    [[SUB29_2:%.*]] = fsub fast float [[CONV26_2]], [[MUL_2]]
; NON-PROFITABLE-NEXT:    [[MUL32_2:%.*]] = fmul fast float [[SUB29_2]], [[DIV_2]]
; NON-PROFITABLE-NEXT:    [[CMP1_I_2:%.*]] = fcmp fast olt float [[MUL32_2]], 0.000000e+00
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I_2:%.*]] = select i1 [[CMP1_I_2]], float 0.000000e+00, float [[MUL32_2]]
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I70_2:%.*]] = tail call fast float @llvm.minnum.f32(float [[MINIMUM_VALUE_VALUE_I_2]], float 2.550000e+02)
; NON-PROFITABLE-NEXT:    [[CONV34_2:%.*]] = fptoui float [[RETVAL_0_I70_2]] to i8
; NON-PROFITABLE-NEXT:    store i8 [[CONV34_2]], ptr [[ARRAYIDX_2]], align 1
; NON-PROFITABLE-NEXT:    ret void
;
entry:
  %white_point.coerce.fca.0.extract = extractvalue [2 x i64] %white_point.coerce, 0
  %0 = extractvalue [2 x i64] %white_point.coerce, 1

  %white_point.sroa.0.0.extract.trunc = trunc i64 %white_point.coerce.fca.0.extract to i32
  %white_point.sroa.2.0.extract.shift = lshr i64 %white_point.coerce.fca.0.extract, 32
  %white_point.sroa.2.0.extract.trunc = trunc i64 %white_point.sroa.2.0.extract.shift to i32
  %tmp.coerce2.sroa.2.0.extract.trunc = trunc i64 %0 to i32

  %1 = bitcast i32 %tmp.coerce2.sroa.2.0.extract.trunc to float
  %2 = bitcast i32 %white_point.sroa.2.0.extract.trunc to float
  %3 = bitcast i32 %white_point.sroa.0.0.extract.trunc to float

  %black_point.coerce.fca.0.extract = extractvalue [2 x i64] %black_point.coerce, 0
  %black_point.coerce.fca.1.extract = extractvalue [2 x i64] %black_point.coerce, 1

  %black_point.sroa.0.0.extract.trunc = trunc i64 %black_point.coerce.fca.0.extract to i32
  %black_point.sroa.2.0.extract.shift = lshr i64 %black_point.coerce.fca.0.extract, 32
  %black_point.sroa.2.0.extract.trunc = trunc i64 %black_point.sroa.2.0.extract.shift to i32
  %tmp.coerce.sroa.2.0.extract.trunc = trunc i64 %black_point.coerce.fca.1.extract to i32

  %4 = bitcast i32 %tmp.coerce.sroa.2.0.extract.trunc to float
  %5 = bitcast i32 %black_point.sroa.2.0.extract.trunc to float
  %6 = bitcast i32 %black_point.sroa.0.0.extract.trunc to float

  %sub = fsub fast float %3, %6
  %sub.1 = fsub fast float %2, %5
  %sub.2 = fsub fast float %1, %4
  %div = fdiv fast float 1.000000e+00, %sub
  %div.1 = fdiv fast float 1.000000e+00, %sub.1
  %div.2 = fdiv fast float 1.000000e+00, %sub.2
  %mul = fmul fast float %6, 2.550000e+02
  %mul.1 = fmul fast float %5, 2.550000e+02
  %mul.2 = fmul fast float %4, 2.550000e+02

  %arrayidx.0 = getelementptr inbounds i8, ptr %array, i64 0
  %a14 = load i8, ptr %arrayidx.0, align 1
  %conv26 = uitofp i8 %a14 to float
  %sub29 = fsub fast float %conv26, %mul
  %mul32 = fmul fast float %sub29, %div
  %cmp1.i = fcmp fast olt float %mul32, 0.000000e+00
  %minimum_value.value.i = select i1 %cmp1.i, float 0.000000e+00, float %mul32
  %retval.0.i70 = tail call fast float @llvm.minnum.f32(float %minimum_value.value.i, float 2.550000e+02)
  %conv34 = fptoui float %retval.0.i70 to i8
  store i8 %conv34, ptr %arrayidx.0, align 1

  %arrayidx.1 = getelementptr inbounds i8, ptr %array, i64 1
  %a15 = load i8, ptr %arrayidx.1, align 1
  %conv26.1 = uitofp i8 %a15 to float
  %sub29.1 = fsub fast float %conv26.1, %mul.1
  %mul32.1 = fmul fast float %sub29.1, %div.1
  %cmp1.i.1 = fcmp fast olt float %mul32.1, 0.000000e+00
  %minimum_value.value.i.1 = select i1 %cmp1.i.1, float 0.000000e+00, float %mul32.1
  %retval.0.i70.1 = tail call fast float @llvm.minnum.f32(float %minimum_value.value.i.1, float 2.550000e+02)
  %conv34.1 = fptoui float %retval.0.i70.1 to i8
  store i8 %conv34.1, ptr %arrayidx.1, align 1

  %arrayidx.2 = getelementptr inbounds i8, ptr %array, i64 2
  %a16 = load i8, ptr %arrayidx.2, align 1
  %conv26.2 = uitofp i8 %a16 to float
  %sub29.2 = fsub fast float %conv26.2, %mul.2
  %mul32.2 = fmul fast float %sub29.2, %div.2
  %cmp1.i.2 = fcmp fast olt float %mul32.2, 0.000000e+00
  %minimum_value.value.i.2 = select i1 %cmp1.i.2, float 0.000000e+00, float %mul32.2
  %retval.0.i70.2 = tail call fast float @llvm.minnum.f32(float %minimum_value.value.i.2, float 2.550000e+02)
  %conv34.2 = fptoui float %retval.0.i70.2 to i8
  store i8 %conv34.2, ptr %arrayidx.2, align 1

  ret void
}

declare float @llvm.minnum.f32(float, float)

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; PROFITABLE: {{.*}}
