; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=PROFITABLE

%"struct.std::_Deque_iterator" = type { ptr, ptr, ptr, ptr }
%"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data" = type { ptr, i64, %"struct.std::_Deque_iterator", %"struct.std::_Deque_iterator" }

; profitable SLP on p470,p670
; reduced from _ZNSt5dequeIN10xalanc_1_89NameSpaceESaIS1_EED2Ev@ResultNamespacesStack.cpp
define void @_ZNSt5dequeIN10xalanc_1_89NameSpaceESaIS1_EED2Ev(ptr %this, ptr %agg.tmp.i) {
; PROFITABLE-LABEL: define void @_ZNSt5dequeIN10xalanc_1_89NameSpaceESaIS1_EED2Ev
; PROFITABLE-SAME: (ptr [[THIS:%.*]], ptr [[AGG_TMP_I:%.*]]) #[[ATTR0:[0-9]+]] {
; PROFITABLE-NEXT:  entry:
; PROFITABLE-NEXT:    [[_M_START_I:%.*]] = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr [[THIS]], i64 0, i32 2
; PROFITABLE-NEXT:    [[TMP0:%.*]] = load <4 x ptr>, ptr [[_M_START_I]], align 8
; PROFITABLE-NEXT:    store <4 x ptr> [[TMP0]], ptr [[AGG_TMP_I]], align 8
; PROFITABLE-NEXT:    ret void
;
; NON-PROFITABLE-LABEL: define void @_ZNSt5dequeIN10xalanc_1_89NameSpaceESaIS1_EED2Ev
; NON-PROFITABLE-SAME: (ptr [[THIS:%.*]], ptr [[AGG_TMP_I:%.*]]) #[[ATTR0:[0-9]+]] {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    [[_M_START_I:%.*]] = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr [[THIS]], i64 0, i32 2
; NON-PROFITABLE-NEXT:    [[_M_FIRST3_I_I:%.*]] = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr [[THIS]], i64 0, i32 2, i32 1
; NON-PROFITABLE-NEXT:    [[_M_LAST4_I_I:%.*]] = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr [[THIS]], i64 0, i32 2, i32 2
; NON-PROFITABLE-NEXT:    [[_M_NODE5_I_I:%.*]] = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr [[THIS]], i64 0, i32 2, i32 3
; NON-PROFITABLE-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[_M_START_I]], align 8
; NON-PROFITABLE-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[_M_FIRST3_I_I]], align 8
; NON-PROFITABLE-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[_M_LAST4_I_I]], align 8
; NON-PROFITABLE-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[_M_NODE5_I_I]], align 8
; NON-PROFITABLE-NEXT:    [[_M_FIRST_I_I7:%.*]] = getelementptr inbounds %"struct.std::_Deque_iterator", ptr [[AGG_TMP_I]], i64 0, i32 1
; NON-PROFITABLE-NEXT:    [[_M_LAST_I_I9:%.*]] = getelementptr inbounds %"struct.std::_Deque_iterator", ptr [[AGG_TMP_I]], i64 0, i32 2
; NON-PROFITABLE-NEXT:    [[_M_NODE_I_I11:%.*]] = getelementptr inbounds %"struct.std::_Deque_iterator", ptr [[AGG_TMP_I]], i64 0, i32 3
; NON-PROFITABLE-NEXT:    store ptr [[TMP0]], ptr [[AGG_TMP_I]], align 8
; NON-PROFITABLE-NEXT:    store ptr [[TMP1]], ptr [[_M_FIRST_I_I7]], align 8
; NON-PROFITABLE-NEXT:    store ptr [[TMP2]], ptr [[_M_LAST_I_I9]], align 8
; NON-PROFITABLE-NEXT:    store ptr [[TMP3]], ptr [[_M_NODE_I_I11]], align 8
; NON-PROFITABLE-NEXT:    ret void
entry:
  %_M_start.i = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr %this, i64 0, i32 2
  %_M_first3.i.i = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr %this, i64 0, i32 2, i32 1
  %_M_last4.i.i = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr %this, i64 0, i32 2, i32 2
  %_M_node5.i.i = getelementptr inbounds %"struct.std::_Deque_base<xalanc_1_8::NameSpace, std::allocator<xalanc_1_8::NameSpace> >::_Deque_impl_data", ptr %this, i64 0, i32 2, i32 3
  %0 = load ptr, ptr %_M_start.i, align 8
  %1 = load ptr, ptr %_M_first3.i.i, align 8
  %2 = load ptr, ptr %_M_last4.i.i, align 8
  %3 = load ptr, ptr %_M_node5.i.i, align 8
  %_M_first.i.i7 = getelementptr inbounds %"struct.std::_Deque_iterator", ptr %agg.tmp.i, i64 0, i32 1
  %_M_last.i.i9 = getelementptr inbounds %"struct.std::_Deque_iterator", ptr %agg.tmp.i, i64 0, i32 2
  %_M_node.i.i11 = getelementptr inbounds %"struct.std::_Deque_iterator", ptr %agg.tmp.i, i64 0, i32 3
  store ptr %0, ptr %agg.tmp.i, align 8
  store ptr %1, ptr %_M_first.i.i7, align 8
  store ptr %2, ptr %_M_last.i.i9, align 8
  store ptr %3, ptr %_M_node.i.i11, align 8
  ret void
}
