; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=riscv64 -mcpu=sifive-x280 -passes=slp-vectorizer -S -slp-revec -slp-max-reg-size=1024 -slp-threshold=-100 -slp-vectorize-non-power-of-2 %s | FileCheck %s

define void @test(ptr %in0, ptr %in1, ptr %out) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GEP0:%.*]] = getelementptr inbounds float, ptr [[IN0:%.*]], i64 0
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds float, ptr [[IN0]], i64 8
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds float, ptr [[IN1:%.*]], i64 0
; CHECK-NEXT:    [[GEP5:%.*]] = getelementptr inbounds float, ptr [[IN1]], i64 8
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[GEP2]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[GEP5]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = call <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float> [[TMP0]], <4 x float> [[TMP1]])
; CHECK-NEXT:    [[GEP6:%.*]] = getelementptr inbounds float, ptr [[OUT:%.*]], i64 0
; CHECK-NEXT:    [[GEP8:%.*]] = getelementptr inbounds float, ptr [[OUT]], i64 8
; CHECK-NEXT:    [[TMP3:%.*]] = load <8 x float>, ptr [[GEP0]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load <8 x float>, ptr [[GEP3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = call <8 x float> @llvm.aarch64.neon.fmin.v8f32(<8 x float> [[TMP3]], <8 x float> [[TMP4]])
; CHECK-NEXT:    store <8 x float> [[TMP5]], ptr [[GEP6]], align 4
; CHECK-NEXT:    store <4 x float> [[TMP2]], ptr [[GEP8]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %gep0 = getelementptr inbounds float, ptr %in0, i64 0
  %gep1 = getelementptr inbounds float, ptr %in0, i64 4
  %gep2 = getelementptr inbounds float, ptr %in0, i64 8
  %gep3 = getelementptr inbounds float, ptr %in1, i64 0
  %gep4 = getelementptr inbounds float, ptr %in1, i64 4
  %gep5 = getelementptr inbounds float, ptr %in1, i64 8
  %0 = load <4 x float>, ptr %gep0, align 4
  %1 = load <4 x float>, ptr %gep1, align 4
  %2 = load <4 x float>, ptr %gep2, align 4
  %3 = load <4 x float>, ptr %gep3, align 4
  %4 = load <4 x float>, ptr %gep4, align 4
  %5 = load <4 x float>, ptr %gep5, align 4
  %6 = call <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float> %0, <4 x float> %3)
  %7 = call <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float> %1, <4 x float> %4)
  %8 = call <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float> %2, <4 x float> %5)
  %gep6 = getelementptr inbounds float, ptr %out, i64 0
  %gep7 = getelementptr inbounds float, ptr %out, i64 4
  %gep8 = getelementptr inbounds float, ptr %out, i64 8
  store <4 x float> %6, ptr %gep6, align 4
  store <4 x float> %7, ptr %gep7, align 4
  store <4 x float> %8, ptr %gep8, align 4
  ret void
}
