; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=slp-vectorizer -S -mtriple=riscv64-unknown-linux-gnu \
; RUN: -mcpu=sifive-x280o  | FileCheck %s

%struct.ImageParameters = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, float, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr, ptr, i32, ptr, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [9 x [16 x [16 x i16]]], [5 x [16 x [16 x i16]]], [9 x [8 x [8 x i16]]], [2 x [4 x [16 x [16 x i16]]]], [16 x [16 x i16]], [16 x [16 x i32]], ptr, ptr, ptr, ptr, ptr, [1200 x %struct.syntaxelement], ptr, ptr, i32, i32, i32, i32, [4 x [4 x i32]], i32, i32, i32, i32, i32, double, i32, i32, i32, i32, ptr, ptr, ptr, ptr, [15 x i16], i32, i32, i32, i32, i32, i32, i32, i32, [6 x [15 x i32]], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [1 x i32], i32, i32, [2 x i32], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr, i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i32, i32, i32, ptr, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [2 x i32], i32, i32, i32 }
%struct.syntaxelement = type { i32, i32, i32, i32, i32, i32, i32, i32, ptr, ptr }
%struct.macroblock = type { i32, i32, i32, i32, i32, [8 x i32], ptr, ptr, i32, [2 x [4 x [4 x [2 x i32]]]], [16 x i32], [16 x i32], i32, i64, [4 x i32], [4 x i32], i64, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.pic_parameter_set_rbsp_t = type { i32, i32, i32, i32, i32, i32, [8 x i32], i32, i32, i32, [8 x i32], [8 x i32], [8 x i32], i32, i32, i32, ptr, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32 }
%struct.InputParameters = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [8 x [2 x i32]], [8 x [2 x i32]], i32, i32, i32, i32, [200 x i8], [200 x i8], [200 x i8], [200 x i8], [200 x i8], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [1024 x i8], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [200 x i8], [200 x i8], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [200 x i8], i32, i32, ptr, ptr, ptr, ptr, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [8 x i32], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, [6 x double], [200 x i8], i32 }
%struct.storable_picture = type { i32, i32, i32, i32, i32, i32, [6 x [33 x i64]], [6 x [33 x i64]], [6 x [33 x i64]], [6 x [33 x i64]], i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, i32, i32, i32, i32, i32, i32, i32 }

@input = external global ptr
@BlockSAD = external global ptr
@img = external global ptr
@search_setup_done = external global ptr
@search_center_x = external global ptr
@search_center_y = external global ptr
@pos_00 = external global ptr
@max_search_range = external global ptr
@active_pps = external global ptr
@listX = external global [6 x ptr]
@enc_picture = external global ptr
@imgY_org = external global ptr
@PelYline_11 = external global ptr
@spiral_search_x = external global ptr
@spiral_search_y = external global ptr
@byte_abs = external global ptr

declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
declare void @SetupLargerBlocks(i32 signext, i32 signext, i32 signext)

define void @SetupFastFullPelSearch(i16 signext %ref, i32 signext %list) {
; CHECK-LABEL: @SetupFastFullPelSearch(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PMV:%.*]] = alloca [2 x i16], align 2
; CHECK-NEXT:    [[ORIG_BLOCKS:%.*]] = alloca [256 x i16], align 2
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[PMV]])
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 512, ptr nonnull [[ORIG_BLOCKS]])
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @BlockSAD, align 8
; CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[LIST:%.*]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds ptr, ptr [[TMP0]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[ARRAYIDX]], align 8
; CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i16 [[REF:%.*]] to i64
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds ptr, ptr [[TMP1]], i64 [[IDXPROM1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[ARRAYIDX2]], align 8
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds ptr, ptr [[TMP2]], i64 7
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[ARRAYIDX3]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr @max_search_range, align 8
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds ptr, ptr [[TMP4]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[ARRAYIDX5]], align 8
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[IDXPROM1]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = shl nsw i32 [[TMP6]], 1
; CHECK-NEXT:    [[ADD:%.*]] = or i32 [[MUL]], 1
; CHECK-NEXT:    [[MUL10:%.*]] = mul i32 [[ADD]], [[ADD]]
; CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr @img, align 8
; CHECK-NEXT:    [[MBAFFFRAMEFLAG:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS:%.*]], ptr [[TMP7]], i64 0, i32 90
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[MBAFFFRAMEFLAG]], align 4
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[TMP8]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[COND_END:%.*]], label [[LAND_LHS_TRUE:%.*]]
; CHECK:       land.lhs.true:
; CHECK-NEXT:    [[MB_DATA:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP7]], i64 0, i32 51
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[MB_DATA]], align 8
; CHECK-NEXT:    [[CURRENT_MB_NR:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP7]], i64 0, i32 3
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[CURRENT_MB_NR]], align 4
; CHECK-NEXT:    [[IDXPROM11:%.*]] = sext i32 [[TMP10]] to i64
; CHECK-NEXT:    [[MB_FIELD:%.*]] = getelementptr inbounds [[STRUCT_MACROBLOCK:%.*]], ptr [[TMP9]], i64 [[IDXPROM11]], i32 22
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[MB_FIELD]], align 4
; CHECK-NEXT:    [[TOBOOL13_NOT:%.*]] = icmp eq i32 [[TMP11]], 0
; CHECK-NEXT:    br i1 [[TOBOOL13_NOT]], label [[COND_END]], label [[COND_TRUE:%.*]]
; CHECK:       cond.true:
; CHECK-NEXT:    [[TMP12:%.*]] = and i32 [[TMP10]], 1
; CHECK-NEXT:    [[TOBOOL15_NOT:%.*]] = icmp eq i32 [[TMP12]], 0
; CHECK-NEXT:    [[COND:%.*]] = select i1 [[TOBOOL15_NOT]], i32 2, i32 4
; CHECK-NEXT:    br label [[COND_END]]
; CHECK:       cond.end:
; CHECK-NEXT:    [[COND16:%.*]] = phi i32 [ [[COND]], [[COND_TRUE]] ], [ 0, [[LAND_LHS_TRUE]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = load ptr, ptr @active_pps, align 8
; CHECK-NEXT:    [[WEIGHTED_PRED_FLAG:%.*]] = getelementptr inbounds [[STRUCT_PIC_PARAMETER_SET_RBSP_T:%.*]], ptr [[TMP13]], i64 0, i32 19
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[WEIGHTED_PRED_FLAG]], align 4
; CHECK-NEXT:    [[TOBOOL17_NOT:%.*]] = icmp eq i32 [[TMP14]], 0
; CHECK-NEXT:    br i1 [[TOBOOL17_NOT]], label [[LOR_RHS:%.*]], label [[LAND_LHS_TRUE18:%.*]]
; CHECK:       land.lhs.true18:
; CHECK-NEXT:    [[TYPE:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP7]], i64 0, i32 6
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TYPE]], align 4
; CHECK-NEXT:    switch i32 [[TMP15]], label [[LOR_RHS]] [
; CHECK-NEXT:      i32 0, label [[LOR_END_THREAD:%.*]]
; CHECK-NEXT:      i32 3, label [[LOR_END_THREAD]]
; CHECK-NEXT:    ]
; CHECK:       lor.rhs:
; CHECK-NEXT:    [[WEIGHTED_BIPRED_IDC:%.*]] = getelementptr inbounds [[STRUCT_PIC_PARAMETER_SET_RBSP_T]], ptr [[TMP13]], i64 0, i32 20
; CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[WEIGHTED_BIPRED_IDC]], align 4
; CHECK-NEXT:    [[TOBOOL21_NOT:%.*]] = icmp eq i32 [[TMP16]], 0
; CHECK-NEXT:    br i1 [[TOBOOL21_NOT]], label [[LOR_END_THREAD171:%.*]], label [[LOR_END:%.*]]
; CHECK:       lor.end.thread171:
; CHECK-NEXT:    [[ADD24172:%.*]] = add nsw i32 [[COND16]], [[LIST]]
; CHECK-NEXT:    [[IDXPROM25173:%.*]] = sext i32 [[ADD24172]] to i64
; CHECK-NEXT:    [[ARRAYIDX26174:%.*]] = getelementptr inbounds [6 x ptr], ptr @listX, i64 0, i64 [[IDXPROM25173]]
; CHECK-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[ARRAYIDX26174]], align 8
; CHECK-NEXT:    [[ARRAYIDX28175:%.*]] = getelementptr inbounds ptr, ptr [[TMP17]], i64 [[IDXPROM1]]
; CHECK-NEXT:    [[TMP18:%.*]] = load ptr, ptr [[ARRAYIDX28175]], align 8
; CHECK-NEXT:    br label [[IF_ELSE:%.*]]
; CHECK:       lor.end.thread:
; CHECK-NEXT:    [[ADD24167:%.*]] = add nsw i32 [[COND16]], [[LIST]]
; CHECK-NEXT:    [[IDXPROM25168:%.*]] = sext i32 [[ADD24167]] to i64
; CHECK-NEXT:    [[ARRAYIDX26169:%.*]] = getelementptr inbounds [6 x ptr], ptr @listX, i64 0, i64 [[IDXPROM25168]]
; CHECK-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[ARRAYIDX26169]], align 8
; CHECK-NEXT:    [[ARRAYIDX28170:%.*]] = getelementptr inbounds ptr, ptr [[TMP19]], i64 [[IDXPROM1]]
; CHECK-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[ARRAYIDX28170]], align 8
; CHECK-NEXT:    br label [[LAND_LHS_TRUE30:%.*]]
; CHECK:       lor.end:
; CHECK-NEXT:    [[TYPE22:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP7]], i64 0, i32 6
; CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[TYPE22]], align 4
; CHECK-NEXT:    [[CMP23:%.*]] = icmp eq i32 [[TMP21]], 1
; CHECK-NEXT:    [[ADD24:%.*]] = add nsw i32 [[COND16]], [[LIST]]
; CHECK-NEXT:    [[IDXPROM25:%.*]] = sext i32 [[ADD24]] to i64
; CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds [6 x ptr], ptr @listX, i64 0, i64 [[IDXPROM25]]
; CHECK-NEXT:    [[TMP22:%.*]] = load ptr, ptr [[ARRAYIDX26]], align 8
; CHECK-NEXT:    [[ARRAYIDX28:%.*]] = getelementptr inbounds ptr, ptr [[TMP22]], i64 [[IDXPROM1]]
; CHECK-NEXT:    [[TMP23:%.*]] = load ptr, ptr [[ARRAYIDX28]], align 8
; CHECK-NEXT:    br i1 [[CMP23]], label [[LAND_LHS_TRUE30]], label [[IF_ELSE]]
; CHECK:       land.lhs.true30:
; CHECK-NEXT:    [[TMP24:%.*]] = phi ptr [ [[TMP20]], [[LOR_END_THREAD]] ], [ [[TMP23]], [[LOR_END]] ]
; CHECK-NEXT:    [[TMP25:%.*]] = load ptr, ptr @input, align 8
; CHECK-NEXT:    [[USEWEIGHTEDREFERENCEME:%.*]] = getelementptr inbounds [[STRUCT_INPUTPARAMETERS:%.*]], ptr [[TMP25]], i64 0, i32 48
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[USEWEIGHTEDREFERENCEME]], align 4
; CHECK-NEXT:    [[TOBOOL31_NOT:%.*]] = icmp eq i32 [[TMP26]], 0
; CHECK-NEXT:    br i1 [[TOBOOL31_NOT]], label [[IF_ELSE]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[IMGY_11_W:%.*]] = getelementptr inbounds [[STRUCT_STORABLE_PICTURE:%.*]], ptr [[TMP24]], i64 0, i32 27
; CHECK-NEXT:    br label [[IF_END:%.*]]
; CHECK:       if.else:
; CHECK-NEXT:    [[TMP27:%.*]] = phi ptr [ [[TMP24]], [[LAND_LHS_TRUE30]] ], [ [[TMP23]], [[LOR_END]] ], [ [[TMP18]], [[LOR_END_THREAD171]] ]
; CHECK-NEXT:    [[IMGY_11:%.*]] = getelementptr inbounds [[STRUCT_STORABLE_PICTURE]], ptr [[TMP27]], i64 0, i32 26
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP28:%.*]] = phi ptr [ [[TMP24]], [[IF_THEN]] ], [ [[TMP27]], [[IF_ELSE]] ]
; CHECK-NEXT:    [[REF_PIC_0_IN:%.*]] = phi ptr [ [[IMGY_11_W]], [[IF_THEN]] ], [ [[IMGY_11]], [[IF_ELSE]] ]
; CHECK-NEXT:    [[REF_PIC_0:%.*]] = load ptr, ptr [[REF_PIC_0_IN]], align 8
; CHECK-NEXT:    [[SIZE_X:%.*]] = getelementptr inbounds [[STRUCT_STORABLE_PICTURE]], ptr [[TMP28]], i64 0, i32 18
; CHECK-NEXT:    [[TMP29:%.*]] = load i32, ptr [[SIZE_X]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[TMP29]], -17
; CHECK-NEXT:    [[SIZE_Y:%.*]] = getelementptr inbounds [[STRUCT_STORABLE_PICTURE]], ptr [[TMP28]], i64 0, i32 19
; CHECK-NEXT:    [[TMP30:%.*]] = load i32, ptr [[SIZE_Y]], align 4
; CHECK-NEXT:    [[SUB32:%.*]] = add nsw i32 [[TMP30]], -17
; CHECK-NEXT:    [[TMP31:%.*]] = load ptr, ptr @enc_picture, align 8
; CHECK-NEXT:    [[REF_IDX:%.*]] = getelementptr inbounds [[STRUCT_STORABLE_PICTURE]], ptr [[TMP31]], i64 0, i32 32
; CHECK-NEXT:    [[TMP32:%.*]] = load ptr, ptr [[REF_IDX]], align 8
; CHECK-NEXT:    [[MV:%.*]] = getelementptr inbounds [[STRUCT_STORABLE_PICTURE]], ptr [[TMP31]], i64 0, i32 35
; CHECK-NEXT:    [[TMP33:%.*]] = load ptr, ptr [[MV]], align 8
; CHECK-NEXT:    call void @SetMotionVectorPredictor(ptr nonnull [[PMV]], ptr [[TMP32]], ptr [[TMP33]], i16 signext [[REF]], i32 signext [[LIST]], i32 signext 0, i32 signext 0, i32 signext 16, i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[PMV]], align 2
; CHECK-NEXT:    [[TMP35:%.*]] = sdiv i16 [[TMP34]], 4
; CHECK-NEXT:    [[DIV:%.*]] = sext i16 [[TMP35]] to i32
; CHECK-NEXT:    [[TMP36:%.*]] = load ptr, ptr @search_center_x, align 8
; CHECK-NEXT:    [[ARRAYIDX38:%.*]] = getelementptr inbounds ptr, ptr [[TMP36]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP37:%.*]] = load ptr, ptr [[ARRAYIDX38]], align 8
; CHECK-NEXT:    [[ARRAYIDX40:%.*]] = getelementptr inbounds i32, ptr [[TMP37]], i64 [[IDXPROM1]]
; CHECK-NEXT:    store i32 [[DIV]], ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    [[ARRAYIDX41:%.*]] = getelementptr inbounds [2 x i16], ptr [[PMV]], i64 0, i64 1
; CHECK-NEXT:    [[TMP38:%.*]] = load i16, ptr [[ARRAYIDX41]], align 2
; CHECK-NEXT:    [[TMP39:%.*]] = sdiv i16 [[TMP38]], 4
; CHECK-NEXT:    [[DIV43:%.*]] = sext i16 [[TMP39]] to i32
; CHECK-NEXT:    [[TMP40:%.*]] = load ptr, ptr @search_center_y, align 8
; CHECK-NEXT:    [[ARRAYIDX45:%.*]] = getelementptr inbounds ptr, ptr [[TMP40]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP41:%.*]] = load ptr, ptr [[ARRAYIDX45]], align 8
; CHECK-NEXT:    [[ARRAYIDX47:%.*]] = getelementptr inbounds i32, ptr [[TMP41]], i64 [[IDXPROM1]]
; CHECK-NEXT:    store i32 [[DIV43]], ptr [[ARRAYIDX47]], align 4
; CHECK-NEXT:    [[TMP42:%.*]] = load ptr, ptr @input, align 8
; CHECK-NEXT:    [[RDOPT:%.*]] = getelementptr inbounds [[STRUCT_INPUTPARAMETERS]], ptr [[TMP42]], i64 0, i32 85
; CHECK-NEXT:    [[TMP43:%.*]] = load i32, ptr [[RDOPT]], align 4
; CHECK-NEXT:    [[TOBOOL48_NOT:%.*]] = icmp eq i32 [[TMP43]], 0
; CHECK-NEXT:    br i1 [[TOBOOL48_NOT]], label [[IF_THEN49:%.*]], label [[IF_END130:%.*]]
; CHECK:       if.then49:
; CHECK-NEXT:    [[SUB50:%.*]] = sub nsw i32 0, [[TMP6]]
; CHECK-NEXT:    [[TMP44:%.*]] = load i32, ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    [[TMP45:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP6]], i32 [[TMP44]])
; CHECK-NEXT:    [[TMP46:%.*]] = tail call i32 @llvm.smax.i32(i32 [[TMP45]], i32 [[SUB50]])
; CHECK-NEXT:    store i32 [[TMP46]], ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    [[TMP47:%.*]] = load i32, ptr [[ARRAYIDX47]], align 4
; CHECK-NEXT:    [[TMP48:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP6]], i32 [[TMP47]])
; CHECK-NEXT:    [[TMP49:%.*]] = tail call i32 @llvm.smax.i32(i32 [[TMP48]], i32 [[SUB50]])
; CHECK-NEXT:    store i32 [[TMP49]], ptr [[ARRAYIDX47]], align 4
; CHECK-NEXT:    br label [[IF_END130]]
; CHECK:       if.end130:
; CHECK-NEXT:    [[TMP50:%.*]] = load ptr, ptr @img, align 8
; CHECK-NEXT:    [[OPIX_X:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP50]], i64 0, i32 37
; CHECK-NEXT:    [[TMP51:%.*]] = load i32, ptr [[OPIX_X]], align 4
; CHECK-NEXT:    [[TMP52:%.*]] = load i32, ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    [[ADD135:%.*]] = add nsw i32 [[TMP52]], [[TMP51]]
; CHECK-NEXT:    store i32 [[ADD135]], ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    [[OPIX_Y:%.*]] = getelementptr inbounds [[STRUCT_IMAGEPARAMETERS]], ptr [[TMP50]], i64 0, i32 38
; CHECK-NEXT:    [[TMP53:%.*]] = load i32, ptr [[OPIX_Y]], align 4
; CHECK-NEXT:    [[TMP54:%.*]] = load i32, ptr [[ARRAYIDX47]], align 4
; CHECK-NEXT:    [[ADD140:%.*]] = add nsw i32 [[TMP54]], [[TMP53]]
; CHECK-NEXT:    store i32 [[ADD140]], ptr [[ARRAYIDX47]], align 4
; CHECK-NEXT:    [[TMP55:%.*]] = load i32, ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    [[TMP56:%.*]] = load i32, ptr [[OPIX_Y]], align 4
; CHECK-NEXT:    [[TMP57:%.*]] = load i32, ptr [[OPIX_X]], align 4
; CHECK-NEXT:    [[TMP58:%.*]] = load ptr, ptr @imgY_org, align 8
; CHECK-NEXT:    [[TMP59:%.*]] = sext i32 [[TMP57]] to i64
; CHECK-NEXT:    [[TMP60:%.*]] = sext i32 [[TMP56]] to i64
; CHECK-NEXT:    [[TMP61:%.*]] = add nsw i32 [[TMP57]], 15
; CHECK-NEXT:    [[TMP62:%.*]] = sext i32 [[TMP61]] to i64
; CHECK-NEXT:    [[TMP63:%.*]] = add nsw i32 [[TMP56]], 15
; CHECK-NEXT:    [[TMP64:%.*]] = sext i32 [[TMP63]] to i64
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV196:%.*]] = phi i64 [ [[TMP60]], [[IF_END130]] ], [ [[INDVARS_IV_NEXT197:%.*]], [[FOR_INC165:%.*]] ]
; CHECK-NEXT:    [[ORGPTR_0180:%.*]] = phi ptr [ [[ORIG_BLOCKS]], [[IF_END130]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC165]] ]
; CHECK-NEXT:    [[ARRAYIDX162:%.*]] = getelementptr inbounds ptr, ptr [[TMP58]], i64 [[INDVARS_IV196]]
; CHECK-NEXT:    [[TMP65:%.*]] = load ptr, ptr [[ARRAYIDX162]], align 8
; CHECK-NEXT:    br label [[FOR_BODY160:%.*]]
; CHECK:       for.body160:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[TMP59]], [[FOR_BODY]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY160]] ]
; CHECK-NEXT:    [[ORGPTR_1178:%.*]] = phi ptr [ [[ORGPTR_0180]], [[FOR_BODY]] ], [ [[INCDEC_PTR]], [[FOR_BODY160]] ]
; CHECK-NEXT:    [[ARRAYIDX164:%.*]] = getelementptr inbounds i16, ptr [[TMP65]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP66:%.*]] = load i16, ptr [[ARRAYIDX164]], align 2
; CHECK-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i16, ptr [[ORGPTR_1178]], i64 1
; CHECK-NEXT:    store i16 [[TMP66]], ptr [[ORGPTR_1178]], align 2
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[CMP158:%.*]] = icmp slt i64 [[INDVARS_IV]], [[TMP62]]
; CHECK-NEXT:    br i1 [[CMP158]], label [[FOR_BODY160]], label [[FOR_INC165]]
; CHECK:       for.inc165:
; CHECK-NEXT:    [[INDVARS_IV_NEXT197]] = add nsw i64 [[INDVARS_IV196]], 1
; CHECK-NEXT:    [[CMP152:%.*]] = icmp slt i64 [[INDVARS_IV196]], [[TMP64]]
; CHECK-NEXT:    br i1 [[CMP152]], label [[FOR_BODY]], label [[FOR_END167:%.*]]
; CHECK:       for.end167:
; CHECK-NEXT:    [[CMP168_NOT:%.*]] = icmp slt i32 [[TMP55]], [[TMP6]]
; CHECK-NEXT:    [[SUB171:%.*]] = sub nsw i32 [[SUB]], [[TMP6]]
; CHECK-NEXT:    [[CMP172_NOT:%.*]] = icmp sgt i32 [[TMP55]], [[SUB171]]
; CHECK-NEXT:    [[OR_COND163:%.*]] = select i1 [[CMP168_NOT]], i1 true, i1 [[CMP172_NOT]]
; CHECK-NEXT:    [[CMP175_NOT:%.*]] = icmp slt i32 [[ADD140]], [[TMP6]]
; CHECK-NEXT:    [[OR_COND164:%.*]] = select i1 [[OR_COND163]], i1 true, i1 [[CMP175_NOT]]
; CHECK-NEXT:    [[SUB178:%.*]] = sub nsw i32 [[SUB32]], [[TMP6]]
; CHECK-NEXT:    [[CMP179_NOT:%.*]] = icmp sgt i32 [[ADD140]], [[SUB178]]
; CHECK-NEXT:    [[OR_COND165:%.*]] = select i1 [[OR_COND164]], i1 true, i1 [[CMP179_NOT]]
; CHECK-NEXT:    br i1 [[OR_COND165]], label [[IF_END183:%.*]], label [[IF_THEN181:%.*]]
; CHECK:       if.then181:
; CHECK-NEXT:    store ptr @FastLine16Y_11, ptr @PelYline_11, align 8
; CHECK-NEXT:    br label [[IF_END183]]
; CHECK:       if.end183:
; CHECK-NEXT:    [[TMP67:%.*]] = load i32, ptr [[RDOPT]], align 4
; CHECK-NEXT:    [[TOBOOL185_NOT:%.*]] = icmp eq i32 [[TMP67]], 0
; CHECK-NEXT:    br i1 [[TOBOOL185_NOT]], label [[IF_THEN186:%.*]], label [[IF_END183_IF_END213_CRIT_EDGE:%.*]]
; CHECK:       if.end183.if.end213_crit_edge:
; CHECK-NEXT:    [[DOTPRE:%.*]] = call i32 @llvm.umax.i32(i32 [[MUL10]], i32 1)
; CHECK-NEXT:    [[DOTPRE216:%.*]] = zext i32 [[DOTPRE]] to i64
; CHECK-NEXT:    br label [[IF_END213:%.*]]
; CHECK:       if.then186:
; CHECK-NEXT:    [[SUB188:%.*]] = sub nsw i32 [[TMP57]], [[TMP55]]
; CHECK-NEXT:    [[SUB190:%.*]] = sub nsw i32 [[TMP56]], [[ADD140]]
; CHECK-NEXT:    [[TMP68:%.*]] = load ptr, ptr @spiral_search_x, align 8
; CHECK-NEXT:    [[TMP69:%.*]] = load ptr, ptr @spiral_search_y, align 8
; CHECK-NEXT:    [[UMAX:%.*]] = call i32 @llvm.umax.i32(i32 [[MUL10]], i32 1)
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[UMAX]] to i64
; CHECK-NEXT:    br label [[FOR_BODY194:%.*]]
; CHECK:       for.body194:
; CHECK-NEXT:    [[INDVARS_IV199:%.*]] = phi i64 [ 0, [[IF_THEN186]] ], [ [[INDVARS_IV_NEXT200:%.*]], [[FOR_INC210:%.*]] ]
; CHECK-NEXT:    [[ARRAYIDX196:%.*]] = getelementptr inbounds i32, ptr [[TMP68]], i64 [[INDVARS_IV199]]
; CHECK-NEXT:    [[TMP70:%.*]] = load i32, ptr [[ARRAYIDX196]], align 4
; CHECK-NEXT:    [[CMP197:%.*]] = icmp eq i32 [[SUB188]], [[TMP70]]
; CHECK-NEXT:    br i1 [[CMP197]], label [[LAND_LHS_TRUE199:%.*]], label [[FOR_INC210]]
; CHECK:       land.lhs.true199:
; CHECK-NEXT:    [[ARRAYIDX201:%.*]] = getelementptr inbounds i32, ptr [[TMP69]], i64 [[INDVARS_IV199]]
; CHECK-NEXT:    [[TMP71:%.*]] = load i32, ptr [[ARRAYIDX201]], align 4
; CHECK-NEXT:    [[CMP202:%.*]] = icmp eq i32 [[SUB190]], [[TMP71]]
; CHECK-NEXT:    br i1 [[CMP202]], label [[IF_THEN204:%.*]], label [[FOR_INC210]]
; CHECK:       if.then204:
; CHECK-NEXT:    [[TMP72:%.*]] = trunc i64 [[INDVARS_IV199]] to i32
; CHECK-NEXT:    [[TMP73:%.*]] = load ptr, ptr @pos_00, align 8
; CHECK-NEXT:    [[ARRAYIDX206:%.*]] = getelementptr inbounds ptr, ptr [[TMP73]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP74:%.*]] = load ptr, ptr [[ARRAYIDX206]], align 8
; CHECK-NEXT:    [[ARRAYIDX208:%.*]] = getelementptr inbounds i32, ptr [[TMP74]], i64 [[IDXPROM1]]
; CHECK-NEXT:    store i32 [[TMP72]], ptr [[ARRAYIDX208]], align 4
; CHECK-NEXT:    br label [[IF_END213]]
; CHECK:       for.inc210:
; CHECK-NEXT:    [[INDVARS_IV_NEXT200]] = add nuw nsw i64 [[INDVARS_IV199]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT200]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[IF_END213]], label [[FOR_BODY194]]
; CHECK:       if.end213:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT214_PRE_PHI:%.*]] = phi i64 [ [[DOTPRE216]], [[IF_END183_IF_END213_CRIT_EDGE]] ], [ [[WIDE_TRIP_COUNT]], [[IF_THEN204]] ], [ [[WIDE_TRIP_COUNT]], [[FOR_INC210]] ]
; CHECK-NEXT:    br label [[FOR_BODY217:%.*]]
; CHECK:       for.body217:
; CHECK-NEXT:    [[INDVARS_IV210:%.*]] = phi i64 [ 0, [[IF_END213]] ], [ [[INDVARS_IV_NEXT211:%.*]], [[FOR_INC405:%.*]] ]
; CHECK-NEXT:    [[TMP75:%.*]] = load ptr, ptr @spiral_search_y, align 8
; CHECK-NEXT:    [[ARRAYIDX219:%.*]] = getelementptr inbounds i32, ptr [[TMP75]], i64 [[INDVARS_IV210]]
; CHECK-NEXT:    [[TMP76:%.*]] = load i32, ptr [[ARRAYIDX219]], align 4
; CHECK-NEXT:    [[ADD220:%.*]] = add nsw i32 [[TMP76]], [[ADD140]]
; CHECK-NEXT:    [[TMP77:%.*]] = load ptr, ptr @spiral_search_x, align 8
; CHECK-NEXT:    [[ARRAYIDX222:%.*]] = getelementptr inbounds i32, ptr [[TMP77]], i64 [[INDVARS_IV210]]
; CHECK-NEXT:    [[TMP78:%.*]] = load i32, ptr [[ARRAYIDX222]], align 4
; CHECK-NEXT:    [[ADD223:%.*]] = add nsw i32 [[TMP78]], [[TMP55]]
; CHECK-NEXT:    br i1 [[OR_COND165]], label [[IF_THEN225:%.*]], label [[FOR_COND246_PREHEADER:%.*]]
; CHECK:       if.then225:
; CHECK-NEXT:    [[CMP226:%.*]] = icmp sgt i32 [[ADD220]], -1
; CHECK-NEXT:    br i1 [[CMP226]], label [[LAND_LHS_TRUE228:%.*]], label [[IF_ELSE238:%.*]]
; CHECK:       land.lhs.true228:
; CHECK-NEXT:    [[CMP229:%.*]] = icmp sgt i32 [[ADD220]], [[SUB32]]
; CHECK-NEXT:    [[CMP232:%.*]] = icmp slt i32 [[ADD223]], 0
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP229]], i1 true, i1 [[CMP232]]
; CHECK-NEXT:    [[CMP235_NOT:%.*]] = icmp sgt i32 [[ADD223]], [[SUB]]
; CHECK-NEXT:    [[OR_COND166:%.*]] = select i1 [[OR_COND]], i1 true, i1 [[CMP235_NOT]]
; CHECK-NEXT:    br i1 [[OR_COND166]], label [[IF_ELSE238]], label [[IF_END240_SINK_SPLIT:%.*]]
; CHECK:       if.else238:
; CHECK-NEXT:    br label [[IF_END240_SINK_SPLIT]]
; CHECK:       if.end240.sink.split:
; CHECK-NEXT:    [[FASTLINE16Y_11_SINK:%.*]] = phi ptr [ @UMVLine16Y_11, [[IF_ELSE238]] ], [ @FastLine16Y_11, [[LAND_LHS_TRUE228]] ]
; CHECK-NEXT:    store ptr [[FASTLINE16Y_11_SINK]], ptr @PelYline_11, align 8
; CHECK-NEXT:    br label [[FOR_COND246_PREHEADER]]
; CHECK:       for.cond246.preheader:
; CHECK-NEXT:    [[INDVARS_IV203:%.*]] = phi i64 [ [[INDVARS_IV_NEXT204:%.*]], [[FOR_END381:%.*]] ], [ 0, [[IF_END240_SINK_SPLIT]] ], [ 0, [[FOR_BODY217]] ]
; CHECK-NEXT:    [[ORGPTR_2192:%.*]] = phi ptr [ [[UGLYGEP:%.*]], [[FOR_END381]] ], [ [[ORIG_BLOCKS]], [[IF_END240_SINK_SPLIT]] ], [ [[ORIG_BLOCKS]], [[FOR_BODY217]] ]
; CHECK-NEXT:    [[ABS_Y_0191:%.*]] = phi i32 [ [[INC250:%.*]], [[FOR_END381]] ], [ [[ADD220]], [[IF_END240_SINK_SPLIT]] ], [ [[ADD220]], [[FOR_BODY217]] ]
; CHECK-NEXT:    [[BLKY_0189:%.*]] = phi i32 [ [[INC403:%.*]], [[FOR_END381]] ], [ 0, [[IF_END240_SINK_SPLIT]] ], [ 0, [[FOR_BODY217]] ]
; CHECK-NEXT:    br label [[FOR_BODY249:%.*]]
; CHECK:       for.body249:
; CHECK-NEXT:    [[ORGPTR_3188:%.*]] = phi ptr [ [[ORGPTR_2192]], [[FOR_COND246_PREHEADER]] ], [ [[INCDEC_PTR373:%.*]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[Y_1187:%.*]] = phi i32 [ 0, [[FOR_COND246_PREHEADER]] ], [ [[INC380:%.*]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[ABS_Y_1186:%.*]] = phi i32 [ [[ABS_Y_0191]], [[FOR_COND246_PREHEADER]] ], [ [[INC250]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[LINESADBLK0_0185:%.*]] = phi i32 [ 0, [[FOR_COND246_PREHEADER]] ], [ [[ADD282:%.*]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[LINESADBLK1_0184:%.*]] = phi i32 [ 0, [[FOR_COND246_PREHEADER]] ], [ [[ADD314:%.*]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[LINESADBLK3_0183:%.*]] = phi i32 [ 0, [[FOR_COND246_PREHEADER]] ], [ [[ADD378:%.*]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[LINESADBLK2_0182:%.*]] = phi i32 [ 0, [[FOR_COND246_PREHEADER]] ], [ [[ADD346:%.*]], [[FOR_BODY249]] ]
; CHECK-NEXT:    [[TMP79:%.*]] = load ptr, ptr @PelYline_11, align 8
; CHECK-NEXT:    [[INC250]] = add nsw i32 [[ABS_Y_1186]], 1
; CHECK-NEXT:    [[CALL:%.*]] = tail call ptr [[TMP79]](ptr [[REF_PIC_0]], i32 signext [[ABS_Y_1186]], i32 signext [[ADD223]], i32 signext [[TMP30]], i32 signext [[TMP29]])
; CHECK-NEXT:    [[TMP80:%.*]] = load ptr, ptr @byte_abs, align 8
; CHECK-NEXT:    [[INCDEC_PTR251:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 1
; CHECK-NEXT:    [[TMP81:%.*]] = load i16, ptr [[CALL]], align 2
; CHECK-NEXT:    [[CONV252:%.*]] = zext i16 [[TMP81]] to i64
; CHECK-NEXT:    [[INCDEC_PTR253:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 1
; CHECK-NEXT:    [[TMP82:%.*]] = load i16, ptr [[ORGPTR_3188]], align 2
; CHECK-NEXT:    [[CONV254:%.*]] = zext i16 [[TMP82]] to i64
; CHECK-NEXT:    [[SUB255:%.*]] = sub nsw i64 [[CONV252]], [[CONV254]]
; CHECK-NEXT:    [[ARRAYIDX257:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB255]]
; CHECK-NEXT:    [[TMP83:%.*]] = load i32, ptr [[ARRAYIDX257]], align 4
; CHECK-NEXT:    [[ADD258:%.*]] = add nsw i32 [[TMP83]], [[LINESADBLK0_0185]]
; CHECK-NEXT:    [[INCDEC_PTR259:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 2
; CHECK-NEXT:    [[TMP84:%.*]] = load i16, ptr [[INCDEC_PTR251]], align 2
; CHECK-NEXT:    [[CONV260:%.*]] = zext i16 [[TMP84]] to i64
; CHECK-NEXT:    [[INCDEC_PTR261:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 2
; CHECK-NEXT:    [[TMP85:%.*]] = load i16, ptr [[INCDEC_PTR253]], align 2
; CHECK-NEXT:    [[CONV262:%.*]] = zext i16 [[TMP85]] to i64
; CHECK-NEXT:    [[SUB263:%.*]] = sub nsw i64 [[CONV260]], [[CONV262]]
; CHECK-NEXT:    [[ARRAYIDX265:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB263]]
; CHECK-NEXT:    [[TMP86:%.*]] = load i32, ptr [[ARRAYIDX265]], align 4
; CHECK-NEXT:    [[ADD266:%.*]] = add nsw i32 [[ADD258]], [[TMP86]]
; CHECK-NEXT:    [[INCDEC_PTR267:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 3
; CHECK-NEXT:    [[TMP87:%.*]] = load i16, ptr [[INCDEC_PTR259]], align 2
; CHECK-NEXT:    [[CONV268:%.*]] = zext i16 [[TMP87]] to i64
; CHECK-NEXT:    [[INCDEC_PTR269:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 3
; CHECK-NEXT:    [[TMP88:%.*]] = load i16, ptr [[INCDEC_PTR261]], align 2
; CHECK-NEXT:    [[CONV270:%.*]] = zext i16 [[TMP88]] to i64
; CHECK-NEXT:    [[SUB271:%.*]] = sub nsw i64 [[CONV268]], [[CONV270]]
; CHECK-NEXT:    [[ARRAYIDX273:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB271]]
; CHECK-NEXT:    [[TMP89:%.*]] = load i32, ptr [[ARRAYIDX273]], align 4
; CHECK-NEXT:    [[ADD274:%.*]] = add nsw i32 [[ADD266]], [[TMP89]]
; CHECK-NEXT:    [[INCDEC_PTR275:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 4
; CHECK-NEXT:    [[TMP90:%.*]] = load i16, ptr [[INCDEC_PTR267]], align 2
; CHECK-NEXT:    [[CONV276:%.*]] = zext i16 [[TMP90]] to i64
; CHECK-NEXT:    [[INCDEC_PTR277:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 4
; CHECK-NEXT:    [[TMP91:%.*]] = load i16, ptr [[INCDEC_PTR269]], align 2
; CHECK-NEXT:    [[CONV278:%.*]] = zext i16 [[TMP91]] to i64
; CHECK-NEXT:    [[SUB279:%.*]] = sub nsw i64 [[CONV276]], [[CONV278]]
; CHECK-NEXT:    [[ARRAYIDX281:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB279]]
; CHECK-NEXT:    [[TMP92:%.*]] = load i32, ptr [[ARRAYIDX281]], align 4
; CHECK-NEXT:    [[ADD282]] = add nsw i32 [[ADD274]], [[TMP92]]
; CHECK-NEXT:    [[INCDEC_PTR283:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 5
; CHECK-NEXT:    [[TMP93:%.*]] = load i16, ptr [[INCDEC_PTR275]], align 2
; CHECK-NEXT:    [[CONV284:%.*]] = zext i16 [[TMP93]] to i64
; CHECK-NEXT:    [[INCDEC_PTR285:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 5
; CHECK-NEXT:    [[TMP94:%.*]] = load i16, ptr [[INCDEC_PTR277]], align 2
; CHECK-NEXT:    [[CONV286:%.*]] = zext i16 [[TMP94]] to i64
; CHECK-NEXT:    [[SUB287:%.*]] = sub nsw i64 [[CONV284]], [[CONV286]]
; CHECK-NEXT:    [[ARRAYIDX289:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB287]]
; CHECK-NEXT:    [[TMP95:%.*]] = load i32, ptr [[ARRAYIDX289]], align 4
; CHECK-NEXT:    [[ADD290:%.*]] = add nsw i32 [[TMP95]], [[LINESADBLK1_0184]]
; CHECK-NEXT:    [[INCDEC_PTR291:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 6
; CHECK-NEXT:    [[TMP96:%.*]] = load i16, ptr [[INCDEC_PTR283]], align 2
; CHECK-NEXT:    [[CONV292:%.*]] = zext i16 [[TMP96]] to i64
; CHECK-NEXT:    [[INCDEC_PTR293:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 6
; CHECK-NEXT:    [[TMP97:%.*]] = load i16, ptr [[INCDEC_PTR285]], align 2
; CHECK-NEXT:    [[CONV294:%.*]] = zext i16 [[TMP97]] to i64
; CHECK-NEXT:    [[SUB295:%.*]] = sub nsw i64 [[CONV292]], [[CONV294]]
; CHECK-NEXT:    [[ARRAYIDX297:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB295]]
; CHECK-NEXT:    [[TMP98:%.*]] = load i32, ptr [[ARRAYIDX297]], align 4
; CHECK-NEXT:    [[ADD298:%.*]] = add nsw i32 [[ADD290]], [[TMP98]]
; CHECK-NEXT:    [[INCDEC_PTR299:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 7
; CHECK-NEXT:    [[TMP99:%.*]] = load i16, ptr [[INCDEC_PTR291]], align 2
; CHECK-NEXT:    [[CONV300:%.*]] = zext i16 [[TMP99]] to i64
; CHECK-NEXT:    [[INCDEC_PTR301:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 7
; CHECK-NEXT:    [[TMP100:%.*]] = load i16, ptr [[INCDEC_PTR293]], align 2
; CHECK-NEXT:    [[CONV302:%.*]] = zext i16 [[TMP100]] to i64
; CHECK-NEXT:    [[SUB303:%.*]] = sub nsw i64 [[CONV300]], [[CONV302]]
; CHECK-NEXT:    [[ARRAYIDX305:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB303]]
; CHECK-NEXT:    [[TMP101:%.*]] = load i32, ptr [[ARRAYIDX305]], align 4
; CHECK-NEXT:    [[ADD306:%.*]] = add nsw i32 [[ADD298]], [[TMP101]]
; CHECK-NEXT:    [[INCDEC_PTR307:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 8
; CHECK-NEXT:    [[TMP102:%.*]] = load i16, ptr [[INCDEC_PTR299]], align 2
; CHECK-NEXT:    [[CONV308:%.*]] = zext i16 [[TMP102]] to i64
; CHECK-NEXT:    [[INCDEC_PTR309:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 8
; CHECK-NEXT:    [[TMP103:%.*]] = load i16, ptr [[INCDEC_PTR301]], align 2
; CHECK-NEXT:    [[CONV310:%.*]] = zext i16 [[TMP103]] to i64
; CHECK-NEXT:    [[SUB311:%.*]] = sub nsw i64 [[CONV308]], [[CONV310]]
; CHECK-NEXT:    [[ARRAYIDX313:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB311]]
; CHECK-NEXT:    [[TMP104:%.*]] = load i32, ptr [[ARRAYIDX313]], align 4
; CHECK-NEXT:    [[ADD314]] = add nsw i32 [[ADD306]], [[TMP104]]
; CHECK-NEXT:    [[INCDEC_PTR315:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 9
; CHECK-NEXT:    [[TMP105:%.*]] = load i16, ptr [[INCDEC_PTR307]], align 2
; CHECK-NEXT:    [[CONV316:%.*]] = zext i16 [[TMP105]] to i64
; CHECK-NEXT:    [[INCDEC_PTR317:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 9
; CHECK-NEXT:    [[TMP106:%.*]] = load i16, ptr [[INCDEC_PTR309]], align 2
; CHECK-NEXT:    [[CONV318:%.*]] = zext i16 [[TMP106]] to i64
; CHECK-NEXT:    [[SUB319:%.*]] = sub nsw i64 [[CONV316]], [[CONV318]]
; CHECK-NEXT:    [[ARRAYIDX321:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB319]]
; CHECK-NEXT:    [[TMP107:%.*]] = load i32, ptr [[ARRAYIDX321]], align 4
; CHECK-NEXT:    [[ADD322:%.*]] = add nsw i32 [[TMP107]], [[LINESADBLK2_0182]]
; CHECK-NEXT:    [[INCDEC_PTR323:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 10
; CHECK-NEXT:    [[TMP108:%.*]] = load i16, ptr [[INCDEC_PTR315]], align 2
; CHECK-NEXT:    [[CONV324:%.*]] = zext i16 [[TMP108]] to i64
; CHECK-NEXT:    [[INCDEC_PTR325:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 10
; CHECK-NEXT:    [[TMP109:%.*]] = load i16, ptr [[INCDEC_PTR317]], align 2
; CHECK-NEXT:    [[CONV326:%.*]] = zext i16 [[TMP109]] to i64
; CHECK-NEXT:    [[SUB327:%.*]] = sub nsw i64 [[CONV324]], [[CONV326]]
; CHECK-NEXT:    [[ARRAYIDX329:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB327]]
; CHECK-NEXT:    [[TMP110:%.*]] = load i32, ptr [[ARRAYIDX329]], align 4
; CHECK-NEXT:    [[ADD330:%.*]] = add nsw i32 [[ADD322]], [[TMP110]]
; CHECK-NEXT:    [[INCDEC_PTR331:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 11
; CHECK-NEXT:    [[TMP111:%.*]] = load i16, ptr [[INCDEC_PTR323]], align 2
; CHECK-NEXT:    [[CONV332:%.*]] = zext i16 [[TMP111]] to i64
; CHECK-NEXT:    [[INCDEC_PTR333:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 11
; CHECK-NEXT:    [[TMP112:%.*]] = load i16, ptr [[INCDEC_PTR325]], align 2
; CHECK-NEXT:    [[CONV334:%.*]] = zext i16 [[TMP112]] to i64
; CHECK-NEXT:    [[SUB335:%.*]] = sub nsw i64 [[CONV332]], [[CONV334]]
; CHECK-NEXT:    [[ARRAYIDX337:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB335]]
; CHECK-NEXT:    [[TMP113:%.*]] = load i32, ptr [[ARRAYIDX337]], align 4
; CHECK-NEXT:    [[ADD338:%.*]] = add nsw i32 [[ADD330]], [[TMP113]]
; CHECK-NEXT:    [[INCDEC_PTR339:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 12
; CHECK-NEXT:    [[TMP114:%.*]] = load i16, ptr [[INCDEC_PTR331]], align 2
; CHECK-NEXT:    [[CONV340:%.*]] = zext i16 [[TMP114]] to i64
; CHECK-NEXT:    [[INCDEC_PTR341:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 12
; CHECK-NEXT:    [[TMP115:%.*]] = load i16, ptr [[INCDEC_PTR333]], align 2
; CHECK-NEXT:    [[CONV342:%.*]] = zext i16 [[TMP115]] to i64
; CHECK-NEXT:    [[SUB343:%.*]] = sub nsw i64 [[CONV340]], [[CONV342]]
; CHECK-NEXT:    [[ARRAYIDX345:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB343]]
; CHECK-NEXT:    [[TMP116:%.*]] = load i32, ptr [[ARRAYIDX345]], align 4
; CHECK-NEXT:    [[ADD346]] = add nsw i32 [[ADD338]], [[TMP116]]
; CHECK-NEXT:    [[INCDEC_PTR347:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 13
; CHECK-NEXT:    [[TMP117:%.*]] = load i16, ptr [[INCDEC_PTR339]], align 2
; CHECK-NEXT:    [[CONV348:%.*]] = zext i16 [[TMP117]] to i64
; CHECK-NEXT:    [[INCDEC_PTR349:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 13
; CHECK-NEXT:    [[TMP118:%.*]] = load i16, ptr [[INCDEC_PTR341]], align 2
; CHECK-NEXT:    [[CONV350:%.*]] = zext i16 [[TMP118]] to i64
; CHECK-NEXT:    [[SUB351:%.*]] = sub nsw i64 [[CONV348]], [[CONV350]]
; CHECK-NEXT:    [[ARRAYIDX353:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB351]]
; CHECK-NEXT:    [[TMP119:%.*]] = load i32, ptr [[ARRAYIDX353]], align 4
; CHECK-NEXT:    [[ADD354:%.*]] = add nsw i32 [[TMP119]], [[LINESADBLK3_0183]]
; CHECK-NEXT:    [[INCDEC_PTR355:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 14
; CHECK-NEXT:    [[TMP120:%.*]] = load i16, ptr [[INCDEC_PTR347]], align 2
; CHECK-NEXT:    [[CONV356:%.*]] = zext i16 [[TMP120]] to i64
; CHECK-NEXT:    [[INCDEC_PTR357:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 14
; CHECK-NEXT:    [[TMP121:%.*]] = load i16, ptr [[INCDEC_PTR349]], align 2
; CHECK-NEXT:    [[CONV358:%.*]] = zext i16 [[TMP121]] to i64
; CHECK-NEXT:    [[SUB359:%.*]] = sub nsw i64 [[CONV356]], [[CONV358]]
; CHECK-NEXT:    [[ARRAYIDX361:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB359]]
; CHECK-NEXT:    [[TMP122:%.*]] = load i32, ptr [[ARRAYIDX361]], align 4
; CHECK-NEXT:    [[ADD362:%.*]] = add nsw i32 [[ADD354]], [[TMP122]]
; CHECK-NEXT:    [[INCDEC_PTR363:%.*]] = getelementptr inbounds i16, ptr [[CALL]], i64 15
; CHECK-NEXT:    [[TMP123:%.*]] = load i16, ptr [[INCDEC_PTR355]], align 2
; CHECK-NEXT:    [[CONV364:%.*]] = zext i16 [[TMP123]] to i64
; CHECK-NEXT:    [[INCDEC_PTR365:%.*]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 15
; CHECK-NEXT:    [[TMP124:%.*]] = load i16, ptr [[INCDEC_PTR357]], align 2
; CHECK-NEXT:    [[CONV366:%.*]] = zext i16 [[TMP124]] to i64
; CHECK-NEXT:    [[SUB367:%.*]] = sub nsw i64 [[CONV364]], [[CONV366]]
; CHECK-NEXT:    [[ARRAYIDX369:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB367]]
; CHECK-NEXT:    [[TMP125:%.*]] = load i32, ptr [[ARRAYIDX369]], align 4
; CHECK-NEXT:    [[ADD370:%.*]] = add nsw i32 [[ADD362]], [[TMP125]]
; CHECK-NEXT:    [[TMP126:%.*]] = load i16, ptr [[INCDEC_PTR363]], align 2
; CHECK-NEXT:    [[CONV372:%.*]] = zext i16 [[TMP126]] to i64
; CHECK-NEXT:    [[INCDEC_PTR373]] = getelementptr inbounds i16, ptr [[ORGPTR_3188]], i64 16
; CHECK-NEXT:    [[TMP127:%.*]] = load i16, ptr [[INCDEC_PTR365]], align 2
; CHECK-NEXT:    [[CONV374:%.*]] = zext i16 [[TMP127]] to i64
; CHECK-NEXT:    [[SUB375:%.*]] = sub nsw i64 [[CONV372]], [[CONV374]]
; CHECK-NEXT:    [[ARRAYIDX377:%.*]] = getelementptr inbounds i32, ptr [[TMP80]], i64 [[SUB375]]
; CHECK-NEXT:    [[TMP128:%.*]] = load i32, ptr [[ARRAYIDX377]], align 4
; CHECK-NEXT:    [[ADD378]] = add nsw i32 [[ADD370]], [[TMP128]]
; CHECK-NEXT:    [[INC380]] = add nuw nsw i32 [[Y_1187]], 1
; CHECK-NEXT:    [[EXITCOND202_NOT:%.*]] = icmp eq i32 [[INC380]], 4
; CHECK-NEXT:    br i1 [[EXITCOND202_NOT]], label [[FOR_END381]], label [[FOR_BODY249]]
; CHECK:       for.end381:
; CHECK-NEXT:    [[UGLYGEP]] = getelementptr i8, ptr [[ORGPTR_2192]], i64 128
; CHECK-NEXT:    [[TMP129:%.*]] = or i64 [[INDVARS_IV203]], 1
; CHECK-NEXT:    [[ARRAYIDX384:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i64 [[INDVARS_IV203]]
; CHECK-NEXT:    [[TMP130:%.*]] = load ptr, ptr [[ARRAYIDX384]], align 8
; CHECK-NEXT:    [[ARRAYIDX386:%.*]] = getelementptr inbounds i32, ptr [[TMP130]], i64 [[INDVARS_IV210]]
; CHECK-NEXT:    store i32 [[ADD282]], ptr [[ARRAYIDX386]], align 4
; CHECK-NEXT:    [[TMP131:%.*]] = or i64 [[INDVARS_IV203]], 2
; CHECK-NEXT:    [[ARRAYIDX389:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i64 [[TMP129]]
; CHECK-NEXT:    [[TMP132:%.*]] = load ptr, ptr [[ARRAYIDX389]], align 8
; CHECK-NEXT:    [[ARRAYIDX391:%.*]] = getelementptr inbounds i32, ptr [[TMP132]], i64 [[INDVARS_IV210]]
; CHECK-NEXT:    store i32 [[ADD314]], ptr [[ARRAYIDX391]], align 4
; CHECK-NEXT:    [[TMP133:%.*]] = or i64 [[INDVARS_IV203]], 3
; CHECK-NEXT:    [[ARRAYIDX394:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i64 [[TMP131]]
; CHECK-NEXT:    [[TMP134:%.*]] = load ptr, ptr [[ARRAYIDX394]], align 8
; CHECK-NEXT:    [[ARRAYIDX396:%.*]] = getelementptr inbounds i32, ptr [[TMP134]], i64 [[INDVARS_IV210]]
; CHECK-NEXT:    store i32 [[ADD346]], ptr [[ARRAYIDX396]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT204]] = add nuw nsw i64 [[INDVARS_IV203]], 4
; CHECK-NEXT:    [[ARRAYIDX399:%.*]] = getelementptr inbounds ptr, ptr [[TMP3]], i64 [[TMP133]]
; CHECK-NEXT:    [[TMP135:%.*]] = load ptr, ptr [[ARRAYIDX399]], align 8
; CHECK-NEXT:    [[ARRAYIDX401:%.*]] = getelementptr inbounds i32, ptr [[TMP135]], i64 [[INDVARS_IV210]]
; CHECK-NEXT:    store i32 [[ADD378]], ptr [[ARRAYIDX401]], align 4
; CHECK-NEXT:    [[INC403]] = add nuw nsw i32 [[BLKY_0189]], 1
; CHECK-NEXT:    [[EXITCOND209_NOT:%.*]] = icmp eq i32 [[INC403]], 4
; CHECK-NEXT:    br i1 [[EXITCOND209_NOT]], label [[FOR_INC405]], label [[FOR_COND246_PREHEADER]]
; CHECK:       for.inc405:
; CHECK-NEXT:    [[INDVARS_IV_NEXT211]] = add nuw nsw i64 [[INDVARS_IV210]], 1
; CHECK-NEXT:    [[EXITCOND215_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT211]], [[WIDE_TRIP_COUNT214_PRE_PHI]]
; CHECK-NEXT:    br i1 [[EXITCOND215_NOT]], label [[FOR_END407:%.*]], label [[FOR_BODY217]]
; CHECK:       for.end407:
; CHECK-NEXT:    [[CONV408:%.*]] = sext i16 [[REF]] to i32
; CHECK-NEXT:    tail call void @SetupLargerBlocks(i32 signext [[LIST]], i32 signext [[CONV408]], i32 signext [[MUL10]])
; CHECK-NEXT:    [[TMP136:%.*]] = load ptr, ptr @search_setup_done, align 8
; CHECK-NEXT:    [[ARRAYIDX410:%.*]] = getelementptr inbounds ptr, ptr [[TMP136]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP137:%.*]] = load ptr, ptr [[ARRAYIDX410]], align 8
; CHECK-NEXT:    [[ARRAYIDX412:%.*]] = getelementptr inbounds i32, ptr [[TMP137]], i64 [[IDXPROM1]]
; CHECK-NEXT:    store i32 1, ptr [[ARRAYIDX412]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 512, ptr nonnull [[ORIG_BLOCKS]])
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[PMV]])
; CHECK-NEXT:    ret void
;
entry:
  %pmv = alloca [2 x i16]
  %orig_blocks = alloca [256 x i16]
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %pmv)
  call void @llvm.lifetime.start.p0(i64 512, ptr nonnull %orig_blocks)
  %0 = load ptr, ptr @BlockSAD
  %idxprom = sext i32 %list to i64
  %arrayidx = getelementptr inbounds ptr, ptr %0, i64 %idxprom
  %1 = load ptr, ptr %arrayidx
  %idxprom1 = sext i16 %ref to i64
  %arrayidx2 = getelementptr inbounds ptr, ptr %1, i64 %idxprom1
  %2 = load ptr, ptr %arrayidx2
  %arrayidx3 = getelementptr inbounds ptr, ptr %2, i64 7
  %3 = load ptr, ptr %arrayidx3
  %4 = load ptr, ptr @max_search_range
  %arrayidx5 = getelementptr inbounds ptr, ptr %4, i64 %idxprom
  %5 = load ptr, ptr %arrayidx5
  %arrayidx7 = getelementptr inbounds i32, ptr %5, i64 %idxprom1
  %6 = load i32, ptr %arrayidx7
  %mul = shl nsw i32 %6, 1
  %add = or i32 %mul, 1
  %mul10 = mul i32 %add, %add
  %7 = load ptr, ptr @img
  %MbaffFrameFlag = getelementptr inbounds %struct.ImageParameters, ptr %7, i64 0, i32 90
  %8 = load i32, ptr %MbaffFrameFlag
  %tobool.not = icmp eq i32 %8, 0
  br i1 %tobool.not, label %cond.end, label %land.lhs.true

land.lhs.true:
  %mb_data = getelementptr inbounds %struct.ImageParameters, ptr %7, i64 0, i32 51
  %9 = load ptr, ptr %mb_data
  %current_mb_nr = getelementptr inbounds %struct.ImageParameters, ptr %7, i64 0, i32 3
  %10 = load i32, ptr %current_mb_nr
  %idxprom11 = sext i32 %10 to i64
  %mb_field = getelementptr inbounds %struct.macroblock, ptr %9, i64 %idxprom11, i32 22
  %11 = load i32, ptr %mb_field
  %tobool13.not = icmp eq i32 %11, 0
  br i1 %tobool13.not, label %cond.end, label %cond.true

cond.true:
  %12 = and i32 %10, 1
  %tobool15.not = icmp eq i32 %12, 0
  %cond = select i1 %tobool15.not, i32 2, i32 4
  br label %cond.end

cond.end:
  %cond16 = phi i32 [ %cond, %cond.true ], [ 0, %land.lhs.true ], [ 0, %entry ]
  %13 = load ptr, ptr @active_pps
  %weighted_pred_flag = getelementptr inbounds %struct.pic_parameter_set_rbsp_t, ptr %13, i64 0, i32 19
  %14 = load i32, ptr %weighted_pred_flag
  %tobool17.not = icmp eq i32 %14, 0
  br i1 %tobool17.not, label %lor.rhs, label %land.lhs.true18

land.lhs.true18:
  %type = getelementptr inbounds %struct.ImageParameters, ptr %7, i64 0, i32 6
  %15 = load i32, ptr %type
  switch i32 %15, label %lor.rhs [
  i32 0, label %lor.end.thread
  i32 3, label %lor.end.thread
  ]

lor.rhs:
  %weighted_bipred_idc = getelementptr inbounds %struct.pic_parameter_set_rbsp_t, ptr %13, i64 0, i32 20
  %16 = load i32, ptr %weighted_bipred_idc
  %tobool21.not = icmp eq i32 %16, 0
  br i1 %tobool21.not, label %lor.end.thread171, label %lor.end

lor.end.thread171:
  %add24172 = add nsw i32 %cond16, %list
  %idxprom25173 = sext i32 %add24172 to i64
  %arrayidx26174 = getelementptr inbounds [6 x ptr], ptr @listX, i64 0, i64 %idxprom25173
  %17 = load ptr, ptr %arrayidx26174
  %arrayidx28175 = getelementptr inbounds ptr, ptr %17, i64 %idxprom1
  %18 = load ptr, ptr %arrayidx28175
  br label %if.else

lor.end.thread:
  %add24167 = add nsw i32 %cond16, %list
  %idxprom25168 = sext i32 %add24167 to i64
  %arrayidx26169 = getelementptr inbounds [6 x ptr], ptr @listX, i64 0, i64 %idxprom25168
  %19 = load ptr, ptr %arrayidx26169
  %arrayidx28170 = getelementptr inbounds ptr, ptr %19, i64 %idxprom1
  %20 = load ptr, ptr %arrayidx28170
  br label %land.lhs.true30

lor.end:
  %type22 = getelementptr inbounds %struct.ImageParameters, ptr %7, i64 0, i32 6
  %21 = load i32, ptr %type22
  %cmp23 = icmp eq i32 %21, 1
  %add24 = add nsw i32 %cond16, %list
  %idxprom25 = sext i32 %add24 to i64
  %arrayidx26 = getelementptr inbounds [6 x ptr], ptr @listX, i64 0, i64 %idxprom25
  %22 = load ptr, ptr %arrayidx26
  %arrayidx28 = getelementptr inbounds ptr, ptr %22, i64 %idxprom1
  %23 = load ptr, ptr %arrayidx28
  br i1 %cmp23, label %land.lhs.true30, label %if.else

land.lhs.true30:
  %24 = phi ptr [ %20, %lor.end.thread ], [ %23, %lor.end ]
  %25 = load ptr, ptr @input
  %UseWeightedReferenceME = getelementptr inbounds %struct.InputParameters, ptr %25, i64 0, i32 48
  %26 = load i32, ptr %UseWeightedReferenceME
  %tobool31.not = icmp eq i32 %26, 0
  br i1 %tobool31.not, label %if.else, label %if.then

if.then:
  %imgY_11_w = getelementptr inbounds %struct.storable_picture, ptr %24, i64 0, i32 27
  br label %if.end

if.else:
  %27 = phi ptr [ %24, %land.lhs.true30 ], [ %23, %lor.end ], [ %18, %lor.end.thread171 ]
  %imgY_11 = getelementptr inbounds %struct.storable_picture, ptr %27, i64 0, i32 26
  br label %if.end

if.end:
  %28 = phi ptr [ %24, %if.then ], [ %27, %if.else ]
  %ref_pic.0.in = phi ptr [ %imgY_11_w, %if.then ], [ %imgY_11, %if.else ]
  %ref_pic.0 = load ptr, ptr %ref_pic.0.in
  %size_x = getelementptr inbounds %struct.storable_picture, ptr %28, i64 0, i32 18
  %29 = load i32, ptr %size_x
  %sub = add nsw i32 %29, -17
  %size_y = getelementptr inbounds %struct.storable_picture, ptr %28, i64 0, i32 19
  %30 = load i32, ptr %size_y
  %sub32 = add nsw i32 %30, -17
  %31 = load ptr, ptr @enc_picture
  %ref_idx = getelementptr inbounds %struct.storable_picture, ptr %31, i64 0, i32 32
  %32 = load ptr, ptr %ref_idx
  %mv = getelementptr inbounds %struct.storable_picture, ptr %31, i64 0, i32 35
  %33 = load ptr, ptr %mv
  call void @SetMotionVectorPredictor(ptr nonnull %pmv, ptr %32, ptr %33, i16 signext %ref, i32 signext %list, i32 signext 0, i32 signext 0, i32 signext 16, i32 16)
  %34 = load i16, ptr %pmv
  %35 = sdiv i16 %34, 4
  %div = sext i16 %35 to i32
  %36 = load ptr, ptr @search_center_x
  %arrayidx38 = getelementptr inbounds ptr, ptr %36, i64 %idxprom
  %37 = load ptr, ptr %arrayidx38
  %arrayidx40 = getelementptr inbounds i32, ptr %37, i64 %idxprom1
  store i32 %div, ptr %arrayidx40
  %arrayidx41 = getelementptr inbounds [2 x i16], ptr %pmv, i64 0, i64 1
  %38 = load i16, ptr %arrayidx41
  %39 = sdiv i16 %38, 4
  %div43 = sext i16 %39 to i32
  %40 = load ptr, ptr @search_center_y
  %arrayidx45 = getelementptr inbounds ptr, ptr %40, i64 %idxprom
  %41 = load ptr, ptr %arrayidx45
  %arrayidx47 = getelementptr inbounds i32, ptr %41, i64 %idxprom1
  store i32 %div43, ptr %arrayidx47
  %42 = load ptr, ptr @input
  %rdopt = getelementptr inbounds %struct.InputParameters, ptr %42, i64 0, i32 85
  %43 = load i32, ptr %rdopt
  %tobool48.not = icmp eq i32 %43, 0
  br i1 %tobool48.not, label %if.then49, label %if.end130

if.then49:
  %sub50 = sub nsw i32 0, %6
  %44 = load i32, ptr %arrayidx40
  %45 = tail call i32 @llvm.smin.i32(i32 %6, i32 %44)
  %46 = tail call i32 @llvm.smax.i32(i32 %45, i32 %sub50)
  store i32 %46, ptr %arrayidx40
  %47 = load i32, ptr %arrayidx47
  %48 = tail call i32 @llvm.smin.i32(i32 %6, i32 %47)
  %49 = tail call i32 @llvm.smax.i32(i32 %48, i32 %sub50)
  store i32 %49, ptr %arrayidx47
  br label %if.end130

if.end130:
  %50 = load ptr, ptr @img
  %opix_x = getelementptr inbounds %struct.ImageParameters, ptr %50, i64 0, i32 37
  %51 = load i32, ptr %opix_x
  %52 = load i32, ptr %arrayidx40
  %add135 = add nsw i32 %52, %51
  store i32 %add135, ptr %arrayidx40
  %opix_y = getelementptr inbounds %struct.ImageParameters, ptr %50, i64 0, i32 38
  %53 = load i32, ptr %opix_y
  %54 = load i32, ptr %arrayidx47
  %add140 = add nsw i32 %54, %53
  store i32 %add140, ptr %arrayidx47
  %55 = load i32, ptr %arrayidx40
  %56 = load i32, ptr %opix_y
  %57 = load i32, ptr %opix_x
  %58 = load ptr, ptr @imgY_org
  %59 = sext i32 %57 to i64
  %60 = sext i32 %56 to i64
  %61 = add nsw i32 %57, 15
  %62 = sext i32 %61 to i64
  %63 = add nsw i32 %56, 15
  %64 = sext i32 %63 to i64
  br label %for.body

for.body:
  %indvars.iv196 = phi i64 [ %60, %if.end130 ], [ %indvars.iv.next197, %for.inc165 ]
  %orgptr.0180 = phi ptr [ %orig_blocks, %if.end130 ], [ %incdec.ptr, %for.inc165 ]
  %arrayidx162 = getelementptr inbounds ptr, ptr %58, i64 %indvars.iv196
  %65 = load ptr, ptr %arrayidx162
  br label %for.body160

for.body160:
  %indvars.iv = phi i64 [ %59, %for.body ], [ %indvars.iv.next, %for.body160 ]
  %orgptr.1178 = phi ptr [ %orgptr.0180, %for.body ], [ %incdec.ptr, %for.body160 ]
  %arrayidx164 = getelementptr inbounds i16, ptr %65, i64 %indvars.iv
  %66 = load i16, ptr %arrayidx164
  %incdec.ptr = getelementptr inbounds i16, ptr %orgptr.1178, i64 1
  store i16 %66, ptr %orgptr.1178
  %indvars.iv.next = add nsw i64 %indvars.iv, 1
  %cmp158 = icmp slt i64 %indvars.iv, %62
  br i1 %cmp158, label %for.body160, label %for.inc165

for.inc165:
  %indvars.iv.next197 = add nsw i64 %indvars.iv196, 1
  %cmp152 = icmp slt i64 %indvars.iv196, %64
  br i1 %cmp152, label %for.body, label %for.end167

for.end167:
  %cmp168.not = icmp slt i32 %55, %6
  %sub171 = sub nsw i32 %sub, %6
  %cmp172.not = icmp sgt i32 %55, %sub171
  %or.cond163 = select i1 %cmp168.not, i1 true, i1 %cmp172.not
  %cmp175.not = icmp slt i32 %add140, %6
  %or.cond164 = select i1 %or.cond163, i1 true, i1 %cmp175.not
  %sub178 = sub nsw i32 %sub32, %6
  %cmp179.not = icmp sgt i32 %add140, %sub178
  %or.cond165 = select i1 %or.cond164, i1 true, i1 %cmp179.not
  br i1 %or.cond165, label %if.end183, label %if.then181

if.then181:
  store ptr @FastLine16Y_11, ptr @PelYline_11
  br label %if.end183

if.end183:
  %67 = load i32, ptr %rdopt
  %tobool185.not = icmp eq i32 %67, 0
  br i1 %tobool185.not, label %if.then186, label %if.end183.if.end213_crit_edge

if.end183.if.end213_crit_edge:
  %.pre = call i32 @llvm.umax.i32(i32 %mul10, i32 1)
  %.pre216 = zext i32 %.pre to i64
  br label %if.end213

if.then186:
  %sub188 = sub nsw i32 %57, %55
  %sub190 = sub nsw i32 %56, %add140
  %68 = load ptr, ptr @spiral_search_x
  %69 = load ptr, ptr @spiral_search_y
  %umax = call i32 @llvm.umax.i32(i32 %mul10, i32 1)
  %wide.trip.count = zext i32 %umax to i64
  br label %for.body194

for.body194:
  %indvars.iv199 = phi i64 [ 0, %if.then186 ], [ %indvars.iv.next200, %for.inc210 ]
  %arrayidx196 = getelementptr inbounds i32, ptr %68, i64 %indvars.iv199
  %70 = load i32, ptr %arrayidx196
  %cmp197 = icmp eq i32 %sub188, %70
  br i1 %cmp197, label %land.lhs.true199, label %for.inc210

land.lhs.true199:
  %arrayidx201 = getelementptr inbounds i32, ptr %69, i64 %indvars.iv199
  %71 = load i32, ptr %arrayidx201
  %cmp202 = icmp eq i32 %sub190, %71
  br i1 %cmp202, label %if.then204, label %for.inc210

if.then204:
  %72 = trunc i64 %indvars.iv199 to i32
  %73 = load ptr, ptr @pos_00
  %arrayidx206 = getelementptr inbounds ptr, ptr %73, i64 %idxprom
  %74 = load ptr, ptr %arrayidx206
  %arrayidx208 = getelementptr inbounds i32, ptr %74, i64 %idxprom1
  store i32 %72, ptr %arrayidx208
  br label %if.end213

for.inc210:
  %indvars.iv.next200 = add nuw nsw i64 %indvars.iv199, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next200, %wide.trip.count
  br i1 %exitcond.not, label %if.end213, label %for.body194

if.end213:
  %wide.trip.count214.pre-phi = phi i64 [ %.pre216, %if.end183.if.end213_crit_edge ], [ %wide.trip.count, %if.then204 ], [ %wide.trip.count, %for.inc210 ]
  br label %for.body217

for.body217:
  %indvars.iv210 = phi i64 [ 0, %if.end213 ], [ %indvars.iv.next211, %for.inc405 ]
  %75 = load ptr, ptr @spiral_search_y
  %arrayidx219 = getelementptr inbounds i32, ptr %75, i64 %indvars.iv210
  %76 = load i32, ptr %arrayidx219
  %add220 = add nsw i32 %76, %add140
  %77 = load ptr, ptr @spiral_search_x
  %arrayidx222 = getelementptr inbounds i32, ptr %77, i64 %indvars.iv210
  %78 = load i32, ptr %arrayidx222
  %add223 = add nsw i32 %78, %55
  br i1 %or.cond165, label %if.then225, label %for.cond246.preheader

if.then225:
  %cmp226 = icmp sgt i32 %add220, -1
  br i1 %cmp226, label %land.lhs.true228, label %if.else238

land.lhs.true228:
  %cmp229 = icmp sgt i32 %add220, %sub32
  %cmp232 = icmp slt i32 %add223, 0
  %or.cond = select i1 %cmp229, i1 true, i1 %cmp232
  %cmp235.not = icmp sgt i32 %add223, %sub
  %or.cond166 = select i1 %or.cond, i1 true, i1 %cmp235.not
  br i1 %or.cond166, label %if.else238, label %if.end240.sink.split

if.else238:
  br label %if.end240.sink.split

if.end240.sink.split:
  %FastLine16Y_11.sink = phi ptr [ @UMVLine16Y_11, %if.else238 ], [ @FastLine16Y_11, %land.lhs.true228 ]
  store ptr %FastLine16Y_11.sink, ptr @PelYline_11
  br label %for.cond246.preheader

for.cond246.preheader:
  %indvars.iv203 = phi i64 [ %indvars.iv.next204, %for.end381 ], [ 0, %if.end240.sink.split ], [ 0, %for.body217 ]
  %orgptr.2192 = phi ptr [ %uglygep, %for.end381 ], [ %orig_blocks, %if.end240.sink.split ], [ %orig_blocks, %for.body217 ]
  %abs_y.0191 = phi i32 [ %inc250, %for.end381 ], [ %add220, %if.end240.sink.split ], [ %add220, %for.body217 ]
  %blky.0189 = phi i32 [ %inc403, %for.end381 ], [ 0, %if.end240.sink.split ], [ 0, %for.body217 ]
  br label %for.body249

for.body249:
  %orgptr.3188 = phi ptr [ %orgptr.2192, %for.cond246.preheader ], [ %incdec.ptr373, %for.body249 ]
  %y.1187 = phi i32 [ 0, %for.cond246.preheader ], [ %inc380, %for.body249 ]
  %abs_y.1186 = phi i32 [ %abs_y.0191, %for.cond246.preheader ], [ %inc250, %for.body249 ]
  %LineSadBlk0.0185 = phi i32 [ 0, %for.cond246.preheader ], [ %add282, %for.body249 ]
  %LineSadBlk1.0184 = phi i32 [ 0, %for.cond246.preheader ], [ %add314, %for.body249 ]
  %LineSadBlk3.0183 = phi i32 [ 0, %for.cond246.preheader ], [ %add378, %for.body249 ]
  %LineSadBlk2.0182 = phi i32 [ 0, %for.cond246.preheader ], [ %add346, %for.body249 ]
  %79 = load ptr, ptr @PelYline_11
  %inc250 = add nsw i32 %abs_y.1186, 1
  %call = tail call ptr %79(ptr %ref_pic.0, i32 signext %abs_y.1186, i32 signext %add223, i32 signext %30, i32 signext %29)
  %80 = load ptr, ptr @byte_abs
  %incdec.ptr251 = getelementptr inbounds i16, ptr %call, i64 1
  %81 = load i16, ptr %call
  %conv252 = zext i16 %81 to i64
  %incdec.ptr253 = getelementptr inbounds i16, ptr %orgptr.3188, i64 1
  %82 = load i16, ptr %orgptr.3188
  %conv254 = zext i16 %82 to i64
  %sub255 = sub nsw i64 %conv252, %conv254
  %arrayidx257 = getelementptr inbounds i32, ptr %80, i64 %sub255
  %83 = load i32, ptr %arrayidx257
  %add258 = add nsw i32 %83, %LineSadBlk0.0185
  %incdec.ptr259 = getelementptr inbounds i16, ptr %call, i64 2
  %84 = load i16, ptr %incdec.ptr251
  %conv260 = zext i16 %84 to i64
  %incdec.ptr261 = getelementptr inbounds i16, ptr %orgptr.3188, i64 2
  %85 = load i16, ptr %incdec.ptr253
  %conv262 = zext i16 %85 to i64
  %sub263 = sub nsw i64 %conv260, %conv262
  %arrayidx265 = getelementptr inbounds i32, ptr %80, i64 %sub263
  %86 = load i32, ptr %arrayidx265
  %add266 = add nsw i32 %add258, %86
  %incdec.ptr267 = getelementptr inbounds i16, ptr %call, i64 3
  %87 = load i16, ptr %incdec.ptr259
  %conv268 = zext i16 %87 to i64
  %incdec.ptr269 = getelementptr inbounds i16, ptr %orgptr.3188, i64 3
  %88 = load i16, ptr %incdec.ptr261
  %conv270 = zext i16 %88 to i64
  %sub271 = sub nsw i64 %conv268, %conv270
  %arrayidx273 = getelementptr inbounds i32, ptr %80, i64 %sub271
  %89 = load i32, ptr %arrayidx273
  %add274 = add nsw i32 %add266, %89
  %incdec.ptr275 = getelementptr inbounds i16, ptr %call, i64 4
  %90 = load i16, ptr %incdec.ptr267
  %conv276 = zext i16 %90 to i64
  %incdec.ptr277 = getelementptr inbounds i16, ptr %orgptr.3188, i64 4
  %91 = load i16, ptr %incdec.ptr269
  %conv278 = zext i16 %91 to i64
  %sub279 = sub nsw i64 %conv276, %conv278
  %arrayidx281 = getelementptr inbounds i32, ptr %80, i64 %sub279
  %92 = load i32, ptr %arrayidx281
  %add282 = add nsw i32 %add274, %92
  %incdec.ptr283 = getelementptr inbounds i16, ptr %call, i64 5
  %93 = load i16, ptr %incdec.ptr275
  %conv284 = zext i16 %93 to i64
  %incdec.ptr285 = getelementptr inbounds i16, ptr %orgptr.3188, i64 5
  %94 = load i16, ptr %incdec.ptr277
  %conv286 = zext i16 %94 to i64
  %sub287 = sub nsw i64 %conv284, %conv286
  %arrayidx289 = getelementptr inbounds i32, ptr %80, i64 %sub287
  %95 = load i32, ptr %arrayidx289
  %add290 = add nsw i32 %95, %LineSadBlk1.0184
  %incdec.ptr291 = getelementptr inbounds i16, ptr %call, i64 6
  %96 = load i16, ptr %incdec.ptr283
  %conv292 = zext i16 %96 to i64
  %incdec.ptr293 = getelementptr inbounds i16, ptr %orgptr.3188, i64 6
  %97 = load i16, ptr %incdec.ptr285
  %conv294 = zext i16 %97 to i64
  %sub295 = sub nsw i64 %conv292, %conv294
  %arrayidx297 = getelementptr inbounds i32, ptr %80, i64 %sub295
  %98 = load i32, ptr %arrayidx297
  %add298 = add nsw i32 %add290, %98
  %incdec.ptr299 = getelementptr inbounds i16, ptr %call, i64 7
  %99 = load i16, ptr %incdec.ptr291
  %conv300 = zext i16 %99 to i64
  %incdec.ptr301 = getelementptr inbounds i16, ptr %orgptr.3188, i64 7
  %100 = load i16, ptr %incdec.ptr293
  %conv302 = zext i16 %100 to i64
  %sub303 = sub nsw i64 %conv300, %conv302
  %arrayidx305 = getelementptr inbounds i32, ptr %80, i64 %sub303
  %101 = load i32, ptr %arrayidx305
  %add306 = add nsw i32 %add298, %101
  %incdec.ptr307 = getelementptr inbounds i16, ptr %call, i64 8
  %102 = load i16, ptr %incdec.ptr299
  %conv308 = zext i16 %102 to i64
  %incdec.ptr309 = getelementptr inbounds i16, ptr %orgptr.3188, i64 8
  %103 = load i16, ptr %incdec.ptr301
  %conv310 = zext i16 %103 to i64
  %sub311 = sub nsw i64 %conv308, %conv310
  %arrayidx313 = getelementptr inbounds i32, ptr %80, i64 %sub311
  %104 = load i32, ptr %arrayidx313
  %add314 = add nsw i32 %add306, %104
  %incdec.ptr315 = getelementptr inbounds i16, ptr %call, i64 9
  %105 = load i16, ptr %incdec.ptr307
  %conv316 = zext i16 %105 to i64
  %incdec.ptr317 = getelementptr inbounds i16, ptr %orgptr.3188, i64 9
  %106 = load i16, ptr %incdec.ptr309
  %conv318 = zext i16 %106 to i64
  %sub319 = sub nsw i64 %conv316, %conv318
  %arrayidx321 = getelementptr inbounds i32, ptr %80, i64 %sub319
  %107 = load i32, ptr %arrayidx321
  %add322 = add nsw i32 %107, %LineSadBlk2.0182
  %incdec.ptr323 = getelementptr inbounds i16, ptr %call, i64 10
  %108 = load i16, ptr %incdec.ptr315
  %conv324 = zext i16 %108 to i64
  %incdec.ptr325 = getelementptr inbounds i16, ptr %orgptr.3188, i64 10
  %109 = load i16, ptr %incdec.ptr317
  %conv326 = zext i16 %109 to i64
  %sub327 = sub nsw i64 %conv324, %conv326
  %arrayidx329 = getelementptr inbounds i32, ptr %80, i64 %sub327
  %110 = load i32, ptr %arrayidx329
  %add330 = add nsw i32 %add322, %110
  %incdec.ptr331 = getelementptr inbounds i16, ptr %call, i64 11
  %111 = load i16, ptr %incdec.ptr323
  %conv332 = zext i16 %111 to i64
  %incdec.ptr333 = getelementptr inbounds i16, ptr %orgptr.3188, i64 11
  %112 = load i16, ptr %incdec.ptr325
  %conv334 = zext i16 %112 to i64
  %sub335 = sub nsw i64 %conv332, %conv334
  %arrayidx337 = getelementptr inbounds i32, ptr %80, i64 %sub335
  %113 = load i32, ptr %arrayidx337
  %add338 = add nsw i32 %add330, %113
  %incdec.ptr339 = getelementptr inbounds i16, ptr %call, i64 12
  %114 = load i16, ptr %incdec.ptr331
  %conv340 = zext i16 %114 to i64
  %incdec.ptr341 = getelementptr inbounds i16, ptr %orgptr.3188, i64 12
  %115 = load i16, ptr %incdec.ptr333
  %conv342 = zext i16 %115 to i64
  %sub343 = sub nsw i64 %conv340, %conv342
  %arrayidx345 = getelementptr inbounds i32, ptr %80, i64 %sub343
  %116 = load i32, ptr %arrayidx345
  %add346 = add nsw i32 %add338, %116
  %incdec.ptr347 = getelementptr inbounds i16, ptr %call, i64 13
  %117 = load i16, ptr %incdec.ptr339
  %conv348 = zext i16 %117 to i64
  %incdec.ptr349 = getelementptr inbounds i16, ptr %orgptr.3188, i64 13
  %118 = load i16, ptr %incdec.ptr341
  %conv350 = zext i16 %118 to i64
  %sub351 = sub nsw i64 %conv348, %conv350
  %arrayidx353 = getelementptr inbounds i32, ptr %80, i64 %sub351
  %119 = load i32, ptr %arrayidx353
  %add354 = add nsw i32 %119, %LineSadBlk3.0183
  %incdec.ptr355 = getelementptr inbounds i16, ptr %call, i64 14
  %120 = load i16, ptr %incdec.ptr347
  %conv356 = zext i16 %120 to i64
  %incdec.ptr357 = getelementptr inbounds i16, ptr %orgptr.3188, i64 14
  %121 = load i16, ptr %incdec.ptr349
  %conv358 = zext i16 %121 to i64
  %sub359 = sub nsw i64 %conv356, %conv358
  %arrayidx361 = getelementptr inbounds i32, ptr %80, i64 %sub359
  %122 = load i32, ptr %arrayidx361
  %add362 = add nsw i32 %add354, %122
  %incdec.ptr363 = getelementptr inbounds i16, ptr %call, i64 15
  %123 = load i16, ptr %incdec.ptr355
  %conv364 = zext i16 %123 to i64
  %incdec.ptr365 = getelementptr inbounds i16, ptr %orgptr.3188, i64 15
  %124 = load i16, ptr %incdec.ptr357
  %conv366 = zext i16 %124 to i64
  %sub367 = sub nsw i64 %conv364, %conv366
  %arrayidx369 = getelementptr inbounds i32, ptr %80, i64 %sub367
  %125 = load i32, ptr %arrayidx369
  %add370 = add nsw i32 %add362, %125
  %126 = load i16, ptr %incdec.ptr363
  %conv372 = zext i16 %126 to i64
  %incdec.ptr373 = getelementptr inbounds i16, ptr %orgptr.3188, i64 16
  %127 = load i16, ptr %incdec.ptr365
  %conv374 = zext i16 %127 to i64
  %sub375 = sub nsw i64 %conv372, %conv374
  %arrayidx377 = getelementptr inbounds i32, ptr %80, i64 %sub375
  %128 = load i32, ptr %arrayidx377
  %add378 = add nsw i32 %add370, %128
  %inc380 = add nuw nsw i32 %y.1187, 1
  %exitcond202.not = icmp eq i32 %inc380, 4
  br i1 %exitcond202.not, label %for.end381, label %for.body249

for.end381:
  %uglygep = getelementptr i8, ptr %orgptr.2192, i64 128
  %129 = or i64 %indvars.iv203, 1
  %arrayidx384 = getelementptr inbounds ptr, ptr %3, i64 %indvars.iv203
  %130 = load ptr, ptr %arrayidx384
  %arrayidx386 = getelementptr inbounds i32, ptr %130, i64 %indvars.iv210
  store i32 %add282, ptr %arrayidx386
  %131 = or i64 %indvars.iv203, 2
  %arrayidx389 = getelementptr inbounds ptr, ptr %3, i64 %129
  %132 = load ptr, ptr %arrayidx389
  %arrayidx391 = getelementptr inbounds i32, ptr %132, i64 %indvars.iv210
  store i32 %add314, ptr %arrayidx391
  %133 = or i64 %indvars.iv203, 3
  %arrayidx394 = getelementptr inbounds ptr, ptr %3, i64 %131
  %134 = load ptr, ptr %arrayidx394
  %arrayidx396 = getelementptr inbounds i32, ptr %134, i64 %indvars.iv210
  store i32 %add346, ptr %arrayidx396
  %indvars.iv.next204 = add nuw nsw i64 %indvars.iv203, 4
  %arrayidx399 = getelementptr inbounds ptr, ptr %3, i64 %133
  %135 = load ptr, ptr %arrayidx399
  %arrayidx401 = getelementptr inbounds i32, ptr %135, i64 %indvars.iv210
  store i32 %add378, ptr %arrayidx401
  %inc403 = add nuw nsw i32 %blky.0189, 1
  %exitcond209.not = icmp eq i32 %inc403, 4
  br i1 %exitcond209.not, label %for.inc405, label %for.cond246.preheader

for.inc405:
  %indvars.iv.next211 = add nuw nsw i64 %indvars.iv210, 1
  %exitcond215.not = icmp eq i64 %indvars.iv.next211, %wide.trip.count214.pre-phi
  br i1 %exitcond215.not, label %for.end407, label %for.body217

for.end407:
  %conv408 = sext i16 %ref to i32
  tail call void @SetupLargerBlocks(i32 signext %list, i32 signext %conv408, i32 signext %mul10)
  %136 = load ptr, ptr @search_setup_done
  %arrayidx410 = getelementptr inbounds ptr, ptr %136, i64 %idxprom
  %137 = load ptr, ptr %arrayidx410
  %arrayidx412 = getelementptr inbounds i32, ptr %137, i64 %idxprom1
  store i32 1, ptr %arrayidx412
  call void @llvm.lifetime.end.p0(i64 512, ptr nonnull %orig_blocks)
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %pmv)
  ret void
}

declare void @SetMotionVectorPredictor(ptr nocapture writeonly, ptr nocapture readonly, ptr nocapture readonly, i16 signext, i32 signext, i32 signext, i32 signext, i32 signext, i32)
declare ptr @FastLine16Y_11(ptr, i32 signext, i32 signext, i32 signext, i32 signext)
declare ptr @UMVLine16Y_11(ptr, i32 signext, i32 signext, i32 signext, i32 signext)
declare i32 @llvm.smin.i32(i32, i32)
declare i32 @llvm.smax.i32(i32, i32)
declare i32 @llvm.umax.i32(i32, i32)
