; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=slp-vectorizer -mtriple=riscv64 -riscv-use-vla-vectorizer -mattr=+v < %s | FileCheck %s

define void @test(ptr %0, i64 %idx) #0 {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr null, align 8
; CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[TMP0:%.*]], align 8
; CHECK-NEXT:    [[ARRIDX:%.*]] = getelementptr double, ptr null, i64 [[IDX:%.*]]
; CHECK-NEXT:    [[TMP3:%.*]] = load double, ptr [[ARRIDX]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = load double, ptr null, align 8
; CHECK-NEXT:    [[IDX1:%.*]] = getelementptr i8, ptr null, i64 48
; CHECK-NEXT:    store double [[TMP1]], ptr [[IDX1]], align 8
; CHECK-NEXT:    [[IDX2:%.*]] = getelementptr i8, ptr null, i64 56
; CHECK-NEXT:    store double [[TMP2]], ptr [[IDX2]], align 8
; CHECK-NEXT:    [[IDX3:%.*]] = getelementptr i8, ptr null, i64 64
; CHECK-NEXT:    store double [[TMP3]], ptr [[IDX3]], align 8
; CHECK-NEXT:    [[IDX4:%.*]] = getelementptr i8, ptr null, i64 72
; CHECK-NEXT:    store double [[TMP4]], ptr [[IDX4]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %1 = load double, ptr null, align 8
  %2 = load double, ptr %0, align 8
  %arridx = getelementptr double, ptr null, i64 %idx
  %3 = load double, ptr %arridx, align 8
  %4 = load double, ptr null, align 8
  %idx1 = getelementptr i8, ptr null, i64 48
  store double %1, ptr %idx1, align 8
  %idx2 = getelementptr i8, ptr null, i64 56
  store double %2, ptr %idx2, align 8
  %idx3 = getelementptr i8, ptr null, i64 64
  store double %3, ptr %idx3, align 8
  %idx4 = getelementptr i8, ptr null, i64 72
  store double %4, ptr %idx4, align 8
  ret void
}

attributes #0 = { vscale_range(8,1024) }
