; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=slp-vectorizer -mtriple=riscv64 -mattr=+v < %s -mcpu=sifive-x280n | FileCheck %s

define void @test(ptr %0, i64 %i) {
; CHECK-LABEL: @test(
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [2 x i32], ptr [[TMP0:%.*]], i64 [[I:%.*]]
; CHECK-NEXT:    store i32 -939524096, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[HISTORY6:%.*]] = getelementptr inbounds [2 x i32], ptr [[TMP0]], i64 [[I]], i32 1
; CHECK-NEXT:    store i32 -1, ptr [[HISTORY6]], align 4
; CHECK-NEXT:    ret void
;
  %arrayidx = getelementptr inbounds [2 x i32], ptr %0, i64 %i
  store i32 -939524096, ptr %arrayidx, align 4
  %history6 = getelementptr inbounds [2 x i32], ptr %0, i64 %i, i32 1
  store i32 -1, ptr %history6, align 4
  ret void
}

