; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE

; non-profitable cases on x280, p470, and p670
; reduced from _ZNK5Scene6renderEiiiiP5ImageIhEi@src/geekbench/raytrace/scene.cpp:293
define void @_ZNK5Scene6renderEiiiiP5ImageIhEi(ptr %this, i32 %x, i32 %y, i32 %width, i32 %height, ptr %out_image, i32 %repeat) {
; NON-PROFITABLE-LABEL: define void @_ZNK5Scene6renderEiiiiP5ImageIhEi
; NON-PROFITABLE-SAME: (ptr [[THIS:%.*]], i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[WIDTH:%.*]], i32 [[HEIGHT:%.*]], ptr [[OUT_IMAGE:%.*]], i32 [[REPEAT:%.*]]) #[[ATTR0:[0-9]+]] {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    [[MUL_I:%.*]] = fdiv double 2.550000e+02, 0.000000e+00
; NON-PROFITABLE-NEXT:    br label [[FOR_BODY14_US:%.*]]
; NON-PROFITABLE:       for.body14.us:
; NON-PROFITABLE-NEXT:    br i1 false, label [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_US:%.*]], label [[CLEANUP_US:%.*]]
; NON-PROFITABLE:       _ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us:
; NON-PROFITABLE-NEXT:    [[TEMP_COLOR_SROA_6_0_COPYLOAD_US:%.*]] = load double, ptr null, align 8
; NON-PROFITABLE-NEXT:    br i1 false, label [[CLEANUP_US]], label [[IF_ELSE45_US:%.*]]
; NON-PROFITABLE:       cleanup.us:
; NON-PROFITABLE-NEXT:    [[COLOR_SROA_9_0_LCSSA_US:%.*]] = phi double [ 0.000000e+00, [[FOR_BODY14_US]] ], [ [[ADD3_I_US168:%.*]], [[IF_ELSE45_US]] ], [ 0.000000e+00, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_US]] ]
; NON-PROFITABLE-NEXT:    [[COLOR_SROA_15_0_LCSSA_US:%.*]] = phi double [ 0.000000e+00, [[FOR_BODY14_US]] ], [ [[ADD5_I_US169:%.*]], [[IF_ELSE45_US]] ], [ 0.000000e+00, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_US]] ]
; NON-PROFITABLE-NEXT:    [[MUL57_US:%.*]] = fmul double [[MUL_I]], [[COLOR_SROA_9_0_LCSSA_US]]
; NON-PROFITABLE-NEXT:    [[CONV58_US:%.*]] = fptosi double [[MUL57_US]] to i32
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I111_US:%.*]] = call i32 @llvm.smax.i32(i32 [[CONV58_US]], i32 0)
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I112_US:%.*]] = call i32 @llvm.smin.i32(i32 [[MINIMUM_VALUE_VALUE_I111_US]], i32 255)
; NON-PROFITABLE-NEXT:    [[MUL61_US:%.*]] = fmul double [[MUL_I]], [[COLOR_SROA_15_0_LCSSA_US]]
; NON-PROFITABLE-NEXT:    [[CONV62_US:%.*]] = fptosi double [[MUL61_US]] to i32
; NON-PROFITABLE-NEXT:    [[MINIMUM_VALUE_VALUE_I114_US:%.*]] = call i32 @llvm.smax.i32(i32 [[CONV62_US]], i32 0)
; NON-PROFITABLE-NEXT:    [[RETVAL_0_I115_US:%.*]] = call i32 @llvm.smin.i32(i32 [[MINIMUM_VALUE_VALUE_I114_US]], i32 255)
; NON-PROFITABLE-NEXT:    [[CONV66_US:%.*]] = trunc i32 [[RETVAL_0_I112_US]] to i8
; NON-PROFITABLE-NEXT:    [[ARRAYIDX67_US:%.*]] = getelementptr i8, ptr null, i64 1
; NON-PROFITABLE-NEXT:    store i8 [[CONV66_US]], ptr [[ARRAYIDX67_US]], align 1
; NON-PROFITABLE-NEXT:    [[CONV68_US:%.*]] = trunc i32 [[RETVAL_0_I115_US]] to i8
; NON-PROFITABLE-NEXT:    [[ARRAYIDX69_US:%.*]] = getelementptr i8, ptr null, i64 2
; NON-PROFITABLE-NEXT:    store i8 [[CONV68_US]], ptr [[ARRAYIDX69_US]], align 1
; NON-PROFITABLE-NEXT:    br label [[FOR_BODY14_US]]
; NON-PROFITABLE:       _ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread135.us:
; NON-PROFITABLE-NEXT:    br label [[IF_ELSE45_US]]
; NON-PROFITABLE:       _ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread.us:
; NON-PROFITABLE-NEXT:    br label [[IF_ELSE45_US]]
; NON-PROFITABLE:       if.else45.us:
; NON-PROFITABLE-NEXT:    [[TEMP_COLOR_SROA_8_0_COPYLOAD134_US:%.*]] = phi double [ 2.000000e-01, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_THREAD_US:%.*]] ], [ 0.000000e+00, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_US]] ], [ 8.000000e-01, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_THREAD135_US:%.*]] ]
; NON-PROFITABLE-NEXT:    [[TEMP_COLOR_SROA_6_0_COPYLOAD133_US:%.*]] = phi double [ 2.000000e-01, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_THREAD_US]] ], [ [[TEMP_COLOR_SROA_6_0_COPYLOAD_US]], [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_US]] ], [ 8.000000e-01, [[_ZNK5SCENE5TRACEERK3RAYRST26LINEAR_CONGRUENTIAL_ENGINEIMLM48271ELM0ELM2147483647EE_EXIT_THREAD135_US]] ]
; NON-PROFITABLE-NEXT:    [[ADD3_I_US168]] = fadd double [[TEMP_COLOR_SROA_6_0_COPYLOAD133_US]], 0.000000e+00
; NON-PROFITABLE-NEXT:    [[ADD5_I_US169]] = fadd double [[TEMP_COLOR_SROA_8_0_COPYLOAD134_US]], 0.000000e+00
; NON-PROFITABLE-NEXT:    br label [[CLEANUP_US]]
;
entry:
  %mul.i = fdiv double 2.550000e+02, 0.000000e+00
  br label %for.body14.us

for.body14.us:
  br i1 false, label %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us, label %cleanup.us

_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us:
  %temp_color.sroa.6.0.copyload.us = load double, ptr null, align 8
  br i1 false, label %cleanup.us, label %if.else45.us

cleanup.us:
  %color.sroa.9.0.lcssa.us = phi double [ 0.000000e+00, %for.body14.us ], [ %add3.i.us168, %if.else45.us ], [ 0.000000e+00, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us ]
  %color.sroa.15.0.lcssa.us = phi double [ 0.000000e+00, %for.body14.us ], [ %add5.i.us169, %if.else45.us ], [ 0.000000e+00, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us ]
  %mul57.us = fmul double %mul.i, %color.sroa.9.0.lcssa.us
  %conv58.us = fptosi double %mul57.us to i32
  %minimum_value.value.i111.us = call i32 @llvm.smax.i32(i32 %conv58.us, i32 0)
  %retval.0.i112.us = call i32 @llvm.smin.i32(i32 %minimum_value.value.i111.us, i32 255)
  %mul61.us = fmul double %mul.i, %color.sroa.15.0.lcssa.us
  %conv62.us = fptosi double %mul61.us to i32
  %minimum_value.value.i114.us = call i32 @llvm.smax.i32(i32 %conv62.us, i32 0)
  %retval.0.i115.us = call i32 @llvm.smin.i32(i32 %minimum_value.value.i114.us, i32 255)
  %conv66.us = trunc i32 %retval.0.i112.us to i8
  %arrayidx67.us = getelementptr i8, ptr null, i64 1
  store i8 %conv66.us, ptr %arrayidx67.us, align 1
  %conv68.us = trunc i32 %retval.0.i115.us to i8
  %arrayidx69.us = getelementptr i8, ptr null, i64 2
  store i8 %conv68.us, ptr %arrayidx69.us, align 1
  br label %for.body14.us

_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread135.us:
  br label %if.else45.us

_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread.us:
  br label %if.else45.us

if.else45.us:
  %temp_color.sroa.8.0.copyload134.us = phi double [ 2.000000e-01, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread.us ], [ 0.000000e+00, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us ], [ 8.000000e-01, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread135.us ]
  %temp_color.sroa.6.0.copyload133.us = phi double [ 2.000000e-01, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread.us ], [ %temp_color.sroa.6.0.copyload.us, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.us ], [ 8.000000e-01, %_ZNK5Scene5traceERK3RayRSt26linear_congruential_engineImLm48271ELm0ELm2147483647EE.exit.thread135.us ]
  %add3.i.us168 = fadd double %temp_color.sroa.6.0.copyload133.us, 0.000000e+00
  %add5.i.us169 = fadd double %temp_color.sroa.8.0.copyload134.us, 0.000000e+00
  br label %cleanup.us
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smax.i32(i32, i32)

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32)
