; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-x280 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p470 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE
; RUN: opt -S -passes=slp-vectorizer -slp-threshold=0 -mtriple=riscv64 \
; RUN: -mcpu=sifive-p670 -o - 2>&1 < %s | FileCheck %s --check-prefixes=NON-PROFITABLE

; non-profitable cases on x280, p470, p670

; The is reduced from spec2k6 464.h264ref mv-search.c.
; On x280 we don't want the loop being vectorized by SLP which would decrease the score from 6.72 to 3.36
; It is currently prevented by https://github.com/sifive/riscv-llvm-internal/pull/557

define void @foo(ptr %byte_abs) {
; NON-PROFITABLE-LABEL: @foo(
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    br label [[FOR_BODY4:%.*]]
; NON-PROFITABLE:       for.body4:
; NON-PROFITABLE-NEXT:    [[LINESADBLK0_0224:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[ADD30:%.*]], [[FOR_BODY4]] ]
; NON-PROFITABLE-NEXT:    [[INCDEC_PTR:%.*]] = getelementptr inbounds i16, ptr null, i64 1
; NON-PROFITABLE-NEXT:    [[TMP0:%.*]] = load i16, ptr null, align 2
; NON-PROFITABLE-NEXT:    [[CONV:%.*]] = zext i16 [[TMP0]] to i64
; NON-PROFITABLE-NEXT:    [[INCDEC_PTR5:%.*]] = getelementptr inbounds i16, ptr null, i64 1
; NON-PROFITABLE-NEXT:    [[TMP1:%.*]] = load i16, ptr null, align 2
; NON-PROFITABLE-NEXT:    [[CONV6:%.*]] = zext i16 [[TMP1]] to i64
; NON-PROFITABLE-NEXT:    [[SUB:%.*]] = sub nsw i64 [[CONV]], [[CONV6]]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[BYTE_ABS:%.*]], i64 [[SUB]]
; NON-PROFITABLE-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; NON-PROFITABLE-NEXT:    [[INCDEC_PTR7:%.*]] = getelementptr inbounds i16, ptr null, i64 2
; NON-PROFITABLE-NEXT:    [[TMP3:%.*]] = load i16, ptr [[INCDEC_PTR]], align 2
; NON-PROFITABLE-NEXT:    [[CONV8:%.*]] = zext i16 [[TMP3]] to i64
; NON-PROFITABLE-NEXT:    [[INCDEC_PTR9:%.*]] = getelementptr inbounds i16, ptr null, i64 2
; NON-PROFITABLE-NEXT:    [[TMP4:%.*]] = load i16, ptr [[INCDEC_PTR5]], align 2
; NON-PROFITABLE-NEXT:    [[CONV10:%.*]] = zext i16 [[TMP4]] to i64
; NON-PROFITABLE-NEXT:    [[SUB11:%.*]] = sub nsw i64 [[CONV8]], [[CONV10]]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds i32, ptr [[BYTE_ABS]], i64 [[SUB11]]
; NON-PROFITABLE-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX13]], align 4
; NON-PROFITABLE-NEXT:    [[ADD14:%.*]] = add nsw i32 [[TMP2]], [[TMP5]]
; NON-PROFITABLE-NEXT:    [[INCDEC_PTR15:%.*]] = getelementptr inbounds i16, ptr null, i64 3
; NON-PROFITABLE-NEXT:    [[TMP6:%.*]] = load i16, ptr [[INCDEC_PTR7]], align 2
; NON-PROFITABLE-NEXT:    [[CONV16:%.*]] = zext i16 [[TMP6]] to i64
; NON-PROFITABLE-NEXT:    [[INCDEC_PTR17:%.*]] = getelementptr inbounds i16, ptr null, i64 3
; NON-PROFITABLE-NEXT:    [[TMP7:%.*]] = load i16, ptr [[INCDEC_PTR9]], align 2
; NON-PROFITABLE-NEXT:    [[CONV18:%.*]] = zext i16 [[TMP7]] to i64
; NON-PROFITABLE-NEXT:    [[SUB19:%.*]] = sub nsw i64 [[CONV16]], [[CONV18]]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds i32, ptr [[BYTE_ABS]], i64 [[SUB19]]
; NON-PROFITABLE-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX21]], align 4
; NON-PROFITABLE-NEXT:    [[ADD22:%.*]] = add nsw i32 [[ADD14]], [[TMP8]]
; NON-PROFITABLE-NEXT:    [[TMP9:%.*]] = load i16, ptr [[INCDEC_PTR15]], align 2
; NON-PROFITABLE-NEXT:    [[CONV24:%.*]] = zext i16 [[TMP9]] to i64
; NON-PROFITABLE-NEXT:    [[TMP10:%.*]] = load i16, ptr [[INCDEC_PTR17]], align 2
; NON-PROFITABLE-NEXT:    [[CONV26:%.*]] = zext i16 [[TMP10]] to i64
; NON-PROFITABLE-NEXT:    [[SUB27:%.*]] = sub nsw i64 [[CONV24]], [[CONV26]]
; NON-PROFITABLE-NEXT:    [[ARRAYIDX29:%.*]] = getelementptr inbounds i32, ptr [[BYTE_ABS]], i64 [[SUB27]]
; NON-PROFITABLE-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX29]], align 4
; NON-PROFITABLE-NEXT:    [[ADD30]] = add nsw i32 [[ADD22]], [[TMP11]]
; NON-PROFITABLE-NEXT:    br label [[FOR_BODY4]]
;
entry:
  br label %for.body4

for.body4:                                        ; preds = %for.body4, %entry
  %LineSadBlk0.0224 = phi i32 [ 0, %entry ], [ %add30, %for.body4 ]
  %incdec.ptr = getelementptr inbounds i16, ptr null, i64 1
  %0 = load i16, ptr null, align 2
  %conv = zext i16 %0 to i64
  %incdec.ptr5 = getelementptr inbounds i16, ptr null, i64 1
  %1 = load i16, ptr null, align 2
  %conv6 = zext i16 %1 to i64
  %sub = sub nsw i64 %conv, %conv6
  %arrayidx = getelementptr inbounds i32, ptr %byte_abs, i64 %sub
  %2 = load i32, ptr %arrayidx, align 4
  %incdec.ptr7 = getelementptr inbounds i16, ptr null, i64 2
  %3 = load i16, ptr %incdec.ptr, align 2
  %conv8 = zext i16 %3 to i64
  %incdec.ptr9 = getelementptr inbounds i16, ptr null, i64 2
  %4 = load i16, ptr %incdec.ptr5, align 2
  %conv10 = zext i16 %4 to i64
  %sub11 = sub nsw i64 %conv8, %conv10
  %arrayidx13 = getelementptr inbounds i32, ptr %byte_abs, i64 %sub11
  %5 = load i32, ptr %arrayidx13, align 4
  %add14 = add nsw i32 %2, %5
  %incdec.ptr15 = getelementptr inbounds i16, ptr null, i64 3
  %6 = load i16, ptr %incdec.ptr7, align 2
  %conv16 = zext i16 %6 to i64
  %incdec.ptr17 = getelementptr inbounds i16, ptr null, i64 3
  %7 = load i16, ptr %incdec.ptr9, align 2
  %conv18 = zext i16 %7 to i64
  %sub19 = sub nsw i64 %conv16, %conv18
  %arrayidx21 = getelementptr inbounds i32, ptr %byte_abs, i64 %sub19
  %8 = load i32, ptr %arrayidx21, align 4
  %add22 = add nsw i32 %add14, %8
  %9 = load i16, ptr %incdec.ptr15, align 2
  %conv24 = zext i16 %9 to i64
  %10 = load i16, ptr %incdec.ptr17, align 2
  %conv26 = zext i16 %10 to i64
  %sub27 = sub nsw i64 %conv24, %conv26
  %arrayidx29 = getelementptr inbounds i32, ptr %byte_abs, i64 %sub27
  %11 = load i32, ptr %arrayidx29, align 4
  %add30 = add nsw i32 %add22, %11
  br label %for.body4
}
