; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=riscv64 -mcpu=sifive-x280o -passes=slp-vectorizer -S -slp-revec -slp-max-reg-size=1024 -slp-threshold=-11 %s | FileCheck %s

@struct0 = external global [2 x [6 x [4 x [4 x i32]]]]

define void @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr null, align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x ptr>, ptr getelementptr inbounds (i8, ptr null, i64 8), align 8
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 32), align 8
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x ptr>, ptr getelementptr inbounds (i8, ptr null, i64 8), align 8
; CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 8), align 8
; CHECK-NEXT:    [[TMP11:%.*]] = load <2 x ptr>, ptr getelementptr inbounds (i8, ptr null, i64 16), align 8
; CHECK-NEXT:    [[TMP12:%.*]] = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 24), align 8
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ult ptr [[TMP12]], null
; CHECK-NEXT:    [[FOUND_CONFLICT199:%.*]] = and i1 false, [[TMP5]]
; CHECK-NEXT:    [[BOUND1202:%.*]] = icmp ult ptr [[TMP2]], null
; CHECK-NEXT:    [[TMP15:%.*]] = call <2 x ptr> @llvm.masked.gather.v2p0.v2p0(<2 x ptr> <ptr inttoptr (i64 16 to ptr), ptr inttoptr (i64 40 to ptr)>, i32 8, <2 x i1> splat (i1 true), <2 x ptr> poison)
; CHECK-NEXT:    [[TMP16:%.*]] = icmp ult <2 x ptr> [[TMP15]], zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i1> [[TMP16]], <2 x i1> poison, <3 x i32> <i32 0, i32 poison, i32 1>
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <3 x i1> <i1 poison, i1 false, i1 poison>, <3 x i1> [[TMP6]], <3 x i32> <i32 3, i32 1, i32 5>
; CHECK-NEXT:    [[TMP8:%.*]] = and <3 x i1> zeroinitializer, [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = call i1 @llvm.vector.reduce.or.v3i1(<3 x i1> [[TMP8]])
; CHECK-NEXT:    [[BOUND1226:%.*]] = icmp ult ptr [[TMP4]], getelementptr inbounds nuw (i8, ptr null, i64 768)
; CHECK-NEXT:    [[TMP13:%.*]] = icmp ult <2 x ptr> [[TMP11]], <ptr inttoptr (i64 768 to ptr), ptr inttoptr (i64 768 to ptr)>
; CHECK-NEXT:    [[BOUND1254:%.*]] = icmp ult ptr [[TMP0]], null
; CHECK-NEXT:    [[TMP14:%.*]] = icmp ult <4 x ptr> [[TMP3]], <ptr inttoptr (i64 384 to ptr), ptr inttoptr (i64 384 to ptr), ptr inttoptr (i64 384 to ptr), ptr inttoptr (i64 768 to ptr)>
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ult <4 x ptr> [[TMP1]], <ptr getelementptr inbounds nuw (i8, ptr @struct0, i64 768), ptr getelementptr inbounds nuw (i8, ptr @struct0, i64 768), ptr getelementptr inbounds nuw (i8, ptr @struct0, i64 768), ptr @struct0>
; CHECK-NEXT:    br i1 [[TMP9]], label [[FOR_COND1_PREHEADER_US_PREHEADER:%.*]], label [[FOR_COND1_PREHEADER_PREHEADER:%.*]]
; CHECK:       for.cond1.preheader.preheader:
; CHECK-NEXT:    ret void
; CHECK:       for.cond1.preheader.us.preheader:
; CHECK-NEXT:    ret void
;
entry:
  %0 = load ptr, ptr null, align 8
  %1 = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 8), align 8
  %2 = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 16), align 8
  %3 = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 24), align 8
  %4 = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 32), align 8
  %5 = load ptr, ptr getelementptr inbounds (i8, ptr null, i64 40), align 8
  %bound0193 = icmp ugt ptr null, null
  %bound1194 = icmp ult ptr %2, null
  %found.conflict195 = and i1 false, %bound1194
  %bound0197 = icmp ugt ptr null, null
  %bound1198 = icmp ult ptr %3, null
  %found.conflict199 = and i1 false, %bound1198
  %bound1202 = icmp ult ptr %4, null
  %found.conflict203 = and i1 false, false
  %conflict.rdx204 = or i1 %found.conflict195, %found.conflict203
  %bound1206 = icmp ult ptr %5, null
  %found.conflict207 = and i1 false, %bound1206
  %conflict.rdx208 = or i1 %conflict.rdx204, %found.conflict207
  %bound1226 = icmp ult ptr %1, getelementptr inbounds nuw (i8, ptr null, i64 768)
  %bound1230 = icmp ult ptr %2, getelementptr inbounds nuw (i8, ptr null, i64 768)
  %bound1234 = icmp ult ptr %3, getelementptr inbounds nuw (i8, ptr null, i64 768)
  %bound1238 = icmp ult ptr %4, getelementptr inbounds nuw (i8, ptr null, i64 768)
  %bound1254 = icmp ult ptr %0, null
  %bound1258 = icmp ult ptr %1, getelementptr inbounds nuw (i8, ptr null, i64 384)
  %bound1262 = icmp ult ptr %2, getelementptr inbounds nuw (i8, ptr null, i64 384)
  %bound1266 = icmp ult ptr %3, getelementptr inbounds nuw (i8, ptr null, i64 384)
  %bound1286 = icmp ult ptr %1, getelementptr inbounds nuw (i8, ptr @struct0, i64 768)
  %bound1290 = icmp ult ptr %2, getelementptr inbounds nuw (i8, ptr @struct0, i64 768)
  %bound1294 = icmp ult ptr %3, getelementptr inbounds nuw (i8, ptr @struct0, i64 768)
  %bound1298 = icmp ult ptr %4, @struct0
  br i1 %conflict.rdx208, label %for.cond1.preheader.us.preheader, label %for.cond1.preheader.preheader

for.cond1.preheader.preheader:
  ret void

for.cond1.preheader.us.preheader:
  ret void
}
