; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -S -mtriple riscv64-unknown-linux-gnu < %s --passes=slp-vectorizer -mcpu=sifive-p670 -slp-threshold=-80 | FileCheck %s

define i32 @test(ptr %pix1, ptr %pix2, i64 %idx.ext, i64 %idx.ext63, ptr %add.ptr, ptr %add.ptr64) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: ptr [[PIX1:%.*]], ptr [[PIX2:%.*]], i64 [[IDX_EXT:%.*]], i64 [[IDX_EXT63:%.*]], ptr [[ADD_PTR:%.*]], ptr [[ADD_PTR64:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr i8, ptr [[PIX1]], i64 4
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr i8, ptr [[PIX2]], i64 4
; CHECK-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr i8, ptr [[PIX1]], i64 2
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr i8, ptr [[PIX2]], i64 2
; CHECK-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr i8, ptr [[PIX1]], i64 6
; CHECK-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr i8, ptr [[PIX2]], i64 6
; CHECK-NEXT:    [[ADD_PTR3:%.*]] = getelementptr i8, ptr [[PIX1]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR644:%.*]] = getelementptr i8, ptr [[PIX2]], i64 [[IDX_EXT63]]
; CHECK-NEXT:    [[ARRAYIDX3_1:%.*]] = getelementptr i8, ptr [[ADD_PTR3]], i64 4
; CHECK-NEXT:    [[ARRAYIDX5_1:%.*]] = getelementptr i8, ptr [[ADD_PTR644]], i64 4
; CHECK-NEXT:    [[ARRAYIDX8_1:%.*]] = getelementptr i8, ptr [[ADD_PTR3]], i64 1
; CHECK-NEXT:    [[ARRAYIDX20_1:%.*]] = getelementptr i8, ptr [[ADD_PTR3]], i64 2
; CHECK-NEXT:    [[ARRAYIDX22_1:%.*]] = getelementptr i8, ptr [[ADD_PTR644]], i64 2
; CHECK-NEXT:    [[ARRAYIDX25_1:%.*]] = getelementptr i8, ptr [[ADD_PTR3]], i64 6
; CHECK-NEXT:    [[ARRAYIDX27_1:%.*]] = getelementptr i8, ptr [[ADD_PTR644]], i64 6
; CHECK-NEXT:    [[ADD_PTR_1:%.*]] = getelementptr i8, ptr [[ADD_PTR]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR64_1:%.*]] = getelementptr i8, ptr [[ADD_PTR64]], i64 [[IDX_EXT63]]
; CHECK-NEXT:    [[ARRAYIDX3_2:%.*]] = getelementptr i8, ptr [[ADD_PTR_1]], i64 4
; CHECK-NEXT:    [[ARRAYIDX5_2:%.*]] = getelementptr i8, ptr [[ADD_PTR64_1]], i64 4
; CHECK-NEXT:    [[ARRAYIDX8_2:%.*]] = getelementptr i8, ptr [[ADD_PTR_1]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX8_2]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i8>, ptr [[ADD_PTR_1]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[ADD_PTR_1]], align 1
; CHECK-NEXT:    [[TMP77:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = zext <2 x i8> [[TMP1]] to <2 x i32>
; CHECK-NEXT:    [[TMP78:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = load <2 x i8>, ptr [[ADD_PTR64_1]], align 1
; CHECK-NEXT:    [[TMP5:%.*]] = zext <2 x i8> [[TMP4]] to <2 x i32>
; CHECK-NEXT:    [[TMP6:%.*]] = sub <2 x i32> [[TMP3]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = load <2 x i8>, ptr [[ARRAYIDX3_2]], align 1
; CHECK-NEXT:    [[TMP8:%.*]] = zext <2 x i8> [[TMP7]] to <2 x i32>
; CHECK-NEXT:    [[TMP9:%.*]] = load <2 x i8>, ptr [[ARRAYIDX5_2]], align 1
; CHECK-NEXT:    [[TMP10:%.*]] = zext <2 x i8> [[TMP9]] to <2 x i32>
; CHECK-NEXT:    [[TMP13:%.*]] = sub <2 x i32> [[TMP8]], [[TMP10]]
; CHECK-NEXT:    [[TMP14:%.*]] = shl <2 x i32> [[TMP13]], splat (i32 16)
; CHECK-NEXT:    [[TMP19:%.*]] = add <2 x i32> [[TMP14]], [[TMP6]]
; CHECK-NEXT:    [[ARRAYIDX20_2:%.*]] = getelementptr i8, ptr [[ADD_PTR_1]], i64 2
; CHECK-NEXT:    [[ARRAYIDX22_2:%.*]] = getelementptr i8, ptr [[ADD_PTR64_1]], i64 2
; CHECK-NEXT:    [[ARRAYIDX25_2:%.*]] = getelementptr i8, ptr [[ADD_PTR_1]], i64 6
; CHECK-NEXT:    [[ARRAYIDX27_2:%.*]] = getelementptr i8, ptr [[ADD_PTR64_1]], i64 6
; CHECK-NEXT:    [[TMP23:%.*]] = load <2 x i8>, ptr [[ARRAYIDX20_2]], align 1
; CHECK-NEXT:    [[TMP15:%.*]] = zext <2 x i8> [[TMP23]] to <2 x i32>
; CHECK-NEXT:    [[TMP16:%.*]] = load <2 x i8>, ptr [[ARRAYIDX22_2]], align 1
; CHECK-NEXT:    [[TMP17:%.*]] = zext <2 x i8> [[TMP16]] to <2 x i32>
; CHECK-NEXT:    [[TMP18:%.*]] = sub <2 x i32> [[TMP15]], [[TMP17]]
; CHECK-NEXT:    [[TMP24:%.*]] = load <2 x i8>, ptr [[ARRAYIDX25_2]], align 1
; CHECK-NEXT:    [[TMP20:%.*]] = zext <2 x i8> [[TMP24]] to <2 x i32>
; CHECK-NEXT:    [[TMP21:%.*]] = load <2 x i8>, ptr [[ARRAYIDX27_2]], align 1
; CHECK-NEXT:    [[TMP22:%.*]] = zext <2 x i8> [[TMP21]] to <2 x i32>
; CHECK-NEXT:    [[TMP25:%.*]] = sub <2 x i32> [[TMP20]], [[TMP22]]
; CHECK-NEXT:    [[TMP26:%.*]] = shl <2 x i32> [[TMP25]], splat (i32 16)
; CHECK-NEXT:    [[TMP294:%.*]] = add <2 x i32> [[TMP26]], [[TMP18]]
; CHECK-NEXT:    [[TMP295:%.*]] = shufflevector <2 x i32> [[TMP19]], <2 x i32> [[TMP294]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <2 x i32> [[TMP19]], <2 x i32> [[TMP294]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP28:%.*]] = add <2 x i32> [[TMP295]], [[TMP27]]
; CHECK-NEXT:    [[TMP151:%.*]] = sub <2 x i32> [[TMP27]], [[TMP295]]
; CHECK-NEXT:    [[TMP31:%.*]] = extractelement <2 x i32> [[TMP28]], i32 1
; CHECK-NEXT:    [[TMP32:%.*]] = extractelement <2 x i32> [[TMP151]], i32 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractelement <2 x i32> [[TMP151]], i32 1
; CHECK-NEXT:    [[SUB59_2:%.*]] = sub i32 [[TMP32]], [[TMP33]]
; CHECK-NEXT:    [[ARRAYIDX5_3:%.*]] = getelementptr i8, ptr null, i64 4
; CHECK-NEXT:    [[TMP34:%.*]] = load <2 x i8>, ptr null, align 1
; CHECK-NEXT:    [[TMP35:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP37:%.*]] = zext <2 x i8> [[TMP34]] to <2 x i32>
; CHECK-NEXT:    [[CONV_3:%.*]] = zext i8 [[TMP35]] to i32
; CHECK-NEXT:    [[TMP36:%.*]] = load <2 x i8>, ptr null, align 1
; CHECK-NEXT:    [[TMP38:%.*]] = zext <2 x i8> [[TMP36]] to <2 x i32>
; CHECK-NEXT:    [[TMP40:%.*]] = sub <2 x i32> [[TMP37]], [[TMP38]]
; CHECK-NEXT:    [[TMP39:%.*]] = call <2 x i8> @llvm.experimental.vp.strided.load.v2i8.p0.i64(ptr align 1 null, i64 4, <2 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[TMP41:%.*]] = zext <2 x i8> [[TMP39]] to <2 x i32>
; CHECK-NEXT:    [[TMP46:%.*]] = shufflevector <2 x i32> [[TMP41]], <2 x i32> poison, <2 x i32> <i32 1, i32 0>
; CHECK-NEXT:    [[TMP42:%.*]] = load <2 x i8>, ptr [[ARRAYIDX5_3]], align 1
; CHECK-NEXT:    [[TMP48:%.*]] = zext <2 x i8> [[TMP42]] to <2 x i32>
; CHECK-NEXT:    [[TMP43:%.*]] = sub <2 x i32> [[TMP46]], [[TMP48]]
; CHECK-NEXT:    [[TMP44:%.*]] = shl <2 x i32> [[TMP43]], splat (i32 16)
; CHECK-NEXT:    [[TMP45:%.*]] = add <2 x i32> [[TMP44]], [[TMP40]]
; CHECK-NEXT:    [[ARRAYIDX20_3:%.*]] = getelementptr i8, ptr null, i64 2
; CHECK-NEXT:    [[ARRAYIDX22_3:%.*]] = getelementptr i8, ptr null, i64 2
; CHECK-NEXT:    [[ARRAYIDX27_3:%.*]] = getelementptr i8, ptr null, i64 6
; CHECK-NEXT:    [[TMP49:%.*]] = load <2 x i8>, ptr [[ARRAYIDX20_3]], align 1
; CHECK-NEXT:    [[TMP50:%.*]] = zext <2 x i8> [[TMP49]] to <2 x i32>
; CHECK-NEXT:    [[TMP51:%.*]] = load <2 x i8>, ptr [[ARRAYIDX22_3]], align 1
; CHECK-NEXT:    [[TMP52:%.*]] = zext <2 x i8> [[TMP51]] to <2 x i32>
; CHECK-NEXT:    [[TMP55:%.*]] = sub <2 x i32> [[TMP50]], [[TMP52]]
; CHECK-NEXT:    [[TMP54:%.*]] = call <2 x i8> @llvm.masked.gather.v2i8.v2p0(<2 x ptr> zeroinitializer, i32 1, <2 x i1> splat (i1 true), <2 x i8> poison)
; CHECK-NEXT:    [[TMP56:%.*]] = zext <2 x i8> [[TMP54]] to <2 x i32>
; CHECK-NEXT:    [[TMP57:%.*]] = load <2 x i8>, ptr [[ARRAYIDX27_3]], align 1
; CHECK-NEXT:    [[TMP64:%.*]] = zext <2 x i8> [[TMP57]] to <2 x i32>
; CHECK-NEXT:    [[TMP58:%.*]] = sub <2 x i32> [[TMP56]], [[TMP64]]
; CHECK-NEXT:    [[TMP59:%.*]] = shl <2 x i32> [[TMP58]], splat (i32 16)
; CHECK-NEXT:    [[TMP60:%.*]] = add <2 x i32> [[TMP59]], [[TMP55]]
; CHECK-NEXT:    [[TMP61:%.*]] = shufflevector <2 x i32> [[TMP45]], <2 x i32> [[TMP60]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP62:%.*]] = shufflevector <2 x i32> [[TMP45]], <2 x i32> [[TMP60]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP63:%.*]] = add <2 x i32> [[TMP61]], [[TMP62]]
; CHECK-NEXT:    [[TMP115:%.*]] = sub <2 x i32> [[TMP62]], [[TMP61]]
; CHECK-NEXT:    [[TMP68:%.*]] = shufflevector <2 x i32> [[TMP28]], <2 x i32> [[TMP63]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP67:%.*]] = shufflevector <2 x i32> [[TMP28]], <2 x i32> [[TMP63]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP65:%.*]] = add <2 x i32> [[TMP68]], [[TMP67]]
; CHECK-NEXT:    [[TMP66:%.*]] = shufflevector <2 x i32> [[TMP63]], <2 x i32> [[TMP28]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP76:%.*]] = shufflevector <2 x i32> [[TMP63]], <2 x i32> [[TMP28]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP69:%.*]] = sub <2 x i32> [[TMP66]], [[TMP76]]
; CHECK-NEXT:    [[TMP72:%.*]] = shufflevector <2 x i32> [[TMP115]], <2 x i32> [[TMP151]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP70:%.*]] = shufflevector <2 x i32> [[TMP115]], <2 x i32> [[TMP151]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP71:%.*]] = add <2 x i32> [[TMP72]], [[TMP70]]
; CHECK-NEXT:    [[TMP73:%.*]] = extractelement <2 x i32> [[TMP115]], i32 0
; CHECK-NEXT:    [[TMP74:%.*]] = extractelement <2 x i32> [[TMP115]], i32 1
; CHECK-NEXT:    [[SUB59_3:%.*]] = sub i32 [[TMP73]], [[TMP74]]
; CHECK-NEXT:    [[SHR_I_1:%.*]] = lshr i32 [[CONV_3]], 15
; CHECK-NEXT:    [[AND_I_1:%.*]] = and i32 [[SHR_I_1]], 65537
; CHECK-NEXT:    [[MUL_I_1:%.*]] = mul i32 [[AND_I_1]], 65535
; CHECK-NEXT:    [[SHR_I49_1:%.*]] = lshr i32 [[TMP31]], 15
; CHECK-NEXT:    [[AND_I50_1:%.*]] = and i32 [[SHR_I49_1]], 65537
; CHECK-NEXT:    [[ADD94_1:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP71]])
; CHECK-NEXT:    [[SHR_I_2:%.*]] = lshr i32 [[TMP77]], 15
; CHECK-NEXT:    [[AND_I_2:%.*]] = and i32 [[SHR_I_2]], 65537
; CHECK-NEXT:    [[MUL_I_2:%.*]] = mul i32 [[AND_I_2]], 65535
; CHECK-NEXT:    [[SHR_I49_3:%.*]] = lshr i32 [[TMP78]], 15
; CHECK-NEXT:    [[AND_I50_3:%.*]] = and i32 [[SHR_I49_3]], 65537
; CHECK-NEXT:    [[TMP79:%.*]] = extractelement <2 x i32> [[TMP69]], i32 0
; CHECK-NEXT:    [[TMP80:%.*]] = extractelement <2 x i32> [[TMP69]], i32 1
; CHECK-NEXT:    [[ADD94_3:%.*]] = add i32 [[TMP79]], [[TMP80]]
; CHECK-NEXT:    [[TMP75:%.*]] = load <2 x i8>, ptr [[ARRAYIDX20]], align 1
; CHECK-NEXT:    [[TMP82:%.*]] = zext <2 x i8> [[TMP75]] to <2 x i32>
; CHECK-NEXT:    [[TMP83:%.*]] = load <2 x i8>, ptr [[ARRAYIDX22]], align 1
; CHECK-NEXT:    [[TMP84:%.*]] = zext <2 x i8> [[TMP83]] to <2 x i32>
; CHECK-NEXT:    [[TMP88:%.*]] = load <2 x i8>, ptr [[ARRAYIDX25]], align 1
; CHECK-NEXT:    [[TMP91:%.*]] = zext <2 x i8> [[TMP88]] to <2 x i32>
; CHECK-NEXT:    [[TMP81:%.*]] = load <2 x i8>, ptr [[ARRAYIDX27]], align 1
; CHECK-NEXT:    [[TMP97:%.*]] = zext <2 x i8> [[TMP81]] to <2 x i32>
; CHECK-NEXT:    [[TMP89:%.*]] = sub <2 x i32> [[TMP91]], [[TMP97]]
; CHECK-NEXT:    [[TMP90:%.*]] = shl <2 x i32> [[TMP89]], splat (i32 16)
; CHECK-NEXT:    [[TMP85:%.*]] = load <2 x i8>, ptr [[ARRAYIDX20]], align 1
; CHECK-NEXT:    [[TMP86:%.*]] = zext <2 x i8> [[TMP85]] to <2 x i32>
; CHECK-NEXT:    [[TMP87:%.*]] = sub <2 x i32> [[TMP86]], [[TMP84]]
; CHECK-NEXT:    [[TMP92:%.*]] = add <2 x i32> [[TMP90]], [[TMP87]]
; CHECK-NEXT:    [[TMP93:%.*]] = insertelement <2 x i32> poison, i32 [[SUB59_2]], i32 0
; CHECK-NEXT:    [[TMP94:%.*]] = shufflevector <2 x i32> [[TMP93]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP95:%.*]] = insertelement <2 x i32> poison, i32 [[SUB59_3]], i32 0
; CHECK-NEXT:    [[TMP96:%.*]] = shufflevector <2 x i32> [[TMP95]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP98:%.*]] = add <2 x i32> [[TMP94]], [[TMP96]]
; CHECK-NEXT:    [[TMP104:%.*]] = sub <2 x i32> [[TMP94]], [[TMP96]]
; CHECK-NEXT:    [[TMP105:%.*]] = shufflevector <2 x i32> [[TMP98]], <2 x i32> [[TMP104]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP100:%.*]] = load <2 x i8>, ptr [[PIX1]], align 1
; CHECK-NEXT:    [[TMP101:%.*]] = zext <2 x i8> [[TMP100]] to <2 x i32>
; CHECK-NEXT:    [[TMP102:%.*]] = load <2 x i8>, ptr [[PIX2]], align 1
; CHECK-NEXT:    [[TMP99:%.*]] = zext <2 x i8> [[TMP102]] to <2 x i32>
; CHECK-NEXT:    [[TMP110:%.*]] = load <2 x i8>, ptr [[ARRAYIDX3]], align 1
; CHECK-NEXT:    [[TMP126:%.*]] = zext <2 x i8> [[TMP110]] to <2 x i32>
; CHECK-NEXT:    [[TMP127:%.*]] = load <2 x i8>, ptr [[ARRAYIDX5]], align 1
; CHECK-NEXT:    [[TMP103:%.*]] = zext <2 x i8> [[TMP127]] to <2 x i32>
; CHECK-NEXT:    [[TMP108:%.*]] = sub <2 x i32> [[TMP126]], [[TMP103]]
; CHECK-NEXT:    [[TMP109:%.*]] = shl <2 x i32> [[TMP108]], splat (i32 16)
; CHECK-NEXT:    [[TMP106:%.*]] = load <2 x i8>, ptr [[PIX1]], align 1
; CHECK-NEXT:    [[TMP107:%.*]] = zext <2 x i8> [[TMP106]] to <2 x i32>
; CHECK-NEXT:    [[TMP139:%.*]] = sub <2 x i32> [[TMP107]], [[TMP99]]
; CHECK-NEXT:    [[TMP111:%.*]] = add <2 x i32> [[TMP109]], [[TMP139]]
; CHECK-NEXT:    [[TMP119:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP111]])
; CHECK-NEXT:    [[TMP113:%.*]] = shufflevector <2 x i32> [[TMP111]], <2 x i32> [[TMP92]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP112:%.*]] = shufflevector <2 x i32> [[TMP111]], <2 x i32> [[TMP92]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP185:%.*]] = sub <2 x i32> [[TMP113]], [[TMP112]]
; CHECK-NEXT:    [[TMP116:%.*]] = lshr <2 x i32> [[TMP101]], splat (i32 15)
; CHECK-NEXT:    [[TMP117:%.*]] = and <2 x i32> [[TMP116]], splat (i32 65537)
; CHECK-NEXT:    [[TMP118:%.*]] = mul <2 x i32> [[TMP117]], splat (i32 65535)
; CHECK-NEXT:    [[TMP187:%.*]] = extractelement <2 x i32> [[TMP185]], i32 0
; CHECK-NEXT:    [[TMP122:%.*]] = extractelement <2 x i32> [[TMP185]], i32 1
; CHECK-NEXT:    [[SUB59:%.*]] = sub i32 [[TMP187]], [[TMP122]]
; CHECK-NEXT:    [[TMP140:%.*]] = load <2 x i8>, ptr [[ARRAYIDX8_1]], align 1
; CHECK-NEXT:    [[TMP174:%.*]] = zext <2 x i8> [[TMP140]] to <2 x i32>
; CHECK-NEXT:    [[TMP120:%.*]] = load <2 x i8>, ptr [[ADD_PTR644]], align 1
; CHECK-NEXT:    [[TMP121:%.*]] = zext <2 x i8> [[TMP120]] to <2 x i32>
; CHECK-NEXT:    [[TMP145:%.*]] = load <2 x i8>, ptr [[ARRAYIDX3_1]], align 1
; CHECK-NEXT:    [[TMP153:%.*]] = zext <2 x i8> [[TMP145]] to <2 x i32>
; CHECK-NEXT:    [[TMP154:%.*]] = load <2 x i8>, ptr [[ARRAYIDX5_1]], align 1
; CHECK-NEXT:    [[TMP125:%.*]] = zext <2 x i8> [[TMP154]] to <2 x i32>
; CHECK-NEXT:    [[TMP131:%.*]] = sub <2 x i32> [[TMP153]], [[TMP125]]
; CHECK-NEXT:    [[TMP132:%.*]] = shl <2 x i32> [[TMP131]], splat (i32 16)
; CHECK-NEXT:    [[TMP128:%.*]] = load <2 x i8>, ptr [[ADD_PTR3]], align 1
; CHECK-NEXT:    [[TMP129:%.*]] = load i8, ptr [[ADD_PTR3]], align 1
; CHECK-NEXT:    [[TMP130:%.*]] = zext <2 x i8> [[TMP128]] to <2 x i32>
; CHECK-NEXT:    [[CONV_1:%.*]] = zext i8 [[TMP129]] to i32
; CHECK-NEXT:    [[SHR_I49_2:%.*]] = lshr i32 [[CONV_1]], 15
; CHECK-NEXT:    [[AND_I50_2:%.*]] = and i32 [[SHR_I49_2]], 65537
; CHECK-NEXT:    [[MUL_I51_2:%.*]] = mul i32 [[AND_I50_2]], 65535
; CHECK-NEXT:    [[TMP155:%.*]] = sub <2 x i32> [[TMP130]], [[TMP121]]
; CHECK-NEXT:    [[TMP136:%.*]] = add <2 x i32> [[TMP132]], [[TMP155]]
; CHECK-NEXT:    [[TMP133:%.*]] = load <2 x i8>, ptr [[ARRAYIDX22_1]], align 1
; CHECK-NEXT:    [[TMP134:%.*]] = zext <2 x i8> [[TMP133]] to <2 x i32>
; CHECK-NEXT:    [[TMP135:%.*]] = load <2 x i8>, ptr [[ARRAYIDX25_1]], align 1
; CHECK-NEXT:    [[TMP156:%.*]] = zext <2 x i8> [[TMP135]] to <2 x i32>
; CHECK-NEXT:    [[TMP137:%.*]] = load <2 x i8>, ptr [[ARRAYIDX27_1]], align 1
; CHECK-NEXT:    [[TMP138:%.*]] = zext <2 x i8> [[TMP137]] to <2 x i32>
; CHECK-NEXT:    [[TMP143:%.*]] = sub <2 x i32> [[TMP156]], [[TMP138]]
; CHECK-NEXT:    [[TMP144:%.*]] = shl <2 x i32> [[TMP143]], splat (i32 16)
; CHECK-NEXT:    [[TMP141:%.*]] = load <2 x i8>, ptr [[ARRAYIDX20_1]], align 1
; CHECK-NEXT:    [[TMP142:%.*]] = zext <2 x i8> [[TMP141]] to <2 x i32>
; CHECK-NEXT:    [[TMP160:%.*]] = sub <2 x i32> [[TMP142]], [[TMP134]]
; CHECK-NEXT:    [[TMP147:%.*]] = add <2 x i32> [[TMP144]], [[TMP160]]
; CHECK-NEXT:    [[TMP150:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP136]])
; CHECK-NEXT:    [[TMP149:%.*]] = shufflevector <2 x i32> [[TMP136]], <2 x i32> [[TMP147]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP148:%.*]] = shufflevector <2 x i32> [[TMP136]], <2 x i32> [[TMP147]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP188:%.*]] = sub <2 x i32> [[TMP149]], [[TMP148]]
; CHECK-NEXT:    [[TMP192:%.*]] = insertelement <2 x i32> poison, i32 [[AND_I50_3]], i32 0
; CHECK-NEXT:    [[TMP197:%.*]] = shufflevector <2 x i32> [[TMP192]], <2 x i32> [[TMP188]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP198:%.*]] = shufflevector <2 x i32> <i32 65535, i32 poison>, <2 x i32> [[TMP188]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP199:%.*]] = mul <2 x i32> [[TMP197]], [[TMP198]]
; CHECK-NEXT:    [[TMP200:%.*]] = add <2 x i32> [[TMP197]], [[TMP198]]
; CHECK-NEXT:    [[TMP213:%.*]] = shufflevector <2 x i32> [[TMP199]], <2 x i32> [[TMP200]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP203:%.*]] = extractelement <2 x i32> [[TMP188]], i32 0
; CHECK-NEXT:    [[TMP204:%.*]] = extractelement <2 x i32> [[TMP188]], i32 1
; CHECK-NEXT:    [[ADD48_2:%.*]] = sub i32 [[TMP203]], [[TMP204]]
; CHECK-NEXT:    [[SHR_I54_1:%.*]] = lshr i32 [[TMP204]], 15
; CHECK-NEXT:    [[AND_I55_1:%.*]] = and i32 [[SHR_I54_1]], 65537
; CHECK-NEXT:    [[MUL_I56_1:%.*]] = mul i32 [[AND_I55_1]], 65535
; CHECK-NEXT:    [[TMP163:%.*]] = lshr <2 x i32> [[TMP174]], splat (i32 15)
; CHECK-NEXT:    [[TMP165:%.*]] = and <2 x i32> [[TMP163]], splat (i32 65537)
; CHECK-NEXT:    [[TMP177:%.*]] = mul <2 x i32> [[TMP165]], splat (i32 65535)
; CHECK-NEXT:    [[TMP180:%.*]] = insertelement <2 x i32> poison, i32 [[ADD48_2]], i32 0
; CHECK-NEXT:    [[TMP181:%.*]] = shufflevector <2 x i32> [[TMP180]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP201:%.*]] = shufflevector <2 x i32> [[TMP188]], <2 x i32> [[TMP185]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP202:%.*]] = shufflevector <2 x i32> [[TMP188]], <2 x i32> [[TMP185]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP292:%.*]] = add <2 x i32> [[TMP201]], [[TMP202]]
; CHECK-NEXT:    [[TMP304:%.*]] = shufflevector <2 x i32> [[TMP185]], <2 x i32> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[TMP309:%.*]] = shufflevector <2 x i32> [[TMP304]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP311:%.*]] = shufflevector <2 x i32> <i32 15, i32 poison>, <2 x i32> [[TMP185]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP207:%.*]] = lshr <2 x i32> [[TMP309]], [[TMP311]]
; CHECK-NEXT:    [[TMP226:%.*]] = add <2 x i32> [[TMP309]], [[TMP311]]
; CHECK-NEXT:    [[TMP209:%.*]] = shufflevector <2 x i32> [[TMP207]], <2 x i32> [[TMP226]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP222:%.*]] = shufflevector <2 x i32> [[TMP71]], <2 x i32> [[TMP292]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP313:%.*]] = shufflevector <2 x i32> [[TMP71]], <2 x i32> [[TMP292]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP214:%.*]] = sub <2 x i32> [[TMP222]], [[TMP313]]
; CHECK-NEXT:    [[TMP215:%.*]] = shufflevector <2 x i32> <i32 65537, i32 poison>, <2 x i32> [[TMP213]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP216:%.*]] = and <2 x i32> [[TMP209]], [[TMP215]]
; CHECK-NEXT:    [[TMP239:%.*]] = sub <2 x i32> [[TMP209]], [[TMP215]]
; CHECK-NEXT:    [[TMP218:%.*]] = shufflevector <2 x i32> [[TMP216]], <2 x i32> [[TMP239]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD105_1:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP214]])
; CHECK-NEXT:    [[ADD78_1:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP292]])
; CHECK-NEXT:    [[TMP221:%.*]] = insertelement <2 x i32> poison, i32 [[ADD105_1]], i32 0
; CHECK-NEXT:    [[TMP233:%.*]] = shufflevector <2 x i32> [[TMP221]], <2 x i32> [[TMP292]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP223:%.*]] = add <2 x i32> [[TMP213]], [[TMP233]]
; CHECK-NEXT:    [[ADD103_1:%.*]] = add i32 [[ADD94_1]], [[ADD78_1]]
; CHECK-NEXT:    [[TMP224:%.*]] = shufflevector <2 x i32> <i32 65535, i32 poison>, <2 x i32> [[TMP214]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP225:%.*]] = mul <2 x i32> [[TMP218]], [[TMP224]]
; CHECK-NEXT:    [[TMP257:%.*]] = sub <2 x i32> [[TMP218]], [[TMP224]]
; CHECK-NEXT:    [[TMP227:%.*]] = shufflevector <2 x i32> [[TMP225]], <2 x i32> [[TMP257]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD_I_1:%.*]] = add i32 [[MUL_I_2]], [[ADD103_1]]
; CHECK-NEXT:    [[XOR_I_1:%.*]] = xor i32 [[ADD_I_1]], [[TMP77]]
; CHECK-NEXT:    [[TMP262:%.*]] = insertelement <2 x i32> poison, i32 [[TMP78]], i32 0
; CHECK-NEXT:    [[TMP228:%.*]] = insertelement <2 x i32> [[TMP262]], i32 [[ADD94_1]], i32 1
; CHECK-NEXT:    [[TMP229:%.*]] = xor <2 x i32> [[TMP223]], [[TMP228]]
; CHECK-NEXT:    [[TMP263:%.*]] = sub <2 x i32> [[TMP223]], [[TMP228]]
; CHECK-NEXT:    [[TMP251:%.*]] = shufflevector <2 x i32> [[TMP229]], <2 x i32> [[TMP263]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD_I62_1:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP227]])
; CHECK-NEXT:    [[XOR_I63_1:%.*]] = xor i32 [[ADD_I62_1]], [[TMP122]]
; CHECK-NEXT:    [[TMP237:%.*]] = insertelement <2 x i32> poison, i32 [[XOR_I_1]], i32 0
; CHECK-NEXT:    [[TMP246:%.*]] = shufflevector <2 x i32> [[TMP237]], <2 x i32> [[TMP188]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP261:%.*]] = insertelement <2 x i32> poison, i32 [[ADD94_3]], i32 0
; CHECK-NEXT:    [[TMP245:%.*]] = shufflevector <2 x i32> [[TMP261]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP266:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP92]])
; CHECK-NEXT:    [[TMP271:%.*]] = shufflevector <2 x i32> [[TMP147]], <2 x i32> [[TMP92]], <2 x i32> <i32 1, i32 3>
; CHECK-NEXT:    [[TMP272:%.*]] = shufflevector <2 x i32> [[TMP147]], <2 x i32> [[TMP92]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP273:%.*]] = add <2 x i32> [[TMP271]], [[TMP272]]
; CHECK-NEXT:    [[TMP277:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP147]])
; CHECK-NEXT:    [[TMP205:%.*]] = insertelement <2 x i32> poison, i32 [[AND_I50_1]], i32 0
; CHECK-NEXT:    [[TMP206:%.*]] = insertelement <2 x i32> [[TMP205]], i32 [[TMP277]], i32 1
; CHECK-NEXT:    [[TMP278:%.*]] = insertelement <2 x i32> <i32 65535, i32 poison>, i32 [[TMP150]], i32 1
; CHECK-NEXT:    [[TMP208:%.*]] = mul <2 x i32> [[TMP206]], [[TMP278]]
; CHECK-NEXT:    [[TMP280:%.*]] = add <2 x i32> [[TMP206]], [[TMP278]]
; CHECK-NEXT:    [[TMP210:%.*]] = shufflevector <2 x i32> [[TMP208]], <2 x i32> [[TMP280]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[SHR_I54:%.*]] = lshr i32 [[TMP277]], 15
; CHECK-NEXT:    [[AND_I55:%.*]] = and i32 [[SHR_I54]], 65537
; CHECK-NEXT:    [[ADD48:%.*]] = add i32 [[TMP266]], [[TMP119]]
; CHECK-NEXT:    [[TMP211:%.*]] = insertelement <2 x i32> poison, i32 [[TMP266]], i32 0
; CHECK-NEXT:    [[TMP212:%.*]] = shufflevector <2 x i32> [[TMP211]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP281:%.*]] = insertelement <2 x i32> <i32 15, i32 poison>, i32 [[TMP119]], i32 1
; CHECK-NEXT:    [[TMP282:%.*]] = lshr <2 x i32> [[TMP212]], [[TMP281]]
; CHECK-NEXT:    [[TMP286:%.*]] = add <2 x i32> [[TMP212]], [[TMP281]]
; CHECK-NEXT:    [[TMP290:%.*]] = shufflevector <2 x i32> [[TMP282]], <2 x i32> [[TMP286]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP217:%.*]] = insertelement <2 x i32> [[TMP65]], i32 [[ADD48]], i32 1
; CHECK-NEXT:    [[TMP291:%.*]] = shufflevector <2 x i32> [[TMP65]], <2 x i32> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[TMP219:%.*]] = shufflevector <2 x i32> [[TMP291]], <2 x i32> [[TMP210]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP220:%.*]] = sub <2 x i32> [[TMP217]], [[TMP219]]
; CHECK-NEXT:    [[TMP293:%.*]] = shufflevector <2 x i32> <i32 65537, i32 poison>, <2 x i32> [[TMP210]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP298:%.*]] = and <2 x i32> [[TMP290]], [[TMP293]]
; CHECK-NEXT:    [[TMP299:%.*]] = sub <2 x i32> [[TMP290]], [[TMP293]]
; CHECK-NEXT:    [[TMP300:%.*]] = shufflevector <2 x i32> [[TMP298]], <2 x i32> [[TMP299]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP301:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP220]])
; CHECK-NEXT:    [[TMP302:%.*]] = add <2 x i32> [[TMP219]], [[TMP217]]
; CHECK-NEXT:    [[TMP303:%.*]] = insertelement <2 x i32> poison, i32 [[TMP301]], i32 0
; CHECK-NEXT:    [[TMP310:%.*]] = insertelement <2 x i32> [[TMP303]], i32 [[ADD48]], i32 1
; CHECK-NEXT:    [[TMP312:%.*]] = add <2 x i32> [[TMP210]], [[TMP310]]
; CHECK-NEXT:    [[TMP230:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP302]])
; CHECK-NEXT:    [[TMP231:%.*]] = shufflevector <2 x i32> <i32 65535, i32 poison>, <2 x i32> [[TMP220]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP232:%.*]] = mul <2 x i32> [[TMP300]], [[TMP231]]
; CHECK-NEXT:    [[TMP314:%.*]] = sub <2 x i32> [[TMP300]], [[TMP231]]
; CHECK-NEXT:    [[TMP234:%.*]] = shufflevector <2 x i32> [[TMP232]], <2 x i32> [[TMP314]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD_I:%.*]] = add i32 [[MUL_I_1]], [[TMP230]]
; CHECK-NEXT:    [[TMP235:%.*]] = insertelement <2 x i32> poison, i32 [[ADD_I]], i32 0
; CHECK-NEXT:    [[TMP236:%.*]] = insertelement <2 x i32> [[TMP235]], i32 [[AND_I55]], i32 1
; CHECK-NEXT:    [[TMP238:%.*]] = insertelement <2 x i32> <i32 poison, i32 65535>, i32 [[CONV_3]], i32 0
; CHECK-NEXT:    [[TMP240:%.*]] = xor <2 x i32> [[TMP236]], [[TMP238]]
; CHECK-NEXT:    [[TMP315:%.*]] = mul <2 x i32> [[TMP236]], [[TMP238]]
; CHECK-NEXT:    [[TMP316:%.*]] = shufflevector <2 x i32> [[TMP240]], <2 x i32> [[TMP315]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP317:%.*]] = shufflevector <2 x i32> [[TMP28]], <2 x i32> poison, <2 x i32> <i32 1, i32 poison>
; CHECK-NEXT:    [[TMP242:%.*]] = shufflevector <2 x i32> [[TMP317]], <2 x i32> [[TMP302]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP243:%.*]] = xor <2 x i32> [[TMP312]], [[TMP242]]
; CHECK-NEXT:    [[TMP318:%.*]] = sub <2 x i32> [[TMP312]], [[TMP242]]
; CHECK-NEXT:    [[TMP319:%.*]] = shufflevector <2 x i32> [[TMP243]], <2 x i32> [[TMP318]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP241:%.*]] = add <2 x i32> [[TMP319]], [[TMP316]]
; CHECK-NEXT:    [[TMP323:%.*]] = extractelement <2 x i32> [[TMP241]], i32 1
; CHECK-NEXT:    [[XOR_I58:%.*]] = xor i32 [[TMP323]], [[TMP277]]
; CHECK-NEXT:    [[TMP320:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP234]])
; CHECK-NEXT:    [[XOR_I63:%.*]] = xor i32 [[TMP320]], [[TMP266]]
; CHECK-NEXT:    [[TMP321:%.*]] = extractelement <2 x i32> [[TMP241]], i32 0
; CHECK-NEXT:    [[ADD112:%.*]] = add i32 [[TMP321]], [[XOR_I58]]
; CHECK-NEXT:    [[ADD94_2:%.*]] = add i32 [[ADD112]], [[XOR_I63]]
; CHECK-NEXT:    [[TMP244:%.*]] = insertelement <2 x i32> poison, i32 [[ADD94_2]], i32 0
; CHECK-NEXT:    [[TMP322:%.*]] = insertelement <2 x i32> [[TMP244]], i32 [[MUL_I56_1]], i32 1
; CHECK-NEXT:    [[TMP324:%.*]] = add <2 x i32> [[TMP251]], [[TMP322]]
; CHECK-NEXT:    [[TMP253:%.*]] = add <2 x i32> [[TMP324]], [[TMP246]]
; CHECK-NEXT:    [[TMP254:%.*]] = xor <2 x i32> [[TMP324]], [[TMP246]]
; CHECK-NEXT:    [[TMP325:%.*]] = shufflevector <2 x i32> [[TMP253]], <2 x i32> [[TMP254]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP339:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP325]])
; CHECK-NEXT:    [[ADD113_1:%.*]] = add i32 [[TMP339]], [[XOR_I63_1]]
; CHECK-NEXT:    [[TMP340:%.*]] = insertelement <2 x i32> poison, i32 [[TMP150]], i32 0
; CHECK-NEXT:    [[TMP341:%.*]] = insertelement <2 x i32> [[TMP340]], i32 [[TMP119]], i32 1
; CHECK-NEXT:    [[TMP247:%.*]] = sub <2 x i32> [[TMP341]], [[TMP273]]
; CHECK-NEXT:    [[TMP114:%.*]] = insertelement <2 x i32> poison, i32 [[TMP119]], i32 0
; CHECK-NEXT:    [[TMP248:%.*]] = shufflevector <2 x i32> [[TMP114]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP249:%.*]] = shufflevector <2 x i32> <i32 15, i32 poison>, <2 x i32> [[TMP273]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP250:%.*]] = lshr <2 x i32> [[TMP248]], [[TMP249]]
; CHECK-NEXT:    [[TMP276:%.*]] = sub <2 x i32> [[TMP248]], [[TMP249]]
; CHECK-NEXT:    [[TMP252:%.*]] = shufflevector <2 x i32> [[TMP250]], <2 x i32> [[TMP276]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD78_2:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP247]])
; CHECK-NEXT:    [[TMP342:%.*]] = shufflevector <2 x i32> [[TMP247]], <2 x i32> [[TMP69]], <2 x i32> <i32 3, i32 1>
; CHECK-NEXT:    [[TMP268:%.*]] = shufflevector <2 x i32> [[TMP247]], <2 x i32> poison, <2 x i32> <i32 poison, i32 0>
; CHECK-NEXT:    [[TMP343:%.*]] = shufflevector <2 x i32> [[TMP268]], <2 x i32> [[TMP69]], <2 x i32> <i32 2, i32 1>
; CHECK-NEXT:    [[TMP270:%.*]] = sub <2 x i32> [[TMP342]], [[TMP343]]
; CHECK-NEXT:    [[TMP255:%.*]] = shufflevector <2 x i32> <i32 65537, i32 poison>, <2 x i32> [[TMP247]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP256:%.*]] = and <2 x i32> [[TMP252]], [[TMP255]]
; CHECK-NEXT:    [[TMP279:%.*]] = sub <2 x i32> [[TMP252]], [[TMP255]]
; CHECK-NEXT:    [[TMP258:%.*]] = shufflevector <2 x i32> [[TMP256]], <2 x i32> [[TMP279]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP259:%.*]] = insertelement <2 x i32> poison, i32 [[ADD78_2]], i32 0
; CHECK-NEXT:    [[TMP260:%.*]] = shufflevector <2 x i32> [[TMP259]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP296:%.*]] = add <2 x i32> [[TMP260]], [[TMP245]]
; CHECK-NEXT:    [[TMP297:%.*]] = sub <2 x i32> [[TMP260]], [[TMP245]]
; CHECK-NEXT:    [[TMP328:%.*]] = shufflevector <2 x i32> [[TMP296]], <2 x i32> [[TMP297]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD105_2:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP270]])
; CHECK-NEXT:    [[TMP264:%.*]] = shufflevector <2 x i32> <i32 65535, i32 poison>, <2 x i32> [[TMP270]], <2 x i32> <i32 0, i32 2>
; CHECK-NEXT:    [[TMP265:%.*]] = mul <2 x i32> [[TMP258]], [[TMP264]]
; CHECK-NEXT:    [[TMP329:%.*]] = sub <2 x i32> [[TMP258]], [[TMP264]]
; CHECK-NEXT:    [[TMP267:%.*]] = shufflevector <2 x i32> [[TMP265]], <2 x i32> [[TMP329]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[ADD_I52_2:%.*]] = add i32 [[MUL_I51_2]], [[ADD105_2]]
; CHECK-NEXT:    [[XOR_I53_2:%.*]] = xor i32 [[ADD_I52_2]], [[CONV_1]]
; CHECK-NEXT:    [[TMP285:%.*]] = add <2 x i32> [[TMP177]], [[TMP328]]
; CHECK-NEXT:    [[TMP269:%.*]] = xor <2 x i32> [[TMP285]], [[TMP174]]
; CHECK-NEXT:    [[ADD_I62_2:%.*]] = call i32 @llvm.vector.reduce.add.v2i32(<2 x i32> [[TMP267]])
; CHECK-NEXT:    [[XOR_I63_2:%.*]] = xor i32 [[ADD_I62_2]], [[TMP119]]
; CHECK-NEXT:    [[ADD108_2:%.*]] = add i32 [[XOR_I53_2]], [[ADD113_1]]
; CHECK-NEXT:    [[TMP326:%.*]] = extractelement <2 x i32> [[TMP269]], i32 0
; CHECK-NEXT:    [[ADD110_2:%.*]] = add i32 [[ADD108_2]], [[TMP326]]
; CHECK-NEXT:    [[TMP327:%.*]] = extractelement <2 x i32> [[TMP269]], i32 1
; CHECK-NEXT:    [[ADD112_2:%.*]] = add i32 [[ADD110_2]], [[TMP327]]
; CHECK-NEXT:    [[ADD113_2:%.*]] = add i32 [[ADD112_2]], [[XOR_I63_2]]
; CHECK-NEXT:    [[TMP274:%.*]] = insertelement <2 x i32> poison, i32 [[SUB59]], i32 0
; CHECK-NEXT:    [[TMP275:%.*]] = shufflevector <2 x i32> [[TMP274]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP330:%.*]] = add <2 x i32> [[TMP275]], [[TMP181]]
; CHECK-NEXT:    [[TMP331:%.*]] = sub <2 x i32> [[TMP275]], [[TMP181]]
; CHECK-NEXT:    [[TMP332:%.*]] = shufflevector <2 x i32> [[TMP330]], <2 x i32> [[TMP331]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP333:%.*]] = shufflevector <2 x i32> [[TMP331]], <2 x i32> [[TMP330]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP334:%.*]] = shufflevector <2 x i32> [[TMP104]], <2 x i32> [[TMP98]], <2 x i32> <i32 0, i32 3>
; CHECK-NEXT:    [[TMP335:%.*]] = add <2 x i32> [[TMP334]], [[TMP333]]
; CHECK-NEXT:    [[TMP336:%.*]] = sub <2 x i32> [[TMP332]], [[TMP105]]
; CHECK-NEXT:    [[TMP283:%.*]] = add <2 x i32> [[TMP118]], [[TMP335]]
; CHECK-NEXT:    [[TMP284:%.*]] = xor <2 x i32> [[TMP283]], [[TMP101]]
; CHECK-NEXT:    [[TMP337:%.*]] = lshr <2 x i32> [[TMP82]], splat (i32 15)
; CHECK-NEXT:    [[TMP338:%.*]] = and <2 x i32> [[TMP337]], splat (i32 65537)
; CHECK-NEXT:    [[TMP287:%.*]] = mul <2 x i32> [[TMP338]], splat (i32 65535)
; CHECK-NEXT:    [[TMP288:%.*]] = add <2 x i32> [[TMP287]], [[TMP336]]
; CHECK-NEXT:    [[TMP289:%.*]] = xor <2 x i32> [[TMP288]], [[TMP82]]
; CHECK-NEXT:    [[TMP305:%.*]] = extractelement <2 x i32> [[TMP284]], i32 0
; CHECK-NEXT:    [[ADD108_3:%.*]] = add i32 [[TMP305]], [[ADD113_2]]
; CHECK-NEXT:    [[TMP306:%.*]] = extractelement <2 x i32> [[TMP284]], i32 1
; CHECK-NEXT:    [[ADD110_3:%.*]] = add i32 [[ADD108_3]], [[TMP306]]
; CHECK-NEXT:    [[TMP307:%.*]] = extractelement <2 x i32> [[TMP289]], i32 0
; CHECK-NEXT:    [[ADD112_3:%.*]] = add i32 [[ADD110_3]], [[TMP307]]
; CHECK-NEXT:    [[TMP308:%.*]] = extractelement <2 x i32> [[TMP289]], i32 1
; CHECK-NEXT:    [[ADD113_3:%.*]] = add i32 [[ADD112_3]], [[TMP308]]
; CHECK-NEXT:    ret i32 [[ADD113_3]]
;
entry:
  %0 = load i8, ptr %pix1, align 1
  %conv = zext i8 %0 to i32
  %1 = load i8, ptr %pix2, align 1
  %conv2 = zext i8 %1 to i32
  %sub = sub i32 %conv, %conv2
  %arrayidx3 = getelementptr i8, ptr %pix1, i64 4
  %2 = load i8, ptr %arrayidx3, align 1
  %conv4 = zext i8 %2 to i32
  %arrayidx5 = getelementptr i8, ptr %pix2, i64 4
  %3 = load i8, ptr %arrayidx5, align 1
  %conv6 = zext i8 %3 to i32
  %sub7 = sub i32 %conv4, %conv6
  %shl = shl i32 %sub7, 16
  %add = add i32 %shl, %sub
  %arrayidx8 = getelementptr i8, ptr %pix1, i64 1
  %4 = load i8, ptr %arrayidx8, align 1
  %conv9 = zext i8 %4 to i32
  %arrayidx10 = getelementptr i8, ptr %pix2, i64 1
  %5 = load i8, ptr %arrayidx10, align 1
  %conv11 = zext i8 %5 to i32
  %sub12 = sub i32 %conv9, %conv11
  %arrayidx13 = getelementptr i8, ptr %pix1, i64 5
  %6 = load i8, ptr %arrayidx13, align 1
  %conv14 = zext i8 %6 to i32
  %arrayidx15 = getelementptr i8, ptr %pix2, i64 5
  %7 = load i8, ptr %arrayidx15, align 1
  %conv16 = zext i8 %7 to i32
  %sub17 = sub i32 %conv14, %conv16
  %shl18 = shl i32 %sub17, 16
  %add19 = add i32 %shl18, %sub12
  %arrayidx20 = getelementptr i8, ptr %pix1, i64 2
  %8 = load i8, ptr %arrayidx20, align 1
  %conv21 = zext i8 %8 to i32
  %arrayidx22 = getelementptr i8, ptr %pix2, i64 2
  %9 = load i8, ptr %arrayidx22, align 1
  %conv23 = zext i8 %9 to i32
  %sub24 = sub i32 %conv21, %conv23
  %arrayidx25 = getelementptr i8, ptr %pix1, i64 6
  %10 = load i8, ptr %arrayidx25, align 1
  %conv26 = zext i8 %10 to i32
  %arrayidx27 = getelementptr i8, ptr %pix2, i64 6
  %11 = load i8, ptr %arrayidx27, align 1
  %conv28 = zext i8 %11 to i32
  %sub29 = sub i32 %conv26, %conv28
  %shl30 = shl i32 %sub29, 16
  %add31 = add i32 %shl30, %sub24
  %arrayidx32 = getelementptr i8, ptr %pix1, i64 3
  %12 = load i8, ptr %arrayidx32, align 1
  %conv33 = zext i8 %12 to i32
  %arrayidx34 = getelementptr i8, ptr %pix2, i64 3
  %13 = load i8, ptr %arrayidx34, align 1
  %conv35 = zext i8 %13 to i32
  %sub36 = sub i32 %conv33, %conv35
  %arrayidx37 = getelementptr i8, ptr %pix1, i64 7
  %14 = load i8, ptr %arrayidx37, align 1
  %conv38 = zext i8 %14 to i32
  %arrayidx39 = getelementptr i8, ptr %pix2, i64 7
  %15 = load i8, ptr %arrayidx39, align 1
  %conv40 = zext i8 %15 to i32
  %sub41 = sub i32 %conv38, %conv40
  %shl42 = shl i32 %sub41, 16
  %add43 = add i32 %shl42, %sub36
  %add44 = add i32 %add19, %add
  %sub45 = sub i32 %add, %add19
  %add46 = add i32 %add43, %add31
  %sub47 = sub i32 %add31, %add43
  %add48 = add i32 %add46, %add44
  %sub51 = sub i32 %add44, %add46
  %add55 = add i32 %sub47, %sub45
  %sub59 = sub i32 %sub45, %sub47
  %add.ptr3 = getelementptr i8, ptr %pix1, i64 %idx.ext
  %add.ptr644 = getelementptr i8, ptr %pix2, i64 %idx.ext63
  %16 = load i8, ptr %add.ptr3, align 1
  %conv.1 = zext i8 %16 to i32
  %17 = load i8, ptr %add.ptr644, align 1
  %conv2.1 = zext i8 %17 to i32
  %sub.1 = sub i32 %conv.1, %conv2.1
  %arrayidx3.1 = getelementptr i8, ptr %add.ptr3, i64 4
  %18 = load i8, ptr %arrayidx3.1, align 1
  %conv4.1 = zext i8 %18 to i32
  %arrayidx5.1 = getelementptr i8, ptr %add.ptr644, i64 4
  %19 = load i8, ptr %arrayidx5.1, align 1
  %conv6.1 = zext i8 %19 to i32
  %sub7.1 = sub i32 %conv4.1, %conv6.1
  %shl.1 = shl i32 %sub7.1, 16
  %add.1 = add i32 %shl.1, %sub.1
  %arrayidx8.1 = getelementptr i8, ptr %add.ptr3, i64 1
  %20 = load i8, ptr %arrayidx8.1, align 1
  %conv9.1 = zext i8 %20 to i32
  %arrayidx10.1 = getelementptr i8, ptr %add.ptr644, i64 1
  %21 = load i8, ptr %arrayidx10.1, align 1
  %conv11.1 = zext i8 %21 to i32
  %sub12.1 = sub i32 %conv9.1, %conv11.1
  %arrayidx13.1 = getelementptr i8, ptr %add.ptr3, i64 5
  %22 = load i8, ptr %arrayidx13.1, align 1
  %conv14.1 = zext i8 %22 to i32
  %arrayidx15.1 = getelementptr i8, ptr %add.ptr644, i64 5
  %23 = load i8, ptr %arrayidx15.1, align 1
  %conv16.1 = zext i8 %23 to i32
  %sub17.1 = sub i32 %conv14.1, %conv16.1
  %shl18.1 = shl i32 %sub17.1, 16
  %add19.1 = add i32 %shl18.1, %sub12.1
  %arrayidx20.1 = getelementptr i8, ptr %add.ptr3, i64 2
  %24 = load i8, ptr %arrayidx20.1, align 1
  %conv21.1 = zext i8 %24 to i32
  %arrayidx22.1 = getelementptr i8, ptr %add.ptr644, i64 2
  %25 = load i8, ptr %arrayidx22.1, align 1
  %conv23.1 = zext i8 %25 to i32
  %sub24.1 = sub i32 %conv21.1, %conv23.1
  %arrayidx25.1 = getelementptr i8, ptr %add.ptr3, i64 6
  %26 = load i8, ptr %arrayidx25.1, align 1
  %conv26.1 = zext i8 %26 to i32
  %arrayidx27.1 = getelementptr i8, ptr %add.ptr644, i64 6
  %27 = load i8, ptr %arrayidx27.1, align 1
  %conv28.1 = zext i8 %27 to i32
  %sub29.1 = sub i32 %conv26.1, %conv28.1
  %shl30.1 = shl i32 %sub29.1, 16
  %add31.1 = add i32 %shl30.1, %sub24.1
  %arrayidx32.1 = getelementptr i8, ptr %add.ptr3, i64 3
  %28 = load i8, ptr %arrayidx32.1, align 1
  %conv33.1 = zext i8 %28 to i32
  %arrayidx34.1 = getelementptr i8, ptr %add.ptr644, i64 3
  %29 = load i8, ptr %arrayidx34.1, align 1
  %conv35.1 = zext i8 %29 to i32
  %sub36.1 = sub i32 %conv33.1, %conv35.1
  %arrayidx37.1 = getelementptr i8, ptr %add.ptr3, i64 7
  %30 = load i8, ptr %arrayidx37.1, align 1
  %conv38.1 = zext i8 %30 to i32
  %arrayidx39.1 = getelementptr i8, ptr %add.ptr644, i64 7
  %31 = load i8, ptr %arrayidx39.1, align 1
  %conv40.1 = zext i8 %31 to i32
  %sub41.1 = sub i32 %conv38.1, %conv40.1
  %shl42.1 = shl i32 %sub41.1, 16
  %add43.1 = add i32 %shl42.1, %sub36.1
  %add44.1 = add i32 %add19.1, %add.1
  %sub45.1 = sub i32 %add.1, %add19.1
  %add46.1 = add i32 %add43.1, %add31.1
  %sub47.1 = sub i32 %add31.1, %add43.1
  %add48.1 = add i32 %add46.1, %add44.1
  %sub51.1 = sub i32 %add44.1, %add46.1
  %add55.1 = add i32 %sub47.1, %sub45.1
  %sub59.1 = sub i32 %sub45.1, %sub47.1
  %add.ptr.1 = getelementptr i8, ptr %add.ptr, i64 %idx.ext
  %add.ptr64.1 = getelementptr i8, ptr %add.ptr64, i64 %idx.ext63
  %32 = load i8, ptr %add.ptr.1, align 1
  %conv.2 = zext i8 %32 to i32
  %33 = load i8, ptr %add.ptr64.1, align 1
  %conv2.2 = zext i8 %33 to i32
  %sub.2 = sub i32 %conv.2, %conv2.2
  %arrayidx3.2 = getelementptr i8, ptr %add.ptr.1, i64 4
  %34 = load i8, ptr %arrayidx3.2, align 1
  %conv4.2 = zext i8 %34 to i32
  %arrayidx5.2 = getelementptr i8, ptr %add.ptr64.1, i64 4
  %35 = load i8, ptr %arrayidx5.2, align 1
  %conv6.2 = zext i8 %35 to i32
  %sub7.2 = sub i32 %conv4.2, %conv6.2
  %shl.2 = shl i32 %sub7.2, 16
  %add.2 = add i32 %shl.2, %sub.2
  %arrayidx8.2 = getelementptr i8, ptr %add.ptr.1, i64 1
  %36 = load i8, ptr %arrayidx8.2, align 1
  %conv9.2 = zext i8 %36 to i32
  %arrayidx10.2 = getelementptr i8, ptr %add.ptr64.1, i64 1
  %37 = load i8, ptr %arrayidx10.2, align 1
  %conv11.2 = zext i8 %37 to i32
  %sub12.2 = sub i32 %conv9.2, %conv11.2
  %arrayidx13.2 = getelementptr i8, ptr %add.ptr.1, i64 5
  %38 = load i8, ptr %arrayidx13.2, align 1
  %conv14.2 = zext i8 %38 to i32
  %arrayidx15.2 = getelementptr i8, ptr %add.ptr64.1, i64 5
  %39 = load i8, ptr %arrayidx15.2, align 1
  %conv16.2 = zext i8 %39 to i32
  %sub17.2 = sub i32 %conv14.2, %conv16.2
  %shl18.2 = shl i32 %sub17.2, 16
  %add19.2 = add i32 %shl18.2, %sub12.2
  %arrayidx20.2 = getelementptr i8, ptr %add.ptr.1, i64 2
  %40 = load i8, ptr %arrayidx20.2, align 1
  %conv21.2 = zext i8 %40 to i32
  %arrayidx22.2 = getelementptr i8, ptr %add.ptr64.1, i64 2
  %41 = load i8, ptr %arrayidx22.2, align 1
  %conv23.2 = zext i8 %41 to i32
  %sub24.2 = sub i32 %conv21.2, %conv23.2
  %arrayidx25.2 = getelementptr i8, ptr %add.ptr.1, i64 6
  %42 = load i8, ptr %arrayidx25.2, align 1
  %conv26.2 = zext i8 %42 to i32
  %arrayidx27.2 = getelementptr i8, ptr %add.ptr64.1, i64 6
  %43 = load i8, ptr %arrayidx27.2, align 1
  %conv28.2 = zext i8 %43 to i32
  %sub29.2 = sub i32 %conv26.2, %conv28.2
  %shl30.2 = shl i32 %sub29.2, 16
  %add31.2 = add i32 %shl30.2, %sub24.2
  %arrayidx32.2 = getelementptr i8, ptr %add.ptr.1, i64 3
  %44 = load i8, ptr %arrayidx32.2, align 1
  %conv33.2 = zext i8 %44 to i32
  %arrayidx34.2 = getelementptr i8, ptr %add.ptr64.1, i64 3
  %45 = load i8, ptr %arrayidx34.2, align 1
  %conv35.2 = zext i8 %45 to i32
  %sub36.2 = sub i32 %conv33.2, %conv35.2
  %arrayidx37.2 = getelementptr i8, ptr %add.ptr.1, i64 7
  %46 = load i8, ptr %arrayidx37.2, align 1
  %conv38.2 = zext i8 %46 to i32
  %arrayidx39.2 = getelementptr i8, ptr %add.ptr64.1, i64 7
  %47 = load i8, ptr %arrayidx39.2, align 1
  %conv40.2 = zext i8 %47 to i32
  %sub41.2 = sub i32 %conv38.2, %conv40.2
  %shl42.2 = shl i32 %sub41.2, 16
  %add43.2 = add i32 %shl42.2, %sub36.2
  %add44.2 = add i32 %add19.2, %add.2
  %sub45.2 = sub i32 %add.2, %add19.2
  %add46.2 = add i32 %add43.2, %add31.2
  %sub47.2 = sub i32 %add31.2, %add43.2
  %add48.2 = add i32 %add46.2, %add44.2
  %sub51.2 = sub i32 %add44.2, %add46.2
  %add55.2 = add i32 %sub47.2, %sub45.2
  %sub59.2 = sub i32 %sub45.2, %sub47.2
  %48 = load i8, ptr null, align 1
  %conv.3 = zext i8 %48 to i32
  %49 = load i8, ptr null, align 1
  %conv2.3 = zext i8 %49 to i32
  %sub.3 = sub i32 %conv.3, %conv2.3
  %arrayidx3.3 = getelementptr i8, ptr null, i64 4
  %50 = load i8, ptr %arrayidx3.3, align 1
  %conv4.3 = zext i8 %50 to i32
  %arrayidx5.3 = getelementptr i8, ptr null, i64 4
  %51 = load i8, ptr %arrayidx5.3, align 1
  %conv6.3 = zext i8 %51 to i32
  %sub7.3 = sub i32 %conv4.3, %conv6.3
  %shl.3 = shl i32 %sub7.3, 16
  %add.3 = add i32 %shl.3, %sub.3
  %arrayidx8.3 = getelementptr i8, ptr null, i64 1
  %52 = load i8, ptr %arrayidx8.3, align 1
  %conv9.3 = zext i8 %52 to i32
  %arrayidx10.3 = getelementptr i8, ptr null, i64 1
  %53 = load i8, ptr %arrayidx10.3, align 1
  %conv11.3 = zext i8 %53 to i32
  %sub12.3 = sub i32 %conv9.3, %conv11.3
  %54 = load i8, ptr null, align 1
  %conv14.3 = zext i8 %54 to i32
  %arrayidx15.3 = getelementptr i8, ptr null, i64 5
  %55 = load i8, ptr %arrayidx15.3, align 1
  %conv16.3 = zext i8 %55 to i32
  %sub17.3 = sub i32 %conv14.3, %conv16.3
  %shl18.3 = shl i32 %sub17.3, 16
  %add19.3 = add i32 %shl18.3, %sub12.3
  %arrayidx20.3 = getelementptr i8, ptr null, i64 2
  %56 = load i8, ptr %arrayidx20.3, align 1
  %conv21.3 = zext i8 %56 to i32
  %arrayidx22.3 = getelementptr i8, ptr null, i64 2
  %57 = load i8, ptr %arrayidx22.3, align 1
  %conv23.3 = zext i8 %57 to i32
  %sub24.3 = sub i32 %conv21.3, %conv23.3
  %58 = load i8, ptr null, align 1
  %conv26.3 = zext i8 %58 to i32
  %arrayidx27.3 = getelementptr i8, ptr null, i64 6
  %59 = load i8, ptr %arrayidx27.3, align 1
  %conv28.3 = zext i8 %59 to i32
  %sub29.3 = sub i32 %conv26.3, %conv28.3
  %shl30.3 = shl i32 %sub29.3, 16
  %add31.3 = add i32 %shl30.3, %sub24.3
  %arrayidx32.3 = getelementptr i8, ptr null, i64 3
  %60 = load i8, ptr %arrayidx32.3, align 1
  %conv33.3 = zext i8 %60 to i32
  %arrayidx34.3 = getelementptr i8, ptr null, i64 3
  %61 = load i8, ptr %arrayidx34.3, align 1
  %conv35.3 = zext i8 %61 to i32
  %sub36.3 = sub i32 %conv33.3, %conv35.3
  %62 = load i8, ptr null, align 1
  %conv38.3 = zext i8 %62 to i32
  %arrayidx39.3 = getelementptr i8, ptr null, i64 7
  %63 = load i8, ptr %arrayidx39.3, align 1
  %conv40.3 = zext i8 %63 to i32
  %sub41.3 = sub i32 %conv38.3, %conv40.3
  %shl42.3 = shl i32 %sub41.3, 16
  %add43.3 = add i32 %shl42.3, %sub36.3
  %add44.3 = add i32 %add19.3, %add.3
  %sub45.3 = sub i32 %add.3, %add19.3
  %add46.3 = add i32 %add43.3, %add31.3
  %sub47.3 = sub i32 %add31.3, %add43.3
  %add48.3 = add i32 %add46.3, %add44.3
  %sub51.3 = sub i32 %add44.3, %add46.3
  %add55.3 = add i32 %sub47.3, %sub45.3
  %sub59.3 = sub i32 %sub45.3, %sub47.3
  %add78 = add i32 %add48.1, %add48
  %sub86 = sub i32 %add48, %add48.1
  %add94 = add i32 %add48.3, %add48.2
  %sub102 = sub i32 %add48.2, %add48.3
  %add103 = add i32 %add94, %add78
  %sub104 = sub i32 %add78, %add94
  %add105 = add i32 %sub102, %sub86
  %sub106 = sub i32 %sub86, %sub102
  %shr.i = lshr i32 %conv.3, 15
  %and.i = and i32 %shr.i, 65537
  %mul.i = mul i32 %and.i, 65535
  %add.i = add i32 %mul.i, %add103
  %xor.i = xor i32 %add.i, %conv.3
  %shr.i49 = lshr i32 %add46.2, 15
  %and.i50 = and i32 %shr.i49, 65537
  %mul.i51 = mul i32 %and.i50, 65535
  %add.i52 = add i32 %mul.i51, %add105
  %xor.i53 = xor i32 %add.i52, %add46.2
  %shr.i54 = lshr i32 %add46.1, 15
  %and.i55 = and i32 %shr.i54, 65537
  %mul.i56 = mul i32 %and.i55, 65535
  %add.i57 = add i32 %mul.i56, %sub104
  %xor.i58 = xor i32 %add.i57, %add46.1
  %shr.i59 = lshr i32 %add46, 15
  %and.i60 = and i32 %shr.i59, 65537
  %mul.i61 = mul i32 %and.i60, 65535
  %add.i62 = add i32 %mul.i61, %sub106
  %xor.i63 = xor i32 %add.i62, %add46
  %add110 = add i32 %xor.i53, %xor.i
  %add112 = add i32 %add110, %xor.i58
  %add113 = add i32 %add112, %xor.i63
  %add78.1 = add i32 %add55.1, %add55
  %sub86.1 = sub i32 %add55, %add55.1
  %add94.1 = add i32 %add55.3, %add55.2
  %sub102.1 = sub i32 %add55.2, %add55.3
  %add103.1 = add i32 %add94.1, %add78.1
  %sub104.1 = sub i32 %add78.1, %add94.1
  %add105.1 = add i32 %sub102.1, %sub86.1
  %sub106.1 = sub i32 %sub86.1, %sub102.1
  %shr.i.1 = lshr i32 %conv9.2, 15
  %and.i.1 = and i32 %shr.i.1, 65537
  %mul.i.1 = mul i32 %and.i.1, 65535
  %add.i.1 = add i32 %mul.i.1, %add103.1
  %xor.i.1 = xor i32 %add.i.1, %conv9.2
  %shr.i49.1 = lshr i32 %conv.2, 15
  %and.i50.1 = and i32 %shr.i49.1, 65537
  %mul.i51.1 = mul i32 %and.i50.1, 65535
  %add.i52.1 = add i32 %mul.i51.1, %add105.1
  %xor.i53.1 = xor i32 %add.i52.1, %conv.2
  %shr.i54.1 = lshr i32 %sub47.1, 15
  %and.i55.1 = and i32 %shr.i54.1, 65537
  %mul.i56.1 = mul i32 %and.i55.1, 65535
  %add.i57.1 = add i32 %mul.i56.1, %sub104.1
  %xor.i58.1 = xor i32 %add.i57.1, %sub47.1
  %shr.i59.1 = lshr i32 %sub47, 15
  %and.i60.1 = and i32 %shr.i59.1, 65537
  %mul.i61.1 = mul i32 %and.i60.1, 65535
  %add.i62.1 = add i32 %mul.i61.1, %sub106.1
  %xor.i63.1 = xor i32 %add.i62.1, %sub47
  %add108.1 = add i32 %xor.i53.1, %add113
  %add110.1 = add i32 %add108.1, %xor.i.1
  %add112.1 = add i32 %add110.1, %xor.i58.1
  %add113.1 = add i32 %add112.1, %xor.i63.1
  %add78.2 = add i32 %sub51.1, %sub51
  %sub86.2 = sub i32 %sub51, %sub51.1
  %add94.2 = add i32 %sub51.3, %sub51.2
  %sub102.2 = sub i32 %sub51.2, %sub51.3
  %add103.2 = add i32 %add94.2, %add78.2
  %sub104.2 = sub i32 %add78.2, %add94.2
  %add105.2 = add i32 %sub102.2, %sub86.2
  %sub106.2 = sub i32 %sub86.2, %sub102.2
  %shr.i.2 = lshr i32 %conv9.1, 15
  %and.i.2 = and i32 %shr.i.2, 65537
  %mul.i.2 = mul i32 %and.i.2, 65535
  %add.i.2 = add i32 %mul.i.2, %add103.2
  %xor.i.2 = xor i32 %add.i.2, %conv9.1
  %shr.i49.2 = lshr i32 %conv.1, 15
  %and.i50.2 = and i32 %shr.i49.2, 65537
  %mul.i51.2 = mul i32 %and.i50.2, 65535
  %add.i52.2 = add i32 %mul.i51.2, %add105.2
  %xor.i53.2 = xor i32 %add.i52.2, %conv.1
  %shr.i54.2 = lshr i32 %conv21.1, 15
  %and.i55.2 = and i32 %shr.i54.2, 65537
  %mul.i56.2 = mul i32 %and.i55.2, 65535
  %add.i57.2 = add i32 %mul.i56.2, %sub104.2
  %xor.i58.2 = xor i32 %add.i57.2, %conv21.1
  %shr.i59.2 = lshr i32 %add44, 15
  %and.i60.2 = and i32 %shr.i59.2, 65537
  %mul.i61.2 = mul i32 %and.i60.2, 65535
  %add.i62.2 = add i32 %mul.i61.2, %sub106.2
  %xor.i63.2 = xor i32 %add.i62.2, %add44
  %add108.2 = add i32 %xor.i53.2, %add113.1
  %add110.2 = add i32 %add108.2, %xor.i.2
  %add112.2 = add i32 %add110.2, %xor.i58.2
  %add113.2 = add i32 %add112.2, %xor.i63.2
  %add78.3 = add i32 %sub59.1, %sub59
  %sub86.3 = sub i32 %sub59, %sub59.1
  %add94.3 = add i32 %sub59.3, %sub59.2
  %sub102.3 = sub i32 %sub59.2, %sub59.3
  %add103.3 = add i32 %add94.3, %add78.3
  %sub104.3 = sub i32 %add78.3, %add94.3
  %add105.3 = add i32 %sub102.3, %sub86.3
  %sub106.3 = sub i32 %sub86.3, %sub102.3
  %shr.i.3 = lshr i32 %conv9, 15
  %and.i.3 = and i32 %shr.i.3, 65537
  %mul.i.3 = mul i32 %and.i.3, 65535
  %add.i.3 = add i32 %mul.i.3, %add103.3
  %xor.i.3 = xor i32 %add.i.3, %conv9
  %shr.i49.3 = lshr i32 %conv, 15
  %and.i50.3 = and i32 %shr.i49.3, 65537
  %mul.i51.3 = mul i32 %and.i50.3, 65535
  %add.i52.3 = add i32 %mul.i51.3, %add105.3
  %xor.i53.3 = xor i32 %add.i52.3, %conv
  %shr.i54.3 = lshr i32 %conv21, 15
  %and.i55.3 = and i32 %shr.i54.3, 65537
  %mul.i56.3 = mul i32 %and.i55.3, 65535
  %add.i57.3 = add i32 %mul.i56.3, %sub104.3
  %xor.i58.3 = xor i32 %add.i57.3, %conv21
  %shr.i59.3 = lshr i32 %conv33, 15
  %and.i60.3 = and i32 %shr.i59.3, 65537
  %mul.i61.3 = mul i32 %and.i60.3, 65535
  %add.i62.3 = add i32 %mul.i61.3, %sub106.3
  %xor.i63.3 = xor i32 %add.i62.3, %conv33
  %add108.3 = add i32 %xor.i53.3, %add113.2
  %add110.3 = add i32 %add108.3, %xor.i.3
  %add112.3 = add i32 %add110.3, %xor.i58.3
  %add113.3 = add i32 %add112.3, %xor.i63.3
  ret i32 %add113.3
}
