// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +experimental-zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv1f32.nxv1bf16.i64(<vscale x 1 x float> poison, <vscale x 1 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_sf_vfwcvt_f_bf16_v_f32mf2(vbfloat16mf4_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32mf2(src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv2f32.nxv2bf16.i64(<vscale x 2 x float> poison, <vscale x 2 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_sf_vfwcvt_f_bf16_v_f32m1(vbfloat16mf2_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m1(src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv4f32.nxv4bf16.i64(<vscale x 4 x float> poison, <vscale x 4 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_sf_vfwcvt_f_bf16_v_f32m2(vbfloat16m1_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m2(src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv8f32.nxv8bf16.i64(<vscale x 8 x float> poison, <vscale x 8 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_sf_vfwcvt_f_bf16_v_f32m4(vbfloat16m2_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m4(src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv16f32.nxv16bf16.i64(<vscale x 16 x float> poison, <vscale x 16 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_sf_vfwcvt_f_bf16_v_f32m8(vbfloat16m4_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m8(src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32mf2_m(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv1f32.nxv1bf16.i64(<vscale x 1 x float> [[MASKEDOFF:%.*]], <vscale x 1 x bfloat> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_sf_vfwcvt_f_bf16_v_f32mf2_m(vbool64_t mask, vfloat32mf2_t maskedoff, vbfloat16mf4_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32mf2_m(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m1_m(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv2f32.nxv2bf16.i64(<vscale x 2 x float> [[MASKEDOFF:%.*]], <vscale x 2 x bfloat> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_sf_vfwcvt_f_bf16_v_f32m1_m(vbool32_t mask, vfloat32m1_t maskedoff, vbfloat16mf2_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m1_m(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m2_m(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv4f32.nxv4bf16.i64(<vscale x 4 x float> [[MASKEDOFF:%.*]], <vscale x 4 x bfloat> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_sf_vfwcvt_f_bf16_v_f32m2_m(vbool16_t mask, vfloat32m2_t maskedoff, vbfloat16m1_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m2_m(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m4_m(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv8f32.nxv8bf16.i64(<vscale x 8 x float> [[MASKEDOFF:%.*]], <vscale x 8 x bfloat> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_sf_vfwcvt_f_bf16_v_f32m4_m(vbool8_t mask, vfloat32m4_t maskedoff, vbfloat16m2_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m4_m(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m8_m(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv16f32.nxv16bf16.i64(<vscale x 16 x float> [[MASKEDOFF:%.*]], <vscale x 16 x bfloat> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_sf_vfwcvt_f_bf16_v_f32m8_m(vbool4_t mask, vfloat32m8_t maskedoff, vbfloat16m4_t src, size_t vl) {
  return sf_vfwcvt_f_bf16_v_f32m8_m(mask, maskedoff, src, vl);
}

