// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +experimental-zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vc_x_se_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8mf8.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8mf8(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8mf8(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8mf4.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8mf4(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8mf4(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8mf2.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8mf2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8mf2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8m1.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8m1(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8m1(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8m2.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8m2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8m2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8m4.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8m4(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8m4(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e8m8.i8.i64(i32 0, i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u8m8(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint8_t xs1, size_t vl) {
  return sf_vc_x_se_u8m8(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e16mf4.i16.i64(i32 0, i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u16mf4(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint16_t xs1, size_t vl) {
  return sf_vc_x_se_u16mf4(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e16mf2.i16.i64(i32 0, i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u16mf2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint16_t xs1, size_t vl) {
  return sf_vc_x_se_u16mf2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e16m1.i16.i64(i32 0, i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u16m1(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint16_t xs1, size_t vl) {
  return sf_vc_x_se_u16m1(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e16m2.i16.i64(i32 0, i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u16m2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint16_t xs1, size_t vl) {
  return sf_vc_x_se_u16m2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e16m4.i16.i64(i32 0, i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u16m4(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint16_t xs1, size_t vl) {
  return sf_vc_x_se_u16m4(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e16m8.i16.i64(i32 0, i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u16m8(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint16_t xs1, size_t vl) {
  return sf_vc_x_se_u16m8(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e32mf2.i32.i64(i32 0, i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u32mf2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint32_t xs1, size_t vl) {
  return sf_vc_x_se_u32mf2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e32m1.i32.i64(i32 0, i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u32m1(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint32_t xs1, size_t vl) {
  return sf_vc_x_se_u32m1(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e32m2.i32.i64(i32 0, i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u32m2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint32_t xs1, size_t vl) {
  return sf_vc_x_se_u32m2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e32m4.i32.i64(i32 0, i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u32m4(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint32_t xs1, size_t vl) {
  return sf_vc_x_se_u32m4(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e32m8.i32.i64(i32 0, i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u32m8(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint32_t xs1, size_t vl) {
  return sf_vc_x_se_u32m8(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e64m1.i64.i64(i32 0, i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u64m1(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint64_t xs1, size_t vl) {
  return sf_vc_x_se_u64m1(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e64m2.i64.i64(i32 0, i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u64m2(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint64_t xs1, size_t vl) {
  return sf_vc_x_se_u64m2(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e64m4.i64.i64(i32 0, i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u64m4(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint64_t xs1, size_t vl) {
  return sf_vc_x_se_u64m4(0, 0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_x_se_u64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.x.se.e64m8.i64.i64(i32 0, i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_x_se_u64m8(int bit_field27_26, int bit_field24_20, int bit_field11_7, uint64_t xs1, size_t vl) {
  return sf_vc_x_se_u64m8(0, 0, 0, xs1, vl);
}

