; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare float @llvm.vp.reduce.fadd.nxv4f32(float, <vscale x 4 x float>, <vscale x 4 x i1>, i32)

define float @fadd_rdx(float %x, <vscale x 4 x float> %v, <vscale x 4 x i1> %mask, i32 %evl) {
; CHECK-LABEL: @fadd_rdx(
; CHECK-NEXT:    [[ADD:%.*]] = call fast float @llvm.vp.reduce.fadd.nxv4f32(float [[X:%.*]], <vscale x 4 x float> [[V:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i32 [[EVL:%.*]])
; CHECK-NEXT:    ret float [[ADD]]
;
  %rdx = call fast float @llvm.vp.reduce.fadd.nxv4f32(float 0.0, <vscale x 4 x float> %v, <vscale x 4 x i1> %mask, i32 %evl)
  %add = fadd fast float %rdx, %x
  ret float %add
}

define float @fadd_rdx_commute(float %x, <vscale x 4 x float> %v, <vscale x 4 x i1> %mask, i32 %evl) {
; CHECK-LABEL: @fadd_rdx_commute(
; CHECK-NEXT:    [[D:%.*]] = fdiv float 4.200000e+01, [[X:%.*]]
; CHECK-NEXT:    [[ADD:%.*]] = call reassoc nsz float @llvm.vp.reduce.fadd.nxv4f32(float [[D]], <vscale x 4 x float> [[V:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i32 [[EVL:%.*]])
; CHECK-NEXT:    ret float [[ADD]]
;
  %d = fdiv float 42.0, %x
  %rdx = call float @llvm.vp.reduce.fadd.nxv4f32(float -0.0, <vscale x 4 x float> %v, <vscale x 4 x i1> %mask, i32 %evl)
  %add = fadd reassoc nsz float %d, %rdx
  ret float %add
}

; Negative test - require nsz to be safer (and reassoc obviously).

define float @fadd_rdx_fmf(float %x, <vscale x 4 x float> %v, <vscale x 4 x i1> %mask, i32 %evl) {
; CHECK-LABEL: @fadd_rdx_fmf(
; CHECK-NEXT:    [[RDX:%.*]] = call float @llvm.vp.reduce.fadd.nxv4f32(float 0.000000e+00, <vscale x 4 x float> [[V:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i32 [[EVL:%.*]])
; CHECK-NEXT:    [[ADD:%.*]] = fadd reassoc float [[RDX]], [[X:%.*]]
; CHECK-NEXT:    ret float [[ADD]]
;
  %rdx = call float @llvm.vp.reduce.fadd.nxv4f32(float 0.0, <vscale x 4 x float> %v, <vscale x 4 x i1> %mask, i32 %evl)
  %add = fadd reassoc float %rdx, %x
  ret float %add
}
