; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=instcombine -S %s | FileCheck %s

define i32 @test_i8(i8 %v) {
; CHECK-LABEL: @test_i8(
; CHECK-NEXT:    [[TMP1:%.*]] = call i8 @llvm.abs.i8(i8 [[V:%.*]], i1 false)
; CHECK-NEXT:    [[COND:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[COND]]
;
  %conv = zext i8 %v to i32
  %sub = sub i32 256, %conv
  %cmp6 = icmp slt i8 %v, 0
  %cond = select i1 %cmp6, i32 %sub, i32 %conv
  ret i32 %cond
}

define i32 @test_i16(i16 %v) {
; CHECK-LABEL: @test_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = call i16 @llvm.abs.i16(i16 [[V:%.*]], i1 false)
; CHECK-NEXT:    [[COND:%.*]] = zext i16 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[COND]]
;
  %conv = zext i16 %v to i32
  %sub = sub i32 65536, %conv
  %cmp6 = icmp slt i16 %v, 0
  %cond = select i1 %cmp6, i32 %sub, i32 %conv
  ret i32 %cond
}

define i64 @test_i32(i32 %v) {
; CHECK-LABEL: @test_i32(
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.abs.i32(i32 [[V:%.*]], i1 false)
; CHECK-NEXT:    [[COND:%.*]] = zext i32 [[TMP1]] to i64
; CHECK-NEXT:    ret i64 [[COND]]
;
  %conv = zext i32 %v to i64
  %sub = sub i64 4294967296, %conv
  %cmp6 = icmp slt i32 %v, 0
  %cond = select i1 %cmp6, i64 %sub, i64 %conv
  ret i64 %cond
}

; Test a few other variations to make sure they all get handled.
define i32 @test_i8_2(i8 %v) {
; CHECK-LABEL: @test_i8_2(
; CHECK-NEXT:    [[TMP1:%.*]] = call i8 @llvm.abs.i8(i8 [[V:%.*]], i1 false)
; CHECK-NEXT:    [[COND:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[COND]]
;
  %conv = zext i8 %v to i32
  %sub = sub i32 256, %conv
  %cmp6 = icmp ult i32 %conv, 128
  %cond = select i1 %cmp6, i32 %conv, i32 %sub
  ret i32 %cond
}

define i32 @test_i8_3(i8 %v) {
; CHECK-LABEL: @test_i8_3(
; CHECK-NEXT:    [[TMP1:%.*]] = call i8 @llvm.abs.i8(i8 [[V:%.*]], i1 false)
; CHECK-NEXT:    [[COND:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[COND]]
;
  %conv = zext i8 %v to i32
  %sub = sub i32 256, %conv
  %cmp6 = icmp uge i32 %conv, 128
  %cond = select i1 %cmp6, i32 %sub, i32 %conv
  ret i32 %cond
}

define i32 @test_i8_4(i8 %v) {
; CHECK-LABEL: @test_i8_4(
; CHECK-NEXT:    [[TMP1:%.*]] = call i8 @llvm.abs.i8(i8 [[V:%.*]], i1 false)
; CHECK-NEXT:    [[COND:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    ret i32 [[COND]]
;
  %conv = zext i8 %v to i32
  %sub = sub i32 256, %conv
  %cmp6 = icmp sge i8 %v, 0
  %cond = select i1 %cmp6, i32 %conv, i32 %sub
  ret i32 %cond
}

