; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt %s -passes=instcombine -S | FileCheck %s

define <vscale x 8 x i32> @vp_merge_or(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl) {
; CHECK-LABEL: define <vscale x 8 x i32> @vp_merge_or(
; CHECK-SAME: <vscale x 8 x i1> [[M:%.*]], <vscale x 8 x i32> [[T:%.*]], <vscale x 8 x i32> [[F:%.*]], i32 [[EVL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> [[M]], <vscale x 8 x i32> [[T]], <vscale x 8 x i32> zeroinitializer, i32 [[EVL]])
; CHECK-NEXT:    [[B:%.*]] = or <vscale x 8 x i32> [[F]], [[TMP1]]
; CHECK-NEXT:    ret <vscale x 8 x i32> [[B]]
;
  %a = or <vscale x 8 x i32> %t, %f
  %b = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> %m, <vscale x 8 x i32> %a, <vscale x 8 x i32> %f, i32 %evl)
  ret <vscale x 8 x i32> %b
}

define <vscale x 8 x i32> @vp_merge_or_2(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl) {
; CHECK-LABEL: define <vscale x 8 x i32> @vp_merge_or_2(
; CHECK-SAME: <vscale x 8 x i1> [[M:%.*]], <vscale x 8 x i32> [[T:%.*]], <vscale x 8 x i32> [[F:%.*]], i32 [[EVL:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> [[M]], <vscale x 8 x i32> [[T]], <vscale x 8 x i32> zeroinitializer, i32 [[EVL]])
; CHECK-NEXT:    [[B:%.*]] = or <vscale x 8 x i32> [[F]], [[TMP1]]
; CHECK-NEXT:    ret <vscale x 8 x i32> [[B]]
;
  %a = or <vscale x 8 x i32> %f, %t
  %b = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> %m, <vscale x 8 x i32> %a, <vscale x 8 x i32> %f, i32 %evl)
  ret <vscale x 8 x i32> %b
}
