; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;RUN: opt %s -passes=instcombine -S | FileCheck %s

declare <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i64> @llvm.experimental.vp.reverse.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i16> @llvm.experimental.vp.reverse.nxv2i16(<vscale x 2 x i16>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.sub.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.mul.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.gather.nxv2i32.nxv2p0(<vscale x 2 x ptr>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.fsub.nxv2f32(<vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.fmul.nxv2f32(<vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i64> @llvm.vp.zext.nxv2i64.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i64> @llvm.vp.sext.nxv2i64.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i16> @llvm.vp.sext.nxv2i16.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.sadd.sat.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.ssub.sat.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.uadd.sat.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.usub.sat.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)

define <vscale x 2 x i32> @reverse_reverse(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, <vscale x 2 x i1> %mask2, i32 %vl) {
; CHECK-LABEL: @reverse_reverse(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> [[X1:%.*]], <vscale x 2 x i1> [[MASK1:%.*]], i32 [[VL:%.*]])
; CHECK-NEXT:    [[X:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> [[A]], <vscale x 2 x i1> [[MASK2:%.*]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[X]]
;
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i1> %mask2, i32 %vl)
  ret <vscale x 2 x i32> %b
}

define <vscale x 2 x i32> @reverse_splat(i32 %x, <vscale x 2 x i1> %mask, i32 %vl) {
; CHECK-LABEL: @reverse_splat(
; CHECK-NEXT:    [[A:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[X:%.*]], i64 0
; CHECK-NEXT:    [[B:%.*]] = shufflevector <vscale x 2 x i32> [[A]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    ret <vscale x 2 x i32> [[B]]
;
  %a = insertelement <vscale x 2 x i32> poison, i32 %x, i32 0
  %b = shufflevector <vscale x 2 x i32> %a, <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
  %c = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %c
}

define <vscale x 2 x i32> @reverse_vpadd(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpadd_lhs_splat(i32 %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd_lhs_splat(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[INSX:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[X:%.*]], i64 0
; CHECK-NEXT:    [[SPLATX:%.*]] = shufflevector <vscale x 2 x i32> [[INSX]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[SPLATX]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %insx = insertelement <vscale x 2 x i32> poison, i32 %x, i32 0
  %splatx = shufflevector <vscale x 2 x i32> %insx, <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %splatx, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpadd_rhs_splat(<vscale x 2 x i32> %x, i32 %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd_rhs_splat(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[INSY:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[Y:%.*]], i64 0
; CHECK-NEXT:    [[SPLATY:%.*]] = shufflevector <vscale x 2 x i32> [[INSY]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[SPLATY]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %insy = insertelement <vscale x 2 x i32> poison, i32 %y, i32 0
  %splaty = shufflevector <vscale x 2 x i32> %insy, <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %splaty, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpadd_lhs_splat_vpgather(ptr %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd_lhs_splat_vpgather(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[LOAD_SPLAT:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.strided.load.nxv2i32.p0.i64(ptr [[X:%.*]], i64 0, <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[LOAD_SPLAT]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %insx = insertelement <vscale x 2 x ptr> poison, ptr %x, i32 0
  %splatx = shufflevector <vscale x 2 x ptr> %insx, <vscale x 2 x ptr> poison, <vscale x 2 x i32> zeroinitializer
  %splatgather = call <vscale x 2 x i32> @llvm.vp.gather.nxv2i32.nxv2p0(<vscale x 2 x ptr> %splatx, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %splatgather, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpadd_rhs_splat_vpgather(<vscale x 2 x i32> %x, ptr %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd_rhs_splat_vpgather(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[LOAD_SPLAT:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.strided.load.nxv2i32.p0.i64(ptr [[Y:%.*]], i64 0, <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[LOAD_SPLAT]], <vscale x 2 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %insy = insertelement <vscale x 2 x ptr> poison, ptr %y, i32 0
  %splaty = shufflevector <vscale x 2 x ptr> %insy, <vscale x 2 x ptr> poison, <vscale x 2 x i32> zeroinitializer
  %splatgather = call <vscale x 2 x i32> @llvm.vp.gather.nxv2i32.nxv2p0(<vscale x 2 x ptr> %splaty, <vscale x 2 x i1> %mask, i32 %vl)
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %splatgather, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpsub(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpsub(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.sub.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.sub.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpmul(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpmul(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.mul.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.mul.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x float> @reverse_vpfadd(<vscale x 2 x float> %x, <vscale x 2 x float> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpfadd(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x float> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x float> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x float> %d
}

define <vscale x 2 x float> @reverse_vpfsub(<vscale x 2 x float> %x, <vscale x 2 x float> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpfsub(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x float> @llvm.vp.fsub.nxv2f32(<vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x float> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x float> @llvm.vp.fsub.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x float> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x float> %d
}

define <vscale x 2 x float> @reverse_vpfmul(<vscale x 2 x float> %x, <vscale x 2 x float> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpfmul(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x float> @llvm.vp.fmul.nxv2f32(<vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x float> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x float> @llvm.vp.fmul.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x float> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x float> %d
}

define <vscale x 2 x float> @reverse_vpfadd_vpfmul(<vscale x 2 x float> %x, <vscale x 2 x float> %y, <vscale x 2 x float> %z, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpfadd_vpfmul(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 2 x float> @llvm.vp.fmul.nxv2f32(<vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    [[E:%.*]] = call <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float> [[D]], <vscale x 2 x float> [[Z:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 2 x float> [[E]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %z, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x float> @llvm.vp.fmul.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x float> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %e = call <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float> %d, <vscale x 2 x float> %c, <vscale x 2 x i1> %mask, i32 %vl)
  %f = call <vscale x 2 x float> @llvm.experimental.vp.reverse.nxv2f32(<vscale x 2 x float> %e, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x float> %f
}

define <vscale x 2 x i32> @reverse_vpadd_lhs_splat_vpsplatload(ptr %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd_lhs_splat_vpsplatload(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[SPLATLOAD:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.strided.load.nxv2i32.p0.i64(ptr [[X:%.*]], i64 0, <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[SPLATLOAD]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %splatload = call <vscale x 2 x i32> @llvm.experimental.vp.strided.load.nxv2i32.p0.i64(ptr %x, i64 0, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %splatload, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

declare <vscale x 2 x i32> @llvm.experimental.vp.strided.load.nxv2i32.p0.i64(ptr, i64, <vscale x 2 x i1>, i32)

; Negative test. We can't reverse this because the mask on the vp.add isn't a splat.
define <vscale x 2 x i32> @reverse_vpadd_nonsplat_mask(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, <vscale x 2 x i1> %addmask, i32 %vl) {
; CHECK-LABEL: @reverse_vpadd_nonsplat_mask(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[A]], <vscale x 2 x i32> [[B]], <vscale x 2 x i1> [[ADDMASK:%.*]], i32 [[VL]])
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> [[C]], <vscale x 2 x i1> [[MASK]], i32 [[VL]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[D]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %addmask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i64> @reverse_vpzext(<vscale x 2 x i32> %x, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpzext(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 2 x i64> @llvm.vp.zext.nxv2i64.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i64> [[B]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i64> @llvm.vp.zext.nxv2i64.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i64> @llvm.experimental.vp.reverse.nxv2i64(<vscale x 2 x i64> %b, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i64> %c
}

define <vscale x 2 x i64> @reverse_vpsext(<vscale x 2 x i32> %x, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpsext(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 2 x i64> @llvm.vp.sext.nxv2i64.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i64> [[B]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i64> @llvm.vp.sext.nxv2i64.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i64> @llvm.experimental.vp.reverse.nxv2i64(<vscale x 2 x i64> %b, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i64> %c
}

define <vscale x 2 x i16> @reverse_vptrunc(<vscale x 2 x i32> %x, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vptrunc(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 2 x i16> @llvm.vp.trunc.nxv2i16.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i16> [[B]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i16> @llvm.vp.trunc.nxv2i16.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i16> @llvm.experimental.vp.reverse.nxv2i16(<vscale x 2 x i16> %b, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i16> %c
}

define <vscale x 2 x i32> @reverse_vpsadd_sat(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpsadd_sat(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.sadd.sat.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.sadd.sat.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpssub_sat(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpssub_sat(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.ssub.sat.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.ssub.sat.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpuadd_sat(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpuadd_sat(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.uadd.sat.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.uadd.sat.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}

define <vscale x 2 x i32> @reverse_vpusub_sat(<vscale x 2 x i32> %x, <vscale x 2 x i32> %y, i1 %m, i32 %vl) {
; CHECK-LABEL: @reverse_vpusub_sat(
; CHECK-NEXT:    [[INS:%.*]] = insertelement <vscale x 2 x i1> poison, i1 [[M:%.*]], i64 0
; CHECK-NEXT:    [[MASK:%.*]] = shufflevector <vscale x 2 x i1> [[INS]], <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 2 x i32> @llvm.vp.usub.sat.nxv2i32(<vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32> [[Y:%.*]], <vscale x 2 x i1> [[MASK]], i32 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x i32> [[C]]
;
  %ins = insertelement <vscale x 2 x i1> poison, i1 %m, i32 0
  %mask = shufflevector <vscale x 2 x i1> %ins, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask, i32 %vl)
  %b = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %y, <vscale x 2 x i1> %mask, i32 %vl)
  %c = call <vscale x 2 x i32> @llvm.vp.usub.sat.nxv2i32(<vscale x 2 x i32> %a, <vscale x 2 x i32> %b, <vscale x 2 x i1> %mask, i32 %vl)
  %d = call <vscale x 2 x i32> @llvm.experimental.vp.reverse.nxv2i32(<vscale x 2 x i32> %c, <vscale x 2 x i1> %mask, i32 %vl)
  ret <vscale x 2 x i32> %d
}
