; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt %s -passes=instcombine -S | FileCheck %s

declare <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1>, <vscale x 8 x i32>, <vscale x 8 x i32>, i32)
declare <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1>, <vscale x 8 x i32>, <vscale x 8 x i32>, i32)

define <vscale x 8 x i32> @redundant_vp_merge(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl) {
; CHECK-LABEL: define <vscale x 8 x i32> @redundant_vp_merge(
; CHECK-SAME: <vscale x 8 x i1> [[M:%.*]], <vscale x 8 x i32> [[T:%.*]], <vscale x 8 x i32> [[F:%.*]], i32 [[EVL:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> [[M]], <vscale x 8 x i32> [[T]], <vscale x 8 x i32> [[F]], i32 [[EVL]])
; CHECK-NEXT:    ret <vscale x 8 x i32> [[B]]
;
  %a = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl)
  %b = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> %a, <vscale x 8 x i32> %f, i32 %evl)
  ret <vscale x 8 x i32> %b
}

define <vscale x 8 x i32> @redundant_vp_merge_convert_to_select(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl) {
; CHECK-LABEL: define <vscale x 8 x i32> @redundant_vp_merge_convert_to_select(
; CHECK-SAME: <vscale x 8 x i1> [[M:%.*]], <vscale x 8 x i32> [[T:%.*]], <vscale x 8 x i32> [[F:%.*]], i32 [[EVL:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> [[M]], <vscale x 8 x i32> [[F]], <vscale x 8 x i32> [[T]], i32 [[EVL]])
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> [[A]], <vscale x 8 x i32> [[F]], i32 [[EVL]])
; CHECK-NEXT:    ret <vscale x 8 x i32> [[B]]
;
  %a = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> %m, <vscale x 8 x i32> %f, <vscale x 8 x i32> %t, i32 %evl)
  %b = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> %a, <vscale x 8 x i32> %f, i32 %evl)
  ret <vscale x 8 x i32> %b
}

define <vscale x 8 x i32> @redundant_vp_merge_convert_to_select2(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl) {
; CHECK-LABEL: define <vscale x 8 x i32> @redundant_vp_merge_convert_to_select2(
; CHECK-SAME: <vscale x 8 x i1> [[M:%.*]], <vscale x 8 x i32> [[T:%.*]], <vscale x 8 x i32> [[F:%.*]], i32 [[EVL:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> [[T]], <vscale x 8 x i32> [[F]], i32 [[EVL]])
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> [[M]], <vscale x 8 x i32> [[A]], <vscale x 8 x i32> [[T]], i32 [[EVL]])
; CHECK-NEXT:    ret <vscale x 8 x i32> [[B]]
;
  %a = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl)
  %b = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> %m, <vscale x 8 x i32> %a, <vscale x 8 x i32> %t, i32 %evl)
  ret <vscale x 8 x i32> %b
}

define <vscale x 8 x i32> @redundant_vp_merge_convert_to_select3(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl) {
; CHECK-LABEL: define <vscale x 8 x i32> @redundant_vp_merge_convert_to_select3(
; CHECK-SAME: <vscale x 8 x i1> [[M:%.*]], <vscale x 8 x i32> [[T:%.*]], <vscale x 8 x i32> [[F:%.*]], i32 [[EVL:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> [[T]], <vscale x 8 x i32> [[F]], i32 [[EVL]])
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> [[M]], <vscale x 8 x i32> [[T]], <vscale x 8 x i32> [[A]], i32 [[EVL]])
; CHECK-NEXT:    ret <vscale x 8 x i32> [[B]]
;
  %a = call <vscale x 8 x i32> @llvm.vp.merge.nxv8i32(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i32> %t, <vscale x 8 x i32> %f, i32 %evl)
  %b = call <vscale x 8 x i32> @llvm.vp.select.nxv8i32(<vscale x 8 x i1> %m, <vscale x 8 x i32> %t, <vscale x 8 x i32> %a, i32 %evl)
  ret <vscale x 8 x i32> %b
}
