// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals
// RUN: %clang_cc1 -triple riscv64 -target-feature +zve64x -std=c++11 -disable-O0-optnone -emit-llvm -Qn -o - %s | opt -S -passes=mem2reg | FileCheck %s

// This file tests metadata node generated by rvv-related pragma

#define DUMMY_LOOP for (int i=0; i<n; ++i) c[i] = a[i] + b[i]

// e8
// CHECK-LABEL: @_Z6mf8_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP5:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void mf8_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(mf8, e8)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6mf4_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP10:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void mf4_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(mf4, e8)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6mf2_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP12:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void mf2_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(mf2, e8)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z5m1_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP14:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m1_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m1, e8)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z5m2_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP16:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m2_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m2, e8)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z5m4_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP18:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m4_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m4, e8)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z5m8_e8PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP20:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m8_e8(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m8, e8)
  DUMMY_LOOP;
}

// e16
// CHECK-LABEL: @_Z7mf4_e16PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP22:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void mf4_e16(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(mf4, e16)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z7mf2_e16PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP24:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void mf2_e16(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(mf2, e16)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m1_e16PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP26:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m1_e16(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m1, e16)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m2_e16PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP28:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m2_e16(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m2, e16)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m4_e16PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP30:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m4_e16(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m4, e16)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m8_e16PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP32:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m8_e16(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m8, e16)
  DUMMY_LOOP;
}

// e32
// CHECK-LABEL: @_Z7mf2_e32PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP34:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void mf2_e32(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(mf2, e32)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m1_e32PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP36:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m1_e32(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m1, e32)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m2_e32PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP38:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m2_e32(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m2, e32)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m4_e32PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP40:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m4_e32(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m4, e32)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m8_e32PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP42:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m8_e32(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m8, e32)
  DUMMY_LOOP;
}

// e64
// CHECK-LABEL: @_Z6m1_e64PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP44:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m1_e64(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m1, e64)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m2_e64PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP46:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m2_e64(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m2, e64)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m4_e64PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP48:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m4_e64(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m4, e64)
  DUMMY_LOOP;
}
// CHECK-LABEL: @_Z6m8_e64PiS_S_i(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_INC:%.*]] ]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[I_0]], [[N:%.*]]
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[I_0]] to i64
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM3]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX4]], align 4
// CHECK-NEXT:    br label [[FOR_INC]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[INC]] = add nsw i32 [[I_0]], 1
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP50:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    ret void
//
void m8_e64(int *a, int *b, int *c, int n) {
#pragma clang rvv lmul_sew(m8, e64)
  DUMMY_LOOP;
}
//.
// CHECK: attributes #[[ATTR0:[0-9]+]] = { mustprogress noinline nounwind vscale_range(1,1024) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+zicsr,+zve32x,+zve64x,+zvl32b,+zvl64b" }
//.
// CHECK: [[META0:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
// CHECK: [[META1:![0-9]+]] = !{i32 1, !"target-abi", !"lp64"}
// CHECK: [[META2:![0-9]+]] = !{i32 6, !"riscv-isa", [[META3:![0-9]+]]}
// CHECK: [[META3]] = !{!"rv64i2p1_zicsr2p0_zve32x1p0_zve64x1p0_zvl32b1p0_zvl64b1p0"}
// CHECK: [[META4:![0-9]+]] = !{i32 8, !"SmallDataLimit", i32 0}
// CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]], [[META7:![0-9]+]], [[META8:![0-9]+]], [[META9:![0-9]+]]}
// CHECK: [[META6]] = !{!"llvm.loop.mustprogress"}
// CHECK: [[META7]] = !{!"llvm.loop.vectorize.lmul_sew", i32 -3, i32 8}
// CHECK: [[META8]] = !{!"llvm.loop.vectorize.scalable.enable", i1 true}
// CHECK: [[META9]] = !{!"llvm.loop.vectorize.enable", i1 true}
// CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META6]], [[META11:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META11]] = !{!"llvm.loop.vectorize.lmul_sew", i32 -2, i32 8}
// CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META6]], [[META13:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META13]] = !{!"llvm.loop.vectorize.lmul_sew", i32 -1, i32 8}
// CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META6]], [[META15:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META15]] = !{!"llvm.loop.vectorize.lmul_sew", i32 0, i32 8}
// CHECK: [[LOOP16]] = distinct !{[[LOOP16]], [[META6]], [[META17:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META17]] = !{!"llvm.loop.vectorize.lmul_sew", i32 1, i32 8}
// CHECK: [[LOOP18]] = distinct !{[[LOOP18]], [[META6]], [[META19:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META19]] = !{!"llvm.loop.vectorize.lmul_sew", i32 2, i32 8}
// CHECK: [[LOOP20]] = distinct !{[[LOOP20]], [[META6]], [[META21:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META21]] = !{!"llvm.loop.vectorize.lmul_sew", i32 3, i32 8}
// CHECK: [[LOOP22]] = distinct !{[[LOOP22]], [[META6]], [[META23:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META23]] = !{!"llvm.loop.vectorize.lmul_sew", i32 -2, i32 16}
// CHECK: [[LOOP24]] = distinct !{[[LOOP24]], [[META6]], [[META25:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META25]] = !{!"llvm.loop.vectorize.lmul_sew", i32 -1, i32 16}
// CHECK: [[LOOP26]] = distinct !{[[LOOP26]], [[META6]], [[META27:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META27]] = !{!"llvm.loop.vectorize.lmul_sew", i32 0, i32 16}
// CHECK: [[LOOP28]] = distinct !{[[LOOP28]], [[META6]], [[META29:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META29]] = !{!"llvm.loop.vectorize.lmul_sew", i32 1, i32 16}
// CHECK: [[LOOP30]] = distinct !{[[LOOP30]], [[META6]], [[META31:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META31]] = !{!"llvm.loop.vectorize.lmul_sew", i32 2, i32 16}
// CHECK: [[LOOP32]] = distinct !{[[LOOP32]], [[META6]], [[META33:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META33]] = !{!"llvm.loop.vectorize.lmul_sew", i32 3, i32 16}
// CHECK: [[LOOP34]] = distinct !{[[LOOP34]], [[META6]], [[META35:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META35]] = !{!"llvm.loop.vectorize.lmul_sew", i32 -1, i32 32}
// CHECK: [[LOOP36]] = distinct !{[[LOOP36]], [[META6]], [[META37:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META37]] = !{!"llvm.loop.vectorize.lmul_sew", i32 0, i32 32}
// CHECK: [[LOOP38]] = distinct !{[[LOOP38]], [[META6]], [[META39:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META39]] = !{!"llvm.loop.vectorize.lmul_sew", i32 1, i32 32}
// CHECK: [[LOOP40]] = distinct !{[[LOOP40]], [[META6]], [[META41:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META41]] = !{!"llvm.loop.vectorize.lmul_sew", i32 2, i32 32}
// CHECK: [[LOOP42]] = distinct !{[[LOOP42]], [[META6]], [[META43:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META43]] = !{!"llvm.loop.vectorize.lmul_sew", i32 3, i32 32}
// CHECK: [[LOOP44]] = distinct !{[[LOOP44]], [[META6]], [[META45:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META45]] = !{!"llvm.loop.vectorize.lmul_sew", i32 0, i32 64}
// CHECK: [[LOOP46]] = distinct !{[[LOOP46]], [[META6]], [[META47:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META47]] = !{!"llvm.loop.vectorize.lmul_sew", i32 1, i32 64}
// CHECK: [[LOOP48]] = distinct !{[[LOOP48]], [[META6]], [[META49:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META49]] = !{!"llvm.loop.vectorize.lmul_sew", i32 2, i32 64}
// CHECK: [[LOOP50]] = distinct !{[[LOOP50]], [[META6]], [[META51:![0-9]+]], [[META8]], [[META9]]}
// CHECK: [[META51]] = !{!"llvm.loop.vectorize.lmul_sew", i32 3, i32 64}
//.
