// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -target-feature +experimental-zvkb \
// RUN:  -target-feature +experimental-zvkg -target-feature +experimental-zvknha \
// RUN:  -target-feature +experimental-zvknhb -target-feature +experimental-zvkns \
// RUN:  -target-feature +experimental-zvksed -target-feature +experimental-zvksh \
// RUN:  -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32mf2_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv1f32.nxv1bf16.i64(<vscale x 1 x float> [[MASKEDOFF:%.*]], <vscale x 1 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_sf_vfwcvt_f_bf16_v_f32mf2_tu(vfloat32mf2_t maskedoff, vbfloat16mf4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32mf2_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m1_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv2f32.nxv2bf16.i64(<vscale x 2 x float> [[MASKEDOFF:%.*]], <vscale x 2 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_sf_vfwcvt_f_bf16_v_f32m1_tu(vfloat32m1_t maskedoff, vbfloat16mf2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m1_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m2_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv4f32.nxv4bf16.i64(<vscale x 4 x float> [[MASKEDOFF:%.*]], <vscale x 4 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_sf_vfwcvt_f_bf16_v_f32m2_tu(vfloat32m2_t maskedoff, vbfloat16m1_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m2_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m4_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv8f32.nxv8bf16.i64(<vscale x 8 x float> [[MASKEDOFF:%.*]], <vscale x 8 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_sf_vfwcvt_f_bf16_v_f32m4_tu(vfloat32m4_t maskedoff, vbfloat16m2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m4_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m8_tu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.nxv16f32.nxv16bf16.i64(<vscale x 16 x float> [[MASKEDOFF:%.*]], <vscale x 16 x bfloat> [[SRC:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_sf_vfwcvt_f_bf16_v_f32m8_tu(vfloat32m8_t maskedoff, vbfloat16m4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m8_tu(maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32mf2_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv1f32.nxv1bf16.i64(<vscale x 1 x float> [[MASKEDOFF:%.*]], <vscale x 1 x bfloat> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_sf_vfwcvt_f_bf16_v_f32mf2_tum(vbool64_t mask, vfloat32mf2_t maskedoff, vbfloat16mf4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32mf2_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m1_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv2f32.nxv2bf16.i64(<vscale x 2 x float> [[MASKEDOFF:%.*]], <vscale x 2 x bfloat> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_sf_vfwcvt_f_bf16_v_f32m1_tum(vbool32_t mask, vfloat32m1_t maskedoff, vbfloat16mf2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m1_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m2_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv4f32.nxv4bf16.i64(<vscale x 4 x float> [[MASKEDOFF:%.*]], <vscale x 4 x bfloat> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_sf_vfwcvt_f_bf16_v_f32m2_tum(vbool16_t mask, vfloat32m2_t maskedoff, vbfloat16m1_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m2_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m4_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv8f32.nxv8bf16.i64(<vscale x 8 x float> [[MASKEDOFF:%.*]], <vscale x 8 x bfloat> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_sf_vfwcvt_f_bf16_v_f32m4_tum(vbool8_t mask, vfloat32m4_t maskedoff, vbfloat16m2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m4_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m8_tum(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv16f32.nxv16bf16.i64(<vscale x 16 x float> [[MASKEDOFF:%.*]], <vscale x 16 x bfloat> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2)
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_sf_vfwcvt_f_bf16_v_f32m8_tum(vbool4_t mask, vfloat32m8_t maskedoff, vbfloat16m4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m8_tum(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32mf2_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv1f32.nxv1bf16.i64(<vscale x 1 x float> [[MASKEDOFF:%.*]], <vscale x 1 x bfloat> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_sf_vfwcvt_f_bf16_v_f32mf2_tumu(vbool64_t mask, vfloat32mf2_t maskedoff, vbfloat16mf4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32mf2_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m1_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv2f32.nxv2bf16.i64(<vscale x 2 x float> [[MASKEDOFF:%.*]], <vscale x 2 x bfloat> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_sf_vfwcvt_f_bf16_v_f32m1_tumu(vbool32_t mask, vfloat32m1_t maskedoff, vbfloat16mf2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m1_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m2_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv4f32.nxv4bf16.i64(<vscale x 4 x float> [[MASKEDOFF:%.*]], <vscale x 4 x bfloat> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_sf_vfwcvt_f_bf16_v_f32m2_tumu(vbool16_t mask, vfloat32m2_t maskedoff, vbfloat16m1_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m2_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m4_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv8f32.nxv8bf16.i64(<vscale x 8 x float> [[MASKEDOFF:%.*]], <vscale x 8 x bfloat> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_sf_vfwcvt_f_bf16_v_f32m4_tumu(vbool8_t mask, vfloat32m4_t maskedoff, vbfloat16m2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m4_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m8_tumu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv16f32.nxv16bf16.i64(<vscale x 16 x float> [[MASKEDOFF:%.*]], <vscale x 16 x bfloat> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0)
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_sf_vfwcvt_f_bf16_v_f32m8_tumu(vbool4_t mask, vfloat32m8_t maskedoff, vbfloat16m4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m8_tumu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32mf2_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv1f32.nxv1bf16.i64(<vscale x 1 x float> [[MASKEDOFF:%.*]], <vscale x 1 x bfloat> [[SRC:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_sf_vfwcvt_f_bf16_v_f32mf2_mu(vbool64_t mask, vfloat32mf2_t maskedoff, vbfloat16mf4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32mf2_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m1_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv2f32.nxv2bf16.i64(<vscale x 2 x float> [[MASKEDOFF:%.*]], <vscale x 2 x bfloat> [[SRC:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_sf_vfwcvt_f_bf16_v_f32m1_mu(vbool32_t mask, vfloat32m1_t maskedoff, vbfloat16mf2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m1_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m2_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv4f32.nxv4bf16.i64(<vscale x 4 x float> [[MASKEDOFF:%.*]], <vscale x 4 x bfloat> [[SRC:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_sf_vfwcvt_f_bf16_v_f32m2_mu(vbool16_t mask, vfloat32m2_t maskedoff, vbfloat16m1_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m2_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m4_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv8f32.nxv8bf16.i64(<vscale x 8 x float> [[MASKEDOFF:%.*]], <vscale x 8 x bfloat> [[SRC:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_sf_vfwcvt_f_bf16_v_f32m4_mu(vbool8_t mask, vfloat32m4_t maskedoff, vbfloat16m2_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m4_mu(mask, maskedoff, src, vl);
}

// CHECK-LABEL: @test_sf_vfwcvt_f_bf16_v_f32m8_mu(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.sf.vfwcvt.f.bf16.v.mask.nxv16f32.nxv16bf16.i64(<vscale x 16 x float> [[MASKEDOFF:%.*]], <vscale x 16 x bfloat> [[SRC:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1)
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_sf_vfwcvt_f_bf16_v_f32m8_mu(vbool4_t mask, vfloat32m8_t maskedoff, vbfloat16m4_t src, size_t vl) {
  return __riscv_sf_vfwcvt_f_bf16_v_f32m8_mu(mask, maskedoff, src, vl);
}

