// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#define __rvv_0p11_compatible_intrinsics
#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf8_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv1i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf8_tu_ntl_P1(vint8mf8_t *v0, vint8mf8_t *v1, vint8mf8_t *v2, vint8mf8_t maskedoff0, vint8mf8_t maskedoff1, vint8mf8_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf8_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf4_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv2i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf4_tu_ntl_P1(vint8mf4_t *v0, vint8mf4_t *v1, vint8mf4_t *v2, vint8mf4_t maskedoff0, vint8mf4_t maskedoff1, vint8mf4_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf4_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf2_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv4i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf2_tu_ntl_P1(vint8mf2_t *v0, vint8mf2_t *v1, vint8mf2_t *v2, vint8mf2_t maskedoff0, vint8mf2_t maskedoff1, vint8mf2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf2_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m1_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv8i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m1_tu_ntl_P1(vint8m1_t *v0, vint8m1_t *v1, vint8m1_t *v2, vint8m1_t maskedoff0, vint8m1_t maskedoff1, vint8m1_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m1_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m2_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv16i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m2_tu_ntl_P1(vint8m2_t *v0, vint8m2_t *v1, vint8m2_t *v2, vint8m2_t maskedoff0, vint8m2_t maskedoff1, vint8m2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m2_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf8_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv1i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf8_tu_ntl_P1(vuint8mf8_t *v0, vuint8mf8_t *v1, vuint8mf8_t *v2, vuint8mf8_t maskedoff0, vuint8mf8_t maskedoff1, vuint8mf8_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf8_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf4_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv2i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf4_tu_ntl_P1(vuint8mf4_t *v0, vuint8mf4_t *v1, vuint8mf4_t *v2, vuint8mf4_t maskedoff0, vuint8mf4_t maskedoff1, vuint8mf4_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf4_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf2_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv4i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf2_tu_ntl_P1(vuint8mf2_t *v0, vuint8mf2_t *v1, vuint8mf2_t *v2, vuint8mf2_t maskedoff0, vuint8mf2_t maskedoff1, vuint8mf2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf2_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m1_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv8i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m1_tu_ntl_P1(vuint8m1_t *v0, vuint8m1_t *v1, vuint8m1_t *v2, vuint8m1_t maskedoff0, vuint8m1_t maskedoff1, vuint8m1_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m1_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m2_tu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.triscv.vector.tuple_nxv16i8_3t.i64.p0(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m2_tu_ntl_P1(vuint8m2_t *v0, vuint8m2_t *v1, vuint8m2_t *v2, vuint8m2_t maskedoff0, vuint8m2_t maskedoff1, vuint8m2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m2_tu_ntl(v0, v1, v2, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf8_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv1i8_3t.i64.p0.nxv1i1(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf8_tum_ntl_P1(vint8mf8_t *v0, vint8mf8_t *v1, vint8mf8_t *v2, vbool64_t mask, vint8mf8_t maskedoff0, vint8mf8_t maskedoff1, vint8mf8_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf8_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf4_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv2i8_3t.i64.p0.nxv2i1(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf4_tum_ntl_P1(vint8mf4_t *v0, vint8mf4_t *v1, vint8mf4_t *v2, vbool32_t mask, vint8mf4_t maskedoff0, vint8mf4_t maskedoff1, vint8mf4_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf4_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf2_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv4i8_3t.i64.p0.nxv4i1(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf2_tum_ntl_P1(vint8mf2_t *v0, vint8mf2_t *v1, vint8mf2_t *v2, vbool16_t mask, vint8mf2_t maskedoff0, vint8mf2_t maskedoff1, vint8mf2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf2_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m1_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv8i8_3t.i64.p0.nxv8i1(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m1_tum_ntl_P1(vint8m1_t *v0, vint8m1_t *v1, vint8m1_t *v2, vbool8_t mask, vint8m1_t maskedoff0, vint8m1_t maskedoff1, vint8m1_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m1_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m2_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv16i8_3t.i64.p0.nxv16i1(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m2_tum_ntl_P1(vint8m2_t *v0, vint8m2_t *v1, vint8m2_t *v2, vbool4_t mask, vint8m2_t maskedoff0, vint8m2_t maskedoff1, vint8m2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m2_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf8_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv1i8_3t.i64.p0.nxv1i1(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf8_tum_ntl_P1(vuint8mf8_t *v0, vuint8mf8_t *v1, vuint8mf8_t *v2, vbool64_t mask, vuint8mf8_t maskedoff0, vuint8mf8_t maskedoff1, vuint8mf8_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf8_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf4_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv2i8_3t.i64.p0.nxv2i1(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf4_tum_ntl_P1(vuint8mf4_t *v0, vuint8mf4_t *v1, vuint8mf4_t *v2, vbool32_t mask, vuint8mf4_t maskedoff0, vuint8mf4_t maskedoff1, vuint8mf4_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf4_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf2_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv4i8_3t.i64.p0.nxv4i1(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf2_tum_ntl_P1(vuint8mf2_t *v0, vuint8mf2_t *v1, vuint8mf2_t *v2, vbool16_t mask, vuint8mf2_t maskedoff0, vuint8mf2_t maskedoff1, vuint8mf2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf2_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m1_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv8i8_3t.i64.p0.nxv8i1(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m1_tum_ntl_P1(vuint8m1_t *v0, vuint8m1_t *v1, vuint8m1_t *v2, vbool8_t mask, vuint8m1_t maskedoff0, vuint8m1_t maskedoff1, vuint8m1_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m1_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m2_tum_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv16i8_3t.i64.p0.nxv16i1(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 2, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m2_tum_ntl_P1(vuint8m2_t *v0, vuint8m2_t *v1, vuint8m2_t *v2, vbool4_t mask, vuint8m2_t maskedoff0, vuint8m2_t maskedoff1, vuint8m2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m2_tum_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf8_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv1i8_3t.i64.p0.nxv1i1(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf8_tumu_ntl_P1(vint8mf8_t *v0, vint8mf8_t *v1, vint8mf8_t *v2, vbool64_t mask, vint8mf8_t maskedoff0, vint8mf8_t maskedoff1, vint8mf8_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf8_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf4_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv2i8_3t.i64.p0.nxv2i1(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf4_tumu_ntl_P1(vint8mf4_t *v0, vint8mf4_t *v1, vint8mf4_t *v2, vbool32_t mask, vint8mf4_t maskedoff0, vint8mf4_t maskedoff1, vint8mf4_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf4_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf2_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv4i8_3t.i64.p0.nxv4i1(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf2_tumu_ntl_P1(vint8mf2_t *v0, vint8mf2_t *v1, vint8mf2_t *v2, vbool16_t mask, vint8mf2_t maskedoff0, vint8mf2_t maskedoff1, vint8mf2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf2_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m1_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv8i8_3t.i64.p0.nxv8i1(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m1_tumu_ntl_P1(vint8m1_t *v0, vint8m1_t *v1, vint8m1_t *v2, vbool8_t mask, vint8m1_t maskedoff0, vint8m1_t maskedoff1, vint8m1_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m1_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m2_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv16i8_3t.i64.p0.nxv16i1(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m2_tumu_ntl_P1(vint8m2_t *v0, vint8m2_t *v1, vint8m2_t *v2, vbool4_t mask, vint8m2_t maskedoff0, vint8m2_t maskedoff1, vint8m2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m2_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf8_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv1i8_3t.i64.p0.nxv1i1(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf8_tumu_ntl_P1(vuint8mf8_t *v0, vuint8mf8_t *v1, vuint8mf8_t *v2, vbool64_t mask, vuint8mf8_t maskedoff0, vuint8mf8_t maskedoff1, vuint8mf8_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf8_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf4_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv2i8_3t.i64.p0.nxv2i1(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf4_tumu_ntl_P1(vuint8mf4_t *v0, vuint8mf4_t *v1, vuint8mf4_t *v2, vbool32_t mask, vuint8mf4_t maskedoff0, vuint8mf4_t maskedoff1, vuint8mf4_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf4_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf2_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv4i8_3t.i64.p0.nxv4i1(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf2_tumu_ntl_P1(vuint8mf2_t *v0, vuint8mf2_t *v1, vuint8mf2_t *v2, vbool16_t mask, vuint8mf2_t maskedoff0, vuint8mf2_t maskedoff1, vuint8mf2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf2_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m1_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv8i8_3t.i64.p0.nxv8i1(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m1_tumu_ntl_P1(vuint8m1_t *v0, vuint8m1_t *v1, vuint8m1_t *v2, vbool8_t mask, vuint8m1_t maskedoff0, vuint8m1_t maskedoff1, vuint8m1_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m1_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m2_tumu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv16i8_3t.i64.p0.nxv16i1(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m2_tumu_ntl_P1(vuint8m2_t *v0, vuint8m2_t *v1, vuint8m2_t *v2, vbool4_t mask, vuint8m2_t maskedoff0, vuint8m2_t maskedoff1, vuint8m2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m2_tumu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf8_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv1i8_3t.i64.p0.nxv1i1(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf8_mu_ntl_P1(vint8mf8_t *v0, vint8mf8_t *v1, vint8mf8_t *v2, vbool64_t mask, vint8mf8_t maskedoff0, vint8mf8_t maskedoff1, vint8mf8_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf8_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf4_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv2i8_3t.i64.p0.nxv2i1(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf4_mu_ntl_P1(vint8mf4_t *v0, vint8mf4_t *v1, vint8mf4_t *v2, vbool32_t mask, vint8mf4_t maskedoff0, vint8mf4_t maskedoff1, vint8mf4_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf4_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8mf2_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv4i8_3t.i64.p0.nxv4i1(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8mf2_mu_ntl_P1(vint8mf2_t *v0, vint8mf2_t *v1, vint8mf2_t *v2, vbool16_t mask, vint8mf2_t maskedoff0, vint8mf2_t maskedoff1, vint8mf2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8mf2_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m1_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv8i8_3t.i64.p0.nxv8i1(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m1_mu_ntl_P1(vint8m1_t *v0, vint8m1_t *v1, vint8m1_t *v2, vbool8_t mask, vint8m1_t maskedoff0, vint8m1_t maskedoff1, vint8m1_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m1_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_i8m2_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv16i8_3t.i64.p0.nxv16i1(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_i8m2_mu_ntl_P1(vint8m2_t *v0, vint8m2_t *v1, vint8m2_t *v2, vbool4_t mask, vint8m2_t maskedoff0, vint8m2_t maskedoff1, vint8m2_t maskedoff2, const int8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_i8m2_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf8_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) poison, <vscale x 1 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP0]], <vscale x 1 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 1 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv1i8_3t.nxv1i8(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP1]], <vscale x 1 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv1i8_3t.i64.p0.nxv1i1(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 1 x i8> @llvm.riscv.tuple.extract.nxv1i8.triscv.vector.tuple_nxv1i8_3t(target("riscv.vector.tuple", <vscale x 1 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 1 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 1 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf8_mu_ntl_P1(vuint8mf8_t *v0, vuint8mf8_t *v1, vuint8mf8_t *v2, vbool64_t mask, vuint8mf8_t maskedoff0, vuint8mf8_t maskedoff1, vuint8mf8_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf8_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf4_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) poison, <vscale x 2 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP0]], <vscale x 2 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 2 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv2i8_3t.nxv2i8(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP1]], <vscale x 2 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv2i8_3t.i64.p0.nxv2i1(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 2 x i8> @llvm.riscv.tuple.extract.nxv2i8.triscv.vector.tuple_nxv2i8_3t(target("riscv.vector.tuple", <vscale x 2 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 2 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 2 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf4_mu_ntl_P1(vuint8mf4_t *v0, vuint8mf4_t *v1, vuint8mf4_t *v2, vbool32_t mask, vuint8mf4_t maskedoff0, vuint8mf4_t maskedoff1, vuint8mf4_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf4_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8mf2_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) poison, <vscale x 4 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP0]], <vscale x 4 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 4 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv4i8_3t.nxv4i8(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP1]], <vscale x 4 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv4i8_3t.i64.p0.nxv4i1(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i8> @llvm.riscv.tuple.extract.nxv4i8.triscv.vector.tuple_nxv4i8_3t(target("riscv.vector.tuple", <vscale x 4 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 4 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 4 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8mf2_mu_ntl_P1(vuint8mf2_t *v0, vuint8mf2_t *v1, vuint8mf2_t *v2, vbool16_t mask, vuint8mf2_t maskedoff0, vuint8mf2_t maskedoff1, vuint8mf2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8mf2_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m1_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) poison, <vscale x 8 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP0]], <vscale x 8 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 8 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv8i8_3t.nxv8i8(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP1]], <vscale x 8 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv8i8_3t.i64.p0.nxv8i1(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 8 x i8> @llvm.riscv.tuple.extract.nxv8i8.triscv.vector.tuple_nxv8i8_3t(target("riscv.vector.tuple", <vscale x 8 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 8 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m1_mu_ntl_P1(vuint8m1_t *v0, vuint8m1_t *v1, vuint8m1_t *v2, vbool8_t mask, vuint8m1_t maskedoff0, vuint8m1_t maskedoff1, vuint8m1_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m1_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-LABEL: @test_vlseg3e8ff_v_u8m2_mu_ntl_P1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) poison, <vscale x 16 x i8> [[MASKEDOFF0:%.*]], i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP0]], <vscale x 16 x i8> [[MASKEDOFF1:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = call target("riscv.vector.tuple", <vscale x 16 x i8>, 3) @llvm.riscv.tuple.insert.triscv.vector.tuple_nxv16i8_3t.nxv16i8(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP1]], <vscale x 16 x i8> [[MASKEDOFF2:%.*]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = call { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } @llvm.riscv.vlseg3ff.mask.triscv.vector.tuple_nxv16i8_3t.i64.p0.nxv16i1(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP2]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 1, i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 0)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP5]], ptr [[V0:%.*]], align 1
// CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 1)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP6]], ptr [[V1:%.*]], align 1
// CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.tuple.extract.nxv16i8.triscv.vector.tuple_nxv16i8_3t(target("riscv.vector.tuple", <vscale x 16 x i8>, 3) [[TMP4]], i32 2)
// CHECK-NEXT:    store <vscale x 16 x i8> [[TMP7]], ptr [[V2:%.*]], align 1
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { target("riscv.vector.tuple", <vscale x 16 x i8>, 3), i64 } [[TMP3]], 1
// CHECK-NEXT:    store i64 [[TMP8]], ptr [[NEW_VL:%.*]], align 1
// CHECK-NEXT:    ret void
//
void test_vlseg3e8ff_v_u8m2_mu_ntl_P1(vuint8m2_t *v0, vuint8m2_t *v1, vuint8m2_t *v2, vbool4_t mask, vuint8m2_t maskedoff0, vuint8m2_t maskedoff1, vuint8m2_t maskedoff2, const uint8_t *base, size_t *new_vl, size_t vl, int domain) {
  return __riscv_vlseg3e8ff_v_u8m2_mu_ntl(v0, v1, v2, mask, maskedoff0, maskedoff1, maskedoff2, base, new_vl, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

