// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +experimental-zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -target-feature +experimental-zvkb \
// RUN:  -target-feature +experimental-zvkg -target-feature +experimental-zvknha \
// RUN:  -target-feature +experimental-zvknhb -target-feature +experimental-zvkns \
// RUN:  -target-feature +experimental-zvksed -target-feature +experimental-zvksh \
// RUN:  -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vc_iv_se_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv1i8.i32.i64(i32 0, i32 0, <vscale x 1 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8mf8(int bit_field27_26, int bit_field11_7, vuint8mf8_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv2i8.i32.i64(i32 0, i32 0, <vscale x 2 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8mf4(int bit_field27_26, int bit_field11_7, vuint8mf4_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv4i8.i32.i64(i32 0, i32 0, <vscale x 4 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8mf2(int bit_field27_26, int bit_field11_7, vuint8mf2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv8i8.i32.i64(i32 0, i32 0, <vscale x 8 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8m1(int bit_field27_26, int bit_field11_7, vuint8m1_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv16i8.i32.i64(i32 0, i32 0, <vscale x 16 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8m2(int bit_field27_26, int bit_field11_7, vuint8m2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv32i8.i32.i64(i32 0, i32 0, <vscale x 32 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8m4(int bit_field27_26, int bit_field11_7, vuint8m4_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv64i8.i32.i64(i32 0, i32 0, <vscale x 64 x i8> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u8m8(int bit_field27_26, int bit_field11_7, vuint8m8_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv1i16.i32.i64(i32 0, i32 0, <vscale x 1 x i16> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u16mf4(int bit_field27_26, int bit_field11_7, vuint16mf4_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv2i16.i32.i64(i32 0, i32 0, <vscale x 2 x i16> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u16mf2(int bit_field27_26, int bit_field11_7, vuint16mf2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv4i16.i32.i64(i32 0, i32 0, <vscale x 4 x i16> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u16m1(int bit_field27_26, int bit_field11_7, vuint16m1_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv8i16.i32.i64(i32 0, i32 0, <vscale x 8 x i16> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u16m2(int bit_field27_26, int bit_field11_7, vuint16m2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv16i16.i32.i64(i32 0, i32 0, <vscale x 16 x i16> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u16m4(int bit_field27_26, int bit_field11_7, vuint16m4_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv32i16.i32.i64(i32 0, i32 0, <vscale x 32 x i16> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u16m8(int bit_field27_26, int bit_field11_7, vuint16m8_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv1i32.i32.i64(i32 0, i32 0, <vscale x 1 x i32> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u32mf2(int bit_field27_26, int bit_field11_7, vuint32mf2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv2i32.i32.i64(i32 0, i32 0, <vscale x 2 x i32> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u32m1(int bit_field27_26, int bit_field11_7, vuint32m1_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv4i32.i32.i64(i32 0, i32 0, <vscale x 4 x i32> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u32m2(int bit_field27_26, int bit_field11_7, vuint32m2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv8i32.i32.i64(i32 0, i32 0, <vscale x 8 x i32> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u32m4(int bit_field27_26, int bit_field11_7, vuint32m4_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv16i32.i32.i64(i32 0, i32 0, <vscale x 16 x i32> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u32m8(int bit_field27_26, int bit_field11_7, vuint32m8_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv1i64.i32.i64(i32 0, i32 0, <vscale x 1 x i64> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u64m1(int bit_field27_26, int bit_field11_7, vuint64m1_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv2i64.i32.i64(i32 0, i32 0, <vscale x 2 x i64> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u64m2(int bit_field27_26, int bit_field11_7, vuint64m2_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv4i64.i32.i64(i32 0, i32 0, <vscale x 4 x i64> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u64m4(int bit_field27_26, int bit_field11_7, vuint64m4_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

// CHECK-LABEL: @test_sf_vc_iv_se_u64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.sf.vc.iv.se.nxv8i64.i32.i64(i32 0, i32 0, <vscale x 8 x i64> [[VS2:%.*]], i32 0, i64 [[VL:%.*]])
// CHECK-NEXT:    ret void
//
void test_sf_vc_iv_se_u64m8(int bit_field27_26, int bit_field11_7, vuint64m8_t vs2, int simm5, size_t vl) {
  return __riscv_sf_vc_iv_se(0, 0, vs2, 0, vl);
}

