// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh \
// RUN:   -target-feature +zvfh -disable-O0-optnone  \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x half> @test_vloxei8_v_f16mf4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vloxei.nxv1f16.p0.nxv1i8.i64(<vscale x 1 x half> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6:![0-9]+]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vloxei8_v_f16mf4_ntl_ALL(const _Float16 *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x half> @test_vloxei8_v_f16mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vloxei.nxv2f16.p0.nxv2i8.i64(<vscale x 2 x half> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vloxei8_v_f16mf2_ntl_ALL(const _Float16 *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x half> @test_vloxei8_v_f16m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vloxei.nxv4f16.p0.nxv4i8.i64(<vscale x 4 x half> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vloxei8_v_f16m1_ntl_ALL(const _Float16 *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x half> @test_vloxei8_v_f16m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vloxei.nxv8f16.p0.nxv8i8.i64(<vscale x 8 x half> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vloxei8_v_f16m2_ntl_ALL(const _Float16 *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x half> @test_vloxei8_v_f16m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vloxei.nxv16f16.p0.nxv16i8.i64(<vscale x 16 x half> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vloxei8_v_f16m4_ntl_ALL(const _Float16 *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x half> @test_vloxei8_v_f16m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vloxei.nxv32f16.p0.nxv32i8.i64(<vscale x 32 x half> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vloxei8_v_f16m8_ntl_ALL(const _Float16 *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x float> @test_vloxei8_v_f32mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vloxei.nxv1f32.p0.nxv1i8.i64(<vscale x 1 x float> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vloxei8_v_f32mf2_ntl_ALL(const float *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x float> @test_vloxei8_v_f32m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vloxei.nxv2f32.p0.nxv2i8.i64(<vscale x 2 x float> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vloxei8_v_f32m1_ntl_ALL(const float *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x float> @test_vloxei8_v_f32m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vloxei.nxv4f32.p0.nxv4i8.i64(<vscale x 4 x float> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vloxei8_v_f32m2_ntl_ALL(const float *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x float> @test_vloxei8_v_f32m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vloxei.nxv8f32.p0.nxv8i8.i64(<vscale x 8 x float> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vloxei8_v_f32m4_ntl_ALL(const float *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x float> @test_vloxei8_v_f32m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vloxei.nxv16f32.p0.nxv16i8.i64(<vscale x 16 x float> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vloxei8_v_f32m8_ntl_ALL(const float *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x double> @test_vloxei8_v_f64m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vloxei.nxv1f64.p0.nxv1i8.i64(<vscale x 1 x double> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vloxei8_v_f64m1_ntl_ALL(const double *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x double> @test_vloxei8_v_f64m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vloxei.nxv2f64.p0.nxv2i8.i64(<vscale x 2 x double> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vloxei8_v_f64m2_ntl_ALL(const double *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x double> @test_vloxei8_v_f64m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vloxei.nxv4f64.p0.nxv4i8.i64(<vscale x 4 x double> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vloxei8_v_f64m4_ntl_ALL(const double *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x double> @test_vloxei8_v_f64m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vloxei.nxv8f64.p0.nxv8i8.i64(<vscale x 8 x double> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vloxei8_v_f64m8_ntl_ALL(const double *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vloxei8_v_i8mf8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vloxei.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vloxei8_v_i8mf8_ntl_ALL(const int8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vloxei8_v_i8mf4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vloxei.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vloxei8_v_i8mf4_ntl_ALL(const int8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vloxei8_v_i8mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vloxei.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vloxei8_v_i8mf2_ntl_ALL(const int8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vloxei8_v_i8m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vloxei.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vloxei8_v_i8m1_ntl_ALL(const int8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vloxei8_v_i8m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vloxei.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vloxei8_v_i8m2_ntl_ALL(const int8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vloxei8_v_i8m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vloxei.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vloxei8_v_i8m4_ntl_ALL(const int8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vloxei8_v_i8m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vloxei.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vloxei8_v_i8m8_ntl_ALL(const int8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vloxei8_v_i16mf4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vloxei.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vloxei8_v_i16mf4_ntl_ALL(const int16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vloxei8_v_i16mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vloxei.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vloxei8_v_i16mf2_ntl_ALL(const int16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vloxei8_v_i16m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vloxei.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vloxei8_v_i16m1_ntl_ALL(const int16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vloxei8_v_i16m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vloxei.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vloxei8_v_i16m2_ntl_ALL(const int16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vloxei8_v_i16m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vloxei.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vloxei8_v_i16m4_ntl_ALL(const int16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vloxei8_v_i16m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vloxei.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vloxei8_v_i16m8_ntl_ALL(const int16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vloxei8_v_i32mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vloxei.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vloxei8_v_i32mf2_ntl_ALL(const int32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vloxei8_v_i32m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vloxei.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vloxei8_v_i32m1_ntl_ALL(const int32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vloxei8_v_i32m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vloxei.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vloxei8_v_i32m2_ntl_ALL(const int32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vloxei8_v_i32m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vloxei.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vloxei8_v_i32m4_ntl_ALL(const int32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vloxei8_v_i32m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vloxei.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vloxei8_v_i32m8_ntl_ALL(const int32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vloxei8_v_i64m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vloxei.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vloxei8_v_i64m1_ntl_ALL(const int64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vloxei8_v_i64m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vloxei.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vloxei8_v_i64m2_ntl_ALL(const int64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vloxei8_v_i64m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vloxei.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vloxei8_v_i64m4_ntl_ALL(const int64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vloxei8_v_i64m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vloxei.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vloxei8_v_i64m8_ntl_ALL(const int64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vloxei8_v_u8mf8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vloxei.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vloxei8_v_u8mf8_ntl_ALL(const uint8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vloxei8_v_u8mf4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vloxei.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vloxei8_v_u8mf4_ntl_ALL(const uint8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vloxei8_v_u8mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vloxei.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vloxei8_v_u8mf2_ntl_ALL(const uint8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vloxei8_v_u8m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vloxei.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vloxei8_v_u8m1_ntl_ALL(const uint8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vloxei8_v_u8m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vloxei.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vloxei8_v_u8m2_ntl_ALL(const uint8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vloxei8_v_u8m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vloxei.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vloxei8_v_u8m4_ntl_ALL(const uint8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vloxei8_v_u8m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vloxei.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vloxei8_v_u8m8_ntl_ALL(const uint8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vloxei8_v_u16mf4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vloxei.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vloxei8_v_u16mf4_ntl_ALL(const uint16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vloxei8_v_u16mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vloxei.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vloxei8_v_u16mf2_ntl_ALL(const uint16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vloxei8_v_u16m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vloxei.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vloxei8_v_u16m1_ntl_ALL(const uint16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vloxei8_v_u16m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vloxei.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vloxei8_v_u16m2_ntl_ALL(const uint16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vloxei8_v_u16m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vloxei.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vloxei8_v_u16m4_ntl_ALL(const uint16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vloxei8_v_u16m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vloxei.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vloxei8_v_u16m8_ntl_ALL(const uint16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vloxei8_v_u32mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vloxei.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vloxei8_v_u32mf2_ntl_ALL(const uint32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vloxei8_v_u32m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vloxei.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vloxei8_v_u32m1_ntl_ALL(const uint32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vloxei8_v_u32m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vloxei.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vloxei8_v_u32m2_ntl_ALL(const uint32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vloxei8_v_u32m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vloxei.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vloxei8_v_u32m4_ntl_ALL(const uint32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vloxei8_v_u32m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vloxei.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vloxei8_v_u32m8_ntl_ALL(const uint32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vloxei8_v_u64m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vloxei.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vloxei8_v_u64m1_ntl_ALL(const uint64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vloxei8_v_u64m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vloxei.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vloxei8_v_u64m2_ntl_ALL(const uint64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vloxei8_v_u64m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vloxei.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vloxei8_v_u64m4_ntl_ALL(const uint64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vloxei8_v_u64m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vloxei.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vloxei8_v_u64m8_ntl_ALL(const uint64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x half> @test_vloxei8_v_f16mf4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vloxei.mask.nxv1f16.p0.nxv1i8.i64(<vscale x 1 x half> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vloxei8_v_f16mf4_m_ntl_ALL(vbool64_t mask, const _Float16 *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x half> @test_vloxei8_v_f16mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vloxei.mask.nxv2f16.p0.nxv2i8.i64(<vscale x 2 x half> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vloxei8_v_f16mf2_m_ntl_ALL(vbool32_t mask, const _Float16 *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x half> @test_vloxei8_v_f16m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vloxei.mask.nxv4f16.p0.nxv4i8.i64(<vscale x 4 x half> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vloxei8_v_f16m1_m_ntl_ALL(vbool16_t mask, const _Float16 *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x half> @test_vloxei8_v_f16m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vloxei.mask.nxv8f16.p0.nxv8i8.i64(<vscale x 8 x half> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vloxei8_v_f16m2_m_ntl_ALL(vbool8_t mask, const _Float16 *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x half> @test_vloxei8_v_f16m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vloxei.mask.nxv16f16.p0.nxv16i8.i64(<vscale x 16 x half> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vloxei8_v_f16m4_m_ntl_ALL(vbool4_t mask, const _Float16 *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x half> @test_vloxei8_v_f16m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vloxei.mask.nxv32f16.p0.nxv32i8.i64(<vscale x 32 x half> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vloxei8_v_f16m8_m_ntl_ALL(vbool2_t mask, const _Float16 *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x float> @test_vloxei8_v_f32mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vloxei.mask.nxv1f32.p0.nxv1i8.i64(<vscale x 1 x float> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vloxei8_v_f32mf2_m_ntl_ALL(vbool64_t mask, const float *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x float> @test_vloxei8_v_f32m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vloxei.mask.nxv2f32.p0.nxv2i8.i64(<vscale x 2 x float> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vloxei8_v_f32m1_m_ntl_ALL(vbool32_t mask, const float *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x float> @test_vloxei8_v_f32m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vloxei.mask.nxv4f32.p0.nxv4i8.i64(<vscale x 4 x float> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vloxei8_v_f32m2_m_ntl_ALL(vbool16_t mask, const float *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x float> @test_vloxei8_v_f32m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vloxei.mask.nxv8f32.p0.nxv8i8.i64(<vscale x 8 x float> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vloxei8_v_f32m4_m_ntl_ALL(vbool8_t mask, const float *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x float> @test_vloxei8_v_f32m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vloxei.mask.nxv16f32.p0.nxv16i8.i64(<vscale x 16 x float> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vloxei8_v_f32m8_m_ntl_ALL(vbool4_t mask, const float *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x double> @test_vloxei8_v_f64m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vloxei.mask.nxv1f64.p0.nxv1i8.i64(<vscale x 1 x double> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vloxei8_v_f64m1_m_ntl_ALL(vbool64_t mask, const double *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x double> @test_vloxei8_v_f64m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vloxei.mask.nxv2f64.p0.nxv2i8.i64(<vscale x 2 x double> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vloxei8_v_f64m2_m_ntl_ALL(vbool32_t mask, const double *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x double> @test_vloxei8_v_f64m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vloxei.mask.nxv4f64.p0.nxv4i8.i64(<vscale x 4 x double> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vloxei8_v_f64m4_m_ntl_ALL(vbool16_t mask, const double *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x double> @test_vloxei8_v_f64m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vloxei.mask.nxv8f64.p0.nxv8i8.i64(<vscale x 8 x double> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vloxei8_v_f64m8_m_ntl_ALL(vbool8_t mask, const double *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vloxei8_v_i8mf8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vloxei.mask.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vloxei8_v_i8mf8_m_ntl_ALL(vbool64_t mask, const int8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vloxei8_v_i8mf4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vloxei.mask.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vloxei8_v_i8mf4_m_ntl_ALL(vbool32_t mask, const int8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vloxei8_v_i8mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vloxei.mask.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vloxei8_v_i8mf2_m_ntl_ALL(vbool16_t mask, const int8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vloxei8_v_i8m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vloxei.mask.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vloxei8_v_i8m1_m_ntl_ALL(vbool8_t mask, const int8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vloxei8_v_i8m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vloxei.mask.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vloxei8_v_i8m2_m_ntl_ALL(vbool4_t mask, const int8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vloxei8_v_i8m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vloxei.mask.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vloxei8_v_i8m4_m_ntl_ALL(vbool2_t mask, const int8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vloxei8_v_i8m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vloxei.mask.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], <vscale x 64 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vloxei8_v_i8m8_m_ntl_ALL(vbool1_t mask, const int8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vloxei8_v_i16mf4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vloxei.mask.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vloxei8_v_i16mf4_m_ntl_ALL(vbool64_t mask, const int16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vloxei8_v_i16mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vloxei.mask.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vloxei8_v_i16mf2_m_ntl_ALL(vbool32_t mask, const int16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vloxei8_v_i16m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vloxei.mask.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vloxei8_v_i16m1_m_ntl_ALL(vbool16_t mask, const int16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vloxei8_v_i16m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vloxei.mask.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vloxei8_v_i16m2_m_ntl_ALL(vbool8_t mask, const int16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vloxei8_v_i16m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vloxei.mask.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vloxei8_v_i16m4_m_ntl_ALL(vbool4_t mask, const int16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vloxei8_v_i16m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vloxei.mask.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vloxei8_v_i16m8_m_ntl_ALL(vbool2_t mask, const int16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vloxei8_v_i32mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vloxei.mask.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vloxei8_v_i32mf2_m_ntl_ALL(vbool64_t mask, const int32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vloxei8_v_i32m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vloxei.mask.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vloxei8_v_i32m1_m_ntl_ALL(vbool32_t mask, const int32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vloxei8_v_i32m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vloxei.mask.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vloxei8_v_i32m2_m_ntl_ALL(vbool16_t mask, const int32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vloxei8_v_i32m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vloxei.mask.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vloxei8_v_i32m4_m_ntl_ALL(vbool8_t mask, const int32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vloxei8_v_i32m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vloxei.mask.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vloxei8_v_i32m8_m_ntl_ALL(vbool4_t mask, const int32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vloxei8_v_i64m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vloxei.mask.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vloxei8_v_i64m1_m_ntl_ALL(vbool64_t mask, const int64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vloxei8_v_i64m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vloxei.mask.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vloxei8_v_i64m2_m_ntl_ALL(vbool32_t mask, const int64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vloxei8_v_i64m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vloxei.mask.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vloxei8_v_i64m4_m_ntl_ALL(vbool16_t mask, const int64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vloxei8_v_i64m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vloxei.mask.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vloxei8_v_i64m8_m_ntl_ALL(vbool8_t mask, const int64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vloxei8_v_u8mf8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vloxei.mask.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vloxei8_v_u8mf8_m_ntl_ALL(vbool64_t mask, const uint8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vloxei8_v_u8mf4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vloxei.mask.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vloxei8_v_u8mf4_m_ntl_ALL(vbool32_t mask, const uint8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vloxei8_v_u8mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vloxei.mask.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vloxei8_v_u8mf2_m_ntl_ALL(vbool16_t mask, const uint8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vloxei8_v_u8m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vloxei.mask.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vloxei8_v_u8m1_m_ntl_ALL(vbool8_t mask, const uint8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vloxei8_v_u8m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vloxei.mask.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vloxei8_v_u8m2_m_ntl_ALL(vbool4_t mask, const uint8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vloxei8_v_u8m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vloxei.mask.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vloxei8_v_u8m4_m_ntl_ALL(vbool2_t mask, const uint8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vloxei8_v_u8m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vloxei.mask.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], <vscale x 64 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vloxei8_v_u8m8_m_ntl_ALL(vbool1_t mask, const uint8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vloxei8_v_u16mf4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vloxei.mask.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vloxei8_v_u16mf4_m_ntl_ALL(vbool64_t mask, const uint16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vloxei8_v_u16mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vloxei.mask.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vloxei8_v_u16mf2_m_ntl_ALL(vbool32_t mask, const uint16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vloxei8_v_u16m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vloxei.mask.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vloxei8_v_u16m1_m_ntl_ALL(vbool16_t mask, const uint16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vloxei8_v_u16m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vloxei.mask.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vloxei8_v_u16m2_m_ntl_ALL(vbool8_t mask, const uint16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vloxei8_v_u16m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vloxei.mask.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vloxei8_v_u16m4_m_ntl_ALL(vbool4_t mask, const uint16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vloxei8_v_u16m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vloxei.mask.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> poison, ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vloxei8_v_u16m8_m_ntl_ALL(vbool2_t mask, const uint16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vloxei8_v_u32mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vloxei.mask.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vloxei8_v_u32mf2_m_ntl_ALL(vbool64_t mask, const uint32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vloxei8_v_u32m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vloxei.mask.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vloxei8_v_u32m1_m_ntl_ALL(vbool32_t mask, const uint32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vloxei8_v_u32m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vloxei.mask.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vloxei8_v_u32m2_m_ntl_ALL(vbool16_t mask, const uint32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vloxei8_v_u32m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vloxei.mask.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vloxei8_v_u32m4_m_ntl_ALL(vbool8_t mask, const uint32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vloxei8_v_u32m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vloxei.mask.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> poison, ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vloxei8_v_u32m8_m_ntl_ALL(vbool4_t mask, const uint32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vloxei8_v_u64m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vloxei.mask.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> poison, ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vloxei8_v_u64m1_m_ntl_ALL(vbool64_t mask, const uint64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vloxei8_v_u64m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vloxei.mask.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> poison, ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vloxei8_v_u64m2_m_ntl_ALL(vbool32_t mask, const uint64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vloxei8_v_u64m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vloxei.mask.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> poison, ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vloxei8_v_u64m4_m_ntl_ALL(vbool16_t mask, const uint64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vloxei8_v_u64m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vloxei.mask.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vloxei8_v_u64m8_m_ntl_ALL(vbool8_t mask, const uint64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return __riscv_vloxei8_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

