// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh \
// RUN:   -target-feature +zvfh -disable-O0-optnone  \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16mf4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1f16.p0.i64(<vscale x 1 x half> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6:![0-9]+]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf4_ntl_P1(_Float16 *base, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16mf2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2f16.p0.i64(<vscale x 2 x half> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf2_ntl_P1(_Float16 *base, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m1_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4f16.p0.i64(<vscale x 4 x half> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m1_ntl_P1(_Float16 *base, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8f16.p0.i64(<vscale x 8 x half> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m2_ntl_P1(_Float16 *base, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16f16.p0.i64(<vscale x 16 x half> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m4_ntl_P1(_Float16 *base, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m8_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32f16.p0.i64(<vscale x 32 x half> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m8_ntl_P1(_Float16 *base, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16mf4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf4_ntl_P1(int16_t *base, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16mf2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf2_ntl_P1(int16_t *base, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m1_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m1_ntl_P1(int16_t *base, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m2_ntl_P1(int16_t *base, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m4_ntl_P1(int16_t *base, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m8_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m8_ntl_P1(int16_t *base, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16mf4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf4_ntl_P1(uint16_t *base, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16mf2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf2_ntl_P1(uint16_t *base, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m1_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m1_ntl_P1(uint16_t *base, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m2_ntl_P1(uint16_t *base, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m4_ntl_P1(uint16_t *base, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m8_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m8_ntl_P1(uint16_t *base, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16mf4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1f16.p0.i64(<vscale x 1 x half> [[VALUE]], ptr [[BASE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf4_m_ntl_P1(vbool64_t mask, _Float16 *base, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16mf2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2f16.p0.i64(<vscale x 2 x half> [[VALUE]], ptr [[BASE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf2_m_ntl_P1(vbool32_t mask, _Float16 *base, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m1_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4f16.p0.i64(<vscale x 4 x half> [[VALUE]], ptr [[BASE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m1_m_ntl_P1(vbool16_t mask, _Float16 *base, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8f16.p0.i64(<vscale x 8 x half> [[VALUE]], ptr [[BASE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m2_m_ntl_P1(vbool8_t mask, _Float16 *base, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16f16.p0.i64(<vscale x 16 x half> [[VALUE]], ptr [[BASE]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m4_m_ntl_P1(vbool4_t mask, _Float16 *base, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_f16m8_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32f16.p0.i64(<vscale x 32 x half> [[VALUE]], ptr [[BASE]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m8_m_ntl_P1(vbool2_t mask, _Float16 *base, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16mf4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf4_m_ntl_P1(vbool64_t mask, int16_t *base, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16mf2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf2_m_ntl_P1(vbool32_t mask, int16_t *base, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m1_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m1_m_ntl_P1(vbool16_t mask, int16_t *base, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m2_m_ntl_P1(vbool8_t mask, int16_t *base, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m4_m_ntl_P1(vbool4_t mask, int16_t *base, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_i16m8_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m8_m_ntl_P1(vbool2_t mask, int16_t *base, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16mf4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf4_m_ntl_P1(vbool64_t mask, uint16_t *base, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16mf2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf2_m_ntl_P1(vbool32_t mask, uint16_t *base, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m1_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m1_m_ntl_P1(vbool16_t mask, uint16_t *base, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m2_m_ntl_P1(vbool8_t mask, uint16_t *base, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m4_m_ntl_P1(vbool4_t mask, uint16_t *base, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse16_v_u16m8_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m8_m_ntl_P1(vbool2_t mask, uint16_t *base, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vse16_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

