// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vse64_v_f64m1_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1f64.p0.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m1_ntl_S1(double *base, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2f64.p0.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m2_ntl_S1(double *base, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4f64.p0.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m4_ntl_S1(double *base, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m8_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8f64.p0.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m8_ntl_S1(double *base, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m1_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m1_ntl_S1(int64_t *base, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m2_ntl_S1(int64_t *base, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m4_ntl_S1(int64_t *base, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m8_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m8_ntl_S1(int64_t *base, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m1_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m1_ntl_S1(uint64_t *base, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m2_ntl_S1(uint64_t *base, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m4_ntl_S1(uint64_t *base, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m8_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m8_ntl_S1(uint64_t *base, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m1_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1f64.p0.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m1_m_ntl_S1(vbool64_t mask, double *base, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2f64.p0.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m2_m_ntl_S1(vbool32_t mask, double *base, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4f64.p0.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m4_m_ntl_S1(vbool16_t mask, double *base, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_f64m8_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8f64.p0.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_f64m8_m_ntl_S1(vbool8_t mask, double *base, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m1_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m1_m_ntl_S1(vbool64_t mask, int64_t *base, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m2_m_ntl_S1(vbool32_t mask, int64_t *base, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m4_m_ntl_S1(vbool16_t mask, int64_t *base, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_i64m8_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_i64m8_m_ntl_S1(vbool8_t mask, int64_t *base, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m1_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m1_m_ntl_S1(vbool64_t mask, uint64_t *base, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m2_m_ntl_S1(vbool32_t mask, uint64_t *base, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m4_m_ntl_S1(vbool16_t mask, uint64_t *base, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vse64_v_u64m8_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse64_v_u64m8_m_ntl_S1(vbool8_t mask, uint64_t *base, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vse64_ntl(mask, base, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

