// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh \
// RUN:   -target-feature +zvfh -disable-O0-optnone  \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16mf4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f16.p0.nxv1i8.i64(<vscale x 1 x half> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6:![0-9]+]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf4_ntl_S1(_Float16 *base, vuint8mf8_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f16.p0.nxv2i8.i64(<vscale x 2 x half> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf2_ntl_S1(_Float16 *base, vuint8mf4_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f16.p0.nxv4i8.i64(<vscale x 4 x half> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m1_ntl_S1(_Float16 *base, vuint8mf2_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f16.p0.nxv8i8.i64(<vscale x 8 x half> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m2_ntl_S1(_Float16 *base, vuint8m1_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f16.p0.nxv16i8.i64(<vscale x 16 x half> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m4_ntl_S1(_Float16 *base, vuint8m2_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32f16.p0.nxv32i8.i64(<vscale x 32 x half> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m8_ntl_S1(_Float16 *base, vuint8m4_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f32.p0.nxv1i8.i64(<vscale x 1 x float> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32mf2_ntl_S1(float *base, vuint8mf8_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f32.p0.nxv2i8.i64(<vscale x 2 x float> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m1_ntl_S1(float *base, vuint8mf4_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f32.p0.nxv4i8.i64(<vscale x 4 x float> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m2_ntl_S1(float *base, vuint8mf2_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f32.p0.nxv8i8.i64(<vscale x 8 x float> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m4_ntl_S1(float *base, vuint8m1_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f32.p0.nxv16i8.i64(<vscale x 16 x float> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m8_ntl_S1(float *base, vuint8m2_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f64.p0.nxv1i8.i64(<vscale x 1 x double> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m1_ntl_S1(double *base, vuint8mf8_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f64.p0.nxv2i8.i64(<vscale x 2 x double> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m2_ntl_S1(double *base, vuint8mf4_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f64.p0.nxv4i8.i64(<vscale x 4 x double> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m4_ntl_S1(double *base, vuint8mf2_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f64.p0.nxv8i8.i64(<vscale x 8 x double> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m8_ntl_S1(double *base, vuint8m1_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8mf8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf8_ntl_S1(int8_t *base, vuint8mf8_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8mf4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf4_ntl_S1(int8_t *base, vuint8mf4_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf2_ntl_S1(int8_t *base, vuint8mf2_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m1_ntl_S1(int8_t *base, vuint8m1_t bindex, vint8m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m2_ntl_S1(int8_t *base, vuint8m2_t bindex, vint8m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m4_ntl_S1(int8_t *base, vuint8m4_t bindex, vint8m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> [[VALUE]], ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m8_ntl_S1(int8_t *base, vuint8m8_t bindex, vint8m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16mf4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf4_ntl_S1(int16_t *base, vuint8mf8_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf2_ntl_S1(int16_t *base, vuint8mf4_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m1_ntl_S1(int16_t *base, vuint8mf2_t bindex, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m2_ntl_S1(int16_t *base, vuint8m1_t bindex, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m4_ntl_S1(int16_t *base, vuint8m2_t bindex, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m8_ntl_S1(int16_t *base, vuint8m4_t bindex, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32mf2_ntl_S1(int32_t *base, vuint8mf8_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m1_ntl_S1(int32_t *base, vuint8mf4_t bindex, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m2_ntl_S1(int32_t *base, vuint8mf2_t bindex, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m4_ntl_S1(int32_t *base, vuint8m1_t bindex, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m8_ntl_S1(int32_t *base, vuint8m2_t bindex, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m1_ntl_S1(int64_t *base, vuint8mf8_t bindex, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m2_ntl_S1(int64_t *base, vuint8mf4_t bindex, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m4_ntl_S1(int64_t *base, vuint8mf2_t bindex, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m8_ntl_S1(int64_t *base, vuint8m1_t bindex, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8mf8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf8_ntl_S1(uint8_t *base, vuint8mf8_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8mf4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf4_ntl_S1(uint8_t *base, vuint8mf4_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf2_ntl_S1(uint8_t *base, vuint8mf2_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m1_ntl_S1(uint8_t *base, vuint8m1_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m2_ntl_S1(uint8_t *base, vuint8m2_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m4_ntl_S1(uint8_t *base, vuint8m4_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> [[VALUE]], ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m8_ntl_S1(uint8_t *base, vuint8m8_t bindex, vuint8m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16mf4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf4_ntl_S1(uint16_t *base, vuint8mf8_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf2_ntl_S1(uint16_t *base, vuint8mf4_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m1_ntl_S1(uint16_t *base, vuint8mf2_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m2_ntl_S1(uint16_t *base, vuint8m1_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m4_ntl_S1(uint16_t *base, vuint8m2_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m8_ntl_S1(uint16_t *base, vuint8m4_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32mf2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32mf2_ntl_S1(uint32_t *base, vuint8mf8_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m1_ntl_S1(uint32_t *base, vuint8mf4_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m2_ntl_S1(uint32_t *base, vuint8mf2_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m4_ntl_S1(uint32_t *base, vuint8m1_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m8_ntl_S1(uint32_t *base, vuint8m2_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m1_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m1_ntl_S1(uint64_t *base, vuint8mf8_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m2_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m2_ntl_S1(uint64_t *base, vuint8mf4_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m4_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m4_ntl_S1(uint64_t *base, vuint8mf2_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m8_ntl_S1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m8_ntl_S1(uint64_t *base, vuint8m1_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16mf4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f16.p0.nxv1i8.i64(<vscale x 1 x half> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf4_m_ntl_S1(vbool64_t mask, _Float16 *base, vuint8mf8_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f16.p0.nxv2i8.i64(<vscale x 2 x half> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf2_m_ntl_S1(vbool32_t mask, _Float16 *base, vuint8mf4_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f16.p0.nxv4i8.i64(<vscale x 4 x half> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m1_m_ntl_S1(vbool16_t mask, _Float16 *base, vuint8mf2_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f16.p0.nxv8i8.i64(<vscale x 8 x half> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m2_m_ntl_S1(vbool8_t mask, _Float16 *base, vuint8m1_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f16.p0.nxv16i8.i64(<vscale x 16 x half> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m4_m_ntl_S1(vbool4_t mask, _Float16 *base, vuint8m2_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f16m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x half> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32f16.p0.nxv32i8.i64(<vscale x 32 x half> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m8_m_ntl_S1(vbool2_t mask, _Float16 *base, vuint8m4_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f32.p0.nxv1i8.i64(<vscale x 1 x float> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32mf2_m_ntl_S1(vbool64_t mask, float *base, vuint8mf8_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f32.p0.nxv2i8.i64(<vscale x 2 x float> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m1_m_ntl_S1(vbool32_t mask, float *base, vuint8mf4_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f32.p0.nxv4i8.i64(<vscale x 4 x float> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m2_m_ntl_S1(vbool16_t mask, float *base, vuint8mf2_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f32.p0.nxv8i8.i64(<vscale x 8 x float> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m4_m_ntl_S1(vbool8_t mask, float *base, vuint8m1_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f32m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f32.p0.nxv16i8.i64(<vscale x 16 x float> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m8_m_ntl_S1(vbool4_t mask, float *base, vuint8m2_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f64.p0.nxv1i8.i64(<vscale x 1 x double> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m1_m_ntl_S1(vbool64_t mask, double *base, vuint8mf8_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f64.p0.nxv2i8.i64(<vscale x 2 x double> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m2_m_ntl_S1(vbool32_t mask, double *base, vuint8mf4_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f64.p0.nxv4i8.i64(<vscale x 4 x double> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m4_m_ntl_S1(vbool16_t mask, double *base, vuint8mf2_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_f64m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f64.p0.nxv8i8.i64(<vscale x 8 x double> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m8_m_ntl_S1(vbool8_t mask, double *base, vuint8m1_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8mf8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf8_m_ntl_S1(vbool64_t mask, int8_t *base, vuint8mf8_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8mf4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf4_m_ntl_S1(vbool32_t mask, int8_t *base, vuint8mf4_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf2_m_ntl_S1(vbool16_t mask, int8_t *base, vuint8mf2_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m1_m_ntl_S1(vbool8_t mask, int8_t *base, vuint8m1_t bindex, vint8m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m2_m_ntl_S1(vbool4_t mask, int8_t *base, vuint8m2_t bindex, vint8m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m4_m_ntl_S1(vbool2_t mask, int8_t *base, vuint8m4_t bindex, vint8m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i8m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> [[VALUE]], ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], <vscale x 64 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m8_m_ntl_S1(vbool1_t mask, int8_t *base, vuint8m8_t bindex, vint8m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16mf4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf4_m_ntl_S1(vbool64_t mask, int16_t *base, vuint8mf8_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf2_m_ntl_S1(vbool32_t mask, int16_t *base, vuint8mf4_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m1_m_ntl_S1(vbool16_t mask, int16_t *base, vuint8mf2_t bindex, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m2_m_ntl_S1(vbool8_t mask, int16_t *base, vuint8m1_t bindex, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m4_m_ntl_S1(vbool4_t mask, int16_t *base, vuint8m2_t bindex, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i16m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m8_m_ntl_S1(vbool2_t mask, int16_t *base, vuint8m4_t bindex, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32mf2_m_ntl_S1(vbool64_t mask, int32_t *base, vuint8mf8_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m1_m_ntl_S1(vbool32_t mask, int32_t *base, vuint8mf4_t bindex, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m2_m_ntl_S1(vbool16_t mask, int32_t *base, vuint8mf2_t bindex, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m4_m_ntl_S1(vbool8_t mask, int32_t *base, vuint8m1_t bindex, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i32m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m8_m_ntl_S1(vbool4_t mask, int32_t *base, vuint8m2_t bindex, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m1_m_ntl_S1(vbool64_t mask, int64_t *base, vuint8mf8_t bindex, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m2_m_ntl_S1(vbool32_t mask, int64_t *base, vuint8mf4_t bindex, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m4_m_ntl_S1(vbool16_t mask, int64_t *base, vuint8mf2_t bindex, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_i64m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m8_m_ntl_S1(vbool8_t mask, int64_t *base, vuint8m1_t bindex, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8mf8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.p0.nxv1i8.i64(<vscale x 1 x i8> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf8_m_ntl_S1(vbool64_t mask, uint8_t *base, vuint8mf8_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8mf4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.p0.nxv2i8.i64(<vscale x 2 x i8> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf4_m_ntl_S1(vbool32_t mask, uint8_t *base, vuint8mf4_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.p0.nxv4i8.i64(<vscale x 4 x i8> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf2_m_ntl_S1(vbool16_t mask, uint8_t *base, vuint8mf2_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.p0.nxv8i8.i64(<vscale x 8 x i8> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m1_m_ntl_S1(vbool8_t mask, uint8_t *base, vuint8m1_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.p0.nxv16i8.i64(<vscale x 16 x i8> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m2_m_ntl_S1(vbool4_t mask, uint8_t *base, vuint8m2_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i8.p0.nxv32i8.i64(<vscale x 32 x i8> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m4_m_ntl_S1(vbool2_t mask, uint8_t *base, vuint8m4_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u8m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i8> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv64i8.p0.nxv64i8.i64(<vscale x 64 x i8> [[VALUE]], ptr [[BASE]], <vscale x 64 x i8> [[BINDEX]], <vscale x 64 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m8_m_ntl_S1(vbool1_t mask, uint8_t *base, vuint8m8_t bindex, vuint8m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16mf4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.p0.nxv1i8.i64(<vscale x 1 x i16> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf4_m_ntl_S1(vbool64_t mask, uint16_t *base, vuint8mf8_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.p0.nxv2i8.i64(<vscale x 2 x i16> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf2_m_ntl_S1(vbool32_t mask, uint16_t *base, vuint8mf4_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.p0.nxv4i8.i64(<vscale x 4 x i16> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m1_m_ntl_S1(vbool16_t mask, uint16_t *base, vuint8mf2_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.p0.nxv8i8.i64(<vscale x 8 x i16> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m2_m_ntl_S1(vbool8_t mask, uint16_t *base, vuint8m1_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.p0.nxv16i8.i64(<vscale x 16 x i16> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m4_m_ntl_S1(vbool4_t mask, uint16_t *base, vuint8m2_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u16m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i16> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i16.p0.nxv32i8.i64(<vscale x 32 x i16> [[VALUE]], ptr [[BASE]], <vscale x 32 x i8> [[BINDEX]], <vscale x 32 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m8_m_ntl_S1(vbool2_t mask, uint16_t *base, vuint8m4_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32mf2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.p0.nxv1i8.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32mf2_m_ntl_S1(vbool64_t mask, uint32_t *base, vuint8mf8_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.p0.nxv2i8.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m1_m_ntl_S1(vbool32_t mask, uint32_t *base, vuint8mf4_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.p0.nxv4i8.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m2_m_ntl_S1(vbool16_t mask, uint32_t *base, vuint8mf2_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.p0.nxv8i8.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m4_m_ntl_S1(vbool8_t mask, uint32_t *base, vuint8m1_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u32m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.p0.nxv16i8.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], <vscale x 16 x i8> [[BINDEX]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m8_m_ntl_S1(vbool4_t mask, uint32_t *base, vuint8m2_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m1_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.p0.nxv1i8.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], <vscale x 1 x i8> [[BINDEX]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m1_m_ntl_S1(vbool64_t mask, uint64_t *base, vuint8mf8_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m2_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.p0.nxv2i8.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], <vscale x 2 x i8> [[BINDEX]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m2_m_ntl_S1(vbool32_t mask, uint64_t *base, vuint8mf4_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m4_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.p0.nxv4i8.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], <vscale x 4 x i8> [[BINDEX]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m4_m_ntl_S1(vbool16_t mask, uint64_t *base, vuint8mf2_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsoxei8_v_u64m8_m_ntl_S1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.p0.nxv8i8.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], <vscale x 8 x i8> [[BINDEX]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m8_m_ntl_S1(vbool8_t mask, uint64_t *base, vuint8m1_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vsoxei8_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

