// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vsse16_v_f16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv1f16.p0.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16mf4_ntl_ALL(_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv2f16.p0.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16mf2_ntl_ALL(_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv4f16.p0.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m1_ntl_ALL(_Float16 *base, ptrdiff_t bstride, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv8f16.p0.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m2_ntl_ALL(_Float16 *base, ptrdiff_t bstride, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv16f16.p0.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m4_ntl_ALL(_Float16 *base, ptrdiff_t bstride, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv32f16.p0.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m8_ntl_ALL(_Float16 *base, ptrdiff_t bstride, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16mf4_ntl_ALL(int16_t *base, ptrdiff_t bstride, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16mf2_ntl_ALL(int16_t *base, ptrdiff_t bstride, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m1_ntl_ALL(int16_t *base, ptrdiff_t bstride, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m2_ntl_ALL(int16_t *base, ptrdiff_t bstride, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m4_ntl_ALL(int16_t *base, ptrdiff_t bstride, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m8_ntl_ALL(int16_t *base, ptrdiff_t bstride, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16mf4_ntl_ALL(uint16_t *base, ptrdiff_t bstride, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16mf2_ntl_ALL(uint16_t *base, ptrdiff_t bstride, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m1_ntl_ALL(uint16_t *base, ptrdiff_t bstride, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m2_ntl_ALL(uint16_t *base, ptrdiff_t bstride, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m4_ntl_ALL(uint16_t *base, ptrdiff_t bstride, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m8_ntl_ALL(uint16_t *base, ptrdiff_t bstride, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv1f16.p0.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16mf4_m_ntl_ALL(vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv2f16.p0.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16mf2_m_ntl_ALL(vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv4f16.p0.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m1_m_ntl_ALL(vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv8f16.p0.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m2_m_ntl_ALL(vbool8_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv16f16.p0.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m4_m_ntl_ALL(vbool4_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_f16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv32f16.p0.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_f16m8_m_ntl_ALL(vbool2_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16mf4_m_ntl_ALL(vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16mf2_m_ntl_ALL(vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m1_m_ntl_ALL(vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m2_m_ntl_ALL(vbool8_t mask, int16_t *base, ptrdiff_t bstride, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m4_m_ntl_ALL(vbool4_t mask, int16_t *base, ptrdiff_t bstride, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_i16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_i16m8_m_ntl_ALL(vbool2_t mask, int16_t *base, ptrdiff_t bstride, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv1i16.p0.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16mf4_m_ntl_ALL(vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv2i16.p0.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16mf2_m_ntl_ALL(vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv4i16.p0.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m1_m_ntl_ALL(vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv8i16.p0.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m2_m_ntl_ALL(vbool8_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv16i16.p0.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m4_m_ntl_ALL(vbool4_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsse16_v_u16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsse.mask.nxv32i16.p0.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsse16_v_u16m8_m_ntl_ALL(vbool2_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vsse16_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_ALL);
}

