// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vsuxei16_v_f16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1f16.p0.nxv1i16.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16mf4_ntl_ALL(_Float16 *base, vuint16mf4_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2f16.p0.nxv2i16.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16mf2_ntl_ALL(_Float16 *base, vuint16mf2_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4f16.p0.nxv4i16.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m1_ntl_ALL(_Float16 *base, vuint16m1_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8f16.p0.nxv8i16.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m2_ntl_ALL(_Float16 *base, vuint16m2_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16f16.p0.nxv16i16.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m4_ntl_ALL(_Float16 *base, vuint16m4_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv32f16.p0.nxv32i16.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m8_ntl_ALL(_Float16 *base, vuint16m8_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1f32.p0.nxv1i16.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32mf2_ntl_ALL(float *base, vuint16mf4_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2f32.p0.nxv2i16.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m1_ntl_ALL(float *base, vuint16mf2_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4f32.p0.nxv4i16.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m2_ntl_ALL(float *base, vuint16m1_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8f32.p0.nxv8i16.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m4_ntl_ALL(float *base, vuint16m2_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16f32.p0.nxv16i16.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m8_ntl_ALL(float *base, vuint16m4_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1f64.p0.nxv1i16.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m1_ntl_ALL(double *base, vuint16mf4_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2f64.p0.nxv2i16.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m2_ntl_ALL(double *base, vuint16mf2_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4f64.p0.nxv4i16.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m4_ntl_ALL(double *base, vuint16m1_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8f64.p0.nxv8i16.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m8_ntl_ALL(double *base, vuint16m2_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8mf8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8mf8_ntl_ALL(int8_t *base, vuint16mf4_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8mf4_ntl_ALL(int8_t *base, vuint16mf2_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8mf2_ntl_ALL(int8_t *base, vuint16m1_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8m1_ntl_ALL(int8_t *base, vuint16m2_t bindex, vint8m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8m2_ntl_ALL(int8_t *base, vuint16m4_t bindex, vint8m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8m4_ntl_ALL(int8_t *base, vuint16m8_t bindex, vint8m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16mf4_ntl_ALL(int16_t *base, vuint16mf4_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16mf2_ntl_ALL(int16_t *base, vuint16mf2_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m1_ntl_ALL(int16_t *base, vuint16m1_t bindex, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m2_ntl_ALL(int16_t *base, vuint16m2_t bindex, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m4_ntl_ALL(int16_t *base, vuint16m4_t bindex, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m8_ntl_ALL(int16_t *base, vuint16m8_t bindex, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32mf2_ntl_ALL(int32_t *base, vuint16mf4_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m1_ntl_ALL(int32_t *base, vuint16mf2_t bindex, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m2_ntl_ALL(int32_t *base, vuint16m1_t bindex, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m4_ntl_ALL(int32_t *base, vuint16m2_t bindex, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m8_ntl_ALL(int32_t *base, vuint16m4_t bindex, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m1_ntl_ALL(int64_t *base, vuint16mf4_t bindex, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m2_ntl_ALL(int64_t *base, vuint16mf2_t bindex, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m4_ntl_ALL(int64_t *base, vuint16m1_t bindex, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m8_ntl_ALL(int64_t *base, vuint16m2_t bindex, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8mf8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8mf8_ntl_ALL(uint8_t *base, vuint16mf4_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8mf4_ntl_ALL(uint8_t *base, vuint16mf2_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8mf2_ntl_ALL(uint8_t *base, vuint16m1_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8m1_ntl_ALL(uint8_t *base, vuint16m2_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8m2_ntl_ALL(uint8_t *base, vuint16m4_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8m4_ntl_ALL(uint8_t *base, vuint16m8_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16mf4_ntl_ALL(uint16_t *base, vuint16mf4_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16mf2_ntl_ALL(uint16_t *base, vuint16mf2_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m1_ntl_ALL(uint16_t *base, vuint16m1_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m2_ntl_ALL(uint16_t *base, vuint16m2_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m4_ntl_ALL(uint16_t *base, vuint16m4_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m8_ntl_ALL(uint16_t *base, vuint16m8_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32mf2_ntl_ALL(uint32_t *base, vuint16mf4_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m1_ntl_ALL(uint32_t *base, vuint16mf2_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m2_ntl_ALL(uint32_t *base, vuint16m1_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m4_ntl_ALL(uint32_t *base, vuint16m2_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m8_ntl_ALL(uint32_t *base, vuint16m4_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m1_ntl_ALL(uint64_t *base, vuint16mf4_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m2_ntl_ALL(uint64_t *base, vuint16mf2_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m4_ntl_ALL(uint64_t *base, vuint16m1_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m8_ntl_ALL(uint64_t *base, vuint16m2_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1f16.p0.nxv1i16.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16mf4_m_ntl_ALL(vbool64_t mask, _Float16 *base, vuint16mf4_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2f16.p0.nxv2i16.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16mf2_m_ntl_ALL(vbool32_t mask, _Float16 *base, vuint16mf2_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4f16.p0.nxv4i16.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m1_m_ntl_ALL(vbool16_t mask, _Float16 *base, vuint16m1_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8f16.p0.nxv8i16.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m2_m_ntl_ALL(vbool8_t mask, _Float16 *base, vuint16m2_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16f16.p0.nxv16i16.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m4_m_ntl_ALL(vbool4_t mask, _Float16 *base, vuint16m4_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv32f16.p0.nxv32i16.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f16m8_m_ntl_ALL(vbool2_t mask, _Float16 *base, vuint16m8_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1f32.p0.nxv1i16.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32mf2_m_ntl_ALL(vbool64_t mask, float *base, vuint16mf4_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2f32.p0.nxv2i16.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m1_m_ntl_ALL(vbool32_t mask, float *base, vuint16mf2_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4f32.p0.nxv4i16.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m2_m_ntl_ALL(vbool16_t mask, float *base, vuint16m1_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8f32.p0.nxv8i16.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m4_m_ntl_ALL(vbool8_t mask, float *base, vuint16m2_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16f32.p0.nxv16i16.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f32m8_m_ntl_ALL(vbool4_t mask, float *base, vuint16m4_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1f64.p0.nxv1i16.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m1_m_ntl_ALL(vbool64_t mask, double *base, vuint16mf4_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2f64.p0.nxv2i16.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m2_m_ntl_ALL(vbool32_t mask, double *base, vuint16mf2_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4f64.p0.nxv4i16.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m4_m_ntl_ALL(vbool16_t mask, double *base, vuint16m1_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_f64m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8f64.p0.nxv8i16.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_f64m8_m_ntl_ALL(vbool8_t mask, double *base, vuint16m2_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8mf8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8mf8_m_ntl_ALL(vbool64_t mask, int8_t *base, vuint16mf4_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8mf4_m_ntl_ALL(vbool32_t mask, int8_t *base, vuint16mf2_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8mf2_m_ntl_ALL(vbool16_t mask, int8_t *base, vuint16m1_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8m1_m_ntl_ALL(vbool8_t mask, int8_t *base, vuint16m2_t bindex, vint8m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8m2_m_ntl_ALL(vbool4_t mask, int8_t *base, vuint16m4_t bindex, vint8m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i8m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i8m4_m_ntl_ALL(vbool2_t mask, int8_t *base, vuint16m8_t bindex, vint8m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16mf4_m_ntl_ALL(vbool64_t mask, int16_t *base, vuint16mf4_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16mf2_m_ntl_ALL(vbool32_t mask, int16_t *base, vuint16mf2_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m1_m_ntl_ALL(vbool16_t mask, int16_t *base, vuint16m1_t bindex, vint16m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m2_m_ntl_ALL(vbool8_t mask, int16_t *base, vuint16m2_t bindex, vint16m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m4_m_ntl_ALL(vbool4_t mask, int16_t *base, vuint16m4_t bindex, vint16m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i16m8_m_ntl_ALL(vbool2_t mask, int16_t *base, vuint16m8_t bindex, vint16m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32mf2_m_ntl_ALL(vbool64_t mask, int32_t *base, vuint16mf4_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m1_m_ntl_ALL(vbool32_t mask, int32_t *base, vuint16mf2_t bindex, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m2_m_ntl_ALL(vbool16_t mask, int32_t *base, vuint16m1_t bindex, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m4_m_ntl_ALL(vbool8_t mask, int32_t *base, vuint16m2_t bindex, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i32m8_m_ntl_ALL(vbool4_t mask, int32_t *base, vuint16m4_t bindex, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m1_m_ntl_ALL(vbool64_t mask, int64_t *base, vuint16mf4_t bindex, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m2_m_ntl_ALL(vbool32_t mask, int64_t *base, vuint16mf2_t bindex, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m4_m_ntl_ALL(vbool16_t mask, int64_t *base, vuint16m1_t bindex, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_i64m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_i64m8_m_ntl_ALL(vbool8_t mask, int64_t *base, vuint16m2_t bindex, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8mf8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8mf8_m_ntl_ALL(vbool64_t mask, uint8_t *base, vuint16mf4_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8mf4_m_ntl_ALL(vbool32_t mask, uint8_t *base, vuint16mf2_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8mf2_m_ntl_ALL(vbool16_t mask, uint8_t *base, vuint16m1_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8m1_m_ntl_ALL(vbool8_t mask, uint8_t *base, vuint16m2_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8m2_m_ntl_ALL(vbool4_t mask, uint8_t *base, vuint16m4_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u8m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u8m4_m_ntl_ALL(vbool2_t mask, uint8_t *base, vuint16m8_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16mf4_m_ntl_ALL(vbool64_t mask, uint16_t *base, vuint16mf4_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16mf2_m_ntl_ALL(vbool32_t mask, uint16_t *base, vuint16mf2_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m1_m_ntl_ALL(vbool16_t mask, uint16_t *base, vuint16m1_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m2_m_ntl_ALL(vbool8_t mask, uint16_t *base, vuint16m2_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m4_m_ntl_ALL(vbool4_t mask, uint16_t *base, vuint16m4_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u16m8_m_ntl_ALL(vbool2_t mask, uint16_t *base, vuint16m8_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32mf2_m_ntl_ALL(vbool64_t mask, uint32_t *base, vuint16mf4_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m1_m_ntl_ALL(vbool32_t mask, uint32_t *base, vuint16mf2_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m2_m_ntl_ALL(vbool16_t mask, uint32_t *base, vuint16m1_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m4_m_ntl_ALL(vbool8_t mask, uint32_t *base, vuint16m2_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u32m8_m_ntl_ALL(vbool4_t mask, uint32_t *base, vuint16m4_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m1_m_ntl_ALL(vbool64_t mask, uint64_t *base, vuint16mf4_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m2_m_ntl_ALL(vbool32_t mask, uint64_t *base, vuint16mf2_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m4_m_ntl_ALL(vbool16_t mask, uint64_t *base, vuint16m1_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vsuxei16_v_u64m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vsuxei.mask.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vsuxei16_v_u64m8_m_ntl_ALL(vbool8_t mask, uint64_t *base, vuint16m2_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vsuxei16_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL);
}

