; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=loop-unroll,slp-vectorizer -mtriple=riscv64 -mcpu=sifive-p470 -S %s | FileCheck %s

; Mimic the prelink and nonlto sifive pipeline for runtime unrolling followed
; by slp for a RISC-V target.

define dso_local nofpclass(nan inf) float @s352(ptr nocapture noundef %func_args, ptr %a, ptr %b) {
; CHECK-LABEL: define dso_local nofpclass(nan inf) float @s352(
; CHECK-SAME: ptr noundef captures(none) [[FUNC_ARGS:%.*]], ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND2_PREHEADER:%.*]]
; CHECK:       for.cond2.preheader:
; CHECK-NEXT:    [[NL_062:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_COND_CLEANUP4:%.*]] ]
; CHECK-NEXT:    br label [[FOR_BODY5:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[ADD39_LCSSA_LCSSA:%.*]] = phi float [ [[ADD39_LCSSA:%.*]], [[FOR_COND_CLEANUP4]] ]
; CHECK-NEXT:    ret float [[ADD39_LCSSA_LCSSA]]
; CHECK:       for.cond.cleanup4:
; CHECK-NEXT:    [[ADD39_LCSSA]] = phi float [ [[OP_RDX4:%.*]], [[FOR_BODY5]] ]
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[NL_062]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], 800000
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_COND2_PREHEADER]]
; CHECK:       for.body5:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_COND2_PREHEADER]] ], [ [[INDVARS_IV_NEXT_3:%.*]], [[FOR_BODY5]] ]
; CHECK-NEXT:    [[DOT_160:%.*]] = phi float [ 0.000000e+00, [[FOR_COND2_PREHEADER]] ], [ [[OP_RDX4]], [[FOR_BODY5]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [32000 x float], ptr [[A]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds [32000 x float], ptr [[B]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_2:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 15
; CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[ARRAYIDX7]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = fmul fast <16 x float> [[TMP1]], [[TMP0]]
; CHECK-NEXT:    [[I2_3:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 16
; CHECK-NEXT:    [[ARRAYIDX10_3:%.*]] = getelementptr inbounds [32000 x float], ptr [[A]], i64 0, i64 [[I2_3]]
; CHECK-NEXT:    [[ARRAYIDX13_3:%.*]] = getelementptr inbounds [32000 x float], ptr [[B]], i64 0, i64 [[I2_3]]
; CHECK-NEXT:    [[TMP3:%.*]] = load <4 x float>, ptr [[ARRAYIDX10_3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load <4 x float>, ptr [[ARRAYIDX13_3]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = fmul fast <4 x float> [[TMP4]], [[TMP3]]
; CHECK-NEXT:    [[TMP6:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP2]], i64 0)
; CHECK-NEXT:    [[RDX_OP:%.*]] = fadd fast <4 x float> [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP2]], <4 x float> [[RDX_OP]], i64 0)
; CHECK-NEXT:    [[TMP8:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP7]])
; CHECK-NEXT:    [[OP_RDX4]] = fadd fast float [[TMP8]], [[DOT_160]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_3]] = add nuw nsw i64 [[INDVARS_IV]], 20
; CHECK-NEXT:    [[CMP3_3:%.*]] = icmp ult i64 [[INDVARS_IV_NEXT_2]], 31995
; CHECK-NEXT:    br i1 [[CMP3_3]], label [[FOR_BODY5]], label [[FOR_COND_CLEANUP4]]
;
entry:
  br label %for.cond2.preheader

for.cond2.preheader:                              ; preds = %for.cond.cleanup4, %entry
  %nl.062 = phi i32 [ 0, %entry ], [ %inc, %for.cond.cleanup4 ]
  br label %for.body5

for.cond.cleanup:                                 ; preds = %for.cond.cleanup4
  ret float %add39

for.cond.cleanup4:                                ; preds = %for.body5
  %inc = add nuw nsw i32 %nl.062, 1
  %exitcond.not = icmp eq i32 %inc, 800000
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.cond2.preheader

for.body5:                                        ; preds = %for.body5, %for.cond2.preheader
  %indvars.iv = phi i64 [ 0, %for.cond2.preheader ], [ %indvars.iv.next, %for.body5 ]
  %dot.160 = phi float [ 0.000000e+00, %for.cond2.preheader ], [ %add39, %for.body5 ]
  %arrayidx = getelementptr inbounds [32000 x float], ptr %a, i64 0, i64 %indvars.iv
  %i = load float, ptr %arrayidx, align 4
  %arrayidx7 = getelementptr inbounds [32000 x float], ptr %b, i64 0, i64 %indvars.iv
  %i1 = load float, ptr %arrayidx7, align 4
  %mul = fmul fast float %i1, %i
  %add = fadd fast float %mul, %dot.160
  %i2 = add nuw nsw i64 %indvars.iv, 1
  %arrayidx10 = getelementptr inbounds [32000 x float], ptr %a, i64 0, i64 %i2
  %i3 = load float, ptr %arrayidx10, align 4
  %arrayidx13 = getelementptr inbounds [32000 x float], ptr %b, i64 0, i64 %i2
  %i4 = load float, ptr %arrayidx13, align 4
  %mul14 = fmul fast float %i4, %i3
  %add15 = fadd fast float %add, %mul14
  %i5 = add nuw nsw i64 %indvars.iv, 2
  %arrayidx18 = getelementptr inbounds [32000 x float], ptr %a, i64 0, i64 %i5
  %i6 = load float, ptr %arrayidx18, align 4
  %arrayidx21 = getelementptr inbounds [32000 x float], ptr %b, i64 0, i64 %i5
  %i7 = load float, ptr %arrayidx21, align 4
  %mul22 = fmul fast float %i7, %i6
  %add23 = fadd fast float %add15, %mul22
  %i8 = add nuw nsw i64 %indvars.iv, 3
  %arrayidx26 = getelementptr inbounds [32000 x float], ptr %a, i64 0, i64 %i8
  %i9 = load float, ptr %arrayidx26, align 4
  %arrayidx29 = getelementptr inbounds [32000 x float], ptr %b, i64 0, i64 %i8
  %i10 = load float, ptr %arrayidx29, align 4
  %mul30 = fmul fast float %i10, %i9
  %add31 = fadd fast float %add23, %mul30
  %i11 = add nuw nsw i64 %indvars.iv, 4
  %arrayidx34 = getelementptr inbounds [32000 x float], ptr %a, i64 0, i64 %i11
  %i12 = load float, ptr %arrayidx34, align 4
  %arrayidx37 = getelementptr inbounds [32000 x float], ptr %b, i64 0, i64 %i11
  %i13 = load float, ptr %arrayidx37, align 4
  %mul38 = fmul fast float %i13, %i12
  %add39 = fadd fast float %add31, %mul38
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 5
  %cmp3 = icmp ult i64 %indvars.iv, 31995
  br i1 %cmp3, label %for.body5, label %for.cond.cleanup4
}
