; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=slp-vectorizer,loop-unroll -unroll-count=7 -sifive-unroll-detect-vector-loops=true -mtriple=riscv64 -mcpu=sifive-p470 -S %s | FileCheck %s

; Mimic the prelink and nonlto sifive pipeline for slp followed by runtime unrolling
; for a RISC-V target. The initial input is an unrolled loop which slp will vectorize.

  %class.Image = type { i32, i32, i32, i32, i32, ptr }
  %class.Image.0 = type { i32, i32, i32, i32, i32, ptr }
  %class.ImageMask = type { %class.Image, %"class.std::vector" }
  %"class.std::vector" = type { %"struct.std::_Vector_base" }
  %"struct.std::_Vector_base" = type { %"struct.std::_Vector_base<std::pair<int, int>, std::allocator<std::pair<int, int>>>::_Vector_impl" }
  %"struct.std::_Vector_base<std::pair<int, int>, std::allocator<std::pair<int, int>>>::_Vector_impl" = type { %"struct.std::_Vector_base<std::pair<int, int>, std::allocator<std::pair<int, int>>>::_Vector_impl_data" }
  %"struct.std::_Vector_base<std::pair<int, int>, std::allocator<std::pair<int, int>>>::_Vector_impl_data" = type { ptr, ptr, ptr }
  %"class.std::mersenne_twister_engine" = type { [624 x i64], i64 }
  %"struct.std::pair" = type { i32, i32 }
  %struct.NnfComponent = type { i32, i32, float }

define internal fastcc float @foo(ptr nocapture noundef nonnull readonly align 8 dereferenceable(32) %input, ptr noundef nonnull align 8 dereferenceable(56) %inpaint_domain_mask, i32 noundef signext %inpaint_iterations, i32 noundef signext %patchmatch_iterations, ptr nocapture noundef %output) {
; CHECK-LABEL: define internal fastcc float @foo(
; CHECK-SAME: ptr noundef nonnull readonly align 8 captures(none) dereferenceable(32) [[INPUT:%.*]], ptr noundef nonnull align 8 dereferenceable(56) [[INPAINT_DOMAIN_MASK:%.*]], i32 noundef signext [[INPAINT_ITERATIONS:%.*]], i32 noundef signext [[PATCHMATCH_ITERATIONS:%.*]], ptr noundef captures(none) [[OUTPUT:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[GENERATOR_I_I:%.*]] = alloca %"class.std::mersenne_twister_engine", align 8
; CHECK-NEXT:    [[SRC_MASK:%.*]] = alloca [[CLASS_IMAGEMASK:%.*]], align 8
; CHECK-NEXT:    [[TRG_MASK:%.*]] = alloca [[CLASS_IMAGEMASK]], align 8
; CHECK-NEXT:    [[COORDS1_I:%.*]] = getelementptr inbounds i8, ptr [[TRG_MASK]], i64 32
; CHECK-NEXT:    [[STRIDE__I_I203:%.*]] = getelementptr inbounds i8, ptr [[OUTPUT]], i64 16
; CHECK-NEXT:    [[DATA__I_I202:%.*]] = getelementptr inbounds i8, ptr [[OUTPUT]], i64 24
; CHECK-NEXT:    [[CHANNELS__I_I205:%.*]] = getelementptr inbounds i8, ptr [[OUTPUT]], i64 8
; CHECK-NEXT:    [[_M_FINISH_I39_I_I:%.*]] = getelementptr inbounds i8, ptr [[TRG_MASK]], i64 40
; CHECK-NEXT:    [[P31:%.*]] = load ptr, ptr [[_M_FINISH_I39_I_I]], align 8, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[P32:%.*]] = load ptr, ptr [[COORDS1_I]], align 8, !tbaa [[TBAA5:![0-9]+]]
; CHECK-NEXT:    [[SUB_PTR_LHS_CAST_I40_I_I:%.*]] = ptrtoint ptr [[P31]] to i64
; CHECK-NEXT:    [[SUB_PTR_RHS_CAST_I41_I_I:%.*]] = ptrtoint ptr [[P32]] to i64
; CHECK-NEXT:    [[SUB_PTR_SUB_I42_I_I:%.*]] = sub i64 [[SUB_PTR_LHS_CAST_I40_I_I]], [[SUB_PTR_RHS_CAST_I41_I_I]]
; CHECK-NEXT:    [[SUB_PTR_DIV_I43_I_I:%.*]] = ashr exact i64 [[SUB_PTR_SUB_I42_I_I]], 3
; CHECK-NEXT:    [[COORDS_I:%.*]] = getelementptr inbounds i8, ptr [[SRC_MASK]], i64 32
; CHECK-NEXT:    [[_M_FINISH_I_I_I:%.*]] = getelementptr inbounds i8, ptr [[SRC_MASK]], i64 40
; CHECK-NEXT:    [[P28:%.*]] = load ptr, ptr [[_M_FINISH_I_I_I]], align 8
; CHECK-NEXT:    [[P29:%.*]] = load ptr, ptr [[COORDS_I]], align 8
; CHECK-NEXT:    [[ADD_PTR_I_I_I:%.*]] = getelementptr inbounds %"struct.std::pair", ptr [[P29]], i64 0
; CHECK-NEXT:    [[I34:%.*]] = load i32, ptr [[ADD_PTR_I_I_I]], align 4, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[SECOND_I_I:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I_I_I]], i64 4
; CHECK-NEXT:    [[I35:%.*]] = load i32, ptr [[SECOND_I_I]], align 4, !tbaa [[TBAA9:![0-9]+]]
; CHECK-NEXT:    [[SUB_I:%.*]] = add nsw i32 [[I34]], -3
; CHECK-NEXT:    [[ARRAYIDX_I_I_I_I_I:%.*]] = getelementptr inbounds [624 x i64], ptr [[GENERATOR_I_I]], i64 0, i64 0
; CHECK-NEXT:    [[I64:%.*]] = load i64, ptr [[ARRAYIDX_I_I_I_I_I]], align 8, !tbaa [[TBAA10:![0-9]+]]
; CHECK-NEXT:    [[SHR_I_I_I_I_I:%.*]] = lshr i64 [[I64]], 11
; CHECK-NEXT:    [[AND_I_I_I_I_I:%.*]] = and i64 [[SHR_I_I_I_I_I]], 4294967295
; CHECK-NEXT:    [[XOR_I_I_I_I_I:%.*]] = xor i64 [[AND_I_I_I_I_I]], [[I64]]
; CHECK-NEXT:    [[SHL_I_I_I_I_I:%.*]] = shl i64 [[XOR_I_I_I_I_I]], 7
; CHECK-NEXT:    [[AND3_I_I_I_I_I:%.*]] = and i64 [[SHL_I_I_I_I_I]], 2636928640
; CHECK-NEXT:    [[XOR4_I_I_I_I_I:%.*]] = xor i64 [[AND3_I_I_I_I_I]], [[XOR_I_I_I_I_I]]
; CHECK-NEXT:    [[SHL5_I_I_I_I_I:%.*]] = shl i64 [[XOR4_I_I_I_I_I]], 15
; CHECK-NEXT:    [[AND6_I_I_I_I_I:%.*]] = and i64 [[SHL5_I_I_I_I_I]], 4022730752
; CHECK-NEXT:    [[XOR7_I_I_I_I_I:%.*]] = xor i64 [[AND6_I_I_I_I_I]], [[XOR4_I_I_I_I_I]]
; CHECK-NEXT:    [[SHR8_I_I_I_I_I:%.*]] = lshr i64 [[XOR7_I_I_I_I_I]], 18
; CHECK-NEXT:    [[XOR9_I_I_I_I_I:%.*]] = xor i64 [[SHR8_I_I_I_I_I]], [[XOR7_I_I_I_I_I]]
; CHECK-NEXT:    [[CONV8_I_I:%.*]] = uitofp i64 [[SUB_PTR_DIV_I43_I_I]] to float
; CHECK-NEXT:    [[MUL_I_I_I:%.*]] = fmul fast float [[CONV8_I_I]], 0x3DF0000000000000
; CHECK-NEXT:    [[CONV13_I_I_I_I:%.*]] = uitofp i64 [[XOR9_I_I_I_I_I]] to float
; CHECK-NEXT:    [[MUL10_I_I:%.*]] = fmul fast float [[MUL_I_I_I]], [[CONV13_I_I_I_I]]
; CHECK-NEXT:    [[CONV11_I_I:%.*]] = fptosi float [[MUL10_I_I]] to i32
; CHECK-NEXT:    [[CONV12_I_I:%.*]] = sext i32 [[CONV11_I_I]] to i64
; CHECK-NEXT:    [[ADD_PTR_I45_I_I:%.*]] = getelementptr inbounds %"struct.std::pair", ptr [[P32]], i64 [[CONV12_I_I]]
; CHECK-NEXT:    [[SECOND17_I_I:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I45_I_I]], i64 4
; CHECK-NEXT:    [[I65:%.*]] = load i32, ptr [[ADD_PTR_I45_I_I]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[I66:%.*]] = load i32, ptr [[SECOND17_I_I]], align 4, !tbaa [[TBAA9]]
; CHECK-NEXT:    [[SUB17_I:%.*]] = add nsw i32 [[I66]], -3
; CHECK-NEXT:    [[P68:%.*]] = load ptr, ptr [[DATA__I_I202]], align 8, !tbaa [[TBAA12:![0-9]+]]
; CHECK-NEXT:    [[I69:%.*]] = load i32, ptr [[STRIDE__I_I203]], align 8, !tbaa [[TBAA14:![0-9]+]]
; CHECK-NEXT:    [[I70:%.*]] = load i32, ptr [[CHANNELS__I_I205]], align 8, !tbaa [[TBAA15:![0-9]+]]
; CHECK-NEXT:    [[IDX_EXT_I:%.*]] = sext i32 [[I69]] to i64
; CHECK-NEXT:    [[SUB10_I:%.*]] = add nsw i32 [[I65]], -3
; CHECK-NEXT:    [[MUL_I71_I:%.*]] = mul nsw i32 [[I69]], [[SUB17_I]]
; CHECK-NEXT:    [[MUL2_I73_I:%.*]] = mul nsw i32 [[I70]], [[SUB10_I]]
; CHECK-NEXT:    [[ADD_I74_I:%.*]] = add nsw i32 [[MUL2_I73_I]], [[MUL_I71_I]]
; CHECK-NEXT:    [[IDXPROM_I75_I:%.*]] = sext i32 [[ADD_I74_I]] to i64
; CHECK-NEXT:    [[ARRAYIDX_I76_I:%.*]] = getelementptr inbounds float, ptr [[P68]], i64 [[IDXPROM_I75_I]]
; CHECK-NEXT:    [[SUB3_I:%.*]] = add nsw i32 [[I35]], -3
; CHECK-NEXT:    [[MUL_I_I204:%.*]] = mul nsw i32 [[I69]], [[SUB3_I]]
; CHECK-NEXT:    [[MUL2_I_I206:%.*]] = mul nsw i32 [[I70]], [[SUB_I]]
; CHECK-NEXT:    [[ADD_I_I207:%.*]] = add nsw i32 [[MUL2_I_I206]], [[MUL_I_I204]]
; CHECK-NEXT:    [[IDXPROM_I_I208:%.*]] = sext i32 [[ADD_I_I207]] to i64
; CHECK-NEXT:    [[ARRAYIDX_I_I209:%.*]] = getelementptr inbounds float, ptr [[P68]], i64 [[IDXPROM_I_I208]]
; CHECK-NEXT:    br label [[FOR_COND29_PREHEADER_I:%.*]]
; CHECK:       for.cond29.preheader.i:
; CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[ARRAYIDX_I_I209]], align 4, !tbaa [[TBAA16:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[ARRAYIDX_I76_I]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP2:%.*]] = fsub fast <16 x float> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = fmul fast <16 x float> [[TMP2]], [[TMP2]]
; CHECK-NEXT:    [[ARRAYIDX_16_I:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_I_I209]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_I76_I]], i64 64
; CHECK-NEXT:    [[TMP4:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP14:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP24:%.*]] = fsub fast <4 x float> [[TMP4]], [[TMP14]]
; CHECK-NEXT:    [[TMP34:%.*]] = fmul fast <4 x float> [[TMP24]], [[TMP24]]
; CHECK-NEXT:    [[ARRAYIDX_20_I:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_I_I209]], i64 80
; CHECK-NEXT:    [[F111:%.*]] = load float, ptr [[ARRAYIDX_20_I]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX_I76_I]], i64 80
; CHECK-NEXT:    [[F112:%.*]] = load float, ptr [[ARRAYIDX34_20_I]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I:%.*]] = fsub fast float [[F111]], [[F112]]
; CHECK-NEXT:    [[MUL_20_I:%.*]] = fmul fast float [[SUB35_20_I]], [[SUB35_20_I]]
; CHECK-NEXT:    [[ADD_PTR_I223:%.*]] = getelementptr inbounds float, ptr [[ARRAYIDX_I_I209]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR40_I:%.*]] = getelementptr inbounds float, ptr [[ARRAYIDX_I76_I]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP35:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP3]], i64 0)
; CHECK-NEXT:    [[RDX_OP:%.*]] = fadd fast <4 x float> [[TMP35]], [[TMP34]]
; CHECK-NEXT:    [[TMP9:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP3]], <4 x float> [[RDX_OP]], i64 0)
; CHECK-NEXT:    [[MUL_19_I:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP9]])
; CHECK-NEXT:    [[OP_RDX2:%.*]] = fadd fast float [[MUL_19_I]], [[MUL_20_I]]
; CHECK-NEXT:    [[TMP5:%.*]] = load <16 x float>, ptr [[ADD_PTR_I223]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP6:%.*]] = load <16 x float>, ptr [[ADD_PTR40_I]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP7:%.*]] = fsub fast <16 x float> [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = fmul fast <16 x float> [[TMP7]], [[TMP7]]
; CHECK-NEXT:    [[ARRAYIDX_16_I_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I]], i64 64
; CHECK-NEXT:    [[TMP36:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP43:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP44:%.*]] = fsub fast <4 x float> [[TMP36]], [[TMP43]]
; CHECK-NEXT:    [[TMP45:%.*]] = fmul fast <4 x float> [[TMP44]], [[TMP44]]
; CHECK-NEXT:    [[ARRAYIDX_20_I_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223]], i64 80
; CHECK-NEXT:    [[F111_1:%.*]] = load float, ptr [[ARRAYIDX_20_I_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I]], i64 80
; CHECK-NEXT:    [[F112_1:%.*]] = load float, ptr [[ARRAYIDX34_20_I_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I_1:%.*]] = fsub fast float [[F111_1]], [[F112_1]]
; CHECK-NEXT:    [[MUL_20_I_1:%.*]] = fmul fast float [[SUB35_20_I_1]], [[SUB35_20_I_1]]
; CHECK-NEXT:    [[ADD_PTR_I223_1:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR_I223]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR40_I_1:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR40_I]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP19:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP8]], i64 0)
; CHECK-NEXT:    [[RDX_OP_1:%.*]] = fadd fast <4 x float> [[TMP19]], [[TMP45]]
; CHECK-NEXT:    [[TMP46:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP8]], <4 x float> [[RDX_OP_1]], i64 0)
; CHECK-NEXT:    [[MUL_19_I_1:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP46]])
; CHECK-NEXT:    [[OP_RDX2_1:%.*]] = fadd fast float [[MUL_19_I_1]], [[MUL_20_I_1]]
; CHECK-NEXT:    [[OP_RDX5_1:%.*]] = fadd fast float [[OP_RDX2_1]], [[OP_RDX2]]
; CHECK-NEXT:    [[TMP10:%.*]] = load <16 x float>, ptr [[ADD_PTR_I223_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP11:%.*]] = load <16 x float>, ptr [[ADD_PTR40_I_1]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP12:%.*]] = fsub fast <16 x float> [[TMP10]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = fmul fast <16 x float> [[TMP12]], [[TMP12]]
; CHECK-NEXT:    [[ARRAYIDX_16_I_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_1]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_1]], i64 64
; CHECK-NEXT:    [[TMP47:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP54:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP55:%.*]] = fsub fast <4 x float> [[TMP47]], [[TMP54]]
; CHECK-NEXT:    [[TMP29:%.*]] = fmul fast <4 x float> [[TMP55]], [[TMP55]]
; CHECK-NEXT:    [[ARRAYIDX_20_I_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_1]], i64 80
; CHECK-NEXT:    [[F111_2:%.*]] = load float, ptr [[ARRAYIDX_20_I_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I_2:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_1]], i64 80
; CHECK-NEXT:    [[F112_2:%.*]] = load float, ptr [[ARRAYIDX34_20_I_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I_2:%.*]] = fsub fast float [[F111_2]], [[F112_2]]
; CHECK-NEXT:    [[MUL_20_I_2:%.*]] = fmul fast float [[SUB35_20_I_2]], [[SUB35_20_I_2]]
; CHECK-NEXT:    [[ADD_PTR_I223_2:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR_I223_1]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR40_I_2:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR40_I_1]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP56:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP13]], i64 0)
; CHECK-NEXT:    [[RDX_OP_2:%.*]] = fadd fast <4 x float> [[TMP56]], [[TMP29]]
; CHECK-NEXT:    [[TMP57:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP13]], <4 x float> [[RDX_OP_2]], i64 0)
; CHECK-NEXT:    [[MUL_19_I_2:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP57]])
; CHECK-NEXT:    [[OP_RDX2_2:%.*]] = fadd fast float [[MUL_19_I_2]], [[MUL_20_I_2]]
; CHECK-NEXT:    [[OP_RDX4_2:%.*]] = fadd fast float [[OP_RDX2_2]], [[OP_RDX5_1]]
; CHECK-NEXT:    [[TMP15:%.*]] = load <16 x float>, ptr [[ADD_PTR_I223_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP16:%.*]] = load <16 x float>, ptr [[ADD_PTR40_I_2]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP17:%.*]] = fsub fast <16 x float> [[TMP15]], [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = fmul fast <16 x float> [[TMP17]], [[TMP17]]
; CHECK-NEXT:    [[ARRAYIDX_16_I_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_2]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_2]], i64 64
; CHECK-NEXT:    [[TMP37:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I_3]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP38:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I_3]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP39:%.*]] = fsub fast <4 x float> [[TMP37]], [[TMP38]]
; CHECK-NEXT:    [[TMP40:%.*]] = fmul fast <4 x float> [[TMP39]], [[TMP39]]
; CHECK-NEXT:    [[ARRAYIDX_20_I_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_2]], i64 80
; CHECK-NEXT:    [[F111_3:%.*]] = load float, ptr [[ARRAYIDX_20_I_3]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I_3:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_2]], i64 80
; CHECK-NEXT:    [[F112_3:%.*]] = load float, ptr [[ARRAYIDX34_20_I_3]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I_3:%.*]] = fsub fast float [[F111_3]], [[F112_3]]
; CHECK-NEXT:    [[MUL_20_I_3:%.*]] = fmul fast float [[SUB35_20_I_3]], [[SUB35_20_I_3]]
; CHECK-NEXT:    [[ADD_PTR_I223_3:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR_I223_2]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR40_I_3:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR40_I_2]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP41:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP18]], i64 0)
; CHECK-NEXT:    [[RDX_OP_3:%.*]] = fadd fast <4 x float> [[TMP41]], [[TMP40]]
; CHECK-NEXT:    [[TMP42:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP18]], <4 x float> [[RDX_OP_3]], i64 0)
; CHECK-NEXT:    [[MUL_19_I_3:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP42]])
; CHECK-NEXT:    [[OP_RDX2_3:%.*]] = fadd fast float [[MUL_19_I_3]], [[MUL_20_I_3]]
; CHECK-NEXT:    [[OP_RDX5_3:%.*]] = fadd fast float [[OP_RDX2_3]], [[OP_RDX4_2]]
; CHECK-NEXT:    [[TMP20:%.*]] = load <16 x float>, ptr [[ADD_PTR_I223_3]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP21:%.*]] = load <16 x float>, ptr [[ADD_PTR40_I_3]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP22:%.*]] = fsub fast <16 x float> [[TMP20]], [[TMP21]]
; CHECK-NEXT:    [[TMP23:%.*]] = fmul fast <16 x float> [[TMP22]], [[TMP22]]
; CHECK-NEXT:    [[ARRAYIDX_16_I_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_3]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_3]], i64 64
; CHECK-NEXT:    [[TMP48:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I_4]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP49:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I_4]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP50:%.*]] = fsub fast <4 x float> [[TMP48]], [[TMP49]]
; CHECK-NEXT:    [[TMP51:%.*]] = fmul fast <4 x float> [[TMP50]], [[TMP50]]
; CHECK-NEXT:    [[ARRAYIDX_20_I_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_3]], i64 80
; CHECK-NEXT:    [[F111_4:%.*]] = load float, ptr [[ARRAYIDX_20_I_4]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I_4:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_3]], i64 80
; CHECK-NEXT:    [[F112_4:%.*]] = load float, ptr [[ARRAYIDX34_20_I_4]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I_4:%.*]] = fsub fast float [[F111_4]], [[F112_4]]
; CHECK-NEXT:    [[MUL_20_I_4:%.*]] = fmul fast float [[SUB35_20_I_4]], [[SUB35_20_I_4]]
; CHECK-NEXT:    [[ADD_PTR_I223_4:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR_I223_3]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR40_I_4:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR40_I_3]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP52:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP23]], i64 0)
; CHECK-NEXT:    [[RDX_OP_4:%.*]] = fadd fast <4 x float> [[TMP52]], [[TMP51]]
; CHECK-NEXT:    [[TMP53:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP23]], <4 x float> [[RDX_OP_4]], i64 0)
; CHECK-NEXT:    [[MUL_19_I_4:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP53]])
; CHECK-NEXT:    [[OP_RDX2_4:%.*]] = fadd fast float [[MUL_19_I_4]], [[MUL_20_I_4]]
; CHECK-NEXT:    [[OP_RDX4_4:%.*]] = fadd fast float [[OP_RDX2_4]], [[OP_RDX5_3]]
; CHECK-NEXT:    [[TMP25:%.*]] = load <16 x float>, ptr [[ADD_PTR_I223_4]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP26:%.*]] = load <16 x float>, ptr [[ADD_PTR40_I_4]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP27:%.*]] = fsub fast <16 x float> [[TMP25]], [[TMP26]]
; CHECK-NEXT:    [[TMP28:%.*]] = fmul fast <16 x float> [[TMP27]], [[TMP27]]
; CHECK-NEXT:    [[ARRAYIDX_16_I_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_4]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_4]], i64 64
; CHECK-NEXT:    [[TMP59:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I_5]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP60:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I_5]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP61:%.*]] = fsub fast <4 x float> [[TMP59]], [[TMP60]]
; CHECK-NEXT:    [[TMP62:%.*]] = fmul fast <4 x float> [[TMP61]], [[TMP61]]
; CHECK-NEXT:    [[ARRAYIDX_20_I_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_4]], i64 80
; CHECK-NEXT:    [[F111_5:%.*]] = load float, ptr [[ARRAYIDX_20_I_5]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I_5:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_4]], i64 80
; CHECK-NEXT:    [[F112_5:%.*]] = load float, ptr [[ARRAYIDX34_20_I_5]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I_5:%.*]] = fsub fast float [[F111_5]], [[F112_5]]
; CHECK-NEXT:    [[MUL_20_I_5:%.*]] = fmul fast float [[SUB35_20_I_5]], [[SUB35_20_I_5]]
; CHECK-NEXT:    [[ADD_PTR_I223_5:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR_I223_4]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR40_I_5:%.*]] = getelementptr inbounds float, ptr [[ADD_PTR40_I_4]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[TMP63:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP28]], i64 0)
; CHECK-NEXT:    [[RDX_OP_5:%.*]] = fadd fast <4 x float> [[TMP63]], [[TMP62]]
; CHECK-NEXT:    [[TMP64:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP28]], <4 x float> [[RDX_OP_5]], i64 0)
; CHECK-NEXT:    [[MUL_19_I_5:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP64]])
; CHECK-NEXT:    [[OP_RDX2_5:%.*]] = fadd fast float [[MUL_19_I_5]], [[MUL_20_I_5]]
; CHECK-NEXT:    [[OP_RDX4_6:%.*]] = fadd fast float [[OP_RDX2_5]], [[OP_RDX4_4]]
; CHECK-NEXT:    [[TMP30:%.*]] = load <16 x float>, ptr [[ADD_PTR_I223_5]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP31:%.*]] = load <16 x float>, ptr [[ADD_PTR40_I_5]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP32:%.*]] = fsub fast <16 x float> [[TMP30]], [[TMP31]]
; CHECK-NEXT:    [[TMP33:%.*]] = fmul fast <16 x float> [[TMP32]], [[TMP32]]
; CHECK-NEXT:    [[ARRAYIDX_16_I_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_5]], i64 64
; CHECK-NEXT:    [[ARRAYIDX34_16_I_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_5]], i64 64
; CHECK-NEXT:    [[TMP70:%.*]] = load <4 x float>, ptr [[ARRAYIDX_16_I_6]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP71:%.*]] = load <4 x float>, ptr [[ARRAYIDX34_16_I_6]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP72:%.*]] = fsub fast <4 x float> [[TMP70]], [[TMP71]]
; CHECK-NEXT:    [[TMP73:%.*]] = fmul fast <4 x float> [[TMP72]], [[TMP72]]
; CHECK-NEXT:    [[ARRAYIDX_20_I_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR_I223_5]], i64 80
; CHECK-NEXT:    [[F111_6:%.*]] = load float, ptr [[ARRAYIDX_20_I_6]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[ARRAYIDX34_20_I_6:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR40_I_5]], i64 80
; CHECK-NEXT:    [[F112_6:%.*]] = load float, ptr [[ARRAYIDX34_20_I_6]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[SUB35_20_I_6:%.*]] = fsub fast float [[F111_6]], [[F112_6]]
; CHECK-NEXT:    [[MUL_20_I_6:%.*]] = fmul fast float [[SUB35_20_I_6]], [[SUB35_20_I_6]]
; CHECK-NEXT:    [[TMP74:%.*]] = call fast <4 x float> @llvm.vector.extract.v4f32.v16f32(<16 x float> [[TMP33]], i64 0)
; CHECK-NEXT:    [[RDX_OP_6:%.*]] = fadd fast <4 x float> [[TMP74]], [[TMP73]]
; CHECK-NEXT:    [[TMP75:%.*]] = call fast <16 x float> @llvm.vector.insert.v16f32.v4f32(<16 x float> [[TMP33]], <4 x float> [[RDX_OP_6]], i64 0)
; CHECK-NEXT:    [[TMP76:%.*]] = call fast float @llvm.vector.reduce.fadd.v16f32(float 0.000000e+00, <16 x float> [[TMP75]])
; CHECK-NEXT:    [[OP_RDX3_6:%.*]] = fadd fast float [[TMP76]], [[MUL_20_I_6]]
; CHECK-NEXT:    [[OP_RDX5_6:%.*]] = fadd fast float [[OP_RDX3_6]], [[OP_RDX4_6]]
; CHECK-NEXT:    ret float [[OP_RDX5_6]]
;
entry:
  %generator.i.i = alloca %"class.std::mersenne_twister_engine", align 8
  %src_mask = alloca %class.ImageMask, align 8
  %trg_mask = alloca %class.ImageMask, align 8
  %coords1.i = getelementptr inbounds i8, ptr %trg_mask, i64 32
  %stride_.i.i203 = getelementptr inbounds i8, ptr %output, i64 16
  %data_.i.i202 = getelementptr inbounds i8, ptr %output, i64 24
  %channels_.i.i205 = getelementptr inbounds i8, ptr %output, i64 8
  %_M_finish.i39.i.i = getelementptr inbounds i8, ptr %trg_mask, i64 40
  %p31 = load ptr, ptr %_M_finish.i39.i.i, align 8, !tbaa !227
  %p32 = load ptr, ptr %coords1.i, align 8, !tbaa !107
  %sub.ptr.lhs.cast.i40.i.i = ptrtoint ptr %p31 to i64
  %sub.ptr.rhs.cast.i41.i.i = ptrtoint ptr %p32 to i64
  %sub.ptr.sub.i42.i.i = sub i64 %sub.ptr.lhs.cast.i40.i.i, %sub.ptr.rhs.cast.i41.i.i
  %sub.ptr.div.i43.i.i = ashr exact i64 %sub.ptr.sub.i42.i.i, 3
  %coords.i = getelementptr inbounds i8, ptr %src_mask, i64 32
  %_M_finish.i.i.i = getelementptr inbounds i8, ptr %src_mask, i64 40
  %p28 = load ptr, ptr %_M_finish.i.i.i, align 8
  %p29 = load ptr, ptr %coords.i, align 8
  %add.ptr.i.i.i = getelementptr inbounds %"struct.std::pair", ptr %p29, i64 0
  %i34 = load i32, ptr %add.ptr.i.i.i, align 4, !tbaa !305
  %second.i.i = getelementptr inbounds i8, ptr %add.ptr.i.i.i, i64 4
  %i35 = load i32, ptr %second.i.i, align 4, !tbaa !308
  %sub.i = add nsw i32 %i34, -3
  %arrayidx.i.i.i.i.i = getelementptr inbounds [624 x i64], ptr %generator.i.i, i64 0, i64 0
  %i64 = load i64, ptr %arrayidx.i.i.i.i.i, align 8, !tbaa !266
  %shr.i.i.i.i.i = lshr i64 %i64, 11
  %and.i.i.i.i.i = and i64 %shr.i.i.i.i.i, 4294967295
  %xor.i.i.i.i.i = xor i64 %and.i.i.i.i.i, %i64
  %shl.i.i.i.i.i = shl i64 %xor.i.i.i.i.i, 7
  %and3.i.i.i.i.i = and i64 %shl.i.i.i.i.i, 2636928640
  %xor4.i.i.i.i.i = xor i64 %and3.i.i.i.i.i, %xor.i.i.i.i.i
  %shl5.i.i.i.i.i = shl i64 %xor4.i.i.i.i.i, 15
  %and6.i.i.i.i.i = and i64 %shl5.i.i.i.i.i, 4022730752
  %xor7.i.i.i.i.i = xor i64 %and6.i.i.i.i.i, %xor4.i.i.i.i.i
  %shr8.i.i.i.i.i = lshr i64 %xor7.i.i.i.i.i, 18
  %xor9.i.i.i.i.i = xor i64 %shr8.i.i.i.i.i, %xor7.i.i.i.i.i
  %conv8.i.i = uitofp i64 %sub.ptr.div.i43.i.i to float
  %mul.i.i.i = fmul fast float %conv8.i.i, 0x3DF0000000000000
  %conv13.i.i.i.i = uitofp i64 %xor9.i.i.i.i.i to float
  %mul10.i.i = fmul fast float %mul.i.i.i, %conv13.i.i.i.i
  %conv11.i.i = fptosi float %mul10.i.i to i32
  %conv12.i.i = sext i32 %conv11.i.i to i64
  %add.ptr.i45.i.i = getelementptr inbounds %"struct.std::pair", ptr %p32, i64 %conv12.i.i
  %second17.i.i = getelementptr inbounds i8, ptr %add.ptr.i45.i.i, i64 4
  %i65 = load i32, ptr %add.ptr.i45.i.i, align 4, !tbaa !305
  %i66 = load i32, ptr %second17.i.i, align 4, !tbaa !308
  %sub17.i = add nsw i32 %i66, -3
  %p68 = load ptr, ptr %data_.i.i202, align 8, !tbaa !156
  %i69 = load i32, ptr %stride_.i.i203, align 8, !tbaa !152
  %i70 = load i32, ptr %channels_.i.i205, align 8, !tbaa !142
  %idx.ext.i = sext i32 %i69 to i64
  %sub10.i = add nsw i32 %i65, -3
  %mul.i71.i = mul nsw i32 %i69, %sub17.i
  %mul2.i73.i = mul nsw i32 %i70, %sub10.i
  %add.i74.i = add nsw i32 %mul2.i73.i, %mul.i71.i
  %idxprom.i75.i = sext i32 %add.i74.i to i64
  %arrayidx.i76.i = getelementptr inbounds float, ptr %p68, i64 %idxprom.i75.i
  %sub3.i = add nsw i32 %i35, -3
  %mul.i.i204 = mul nsw i32 %i69, %sub3.i
  %mul2.i.i206 = mul nsw i32 %i70, %sub.i
  %add.i.i207 = add nsw i32 %mul2.i.i206, %mul.i.i204
  %idxprom.i.i208 = sext i32 %add.i.i207 to i64
  %arrayidx.i.i209 = getelementptr inbounds float, ptr %p68, i64 %idxprom.i.i208
  br label %for.cond29.preheader.i

for.cond29.preheader.i:                           ; preds = %for.cond29.preheader.i, %entry
  %distance_sum.084.i = phi float [ 0.000000e+00, %entry ], [ %add41.i, %for.cond29.preheader.i ]
  %y.083.i = phi i32 [ 0, %entry ], [ %inc43.i, %for.cond29.preheader.i ]
  %row_img2.082.i = phi ptr [ %arrayidx.i76.i, %entry ], [ %add.ptr40.i, %for.cond29.preheader.i ]
  %row_img1.081.i = phi ptr [ %arrayidx.i.i209, %entry ], [ %add.ptr.i223, %for.cond29.preheader.i ]
  %f71 = load float, ptr %row_img1.081.i, align 4, !tbaa !413
  %f72 = load float, ptr %row_img2.082.i, align 4, !tbaa !413
  %sub35.i = fsub fast float %f71, %f72
  %mul.i210 = fmul fast float %sub35.i, %sub35.i
  %arrayidx.1.i211 = getelementptr inbounds i8, ptr %row_img1.081.i, i64 4
  %f73 = load float, ptr %arrayidx.1.i211, align 4, !tbaa !413
  %arrayidx34.1.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 4
  %f74 = load float, ptr %arrayidx34.1.i, align 4, !tbaa !413
  %sub35.1.i = fsub fast float %f73, %f74
  %mul.1.i212 = fmul fast float %sub35.1.i, %sub35.1.i
  %arrayidx.2.i213 = getelementptr inbounds i8, ptr %row_img1.081.i, i64 8
  %f75 = load float, ptr %arrayidx.2.i213, align 4, !tbaa !413
  %arrayidx34.2.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 8
  %f76 = load float, ptr %arrayidx34.2.i, align 4, !tbaa !413
  %sub35.2.i = fsub fast float %f75, %f76
  %mul.2.i214 = fmul fast float %sub35.2.i, %sub35.2.i
  %arrayidx.3.i215 = getelementptr inbounds i8, ptr %row_img1.081.i, i64 12
  %f77 = load float, ptr %arrayidx.3.i215, align 4, !tbaa !413
  %arrayidx34.3.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 12
  %f78 = load float, ptr %arrayidx34.3.i, align 4, !tbaa !413
  %sub35.3.i = fsub fast float %f77, %f78
  %mul.3.i216 = fmul fast float %sub35.3.i, %sub35.3.i
  %arrayidx.4.i217 = getelementptr inbounds i8, ptr %row_img1.081.i, i64 16
  %f79 = load float, ptr %arrayidx.4.i217, align 4, !tbaa !413
  %arrayidx34.4.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 16
  %f80 = load float, ptr %arrayidx34.4.i, align 4, !tbaa !413
  %sub35.4.i = fsub fast float %f79, %f80
  %mul.4.i218 = fmul fast float %sub35.4.i, %sub35.4.i
  %arrayidx.5.i219 = getelementptr inbounds i8, ptr %row_img1.081.i, i64 20
  %f81 = load float, ptr %arrayidx.5.i219, align 4, !tbaa !413
  %arrayidx34.5.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 20
  %f82 = load float, ptr %arrayidx34.5.i, align 4, !tbaa !413
  %sub35.5.i = fsub fast float %f81, %f82
  %mul.5.i220 = fmul fast float %sub35.5.i, %sub35.5.i
  %arrayidx.6.i221 = getelementptr inbounds i8, ptr %row_img1.081.i, i64 24
  %f83 = load float, ptr %arrayidx.6.i221, align 4, !tbaa !413
  %arrayidx34.6.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 24
  %f84 = load float, ptr %arrayidx34.6.i, align 4, !tbaa !413
  %sub35.6.i = fsub fast float %f83, %f84
  %mul.6.i222 = fmul fast float %sub35.6.i, %sub35.6.i
  %arrayidx.7.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 28
  %f85 = load float, ptr %arrayidx.7.i, align 4, !tbaa !413
  %arrayidx34.7.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 28
  %f86 = load float, ptr %arrayidx34.7.i, align 4, !tbaa !413
  %sub35.7.i = fsub fast float %f85, %f86
  %mul.7.i = fmul fast float %sub35.7.i, %sub35.7.i
  %arrayidx.8.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 32
  %f87 = load float, ptr %arrayidx.8.i, align 4, !tbaa !413
  %arrayidx34.8.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 32
  %f88 = load float, ptr %arrayidx34.8.i, align 4, !tbaa !413
  %sub35.8.i = fsub fast float %f87, %f88
  %mul.8.i = fmul fast float %sub35.8.i, %sub35.8.i
  %arrayidx.9.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 36
  %f89 = load float, ptr %arrayidx.9.i, align 4, !tbaa !413
  %arrayidx34.9.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 36
  %f90 = load float, ptr %arrayidx34.9.i, align 4, !tbaa !413
  %sub35.9.i = fsub fast float %f89, %f90
  %mul.9.i = fmul fast float %sub35.9.i, %sub35.9.i
  %arrayidx.10.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 40
  %f91 = load float, ptr %arrayidx.10.i, align 4, !tbaa !413
  %arrayidx34.10.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 40
  %f92 = load float, ptr %arrayidx34.10.i, align 4, !tbaa !413
  %sub35.10.i = fsub fast float %f91, %f92
  %mul.10.i = fmul fast float %sub35.10.i, %sub35.10.i
  %arrayidx.11.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 44
  %f93 = load float, ptr %arrayidx.11.i, align 4, !tbaa !413
  %arrayidx34.11.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 44
  %f94 = load float, ptr %arrayidx34.11.i, align 4, !tbaa !413
  %sub35.11.i = fsub fast float %f93, %f94
  %mul.11.i = fmul fast float %sub35.11.i, %sub35.11.i
  %arrayidx.12.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 48
  %f95 = load float, ptr %arrayidx.12.i, align 4, !tbaa !413
  %arrayidx34.12.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 48
  %f96 = load float, ptr %arrayidx34.12.i, align 4, !tbaa !413
  %sub35.12.i = fsub fast float %f95, %f96
  %mul.12.i = fmul fast float %sub35.12.i, %sub35.12.i
  %arrayidx.13.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 52
  %f97 = load float, ptr %arrayidx.13.i, align 4, !tbaa !413
  %arrayidx34.13.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 52
  %f98 = load float, ptr %arrayidx34.13.i, align 4, !tbaa !413
  %sub35.13.i = fsub fast float %f97, %f98
  %mul.13.i = fmul fast float %sub35.13.i, %sub35.13.i
  %arrayidx.14.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 56
  %f99 = load float, ptr %arrayidx.14.i, align 4, !tbaa !413
  %arrayidx34.14.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 56
  %f100 = load float, ptr %arrayidx34.14.i, align 4, !tbaa !413
  %sub35.14.i = fsub fast float %f99, %f100
  %mul.14.i = fmul fast float %sub35.14.i, %sub35.14.i
  %arrayidx.15.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 60
  %f101 = load float, ptr %arrayidx.15.i, align 4, !tbaa !413
  %arrayidx34.15.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 60
  %f102 = load float, ptr %arrayidx34.15.i, align 4, !tbaa !413
  %sub35.15.i = fsub fast float %f101, %f102
  %mul.15.i = fmul fast float %sub35.15.i, %sub35.15.i
  %arrayidx.16.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 64
  %f103 = load float, ptr %arrayidx.16.i, align 4, !tbaa !413
  %arrayidx34.16.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 64
  %f104 = load float, ptr %arrayidx34.16.i, align 4, !tbaa !413
  %sub35.16.i = fsub fast float %f103, %f104
  %mul.16.i = fmul fast float %sub35.16.i, %sub35.16.i
  %arrayidx.17.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 68
  %f105 = load float, ptr %arrayidx.17.i, align 4, !tbaa !413
  %arrayidx34.17.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 68
  %f106 = load float, ptr %arrayidx34.17.i, align 4, !tbaa !413
  %sub35.17.i = fsub fast float %f105, %f106
  %mul.17.i = fmul fast float %sub35.17.i, %sub35.17.i
  %arrayidx.18.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 72
  %f107 = load float, ptr %arrayidx.18.i, align 4, !tbaa !413
  %arrayidx34.18.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 72
  %f108 = load float, ptr %arrayidx34.18.i, align 4, !tbaa !413
  %sub35.18.i = fsub fast float %f107, %f108
  %mul.18.i = fmul fast float %sub35.18.i, %sub35.18.i
  %arrayidx.19.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 76
  %f109 = load float, ptr %arrayidx.19.i, align 4, !tbaa !413
  %arrayidx34.19.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 76
  %f110 = load float, ptr %arrayidx34.19.i, align 4, !tbaa !413
  %sub35.19.i = fsub fast float %f109, %f110
  %mul.19.i = fmul fast float %sub35.19.i, %sub35.19.i
  %arrayidx.20.i = getelementptr inbounds i8, ptr %row_img1.081.i, i64 80
  %f111 = load float, ptr %arrayidx.20.i, align 4, !tbaa !413
  %arrayidx34.20.i = getelementptr inbounds i8, ptr %row_img2.082.i, i64 80
  %f112 = load float, ptr %arrayidx34.20.i, align 4, !tbaa !413
  %sub35.20.i = fsub fast float %f111, %f112
  %mul.20.i = fmul fast float %sub35.20.i, %sub35.20.i
  %add.ptr.i223 = getelementptr inbounds float, ptr %row_img1.081.i, i64 %idx.ext.i
  %add.ptr40.i = getelementptr inbounds float, ptr %row_img2.082.i, i64 %idx.ext.i
  %add36.1.i = fadd fast float %mul.i210, %distance_sum.084.i
  %add36.2.i = fadd fast float %add36.1.i, %mul.1.i212
  %add36.3.i = fadd fast float %add36.2.i, %mul.2.i214
  %add36.4.i = fadd fast float %add36.3.i, %mul.3.i216
  %add36.5.i = fadd fast float %add36.4.i, %mul.4.i218
  %add36.6.i = fadd fast float %add36.5.i, %mul.5.i220
  %add36.7.i = fadd fast float %add36.6.i, %mul.6.i222
  %add36.8.i = fadd fast float %add36.7.i, %mul.7.i
  %add36.9.i = fadd fast float %add36.8.i, %mul.8.i
  %add36.10.i = fadd fast float %add36.9.i, %mul.9.i
  %add36.11.i = fadd fast float %add36.10.i, %mul.10.i
  %add36.12.i = fadd fast float %add36.11.i, %mul.11.i
  %add36.13.i = fadd fast float %add36.12.i, %mul.12.i
  %add36.14.i = fadd fast float %add36.13.i, %mul.13.i
  %add36.15.i = fadd fast float %add36.14.i, %mul.14.i
  %add36.16.i = fadd fast float %add36.15.i, %mul.15.i
  %add36.17.i = fadd fast float %add36.16.i, %mul.16.i
  %add36.18.i = fadd fast float %add36.17.i, %mul.17.i
  %add36.19.i = fadd fast float %add36.18.i, %mul.18.i
  %add36.20.i = fadd fast float %add36.19.i, %mul.19.i
  %add41.i = fadd fast float %add36.20.i, %mul.20.i
  %inc43.i = add nuw nsw i32 %y.083.i, 1
  %exitcond.not.i224 = icmp eq i32 %inc43.i, 7
  br i1 %exitcond.not.i224, label %exit, label %for.cond29.preheader.i

exit:
  ret float %add41.i
}

!22 = !{!"int", !23, i64 0}
!23 = !{!"omnipotent char", !24, i64 0}
!24 = !{!"Simple C++ TBAA"}
!25 = !{!"any pointer", !23, i64 0}
!82 = !{!"llvm.loop.mustprogress"}
!107 = !{!108, !25, i64 0}
!108 = !{!"_ZTSNSt12_Vector_baseISt4pairIiiESaIS1_EE17_Vector_impl_dataE", !25, i64 0, !25, i64 8, !25, i64 16}
!131 = !{!132, !22, i64 0}
!132 = !{!"_ZTS5ImageIfE", !22, i64 0, !22, i64 4, !22, i64 8, !22, i64 12, !22, i64 16, !25, i64 24}
!142 = !{!132, !22, i64 8}
!152 = !{!132, !22, i64 16}
!156 = !{!132, !25, i64 24}
!227 = !{!108, !25, i64 8}
!266 = !{!267, !267, i64 0}
!267 = !{!"long", !23, i64 0}
!305 = !{!306, !22, i64 0}
!306 = !{!"_ZTSSt4pairIiiE", !22, i64 0, !22, i64 4}
!308 = !{!306, !22, i64 4}
!388 = !{!"float", !23, i64 0}
!413 = !{!388, !388, i64 0}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META2:![0-9]+]], i64 8}
; CHECK: [[META1]] = !{!"_ZTSNSt12_Vector_baseISt4pairIiiESaIS1_EE17_Vector_impl_dataE", [[META2]], i64 0, [[META2]], i64 8, [[META2]], i64 16}
; CHECK: [[META2]] = !{!"any pointer", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"Simple C++ TBAA"}
; CHECK: [[TBAA5]] = !{[[META1]], [[META2]], i64 0}
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META8:![0-9]+]], i64 0}
; CHECK: [[META7]] = !{!"_ZTSSt4pairIiiE", [[META8]], i64 0, [[META8]], i64 4}
; CHECK: [[META8]] = !{!"int", [[META3]], i64 0}
; CHECK: [[TBAA9]] = !{[[META7]], [[META8]], i64 4}
; CHECK: [[TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
; CHECK: [[META11]] = !{!"long", [[META3]], i64 0}
; CHECK: [[TBAA12]] = !{[[META13:![0-9]+]], [[META2]], i64 24}
; CHECK: [[META13]] = !{!"_ZTS5ImageIfE", [[META8]], i64 0, [[META8]], i64 4, [[META8]], i64 8, [[META8]], i64 12, [[META8]], i64 16, [[META2]], i64 24}
; CHECK: [[TBAA14]] = !{[[META13]], [[META8]], i64 16}
; CHECK: [[TBAA15]] = !{[[META13]], [[META8]], i64 8}
; CHECK: [[TBAA16]] = !{[[META17:![0-9]+]], [[META17]], i64 0}
; CHECK: [[META17]] = !{!"float", [[META3]], i64 0}
;.
