; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mcpu=sifive-x280 -mtriple=riscv64 -passes='default<O2>' -S %s | FileCheck %s

define dso_local <vscale x 16 x i32> @_Z16vunaryop_v_i32m8u15__rvv_int32m8_tm(<vscale x 16 x i32> %vx, i64 noundef %vl) #0 {
; CHECK-LABEL: define dso_local <vscale x 16 x i32> @_Z16vunaryop_v_i32m8u15__rvv_int32m8_tm(
; CHECK-SAME: <vscale x 16 x i32> [[VX:%.*]], i64 noundef [[VL:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 16 x i32> @llvm.riscv.vrsub.nxv16i32.i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[VX]], i32 0, i64 [[VL]])
; CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
;
entry:
  %vx.addr = alloca <vscale x 16 x i32>, align 4
  %vl.addr = alloca i64, align 8
  store <vscale x 16 x i32> %vx, ptr %vx.addr, align 4, !tbaa !9
  store i64 %vl, ptr %vl.addr, align 8, !tbaa !13
  %0 = load <vscale x 16 x i32>, ptr %vx.addr, align 4, !tbaa !9
  %1 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %2 = call <vscale x 16 x i32> @llvm.riscv.vrsub.nxv16i32.i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> %0, i32 0, i64 %1)
  ret <vscale x 16 x i32> %2
}

declare <vscale x 16 x i32> @llvm.riscv.vrsub.nxv16i32.i32.i64(<vscale x 16 x i32>, <vscale x 16 x i32>, i32, i64) #1

define dso_local <vscale x 16 x i1> @_Z23vbinarypred_vv_i32m8_b4u15__rvv_int32m8_tu15__rvv_int32m8_tm(<vscale x 16 x i32> %vx, <vscale x 16 x i32> %vy, i64 noundef %vl) #0 {
; CHECK-LABEL: define dso_local <vscale x 16 x i1> @_Z23vbinarypred_vv_i32m8_b4u15__rvv_int32m8_tu15__rvv_int32m8_tm(
; CHECK-SAME: <vscale x 16 x i32> [[VX:%.*]], <vscale x 16 x i32> [[VY:%.*]], i64 noundef [[VL:%.*]]) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 16 x i1> @llvm.riscv.vmslt.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[VX]], <vscale x 16 x i32> [[VY]], i64 [[VL]])
; CHECK-NEXT:    ret <vscale x 16 x i1> [[TMP0]]
;
entry:
  %vx.addr = alloca <vscale x 16 x i32>, align 4
  %vy.addr = alloca <vscale x 16 x i32>, align 4
  %vl.addr = alloca i64, align 8
  store <vscale x 16 x i32> %vx, ptr %vx.addr, align 4, !tbaa !9
  store <vscale x 16 x i32> %vy, ptr %vy.addr, align 4, !tbaa !9
  store i64 %vl, ptr %vl.addr, align 8, !tbaa !13
  %0 = load <vscale x 16 x i32>, ptr %vx.addr, align 4, !tbaa !9
  %1 = load <vscale x 16 x i32>, ptr %vy.addr, align 4, !tbaa !9
  %2 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %3 = call <vscale x 16 x i1> @llvm.riscv.vmslt.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> %0, <vscale x 16 x i32> %1, i64 %2)
  ret <vscale x 16 x i1> %3
}

define dso_local <vscale x 16 x i1> @_ZN7attempt23vbinarypred_vv_i32m8_b4Eu15__rvv_int32m8_tu15__rvv_int32m8_tm(<vscale x 16 x i32> %vx, <vscale x 16 x i32> %vy, i64 noundef %vl) #2 {
; CHECK-LABEL: define dso_local <vscale x 16 x i1> @_ZN7attempt23vbinarypred_vv_i32m8_b4Eu15__rvv_int32m8_tu15__rvv_int32m8_tm(
; CHECK-SAME: <vscale x 16 x i32> [[VX:%.*]], <vscale x 16 x i32> [[VY:%.*]], i64 noundef [[VL:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[VL]], i64 3, i64 3)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i64 [[TMP0]], 0
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[MUL:%.*]] = shl nuw nsw i64 [[TMP0]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = alloca i8, i64 [[MUL]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = alloca i8, i64 [[MUL]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = alloca i8, i64 [[TMP0]], align 1
; CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i32.i64(<vscale x 16 x i32> [[VX]], ptr nonnull [[TMP1]], i64 [[TMP0]])
; CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i32.i64(<vscale x 16 x i32> [[VY]], ptr nonnull [[TMP2]], i64 [[TMP0]])
; CHECK-NEXT:    [[TMP4:%.*]] = tail call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP5:%.*]] = shl nuw nsw i64 [[TMP4]], 4
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp samesign ult i64 [[TMP0]], [[TMP5]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[FOR_BODY_PREHEADER:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul nsw i64 [[TMP4]], -16
; CHECK-NEXT:    [[N_VEC:%.*]] = and i64 [[TMP0]], [[DOTNEG]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP1]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i32>, ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP2]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD18:%.*]] = load <vscale x 16 x i32>, ptr [[TMP7]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = icmp slt <vscale x 16 x i32> [[WIDE_LOAD]], [[WIDE_LOAD18]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP3]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP10:%.*]] = zext <vscale x 16 x i1> [[TMP8]] to <vscale x 16 x i8>
; CHECK-NEXT:    store <vscale x 16 x i8> [[TMP10]], ptr [[TMP9]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP5]]
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP0]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP:.*]], label %[[FOR_BODY_PREHEADER]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[I_017_PH:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[N_VEC]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[TMP12:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> poison, ptr nonnull [[TMP3]], i64 [[TMP0]])
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = tail call <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP12]], i8 0, i64 [[TMP0]])
; CHECK-NEXT:    ret <vscale x 16 x i1> [[VP_OP_ICMP]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_017:%.*]] = phi i64 [ [[INC:%.*]], %[[FOR_BODY]] ], [ [[I_017_PH]], %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP1]], i64 [[I_017]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA13:![0-9]+]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds nuw i32, ptr [[TMP2]], i64 [[I_017]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA13]]
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp slt i32 [[TMP14]], [[TMP15]]
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP3]], i64 [[I_017]]
; CHECK-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[CMP_I]] to i8
; CHECK-NEXT:    store i8 [[FROMBOOL]], ptr [[ARRAYIDX5]], align 1, !tbaa [[TBAA17:![0-9]+]]
; CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I_017]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INC]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP19:![0-9]+]]
;
entry:
  %vx.addr = alloca <vscale x 16 x i32>, align 4
  %vy.addr = alloca <vscale x 16 x i32>, align 4
  %vl.addr = alloca i64, align 8
  %ax = alloca ptr, align 8
  %ay = alloca ptr, align 8
  %az = alloca ptr, align 8
  %i = alloca i64, align 8
  store <vscale x 16 x i32> %vx, ptr %vx.addr, align 4, !tbaa !9
  store <vscale x 16 x i32> %vy, ptr %vy.addr, align 4, !tbaa !9
  store i64 %vl, ptr %vl.addr, align 8, !tbaa !13
  %0 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 %0, i64 3, i64 3)
  store i64 %1, ptr %vl.addr, align 8, !tbaa !13
  %2 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %cmp = icmp ugt i64 %2, 0
  call void @llvm.assume(i1 %cmp)
  call void @llvm.lifetime.start.p0(i64 8, ptr %ax) #8
  %3 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %mul = mul i64 %3, 4
  %4 = alloca i8, i64 %mul, align 4
  store ptr %4, ptr %ax, align 8, !tbaa !15
  call void @llvm.lifetime.start.p0(i64 8, ptr %ay) #8
  %5 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %mul1 = mul i64 %5, 4
  %6 = alloca i8, i64 %mul1, align 4
  store ptr %6, ptr %ay, align 8, !tbaa !15
  call void @llvm.lifetime.start.p0(i64 8, ptr %az) #8
  %7 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %mul2 = mul i64 %7, 1
  %8 = alloca i8, i64 %mul2, align 1
  store ptr %8, ptr %az, align 8, !tbaa !15
  %9 = load ptr, ptr %ax, align 8, !tbaa !15
  %10 = load <vscale x 16 x i32>, ptr %vx.addr, align 4, !tbaa !9
  %11 = load i64, ptr %vl.addr, align 8, !tbaa !13
  call void @llvm.riscv.vse.nxv16i32.i64(<vscale x 16 x i32> %10, ptr %9, i64 %11)
  %12 = load ptr, ptr %ay, align 8, !tbaa !15
  %13 = load <vscale x 16 x i32>, ptr %vy.addr, align 4, !tbaa !9
  %14 = load i64, ptr %vl.addr, align 8, !tbaa !13
  call void @llvm.riscv.vse.nxv16i32.i64(<vscale x 16 x i32> %13, ptr %12, i64 %14)
  call void @llvm.lifetime.start.p0(i64 8, ptr %i) #8
  store i64 0, ptr %i, align 8, !tbaa !13
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %15 = load i64, ptr %i, align 8, !tbaa !13
  %16 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %cmp3 = icmp ult i64 %15, %16
  br i1 %cmp3, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  call void @llvm.lifetime.end.p0(i64 8, ptr %i) #8
  br label %for.end

for.body:                                         ; preds = %for.cond
  %17 = load ptr, ptr %ax, align 8, !tbaa !15
  %18 = load i64, ptr %i, align 8, !tbaa !13
  %arrayidx = getelementptr inbounds i32, ptr %17, i64 %18
  %19 = load i32, ptr %arrayidx, align 4, !tbaa !17
  %20 = load ptr, ptr %ay, align 8, !tbaa !15
  %21 = load i64, ptr %i, align 8, !tbaa !13
  %arrayidx4 = getelementptr inbounds i32, ptr %20, i64 %21
  %22 = load i32, ptr %arrayidx4, align 4, !tbaa !17
  %call = call noundef zeroext i1 @_ZL10BinaryPredii(i32 noundef signext %19, i32 noundef signext %22)
  %23 = load ptr, ptr %az, align 8, !tbaa !15
  %24 = load i64, ptr %i, align 8, !tbaa !13
  %arrayidx5 = getelementptr inbounds i8, ptr %23, i64 %24
  %frombool = zext i1 %call to i8
  store i8 %frombool, ptr %arrayidx5, align 1, !tbaa !19
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %25 = load i64, ptr %i, align 8, !tbaa !13
  %inc = add i64 %25, 1
  store i64 %inc, ptr %i, align 8, !tbaa !13
  br label %for.cond, !llvm.loop !21

for.end:                                          ; preds = %for.cond.cleanup
  %26 = load ptr, ptr %az, align 8, !tbaa !15
  %27 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %28 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> poison, ptr %26, i64 %27)
  %29 = load i64, ptr %vl.addr, align 8, !tbaa !13
  %30 = call <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8> %28, i8 0, i64 %29)
  call void @llvm.lifetime.end.p0(i64 8, ptr %az) #8
  call void @llvm.lifetime.end.p0(i64 8, ptr %ay) #8
  call void @llvm.lifetime.end.p0(i64 8, ptr %ax) #8
  ret <vscale x 16 x i1> %30
}

; Function Attrs: mustprogress nounwind uwtable vscale_range(8,1024)
define internal noundef zeroext i1 @_ZL10BinaryPredii(i32 noundef signext %x, i32 noundef signext %y) #0 {
entry:
  %x.addr = alloca i32, align 4
  %y.addr = alloca i32, align 4
  store i32 %x, ptr %x.addr, align 4, !tbaa !17
  store i32 %y, ptr %y.addr, align 4, !tbaa !17
  %0 = load i32, ptr %x.addr, align 4, !tbaa !17
  %1 = load i32, ptr %y.addr, align 4, !tbaa !17
  %cmp = icmp slt i32 %0, %1
  ret i1 %cmp
}

attributes #0 = { mustprogress nounwind uwtable vscale_range(8,1024) "approx-func-fp-math"="true" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sifive-x280o" "target-features"="+64bit,+a,+c,+d,+experimental,+experimental-zvfbfmin,+f,+m,+relax,+v,+xsfvfhbfmin,+xsfvfnrclipxfqf,+xsfvfwmaccqqq,+xsfvqmaccqoq,+zba,+zbb,+zfh,+zfhmin,+zicsr,+zifencei,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvfh,+zvfhmin,+zvl128b,+zvl256b,+zvl32b,+zvl512b,+zvl64b,-e,-experimental-smmpm,-experimental-smnpm,-experimental-smrnmi,-experimental-smwg,-experimental-smwgd,-experimental-ssnpm,-experimental-sspm,-experimental-ssqosid,-experimental-sswg,-experimental-supm,-experimental-zabha,-experimental-zalasr,-experimental-zfbfmin,-experimental-zicfilp,-experimental-zicfiss,-experimental-zjid,-experimental-ztso,-experimental-zvfbfwma,-h,-i,-sdext,-sdtrig,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smepmp,-smstateen,-ss,-ssaia,-ssccptr,-sscofpmf,-sscounterenw,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfmm128t,-xsfmm32a,-xsfmm32a8f,-xsfmm32t,-xsfmm64a,-xsfmm64t,-xsfmmbase,-xsfpgflushdlone,-xsfpmpmt,-xsfvcp,-xsfvfexpa,-xsfvfexpa64e,-xsfvqdotq,-xsfvqmaccdod,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-za128rs,-za64rs,-zaamo,-zacas,-zalrsc,-zama16b,-zawrs,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-zvbb,-zvbc,-zvkb,-zvkb0p1,-zvkg,-zvkg0p1,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknha0p1,-zvknhb,-zvknhb0p1,-zvkns,-zvks,-zvksc,-zvksed,-zvksed0p1,-zvksg,-zvksh,-zvksh0p1,-zvkt,-zvl1024b,-zvl16384b,-zvl2048b,-zvl32768b,-zvl4096b,-zvl65536b,-zvl8192b" "unsafe-fp-math"="true" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #2 = { mustprogress uwtable vscale_range(8,1024) "approx-func-fp-math"="true" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="sifive-x280o" "target-features"="+64bit,+a,+c,+d,+experimental,+experimental-zvfbfmin,+f,+m,+relax,+v,+xsfvfhbfmin,+xsfvfnrclipxfqf,+xsfvfwmaccqqq,+xsfvqmaccqoq,+zba,+zbb,+zfh,+zfhmin,+zicsr,+zifencei,+zve32f,+zve32x,+zve64d,+zve64f,+zve64x,+zvfh,+zvfhmin,+zvl128b,+zvl256b,+zvl32b,+zvl512b,+zvl64b,-e,-experimental-smmpm,-experimental-smnpm,-experimental-smrnmi,-experimental-smwg,-experimental-smwgd,-experimental-ssnpm,-experimental-sspm,-experimental-ssqosid,-experimental-sswg,-experimental-supm,-experimental-zabha,-experimental-zalasr,-experimental-zfbfmin,-experimental-zicfilp,-experimental-zicfiss,-experimental-zjid,-experimental-ztso,-experimental-zvfbfwma,-h,-i,-sdext,-sdtrig,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smepmp,-smstateen,-ss,-ssaia,-ssccptr,-sscofpmf,-sscounterenw,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfmm128t,-xsfmm32a,-xsfmm32a8f,-xsfmm32t,-xsfmm64a,-xsfmm64t,-xsfmmbase,-xsfpgflushdlone,-xsfpmpmt,-xsfvcp,-xsfvfexpa,-xsfvfexpa64e,-xsfvqdotq,-xsfvqmaccdod,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-za128rs,-za64rs,-zaamo,-zacas,-zalrsc,-zama16b,-zawrs,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-zvbb,-zvbc,-zvkb,-zvkb0p1,-zvkg,-zvkg0p1,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknha0p1,-zvknhb,-zvknhb0p1,-zvkns,-zvks,-zvksc,-zvksed,-zvksed0p1,-zvksg,-zvksh,-zvksh0p1,-zvkt,-zvl1024b,-zvl16384b,-zvl2048b,-zvl32768b,-zvl4096b,-zvl65536b,-zvl8192b" "unsafe-fp-math"="true" }

!llvm.module.flags = !{!0, !1, !2, !4, !5, !6, !7}
!llvm.ident = !{!8}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"lp64d"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv64i2p1_m2p0_a2p1_f2p2_d2p2_c2p0_v1p0_zicsr2p0_zifencei2p0_zfh1p0_zfhmin1p0_zba1p0_zbb1p0_zve32f1p0_zve32x1p0_zve64d1p0_zve64f1p0_zve64x1p0_zvfbfmin1p0_zvfh1p0_zvfhmin1p0_zvl128b1p0_zvl256b1p0_zvl32b1p0_zvl512b1p0_zvl64b1p0_xsfvfhbfmin0p1_xsfvfnrclipxfqf1p0_xsfvfwmaccqqq1p0_xsfvqmaccqoq1p0"}
!4 = !{i32 8, !"PIC Level", i32 2}
!5 = !{i32 7, !"PIE Level", i32 2}
!6 = !{i32 7, !"uwtable", i32 2}
!7 = !{i32 8, !"SmallDataLimit", i32 8}
!8 = !{!"clang version 18.9.149git (git@github.com:sifive/riscv-llvm-internal.git 9f61d1b3026054c89fcbddf6206768db9bb90fb4)"}
!9 = !{!10, !10, i64 0}
!10 = !{!"__rvv_int32m8_t", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
!13 = !{!14, !14, i64 0}
!14 = !{!"long", !11, i64 0}
!15 = !{!16, !16, i64 0}
!16 = !{!"any pointer", !11, i64 0}
!17 = !{!18, !18, i64 0}
!18 = !{!"int", !11, i64 0}
!19 = !{!20, !20, i64 0}
!20 = !{!"bool", !11, i64 0}
!21 = distinct !{!21, !22, !23, !24, !25}
!22 = !{!"llvm.loop.mustprogress"}
!23 = !{!"llvm.loop.vectorize.lmul_sew", i32 3, i32 32}
!24 = !{!"llvm.loop.vectorize.scalable.enable", i1 true}
!25 = !{!"llvm.loop.vectorize.enable", i1 true}
;.
; CHECK: [[LOOP9]] = distinct !{[[LOOP9]], [[META10:![0-9]+]], [[META11:![0-9]+]], [[META12:![0-9]+]]}
; CHECK: [[META10]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META11]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META12]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[TBAA13]] = !{[[META14:![0-9]+]], [[META14]], i64 0}
; CHECK: [[META14]] = !{!"int", [[META15:![0-9]+]], i64 0}
; CHECK: [[META15]] = !{!"omnipotent char", [[META16:![0-9]+]], i64 0}
; CHECK: [[META16]] = !{!"Simple C++ TBAA"}
; CHECK: [[TBAA17]] = !{[[META18:![0-9]+]], [[META18]], i64 0}
; CHECK: [[META18]] = !{!"bool", [[META15]], i64 0}
; CHECK: [[LOOP19]] = distinct !{[[LOOP19]], [[META10]], [[META12]], [[META11]]}
;.
