; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -S -passes=loop-unroll -unroll-runtime -sifive-unroll-detect-vector-loops=false | FileCheck %s --check-prefix=NODETECT
; RUN: opt < %s -S -passes=loop-unroll -unroll-runtime -sifive-unroll-detect-vector-loops=true | FileCheck %s --check-prefix=DETECT

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-unknown"

; The NODETECT case will succeed and unroll the loop below, the DETECT case will not as
; there are no vector ops present in the loop.

define i32 @test(ptr nocapture %a, i32 %n) nounwind uwtable readonly {
; NODETECT-LABEL: define i32 @test(
; NODETECT-SAME: ptr captures(none) [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; NODETECT-NEXT:  entry:
; NODETECT-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; NODETECT-NEXT:    br i1 [[CMP1]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; NODETECT:       for.body.preheader:
; NODETECT-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; NODETECT-NEXT:    [[XTRAITER:%.*]] = and i32 [[N]], 7
; NODETECT-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[TMP0]], 7
; NODETECT-NEXT:    br i1 [[TMP1]], label [[FOR_END_LOOPEXIT_UNR_LCSSA:%.*]], label [[FOR_BODY_PREHEADER_NEW:%.*]]
; NODETECT:       for.body.preheader.new:
; NODETECT-NEXT:    [[UNROLL_ITER:%.*]] = sub i32 [[N]], [[XTRAITER]]
; NODETECT-NEXT:    br label [[FOR_BODY:%.*]]
; NODETECT:       for.body:
; NODETECT-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER_NEW]] ], [ [[INDVARS_IV_NEXT_7:%.*]], [[FOR_BODY]] ]
; NODETECT-NEXT:    [[SUM_02:%.*]] = phi i32 [ 0, [[FOR_BODY_PREHEADER_NEW]] ], [ [[ADD_7:%.*]], [[FOR_BODY]] ]
; NODETECT-NEXT:    [[NITER:%.*]] = phi i32 [ 0, [[FOR_BODY_PREHEADER_NEW]] ], [ [[NITER_NEXT_7:%.*]], [[FOR_BODY]] ]
; NODETECT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; NODETECT-NEXT:    [[I0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; NODETECT-NEXT:    [[ADD:%.*]] = add nsw i32 [[I0]], [[SUM_02]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 1
; NODETECT-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT]]
; NODETECT-NEXT:    [[I0_1:%.*]] = load i32, ptr [[ARRAYIDX_1]], align 4
; NODETECT-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[I0_1]], [[ADD]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_1:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 2
; NODETECT-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_1]]
; NODETECT-NEXT:    [[I0_2:%.*]] = load i32, ptr [[ARRAYIDX_2]], align 4
; NODETECT-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[I0_2]], [[ADD_1]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_2:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 3
; NODETECT-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_2]]
; NODETECT-NEXT:    [[I0_3:%.*]] = load i32, ptr [[ARRAYIDX_3]], align 4
; NODETECT-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[I0_3]], [[ADD_2]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_3:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 4
; NODETECT-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_3]]
; NODETECT-NEXT:    [[I0_4:%.*]] = load i32, ptr [[ARRAYIDX_4]], align 4
; NODETECT-NEXT:    [[ADD_4:%.*]] = add nsw i32 [[I0_4]], [[ADD_3]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_4:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 5
; NODETECT-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_4]]
; NODETECT-NEXT:    [[I0_5:%.*]] = load i32, ptr [[ARRAYIDX_5]], align 4
; NODETECT-NEXT:    [[ADD_5:%.*]] = add nsw i32 [[I0_5]], [[ADD_4]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_5:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 6
; NODETECT-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_5]]
; NODETECT-NEXT:    [[I0_6:%.*]] = load i32, ptr [[ARRAYIDX_6]], align 4
; NODETECT-NEXT:    [[ADD_6:%.*]] = add nsw i32 [[I0_6]], [[ADD_5]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_6:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 7
; NODETECT-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_NEXT_6]]
; NODETECT-NEXT:    [[I0_7:%.*]] = load i32, ptr [[ARRAYIDX_7]], align 4
; NODETECT-NEXT:    [[ADD_7]] = add nsw i32 [[I0_7]], [[ADD_6]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_7]] = add nuw nsw i64 [[INDVARS_IV]], 8
; NODETECT-NEXT:    [[NITER_NEXT_7]] = add i32 [[NITER]], 8
; NODETECT-NEXT:    [[NITER_NCMP_7:%.*]] = icmp eq i32 [[NITER_NEXT_7]], [[UNROLL_ITER]]
; NODETECT-NEXT:    br i1 [[NITER_NCMP_7]], label [[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT:%.*]], label [[FOR_BODY]]
; NODETECT:       for.end.loopexit.unr-lcssa.loopexit:
; NODETECT-NEXT:    [[ADD_LCSSA_PH_PH:%.*]] = phi i32 [ [[ADD_7]], [[FOR_BODY]] ]
; NODETECT-NEXT:    [[INDVARS_IV_UNR_PH:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_7]], [[FOR_BODY]] ]
; NODETECT-NEXT:    [[SUM_02_UNR_PH:%.*]] = phi i32 [ [[ADD_7]], [[FOR_BODY]] ]
; NODETECT-NEXT:    br label [[FOR_END_LOOPEXIT_UNR_LCSSA]]
; NODETECT:       for.end.loopexit.unr-lcssa:
; NODETECT-NEXT:    [[ADD_LCSSA_PH:%.*]] = phi i32 [ poison, [[FOR_BODY_PREHEADER]] ], [ [[ADD_LCSSA_PH_PH]], [[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]] ]
; NODETECT-NEXT:    [[INDVARS_IV_UNR:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_UNR_PH]], [[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]] ]
; NODETECT-NEXT:    [[SUM_02_UNR:%.*]] = phi i32 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[SUM_02_UNR_PH]], [[FOR_END_LOOPEXIT_UNR_LCSSA_LOOPEXIT]] ]
; NODETECT-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i32 [[XTRAITER]], 0
; NODETECT-NEXT:    br i1 [[LCMP_MOD]], label [[FOR_BODY_EPIL_PREHEADER:%.*]], label [[FOR_END_LOOPEXIT:%.*]]
; NODETECT:       for.body.epil.preheader:
; NODETECT-NEXT:    br label [[FOR_BODY_EPIL:%.*]]
; NODETECT:       for.body.epil:
; NODETECT-NEXT:    [[INDVARS_IV_EPIL:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_EPIL:%.*]], [[FOR_BODY_EPIL]] ], [ [[INDVARS_IV_UNR]], [[FOR_BODY_EPIL_PREHEADER]] ]
; NODETECT-NEXT:    [[SUM_02_EPIL:%.*]] = phi i32 [ [[ADD_EPIL:%.*]], [[FOR_BODY_EPIL]] ], [ [[SUM_02_UNR]], [[FOR_BODY_EPIL_PREHEADER]] ]
; NODETECT-NEXT:    [[EPIL_ITER:%.*]] = phi i32 [ 0, [[FOR_BODY_EPIL_PREHEADER]] ], [ [[EPIL_ITER_NEXT:%.*]], [[FOR_BODY_EPIL]] ]
; NODETECT-NEXT:    [[ARRAYIDX_EPIL:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV_EPIL]]
; NODETECT-NEXT:    [[I0_EPIL:%.*]] = load i32, ptr [[ARRAYIDX_EPIL]], align 4
; NODETECT-NEXT:    [[ADD_EPIL]] = add nsw i32 [[I0_EPIL]], [[SUM_02_EPIL]]
; NODETECT-NEXT:    [[INDVARS_IV_NEXT_EPIL]] = add i64 [[INDVARS_IV_EPIL]], 1
; NODETECT-NEXT:    [[LFTR_WIDEIV_EPIL:%.*]] = trunc i64 [[INDVARS_IV_NEXT_EPIL]] to i32
; NODETECT-NEXT:    [[EXITCOND_EPIL:%.*]] = icmp eq i32 [[LFTR_WIDEIV_EPIL]], [[N]]
; NODETECT-NEXT:    [[EPIL_ITER_NEXT]] = add i32 [[EPIL_ITER]], 1
; NODETECT-NEXT:    [[EPIL_ITER_CMP:%.*]] = icmp ne i32 [[EPIL_ITER_NEXT]], [[XTRAITER]]
; NODETECT-NEXT:    br i1 [[EPIL_ITER_CMP]], label [[FOR_BODY_EPIL]], label [[FOR_END_LOOPEXIT_EPILOG_LCSSA:%.*]], !llvm.loop [[LOOP0:![0-9]+]]
; NODETECT:       for.end.loopexit.epilog-lcssa:
; NODETECT-NEXT:    [[ADD_LCSSA_PH1:%.*]] = phi i32 [ [[ADD_EPIL]], [[FOR_BODY_EPIL]] ]
; NODETECT-NEXT:    br label [[FOR_END_LOOPEXIT]]
; NODETECT:       for.end.loopexit:
; NODETECT-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD_LCSSA_PH]], [[FOR_END_LOOPEXIT_UNR_LCSSA]] ], [ [[ADD_LCSSA_PH1]], [[FOR_END_LOOPEXIT_EPILOG_LCSSA]] ]
; NODETECT-NEXT:    br label [[FOR_END]]
; NODETECT:       for.end:
; NODETECT-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[ADD_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; NODETECT-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
; DETECT-LABEL: define i32 @test(
; DETECT-SAME: ptr captures(none) [[A:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; DETECT-NEXT:  entry:
; DETECT-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[N]], 0
; DETECT-NEXT:    br i1 [[CMP1]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; DETECT:       for.body.preheader:
; DETECT-NEXT:    br label [[FOR_BODY:%.*]]
; DETECT:       for.body:
; DETECT-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; DETECT-NEXT:    [[SUM_02:%.*]] = phi i32 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; DETECT-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; DETECT-NEXT:    [[I0:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; DETECT-NEXT:    [[ADD]] = add nsw i32 [[I0]], [[SUM_02]]
; DETECT-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 1
; DETECT-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; DETECT-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], [[N]]
; DETECT-NEXT:    br i1 [[EXITCOND]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; DETECT:       for.end.loopexit:
; DETECT-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], [[FOR_BODY]] ]
; DETECT-NEXT:    br label [[FOR_END]]
; DETECT:       for.end:
; DETECT-NEXT:    [[SUM_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[ADD_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; DETECT-NEXT:    ret i32 [[SUM_0_LCSSA]]
;
entry:
  %cmp1 = icmp eq i32 %n, 0
  br i1 %cmp1, label %for.end, label %for.body

for.body:                                         ; preds = %for.body, %entry
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body ], [ 0, %entry ]
  %sum.02 = phi i32 [ %add, %for.body ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i32, ptr %a, i64 %indvars.iv
  %i0 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %i0, %sum.02
  %indvars.iv.next = add i64 %indvars.iv, 1
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:                                          ; preds = %for.body, %entry
  %sum.0.lcssa = phi i32 [ 0, %entry ], [ %add, %for.body ]
  ret i32 %sum.0.lcssa
}
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.unroll.disable"}
;.
; NODETECT: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; NODETECT: [[META1]] = !{!"llvm.loop.unroll.disable"}
;.
