; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
;RUN: opt -S -passes=simplifycfg -simplifycfg-require-and-preserve-domtree=1 -mtriple=riscv64 -sink-common-insts  < %s | FileCheck %s
define i32 @test1(i32 zeroext %flag, ptr %base) {
; CHECK-LABEL: define i32 @test1
; CHECK-SAME: (i32 zeroext [[FLAG:%.*]], ptr [[BASE:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i32 [[FLAG]], label [[OTHERWISE:%.*]] [
; CHECK-NEXT:    i32 2, label [[CASE1:%.*]]
; CHECK-NEXT:    i32 7, label [[CASE2:%.*]]
; CHECK-NEXT:    i32 11, label [[IF_END:%.*]]
; CHECK-NEXT:    ]
; CHECK:       otherwise:
; CHECK-NEXT:    [[ADDR0:%.*]] = getelementptr i32, ptr [[BASE]], i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ADDR0]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       case1:
; CHECK-NEXT:    [[ADDR1:%.*]] = getelementptr i32, ptr [[BASE]], i32 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ADDR1]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       case2:
; CHECK-NEXT:    [[ADDR2:%.*]] = getelementptr i32, ptr [[BASE]], i32 3
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ADDR2]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[RES:%.*]] = phi i32 [ [[TMP0]], [[OTHERWISE]] ], [ [[TMP1]], [[CASE1]] ], [ [[TMP2]], [[CASE2]] ], [ 4, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  switch i32 %flag, label %otherwise [ i32 2, label %case1
  i32 7, label %case2
  i32 11, label %if.end]

otherwise:
  %addr0 = getelementptr i32, ptr %base, i32 4
  %0 = load i32, ptr %addr0
  br label %if.end

case1:
  %addr1 = getelementptr i32, ptr %base, i32 1
  %1 = load i32, ptr %addr1
  br label %if.end

case2:
  %addr2 = getelementptr i32, ptr %base, i32 3
  %2 = load i32, ptr %addr2
  br label %if.end

if.end:
  %res = phi i32 [ %0, %otherwise ], [ %1, %case1 ], [ %2, %case2 ], [4, %entry]
  ret i32 %res
}

; Different GEP position.
define i32 @test2(i32 zeroext %flag, ptr %base, ptr %base2) {
; CHECK-LABEL: define i32 @test2
; CHECK-SAME: (i32 zeroext [[FLAG:%.*]], ptr [[BASE:%.*]], ptr [[BASE2:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i32 [[FLAG]], label [[OTHERWISE:%.*]] [
; CHECK-NEXT:    i32 2, label [[CASE1:%.*]]
; CHECK-NEXT:    i32 7, label [[CASE2:%.*]]
; CHECK-NEXT:    i32 6, label [[CASE3:%.*]]
; CHECK-NEXT:    i32 11, label [[IF_END:%.*]]
; CHECK-NEXT:    ]
; CHECK:       otherwise:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[BASE]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       case1:
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[BASE2]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       case2:
; CHECK-NEXT:    [[ADDR2:%.*]] = getelementptr i32, ptr [[BASE]], i32 3
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ADDR2]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       case3:
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[BASE2]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[RES:%.*]] = phi i32 [ [[TMP0]], [[OTHERWISE]] ], [ [[TMP1]], [[CASE1]] ], [ [[TMP2]], [[CASE2]] ], [ [[TMP3]], [[CASE3]] ], [ 4, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  switch i32 %flag, label %otherwise [ i32 2, label %case1
  i32 7, label %case2
  i32 6, label %case3
  i32 11, label %if.end]

otherwise:
  %0 = load i32, ptr %base
  br label %if.end

case1:
  %1 = load i32, ptr %base2
  br label %if.end

case2:
  %addr2 = getelementptr i32, ptr %base, i32 3
  %2 = load i32, ptr %addr2
  br label %if.end

case3:
  %3 = load i32, ptr %base2
  br label %if.end

if.end:
  %res = phi i32 [ %0, %otherwise ], [ %1, %case1 ], [ %2, %case2 ], [ %3, %case3 ], [4, %entry]
  ret i32 %res
}

; Sink load when the offset of pointer not fitted to simm12.
define i32 @test3(i32 zeroext %flag, ptr %base) {
; CHECK-LABEL: define i32 @test3
; CHECK-SAME: (i32 zeroext [[FLAG:%.*]], ptr [[BASE:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    switch i32 [[FLAG]], label [[IF_END_SINK_SPLIT:%.*]] [
; CHECK-NEXT:    i32 2, label [[CASE1:%.*]]
; CHECK-NEXT:    i32 7, label [[CASE2:%.*]]
; CHECK-NEXT:    i32 11, label [[IF_END:%.*]]
; CHECK-NEXT:    ]
; CHECK:       case1:
; CHECK-NEXT:    br label [[IF_END_SINK_SPLIT]]
; CHECK:       case2:
; CHECK-NEXT:    br label [[IF_END_SINK_SPLIT]]
; CHECK:       if.end.sink.split:
; CHECK-NEXT:    [[DOTSINK:%.*]] = phi i32 [ 2500, [[CASE2]] ], [ 3214, [[CASE1]] ], [ 4099, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[ADDR2:%.*]] = getelementptr i32, ptr [[BASE]], i32 [[DOTSINK]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ADDR2]], align 4
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[RES:%.*]] = phi i32 [ 4, [[ENTRY]] ], [ [[TMP0]], [[IF_END_SINK_SPLIT]] ]
; CHECK-NEXT:    ret i32 [[RES]]
;
entry:
  switch i32 %flag, label %otherwise [ i32 2, label %case1
  i32 7, label %case2
  i32 11, label %if.end]

otherwise:
  %addr0 = getelementptr i32, ptr %base, i32 4099
  %0 = load i32, ptr %addr0
  br label %if.end

case1:
  %addr1 = getelementptr i32, ptr %base, i32 3214
  %1 = load i32, ptr %addr1
  br label %if.end

case2:
  %addr2 = getelementptr i32, ptr %base, i32 2500
  %2 = load i32, ptr %addr2
  br label %if.end

if.end:
  %res = phi i32 [ %0, %otherwise ], [ %1, %case1 ], [ %2, %case2 ], [4, %entry]
  ret i32 %res
}
