; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=inline,argpromotion -S | FileCheck --check-prefix=ARGPROMOTION %s
; RUN: opt < %s -passes=inline,argpromotion -loop-data-layout-enable -S | FileCheck --check-prefix=NOARGPROMOTION %s

; This test exemplies guarding of argument promotion of
; structs with/without -loop-data-layout.

%struct.reg_struct = type { i32, i32, i32, ptr, ptr }
%struct.reg_node_struct = type { { float, float }, i64 }

@str.3 = private unnamed_addr constant [26 x i8] c"Measured zero, try again.\00", align 1
@str.4 = private unnamed_addr constant [24 x i8] c"Impossible Measurement!\00", align 1
@.str.10 = private unnamed_addr constant [24 x i8] c"Possible period is %i.\0A\00", align 1
@.str.11.38 = private unnamed_addr constant [14 x i8] c"%i = %i * %i\0A\00", align 1
@.str.2.35 = private unnamed_addr constant [28 x i8] c"N = %i, %i qubits required\0A\00", align 1
@.str.3.36 = private unnamed_addr constant [17 x i8] c"Random seed: %i\0A\00", align 1
@str.6 = private unnamed_addr constant [22 x i8] c"Usage: shor [number]\0A\00", align 1
@.str.6 = private unnamed_addr constant [19 x i8] c"Measured %i (%f), \00", align 1
@.str.7 = private unnamed_addr constant [36 x i8] c"fractional approximation is %i/%i.\0A\00", align 1
@str.1.39 = private unnamed_addr constant [40 x i8] c"Unable to determine factors, try again.\00", align 1
@str.2 = private unnamed_addr constant [23 x i8] c"Odd period, try again.\00", align 1
@str.37 = private unnamed_addr constant [40 x i8] c"Odd denominator, trying to expand by 2.\00", align 1
@str.5 = private unnamed_addr constant [16 x i8] c"Invalid number\0A\00", align 1
@opstatus = internal global i32 0, align 4

define internal i64 @measure(ptr nocapture noundef readonly %arg) align 8 {
bb:
  %i = load i32, ptr @opstatus, align 4, !tbaa !11
  %i1 = icmp eq i32 %i, 0
  br i1 %i1, label %bb2, label %bb30

bb2:                                              ; preds = %bb
  %i3 = tail call fast nofpclass(nan inf) double @spec_rand()
  %i4 = getelementptr inbounds nuw %struct.reg_struct, ptr %arg, i64 0, i32 1
  %i5 = load i32, ptr %i4, align 4, !tbaa !15
  %i6 = icmp sgt i32 %i5, 0
  br i1 %i6, label %bb7, label %bb30

bb7:                                              ; preds = %bb2
  %i8 = getelementptr inbounds nuw %struct.reg_struct, ptr %arg, i64 0, i32 3
  %i9 = load ptr, ptr %i8, align 8, !tbaa !20
  %i10 = zext nneg i32 %i5 to i64
  br label %bb14

bb11:                                             ; preds = %bb14
  %i12 = add nuw nsw i64 %i15, 1
  %i13 = icmp eq i64 %i12, %i10
  br i1 %i13, label %bb30, label %bb14, !llvm.loop !21

bb14:                                             ; preds = %bb11, %bb7
  %i15 = phi i64 [ 0, %bb7 ], [ %i12, %bb11 ]
  %i16 = phi double [ %i3, %bb7 ], [ %i25, %bb11 ]
  %i17 = getelementptr inbounds %struct.reg_node_struct, ptr %i9, i64 %i15
  %i18 = load float, ptr %i17, align 8
  %i19 = getelementptr inbounds nuw { float, float }, ptr %i17, i64 0, i32 1
  %i20 = load float, ptr %i19, align 4
  %i21 = fmul fast float %i18, %i18
  %i22 = fmul fast float %i20, %i20
  %i23 = fadd fast float %i22, %i21
  %i24 = fpext float %i23 to double
  %i25 = fsub fast double %i16, %i24
  %i26 = fcmp fast ugt double %i25, 0.000000e+00
  br i1 %i26, label %bb11, label %bb27

bb27:                                             ; preds = %bb14
  %i28 = getelementptr inbounds %struct.reg_node_struct, ptr %i9, i64 %i15, i32 1
  %i29 = load i64, ptr %i28, align 8, !tbaa !23
  br label %bb30

bb30:                                             ; preds = %bb27, %bb11, %bb2, %bb
  %i31 = phi i64 [ %i29, %bb27 ], [ 0, %bb ], [ -1, %bb2 ], [ -1, %bb11 ]
  ret i64 %i31
}

declare dso_local noalias noundef ptr @realloc(ptr allocptr nocapture noundef, i64 noundef)
declare dso_local void @addscratch(i32 noundef signext, ptr nocapture noundef) align 8
declare dso_local signext range(i32 0, 2) i32 @bmeasure(i32 noundef signext, ptr noundef) align 8
declare dso_local void @cnot(i32 noundef signext, i32 noundef signext, ptr noundef) align 8
declare dso_local void @delete_qureg(ptr nocapture noundef) align 8
declare dso_local void @exp_mod_n(i32 noundef signext, i32 noundef signext, i32 noundef signext, i32 noundef signext, ptr noundef) align 8
declare dso_local void @frac_approx(ptr nocapture noundef, ptr nocapture noundef, i32 noundef signext) align 8
declare dso_local signext i32 @gcd(i32 noundef signext, i32 noundef signext) align 8
declare dso_local signext i32 @getwidth(i32 noundef signext) align 8
declare dso_local void @hadamard(i32 noundef signext, ptr noundef) align 8
declare dso_local signext i32 @ipow(i32 noundef signext, i32 noundef signext) align 8
declare dso_local void @new_qureg(ptr dead_on_unwind noalias nocapture writable writeonly align 8 initializes((0, 12), (16, 24)), i64 noundef, i32 noundef signext) align 8
declare dso_local void @qft(i32 noundef signext, ptr noundef) align 8
declare dso_local nofpclass(nan inf) double @spec_rand() align 8
declare dso_local void @spec_srand(i32 noundef signext) align 8
declare dso_local noundef signext i32 @printf(ptr nocapture noundef readonly, ...)
declare dso_local i64 @strtol(ptr noundef readonly, ptr nocapture noundef, i32 noundef signext)

define dso_local signext range(i32 0, 4) i32 @main(i32 noundef signext %arg, ptr nocapture noundef readonly %arg1) align 8 {
; ARGPROMOTION-LABEL: define dso_local signext range(i32 0, 4) i32 @main(
; ARGPROMOTION-SAME: i32 noundef signext [[ARG:%.*]], ptr noundef readonly captures(none) [[ARG1:%.*]]) align 8 {
; ARGPROMOTION-NEXT:  [[BB:.*:]]
; ARGPROMOTION-NEXT:    [[I:%.*]] = alloca [[STRUCT_REG_STRUCT:%.*]], align 8
; ARGPROMOTION-NEXT:    [[I2:%.*]] = alloca i32, align 4
; ARGPROMOTION-NEXT:    [[I3:%.*]] = alloca i32, align 4
; ARGPROMOTION-NEXT:    [[I4:%.*]] = alloca [[STRUCT_REG_STRUCT]], align 8
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[I]])
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[I2]])
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[I3]])
; ARGPROMOTION-NEXT:    tail call void @spec_srand(i32 noundef signext 26)
; ARGPROMOTION-NEXT:    [[I5:%.*]] = icmp eq i32 [[ARG]], 1
; ARGPROMOTION-NEXT:    br i1 [[I5]], label %[[BB6:.*]], label %[[BB8:.*]]
; ARGPROMOTION:       [[BB6]]:
; ARGPROMOTION-NEXT:    [[I7:%.*]] = tail call i32 @puts(ptr nonnull dereferenceable(1) @str.6)
; ARGPROMOTION-NEXT:    br label %[[BB124:.*]]
; ARGPROMOTION:       [[BB8]]:
; ARGPROMOTION-NEXT:    [[I9:%.*]] = getelementptr inbounds ptr, ptr [[ARG1]], i64 1
; ARGPROMOTION-NEXT:    [[I10:%.*]] = load ptr, ptr [[I9]], align 8, !tbaa [[TBAA0:![0-9]+]]
; ARGPROMOTION-NEXT:    [[I11:%.*]] = tail call i64 @strtol(ptr noundef nonnull captures(none) [[I10]], ptr noundef null, i32 noundef signext 10)
; ARGPROMOTION-NEXT:    [[I12:%.*]] = trunc i64 [[I11]] to i32
; ARGPROMOTION-NEXT:    [[I13:%.*]] = icmp slt i32 [[I12]], 15
; ARGPROMOTION-NEXT:    br i1 [[I13]], label %[[BB14:.*]], label %[[BB16:.*]]
; ARGPROMOTION:       [[BB14]]:
; ARGPROMOTION-NEXT:    [[I15:%.*]] = tail call i32 @puts(ptr nonnull dereferenceable(1) @str.5)
; ARGPROMOTION-NEXT:    br label %[[BB124]]
; ARGPROMOTION:       [[BB16]]:
; ARGPROMOTION-NEXT:    [[I17:%.*]] = mul nuw nsw i32 [[I12]], [[I12]]
; ARGPROMOTION-NEXT:    [[I18:%.*]] = tail call signext i32 @getwidth(i32 noundef signext [[I17]])
; ARGPROMOTION-NEXT:    [[I19:%.*]] = tail call signext i32 @getwidth(i32 noundef signext [[I12]])
; ARGPROMOTION-NEXT:    [[I20:%.*]] = mul nsw i32 [[I19]], 3
; ARGPROMOTION-NEXT:    [[I21:%.*]] = add i32 [[I20]], 2
; ARGPROMOTION-NEXT:    [[I22:%.*]] = add i32 [[I21]], [[I18]]
; ARGPROMOTION-NEXT:    [[I23:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.2.35, i32 noundef signext [[I12]], i32 noundef signext [[I22]])
; ARGPROMOTION-NEXT:    [[I24:%.*]] = icmp sgt i32 [[ARG]], 2
; ARGPROMOTION-NEXT:    br i1 [[I24]], label %[[BB25:.*]], label %[[BB30:.*]]
; ARGPROMOTION:       [[BB25]]:
; ARGPROMOTION-NEXT:    [[I26:%.*]] = getelementptr inbounds ptr, ptr [[ARG1]], i64 2
; ARGPROMOTION-NEXT:    [[I27:%.*]] = load ptr, ptr [[I26]], align 8, !tbaa [[TBAA0]]
; ARGPROMOTION-NEXT:    [[I28:%.*]] = tail call i64 @strtol(ptr noundef nonnull captures(none) [[I27]], ptr noundef null, i32 noundef signext 10)
; ARGPROMOTION-NEXT:    [[I29:%.*]] = trunc i64 [[I28]] to i32
; ARGPROMOTION-NEXT:    br label %[[BB30]]
; ARGPROMOTION:       [[BB30]]:
; ARGPROMOTION-NEXT:    [[I31:%.*]] = phi i32 [ [[I29]], %[[BB25]] ], [ 0, %[[BB16]] ]
; ARGPROMOTION-NEXT:    [[I32:%.*]] = and i64 [[I11]], 2147483647
; ARGPROMOTION-NEXT:    br label %[[BB33:.*]]
; ARGPROMOTION:       [[BB33]]:
; ARGPROMOTION-NEXT:    [[I34:%.*]] = phi i32 [ [[I31]], %[[BB30]] ], [ [[I44:%.*]], %[[BB39:.*]] ]
; ARGPROMOTION-NEXT:    [[I35:%.*]] = tail call signext i32 @gcd(i32 noundef signext [[I12]], i32 noundef signext [[I34]])
; ARGPROMOTION-NEXT:    [[I36:%.*]] = icmp sgt i32 [[I35]], 1
; ARGPROMOTION-NEXT:    [[I37:%.*]] = icmp slt i32 [[I34]], 2
; ARGPROMOTION-NEXT:    [[I38:%.*]] = or i1 [[I37]], [[I36]]
; ARGPROMOTION-NEXT:    br i1 [[I38]], label %[[BB39]], label %[[BB45:.*]]
; ARGPROMOTION:       [[BB39]]:
; ARGPROMOTION-NEXT:    [[I40:%.*]] = tail call fast nofpclass(nan inf) double @spec_rand()
; ARGPROMOTION-NEXT:    [[I41:%.*]] = fmul fast double [[I40]], 0x41DFFFFFFFC00000
; ARGPROMOTION-NEXT:    [[I42:%.*]] = fptosi double [[I41]] to i64
; ARGPROMOTION-NEXT:    [[I43:%.*]] = srem i64 [[I42]], [[I32]]
; ARGPROMOTION-NEXT:    [[I44]] = trunc nsw i64 [[I43]] to i32
; ARGPROMOTION-NEXT:    br label %[[BB33]], !llvm.loop [[LOOP4:![0-9]+]]
; ARGPROMOTION:       [[BB45]]:
; ARGPROMOTION-NEXT:    [[I46:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.3.36, i32 noundef signext [[I34]])
; ARGPROMOTION-NEXT:    call void @new_qureg(ptr dead_on_unwind noalias nonnull writable align 8 [[I]], i64 noundef 0, i32 noundef signext [[I18]])
; ARGPROMOTION-NEXT:    [[I47:%.*]] = icmp sgt i32 [[I18]], 0
; ARGPROMOTION-NEXT:    br i1 [[I47]], label %[[BB48:.*]], label %[[BB52:.*]]
; ARGPROMOTION:       [[BB48]]:
; ARGPROMOTION-NEXT:    [[I49:%.*]] = phi i32 [ [[I50:%.*]], %[[BB48]] ], [ 0, %[[BB45]] ]
; ARGPROMOTION-NEXT:    call void @hadamard(i32 noundef signext [[I49]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    [[I50]] = add nuw nsw i32 [[I49]], 1
; ARGPROMOTION-NEXT:    [[I51:%.*]] = icmp eq i32 [[I50]], [[I18]]
; ARGPROMOTION-NEXT:    br i1 [[I51]], label %[[BB52]], label %[[BB48]], !llvm.loop [[LOOP6:![0-9]+]]
; ARGPROMOTION:       [[BB52]]:
; ARGPROMOTION-NEXT:    call void @addscratch(i32 noundef signext [[I21]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    call void @exp_mod_n(i32 noundef signext [[I12]], i32 noundef signext [[I34]], i32 noundef signext [[I18]], i32 noundef signext [[I19]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    [[I53:%.*]] = icmp sgt i32 [[I19]], -1
; ARGPROMOTION-NEXT:    br i1 [[I53]], label %[[BB54:.*]], label %[[BB61:.*]]
; ARGPROMOTION:       [[BB54]]:
; ARGPROMOTION-NEXT:    [[I55:%.*]] = call i32 @llvm.smax.i32(i32 [[I21]], i32 1)
; ARGPROMOTION-NEXT:    br label %[[BB56:.*]]
; ARGPROMOTION:       [[BB56]]:
; ARGPROMOTION-NEXT:    [[I57:%.*]] = phi i32 [ [[I59:%.*]], %[[BB56]] ], [ 0, %[[BB54]] ]
; ARGPROMOTION-NEXT:    [[I58:%.*]] = call signext i32 @bmeasure(i32 noundef signext 0, ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    [[I59]] = add nuw nsw i32 [[I57]], 1
; ARGPROMOTION-NEXT:    [[I60:%.*]] = icmp eq i32 [[I59]], [[I55]]
; ARGPROMOTION-NEXT:    br i1 [[I60]], label %[[BB61]], label %[[BB56]], !llvm.loop [[LOOP7:![0-9]+]]
; ARGPROMOTION:       [[BB61]]:
; ARGPROMOTION-NEXT:    call void @qft(i32 noundef signext [[I18]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    [[I62:%.*]] = sdiv i32 [[I18]], 2
; ARGPROMOTION-NEXT:    [[I63:%.*]] = icmp sgt i32 [[I18]], 1
; ARGPROMOTION-NEXT:    br i1 [[I63]], label %[[BB64:.*]], label %[[BB70:.*]]
; ARGPROMOTION:       [[BB64]]:
; ARGPROMOTION-NEXT:    [[I65:%.*]] = phi i32 [ [[I68:%.*]], %[[BB64]] ], [ 0, %[[BB61]] ]
; ARGPROMOTION-NEXT:    [[I66:%.*]] = xor i32 [[I65]], -1
; ARGPROMOTION-NEXT:    [[I67:%.*]] = add nsw i32 [[I18]], [[I66]]
; ARGPROMOTION-NEXT:    call void @cnot(i32 noundef signext [[I65]], i32 noundef signext [[I67]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    call void @cnot(i32 noundef signext [[I67]], i32 noundef signext [[I65]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    call void @cnot(i32 noundef signext [[I65]], i32 noundef signext [[I67]], ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    [[I68]] = add nuw nsw i32 [[I65]], 1
; ARGPROMOTION-NEXT:    [[I69:%.*]] = icmp eq i32 [[I68]], [[I62]]
; ARGPROMOTION-NEXT:    br i1 [[I69]], label %[[BB70]], label %[[BB64]], !llvm.loop [[LOOP8:![0-9]+]]
; ARGPROMOTION:       [[BB70]]:
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[I4]])
; ARGPROMOTION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) [[I4]], ptr noundef nonnull align 8 dereferenceable(32) [[I]], i64 32, i1 false), !tbaa [[TBAA9:![0-9]+]], !tbaa.struct [[TBAA_STRUCT12:![0-9]+]]
; ARGPROMOTION-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[I4]], i64 4
; ARGPROMOTION-NEXT:    [[I4_VAL:%.*]] = load i32, ptr [[TMP0]], align 4
; ARGPROMOTION-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[I4]], i64 16
; ARGPROMOTION-NEXT:    [[I4_VAL1:%.*]] = load ptr, ptr [[TMP1]], align 8
; ARGPROMOTION-NEXT:    [[I_I:%.*]] = load i32, ptr @opstatus, align 4, !tbaa [[TBAA14:![0-9]+]]
; ARGPROMOTION-NEXT:    [[I1_I:%.*]] = icmp eq i32 [[I_I]], 0
; ARGPROMOTION-NEXT:    br i1 [[I1_I]], label %[[BB2_I:.*]], label %[[MEASURE_EXIT:.*]]
; ARGPROMOTION:       [[BB2_I]]:
; ARGPROMOTION-NEXT:    [[I3_I:%.*]] = call fast nofpclass(nan inf) double @spec_rand()
; ARGPROMOTION-NEXT:    [[I6_I:%.*]] = icmp sgt i32 [[I4_VAL]], 0
; ARGPROMOTION-NEXT:    br i1 [[I6_I]], label %[[BB7_I:.*]], label %[[MEASURE_EXIT]]
; ARGPROMOTION:       [[BB7_I]]:
; ARGPROMOTION-NEXT:    [[I10_I:%.*]] = zext nneg i32 [[I4_VAL]] to i64
; ARGPROMOTION-NEXT:    br label %[[BB14_I:.*]]
; ARGPROMOTION:       [[BB11_I:.*]]:
; ARGPROMOTION-NEXT:    [[I12_I:%.*]] = add nuw nsw i64 [[I15_I:%.*]], 1
; ARGPROMOTION-NEXT:    [[I13_I:%.*]] = icmp eq i64 [[I12_I]], [[I10_I]]
; ARGPROMOTION-NEXT:    br i1 [[I13_I]], label %[[MEASURE_EXIT]], label %[[BB14_I]], !llvm.loop [[LOOP16:![0-9]+]]
; ARGPROMOTION:       [[BB14_I]]:
; ARGPROMOTION-NEXT:    [[I15_I]] = phi i64 [ 0, %[[BB7_I]] ], [ [[I12_I]], %[[BB11_I]] ]
; ARGPROMOTION-NEXT:    [[I16_I:%.*]] = phi double [ [[I3_I]], %[[BB7_I]] ], [ [[I25_I:%.*]], %[[BB11_I]] ]
; ARGPROMOTION-NEXT:    [[I17_I:%.*]] = getelementptr inbounds [[STRUCT_REG_NODE_STRUCT:%.*]], ptr [[I4_VAL1]], i64 [[I15_I]]
; ARGPROMOTION-NEXT:    [[I18_I:%.*]] = load float, ptr [[I17_I]], align 8
; ARGPROMOTION-NEXT:    [[I19_I:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[I17_I]], i64 0, i32 1
; ARGPROMOTION-NEXT:    [[I20_I:%.*]] = load float, ptr [[I19_I]], align 4
; ARGPROMOTION-NEXT:    [[I21_I:%.*]] = fmul fast float [[I18_I]], [[I18_I]]
; ARGPROMOTION-NEXT:    [[I22_I:%.*]] = fmul fast float [[I20_I]], [[I20_I]]
; ARGPROMOTION-NEXT:    [[I23_I:%.*]] = fadd fast float [[I22_I]], [[I21_I]]
; ARGPROMOTION-NEXT:    [[I24_I:%.*]] = fpext float [[I23_I]] to double
; ARGPROMOTION-NEXT:    [[I25_I]] = fsub fast double [[I16_I]], [[I24_I]]
; ARGPROMOTION-NEXT:    [[I26_I:%.*]] = fcmp fast ugt double [[I25_I]], 0.000000e+00
; ARGPROMOTION-NEXT:    br i1 [[I26_I]], label %[[BB11_I]], label %[[BB27_I:.*]]
; ARGPROMOTION:       [[BB27_I]]:
; ARGPROMOTION-NEXT:    [[I28_I:%.*]] = getelementptr inbounds [[STRUCT_REG_NODE_STRUCT]], ptr [[I4_VAL1]], i64 [[I15_I]], i32 1
; ARGPROMOTION-NEXT:    [[I29_I:%.*]] = load i64, ptr [[I28_I]], align 8, !tbaa [[TBAA17:![0-9]+]]
; ARGPROMOTION-NEXT:    br label %[[MEASURE_EXIT]]
; ARGPROMOTION:       [[MEASURE_EXIT]]:
; ARGPROMOTION-NEXT:    [[I31_I:%.*]] = phi i64 [ [[I29_I]], %[[BB27_I]] ], [ 0, %[[BB70]] ], [ -1, %[[BB2_I]] ], [ -1, %[[BB11_I]] ]
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[I4]])
; ARGPROMOTION-NEXT:    [[I72:%.*]] = trunc i64 [[I31_I]] to i32
; ARGPROMOTION-NEXT:    store i32 [[I72]], ptr [[I2]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    switch i32 [[I72]], label %[[BB77:.*]] [
; ARGPROMOTION-NEXT:      i32 -1, label %[[BB73:.*]]
; ARGPROMOTION-NEXT:      i32 0, label %[[BB75:.*]]
; ARGPROMOTION-NEXT:    ]
; ARGPROMOTION:       [[BB73]]:
; ARGPROMOTION-NEXT:    [[I74:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.4)
; ARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 1)
; ARGPROMOTION-NEXT:    unreachable
; ARGPROMOTION:       [[BB75]]:
; ARGPROMOTION-NEXT:    [[I76:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.3)
; ARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 2)
; ARGPROMOTION-NEXT:    unreachable
; ARGPROMOTION:       [[BB77]]:
; ARGPROMOTION-NEXT:    [[I78:%.*]] = shl nuw i32 1, [[I18]]
; ARGPROMOTION-NEXT:    store i32 [[I78]], ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I79:%.*]] = sitofp i32 [[I72]] to float
; ARGPROMOTION-NEXT:    [[I80:%.*]] = sitofp i32 [[I78]] to float
; ARGPROMOTION-NEXT:    [[I81:%.*]] = fdiv fast float [[I79]], [[I80]]
; ARGPROMOTION-NEXT:    [[I82:%.*]] = fpext float [[I81]] to double
; ARGPROMOTION-NEXT:    [[I83:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.6, i32 noundef signext [[I72]], double noundef nofpclass(nan inf) [[I82]])
; ARGPROMOTION-NEXT:    call void @frac_approx(ptr noundef nonnull [[I2]], ptr noundef nonnull [[I3]], i32 noundef signext [[I18]])
; ARGPROMOTION-NEXT:    [[I84:%.*]] = load i32, ptr [[I2]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I85:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I86:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.7, i32 noundef signext [[I84]], i32 noundef signext [[I85]])
; ARGPROMOTION-NEXT:    [[I87:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I88:%.*]] = and i32 [[I87]], -2147483647
; ARGPROMOTION-NEXT:    [[I89:%.*]] = icmp eq i32 [[I88]], 1
; ARGPROMOTION-NEXT:    [[I90:%.*]] = shl nuw nsw i32 [[I87]], 1
; ARGPROMOTION-NEXT:    [[I91:%.*]] = icmp slt i32 [[I90]], [[I78]]
; ARGPROMOTION-NEXT:    [[I92:%.*]] = select i1 [[I89]], i1 [[I91]], i1 false
; ARGPROMOTION-NEXT:    br i1 [[I92]], label %[[BB93:.*]], label %[[BB97:.*]]
; ARGPROMOTION:       [[BB93]]:
; ARGPROMOTION-NEXT:    [[I94:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.37)
; ARGPROMOTION-NEXT:    [[I95:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I96:%.*]] = shl nsw i32 [[I95]], 1
; ARGPROMOTION-NEXT:    store i32 [[I96]], ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    br label %[[BB97]]
; ARGPROMOTION:       [[BB97]]:
; ARGPROMOTION-NEXT:    [[I98:%.*]] = phi i32 [ [[I96]], %[[BB93]] ], [ [[I87]], %[[BB77]] ]
; ARGPROMOTION-NEXT:    [[I99:%.*]] = and i32 [[I98]], -2147483647
; ARGPROMOTION-NEXT:    [[I100:%.*]] = icmp eq i32 [[I99]], 1
; ARGPROMOTION-NEXT:    br i1 [[I100]], label %[[BB101:.*]], label %[[BB103:.*]]
; ARGPROMOTION:       [[BB101]]:
; ARGPROMOTION-NEXT:    [[I102:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.2)
; ARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 2)
; ARGPROMOTION-NEXT:    unreachable
; ARGPROMOTION:       [[BB103]]:
; ARGPROMOTION-NEXT:    [[I104:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.10, i32 noundef signext [[I98]])
; ARGPROMOTION-NEXT:    [[I105:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I106:%.*]] = sdiv i32 [[I105]], 2
; ARGPROMOTION-NEXT:    [[I107:%.*]] = call signext i32 @ipow(i32 noundef signext [[I34]], i32 noundef signext [[I106]])
; ARGPROMOTION-NEXT:    [[I108:%.*]] = add nsw i32 [[I107]], 1
; ARGPROMOTION-NEXT:    [[I109:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; ARGPROMOTION-NEXT:    [[I110:%.*]] = sdiv i32 [[I109]], 2
; ARGPROMOTION-NEXT:    [[I111:%.*]] = call signext i32 @ipow(i32 noundef signext [[I34]], i32 noundef signext [[I110]])
; ARGPROMOTION-NEXT:    [[I112:%.*]] = add nsw i32 [[I111]], -1
; ARGPROMOTION-NEXT:    [[I113:%.*]] = call signext i32 @gcd(i32 noundef signext [[I12]], i32 noundef signext [[I108]])
; ARGPROMOTION-NEXT:    [[I114:%.*]] = call signext i32 @gcd(i32 noundef signext [[I12]], i32 noundef signext [[I112]])
; ARGPROMOTION-NEXT:    [[I115:%.*]] = call i32 @llvm.smax.i32(i32 [[I113]], i32 [[I114]])
; ARGPROMOTION-NEXT:    [[I116:%.*]] = icmp slt i32 [[I115]], [[I12]]
; ARGPROMOTION-NEXT:    [[I117:%.*]] = icmp sgt i32 [[I115]], 1
; ARGPROMOTION-NEXT:    [[I118:%.*]] = and i1 [[I116]], [[I117]]
; ARGPROMOTION-NEXT:    br i1 [[I118]], label %[[BB119:.*]], label %[[BB122:.*]]
; ARGPROMOTION:       [[BB119]]:
; ARGPROMOTION-NEXT:    [[I120:%.*]] = udiv i32 [[I12]], [[I115]]
; ARGPROMOTION-NEXT:    [[I121:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.11.38, i32 noundef signext [[I12]], i32 noundef signext [[I115]], i32 noundef signext [[I120]])
; ARGPROMOTION-NEXT:    call void @delete_qureg(ptr noundef nonnull [[I]])
; ARGPROMOTION-NEXT:    br label %[[BB124]]
; ARGPROMOTION:       [[BB122]]:
; ARGPROMOTION-NEXT:    [[I123:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.1.39)
; ARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 0)
; ARGPROMOTION-NEXT:    unreachable
; ARGPROMOTION:       [[BB124]]:
; ARGPROMOTION-NEXT:    [[I125:%.*]] = phi i32 [ 3, %[[BB6]] ], [ 3, %[[BB14]] ], [ 0, %[[BB119]] ]
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[I3]])
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[I2]])
; ARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[I]])
; ARGPROMOTION-NEXT:    ret i32 [[I125]]
;
; NOARGPROMOTION-LABEL: define dso_local signext range(i32 0, 4) i32 @main(
; NOARGPROMOTION-SAME: i32 noundef signext [[ARG:%.*]], ptr noundef readonly captures(none) [[ARG1:%.*]]) align 8 {
; NOARGPROMOTION-NEXT:  [[BB:.*:]]
; NOARGPROMOTION-NEXT:    [[I:%.*]] = alloca [[STRUCT_REG_STRUCT:%.*]], align 8
; NOARGPROMOTION-NEXT:    [[I2:%.*]] = alloca i32, align 4
; NOARGPROMOTION-NEXT:    [[I3:%.*]] = alloca i32, align 4
; NOARGPROMOTION-NEXT:    [[I4:%.*]] = alloca [[STRUCT_REG_STRUCT]], align 8
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[I]])
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[I2]])
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr nonnull [[I3]])
; NOARGPROMOTION-NEXT:    tail call void @spec_srand(i32 noundef signext 26)
; NOARGPROMOTION-NEXT:    [[I5:%.*]] = icmp eq i32 [[ARG]], 1
; NOARGPROMOTION-NEXT:    br i1 [[I5]], label %[[BB6:.*]], label %[[BB8:.*]]
; NOARGPROMOTION:       [[BB6]]:
; NOARGPROMOTION-NEXT:    [[I7:%.*]] = tail call i32 @puts(ptr nonnull dereferenceable(1) @str.6)
; NOARGPROMOTION-NEXT:    br label %[[BB124:.*]]
; NOARGPROMOTION:       [[BB8]]:
; NOARGPROMOTION-NEXT:    [[I9:%.*]] = getelementptr inbounds ptr, ptr [[ARG1]], i64 1
; NOARGPROMOTION-NEXT:    [[I10:%.*]] = load ptr, ptr [[I9]], align 8, !tbaa [[TBAA0:![0-9]+]]
; NOARGPROMOTION-NEXT:    [[I11:%.*]] = tail call i64 @strtol(ptr noundef nonnull captures(none) [[I10]], ptr noundef null, i32 noundef signext 10)
; NOARGPROMOTION-NEXT:    [[I12:%.*]] = trunc i64 [[I11]] to i32
; NOARGPROMOTION-NEXT:    [[I13:%.*]] = icmp slt i32 [[I12]], 15
; NOARGPROMOTION-NEXT:    br i1 [[I13]], label %[[BB14:.*]], label %[[BB16:.*]]
; NOARGPROMOTION:       [[BB14]]:
; NOARGPROMOTION-NEXT:    [[I15:%.*]] = tail call i32 @puts(ptr nonnull dereferenceable(1) @str.5)
; NOARGPROMOTION-NEXT:    br label %[[BB124]]
; NOARGPROMOTION:       [[BB16]]:
; NOARGPROMOTION-NEXT:    [[I17:%.*]] = mul nuw nsw i32 [[I12]], [[I12]]
; NOARGPROMOTION-NEXT:    [[I18:%.*]] = tail call signext i32 @getwidth(i32 noundef signext [[I17]])
; NOARGPROMOTION-NEXT:    [[I19:%.*]] = tail call signext i32 @getwidth(i32 noundef signext [[I12]])
; NOARGPROMOTION-NEXT:    [[I20:%.*]] = mul nsw i32 [[I19]], 3
; NOARGPROMOTION-NEXT:    [[I21:%.*]] = add i32 [[I20]], 2
; NOARGPROMOTION-NEXT:    [[I22:%.*]] = add i32 [[I21]], [[I18]]
; NOARGPROMOTION-NEXT:    [[I23:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.2.35, i32 noundef signext [[I12]], i32 noundef signext [[I22]])
; NOARGPROMOTION-NEXT:    [[I24:%.*]] = icmp sgt i32 [[ARG]], 2
; NOARGPROMOTION-NEXT:    br i1 [[I24]], label %[[BB25:.*]], label %[[BB30:.*]]
; NOARGPROMOTION:       [[BB25]]:
; NOARGPROMOTION-NEXT:    [[I26:%.*]] = getelementptr inbounds ptr, ptr [[ARG1]], i64 2
; NOARGPROMOTION-NEXT:    [[I27:%.*]] = load ptr, ptr [[I26]], align 8, !tbaa [[TBAA0]]
; NOARGPROMOTION-NEXT:    [[I28:%.*]] = tail call i64 @strtol(ptr noundef nonnull captures(none) [[I27]], ptr noundef null, i32 noundef signext 10)
; NOARGPROMOTION-NEXT:    [[I29:%.*]] = trunc i64 [[I28]] to i32
; NOARGPROMOTION-NEXT:    br label %[[BB30]]
; NOARGPROMOTION:       [[BB30]]:
; NOARGPROMOTION-NEXT:    [[I31:%.*]] = phi i32 [ [[I29]], %[[BB25]] ], [ 0, %[[BB16]] ]
; NOARGPROMOTION-NEXT:    [[I32:%.*]] = and i64 [[I11]], 2147483647
; NOARGPROMOTION-NEXT:    br label %[[BB33:.*]]
; NOARGPROMOTION:       [[BB33]]:
; NOARGPROMOTION-NEXT:    [[I34:%.*]] = phi i32 [ [[I31]], %[[BB30]] ], [ [[I44:%.*]], %[[BB39:.*]] ]
; NOARGPROMOTION-NEXT:    [[I35:%.*]] = tail call signext i32 @gcd(i32 noundef signext [[I12]], i32 noundef signext [[I34]])
; NOARGPROMOTION-NEXT:    [[I36:%.*]] = icmp sgt i32 [[I35]], 1
; NOARGPROMOTION-NEXT:    [[I37:%.*]] = icmp slt i32 [[I34]], 2
; NOARGPROMOTION-NEXT:    [[I38:%.*]] = or i1 [[I37]], [[I36]]
; NOARGPROMOTION-NEXT:    br i1 [[I38]], label %[[BB39]], label %[[BB45:.*]]
; NOARGPROMOTION:       [[BB39]]:
; NOARGPROMOTION-NEXT:    [[I40:%.*]] = tail call fast nofpclass(nan inf) double @spec_rand()
; NOARGPROMOTION-NEXT:    [[I41:%.*]] = fmul fast double [[I40]], 0x41DFFFFFFFC00000
; NOARGPROMOTION-NEXT:    [[I42:%.*]] = fptosi double [[I41]] to i64
; NOARGPROMOTION-NEXT:    [[I43:%.*]] = srem i64 [[I42]], [[I32]]
; NOARGPROMOTION-NEXT:    [[I44]] = trunc nsw i64 [[I43]] to i32
; NOARGPROMOTION-NEXT:    br label %[[BB33]], !llvm.loop [[LOOP4:![0-9]+]]
; NOARGPROMOTION:       [[BB45]]:
; NOARGPROMOTION-NEXT:    [[I46:%.*]] = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.3.36, i32 noundef signext [[I34]])
; NOARGPROMOTION-NEXT:    call void @new_qureg(ptr dead_on_unwind noalias nonnull writable align 8 [[I]], i64 noundef 0, i32 noundef signext [[I18]])
; NOARGPROMOTION-NEXT:    [[I47:%.*]] = icmp sgt i32 [[I18]], 0
; NOARGPROMOTION-NEXT:    br i1 [[I47]], label %[[BB48:.*]], label %[[BB52:.*]]
; NOARGPROMOTION:       [[BB48]]:
; NOARGPROMOTION-NEXT:    [[I49:%.*]] = phi i32 [ [[I50:%.*]], %[[BB48]] ], [ 0, %[[BB45]] ]
; NOARGPROMOTION-NEXT:    call void @hadamard(i32 noundef signext [[I49]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    [[I50]] = add nuw nsw i32 [[I49]], 1
; NOARGPROMOTION-NEXT:    [[I51:%.*]] = icmp eq i32 [[I50]], [[I18]]
; NOARGPROMOTION-NEXT:    br i1 [[I51]], label %[[BB52]], label %[[BB48]], !llvm.loop [[LOOP6:![0-9]+]]
; NOARGPROMOTION:       [[BB52]]:
; NOARGPROMOTION-NEXT:    call void @addscratch(i32 noundef signext [[I21]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    call void @exp_mod_n(i32 noundef signext [[I12]], i32 noundef signext [[I34]], i32 noundef signext [[I18]], i32 noundef signext [[I19]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    [[I53:%.*]] = icmp sgt i32 [[I19]], -1
; NOARGPROMOTION-NEXT:    br i1 [[I53]], label %[[BB54:.*]], label %[[BB61:.*]]
; NOARGPROMOTION:       [[BB54]]:
; NOARGPROMOTION-NEXT:    [[I55:%.*]] = call i32 @llvm.smax.i32(i32 [[I21]], i32 1)
; NOARGPROMOTION-NEXT:    br label %[[BB56:.*]]
; NOARGPROMOTION:       [[BB56]]:
; NOARGPROMOTION-NEXT:    [[I57:%.*]] = phi i32 [ [[I59:%.*]], %[[BB56]] ], [ 0, %[[BB54]] ]
; NOARGPROMOTION-NEXT:    [[I58:%.*]] = call signext i32 @bmeasure(i32 noundef signext 0, ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    [[I59]] = add nuw nsw i32 [[I57]], 1
; NOARGPROMOTION-NEXT:    [[I60:%.*]] = icmp eq i32 [[I59]], [[I55]]
; NOARGPROMOTION-NEXT:    br i1 [[I60]], label %[[BB61]], label %[[BB56]], !llvm.loop [[LOOP7:![0-9]+]]
; NOARGPROMOTION:       [[BB61]]:
; NOARGPROMOTION-NEXT:    call void @qft(i32 noundef signext [[I18]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    [[I62:%.*]] = sdiv i32 [[I18]], 2
; NOARGPROMOTION-NEXT:    [[I63:%.*]] = icmp sgt i32 [[I18]], 1
; NOARGPROMOTION-NEXT:    br i1 [[I63]], label %[[BB64:.*]], label %[[BB70:.*]]
; NOARGPROMOTION:       [[BB64]]:
; NOARGPROMOTION-NEXT:    [[I65:%.*]] = phi i32 [ [[I68:%.*]], %[[BB64]] ], [ 0, %[[BB61]] ]
; NOARGPROMOTION-NEXT:    [[I66:%.*]] = xor i32 [[I65]], -1
; NOARGPROMOTION-NEXT:    [[I67:%.*]] = add nsw i32 [[I18]], [[I66]]
; NOARGPROMOTION-NEXT:    call void @cnot(i32 noundef signext [[I65]], i32 noundef signext [[I67]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    call void @cnot(i32 noundef signext [[I67]], i32 noundef signext [[I65]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    call void @cnot(i32 noundef signext [[I65]], i32 noundef signext [[I67]], ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    [[I68]] = add nuw nsw i32 [[I65]], 1
; NOARGPROMOTION-NEXT:    [[I69:%.*]] = icmp eq i32 [[I68]], [[I62]]
; NOARGPROMOTION-NEXT:    br i1 [[I69]], label %[[BB70]], label %[[BB64]], !llvm.loop [[LOOP8:![0-9]+]]
; NOARGPROMOTION:       [[BB70]]:
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr nonnull [[I4]])
; NOARGPROMOTION-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) [[I4]], ptr noundef nonnull align 8 dereferenceable(32) [[I]], i64 32, i1 false), !tbaa [[TBAA9:![0-9]+]], !tbaa.struct [[TBAA_STRUCT12:![0-9]+]]
; NOARGPROMOTION-NEXT:    [[I_I:%.*]] = load i32, ptr @opstatus, align 4, !tbaa [[TBAA14:![0-9]+]]
; NOARGPROMOTION-NEXT:    [[I1_I:%.*]] = icmp eq i32 [[I_I]], 0
; NOARGPROMOTION-NEXT:    br i1 [[I1_I]], label %[[BB2_I:.*]], label %[[MEASURE_EXIT:.*]]
; NOARGPROMOTION:       [[BB2_I]]:
; NOARGPROMOTION-NEXT:    [[I3_I:%.*]] = call fast nofpclass(nan inf) double @spec_rand()
; NOARGPROMOTION-NEXT:    [[I4_I:%.*]] = getelementptr inbounds nuw [[STRUCT_REG_STRUCT]], ptr [[I4]], i64 0, i32 1
; NOARGPROMOTION-NEXT:    [[I5_I:%.*]] = load i32, ptr [[I4_I]], align 4, !tbaa [[TBAA16:![0-9]+]]
; NOARGPROMOTION-NEXT:    [[I6_I:%.*]] = icmp sgt i32 [[I5_I]], 0
; NOARGPROMOTION-NEXT:    br i1 [[I6_I]], label %[[BB7_I:.*]], label %[[MEASURE_EXIT]]
; NOARGPROMOTION:       [[BB7_I]]:
; NOARGPROMOTION-NEXT:    [[I8_I:%.*]] = getelementptr inbounds nuw [[STRUCT_REG_STRUCT]], ptr [[I4]], i64 0, i32 3
; NOARGPROMOTION-NEXT:    [[I9_I:%.*]] = load ptr, ptr [[I8_I]], align 8, !tbaa [[TBAA18:![0-9]+]]
; NOARGPROMOTION-NEXT:    [[I10_I:%.*]] = zext nneg i32 [[I5_I]] to i64
; NOARGPROMOTION-NEXT:    br label %[[BB14_I:.*]]
; NOARGPROMOTION:       [[BB11_I:.*]]:
; NOARGPROMOTION-NEXT:    [[I12_I:%.*]] = add nuw nsw i64 [[I15_I:%.*]], 1
; NOARGPROMOTION-NEXT:    [[I13_I:%.*]] = icmp eq i64 [[I12_I]], [[I10_I]]
; NOARGPROMOTION-NEXT:    br i1 [[I13_I]], label %[[MEASURE_EXIT]], label %[[BB14_I]], !llvm.loop [[LOOP19:![0-9]+]]
; NOARGPROMOTION:       [[BB14_I]]:
; NOARGPROMOTION-NEXT:    [[I15_I]] = phi i64 [ 0, %[[BB7_I]] ], [ [[I12_I]], %[[BB11_I]] ]
; NOARGPROMOTION-NEXT:    [[I16_I:%.*]] = phi double [ [[I3_I]], %[[BB7_I]] ], [ [[I25_I:%.*]], %[[BB11_I]] ]
; NOARGPROMOTION-NEXT:    [[I17_I:%.*]] = getelementptr inbounds [[STRUCT_REG_NODE_STRUCT:%.*]], ptr [[I9_I]], i64 [[I15_I]]
; NOARGPROMOTION-NEXT:    [[I18_I:%.*]] = load float, ptr [[I17_I]], align 8
; NOARGPROMOTION-NEXT:    [[I19_I:%.*]] = getelementptr inbounds nuw { float, float }, ptr [[I17_I]], i64 0, i32 1
; NOARGPROMOTION-NEXT:    [[I20_I:%.*]] = load float, ptr [[I19_I]], align 4
; NOARGPROMOTION-NEXT:    [[I21_I:%.*]] = fmul fast float [[I18_I]], [[I18_I]]
; NOARGPROMOTION-NEXT:    [[I22_I:%.*]] = fmul fast float [[I20_I]], [[I20_I]]
; NOARGPROMOTION-NEXT:    [[I23_I:%.*]] = fadd fast float [[I22_I]], [[I21_I]]
; NOARGPROMOTION-NEXT:    [[I24_I:%.*]] = fpext float [[I23_I]] to double
; NOARGPROMOTION-NEXT:    [[I25_I]] = fsub fast double [[I16_I]], [[I24_I]]
; NOARGPROMOTION-NEXT:    [[I26_I:%.*]] = fcmp fast ugt double [[I25_I]], 0.000000e+00
; NOARGPROMOTION-NEXT:    br i1 [[I26_I]], label %[[BB11_I]], label %[[BB27_I:.*]]
; NOARGPROMOTION:       [[BB27_I]]:
; NOARGPROMOTION-NEXT:    [[I28_I:%.*]] = getelementptr inbounds [[STRUCT_REG_NODE_STRUCT]], ptr [[I9_I]], i64 [[I15_I]], i32 1
; NOARGPROMOTION-NEXT:    [[I29_I:%.*]] = load i64, ptr [[I28_I]], align 8, !tbaa [[TBAA20:![0-9]+]]
; NOARGPROMOTION-NEXT:    br label %[[MEASURE_EXIT]]
; NOARGPROMOTION:       [[MEASURE_EXIT]]:
; NOARGPROMOTION-NEXT:    [[I31_I:%.*]] = phi i64 [ [[I29_I]], %[[BB27_I]] ], [ 0, %[[BB70]] ], [ -1, %[[BB2_I]] ], [ -1, %[[BB11_I]] ]
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[I4]])
; NOARGPROMOTION-NEXT:    [[I72:%.*]] = trunc i64 [[I31_I]] to i32
; NOARGPROMOTION-NEXT:    store i32 [[I72]], ptr [[I2]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    switch i32 [[I72]], label %[[BB77:.*]] [
; NOARGPROMOTION-NEXT:      i32 -1, label %[[BB73:.*]]
; NOARGPROMOTION-NEXT:      i32 0, label %[[BB75:.*]]
; NOARGPROMOTION-NEXT:    ]
; NOARGPROMOTION:       [[BB73]]:
; NOARGPROMOTION-NEXT:    [[I74:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.4)
; NOARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 1)
; NOARGPROMOTION-NEXT:    unreachable
; NOARGPROMOTION:       [[BB75]]:
; NOARGPROMOTION-NEXT:    [[I76:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.3)
; NOARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 2)
; NOARGPROMOTION-NEXT:    unreachable
; NOARGPROMOTION:       [[BB77]]:
; NOARGPROMOTION-NEXT:    [[I78:%.*]] = shl nuw i32 1, [[I18]]
; NOARGPROMOTION-NEXT:    store i32 [[I78]], ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I79:%.*]] = sitofp i32 [[I72]] to float
; NOARGPROMOTION-NEXT:    [[I80:%.*]] = sitofp i32 [[I78]] to float
; NOARGPROMOTION-NEXT:    [[I81:%.*]] = fdiv fast float [[I79]], [[I80]]
; NOARGPROMOTION-NEXT:    [[I82:%.*]] = fpext float [[I81]] to double
; NOARGPROMOTION-NEXT:    [[I83:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.6, i32 noundef signext [[I72]], double noundef nofpclass(nan inf) [[I82]])
; NOARGPROMOTION-NEXT:    call void @frac_approx(ptr noundef nonnull [[I2]], ptr noundef nonnull [[I3]], i32 noundef signext [[I18]])
; NOARGPROMOTION-NEXT:    [[I84:%.*]] = load i32, ptr [[I2]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I85:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I86:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.7, i32 noundef signext [[I84]], i32 noundef signext [[I85]])
; NOARGPROMOTION-NEXT:    [[I87:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I88:%.*]] = and i32 [[I87]], -2147483647
; NOARGPROMOTION-NEXT:    [[I89:%.*]] = icmp eq i32 [[I88]], 1
; NOARGPROMOTION-NEXT:    [[I90:%.*]] = shl nuw nsw i32 [[I87]], 1
; NOARGPROMOTION-NEXT:    [[I91:%.*]] = icmp slt i32 [[I90]], [[I78]]
; NOARGPROMOTION-NEXT:    [[I92:%.*]] = select i1 [[I89]], i1 [[I91]], i1 false
; NOARGPROMOTION-NEXT:    br i1 [[I92]], label %[[BB93:.*]], label %[[BB97:.*]]
; NOARGPROMOTION:       [[BB93]]:
; NOARGPROMOTION-NEXT:    [[I94:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.37)
; NOARGPROMOTION-NEXT:    [[I95:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I96:%.*]] = shl nsw i32 [[I95]], 1
; NOARGPROMOTION-NEXT:    store i32 [[I96]], ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    br label %[[BB97]]
; NOARGPROMOTION:       [[BB97]]:
; NOARGPROMOTION-NEXT:    [[I98:%.*]] = phi i32 [ [[I96]], %[[BB93]] ], [ [[I87]], %[[BB77]] ]
; NOARGPROMOTION-NEXT:    [[I99:%.*]] = and i32 [[I98]], -2147483647
; NOARGPROMOTION-NEXT:    [[I100:%.*]] = icmp eq i32 [[I99]], 1
; NOARGPROMOTION-NEXT:    br i1 [[I100]], label %[[BB101:.*]], label %[[BB103:.*]]
; NOARGPROMOTION:       [[BB101]]:
; NOARGPROMOTION-NEXT:    [[I102:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.2)
; NOARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 2)
; NOARGPROMOTION-NEXT:    unreachable
; NOARGPROMOTION:       [[BB103]]:
; NOARGPROMOTION-NEXT:    [[I104:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.10, i32 noundef signext [[I98]])
; NOARGPROMOTION-NEXT:    [[I105:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I106:%.*]] = sdiv i32 [[I105]], 2
; NOARGPROMOTION-NEXT:    [[I107:%.*]] = call signext i32 @ipow(i32 noundef signext [[I34]], i32 noundef signext [[I106]])
; NOARGPROMOTION-NEXT:    [[I108:%.*]] = add nsw i32 [[I107]], 1
; NOARGPROMOTION-NEXT:    [[I109:%.*]] = load i32, ptr [[I3]], align 4, !tbaa [[TBAA14]]
; NOARGPROMOTION-NEXT:    [[I110:%.*]] = sdiv i32 [[I109]], 2
; NOARGPROMOTION-NEXT:    [[I111:%.*]] = call signext i32 @ipow(i32 noundef signext [[I34]], i32 noundef signext [[I110]])
; NOARGPROMOTION-NEXT:    [[I112:%.*]] = add nsw i32 [[I111]], -1
; NOARGPROMOTION-NEXT:    [[I113:%.*]] = call signext i32 @gcd(i32 noundef signext [[I12]], i32 noundef signext [[I108]])
; NOARGPROMOTION-NEXT:    [[I114:%.*]] = call signext i32 @gcd(i32 noundef signext [[I12]], i32 noundef signext [[I112]])
; NOARGPROMOTION-NEXT:    [[I115:%.*]] = call i32 @llvm.smax.i32(i32 [[I113]], i32 [[I114]])
; NOARGPROMOTION-NEXT:    [[I116:%.*]] = icmp slt i32 [[I115]], [[I12]]
; NOARGPROMOTION-NEXT:    [[I117:%.*]] = icmp sgt i32 [[I115]], 1
; NOARGPROMOTION-NEXT:    [[I118:%.*]] = and i1 [[I116]], [[I117]]
; NOARGPROMOTION-NEXT:    br i1 [[I118]], label %[[BB119:.*]], label %[[BB122:.*]]
; NOARGPROMOTION:       [[BB119]]:
; NOARGPROMOTION-NEXT:    [[I120:%.*]] = udiv i32 [[I12]], [[I115]]
; NOARGPROMOTION-NEXT:    [[I121:%.*]] = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.11.38, i32 noundef signext [[I12]], i32 noundef signext [[I115]], i32 noundef signext [[I120]])
; NOARGPROMOTION-NEXT:    call void @delete_qureg(ptr noundef nonnull [[I]])
; NOARGPROMOTION-NEXT:    br label %[[BB124]]
; NOARGPROMOTION:       [[BB122]]:
; NOARGPROMOTION-NEXT:    [[I123:%.*]] = call i32 @puts(ptr nonnull dereferenceable(1) @str.1.39)
; NOARGPROMOTION-NEXT:    call void @exit(i32 noundef signext 0)
; NOARGPROMOTION-NEXT:    unreachable
; NOARGPROMOTION:       [[BB124]]:
; NOARGPROMOTION-NEXT:    [[I125:%.*]] = phi i32 [ 3, %[[BB6]] ], [ 3, %[[BB14]] ], [ 0, %[[BB119]] ]
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[I3]])
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr nonnull [[I2]])
; NOARGPROMOTION-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr nonnull [[I]])
; NOARGPROMOTION-NEXT:    ret i32 [[I125]]
;
bb:
  %i = alloca %struct.reg_struct, align 8
  %i2 = alloca i32, align 4
  %i3 = alloca i32, align 4
  %i4 = alloca %struct.reg_struct, align 8
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %i)
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %i2)
  call void @llvm.lifetime.start.p0(i64 4, ptr nonnull %i3)
  tail call void @spec_srand(i32 noundef signext 26)
  %i5 = icmp eq i32 %arg, 1
  br i1 %i5, label %bb6, label %bb8

bb6:                                              ; preds = %bb
  %i7 = tail call i32 @puts(ptr nonnull dereferenceable(1) @str.6)
  br label %bb124

bb8:                                              ; preds = %bb
  %i9 = getelementptr inbounds ptr, ptr %arg1, i64 1
  %i10 = load ptr, ptr %i9, align 8, !tbaa !26
  %i11 = tail call i64 @strtol(ptr nocapture noundef nonnull %i10, ptr noundef null, i32 noundef signext 10)
  %i12 = trunc i64 %i11 to i32
  %i13 = icmp slt i32 %i12, 15
  br i1 %i13, label %bb14, label %bb16

bb14:                                             ; preds = %bb8
  %i15 = tail call i32 @puts(ptr nonnull dereferenceable(1) @str.5)
  br label %bb124

bb16:                                             ; preds = %bb8
  %i17 = mul nuw nsw i32 %i12, %i12
  %i18 = tail call signext i32 @getwidth(i32 noundef signext %i17)
  %i19 = tail call signext i32 @getwidth(i32 noundef signext %i12)
  %i20 = mul nsw i32 %i19, 3
  %i21 = add i32 %i20, 2
  %i22 = add i32 %i21, %i18
  %i23 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.2.35, i32 noundef signext %i12, i32 noundef signext %i22)
  %i24 = icmp sgt i32 %arg, 2
  br i1 %i24, label %bb25, label %bb30

bb25:                                             ; preds = %bb16
  %i26 = getelementptr inbounds ptr, ptr %arg1, i64 2
  %i27 = load ptr, ptr %i26, align 8, !tbaa !26
  %i28 = tail call i64 @strtol(ptr nocapture noundef nonnull %i27, ptr noundef null, i32 noundef signext 10)
  %i29 = trunc i64 %i28 to i32
  br label %bb30

bb30:                                             ; preds = %bb25, %bb16
  %i31 = phi i32 [ %i29, %bb25 ], [ 0, %bb16 ]
  %i32 = and i64 %i11, 2147483647
  br label %bb33

bb33:                                             ; preds = %bb39, %bb30
  %i34 = phi i32 [ %i31, %bb30 ], [ %i44, %bb39 ]
  %i35 = tail call signext i32 @gcd(i32 noundef signext %i12, i32 noundef signext %i34)
  %i36 = icmp sgt i32 %i35, 1
  %i37 = icmp slt i32 %i34, 2
  %i38 = or i1 %i37, %i36
  br i1 %i38, label %bb39, label %bb45

bb39:                                             ; preds = %bb33
  %i40 = tail call fast nofpclass(nan inf) double @spec_rand()
  %i41 = fmul fast double %i40, 0x41DFFFFFFFC00000
  %i42 = fptosi double %i41 to i64
  %i43 = srem i64 %i42, %i32
  %i44 = trunc nsw i64 %i43 to i32
  br label %bb33, !llvm.loop !28

bb45:                                             ; preds = %bb33
  %i46 = tail call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.3.36, i32 noundef signext %i34)
  call void @new_qureg(ptr dead_on_unwind noalias nonnull writable align 8 %i, i64 noundef 0, i32 noundef signext %i18)
  %i47 = icmp sgt i32 %i18, 0
  br i1 %i47, label %bb48, label %bb52

bb48:                                             ; preds = %bb48, %bb45
  %i49 = phi i32 [ %i50, %bb48 ], [ 0, %bb45 ]
  call void @hadamard(i32 noundef signext %i49, ptr noundef nonnull %i)
  %i50 = add nuw nsw i32 %i49, 1
  %i51 = icmp eq i32 %i50, %i18
  br i1 %i51, label %bb52, label %bb48, !llvm.loop !29

bb52:                                             ; preds = %bb48, %bb45
  call void @addscratch(i32 noundef signext %i21, ptr noundef nonnull %i)
  call void @exp_mod_n(i32 noundef signext %i12, i32 noundef signext %i34, i32 noundef signext %i18, i32 noundef signext %i19, ptr noundef nonnull %i)
  %i53 = icmp sgt i32 %i19, -1
  br i1 %i53, label %bb54, label %bb61

bb54:                                             ; preds = %bb52
  %i55 = call i32 @llvm.smax.i32(i32 %i21, i32 1)
  br label %bb56

bb56:                                             ; preds = %bb56, %bb54
  %i57 = phi i32 [ %i59, %bb56 ], [ 0, %bb54 ]
  %i58 = call signext i32 @bmeasure(i32 noundef signext 0, ptr noundef nonnull %i)
  %i59 = add nuw nsw i32 %i57, 1
  %i60 = icmp eq i32 %i59, %i55
  br i1 %i60, label %bb61, label %bb56, !llvm.loop !30

bb61:                                             ; preds = %bb56, %bb52
  call void @qft(i32 noundef signext %i18, ptr noundef nonnull %i)
  %i62 = sdiv i32 %i18, 2
  %i63 = icmp sgt i32 %i18, 1
  br i1 %i63, label %bb64, label %bb70

bb64:                                             ; preds = %bb64, %bb61
  %i65 = phi i32 [ %i68, %bb64 ], [ 0, %bb61 ]
  %i66 = xor i32 %i65, -1
  %i67 = add nsw i32 %i18, %i66
  call void @cnot(i32 noundef signext %i65, i32 noundef signext %i67, ptr noundef nonnull %i)
  call void @cnot(i32 noundef signext %i67, i32 noundef signext %i65, ptr noundef nonnull %i)
  call void @cnot(i32 noundef signext %i65, i32 noundef signext %i67, ptr noundef nonnull %i)
  %i68 = add nuw nsw i32 %i65, 1
  %i69 = icmp eq i32 %i68, %i62
  br i1 %i69, label %bb70, label %bb64, !llvm.loop !31

bb70:                                             ; preds = %bb64, %bb61
  call void @llvm.lifetime.start.p0(i64 32, ptr nonnull %i4)
  call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(32) %i4, ptr noundef nonnull align 8 dereferenceable(32) %i, i64 32, i1 false), !tbaa !32, !tbaa.struct !33
  %i71 = call i64 @measure(ptr noundef nonnull %i4)
  call void @llvm.lifetime.end.p0(i64 32, ptr nonnull %i4)
  %i72 = trunc i64 %i71 to i32
  store i32 %i72, ptr %i2, align 4, !tbaa !11
  switch i32 %i72, label %bb77 [
  i32 -1, label %bb73
  i32 0, label %bb75
  ]

bb73:                                             ; preds = %bb70
  %i74 = call i32 @puts(ptr nonnull dereferenceable(1) @str.4)
  call void @exit(i32 noundef signext 1)
  unreachable

bb75:                                             ; preds = %bb70
  %i76 = call i32 @puts(ptr nonnull dereferenceable(1) @str.3)
  call void @exit(i32 noundef signext 2)
  unreachable

bb77:                                             ; preds = %bb70
  %i78 = shl nuw i32 1, %i18
  store i32 %i78, ptr %i3, align 4, !tbaa !11
  %i79 = sitofp i32 %i72 to float
  %i80 = sitofp i32 %i78 to float
  %i81 = fdiv fast float %i79, %i80
  %i82 = fpext float %i81 to double
  %i83 = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.6, i32 noundef signext %i72, double noundef nofpclass(nan inf) %i82)
  call void @frac_approx(ptr noundef nonnull %i2, ptr noundef nonnull %i3, i32 noundef signext %i18)
  %i84 = load i32, ptr %i2, align 4, !tbaa !11
  %i85 = load i32, ptr %i3, align 4, !tbaa !11
  %i86 = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.7, i32 noundef signext %i84, i32 noundef signext %i85)
  %i87 = load i32, ptr %i3, align 4, !tbaa !11
  %i88 = and i32 %i87, -2147483647
  %i89 = icmp eq i32 %i88, 1
  %i90 = shl nuw nsw i32 %i87, 1
  %i91 = icmp slt i32 %i90, %i78
  %i92 = select i1 %i89, i1 %i91, i1 false
  br i1 %i92, label %bb93, label %bb97

bb93:                                             ; preds = %bb77
  %i94 = call i32 @puts(ptr nonnull dereferenceable(1) @str.37)
  %i95 = load i32, ptr %i3, align 4, !tbaa !11
  %i96 = shl nsw i32 %i95, 1
  store i32 %i96, ptr %i3, align 4, !tbaa !11
  br label %bb97

bb97:                                             ; preds = %bb93, %bb77
  %i98 = phi i32 [ %i96, %bb93 ], [ %i87, %bb77 ]
  %i99 = and i32 %i98, -2147483647
  %i100 = icmp eq i32 %i99, 1
  br i1 %i100, label %bb101, label %bb103

bb101:                                            ; preds = %bb97
  %i102 = call i32 @puts(ptr nonnull dereferenceable(1) @str.2)
  call void @exit(i32 noundef signext 2)
  unreachable

bb103:                                            ; preds = %bb97
  %i104 = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.10, i32 noundef signext %i98)
  %i105 = load i32, ptr %i3, align 4, !tbaa !11
  %i106 = sdiv i32 %i105, 2
  %i107 = call signext i32 @ipow(i32 noundef signext %i34, i32 noundef signext %i106)
  %i108 = add nsw i32 %i107, 1
  %i109 = load i32, ptr %i3, align 4, !tbaa !11
  %i110 = sdiv i32 %i109, 2
  %i111 = call signext i32 @ipow(i32 noundef signext %i34, i32 noundef signext %i110)
  %i112 = add nsw i32 %i111, -1
  %i113 = call signext i32 @gcd(i32 noundef signext %i12, i32 noundef signext %i108)
  %i114 = call signext i32 @gcd(i32 noundef signext %i12, i32 noundef signext %i112)
  %i115 = call i32 @llvm.smax.i32(i32 %i113, i32 %i114)
  %i116 = icmp slt i32 %i115, %i12
  %i117 = icmp sgt i32 %i115, 1
  %i118 = and i1 %i116, %i117
  br i1 %i118, label %bb119, label %bb122

bb119:                                            ; preds = %bb103
  %i120 = udiv i32 %i12, %i115
  %i121 = call signext i32 (ptr, ...) @printf(ptr noundef nonnull dereferenceable(1) @.str.11.38, i32 noundef signext %i12, i32 noundef signext %i115, i32 noundef signext %i120)
  call void @delete_qureg(ptr noundef nonnull %i)
  br label %bb124

bb122:                                            ; preds = %bb103
  %i123 = call i32 @puts(ptr nonnull dereferenceable(1) @str.1.39)
  call void @exit(i32 noundef signext 0)
  unreachable

bb124:                                            ; preds = %bb119, %bb14, %bb6
  %i125 = phi i32 [ 3, %bb6 ], [ 3, %bb14 ], [ 0, %bb119 ]
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %i3)
  call void @llvm.lifetime.end.p0(i64 4, ptr nonnull %i2)
  call void @llvm.lifetime.end.p0(i64 32, ptr nonnull %i)
  ret i32 %i125
}

declare dso_local void @exit(i32 noundef signext)
declare dso_local noundef i32 @puts(ptr nocapture noundef readonly) local_unnamed_addr
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg) #1
declare i32 @llvm.smax.i32(i32, i32)
declare void @llvm.va_start.p0(ptr)

!11 = !{!12, !12, i64 0, i64 4}
!12 = !{!13, i64 4, !"int"}
!13 = !{!14, i64 1, !"omnipotent char"}
!14 = !{!"Simple C/C++ TBAA"}
!15 = !{!16, !12, i64 4, i64 4}
!16 = !{!13, i64 32, !"reg_struct", !12, i64 0, i64 4, !12, i64 4, i64 4, !12, i64 8, i64 4, !17, i64 16, i64 8, !19, i64 24, i64 8}
!17 = !{!18, i64 8, !"p1 struct reg_node_struct"}
!18 = !{!13, i64 8, !"any pointer"}
!19 = !{!18, i64 8, !"p1 int"}
!20 = !{!16, !17, i64 16, i64 8}
!21 = distinct !{!21, !22}
!22 = !{!"llvm.loop.mustprogress"}
!23 = !{!24, !25, i64 8, i64 8}
!24 = !{!13, i64 16, !"reg_node_struct", !13, i64 0, i64 8, !25, i64 8, i64 8}
!25 = !{!13, i64 8, !"long long"}
!26 = !{!27, !27, i64 0, i64 8}
!27 = !{!13, i64 8, !"long"}
!28 = distinct !{!28, !22}
!29 = distinct !{!29, !22}
!30 = distinct !{!30, !22}
!31 = distinct !{!31, !22}
!32 = !{!17, !17, i64 0, i64 8}
!33 = !{!19, !19, i64 0, i64 8}
;.
; ARGPROMOTION: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0, i64 8}
; ARGPROMOTION: [[META1]] = !{[[META2:![0-9]+]], i64 8, !"long"}
; ARGPROMOTION: [[META2]] = !{[[META3:![0-9]+]], i64 1, !"omnipotent char"}
; ARGPROMOTION: [[META3]] = !{!"Simple C/C++ TBAA"}
; ARGPROMOTION: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]]}
; ARGPROMOTION: [[META5]] = !{!"llvm.loop.mustprogress"}
; ARGPROMOTION: [[LOOP6]] = distinct !{[[LOOP6]], [[META5]]}
; ARGPROMOTION: [[LOOP7]] = distinct !{[[LOOP7]], [[META5]]}
; ARGPROMOTION: [[LOOP8]] = distinct !{[[LOOP8]], [[META5]]}
; ARGPROMOTION: [[TBAA9]] = !{[[META10:![0-9]+]], [[META10]], i64 0, i64 8}
; ARGPROMOTION: [[META10]] = !{[[META11:![0-9]+]], i64 8, !"p1 struct reg_node_struct"}
; ARGPROMOTION: [[META11]] = !{[[META2]], i64 8, !"any pointer"}
; ARGPROMOTION: [[TBAA_STRUCT12]] = !{[[META13:![0-9]+]], [[META13]], i64 0, i64 8}
; ARGPROMOTION: [[META13]] = !{[[META11]], i64 8, !"p1 int"}
; ARGPROMOTION: [[TBAA14]] = !{[[META15:![0-9]+]], [[META15]], i64 0, i64 4}
; ARGPROMOTION: [[META15]] = !{[[META2]], i64 4, !"int"}
; ARGPROMOTION: [[LOOP16]] = distinct !{[[LOOP16]], [[META5]]}
; ARGPROMOTION: [[TBAA17]] = !{[[META18:![0-9]+]], [[META19:![0-9]+]], i64 8, i64 8}
; ARGPROMOTION: [[META18]] = !{[[META2]], i64 16, !"reg_node_struct", [[META2]], i64 0, i64 8, [[META19]], i64 8, i64 8}
; ARGPROMOTION: [[META19]] = !{[[META2]], i64 8, !"long long"}
;.
; NOARGPROMOTION: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0, i64 8}
; NOARGPROMOTION: [[META1]] = !{[[META2:![0-9]+]], i64 8, !"long"}
; NOARGPROMOTION: [[META2]] = !{[[META3:![0-9]+]], i64 1, !"omnipotent char"}
; NOARGPROMOTION: [[META3]] = !{!"Simple C/C++ TBAA"}
; NOARGPROMOTION: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]]}
; NOARGPROMOTION: [[META5]] = !{!"llvm.loop.mustprogress"}
; NOARGPROMOTION: [[LOOP6]] = distinct !{[[LOOP6]], [[META5]]}
; NOARGPROMOTION: [[LOOP7]] = distinct !{[[LOOP7]], [[META5]]}
; NOARGPROMOTION: [[LOOP8]] = distinct !{[[LOOP8]], [[META5]]}
; NOARGPROMOTION: [[TBAA9]] = !{[[META10:![0-9]+]], [[META10]], i64 0, i64 8}
; NOARGPROMOTION: [[META10]] = !{[[META11:![0-9]+]], i64 8, !"p1 struct reg_node_struct"}
; NOARGPROMOTION: [[META11]] = !{[[META2]], i64 8, !"any pointer"}
; NOARGPROMOTION: [[TBAA_STRUCT12]] = !{[[META13:![0-9]+]], [[META13]], i64 0, i64 8}
; NOARGPROMOTION: [[META13]] = !{[[META11]], i64 8, !"p1 int"}
; NOARGPROMOTION: [[TBAA14]] = !{[[META15:![0-9]+]], [[META15]], i64 0, i64 4}
; NOARGPROMOTION: [[META15]] = !{[[META2]], i64 4, !"int"}
; NOARGPROMOTION: [[TBAA16]] = !{[[META17:![0-9]+]], [[META15]], i64 4, i64 4}
; NOARGPROMOTION: [[META17]] = !{[[META2]], i64 32, !"reg_struct", [[META15]], i64 0, i64 4, [[META15]], i64 4, i64 4, [[META15]], i64 8, i64 4, [[META10]], i64 16, i64 8, [[META13]], i64 24, i64 8}
; NOARGPROMOTION: [[TBAA18]] = !{[[META17]], [[META10]], i64 16, i64 8}
; NOARGPROMOTION: [[LOOP19]] = distinct !{[[LOOP19]], [[META5]]}
; NOARGPROMOTION: [[TBAA20]] = !{[[META21:![0-9]+]], [[META22:![0-9]+]], i64 8, i64 8}
; NOARGPROMOTION: [[META21]] = !{[[META2]], i64 16, !"reg_node_struct", [[META2]], i64 0, i64 8, [[META22]], i64 8, i64 8}
; NOARGPROMOTION: [[META22]] = !{[[META2]], i64 8, !"long long"}
;.
