; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -mtriple=riscv64-unknown-linux-gnu -O3 -inline-threshold=20 -inline-leaf-threshold=true -S | FileCheck --check-prefix=CHECK_LEAF %s
; RUN: opt < %s -mtriple=riscv64-unknown-linux-gnu -O3 -inline-threshold=20 -inline-leaf-threshold=false -S | FileCheck --check-prefix=CHECK_NOLEAF %s

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"

; Check that the inline-leaf-threshold changes how leaf functions are considered
; in inline cost analysis.

@a = global i32 4

define i32 @inner() {
; CHECK_LEAF-LABEL: define range(i32 0, -1) i32 @inner(
; CHECK_LEAF-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK_LEAF-NEXT:    [[A1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X1:%.*]] = shl i32 [[A1]], 1
; CHECK_LEAF-NEXT:    ret i32 [[X1]]
;
; CHECK_NOLEAF-LABEL: define range(i32 0, -1) i32 @inner(
; CHECK_NOLEAF-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK_NOLEAF-NEXT:    [[A1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X1:%.*]] = shl i32 [[A1]], 1
; CHECK_NOLEAF-NEXT:    ret i32 [[X1]]
;
  %a1 = load volatile i32, ptr @a
  %x1 = add i32 %a1,  %a1
  ret i32 %x1
}

define i32 @inner2() {
; CHECK_LEAF-LABEL: define i32 @inner2(
; CHECK_LEAF-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK_LEAF-NEXT:    [[A1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X1:%.*]] = shl i32 [[A1]], 1
; CHECK_LEAF-NEXT:    [[A2:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X2:%.*]] = add i32 [[X1]], [[A2]]
; CHECK_LEAF-NEXT:    [[A3:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X3:%.*]] = add i32 [[X2]], [[A3]]
; CHECK_LEAF-NEXT:    [[A4:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A5:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X5:%.*]] = add i32 [[X3]], [[A5]]
; CHECK_LEAF-NEXT:    [[A6:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X6:%.*]] = add i32 [[X5]], [[A6]]
; CHECK_LEAF-NEXT:    [[A7:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X7:%.*]] = add i32 [[X6]], [[A7]]
; CHECK_LEAF-NEXT:    [[A8:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X8:%.*]] = add i32 [[X7]], [[A8]]
; CHECK_LEAF-NEXT:    ret i32 [[X8]]
;
; CHECK_NOLEAF-LABEL: define i32 @inner2(
; CHECK_NOLEAF-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK_NOLEAF-NEXT:    [[A1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X1:%.*]] = shl i32 [[A1]], 1
; CHECK_NOLEAF-NEXT:    [[A2:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X2:%.*]] = add i32 [[X1]], [[A2]]
; CHECK_NOLEAF-NEXT:    [[A3:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X3:%.*]] = add i32 [[X2]], [[A3]]
; CHECK_NOLEAF-NEXT:    [[A4:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[A5:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X5:%.*]] = add i32 [[X3]], [[A5]]
; CHECK_NOLEAF-NEXT:    [[A6:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X6:%.*]] = add i32 [[X5]], [[A6]]
; CHECK_NOLEAF-NEXT:    [[A7:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X7:%.*]] = add i32 [[X6]], [[A7]]
; CHECK_NOLEAF-NEXT:    [[A8:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X8:%.*]] = add i32 [[X7]], [[A8]]
; CHECK_NOLEAF-NEXT:    ret i32 [[X8]]
;
  %a1 = load volatile i32, ptr @a
  %x1 = add i32 %a1,  %a1
  %a2 = load volatile i32, ptr @a
  %x2 = add i32 %x1, %a2
  %a3 = load volatile i32, ptr @a
  %x3 = add i32 %x2, %a3
  %a4 = load volatile i32, ptr @a
  %x4 = add i32 %x3, %a4
  %a5 = load volatile i32, ptr @a
  %x5 = add i32 %x3, %a5
  %a6 = load volatile i32, ptr @a
  %x6 = add i32 %x5, %a6
  %a7 = load volatile i32, ptr @a
  %x7 = add i32 %x6, %a7
  %a8 = load volatile i32, ptr @a
  %x8 = add i32 %x7, %a8
  ret i32 %x8
}

define i32 @outer() optsize {
; CHECK_LEAF-LABEL: define i32 @outer(
; CHECK_LEAF-SAME: ) local_unnamed_addr #[[ATTR1:[0-9]+]] {
; CHECK_LEAF-NEXT:    [[A1_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X1_I:%.*]] = shl i32 [[A1_I]], 2
; CHECK_LEAF-NEXT:    [[Y:%.*]] = mul i32 [[X1_I]], [[X1_I]]
; CHECK_LEAF-NEXT:    ret i32 [[Y]]
;
; CHECK_NOLEAF-LABEL: define i32 @outer(
; CHECK_NOLEAF-SAME: ) local_unnamed_addr #[[ATTR1:[0-9]+]] {
; CHECK_NOLEAF-NEXT:    [[A1_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X1_I:%.*]] = shl i32 [[A1_I]], 2
; CHECK_NOLEAF-NEXT:    [[Y:%.*]] = mul i32 [[X1_I]], [[X1_I]]
; CHECK_NOLEAF-NEXT:    ret i32 [[Y]]
;
  %r = call i32 @inner()
  %x = add i32 %r, %r
  %y = mul i32 %x, %x
  ret i32 %y
}

define i32 @outer2() optsize {
; CHECK_LEAF-LABEL: define i32 @outer2(
; CHECK_LEAF-SAME: ) local_unnamed_addr #[[ATTR1]] {
; CHECK_LEAF-NEXT:    [[A1_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X1_I:%.*]] = shl i32 [[A1_I]], 1
; CHECK_LEAF-NEXT:    [[A2_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X2_I:%.*]] = add i32 [[X1_I]], [[A2_I]]
; CHECK_LEAF-NEXT:    [[A3_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X3_I:%.*]] = add i32 [[X2_I]], [[A3_I]]
; CHECK_LEAF-NEXT:    [[A4_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A5_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X5_I:%.*]] = add i32 [[X3_I]], [[A5_I]]
; CHECK_LEAF-NEXT:    [[A6_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X6_I:%.*]] = add i32 [[X5_I]], [[A6_I]]
; CHECK_LEAF-NEXT:    [[A7_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X7_I:%.*]] = add i32 [[X6_I]], [[A7_I]]
; CHECK_LEAF-NEXT:    [[A8_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X8_I:%.*]] = add i32 [[X7_I]], [[A8_I]]
; CHECK_LEAF-NEXT:    ret i32 [[X8_I]]
;
; CHECK_NOLEAF-LABEL: define i32 @outer2(
; CHECK_NOLEAF-SAME: ) local_unnamed_addr #[[ATTR2:[0-9]+]] {
; CHECK_NOLEAF-NEXT:    [[R:%.*]] = tail call i32 @inner2()
; CHECK_NOLEAF-NEXT:    ret i32 [[R]]
;
  %r = call i32 @inner2()
  ret i32 %r
}

define i32 @run() {
; CHECK_LEAF-LABEL: define i32 @run(
; CHECK_LEAF-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK_LEAF-NEXT:    [[A1_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X1_I_I:%.*]] = shl i32 [[A1_I_I]], 2
; CHECK_LEAF-NEXT:    [[Y_I:%.*]] = mul i32 [[X1_I_I]], [[X1_I_I]]
; CHECK_LEAF-NEXT:    [[A1_I_I1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X1_I_I2:%.*]] = shl i32 [[A1_I_I1]], 1
; CHECK_LEAF-NEXT:    [[A2_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X2_I_I:%.*]] = add i32 [[X1_I_I2]], [[A2_I_I]]
; CHECK_LEAF-NEXT:    [[A3_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A4_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A5_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A6_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A7_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[A8_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_LEAF-NEXT:    [[X3_I_I:%.*]] = add i32 [[X2_I_I]], [[Y_I]]
; CHECK_LEAF-NEXT:    [[X5_I_I:%.*]] = add i32 [[X3_I_I]], [[A3_I_I]]
; CHECK_LEAF-NEXT:    [[X6_I_I:%.*]] = add i32 [[X5_I_I]], [[A5_I_I]]
; CHECK_LEAF-NEXT:    [[X7_I_I:%.*]] = add i32 [[X6_I_I]], [[A6_I_I]]
; CHECK_LEAF-NEXT:    [[X8_I_I:%.*]] = add i32 [[X7_I_I]], [[A7_I_I]]
; CHECK_LEAF-NEXT:    [[C:%.*]] = add i32 [[X8_I_I]], [[A8_I_I]]
; CHECK_LEAF-NEXT:    ret i32 [[C]]
;
; CHECK_NOLEAF-LABEL: define i32 @run(
; CHECK_NOLEAF-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
; CHECK_NOLEAF-NEXT:    [[A1_I_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_NOLEAF-NEXT:    [[X1_I_I:%.*]] = shl i32 [[A1_I_I]], 2
; CHECK_NOLEAF-NEXT:    [[Y_I:%.*]] = mul i32 [[X1_I_I]], [[X1_I_I]]
; CHECK_NOLEAF-NEXT:    [[R_I:%.*]] = tail call i32 @inner2()
; CHECK_NOLEAF-NEXT:    [[C:%.*]] = add i32 [[Y_I]], [[R_I]]
; CHECK_NOLEAF-NEXT:    ret i32 [[C]]
;
  %a = call i32 @outer()
  %b = call i32 @outer2()
  %c = add i32 %a, %b
  ret i32 %c
}
