; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; Test that inlining is either enabled or disabled by cost for value pressure
; RUN: opt < %s -O3 -inline-threshold=500 -value-liveness-enable=3 -S  | FileCheck %s -check-prefix=CHECK_VLP_FAIL
; RUN: opt < %s -O3 -inline-threshold=700 -value-liveness-enable=3 -S  | FileCheck %s -check-prefix=CHECK_VLP_SUCCESS

@a = global i32 4

define i32 @foo(i32 %a) #0 {
; CHECK_VLP_FAIL-LABEL: define i32 @foo(
; CHECK_VLP_FAIL-SAME: i32 [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK_VLP_FAIL-NEXT:  [[ENTRY:.*:]]
; CHECK_VLP_FAIL-NEXT:    [[A1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_VLP_FAIL-NEXT:    [[X1:%.*]] = add i32 [[A1]], [[A]]
; CHECK_VLP_FAIL-NEXT:    ret i32 [[X1]]
;
; CHECK_VLP_SUCCESS-LABEL: define i32 @foo(
; CHECK_VLP_SUCCESS-SAME: i32 [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK_VLP_SUCCESS-NEXT:  [[ENTRY:.*:]]
; CHECK_VLP_SUCCESS-NEXT:    [[A1:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_VLP_SUCCESS-NEXT:    [[X1:%.*]] = add i32 [[A1]], [[A]]
; CHECK_VLP_SUCCESS-NEXT:    ret i32 [[X1]]
;
entry:
  %a1 = load volatile i32, ptr @a
  %x1 = add i32 %a1,  %a
  ret i32 %x1
}

; Function Attrs: nounwind readnone uwtable
define i32 @bar(i32 %a) #0 {
; CHECK_VLP_FAIL-LABEL: define i32 @bar(
; CHECK_VLP_FAIL-SAME: i32 [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
; CHECK_VLP_FAIL-NEXT:  [[ENTRY:.*:]]
; CHECK_VLP_FAIL-NEXT:    [[G:%.*]] = add i32 [[A]], 6
; CHECK_VLP_FAIL-NEXT:    [[I:%.*]] = tail call i32 @foo(i32 [[G]]) #[[ATTR1:[0-9]+]]
; CHECK_VLP_FAIL-NEXT:    [[FACTOR:%.*]] = mul i32 [[A]], 6
; CHECK_VLP_FAIL-NEXT:    [[P:%.*]] = add i32 [[A]], 28
; CHECK_VLP_FAIL-NEXT:    [[B:%.*]] = add i32 [[P]], [[FACTOR]]
; CHECK_VLP_FAIL-NEXT:    [[Q:%.*]] = add i32 [[B]], [[I]]
; CHECK_VLP_FAIL-NEXT:    ret i32 [[Q]]
;
; CHECK_VLP_SUCCESS-LABEL: define i32 @bar(
; CHECK_VLP_SUCCESS-SAME: i32 [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
; CHECK_VLP_SUCCESS-NEXT:  [[ENTRY:.*:]]
; CHECK_VLP_SUCCESS-NEXT:    [[A1_I:%.*]] = load volatile i32, ptr @a, align 4
; CHECK_VLP_SUCCESS-NEXT:    [[FACTOR:%.*]] = shl i32 [[A]], 3
; CHECK_VLP_SUCCESS-NEXT:    [[B:%.*]] = add i32 [[FACTOR]], 34
; CHECK_VLP_SUCCESS-NEXT:    [[Q:%.*]] = add i32 [[B]], [[A1_I]]
; CHECK_VLP_SUCCESS-NEXT:    ret i32 [[Q]]
;
entry:
  %b = add i32 %a, 1
  %c = add i32 %b, 1
  %d = add i32 %c, 1
  %e = add i32 %d, 1
  %f = add i32 %e, 1
  %g = add i32 %f, 1
  %h = add i32 %g, 1
  %i = tail call i32 @foo(i32 %g) "function-inline-cost"="749"
  %k = add i32 %h, %i
  %l = add i32 %g, %k
  %m = add i32 %f, %l
  %n = add i32 %e, %m
  %o = add i32 %d, %n
  %p = add i32 %c, %o
  %q = add i32 %b, %p
  ret i32 %q
}

attributes #0 = { nounwind readnone uwtable }
