; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

define <vscale x 4 x i32> @test_vaadd_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vaadd_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vaadd_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vaadd_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vaadd_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vaadd_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vaaddu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vaaddu_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vaaddu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vaaddu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vaaddu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vaaddu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vasub_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vasub_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vasub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vasub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

; vasub is not commutable
define <vscale x 4 x i32> @test_vasub_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vasub_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vasub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vasub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vasubu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vasubu_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vasubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vasubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

; vasubu is not commutable
define <vscale x 4 x i32> @test_vasubu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vasubu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vasubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vasubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vadd_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vadd_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vadd_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vadd_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vadd_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vadd_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vand_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vand_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vand_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vand_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vand_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vand_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vdiv_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vdiv_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vdiv.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vdiv.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vdiv is not commutable
define <vscale x 4 x i32> @test_vdiv_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vdiv_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vdiv.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vdiv.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vdivu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vdivu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vdivu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vdivu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vdivu is not commutable
define <vscale x 4 x i32> @test_vdivu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vdivu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vdivu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vdivu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmax_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmax_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmax_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmax_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmax_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmax_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmaxu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmaxu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmaxu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmaxu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmaxu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmaxu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmin_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmin_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmin_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmin_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmin_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmin_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vminu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vminu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vminu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vminu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vminu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vminu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmul_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmul_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmul_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmul_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmul_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmul_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmulh_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmulh_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmulh_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmulh_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmulh_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmulh_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmulhu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmulhu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmulhu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmulhu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmulhu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmulhu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmulhsu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmulhsu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vmulhsu is not commutable.
define <vscale x 4 x i32> @test_vmulhsu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmulhsu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vor_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vor_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vor_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vor_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vor_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vor_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vrem_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vrem_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vrem.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vrem.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vrem is not commutable
define <vscale x 4 x i32> @test_vrem_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vrem_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vrem.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vrem.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vremu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vremu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vremu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vremu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vremu is not commutable
define <vscale x 4 x i32> @test_vremu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vremu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vremu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vremu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsadd_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsadd_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsadd_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsadd_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vsadd_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vsadd_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsaddu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsaddu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsaddu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsaddu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vsaddu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vsaddu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsmul_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsmul_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsmul_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsmul_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vsmul_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vsmul_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vssub_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vssub_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vssub.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vssub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vssub is not commutable
define <vscale x 4 x i32> @test_vssub_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vssub_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vssub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vssub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vssubu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vssubu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vssubu.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vssubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

; vssubu is not commutable
define <vscale x 4 x i32> @test_vssubu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vssubu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vssubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vssubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsub_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsub_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsub_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsub_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vrsub.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vsub_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vsub_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i64> @test_vwadd_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwadd_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwadd_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwadd_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwadd_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vwadd_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwadd_w_rhs(<vscale x 4 x i64> %x, i32 %y) {
; CHECK-LABEL: @test_vwadd_w_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.nxv4i64.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwaddu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwaddu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwaddu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwaddu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwaddu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vwaddu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwaddu_w_rhs(<vscale x 4 x i64> %x, i32 %y) {
; CHECK-LABEL: @test_vwaddu_w_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwaddu.w.nxv4i64.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwaddu.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmul_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwmul_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmul_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwmul_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwmul_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vwmul_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmulsu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwmulsu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

; vwmulsu is not commutable.
define <vscale x 4 x i64> @test_vwmulsu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwmulsu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmulu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwmulu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmulu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwmulu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwmulu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vwmulu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwsub_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwsub_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

; vwsub is not commutable
define <vscale x 4 x i64> @test_vwsub_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwsub_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwsub_w_rhs(<vscale x 4 x i64> %x, i32 %y) {
; CHECK-LABEL: @test_vwsub_w_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwsub.w.nxv4i64.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwsub.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwsubu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwsubu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

; vwsubu is not commutable
define <vscale x 4 x i64> @test_vwsubu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vwsubu_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwsubu_w_rhs(<vscale x 4 x i64> %x, i32 %y) {
; CHECK-LABEL: @test_vwsubu_w_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwsubu.w.nxv4i64.i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwsubu.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> undef, <vscale x 4 x i64> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i32> @test_vxor_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vxor_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vxor_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vxor_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vxor_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vxor_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x float> @test_vfadd_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfadd_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfadd_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfadd_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfadd_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfadd_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmax_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfmax_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmax_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfmax_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfmax_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfmax_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmin_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfmin_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmin_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfmin_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfmin_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfmin_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmul_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfmul_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmul_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfmul_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfmul_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfmul_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfdiv_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfdiv_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfdiv_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfdiv_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfrdiv.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfdiv_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfdiv_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfsub_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsub_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfsub_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsub_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfrsub.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfsub_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfsub_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %x, i64 7, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfsgnj_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsgnj_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsgnj.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsgnj.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x float> %b
}

; vfsgnj is not commutable
define <vscale x 4 x float> @test_vfsgnj_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsgnj_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsgnj.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], <vscale x 4 x float> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsgnj.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfsgnjn_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsgnjn_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsgnjn.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsgnjn.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x float> %b
}

; vfsgnjn is not commutable
define <vscale x 4 x float> @test_vfsgnjn_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsgnjn_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsgnjn.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], <vscale x 4 x float> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsgnjn.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfsgnjx_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsgnjx_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsgnjx.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsgnjx.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x float> %b
}

; vfsgnjx is not commutable
define <vscale x 4 x float> @test_vfsgnjx_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfsgnjx_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfsgnjx.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[A]], <vscale x 4 x float> [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfsgnjx.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x double> @test_vfwadd_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfwadd_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwadd_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfwadd_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x double> @test_vfwadd_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfwadd_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %a, float %x, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwadd_w_rhs(<vscale x 4 x double> %x, float %y) {
; CHECK-LABEL: @test_vfwadd_w_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwadd.w.nxv4f64.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x double> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwadd.w.nxv4f64.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x double> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwmul_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfwmul_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwmul_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfwmul_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x double> @test_vfwmul_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vfwmul_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[A]], float [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %a, float %x, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwsub_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfwsub_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwsub.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwsub.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

; vfwsub is not commutable
define <vscale x 4 x double> @test_vfwsub_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vfwsub_lhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwsub.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> [[A]], <vscale x 4 x float> [[X:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwsub.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwsub_w_rhs(<vscale x 4 x double> %x, float %y) {
; CHECK-LABEL: @test_vfwsub_w_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwsub.w.nxv4f64.f32.i64(<vscale x 4 x double> undef, <vscale x 4 x double> [[X:%.*]], float [[Y:%.*]], i64 7, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwsub.w.nxv4f64.nxv4f32.i64(<vscale x 4 x double> undef, <vscale x 4 x double> %x, <vscale x 4 x float> %a, i64 7, i64 4)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x i32> @test_vmacc_rhs(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vmacc_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmacc_lhs(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vmacc_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vmacc_scalar(<vscale x 4 x i32> %x, i32 %y, i32 %z) {
; CHECK-LABEL: @test_vmacc_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i32> [[A]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.i32.i64(<vscale x 4 x i32> %x, i32 %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vnmsac_rhs(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vnmsac_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vnmsac_lhs(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vnmsac_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i32> @test_vnmsac_scalar(<vscale x 4 x i32> %x, i32 %y, i32 %z) {
; CHECK-LABEL: @test_vnmsac_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i32> [[A]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.i32.i64(<vscale x 4 x i32> %x, i32 %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vmadd(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vmadd(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmadd.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vnmsub(<vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vnmsub(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vnmsub.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vnmsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x float> @test_vfmacc_rhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfmacc_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmacc_lhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfmacc_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfmacc_scalar(<vscale x 4 x float> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfmacc_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.f32.i64(<vscale x 4 x float> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfnmacc_rhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfnmacc_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfnmacc_lhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfnmacc_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfnmacc_scalar(<vscale x 4 x float> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfnmacc_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.f32.i64(<vscale x 4 x float> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmsac_rhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfmsac_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmsac_lhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfmsac_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfmsac_scalar(<vscale x 4 x float> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfmsac_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.f32.i64(<vscale x 4 x float> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfnmsac_rhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfnmsac_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfnmsac_lhs(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfnmsac_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x float> @test_vfnmsac_scalar(<vscale x 4 x float> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfnmsac_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.f32.i64(<vscale x 4 x float> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmadd(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfmadd(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmadd.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfnmadd(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfnmadd(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmadd.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfmsub(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfmsub(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmsub.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x float> @test_vfnmsub(<vscale x 4 x float> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfnmsub(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfnmsub.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfnmsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x i64> @test_vwmacc_rhs(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vwmacc_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmacc_lhs(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vwmacc_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwmacc_scalar(<vscale x 4 x i64> %x, i32 %y, i32 %z) {
; CHECK-LABEL: @test_vwmacc_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i32> [[A]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> %x, i32 %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmaccu_rhs(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vwmaccu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmaccu_lhs(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vwmaccu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwmaccu_scalar(<vscale x 4 x i64> %x, i32 %y, i32 %z) {
; CHECK-LABEL: @test_vwmaccu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i32> [[A]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> %x, i32 %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmaccsu_rhs(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vwmaccsu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmaccus.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x i64> @test_vwmaccsu_lhs(<vscale x 4 x i64> %x, <vscale x 4 x i32> %y, i32 %z) {
; CHECK-LABEL: @test_vwmaccsu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Z:%.*]], <vscale x 4 x i32> [[Y:%.*]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64> %x, <vscale x 4 x i32> %a, <vscale x 4 x i32> %y, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x i64> @test_vwmaccsu_scalar(<vscale x 4 x i64> %x, i32 %y, i32 %z) {
; CHECK-LABEL: @test_vwmaccsu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i32> [[A]], i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x i64> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %z, i64 4)
  %b = call <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64> %x, i32 %y, <vscale x 4 x i32> %a, i64 4, i64 0)
  ret <vscale x 4 x i64> %b
}

define <vscale x 4 x double> @test_vfwmacc_rhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwmacc_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwmacc_lhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwmacc_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x double> @test_vfwmacc_scalar(<vscale x 4 x double> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfwmacc_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwnmacc_rhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwnmacc_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwnmacc_lhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwnmacc_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x double> @test_vfwnmacc_scalar(<vscale x 4 x double> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfwnmacc_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwmsac_rhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwmsac_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwmsac_lhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwmsac_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x double> @test_vfwmsac_scalar(<vscale x 4 x double> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfwmsac_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwnmsac_rhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwnmsac_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x double> @test_vfwnmsac_lhs(<vscale x 4 x double> %x, <vscale x 4 x float> %y, float %z) {
; CHECK-LABEL: @test_vfwnmsac_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Z:%.*]], <vscale x 4 x float> [[Y:%.*]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double> %x, <vscale x 4 x float> %a, <vscale x 4 x float> %y, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

; Negative test. We already have a scalar. We can't have another.
define <vscale x 4 x double> @test_vfwnmsac_scalar(<vscale x 4 x double> %x, float %y, float %z) {
; CHECK-LABEL: @test_vfwnmsac_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Z:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x float> [[A]], i64 7, i64 4, i64 0)
; CHECK-NEXT:    ret <vscale x 4 x double> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %z, i64 4)
  %b = call <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double> %x, float %y, <vscale x 4 x float> %a, i64 7, i64 4, i64 0)
  ret <vscale x 4 x double> %b
}

define <vscale x 4 x i32> @test_vmerge(<vscale x 4 x i32> %x, i32 %y, <vscale x 4 x i1> %z) {
; CHECK-LABEL: @test_vmerge(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i1> [[Z:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, <vscale x 4 x i1> %z, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x float> @test_vfmerge(<vscale x 4 x float> %x, float %y, <vscale x 4 x i1> %z) {
; CHECK-LABEL: @test_vfmerge(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], <vscale x 4 x i1> [[Z:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x float> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %x, <vscale x 4 x float> %a, <vscale x 4 x i1> %z, i64 4)
  ret <vscale x 4 x float> %b
}

define <vscale x 4 x i32> @test_vsll_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsll_rhs(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.i64.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i64 [[TMP1]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsrl_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsrl_rhs(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsrl.nxv4i32.i64.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i64 [[TMP1]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsrl.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vsra_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vsra_rhs(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.i64.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i64 [[TMP1]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vssrl_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vssrl_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vssrl.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vssrl.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vssra_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vssra_rhs(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vssra.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[A]], i64 0, i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vssra.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 0, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vnsrl_rhs(<vscale x 4 x i64> %x, i32 %y) {
; CHECK-LABEL: @test_vnsrl_rhs(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.i64.i64(<vscale x 4 x i32> undef, <vscale x 4 x i64> [[X:%.*]], i64 [[TMP1]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i64> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

define <vscale x 4 x i32> @test_vnsra_rhs(<vscale x 4 x i64> %x, i32 %y) {
; CHECK-LABEL: @test_vnsra_rhs(
; CHECK-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vnsra.nxv4i32.nxv4i64.i64.i64(<vscale x 4 x i32> undef, <vscale x 4 x i64> [[X:%.*]], i64 [[TMP1]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vnsra.nxv4i32.nxv4i64.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i64> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i32> %b
}

declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vaadd.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vaaddu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vasub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vasubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vdiv.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vdiv.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vdivu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vdivu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vrem.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vrem.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vremu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vremu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsadd.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsaddu.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsmul.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vssub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vssubu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwadd.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwaddu.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwsub.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwsubu.w.nxv4i64.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)

declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfdiv.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmax.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmin.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsgnj.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsgnj.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsgnjn.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsgnjn.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsgnjx.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x float> @llvm.riscv.vfsgnjx.nxv4f32.f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, float, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwadd.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwadd.w.nxv4f64.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x double>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwmul.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwsub.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwsub.nxv4f64.nxv4f32.f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, float, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwsub.w.nxv4f64.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x double>, <vscale x 4 x float>, i64, i64)

declare <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vnmsub.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)

declare <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.f32.i64(<vscale x 4 x float>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.f32.i64(<vscale x 4 x float>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.f32.i64(<vscale x 4 x float>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.f32.i64(<vscale x 4 x float>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmsub.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)

declare <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64>, i32, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64>, i32, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.nxv4i32.nxv4i32.i64(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.i32.nxv4i32.i64(<vscale x 4 x i64>, i32, <vscale x 4 x i32>, i64, i64)

declare <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwnmacc.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double>, float, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.nxv4f32.nxv4f32.i64(<vscale x 4 x double>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64, i64)
declare <vscale x 4 x double> @llvm.riscv.vfwnmsac.nxv4f64.f32.nxv4f32.i64(<vscale x 4 x double>, float, <vscale x 4 x float>, i64, i64, i64)

declare <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i1>, i64)
declare <vscale x 4 x float> @llvm.riscv.vmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x i1>, i64)

declare <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsrl.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vssrl.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vssra.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64, i64)
declare <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i64>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vnsra.nxv4i32.nxv4i64.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i64>, <vscale x 4 x i32>, i64)
