; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mtriple=riscv64 -passes='instcombine' %s -S | FileCheck %s

define double @test(ptr %this, i1 %cmp) {
; CHECK-LABEL: define double @test(
; CHECK-SAME: ptr [[THIS:%.*]], i1 [[CMP:%.*]]) {
; CHECK-NEXT:    [[P0:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 1240
; CHECK-NEXT:    [[P1:%.*]] = getelementptr inbounds nuw i8, ptr [[THIS]], i64 1264
; CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[P0]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[P1]], align 8
; CHECK-NEXT:    [[D:%.*]] = select i1 [[CMP]], double [[TMP2]], double [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = fadd double [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = fadd double [[TMP3]], [[D]]
; CHECK-NEXT:    ret double [[TMP4]]
;
  %p0 = getelementptr inbounds i8, ptr %this, i64 1240
  %p1 = getelementptr inbounds i8, ptr %this, i64 1264
  %1 = load double, ptr %p0, align 8
  %2 = load double, ptr %p1, align 8
  %ps = select i1 %cmp, ptr %p1, ptr %p0
  %d = load double, ptr %ps, align 8

  %3 = fadd double %1, %2
  %4 = fadd double %3, %d
  ret double %4
}
