; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

; Test case take from TOOLCHAIN-1431 with a call to __builtin_rvv_is_splat added.
; We want riscv.is.splat to constant fold to true so that the vfirst will not
; execute if the compiler is not able to scalarize it.

define void @test_vshlq_u8(i8* nocapture readonly %in, i8 signext %v, i8* nocapture %out) {
; CHECK-LABEL: @test_vshlq_u8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, ptr [[IN:%.*]], i64 16)
; CHECK-NEXT:    br i1 true, label [[LAND_LHS_TRUE_I:%.*]], label [[IF_ELSE_I:%.*]]
; CHECK:       land.lhs.true.i:
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i8 [[V:%.*]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[VSHLQ_U8_EXIT:%.*]], label [[IF_ELSE_I]]
; CHECK:       if.else.i:
; CHECK-NEXT:    [[TMP1:%.*]] = zext i8 [[V]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.i64.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP0]], i64 [[TMP1]], i64 16)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 0, i64 16)
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ugt i8 [[V]], 7
; CHECK-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], <vscale x 16 x i8> [[TMP3]], <vscale x 16 x i8> [[TMP2]]
; CHECK-NEXT:    [[TMP6:%.*]] = sub i8 0, [[V]]
; CHECK-NEXT:    [[TMP7:%.*]] = zext i8 [[TMP6]] to i64
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.i64.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP0]], i64 [[TMP7]], i64 16)
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 0, i64 16)
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ult i8 [[V]], -7
; CHECK-NEXT:    [[TMP11:%.*]] = select i1 [[TMP10]], <vscale x 16 x i8> [[TMP9]], <vscale x 16 x i8> [[TMP8]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp slt i8 [[V]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = select i1 [[TMP12]], <vscale x 16 x i8> [[TMP11]], <vscale x 16 x i8> [[TMP5]]
; CHECK-NEXT:    br label [[VSHLQ_U8_EXIT]]
; CHECK:       vshlq_u8.exit:
; CHECK-NEXT:    [[TEMP_2_0_I:%.*]] = phi <vscale x 16 x i8> [ [[TMP13]], [[IF_ELSE_I]] ], [ [[TMP0]], [[LAND_LHS_TRUE_I]] ]
; CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> [[TEMP_2_0_I]], ptr [[OUT:%.*]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 16 x i8>*
  %1 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8>* %0, i64 16)
  %2 = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %1)
  %3 = call <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8> undef, i8 %v, i64 16)
  %4 = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %3)
  %5 = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %2)
  %6 = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %4)
  %7 = call i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8> %6)
  br i1 %7, label %land.lhs.true.i, label %if.else.i

land.lhs.true.i:                                  ; preds = %entry
  %8 = call <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8> %6, i8 0, i64 16)
  %9 = call i64 @llvm.riscv.vfirst.nxv16i1.i64(<vscale x 16 x i1> %8, i64 16)
  %cmp.i = icmp slt i64 %9, 0
  br i1 %cmp.i, label %vshlq_u8.exit, label %if.else.i

if.else.i:                                        ; preds = %land.lhs.true.i, %entry
  %10 = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> %6, i8 127, i64 16)
  %11 = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> %6, i8 7, i64 16)
  %12 = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %5, <vscale x 16 x i8> %6, i64 16)
  %13 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %12, i8 0, <vscale x 16 x i1> %11, i64 16)
  %14 = call <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8> %6, i8 -7, i64 16)
  %15 = call <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %6, i8 0, i64 16)
  %16 = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %5, <vscale x 16 x i8> %15, i64 16)
  %17 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %16, i8 0, <vscale x 16 x i1> %14, i64 16)
  %18 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %13, <vscale x 16 x i8> %17, <vscale x 16 x i1> %10, i64 16)
  br label %vshlq_u8.exit

vshlq_u8.exit:                                    ; preds = %land.lhs.true.i, %if.else.i
  %temp_2.0.i = phi <vscale x 16 x i8> [ %18, %if.else.i ], [ %5, %land.lhs.true.i ]
  %19 = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %temp_2.0.i)
  %20 = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %19)
  %21 = bitcast i8* %out to <vscale x 16 x i8>*
  call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> %20, <vscale x 16 x i8>* %21, i64 16)
  ret void
}

; Similar to above, but is.splat can't be proven true so it won't be removed.
define void @test_vshlq_u8_2(i8* nocapture readonly %in, i8* nocapture readonly %v, i8* nocapture %out) {
; CHECK-LABEL: @test_vshlq_u8_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, ptr [[IN:%.*]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, ptr [[V:%.*]], i64 16)
; CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8> [[TMP1]])
; CHECK-NEXT:    br i1 [[TMP2]], label [[LAND_LHS_TRUE_I:%.*]], label [[IF_ELSE_I:%.*]]
; CHECK:       land.lhs.true.i:
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP1]], i8 0, i64 16)
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vfirst.nxv16i1.i64(<vscale x 16 x i1> [[TMP3]], i64 16)
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp slt i64 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[CMP_I]], label [[VSHLQ_U8_EXIT:%.*]], label [[IF_ELSE_I]]
; CHECK:       if.else.i:
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP1]], i8 127, i64 16)
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP1]], i8 7, i64 16)
; CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP0]], <vscale x 16 x i8> [[TMP1]], i64 16)
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP7]], i8 0, <vscale x 16 x i1> [[TMP6]], i64 16)
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8> [[TMP1]], i8 -7, i64 16)
; CHECK-NEXT:    [[TMP10:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP1]], i8 0, i64 16)
; CHECK-NEXT:    [[TMP11:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP0]], <vscale x 16 x i8> [[TMP10]], i64 16)
; CHECK-NEXT:    [[TMP12:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP11]], i8 0, <vscale x 16 x i1> [[TMP9]], i64 16)
; CHECK-NEXT:    [[TMP13:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> [[TMP8]], <vscale x 16 x i8> [[TMP12]], <vscale x 16 x i1> [[TMP5]], i64 16)
; CHECK-NEXT:    br label [[VSHLQ_U8_EXIT]]
; CHECK:       vshlq_u8.exit:
; CHECK-NEXT:    [[TEMP_2_0_I:%.*]] = phi <vscale x 16 x i8> [ [[TMP13]], [[IF_ELSE_I]] ], [ [[TMP0]], [[LAND_LHS_TRUE_I]] ]
; CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> [[TEMP_2_0_I]], ptr [[OUT:%.*]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 16 x i8>*
  %1 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8>* %0, i64 16)
  %2 = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %1)
  %3 = bitcast i8* %v to <vscale x 16 x i8>*
  %4 = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8>* %3, i64 16)
  %5 = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %4)
  %6 = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %2)
  %7 = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %5)
  %8 = call i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8> %7)
  br i1 %8, label %land.lhs.true.i, label %if.else.i

land.lhs.true.i:                                  ; preds = %entry
  %9 = call <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8> %7, i8 0, i64 16)
  %10 = call i64 @llvm.riscv.vfirst.nxv16i1.i64(<vscale x 16 x i1> %9, i64 16) #6
  %cmp.i = icmp slt i64 %10, 0
  br i1 %cmp.i, label %vshlq_u8.exit, label %if.else.i

if.else.i:                                        ; preds = %land.lhs.true.i, %entry
  %11 = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> %7, i8 127, i64 16)
  %12 = call <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8> %7, i8 7, i64 16)
  %13 = call <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %6, <vscale x 16 x i8> %7, i64 16)
  %14 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %13, i8 0, <vscale x 16 x i1> %12, i64 16)
  %15 = call <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8> %7, i8 -7, i64 16)
  %16 = call <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %7, i8 0, i64 16)
  %17 = call <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %6, <vscale x 16 x i8> %16, i64 16)
  %18 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %17, i8 0, <vscale x 16 x i1> %15, i64 16)
  %19 = call <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> undef, <vscale x 16 x i8> %14, <vscale x 16 x i8> %18, <vscale x 16 x i1> %11, i64 16)
  br label %vshlq_u8.exit

vshlq_u8.exit:                                    ; preds = %land.lhs.true.i, %if.else.i
  %temp_2.0.i = phi <vscale x 16 x i8> [ %19, %if.else.i ], [ %6, %land.lhs.true.i ]
  %20 = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %temp_2.0.i)
  %21 = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %20)
  %22 = bitcast i8* %out to <vscale x 16 x i8>*
  call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> %21, <vscale x 16 x i8>* %22, i64 16)
  ret void
}

declare <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8>)
declare void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>* nocapture, i64)
declare i1 @llvm.riscv.is.splat.nxv16i8(<vscale x 16 x i8>)
declare <vscale x 16 x i1> @llvm.riscv.vmsne.nxv16i8.i8.i64(<vscale x 16 x i8>, i8, i64)
declare i64 @llvm.riscv.vfirst.nxv16i1.i64(<vscale x 16 x i1>, i64)
declare <vscale x 16 x i1> @llvm.riscv.vmsgtu.nxv16i8.i8.i64(<vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vsll.nxv16i8.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, i64)
declare <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, i8, <vscale x 16 x i1>, i64)
declare <vscale x 16 x i1> @llvm.riscv.vmsltu.nxv16i8.i8.i64(<vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vrsub.nxv16i8.i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, i8, i64)
declare <vscale x 16 x i8> @llvm.riscv.vsrl.nxv16i8.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, i64)
declare <vscale x 16 x i8> @llvm.riscv.vmerge.nxv16i8.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i1>, i64)
declare <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8>)
declare <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.i64(<vscale x 16 x i8>, <vscale x 16 x i8>* nocapture, i64)
declare <vscale x 16 x i8> @llvm.riscv.vmv.v.x.nxv16i8.i64(<vscale x 16 x i8>, i8, i64)
