; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v,+zvl512b -passes=instcombine -S | FileCheck %s

define void @vset_1(i8* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @vset_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[IN:%.*]], i64 3
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    store i32 [[CONV]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 1, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i32, ptr [[OUT]], i64 2
; CHECK-NEXT:    store i32 2, ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i32, ptr [[OUT]], i64 3
; CHECK-NEXT:    store i32 3, ptr [[TMP3]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx = getelementptr inbounds i8, i8* %in, i64 3
  %0 = load i8, i8* %arrayidx, align 1
  %conv = zext i8 %0 to i32
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v4i32(<4 x i32> <i32 0, i32 1, i32 2, i32 3>)
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv, i64 1)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %1, <vscale x 1 x i32> %2, i64 0, i64 1, i64 0)
  %4 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %3, <vscale x 1 x i32>* %4, i64 4)
  ret void
}

define void @vset_2(i8* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @vset_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[IN:%.*]], i64 3
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; CHECK-NEXT:    [[CONV3:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    store i32 [[CONV]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[CONV3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i32, ptr [[OUT]], i64 2
; CHECK-NEXT:    store i32 2, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[OUT]], i64 3
; CHECK-NEXT:    store i32 3, ptr [[TMP4]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx = getelementptr inbounds i8, i8* %in, i64 3
  %0 = load i8, i8* %arrayidx, align 1
  %conv = zext i8 %0 to i32
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v4i32(<4 x i32> <i32 0, i32 1, i32 2, i32 3>)
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv, i64 1)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %1, <vscale x 1 x i32> %2, i64 0, i64 1, i64 0)
  %arrayidx2 = getelementptr inbounds i8, i8* %in, i64 2
  %4 = load i8, i8* %arrayidx2, align 1
  %conv3 = zext i8 %4 to i32
  %5 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv3, i64 1)
  %6 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %3, <vscale x 1 x i32> %5, i64 1, i64 2, i64 0)
  %7 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %6, <vscale x 1 x i32>* %7, i64 4)
  ret void
}

define void @vset_3(i8* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @vset_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[IN:%.*]], i64 3
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; CHECK-NEXT:    [[CONV2:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    store i32 [[CONV]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[CONV2]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i32, ptr [[OUT]], i64 2
; CHECK-NEXT:    store i32 2, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[OUT]], i64 3
; CHECK-NEXT:    store i32 3, ptr [[TMP4]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx = getelementptr inbounds i8, i8* %in, i64 3
  %0 = load i8, i8* %arrayidx, align 1
  %conv = zext i8 %0 to i32
  %vecins = insertelement <4 x i32> <i32 poison, i32 1, i32 2, i32 3>, i32 %conv, i32 0
  %arrayidx1 = getelementptr inbounds i8, i8* %in, i64 2
  %1 = load i8, i8* %arrayidx1, align 1
  %conv2 = zext i8 %1 to i32
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v4i32(<4 x i32> %vecins)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv2, i64 1)
  %4 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %2, <vscale x 1 x i32> %3, i64 1, i64 2, i64 0)
  %5 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %4, <vscale x 1 x i32>* %5, i64 4)
  ret void
}

define void @vset_4(i8* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @vset_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[IN:%.*]], i64 3
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; CHECK-NEXT:    [[CONV3:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[ARRAYIDX7]], align 1
; CHECK-NEXT:    [[CONV8:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[IN]], align 1
; CHECK-NEXT:    [[CONV13:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    store i32 [[CONV]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[CONV3]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[OUT]], i64 2
; CHECK-NEXT:    store i32 [[CONV8]], ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr [[OUT]], i64 3
; CHECK-NEXT:    store i32 [[CONV13]], ptr [[TMP6]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx = getelementptr inbounds i8, i8* %in, i64 3
  %0 = load i8, i8* %arrayidx, align 1
  %conv = zext i8 %0 to i32
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v4i32(<4 x i32> <i32 0, i32 1, i32 2, i32 3>)
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv, i64 1)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %1, <vscale x 1 x i32> %2, i64 0, i64 1, i64 0)
  %arrayidx2 = getelementptr inbounds i8, i8* %in, i64 2
  %4 = load i8, i8* %arrayidx2, align 1
  %conv3 = zext i8 %4 to i32
  %5 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv3, i64 1)
  %6 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %3, <vscale x 1 x i32> %5, i64 1, i64 2, i64 0)
  %arrayidx7 = getelementptr inbounds i8, i8* %in, i64 1
  %7 = load i8, i8* %arrayidx7, align 1
  %conv8 = zext i8 %7 to i32
  %8 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv8, i64 1)
  %9 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %6, <vscale x 1 x i32> %8, i64 2, i64 3, i64 0)
  %10 = load i8, i8* %in, align 1
  %conv13 = zext i8 %10 to i32
  %11 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv13, i64 1)
  %12 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %9, <vscale x 1 x i32> %11, i64 3, i64 4, i64 0)
  %13 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %12, <vscale x 1 x i32>* %13, i64 4)
  ret void
}

define void @vset_5(float* nocapture readonly %in, float* nocapture %out) {
; CHECK-LABEL: @vset_5(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[IN:%.*]], i64 3
; CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, ptr [[IN]], i64 2
; CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[ARRAYIDX2]], align 4
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds float, ptr [[IN]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[ARRAYIDX6]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[IN]], align 4
; CHECK-NEXT:    store float [[TMP0]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr float, ptr [[OUT]], i64 1
; CHECK-NEXT:    store float [[TMP1]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr float, ptr [[OUT]], i64 2
; CHECK-NEXT:    store float [[TMP2]], ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr float, ptr [[OUT]], i64 3
; CHECK-NEXT:    store float [[TMP3]], ptr [[TMP6]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx = getelementptr inbounds float, float* %in, i64 3
  %0 = load float, float* %arrayidx, align 4
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v4f32(<4 x float> <float 0.000000e+00, float 1.000000e+00, float 2.000000e+00, float 3.000000e+00>)
  %2 = tail call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float> undef, float %0, i64 1)
  %3 = tail call <vscale x 1 x float> @llvm.riscv.vslideup.nxv1f32.i64(<vscale x 1 x float> %1, <vscale x 1 x float> %2, i64 0, i64 1, i64 0)
  %arrayidx2 = getelementptr inbounds float, float* %in, i64 2
  %4 = load float, float* %arrayidx2, align 4
  %5 = tail call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float> undef, float %4, i64 1)
  %6 = tail call <vscale x 1 x float> @llvm.riscv.vslideup.nxv1f32.i64(<vscale x 1 x float> %3, <vscale x 1 x float> %5, i64 1, i64 2, i64 0)
  %arrayidx6 = getelementptr inbounds float, float* %in, i64 1
  %7 = load float, float* %arrayidx6, align 4
  %8 = tail call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float> undef, float %7, i64 1)
  %9 = tail call <vscale x 1 x float> @llvm.riscv.vslideup.nxv1f32.i64(<vscale x 1 x float> %6, <vscale x 1 x float> %8, i64 2, i64 3, i64 0)
  %10 = load float, float* %in, align 4
  %11 = tail call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float> undef, float %10, i64 1)
  %12 = tail call <vscale x 1 x float> @llvm.riscv.vslideup.nxv1f32.i64(<vscale x 1 x float> %9, <vscale x 1 x float> %11, i64 3, i64 4, i64 0)
  %13 = bitcast float* %out to <vscale x 1 x float>*
  tail call void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float> %12, <vscale x 1 x float>* %13, i64 4)
  ret void
}

define void @vset_6(i8* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @vset_6(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[IN:%.*]], i64 3
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX4]], align 1
; CHECK-NEXT:    [[CONV5:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i8, ptr [[IN]], i64 1
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[ARRAYIDX9]], align 1
; CHECK-NEXT:    [[CONV10:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[IN]], align 1
; CHECK-NEXT:    [[CONV15:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    store i32 [[CONV]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[OUT]], i64 1
; CHECK-NEXT:    store i32 [[CONV5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[OUT]], i64 2
; CHECK-NEXT:    store i32 [[CONV10]], ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr [[OUT]], i64 3
; CHECK-NEXT:    store i32 [[CONV15]], ptr [[TMP6]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %arrayidx = getelementptr inbounds i8, i8* %in, i64 3
  %0 = load i8, i8* %arrayidx, align 1
  %conv = zext i8 %0 to i32
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 0, i64 4)
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv, i64 1)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %1, <vscale x 1 x i32> %2, i64 0, i64 1, i64 0)
  %arrayidx4 = getelementptr inbounds i8, i8* %in, i64 2
  %4 = load i8, i8* %arrayidx4, align 1
  %conv5 = zext i8 %4 to i32
  %5 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv5, i64 1)
  %6 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %3, <vscale x 1 x i32> %5, i64 1, i64 2, i64 0)
  %arrayidx9 = getelementptr inbounds i8, i8* %in, i64 1
  %7 = load i8, i8* %arrayidx9, align 1
  %conv10 = zext i8 %7 to i32
  %8 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv10, i64 1)
  %9 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %6, <vscale x 1 x i32> %8, i64 2, i64 3, i64 0)
  %10 = load i8, i8* %in, align 1
  %conv15 = zext i8 %10 to i32
  %11 = tail call <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32> undef, i32 %conv15, i64 1)
  %12 = tail call <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32> %9, <vscale x 1 x i32> %11, i64 3, i64 4, i64 0)
  %13 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %12, <vscale x 1 x i32>* %13, i64 4)
  ret void
}

define dso_local void @vset_7(i32* nocapture %out) {
; CHECK-LABEL: @vset_7(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vid.nxv1i32.i64(<vscale x 1 x i32> undef, i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vadd.nxv1i32.i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP0]], i32 -2, i64 4)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> [[TMP1]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
;
entry:
  %0 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v4i32(<4 x i32> <i32 -2, i32 -1, i32 0, i32 1>)
  %1 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %0, <vscale x 1 x i32>* %1, i64 4)
  ret void
}

declare <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v4i32(<4 x i32>)
declare <vscale x 1 x i32> @llvm.riscv.vmv.v.x.nxv1i32.i64(<vscale x 1 x i32>, i32, i64)
declare <vscale x 1 x i32> @llvm.riscv.vslideup.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64, i64)
declare void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>* nocapture, i64)
declare <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v4f32(<4 x float>)
declare <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float>, float, i64)
declare <vscale x 1 x float> @llvm.riscv.vslideup.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>, i64, i64, i64)
declare void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)
