; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | opt -mtriple=riscv32 -passes=instcombine -S | FileCheck %s --check-prefixes=RV32
; RUN: sed 's/iXLen/i64/g' %s | opt -mtriple=riscv64 -passes=instcombine -S | FileCheck %s --check-prefixes=RV64

declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32>, i32, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64>, i64, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float>, float, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vrsub.nxv4i32.i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfrsub.nxv4f32.f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, float, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.iXLen.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vsll.nxv4i64.iXLen.iXLen(<vscale x 4 x i64>, <vscale x 4 x i64>, iXLen, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vsrl.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwaddu.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwadd.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwsubu.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwsub.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i64>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.iXLen.iXLen(<vscale x 4 x i32>, <vscale x 4 x i64>, iXLen, iXLen)
declare <vscale x 4 x i16> @llvm.riscv.vnsrl.nxv4i16.nxv4i32.iXLen.iXLen(<vscale x 4 x i16>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vnsra.nxv4i32.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i64>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen)

define <vscale x 4 x i32> @test_vadd(i32 %x, i32 %y) {
; RV32-LABEL: @test_vadd(
; RV32-NEXT:    [[TMP1:%.*]] = add i32 [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vadd(
; RV64-NEXT:    [[TMP1:%.*]] = add i32 [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vsub(i32 %x, i32 %y) {
; RV32-LABEL: @test_vsub(
; RV32-NEXT:    [[TMP1:%.*]] = sub i32 [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vsub(
; RV64-NEXT:    [[TMP1:%.*]] = sub i32 [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vsub.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vrsub(i32 %x, i32 %y) {
; RV32-LABEL: @test_vrsub(
; RV32-NEXT:    [[TMP1:%.*]] = sub i32 [[Y:%.*]], [[X:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vrsub(
; RV64-NEXT:    [[TMP1:%.*]] = sub i32 [[Y:%.*]], [[X:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vrsub.nxv4i32.i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 %y, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x float> @test_vfadd(float %x, float %y) {
; RV32-LABEL: @test_vfadd(
; RV32-NEXT:    [[TMP1:%.*]] = fadd float [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[C]]
;
; RV64-LABEL: @test_vfadd(
; RV64-NEXT:    [[TMP1:%.*]] = fadd float [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[C]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %b, iXLen 7, iXLen 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfsub(float %x, float %y) {
; RV32-LABEL: @test_vfsub(
; RV32-NEXT:    [[TMP1:%.*]] = fsub float [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[C]]
;
; RV64-LABEL: @test_vfsub(
; RV64-NEXT:    [[TMP1:%.*]] = fsub float [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[C]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfsub.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %b, iXLen 7, iXLen 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfrsub(float %x, float %y) {
; RV32-LABEL: @test_vfrsub(
; RV32-NEXT:    [[TMP1:%.*]] = fsub float [[Y:%.*]], [[X:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[C]]
;
; RV64-LABEL: @test_vfrsub(
; RV64-NEXT:    [[TMP1:%.*]] = fsub float [[Y:%.*]], [[X:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[C]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfrsub.nxv4f32.f32.iXLen(<vscale x 4 x float> undef, <vscale x 4 x float> %a, float %y, iXLen 7, iXLen 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x i32> @test_vand(i32 %x, i32 %y) {
; RV32-LABEL: @test_vand(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vand(
; RV64-NEXT:    [[TMP1:%.*]] = and i32 [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vor(i32 %x, i32 %y) {
; RV32-LABEL: @test_vor(
; RV32-NEXT:    [[TMP1:%.*]] = or i32 [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vor(
; RV64-NEXT:    [[TMP1:%.*]] = or i32 [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vor.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vxor(i32 %x, i32 %y) {
; RV32-LABEL: @test_vxor(
; RV32-NEXT:    [[TMP1:%.*]] = xor i32 [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vxor(
; RV64-NEXT:    [[TMP1:%.*]] = xor i32 [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vsll(i32 %x, i32 %y) {
; RV32-LABEL: @test_vsll(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV32-NEXT:    [[TMP2:%.*]] = shl i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vsll(
; RV64-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV64-NEXT:    [[TMP2:%.*]] = shl i32 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vsll_vx(i32 %x, iXLen %y) {
; RV32-LABEL: @test_vsll_vx(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV32-NEXT:    [[TMP2:%.*]] = shl i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vsll_vx(
; RV64-NEXT:    [[TMP1:%.*]] = trunc i64 [[Y:%.*]] to i32
; RV64-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 31
; RV64-NEXT:    [[TMP3:%.*]] = shl i32 [[X:%.*]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vsll.nxv4i32.iXLen.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, iXLen %y, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i64> @test_vsll_vx_2(i64 %x, iXLen %y) {
; RV32-LABEL: @test_vsll_vx_2(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 63
; RV32-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = shl i64 [[X:%.*]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vsll_vx_2(
; RV64-NEXT:    [[TMP1:%.*]] = and i64 [[Y:%.*]], 63
; RV64-NEXT:    [[TMP2:%.*]] = shl i64 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vsll.nxv4i64.iXLen.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i64> %a, iXLen %y, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i32> @test_vsrl(i32 %x, i32 %y) {
; RV32-LABEL: @test_vsrl(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV32-NEXT:    [[TMP2:%.*]] = lshr i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vsrl(
; RV64-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV64-NEXT:    [[TMP2:%.*]] = lshr i32 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vsrl.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vsra(i32 %x, i32 %y) {
; RV32-LABEL: @test_vsra(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV32-NEXT:    [[TMP2:%.*]] = ashr i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vsra(
; RV64-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV64-NEXT:    [[TMP2:%.*]] = ashr i32 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vsra.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmul(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmul(
; RV32-NEXT:    [[TMP1:%.*]] = mul i32 [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmul(
; RV64-NEXT:    [[TMP1:%.*]] = mul i32 [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmulh(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmulh(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 32
; RV32-NEXT:    [[TMP5:%.*]] = trunc nuw i64 [[TMP4]] to i32
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP5]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmulh(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 32
; RV64-NEXT:    [[TMP5:%.*]] = trunc nuw i64 [[TMP4]] to i32
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP5]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmulh.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmulhu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmulhu(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 32
; RV32-NEXT:    [[TMP5:%.*]] = trunc nuw i64 [[TMP4]] to i32
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP5]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmulhu(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 32
; RV64-NEXT:    [[TMP5:%.*]] = trunc nuw i64 [[TMP4]] to i32
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP5]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmulhu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmulhsu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmulhsu(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 32
; RV32-NEXT:    [[TMP5:%.*]] = trunc nuw i64 [[TMP4]] to i32
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP5]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmulhsu(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP3]], 32
; RV64-NEXT:    [[TMP5:%.*]] = trunc nuw i64 [[TMP4]] to i32
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP5]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmulhsu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x float> @test_vfmul(float %x, float %y) {
; RV32-LABEL: @test_vfmul(
; RV32-NEXT:    [[TMP1:%.*]] = fmul float [[X:%.*]], [[Y:%.*]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[C]]
;
; RV64-LABEL: @test_vfmul(
; RV64-NEXT:    [[TMP1:%.*]] = fmul float [[X:%.*]], [[Y:%.*]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[C]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmul.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> undef, <vscale x 4 x float> %a, <vscale x 4 x float> %b, iXLen 7, iXLen 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x i64> @test_vwmul(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwmul(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwmul(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwmul.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwmulu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwmulu(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwmulu(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwmulu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwmulsu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwmulsu(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwmulsu(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwmulsu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwaddu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwaddu(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwaddu(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwaddu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwadd(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwadd(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = add nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwadd(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = add nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwadd.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwsubu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwsubu(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = sub nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwsubu(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = sub nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwsubu.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwsub(i32 %x, i32 %y) {
; RV32-LABEL: @test_vwsub(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = sub nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwsub(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[X:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = sub nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwsub.nxv4i64.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwaddu_w(i64 %x, i32 %y) {
; RV32-LABEL: @test_vwaddu_w(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = add i64 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwaddu_w(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = add i64 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwaddu.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i64> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwadd_w(i64 %x, i32 %y) {
; RV32-LABEL: @test_vwadd_w(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = add i64 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwadd_w(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = add i64 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i64> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwsubu_w(i64 %x, i32 %y) {
; RV32-LABEL: @test_vwsubu_w(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sub i64 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwsubu_w(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sub i64 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwsubu.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i64> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i64> @test_vwsub_w(i64 %x, i32 %y) {
; RV32-LABEL: @test_vwsub_w(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sub i64 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[C]]
;
; RV64-LABEL: @test_vwsub_w(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sub i64 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i64> @llvm.riscv.vwsub.w.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> undef, <vscale x 4 x i64> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i64> %c
}

define <vscale x 4 x i32> @test_vnsrl(i64 %x, i32 %y) {
; RV32-LABEL: @test_vnsrl(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 63
; RV32-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = lshr i64 [[X:%.*]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vnsrl(
; RV64-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 63
; RV64-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = lshr i64 [[X:%.*]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i64> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vnsrl_vx(i64 %x, iXLen %y) {
; RV32-LABEL: @test_vnsrl_vx(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 63
; RV32-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = lshr i64 [[X:%.*]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vnsrl_vx(
; RV64-NEXT:    [[TMP1:%.*]] = and i64 [[Y:%.*]], 63
; RV64-NEXT:    [[TMP2:%.*]] = lshr i64 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vnsrl.nxv4i32.nxv4i64.iXLen.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i64> %a, iXLen %y, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i16> @test_vnsrl_vx_2(i32 %x, iXLen %y) {
; RV32-LABEL: @test_vnsrl_vx_2(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 31
; RV32-NEXT:    [[TMP2:%.*]] = lshr i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[TMP3:%.*]] = trunc i32 [[TMP2]] to i16
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmv.v.x.nxv4i16.i32(<vscale x 4 x i16> undef, i16 [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i16> [[C]]
;
; RV64-LABEL: @test_vnsrl_vx_2(
; RV64-NEXT:    [[TMP1:%.*]] = trunc i64 [[Y:%.*]] to i32
; RV64-NEXT:    [[TMP2:%.*]] = and i32 [[TMP1]], 31
; RV64-NEXT:    [[TMP3:%.*]] = lshr i32 [[X:%.*]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = trunc i32 [[TMP3]] to i16
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmv.v.x.nxv4i16.i64(<vscale x 4 x i16> undef, i16 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i16> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %c = call <vscale x 4 x i16> @llvm.riscv.vnsrl.nxv4i16.nxv4i32.iXLen.iXLen(<vscale x 4 x i16> undef, <vscale x 4 x i32> %a, iXLen %y, iXLen 4)
  ret <vscale x 4 x i16> %c
}

define <vscale x 4 x i32> @test_vnsra(i64 %x, i32 %y) {
; RV32-LABEL: @test_vnsra(
; RV32-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 63
; RV32-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = ashr i64 [[X:%.*]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vnsra(
; RV64-NEXT:    [[TMP1:%.*]] = and i32 [[Y:%.*]], 63
; RV64-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = ashr i64 [[X:%.*]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vnsra.nxv4i32.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i64> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vminu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vminu(
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.umin.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vminu(
; RV64-NEXT:    [[TMP1:%.*]] = call i32 @llvm.umin.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vminu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmin(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmin(
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.smin.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmin(
; RV64-NEXT:    [[TMP1:%.*]] = call i32 @llvm.smin.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmin.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmaxu(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmaxu(
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.umax.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmaxu(
; RV64-NEXT:    [[TMP1:%.*]] = call i32 @llvm.umax.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmaxu.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmax(i32 %x, i32 %y) {
; RV32-LABEL: @test_vmax(
; RV32-NEXT:    [[TMP1:%.*]] = call i32 @llvm.smax.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV32-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[C]]
;
; RV64-LABEL: @test_vmax(
; RV64-NEXT:    [[TMP1:%.*]] = call i32 @llvm.smax.i32(i32 [[X:%.*]], i32 [[Y:%.*]])
; RV64-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmax.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, iXLen 4)
  ret <vscale x 4 x i32> %c
}
