; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

declare <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>, <vscale x 1 x i16>, i64)
declare <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>, <vscale x 1 x i16>, i64)
declare <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>, <vscale x 1 x i16>, i64)
declare <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16>, <vscale x 1 x i8>, i8, i64)
declare <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16>, <vscale x 1 x i8>, i8, i64)
declare <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16>, <vscale x 1 x i8>, i64)
declare <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16>, <vscale x 1 x i8>, i64)
declare <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8>, <vscale x 1 x i8>* nocapture, i64)
declare void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>* nocapture, i64)

; (vadd (vwcvtu x), (vwcvtu y)) -> (vwaddu x, y)
define void @add_wcvtu_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvtu_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vzext.f2 x), (vwctu y)) -> (vwaddu x, y)
define void @add_wcvtu_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvtu_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vwcvtu x), (vzext.f2 y)) -> (vwaddu x, y)
define void @add_wcvtu_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvtu_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vzext.f2 x), (vzext.f2 y)) -> (vwaddu x, y)
define void @add_wcvtu_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvtu_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vwcvt x), (vwcvt y)) -> (vwadd x, y)
define void @add_wcvt_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvt_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vsext.f2 x), (vwcvt y)) -> (vwadd x, y)
define void @add_wcvt_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvt_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vwcvt x), (vsext.f2 y)) -> (vwadd x, y)
define void @add_wcvt_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvt_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vadd (vsext.f2 x), (vsext.f2 y)) -> (vwadd x, y)
define void @add_wcvt_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @add_wcvt_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vadd.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vwcvtu x), (vwcvtu y)) -> (vwsubu x, y)
define void @sub_wcvtu_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvtu_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsubu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vzext.f2 x), (vwctu y)) -> (vwsubu x, y)
define void @sub_wcvtu_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvtu_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsubu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vwcvtu x), (vzext.f2 y)) -> (vwsubu x, y)
define void @sub_wcvtu_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvtu_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsubu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vzext.f2 x), (vzext.f2 y)) -> (vwsubu x, y)
define void @sub_wcvtu_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvtu_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsubu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vwcvt x), (vwcvt y)) -> (vwsub x, y)
define void @sub_wcvt_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvt_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsub.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vsext.f2 x), (vwcvt y)) -> (vwsub x, y)
define void @sub_wcvt_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvt_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsub.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vwcvt x), (vsext.f2 y)) -> (vwsub x, y)
define void @sub_wcvt_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvt_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsub.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vsub (vsext.f2 x), (vsext.f2 y)) -> (vwsub x, y)
define void @sub_wcvt_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @sub_wcvt_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwsub.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vsub.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvtu x), (vwcvtu y)) -> (vwmulu x, y)
define void @mul_wcvtu_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvtu_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vzext.f2 x), (vwctu y)) -> (vwmulu x, y)
define void @mul_wcvtu_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvtu_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvtu x), (vzext.f2 y)) -> (vwmulu x, y)
define void @mul_wcvtu_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvtu_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vzext.f2 x), (vzext.f2 y)) -> (vwmulu x, y)
define void @mul_wcvtu_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvtu_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvt x), (vwcvt y)) -> (vwmul x, y)
define void @mul_wcvt_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmul.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vsext.f2 x), (vwcvt y)) -> (vwmul x, y)
define void @mul_wcvt_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmul.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvt x), (vsext.f2 y)) -> (vwmul x, y)
define void @mul_wcvt_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmul.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vsext.f2 x), (vsext.f2 y)) -> (vwmul x, y)
define void @mul_wcvt_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmul.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvt x), (vwcvtu y)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvtu y), (vwcvt x)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_2(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %5, <vscale x 1 x i16> %2, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvt x), (vzext.f2 y)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_3(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vzext.f2 y), (vwcvt x)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_4(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %5, <vscale x 1 x i16> %2, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vsext.f2 x), (vwcvtu y)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_5(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_5(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vwcvtu y), (vsext.f2 x)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_6(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_6(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i8 0, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %5, <vscale x 1 x i16> %2, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vsext.f2 x), (vzext.f2 y)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_7(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_7(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, <vscale x 1 x i16> %5, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

; (vmul (vzext.f2 y), (vsext.f2 x)) -> (vwmulsu x, y)
define void @mul_wcvt_wcvtu_8(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @mul_wcvt_wcvtu_8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.p0.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmulsu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.p0.i64(<vscale x 1 x i16> [[TMP2]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vsext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i64 8)
  %3 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %4 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %3, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vzext.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %5, <vscale x 1 x i16> %2, i64 8)
  %7 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %6, <vscale x 1 x i16>* %7, i64 8)
  ret void
}

declare <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64.i64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, i64, i64)
declare <vscale x 1 x double> @llvm.riscv.vfsub.nxv1f64.nxv1f64.i64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, i64, i64)
declare <vscale x 1 x double> @llvm.riscv.vfmul.nxv1f64.nxv1f64.i64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, i64, i64)
declare <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double>, <vscale x 1 x float>, i64)
declare void @llvm.riscv.vse.nxv1f64.i64(<vscale x 1 x double>, <vscale x 1 x double>* nocapture, i64)
declare <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)

define void @fwcvt_fadd(float* nocapture readonly %in_0, float* nocapture readonly %in_1, double* nocapture %out) {
; CHECK-LABEL: @fwcvt_fadd(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> undef, ptr [[IN_0:%.*]], i64 2)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> undef, ptr [[IN_1:%.*]], i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x double> @llvm.riscv.vfwadd.nxv1f64.nxv1f32.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> [[TMP0]], <vscale x 1 x float> [[TMP1]], i64 7, i64 2)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1f64.p0.i64(<vscale x 1 x double> [[TMP2]], ptr [[OUT:%.*]], i64 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in_0 to <vscale x 1 x float>*
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %0, i64 2)
  %2 = tail call <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> %1, i64 2)
  %3 = bitcast float* %in_1 to <vscale x 1 x float>*
  %4 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %3, i64 2)
  %5 = tail call <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> %4, i64 2)
  %6 = tail call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64.i64(<vscale x 1 x double> undef, <vscale x 1 x double> %2, <vscale x 1 x double> %5, i64 7, i64 2)
  %7 = bitcast double* %out to <vscale x 1 x double>*
  tail call void @llvm.riscv.vse.nxv1f64.i64(<vscale x 1 x double> %6, <vscale x 1 x double>* %7, i64 2)
  ret void
}

define void @fwcvt_fsub(float* nocapture readonly %in_0, float* nocapture readonly %in_1, double* nocapture %out) {
; CHECK-LABEL: @fwcvt_fsub(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> undef, ptr [[IN_0:%.*]], i64 2)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> undef, ptr [[IN_1:%.*]], i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x double> @llvm.riscv.vfwsub.nxv1f64.nxv1f32.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> [[TMP0]], <vscale x 1 x float> [[TMP1]], i64 7, i64 2)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1f64.p0.i64(<vscale x 1 x double> [[TMP2]], ptr [[OUT:%.*]], i64 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in_0 to <vscale x 1 x float>*
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %0, i64 2)
  %2 = tail call <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> %1, i64 2)
  %3 = bitcast float* %in_1 to <vscale x 1 x float>*
  %4 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %3, i64 2)
  %5 = tail call <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> %4, i64 2)
  %6 = tail call <vscale x 1 x double> @llvm.riscv.vfsub.nxv1f64.nxv1f64.i64(<vscale x 1 x double> undef, <vscale x 1 x double> %2, <vscale x 1 x double> %5, i64 7, i64 2)
  %7 = bitcast double* %out to <vscale x 1 x double>*
  tail call void @llvm.riscv.vse.nxv1f64.i64(<vscale x 1 x double> %6, <vscale x 1 x double>* %7, i64 2)
  ret void
}

define void @fwcvt_fmul(float* nocapture readonly %in_0, float* nocapture readonly %in_1, double* nocapture %out) {
; CHECK-LABEL: @fwcvt_fmul(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> undef, ptr [[IN_0:%.*]], i64 2)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> undef, ptr [[IN_1:%.*]], i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x double> @llvm.riscv.vfwmul.nxv1f64.nxv1f32.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> [[TMP0]], <vscale x 1 x float> [[TMP1]], i64 7, i64 2)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1f64.p0.i64(<vscale x 1 x double> [[TMP2]], ptr [[OUT:%.*]], i64 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in_0 to <vscale x 1 x float>*
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %0, i64 2)
  %2 = tail call <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> %1, i64 2)
  %3 = bitcast float* %in_1 to <vscale x 1 x float>*
  %4 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %3, i64 2)
  %5 = tail call <vscale x 1 x double> @llvm.riscv.vfwcvt.f.f.v.nxv1f64.nxv1f32.i64(<vscale x 1 x double> undef, <vscale x 1 x float> %4, i64 2)
  %6 = tail call <vscale x 1 x double> @llvm.riscv.vfmul.nxv1f64.nxv1f64.i64(<vscale x 1 x double> undef, <vscale x 1 x double> %2, <vscale x 1 x double> %5, i64 7, i64 2)
  %7 = bitcast double* %out to <vscale x 1 x double>*
  tail call void @llvm.riscv.vse.nxv1f64.i64(<vscale x 1 x double> %6, <vscale x 1 x double>* %7, i64 2)
  ret void
}

