; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mcpu=sifive-x280 -passes="instcombine,simplifycfg,instcombine" %s -o - | FileCheck %s

; Test for existance of a covering Store to provide a value before checking control dependence.
; This is a false positive in that no covering Store is provided.

define <vscale x 16 x i32> @test(<vscale x 16 x i32> %vx, i64 noundef %avl) vscale_range(1) {
; CHECK-LABEL: define <vscale x 16 x i32> @test(
; CHECK-SAME: <vscale x 16 x i32> [[VX:%.*]], i64 noundef [[AVL:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 3)
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne i64 [[TMP0]], 0
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[CMP]])
; CHECK-NEXT:    [[VLA:%.*]] = alloca i32, i64 [[TMP0]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = trunc nuw nsw i64 [[TMP0]] to i32
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 [[VLA]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 16 x i32> @llvm.vp.sub.nxv16i32(<vscale x 16 x i32> zeroinitializer, <vscale x 16 x i32> [[VP_OP_LOAD]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP7]]
;
entry:
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %avl, i64 2, i64 3)
  %cmp = icmp ne i64 %0, 0
  tail call void @llvm.assume(i1 %cmp)
  %vla = alloca i32, i64 %0, align 8
  %vla1 = alloca i32, i64 %0, align 8
  br i1 false, label %scalar.ph, label %vector.ph

vector.ph:                                        ; preds = %entry
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.evl.next, %vector.body ]
  %evl.based.iv = phi i64 [ 0, %vector.ph ], [ %index.evl.next, %vector.body ]
  %1 = add i64 %index, 0
  %2 = sub i64 %0, %evl.based.iv
  %3 = call i32 @llvm.experimental.get.vector.length.i64(i64 %2, i32 16, i1 true)
  %4 = getelementptr inbounds i32, ptr %vla, i64 %1
  %5 = getelementptr inbounds i32, ptr %4, i32 0
  %vp.op.load = call <vscale x 16 x i32> @llvm.vp.load.nxv16i32.p0(ptr align 4 %5, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %3)
  %vp.op = call <vscale x 16 x i32> @llvm.vp.sub.nxv16i32(<vscale x 16 x i32> zeroinitializer, <vscale x 16 x i32> %vp.op.load, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %3)
  %6 = getelementptr inbounds i32, ptr %vla1, i64 %1
  %7 = getelementptr inbounds i32, ptr %6, i32 0
  call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> %vp.op, ptr align 4 %7, <vscale x 16 x i1> shufflevector (<vscale x 16 x i1> insertelement (<vscale x 16 x i1> poison, i1 true, i64 0), <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer), i32 %3)
  %8 = zext i32 %3 to i64
  %index.evl.next = add i64 %evl.based.iv, %8
  %9 = zext i32 %3 to i64
  %index.next = add i64 %evl.based.iv, %9
  %10 = icmp eq i64 %index.evl.next, %0
  br i1 %10, label %middle.block, label %vector.body

middle.block:                                     ; preds = %vector.body
  br label %for.cond.cleanup

scalar.ph:                                        ; preds = %entry
  %bc.resume.val = phi i64 [ 0, %entry ]
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.body
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %middle.block
  %11 = call <vscale x 16 x i32> @llvm.riscv.vle.nxv16i32.i64(<vscale x 16 x i32> poison, ptr nonnull %vla1, i64 %0)
  ret <vscale x 16 x i32> %11

for.body:                                         ; preds = %scalar.ph, %for.body
  %i.012 = phi i64 [ %bc.resume.val, %scalar.ph ], [ %inc, %for.body ]
  %arrayidx = getelementptr inbounds i32, ptr %vla, i64 %i.012
  %12 = load i32, ptr %arrayidx, align 4
  %sub.i = sub nsw i32 0, %12
  %arrayidx3 = getelementptr inbounds i32, ptr %vla1, i64 %i.012
  store i32 %sub.i, ptr %arrayidx3, align 4
  %inc = add nuw nsw i64 %i.012, 1
  %exitcond.not = icmp eq i64 %inc, %0
  br i1 %exitcond.not, label %for.cond.cleanup.loopexit, label %for.body
}
