; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

; This is the motivating case from TOOLCHAIN-1361. We want to rewrite the phis
; to use scalable vector types and remove the vcasts.
define void @dot_prod_f32(float* nocapture readonly %pSrcA, float* nocapture readonly %pSrcB, i32 signext %blockSize, float* nocapture %result) {
; CHECK-LABEL: @dot_prod_f32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float 0.000000e+00, i64 4)
; CHECK-NEXT:    br label [[FOR_COND:%.*]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[I_0:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[ADD:%.*]], [[FOR_BODY:%.*]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = phi <vscale x 4 x float> [ [[TMP0]], [[ENTRY]] ], [ [[TMP10:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[BLOCKSIZE:%.*]] to i64
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[I_0]], [[CONV]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <vscale x 4 x float> [[TMP1]] to <vscale x 4 x i32>
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> [[TMP2]], i32 -2147483648, i64 4)
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> [[TMP3]], i64 4)
; CHECK-NEXT:    [[CMP_NOT_I:%.*]] = icmp eq i64 [[TMP4]], -1
; CHECK-NEXT:    br i1 [[CMP_NOT_I]], label [[VADDVQ_F32_EXIT:%.*]], label [[IF_THEN_I:%.*]]
; CHECK:       if.then.i:
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfmv.v.f.nxv2f32.i64(<vscale x 2 x float> undef, float 0.000000e+00, i64 1)
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x float> @llvm.riscv.vfredosum.nxv2f32.nxv4f32.i64(<vscale x 2 x float> undef, <vscale x 4 x float> [[TMP1]], <vscale x 2 x float> [[TMP5]], i64 4)
; CHECK-NEXT:    [[TMP7:%.*]] = call float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float> [[TMP6]])
; CHECK-NEXT:    br label [[VADDVQ_F32_EXIT]]
; CHECK:       vaddvq_f32.exit:
; CHECK-NEXT:    [[TEMP_2_0_I:%.*]] = phi float [ [[TMP7]], [[IF_THEN_I]] ], [ -0.000000e+00, [[FOR_COND_CLEANUP]] ]
; CHECK-NEXT:    store float [[TEMP_2_0_I]], ptr [[RESULT:%.*]], align 4
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[PSRCA:%.*]], i64 [[I_0]]
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, ptr [[ARRAYIDX]], i64 4)
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[PSRCB:%.*]], i64 [[I_0]]
; CHECK-NEXT:    [[TMP9:%.*]] = call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, ptr [[ARRAYIDX4]], i64 4)
; CHECK-NEXT:    [[TMP10]] = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> [[TMP1]], <vscale x 4 x float> [[TMP8]], <vscale x 4 x float> [[TMP9]], i64 4, i64 0)
; CHECK-NEXT:    [[ADD]] = add i64 [[I_0]], 4
; CHECK-NEXT:    br label [[FOR_COND]]
;
entry:
  %0 = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float 0.000000e+00, i64 4) #3
  %1 = call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> %0) #3
  br label %for.cond

for.cond:                                         ; preds = %for.body, %entry
  %i.0 = phi i64 [ 0, %entry ], [ %add, %for.body ]
  %acc.0.in.in = phi <4 x float> [ %1, %entry ], [ %15, %for.body ]
  %conv = zext i32 %blockSize to i64
  %cmp = icmp ult i64 %i.0, %conv
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  %2 = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %acc.0.in.in) #3
  %3 = bitcast <vscale x 4 x float> %2 to <vscale x 4 x i32>
  %4 = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> %3, i32 -2147483648, i64 4) #3
  %5 = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %4, i64 4) #3
  %cmp.not.i = icmp eq i64 %5, -1
  br i1 %cmp.not.i, label %vaddvq_f32.exit, label %if.then.i

if.then.i:                                        ; preds = %for.cond.cleanup
  %6 = call <vscale x 2 x float> @llvm.riscv.vfmv.v.f.nxv2f32.i64(<vscale x 2 x float> undef, float 0.000000e+00, i64 1) #3
  %7 = call <vscale x 2 x float> @llvm.riscv.vfredosum.nxv2f32.nxv4f32.i64(<vscale x 2 x float> undef, <vscale x 4 x float> %2, <vscale x 2 x float> %6, i64 4) #3
  %8 = call float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float> %7) #3
  br label %vaddvq_f32.exit

vaddvq_f32.exit:                                  ; preds = %if.then.i, %for.cond.cleanup
  %temp_2.0.i = phi float [ %8, %if.then.i ], [ -0.000000e+00, %for.cond.cleanup ]
  store float %temp_2.0.i, float* %result, align 4
  ret void

for.body:                                         ; preds = %for.cond
  %arrayidx = getelementptr inbounds float, float* %pSrcA, i64 %i.0
  %9 = bitcast float* %arrayidx to <vscale x 4 x float>*
  %10 = call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float>* %9, i64 4) #3
  %arrayidx4 = getelementptr inbounds float, float* %pSrcB, i64 %i.0
  %11 = bitcast float* %arrayidx4 to <vscale x 4 x float>*
  %12 = call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float>* %11, i64 4) #3
  %13 = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %acc.0.in.in) #3
  %14 = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %13, <vscale x 4 x float> %10, <vscale x 4 x float> %12, i64 4, i64 0) #3
  %15 = call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> %14) #3
  %add = add i64 %i.0, 4
  br label %for.cond
}

declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64) #1
declare <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float>) #1
declare <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>* nocapture, i64) #2
declare <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float>) #1
declare <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64) #1
declare <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64) #1
declare i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1>, i64) #1
declare <vscale x 2 x float> @llvm.riscv.vfmv.v.f.nxv2f32.i64(<vscale x 2 x float>, float, i64) #1
declare <vscale x 2 x float> @llvm.riscv.vfredosum.nxv2f32.nxv4f32.i64(<vscale x 2 x float>, <vscale x 4 x float>, <vscale x 2 x float>, i64) #1
declare float @llvm.riscv.vfmv.f.s.nxv2f32(<vscale x 2 x float>) #1

define void @vcast(float* nocapture readonly %in, i64 %size, float* nocapture %out) {
; CHECK-LABEL: @vcast(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT16:%.*]] = icmp eq i64 [[SIZE:%.*]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float> undef, float 0.000000e+00, i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x float> @llvm.riscv.vfmv.v.f.nxv1f32.i64(<vscale x 1 x float> undef, float 0.000000e+00, i64 4)
; CHECK-NEXT:    br i1 [[CMP_NOT16]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[TMP2:%.*]] = phi <vscale x 1 x float> [ [[TMP1]], [[ENTRY:%.*]] ], [ [[TMP5:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float> [[TMP2]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[TMP3:%.*]] = phi <vscale x 1 x float> [ [[TMP5]], [[FOR_BODY]] ], [ [[TMP0]], [[ENTRY]] ]
; CHECK-NEXT:    [[I_017:%.*]] = phi i64 [ [[ADD:%.*]], [[FOR_BODY]] ], [ 0, [[ENTRY]] ]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds float, ptr [[IN:%.*]], i64 [[I_017]]
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, ptr [[ADD_PTR]], i64 4)
; CHECK-NEXT:    [[TMP5]] = tail call <vscale x 1 x float> @llvm.riscv.vfmacc.nxv1f32.nxv1f32.i64(<vscale x 1 x float> [[TMP3]], <vscale x 1 x float> [[TMP4]], <vscale x 1 x float> [[TMP4]], i64 4, i64 0)
; CHECK-NEXT:    [[ADD]] = add i64 [[I_017]], 4
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[ADD]], [[SIZE]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]]
;
entry:
  %cmp.not16 = icmp eq i64 %size, 0
  br i1 %cmp.not16, label %for.cond.cleanup, label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %.lcssa = phi <4 x float> [ zeroinitializer, %entry ], [ %7, %for.body ]
  %0 = tail call <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v4f32(<4 x float> %.lcssa)
  %1 = bitcast float* %out to <vscale x 1 x float>*
  tail call void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float> %0, <vscale x 1 x float>* %1, i64 4)
  ret void

for.body:                                         ; preds = %entry, %for.body
  %2 = phi <4 x float> [ %7, %for.body ], [ zeroinitializer, %entry ]
  %i.017 = phi i64 [ %add, %for.body ], [ 0, %entry ]
  %add.ptr = getelementptr inbounds float, float* %in, i64 %i.017
  %3 = bitcast float* %add.ptr to <vscale x 1 x float>*
  %4 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %3, i64 4)
  %5 = tail call <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v4f32(<4 x float> %2)
  %6 = tail call <vscale x 1 x float> @llvm.riscv.vfmacc.nxv1f32.nxv1f32.i64(<vscale x 1 x float> %5, <vscale x 1 x float> %4, <vscale x 1 x float> %4, i64 4, i64 0)
  %7 = tail call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv1f32(<vscale x 1 x float> %6)
  %add = add i64 %i.017, 4
  %cmp.not = icmp eq i64 %add, %size
  br i1 %cmp.not, label %for.cond.cleanup, label %for.body
}

declare <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)
declare <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv1f32(<vscale x 1 x float>)
declare <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v4f32(<4 x float>)
declare <vscale x 1 x float> @llvm.riscv.vfmacc.nxv1f32.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>, <vscale x 1 x float>, i64, i64)
declare void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)
