; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

define void @_Z4testPKiPi(i32* readonly %in, i32* %out) {
; CHECK-LABEL: @_Z4testPKiPi(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.i64(<vscale x 4 x i32> undef, ptr [[IN:%.*]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[TMP0]], i32 12, i64 4)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv4i32.i64(<vscale x 4 x i32> [[TMP1]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i32* %in to <vscale x 4 x i32>*
  %1 = tail call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32>* %0, i64 4)
  %2 = tail call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> <i32 12, i32 12, i32 12, i32 12>)
  %3 = tail call <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %1, <vscale x 4 x i32> %2, i64 4)
  %4 = bitcast i32* %out to <vscale x 4 x i32>*
  tail call void @llvm.riscv.vse.nxv4i32.i64(<vscale x 4 x i32> %3, <vscale x 4 x i32>* %4, i64 4)
  ret void
}

define void @_Z4testPKfPf(float* readonly %in, float* %out) {
; CHECK-LABEL: @_Z4testPKfPf(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, ptr [[IN:%.*]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 1065353216, i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <vscale x 4 x i32> [[TMP1]] to <vscale x 4 x float>
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 1065353217, i64 4)
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <vscale x 4 x i32> [[TMP3]] to <vscale x 4 x float>
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> [[TMP2]], <vscale x 4 x float> [[TMP4]], <vscale x 4 x float> [[TMP0]], i64 4, i64 0)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> [[TMP5]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in to <vscale x 4 x float>*
  %1 = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float>* %0, i64 4)
  %2 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> <float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00>)
  %3 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> <float 0x3FF0000020000000, float 0x3FF0000020000000, float 0x3FF0000020000000, float 0x3FF0000020000000>)
  %4 = tail call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %2, <vscale x 4 x float> %3, <vscale x 4 x float> %1, i64 4, i64 0)
  %5 = bitcast float* %out to <vscale x 4 x float>*
  tail call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> %4, <vscale x 4 x float>* %5, i64 4)
  ret void
}

define void @_Z4testPKfPKiPf(float* readonly %in_0, i32* readonly %in_1, float* %out) {
; CHECK-LABEL: @_Z4testPKfPKiPf(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, ptr [[IN_0:%.*]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.i64(<vscale x 4 x i32> undef, ptr [[IN_1:%.*]], i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i32> [[TMP2]] to <4 x float>
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 1060205080, i64 4)
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <vscale x 4 x i32> [[TMP5]] to <vscale x 4 x float>
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> [[TMP0]], <vscale x 4 x float> [[TMP4]], <vscale x 4 x float> [[TMP6]], i64 4, i64 0)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> [[TMP7]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in_0 to <vscale x 4 x float>*
  %1 = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float>* %0, i64 4)
  %2 = bitcast i32* %in_1 to <vscale x 4 x i32>*
  %3 = tail call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32>* %2, i64 4)
  %4 = tail call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32> %3)
  %5 = bitcast <4 x i32> %4 to <4 x float>
  %6 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %5)
  %7 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> <float 0x3FE62E4300000000, float 0x3FE62E4300000000, float 0x3FE62E4300000000, float 0x3FE62E4300000000>)
  %8 = tail call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %1, <vscale x 4 x float> %6, <vscale x 4 x float> %7, i64 4, i64 0)
  %9 = bitcast float* %out to <vscale x 4 x float>*
  tail call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> %8, <vscale x 4 x float>* %9, i64 4)
  ret void
}

define void @_Z4testPKfDv4_fmPf(float* readonly %in_0, i128 %in_1.coerce, i64 %i, float* %out) {
; CHECK-LABEL: @_Z4testPKfDv4_fmPf(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i128 [[IN_1_COERCE:%.*]] to <4 x float>
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, ptr [[IN_0:%.*]], i64 4)
; CHECK-NEXT:    [[VECEXT:%.*]] = extractelement <4 x float> [[TMP0]], i64 [[I:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> [[TMP1]], float [[VECEXT]], i64 4)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> [[TMP2]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i128 %in_1.coerce to <4 x float>
  %1 = bitcast float* %in_0 to <vscale x 4 x float>*
  %2 = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float>* %1, i64 4)
  %vecext = extractelement <4 x float> %0, i64 %i
  %vecinit.i = insertelement <4 x float> undef, float %vecext, i32 0
  %vecinit3.i = shufflevector <4 x float> %vecinit.i, <4 x float> poison, <4 x i32> zeroinitializer
  %3 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %vecinit3.i)
  %4 = tail call <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %2, <vscale x 4 x float> %3, i64 4)
  %5 = bitcast float* %out to <vscale x 4 x float>*
  tail call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> %4, <vscale x 4 x float>* %5, i64 4)
  ret void
}

declare <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32>)
declare void @llvm.riscv.vse.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>* nocapture, i64)
declare <vscale x 4 x i32> @llvm.riscv.vadd.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>* nocapture, i64)
declare <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float>)
declare void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>* nocapture, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>* nocapture, i64)
declare <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare <vscale x 4 x float> @llvm.riscv.vfadd.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i64)
