; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt %s -passes=instcombine -S | FileCheck %s

define void @test1(ptr %arg, ptr %arg1) vscale_range(1) {
; CHECK-LABEL: define void @test1
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 1)
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 1)
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 1)
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 1)
; CHECK-NEXT:    br i1 true, label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 1, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, 1
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

define void @test2(ptr %arg, ptr %arg1) vscale_range(1) {
; CHECK-LABEL: define void @test2
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 2)
; CHECK-NEXT:    br i1 true, label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 2, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, 2
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

define void @test3(ptr %arg, ptr %arg1) vscale_range(1) {
; CHECK-LABEL: define void @test3
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 4)
; CHECK-NEXT:    br i1 true, label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 4, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, 4
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

define void @test4(ptr %arg, ptr %arg1, i64 %avl) vscale_range(1) {
; CHECK-LABEL: define void @test4
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]], i64 [[AVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[VL:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 2)
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CALL:%.*]] = trunc nuw nsw i64 [[VL]] to i32
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    br i1 true, label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  %vl = tail call i64 @llvm.riscv.vsetvli.i64(i64 %avl, i64 3, i64 2)
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 %vl, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, %vl
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

define void @test5(ptr %arg, ptr %arg1, i64 %avl) vscale_range(1) {
; CHECK-LABEL: define void @test5
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]], i64 [[AVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[VL:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 1)
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[CALL:%.*]] = trunc nuw nsw i64 [[VL]] to i32
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[ARG1]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[ARG]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    br i1 true, label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  %vl = tail call i64 @llvm.riscv.vsetvli.i64(i64 %avl, i64 3, i64 1)
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 %vl, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, %vl
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

; Negative test. LMUL on vsetvli is too large.
define void @test6(ptr %arg, ptr %arg1, i64 %avl) vscale_range(1) {
; CHECK-LABEL: define void @test6
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]], i64 [[AVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[VL:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 3, i64 3)
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[ADD:%.*]], [[BB2]] ], [ 0, [[BB:%.*]] ]
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 [[VL]], [[PHI]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @llvm.experimental.get.vector.length.i64(i64 [[SUB]], i32 4, i1 true)
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[CALL]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[PHI]], 3
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr i8, ptr [[ARG]], i64 [[SHL]]
; CHECK-NEXT:    [[GETELEMENTPTR3:%.*]] = getelementptr i8, ptr [[ARG1]], i64 [[SHL]]
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[GETELEMENTPTR3]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[GETELEMENTPTR]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[GETELEMENTPTR3]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[GETELEMENTPTR]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    [[ADD]] = add i64 [[PHI]], [[ZEXT]]
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i64 [[ADD]], [[VL]]
; CHECK-NEXT:    br i1 [[ICMP]], label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  %vl = tail call i64 @llvm.riscv.vsetvli.i64(i64 %avl, i64 3, i64 3)
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 %vl, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, %vl
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

; Negative test. SEW on vsetvli is too small.
define void @test7(ptr %arg, ptr %arg1, i64 %avl) vscale_range(1) {
; CHECK-LABEL: define void @test7
; CHECK-SAME: (ptr [[ARG:%.*]], ptr [[ARG1:%.*]], i64 [[AVL:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[VL:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 [[AVL]], i64 2, i64 2)
; CHECK-NEXT:    br label [[BB2:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[ADD:%.*]], [[BB2]] ], [ 0, [[BB:%.*]] ]
; CHECK-NEXT:    [[SUB:%.*]] = sub i64 [[VL]], [[PHI]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @llvm.experimental.get.vector.length.i64(i64 [[SUB]], i32 4, i1 true)
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[CALL]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[PHI]], 3
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr i8, ptr [[ARG]], i64 [[SHL]]
; CHECK-NEXT:    [[GETELEMENTPTR3:%.*]] = getelementptr i8, ptr [[ARG1]], i64 [[SHL]]
; CHECK-NEXT:    [[CALL4:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[GETELEMENTPTR3]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    [[CALL5:%.*]] = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[GETELEMENTPTR]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL5]], ptr align 8 [[GETELEMENTPTR3]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[CALL4]], ptr align 8 [[GETELEMENTPTR]], <vscale x 4 x i1> splat (i1 true), i32 [[CALL]])
; CHECK-NEXT:    [[ADD]] = add i64 [[PHI]], [[ZEXT]]
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i64 [[ADD]], [[VL]]
; CHECK-NEXT:    br i1 [[ICMP]], label [[BB6:%.*]], label [[BB2]]
; CHECK:       bb6:
; CHECK-NEXT:    ret void
;
bb:
  %vl = tail call i64 @llvm.riscv.vsetvli.i64(i64 %avl, i64 2, i64 2)
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ %add, %bb2 ], [ 0, %bb ]
  %sub = sub i64 %vl, %phi
  %call = tail call i32 @llvm.experimental.get.vector.length.i64(i64 %sub, i32 4, i1 true)
  %zext = zext i32 %call to i64
  %shl = shl i64 %phi, 3
  %getelementptr = getelementptr i8, ptr %arg, i64 %shl
  %getelementptr3 = getelementptr i8, ptr %arg1, i64 %shl
  %call4 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %call5 = tail call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call5, ptr align 8 %getelementptr3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  tail call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> %call4, ptr align 8 %getelementptr, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i64 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %call)
  %add = add i64 %phi, %zext
  %icmp = icmp eq i64 %add, %vl
  br i1 %icmp, label %bb6, label %bb2

bb6:                                              ; preds = %bb2
  ret void
}

declare <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr nocapture, <vscale x 4 x i1>, i32)
declare void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64>, ptr nocapture, <vscale x 4 x i1>, i32)
declare i32 @llvm.experimental.get.vector.length.i64(i64, i32, i1)
declare i64 @llvm.riscv.vsetvli.i64(i64, i64, i64)
