; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, <vscale x 4 x i1>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i1>, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x i1>, i64)

; fold (vmerge (vmslt (vmv.v.x A), (vmv.v.x B)), C, D) -> (select (icmp slt A, B), C, D)

define <vscale x 4 x i32> @test_vmerge_vmseq(i32 %x, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmseq(
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i32> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 0, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsne(i32 %x, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP1]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 0, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsltu(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsltu(
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i32> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmslt(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmslt(
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i32> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsleu(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsleu(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP1]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsle(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsle(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp sgt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP1]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsgtu(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsgtu(
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ugt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i32> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsgt(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsgt(
; CHECK-NEXT:    [[TMP1:%.*]] = icmp sgt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x i32> [[OP2:%.*]], <vscale x 4 x i32> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsgeu(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsgeu(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP1]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsge(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsge(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP1]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vmerge_vmsge_vv(i32 %x, i32 %y, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2) {
; CHECK-LABEL: @test_vmerge_vmsge_vv(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP1]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %c = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, <vscale x 4 x i32> %op2, <vscale x 4 x i1> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vmerge_vx_vmsge_vv(i32 %x, i32 %y, <vscale x 4 x i32> %op1, i32 %op2) {
; CHECK-LABEL: @test_vmerge_vx_vmsge_vv(
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[OP2:%.*]], i64 4)
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[DOTNOT]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[TMP1]]
; CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %c = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %op1, i32 %op2, <vscale x 4 x i1> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x float> @test_vfmerge_vmfeq(float %x, float %y, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2) {
; CHECK-LABEL: @test_vfmerge_vmfeq(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp oeq float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x float> [[OP2:%.*]], <vscale x 4 x float> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfmerge_vmfne(float %x, float %y, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2) {
; CHECK-LABEL: @test_vfmerge_vmfne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp une float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x float> [[OP2:%.*]], <vscale x 4 x float> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfmerge_vmflt(float %x, float %y, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2) {
; CHECK-LABEL: @test_vfmerge_vmflt(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp olt float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x float> [[OP2:%.*]], <vscale x 4 x float> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfmerge_vmfle(float %x, float %y, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2) {
; CHECK-LABEL: @test_vfmerge_vmfle(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp ole float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x float> [[OP2:%.*]], <vscale x 4 x float> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfmerge_vmfgt(float %x, float %y, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2) {
; CHECK-LABEL: @test_vfmerge_vmfgt(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp ogt float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x float> [[OP2:%.*]], <vscale x 4 x float> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x float> %c
}

define <vscale x 4 x float> @test_vfmerge_vmfge(float %x, float %y, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2) {
; CHECK-LABEL: @test_vfmerge_vmfge(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp oge float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    [[TMP2:%.*]] = select i1 [[TMP1]], <vscale x 4 x float> [[OP2:%.*]], <vscale x 4 x float> [[OP1:%.*]]
; CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmerge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %op1, <vscale x 4 x float> %op2, <vscale x 4 x i1> %b, i64 4)
  ret <vscale x 4 x float> %c
}
