; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | opt -mtriple=riscv32 -passes=instcombine -S | FileCheck %s --check-prefixes=RV32
; RUN: sed 's/iXLen/i64/g' %s | opt -mtriple=riscv64 -passes=instcombine -S | FileCheck %s --check-prefixes=RV64

declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32>, i32, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64>, i64, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float>, float, iXLen)

declare <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vmadd.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i32> @llvm.riscv.vnmsub.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x i64> @llvm.riscv.vwmaccus.nxv4i64.i32.iXLen(<vscale x 4 x i64>, i32, <vscale x 4 x i32>, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmadd.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfnmadd.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfmsub.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)
declare <vscale x 4 x float> @llvm.riscv.vfnmsub.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen, iXLen, iXLen)

define <vscale x 4 x i32> @test_vmacc(i32 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vmacc(
; RV32-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[Z:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = add i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[D]]
;
; RV64-LABEL: @test_vmacc(
; RV64-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[Z:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = add i32 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vmacc.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vnmsac(i32 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vnmsac(
; RV32-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[Z:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = sub i32 [[X:%.*]], [[TMP1]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[D]]
;
; RV64-LABEL: @test_vnmsac(
; RV64-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[Z:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = sub i32 [[X:%.*]], [[TMP1]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vnmsac.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vmadd(i32 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vmadd(
; RV32-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[X:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = add i32 [[Z:%.*]], [[TMP1]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[D]]
;
; RV64-LABEL: @test_vmadd(
; RV64-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[X:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = add i32 [[Z:%.*]], [[TMP1]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vmadd.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vnmsub(i32 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vnmsub(
; RV32-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[X:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = sub i32 [[Z:%.*]], [[TMP1]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i32(<vscale x 4 x i32> undef, i32 [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i32> [[D]]
;
; RV64-LABEL: @test_vnmsub(
; RV64-NEXT:    [[TMP1:%.*]] = mul i32 [[Y:%.*]], [[X:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = sub i32 [[Z:%.*]], [[TMP1]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vnmsub.nxv4i32.nxv4i32.iXLen(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i64> @test_vwmaccu(i64 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vwmaccu(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Z:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[D]]
;
; RV64-LABEL: @test_vwmaccu(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Z:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[D]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i64> @llvm.riscv.vwmaccu.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i64> %d
}

define <vscale x 4 x i64> @test_vwmacc(i64 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vwmacc(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sext i32 [[Z:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[D]]
;
; RV64-LABEL: @test_vwmacc(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[Z:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[D]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i64> @llvm.riscv.vwmacc.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i64> %d
}

define <vscale x 4 x i64> @test_vwmaccsu(i64 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vwmaccsu(
; RV32-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = zext i32 [[Z:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[D]]
;
; RV64-LABEL: @test_vwmaccsu(
; RV64-NEXT:    [[TMP1:%.*]] = sext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = zext i32 [[Z:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[D]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %y, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i64> @llvm.riscv.vwmaccsu.nxv4i64.nxv4i32.iXLen(<vscale x 4 x i64> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i64> %d
}

define <vscale x 4 x i64> @test_vwmaccus(i64 %x, i32 %y, i32 %z) {
; RV32-LABEL: @test_vwmaccus(
; RV32-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV32-NEXT:    [[TMP2:%.*]] = sext i32 [[Z:%.*]] to i64
; RV32-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV32-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i32(<vscale x 4 x i64> undef, i64 [[TMP4]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x i64> [[D]]
;
; RV64-LABEL: @test_vwmaccus(
; RV64-NEXT:    [[TMP1:%.*]] = zext i32 [[Y:%.*]] to i64
; RV64-NEXT:    [[TMP2:%.*]] = sext i32 [[Z:%.*]] to i64
; RV64-NEXT:    [[TMP3:%.*]] = mul nsw i64 [[TMP1]], [[TMP2]]
; RV64-NEXT:    [[TMP4:%.*]] = add i64 [[X:%.*]], [[TMP3]]
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.i64(<vscale x 4 x i64> undef, i64 [[TMP4]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x i64> [[D]]
;
  %a = call <vscale x 4 x i64> @llvm.riscv.vmv.v.x.nxv4i64.iXLen(<vscale x 4 x i64> undef, i64 %x, iXLen 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.iXLen(<vscale x 4 x i32> undef, i32 %z, iXLen 4)
  %d = call <vscale x 4 x i64> @llvm.riscv.vwmaccus.nxv4i64.i32.iXLen(<vscale x 4 x i64> %a, i32 %y, <vscale x 4 x i32> %c, iXLen 4, iXLen 0)
  ret <vscale x 4 x i64> %d
}

define <vscale x 4 x float> @test_vfmacc(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfmacc(
; RV32-NEXT:    [[TMP1:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[Z:%.*]], float [[X:%.*]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfmacc(
; RV64-NEXT:    [[TMP1:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[Z:%.*]], float [[X:%.*]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfmacc.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfnmacc(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfnmacc(
; RV32-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = fneg float [[X:%.*]]
; RV32-NEXT:    [[TMP3:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[Z:%.*]], float [[TMP2]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfnmacc(
; RV64-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = fneg float [[X:%.*]]
; RV64-NEXT:    [[TMP3:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[Z:%.*]], float [[TMP2]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfnmacc.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfmsac(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfmsac(
; RV32-NEXT:    [[TMP1:%.*]] = fneg float [[X:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[Z:%.*]], float [[TMP1]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfmsac(
; RV64-NEXT:    [[TMP1:%.*]] = fneg float [[X:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[Z:%.*]], float [[TMP1]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfmsac.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfnmsac(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfnmsac(
; RV32-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[Z:%.*]], float [[X:%.*]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfnmsac(
; RV64-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[Z:%.*]], float [[X:%.*]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfnmsac.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfmadd(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfmadd(
; RV32-NEXT:    [[TMP1:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[X:%.*]], float [[Z:%.*]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP1]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfmadd(
; RV64-NEXT:    [[TMP1:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[X:%.*]], float [[Z:%.*]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP1]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfmadd.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfnmadd(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfnmadd(
; RV32-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = fneg float [[Z:%.*]]
; RV32-NEXT:    [[TMP3:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[X:%.*]], float [[TMP2]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP3]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfnmadd(
; RV64-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = fneg float [[Z:%.*]]
; RV64-NEXT:    [[TMP3:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[X:%.*]], float [[TMP2]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP3]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfnmadd.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfmsub(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfmsub(
; RV32-NEXT:    [[TMP1:%.*]] = fneg float [[Z:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[X:%.*]], float [[TMP1]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfmsub(
; RV64-NEXT:    [[TMP1:%.*]] = fneg float [[Z:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[Y:%.*]], float [[X:%.*]], float [[TMP1]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfmsub.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}

define <vscale x 4 x float> @test_vfnmsub(float %x, float %y, float %z) {
; RV32-LABEL: @test_vfnmsub(
; RV32-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV32-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[X:%.*]], float [[Z:%.*]])
; RV32-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i32(<vscale x 4 x float> undef, float [[TMP2]], i32 4)
; RV32-NEXT:    ret <vscale x 4 x float> [[D]]
;
; RV64-LABEL: @test_vfnmsub(
; RV64-NEXT:    [[TMP1:%.*]] = fneg float [[Y:%.*]]
; RV64-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[X:%.*]], float [[Z:%.*]])
; RV64-NEXT:    [[D:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[TMP2]], i64 4)
; RV64-NEXT:    ret <vscale x 4 x float> [[D]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %x, iXLen 4)
  %b = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %y, iXLen 4)
  %c = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.iXLen(<vscale x 4 x float> undef, float %z, iXLen 4)
  %d = call <vscale x 4 x float> @llvm.riscv.vfnmsub.nxv4f32.nxv4f32.iXLen(<vscale x 4 x float> %a, <vscale x 4 x float> %b, <vscale x 4 x float> %c, iXLen 7, iXLen 4, iXLen 0)
  ret <vscale x 4 x float> %d
}
