; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=instcombine -S %s | FileCheck %s

; This file covers test case of fixed-point intrinsics with an extra rounding
; mode operand that was dealt differently under foldVBroadcast in
; SiFive_RISCVInstCombineIntrinsic.cpp

target triple = "riscv64"

define <vscale x 2 x i16> @test_vaadd(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vaadd
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vaadd.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i16 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vaadd.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16>, i16, i64) #1

declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg) #2

declare <vscale x 2 x i16> @llvm.riscv.vaadd.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #2

define <vscale x 2 x i16> @test_vaaddu(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vaaddu
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vaaddu.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i16 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vaaddu.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vaaddu.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #2

define <vscale x 2 x i16> @test_vsmul(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vsmul
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vsmul.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i16 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vsmul.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vsmul.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #2

define <vscale x 2 x i16> @test_vasub(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vasub
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vasub.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i16 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vasub.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vasub.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #2

define <vscale x 2 x i16> @test_vasubu(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vasubu
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vasubu.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i16 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vasubu.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vasubu.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #2

define <vscale x 2 x i16> @test_vssra(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vssra
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vssra.nxv2i16.i64.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i64 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vssra.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vssra.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #3

define <vscale x 2 x i16> @test_vssrl(<vscale x 2 x i16> %var_14) {
; CHECK-LABEL: define <vscale x 2 x i16> @test_vssrl
; CHECK-SAME: (<vscale x 2 x i16> [[VAR_14:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vssrl.nxv2i16.i64.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[VAR_14]], i64 21968, i64 7, i64 3)
; CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x i16> @llvm.riscv.vmv.v.x.nxv2i16.i64(<vscale x 2 x i16> poison, i16 21968, i64 7)
  %1 = call i64 @llvm.riscv.vsetvli.i64(i64 3, i64 1, i64 7)
  %2 = call <vscale x 2 x i16> @llvm.riscv.vssrl.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> %var_14, <vscale x 2 x i16> %0, i64 7, i64 3)
  ret <vscale x 2 x i16> %2
}

declare <vscale x 2 x i16> @llvm.riscv.vssrl.nxv2i16.nxv2i16.i64(<vscale x 2 x i16>, <vscale x 2 x i16>, <vscale x 2 x i16>, i64 immarg, i64) #3
