; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

define <vscale x 1 x i8> @intrinsic_vsrl_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsrl_vx_nxv1i8_nxv1i8_i8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 6
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vsrl.nxv1i8.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vsrl.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vsrl.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vsrl_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsrl_vx_nxv1i16_nxv1i16_i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vsrl.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vsrl.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vsrl.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vsrl_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsrl_vx_nxv1i32_nxv1i32_i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vsrl.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vsrl.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vsrl.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i64> @intrinsic_vsrl_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsrl_vx_nxv1i64_nxv1i64_i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vsrl.nxv1i64.i64.i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i64> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vsrl.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vsrl.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vsra_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsra_vx_nxv1i8_nxv1i8_i8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 6
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vsra.nxv1i8.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vsra.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vsra.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vsra_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsra_vx_nxv1i16_nxv1i16_i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vsra.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vsra.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vsra.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vsra_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsra_vx_nxv1i32_nxv1i32_i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vsra.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vsra.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vsra.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i64> @intrinsic_vsra_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsra_vx_nxv1i64_nxv1i64_i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vsra.nxv1i64.i64.i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i64> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vsra.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vsra.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vsll_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsll_vx_nxv1i8_nxv1i8_i8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 6
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vsll.nxv1i8.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vsll.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vsll.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vsll_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsll_vx_nxv1i16_nxv1i16_i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vsll_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsll_vx_nxv1i32_nxv1i32_i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i64> @intrinsic_vsll_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vsll_vx_nxv1i64_nxv1i64_i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vsll.nxv1i64.i64.i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i64> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vsll.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vsll.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vssrl_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssrl_vx_nxv1i8_nxv1i8_i8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 6
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vssrl.nxv1i8.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vssrl.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vssrl.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64, i64)

define <vscale x 1 x i16> @intrinsic_vssrl_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssrl_vx_nxv1i16_nxv1i16_i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vssrl.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vssrl.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vssrl.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64, i64)

define <vscale x 1 x i32> @intrinsic_vssrl_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssrl_vx_nxv1i32_nxv1i32_i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vssrl.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vssrl.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vssrl.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64, i64)

define <vscale x 1 x i64> @intrinsic_vssrl_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssrl_vx_nxv1i64_nxv1i64_i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vssrl.nxv1i64.i64.i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i64> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vssrl.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vssrl.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64, i64)

define <vscale x 1 x i8> @intrinsic_vssra_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssra_vx_nxv1i8_nxv1i8_i8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 6
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vssra.nxv1i8.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vssra.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vssra.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64, i64)

define <vscale x 1 x i16> @intrinsic_vssra_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssra_vx_nxv1i16_nxv1i16_i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vssra.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vssra.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vssra.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64, i64)

define <vscale x 1 x i32> @intrinsic_vssra_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssra_vx_nxv1i32_nxv1i32_i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vssra.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vssra.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vssra.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64, i64)

define <vscale x 1 x i64> @intrinsic_vssra_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vssra_vx_nxv1i64_nxv1i64_i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vssra.nxv1i64.i64.i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 7, i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i64> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vssra.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 7, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vssra.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64, i64)

define <vscale x 1 x i8> @intrinsic_vnsrl_vx_nxv1i8_nxv1i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsrl_vx_nxv1i8_nxv1i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vnsrl.nxv1i8.nxv1i16.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vnsrl.nxv1i8.nxv1i16(<vscale x 1 x i8> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vnsrl.nxv1i8.nxv1i16(<vscale x 1 x i8>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vnsrl_vx_nxv1i16_nxv1i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsrl_vx_nxv1i16_nxv1i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vnsrl.nxv1i16.nxv1i32.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vnsrl.nxv1i16.nxv1i32(<vscale x 1 x i16> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vnsrl.nxv1i16.nxv1i32(<vscale x 1 x i16>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vnsrl_vx_nxv1i32_nxv1i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsrl_vx_nxv1i32_nxv1i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64(<vscale x 1 x i32>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vnsra_vx_nxv1i8_nxv1i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsra_vx_nxv1i8_nxv1i16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 14
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vnsra.nxv1i8.nxv1i16.i64.i64(<vscale x 1 x i8> undef, <vscale x 1 x i16> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i8> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vnsra.nxv1i8.nxv1i16(<vscale x 1 x i8> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vnsra.nxv1i8.nxv1i16(<vscale x 1 x i8>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vnsra_vx_nxv1i16_nxv1i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsra_vx_nxv1i16_nxv1i32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 30
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vnsra.nxv1i16.nxv1i32.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i32> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i16> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vnsra.nxv1i16.nxv1i32(<vscale x 1 x i16> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vnsra.nxv1i16.nxv1i32(<vscale x 1 x i16>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vnsra_vx_nxv1i32_nxv1i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsra_vx_nxv1i32_nxv1i64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SHAMT:%.*]] = and i64 [[TMP1:%.*]], 62
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[SHAMT]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vnsra_vx_nxv1i32_nxv1i64_63(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsra_vx_nxv1i32_nxv1i64_63(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[TMP1:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, 63
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}

define <vscale x 1 x i32> @intrinsic_vnsra_vx_nxv1i32_nxv1i64_127(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: @intrinsic_vnsra_vx_nxv1i32_nxv1i64_127(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP0:%.*]], i64 [[TMP1:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x i32> [[A]]
;
entry:
  %shamt = and i64 %1, 127
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
