; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=instcombine -S | FileCheck %s

define i128 @vmv_f16(half %value) {
; CHECK-LABEL: @vmv_f16(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 8 x half> @llvm.riscv.vfmv.v.f.nxv8f16.i64(<vscale x 8 x half> undef, half 0xH7E00, i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv8f16(<vscale x 8 x half> [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x half> [[TMP1]] to i128
; CHECK-NEXT:    ret i128 [[TMP2]]
;
entry:
  %0 = tail call <vscale x 8 x half> @llvm.riscv.vfmv.v.f.nxv8f16.i64(<vscale x 8 x half> undef, half 0xH7E00, i64 8)
  %1 = tail call <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv8f16(<vscale x 8 x half> %0)
  %2 = bitcast <8 x half> %1 to i128
  ret i128 %2
}

declare <vscale x 8 x half> @llvm.riscv.vfmv.v.f.nxv8f16.i64(<vscale x 8 x half>, half, i64)
declare <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv8f16(<vscale x 8 x half>)

define i128 @vmv_f32(float %value) {
; CHECK-LABEL: @vmv_f32(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float 0x7FF8000000000000, i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x float> [[TMP1]] to i128
; CHECK-NEXT:    ret i128 [[TMP2]]
;
entry:
  %0 = tail call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float 0x7FF8000000000000, i64 4)
  %1 = tail call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> %0)
  %2 = bitcast <4 x float> %1 to i128
  ret i128 %2
}

declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64)
declare <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float>)

define i128 @vmv_f64(double %value) {
; CHECK-LABEL: @vmv_f64(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 2 x double> @llvm.riscv.vfmv.v.f.nxv2f64.i64(<vscale x 2 x double> undef, double 0x7FF8000000000000, i64 2)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv2f64(<vscale x 2 x double> [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x double> [[TMP1]] to i128
; CHECK-NEXT:    ret i128 [[TMP2]]
;
entry:
  %0 = tail call <vscale x 2 x double> @llvm.riscv.vfmv.v.f.nxv2f64.i64(<vscale x 2 x double> undef, double 0x7FF8000000000000, i64 2)
  %1 = tail call <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv2f64(<vscale x 2 x double> %0)
  %2 = bitcast <2 x double> %1 to i128
  ret i128 %2
}

declare <vscale x 2 x double> @llvm.riscv.vfmv.v.f.nxv2f64.i64(<vscale x 2 x double>, double, i64)
declare <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv2f64(<vscale x 2 x double>)
