; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

define <vscale x 4 x i1> @test_vmseq_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmseq_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmseq_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmseq_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmseq_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmseq_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsne_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsne_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsne_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsne_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsne_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsne_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsltu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsltu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsltu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsltu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsltu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsltu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmslt_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmslt_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmslt_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmslt_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmslt_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmslt_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsleu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsleu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsleu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsleu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsleu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsleu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsle_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsle_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsle_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsle_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsle_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsle_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsgtu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsgtu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsgtu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsgtu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsgtu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsgtu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsgt_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsgt_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsgt_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsgt_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsgt_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsgt_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsgeu_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsgeu_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsgeu_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsgeu_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsgeu_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsgeu_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsge_rhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsge_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %x, <vscale x 4 x i32> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmsge_lhs(<vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vmsge_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmsge_scalar(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vmsge_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfeq_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfeq_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfeq_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfeq_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmfeq_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vmfeq_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfne_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfne_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfne_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfne_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmfne_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vmfne_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmflt_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmflt_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmflt_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmflt_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmflt_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vmflt_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfle_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfle_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfle_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfle_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmfle_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vmfle_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfgt_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfgt_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfgt_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfgt_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmfgt_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vmfgt_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfge_rhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfge_rhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %x, <vscale x 4 x float> %a, i64 4)
  ret <vscale x 4 x i1> %b
}

define <vscale x 4 x i1> @test_vmfge_lhs(<vscale x 4 x float> %x, float %y) {
; CHECK-LABEL: @test_vmfge_lhs(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float> [[X:%.*]], float [[Y:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.nxv4f32.i64(<vscale x 4 x float> %a, <vscale x 4 x float> %x, i64 4)
  ret <vscale x 4 x i1> %b
}

; Negative test, we can't have two scalars.
define <vscale x 4 x i1> @test_vmfge_scalar(float %x, float %y) {
; CHECK-LABEL: @test_vmfge_scalar(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float> [[A]], float [[X:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i1> [[B]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %y, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %x, i64 4)
  ret <vscale x 4 x i1> %b
}

declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)

declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
