; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v,+zvl512b -passes=instcombine -S | FileCheck %s

define void @test1(i8* nocapture readonly %in, i8* nocapture writeonly %out) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[IN:%.*]], i64 7
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP1]], ptr [[OUT:%.*]], align 1
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i8> @llvm.riscv.vrgather.vx.nxv1i8.i64(<vscale x 1 x i8>undef, <vscale x 1 x i8> %1, i64 7, i64 1)
  %3 = tail call i8 @llvm.riscv.vmv.x.s.nxv1i8(<vscale x 1 x i8> %2)
  store i8 %3, i8* %out, align 1
  ret void
}

define void @test2(float* nocapture readonly %in, float* nocapture writeonly %out) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[IN:%.*]], i64 12
; CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[TMP0]], align 4
; CHECK-NEXT:    store float [[TMP1]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in to <vscale x 1 x float>*
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %0, i64 4)
  %2 = tail call <vscale x 1 x float> @llvm.riscv.vrgather.vx.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float> %1, i64 3, i64 1)
  %3 = tail call float @llvm.riscv.vfmv.f.s.nxv1f32(<vscale x 1 x float> %2)
  store float %3, float* %out, align 4
  ret void
}

define void @test3(i8* nocapture readonly %in, i8* nocapture writeonly %out) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[IN:%.*]], align 1
; CHECK-NEXT:    [[IDXPROM:%.*]] = zext i8 [[TMP0]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT:%.*]], i64 [[IDXPROM]]
; CHECK-NEXT:    store i8 0, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call i8 @llvm.riscv.vmv.x.s.nxv1i8(<vscale x 1 x i8> %1)
  %idxprom = zext i8 %2 to i64
  %arrayidx = getelementptr inbounds i8, i8* %out, i64 %idxprom
  store i8 0, i8* %arrayidx, align 1
  ret void
}

declare <vscale x 1 x i8> @llvm.riscv.vrgather.vx.nxv1i8.i64(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)
declare i8 @llvm.riscv.vmv.x.s.nxv1i8(<vscale x 1 x i8>)
declare <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8>, <vscale x 1 x i8>* nocapture, i64)
declare <vscale x 1 x float> @llvm.riscv.vrgather.vx.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>, i64, i64)
declare float @llvm.riscv.vfmv.f.s.nxv1f32(<vscale x 1 x float>)
declare <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)
