; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v,+zvl512b -passes=instcombine -S | FileCheck %s

define void @slidedown_slideup_1(i8* nocapture readonly %in, i8* nocapture %out) {
; CHECK-LABEL: @slidedown_slideup_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.p0.i64(<vscale x 2 x i8> undef, ptr [[IN:%.*]], i64 16)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv2i8.p0.i64(<vscale x 2 x i8> [[TMP0]], ptr [[OUT:%.*]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in to <vscale x 2 x i8>*
  %1 = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8>* %0, i64 16)
  %2 = tail call <vscale x 2 x i8> @llvm.riscv.vslidedown.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8> %1, i64 8, i64 8, i64 0)
  %3 = tail call <vscale x 2 x i8> @llvm.riscv.vslideup.nxv2i8.i64(<vscale x 2 x i8> %1, <vscale x 2 x i8> %2, i64 8, i64 16, i64 0)
  %4 = bitcast i8* %out to <vscale x 2 x i8>*
  tail call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> %3, <vscale x 2 x i8>* %4, i64 16)
  ret void
}

declare <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>* nocapture, i64)
declare void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>* nocapture, i64)
declare <vscale x 2 x i8> @llvm.riscv.vslideup.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>, i64, i64, i64)
declare <vscale x 2 x i8> @llvm.riscv.vslidedown.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>, i64, i64, i64)

define void @slidedown_slideup_2(double* nocapture readonly %in, double* nocapture %out) {
; CHECK-LABEL: @slidedown_slideup_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.riscv.vsetvli.i64(i64 8, i64 3, i64 3)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x double> @llvm.riscv.vle.nxv8f64.p0.i64(<vscale x 8 x double> undef, ptr [[IN:%.*]], i64 [[TMP0]])
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv8f64.p0.i64(<vscale x 8 x double> [[TMP1]], ptr [[OUT:%.*]], i64 [[TMP0]])
; CHECK-NEXT:    ret void
;
entry:
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 8, i64 3, i64 3)
  %1 = bitcast double* %in to <vscale x 8 x double>*
  %2 = tail call <vscale x 8 x double> @llvm.riscv.vle.nxv8f64.i64(<vscale x 8 x double> undef, <vscale x 8 x double>* %1, i64 %0)
  %3 = tail call <vscale x 8 x double> @llvm.riscv.vslidedown.nxv8f64.i64(<vscale x 8 x double> undef, <vscale x 8 x double> %2, i64 2, i64 6, i64 0)
  %4 = tail call <vscale x 8 x double> @llvm.riscv.vslideup.nxv8f64.i64(<vscale x 8 x double> %2, <vscale x 8 x double> %3, i64 2, i64 3, i64 0)
  %5 = bitcast double* %out to <vscale x 8 x double>*
  tail call void @llvm.riscv.vse.nxv8f64.i64(<vscale x 8 x double> %4, <vscale x 8 x double>* %5, i64 %0)
  ret void
}

declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)
declare <vscale x 8 x double> @llvm.riscv.vle.nxv8f64.i64(<vscale x 8 x double>, <vscale x 8 x double>* nocapture, i64)
declare <vscale x 8 x double> @llvm.riscv.vslidedown.nxv8f64.i64(<vscale x 8 x double>, <vscale x 8 x double>, i64, i64, i64)
declare <vscale x 8 x double> @llvm.riscv.vslideup.nxv8f64.i64(<vscale x 8 x double>, <vscale x 8 x double>, i64, i64, i64)
declare void @llvm.riscv.vse.nxv8f64.i64(<vscale x 8 x double>, <vscale x 8 x double>* nocapture, i64)
