; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float>, float, i64)
declare i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1>, i64)

; fold (vfirst (vmslt (vmv.v.x A), (vmv.v.x B))) -> (select (icmp slt A, B), 0, -1)

define i64 @test_vfirst_vmseq_ne(i32 %x) {
; CHECK-LABEL: @test_vfirst_vmseq_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 0, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsne_ne(i32 %x) {
; CHECK-LABEL: @test_vfirst_vmsne_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 0, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsltu_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsltu_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmslt_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmslt_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsleu_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsleu_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsle_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsle_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp sgt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsgtu_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsgtu_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsgt_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsgt_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp sgt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsgeu_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsgeu_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsge_ne(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsge_ne(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmseq_eq(i32 %x) {
; CHECK-LABEL: @test_vfirst_vmseq_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmseq.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 0, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsne_eq(i32 %x) {
; CHECK-LABEL: @test_vfirst_vmsne_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[X:%.*]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsne.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 0, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsltu_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsltu_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsltu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmslt_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmslt_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsleu_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsleu_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsleu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsle_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsle_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp sgt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsle.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsgtu_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsgtu_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ugt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgtu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsgt_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsgt_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp sgt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgt.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsgeu_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsgeu_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp ult i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsgeu.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmsge_eq(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_vmsge_eq(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_setcc_commutable(i32 %x, i32 %y) {
; CHECK-LABEL: @test_setcc_commutable(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp eq i64 -1, %c
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_compare_vv(i32 %x, i32 %y) {
; CHECK-LABEL: @test_compare_vv(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %c = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, i64 4)
  %d = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %c, i64 4)
  %cmp = icmp eq i64 -1, %d
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_with_vl_zero(i32 %x, i32 %y) {
; CHECK-LABEL: @test_vfirst_with_vl_zero(
; CHECK-NEXT:    br i1 true, label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 4)
  %c = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, i64 4)
  %d = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %c, i64 0)
  %cmp = icmp eq i64 -1, %d
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_icmp_slt(i32 %x, i32 %y) {
; CHECK-LABEL: @test_icmp_slt(
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp slt i64 %c, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_icmp_sge(i32 %x, i32 %y) {
; CHECK-LABEL: @test_icmp_sge(
; CHECK-NEXT:    [[DOTNOT_NOT:%.*]] = icmp slt i32 [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[DOTNOT_NOT]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> %a, i32 %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp sge i64 %c, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_with_unknown_vl(i32 %x, i32 %y, i64 %vl) {
; CHECK-LABEL: @test_vfirst_with_unknown_vl(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 [[X:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.i32.i64(<vscale x 4 x i32> [[A]], i32 [[Y:%.*]], i64 [[VL]])
; CHECK-NEXT:    [[D:%.*]] = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> [[C]], i64 [[VL]])
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[D]], -1
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 %vl)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %y, i64 %vl)
  %c = call <vscale x 4 x i1> @llvm.riscv.vmsge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, i64 %vl)
  %d = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %c, i64 %vl)
  %cmp = icmp eq i64 -1, %d
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmfeq_ne(float %x, float %y) {
; CHECK-LABEL: @test_vfirst_vmfeq_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp une float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfeq.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmfne_ne(float %x, float %y) {
; CHECK-LABEL: @test_vfirst_vmfne_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp oeq float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmflt_ne(float %x, float %y) {
; CHECK-LABEL: @test_vfirst_vmflt_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp uge float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmflt.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmfle_ne(float %x, float %y) {
; CHECK-LABEL: @test_vfirst_vmfle_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp ugt float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfle.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmfgt_ne(float %x, float %y) {
; CHECK-LABEL: @test_vfirst_vmfgt_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp ule float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfgt.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}

define i64 @test_vfirst_vmfge_ne(float %x, float %y) {
; CHECK-LABEL: @test_vfirst_vmfge_ne(
; CHECK-NEXT:    [[TMP1:%.*]] = fcmp ult float [[X:%.*]], [[Y:%.*]]
; CHECK-NEXT:    br i1 [[TMP1]], label [[IF_ELSE:%.*]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    ret i64 0
; CHECK:       if.else:
; CHECK-NEXT:    ret i64 1
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call <vscale x 4 x i1> @llvm.riscv.vmfge.nxv4f32.f32.i64(<vscale x 4 x float> %a, float %y, i64 4)
  %c = call i64 @llvm.riscv.vfirst.nxv4i1.i64(<vscale x 4 x i1> %b, i64 4)
  %cmp = icmp ne i64 %c, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:
  ret i64 0
if.else:
  ret i64 1
}
