; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -passes=instcombine -S | FileCheck %s

define <vscale x 4 x i32> @test_vand_vmerge(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x) {
; CHECK-LABEL: @test_vand_vmerge(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 -1, <vscale x 4 x i1> %mask, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %b, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vand_vmerge2(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x) {
; CHECK-LABEL: @test_vand_vmerge2(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 -1, <vscale x 4 x i1> %mask, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vand_vmerge3(<vscale x 4 x i1> %mask, i32 %x) {
; CHECK-LABEL: @test_vand_vmerge3(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], i32 [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[C]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, i32 -1, <vscale x 4 x i1> %mask, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, i32 %x, i64 4)
  ret <vscale x 4 x i32> %c
}

define <vscale x 4 x i32> @test_vxor_vmerge(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge2(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge2(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, <vscale x 4 x i32> %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge3(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge3(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge4(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge4(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, <vscale x 4 x i32> %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge5(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge5(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge6(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge6(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, <vscale x 4 x i32> %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge7(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge7(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge8(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge8(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, <vscale x 4 x i32> %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_zero_scalar(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge_zero_scalar(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, i32 0, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_zero_scalar2(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge_zero_scalar2(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, <vscale x 4 x i32> %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, i32 0, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_zero_scalar3(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge_zero_scalar3(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, i32 0, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_zero_scalar4(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge_zero_scalar4(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, <vscale x 4 x i32> %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, i32 0, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_scalar_y_1(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vxor_vmerge_scalar_y_1(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_scalar_y_2(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vxor_vmerge_scalar_y_2(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

; Can't fold because we can't put %y in the first operand of vmerge without an
; extra splat intrinsic.
define <vscale x 4 x i32> @test_vxor_vmerge_scalar_y_3(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vxor_vmerge_scalar_y_3(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[B]], i32 0, <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[C]], <vscale x 4 x i32> [[X]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, <vscale x 4 x i32> %x, i64 4)
  ret <vscale x 4 x i32> %d
}

; Can't fold because we can't put %y in the first operand of vmerge without an
; extra splat intrinsic.
define <vscale x 4 x i32> @test_vxor_vmerge_scalar_y_4(<vscale x 4 x i1> %mask, <vscale x 4 x i32> %x, i32 %y) {
; CHECK-LABEL: @test_vxor_vmerge_scalar_y_4(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X:%.*]], i32 [[Y:%.*]], i64 4)
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[B]], i32 0, <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[X]], <vscale x 4 x i32> [[C]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, i32 %y, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %x, <vscale x 4 x i32> %c, i64 4)
  ret <vscale x 4 x i32> %d
}

; Can't fold because we can't put %x in the first operand of vmerge without an
; extra splat intrinsic.
define <vscale x 4 x i32> @test_vxor_vmerge_scalar_x_1(<vscale x 4 x i1> %mask, i32 %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge_scalar_x_1(
; CHECK-NEXT:    [[A:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], i32 [[X:%.*]], i64 4)
; CHECK-NEXT:    [[C:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[A]], <vscale x 4 x i32> [[B]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[C]], i32 [[X]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, i32 %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, i32 %x, i64 4)
  ret <vscale x 4 x i32> %d
}

define <vscale x 4 x i32> @test_vxor_vmerge_scalar_x_2(<vscale x 4 x i1> %mask, i32 %x, <vscale x 4 x i32> %y) {
; CHECK-LABEL: @test_vxor_vmerge_scalar_x_2(
; CHECK-NEXT:    [[D:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[Y:%.*]], i32 [[X:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 4)
; CHECK-NEXT:    ret <vscale x 4 x i32> [[D]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %b = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %y, i32 %x, i64 4)
  %c = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %b, <vscale x 4 x i32> %a, <vscale x 4 x i1> %mask, i64 4)
  %d = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %c, i32 %x, i64 4)
  ret <vscale x 4 x i32> %d
}

; Make sure we optimize the motivating case from TOOLCHAIN-1358 to vmslt+vmerge.
; TODO: Is it worthwhile to get rid of the bitcasts around riscv.vmerge
define i128 @cmp_select(i128 %a.coerce, i128 %b.coerce, i128 %c.coerce, i128 %d.coerce) {
; CHECK-LABEL: @cmp_select(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[I:%.*]] = bitcast i128 [[A_COERCE:%.*]] to <4 x i32>
; CHECK-NEXT:    [[I1:%.*]] = bitcast i128 [[B_COERCE:%.*]] to <4 x i32>
; CHECK-NEXT:    [[I2:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> [[I]])
; CHECK-NEXT:    [[I3:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> [[I1]])
; CHECK-NEXT:    [[I4:%.*]] = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[I2]], <vscale x 4 x i32> [[I3]], i64 4)
; CHECK-NEXT:    [[I8:%.*]] = bitcast i128 [[C_COERCE:%.*]] to <4 x float>
; CHECK-NEXT:    [[I9:%.*]] = bitcast i128 [[D_COERCE:%.*]] to <4 x float>
; CHECK-NEXT:    [[I11:%.*]] = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> [[I8]])
; CHECK-NEXT:    [[I12:%.*]] = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> [[I9]])
; CHECK-NEXT:    [[I13:%.*]] = bitcast <vscale x 4 x float> [[I12]] to <vscale x 4 x i32>
; CHECK-NEXT:    [[I14:%.*]] = bitcast <vscale x 4 x float> [[I11]] to <vscale x 4 x i32>
; CHECK-NEXT:    [[I17:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> [[I13]], <vscale x 4 x i32> [[I14]], <vscale x 4 x i1> [[I4]], i64 4)
; CHECK-NEXT:    [[I18:%.*]] = bitcast <vscale x 4 x i32> [[I17]] to <vscale x 4 x float>
; CHECK-NEXT:    [[I19:%.*]] = call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> [[I18]])
; CHECK-NEXT:    [[I20:%.*]] = bitcast <4 x float> [[I19]] to i128
; CHECK-NEXT:    ret i128 [[I20]]
;
entry:
  %i = bitcast i128 %a.coerce to <4 x i32>
  %i1 = bitcast i128 %b.coerce to <4 x i32>
  %i2 = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> %i)
  %i3 = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> %i1)
  %i4 = call <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> %i2, <vscale x 4 x i32> %i3, i64 4)
  %i5 = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 0, i64 4)
  %i6 = call <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %i5, i32 -1, <vscale x 4 x i1> %i4, i64 4)
  %i7 = call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32> %i6)
  %i8 = bitcast i128 %c.coerce to <4 x float>
  %i9 = bitcast i128 %d.coerce to <4 x float>
  %i10 = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> %i7)
  %i11 = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %i8)
  %i12 = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %i9)
  %i13 = bitcast <vscale x 4 x float> %i12 to <vscale x 4 x i32>
  %i14 = bitcast <vscale x 4 x float> %i11 to <vscale x 4 x i32>
  %i15 = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %i13, <vscale x 4 x i32> %i14, i64 4)
  %i16 = call <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %i15, <vscale x 4 x i32> %i10, i64 4)
  %i17 = call <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> undef, <vscale x 4 x i32> %i13, <vscale x 4 x i32> %i16, i64 4)
  %i18 = bitcast <vscale x 4 x i32> %i17 to <vscale x 4 x float>
  %i19 = call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> %i18)
  %i20 = bitcast <4 x float> %i19 to i128
  ret i128 %i20
}

declare <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32>)
declare <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float>)
declare <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vxor.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vand.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, i64)
declare <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float>)
declare <vscale x 4 x i1> @llvm.riscv.vmslt.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32>, i32, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, i32, <vscale x 4 x i1>, i64)
declare <vscale x 4 x i32> @llvm.riscv.vmerge.nxv4i32.nxv4i32.i64(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i1>, i64)
declare <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32>)

define i32 @test_vmv_x_s_splat_constant_vl(i32 %x) {
; CHECK-LABEL: @test_vmv_x_s_splat_constant_vl(
; CHECK-NEXT:    ret i32 [[X:%.*]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 4)
  %b = call i32 @llvm.riscv.vmv.x.s.nxv4i32(<vscale x 4 x i32> %a)
  ret i32 %b
}

define i32 @test_vmv_x_s_splat_variable_vl(i32 %x, i64 %vl) {
; CHECK-LABEL: @test_vmv_x_s_splat_variable_vl(
; CHECK-NEXT:    ret i32 [[X:%.*]]
;
  %a = call <vscale x 4 x i32> @llvm.riscv.vmv.v.x.nxv4i32.i64(<vscale x 4 x i32> undef, i32 %x, i64 %vl)
  %b = call i32 @llvm.riscv.vmv.x.s.nxv4i32(<vscale x 4 x i32> %a)
  ret i32 %b
}
declare i32 @llvm.riscv.vmv.x.s.nxv4i32(<vscale x 4 x i32>)

define float @test_vfmv_splat_constant_vl(float %x) {
; CHECK-LABEL: @test_vfmv_splat_constant_vl(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 4)
  %b = call float @llvm.riscv.vfmv.f.s.nxv4f32(<vscale x 4 x float> %a)
  ret float %b
}

define float @test_vfmv_splat_variable_vl(float %x, i64 %vl) {
; CHECK-LABEL: @test_vfmv_splat_variable_vl(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %a = call <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float> undef, float %x, i64 %vl)
  %b = call float @llvm.riscv.vfmv.f.s.nxv4f32(<vscale x 4 x float> %a)
  ret float %b
}
declare <vscale x 4 x float> @llvm.riscv.vfmv.v.f.nxv4f32.i64(<vscale x 4 x float>, float, i64)
declare float @llvm.riscv.vfmv.f.s.nxv4f32(<vscale x 4 x float>)

define <vscale x 1 x float> @test_vfcvt_f_xu_v_to_vfwcvt_f_xu_v(<vscale x 1 x i16> %x) {
; CHECK-LABEL: @test_vfcvt_f_xu_v_to_vfwcvt_f_xu_v(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 1 x float> @llvm.riscv.vfwcvt.f.xu.v.nxv1f32.nxv1i16.i64(<vscale x 1 x float> undef, <vscale x 1 x i16> [[X:%.*]], i64 2)
; CHECK-NEXT:    ret <vscale x 1 x float> [[B]]
;
  %a = call <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> %x, i16 0, i64 2)
  %b = call <vscale x 1 x float> @llvm.riscv.vfcvt.f.xu.v.nxv1f32.nxv1i32.i64(<vscale x 1 x float> undef, <vscale x 1 x i32> %a, i64 2)
  ret <vscale x 1 x float> %b
}
declare <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32>, <vscale x 1 x i16>, i16, i64)
declare <vscale x 1 x float> @llvm.riscv.vfcvt.f.xu.v.nxv1f32.nxv1i32.i64(<vscale x 1 x float>, <vscale x 1 x i32>, i64)

define <vscale x 1 x float> @test_vfcvt_f_x_v_to_vfwcvt_f_x_v(<vscale x 1 x i16> %x) {
; CHECK-LABEL: @test_vfcvt_f_x_v_to_vfwcvt_f_x_v(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 1 x float> @llvm.riscv.vfwcvt.f.x.v.nxv1f32.nxv1i16.i64(<vscale x 1 x float> undef, <vscale x 1 x i16> [[X:%.*]], i64 2)
; CHECK-NEXT:    ret <vscale x 1 x float> [[B]]
;
  %a = call <vscale x 1 x i32> @llvm.riscv.vwadd.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> %x, i16 0, i64 2)
  %b = call <vscale x 1 x float> @llvm.riscv.vfcvt.f.x.v.nxv1f32.nxv1i32.i64(<vscale x 1 x float> undef, <vscale x 1 x i32> %a, i64 2)
  ret <vscale x 1 x float> %b
}
declare <vscale x 1 x i32> @llvm.riscv.vwadd.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32>, <vscale x 1 x i16>, i16, i64)
declare <vscale x 1 x float> @llvm.riscv.vfcvt.f.x.v.nxv1f32.nxv1i32.i64(<vscale x 1 x float>, <vscale x 1 x i32>, i64)

define <vscale x 1 x float> @test_vfcvt_f_xu_v_to_vfwcvt_f_xu_v_variable_vl(<vscale x 1 x i16> %x, i64 %vl) {
; CHECK-LABEL: @test_vfcvt_f_xu_v_to_vfwcvt_f_xu_v_variable_vl(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 1 x float> @llvm.riscv.vfwcvt.f.xu.v.nxv1f32.nxv1i16.i64(<vscale x 1 x float> undef, <vscale x 1 x i16> [[X:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x float> [[B]]
;
  %a = call <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> %x, i16 0, i64 %vl)
  %b = call <vscale x 1 x float> @llvm.riscv.vfcvt.f.xu.v.nxv1f32.nxv1i32.i64(<vscale x 1 x float> undef, <vscale x 1 x i32> %a, i64 %vl)
  ret <vscale x 1 x float> %b
}

define <vscale x 1 x float> @test_vfcvt_f_x_v_to_vfwcvt_f_x_v_variable_vl(<vscale x 1 x i16> %x, i64 %vl) {
; CHECK-LABEL: @test_vfcvt_f_x_v_to_vfwcvt_f_x_v_variable_vl(
; CHECK-NEXT:    [[B:%.*]] = call <vscale x 1 x float> @llvm.riscv.vfwcvt.f.x.v.nxv1f32.nxv1i16.i64(<vscale x 1 x float> undef, <vscale x 1 x i16> [[X:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 1 x float> [[B]]
;
  %a = call <vscale x 1 x i32> @llvm.riscv.vwadd.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> %x, i16 0, i64 %vl)
  %b = call <vscale x 1 x float> @llvm.riscv.vfcvt.f.x.v.nxv1f32.nxv1i32.i64(<vscale x 1 x float> undef, <vscale x 1 x i32> %a, i64 %vl)
  ret <vscale x 1 x float> %b
}

define void @mul_add_u8_1(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i8* nocapture %out) {
; CHECK-LABEL: @mul_add_u8_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, ptr [[IN_0:%.*]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, ptr [[IN_1:%.*]], i64 16)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmacc.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[TMP1]], <vscale x 2 x i8> [[TMP0]], <vscale x 2 x i8> [[TMP0]], i64 16, i64 1)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> [[TMP2]], ptr [[OUT:%.*]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 2 x i8>*
  %1 = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8>* %0, i64 16)
  %2 = tail call <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8> %1, <vscale x 2 x i8> %1, i64 16)
  %3 = bitcast i8* %in_1 to <vscale x 2 x i8>*
  %4 = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8>* %3, i64 16)
  %5 = tail call <vscale x 2 x i8> @llvm.riscv.vadd.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8> %2, <vscale x 2 x i8> %4, i64 16)
  %6 = bitcast i8* %out to <vscale x 2 x i8>*
  tail call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> %5, <vscale x 2 x i8>* %6, i64 16)
  ret void
}

define void @mul_add_u8_2(i8* nocapture readonly %in_0, i8 zeroext %in_1, i8* nocapture readonly %in_2, i8* nocapture %out) {
; CHECK-LABEL: @mul_add_u8_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, ptr [[IN_0:%.*]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, ptr [[IN_2:%.*]], i64 16)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmacc.nxv2i8.i8.i64(<vscale x 2 x i8> [[TMP1]], i8 [[IN_1:%.*]], <vscale x 2 x i8> [[TMP0]], i64 16, i64 1)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> [[TMP2]], ptr [[OUT:%.*]], i64 16)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 2 x i8>*
  %1 = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8>* %0, i64 16)
  %2 = tail call <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8> %1, i8 %in_1, i64 16)
  %3 = bitcast i8* %in_2 to <vscale x 2 x i8>*
  %4 = tail call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8>* %3, i64 16)
  %5 = tail call <vscale x 2 x i8> @llvm.riscv.vadd.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> undef, <vscale x 2 x i8> %2, <vscale x 2 x i8> %4, i64 16)
  %6 = bitcast i8* %out to <vscale x 2 x i8>*
  tail call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> %5, <vscale x 2 x i8>* %6, i64 16)
  ret void
}

declare <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>* nocapture, i64)
declare void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>* nocapture, i64)
declare <vscale x 2 x i8> @llvm.riscv.vadd.nxv2i8.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>, <vscale x 2 x i8>, i64)
declare <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.nxv2i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>, <vscale x 2 x i8>, i64)
declare <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.i8.i64(<vscale x 2 x i8>, <vscale x 2 x i8>, i8, i64)

declare void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>* nocapture, i64)
declare <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16>, <vscale x 1 x i8>, i8, i64)
declare <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8>, <vscale x 1 x i8>* nocapture, i64)
declare <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16>, <vscale x 1 x i8>, i8, i64)

declare <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>* nocapture, i64)

define void @vwsll_or(i8* nocapture readonly %in_0, i8* nocapture readonly %in_1, i16* nocapture %out) {
; CHECK-LABEL: @vwsll_or(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.nxv1i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP0]], <vscale x 1 x i8> [[TMP1]], i64 8)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vwmaccu.nxv1i16.i8.nxv1i8.i64(<vscale x 1 x i16> [[TMP2]], i8 -1, <vscale x 1 x i8> [[TMP0]], i64 8, i64 1)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> [[TMP3]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i8* %in_0 to <vscale x 1 x i8>*
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %0, i64 8)
  %2 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %1, i8 0, i64 8)
  %3 = tail call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %2, i64 8, i64 8)
  %4 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %5 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %4, i64 8)
  %6 = tail call <vscale x 1 x i16> @llvm.riscv.vwaddu.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %5, i8 0, i64 8)
  %7 = tail call <vscale x 1 x i16> @llvm.riscv.vor.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %3, <vscale x 1 x i16> %6, i64 8)
  %8 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %7, <vscale x 1 x i16>* %8, i64 8)
  ret void
}

declare <vscale x 1 x i16> @llvm.riscv.vor.nxv1i16.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>, <vscale x 1 x i16>, i64)
declare <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define void @vmacc_vwsll_s(i16* nocapture readonly %in_0, i8* nocapture readonly %in_1, i8* nocapture readonly %in_2, i16* nocapture %out) {
; CHECK-LABEL: @vmacc_vwsll_s(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16> undef, ptr [[IN_0:%.*]], i64 8)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, ptr [[IN_1:%.*]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP1]], i8 0, i64 8)
; CHECK-NEXT:    [[TMP3:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP2]], i64 0, i64 8)
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, ptr [[IN_2:%.*]], i64 8)
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> [[TMP4]], i8 0, i64 8)
; CHECK-NEXT:    [[TMP6:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> [[TMP5]], i64 0, i64 8)
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vmacc.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[TMP0]], <vscale x 1 x i16> [[TMP3]], <vscale x 1 x i16> [[TMP6]], i64 8, i64 0)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> [[TMP7]], ptr [[OUT:%.*]], i64 8)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i16* %in_0 to <vscale x 1 x i16>*
  %1 = tail call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16>* %0, i64 8)
  %2 = bitcast i8* %in_1 to <vscale x 1 x i8>*
  %3 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %2, i64 8)
  %4 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %3, i8 0, i64 8)
  %5 = tail call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %4, i64 0, i64 8)
  %6 = bitcast i8* %in_2 to <vscale x 1 x i8>*
  %7 = tail call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.i64(<vscale x 1 x i8> undef, <vscale x 1 x i8>* %6, i64 8)
  %8 = tail call <vscale x 1 x i16> @llvm.riscv.vwadd.nxv1i16.nxv1i8.i8.i64(<vscale x 1 x i16> undef, <vscale x 1 x i8> %7, i8 0, i64 8)
  %9 = tail call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16.i64.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16> %8, i64 0, i64 8)
  %10 = tail call <vscale x 1 x i16> @llvm.riscv.vmacc.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> %1, <vscale x 1 x i16> %5, <vscale x 1 x i16> %9, i64 8, i64 0)
  %11 = bitcast i16* %out to <vscale x 1 x i16>*
  tail call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> %10, <vscale x 1 x i16>* %11, i64 8)
  ret void
}

define void @vmacc_vwsll_u(i32* nocapture readonly %in_0, i16* nocapture readonly %in_1, i16* nocapture readonly %in_2, i32* nocapture %out) {
; CHECK-LABEL: @vmacc_vwsll_u(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32> undef, ptr [[IN_0:%.*]], i64 4)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16> undef, ptr [[IN_1:%.*]], i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> [[TMP1]], i16 0, i64 4)
; CHECK-NEXT:    [[TMP3:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP2]], i64 0, i64 4)
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16> undef, ptr [[IN_2:%.*]], i64 4)
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> [[TMP4]], i16 0, i64 4)
; CHECK-NEXT:    [[TMP6:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> [[TMP5]], i64 0, i64 4)
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vmacc.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[TMP0]], <vscale x 1 x i32> [[TMP3]], <vscale x 1 x i32> [[TMP6]], i64 4, i64 0)
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> [[TMP7]], ptr [[OUT:%.*]], i64 4)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i32* %in_0 to <vscale x 1 x i32>*
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32>* %0, i64 4)
  %2 = bitcast i16* %in_1 to <vscale x 1 x i16>*
  %3 = tail call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16>* %2, i64 4)
  %4 = tail call <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> %3, i16 0, i64 4)
  %5 = tail call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> %4, i64 0, i64 4)
  %6 = bitcast i16* %in_2 to <vscale x 1 x i16>*
  %7 = tail call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.i64(<vscale x 1 x i16> undef, <vscale x 1 x i16>* %6, i64 4)
  %8 = tail call <vscale x 1 x i32> @llvm.riscv.vwaddu.nxv1i32.nxv1i16.i16.i64(<vscale x 1 x i32> undef, <vscale x 1 x i16> %7, i16 0, i64 4)
  %9 = tail call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> %8, i64 0, i64 4)
  %10 = tail call <vscale x 1 x i32> @llvm.riscv.vmacc.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> %1, <vscale x 1 x i32> %5, <vscale x 1 x i32> %9, i64 4, i64 0)
  %11 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %10, <vscale x 1 x i32>* %11, i64 4)
  ret void
}

declare <vscale x 1 x i16> @llvm.riscv.vmacc.nxv1i16.nxv1i16.i64(<vscale x 1 x i16>, <vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)
declare void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>* nocapture, i64)
declare <vscale x 1 x i32> @llvm.riscv.vmacc.nxv1i32.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)
declare <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>* nocapture, i64)
declare <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32.i64.i64(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)
