; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -instcombine -S | FileCheck %s

define void @mix_slidedown_slidedown_u(i32* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @mix_slidedown_slidedown_u(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 1 x i32>*
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32>* [[TMP0]], i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vector.insert.nxv2i32.nxv1i32(<vscale x 2 x i32> undef, <vscale x 1 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <vscale x 2 x i32> [[TMP2]] to <vscale x 1 x i64>
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP3]], i64 32, i64 2)
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 1 x i32>*
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> [[TMP4]], <vscale x 1 x i32>* [[TMP5]], i64 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i32* %in to <vscale x 1 x i32>*
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32>* %0, i64 4)
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vslidedown.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> %1, i64 2, i64 2)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vslidedown.nxv1i32.i64(<vscale x 1 x i32> %2, <vscale x 1 x i32> %1, i64 1, i64 1)
  %4 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %3, <vscale x 1 x i32>* %4, i64 2)
  ret void
}

define void @mix_slidedown_slidedown_i(i32* nocapture readonly %in, i32* nocapture %out) {
; CHECK-LABEL: @mix_slidedown_slidedown_i(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i32* [[IN:%.*]] to <vscale x 1 x i32>*
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32>* [[TMP0]], i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vector.insert.nxv2i32.nxv1i32(<vscale x 2 x i32> undef, <vscale x 1 x i32> [[TMP1]], i64 0)
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast <vscale x 2 x i32> [[TMP2]] to <vscale x 1 x i64>
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP3]], i64 32, i64 2)
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast i32* [[OUT:%.*]] to <vscale x 1 x i32>*
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> [[TMP4]], <vscale x 1 x i32>* [[TMP5]], i64 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i32* %in to <vscale x 1 x i32>*
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32>* %0, i64 4)
  %2 = tail call <vscale x 1 x i32> @llvm.riscv.vslidedown.nxv1i32.i64(<vscale x 1 x i32> undef, <vscale x 1 x i32> %1, i64 2, i64 2)
  %3 = tail call <vscale x 1 x i32> @llvm.riscv.vslidedown.nxv1i32.i64(<vscale x 1 x i32> %2, <vscale x 1 x i32> %1, i64 1, i64 1)
  %4 = bitcast i32* %out to <vscale x 1 x i32>*
  tail call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> %3, <vscale x 1 x i32>* %4, i64 2)
  ret void
}

define void @mix_slidedown_slidedown_f(float* nocapture readonly %in, float* nocapture %out) {
; CHECK-LABEL: @mix_slidedown_slidedown_f(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast float* [[IN:%.*]] to <vscale x 1 x float>*
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* [[TMP0]], i64 4)
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast <vscale x 1 x float> [[TMP1]] to <vscale x 1 x i32>
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vector.insert.nxv2i32.nxv1i32(<vscale x 2 x i32> undef, <vscale x 1 x i32> [[TMP2]], i64 0)
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <vscale x 2 x i32> [[TMP3]] to <vscale x 1 x i64>
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64.i64.i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> [[TMP4]], i64 32, i64 2)
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast <vscale x 1 x i32> [[TMP5]] to <vscale x 1 x float>
; CHECK-NEXT:    [[TMP7:%.*]] = bitcast float* [[OUT:%.*]] to <vscale x 1 x float>*
; CHECK-NEXT:    tail call void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float> [[TMP6]], <vscale x 1 x float>* [[TMP7]], i64 2)
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast float* %in to <vscale x 1 x float>*
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float>* %0, i64 4)
  %2 = tail call <vscale x 1 x float> @llvm.riscv.vslidedown.nxv1f32.i64(<vscale x 1 x float> undef, <vscale x 1 x float> %1, i64 2, i64 2)
  %3 = tail call <vscale x 1 x float> @llvm.riscv.vslidedown.nxv1f32.i64(<vscale x 1 x float> %2, <vscale x 1 x float> %1, i64 1, i64 1)
  %4 = bitcast float* %out to <vscale x 1 x float>*
  tail call void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float> %3, <vscale x 1 x float>* %4, i64 2)
  ret void
}

declare <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>* nocapture, i64)
declare void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>* nocapture, i64)
declare <vscale x 1 x i32> @llvm.riscv.vslidedown.nxv1i32.i64(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)
declare void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)
declare <vscale x 1 x float> @llvm.riscv.vslidedown.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>, i64, i64)
declare <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.i64(<vscale x 1 x float>, <vscale x 1 x float>* nocapture, i64)
