; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -instcombine -S | FileCheck %s

declare <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16>, <vscale x 8 x i8>, i8, i64) #2
declare <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16>, <vscale x 8 x i8>, i8, i64) #2
declare <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16>, <vscale x 8 x i8>, i64) #2
declare <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16>, <vscale x 8 x i8>, i64) #2
declare <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, i64, i64) #2
declare <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double>, <vscale x 2 x float>, i64) #2
declare <vscale x 2 x double> @llvm.riscv.vfmacc.nxv2f64.nxv2f64.i64(<vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, i64, i64) #2
declare <vscale x 2 x double> @llvm.riscv.vfnmacc.nxv2f64.nxv2f64.i64(<vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, i64, i64) #2
declare <vscale x 2 x double> @llvm.riscv.vfmsac.nxv2f64.nxv2f64.i64(<vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, i64, i64) #2
declare <vscale x 2 x double> @llvm.riscv.vfnmsac.nxv2f64.nxv2f64.i64(<vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, i64, i64) #2

define <vscale x 8 x i16> @wcvt_macc_1(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_macc_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmacc.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_macc_2(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_macc_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmacc.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_macc_3(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_macc_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmacc.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_macc_4(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_macc_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmacc.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccu_1(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccu_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccu_3(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccu_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccu_2(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccu_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccu_4(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccu_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_1(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_2(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %1, <vscale x 8 x i16> %0, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_3(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_4(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vwadd.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i8 0, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %1, <vscale x 8 x i16> %0, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_5(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_5(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_6(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_6(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vwaddu.nxv8i16.nxv8i8.i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i8 0, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %1, <vscale x 8 x i16> %0, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_7(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_7(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 8 x i16> @wcvt_maccsu_8(<vscale x 8 x i16> %d, <vscale x 8 x i8> %x, <vscale x 8 x i8> %y, i64 %vl) {
; CHECK-LABEL: @wcvt_maccsu_8(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vwmaccsu.nxv8i16.nxv8i8.nxv8i8.i64(<vscale x 8 x i16> [[D:%.*]], <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
;
entry:
  %0 = call <vscale x 8 x i16> @llvm.riscv.vsext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %x, i64 %vl)
  %1 = call <vscale x 8 x i16> @llvm.riscv.vzext.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> undef, <vscale x 8 x i8> %y, i64 %vl)
  %2 = call <vscale x 8 x i16> @llvm.riscv.vmacc.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> %d, <vscale x 8 x i16> %1, <vscale x 8 x i16> %0, i64 %vl, i64 0)
  ret <vscale x 8 x i16> %2
}

define <vscale x 2 x double> @fwcvt_fmacc(<vscale x 2 x double> %d, <vscale x 2 x float> %x, <vscale x 2 x float> %y, i64 %vl) {
; CHECK-LABEL: @fwcvt_fmacc(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vfwmacc.nxv2f64.nxv2f32.nxv2f32.i64(<vscale x 2 x double> [[D:%.*]], <vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x double> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %x, i64 %vl)
  %1 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %y, i64 %vl)
  %2 = call <vscale x 2 x double> @llvm.riscv.vfmacc.nxv2f64.nxv2f64.i64(<vscale x 2 x double> %d, <vscale x 2 x double> %0, <vscale x 2 x double> %1, i64 %vl, i64 0)
  ret <vscale x 2 x double> %2
}

define <vscale x 2 x double> @fwcvt_fnmacc(<vscale x 2 x double> %d, <vscale x 2 x float> %x, <vscale x 2 x float> %y, i64 %vl) {
; CHECK-LABEL: @fwcvt_fnmacc(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vfwnmacc.nxv2f64.nxv2f32.nxv2f32.i64(<vscale x 2 x double> [[D:%.*]], <vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x double> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %x, i64 %vl)
  %1 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %y, i64 %vl)
  %2 = call <vscale x 2 x double> @llvm.riscv.vfnmacc.nxv2f64.nxv2f64.i64(<vscale x 2 x double> %d, <vscale x 2 x double> %0, <vscale x 2 x double> %1, i64 %vl, i64 0)
  ret <vscale x 2 x double> %2
}

define <vscale x 2 x double> @fwcvt_fmsac(<vscale x 2 x double> %d, <vscale x 2 x float> %x, <vscale x 2 x float> %y, i64 %vl) {
; CHECK-LABEL: @fwcvt_fmsac(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vfwmsac.nxv2f64.nxv2f32.nxv2f32.i64(<vscale x 2 x double> [[D:%.*]], <vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x double> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %x, i64 %vl)
  %1 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %y, i64 %vl)
  %2 = call <vscale x 2 x double> @llvm.riscv.vfmsac.nxv2f64.nxv2f64.i64(<vscale x 2 x double> %d, <vscale x 2 x double> %0, <vscale x 2 x double> %1, i64 %vl, i64 0)
  ret <vscale x 2 x double> %2
}

define <vscale x 2 x double> @fwcvt_fnmsac(<vscale x 2 x double> %d, <vscale x 2 x float> %x, <vscale x 2 x float> %y, i64 %vl) {
; CHECK-LABEL: @fwcvt_fnmsac(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vfwnmsac.nxv2f64.nxv2f32.nxv2f32.i64(<vscale x 2 x double> [[D:%.*]], <vscale x 2 x float> [[X:%.*]], <vscale x 2 x float> [[Y:%.*]], i64 [[VL:%.*]])
; CHECK-NEXT:    ret <vscale x 2 x double> [[TMP0]]
;
entry:
  %0 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %x, i64 %vl)
  %1 = call <vscale x 2 x double> @llvm.riscv.vfwcvt.f.f.v.nxv2f64.nxv2f32.i64(<vscale x 2 x double> undef, <vscale x 2 x float> %y, i64 %vl)
  %2 = call <vscale x 2 x double> @llvm.riscv.vfnmsac.nxv2f64.nxv2f64.i64(<vscale x 2 x double> %d, <vscale x 2 x double> %0, <vscale x 2 x double> %1, i64 %vl, i64 0)
  ret <vscale x 2 x double> %2
}
