; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;RUN: opt %s -passes=instcombine -S | FileCheck %s

declare <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.or.nxv2i32(<vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x i1>, i32)

define <vscale x 2 x i32> @add_null(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl) {
; CHECK-LABEL: @add_null(
; CHECK-NEXT:    ret <vscale x 2 x i32> [[X:%.*]]
;
  %a = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i32> zeroinitializer, <vscale x 2 x i1> %mask1, i32 %vl)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @add_null1(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl) {
; CHECK-LABEL: @add_null1(
; CHECK-NEXT:    ret <vscale x 2 x i32> [[X:%.*]]
;
  %a = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> zeroinitializer, <vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @or_null(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl) {
; CHECK-LABEL: @or_null(
; CHECK-NEXT:    ret <vscale x 2 x i32> [[X:%.*]]
;
  %a = call <vscale x 2 x i32> @llvm.vp.or.nxv2i32(<vscale x 2 x i32> %x, <vscale x 2 x i32> zeroinitializer, <vscale x 2 x i1> %mask1, i32 %vl)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @or_null1(<vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl) {
; CHECK-LABEL: @or_null1(
; CHECK-NEXT:    ret <vscale x 2 x i32> [[X:%.*]]
;
  %a = call <vscale x 2 x i32> @llvm.vp.or.nxv2i32(<vscale x 2 x i32> zeroinitializer, <vscale x 2 x i32> %x, <vscale x 2 x i1> %mask1, i32 %vl)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x float> @fadd_null(<vscale x 2 x float> %x, <vscale x 2 x i1> %mask1, i32 %vl) {
; CHECK-LABEL: @fadd_null(
; CHECK-NEXT:    ret <vscale x 2 x float> [[X:%.*]]
;
  %a = call fast <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float> %x, <vscale x 2 x float> zeroinitializer, <vscale x 2 x i1> %mask1, i32 %vl)
  ret <vscale x 2 x float> %a
}

define <vscale x 2 x float> @fadd_null1(<vscale x 2 x float> %x, <vscale x 2 x i1> %mask1, i32 %vl) {
; CHECK-LABEL: @fadd_null1(
; CHECK-NEXT:    ret <vscale x 2 x float> [[X:%.*]]
;
  %a = call fast <vscale x 2 x float> @llvm.vp.fadd.nxv2f32(<vscale x 2 x float> zeroinitializer, <vscale x 2 x float> %x, <vscale x 2 x i1> %mask1, i32 %vl)
  ret <vscale x 2 x float> %a
}
