// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vle32_v_f32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.p0.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vle32_v_f32mf2_ntl_ALL(const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32mf2_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vle.nxv2f32.p0.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vle32_v_f32m1_ntl_ALL(const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m1_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.p0.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vle32_v_f32m2_ntl_ALL(const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m2_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vle.nxv8f32.p0.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vle32_v_f32m4_ntl_ALL(const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m4_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.p0.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vle32_v_f32m8_ntl_ALL(const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m8_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.p0.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vle32_v_i32mf2_ntl_ALL(const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32mf2_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vle.nxv2i32.p0.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vle32_v_i32m1_ntl_ALL(const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m1_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.p0.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vle32_v_i32m2_ntl_ALL(const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m2_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.p0.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vle32_v_i32m4_ntl_ALL(const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m4_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vle.nxv16i32.p0.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vle32_v_i32m8_ntl_ALL(const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m8_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.p0.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vle32_v_u32mf2_ntl_ALL(const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32mf2_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vle.nxv2i32.p0.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vle32_v_u32m1_ntl_ALL(const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m1_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.p0.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vle32_v_u32m2_ntl_ALL(const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m2_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.p0.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vle32_v_u32m4_ntl_ALL(const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m4_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vle.nxv16i32.p0.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vle32_v_u32m8_ntl_ALL(const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m8_ntl(base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vle.mask.nxv1f32.p0.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vle32_v_f32mf2_m_ntl_ALL(vbool64_t mask, const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32mf2_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vle.mask.nxv2f32.p0.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vle32_v_f32m1_m_ntl_ALL(vbool32_t mask, const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m1_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vle.mask.nxv4f32.p0.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vle32_v_f32m2_m_ntl_ALL(vbool16_t mask, const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m2_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vle.mask.nxv8f32.p0.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vle32_v_f32m4_m_ntl_ALL(vbool8_t mask, const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m4_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_f32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vle.mask.nxv16f32.p0.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vle32_v_f32m8_m_ntl_ALL(vbool4_t mask, const float *base, size_t vl, int domain) {
  return __riscv_vle32_v_f32m8_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vle.mask.nxv1i32.p0.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vle32_v_i32mf2_m_ntl_ALL(vbool64_t mask, const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32mf2_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vle.mask.nxv2i32.p0.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vle32_v_i32m1_m_ntl_ALL(vbool32_t mask, const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m1_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vle.mask.nxv4i32.p0.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vle32_v_i32m2_m_ntl_ALL(vbool16_t mask, const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m2_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vle.mask.nxv8i32.p0.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vle32_v_i32m4_m_ntl_ALL(vbool8_t mask, const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m4_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_i32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vle.mask.nxv16i32.p0.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vle32_v_i32m8_m_ntl_ALL(vbool4_t mask, const int32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_i32m8_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vle.mask.nxv1i32.p0.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vle32_v_u32mf2_m_ntl_ALL(vbool64_t mask, const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32mf2_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vle.mask.nxv2i32.p0.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vle32_v_u32m1_m_ntl_ALL(vbool32_t mask, const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m1_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vle.mask.nxv4i32.p0.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vle32_v_u32m2_m_ntl_ALL(vbool16_t mask, const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m2_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vle.mask.nxv8i32.p0.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vle32_v_u32m4_m_ntl_ALL(vbool8_t mask, const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m4_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vle32_v_u32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vle.mask.nxv16i32.p0.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vle32_v_u32m8_m_ntl_ALL(vbool4_t mask, const uint32_t *base, size_t vl, int domain) {
  return __riscv_vle32_v_u32m8_m_ntl(mask, base, vl, __RISCV_NTLH_ALL);
}

