// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vlse16_v_f16mf4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vlse.nxv1f16.p0.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vlse16_v_f16mf4_ntl_S1(const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16mf4_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16mf2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vlse.nxv2f16.p0.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vlse16_v_f16mf2_ntl_S1(const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16mf2_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m1_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vlse.nxv4f16.p0.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vlse16_v_f16m1_ntl_S1(const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m1_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vlse.nxv8f16.p0.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vlse16_v_f16m2_ntl_S1(const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m2_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vlse.nxv16f16.p0.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vlse16_v_f16m4_ntl_S1(const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m4_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m8_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vlse.nxv32f16.p0.i64(<vscale x 32 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vlse16_v_f16m8_ntl_S1(const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m8_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16mf4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vlse.nxv1i16.p0.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vlse16_v_i16mf4_ntl_S1(const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16mf4_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16mf2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vlse.nxv2i16.p0.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vlse16_v_i16mf2_ntl_S1(const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16mf2_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m1_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vlse.nxv4i16.p0.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vlse16_v_i16m1_ntl_S1(const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m1_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vlse.nxv8i16.p0.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vlse16_v_i16m2_ntl_S1(const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m2_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vlse.nxv16i16.p0.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vlse16_v_i16m4_ntl_S1(const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m4_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m8_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vlse.nxv32i16.p0.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vlse16_v_i16m8_ntl_S1(const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m8_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16mf4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vlse.nxv1i16.p0.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vlse16_v_u16mf4_ntl_S1(const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16mf4_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16mf2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vlse.nxv2i16.p0.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vlse16_v_u16mf2_ntl_S1(const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16mf2_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m1_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vlse.nxv4i16.p0.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vlse16_v_u16m1_ntl_S1(const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m1_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m2_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vlse.nxv8i16.p0.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vlse16_v_u16m2_ntl_S1(const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m2_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m4_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vlse.nxv16i16.p0.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vlse16_v_u16m4_ntl_S1(const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m4_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m8_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vlse.nxv32i16.p0.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vlse16_v_u16m8_ntl_S1(const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m8_ntl(base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16mf4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vlse.mask.nxv1f16.p0.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vlse16_v_f16mf4_m_ntl_S1(vbool64_t mask, const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16mf4_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16mf2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vlse.mask.nxv2f16.p0.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vlse16_v_f16mf2_m_ntl_S1(vbool32_t mask, const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16mf2_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m1_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vlse.mask.nxv4f16.p0.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vlse16_v_f16m1_m_ntl_S1(vbool16_t mask, const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m1_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vlse.mask.nxv8f16.p0.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vlse16_v_f16m2_m_ntl_S1(vbool8_t mask, const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m2_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vlse.mask.nxv16f16.p0.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vlse16_v_f16m4_m_ntl_S1(vbool4_t mask, const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m4_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_f16m8_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vlse.mask.nxv32f16.p0.i64(<vscale x 32 x half> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vlse16_v_f16m8_m_ntl_S1(vbool2_t mask, const _Float16 *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_f16m8_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16mf4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vlse.mask.nxv1i16.p0.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vlse16_v_i16mf4_m_ntl_S1(vbool64_t mask, const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16mf4_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16mf2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vlse.mask.nxv2i16.p0.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vlse16_v_i16mf2_m_ntl_S1(vbool32_t mask, const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16mf2_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m1_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vlse.mask.nxv4i16.p0.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vlse16_v_i16m1_m_ntl_S1(vbool16_t mask, const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m1_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vlse.mask.nxv8i16.p0.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vlse16_v_i16m2_m_ntl_S1(vbool8_t mask, const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m2_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vlse.mask.nxv16i16.p0.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vlse16_v_i16m4_m_ntl_S1(vbool4_t mask, const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m4_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_i16m8_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vlse.mask.nxv32i16.p0.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vlse16_v_i16m8_m_ntl_S1(vbool2_t mask, const int16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_i16m8_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16mf4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vlse.mask.nxv1i16.p0.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vlse16_v_u16mf4_m_ntl_S1(vbool64_t mask, const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16mf4_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16mf2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vlse.mask.nxv2i16.p0.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vlse16_v_u16mf2_m_ntl_S1(vbool32_t mask, const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16mf2_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m1_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vlse.mask.nxv4i16.p0.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vlse16_v_u16m1_m_ntl_S1(vbool16_t mask, const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m1_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m2_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vlse.mask.nxv8i16.p0.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vlse16_v_u16m2_m_ntl_S1(vbool8_t mask, const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m2_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m4_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vlse.mask.nxv16i16.p0.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vlse16_v_u16m4_m_ntl_S1(vbool4_t mask, const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m4_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

// CHECK-LABEL: @test_vlse16_v_u16m8_m_ntl_S1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vlse.mask.nxv32i16.p0.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vlse16_v_u16m8_m_ntl_S1(vbool2_t mask, const uint16_t *base, ptrdiff_t bstride, size_t vl, int domain) {
  return __riscv_vlse16_v_u16m8_m_ntl(mask, base, bstride, vl, __RISCV_NTLH_INNERMOST_SHARED);
}

