// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vluxei16_v_f16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.nxv1f16.p0.nxv1i16.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei16_v_f16mf4_ntl_ALL(const _Float16 *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16mf4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.nxv2f16.p0.nxv2i16.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei16_v_f16mf2_ntl_ALL(const _Float16 *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.nxv4f16.p0.nxv4i16.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei16_v_f16m1_ntl_ALL(const _Float16 *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.nxv8f16.p0.nxv8i16.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei16_v_f16m2_ntl_ALL(const _Float16 *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.nxv16f16.p0.nxv16i16.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei16_v_f16m4_ntl_ALL(const _Float16 *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vluxei.nxv32f16.p0.nxv32i16.i64(<vscale x 32 x half> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vluxei16_v_f16m8_ntl_ALL(const _Float16 *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.nxv1f32.p0.nxv1i16.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei16_v_f32mf2_ntl_ALL(const float *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.nxv2f32.p0.nxv2i16.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei16_v_f32m1_ntl_ALL(const float *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.nxv4f32.p0.nxv4i16.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei16_v_f32m2_ntl_ALL(const float *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.nxv8f32.p0.nxv8i16.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei16_v_f32m4_ntl_ALL(const float *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.nxv16f32.p0.nxv16i16.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei16_v_f32m8_ntl_ALL(const float *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.nxv1f64.p0.nxv1i16.i64(<vscale x 1 x double> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei16_v_f64m1_ntl_ALL(const double *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.nxv2f64.p0.nxv2i16.i64(<vscale x 2 x double> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei16_v_f64m2_ntl_ALL(const double *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.nxv4f64.p0.nxv4i16.i64(<vscale x 4 x double> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei16_v_f64m4_ntl_ALL(const double *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.nxv8f64.p0.nxv8i16.i64(<vscale x 8 x double> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei16_v_f64m8_ntl_ALL(const double *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8mf8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei16_v_i8mf8_ntl_ALL(const int8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8mf8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei16_v_i8mf4_ntl_ALL(const int8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8mf4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei16_v_i8mf2_ntl_ALL(const int8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei16_v_i8m1_ntl_ALL(const int8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei16_v_i8m2_ntl_ALL(const int8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vluxei16_v_i8m4_ntl_ALL(const int8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei16_v_i16mf4_ntl_ALL(const int16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16mf4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei16_v_i16mf2_ntl_ALL(const int16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei16_v_i16m1_ntl_ALL(const int16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei16_v_i16m2_ntl_ALL(const int16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei16_v_i16m4_ntl_ALL(const int16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vluxei16_v_i16m8_ntl_ALL(const int16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei16_v_i32mf2_ntl_ALL(const int32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei16_v_i32m1_ntl_ALL(const int32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei16_v_i32m2_ntl_ALL(const int32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei16_v_i32m4_ntl_ALL(const int32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei16_v_i32m8_ntl_ALL(const int32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei16_v_i64m1_ntl_ALL(const int64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei16_v_i64m2_ntl_ALL(const int64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei16_v_i64m4_ntl_ALL(const int64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei16_v_i64m8_ntl_ALL(const int64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8mf8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei16_v_u8mf8_ntl_ALL(const uint8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8mf8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei16_v_u8mf4_ntl_ALL(const uint8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8mf4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei16_v_u8mf2_ntl_ALL(const uint8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei16_v_u8m1_ntl_ALL(const uint8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei16_v_u8m2_ntl_ALL(const uint8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vluxei16_v_u8m4_ntl_ALL(const uint8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei16_v_u16mf4_ntl_ALL(const uint16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16mf4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei16_v_u16mf2_ntl_ALL(const uint16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei16_v_u16m1_ntl_ALL(const uint16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei16_v_u16m2_ntl_ALL(const uint16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei16_v_u16m4_ntl_ALL(const uint16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vluxei16_v_u16m8_ntl_ALL(const uint16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei16_v_u32mf2_ntl_ALL(const uint32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32mf2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei16_v_u32m1_ntl_ALL(const uint32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei16_v_u32m2_ntl_ALL(const uint32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei16_v_u32m4_ntl_ALL(const uint32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei16_v_u32m8_ntl_ALL(const uint32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei16_v_u64m1_ntl_ALL(const uint64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m1_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei16_v_u64m2_ntl_ALL(const uint64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m2_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei16_v_u64m4_ntl_ALL(const uint64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m4_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei16_v_u64m8_ntl_ALL(const uint64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.mask.nxv1f16.p0.nxv1i16.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei16_v_f16mf4_m_ntl_ALL(vbool64_t mask, const _Float16 *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16mf4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.mask.nxv2f16.p0.nxv2i16.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei16_v_f16mf2_m_ntl_ALL(vbool32_t mask, const _Float16 *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.mask.nxv4f16.p0.nxv4i16.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei16_v_f16m1_m_ntl_ALL(vbool16_t mask, const _Float16 *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.mask.nxv8f16.p0.nxv8i16.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei16_v_f16m2_m_ntl_ALL(vbool8_t mask, const _Float16 *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.mask.nxv16f16.p0.nxv16i16.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei16_v_f16m4_m_ntl_ALL(vbool4_t mask, const _Float16 *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vluxei.mask.nxv32f16.p0.nxv32i16.i64(<vscale x 32 x half> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vluxei16_v_f16m8_m_ntl_ALL(vbool2_t mask, const _Float16 *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f16m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.mask.nxv1f32.p0.nxv1i16.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei16_v_f32mf2_m_ntl_ALL(vbool64_t mask, const float *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.mask.nxv2f32.p0.nxv2i16.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei16_v_f32m1_m_ntl_ALL(vbool32_t mask, const float *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.mask.nxv4f32.p0.nxv4i16.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei16_v_f32m2_m_ntl_ALL(vbool16_t mask, const float *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.mask.nxv8f32.p0.nxv8i16.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei16_v_f32m4_m_ntl_ALL(vbool8_t mask, const float *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.mask.nxv16f32.p0.nxv16i16.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei16_v_f32m8_m_ntl_ALL(vbool4_t mask, const float *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f32m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.mask.nxv1f64.p0.nxv1i16.i64(<vscale x 1 x double> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei16_v_f64m1_m_ntl_ALL(vbool64_t mask, const double *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.mask.nxv2f64.p0.nxv2i16.i64(<vscale x 2 x double> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei16_v_f64m2_m_ntl_ALL(vbool32_t mask, const double *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.mask.nxv4f64.p0.nxv4i16.i64(<vscale x 4 x double> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei16_v_f64m4_m_ntl_ALL(vbool16_t mask, const double *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_f64m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.mask.nxv8f64.p0.nxv8i16.i64(<vscale x 8 x double> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei16_v_f64m8_m_ntl_ALL(vbool8_t mask, const double *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_f64m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8mf8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei16_v_i8mf8_m_ntl_ALL(vbool64_t mask, const int8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8mf8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei16_v_i8mf4_m_ntl_ALL(vbool32_t mask, const int8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8mf4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei16_v_i8mf2_m_ntl_ALL(vbool16_t mask, const int8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei16_v_i8m1_m_ntl_ALL(vbool8_t mask, const int8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei16_v_i8m2_m_ntl_ALL(vbool4_t mask, const int8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i8m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.mask.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vluxei16_v_i8m4_m_ntl_ALL(vbool2_t mask, const int8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i8m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei16_v_i16mf4_m_ntl_ALL(vbool64_t mask, const int16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16mf4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei16_v_i16mf2_m_ntl_ALL(vbool32_t mask, const int16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei16_v_i16m1_m_ntl_ALL(vbool16_t mask, const int16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei16_v_i16m2_m_ntl_ALL(vbool8_t mask, const int16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei16_v_i16m4_m_ntl_ALL(vbool4_t mask, const int16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.mask.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vluxei16_v_i16m8_m_ntl_ALL(vbool2_t mask, const int16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i16m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei16_v_i32mf2_m_ntl_ALL(vbool64_t mask, const int32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei16_v_i32m1_m_ntl_ALL(vbool32_t mask, const int32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei16_v_i32m2_m_ntl_ALL(vbool16_t mask, const int32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei16_v_i32m4_m_ntl_ALL(vbool8_t mask, const int32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei16_v_i32m8_m_ntl_ALL(vbool4_t mask, const int32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i32m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei16_v_i64m1_m_ntl_ALL(vbool64_t mask, const int64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei16_v_i64m2_m_ntl_ALL(vbool32_t mask, const int64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei16_v_i64m4_m_ntl_ALL(vbool16_t mask, const int64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_i64m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei16_v_i64m8_m_ntl_ALL(vbool8_t mask, const int64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_i64m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8mf8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.p0.nxv1i16.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei16_v_u8mf8_m_ntl_ALL(vbool64_t mask, const uint8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8mf8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.p0.nxv2i16.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei16_v_u8mf4_m_ntl_ALL(vbool32_t mask, const uint8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8mf4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.p0.nxv4i16.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei16_v_u8mf2_m_ntl_ALL(vbool16_t mask, const uint8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.p0.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei16_v_u8m1_m_ntl_ALL(vbool8_t mask, const uint8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.p0.nxv16i16.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei16_v_u8m2_m_ntl_ALL(vbool4_t mask, const uint8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u8m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.mask.nxv32i8.p0.nxv32i16.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vluxei16_v_u8m4_m_ntl_ALL(vbool2_t mask, const uint8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u8m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.p0.nxv1i16.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei16_v_u16mf4_m_ntl_ALL(vbool64_t mask, const uint16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16mf4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.p0.nxv2i16.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei16_v_u16mf2_m_ntl_ALL(vbool32_t mask, const uint16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.p0.nxv4i16.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei16_v_u16m1_m_ntl_ALL(vbool16_t mask, const uint16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.p0.nxv8i16.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei16_v_u16m2_m_ntl_ALL(vbool8_t mask, const uint16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.p0.nxv16i16.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei16_v_u16m4_m_ntl_ALL(vbool4_t mask, const uint16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u16m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.mask.nxv32i16.p0.nxv32i16.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vluxei16_v_u16m8_m_ntl_ALL(vbool2_t mask, const uint16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u16m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.p0.nxv1i16.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei16_v_u32mf2_m_ntl_ALL(vbool64_t mask, const uint32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32mf2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.p0.nxv2i16.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei16_v_u32m1_m_ntl_ALL(vbool32_t mask, const uint32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.p0.nxv4i16.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei16_v_u32m2_m_ntl_ALL(vbool16_t mask, const uint32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.p0.nxv8i16.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei16_v_u32m4_m_ntl_ALL(vbool8_t mask, const uint32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u32m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.p0.nxv16i16.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei16_v_u32m8_m_ntl_ALL(vbool4_t mask, const uint32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u32m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.p0.nxv1i16.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei16_v_u64m1_m_ntl_ALL(vbool64_t mask, const uint64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m1_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.p0.nxv2i16.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei16_v_u64m2_m_ntl_ALL(vbool32_t mask, const uint64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m2_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.p0.nxv4i16.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei16_v_u64m4_m_ntl_ALL(vbool16_t mask, const uint64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m4_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vluxei16_v_u64m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.p0.nxv8i16.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 3), !nontemporal [[META6]]
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei16_v_u64m8_m_ntl_ALL(vbool8_t mask, const uint64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return __riscv_vluxei16_v_u64m8_m_ntl(mask, base, bindex, vl, __RISCV_NTLH_ALL);
}

