// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh \
// RUN:   -target-feature +zvfh -disable-O0-optnone  \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1f32.p0.i64(<vscale x 1 x float> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6:![0-9]+]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32mf2_ntl_ALL(float *base, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32mf2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2f32.p0.i64(<vscale x 2 x float> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m1_ntl_ALL(float *base, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m1_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4f32.p0.i64(<vscale x 4 x float> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m2_ntl_ALL(float *base, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8f32.p0.i64(<vscale x 8 x float> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m4_ntl_ALL(float *base, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16f32.p0.i64(<vscale x 16 x float> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m8_ntl_ALL(float *base, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32mf2_ntl_ALL(int32_t *base, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32mf2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m1_ntl_ALL(int32_t *base, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m1_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m2_ntl_ALL(int32_t *base, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m4_ntl_ALL(int32_t *base, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m8_ntl_ALL(int32_t *base, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32mf2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32mf2_ntl_ALL(uint32_t *base, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32mf2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m1_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m1_ntl_ALL(uint32_t *base, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m1_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m2_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m2_ntl_ALL(uint32_t *base, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m4_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m4_ntl_ALL(uint32_t *base, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m8_ntl_ALL
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m8_ntl_ALL(uint32_t *base, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1f32.p0.i64(<vscale x 1 x float> [[VALUE]], ptr [[BASE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32mf2_m_ntl_ALL(vbool64_t mask, float *base, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2f32.p0.i64(<vscale x 2 x float> [[VALUE]], ptr [[BASE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m1_m_ntl_ALL(vbool32_t mask, float *base, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4f32.p0.i64(<vscale x 4 x float> [[VALUE]], ptr [[BASE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m2_m_ntl_ALL(vbool16_t mask, float *base, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8f32.p0.i64(<vscale x 8 x float> [[VALUE]], ptr [[BASE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m4_m_ntl_ALL(vbool8_t mask, float *base, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_f32m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x float> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16f32.p0.i64(<vscale x 16 x float> [[VALUE]], ptr [[BASE]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m8_m_ntl_ALL(vbool4_t mask, float *base, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32mf2_m_ntl_ALL(vbool64_t mask, int32_t *base, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m1_m_ntl_ALL(vbool32_t mask, int32_t *base, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m2_m_ntl_ALL(vbool16_t mask, int32_t *base, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m4_m_ntl_ALL(vbool8_t mask, int32_t *base, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_i32m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m8_m_ntl_ALL(vbool4_t mask, int32_t *base, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32mf2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 1 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE]], ptr [[BASE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32mf2_m_ntl_ALL(vbool64_t mask, uint32_t *base, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m1_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 2 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE]], ptr [[BASE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m1_m_ntl_ALL(vbool32_t mask, uint32_t *base, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m2_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 4 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE]], ptr [[BASE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m2_m_ntl_ALL(vbool16_t mask, uint32_t *base, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m4_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 8 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE]], ptr [[BASE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m4_m_ntl_ALL(vbool8_t mask, uint32_t *base, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-RV64-LABEL: define dso_local void @test_vse32_v_u32m8_m_ntl_ALL
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], <vscale x 16 x i32> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE]], ptr [[BASE]], <vscale x 16 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m8_m_ntl_ALL(vbool4_t mask, uint32_t *base, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

