// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vse32_v_f32mf2_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1f32.p0.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32mf2_ntl_PALL(float *base, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32mf2_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m1_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2f32.p0.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m1_ntl_PALL(float *base, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m1_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m2_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4f32.p0.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m2_ntl_PALL(float *base, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m2_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m4_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8f32.p0.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m4_ntl_PALL(float *base, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m4_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m8_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv16f32.p0.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m8_ntl_PALL(float *base, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32mf2_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32mf2_ntl_PALL(int32_t *base, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32mf2_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m1_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m1_ntl_PALL(int32_t *base, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m1_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m2_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m2_ntl_PALL(int32_t *base, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m2_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m4_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m4_ntl_PALL(int32_t *base, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m4_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m8_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m8_ntl_PALL(int32_t *base, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32mf2_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32mf2_ntl_PALL(uint32_t *base, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32mf2_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m1_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m1_ntl_PALL(uint32_t *base, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m1_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m2_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m2_ntl_PALL(uint32_t *base, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m2_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m4_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m4_ntl_PALL(uint32_t *base, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m4_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m8_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m8_ntl_PALL(uint32_t *base, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32mf2_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1f32.p0.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32mf2_m_ntl_PALL(vbool64_t mask, float *base, vfloat32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m1_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2f32.p0.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m1_m_ntl_PALL(vbool32_t mask, float *base, vfloat32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m2_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4f32.p0.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m2_m_ntl_PALL(vbool16_t mask, float *base, vfloat32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m4_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8f32.p0.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m4_m_ntl_PALL(vbool8_t mask, float *base, vfloat32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_f32m8_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv16f32.p0.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_f32m8_m_ntl_PALL(vbool4_t mask, float *base, vfloat32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_f32m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32mf2_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32mf2_m_ntl_PALL(vbool64_t mask, int32_t *base, vint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m1_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m1_m_ntl_PALL(vbool32_t mask, int32_t *base, vint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m2_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m2_m_ntl_PALL(vbool16_t mask, int32_t *base, vint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m4_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m4_m_ntl_PALL(vbool8_t mask, int32_t *base, vint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_i32m8_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_i32m8_m_ntl_PALL(vbool4_t mask, int32_t *base, vint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_i32m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32mf2_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1i32.p0.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32mf2_m_ntl_PALL(vbool64_t mask, uint32_t *base, vuint32mf2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m1_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2i32.p0.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m1_m_ntl_PALL(vbool32_t mask, uint32_t *base, vuint32m1_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m2_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4i32.p0.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m2_m_ntl_PALL(vbool16_t mask, uint32_t *base, vuint32m2_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m4_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8i32.p0.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m4_m_ntl_PALL(vbool8_t mask, uint32_t *base, vuint32m4_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

// CHECK-LABEL: @test_vse32_v_u32m8_m_ntl_PALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv16i32.p0.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse32_v_u32m8_m_ntl_PALL(vbool4_t mask, uint32_t *base, vuint32m8_t value, size_t vl, int domain) {
  return __riscv_vse32_v_u32m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}

