// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>
// CHECK-LABEL: @test_vse8_v_i8mf8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1i8.p0.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8mf8_ntl_ALL(int8_t *base, vint8mf8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8mf8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2i8.p0.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8mf4_ntl_ALL(int8_t *base, vint8mf4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8mf4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4i8.p0.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8mf2_ntl_ALL(int8_t *base, vint8mf2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8mf2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8i8.p0.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m1_ntl_ALL(int8_t *base, vint8m1_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m1_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i8.p0.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m2_ntl_ALL(int8_t *base, vint8m2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv32i8.p0.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m4_ntl_ALL(int8_t *base, vint8m4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv64i8.p0.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m8_ntl_ALL(int8_t *base, vint8m8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8mf8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv1i8.p0.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8mf8_ntl_ALL(uint8_t *base, vuint8mf8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8mf8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8mf4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv2i8.p0.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8mf4_ntl_ALL(uint8_t *base, vuint8mf4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8mf4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8mf2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv4i8.p0.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8mf2_ntl_ALL(uint8_t *base, vuint8mf2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8mf2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m1_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv8i8.p0.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m1_ntl_ALL(uint8_t *base, vuint8m1_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m1_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m2_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv16i8.p0.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m2_ntl_ALL(uint8_t *base, vuint8m2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m2_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m4_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv32i8.p0.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m4_ntl_ALL(uint8_t *base, vuint8m4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m4_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m8_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.nxv64i8.p0.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m8_ntl_ALL(uint8_t *base, vuint8m8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m8_ntl(base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8mf8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1i8.p0.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8mf8_m_ntl_ALL(vbool64_t mask, int8_t *base, vint8mf8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8mf8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2i8.p0.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8mf4_m_ntl_ALL(vbool32_t mask, int8_t *base, vint8mf4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8mf4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4i8.p0.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8mf2_m_ntl_ALL(vbool16_t mask, int8_t *base, vint8mf2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8i8.p0.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m1_m_ntl_ALL(vbool8_t mask, int8_t *base, vint8m1_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv16i8.p0.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m2_m_ntl_ALL(vbool4_t mask, int8_t *base, vint8m2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv32i8.p0.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m4_m_ntl_ALL(vbool2_t mask, int8_t *base, vint8m4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_i8m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv64i8.p0.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_i8m8_m_ntl_ALL(vbool1_t mask, int8_t *base, vint8m8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_i8m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8mf8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv1i8.p0.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8mf8_m_ntl_ALL(vbool64_t mask, uint8_t *base, vuint8mf8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8mf8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8mf4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv2i8.p0.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8mf4_m_ntl_ALL(vbool32_t mask, uint8_t *base, vuint8mf4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8mf4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8mf2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv4i8.p0.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8mf2_m_ntl_ALL(vbool16_t mask, uint8_t *base, vuint8mf2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8mf2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m1_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv8i8.p0.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m1_m_ntl_ALL(vbool8_t mask, uint8_t *base, vuint8m1_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m1_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m2_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv16i8.p0.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m2_m_ntl_ALL(vbool4_t mask, uint8_t *base, vuint8m2_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m2_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m4_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv32i8.p0.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m4_m_ntl_ALL(vbool2_t mask, uint8_t *base, vuint8m4_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m4_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

// CHECK-LABEL: @test_vse8_v_u8m8_m_ntl_ALL(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.riscv.vse.mask.nxv64i8.p0.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal [[META6]]
// CHECK-NEXT:    ret void
//
void test_vse8_v_u8m8_m_ntl_ALL(vbool1_t mask, uint8_t *base, vuint8m8_t value, size_t vl, int domain) {
  return __riscv_vse8_v_u8m8_m_ntl(mask, base, value, vl, __RISCV_NTLH_ALL);
}

