// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -target-feature +zfh \
// RUN:   -target-feature +zvfh -disable-O0-optnone  \
// RUN:   -emit-llvm %s -o - | opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s

#include <riscv_vector.h>

#include <riscv_ntlh.h>

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m1_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 1 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv1f64.p0.i64(<vscale x 1 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6:![0-9]+]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m1_ntl_P1(double *base, ptrdiff_t bstride, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m1_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 2 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv2f64.p0.i64(<vscale x 2 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m2_ntl_P1(double *base, ptrdiff_t bstride, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m2_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 4 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv4f64.p0.i64(<vscale x 4 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m4_ntl_P1(double *base, ptrdiff_t bstride, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m4_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m8_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 8 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv8f64.p0.i64(<vscale x 8 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m8_ntl_P1(double *base, ptrdiff_t bstride, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m8_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m1_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m1_ntl_P1(int64_t *base, ptrdiff_t bstride, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m1_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m2_ntl_P1(int64_t *base, ptrdiff_t bstride, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m2_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m4_ntl_P1(int64_t *base, ptrdiff_t bstride, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m4_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m8_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m8_ntl_P1(int64_t *base, ptrdiff_t bstride, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m8_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m1_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m1_ntl_P1(uint64_t *base, ptrdiff_t bstride, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m1_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m2_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m2_ntl_P1(uint64_t *base, ptrdiff_t bstride, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m2_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m4_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m4_ntl_P1(uint64_t *base, ptrdiff_t bstride, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m4_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m8_ntl_P1
// CHECK-RV64-SAME: (ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m8_ntl_P1(uint64_t *base, ptrdiff_t bstride, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m8_ntl(base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m1_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 1 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv1f64.p0.i64(<vscale x 1 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m1_m_ntl_P1(vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m1_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 2 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv2f64.p0.i64(<vscale x 2 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m2_m_ntl_P1(vbool32_t mask, double *base, ptrdiff_t bstride, vfloat64m2_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m2_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 4 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv4f64.p0.i64(<vscale x 4 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m4_m_ntl_P1(vbool16_t mask, double *base, ptrdiff_t bstride, vfloat64m4_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m4_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_f64m8_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 8 x double> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv8f64.p0.i64(<vscale x 8 x double> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_f64m8_m_ntl_P1(vbool8_t mask, double *base, ptrdiff_t bstride, vfloat64m8_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_f64m8_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m1_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m1_m_ntl_P1(vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m1_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m2_m_ntl_P1(vbool32_t mask, int64_t *base, ptrdiff_t bstride, vint64m2_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m2_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m4_m_ntl_P1(vbool16_t mask, int64_t *base, ptrdiff_t bstride, vint64m4_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m4_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_i64m8_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_i64m8_m_ntl_P1(vbool8_t mask, int64_t *base, ptrdiff_t bstride, vint64m8_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_i64m8_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m1_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 1 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv1i64.p0.i64(<vscale x 1 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 1 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m1_m_ntl_P1(vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m1_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m2_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 2 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv2i64.p0.i64(<vscale x 2 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 2 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m2_m_ntl_P1(vbool32_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m2_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m2_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m4_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 4 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv4i64.p0.i64(<vscale x 4 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 4 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m4_m_ntl_P1(vbool16_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m4_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m4_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

// CHECK-RV64-LABEL: define dso_local void @test_vsse64_v_u64m8_m_ntl_P1
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], ptr noundef [[BASE:%.*]], i64 noundef [[BSTRIDE:%.*]], <vscale x 8 x i64> [[VALUE:%.*]], i64 noundef [[VL:%.*]], i32 noundef signext [[DOMAIN:%.*]]) #[[ATTR0]] {
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsse.mask.nxv8i64.p0.i64(<vscale x 8 x i64> [[VALUE]], ptr [[BASE]], i64 [[BSTRIDE]], <vscale x 8 x i1> [[MASK]], i64 [[VL]]), !nontemporal [[META6]]
// CHECK-RV64-NEXT:    ret void
//
void test_vsse64_v_u64m8_m_ntl_P1(vbool8_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m8_t value, size_t vl, int domain) {
  return __riscv_vsse64_v_u64m8_m_ntl(mask, base, bstride, value, vl, __RISCV_NTLH_INNERMOST_PRIVATE);
}

