; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes="loop(loop-idiom),instcombine" -S %s | FileCheck %s

define zeroext i16 @crcu8(i8 zeroext %data, i16 zeroext %crc) {
; CHECK-LABEL: define zeroext i16 @crcu8(
; CHECK-SAME: i8 zeroext [[DATA:%.*]], i16 zeroext [[CRC:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = zext i8 [[DATA]] to i16
; CHECK-NEXT:    [[TMP1:%.*]] = xor i16 [[CRC]], [[TMP0]]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_036:%.*]] = phi i8 [ 0, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[CRC_ADDR_035:%.*]] = phi i16 [ [[TMP1]], [[ENTRY]] ], [ [[CRC_ADDR_2:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[XOR1:%.*]] = and i16 [[CRC_ADDR_035]], 1
; CHECK-NEXT:    [[CMP10_NOT:%.*]] = icmp eq i16 [[XOR1]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = lshr i16 [[CRC_ADDR_035]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = xor i16 [[TMP2]], -24575
; CHECK-NEXT:    [[CRC_ADDR_2]] = select i1 [[CMP10_NOT]], i16 [[TMP2]], i16 [[TMP3]]
; CHECK-NEXT:    [[INC]] = add nuw nsw i8 [[I_036]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i8 [[I_036]], 7
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END:%.*]]
; CHECK:       for.end:
; CHECK-NEXT:    ret i16 [[CRC_ADDR_2]]
;
entry:
  br label %for.body

for.body:                                         ; preds = %for.body, %entry
  %i.036 = phi i8 [ 0, %entry ], [ %inc, %for.body ]
  %crc.addr.035 = phi i16 [ %crc, %entry ], [ %crc.addr.2, %for.body ]
  %data.addr.034 = phi i8 [ %data, %entry ], [ %1, %for.body ]
  %0 = trunc i16 %crc.addr.035 to i8
  %and33 = xor i8 %data.addr.034, %0
  %xor = and i8 %and33, 1
  %1 = lshr i8 %data.addr.034, 1
  %cmp10.not = icmp eq i8 %xor, 0
  %2 = lshr i16 %crc.addr.035, 1
  %3 = xor i16 %2, -24575
  %crc.addr.2 = select i1 %cmp10.not, i16 %2, i16 %3
  %inc = add nuw nsw i8 %i.036, 1
  %cmp = icmp ult i8 %i.036, 7
  br i1 %cmp, label %for.body, label %for.end

for.end:                                          ; preds = %for.body
  %crc.addr.2.lcssa = phi i16 [ %crc.addr.2, %for.body ]
  ret i16 %crc.addr.2.lcssa
}
