; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt %s -S -loop-fusion -loop-concat-canonicalize -passes='simplifycfg,loop-fusion,loop-unroll,function(dce)' -mtriple=riscv64 -mcpu=sifive-p470 | FileCheck %s

define dso_local signext range(i32 0, 98304) i32 @x264_pixel_satd_8x8(ptr nocapture noundef readonly %pix1, i32 noundef signext %i_pix1, ptr nocapture noundef readonly %pix2, i32 noundef signext %i_pix2) {
; CHECK-LABEL: define dso_local signext range(i32 0, 98304) i32 @x264_pixel_satd_8x8(
; CHECK-SAME: ptr noundef readonly captures(none) [[PIX1:%.*]], i32 noundef signext [[I_PIX1:%.*]], ptr noundef readonly captures(none) [[PIX2:%.*]], i32 noundef signext [[I_PIX2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMPA:%.*]] = alloca [8 x [4 x i32]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 64
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 128, ptr nonnull [[TMPA]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    [[IDX_EXT201:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT203:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND66_PREHEADER:.*]]:
; CHECK-NEXT:    [[ARRAYIDX75:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 16
; CHECK-NEXT:    [[ARRAYIDX88:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 32
; CHECK-NEXT:    [[ARRAYIDX91:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 48
; CHECK-NEXT:    [[ARRAYIDX216:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 16
; CHECK-NEXT:    [[ARRAYIDX229:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 32
; CHECK-NEXT:    [[ARRAYIDX232:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 48
; CHECK-NEXT:    br label %[[FOR_BODY70:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT_1:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX1_ADDR_0144:%.*]] = phi ptr [ [[PIX1]], %[[ENTRY]] ], [ [[ADD_PTR_1:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX2_ADDR_0143:%.*]] = phi ptr [ [[PIX2]], %[[ENTRY]] ], [ [[ADD_PTR64_1:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[PIX1_ADDR_0144]], align 1, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[PIX2_ADDR_0143]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[CONV]], [[CONV2]]
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX3]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[ARRAYIDX5]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6:%.*]] = zext i8 [[TMP4]] to i32
; CHECK-NEXT:    [[SUB7:%.*]] = sub nsw i32 [[CONV4]], [[CONV6]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nsw i32 [[SUB7]], 16
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[SHL]], [[SUB]]
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 1
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[ARRAYIDX8]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9:%.*]] = zext i8 [[TMP5]] to i32
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 1
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[ARRAYIDX10]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11:%.*]] = zext i8 [[TMP6]] to i32
; CHECK-NEXT:    [[SUB12:%.*]] = sub nsw i32 [[CONV9]], [[CONV11]]
; CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 5
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[ARRAYIDX13]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14:%.*]] = zext i8 [[TMP7]] to i32
; CHECK-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 5
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[ARRAYIDX15]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16:%.*]] = zext i8 [[TMP8]] to i32
; CHECK-NEXT:    [[SUB17:%.*]] = sub nsw i32 [[CONV14]], [[CONV16]]
; CHECK-NEXT:    [[SHL18:%.*]] = shl nsw i32 [[SUB17]], 16
; CHECK-NEXT:    [[ADD19:%.*]] = add nsw i32 [[SHL18]], [[SUB12]]
; CHECK-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 2
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[ARRAYIDX20]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21:%.*]] = zext i8 [[TMP9]] to i32
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[ARRAYIDX22]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23:%.*]] = zext i8 [[TMP10]] to i32
; CHECK-NEXT:    [[SUB24:%.*]] = sub nsw i32 [[CONV21]], [[CONV23]]
; CHECK-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[ARRAYIDX25]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26:%.*]] = zext i8 [[TMP11]] to i32
; CHECK-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 6
; CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX27]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28:%.*]] = zext i8 [[TMP12]] to i32
; CHECK-NEXT:    [[SUB29:%.*]] = sub nsw i32 [[CONV26]], [[CONV28]]
; CHECK-NEXT:    [[SHL30:%.*]] = shl nsw i32 [[SUB29]], 16
; CHECK-NEXT:    [[ADD31:%.*]] = add nsw i32 [[SHL30]], [[SUB24]]
; CHECK-NEXT:    [[ARRAYIDX32:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 3
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[ARRAYIDX32]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33:%.*]] = zext i8 [[TMP13]] to i32
; CHECK-NEXT:    [[ARRAYIDX34:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 3
; CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[ARRAYIDX34]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35:%.*]] = zext i8 [[TMP14]] to i32
; CHECK-NEXT:    [[SUB36:%.*]] = sub nsw i32 [[CONV33]], [[CONV35]]
; CHECK-NEXT:    [[ARRAYIDX37:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 7
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[ARRAYIDX37]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38:%.*]] = zext i8 [[TMP15]] to i32
; CHECK-NEXT:    [[ARRAYIDX39:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 7
; CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX39]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40:%.*]] = zext i8 [[TMP16]] to i32
; CHECK-NEXT:    [[SUB41:%.*]] = sub nsw i32 [[CONV38]], [[CONV40]]
; CHECK-NEXT:    [[SHL42:%.*]] = shl nsw i32 [[SUB41]], 16
; CHECK-NEXT:    [[ADD43:%.*]] = add nsw i32 [[SHL42]], [[SUB36]]
; CHECK-NEXT:    [[ADD44:%.*]] = add nsw i32 [[ADD19]], [[ADD]]
; CHECK-NEXT:    [[SUB45:%.*]] = sub nsw i32 [[ADD]], [[ADD19]]
; CHECK-NEXT:    [[ADD46:%.*]] = add nsw i32 [[ADD43]], [[ADD31]]
; CHECK-NEXT:    [[SUB47:%.*]] = sub nsw i32 [[ADD31]], [[ADD43]]
; CHECK-NEXT:    [[ADD48:%.*]] = add nsw i32 [[ADD46]], [[ADD44]]
; CHECK-NEXT:    [[ARRAYIDX49:%.*]] = getelementptr inbounds [8 x [4 x i32]], ptr [[TMPA]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[ADD48]], ptr [[ARRAYIDX49]], align 8, !tbaa [[TBAA3:![0-9]+]]
; CHECK-NEXT:    [[SUB51:%.*]] = sub nsw i32 [[ADD44]], [[ADD46]]
; CHECK-NEXT:    [[ARRAYIDX54:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49]], i64 8
; CHECK-NEXT:    store i32 [[SUB51]], ptr [[ARRAYIDX54]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55:%.*]] = add nsw i32 [[SUB47]], [[SUB45]]
; CHECK-NEXT:    [[ARRAYIDX58:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49]], i64 4
; CHECK-NEXT:    store i32 [[ADD55]], ptr [[ARRAYIDX58]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59:%.*]] = sub nsw i32 [[SUB45]], [[SUB47]]
; CHECK-NEXT:    [[ARRAYIDX62:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49]], i64 12
; CHECK-NEXT:    store i32 [[SUB59]], ptr [[ARRAYIDX62]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 [[IDX_EXT201]]
; CHECK-NEXT:    [[ADD_PTR64:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 [[IDX_EXT203]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[ADD_PTR]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV_1:%.*]] = zext i8 [[TMP17]] to i32
; CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[ADD_PTR64]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2_1:%.*]] = zext i8 [[TMP18]] to i32
; CHECK-NEXT:    [[SUB_1:%.*]] = sub nsw i32 [[CONV_1]], [[CONV2_1]]
; CHECK-NEXT:    [[ARRAYIDX3_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 4
; CHECK-NEXT:    [[TMP19:%.*]] = load i8, ptr [[ARRAYIDX3_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4_1:%.*]] = zext i8 [[TMP19]] to i32
; CHECK-NEXT:    [[ARRAYIDX5_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 4
; CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[ARRAYIDX5_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6_1:%.*]] = zext i8 [[TMP20]] to i32
; CHECK-NEXT:    [[SUB7_1:%.*]] = sub nsw i32 [[CONV4_1]], [[CONV6_1]]
; CHECK-NEXT:    [[SHL_1:%.*]] = shl nsw i32 [[SUB7_1]], 16
; CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[SHL_1]], [[SUB_1]]
; CHECK-NEXT:    [[ARRAYIDX8_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 1
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[ARRAYIDX8_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9_1:%.*]] = zext i8 [[TMP21]] to i32
; CHECK-NEXT:    [[ARRAYIDX10_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 1
; CHECK-NEXT:    [[TMP22:%.*]] = load i8, ptr [[ARRAYIDX10_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11_1:%.*]] = zext i8 [[TMP22]] to i32
; CHECK-NEXT:    [[SUB12_1:%.*]] = sub nsw i32 [[CONV9_1]], [[CONV11_1]]
; CHECK-NEXT:    [[ARRAYIDX13_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 5
; CHECK-NEXT:    [[TMP23:%.*]] = load i8, ptr [[ARRAYIDX13_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14_1:%.*]] = zext i8 [[TMP23]] to i32
; CHECK-NEXT:    [[ARRAYIDX15_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 5
; CHECK-NEXT:    [[TMP24:%.*]] = load i8, ptr [[ARRAYIDX15_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16_1:%.*]] = zext i8 [[TMP24]] to i32
; CHECK-NEXT:    [[SUB17_1:%.*]] = sub nsw i32 [[CONV14_1]], [[CONV16_1]]
; CHECK-NEXT:    [[SHL18_1:%.*]] = shl nsw i32 [[SUB17_1]], 16
; CHECK-NEXT:    [[ADD19_1:%.*]] = add nsw i32 [[SHL18_1]], [[SUB12_1]]
; CHECK-NEXT:    [[ARRAYIDX20_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 2
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[ARRAYIDX20_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21_1:%.*]] = zext i8 [[TMP25]] to i32
; CHECK-NEXT:    [[ARRAYIDX22_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 2
; CHECK-NEXT:    [[TMP26:%.*]] = load i8, ptr [[ARRAYIDX22_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23_1:%.*]] = zext i8 [[TMP26]] to i32
; CHECK-NEXT:    [[SUB24_1:%.*]] = sub nsw i32 [[CONV21_1]], [[CONV23_1]]
; CHECK-NEXT:    [[ARRAYIDX25_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 6
; CHECK-NEXT:    [[TMP27:%.*]] = load i8, ptr [[ARRAYIDX25_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26_1:%.*]] = zext i8 [[TMP27]] to i32
; CHECK-NEXT:    [[ARRAYIDX27_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 6
; CHECK-NEXT:    [[TMP28:%.*]] = load i8, ptr [[ARRAYIDX27_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28_1:%.*]] = zext i8 [[TMP28]] to i32
; CHECK-NEXT:    [[SUB29_1:%.*]] = sub nsw i32 [[CONV26_1]], [[CONV28_1]]
; CHECK-NEXT:    [[SHL30_1:%.*]] = shl nsw i32 [[SUB29_1]], 16
; CHECK-NEXT:    [[ADD31_1:%.*]] = add nsw i32 [[SHL30_1]], [[SUB24_1]]
; CHECK-NEXT:    [[ARRAYIDX32_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 3
; CHECK-NEXT:    [[TMP29:%.*]] = load i8, ptr [[ARRAYIDX32_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33_1:%.*]] = zext i8 [[TMP29]] to i32
; CHECK-NEXT:    [[ARRAYIDX34_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 3
; CHECK-NEXT:    [[TMP30:%.*]] = load i8, ptr [[ARRAYIDX34_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35_1:%.*]] = zext i8 [[TMP30]] to i32
; CHECK-NEXT:    [[SUB36_1:%.*]] = sub nsw i32 [[CONV33_1]], [[CONV35_1]]
; CHECK-NEXT:    [[ARRAYIDX37_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 7
; CHECK-NEXT:    [[TMP31:%.*]] = load i8, ptr [[ARRAYIDX37_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38_1:%.*]] = zext i8 [[TMP31]] to i32
; CHECK-NEXT:    [[ARRAYIDX39_1:%.*]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 7
; CHECK-NEXT:    [[TMP32:%.*]] = load i8, ptr [[ARRAYIDX39_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40_1:%.*]] = zext i8 [[TMP32]] to i32
; CHECK-NEXT:    [[SUB41_1:%.*]] = sub nsw i32 [[CONV38_1]], [[CONV40_1]]
; CHECK-NEXT:    [[SHL42_1:%.*]] = shl nsw i32 [[SUB41_1]], 16
; CHECK-NEXT:    [[ADD43_1:%.*]] = add nsw i32 [[SHL42_1]], [[SUB36_1]]
; CHECK-NEXT:    [[ADD44_1:%.*]] = add nsw i32 [[ADD19_1]], [[ADD_1]]
; CHECK-NEXT:    [[SUB45_1:%.*]] = sub nsw i32 [[ADD_1]], [[ADD19_1]]
; CHECK-NEXT:    [[ADD46_1:%.*]] = add nsw i32 [[ADD43_1]], [[ADD31_1]]
; CHECK-NEXT:    [[SUB47_1:%.*]] = sub nsw i32 [[ADD31_1]], [[ADD43_1]]
; CHECK-NEXT:    [[ADD48_1:%.*]] = add nsw i32 [[ADD46_1]], [[ADD44_1]]
; CHECK-NEXT:    [[ARRAYIDX49_1:%.*]] = getelementptr inbounds [8 x [4 x i32]], ptr [[TMPA]], i64 0, i64 [[INDVARS_IV_NEXT]]
; CHECK-NEXT:    store i32 [[ADD48_1]], ptr [[ARRAYIDX49_1]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB51_1:%.*]] = sub nsw i32 [[ADD44_1]], [[ADD46_1]]
; CHECK-NEXT:    [[ARRAYIDX54_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49_1]], i64 8
; CHECK-NEXT:    store i32 [[SUB51_1]], ptr [[ARRAYIDX54_1]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55_1:%.*]] = add nsw i32 [[SUB47_1]], [[SUB45_1]]
; CHECK-NEXT:    [[ARRAYIDX58_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49_1]], i64 4
; CHECK-NEXT:    store i32 [[ADD55_1]], ptr [[ARRAYIDX58_1]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59_1:%.*]] = sub nsw i32 [[SUB45_1]], [[SUB47_1]]
; CHECK-NEXT:    [[ARRAYIDX62_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49_1]], i64 12
; CHECK-NEXT:    store i32 [[SUB59_1]], ptr [[ARRAYIDX62_1]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_1]] = add nuw nsw i64 [[INDVARS_IV]], 2
; CHECK-NEXT:    [[ADD_PTR_1]] = getelementptr inbounds i8, ptr [[ADD_PTR]], i64 [[IDX_EXT201]]
; CHECK-NEXT:    [[ADD_PTR64_1]] = getelementptr inbounds i8, ptr [[ADD_PTR64]], i64 [[IDX_EXT203]]
; CHECK-NEXT:    [[EXITCOND_1:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT_1]], 8
; CHECK-NEXT:    br i1 [[EXITCOND_1]], label %[[FOR_BODY]], label %[[FOR_COND66_PREHEADER]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[FOR_BODY70]]:
; CHECK-NEXT:    [[INDVARS_IV161:%.*]] = phi i64 [ 0, %[[FOR_COND66_PREHEADER]] ], [ [[INDVARS_IV_NEXT162:%.*]], %[[FOR_BODY70]] ]
; CHECK-NEXT:    [[SUM1_0150:%.*]] = phi i32 [ 0, %[[FOR_COND66_PREHEADER]] ], [ [[ADD255:%.*]], %[[FOR_BODY70]] ]
; CHECK-NEXT:    [[ARRAYIDX74:%.*]] = getelementptr inbounds [4 x i32], ptr [[TMPA]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[ARRAYIDX74]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX77:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX75]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[ARRAYIDX77]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD78:%.*]] = add i32 [[TMP34]], [[TMP33]]
; CHECK-NEXT:    [[SUB86:%.*]] = sub i32 [[TMP33]], [[TMP34]]
; CHECK-NEXT:    [[ARRAYIDX90:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX88]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr [[ARRAYIDX90]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX93:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX91]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP36:%.*]] = load i32, ptr [[ARRAYIDX93]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD94:%.*]] = add i32 [[TMP36]], [[TMP35]]
; CHECK-NEXT:    [[SUB102:%.*]] = sub i32 [[TMP35]], [[TMP36]]
; CHECK-NEXT:    [[ADD103:%.*]] = add nsw i32 [[ADD94]], [[ADD78]]
; CHECK-NEXT:    [[SUB104:%.*]] = sub nsw i32 [[ADD78]], [[ADD94]]
; CHECK-NEXT:    [[ADD105:%.*]] = add nsw i32 [[SUB102]], [[SUB86]]
; CHECK-NEXT:    [[SUB106:%.*]] = sub nsw i32 [[SUB86]], [[SUB102]]
; CHECK-NEXT:    [[SHR_I:%.*]] = lshr i32 [[ADD103]], 15
; CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SHR_I]], 65537
; CHECK-NEXT:    [[MUL_I:%.*]] = mul nuw i32 [[AND_I]], 65535
; CHECK-NEXT:    [[ADD_I:%.*]] = add i32 [[MUL_I]], [[ADD103]]
; CHECK-NEXT:    [[XOR_I:%.*]] = xor i32 [[ADD_I]], [[MUL_I]]
; CHECK-NEXT:    [[SHR_I107:%.*]] = lshr i32 [[ADD105]], 15
; CHECK-NEXT:    [[AND_I108:%.*]] = and i32 [[SHR_I107]], 65537
; CHECK-NEXT:    [[MUL_I109:%.*]] = mul nuw i32 [[AND_I108]], 65535
; CHECK-NEXT:    [[ADD_I110:%.*]] = add i32 [[MUL_I109]], [[ADD105]]
; CHECK-NEXT:    [[XOR_I111:%.*]] = xor i32 [[ADD_I110]], [[MUL_I109]]
; CHECK-NEXT:    [[SHR_I112:%.*]] = lshr i32 [[SUB104]], 15
; CHECK-NEXT:    [[AND_I113:%.*]] = and i32 [[SHR_I112]], 65537
; CHECK-NEXT:    [[MUL_I114:%.*]] = mul nuw i32 [[AND_I113]], 65535
; CHECK-NEXT:    [[ADD_I115:%.*]] = add i32 [[MUL_I114]], [[SUB104]]
; CHECK-NEXT:    [[XOR_I116:%.*]] = xor i32 [[ADD_I115]], [[MUL_I114]]
; CHECK-NEXT:    [[SHR_I117:%.*]] = lshr i32 [[SUB106]], 15
; CHECK-NEXT:    [[AND_I118:%.*]] = and i32 [[SHR_I117]], 65537
; CHECK-NEXT:    [[MUL_I119:%.*]] = mul nuw i32 [[AND_I118]], 65535
; CHECK-NEXT:    [[ADD_I120:%.*]] = add i32 [[MUL_I119]], [[SUB106]]
; CHECK-NEXT:    [[XOR_I121:%.*]] = xor i32 [[ADD_I120]], [[MUL_I119]]
; CHECK-NEXT:    [[ADD108:%.*]] = add i32 [[XOR_I111]], [[SUM1_0150]]
; CHECK-NEXT:    [[ADD110:%.*]] = add i32 [[ADD108]], [[XOR_I]]
; CHECK-NEXT:    [[ADD112:%.*]] = add i32 [[ADD110]], [[XOR_I116]]
; CHECK-NEXT:    [[ADD113:%.*]] = add i32 [[ADD112]], [[XOR_I121]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT162]] = add nuw nsw i64 [[INDVARS_IV161]], 1
; CHECK-NEXT:    [[ARRAYIDX215:%.*]] = getelementptr inbounds [4 x i32], ptr [[TMP0]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP37:%.*]] = load i32, ptr [[ARRAYIDX215]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX218:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX216]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP38:%.*]] = load i32, ptr [[ARRAYIDX218]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD219:%.*]] = add i32 [[TMP38]], [[TMP37]]
; CHECK-NEXT:    [[SUB227:%.*]] = sub i32 [[TMP37]], [[TMP38]]
; CHECK-NEXT:    [[ARRAYIDX231:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX229]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP39:%.*]] = load i32, ptr [[ARRAYIDX231]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX234:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX232]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP40:%.*]] = load i32, ptr [[ARRAYIDX234]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD235:%.*]] = add i32 [[TMP40]], [[TMP39]]
; CHECK-NEXT:    [[SUB243:%.*]] = sub i32 [[TMP39]], [[TMP40]]
; CHECK-NEXT:    [[ADD244:%.*]] = add nsw i32 [[ADD235]], [[ADD219]]
; CHECK-NEXT:    [[SUB245:%.*]] = sub nsw i32 [[ADD219]], [[ADD235]]
; CHECK-NEXT:    [[ADD246:%.*]] = add nsw i32 [[SUB243]], [[SUB227]]
; CHECK-NEXT:    [[SUB247:%.*]] = sub nsw i32 [[SUB227]], [[SUB243]]
; CHECK-NEXT:    [[SHR_I122:%.*]] = lshr i32 [[ADD244]], 15
; CHECK-NEXT:    [[AND_I123:%.*]] = and i32 [[SHR_I122]], 65537
; CHECK-NEXT:    [[MUL_I124:%.*]] = mul nuw i32 [[AND_I123]], 65535
; CHECK-NEXT:    [[ADD_I125:%.*]] = add i32 [[MUL_I124]], [[ADD244]]
; CHECK-NEXT:    [[XOR_I126:%.*]] = xor i32 [[ADD_I125]], [[MUL_I124]]
; CHECK-NEXT:    [[SHR_I127:%.*]] = lshr i32 [[ADD246]], 15
; CHECK-NEXT:    [[AND_I128:%.*]] = and i32 [[SHR_I127]], 65537
; CHECK-NEXT:    [[MUL_I129:%.*]] = mul nuw i32 [[AND_I128]], 65535
; CHECK-NEXT:    [[ADD_I130:%.*]] = add i32 [[MUL_I129]], [[ADD246]]
; CHECK-NEXT:    [[XOR_I131:%.*]] = xor i32 [[ADD_I130]], [[MUL_I129]]
; CHECK-NEXT:    [[SHR_I132:%.*]] = lshr i32 [[SUB245]], 15
; CHECK-NEXT:    [[AND_I133:%.*]] = and i32 [[SHR_I132]], 65537
; CHECK-NEXT:    [[MUL_I134:%.*]] = mul nuw i32 [[AND_I133]], 65535
; CHECK-NEXT:    [[ADD_I135:%.*]] = add i32 [[MUL_I134]], [[SUB245]]
; CHECK-NEXT:    [[XOR_I136:%.*]] = xor i32 [[ADD_I135]], [[MUL_I134]]
; CHECK-NEXT:    [[SHR_I137:%.*]] = lshr i32 [[SUB247]], 15
; CHECK-NEXT:    [[AND_I138:%.*]] = and i32 [[SHR_I137]], 65537
; CHECK-NEXT:    [[MUL_I139:%.*]] = mul nuw i32 [[AND_I138]], 65535
; CHECK-NEXT:    [[ADD_I140:%.*]] = add i32 [[MUL_I139]], [[SUB247]]
; CHECK-NEXT:    [[XOR_I141:%.*]] = xor i32 [[ADD_I140]], [[MUL_I139]]
; CHECK-NEXT:    [[ADD250:%.*]] = add i32 [[XOR_I131]], [[ADD113]]
; CHECK-NEXT:    [[ADD252:%.*]] = add i32 [[ADD250]], [[XOR_I126]]
; CHECK-NEXT:    [[ADD254:%.*]] = add i32 [[ADD252]], [[XOR_I136]]
; CHECK-NEXT:    [[ADD255]] = add i32 [[ADD254]], [[XOR_I141]]
; CHECK-NEXT:    [[EXITCOND164:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT162]], 4
; CHECK-NEXT:    br i1 [[EXITCOND164]], label %[[FOR_BODY70]], label %[[FOR_COND_CLEANUP210:.*]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[FOR_COND_CLEANUP210]]:
; CHECK-NEXT:    [[ADD255_LCSSA:%.*]] = phi i32 [ [[ADD255]], %[[FOR_BODY70]] ]
; CHECK-NEXT:    [[CONV260:%.*]] = and i32 [[ADD255_LCSSA]], 65535
; CHECK-NEXT:    [[CMP261:%.*]] = icmp ugt i32 [[ADD255_LCSSA]], 16
; CHECK-NEXT:    [[CONV262:%.*]] = zext i1 [[CMP261]] to i32
; CHECK-NEXT:    [[ADD263:%.*]] = add nuw nsw i32 [[CONV260]], [[CONV262]]
; CHECK-NEXT:    [[SHR264:%.*]] = lshr i32 [[ADD263]], 1
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 128, ptr nonnull [[TMPA]]) #[[ATTR2]]
; CHECK-NEXT:    ret i32 [[SHR264]]
;
entry:
  %tmpa = alloca [8 x [4 x i32]], align 8
  %0 = getelementptr inbounds i8, ptr %tmpa, i64 64
  call void @llvm.lifetime.start.p0(i64 128, ptr nonnull %tmpa) #1
  %idx.ext = sext i32 %i_pix1 to i64
  %idx.ext63 = sext i32 %i_pix2 to i64
  %idx.ext201 = sext i32 %i_pix1 to i64
  %idx.ext203 = sext i32 %i_pix2 to i64
  br label %for.body

for.cond66.preheader:                             ; preds = %for.body
  %add.ptr.lcssa = phi ptr [ %add.ptr, %for.body ]
  %add.ptr64.lcssa = phi ptr [ %add.ptr64, %for.body ]
  %arrayidx75 = getelementptr inbounds i8, ptr %tmpa, i64 16
  %arrayidx88 = getelementptr inbounds i8, ptr %tmpa, i64 32
  %arrayidx91 = getelementptr inbounds i8, ptr %tmpa, i64 48
  br label %for.body70

for.body:                                         ; preds = %for.body, %entry
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %pix1.addr.0144 = phi ptr [ %pix1, %entry ], [ %add.ptr, %for.body ]
  %pix2.addr.0143 = phi ptr [ %pix2, %entry ], [ %add.ptr64, %for.body ]
  %1 = load i8, ptr %pix1.addr.0144, align 1, !tbaa !0
  %conv = zext i8 %1 to i32
  %2 = load i8, ptr %pix2.addr.0143, align 1, !tbaa !0
  %conv2 = zext i8 %2 to i32
  %sub = sub nsw i32 %conv, %conv2
  %arrayidx3 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 4
  %3 = load i8, ptr %arrayidx3, align 1, !tbaa !0
  %conv4 = zext i8 %3 to i32
  %arrayidx5 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 4
  %4 = load i8, ptr %arrayidx5, align 1, !tbaa !0
  %conv6 = zext i8 %4 to i32
  %sub7 = sub nsw i32 %conv4, %conv6
  %shl = shl nsw i32 %sub7, 16
  %add = add nsw i32 %shl, %sub
  %arrayidx8 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 1
  %5 = load i8, ptr %arrayidx8, align 1, !tbaa !0
  %conv9 = zext i8 %5 to i32
  %arrayidx10 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 1
  %6 = load i8, ptr %arrayidx10, align 1, !tbaa !0
  %conv11 = zext i8 %6 to i32
  %sub12 = sub nsw i32 %conv9, %conv11
  %arrayidx13 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 5
  %7 = load i8, ptr %arrayidx13, align 1, !tbaa !0
  %conv14 = zext i8 %7 to i32
  %arrayidx15 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 5
  %8 = load i8, ptr %arrayidx15, align 1, !tbaa !0
  %conv16 = zext i8 %8 to i32
  %sub17 = sub nsw i32 %conv14, %conv16
  %shl18 = shl nsw i32 %sub17, 16
  %add19 = add nsw i32 %shl18, %sub12
  %arrayidx20 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 2
  %9 = load i8, ptr %arrayidx20, align 1, !tbaa !0
  %conv21 = zext i8 %9 to i32
  %arrayidx22 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 2
  %10 = load i8, ptr %arrayidx22, align 1, !tbaa !0
  %conv23 = zext i8 %10 to i32
  %sub24 = sub nsw i32 %conv21, %conv23
  %arrayidx25 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 6
  %11 = load i8, ptr %arrayidx25, align 1, !tbaa !0
  %conv26 = zext i8 %11 to i32
  %arrayidx27 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 6
  %12 = load i8, ptr %arrayidx27, align 1, !tbaa !0
  %conv28 = zext i8 %12 to i32
  %sub29 = sub nsw i32 %conv26, %conv28
  %shl30 = shl nsw i32 %sub29, 16
  %add31 = add nsw i32 %shl30, %sub24
  %arrayidx32 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 3
  %13 = load i8, ptr %arrayidx32, align 1, !tbaa !0
  %conv33 = zext i8 %13 to i32
  %arrayidx34 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 3
  %14 = load i8, ptr %arrayidx34, align 1, !tbaa !0
  %conv35 = zext i8 %14 to i32
  %sub36 = sub nsw i32 %conv33, %conv35
  %arrayidx37 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 7
  %15 = load i8, ptr %arrayidx37, align 1, !tbaa !0
  %conv38 = zext i8 %15 to i32
  %arrayidx39 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 7
  %16 = load i8, ptr %arrayidx39, align 1, !tbaa !0
  %conv40 = zext i8 %16 to i32
  %sub41 = sub nsw i32 %conv38, %conv40
  %shl42 = shl nsw i32 %sub41, 16
  %add43 = add nsw i32 %shl42, %sub36
  %add44 = add nsw i32 %add19, %add
  %sub45 = sub nsw i32 %add, %add19
  %add46 = add nsw i32 %add43, %add31
  %sub47 = sub nsw i32 %add31, %add43
  %add48 = add nsw i32 %add46, %add44
  %arrayidx49 = getelementptr inbounds [8 x [4 x i32]], ptr %tmpa, i64 0, i64 %indvars.iv
  store i32 %add48, ptr %arrayidx49, align 8, !tbaa !3
  %sub51 = sub nsw i32 %add44, %add46
  %arrayidx54 = getelementptr inbounds i8, ptr %arrayidx49, i64 8
  store i32 %sub51, ptr %arrayidx54, align 8, !tbaa !3
  %add55 = add nsw i32 %sub47, %sub45
  %arrayidx58 = getelementptr inbounds i8, ptr %arrayidx49, i64 4
  store i32 %add55, ptr %arrayidx58, align 4, !tbaa !3
  %sub59 = sub nsw i32 %sub45, %sub47
  %arrayidx62 = getelementptr inbounds i8, ptr %arrayidx49, i64 12
  store i32 %sub59, ptr %arrayidx62, align 4, !tbaa !3
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %add.ptr = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 %idx.ext
  %add.ptr64 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 %idx.ext63
  %exitcond = icmp ne i64 %indvars.iv.next, 8
  br i1 %exitcond, label %for.body, label %for.cond66.preheader, !llvm.loop !5

for.cond122.preheader:                            ; preds = %for.body70
  br label %for.cond207.preheader

for.body70:                                       ; preds = %for.body70, %for.cond66.preheader
  %indvars.iv153 = phi i64 [ 0, %for.cond66.preheader ], [ %indvars.iv.next154, %for.body70 ]
  %sum0.0146 = phi i32 [ 0, %for.cond66.preheader ], [ %add113, %for.body70 ]
  %arrayidx74 = getelementptr inbounds [4 x i32], ptr %tmpa, i64 0, i64 %indvars.iv153
  %17 = load i32, ptr %arrayidx74, align 4, !tbaa !3
  %arrayidx77 = getelementptr inbounds [4 x i32], ptr %arrayidx75, i64 0, i64 %indvars.iv153
  %18 = load i32, ptr %arrayidx77, align 4, !tbaa !3
  %add78 = add i32 %18, %17
  %sub86 = sub i32 %17, %18
  %arrayidx90 = getelementptr inbounds [4 x i32], ptr %arrayidx88, i64 0, i64 %indvars.iv153
  %19 = load i32, ptr %arrayidx90, align 4, !tbaa !3
  %arrayidx93 = getelementptr inbounds [4 x i32], ptr %arrayidx91, i64 0, i64 %indvars.iv153
  %20 = load i32, ptr %arrayidx93, align 4, !tbaa !3
  %add94 = add i32 %20, %19
  %sub102 = sub i32 %19, %20
  %add103 = add nsw i32 %add94, %add78
  %sub104 = sub nsw i32 %add78, %add94
  %add105 = add nsw i32 %sub102, %sub86
  %sub106 = sub nsw i32 %sub86, %sub102
  %shr.i = lshr i32 %add103, 15
  %and.i = and i32 %shr.i, 65537
  %mul.i = mul nuw i32 %and.i, 65535
  %add.i = add i32 %mul.i, %add103
  %xor.i = xor i32 %add.i, %mul.i
  %shr.i107 = lshr i32 %add105, 15
  %and.i108 = and i32 %shr.i107, 65537
  %mul.i109 = mul nuw i32 %and.i108, 65535
  %add.i110 = add i32 %mul.i109, %add105
  %xor.i111 = xor i32 %add.i110, %mul.i109
  %shr.i112 = lshr i32 %sub104, 15
  %and.i113 = and i32 %shr.i112, 65537
  %mul.i114 = mul nuw i32 %and.i113, 65535
  %add.i115 = add i32 %mul.i114, %sub104
  %xor.i116 = xor i32 %add.i115, %mul.i114
  %shr.i117 = lshr i32 %sub106, 15
  %and.i118 = and i32 %shr.i117, 65537
  %mul.i119 = mul nuw i32 %and.i118, 65535
  %add.i120 = add i32 %mul.i119, %sub106
  %xor.i121 = xor i32 %add.i120, %mul.i119
  %add108 = add i32 %xor.i111, %sum0.0146
  %add110 = add i32 %add108, %xor.i
  %add112 = add i32 %add110, %xor.i116
  %add113 = add i32 %add112, %xor.i121
  %indvars.iv.next154 = add nuw nsw i64 %indvars.iv153, 1
  %exitcond156 = icmp ne i64 %indvars.iv.next154, 4
  br i1 %exitcond156, label %for.body70, label %for.cond122.preheader, !llvm.loop !7

for.cond207.preheader:                            ; preds = %for.cond122.preheader
  %add113.lcssa = phi i32 [ %add113, %for.cond122.preheader ]
  %arrayidx216 = getelementptr inbounds i8, ptr %0, i64 16
  %arrayidx229 = getelementptr inbounds i8, ptr %0, i64 32
  %arrayidx232 = getelementptr inbounds i8, ptr %0, i64 48
  br label %for.body211

for.cond.cleanup210:                              ; preds = %for.body211
  %add255.lcssa = phi i32 [ %add255, %for.body211 ]
  %conv118 = and i32 %add113.lcssa, 65535
  %shr = lshr i32 %add113.lcssa, 16
  %add119 = add nuw nsw i32 %conv118, %shr
  %shr120 = lshr i32 %add119, 1
  %conv260 = and i32 %add255.lcssa, 65535
  %cmp261 = icmp ugt i32 %add255.lcssa, 16
  %conv262 = zext i1 %cmp261 to i32
  %add263 = add nuw nsw i32 %conv260, %conv262
  %shr264 = lshr i32 %add263, 1
  %add265 = add nuw nsw i32 %shr264, %shr120
  call void @llvm.lifetime.end.p0(i64 128, ptr nonnull %tmpa) #1
  ret i32 %add265

for.body211:                                      ; preds = %for.body211, %for.cond207.preheader
  %indvars.iv161 = phi i64 [ 0, %for.cond207.preheader ], [ %indvars.iv.next162, %for.body211 ]
  %sum1.0150 = phi i32 [ 0, %for.cond207.preheader ], [ %add255, %for.body211 ]
  %arrayidx215 = getelementptr inbounds [4 x i32], ptr %0, i64 0, i64 %indvars.iv161
  %21 = load i32, ptr %arrayidx215, align 4, !tbaa !3
  %arrayidx218 = getelementptr inbounds [4 x i32], ptr %arrayidx216, i64 0, i64 %indvars.iv161
  %22 = load i32, ptr %arrayidx218, align 4, !tbaa !3
  %add219 = add i32 %22, %21
  %sub227 = sub i32 %21, %22
  %arrayidx231 = getelementptr inbounds [4 x i32], ptr %arrayidx229, i64 0, i64 %indvars.iv161
  %23 = load i32, ptr %arrayidx231, align 4, !tbaa !3
  %arrayidx234 = getelementptr inbounds [4 x i32], ptr %arrayidx232, i64 0, i64 %indvars.iv161
  %24 = load i32, ptr %arrayidx234, align 4, !tbaa !3
  %add235 = add i32 %24, %23
  %sub243 = sub i32 %23, %24
  %add244 = add nsw i32 %add235, %add219
  %sub245 = sub nsw i32 %add219, %add235
  %add246 = add nsw i32 %sub243, %sub227
  %sub247 = sub nsw i32 %sub227, %sub243
  %shr.i122 = lshr i32 %add244, 15
  %and.i123 = and i32 %shr.i122, 65537
  %mul.i124 = mul nuw i32 %and.i123, 65535
  %add.i125 = add i32 %mul.i124, %add244
  %xor.i126 = xor i32 %add.i125, %mul.i124
  %shr.i127 = lshr i32 %add246, 15
  %and.i128 = and i32 %shr.i127, 65537
  %mul.i129 = mul nuw i32 %and.i128, 65535
  %add.i130 = add i32 %mul.i129, %add246
  %xor.i131 = xor i32 %add.i130, %mul.i129
  %shr.i132 = lshr i32 %sub245, 15
  %and.i133 = and i32 %shr.i132, 65537
  %mul.i134 = mul nuw i32 %and.i133, 65535
  %add.i135 = add i32 %mul.i134, %sub245
  %xor.i136 = xor i32 %add.i135, %mul.i134
  %shr.i137 = lshr i32 %sub247, 15
  %and.i138 = and i32 %shr.i137, 65537
  %mul.i139 = mul nuw i32 %and.i138, 65535
  %add.i140 = add i32 %mul.i139, %sub247
  %xor.i141 = xor i32 %add.i140, %mul.i139
  %add250 = add i32 %xor.i131, %sum1.0150
  %add252 = add i32 %add250, %xor.i126
  %add254 = add i32 %add252, %xor.i136
  %add255 = add i32 %add254, %xor.i141
  %indvars.iv.next162 = add nuw nsw i64 %indvars.iv161, 1
  %exitcond164 = icmp ne i64 %indvars.iv.next162, 4
  br i1 %exitcond164, label %for.body211, label %for.cond.cleanup210, !llvm.loop !8
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #0

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #1 = { nounwind }

!0 = !{!1, !1, i64 0}
!1 = !{!"omnipotent char", !2, i64 0}
!2 = !{!"Simple C/C++ TBAA"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !1, i64 0}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.mustprogress"}
!7 = distinct !{!7, !6}
!8 = distinct !{!8, !6}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"omnipotent char", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
; CHECK: [[META4]] = !{!"int", [[META1]], i64 0}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META6]]}
;.
