; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt %s -S -loop-fusion -loop-concat-canonicalize -passes='simplifycfg,loop-fusion,loop-unroll,function(dce)' -mtriple=riscv64 -mcpu=sifive-p470 | FileCheck %s

; Test non adjacent LoopFusion.  see loop at : for.body70.i228 as it will be
; Fused with for.body70.i

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
define internal signext range(i32 0, 262141) i32 @x264_pixel_satd_16x8(ptr nocapture noundef readonly %pix1, i32 noundef signext %i_pix1, ptr nocapture noundef readonly %pix2, i32 noundef signext %i_pix2) #0 {
; CHECK-LABEL: define internal signext range(i32 0, 262141) i32 @x264_pixel_satd_16x8(
; CHECK-SAME: ptr noundef readonly captures(none) [[PIX1:%.*]], i32 noundef signext [[I_PIX1:%.*]], ptr noundef readonly captures(none) [[PIX2:%.*]], i32 noundef signext [[I_PIX2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP_I155:%.*]] = alloca [8 x [4 x i32]], align 8
; CHECK-NEXT:    [[TMP_I:%.*]] = alloca [8 x [4 x i32]], align 8
; CHECK-NEXT:    [[I:%.*]] = getelementptr inbounds i8, ptr [[TMP_I155]], i64 64
; CHECK-NEXT:    [[I1:%.*]] = getelementptr inbounds i8, ptr [[TMP_I]], i64 64
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 128, ptr nonnull [[TMP_I]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[IDX_EXT_I:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT63_I:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY_I:.*]]
; CHECK:       [[FOR_COND66_PREHEADER_I:.*]]:
; CHECK-NEXT:    [[ARRAYIDX75_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP_I]], i64 16
; CHECK-NEXT:    [[ARRAYIDX88_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP_I]], i64 32
; CHECK-NEXT:    [[ARRAYIDX91_I:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP_I]], i64 48
; CHECK-NEXT:    [[ARRAYIDX75_I106:%.*]] = getelementptr inbounds nuw i8, ptr [[I1]], i64 16
; CHECK-NEXT:    [[ARRAYIDX88_I107:%.*]] = getelementptr inbounds nuw i8, ptr [[I1]], i64 32
; CHECK-NEXT:    [[ARRAYIDX91_I108:%.*]] = getelementptr inbounds nuw i8, ptr [[I1]], i64 48
; CHECK-NEXT:    br label %[[X264_PIXEL_SATD_8X4_EXIT154:.*]]
; CHECK:       [[FOR_BODY_I]]:
; CHECK-NEXT:    [[INDVARS_IV_I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT_I_1:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[PIX1_ADDR_0186_I:%.*]] = phi ptr [ [[PIX1]], %[[ENTRY]] ], [ [[ADD_PTR_I_1:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[PIX2_ADDR_0185_I:%.*]] = phi ptr [ [[PIX2]], %[[ENTRY]] ], [ [[ADD_PTR64_I_1:%.*]], %[[FOR_BODY_I]] ]
; CHECK-NEXT:    [[I2:%.*]] = load i8, ptr [[PIX1_ADDR_0186_I]], align 1, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[CONV_I:%.*]] = zext i8 [[I2]] to i32
; CHECK-NEXT:    [[I3:%.*]] = load i8, ptr [[PIX2_ADDR_0185_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2_I:%.*]] = zext i8 [[I3]] to i32
; CHECK-NEXT:    [[SUB_I:%.*]] = sub nsw i32 [[CONV_I]], [[CONV2_I]]
; CHECK-NEXT:    [[ARRAYIDX3_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 4
; CHECK-NEXT:    [[I4:%.*]] = load i8, ptr [[ARRAYIDX3_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4_I:%.*]] = zext i8 [[I4]] to i32
; CHECK-NEXT:    [[ARRAYIDX5_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 4
; CHECK-NEXT:    [[I5:%.*]] = load i8, ptr [[ARRAYIDX5_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6_I:%.*]] = zext i8 [[I5]] to i32
; CHECK-NEXT:    [[SUB7_I:%.*]] = sub nsw i32 [[CONV4_I]], [[CONV6_I]]
; CHECK-NEXT:    [[SHL_I:%.*]] = shl nsw i32 [[SUB7_I]], 16
; CHECK-NEXT:    [[ADD_I:%.*]] = add nsw i32 [[SHL_I]], [[SUB_I]]
; CHECK-NEXT:    [[ARRAYIDX8_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 1
; CHECK-NEXT:    [[I6:%.*]] = load i8, ptr [[ARRAYIDX8_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9_I:%.*]] = zext i8 [[I6]] to i32
; CHECK-NEXT:    [[ARRAYIDX10_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 1
; CHECK-NEXT:    [[I7:%.*]] = load i8, ptr [[ARRAYIDX10_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11_I:%.*]] = zext i8 [[I7]] to i32
; CHECK-NEXT:    [[SUB12_I:%.*]] = sub nsw i32 [[CONV9_I]], [[CONV11_I]]
; CHECK-NEXT:    [[ARRAYIDX13_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 5
; CHECK-NEXT:    [[I8:%.*]] = load i8, ptr [[ARRAYIDX13_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14_I:%.*]] = zext i8 [[I8]] to i32
; CHECK-NEXT:    [[ARRAYIDX15_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 5
; CHECK-NEXT:    [[I9:%.*]] = load i8, ptr [[ARRAYIDX15_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16_I:%.*]] = zext i8 [[I9]] to i32
; CHECK-NEXT:    [[SUB17_I:%.*]] = sub nsw i32 [[CONV14_I]], [[CONV16_I]]
; CHECK-NEXT:    [[SHL18_I:%.*]] = shl nsw i32 [[SUB17_I]], 16
; CHECK-NEXT:    [[ADD19_I:%.*]] = add nsw i32 [[SHL18_I]], [[SUB12_I]]
; CHECK-NEXT:    [[ARRAYIDX20_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 2
; CHECK-NEXT:    [[I10:%.*]] = load i8, ptr [[ARRAYIDX20_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21_I:%.*]] = zext i8 [[I10]] to i32
; CHECK-NEXT:    [[ARRAYIDX22_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 2
; CHECK-NEXT:    [[I11:%.*]] = load i8, ptr [[ARRAYIDX22_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23_I:%.*]] = zext i8 [[I11]] to i32
; CHECK-NEXT:    [[SUB24_I:%.*]] = sub nsw i32 [[CONV21_I]], [[CONV23_I]]
; CHECK-NEXT:    [[ARRAYIDX25_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 6
; CHECK-NEXT:    [[I12:%.*]] = load i8, ptr [[ARRAYIDX25_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26_I:%.*]] = zext i8 [[I12]] to i32
; CHECK-NEXT:    [[ARRAYIDX27_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 6
; CHECK-NEXT:    [[I13:%.*]] = load i8, ptr [[ARRAYIDX27_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28_I:%.*]] = zext i8 [[I13]] to i32
; CHECK-NEXT:    [[SUB29_I:%.*]] = sub nsw i32 [[CONV26_I]], [[CONV28_I]]
; CHECK-NEXT:    [[SHL30_I:%.*]] = shl nsw i32 [[SUB29_I]], 16
; CHECK-NEXT:    [[ADD31_I:%.*]] = add nsw i32 [[SHL30_I]], [[SUB24_I]]
; CHECK-NEXT:    [[ARRAYIDX32_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 3
; CHECK-NEXT:    [[I14:%.*]] = load i8, ptr [[ARRAYIDX32_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33_I:%.*]] = zext i8 [[I14]] to i32
; CHECK-NEXT:    [[ARRAYIDX34_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 3
; CHECK-NEXT:    [[I15:%.*]] = load i8, ptr [[ARRAYIDX34_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35_I:%.*]] = zext i8 [[I15]] to i32
; CHECK-NEXT:    [[SUB36_I:%.*]] = sub nsw i32 [[CONV33_I]], [[CONV35_I]]
; CHECK-NEXT:    [[ARRAYIDX37_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I]], i64 7
; CHECK-NEXT:    [[I16:%.*]] = load i8, ptr [[ARRAYIDX37_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38_I:%.*]] = zext i8 [[I16]] to i32
; CHECK-NEXT:    [[ARRAYIDX39_I:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I]], i64 7
; CHECK-NEXT:    [[I17:%.*]] = load i8, ptr [[ARRAYIDX39_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40_I:%.*]] = zext i8 [[I17]] to i32
; CHECK-NEXT:    [[SUB41_I:%.*]] = sub nsw i32 [[CONV38_I]], [[CONV40_I]]
; CHECK-NEXT:    [[SHL42_I:%.*]] = shl nsw i32 [[SUB41_I]], 16
; CHECK-NEXT:    [[ADD43_I:%.*]] = add nsw i32 [[SHL42_I]], [[SUB36_I]]
; CHECK-NEXT:    [[ADD44_I:%.*]] = add nsw i32 [[ADD19_I]], [[ADD_I]]
; CHECK-NEXT:    [[SUB45_I:%.*]] = sub nsw i32 [[ADD_I]], [[ADD19_I]]
; CHECK-NEXT:    [[ADD46_I:%.*]] = add nsw i32 [[ADD43_I]], [[ADD31_I]]
; CHECK-NEXT:    [[SUB47_I:%.*]] = sub nsw i32 [[ADD31_I]], [[ADD43_I]]
; CHECK-NEXT:    [[ADD48_I:%.*]] = add nsw i32 [[ADD46_I]], [[ADD44_I]]
; CHECK-NEXT:    [[ARRAYIDX49_I:%.*]] = getelementptr inbounds nuw [8 x [4 x i32]], ptr [[TMP_I]], i64 0, i64 [[INDVARS_IV_I]]
; CHECK-NEXT:    store i32 [[ADD48_I]], ptr [[ARRAYIDX49_I]], align 8, !tbaa [[TBAA3:![0-9]+]]
; CHECK-NEXT:    [[SUB51_I:%.*]] = sub nsw i32 [[ADD44_I]], [[ADD46_I]]
; CHECK-NEXT:    [[ARRAYIDX54_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I]], i64 8
; CHECK-NEXT:    store i32 [[SUB51_I]], ptr [[ARRAYIDX54_I]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55_I:%.*]] = add nsw i32 [[SUB47_I]], [[SUB45_I]]
; CHECK-NEXT:    [[ARRAYIDX58_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I]], i64 4
; CHECK-NEXT:    store i32 [[ADD55_I]], ptr [[ARRAYIDX58_I]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59_I:%.*]] = sub nsw i32 [[SUB45_I]], [[SUB47_I]]
; CHECK-NEXT:    [[ARRAYIDX62_I:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I]], i64 12
; CHECK-NEXT:    store i32 [[SUB59_I]], ptr [[ARRAYIDX62_I]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I:%.*]] = add nuw nsw i64 [[INDVARS_IV_I]], 1
; CHECK-NEXT:    [[ADD_PTR_I:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0186_I]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR64_I:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0185_I]], i64 [[IDX_EXT63_I]]
; CHECK-NEXT:    [[I2_1:%.*]] = load i8, ptr [[ADD_PTR_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV_I_1:%.*]] = zext i8 [[I2_1]] to i32
; CHECK-NEXT:    [[I3_1:%.*]] = load i8, ptr [[ADD_PTR64_I]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2_I_1:%.*]] = zext i8 [[I3_1]] to i32
; CHECK-NEXT:    [[SUB_I_1:%.*]] = sub nsw i32 [[CONV_I_1]], [[CONV2_I_1]]
; CHECK-NEXT:    [[ARRAYIDX3_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 4
; CHECK-NEXT:    [[I4_1:%.*]] = load i8, ptr [[ARRAYIDX3_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4_I_1:%.*]] = zext i8 [[I4_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX5_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 4
; CHECK-NEXT:    [[I5_1:%.*]] = load i8, ptr [[ARRAYIDX5_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6_I_1:%.*]] = zext i8 [[I5_1]] to i32
; CHECK-NEXT:    [[SUB7_I_1:%.*]] = sub nsw i32 [[CONV4_I_1]], [[CONV6_I_1]]
; CHECK-NEXT:    [[SHL_I_1:%.*]] = shl nsw i32 [[SUB7_I_1]], 16
; CHECK-NEXT:    [[ADD_I_1:%.*]] = add nsw i32 [[SHL_I_1]], [[SUB_I_1]]
; CHECK-NEXT:    [[ARRAYIDX8_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 1
; CHECK-NEXT:    [[I6_1:%.*]] = load i8, ptr [[ARRAYIDX8_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9_I_1:%.*]] = zext i8 [[I6_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX10_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 1
; CHECK-NEXT:    [[I7_1:%.*]] = load i8, ptr [[ARRAYIDX10_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11_I_1:%.*]] = zext i8 [[I7_1]] to i32
; CHECK-NEXT:    [[SUB12_I_1:%.*]] = sub nsw i32 [[CONV9_I_1]], [[CONV11_I_1]]
; CHECK-NEXT:    [[ARRAYIDX13_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 5
; CHECK-NEXT:    [[I8_1:%.*]] = load i8, ptr [[ARRAYIDX13_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14_I_1:%.*]] = zext i8 [[I8_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX15_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 5
; CHECK-NEXT:    [[I9_1:%.*]] = load i8, ptr [[ARRAYIDX15_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16_I_1:%.*]] = zext i8 [[I9_1]] to i32
; CHECK-NEXT:    [[SUB17_I_1:%.*]] = sub nsw i32 [[CONV14_I_1]], [[CONV16_I_1]]
; CHECK-NEXT:    [[SHL18_I_1:%.*]] = shl nsw i32 [[SUB17_I_1]], 16
; CHECK-NEXT:    [[ADD19_I_1:%.*]] = add nsw i32 [[SHL18_I_1]], [[SUB12_I_1]]
; CHECK-NEXT:    [[ARRAYIDX20_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 2
; CHECK-NEXT:    [[I10_1:%.*]] = load i8, ptr [[ARRAYIDX20_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21_I_1:%.*]] = zext i8 [[I10_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX22_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 2
; CHECK-NEXT:    [[I11_1:%.*]] = load i8, ptr [[ARRAYIDX22_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23_I_1:%.*]] = zext i8 [[I11_1]] to i32
; CHECK-NEXT:    [[SUB24_I_1:%.*]] = sub nsw i32 [[CONV21_I_1]], [[CONV23_I_1]]
; CHECK-NEXT:    [[ARRAYIDX25_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 6
; CHECK-NEXT:    [[I12_1:%.*]] = load i8, ptr [[ARRAYIDX25_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26_I_1:%.*]] = zext i8 [[I12_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX27_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 6
; CHECK-NEXT:    [[I13_1:%.*]] = load i8, ptr [[ARRAYIDX27_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28_I_1:%.*]] = zext i8 [[I13_1]] to i32
; CHECK-NEXT:    [[SUB29_I_1:%.*]] = sub nsw i32 [[CONV26_I_1]], [[CONV28_I_1]]
; CHECK-NEXT:    [[SHL30_I_1:%.*]] = shl nsw i32 [[SUB29_I_1]], 16
; CHECK-NEXT:    [[ADD31_I_1:%.*]] = add nsw i32 [[SHL30_I_1]], [[SUB24_I_1]]
; CHECK-NEXT:    [[ARRAYIDX32_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 3
; CHECK-NEXT:    [[I14_1:%.*]] = load i8, ptr [[ARRAYIDX32_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33_I_1:%.*]] = zext i8 [[I14_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX34_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 3
; CHECK-NEXT:    [[I15_1:%.*]] = load i8, ptr [[ARRAYIDX34_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35_I_1:%.*]] = zext i8 [[I15_1]] to i32
; CHECK-NEXT:    [[SUB36_I_1:%.*]] = sub nsw i32 [[CONV33_I_1]], [[CONV35_I_1]]
; CHECK-NEXT:    [[ARRAYIDX37_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I]], i64 7
; CHECK-NEXT:    [[I16_1:%.*]] = load i8, ptr [[ARRAYIDX37_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38_I_1:%.*]] = zext i8 [[I16_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX39_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I]], i64 7
; CHECK-NEXT:    [[I17_1:%.*]] = load i8, ptr [[ARRAYIDX39_I_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40_I_1:%.*]] = zext i8 [[I17_1]] to i32
; CHECK-NEXT:    [[SUB41_I_1:%.*]] = sub nsw i32 [[CONV38_I_1]], [[CONV40_I_1]]
; CHECK-NEXT:    [[SHL42_I_1:%.*]] = shl nsw i32 [[SUB41_I_1]], 16
; CHECK-NEXT:    [[ADD43_I_1:%.*]] = add nsw i32 [[SHL42_I_1]], [[SUB36_I_1]]
; CHECK-NEXT:    [[ADD44_I_1:%.*]] = add nsw i32 [[ADD19_I_1]], [[ADD_I_1]]
; CHECK-NEXT:    [[SUB45_I_1:%.*]] = sub nsw i32 [[ADD_I_1]], [[ADD19_I_1]]
; CHECK-NEXT:    [[ADD46_I_1:%.*]] = add nsw i32 [[ADD43_I_1]], [[ADD31_I_1]]
; CHECK-NEXT:    [[SUB47_I_1:%.*]] = sub nsw i32 [[ADD31_I_1]], [[ADD43_I_1]]
; CHECK-NEXT:    [[ADD48_I_1:%.*]] = add nsw i32 [[ADD46_I_1]], [[ADD44_I_1]]
; CHECK-NEXT:    [[ARRAYIDX49_I_1:%.*]] = getelementptr inbounds nuw [8 x [4 x i32]], ptr [[TMP_I]], i64 0, i64 [[INDVARS_IV_NEXT_I]]
; CHECK-NEXT:    store i32 [[ADD48_I_1]], ptr [[ARRAYIDX49_I_1]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB51_I_1:%.*]] = sub nsw i32 [[ADD44_I_1]], [[ADD46_I_1]]
; CHECK-NEXT:    [[ARRAYIDX54_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I_1]], i64 8
; CHECK-NEXT:    store i32 [[SUB51_I_1]], ptr [[ARRAYIDX54_I_1]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55_I_1:%.*]] = add nsw i32 [[SUB47_I_1]], [[SUB45_I_1]]
; CHECK-NEXT:    [[ARRAYIDX58_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I_1]], i64 4
; CHECK-NEXT:    store i32 [[ADD55_I_1]], ptr [[ARRAYIDX58_I_1]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59_I_1:%.*]] = sub nsw i32 [[SUB45_I_1]], [[SUB47_I_1]]
; CHECK-NEXT:    [[ARRAYIDX62_I_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I_1]], i64 12
; CHECK-NEXT:    store i32 [[SUB59_I_1]], ptr [[ARRAYIDX62_I_1]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I_1]] = add nuw nsw i64 [[INDVARS_IV_I]], 2
; CHECK-NEXT:    [[ADD_PTR_I_1]] = getelementptr inbounds i8, ptr [[ADD_PTR_I]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR64_I_1]] = getelementptr inbounds i8, ptr [[ADD_PTR64_I]], i64 [[IDX_EXT63_I]]
; CHECK-NEXT:    [[EXITCOND_NOT_I_1:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT_I_1]], 8
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I_1]], label %[[FOR_COND66_PREHEADER_I]], label %[[FOR_BODY_I]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[FOR_BODY70_I:.*]]:
; CHECK-NEXT:    [[INDVARS_IV190_I:%.*]] = phi i64 [ 0, %[[FOR_COND66_PREHEADER_I224:.*]] ], [ [[INDVARS_IV_NEXT191_I:%.*]], %[[FOR_BODY70_I]] ]
; CHECK-NEXT:    [[SUM_0187_I:%.*]] = phi i32 [ 0, %[[FOR_COND66_PREHEADER_I224]] ], [ [[ADD113_I385:%.*]], %[[FOR_BODY70_I]] ]
; CHECK-NEXT:    [[ARRAYIDX74_I:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[TMP_I]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I18:%.*]] = load i32, ptr [[ARRAYIDX74_I]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX77_I:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX75_I]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I19:%.*]] = load i32, ptr [[ARRAYIDX77_I]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD78_I:%.*]] = add i32 [[I19]], [[I18]]
; CHECK-NEXT:    [[SUB86_I:%.*]] = sub i32 [[I18]], [[I19]]
; CHECK-NEXT:    [[ARRAYIDX90_I:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX88_I]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I20:%.*]] = load i32, ptr [[ARRAYIDX90_I]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX93_I:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX91_I]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I21:%.*]] = load i32, ptr [[ARRAYIDX93_I]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD94_I:%.*]] = add i32 [[I21]], [[I20]]
; CHECK-NEXT:    [[SUB102_I:%.*]] = sub i32 [[I20]], [[I21]]
; CHECK-NEXT:    [[ADD103_I:%.*]] = add nsw i32 [[ADD94_I]], [[ADD78_I]]
; CHECK-NEXT:    [[SUB104_I:%.*]] = sub nsw i32 [[ADD78_I]], [[ADD94_I]]
; CHECK-NEXT:    [[ADD105_I:%.*]] = add nsw i32 [[SUB102_I]], [[SUB86_I]]
; CHECK-NEXT:    [[SUB106_I:%.*]] = sub nsw i32 [[SUB86_I]], [[SUB102_I]]
; CHECK-NEXT:    [[SHR_I_I:%.*]] = lshr i32 [[ADD103_I]], 15
; CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[SHR_I_I]], 65537
; CHECK-NEXT:    [[MUL_I_I:%.*]] = mul nuw i32 [[AND_I_I]], 65535
; CHECK-NEXT:    [[ADD_I_I:%.*]] = add i32 [[MUL_I_I]], [[ADD103_I]]
; CHECK-NEXT:    [[XOR_I_I:%.*]] = xor i32 [[ADD_I_I]], [[MUL_I_I]]
; CHECK-NEXT:    [[SHR_I169_I:%.*]] = lshr i32 [[ADD105_I]], 15
; CHECK-NEXT:    [[AND_I170_I:%.*]] = and i32 [[SHR_I169_I]], 65537
; CHECK-NEXT:    [[MUL_I171_I:%.*]] = mul nuw i32 [[AND_I170_I]], 65535
; CHECK-NEXT:    [[ADD_I172_I:%.*]] = add i32 [[MUL_I171_I]], [[ADD105_I]]
; CHECK-NEXT:    [[XOR_I173_I:%.*]] = xor i32 [[ADD_I172_I]], [[MUL_I171_I]]
; CHECK-NEXT:    [[SHR_I174_I:%.*]] = lshr i32 [[SUB104_I]], 15
; CHECK-NEXT:    [[AND_I175_I:%.*]] = and i32 [[SHR_I174_I]], 65537
; CHECK-NEXT:    [[MUL_I176_I:%.*]] = mul nuw i32 [[AND_I175_I]], 65535
; CHECK-NEXT:    [[ADD_I177_I:%.*]] = add i32 [[MUL_I176_I]], [[SUB104_I]]
; CHECK-NEXT:    [[XOR_I178_I:%.*]] = xor i32 [[ADD_I177_I]], [[MUL_I176_I]]
; CHECK-NEXT:    [[SHR_I179_I:%.*]] = lshr i32 [[SUB106_I]], 15
; CHECK-NEXT:    [[AND_I180_I:%.*]] = and i32 [[SHR_I179_I]], 65537
; CHECK-NEXT:    [[MUL_I181_I:%.*]] = mul nuw i32 [[AND_I180_I]], 65535
; CHECK-NEXT:    [[ADD_I182_I:%.*]] = add i32 [[MUL_I181_I]], [[SUB106_I]]
; CHECK-NEXT:    [[XOR_I183_I:%.*]] = xor i32 [[ADD_I182_I]], [[MUL_I181_I]]
; CHECK-NEXT:    [[ADD108_I:%.*]] = add i32 [[XOR_I173_I]], [[SUM_0187_I]]
; CHECK-NEXT:    [[ADD110_I:%.*]] = add i32 [[ADD108_I]], [[XOR_I_I]]
; CHECK-NEXT:    [[ADD112_I:%.*]] = add i32 [[ADD110_I]], [[XOR_I178_I]]
; CHECK-NEXT:    [[ADD113_I:%.*]] = add i32 [[ADD112_I]], [[XOR_I183_I]]
; CHECK-NEXT:    [[ARRAYIDX74_I112:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[I1]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I22:%.*]] = load i32, ptr [[ARRAYIDX74_I112]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX77_I113:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX75_I106]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I23:%.*]] = load i32, ptr [[ARRAYIDX77_I113]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD78_I114:%.*]] = add i32 [[I23]], [[I22]]
; CHECK-NEXT:    [[SUB86_I115:%.*]] = sub i32 [[I22]], [[I23]]
; CHECK-NEXT:    [[ARRAYIDX90_I116:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX88_I107]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I24:%.*]] = load i32, ptr [[ARRAYIDX90_I116]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX93_I117:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX91_I108]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I25:%.*]] = load i32, ptr [[ARRAYIDX93_I117]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD94_I118:%.*]] = add i32 [[I25]], [[I24]]
; CHECK-NEXT:    [[SUB102_I119:%.*]] = sub i32 [[I24]], [[I25]]
; CHECK-NEXT:    [[ADD103_I120:%.*]] = add nsw i32 [[ADD94_I118]], [[ADD78_I114]]
; CHECK-NEXT:    [[SUB104_I121:%.*]] = sub nsw i32 [[ADD78_I114]], [[ADD94_I118]]
; CHECK-NEXT:    [[ADD105_I122:%.*]] = add nsw i32 [[SUB102_I119]], [[SUB86_I115]]
; CHECK-NEXT:    [[SUB106_I123:%.*]] = sub nsw i32 [[SUB86_I115]], [[SUB102_I119]]
; CHECK-NEXT:    [[SHR_I_I124:%.*]] = lshr i32 [[ADD103_I120]], 15
; CHECK-NEXT:    [[AND_I_I125:%.*]] = and i32 [[SHR_I_I124]], 65537
; CHECK-NEXT:    [[MUL_I_I126:%.*]] = mul nuw i32 [[AND_I_I125]], 65535
; CHECK-NEXT:    [[ADD_I_I127:%.*]] = add i32 [[MUL_I_I126]], [[ADD103_I120]]
; CHECK-NEXT:    [[XOR_I_I128:%.*]] = xor i32 [[ADD_I_I127]], [[MUL_I_I126]]
; CHECK-NEXT:    [[SHR_I169_I129:%.*]] = lshr i32 [[ADD105_I122]], 15
; CHECK-NEXT:    [[AND_I170_I130:%.*]] = and i32 [[SHR_I169_I129]], 65537
; CHECK-NEXT:    [[MUL_I171_I131:%.*]] = mul nuw i32 [[AND_I170_I130]], 65535
; CHECK-NEXT:    [[ADD_I172_I132:%.*]] = add i32 [[MUL_I171_I131]], [[ADD105_I122]]
; CHECK-NEXT:    [[XOR_I173_I133:%.*]] = xor i32 [[ADD_I172_I132]], [[MUL_I171_I131]]
; CHECK-NEXT:    [[SHR_I174_I134:%.*]] = lshr i32 [[SUB104_I121]], 15
; CHECK-NEXT:    [[AND_I175_I135:%.*]] = and i32 [[SHR_I174_I134]], 65537
; CHECK-NEXT:    [[MUL_I176_I136:%.*]] = mul nuw i32 [[AND_I175_I135]], 65535
; CHECK-NEXT:    [[ADD_I177_I137:%.*]] = add i32 [[MUL_I176_I136]], [[SUB104_I121]]
; CHECK-NEXT:    [[XOR_I178_I138:%.*]] = xor i32 [[ADD_I177_I137]], [[MUL_I176_I136]]
; CHECK-NEXT:    [[SHR_I179_I139:%.*]] = lshr i32 [[SUB106_I123]], 15
; CHECK-NEXT:    [[AND_I180_I140:%.*]] = and i32 [[SHR_I179_I139]], 65537
; CHECK-NEXT:    [[MUL_I181_I141:%.*]] = mul nuw i32 [[AND_I180_I140]], 65535
; CHECK-NEXT:    [[ADD_I182_I142:%.*]] = add i32 [[MUL_I181_I141]], [[SUB106_I123]]
; CHECK-NEXT:    [[XOR_I183_I143:%.*]] = xor i32 [[ADD_I182_I142]], [[MUL_I181_I141]]
; CHECK-NEXT:    [[ADD108_I144:%.*]] = add i32 [[XOR_I173_I133]], [[ADD113_I]]
; CHECK-NEXT:    [[ADD110_I145:%.*]] = add i32 [[ADD108_I144]], [[XOR_I_I128]]
; CHECK-NEXT:    [[ADD112_I146:%.*]] = add i32 [[ADD110_I145]], [[XOR_I178_I138]]
; CHECK-NEXT:    [[ADD113_I147:%.*]] = add i32 [[ADD112_I146]], [[XOR_I183_I143]]
; CHECK-NEXT:    [[ARRAYIDX74_I231:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[TMP_I155]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I42:%.*]] = load i32, ptr [[ARRAYIDX74_I231]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX77_I232:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX75_I225:%.*]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I43:%.*]] = load i32, ptr [[ARRAYIDX77_I232]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD78_I233:%.*]] = add i32 [[I43]], [[I42]]
; CHECK-NEXT:    [[SUB86_I234:%.*]] = sub i32 [[I42]], [[I43]]
; CHECK-NEXT:    [[ARRAYIDX90_I235:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX88_I226:%.*]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I44:%.*]] = load i32, ptr [[ARRAYIDX90_I235]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX93_I236:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX91_I227:%.*]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I45:%.*]] = load i32, ptr [[ARRAYIDX93_I236]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD94_I237:%.*]] = add i32 [[I45]], [[I44]]
; CHECK-NEXT:    [[SUB102_I238:%.*]] = sub i32 [[I44]], [[I45]]
; CHECK-NEXT:    [[ADD103_I239:%.*]] = add nsw i32 [[ADD94_I237]], [[ADD78_I233]]
; CHECK-NEXT:    [[SUB104_I240:%.*]] = sub nsw i32 [[ADD78_I233]], [[ADD94_I237]]
; CHECK-NEXT:    [[ADD105_I241:%.*]] = add nsw i32 [[SUB102_I238]], [[SUB86_I234]]
; CHECK-NEXT:    [[SUB106_I242:%.*]] = sub nsw i32 [[SUB86_I234]], [[SUB102_I238]]
; CHECK-NEXT:    [[SHR_I_I243:%.*]] = lshr i32 [[ADD103_I239]], 15
; CHECK-NEXT:    [[AND_I_I244:%.*]] = and i32 [[SHR_I_I243]], 65537
; CHECK-NEXT:    [[MUL_I_I245:%.*]] = mul nuw i32 [[AND_I_I244]], 65535
; CHECK-NEXT:    [[ADD_I_I246:%.*]] = add i32 [[MUL_I_I245]], [[ADD103_I239]]
; CHECK-NEXT:    [[XOR_I_I247:%.*]] = xor i32 [[ADD_I_I246]], [[MUL_I_I245]]
; CHECK-NEXT:    [[SHR_I169_I248:%.*]] = lshr i32 [[ADD105_I241]], 15
; CHECK-NEXT:    [[AND_I170_I249:%.*]] = and i32 [[SHR_I169_I248]], 65537
; CHECK-NEXT:    [[MUL_I171_I250:%.*]] = mul nuw i32 [[AND_I170_I249]], 65535
; CHECK-NEXT:    [[ADD_I172_I251:%.*]] = add i32 [[MUL_I171_I250]], [[ADD105_I241]]
; CHECK-NEXT:    [[XOR_I173_I252:%.*]] = xor i32 [[ADD_I172_I251]], [[MUL_I171_I250]]
; CHECK-NEXT:    [[SHR_I174_I253:%.*]] = lshr i32 [[SUB104_I240]], 15
; CHECK-NEXT:    [[AND_I175_I254:%.*]] = and i32 [[SHR_I174_I253]], 65537
; CHECK-NEXT:    [[MUL_I176_I255:%.*]] = mul nuw i32 [[AND_I175_I254]], 65535
; CHECK-NEXT:    [[ADD_I177_I256:%.*]] = add i32 [[MUL_I176_I255]], [[SUB104_I240]]
; CHECK-NEXT:    [[XOR_I178_I257:%.*]] = xor i32 [[ADD_I177_I256]], [[MUL_I176_I255]]
; CHECK-NEXT:    [[SHR_I179_I258:%.*]] = lshr i32 [[SUB106_I242]], 15
; CHECK-NEXT:    [[AND_I180_I259:%.*]] = and i32 [[SHR_I179_I258]], 65537
; CHECK-NEXT:    [[MUL_I181_I260:%.*]] = mul nuw i32 [[AND_I180_I259]], 65535
; CHECK-NEXT:    [[ADD_I182_I261:%.*]] = add i32 [[MUL_I181_I260]], [[SUB106_I242]]
; CHECK-NEXT:    [[XOR_I183_I262:%.*]] = xor i32 [[ADD_I182_I261]], [[MUL_I181_I260]]
; CHECK-NEXT:    [[ADD108_I263:%.*]] = add i32 [[XOR_I173_I252]], [[ADD113_I147]]
; CHECK-NEXT:    [[ADD110_I264:%.*]] = add i32 [[ADD108_I263]], [[XOR_I_I247]]
; CHECK-NEXT:    [[ADD112_I265:%.*]] = add i32 [[ADD110_I264]], [[XOR_I178_I257]]
; CHECK-NEXT:    [[ADD113_I266:%.*]] = add i32 [[ADD112_I265]], [[XOR_I183_I262]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT191_I]] = add nuw nsw i64 [[INDVARS_IV190_I]], 1
; CHECK-NEXT:    [[ARRAYIDX74_I350:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[I]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I46:%.*]] = load i32, ptr [[ARRAYIDX74_I350]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX77_I351:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX75_I344:%.*]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I47:%.*]] = load i32, ptr [[ARRAYIDX77_I351]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD78_I352:%.*]] = add i32 [[I47]], [[I46]]
; CHECK-NEXT:    [[SUB86_I353:%.*]] = sub i32 [[I46]], [[I47]]
; CHECK-NEXT:    [[ARRAYIDX90_I354:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX88_I345:%.*]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I48:%.*]] = load i32, ptr [[ARRAYIDX90_I354]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX93_I355:%.*]] = getelementptr inbounds nuw [4 x i32], ptr [[ARRAYIDX91_I346:%.*]], i64 0, i64 [[INDVARS_IV190_I]]
; CHECK-NEXT:    [[I49:%.*]] = load i32, ptr [[ARRAYIDX93_I355]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD94_I356:%.*]] = add i32 [[I49]], [[I48]]
; CHECK-NEXT:    [[SUB102_I357:%.*]] = sub i32 [[I48]], [[I49]]
; CHECK-NEXT:    [[ADD103_I358:%.*]] = add nsw i32 [[ADD94_I356]], [[ADD78_I352]]
; CHECK-NEXT:    [[SUB104_I359:%.*]] = sub nsw i32 [[ADD78_I352]], [[ADD94_I356]]
; CHECK-NEXT:    [[ADD105_I360:%.*]] = add nsw i32 [[SUB102_I357]], [[SUB86_I353]]
; CHECK-NEXT:    [[SUB106_I361:%.*]] = sub nsw i32 [[SUB86_I353]], [[SUB102_I357]]
; CHECK-NEXT:    [[SHR_I_I362:%.*]] = lshr i32 [[ADD103_I358]], 15
; CHECK-NEXT:    [[AND_I_I363:%.*]] = and i32 [[SHR_I_I362]], 65537
; CHECK-NEXT:    [[MUL_I_I364:%.*]] = mul nuw i32 [[AND_I_I363]], 65535
; CHECK-NEXT:    [[ADD_I_I365:%.*]] = add i32 [[MUL_I_I364]], [[ADD103_I358]]
; CHECK-NEXT:    [[XOR_I_I366:%.*]] = xor i32 [[ADD_I_I365]], [[MUL_I_I364]]
; CHECK-NEXT:    [[SHR_I169_I367:%.*]] = lshr i32 [[ADD105_I360]], 15
; CHECK-NEXT:    [[AND_I170_I368:%.*]] = and i32 [[SHR_I169_I367]], 65537
; CHECK-NEXT:    [[MUL_I171_I369:%.*]] = mul nuw i32 [[AND_I170_I368]], 65535
; CHECK-NEXT:    [[ADD_I172_I370:%.*]] = add i32 [[MUL_I171_I369]], [[ADD105_I360]]
; CHECK-NEXT:    [[XOR_I173_I371:%.*]] = xor i32 [[ADD_I172_I370]], [[MUL_I171_I369]]
; CHECK-NEXT:    [[SHR_I174_I372:%.*]] = lshr i32 [[SUB104_I359]], 15
; CHECK-NEXT:    [[AND_I175_I373:%.*]] = and i32 [[SHR_I174_I372]], 65537
; CHECK-NEXT:    [[MUL_I176_I374:%.*]] = mul nuw i32 [[AND_I175_I373]], 65535
; CHECK-NEXT:    [[ADD_I177_I375:%.*]] = add i32 [[MUL_I176_I374]], [[SUB104_I359]]
; CHECK-NEXT:    [[XOR_I178_I376:%.*]] = xor i32 [[ADD_I177_I375]], [[MUL_I176_I374]]
; CHECK-NEXT:    [[SHR_I179_I377:%.*]] = lshr i32 [[SUB106_I361]], 15
; CHECK-NEXT:    [[AND_I180_I378:%.*]] = and i32 [[SHR_I179_I377]], 65537
; CHECK-NEXT:    [[MUL_I181_I379:%.*]] = mul nuw i32 [[AND_I180_I378]], 65535
; CHECK-NEXT:    [[ADD_I182_I380:%.*]] = add i32 [[MUL_I181_I379]], [[SUB106_I361]]
; CHECK-NEXT:    [[XOR_I183_I381:%.*]] = xor i32 [[ADD_I182_I380]], [[MUL_I181_I379]]
; CHECK-NEXT:    [[ADD108_I382:%.*]] = add i32 [[XOR_I173_I371]], [[ADD113_I266]]
; CHECK-NEXT:    [[ADD110_I383:%.*]] = add i32 [[ADD108_I382]], [[XOR_I_I366]]
; CHECK-NEXT:    [[ADD112_I384:%.*]] = add i32 [[ADD110_I383]], [[XOR_I178_I376]]
; CHECK-NEXT:    [[ADD113_I385]] = add i32 [[ADD112_I384]], [[XOR_I183_I381]]
; CHECK-NEXT:    [[EXITCOND193_NOT_I387:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT191_I]], 4
; CHECK-NEXT:    br i1 [[EXITCOND193_NOT_I387]], label %[[X264_PIXEL_SATD_8X4_EXIT392:.*]], label %[[FOR_BODY70_I]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[X264_PIXEL_SATD_8X4_EXIT154]]:
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 128, ptr nonnull [[TMP_I]]) #[[ATTR1]]
; CHECK-NEXT:    [[ADD_PTR5:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1]], i64 8
; CHECK-NEXT:    [[ADD_PTR6:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2]], i64 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 128, ptr nonnull [[TMP_I155]]) #[[ATTR1]]
; CHECK-NEXT:    br label %[[FOR_BODY_I158:.*]]
; CHECK:       [[FOR_COND66_PREHEADER_I224]]:
; CHECK-NEXT:    [[ARRAYIDX75_I225]] = getelementptr inbounds nuw i8, ptr [[TMP_I155]], i64 16
; CHECK-NEXT:    [[ARRAYIDX88_I226]] = getelementptr inbounds nuw i8, ptr [[TMP_I155]], i64 32
; CHECK-NEXT:    [[ARRAYIDX91_I227]] = getelementptr inbounds nuw i8, ptr [[TMP_I155]], i64 48
; CHECK-NEXT:    [[ARRAYIDX75_I344]] = getelementptr inbounds nuw i8, ptr [[I]], i64 16
; CHECK-NEXT:    [[ARRAYIDX88_I345]] = getelementptr inbounds nuw i8, ptr [[I]], i64 32
; CHECK-NEXT:    [[ARRAYIDX91_I346]] = getelementptr inbounds nuw i8, ptr [[I]], i64 48
; CHECK-NEXT:    br label %[[FOR_BODY70_I]]
; CHECK:       [[FOR_BODY_I158]]:
; CHECK-NEXT:    [[INDVARS_IV_I159:%.*]] = phi i64 [ 0, %[[X264_PIXEL_SATD_8X4_EXIT154]] ], [ [[INDVARS_IV_NEXT_I220_1:%.*]], %[[FOR_BODY_I158]] ]
; CHECK-NEXT:    [[PIX1_ADDR_0186_I160:%.*]] = phi ptr [ [[ADD_PTR5]], %[[X264_PIXEL_SATD_8X4_EXIT154]] ], [ [[ADD_PTR_I221_1:%.*]], %[[FOR_BODY_I158]] ]
; CHECK-NEXT:    [[PIX2_ADDR_0185_I161:%.*]] = phi ptr [ [[ADD_PTR6]], %[[X264_PIXEL_SATD_8X4_EXIT154]] ], [ [[ADD_PTR64_I222_1:%.*]], %[[FOR_BODY_I158]] ]
; CHECK-NEXT:    [[I26:%.*]] = load i8, ptr [[PIX1_ADDR_0186_I160]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV_I162:%.*]] = zext i8 [[I26]] to i32
; CHECK-NEXT:    [[I27:%.*]] = load i8, ptr [[PIX2_ADDR_0185_I161]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2_I163:%.*]] = zext i8 [[I27]] to i32
; CHECK-NEXT:    [[SUB_I164:%.*]] = sub nsw i32 [[CONV_I162]], [[CONV2_I163]]
; CHECK-NEXT:    [[ARRAYIDX3_I165:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 4
; CHECK-NEXT:    [[I28:%.*]] = load i8, ptr [[ARRAYIDX3_I165]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4_I166:%.*]] = zext i8 [[I28]] to i32
; CHECK-NEXT:    [[ARRAYIDX5_I167:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 4
; CHECK-NEXT:    [[I29:%.*]] = load i8, ptr [[ARRAYIDX5_I167]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6_I168:%.*]] = zext i8 [[I29]] to i32
; CHECK-NEXT:    [[SUB7_I169:%.*]] = sub nsw i32 [[CONV4_I166]], [[CONV6_I168]]
; CHECK-NEXT:    [[SHL_I170:%.*]] = shl nsw i32 [[SUB7_I169]], 16
; CHECK-NEXT:    [[ADD_I171:%.*]] = add nsw i32 [[SHL_I170]], [[SUB_I164]]
; CHECK-NEXT:    [[ARRAYIDX8_I172:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 1
; CHECK-NEXT:    [[I30:%.*]] = load i8, ptr [[ARRAYIDX8_I172]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9_I173:%.*]] = zext i8 [[I30]] to i32
; CHECK-NEXT:    [[ARRAYIDX10_I174:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 1
; CHECK-NEXT:    [[I31:%.*]] = load i8, ptr [[ARRAYIDX10_I174]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11_I175:%.*]] = zext i8 [[I31]] to i32
; CHECK-NEXT:    [[SUB12_I176:%.*]] = sub nsw i32 [[CONV9_I173]], [[CONV11_I175]]
; CHECK-NEXT:    [[ARRAYIDX13_I177:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 5
; CHECK-NEXT:    [[I32:%.*]] = load i8, ptr [[ARRAYIDX13_I177]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14_I178:%.*]] = zext i8 [[I32]] to i32
; CHECK-NEXT:    [[ARRAYIDX15_I179:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 5
; CHECK-NEXT:    [[I33:%.*]] = load i8, ptr [[ARRAYIDX15_I179]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16_I180:%.*]] = zext i8 [[I33]] to i32
; CHECK-NEXT:    [[SUB17_I181:%.*]] = sub nsw i32 [[CONV14_I178]], [[CONV16_I180]]
; CHECK-NEXT:    [[SHL18_I182:%.*]] = shl nsw i32 [[SUB17_I181]], 16
; CHECK-NEXT:    [[ADD19_I183:%.*]] = add nsw i32 [[SHL18_I182]], [[SUB12_I176]]
; CHECK-NEXT:    [[ARRAYIDX20_I184:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 2
; CHECK-NEXT:    [[I34:%.*]] = load i8, ptr [[ARRAYIDX20_I184]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21_I185:%.*]] = zext i8 [[I34]] to i32
; CHECK-NEXT:    [[ARRAYIDX22_I186:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 2
; CHECK-NEXT:    [[I35:%.*]] = load i8, ptr [[ARRAYIDX22_I186]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23_I187:%.*]] = zext i8 [[I35]] to i32
; CHECK-NEXT:    [[SUB24_I188:%.*]] = sub nsw i32 [[CONV21_I185]], [[CONV23_I187]]
; CHECK-NEXT:    [[ARRAYIDX25_I189:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 6
; CHECK-NEXT:    [[I36:%.*]] = load i8, ptr [[ARRAYIDX25_I189]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26_I190:%.*]] = zext i8 [[I36]] to i32
; CHECK-NEXT:    [[ARRAYIDX27_I191:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 6
; CHECK-NEXT:    [[I37:%.*]] = load i8, ptr [[ARRAYIDX27_I191]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28_I192:%.*]] = zext i8 [[I37]] to i32
; CHECK-NEXT:    [[SUB29_I193:%.*]] = sub nsw i32 [[CONV26_I190]], [[CONV28_I192]]
; CHECK-NEXT:    [[SHL30_I194:%.*]] = shl nsw i32 [[SUB29_I193]], 16
; CHECK-NEXT:    [[ADD31_I195:%.*]] = add nsw i32 [[SHL30_I194]], [[SUB24_I188]]
; CHECK-NEXT:    [[ARRAYIDX32_I196:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 3
; CHECK-NEXT:    [[I38:%.*]] = load i8, ptr [[ARRAYIDX32_I196]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33_I197:%.*]] = zext i8 [[I38]] to i32
; CHECK-NEXT:    [[ARRAYIDX34_I198:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 3
; CHECK-NEXT:    [[I39:%.*]] = load i8, ptr [[ARRAYIDX34_I198]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35_I199:%.*]] = zext i8 [[I39]] to i32
; CHECK-NEXT:    [[SUB36_I200:%.*]] = sub nsw i32 [[CONV33_I197]], [[CONV35_I199]]
; CHECK-NEXT:    [[ARRAYIDX37_I201:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX1_ADDR_0186_I160]], i64 7
; CHECK-NEXT:    [[I40:%.*]] = load i8, ptr [[ARRAYIDX37_I201]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38_I202:%.*]] = zext i8 [[I40]] to i32
; CHECK-NEXT:    [[ARRAYIDX39_I203:%.*]] = getelementptr inbounds nuw i8, ptr [[PIX2_ADDR_0185_I161]], i64 7
; CHECK-NEXT:    [[I41:%.*]] = load i8, ptr [[ARRAYIDX39_I203]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40_I204:%.*]] = zext i8 [[I41]] to i32
; CHECK-NEXT:    [[SUB41_I205:%.*]] = sub nsw i32 [[CONV38_I202]], [[CONV40_I204]]
; CHECK-NEXT:    [[SHL42_I206:%.*]] = shl nsw i32 [[SUB41_I205]], 16
; CHECK-NEXT:    [[ADD43_I207:%.*]] = add nsw i32 [[SHL42_I206]], [[SUB36_I200]]
; CHECK-NEXT:    [[ADD44_I208:%.*]] = add nsw i32 [[ADD19_I183]], [[ADD_I171]]
; CHECK-NEXT:    [[SUB45_I209:%.*]] = sub nsw i32 [[ADD_I171]], [[ADD19_I183]]
; CHECK-NEXT:    [[ADD46_I210:%.*]] = add nsw i32 [[ADD43_I207]], [[ADD31_I195]]
; CHECK-NEXT:    [[SUB47_I211:%.*]] = sub nsw i32 [[ADD31_I195]], [[ADD43_I207]]
; CHECK-NEXT:    [[ADD48_I212:%.*]] = add nsw i32 [[ADD46_I210]], [[ADD44_I208]]
; CHECK-NEXT:    [[ARRAYIDX49_I213:%.*]] = getelementptr inbounds nuw [8 x [4 x i32]], ptr [[TMP_I155]], i64 0, i64 [[INDVARS_IV_I159]]
; CHECK-NEXT:    store i32 [[ADD48_I212]], ptr [[ARRAYIDX49_I213]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB51_I214:%.*]] = sub nsw i32 [[ADD44_I208]], [[ADD46_I210]]
; CHECK-NEXT:    [[ARRAYIDX54_I215:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I213]], i64 8
; CHECK-NEXT:    store i32 [[SUB51_I214]], ptr [[ARRAYIDX54_I215]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55_I216:%.*]] = add nsw i32 [[SUB47_I211]], [[SUB45_I209]]
; CHECK-NEXT:    [[ARRAYIDX58_I217:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I213]], i64 4
; CHECK-NEXT:    store i32 [[ADD55_I216]], ptr [[ARRAYIDX58_I217]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59_I218:%.*]] = sub nsw i32 [[SUB45_I209]], [[SUB47_I211]]
; CHECK-NEXT:    [[ARRAYIDX62_I219:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I213]], i64 12
; CHECK-NEXT:    store i32 [[SUB59_I218]], ptr [[ARRAYIDX62_I219]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I220:%.*]] = add nuw nsw i64 [[INDVARS_IV_I159]], 1
; CHECK-NEXT:    [[ADD_PTR_I221:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0186_I160]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR64_I222:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0185_I161]], i64 [[IDX_EXT63_I]]
; CHECK-NEXT:    [[I26_1:%.*]] = load i8, ptr [[ADD_PTR_I221]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV_I162_1:%.*]] = zext i8 [[I26_1]] to i32
; CHECK-NEXT:    [[I27_1:%.*]] = load i8, ptr [[ADD_PTR64_I222]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2_I163_1:%.*]] = zext i8 [[I27_1]] to i32
; CHECK-NEXT:    [[SUB_I164_1:%.*]] = sub nsw i32 [[CONV_I162_1]], [[CONV2_I163_1]]
; CHECK-NEXT:    [[ARRAYIDX3_I165_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 4
; CHECK-NEXT:    [[I28_1:%.*]] = load i8, ptr [[ARRAYIDX3_I165_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4_I166_1:%.*]] = zext i8 [[I28_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX5_I167_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 4
; CHECK-NEXT:    [[I29_1:%.*]] = load i8, ptr [[ARRAYIDX5_I167_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6_I168_1:%.*]] = zext i8 [[I29_1]] to i32
; CHECK-NEXT:    [[SUB7_I169_1:%.*]] = sub nsw i32 [[CONV4_I166_1]], [[CONV6_I168_1]]
; CHECK-NEXT:    [[SHL_I170_1:%.*]] = shl nsw i32 [[SUB7_I169_1]], 16
; CHECK-NEXT:    [[ADD_I171_1:%.*]] = add nsw i32 [[SHL_I170_1]], [[SUB_I164_1]]
; CHECK-NEXT:    [[ARRAYIDX8_I172_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 1
; CHECK-NEXT:    [[I30_1:%.*]] = load i8, ptr [[ARRAYIDX8_I172_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9_I173_1:%.*]] = zext i8 [[I30_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX10_I174_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 1
; CHECK-NEXT:    [[I31_1:%.*]] = load i8, ptr [[ARRAYIDX10_I174_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11_I175_1:%.*]] = zext i8 [[I31_1]] to i32
; CHECK-NEXT:    [[SUB12_I176_1:%.*]] = sub nsw i32 [[CONV9_I173_1]], [[CONV11_I175_1]]
; CHECK-NEXT:    [[ARRAYIDX13_I177_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 5
; CHECK-NEXT:    [[I32_1:%.*]] = load i8, ptr [[ARRAYIDX13_I177_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14_I178_1:%.*]] = zext i8 [[I32_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX15_I179_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 5
; CHECK-NEXT:    [[I33_1:%.*]] = load i8, ptr [[ARRAYIDX15_I179_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16_I180_1:%.*]] = zext i8 [[I33_1]] to i32
; CHECK-NEXT:    [[SUB17_I181_1:%.*]] = sub nsw i32 [[CONV14_I178_1]], [[CONV16_I180_1]]
; CHECK-NEXT:    [[SHL18_I182_1:%.*]] = shl nsw i32 [[SUB17_I181_1]], 16
; CHECK-NEXT:    [[ADD19_I183_1:%.*]] = add nsw i32 [[SHL18_I182_1]], [[SUB12_I176_1]]
; CHECK-NEXT:    [[ARRAYIDX20_I184_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 2
; CHECK-NEXT:    [[I34_1:%.*]] = load i8, ptr [[ARRAYIDX20_I184_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21_I185_1:%.*]] = zext i8 [[I34_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX22_I186_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 2
; CHECK-NEXT:    [[I35_1:%.*]] = load i8, ptr [[ARRAYIDX22_I186_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23_I187_1:%.*]] = zext i8 [[I35_1]] to i32
; CHECK-NEXT:    [[SUB24_I188_1:%.*]] = sub nsw i32 [[CONV21_I185_1]], [[CONV23_I187_1]]
; CHECK-NEXT:    [[ARRAYIDX25_I189_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 6
; CHECK-NEXT:    [[I36_1:%.*]] = load i8, ptr [[ARRAYIDX25_I189_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26_I190_1:%.*]] = zext i8 [[I36_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX27_I191_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 6
; CHECK-NEXT:    [[I37_1:%.*]] = load i8, ptr [[ARRAYIDX27_I191_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28_I192_1:%.*]] = zext i8 [[I37_1]] to i32
; CHECK-NEXT:    [[SUB29_I193_1:%.*]] = sub nsw i32 [[CONV26_I190_1]], [[CONV28_I192_1]]
; CHECK-NEXT:    [[SHL30_I194_1:%.*]] = shl nsw i32 [[SUB29_I193_1]], 16
; CHECK-NEXT:    [[ADD31_I195_1:%.*]] = add nsw i32 [[SHL30_I194_1]], [[SUB24_I188_1]]
; CHECK-NEXT:    [[ARRAYIDX32_I196_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 3
; CHECK-NEXT:    [[I38_1:%.*]] = load i8, ptr [[ARRAYIDX32_I196_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33_I197_1:%.*]] = zext i8 [[I38_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX34_I198_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 3
; CHECK-NEXT:    [[I39_1:%.*]] = load i8, ptr [[ARRAYIDX34_I198_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35_I199_1:%.*]] = zext i8 [[I39_1]] to i32
; CHECK-NEXT:    [[SUB36_I200_1:%.*]] = sub nsw i32 [[CONV33_I197_1]], [[CONV35_I199_1]]
; CHECK-NEXT:    [[ARRAYIDX37_I201_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR_I221]], i64 7
; CHECK-NEXT:    [[I40_1:%.*]] = load i8, ptr [[ARRAYIDX37_I201_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38_I202_1:%.*]] = zext i8 [[I40_1]] to i32
; CHECK-NEXT:    [[ARRAYIDX39_I203_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ADD_PTR64_I222]], i64 7
; CHECK-NEXT:    [[I41_1:%.*]] = load i8, ptr [[ARRAYIDX39_I203_1]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40_I204_1:%.*]] = zext i8 [[I41_1]] to i32
; CHECK-NEXT:    [[SUB41_I205_1:%.*]] = sub nsw i32 [[CONV38_I202_1]], [[CONV40_I204_1]]
; CHECK-NEXT:    [[SHL42_I206_1:%.*]] = shl nsw i32 [[SUB41_I205_1]], 16
; CHECK-NEXT:    [[ADD43_I207_1:%.*]] = add nsw i32 [[SHL42_I206_1]], [[SUB36_I200_1]]
; CHECK-NEXT:    [[ADD44_I208_1:%.*]] = add nsw i32 [[ADD19_I183_1]], [[ADD_I171_1]]
; CHECK-NEXT:    [[SUB45_I209_1:%.*]] = sub nsw i32 [[ADD_I171_1]], [[ADD19_I183_1]]
; CHECK-NEXT:    [[ADD46_I210_1:%.*]] = add nsw i32 [[ADD43_I207_1]], [[ADD31_I195_1]]
; CHECK-NEXT:    [[SUB47_I211_1:%.*]] = sub nsw i32 [[ADD31_I195_1]], [[ADD43_I207_1]]
; CHECK-NEXT:    [[ADD48_I212_1:%.*]] = add nsw i32 [[ADD46_I210_1]], [[ADD44_I208_1]]
; CHECK-NEXT:    [[ARRAYIDX49_I213_1:%.*]] = getelementptr inbounds nuw [8 x [4 x i32]], ptr [[TMP_I155]], i64 0, i64 [[INDVARS_IV_NEXT_I220]]
; CHECK-NEXT:    store i32 [[ADD48_I212_1]], ptr [[ARRAYIDX49_I213_1]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB51_I214_1:%.*]] = sub nsw i32 [[ADD44_I208_1]], [[ADD46_I210_1]]
; CHECK-NEXT:    [[ARRAYIDX54_I215_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I213_1]], i64 8
; CHECK-NEXT:    store i32 [[SUB51_I214_1]], ptr [[ARRAYIDX54_I215_1]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55_I216_1:%.*]] = add nsw i32 [[SUB47_I211_1]], [[SUB45_I209_1]]
; CHECK-NEXT:    [[ARRAYIDX58_I217_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I213_1]], i64 4
; CHECK-NEXT:    store i32 [[ADD55_I216_1]], ptr [[ARRAYIDX58_I217_1]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59_I218_1:%.*]] = sub nsw i32 [[SUB45_I209_1]], [[SUB47_I211_1]]
; CHECK-NEXT:    [[ARRAYIDX62_I219_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX49_I213_1]], i64 12
; CHECK-NEXT:    store i32 [[SUB59_I218_1]], ptr [[ARRAYIDX62_I219_1]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I220_1]] = add nuw nsw i64 [[INDVARS_IV_I159]], 2
; CHECK-NEXT:    [[ADD_PTR_I221_1]] = getelementptr inbounds i8, ptr [[ADD_PTR_I221]], i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ADD_PTR64_I222_1]] = getelementptr inbounds i8, ptr [[ADD_PTR64_I222]], i64 [[IDX_EXT63_I]]
; CHECK-NEXT:    [[EXITCOND_NOT_I223_1:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT_I220_1]], 8
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I223_1]], label %[[FOR_COND66_PREHEADER_I224]], label %[[FOR_BODY_I158]], !llvm.loop [[LOOP5]]
; CHECK:       [[X264_PIXEL_SATD_8X4_EXIT392]]:
; CHECK-NEXT:    [[ADD113_I385_LCSSA:%.*]] = phi i32 [ [[ADD113_I385]], %[[FOR_BODY70_I]] ]
; CHECK-NEXT:    [[CONV118_I388:%.*]] = and i32 [[ADD113_I385_LCSSA]], 65535
; CHECK-NEXT:    [[SHR_I389:%.*]] = lshr i32 [[ADD113_I385_LCSSA]], 16
; CHECK-NEXT:    [[ADD119_I390:%.*]] = add nuw nsw i32 [[CONV118_I388]], [[SHR_I389]]
; CHECK-NEXT:    [[SHR120_I391:%.*]] = lshr i32 [[ADD119_I390]], 1
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 128, ptr nonnull [[TMP_I155]]) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[SHR120_I391]]
;
entry:
  %tmp.i155 = alloca [8 x [4 x i32]], align 8
  %tmp.i = alloca [8 x [4 x i32]], align 8
  %i = getelementptr inbounds i8, ptr %tmp.i155, i64 64
  %i1 = getelementptr inbounds i8, ptr %tmp.i, i64 64
  call void @llvm.lifetime.start.p0(i64 128, ptr nonnull %tmp.i) #1
  %idx.ext.i = sext i32 %i_pix1 to i64
  %idx.ext63.i = sext i32 %i_pix2 to i64
  %mul = shl nsw i32 %i_pix1, 2
  %idx.ext = sext i32 %mul to i64
  %add.ptr = getelementptr inbounds i8, ptr %pix1, i64 %idx.ext
  %mul1 = shl nsw i32 %i_pix2, 2
  %idx.ext2 = sext i32 %mul1 to i64
  %add.ptr3 = getelementptr inbounds i8, ptr %pix2, i64 %idx.ext2
  br label %for.body.i

for.cond66.preheader.i:                           ; preds = %for.body.i
  %arrayidx75.i = getelementptr inbounds nuw i8, ptr %tmp.i, i64 16
  %arrayidx88.i = getelementptr inbounds nuw i8, ptr %tmp.i, i64 32
  %arrayidx91.i = getelementptr inbounds nuw i8, ptr %tmp.i, i64 48
  br label %for.body70.i

for.body.i:                                       ; preds = %for.body.i, %entry
  %indvars.iv.i = phi i64 [ 0, %entry ], [ %indvars.iv.next.i, %for.body.i ]
  %pix1.addr.0186.i = phi ptr [ %pix1, %entry ], [ %add.ptr.i, %for.body.i ]
  %pix2.addr.0185.i = phi ptr [ %pix2, %entry ], [ %add.ptr64.i, %for.body.i ]
  %i2 = load i8, ptr %pix1.addr.0186.i, align 1, !tbaa !0
  %conv.i = zext i8 %i2 to i32
  %i3 = load i8, ptr %pix2.addr.0185.i, align 1, !tbaa !0
  %conv2.i = zext i8 %i3 to i32
  %sub.i = sub nsw i32 %conv.i, %conv2.i
  %arrayidx3.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 4
  %i4 = load i8, ptr %arrayidx3.i, align 1, !tbaa !0
  %conv4.i = zext i8 %i4 to i32
  %arrayidx5.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 4
  %i5 = load i8, ptr %arrayidx5.i, align 1, !tbaa !0
  %conv6.i = zext i8 %i5 to i32
  %sub7.i = sub nsw i32 %conv4.i, %conv6.i
  %shl.i = shl nsw i32 %sub7.i, 16
  %add.i = add nsw i32 %shl.i, %sub.i
  %arrayidx8.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 1
  %i6 = load i8, ptr %arrayidx8.i, align 1, !tbaa !0
  %conv9.i = zext i8 %i6 to i32
  %arrayidx10.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 1
  %i7 = load i8, ptr %arrayidx10.i, align 1, !tbaa !0
  %conv11.i = zext i8 %i7 to i32
  %sub12.i = sub nsw i32 %conv9.i, %conv11.i
  %arrayidx13.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 5
  %i8 = load i8, ptr %arrayidx13.i, align 1, !tbaa !0
  %conv14.i = zext i8 %i8 to i32
  %arrayidx15.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 5
  %i9 = load i8, ptr %arrayidx15.i, align 1, !tbaa !0
  %conv16.i = zext i8 %i9 to i32
  %sub17.i = sub nsw i32 %conv14.i, %conv16.i
  %shl18.i = shl nsw i32 %sub17.i, 16
  %add19.i = add nsw i32 %shl18.i, %sub12.i
  %arrayidx20.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 2
  %i10 = load i8, ptr %arrayidx20.i, align 1, !tbaa !0
  %conv21.i = zext i8 %i10 to i32
  %arrayidx22.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 2
  %i11 = load i8, ptr %arrayidx22.i, align 1, !tbaa !0
  %conv23.i = zext i8 %i11 to i32
  %sub24.i = sub nsw i32 %conv21.i, %conv23.i
  %arrayidx25.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 6
  %i12 = load i8, ptr %arrayidx25.i, align 1, !tbaa !0
  %conv26.i = zext i8 %i12 to i32
  %arrayidx27.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 6
  %i13 = load i8, ptr %arrayidx27.i, align 1, !tbaa !0
  %conv28.i = zext i8 %i13 to i32
  %sub29.i = sub nsw i32 %conv26.i, %conv28.i
  %shl30.i = shl nsw i32 %sub29.i, 16
  %add31.i = add nsw i32 %shl30.i, %sub24.i
  %arrayidx32.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 3
  %i14 = load i8, ptr %arrayidx32.i, align 1, !tbaa !0
  %conv33.i = zext i8 %i14 to i32
  %arrayidx34.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 3
  %i15 = load i8, ptr %arrayidx34.i, align 1, !tbaa !0
  %conv35.i = zext i8 %i15 to i32
  %sub36.i = sub nsw i32 %conv33.i, %conv35.i
  %arrayidx37.i = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i, i64 7
  %i16 = load i8, ptr %arrayidx37.i, align 1, !tbaa !0
  %conv38.i = zext i8 %i16 to i32
  %arrayidx39.i = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i, i64 7
  %i17 = load i8, ptr %arrayidx39.i, align 1, !tbaa !0
  %conv40.i = zext i8 %i17 to i32
  %sub41.i = sub nsw i32 %conv38.i, %conv40.i
  %shl42.i = shl nsw i32 %sub41.i, 16
  %add43.i = add nsw i32 %shl42.i, %sub36.i
  %add44.i = add nsw i32 %add19.i, %add.i
  %sub45.i = sub nsw i32 %add.i, %add19.i
  %add46.i = add nsw i32 %add43.i, %add31.i
  %sub47.i = sub nsw i32 %add31.i, %add43.i
  %add48.i = add nsw i32 %add46.i, %add44.i
  %arrayidx49.i = getelementptr inbounds nuw [8 x [4 x i32]], ptr %tmp.i, i64 0, i64 %indvars.iv.i
  store i32 %add48.i, ptr %arrayidx49.i, align 8, !tbaa !3
  %sub51.i = sub nsw i32 %add44.i, %add46.i
  %arrayidx54.i = getelementptr inbounds nuw i8, ptr %arrayidx49.i, i64 8
  store i32 %sub51.i, ptr %arrayidx54.i, align 8, !tbaa !3
  %add55.i = add nsw i32 %sub47.i, %sub45.i
  %arrayidx58.i = getelementptr inbounds nuw i8, ptr %arrayidx49.i, i64 4
  store i32 %add55.i, ptr %arrayidx58.i, align 4, !tbaa !3
  %sub59.i = sub nsw i32 %sub45.i, %sub47.i
  %arrayidx62.i = getelementptr inbounds nuw i8, ptr %arrayidx49.i, i64 12
  store i32 %sub59.i, ptr %arrayidx62.i, align 4, !tbaa !3
  %indvars.iv.next.i = add nuw nsw i64 %indvars.iv.i, 1
  %add.ptr.i = getelementptr inbounds i8, ptr %pix1.addr.0186.i, i64 %idx.ext.i
  %add.ptr64.i = getelementptr inbounds i8, ptr %pix2.addr.0185.i, i64 %idx.ext63.i
  %exitcond.not.i = icmp eq i64 %indvars.iv.next.i, 8
  br i1 %exitcond.not.i, label %for.cond66.preheader.i, label %for.body.i, !llvm.loop !5

for.body70.i:                                     ; preds = %for.body70.i, %for.cond66.preheader.i
  %indvars.iv190.i = phi i64 [ 0, %for.cond66.preheader.i ], [ %indvars.iv.next191.i, %for.body70.i ]
  %sum.0187.i = phi i32 [ 0, %for.cond66.preheader.i ], [ %add113.i, %for.body70.i ]
  %arrayidx74.i = getelementptr inbounds nuw [4 x i32], ptr %tmp.i, i64 0, i64 %indvars.iv190.i
  %i18 = load i32, ptr %arrayidx74.i, align 4, !tbaa !3
  %arrayidx77.i = getelementptr inbounds nuw [4 x i32], ptr %arrayidx75.i, i64 0, i64 %indvars.iv190.i
  %i19 = load i32, ptr %arrayidx77.i, align 4, !tbaa !3
  %add78.i = add i32 %i19, %i18
  %sub86.i = sub i32 %i18, %i19
  %arrayidx90.i = getelementptr inbounds nuw [4 x i32], ptr %arrayidx88.i, i64 0, i64 %indvars.iv190.i
  %i20 = load i32, ptr %arrayidx90.i, align 4, !tbaa !3
  %arrayidx93.i = getelementptr inbounds nuw [4 x i32], ptr %arrayidx91.i, i64 0, i64 %indvars.iv190.i
  %i21 = load i32, ptr %arrayidx93.i, align 4, !tbaa !3
  %add94.i = add i32 %i21, %i20
  %sub102.i = sub i32 %i20, %i21
  %add103.i = add nsw i32 %add94.i, %add78.i
  %sub104.i = sub nsw i32 %add78.i, %add94.i
  %add105.i = add nsw i32 %sub102.i, %sub86.i
  %sub106.i = sub nsw i32 %sub86.i, %sub102.i
  %shr.i.i = lshr i32 %add103.i, 15
  %and.i.i = and i32 %shr.i.i, 65537
  %mul.i.i = mul nuw i32 %and.i.i, 65535
  %add.i.i = add i32 %mul.i.i, %add103.i
  %xor.i.i = xor i32 %add.i.i, %mul.i.i
  %shr.i169.i = lshr i32 %add105.i, 15
  %and.i170.i = and i32 %shr.i169.i, 65537
  %mul.i171.i = mul nuw i32 %and.i170.i, 65535
  %add.i172.i = add i32 %mul.i171.i, %add105.i
  %xor.i173.i = xor i32 %add.i172.i, %mul.i171.i
  %shr.i174.i = lshr i32 %sub104.i, 15
  %and.i175.i = and i32 %shr.i174.i, 65537
  %mul.i176.i = mul nuw i32 %and.i175.i, 65535
  %add.i177.i = add i32 %mul.i176.i, %sub104.i
  %xor.i178.i = xor i32 %add.i177.i, %mul.i176.i
  %shr.i179.i = lshr i32 %sub106.i, 15
  %and.i180.i = and i32 %shr.i179.i, 65537
  %mul.i181.i = mul nuw i32 %and.i180.i, 65535
  %add.i182.i = add i32 %mul.i181.i, %sub106.i
  %xor.i183.i = xor i32 %add.i182.i, %mul.i181.i
  %add108.i = add i32 %xor.i173.i, %sum.0187.i
  %add110.i = add i32 %add108.i, %xor.i.i
  %add112.i = add i32 %add110.i, %xor.i178.i
  %add113.i = add i32 %add112.i, %xor.i183.i
  %indvars.iv.next191.i = add nuw nsw i64 %indvars.iv190.i, 1
  %exitcond193.not.i = icmp eq i64 %indvars.iv.next191.i, 4
  br i1 %exitcond193.not.i, label %for.cond66.preheader.i105, label %for.body70.i, !llvm.loop !7

for.cond66.preheader.i105:                        ; preds = %for.body70.i
  %add113.i.lcssa = phi i32 [ %add113.i, %for.body70.i ]
  %arrayidx75.i106 = getelementptr inbounds nuw i8, ptr %i1, i64 16
  %arrayidx88.i107 = getelementptr inbounds nuw i8, ptr %i1, i64 32
  %arrayidx91.i108 = getelementptr inbounds nuw i8, ptr %i1, i64 48
  br label %for.body70.i109

for.body70.i109:                                  ; preds = %for.body70.i109, %for.cond66.preheader.i105
  %indvars.iv190.i110 = phi i64 [ 0, %for.cond66.preheader.i105 ], [ %indvars.iv.next191.i148, %for.body70.i109 ]
  %sum.0187.i111 = phi i32 [ 0, %for.cond66.preheader.i105 ], [ %add113.i147, %for.body70.i109 ]
  %arrayidx74.i112 = getelementptr inbounds nuw [4 x i32], ptr %i1, i64 0, i64 %indvars.iv190.i110
  %i22 = load i32, ptr %arrayidx74.i112, align 4, !tbaa !3
  %arrayidx77.i113 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx75.i106, i64 0, i64 %indvars.iv190.i110
  %i23 = load i32, ptr %arrayidx77.i113, align 4, !tbaa !3
  %add78.i114 = add i32 %i23, %i22
  %sub86.i115 = sub i32 %i22, %i23
  %arrayidx90.i116 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx88.i107, i64 0, i64 %indvars.iv190.i110
  %i24 = load i32, ptr %arrayidx90.i116, align 4, !tbaa !3
  %arrayidx93.i117 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx91.i108, i64 0, i64 %indvars.iv190.i110
  %i25 = load i32, ptr %arrayidx93.i117, align 4, !tbaa !3
  %add94.i118 = add i32 %i25, %i24
  %sub102.i119 = sub i32 %i24, %i25
  %add103.i120 = add nsw i32 %add94.i118, %add78.i114
  %sub104.i121 = sub nsw i32 %add78.i114, %add94.i118
  %add105.i122 = add nsw i32 %sub102.i119, %sub86.i115
  %sub106.i123 = sub nsw i32 %sub86.i115, %sub102.i119
  %shr.i.i124 = lshr i32 %add103.i120, 15
  %and.i.i125 = and i32 %shr.i.i124, 65537
  %mul.i.i126 = mul nuw i32 %and.i.i125, 65535
  %add.i.i127 = add i32 %mul.i.i126, %add103.i120
  %xor.i.i128 = xor i32 %add.i.i127, %mul.i.i126
  %shr.i169.i129 = lshr i32 %add105.i122, 15
  %and.i170.i130 = and i32 %shr.i169.i129, 65537
  %mul.i171.i131 = mul nuw i32 %and.i170.i130, 65535
  %add.i172.i132 = add i32 %mul.i171.i131, %add105.i122
  %xor.i173.i133 = xor i32 %add.i172.i132, %mul.i171.i131
  %shr.i174.i134 = lshr i32 %sub104.i121, 15
  %and.i175.i135 = and i32 %shr.i174.i134, 65537
  %mul.i176.i136 = mul nuw i32 %and.i175.i135, 65535
  %add.i177.i137 = add i32 %mul.i176.i136, %sub104.i121
  %xor.i178.i138 = xor i32 %add.i177.i137, %mul.i176.i136
  %shr.i179.i139 = lshr i32 %sub106.i123, 15
  %and.i180.i140 = and i32 %shr.i179.i139, 65537
  %mul.i181.i141 = mul nuw i32 %and.i180.i140, 65535
  %add.i182.i142 = add i32 %mul.i181.i141, %sub106.i123
  %xor.i183.i143 = xor i32 %add.i182.i142, %mul.i181.i141
  %add108.i144 = add i32 %xor.i173.i133, %sum.0187.i111
  %add110.i145 = add i32 %add108.i144, %xor.i.i128
  %add112.i146 = add i32 %add110.i145, %xor.i178.i138
  %add113.i147 = add i32 %add112.i146, %xor.i183.i143
  %indvars.iv.next191.i148 = add nuw nsw i64 %indvars.iv190.i110, 1
  %exitcond193.not.i149 = icmp eq i64 %indvars.iv.next191.i148, 4
  br i1 %exitcond193.not.i149, label %x264_pixel_satd_8x4.exit154, label %for.body70.i109, !llvm.loop !7

x264_pixel_satd_8x4.exit154:                      ; preds = %for.body70.i109
  %add113.i147.lcssa = phi i32 [ %add113.i147, %for.body70.i109 ]
  call void @llvm.lifetime.end.p0(i64 128, ptr nonnull %tmp.i) #1
  %add.ptr5 = getelementptr inbounds nuw i8, ptr %pix1, i64 8
  %add.ptr6 = getelementptr inbounds nuw i8, ptr %pix2, i64 8
  call void @llvm.lifetime.start.p0(i64 128, ptr nonnull %tmp.i155) #1
  %add.ptr11 = getelementptr inbounds i8, ptr %add.ptr5, i64 %idx.ext
  %add.ptr15 = getelementptr inbounds i8, ptr %add.ptr6, i64 %idx.ext2
  br label %for.body.i158

for.cond66.preheader.i224:                        ; preds = %for.body.i158
  %arrayidx75.i225 = getelementptr inbounds nuw i8, ptr %tmp.i155, i64 16
  %arrayidx88.i226 = getelementptr inbounds nuw i8, ptr %tmp.i155, i64 32
  %arrayidx91.i227 = getelementptr inbounds nuw i8, ptr %tmp.i155, i64 48
  br label %for.body70.i228

for.body.i158:                                    ; preds = %for.body.i158, %x264_pixel_satd_8x4.exit154
  %indvars.iv.i159 = phi i64 [ 0, %x264_pixel_satd_8x4.exit154 ], [ %indvars.iv.next.i220, %for.body.i158 ]
  %pix1.addr.0186.i160 = phi ptr [ %add.ptr5, %x264_pixel_satd_8x4.exit154 ], [ %add.ptr.i221, %for.body.i158 ]
  %pix2.addr.0185.i161 = phi ptr [ %add.ptr6, %x264_pixel_satd_8x4.exit154 ], [ %add.ptr64.i222, %for.body.i158 ]
  %i26 = load i8, ptr %pix1.addr.0186.i160, align 1, !tbaa !0
  %conv.i162 = zext i8 %i26 to i32
  %i27 = load i8, ptr %pix2.addr.0185.i161, align 1, !tbaa !0
  %conv2.i163 = zext i8 %i27 to i32
  %sub.i164 = sub nsw i32 %conv.i162, %conv2.i163
  %arrayidx3.i165 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 4
  %i28 = load i8, ptr %arrayidx3.i165, align 1, !tbaa !0
  %conv4.i166 = zext i8 %i28 to i32
  %arrayidx5.i167 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 4
  %i29 = load i8, ptr %arrayidx5.i167, align 1, !tbaa !0
  %conv6.i168 = zext i8 %i29 to i32
  %sub7.i169 = sub nsw i32 %conv4.i166, %conv6.i168
  %shl.i170 = shl nsw i32 %sub7.i169, 16
  %add.i171 = add nsw i32 %shl.i170, %sub.i164
  %arrayidx8.i172 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 1
  %i30 = load i8, ptr %arrayidx8.i172, align 1, !tbaa !0
  %conv9.i173 = zext i8 %i30 to i32
  %arrayidx10.i174 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 1
  %i31 = load i8, ptr %arrayidx10.i174, align 1, !tbaa !0
  %conv11.i175 = zext i8 %i31 to i32
  %sub12.i176 = sub nsw i32 %conv9.i173, %conv11.i175
  %arrayidx13.i177 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 5
  %i32 = load i8, ptr %arrayidx13.i177, align 1, !tbaa !0
  %conv14.i178 = zext i8 %i32 to i32
  %arrayidx15.i179 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 5
  %i33 = load i8, ptr %arrayidx15.i179, align 1, !tbaa !0
  %conv16.i180 = zext i8 %i33 to i32
  %sub17.i181 = sub nsw i32 %conv14.i178, %conv16.i180
  %shl18.i182 = shl nsw i32 %sub17.i181, 16
  %add19.i183 = add nsw i32 %shl18.i182, %sub12.i176
  %arrayidx20.i184 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 2
  %i34 = load i8, ptr %arrayidx20.i184, align 1, !tbaa !0
  %conv21.i185 = zext i8 %i34 to i32
  %arrayidx22.i186 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 2
  %i35 = load i8, ptr %arrayidx22.i186, align 1, !tbaa !0
  %conv23.i187 = zext i8 %i35 to i32
  %sub24.i188 = sub nsw i32 %conv21.i185, %conv23.i187
  %arrayidx25.i189 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 6
  %i36 = load i8, ptr %arrayidx25.i189, align 1, !tbaa !0
  %conv26.i190 = zext i8 %i36 to i32
  %arrayidx27.i191 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 6
  %i37 = load i8, ptr %arrayidx27.i191, align 1, !tbaa !0
  %conv28.i192 = zext i8 %i37 to i32
  %sub29.i193 = sub nsw i32 %conv26.i190, %conv28.i192
  %shl30.i194 = shl nsw i32 %sub29.i193, 16
  %add31.i195 = add nsw i32 %shl30.i194, %sub24.i188
  %arrayidx32.i196 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 3
  %i38 = load i8, ptr %arrayidx32.i196, align 1, !tbaa !0
  %conv33.i197 = zext i8 %i38 to i32
  %arrayidx34.i198 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 3
  %i39 = load i8, ptr %arrayidx34.i198, align 1, !tbaa !0
  %conv35.i199 = zext i8 %i39 to i32
  %sub36.i200 = sub nsw i32 %conv33.i197, %conv35.i199
  %arrayidx37.i201 = getelementptr inbounds nuw i8, ptr %pix1.addr.0186.i160, i64 7
  %i40 = load i8, ptr %arrayidx37.i201, align 1, !tbaa !0
  %conv38.i202 = zext i8 %i40 to i32
  %arrayidx39.i203 = getelementptr inbounds nuw i8, ptr %pix2.addr.0185.i161, i64 7
  %i41 = load i8, ptr %arrayidx39.i203, align 1, !tbaa !0
  %conv40.i204 = zext i8 %i41 to i32
  %sub41.i205 = sub nsw i32 %conv38.i202, %conv40.i204
  %shl42.i206 = shl nsw i32 %sub41.i205, 16
  %add43.i207 = add nsw i32 %shl42.i206, %sub36.i200
  %add44.i208 = add nsw i32 %add19.i183, %add.i171
  %sub45.i209 = sub nsw i32 %add.i171, %add19.i183
  %add46.i210 = add nsw i32 %add43.i207, %add31.i195
  %sub47.i211 = sub nsw i32 %add31.i195, %add43.i207
  %add48.i212 = add nsw i32 %add46.i210, %add44.i208
  %arrayidx49.i213 = getelementptr inbounds nuw [8 x [4 x i32]], ptr %tmp.i155, i64 0, i64 %indvars.iv.i159
  store i32 %add48.i212, ptr %arrayidx49.i213, align 8, !tbaa !3
  %sub51.i214 = sub nsw i32 %add44.i208, %add46.i210
  %arrayidx54.i215 = getelementptr inbounds nuw i8, ptr %arrayidx49.i213, i64 8
  store i32 %sub51.i214, ptr %arrayidx54.i215, align 8, !tbaa !3
  %add55.i216 = add nsw i32 %sub47.i211, %sub45.i209
  %arrayidx58.i217 = getelementptr inbounds nuw i8, ptr %arrayidx49.i213, i64 4
  store i32 %add55.i216, ptr %arrayidx58.i217, align 4, !tbaa !3
  %sub59.i218 = sub nsw i32 %sub45.i209, %sub47.i211
  %arrayidx62.i219 = getelementptr inbounds nuw i8, ptr %arrayidx49.i213, i64 12
  store i32 %sub59.i218, ptr %arrayidx62.i219, align 4, !tbaa !3
  %indvars.iv.next.i220 = add nuw nsw i64 %indvars.iv.i159, 1
  %add.ptr.i221 = getelementptr inbounds i8, ptr %pix1.addr.0186.i160, i64 %idx.ext.i
  %add.ptr64.i222 = getelementptr inbounds i8, ptr %pix2.addr.0185.i161, i64 %idx.ext63.i
  %exitcond.not.i223 = icmp eq i64 %indvars.iv.next.i220, 8
  br i1 %exitcond.not.i223, label %for.cond66.preheader.i224, label %for.body.i158, !llvm.loop !5

for.body70.i228:                                  ; preds = %for.body70.i228, %for.cond66.preheader.i224
  %indvars.iv190.i229 = phi i64 [ 0, %for.cond66.preheader.i224 ], [ %indvars.iv.next191.i267, %for.body70.i228 ]
  %sum.0187.i230 = phi i32 [ 0, %for.cond66.preheader.i224 ], [ %add113.i266, %for.body70.i228 ]
  %arrayidx74.i231 = getelementptr inbounds nuw [4 x i32], ptr %tmp.i155, i64 0, i64 %indvars.iv190.i229
  %i42 = load i32, ptr %arrayidx74.i231, align 4, !tbaa !3
  %arrayidx77.i232 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx75.i225, i64 0, i64 %indvars.iv190.i229
  %i43 = load i32, ptr %arrayidx77.i232, align 4, !tbaa !3
  %add78.i233 = add i32 %i43, %i42
  %sub86.i234 = sub i32 %i42, %i43
  %arrayidx90.i235 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx88.i226, i64 0, i64 %indvars.iv190.i229
  %i44 = load i32, ptr %arrayidx90.i235, align 4, !tbaa !3
  %arrayidx93.i236 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx91.i227, i64 0, i64 %indvars.iv190.i229
  %i45 = load i32, ptr %arrayidx93.i236, align 4, !tbaa !3
  %add94.i237 = add i32 %i45, %i44
  %sub102.i238 = sub i32 %i44, %i45
  %add103.i239 = add nsw i32 %add94.i237, %add78.i233
  %sub104.i240 = sub nsw i32 %add78.i233, %add94.i237
  %add105.i241 = add nsw i32 %sub102.i238, %sub86.i234
  %sub106.i242 = sub nsw i32 %sub86.i234, %sub102.i238
  %shr.i.i243 = lshr i32 %add103.i239, 15
  %and.i.i244 = and i32 %shr.i.i243, 65537
  %mul.i.i245 = mul nuw i32 %and.i.i244, 65535
  %add.i.i246 = add i32 %mul.i.i245, %add103.i239
  %xor.i.i247 = xor i32 %add.i.i246, %mul.i.i245
  %shr.i169.i248 = lshr i32 %add105.i241, 15
  %and.i170.i249 = and i32 %shr.i169.i248, 65537
  %mul.i171.i250 = mul nuw i32 %and.i170.i249, 65535
  %add.i172.i251 = add i32 %mul.i171.i250, %add105.i241
  %xor.i173.i252 = xor i32 %add.i172.i251, %mul.i171.i250
  %shr.i174.i253 = lshr i32 %sub104.i240, 15
  %and.i175.i254 = and i32 %shr.i174.i253, 65537
  %mul.i176.i255 = mul nuw i32 %and.i175.i254, 65535
  %add.i177.i256 = add i32 %mul.i176.i255, %sub104.i240
  %xor.i178.i257 = xor i32 %add.i177.i256, %mul.i176.i255
  %shr.i179.i258 = lshr i32 %sub106.i242, 15
  %and.i180.i259 = and i32 %shr.i179.i258, 65537
  %mul.i181.i260 = mul nuw i32 %and.i180.i259, 65535
  %add.i182.i261 = add i32 %mul.i181.i260, %sub106.i242
  %xor.i183.i262 = xor i32 %add.i182.i261, %mul.i181.i260
  %add108.i263 = add i32 %xor.i173.i252, %sum.0187.i230
  %add110.i264 = add i32 %add108.i263, %xor.i.i247
  %add112.i265 = add i32 %add110.i264, %xor.i178.i257
  %add113.i266 = add i32 %add112.i265, %xor.i183.i262
  %indvars.iv.next191.i267 = add nuw nsw i64 %indvars.iv190.i229, 1
  %exitcond193.not.i268 = icmp eq i64 %indvars.iv.next191.i267, 4
  br i1 %exitcond193.not.i268, label %for.cond66.preheader.i343, label %for.body70.i228, !llvm.loop !7

for.cond66.preheader.i343:                        ; preds = %for.body70.i228
  %add113.i266.lcssa = phi i32 [ %add113.i266, %for.body70.i228 ]
  %arrayidx75.i344 = getelementptr inbounds nuw i8, ptr %i, i64 16
  %arrayidx88.i345 = getelementptr inbounds nuw i8, ptr %i, i64 32
  %arrayidx91.i346 = getelementptr inbounds nuw i8, ptr %i, i64 48
  br label %for.body70.i347

for.body70.i347:                                  ; preds = %for.body70.i347, %for.cond66.preheader.i343
  %indvars.iv190.i348 = phi i64 [ 0, %for.cond66.preheader.i343 ], [ %indvars.iv.next191.i386, %for.body70.i347 ]
  %sum.0187.i349 = phi i32 [ 0, %for.cond66.preheader.i343 ], [ %add113.i385, %for.body70.i347 ]
  %arrayidx74.i350 = getelementptr inbounds nuw [4 x i32], ptr %i, i64 0, i64 %indvars.iv190.i348
  %i46 = load i32, ptr %arrayidx74.i350, align 4, !tbaa !3
  %arrayidx77.i351 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx75.i344, i64 0, i64 %indvars.iv190.i348
  %i47 = load i32, ptr %arrayidx77.i351, align 4, !tbaa !3
  %add78.i352 = add i32 %i47, %i46
  %sub86.i353 = sub i32 %i46, %i47
  %arrayidx90.i354 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx88.i345, i64 0, i64 %indvars.iv190.i348
  %i48 = load i32, ptr %arrayidx90.i354, align 4, !tbaa !3
  %arrayidx93.i355 = getelementptr inbounds nuw [4 x i32], ptr %arrayidx91.i346, i64 0, i64 %indvars.iv190.i348
  %i49 = load i32, ptr %arrayidx93.i355, align 4, !tbaa !3
  %add94.i356 = add i32 %i49, %i48
  %sub102.i357 = sub i32 %i48, %i49
  %add103.i358 = add nsw i32 %add94.i356, %add78.i352
  %sub104.i359 = sub nsw i32 %add78.i352, %add94.i356
  %add105.i360 = add nsw i32 %sub102.i357, %sub86.i353
  %sub106.i361 = sub nsw i32 %sub86.i353, %sub102.i357
  %shr.i.i362 = lshr i32 %add103.i358, 15
  %and.i.i363 = and i32 %shr.i.i362, 65537
  %mul.i.i364 = mul nuw i32 %and.i.i363, 65535
  %add.i.i365 = add i32 %mul.i.i364, %add103.i358
  %xor.i.i366 = xor i32 %add.i.i365, %mul.i.i364
  %shr.i169.i367 = lshr i32 %add105.i360, 15
  %and.i170.i368 = and i32 %shr.i169.i367, 65537
  %mul.i171.i369 = mul nuw i32 %and.i170.i368, 65535
  %add.i172.i370 = add i32 %mul.i171.i369, %add105.i360
  %xor.i173.i371 = xor i32 %add.i172.i370, %mul.i171.i369
  %shr.i174.i372 = lshr i32 %sub104.i359, 15
  %and.i175.i373 = and i32 %shr.i174.i372, 65537
  %mul.i176.i374 = mul nuw i32 %and.i175.i373, 65535
  %add.i177.i375 = add i32 %mul.i176.i374, %sub104.i359
  %xor.i178.i376 = xor i32 %add.i177.i375, %mul.i176.i374
  %shr.i179.i377 = lshr i32 %sub106.i361, 15
  %and.i180.i378 = and i32 %shr.i179.i377, 65537
  %mul.i181.i379 = mul nuw i32 %and.i180.i378, 65535
  %add.i182.i380 = add i32 %mul.i181.i379, %sub106.i361
  %xor.i183.i381 = xor i32 %add.i182.i380, %mul.i181.i379
  %add108.i382 = add i32 %xor.i173.i371, %sum.0187.i349
  %add110.i383 = add i32 %add108.i382, %xor.i.i366
  %add112.i384 = add i32 %add110.i383, %xor.i178.i376
  %add113.i385 = add i32 %add112.i384, %xor.i183.i381
  %indvars.iv.next191.i386 = add nuw nsw i64 %indvars.iv190.i348, 1
  %exitcond193.not.i387 = icmp eq i64 %indvars.iv.next191.i386, 4
  br i1 %exitcond193.not.i387, label %x264_pixel_satd_8x4.exit392, label %for.body70.i347, !llvm.loop !7

x264_pixel_satd_8x4.exit392:                      ; preds = %for.body70.i347
  %add113.i385.lcssa = phi i32 [ %add113.i385, %for.body70.i347 ]
  %conv118.i269 = and i32 %add113.i266.lcssa, 65535
  %shr.i270 = lshr i32 %add113.i266.lcssa, 16
  %add119.i271 = add nuw nsw i32 %conv118.i269, %shr.i270
  %shr120.i272 = lshr i32 %add119.i271, 1
  %conv118.i = and i32 %add113.i.lcssa, 65535
  %shr.i = lshr i32 %add113.i.lcssa, 16
  %add119.i = add nuw nsw i32 %conv118.i, %shr.i
  %shr120.i = lshr i32 %add119.i, 1
  %conv118.i150 = and i32 %add113.i147.lcssa, 65535
  %shr.i151 = lshr i32 %add113.i147.lcssa, 16
  %add119.i152 = add nuw nsw i32 %conv118.i150, %shr.i151
  %shr120.i153 = lshr i32 %add119.i152, 1
  %conv118.i388 = and i32 %add113.i385.lcssa, 65535
  %shr.i389 = lshr i32 %add113.i385.lcssa, 16
  %add119.i390 = add nuw nsw i32 %conv118.i388, %shr.i389
  %shr120.i391 = lshr i32 %add119.i390, 1
  call void @llvm.lifetime.end.p0(i64 128, ptr nonnull %tmp.i155) #1
  %add17 = add nuw nsw i32 %shr120.i153, %shr120.i
  %add = add nuw nsw i32 %add17, %shr120.i272
  %add18 = add nuw nsw i32 %add, %shr120.i391
  ret i32 %add18
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture) #0

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture) #0

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #1 = { nounwind }

!0 = !{!1, !1, i64 0}
!1 = !{!"omnipotent char", !2, i64 0}
!2 = !{!"Simple C/C++ TBAA"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !1, i64 0}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.mustprogress"}
!7 = distinct !{!7, !6}

;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"omnipotent char", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
; CHECK: [[META4]] = !{!"int", [[META1]], i64 0}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META6]]}
;.
