# The LLVM Version number information

if(NOT DEFINED LLVM_VERSION_MAJOR)
<<<<<<< HEAD
  set(LLVM_VERSION_MAJOR 18) # SIFIVE
||||||| 266a5a9cb9da
  set(LLVM_VERSION_MAJOR 19)
=======
  set(LLVM_VERSION_MAJOR 20)
>>>>>>> 721aa5db
endif()
if(NOT DEFINED LLVM_VERSION_MINOR)
  set(LLVM_VERSION_MINOR 9) # SIFIVE
endif()
if(NOT DEFINED LLVM_VERSION_PATCH)
  set(LLVM_VERSION_PATCH 155) # SIFIVE Weekly Build ID
endif()
if(NOT DEFINED LLVM_VERSION_SUFFIX)
  set(LLVM_VERSION_SUFFIX git)
endif()

