; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -S -loop-concat-canonicalize -passes=loop-simplify,loop-rotate,loop-concat | FileCheck %s

; Function Attrs: nounwind uwtable vscale_range(2,2)
define dso_local signext range(i32 0, 98304) i32 @x264_pixel_satd_8x8(ptr nocapture noundef readonly %pix1, i32 noundef signext %i_pix1, ptr nocapture noundef readonly %pix2, i32 noundef signext %i_pix2) {
; CHECK-LABEL: define dso_local signext range(i32 0, 98304) i32 @x264_pixel_satd_8x8(
; CHECK-SAME: ptr noundef readonly captures(none) [[PIX1:%.*]], i32 noundef signext [[I_PIX1:%.*]], ptr noundef readonly captures(none) [[PIX2:%.*]], i32 noundef signext [[I_PIX2:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMPA:%.*]] = alloca [8 x [4 x i32]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 64
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 128, ptr nonnull [[TMPA]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT63:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    [[IDX_EXT201:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT203:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond66.preheader:
; CHECK-NEXT:    [[ADD_PTR_LCSSA:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ADD_PTR64_LCSSA:%.*]] = phi ptr [ [[ADD_PTR64:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX75:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 16
; CHECK-NEXT:    [[ARRAYIDX88:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 32
; CHECK-NEXT:    [[ARRAYIDX91:%.*]] = getelementptr inbounds i8, ptr [[TMPA]], i64 48
; CHECK-NEXT:    br label [[FOR_BODY70:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX1_ADDR_0144:%.*]] = phi ptr [ [[PIX1]], [[ENTRY]] ], [ [[ADD_PTR]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX2_ADDR_0143:%.*]] = phi ptr [ [[PIX2]], [[ENTRY]] ], [ [[ADD_PTR64]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[PIX1_ADDR_0144]], align 1, !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[PIX2_ADDR_0143]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV2:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[CONV]], [[CONV2]]
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX3]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV4:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    [[ARRAYIDX5:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[ARRAYIDX5]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV6:%.*]] = zext i8 [[TMP4]] to i32
; CHECK-NEXT:    [[SUB7:%.*]] = sub nsw i32 [[CONV4]], [[CONV6]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nsw i32 [[SUB7]], 16
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[SHL]], [[SUB]]
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 1
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[ARRAYIDX8]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV9:%.*]] = zext i8 [[TMP5]] to i32
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 1
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[ARRAYIDX10]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV11:%.*]] = zext i8 [[TMP6]] to i32
; CHECK-NEXT:    [[SUB12:%.*]] = sub nsw i32 [[CONV9]], [[CONV11]]
; CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 5
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[ARRAYIDX13]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV14:%.*]] = zext i8 [[TMP7]] to i32
; CHECK-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 5
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[ARRAYIDX15]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV16:%.*]] = zext i8 [[TMP8]] to i32
; CHECK-NEXT:    [[SUB17:%.*]] = sub nsw i32 [[CONV14]], [[CONV16]]
; CHECK-NEXT:    [[SHL18:%.*]] = shl nsw i32 [[SUB17]], 16
; CHECK-NEXT:    [[ADD19:%.*]] = add nsw i32 [[SHL18]], [[SUB12]]
; CHECK-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 2
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[ARRAYIDX20]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV21:%.*]] = zext i8 [[TMP9]] to i32
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i8, ptr [[ARRAYIDX22]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV23:%.*]] = zext i8 [[TMP10]] to i32
; CHECK-NEXT:    [[SUB24:%.*]] = sub nsw i32 [[CONV21]], [[CONV23]]
; CHECK-NEXT:    [[ARRAYIDX25:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[ARRAYIDX25]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV26:%.*]] = zext i8 [[TMP11]] to i32
; CHECK-NEXT:    [[ARRAYIDX27:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 6
; CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX27]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV28:%.*]] = zext i8 [[TMP12]] to i32
; CHECK-NEXT:    [[SUB29:%.*]] = sub nsw i32 [[CONV26]], [[CONV28]]
; CHECK-NEXT:    [[SHL30:%.*]] = shl nsw i32 [[SUB29]], 16
; CHECK-NEXT:    [[ADD31:%.*]] = add nsw i32 [[SHL30]], [[SUB24]]
; CHECK-NEXT:    [[ARRAYIDX32:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 3
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[ARRAYIDX32]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV33:%.*]] = zext i8 [[TMP13]] to i32
; CHECK-NEXT:    [[ARRAYIDX34:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 3
; CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[ARRAYIDX34]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV35:%.*]] = zext i8 [[TMP14]] to i32
; CHECK-NEXT:    [[SUB36:%.*]] = sub nsw i32 [[CONV33]], [[CONV35]]
; CHECK-NEXT:    [[ARRAYIDX37:%.*]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 7
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[ARRAYIDX37]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV38:%.*]] = zext i8 [[TMP15]] to i32
; CHECK-NEXT:    [[ARRAYIDX39:%.*]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 7
; CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX39]], align 1, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[CONV40:%.*]] = zext i8 [[TMP16]] to i32
; CHECK-NEXT:    [[SUB41:%.*]] = sub nsw i32 [[CONV38]], [[CONV40]]
; CHECK-NEXT:    [[SHL42:%.*]] = shl nsw i32 [[SUB41]], 16
; CHECK-NEXT:    [[ADD43:%.*]] = add nsw i32 [[SHL42]], [[SUB36]]
; CHECK-NEXT:    [[ADD44:%.*]] = add nsw i32 [[ADD19]], [[ADD]]
; CHECK-NEXT:    [[SUB45:%.*]] = sub nsw i32 [[ADD]], [[ADD19]]
; CHECK-NEXT:    [[ADD46:%.*]] = add nsw i32 [[ADD43]], [[ADD31]]
; CHECK-NEXT:    [[SUB47:%.*]] = sub nsw i32 [[ADD31]], [[ADD43]]
; CHECK-NEXT:    [[ADD48:%.*]] = add nsw i32 [[ADD46]], [[ADD44]]
; CHECK-NEXT:    [[ARRAYIDX49:%.*]] = getelementptr inbounds [8 x [4 x i32]], ptr [[TMPA]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[ADD48]], ptr [[ARRAYIDX49]], align 8, !tbaa [[TBAA3:![0-9]+]]
; CHECK-NEXT:    [[SUB51:%.*]] = sub nsw i32 [[ADD44]], [[ADD46]]
; CHECK-NEXT:    [[ARRAYIDX54:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49]], i64 8
; CHECK-NEXT:    store i32 [[SUB51]], ptr [[ARRAYIDX54]], align 8, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD55:%.*]] = add nsw i32 [[SUB47]], [[SUB45]]
; CHECK-NEXT:    [[ARRAYIDX58:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49]], i64 4
; CHECK-NEXT:    store i32 [[ADD55]], ptr [[ARRAYIDX58]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[SUB59:%.*]] = sub nsw i32 [[SUB45]], [[SUB47]]
; CHECK-NEXT:    [[ARRAYIDX62:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX49]], i64 12
; CHECK-NEXT:    store i32 [[SUB59]], ptr [[ARRAYIDX62]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[PIX1_ADDR_0144]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR64]] = getelementptr inbounds i8, ptr [[PIX2_ADDR_0143]], i64 [[IDX_EXT63]]
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT]], 8
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_BODY]], label [[FOR_COND66_PREHEADER:%.*]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       for.cond122.preheader:
; CHECK-NEXT:    br label [[FOR_COND207_PREHEADER:%.*]]
; CHECK:       for.body70:
; CHECK-NEXT:    [[INDVARS_IV153:%.*]] = phi i64 [ 0, [[FOR_COND66_PREHEADER]] ], [ [[INDVARS_IV_NEXT154:%.*]], [[FOR_BODY70]] ]
; CHECK-NEXT:    [[SUM0_0146:%.*]] = phi i32 [ 0, [[FOR_COND66_PREHEADER]] ], [ [[ADD113:%.*]], [[FOR_BODY70]] ]
; CHECK-NEXT:    [[ARRAYIDX74:%.*]] = getelementptr inbounds [4 x i32], ptr [[TMPA]], i64 0, i64 [[INDVARS_IV153]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[ARRAYIDX74]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX77:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX75]], i64 0, i64 [[INDVARS_IV153]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[ARRAYIDX77]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD78:%.*]] = add i32 [[TMP18]], [[TMP17]]
; CHECK-NEXT:    [[SUB86:%.*]] = sub i32 [[TMP17]], [[TMP18]]
; CHECK-NEXT:    [[ARRAYIDX90:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX88]], i64 0, i64 [[INDVARS_IV153]]
; CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[ARRAYIDX90]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX93:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX91]], i64 0, i64 [[INDVARS_IV153]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[ARRAYIDX93]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD94:%.*]] = add i32 [[TMP20]], [[TMP19]]
; CHECK-NEXT:    [[SUB102:%.*]] = sub i32 [[TMP19]], [[TMP20]]
; CHECK-NEXT:    [[ADD103:%.*]] = add nsw i32 [[ADD94]], [[ADD78]]
; CHECK-NEXT:    [[SUB104:%.*]] = sub nsw i32 [[ADD78]], [[ADD94]]
; CHECK-NEXT:    [[ADD105:%.*]] = add nsw i32 [[SUB102]], [[SUB86]]
; CHECK-NEXT:    [[SUB106:%.*]] = sub nsw i32 [[SUB86]], [[SUB102]]
; CHECK-NEXT:    [[SHR_I:%.*]] = lshr i32 [[ADD103]], 15
; CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SHR_I]], 65537
; CHECK-NEXT:    [[MUL_I:%.*]] = mul nuw i32 [[AND_I]], 65535
; CHECK-NEXT:    [[ADD_I:%.*]] = add i32 [[MUL_I]], [[ADD103]]
; CHECK-NEXT:    [[XOR_I:%.*]] = xor i32 [[ADD_I]], [[MUL_I]]
; CHECK-NEXT:    [[SHR_I107:%.*]] = lshr i32 [[ADD105]], 15
; CHECK-NEXT:    [[AND_I108:%.*]] = and i32 [[SHR_I107]], 65537
; CHECK-NEXT:    [[MUL_I109:%.*]] = mul nuw i32 [[AND_I108]], 65535
; CHECK-NEXT:    [[ADD_I110:%.*]] = add i32 [[MUL_I109]], [[ADD105]]
; CHECK-NEXT:    [[XOR_I111:%.*]] = xor i32 [[ADD_I110]], [[MUL_I109]]
; CHECK-NEXT:    [[SHR_I112:%.*]] = lshr i32 [[SUB104]], 15
; CHECK-NEXT:    [[AND_I113:%.*]] = and i32 [[SHR_I112]], 65537
; CHECK-NEXT:    [[MUL_I114:%.*]] = mul nuw i32 [[AND_I113]], 65535
; CHECK-NEXT:    [[ADD_I115:%.*]] = add i32 [[MUL_I114]], [[SUB104]]
; CHECK-NEXT:    [[XOR_I116:%.*]] = xor i32 [[ADD_I115]], [[MUL_I114]]
; CHECK-NEXT:    [[SHR_I117:%.*]] = lshr i32 [[SUB106]], 15
; CHECK-NEXT:    [[AND_I118:%.*]] = and i32 [[SHR_I117]], 65537
; CHECK-NEXT:    [[MUL_I119:%.*]] = mul nuw i32 [[AND_I118]], 65535
; CHECK-NEXT:    [[ADD_I120:%.*]] = add i32 [[MUL_I119]], [[SUB106]]
; CHECK-NEXT:    [[XOR_I121:%.*]] = xor i32 [[ADD_I120]], [[MUL_I119]]
; CHECK-NEXT:    [[ADD108:%.*]] = add i32 [[XOR_I111]], [[SUM0_0146]]
; CHECK-NEXT:    [[ADD110:%.*]] = add i32 [[ADD108]], [[XOR_I]]
; CHECK-NEXT:    [[ADD112:%.*]] = add i32 [[ADD110]], [[XOR_I116]]
; CHECK-NEXT:    [[ADD113]] = add i32 [[ADD112]], [[XOR_I121]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT154]] = add nuw nsw i64 [[INDVARS_IV153]], 1
; CHECK-NEXT:    [[EXITCOND156:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT154]], 4
; CHECK-NEXT:    br i1 [[EXITCOND156]], label [[FOR_BODY70]], label [[FOR_COND122_PREHEADER:%.*]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       for.cond207.preheader:
; CHECK-NEXT:    [[ADD113_LCSSA:%.*]] = phi i32 [ [[ADD113]], [[FOR_COND122_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX216:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 16
; CHECK-NEXT:    [[ARRAYIDX229:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 32
; CHECK-NEXT:    [[ARRAYIDX232:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 48
; CHECK-NEXT:    br label [[FOR_BODY211:%.*]]
; CHECK:       for.cond.cleanup210:
; CHECK-NEXT:    [[ADD255_LCSSA:%.*]] = phi i32 [ [[ADD255:%.*]], [[FOR_BODY211]] ]
; CHECK-NEXT:    [[CONV118:%.*]] = and i32 [[ADD113_LCSSA]], 65535
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[ADD113_LCSSA]], 16
; CHECK-NEXT:    [[ADD119:%.*]] = add nuw nsw i32 [[CONV118]], [[SHR]]
; CHECK-NEXT:    [[SHR120:%.*]] = lshr i32 [[ADD119]], 1
; CHECK-NEXT:    [[CONV260:%.*]] = and i32 [[ADD255_LCSSA]], 65535
; CHECK-NEXT:    [[CMP261:%.*]] = icmp ugt i32 [[ADD255_LCSSA]], 16
; CHECK-NEXT:    [[CONV262:%.*]] = zext i1 [[CMP261]] to i32
; CHECK-NEXT:    [[ADD263:%.*]] = add nuw nsw i32 [[CONV260]], [[CONV262]]
; CHECK-NEXT:    [[SHR264:%.*]] = lshr i32 [[ADD263]], 1
; CHECK-NEXT:    [[ADD265:%.*]] = add nuw nsw i32 [[SHR264]], [[SHR120]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 128, ptr nonnull [[TMPA]]) #[[ATTR1]]
; CHECK-NEXT:    ret i32 [[ADD265]]
; CHECK:       for.body211:
; CHECK-NEXT:    [[INDVARS_IV161:%.*]] = phi i64 [ 0, [[FOR_COND207_PREHEADER]] ], [ [[INDVARS_IV_NEXT162:%.*]], [[FOR_BODY211]] ]
; CHECK-NEXT:    [[SUM1_0150:%.*]] = phi i32 [ 0, [[FOR_COND207_PREHEADER]] ], [ [[ADD255]], [[FOR_BODY211]] ]
; CHECK-NEXT:    [[ARRAYIDX215:%.*]] = getelementptr inbounds [4 x i32], ptr [[TMP0]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[ARRAYIDX215]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX218:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX216]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP22:%.*]] = load i32, ptr [[ARRAYIDX218]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD219:%.*]] = add i32 [[TMP22]], [[TMP21]]
; CHECK-NEXT:    [[SUB227:%.*]] = sub i32 [[TMP21]], [[TMP22]]
; CHECK-NEXT:    [[ARRAYIDX231:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX229]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[ARRAYIDX231]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ARRAYIDX234:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX232]], i64 0, i64 [[INDVARS_IV161]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i32, ptr [[ARRAYIDX234]], align 4, !tbaa [[TBAA3]]
; CHECK-NEXT:    [[ADD235:%.*]] = add i32 [[TMP24]], [[TMP23]]
; CHECK-NEXT:    [[SUB243:%.*]] = sub i32 [[TMP23]], [[TMP24]]
; CHECK-NEXT:    [[ADD244:%.*]] = add nsw i32 [[ADD235]], [[ADD219]]
; CHECK-NEXT:    [[SUB245:%.*]] = sub nsw i32 [[ADD219]], [[ADD235]]
; CHECK-NEXT:    [[ADD246:%.*]] = add nsw i32 [[SUB243]], [[SUB227]]
; CHECK-NEXT:    [[SUB247:%.*]] = sub nsw i32 [[SUB227]], [[SUB243]]
; CHECK-NEXT:    [[SHR_I122:%.*]] = lshr i32 [[ADD244]], 15
; CHECK-NEXT:    [[AND_I123:%.*]] = and i32 [[SHR_I122]], 65537
; CHECK-NEXT:    [[MUL_I124:%.*]] = mul nuw i32 [[AND_I123]], 65535
; CHECK-NEXT:    [[ADD_I125:%.*]] = add i32 [[MUL_I124]], [[ADD244]]
; CHECK-NEXT:    [[XOR_I126:%.*]] = xor i32 [[ADD_I125]], [[MUL_I124]]
; CHECK-NEXT:    [[SHR_I127:%.*]] = lshr i32 [[ADD246]], 15
; CHECK-NEXT:    [[AND_I128:%.*]] = and i32 [[SHR_I127]], 65537
; CHECK-NEXT:    [[MUL_I129:%.*]] = mul nuw i32 [[AND_I128]], 65535
; CHECK-NEXT:    [[ADD_I130:%.*]] = add i32 [[MUL_I129]], [[ADD246]]
; CHECK-NEXT:    [[XOR_I131:%.*]] = xor i32 [[ADD_I130]], [[MUL_I129]]
; CHECK-NEXT:    [[SHR_I132:%.*]] = lshr i32 [[SUB245]], 15
; CHECK-NEXT:    [[AND_I133:%.*]] = and i32 [[SHR_I132]], 65537
; CHECK-NEXT:    [[MUL_I134:%.*]] = mul nuw i32 [[AND_I133]], 65535
; CHECK-NEXT:    [[ADD_I135:%.*]] = add i32 [[MUL_I134]], [[SUB245]]
; CHECK-NEXT:    [[XOR_I136:%.*]] = xor i32 [[ADD_I135]], [[MUL_I134]]
; CHECK-NEXT:    [[SHR_I137:%.*]] = lshr i32 [[SUB247]], 15
; CHECK-NEXT:    [[AND_I138:%.*]] = and i32 [[SHR_I137]], 65537
; CHECK-NEXT:    [[MUL_I139:%.*]] = mul nuw i32 [[AND_I138]], 65535
; CHECK-NEXT:    [[ADD_I140:%.*]] = add i32 [[MUL_I139]], [[SUB247]]
; CHECK-NEXT:    [[XOR_I141:%.*]] = xor i32 [[ADD_I140]], [[MUL_I139]]
; CHECK-NEXT:    [[ADD250:%.*]] = add i32 [[XOR_I131]], [[SUM1_0150]]
; CHECK-NEXT:    [[ADD252:%.*]] = add i32 [[ADD250]], [[XOR_I126]]
; CHECK-NEXT:    [[ADD254:%.*]] = add i32 [[ADD252]], [[XOR_I136]]
; CHECK-NEXT:    [[ADD255]] = add i32 [[ADD254]], [[XOR_I141]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT162]] = add nuw nsw i64 [[INDVARS_IV161]], 1
; CHECK-NEXT:    [[EXITCOND164:%.*]] = icmp ne i64 [[INDVARS_IV_NEXT162]], 4
; CHECK-NEXT:    br i1 [[EXITCOND164]], label [[FOR_BODY211]], label [[FOR_COND_CLEANUP210:%.*]], !llvm.loop [[LOOP8:![0-9]+]]
;
entry:
  %tmpa = alloca [4 x [4 x i32]], align 8
  %tmpb = alloca [4 x [4 x i32]], align 8
  call void @llvm.lifetime.start.p0(i64 64, ptr nonnull %tmpa) #2
  call void @llvm.lifetime.start.p0(i64 64, ptr nonnull %tmpb) #2
  %idx.ext = sext i32 %i_pix1 to i64
  %idx.ext63 = sext i32 %i_pix2 to i64
  br label %for.body

for.cond66.preheader:                             ; preds = %for.body
  %add.ptr.lcssa = phi ptr [ %add.ptr, %for.body ]
  %add.ptr64.lcssa = phi ptr [ %add.ptr64, %for.body ]
  %arrayidx75 = getelementptr inbounds i8, ptr %tmpa, i64 16
  %arrayidx88 = getelementptr inbounds i8, ptr %tmpa, i64 32
  %arrayidx91 = getelementptr inbounds i8, ptr %tmpa, i64 48
  br label %for.body70

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %pix1.addr.0144 = phi ptr [ %pix1, %entry ], [ %add.ptr, %for.body ]
  %pix2.addr.0143 = phi ptr [ %pix2, %entry ], [ %add.ptr64, %for.body ]
  %0 = load i8, ptr %pix1.addr.0144, align 1, !tbaa !11
  %conv = zext i8 %0 to i32
  %1 = load i8, ptr %pix2.addr.0143, align 1, !tbaa !11
  %conv2 = zext i8 %1 to i32
  %sub = sub nsw i32 %conv, %conv2
  %arrayidx3 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 4
  %2 = load i8, ptr %arrayidx3, align 1, !tbaa !11
  %conv4 = zext i8 %2 to i32
  %arrayidx5 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 4
  %3 = load i8, ptr %arrayidx5, align 1, !tbaa !11
  %conv6 = zext i8 %3 to i32
  %sub7 = sub nsw i32 %conv4, %conv6
  %shl = shl nsw i32 %sub7, 16
  %add = add nsw i32 %shl, %sub
  %arrayidx8 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 1
  %4 = load i8, ptr %arrayidx8, align 1, !tbaa !11
  %conv9 = zext i8 %4 to i32
  %arrayidx10 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 1
  %5 = load i8, ptr %arrayidx10, align 1, !tbaa !11
  %conv11 = zext i8 %5 to i32
  %sub12 = sub nsw i32 %conv9, %conv11
  %arrayidx13 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 5
  %6 = load i8, ptr %arrayidx13, align 1, !tbaa !11
  %conv14 = zext i8 %6 to i32
  %arrayidx15 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 5
  %7 = load i8, ptr %arrayidx15, align 1, !tbaa !11
  %conv16 = zext i8 %7 to i32
  %sub17 = sub nsw i32 %conv14, %conv16
  %shl18 = shl nsw i32 %sub17, 16
  %add19 = add nsw i32 %shl18, %sub12
  %arrayidx20 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 2
  %8 = load i8, ptr %arrayidx20, align 1, !tbaa !11
  %conv21 = zext i8 %8 to i32
  %arrayidx22 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 2
  %9 = load i8, ptr %arrayidx22, align 1, !tbaa !11
  %conv23 = zext i8 %9 to i32
  %sub24 = sub nsw i32 %conv21, %conv23
  %arrayidx25 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 6
  %10 = load i8, ptr %arrayidx25, align 1, !tbaa !11
  %conv26 = zext i8 %10 to i32
  %arrayidx27 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 6
  %11 = load i8, ptr %arrayidx27, align 1, !tbaa !11
  %conv28 = zext i8 %11 to i32
  %sub29 = sub nsw i32 %conv26, %conv28
  %shl30 = shl nsw i32 %sub29, 16
  %add31 = add nsw i32 %shl30, %sub24
  %arrayidx32 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 3
  %12 = load i8, ptr %arrayidx32, align 1, !tbaa !11
  %conv33 = zext i8 %12 to i32
  %arrayidx34 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 3
  %13 = load i8, ptr %arrayidx34, align 1, !tbaa !11
  %conv35 = zext i8 %13 to i32
  %sub36 = sub nsw i32 %conv33, %conv35
  %arrayidx37 = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 7
  %14 = load i8, ptr %arrayidx37, align 1, !tbaa !11
  %conv38 = zext i8 %14 to i32
  %arrayidx39 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 7
  %15 = load i8, ptr %arrayidx39, align 1, !tbaa !11
  %conv40 = zext i8 %15 to i32
  %sub41 = sub nsw i32 %conv38, %conv40
  %shl42 = shl nsw i32 %sub41, 16
  %add43 = add nsw i32 %shl42, %sub36
  %add44 = add nsw i32 %add19, %add
  %sub45 = sub nsw i32 %add, %add19
  %add46 = add nsw i32 %add43, %add31
  %sub47 = sub nsw i32 %add31, %add43
  %add48 = add nsw i32 %add46, %add44
  %arrayidx49 = getelementptr inbounds [4 x [4 x i32]], ptr %tmpa, i64 0, i64 %indvars.iv
  store i32 %add48, ptr %arrayidx49, align 8, !tbaa !14
  %sub51 = sub nsw i32 %add44, %add46
  %arrayidx54 = getelementptr inbounds i8, ptr %arrayidx49, i64 8
  store i32 %sub51, ptr %arrayidx54, align 8, !tbaa !14
  %add55 = add nsw i32 %sub47, %sub45
  %arrayidx58 = getelementptr inbounds i8, ptr %arrayidx49, i64 4
  store i32 %add55, ptr %arrayidx58, align 4, !tbaa !14
  %sub59 = sub nsw i32 %sub45, %sub47
  %arrayidx62 = getelementptr inbounds i8, ptr %arrayidx49, i64 12
  store i32 %sub59, ptr %arrayidx62, align 4, !tbaa !14
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %add.ptr = getelementptr inbounds i8, ptr %pix1.addr.0144, i64 %idx.ext
  %add.ptr64 = getelementptr inbounds i8, ptr %pix2.addr.0143, i64 %idx.ext63
  %exitcond = icmp ne i64 %indvars.iv.next, 4
  br i1 %exitcond, label %for.body, label %for.cond66.preheader, !llvm.loop !16

for.cond122.preheader:                            ; preds = %for.body70
  %add113.lcssa = phi i32 [ %add113, %for.body70 ]
  %idx.ext201 = sext i32 %i_pix1 to i64
  %idx.ext203 = sext i32 %i_pix2 to i64
  br label %for.body126

for.body70:                                       ; preds = %for.cond66.preheader, %for.body70
  %indvars.iv153 = phi i64 [ 0, %for.cond66.preheader ], [ %indvars.iv.next154, %for.body70 ]
  %sum0.0146 = phi i32 [ 0, %for.cond66.preheader ], [ %add113, %for.body70 ]
  %arrayidx74 = getelementptr inbounds [4 x i32], ptr %tmpa, i64 0, i64 %indvars.iv153
  %16 = load i32, ptr %arrayidx74, align 4, !tbaa !14
  %arrayidx77 = getelementptr inbounds [4 x i32], ptr %arrayidx75, i64 0, i64 %indvars.iv153
  %17 = load i32, ptr %arrayidx77, align 4, !tbaa !14
  %add78 = add i32 %17, %16
  %sub86 = sub i32 %16, %17
  %arrayidx90 = getelementptr inbounds [4 x i32], ptr %arrayidx88, i64 0, i64 %indvars.iv153
  %18 = load i32, ptr %arrayidx90, align 4, !tbaa !14
  %arrayidx93 = getelementptr inbounds [4 x i32], ptr %arrayidx91, i64 0, i64 %indvars.iv153
  %19 = load i32, ptr %arrayidx93, align 4, !tbaa !14
  %add94 = add i32 %19, %18
  %sub102 = sub i32 %18, %19
  %add103 = add nsw i32 %add94, %add78
  %sub104 = sub nsw i32 %add78, %add94
  %add105 = add nsw i32 %sub102, %sub86
  %sub106 = sub nsw i32 %sub86, %sub102
  %shr.i = lshr i32 %add103, 15
  %and.i = and i32 %shr.i, 65537
  %mul.i = mul nuw i32 %and.i, 65535
  %add.i = add i32 %mul.i, %add103
  %xor.i = xor i32 %add.i, %mul.i
  %shr.i107 = lshr i32 %add105, 15
  %and.i108 = and i32 %shr.i107, 65537
  %mul.i109 = mul nuw i32 %and.i108, 65535
  %add.i110 = add i32 %mul.i109, %add105
  %xor.i111 = xor i32 %add.i110, %mul.i109
  %shr.i112 = lshr i32 %sub104, 15
  %and.i113 = and i32 %shr.i112, 65537
  %mul.i114 = mul nuw i32 %and.i113, 65535
  %add.i115 = add i32 %mul.i114, %sub104
  %xor.i116 = xor i32 %add.i115, %mul.i114
  %shr.i117 = lshr i32 %sub106, 15
  %and.i118 = and i32 %shr.i117, 65537
  %mul.i119 = mul nuw i32 %and.i118, 65535
  %add.i120 = add i32 %mul.i119, %sub106
  %xor.i121 = xor i32 %add.i120, %mul.i119
  %add108 = add i32 %xor.i111, %sum0.0146
  %add110 = add i32 %add108, %xor.i
  %add112 = add i32 %add110, %xor.i116
  %add113 = add i32 %add112, %xor.i121
  %indvars.iv.next154 = add nuw nsw i64 %indvars.iv153, 1
  %exitcond156 = icmp ne i64 %indvars.iv.next154, 4
  br i1 %exitcond156, label %for.body70, label %for.cond122.preheader, !llvm.loop !18

for.cond207.preheader:                            ; preds = %for.body126
  %arrayidx216 = getelementptr inbounds i8, ptr %tmpb, i64 16
  %arrayidx229 = getelementptr inbounds i8, ptr %tmpb, i64 32
  %arrayidx232 = getelementptr inbounds i8, ptr %tmpb, i64 48
  br label %for.body211

for.body126:                                      ; preds = %for.cond122.preheader, %for.body126
  %indvars.iv157 = phi i64 [ 0, %for.cond122.preheader ], [ %indvars.iv.next158, %for.body126 ]
  %pix1.addr.1149 = phi ptr [ %add.ptr.lcssa, %for.cond122.preheader ], [ %add.ptr202, %for.body126 ]
  %pix2.addr.1148 = phi ptr [ %add.ptr64.lcssa, %for.cond122.preheader ], [ %add.ptr204, %for.body126 ]
  %20 = load i8, ptr %pix1.addr.1149, align 1, !tbaa !11
  %conv128 = zext i8 %20 to i32
  %21 = load i8, ptr %pix2.addr.1148, align 1, !tbaa !11
  %conv130 = zext i8 %21 to i32
  %sub131 = sub nsw i32 %conv128, %conv130
  %arrayidx132 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 4
  %22 = load i8, ptr %arrayidx132, align 1, !tbaa !11
  %conv133 = zext i8 %22 to i32
  %arrayidx134 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 4
  %23 = load i8, ptr %arrayidx134, align 1, !tbaa !11
  %conv135 = zext i8 %23 to i32
  %sub136 = sub nsw i32 %conv133, %conv135
  %shl137 = shl nsw i32 %sub136, 16
  %add138 = add nsw i32 %shl137, %sub131
  %arrayidx139 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 1
  %24 = load i8, ptr %arrayidx139, align 1, !tbaa !11
  %conv140 = zext i8 %24 to i32
  %arrayidx141 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 1
  %25 = load i8, ptr %arrayidx141, align 1, !tbaa !11
  %conv142 = zext i8 %25 to i32
  %sub143 = sub nsw i32 %conv140, %conv142
  %arrayidx144 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 5
  %26 = load i8, ptr %arrayidx144, align 1, !tbaa !11
  %conv145 = zext i8 %26 to i32
  %arrayidx146 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 5
  %27 = load i8, ptr %arrayidx146, align 1, !tbaa !11
  %conv147 = zext i8 %27 to i32
  %sub148 = sub nsw i32 %conv145, %conv147
  %shl149 = shl nsw i32 %sub148, 16
  %add150 = add nsw i32 %shl149, %sub143
  %arrayidx151 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 2
  %28 = load i8, ptr %arrayidx151, align 1, !tbaa !11
  %conv152 = zext i8 %28 to i32
  %arrayidx153 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 2
  %29 = load i8, ptr %arrayidx153, align 1, !tbaa !11
  %conv154 = zext i8 %29 to i32
  %sub155 = sub nsw i32 %conv152, %conv154
  %arrayidx156 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 6
  %30 = load i8, ptr %arrayidx156, align 1, !tbaa !11
  %conv157 = zext i8 %30 to i32
  %arrayidx158 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 6
  %31 = load i8, ptr %arrayidx158, align 1, !tbaa !11
  %conv159 = zext i8 %31 to i32
  %sub160 = sub nsw i32 %conv157, %conv159
  %shl161 = shl nsw i32 %sub160, 16
  %add162 = add nsw i32 %shl161, %sub155
  %arrayidx163 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 3
  %32 = load i8, ptr %arrayidx163, align 1, !tbaa !11
  %conv164 = zext i8 %32 to i32
  %arrayidx165 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 3
  %33 = load i8, ptr %arrayidx165, align 1, !tbaa !11
  %conv166 = zext i8 %33 to i32
  %sub167 = sub nsw i32 %conv164, %conv166
  %arrayidx168 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 7
  %34 = load i8, ptr %arrayidx168, align 1, !tbaa !11
  %conv169 = zext i8 %34 to i32
  %arrayidx170 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 7
  %35 = load i8, ptr %arrayidx170, align 1, !tbaa !11
  %conv171 = zext i8 %35 to i32
  %sub172 = sub nsw i32 %conv169, %conv171
  %shl173 = shl nsw i32 %sub172, 16
  %add174 = add nsw i32 %shl173, %sub167
  %add176 = add nsw i32 %add150, %add138
  %sub178 = sub nsw i32 %add138, %add150
  %add180 = add nsw i32 %add174, %add162
  %sub182 = sub nsw i32 %add162, %add174
  %add183 = add nsw i32 %add180, %add176
  %arrayidx185 = getelementptr inbounds [4 x [4 x i32]], ptr %tmpb, i64 0, i64 %indvars.iv157
  store i32 %add183, ptr %arrayidx185, align 8, !tbaa !14
  %sub187 = sub nsw i32 %add176, %add180
  %arrayidx190 = getelementptr inbounds i8, ptr %arrayidx185, i64 8
  store i32 %sub187, ptr %arrayidx190, align 8, !tbaa !14
  %add191 = add nsw i32 %sub182, %sub178
  %arrayidx194 = getelementptr inbounds i8, ptr %arrayidx185, i64 4
  store i32 %add191, ptr %arrayidx194, align 4, !tbaa !14
  %sub195 = sub nsw i32 %sub178, %sub182
  %arrayidx198 = getelementptr inbounds i8, ptr %arrayidx185, i64 12
  store i32 %sub195, ptr %arrayidx198, align 4, !tbaa !14
  %indvars.iv.next158 = add nuw nsw i64 %indvars.iv157, 1
  %add.ptr202 = getelementptr inbounds i8, ptr %pix1.addr.1149, i64 %idx.ext201
  %add.ptr204 = getelementptr inbounds i8, ptr %pix2.addr.1148, i64 %idx.ext203
  %exitcond160 = icmp ne i64 %indvars.iv.next158, 4
  br i1 %exitcond160, label %for.body126, label %for.cond207.preheader, !llvm.loop !19

for.cond.cleanup210:                              ; preds = %for.body211
  %add255.lcssa = phi i32 [ %add255, %for.body211 ]
  %conv118 = and i32 %add113.lcssa, 65535
  %shr = lshr i32 %add113.lcssa, 16
  %add119 = add nuw nsw i32 %conv118, %shr
  %shr120 = lshr i32 %add119, 1
  %conv260 = and i32 %add255.lcssa, 65535
  %cmp261 = icmp ugt i32 %add255.lcssa, 16
  %conv262 = zext i1 %cmp261 to i32
  %add263 = add nuw nsw i32 %conv260, %conv262
  %shr264 = lshr i32 %add263, 1
  %add265 = add nuw nsw i32 %shr264, %shr120
  call void @llvm.lifetime.end.p0(i64 64, ptr nonnull %tmpb) #2
  call void @llvm.lifetime.end.p0(i64 64, ptr nonnull %tmpa) #2
  ret i32 %add265

for.body211:                                      ; preds = %for.cond207.preheader, %for.body211
  %indvars.iv161 = phi i64 [ 0, %for.cond207.preheader ], [ %indvars.iv.next162, %for.body211 ]
  %sum1.0150 = phi i32 [ 0, %for.cond207.preheader ], [ %add255, %for.body211 ]
  %arrayidx215 = getelementptr inbounds [4 x i32], ptr %tmpb, i64 0, i64 %indvars.iv161
  %36 = load i32, ptr %arrayidx215, align 4, !tbaa !14
  %arrayidx218 = getelementptr inbounds [4 x i32], ptr %arrayidx216, i64 0, i64 %indvars.iv161
  %37 = load i32, ptr %arrayidx218, align 4, !tbaa !14
  %add219 = add i32 %37, %36
  %sub227 = sub i32 %36, %37
  %arrayidx231 = getelementptr inbounds [4 x i32], ptr %arrayidx229, i64 0, i64 %indvars.iv161
  %38 = load i32, ptr %arrayidx231, align 4, !tbaa !14
  %arrayidx234 = getelementptr inbounds [4 x i32], ptr %arrayidx232, i64 0, i64 %indvars.iv161
  %39 = load i32, ptr %arrayidx234, align 4, !tbaa !14
  %add235 = add i32 %39, %38
  %sub243 = sub i32 %38, %39
  %add244 = add nsw i32 %add235, %add219
  %sub245 = sub nsw i32 %add219, %add235
  %add246 = add nsw i32 %sub243, %sub227
  %sub247 = sub nsw i32 %sub227, %sub243
  %shr.i122 = lshr i32 %add244, 15
  %and.i123 = and i32 %shr.i122, 65537
  %mul.i124 = mul nuw i32 %and.i123, 65535
  %add.i125 = add i32 %mul.i124, %add244
  %xor.i126 = xor i32 %add.i125, %mul.i124
  %shr.i127 = lshr i32 %add246, 15
  %and.i128 = and i32 %shr.i127, 65537
  %mul.i129 = mul nuw i32 %and.i128, 65535
  %add.i130 = add i32 %mul.i129, %add246
  %xor.i131 = xor i32 %add.i130, %mul.i129
  %shr.i132 = lshr i32 %sub245, 15
  %and.i133 = and i32 %shr.i132, 65537
  %mul.i134 = mul nuw i32 %and.i133, 65535
  %add.i135 = add i32 %mul.i134, %sub245
  %xor.i136 = xor i32 %add.i135, %mul.i134
  %shr.i137 = lshr i32 %sub247, 15
  %and.i138 = and i32 %shr.i137, 65537
  %mul.i139 = mul nuw i32 %and.i138, 65535
  %add.i140 = add i32 %mul.i139, %sub247
  %xor.i141 = xor i32 %add.i140, %mul.i139
  %add250 = add i32 %xor.i131, %sum1.0150
  %add252 = add i32 %add250, %xor.i126
  %add254 = add i32 %add252, %xor.i136
  %add255 = add i32 %add254, %xor.i141
  %indvars.iv.next162 = add nuw nsw i64 %indvars.iv161, 1
  %exitcond164 = icmp ne i64 %indvars.iv.next162, 4
  br i1 %exitcond164, label %for.body211, label %for.cond.cleanup210, !llvm.loop !20
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg %0, ptr nocapture %1) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg %0, ptr nocapture %1) #1

attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nounwind }

!11 = !{!12, !12, i64 0}
!12 = !{!"omnipotent char", !13, i64 0}
!13 = !{!"Simple C/C++ TBAA"}
!14 = !{!15, !15, i64 0}
!15 = !{!"int", !12, i64 0}
!16 = distinct !{!16, !17}
!17 = !{!"llvm.loop.mustprogress"}
!18 = distinct !{!18, !17}
!19 = distinct !{!19, !17}
!20 = distinct !{!20, !17}
;.
; CHECK: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; CHECK: [[META1]] = !{!"omnipotent char", [[META2:![0-9]+]], i64 0}
; CHECK: [[META2]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
; CHECK: [[META4]] = !{!"int", [[META1]], i64 0}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META6]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META6]]}
;.
