// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f -target-feature +d \
// RUN:   -target-feature +v -target-feature +zfh -target-feature +experimental-zvfh \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck --check-prefix=CHECK-RV64 %s
#include <riscv_vector.h>
#include <riscv_ntlh.h>
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf8_ntl_PALL (int8_t *base, vuint8mf8_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei8_v_i8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf4_ntl_PALL (int8_t *base, vuint8mf4_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_i8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf2_ntl_PALL (int8_t *base, vuint8mf2_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_i8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m1_ntl_PALL (int8_t *base, vuint8m1_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m2_ntl_PALL (int8_t *base, vuint8m2_t bindex, vint8m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m4_ntl_PALL (int8_t *base, vuint8m4_t bindex, vint8m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m8_ntl_PALL (int8_t *base, vuint8m8_t bindex, vint8m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8mf8_ntl_PALL (int8_t *base, vuint16mf4_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei16_v_i8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8mf4_ntl_PALL (int8_t *base, vuint16mf2_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_i8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8mf2_ntl_PALL (int8_t *base, vuint16m1_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_i8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8m1_ntl_PALL (int8_t *base, vuint16m2_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8m2_ntl_PALL (int8_t *base, vuint16m4_t bindex, vint8m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i8m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8m4_ntl_PALL (int8_t *base, vuint16m8_t bindex, vint8m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i8m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8mf8_ntl_PALL (int8_t *base, vuint32mf2_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei32_v_i8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8mf4_ntl_PALL (int8_t *base, vuint32m1_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_i8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8mf2_ntl_PALL (int8_t *base, vuint32m2_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_i8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8m1_ntl_PALL (int8_t *base, vuint32m4_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8m2_ntl_PALL (int8_t *base, vuint32m8_t bindex, vint8m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i8m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8mf8_ntl_PALL (int8_t *base, vuint64m1_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei64_v_i8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8mf4_ntl_PALL (int8_t *base, vuint64m2_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_i8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8mf2_ntl_PALL (int8_t *base, vuint64m4_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_i8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8m1_ntl_PALL (int8_t *base, vuint64m8_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf4_ntl_PALL (int16_t *base, vuint8mf8_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_i16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf2_ntl_PALL (int16_t *base, vuint8mf4_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_i16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m1_ntl_PALL (int16_t *base, vuint8mf2_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m2_ntl_PALL (int16_t *base, vuint8m1_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m4_ntl_PALL (int16_t *base, vuint8m2_t bindex, vint16m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m8_ntl_PALL (int16_t *base, vuint8m4_t bindex, vint16m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16mf4_ntl_PALL (int16_t *base, vuint16mf4_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_i16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16mf2_ntl_PALL (int16_t *base, vuint16mf2_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_i16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m1_ntl_PALL (int16_t *base, vuint16m1_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m2_ntl_PALL (int16_t *base, vuint16m2_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m4_ntl_PALL (int16_t *base, vuint16m4_t bindex, vint16m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m8_ntl_PALL (int16_t *base, vuint16m8_t bindex, vint16m8_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16mf4_ntl_PALL (int16_t *base, vuint32mf2_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_i16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16mf2_ntl_PALL (int16_t *base, vuint32m1_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_i16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16m1_ntl_PALL (int16_t *base, vuint32m2_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16m2_ntl_PALL (int16_t *base, vuint32m4_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16m4_ntl_PALL (int16_t *base, vuint32m8_t bindex, vint16m4_t value, size_t vl, int domain) {
  return vsoxei32_v_i16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16mf4_ntl_PALL (int16_t *base, vuint64m1_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_i16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16mf2_ntl_PALL (int16_t *base, vuint64m2_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_i16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16m1_ntl_PALL (int16_t *base, vuint64m4_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16m2_ntl_PALL (int16_t *base, vuint64m8_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei64_v_i16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32mf2_ntl_PALL (int32_t *base, vuint8mf8_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_i32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m1_ntl_PALL (int32_t *base, vuint8mf4_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m2_ntl_PALL (int32_t *base, vuint8mf2_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m4_ntl_PALL (int32_t *base, vuint8m1_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m8_ntl_PALL (int32_t *base, vuint8m2_t bindex, vint32m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32mf2_ntl_PALL (int32_t *base, vuint16mf4_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_i32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m1_ntl_PALL (int32_t *base, vuint16mf2_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m2_ntl_PALL (int32_t *base, vuint16m1_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m4_ntl_PALL (int32_t *base, vuint16m2_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m8_ntl_PALL (int32_t *base, vuint16m4_t bindex, vint32m8_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32mf2_ntl_PALL (int32_t *base, vuint32mf2_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_i32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m1_ntl_PALL (int32_t *base, vuint32m1_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m2_ntl_PALL (int32_t *base, vuint32m2_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m4_ntl_PALL (int32_t *base, vuint32m4_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m8_ntl_PALL (int32_t *base, vuint32m8_t bindex, vint32m8_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32mf2_ntl_PALL (int32_t *base, vuint64m1_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_i32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32m1_ntl_PALL (int32_t *base, vuint64m2_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32m2_ntl_PALL (int32_t *base, vuint64m4_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei64_v_i32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32m4_ntl_PALL (int32_t *base, vuint64m8_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei64_v_i32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m1_ntl_PALL (int64_t *base, vuint8mf8_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m2_ntl_PALL (int64_t *base, vuint8mf4_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m4_ntl_PALL (int64_t *base, vuint8mf2_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m8_ntl_PALL (int64_t *base, vuint8m1_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m1_ntl_PALL (int64_t *base, vuint16mf4_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m2_ntl_PALL (int64_t *base, vuint16mf2_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m4_ntl_PALL (int64_t *base, vuint16m1_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m8_ntl_PALL (int64_t *base, vuint16m2_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m1_ntl_PALL (int64_t *base, vuint32mf2_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m2_ntl_PALL (int64_t *base, vuint32m1_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m4_ntl_PALL (int64_t *base, vuint32m2_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m8_ntl_PALL (int64_t *base, vuint32m4_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m1_ntl_PALL (int64_t *base, vuint64m1_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m2_ntl_PALL (int64_t *base, vuint64m2_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m4_ntl_PALL (int64_t *base, vuint64m4_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m8_ntl_PALL (int64_t *base, vuint64m8_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf8_ntl_PALL (uint8_t *base, vuint8mf8_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei8_v_u8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf4_ntl_PALL (uint8_t *base, vuint8mf4_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_u8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf2_ntl_PALL (uint8_t *base, vuint8mf2_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_u8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m1_ntl_PALL (uint8_t *base, vuint8m1_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m2_ntl_PALL (uint8_t *base, vuint8m2_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m4_ntl_PALL (uint8_t *base, vuint8m4_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m8_ntl_PALL (uint8_t *base, vuint8m8_t bindex, vuint8m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8mf8_ntl_PALL (uint8_t *base, vuint16mf4_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei16_v_u8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8mf4_ntl_PALL (uint8_t *base, vuint16mf2_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_u8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8mf2_ntl_PALL (uint8_t *base, vuint16m1_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_u8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8m1_ntl_PALL (uint8_t *base, vuint16m2_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8m2_ntl_PALL (uint8_t *base, vuint16m4_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u8m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8m4_ntl_PALL (uint8_t *base, vuint16m8_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u8m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8mf8_ntl_PALL (uint8_t *base, vuint32mf2_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei32_v_u8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8mf4_ntl_PALL (uint8_t *base, vuint32m1_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_u8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8mf2_ntl_PALL (uint8_t *base, vuint32m2_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_u8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8m1_ntl_PALL (uint8_t *base, vuint32m4_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8m2_ntl_PALL (uint8_t *base, vuint32m8_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u8m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8mf8_ntl_PALL (uint8_t *base, vuint64m1_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei64_v_u8mf8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8mf4_ntl_PALL (uint8_t *base, vuint64m2_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_u8mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8mf2_ntl_PALL (uint8_t *base, vuint64m4_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_u8mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8m1_ntl_PALL (uint8_t *base, vuint64m8_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u8m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf4_ntl_PALL (uint16_t *base, vuint8mf8_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_u16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf2_ntl_PALL (uint16_t *base, vuint8mf4_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_u16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m1_ntl_PALL (uint16_t *base, vuint8mf2_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m2_ntl_PALL (uint16_t *base, vuint8m1_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m4_ntl_PALL (uint16_t *base, vuint8m2_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m8_ntl_PALL (uint16_t *base, vuint8m4_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16mf4_ntl_PALL (uint16_t *base, vuint16mf4_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_u16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16mf2_ntl_PALL (uint16_t *base, vuint16mf2_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_u16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m1_ntl_PALL (uint16_t *base, vuint16m1_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m2_ntl_PALL (uint16_t *base, vuint16m2_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m4_ntl_PALL (uint16_t *base, vuint16m4_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m8_ntl_PALL (uint16_t *base, vuint16m8_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16mf4_ntl_PALL (uint16_t *base, vuint32mf2_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_u16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16mf2_ntl_PALL (uint16_t *base, vuint32m1_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_u16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16m1_ntl_PALL (uint16_t *base, vuint32m2_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16m2_ntl_PALL (uint16_t *base, vuint32m4_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16m4_ntl_PALL (uint16_t *base, vuint32m8_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return vsoxei32_v_u16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16mf4_ntl_PALL (uint16_t *base, vuint64m1_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_u16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16mf2_ntl_PALL (uint16_t *base, vuint64m2_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_u16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16m1_ntl_PALL (uint16_t *base, vuint64m4_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16m2_ntl_PALL (uint16_t *base, vuint64m8_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei64_v_u16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32mf2_ntl_PALL (uint32_t *base, vuint8mf8_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_u32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m1_ntl_PALL (uint32_t *base, vuint8mf4_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m2_ntl_PALL (uint32_t *base, vuint8mf2_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m4_ntl_PALL (uint32_t *base, vuint8m1_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m8_ntl_PALL (uint32_t *base, vuint8m2_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32mf2_ntl_PALL (uint32_t *base, vuint16mf4_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_u32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m1_ntl_PALL (uint32_t *base, vuint16mf2_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m2_ntl_PALL (uint32_t *base, vuint16m1_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m4_ntl_PALL (uint32_t *base, vuint16m2_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m8_ntl_PALL (uint32_t *base, vuint16m4_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32mf2_ntl_PALL (uint32_t *base, vuint32mf2_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_u32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m1_ntl_PALL (uint32_t *base, vuint32m1_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m2_ntl_PALL (uint32_t *base, vuint32m2_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m4_ntl_PALL (uint32_t *base, vuint32m4_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m8_ntl_PALL (uint32_t *base, vuint32m8_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32mf2_ntl_PALL (uint32_t *base, vuint64m1_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_u32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32m1_ntl_PALL (uint32_t *base, vuint64m2_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32m2_ntl_PALL (uint32_t *base, vuint64m4_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei64_v_u32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32m4_ntl_PALL (uint32_t *base, vuint64m8_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei64_v_u32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m1_ntl_PALL (uint64_t *base, vuint8mf8_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m2_ntl_PALL (uint64_t *base, vuint8mf4_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m4_ntl_PALL (uint64_t *base, vuint8mf2_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m8_ntl_PALL (uint64_t *base, vuint8m1_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m1_ntl_PALL (uint64_t *base, vuint16mf4_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m2_ntl_PALL (uint64_t *base, vuint16mf2_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m4_ntl_PALL (uint64_t *base, vuint16m1_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m8_ntl_PALL (uint64_t *base, vuint16m2_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m1_ntl_PALL (uint64_t *base, vuint32mf2_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m2_ntl_PALL (uint64_t *base, vuint32m1_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m4_ntl_PALL (uint64_t *base, vuint32m2_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m8_ntl_PALL (uint64_t *base, vuint32m4_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m1_ntl_PALL (uint64_t *base, vuint64m1_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m2_ntl_PALL (uint64_t *base, vuint64m2_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m4_ntl_PALL (uint64_t *base, vuint64m4_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m8_ntl_PALL (uint64_t *base, vuint64m8_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f16.nxv1i8.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf4_ntl_PALL (_Float16 *base, vuint8mf8_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_f16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f16.nxv2i8.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf2_ntl_PALL (_Float16 *base, vuint8mf4_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_f16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f16.nxv4i8.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m1_ntl_PALL (_Float16 *base, vuint8mf2_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f16.nxv8i8.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m2_ntl_PALL (_Float16 *base, vuint8m1_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f16.nxv16i8.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m4_ntl_PALL (_Float16 *base, vuint8m2_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32f16.nxv32i8.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m8_ntl_PALL (_Float16 *base, vuint8m4_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f16.nxv1i16.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16mf4_ntl_PALL (_Float16 *base, vuint16mf4_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_f16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f16.nxv2i16.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16mf2_ntl_PALL (_Float16 *base, vuint16mf2_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_f16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f16.nxv4i16.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m1_ntl_PALL (_Float16 *base, vuint16m1_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f16.nxv8i16.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m2_ntl_PALL (_Float16 *base, vuint16m2_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f16.nxv16i16.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m4_ntl_PALL (_Float16 *base, vuint16m4_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv32f16.nxv32i16.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m8_ntl_PALL (_Float16 *base, vuint16m8_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f16.nxv1i32.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16mf4_ntl_PALL (_Float16 *base, vuint32mf2_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_f16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f16.nxv2i32.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16mf2_ntl_PALL (_Float16 *base, vuint32m1_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_f16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f16.nxv4i32.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16m1_ntl_PALL (_Float16 *base, vuint32m2_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei32_v_f16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f16.nxv8i32.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16m2_ntl_PALL (_Float16 *base, vuint32m4_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei32_v_f16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f16.nxv16i32.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16m4_ntl_PALL (_Float16 *base, vuint32m8_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return vsoxei32_v_f16m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f16.nxv1i64.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16mf4_ntl_PALL (_Float16 *base, vuint64m1_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_f16mf4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f16.nxv2i64.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16mf2_ntl_PALL (_Float16 *base, vuint64m2_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_f16mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f16.nxv4i64.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16m1_ntl_PALL (_Float16 *base, vuint64m4_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei64_v_f16m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f16.nxv8i64.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16m2_ntl_PALL (_Float16 *base, vuint64m8_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei64_v_f16m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f32.nxv1i8.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32mf2_ntl_PALL (float *base, vuint8mf8_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_f32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f32.nxv2i8.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m1_ntl_PALL (float *base, vuint8mf4_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f32.nxv4i8.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m2_ntl_PALL (float *base, vuint8mf2_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f32.nxv8i8.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m4_ntl_PALL (float *base, vuint8m1_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f32.nxv16i8.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m8_ntl_PALL (float *base, vuint8m2_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f32.nxv1i16.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32mf2_ntl_PALL (float *base, vuint16mf4_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_f32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f32.nxv2i16.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m1_ntl_PALL (float *base, vuint16mf2_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f32.nxv4i16.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m2_ntl_PALL (float *base, vuint16m1_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f32.nxv8i16.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m4_ntl_PALL (float *base, vuint16m2_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f32.nxv16i16.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m8_ntl_PALL (float *base, vuint16m4_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f32.nxv1i32.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32mf2_ntl_PALL (float *base, vuint32mf2_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_f32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f32.nxv2i32.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m1_ntl_PALL (float *base, vuint32m1_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f32.nxv4i32.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m2_ntl_PALL (float *base, vuint32m2_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f32.nxv8i32.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m4_ntl_PALL (float *base, vuint32m4_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv16f32.nxv16i32.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m8_ntl_PALL (float *base, vuint32m8_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f32.nxv1i64.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32mf2_ntl_PALL (float *base, vuint64m1_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_f32mf2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f32.nxv2i64.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32m1_ntl_PALL (float *base, vuint64m2_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei64_v_f32m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f32.nxv4i64.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32m2_ntl_PALL (float *base, vuint64m4_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei64_v_f32m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f32.nxv8i64.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32m4_ntl_PALL (float *base, vuint64m8_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei64_v_f32m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f64.nxv1i8.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m1_ntl_PALL (double *base, vuint8mf8_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f64.nxv2i8.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m2_ntl_PALL (double *base, vuint8mf4_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f64.nxv4i8.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m4_ntl_PALL (double *base, vuint8mf2_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f64.nxv8i8.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m8_ntl_PALL (double *base, vuint8m1_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f64.nxv1i16.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m1_ntl_PALL (double *base, vuint16mf4_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f64.nxv2i16.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m2_ntl_PALL (double *base, vuint16mf2_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f64.nxv4i16.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m4_ntl_PALL (double *base, vuint16m1_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f64.nxv8i16.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m8_ntl_PALL (double *base, vuint16m2_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f64.nxv1i32.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m1_ntl_PALL (double *base, vuint32mf2_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f64.nxv2i32.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m2_ntl_PALL (double *base, vuint32m1_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f64.nxv4i32.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m4_ntl_PALL (double *base, vuint32m2_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f64.nxv8i32.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m8_ntl_PALL (double *base, vuint32m4_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv1f64.nxv1i64.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m1_ntl_PALL (double *base, vuint64m1_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m1_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv2f64.nxv2i64.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m2_ntl_PALL (double *base, vuint64m2_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m2_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv4f64.nxv4i64.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m4_ntl_PALL (double *base, vuint64m4_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m4_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.nxv8f64.nxv8i64.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m8_ntl_PALL (double *base, vuint64m8_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m8_ntl(base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, vuint8mf8_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei8_v_i8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, vuint8mf4_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_i8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, vuint8mf2_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_i8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, vuint8m1_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, vuint8m2_t bindex, vint8m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m4_m_ntl_PALL (vbool2_t mask, int8_t *base, vuint8m4_t bindex, vint8m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i8m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i8m8_m_ntl_PALL (vbool1_t mask, int8_t *base, vuint8m8_t bindex, vint8m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i8m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, vuint16mf4_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei16_v_i8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, vuint16mf2_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_i8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, vuint16m1_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_i8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, vuint16m2_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, vuint16m4_t bindex, vint8m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i8m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i8m4_m_ntl_PALL (vbool2_t mask, int8_t *base, vuint16m8_t bindex, vint8m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i8m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, vuint32mf2_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei32_v_i8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, vuint32m1_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_i8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, vuint32m2_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_i8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, vuint32m4_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, vuint32m8_t bindex, vint8m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i8m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, vuint64m1_t bindex, vint8mf8_t value, size_t vl, int domain) {
  return vsoxei64_v_i8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, vuint64m2_t bindex, vint8mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_i8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, vuint64m4_t bindex, vint8mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_i8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, vuint64m8_t bindex, vint8m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, vuint8mf8_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_i16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, vuint8mf4_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_i16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, vuint8mf2_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, vuint8m1_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m4_m_ntl_PALL (vbool4_t mask, int16_t *base, vuint8m2_t bindex, vint16m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i16m8_m_ntl_PALL (vbool2_t mask, int16_t *base, vuint8m4_t bindex, vint16m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i16m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, vuint16mf4_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_i16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, vuint16mf2_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_i16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, vuint16m1_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, vuint16m2_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m4_m_ntl_PALL (vbool4_t mask, int16_t *base, vuint16m4_t bindex, vint16m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i16m8_m_ntl_PALL (vbool2_t mask, int16_t *base, vuint16m8_t bindex, vint16m8_t value, size_t vl, int domain) {
  return vsoxei16_v_i16m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, vuint32mf2_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_i16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, vuint32m1_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_i16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, vuint32m2_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, vuint32m4_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i16m4_m_ntl_PALL (vbool4_t mask, int16_t *base, vuint32m8_t bindex, vint16m4_t value, size_t vl, int domain) {
  return vsoxei32_v_i16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, vuint64m1_t bindex, vint16mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_i16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, vuint64m2_t bindex, vint16mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_i16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, vuint64m4_t bindex, vint16m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, vuint64m8_t bindex, vint16m2_t value, size_t vl, int domain) {
  return vsoxei64_v_i16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, vuint8mf8_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_i32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, vuint8mf4_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, vuint8mf2_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m4_m_ntl_PALL (vbool8_t mask, int32_t *base, vuint8m1_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i32m8_m_ntl_PALL (vbool4_t mask, int32_t *base, vuint8m2_t bindex, vint32m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, vuint16mf4_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_i32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, vuint16mf2_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, vuint16m1_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m4_m_ntl_PALL (vbool8_t mask, int32_t *base, vuint16m2_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i32m8_m_ntl_PALL (vbool4_t mask, int32_t *base, vuint16m4_t bindex, vint32m8_t value, size_t vl, int domain) {
  return vsoxei16_v_i32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, vuint32mf2_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_i32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, vuint32m1_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, vuint32m2_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m4_m_ntl_PALL (vbool8_t mask, int32_t *base, vuint32m4_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i32m8_m_ntl_PALL (vbool4_t mask, int32_t *base, vuint32m8_t bindex, vint32m8_t value, size_t vl, int domain) {
  return vsoxei32_v_i32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, vuint64m1_t bindex, vint32mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_i32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, vuint64m2_t bindex, vint32m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, vuint64m4_t bindex, vint32m2_t value, size_t vl, int domain) {
  return vsoxei64_v_i32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i32m4_m_ntl_PALL (vbool8_t mask, int32_t *base, vuint64m8_t bindex, vint32m4_t value, size_t vl, int domain) {
  return vsoxei64_v_i32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, vuint8mf8_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, vuint8mf4_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m4_m_ntl_PALL (vbool16_t mask, int64_t *base, vuint8mf2_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_i64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_i64m8_m_ntl_PALL (vbool8_t mask, int64_t *base, vuint8m1_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei8_v_i64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, vuint16mf4_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, vuint16mf2_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m4_m_ntl_PALL (vbool16_t mask, int64_t *base, vuint16m1_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_i64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_i64m8_m_ntl_PALL (vbool8_t mask, int64_t *base, vuint16m2_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei16_v_i64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, vuint32mf2_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, vuint32m1_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m4_m_ntl_PALL (vbool16_t mask, int64_t *base, vuint32m2_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_i64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_i64m8_m_ntl_PALL (vbool8_t mask, int64_t *base, vuint32m4_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei32_v_i64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, vuint64m1_t bindex, vint64m1_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, vuint64m2_t bindex, vint64m2_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m4_m_ntl_PALL (vbool16_t mask, int64_t *base, vuint64m4_t bindex, vint64m4_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_i64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_i64m8_m_ntl_PALL (vbool8_t mask, int64_t *base, vuint64m8_t bindex, vint64m8_t value, size_t vl, int domain) {
  return vsoxei64_v_i64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, vuint8mf8_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei8_v_u8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, vuint8mf4_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_u8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, vuint8mf2_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_u8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, vuint8m1_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, vuint8m2_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m4_m_ntl_PALL (vbool2_t mask, uint8_t *base, vuint8m4_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u8m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u8m8_m_ntl_PALL (vbool1_t mask, uint8_t *base, vuint8m8_t bindex, vuint8m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u8m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, vuint16mf4_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei16_v_u8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, vuint16mf2_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_u8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, vuint16m1_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_u8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, vuint16m2_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, vuint16m4_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u8m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u8m4_m_ntl_PALL (vbool2_t mask, uint8_t *base, vuint16m8_t bindex, vuint8m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u8m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, vuint32mf2_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei32_v_u8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, vuint32m1_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_u8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, vuint32m2_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_u8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, vuint32m4_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, vuint32m8_t bindex, vuint8m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u8m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, vuint64m1_t bindex, vuint8mf8_t value, size_t vl, int domain) {
  return vsoxei64_v_u8mf8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, vuint64m2_t bindex, vuint8mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_u8mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, vuint64m4_t bindex, vuint8mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_u8mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, vuint64m8_t bindex, vuint8m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u8m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, vuint8mf8_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_u16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, vuint8mf4_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_u16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, vuint8mf2_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, vuint8m1_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m4_m_ntl_PALL (vbool4_t mask, uint16_t *base, vuint8m2_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u16m8_m_ntl_PALL (vbool2_t mask, uint16_t *base, vuint8m4_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u16m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, vuint16mf4_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_u16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, vuint16mf2_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_u16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, vuint16m1_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, vuint16m2_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m4_m_ntl_PALL (vbool4_t mask, uint16_t *base, vuint16m4_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u16m8_m_ntl_PALL (vbool2_t mask, uint16_t *base, vuint16m8_t bindex, vuint16m8_t value, size_t vl, int domain) {
  return vsoxei16_v_u16m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, vuint32mf2_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_u16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, vuint32m1_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_u16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, vuint32m2_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, vuint32m4_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u16m4_m_ntl_PALL (vbool4_t mask, uint16_t *base, vuint32m8_t bindex, vuint16m4_t value, size_t vl, int domain) {
  return vsoxei32_v_u16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, vuint64m1_t bindex, vuint16mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_u16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, vuint64m2_t bindex, vuint16mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_u16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, vuint64m4_t bindex, vuint16m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, vuint64m8_t bindex, vuint16m2_t value, size_t vl, int domain) {
  return vsoxei64_v_u16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, vuint8mf8_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_u32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, vuint8mf4_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, vuint8mf2_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m4_m_ntl_PALL (vbool8_t mask, uint32_t *base, vuint8m1_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u32m8_m_ntl_PALL (vbool4_t mask, uint32_t *base, vuint8m2_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, vuint16mf4_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_u32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, vuint16mf2_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, vuint16m1_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m4_m_ntl_PALL (vbool8_t mask, uint32_t *base, vuint16m2_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u32m8_m_ntl_PALL (vbool4_t mask, uint32_t *base, vuint16m4_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return vsoxei16_v_u32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, vuint32mf2_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_u32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, vuint32m1_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, vuint32m2_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m4_m_ntl_PALL (vbool8_t mask, uint32_t *base, vuint32m4_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u32m8_m_ntl_PALL (vbool4_t mask, uint32_t *base, vuint32m8_t bindex, vuint32m8_t value, size_t vl, int domain) {
  return vsoxei32_v_u32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, vuint64m1_t bindex, vuint32mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_u32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, vuint64m2_t bindex, vuint32m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, vuint64m4_t bindex, vuint32m2_t value, size_t vl, int domain) {
  return vsoxei64_v_u32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u32m4_m_ntl_PALL (vbool8_t mask, uint32_t *base, vuint64m8_t bindex, vuint32m4_t value, size_t vl, int domain) {
  return vsoxei64_v_u32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, vuint8mf8_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, vuint8mf4_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m4_m_ntl_PALL (vbool16_t mask, uint64_t *base, vuint8mf2_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_u64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_u64m8_m_ntl_PALL (vbool8_t mask, uint64_t *base, vuint8m1_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei8_v_u64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, vuint16mf4_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, vuint16mf2_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m4_m_ntl_PALL (vbool16_t mask, uint64_t *base, vuint16m1_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_u64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_u64m8_m_ntl_PALL (vbool8_t mask, uint64_t *base, vuint16m2_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei16_v_u64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, vuint32mf2_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, vuint32m1_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m4_m_ntl_PALL (vbool16_t mask, uint64_t *base, vuint32m2_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_u64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_u64m8_m_ntl_PALL (vbool8_t mask, uint64_t *base, vuint32m4_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei32_v_u64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, vuint64m1_t bindex, vuint64m1_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, vuint64m2_t bindex, vuint64m2_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m4_m_ntl_PALL (vbool16_t mask, uint64_t *base, vuint64m4_t bindex, vuint64m4_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_u64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_u64m8_m_ntl_PALL (vbool8_t mask, uint64_t *base, vuint64m8_t bindex, vuint64m8_t value, size_t vl, int domain) {
  return vsoxei64_v_u64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f16.nxv1i8.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, vuint8mf8_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei8_v_f16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f16.nxv2i8.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, vuint8mf4_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_f16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f16.nxv4i8.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, vuint8mf2_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f16.nxv8i8.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, vuint8m1_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f16.nxv16i8.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m4_m_ntl_PALL (vbool4_t mask, _Float16 *base, vuint8m2_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32f16.nxv32i8.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f16m8_m_ntl_PALL (vbool2_t mask, _Float16 *base, vuint8m4_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return vsoxei8_v_f16m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f16.nxv1i16.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, vuint16mf4_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei16_v_f16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f16.nxv2i16.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, vuint16mf2_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_f16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f16.nxv4i16.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, vuint16m1_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f16.nxv8i16.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, vuint16m2_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f16.nxv16i16.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m4_m_ntl_PALL (vbool4_t mask, _Float16 *base, vuint16m4_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv32f16.nxv32i16.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f16m8_m_ntl_PALL (vbool2_t mask, _Float16 *base, vuint16m8_t bindex, vfloat16m8_t value, size_t vl, int domain) {
  return vsoxei16_v_f16m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f16.nxv1i32.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, vuint32mf2_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei32_v_f16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f16.nxv2i32.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, vuint32m1_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_f16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f16.nxv4i32.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, vuint32m2_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei32_v_f16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f16.nxv8i32.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, vuint32m4_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei32_v_f16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f16.nxv16i32.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f16m4_m_ntl_PALL (vbool4_t mask, _Float16 *base, vuint32m8_t bindex, vfloat16m4_t value, size_t vl, int domain) {
  return vsoxei32_v_f16m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f16.nxv1i64.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, vuint64m1_t bindex, vfloat16mf4_t value, size_t vl, int domain) {
  return vsoxei64_v_f16mf4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f16.nxv2i64.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, vuint64m2_t bindex, vfloat16mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_f16mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f16.nxv4i64.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, vuint64m4_t bindex, vfloat16m1_t value, size_t vl, int domain) {
  return vsoxei64_v_f16m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f16.nxv8i64.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, vuint64m8_t bindex, vfloat16m2_t value, size_t vl, int domain) {
  return vsoxei64_v_f16m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f32.nxv1i8.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, vuint8mf8_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei8_v_f32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f32.nxv2i8.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, vuint8mf4_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f32.nxv4i8.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, vuint8mf2_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f32.nxv8i8.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m4_m_ntl_PALL (vbool8_t mask, float *base, vuint8m1_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f32.nxv16i8.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f32m8_m_ntl_PALL (vbool4_t mask, float *base, vuint8m2_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return vsoxei8_v_f32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f32.nxv1i16.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, vuint16mf4_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei16_v_f32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f32.nxv2i16.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, vuint16mf2_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f32.nxv4i16.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, vuint16m1_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f32.nxv8i16.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m4_m_ntl_PALL (vbool8_t mask, float *base, vuint16m2_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f32.nxv16i16.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f32m8_m_ntl_PALL (vbool4_t mask, float *base, vuint16m4_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return vsoxei16_v_f32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f32.nxv1i32.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, vuint32mf2_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei32_v_f32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f32.nxv2i32.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, vuint32m1_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f32.nxv4i32.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, vuint32m2_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f32.nxv8i32.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m4_m_ntl_PALL (vbool8_t mask, float *base, vuint32m4_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv16f32.nxv16i32.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f32m8_m_ntl_PALL (vbool4_t mask, float *base, vuint32m8_t bindex, vfloat32m8_t value, size_t vl, int domain) {
  return vsoxei32_v_f32m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f32.nxv1i64.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, vuint64m1_t bindex, vfloat32mf2_t value, size_t vl, int domain) {
  return vsoxei64_v_f32mf2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f32.nxv2i64.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, vuint64m2_t bindex, vfloat32m1_t value, size_t vl, int domain) {
  return vsoxei64_v_f32m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f32.nxv4i64.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, vuint64m4_t bindex, vfloat32m2_t value, size_t vl, int domain) {
  return vsoxei64_v_f32m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f32.nxv8i64.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f32m4_m_ntl_PALL (vbool8_t mask, float *base, vuint64m8_t bindex, vfloat32m4_t value, size_t vl, int domain) {
  return vsoxei64_v_f32m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f64.nxv1i8.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, vuint8mf8_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f64.nxv2i8.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, vuint8mf4_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f64.nxv4i8.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m4_m_ntl_PALL (vbool16_t mask, double *base, vuint8mf2_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei8_v_f64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f64.nxv8i8.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei8_v_f64m8_m_ntl_PALL (vbool8_t mask, double *base, vuint8m1_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei8_v_f64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f64.nxv1i16.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, vuint16mf4_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f64.nxv2i16.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, vuint16mf2_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f64.nxv4i16.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m4_m_ntl_PALL (vbool16_t mask, double *base, vuint16m1_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei16_v_f64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f64.nxv8i16.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei16_v_f64m8_m_ntl_PALL (vbool8_t mask, double *base, vuint16m2_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei16_v_f64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f64.nxv1i32.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, vuint32mf2_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f64.nxv2i32.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, vuint32m1_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f64.nxv4i32.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m4_m_ntl_PALL (vbool16_t mask, double *base, vuint32m2_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei32_v_f64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f64.nxv8i32.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei32_v_f64m8_m_ntl_PALL (vbool8_t mask, double *base, vuint32m4_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei32_v_f64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv1f64.nxv1i64.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, vuint64m1_t bindex, vfloat64m1_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m1_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv2f64.nxv2i64.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, vuint64m2_t bindex, vfloat64m2_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m2_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv4f64.nxv4i64.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m4_m_ntl_PALL (vbool16_t mask, double *base, vuint64m4_t bindex, vfloat64m4_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m4_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vsoxei64_v_f64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vsoxei.mask.nxv8f64.nxv8i64.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vsoxei64_v_f64m8_m_ntl_PALL (vbool8_t mask, double *base, vuint64m8_t bindex, vfloat64m8_t value, size_t vl, int domain) {
  return vsoxei64_v_f64m8_m_ntl(mask, base, bindex, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
