; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -O0 -mtriple=riscv64 -mattr=+m,+v | FileCheck %s

define <8 x i8> @vqshlb_u8() {
; CHECK-LABEL: vqshlb_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 6
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x30, 0x22, 0x11, 0x06, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 48 + 6 * vlenb
; CHECK-NEXT:    li a0, 200
; CHECK-NEXT:    sb a0, 47(sp)
; CHECK-NEXT:    li a0, -3
; CHECK-NEXT:    sb a0, 46(sp)
; CHECK-NEXT:    lbu a0, 47(sp)
; CHECK-NEXT:    lbu a1, 46(sp)
; CHECK-NEXT:    sd a1, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    # implicit-def: $v9
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v9, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a2, a0, 1
; CHECK-NEXT:    add a0, a2, a0
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vs1r.v v9, (a0) # vscale x 8-byte Folded Spill
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    sub a0, a0, a1
; CHECK-NEXT:    # implicit-def: $v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vsrl.vx v8, v9, a0
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 2
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 48
; CHECK-NEXT:    vs1r.v v8, (a1) # vscale x 8-byte Folded Spill
; CHECK-NEXT:    # implicit-def: $v8
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, tu, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    sd a1, 32(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    slli a3, a2, 2
; CHECK-NEXT:    add a2, a3, a2
; CHECK-NEXT:    add a2, sp, a2
; CHECK-NEXT:    addi a2, a2, 48
; CHECK-NEXT:    vs1r.v v8, (a2) # vscale x 8-byte Folded Spill
; CHECK-NEXT:    bgeu a0, a1, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 2
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vl1r.v v8, (a0) # vscale x 8-byte Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a1, a0, 2
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vs1r.v v8, (a0) # vscale x 8-byte Folded Spill
; CHECK-NEXT:  .LBB0_2: # %entry
; CHECK-NEXT:    ld a0, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld a1, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    slli a3, a2, 2
; CHECK-NEXT:    add a2, a3, a2
; CHECK-NEXT:    add a2, sp, a2
; CHECK-NEXT:    addi a2, a2, 48
; CHECK-NEXT:    vl1r.v v8, (a2) # vscale x 8-byte Folded Reload
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    slli a2, a2, 1
; CHECK-NEXT:    add a2, sp, a2
; CHECK-NEXT:    addi a2, a2, 48
; CHECK-NEXT:    vs1r.v v8, (a2) # vscale x 8-byte Folded Spill
; CHECK-NEXT:    mv a2, a0
; CHECK-NEXT:    sd a2, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    bltu a0, a1, .LBB0_4
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ld a0, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    sd a0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:  .LBB0_4: # %entry
; CHECK-NEXT:    ld a0, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld a1, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    slli a2, a2, 1
; CHECK-NEXT:    add a2, sp, a2
; CHECK-NEXT:    addi a2, a2, 48
; CHECK-NEXT:    vl1r.v v8, (a2) # vscale x 8-byte Folded Reload
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    slli a3, a2, 1
; CHECK-NEXT:    add a2, a3, a2
; CHECK-NEXT:    add a2, sp, a2
; CHECK-NEXT:    addi a2, a2, 48
; CHECK-NEXT:    vl1r.v v10, (a2) # vscale x 8-byte Folded Reload
; CHECK-NEXT:    # implicit-def: $v9
; CHECK-NEXT:    vmv.v.x v9, a1
; CHECK-NEXT:    # implicit-def: $v11
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    # implicit-def: $v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    # implicit-def: $v10
; CHECK-NEXT:    vsll.vv v10, v9, v11
; CHECK-NEXT:    # implicit-def: $v9
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:    addi a1, sp, 48
; CHECK-NEXT:    vs1r.v v9, (a1) # vscale x 8-byte Folded Spill
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    add a2, sp, a2
; CHECK-NEXT:    addi a2, a2, 48
; CHECK-NEXT:    vs1r.v v8, (a2) # vscale x 8-byte Folded Spill
; CHECK-NEXT:    bgeu a0, a1, .LBB0_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    addi a0, sp, 48
; CHECK-NEXT:    vl1r.v v8, (a0) # vscale x 8-byte Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vs1r.v v8, (a0) # vscale x 8-byte Folded Spill
; CHECK-NEXT:  .LBB0_6: # %entry
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vl1r.v v8, (a0) # vscale x 8-byte Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 6
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 48
; CHECK-NEXT:    addi sp, sp, 48
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %__p0.addr.i = alloca i8, align 1
  %__p1.addr.i = alloca i8, align 1
  %__ret.i = alloca i8, align 1
  store i8 -56, ptr %__p0.addr.i, align 1
  store i8 -3, ptr %__p1.addr.i, align 1
  %0 = load i8, ptr %__p0.addr.i, align 1
  %1 = load i8, ptr %__p1.addr.i, align 1
  %2 = insertelement <8 x i8> poison, i8 %0, i64 0
  %3 = insertelement <8 x i8> poison, i8 %1, i64 0
  %vqshlb_u8.i = call <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8> %2, <8 x i8> %3)
  ret <8 x i8> %vqshlb_u8.i
}

declare <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8>, <8 x i8>)
