; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v -verify-machineinstrs | FileCheck %s

define void @_Z12export_rgba8PhiPfi(ptr nocapture noundef writeonly %dst, i32 noundef signext %channels, ptr noalias nocapture noundef readonly %data, i32 noundef signext %width_) {
; CHECK-LABEL: _Z12export_rgba8PhiPfi:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    blez a3, .LBB0_3
; CHECK-NEXT:  # %bb.1: # %for.body.lr.ph
; CHECK-NEXT:    slli a4, a3, 4
; CHECK-NEXT:    fmv.w.x fa5, zero
; CHECK-NEXT:    lui a3, 523264
; CHECK-NEXT:    lui a5, 276464
; CHECK-NEXT:    add a4, a2, a4
; CHECK-NEXT:    fmv.w.x fa4, a5
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:  .LBB0_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a2)
; CHECK-NEXT:    vfmax.vf v10, v9, fa5
; CHECK-NEXT:    vmfne.vv v0, v9, v9
; CHECK-NEXT:    vmerge.vxm v9, v10, a3, v0
; CHECK-NEXT:    vfmin.vf v10, v9, fa4
; CHECK-NEXT:    vmfne.vv v0, v9, v9
; CHECK-NEXT:    vmerge.vxm v9, v10, a3, v0
; CHECK-NEXT:    vmfne.vv v0, v9, v9
; CHECK-NEXT:    vfcvt.rtz.xu.f.v v9, v9
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v9, 0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v9, v8, 4
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v9, 0
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v9, (a0)
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    addi a2, a2, 16
; CHECK-NEXT:    bne a2, a4, .LBB0_2
; CHECK-NEXT:  .LBB0_3: # %for.cond.cleanup
; CHECK-NEXT:    ret
entry:
  %cmp7 = icmp sgt i32 %width_, 0
  br i1 %cmp7, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %idx.ext = sext i32 %channels to i64
  %wide.trip.count = zext nneg i32 %width_ to i64
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %indvars.iv = phi i64 [ 0, %for.body.lr.ph ], [ %indvars.iv.next, %for.body ]
  %dst.addr.09 = phi ptr [ %dst, %for.body.lr.ph ], [ %add.ptr, %for.body ]
  %arrayidx = getelementptr inbounds <4 x float>, ptr %data, i64 %indvars.iv
  %0 = load <4 x float>, ptr %arrayidx, align 16
  %vmax2.i = tail call fast <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float> %0, <4 x float> zeroinitializer)
  %vmin2.i = tail call fast <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float> %vmax2.i, <4 x float> <float 2.550000e+02, float 2.550000e+02, float 2.550000e+02, float 2.550000e+02>)
  %1 = tail call <4 x i32> @llvm.fptoui.sat.v4i32.v4f32(<4 x float> %vmin2.i)
  %vqmovn_v1.i.i = tail call <4 x i16> @llvm.aarch64.neon.uqxtn.v4i16(<4 x i32> %1)
  %shuffle.i.i = shufflevector <4 x i16> %vqmovn_v1.i.i, <4 x i16> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %vqmovn_v1.i8.i = tail call <8 x i8> @llvm.aarch64.neon.uqxtn.v8i8(<8 x i16> %shuffle.i.i)
  %shuffle.i9.i = shufflevector <8 x i8> %vqmovn_v1.i8.i, <8 x i8> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  %2 = bitcast <16 x i8> %shuffle.i9.i to <4 x i32>
  %vgetq_lane.i = extractelement <4 x i32> %2, i64 0
  store i32 %vgetq_lane.i, ptr %dst.addr.09, align 4
  %add.ptr = getelementptr inbounds i8, ptr %dst.addr.09, i64 %idx.ext
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

declare <4 x i16> @llvm.aarch64.neon.uqxtn.v4i16(<4 x i32>)
declare <8 x i8> @llvm.aarch64.neon.uqxtn.v8i8(<8 x i16>)
declare <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float>, <4 x float>)
declare <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float>, <4 x float>)
declare <4 x i32> @llvm.fptoui.sat.v4i32.v4f32(<4 x float>)
