; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vabd_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabd_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vfsub.vv v8, v8, v9
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vabd2.i = tail call <4 x half> @llvm.aarch64.neon.fabd.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vabd2.i, ptr %out, align 2
  ret void
}

define void @vabd_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabd_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vfsub.vv v8, v8, v9
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vabd2.i = tail call <2 x float> @llvm.aarch64.neon.fabd.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vabd2.i, ptr %out, align 4
  ret void
}

define void @vabd_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabd_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    vfsub.vv v8, v8, v9
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vabd2.i = tail call <1 x double> @llvm.aarch64.neon.fabd.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x double> %vabd2.i, ptr %out, align 8
  ret void
}

define void @vabdq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabdq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vfsub.vv v8, v8, v9
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vabd2.i = tail call <8 x half> @llvm.aarch64.neon.fabd.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vabd2.i, ptr %out, align 2
  ret void
}

define void @vabdq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabdq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vfsub.vv v8, v8, v9
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vabd2.i = tail call <4 x float> @llvm.aarch64.neon.fabd.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vabd2.i, ptr %out, align 4
  ret void
}

define void @vabdq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabdq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    vfsub.vv v8, v8, v9
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vabd2.i = tail call <2 x double> @llvm.aarch64.neon.fabd.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vabd2.i, ptr %out, align 8
  ret void
}

declare <1 x double> @llvm.aarch64.neon.fabd.v1f64(<1 x double>, <1 x double>)
declare <2 x double> @llvm.aarch64.neon.fabd.v2f64(<2 x double>, <2 x double>)
declare <2 x float> @llvm.aarch64.neon.fabd.v2f32(<2 x float>, <2 x float>)
declare <4 x float> @llvm.aarch64.neon.fabd.v4f32(<4 x float>, <4 x float>)
declare <4 x half> @llvm.aarch64.neon.fabd.v4f16(<4 x half>, <4 x half>)
declare <8 x half> @llvm.aarch64.neon.fabd.v8f16(<8 x half>, <8 x half>)
