; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vabs_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabs_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vabs1.i = tail call <4 x i16> @llvm.aarch64.neon.abs.v4i16(<4 x i16> %0)
  store <4 x i16> %vabs1.i, ptr %out, align 2
  ret void
}

define void @vabs_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabs_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vabs1.i = tail call <2 x i32> @llvm.aarch64.neon.abs.v2i32(<2 x i32> %0)
  store <2 x i32> %vabs1.i, ptr %out, align 4
  ret void
}

define void @vabs_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabs_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vabs1.i = tail call <1 x i64> @llvm.aarch64.neon.abs.v1i64(<1 x i64> %0)
  store <1 x i64> %vabs1.i, ptr %out, align 8
  ret void
}

define void @vabs_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabs_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vabs.i = tail call <8 x i8> @llvm.aarch64.neon.abs.v8i8(<8 x i8> %0)
  store <8 x i8> %vabs.i, ptr %out, align 1
  ret void
}

define void @vabsd_s64(i64 noundef %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabsd_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srai a2, a0, 63
; CHECK-NEXT:    xor a0, a0, a2
; CHECK-NEXT:    sub a0, a0, a2
; CHECK-NEXT:    sd a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %vabsd_s64.i = tail call i64 @llvm.aarch64.neon.abs.i64(i64 %in_0)
  store i64 %vabsd_s64.i, ptr %out, align 8
  ret void
}

define void @vabsq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabsq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vabs1.i = tail call <8 x i16> @llvm.aarch64.neon.abs.v8i16(<8 x i16> %0)
  store <8 x i16> %vabs1.i, ptr %out, align 2
  ret void
}

define void @vabsq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabsq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vabs1.i = tail call <4 x i32> @llvm.aarch64.neon.abs.v4i32(<4 x i32> %0)
  store <4 x i32> %vabs1.i, ptr %out, align 4
  ret void
}

define void @vabsq_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabsq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vabs1.i = tail call <2 x i64> @llvm.aarch64.neon.abs.v2i64(<2 x i64> %0)
  store <2 x i64> %vabs1.i, ptr %out, align 8
  ret void
}

define void @vabsq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vabsq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vmax.vv v8, v8, v9
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vabs.i = tail call <16 x i8> @llvm.aarch64.neon.abs.v16i8(<16 x i8> %0)
  store <16 x i8> %vabs.i, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.abs.v1i64(<1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.abs.v16i8(<16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.abs.v2i32(<2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.abs.v2i64(<2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.abs.v4i16(<4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.abs.v4i32(<4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.abs.v8i16(<8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.abs.v8i8(<8 x i8>)
declare i64 @llvm.aarch64.neon.abs.i64(i64)
