; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vaddlv_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlv_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vwredsum.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.saddlv.i32.v4i16(<4 x i16> %0)
  store i32 %vaddlv.i, ptr %out, align 4
  ret void
}

define void @vaddlv_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlv_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vwredsum.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vaddlv_s32.i = tail call i64 @llvm.aarch64.neon.saddlv.i64.v2i32(<2 x i32> %0)
  store i64 %vaddlv_s32.i, ptr %out, align 8
  ret void
}

define void @vaddlv_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlv_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vsext.vf4 v8, v10
; CHECK-NEXT:    vmv.s.x v10, zero
; CHECK-NEXT:    vredsum.vs v8, v8, v10
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    sh a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.saddlv.i32.v8i8(<8 x i8> %0)
  %1 = trunc i32 %vaddlv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vaddlv_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlv_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vwredsumu.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.uaddlv.i32.v4i16(<4 x i16> %0)
  store i32 %vaddlv.i, ptr %out, align 4
  ret void
}

define void @vaddlv_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlv_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vwredsumu.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vaddlv_u32.i = tail call i64 @llvm.aarch64.neon.uaddlv.i64.v2i32(<2 x i32> %0)
  store i64 %vaddlv_u32.i, ptr %out, align 8
  ret void
}

define void @vaddlv_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlv_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vzext.vf4 v8, v10
; CHECK-NEXT:    vmv.s.x v10, zero
; CHECK-NEXT:    vredsum.vs v8, v8, v10
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    sh a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.uaddlv.i32.v8i8(<8 x i8> %0)
  %1 = trunc i32 %vaddlv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vaddlvq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlvq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vwredsum.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.saddlv.i32.v8i16(<8 x i16> %0)
  store i32 %vaddlv.i, ptr %out, align 4
  ret void
}

define void @vaddlvq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlvq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vwredsum.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vaddlvq_s32.i = tail call i64 @llvm.aarch64.neon.saddlv.i64.v4i32(<4 x i32> %0)
  store i64 %vaddlvq_s32.i, ptr %out, align 8
  ret void
}

define void @vaddlvq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlvq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vsext.vf4 v8, v11
; CHECK-NEXT:    vmv.s.x v12, zero
; CHECK-NEXT:    vredsum.vs v8, v8, v12
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    sh a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.saddlv.i32.v16i8(<16 x i8> %0)
  %1 = trunc i32 %vaddlv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vaddlvq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlvq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vwredsumu.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.uaddlv.i32.v8i16(<8 x i16> %0)
  store i32 %vaddlv.i, ptr %out, align 4
  ret void
}

define void @vaddlvq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlvq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vwredsumu.vs v8, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vaddlvq_u32.i = tail call i64 @llvm.aarch64.neon.uaddlv.i64.v4i32(<4 x i32> %0)
  store i64 %vaddlvq_u32.i, ptr %out, align 8
  ret void
}

define void @vaddlvq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddlvq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vzext.vf4 v8, v11
; CHECK-NEXT:    vmv.s.x v12, zero
; CHECK-NEXT:    vredsum.vs v8, v8, v12
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    sh a0, 0(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vaddlv.i = tail call i32 @llvm.aarch64.neon.uaddlv.i32.v16i8(<16 x i8> %0)
  %1 = trunc i32 %vaddlv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

declare i32 @llvm.aarch64.neon.saddlv.i32.v16i8(<16 x i8>)
declare i32 @llvm.aarch64.neon.saddlv.i32.v4i16(<4 x i16>)
declare i32 @llvm.aarch64.neon.saddlv.i32.v8i16(<8 x i16>)
declare i32 @llvm.aarch64.neon.saddlv.i32.v8i8(<8 x i8>)
declare i32 @llvm.aarch64.neon.uaddlv.i32.v16i8(<16 x i8>)
declare i32 @llvm.aarch64.neon.uaddlv.i32.v4i16(<4 x i16>)
declare i32 @llvm.aarch64.neon.uaddlv.i32.v8i16(<8 x i16>)
declare i32 @llvm.aarch64.neon.uaddlv.i32.v8i8(<8 x i8>)
declare i64 @llvm.aarch64.neon.saddlv.i64.v2i32(<2 x i32>)
declare i64 @llvm.aarch64.neon.saddlv.i64.v4i32(<4 x i32>)
declare i64 @llvm.aarch64.neon.uaddlv.i64.v2i32(<2 x i32>)
declare i64 @llvm.aarch64.neon.uaddlv.i64.v4i32(<4 x i32>)
