; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vaddv_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddv_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %vaddv_f32.i = tail call float @llvm.aarch64.neon.faddv.f32.v2f32(<2 x float> %0)
  store float %vaddv_f32.i, ptr %out, align 4
  ret void
}

define void @vaddvq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddvq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %vaddvq_f32.i = tail call float @llvm.aarch64.neon.faddv.f32.v4f32(<4 x float> %0)
  store float %vaddvq_f32.i, ptr %out, align 4
  ret void
}

define void @vaddvq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vaddvq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %vaddvq_f64.i = tail call double @llvm.aarch64.neon.faddv.f64.v2f64(<2 x double> %0)
  store double %vaddvq_f64.i, ptr %out, align 8
  ret void
}

declare double @llvm.aarch64.neon.faddv.f64.v2f64(<2 x double>)
declare float @llvm.aarch64.neon.faddv.f32.v2f32(<2 x float>)
declare float @llvm.aarch64.neon.faddv.f32.v4f32(<4 x float>)
