; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vcagt_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcagt_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vcagt_v2.i = tail call <4 x i16> @llvm.aarch64.neon.facgt.v4i16.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x i16> %vcagt_v2.i, ptr %out, align 2
  ret void
}

define void @vcagt_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcagt_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vcagt_v2.i = tail call <2 x i32> @llvm.aarch64.neon.facgt.v2i32.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x i32> %vcagt_v2.i, ptr %out, align 4
  ret void
}

define void @vcagt_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcagt_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vcagt_v2.i = tail call <1 x i64> @llvm.aarch64.neon.facgt.v1i64.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x i64> %vcagt_v2.i, ptr %out, align 8
  ret void
}

define void @vcagtq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcagtq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vcagtq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.facgt.v8i16.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x i16> %vcagtq_v2.i, ptr %out, align 2
  ret void
}

define void @vcagtq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcagtq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vcagtq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.facgt.v4i32.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x i32> %vcagtq_v2.i, ptr %out, align 4
  ret void
}

define void @vcagtq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcagtq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vcagtq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.facgt.v2i64.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x i64> %vcagtq_v2.i, ptr %out, align 8
  ret void
}

define void @vcalt_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcalt_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vcalt_v2.i = tail call <4 x i16> @llvm.aarch64.neon.facgt.v4i16.v4f16(<4 x half> %1, <4 x half> %0)
  store <4 x i16> %vcalt_v2.i, ptr %out, align 2
  ret void
}

define void @vcalt_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcalt_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vcalt_v2.i = tail call <2 x i32> @llvm.aarch64.neon.facgt.v2i32.v2f32(<2 x float> %1, <2 x float> %0)
  store <2 x i32> %vcalt_v2.i, ptr %out, align 4
  ret void
}

define void @vcalt_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcalt_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vcalt_v2.i = tail call <1 x i64> @llvm.aarch64.neon.facgt.v1i64.v1f64(<1 x double> %1, <1 x double> %0)
  store <1 x i64> %vcalt_v2.i, ptr %out, align 8
  ret void
}

define void @vcaltq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcaltq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vcaltq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.facgt.v8i16.v8f16(<8 x half> %1, <8 x half> %0)
  store <8 x i16> %vcaltq_v2.i, ptr %out, align 2
  ret void
}

define void @vcaltq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcaltq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vcaltq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.facgt.v4i32.v4f32(<4 x float> %1, <4 x float> %0)
  store <4 x i32> %vcaltq_v2.i, ptr %out, align 4
  ret void
}

define void @vcaltq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcaltq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vfabs.v v8, v8
; CHECK-NEXT:    vfabs.v v9, v9
; CHECK-NEXT:    vmflt.vv v0, v9, v8
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vmerge.vim v8, v8, -1, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vcaltq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.facgt.v2i64.v2f64(<2 x double> %1, <2 x double> %0)
  store <2 x i64> %vcaltq_v2.i, ptr %out, align 8
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.facgt.v1i64.v1f64(<1 x double>, <1 x double>)
declare <2 x i32> @llvm.aarch64.neon.facgt.v2i32.v2f32(<2 x float>, <2 x float>)
declare <2 x i64> @llvm.aarch64.neon.facgt.v2i64.v2f64(<2 x double>, <2 x double>)
declare <4 x i16> @llvm.aarch64.neon.facgt.v4i16.v4f16(<4 x half>, <4 x half>)
declare <4 x i32> @llvm.aarch64.neon.facgt.v4i32.v4f32(<4 x float>, <4 x float>)
declare <8 x i16> @llvm.aarch64.neon.facgt.v8i16.v8f16(<8 x half>, <8 x half>)
