; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vcvt_f32_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcvt_f32_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vfwcvt.f.f.v v9, v8
; CHECK-NEXT:    vse32.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vcvt_f32_f161.i = tail call <4 x float> @llvm.aarch64.neon.vcvthf2fp(<4 x i16> %0)
  store <4 x float> %vcvt_f32_f161.i, ptr %out, align 4
  ret void
}

define void @vcvt_high_f32_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vcvt_high_f32_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vfwcvt.f.f.v v9, v8
; CHECK-NEXT:    vse32.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %shuffle.i.i = shufflevector <8 x half> %0, <8 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %vcvt_f32_f16.i.i = bitcast <4 x half> %shuffle.i.i to <4 x i16>
  %vcvt_f32_f161.i.i = tail call <4 x float> @llvm.aarch64.neon.vcvthf2fp(<4 x i16> %vcvt_f32_f16.i.i)
  store <4 x float> %vcvt_f32_f161.i.i, ptr %out, align 4
  ret void
}

declare <4 x float> @llvm.aarch64.neon.vcvthf2fp(<4 x i16>)
