; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vdot_lane_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdot_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 1(a2)
; CHECK-NEXT:    lbu a1, 0(a2)
; CHECK-NEXT:    lbu a4, 2(a2)
; CHECK-NEXT:    lbu a2, 3(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmul.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wi v10, v11, 16
; CHECK-NEXT:    vwadd.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wx v10, v11, a1
; CHECK-NEXT:    vadd.vv v9, v9, v10
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <2 x i32>, ptr %in_2, align 1
  %lane = shufflevector <2 x i32> %2, <2 x i32> poison, <2 x i32> zeroinitializer
  %3 = bitcast <2 x i32> %lane to <8 x i8>
  %vdot1.i = tail call <2 x i32> @llvm.aarch64.neon.sdot.v2i32.v8i8(<2 x i32> %0, <8 x i8> %1, <8 x i8> %3)
  store <2 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdot_lane_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdot_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 1(a2)
; CHECK-NEXT:    lbu a1, 0(a2)
; CHECK-NEXT:    lbu a4, 2(a2)
; CHECK-NEXT:    lbu a2, 3(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wi v10, v11, 16
; CHECK-NEXT:    vwaddu.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wx v10, v11, a1
; CHECK-NEXT:    vadd.vv v9, v9, v10
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <2 x i32>, ptr %in_2, align 1
  %lane = shufflevector <2 x i32> %2, <2 x i32> poison, <2 x i32> zeroinitializer
  %3 = bitcast <2 x i32> %lane to <8 x i8>
  %vdot1.i = tail call <2 x i32> @llvm.aarch64.neon.udot.v2i32.v8i8(<2 x i32> %0, <8 x i8> %1, <8 x i8> %3)
  store <2 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdot_laneq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdot_laneq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 1(a2)
; CHECK-NEXT:    lbu a1, 0(a2)
; CHECK-NEXT:    lbu a4, 2(a2)
; CHECK-NEXT:    lbu a2, 3(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmul.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wi v10, v11, 16
; CHECK-NEXT:    vwadd.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wx v10, v11, a1
; CHECK-NEXT:    vadd.vv v9, v9, v10
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <4 x i32>, ptr %in_2, align 1
  %lane = shufflevector <4 x i32> %2, <4 x i32> poison, <2 x i32> zeroinitializer
  %3 = bitcast <2 x i32> %lane to <8 x i8>
  %vdot1.i = tail call <2 x i32> @llvm.aarch64.neon.sdot.v2i32.v8i8(<2 x i32> %0, <8 x i8> %1, <8 x i8> %3)
  store <2 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdot_laneq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdot_laneq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 9(a2)
; CHECK-NEXT:    lbu a1, 8(a2)
; CHECK-NEXT:    lbu a4, 10(a2)
; CHECK-NEXT:    lbu a2, 11(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wi v10, v11, 16
; CHECK-NEXT:    vwaddu.vv v11, v9, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v11, 0
; CHECK-NEXT:    vnsrl.wx v10, v11, a1
; CHECK-NEXT:    vadd.vv v9, v9, v10
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <4 x i32>, ptr %in_2, align 1
  %lane = shufflevector <4 x i32> %2, <4 x i32> poison, <2 x i32> <i32 2, i32 2>
  %3 = bitcast <2 x i32> %lane to <8 x i8>
  %vdot1.i = tail call <2 x i32> @llvm.aarch64.neon.udot.v2i32.v8i8(<2 x i32> %0, <8 x i8> %1, <8 x i8> %3)
  store <2 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdot_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdot_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a2)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmul.vv v11, v8, v9
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v11, 0
; CHECK-NEXT:    vnsrl.wi v9, v11, 16
; CHECK-NEXT:    vwadd.vv v11, v8, v9
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v11, 0
; CHECK-NEXT:    vnsrl.wx v9, v11, a0
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vdot1.i = tail call <2 x i32> @llvm.aarch64.neon.sdot.v2i32.v8i8(<2 x i32> %0, <8 x i8> %1, <8 x i8> %2)
  store <2 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdot_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdot_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a2)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vv v11, v8, v9
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v11, 0
; CHECK-NEXT:    vnsrl.wi v9, v11, 16
; CHECK-NEXT:    vwaddu.vv v11, v8, v9
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v11, 0
; CHECK-NEXT:    vnsrl.wx v9, v11, a0
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vdot1.i = tail call <2 x i32> @llvm.aarch64.neon.udot.v2i32.v8i8(<2 x i32> %0, <8 x i8> %1, <8 x i8> %2)
  store <2 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdotq_lane_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdotq_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 5(a2)
; CHECK-NEXT:    lbu a1, 4(a2)
; CHECK-NEXT:    lbu a4, 6(a2)
; CHECK-NEXT:    lbu a2, 7(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v11, a0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmul.vv v8, v9, v11
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wi v12, v8, 16
; CHECK-NEXT:    vwadd.vv v8, v11, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a1
; CHECK-NEXT:    vadd.vv v8, v11, v8
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <2 x i32>, ptr %in_2, align 1
  %lane = shufflevector <2 x i32> %2, <2 x i32> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  %3 = bitcast <4 x i32> %lane to <16 x i8>
  %vdot1.i = tail call <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32> %0, <16 x i8> %1, <16 x i8> %3)
  store <4 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdotq_lane_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdotq_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 1(a2)
; CHECK-NEXT:    lbu a1, 0(a2)
; CHECK-NEXT:    lbu a4, 2(a2)
; CHECK-NEXT:    lbu a2, 3(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v11, a0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmulu.vv v8, v9, v11
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wi v12, v8, 16
; CHECK-NEXT:    vwaddu.vv v8, v11, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a1
; CHECK-NEXT:    vadd.vv v8, v11, v8
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <2 x i32>, ptr %in_2, align 1
  %lane = shufflevector <2 x i32> %2, <2 x i32> poison, <4 x i32> zeroinitializer
  %3 = bitcast <4 x i32> %lane to <16 x i8>
  %vdot1.i = tail call <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %0, <16 x i8> %1, <16 x i8> %3)
  store <4 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdotq_laneq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdotq_laneq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 13(a2)
; CHECK-NEXT:    lbu a1, 12(a2)
; CHECK-NEXT:    lbu a4, 14(a2)
; CHECK-NEXT:    lbu a2, 15(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v11, a0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmul.vv v8, v9, v11
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wi v12, v8, 16
; CHECK-NEXT:    vwadd.vv v8, v11, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a1
; CHECK-NEXT:    vadd.vv v8, v11, v8
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <4 x i32>, ptr %in_2, align 1
  %lane = shufflevector <4 x i32> %2, <4 x i32> poison, <4 x i32> <i32 3, i32 3, i32 3, i32 3>
  %3 = bitcast <4 x i32> %lane to <16 x i8>
  %vdot1.i = tail call <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32> %0, <16 x i8> %1, <16 x i8> %3)
  store <4 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdotq_laneq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdotq_laneq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    lbu a0, 1(a2)
; CHECK-NEXT:    lbu a1, 0(a2)
; CHECK-NEXT:    lbu a4, 2(a2)
; CHECK-NEXT:    lbu a2, 3(a2)
; CHECK-NEXT:    slli a0, a0, 8
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a2, a2, 24
; CHECK-NEXT:    or a2, a2, a4
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    or a0, a2, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v11, a0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmulu.vv v8, v9, v11
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wi v12, v8, 16
; CHECK-NEXT:    vwaddu.vv v8, v11, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v8, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a1
; CHECK-NEXT:    vadd.vv v8, v11, v8
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <4 x i32>, ptr %in_2, align 1
  %lane = shufflevector <4 x i32> %2, <4 x i32> poison, <4 x i32> zeroinitializer
  %3 = bitcast <4 x i32> %lane to <16 x i8>
  %vdot1.i = tail call <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %0, <16 x i8> %1, <16 x i8> %3)
  store <4 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdotq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdotq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v11, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmul.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v12, v8, 16
; CHECK-NEXT:    vwadd.vv v8, v10, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vadd.vv v8, v11, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <16 x i8>, ptr %in_2, align 1
  %vdot1.i = tail call <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32> %0, <16 x i8> %1, <16 x i8> %2)
  store <4 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

define void @vdotq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vdotq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v11, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmulu.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v12, v8, 16
; CHECK-NEXT:    vwaddu.vv v8, v10, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    vadd.vv v8, v10, v8
; CHECK-NEXT:    vadd.vv v8, v11, v8
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <16 x i8>, ptr %in_2, align 1
  %vdot1.i = tail call <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %0, <16 x i8> %1, <16 x i8> %2)
  store <4 x i32> %vdot1.i, ptr %out, align 4
  ret void
}

declare <2 x i32> @llvm.aarch64.neon.sdot.v2i32.v8i8(<2 x i32>, <8 x i8>, <8 x i8>)
declare <2 x i32> @llvm.aarch64.neon.udot.v2i32.v8i8(<2 x i32>, <8 x i8>, <8 x i8>)
declare <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32>, <16 x i8>, <16 x i8>)
declare <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32>, <16 x i8>, <16 x i8>)
