; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vld1_f16_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x2.v4f16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4f16.p0(<4 x half> %vld1xN.fca.0.extract, <4 x half> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_f16_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x3.v4f16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4f16.p0(<4 x half> %vld1xN.fca.0.extract, <4 x half> %vld1xN.fca.1.extract, <4 x half> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_f16_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x4.v4f16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4f16.p0(<4 x half> %vld1xN.fca.0.extract, <4 x half> %vld1xN.fca.1.extract, <4 x half> %vld1xN.fca.2.extract, <4 x half> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_f32_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x2.v2f32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2f32.p0(<2 x float> %vld1xN.fca.0.extract, <2 x float> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_f32_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x3.v2f32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2f32.p0(<2 x float> %vld1xN.fca.0.extract, <2 x float> %vld1xN.fca.1.extract, <2 x float> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_f32_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x4.v2f32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2f32.p0(<2 x float> %vld1xN.fca.0.extract, <2 x float> %vld1xN.fca.1.extract, <2 x float> %vld1xN.fca.2.extract, <2 x float> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_f64_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x2.v1f64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v1f64.p0(<1 x double> %vld1xN.fca.0.extract, <1 x double> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_f64_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 3, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x3.v1f64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v1f64.p0(<1 x double> %vld1xN.fca.0.extract, <1 x double> %vld1xN.fca.1.extract, <1 x double> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_f64_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_f64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x4.v1f64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v1f64.p0(<1 x double> %vld1xN.fca.0.extract, <1 x double> %vld1xN.fca.1.extract, <1 x double> %vld1xN.fca.2.extract, <1 x double> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_s16_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x2.v4i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_s16_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x3.v4i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_s16_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x4.v4i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, <4 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_s32_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x2.v2i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_s32_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x3.v2i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_s32_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x4.v2i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, <2 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_s64_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x2.v1i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_s64_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 3, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x3.v1i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_s64_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x4.v1i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, <1 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_s8_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_s8_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x3.v8i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_s8_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_s8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, <8 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_u16_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x2.v4i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_u16_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x3.v4i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_u16_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x4.v4i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, <4 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_u32_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x2.v2i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_u32_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x3.v2i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_u32_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x4.v2i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, <2 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_u64_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x2.v1i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_u64_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 3, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x3.v1i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_u64_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x4.v1i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, <1 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1_u8_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1_u8_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x3.v8i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1_u8_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1_u8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, <8 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_f16_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x2.v8f16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8f16.p0(<8 x half> %vld1xN.fca.0.extract, <8 x half> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_f16_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x3.v8f16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8f16.p0(<8 x half> %vld1xN.fca.0.extract, <8 x half> %vld1xN.fca.1.extract, <8 x half> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_f16_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x4.v8f16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8f16.p0(<8 x half> %vld1xN.fca.0.extract, <8 x half> %vld1xN.fca.1.extract, <8 x half> %vld1xN.fca.2.extract, <8 x half> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_f32_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x2.v4f32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4f32.p0(<4 x float> %vld1xN.fca.0.extract, <4 x float> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_f32_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x3.v4f32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4f32.p0(<4 x float> %vld1xN.fca.0.extract, <4 x float> %vld1xN.fca.1.extract, <4 x float> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_f32_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x4.v4f32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4f32.p0(<4 x float> %vld1xN.fca.0.extract, <4 x float> %vld1xN.fca.1.extract, <4 x float> %vld1xN.fca.2.extract, <4 x float> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_f64_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x2.v2f64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2f64.p0(<2 x double> %vld1xN.fca.0.extract, <2 x double> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_f64_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x3.v2f64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2f64.p0(<2 x double> %vld1xN.fca.0.extract, <2 x double> %vld1xN.fca.1.extract, <2 x double> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_f64_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_f64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x4.v2f64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2f64.p0(<2 x double> %vld1xN.fca.0.extract, <2 x double> %vld1xN.fca.1.extract, <2 x double> %vld1xN.fca.2.extract, <2 x double> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_s16_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x2.v8i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_s16_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x3.v8i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_s16_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x4.v8i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, <8 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_s32_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x2.v4i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_s32_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x3.v4i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_s32_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x4.v4i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, <4 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_s64_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x2.v2i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_s64_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x3.v2i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_s64_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x4.v2i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, <2 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_s8_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_s8_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 48
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_s8_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_s8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 64
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, <16 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_u16_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x2.v8i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_u16_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x3.v8i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_u16_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x4.v8i16.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, <8 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_u32_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x2.v4i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_u32_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x3.v4i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_u32_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x4.v4i32.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, <4 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_u64_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x2.v2i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_u64_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x3.v2i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_u64_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x4.v2i64.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, <2 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vld1q_u8_x2(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vld1q_u8_x3(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 48
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vld1q_u8_x4(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld1q_u8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 64
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_0)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, <16 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_f16_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x2.v4f16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4f16.p0(<4 x half> %vld1xN.fca.0.extract, <4 x half> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_f16_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x3.v4f16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4f16.p0(<4 x half> %vld1xN.fca.0.extract, <4 x half> %vld1xN.fca.1.extract, <4 x half> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_f16_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x4.v4f16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4f16.p0(<4 x half> %vld1xN.fca.0.extract, <4 x half> %vld1xN.fca.1.extract, <4 x half> %vld1xN.fca.2.extract, <4 x half> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_f32_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x2.v2f32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2f32.p0(<2 x float> %vld1xN.fca.0.extract, <2 x float> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_f32_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x3.v2f32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2f32.p0(<2 x float> %vld1xN.fca.0.extract, <2 x float> %vld1xN.fca.1.extract, <2 x float> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_f32_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x4.v2f32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2f32.p0(<2 x float> %vld1xN.fca.0.extract, <2 x float> %vld1xN.fca.1.extract, <2 x float> %vld1xN.fca.2.extract, <2 x float> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_f64_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x2.v1f64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v1f64.p0(<1 x double> %vld1xN.fca.0.extract, <1 x double> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_f64_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 3, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x3.v1f64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v1f64.p0(<1 x double> %vld1xN.fca.0.extract, <1 x double> %vld1xN.fca.1.extract, <1 x double> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_f64_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_f64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x4.v1f64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v1f64.p0(<1 x double> %vld1xN.fca.0.extract, <1 x double> %vld1xN.fca.1.extract, <1 x double> %vld1xN.fca.2.extract, <1 x double> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_s16_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x2.v4i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_s16_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x3.v4i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_s16_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x4.v4i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, <4 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_s32_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x2.v2i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_s32_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x3.v2i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_s32_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x4.v2i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, <2 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_s64_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x2.v1i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_s64_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 3, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x3.v1i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_s64_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x4.v1i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, <1 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_s8_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_s8_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x3.v8i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_s8_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_s8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, <8 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_u16_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x2.v4i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_u16_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x3.v4i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_u16_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x4.v4i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i16.p0(<4 x i16> %vld1xN.fca.0.extract, <4 x i16> %vld1xN.fca.1.extract, <4 x i16> %vld1xN.fca.2.extract, <4 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_u32_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x2.v2i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_u32_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x3.v2i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_u32_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x4.v2i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i32.p0(<2 x i32> %vld1xN.fca.0.extract, <2 x i32> %vld1xN.fca.1.extract, <2 x i32> %vld1xN.fca.2.extract, <2 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_u64_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x2.v1i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_u64_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 3, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x3.v1i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_u64_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x4.v1i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v1i64.p0(<1 x i64> %vld1xN.fca.0.extract, <1 x i64> %vld1xN.fca.1.extract, <1 x i64> %vld1xN.fca.2.extract, <1 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1_u8_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1_u8_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x3.v8i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1_u8_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1_u8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i8.p0(<8 x i8> %vld1xN.fca.0.extract, <8 x i8> %vld1xN.fca.1.extract, <8 x i8> %vld1xN.fca.2.extract, <8 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_f16_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x2.v8f16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8f16.p0(<8 x half> %vld1xN.fca.0.extract, <8 x half> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_f16_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x3.v8f16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8f16.p0(<8 x half> %vld1xN.fca.0.extract, <8 x half> %vld1xN.fca.1.extract, <8 x half> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_f16_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x4.v8f16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8f16.p0(<8 x half> %vld1xN.fca.0.extract, <8 x half> %vld1xN.fca.1.extract, <8 x half> %vld1xN.fca.2.extract, <8 x half> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_f32_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x2.v4f32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4f32.p0(<4 x float> %vld1xN.fca.0.extract, <4 x float> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_f32_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x3.v4f32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4f32.p0(<4 x float> %vld1xN.fca.0.extract, <4 x float> %vld1xN.fca.1.extract, <4 x float> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_f32_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x4.v4f32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4f32.p0(<4 x float> %vld1xN.fca.0.extract, <4 x float> %vld1xN.fca.1.extract, <4 x float> %vld1xN.fca.2.extract, <4 x float> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_f64_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x2.v2f64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2f64.p0(<2 x double> %vld1xN.fca.0.extract, <2 x double> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_f64_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x3.v2f64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2f64.p0(<2 x double> %vld1xN.fca.0.extract, <2 x double> %vld1xN.fca.1.extract, <2 x double> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_f64_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_f64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x4.v2f64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2f64.p0(<2 x double> %vld1xN.fca.0.extract, <2 x double> %vld1xN.fca.1.extract, <2 x double> %vld1xN.fca.2.extract, <2 x double> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_s16_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x2.v8i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_s16_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x3.v8i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_s16_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x4.v8i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, <8 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_s32_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x2.v4i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_s32_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x3.v4i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_s32_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x4.v4i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, <4 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_s64_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x2.v2i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_s64_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x3.v2i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_s64_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x4.v2i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, <2 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_s8_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_s8_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 48
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_s8_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_s8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 64
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, <16 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_u16_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u16_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x2.v8i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_u16_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u16_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x3.v8i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_u16_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u16_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x4.v8i16.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v8i16.p0(<8 x i16> %vld1xN.fca.0.extract, <8 x i16> %vld1xN.fca.1.extract, <8 x i16> %vld1xN.fca.2.extract, <8 x i16> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_u32_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u32_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x2.v4i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_u32_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u32_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 12, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x3.v4i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_u32_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u32_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x4.v4i32.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v4i32.p0(<4 x i32> %vld1xN.fca.0.extract, <4 x i32> %vld1xN.fca.1.extract, <4 x i32> %vld1xN.fca.2.extract, <4 x i32> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_u64_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u64_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x2.v2i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_u64_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u64_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 6, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x3.v2i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_u64_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u64_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x4.v2i64.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v2i64.p0(<2 x i64> %vld1xN.fca.0.extract, <2 x i64> %vld1xN.fca.1.extract, <2 x i64> %vld1xN.fca.2.extract, <2 x i64> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

define void @vst1q_u8_x2(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u8_x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld1xN, 1
  tail call void @llvm.aarch64.neon.st1x2.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, ptr %out)
  ret void
}

define void @vst1q_u8_x3(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u8_x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 48
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  tail call void @llvm.aarch64.neon.st1x3.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, ptr %out)
  ret void
}

define void @vst1q_u8_x4(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst1q_u8_x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 64
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld1xN = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_1)
  %vld1xN.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 0
  %vld1xN.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 1
  %vld1xN.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 2
  %vld1xN.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld1xN, 3
  tail call void @llvm.aarch64.neon.st1x4.v16i8.p0(<16 x i8> %vld1xN.fca.0.extract, <16 x i8> %vld1xN.fca.1.extract, <16 x i8> %vld1xN.fca.2.extract, <16 x i8> %vld1xN.fca.3.extract, ptr %out)
  ret void
}

declare void @llvm.aarch64.neon.st1x2.v16i8.p0(<16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v1f64.p0(<1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v1i64.p0(<1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v2f32.p0(<2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v2f64.p0(<2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v2i32.p0(<2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v2i64.p0(<2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v4f16.p0(<4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v4f32.p0(<4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v4i16.p0(<4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v4i32.p0(<4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v8f16.p0(<8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v8i16.p0(<8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x2.v8i8.p0(<8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x3.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st1x4.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x2.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x3.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld1x4.v1f64.p0(ptr)
declare { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x2.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x3.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld1x4.v1i64.p0(ptr)
declare { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr)
declare { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x2.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x3.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld1x4.v2f64.p0(ptr)
declare { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x2.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x3.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld1x4.v2f32.p0(ptr)
declare { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x2.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x3.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld1x4.v2i32.p0(ptr)
declare { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x2.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x3.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld1x4.v2i64.p0(ptr)
declare { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x2.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x3.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld1x4.v4f32.p0(ptr)
declare { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x2.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x3.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld1x4.v4f16.p0(ptr)
declare { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x2.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x3.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld1x4.v4i16.p0(ptr)
declare { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x2.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x3.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld1x4.v4i32.p0(ptr)
declare { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x2.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x3.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld1x4.v8f16.p0(ptr)
declare { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x2.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x3.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld1x4.v8i16.p0(ptr)
declare { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x3.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr)
