; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vld2_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2.v4f16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vld2.fca.0.extract, <4 x half> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2.v2f32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vld2.fca.0.extract, <2 x float> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2.v1f64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double> %vld2.fca.0.extract, <1 x double> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a0)
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a0)
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2.v8f16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vld2.fca.0.extract, <8 x half> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2.v4f32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vld2.fca.0.extract, <4 x float> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2.v2f64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double> %vld2.fca.0.extract, <2 x double> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a0)
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a0)
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a0)
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a0)
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld3_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a0)
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3.v4f16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half> %vld3.fca.0.extract, <4 x half> %vld3.fca.1.extract, <4 x half> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a0)
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3.v2f32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float> %vld3.fca.0.extract, <2 x float> %vld3.fca.1.extract, <2 x float> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a0)
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3.v1f64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double> %vld3.fca.0.extract, <1 x double> %vld3.fca.1.extract, <1 x double> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a0)
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a0)
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a0)
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a0)
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a0)
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a0)
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a0)
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a0)
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a0)
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3.v8f16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half> %vld3.fca.0.extract, <8 x half> %vld3.fca.1.extract, <8 x half> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a0)
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3.v4f32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float> %vld3.fca.0.extract, <4 x float> %vld3.fca.1.extract, <4 x float> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a0)
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3.v2f64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double> %vld3.fca.0.extract, <2 x double> %vld3.fca.1.extract, <2 x double> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a0)
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a0)
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a0)
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a0)
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a0)
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a0)
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a0)
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a0)
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld4_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a0)
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4.v4f16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half> %vld4.fca.0.extract, <4 x half> %vld4.fca.1.extract, <4 x half> %vld4.fca.2.extract, <4 x half> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a0)
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4.v2f32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float> %vld4.fca.0.extract, <2 x float> %vld4.fca.1.extract, <2 x float> %vld4.fca.2.extract, <2 x float> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a0)
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4.v1f64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double> %vld4.fca.0.extract, <1 x double> %vld4.fca.1.extract, <1 x double> %vld4.fca.2.extract, <1 x double> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a0)
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a0)
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a0)
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a0)
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a0)
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a0)
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a0)
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a0)
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a0)
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4.v8f16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half> %vld4.fca.0.extract, <8 x half> %vld4.fca.1.extract, <8 x half> %vld4.fca.2.extract, <8 x half> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a0)
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4.v4f32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float> %vld4.fca.0.extract, <4 x float> %vld4.fca.1.extract, <4 x float> %vld4.fca.2.extract, <4 x float> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a0)
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4.v2f64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double> %vld4.fca.0.extract, <2 x double> %vld4.fca.1.extract, <2 x double> %vld4.fca.2.extract, <2 x double> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a0)
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a0)
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a0)
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a0)
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a0)
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a0)
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a0)
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a0)
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst2_f16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2.v4f16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vld2.fca.0.extract, <4 x half> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_f32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2.v2f32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vld2.fca.0.extract, <2 x float> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_f64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2.v1f64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double> %vld2.fca.0.extract, <1 x double> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_s16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_s32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_s64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_s8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsseg2e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_u16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_u32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_u64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2_u8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsseg2e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_f16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2.v8f16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vld2.fca.0.extract, <8 x half> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_f32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2.v4f32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vld2.fca.0.extract, <4 x float> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_f64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2.v2f64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double> %vld2.fca.0.extract, <2 x double> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_s16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_s32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_s64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_s8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsseg2e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_u16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsseg2e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_u32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsseg2e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_u64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsseg2e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst2q_u8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst2q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsseg2e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vst3_f16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsseg3e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3.v4f16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half> %vld3.fca.0.extract, <4 x half> %vld3.fca.1.extract, <4 x half> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_f32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsseg3e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3.v2f32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float> %vld3.fca.0.extract, <2 x float> %vld3.fca.1.extract, <2 x float> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_f64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    vsseg3e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3.v1f64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double> %vld3.fca.0.extract, <1 x double> %vld3.fca.1.extract, <1 x double> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_s16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsseg3e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_s32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsseg3e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_s64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    vsseg3e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_s8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsseg3e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_u16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsseg3e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_u32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsseg3e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_u64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    vsseg3e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3_u8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsseg3e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_f16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsseg3e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3.v8f16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half> %vld3.fca.0.extract, <8 x half> %vld3.fca.1.extract, <8 x half> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_f32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsseg3e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3.v4f32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float> %vld3.fca.0.extract, <4 x float> %vld3.fca.1.extract, <4 x float> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_f64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    vsseg3e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3.v2f64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double> %vld3.fca.0.extract, <2 x double> %vld3.fca.1.extract, <2 x double> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_s16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsseg3e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_s32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsseg3e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_s64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    vsseg3e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_s8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsseg3e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_u16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsseg3e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_u32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsseg3e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_u64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    vsseg3e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst3q_u8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst3q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsseg3e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vst4_f16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsseg4e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4.v4f16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half> %vld4.fca.0.extract, <4 x half> %vld4.fca.1.extract, <4 x half> %vld4.fca.2.extract, <4 x half> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_f32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsseg4e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4.v2f32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float> %vld4.fca.0.extract, <2 x float> %vld4.fca.1.extract, <2 x float> %vld4.fca.2.extract, <2 x float> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_f64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    vsseg4e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4.v1f64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double> %vld4.fca.0.extract, <1 x double> %vld4.fca.1.extract, <1 x double> %vld4.fca.2.extract, <1 x double> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_s16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsseg4e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_s32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsseg4e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_s64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    vsseg4e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_s8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsseg4e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_u16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsseg4e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_u32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsseg4e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_u64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    vsseg4e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4_u8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsseg4e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_f16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsseg4e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4.v8f16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half> %vld4.fca.0.extract, <8 x half> %vld4.fca.1.extract, <8 x half> %vld4.fca.2.extract, <8 x half> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_f32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsseg4e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4.v4f32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float> %vld4.fca.0.extract, <4 x float> %vld4.fca.1.extract, <4 x float> %vld4.fca.2.extract, <4 x float> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_f64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    vsseg4e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4.v2f64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double> %vld4.fca.0.extract, <2 x double> %vld4.fca.1.extract, <2 x double> %vld4.fca.2.extract, <2 x double> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_s16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsseg4e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_s32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsseg4e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_s64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    vsseg4e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_s8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsseg4e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_u16(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsseg4e16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_u32(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsseg4e32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_u64(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    vsseg4e64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vst4q_u8(ptr nocapture noundef %out, ptr noundef %in_1) {
; CHECK-LABEL: vst4q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsseg4e8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vtrn_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vslideup.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 5
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vtrn.i = shufflevector <4 x half> %0, <4 x half> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>
  %vtrn1.i = shufflevector <4 x half> %0, <4 x half> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vtrn.i, <4 x half> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vtrn.i = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 0, i32 2>
  %vtrn1.i = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vtrn.i, <2 x float> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vslideup.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 5
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vtrn.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>
  %vtrn1.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vtrn.i, <4 x i16> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vtrn.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 0, i32 2>
  %vtrn1.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vtrn.i, <2 x i32> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 170
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    li a0, 85
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vslideup.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vsseg2e8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vtrn.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>
  %vtrn1.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vtrn.i, <8 x i8> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vslideup.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 5
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vtrn.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>
  %vtrn1.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vtrn.i, <4 x i16> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vtrn.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 0, i32 2>
  %vtrn1.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vtrn.i, <2 x i32> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrn_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrn_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 170
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    li a0, 85
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vslideup.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vsseg2e8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vtrn.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>
  %vtrn1.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vtrn.i, <8 x i8> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    li a0, 170
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    li a0, 85
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vtrn.i = shufflevector <8 x half> %0, <8 x half> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>
  %vtrn1.i = shufflevector <8 x half> %0, <8 x half> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vtrn.i, <8 x half> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 5
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vtrn.i = shufflevector <4 x float> %0, <4 x float> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>
  %vtrn1.i = shufflevector <4 x float> %0, <4 x float> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vtrn.i, <4 x float> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    li a0, 170
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    li a0, 85
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vtrn.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>
  %vtrn1.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vtrn.i, <8 x i16> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 5
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vtrn.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>
  %vtrn1.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vtrn.i, <4 x i32> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    lui a0, 11
; CHECK-NEXT:    lui a1, 5
; CHECK-NEXT:    addi a0, a0, -1366
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    addi a0, a1, 1365
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vtrn.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 0, i32 16, i32 2, i32 18, i32 4, i32 20, i32 6, i32 22, i32 8, i32 24, i32 10, i32 26, i32 12, i32 28, i32 14, i32 30>
  %vtrn1.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 1, i32 17, i32 3, i32 19, i32 5, i32 21, i32 7, i32 23, i32 9, i32 25, i32 11, i32 27, i32 13, i32 29, i32 15, i32 31>
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vtrn.i, <16 x i8> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    li a0, 170
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    li a0, 85
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vtrn.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 0, i32 8, i32 2, i32 10, i32 4, i32 12, i32 6, i32 14>
  %vtrn1.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 1, i32 9, i32 3, i32 11, i32 5, i32 13, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vtrn.i, <8 x i16> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 5
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vtrn.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 0, i32 4, i32 2, i32 6>
  %vtrn1.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 1, i32 5, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vtrn.i, <4 x i32> %vtrn1.i, ptr %out)
  ret void
}

define void @vtrnq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vtrnq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    lui a0, 11
; CHECK-NEXT:    lui a1, 5
; CHECK-NEXT:    addi a0, a0, -1366
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    addi a0, a1, 1365
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v10, 1, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v9, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vtrn.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 0, i32 16, i32 2, i32 18, i32 4, i32 20, i32 6, i32 22, i32 8, i32 24, i32 10, i32 26, i32 12, i32 28, i32 14, i32 30>
  %vtrn1.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 1, i32 17, i32 3, i32 19, i32 5, i32 21, i32 7, i32 23, i32 9, i32 25, i32 11, i32 27, i32 13, i32 29, i32 15, i32 31>
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vtrn.i, <16 x i8> %vtrn1.i, ptr %out)
  ret void
}

define void @vuzp_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v12, v9, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v12, v8, 2
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vuzp.i = shufflevector <4 x half> %0, <4 x half> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %vuzp1.i = shufflevector <4 x half> %0, <4 x half> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vuzp.i, <4 x half> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vuzp.i = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 0, i32 2>
  %vuzp1.i = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vuzp.i, <2 x float> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v12, v9, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v12, v8, 2
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vuzp.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %vuzp1.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vuzp.i, <4 x i16> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vuzp.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 0, i32 2>
  %vuzp1.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vuzp.i, <2 x i32> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 4
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 8
; CHECK-NEXT:    vnsrl.wi v12, v9, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vsseg2e8.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vuzp.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %vuzp1.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vuzp.i, <8 x i8> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v12, v9, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v12, v8, 2
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vuzp.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %vuzp1.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vuzp.i, <4 x i16> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vuzp.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 0, i32 2>
  %vuzp1.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vuzp.i, <2 x i32> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzp_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzp_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 4
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 8
; CHECK-NEXT:    vnsrl.wi v12, v9, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vsseg2e8.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vuzp.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %vuzp1.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vuzp.i, <8 x i8> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vnsrl.wi v10, v10, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 4
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vuzp.i = shufflevector <8 x half> %0, <8 x half> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %vuzp1.i = shufflevector <8 x half> %0, <8 x half> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vuzp.i, <8 x half> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 2
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wx v9, v9, a0
; CHECK-NEXT:    vnsrl.wx v10, v10, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 2
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vuzp.i = shufflevector <4 x float> %0, <4 x float> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %vuzp1.i = shufflevector <4 x float> %0, <4 x float> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vuzp.i, <4 x float> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vnsrl.wi v10, v10, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 4
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vuzp.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %vuzp1.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vuzp.i, <8 x i16> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 2
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wx v9, v9, a0
; CHECK-NEXT:    vnsrl.wx v10, v10, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 2
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vuzp.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %vuzp1.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vuzp.i, <4 x i32> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v9, 8
; CHECK-NEXT:    vnsrl.wi v10, v10, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vuzp.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %vuzp1.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vuzp.i, <16 x i8> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vnsrl.wi v10, v10, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 4
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vuzp.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %vuzp1.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vuzp.i, <8 x i16> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 2
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wx v9, v9, a0
; CHECK-NEXT:    vnsrl.wx v10, v10, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 2
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vuzp.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 0, i32 2, i32 4, i32 6>
  %vuzp1.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 1, i32 3, i32 5, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vuzp.i, <4 x i32> %vuzp1.i, ptr %out)
  ret void
}

define void @vuzpq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vuzpq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v10, 0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v9, v9, 8
; CHECK-NEXT:    vnsrl.wi v10, v10, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v10, v9, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vuzp.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 16, i32 18, i32 20, i32 22, i32 24, i32 26, i32 28, i32 30>
  %vuzp1.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 17, i32 19, i32 21, i32 23, i32 25, i32 27, i32 29, i32 31>
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vuzp.i, <16 x i8> %vuzp1.i, ptr %out)
  ret void
}

define void @vzip_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v8, v9
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 2
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwmaccu.vx v10, a0, v9
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 2
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vmerge.vvm v11, v11, v8, v0
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vzip.i = shufflevector <4 x half> %0, <4 x half> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %vzip1.i = shufflevector <4 x half> %0, <4 x half> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vzip.i, <4 x half> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vzip.i = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 0, i32 2>
  %vzip1.i = shufflevector <2 x float> %0, <2 x float> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vzip.i, <2 x float> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v8, v9
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 2
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwmaccu.vx v10, a0, v9
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 2
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vmerge.vvm v11, v11, v8, v0
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vzip.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %vzip1.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vzip.i, <4 x i16> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vzip.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 0, i32 2>
  %vzip1.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vzip.i, <2 x i32> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 170
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v8, v9
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vwmaccu.vx v10, a0, v9
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmerge.vvm v11, v11, v8, v0
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vsseg2e8.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vzip.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
  %vzip1.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vzip.i, <8 x i8> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v8, v9
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 2
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwmaccu.vx v10, a0, v9
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 2
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vmerge.vvm v11, v11, v8, v0
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vsseg2e16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vzip.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %vzip1.i = shufflevector <4 x i16> %0, <4 x i16> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vzip.i, <4 x i16> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vslideup.vi v9, v10, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vsseg2e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vzip.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 0, i32 2>
  %vzip1.i = shufflevector <2 x i32> %0, <2 x i32> %1, <2 x i32> <i32 1, i32 3>
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vzip.i, <2 x i32> %vzip1.i, ptr %out)
  ret void
}

define void @vzip_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzip_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 170
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vwaddu.vv v10, v8, v9
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vwmaccu.vx v10, a0, v9
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmerge.vvm v11, v11, v8, v0
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vsseg2e8.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vzip.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
  %vzip1.i = shufflevector <8 x i8> %0, <8 x i8> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vzip.i, <8 x i8> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 170
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 4
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    vsll.vi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v9, v0
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vzip.i = shufflevector <8 x half> %0, <8 x half> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
  %vzip1.i = shufflevector <8 x half> %0, <8 x half> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vzip.i, <8 x half> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 2
; CHECK-NEXT:    vslidedown.vi v9, v9, 2
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v10
; CHECK-NEXT:    vsll.vx v10, v11, a1
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v10, v0
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vzip.i = shufflevector <4 x float> %0, <4 x float> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %vzip1.i = shufflevector <4 x float> %0, <4 x float> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vzip.i, <4 x float> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 170
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 4
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    vsll.vi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v9, v0
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vzip.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
  %vzip1.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vzip.i, <8 x i16> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 2
; CHECK-NEXT:    vslidedown.vi v9, v9, 2
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v10
; CHECK-NEXT:    vsll.vx v10, v11, a1
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v10, v0
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vzip.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %vzip1.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vzip.i, <4 x i32> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    lui a1, 11
; CHECK-NEXT:    addi a1, a1, -1366
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 8
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    vsll.vi v9, v9, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v9, v0
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vzip.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 0, i32 16, i32 1, i32 17, i32 2, i32 18, i32 3, i32 19, i32 4, i32 20, i32 5, i32 21, i32 6, i32 22, i32 7, i32 23>
  %vzip1.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vzip.i, <16 x i8> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 170
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 4
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 4
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    vsll.vi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v9, v0
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vzip.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 0, i32 8, i32 1, i32 9, i32 2, i32 10, i32 3, i32 11>
  %vzip1.i = shufflevector <8 x i16> %0, <8 x i16> %1, <8 x i32> <i32 4, i32 12, i32 5, i32 13, i32 6, i32 14, i32 7, i32 15>
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vzip.i, <8 x i16> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vmv.v.i v0, 10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 2
; CHECK-NEXT:    vslidedown.vi v9, v9, 2
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v10
; CHECK-NEXT:    vsll.vx v10, v11, a1
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v10, v0
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vzip.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  %vzip1.i = shufflevector <4 x i32> %0, <4 x i32> %1, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vzip.i, <4 x i32> %vzip1.i, ptr %out)
  ret void
}

define void @vzipq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vzipq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    lui a1, 11
; CHECK-NEXT:    addi a1, a1, -1366
; CHECK-NEXT:    vmv.s.x v0, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwaddu.vv v8, v9, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmaccu.vx v8, a0, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v10, 8
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    vsll.vi v9, v9, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v10, v11, v9, v0
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vzip.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 0, i32 16, i32 1, i32 17, i32 2, i32 18, i32 3, i32 19, i32 4, i32 20, i32 5, i32 21, i32 6, i32 22, i32 7, i32 23>
  %vzip1.i = shufflevector <16 x i8> %0, <16 x i8> %1, <16 x i32> <i32 8, i32 24, i32 9, i32 25, i32 10, i32 26, i32 11, i32 27, i32 12, i32 28, i32 13, i32 29, i32 14, i32 30, i32 15, i32 31>
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vzip.i, <16 x i8> %vzip1.i, ptr %out)
  ret void
}

declare void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4.v1f64.p0(ptr)
declare { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr)
declare { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr)
declare { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4.v2f64.p0(ptr)
declare { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4.v2f32.p0(ptr)
declare { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr)
declare { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr)
declare { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4.v4f32.p0(ptr)
declare { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4.v4f16.p0(ptr)
declare { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr)
declare { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr)
declare { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4.v8f16.p0(ptr)
declare { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr)
declare { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr)
