; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vld2_lane_f16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2.v4f16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 1
  %vld2_lane = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2lane.v4f16.p0(<4 x half> %vld2.fca.0.extract, <4 x half> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vld2_lane.fca.0.extract, <4 x half> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_f32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v10, v9
; CHECK-NEXT:    vmv1r.v v9, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2.v2f32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 1
  %vld2_lane = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2lane.v2f32.p0(<2 x float> %vld2.fca.0.extract, <2 x float> %vld2.fca.1.extract, i64 1, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vld2_lane.fca.0.extract, <2 x float> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_f64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsseg2e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2.v1f64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 1
  %vld2_lane = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2lane.v1f64.p0(<1 x double> %vld2.fca.0.extract, <1 x double> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double> %vld2_lane.fca.0.extract, <1 x double> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_s16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  %vld2_lane = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2lane.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2_lane.fca.0.extract, <4 x i16> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_s32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  %vld2_lane = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2lane.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2_lane.fca.0.extract, <2 x i32> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_s64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsseg2e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  %vld2_lane = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2lane.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2_lane.fca.0.extract, <1 x i64> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_s8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 5, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 4
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v10, 3, v0.t
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  %vld2_lane = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2lane.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, i64 4, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2_lane.fca.0.extract, <8 x i8> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_u16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 8
; CHECK-NEXT:    vslideup.vi v8, v10, 3
; CHECK-NEXT:    vslideup.vi v9, v10, 2, v0.t
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  %vld2_lane = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2lane.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, i64 3, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2_lane.fca.0.extract, <4 x i16> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_u32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  %vld2_lane = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2lane.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2_lane.fca.0.extract, <2 x i32> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_u64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsseg2e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  %vld2_lane = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2lane.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2_lane.fca.0.extract, <1 x i64> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_lane_u8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_lane_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 5, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 4
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v10, 3, v0.t
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  %vld2_lane = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2lane.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, i64 4, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2_lane.fca.0.extract, <8 x i8> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_f16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, -3
; CHECK-NEXT:    vsetivli zero, 2, e16, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 1
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v9, v10, v9, v0
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2.v8f16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 1
  %vld2_lane = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2lane.v8f16.p0(<8 x half> %vld2.fca.0.extract, <8 x half> %vld2.fca.1.extract, i64 1, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vld2_lane.fca.0.extract, <8 x half> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_f32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 13
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 1
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v9, v10, v9, v0
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2.v4f32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 1
  %vld2_lane = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2lane.v4f32.p0(<4 x float> %vld2.fca.0.extract, <4 x float> %vld2.fca.1.extract, i64 1, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vld2_lane.fca.0.extract, <4 x float> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_f64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2.v2f64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 1
  %vld2_lane = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2lane.v2f64.p0(<2 x double> %vld2.fca.0.extract, <2 x double> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double> %vld2_lane.fca.0.extract, <2 x double> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_s16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v10, 7
; CHECK-NEXT:    vslideup.vi v9, v10, 6, v0.t
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  %vld2_lane = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2lane.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, i64 7, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2_lane.fca.0.extract, <8 x i16> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_s32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 13
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 1
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v9, v10, v9, v0
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  %vld2_lane = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2lane.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, i64 1, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2_lane.fca.0.extract, <4 x i32> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_s64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  %vld2_lane = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2lane.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, i64 0, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2_lane.fca.0.extract, <2 x i64> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_s8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    lui a0, 2
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 14, e8, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 13
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v10, 12, v0.t
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  %vld2_lane = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2lane.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, i64 13, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2_lane.fca.0.extract, <16 x i8> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_u16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg2e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v10, 7
; CHECK-NEXT:    vslideup.vi v9, v10, 6, v0.t
; CHECK-NEXT:    vsseg2e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  %vld2_lane = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2lane.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, i64 7, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2_lane.fca.0.extract, <8 x i16> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_u32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg2e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vmv.v.i v0, 4
; CHECK-NEXT:    vsetivli zero, 3, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 2
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v10, 1, v0.t
; CHECK-NEXT:    vsseg2e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  %vld2_lane = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2lane.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, i64 2, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2_lane.fca.0.extract, <4 x i32> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_u64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v10, v9
; CHECK-NEXT:    vmv1r.v v9, v10
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vsseg2e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  %vld2_lane = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2lane.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, i64 1, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2_lane.fca.0.extract, <2 x i64> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_lane_u8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_lane_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlseg2e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 9, e8, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v10, 8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v10, 7, v0.t
; CHECK-NEXT:    vsseg2e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  %vld2_lane = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2lane.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, i64 8, ptr %in_0)
  %vld2_lane.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2_lane, 0
  %vld2_lane.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2_lane, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2_lane.fca.0.extract, <16 x i8> %vld2_lane.fca.1.extract, ptr %out)
  ret void
}

define void @vld3_lane_f16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, 8
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v11, 3
; CHECK-NEXT:    vslideup.vi v9, v11, 2, v0.t
; CHECK-NEXT:    vslideup.vi v10, v11, 1, v0.t
; CHECK-NEXT:    vsseg3e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3.v4f16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 2
  %vld3_lane = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3lane.v4f16.p0(<4 x half> %vld3.fca.0.extract, <4 x half> %vld3.fca.1.extract, <4 x half> %vld3.fca.2.extract, i64 3, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half> %vld3_lane.fca.0.extract, <4 x half> %vld3_lane.fca.1.extract, <4 x half> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_f32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    lbu a3, 0(a0)
; CHECK-NEXT:    lbu a4, 1(a0)
; CHECK-NEXT:    lbu a5, 2(a0)
; CHECK-NEXT:    lbu a6, 3(a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    slli a4, a4, 8
; CHECK-NEXT:    slli a5, a5, 16
; CHECK-NEXT:    slli a6, a6, 24
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    or a1, a6, a5
; CHECK-NEXT:    or a1, a1, a3
; CHECK-NEXT:    sw a1, 8(sp)
; CHECK-NEXT:    flw fa5, 8(sp)
; CHECK-NEXT:    lbu a1, 5(a0)
; CHECK-NEXT:    lbu a3, 4(a0)
; CHECK-NEXT:    lbu a4, 6(a0)
; CHECK-NEXT:    lbu a5, 7(a0)
; CHECK-NEXT:    slli a1, a1, 8
; CHECK-NEXT:    or a1, a1, a3
; CHECK-NEXT:    vfmv.s.f v11, fa5
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    sw a1, 16(sp)
; CHECK-NEXT:    lbu a1, 8(a0)
; CHECK-NEXT:    lbu a3, 9(a0)
; CHECK-NEXT:    lbu a4, 10(a0)
; CHECK-NEXT:    lbu a0, 11(a0)
; CHECK-NEXT:    flw fa5, 16(sp)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a0, a0, a4
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    sw a0, 24(sp)
; CHECK-NEXT:    flw fa4, 24(sp)
; CHECK-NEXT:    vfmv.s.f v12, fa5
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vslideup.vi v9, v12, 1
; CHECK-NEXT:    vfmv.s.f v11, fa4
; CHECK-NEXT:    vslideup.vi v10, v11, 1
; CHECK-NEXT:    vsseg3e32.v v8, (a2)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3.v2f32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 2
  %vld3_lane = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3lane.v2f32.p0(<2 x float> %vld3.fca.0.extract, <2 x float> %vld3.fca.1.extract, <2 x float> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float> %vld3_lane.fca.0.extract, <2 x float> %vld3_lane.fca.1.extract, <2 x float> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_f64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v13, v8, 1
; CHECK-NEXT:    vmv2r.v v10, v8
; CHECK-NEXT:    vmv.v.v v11, v13
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsseg3e64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3.v1f64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 2
  %vld3_lane = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3lane.v1f64.p0(<1 x double> %vld3.fca.0.extract, <1 x double> %vld3.fca.1.extract, <1 x double> %vld3.fca.2.extract, i64 0, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double> %vld3_lane.fca.0.extract, <1 x double> %vld3_lane.fca.1.extract, <1 x double> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_s16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, 13
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vmerge.vvm v9, v11, v9, v0
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vslidedown.vi v10, v11, 1, v0.t
; CHECK-NEXT:    vsseg3e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  %vld3_lane = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3lane.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3_lane.fca.0.extract, <4 x i16> %vld3_lane.fca.1.extract, <4 x i16> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_s32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    lbu a1, 1(a0)
; CHECK-NEXT:    lbu a3, 0(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lb a5, 3(a0)
; CHECK-NEXT:    slli a1, a1, 8
; CHECK-NEXT:    or a1, a1, a3
; CHECK-NEXT:    lbu a3, 4(a0)
; CHECK-NEXT:    lbu a6, 5(a0)
; CHECK-NEXT:    lbu a7, 6(a0)
; CHECK-NEXT:    lb t0, 7(a0)
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t0, t0, 24
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a6, a3
; CHECK-NEXT:    or a5, t0, a7
; CHECK-NEXT:    lbu a6, 9(a0)
; CHECK-NEXT:    lbu a7, 8(a0)
; CHECK-NEXT:    lbu t0, 10(a0)
; CHECK-NEXT:    lb a0, 11(a0)
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    or a6, a6, a7
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t0
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    or a0, a0, a6
; CHECK-NEXT:    vmv.s.x v11, a1
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a3
; CHECK-NEXT:    vslideup.vi v9, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vslideup.vi v10, v11, 1
; CHECK-NEXT:    vsseg3e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  %vld3_lane = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3lane.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3_lane.fca.0.extract, <2 x i32> %vld3_lane.fca.1.extract, <2 x i32> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_s64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v13, v8, 1
; CHECK-NEXT:    vmv2r.v v10, v8
; CHECK-NEXT:    vmv.v.v v11, v13
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsseg3e64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  %vld3_lane = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3lane.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, i64 0, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3_lane.fca.0.extract, <1 x i64> %vld3_lane.fca.1.extract, <1 x i64> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_s8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 3, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, -3
; CHECK-NEXT:    vsetivli zero, 2, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vmerge.vvm v9, v11, v9, v0
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vslidedown.vi v10, v11, 1, v0.t
; CHECK-NEXT:    vsseg3e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  %vld3_lane = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3lane.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3_lane.fca.0.extract, <8 x i8> %vld3_lane.fca.1.extract, <8 x i8> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_u16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, 13
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vmerge.vvm v9, v11, v9, v0
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vslidedown.vi v10, v11, 1, v0.t
; CHECK-NEXT:    vsseg3e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  %vld3_lane = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3lane.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3_lane.fca.0.extract, <4 x i16> %vld3_lane.fca.1.extract, <4 x i16> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_u32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    lbu a1, 1(a0)
; CHECK-NEXT:    lbu a3, 0(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lb a5, 3(a0)
; CHECK-NEXT:    slli a1, a1, 8
; CHECK-NEXT:    or a1, a1, a3
; CHECK-NEXT:    lbu a3, 4(a0)
; CHECK-NEXT:    lbu a6, 5(a0)
; CHECK-NEXT:    lbu a7, 6(a0)
; CHECK-NEXT:    lb t0, 7(a0)
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t0, t0, 24
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a6, a3
; CHECK-NEXT:    or a5, t0, a7
; CHECK-NEXT:    lbu a6, 9(a0)
; CHECK-NEXT:    lbu a7, 8(a0)
; CHECK-NEXT:    lbu t0, 10(a0)
; CHECK-NEXT:    lb a0, 11(a0)
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    or a6, a6, a7
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t0
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    or a0, a0, a6
; CHECK-NEXT:    vmv.s.x v11, a1
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a3
; CHECK-NEXT:    vslideup.vi v9, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vslideup.vi v10, v11, 1
; CHECK-NEXT:    vsseg3e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  %vld3_lane = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3lane.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3_lane.fca.0.extract, <2 x i32> %vld3_lane.fca.1.extract, <2 x i32> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_u64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 24, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v13, v8, 1
; CHECK-NEXT:    vmv2r.v v10, v8
; CHECK-NEXT:    vmv.v.v v11, v13
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsseg3e64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  %vld3_lane = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3lane.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, i64 0, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3_lane.fca.0.extract, <1 x i64> %vld3_lane.fca.1.extract, <1 x i64> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_lane_u8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_lane_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 3, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 5
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v11, 4, v0.t
; CHECK-NEXT:    vslideup.vi v10, v11, 3, v0.t
; CHECK-NEXT:    vsseg3e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  %vld3_lane = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3lane.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, i64 5, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3_lane.fca.0.extract, <8 x i8> %vld3_lane.fca.1.extract, <8 x i8> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_f16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, -3
; CHECK-NEXT:    vsetivli zero, 2, e16, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vmerge.vvm v9, v11, v9, v0
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vslidedown.vi v10, v11, 1, v0.t
; CHECK-NEXT:    vsseg3e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3.v8f16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 2
  %vld3_lane = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3lane.v8f16.p0(<8 x half> %vld3.fca.0.extract, <8 x half> %vld3.fca.1.extract, <8 x half> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half> %vld3_lane.fca.0.extract, <8 x half> %vld3_lane.fca.1.extract, <8 x half> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_f32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 12, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, 4
; CHECK-NEXT:    vsetivli zero, 3, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 2
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v11, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 11
; CHECK-NEXT:    vmerge.vvm v10, v11, v10, v0
; CHECK-NEXT:    vsseg3e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3.v4f32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 2
  %vld3_lane = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3lane.v4f32.p0(<4 x float> %vld3.fca.0.extract, <4 x float> %vld3.fca.1.extract, <4 x float> %vld3.fca.2.extract, i64 2, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float> %vld3_lane.fca.0.extract, <4 x float> %vld3_lane.fca.1.extract, <4 x float> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_f64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lbu t1, 7(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 9(a0)
; CHECK-NEXT:    lbu t4, 10(a0)
; CHECK-NEXT:    lbu t5, 11(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, a5, a4
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    lbu a5, 12(a0)
; CHECK-NEXT:    lbu a6, 13(a0)
; CHECK-NEXT:    lbu a7, 14(a0)
; CHECK-NEXT:    lbu t6, 15(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    or t0, t1, t0
; CHECK-NEXT:    or t1, t3, t2
; CHECK-NEXT:    or t2, t5, t4
; CHECK-NEXT:    or a5, a6, a5
; CHECK-NEXT:    lbu a6, 16(a0)
; CHECK-NEXT:    lbu t3, 17(a0)
; CHECK-NEXT:    lbu t4, 18(a0)
; CHECK-NEXT:    lbu t5, 19(a0)
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t6, t6, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    or a7, t6, a7
; CHECK-NEXT:    or a6, t3, a6
; CHECK-NEXT:    or t3, t5, t4
; CHECK-NEXT:    lbu t4, 21(a0)
; CHECK-NEXT:    lbu t5, 20(a0)
; CHECK-NEXT:    lbu t6, 22(a0)
; CHECK-NEXT:    lbu a0, 23(a0)
; CHECK-NEXT:    slli t4, t4, 8
; CHECK-NEXT:    or t4, t4, t5
; CHECK-NEXT:    slli t6, t6, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t6
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, t0, a4
; CHECK-NEXT:    or a4, t2, t1
; CHECK-NEXT:    or a5, a7, a5
; CHECK-NEXT:    or a6, t3, a6
; CHECK-NEXT:    or a0, a0, t4
; CHECK-NEXT:    slli a3, a3, 32
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    slli a5, a5, 32
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a0, a0, a6
; CHECK-NEXT:    vmv.s.x v11, a1
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a4
; CHECK-NEXT:    vslideup.vi v9, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vslideup.vi v10, v11, 1
; CHECK-NEXT:    vsseg3e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3.v2f64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 2
  %vld3_lane = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3lane.v2f64.p0(<2 x double> %vld3.fca.0.extract, <2 x double> %vld3.fca.1.extract, <2 x double> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double> %vld3_lane.fca.0.extract, <2 x double> %vld3_lane.fca.1.extract, <2 x double> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_s16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v11, 7
; CHECK-NEXT:    vslideup.vi v9, v11, 6, v0.t
; CHECK-NEXT:    vslideup.vi v10, v11, 5, v0.t
; CHECK-NEXT:    vsseg3e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  %vld3_lane = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3lane.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, i64 7, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3_lane.fca.0.extract, <8 x i16> %vld3_lane.fca.1.extract, <8 x i16> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_s32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 12, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, 4
; CHECK-NEXT:    vsetivli zero, 3, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 2
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v11, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 11
; CHECK-NEXT:    vmerge.vvm v10, v11, v10, v0
; CHECK-NEXT:    vsseg3e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  %vld3_lane = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3lane.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, i64 2, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3_lane.fca.0.extract, <4 x i32> %vld3_lane.fca.1.extract, <4 x i32> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_s64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lbu t1, 7(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 9(a0)
; CHECK-NEXT:    lbu t4, 10(a0)
; CHECK-NEXT:    lbu t5, 11(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, a5, a4
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    lbu a5, 12(a0)
; CHECK-NEXT:    lbu a6, 13(a0)
; CHECK-NEXT:    lbu a7, 14(a0)
; CHECK-NEXT:    lbu t6, 15(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    or t0, t1, t0
; CHECK-NEXT:    or t1, t3, t2
; CHECK-NEXT:    or t2, t5, t4
; CHECK-NEXT:    or a5, a6, a5
; CHECK-NEXT:    lbu a6, 16(a0)
; CHECK-NEXT:    lbu t3, 17(a0)
; CHECK-NEXT:    lbu t4, 18(a0)
; CHECK-NEXT:    lbu t5, 19(a0)
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t6, t6, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    or a7, t6, a7
; CHECK-NEXT:    or a6, t3, a6
; CHECK-NEXT:    or t3, t5, t4
; CHECK-NEXT:    lbu t4, 21(a0)
; CHECK-NEXT:    lbu t5, 20(a0)
; CHECK-NEXT:    lbu t6, 22(a0)
; CHECK-NEXT:    lbu a0, 23(a0)
; CHECK-NEXT:    slli t4, t4, 8
; CHECK-NEXT:    or t4, t4, t5
; CHECK-NEXT:    slli t6, t6, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t6
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, t0, a4
; CHECK-NEXT:    or a4, t2, t1
; CHECK-NEXT:    or a5, a7, a5
; CHECK-NEXT:    or a6, t3, a6
; CHECK-NEXT:    or a0, a0, t4
; CHECK-NEXT:    slli a3, a3, 32
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    slli a5, a5, 32
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a0, a0, a6
; CHECK-NEXT:    vmv.s.x v11, a1
; CHECK-NEXT:    vslideup.vi v8, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a4
; CHECK-NEXT:    vslideup.vi v9, v11, 1
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vslideup.vi v10, v11, 1
; CHECK-NEXT:    vsseg3e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  %vld3_lane = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3lane.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, i64 1, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3_lane.fca.0.extract, <2 x i64> %vld3_lane.fca.1.extract, <2 x i64> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_s8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 3, e16, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    li a0, 64
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 7, e8, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 6
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v11, 5, v0.t
; CHECK-NEXT:    vslideup.vi v10, v11, 4, v0.t
; CHECK-NEXT:    vsseg3e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  %vld3_lane = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3lane.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, i64 6, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3_lane.fca.0.extract, <16 x i8> %vld3_lane.fca.1.extract, <16 x i8> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_u16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg3e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 6, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    li a0, 64
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 7, e16, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v11, 6
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v11, 5, v0.t
; CHECK-NEXT:    vslideup.vi v10, v11, 4, v0.t
; CHECK-NEXT:    vsseg3e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  %vld3_lane = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3lane.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, i64 6, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3_lane.fca.0.extract, <8 x i16> %vld3_lane.fca.1.extract, <8 x i16> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_u32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 12, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vmv.v.i v0, 8
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v11, 3
; CHECK-NEXT:    vslideup.vi v9, v11, 2, v0.t
; CHECK-NEXT:    vslideup.vi v10, v11, 1, v0.t
; CHECK-NEXT:    vsseg3e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  %vld3_lane = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3lane.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, i64 3, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3_lane.fca.0.extract, <4 x i32> %vld3_lane.fca.1.extract, <4 x i32> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_u64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg3e64.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lbu t1, 7(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 9(a0)
; CHECK-NEXT:    lbu t4, 10(a0)
; CHECK-NEXT:    lbu t5, 11(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, a5, a4
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    lbu a5, 12(a0)
; CHECK-NEXT:    lbu a6, 13(a0)
; CHECK-NEXT:    lbu a7, 14(a0)
; CHECK-NEXT:    lbu t6, 15(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    or t0, t1, t0
; CHECK-NEXT:    or t1, t3, t2
; CHECK-NEXT:    or t2, t5, t4
; CHECK-NEXT:    or a5, a6, a5
; CHECK-NEXT:    lbu a6, 16(a0)
; CHECK-NEXT:    lbu t3, 17(a0)
; CHECK-NEXT:    lbu t4, 18(a0)
; CHECK-NEXT:    lbu t5, 19(a0)
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t6, t6, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    or a7, t6, a7
; CHECK-NEXT:    or a6, t3, a6
; CHECK-NEXT:    or t3, t5, t4
; CHECK-NEXT:    lbu t4, 21(a0)
; CHECK-NEXT:    lbu t5, 20(a0)
; CHECK-NEXT:    lbu t6, 22(a0)
; CHECK-NEXT:    lbu a0, 23(a0)
; CHECK-NEXT:    slli t4, t4, 8
; CHECK-NEXT:    or t4, t4, t5
; CHECK-NEXT:    slli t6, t6, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t6
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, t0, a4
; CHECK-NEXT:    or a4, t2, t1
; CHECK-NEXT:    or a5, a7, a5
; CHECK-NEXT:    or a6, t3, a6
; CHECK-NEXT:    or a0, a0, t4
; CHECK-NEXT:    slli a3, a3, 32
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    slli a5, a5, 32
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    vmv.s.x v9, a4
; CHECK-NEXT:    or a0, a0, a6
; CHECK-NEXT:    vmv.s.x v10, a0
; CHECK-NEXT:    vsseg3e64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  %vld3_lane = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3lane.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, i64 0, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3_lane.fca.0.extract, <2 x i64> %vld3_lane.fca.1.extract, <2 x i64> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_lane_u8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_lane_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlseg3e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 3, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v11
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v11, 1, v0.t
; CHECK-NEXT:    vslidedown.vi v10, v11, 2, v0.t
; CHECK-NEXT:    vsseg3e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  %vld3_lane = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3lane.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, i64 0, ptr %in_0)
  %vld3_lane.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3_lane, 0
  %vld3_lane.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3_lane, 1
  %vld3_lane.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3_lane, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3_lane.fca.0.extract, <16 x i8> %vld3_lane.fca.1.extract, <16 x i8> %vld3_lane.fca.2.extract, ptr %out)
  ret void
}

define void @vld4_lane_f16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v13, (a0)
; CHECK-NEXT:    vmv.v.i v8, 4
; CHECK-NEXT:    vsetivli zero, 3, e16, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v9, v13, 2
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vslideup.vi v10, v13, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 11
; CHECK-NEXT:    vmerge.vvm v11, v13, v11, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vslidedown.vi v12, v13, 1, v0.t
; CHECK-NEXT:    vsseg4e16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4.v4f16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 3
  %vld4_lane = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4lane.v4f16.p0(<4 x half> %vld4.fca.0.extract, <4 x half> %vld4.fca.1.extract, <4 x half> %vld4.fca.2.extract, <4 x half> %vld4.fca.3.extract, i64 2, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half> %vld4_lane.fca.0.extract, <4 x half> %vld4_lane.fca.1.extract, <4 x half> %vld4_lane.fca.2.extract, <4 x half> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_f32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    lbu a3, 0(a0)
; CHECK-NEXT:    lbu a4, 1(a0)
; CHECK-NEXT:    lbu a5, 2(a0)
; CHECK-NEXT:    lbu a6, 3(a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    slli a4, a4, 8
; CHECK-NEXT:    slli a5, a5, 16
; CHECK-NEXT:    slli a6, a6, 24
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    or a1, a6, a5
; CHECK-NEXT:    or a1, a1, a3
; CHECK-NEXT:    sw a1, 0(sp)
; CHECK-NEXT:    lbu a1, 4(a0)
; CHECK-NEXT:    lbu a3, 5(a0)
; CHECK-NEXT:    lbu a4, 6(a0)
; CHECK-NEXT:    lbu a5, 7(a0)
; CHECK-NEXT:    flw fa5, 0(sp)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    sw a1, 8(sp)
; CHECK-NEXT:    lbu a1, 9(a0)
; CHECK-NEXT:    lbu a3, 8(a0)
; CHECK-NEXT:    lbu a4, 10(a0)
; CHECK-NEXT:    lbu a5, 11(a0)
; CHECK-NEXT:    slli a1, a1, 8
; CHECK-NEXT:    or a1, a1, a3
; CHECK-NEXT:    flw fa4, 8(sp)
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    sw a1, 16(sp)
; CHECK-NEXT:    lbu a1, 12(a0)
; CHECK-NEXT:    lbu a3, 13(a0)
; CHECK-NEXT:    lbu a4, 14(a0)
; CHECK-NEXT:    lbu a0, 15(a0)
; CHECK-NEXT:    flw fa3, 16(sp)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a0, a0, a4
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    sw a0, 24(sp)
; CHECK-NEXT:    flw fa2, 24(sp)
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, tu, ma
; CHECK-NEXT:    vfmv.s.f v8, fa5
; CHECK-NEXT:    vfmv.s.f v9, fa4
; CHECK-NEXT:    vfmv.s.f v10, fa3
; CHECK-NEXT:    vfmv.s.f v11, fa2
; CHECK-NEXT:    vsseg4e32.v v8, (a2)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4.v2f32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 3
  %vld4_lane = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4lane.v2f32.p0(<2 x float> %vld4.fca.0.extract, <2 x float> %vld4.fca.1.extract, <2 x float> %vld4.fca.2.extract, <2 x float> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float> %vld4_lane.fca.0.extract, <2 x float> %vld4_lane.fca.1.extract, <2 x float> %vld4_lane.fca.2.extract, <2 x float> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_f64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 1
; CHECK-NEXT:    vmv1r.v v11, v8
; CHECK-NEXT:    vmv.v.v v12, v10
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v16, v8, 2
; CHECK-NEXT:    vslidedown.vi v14, v8, 3
; CHECK-NEXT:    vmv1r.v v13, v16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsseg4e64.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4.v1f64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 3
  %vld4_lane = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4lane.v1f64.p0(<1 x double> %vld4.fca.0.extract, <1 x double> %vld4.fca.1.extract, <1 x double> %vld4.fca.2.extract, <1 x double> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double> %vld4_lane.fca.0.extract, <1 x double> %vld4_lane.fca.1.extract, <1 x double> %vld4_lane.fca.2.extract, <1 x double> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_s16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v12, 1, v0.t
; CHECK-NEXT:    vslidedown.vi v10, v12, 2, v0.t
; CHECK-NEXT:    vslidedown.vi v11, v12, 3, v0.t
; CHECK-NEXT:    vsseg4e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  %vld4_lane = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4lane.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4_lane.fca.0.extract, <4 x i16> %vld4_lane.fca.1.extract, <4 x i16> %vld4_lane.fca.2.extract, <4 x i16> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_s32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lb a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lb t1, 7(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a7, a6
; CHECK-NEXT:    lbu a5, 8(a0)
; CHECK-NEXT:    lbu a6, 9(a0)
; CHECK-NEXT:    lbu a7, 10(a0)
; CHECK-NEXT:    lb t2, 11(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t2, t2, 24
; CHECK-NEXT:    or t0, t1, t0
; CHECK-NEXT:    or a5, a6, a5
; CHECK-NEXT:    or a6, t2, a7
; CHECK-NEXT:    lbu a7, 13(a0)
; CHECK-NEXT:    lbu t1, 12(a0)
; CHECK-NEXT:    lbu t2, 14(a0)
; CHECK-NEXT:    lb a0, 15(a0)
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a7, a7, t1
; CHECK-NEXT:    slli t2, t2, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t2
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    or a3, t0, a3
; CHECK-NEXT:    or a4, a6, a5
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    vmv.s.x v9, a3
; CHECK-NEXT:    vmv.s.x v10, a4
; CHECK-NEXT:    or a0, a0, a7
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vsseg4e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  %vld4_lane = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4lane.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4_lane.fca.0.extract, <2 x i32> %vld4_lane.fca.1.extract, <2 x i32> %vld4_lane.fca.2.extract, <2 x i32> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_s64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 1
; CHECK-NEXT:    vmv1r.v v11, v8
; CHECK-NEXT:    vmv.v.v v12, v10
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v16, v8, 2
; CHECK-NEXT:    vslidedown.vi v14, v8, 3
; CHECK-NEXT:    vmv1r.v v13, v16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsseg4e64.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  %vld4_lane = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4lane.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4_lane.fca.0.extract, <1 x i64> %vld4_lane.fca.1.extract, <1 x i64> %vld4_lane.fca.2.extract, <1 x i64> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_s8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e8, mf2, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v12, 1, v0.t
; CHECK-NEXT:    vslidedown.vi v10, v12, 2, v0.t
; CHECK-NEXT:    vslidedown.vi v11, v12, 3, v0.t
; CHECK-NEXT:    vsseg4e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  %vld4_lane = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4lane.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4_lane.fca.0.extract, <8 x i8> %vld4_lane.fca.1.extract, <8 x i8> %vld4_lane.fca.2.extract, <8 x i8> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_u16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlseg4e16.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v13, (a0)
; CHECK-NEXT:    vmv.v.i v0, 13
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v9, v13, 1
; CHECK-NEXT:    vmv.v.i v8, 2
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vmerge.vvm v10, v13, v10, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vslidedown.vi v11, v13, 1, v0.t
; CHECK-NEXT:    vslidedown.vi v12, v13, 2, v0.t
; CHECK-NEXT:    vsseg4e16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  %vld4_lane = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4lane.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, i64 1, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4_lane.fca.0.extract, <4 x i16> %vld4_lane.fca.1.extract, <4 x i16> %vld4_lane.fca.2.extract, <4 x i16> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_u32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lb a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lb t1, 7(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a7, a6
; CHECK-NEXT:    lbu a5, 8(a0)
; CHECK-NEXT:    lbu a6, 9(a0)
; CHECK-NEXT:    lbu a7, 10(a0)
; CHECK-NEXT:    lb t2, 11(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    slli a7, a7, 16
; CHECK-NEXT:    slli t2, t2, 24
; CHECK-NEXT:    or t0, t1, t0
; CHECK-NEXT:    or a5, a6, a5
; CHECK-NEXT:    or a6, t2, a7
; CHECK-NEXT:    lbu a7, 13(a0)
; CHECK-NEXT:    lbu t1, 12(a0)
; CHECK-NEXT:    lbu t2, 14(a0)
; CHECK-NEXT:    lb a0, 15(a0)
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a7, a7, t1
; CHECK-NEXT:    slli t2, t2, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, t2
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    or a3, t0, a3
; CHECK-NEXT:    or a4, a6, a5
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    vmv.s.x v9, a3
; CHECK-NEXT:    vmv.s.x v10, a4
; CHECK-NEXT:    or a0, a0, a7
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vsseg4e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  %vld4_lane = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4lane.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4_lane.fca.0.extract, <2 x i32> %vld4_lane.fca.1.extract, <2 x i32> %vld4_lane.fca.2.extract, <2 x i32> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_u64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 1
; CHECK-NEXT:    vmv1r.v v11, v8
; CHECK-NEXT:    vmv.v.v v12, v10
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v16, v8, 2
; CHECK-NEXT:    vslidedown.vi v14, v8, 3
; CHECK-NEXT:    vmv1r.v v13, v16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsseg4e64.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  %vld4_lane = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4lane.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4_lane.fca.0.extract, <1 x i64> %vld4_lane.fca.1.extract, <1 x i64> %vld4_lane.fca.2.extract, <1 x i64> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_lane_u8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_lane_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    vmv.v.i v0, 8
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v12, 3
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v12, 2, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, -9
; CHECK-NEXT:    vmerge.vvm v11, v12, v11, v0
; CHECK-NEXT:    vsseg4e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  %vld4_lane = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4lane.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, i64 3, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4_lane.fca.0.extract, <8 x i8> %vld4_lane.fca.1.extract, <8 x i8> %vld4_lane.fca.2.extract, <8 x i8> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_f16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslideup.vi v8, v12, 7
; CHECK-NEXT:    vslideup.vi v9, v12, 6, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 5, v0.t
; CHECK-NEXT:    vslideup.vi v11, v12, 4, v0.t
; CHECK-NEXT:    vsseg4e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4.v8f16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 3
  %vld4_lane = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4lane.v8f16.p0(<8 x half> %vld4.fca.0.extract, <8 x half> %vld4.fca.1.extract, <8 x half> %vld4.fca.2.extract, <8 x half> %vld4.fca.3.extract, i64 7, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half> %vld4_lane.fca.0.extract, <8 x half> %vld4_lane.fca.1.extract, <8 x half> %vld4_lane.fca.2.extract, <8 x half> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_f32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    vmv.v.i v0, 8
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v8, v12, 3
; CHECK-NEXT:    vslideup.vi v9, v12, 2, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 3, e32, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v12, v11
; CHECK-NEXT:    vmv1r.v v11, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vsseg4e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4.v4f32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 3
  %vld4_lane = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4lane.v4f32.p0(<4 x float> %vld4.fca.0.extract, <4 x float> %vld4.fca.1.extract, <4 x float> %vld4.fca.2.extract, <4 x float> %vld4.fca.3.extract, i64 3, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float> %vld4_lane.fca.0.extract, <4 x float> %vld4_lane.fca.1.extract, <4 x float> %vld4_lane.fca.2.extract, <4 x float> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_f64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    sd s0, 56(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 48(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s2, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s3, 32(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s4, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s5, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s6, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    .cfi_offset s2, -24
; CHECK-NEXT:    .cfi_offset s3, -32
; CHECK-NEXT:    .cfi_offset s4, -40
; CHECK-NEXT:    .cfi_offset s5, -48
; CHECK-NEXT:    .cfi_offset s6, -56
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lbu t1, 7(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 9(a0)
; CHECK-NEXT:    lbu t4, 10(a0)
; CHECK-NEXT:    lbu t5, 11(a0)
; CHECK-NEXT:    lbu t6, 12(a0)
; CHECK-NEXT:    lbu s0, 13(a0)
; CHECK-NEXT:    lbu s1, 14(a0)
; CHECK-NEXT:    lbu s2, 15(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, a5, a4
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    lbu s3, 16(a0)
; CHECK-NEXT:    lbu s4, 17(a0)
; CHECK-NEXT:    lbu s5, 18(a0)
; CHECK-NEXT:    lbu s6, 19(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    slli s0, s0, 8
; CHECK-NEXT:    or a5, t1, t0
; CHECK-NEXT:    or a6, t3, t2
; CHECK-NEXT:    or a7, t5, t4
; CHECK-NEXT:    or t0, s0, t6
; CHECK-NEXT:    lbu t1, 20(a0)
; CHECK-NEXT:    lbu t2, 21(a0)
; CHECK-NEXT:    lbu t3, 22(a0)
; CHECK-NEXT:    lbu t4, 23(a0)
; CHECK-NEXT:    slli s1, s1, 16
; CHECK-NEXT:    slli s2, s2, 24
; CHECK-NEXT:    slli s4, s4, 8
; CHECK-NEXT:    slli s5, s5, 16
; CHECK-NEXT:    slli s6, s6, 24
; CHECK-NEXT:    slli t2, t2, 8
; CHECK-NEXT:    or t5, s2, s1
; CHECK-NEXT:    or t6, s4, s3
; CHECK-NEXT:    or s0, s6, s5
; CHECK-NEXT:    or t1, t2, t1
; CHECK-NEXT:    lbu t2, 24(a0)
; CHECK-NEXT:    lbu s1, 25(a0)
; CHECK-NEXT:    lbu s2, 26(a0)
; CHECK-NEXT:    lbu s3, 27(a0)
; CHECK-NEXT:    slli t3, t3, 16
; CHECK-NEXT:    slli t4, t4, 24
; CHECK-NEXT:    slli s1, s1, 8
; CHECK-NEXT:    slli s2, s2, 16
; CHECK-NEXT:    slli s3, s3, 24
; CHECK-NEXT:    or t3, t4, t3
; CHECK-NEXT:    or t2, s1, t2
; CHECK-NEXT:    or t4, s3, s2
; CHECK-NEXT:    lbu s1, 29(a0)
; CHECK-NEXT:    lbu s2, 28(a0)
; CHECK-NEXT:    lbu s3, 30(a0)
; CHECK-NEXT:    lbu a0, 31(a0)
; CHECK-NEXT:    slli s1, s1, 8
; CHECK-NEXT:    or s1, s1, s2
; CHECK-NEXT:    slli s3, s3, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, s3
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a7, a6
; CHECK-NEXT:    or a5, t5, t0
; CHECK-NEXT:    or a6, s0, t6
; CHECK-NEXT:    or a7, t3, t1
; CHECK-NEXT:    or t0, t4, t2
; CHECK-NEXT:    or a0, a0, s1
; CHECK-NEXT:    slli a4, a4, 32
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    slli a5, a5, 32
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    slli a7, a7, 32
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    vmv.s.x v9, a3
; CHECK-NEXT:    vmv.s.x v10, a4
; CHECK-NEXT:    or a0, a0, t0
; CHECK-NEXT:    vmv.s.x v11, a0
; CHECK-NEXT:    vsseg4e64.v v8, (a2)
; CHECK-NEXT:    ld s0, 56(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 48(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s2, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s3, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s4, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s5, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s6, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s2
; CHECK-NEXT:    .cfi_restore s3
; CHECK-NEXT:    .cfi_restore s4
; CHECK-NEXT:    .cfi_restore s5
; CHECK-NEXT:    .cfi_restore s6
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4.v2f64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 3
  %vld4_lane = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4lane.v2f64.p0(<2 x double> %vld4.fca.0.extract, <2 x double> %vld4.fca.1.extract, <2 x double> %vld4.fca.2.extract, <2 x double> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double> %vld4_lane.fca.0.extract, <2 x double> %vld4_lane.fca.1.extract, <2 x double> %vld4_lane.fca.2.extract, <2 x double> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_s16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vslideup.vi v8, v12, 7
; CHECK-NEXT:    vslideup.vi v9, v12, 6, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 5, v0.t
; CHECK-NEXT:    vslideup.vi v11, v12, 4, v0.t
; CHECK-NEXT:    vsseg4e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  %vld4_lane = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4lane.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, i64 7, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4_lane.fca.0.extract, <8 x i16> %vld4_lane.fca.1.extract, <8 x i16> %vld4_lane.fca.2.extract, <8 x i16> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_s32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v13, (a0)
; CHECK-NEXT:    vmv.v.i v8, 4
; CHECK-NEXT:    vsetivli zero, 3, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v9, v13, 2
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v10, v13, 1, v0.t
; CHECK-NEXT:    vmv.v.i v0, 11
; CHECK-NEXT:    vmerge.vvm v11, v13, v11, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vslidedown.vi v12, v13, 1, v0.t
; CHECK-NEXT:    vsseg4e32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  %vld4_lane = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4lane.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, i64 2, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4_lane.fca.0.extract, <4 x i32> %vld4_lane.fca.1.extract, <4 x i32> %vld4_lane.fca.2.extract, <4 x i32> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_s64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    sd s0, 56(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 48(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s2, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s3, 32(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s4, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s5, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s6, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    .cfi_offset s2, -24
; CHECK-NEXT:    .cfi_offset s3, -32
; CHECK-NEXT:    .cfi_offset s4, -40
; CHECK-NEXT:    .cfi_offset s5, -48
; CHECK-NEXT:    .cfi_offset s6, -56
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lbu t1, 7(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 9(a0)
; CHECK-NEXT:    lbu t4, 10(a0)
; CHECK-NEXT:    lbu t5, 11(a0)
; CHECK-NEXT:    lbu t6, 12(a0)
; CHECK-NEXT:    lbu s0, 13(a0)
; CHECK-NEXT:    lbu s1, 14(a0)
; CHECK-NEXT:    lbu s2, 15(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, a5, a4
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    lbu s3, 16(a0)
; CHECK-NEXT:    lbu s4, 17(a0)
; CHECK-NEXT:    lbu s5, 18(a0)
; CHECK-NEXT:    lbu s6, 19(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    slli s0, s0, 8
; CHECK-NEXT:    or a5, t1, t0
; CHECK-NEXT:    or a6, t3, t2
; CHECK-NEXT:    or a7, t5, t4
; CHECK-NEXT:    or t0, s0, t6
; CHECK-NEXT:    lbu t1, 20(a0)
; CHECK-NEXT:    lbu t2, 21(a0)
; CHECK-NEXT:    lbu t3, 22(a0)
; CHECK-NEXT:    lbu t4, 23(a0)
; CHECK-NEXT:    slli s1, s1, 16
; CHECK-NEXT:    slli s2, s2, 24
; CHECK-NEXT:    slli s4, s4, 8
; CHECK-NEXT:    slli s5, s5, 16
; CHECK-NEXT:    slli s6, s6, 24
; CHECK-NEXT:    slli t2, t2, 8
; CHECK-NEXT:    or t5, s2, s1
; CHECK-NEXT:    or t6, s4, s3
; CHECK-NEXT:    or s0, s6, s5
; CHECK-NEXT:    or t1, t2, t1
; CHECK-NEXT:    lbu t2, 24(a0)
; CHECK-NEXT:    lbu s1, 25(a0)
; CHECK-NEXT:    lbu s2, 26(a0)
; CHECK-NEXT:    lbu s3, 27(a0)
; CHECK-NEXT:    slli t3, t3, 16
; CHECK-NEXT:    slli t4, t4, 24
; CHECK-NEXT:    slli s1, s1, 8
; CHECK-NEXT:    slli s2, s2, 16
; CHECK-NEXT:    slli s3, s3, 24
; CHECK-NEXT:    or t3, t4, t3
; CHECK-NEXT:    or t2, s1, t2
; CHECK-NEXT:    or t4, s3, s2
; CHECK-NEXT:    lbu s1, 29(a0)
; CHECK-NEXT:    lbu s2, 28(a0)
; CHECK-NEXT:    lbu s3, 30(a0)
; CHECK-NEXT:    lbu a0, 31(a0)
; CHECK-NEXT:    slli s1, s1, 8
; CHECK-NEXT:    or s1, s1, s2
; CHECK-NEXT:    slli s3, s3, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, s3
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a7, a6
; CHECK-NEXT:    or a5, t5, t0
; CHECK-NEXT:    or a6, s0, t6
; CHECK-NEXT:    or a7, t3, t1
; CHECK-NEXT:    or t0, t4, t2
; CHECK-NEXT:    or a0, a0, s1
; CHECK-NEXT:    slli a4, a4, 32
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    slli a5, a5, 32
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    slli a7, a7, 32
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    or a0, a0, t0
; CHECK-NEXT:    vmv.s.x v12, a1
; CHECK-NEXT:    vslideup.vi v8, v12, 1
; CHECK-NEXT:    vmv.s.x v12, a3
; CHECK-NEXT:    vslideup.vi v9, v12, 1
; CHECK-NEXT:    vmv.s.x v12, a4
; CHECK-NEXT:    vslideup.vi v10, v12, 1
; CHECK-NEXT:    vmv.s.x v12, a0
; CHECK-NEXT:    vslideup.vi v11, v12, 1
; CHECK-NEXT:    vsseg4e64.v v8, (a2)
; CHECK-NEXT:    ld s0, 56(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 48(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s2, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s3, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s4, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s5, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s6, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s2
; CHECK-NEXT:    .cfi_restore s3
; CHECK-NEXT:    .cfi_restore s4
; CHECK-NEXT:    .cfi_restore s5
; CHECK-NEXT:    .cfi_restore s6
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  %vld4_lane = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4lane.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, i64 1, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4_lane.fca.0.extract, <2 x i64> %vld4_lane.fca.1.extract, <2 x i64> %vld4_lane.fca.2.extract, <2 x i64> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_s8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    lui a0, 4
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 15, e8, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v12, 14
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v12, 13, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 12, v0.t
; CHECK-NEXT:    vslideup.vi v11, v12, 11, v0.t
; CHECK-NEXT:    vsseg4e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  %vld4_lane = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4lane.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, i64 14, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4_lane.fca.0.extract, <16 x i8> %vld4_lane.fca.1.extract, <16 x i8> %vld4_lane.fca.2.extract, <16 x i8> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_u16(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlseg4e16.v v8, (a1)
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vmv.s.x v0, a0
; CHECK-NEXT:    vsetivli zero, 6, e16, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v12, 5
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v12, 4, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 3, v0.t
; CHECK-NEXT:    vslideup.vi v11, v12, 2, v0.t
; CHECK-NEXT:    vsseg4e16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  %vld4_lane = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4lane.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, i64 5, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4_lane.fca.0.extract, <8 x i16> %vld4_lane.fca.1.extract, <8 x i16> %vld4_lane.fca.2.extract, <8 x i16> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_u32(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlseg4e32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v9, v12, 1, v0.t
; CHECK-NEXT:    vslidedown.vi v10, v12, 2, v0.t
; CHECK-NEXT:    vslidedown.vi v11, v12, 3, v0.t
; CHECK-NEXT:    vsseg4e32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  %vld4_lane = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4lane.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, i64 0, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4_lane.fca.0.extract, <4 x i32> %vld4_lane.fca.1.extract, <4 x i32> %vld4_lane.fca.2.extract, <4 x i32> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_u64(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    sd s0, 56(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s1, 48(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s2, 40(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s3, 32(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s4, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s5, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    sd s6, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -8
; CHECK-NEXT:    .cfi_offset s1, -16
; CHECK-NEXT:    .cfi_offset s2, -24
; CHECK-NEXT:    .cfi_offset s3, -32
; CHECK-NEXT:    .cfi_offset s4, -40
; CHECK-NEXT:    .cfi_offset s5, -48
; CHECK-NEXT:    .cfi_offset s6, -56
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg4e64.v v8, (a1)
; CHECK-NEXT:    lbu a1, 0(a0)
; CHECK-NEXT:    lbu a3, 1(a0)
; CHECK-NEXT:    lbu a4, 2(a0)
; CHECK-NEXT:    lbu a5, 3(a0)
; CHECK-NEXT:    lbu a6, 4(a0)
; CHECK-NEXT:    lbu a7, 5(a0)
; CHECK-NEXT:    lbu t0, 6(a0)
; CHECK-NEXT:    lbu t1, 7(a0)
; CHECK-NEXT:    lbu t2, 8(a0)
; CHECK-NEXT:    lbu t3, 9(a0)
; CHECK-NEXT:    lbu t4, 10(a0)
; CHECK-NEXT:    lbu t5, 11(a0)
; CHECK-NEXT:    lbu t6, 12(a0)
; CHECK-NEXT:    lbu s0, 13(a0)
; CHECK-NEXT:    lbu s1, 14(a0)
; CHECK-NEXT:    lbu s2, 15(a0)
; CHECK-NEXT:    slli a3, a3, 8
; CHECK-NEXT:    slli a4, a4, 16
; CHECK-NEXT:    slli a5, a5, 24
; CHECK-NEXT:    slli a7, a7, 8
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a3, a5, a4
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    lbu s3, 16(a0)
; CHECK-NEXT:    lbu s4, 17(a0)
; CHECK-NEXT:    lbu s5, 18(a0)
; CHECK-NEXT:    lbu s6, 19(a0)
; CHECK-NEXT:    slli t0, t0, 16
; CHECK-NEXT:    slli t1, t1, 24
; CHECK-NEXT:    slli t3, t3, 8
; CHECK-NEXT:    slli t4, t4, 16
; CHECK-NEXT:    slli t5, t5, 24
; CHECK-NEXT:    slli s0, s0, 8
; CHECK-NEXT:    or a5, t1, t0
; CHECK-NEXT:    or a6, t3, t2
; CHECK-NEXT:    or a7, t5, t4
; CHECK-NEXT:    or t0, s0, t6
; CHECK-NEXT:    lbu t1, 20(a0)
; CHECK-NEXT:    lbu t2, 21(a0)
; CHECK-NEXT:    lbu t3, 22(a0)
; CHECK-NEXT:    lbu t4, 23(a0)
; CHECK-NEXT:    slli s1, s1, 16
; CHECK-NEXT:    slli s2, s2, 24
; CHECK-NEXT:    slli s4, s4, 8
; CHECK-NEXT:    slli s5, s5, 16
; CHECK-NEXT:    slli s6, s6, 24
; CHECK-NEXT:    slli t2, t2, 8
; CHECK-NEXT:    or t5, s2, s1
; CHECK-NEXT:    or t6, s4, s3
; CHECK-NEXT:    or s0, s6, s5
; CHECK-NEXT:    or t1, t2, t1
; CHECK-NEXT:    lbu t2, 24(a0)
; CHECK-NEXT:    lbu s1, 25(a0)
; CHECK-NEXT:    lbu s2, 26(a0)
; CHECK-NEXT:    lbu s3, 27(a0)
; CHECK-NEXT:    slli t3, t3, 16
; CHECK-NEXT:    slli t4, t4, 24
; CHECK-NEXT:    slli s1, s1, 8
; CHECK-NEXT:    slli s2, s2, 16
; CHECK-NEXT:    slli s3, s3, 24
; CHECK-NEXT:    or t3, t4, t3
; CHECK-NEXT:    or t2, s1, t2
; CHECK-NEXT:    or t4, s3, s2
; CHECK-NEXT:    lbu s1, 29(a0)
; CHECK-NEXT:    lbu s2, 28(a0)
; CHECK-NEXT:    lbu s3, 30(a0)
; CHECK-NEXT:    lbu a0, 31(a0)
; CHECK-NEXT:    slli s1, s1, 8
; CHECK-NEXT:    or s1, s1, s2
; CHECK-NEXT:    slli s3, s3, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a0, a0, s3
; CHECK-NEXT:    or a1, a3, a1
; CHECK-NEXT:    or a4, a5, a4
; CHECK-NEXT:    or a3, a7, a6
; CHECK-NEXT:    or a5, t5, t0
; CHECK-NEXT:    or a6, s0, t6
; CHECK-NEXT:    or a7, t3, t1
; CHECK-NEXT:    or t0, t4, t2
; CHECK-NEXT:    or a0, a0, s1
; CHECK-NEXT:    slli a4, a4, 32
; CHECK-NEXT:    or a1, a4, a1
; CHECK-NEXT:    slli a5, a5, 32
; CHECK-NEXT:    or a3, a5, a3
; CHECK-NEXT:    slli a7, a7, 32
; CHECK-NEXT:    or a4, a7, a6
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    or a0, a0, t0
; CHECK-NEXT:    vmv.s.x v12, a1
; CHECK-NEXT:    vslideup.vi v8, v12, 1
; CHECK-NEXT:    vmv.s.x v12, a3
; CHECK-NEXT:    vslideup.vi v9, v12, 1
; CHECK-NEXT:    vmv.s.x v12, a4
; CHECK-NEXT:    vslideup.vi v10, v12, 1
; CHECK-NEXT:    vmv.s.x v12, a0
; CHECK-NEXT:    vslideup.vi v11, v12, 1
; CHECK-NEXT:    vsseg4e64.v v8, (a2)
; CHECK-NEXT:    ld s0, 56(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s1, 48(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s2, 40(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s3, 32(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s4, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s5, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ld s6, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s2
; CHECK-NEXT:    .cfi_restore s3
; CHECK-NEXT:    .cfi_restore s4
; CHECK-NEXT:    .cfi_restore s5
; CHECK-NEXT:    .cfi_restore s6
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  %vld4_lane = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4lane.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, i64 1, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4_lane.fca.0.extract, <2 x i64> %vld4_lane.fca.1.extract, <2 x i64> %vld4_lane.fca.2.extract, <2 x i64> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_lane_u8(ptr noundef %in_0, ptr noundef %in_1, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_lane_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlseg4e8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 8
; CHECK-NEXT:    vsetivli zero, 4, e8, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v12, 3
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vslideup.vi v9, v12, 2, v0.t
; CHECK-NEXT:    vslideup.vi v10, v12, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.i v0, -9
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmerge.vvm v11, v12, v11, v0
; CHECK-NEXT:    vsseg4e8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  %vld4_lane = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4lane.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, i64 3, ptr %in_0)
  %vld4_lane.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 0
  %vld4_lane.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 1
  %vld4_lane.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 2
  %vld4_lane.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4_lane, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4_lane.fca.0.extract, <16 x i8> %vld4_lane.fca.1.extract, <16 x i8> %vld4_lane.fca.2.extract, <16 x i8> %vld4_lane.fca.3.extract, ptr %out)
  ret void
}

declare void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2.v1f64.p0(ptr)
declare { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2lane.v1f64.p0(<1 x double>, <1 x double>, i64, ptr)
declare { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3lane.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, i64, ptr)
declare { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4lane.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, <1 x double>, i64, ptr)
declare { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2lane.v1i64.p0(<1 x i64>, <1 x i64>, i64, ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3lane.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, i64, ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4lane.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, <1 x i64>, i64, ptr)
declare { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2lane.v16i8.p0(<16 x i8>, <16 x i8>, i64, ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3lane.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, i64, ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4lane.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i64, ptr)
declare { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2.v2f64.p0(ptr)
declare { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2lane.v2f64.p0(<2 x double>, <2 x double>, i64, ptr)
declare { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3lane.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, i64, ptr)
declare { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4lane.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, <2 x double>, i64, ptr)
declare { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2.v2f32.p0(ptr)
declare { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2lane.v2f32.p0(<2 x float>, <2 x float>, i64, ptr)
declare { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3lane.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, i64, ptr)
declare { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4lane.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, <2 x float>, i64, ptr)
declare { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2lane.v2i32.p0(<2 x i32>, <2 x i32>, i64, ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3lane.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, i64, ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4lane.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, i64, ptr)
declare { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2lane.v2i64.p0(<2 x i64>, <2 x i64>, i64, ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3lane.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, i64, ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4lane.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, i64, ptr)
declare { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2.v4f32.p0(ptr)
declare { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2lane.v4f32.p0(<4 x float>, <4 x float>, i64, ptr)
declare { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3lane.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, i64, ptr)
declare { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4lane.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, <4 x float>, i64, ptr)
declare { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2.v4f16.p0(ptr)
declare { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2lane.v4f16.p0(<4 x half>, <4 x half>, i64, ptr)
declare { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3lane.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, i64, ptr)
declare { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4lane.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, <4 x half>, i64, ptr)
declare { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2lane.v4i16.p0(<4 x i16>, <4 x i16>, i64, ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3lane.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, i64, ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4lane.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, <4 x i16>, i64, ptr)
declare { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2lane.v4i32.p0(<4 x i32>, <4 x i32>, i64, ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3lane.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, i64, ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4lane.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, i64, ptr)
declare { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2.v8f16.p0(ptr)
declare { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2lane.v8f16.p0(<8 x half>, <8 x half>, i64, ptr)
declare { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3lane.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, i64, ptr)
declare { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4lane.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, <8 x half>, i64, ptr)
declare { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2lane.v8i16.p0(<8 x i16>, <8 x i16>, i64, ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3lane.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, i64, ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4lane.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, i64, ptr)
declare { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2lane.v8i8.p0(<8 x i8>, <8 x i8>, i64, ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3lane.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, i64, ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4lane.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, <8 x i8>, i64, ptr)
