; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vld2_dup_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2r.v4f16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x half>, <4 x half> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half> %vld2.fca.0.extract, <4 x half> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2r.v2f32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x float>, <2 x float> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float> %vld2.fca.0.extract, <2 x float> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg2e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2r.v1f64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x double>, <1 x double> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double> %vld2.fca.0.extract, <1 x double> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2r.v4i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2r.v2i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg2e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2r.v1i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2r.v8i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2r.v4i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i16>, <4 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16> %vld2.fca.0.extract, <4 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2r.v2i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i32>, <2 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32> %vld2.fca.0.extract, <2 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg2e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2r.v1i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <1 x i64>, <1 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64> %vld2.fca.0.extract, <1 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2_dup_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2_dup_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlsseg2e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2r.v8i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg2e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2r.v8f16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x half>, <8 x half> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half> %vld2.fca.0.extract, <8 x half> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg2e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2r.v4f32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x float>, <4 x float> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float> %vld2.fca.0.extract, <4 x float> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg2e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2r.v2f64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x double>, <2 x double> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double> %vld2.fca.0.extract, <2 x double> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg2e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2r.v8i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg2e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2r.v4i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg2e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2r.v2i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlsseg2e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2r.v16i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg2e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2r.v8i16.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i16>, <8 x i16> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> %vld2.fca.0.extract, <8 x i16> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg2e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2r.v4i32.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <4 x i32>, <4 x i32> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32> %vld2.fca.0.extract, <4 x i32> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg2e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2r.v2i64.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <2 x i64>, <2 x i64> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64> %vld2.fca.0.extract, <2 x i64> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld2q_dup_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld2q_dup_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlsseg2e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg2e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2r.v16i8.p0(ptr %in_0)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  tail call void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, ptr %out)
  ret void
}

define void @vld3_dup_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3r.v4f16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half> %vld3.fca.0.extract, <4 x half> %vld3.fca.1.extract, <4 x half> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3r.v2f32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float> %vld3.fca.0.extract, <2 x float> %vld3.fca.1.extract, <2 x float> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg3e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3r.v1f64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double> %vld3.fca.0.extract, <1 x double> %vld3.fca.1.extract, <1 x double> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3r.v4i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3r.v2i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg3e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3r.v1i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3r.v8i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3r.v4i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16> %vld3.fca.0.extract, <4 x i16> %vld3.fca.1.extract, <4 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3r.v2i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32> %vld3.fca.0.extract, <2 x i32> %vld3.fca.1.extract, <2 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg3e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3r.v1i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64> %vld3.fca.0.extract, <1 x i64> %vld3.fca.1.extract, <1 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3_dup_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3_dup_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlsseg3e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3r.v8i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8> %vld3.fca.0.extract, <8 x i8> %vld3.fca.1.extract, <8 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg3e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3r.v8f16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half> %vld3.fca.0.extract, <8 x half> %vld3.fca.1.extract, <8 x half> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg3e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3r.v4f32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float> %vld3.fca.0.extract, <4 x float> %vld3.fca.1.extract, <4 x float> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg3e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3r.v2f64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double> %vld3.fca.0.extract, <2 x double> %vld3.fca.1.extract, <2 x double> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg3e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3r.v8i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg3e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3r.v4i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg3e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3r.v2i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlsseg3e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3r.v16i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg3e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3r.v8i16.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> %vld3.fca.0.extract, <8 x i16> %vld3.fca.1.extract, <8 x i16> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg3e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3r.v4i32.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32> %vld3.fca.0.extract, <4 x i32> %vld3.fca.1.extract, <4 x i32> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg3e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3r.v2i64.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64> %vld3.fca.0.extract, <2 x i64> %vld3.fca.1.extract, <2 x i64> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld3q_dup_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld3q_dup_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlsseg3e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg3e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3r.v16i8.p0(ptr %in_0)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  tail call void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, ptr %out)
  ret void
}

define void @vld4_dup_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4r.v4f16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x half>, <4 x half>, <4 x half>, <4 x half> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half> %vld4.fca.0.extract, <4 x half> %vld4.fca.1.extract, <4 x half> %vld4.fca.2.extract, <4 x half> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4r.v2f32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x float>, <2 x float>, <2 x float>, <2 x float> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float> %vld4.fca.0.extract, <2 x float> %vld4.fca.1.extract, <2 x float> %vld4.fca.2.extract, <2 x float> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg4e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4r.v1f64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x double>, <1 x double>, <1 x double>, <1 x double> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double> %vld4.fca.0.extract, <1 x double> %vld4.fca.1.extract, <1 x double> %vld4.fca.2.extract, <1 x double> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4r.v4i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4r.v2i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg4e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4r.v1i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4r.v8i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4r.v4i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16> %vld4.fca.0.extract, <4 x i16> %vld4.fca.1.extract, <4 x i16> %vld4.fca.2.extract, <4 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4r.v2i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32> %vld4.fca.0.extract, <2 x i32> %vld4.fca.1.extract, <2 x i32> %vld4.fca.2.extract, <2 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg4e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4r.v1i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64> %vld4.fca.0.extract, <1 x i64> %vld4.fca.1.extract, <1 x i64> %vld4.fca.2.extract, <1 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4_dup_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4_dup_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vlsseg4e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4r.v8i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_f16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg4e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4r.v8f16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x half>, <8 x half>, <8 x half>, <8 x half> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half> %vld4.fca.0.extract, <8 x half> %vld4.fca.1.extract, <8 x half> %vld4.fca.2.extract, <8 x half> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_f32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg4e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4r.v4f32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x float>, <4 x float>, <4 x float>, <4 x float> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float> %vld4.fca.0.extract, <4 x float> %vld4.fca.1.extract, <4 x float> %vld4.fca.2.extract, <4 x float> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_f64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg4e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4r.v2f64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x double>, <2 x double>, <2 x double>, <2 x double> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double> %vld4.fca.0.extract, <2 x double> %vld4.fca.1.extract, <2 x double> %vld4.fca.2.extract, <2 x double> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_s16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg4e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4r.v8i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_s32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg4e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4r.v4i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_s64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg4e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4r.v2i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_s8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlsseg4e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4r.v16i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_u16(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vlsseg4e16.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4r.v8i16.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> %vld4.fca.0.extract, <8 x i16> %vld4.fca.1.extract, <8 x i16> %vld4.fca.2.extract, <8 x i16> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_u32(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vlsseg4e32.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4r.v4i32.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32> %vld4.fca.0.extract, <4 x i32> %vld4.fca.1.extract, <4 x i32> %vld4.fca.2.extract, <4 x i32> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_u64(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlsseg4e64.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4r.v2i64.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64> %vld4.fca.0.extract, <2 x i64> %vld4.fca.1.extract, <2 x i64> %vld4.fca.2.extract, <2 x i64> %vld4.fca.3.extract, ptr %out)
  ret void
}

define void @vld4q_dup_u8(ptr noundef %in_0, ptr nocapture noundef %out) {
; CHECK-LABEL: vld4q_dup_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vlsseg4e8.v v8, (a0), zero
; CHECK-NEXT:    vsseg4e8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4r.v16i8.p0(ptr %in_0)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  tail call void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, ptr %out)
  ret void
}

declare void @llvm.aarch64.neon.st2.v16i8.p0(<16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v1f64.p0(<1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v1i64.p0(<1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2f32.p0(<2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2f64.p0(<2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2i32.p0(<2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v2i64.p0(<2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4f16.p0(<4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4f32.p0(<4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4i16.p0(<4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v4i32.p0(<4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8f16.p0(<8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st2.v8i8.p0(<8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st3.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v16i8.p0(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v1f64.p0(<1 x double>, <1 x double>, <1 x double>, <1 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v1i64.p0(<1 x i64>, <1 x i64>, <1 x i64>, <1 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2f32.p0(<2 x float>, <2 x float>, <2 x float>, <2 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2f64.p0(<2 x double>, <2 x double>, <2 x double>, <2 x double>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2i32.p0(<2 x i32>, <2 x i32>, <2 x i32>, <2 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v2i64.p0(<2 x i64>, <2 x i64>, <2 x i64>, <2 x i64>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4f16.p0(<4 x half>, <4 x half>, <4 x half>, <4 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4f32.p0(<4 x float>, <4 x float>, <4 x float>, <4 x float>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4i16.p0(<4 x i16>, <4 x i16>, <4 x i16>, <4 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v4i32.p0(<4 x i32>, <4 x i32>, <4 x i32>, <4 x i32>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8f16.p0(<8 x half>, <8 x half>, <8 x half>, <8 x half>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16>, <8 x i16>, <8 x i16>, <8 x i16>, ptr nocapture)
declare void @llvm.aarch64.neon.st4.v8i8.p0(<8 x i8>, <8 x i8>, <8 x i8>, <8 x i8>, ptr nocapture)
declare { <1 x double>, <1 x double> } @llvm.aarch64.neon.ld2r.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld3r.v1f64.p0(ptr)
declare { <1 x double>, <1 x double>, <1 x double>, <1 x double> } @llvm.aarch64.neon.ld4r.v1f64.p0(ptr)
declare { <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld2r.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld3r.v1i64.p0(ptr)
declare { <1 x i64>, <1 x i64>, <1 x i64>, <1 x i64> } @llvm.aarch64.neon.ld4r.v1i64.p0(ptr)
declare { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld2r.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld3r.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld4r.v16i8.p0(ptr)
declare { <2 x double>, <2 x double> } @llvm.aarch64.neon.ld2r.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld3r.v2f64.p0(ptr)
declare { <2 x double>, <2 x double>, <2 x double>, <2 x double> } @llvm.aarch64.neon.ld4r.v2f64.p0(ptr)
declare { <2 x float>, <2 x float> } @llvm.aarch64.neon.ld2r.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld3r.v2f32.p0(ptr)
declare { <2 x float>, <2 x float>, <2 x float>, <2 x float> } @llvm.aarch64.neon.ld4r.v2f32.p0(ptr)
declare { <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld2r.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld3r.v2i32.p0(ptr)
declare { <2 x i32>, <2 x i32>, <2 x i32>, <2 x i32> } @llvm.aarch64.neon.ld4r.v2i32.p0(ptr)
declare { <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld2r.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld3r.v2i64.p0(ptr)
declare { <2 x i64>, <2 x i64>, <2 x i64>, <2 x i64> } @llvm.aarch64.neon.ld4r.v2i64.p0(ptr)
declare { <4 x float>, <4 x float> } @llvm.aarch64.neon.ld2r.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld3r.v4f32.p0(ptr)
declare { <4 x float>, <4 x float>, <4 x float>, <4 x float> } @llvm.aarch64.neon.ld4r.v4f32.p0(ptr)
declare { <4 x half>, <4 x half> } @llvm.aarch64.neon.ld2r.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld3r.v4f16.p0(ptr)
declare { <4 x half>, <4 x half>, <4 x half>, <4 x half> } @llvm.aarch64.neon.ld4r.v4f16.p0(ptr)
declare { <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld2r.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld3r.v4i16.p0(ptr)
declare { <4 x i16>, <4 x i16>, <4 x i16>, <4 x i16> } @llvm.aarch64.neon.ld4r.v4i16.p0(ptr)
declare { <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld2r.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld3r.v4i32.p0(ptr)
declare { <4 x i32>, <4 x i32>, <4 x i32>, <4 x i32> } @llvm.aarch64.neon.ld4r.v4i32.p0(ptr)
declare { <8 x half>, <8 x half> } @llvm.aarch64.neon.ld2r.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld3r.v8f16.p0(ptr)
declare { <8 x half>, <8 x half>, <8 x half>, <8 x half> } @llvm.aarch64.neon.ld4r.v8f16.p0(ptr)
declare { <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld2r.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld3r.v8i16.p0(ptr)
declare { <8 x i16>, <8 x i16>, <8 x i16>, <8 x i16> } @llvm.aarch64.neon.ld4r.v8i16.p0(ptr)
declare { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld2r.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld3r.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld4r.v8i8.p0(ptr)
