; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vmaxv_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredmax.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.smaxv.i32.v4i16(<4 x i16> %0)
  %1 = trunc i32 %vmaxv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vmaxv_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredmax.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vmaxv_s32.i = tail call i32 @llvm.aarch64.neon.smaxv.i32.v2i32(<2 x i32> %0)
  store i32 %vmaxv_s32.i, ptr %out, align 4
  ret void
}

define void @vmaxv_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredmax.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.smaxv.i32.v8i8(<8 x i8> %0)
  %1 = trunc i32 %vmaxv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vmaxv_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredmaxu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v4i16(<4 x i16> %0)
  %1 = trunc i32 %vmaxv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vmaxv_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredmaxu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vmaxv_u32.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v2i32(<2 x i32> %0)
  store i32 %vmaxv_u32.i, ptr %out, align 4
  ret void
}

define void @vmaxv_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredmaxu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v8i8(<8 x i8> %0)
  %1 = trunc i32 %vmaxv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vmaxvq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredmax.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.smaxv.i32.v8i16(<8 x i16> %0)
  %1 = trunc i32 %vmaxv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vmaxvq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredmax.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vmaxvq_s32.i = tail call i32 @llvm.aarch64.neon.smaxv.i32.v4i32(<4 x i32> %0)
  store i32 %vmaxvq_s32.i, ptr %out, align 4
  ret void
}

define void @vmaxvq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredmax.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.smaxv.i32.v16i8(<16 x i8> %0)
  %1 = trunc i32 %vmaxv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vmaxvq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredmaxu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v8i16(<8 x i16> %0)
  %1 = trunc i32 %vmaxv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vmaxvq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredmaxu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vmaxvq_u32.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v4i32(<4 x i32> %0)
  store i32 %vmaxvq_u32.i, ptr %out, align 4
  ret void
}

define void @vmaxvq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredmaxu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vmaxv.i = tail call i32 @llvm.aarch64.neon.umaxv.i32.v16i8(<16 x i8> %0)
  %1 = trunc i32 %vmaxv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vminv_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredmin.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vminv.i = tail call i32 @llvm.aarch64.neon.sminv.i32.v4i16(<4 x i16> %0)
  %1 = trunc i32 %vminv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vminv_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredmin.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vminv_s32.i = tail call i32 @llvm.aarch64.neon.sminv.i32.v2i32(<2 x i32> %0)
  store i32 %vminv_s32.i, ptr %out, align 4
  ret void
}

define void @vminv_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredmin.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vminv.i = tail call i32 @llvm.aarch64.neon.sminv.i32.v8i8(<8 x i8> %0)
  %1 = trunc i32 %vminv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vminv_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredminu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v4i16(<4 x i16> %0)
  %1 = trunc i32 %vminv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vminv_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredminu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vminv_u32.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v2i32(<2 x i32> %0)
  store i32 %vminv_u32.i, ptr %out, align 4
  ret void
}

define void @vminv_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredminu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v8i8(<8 x i8> %0)
  %1 = trunc i32 %vminv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vminvq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredmin.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vminv.i = tail call i32 @llvm.aarch64.neon.sminv.i32.v8i16(<8 x i16> %0)
  %1 = trunc i32 %vminv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vminvq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredmin.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vminvq_s32.i = tail call i32 @llvm.aarch64.neon.sminv.i32.v4i32(<4 x i32> %0)
  store i32 %vminvq_s32.i, ptr %out, align 4
  ret void
}

define void @vminvq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredmin.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vminv.i = tail call i32 @llvm.aarch64.neon.sminv.i32.v16i8(<16 x i8> %0)
  %1 = trunc i32 %vminv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

define void @vminvq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vredminu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v8i16(<8 x i16> %0)
  %1 = trunc i32 %vminv.i to i16
  store i16 %1, ptr %out, align 2
  ret void
}

define void @vminvq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vredminu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vminvq_u32.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v4i32(<4 x i32> %0)
  store i32 %vminvq_u32.i, ptr %out, align 4
  ret void
}

define void @vminvq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vredminu.vs v8, v8, v8
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vminv.i = tail call i32 @llvm.aarch64.neon.uminv.i32.v16i8(<16 x i8> %0)
  %1 = trunc i32 %vminv.i to i8
  store i8 %1, ptr %out, align 1
  ret void
}

declare i32 @llvm.aarch64.neon.smaxv.i32.v16i8(<16 x i8>)
declare i32 @llvm.aarch64.neon.smaxv.i32.v2i32(<2 x i32>)
declare i32 @llvm.aarch64.neon.smaxv.i32.v4i16(<4 x i16>)
declare i32 @llvm.aarch64.neon.smaxv.i32.v4i32(<4 x i32>)
declare i32 @llvm.aarch64.neon.smaxv.i32.v8i16(<8 x i16>)
declare i32 @llvm.aarch64.neon.smaxv.i32.v8i8(<8 x i8>)
declare i32 @llvm.aarch64.neon.sminv.i32.v16i8(<16 x i8>)
declare i32 @llvm.aarch64.neon.sminv.i32.v2i32(<2 x i32>)
declare i32 @llvm.aarch64.neon.sminv.i32.v4i16(<4 x i16>)
declare i32 @llvm.aarch64.neon.sminv.i32.v4i32(<4 x i32>)
declare i32 @llvm.aarch64.neon.sminv.i32.v8i16(<8 x i16>)
declare i32 @llvm.aarch64.neon.sminv.i32.v8i8(<8 x i8>)
declare i32 @llvm.aarch64.neon.umaxv.i32.v16i8(<16 x i8>)
declare i32 @llvm.aarch64.neon.umaxv.i32.v2i32(<2 x i32>)
declare i32 @llvm.aarch64.neon.umaxv.i32.v4i16(<4 x i16>)
declare i32 @llvm.aarch64.neon.umaxv.i32.v4i32(<4 x i32>)
declare i32 @llvm.aarch64.neon.umaxv.i32.v8i16(<8 x i16>)
declare i32 @llvm.aarch64.neon.umaxv.i32.v8i8(<8 x i8>)
declare i32 @llvm.aarch64.neon.uminv.i32.v16i8(<16 x i8>)
declare i32 @llvm.aarch64.neon.uminv.i32.v2i32(<2 x i32>)
declare i32 @llvm.aarch64.neon.uminv.i32.v4i16(<4 x i16>)
declare i32 @llvm.aarch64.neon.uminv.i32.v4i32(<4 x i32>)
declare i32 @llvm.aarch64.neon.uminv.i32.v8i16(<8 x i16>)
declare i32 @llvm.aarch64.neon.uminv.i32.v8i8(<8 x i8>)
