; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vmaxnm_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxnm_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vmaxnm2.i = tail call <4 x half> @llvm.aarch64.neon.fmaxnm.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vmaxnm2.i, ptr %out, align 2
  ret void
}

define void @vmaxnm_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxnm_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, 523264
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vmerge.vxm v8, v8, a1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vmaxnm2.i = tail call <2 x float> @llvm.aarch64.neon.fmaxnm.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vmaxnm2.i, ptr %out, align 4
  ret void
}

define void @vmaxnm_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxnm_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI2_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI2_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vmaxnm2.i = tail call <1 x double> @llvm.aarch64.neon.fmaxnm.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x double> %vmaxnm2.i, ptr %out, align 8
  ret void
}

define void @vmaxnmq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxnmq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI3_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI3_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vmaxnm2.i = tail call <8 x half> @llvm.aarch64.neon.fmaxnm.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vmaxnm2.i, ptr %out, align 2
  ret void
}

define void @vmaxnmq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxnmq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, 523264
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vmerge.vxm v8, v8, a1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vmaxnm2.i = tail call <4 x float> @llvm.aarch64.neon.fmaxnm.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vmaxnm2.i, ptr %out, align 4
  ret void
}

define void @vmaxnmq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxnmq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI5_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI5_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vmaxnm2.i = tail call <2 x double> @llvm.aarch64.neon.fmaxnm.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vmaxnm2.i, ptr %out, align 8
  ret void
}

define void @vminnm_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminnm_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI6_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI6_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vminnm2.i = tail call <4 x half> @llvm.aarch64.neon.fminnm.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vminnm2.i, ptr %out, align 2
  ret void
}

define void @vminnm_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminnm_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, 523264
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vmerge.vxm v8, v8, a1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vminnm2.i = tail call <2 x float> @llvm.aarch64.neon.fminnm.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vminnm2.i, ptr %out, align 4
  ret void
}

define void @vminnm_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminnm_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI8_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI8_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vminnm2.i = tail call <1 x double> @llvm.aarch64.neon.fminnm.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x double> %vminnm2.i, ptr %out, align 8
  ret void
}

define void @vminnmq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminnmq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI9_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI9_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vminnm2.i = tail call <8 x half> @llvm.aarch64.neon.fminnm.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vminnm2.i, ptr %out, align 2
  ret void
}

define void @vminnmq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminnmq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, 523264
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vmerge.vxm v8, v8, a1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vminnm2.i = tail call <4 x float> @llvm.aarch64.neon.fminnm.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vminnm2.i, ptr %out, align 4
  ret void
}

define void @vminnmq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminnmq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    lui a1, %hi(.LCPI11_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI11_0)(a1)
; CHECK-NEXT:    vfclass.v v10, v8
; CHECK-NEXT:    vfclass.v v11, v9
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vor.vv v9, v10, v11
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsne.vi v0, v9, 0
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vminnm2.i = tail call <2 x double> @llvm.aarch64.neon.fminnm.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vminnm2.i, ptr %out, align 8
  ret void
}

declare <1 x double> @llvm.aarch64.neon.fmaxnm.v1f64(<1 x double>, <1 x double>)
declare <1 x double> @llvm.aarch64.neon.fminnm.v1f64(<1 x double>, <1 x double>)
declare <2 x double> @llvm.aarch64.neon.fmaxnm.v2f64(<2 x double>, <2 x double>)
declare <2 x double> @llvm.aarch64.neon.fminnm.v2f64(<2 x double>, <2 x double>)
declare <2 x float> @llvm.aarch64.neon.fmaxnm.v2f32(<2 x float>, <2 x float>)
declare <2 x float> @llvm.aarch64.neon.fminnm.v2f32(<2 x float>, <2 x float>)
declare <4 x float> @llvm.aarch64.neon.fmaxnm.v4f32(<4 x float>, <4 x float>)
declare <4 x float> @llvm.aarch64.neon.fminnm.v4f32(<4 x float>, <4 x float>)
declare <4 x half> @llvm.aarch64.neon.fmaxnm.v4f16(<4 x half>, <4 x half>)
declare <4 x half> @llvm.aarch64.neon.fminnm.v4f16(<4 x half>, <4 x half>)
declare <8 x half> @llvm.aarch64.neon.fmaxnm.v8f16(<8 x half>, <8 x half>)
declare <8 x half> @llvm.aarch64.neon.fminnm.v8f16(<8 x half>, <8 x half>)
