; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vmaxv_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmax.vv v9, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 3
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmax.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vmfne.vv v9, v8, v8
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v9
; CHECK-NEXT:    vfmax.vv v8, v10, v8
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %vmaxv2 = tail call half @llvm.aarch64.neon.fmaxv.f16.v4f16(<4 x half> %0)
  store half %vmaxv2, ptr %out, align 2
  ret void
}

define void @vmaxv_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxv_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vxm v8, v8, a0, v0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %vmaxv_f32.i = tail call float @llvm.aarch64.neon.fmaxv.f32.v2f32(<2 x float> %0)
  store float %vmaxv_f32.i, ptr %out, align 4
  ret void
}

define void @vmaxvq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI2_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI2_0)(a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmax.vv v9, v8, v9
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmax.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 3
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vfmax.vv v9, v10, v9
; CHECK-NEXT:    vmfne.vv v10, v10, v10
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 4
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmax.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 5
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vfmax.vv v9, v10, v9
; CHECK-NEXT:    vmfne.vv v10, v10, v10
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 6
; CHECK-NEXT:    vslidedown.vi v8, v8, 7
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmax.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vmfne.vv v9, v8, v8
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v9
; CHECK-NEXT:    vfmax.vv v8, v10, v8
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %vmaxv2 = tail call half @llvm.aarch64.neon.fmaxv.f16.v8f16(<8 x half> %0)
  store half %vmaxv2, ptr %out, align 2
  ret void
}

define void @vmaxvq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vfmax.vv v9, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 3
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmerge.vxm v9, v9, a0, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmax.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vmfne.vv v9, v8, v8
; CHECK-NEXT:    vmerge.vxm v10, v10, a0, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v9
; CHECK-NEXT:    vfmax.vv v8, v10, v8
; CHECK-NEXT:    vmerge.vxm v8, v8, a0, v0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %vmaxvq_f32.i = tail call float @llvm.aarch64.neon.fmaxv.f32.v4f32(<4 x float> %0)
  store float %vmaxvq_f32.i, ptr %out, align 4
  ret void
}

define void @vmaxvq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxvq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI4_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI4_0)(a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vfmax.vv v8, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %vmaxvq_f64.i = tail call double @llvm.aarch64.neon.fmaxv.f64.v2f64(<2 x double> %0)
  store double %vmaxvq_f64.i, ptr %out, align 8
  ret void
}

define void @vminv_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI5_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI5_0)(a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmin.vv v9, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e16, mf2, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 3
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmin.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vmfne.vv v9, v8, v8
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v9
; CHECK-NEXT:    vfmin.vv v8, v10, v8
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %vminv2 = tail call half @llvm.aarch64.neon.fminv.f16.v4f16(<4 x half> %0)
  store half %vminv2, ptr %out, align 2
  ret void
}

define void @vminv_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminv_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vxm v8, v8, a0, v0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %vminv_f32.i = tail call float @llvm.aarch64.neon.fminv.f32.v2f32(<2 x float> %0)
  store float %vminv_f32.i, ptr %out, align 4
  ret void
}

define void @vminvq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI7_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI7_0)(a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmin.vv v9, v8, v9
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmin.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 3
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vfmin.vv v9, v10, v9
; CHECK-NEXT:    vmfne.vv v10, v10, v10
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 4
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmin.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 5
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vfmin.vv v9, v10, v9
; CHECK-NEXT:    vmfne.vv v10, v10, v10
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 6
; CHECK-NEXT:    vslidedown.vi v8, v8, 7
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vfmerge.vfm v9, v9, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmin.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vmfne.vv v9, v8, v8
; CHECK-NEXT:    vfmerge.vfm v10, v10, fa5, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v9
; CHECK-NEXT:    vfmin.vv v8, v10, v8
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %vminv2 = tail call half @llvm.aarch64.neon.fminv.f16.v8f16(<8 x half> %0)
  store half %vminv2, ptr %out, align 2
  ret void
}

define void @vminvq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vfmin.vv v9, v8, v9
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v8, v8, 3
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmerge.vxm v9, v9, a0, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vfmin.vv v10, v9, v10
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    vmfne.vv v9, v8, v8
; CHECK-NEXT:    vmerge.vxm v10, v10, a0, v0
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v9
; CHECK-NEXT:    vfmin.vv v8, v10, v8
; CHECK-NEXT:    vmerge.vxm v8, v8, a0, v0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %vminvq_f32.i = tail call float @llvm.aarch64.neon.fminv.f32.v4f32(<4 x float> %0)
  store float %vminvq_f32.i, ptr %out, align 4
  ret void
}

define void @vminvq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminvq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI9_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI9_0)(a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmfne.vv v10, v8, v8
; CHECK-NEXT:    vmfne.vv v11, v9, v9
; CHECK-NEXT:    vmor.mm v0, v10, v11
; CHECK-NEXT:    vfmin.vv v8, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %vminvq_f64.i = tail call double @llvm.aarch64.neon.fminv.f64.v2f64(<2 x double> %0)
  store double %vminvq_f64.i, ptr %out, align 8
  ret void
}

declare double @llvm.aarch64.neon.fmaxv.f64.v2f64(<2 x double>)
declare double @llvm.aarch64.neon.fminv.f64.v2f64(<2 x double>)
declare float @llvm.aarch64.neon.fmaxv.f32.v2f32(<2 x float>)
declare float @llvm.aarch64.neon.fmaxv.f32.v4f32(<4 x float>)
declare float @llvm.aarch64.neon.fminv.f32.v2f32(<2 x float>)
declare float @llvm.aarch64.neon.fminv.f32.v4f32(<4 x float>)
declare half @llvm.aarch64.neon.fmaxv.f16.v4f16(<4 x half>)
declare half @llvm.aarch64.neon.fmaxv.f16.v8f16(<8 x half>)
declare half @llvm.aarch64.neon.fminv.f16.v4f16(<4 x half>)
declare half @llvm.aarch64.neon.fminv.f16.v8f16(<8 x half>)
