; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vmax_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmax_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    vfmax.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vmax2.i = tail call <4 x half> @llvm.aarch64.neon.fmax.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vmax2.i, ptr %out, align 2
  ret void
}

define void @vmax_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmax_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vfmax.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vxm v8, v10, a0, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vmax2.i = tail call <2 x float> @llvm.aarch64.neon.fmax.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vmax2.i, ptr %out, align 4
  ret void
}

define void @vmax_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmax_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI2_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI2_0)(a0)
; CHECK-NEXT:    vfmax.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vmax2.i = tail call <1 x double> @llvm.aarch64.neon.fmax.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x double> %vmax2.i, ptr %out, align 8
  ret void
}

define void @vmaxq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI3_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI3_0)(a0)
; CHECK-NEXT:    vfmax.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vmax2.i = tail call <8 x half> @llvm.aarch64.neon.fmax.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vmax2.i, ptr %out, align 2
  ret void
}

define void @vmaxq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vfmax.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vxm v8, v10, a0, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vmax2.i = tail call <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vmax2.i, ptr %out, align 4
  ret void
}

define void @vmaxq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmaxq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI5_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI5_0)(a0)
; CHECK-NEXT:    vfmax.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vmax2.i = tail call <2 x double> @llvm.aarch64.neon.fmax.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vmax2.i, ptr %out, align 8
  ret void
}

define void @vmin_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmin_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI6_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI6_0)(a0)
; CHECK-NEXT:    vfmin.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vmin2.i = tail call <4 x half> @llvm.aarch64.neon.fmin.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vmin2.i, ptr %out, align 2
  ret void
}

define void @vmin_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmin_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vfmin.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vxm v8, v10, a0, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vmin2.i = tail call <2 x float> @llvm.aarch64.neon.fmin.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vmin2.i, ptr %out, align 4
  ret void
}

define void @vmin_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmin_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI8_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI8_0)(a0)
; CHECK-NEXT:    vfmin.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vmin2.i = tail call <1 x double> @llvm.aarch64.neon.fmin.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x double> %vmin2.i, ptr %out, align 8
  ret void
}

define void @vminq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI9_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI9_0)(a0)
; CHECK-NEXT:    vfmin.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vmin2.i = tail call <8 x half> @llvm.aarch64.neon.fmin.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vmin2.i, ptr %out, align 2
  ret void
}

define void @vminq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vfmin.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vxm v8, v10, a0, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vmin2.i = tail call <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vmin2.i, ptr %out, align 4
  ret void
}

define void @vminq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vminq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    lui a0, %hi(.LCPI11_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI11_0)(a0)
; CHECK-NEXT:    vfmin.vv v10, v8, v9
; CHECK-NEXT:    vmfne.vv v9, v9, v9
; CHECK-NEXT:    vmfne.vv v8, v8, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vfmerge.vfm v8, v10, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vmin2.i = tail call <2 x double> @llvm.aarch64.neon.fmin.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vmin2.i, ptr %out, align 8
  ret void
}

declare <1 x double> @llvm.aarch64.neon.fmax.v1f64(<1 x double>, <1 x double>)
declare <1 x double> @llvm.aarch64.neon.fmin.v1f64(<1 x double>, <1 x double>)
declare <2 x double> @llvm.aarch64.neon.fmax.v2f64(<2 x double>, <2 x double>)
declare <2 x double> @llvm.aarch64.neon.fmin.v2f64(<2 x double>, <2 x double>)
declare <2 x float> @llvm.aarch64.neon.fmax.v2f32(<2 x float>, <2 x float>)
declare <2 x float> @llvm.aarch64.neon.fmin.v2f32(<2 x float>, <2 x float>)
declare <4 x float> @llvm.aarch64.neon.fmax.v4f32(<4 x float>, <4 x float>)
declare <4 x float> @llvm.aarch64.neon.fmin.v4f32(<4 x float>, <4 x float>)
declare <4 x half> @llvm.aarch64.neon.fmax.v4f16(<4 x half>, <4 x half>)
declare <4 x half> @llvm.aarch64.neon.fmin.v4f16(<4 x half>, <4 x half>)
declare <8 x half> @llvm.aarch64.neon.fmax.v8f16(<8 x half>, <8 x half>)
declare <8 x half> @llvm.aarch64.neon.fmin.v8f16(<8 x half>, <8 x half>)
