; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vmlal_high_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_high_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    addi a2, a2, 8
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a2)
; CHECK-NEXT:    vwmacc.vv v8, v9, v10
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <8 x i16>, ptr %in_1, align 2
  %2 = load <8 x i16>, ptr %in_2, align 2
  %shuffle.i.i = shufflevector <8 x i16> %1, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %shuffle.i3.i = shufflevector <8 x i16> %2, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %vmull2.i.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %shuffle.i.i, <4 x i16> %shuffle.i3.i)
  %add.i.i = add <4 x i32> %vmull2.i.i.i, %0
  store <4 x i32> %add.i.i, ptr %out, align 4
  ret void
}

define void @vmlal_high_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_high_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    addi a2, a2, 8
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a2)
; CHECK-NEXT:    vwmacc.vv v8, v9, v10
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <4 x i32>, ptr %in_1, align 4
  %2 = load <4 x i32>, ptr %in_2, align 4
  %shuffle.i.i = shufflevector <4 x i32> %1, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %shuffle.i3.i = shufflevector <4 x i32> %2, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %vmull2.i.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %shuffle.i.i, <2 x i32> %shuffle.i3.i)
  %add.i.i = add <2 x i64> %vmull2.i.i.i, %0
  store <2 x i64> %add.i.i, ptr %out, align 8
  ret void
}

define void @vmlal_high_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_high_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    addi a2, a2, 8
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    vwmacc.vv v8, v9, v10
; CHECK-NEXT:    vse16.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <16 x i8>, ptr %in_2, align 1
  %shuffle.i.i = shufflevector <16 x i8> %1, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shuffle.i3.i = shufflevector <16 x i8> %2, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vmull.i.i.i = tail call <8 x i16> @llvm.aarch64.neon.smull.v8i16(<8 x i8> %shuffle.i.i, <8 x i8> %shuffle.i3.i)
  %add.i.i = add <8 x i16> %vmull.i.i.i, %0
  store <8 x i16> %add.i.i, ptr %out, align 2
  ret void
}

define void @vmlal_high_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_high_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    addi a2, a2, 8
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a2)
; CHECK-NEXT:    vwmaccu.vv v8, v9, v10
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <8 x i16>, ptr %in_1, align 2
  %2 = load <8 x i16>, ptr %in_2, align 2
  %shuffle.i.i = shufflevector <8 x i16> %1, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %shuffle.i3.i = shufflevector <8 x i16> %2, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %vmull2.i.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %shuffle.i.i, <4 x i16> %shuffle.i3.i)
  %add.i.i = add <4 x i32> %vmull2.i.i.i, %0
  store <4 x i32> %add.i.i, ptr %out, align 4
  ret void
}

define void @vmlal_high_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_high_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    addi a2, a2, 8
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a2)
; CHECK-NEXT:    vwmaccu.vv v8, v9, v10
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <4 x i32>, ptr %in_1, align 4
  %2 = load <4 x i32>, ptr %in_2, align 4
  %shuffle.i.i = shufflevector <4 x i32> %1, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %shuffle.i3.i = shufflevector <4 x i32> %2, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %vmull2.i.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %shuffle.i.i, <2 x i32> %shuffle.i3.i)
  %add.i.i = add <2 x i64> %vmull2.i.i.i, %0
  store <2 x i64> %add.i.i, ptr %out, align 8
  ret void
}

define void @vmlal_high_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_high_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    addi a2, a2, 8
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    vwmaccu.vv v8, v9, v10
; CHECK-NEXT:    vse16.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <16 x i8>, ptr %in_2, align 1
  %shuffle.i.i = shufflevector <16 x i8> %1, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shuffle.i3.i = shufflevector <16 x i8> %2, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vmull.i.i.i = tail call <8 x i16> @llvm.aarch64.neon.umull.v8i16(<8 x i8> %shuffle.i.i, <8 x i8> %shuffle.i3.i)
  %add.i.i = add <8 x i16> %vmull.i.i.i, %0
  store <8 x i16> %add.i.i, ptr %out, align 2
  ret void
}

define void @vmlal_lane_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_lane_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lh a0, 6(a2)
; CHECK-NEXT:    vwmacc.vx v8, a0, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <4 x i16>, ptr %in_2, align 2
  %lane = shufflevector <4 x i16> %2, <4 x i16> poison, <4 x i32> <i32 3, i32 3, i32 3, i32 3>
  %vmull2.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %1, <4 x i16> %lane)
  %add = add <4 x i32> %vmull2.i, %0
  store <4 x i32> %add, ptr %out, align 4
  ret void
}

define void @vmlal_lane_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_lane_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lw a0, 4(a2)
; CHECK-NEXT:    vwmacc.vx v8, a0, v9
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <2 x i32>, ptr %in_2, align 4
  %lane = shufflevector <2 x i32> %2, <2 x i32> poison, <2 x i32> <i32 1, i32 1>
  %vmull2.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %1, <2 x i32> %lane)
  %add = add <2 x i64> %vmull2.i, %0
  store <2 x i64> %add, ptr %out, align 8
  ret void
}

define void @vmlal_lane_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_lane_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lh a0, 4(a2)
; CHECK-NEXT:    vwmaccu.vx v8, a0, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <4 x i16>, ptr %in_2, align 2
  %lane = shufflevector <4 x i16> %2, <4 x i16> poison, <4 x i32> <i32 2, i32 2, i32 2, i32 2>
  %vmull2.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %1, <4 x i16> %lane)
  %add = add <4 x i32> %vmull2.i, %0
  store <4 x i32> %add, ptr %out, align 4
  ret void
}

define void @vmlal_lane_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_lane_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lw a0, 4(a2)
; CHECK-NEXT:    vwmaccu.vx v8, a0, v9
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <2 x i32>, ptr %in_2, align 4
  %lane = shufflevector <2 x i32> %2, <2 x i32> poison, <2 x i32> <i32 1, i32 1>
  %vmull2.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %1, <2 x i32> %lane)
  %add = add <2 x i64> %vmull2.i, %0
  store <2 x i64> %add, ptr %out, align 8
  ret void
}

define void @vmlal_laneq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_laneq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lh a0, 14(a2)
; CHECK-NEXT:    vwmacc.vx v8, a0, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <8 x i16>, ptr %in_2, align 2
  %lane = shufflevector <8 x i16> %2, <8 x i16> poison, <4 x i32> <i32 7, i32 7, i32 7, i32 7>
  %vmull2.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %1, <4 x i16> %lane)
  %add = add <4 x i32> %vmull2.i, %0
  store <4 x i32> %add, ptr %out, align 4
  ret void
}

define void @vmlal_laneq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_laneq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lw a0, 0(a2)
; CHECK-NEXT:    vwmacc.vx v8, a0, v9
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <4 x i32>, ptr %in_2, align 4
  %lane = shufflevector <4 x i32> %2, <4 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %1, <2 x i32> %lane)
  %add = add <2 x i64> %vmull2.i, %0
  store <2 x i64> %add, ptr %out, align 8
  ret void
}

define void @vmlal_laneq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_laneq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    lh a0, 0(a2)
; CHECK-NEXT:    vwmaccu.vx v8, a0, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <8 x i16>, ptr %in_2, align 2
  %lane = shufflevector <8 x i16> %2, <8 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %1, <4 x i16> %lane)
  %add = add <4 x i32> %vmull2.i, %0
  store <4 x i32> %add, ptr %out, align 4
  ret void
}

define void @vmlal_laneq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_laneq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    lw a0, 4(a2)
; CHECK-NEXT:    vwmaccu.vx v8, a0, v9
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <4 x i32>, ptr %in_2, align 4
  %lane = shufflevector <4 x i32> %2, <4 x i32> poison, <2 x i32> <i32 1, i32 1>
  %vmull2.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %1, <2 x i32> %lane)
  %add = add <2 x i64> %vmull2.i, %0
  store <2 x i64> %add, ptr %out, align 8
  ret void
}

define void @vmlal_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i16 noundef signext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmacc.vx v8, a2, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_2, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %1, <4 x i16> %vecinit3.i)
  %add.i = add <4 x i32> %vmull2.i.i, %0
  store <4 x i32> %add.i, ptr %out, align 4
  ret void
}

define void @vmlal_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i32 noundef signext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmacc.vx v8, a2, v9
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_2, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %1, <2 x i32> %vecinit1.i)
  %add.i = add <2 x i64> %vmull2.i.i, %0
  store <2 x i64> %add.i, ptr %out, align 8
  ret void
}

define void @vmlal_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i16 noundef zeroext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmaccu.vx v8, a2, v9
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_2, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %1, <4 x i16> %vecinit3.i)
  %add.i = add <4 x i32> %vmull2.i.i, %0
  store <4 x i32> %add.i, ptr %out, align 4
  ret void
}

define void @vmlal_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i32 noundef signext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmaccu.vx v8, a2, v9
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_2, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %1, <2 x i32> %vecinit1.i)
  %add.i = add <2 x i64> %vmull2.i.i, %0
  store <2 x i64> %add.i, ptr %out, align 8
  ret void
}

define void @vmlal_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a2)
; CHECK-NEXT:    vwmacc.vv v8, v9, v10
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <4 x i16>, ptr %in_2, align 2
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %1, <4 x i16> %2)
  %add.i = add <4 x i32> %vmull2.i.i, %0
  store <4 x i32> %add.i, ptr %out, align 4
  ret void
}

define void @vmlal_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a2)
; CHECK-NEXT:    vwmacc.vv v8, v9, v10
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <2 x i32>, ptr %in_2, align 4
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %1, <2 x i32> %2)
  %add.i = add <2 x i64> %vmull2.i.i, %0
  store <2 x i64> %add.i, ptr %out, align 8
  ret void
}

define void @vmlal_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    vwmacc.vv v8, v9, v10
; CHECK-NEXT:    vse16.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vmull.i.i = tail call <8 x i16> @llvm.aarch64.neon.smull.v8i16(<8 x i8> %1, <8 x i8> %2)
  %add.i = add <8 x i16> %vmull.i.i, %0
  store <8 x i16> %add.i, ptr %out, align 2
  ret void
}

define void @vmlal_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vle16.v v10, (a2)
; CHECK-NEXT:    vwmaccu.vv v8, v9, v10
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <4 x i16>, ptr %in_2, align 2
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %1, <4 x i16> %2)
  %add.i = add <4 x i32> %vmull2.i.i, %0
  store <4 x i32> %add.i, ptr %out, align 4
  ret void
}

define void @vmlal_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vle32.v v10, (a2)
; CHECK-NEXT:    vwmaccu.vv v8, v9, v10
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <2 x i32>, ptr %in_2, align 4
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %1, <2 x i32> %2)
  %add.i = add <2 x i64> %vmull2.i.i, %0
  store <2 x i64> %add.i, ptr %out, align 8
  ret void
}

define void @vmlal_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlal_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    vwmaccu.vv v8, v9, v10
; CHECK-NEXT:    vse16.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vmull.i.i = tail call <8 x i16> @llvm.aarch64.neon.umull.v8i16(<8 x i8> %1, <8 x i8> %2)
  %add.i = add <8 x i16> %vmull.i.i, %0
  store <8 x i16> %add.i, ptr %out, align 2
  ret void
}

define void @vmlsl_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i16 noundef signext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vwmul.vx v10, v8, a2
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v9, v10
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_2, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %1, <4 x i16> %vecinit3.i)
  %sub.i = sub <4 x i32> %0, %vmull2.i.i
  store <4 x i32> %sub.i, ptr %out, align 4
  ret void
}

define void @vmlsl_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i32 noundef signext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vwmul.vx v10, v8, a2
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v9, v10
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_2, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %1, <2 x i32> %vecinit1.i)
  %sub.i = sub <2 x i64> %0, %vmull2.i.i
  store <2 x i64> %sub.i, ptr %out, align 8
  ret void
}

define void @vmlsl_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i16 noundef zeroext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vwmulu.vx v10, v8, a2
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v9, v10
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_2, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %1, <4 x i16> %vecinit3.i)
  %sub.i = sub <4 x i32> %0, %vmull2.i.i
  store <4 x i32> %sub.i, ptr %out, align 4
  ret void
}

define void @vmlsl_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, i32 noundef signext %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vwmulu.vx v10, v8, a2
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v9, v10
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_2, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %1, <2 x i32> %vecinit1.i)
  %sub.i = sub <2 x i64> %0, %vmull2.i.i
  store <2 x i64> %sub.i, ptr %out, align 8
  ret void
}

define void @vmlsl_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a2)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    vwmul.vv v11, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v10, v11
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <4 x i16>, ptr %in_2, align 2
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %1, <4 x i16> %2)
  %sub.i = sub <4 x i32> %0, %vmull2.i.i
  store <4 x i32> %sub.i, ptr %out, align 4
  ret void
}

define void @vmlsl_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a2)
; CHECK-NEXT:    vle64.v v10, (a0)
; CHECK-NEXT:    vwmul.vv v11, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v10, v11
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <2 x i32>, ptr %in_2, align 4
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %1, <2 x i32> %2)
  %sub.i = sub <2 x i64> %0, %vmull2.i.i
  store <2 x i64> %sub.i, ptr %out, align 8
  ret void
}

define void @vmlsl_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a2)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vwmul.vv v11, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v10, v11
; CHECK-NEXT:    vse16.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vmull.i.i = tail call <8 x i16> @llvm.aarch64.neon.smull.v8i16(<8 x i8> %1, <8 x i8> %2)
  %sub.i = sub <8 x i16> %0, %vmull.i.i
  store <8 x i16> %sub.i, ptr %out, align 2
  ret void
}

define void @vmlsl_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a2)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    vwmulu.vv v11, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v10, v11
; CHECK-NEXT:    vse32.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i16>, ptr %in_1, align 2
  %2 = load <4 x i16>, ptr %in_2, align 2
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %1, <4 x i16> %2)
  %sub.i = sub <4 x i32> %0, %vmull2.i.i
  store <4 x i32> %sub.i, ptr %out, align 4
  ret void
}

define void @vmlsl_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a2)
; CHECK-NEXT:    vle64.v v10, (a0)
; CHECK-NEXT:    vwmulu.vv v11, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v10, v11
; CHECK-NEXT:    vse64.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i32>, ptr %in_1, align 4
  %2 = load <2 x i32>, ptr %in_2, align 4
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %1, <2 x i32> %2)
  %sub.i = sub <2 x i64> %0, %vmull2.i.i
  store <2 x i64> %sub.i, ptr %out, align 8
  ret void
}

define void @vmlsl_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmlsl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a2)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vwmulu.vv v11, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsub.vv v8, v10, v11
; CHECK-NEXT:    vse16.v v8, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vmull.i.i = tail call <8 x i16> @llvm.aarch64.neon.umull.v8i16(<8 x i8> %1, <8 x i8> %2)
  %sub.i = sub <8 x i16> %0, %vmull.i.i
  store <8 x i16> %sub.i, ptr %out, align 2
  ret void
}

define void @vmull_high_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_high_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %shuffle.i.i = shufflevector <8 x i16> %0, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %shuffle.i3.i = shufflevector <8 x i16> %1, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %shuffle.i.i, <4 x i16> %shuffle.i3.i)
  store <4 x i32> %vmull2.i.i, ptr %out, align 4
  ret void
}

define void @vmull_high_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_high_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %shuffle.i.i = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %shuffle.i3.i = shufflevector <4 x i32> %1, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %shuffle.i.i, <2 x i32> %shuffle.i3.i)
  store <2 x i64> %vmull2.i.i, ptr %out, align 8
  ret void
}

define void @vmull_high_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_high_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %shuffle.i.i = shufflevector <16 x i8> %0, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shuffle.i3.i = shufflevector <16 x i8> %1, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vmull.i.i = tail call <8 x i16> @llvm.aarch64.neon.smull.v8i16(<8 x i8> %shuffle.i.i, <8 x i8> %shuffle.i3.i)
  store <8 x i16> %vmull.i.i, ptr %out, align 2
  ret void
}

define void @vmull_high_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_high_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmulu.vv v10, v8, v9
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %shuffle.i.i = shufflevector <8 x i16> %0, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %shuffle.i3.i = shufflevector <8 x i16> %1, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %shuffle.i.i, <4 x i16> %shuffle.i3.i)
  store <4 x i32> %vmull2.i.i, ptr %out, align 4
  ret void
}

define void @vmull_high_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_high_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmulu.vv v10, v8, v9
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %shuffle.i.i = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %shuffle.i3.i = shufflevector <4 x i32> %1, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %shuffle.i.i, <2 x i32> %shuffle.i3.i)
  store <2 x i64> %vmull2.i.i, ptr %out, align 8
  ret void
}

define void @vmull_high_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_high_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    addi a1, a1, 8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vwmulu.vv v10, v8, v9
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %shuffle.i.i = shufflevector <16 x i8> %0, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %shuffle.i3.i = shufflevector <16 x i8> %1, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vmull.i.i = tail call <8 x i16> @llvm.aarch64.neon.umull.v8i16(<8 x i8> %shuffle.i.i, <8 x i8> %shuffle.i3.i)
  store <8 x i16> %vmull.i.i, ptr %out, align 2
  ret void
}

define void @vmull_n_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vwmul.vx v9, v8, a1
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i32> %vmull2.i.i, ptr %out, align 4
  ret void
}

define void @vmull_n_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vwmul.vx v9, v8, a1
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i64> %vmull2.i.i, ptr %out, align 8
  ret void
}

define void @vmull_n_u16(ptr nocapture noundef readonly %in_0, i16 noundef zeroext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vwmulu.vx v9, v8, a1
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vmull2.i.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i32> %vmull2.i.i, ptr %out, align 4
  ret void
}

define void @vmull_n_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vwmulu.vx v9, v8, a1
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vmull2.i.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i64> %vmull2.i.i, ptr %out, align 8
  ret void
}

define void @vmull_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vmull2.i = tail call <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16> %0, <4 x i16> %1)
  store <4 x i32> %vmull2.i, ptr %out, align 4
  ret void
}

define void @vmull_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vmull2.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> %0, <2 x i32> %1)
  store <2 x i64> %vmull2.i, ptr %out, align 8
  ret void
}

define void @vmull_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vmull.i = tail call <8 x i16> @llvm.aarch64.neon.smull.v8i16(<8 x i8> %0, <8 x i8> %1)
  store <8 x i16> %vmull.i, ptr %out, align 2
  ret void
}

define void @vmull_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmulu.vv v10, v8, v9
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vmull2.i = tail call <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16> %0, <4 x i16> %1)
  store <4 x i32> %vmull2.i, ptr %out, align 4
  ret void
}

define void @vmull_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmulu.vv v10, v8, v9
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vmull2.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> %0, <2 x i32> %1)
  store <2 x i64> %vmull2.i, ptr %out, align 8
  ret void
}

define void @vmull_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vmull_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vwmulu.vv v10, v8, v9
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vmull.i = tail call <8 x i16> @llvm.aarch64.neon.umull.v8i16(<8 x i8> %0, <8 x i8> %1)
  store <8 x i16> %vmull.i, ptr %out, align 2
  ret void
}

declare <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32>, <2 x i32>)
declare <4 x i32> @llvm.aarch64.neon.smull.v4i32(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.umull.v4i32(<4 x i16>, <4 x i16>)
declare <8 x i16> @llvm.aarch64.neon.smull.v8i16(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.umull.v8i16(<8 x i8>, <8 x i8>)
