; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vpmax_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmax_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vslideup.vi v9, v8, 2
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v10, v11, v11
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vfmax.vv v8, v11, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vpmax2.i = tail call <4 x half> @llvm.aarch64.neon.fmaxp.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vpmax2.i, ptr %out, align 2
  ret void
}

define void @vpmax_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmax_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vmv1r.v v10, v8
; CHECK-NEXT:    vslideup.vi v10, v9, 1
; CHECK-NEXT:    vslidedown.vi v9, v8, 1, v0.t
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v8
; CHECK-NEXT:    vfmax.vv v8, v10, v9
; CHECK-NEXT:    vmerge.vxm v8, v8, a0, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vpmax2.i = tail call <2 x float> @llvm.aarch64.neon.fmaxp.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vpmax2.i, ptr %out, align 4
  ret void
}

define void @vpmaxq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmaxq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI2_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI2_0)(a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 4
; CHECK-NEXT:    vslideup.vi v9, v8, 4
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v10, v11, v11
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vfmax.vv v8, v11, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vpmax2.i = tail call <8 x half> @llvm.aarch64.neon.fmaxp.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vpmax2.i, ptr %out, align 2
  ret void
}

define void @vpmaxq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmaxq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    lui a1, 523264
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    vnsrl.wx v9, v9, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vslideup.vi v9, v8, 2
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v10, v11, v11
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vfmax.vv v8, v11, v9
; CHECK-NEXT:    vmerge.vxm v8, v8, a1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vpmax2.i = tail call <4 x float> @llvm.aarch64.neon.fmaxp.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vpmax2.i, ptr %out, align 4
  ret void
}

define void @vpmaxq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmaxq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    lui a0, %hi(.LCPI4_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI4_0)(a0)
; CHECK-NEXT:    vmv.v.v v10, v8
; CHECK-NEXT:    vslideup.vi v10, v9, 1
; CHECK-NEXT:    vslidedown.vi v9, v8, 1, v0.t
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v8
; CHECK-NEXT:    vfmax.vv v8, v10, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vpmax2.i = tail call <2 x double> @llvm.aarch64.neon.fmaxp.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vpmax2.i, ptr %out, align 8
  ret void
}

define void @vpmin_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmin_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI5_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI5_0)(a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vslideup.vi v9, v8, 2
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v10, v11, v11
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vfmin.vv v8, v11, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vpmin2.i = tail call <4 x half> @llvm.aarch64.neon.fminp.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vpmin2.i, ptr %out, align 2
  ret void
}

define void @vpmin_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpmin_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    lui a0, 523264
; CHECK-NEXT:    vmv1r.v v10, v8
; CHECK-NEXT:    vslideup.vi v10, v9, 1
; CHECK-NEXT:    vslidedown.vi v9, v8, 1, v0.t
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v8
; CHECK-NEXT:    vfmin.vv v8, v10, v9
; CHECK-NEXT:    vmerge.vxm v8, v8, a0, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vpmin2.i = tail call <2 x float> @llvm.aarch64.neon.fminp.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vpmin2.i, ptr %out, align 4
  ret void
}

define void @vpminq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpminq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI7_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI7_0)(a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wi v8, v8, 16
; CHECK-NEXT:    vnsrl.wi v9, v9, 16
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 4
; CHECK-NEXT:    vslideup.vi v9, v8, 4
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v10, v11, v11
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vfmin.vv v8, v11, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vpmin2.i = tail call <8 x half> @llvm.aarch64.neon.fminp.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vpmin2.i, ptr %out, align 2
  ret void
}

define void @vpminq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpminq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    lui a1, 523264
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v10, v8, 0
; CHECK-NEXT:    vnsrl.wi v11, v9, 0
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    vnsrl.wx v9, v9, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vslideup.vi v11, v10, 2
; CHECK-NEXT:    vslideup.vi v9, v8, 2
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v10, v11, v11
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vfmin.vv v8, v11, v9
; CHECK-NEXT:    vmerge.vxm v8, v8, a1, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vpmin2.i = tail call <4 x float> @llvm.aarch64.neon.fminp.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vpmin2.i, ptr %out, align 4
  ret void
}

define void @vpminq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vpminq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    lui a0, %hi(.LCPI9_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI9_0)(a0)
; CHECK-NEXT:    vmv.v.v v10, v8
; CHECK-NEXT:    vslideup.vi v10, v9, 1
; CHECK-NEXT:    vslidedown.vi v9, v8, 1, v0.t
; CHECK-NEXT:    vmfne.vv v8, v9, v9
; CHECK-NEXT:    vmfne.vv v11, v10, v10
; CHECK-NEXT:    vmor.mm v0, v11, v8
; CHECK-NEXT:    vfmin.vv v8, v10, v9
; CHECK-NEXT:    vfmerge.vfm v8, v8, fa5, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vpmin2.i = tail call <2 x double> @llvm.aarch64.neon.fminp.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vpmin2.i, ptr %out, align 8
  ret void
}

declare <2 x double> @llvm.aarch64.neon.fmaxp.v2f64(<2 x double>, <2 x double>)
declare <2 x double> @llvm.aarch64.neon.fminp.v2f64(<2 x double>, <2 x double>)
declare <2 x float> @llvm.aarch64.neon.fmaxp.v2f32(<2 x float>, <2 x float>)
declare <2 x float> @llvm.aarch64.neon.fminp.v2f32(<2 x float>, <2 x float>)
declare <4 x float> @llvm.aarch64.neon.fmaxp.v4f32(<4 x float>, <4 x float>)
declare <4 x float> @llvm.aarch64.neon.fminp.v4f32(<4 x float>, <4 x float>)
declare <4 x half> @llvm.aarch64.neon.fmaxp.v4f16(<4 x half>, <4 x half>)
declare <4 x half> @llvm.aarch64.neon.fminp.v4f16(<4 x half>, <4 x half>)
declare <8 x half> @llvm.aarch64.neon.fmaxp.v8f16(<8 x half>, <8 x half>)
declare <8 x half> @llvm.aarch64.neon.fminp.v8f16(<8 x half>, <8 x half>)
