; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqabs_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabs_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, 1048568
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vqabs_v1.i = tail call <4 x i16> @llvm.aarch64.neon.sqabs.v4i16(<4 x i16> %0)
  store <4 x i16> %vqabs_v1.i, ptr %out, align 2
  ret void
}

define void @vqabs_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabs_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    lui a0, 524288
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vqabs_v1.i = tail call <2 x i32> @llvm.aarch64.neon.sqabs.v2i32(<2 x i32> %0)
  store <2 x i32> %vqabs_v1.i, ptr %out, align 4
  ret void
}

define void @vqabs_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabs_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vqabs_v1.i = tail call <1 x i64> @llvm.aarch64.neon.sqabs.v1i64(<1 x i64> %0)
  store <1 x i64> %vqabs_v1.i, ptr %out, align 8
  ret void
}

define void @vqabs_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabs_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, -128
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vqabs_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqabs.v8i8(<8 x i8> %0)
  store <8 x i8> %vqabs_v.i, ptr %out, align 1
  ret void
}

define void @vqabsq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabsq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, 1048568
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vqabsq_v1.i = tail call <8 x i16> @llvm.aarch64.neon.sqabs.v8i16(<8 x i16> %0)
  store <8 x i16> %vqabsq_v1.i, ptr %out, align 2
  ret void
}

define void @vqabsq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabsq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    lui a0, 524288
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vqabsq_v1.i = tail call <4 x i32> @llvm.aarch64.neon.sqabs.v4i32(<4 x i32> %0)
  store <4 x i32> %vqabsq_v1.i, ptr %out, align 4
  ret void
}

define void @vqabsq_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabsq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vqabsq_v1.i = tail call <2 x i64> @llvm.aarch64.neon.sqabs.v2i64(<2 x i64> %0)
  store <2 x i64> %vqabsq_v1.i, ptr %out, align 8
  ret void
}

define void @vqabsq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqabsq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, -128
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vsmul.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vqabsq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqabs.v16i8(<16 x i8> %0)
  store <16 x i8> %vqabsq_v.i, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.sqabs.v1i64(<1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sqabs.v16i8(<16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.sqabs.v2i32(<2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqabs.v2i64(<2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.sqabs.v4i16(<4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqabs.v4i32(<4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.sqabs.v8i16(<8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.sqabs.v8i8(<8 x i8>)
