; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqdmulh_n_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulh_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vwmul.vx v9, v8, a1
; CHECK-NEXT:    vnclip.wi v8, v9, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vqdmulh_v2.i.i = tail call <4 x i16> @llvm.aarch64.neon.sqdmulh.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vqdmulh_v2.i.i, ptr %out, align 2
  ret void
}

define void @vqdmulh_n_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulh_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vwmul.vx v9, v8, a1
; CHECK-NEXT:    vnclip.wi v8, v9, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vqdmulh_v2.i.i = tail call <2 x i32> @llvm.aarch64.neon.sqdmulh.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vqdmulh_v2.i.i, ptr %out, align 4
  ret void
}

define void @vqdmulh_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulh_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v10, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vqdmulh_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqdmulh.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vqdmulh_v2.i, ptr %out, align 2
  ret void
}

define void @vqdmulh_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulh_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v10, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vqdmulh_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqdmulh.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vqdmulh_v2.i, ptr %out, align 4
  ret void
}

define void @vqdmulhq_n_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulhq_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vwmul.vx v8, v9, a1
; CHECK-NEXT:    vnclip.wi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vqdmulhq_v2.i.i = tail call <8 x i16> @llvm.aarch64.neon.sqdmulh.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vqdmulhq_v2.i.i, ptr %out, align 2
  ret void
}

define void @vqdmulhq_n_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulhq_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vwmul.vx v8, v9, a1
; CHECK-NEXT:    vnclip.wi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vqdmulhq_v2.i.i = tail call <4 x i32> @llvm.aarch64.neon.sqdmulh.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vqdmulhq_v2.i.i, ptr %out, align 4
  ret void
}

define void @vqdmulhq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulhq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    vwmul.vv v8, v9, v10
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vqdmulhq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqdmulh.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vqdmulhq_v2.i, ptr %out, align 2
  ret void
}

define void @vqdmulhq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqdmulhq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vwmul.vv v8, v9, v10
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vqdmulhq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqdmulh.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vqdmulhq_v2.i, ptr %out, align 4
  ret void
}

define void @vqrdmulh_n_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulh_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vwmul.vx v9, v8, a1
; CHECK-NEXT:    vnclip.wi v8, v9, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vqrdmulh_v2.i.i = tail call <4 x i16> @llvm.aarch64.neon.sqrdmulh.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vqrdmulh_v2.i.i, ptr %out, align 2
  ret void
}

define void @vqrdmulh_n_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulh_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vwmul.vx v9, v8, a1
; CHECK-NEXT:    vnclip.wi v8, v9, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vqrdmulh_v2.i.i = tail call <2 x i32> @llvm.aarch64.neon.sqrdmulh.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vqrdmulh_v2.i.i, ptr %out, align 4
  ret void
}

define void @vqrdmulh_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulh_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vnclip.wi v8, v10, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vqrdmulh_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqrdmulh.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vqrdmulh_v2.i, ptr %out, align 2
  ret void
}

define void @vqrdmulh_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulh_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    vwmul.vv v10, v8, v9
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vnclip.wi v8, v10, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vqrdmulh_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqrdmulh.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vqrdmulh_v2.i, ptr %out, align 4
  ret void
}

define void @vqrdmulhq_n_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulhq_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vwmul.vx v8, v9, a1
; CHECK-NEXT:    vnclip.wi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vqrdmulhq_v2.i.i = tail call <8 x i16> @llvm.aarch64.neon.sqrdmulh.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vqrdmulhq_v2.i.i, ptr %out, align 2
  ret void
}

define void @vqrdmulhq_n_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulhq_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vwmul.vx v8, v9, a1
; CHECK-NEXT:    vnclip.wi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vqrdmulhq_v2.i.i = tail call <4 x i32> @llvm.aarch64.neon.sqrdmulh.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vqrdmulhq_v2.i.i, ptr %out, align 4
  ret void
}

define void @vqrdmulhq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulhq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v10, (a1)
; CHECK-NEXT:    vwmul.vv v8, v9, v10
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vnclip.wi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vqrdmulhq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqrdmulh.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vqrdmulhq_v2.i, ptr %out, align 2
  ret void
}

define void @vqrdmulhq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrdmulhq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v10, (a1)
; CHECK-NEXT:    vwmul.vv v8, v9, v10
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vnclip.wi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vqrdmulhq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqrdmulh.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vqrdmulhq_v2.i, ptr %out, align 4
  ret void
}

declare <2 x i32> @llvm.aarch64.neon.sqdmulh.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.aarch64.neon.sqrdmulh.v2i32(<2 x i32>, <2 x i32>)
declare <4 x i16> @llvm.aarch64.neon.sqdmulh.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.aarch64.neon.sqrdmulh.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqdmulh.v4i32(<4 x i32>, <4 x i32>)
declare <4 x i32> @llvm.aarch64.neon.sqrdmulh.v4i32(<4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.sqdmulh.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.sqrdmulh.v8i16(<8 x i16>, <8 x i16>)
