; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqrshl_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v10, v9, a1
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    vssra.vv v11, v8, v10
; CHECK-NEXT:    vmsgtu.vi v0, v10, 15
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsext.vf2 v10, v8
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v8, v11, 0, v0
; CHECK-NEXT:    vminu.vx v11, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v11
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsll.vv v9, v10, v12
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v9, 0
; CHECK-NEXT:    vmerge.vvm v8, v9, v8, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vqrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqrshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vqrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshl_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 31
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmsgtu.vx v0, v10, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vssra.vv v10, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsext.vf2 v11, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v9, v10, 0, v0
; CHECK-NEXT:    vminu.vx v10, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vv v8, v11, v12
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v9, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vqrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqrshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vqrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshl_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a1, a0, 1
; CHECK-NEXT:    vmv.s.x v10, a1
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v9, v9, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmerge.vxm v10, v10, a0, v0
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vminu.vx v11, v9, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmsne.vi v12, v8, 0
; CHECK-NEXT:    vrsub.vx v13, v9, a1
; CHECK-NEXT:    vminu.vx v14, v11, a0
; CHECK-NEXT:    vmsgtu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v11, v12, v11
; CHECK-NEXT:    vsll.vv v12, v8, v14
; CHECK-NEXT:    vsra.vv v14, v12, v14
; CHECK-NEXT:    vmsne.vv v14, v8, v14
; CHECK-NEXT:    vmor.mm v0, v14, v11
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmerge.vvm v10, v12, v10, v0
; CHECK-NEXT:    vmsgtu.vx v0, v13, a0
; CHECK-NEXT:    vssra.vv v8, v8, v13
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v9, a1
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vqrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sqrshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vqrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshl_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vrsub.vi v11, v10, 0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsext.vf2 v12, v9
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vssra.vv v9, v9, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 7
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v12, v11
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v10, v10, 0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vqrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqrshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vqrshl_v.i, ptr %out, align 1
  ret void
}

define void @vqrshl_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmseq.vx v0, v10, a0
; CHECK-NEXT:    vssrl.vv v11, v9, v10
; CHECK-NEXT:    vsrl.vi v11, v9, 15, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v9
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vminu.vx v9, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v13, v9
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v10, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsll.vv v9, v12, v13
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v10, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v10, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vqrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.uqrshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vqrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshl_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmseq.vx v0, v10, a0
; CHECK-NEXT:    vssrl.vv v11, v9, v10
; CHECK-NEXT:    vsrl.vi v11, v9, 31, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vminu.vx v9, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v13, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v10, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vv v9, v12, v13
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v10, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v10, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vqrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.uqrshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vqrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshl_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v8, v8, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmsne.vi v11, v9, 0
; CHECK-NEXT:    vminu.vx v12, v8, a1
; CHECK-NEXT:    vmseq.vx v0, v10, a1
; CHECK-NEXT:    vssrl.vv v13, v9, v10
; CHECK-NEXT:    vsrl.vx v13, v9, a0, v0.t
; CHECK-NEXT:    vmsgtu.vx v14, v12, a0
; CHECK-NEXT:    vmand.mm v11, v11, v14
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vminu.vx v10, v12, a0
; CHECK-NEXT:    vmerge.vim v12, v13, 0, v0
; CHECK-NEXT:    vsll.vv v13, v9, v10
; CHECK-NEXT:    vsrl.vv v10, v13, v10
; CHECK-NEXT:    vmsne.vv v9, v9, v10
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v13, -1, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v9, v12, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vqrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.uqrshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vqrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshl_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vrsub.vi v11, v10, 0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmseq.vi v0, v11, 8
; CHECK-NEXT:    vssrl.vv v12, v9, v11
; CHECK-NEXT:    vsrl.vi v12, v9, 7, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v13, v9
; CHECK-NEXT:    vzext.vf2 v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v11, 8
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsll.vv v9, v13, v9
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v10, v12, 0, v0
; CHECK-NEXT:    vnclipu.wi v9, v9, 0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vqrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.uqrshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vqrshl_v.i, ptr %out, align 1
  ret void
}

define void @vqrshlq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vand.vx v12, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v12, a1
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vsext.vf2 v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vssra.vv v10, v10, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 15
; CHECK-NEXT:    vminu.vx v11, v12, a1
; CHECK-NEXT:    vmerge.vim v13, v10, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v12, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vsll.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v13, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vqrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqrshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vqrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshlq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v12, v8, a0
; CHECK-NEXT:    li a0, 31
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v11, v12, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmsgtu.vx v0, v11, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vsext.vf2 v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vssra.vv v10, v10, v11
; CHECK-NEXT:    vminu.vx v11, v12, a0
; CHECK-NEXT:    vmerge.vim v13, v10, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v12, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vsll.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v13, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vqrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqrshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vqrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshlq_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a1, a0, 1
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v9, v9, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmerge.vxm v10, v10, a0, v0
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vminu.vx v11, v9, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmsne.vi v12, v8, 0
; CHECK-NEXT:    vrsub.vx v13, v9, a1
; CHECK-NEXT:    vminu.vx v14, v11, a0
; CHECK-NEXT:    vmsgtu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v11, v12, v11
; CHECK-NEXT:    vsll.vv v12, v8, v14
; CHECK-NEXT:    vsra.vv v14, v12, v14
; CHECK-NEXT:    vmsne.vv v14, v8, v14
; CHECK-NEXT:    vmor.mm v0, v14, v11
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmerge.vvm v10, v12, v10, v0
; CHECK-NEXT:    vmsgtu.vx v0, v13, a0
; CHECK-NEXT:    vssra.vv v8, v8, v13
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v9, a1
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vqrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sqrshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vqrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshlq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vrsub.vi v11, v10, 0
; CHECK-NEXT:    vminu.vx v13, v10, a1
; CHECK-NEXT:    vssra.vv v12, v9, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 7
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vsext.vf2 v10, v9
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v13
; CHECK-NEXT:    vsll.vv v10, v10, v12
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v10, v10, 0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vqrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqrshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vqrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vqrshlq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v12, v8, a0
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, mu
; CHECK-NEXT:    vrsub.vx v13, v12, a1
; CHECK-NEXT:    vmseq.vx v0, v13, a0
; CHECK-NEXT:    vssrl.vv v14, v10, v13
; CHECK-NEXT:    vsrl.vi v14, v10, 15, v0.t
; CHECK-NEXT:    vminu.vx v11, v12, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsll.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v13, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v10, v14, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v12, a0
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v10, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vqrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.uqrshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vqrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshlq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v12, v8, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, mu
; CHECK-NEXT:    vrsub.vx v13, v12, a1
; CHECK-NEXT:    vmseq.vx v0, v13, a0
; CHECK-NEXT:    vssrl.vv v14, v10, v13
; CHECK-NEXT:    vsrl.vi v14, v10, 31, v0.t
; CHECK-NEXT:    vminu.vx v11, v12, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsll.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v13, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v10, v14, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v12, a0
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v10, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vqrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.uqrshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vqrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshlq_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v8, v8, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmsne.vi v11, v9, 0
; CHECK-NEXT:    vminu.vx v12, v8, a1
; CHECK-NEXT:    vmseq.vx v0, v10, a1
; CHECK-NEXT:    vssrl.vv v13, v9, v10
; CHECK-NEXT:    vsrl.vx v13, v9, a0, v0.t
; CHECK-NEXT:    vmsgtu.vx v14, v12, a0
; CHECK-NEXT:    vmand.mm v11, v11, v14
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vminu.vx v10, v12, a0
; CHECK-NEXT:    vmerge.vim v12, v13, 0, v0
; CHECK-NEXT:    vsll.vv v13, v9, v10
; CHECK-NEXT:    vsrl.vv v10, v13, v10
; CHECK-NEXT:    vmsne.vv v9, v9, v10
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v13, -1, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v9, v12, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vqrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.uqrshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vqrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshlq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    vrsub.vi v13, v12, 0
; CHECK-NEXT:    vminu.vx v11, v12, a0
; CHECK-NEXT:    vmseq.vi v0, v13, 8
; CHECK-NEXT:    vssrl.vv v14, v9, v13
; CHECK-NEXT:    vsrl.vi v14, v9, 7, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsll.vv v10, v8, v10
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v13, 8
; CHECK-NEXT:    vmsgtu.vx v8, v12, a0
; CHECK-NEXT:    vmerge.vim v9, v14, 0, v0
; CHECK-NEXT:    vnclipu.wi v10, v10, 0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vqrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.uqrshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vqrshlq_v.i, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.sqrshl.v1i64(<1 x i64>, <1 x i64>)
declare <1 x i64> @llvm.aarch64.neon.uqrshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sqrshl.v16i8(<16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.uqrshl.v16i8(<16 x i8>, <16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.sqrshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.aarch64.neon.uqrshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqrshl.v2i64(<2 x i64>, <2 x i64>)
declare <2 x i64> @llvm.aarch64.neon.uqrshl.v2i64(<2 x i64>, <2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.sqrshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.aarch64.neon.uqrshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqrshl.v4i32(<4 x i32>, <4 x i32>)
declare <4 x i32> @llvm.aarch64.neon.uqrshl.v4i32(<4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.sqrshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.uqrshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.sqrshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.uqrshl.v8i8(<8 x i8>, <8 x i8>)
