; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqrshlq_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vsext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 8
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vqrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqrshl.v16i8(<16 x i8> %0, <16 x i8> <i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126>)
  store <16 x i8> %vqrshlq_v.i, ptr %des, align 1
  ret void
}

define void @vqrshl_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vqrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqrshl.v8i8(<8 x i8> %0, <8 x i8> <i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128>)
  store <8 x i8> %vqrshl_v.i, ptr %des, align 1
  ret void
}

define void @vqrshlq_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vwadd.vv v8, v9, v9
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vqrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqrshl.v8i16(<8 x i16> %0, <8 x i16> <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>)
  store <8 x i16> %vqrshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vqrshl_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vwadd.vv v9, v8, v8
; CHECK-NEXT:    vnclip.wi v8, v9, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vqrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqrshl.v4i16(<4 x i16> %0, <4 x i16> <i16 1, i16 1, i16 1, i16 1>)
  store <4 x i16> %vqrshl_v2.i, ptr %des, align 2
  ret void
}

define void @vqrshlq_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vsext.vf2 v8, v9
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vqrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqrshl.v4i32(<4 x i32> %0, <4 x i32> <i32 127, i32 127, i32 127, i32 127>)
  store <4 x i32> %vqrshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vqrshl_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsll.vx v8, v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vqrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqrshl.v2i32(<2 x i32> %0, <2 x i32> <i32 33, i32 33>)
  store <2 x i32> %vqrshl_v2.i, ptr %des, align 4
  ret void
}

define void @vqrshlq_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vqrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sqrshl.v2i64(<2 x i64> %0, <2 x i64> zeroinitializer)
  store <2 x i64> %vqrshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vqrshl_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a2, a0, 1
; CHECK-NEXT:    vmv.s.x v9, a2
; CHECK-NEXT:    li a2, 63
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    vsll.vx v10, v8, a2
; CHECK-NEXT:    vmerge.vxm v9, v9, a0, v0
; CHECK-NEXT:    vsra.vx v11, v10, a2
; CHECK-NEXT:    vmsne.vv v0, v8, v11
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vqrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sqrshl.v1i64(<1 x i64> %0, <1 x i64> <i64 63>)
  store <1 x i64> %vqrshl_v2.i, ptr %des, align 8
  ret void
}

define void @vqrshlq_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 8
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vqrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.uqrshl.v16i8(<16 x i8> %0, <16 x i8> <i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8>)
  store <16 x i8> %vqrshlq_v.i, ptr %des, align 1
  ret void
}

define void @vqrshl_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vqrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.uqrshl.v8i8(<8 x i8> %0, <8 x i8> zeroinitializer)
  store <8 x i8> %vqrshl_v.i, ptr %des, align 1
  ret void
}

define void @vqrshlq_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vsll.vi v8, v8, 16
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vqrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.uqrshl.v8i16(<8 x i16> %0, <8 x i16> <i16 126, i16 126, i16 126, i16 126, i16 126, i16 126, i16 126, i16 126>)
  store <8 x i16> %vqrshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vqrshl_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vi v8, v9, 16
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vqrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.uqrshl.v4i16(<4 x i16> %0, <4 x i16> <i16 16, i16 16, i16 16, i16 16>)
  store <4 x i16> %vqrshl_v2.i, ptr %des, align 2
  ret void
}

define void @vqrshlq_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vqrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.uqrshl.v4i32(<4 x i32> %0, <4 x i32> <i32 126, i32 126, i32 126, i32 126>)
  store <4 x i32> %vqrshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vqrshl_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsll.vx v8, v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vqrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.uqrshl.v2i32(<2 x i32> %0, <2 x i32> <i32 33, i32 33>)
  store <2 x i32> %vqrshl_v2.i, ptr %des, align 4
  ret void
}

define void @vqrshlq_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    vsrl.vx v10, v9, a0
; CHECK-NEXT:    vmsne.vv v10, v8, v10
; CHECK-NEXT:    vmsne.vi v8, v8, 0
; CHECK-NEXT:    vmor.mm v0, v10, v8
; CHECK-NEXT:    vmerge.vim v8, v9, -1, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vqrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.uqrshl.v2i64(<2 x i64> %0, <2 x i64> <i64 65, i64 65>)
  store <2 x i64> %vqrshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vqrshl_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqrshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vi v8, v8, 1
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vqrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.uqrshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -1>)
  store <1 x i64> %vqrshl_v2.i, ptr %des, align 8
  ret void
}

declare <16 x i8> @llvm.aarch64.neon.sqrshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.sqrshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sqrshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.sqrshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqrshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.sqrshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqrshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.sqrshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.uqrshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.uqrshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.uqrshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.uqrshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.uqrshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.uqrshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.uqrshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.uqrshl.v1i64(<1 x i64>, <1 x i64>)
