; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqshrn_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshrn_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v8, 6
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vqshrn_n2 = tail call <8 x i8> @llvm.aarch64.neon.sqshrn.v8i8(<8 x i16> %0, i32 6)
  store <8 x i8> %vqshrn_n2, ptr %out, align 1
  ret void
}

define void @vqshrn_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshrn_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v8, 8
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vqshrn_n2 = tail call <4 x i16> @llvm.aarch64.neon.sqshrn.v4i16(<4 x i32> %0, i32 8)
  store <4 x i16> %vqshrn_n2, ptr %out, align 2
  ret void
}

define void @vqshrn_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshrn_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclip.wi v8, v8, 4
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vqshrn_n2 = tail call <2 x i32> @llvm.aarch64.neon.sqshrn.v2i32(<2 x i64> %0, i32 4)
  store <2 x i32> %vqshrn_n2, ptr %out, align 4
  ret void
}

define void @vqshrn_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshrn_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclipu.wi v8, v8, 2
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vqshrn_n2 = tail call <8 x i8> @llvm.aarch64.neon.uqshrn.v8i8(<8 x i16> %0, i32 2)
  store <8 x i8> %vqshrn_n2, ptr %out, align 1
  ret void
}

define void @vqshrn_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshrn_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclipu.wi v8, v8, 13
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vqshrn_n2 = tail call <4 x i16> @llvm.aarch64.neon.uqshrn.v4i16(<4 x i32> %0, i32 13)
  store <4 x i16> %vqshrn_n2, ptr %out, align 2
  ret void
}

define void @vqshrn_n_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshrn_n_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 2
; CHECK-NEXT:    vnclipu.wi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vqshrn_n2 = tail call <2 x i32> @llvm.aarch64.neon.uqshrn.v2i32(<2 x i64> %0, i32 31)
  store <2 x i32> %vqshrn_n2, ptr %out, align 4
  ret void
}

declare <2 x i32> @llvm.aarch64.neon.sqshrn.v2i32(<2 x i64>, i32)
declare <2 x i32> @llvm.aarch64.neon.uqshrn.v2i32(<2 x i64>, i32)
declare <4 x i16> @llvm.aarch64.neon.sqshrn.v4i16(<4 x i32>, i32)
declare <4 x i16> @llvm.aarch64.neon.uqshrn.v4i16(<4 x i32>, i32)
declare <8 x i8> @llvm.aarch64.neon.sqshrn.v8i8(<8 x i16>, i32)
declare <8 x i8> @llvm.aarch64.neon.uqshrn.v8i8(<8 x i16>, i32)
