; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqshlq_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsra.vi v8, v8, 7
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vqshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8> %0, <16 x i8> <i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7>)
  store <16 x i8> %vqshlq_v.i, ptr %des, align 1
  ret void
}

define void @vqshl_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vi v8, v9, 8
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vqshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8> %0, <8 x i8> <i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8, i8 8>)
  store <8 x i8> %vqshl_v.i, ptr %des, align 1
  ret void
}

define void @vqshlq_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsra.vi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vqshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16> %0, <8 x i16> <i16 -128, i16 -128, i16 -128, i16 -128, i16 -128, i16 -128, i16 -128, i16 -128>)
  store <8 x i16> %vqshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vqshl_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vi v8, v9, 16
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vqshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16> %0, <4 x i16> <i16 126, i16 126, i16 126, i16 126>)
  store <4 x i16> %vqshl_v2.i, ptr %des, align 2
  ret void
}

define void @vqshlq_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsra.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vqshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32> %0, <4 x i32> <i32 -127, i32 -127, i32 -127, i32 -127>)
  store <4 x i32> %vqshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vqshl_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsra.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vqshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32> %0, <2 x i32> <i32 -33, i32 -33>)
  store <2 x i32> %vqshl_v2.i, ptr %des, align 4
  ret void
}

define void @vqshlq_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vqshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64> %0, <2 x i64> <i64 -65, i64 -65>)
  store <2 x i64> %vqshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vqshl_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vqshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -128>)
  store <1 x i64> %vqshl_v2.i, ptr %des, align 8
  ret void
}

define void @vqshlq_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vqshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8> %0, <16 x i8> <i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8>)
  store <16 x i8> %vqshlq_v.i, ptr %des, align 1
  ret void
}

define void @vqshl_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 7
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vqshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8> %0, <8 x i8> <i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7>)
  store <8 x i8> %vqshl_v.i, ptr %des, align 1
  ret void
}

define void @vqshlq_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vwmulu.vx v8, v9, a0
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vqshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16> %0, <8 x i16> <i16 15, i16 15, i16 15, i16 15, i16 15, i16 15, i16 15, i16 15>)
  store <8 x i16> %vqshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vqshl_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vwaddu.vv v9, v8, v8
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vqshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16> %0, <4 x i16> <i16 1, i16 1, i16 1, i16 1>)
  store <4 x i16> %vqshl_v2.i, ptr %des, align 2
  ret void
}

define void @vqshlq_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vqshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32> %0, <4 x i32> <i32 127, i32 127, i32 127, i32 127>)
  store <4 x i32> %vqshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vqshl_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vqshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32> %0, <2 x i32> <i32 -32, i32 -32>)
  store <2 x i32> %vqshl_v2.i, ptr %des, align 4
  ret void
}

define void @vqshlq_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vqshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64> %0, <2 x i64> <i64 -1, i64 -1>)
  store <2 x i64> %vqshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vqshl_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vqshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vqshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -63>)
  store <1 x i64> %vqshl_v2.i, ptr %des, align 8
  ret void
}

declare <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64>, <1 x i64>)
