; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqshl_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vqshl_n2 = tail call <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16> %0, <4 x i16> zeroinitializer)
  store <4 x i16> %vqshl_n2, ptr %out, align 2
  ret void
}

define void @vqshl_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vwadd.vv v9, v8, v8
; CHECK-NEXT:    vnclip.wi v8, v9, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vqshl_n2 = tail call <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32> %0, <2 x i32> <i32 1, i32 1>)
  store <2 x i32> %vqshl_n2, ptr %out, align 4
  ret void
}

define void @vqshl_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a2, a0, 1
; CHECK-NEXT:    vmv.s.x v9, a2
; CHECK-NEXT:    li a2, 63
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    vsll.vx v10, v8, a2
; CHECK-NEXT:    vmerge.vxm v9, v9, a0, v0
; CHECK-NEXT:    vsra.vx v11, v10, a2
; CHECK-NEXT:    vmsne.vv v0, v8, v11
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vqshl_n2 = tail call <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64> %0, <1 x i64> <i64 63>)
  store <1 x i64> %vqshl_n2, ptr %out, align 8
  ret void
}

define void @vqshl_n_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vwadd.vv v9, v8, v8
; CHECK-NEXT:    vnclip.wi v8, v9, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vqshl_n = tail call <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8> %0, <8 x i8> <i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1>)
  store <8 x i8> %vqshl_n, ptr %out, align 1
  ret void
}

define void @vqshl_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vqshl_n2 = tail call <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16> %0, <4 x i16> <i16 15, i16 15, i16 15, i16 15>)
  store <4 x i16> %vqshl_n2, ptr %out, align 2
  ret void
}

define void @vqshl_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vqshl_n2 = tail call <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32> %0, <2 x i32> zeroinitializer)
  store <2 x i32> %vqshl_n2, ptr %out, align 4
  ret void
}

define void @vqshl_n_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vqshl_n2 = tail call <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64> %0, <1 x i64> zeroinitializer)
  store <1 x i64> %vqshl_n2, ptr %out, align 8
  ret void
}

define void @vqshl_n_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_n_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vqshl_n = tail call <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8> %0, <8 x i8> <i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7>)
  store <8 x i8> %vqshl_n, ptr %out, align 1
  ret void
}

define void @vqshl_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    vrsub.vx v10, v8, a0
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    vminu.vx v8, v8, a0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vsext.vf2 v8, v9
; CHECK-NEXT:    vsll.vv v8, v8, v11
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, mu
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vsra.vv v8, v9, v10, v0.t
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vqshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vqshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqshl_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vrsub.vx v10, v8, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vminu.vx v8, v8, a0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vsext.vf2 v8, v9
; CHECK-NEXT:    vsll.vv v8, v8, v11
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, mu
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vsra.vv v8, v9, v10, v0.t
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vqshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vqshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqshl_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a1, a0, 1
; CHECK-NEXT:    vmv.s.x v10, a1
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v9, v9, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmerge.vxm v10, v10, a0, v0
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vminu.vx v11, v9, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vmsne.vi v12, v8, 0
; CHECK-NEXT:    vrsub.vx v13, v9, a1
; CHECK-NEXT:    vminu.vx v14, v11, a0
; CHECK-NEXT:    vmsgtu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v11, v12, v11
; CHECK-NEXT:    vsll.vv v12, v8, v14
; CHECK-NEXT:    vsra.vv v14, v12, v14
; CHECK-NEXT:    vmsne.vv v14, v8, v14
; CHECK-NEXT:    vmor.mm v0, v14, v11
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmerge.vvm v10, v12, v10, v0
; CHECK-NEXT:    vmsgtu.vx v0, v9, a1
; CHECK-NEXT:    vminu.vx v9, v13, a0
; CHECK-NEXT:    vsra.vv v10, v8, v9, v0.t
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vqshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vqshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqshl_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    vrsub.vi v10, v8, 0
; CHECK-NEXT:    vminu.vx v8, v8, a0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v8
; CHECK-NEXT:    vsext.vf2 v8, v9
; CHECK-NEXT:    vsll.vv v8, v8, v11
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, mu
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vsra.vv v8, v9, v10, v0.t
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vqshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vqshl_v.i, ptr %out, align 1
  ret void
}

define void @vqshl_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    vsrl.vv v11, v9, v10
; CHECK-NEXT:    vmsgtu.vi v0, v10, 15
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v9, v11, 0, v0
; CHECK-NEXT:    vminu.vx v11, v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v11
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsll.vv v8, v10, v12
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v9, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vqshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vqshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqshl_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 31
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmsgtu.vx v0, v10, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsrl.vv v10, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v9, v10, 0, v0
; CHECK-NEXT:    vminu.vx v10, v8, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vv v8, v11, v12
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v9, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vqshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vqshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqshl_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmsne.vi v11, v9, 0
; CHECK-NEXT:    vminu.vx v12, v8, a1
; CHECK-NEXT:    vmsgtu.vx v0, v10, a0
; CHECK-NEXT:    vsrl.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v13, v12, a0
; CHECK-NEXT:    vmsgtu.vx v12, v12, a0
; CHECK-NEXT:    vmand.mm v11, v11, v12
; CHECK-NEXT:    vsll.vv v12, v9, v13
; CHECK-NEXT:    vsrl.vv v13, v12, v13
; CHECK-NEXT:    vmsne.vv v9, v9, v13
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v12, -1, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vqshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vqshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqshl_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    vmsgtu.vx v8, v9, a0
; CHECK-NEXT:    vrsub.vi v11, v9, 0
; CHECK-NEXT:    vminu.vx v9, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vsrl.vv v10, v10, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 7
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v11, v9
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmerge.vim v9, v10, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v12, v11
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v10, v10, 0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vqshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vqshl_v.i, ptr %out, align 1
  ret void
}

define void @vqshlq_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vwadd.vv v8, v9, v9
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vqshl_n2 = tail call <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16> %0, <8 x i16> <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>)
  store <8 x i16> %vqshl_n2, ptr %out, align 2
  ret void
}

define void @vqshlq_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vqshl_n2 = tail call <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32> %0, <4 x i32> zeroinitializer)
  store <4 x i32> %vqshl_n2, ptr %out, align 4
  ret void
}

define void @vqshlq_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a2, a0, 1
; CHECK-NEXT:    vmv.v.x v9, a2
; CHECK-NEXT:    li a2, 63
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    vsll.vx v10, v8, a2
; CHECK-NEXT:    vmerge.vxm v9, v9, a0, v0
; CHECK-NEXT:    vsra.vx v11, v10, a2
; CHECK-NEXT:    vmsne.vv v0, v8, v11
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vqshl_n2 = tail call <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64> %0, <2 x i64> <i64 63, i64 63>)
  store <2 x i64> %vqshl_n2, ptr %out, align 8
  ret void
}

define void @vqshlq_n_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vwmulsu.vx v8, v9, a0
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vqshl_n = tail call <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8> %0, <16 x i8> <i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7>)
  store <16 x i8> %vqshl_n, ptr %out, align 1
  ret void
}

define void @vqshlq_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vwmulu.vx v8, v9, a0
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vqshl_n2 = tail call <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16> %0, <8 x i16> <i16 15, i16 15, i16 15, i16 15, i16 15, i16 15, i16 15, i16 15>)
  store <8 x i16> %vqshl_n2, ptr %out, align 2
  ret void
}

define void @vqshlq_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vwaddu.vv v8, v9, v9
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vqshl_n2 = tail call <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32> %0, <4 x i32> <i32 1, i32 1, i32 1, i32 1>)
  store <4 x i32> %vqshl_n2, ptr %out, align 4
  ret void
}

define void @vqshlq_n_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vadd.vv v9, v8, v8
; CHECK-NEXT:    vsrl.vi v10, v9, 1
; CHECK-NEXT:    vmsne.vv v0, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v9, -1, v0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vqshl_n2 = tail call <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64> %0, <2 x i64> <i64 1, i64 1>)
  store <2 x i64> %vqshl_n2, ptr %out, align 8
  ret void
}

define void @vqshlq_n_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_n_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vqshl_n = tail call <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8> %0, <16 x i8> zeroinitializer)
  store <16 x i8> %vqshl_n, ptr %out, align 1
  ret void
}

define void @vqshlq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v12, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    vrsub.vx v9, v8, a0
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    vminu.vx v10, v8, a0
; CHECK-NEXT:    vminu.vx v13, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsext.vf2 v10, v12
; CHECK-NEXT:    vsll.vv v8, v10, v8
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, mu
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vsra.vv v8, v12, v13, v0.t
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vqshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vqshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqshlq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v12, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vrsub.vx v9, v8, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vminu.vx v10, v8, a0
; CHECK-NEXT:    vminu.vx v13, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsext.vf2 v10, v12
; CHECK-NEXT:    vsll.vv v8, v10, v8
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, mu
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vsra.vv v8, v12, v13, v0.t
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vqshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vqshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqshlq_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a1, a0, 1
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v9, v9, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    slli a0, a0, 63
; CHECK-NEXT:    vmerge.vxm v10, v10, a0, v0
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vminu.vx v11, v9, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vmsne.vi v12, v8, 0
; CHECK-NEXT:    vrsub.vx v13, v9, a1
; CHECK-NEXT:    vminu.vx v14, v11, a0
; CHECK-NEXT:    vmsgtu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v11, v12, v11
; CHECK-NEXT:    vsll.vv v12, v8, v14
; CHECK-NEXT:    vsra.vv v14, v12, v14
; CHECK-NEXT:    vmsne.vv v14, v8, v14
; CHECK-NEXT:    vmor.mm v0, v14, v11
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmerge.vvm v10, v12, v10, v0
; CHECK-NEXT:    vmsgtu.vx v0, v9, a1
; CHECK-NEXT:    vminu.vx v9, v13, a0
; CHECK-NEXT:    vsra.vv v10, v8, v9, v0.t
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vqshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vqshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqshlq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vle8.v v12, (a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    vrsub.vi v9, v8, 0
; CHECK-NEXT:    vminu.vx v10, v8, a0
; CHECK-NEXT:    vminu.vx v13, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsext.vf2 v10, v12
; CHECK-NEXT:    vsll.vv v8, v10, v8
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, mu
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vsra.vv v8, v12, v13, v0.t
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vqshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vqshlq_v.i, ptr %out, align 1
  ret void
}

define void @vqshlq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v12, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v12, a1
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vsrl.vv v10, v10, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 15
; CHECK-NEXT:    vminu.vx v11, v12, a1
; CHECK-NEXT:    vmerge.vim v13, v10, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v12, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vsll.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v13, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vqshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vqshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqshlq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v12, v8, a0
; CHECK-NEXT:    li a0, 31
; CHECK-NEXT:    vrsub.vx v11, v12, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmsgtu.vx v0, v11, a0
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsrl.vv v10, v10, v11
; CHECK-NEXT:    vminu.vx v11, v12, a0
; CHECK-NEXT:    vmerge.vim v13, v10, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v12, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vsll.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vmerge.vvm v8, v8, v13, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vqshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vqshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqshlq_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmsne.vi v11, v9, 0
; CHECK-NEXT:    vminu.vx v12, v8, a1
; CHECK-NEXT:    vmsgtu.vx v0, v10, a0
; CHECK-NEXT:    vsrl.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v13, v12, a0
; CHECK-NEXT:    vmsgtu.vx v12, v12, a0
; CHECK-NEXT:    vmand.mm v11, v11, v12
; CHECK-NEXT:    vsll.vv v12, v9, v13
; CHECK-NEXT:    vsrl.vv v13, v12, v13
; CHECK-NEXT:    vmsne.vv v9, v9, v13
; CHECK-NEXT:    vmor.mm v0, v9, v11
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v12, -1, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vqshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vqshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqshlq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v11, (a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    vmsgtu.vx v8, v9, a0
; CHECK-NEXT:    vrsub.vi v10, v9, 0
; CHECK-NEXT:    vminu.vx v9, v9, a1
; CHECK-NEXT:    vsrl.vv v12, v11, v10
; CHECK-NEXT:    vmsgtu.vi v0, v10, 7
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v11
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vmerge.vim v14, v12, 0, v0
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v12, v9
; CHECK-NEXT:    vsll.vv v10, v10, v12
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v9, v14, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vqshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vqshlq_v.i, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64>, <1 x i64>)
declare <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8>, <16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64>, <2 x i64>)
declare <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64>, <2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32>, <4 x i32>)
declare <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8>, <8 x i8>)
