; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqshlu_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlu_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmax.vx v8, v8, zero
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vqshlu_n2 = tail call <4 x i16> @llvm.aarch64.neon.sqshlu.v4i16(<4 x i16> %0, <4 x i16> <i16 15, i16 15, i16 15, i16 15>)
  store <4 x i16> %vqshlu_n2, ptr %out, align 2
  ret void
}

define void @vqshlu_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlu_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmax.vx v8, v8, zero
; CHECK-NEXT:    lui a0, 524288
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vqshlu_n2 = tail call <2 x i32> @llvm.aarch64.neon.sqshlu.v2i32(<2 x i32> %0, <2 x i32> <i32 31, i32 31>)
  store <2 x i32> %vqshlu_n2, ptr %out, align 4
  ret void
}

define void @vqshlu_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlu_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vmax.vx v8, v8, zero
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vqshlu_n2 = tail call <1 x i64> @llvm.aarch64.neon.sqshlu.v1i64(<1 x i64> %0, <1 x i64> zeroinitializer)
  store <1 x i64> %vqshlu_n2, ptr %out, align 8
  ret void
}

define void @vqshlu_n_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlu_n_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vmax.vx v8, v8, zero
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vqshlu_n = tail call <8 x i8> @llvm.aarch64.neon.sqshlu.v8i8(<8 x i8> %0, <8 x i8> zeroinitializer)
  store <8 x i8> %vqshlu_n, ptr %out, align 1
  ret void
}

define void @vqshluq_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshluq_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmax.vx v9, v8, zero
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vwmulu.vx v8, v9, a0
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vqshlu_n2 = tail call <8 x i16> @llvm.aarch64.neon.sqshlu.v8i16(<8 x i16> %0, <8 x i16> <i16 15, i16 15, i16 15, i16 15, i16 15, i16 15, i16 15, i16 15>)
  store <8 x i16> %vqshlu_n2, ptr %out, align 2
  ret void
}

define void @vqshluq_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshluq_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmax.vx v8, v8, zero
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vqshlu_n2 = tail call <4 x i32> @llvm.aarch64.neon.sqshlu.v4i32(<4 x i32> %0, <4 x i32> zeroinitializer)
  store <4 x i32> %vqshlu_n2, ptr %out, align 4
  ret void
}

define void @vqshluq_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshluq_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vmax.vx v8, v8, zero
; CHECK-NEXT:    vadd.vv v8, v8, v8
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vqshlu_n2 = tail call <2 x i64> @llvm.aarch64.neon.sqshlu.v2i64(<2 x i64> %0, <2 x i64> <i64 1, i64 1>)
  store <2 x i64> %vqshlu_n2, ptr %out, align 8
  ret void
}

define void @vqshluq_n_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshluq_n_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vmax.vx v9, v8, zero
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vwmulu.vx v8, v9, a0
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vqshlu_n = tail call <16 x i8> @llvm.aarch64.neon.sqshlu.v16i8(<16 x i8> %0, <16 x i8> <i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7, i8 7>)
  store <16 x i8> %vqshlu_n, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.sqshlu.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sqshlu.v16i8(<16 x i8>, <16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.sqshlu.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqshlu.v2i64(<2 x i64>, <2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.sqshlu.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqshlu.v4i32(<4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.sqshlu.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.sqshlu.v8i8(<8 x i8>, <8 x i8>)
