; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vrecpe_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrecpe_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %vrecpe_v1.i = tail call <4 x half> @llvm.aarch64.neon.frecpe.v4f16(<4 x half> %0)
  store <4 x half> %vrecpe_v1.i, ptr %out, align 2
  ret void
}

define void @vrecpe_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrecpe_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %vrecpe_v1.i = tail call <2 x float> @llvm.aarch64.neon.frecpe.v2f32(<2 x float> %0)
  store <2 x float> %vrecpe_v1.i, ptr %out, align 4
  ret void
}

define void @vrecpe_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrecpe_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %vrecpe_v1.i = tail call <1 x double> @llvm.aarch64.neon.frecpe.v1f64(<1 x double> %0)
  store <1 x double> %vrecpe_v1.i, ptr %out, align 8
  ret void
}

define void @vrecpeq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrecpeq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %vrecpeq_v1.i = tail call <8 x half> @llvm.aarch64.neon.frecpe.v8f16(<8 x half> %0)
  store <8 x half> %vrecpeq_v1.i, ptr %out, align 2
  ret void
}

define void @vrecpeq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrecpeq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %vrecpeq_v1.i = tail call <4 x float> @llvm.aarch64.neon.frecpe.v4f32(<4 x float> %0)
  store <4 x float> %vrecpeq_v1.i, ptr %out, align 4
  ret void
}

define void @vrecpeq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrecpeq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %vrecpeq_v1.i = tail call <2 x double> @llvm.aarch64.neon.frecpe.v2f64(<2 x double> %0)
  store <2 x double> %vrecpeq_v1.i, ptr %out, align 8
  ret void
}

declare <1 x double> @llvm.aarch64.neon.frecpe.v1f64(<1 x double>)
declare <2 x double> @llvm.aarch64.neon.frecpe.v2f64(<2 x double>)
declare <2 x float> @llvm.aarch64.neon.frecpe.v2f32(<2 x float>)
declare <4 x float> @llvm.aarch64.neon.frecpe.v4f32(<4 x float>)
declare <4 x half> @llvm.aarch64.neon.frecpe.v4f16(<4 x half>)
declare <8 x half> @llvm.aarch64.neon.frecpe.v8f16(<8 x half>)
