; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vrshlq_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vadd.vv v8, v8, v8
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8> %0, <16 x i8> <i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1>)
  store <16 x i8> %vrshlq_v.i, ptr %des, align 1
  ret void
}

define void @vrshl_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8> %0, <8 x i8> <i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126>)
  store <8 x i8> %vrshl_v.i, ptr %des, align 1
  ret void
}

define void @vrshlq_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16> %0, <8 x i16> <i16 -15, i16 -15, i16 -15, i16 -15, i16 -15, i16 -15, i16 -15, i16 -15>)
  store <8 x i16> %vrshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vrshl_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsll.vi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16> %0, <4 x i16> <i16 15, i16 15, i16 15, i16 15>)
  store <4 x i16> %vrshl_v2.i, ptr %des, align 2
  ret void
}

define void @vrshlq_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 1
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32> %0, <4 x i32> <i32 -1, i32 -1, i32 -1, i32 -1>)
  store <4 x i32> %vrshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vrshl_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsll.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32> %0, <2 x i32> <i32 31, i32 31>)
  store <2 x i32> %vrshl_v2.i, ptr %des, align 4
  ret void
}

define void @vrshlq_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64> %0, <2 x i64> <i64 -128, i64 -128>)
  store <2 x i64> %vrshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vrshl_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -128>)
  store <1 x i64> %vrshl_v2.i, ptr %des, align 8
  ret void
}

define void @vrshlq_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8> %0, <16 x i8> <i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9, i8 -9>)
  store <16 x i8> %vrshlq_v.i, ptr %des, align 1
  ret void
}

define void @vrshl_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8> %0, <8 x i8> <i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126, i8 126>)
  store <8 x i8> %vrshl_v.i, ptr %des, align 1
  ret void
}

define void @vrshlq_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16> %0, <8 x i16> <i16 -15, i16 -15, i16 -15, i16 -15, i16 -15, i16 -15, i16 -15, i16 -15>)
  store <8 x i16> %vrshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vrshl_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16> %0, <4 x i16> <i16 -128, i16 -128, i16 -128, i16 -128>)
  store <4 x i16> %vrshl_v2.i, ptr %des, align 2
  ret void
}

define void @vrshlq_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32> %0, <4 x i32> <i32 -127, i32 -127, i32 -127, i32 -127>)
  store <4 x i32> %vrshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vrshl_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32> %0, <2 x i32> <i32 33, i32 33>)
  store <2 x i32> %vrshl_v2.i, ptr %des, align 4
  ret void
}

define void @vrshlq_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64> %0, <2 x i64> <i64 -65, i64 -65>)
  store <2 x i64> %vrshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vrshl_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vrshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64> %0, <1 x i64> <i64 127>)
  store <1 x i64> %vrshl_v2.i, ptr %des, align 8
  ret void
}

declare <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64>, <1 x i64>)
