; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vrshl_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsgtu.vi v0, v9, 15
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vrsub.vx v11, v9, a1
; CHECK-NEXT:    vssra.vv v8, v8, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 15
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v9, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vrshl_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsll.vv v11, v9, v8
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vssra.vv v9, v9, v10
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v11, v9, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vrshl_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsll.vv v11, v9, v8
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vssra.vv v9, v9, v10
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v11, v9, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vrshl_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmsgtu.vx v8, v9, a0
; CHECK-NEXT:    vsll.vv v11, v10, v9
; CHECK-NEXT:    vmsgtu.vi v0, v9, 7
; CHECK-NEXT:    vrsub.vi v9, v9, 0
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vi v0, v9, 7
; CHECK-NEXT:    vssra.vv v9, v10, v9
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v11, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vrshl_v.i, ptr %out, align 1
  ret void
}

define void @vrshl_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsll.vv v10, v9, v8
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vrsub.vx v11, v8, a1
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vmseq.vx v0, v11, a0
; CHECK-NEXT:    vssrl.vv v12, v9, v11
; CHECK-NEXT:    vsrl.vi v12, v9, 15, v0.t
; CHECK-NEXT:    vmsgtu.vx v0, v11, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vrshl_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsll.vv v10, v9, v8
; CHECK-NEXT:    vrsub.vx v11, v8, a0
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vmseq.vx v0, v11, a1
; CHECK-NEXT:    vssrl.vv v12, v9, v11
; CHECK-NEXT:    vsrl.vi v12, v9, 31, v0.t
; CHECK-NEXT:    vmsgtu.vx v0, v11, a1
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vrshl_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v8, v8, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmseq.vx v0, v10, a1
; CHECK-NEXT:    vssrl.vv v11, v9, v10
; CHECK-NEXT:    vsrl.vx v11, v9, a0, v0.t
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmerge.vim v10, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vsll.vv v9, v9, v8
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vrshl_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vmsgtu.vi v0, v9, 7
; CHECK-NEXT:    vrsub.vi v11, v9, 0
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vmseq.vi v0, v11, 8
; CHECK-NEXT:    vssrl.vv v12, v8, v11
; CHECK-NEXT:    vsrl.vi v12, v8, 7, v0.t
; CHECK-NEXT:    vmsgtu.vi v0, v11, 8
; CHECK-NEXT:    vmsgtu.vx v8, v9, a0
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vrshl_v.i, ptr %out, align 1
  ret void
}

define void @vrshlq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vand.vx v9, v9, a0
; CHECK-NEXT:    vmsgtu.vi v0, v9, 15
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vrsub.vx v11, v9, a1
; CHECK-NEXT:    vssra.vv v8, v8, v11
; CHECK-NEXT:    vmsgtu.vi v0, v11, 15
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v9, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v8, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vrshlq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsll.vv v11, v9, v8
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vssra.vv v9, v9, v10
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v11, v9, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vrshlq_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vrsub.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsll.vv v11, v9, v8
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vssra.vv v9, v9, v10
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v11, v9, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vrshlq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmsgtu.vx v8, v9, a0
; CHECK-NEXT:    vsll.vv v11, v10, v9
; CHECK-NEXT:    vmsgtu.vi v0, v9, 7
; CHECK-NEXT:    vrsub.vi v9, v9, 0
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vi v0, v9, 7
; CHECK-NEXT:    vssra.vv v9, v10, v9
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v11, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vrshlq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 16
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsll.vv v10, v9, v8
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vrsub.vx v11, v8, a1
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vmseq.vx v0, v11, a0
; CHECK-NEXT:    vssrl.vv v12, v9, v11
; CHECK-NEXT:    vsrl.vi v12, v9, 15, v0.t
; CHECK-NEXT:    vmsgtu.vx v0, v11, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vrshlq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vand.vx v8, v8, a0
; CHECK-NEXT:    li a0, 256
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsll.vv v10, v9, v8
; CHECK-NEXT:    vrsub.vx v11, v8, a0
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vmseq.vx v0, v11, a1
; CHECK-NEXT:    vssrl.vv v12, v9, v11
; CHECK-NEXT:    vsrl.vi v12, v9, 31, v0.t
; CHECK-NEXT:    vmsgtu.vx v0, v11, a1
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vrshlq_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    li a1, 255
; CHECK-NEXT:    vand.vx v8, v8, a1
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vrsub.vx v10, v8, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vmseq.vx v0, v10, a1
; CHECK-NEXT:    vssrl.vv v11, v9, v10
; CHECK-NEXT:    vsrl.vx v11, v9, a0, v0.t
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vmerge.vim v10, v11, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a0
; CHECK-NEXT:    vsll.vv v9, v9, v8
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vrshlq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vmsgtu.vi v0, v9, 7
; CHECK-NEXT:    vrsub.vi v11, v9, 0
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vmseq.vi v0, v11, 8
; CHECK-NEXT:    vssrl.vv v12, v8, v11
; CHECK-NEXT:    vsrl.vi v12, v8, 7, v0.t
; CHECK-NEXT:    vmsgtu.vi v0, v11, 8
; CHECK-NEXT:    vmsgtu.vx v8, v9, a0
; CHECK-NEXT:    vmerge.vim v9, v12, 0, v0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vmerge.vvm v8, v10, v9, v0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vrshr_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 1
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vrshr_n2 = tail call <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16> %0, <4 x i16> <i16 -1, i16 -1, i16 -1, i16 -1>)
  store <4 x i16> %vrshr_n2, ptr %out, align 2
  ret void
}

define void @vrshr_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 1
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vrshr_n2 = tail call <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32> %0, <2 x i32> <i32 -1, i32 -1>)
  store <2 x i32> %vrshr_n2, ptr %out, align 4
  ret void
}

define void @vrshr_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vrshr_n2 = tail call <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -64>)
  store <1 x i64> %vrshr_n2, ptr %out, align 8
  ret void
}

define void @vrshr_n_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 7
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vrshr_n = tail call <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8> %0, <8 x i8> <i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7, i8 -7>)
  store <8 x i8> %vrshr_n, ptr %out, align 1
  ret void
}

define void @vrshr_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vrshr_n2 = tail call <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16> %0, <4 x i16> <i16 -16, i16 -16, i16 -16, i16 -16>)
  store <4 x i16> %vrshr_n2, ptr %out, align 2
  ret void
}

define void @vrshr_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vrshr_n2 = tail call <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32> %0, <2 x i32> <i32 -32, i32 -32>)
  store <2 x i32> %vrshr_n2, ptr %out, align 4
  ret void
}

define void @vrshr_n_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vrshr_n2 = tail call <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -64>)
  store <1 x i64> %vrshr_n2, ptr %out, align 8
  ret void
}

define void @vrshr_n_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshr_n_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vi v8, v8, 1
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vrshr_n = tail call <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8> %0, <8 x i8> <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>)
  store <8 x i8> %vrshr_n, ptr %out, align 1
  ret void
}

define void @vrshrq_n_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 1
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vrshr_n2 = tail call <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16> %0, <8 x i16> <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>)
  store <8 x i16> %vrshr_n2, ptr %out, align 2
  ret void
}

define void @vrshrq_n_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vrshr_n2 = tail call <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32> %0, <4 x i32> <i32 -32, i32 -32, i32 -32, i32 -32>)
  store <4 x i32> %vrshr_n2, ptr %out, align 4
  ret void
}

define void @vrshrq_n_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vi v8, v8, 1
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vrshr_n2 = tail call <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64> %0, <2 x i64> <i64 -1, i64 -1>)
  store <2 x i64> %vrshr_n2, ptr %out, align 8
  ret void
}

define void @vrshrq_n_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vrshr_n = tail call <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8> %0, <16 x i8> <i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8>)
  store <16 x i8> %vrshr_n, ptr %out, align 1
  ret void
}

define void @vrshrq_n_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 15
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vrshr_n2 = tail call <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16> %0, <8 x i16> <i16 -16, i16 -16, i16 -16, i16 -16, i16 -16, i16 -16, i16 -16, i16 -16>)
  store <8 x i16> %vrshr_n2, ptr %out, align 2
  ret void
}

define void @vrshrq_n_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vrshr_n2 = tail call <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32> %0, <4 x i32> <i32 -31, i32 -31, i32 -31, i32 -31>)
  store <4 x i32> %vrshr_n2, ptr %out, align 4
  ret void
}

define void @vrshrq_n_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vrshr_n2 = tail call <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64> %0, <2 x i64> <i64 -63, i64 -63>)
  store <2 x i64> %vrshr_n2, ptr %out, align 8
  ret void
}

define void @vrshrq_n_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshrq_n_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 7
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vrshr_n = tail call <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8> %0, <16 x i8> <i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8, i8 -8>)
  store <16 x i8> %vrshr_n, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64>, <1 x i64>)
declare <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8>, <16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64>, <2 x i64>)
declare <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64>, <2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32>, <4 x i32>)
declare <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8>, <8 x i8>)
