; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vrsqrts_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrsqrts_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 144
; CHECK-NEXT:    lui a1, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI0_1)
; CHECK-NEXT:    flh fa4, %lo(.LCPI0_1)(a1)
; CHECK-NEXT:    vfabs.v v10, v8
; CHECK-NEXT:    vfabs.v v11, v9
; CHECK-NEXT:    vfclass.v v10, v10
; CHECK-NEXT:    vfclass.v v11, v11
; CHECK-NEXT:    vor.vv v10, v10, v11
; CHECK-NEXT:    vmsne.vx v0, v10, a0
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    vfnmsac.vv v10, v8, v9, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa4
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x half>, ptr %in_0, align 2
  %1 = load <4 x half>, ptr %in_1, align 2
  %vrsqrts_v2.i = tail call <4 x half> @llvm.aarch64.neon.frsqrts.v4f16(<4 x half> %0, <4 x half> %1)
  store <4 x half> %vrsqrts_v2.i, ptr %out, align 2
  ret void
}

define void @vrsqrts_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrsqrts_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    li a0, 144
; CHECK-NEXT:    lui a1, 263168
; CHECK-NEXT:    vfabs.v v10, v8
; CHECK-NEXT:    vfabs.v v11, v9
; CHECK-NEXT:    vfclass.v v10, v10
; CHECK-NEXT:    vfclass.v v11, v11
; CHECK-NEXT:    vor.vv v10, v10, v11
; CHECK-NEXT:    vmsne.vx v0, v10, a0
; CHECK-NEXT:    lui a0, 258048
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    vfnmsac.vv v10, v8, v9, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v10, fa5
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x float>, ptr %in_0, align 4
  %1 = load <2 x float>, ptr %in_1, align 4
  %vrsqrts_v2.i = tail call <2 x float> @llvm.aarch64.neon.frsqrts.v2f32(<2 x float> %0, <2 x float> %1)
  store <2 x float> %vrsqrts_v2.i, ptr %out, align 4
  ret void
}

define void @vrsqrts_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrsqrts_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, 144
; CHECK-NEXT:    lui a1, %hi(.LCPI2_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI2_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI2_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI2_1)(a1)
; CHECK-NEXT:    vfabs.v v10, v8
; CHECK-NEXT:    vfabs.v v11, v9
; CHECK-NEXT:    vfclass.v v10, v10
; CHECK-NEXT:    vfclass.v v11, v11
; CHECK-NEXT:    vor.vv v10, v10, v11
; CHECK-NEXT:    vmsne.vx v0, v10, a0
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    vfnmsac.vv v10, v8, v9, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa4
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x double>, ptr %in_0, align 8
  %1 = load <1 x double>, ptr %in_1, align 8
  %vrsqrts_v2.i = tail call <1 x double> @llvm.aarch64.neon.frsqrts.v1f64(<1 x double> %0, <1 x double> %1)
  store <1 x double> %vrsqrts_v2.i, ptr %out, align 8
  ret void
}

define void @vrsqrtsq_f16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrsqrtsq_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vle16.v v9, (a1)
; CHECK-NEXT:    li a0, 144
; CHECK-NEXT:    lui a1, %hi(.LCPI3_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI3_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI3_1)
; CHECK-NEXT:    flh fa4, %lo(.LCPI3_1)(a1)
; CHECK-NEXT:    vfabs.v v10, v8
; CHECK-NEXT:    vfabs.v v11, v9
; CHECK-NEXT:    vfclass.v v10, v10
; CHECK-NEXT:    vfclass.v v11, v11
; CHECK-NEXT:    vor.vv v10, v10, v11
; CHECK-NEXT:    vmsne.vx v0, v10, a0
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    vfnmsac.vv v10, v8, v9, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa4
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x half>, ptr %in_0, align 2
  %1 = load <8 x half>, ptr %in_1, align 2
  %vrsqrtsq_v2.i = tail call <8 x half> @llvm.aarch64.neon.frsqrts.v8f16(<8 x half> %0, <8 x half> %1)
  store <8 x half> %vrsqrtsq_v2.i, ptr %out, align 2
  ret void
}

define void @vrsqrtsq_f32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrsqrtsq_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vle32.v v9, (a1)
; CHECK-NEXT:    li a0, 144
; CHECK-NEXT:    lui a1, 263168
; CHECK-NEXT:    vfabs.v v10, v8
; CHECK-NEXT:    vfabs.v v11, v9
; CHECK-NEXT:    vfclass.v v10, v10
; CHECK-NEXT:    vfclass.v v11, v11
; CHECK-NEXT:    vor.vv v10, v10, v11
; CHECK-NEXT:    vmsne.vx v0, v10, a0
; CHECK-NEXT:    lui a0, 258048
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    vfnmsac.vv v10, v8, v9, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v10, fa5
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x float>, ptr %in_0, align 4
  %1 = load <4 x float>, ptr %in_1, align 4
  %vrsqrtsq_v2.i = tail call <4 x float> @llvm.aarch64.neon.frsqrts.v4f32(<4 x float> %0, <4 x float> %1)
  store <4 x float> %vrsqrtsq_v2.i, ptr %out, align 4
  ret void
}

define void @vrsqrtsq_f64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrsqrtsq_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vle64.v v9, (a1)
; CHECK-NEXT:    li a0, 144
; CHECK-NEXT:    lui a1, %hi(.LCPI5_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI5_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI5_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI5_1)(a1)
; CHECK-NEXT:    vfabs.v v10, v8
; CHECK-NEXT:    vfabs.v v11, v9
; CHECK-NEXT:    vfclass.v v10, v10
; CHECK-NEXT:    vfclass.v v11, v11
; CHECK-NEXT:    vor.vv v10, v10, v11
; CHECK-NEXT:    vmsne.vx v0, v10, a0
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    vfnmsac.vv v10, v8, v9, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa4
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x double>, ptr %in_0, align 8
  %1 = load <2 x double>, ptr %in_1, align 8
  %vrsqrtsq_v2.i = tail call <2 x double> @llvm.aarch64.neon.frsqrts.v2f64(<2 x double> %0, <2 x double> %1)
  store <2 x double> %vrsqrtsq_v2.i, ptr %out, align 8
  ret void
}

declare <1 x double> @llvm.aarch64.neon.frsqrts.v1f64(<1 x double>, <1 x double>)
declare <2 x double> @llvm.aarch64.neon.frsqrts.v2f64(<2 x double>, <2 x double>)
declare <2 x float> @llvm.aarch64.neon.frsqrts.v2f32(<2 x float>, <2 x float>)
declare <4 x float> @llvm.aarch64.neon.frsqrts.v4f32(<4 x float>, <4 x float>)
declare <4 x half> @llvm.aarch64.neon.frsqrts.v4f16(<4 x half>, <4 x half>)
declare <8 x half> @llvm.aarch64.neon.frsqrts.v8f16(<8 x half>, <8 x half>)
