; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zbb,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqrshl_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    bgeu a3, a1, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB0_3
; CHECK-NEXT:    j .LBB0_4
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB0_4
; CHECK-NEXT:  .LBB0_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v8, 0
; CHECK-NEXT:  .LBB0_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vqrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqrshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vqrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshl_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    bgeu a3, a1, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB1_3
; CHECK-NEXT:    j .LBB1_4
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB1_4
; CHECK-NEXT:  .LBB1_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v8, 0
; CHECK-NEXT:  .LBB1_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vqrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqrshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vqrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshl_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    bgeu a3, a1, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB2_3
; CHECK-NEXT:    j .LBB2_4
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB2_4
; CHECK-NEXT:  .LBB2_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmv.s.x v9, a0
; CHECK-NEXT:    vmv.s.x v10, a1
; CHECK-NEXT:    vminu.vx v9, v9, a1
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    vmsne.vi v11, v8, 0
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    vmsltu.vx v10, v10, a0
; CHECK-NEXT:    srli a0, a1, 1
; CHECK-NEXT:    slli a1, a1, 63
; CHECK-NEXT:    vmv.s.x v12, a0
; CHECK-NEXT:    vmand.mm v10, v11, v10
; CHECK-NEXT:    vsll.vv v11, v8, v9
; CHECK-NEXT:    vsra.vv v9, v11, v9
; CHECK-NEXT:    vmsne.vv v8, v8, v9
; CHECK-NEXT:    vmor.mm v8, v8, v10
; CHECK-NEXT:    vmerge.vxm v9, v12, a1, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v9, v11, v9, v0
; CHECK-NEXT:  .LBB2_4: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vqrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sqrshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vqrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshl_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    bgeu a3, a0, .LBB3_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a1, a3, .LBB3_3
; CHECK-NEXT:    j .LBB3_4
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a1, a3, .LBB3_4
; CHECK-NEXT:  .LBB3_3: # %entry
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v8, 0
; CHECK-NEXT:  .LBB3_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vqrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqrshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vqrshl_v.i, ptr %out, align 1
  ret void
}

define void @vqrshl_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    beq a3, a1, .LBB4_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a3
; CHECK-NEXT:    li a4, 17
; CHECK-NEXT:    bgeu a3, a4, .LBB4_3
; CHECK-NEXT:    j .LBB4_4
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    vsrl.vi v9, v8, 15
; CHECK-NEXT:    li a4, 17
; CHECK-NEXT:    bltu a3, a4, .LBB4_4
; CHECK-NEXT:  .LBB4_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB4_4: # %entry
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB4_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB4_6: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v8, 0
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vqrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.uqrshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vqrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshl_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    beq a3, a1, .LBB5_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a3
; CHECK-NEXT:    li a4, 33
; CHECK-NEXT:    bgeu a3, a4, .LBB5_3
; CHECK-NEXT:    j .LBB5_4
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    vsrl.vi v9, v8, 31
; CHECK-NEXT:    li a4, 33
; CHECK-NEXT:    bltu a3, a4, .LBB5_4
; CHECK-NEXT:  .LBB5_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB5_4: # %entry
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB5_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB5_6: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v8, 0
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vqrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.uqrshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vqrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshl_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:    li a4, 256
; CHECK-NEXT:    sub a4, a4, a1
; CHECK-NEXT:    li a3, 64
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    beq a4, a3, .LBB6_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a4
; CHECK-NEXT:    li a5, 65
; CHECK-NEXT:    bgeu a4, a5, .LBB6_3
; CHECK-NEXT:    j .LBB6_4
; CHECK-NEXT:  .LBB6_2:
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:    li a5, 65
; CHECK-NEXT:    bltu a4, a5, .LBB6_4
; CHECK-NEXT:  .LBB6_3:
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:  .LBB6_4: # %entry
; CHECK-NEXT:    li a4, 128
; CHECK-NEXT:    bltu a1, a4, .LBB6_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB6_6: # %entry
; CHECK-NEXT:    minu a1, a1, a3
; CHECK-NEXT:    vmv.s.x v9, a0
; CHECK-NEXT:    vmsne.vi v10, v8, 0
; CHECK-NEXT:    vmv.s.x v11, a1
; CHECK-NEXT:    vmsltu.vx v9, v9, a1
; CHECK-NEXT:    vminu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v9, v10, v9
; CHECK-NEXT:    vsll.vv v10, v8, v11
; CHECK-NEXT:    vsrl.vv v11, v10, v11
; CHECK-NEXT:    vmsne.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vim v9, v10, -1, v0
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vqrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.uqrshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vqrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshl_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    beq a3, a0, .LBB7_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a3
; CHECK-NEXT:    li a4, 9
; CHECK-NEXT:    bgeu a3, a4, .LBB7_3
; CHECK-NEXT:    j .LBB7_4
; CHECK-NEXT:  .LBB7_2:
; CHECK-NEXT:    vsrl.vi v9, v8, 7
; CHECK-NEXT:    li a4, 9
; CHECK-NEXT:    bltu a3, a4, .LBB7_4
; CHECK-NEXT:  .LBB7_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB7_4: # %entry
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a1, a3, .LBB7_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB7_6: # %entry
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v8, 0
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vqrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.uqrshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vqrshl_v.i, ptr %out, align 1
  ret void
}

define void @vqrshlq_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    bgeu a3, a1, .LBB8_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB8_3
; CHECK-NEXT:    j .LBB8_4
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB8_4
; CHECK-NEXT:  .LBB8_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v10, 0
; CHECK-NEXT:  .LBB8_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vqrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqrshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vqrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshlq_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    bgeu a3, a1, .LBB9_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB9_3
; CHECK-NEXT:    j .LBB9_4
; CHECK-NEXT:  .LBB9_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB9_4
; CHECK-NEXT:  .LBB9_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v10, 0
; CHECK-NEXT:  .LBB9_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vqrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqrshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vqrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshlq_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    bgeu a3, a1, .LBB10_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB10_3
; CHECK-NEXT:    j .LBB10_4
; CHECK-NEXT:  .LBB10_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB10_4
; CHECK-NEXT:  .LBB10_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    vminu.vx v9, v9, a1
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    vmsne.vi v11, v8, 0
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    vmsltu.vx v10, v10, a0
; CHECK-NEXT:    srli a0, a1, 1
; CHECK-NEXT:    slli a1, a1, 63
; CHECK-NEXT:    vmv.v.x v12, a0
; CHECK-NEXT:    vmand.mm v10, v11, v10
; CHECK-NEXT:    vsll.vv v11, v8, v9
; CHECK-NEXT:    vsra.vv v9, v11, v9
; CHECK-NEXT:    vmsne.vv v8, v8, v9
; CHECK-NEXT:    vmor.mm v8, v8, v10
; CHECK-NEXT:    vmerge.vxm v9, v12, a1, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vvm v9, v11, v9, v0
; CHECK-NEXT:  .LBB10_4: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vqrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sqrshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vqrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshlq_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    bgeu a3, a0, .LBB11_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a1, a3, .LBB11_3
; CHECK-NEXT:    j .LBB11_4
; CHECK-NEXT:  .LBB11_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a1, a3, .LBB11_4
; CHECK-NEXT:  .LBB11_3: # %entry
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v9, v10, 0
; CHECK-NEXT:  .LBB11_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vqrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqrshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vqrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vqrshlq_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    beq a3, a1, .LBB12_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a3
; CHECK-NEXT:    li a4, 17
; CHECK-NEXT:    bgeu a3, a4, .LBB12_3
; CHECK-NEXT:    j .LBB12_4
; CHECK-NEXT:  .LBB12_2:
; CHECK-NEXT:    vsrl.vi v9, v8, 15
; CHECK-NEXT:    li a4, 17
; CHECK-NEXT:    bltu a3, a4, .LBB12_4
; CHECK-NEXT:  .LBB12_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB12_4: # %entry
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB12_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB12_6: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vqrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.uqrshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vqrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqrshlq_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    beq a3, a1, .LBB13_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a3
; CHECK-NEXT:    li a4, 33
; CHECK-NEXT:    bgeu a3, a4, .LBB13_3
; CHECK-NEXT:    j .LBB13_4
; CHECK-NEXT:  .LBB13_2:
; CHECK-NEXT:    vsrl.vi v9, v8, 31
; CHECK-NEXT:    li a4, 33
; CHECK-NEXT:    bltu a3, a4, .LBB13_4
; CHECK-NEXT:  .LBB13_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB13_4: # %entry
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB13_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB13_6: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vqrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.uqrshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vqrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqrshlq_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:    li a4, 256
; CHECK-NEXT:    sub a4, a4, a1
; CHECK-NEXT:    li a3, 64
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    beq a4, a3, .LBB14_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a4
; CHECK-NEXT:    li a5, 65
; CHECK-NEXT:    bgeu a4, a5, .LBB14_3
; CHECK-NEXT:    j .LBB14_4
; CHECK-NEXT:  .LBB14_2:
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:    li a5, 65
; CHECK-NEXT:    bltu a4, a5, .LBB14_4
; CHECK-NEXT:  .LBB14_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB14_4: # %entry
; CHECK-NEXT:    li a4, 128
; CHECK-NEXT:    bltu a1, a4, .LBB14_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB14_6: # %entry
; CHECK-NEXT:    minu a1, a1, a3
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vmsne.vi v10, v8, 0
; CHECK-NEXT:    vmv.v.x v11, a1
; CHECK-NEXT:    vmsltu.vx v9, v9, a1
; CHECK-NEXT:    vminu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v9, v10, v9
; CHECK-NEXT:    vsll.vv v10, v8, v11
; CHECK-NEXT:    vsrl.vv v11, v10, v11
; CHECK-NEXT:    vmsne.vv v8, v8, v11
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vim v9, v10, -1, v0
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vqrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.uqrshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vqrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqrshlq_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqrshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    beq a3, a0, .LBB15_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v9, v8, a3
; CHECK-NEXT:    li a4, 9
; CHECK-NEXT:    bgeu a3, a4, .LBB15_3
; CHECK-NEXT:    j .LBB15_4
; CHECK-NEXT:  .LBB15_2:
; CHECK-NEXT:    vsrl.vi v9, v8, 7
; CHECK-NEXT:    li a4, 9
; CHECK-NEXT:    bltu a3, a4, .LBB15_4
; CHECK-NEXT:  .LBB15_3:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:  .LBB15_4: # %entry
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a1, a3, .LBB15_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB15_6: # %entry
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vqrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.uqrshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vqrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vqshl_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB16_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB16_2:
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    sub a1, a1, a0
; CHECK-NEXT:    li a0, 15
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vqshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vqshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqshl_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB17_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB17_2:
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    sub a1, a1, a0
; CHECK-NEXT:    li a0, 31
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vqshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vqshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqshl_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    bgeu a1, a3, .LBB18_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    li a3, -1
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    vmv.s.x v9, a0
; CHECK-NEXT:    vmsne.vi v10, v8, 0
; CHECK-NEXT:    minu a1, a1, a4
; CHECK-NEXT:    srli a4, a3, 1
; CHECK-NEXT:    slli a3, a3, 63
; CHECK-NEXT:    vmv.s.x v11, a4
; CHECK-NEXT:    vmerge.vxm v11, v11, a3, v0
; CHECK-NEXT:    vmv.s.x v12, a1
; CHECK-NEXT:    vmsltu.vx v9, v9, a1
; CHECK-NEXT:    vminu.vx v12, v12, a0
; CHECK-NEXT:    vmand.mm v9, v10, v9
; CHECK-NEXT:    vsll.vv v10, v8, v12
; CHECK-NEXT:    vsra.vv v12, v10, v12
; CHECK-NEXT:    vmsne.vv v8, v8, v12
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vvm v8, v10, v11, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB18_2:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a1
; CHECK-NEXT:    minu a0, a3, a0
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vqshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vqshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqshl_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bgeu a1, a0, .LBB19_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB19_2:
; CHECK-NEXT:    neg a0, a1
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vqshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vqshl_v.i, ptr %out, align 1
  ret void
}

define void @vqshl_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    bgeu a3, a1, .LBB20_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB20_3
; CHECK-NEXT:    j .LBB20_4
; CHECK-NEXT:  .LBB20_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB20_4
; CHECK-NEXT:  .LBB20_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v8, 0
; CHECK-NEXT:  .LBB20_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vqshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vqshl_v2.i, ptr %out, align 2
  ret void
}

define void @vqshl_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    bgeu a3, a1, .LBB21_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB21_3
; CHECK-NEXT:    j .LBB21_4
; CHECK-NEXT:  .LBB21_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB21_4
; CHECK-NEXT:  .LBB21_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v8, 0
; CHECK-NEXT:  .LBB21_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vqshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vqshl_v2.i, ptr %out, align 4
  ret void
}

define void @vqshl_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    bgeu a3, a1, .LBB22_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB22_3
; CHECK-NEXT:    j .LBB22_4
; CHECK-NEXT:  .LBB22_2:
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB22_4
; CHECK-NEXT:  .LBB22_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmsne.vi v9, v8, 0
; CHECK-NEXT:    vmv.s.x v10, a0
; CHECK-NEXT:    vmv.s.x v11, a1
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmsltu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v9, v9, v11
; CHECK-NEXT:    vsll.vv v11, v8, v10
; CHECK-NEXT:    vsrl.vv v10, v11, v10
; CHECK-NEXT:    vmsne.vv v8, v8, v10
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vim v9, v11, -1, v0
; CHECK-NEXT:  .LBB22_4: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vqshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vqshl_v2.i, ptr %out, align 8
  ret void
}

define void @vqshl_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    bgeu a3, a0, .LBB23_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a1, a3, .LBB23_3
; CHECK-NEXT:    j .LBB23_4
; CHECK-NEXT:  .LBB23_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a1, a3, .LBB23_4
; CHECK-NEXT:  .LBB23_3: # %entry
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v9, v8
; CHECK-NEXT:    vsll.vv v8, v9, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v8, 0
; CHECK-NEXT:  .LBB23_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vqshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vqshl_v.i, ptr %out, align 1
  ret void
}

define void @vqshlq_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB24_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v8, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB24_2:
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    sub a1, a1, a0
; CHECK-NEXT:    li a0, 15
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vqshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vqshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqshlq_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB25_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v8, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB25_2:
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    sub a1, a1, a0
; CHECK-NEXT:    li a0, 31
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vqshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vqshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqshlq_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    bgeu a1, a3, .LBB26_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vmsle.vi v0, v8, -1
; CHECK-NEXT:    li a3, -1
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vmsne.vi v10, v8, 0
; CHECK-NEXT:    minu a1, a1, a4
; CHECK-NEXT:    srli a4, a3, 1
; CHECK-NEXT:    slli a3, a3, 63
; CHECK-NEXT:    vmv.v.x v11, a4
; CHECK-NEXT:    vmerge.vxm v11, v11, a3, v0
; CHECK-NEXT:    vmv.v.x v12, a1
; CHECK-NEXT:    vmsltu.vx v9, v9, a1
; CHECK-NEXT:    vminu.vx v12, v12, a0
; CHECK-NEXT:    vmand.mm v9, v10, v9
; CHECK-NEXT:    vsll.vv v10, v8, v12
; CHECK-NEXT:    vsra.vv v12, v10, v12
; CHECK-NEXT:    vmsne.vv v8, v8, v12
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vvm v8, v10, v11, v0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB26_2:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a1
; CHECK-NEXT:    minu a0, a3, a0
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vqshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vqshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqshlq_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bgeu a1, a0, .LBB27_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vsext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v8, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclip.wi v8, v8, 0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB27_2:
; CHECK-NEXT:    neg a0, a1
; CHECK-NEXT:    li a1, 7
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vqshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vqshlq_v.i, ptr %out, align 1
  ret void
}

define void @vqshlq_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    bgeu a3, a1, .LBB28_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB28_3
; CHECK-NEXT:    j .LBB28_4
; CHECK-NEXT:  .LBB28_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB28_4
; CHECK-NEXT:  .LBB28_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:  .LBB28_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vqshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vqshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vqshlq_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    bgeu a3, a1, .LBB29_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB29_3
; CHECK-NEXT:    j .LBB29_4
; CHECK-NEXT:  .LBB29_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB29_4
; CHECK-NEXT:  .LBB29_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:  .LBB29_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vqshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vqshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vqshlq_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    bgeu a3, a1, .LBB30_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a0, a3, .LBB30_3
; CHECK-NEXT:    j .LBB30_4
; CHECK-NEXT:  .LBB30_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a0, a3, .LBB30_4
; CHECK-NEXT:  .LBB30_3: # %entry
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmsne.vi v9, v8, 0
; CHECK-NEXT:    vmv.v.x v10, a0
; CHECK-NEXT:    vmv.v.x v11, a1
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmsltu.vx v11, v11, a0
; CHECK-NEXT:    vmand.mm v9, v9, v11
; CHECK-NEXT:    vsll.vv v11, v8, v10
; CHECK-NEXT:    vsrl.vv v10, v11, v10
; CHECK-NEXT:    vmsne.vv v8, v8, v10
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    vmerge.vim v9, v11, -1, v0
; CHECK-NEXT:  .LBB30_4: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vqshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vqshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vqshlq_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    bgeu a3, a0, .LBB31_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsrl.vx v9, v8, a3
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bltu a1, a3, .LBB31_3
; CHECK-NEXT:    j .LBB31_4
; CHECK-NEXT:  .LBB31_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 128
; CHECK-NEXT:    bgeu a1, a3, .LBB31_4
; CHECK-NEXT:  .LBB31_3: # %entry
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vmv.v.x v9, a0
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v9
; CHECK-NEXT:    vzext.vf2 v12, v8
; CHECK-NEXT:    vsll.vv v10, v12, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v9, v10, 0
; CHECK-NEXT:  .LBB31_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vqshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vqshlq_v.i, ptr %out, align 1
  ret void
}

define void @vrshl_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    bltu a3, a1, .LBB32_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB32_5
; CHECK-NEXT:  .LBB32_2: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB32_6
; CHECK-NEXT:  .LBB32_3: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB32_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a0, a1, .LBB32_2
; CHECK-NEXT:  .LBB32_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB32_3
; CHECK-NEXT:  .LBB32_6: # %entry
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vrshl_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    bltu a3, a1, .LBB33_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB33_5
; CHECK-NEXT:  .LBB33_2: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB33_6
; CHECK-NEXT:  .LBB33_3: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB33_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a0, a1, .LBB33_2
; CHECK-NEXT:  .LBB33_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB33_3
; CHECK-NEXT:  .LBB33_6: # %entry
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vrshl_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v10, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmv.v.v v9, v8
; CHECK-NEXT:    bltu a3, a1, .LBB34_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB34_5
; CHECK-NEXT:  .LBB34_2: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB34_6
; CHECK-NEXT:  .LBB34_3: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB34_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a0, a1, .LBB34_2
; CHECK-NEXT:  .LBB34_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB34_3
; CHECK-NEXT:  .LBB34_6: # %entry
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vrshl_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    vmv1r.v v9, v8
; CHECK-NEXT:    bltu a3, a0, .LBB35_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a1, a0, .LBB35_5
; CHECK-NEXT:  .LBB35_2: # %entry
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bltu a1, a0, .LBB35_6
; CHECK-NEXT:  .LBB35_3: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB35_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a1, a0, .LBB35_2
; CHECK-NEXT:  .LBB35_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a1
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bgeu a1, a0, .LBB35_3
; CHECK-NEXT:  .LBB35_6: # %entry
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vrshl_v.i, ptr %out, align 1
  ret void
}

define void @vrshl_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    beq a3, a1, .LBB36_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB36_3
; CHECK-NEXT:  .LBB36_2:
; CHECK-NEXT:    vsrl.vi v11, v8, 15
; CHECK-NEXT:  .LBB36_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 17
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB36_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB36_8
; CHECK-NEXT:  .LBB36_5: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB36_9
; CHECK-NEXT:  .LBB36_6: # %entry
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB36_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a0, a1, .LBB36_5
; CHECK-NEXT:  .LBB36_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB36_6
; CHECK-NEXT:  .LBB36_9: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vrshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vrshl_v2.i, ptr %out, align 2
  ret void
}

define void @vrshl_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    beq a3, a1, .LBB37_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB37_3
; CHECK-NEXT:  .LBB37_2:
; CHECK-NEXT:    vsrl.vi v11, v8, 31
; CHECK-NEXT:  .LBB37_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 33
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB37_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB37_8
; CHECK-NEXT:  .LBB37_5: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB37_9
; CHECK-NEXT:  .LBB37_6: # %entry
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB37_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a0, a1, .LBB37_5
; CHECK-NEXT:  .LBB37_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB37_6
; CHECK-NEXT:  .LBB37_9: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vrshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vrshl_v2.i, ptr %out, align 4
  ret void
}

define void @vrshl_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    beq a3, a1, .LBB38_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB38_3
; CHECK-NEXT:  .LBB38_2:
; CHECK-NEXT:    li a4, 63
; CHECK-NEXT:    vsrl.vx v11, v8, a4
; CHECK-NEXT:  .LBB38_3: # %entry
; CHECK-NEXT:    vmv.s.x v9, zero
; CHECK-NEXT:    li a4, 65
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB38_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB38_8
; CHECK-NEXT:  .LBB38_5: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB38_9
; CHECK-NEXT:  .LBB38_6: # %entry
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB38_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a0, a1, .LBB38_5
; CHECK-NEXT:  .LBB38_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB38_6
; CHECK-NEXT:  .LBB38_9: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vrshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vrshl_v2.i, ptr %out, align 8
  ret void
}

define void @vrshl_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    beq a3, a0, .LBB39_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB39_3
; CHECK-NEXT:  .LBB39_2:
; CHECK-NEXT:    vsrl.vi v11, v8, 7
; CHECK-NEXT:  .LBB39_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 9
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB39_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a1, a0, .LBB39_8
; CHECK-NEXT:  .LBB39_5: # %entry
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bltu a1, a0, .LBB39_9
; CHECK-NEXT:  .LBB39_6: # %entry
; CHECK-NEXT:    vse8.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB39_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a1, a0, .LBB39_5
; CHECK-NEXT:  .LBB39_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a1
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bgeu a1, a0, .LBB39_6
; CHECK-NEXT:  .LBB39_9: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vrshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vrshl_v.i, ptr %out, align 1
  ret void
}

define void @vrshlq_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v10, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bltu a3, a1, .LBB40_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB40_5
; CHECK-NEXT:  .LBB40_2: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB40_6
; CHECK-NEXT:  .LBB40_3: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB40_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a0, a1, .LBB40_2
; CHECK-NEXT:  .LBB40_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB40_3
; CHECK-NEXT:  .LBB40_6: # %entry
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vrshlq_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v10, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bltu a3, a1, .LBB41_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB41_5
; CHECK-NEXT:  .LBB41_2: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB41_6
; CHECK-NEXT:  .LBB41_3: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB41_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a0, a1, .LBB41_2
; CHECK-NEXT:  .LBB41_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB41_3
; CHECK-NEXT:  .LBB41_6: # %entry
; CHECK-NEXT:    vse32.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vrshlq_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v10, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bltu a3, a1, .LBB42_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB42_5
; CHECK-NEXT:  .LBB42_2: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB42_6
; CHECK-NEXT:  .LBB42_3: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB42_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a0, a1, .LBB42_2
; CHECK-NEXT:  .LBB42_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB42_3
; CHECK-NEXT:  .LBB42_6: # %entry
; CHECK-NEXT:    vse64.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vrshlq_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v10, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bltu a3, a0, .LBB43_4
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    bltu a1, a0, .LBB43_5
; CHECK-NEXT:  .LBB43_2: # %entry
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bltu a1, a0, .LBB43_6
; CHECK-NEXT:  .LBB43_3: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB43_4: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssra.vx v9, v10, a3
; CHECK-NEXT:    bgeu a1, a0, .LBB43_2
; CHECK-NEXT:  .LBB43_5: # %entry
; CHECK-NEXT:    vsll.vx v8, v10, a1
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bgeu a1, a0, .LBB43_3
; CHECK-NEXT:  .LBB43_6: # %entry
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vrshlq_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 16
; CHECK-NEXT:    beq a3, a1, .LBB44_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB44_3
; CHECK-NEXT:  .LBB44_2:
; CHECK-NEXT:    vsrl.vi v11, v8, 15
; CHECK-NEXT:  .LBB44_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 17
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB44_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB44_8
; CHECK-NEXT:  .LBB44_5: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB44_9
; CHECK-NEXT:  .LBB44_6: # %entry
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB44_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a0, a1, .LBB44_5
; CHECK-NEXT:  .LBB44_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB44_6
; CHECK-NEXT:  .LBB44_9: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vrshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vrshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vrshlq_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    beq a3, a1, .LBB45_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB45_3
; CHECK-NEXT:  .LBB45_2:
; CHECK-NEXT:    vsrl.vi v11, v8, 31
; CHECK-NEXT:  .LBB45_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 33
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB45_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB45_8
; CHECK-NEXT:  .LBB45_5: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB45_9
; CHECK-NEXT:  .LBB45_6: # %entry
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB45_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a0, a1, .LBB45_5
; CHECK-NEXT:  .LBB45_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB45_6
; CHECK-NEXT:  .LBB45_9: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vrshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vrshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vrshlq_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    beq a3, a1, .LBB46_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB46_3
; CHECK-NEXT:  .LBB46_2:
; CHECK-NEXT:    li a4, 63
; CHECK-NEXT:    vsrl.vx v11, v8, a4
; CHECK-NEXT:  .LBB46_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 65
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB46_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a0, a1, .LBB46_8
; CHECK-NEXT:  .LBB46_5: # %entry
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bltu a0, a1, .LBB46_9
; CHECK-NEXT:  .LBB46_6: # %entry
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB46_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a0, a1, .LBB46_5
; CHECK-NEXT:  .LBB46_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    bgeu a0, a1, .LBB46_6
; CHECK-NEXT:  .LBB46_9: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vrshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vrshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vrshlq_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vrshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    neg a3, a1
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    beq a3, a0, .LBB47_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    csrwi vxrm, 0
; CHECK-NEXT:    vssrl.vx v11, v8, a3
; CHECK-NEXT:    j .LBB47_3
; CHECK-NEXT:  .LBB47_2:
; CHECK-NEXT:    vsrl.vi v11, v8, 7
; CHECK-NEXT:  .LBB47_3: # %entry
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a4, 9
; CHECK-NEXT:    vmv1r.v v10, v9
; CHECK-NEXT:    bltu a3, a4, .LBB47_7
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    bltu a1, a0, .LBB47_8
; CHECK-NEXT:  .LBB47_5: # %entry
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bltu a1, a0, .LBB47_9
; CHECK-NEXT:  .LBB47_6: # %entry
; CHECK-NEXT:    vse8.v v10, (a2)
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB47_7: # %entry
; CHECK-NEXT:    vmv1r.v v10, v11
; CHECK-NEXT:    bgeu a1, a0, .LBB47_5
; CHECK-NEXT:  .LBB47_8: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a1
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    bgeu a1, a0, .LBB47_6
; CHECK-NEXT:  .LBB47_9: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vrshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vrshlq_v.i, ptr %out, align 1
  ret void
}

define void @vshl_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    bltu a1, a0, .LBB48_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB48_3
; CHECK-NEXT:    j .LBB48_4
; CHECK-NEXT:  .LBB48_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB48_4
; CHECK-NEXT:  .LBB48_3:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    minu a0, a3, a1
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB48_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sshl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vshl_v2.i, ptr %out, align 2
  ret void
}

define void @vshl_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    bltu a1, a0, .LBB49_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB49_3
; CHECK-NEXT:    j .LBB49_4
; CHECK-NEXT:  .LBB49_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB49_4
; CHECK-NEXT:  .LBB49_3:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    minu a0, a3, a1
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB49_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sshl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vshl_v2.i, ptr %out, align 4
  ret void
}

define void @vshl_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sshl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vshl_v2.i, ptr %out, align 8
  ret void
}

define void @vshl_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    bltu a0, a1, .LBB51_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a1
; CHECK-NEXT:    bltz a1, .LBB51_3
; CHECK-NEXT:    j .LBB51_4
; CHECK-NEXT:  .LBB51_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bgez a1, .LBB51_4
; CHECK-NEXT:  .LBB51_3:
; CHECK-NEXT:    negw a1, a1
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB51_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sshl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vshl_v.i, ptr %out, align 1
  ret void
}

define void @vshl_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    bltu a1, a0, .LBB52_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB52_3
; CHECK-NEXT:    j .LBB52_4
; CHECK-NEXT:  .LBB52_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB52_4
; CHECK-NEXT:  .LBB52_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    xori a0, a0, 255
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB52_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <4 x i16> undef, i16 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i16> %vecinit.i, <4 x i16> poison, <4 x i32> zeroinitializer
  %vshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.ushl.v4i16(<4 x i16> %0, <4 x i16> %vecinit3.i)
  store <4 x i16> %vshl_v2.i, ptr %out, align 2
  ret void
}

define void @vshl_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    bltu a1, a0, .LBB53_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB53_3
; CHECK-NEXT:    j .LBB53_4
; CHECK-NEXT:  .LBB53_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB53_4
; CHECK-NEXT:  .LBB53_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    xori a0, a0, 255
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB53_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <2 x i32> undef, i32 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i32> %vecinit.i, <2 x i32> poison, <2 x i32> zeroinitializer
  %vshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.ushl.v2i32(<2 x i32> %0, <2 x i32> %vecinit1.i)
  store <2 x i32> %vshl_v2.i, ptr %out, align 4
  ret void
}

define void @vshl_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vxor.vx v11, v10, a0
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vsrl.vi v9, v9, 1
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsrl.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <1 x i64> undef, i64 %in_1, i64 0
  %vshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.ushl.v1i64(<1 x i64> %0, <1 x i64> %vecinit.i)
  store <1 x i64> %vshl_v2.i, ptr %out, align 8
  ret void
}

define void @vshl_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    bltu a0, a1, .LBB55_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a1
; CHECK-NEXT:    bltz a1, .LBB55_3
; CHECK-NEXT:    j .LBB55_4
; CHECK-NEXT:  .LBB55_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bgez a1, .LBB55_4
; CHECK-NEXT:  .LBB55_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    li a0, -8
; CHECK-NEXT:    maxu a0, a1, a0
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB55_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <8 x i8> undef, i8 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i8> %vecinit.i, <8 x i8> poison, <8 x i32> zeroinitializer
  %vshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.ushl.v8i8(<8 x i8> %0, <8 x i8> %vecinit7.i)
  store <8 x i8> %vshl_v.i, ptr %out, align 1
  ret void
}

define void @vshlq_s16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    bltu a1, a0, .LBB56_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB56_3
; CHECK-NEXT:    j .LBB56_4
; CHECK-NEXT:  .LBB56_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB56_4
; CHECK-NEXT:  .LBB56_3:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    minu a0, a3, a1
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB56_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vshlq_s32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    bltu a1, a0, .LBB57_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB57_3
; CHECK-NEXT:    j .LBB57_4
; CHECK-NEXT:  .LBB57_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB57_4
; CHECK-NEXT:  .LBB57_3:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    minu a0, a3, a1
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB57_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vshlq_s64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    bltu a1, a0, .LBB58_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB58_3
; CHECK-NEXT:    j .LBB58_4
; CHECK-NEXT:  .LBB58_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB58_4
; CHECK-NEXT:  .LBB58_3:
; CHECK-NEXT:    li a3, 256
; CHECK-NEXT:    sub a3, a3, a0
; CHECK-NEXT:    minu a0, a3, a1
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB58_4: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vshlq_s8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    bltu a0, a1, .LBB59_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a1
; CHECK-NEXT:    bltz a1, .LBB59_3
; CHECK-NEXT:    j .LBB59_4
; CHECK-NEXT:  .LBB59_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bgez a1, .LBB59_4
; CHECK-NEXT:  .LBB59_3:
; CHECK-NEXT:    negw a1, a1
; CHECK-NEXT:    zext.b a1, a1
; CHECK-NEXT:    minu a0, a1, a0
; CHECK-NEXT:    vsra.vx v9, v8, a0
; CHECK-NEXT:  .LBB59_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vshlq_v.i, ptr %out, align 1
  ret void
}

define void @vshlq_u16(ptr nocapture noundef readonly %in_0, i16 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    bltu a1, a0, .LBB60_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB60_3
; CHECK-NEXT:    j .LBB60_4
; CHECK-NEXT:  .LBB60_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB60_4
; CHECK-NEXT:  .LBB60_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    xori a0, a0, 255
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB60_4: # %entry
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %vecinit.i = insertelement <8 x i16> undef, i16 %in_1, i64 0
  %vecinit7.i = shufflevector <8 x i16> %vecinit.i, <8 x i16> poison, <8 x i32> zeroinitializer
  %vshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16> %0, <8 x i16> %vecinit7.i)
  store <8 x i16> %vshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vshlq_u32(ptr nocapture noundef readonly %in_0, i32 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    bltu a1, a0, .LBB61_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB61_3
; CHECK-NEXT:    j .LBB61_4
; CHECK-NEXT:  .LBB61_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB61_4
; CHECK-NEXT:  .LBB61_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    xori a0, a0, 255
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB61_4: # %entry
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %vecinit.i = insertelement <4 x i32> undef, i32 %in_1, i64 0
  %vecinit3.i = shufflevector <4 x i32> %vecinit.i, <4 x i32> poison, <4 x i32> zeroinitializer
  %vshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32> %0, <4 x i32> %vecinit3.i)
  store <4 x i32> %vshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vshlq_u64(ptr nocapture noundef readonly %in_0, i64 noundef %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    zext.b a0, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    bltu a1, a0, .LBB62_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bltu a3, a0, .LBB62_3
; CHECK-NEXT:    j .LBB62_4
; CHECK-NEXT:  .LBB62_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    li a3, 127
; CHECK-NEXT:    bgeu a3, a0, .LBB62_4
; CHECK-NEXT:  .LBB62_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    xori a0, a0, 255
; CHECK-NEXT:    minu a0, a0, a1
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB62_4: # %entry
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %vecinit.i = insertelement <2 x i64> undef, i64 %in_1, i64 0
  %vecinit1.i = shufflevector <2 x i64> %vecinit.i, <2 x i64> poison, <2 x i32> zeroinitializer
  %vshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64> %0, <2 x i64> %vecinit1.i)
  store <2 x i64> %vshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vshlq_u8(ptr nocapture noundef readonly %in_0, i8 noundef signext %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    bltu a0, a1, .LBB63_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    vsll.vx v9, v8, a1
; CHECK-NEXT:    bltz a1, .LBB63_3
; CHECK-NEXT:    j .LBB63_4
; CHECK-NEXT:  .LBB63_2:
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    bgez a1, .LBB63_4
; CHECK-NEXT:  .LBB63_3:
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    li a0, -8
; CHECK-NEXT:    maxu a0, a1, a0
; CHECK-NEXT:    not a0, a0
; CHECK-NEXT:    vsrl.vx v9, v8, a0
; CHECK-NEXT:  .LBB63_4: # %entry
; CHECK-NEXT:    vse8.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vecinit.i = insertelement <16 x i8> undef, i8 %in_1, i64 0
  %vecinit15.i = shufflevector <16 x i8> %vecinit.i, <16 x i8> poison, <16 x i32> zeroinitializer
  %vshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8> %0, <16 x i8> %vecinit15.i)
  store <16 x i8> %vshlq_v.i, ptr %out, align 1
  ret void
}

declare <4 x i16> @llvm.aarch64.neon.sqrshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.sqrshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.sqrshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.sqrshl.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.aarch64.neon.uqrshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.uqrshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.uqrshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.uqrshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sqrshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqrshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqrshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sqrshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.aarch64.neon.uqrshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.uqrshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.uqrshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.uqrshl.v16i8(<16 x i8>, <16 x i8>)
declare <4 x i16> @llvm.aarch64.neon.sqshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.sqshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.sqshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.sqshl.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.aarch64.neon.uqshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.uqshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.uqshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.uqshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sqshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sqshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sqshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sqshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.aarch64.neon.uqshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.uqshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.uqshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.uqshl.v16i8(<16 x i8>, <16 x i8>)
declare <4 x i16> @llvm.aarch64.neon.srshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.srshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.srshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.srshl.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.aarch64.neon.urshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.urshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.urshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.urshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.srshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.srshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.srshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.srshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.aarch64.neon.urshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.urshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.urshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.urshl.v16i8(<16 x i8>, <16 x i8>)
declare <4 x i16> @llvm.aarch64.neon.sshl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.sshl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.sshl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.sshl.v8i8(<8 x i8>, <8 x i8>)
declare <4 x i16> @llvm.aarch64.neon.ushl.v4i16(<4 x i16>, <4 x i16>)
declare <2 x i32> @llvm.aarch64.neon.ushl.v2i32(<2 x i32>, <2 x i32>)
declare <1 x i64> @llvm.aarch64.neon.ushl.v1i64(<1 x i64>, <1 x i64>)
declare <8 x i8> @llvm.aarch64.neon.ushl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64>, <2 x i64>)
declare <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8>, <16 x i8>)
