; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vshlq_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8> %0, <16 x i8> zeroinitializer)
  store <16 x i8> %vshlq_v.i, ptr %des, align 1
  ret void
}

define void @vshl_s8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsra.vi v8, v8, 1
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sshl.v8i8(<8 x i8> %0, <8 x i8> <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>)
  store <8 x i8> %vshl_v.i, ptr %des, align 1
  ret void
}

define void @vshlq_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16> %0, <8 x i16> <i16 127, i16 127, i16 127, i16 127, i16 127, i16 127, i16 127, i16 127>)
  store <8 x i16> %vshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vshl_s16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sshl.v4i16(<4 x i16> %0, <4 x i16> zeroinitializer)
  store <4 x i16> %vshl_v2.i, ptr %des, align 2
  ret void
}

define void @vshlq_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32> %0, <4 x i32> <i32 127, i32 127, i32 127, i32 127>)
  store <4 x i32> %vshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vshl_s32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsra.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sshl.v2i32(<2 x i32> %0, <2 x i32> <i32 -32, i32 -32>)
  store <2 x i32> %vshl_v2.i, ptr %des, align 4
  ret void
}

define void @vshlq_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64> %0, <2 x i64> <i64 64, i64 64>)
  store <2 x i64> %vshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vshl_s64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sshl.v1i64(<1 x i64> %0, <1 x i64> <i64 -64>)
  store <1 x i64> %vshl_v2.i, ptr %des, align 8
  ret void
}

define void @vshlq_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %src, align 1
  %vshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8> %0, <16 x i8> <i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128, i8 -128>)
  store <16 x i8> %vshlq_v.i, ptr %des, align 1
  ret void
}

define void @vshl_u8(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %src, align 1
  %vshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.ushl.v8i8(<8 x i8> %0, <8 x i8> <i8 9, i8 9, i8 9, i8 9, i8 9, i8 9, i8 9, i8 9>)
  store <8 x i8> %vshl_v.i, ptr %des, align 1
  ret void
}

define void @vshlq_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %src, align 2
  %vshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16> %0, <8 x i16> <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>)
  store <8 x i16> %vshlq_v2.i, ptr %des, align 2
  ret void
}

define void @vshl_u16(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 1
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %src, align 2
  %vshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.ushl.v4i16(<4 x i16> %0, <4 x i16> <i16 -1, i16 -1, i16 -1, i16 -1>)
  store <4 x i16> %vshl_v2.i, ptr %des, align 2
  ret void
}

define void @vshlq_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %src, align 4
  %vshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32> %0, <4 x i32> <i32 -32, i32 -32, i32 -32, i32 -32>)
  store <4 x i32> %vshlq_v2.i, ptr %des, align 4
  ret void
}

define void @vshl_u32(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsrl.vi v8, v8, 31
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %src, align 4
  %vshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.ushl.v2i32(<2 x i32> %0, <2 x i32> <i32 -31, i32 -31>)
  store <2 x i32> %vshl_v2.i, ptr %des, align 4
  ret void
}

define void @vshlq_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %src, align 8
  %vshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64> %0, <2 x i64> <i64 -128, i64 -128>)
  store <2 x i64> %vshlq_v2.i, ptr %des, align 8
  ret void
}

define void @vshl_u64(ptr nocapture noundef readonly %src, ptr nocapture noundef writeonly %des) {
; CHECK-LABEL: vshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    li a0, 63
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %src, align 8
  %vshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.ushl.v1i64(<1 x i64> %0, <1 x i64> <i64 -63>)
  store <1 x i64> %vshl_v2.i, ptr %des, align 8
  ret void
}

declare <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.sshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.sshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.sshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.sshl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.ushl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16>, <8 x i16>)
declare <4 x i16> @llvm.aarch64.neon.ushl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32>, <4 x i32>)
declare <2 x i32> @llvm.aarch64.neon.ushl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64>, <2 x i64>)
declare <1 x i64> @llvm.aarch64.neon.ushl.v1i64(<1 x i64>, <1 x i64>)
