; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vshl_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vi v0, v10, 15
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.sshl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vshl_v2.i, ptr %out, align 2
  ret void
}

define void @vshl_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.sshl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vshl_v2.i, ptr %out, align 4
  ret void
}

define void @vshl_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.sshl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vshl_v2.i, ptr %out, align 8
  ret void
}

define void @vshl_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    vrsub.vi v11, v10, 0
; CHECK-NEXT:    vmsle.vi v8, v10, -1
; CHECK-NEXT:    vmsgtu.vi v0, v10, 7
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse8.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.sshl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vshl_v.i, ptr %out, align 1
  ret void
}

define void @vshl_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    vsrl.vi v11, v9, 1
; CHECK-NEXT:    vmsgtu.vi v0, v10, 15
; CHECK-NEXT:    vsll.vv v9, v9, v10
; CHECK-NEXT:    vxor.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsrl.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i16>, ptr %in_0, align 2
  %1 = load <4 x i16>, ptr %in_1, align 2
  %vshl_v2.i = tail call <4 x i16> @llvm.aarch64.neon.ushl.v4i16(<4 x i16> %0, <4 x i16> %1)
  store <4 x i16> %vshl_v2.i, ptr %out, align 2
  ret void
}

define void @vshl_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vsrl.vi v11, v9, 1
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v9, v9, v10
; CHECK-NEXT:    vxor.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsrl.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i32>, ptr %in_0, align 4
  %1 = load <2 x i32>, ptr %in_1, align 4
  %vshl_v2.i = tail call <2 x i32> @llvm.aarch64.neon.ushl.v2i32(<2 x i32> %0, <2 x i32> %1)
  store <2 x i32> %vshl_v2.i, ptr %out, align 4
  ret void
}

define void @vshl_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vsrl.vi v11, v9, 1
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v9, v9, v10
; CHECK-NEXT:    vxor.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsrl.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <1 x i64>, ptr %in_0, align 8
  %1 = load <1 x i64>, ptr %in_1, align 8
  %vshl_v2.i = tail call <1 x i64> @llvm.aarch64.neon.ushl.v1i64(<1 x i64> %0, <1 x i64> %1)
  store <1 x i64> %vshl_v2.i, ptr %out, align 8
  ret void
}

define void @vshl_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshl_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, -8
; CHECK-NEXT:    vmsle.vi v8, v10, -1
; CHECK-NEXT:    vmsgtu.vi v0, v10, 7
; CHECK-NEXT:    vsll.vv v11, v9, v10
; CHECK-NEXT:    vsrl.vi v9, v9, 1
; CHECK-NEXT:    vmaxu.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vnot.v v10, v10
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vsrl.vv v11, v9, v10, v0.t
; CHECK-NEXT:    vse8.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <8 x i8>, ptr %in_1, align 1
  %vshl_v.i = tail call <8 x i8> @llvm.aarch64.neon.ushl.v8i8(<8 x i8> %0, <8 x i8> %1)
  store <8 x i8> %vshl_v.i, ptr %out, align 1
  ret void
}

define void @vshlq_s16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vi v0, v10, 15
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vshlq_s32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vshlq_s64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 256
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    li a0, 127
; CHECK-NEXT:    vrsub.vx v11, v10, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vmsgtu.vx v8, v10, a0
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vshlq_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, 7
; CHECK-NEXT:    vrsub.vi v11, v10, 0
; CHECK-NEXT:    vmsle.vi v8, v10, -1
; CHECK-NEXT:    vmsgtu.vi v0, v10, 7
; CHECK-NEXT:    vsll.vv v10, v9, v10
; CHECK-NEXT:    vmerge.vim v10, v10, 0, v0
; CHECK-NEXT:    vminu.vx v11, v11, a0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsra.vv v10, v9, v11, v0.t
; CHECK-NEXT:    vse8.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vshlq_v.i, ptr %out, align 1
  ret void
}

define void @vshlq_u16(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, mu
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 15
; CHECK-NEXT:    vsrl.vi v11, v9, 1
; CHECK-NEXT:    vmsgtu.vi v0, v10, 15
; CHECK-NEXT:    vsll.vv v9, v9, v10
; CHECK-NEXT:    vxor.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsrl.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vse16.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i16>, ptr %in_0, align 2
  %1 = load <8 x i16>, ptr %in_1, align 2
  %vshlq_v2.i = tail call <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16> %0, <8 x i16> %1)
  store <8 x i16> %vshlq_v2.i, ptr %out, align 2
  ret void
}

define void @vshlq_u32(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, mu
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vsrl.vi v11, v9, 1
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v9, v9, v10
; CHECK-NEXT:    vxor.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsrl.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vse32.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <4 x i32>, ptr %in_0, align 4
  %1 = load <4 x i32>, ptr %in_1, align 4
  %vshlq_v2.i = tail call <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32> %0, <4 x i32> %1)
  store <4 x i32> %vshlq_v2.i, ptr %out, align 4
  ret void
}

define void @vshlq_u64(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vle64.v v9, (a0)
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    li a1, 127
; CHECK-NEXT:    vand.vx v10, v8, a0
; CHECK-NEXT:    vmsgtu.vx v8, v10, a1
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vsrl.vi v11, v9, 1
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsll.vv v9, v9, v10
; CHECK-NEXT:    vxor.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v9, v9, 0, v0
; CHECK-NEXT:    vminu.vx v10, v10, a1
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsrl.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vse64.v v9, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <2 x i64>, ptr %in_0, align 8
  %1 = load <2 x i64>, ptr %in_1, align 8
  %vshlq_v2.i = tail call <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64> %0, <2 x i64> %1)
  store <2 x i64> %vshlq_v2.i, ptr %out, align 8
  ret void
}

define void @vshlq_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vshlq_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v9, (a0)
; CHECK-NEXT:    vle8.v v10, (a1)
; CHECK-NEXT:    li a0, -8
; CHECK-NEXT:    vmsle.vi v8, v10, -1
; CHECK-NEXT:    vmsgtu.vi v0, v10, 7
; CHECK-NEXT:    vsll.vv v11, v9, v10
; CHECK-NEXT:    vsrl.vi v9, v9, 1
; CHECK-NEXT:    vmaxu.vx v10, v10, a0
; CHECK-NEXT:    vmerge.vim v11, v11, 0, v0
; CHECK-NEXT:    vnot.v v10, v10
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    vsrl.vv v11, v9, v10, v0.t
; CHECK-NEXT:    vse8.v v11, (a2)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %vshlq_v.i = tail call <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8> %0, <16 x i8> %1)
  store <16 x i8> %vshlq_v.i, ptr %out, align 1
  ret void
}

declare <1 x i64> @llvm.aarch64.neon.sshl.v1i64(<1 x i64>, <1 x i64>)
declare <1 x i64> @llvm.aarch64.neon.ushl.v1i64(<1 x i64>, <1 x i64>)
declare <16 x i8> @llvm.aarch64.neon.sshl.v16i8(<16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.ushl.v16i8(<16 x i8>, <16 x i8>)
declare <2 x i32> @llvm.aarch64.neon.sshl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i32> @llvm.aarch64.neon.ushl.v2i32(<2 x i32>, <2 x i32>)
declare <2 x i64> @llvm.aarch64.neon.sshl.v2i64(<2 x i64>, <2 x i64>)
declare <2 x i64> @llvm.aarch64.neon.ushl.v2i64(<2 x i64>, <2 x i64>)
declare <4 x i16> @llvm.aarch64.neon.sshl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i16> @llvm.aarch64.neon.ushl.v4i16(<4 x i16>, <4 x i16>)
declare <4 x i32> @llvm.aarch64.neon.sshl.v4i32(<4 x i32>, <4 x i32>)
declare <4 x i32> @llvm.aarch64.neon.ushl.v4i32(<4 x i32>, <4 x i32>)
declare <8 x i16> @llvm.aarch64.neon.sshl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.ushl.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i8> @llvm.aarch64.neon.sshl.v8i8(<8 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.ushl.v8i8(<8 x i8>, <8 x i8>)
