; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -mtriple=riscv64 -mattr=+v -passes=sifive-recode,instcombine -S | llc -mtriple=riscv64 -mattr=+v,+zfh,+zvfh -verify-machineinstrs | FileCheck %s

define void @vqtbx1_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx1_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vv v10, v9, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vse8.v v10, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vtbx1.i = tail call <8 x i8> @llvm.aarch64.neon.tbx1.v8i8(<8 x i8> %0, <16 x i8> %1, <8 x i8> %2)
  store <8 x i8> %vtbx1.i, ptr %out, align 1
  ret void
}

define void @vqtbx1_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx1_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vv v10, v9, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vse8.v v10, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <8 x i8>, ptr %in_2, align 1
  %vtbx1.i = tail call <8 x i8> @llvm.aarch64.neon.tbx1.v8i8(<8 x i8> %0, <16 x i8> %1, <8 x i8> %2)
  store <8 x i8> %vtbx1.i, ptr %out, align 1
  ret void
}

define void @vqtbx1q_s8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx1q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vrgather.vv v10, v9, v8
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vse8.v v10, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <16 x i8>, ptr %in_2, align 1
  %vtbx1.i = tail call <16 x i8> @llvm.aarch64.neon.tbx1.v16i8(<16 x i8> %0, <16 x i8> %1, <16 x i8> %2)
  store <16 x i8> %vtbx1.i, ptr %out, align 1
  ret void
}

define void @vqtbx1q_u8(ptr nocapture noundef readonly %in_0, ptr nocapture noundef readonly %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx1q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vrgather.vv v10, v9, v8
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vse8.v v10, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %1 = load <16 x i8>, ptr %in_1, align 1
  %2 = load <16 x i8>, ptr %in_2, align 1
  %vtbx1.i = tail call <16 x i8> @llvm.aarch64.neon.tbx1.v16i8(<16 x i8> %0, <16 x i8> %1, <16 x i8> %2)
  store <16 x i8> %vtbx1.i, ptr %out, align 1
  ret void
}

define void @vqtbx2_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx2_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 32
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vv v12, v8, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v12, (a0), v0.t
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx2.i = tail call <8 x i8> @llvm.aarch64.neon.tbx2.v8i8(<8 x i8> %0, <16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, <8 x i8> %1)
  store <8 x i8> %vtbx2.i, ptr %out, align 1
  ret void
}

define void @vqtbx2_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx2_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 32
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vv v12, v8, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v12, (a0), v0.t
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx2.i = tail call <8 x i8> @llvm.aarch64.neon.tbx2.v8i8(<8 x i8> %0, <16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, <8 x i8> %1)
  store <8 x i8> %vtbx2.i, ptr %out, align 1
  ret void
}

define void @vqtbx2q_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx2q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 32
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vv v12, v8, v10
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v12, (a0), v0.t
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  %1 = load <16 x i8>, ptr %in_2, align 1
  %vtbx2.i = tail call <16 x i8> @llvm.aarch64.neon.tbx2.v16i8(<16 x i8> %0, <16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, <16 x i8> %1)
  store <16 x i8> %vtbx2.i, ptr %out, align 1
  ret void
}

define void @vqtbx2q_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx2q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 32
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vv v12, v8, v10
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v12, (a0), v0.t
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vld2 = tail call { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <16 x i8>, <16 x i8> } %vld2, 1
  %1 = load <16 x i8>, ptr %in_2, align 1
  %vtbx2.i = tail call <16 x i8> @llvm.aarch64.neon.tbx2.v16i8(<16 x i8> %0, <16 x i8> %vld2.fca.0.extract, <16 x i8> %vld2.fca.1.extract, <16 x i8> %1)
  store <16 x i8> %vtbx2.i, ptr %out, align 1
  ret void
}

define void @vqtbx3_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx3_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 48
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 47
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx3.i = tail call <8 x i8> @llvm.aarch64.neon.tbx3.v8i8(<8 x i8> %0, <16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, <8 x i8> %1)
  store <8 x i8> %vtbx3.i, ptr %out, align 1
  ret void
}

define void @vqtbx3_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx3_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 48
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 47
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx3.i = tail call <8 x i8> @llvm.aarch64.neon.tbx3.v8i8(<8 x i8> %0, <16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, <8 x i8> %1)
  store <8 x i8> %vtbx3.i, ptr %out, align 1
  ret void
}

define void @vqtbx3q_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx3q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 48
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 47
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 16, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  %1 = load <16 x i8>, ptr %in_2, align 1
  %vtbx3.i = tail call <16 x i8> @llvm.aarch64.neon.tbx3.v16i8(<16 x i8> %0, <16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, <16 x i8> %1)
  store <16 x i8> %vtbx3.i, ptr %out, align 1
  ret void
}

define void @vqtbx3q_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx3q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 48
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 47
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 16, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vld3 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr %in_1)
  %vld3.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 0
  %vld3.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 1
  %vld3.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %vld3, 2
  %1 = load <16 x i8>, ptr %in_2, align 1
  %vtbx3.i = tail call <16 x i8> @llvm.aarch64.neon.tbx3.v16i8(<16 x i8> %0, <16 x i8> %vld3.fca.0.extract, <16 x i8> %vld3.fca.1.extract, <16 x i8> %vld3.fca.2.extract, <16 x i8> %1)
  store <16 x i8> %vtbx3.i, ptr %out, align 1
  ret void
}

define void @vqtbx4_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx4_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx4.i = tail call <8 x i8> @llvm.aarch64.neon.tbx4.v8i8(<8 x i8> %0, <16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, <8 x i8> %1)
  store <8 x i8> %vtbx4.i, ptr %out, align 1
  ret void
}

define void @vqtbx4_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx4_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx4.i = tail call <8 x i8> @llvm.aarch64.neon.tbx4.v8i8(<8 x i8> %0, <16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, <8 x i8> %1)
  store <8 x i8> %vtbx4.i, ptr %out, align 1
  ret void
}

define void @vqtbx4q_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx4q_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 16, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  %1 = load <16 x i8>, ptr %in_2, align 1
  %vtbx4.i = tail call <16 x i8> @llvm.aarch64.neon.tbx4.v16i8(<16 x i8> %0, <16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, <16 x i8> %1)
  store <16 x i8> %vtbx4.i, ptr %out, align 1
  ret void
}

define void @vqtbx4q_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vqtbx4q_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 64
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a4, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v12, (a1)
; CHECK-NEXT:    li a1, 63
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vmsgtu.vx v0, v8, a1
; CHECK-NEXT:    vsetivli zero, 16, e8, m4, ta, ma
; CHECK-NEXT:    vrgather.vv v16, v12, v8
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, mu
; CHECK-NEXT:    vle8.v v16, (a0), v0.t
; CHECK-NEXT:    vse8.v v16, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <16 x i8>, ptr %in_0, align 1
  %vld4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %vld4, 3
  %1 = load <16 x i8>, ptr %in_2, align 1
  %vtbx4.i = tail call <16 x i8> @llvm.aarch64.neon.tbx4.v16i8(<16 x i8> %0, <16 x i8> %vld4.fca.0.extract, <16 x i8> %vld4.fca.1.extract, <16 x i8> %vld4.fca.2.extract, <16 x i8> %vld4.fca.3.extract, <16 x i8> %1)
  store <16 x i8> %vtbx4.i, ptr %out, align 1
  ret void
}

define void @vtbx2_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vtbx2_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vv v10, v9, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vse8.v v10, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx1.i = shufflevector <8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vtbx13.i = tail call <8 x i8> @llvm.aarch64.neon.tbx1.v8i8(<8 x i8> %0, <16 x i8> %vtbx1.i, <8 x i8> %1)
  store <8 x i8> %vtbx13.i, ptr %out, align 1
  ret void
}

define void @vtbx2_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vtbx2_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 15
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vrgather.vv v10, v9, v8
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v10, (a0), v0.t
; CHECK-NEXT:    vse8.v v10, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld2 = tail call { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr %in_1)
  %vld2.fca.0.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 0
  %vld2.fca.1.extract = extractvalue { <8 x i8>, <8 x i8> } %vld2, 1
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx1.i = shufflevector <8 x i8> %vld2.fca.0.extract, <8 x i8> %vld2.fca.1.extract, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vtbx13.i = tail call <8 x i8> @llvm.aarch64.neon.tbx1.v8i8(<8 x i8> %0, <16 x i8> %vtbx1.i, <8 x i8> %1)
  store <8 x i8> %vtbx13.i, ptr %out, align 1
  ret void
}

define void @vtbx4_s8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vtbx4_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 32
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vv v12, v8, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v12, (a0), v0.t
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx2.i = shufflevector <8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vtbx27.i = shufflevector <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vtbx28.i = tail call <8 x i8> @llvm.aarch64.neon.tbx2.v8i8(<8 x i8> %0, <16 x i8> %vtbx2.i, <16 x i8> %vtbx27.i, <8 x i8> %1)
  store <8 x i8> %vtbx28.i, ptr %out, align 1
  ret void
}

define void @vtbx4_u8(ptr nocapture noundef readonly %in_0, ptr noundef %in_1, ptr nocapture noundef readonly %in_2, ptr nocapture noundef writeonly %out) {
; CHECK-LABEL: vtbx4_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a4, 32
; CHECK-NEXT:    vsetvli zero, a4, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v10, (a2)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    vmsgtu.vx v0, v10, a1
; CHECK-NEXT:    vsetivli zero, 8, e8, m2, ta, ma
; CHECK-NEXT:    vrgather.vv v12, v8, v10
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, mu
; CHECK-NEXT:    vle8.v v12, (a0), v0.t
; CHECK-NEXT:    vse8.v v12, (a3)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i8>, ptr %in_0, align 1
  %vld4 = tail call { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr %in_1)
  %vld4.fca.0.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 0
  %vld4.fca.1.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 1
  %vld4.fca.2.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 2
  %vld4.fca.3.extract = extractvalue { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } %vld4, 3
  %1 = load <8 x i8>, ptr %in_2, align 1
  %vtbx2.i = shufflevector <8 x i8> %vld4.fca.0.extract, <8 x i8> %vld4.fca.1.extract, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vtbx27.i = shufflevector <8 x i8> %vld4.fca.2.extract, <8 x i8> %vld4.fca.3.extract, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vtbx28.i = tail call <8 x i8> @llvm.aarch64.neon.tbx2.v8i8(<8 x i8> %0, <16 x i8> %vtbx2.i, <16 x i8> %vtbx27.i, <8 x i8> %1)
  store <8 x i8> %vtbx28.i, ptr %out, align 1
  ret void
}

declare <16 x i8> @llvm.aarch64.neon.tbx1.v16i8(<16 x i8>, <16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.tbx2.v16i8(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.tbx3.v16i8(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.aarch64.neon.tbx4.v16i8(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>)
declare <8 x i8> @llvm.aarch64.neon.tbx1.v8i8(<8 x i8>, <16 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.tbx2.v8i8(<8 x i8>, <16 x i8>, <16 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.tbx3.v8i8(<8 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i8>)
declare <8 x i8> @llvm.aarch64.neon.tbx4.v8i8(<8 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i8>)
declare { <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x2.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x3.v16i8.p0(ptr)
declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.aarch64.neon.ld1x4.v16i8.p0(ptr)
declare { <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x2.v8i8.p0(ptr)
declare { <8 x i8>, <8 x i8>, <8 x i8>, <8 x i8> } @llvm.aarch64.neon.ld1x4.v8i8.p0(ptr)
