// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +experimental-zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vc_v_x_se_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.sf.vc.v.x.se.nxv1i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_sf_vc_v_x_se_u8mf8(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8mf8(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.sf.vc.v.x.se.nxv2i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_sf_vc_v_x_se_u8mf4(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8mf4(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.sf.vc.v.x.se.nxv4i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_sf_vc_v_x_se_u8mf2(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8mf2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.sf.vc.v.x.se.nxv8i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_sf_vc_v_x_se_u8m1(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8m1(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.sf.vc.v.x.se.nxv16i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_sf_vc_v_x_se_u8m2(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8m2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.sf.vc.v.x.se.nxv32i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_sf_vc_v_x_se_u8m4(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8m4(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.sf.vc.v.x.se.nxv64i8.i8.i64(i32 0, i32 0, i8 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_sf_vc_v_x_se_u8m8(int bit_field27_26, int bit_field24_20, uint8_t xs1, size_t vl) {
  return sf_vc_v_x_se_u8m8(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.sf.vc.v.x.se.nxv1i16.i16.i64(i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_sf_vc_v_x_se_u16mf4(int bit_field27_26, int bit_field24_20, uint16_t xs1, size_t vl) {
  return sf_vc_v_x_se_u16mf4(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.sf.vc.v.x.se.nxv2i16.i16.i64(i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_sf_vc_v_x_se_u16mf2(int bit_field27_26, int bit_field24_20, uint16_t xs1, size_t vl) {
  return sf_vc_v_x_se_u16mf2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.sf.vc.v.x.se.nxv4i16.i16.i64(i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_sf_vc_v_x_se_u16m1(int bit_field27_26, int bit_field24_20, uint16_t xs1, size_t vl) {
  return sf_vc_v_x_se_u16m1(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.sf.vc.v.x.se.nxv8i16.i16.i64(i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_sf_vc_v_x_se_u16m2(int bit_field27_26, int bit_field24_20, uint16_t xs1, size_t vl) {
  return sf_vc_v_x_se_u16m2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.sf.vc.v.x.se.nxv16i16.i16.i64(i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_sf_vc_v_x_se_u16m4(int bit_field27_26, int bit_field24_20, uint16_t xs1, size_t vl) {
  return sf_vc_v_x_se_u16m4(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.sf.vc.v.x.se.nxv32i16.i16.i64(i32 0, i32 0, i16 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_sf_vc_v_x_se_u16m8(int bit_field27_26, int bit_field24_20, uint16_t xs1, size_t vl) {
  return sf_vc_v_x_se_u16m8(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.sf.vc.v.x.se.nxv1i32.i32.i64(i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_sf_vc_v_x_se_u32mf2(int bit_field27_26, int bit_field24_20, uint32_t xs1, size_t vl) {
  return sf_vc_v_x_se_u32mf2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.sf.vc.v.x.se.nxv2i32.i32.i64(i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_sf_vc_v_x_se_u32m1(int bit_field27_26, int bit_field24_20, uint32_t xs1, size_t vl) {
  return sf_vc_v_x_se_u32m1(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.sf.vc.v.x.se.nxv4i32.i32.i64(i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_sf_vc_v_x_se_u32m2(int bit_field27_26, int bit_field24_20, uint32_t xs1, size_t vl) {
  return sf_vc_v_x_se_u32m2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.sf.vc.v.x.se.nxv8i32.i32.i64(i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_sf_vc_v_x_se_u32m4(int bit_field27_26, int bit_field24_20, uint32_t xs1, size_t vl) {
  return sf_vc_v_x_se_u32m4(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.sf.vc.v.x.se.nxv16i32.i32.i64(i32 0, i32 0, i32 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_sf_vc_v_x_se_u32m8(int bit_field27_26, int bit_field24_20, uint32_t xs1, size_t vl) {
  return sf_vc_v_x_se_u32m8(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.sf.vc.v.x.se.nxv1i64.i64.i64(i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_sf_vc_v_x_se_u64m1(int bit_field27_26, int bit_field24_20, uint64_t xs1, size_t vl) {
  return sf_vc_v_x_se_u64m1(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.sf.vc.v.x.se.nxv2i64.i64.i64(i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_sf_vc_v_x_se_u64m2(int bit_field27_26, int bit_field24_20, uint64_t xs1, size_t vl) {
  return sf_vc_v_x_se_u64m2(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.sf.vc.v.x.se.nxv4i64.i64.i64(i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_sf_vc_v_x_se_u64m4(int bit_field27_26, int bit_field24_20, uint64_t xs1, size_t vl) {
  return sf_vc_v_x_se_u64m4(0, 0, xs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_x_se_u64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.sf.vc.v.x.se.nxv8i64.i64.i64(i32 0, i32 0, i64 [[XS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_sf_vc_v_x_se_u64m8(int bit_field27_26, int bit_field24_20, uint64_t xs1, size_t vl) {
  return sf_vc_v_x_se_u64m8(0, 0, xs1, vl);
}

