// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f \
// RUN:  -target-feature +d -target-feature +v \
// RUN:  -target-feature +zfh -target-feature +xsfvcp -target-feature +experimental-zvfh \
// RUN:  -target-feature +xsfvqmaccqoq -target-feature +xsfvqmaccdod \
// RUN:  -target-feature +xsfvfnrclipxfqf -target-feature +xsfvfhbfmin \
// RUN:  -target-feature +xsfvfwmaccqqq -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:  opt -S -passes=mem2reg | FileCheck %s

#include <riscv_vector.h>

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv1i8.nxv1i8.i64(i32 0, <vscale x 1 x i8> [[VD:%.*]], <vscale x 1 x i8> [[VS2:%.*]], <vscale x 1 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_sf_vc_v_vvv_se_u8mf8(int bit_field27_26, vuint8mf8_t vd, vuint8mf8_t vs2, vuint8mf8_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8mf8(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv2i8.nxv2i8.i64(i32 0, <vscale x 2 x i8> [[VD:%.*]], <vscale x 2 x i8> [[VS2:%.*]], <vscale x 2 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_sf_vc_v_vvv_se_u8mf4(int bit_field27_26, vuint8mf4_t vd, vuint8mf4_t vs2, vuint8mf4_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8mf4(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv4i8.nxv4i8.i64(i32 0, <vscale x 4 x i8> [[VD:%.*]], <vscale x 4 x i8> [[VS2:%.*]], <vscale x 4 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_sf_vc_v_vvv_se_u8mf2(int bit_field27_26, vuint8mf2_t vd, vuint8mf2_t vs2, vuint8mf2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8mf2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv8i8.nxv8i8.i64(i32 0, <vscale x 8 x i8> [[VD:%.*]], <vscale x 8 x i8> [[VS2:%.*]], <vscale x 8 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_sf_vc_v_vvv_se_u8m1(int bit_field27_26, vuint8m1_t vd, vuint8m1_t vs2, vuint8m1_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8m1(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv16i8.nxv16i8.i64(i32 0, <vscale x 16 x i8> [[VD:%.*]], <vscale x 16 x i8> [[VS2:%.*]], <vscale x 16 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_sf_vc_v_vvv_se_u8m2(int bit_field27_26, vuint8m2_t vd, vuint8m2_t vs2, vuint8m2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8m2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv32i8.nxv32i8.i64(i32 0, <vscale x 32 x i8> [[VD:%.*]], <vscale x 32 x i8> [[VS2:%.*]], <vscale x 32 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_sf_vc_v_vvv_se_u8m4(int bit_field27_26, vuint8m4_t vd, vuint8m4_t vs2, vuint8m4_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8m4(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.sf.vc.v.vvv.se.nxv64i8.nxv64i8.i64(i32 0, <vscale x 64 x i8> [[VD:%.*]], <vscale x 64 x i8> [[VS2:%.*]], <vscale x 64 x i8> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_sf_vc_v_vvv_se_u8m8(int bit_field27_26, vuint8m8_t vd, vuint8m8_t vs2, vuint8m8_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u8m8(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.sf.vc.v.vvv.se.nxv1i16.nxv1i16.i64(i32 0, <vscale x 1 x i16> [[VD:%.*]], <vscale x 1 x i16> [[VS2:%.*]], <vscale x 1 x i16> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_sf_vc_v_vvv_se_u16mf4(int bit_field27_26, vuint16mf4_t vd, vuint16mf4_t vs2, vuint16mf4_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u16mf4(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.sf.vc.v.vvv.se.nxv2i16.nxv2i16.i64(i32 0, <vscale x 2 x i16> [[VD:%.*]], <vscale x 2 x i16> [[VS2:%.*]], <vscale x 2 x i16> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_sf_vc_v_vvv_se_u16mf2(int bit_field27_26, vuint16mf2_t vd, vuint16mf2_t vs2, vuint16mf2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u16mf2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.sf.vc.v.vvv.se.nxv4i16.nxv4i16.i64(i32 0, <vscale x 4 x i16> [[VD:%.*]], <vscale x 4 x i16> [[VS2:%.*]], <vscale x 4 x i16> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_sf_vc_v_vvv_se_u16m1(int bit_field27_26, vuint16m1_t vd, vuint16m1_t vs2, vuint16m1_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u16m1(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.sf.vc.v.vvv.se.nxv8i16.nxv8i16.i64(i32 0, <vscale x 8 x i16> [[VD:%.*]], <vscale x 8 x i16> [[VS2:%.*]], <vscale x 8 x i16> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_sf_vc_v_vvv_se_u16m2(int bit_field27_26, vuint16m2_t vd, vuint16m2_t vs2, vuint16m2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u16m2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.sf.vc.v.vvv.se.nxv16i16.nxv16i16.i64(i32 0, <vscale x 16 x i16> [[VD:%.*]], <vscale x 16 x i16> [[VS2:%.*]], <vscale x 16 x i16> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_sf_vc_v_vvv_se_u16m4(int bit_field27_26, vuint16m4_t vd, vuint16m4_t vs2, vuint16m4_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u16m4(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.sf.vc.v.vvv.se.nxv32i16.nxv32i16.i64(i32 0, <vscale x 32 x i16> [[VD:%.*]], <vscale x 32 x i16> [[VS2:%.*]], <vscale x 32 x i16> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_sf_vc_v_vvv_se_u16m8(int bit_field27_26, vuint16m8_t vd, vuint16m8_t vs2, vuint16m8_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u16m8(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.sf.vc.v.vvv.se.nxv1i32.nxv1i32.i64(i32 0, <vscale x 1 x i32> [[VD:%.*]], <vscale x 1 x i32> [[VS2:%.*]], <vscale x 1 x i32> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_sf_vc_v_vvv_se_u32mf2(int bit_field27_26, vuint32mf2_t vd, vuint32mf2_t vs2, vuint32mf2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u32mf2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.sf.vc.v.vvv.se.nxv2i32.nxv2i32.i64(i32 0, <vscale x 2 x i32> [[VD:%.*]], <vscale x 2 x i32> [[VS2:%.*]], <vscale x 2 x i32> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_sf_vc_v_vvv_se_u32m1(int bit_field27_26, vuint32m1_t vd, vuint32m1_t vs2, vuint32m1_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u32m1(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.sf.vc.v.vvv.se.nxv4i32.nxv4i32.i64(i32 0, <vscale x 4 x i32> [[VD:%.*]], <vscale x 4 x i32> [[VS2:%.*]], <vscale x 4 x i32> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_sf_vc_v_vvv_se_u32m2(int bit_field27_26, vuint32m2_t vd, vuint32m2_t vs2, vuint32m2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u32m2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.sf.vc.v.vvv.se.nxv8i32.nxv8i32.i64(i32 0, <vscale x 8 x i32> [[VD:%.*]], <vscale x 8 x i32> [[VS2:%.*]], <vscale x 8 x i32> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_sf_vc_v_vvv_se_u32m4(int bit_field27_26, vuint32m4_t vd, vuint32m4_t vs2, vuint32m4_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u32m4(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.sf.vc.v.vvv.se.nxv16i32.nxv16i32.i64(i32 0, <vscale x 16 x i32> [[VD:%.*]], <vscale x 16 x i32> [[VS2:%.*]], <vscale x 16 x i32> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_sf_vc_v_vvv_se_u32m8(int bit_field27_26, vuint32m8_t vd, vuint32m8_t vs2, vuint32m8_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u32m8(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.sf.vc.v.vvv.se.nxv1i64.nxv1i64.i64(i32 0, <vscale x 1 x i64> [[VD:%.*]], <vscale x 1 x i64> [[VS2:%.*]], <vscale x 1 x i64> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_sf_vc_v_vvv_se_u64m1(int bit_field27_26, vuint64m1_t vd, vuint64m1_t vs2, vuint64m1_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u64m1(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.sf.vc.v.vvv.se.nxv2i64.nxv2i64.i64(i32 0, <vscale x 2 x i64> [[VD:%.*]], <vscale x 2 x i64> [[VS2:%.*]], <vscale x 2 x i64> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_sf_vc_v_vvv_se_u64m2(int bit_field27_26, vuint64m2_t vd, vuint64m2_t vs2, vuint64m2_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u64m2(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.sf.vc.v.vvv.se.nxv4i64.nxv4i64.i64(i32 0, <vscale x 4 x i64> [[VD:%.*]], <vscale x 4 x i64> [[VS2:%.*]], <vscale x 4 x i64> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_sf_vc_v_vvv_se_u64m4(int bit_field27_26, vuint64m4_t vd, vuint64m4_t vs2, vuint64m4_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u64m4(0, vd, vs2, rs1, vl);
}

// CHECK-LABEL: @test_sf_vc_v_vvv_se_u64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.sf.vc.v.vvv.se.nxv8i64.nxv8i64.i64(i32 0, <vscale x 8 x i64> [[VD:%.*]], <vscale x 8 x i64> [[VS2:%.*]], <vscale x 8 x i64> [[RS1:%.*]], i64 [[VL:%.*]])
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_sf_vc_v_vvv_se_u64m8(int bit_field27_26, vuint64m8_t vd, vuint64m8_t vs2, vuint64m8_t rs1, size_t vl) {
  return sf_vc_v_vvv_se_u64m8(0, vd, vs2, rs1, vl);
}

