; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-idiom -S %s | FileCheck %s

; unsigned test1(unsigned val, unsigned tc, unsigned offset) {
;   unsigned bits = 0;
;   for (unsigned i = 0; i != tc; ++i)
;     bits += val & (1 << (i + offset));
;
;   return bits;
; }
define i32 @test1(i32 %val, i32 %tc, i32 %offset) {
; CHECK-LABEL: @test1(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT5:%.*]] = icmp eq i32 [[TC:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT5]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = shl i32 -1, [[TC]]
; CHECK-NEXT:    [[TMP1:%.*]] = xor i32 [[TMP0]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = shl i32 [[TMP1]], [[OFFSET:%.*]]
; CHECK-NEXT:    [[TMP3:%.*]] = and i32 [[VAL:%.*]], [[TMP2]]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    [[ADD1_LCSSA:%.*]] = phi i32 [ [[TMP3]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[BITS_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[ADD1_LCSSA]], [[FOR_COND_CLEANUP_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    ret i32 [[BITS_0_LCSSA]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_07:%.*]] = phi i32 [ [[INC:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[BITS_06:%.*]] = phi i32 [ [[ADD1:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[I_07]], [[OFFSET]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i32 1, [[ADD]]
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[SHL]], [[VAL]]
; CHECK-NEXT:    [[ADD1]] = add i32 [[AND]], [[BITS_06]]
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_07]], 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[INC]], [[TC]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]]
;
entry:
  %cmp.not5 = icmp eq i32 %tc, 0
  br i1 %cmp.not5, label %for.cond.cleanup, label %for.body.preheader

for.body.preheader:                               ; preds = %entry
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.cond.cleanup, %entry
  %bits.0.lcssa = phi i32 [ 0, %entry ], [ %add1, %for.body ]
  ret i32 %bits.0.lcssa

for.body:                                         ; preds = %for.body.preheader, %for.body
  %i.07 = phi i32 [ %inc, %for.body ], [ 0, %for.body.preheader ]
  %bits.06 = phi i32 [ %add1, %for.body ], [ 0, %for.body.preheader ]
  %add = add i32 %i.07, %offset
  %shl = shl nuw i32 1, %add
  %and = and i32 %shl, %val
  %add1 = add i32 %and, %bits.06
  %inc = add nuw nsw i32 %i.07, 1
  %cmp.not = icmp eq i32 %inc, %tc
  br i1 %cmp.not, label %for.cond.cleanup, label %for.body
}

; unsigned test2(uint64_t val, unsigned tc, unsigned offset) {
;   unsigned bits = 0;
;   for (unsigned i = 0; i != tc; ++i)
;     bits += val & (1ULL << (i + offset));
;
;   return bits;
; }
define i32 @test2(i64 %val, i32 %tc, i32 %offset) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT6:%.*]] = icmp eq i32 [[TC:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT6]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[TC]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 -1, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = xor i64 [[TMP1]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[OFFSET:%.*]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = shl i64 [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = and i64 [[VAL:%.*]], [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i64 [[TMP5]] to i32
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    [[CONV2_LCSSA:%.*]] = phi i32 [ [[TMP6]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[BITS_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[CONV2_LCSSA]], [[FOR_COND_CLEANUP_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    ret i32 [[BITS_0_LCSSA]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_08:%.*]] = phi i32 [ [[INC:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[BITS_07:%.*]] = phi i32 [ [[CONV2:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[I_08]], [[OFFSET]]
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext i32 [[ADD]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i64 1, [[SH_PROM]]
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[SHL]], [[VAL]]
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i64 [[AND]] to i32
; CHECK-NEXT:    [[CONV2]] = add i32 [[BITS_07]], [[TMP7]]
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_08]], 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[INC]], [[TC]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]]
;
entry:
  %cmp.not6 = icmp eq i32 %tc, 0
  br i1 %cmp.not6, label %for.cond.cleanup, label %for.body.preheader

for.body.preheader:                               ; preds = %entry
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.cond.cleanup, %entry
  %bits.0.lcssa = phi i32 [ 0, %entry ], [ %conv2, %for.body ]
  ret i32 %bits.0.lcssa

for.body:                                         ; preds = %for.body.preheader, %for.body
  %i.08 = phi i32 [ %inc, %for.body ], [ 0, %for.body.preheader ]
  %bits.07 = phi i32 [ %conv2, %for.body ], [ 0, %for.body.preheader ]
  %add = add i32 %i.08, %offset
  %sh_prom = zext i32 %add to i64
  %shl = shl nuw i64 1, %sh_prom
  %and = and i64 %shl, %val
  %0 = trunc i64 %and to i32
  %conv2 = add i32 %bits.07, %0
  %inc = add nuw nsw i32 %i.08, 1
  %cmp.not = icmp eq i32 %inc, %tc
  br i1 %cmp.not, label %for.cond.cleanup, label %for.body
}

; unsigned test2(uint64_t val, uint64_t tc, uint64_t offset) {
;   uint64_t bits = 0;
;   for (uint64_t i = 0; i != tc; ++i)
;     bits += val & (1ULL << (i + offset));
;
;   return bits;
; }
define i32 @test3(i64 %val, i64 %tc, i64 %offset) {
; CHECK-LABEL: @test3(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT7:%.*]] = icmp eq i64 [[TC:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT7]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_LR_PH:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = shl i64 -1, [[TC]]
; CHECK-NEXT:    [[TMP1:%.*]] = xor i64 [[TMP0]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[TMP1]], [[OFFSET:%.*]]
; CHECK-NEXT:    [[TMP3:%.*]] = and i64 [[VAL:%.*]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    [[CONV_LCSSA:%.*]] = phi i32 [ [[TMP4]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[BITS_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[CONV_LCSSA]], [[FOR_COND_CLEANUP_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    ret i32 [[BITS_0_LCSSA]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_09:%.*]] = phi i64 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[BITS_08:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[CONV:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[I_09]], [[OFFSET]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i64 1, [[ADD]]
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[SHL]], [[VAL]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[AND]] to i32
; CHECK-NEXT:    [[CONV]] = add i32 [[BITS_08]], [[TMP5]]
; CHECK-NEXT:    [[INC]] = add i64 [[I_09]], 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[INC]], [[TC]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]]
;
entry:
  %cmp.not7 = icmp eq i64 %tc, 0
  br i1 %cmp.not7, label %for.cond.cleanup, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %entry
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  %bits.0.lcssa = phi i32 [ 0, %entry ], [ %conv, %for.body ]
  ret i32 %bits.0.lcssa

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %i.09 = phi i64 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %bits.08 = phi i32 [ 0, %for.body.lr.ph ], [ %conv, %for.body ]
  %add = add i64 %i.09, %offset
  %shl = shl nuw i64 1, %add
  %and = and i64 %shl, %val
  %0 = trunc i64 %and to i32
  %conv = add i32 %bits.08, %0
  %inc = add i64 %i.09, 1
  %cmp.not = icmp eq i64 %inc, %tc
  br i1 %cmp.not, label %for.cond.cleanup, label %for.body
}

; Negative test. %val is smaller than %c and %offset. We should not optimize.
define i32 @test4(i32 %val, i64 %tc, i64 %offset) {
; CHECK-LABEL: @test4(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT7:%.*]] = icmp eq i64 [[TC:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT7]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    [[CONV3_LCSSA:%.*]] = phi i32 [ [[CONV3:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[BITS_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[CONV3_LCSSA]], [[FOR_COND_CLEANUP_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    ret i32 [[BITS_0_LCSSA]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_09:%.*]] = phi i64 [ [[INC:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[BITS_08:%.*]] = phi i32 [ [[CONV3]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ADD:%.*]] = add i64 [[I_09]], [[OFFSET:%.*]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i64 1, [[ADD]]
; CHECK-NEXT:    [[TMP0:%.*]] = trunc i64 [[SHL]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[TMP0]], [[VAL:%.*]]
; CHECK-NEXT:    [[CONV3]] = add i32 [[TMP1]], [[BITS_08]]
; CHECK-NEXT:    [[INC]] = add i64 [[I_09]], 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[INC]], [[TC]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]]
;
entry:
  %cmp.not7 = icmp eq i64 %tc, 0
  br i1 %cmp.not7, label %for.cond.cleanup, label %for.body.preheader

for.body.preheader:                               ; preds = %entry
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.body
  %conv3.lcssa = phi i32 [ %conv3, %for.body ]
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  %bits.0.lcssa = phi i32 [ 0, %entry ], [ %conv3.lcssa, %for.cond.cleanup.loopexit ]
  ret i32 %bits.0.lcssa

for.body:                                         ; preds = %for.body.preheader, %for.body
  %i.09 = phi i64 [ %inc, %for.body ], [ 0, %for.body.preheader ]
  %bits.08 = phi i32 [ %conv3, %for.body ], [ 0, %for.body.preheader ]
  %add = add i64 %i.09, %offset
  %shl = shl nuw i64 1, %add
  %0 = trunc i64 %shl to i32
  %1 = and i32 %0, %val
  %conv3 = add i32 %1, %bits.08
  %inc = add i64 %i.09, 1
  %cmp.not = icmp eq i64 %inc, %tc
  br i1 %cmp.not, label %for.cond.cleanup.loopexit, label %for.body
}
