; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -mattr=+v < %s -S | FileCheck %s --check-prefix=V
; RUN: opt -passes=loop-vectorize -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -mattr=+f,+zve32f < %s -S | FileCheck %s --check-prefix=ZVE32F

target triple = "riscv64"

define void @foo(i64* %x, i64 %n, i64 %y) {
; V-LABEL: @foo(
; V-NEXT:  entry:
; V-NEXT:    [[CMP_NOT5:%.*]] = icmp eq i64 [[N:%.*]], 0
; V-NEXT:    br i1 [[CMP_NOT5]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; V:       for.body.preheader:
; V-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; V:       vector.ph:
; V-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[N]], i32 1, i1 true)
; V-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[Y:%.*]], i64 0
; V-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
; V-NEXT:    br label [[VECTOR_BODY:%.*]]
; V:       vector.body:
; V-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; V-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; V-NEXT:    [[TMP0:%.*]] = sub i64 [[N]], [[EVL_BASED_IV]]
; V-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 1, i1 true)
; V-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[X:%.*]], i64 [[EVL_BASED_IV]]
; V-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[TMP3]], i32 0
; V-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 1 x i64> @llvm.vp.load.nxv1i64.p0(ptr align 8 [[TMP4]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP1]])
; V-NEXT:    [[VP_OP:%.*]] = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> [[VP_OP_LOAD]], <vscale x 1 x i64> [[BROADCAST_SPLAT]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP1]])
; V-NEXT:    call void @llvm.vp.store.nxv1i64.p0(<vscale x 1 x i64> [[VP_OP]], ptr align 8 [[TMP4]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP1]])
; V-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP1]] to i64
; V-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP5]], [[EVL_BASED_IV]]
; V-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[N]]
; V-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; V:       middle.block:
; V-NEXT:    br label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]]
; V:       scalar.ph:
; V-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ]
; V-NEXT:    br label [[FOR_BODY:%.*]]
; V:       for.cond.cleanup.loopexit:
; V-NEXT:    br label [[FOR_COND_CLEANUP]]
; V:       for.cond.cleanup:
; V-NEXT:    ret void
; V:       for.body:
; V-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; V-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[X]], i64 [[INDVARS_IV]]
; V-NEXT:    [[TMP7:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
; V-NEXT:    [[ADD:%.*]] = add nsw i64 [[TMP7]], [[Y]]
; V-NEXT:    store i64 [[ADD]], ptr [[ARRAYIDX]], align 8
; V-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; V-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[N]]
; V-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
;
; ZVE32F-LABEL: @foo(
; ZVE32F-NEXT:  entry:
; ZVE32F-NEXT:    [[CMP_NOT5:%.*]] = icmp eq i64 [[N:%.*]], 0
; ZVE32F-NEXT:    br i1 [[CMP_NOT5]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; ZVE32F:       for.body.preheader:
; ZVE32F-NEXT:    br label [[FOR_BODY:%.*]]
; ZVE32F:       for.cond.cleanup.loopexit:
; ZVE32F-NEXT:    br label [[FOR_COND_CLEANUP]]
; ZVE32F:       for.cond.cleanup:
; ZVE32F-NEXT:    ret void
; ZVE32F:       for.body:
; ZVE32F-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; ZVE32F-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[X:%.*]], i64 [[INDVARS_IV]]
; ZVE32F-NEXT:    [[TMP0:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
; ZVE32F-NEXT:    [[ADD:%.*]] = add nsw i64 [[TMP0]], [[Y:%.*]]
; ZVE32F-NEXT:    store i64 [[ADD]], ptr [[ARRAYIDX]], align 8
; ZVE32F-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; ZVE32F-NEXT:    [[CMP_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[N]]
; ZVE32F-NEXT:    br i1 [[CMP_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[FOR_BODY]]
;
entry:
  %cmp.not5 = icmp eq i64 %n, 0
  br i1 %cmp.not5, label %for.cond.cleanup, label %for.body.preheader

for.body.preheader:                               ; preds = %entry
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.body
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  ret void

for.body:                                         ; preds = %for.body.preheader, %for.body
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body ], [ 0, %for.body.preheader ]
  %arrayidx = getelementptr inbounds i64, i64* %x, i64 %indvars.iv
  %0 = load i64, i64* %arrayidx, align 8
  %add = add nsw i64 %0, %y
  store i64 %add, i64* %arrayidx, align 8
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %cmp.not = icmp eq i64 %indvars.iv.next, %n
  br i1 %cmp.not, label %for.cond.cleanup.loopexit, label %for.body
}
