; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=loop-vectorize -mtriple=riscv64 -riscv-use-vla-vectorizer -mattr=+v < %s | FileCheck %s

define void @test(ptr %Ptr, i8 %Val) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 253, i32 4, i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[VAL:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 253, [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[EVL_BASED_IV1]], 4
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = add i64 10, [[TMP2]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr [[PTR:%.*]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i8.p0.i64(<vscale x 4 x i8> [[BROADCAST_SPLAT]], ptr align 1 [[TMP3]], i64 4, <vscale x 4 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = or disjoint i64 [[OFFSET_IDX]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i8, ptr [[PTR]], i64 [[TMP4]]
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i8.p0.i64(<vscale x 4 x i8> [[BROADCAST_SPLAT]], ptr align 1 [[TMP5]], i64 4, <vscale x 4 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP6]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 253
; CHECK-NEXT:    br i1 [[TMP7]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 1022, [[MIDDLE_BLOCK]] ], [ 10, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[EDGE:%.*]]
; CHECK:       edge:
; CHECK-NEXT:    [[INDVAR:%.*]] = phi i64 [ [[INDVAR_NEXT1:%.*]], [[EDGE1:%.*]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[PTR]], i64 [[INDVAR]]
; CHECK-NEXT:    store i8 [[VAL]], ptr [[ARRAYIDX1]], align 1
; CHECK-NEXT:    [[INDVAR_NEXT:%.*]] = or disjoint i64 [[INDVAR]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[INDVAR_NEXT]], 1024
; CHECK-NEXT:    br i1 [[CMP]], label [[EDGE1]], label [[LOOPEXIT:%.*]]
; CHECK:       edge1:
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[PTR]], i64 [[INDVAR_NEXT]]
; CHECK-NEXT:    store i8 [[VAL]], ptr [[ARRAYIDX2]], align 1
; CHECK-NEXT:    [[INDVAR_NEXT1]] = add nuw nsw i64 [[INDVAR]], 4
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ult i64 [[INDVAR_NEXT1]], 1024
; CHECK-NEXT:    br i1 [[CMP1]], label [[EDGE]], label [[LOOPEXIT]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       loopexit:
; CHECK-NEXT:    ret void
;
entry:
  br label %edge

edge:
  %indvar = phi i64 [ %indvar.next1, %edge1 ], [ 10, %entry ]
  %arrayidx1 = getelementptr inbounds i8, ptr %Ptr, i64 %indvar
  store i8 %Val, ptr %arrayidx1, align 1
  %indvar.next = or disjoint i64 %indvar, 1
  %cmp = icmp ult i64 %indvar.next, 1024
  br i1 %cmp, label %edge1, label %loopexit

edge1:
  %arrayidx2 = getelementptr inbounds i8, ptr %Ptr, i64 %indvar.next
  store i8 %Val, ptr %arrayidx2, align 1
  %indvar.next1 = add nuw nsw i64 %indvar, 4
  %cmp1 = icmp ult i64 %indvar.next1, 1024
  br i1 %cmp1, label %edge, label %loopexit

loopexit:
  ret void
}
