; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -vector-primary-lmul-max=1 -scalable-vectorization=only -riscv-use-vla-vectorizer -prefer-predicate-over-epilogue=predicate-dont-vectorize -aa-pipeline=tbaa -passes=loop-vectorize | FileCheck %s

%struct.sv = type { ptr, i32, i32 }

define ptr @Perl_newSV(ptr %call.i) {
; CHECK-LABEL: @Perl_newSV(
; CHECK-NEXT:  if.else.i:
; CHECK-NEXT:    [[CALL_I1:%.*]] = call ptr @Perl_safesysmalloc()
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 24, i32 1, i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = call <vscale x 1 x i64> @llvm.stepvector.nxv1i64()
; CHECK-NEXT:    [[TMP3:%.*]] = mul <vscale x 1 x i64> [[TMP1]], splat (i64 11)
; CHECK-NEXT:    [[INDUCTION:%.*]] = add <vscale x 1 x i64> splat (i64 1), [[TMP3]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 1 x i64> [ [[INDUCTION]], [[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = sub i64 24, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP5]], i32 1, i1 true)
; CHECK-NEXT:    [[TMP4:%.*]] = zext i32 [[TMP6]] to i64
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 11, [[TMP4]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[TMP8]], i64 0
; CHECK-NEXT:    [[DOTSPLAT2:%.*]] = shufflevector <vscale x 1 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = mul i64 [[EVL_BASED_IV]], 11
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = add i64 1, [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = add nuw nsw i64 [[OFFSET_IDX]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds [[STRUCT_SV:%.*]], ptr [[CALL_I:%.*]], i64 [[TMP9]], i32 1
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv1i32.p0.i64(<vscale x 1 x i32> zeroinitializer, ptr align 8 [[TMP10]], i64 176, <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]]), !tbaa [[TBAA0:![0-9]+]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[TMP9]], i32 2
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv1i32.p0.i64(<vscale x 1 x i32> zeroinitializer, ptr align 4 [[TMP11]], i64 176, <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]]), !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[TMP12:%.*]] = add nuw nsw i64 [[OFFSET_IDX]], 6
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[TMP12]], i32 1
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv1i32.p0.i64(<vscale x 1 x i32> zeroinitializer, ptr align 8 [[TMP13]], i64 176, <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]]), !tbaa [[TBAA0]]
; CHECK-NEXT:    [[TMP14:%.*]] = add nuw nsw i64 [[OFFSET_IDX]], 10
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[TMP14]]
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> [[VEC_IND]], <vscale x 1 x i64> splat (i64 11), <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], <vscale x 1 x i64> [[VP_OP]]
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv1p0.p0.i64(<vscale x 1 x ptr> [[TMP16]], ptr align 8 [[TMP15]], i64 176, <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]]), !tbaa [[TBAA7:![0-9]+]]
; CHECK-NEXT:    [[TMP17:%.*]] = zext i32 [[TMP6]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP17]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[VEC_IND_NEXT]] = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> [[VEC_IND]], <vscale x 1 x i64> [[DOTSPLAT2]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-NEXT:    [[TMP20:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 24
; CHECK-NEXT:    br i1 [[TMP20]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP21:%.*]] = sub i32 [[TMP6]], 1
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <vscale x 1 x ptr> [[TMP16]], i32 [[TMP21]]
; CHECK-NEXT:    br label [[PERL_SV_ADD_ARENA_EXIT14_I:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 1, [[IF_ELSE_I:%.*]] ]
; CHECK-NEXT:    br label [[WHILE_BODY_I11_I:%.*]]
; CHECK:       while.body.i11.i:
; CHECK-NEXT:    [[SV_026_I6_IDX_I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[SV_026_I6_ADD_I_10:%.*]], [[WHILE_BODY_I11_I]] ]
; CHECK-NEXT:    [[SV_026_I6_ADD_I_3:%.*]] = add nuw nsw i64 [[SV_026_I6_IDX_I]], 1
; CHECK-NEXT:    [[SV_REFCNT7_I8_I_4:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[SV_026_I6_ADD_I_3]], i32 1
; CHECK-NEXT:    store i32 0, ptr [[SV_REFCNT7_I8_I_4]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[SV_FLAGS8_I9_I_4:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[SV_026_I6_ADD_I_3]], i32 2
; CHECK-NEXT:    store i32 0, ptr [[SV_FLAGS8_I9_I_4]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[SV_026_I6_ADD_I_5:%.*]] = add nuw nsw i64 [[SV_026_I6_IDX_I]], 6
; CHECK-NEXT:    [[SV_REFCNT7_I8_I_6:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[SV_026_I6_ADD_I_5]], i32 1
; CHECK-NEXT:    store i32 0, ptr [[SV_REFCNT7_I8_I_6]], align 8, !tbaa [[TBAA0]]
; CHECK-NEXT:    [[SV_026_I6_ADD_I_9:%.*]] = add nuw nsw i64 [[SV_026_I6_IDX_I]], 10
; CHECK-NEXT:    [[SV_026_I6_PTR_I_10:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[SV_026_I6_ADD_I_9]]
; CHECK-NEXT:    [[SV_026_I6_ADD_I_10]] = add nuw nsw i64 [[SV_026_I6_IDX_I]], 11
; CHECK-NEXT:    [[ADD_PTR5_I7_PTR_I_10:%.*]] = getelementptr inbounds [[STRUCT_SV]], ptr [[CALL_I]], i64 [[SV_026_I6_ADD_I_10]]
; CHECK-NEXT:    store ptr [[ADD_PTR5_I7_PTR_I_10]], ptr [[SV_026_I6_PTR_I_10]], align 8, !tbaa [[TBAA7]]
; CHECK-NEXT:    [[EXITCOND_NOT_I_10:%.*]] = icmp eq i64 [[SV_026_I6_IDX_I]], 254
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I_10]], label [[PERL_SV_ADD_ARENA_EXIT14_I]], label [[WHILE_BODY_I11_I]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       Perl_sv_add_arena.exit14.i:
; CHECK-NEXT:    [[ADD_PTR5_I7_PTR_I_10_LCSSA:%.*]] = phi ptr [ [[ADD_PTR5_I7_PTR_I_10]], [[WHILE_BODY_I11_I]] ], [ [[TMP22]], [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    store ptr null, ptr [[ADD_PTR5_I7_PTR_I_10_LCSSA]], align 8
; CHECK-NEXT:    ret ptr null
;

if.else.i:
  %call.i1 = call ptr @Perl_safesysmalloc()
  br label %while.body.i11.i

while.body.i11.i:                                 ; preds = %while.body.i11.i, %if.else.i
  %sv.026.i6.idx.i = phi i64 [ 1, %if.else.i ], [ %sv.026.i6.add.i.10, %while.body.i11.i ]
  %sv.026.i6.add.i.3 = add nuw nsw i64 %sv.026.i6.idx.i, 1
  %sv_refcnt7.i8.i.4 = getelementptr inbounds %struct.sv, ptr %call.i, i64 %sv.026.i6.add.i.3, i32 1
  store i32 0, ptr %sv_refcnt7.i8.i.4, align 8, !tbaa !0
  %sv_flags8.i9.i.4 = getelementptr inbounds %struct.sv, ptr %call.i, i64 %sv.026.i6.add.i.3, i32 2
  store i32 0, ptr %sv_flags8.i9.i.4, align 4, !tbaa !6
  %sv.026.i6.add.i.5 = add nuw nsw i64 %sv.026.i6.idx.i, 6
  %sv_refcnt7.i8.i.6 = getelementptr inbounds %struct.sv, ptr %call.i, i64 %sv.026.i6.add.i.5, i32 1
  store i32 0, ptr %sv_refcnt7.i8.i.6, align 8, !tbaa !0
  %sv.026.i6.add.i.9 = add nuw nsw i64 %sv.026.i6.idx.i, 10
  %sv.026.i6.ptr.i.10 = getelementptr inbounds %struct.sv, ptr %call.i, i64 %sv.026.i6.add.i.9
  %sv.026.i6.add.i.10 = add nuw nsw i64 %sv.026.i6.idx.i, 11
  %add.ptr5.i7.ptr.i.10 = getelementptr inbounds %struct.sv, ptr %call.i, i64 %sv.026.i6.add.i.10
  store ptr %add.ptr5.i7.ptr.i.10, ptr %sv.026.i6.ptr.i.10, align 8, !tbaa !7
  %exitcond.not.i.10 = icmp eq i64 %sv.026.i6.idx.i, 254
  br i1 %exitcond.not.i.10, label %Perl_sv_add_arena.exit14.i, label %while.body.i11.i

Perl_sv_add_arena.exit14.i:                       ; preds = %while.body.i11.i
  store ptr null, ptr %add.ptr5.i7.ptr.i.10, align 8
  ret ptr null
}

declare ptr @Perl_safesysmalloc()

!0 = !{!1, !5, i64 8}
!1 = !{!"sv", !2, i64 0, !5, i64 8, !5, i64 12}
!2 = !{!"any pointer", !3, i64 0}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C/C++ TBAA"}
!5 = !{!"int", !3, i64 0}
!6 = !{!1, !5, i64 12}
!7 = !{!1, !2, i64 0}
