; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -S -mtriple riscv64-unknown-linux-gnu -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -mattr=+v -vectorizer-use-vp-strided-load-store < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  while.body380.preheader:
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i32(i32 100, i32 4, i1 true)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i32 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = sub i32 100, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i32(i32 [[TMP0]], i32 4, i1 true)
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv4i8.nxv4p0(<vscale x 4 x i8> zeroinitializer, <vscale x 4 x ptr> align 1 zeroinitializer, <vscale x 4 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i32 [[TMP1]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[INDEX_EVL_NEXT]], 100
; CHECK-NEXT:    br i1 [[TMP2]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[FINISH_LOOPEXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ 0, [[WHILE_BODY380_PREHEADER:%.*]] ]
; CHECK-NEXT:    br label [[WHILE_BODY380:%.*]]
; CHECK:       while.body380:
; CHECK-NEXT:    [[LEN_4735:%.*]] = phi i32 [ [[DEC378:%.*]], [[WHILE_BODY380]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[DEC378]] = add nsw i32 [[LEN_4735]], 1
; CHECK-NEXT:    [[AND385681:%.*]] = and i8 0, 0
; CHECK-NEXT:    store i8 [[AND385681]], ptr null, align 1
; CHECK-NEXT:    [[TOBOOL379_NOT:%.*]] = icmp eq i32 [[DEC378]], 100
; CHECK-NEXT:    br i1 [[TOBOOL379_NOT]], label [[FINISH_LOOPEXIT]], label [[WHILE_BODY380]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       finish.loopexit:
; CHECK-NEXT:    ret void
;
while.body380.preheader:
  br label %while.body380

while.body380:
  %len.4735 = phi i32 [ %dec378, %while.body380 ], [ 0, %while.body380.preheader ]
  %dec378 = add nsw i32 %len.4735, 1
  %and385681 = and i8 0, 0
  store i8 %and385681, i8* null, align 1
  %tobool379.not = icmp eq i32 %dec378, 100
  br i1 %tobool379.not, label %finish.loopexit, label %while.body380

finish.loopexit:
  ret void
}
