; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -vector-primary-lmul-max=3 --mcpu=sifive-x280 -S < %s | FileCheck -check-prefix=PROFITABLE %s
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -vector-primary-lmul-max=3 --mcpu=sifive-p470 -S < %s | FileCheck -check-prefix=PROFITABLE %s
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -vector-primary-lmul-max=3 --mcpu=sifive-p670 -S < %s | FileCheck -check-prefix=NON-PROFITABLE %s

%struct.su3_vector = type { [3 x %struct.complex] }
%struct.complex = type { double, double }

; reduced from Spec2k6 FP 433.milc quark_stuff.c:993
define void @eo_fermion_force(ptr %a, ptr %b, double %s, i64 %n) {
; PROFITABLE-LABEL: define void @eo_fermion_force
; PROFITABLE-SAME: (ptr [[A:%.*]], ptr [[B:%.*]], double [[S:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; PROFITABLE-NEXT:  entry:
; PROFITABLE-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_SCEVCHECK:%.*]]
; PROFITABLE:       vector.scevcheck:
; PROFITABLE-NEXT:    [[TMP0:%.*]] = add i64 [[N]], -1
; PROFITABLE-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[A]], i64 40
; PROFITABLE-NEXT:    [[MUL:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 48, i64 [[TMP0]])
; PROFITABLE-NEXT:    [[MUL_RESULT:%.*]] = extractvalue { i64, i1 } [[MUL]], 0
; PROFITABLE-NEXT:    [[MUL_OVERFLOW:%.*]] = extractvalue { i64, i1 } [[MUL]], 1
; PROFITABLE-NEXT:    [[TMP1:%.*]] = sub i64 0, [[MUL_RESULT]]
; PROFITABLE-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[SCEVGEP]], i64 [[MUL_RESULT]]
; PROFITABLE-NEXT:    [[TMP3:%.*]] = icmp ult ptr [[TMP2]], [[SCEVGEP]]
; PROFITABLE-NEXT:    [[TMP4:%.*]] = or i1 [[TMP3]], [[MUL_OVERFLOW]]
; PROFITABLE-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[A]], i64 32
; PROFITABLE-NEXT:    [[MUL2:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 48, i64 [[TMP0]])
; PROFITABLE-NEXT:    [[MUL_RESULT3:%.*]] = extractvalue { i64, i1 } [[MUL2]], 0
; PROFITABLE-NEXT:    [[MUL_OVERFLOW4:%.*]] = extractvalue { i64, i1 } [[MUL2]], 1
; PROFITABLE-NEXT:    [[TMP5:%.*]] = sub i64 0, [[MUL_RESULT3]]
; PROFITABLE-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[SCEVGEP1]], i64 [[MUL_RESULT3]]
; PROFITABLE-NEXT:    [[TMP7:%.*]] = icmp ult ptr [[TMP6]], [[SCEVGEP1]]
; PROFITABLE-NEXT:    [[TMP8:%.*]] = or i1 [[TMP7]], [[MUL_OVERFLOW4]]
; PROFITABLE-NEXT:    [[SCEVGEP5:%.*]] = getelementptr i8, ptr [[A]], i64 24
; PROFITABLE-NEXT:    [[MUL6:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 48, i64 [[TMP0]])
; PROFITABLE-NEXT:    [[MUL_RESULT7:%.*]] = extractvalue { i64, i1 } [[MUL6]], 0
; PROFITABLE-NEXT:    [[MUL_OVERFLOW8:%.*]] = extractvalue { i64, i1 } [[MUL6]], 1
; PROFITABLE-NEXT:    [[TMP9:%.*]] = sub i64 0, [[MUL_RESULT7]]
; PROFITABLE-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[SCEVGEP5]], i64 [[MUL_RESULT7]]
; PROFITABLE-NEXT:    [[TMP11:%.*]] = icmp ult ptr [[TMP10]], [[SCEVGEP5]]
; PROFITABLE-NEXT:    [[TMP12:%.*]] = or i1 [[TMP11]], [[MUL_OVERFLOW8]]
; PROFITABLE-NEXT:    [[SCEVGEP9:%.*]] = getelementptr i8, ptr [[A]], i64 16
; PROFITABLE-NEXT:    [[MUL10:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 48, i64 [[TMP0]])
; PROFITABLE-NEXT:    [[MUL_RESULT11:%.*]] = extractvalue { i64, i1 } [[MUL10]], 0
; PROFITABLE-NEXT:    [[MUL_OVERFLOW12:%.*]] = extractvalue { i64, i1 } [[MUL10]], 1
; PROFITABLE-NEXT:    [[TMP13:%.*]] = sub i64 0, [[MUL_RESULT11]]
; PROFITABLE-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[SCEVGEP9]], i64 [[MUL_RESULT11]]
; PROFITABLE-NEXT:    [[TMP15:%.*]] = icmp ult ptr [[TMP14]], [[SCEVGEP9]]
; PROFITABLE-NEXT:    [[TMP16:%.*]] = or i1 [[TMP15]], [[MUL_OVERFLOW12]]
; PROFITABLE-NEXT:    [[SCEVGEP13:%.*]] = getelementptr i8, ptr [[A]], i64 8
; PROFITABLE-NEXT:    [[MUL14:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 48, i64 [[TMP0]])
; PROFITABLE-NEXT:    [[MUL_RESULT15:%.*]] = extractvalue { i64, i1 } [[MUL14]], 0
; PROFITABLE-NEXT:    [[MUL_OVERFLOW16:%.*]] = extractvalue { i64, i1 } [[MUL14]], 1
; PROFITABLE-NEXT:    [[TMP17:%.*]] = sub i64 0, [[MUL_RESULT15]]
; PROFITABLE-NEXT:    [[TMP18:%.*]] = getelementptr i8, ptr [[SCEVGEP13]], i64 [[MUL_RESULT15]]
; PROFITABLE-NEXT:    [[TMP19:%.*]] = icmp ult ptr [[TMP18]], [[SCEVGEP13]]
; PROFITABLE-NEXT:    [[TMP20:%.*]] = or i1 [[TMP19]], [[MUL_OVERFLOW16]]
; PROFITABLE-NEXT:    [[MUL17:%.*]] = call { i64, i1 } @llvm.umul.with.overflow.i64(i64 48, i64 [[TMP0]])
; PROFITABLE-NEXT:    [[MUL_RESULT18:%.*]] = extractvalue { i64, i1 } [[MUL17]], 0
; PROFITABLE-NEXT:    [[MUL_OVERFLOW19:%.*]] = extractvalue { i64, i1 } [[MUL17]], 1
; PROFITABLE-NEXT:    [[TMP21:%.*]] = sub i64 0, [[MUL_RESULT18]]
; PROFITABLE-NEXT:    [[TMP22:%.*]] = getelementptr i8, ptr [[A]], i64 [[MUL_RESULT18]]
; PROFITABLE-NEXT:    [[TMP23:%.*]] = icmp ult ptr [[TMP22]], [[A]]
; PROFITABLE-NEXT:    [[TMP24:%.*]] = or i1 [[TMP23]], [[MUL_OVERFLOW19]]
; PROFITABLE-NEXT:    [[TMP25:%.*]] = or i1 [[TMP4]], [[TMP8]]
; PROFITABLE-NEXT:    [[TMP26:%.*]] = or i1 [[TMP25]], [[TMP12]]
; PROFITABLE-NEXT:    [[TMP27:%.*]] = or i1 [[TMP26]], [[TMP16]]
; PROFITABLE-NEXT:    [[TMP28:%.*]] = or i1 [[TMP27]], [[TMP20]]
; PROFITABLE-NEXT:    [[TMP29:%.*]] = or i1 [[TMP28]], [[TMP24]]
; PROFITABLE-NEXT:    br i1 [[TMP29]], label [[SCALAR_PH]], label [[VECTOR_MEMCHECK:%.*]]
; PROFITABLE:       vector.memcheck:
; PROFITABLE-NEXT:    [[TMP30:%.*]] = mul i64 [[N]], 48
; PROFITABLE-NEXT:    [[SCEVGEP20:%.*]] = getelementptr i8, ptr [[A]], i64 [[TMP30]]
; PROFITABLE-NEXT:    [[SCEVGEP21:%.*]] = getelementptr i8, ptr [[B]], i64 [[TMP30]]
; PROFITABLE-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[A]], [[SCEVGEP21]]
; PROFITABLE-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[B]], [[SCEVGEP20]]
; PROFITABLE-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; PROFITABLE-NEXT:    br i1 [[FOUND_CONFLICT]], label [[SCALAR_PH]], label [[VECTOR_PH:%.*]]
; PROFITABLE:       vector.ph:
; PROFITABLE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x double> poison, double [[S]], i64 0
; PROFITABLE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x double> [[BROADCAST_SPLATINSERT]], <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
; PROFITABLE-NEXT:    br label [[VECTOR_BODY:%.*]]
; PROFITABLE:       vector.body:
; PROFITABLE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; PROFITABLE-NEXT:    [[TMP31:%.*]] = sub i64 [[N]], [[INDEX]]
; PROFITABLE-NEXT:    [[TMP32:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[TMP31]], i64 3, i64 3)
; PROFITABLE-NEXT:    [[TMP33:%.*]] = trunc i64 [[TMP32]] to i32
; PROFITABLE-NEXT:    [[TMP34:%.*]] = add i64 [[INDEX]], 0
; PROFITABLE-NEXT:    [[TMP35:%.*]] = getelementptr [[STRUCT_SU3_VECTOR:%.*]], ptr [[A]], i64 [[TMP34]]
; PROFITABLE-NEXT:    [[TMP36:%.*]] = getelementptr [[STRUCT_SU3_VECTOR]], ptr [[B]], i64 [[TMP34]]
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP35]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD22:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP36]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_STRIDED_LOAD22]], <vscale x 8 x double> [[BROADCAST_SPLAT]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP23:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP]], <vscale x 8 x double> [[VP_STRIDED_LOAD]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    call void @llvm.experimental.vp.strided.store.nxv8f64.p0.i64(<vscale x 8 x double> [[VP_OP23]], ptr [[TMP35]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]]), !alias.scope !0, !noalias !3
; PROFITABLE-NEXT:    [[TMP37:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP35]], i64 0, i64 0, i32 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD24:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP37]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[TMP38:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP36]], i64 0, i64 0, i32 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD25:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP38]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP26:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_STRIDED_LOAD25]], <vscale x 8 x double> [[BROADCAST_SPLAT]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP27:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP26]], <vscale x 8 x double> [[VP_STRIDED_LOAD24]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    call void @llvm.experimental.vp.strided.store.nxv8f64.p0.i64(<vscale x 8 x double> [[VP_OP27]], ptr [[TMP37]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]]), !alias.scope !0, !noalias !3
; PROFITABLE-NEXT:    [[TMP39:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP35]], i64 0, i64 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD28:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP39]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[TMP40:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP36]], i64 0, i64 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD29:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP40]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP30:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_STRIDED_LOAD29]], <vscale x 8 x double> [[BROADCAST_SPLAT]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP31:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP30]], <vscale x 8 x double> [[VP_STRIDED_LOAD28]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    call void @llvm.experimental.vp.strided.store.nxv8f64.p0.i64(<vscale x 8 x double> [[VP_OP31]], ptr [[TMP39]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]]), !alias.scope !0, !noalias !3
; PROFITABLE-NEXT:    [[TMP41:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP35]], i64 0, i64 1, i32 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD32:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP41]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[TMP42:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP36]], i64 0, i64 1, i32 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD33:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP42]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP34:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_STRIDED_LOAD33]], <vscale x 8 x double> [[BROADCAST_SPLAT]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP35:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP34]], <vscale x 8 x double> [[VP_STRIDED_LOAD32]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    call void @llvm.experimental.vp.strided.store.nxv8f64.p0.i64(<vscale x 8 x double> [[VP_OP35]], ptr [[TMP41]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]]), !alias.scope !0, !noalias !3
; PROFITABLE-NEXT:    [[TMP43:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP35]], i64 0, i64 2
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD36:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP43]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[TMP44:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP36]], i64 0, i64 2
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD37:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP44]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP38:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_STRIDED_LOAD37]], <vscale x 8 x double> [[BROADCAST_SPLAT]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP39:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP38]], <vscale x 8 x double> [[VP_STRIDED_LOAD36]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    call void @llvm.experimental.vp.strided.store.nxv8f64.p0.i64(<vscale x 8 x double> [[VP_OP39]], ptr [[TMP43]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]]), !alias.scope !0, !noalias !3
; PROFITABLE-NEXT:    [[TMP45:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP35]], i64 0, i64 2, i32 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD40:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP45]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[TMP46:%.*]] = getelementptr [3 x %struct.complex], ptr [[TMP36]], i64 0, i64 2, i32 1
; PROFITABLE-NEXT:    [[VP_STRIDED_LOAD41:%.*]] = call <vscale x 8 x double> @llvm.experimental.vp.strided.load.nxv8f64.p0.i64(ptr [[TMP46]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP42:%.*]] = call <vscale x 8 x double> @llvm.vp.fmul.nxv8f64(<vscale x 8 x double> [[VP_STRIDED_LOAD41]], <vscale x 8 x double> [[BROADCAST_SPLAT]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    [[VP_OP43:%.*]] = call <vscale x 8 x double> @llvm.vp.fadd.nxv8f64(<vscale x 8 x double> [[VP_OP42]], <vscale x 8 x double> [[VP_STRIDED_LOAD40]], <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]])
; PROFITABLE-NEXT:    call void @llvm.experimental.vp.strided.store.nxv8f64.p0.i64(<vscale x 8 x double> [[VP_OP43]], ptr [[TMP45]], i64 48, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 [[TMP33]]), !alias.scope !0, !noalias !3
; PROFITABLE-NEXT:    [[TMP47:%.*]] = zext i32 [[TMP33]] to i64
; PROFITABLE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP47]]
; PROFITABLE-NEXT:    [[TMP48:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N]]
; PROFITABLE-NEXT:    br i1 [[TMP48]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; PROFITABLE:       middle.block:
; PROFITABLE-NEXT:    br i1 true, label [[EXIT:%.*]], label [[SCALAR_PH]]
; PROFITABLE:       scalar.ph:
; PROFITABLE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ], [ 0, [[VECTOR_SCEVCHECK]] ], [ 0, [[VECTOR_MEMCHECK]] ]
; PROFITABLE-NEXT:    br label [[LOOP:%.*]]
; PROFITABLE:       loop:
; PROFITABLE-NEXT:    [[COUNTER:%.*]] = phi i64 [ [[COUNTER_NEXT:%.*]], [[LOOP]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; PROFITABLE-NEXT:    [[ADDRA:%.*]] = getelementptr [[STRUCT_SU3_VECTOR]], ptr [[A]], i64 [[COUNTER]]
; PROFITABLE-NEXT:    [[ADDRB:%.*]] = getelementptr [[STRUCT_SU3_VECTOR]], ptr [[B]], i64 [[COUNTER]]
; PROFITABLE-NEXT:    [[A0R:%.*]] = load double, ptr [[ADDRA]], align 8
; PROFITABLE-NEXT:    [[B0R:%.*]] = load double, ptr [[ADDRB]], align 8
; PROFITABLE-NEXT:    [[T0R:%.*]] = fmul double [[B0R]], [[S]]
; PROFITABLE-NEXT:    [[C0R:%.*]] = fadd double [[T0R]], [[A0R]]
; PROFITABLE-NEXT:    store double [[C0R]], ptr [[ADDRA]], align 8
; PROFITABLE-NEXT:    [[ADDRA0I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 0, i32 1
; PROFITABLE-NEXT:    [[A0I:%.*]] = load double, ptr [[ADDRA0I]], align 8
; PROFITABLE-NEXT:    [[ADDRB0I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 0, i32 1
; PROFITABLE-NEXT:    [[B0I:%.*]] = load double, ptr [[ADDRB0I]], align 8
; PROFITABLE-NEXT:    [[T0I:%.*]] = fmul double [[B0I]], [[S]]
; PROFITABLE-NEXT:    [[C0I:%.*]] = fadd double [[T0I]], [[A0I]]
; PROFITABLE-NEXT:    store double [[C0I]], ptr [[ADDRA0I]], align 8
; PROFITABLE-NEXT:    [[ADDRA1R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 1
; PROFITABLE-NEXT:    [[A1R:%.*]] = load double, ptr [[ADDRA1R]], align 8
; PROFITABLE-NEXT:    [[ADDRB1R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 1
; PROFITABLE-NEXT:    [[B1R:%.*]] = load double, ptr [[ADDRB1R]], align 8
; PROFITABLE-NEXT:    [[T1R:%.*]] = fmul double [[B1R]], [[S]]
; PROFITABLE-NEXT:    [[C1R:%.*]] = fadd double [[T1R]], [[A1R]]
; PROFITABLE-NEXT:    store double [[C1R]], ptr [[ADDRA1R]], align 8
; PROFITABLE-NEXT:    [[ADDRA1I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 1, i32 1
; PROFITABLE-NEXT:    [[A1I:%.*]] = load double, ptr [[ADDRA1I]], align 8
; PROFITABLE-NEXT:    [[ADDRB1I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 1, i32 1
; PROFITABLE-NEXT:    [[B1I:%.*]] = load double, ptr [[ADDRB1I]], align 8
; PROFITABLE-NEXT:    [[T1I:%.*]] = fmul double [[B1I]], [[S]]
; PROFITABLE-NEXT:    [[C1I:%.*]] = fadd double [[T1I]], [[A1I]]
; PROFITABLE-NEXT:    store double [[C1I]], ptr [[ADDRA1I]], align 8
; PROFITABLE-NEXT:    [[ADDRA2R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 2
; PROFITABLE-NEXT:    [[A2R:%.*]] = load double, ptr [[ADDRA2R]], align 8
; PROFITABLE-NEXT:    [[ADDRB2R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 2
; PROFITABLE-NEXT:    [[B2R:%.*]] = load double, ptr [[ADDRB2R]], align 8
; PROFITABLE-NEXT:    [[T2R:%.*]] = fmul double [[B2R]], [[S]]
; PROFITABLE-NEXT:    [[C2R:%.*]] = fadd double [[T2R]], [[A2R]]
; PROFITABLE-NEXT:    store double [[C2R]], ptr [[ADDRA2R]], align 8
; PROFITABLE-NEXT:    [[ADDRA2I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 2, i32 1
; PROFITABLE-NEXT:    [[A2I:%.*]] = load double, ptr [[ADDRA2I]], align 8
; PROFITABLE-NEXT:    [[ADDRB2I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 2, i32 1
; PROFITABLE-NEXT:    [[B2I:%.*]] = load double, ptr [[ADDRB2I]], align 8
; PROFITABLE-NEXT:    [[T2I:%.*]] = fmul double [[B2I]], [[S]]
; PROFITABLE-NEXT:    [[C2I:%.*]] = fadd double [[T2I]], [[A2I]]
; PROFITABLE-NEXT:    store double [[C2I]], ptr [[ADDRA2I]], align 8
; PROFITABLE-NEXT:    [[COUNTER_NEXT]] = add i64 [[COUNTER]], 1
; PROFITABLE-NEXT:    [[COND:%.*]] = icmp ne i64 [[COUNTER_NEXT]], [[N]]
; PROFITABLE-NEXT:    br i1 [[COND]], label [[LOOP]], label [[EXIT]], !llvm.loop [[LOOP8:![0-9]+]]
; PROFITABLE:       exit:
; PROFITABLE-NEXT:    ret void
;
; NON-PROFITABLE-LABEL: define void @eo_fermion_force
; NON-PROFITABLE-SAME: (ptr [[A:%.*]], ptr [[B:%.*]], double [[S:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; NON-PROFITABLE-NEXT:  entry:
; NON-PROFITABLE-NEXT:    br label [[LOOP:%.*]]
; NON-PROFITABLE:       loop:
; NON-PROFITABLE-NEXT:    [[COUNTER:%.*]] = phi i64 [ [[COUNTER_NEXT:%.*]], [[LOOP]] ], [ 0, [[ENTRY:%.*]] ]
; NON-PROFITABLE-NEXT:    [[ADDRA:%.*]] = getelementptr [[STRUCT_SU3_VECTOR:%.*]], ptr [[A]], i64 [[COUNTER]]
; NON-PROFITABLE-NEXT:    [[ADDRB:%.*]] = getelementptr [[STRUCT_SU3_VECTOR]], ptr [[B]], i64 [[COUNTER]]
; NON-PROFITABLE-NEXT:    [[A0R:%.*]] = load double, ptr [[ADDRA]], align 8
; NON-PROFITABLE-NEXT:    [[B0R:%.*]] = load double, ptr [[ADDRB]], align 8
; NON-PROFITABLE-NEXT:    [[T0R:%.*]] = fmul double [[B0R]], [[S]]
; NON-PROFITABLE-NEXT:    [[C0R:%.*]] = fadd double [[T0R]], [[A0R]]
; NON-PROFITABLE-NEXT:    store double [[C0R]], ptr [[ADDRA]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRA0I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 0, i32 1
; NON-PROFITABLE-NEXT:    [[A0I:%.*]] = load double, ptr [[ADDRA0I]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRB0I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 0, i32 1
; NON-PROFITABLE-NEXT:    [[B0I:%.*]] = load double, ptr [[ADDRB0I]], align 8
; NON-PROFITABLE-NEXT:    [[T0I:%.*]] = fmul double [[B0I]], [[S]]
; NON-PROFITABLE-NEXT:    [[C0I:%.*]] = fadd double [[T0I]], [[A0I]]
; NON-PROFITABLE-NEXT:    store double [[C0I]], ptr [[ADDRA0I]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRA1R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 1
; NON-PROFITABLE-NEXT:    [[A1R:%.*]] = load double, ptr [[ADDRA1R]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRB1R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 1
; NON-PROFITABLE-NEXT:    [[B1R:%.*]] = load double, ptr [[ADDRB1R]], align 8
; NON-PROFITABLE-NEXT:    [[T1R:%.*]] = fmul double [[B1R]], [[S]]
; NON-PROFITABLE-NEXT:    [[C1R:%.*]] = fadd double [[T1R]], [[A1R]]
; NON-PROFITABLE-NEXT:    store double [[C1R]], ptr [[ADDRA1R]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRA1I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 1, i32 1
; NON-PROFITABLE-NEXT:    [[A1I:%.*]] = load double, ptr [[ADDRA1I]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRB1I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 1, i32 1
; NON-PROFITABLE-NEXT:    [[B1I:%.*]] = load double, ptr [[ADDRB1I]], align 8
; NON-PROFITABLE-NEXT:    [[T1I:%.*]] = fmul double [[B1I]], [[S]]
; NON-PROFITABLE-NEXT:    [[C1I:%.*]] = fadd double [[T1I]], [[A1I]]
; NON-PROFITABLE-NEXT:    store double [[C1I]], ptr [[ADDRA1I]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRA2R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 2
; NON-PROFITABLE-NEXT:    [[A2R:%.*]] = load double, ptr [[ADDRA2R]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRB2R:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 2
; NON-PROFITABLE-NEXT:    [[B2R:%.*]] = load double, ptr [[ADDRB2R]], align 8
; NON-PROFITABLE-NEXT:    [[T2R:%.*]] = fmul double [[B2R]], [[S]]
; NON-PROFITABLE-NEXT:    [[C2R:%.*]] = fadd double [[T2R]], [[A2R]]
; NON-PROFITABLE-NEXT:    store double [[C2R]], ptr [[ADDRA2R]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRA2I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRA]], i64 0, i64 2, i32 1
; NON-PROFITABLE-NEXT:    [[A2I:%.*]] = load double, ptr [[ADDRA2I]], align 8
; NON-PROFITABLE-NEXT:    [[ADDRB2I:%.*]] = getelementptr [3 x %struct.complex], ptr [[ADDRB]], i64 0, i64 2, i32 1
; NON-PROFITABLE-NEXT:    [[B2I:%.*]] = load double, ptr [[ADDRB2I]], align 8
; NON-PROFITABLE-NEXT:    [[T2I:%.*]] = fmul double [[B2I]], [[S]]
; NON-PROFITABLE-NEXT:    [[C2I:%.*]] = fadd double [[T2I]], [[A2I]]
; NON-PROFITABLE-NEXT:    store double [[C2I]], ptr [[ADDRA2I]], align 8
; NON-PROFITABLE-NEXT:    [[COUNTER_NEXT]] = add i64 [[COUNTER]], 1
; NON-PROFITABLE-NEXT:    [[COND:%.*]] = icmp ne i64 [[COUNTER_NEXT]], [[N]]
; NON-PROFITABLE-NEXT:    br i1 [[COND]], label [[LOOP]], label [[EXIT:%.*]]
; NON-PROFITABLE:       exit:
; NON-PROFITABLE-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %counter = phi i64 [ %counter.next, %loop], [ 0, %entry]
  %addra = getelementptr %struct.su3_vector, ptr %a, i64 %counter
  %addrb = getelementptr %struct.su3_vector, ptr %b, i64 %counter
  %a0r = load double, ptr %addra, align 8
  %b0r = load double, ptr %addrb, align 8
  %t0r = fmul double %b0r, %s
  %c0r = fadd double %t0r, %a0r
  store double %c0r, ptr %addra, align 8
  %addra0i = getelementptr [3 x %struct.complex], ptr %addra, i64 0, i64 0, i32 1
  %a0i = load double, ptr %addra0i, align 8
  %addrb0i = getelementptr [3 x %struct.complex], ptr %addrb, i64 0, i64 0, i32 1
  %b0i = load double, ptr %addrb0i, align 8
  %t0i = fmul double %b0i, %s
  %c0i = fadd double %t0i, %a0i
  store double %c0i, ptr %addra0i, align 8

  %addra1r = getelementptr [3 x %struct.complex], ptr %addra, i64 0, i64 1
  %a1r = load double, ptr %addra1r, align 8
  %addrb1r = getelementptr [3 x %struct.complex], ptr %addrb, i64 0, i64 1
  %b1r = load double, ptr %addrb1r, align 8
  %t1r = fmul double %b1r, %s
  %c1r = fadd double %t1r, %a1r
  store double %c1r, ptr %addra1r, align 8
  %addra1i = getelementptr [3 x %struct.complex], ptr %addra, i64 0, i64 1, i32 1
  %a1i = load double, ptr %addra1i, align 8
  %addrb1i = getelementptr [3 x %struct.complex], ptr %addrb, i64 0, i64 1, i32 1
  %b1i = load double, ptr %addrb1i, align 8
  %t1i = fmul double %b1i, %s
  %c1i = fadd double %t1i, %a1i
  store double %c1i, ptr %addra1i, align 8

  %addra2r = getelementptr [3 x %struct.complex], ptr %addra, i64 0, i64 2
  %a2r = load double, ptr %addra2r, align 8
  %addrb2r = getelementptr [3 x %struct.complex], ptr %addrb, i64 0, i64 2
  %b2r = load double, ptr %addrb2r, align 8
  %t2r = fmul double %b2r, %s
  %c2r = fadd double %t2r, %a2r
  store double %c2r, ptr %addra2r, align 8
  %addra2i = getelementptr [3 x %struct.complex], ptr %addra, i64 0, i64 2, i32 1
  %a2i = load double, ptr %addra2i, align 8
  %addrb2i = getelementptr [3 x %struct.complex], ptr %addrb, i64 0, i64 2, i32 1
  %b2i = load double, ptr %addrb2i, align 8
  %t2i = fmul double %b2i, %s
  %c2i = fadd double %t2i, %a2i
  store double %c2i, ptr %addra2i, align 8

  %counter.next = add i64 %counter, 1
  %cond = icmp ne i64 %counter.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}
