; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=loop-vectorize -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=512 -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -mattr=+v < %s | FileCheck %s
define void @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  for.body11.i.preheader:
; CHECK-NEXT:    br label [[FOR_BODY11_I:%.*]]
; CHECK:       for.body11.i:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY11_I_PREHEADER:%.*]] ], [ [[INDVARS_IV_NEXT:%.*]], [[LOR_END_I:%.*]] ]
; CHECK-NEXT:    br i1 false, label [[LOR_END_I]], label [[LOR_RHS_I:%.*]]
; CHECK:       lor.rhs.i:
; CHECK-NEXT:    br label [[LOR_END_I]]
; CHECK:       lor.end.i:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ false, [[FOR_BODY11_I]] ], [ false, [[LOR_RHS_I]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 100
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[SW_EPILOG_I_LOOPEXIT71:%.*]], label [[FOR_BODY11_I]]
; CHECK:       sw.epilog.i.loopexit71:
; CHECK-NEXT:    ret void
;
for.body11.i.preheader:
  br label %for.body11.i

for.body11.i:
  %indvars.iv = phi i64 [ 0, %for.body11.i.preheader ], [ %indvars.iv.next, %lor.end.i ]
  br i1 false, label %lor.end.i, label %lor.rhs.i

lor.rhs.i:
  br label %lor.end.i

lor.end.i:
  %0 = phi i1 [ false, %for.body11.i ], [ false, %lor.rhs.i ]
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 100
  br i1 %exitcond.not, label %sw.epilog.i.loopexit71, label %for.body11.i

sw.epilog.i.loopexit71:
  ret void
}
