; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -passes=loop-vectorize -force-tail-folding-style=data-with-evl \
; RUN: -prefer-predicate-over-epilogue=predicate-dont-vectorize -mtriple=riscv64 -mattr=+v | FileCheck %s

; Make sure the assertion in fixupIVUsers doesn't crash revectorized loops
define fastcc void @foo(ptr %arg) {
; CHECK-LABEL: define fastcc void @foo(
; CHECK-SAME: ptr [[ARG:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr getelementptr inbounds nuw (i8, ptr null, i64 72468), align 4
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[ADD:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[PHI2:%.*]] = phi i32 [ [[ADD4:%.*]], %[[LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[ADD]] = add i32 [[PHI]], 1
; CHECK-NEXT:    [[ICMP:%.*]] = icmp ult i32 [[PHI]], 0
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[PHI2]], [[LOAD]]
; CHECK-NEXT:    [[ADD3:%.*]] = add i32 [[MUL]], 0
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[ADD3]] to i64
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr i8, ptr null, i64 [[ZEXT]]
; CHECK-NEXT:    store i8 0, ptr [[GETELEMENTPTR]], align 1
; CHECK-NEXT:    [[ADD4]] = add i32 [[PHI2]], 1
; CHECK-NEXT:    [[ICMP5:%.*]] = icmp ne i32 [[ADD4]], 0
; CHECK-NEXT:    br i1 [[ICMP5]], label %[[LOOP]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[PHI7:%.*]] = phi i32 [ [[ADD]], %[[LOOP]] ]
; CHECK-NEXT:    ret void
;
entry:
  %load = load i32, ptr getelementptr inbounds nuw (i8, ptr null, i64 72468), align 4
  br label %loop

loop:                                              ; preds = %loop, %entry
  %phi = phi i32 [ %add, %loop ], [ 0, %entry ]
  %phi2 = phi i32 [ %add4, %loop ], [ 0, %entry ]
  %add = add i32 %phi, 1
  %icmp = icmp ult i32 %phi, 0
  %mul = mul i32 %phi2, %load
  %add3 = add i32 %mul, 0
  %zext = zext i32 %add3 to i64
  %getelementptr = getelementptr i8, ptr null, i64 %zext
  store i8 0, ptr %getelementptr, align 1
  %add4 = add i32 %phi2, 1
  %icmp5 = icmp ne i32 %add4, 0
  br i1 %icmp5, label %loop, label %exit

exit:                                              ; preds = %loop
  %phi7 = phi i32 [ %add, %loop ]
  ret void
}
