; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -sifive-loop-vectorizer-enable-interleaved-access=const-stride -passes=loop-vectorize < %s | FileCheck %s

%class.a = type { i32, i32 }

@m = global %class.a zeroinitializer, align 4

define void @_Z3fn1v(i32 %n, ptr %k, i32 %l) {
; CHECK-LABEL: define void @_Z3fn1v(
; CHECK-SAME: i32 [[N:%.*]], ptr [[K:%.*]], i32 [[L:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = sext i32 [[L]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[N]], -2
; CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[TMP2]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ule i64 [[TMP3]], 1
; CHECK-NEXT:    br i1 [[TMP4]], label [[SCALAR_PH:%.*]], label [[VECTOR_SCEVCHECK:%.*]]
; CHECK:       vector.scevcheck:
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i32 [[L]], 1
; CHECK-NEXT:    br i1 [[IDENT_CHECK]], label [[SCALAR_PH]], label [[VECTOR_MEMCHECK:%.*]]
; CHECK:       vector.memcheck:
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[N]], -2
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP5]] to i64
; CHECK-NEXT:    [[TMP7:%.*]] = shl nuw nsw i64 [[TMP6]], 3
; CHECK-NEXT:    [[TMP8:%.*]] = add nuw nsw i64 [[TMP7]], 4
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[K]], i64 [[TMP8]]
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr @m, [[SCEVGEP]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[K]], getelementptr inbounds nuw (i8, ptr @m, i64 4)
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label [[SCALAR_PH]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP3]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[N_VEC]], i32 2, i1 true)
; CHECK-NEXT:    [[IND_END:%.*]] = mul i64 [[N_VEC]], [[TMP0]]
; CHECK-NEXT:    [[DOTCAST:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[IND_END1:%.*]] = add i32 1, [[DOTCAST]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[N_VEC]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV1]], [[TMP0]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds [[CLASS_A:%.*]], ptr [[K]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP14:%.*]] = mul nuw nsw i32 [[TMP12]], 2
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr align 4 [[TMP13]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP14]])
; CHECK-NEXT:    [[DEINTERLEAVED_RESULTS:%.*]] = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave2.nxv4i32(<vscale x 4 x i32> [[WIDE_MASKED_LOAD]])
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } [[DEINTERLEAVED_RESULTS]], 0
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv2i32.nxv2p0(<vscale x 2 x i32> [[TMP15]], <vscale x 2 x ptr> align 4 shufflevector (<vscale x 2 x ptr> insertelement (<vscale x 2 x ptr> poison, ptr @m, i64 0), <vscale x 2 x ptr> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> splat (i1 true), i32 [[TMP12]])
; CHECK-NEXT:    [[TMP16:%.*]] = zext i32 [[TMP12]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP16]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP19:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP19]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[IND_END]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ], [ 0, [[VECTOR_SCEVCHECK]] ], [ 0, [[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi i32 [ [[IND_END1]], [[MIDDLE_BLOCK]] ], [ 1, [[ENTRY]] ], [ 1, [[VECTOR_SCEVCHECK]] ], [ 1, [[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[NO_SCEV_CHECK:%.*]] = phi i1 [ true, [[VECTOR_MEMCHECK]] ], [ false, [[VECTOR_SCEVCHECK]] ], [ true, [[ENTRY]] ], [ true, [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = add i32 [[N]], -1
; CHECK-NEXT:    [[TMP38:%.*]] = sub i32 [[TMP18]], [[BC_RESUME_VAL2]]
; CHECK-NEXT:    [[TMP20:%.*]] = zext i32 [[TMP38]] to i64
; CHECK-NEXT:    [[TMP21:%.*]] = add nuw nsw i64 [[TMP20]], 1
; CHECK-NEXT:    [[TMP22:%.*]] = shl nsw i64 [[TMP0]], 3
; CHECK-NEXT:    br i1 [[NO_SCEV_CHECK]], label [[SCALAR_PH9:%.*]], label [[VECTOR_MEMCHECK2:%.*]]
; CHECK:       vector.memcheck2:
; CHECK-NEXT:    [[TMP23:%.*]] = add i32 [[N]], -1
; CHECK-NEXT:    [[TMP24:%.*]] = sub i32 [[TMP23]], [[BC_RESUME_VAL2]]
; CHECK-NEXT:    [[TMP25:%.*]] = zext i32 [[TMP24]] to i64
; CHECK-NEXT:    [[TMP26:%.*]] = mul i64 [[TMP0]], [[TMP25]]
; CHECK-NEXT:    [[TMP27:%.*]] = shl i64 [[TMP26]], 3
; CHECK-NEXT:    [[TMP28:%.*]] = shl i64 [[BC_RESUME_VAL]], 3
; CHECK-NEXT:    [[TMP29:%.*]] = add i64 [[TMP27]], [[TMP28]]
; CHECK-NEXT:    [[SCEVGEP3:%.*]] = getelementptr i8, ptr [[K]], i64 [[TMP29]]
; CHECK-NEXT:    [[SCEVGEP4:%.*]] = getelementptr i8, ptr [[K]], i64 [[TMP28]]
; CHECK-NEXT:    [[TMP30:%.*]] = icmp ult ptr [[SCEVGEP3]], [[SCEVGEP4]]
; CHECK-NEXT:    [[UMIN:%.*]] = select i1 [[TMP30]], ptr [[SCEVGEP3]], ptr [[SCEVGEP4]]
; CHECK-NEXT:    [[TMP31:%.*]] = icmp ugt ptr [[SCEVGEP3]], [[SCEVGEP4]]
; CHECK-NEXT:    [[UMAX:%.*]] = select i1 [[TMP31]], ptr [[SCEVGEP3]], ptr [[SCEVGEP4]]
; CHECK-NEXT:    [[SCEVGEP5:%.*]] = getelementptr i8, ptr [[UMAX]], i64 4
; CHECK-NEXT:    [[BOUND06:%.*]] = icmp ult ptr @m, [[SCEVGEP5]]
; CHECK-NEXT:    [[BOUND17:%.*]] = icmp ult ptr [[UMIN]], getelementptr inbounds nuw (i8, ptr @m, i64 4)
; CHECK-NEXT:    [[FOUND_CONFLICT8:%.*]] = and i1 [[BOUND06]], [[BOUND17]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT8]], label [[SCALAR_PH9]], label [[VECTOR_PH10:%.*]]
; CHECK:       vector.ph10:
; CHECK-NEXT:    [[TMP32:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP21]], i32 2, i1 true)
; CHECK-NEXT:    br label [[FOR_BODY_I:%.*]]
; CHECK:       vector.body11:
; CHECK-NEXT:    [[INDEX12:%.*]] = phi i64 [ 0, [[VECTOR_PH10]] ], [ [[INDEX_EVL_NEXT16:%.*]], [[FOR_BODY_I]] ]
; CHECK-NEXT:    [[EVL_BASED_IV13:%.*]] = phi i64 [ 0, [[VECTOR_PH10]] ], [ [[INDEX_EVL_NEXT16]], [[FOR_BODY_I]] ]
; CHECK-NEXT:    [[AVL14:%.*]] = sub i64 [[TMP21]], [[EVL_BASED_IV13]]
; CHECK-NEXT:    [[TMP33:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL14]], i32 2, i1 true)
; CHECK-NEXT:    [[TMP34:%.*]] = mul i64 [[EVL_BASED_IV13]], [[TMP0]]
; CHECK-NEXT:    [[OFFSET_IDX15:%.*]] = add i64 [[BC_RESUME_VAL]], [[TMP34]]
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds [[CLASS_A]], ptr [[K]], i64 [[OFFSET_IDX15]]
; CHECK-NEXT:    [[VP_STRIDED_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.experimental.vp.strided.load.nxv2i32.p0.i64(ptr align 4 [[TMP35]], i64 [[TMP22]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP33]])
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv2i32.nxv2p0(<vscale x 2 x i32> [[VP_STRIDED_LOAD]], <vscale x 2 x ptr> align 4 shufflevector (<vscale x 2 x ptr> insertelement (<vscale x 2 x ptr> poison, ptr @m, i64 0), <vscale x 2 x ptr> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> splat (i1 true), i32 [[TMP33]])
; CHECK-NEXT:    [[TMP36:%.*]] = zext i32 [[TMP33]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT16]] = add nuw i64 [[TMP36]], [[EVL_BASED_IV13]]
; CHECK-NEXT:    [[TMP37:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT16]], [[TMP21]]
; CHECK-NEXT:    br i1 [[TMP37]], label [[MIDDLE_BLOCK17:%.*]], label [[FOR_BODY_I]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       middle.block17:
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       scalar.ph9:
; CHECK-NEXT:    [[BC_RESUME_VAL18:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[BC_RESUME_VAL]], [[VECTOR_MEMCHECK2]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL19:%.*]] = phi i32 [ [[BC_RESUME_VAL2]], [[SCALAR_PH]] ], [ [[BC_RESUME_VAL2]], [[VECTOR_MEMCHECK2]] ]
; CHECK-NEXT:    br label [[FOR_BODY_I1:%.*]]
; CHECK:       for.body.i:
; CHECK-NEXT:    [[INDVARS_IV_I:%.*]] = phi i64 [ [[BC_RESUME_VAL18]], [[SCALAR_PH9]] ], [ [[INDVARS_IV_NEXT_I:%.*]], [[FOR_BODY_I1]] ]
; CHECK-NEXT:    [[H_08_I:%.*]] = phi i32 [ [[BC_RESUME_VAL19]], [[SCALAR_PH9]] ], [ [[INC_I:%.*]], [[FOR_BODY_I1]] ]
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds [[CLASS_A]], ptr [[K]], i64 [[INDVARS_IV_I]]
; CHECK-NEXT:    [[TMP44:%.*]] = load i32, ptr [[ARRAYIDX_I]], align 4
; CHECK-NEXT:    store i32 [[TMP44]], ptr @m, align 4
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i32 [[H_08_I]], 1
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I]] = add nsw i64 [[INDVARS_IV_I]], [[TMP0]]
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i32 [[INC_I]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label [[EXIT]], label [[FOR_BODY_I1]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %0 = sext i32 %l to i64
  br label %for.body.i

for.body.i:                                       ; preds = %for.body.i, %entry
  %indvars.iv.i = phi i64 [ 0, %entry ], [ %indvars.iv.next.i, %for.body.i ]
  %h.08.i = phi i32 [ 1, %entry ], [ %inc.i, %for.body.i ]
  %arrayidx.i = getelementptr inbounds %class.a, ptr %k, i64 %indvars.iv.i
  %1 = load i32, ptr %arrayidx.i, align 4
  store i32 %1, ptr @m, align 4
  %inc.i = add nuw nsw i32 %h.08.i, 1
  %indvars.iv.next.i = add nsw i64 %indvars.iv.i, %0
  %exitcond.not.i = icmp eq i32 %inc.i, %n
  br i1 %exitcond.not.i, label %exit, label %for.body.i

exit:                                             ; preds = %for.body.i
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]], [[META3]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]]}
;.
