; RUN: opt -passes=loop-vectorize -mtriple riscv64 -vector-primary-lmul-max=3 -mcpu=sifive-x280 -debug-only=vplan-cost-model -disable-output %s 2>&1 | FileCheck %s

; REQUIRES: asserts

; SIFIVE: FIXME: upstream changes the underlying value from Trunc to Phi
; SIFIVE: so the sew becomes i64. Update the checks once upstream fixes it.
; CHECK: VPlanCM: cost 2 for RVL (m1, i64) for VPInstruction: ir<%indvars.iv> = WIDEN-INDUCTION
; CHECK: VPlanCM: cost 3 for RVL (m2, i64) for VPInstruction: ir<%indvars.iv> = WIDEN-INDUCTION
; CHECK: VPlanCM: cost 5 for RVL (m4, i64) for VPInstruction: ir<%indvars.iv> = WIDEN-INDUCTION
; CHECK: VPlanCM: cost 9 for RVL (m8, i64) for VPInstruction: ir<%indvars.iv> = WIDEN-INDUCTION
; CHECK: VPlanCM: cost 17 for RVL (unsupported, i64) for VPInstruction: ir<%indvars.iv> = WIDEN-INDUCTION


define float @foo(ptr %a, i32 %N) {
entry:
  %cmp4 = icmp sgt i32 %N, 0
  br i1 %cmp4, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:
  %wide.trip.count = zext i32 %N to i64
  br label %for.body

for.cond.cleanup.loopexit:
  br label %for.cond.cleanup

for.cond.cleanup:
  ret float undef

for.body:
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.body ]
  %0 = trunc i64 %indvars.iv to i32
  %rem = and i32 %0, 3
  %conv = sitofp i32 %rem to float
  %arrayidx = getelementptr inbounds float, ptr %a, i64 %indvars.iv
  store float %conv, ptr %arrayidx, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup.loopexit, label %for.body
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
