; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=loop-vectorize -sifive-enable-csa -force-vectorization -mtriple riscv64 -riscv-v-vector-bits-min=256 -mattr="+v" -S | FileCheck %s

define i32 @zot(ptr %arg, i64 %arg1) {
; CHECK-LABEL: define i32 @zot(
; CHECK-SAME: ptr [[ARG:%.*]], i64 [[ARG1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB3:%.*]]
; CHECK:       bb2:
; CHECK-NEXT:    [[PHI1:%.*]] = phi i64 [ 0, [[SCALAR_PH:%.*]] ], [ [[ADD1:%.*]], [[BB3]] ]
; CHECK-NEXT:    [[PHI3:%.*]] = phi i32 [ 0, [[SCALAR_PH]] ], [ [[SELECT:%.*]], [[BB3]] ]
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr inbounds i32, ptr [[ARG]], i64 [[PHI1]]
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GETELEMENTPTR]], align 4
; CHECK-NEXT:    [[ICMP:%.*]] = icmp slt i32 [[LOAD]], 0
; CHECK-NEXT:    [[SELECT]] = select i1 [[ICMP]], i32 [[PHI3]], i32 1
; CHECK-NEXT:    [[ADD1]] = add nsw i64 [[PHI1]], 2
; CHECK-NEXT:    [[ICMP4:%.*]] = icmp ult i64 [[PHI1]], [[ARG1]]
; CHECK-NEXT:    br i1 [[ICMP4]], label [[BB3]], label [[BB5:%.*]]
; CHECK:       bb5:
; CHECK-NEXT:    [[PHI3_LCSSA:%.*]] = phi i32 [ [[PHI3]], [[BB3]] ]
; CHECK-NEXT:    ret i32 [[PHI3_LCSSA]]
;
bb:
  br label %bb2

bb2:                                              ; preds = %bb2, %bb
  %phi = phi i64 [ 0, %bb ], [ %add, %bb2 ]
  %phi3 = phi i32 [ 0, %bb ], [ %select, %bb2 ]
  %getelementptr = getelementptr inbounds i32, ptr %arg, i64 %phi
  %load = load i32, ptr %getelementptr, align 4
  %icmp = icmp slt i32 %load, 0
  %select = select i1 %icmp, i32 %phi3, i32 1
  %add = add nsw i64 %phi, 2
  %icmp4 = icmp ult i64 %phi, %arg1
  br i1 %icmp4, label %bb2, label %bb5

bb5:                                              ; preds = %bb2
  ret i32 %phi3
}
