; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mcpu=sifive-x280o < %s | FileCheck %s

define i32 @test() vscale_range(8,1024) {
; CHECK-LABEL: define i32 @test(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[V11:%.*]] = alloca [0 x [0 x [10 x i32]]], i32 0, align 8
; CHECK-NEXT:    [[ADD_PTR26_I:%.*]] = getelementptr i8, ptr [[V11]], i64 8
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 8, i32 1, i1 true)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 8, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 2)
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP1]], i32 1, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[ADD_PTR26_I]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[OFFSET_IDX1:%.*]] = mul i64 [[EVL_BASED_IV]], 4
; CHECK-NEXT:    [[NEXT_GEP2:%.*]] = getelementptr i8, ptr [[V11]], i64 [[OFFSET_IDX1]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr [[NEXT_GEP2]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 1 x i32> @llvm.vp.load.nxv1i32.p0(ptr align 4 [[TMP6]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; CHECK-NEXT:    call void @llvm.vp.store.nxv1i32.p0(<vscale x 1 x i32> [[VP_OP_LOAD]], ptr align 4 [[TMP7]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP5]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 8
; CHECK-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL3:%.*]] = phi ptr [ [[ADD_PTR26_I]], %[[ENTRY]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL4:%.*]] = phi ptr [ [[V11]], %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[__I_0155_I:%.*]] = phi i64 [ [[INC_I:%.*]], %[[LOOP]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[__Q_0154_I:%.*]] = phi ptr [ [[INCDEC_PTR30_I:%.*]], %[[LOOP]] ], [ [[BC_RESUME_VAL3]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[__P_1153_I:%.*]] = phi ptr [ [[INCDEC_PTR_I:%.*]], %[[LOOP]] ], [ [[BC_RESUME_VAL4]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[__P_1153_I]], align 4
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[__Q_0154_I]], align 4
; CHECK-NEXT:    [[INCDEC_PTR_I]] = getelementptr i8, ptr [[__P_1153_I]], i64 4
; CHECK-NEXT:    [[INCDEC_PTR30_I]] = getelementptr i8, ptr [[__Q_0154_I]], i64 4
; CHECK-NEXT:    [[INC_I]] = add i64 [[__I_0155_I]], 1
; CHECK-NEXT:    [[EXITCOND162_NOT_I:%.*]] = icmp eq i64 [[INC_I]], 8
; CHECK-NEXT:    br i1 [[EXITCOND162_NOT_I]], label %[[EXIT]], label %[[LOOP]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %v11 = alloca [0 x [0 x [10 x i32]]], i32 0, align 8
  %add.ptr26.i = getelementptr i8, ptr %v11, i64 8
  br label %loop

loop:
  %__i.0155.i = phi i64 [ %inc.i, %loop ], [ 0, %entry ]
  %__q.0154.i = phi ptr [ %incdec.ptr30.i, %loop ], [ %add.ptr26.i, %entry ]
  %__p.1153.i = phi ptr [ %incdec.ptr.i, %loop ], [ %v11, %entry ]
  %0 = load i32, ptr %__p.1153.i, align 4
  store i32 %0, ptr %__q.0154.i, align 4
  %incdec.ptr.i = getelementptr i8, ptr %__p.1153.i, i64 4
  %incdec.ptr30.i = getelementptr i8, ptr %__q.0154.i, i64 4
  %inc.i = add i64 %__i.0155.i, 1
  %exitcond162.not.i = icmp eq i64 %inc.i, 8
  br i1 %exitcond162.not.i, label %exit, label %loop

exit:
  ret i32 0
}

;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
