; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mattr="+v"  -S %s | FileCheck --check-prefix=VEC %s
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mattr="+zve32f,+zvl128b" -S %s | FileCheck --check-prefix=UNSUPPORT %s
;
; COM: SCT-4066
; COM: Extracted from 502.gcc_r decNumber.c:6538
; COM: Original Loop:
; COM:
; COM: for (; c<clsu+bshift; a++, c++) {  /* copy needed */
; COM:         if (a<alsu+alength) *c=*a;
; COM:                else *c=0;
; COM: }


define dso_local noundef signext i32 @f(ptr noundef writeonly %c, ptr noundef readonly %a, ptr noundef readnone %clsu, i32 noundef signext %bshift, ptr noundef readnone %alsu, i32 noundef signext %alength) local_unnamed_addr #0 {
; VEC-LABEL: @f(
; VEC-NEXT:  entry:
; VEC-NEXT:    [[C4:%.*]] = ptrtoint ptr [[C:%.*]] to i64
; VEC-NEXT:    [[CLSU3:%.*]] = ptrtoint ptr [[CLSU:%.*]] to i64
; VEC-NEXT:    [[A2:%.*]] = ptrtoint ptr [[A:%.*]] to i64
; VEC-NEXT:    [[C1:%.*]] = ptrtoint ptr [[C]] to i64
; VEC-NEXT:    [[IDX_EXT:%.*]] = zext i32 [[BSHIFT:%.*]] to i64
; VEC-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[CLSU]], i64 [[IDX_EXT]]
; VEC-NEXT:    [[CMP10:%.*]] = icmp ugt ptr [[ADD_PTR]], [[C]]
; VEC-NEXT:    br i1 [[CMP10]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_END:%.*]]
; VEC:       for.body.lr.ph:
; VEC-NEXT:    [[IDX_EXT1:%.*]] = zext i32 [[ALENGTH:%.*]] to i64
; VEC-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i32, ptr [[ALSU:%.*]], i64 [[IDX_EXT1]]
; VEC-NEXT:    [[TMP0:%.*]] = shl nuw nsw i64 [[IDX_EXT]], 2
; VEC-NEXT:    [[TMP1:%.*]] = add nuw i64 [[CLSU3]], [[TMP0]]
; VEC-NEXT:    [[TMP2:%.*]] = add i64 [[C4]], 4
; VEC-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP1]], i64 [[TMP2]])
; VEC-NEXT:    [[TMP3:%.*]] = add i64 [[UMAX]], -1
; VEC-NEXT:    [[TMP4:%.*]] = sub i64 [[TMP3]], [[C4]]
; VEC-NEXT:    [[TMP5:%.*]] = lshr i64 [[TMP4]], 2
; VEC-NEXT:    [[TMP6:%.*]] = add nuw nsw i64 [[TMP5]], 1
; VEC-NEXT:    br label [[VECTOR_MEMCHECK:%.*]]
; VEC:       vector.memcheck:
; VEC-NEXT:    [[TMP7:%.*]] = call i64 @llvm.vscale.i64()
; VEC-NEXT:    [[TMP8:%.*]] = mul nuw i64 [[TMP7]], 2
; VEC-NEXT:    [[TMP9:%.*]] = mul i64 [[TMP8]], 4
; VEC-NEXT:    [[TMP10:%.*]] = sub i64 [[C1]], [[A2]]
; VEC-NEXT:    [[DIFF_CHECK:%.*]] = icmp ult i64 [[TMP10]], [[TMP9]]
; VEC-NEXT:    br i1 [[DIFF_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; VEC:       vector.ph:
; VEC-NEXT:    [[TMP11:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP6]], i32 2, i1 true)
; VEC-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x ptr> poison, ptr [[ADD_PTR2]], i64 0
; VEC-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x ptr> [[BROADCAST_SPLATINSERT]], <vscale x 2 x ptr> poison, <vscale x 2 x i32> zeroinitializer
; VEC-NEXT:    [[TMP16:%.*]] = call i64 @llvm.vscale.i64()
; VEC-NEXT:    [[TMP13:%.*]] = mul nuw i64 [[TMP16]], 2
; VEC-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP13]], 0
; VEC-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[TMP14]], i64 0
; VEC-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[DOTSPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; VEC-NEXT:    [[TMP15:%.*]] = call <vscale x 2 x i64> @llvm.stepvector.nxv2i64()
; VEC-NEXT:    [[TMP20:%.*]] = add <vscale x 2 x i64> [[DOTSPLAT]], [[TMP15]]
; VEC-NEXT:    br label [[VECTOR_BODY:%.*]]
; VEC:       vector.body:
; VEC-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; VEC-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; VEC-NEXT:    [[POINTER_PHI:%.*]] = phi ptr [ [[A]], [[VECTOR_PH]] ], [ [[PTR_IND:%.*]], [[VECTOR_BODY]] ]
; VEC-NEXT:    [[TMP17:%.*]] = mul <vscale x 2 x i64> [[TMP20]], splat (i64 4)
; VEC-NEXT:    [[VECTOR_GEP:%.*]] = getelementptr i8, ptr [[POINTER_PHI]], <vscale x 2 x i64> [[TMP17]]
; VEC-NEXT:    [[AVL:%.*]] = sub i64 [[TMP6]], [[EVL_BASED_IV1]]
; VEC-NEXT:    [[TMP18:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; VEC-NEXT:    [[TMP19:%.*]] = zext i32 [[TMP18]] to i64
; VEC-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV1]], 4
; VEC-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[C]], i64 [[OFFSET_IDX]]
; VEC-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 2 x i1> @llvm.vp.icmp.nxv2p0(<vscale x 2 x ptr> [[VECTOR_GEP]], <vscale x 2 x ptr> [[BROADCAST_SPLAT]], metadata !"ult", <vscale x 2 x i1> splat (i1 true), i32 [[TMP18]])
; VEC-NEXT:    [[TMP23:%.*]] = extractelement <vscale x 2 x ptr> [[VECTOR_GEP]], i32 0
; VEC-NEXT:    [[TMP24:%.*]] = getelementptr i32, ptr [[TMP23]], i32 0
; VEC-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr align 4 [[TMP24]], <vscale x 2 x i1> [[VP_OP_ICMP]], i32 [[TMP18]])
; VEC-NEXT:    [[PREDPHI:%.*]] = call <vscale x 2 x i32> @llvm.vp.select.nxv2i32(<vscale x 2 x i1> [[VP_OP_ICMP]], <vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> zeroinitializer, i32 [[TMP18]])
; VEC-NEXT:    [[TMP25:%.*]] = getelementptr i32, ptr [[NEXT_GEP]], i32 0
; VEC-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> [[PREDPHI]], ptr align 4 [[TMP25]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP18]])
; VEC-NEXT:    [[TMP27:%.*]] = zext i32 [[TMP18]] to i64
; VEC-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP27]], [[EVL_BASED_IV1]]
; VEC-NEXT:    [[TMP29:%.*]] = mul i64 [[TMP19]], 1
; VEC-NEXT:    [[TMP28:%.*]] = mul i64 4, [[TMP29]]
; VEC-NEXT:    [[PTR_IND]] = getelementptr i8, ptr [[POINTER_PHI]], i64 [[TMP28]]
; VEC-NEXT:    [[TMP26:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP6]]
; VEC-NEXT:    br i1 [[TMP26]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VEC:       middle.block:
; VEC-NEXT:    br label [[FOR_END_LOOPEXIT:%.*]]
; VEC:       scalar.ph:
; VEC-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[C]], [[VECTOR_MEMCHECK]] ]
; VEC-NEXT:    [[BC_RESUME_VAL5:%.*]] = phi ptr [ [[A]], [[VECTOR_MEMCHECK]] ]
; VEC-NEXT:    br label [[FOR_BODY:%.*]]
; VEC:       for.body:
; VEC-NEXT:    [[C_ADDR_012:%.*]] = phi ptr [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INCDEC_PTR4:%.*]], [[FOR_INC:%.*]] ]
; VEC-NEXT:    [[A_ADDR_011:%.*]] = phi ptr [ [[BC_RESUME_VAL5]], [[SCALAR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC]] ]
; VEC-NEXT:    [[CMP3:%.*]] = icmp ult ptr [[A_ADDR_011]], [[ADD_PTR2]]
; VEC-NEXT:    br i1 [[CMP3]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; VEC:       if.then:
; VEC-NEXT:    [[TMP30:%.*]] = load i32, ptr [[A_ADDR_011]], align 4
; VEC-NEXT:    br label [[FOR_INC]]
; VEC:       for.inc:
; VEC-NEXT:    [[STOREMERGE:%.*]] = phi i32 [ [[TMP30]], [[IF_THEN]] ], [ 0, [[FOR_BODY]] ]
; VEC-NEXT:    store i32 [[STOREMERGE]], ptr [[C_ADDR_012]], align 4
; VEC-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[A_ADDR_011]], i64 4
; VEC-NEXT:    [[INCDEC_PTR4]] = getelementptr inbounds i8, ptr [[C_ADDR_012]], i64 4
; VEC-NEXT:    [[CMP:%.*]] = icmp ult ptr [[INCDEC_PTR4]], [[ADD_PTR]]
; VEC-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END_LOOPEXIT]], !llvm.loop [[LOOP4:![0-9]+]]
; VEC:       for.end.loopexit:
; VEC-NEXT:    br label [[FOR_END]]
; VEC:       for.end:
; VEC-NEXT:    ret i32 0
;
; UNSUPPORT-LABEL: @f(
; UNSUPPORT-NEXT:  entry:
; UNSUPPORT-NEXT:    [[IDX_EXT:%.*]] = zext i32 [[BSHIFT:%.*]] to i64
; UNSUPPORT-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[CLSU:%.*]], i64 [[IDX_EXT]]
; UNSUPPORT-NEXT:    [[CMP10:%.*]] = icmp ugt ptr [[ADD_PTR]], [[C:%.*]]
; UNSUPPORT-NEXT:    br i1 [[CMP10]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_END:%.*]]
; UNSUPPORT:       for.body.lr.ph:
; UNSUPPORT-NEXT:    [[IDX_EXT1:%.*]] = zext i32 [[ALENGTH:%.*]] to i64
; UNSUPPORT-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds i32, ptr [[ALSU:%.*]], i64 [[IDX_EXT1]]
; UNSUPPORT-NEXT:    br label [[FOR_BODY:%.*]]
; UNSUPPORT:       for.body:
; UNSUPPORT-NEXT:    [[C_ADDR_012:%.*]] = phi ptr [ [[C]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR4:%.*]], [[FOR_INC:%.*]] ]
; UNSUPPORT-NEXT:    [[A_ADDR_011:%.*]] = phi ptr [ [[A:%.*]], [[FOR_BODY_LR_PH]] ], [ [[INCDEC_PTR:%.*]], [[FOR_INC]] ]
; UNSUPPORT-NEXT:    [[CMP3:%.*]] = icmp ult ptr [[A_ADDR_011]], [[ADD_PTR2]]
; UNSUPPORT-NEXT:    br i1 [[CMP3]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; UNSUPPORT:       if.then:
; UNSUPPORT-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A_ADDR_011]], align 4
; UNSUPPORT-NEXT:    br label [[FOR_INC]]
; UNSUPPORT:       for.inc:
; UNSUPPORT-NEXT:    [[STOREMERGE:%.*]] = phi i32 [ [[TMP0]], [[IF_THEN]] ], [ 0, [[FOR_BODY]] ]
; UNSUPPORT-NEXT:    store i32 [[STOREMERGE]], ptr [[C_ADDR_012]], align 4
; UNSUPPORT-NEXT:    [[INCDEC_PTR]] = getelementptr inbounds i8, ptr [[A_ADDR_011]], i64 4
; UNSUPPORT-NEXT:    [[INCDEC_PTR4]] = getelementptr inbounds i8, ptr [[C_ADDR_012]], i64 4
; UNSUPPORT-NEXT:    [[CMP:%.*]] = icmp ult ptr [[INCDEC_PTR4]], [[ADD_PTR]]
; UNSUPPORT-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_END_LOOPEXIT:%.*]]
; UNSUPPORT:       for.end.loopexit:
; UNSUPPORT-NEXT:    br label [[FOR_END]]
; UNSUPPORT:       for.end:
; UNSUPPORT-NEXT:    ret i32 0
;
entry:
  %idx.ext = zext i32 %bshift to i64
  %add.ptr = getelementptr inbounds i32, ptr %clsu, i64 %idx.ext
  %cmp10 = icmp ugt ptr %add.ptr, %c
  br i1 %cmp10, label %for.body.lr.ph, label %for.end

for.body.lr.ph:                                   ; preds = %entry
  %idx.ext1 = zext i32 %alength to i64
  %add.ptr2 = getelementptr inbounds i32, ptr %alsu, i64 %idx.ext1
  br label %for.body

for.body:                                         ; preds = %for.body.lr.ph, %for.inc
  %c.addr.012 = phi ptr [ %c, %for.body.lr.ph ], [ %incdec.ptr4, %for.inc ]
  %a.addr.011 = phi ptr [ %a, %for.body.lr.ph ], [ %incdec.ptr, %for.inc ]
  %cmp3 = icmp ult ptr %a.addr.011, %add.ptr2
  br i1 %cmp3, label %if.then, label %for.inc

if.then:                                          ; preds = %for.body
  %0 = load i32, ptr %a.addr.011, align 4
  br label %for.inc

for.inc:                                          ; preds = %for.body, %if.then
  %storemerge = phi i32 [ %0, %if.then ], [ 0, %for.body ]
  store i32 %storemerge, ptr %c.addr.012, align 4
  %incdec.ptr = getelementptr inbounds i8, ptr %a.addr.011, i64 4
  %incdec.ptr4 = getelementptr inbounds i8, ptr %c.addr.012, i64 4
  %cmp = icmp ult ptr %incdec.ptr4, %add.ptr
  br i1 %cmp, label %for.body, label %for.end.loopexit

for.end.loopexit:                                 ; preds = %for.inc
  br label %for.end

for.end:                                          ; preds = %for.end.loopexit, %entry
  ret i32 0
}

