; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -mcpu=sifive-p670 -mtriple riscv64 -S %s | FileCheck %s

define  i32 @test_16x16(ptr %pix1_base, i32 %i_pix1, ptr %pix2_base, i32 %i_pix2) {
; CHECK-LABEL: define i32 @test_16x16(
; CHECK-SAME: ptr [[PIX1_BASE:%.*]], i32 [[I_PIX1:%.*]], ptr [[PIX2_BASE:%.*]], i32 [[I_PIX2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP:%.*]] = alloca [16 x [4 x i32]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 256, ptr nonnull [[TMP]])
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[PIX1_BASE]], i64 8
; CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds i8, ptr [[PIX2_BASE]], i64 8
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT65:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    br label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i32 [[I_PIX1]], 1
; CHECK-NEXT:    [[IDENT_CHECK1:%.*]] = icmp ne i32 [[I_PIX2]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = or i1 [[IDENT_CHECK]], [[IDENT_CHECK1]]
; CHECK-NEXT:    br i1 [[TMP4]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH1:.*]]
; CHECK:       [[VECTOR_PH1]]:
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 4, i1 true)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH1]] ], [ [[INDEX_EVL_NEXT120:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH1]] ], [ [[INDEX_EVL_NEXT120]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP83:%.*]] = sub i64 16, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP45:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP83]], i32 4, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], [[IDX_EXT]]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[ADD_PTR]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[N_RND_UP:%.*]] = mul i64 [[EVL_BASED_IV]], [[IDX_EXT65]]
; CHECK-NEXT:    [[NEXT_GEP6:%.*]] = getelementptr i8, ptr [[ADD_PTR1]], i64 [[N_RND_UP]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP3]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VECTOR_PH:%.*]] = getelementptr i8, ptr [[NEXT_GEP6]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD7:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[VECTOR_PH]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST8:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD7]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST]], <vscale x 4 x i32> [[VP_CAST8]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 4
; CHECK-NEXT:    [[TMP103:%.*]] = getelementptr inbounds i8, ptr [[TMP101]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD9:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP103]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST10:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD9]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP104:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 4
; CHECK-NEXT:    [[TMP105:%.*]] = getelementptr inbounds i8, ptr [[TMP104]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD11:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP105]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST12:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD11]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP13:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST10]], <vscale x 4 x i32> [[VP_CAST12]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP14:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP13]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP15:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP14]], <vscale x 4 x i32> [[VP_OP]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP106:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 1
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i8, ptr [[TMP106]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD16:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP17]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST17:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD16]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP107:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 1
; CHECK-NEXT:    [[TMP108:%.*]] = getelementptr inbounds i8, ptr [[TMP107]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD18:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP108]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST19:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD18]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP20:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST17]], <vscale x 4 x i32> [[VP_CAST19]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 5
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i8, ptr [[TMP20]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD21:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP21]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST22:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD21]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 5
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i8, ptr [[TMP109]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD23:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP23]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST24:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD23]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP25:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST22]], <vscale x 4 x i32> [[VP_CAST24]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP26:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP25]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP27:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP26]], <vscale x 4 x i32> [[VP_OP20]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 2
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i8, ptr [[TMP24]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD28:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP25]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST29:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD28]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 2
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i8, ptr [[TMP26]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD30:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP27]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST31:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD30]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP32:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST29]], <vscale x 4 x i32> [[VP_CAST31]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 6
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i8, ptr [[TMP28]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD33:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP29]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST34:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD33]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 6
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i8, ptr [[TMP30]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD35:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP31]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST36:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD35]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP37:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST34]], <vscale x 4 x i32> [[VP_CAST36]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP38:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP37]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP39:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP38]], <vscale x 4 x i32> [[VP_OP32]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 3
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i8, ptr [[TMP32]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD40:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP33]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST41:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD40]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 3
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr inbounds i8, ptr [[TMP34]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD42:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP35]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST43:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD42]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP44:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST41]], <vscale x 4 x i32> [[VP_CAST43]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 7
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i8, ptr [[TMP36]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD45:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP37]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST46:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD45]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 7
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr inbounds i8, ptr [[TMP38]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD47:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP39]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_CAST48:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD47]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP49:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST46]], <vscale x 4 x i32> [[VP_CAST48]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP50:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP49]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP51:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP50]], <vscale x 4 x i32> [[VP_OP44]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP52:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP27]], <vscale x 4 x i32> [[VP_OP15]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP53:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP15]], <vscale x 4 x i32> [[VP_OP27]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP54:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP51]], <vscale x 4 x i32> [[VP_OP39]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP55:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP39]], <vscale x 4 x i32> [[VP_OP51]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP115:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP54]], <vscale x 4 x i32> [[VP_OP52]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[TMP74:%.*]] = getelementptr inbounds [16 x [4 x i32]], ptr [[TMP]], i64 0, i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[VP_OP116:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP52]], <vscale x 4 x i32> [[VP_OP54]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP117:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP55]], <vscale x 4 x i32> [[VP_OP53]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[VP_OP118:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP53]], <vscale x 4 x i32> [[VP_OP55]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP45]])
; CHECK-NEXT:    [[INTERLEAVED_VEC119:%.*]] = call <vscale x 16 x i32> @llvm.vector.interleave4.nxv16i32(<vscale x 4 x i32> [[VP_OP115]], <vscale x 4 x i32> [[VP_OP117]], <vscale x 4 x i32> [[VP_OP116]], <vscale x 4 x i32> [[VP_OP118]])
; CHECK-NEXT:    [[TMP77:%.*]] = mul nuw nsw i32 [[TMP45]], 4
; CHECK-NEXT:    call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> [[INTERLEAVED_VEC119]], ptr align 4 [[TMP74]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP77]])
; CHECK-NEXT:    [[TMP57:%.*]] = zext i32 [[TMP45]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT120]] = add nuw i64 [[TMP57]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP80:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT120]], 16
; CHECK-NEXT:    br i1 [[TMP80]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[FOR_COND68_PREHEADER:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL57:%.*]] = phi ptr [ [[ADD_PTR]], %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL58:%.*]] = phi ptr [ [[ADD_PTR1]], %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND68_PREHEADER]]:
; CHECK-NEXT:    [[ARRAYIDX76:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 16
; CHECK-NEXT:    [[ARRAYIDX89:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 32
; CHECK-NEXT:    [[ARRAYIDX92:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 48
; CHECK-NEXT:    [[ARRAYIDX116:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 64
; CHECK-NEXT:    [[ARRAYIDX119:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 80
; CHECK-NEXT:    [[ARRAYIDX132:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 96
; CHECK-NEXT:    [[ARRAYIDX135:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 112
; CHECK-NEXT:    [[ARRAYIDX160:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 128
; CHECK-NEXT:    [[ARRAYIDX163:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 144
; CHECK-NEXT:    [[ARRAYIDX176:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 160
; CHECK-NEXT:    [[ARRAYIDX179:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 176
; CHECK-NEXT:    [[ARRAYIDX204:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 192
; CHECK-NEXT:    [[ARRAYIDX207:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 208
; CHECK-NEXT:    [[ARRAYIDX220:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 224
; CHECK-NEXT:    [[ARRAYIDX223:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 240
; CHECK-NEXT:    br label %[[FOR_BODY71:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX1_0453:%.*]] = phi ptr [ [[BC_RESUME_VAL57]], %[[SCALAR_PH]] ], [ [[ADD_PTR64:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX2_0452:%.*]] = phi ptr [ [[BC_RESUME_VAL58]], %[[SCALAR_PH]] ], [ [[ADD_PTR66:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP110:%.*]] = load i8, ptr [[PIX1_0453]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP110]] to i32
; CHECK-NEXT:    [[TMP111:%.*]] = load i8, ptr [[PIX2_0452]], align 1
; CHECK-NEXT:    [[CONV3:%.*]] = zext i8 [[TMP111]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[CONV]], [[CONV3]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 4
; CHECK-NEXT:    [[TMP112:%.*]] = load i8, ptr [[ARRAYIDX4]], align 1
; CHECK-NEXT:    [[CONV5:%.*]] = zext i8 [[TMP112]] to i32
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 4
; CHECK-NEXT:    [[TMP113:%.*]] = load i8, ptr [[ARRAYIDX6]], align 1
; CHECK-NEXT:    [[CONV7:%.*]] = zext i8 [[TMP113]] to i32
; CHECK-NEXT:    [[SUB8:%.*]] = sub nsw i32 [[CONV5]], [[CONV7]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nsw i32 [[SUB8]], 16
; CHECK-NEXT:    [[ADD20:%.*]] = add nsw i32 [[SHL]], [[SUB]]
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 1
; CHECK-NEXT:    [[TMP114:%.*]] = load i8, ptr [[ARRAYIDX9]], align 1
; CHECK-NEXT:    [[CONV10:%.*]] = zext i8 [[TMP114]] to i32
; CHECK-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 1
; CHECK-NEXT:    [[TMP115:%.*]] = load i8, ptr [[ARRAYIDX11]], align 1
; CHECK-NEXT:    [[CONV12:%.*]] = zext i8 [[TMP115]] to i32
; CHECK-NEXT:    [[SUB13:%.*]] = sub nsw i32 [[CONV10]], [[CONV12]]
; CHECK-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 5
; CHECK-NEXT:    [[TMP116:%.*]] = load i8, ptr [[ARRAYIDX14]], align 1
; CHECK-NEXT:    [[CONV15:%.*]] = zext i8 [[TMP116]] to i32
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 5
; CHECK-NEXT:    [[TMP118:%.*]] = load i8, ptr [[ARRAYIDX16]], align 1
; CHECK-NEXT:    [[CONV17:%.*]] = zext i8 [[TMP118]] to i32
; CHECK-NEXT:    [[SUB18:%.*]] = sub nsw i32 [[CONV15]], [[CONV17]]
; CHECK-NEXT:    [[SHL19:%.*]] = shl nsw i32 [[SUB18]], 16
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[SHL19]], [[SUB13]]
; CHECK-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 2
; CHECK-NEXT:    [[TMP121:%.*]] = load i8, ptr [[ARRAYIDX21]], align 1
; CHECK-NEXT:    [[CONV22:%.*]] = zext i8 [[TMP121]] to i32
; CHECK-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 2
; CHECK-NEXT:    [[TMP124:%.*]] = load i8, ptr [[ARRAYIDX23]], align 1
; CHECK-NEXT:    [[CONV24:%.*]] = zext i8 [[TMP124]] to i32
; CHECK-NEXT:    [[SUB25:%.*]] = sub nsw i32 [[CONV22]], [[CONV24]]
; CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 6
; CHECK-NEXT:    [[TMP130:%.*]] = load i8, ptr [[ARRAYIDX26]], align 1
; CHECK-NEXT:    [[CONV27:%.*]] = zext i8 [[TMP130]] to i32
; CHECK-NEXT:    [[ARRAYIDX28:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 6
; CHECK-NEXT:    [[TMP136:%.*]] = load i8, ptr [[ARRAYIDX28]], align 1
; CHECK-NEXT:    [[CONV29:%.*]] = zext i8 [[TMP136]] to i32
; CHECK-NEXT:    [[SUB30:%.*]] = sub nsw i32 [[CONV27]], [[CONV29]]
; CHECK-NEXT:    [[SHL31:%.*]] = shl nsw i32 [[SUB30]], 16
; CHECK-NEXT:    [[ADD44:%.*]] = add nsw i32 [[SHL31]], [[SUB25]]
; CHECK-NEXT:    [[ARRAYIDX33:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 3
; CHECK-NEXT:    [[TMP137:%.*]] = load i8, ptr [[ARRAYIDX33]], align 1
; CHECK-NEXT:    [[CONV34:%.*]] = zext i8 [[TMP137]] to i32
; CHECK-NEXT:    [[ARRAYIDX35:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 3
; CHECK-NEXT:    [[TMP138:%.*]] = load i8, ptr [[ARRAYIDX35]], align 1
; CHECK-NEXT:    [[CONV36:%.*]] = zext i8 [[TMP138]] to i32
; CHECK-NEXT:    [[SUB37:%.*]] = sub nsw i32 [[CONV34]], [[CONV36]]
; CHECK-NEXT:    [[ARRAYIDX38:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 7
; CHECK-NEXT:    [[TMP139:%.*]] = load i8, ptr [[ARRAYIDX38]], align 1
; CHECK-NEXT:    [[CONV39:%.*]] = zext i8 [[TMP139]] to i32
; CHECK-NEXT:    [[ARRAYIDX40:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 7
; CHECK-NEXT:    [[TMP140:%.*]] = load i8, ptr [[ARRAYIDX40]], align 1
; CHECK-NEXT:    [[CONV41:%.*]] = zext i8 [[TMP140]] to i32
; CHECK-NEXT:    [[SUB42:%.*]] = sub nsw i32 [[CONV39]], [[CONV41]]
; CHECK-NEXT:    [[SHL43:%.*]] = shl nsw i32 [[SUB42]], 16
; CHECK-NEXT:    [[ADD32:%.*]] = add nsw i32 [[SHL43]], [[SUB37]]
; CHECK-NEXT:    [[SUB46:%.*]] = add nsw i32 [[ADD]], [[ADD20]]
; CHECK-NEXT:    [[SUB47:%.*]] = sub nsw i32 [[ADD20]], [[ADD]]
; CHECK-NEXT:    [[SUB48:%.*]] = add nsw i32 [[ADD32]], [[ADD44]]
; CHECK-NEXT:    [[SUB49:%.*]] = sub nsw i32 [[ADD44]], [[ADD32]]
; CHECK-NEXT:    [[ADD49:%.*]] = add nsw i32 [[SUB48]], [[SUB46]]
; CHECK-NEXT:    [[ARRAYIDX50:%.*]] = getelementptr inbounds [16 x [4 x i32]], ptr [[TMP]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[ADD49]], ptr [[ARRAYIDX50]], align 8
; CHECK-NEXT:    [[SUB52:%.*]] = sub nsw i32 [[SUB46]], [[SUB48]]
; CHECK-NEXT:    [[ARRAYIDX55:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX50]], i64 8
; CHECK-NEXT:    store i32 [[SUB52]], ptr [[ARRAYIDX55]], align 8
; CHECK-NEXT:    [[ADD56:%.*]] = add nsw i32 [[SUB49]], [[SUB47]]
; CHECK-NEXT:    [[ARRAYIDX59:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX50]], i64 4
; CHECK-NEXT:    store i32 [[ADD56]], ptr [[ARRAYIDX59]], align 4
; CHECK-NEXT:    [[SUB60:%.*]] = sub nsw i32 [[SUB47]], [[SUB49]]
; CHECK-NEXT:    [[ARRAYIDX63:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX50]], i64 12
; CHECK-NEXT:    store i32 [[SUB60]], ptr [[ARRAYIDX63]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[ADD_PTR64]] = getelementptr inbounds i8, ptr [[PIX1_0453]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR66]] = getelementptr inbounds i8, ptr [[PIX2_0452]], i64 [[IDX_EXT65]]
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 16
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND68_PREHEADER]], label %[[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[FOR_COND_CLEANUP70:.*]]:
; CHECK-NEXT:    [[ADD114_LCSSA:%.*]] = phi i32 [ [[ADD114:%.*]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[ADD158_LCSSA:%.*]] = phi i32 [ [[ADD158:%.*]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[ADD202_LCSSA:%.*]] = phi i32 [ [[ADD202:%.*]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[ADD246_LCSSA:%.*]] = phi i32 [ [[ADD246:%.*]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[CONV251:%.*]] = and i32 [[ADD114_LCSSA]], 65535
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[ADD114_LCSSA]], 16
; CHECK-NEXT:    [[ADD252:%.*]] = add nuw nsw i32 [[CONV251]], [[SHR]]
; CHECK-NEXT:    [[SHR253:%.*]] = lshr i32 [[ADD252]], 1
; CHECK-NEXT:    [[CONV255:%.*]] = and i32 [[ADD158_LCSSA]], 65535
; CHECK-NEXT:    [[SHR256:%.*]] = lshr i32 [[ADD158_LCSSA]], 16
; CHECK-NEXT:    [[ADD257:%.*]] = add nuw nsw i32 [[CONV255]], [[SHR256]]
; CHECK-NEXT:    [[SHR258:%.*]] = lshr i32 [[ADD257]], 1
; CHECK-NEXT:    [[CONV261:%.*]] = and i32 [[ADD202_LCSSA]], 65535
; CHECK-NEXT:    [[SHR262:%.*]] = lshr i32 [[ADD202_LCSSA]], 16
; CHECK-NEXT:    [[ADD263:%.*]] = add nuw nsw i32 [[CONV261]], [[SHR262]]
; CHECK-NEXT:    [[SHR264:%.*]] = lshr i32 [[ADD263]], 1
; CHECK-NEXT:    [[CONV267:%.*]] = and i32 [[ADD246_LCSSA]], 65535
; CHECK-NEXT:    [[SHR268:%.*]] = lshr i32 [[ADD246_LCSSA]], 16
; CHECK-NEXT:    [[ADD269:%.*]] = add nuw nsw i32 [[CONV267]], [[SHR268]]
; CHECK-NEXT:    [[SHR270:%.*]] = lshr i32 [[ADD269]], 1
; CHECK-NEXT:    [[ADD259:%.*]] = add nuw nsw i32 [[SHR264]], [[SHR270]]
; CHECK-NEXT:    [[ADD265:%.*]] = add nuw nsw i32 [[ADD259]], [[SHR258]]
; CHECK-NEXT:    [[ADD271:%.*]] = add nuw nsw i32 [[ADD265]], [[SHR253]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 256, ptr nonnull [[TMP]])
; CHECK-NEXT:    ret i32 [[ADD271]]
; CHECK:       [[FOR_BODY71]]:
; CHECK-NEXT:    [[INDVARS_IV460:%.*]] = phi i64 [ 0, %[[FOR_COND68_PREHEADER]] ], [ [[INDVARS_IV_NEXT461:%.*]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[SUM0_0458:%.*]] = phi i32 [ 0, %[[FOR_COND68_PREHEADER]] ], [ [[ADD114]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[SUM1_0457:%.*]] = phi i32 [ 0, %[[FOR_COND68_PREHEADER]] ], [ [[ADD158]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[SUM2_0456:%.*]] = phi i32 [ 0, %[[FOR_COND68_PREHEADER]] ], [ [[ADD202]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[SUM3_0455:%.*]] = phi i32 [ 0, %[[FOR_COND68_PREHEADER]] ], [ [[ADD246]], %[[FOR_BODY71]] ]
; CHECK-NEXT:    [[ARRAYIDX75:%.*]] = getelementptr inbounds [4 x i32], ptr [[TMP]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP191:%.*]] = load i32, ptr [[ARRAYIDX75]], align 4
; CHECK-NEXT:    [[ARRAYIDX78:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX76]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP192:%.*]] = load i32, ptr [[ARRAYIDX78]], align 4
; CHECK-NEXT:    [[ADD79:%.*]] = add i32 [[TMP192]], [[TMP191]]
; CHECK-NEXT:    [[SUB87:%.*]] = sub i32 [[TMP191]], [[TMP192]]
; CHECK-NEXT:    [[ARRAYIDX91:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX89]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP193:%.*]] = load i32, ptr [[ARRAYIDX91]], align 4
; CHECK-NEXT:    [[ARRAYIDX94:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX92]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP194:%.*]] = load i32, ptr [[ARRAYIDX94]], align 4
; CHECK-NEXT:    [[ADD95:%.*]] = add i32 [[TMP194]], [[TMP193]]
; CHECK-NEXT:    [[SUB103:%.*]] = sub i32 [[TMP193]], [[TMP194]]
; CHECK-NEXT:    [[ADD104:%.*]] = add nsw i32 [[ADD95]], [[ADD79]]
; CHECK-NEXT:    [[SUB105:%.*]] = sub nsw i32 [[ADD79]], [[ADD95]]
; CHECK-NEXT:    [[ADD106:%.*]] = add nsw i32 [[SUB103]], [[SUB87]]
; CHECK-NEXT:    [[SUB107:%.*]] = sub nsw i32 [[SUB87]], [[SUB103]]
; CHECK-NEXT:    [[SHR_I:%.*]] = lshr i32 [[ADD104]], 15
; CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SHR_I]], 65537
; CHECK-NEXT:    [[MUL_I:%.*]] = mul nuw i32 [[AND_I]], 65535
; CHECK-NEXT:    [[ADD_I:%.*]] = add i32 [[MUL_I]], [[ADD104]]
; CHECK-NEXT:    [[XOR_I:%.*]] = xor i32 [[ADD_I]], [[MUL_I]]
; CHECK-NEXT:    [[SHR_I376:%.*]] = lshr i32 [[ADD106]], 15
; CHECK-NEXT:    [[AND_I377:%.*]] = and i32 [[SHR_I376]], 65537
; CHECK-NEXT:    [[MUL_I378:%.*]] = mul nuw i32 [[AND_I377]], 65535
; CHECK-NEXT:    [[ADD_I379:%.*]] = add i32 [[MUL_I378]], [[ADD106]]
; CHECK-NEXT:    [[XOR_I380:%.*]] = xor i32 [[ADD_I379]], [[MUL_I378]]
; CHECK-NEXT:    [[SHR_I381:%.*]] = lshr i32 [[SUB105]], 15
; CHECK-NEXT:    [[AND_I382:%.*]] = and i32 [[SHR_I381]], 65537
; CHECK-NEXT:    [[MUL_I383:%.*]] = mul nuw i32 [[AND_I382]], 65535
; CHECK-NEXT:    [[ADD_I384:%.*]] = add i32 [[MUL_I383]], [[SUB105]]
; CHECK-NEXT:    [[XOR_I385:%.*]] = xor i32 [[ADD_I384]], [[MUL_I383]]
; CHECK-NEXT:    [[SHR_I386:%.*]] = lshr i32 [[SUB107]], 15
; CHECK-NEXT:    [[AND_I387:%.*]] = and i32 [[SHR_I386]], 65537
; CHECK-NEXT:    [[MUL_I388:%.*]] = mul nuw i32 [[AND_I387]], 65535
; CHECK-NEXT:    [[ADD_I389:%.*]] = add i32 [[MUL_I388]], [[SUB107]]
; CHECK-NEXT:    [[XOR_I390:%.*]] = xor i32 [[ADD_I389]], [[MUL_I388]]
; CHECK-NEXT:    [[ADD109:%.*]] = add i32 [[XOR_I380]], [[SUM0_0458]]
; CHECK-NEXT:    [[ADD111:%.*]] = add i32 [[ADD109]], [[XOR_I]]
; CHECK-NEXT:    [[ADD113:%.*]] = add i32 [[ADD111]], [[XOR_I385]]
; CHECK-NEXT:    [[ADD114]] = add i32 [[ADD113]], [[XOR_I390]]
; CHECK-NEXT:    [[ARRAYIDX118:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX116]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP195:%.*]] = load i32, ptr [[ARRAYIDX118]], align 4
; CHECK-NEXT:    [[ARRAYIDX121:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX119]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP196:%.*]] = load i32, ptr [[ARRAYIDX121]], align 4
; CHECK-NEXT:    [[ADD122:%.*]] = add i32 [[TMP196]], [[TMP195]]
; CHECK-NEXT:    [[SUB130:%.*]] = sub i32 [[TMP195]], [[TMP196]]
; CHECK-NEXT:    [[ARRAYIDX134:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX132]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP197:%.*]] = load i32, ptr [[ARRAYIDX134]], align 4
; CHECK-NEXT:    [[ARRAYIDX137:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX135]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP198:%.*]] = load i32, ptr [[ARRAYIDX137]], align 4
; CHECK-NEXT:    [[ADD138:%.*]] = add i32 [[TMP198]], [[TMP197]]
; CHECK-NEXT:    [[SUB146:%.*]] = sub i32 [[TMP197]], [[TMP198]]
; CHECK-NEXT:    [[ADD147:%.*]] = add nsw i32 [[ADD138]], [[ADD122]]
; CHECK-NEXT:    [[SUB148:%.*]] = sub nsw i32 [[ADD122]], [[ADD138]]
; CHECK-NEXT:    [[ADD149:%.*]] = add nsw i32 [[SUB146]], [[SUB130]]
; CHECK-NEXT:    [[SUB150:%.*]] = sub nsw i32 [[SUB130]], [[SUB146]]
; CHECK-NEXT:    [[SHR_I391:%.*]] = lshr i32 [[ADD147]], 15
; CHECK-NEXT:    [[AND_I392:%.*]] = and i32 [[SHR_I391]], 65537
; CHECK-NEXT:    [[MUL_I393:%.*]] = mul nuw i32 [[AND_I392]], 65535
; CHECK-NEXT:    [[ADD_I394:%.*]] = add i32 [[MUL_I393]], [[ADD147]]
; CHECK-NEXT:    [[XOR_I395:%.*]] = xor i32 [[ADD_I394]], [[MUL_I393]]
; CHECK-NEXT:    [[SHR_I396:%.*]] = lshr i32 [[ADD149]], 15
; CHECK-NEXT:    [[AND_I397:%.*]] = and i32 [[SHR_I396]], 65537
; CHECK-NEXT:    [[MUL_I398:%.*]] = mul nuw i32 [[AND_I397]], 65535
; CHECK-NEXT:    [[ADD_I399:%.*]] = add i32 [[MUL_I398]], [[ADD149]]
; CHECK-NEXT:    [[XOR_I400:%.*]] = xor i32 [[ADD_I399]], [[MUL_I398]]
; CHECK-NEXT:    [[SHR_I401:%.*]] = lshr i32 [[SUB148]], 15
; CHECK-NEXT:    [[AND_I402:%.*]] = and i32 [[SHR_I401]], 65537
; CHECK-NEXT:    [[MUL_I403:%.*]] = mul nuw i32 [[AND_I402]], 65535
; CHECK-NEXT:    [[ADD_I404:%.*]] = add i32 [[MUL_I403]], [[SUB148]]
; CHECK-NEXT:    [[XOR_I405:%.*]] = xor i32 [[ADD_I404]], [[MUL_I403]]
; CHECK-NEXT:    [[SHR_I406:%.*]] = lshr i32 [[SUB150]], 15
; CHECK-NEXT:    [[AND_I407:%.*]] = and i32 [[SHR_I406]], 65537
; CHECK-NEXT:    [[MUL_I408:%.*]] = mul nuw i32 [[AND_I407]], 65535
; CHECK-NEXT:    [[ADD_I409:%.*]] = add i32 [[MUL_I408]], [[SUB150]]
; CHECK-NEXT:    [[XOR_I410:%.*]] = xor i32 [[ADD_I409]], [[MUL_I408]]
; CHECK-NEXT:    [[ADD153:%.*]] = add i32 [[XOR_I400]], [[SUM1_0457]]
; CHECK-NEXT:    [[ADD155:%.*]] = add i32 [[ADD153]], [[XOR_I395]]
; CHECK-NEXT:    [[ADD157:%.*]] = add i32 [[ADD155]], [[XOR_I405]]
; CHECK-NEXT:    [[ADD158]] = add i32 [[ADD157]], [[XOR_I410]]
; CHECK-NEXT:    [[ARRAYIDX162:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX160]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP199:%.*]] = load i32, ptr [[ARRAYIDX162]], align 4
; CHECK-NEXT:    [[ARRAYIDX165:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX163]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP200:%.*]] = load i32, ptr [[ARRAYIDX165]], align 4
; CHECK-NEXT:    [[ADD166:%.*]] = add i32 [[TMP200]], [[TMP199]]
; CHECK-NEXT:    [[SUB174:%.*]] = sub i32 [[TMP199]], [[TMP200]]
; CHECK-NEXT:    [[ARRAYIDX178:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX176]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP201:%.*]] = load i32, ptr [[ARRAYIDX178]], align 4
; CHECK-NEXT:    [[ARRAYIDX181:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX179]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP202:%.*]] = load i32, ptr [[ARRAYIDX181]], align 4
; CHECK-NEXT:    [[ADD182:%.*]] = add i32 [[TMP202]], [[TMP201]]
; CHECK-NEXT:    [[SUB190:%.*]] = sub i32 [[TMP201]], [[TMP202]]
; CHECK-NEXT:    [[ADD191:%.*]] = add nsw i32 [[ADD182]], [[ADD166]]
; CHECK-NEXT:    [[SUB192:%.*]] = sub nsw i32 [[ADD166]], [[ADD182]]
; CHECK-NEXT:    [[ADD193:%.*]] = add nsw i32 [[SUB190]], [[SUB174]]
; CHECK-NEXT:    [[SUB194:%.*]] = sub nsw i32 [[SUB174]], [[SUB190]]
; CHECK-NEXT:    [[SHR_I411:%.*]] = lshr i32 [[ADD191]], 15
; CHECK-NEXT:    [[AND_I412:%.*]] = and i32 [[SHR_I411]], 65537
; CHECK-NEXT:    [[MUL_I413:%.*]] = mul nuw i32 [[AND_I412]], 65535
; CHECK-NEXT:    [[ADD_I414:%.*]] = add i32 [[MUL_I413]], [[ADD191]]
; CHECK-NEXT:    [[XOR_I415:%.*]] = xor i32 [[ADD_I414]], [[MUL_I413]]
; CHECK-NEXT:    [[SHR_I416:%.*]] = lshr i32 [[ADD193]], 15
; CHECK-NEXT:    [[AND_I417:%.*]] = and i32 [[SHR_I416]], 65537
; CHECK-NEXT:    [[MUL_I418:%.*]] = mul nuw i32 [[AND_I417]], 65535
; CHECK-NEXT:    [[ADD_I419:%.*]] = add i32 [[MUL_I418]], [[ADD193]]
; CHECK-NEXT:    [[XOR_I420:%.*]] = xor i32 [[ADD_I419]], [[MUL_I418]]
; CHECK-NEXT:    [[SHR_I421:%.*]] = lshr i32 [[SUB192]], 15
; CHECK-NEXT:    [[AND_I422:%.*]] = and i32 [[SHR_I421]], 65537
; CHECK-NEXT:    [[MUL_I423:%.*]] = mul nuw i32 [[AND_I422]], 65535
; CHECK-NEXT:    [[ADD_I424:%.*]] = add i32 [[MUL_I423]], [[SUB192]]
; CHECK-NEXT:    [[XOR_I425:%.*]] = xor i32 [[ADD_I424]], [[MUL_I423]]
; CHECK-NEXT:    [[SHR_I426:%.*]] = lshr i32 [[SUB194]], 15
; CHECK-NEXT:    [[AND_I427:%.*]] = and i32 [[SHR_I426]], 65537
; CHECK-NEXT:    [[MUL_I428:%.*]] = mul nuw i32 [[AND_I427]], 65535
; CHECK-NEXT:    [[ADD_I429:%.*]] = add i32 [[MUL_I428]], [[SUB194]]
; CHECK-NEXT:    [[XOR_I430:%.*]] = xor i32 [[ADD_I429]], [[MUL_I428]]
; CHECK-NEXT:    [[ADD197:%.*]] = add i32 [[XOR_I420]], [[SUM2_0456]]
; CHECK-NEXT:    [[ADD199:%.*]] = add i32 [[ADD197]], [[XOR_I415]]
; CHECK-NEXT:    [[ADD201:%.*]] = add i32 [[ADD199]], [[XOR_I425]]
; CHECK-NEXT:    [[ADD202]] = add i32 [[ADD201]], [[XOR_I430]]
; CHECK-NEXT:    [[ARRAYIDX206:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX204]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP203:%.*]] = load i32, ptr [[ARRAYIDX206]], align 4
; CHECK-NEXT:    [[ARRAYIDX209:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX207]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP204:%.*]] = load i32, ptr [[ARRAYIDX209]], align 4
; CHECK-NEXT:    [[ADD210:%.*]] = add i32 [[TMP204]], [[TMP203]]
; CHECK-NEXT:    [[SUB218:%.*]] = sub i32 [[TMP203]], [[TMP204]]
; CHECK-NEXT:    [[ARRAYIDX222:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX220]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP205:%.*]] = load i32, ptr [[ARRAYIDX222]], align 4
; CHECK-NEXT:    [[ARRAYIDX225:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARRAYIDX223]], i64 0, i64 [[INDVARS_IV460]]
; CHECK-NEXT:    [[TMP206:%.*]] = load i32, ptr [[ARRAYIDX225]], align 4
; CHECK-NEXT:    [[ADD226:%.*]] = add i32 [[TMP206]], [[TMP205]]
; CHECK-NEXT:    [[SUB234:%.*]] = sub i32 [[TMP205]], [[TMP206]]
; CHECK-NEXT:    [[ADD235:%.*]] = add nsw i32 [[ADD226]], [[ADD210]]
; CHECK-NEXT:    [[SUB236:%.*]] = sub nsw i32 [[ADD210]], [[ADD226]]
; CHECK-NEXT:    [[ADD237:%.*]] = add nsw i32 [[SUB234]], [[SUB218]]
; CHECK-NEXT:    [[SUB238:%.*]] = sub nsw i32 [[SUB218]], [[SUB234]]
; CHECK-NEXT:    [[SHR_I431:%.*]] = lshr i32 [[ADD235]], 15
; CHECK-NEXT:    [[AND_I432:%.*]] = and i32 [[SHR_I431]], 65537
; CHECK-NEXT:    [[MUL_I433:%.*]] = mul nuw i32 [[AND_I432]], 65535
; CHECK-NEXT:    [[ADD_I434:%.*]] = add i32 [[MUL_I433]], [[ADD235]]
; CHECK-NEXT:    [[XOR_I435:%.*]] = xor i32 [[ADD_I434]], [[MUL_I433]]
; CHECK-NEXT:    [[SHR_I436:%.*]] = lshr i32 [[ADD237]], 15
; CHECK-NEXT:    [[AND_I437:%.*]] = and i32 [[SHR_I436]], 65537
; CHECK-NEXT:    [[MUL_I438:%.*]] = mul nuw i32 [[AND_I437]], 65535
; CHECK-NEXT:    [[ADD_I439:%.*]] = add i32 [[MUL_I438]], [[ADD237]]
; CHECK-NEXT:    [[XOR_I440:%.*]] = xor i32 [[ADD_I439]], [[MUL_I438]]
; CHECK-NEXT:    [[SHR_I441:%.*]] = lshr i32 [[SUB236]], 15
; CHECK-NEXT:    [[AND_I442:%.*]] = and i32 [[SHR_I441]], 65537
; CHECK-NEXT:    [[MUL_I443:%.*]] = mul nuw i32 [[AND_I442]], 65535
; CHECK-NEXT:    [[ADD_I444:%.*]] = add i32 [[MUL_I443]], [[SUB236]]
; CHECK-NEXT:    [[XOR_I445:%.*]] = xor i32 [[ADD_I444]], [[MUL_I443]]
; CHECK-NEXT:    [[SHR_I446:%.*]] = lshr i32 [[SUB238]], 15
; CHECK-NEXT:    [[AND_I447:%.*]] = and i32 [[SHR_I446]], 65537
; CHECK-NEXT:    [[MUL_I448:%.*]] = mul nuw i32 [[AND_I447]], 65535
; CHECK-NEXT:    [[ADD_I449:%.*]] = add i32 [[MUL_I448]], [[SUB238]]
; CHECK-NEXT:    [[XOR_I450:%.*]] = xor i32 [[ADD_I449]], [[MUL_I448]]
; CHECK-NEXT:    [[ADD241:%.*]] = add i32 [[XOR_I440]], [[SUM3_0455]]
; CHECK-NEXT:    [[ADD243:%.*]] = add i32 [[ADD241]], [[XOR_I435]]
; CHECK-NEXT:    [[ADD245:%.*]] = add i32 [[ADD243]], [[XOR_I445]]
; CHECK-NEXT:    [[ADD246]] = add i32 [[ADD245]], [[XOR_I450]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT461]] = add nuw nsw i64 [[INDVARS_IV460]], 1
; CHECK-NEXT:    [[EXITCOND463_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT461]], 4
; CHECK-NEXT:    br i1 [[EXITCOND463_NOT]], label %[[FOR_COND_CLEANUP70]], label %[[FOR_BODY71]]
;
entry:
  %tmp = alloca [16 x [4 x i32]], align 8
  call void @llvm.lifetime.start.p0(i64 256, ptr nonnull %tmp) #2
  %add.ptr = getelementptr inbounds i8, ptr %pix1_base, i64 8
  %add.ptr1 = getelementptr inbounds i8, ptr %pix2_base, i64 8
  %idx.ext = sext i32 %i_pix1 to i64
  %idx.ext65 = sext i32 %i_pix2 to i64
  br label %for.body

for.cond68.preheader:                             ; preds = %for.body
  %arrayidx76 = getelementptr inbounds i8, ptr %tmp, i64 16
  %arrayidx89 = getelementptr inbounds i8, ptr %tmp, i64 32
  %arrayidx92 = getelementptr inbounds i8, ptr %tmp, i64 48
  %arrayidx116 = getelementptr inbounds i8, ptr %tmp, i64 64
  %arrayidx119 = getelementptr inbounds i8, ptr %tmp, i64 80
  %arrayidx132 = getelementptr inbounds i8, ptr %tmp, i64 96
  %arrayidx135 = getelementptr inbounds i8, ptr %tmp, i64 112
  %arrayidx160 = getelementptr inbounds i8, ptr %tmp, i64 128
  %arrayidx163 = getelementptr inbounds i8, ptr %tmp, i64 144
  %arrayidx176 = getelementptr inbounds i8, ptr %tmp, i64 160
  %arrayidx179 = getelementptr inbounds i8, ptr %tmp, i64 176
  %arrayidx204 = getelementptr inbounds i8, ptr %tmp, i64 192
  %arrayidx207 = getelementptr inbounds i8, ptr %tmp, i64 208
  %arrayidx220 = getelementptr inbounds i8, ptr %tmp, i64 224
  %arrayidx223 = getelementptr inbounds i8, ptr %tmp, i64 240
  br label %for.body71

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %pix1.0453 = phi ptr [ %add.ptr, %entry ], [ %add.ptr64, %for.body ]
  %pix2.0452 = phi ptr [ %add.ptr1, %entry ], [ %add.ptr66, %for.body ]
  %0 = load i8, ptr %pix1.0453, align 1
  %conv = zext i8 %0 to i32
  %1 = load i8, ptr %pix2.0452, align 1
  %conv3 = zext i8 %1 to i32
  %sub = sub nsw i32 %conv, %conv3
  %arrayidx4 = getelementptr inbounds i8, ptr %pix1.0453, i64 4
  %2 = load i8, ptr %arrayidx4, align 1
  %conv5 = zext i8 %2 to i32
  %arrayidx6 = getelementptr inbounds i8, ptr %pix2.0452, i64 4
  %3 = load i8, ptr %arrayidx6, align 1
  %conv7 = zext i8 %3 to i32
  %sub8 = sub nsw i32 %conv5, %conv7
  %shl = shl nsw i32 %sub8, 16
  %add = add nsw i32 %shl, %sub
  %arrayidx9 = getelementptr inbounds i8, ptr %pix1.0453, i64 1
  %4 = load i8, ptr %arrayidx9, align 1
  %conv10 = zext i8 %4 to i32
  %arrayidx11 = getelementptr inbounds i8, ptr %pix2.0452, i64 1
  %5 = load i8, ptr %arrayidx11, align 1
  %conv12 = zext i8 %5 to i32
  %sub13 = sub nsw i32 %conv10, %conv12
  %arrayidx14 = getelementptr inbounds i8, ptr %pix1.0453, i64 5
  %6 = load i8, ptr %arrayidx14, align 1
  %conv15 = zext i8 %6 to i32
  %arrayidx16 = getelementptr inbounds i8, ptr %pix2.0452, i64 5
  %7 = load i8, ptr %arrayidx16, align 1
  %conv17 = zext i8 %7 to i32
  %sub18 = sub nsw i32 %conv15, %conv17
  %shl19 = shl nsw i32 %sub18, 16
  %add20 = add nsw i32 %shl19, %sub13
  %arrayidx21 = getelementptr inbounds i8, ptr %pix1.0453, i64 2
  %8 = load i8, ptr %arrayidx21, align 1
  %conv22 = zext i8 %8 to i32
  %arrayidx23 = getelementptr inbounds i8, ptr %pix2.0452, i64 2
  %9 = load i8, ptr %arrayidx23, align 1
  %conv24 = zext i8 %9 to i32
  %sub25 = sub nsw i32 %conv22, %conv24
  %arrayidx26 = getelementptr inbounds i8, ptr %pix1.0453, i64 6
  %10 = load i8, ptr %arrayidx26, align 1
  %conv27 = zext i8 %10 to i32
  %arrayidx28 = getelementptr inbounds i8, ptr %pix2.0452, i64 6
  %11 = load i8, ptr %arrayidx28, align 1
  %conv29 = zext i8 %11 to i32
  %sub30 = sub nsw i32 %conv27, %conv29
  %shl31 = shl nsw i32 %sub30, 16
  %add32 = add nsw i32 %shl31, %sub25
  %arrayidx33 = getelementptr inbounds i8, ptr %pix1.0453, i64 3
  %12 = load i8, ptr %arrayidx33, align 1
  %conv34 = zext i8 %12 to i32
  %arrayidx35 = getelementptr inbounds i8, ptr %pix2.0452, i64 3
  %13 = load i8, ptr %arrayidx35, align 1
  %conv36 = zext i8 %13 to i32
  %sub37 = sub nsw i32 %conv34, %conv36
  %arrayidx38 = getelementptr inbounds i8, ptr %pix1.0453, i64 7
  %14 = load i8, ptr %arrayidx38, align 1
  %conv39 = zext i8 %14 to i32
  %arrayidx40 = getelementptr inbounds i8, ptr %pix2.0452, i64 7
  %15 = load i8, ptr %arrayidx40, align 1
  %conv41 = zext i8 %15 to i32
  %sub42 = sub nsw i32 %conv39, %conv41
  %shl43 = shl nsw i32 %sub42, 16
  %add44 = add nsw i32 %shl43, %sub37
  %add45 = add nsw i32 %add20, %add
  %sub46 = sub nsw i32 %add, %add20
  %add47 = add nsw i32 %add44, %add32
  %sub48 = sub nsw i32 %add32, %add44
  %add49 = add nsw i32 %add47, %add45
  %arrayidx50 = getelementptr inbounds [16 x [4 x i32]], ptr %tmp, i64 0, i64 %indvars.iv
  store i32 %add49, ptr %arrayidx50, align 8
  %sub52 = sub nsw i32 %add45, %add47
  %arrayidx55 = getelementptr inbounds i8, ptr %arrayidx50, i64 8
  store i32 %sub52, ptr %arrayidx55, align 8
  %add56 = add nsw i32 %sub48, %sub46
  %arrayidx59 = getelementptr inbounds i8, ptr %arrayidx50, i64 4
  store i32 %add56, ptr %arrayidx59, align 4
  %sub60 = sub nsw i32 %sub46, %sub48
  %arrayidx63 = getelementptr inbounds i8, ptr %arrayidx50, i64 12
  store i32 %sub60, ptr %arrayidx63, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %add.ptr64 = getelementptr inbounds i8, ptr %pix1.0453, i64 %idx.ext
  %add.ptr66 = getelementptr inbounds i8, ptr %pix2.0452, i64 %idx.ext65
  %exitcond.not = icmp eq i64 %indvars.iv.next, 16
  br i1 %exitcond.not, label %for.cond68.preheader, label %for.body

for.cond.cleanup70:                               ; preds = %for.body71
  %add114.lcssa = phi i32 [ %add114, %for.body71 ]
  %add158.lcssa = phi i32 [ %add158, %for.body71 ]
  %add202.lcssa = phi i32 [ %add202, %for.body71 ]
  %add246.lcssa = phi i32 [ %add246, %for.body71 ]
  %conv251 = and i32 %add114.lcssa, 65535
  %shr = lshr i32 %add114.lcssa, 16
  %add252 = add nuw nsw i32 %conv251, %shr
  %shr253 = lshr i32 %add252, 1
  %conv255 = and i32 %add158.lcssa, 65535
  %shr256 = lshr i32 %add158.lcssa, 16
  %add257 = add nuw nsw i32 %conv255, %shr256
  %shr258 = lshr i32 %add257, 1
  %conv261 = and i32 %add202.lcssa, 65535
  %shr262 = lshr i32 %add202.lcssa, 16
  %add263 = add nuw nsw i32 %conv261, %shr262
  %shr264 = lshr i32 %add263, 1
  %conv267 = and i32 %add246.lcssa, 65535
  %shr268 = lshr i32 %add246.lcssa, 16
  %add269 = add nuw nsw i32 %conv267, %shr268
  %shr270 = lshr i32 %add269, 1
  %add259 = add nuw nsw i32 %shr264, %shr270
  %add265 = add nuw nsw i32 %add259, %shr258
  %add271 = add nuw nsw i32 %add265, %shr253
  call void @llvm.lifetime.end.p0(i64 256, ptr nonnull %tmp) #2
  ret i32 %add271

for.body71:                                       ; preds = %for.cond68.preheader, %for.body71
  %indvars.iv460 = phi i64 [ 0, %for.cond68.preheader ], [ %indvars.iv.next461, %for.body71 ]
  %sum0.0458 = phi i32 [ 0, %for.cond68.preheader ], [ %add114, %for.body71 ]
  %sum1.0457 = phi i32 [ 0, %for.cond68.preheader ], [ %add158, %for.body71 ]
  %sum2.0456 = phi i32 [ 0, %for.cond68.preheader ], [ %add202, %for.body71 ]
  %sum3.0455 = phi i32 [ 0, %for.cond68.preheader ], [ %add246, %for.body71 ]
  %arrayidx75 = getelementptr inbounds [4 x i32], ptr %tmp, i64 0, i64 %indvars.iv460
  %16 = load i32, ptr %arrayidx75, align 4
  %arrayidx78 = getelementptr inbounds [4 x i32], ptr %arrayidx76, i64 0, i64 %indvars.iv460
  %17 = load i32, ptr %arrayidx78, align 4
  %add79 = add i32 %17, %16
  %sub87 = sub i32 %16, %17
  %arrayidx91 = getelementptr inbounds [4 x i32], ptr %arrayidx89, i64 0, i64 %indvars.iv460
  %18 = load i32, ptr %arrayidx91, align 4
  %arrayidx94 = getelementptr inbounds [4 x i32], ptr %arrayidx92, i64 0, i64 %indvars.iv460
  %19 = load i32, ptr %arrayidx94, align 4
  %add95 = add i32 %19, %18
  %sub103 = sub i32 %18, %19
  %add104 = add nsw i32 %add95, %add79
  %sub105 = sub nsw i32 %add79, %add95
  %add106 = add nsw i32 %sub103, %sub87
  %sub107 = sub nsw i32 %sub87, %sub103
  %shr.i = lshr i32 %add104, 15
  %and.i = and i32 %shr.i, 65537
  %mul.i = mul nuw i32 %and.i, 65535
  %add.i = add i32 %mul.i, %add104
  %xor.i = xor i32 %add.i, %mul.i
  %shr.i376 = lshr i32 %add106, 15
  %and.i377 = and i32 %shr.i376, 65537
  %mul.i378 = mul nuw i32 %and.i377, 65535
  %add.i379 = add i32 %mul.i378, %add106
  %xor.i380 = xor i32 %add.i379, %mul.i378
  %shr.i381 = lshr i32 %sub105, 15
  %and.i382 = and i32 %shr.i381, 65537
  %mul.i383 = mul nuw i32 %and.i382, 65535
  %add.i384 = add i32 %mul.i383, %sub105
  %xor.i385 = xor i32 %add.i384, %mul.i383
  %shr.i386 = lshr i32 %sub107, 15
  %and.i387 = and i32 %shr.i386, 65537
  %mul.i388 = mul nuw i32 %and.i387, 65535
  %add.i389 = add i32 %mul.i388, %sub107
  %xor.i390 = xor i32 %add.i389, %mul.i388
  %add109 = add i32 %xor.i380, %sum0.0458
  %add111 = add i32 %add109, %xor.i
  %add113 = add i32 %add111, %xor.i385
  %add114 = add i32 %add113, %xor.i390
  %arrayidx118 = getelementptr inbounds [4 x i32], ptr %arrayidx116, i64 0, i64 %indvars.iv460
  %20 = load i32, ptr %arrayidx118, align 4
  %arrayidx121 = getelementptr inbounds [4 x i32], ptr %arrayidx119, i64 0, i64 %indvars.iv460
  %21 = load i32, ptr %arrayidx121, align 4
  %add122 = add i32 %21, %20
  %sub130 = sub i32 %20, %21
  %arrayidx134 = getelementptr inbounds [4 x i32], ptr %arrayidx132, i64 0, i64 %indvars.iv460
  %22 = load i32, ptr %arrayidx134, align 4
  %arrayidx137 = getelementptr inbounds [4 x i32], ptr %arrayidx135, i64 0, i64 %indvars.iv460
  %23 = load i32, ptr %arrayidx137, align 4
  %add138 = add i32 %23, %22
  %sub146 = sub i32 %22, %23
  %add147 = add nsw i32 %add138, %add122
  %sub148 = sub nsw i32 %add122, %add138
  %add149 = add nsw i32 %sub146, %sub130
  %sub150 = sub nsw i32 %sub130, %sub146
  %shr.i391 = lshr i32 %add147, 15
  %and.i392 = and i32 %shr.i391, 65537
  %mul.i393 = mul nuw i32 %and.i392, 65535
  %add.i394 = add i32 %mul.i393, %add147
  %xor.i395 = xor i32 %add.i394, %mul.i393
  %shr.i396 = lshr i32 %add149, 15
  %and.i397 = and i32 %shr.i396, 65537
  %mul.i398 = mul nuw i32 %and.i397, 65535
  %add.i399 = add i32 %mul.i398, %add149
  %xor.i400 = xor i32 %add.i399, %mul.i398
  %shr.i401 = lshr i32 %sub148, 15
  %and.i402 = and i32 %shr.i401, 65537
  %mul.i403 = mul nuw i32 %and.i402, 65535
  %add.i404 = add i32 %mul.i403, %sub148
  %xor.i405 = xor i32 %add.i404, %mul.i403
  %shr.i406 = lshr i32 %sub150, 15
  %and.i407 = and i32 %shr.i406, 65537
  %mul.i408 = mul nuw i32 %and.i407, 65535
  %add.i409 = add i32 %mul.i408, %sub150
  %xor.i410 = xor i32 %add.i409, %mul.i408
  %add153 = add i32 %xor.i400, %sum1.0457
  %add155 = add i32 %add153, %xor.i395
  %add157 = add i32 %add155, %xor.i405
  %add158 = add i32 %add157, %xor.i410
  %arrayidx162 = getelementptr inbounds [4 x i32], ptr %arrayidx160, i64 0, i64 %indvars.iv460
  %24 = load i32, ptr %arrayidx162, align 4
  %arrayidx165 = getelementptr inbounds [4 x i32], ptr %arrayidx163, i64 0, i64 %indvars.iv460
  %25 = load i32, ptr %arrayidx165, align 4
  %add166 = add i32 %25, %24
  %sub174 = sub i32 %24, %25
  %arrayidx178 = getelementptr inbounds [4 x i32], ptr %arrayidx176, i64 0, i64 %indvars.iv460
  %26 = load i32, ptr %arrayidx178, align 4
  %arrayidx181 = getelementptr inbounds [4 x i32], ptr %arrayidx179, i64 0, i64 %indvars.iv460
  %27 = load i32, ptr %arrayidx181, align 4
  %add182 = add i32 %27, %26
  %sub190 = sub i32 %26, %27
  %add191 = add nsw i32 %add182, %add166
  %sub192 = sub nsw i32 %add166, %add182
  %add193 = add nsw i32 %sub190, %sub174
  %sub194 = sub nsw i32 %sub174, %sub190
  %shr.i411 = lshr i32 %add191, 15
  %and.i412 = and i32 %shr.i411, 65537
  %mul.i413 = mul nuw i32 %and.i412, 65535
  %add.i414 = add i32 %mul.i413, %add191
  %xor.i415 = xor i32 %add.i414, %mul.i413
  %shr.i416 = lshr i32 %add193, 15
  %and.i417 = and i32 %shr.i416, 65537
  %mul.i418 = mul nuw i32 %and.i417, 65535
  %add.i419 = add i32 %mul.i418, %add193
  %xor.i420 = xor i32 %add.i419, %mul.i418
  %shr.i421 = lshr i32 %sub192, 15
  %and.i422 = and i32 %shr.i421, 65537
  %mul.i423 = mul nuw i32 %and.i422, 65535
  %add.i424 = add i32 %mul.i423, %sub192
  %xor.i425 = xor i32 %add.i424, %mul.i423
  %shr.i426 = lshr i32 %sub194, 15
  %and.i427 = and i32 %shr.i426, 65537
  %mul.i428 = mul nuw i32 %and.i427, 65535
  %add.i429 = add i32 %mul.i428, %sub194
  %xor.i430 = xor i32 %add.i429, %mul.i428
  %add197 = add i32 %xor.i420, %sum2.0456
  %add199 = add i32 %add197, %xor.i415
  %add201 = add i32 %add199, %xor.i425
  %add202 = add i32 %add201, %xor.i430
  %arrayidx206 = getelementptr inbounds [4 x i32], ptr %arrayidx204, i64 0, i64 %indvars.iv460
  %28 = load i32, ptr %arrayidx206, align 4
  %arrayidx209 = getelementptr inbounds [4 x i32], ptr %arrayidx207, i64 0, i64 %indvars.iv460
  %29 = load i32, ptr %arrayidx209, align 4
  %add210 = add i32 %29, %28
  %sub218 = sub i32 %28, %29
  %arrayidx222 = getelementptr inbounds [4 x i32], ptr %arrayidx220, i64 0, i64 %indvars.iv460
  %30 = load i32, ptr %arrayidx222, align 4
  %arrayidx225 = getelementptr inbounds [4 x i32], ptr %arrayidx223, i64 0, i64 %indvars.iv460
  %31 = load i32, ptr %arrayidx225, align 4
  %add226 = add i32 %31, %30
  %sub234 = sub i32 %30, %31
  %add235 = add nsw i32 %add226, %add210
  %sub236 = sub nsw i32 %add210, %add226
  %add237 = add nsw i32 %sub234, %sub218
  %sub238 = sub nsw i32 %sub218, %sub234
  %shr.i431 = lshr i32 %add235, 15
  %and.i432 = and i32 %shr.i431, 65537
  %mul.i433 = mul nuw i32 %and.i432, 65535
  %add.i434 = add i32 %mul.i433, %add235
  %xor.i435 = xor i32 %add.i434, %mul.i433
  %shr.i436 = lshr i32 %add237, 15
  %and.i437 = and i32 %shr.i436, 65537
  %mul.i438 = mul nuw i32 %and.i437, 65535
  %add.i439 = add i32 %mul.i438, %add237
  %xor.i440 = xor i32 %add.i439, %mul.i438
  %shr.i441 = lshr i32 %sub236, 15
  %and.i442 = and i32 %shr.i441, 65537
  %mul.i443 = mul nuw i32 %and.i442, 65535
  %add.i444 = add i32 %mul.i443, %sub236
  %xor.i445 = xor i32 %add.i444, %mul.i443
  %shr.i446 = lshr i32 %sub238, 15
  %and.i447 = and i32 %shr.i446, 65537
  %mul.i448 = mul nuw i32 %and.i447, 65535
  %add.i449 = add i32 %mul.i448, %sub238
  %xor.i450 = xor i32 %add.i449, %mul.i448
  %add241 = add i32 %xor.i440, %sum3.0455
  %add243 = add i32 %add241, %xor.i435
  %add245 = add i32 %add243, %xor.i445
  %add246 = add i32 %add245, %xor.i450
  %indvars.iv.next461 = add nuw nsw i64 %indvars.iv460, 1
  %exitcond463.not = icmp eq i64 %indvars.iv.next461, 4
  br i1 %exitcond463.not, label %for.cond.cleanup70, label %for.body71
}

define i32 @test_8x8(ptr %pix1_base, i32 %i_pix1, ptr %pix2_base, i32 %i_pix2){
; CHECK-LABEL: define i32 @test_8x8(
; CHECK-SAME: ptr [[PIX1_BASE:%.*]], i32 [[I_PIX1:%.*]], ptr [[PIX2_BASE:%.*]], i32 [[I_PIX2:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP:%.*]] = alloca [8 x [4 x i32]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 128, ptr nonnull [[TMP]])
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[PIX1_BASE]], i64 8
; CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds i8, ptr [[PIX2_BASE]], i64 8
; CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[I_PIX1]] to i64
; CHECK-NEXT:    [[IDX_EXT65:%.*]] = sext i32 [[I_PIX2]] to i64
; CHECK-NEXT:    br label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i32 [[I_PIX1]], 1
; CHECK-NEXT:    [[IDENT_CHECK1:%.*]] = icmp ne i32 [[I_PIX2]], 1
; CHECK-NEXT:    [[TMP81:%.*]] = or i1 [[IDENT_CHECK]], [[IDENT_CHECK1]]
; CHECK-NEXT:    br i1 [[TMP81]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP48:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 16, i32 4, i1 true)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT120:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT120]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP84:%.*]] = sub i64 16, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP85:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP84]], i32 4, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], [[IDX_EXT]]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[ADD_PTR]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[OFFSET_IDX5:%.*]] = mul i64 [[EVL_BASED_IV]], [[IDX_EXT65]]
; CHECK-NEXT:    [[NEXT_GEP6:%.*]] = getelementptr i8, ptr [[ADD_PTR1]], i64 [[OFFSET_IDX5]]
; CHECK-NEXT:    [[TMP91:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP91]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP92:%.*]] = getelementptr i8, ptr [[NEXT_GEP6]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD7:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP92]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST8:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD7]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST]], <vscale x 4 x i32> [[VP_CAST8]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP93:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 4
; CHECK-NEXT:    [[TMP94:%.*]] = getelementptr inbounds i8, ptr [[TMP93]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD9:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP94]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST10:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD9]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP95:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 4
; CHECK-NEXT:    [[TMP96:%.*]] = getelementptr inbounds i8, ptr [[TMP95]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD11:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP96]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST12:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD11]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP13:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST10]], <vscale x 4 x i32> [[VP_CAST12]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP14:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP13]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP15:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP14]], <vscale x 4 x i32> [[VP_OP]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP97:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 1
; CHECK-NEXT:    [[TMP98:%.*]] = getelementptr inbounds i8, ptr [[TMP97]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD16:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP98]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST17:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD16]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP99:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 1
; CHECK-NEXT:    [[TMP100:%.*]] = getelementptr inbounds i8, ptr [[TMP99]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD18:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP100]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST19:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD18]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP20:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST17]], <vscale x 4 x i32> [[VP_CAST19]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP101:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 5
; CHECK-NEXT:    [[TMP102:%.*]] = getelementptr inbounds i8, ptr [[TMP101]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD21:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP102]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST22:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD21]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP103:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 5
; CHECK-NEXT:    [[TMP104:%.*]] = getelementptr inbounds i8, ptr [[TMP103]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD23:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP104]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST24:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD23]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP25:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST22]], <vscale x 4 x i32> [[VP_CAST24]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP26:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP25]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP27:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP26]], <vscale x 4 x i32> [[VP_OP20]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP105:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 2
; CHECK-NEXT:    [[TMP106:%.*]] = getelementptr inbounds i8, ptr [[TMP105]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD28:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP106]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST29:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD28]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP107:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 2
; CHECK-NEXT:    [[TMP108:%.*]] = getelementptr inbounds i8, ptr [[TMP107]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD30:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP108]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST31:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD30]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP32:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST29]], <vscale x 4 x i32> [[VP_CAST31]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 6
; CHECK-NEXT:    [[TMP110:%.*]] = getelementptr inbounds i8, ptr [[TMP109]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD33:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP110]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST34:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD33]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP111:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 6
; CHECK-NEXT:    [[TMP112:%.*]] = getelementptr inbounds i8, ptr [[TMP111]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD35:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP112]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST36:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD35]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP37:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST34]], <vscale x 4 x i32> [[VP_CAST36]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP38:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP37]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP39:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP38]], <vscale x 4 x i32> [[VP_OP32]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP113:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 3
; CHECK-NEXT:    [[TMP114:%.*]] = getelementptr inbounds i8, ptr [[TMP113]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD40:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP114]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST41:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD40]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP115:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 3
; CHECK-NEXT:    [[TMP116:%.*]] = getelementptr inbounds i8, ptr [[TMP115]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD42:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP116]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST43:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD42]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP44:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST41]], <vscale x 4 x i32> [[VP_CAST43]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP117:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 7
; CHECK-NEXT:    [[TMP118:%.*]] = getelementptr inbounds i8, ptr [[TMP117]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD45:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP118]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST46:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD45]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP119:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 7
; CHECK-NEXT:    [[TMP120:%.*]] = getelementptr inbounds i8, ptr [[TMP119]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD47:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP120]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_CAST48:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD47]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP49:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_CAST46]], <vscale x 4 x i32> [[VP_CAST48]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP50:%.*]] = call <vscale x 4 x i32> @llvm.vp.shl.nxv4i32(<vscale x 4 x i32> [[VP_OP49]], <vscale x 4 x i32> splat (i32 16), <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP51:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP50]], <vscale x 4 x i32> [[VP_OP44]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP52:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP27]], <vscale x 4 x i32> [[VP_OP15]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP53:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP15]], <vscale x 4 x i32> [[VP_OP27]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP54:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP51]], <vscale x 4 x i32> [[VP_OP39]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP55:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP39]], <vscale x 4 x i32> [[VP_OP51]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP115:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP54]], <vscale x 4 x i32> [[VP_OP52]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[TMP74:%.*]] = getelementptr inbounds [8 x [4 x i32]], ptr [[TMP]], i64 0, i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[VP_OP116:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP52]], <vscale x 4 x i32> [[VP_OP54]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP117:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP55]], <vscale x 4 x i32> [[VP_OP53]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[VP_OP118:%.*]] = call <vscale x 4 x i32> @llvm.vp.sub.nxv4i32(<vscale x 4 x i32> [[VP_OP53]], <vscale x 4 x i32> [[VP_OP55]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP85]])
; CHECK-NEXT:    [[INTERLEAVED_VEC119:%.*]] = call <vscale x 16 x i32> @llvm.vector.interleave4.nxv16i32(<vscale x 4 x i32> [[VP_OP115]], <vscale x 4 x i32> [[VP_OP117]], <vscale x 4 x i32> [[VP_OP116]], <vscale x 4 x i32> [[VP_OP118]])
; CHECK-NEXT:    [[TMP77:%.*]] = mul nuw nsw i32 [[TMP85]], 4
; CHECK-NEXT:    call void @llvm.vp.store.nxv16i32.p0(<vscale x 16 x i32> [[INTERLEAVED_VEC119]], ptr align 4 [[TMP74]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP77]])
; CHECK-NEXT:    [[TMP49:%.*]] = zext i32 [[TMP85]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT120]] = add nuw i64 [[TMP49]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP80:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT120]], 16
; CHECK-NEXT:    br i1 [[TMP80]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[FOR_COND68_PREHEADER:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL57:%.*]] = phi ptr [ [[ADD_PTR]], %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL58:%.*]] = phi ptr [ [[ADD_PTR1]], %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND68_PREHEADER]]:
; CHECK-NEXT:    [[ARRAYIDX76:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 16
; CHECK-NEXT:    [[ARRAYIDX89:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 32
; CHECK-NEXT:    [[ARRAYIDX92:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 48
; CHECK-NEXT:    [[ARRAYIDX116:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 64
; CHECK-NEXT:    [[ARRAYIDX119:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 80
; CHECK-NEXT:    [[ARRAYIDX132:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 96
; CHECK-NEXT:    [[ARRAYIDX135:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 112
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[TMP]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX76]], align 4
; CHECK-NEXT:    [[ADD79:%.*]] = add i32 [[TMP1]], [[TMP0]]
; CHECK-NEXT:    [[SUB87:%.*]] = sub i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ARRAYIDX89]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX92]], align 4
; CHECK-NEXT:    [[ADD95:%.*]] = add i32 [[TMP3]], [[TMP2]]
; CHECK-NEXT:    [[SUB103:%.*]] = sub i32 [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[ADD104:%.*]] = add nsw i32 [[ADD95]], [[ADD79]]
; CHECK-NEXT:    [[SUB105:%.*]] = sub nsw i32 [[ADD79]], [[ADD95]]
; CHECK-NEXT:    [[ADD106:%.*]] = add nsw i32 [[SUB103]], [[SUB87]]
; CHECK-NEXT:    [[SUB107:%.*]] = sub nsw i32 [[SUB87]], [[SUB103]]
; CHECK-NEXT:    [[SHR_I:%.*]] = lshr i32 [[ADD104]], 15
; CHECK-NEXT:    [[AND_I:%.*]] = and i32 [[SHR_I]], 65537
; CHECK-NEXT:    [[MUL_I:%.*]] = mul nuw i32 [[AND_I]], 65535
; CHECK-NEXT:    [[ADD_I:%.*]] = add i32 [[MUL_I]], [[ADD104]]
; CHECK-NEXT:    [[XOR_I:%.*]] = xor i32 [[ADD_I]], [[MUL_I]]
; CHECK-NEXT:    [[SHR_I240:%.*]] = lshr i32 [[ADD106]], 15
; CHECK-NEXT:    [[AND_I241:%.*]] = and i32 [[SHR_I240]], 65537
; CHECK-NEXT:    [[MUL_I242:%.*]] = mul nuw i32 [[AND_I241]], 65535
; CHECK-NEXT:    [[ADD_I243:%.*]] = add i32 [[MUL_I242]], [[ADD106]]
; CHECK-NEXT:    [[XOR_I244:%.*]] = xor i32 [[ADD_I243]], [[MUL_I242]]
; CHECK-NEXT:    [[SHR_I245:%.*]] = lshr i32 [[SUB105]], 15
; CHECK-NEXT:    [[AND_I246:%.*]] = and i32 [[SHR_I245]], 65537
; CHECK-NEXT:    [[MUL_I247:%.*]] = mul nuw i32 [[AND_I246]], 65535
; CHECK-NEXT:    [[ADD_I248:%.*]] = add i32 [[MUL_I247]], [[SUB105]]
; CHECK-NEXT:    [[XOR_I249:%.*]] = xor i32 [[ADD_I248]], [[MUL_I247]]
; CHECK-NEXT:    [[SHR_I250:%.*]] = lshr i32 [[SUB107]], 15
; CHECK-NEXT:    [[AND_I251:%.*]] = and i32 [[SHR_I250]], 65537
; CHECK-NEXT:    [[MUL_I252:%.*]] = mul nuw i32 [[AND_I251]], 65535
; CHECK-NEXT:    [[ADD_I253:%.*]] = add i32 [[MUL_I252]], [[SUB107]]
; CHECK-NEXT:    [[XOR_I254:%.*]] = xor i32 [[ADD_I253]], [[MUL_I252]]
; CHECK-NEXT:    [[ADD111:%.*]] = add i32 [[XOR_I244]], [[XOR_I]]
; CHECK-NEXT:    [[ADD113:%.*]] = add i32 [[ADD111]], [[XOR_I249]]
; CHECK-NEXT:    [[ADD114:%.*]] = add i32 [[ADD113]], [[XOR_I254]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX116]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX119]], align 4
; CHECK-NEXT:    [[ADD122:%.*]] = add i32 [[TMP5]], [[TMP4]]
; CHECK-NEXT:    [[SUB130:%.*]] = sub i32 [[TMP4]], [[TMP5]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARRAYIDX132]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX135]], align 4
; CHECK-NEXT:    [[ADD138:%.*]] = add i32 [[TMP7]], [[TMP6]]
; CHECK-NEXT:    [[SUB146:%.*]] = sub i32 [[TMP6]], [[TMP7]]
; CHECK-NEXT:    [[ADD147:%.*]] = add nsw i32 [[ADD138]], [[ADD122]]
; CHECK-NEXT:    [[SUB148:%.*]] = sub nsw i32 [[ADD122]], [[ADD138]]
; CHECK-NEXT:    [[ADD149:%.*]] = add nsw i32 [[SUB146]], [[SUB130]]
; CHECK-NEXT:    [[SUB150:%.*]] = sub nsw i32 [[SUB130]], [[SUB146]]
; CHECK-NEXT:    [[SHR_I255:%.*]] = lshr i32 [[ADD147]], 15
; CHECK-NEXT:    [[AND_I256:%.*]] = and i32 [[SHR_I255]], 65537
; CHECK-NEXT:    [[MUL_I257:%.*]] = mul nuw i32 [[AND_I256]], 65535
; CHECK-NEXT:    [[ADD_I258:%.*]] = add i32 [[MUL_I257]], [[ADD147]]
; CHECK-NEXT:    [[XOR_I259:%.*]] = xor i32 [[ADD_I258]], [[MUL_I257]]
; CHECK-NEXT:    [[SHR_I260:%.*]] = lshr i32 [[ADD149]], 15
; CHECK-NEXT:    [[AND_I261:%.*]] = and i32 [[SHR_I260]], 65537
; CHECK-NEXT:    [[MUL_I262:%.*]] = mul nuw i32 [[AND_I261]], 65535
; CHECK-NEXT:    [[ADD_I263:%.*]] = add i32 [[MUL_I262]], [[ADD149]]
; CHECK-NEXT:    [[XOR_I264:%.*]] = xor i32 [[ADD_I263]], [[MUL_I262]]
; CHECK-NEXT:    [[SHR_I265:%.*]] = lshr i32 [[SUB148]], 15
; CHECK-NEXT:    [[AND_I266:%.*]] = and i32 [[SHR_I265]], 65537
; CHECK-NEXT:    [[MUL_I267:%.*]] = mul nuw i32 [[AND_I266]], 65535
; CHECK-NEXT:    [[ADD_I268:%.*]] = add i32 [[MUL_I267]], [[SUB148]]
; CHECK-NEXT:    [[XOR_I269:%.*]] = xor i32 [[ADD_I268]], [[MUL_I267]]
; CHECK-NEXT:    [[SHR_I270:%.*]] = lshr i32 [[SUB150]], 15
; CHECK-NEXT:    [[AND_I271:%.*]] = and i32 [[SHR_I270]], 65537
; CHECK-NEXT:    [[MUL_I272:%.*]] = mul nuw i32 [[AND_I271]], 65535
; CHECK-NEXT:    [[ADD_I273:%.*]] = add i32 [[MUL_I272]], [[SUB150]]
; CHECK-NEXT:    [[XOR_I274:%.*]] = xor i32 [[ADD_I273]], [[MUL_I272]]
; CHECK-NEXT:    [[ADD155:%.*]] = add i32 [[XOR_I264]], [[XOR_I259]]
; CHECK-NEXT:    [[ADD157:%.*]] = add i32 [[ADD155]], [[XOR_I269]]
; CHECK-NEXT:    [[ADD158:%.*]] = add i32 [[ADD157]], [[XOR_I274]]
; CHECK-NEXT:    [[ARRAYIDX75_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX75_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX78_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 20
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[ARRAYIDX78_1]], align 4
; CHECK-NEXT:    [[ADD79_1:%.*]] = add i32 [[TMP9]], [[TMP8]]
; CHECK-NEXT:    [[SUB87_1:%.*]] = sub i32 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[ARRAYIDX91_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 36
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARRAYIDX91_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX94_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 52
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[ARRAYIDX94_1]], align 4
; CHECK-NEXT:    [[ADD95_1:%.*]] = add i32 [[TMP11]], [[TMP10]]
; CHECK-NEXT:    [[SUB103_1:%.*]] = sub i32 [[TMP10]], [[TMP11]]
; CHECK-NEXT:    [[ADD104_1:%.*]] = add nsw i32 [[ADD95_1]], [[ADD79_1]]
; CHECK-NEXT:    [[SUB105_1:%.*]] = sub nsw i32 [[ADD79_1]], [[ADD95_1]]
; CHECK-NEXT:    [[ADD106_1:%.*]] = add nsw i32 [[SUB103_1]], [[SUB87_1]]
; CHECK-NEXT:    [[SUB107_1:%.*]] = sub nsw i32 [[SUB87_1]], [[SUB103_1]]
; CHECK-NEXT:    [[SHR_I_1:%.*]] = lshr i32 [[ADD104_1]], 15
; CHECK-NEXT:    [[AND_I_1:%.*]] = and i32 [[SHR_I_1]], 65537
; CHECK-NEXT:    [[MUL_I_1:%.*]] = mul nuw i32 [[AND_I_1]], 65535
; CHECK-NEXT:    [[ADD_I_1:%.*]] = add i32 [[MUL_I_1]], [[ADD104_1]]
; CHECK-NEXT:    [[XOR_I_1:%.*]] = xor i32 [[ADD_I_1]], [[MUL_I_1]]
; CHECK-NEXT:    [[SHR_I240_1:%.*]] = lshr i32 [[ADD106_1]], 15
; CHECK-NEXT:    [[AND_I241_1:%.*]] = and i32 [[SHR_I240_1]], 65537
; CHECK-NEXT:    [[MUL_I242_1:%.*]] = mul nuw i32 [[AND_I241_1]], 65535
; CHECK-NEXT:    [[ADD_I243_1:%.*]] = add i32 [[MUL_I242_1]], [[ADD106_1]]
; CHECK-NEXT:    [[XOR_I244_1:%.*]] = xor i32 [[ADD_I243_1]], [[MUL_I242_1]]
; CHECK-NEXT:    [[SHR_I245_1:%.*]] = lshr i32 [[SUB105_1]], 15
; CHECK-NEXT:    [[AND_I246_1:%.*]] = and i32 [[SHR_I245_1]], 65537
; CHECK-NEXT:    [[MUL_I247_1:%.*]] = mul nuw i32 [[AND_I246_1]], 65535
; CHECK-NEXT:    [[ADD_I248_1:%.*]] = add i32 [[MUL_I247_1]], [[SUB105_1]]
; CHECK-NEXT:    [[XOR_I249_1:%.*]] = xor i32 [[ADD_I248_1]], [[MUL_I247_1]]
; CHECK-NEXT:    [[SHR_I250_1:%.*]] = lshr i32 [[SUB107_1]], 15
; CHECK-NEXT:    [[AND_I251_1:%.*]] = and i32 [[SHR_I250_1]], 65537
; CHECK-NEXT:    [[MUL_I252_1:%.*]] = mul nuw i32 [[AND_I251_1]], 65535
; CHECK-NEXT:    [[ADD_I253_1:%.*]] = add i32 [[MUL_I252_1]], [[SUB107_1]]
; CHECK-NEXT:    [[XOR_I254_1:%.*]] = xor i32 [[ADD_I253_1]], [[MUL_I252_1]]
; CHECK-NEXT:    [[ADD109_1:%.*]] = add i32 [[XOR_I244_1]], [[ADD114]]
; CHECK-NEXT:    [[ADD111_1:%.*]] = add i32 [[ADD109_1]], [[XOR_I_1]]
; CHECK-NEXT:    [[ADD113_1:%.*]] = add i32 [[ADD111_1]], [[XOR_I249_1]]
; CHECK-NEXT:    [[ADD114_1:%.*]] = add i32 [[ADD113_1]], [[XOR_I254_1]]
; CHECK-NEXT:    [[ARRAYIDX118_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 68
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX118_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX121_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 84
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX121_1]], align 4
; CHECK-NEXT:    [[ADD122_1:%.*]] = add i32 [[TMP13]], [[TMP12]]
; CHECK-NEXT:    [[SUB130_1:%.*]] = sub i32 [[TMP12]], [[TMP13]]
; CHECK-NEXT:    [[ARRAYIDX134_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 100
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[ARRAYIDX134_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX137_1:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 116
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[ARRAYIDX137_1]], align 4
; CHECK-NEXT:    [[ADD138_1:%.*]] = add i32 [[TMP15]], [[TMP14]]
; CHECK-NEXT:    [[SUB146_1:%.*]] = sub i32 [[TMP14]], [[TMP15]]
; CHECK-NEXT:    [[ADD147_1:%.*]] = add nsw i32 [[ADD138_1]], [[ADD122_1]]
; CHECK-NEXT:    [[SUB148_1:%.*]] = sub nsw i32 [[ADD122_1]], [[ADD138_1]]
; CHECK-NEXT:    [[ADD149_1:%.*]] = add nsw i32 [[SUB146_1]], [[SUB130_1]]
; CHECK-NEXT:    [[SUB150_1:%.*]] = sub nsw i32 [[SUB130_1]], [[SUB146_1]]
; CHECK-NEXT:    [[SHR_I255_1:%.*]] = lshr i32 [[ADD147_1]], 15
; CHECK-NEXT:    [[AND_I256_1:%.*]] = and i32 [[SHR_I255_1]], 65537
; CHECK-NEXT:    [[MUL_I257_1:%.*]] = mul nuw i32 [[AND_I256_1]], 65535
; CHECK-NEXT:    [[ADD_I258_1:%.*]] = add i32 [[MUL_I257_1]], [[ADD147_1]]
; CHECK-NEXT:    [[XOR_I259_1:%.*]] = xor i32 [[ADD_I258_1]], [[MUL_I257_1]]
; CHECK-NEXT:    [[SHR_I260_1:%.*]] = lshr i32 [[ADD149_1]], 15
; CHECK-NEXT:    [[AND_I261_1:%.*]] = and i32 [[SHR_I260_1]], 65537
; CHECK-NEXT:    [[MUL_I262_1:%.*]] = mul nuw i32 [[AND_I261_1]], 65535
; CHECK-NEXT:    [[ADD_I263_1:%.*]] = add i32 [[MUL_I262_1]], [[ADD149_1]]
; CHECK-NEXT:    [[XOR_I264_1:%.*]] = xor i32 [[ADD_I263_1]], [[MUL_I262_1]]
; CHECK-NEXT:    [[SHR_I265_1:%.*]] = lshr i32 [[SUB148_1]], 15
; CHECK-NEXT:    [[AND_I266_1:%.*]] = and i32 [[SHR_I265_1]], 65537
; CHECK-NEXT:    [[MUL_I267_1:%.*]] = mul nuw i32 [[AND_I266_1]], 65535
; CHECK-NEXT:    [[ADD_I268_1:%.*]] = add i32 [[MUL_I267_1]], [[SUB148_1]]
; CHECK-NEXT:    [[XOR_I269_1:%.*]] = xor i32 [[ADD_I268_1]], [[MUL_I267_1]]
; CHECK-NEXT:    [[SHR_I270_1:%.*]] = lshr i32 [[SUB150_1]], 15
; CHECK-NEXT:    [[AND_I271_1:%.*]] = and i32 [[SHR_I270_1]], 65537
; CHECK-NEXT:    [[MUL_I272_1:%.*]] = mul nuw i32 [[AND_I271_1]], 65535
; CHECK-NEXT:    [[ADD_I273_1:%.*]] = add i32 [[MUL_I272_1]], [[SUB150_1]]
; CHECK-NEXT:    [[XOR_I274_1:%.*]] = xor i32 [[ADD_I273_1]], [[MUL_I272_1]]
; CHECK-NEXT:    [[ADD153_1:%.*]] = add i32 [[XOR_I264_1]], [[ADD158]]
; CHECK-NEXT:    [[ADD155_1:%.*]] = add i32 [[ADD153_1]], [[XOR_I259_1]]
; CHECK-NEXT:    [[ADD157_1:%.*]] = add i32 [[ADD155_1]], [[XOR_I269_1]]
; CHECK-NEXT:    [[ADD158_1:%.*]] = add i32 [[ADD157_1]], [[XOR_I274_1]]
; CHECK-NEXT:    [[ARRAYIDX75_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 8
; CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[ARRAYIDX75_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX78_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 24
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[ARRAYIDX78_2]], align 4
; CHECK-NEXT:    [[ADD79_2:%.*]] = add i32 [[TMP17]], [[TMP16]]
; CHECK-NEXT:    [[SUB87_2:%.*]] = sub i32 [[TMP16]], [[TMP17]]
; CHECK-NEXT:    [[ARRAYIDX91_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 40
; CHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[ARRAYIDX91_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX94_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 56
; CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[ARRAYIDX94_2]], align 4
; CHECK-NEXT:    [[ADD95_2:%.*]] = add i32 [[TMP19]], [[TMP18]]
; CHECK-NEXT:    [[SUB103_2:%.*]] = sub i32 [[TMP18]], [[TMP19]]
; CHECK-NEXT:    [[ADD104_2:%.*]] = add nsw i32 [[ADD95_2]], [[ADD79_2]]
; CHECK-NEXT:    [[SUB105_2:%.*]] = sub nsw i32 [[ADD79_2]], [[ADD95_2]]
; CHECK-NEXT:    [[ADD106_2:%.*]] = add nsw i32 [[SUB103_2]], [[SUB87_2]]
; CHECK-NEXT:    [[SUB107_2:%.*]] = sub nsw i32 [[SUB87_2]], [[SUB103_2]]
; CHECK-NEXT:    [[SHR_I_2:%.*]] = lshr i32 [[ADD104_2]], 15
; CHECK-NEXT:    [[AND_I_2:%.*]] = and i32 [[SHR_I_2]], 65537
; CHECK-NEXT:    [[MUL_I_2:%.*]] = mul nuw i32 [[AND_I_2]], 65535
; CHECK-NEXT:    [[ADD_I_2:%.*]] = add i32 [[MUL_I_2]], [[ADD104_2]]
; CHECK-NEXT:    [[XOR_I_2:%.*]] = xor i32 [[ADD_I_2]], [[MUL_I_2]]
; CHECK-NEXT:    [[SHR_I240_2:%.*]] = lshr i32 [[ADD106_2]], 15
; CHECK-NEXT:    [[AND_I241_2:%.*]] = and i32 [[SHR_I240_2]], 65537
; CHECK-NEXT:    [[MUL_I242_2:%.*]] = mul nuw i32 [[AND_I241_2]], 65535
; CHECK-NEXT:    [[ADD_I243_2:%.*]] = add i32 [[MUL_I242_2]], [[ADD106_2]]
; CHECK-NEXT:    [[XOR_I244_2:%.*]] = xor i32 [[ADD_I243_2]], [[MUL_I242_2]]
; CHECK-NEXT:    [[SHR_I245_2:%.*]] = lshr i32 [[SUB105_2]], 15
; CHECK-NEXT:    [[AND_I246_2:%.*]] = and i32 [[SHR_I245_2]], 65537
; CHECK-NEXT:    [[MUL_I247_2:%.*]] = mul nuw i32 [[AND_I246_2]], 65535
; CHECK-NEXT:    [[ADD_I248_2:%.*]] = add i32 [[MUL_I247_2]], [[SUB105_2]]
; CHECK-NEXT:    [[XOR_I249_2:%.*]] = xor i32 [[ADD_I248_2]], [[MUL_I247_2]]
; CHECK-NEXT:    [[SHR_I250_2:%.*]] = lshr i32 [[SUB107_2]], 15
; CHECK-NEXT:    [[AND_I251_2:%.*]] = and i32 [[SHR_I250_2]], 65537
; CHECK-NEXT:    [[MUL_I252_2:%.*]] = mul nuw i32 [[AND_I251_2]], 65535
; CHECK-NEXT:    [[ADD_I253_2:%.*]] = add i32 [[MUL_I252_2]], [[SUB107_2]]
; CHECK-NEXT:    [[XOR_I254_2:%.*]] = xor i32 [[ADD_I253_2]], [[MUL_I252_2]]
; CHECK-NEXT:    [[ADD109_2:%.*]] = add i32 [[XOR_I244_2]], [[ADD114_1]]
; CHECK-NEXT:    [[ADD111_2:%.*]] = add i32 [[ADD109_2]], [[XOR_I_2]]
; CHECK-NEXT:    [[ADD113_2:%.*]] = add i32 [[ADD111_2]], [[XOR_I249_2]]
; CHECK-NEXT:    [[ADD114_2:%.*]] = add i32 [[ADD113_2]], [[XOR_I254_2]]
; CHECK-NEXT:    [[ARRAYIDX118_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 72
; CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[ARRAYIDX118_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX121_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 88
; CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[ARRAYIDX121_2]], align 4
; CHECK-NEXT:    [[ADD122_2:%.*]] = add i32 [[TMP21]], [[TMP20]]
; CHECK-NEXT:    [[SUB130_2:%.*]] = sub i32 [[TMP20]], [[TMP21]]
; CHECK-NEXT:    [[ARRAYIDX134_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 104
; CHECK-NEXT:    [[TMP22:%.*]] = load i32, ptr [[ARRAYIDX134_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX137_2:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 120
; CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[ARRAYIDX137_2]], align 4
; CHECK-NEXT:    [[ADD138_2:%.*]] = add i32 [[TMP23]], [[TMP22]]
; CHECK-NEXT:    [[SUB146_2:%.*]] = sub i32 [[TMP22]], [[TMP23]]
; CHECK-NEXT:    [[ADD147_2:%.*]] = add nsw i32 [[ADD138_2]], [[ADD122_2]]
; CHECK-NEXT:    [[SUB148_2:%.*]] = sub nsw i32 [[ADD122_2]], [[ADD138_2]]
; CHECK-NEXT:    [[ADD149_2:%.*]] = add nsw i32 [[SUB146_2]], [[SUB130_2]]
; CHECK-NEXT:    [[SUB150_2:%.*]] = sub nsw i32 [[SUB130_2]], [[SUB146_2]]
; CHECK-NEXT:    [[SHR_I255_2:%.*]] = lshr i32 [[ADD147_2]], 15
; CHECK-NEXT:    [[AND_I256_2:%.*]] = and i32 [[SHR_I255_2]], 65537
; CHECK-NEXT:    [[MUL_I257_2:%.*]] = mul nuw i32 [[AND_I256_2]], 65535
; CHECK-NEXT:    [[ADD_I258_2:%.*]] = add i32 [[MUL_I257_2]], [[ADD147_2]]
; CHECK-NEXT:    [[XOR_I259_2:%.*]] = xor i32 [[ADD_I258_2]], [[MUL_I257_2]]
; CHECK-NEXT:    [[SHR_I260_2:%.*]] = lshr i32 [[ADD149_2]], 15
; CHECK-NEXT:    [[AND_I261_2:%.*]] = and i32 [[SHR_I260_2]], 65537
; CHECK-NEXT:    [[MUL_I262_2:%.*]] = mul nuw i32 [[AND_I261_2]], 65535
; CHECK-NEXT:    [[ADD_I263_2:%.*]] = add i32 [[MUL_I262_2]], [[ADD149_2]]
; CHECK-NEXT:    [[XOR_I264_2:%.*]] = xor i32 [[ADD_I263_2]], [[MUL_I262_2]]
; CHECK-NEXT:    [[SHR_I265_2:%.*]] = lshr i32 [[SUB148_2]], 15
; CHECK-NEXT:    [[AND_I266_2:%.*]] = and i32 [[SHR_I265_2]], 65537
; CHECK-NEXT:    [[MUL_I267_2:%.*]] = mul nuw i32 [[AND_I266_2]], 65535
; CHECK-NEXT:    [[ADD_I268_2:%.*]] = add i32 [[MUL_I267_2]], [[SUB148_2]]
; CHECK-NEXT:    [[XOR_I269_2:%.*]] = xor i32 [[ADD_I268_2]], [[MUL_I267_2]]
; CHECK-NEXT:    [[SHR_I270_2:%.*]] = lshr i32 [[SUB150_2]], 15
; CHECK-NEXT:    [[AND_I271_2:%.*]] = and i32 [[SHR_I270_2]], 65537
; CHECK-NEXT:    [[MUL_I272_2:%.*]] = mul nuw i32 [[AND_I271_2]], 65535
; CHECK-NEXT:    [[ADD_I273_2:%.*]] = add i32 [[MUL_I272_2]], [[SUB150_2]]
; CHECK-NEXT:    [[XOR_I274_2:%.*]] = xor i32 [[ADD_I273_2]], [[MUL_I272_2]]
; CHECK-NEXT:    [[ADD153_2:%.*]] = add i32 [[XOR_I264_2]], [[ADD158_1]]
; CHECK-NEXT:    [[ADD155_2:%.*]] = add i32 [[ADD153_2]], [[XOR_I259_2]]
; CHECK-NEXT:    [[ADD157_2:%.*]] = add i32 [[ADD155_2]], [[XOR_I269_2]]
; CHECK-NEXT:    [[ADD158_2:%.*]] = add i32 [[ADD157_2]], [[XOR_I274_2]]
; CHECK-NEXT:    [[ARRAYIDX75_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 12
; CHECK-NEXT:    [[TMP24:%.*]] = load i32, ptr [[ARRAYIDX75_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX78_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 28
; CHECK-NEXT:    [[TMP25:%.*]] = load i32, ptr [[ARRAYIDX78_3]], align 4
; CHECK-NEXT:    [[ADD79_3:%.*]] = add i32 [[TMP25]], [[TMP24]]
; CHECK-NEXT:    [[SUB87_3:%.*]] = sub i32 [[TMP24]], [[TMP25]]
; CHECK-NEXT:    [[ARRAYIDX91_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 44
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[ARRAYIDX91_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX94_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 60
; CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[ARRAYIDX94_3]], align 4
; CHECK-NEXT:    [[ADD95_3:%.*]] = add i32 [[TMP27]], [[TMP26]]
; CHECK-NEXT:    [[SUB103_3:%.*]] = sub i32 [[TMP26]], [[TMP27]]
; CHECK-NEXT:    [[ADD104_3:%.*]] = add nsw i32 [[ADD95_3]], [[ADD79_3]]
; CHECK-NEXT:    [[SUB105_3:%.*]] = sub nsw i32 [[ADD79_3]], [[ADD95_3]]
; CHECK-NEXT:    [[ADD106_3:%.*]] = add nsw i32 [[SUB103_3]], [[SUB87_3]]
; CHECK-NEXT:    [[SUB107_3:%.*]] = sub nsw i32 [[SUB87_3]], [[SUB103_3]]
; CHECK-NEXT:    [[SHR_I_3:%.*]] = lshr i32 [[ADD104_3]], 15
; CHECK-NEXT:    [[AND_I_3:%.*]] = and i32 [[SHR_I_3]], 65537
; CHECK-NEXT:    [[MUL_I_3:%.*]] = mul nuw i32 [[AND_I_3]], 65535
; CHECK-NEXT:    [[ADD_I_3:%.*]] = add i32 [[MUL_I_3]], [[ADD104_3]]
; CHECK-NEXT:    [[XOR_I_3:%.*]] = xor i32 [[ADD_I_3]], [[MUL_I_3]]
; CHECK-NEXT:    [[SHR_I240_3:%.*]] = lshr i32 [[ADD106_3]], 15
; CHECK-NEXT:    [[AND_I241_3:%.*]] = and i32 [[SHR_I240_3]], 65537
; CHECK-NEXT:    [[MUL_I242_3:%.*]] = mul nuw i32 [[AND_I241_3]], 65535
; CHECK-NEXT:    [[ADD_I243_3:%.*]] = add i32 [[MUL_I242_3]], [[ADD106_3]]
; CHECK-NEXT:    [[XOR_I244_3:%.*]] = xor i32 [[ADD_I243_3]], [[MUL_I242_3]]
; CHECK-NEXT:    [[SHR_I245_3:%.*]] = lshr i32 [[SUB105_3]], 15
; CHECK-NEXT:    [[AND_I246_3:%.*]] = and i32 [[SHR_I245_3]], 65537
; CHECK-NEXT:    [[MUL_I247_3:%.*]] = mul nuw i32 [[AND_I246_3]], 65535
; CHECK-NEXT:    [[ADD_I248_3:%.*]] = add i32 [[MUL_I247_3]], [[SUB105_3]]
; CHECK-NEXT:    [[XOR_I249_3:%.*]] = xor i32 [[ADD_I248_3]], [[MUL_I247_3]]
; CHECK-NEXT:    [[SHR_I250_3:%.*]] = lshr i32 [[SUB107_3]], 15
; CHECK-NEXT:    [[AND_I251_3:%.*]] = and i32 [[SHR_I250_3]], 65537
; CHECK-NEXT:    [[MUL_I252_3:%.*]] = mul nuw i32 [[AND_I251_3]], 65535
; CHECK-NEXT:    [[ADD_I253_3:%.*]] = add i32 [[MUL_I252_3]], [[SUB107_3]]
; CHECK-NEXT:    [[XOR_I254_3:%.*]] = xor i32 [[ADD_I253_3]], [[MUL_I252_3]]
; CHECK-NEXT:    [[ADD109_3:%.*]] = add i32 [[XOR_I244_3]], [[ADD114_2]]
; CHECK-NEXT:    [[ADD111_3:%.*]] = add i32 [[ADD109_3]], [[XOR_I_3]]
; CHECK-NEXT:    [[ADD113_3:%.*]] = add i32 [[ADD111_3]], [[XOR_I249_3]]
; CHECK-NEXT:    [[ADD114_3:%.*]] = add i32 [[ADD113_3]], [[XOR_I254_3]]
; CHECK-NEXT:    [[ARRAYIDX118_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 76
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[ARRAYIDX118_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX121_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 92
; CHECK-NEXT:    [[TMP29:%.*]] = load i32, ptr [[ARRAYIDX121_3]], align 4
; CHECK-NEXT:    [[ADD122_3:%.*]] = add i32 [[TMP29]], [[TMP28]]
; CHECK-NEXT:    [[SUB130_3:%.*]] = sub i32 [[TMP28]], [[TMP29]]
; CHECK-NEXT:    [[ARRAYIDX134_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 108
; CHECK-NEXT:    [[TMP30:%.*]] = load i32, ptr [[ARRAYIDX134_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX137_3:%.*]] = getelementptr inbounds i8, ptr [[TMP]], i64 124
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[ARRAYIDX137_3]], align 4
; CHECK-NEXT:    [[ADD138_3:%.*]] = add i32 [[TMP31]], [[TMP30]]
; CHECK-NEXT:    [[SUB146_3:%.*]] = sub i32 [[TMP30]], [[TMP31]]
; CHECK-NEXT:    [[ADD147_3:%.*]] = add nsw i32 [[ADD138_3]], [[ADD122_3]]
; CHECK-NEXT:    [[SUB148_3:%.*]] = sub nsw i32 [[ADD122_3]], [[ADD138_3]]
; CHECK-NEXT:    [[ADD149_3:%.*]] = add nsw i32 [[SUB146_3]], [[SUB130_3]]
; CHECK-NEXT:    [[SUB150_3:%.*]] = sub nsw i32 [[SUB130_3]], [[SUB146_3]]
; CHECK-NEXT:    [[SHR_I255_3:%.*]] = lshr i32 [[ADD147_3]], 15
; CHECK-NEXT:    [[AND_I256_3:%.*]] = and i32 [[SHR_I255_3]], 65537
; CHECK-NEXT:    [[MUL_I257_3:%.*]] = mul nuw i32 [[AND_I256_3]], 65535
; CHECK-NEXT:    [[ADD_I258_3:%.*]] = add i32 [[MUL_I257_3]], [[ADD147_3]]
; CHECK-NEXT:    [[XOR_I259_3:%.*]] = xor i32 [[ADD_I258_3]], [[MUL_I257_3]]
; CHECK-NEXT:    [[SHR_I260_3:%.*]] = lshr i32 [[ADD149_3]], 15
; CHECK-NEXT:    [[AND_I261_3:%.*]] = and i32 [[SHR_I260_3]], 65537
; CHECK-NEXT:    [[MUL_I262_3:%.*]] = mul nuw i32 [[AND_I261_3]], 65535
; CHECK-NEXT:    [[ADD_I263_3:%.*]] = add i32 [[MUL_I262_3]], [[ADD149_3]]
; CHECK-NEXT:    [[XOR_I264_3:%.*]] = xor i32 [[ADD_I263_3]], [[MUL_I262_3]]
; CHECK-NEXT:    [[SHR_I265_3:%.*]] = lshr i32 [[SUB148_3]], 15
; CHECK-NEXT:    [[AND_I266_3:%.*]] = and i32 [[SHR_I265_3]], 65537
; CHECK-NEXT:    [[MUL_I267_3:%.*]] = mul nuw i32 [[AND_I266_3]], 65535
; CHECK-NEXT:    [[ADD_I268_3:%.*]] = add i32 [[MUL_I267_3]], [[SUB148_3]]
; CHECK-NEXT:    [[XOR_I269_3:%.*]] = xor i32 [[ADD_I268_3]], [[MUL_I267_3]]
; CHECK-NEXT:    [[SHR_I270_3:%.*]] = lshr i32 [[SUB150_3]], 15
; CHECK-NEXT:    [[AND_I271_3:%.*]] = and i32 [[SHR_I270_3]], 65537
; CHECK-NEXT:    [[MUL_I272_3:%.*]] = mul nuw i32 [[AND_I271_3]], 65535
; CHECK-NEXT:    [[ADD_I273_3:%.*]] = add i32 [[MUL_I272_3]], [[SUB150_3]]
; CHECK-NEXT:    [[XOR_I274_3:%.*]] = xor i32 [[ADD_I273_3]], [[MUL_I272_3]]
; CHECK-NEXT:    [[ADD153_3:%.*]] = add i32 [[XOR_I264_3]], [[ADD158_2]]
; CHECK-NEXT:    [[ADD155_3:%.*]] = add i32 [[ADD153_3]], [[XOR_I259_3]]
; CHECK-NEXT:    [[ADD157_3:%.*]] = add i32 [[ADD155_3]], [[XOR_I269_3]]
; CHECK-NEXT:    [[ADD158_3:%.*]] = add i32 [[ADD157_3]], [[XOR_I274_3]]
; CHECK-NEXT:    [[CONV163:%.*]] = and i32 [[ADD114_3]], 65535
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[ADD114_3]], 16
; CHECK-NEXT:    [[ADD164:%.*]] = add nuw nsw i32 [[CONV163]], [[SHR]]
; CHECK-NEXT:    [[SHR165:%.*]] = lshr i32 [[ADD164]], 1
; CHECK-NEXT:    [[CONV167:%.*]] = and i32 [[ADD158_3]], 65535
; CHECK-NEXT:    [[SHR168:%.*]] = lshr i32 [[ADD158_3]], 16
; CHECK-NEXT:    [[ADD169:%.*]] = add nuw nsw i32 [[CONV167]], [[SHR168]]
; CHECK-NEXT:    [[SHR170:%.*]] = lshr i32 [[ADD169]], 1
; CHECK-NEXT:    [[ADD171:%.*]] = add nuw nsw i32 [[SHR165]], [[SHR170]]
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 128, ptr nonnull [[TMP]])
; CHECK-NEXT:    ret i32 [[ADD171]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX1_0277:%.*]] = phi ptr [ [[BC_RESUME_VAL57]], %[[SCALAR_PH]] ], [ [[ADD_PTR64:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[PIX2_0276:%.*]] = phi ptr [ [[BC_RESUME_VAL58]], %[[SCALAR_PH]] ], [ [[ADD_PTR66:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = load i8, ptr [[PIX1_0277]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP32]] to i32
; CHECK-NEXT:    [[TMP33:%.*]] = load i8, ptr [[PIX2_0276]], align 1
; CHECK-NEXT:    [[CONV3:%.*]] = zext i8 [[TMP33]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[CONV]], [[CONV3]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i8, ptr [[ARRAYIDX4]], align 1
; CHECK-NEXT:    [[CONV5:%.*]] = zext i8 [[TMP34]] to i32
; CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 4
; CHECK-NEXT:    [[TMP35:%.*]] = load i8, ptr [[ARRAYIDX6]], align 1
; CHECK-NEXT:    [[CONV7:%.*]] = zext i8 [[TMP35]] to i32
; CHECK-NEXT:    [[SUB8:%.*]] = sub nsw i32 [[CONV5]], [[CONV7]]
; CHECK-NEXT:    [[SHL:%.*]] = shl nsw i32 [[SUB8]], 16
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[SHL]], [[SUB]]
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 1
; CHECK-NEXT:    [[TMP36:%.*]] = load i8, ptr [[ARRAYIDX9]], align 1
; CHECK-NEXT:    [[CONV10:%.*]] = zext i8 [[TMP36]] to i32
; CHECK-NEXT:    [[ARRAYIDX11:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 1
; CHECK-NEXT:    [[TMP37:%.*]] = load i8, ptr [[ARRAYIDX11]], align 1
; CHECK-NEXT:    [[CONV12:%.*]] = zext i8 [[TMP37]] to i32
; CHECK-NEXT:    [[SUB13:%.*]] = sub nsw i32 [[CONV10]], [[CONV12]]
; CHECK-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 5
; CHECK-NEXT:    [[TMP38:%.*]] = load i8, ptr [[ARRAYIDX14]], align 1
; CHECK-NEXT:    [[CONV15:%.*]] = zext i8 [[TMP38]] to i32
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 5
; CHECK-NEXT:    [[TMP39:%.*]] = load i8, ptr [[ARRAYIDX16]], align 1
; CHECK-NEXT:    [[CONV17:%.*]] = zext i8 [[TMP39]] to i32
; CHECK-NEXT:    [[SUB18:%.*]] = sub nsw i32 [[CONV15]], [[CONV17]]
; CHECK-NEXT:    [[SHL19:%.*]] = shl nsw i32 [[SUB18]], 16
; CHECK-NEXT:    [[ADD20:%.*]] = add nsw i32 [[SHL19]], [[SUB13]]
; CHECK-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 2
; CHECK-NEXT:    [[TMP40:%.*]] = load i8, ptr [[ARRAYIDX21]], align 1
; CHECK-NEXT:    [[CONV22:%.*]] = zext i8 [[TMP40]] to i32
; CHECK-NEXT:    [[ARRAYIDX23:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 2
; CHECK-NEXT:    [[TMP41:%.*]] = load i8, ptr [[ARRAYIDX23]], align 1
; CHECK-NEXT:    [[CONV24:%.*]] = zext i8 [[TMP41]] to i32
; CHECK-NEXT:    [[SUB25:%.*]] = sub nsw i32 [[CONV22]], [[CONV24]]
; CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 6
; CHECK-NEXT:    [[TMP42:%.*]] = load i8, ptr [[ARRAYIDX26]], align 1
; CHECK-NEXT:    [[CONV27:%.*]] = zext i8 [[TMP42]] to i32
; CHECK-NEXT:    [[ARRAYIDX28:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 6
; CHECK-NEXT:    [[TMP43:%.*]] = load i8, ptr [[ARRAYIDX28]], align 1
; CHECK-NEXT:    [[CONV29:%.*]] = zext i8 [[TMP43]] to i32
; CHECK-NEXT:    [[SUB30:%.*]] = sub nsw i32 [[CONV27]], [[CONV29]]
; CHECK-NEXT:    [[SHL31:%.*]] = shl nsw i32 [[SUB30]], 16
; CHECK-NEXT:    [[ADD32:%.*]] = add nsw i32 [[SHL31]], [[SUB25]]
; CHECK-NEXT:    [[ARRAYIDX33:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 3
; CHECK-NEXT:    [[TMP44:%.*]] = load i8, ptr [[ARRAYIDX33]], align 1
; CHECK-NEXT:    [[CONV34:%.*]] = zext i8 [[TMP44]] to i32
; CHECK-NEXT:    [[ARRAYIDX35:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 3
; CHECK-NEXT:    [[TMP45:%.*]] = load i8, ptr [[ARRAYIDX35]], align 1
; CHECK-NEXT:    [[CONV36:%.*]] = zext i8 [[TMP45]] to i32
; CHECK-NEXT:    [[SUB37:%.*]] = sub nsw i32 [[CONV34]], [[CONV36]]
; CHECK-NEXT:    [[ARRAYIDX38:%.*]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 7
; CHECK-NEXT:    [[TMP46:%.*]] = load i8, ptr [[ARRAYIDX38]], align 1
; CHECK-NEXT:    [[CONV39:%.*]] = zext i8 [[TMP46]] to i32
; CHECK-NEXT:    [[ARRAYIDX40:%.*]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 7
; CHECK-NEXT:    [[TMP47:%.*]] = load i8, ptr [[ARRAYIDX40]], align 1
; CHECK-NEXT:    [[CONV41:%.*]] = zext i8 [[TMP47]] to i32
; CHECK-NEXT:    [[SUB42:%.*]] = sub nsw i32 [[CONV39]], [[CONV41]]
; CHECK-NEXT:    [[SHL43:%.*]] = shl nsw i32 [[SUB42]], 16
; CHECK-NEXT:    [[ADD44:%.*]] = add nsw i32 [[SHL43]], [[SUB37]]
; CHECK-NEXT:    [[ADD45:%.*]] = add nsw i32 [[ADD20]], [[ADD]]
; CHECK-NEXT:    [[SUB46:%.*]] = sub nsw i32 [[ADD]], [[ADD20]]
; CHECK-NEXT:    [[ADD47:%.*]] = add nsw i32 [[ADD44]], [[ADD32]]
; CHECK-NEXT:    [[SUB48:%.*]] = sub nsw i32 [[ADD32]], [[ADD44]]
; CHECK-NEXT:    [[ADD49:%.*]] = add nsw i32 [[ADD47]], [[ADD45]]
; CHECK-NEXT:    [[ARRAYIDX50:%.*]] = getelementptr inbounds [8 x [4 x i32]], ptr [[TMP]], i64 0, i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[ADD49]], ptr [[ARRAYIDX50]], align 8
; CHECK-NEXT:    [[SUB52:%.*]] = sub nsw i32 [[ADD45]], [[ADD47]]
; CHECK-NEXT:    [[ARRAYIDX55:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX50]], i64 8
; CHECK-NEXT:    store i32 [[SUB52]], ptr [[ARRAYIDX55]], align 8
; CHECK-NEXT:    [[ADD56:%.*]] = add nsw i32 [[SUB48]], [[SUB46]]
; CHECK-NEXT:    [[ARRAYIDX59:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX50]], i64 4
; CHECK-NEXT:    store i32 [[ADD56]], ptr [[ARRAYIDX59]], align 4
; CHECK-NEXT:    [[SUB60:%.*]] = sub nsw i32 [[SUB46]], [[SUB48]]
; CHECK-NEXT:    [[ARRAYIDX63:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX50]], i64 12
; CHECK-NEXT:    store i32 [[SUB60]], ptr [[ARRAYIDX63]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[ADD_PTR64]] = getelementptr inbounds i8, ptr [[PIX1_0277]], i64 [[IDX_EXT]]
; CHECK-NEXT:    [[ADD_PTR66]] = getelementptr inbounds i8, ptr [[PIX2_0276]], i64 [[IDX_EXT65]]
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 16
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND68_PREHEADER]], label %[[FOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
;
entry:
  %tmp = alloca [8 x [4 x i32]], align 8
  call void @llvm.lifetime.start.p0(i64 128, ptr nonnull %tmp) #5
  %add.ptr = getelementptr inbounds i8, ptr %pix1_base, i64 8
  %add.ptr1 = getelementptr inbounds i8, ptr %pix2_base, i64 8
  %idx.ext = sext i32 %i_pix1 to i64
  %idx.ext65 = sext i32 %i_pix2 to i64
  br label %for.body

for.cond68.preheader:                             ; preds = %for.body
  %arrayidx76 = getelementptr inbounds i8, ptr %tmp, i64 16
  %arrayidx89 = getelementptr inbounds i8, ptr %tmp, i64 32
  %arrayidx92 = getelementptr inbounds i8, ptr %tmp, i64 48
  %arrayidx116 = getelementptr inbounds i8, ptr %tmp, i64 64
  %arrayidx119 = getelementptr inbounds i8, ptr %tmp, i64 80
  %arrayidx132 = getelementptr inbounds i8, ptr %tmp, i64 96
  %arrayidx135 = getelementptr inbounds i8, ptr %tmp, i64 112
  %0 = load i32, ptr %tmp, align 4
  %1 = load i32, ptr %arrayidx76, align 4
  %add79 = add i32 %1, %0
  %sub87 = sub i32 %0, %1
  %2 = load i32, ptr %arrayidx89, align 4
  %3 = load i32, ptr %arrayidx92, align 4
  %add95 = add i32 %3, %2
  %sub103 = sub i32 %2, %3
  %add104 = add nsw i32 %add95, %add79
  %sub105 = sub nsw i32 %add79, %add95
  %add106 = add nsw i32 %sub103, %sub87
  %sub107 = sub nsw i32 %sub87, %sub103
  %shr.i = lshr i32 %add104, 15
  %and.i = and i32 %shr.i, 65537
  %mul.i = mul nuw i32 %and.i, 65535
  %add.i = add i32 %mul.i, %add104
  %xor.i = xor i32 %add.i, %mul.i
  %shr.i240 = lshr i32 %add106, 15
  %and.i241 = and i32 %shr.i240, 65537
  %mul.i242 = mul nuw i32 %and.i241, 65535
  %add.i243 = add i32 %mul.i242, %add106
  %xor.i244 = xor i32 %add.i243, %mul.i242
  %shr.i245 = lshr i32 %sub105, 15
  %and.i246 = and i32 %shr.i245, 65537
  %mul.i247 = mul nuw i32 %and.i246, 65535
  %add.i248 = add i32 %mul.i247, %sub105
  %xor.i249 = xor i32 %add.i248, %mul.i247
  %shr.i250 = lshr i32 %sub107, 15
  %and.i251 = and i32 %shr.i250, 65537
  %mul.i252 = mul nuw i32 %and.i251, 65535
  %add.i253 = add i32 %mul.i252, %sub107
  %xor.i254 = xor i32 %add.i253, %mul.i252
  %add111 = add i32 %xor.i244, %xor.i
  %add113 = add i32 %add111, %xor.i249
  %add114 = add i32 %add113, %xor.i254
  %4 = load i32, ptr %arrayidx116, align 4
  %5 = load i32, ptr %arrayidx119, align 4
  %add122 = add i32 %5, %4
  %sub130 = sub i32 %4, %5
  %6 = load i32, ptr %arrayidx132, align 4
  %7 = load i32, ptr %arrayidx135, align 4
  %add138 = add i32 %7, %6
  %sub146 = sub i32 %6, %7
  %add147 = add nsw i32 %add138, %add122
  %sub148 = sub nsw i32 %add122, %add138
  %add149 = add nsw i32 %sub146, %sub130
  %sub150 = sub nsw i32 %sub130, %sub146
  %shr.i255 = lshr i32 %add147, 15
  %and.i256 = and i32 %shr.i255, 65537
  %mul.i257 = mul nuw i32 %and.i256, 65535
  %add.i258 = add i32 %mul.i257, %add147
  %xor.i259 = xor i32 %add.i258, %mul.i257
  %shr.i260 = lshr i32 %add149, 15
  %and.i261 = and i32 %shr.i260, 65537
  %mul.i262 = mul nuw i32 %and.i261, 65535
  %add.i263 = add i32 %mul.i262, %add149
  %xor.i264 = xor i32 %add.i263, %mul.i262
  %shr.i265 = lshr i32 %sub148, 15
  %and.i266 = and i32 %shr.i265, 65537
  %mul.i267 = mul nuw i32 %and.i266, 65535
  %add.i268 = add i32 %mul.i267, %sub148
  %xor.i269 = xor i32 %add.i268, %mul.i267
  %shr.i270 = lshr i32 %sub150, 15
  %and.i271 = and i32 %shr.i270, 65537
  %mul.i272 = mul nuw i32 %and.i271, 65535
  %add.i273 = add i32 %mul.i272, %sub150
  %xor.i274 = xor i32 %add.i273, %mul.i272
  %add155 = add i32 %xor.i264, %xor.i259
  %add157 = add i32 %add155, %xor.i269
  %add158 = add i32 %add157, %xor.i274
  %arrayidx75.1 = getelementptr inbounds i8, ptr %tmp, i64 4
  %8 = load i32, ptr %arrayidx75.1, align 4
  %arrayidx78.1 = getelementptr inbounds i8, ptr %tmp, i64 20
  %9 = load i32, ptr %arrayidx78.1, align 4
  %add79.1 = add i32 %9, %8
  %sub87.1 = sub i32 %8, %9
  %arrayidx91.1 = getelementptr inbounds i8, ptr %tmp, i64 36
  %10 = load i32, ptr %arrayidx91.1, align 4
  %arrayidx94.1 = getelementptr inbounds i8, ptr %tmp, i64 52
  %11 = load i32, ptr %arrayidx94.1, align 4
  %add95.1 = add i32 %11, %10
  %sub103.1 = sub i32 %10, %11
  %add104.1 = add nsw i32 %add95.1, %add79.1
  %sub105.1 = sub nsw i32 %add79.1, %add95.1
  %add106.1 = add nsw i32 %sub103.1, %sub87.1
  %sub107.1 = sub nsw i32 %sub87.1, %sub103.1
  %shr.i.1 = lshr i32 %add104.1, 15
  %and.i.1 = and i32 %shr.i.1, 65537
  %mul.i.1 = mul nuw i32 %and.i.1, 65535
  %add.i.1 = add i32 %mul.i.1, %add104.1
  %xor.i.1 = xor i32 %add.i.1, %mul.i.1
  %shr.i240.1 = lshr i32 %add106.1, 15
  %and.i241.1 = and i32 %shr.i240.1, 65537
  %mul.i242.1 = mul nuw i32 %and.i241.1, 65535
  %add.i243.1 = add i32 %mul.i242.1, %add106.1
  %xor.i244.1 = xor i32 %add.i243.1, %mul.i242.1
  %shr.i245.1 = lshr i32 %sub105.1, 15
  %and.i246.1 = and i32 %shr.i245.1, 65537
  %mul.i247.1 = mul nuw i32 %and.i246.1, 65535
  %add.i248.1 = add i32 %mul.i247.1, %sub105.1
  %xor.i249.1 = xor i32 %add.i248.1, %mul.i247.1
  %shr.i250.1 = lshr i32 %sub107.1, 15
  %and.i251.1 = and i32 %shr.i250.1, 65537
  %mul.i252.1 = mul nuw i32 %and.i251.1, 65535
  %add.i253.1 = add i32 %mul.i252.1, %sub107.1
  %xor.i254.1 = xor i32 %add.i253.1, %mul.i252.1
  %add109.1 = add i32 %xor.i244.1, %add114
  %add111.1 = add i32 %add109.1, %xor.i.1
  %add113.1 = add i32 %add111.1, %xor.i249.1
  %add114.1 = add i32 %add113.1, %xor.i254.1
  %arrayidx118.1 = getelementptr inbounds i8, ptr %tmp, i64 68
  %12 = load i32, ptr %arrayidx118.1, align 4
  %arrayidx121.1 = getelementptr inbounds i8, ptr %tmp, i64 84
  %13 = load i32, ptr %arrayidx121.1, align 4
  %add122.1 = add i32 %13, %12
  %sub130.1 = sub i32 %12, %13
  %arrayidx134.1 = getelementptr inbounds i8, ptr %tmp, i64 100
  %14 = load i32, ptr %arrayidx134.1, align 4
  %arrayidx137.1 = getelementptr inbounds i8, ptr %tmp, i64 116
  %15 = load i32, ptr %arrayidx137.1, align 4
  %add138.1 = add i32 %15, %14
  %sub146.1 = sub i32 %14, %15
  %add147.1 = add nsw i32 %add138.1, %add122.1
  %sub148.1 = sub nsw i32 %add122.1, %add138.1
  %add149.1 = add nsw i32 %sub146.1, %sub130.1
  %sub150.1 = sub nsw i32 %sub130.1, %sub146.1
  %shr.i255.1 = lshr i32 %add147.1, 15
  %and.i256.1 = and i32 %shr.i255.1, 65537
  %mul.i257.1 = mul nuw i32 %and.i256.1, 65535
  %add.i258.1 = add i32 %mul.i257.1, %add147.1
  %xor.i259.1 = xor i32 %add.i258.1, %mul.i257.1
  %shr.i260.1 = lshr i32 %add149.1, 15
  %and.i261.1 = and i32 %shr.i260.1, 65537
  %mul.i262.1 = mul nuw i32 %and.i261.1, 65535
  %add.i263.1 = add i32 %mul.i262.1, %add149.1
  %xor.i264.1 = xor i32 %add.i263.1, %mul.i262.1
  %shr.i265.1 = lshr i32 %sub148.1, 15
  %and.i266.1 = and i32 %shr.i265.1, 65537
  %mul.i267.1 = mul nuw i32 %and.i266.1, 65535
  %add.i268.1 = add i32 %mul.i267.1, %sub148.1
  %xor.i269.1 = xor i32 %add.i268.1, %mul.i267.1
  %shr.i270.1 = lshr i32 %sub150.1, 15
  %and.i271.1 = and i32 %shr.i270.1, 65537
  %mul.i272.1 = mul nuw i32 %and.i271.1, 65535
  %add.i273.1 = add i32 %mul.i272.1, %sub150.1
  %xor.i274.1 = xor i32 %add.i273.1, %mul.i272.1
  %add153.1 = add i32 %xor.i264.1, %add158
  %add155.1 = add i32 %add153.1, %xor.i259.1
  %add157.1 = add i32 %add155.1, %xor.i269.1
  %add158.1 = add i32 %add157.1, %xor.i274.1
  %arrayidx75.2 = getelementptr inbounds i8, ptr %tmp, i64 8
  %16 = load i32, ptr %arrayidx75.2, align 4
  %arrayidx78.2 = getelementptr inbounds i8, ptr %tmp, i64 24
  %17 = load i32, ptr %arrayidx78.2, align 4
  %add79.2 = add i32 %17, %16
  %sub87.2 = sub i32 %16, %17
  %arrayidx91.2 = getelementptr inbounds i8, ptr %tmp, i64 40
  %18 = load i32, ptr %arrayidx91.2, align 4
  %arrayidx94.2 = getelementptr inbounds i8, ptr %tmp, i64 56
  %19 = load i32, ptr %arrayidx94.2, align 4
  %add95.2 = add i32 %19, %18
  %sub103.2 = sub i32 %18, %19
  %add104.2 = add nsw i32 %add95.2, %add79.2
  %sub105.2 = sub nsw i32 %add79.2, %add95.2
  %add106.2 = add nsw i32 %sub103.2, %sub87.2
  %sub107.2 = sub nsw i32 %sub87.2, %sub103.2
  %shr.i.2 = lshr i32 %add104.2, 15
  %and.i.2 = and i32 %shr.i.2, 65537
  %mul.i.2 = mul nuw i32 %and.i.2, 65535
  %add.i.2 = add i32 %mul.i.2, %add104.2
  %xor.i.2 = xor i32 %add.i.2, %mul.i.2
  %shr.i240.2 = lshr i32 %add106.2, 15
  %and.i241.2 = and i32 %shr.i240.2, 65537
  %mul.i242.2 = mul nuw i32 %and.i241.2, 65535
  %add.i243.2 = add i32 %mul.i242.2, %add106.2
  %xor.i244.2 = xor i32 %add.i243.2, %mul.i242.2
  %shr.i245.2 = lshr i32 %sub105.2, 15
  %and.i246.2 = and i32 %shr.i245.2, 65537
  %mul.i247.2 = mul nuw i32 %and.i246.2, 65535
  %add.i248.2 = add i32 %mul.i247.2, %sub105.2
  %xor.i249.2 = xor i32 %add.i248.2, %mul.i247.2
  %shr.i250.2 = lshr i32 %sub107.2, 15
  %and.i251.2 = and i32 %shr.i250.2, 65537
  %mul.i252.2 = mul nuw i32 %and.i251.2, 65535
  %add.i253.2 = add i32 %mul.i252.2, %sub107.2
  %xor.i254.2 = xor i32 %add.i253.2, %mul.i252.2
  %add109.2 = add i32 %xor.i244.2, %add114.1
  %add111.2 = add i32 %add109.2, %xor.i.2
  %add113.2 = add i32 %add111.2, %xor.i249.2
  %add114.2 = add i32 %add113.2, %xor.i254.2
  %arrayidx118.2 = getelementptr inbounds i8, ptr %tmp, i64 72
  %20 = load i32, ptr %arrayidx118.2, align 4
  %arrayidx121.2 = getelementptr inbounds i8, ptr %tmp, i64 88
  %21 = load i32, ptr %arrayidx121.2, align 4
  %add122.2 = add i32 %21, %20
  %sub130.2 = sub i32 %20, %21
  %arrayidx134.2 = getelementptr inbounds i8, ptr %tmp, i64 104
  %22 = load i32, ptr %arrayidx134.2, align 4
  %arrayidx137.2 = getelementptr inbounds i8, ptr %tmp, i64 120
  %23 = load i32, ptr %arrayidx137.2, align 4
  %add138.2 = add i32 %23, %22
  %sub146.2 = sub i32 %22, %23
  %add147.2 = add nsw i32 %add138.2, %add122.2
  %sub148.2 = sub nsw i32 %add122.2, %add138.2
  %add149.2 = add nsw i32 %sub146.2, %sub130.2
  %sub150.2 = sub nsw i32 %sub130.2, %sub146.2
  %shr.i255.2 = lshr i32 %add147.2, 15
  %and.i256.2 = and i32 %shr.i255.2, 65537
  %mul.i257.2 = mul nuw i32 %and.i256.2, 65535
  %add.i258.2 = add i32 %mul.i257.2, %add147.2
  %xor.i259.2 = xor i32 %add.i258.2, %mul.i257.2
  %shr.i260.2 = lshr i32 %add149.2, 15
  %and.i261.2 = and i32 %shr.i260.2, 65537
  %mul.i262.2 = mul nuw i32 %and.i261.2, 65535
  %add.i263.2 = add i32 %mul.i262.2, %add149.2
  %xor.i264.2 = xor i32 %add.i263.2, %mul.i262.2
  %shr.i265.2 = lshr i32 %sub148.2, 15
  %and.i266.2 = and i32 %shr.i265.2, 65537
  %mul.i267.2 = mul nuw i32 %and.i266.2, 65535
  %add.i268.2 = add i32 %mul.i267.2, %sub148.2
  %xor.i269.2 = xor i32 %add.i268.2, %mul.i267.2
  %shr.i270.2 = lshr i32 %sub150.2, 15
  %and.i271.2 = and i32 %shr.i270.2, 65537
  %mul.i272.2 = mul nuw i32 %and.i271.2, 65535
  %add.i273.2 = add i32 %mul.i272.2, %sub150.2
  %xor.i274.2 = xor i32 %add.i273.2, %mul.i272.2
  %add153.2 = add i32 %xor.i264.2, %add158.1
  %add155.2 = add i32 %add153.2, %xor.i259.2
  %add157.2 = add i32 %add155.2, %xor.i269.2
  %add158.2 = add i32 %add157.2, %xor.i274.2
  %arrayidx75.3 = getelementptr inbounds i8, ptr %tmp, i64 12
  %24 = load i32, ptr %arrayidx75.3, align 4
  %arrayidx78.3 = getelementptr inbounds i8, ptr %tmp, i64 28
  %25 = load i32, ptr %arrayidx78.3, align 4
  %add79.3 = add i32 %25, %24
  %sub87.3 = sub i32 %24, %25
  %arrayidx91.3 = getelementptr inbounds i8, ptr %tmp, i64 44
  %26 = load i32, ptr %arrayidx91.3, align 4
  %arrayidx94.3 = getelementptr inbounds i8, ptr %tmp, i64 60
  %27 = load i32, ptr %arrayidx94.3, align 4
  %add95.3 = add i32 %27, %26
  %sub103.3 = sub i32 %26, %27
  %add104.3 = add nsw i32 %add95.3, %add79.3
  %sub105.3 = sub nsw i32 %add79.3, %add95.3
  %add106.3 = add nsw i32 %sub103.3, %sub87.3
  %sub107.3 = sub nsw i32 %sub87.3, %sub103.3
  %shr.i.3 = lshr i32 %add104.3, 15
  %and.i.3 = and i32 %shr.i.3, 65537
  %mul.i.3 = mul nuw i32 %and.i.3, 65535
  %add.i.3 = add i32 %mul.i.3, %add104.3
  %xor.i.3 = xor i32 %add.i.3, %mul.i.3
  %shr.i240.3 = lshr i32 %add106.3, 15
  %and.i241.3 = and i32 %shr.i240.3, 65537
  %mul.i242.3 = mul nuw i32 %and.i241.3, 65535
  %add.i243.3 = add i32 %mul.i242.3, %add106.3
  %xor.i244.3 = xor i32 %add.i243.3, %mul.i242.3
  %shr.i245.3 = lshr i32 %sub105.3, 15
  %and.i246.3 = and i32 %shr.i245.3, 65537
  %mul.i247.3 = mul nuw i32 %and.i246.3, 65535
  %add.i248.3 = add i32 %mul.i247.3, %sub105.3
  %xor.i249.3 = xor i32 %add.i248.3, %mul.i247.3
  %shr.i250.3 = lshr i32 %sub107.3, 15
  %and.i251.3 = and i32 %shr.i250.3, 65537
  %mul.i252.3 = mul nuw i32 %and.i251.3, 65535
  %add.i253.3 = add i32 %mul.i252.3, %sub107.3
  %xor.i254.3 = xor i32 %add.i253.3, %mul.i252.3
  %add109.3 = add i32 %xor.i244.3, %add114.2
  %add111.3 = add i32 %add109.3, %xor.i.3
  %add113.3 = add i32 %add111.3, %xor.i249.3
  %add114.3 = add i32 %add113.3, %xor.i254.3
  %arrayidx118.3 = getelementptr inbounds i8, ptr %tmp, i64 76
  %28 = load i32, ptr %arrayidx118.3, align 4
  %arrayidx121.3 = getelementptr inbounds i8, ptr %tmp, i64 92
  %29 = load i32, ptr %arrayidx121.3, align 4
  %add122.3 = add i32 %29, %28
  %sub130.3 = sub i32 %28, %29
  %arrayidx134.3 = getelementptr inbounds i8, ptr %tmp, i64 108
  %30 = load i32, ptr %arrayidx134.3, align 4
  %arrayidx137.3 = getelementptr inbounds i8, ptr %tmp, i64 124
  %31 = load i32, ptr %arrayidx137.3, align 4
  %add138.3 = add i32 %31, %30
  %sub146.3 = sub i32 %30, %31
  %add147.3 = add nsw i32 %add138.3, %add122.3
  %sub148.3 = sub nsw i32 %add122.3, %add138.3
  %add149.3 = add nsw i32 %sub146.3, %sub130.3
  %sub150.3 = sub nsw i32 %sub130.3, %sub146.3
  %shr.i255.3 = lshr i32 %add147.3, 15
  %and.i256.3 = and i32 %shr.i255.3, 65537
  %mul.i257.3 = mul nuw i32 %and.i256.3, 65535
  %add.i258.3 = add i32 %mul.i257.3, %add147.3
  %xor.i259.3 = xor i32 %add.i258.3, %mul.i257.3
  %shr.i260.3 = lshr i32 %add149.3, 15
  %and.i261.3 = and i32 %shr.i260.3, 65537
  %mul.i262.3 = mul nuw i32 %and.i261.3, 65535
  %add.i263.3 = add i32 %mul.i262.3, %add149.3
  %xor.i264.3 = xor i32 %add.i263.3, %mul.i262.3
  %shr.i265.3 = lshr i32 %sub148.3, 15
  %and.i266.3 = and i32 %shr.i265.3, 65537
  %mul.i267.3 = mul nuw i32 %and.i266.3, 65535
  %add.i268.3 = add i32 %mul.i267.3, %sub148.3
  %xor.i269.3 = xor i32 %add.i268.3, %mul.i267.3
  %shr.i270.3 = lshr i32 %sub150.3, 15
  %and.i271.3 = and i32 %shr.i270.3, 65537
  %mul.i272.3 = mul nuw i32 %and.i271.3, 65535
  %add.i273.3 = add i32 %mul.i272.3, %sub150.3
  %xor.i274.3 = xor i32 %add.i273.3, %mul.i272.3
  %add153.3 = add i32 %xor.i264.3, %add158.2
  %add155.3 = add i32 %add153.3, %xor.i259.3
  %add157.3 = add i32 %add155.3, %xor.i269.3
  %add158.3 = add i32 %add157.3, %xor.i274.3
  %conv163 = and i32 %add114.3, 65535
  %shr = lshr i32 %add114.3, 16
  %add164 = add nuw nsw i32 %conv163, %shr
  %shr165 = lshr i32 %add164, 1
  %conv167 = and i32 %add158.3, 65535
  %shr168 = lshr i32 %add158.3, 16
  %add169 = add nuw nsw i32 %conv167, %shr168
  %shr170 = lshr i32 %add169, 1
  %add171 = add nuw nsw i32 %shr165, %shr170
  call void @llvm.lifetime.end.p0(i64 128, ptr nonnull %tmp) #5
  ret i32 %add171

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %pix1.0277 = phi ptr [ %add.ptr, %entry ], [ %add.ptr64, %for.body ]
  %pix2.0276 = phi ptr [ %add.ptr1, %entry ], [ %add.ptr66, %for.body ]
  %32 = load i8, ptr %pix1.0277, align 1
  %conv = zext i8 %32 to i32
  %33 = load i8, ptr %pix2.0276, align 1
  %conv3 = zext i8 %33 to i32
  %sub = sub nsw i32 %conv, %conv3
  %arrayidx4 = getelementptr inbounds i8, ptr %pix1.0277, i64 4
  %34 = load i8, ptr %arrayidx4, align 1
  %conv5 = zext i8 %34 to i32
  %arrayidx6 = getelementptr inbounds i8, ptr %pix2.0276, i64 4
  %35 = load i8, ptr %arrayidx6, align 1
  %conv7 = zext i8 %35 to i32
  %sub8 = sub nsw i32 %conv5, %conv7
  %shl = shl nsw i32 %sub8, 16
  %add = add nsw i32 %shl, %sub
  %arrayidx9 = getelementptr inbounds i8, ptr %pix1.0277, i64 1
  %36 = load i8, ptr %arrayidx9, align 1
  %conv10 = zext i8 %36 to i32
  %arrayidx11 = getelementptr inbounds i8, ptr %pix2.0276, i64 1
  %37 = load i8, ptr %arrayidx11, align 1
  %conv12 = zext i8 %37 to i32
  %sub13 = sub nsw i32 %conv10, %conv12
  %arrayidx14 = getelementptr inbounds i8, ptr %pix1.0277, i64 5
  %38 = load i8, ptr %arrayidx14, align 1
  %conv15 = zext i8 %38 to i32
  %arrayidx16 = getelementptr inbounds i8, ptr %pix2.0276, i64 5
  %39 = load i8, ptr %arrayidx16, align 1
  %conv17 = zext i8 %39 to i32
  %sub18 = sub nsw i32 %conv15, %conv17
  %shl19 = shl nsw i32 %sub18, 16
  %add20 = add nsw i32 %shl19, %sub13
  %arrayidx21 = getelementptr inbounds i8, ptr %pix1.0277, i64 2
  %40 = load i8, ptr %arrayidx21, align 1
  %conv22 = zext i8 %40 to i32
  %arrayidx23 = getelementptr inbounds i8, ptr %pix2.0276, i64 2
  %41 = load i8, ptr %arrayidx23, align 1
  %conv24 = zext i8 %41 to i32
  %sub25 = sub nsw i32 %conv22, %conv24
  %arrayidx26 = getelementptr inbounds i8, ptr %pix1.0277, i64 6
  %42 = load i8, ptr %arrayidx26, align 1
  %conv27 = zext i8 %42 to i32
  %arrayidx28 = getelementptr inbounds i8, ptr %pix2.0276, i64 6
  %43 = load i8, ptr %arrayidx28, align 1
  %conv29 = zext i8 %43 to i32
  %sub30 = sub nsw i32 %conv27, %conv29
  %shl31 = shl nsw i32 %sub30, 16
  %add32 = add nsw i32 %shl31, %sub25
  %arrayidx33 = getelementptr inbounds i8, ptr %pix1.0277, i64 3
  %44 = load i8, ptr %arrayidx33, align 1
  %conv34 = zext i8 %44 to i32
  %arrayidx35 = getelementptr inbounds i8, ptr %pix2.0276, i64 3
  %45 = load i8, ptr %arrayidx35, align 1
  %conv36 = zext i8 %45 to i32
  %sub37 = sub nsw i32 %conv34, %conv36
  %arrayidx38 = getelementptr inbounds i8, ptr %pix1.0277, i64 7
  %46 = load i8, ptr %arrayidx38, align 1
  %conv39 = zext i8 %46 to i32
  %arrayidx40 = getelementptr inbounds i8, ptr %pix2.0276, i64 7
  %47 = load i8, ptr %arrayidx40, align 1
  %conv41 = zext i8 %47 to i32
  %sub42 = sub nsw i32 %conv39, %conv41
  %shl43 = shl nsw i32 %sub42, 16
  %add44 = add nsw i32 %shl43, %sub37
  %add45 = add nsw i32 %add20, %add
  %sub46 = sub nsw i32 %add, %add20
  %add47 = add nsw i32 %add44, %add32
  %sub48 = sub nsw i32 %add32, %add44
  %add49 = add nsw i32 %add47, %add45
  %arrayidx50 = getelementptr inbounds [8 x [4 x i32]], ptr %tmp, i64 0, i64 %indvars.iv
  store i32 %add49, ptr %arrayidx50, align 8
  %sub52 = sub nsw i32 %add45, %add47
  %arrayidx55 = getelementptr inbounds i8, ptr %arrayidx50, i64 8
  store i32 %sub52, ptr %arrayidx55, align 8
  %add56 = add nsw i32 %sub48, %sub46
  %arrayidx59 = getelementptr inbounds i8, ptr %arrayidx50, i64 4
  store i32 %add56, ptr %arrayidx59, align 4
  %sub60 = sub nsw i32 %sub46, %sub48
  %arrayidx63 = getelementptr inbounds i8, ptr %arrayidx50, i64 12
  store i32 %sub60, ptr %arrayidx63, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %add.ptr64 = getelementptr inbounds i8, ptr %pix1.0277, i64 %idx.ext
  %add.ptr66 = getelementptr inbounds i8, ptr %pix2.0276, i64 %idx.ext65
  %exitcond.not = icmp eq i64 %indvars.iv.next, 16
  br i1 %exitcond.not, label %for.cond68.preheader, label %for.body
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]], [[META2]], [[META3]]}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]]}
;.
