; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -S -passes=loop-vectorize -force-tail-folding-style=data-with-evl \
; RUN: -prefer-predicate-over-epilogue=predicate-dont-vectorize -mtriple=riscv64 -mattr=+v | FileCheck %s
define void @ham() {
; CHECK-LABEL: define void @ham(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ [[ADD6:%.*]], %[[FOR_BODY_2:.*]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 4, i32 2, i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i64> poison, i64 [[PHI]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i64> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP0:%.*]] = trunc <vscale x 2 x i64> [[BROADCAST_SPLAT]] to <vscale x 2 x i32>
; CHECK-NEXT:    [[TMP1:%.*]] = add <vscale x 2 x i32> [[TMP0]], splat (i32 5)
; CHECK-NEXT:    [[TMP2:%.*]] = shl <vscale x 2 x i32> zeroinitializer, [[TMP1]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 4, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv2i32.nxv2p0(<vscale x 2 x i32> [[TMP2]], <vscale x 2 x ptr> align 4 zeroinitializer, <vscale x 2 x i1> splat (i1 true), i32 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = zext i32 [[TMP3]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP4]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 4
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[FOR_BODY_2]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[FOR_BODY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY_1:.*]]
; CHECK:       [[FOR_BODY_1]]:
; CHECK-NEXT:    [[PHI3:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[ADD4:%.*]], %[[FOR_BODY_1]] ]
; CHECK-NEXT:    [[TRUNC:%.*]] = trunc i64 [[PHI]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[TRUNC]], 5
; CHECK-NEXT:    [[SHL:%.*]] = shl i32 0, [[ADD]]
; CHECK-NEXT:    store i32 [[SHL]], ptr null, align 4
; CHECK-NEXT:    [[ADD4]] = add i64 [[PHI3]], 1
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i64 [[ADD4]], 4
; CHECK-NEXT:    br i1 [[ICMP]], label %[[FOR_BODY_2]], label %[[FOR_BODY_1]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[FOR_BODY_2]]:
; CHECK-NEXT:    [[ADD6]] = add i64 [[PHI]], 1
; CHECK-NEXT:    br label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.body:
  %phi = phi i64 [ %add6, %for.body.2], [ 0, %entry ]
  br label %for.body.1

for.body.1:
  %phi3 = phi i64 [ 0, %for.body], [ %add4, %for.body.1 ]
  %trunc = trunc i64 %phi to i32
  %add = add i32 %trunc, 5
  %shl = shl i32 0, %add
  store i32 %shl, ptr null, align 4
  %add4 = add i64 %phi3, 1
  %icmp = icmp eq i64 %add4, 4
  br i1 %icmp, label %for.body.2, label %for.body.1

for.body.2:
  %add6 = add i64 %phi, 1
  br label %for.body
}

;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
