; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -S -mtriple riscv64-unknown-linux-gnu -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -mattr=+v < %s | FileCheck %s

define double @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  for.body.preheader:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond13.preheader.loopexit:
; CHECK-NEXT:    ret double 0.000000e+00
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER:%.*]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[ADD_PTR_I:%.*]] = getelementptr inbounds ptr, ptr undef, i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ADD_PTR_I]], align 8
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 100
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND13_PREHEADER_LOOPEXIT:%.*]], label [[FOR_BODY]]
;
for.body.preheader:
  br label %for.body

for.cond13.preheader.loopexit:
  ret double 0.000000e+00

for.body:
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.body ]
  %add.ptr.i = getelementptr inbounds i8*, i8** undef, i64 %indvars.iv
  %0 = load i8*, i8** %add.ptr.i, align 8
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 100
  br i1 %exitcond.not, label %for.cond13.preheader.loopexit, label %for.body
}
