; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -S -mtriple riscv64-unknown-linux-gnu -riscv-use-vla-vectorizer -riscv-v-vector-bits-min=128 -mattr="+64bit,+a,+c,+d,+f,+m,+v,+zicsr,+zifencei,+zvl128b,+zvl32b,+zvl64b" %s | FileCheck %s
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-linux-gnu"

%struct.CPpmd_State.19.114.124.235.343.467.495.627.635.651.662.682.701.702.704.722.741.759.778 = type { i8, i8, i16, i16 }

define void @Ppmd8_EncodeSymbol(ptr %p, i8 %0) {
; CHECK-LABEL: @Ppmd8_EncodeSymbol(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND179:%.*]]
; CHECK:       for.cond179.loopexit:
; CHECK-NEXT:    br label [[FOR_COND179]]
; CHECK:       for.cond179:
; CHECK-NEXT:    [[TMP1:%.*]] = phi i8 [ 1, [[ENTRY:%.*]] ], [ 0, [[FOR_COND179_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[CONV212:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    br label [[DO_BODY214:%.*]]
; CHECK:       do.body214:
; CHECK-NEXT:    [[INDVAR:%.*]] = phi i64 [ [[INDVAR_NEXT:%.*]], [[DO_COND274:%.*]] ], [ 0, [[FOR_COND179]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = phi i8 [ [[TMP0:%.*]], [[FOR_COND179]] ], [ 0, [[DO_COND274]] ]
; CHECK-NEXT:    [[S180_06:%.*]] = phi ptr [ null, [[FOR_COND179]] ], [ [[INCDEC_PTR270:%.*]], [[DO_COND274]] ]
; CHECK-NEXT:    [[I182_0:%.*]] = phi i32 [ [[CONV212]], [[FOR_COND179]] ], [ [[DEC275:%.*]], [[DO_COND274]] ]
; CHECK-NEXT:    [[CMP217:%.*]] = icmp eq i8 [[TMP2]], 0
; CHECK-NEXT:    br i1 [[CMP217]], label [[DO_BODY220_PREHEADER:%.*]], label [[DO_COND274]]
; CHECK:       do.body220.preheader:
; CHECK-NEXT:    [[INDVAR_LCSSA:%.*]] = phi i64 [ [[INDVAR]], [[DO_BODY214]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi i8 [ [[TMP1]], [[DO_BODY214]] ]
; CHECK-NEXT:    [[S180_06_LCSSA:%.*]] = phi ptr [ [[S180_06]], [[DO_BODY214]] ]
; CHECK-NEXT:    [[I182_0_LCSSA:%.*]] = phi i32 [ [[I182_0]], [[DO_BODY214]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = zext nneg i8 [[DOTLCSSA]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = add nuw nsw i64 [[TMP3]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = mul nsw i64 [[INDVAR_LCSSA]], -1
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ule i64 [[TMP6]], 1
; CHECK-NEXT:    br i1 [[TMP7]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP6]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[N_VEC]], i32 8, i1 true)
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 [[N_VEC]], 6
; CHECK-NEXT:    [[IND_END:%.*]] = getelementptr i8, ptr [[S180_06_LCSSA]], i64 [[TMP8]]
; CHECK-NEXT:    [[DOTCAST:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[IND_END4:%.*]] = sub i32 [[I182_0_LCSSA]], [[DOTCAST]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[N_VEC]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP12:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 8, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV1]], 6
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[S180_06_LCSSA]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds [[STRUCT_CPPMD_STATE_19_114_124_235_343_467_495_627_635_651_662_682_701_702_704_722_741_759_778:%.*]], ptr [[NEXT_GEP]], i64 0, i32 1
; CHECK-NEXT:    [[TMP15:%.*]] = mul nuw nsw i32 [[TMP12]], 6
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 48 x i8> @llvm.vp.load.nxv48i8.p0(ptr align 1 [[TMP14]], <vscale x 48 x i1> splat (i1 true), i32 [[TMP15]])
; CHECK-NEXT:    [[DEINTERLEAVED_RESULTS:%.*]] = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8> } @llvm.vector.deinterleave6.nxv48i8(<vscale x 48 x i8> [[WIDE_MASKED_LOAD]])
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8> } [[DEINTERLEAVED_RESULTS]], 0
; CHECK-NEXT:    [[VP_CAST:%.*]] = call <vscale x 8 x i32> @llvm.vp.zext.nxv8i32.nxv8i8(<vscale x 8 x i8> [[TMP16]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP12]])
; CHECK-NEXT:    [[TMP17:%.*]] = zext i32 [[TMP12]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP17]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP19:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP19]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP20:%.*]] = sub i32 [[TMP12]], 1
; CHECK-NEXT:    [[VECTOR_RECUR_EXTRACT:%.*]] = extractelement <vscale x 8 x i32> [[VP_CAST]], i32 [[TMP20]]
; CHECK-NEXT:    br label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[IND_END]], [[MIDDLE_BLOCK]] ], [ [[S180_06_LCSSA]], [[DO_BODY220_PREHEADER]] ]
; CHECK-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi i32 [ [[VECTOR_RECUR_EXTRACT]], [[MIDDLE_BLOCK]] ], [ 0, [[DO_BODY220_PREHEADER]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL5:%.*]] = phi i32 [ [[IND_END4]], [[MIDDLE_BLOCK]] ], [ [[I182_0_LCSSA]], [[DO_BODY220_PREHEADER]] ]
; CHECK-NEXT:    br label [[DO_BODY220:%.*]]
; CHECK:       do.body220:
; CHECK-NEXT:    [[S180_1:%.*]] = phi ptr [ [[INCDEC_PTR230:%.*]], [[DO_BODY220]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[SUM181_1:%.*]] = phi i32 [ [[AND228:%.*]], [[DO_BODY220]] ], [ [[SCALAR_RECUR_INIT]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[I182_1:%.*]] = phi i32 [ [[DEC232:%.*]], [[DO_BODY220]] ], [ [[BC_RESUME_VAL5]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[FREQ221:%.*]] = getelementptr inbounds [[STRUCT_CPPMD_STATE_19_114_124_235_343_467_495_627_635_651_662_682_701_702_704_722_741_759_778]], ptr [[S180_1]], i64 0, i32 1
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[FREQ221]], align 1
; CHECK-NEXT:    [[AND228]] = zext i8 [[TMP21]] to i32
; CHECK-NEXT:    [[INCDEC_PTR230]] = getelementptr inbounds [[STRUCT_CPPMD_STATE_19_114_124_235_343_467_495_627_635_651_662_682_701_702_704_722_741_759_778]], ptr [[S180_1]], i64 1
; CHECK-NEXT:    [[DEC232]] = add i32 [[I182_1]], -1
; CHECK-NEXT:    [[TOBOOL233_NOT:%.*]] = icmp eq i32 [[I182_1]], 0
; CHECK-NEXT:    br i1 [[TOBOOL233_NOT]], label [[DO_END234:%.*]], label [[DO_BODY220]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       do.end234:
; CHECK-NEXT:    [[SUM181_1_LCSSA:%.*]] = phi i32 [ [[SUM181_1]], [[DO_BODY220]] ]
; CHECK-NEXT:    store i32 [[SUM181_1_LCSSA]], ptr [[P:%.*]], align 8
; CHECK-NEXT:    ret void
; CHECK:       do.cond274:
; CHECK-NEXT:    [[INCDEC_PTR270]] = getelementptr inbounds [[STRUCT_CPPMD_STATE_19_114_124_235_343_467_495_627_635_651_662_682_701_702_704_722_741_759_778]], ptr [[S180_06]], i64 1
; CHECK-NEXT:    [[DEC275]] = add i32 [[I182_0]], -1
; CHECK-NEXT:    [[TOBOOL276_NOT:%.*]] = icmp eq i32 [[I182_0]], 0
; CHECK-NEXT:    [[INDVAR_NEXT]] = add i64 [[INDVAR]], 1
; CHECK-NEXT:    br i1 [[TOBOOL276_NOT]], label [[FOR_COND179_LOOPEXIT]], label [[DO_BODY214]]
;
entry:
  br label %for.cond179

for.cond179:                                      ; preds = %do.cond274, %entry
  %1 = phi i8 [ 0, %do.cond274 ], [ 1, %entry ]
  %conv212 = zext i8 %1 to i32
  br label %do.body214

do.body214:                                       ; preds = %do.cond274, %for.cond179
  %2 = phi i8 [ %0, %for.cond179 ], [ 0, %do.cond274 ]
  %s180.06 = phi ptr [ null, %for.cond179 ], [ %incdec.ptr270, %do.cond274 ]
  %i182.0 = phi i32 [ %conv212, %for.cond179 ], [ %dec275, %do.cond274 ]
  %cmp217 = icmp eq i8 %2, 0
  br i1 %cmp217, label %do.body220, label %do.cond274

do.body220:                                       ; preds = %do.body220, %do.body214
  %s180.1 = phi ptr [ %incdec.ptr230, %do.body220 ], [ %s180.06, %do.body214 ]
  %sum181.1 = phi i32 [ %and228, %do.body220 ], [ 0, %do.body214 ]
  %i182.1 = phi i32 [ %dec232, %do.body220 ], [ %i182.0, %do.body214 ]
  %Freq221 = getelementptr inbounds %struct.CPpmd_State.19.114.124.235.343.467.495.627.635.651.662.682.701.702.704.722.741.759.778, ptr %s180.1, i64 0, i32 1
  %3 = load i8, ptr %Freq221, align 1
  %and228 = zext i8 %3 to i32
  %incdec.ptr230 = getelementptr inbounds %struct.CPpmd_State.19.114.124.235.343.467.495.627.635.651.662.682.701.702.704.722.741.759.778, ptr %s180.1, i64 1
  %dec232 = add i32 %i182.1, -1
  %tobool233.not = icmp eq i32 %i182.1, 0
  br i1 %tobool233.not, label %do.end234, label %do.body220

do.end234:                                        ; preds = %do.body220
  store i32 %sum181.1, ptr %p, align 8
  ret void

do.cond274:                                       ; preds = %do.body214
  %incdec.ptr270 = getelementptr inbounds %struct.CPpmd_State.19.114.124.235.343.467.495.627.635.651.662.682.701.702.704.722.741.759.778, ptr %s180.06, i64 1
  %dec275 = add i32 %i182.0, -1
  %tobool276.not = icmp eq i32 %i182.0, 0
  br i1 %tobool276.not, label %for.cond179, label %do.body214
}
