; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -passes=loop-vectorize -riscv-use-vla-vectorizer=true -enable-vplan-native-path < %s | FileCheck %s --check-prefix=CHECK

define void @sct3433(ptr %g) {
; CHECK-LABEL: define void @sct3433(
; CHECK-SAME: ptr [[G:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 4
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 23, [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP2]], 4
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 23, [[TMP3]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 23, [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP5:%.*]] = mul nuw i64 [[TMP4]], 4
; CHECK-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-NEXT:    [[TMP8:%.*]] = mul <vscale x 4 x i64> [[TMP6]], splat (i64 1)
; CHECK-NEXT:    [[INDUCTION:%.*]] = add <vscale x 4 x i64> zeroinitializer, [[TMP8]]
; CHECK-NEXT:    [[TMP11:%.*]] = mul i64 1, [[TMP5]]
; CHECK-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP11]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[DOTSPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[FOR_OUTER_CLEANUP2:%.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i64> [ [[INDUCTION]], [[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], [[FOR_OUTER_CLEANUP2]] ]
; CHECK-NEXT:    br label [[FOR_BODY1:%.*]]
; CHECK:       for.body1:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i64> [ zeroinitializer, [[VECTOR_BODY]] ], [ [[TMP15:%.*]], [[FOR_BODY1]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = trunc <vscale x 4 x i64> [[VEC_PHI]] to <vscale x 4 x i32>
; CHECK-NEXT:    [[TMP13:%.*]] = mul nuw nsw <vscale x 4 x i64> [[VEC_PHI]], [[VEC_IND]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[G]], <vscale x 4 x i64> [[TMP13]]
; CHECK-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> [[TMP12]], <vscale x 4 x ptr> [[TMP14]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP15]] = add nuw nsw <vscale x 4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq <vscale x 4 x i64> [[TMP15]], splat (i64 7)
; CHECK-NEXT:    [[TMP17:%.*]] = extractelement <vscale x 4 x i1> [[TMP16]], i32 0
; CHECK-NEXT:    br i1 [[TMP17]], label [[FOR_OUTER_CLEANUP2]], label [[FOR_BODY1]]
; CHECK:       vector.latch:
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP5]]
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i64> [[VEC_IND]], [[DOTSPLAT]]
; CHECK-NEXT:    [[TMP20:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP20]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 23, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label [[EXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[FOR_OUTER_PREHEADER:%.*]]
; CHECK:       for.outer.preheader:
; CHECK-NEXT:    [[H_015_I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INC7_I:%.*]], [[FOR_OUTER_CLEANUP:%.*]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_014_I:%.*]] = phi i64 [ 0, [[FOR_OUTER_PREHEADER]] ], [ [[INC_I:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[CONV_I:%.*]] = trunc i64 [[I_014_I]] to i32
; CHECK-NEXT:    [[MUL_I:%.*]] = mul nuw nsw i64 [[I_014_I]], [[H_015_I]]
; CHECK-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds i32, ptr [[G]], i64 [[MUL_I]]
; CHECK-NEXT:    store i32 [[CONV_I]], ptr [[ARRAYIDX_I]], align 4
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i64 [[I_014_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i64 [[INC_I]], 7
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label [[FOR_OUTER_CLEANUP]], label [[FOR_BODY]]
; CHECK:       for.outer.cleanup:
; CHECK-NEXT:    [[INC7_I]] = add nuw nsw i64 [[H_015_I]], 1
; CHECK-NEXT:    [[EXITCOND16_NOT_I:%.*]] = icmp eq i64 [[INC7_I]], 23
; CHECK-NEXT:    br i1 [[EXITCOND16_NOT_I]], label [[EXIT]], label [[FOR_OUTER_PREHEADER]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.outer.preheader

for.outer.preheader:
  %h.015.i = phi i64 [ 0, %entry ], [ %inc7.i, %for.outer.cleanup ]
  br label %for.body

for.body:
  %i.014.i = phi i64 [ 0, %for.outer.preheader ], [ %inc.i, %for.body ]
  %conv.i = trunc i64 %i.014.i to i32
  %mul.i = mul nuw nsw i64 %i.014.i, %h.015.i
  %arrayidx.i = getelementptr inbounds i32, ptr %g, i64 %mul.i
  store i32 %conv.i, ptr %arrayidx.i, align 4
  %inc.i = add nuw nsw i64 %i.014.i, 1
  %exitcond.not.i = icmp eq i64 %inc.i, 7
  br i1 %exitcond.not.i, label %for.outer.cleanup, label %for.body

for.outer.cleanup:
  %inc7.i = add nuw nsw i64 %h.015.i, 1
  %exitcond16.not.i = icmp eq i64 %inc7.i, 23
  br i1 %exitcond16.not.i, label %exit, label %for.outer.preheader, !llvm.loop !0

exit:
  ret void
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.vectorize.enable", i1 true}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]]}
;.
