; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p670 -force-vectorization %s -S | FileCheck %s

define fastcc i32 @S_unpack_rec(i64 %0) {
; CHECK-LABEL: define fastcc i32 @S_unpack_rec(
; CHECK-SAME: i64 [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @llvm.experimental.get.vector.length.i32(i32 536870912, i32 4, i1 true)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 536870912, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i32(i32 [[TMP2]], i32 4, i1 true)
; CHECK-NEXT:    store i64 0, ptr null, align 8
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i32 [[TMP3]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[INDEX_EVL_NEXT]], 536870912
; CHECK-NEXT:    br i1 [[TMP4]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[BB9:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ 0, [[TMP1:%.*]] ]
; CHECK-NEXT:    br label %[[BB5:.*]]
; CHECK:       [[BB5]]:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i32 [ [[TMP7:%.*]], %[[BB5]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    store i64 0, ptr null, align 8
; CHECK-NEXT:    [[TMP7]] = add nsw i32 [[TMP6]], -8
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP6]], 1
; CHECK-NEXT:    br i1 [[TMP8]], label %[[BB9]], label %[[BB5]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[BB9]]:
; CHECK-NEXT:    [[TMP10:%.*]] = phi i64 [ [[TMP0]], %[[BB5]] ], [ [[TMP0]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret i32 0
;
  br label %2

2:
  %3 = phi i32 [ %4, %2 ], [ 0, %1 ]
  store i64 0, ptr null, align 8
  %4 = add nsw i32 %3, -8
  %5 = icmp eq i32 %3, 1
  br i1 %5, label %6, label %2

6:
  %7 = phi i64 [ %0, %2 ]
  ret i32 0
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
