; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -passes=loop-vectorize -mtriple riscv64-unknown-linux-gnu -riscv-use-vla-vectorizer -mcpu=sifive-x280n %s | FileCheck %s

define i32 @test() {
; CHECK-LABEL: define i32 @test
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 1024, i32 8, i1 true)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 1024, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 8, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 1, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr double, ptr null, i64 [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr double, ptr [[TMP3]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 8 x double> @llvm.vp.load.nxv8f64.p0(ptr align 8 [[TMP4]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv8f64.nxv8p0(<vscale x 8 x double> [[VP_OP_LOAD]], <vscale x 8 x ptr> align 8 zeroinitializer, <vscale x 8 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP5]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[FOR_EXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[FOR_PH:%.*]]
; CHECK:       for.ph:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], [[FOR_COND:%.*]] ]
; CHECK-NEXT:    br i1 false, label [[FOR_COND_LCSSA:%.*]], label [[FOR_BODY:%.*]]
; CHECK:       for.exit:
; CHECK-NEXT:    ret i32 0
; CHECK:       for.cond.lcssa:
; CHECK-NEXT:    [[INDVARS_IV_I201_UNR_I:%.*]] = phi i64 [ 1, [[FOR_BODY]] ], [ 0, [[FOR_PH]] ]
; CHECK-NEXT:    br i1 false, label [[FOR_COND]], label [[FOR_EPILOGUE:%.*]]
; CHECK:       for.epilogue:
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[INDVARS_IV_I201_UNR_I]], [[IV]]
; CHECK-NEXT:    [[ARRAYIDX_I61_I203_EPIL_I:%.*]] = getelementptr double, ptr null, i64 [[TMP7]]
; CHECK-NEXT:    [[TMP8:%.*]] = load double, ptr [[ARRAYIDX_I61_I203_EPIL_I]], align 8
; CHECK-NEXT:    store double [[TMP8]], ptr null, align 8
; CHECK-NEXT:    br label [[FOR_COND]]
; CHECK:       for.cond:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND83_NOT_I199_I:%.*]] = icmp eq i64 [[IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND83_NOT_I199_I]], label [[FOR_EXIT]], label [[FOR_PH]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       for.body:
; CHECK-NEXT:    br label [[FOR_COND_LCSSA]]
;

entry:
  br label %for.ph

for.ph:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.cond ]
  br i1 false, label %for.cond.lcssa, label %for.body

for.exit:                ; preds = %for.cond
  ret i32 0

for.cond.lcssa:
  %indvars.iv.i201.unr.i = phi i64 [ 1, %for.body ], [ 0, %for.ph ]
  br i1 false, label %for.cond, label %for.epilogue

for.epilogue:
  %0 = add i64 %indvars.iv.i201.unr.i, %iv
  %arrayidx.i61.i203.epil.i = getelementptr double, ptr null, i64 %0
  %1 = load double, ptr %arrayidx.i61.i203.epil.i, align 8
  store double %1, ptr null, align 8
  br label %for.cond

for.cond:
  %iv.next = add i64 %iv, 1
  %exitcond83.not.i199.i = icmp eq i64 %iv.next, 1024
  br i1 %exitcond83.not.i199.i, label %for.exit, label %for.ph

for.body:
  br label %for.cond.lcssa
}
