; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -sifive-loop-vectorizer-enable-interleaved-access=invariant-stride -force-vectorization -passes=loop-vectorize %s | FileCheck %s

%class.SparseMatrixEZ.16 = type <{ %class.Subscriptor, i32, [4 x i8], %"class.std::vector.17", %"class.std::vector.22", i32, [4 x i8] }>
%class.Subscriptor = type { ptr, i32, ptr }
%"class.std::vector.17" = type { %"struct.std::_Vector_base.18" }
%"struct.std::_Vector_base.18" = type { %"struct.std::_Vector_base<SparseMatrixEZ<float>::RowInfo, std::allocator<SparseMatrixEZ<float>::RowInfo> >::_Vector_impl" }
%"struct.std::_Vector_base<SparseMatrixEZ<float>::RowInfo, std::allocator<SparseMatrixEZ<float>::RowInfo> >::_Vector_impl" = type { %"struct.std::_Vector_base<SparseMatrixEZ<float>::RowInfo, std::allocator<SparseMatrixEZ<float>::RowInfo> >::_Vector_impl_data" }
%"struct.std::_Vector_base<SparseMatrixEZ<float>::RowInfo, std::allocator<SparseMatrixEZ<float>::RowInfo> >::_Vector_impl_data" = type { ptr, ptr, ptr }
%"class.std::vector.22" = type { %"struct.std::_Vector_base.23" }
%"struct.std::_Vector_base.23" = type { %"struct.std::_Vector_base<SparseMatrixEZ<float>::Entry, std::allocator<SparseMatrixEZ<float>::Entry> >::_Vector_impl" }
%"struct.std::_Vector_base<SparseMatrixEZ<float>::Entry, std::allocator<SparseMatrixEZ<float>::Entry> >::_Vector_impl" = type { %"struct.std::_Vector_base<SparseMatrixEZ<float>::Entry, std::allocator<SparseMatrixEZ<float>::Entry> >::_Vector_impl_data" }
%"struct.std::_Vector_base<SparseMatrixEZ<float>::Entry, std::allocator<SparseMatrixEZ<float>::Entry> >::_Vector_impl_data" = type { ptr, ptr, ptr }

define void @test(i32 %0, i64 %conv, ptr %call5.i.i.i4.i.i101) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[TMP0:%.*]], i64 [[CONV:%.*]], ptr [[CALL5_I_I_I4_I_I101:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[CONV]], 1
; CHECK-NEXT:    [[TMP15:%.*]] = sext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[TMP16:%.*]] = mul nsw i64 [[TMP15]], 88
; CHECK-NEXT:    [[TMP17:%.*]] = lshr i64 [[TMP16]], 3
; CHECK-NEXT:    [[TMP27:%.*]] = shl nuw i64 [[TMP17]], 3
; CHECK-NEXT:    br label [[VECTOR_SCEVCHECK:%.*]]
; CHECK:       vector.scevcheck:
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 0, [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = icmp slt i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP4:%.*]] = select i1 [[TMP3]], i32 [[TMP2]], i32 [[TMP0]]
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[CONV]] to i32
; CHECK-NEXT:    [[MUL:%.*]] = call { i32, i1 } @llvm.umul.with.overflow.i32(i32 [[TMP4]], i32 [[TMP5]])
; CHECK-NEXT:    [[MUL_RESULT:%.*]] = extractvalue { i32, i1 } [[MUL]], 0
; CHECK-NEXT:    [[MUL_OVERFLOW:%.*]] = extractvalue { i32, i1 } [[MUL]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = sub i32 0, [[MUL_RESULT]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ugt i32 [[TMP6]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = select i1 [[TMP3]], i1 [[TMP7]], i1 false
; CHECK-NEXT:    [[TMP9:%.*]] = or i1 [[TMP8]], [[MUL_OVERFLOW]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ugt i64 [[CONV]], 4294967295
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ne i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = and i1 [[TMP10]], [[TMP11]]
; CHECK-NEXT:    [[TMP13:%.*]] = or i1 [[TMP9]], [[TMP12]]
; CHECK-NEXT:    br i1 [[TMP13]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP14:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP1]], i32 1, i1 true)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP1]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP19:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 1, i1 true)
; CHECK-NEXT:    [[TMP20:%.*]] = trunc i64 [[EVL_BASED_IV1]] to i32
; CHECK-NEXT:    [[TMP21:%.*]] = mul i32 [[TMP20]], [[TMP0]]
; CHECK-NEXT:    [[TMP22:%.*]] = zext i32 [[TMP21]] to i64
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr [[CLASS_SPARSEMATRIXEZ_16:%.*]], ptr null, i64 [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = getelementptr i8, ptr [[TMP23]], i64 32
; CHECK-NEXT:    [[WIDE_STRIDED_LOAD:%.*]] = call <vscale x 1 x i128> @llvm.experimental.vp.strided.load.nxv1i128.p0.i64(ptr align 8 [[TMP24]], i64 [[TMP27]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP19]])
; CHECK-NEXT:    [[WIDE_STRIDED_LOAD_INTCAST:%.*]] = bitcast <vscale x 1 x i128> [[WIDE_STRIDED_LOAD]] to <vscale x 2 x i64>
; CHECK-NEXT:    [[WIDE_STRIDED_LOAD_INTCAST_CAST:%.*]] = inttoptr <vscale x 2 x i64> [[WIDE_STRIDED_LOAD_INTCAST]] to <vscale x 2 x ptr>
; CHECK-NEXT:    [[DEINTERLEAVED_RESULTS:%.*]] = call { <vscale x 1 x ptr>, <vscale x 1 x ptr> } @llvm.vector.deinterleave2.nxv2p0(<vscale x 2 x ptr> [[WIDE_STRIDED_LOAD_INTCAST_CAST]])
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <vscale x 1 x ptr>, <vscale x 1 x ptr> } [[DEINTERLEAVED_RESULTS]], 0
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <vscale x 1 x ptr>, <vscale x 1 x ptr> } [[DEINTERLEAVED_RESULTS]], 1
; CHECK-NEXT:    [[VP_CAST:%.*]] = call <vscale x 1 x i64> @llvm.vp.ptrtoint.nxv1i64.nxv1p0(<vscale x 1 x ptr> [[TMP26]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP19]])
; CHECK-NEXT:    [[VP_CAST1:%.*]] = call <vscale x 1 x i64> @llvm.vp.ptrtoint.nxv1i64.nxv1p0(<vscale x 1 x ptr> [[TMP25]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP19]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64> [[VP_CAST]], <vscale x 1 x i64> [[VP_CAST1]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP19]])
; CHECK-NEXT:    [[VP_CAST2:%.*]] = call <vscale x 1 x i32> @llvm.vp.trunc.nxv1i32.nxv1i64(<vscale x 1 x i64> [[VP_OP]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP19]])
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr i32, ptr [[CALL5_I_I_I4_I_I101]], i64 [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr i32, ptr [[TMP30]], i32 0
; CHECK-NEXT:    call void @llvm.vp.store.nxv1i32.p0(<vscale x 1 x i32> [[VP_CAST2]], ptr align 4 [[TMP31]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP19]])
; CHECK-NEXT:    [[TMP29:%.*]] = zext i32 [[TMP19]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP29]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP32:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP1]]
; CHECK-NEXT:    br i1 [[TMP32]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP21:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    br label [[INVOKE_CONT14:%.*]]
; CHECK:       invoke.cont14:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[INVOKE_CONT14]] ]
; CHECK-NEXT:    [[TMP35:%.*]] = trunc i64 [[INDVARS_IV]] to i32
; CHECK-NEXT:    [[MUL_I:%.*]] = mul i32 [[TMP35]], [[TMP0]]
; CHECK-NEXT:    [[IDX_EXT_I:%.*]] = zext i32 [[MUL_I]] to i64
; CHECK-NEXT:    [[ADD_PTR_I:%.*]] = getelementptr [[CLASS_SPARSEMATRIXEZ_16]], ptr null, i64 [[IDX_EXT_I]]
; CHECK-NEXT:    [[ROW_INFO_I:%.*]] = getelementptr i8, ptr [[ADD_PTR_I]], i64 32
; CHECK-NEXT:    [[_M_FINISH_I_I:%.*]] = getelementptr i8, ptr [[ADD_PTR_I]], i64 40
; CHECK-NEXT:    [[TMP36:%.*]] = load ptr, ptr [[_M_FINISH_I_I]], align 8
; CHECK-NEXT:    [[TMP37:%.*]] = load ptr, ptr [[ROW_INFO_I]], align 8
; CHECK-NEXT:    [[SUB_PTR_LHS_CAST_I_I:%.*]] = ptrtoint ptr [[TMP36]] to i64
; CHECK-NEXT:    [[SUB_PTR_RHS_CAST_I_I:%.*]] = ptrtoint ptr [[TMP37]] to i64
; CHECK-NEXT:    [[SUB_PTR_SUB_I_I:%.*]] = or i64 [[SUB_PTR_LHS_CAST_I_I]], [[SUB_PTR_RHS_CAST_I_I]]
; CHECK-NEXT:    [[CONV_I:%.*]] = trunc i64 [[SUB_PTR_SUB_I_I]] to i32
; CHECK-NEXT:    [[ADD_PTR_I117:%.*]] = getelementptr i32, ptr [[CALL5_I_I_I4_I_I101]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[CONV_I]], ptr [[ADD_PTR_I117]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV]], [[CONV]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP21]], label [[INVOKE_CONT14]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       for.cond.cleanup21:
; CHECK-NEXT:    ret void
;
entry:
  br label %invoke.cont14

invoke.cont14:
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %invoke.cont14 ]
  %1 = trunc i64 %indvars.iv to i32
  %mul.i = mul i32 %1, %0
  %idx.ext.i = zext i32 %mul.i to i64
  %add.ptr.i = getelementptr %class.SparseMatrixEZ.16, ptr null, i64 %idx.ext.i
  %row_info.i = getelementptr i8, ptr %add.ptr.i, i64 32
  %_M_finish.i.i = getelementptr i8, ptr %add.ptr.i, i64 40
  %2 = load ptr, ptr %_M_finish.i.i, align 8
  %3 = load ptr, ptr %row_info.i, align 8
  %sub.ptr.lhs.cast.i.i = ptrtoint ptr %2 to i64
  %sub.ptr.rhs.cast.i.i = ptrtoint ptr %3 to i64
  %sub.ptr.sub.i.i = or i64 %sub.ptr.lhs.cast.i.i, %sub.ptr.rhs.cast.i.i
  %conv.i = trunc i64 %sub.ptr.sub.i.i to i32
  %add.ptr.i117 = getelementptr i32, ptr %call5.i.i.i4.i.i101, i64 %indvars.iv
  store i32 %conv.i, ptr %add.ptr.i117, align 4
  %indvars.iv.next = add i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv, %conv
  br i1 %exitcond.not, label %for.cond.cleanup21, label %invoke.cont14

for.cond.cleanup21:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]]}
;.
