; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;RUN: opt -passes=loop-vectorize -S -mtriple riscv64-unknown-linux-gnu -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -riscv-v-vector-bits-min=128 -mattr="+64bit,+a,+c,+d,+f,+m,+v,+zicsr,+zifencei,+zvl128b,+zvl32b,+zvl64b" < %s | FileCheck %s --check-prefix=SCALABLE

define void @test() {
; SCALABLE-LABEL: @test(
; SCALABLE-NEXT:  entry:
; SCALABLE-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; SCALABLE:       vector.ph:
; SCALABLE-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 7, i32 2, i1 true)
; SCALABLE-NEXT:    br label [[VECTOR_BODY:%.*]]
; SCALABLE:       vector.body:
; SCALABLE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[TMP0:%.*]] = sub i64 7, [[EVL_BASED_IV]]
; SCALABLE-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; SCALABLE-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [125 x i32], ptr undef, i64 0, i64 [[EVL_BASED_IV]]
; SCALABLE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i32 0
; SCALABLE-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> zeroinitializer, ptr align 4 [[TMP4]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP1]])
; SCALABLE-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP1]] to i64
; SCALABLE-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP5]], [[EVL_BASED_IV]]
; SCALABLE-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 7
; SCALABLE-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; SCALABLE:       middle.block:
; SCALABLE-NEXT:    br label [[FOR_COND_PREHEADER:%.*]]
; SCALABLE:       scalar.ph:
; SCALABLE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; SCALABLE-NEXT:    br label [[FOR_BODY_I:%.*]]
; SCALABLE:       for.body.i:
; SCALABLE-NEXT:    [[INDVARS_IV_I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT_I:%.*]], [[FOR_BODY_I]] ]
; SCALABLE-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds [125 x i32], ptr undef, i64 0, i64 [[INDVARS_IV_I]]
; SCALABLE-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX_I]], align 4
; SCALABLE-NEXT:    [[ARRAYIDX2_I:%.*]] = getelementptr inbounds [125 x i32], ptr undef, i64 0, i64 [[INDVARS_IV_I]]
; SCALABLE-NEXT:    store i32 0, ptr [[ARRAYIDX2_I]], align 4
; SCALABLE-NEXT:    [[INDVARS_IV_NEXT_I]] = add nuw nsw i64 [[INDVARS_IV_I]], 1
; SCALABLE-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i64 [[INDVARS_IV_I]], 6
; SCALABLE-NEXT:    br i1 [[EXITCOND_NOT_I]], label [[FOR_COND_PREHEADER]], label [[FOR_BODY_I]], !llvm.loop [[LOOP3:![0-9]+]]
; SCALABLE:       for.cond.preheader:
; SCALABLE-NEXT:    ret void
;
entry:
  br label %for.body.i

for.body.i:
  %indvars.iv.i = phi i64 [ 0, %entry ], [ %indvars.iv.next.i, %for.body.i ]
  %arrayidx.i = getelementptr inbounds [125 x i32], [125 x i32]* undef, i64 0, i64 %indvars.iv.i
  %0 = load i32, i32* %arrayidx.i, align 4
  %arrayidx2.i = getelementptr inbounds [125 x i32], [125 x i32]* undef, i64 0, i64 %indvars.iv.i
  store i32 0, i32* %arrayidx2.i, align 4
  %indvars.iv.next.i = add nuw nsw i64 %indvars.iv.i, 1
  %exitcond.not.i = icmp eq i64 %indvars.iv.i, 6
  br i1 %exitcond.not.i, label %for.cond.preheader, label %for.body.i

for.cond.preheader:
  ret void
}
