; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt --passes=loop-vectorize \
; RUN: -vector-primary-lmul-max=3 \
; RUN: -mtriple riscv64 -mcpu=sifive-x280 < %s -S |\
; RUN: FileCheck %s --check-prefixes=X280
;
; RUN: opt --passes=loop-vectorize \
; RUN: -vector-primary-lmul-max=3 \
; RUN: -mtriple riscv64 -mcpu=sifive-x390 < %s -S |\
; RUN: FileCheck %s --check-prefixes=X390

; Not selecting lmul 8 in this case.
define float @P7Viterbi(ptr noundef %dsq, i64 noundef signext %L, ptr noundef %hmm, ptr noundef %mx, i32 %int321, ptr noalias %0, ptr noalias %1, ptr noalias %2, ptr noalias %3, ptr noalias %4, ptr noalias %5, ptr noalias %6) {
; X280-LABEL: define float @P7Viterbi(
; X280-SAME: ptr noundef [[DSQ:%.*]], i64 noundef signext [[L:%.*]], ptr noundef [[HMM:%.*]], ptr noundef [[MX:%.*]], i32 [[INT321:%.*]], ptr noalias [[TMP0:%.*]], ptr noalias [[TMP1:%.*]], ptr noalias [[TMP2:%.*]], ptr noalias [[TMP3:%.*]], ptr noalias [[TMP4:%.*]], ptr noalias [[TMP5:%.*]], ptr noalias [[TMP6:%.*]]) #[[ATTR0:[0-9]+]] {
; X280-NEXT:  [[ENTRY:.*]]:
; X280-NEXT:    [[TMP7:%.*]] = add i64 [[L]], -1
; X280-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; X280:       [[VECTOR_PH]]:
; X280-NEXT:    [[TMP10:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP7]], i32 8, i1 true)
; X280-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i32> poison, i32 [[INT321]], i64 0
; X280-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer
; X280-NEXT:    br label %[[VECTOR_BODY:.*]]
; X280:       [[VECTOR_BODY]]:
; X280-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; X280-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; X280-NEXT:    [[TMP8:%.*]] = sub i64 [[TMP7]], [[EVL_BASED_IV]]
; X280-NEXT:    [[TMP9:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP8]], i32 8, i1 true)
; X280-NEXT:    [[OFFSET_IDX:%.*]] = add i64 1, [[EVL_BASED_IV]]
; X280-NEXT:    [[TMP11:%.*]] = add nsw i64 [[OFFSET_IDX]], -1
; X280-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[DSQ]], i64 [[TMP11]]
; X280-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[TMP12]], i32 0
; X280-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP13]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[HMM]], i64 [[TMP11]]
; X280-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[TMP14]], i32 0
; X280-NEXT:    [[VP_OP_LOAD1:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP15]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD1]], <vscale x 8 x i32> [[VP_OP_LOAD]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[OFFSET_IDX]]
; X280-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i32 0
; X280-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[TMP11]]
; X280-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i32, ptr [[TMP18]], i32 0
; X280-NEXT:    [[VP_OP_LOAD2:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP19]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 [[TMP11]]
; X280-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP20]], i32 0
; X280-NEXT:    [[VP_OP_LOAD3:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP21]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP4:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD3]], <vscale x 8 x i32> [[VP_OP_LOAD2]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP5:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP4]], <vscale x 8 x i32> [[VP_OP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP5]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 [[TMP11]]
; X280-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i32, ptr [[TMP22]], i32 0
; X280-NEXT:    [[VP_OP_LOAD6:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP23]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 [[TMP11]]
; X280-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP24]], i32 0
; X280-NEXT:    [[VP_OP_LOAD7:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP25]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP8:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD7]], <vscale x 8 x i32> [[VP_OP_LOAD6]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP9:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP8]], <vscale x 8 x i32> [[VP_OP5]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP9]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[OFFSET_IDX]]
; X280-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[TMP26]], i32 0
; X280-NEXT:    [[VP_OP_LOAD10:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP27]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP11:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD10]], <vscale x 8 x i32> [[BROADCAST_SPLAT]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP12:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP11]], <vscale x 8 x i32> [[VP_OP9]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP12]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 [[OFFSET_IDX]]
; X280-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i32, ptr [[TMP28]], i32 0
; X280-NEXT:    [[VP_OP_LOAD13:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP29]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP14:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP12]], <vscale x 8 x i32> [[VP_OP_LOAD13]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[VP_OP15:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP14]], <vscale x 8 x i32> splat (i32 -987654321), <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP15]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X280-NEXT:    [[TMP31:%.*]] = zext i32 [[TMP9]] to i64
; X280-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP31]], [[EVL_BASED_IV]]
; X280-NEXT:    [[TMP30:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP7]]
; X280-NEXT:    br i1 [[TMP30]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; X280:       [[MIDDLE_BLOCK]]:
; X280-NEXT:    br label %[[FOR_EXIT:.*]]
; X280:       [[SCALAR_PH]]:
; X280-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 1, %[[ENTRY]] ]
; X280-NEXT:    br label %[[FOR_BODY:.*]]
; X280:       [[FOR_BODY]]:
; X280-NEXT:    [[INDVARS_IV179_LDIST1:%.*]] = phi i64 [ [[INDVARS_IV_NEXT180_LDIST1:%.*]], %[[FOR_BODY]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; X280-NEXT:    [[TMP33:%.*]] = add nsw i64 [[INDVARS_IV179_LDIST1]], -1
; X280-NEXT:    [[ARRAYIDX75_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[DSQ]], i64 [[TMP33]]
; X280-NEXT:    [[TMP34:%.*]] = load i32, ptr [[ARRAYIDX75_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX78_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[HMM]], i64 [[TMP33]]
; X280-NEXT:    [[TMP35:%.*]] = load i32, ptr [[ARRAYIDX78_LDIST1]], align 4
; X280-NEXT:    [[ADD_LDIST1:%.*]] = add nsw i32 [[TMP35]], [[TMP34]]
; X280-NEXT:    [[ARRAYIDX80_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[INDVARS_IV179_LDIST1]]
; X280-NEXT:    store i32 [[ADD_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX83_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[TMP33]]
; X280-NEXT:    [[TMP36:%.*]] = load i32, ptr [[ARRAYIDX83_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX86_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 [[TMP33]]
; X280-NEXT:    [[TMP37:%.*]] = load i32, ptr [[ARRAYIDX86_LDIST1]], align 4
; X280-NEXT:    [[ADD87_LDIST1:%.*]] = add nsw i32 [[TMP37]], [[TMP36]]
; X280-NEXT:    [[SPEC_STORE_SELECT_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD87_LDIST1]], i32 [[ADD_LDIST1]])
; X280-NEXT:    store i32 [[SPEC_STORE_SELECT_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX96_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 [[TMP33]]
; X280-NEXT:    [[TMP38:%.*]] = load i32, ptr [[ARRAYIDX96_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX99_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 [[TMP33]]
; X280-NEXT:    [[TMP39:%.*]] = load i32, ptr [[ARRAYIDX99_LDIST1]], align 4
; X280-NEXT:    [[ADD100_LDIST1:%.*]] = add nsw i32 [[TMP39]], [[TMP38]]
; X280-NEXT:    [[SPEC_STORE_SELECT157_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD100_LDIST1]], i32 [[SPEC_STORE_SELECT_LDIST1]])
; X280-NEXT:    store i32 [[SPEC_STORE_SELECT157_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX110_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[INDVARS_IV179_LDIST1]]
; X280-NEXT:    [[TMP40:%.*]] = load i32, ptr [[ARRAYIDX110_LDIST1]], align 4
; X280-NEXT:    [[ADD111_LDIST1:%.*]] = add nsw i32 [[TMP40]], [[INT321]]
; X280-NEXT:    [[SPEC_STORE_SELECT160_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD111_LDIST1]], i32 [[SPEC_STORE_SELECT157_LDIST1]])
; X280-NEXT:    store i32 [[SPEC_STORE_SELECT160_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X280-NEXT:    [[ARRAYIDX121_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 [[INDVARS_IV179_LDIST1]]
; X280-NEXT:    [[TMP41:%.*]] = load i32, ptr [[ARRAYIDX121_LDIST1]], align 4
; X280-NEXT:    [[ADD124_LDIST1:%.*]] = add nsw i32 [[SPEC_STORE_SELECT160_LDIST1]], [[TMP41]]
; X280-NEXT:    [[SPEC_SELECT_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD124_LDIST1]], i32 -987654321)
; X280-NEXT:    store i32 [[SPEC_SELECT_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X280-NEXT:    [[INDVARS_IV_NEXT180_LDIST1]] = add nuw nsw i64 [[INDVARS_IV179_LDIST1]], 1
; X280-NEXT:    [[EXITCOND_NOT_LDIST1:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT180_LDIST1]], [[L]]
; X280-NEXT:    br i1 [[EXITCOND_NOT_LDIST1]], label %[[FOR_EXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; X280:       [[FOR_EXIT]]:
; X280-NEXT:    ret float 0.000000e+00
;
; X390-LABEL: define float @P7Viterbi(
; X390-SAME: ptr noundef [[DSQ:%.*]], i64 noundef signext [[L:%.*]], ptr noundef [[HMM:%.*]], ptr noundef [[MX:%.*]], i32 [[INT321:%.*]], ptr noalias [[TMP0:%.*]], ptr noalias [[TMP1:%.*]], ptr noalias [[TMP2:%.*]], ptr noalias [[TMP3:%.*]], ptr noalias [[TMP4:%.*]], ptr noalias [[TMP5:%.*]], ptr noalias [[TMP6:%.*]]) #[[ATTR0:[0-9]+]] {
; X390-NEXT:  [[ENTRY:.*]]:
; X390-NEXT:    [[TMP7:%.*]] = add i64 [[L]], -1
; X390-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; X390:       [[VECTOR_PH]]:
; X390-NEXT:    [[TMP10:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP7]], i32 8, i1 true)
; X390-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i32> poison, i32 [[INT321]], i64 0
; X390-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer
; X390-NEXT:    br label %[[VECTOR_BODY:.*]]
; X390:       [[VECTOR_BODY]]:
; X390-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; X390-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; X390-NEXT:    [[TMP8:%.*]] = sub i64 [[TMP7]], [[EVL_BASED_IV]]
; X390-NEXT:    [[TMP9:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP8]], i32 8, i1 true)
; X390-NEXT:    [[OFFSET_IDX:%.*]] = add i64 1, [[EVL_BASED_IV]]
; X390-NEXT:    [[TMP11:%.*]] = add nsw i64 [[OFFSET_IDX]], -1
; X390-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[DSQ]], i64 [[TMP11]]
; X390-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[TMP12]], i32 0
; X390-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP13]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[HMM]], i64 [[TMP11]]
; X390-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[TMP14]], i32 0
; X390-NEXT:    [[VP_OP_LOAD1:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP15]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD1]], <vscale x 8 x i32> [[VP_OP_LOAD]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[OFFSET_IDX]]
; X390-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[TMP16]], i32 0
; X390-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[TMP11]]
; X390-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i32, ptr [[TMP18]], i32 0
; X390-NEXT:    [[VP_OP_LOAD2:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP19]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 [[TMP11]]
; X390-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP20]], i32 0
; X390-NEXT:    [[VP_OP_LOAD3:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP21]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP4:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD3]], <vscale x 8 x i32> [[VP_OP_LOAD2]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP5:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP4]], <vscale x 8 x i32> [[VP_OP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP5]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 [[TMP11]]
; X390-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i32, ptr [[TMP22]], i32 0
; X390-NEXT:    [[VP_OP_LOAD6:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP23]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 [[TMP11]]
; X390-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP24]], i32 0
; X390-NEXT:    [[VP_OP_LOAD7:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP25]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP8:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD7]], <vscale x 8 x i32> [[VP_OP_LOAD6]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP9:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP8]], <vscale x 8 x i32> [[VP_OP5]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP9]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[OFFSET_IDX]]
; X390-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[TMP26]], i32 0
; X390-NEXT:    [[VP_OP_LOAD10:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP27]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP11:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP_LOAD10]], <vscale x 8 x i32> [[BROADCAST_SPLAT]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP12:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP11]], <vscale x 8 x i32> [[VP_OP9]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP12]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 [[OFFSET_IDX]]
; X390-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i32, ptr [[TMP28]], i32 0
; X390-NEXT:    [[VP_OP_LOAD13:%.*]] = call <vscale x 8 x i32> @llvm.vp.load.nxv8i32.p0(ptr align 4 [[TMP29]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP14:%.*]] = call <vscale x 8 x i32> @llvm.vp.add.nxv8i32(<vscale x 8 x i32> [[VP_OP12]], <vscale x 8 x i32> [[VP_OP_LOAD13]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[VP_OP15:%.*]] = call <vscale x 8 x i32> @llvm.vp.smax.nxv8i32(<vscale x 8 x i32> [[VP_OP14]], <vscale x 8 x i32> splat (i32 -987654321), <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    call void @llvm.vp.store.nxv8i32.p0(<vscale x 8 x i32> [[VP_OP15]], ptr align 4 [[TMP17]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP9]])
; X390-NEXT:    [[TMP31:%.*]] = zext i32 [[TMP9]] to i64
; X390-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP31]], [[EVL_BASED_IV]]
; X390-NEXT:    [[TMP30:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP7]]
; X390-NEXT:    br i1 [[TMP30]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; X390:       [[MIDDLE_BLOCK]]:
; X390-NEXT:    br label %[[FOR_EXIT:.*]]
; X390:       [[SCALAR_PH]]:
; X390-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 1, %[[ENTRY]] ]
; X390-NEXT:    br label %[[FOR_BODY:.*]]
; X390:       [[FOR_BODY]]:
; X390-NEXT:    [[INDVARS_IV179_LDIST1:%.*]] = phi i64 [ [[INDVARS_IV_NEXT180_LDIST1:%.*]], %[[FOR_BODY]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; X390-NEXT:    [[TMP33:%.*]] = add nsw i64 [[INDVARS_IV179_LDIST1]], -1
; X390-NEXT:    [[ARRAYIDX75_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[DSQ]], i64 [[TMP33]]
; X390-NEXT:    [[TMP34:%.*]] = load i32, ptr [[ARRAYIDX75_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX78_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[HMM]], i64 [[TMP33]]
; X390-NEXT:    [[TMP35:%.*]] = load i32, ptr [[ARRAYIDX78_LDIST1]], align 4
; X390-NEXT:    [[ADD_LDIST1:%.*]] = add nsw i32 [[TMP35]], [[TMP34]]
; X390-NEXT:    [[ARRAYIDX80_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 [[INDVARS_IV179_LDIST1]]
; X390-NEXT:    store i32 [[ADD_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX83_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[TMP33]]
; X390-NEXT:    [[TMP36:%.*]] = load i32, ptr [[ARRAYIDX83_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX86_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 [[TMP33]]
; X390-NEXT:    [[TMP37:%.*]] = load i32, ptr [[ARRAYIDX86_LDIST1]], align 4
; X390-NEXT:    [[ADD87_LDIST1:%.*]] = add nsw i32 [[TMP37]], [[TMP36]]
; X390-NEXT:    [[SPEC_STORE_SELECT_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD87_LDIST1]], i32 [[ADD_LDIST1]])
; X390-NEXT:    store i32 [[SPEC_STORE_SELECT_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX96_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 [[TMP33]]
; X390-NEXT:    [[TMP38:%.*]] = load i32, ptr [[ARRAYIDX96_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX99_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 [[TMP33]]
; X390-NEXT:    [[TMP39:%.*]] = load i32, ptr [[ARRAYIDX99_LDIST1]], align 4
; X390-NEXT:    [[ADD100_LDIST1:%.*]] = add nsw i32 [[TMP39]], [[TMP38]]
; X390-NEXT:    [[SPEC_STORE_SELECT157_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD100_LDIST1]], i32 [[SPEC_STORE_SELECT_LDIST1]])
; X390-NEXT:    store i32 [[SPEC_STORE_SELECT157_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX110_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[INDVARS_IV179_LDIST1]]
; X390-NEXT:    [[TMP40:%.*]] = load i32, ptr [[ARRAYIDX110_LDIST1]], align 4
; X390-NEXT:    [[ADD111_LDIST1:%.*]] = add nsw i32 [[TMP40]], [[INT321]]
; X390-NEXT:    [[SPEC_STORE_SELECT160_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD111_LDIST1]], i32 [[SPEC_STORE_SELECT157_LDIST1]])
; X390-NEXT:    store i32 [[SPEC_STORE_SELECT160_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X390-NEXT:    [[ARRAYIDX121_LDIST1:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 [[INDVARS_IV179_LDIST1]]
; X390-NEXT:    [[TMP41:%.*]] = load i32, ptr [[ARRAYIDX121_LDIST1]], align 4
; X390-NEXT:    [[ADD124_LDIST1:%.*]] = add nsw i32 [[SPEC_STORE_SELECT160_LDIST1]], [[TMP41]]
; X390-NEXT:    [[SPEC_SELECT_LDIST1:%.*]] = call i32 @llvm.smax.i32(i32 [[ADD124_LDIST1]], i32 -987654321)
; X390-NEXT:    store i32 [[SPEC_SELECT_LDIST1]], ptr [[ARRAYIDX80_LDIST1]], align 4
; X390-NEXT:    [[INDVARS_IV_NEXT180_LDIST1]] = add nuw nsw i64 [[INDVARS_IV179_LDIST1]], 1
; X390-NEXT:    [[EXITCOND_NOT_LDIST1:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT180_LDIST1]], [[L]]
; X390-NEXT:    br i1 [[EXITCOND_NOT_LDIST1]], label %[[FOR_EXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; X390:       [[FOR_EXIT]]:
; X390-NEXT:    ret float 0.000000e+00
;
entry:                            ; preds = %for.end204
  br label %for.body

for.body:
  %indvars.iv179.ldist1 = phi i64 [ %indvars.iv.next180.ldist1, %for.body ], [ 1, %entry ]
  %63 = add nsw i64 %indvars.iv179.ldist1, -1
  %arrayidx75.ldist1 = getelementptr inbounds i32, ptr %dsq, i64 %63
  %64 = load i32, ptr %arrayidx75.ldist1, align 4
  %arrayidx78.ldist1 = getelementptr inbounds i32, ptr %hmm, i64 %63
  %65 = load i32, ptr %arrayidx78.ldist1, align 4
  %add.ldist1 = add nsw i32 %65, %64
  %arrayidx80.ldist1 = getelementptr inbounds i32, ptr %0, i64 %indvars.iv179.ldist1
  store i32 %add.ldist1, ptr %arrayidx80.ldist1, align 4
  %arrayidx83.ldist1 = getelementptr inbounds i32, ptr %1, i64 %63
  %66 = load i32, ptr %arrayidx83.ldist1, align 4
  %arrayidx86.ldist1 = getelementptr inbounds i32, ptr %2, i64 %63
  %67 = load i32, ptr %arrayidx86.ldist1, align 4
  %add87.ldist1 = add nsw i32 %67, %66
  %spec.store.select.ldist1 = call i32 @llvm.smax.i32(i32 %add87.ldist1, i32 %add.ldist1)
  store i32 %spec.store.select.ldist1, ptr %arrayidx80.ldist1, align 4
  %arrayidx96.ldist1 = getelementptr inbounds i32, ptr %3, i64 %63
  %68 = load i32, ptr %arrayidx96.ldist1, align 4
  %arrayidx99.ldist1 = getelementptr inbounds i32, ptr %4, i64 %63
  %69 = load i32, ptr %arrayidx99.ldist1, align 4
  %add100.ldist1 = add nsw i32 %69, %68
  %spec.store.select157.ldist1 = call i32 @llvm.smax.i32(i32 %add100.ldist1, i32 %spec.store.select.ldist1)
  store i32 %spec.store.select157.ldist1, ptr %arrayidx80.ldist1, align 4
  %arrayidx110.ldist1 = getelementptr inbounds i32, ptr %5, i64 %indvars.iv179.ldist1
  %70 = load i32, ptr %arrayidx110.ldist1, align 4
  %add111.ldist1 = add nsw i32 %70, %int321
  %spec.store.select160.ldist1 = call i32 @llvm.smax.i32(i32 %add111.ldist1, i32 %spec.store.select157.ldist1)
  store i32 %spec.store.select160.ldist1, ptr %arrayidx80.ldist1, align 4
  %arrayidx121.ldist1 = getelementptr inbounds i32, ptr %6, i64 %indvars.iv179.ldist1
  %71 = load i32, ptr %arrayidx121.ldist1, align 4
  %add124.ldist1 = add nsw i32 %spec.store.select160.ldist1, %71
  %spec.select.ldist1 = call i32 @llvm.smax.i32(i32 %add124.ldist1, i32 -987654321)
  store i32 %spec.select.ldist1, ptr %arrayidx80.ldist1, align 4
  %indvars.iv.next180.ldist1 = add nuw nsw i64 %indvars.iv179.ldist1, 1
  %exitcond.not.ldist1 = icmp eq i64 %indvars.iv.next180.ldist1, %L
  br i1 %exitcond.not.ldist1, label %for.exit, label %for.body

for.exit:
  ret float 0.0

}
;.
; X280: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; X280: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; X280: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; X280: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; X280: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
; X390: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; X390: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; X390: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; X390: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; X390: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
