; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S --passes=loop-vectorize -mtriple=riscv64-unknown-linux-gnu -mcpu=sifive-x390-fast-fp64 < %s | FileCheck %s

define void @test(i64 %0, i32 %1, i32 %2) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i64 [[TMP0:%.*]], i32 [[TMP1:%.*]], i32 [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP3:%.*]] = udiv i32 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[DIV_I1313_US1933:%.*]] = zext i32 [[TMP3]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[TMP0]], 1
; CHECK-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP13:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP4]], i32 16, i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[DIV_I1313_US1933]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; CHECK-NEXT:    [[TMP9:%.*]] = mul <vscale x 16 x i64> [[TMP8]], splat (i64 1)
; CHECK-NEXT:    [[INDUCTION:%.*]] = add <vscale x 16 x i64> zeroinitializer, [[TMP9]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 16 x i64> [ [[INDUCTION]], %[[VECTOR_PH]] ], [ [[STEP_ADD:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP4]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 16, i1 true)
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP10]] to i64
; CHECK-NEXT:    [[TMP14:%.*]] = mul i64 1, [[TMP6]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP14]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 16 x i64> @llvm.vp.mul.nxv16i64(<vscale x 16 x i64> [[VEC_IND]], <vscale x 16 x i64> [[BROADCAST_SPLAT]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr float, ptr null, <vscale x 16 x i64> [[VP_OP]]
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv16f32.nxv16p0(<vscale x 16 x float> zeroinitializer, <vscale x 16 x ptr> align 4 [[TMP11]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; CHECK-NEXT:    [[TMP12:%.*]] = zext i32 [[TMP10]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP12]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[STEP_ADD]] = call <vscale x 16 x i64> @llvm.vp.add.nxv16i64(<vscale x 16 x i64> [[VEC_IND]], <vscale x 16 x i64> [[DOTSPLAT]], <vscale x 16 x i1> splat (i1 true), i32 [[TMP10]])
; CHECK-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP16]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[OC_01860_US1911:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INC419_US1918:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[MUL413_US1916:%.*]] = mul i64 [[OC_01860_US1911]], [[DIV_I1313_US1933]]
; CHECK-NEXT:    [[GEP_US1917:%.*]] = getelementptr float, ptr null, i64 [[MUL413_US1916]]
; CHECK-NEXT:    store float 0.000000e+00, ptr [[GEP_US1917]], align 4
; CHECK-NEXT:    [[INC419_US1918]] = add i64 [[OC_01860_US1911]], 1
; CHECK-NEXT:    [[EXITCOND1973_NOT:%.*]] = icmp eq i64 [[OC_01860_US1911]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND1973_NOT]], label %[[EXIT]], label %[[LOOP]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %3 = udiv i32 %1, %2
  %div.i1313.us1933 = zext i32 %3 to i64
  br label %loop

loop:
  %oc.01860.us1911 = phi i64 [ 0, %entry ], [ %inc419.us1918, %loop ]
  %mul413.us1916 = mul i64 %oc.01860.us1911, %div.i1313.us1933
  %gep.us1917 = getelementptr float, ptr null, i64 %mul413.us1916
  store float 0.000000e+00, ptr %gep.us1917, align 4
  %inc419.us1918 = add i64 %oc.01860.us1911, 1
  %exitcond1973.not = icmp eq i64 %oc.01860.us1911, %0
  br i1 %exitcond1973.not, label %exit, label %loop

exit:
  ret void
}

;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
