; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -S -mtriple riscv64-unknown-linux-gnu -riscv-use-vla-vectorizer -riscv-v-vector-bits-min=128 -mattr="+64bit,+a,+c,+d,+f,+m,+v,+zicsr,+zifencei,+zvl128b,+zvl32b,+zvl64b" %s 2>&1 | FileCheck %s

define void @test(ptr %a, ptr%b, ptr %c, ptr %d, i64 %len) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP_NOT23:%.*]] = icmp eq i64 [[LEN:%.*]], 2147483647
; CHECK-NEXT:    br i1 [[CMP_NOT23]], label [[FOR_END:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[LEN]], [[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = sub nsw i64 [[INDVARS_IV]], [[LEN]]
; CHECK-NEXT:    [[CMP1:%.*]] = icmp ugt i64 [[TMP0]], 32
; CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       if.else:
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds i32, ptr [[D:%.*]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 2147483647
; CHECK-NEXT:    br i1 [[TMP2]], label [[FOR_END_LOOPEXIT:%.*]], label [[FOR_BODY]]
; CHECK:       for.end.loopexit:
; CHECK-NEXT:    br label [[FOR_END]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  %cmp.not23 = icmp eq i64 %len, 2147483647
  br i1 %cmp.not23, label %for.end, label %for.body.preheader

for.body.preheader:
  br label %for.body

for.body:
  %indvars.iv = phi i64 [ %len, %for.body.preheader ], [ %indvars.iv.next, %for.inc ]
  %0 = sub nsw i64 %indvars.iv, %len
  %cmp1 = icmp ugt i64 %0, 32
  br i1 %cmp1, label %if.then, label %if.else

if.then:
  br label %for.inc

if.else:
  %arrayidx8 = getelementptr inbounds i32, ptr %d, i64 %0
  %1 = load i32, ptr %arrayidx8, align 4
  br label %for.inc

for.inc:
  %indvars.iv.next = add nsw i64 %indvars.iv, 1
  %2 = icmp eq i64 %indvars.iv.next, 2147483647
  br i1 %2, label %for.end.loopexit, label %for.body

for.end.loopexit:
  br label %for.end

for.end:
  ret void
}
