; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -passes=loop-vectorize -riscv-use-vla-vectorizer=false -enable-vplan-native-path < %s | FileCheck %s --check-prefix=CHECK
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -passes=loop-vectorize -riscv-use-vla-vectorizer=true -enable-vplan-native-path < %s | FileCheck %s --check-prefix=CHECK-VLA

define i32 @sct3313() {
; CHECK-LABEL: define i32 @sct3313(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 4
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 23, [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP2]], 4
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 23, [[TMP3]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 23, [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP9:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP10:%.*]] = mul nuw i64 [[TMP9]], 4
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[FOR_OUTER_CLEANUP2:%.*]] ]
; CHECK-NEXT:    br label [[FOR_PREHEADER1:%.*]]
; CHECK:       for.preheader1:
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i64> [ zeroinitializer, [[VECTOR_BODY]] ], [ [[TMP17:%.*]], [[FOR_PREHEADER1]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i32, ptr null, <vscale x 4 x i64> [[VEC_PHI]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 1
; CHECK-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 1), <vscale x 4 x ptr> [[TMP13]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 2
; CHECK-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 2), <vscale x 4 x ptr> [[TMP14]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 3
; CHECK-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 3), <vscale x 4 x ptr> [[TMP15]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 4
; CHECK-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 4), <vscale x 4 x ptr> [[TMP16]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-NEXT:    [[TMP17]] = add nuw nsw <vscale x 4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq <vscale x 4 x i64> [[TMP17]], splat (i64 5)
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <vscale x 4 x i1> [[TMP18]], i32 0
; CHECK-NEXT:    br i1 [[TMP19]], label [[FOR_OUTER_CLEANUP2]], label [[FOR_PREHEADER1]]
; CHECK:       vector.latch:
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP10]]
; CHECK-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP22]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 23, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label [[EXIT:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[FOR_OUTER_PREHEADER:%.*]]
; CHECK:       for.outer.preheader:
; CHECK-NEXT:    [[I_03_I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INC14_I:%.*]], [[FOR_OUTER_CLEANUP:%.*]] ]
; CHECK-NEXT:    br label [[FOR_PREHEADER:%.*]]
; CHECK:       for.preheader:
; CHECK-NEXT:    [[L_02_I:%.*]] = phi i64 [ 0, [[FOR_OUTER_PREHEADER]] ], [ [[INC11_I:%.*]], [[FOR_PREHEADER]] ]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr i32, ptr null, i64 [[L_02_I]]
; CHECK-NEXT:    [[ARRAYIDX_1_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 1
; CHECK-NEXT:    store i32 1, ptr [[ARRAYIDX_1_I]], align 4
; CHECK-NEXT:    [[ARRAYIDX_2_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 2
; CHECK-NEXT:    store i32 2, ptr [[ARRAYIDX_2_I]], align 4
; CHECK-NEXT:    [[ARRAYIDX_3_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 3
; CHECK-NEXT:    store i32 3, ptr [[ARRAYIDX_3_I]], align 4
; CHECK-NEXT:    [[ARRAYIDX_4_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 4
; CHECK-NEXT:    store i32 4, ptr [[ARRAYIDX_4_I]], align 4
; CHECK-NEXT:    [[INC11_I]] = add nuw nsw i64 [[L_02_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i64 [[INC11_I]], 5
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label [[FOR_OUTER_CLEANUP]], label [[FOR_PREHEADER]]
; CHECK:       for.outer.cleanup:
; CHECK-NEXT:    [[INC14_I]] = add nuw nsw i64 [[I_03_I]], 1
; CHECK-NEXT:    [[EXITCOND4_NOT_I:%.*]] = icmp eq i64 [[INC14_I]], 23
; CHECK-NEXT:    br i1 [[EXITCOND4_NOT_I]], label [[EXIT]], label [[FOR_OUTER_PREHEADER]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret i32 0
;
; CHECK-VLA-LABEL: define i32 @sct3313(
; CHECK-VLA-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-VLA-NEXT:  entry:
; CHECK-VLA-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-VLA-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 4
; CHECK-VLA-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 23, [[TMP1]]
; CHECK-VLA-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-VLA:       vector.ph:
; CHECK-VLA-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-VLA-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP2]], 4
; CHECK-VLA-NEXT:    [[N_MOD_VF:%.*]] = urem i64 23, [[TMP3]]
; CHECK-VLA-NEXT:    [[N_VEC:%.*]] = sub i64 23, [[N_MOD_VF]]
; CHECK-VLA-NEXT:    [[TMP9:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-VLA-NEXT:    [[TMP10:%.*]] = mul nuw i64 [[TMP9]], 4
; CHECK-VLA-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-VLA:       vector.body:
; CHECK-VLA-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[FOR_OUTER_CLEANUP2:%.*]] ]
; CHECK-VLA-NEXT:    br label [[FOR_PREHEADER1:%.*]]
; CHECK-VLA:       for.preheader1:
; CHECK-VLA-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i64> [ zeroinitializer, [[VECTOR_BODY]] ], [ [[TMP17:%.*]], [[FOR_PREHEADER1]] ]
; CHECK-VLA-NEXT:    [[TMP12:%.*]] = getelementptr i32, ptr null, <vscale x 4 x i64> [[VEC_PHI]]
; CHECK-VLA-NEXT:    [[TMP13:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 1
; CHECK-VLA-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 1), <vscale x 4 x ptr> [[TMP13]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-VLA-NEXT:    [[TMP14:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 2
; CHECK-VLA-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 2), <vscale x 4 x ptr> [[TMP14]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-VLA-NEXT:    [[TMP15:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 3
; CHECK-VLA-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 3), <vscale x 4 x ptr> [[TMP15]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-VLA-NEXT:    [[TMP16:%.*]] = getelementptr i32, <vscale x 4 x ptr> [[TMP12]], i64 4
; CHECK-VLA-NEXT:    call void @llvm.masked.scatter.nxv4i32.nxv4p0(<vscale x 4 x i32> splat (i32 4), <vscale x 4 x ptr> [[TMP16]], i32 4, <vscale x 4 x i1> splat (i1 true))
; CHECK-VLA-NEXT:    [[TMP17]] = add nuw nsw <vscale x 4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-VLA-NEXT:    [[TMP18:%.*]] = icmp eq <vscale x 4 x i64> [[TMP17]], splat (i64 5)
; CHECK-VLA-NEXT:    [[TMP19:%.*]] = extractelement <vscale x 4 x i1> [[TMP18]], i32 0
; CHECK-VLA-NEXT:    br i1 [[TMP19]], label [[FOR_OUTER_CLEANUP2]], label [[FOR_PREHEADER1]]
; CHECK-VLA:       vector.latch:
; CHECK-VLA-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP10]]
; CHECK-VLA-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-VLA-NEXT:    br i1 [[TMP22]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-VLA:       middle.block:
; CHECK-VLA-NEXT:    [[CMP_N:%.*]] = icmp eq i64 23, [[N_VEC]]
; CHECK-VLA-NEXT:    br i1 [[CMP_N]], label [[EXIT:%.*]], label [[SCALAR_PH]]
; CHECK-VLA:       scalar.ph:
; CHECK-VLA-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-VLA-NEXT:    br label [[FOR_OUTER_PREHEADER:%.*]]
; CHECK-VLA:       for.outer.preheader:
; CHECK-VLA-NEXT:    [[I_03_I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INC14_I:%.*]], [[FOR_OUTER_CLEANUP:%.*]] ]
; CHECK-VLA-NEXT:    br label [[FOR_PREHEADER:%.*]]
; CHECK-VLA:       for.preheader:
; CHECK-VLA-NEXT:    [[L_02_I:%.*]] = phi i64 [ 0, [[FOR_OUTER_PREHEADER]] ], [ [[INC11_I:%.*]], [[FOR_PREHEADER]] ]
; CHECK-VLA-NEXT:    [[TMP23:%.*]] = getelementptr i32, ptr null, i64 [[L_02_I]]
; CHECK-VLA-NEXT:    [[ARRAYIDX_1_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 1
; CHECK-VLA-NEXT:    store i32 1, ptr [[ARRAYIDX_1_I]], align 4
; CHECK-VLA-NEXT:    [[ARRAYIDX_2_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 2
; CHECK-VLA-NEXT:    store i32 2, ptr [[ARRAYIDX_2_I]], align 4
; CHECK-VLA-NEXT:    [[ARRAYIDX_3_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 3
; CHECK-VLA-NEXT:    store i32 3, ptr [[ARRAYIDX_3_I]], align 4
; CHECK-VLA-NEXT:    [[ARRAYIDX_4_I:%.*]] = getelementptr i32, ptr [[TMP23]], i64 4
; CHECK-VLA-NEXT:    store i32 4, ptr [[ARRAYIDX_4_I]], align 4
; CHECK-VLA-NEXT:    [[INC11_I]] = add nuw nsw i64 [[L_02_I]], 1
; CHECK-VLA-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i64 [[INC11_I]], 5
; CHECK-VLA-NEXT:    br i1 [[EXITCOND_NOT_I]], label [[FOR_OUTER_CLEANUP]], label [[FOR_PREHEADER]]
; CHECK-VLA:       for.outer.cleanup:
; CHECK-VLA-NEXT:    [[INC14_I]] = add nuw nsw i64 [[I_03_I]], 1
; CHECK-VLA-NEXT:    [[EXITCOND4_NOT_I:%.*]] = icmp eq i64 [[INC14_I]], 23
; CHECK-VLA-NEXT:    br i1 [[EXITCOND4_NOT_I]], label [[EXIT]], label [[FOR_OUTER_PREHEADER]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK-VLA:       exit:
; CHECK-VLA-NEXT:    ret i32 0
;
entry:
  br label %for.outer.preheader

for.outer.preheader:
  %i.03.i = phi i64 [ 0, %entry ], [ %inc14.i, %for.outer.cleanup ]
  br label %for.preheader

for.preheader:
  %l.02.i = phi i64 [ 0, %for.outer.preheader ], [ %inc11.i, %for.preheader ]
  %0 = getelementptr i32, ptr null, i64 %l.02.i
  %arrayidx.1.i = getelementptr i32, ptr %0, i64 1
  store i32 1, ptr %arrayidx.1.i, align 4
  %arrayidx.2.i = getelementptr i32, ptr %0, i64 2
  store i32 2, ptr %arrayidx.2.i, align 4
  %arrayidx.3.i = getelementptr i32, ptr %0, i64 3
  store i32 3, ptr %arrayidx.3.i, align 4
  %arrayidx.4.i = getelementptr i32, ptr %0, i64 4
  store i32 4, ptr %arrayidx.4.i, align 4
  %inc11.i = add nuw nsw i64 %l.02.i, 1
  %exitcond.not.i = icmp eq i64 %inc11.i, 5
  br i1 %exitcond.not.i, label %for.outer.cleanup, label %for.preheader

for.outer.cleanup:
  %inc14.i = add nuw nsw i64 %i.03.i, 1
  %exitcond4.not.i = icmp eq i64 %inc14.i, 23
  br i1 %exitcond4.not.i, label %exit, label %for.outer.preheader, !llvm.loop !0

exit:
  ret i32 0
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.vectorize.enable", i1 true}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]]}
;.
; CHECK-VLA: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK-VLA: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK-VLA: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK-VLA: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]]}
;.
