; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -passes=loop-vectorize -sifive-loop-vectorizer-enable-interleaved-access=const-stride < %s | FileCheck %s

%"class.clang::BaseSubobject" = type { ptr, %"class.clang::CharUnits" }
%"class.clang::CharUnits" = type { i64 }
%"class.llvm::detail::DenseSetPair.1052" = type { %"class.clang::BaseSubobject" }

define void @_ZN5clang22MicrosoftVTableContext31computeVTableRelatedInformationEPKNS_13CXXRecordDeclE(ptr writeonly %0){
; CHECK-LABEL: define void @_ZN5clang22MicrosoftVTableContext31computeVTableRelatedInformationEPKNS_13CXXRecordDeclE
; CHECK-SAME: (ptr writeonly [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = lshr i64 [[TMP1]], 4
; CHECK-NEXT:    [[TMP3:%.*]] = add nuw nsw i64 [[TMP2]], 1
; CHECK-NEXT:    br label [[VECTOR_MEMCHECK:%.*]]
; CHECK:       vector.memcheck:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[TMP0]], i64 8
; CHECK-NEXT:    [[TMP4:%.*]] = lshr i64 [[TMP1]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = shl nuw i64 [[TMP4]], 4
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], 16
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr null, i64 [[TMP6]]
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[TMP0]], [[SCEVGEP1]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr inttoptr (i64 8 to ptr), [[SCEVGEP]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP3]], i32 1, i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 1 x ptr> poison, ptr [[TMP0]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 1 x ptr> [[BROADCAST_SPLATINSERT]], <vscale x 1 x ptr> poison, <vscale x 1 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP3]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 1, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV]], 16
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr null, i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP9:%.*]] = mul nuw nsw i32 [[TMP8]], 2
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr align 8 [[NEXT_GEP]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[DEINTERLEAVED_RESULTS:%.*]] = call { <vscale x 1 x ptr>, <vscale x 1 x ptr> } @llvm.vector.deinterleave2.nxv2p0(<vscale x 2 x ptr> [[WIDE_MASKED_LOAD]])
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 1 x ptr>, <vscale x 1 x ptr> } [[DEINTERLEAVED_RESULTS]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <vscale x 1 x ptr>, <vscale x 1 x ptr> } [[DEINTERLEAVED_RESULTS]], 1
; CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint <vscale x 1 x ptr> [[TMP11]] to <vscale x 1 x i64>
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 1 x i1> @llvm.vp.icmp.nxv1p0(<vscale x 1 x ptr> [[TMP10]], <vscale x 1 x ptr> zeroinitializer, metadata !"eq", <vscale x 1 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[VP_OP_ICMP2:%.*]] = call <vscale x 1 x i1> @llvm.vp.icmp.nxv1i64(<vscale x 1 x i64> [[TMP12]], <vscale x 1 x i64> zeroinitializer, metadata !"eq", <vscale x 1 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[VP_WIDEN_SELECT:%.*]] = call <vscale x 1 x i1> @llvm.vp.select.nxv1i1(<vscale x 1 x i1> [[VP_OP_ICMP]], <vscale x 1 x i1> [[VP_OP_ICMP2]], <vscale x 1 x i1> zeroinitializer, i32 [[TMP8]])
; CHECK-NEXT:    [[PRED_NOT:%.*]] = call <vscale x 1 x i1> @llvm.vp.xor.nxv1i1(<vscale x 1 x i1> [[VP_WIDEN_SELECT]], <vscale x 1 x i1> splat (i1 true), <vscale x 1 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv1p0.nxv1p0(<vscale x 1 x ptr> zeroinitializer, <vscale x 1 x ptr> align 8 [[BROADCAST_SPLAT]], <vscale x 1 x i1> [[PRED_NOT]], i32 [[TMP8]]), !alias.scope [[META0:![0-9]+]], !noalias [[META3:![0-9]+]]
; CHECK-NEXT:    [[TMP13:%.*]] = zext i32 [[TMP8]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP13]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP3]]
; CHECK-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP_I_I_I_I_LOOPEXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ null, [[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    br label [[FOR_BODY_I_I_I_I:%.*]]
; CHECK:       for.cond.cleanup.i.i.i.i.loopexit:
; CHECK-NEXT:    ret void
; CHECK:       for.body.i.i.i.i:
; CHECK-NEXT:    [[P_048_I_I_I_I1:%.*]] = phi ptr [ [[INCDEC_PTR_I_I_I_I:%.*]], [[FOR_INC_I_I_I_I:%.*]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[P_048_I_I_I_I1]], align 8
; CHECK-NEXT:    [[CMP_I_I41_I_I_I_I:%.*]] = icmp eq ptr [[TMP15]], null
; CHECK-NEXT:    [[BASEOFFSET_I_I_I_I_I_I:%.*]] = getelementptr %"class.clang::BaseSubobject", ptr [[P_048_I_I_I_I1]], i64 0, i32 1
; CHECK-NEXT:    [[TMP16:%.*]] = load i64, ptr [[BASEOFFSET_I_I_I_I_I_I]], align 8
; CHECK-NEXT:    [[CMP_I_I_I_I_I_I_I:%.*]] = icmp eq i64 [[TMP16]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = select i1 [[CMP_I_I41_I_I_I_I]], i1 [[CMP_I_I_I_I_I_I_I]], i1 false
; CHECK-NEXT:    br i1 [[TMP17]], label [[FOR_INC_I_I_I_I]], label [[IF_THEN20_I_I_I_I:%.*]]
; CHECK:       if.then20.i.i.i.i:
; CHECK-NEXT:    store ptr null, ptr [[TMP0]], align 8
; CHECK-NEXT:    br label [[FOR_INC_I_I_I_I]]
; CHECK:       for.inc.i.i.i.i:
; CHECK-NEXT:    [[INCDEC_PTR_I_I_I_I]] = getelementptr inbounds %"class.llvm::detail::DenseSetPair.1052", ptr [[P_048_I_I_I_I1]], i64 1
; CHECK-NEXT:    [[CMP17_NOT_I_I_I_I:%.*]] = icmp eq ptr [[P_048_I_I_I_I1]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP17_NOT_I_I_I_I]], label [[FOR_COND_CLEANUP_I_I_I_I_LOOPEXIT]], label [[FOR_BODY_I_I_I_I]], !llvm.loop [[LOOP9:![0-9]+]]
;

entry:
  br label %for.body.i.i.i.i

for.cond.cleanup.i.i.i.i.loopexit:                ; preds = %for.inc.i.i.i.i
  ret void

for.body.i.i.i.i:                                 ; preds = %for.inc.i.i.i.i, %entry
  %P.048.i.i.i.i1 = phi ptr [ %incdec.ptr.i.i.i.i, %for.inc.i.i.i.i ], [ null, %entry ]
  %1 = load ptr, ptr %P.048.i.i.i.i1, align 8
  %cmp.i.i41.i.i.i.i = icmp eq ptr %1, null
  %BaseOffset.i.i.i.i.i.i = getelementptr %"class.clang::BaseSubobject", ptr %P.048.i.i.i.i1, i64 0, i32 1
  %2 = load i64, ptr %BaseOffset.i.i.i.i.i.i, align 8
  %cmp.i.i.i.i.i.i.i = icmp eq i64 %2, 0
  %3 = select i1 %cmp.i.i41.i.i.i.i, i1 %cmp.i.i.i.i.i.i.i, i1 false
  br i1 %3, label %for.inc.i.i.i.i, label %if.then20.i.i.i.i

if.then20.i.i.i.i:                                ; preds = %for.body.i.i.i.i
  store ptr null, ptr %0, align 8
  br label %for.inc.i.i.i.i

for.inc.i.i.i.i:                                  ; preds = %if.then20.i.i.i.i, %for.body.i.i.i.i
  %incdec.ptr.i.i.i.i = getelementptr inbounds %"class.llvm::detail::DenseSetPair.1052", ptr %P.048.i.i.i.i1, i64 1
  %cmp17.not.i.i.i.i = icmp eq ptr %P.048.i.i.i.i1, %0
  br i1 %cmp17.not.i.i.i.i, label %for.cond.cleanup.i.i.i.i.loopexit, label %for.body.i.i.i.i
}
