; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-x280 -S %s 2>&1 | FileCheck --check-prefix X280 %s
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p470 -S %s 2>&1 | FileCheck --check-prefix P470 %s
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p670 -S %s 2>&1 | FileCheck --check-prefix P670 %s

define void @test(i32 %control1, i32 %control2, i32 %target, i32 %reg.4.val, ptr %reg.24.val) {
; X280-LABEL: define void @test(
; X280-SAME: i32 [[CONTROL1:%.*]], i32 [[CONTROL2:%.*]], i32 [[TARGET:%.*]], i32 [[REG_4_VAL:%.*]], ptr [[REG_24_VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; X280-NEXT:  [[ENTRY:.*:]]
; X280-NEXT:    [[CMP1:%.*]] = icmp sgt i32 [[REG_4_VAL]], 0
; X280-NEXT:    br i1 [[CMP1]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END:.*]]
; X280:       [[FOR_BODY_LR_PH]]:
; X280-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONTROL1]] to i64
; X280-NEXT:    [[SHL:%.*]] = shl nuw i64 1, [[SH_PROM]]
; X280-NEXT:    [[SH_PROM5:%.*]] = zext nneg i32 [[CONTROL2]] to i64
; X280-NEXT:    [[SHL6:%.*]] = shl nuw i64 1, [[SH_PROM5]]
; X280-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[TARGET]] to i64
; X280-NEXT:    [[SHL11:%.*]] = shl nuw nsw i64 1, [[SH_PROM10]]
; X280-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[REG_4_VAL]] to i64
; X280-NEXT:    [[TMP0:%.*]] = freeze i64 [[SHL6]]
; X280-NEXT:    [[TMP1:%.*]] = or i64 [[SHL]], [[TMP0]]
; X280-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; X280:       [[VECTOR_PH]]:
; X280-NEXT:    [[TMP4:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[WIDE_TRIP_COUNT]], i32 8, i1 true)
; X280-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i64> poison, i64 [[SHL11]], i64 0
; X280-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer
; X280-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 8 x i64> poison, i64 [[TMP1]], i64 0
; X280-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 8 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer
; X280-NEXT:    br label %[[VECTOR_BODY:.*]]
; X280:       [[VECTOR_BODY]]:
; X280-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; X280-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; X280-NEXT:    [[TMP2:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[EVL_BASED_IV]]
; X280-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP2]], i32 8, i1 true)
; X280-NEXT:    [[TMP5:%.*]] = getelementptr i64, ptr [[REG_24_VAL]], i64 [[EVL_BASED_IV]]
; X280-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP5]], i32 0
; X280-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 8 x i64> @llvm.vp.load.nxv8i64.p0(ptr align 8 [[TMP6]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP3]])
; X280-NEXT:    [[VP_OP:%.*]] = call <vscale x 8 x i64> @llvm.vp.and.nxv8i64(<vscale x 8 x i64> [[VP_OP_LOAD]], <vscale x 8 x i64> [[BROADCAST_SPLAT2]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP3]])
; X280-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i64(<vscale x 8 x i64> [[VP_OP]], <vscale x 8 x i64> [[BROADCAST_SPLAT2]], metadata !"eq", <vscale x 8 x i1> splat (i1 true), i32 [[TMP3]])
; X280-NEXT:    [[VP_OP3:%.*]] = call <vscale x 8 x i64> @llvm.vp.xor.nxv8i64(<vscale x 8 x i64> [[VP_OP_LOAD]], <vscale x 8 x i64> [[BROADCAST_SPLAT]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP3]])
; X280-NEXT:    [[TMP7:%.*]] = getelementptr i64, ptr [[TMP5]], i32 0
; X280-NEXT:    call void @llvm.vp.store.nxv8i64.p0(<vscale x 8 x i64> [[VP_OP3]], ptr align 8 [[TMP7]], <vscale x 8 x i1> [[VP_OP_ICMP]], i32 [[TMP3]])
; X280-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP3]] to i64
; X280-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; X280-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[WIDE_TRIP_COUNT]]
; X280-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; X280:       [[MIDDLE_BLOCK]]:
; X280-NEXT:    br label %[[FOR_END_LOOPEXIT:.*]]
; X280:       [[SCALAR_PH]]:
; X280-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[FOR_BODY_LR_PH]] ]
; X280-NEXT:    br label %[[FOR_BODY:.*]]
; X280:       [[FOR_BODY]]:
; X280-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ]
; X280-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[REG_24_VAL]], i64 [[INDVARS_IV]]
; X280-NEXT:    [[TMP11:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
; X280-NEXT:    [[TMP12:%.*]] = and i64 [[TMP11]], [[TMP1]]
; X280-NEXT:    [[OR_COND_NOT:%.*]] = icmp eq i64 [[TMP12]], [[TMP1]]
; X280-NEXT:    br i1 [[OR_COND_NOT]], label %[[IF_THEN9:.*]], label %[[FOR_INC]]
; X280:       [[IF_THEN9]]:
; X280-NEXT:    [[XOR:%.*]] = xor i64 [[TMP11]], [[SHL11]]
; X280-NEXT:    store i64 [[XOR]], ptr [[ARRAYIDX]], align 8
; X280-NEXT:    br label %[[FOR_INC]]
; X280:       [[FOR_INC]]:
; X280-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; X280-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; X280-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; X280:       [[FOR_END_LOOPEXIT]]:
; X280-NEXT:    br label %[[FOR_END]]
; X280:       [[FOR_END]]:
; X280-NEXT:    ret void
;
; P470-LABEL: define void @test(
; P470-SAME: i32 [[CONTROL1:%.*]], i32 [[CONTROL2:%.*]], i32 [[TARGET:%.*]], i32 [[REG_4_VAL:%.*]], ptr [[REG_24_VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; P470-NEXT:  [[ENTRY:.*:]]
; P470-NEXT:    [[CMP1:%.*]] = icmp sgt i32 [[REG_4_VAL]], 0
; P470-NEXT:    br i1 [[CMP1]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END:.*]]
; P470:       [[FOR_BODY_LR_PH]]:
; P470-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONTROL1]] to i64
; P470-NEXT:    [[SHL:%.*]] = shl nuw i64 1, [[SH_PROM]]
; P470-NEXT:    [[SH_PROM5:%.*]] = zext nneg i32 [[CONTROL2]] to i64
; P470-NEXT:    [[SHL6:%.*]] = shl nuw i64 1, [[SH_PROM5]]
; P470-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[TARGET]] to i64
; P470-NEXT:    [[SHL11:%.*]] = shl nuw nsw i64 1, [[SH_PROM10]]
; P470-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[REG_4_VAL]] to i64
; P470-NEXT:    [[TMP0:%.*]] = freeze i64 [[SHL6]]
; P470-NEXT:    [[TMP1:%.*]] = or i64 [[SHL]], [[TMP0]]
; P470-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; P470:       [[VECTOR_PH]]:
; P470-NEXT:    [[TMP4:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[WIDE_TRIP_COUNT]], i32 4, i1 true)
; P470-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[SHL11]], i64 0
; P470-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; P470-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; P470-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; P470-NEXT:    br label %[[VECTOR_BODY:.*]]
; P470:       [[VECTOR_BODY]]:
; P470-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY_SPLIT:.*]] ]
; P470-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY_SPLIT]] ]
; P470-NEXT:    [[TMP2:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP2]], i32 4, i1 true)
; P470-NEXT:    [[TMP5:%.*]] = getelementptr i64, ptr [[REG_24_VAL]], i64 [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP5]], i32 0
; P470-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[TMP6]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P470-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i64> @llvm.vp.and.nxv4i64(<vscale x 4 x i64> [[VP_OP_LOAD]], <vscale x 4 x i64> [[BROADCAST_SPLAT2]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P470-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> [[VP_OP]], <vscale x 4 x i64> [[BROADCAST_SPLAT2]], metadata !"eq", <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P470-NEXT:    [[TMP8:%.*]] = call i32 @llvm.vp.first.nxv4i1(<vscale x 4 x i1> [[VP_OP_ICMP]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P470-NEXT:    [[TMP7:%.*]] = icmp ne i32 [[TMP8]], -1
; P470-NEXT:    br i1 [[TMP7]], label %[[VECTOR_IF_BB:.*]], label %[[VECTOR_BODY_SPLIT]]
; P470:       [[VECTOR_IF_BB]]:
; P470-NEXT:    [[VP_OP3:%.*]] = call <vscale x 4 x i64> @llvm.vp.xor.nxv4i64(<vscale x 4 x i64> [[VP_OP_LOAD]], <vscale x 4 x i64> [[BROADCAST_SPLAT]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P470-NEXT:    [[TMP9:%.*]] = getelementptr i64, ptr [[TMP5]], i32 0
; P470-NEXT:    call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[VP_OP3]], ptr align 8 [[TMP9]], <vscale x 4 x i1> [[VP_OP_ICMP]], i32 [[TMP3]])
; P470-NEXT:    br label %[[VECTOR_BODY_SPLIT]]
; P470:       [[VECTOR_BODY_SPLIT]]:
; P470-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP3]] to i64
; P470-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP11]], [[EVL_BASED_IV]]
; P470-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[WIDE_TRIP_COUNT]]
; P470-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; P470:       [[MIDDLE_BLOCK]]:
; P470-NEXT:    br label %[[FOR_END_LOOPEXIT:.*]]
; P470:       [[SCALAR_PH]]:
; P470-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[FOR_BODY_LR_PH]] ]
; P470-NEXT:    br label %[[FOR_BODY:.*]]
; P470:       [[FOR_BODY]]:
; P470-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ]
; P470-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[REG_24_VAL]], i64 [[INDVARS_IV]]
; P470-NEXT:    [[TMP13:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
; P470-NEXT:    [[TMP14:%.*]] = and i64 [[TMP13]], [[TMP1]]
; P470-NEXT:    [[OR_COND_NOT:%.*]] = icmp eq i64 [[TMP14]], [[TMP1]]
; P470-NEXT:    br i1 [[OR_COND_NOT]], label %[[IF_THEN9:.*]], label %[[FOR_INC]]
; P470:       [[IF_THEN9]]:
; P470-NEXT:    [[XOR:%.*]] = xor i64 [[TMP13]], [[SHL11]]
; P470-NEXT:    store i64 [[XOR]], ptr [[ARRAYIDX]], align 8
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[FOR_INC]]:
; P470-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; P470-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; P470-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; P470:       [[FOR_END_LOOPEXIT]]:
; P470-NEXT:    br label %[[FOR_END]]
; P470:       [[FOR_END]]:
; P470-NEXT:    ret void
;
; P670-LABEL: define void @test(
; P670-SAME: i32 [[CONTROL1:%.*]], i32 [[CONTROL2:%.*]], i32 [[TARGET:%.*]], i32 [[REG_4_VAL:%.*]], ptr [[REG_24_VAL:%.*]]) #[[ATTR0:[0-9]+]] {
; P670-NEXT:  [[ENTRY:.*:]]
; P670-NEXT:    [[CMP1:%.*]] = icmp sgt i32 [[REG_4_VAL]], 0
; P670-NEXT:    br i1 [[CMP1]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END:.*]]
; P670:       [[FOR_BODY_LR_PH]]:
; P670-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONTROL1]] to i64
; P670-NEXT:    [[SHL:%.*]] = shl nuw i64 1, [[SH_PROM]]
; P670-NEXT:    [[SH_PROM5:%.*]] = zext nneg i32 [[CONTROL2]] to i64
; P670-NEXT:    [[SHL6:%.*]] = shl nuw i64 1, [[SH_PROM5]]
; P670-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[TARGET]] to i64
; P670-NEXT:    [[SHL11:%.*]] = shl nuw nsw i64 1, [[SH_PROM10]]
; P670-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[REG_4_VAL]] to i64
; P670-NEXT:    [[TMP0:%.*]] = freeze i64 [[SHL6]]
; P670-NEXT:    [[TMP1:%.*]] = or i64 [[SHL]], [[TMP0]]
; P670-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; P670:       [[VECTOR_PH]]:
; P670-NEXT:    [[TMP4:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[WIDE_TRIP_COUNT]], i32 4, i1 true)
; P670-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[SHL11]], i64 0
; P670-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; P670-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[TMP1]], i64 0
; P670-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; P670-NEXT:    br label %[[VECTOR_BODY:.*]]
; P670:       [[VECTOR_BODY]]:
; P670-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; P670-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; P670-NEXT:    [[TMP2:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[EVL_BASED_IV]]
; P670-NEXT:    [[TMP3:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP2]], i32 4, i1 true)
; P670-NEXT:    [[TMP5:%.*]] = getelementptr i64, ptr [[REG_24_VAL]], i64 [[EVL_BASED_IV]]
; P670-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[TMP5]], i32 0
; P670-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[TMP6]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P670-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i64> @llvm.vp.and.nxv4i64(<vscale x 4 x i64> [[VP_OP_LOAD]], <vscale x 4 x i64> [[BROADCAST_SPLAT2]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P670-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> [[VP_OP]], <vscale x 4 x i64> [[BROADCAST_SPLAT2]], metadata !"eq", <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P670-NEXT:    [[VP_OP3:%.*]] = call <vscale x 4 x i64> @llvm.vp.xor.nxv4i64(<vscale x 4 x i64> [[VP_OP_LOAD]], <vscale x 4 x i64> [[BROADCAST_SPLAT]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP3]])
; P670-NEXT:    [[TMP7:%.*]] = getelementptr i64, ptr [[TMP5]], i32 0
; P670-NEXT:    call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[VP_OP3]], ptr align 8 [[TMP7]], <vscale x 4 x i1> [[VP_OP_ICMP]], i32 [[TMP3]])
; P670-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP3]] to i64
; P670-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP9]], [[EVL_BASED_IV]]
; P670-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[WIDE_TRIP_COUNT]]
; P670-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; P670:       [[MIDDLE_BLOCK]]:
; P670-NEXT:    br label %[[FOR_END_LOOPEXIT:.*]]
; P670:       [[SCALAR_PH]]:
; P670-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[FOR_BODY_LR_PH]] ]
; P670-NEXT:    br label %[[FOR_BODY:.*]]
; P670:       [[FOR_BODY]]:
; P670-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ]
; P670-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[REG_24_VAL]], i64 [[INDVARS_IV]]
; P670-NEXT:    [[TMP11:%.*]] = load i64, ptr [[ARRAYIDX]], align 8
; P670-NEXT:    [[TMP12:%.*]] = and i64 [[TMP11]], [[TMP1]]
; P670-NEXT:    [[OR_COND_NOT:%.*]] = icmp eq i64 [[TMP12]], [[TMP1]]
; P670-NEXT:    br i1 [[OR_COND_NOT]], label %[[IF_THEN9:.*]], label %[[FOR_INC]]
; P670:       [[IF_THEN9]]:
; P670-NEXT:    [[XOR:%.*]] = xor i64 [[TMP11]], [[SHL11]]
; P670-NEXT:    store i64 [[XOR]], ptr [[ARRAYIDX]], align 8
; P670-NEXT:    br label %[[FOR_INC]]
; P670:       [[FOR_INC]]:
; P670-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; P670-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; P670-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; P670:       [[FOR_END_LOOPEXIT]]:
; P670-NEXT:    br label %[[FOR_END]]
; P670:       [[FOR_END]]:
; P670-NEXT:    ret void
;
entry:
  %cmp1 = icmp sgt i32 %reg.4.val, 0
  br i1 %cmp1, label %for.body.lr.ph, label %for.end

for.body.lr.ph:
  %sh_prom = zext nneg i32 %control1 to i64
  %shl = shl nuw i64 1, %sh_prom
  %sh_prom5 = zext nneg i32 %control2 to i64
  %shl6 = shl nuw i64 1, %sh_prom5
  %sh_prom10 = zext nneg i32 %target to i64
  %shl11 = shl nuw nsw i64 1, %sh_prom10
  %wide.trip.count = zext nneg i32 %reg.4.val to i64
  %0 = freeze i64 %shl6
  %1 = or i64 %shl, %0
  br label %for.body

for.body:
  %indvars.iv = phi i64 [ 0, %for.body.lr.ph ], [ %indvars.iv.next, %for.inc ]
  %arrayidx = getelementptr inbounds i64, ptr %reg.24.val, i64 %indvars.iv
  %2 = load i64, ptr %arrayidx, align 8
  %3 = and i64 %2, %1
  %or.cond.not = icmp eq i64 %3, %1
  br i1 %or.cond.not, label %if.then9, label %for.inc

if.then9:
  %xor = xor i64 %2, %shl11
  store i64 %xor, ptr %arrayidx, align 8
  br label %for.inc

for.inc:
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.end.loopexit, label %for.body

for.end.loopexit:
  br label %for.end

for.end:
  ret void
}
;.
; X280: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; X280: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; X280: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; X280: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; X280: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
; P470: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; P470: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; P470: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; P470: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; P470: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
; P670: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; P670: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; P670: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; P670: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; P670: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
