; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -loop-vectorize -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=512 -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-prefer-predicated-vector-ops -mattr=+v < %s | FileCheck %s
define void @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  for.body11.i.preheader:
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i64> poison, i64 [[INDEX]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 8 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i64> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.experimental.stepvector.nxv8i64()
; CHECK-NEXT:    [[TMP1:%.*]] = add <vscale x 8 x i64> zeroinitializer, [[TMP0]]
; CHECK-NEXT:    [[VEC_IV:%.*]] = add <vscale x 8 x i64> [[BROADCAST_SPLAT]], [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 0, [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP4:%.*]] = mul i64 [[TMP3]], 8
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP2]], i64 [[TMP4]])
; CHECK-NEXT:    [[TMP5:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 0, i64 0)
; CHECK-NEXT:    [[TMP6:%.*]] = trunc i64 [[TMP5]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], 8
; CHECK-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP6]] to i64
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP9]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], 0
; CHECK-NEXT:    br i1 [[TMP10]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br i1 true, label [[SW_EPILOG_I_LOOPEXIT71:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[MIDDLE_BLOCK]] ], [ 0, [[FOR_BODY11_I_PREHEADER:%.*]] ]
; CHECK-NEXT:    br label [[FOR_BODY11_I:%.*]]
; CHECK:       for.body11.i:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[LOR_END_I:%.*]] ]
; CHECK-NEXT:    br i1 false, label [[LOR_END_I]], label [[LOR_RHS_I:%.*]]
; CHECK:       lor.rhs.i:
; CHECK-NEXT:    br label [[LOR_END_I]]
; CHECK:       lor.end.i:
; CHECK-NEXT:    [[TMP11:%.*]] = phi i1 [ false, [[FOR_BODY11_I]] ], [ false, [[LOR_RHS_I]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[SW_EPILOG_I_LOOPEXIT71]], label [[FOR_BODY11_I]], !llvm.loop [[LOOP2:![0-9]+]]
; CHECK:       sw.epilog.i.loopexit71:
; CHECK-NEXT:    ret void
;
for.body11.i.preheader:
  br label %for.body11.i

for.body11.i:
  %indvars.iv = phi i64 [ 0, %for.body11.i.preheader ], [ %indvars.iv.next, %lor.end.i ]
  br i1 false, label %lor.end.i, label %lor.rhs.i

lor.rhs.i:
  br label %lor.end.i

lor.end.i:
  %0 = phi i1 [ false, %for.body11.i ], [ false, %lor.rhs.i ]
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 0
  br i1 %exitcond.not, label %sw.epilog.i.loopexit71, label %for.body11.i

sw.epilog.i.loopexit71:
  ret void
}
