; NOTE: Assertions have been autogenerated by utils/update_test_checks.py

; RUN: opt -riscv-use-vla-vectorizer -passes=loop-vectorize -S -mtriple=riscv64-unknown-linux-gnu -mattr=+v %s | FileCheck %s --check-prefix=VL0
; RUN: opt -riscv-use-vla-vectorizer -passes=loop-vectorize -S -mtriple=riscv64-unknown-linux-gnu -mattr=+v %s -sifive-loop-vectorizer-clamp-vl=1 | FileCheck %s --check-prefix=VL1
; RUN: opt -riscv-use-vla-vectorizer -passes=loop-vectorize -S -mtriple=riscv64-unknown-linux-gnu -mattr=+v %s -sifive-loop-vectorizer-clamp-vl=4 | FileCheck %s --check-prefix=VL4

define void @test(ptr %A) {
; VL0-LABEL: @test(
; VL0-NEXT:  entry:
; VL0-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; VL0:       vector.ph:
; VL0-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 1000, i32 2, i1 true)
; VL0-NEXT:    br label [[VECTOR_BODY:%.*]]
; VL0:       vector.body:
; VL0-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; VL0-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; VL0-NEXT:    [[AVL:%.*]] = sub i64 1000, [[EVL_BASED_IV1]]
; VL0-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; VL0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[EVL_BASED_IV1]]
; VL0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i32 0
; VL0-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr align 4 [[TMP4]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP1]])
; VL0-NEXT:    [[VP_OP:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> splat (i32 1), <vscale x 2 x i1> splat (i1 true), i32 [[TMP1]])
; VL0-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> [[VP_OP]], ptr align 4 [[TMP4]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP1]])
; VL0-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP1]] to i64
; VL0-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP6]], [[EVL_BASED_IV1]]
; VL0-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 1000
; VL0-NEXT:    br i1 [[TMP5]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VL0:       middle.block:
; VL0-NEXT:    br label [[FOR_COND_CLEANUP:%.*]]
; VL0:       scalar.ph:
; VL0-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; VL0-NEXT:    br label [[FOR_BODY:%.*]]
; VL0:       for.cond.cleanup:
; VL0-NEXT:    ret void
; VL0:       for.body:
; VL0-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; VL0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; VL0-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VL0-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP7]], 1
; VL0-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX]], align 4
; VL0-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VL0-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1000
; VL0-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
;
; VL1-LABEL: @test(
; VL1-NEXT:  entry:
; VL1-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; VL1:       vector.ph:
; VL1-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 1000, i32 2, i1 true)
; VL1-NEXT:    br label [[VECTOR_BODY:%.*]]
; VL1:       vector.body:
; VL1-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; VL1-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; VL1-NEXT:    [[AVL:%.*]] = sub i64 1000, [[EVL_BASED_IV1]]
; VL1-NEXT:    [[TMP1:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 1)
; VL1-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP1]], i32 2, i1 true)
; VL1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[EVL_BASED_IV1]]
; VL1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 0
; VL1-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr align 4 [[TMP5]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; VL1-NEXT:    [[VP_OP:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> splat (i32 1), <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; VL1-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> [[VP_OP]], ptr align 4 [[TMP5]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; VL1-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP2]] to i64
; VL1-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP7]], [[EVL_BASED_IV1]]
; VL1-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 1000
; VL1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VL1:       middle.block:
; VL1-NEXT:    br label [[FOR_COND_CLEANUP:%.*]]
; VL1:       scalar.ph:
; VL1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; VL1-NEXT:    br label [[FOR_BODY:%.*]]
; VL1:       for.cond.cleanup:
; VL1-NEXT:    ret void
; VL1:       for.body:
; VL1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; VL1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; VL1-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VL1-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP8]], 1
; VL1-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX]], align 4
; VL1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VL1-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1000
; VL1-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
;
; VL4-LABEL: @test(
; VL4-NEXT:  entry:
; VL4-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; VL4:       vector.ph:
; VL4-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 1000, i32 2, i1 true)
; VL4-NEXT:    br label [[VECTOR_BODY:%.*]]
; VL4:       vector.body:
; VL4-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; VL4-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; VL4-NEXT:    [[AVL:%.*]] = sub i64 1000, [[EVL_BASED_IV1]]
; VL4-NEXT:    [[TMP1:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 4)
; VL4-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP1]], i32 2, i1 true)
; VL4-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[EVL_BASED_IV1]]
; VL4-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 0
; VL4-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 2 x i32> @llvm.vp.load.nxv2i32.p0(ptr align 4 [[TMP5]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; VL4-NEXT:    [[VP_OP:%.*]] = call <vscale x 2 x i32> @llvm.vp.add.nxv2i32(<vscale x 2 x i32> [[VP_OP_LOAD]], <vscale x 2 x i32> splat (i32 1), <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; VL4-NEXT:    call void @llvm.vp.store.nxv2i32.p0(<vscale x 2 x i32> [[VP_OP]], ptr align 4 [[TMP5]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP2]])
; VL4-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP2]] to i64
; VL4-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP7]], [[EVL_BASED_IV1]]
; VL4-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 1000
; VL4-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VL4:       middle.block:
; VL4-NEXT:    br label [[FOR_COND_CLEANUP:%.*]]
; VL4:       scalar.ph:
; VL4-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; VL4-NEXT:    br label [[FOR_BODY:%.*]]
; VL4:       for.cond.cleanup:
; VL4-NEXT:    ret void
; VL4:       for.body:
; VL4-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; VL4-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; VL4-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; VL4-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP8]], 1
; VL4-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX]], align 4
; VL4-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VL4-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1000
; VL4-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:
  ret void

for.body:
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds i32, ptr %A, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %0, 1
  store i32 %add, ptr %arrayidx, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1000
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
