; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -sifive-loop-vectorizer-enable-interleaved-access=invariant-stride -force-vectorization -passes=loop-vectorize -enable-mem-access-versioning=false < %s | FileCheck %s
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -sifive-loop-vectorizer-enable-interleaved-access=invariant-stride -force-vectorization -passes=loop-vectorize -enable-mem-access-versioning=true < %s | FileCheck %s --check-prefix CHECK-VERSIONING

define void @test(ptr %a, ptr %b, i64 %stride) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[STRIDE]], i64 -1)
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[SMAX]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i64 [[STRIDE]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = shl nuw i64 [[TMP1]], 2
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; CHECK-NEXT:    [[TMP3:%.*]] = sub i32 [[TMP2]], 1
; CHECK-NEXT:    [[VECTOR_RECUR_INIT:%.*]] = insertelement <vscale x 2 x double> poison, double 0.000000e+00, i32 [[TMP3]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 2 x double> [ [[VECTOR_RECUR_INIT]], [[VECTOR_PH]] ], [ [[VP_OP:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[PREV_EVL:%.*]] = phi i32 [ [[TMP2]], [[VECTOR_PH]] ], [ [[TMP9:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP0]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP9]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[EVL_BASED_IV1]], [[STRIDE]]
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[B]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 8
; CHECK-NEXT:    [[WIDE_STRIDED_LOAD:%.*]] = call <vscale x 2 x i64> @llvm.experimental.vp.strided.load.nxv2i64.p0.i64(ptr align 4 [[TMP6]], i64 [[TMP4]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[WIDE_STRIDED_LOAD_CAST:%.*]] = bitcast <vscale x 2 x i64> [[WIDE_STRIDED_LOAD]] to <vscale x 4 x float>
; CHECK-NEXT:    [[DEINTERLEAVED_RESULTS:%.*]] = call { <vscale x 2 x float>, <vscale x 2 x float> } @llvm.vector.deinterleave2.nxv4f32(<vscale x 4 x float> [[WIDE_STRIDED_LOAD_CAST]])
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float> } [[DEINTERLEAVED_RESULTS]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float> } [[DEINTERLEAVED_RESULTS]], 1
; CHECK-NEXT:    [[VP_CAST:%.*]] = call <vscale x 2 x double> @llvm.vp.fpext.nxv2f64.nxv2f32(<vscale x 2 x float> [[TMP7]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[VP_CAST1:%.*]] = call <vscale x 2 x double> @llvm.vp.fpext.nxv2f64.nxv2f32(<vscale x 2 x float> [[TMP8]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[VP_OP]] = call <vscale x 2 x double> @llvm.vp.fmuladd.nxv2f64(<vscale x 2 x double> [[VP_CAST1]], <vscale x 2 x double> zeroinitializer, <vscale x 2 x double> [[VP_CAST]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP9]])
; CHECK-NEXT:    [[TMP12:%.*]] = call <vscale x 2 x double> @llvm.experimental.vp.splice.nxv2f64(<vscale x 2 x double> [[VECTOR_RECUR]], <vscale x 2 x double> [[VP_OP]], i32 -1, <vscale x 2 x i1> splat (i1 true), i32 [[PREV_EVL]], i32 [[TMP9]])
; CHECK-NEXT:    [[TMP10:%.*]] = zext i32 [[TMP9]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP10]], [[EVL_BASED_IV1]]
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP0]]
; CHECK-NEXT:    br i1 [[TMP11]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP19:%.*]] = sub i32 [[TMP9]], 1
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <vscale x 2 x double> [[TMP12]], i32 [[TMP19]]
; CHECK-NEXT:    br label [[LOOPEXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL3:%.*]] = phi ptr [ [[B]], [[ENTRY]] ]
; CHECK-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi double [ 0.000000e+00, [[ENTRY]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       loopexit:
; CHECK-NEXT:    [[S_LCSSA:%.*]] = phi double [ [[SCALAR_RECUR:%.*]], [[FOR_BODY]] ], [ [[TMP22]], [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[CONV238:%.*]] = fptrunc double [[S_LCSSA]] to float
; CHECK-NEXT:    store float [[CONV238]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[FOR_BODY]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[DELTA:%.*]] = phi ptr [ [[DELTA_NEXT:%.*]], [[FOR_BODY]] ], [ [[BC_RESUME_VAL3]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[SCALAR_RECUR]] = phi double [ [[TMP25:%.*]], [[FOR_BODY]] ], [ [[SCALAR_RECUR_INIT]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[ARRAYIDX197:%.*]] = getelementptr i8, ptr [[DELTA]], i64 8
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[ARRAYIDX197]], align 4
; CHECK-NEXT:    [[CONV199:%.*]] = fpext float [[TMP23]] to double
; CHECK-NEXT:    [[ARRAYIDX210:%.*]] = getelementptr i8, ptr [[DELTA]], i64 12
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[ARRAYIDX210]], align 4
; CHECK-NEXT:    [[CONV212:%.*]] = fpext float [[TMP24]] to double
; CHECK-NEXT:    [[TMP25]] = call double @llvm.fmuladd.f64(double [[CONV212]], double 0.000000e+00, double [[CONV199]])
; CHECK-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 1
; CHECK-NEXT:    [[DELTA_NEXT]] = getelementptr i8, ptr [[DELTA]], i64 [[STRIDE]]
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp sgt i64 [[IV]], [[STRIDE]]
; CHECK-NEXT:    br i1 [[DOTNOT]], label [[LOOPEXIT]], label [[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
;
; CHECK-VERSIONING-LABEL: define void @test(
; CHECK-VERSIONING-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-VERSIONING-NEXT:  entry:
; CHECK-VERSIONING-NEXT:    [[SMAX:%.*]] = call i64 @llvm.smax.i64(i64 [[STRIDE]], i64 -1)
; CHECK-VERSIONING-NEXT:    [[TMP0:%.*]] = add i64 [[SMAX]], 2
; CHECK-VERSIONING-NEXT:    br label [[VECTOR_SCEVCHECK:%.*]]
; CHECK-VERSIONING:       vector.scevcheck:
; CHECK-VERSIONING-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[STRIDE]], 1
; CHECK-VERSIONING-NEXT:    br i1 [[IDENT_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-VERSIONING:       vector.ph:
; CHECK-VERSIONING-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; CHECK-VERSIONING-NEXT:    [[TMP3:%.*]] = sub i32 [[TMP2]], 1
; CHECK-VERSIONING-NEXT:    [[VECTOR_RECUR_INIT:%.*]] = insertelement <vscale x 2 x double> poison, double 0.000000e+00, i32 [[TMP3]]
; CHECK-VERSIONING-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-VERSIONING:       vector.body:
; CHECK-VERSIONING-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-VERSIONING-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-VERSIONING-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 2 x double> [ [[VECTOR_RECUR_INIT]], [[VECTOR_PH]] ], [ [[VP_OP:%.*]], [[VECTOR_BODY]] ]
; CHECK-VERSIONING-NEXT:    [[PREV_EVL:%.*]] = phi i32 [ [[TMP2]], [[VECTOR_PH]] ], [ [[TMP6:%.*]], [[VECTOR_BODY]] ]
; CHECK-VERSIONING-NEXT:    [[AVL:%.*]] = sub i64 [[TMP0]], [[EVL_BASED_IV1]]
; CHECK-VERSIONING-NEXT:    [[TMP6]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 2, i1 true)
; CHECK-VERSIONING-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[B]], i64 [[EVL_BASED_IV1]]
; CHECK-VERSIONING-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 8
; CHECK-VERSIONING-NEXT:    [[VP_STRIDED_LOAD:%.*]] = call <vscale x 2 x float> @llvm.experimental.vp.strided.load.nxv2f32.p0.i64(ptr align 4 [[TMP4]], i64 1, <vscale x 2 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-VERSIONING-NEXT:    [[VP_CAST:%.*]] = call <vscale x 2 x double> @llvm.vp.fpext.nxv2f64.nxv2f32(<vscale x 2 x float> [[VP_STRIDED_LOAD]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-VERSIONING-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[NEXT_GEP]], i64 12
; CHECK-VERSIONING-NEXT:    [[VP_STRIDED_LOAD1:%.*]] = call <vscale x 2 x float> @llvm.experimental.vp.strided.load.nxv2f32.p0.i64(ptr align 4 [[TMP5]], i64 1, <vscale x 2 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-VERSIONING-NEXT:    [[VP_CAST2:%.*]] = call <vscale x 2 x double> @llvm.vp.fpext.nxv2f64.nxv2f32(<vscale x 2 x float> [[VP_STRIDED_LOAD1]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-VERSIONING-NEXT:    [[VP_OP]] = call <vscale x 2 x double> @llvm.vp.fmuladd.nxv2f64(<vscale x 2 x double> [[VP_CAST2]], <vscale x 2 x double> zeroinitializer, <vscale x 2 x double> [[VP_CAST]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP6]])
; CHECK-VERSIONING-NEXT:    [[TMP9:%.*]] = call <vscale x 2 x double> @llvm.experimental.vp.splice.nxv2f64(<vscale x 2 x double> [[VECTOR_RECUR]], <vscale x 2 x double> [[VP_OP]], i32 -1, <vscale x 2 x i1> splat (i1 true), i32 [[PREV_EVL]], i32 [[TMP6]])
; CHECK-VERSIONING-NEXT:    [[TMP7:%.*]] = zext i32 [[TMP6]] to i64
; CHECK-VERSIONING-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP7]], [[EVL_BASED_IV1]]
; CHECK-VERSIONING-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP0]]
; CHECK-VERSIONING-NEXT:    br i1 [[TMP8]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-VERSIONING:       middle.block:
; CHECK-VERSIONING-NEXT:    [[TMP14:%.*]] = sub i32 [[TMP6]], 1
; CHECK-VERSIONING-NEXT:    [[TMP17:%.*]] = extractelement <vscale x 2 x double> [[TMP9]], i32 [[TMP14]]
; CHECK-VERSIONING-NEXT:    br label [[LOOPEXIT:%.*]]
; CHECK-VERSIONING:       scalar.ph:
; CHECK-VERSIONING-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[VECTOR_SCEVCHECK]] ]
; CHECK-VERSIONING-NEXT:    [[BC_RESUME_VAL4:%.*]] = phi ptr [ [[B]], [[VECTOR_SCEVCHECK]] ]
; CHECK-VERSIONING-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi double [ 0.000000e+00, [[VECTOR_SCEVCHECK]] ]
; CHECK-VERSIONING-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK-VERSIONING:       loopexit:
; CHECK-VERSIONING-NEXT:    [[S_LCSSA:%.*]] = phi double [ [[SCALAR_RECUR:%.*]], [[FOR_BODY]] ], [ [[TMP17]], [[MIDDLE_BLOCK]] ]
; CHECK-VERSIONING-NEXT:    [[CONV238:%.*]] = fptrunc double [[S_LCSSA]] to float
; CHECK-VERSIONING-NEXT:    store float [[CONV238]], ptr [[A]], align 4
; CHECK-VERSIONING-NEXT:    ret void
; CHECK-VERSIONING:       for.body:
; CHECK-VERSIONING-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[FOR_BODY]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-VERSIONING-NEXT:    [[DELTA:%.*]] = phi ptr [ [[DELTA_NEXT:%.*]], [[FOR_BODY]] ], [ [[BC_RESUME_VAL4]], [[SCALAR_PH]] ]
; CHECK-VERSIONING-NEXT:    [[SCALAR_RECUR]] = phi double [ [[TMP20:%.*]], [[FOR_BODY]] ], [ [[SCALAR_RECUR_INIT]], [[SCALAR_PH]] ]
; CHECK-VERSIONING-NEXT:    [[ARRAYIDX197:%.*]] = getelementptr i8, ptr [[DELTA]], i64 8
; CHECK-VERSIONING-NEXT:    [[TMP18:%.*]] = load float, ptr [[ARRAYIDX197]], align 4
; CHECK-VERSIONING-NEXT:    [[CONV199:%.*]] = fpext float [[TMP18]] to double
; CHECK-VERSIONING-NEXT:    [[ARRAYIDX210:%.*]] = getelementptr i8, ptr [[DELTA]], i64 12
; CHECK-VERSIONING-NEXT:    [[TMP19:%.*]] = load float, ptr [[ARRAYIDX210]], align 4
; CHECK-VERSIONING-NEXT:    [[CONV212:%.*]] = fpext float [[TMP19]] to double
; CHECK-VERSIONING-NEXT:    [[TMP20]] = call double @llvm.fmuladd.f64(double [[CONV212]], double 0.000000e+00, double [[CONV199]])
; CHECK-VERSIONING-NEXT:    [[IV_NEXT]] = add nsw i64 [[IV]], 1
; CHECK-VERSIONING-NEXT:    [[DELTA_NEXT]] = getelementptr i8, ptr [[DELTA]], i64 [[STRIDE]]
; CHECK-VERSIONING-NEXT:    [[DOTNOT:%.*]] = icmp sgt i64 [[IV]], [[STRIDE]]
; CHECK-VERSIONING-NEXT:    br i1 [[DOTNOT]], label [[LOOPEXIT]], label [[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
;
entry:
  br label %for.body

loopexit:
  %conv238 = fptrunc double %s to float
  store float %conv238, ptr %a, align 4
  ret void

for.body:
  %iv = phi i64 [ %iv.next, %for.body ], [ 0, %entry ]
  %delta = phi ptr [ %delta.next, %for.body ], [ %b, %entry ]
  %s = phi double [ %2, %for.body ], [ 0.000000e+00, %entry ]
  %arrayidx197 = getelementptr i8, ptr %delta, i64 8
  %0 = load float, ptr %arrayidx197, align 4
  %conv199 = fpext float %0 to double
  %arrayidx210 = getelementptr i8, ptr %delta, i64 12
  %1 = load float, ptr %arrayidx210, align 4
  %conv212 = fpext float %1 to double
  %2 = call double @llvm.fmuladd.f64(double %conv212, double 0.000000e+00, double %conv199)
  %iv.next = add nsw i64 %iv, 1
  %delta.next = getelementptr i8, ptr %delta, i64 %stride
  %.not = icmp sgt i64 %iv, %stride
  br i1 %.not, label %loopexit, label %for.body
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.fmuladd.f64(double, double, double) #0
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
; CHECK-VERSIONING: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK-VERSIONING: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK-VERSIONING: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK-VERSIONING: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK-VERSIONING: [[LOOP4]] = distinct !{[[LOOP4]]}
;.
