; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
;RUN: opt -p loop-vectorize -mcpu=sifive-cheetah -S < %s | FileCheck %s

; Check that VPlan optimization that folding ICmp/FCmp + Not => Cmp w/ inverse predicate correctly.
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define i32 @main() {
; CHECK-LABEL: define i32 @main(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br i1 false, label %[[VEC_UNCOUNTABLE_SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 100, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 16)
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 8, i1 true)
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [13 x i32], ptr null, i64 0, i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i32, ptr [[TMP2]], i32 0
; CHECK-NEXT:    [[VP_OP_LOAD_FF:%.*]] = call { <vscale x 8 x i32>, i32 } @llvm.vp.load.ff.nxv8i32.p0(ptr align 4 [[TMP3]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <vscale x 8 x i32>, i32 } [[VP_OP_LOAD_FF]], 0
; CHECK-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 8 x i1> @llvm.vp.icmp.nxv8i32(<vscale x 8 x i32> [[TMP5]], <vscale x 8 x i32> zeroinitializer, metadata !"ne", <vscale x 8 x i1> splat (i1 true), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> [[VP_OP_ICMP]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP4]])
; CHECK-NEXT:    [[TMP7:%.*]] = icmp sge i32 [[TMP6]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = zext i32 [[TMP4]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP8]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 100
; CHECK-NEXT:    [[TMP11:%.*]] = or i1 [[TMP7]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_SPLIT]]:
; CHECK-NEXT:    br i1 [[TMP7]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[FOR_END32_LOOPEXIT:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[IF_THEN28:.*]]
; CHECK:       [[VEC_UNCOUNTABLE_SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY22:.*]]
; CHECK:       [[FOR_COND20:.*]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT66:%.*]] = add i64 [[INDVARS_IV65:%.*]], 1
; CHECK-NEXT:    [[EXITCOND69_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT66]], 100
; CHECK-NEXT:    br i1 [[EXITCOND69_NOT]], label %[[FOR_END32_LOOPEXIT]], label %[[FOR_BODY22]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[FOR_BODY22]]:
; CHECK-NEXT:    [[INDVARS_IV65]] = phi i64 [ [[BC_RESUME_VAL]], %[[VEC_UNCOUNTABLE_SCALAR_PH]] ], [ [[INDVARS_IV_NEXT66]], %[[FOR_COND20]] ]
; CHECK-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr [13 x i32], ptr null, i64 0, i64 [[INDVARS_IV65]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[ARRAYIDX24]], align 4
; CHECK-NEXT:    [[CMP27_NOT:%.*]] = icmp eq i32 [[TMP10]], 0
; CHECK-NEXT:    br i1 [[CMP27_NOT]], label %[[FOR_COND20]], label %[[IF_THEN28]]
; CHECK:       [[IF_THEN28]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[FOR_END32_LOOPEXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %for.body22

for.cond20:
  %indvars.iv.next66 = add i64 %indvars.iv65, 1
  %exitcond69.not = icmp eq i64 %indvars.iv.next66, 100
  br i1 %exitcond69.not, label %for.end32.loopexit, label %for.body22

for.body22:
  %indvars.iv65 = phi i64 [ 0, %entry ], [ %indvars.iv.next66, %for.cond20 ]
  %arrayidx24 = getelementptr [13 x i32], ptr null, i64 0, i64 %indvars.iv65
  %0 = load i32, ptr %arrayidx24, align 4
  %cmp27.not = icmp eq i32 %0, 0
  br i1 %cmp27.not, label %for.cond20, label %if.then28

if.then28:
  unreachable

for.end32.loopexit:
  ret i32 0
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
