; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 -sifive-loop-vectorizer-enable-interleaved-access=invariant-stride -force-vectorization -passes=loop-vectorize < %s | FileCheck %s

define void @non_const_strided_store_factor_8(i64 %n, ptr %b, i64 %stride) {
; CHECK-LABEL: define void @non_const_strided_store_factor_8
; CHECK-SAME: (i64 [[N:%.*]], ptr [[B:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = mul nsw i64 [[INDVARS_IV]], [[STRIDE]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP1:%.*]] = trunc i64 [[INDVARS_IV]] to i32
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = add nsw i64 [[TMP0]], 1
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP2]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX4]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw i64 [[TMP0]], 2
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP3]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = add nsw i64 [[TMP0]], 3
; CHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP4]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX12]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = add nsw i64 [[TMP0]], 4
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP5]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX16]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = add nsw i64 [[TMP0]], 5
; CHECK-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP6]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX20]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = add nsw i64 [[TMP0]], 6
; CHECK-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP7]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX24]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = add nsw i64 [[TMP0]], 7
; CHECK-NEXT:    [[ARRAYIDX28:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[TMP8]]
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[ARRAYIDX28]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[EXIT:%.*]], label [[FOR_BODY]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %0 = mul nsw i64 %indvars.iv, %stride
  %arrayidx = getelementptr inbounds i32, ptr %b, i64 %0
  %1 = trunc i64 %indvars.iv to i32
  store i32 %1, ptr %arrayidx, align 4
  %2 = add nsw i64 %0, 1
  %arrayidx4 = getelementptr inbounds i32, ptr %b, i64 %2
  store i32 %1, ptr %arrayidx4, align 4
  %3 = add nsw i64 %0, 2
  %arrayidx8 = getelementptr inbounds i32, ptr %b, i64 %3
  store i32 %1, ptr %arrayidx8, align 4
  %4 = add nsw i64 %0, 3
  %arrayidx12 = getelementptr inbounds i32, ptr %b, i64 %4
  store i32 %1, ptr %arrayidx12, align 4
  %5 = add nsw i64 %0, 4
  %arrayidx16 = getelementptr inbounds i32, ptr %b, i64 %5
  store i32 %1, ptr %arrayidx16, align 4
  %6 = add nsw i64 %0, 5
  %arrayidx20 = getelementptr inbounds i32, ptr %b, i64 %6
  store i32 %1, ptr %arrayidx20, align 4
  %7 = add nsw i64 %0, 6
  %arrayidx24 = getelementptr inbounds i32, ptr %b, i64 %7
  store i32 %1, ptr %arrayidx24, align 4
  %8 = add nsw i64 %0, 7
  %arrayidx28 = getelementptr inbounds i32, ptr %b, i64 %8
  store i32 %1, ptr %arrayidx28, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %n
  br i1 %exitcond.not, label %exit, label %for.body

exit:                                             ; preds = %for.body
  ret void
}
