; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-vectorize -S -mtriple=riscv64-unknown-linux-gnu -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -mattr=+v -vectorizer-use-vp-strided-load-store < %s | FileCheck %s

define void @test(i32 %sub.pn.i194) {
; CHECK-LABEL: @test(
; CHECK-NEXT:  for.body213.preheader:
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP5:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 100, i32 2, i1 true)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[SUB_PN_I194:%.*]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <vscale x 2 x i32> [[BROADCAST_SPLAT]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = sub i64 100, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP0]], i32 2, i1 true)
; CHECK-NEXT:    call void @llvm.vp.scatter.nxv2i32.nxv2p0(<vscale x 2 x i32> [[TMP2]], <vscale x 2 x ptr> align 4 zeroinitializer, <vscale x 2 x i1> splat (i1 true), i32 [[TMP1]])
; CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP3]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 100
; CHECK-NEXT:    br i1 [[TMP4]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[FOR_END230_LOOPEXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[FOR_BODY213_PREHEADER:%.*]] ]
; CHECK-NEXT:    br label [[FOR_BODY213:%.*]]
; CHECK:       for.body213:
; CHECK-NEXT:    [[INDVARS_IV1351:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT1352:%.*]], [[FOR_BODY213]] ]
; CHECK-NEXT:    [[SUB_PN_FR_I198:%.*]] = freeze i32 [[SUB_PN_I194]]
; CHECK-NEXT:    store i32 [[SUB_PN_FR_I198]], ptr null, align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT1352]] = add nuw nsw i64 [[INDVARS_IV1351]], 1
; CHECK-NEXT:    [[EXITCOND1355_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT1352]], 100
; CHECK-NEXT:    br i1 [[EXITCOND1355_NOT]], label [[FOR_END230_LOOPEXIT]], label [[FOR_BODY213]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       for.end230.loopexit:
; CHECK-NEXT:    ret void
;
for.body213.preheader:
  br label %for.body213

for.body213:
  %indvars.iv1351 = phi i64 [ 0, %for.body213.preheader ], [ %indvars.iv.next1352, %for.body213 ]
  %sub.pn.fr.i198 = freeze i32 %sub.pn.i194
  store i32 %sub.pn.fr.i198, ptr null, align 4
  %indvars.iv.next1352 = add nuw nsw i64 %indvars.iv1351, 1
  %exitcond1355.not = icmp eq i64 %indvars.iv.next1352, 100
  br i1 %exitcond1355.not, label %for.end230.loopexit, label %for.body213

for.end230.loopexit:
  ret void
}
