; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -force-vector-width=4 -riscv-use-vla-vectorizer=false -scalable-vectorization=on -mtriple=riscv64 -mattr=+v -S < %s | FileCheck %s --check-prefix=SCALABLE
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -force-vector-width=4 -riscv-use-vla-vectorizer=true -scalable-vectorization=on -mtriple=riscv64 -mattr=+v -S < %s | FileCheck %s --check-prefix=VP-SCALABLE

;
; The test case is extracted from fmo.c (464.h264ref).
;
; int FmoGetLastCodedMBOfSliceGroup (int SliceGroupID)
; {
;   int i;
;   int LastMB = -1;
;
;   for (i=0; i<(int)img->PicSizeInMbs; i++)
;     if (FmoMB2SliceGroup (i) == SliceGroupID)
;       LastMB = i;
;   return LastMB;
; }
;

define i32 @FmoGetLastCodedMBOfSliceGroup(i32 %SliceGroupID, ptr %MBAmap, i32 %PicSizeInMbs) {
; SCALABLE-LABEL: define i32 @FmoGetLastCodedMBOfSliceGroup
; SCALABLE-SAME: (i32 [[SLICEGROUPID:%.*]], ptr [[MBAMAP:%.*]], i32 [[PICSIZEINMBS:%.*]]) #[[ATTR0:[0-9]+]] {
; SCALABLE-NEXT:  entry:
; SCALABLE-NEXT:    [[CMP4:%.*]] = icmp sgt i32 [[PICSIZEINMBS]], 0
; SCALABLE-NEXT:    br i1 [[CMP4]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_END:%.*]]
; SCALABLE:       for.body.lr.ph:
; SCALABLE-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[PICSIZEINMBS]] to i64
; SCALABLE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SCALABLE-NEXT:    [[TMP1:%.*]] = mul nuw i64 [[TMP0]], 4
; SCALABLE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[WIDE_TRIP_COUNT]], [[TMP1]]
; SCALABLE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; SCALABLE:       vector.ph:
; SCALABLE-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; SCALABLE-NEXT:    [[TMP3:%.*]] = mul nuw i64 [[TMP2]], 4
; SCALABLE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[WIDE_TRIP_COUNT]], [[TMP3]]
; SCALABLE-NEXT:    [[N_VEC:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[N_MOD_VF]]
; SCALABLE-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; SCALABLE-NEXT:    [[TMP5:%.*]] = mul nuw i64 [[TMP4]], 4
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[SLICEGROUPID]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[TMP6:%.*]] = call <vscale x 4 x i32> @llvm.stepvector.nxv4i32()
; SCALABLE-NEXT:    [[TMP7:%.*]] = mul <vscale x 4 x i32> [[TMP6]], splat (i32 1)
; SCALABLE-NEXT:    [[INDUCTION:%.*]] = add <vscale x 4 x i32> zeroinitializer, [[TMP7]]
; SCALABLE-NEXT:    [[TMP8:%.*]] = trunc i64 [[TMP5]] to i32
; SCALABLE-NEXT:    [[TMP9:%.*]] = mul i32 1, [[TMP8]]
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[TMP9]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i32> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    br label [[VECTOR_BODY:%.*]]
; SCALABLE:       vector.body:
; SCALABLE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ splat (i32 -2147483648), [[VECTOR_PH]] ], [ [[TMP14:%.*]], [[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i32> [ [[INDUCTION]], [[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], [[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i8, ptr [[MBAMAP]], i64 [[INDEX]]
; SCALABLE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i8, ptr [[TMP10]], i32 0
; SCALABLE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i8>, ptr [[TMP11]], align 1
; SCALABLE-NEXT:    [[TMP12:%.*]] = zext <vscale x 4 x i8> [[WIDE_LOAD]] to <vscale x 4 x i32>
; SCALABLE-NEXT:    [[TMP13:%.*]] = icmp eq <vscale x 4 x i32> [[TMP12]], [[BROADCAST_SPLAT]]
; SCALABLE-NEXT:    [[TMP14]] = select <vscale x 4 x i1> [[TMP13]], <vscale x 4 x i32> [[VEC_IND]], <vscale x 4 x i32> [[VEC_PHI]]
; SCALABLE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP5]]
; SCALABLE-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 4 x i32> [[VEC_IND]], [[BROADCAST_SPLAT2]]
; SCALABLE-NEXT:    [[TMP15:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; SCALABLE-NEXT:    br i1 [[TMP15]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; SCALABLE:       middle.block:
; SCALABLE-NEXT:    [[TMP16:%.*]] = call i32 @llvm.vector.reduce.smax.nxv4i32(<vscale x 4 x i32> [[TMP14]])
; SCALABLE-NEXT:    [[RDX_SELECT_CMP:%.*]] = icmp ne i32 [[TMP16]], -2147483648
; SCALABLE-NEXT:    [[RDX_SELECT:%.*]] = select i1 [[RDX_SELECT_CMP]], i32 [[TMP16]], i32 -1
; SCALABLE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[WIDE_TRIP_COUNT]], [[N_VEC]]
; SCALABLE-NEXT:    br i1 [[CMP_N]], label [[FOR_END_LOOPEXIT:%.*]], label [[SCALAR_PH]]
; SCALABLE:       scalar.ph:
; SCALABLE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[FOR_BODY_LR_PH]] ]
; SCALABLE-NEXT:    [[BC_MERGE_RDX:%.*]] = phi i32 [ [[RDX_SELECT]], [[MIDDLE_BLOCK]] ], [ -1, [[FOR_BODY_LR_PH]] ]
; SCALABLE-NEXT:    br label [[FOR_BODY:%.*]]
; SCALABLE:       for.body:
; SCALABLE-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; SCALABLE-NEXT:    [[LASTMB_06:%.*]] = phi i32 [ [[BC_MERGE_RDX]], [[SCALAR_PH]] ], [ [[SPEC_SELECT:%.*]], [[FOR_BODY]] ]
; SCALABLE-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds i8, ptr [[MBAMAP]], i64 [[INDVARS_IV]]
; SCALABLE-NEXT:    [[TMP17:%.*]] = load i8, ptr [[ARRAYIDX_I]], align 1
; SCALABLE-NEXT:    [[CONV_I:%.*]] = zext i8 [[TMP17]] to i32
; SCALABLE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[CONV_I]], [[SLICEGROUPID]]
; SCALABLE-NEXT:    [[TMP18:%.*]] = trunc i64 [[INDVARS_IV]] to i32
; SCALABLE-NEXT:    [[SPEC_SELECT]] = select i1 [[CMP1]], i32 [[TMP18]], i32 [[LASTMB_06]]
; SCALABLE-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; SCALABLE-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; SCALABLE-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_END_LOOPEXIT]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; SCALABLE:       for.end.loopexit:
; SCALABLE-NEXT:    [[SPEC_SELECT_LCSSA:%.*]] = phi i32 [ [[SPEC_SELECT]], [[FOR_BODY]] ], [ [[RDX_SELECT]], [[MIDDLE_BLOCK]] ]
; SCALABLE-NEXT:    br label [[FOR_END]]
; SCALABLE:       for.end:
; SCALABLE-NEXT:    [[LASTMB_0_LCSSA:%.*]] = phi i32 [ -1, [[ENTRY:%.*]] ], [ [[SPEC_SELECT_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; SCALABLE-NEXT:    ret i32 [[LASTMB_0_LCSSA]]
;
; VP-SCALABLE-LABEL: define i32 @FmoGetLastCodedMBOfSliceGroup
; VP-SCALABLE-SAME: (i32 [[SLICEGROUPID:%.*]], ptr [[MBAMAP:%.*]], i32 [[PICSIZEINMBS:%.*]]) #[[ATTR0:[0-9]+]] {
; VP-SCALABLE-NEXT:  entry:
; VP-SCALABLE-NEXT:    [[CMP4:%.*]] = icmp sgt i32 [[PICSIZEINMBS]], 0
; VP-SCALABLE-NEXT:    br i1 [[CMP4]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_END:%.*]]
; VP-SCALABLE:       for.body.lr.ph:
; VP-SCALABLE-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[PICSIZEINMBS]] to i64
; VP-SCALABLE-NEXT:    [[PROF_MIN_ITERS_CHECK:%.*]] = icmp ule i64 [[WIDE_TRIP_COUNT]], 12
; VP-SCALABLE-NEXT:    [[TMP0:%.*]] = or i1 false, [[PROF_MIN_ITERS_CHECK]]
; VP-SCALABLE-NEXT:    br i1 [[TMP0]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; VP-SCALABLE:       vector.ph:
; VP-SCALABLE-NEXT:    [[TMP1:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[WIDE_TRIP_COUNT]], i32 4, i1 true)
; VP-SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[SLICEGROUPID]], i64 0
; VP-SCALABLE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i32> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; VP-SCALABLE-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.stepvector.nxv4i32()
; VP-SCALABLE-NEXT:    [[TMP3:%.*]] = mul <vscale x 4 x i32> [[TMP2]], splat (i32 1)
; VP-SCALABLE-NEXT:    [[INDUCTION:%.*]] = add <vscale x 4 x i32> zeroinitializer, [[TMP3]]
; VP-SCALABLE-NEXT:    br label [[VECTOR_BODY:%.*]]
; VP-SCALABLE:       vector.body:
; VP-SCALABLE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; VP-SCALABLE-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; VP-SCALABLE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ splat (i32 -2147483648), [[VECTOR_PH]] ], [ [[VP_OP_MERGE:%.*]], [[VECTOR_BODY]] ]
; VP-SCALABLE-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x i32> [ [[INDUCTION]], [[VECTOR_PH]] ], [ [[VP_OP:%.*]], [[VECTOR_BODY]] ]
; VP-SCALABLE-NEXT:    [[AVL:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], [[EVL_BASED_IV]]
; VP-SCALABLE-NEXT:    [[TMP4:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; VP-SCALABLE-NEXT:    [[TMP5:%.*]] = mul i32 1, [[TMP4]]
; VP-SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i32> poison, i32 [[TMP5]], i64 0
; VP-SCALABLE-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i32> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i32> poison, <vscale x 4 x i32> zeroinitializer
; VP-SCALABLE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i8, ptr [[MBAMAP]], i64 [[EVL_BASED_IV]]
; VP-SCALABLE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i8, ptr [[TMP6]], i32 0
; VP-SCALABLE-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i8> @llvm.vp.load.nxv4i8.p0(ptr align 1 [[TMP7]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP4]])
; VP-SCALABLE-NEXT:    [[VP_CAST:%.*]] = call <vscale x 4 x i32> @llvm.vp.zext.nxv4i32.nxv4i8(<vscale x 4 x i8> [[VP_OP_LOAD]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP4]])
; VP-SCALABLE-NEXT:    [[VP_OP_ICMP:%.*]] = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i32(<vscale x 4 x i32> [[VP_CAST]], <vscale x 4 x i32> [[BROADCAST_SPLAT]], metadata !"eq", <vscale x 4 x i1> splat (i1 true), i32 [[TMP4]])
; VP-SCALABLE-NEXT:    [[VP_WIDEN_SELECT:%.*]] = call <vscale x 4 x i32> @llvm.vp.select.nxv4i32(<vscale x 4 x i1> [[VP_OP_ICMP]], <vscale x 4 x i32> [[VEC_IND]], <vscale x 4 x i32> [[VEC_PHI]], i32 [[TMP4]])
; VP-SCALABLE-NEXT:    [[VP_OP_MERGE]] = call <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> [[VP_WIDEN_SELECT]], <vscale x 4 x i32> [[VEC_PHI]], i32 [[TMP4]])
; VP-SCALABLE-NEXT:    [[TMP8:%.*]] = zext i32 [[TMP4]] to i64
; VP-SCALABLE-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP8]], [[EVL_BASED_IV]]
; VP-SCALABLE-NEXT:    [[VP_OP]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VEC_IND]], <vscale x 4 x i32> [[BROADCAST_SPLAT2]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP4]])
; VP-SCALABLE-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[WIDE_TRIP_COUNT]]
; VP-SCALABLE-NEXT:    br i1 [[TMP9]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VP-SCALABLE:       middle.block:
; VP-SCALABLE-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vp.reduce.smax.nxv4i32(i32 -2147483648, <vscale x 4 x i32> [[VP_OP_MERGE]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP1]])
; VP-SCALABLE-NEXT:    [[RDX_SELECT_CMP:%.*]] = icmp ne i32 [[TMP10]], -2147483648
; VP-SCALABLE-NEXT:    [[RDX_SELECT:%.*]] = select i1 [[RDX_SELECT_CMP]], i32 [[TMP10]], i32 -1
; VP-SCALABLE-NEXT:    br label [[FOR_END_LOOPEXIT:%.*]]
; VP-SCALABLE:       scalar.ph:
; VP-SCALABLE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[FOR_BODY_LR_PH]] ]
; VP-SCALABLE-NEXT:    [[BC_MERGE_RDX:%.*]] = phi i32 [ -1, [[FOR_BODY_LR_PH]] ]
; VP-SCALABLE-NEXT:    br label [[FOR_BODY:%.*]]
; VP-SCALABLE:       for.body:
; VP-SCALABLE-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; VP-SCALABLE-NEXT:    [[LASTMB_06:%.*]] = phi i32 [ [[BC_MERGE_RDX]], [[SCALAR_PH]] ], [ [[SPEC_SELECT:%.*]], [[FOR_BODY]] ]
; VP-SCALABLE-NEXT:    [[ARRAYIDX_I:%.*]] = getelementptr inbounds i8, ptr [[MBAMAP]], i64 [[INDVARS_IV]]
; VP-SCALABLE-NEXT:    [[TMP11:%.*]] = load i8, ptr [[ARRAYIDX_I]], align 1
; VP-SCALABLE-NEXT:    [[CONV_I:%.*]] = zext i8 [[TMP11]] to i32
; VP-SCALABLE-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[CONV_I]], [[SLICEGROUPID]]
; VP-SCALABLE-NEXT:    [[TMP12:%.*]] = trunc i64 [[INDVARS_IV]] to i32
; VP-SCALABLE-NEXT:    [[SPEC_SELECT]] = select i1 [[CMP1]], i32 [[TMP12]], i32 [[LASTMB_06]]
; VP-SCALABLE-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VP-SCALABLE-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; VP-SCALABLE-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_END_LOOPEXIT]], label [[FOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; VP-SCALABLE:       for.end.loopexit:
; VP-SCALABLE-NEXT:    [[SPEC_SELECT_LCSSA:%.*]] = phi i32 [ [[SPEC_SELECT]], [[FOR_BODY]] ], [ [[RDX_SELECT]], [[MIDDLE_BLOCK]] ]
; VP-SCALABLE-NEXT:    br label [[FOR_END]]
; VP-SCALABLE:       for.end:
; VP-SCALABLE-NEXT:    [[LASTMB_0_LCSSA:%.*]] = phi i32 [ -1, [[ENTRY:%.*]] ], [ [[SPEC_SELECT_LCSSA]], [[FOR_END_LOOPEXIT]] ]
; VP-SCALABLE-NEXT:    ret i32 [[LASTMB_0_LCSSA]]
;

entry:
  %cmp4 = icmp sgt i32 %PicSizeInMbs, 0
  br i1 %cmp4, label %for.body.lr.ph, label %for.end

for.body.lr.ph:                                   ; preds = %entry
  %wide.trip.count = zext i32 %PicSizeInMbs to i64
  br label %for.body

for.body:                                         ; preds = %for.body.lr.ph, %for.body
  %indvars.iv = phi i64 [ 0, %for.body.lr.ph ], [ %indvars.iv.next, %for.body ]
  %LastMB.06 = phi i32 [ -1, %for.body.lr.ph ], [ %spec.select, %for.body ]
  %arrayidx.i = getelementptr inbounds i8, ptr %MBAmap, i64 %indvars.iv
  %0 = load i8, ptr %arrayidx.i, align 1
  %conv.i = zext i8 %0 to i32
  %cmp1 = icmp eq i32 %conv.i, %SliceGroupID
  %1 = trunc i64 %indvars.iv to i32
  %spec.select = select i1 %cmp1, i32 %1, i32 %LastMB.06
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.end, label %for.body, !llvm.loop !0

for.end:                                          ; preds = %for.end, %entry
  %LastMB.0.lcssa = phi i32 [ -1, %entry ], [ %spec.select, %for.body ]
  ret i32 %LastMB.0.lcssa
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.vectorize.scalable.enable", i1 true}
