; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p470 -S %s 2>&1 | FileCheck %s

define void @foo(i32 %arg) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: i32 [[ARG:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[ADD:%.*]], %[[LOOP_NEXT:.*]] ]
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i32 [[ARG]], 0
; CHECK-NEXT:    br i1 [[COND]], label %[[IF_THEN:.*]], label %[[LOOP_NEXT]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    store double 0.000000e+00, ptr null, align 8
; CHECK-NEXT:    br label %[[LOOP_NEXT]]
; CHECK:       [[LOOP_NEXT]]:
; CHECK-NEXT:    [[ADD]] = add i64 [[PHI]], 1
; CHECK-NEXT:    [[ICMP112:%.*]] = icmp eq i64 [[ADD]], 0
; CHECK-NEXT:    br i1 [[ICMP112]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %phi = phi i64 [ 0, %entry ], [ %add, %loop.next ]
  %cond = icmp eq i32 %arg, 0
  br i1 %cond, label %if.then, label %loop.next

if.then:
  store double 0.000000e+00, ptr null, align 8
  br label %loop.next

loop.next:
  %add = add i64 %phi, 1
  %icmp112 = icmp eq i64 %add, 0
  br i1 %icmp112, label %exit, label %loop

exit:
  ret void
}
