; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -vectorize-with-known-depdist=true -passes=loop-vectorize -riscv-use-vla-vectorizer=true -mtriple=riscv64 -mattr=+d,+v -riscv-v-vector-bits-min=512 %s | FileCheck %s

; This test checks to make sure that the stride of pointer access in the vector loop is the maximum safe number of elements, opposed to the number of unrolled elements.

%struct = type <{ ptr, double }>
%struct2 = type <{ ptr, ptr, ptr }>

define void @widget(ptr %a, i64 %n) {
; CHECK-LABEL: @widget(
; CHECK-NEXT:  ph:
; CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds [[STRUCT2:%.*]], ptr [[A:%.*]], i64 0, i32 2
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[N:%.*]], 1
; CHECK-NEXT:    [[UMIN:%.*]] = call i64 @llvm.umin.i64(i64 [[N]], i64 1)
; CHECK-NEXT:    [[TMP1:%.*]] = sub i64 [[TMP0]], [[UMIN]]
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP1]], i32 1, i1 true)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i64 [[TMP1]], [[TMP4]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.umin.i64(i64 [[AVL]], i64 2)
; CHECK-NEXT:    [[TMP25:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP3]], i32 1, i1 true)
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = mul i64 [[TMP4]], -16
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[OFFSET_IDX5:%.*]] = mul i64 [[TMP4]], -16
; CHECK-NEXT:    [[NEXT_GEP6:%.*]] = getelementptr i8, ptr [[B]], i64 [[OFFSET_IDX5]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr [[STRUCT:%.*]], ptr [[NEXT_GEP6]], i64 -1, i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP25]] to i64
; CHECK-NEXT:    [[TMP7:%.*]] = mul i64 0, [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = sub i64 [[TMP6]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = mul i64 -2, [[TMP8]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr ptr, ptr [[TMP5]], i64 [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr ptr, ptr [[TMP17]], i64 [[TMP16]]
; CHECK-NEXT:    [[TMP10:%.*]] = mul nuw nsw i32 [[TMP25]], 2
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 2 x ptr> @llvm.vp.load.nxv2p0.p0(ptr align 8 [[TMP9]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP10]])
; CHECK-NEXT:    [[DEINTERLEAVED_RESULTS:%.*]] = call { <vscale x 1 x ptr>, <vscale x 1 x ptr> } @llvm.vector.deinterleave2.nxv2p0(<vscale x 2 x ptr> [[WIDE_MASKED_LOAD]])
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <vscale x 1 x ptr>, <vscale x 1 x ptr> } [[DEINTERLEAVED_RESULTS]], 0
; CHECK-NEXT:    [[DEINTERLEAVED_RESULT_REVERSE:%.*]] = call <vscale x 1 x ptr> @llvm.experimental.vp.reverse.nxv1p0(<vscale x 1 x ptr> [[TMP11]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP25]])
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <vscale x 1 x ptr>, <vscale x 1 x ptr> } [[DEINTERLEAVED_RESULTS]], 1
; CHECK-NEXT:    [[DEINTERLEAVED_RESULT_REVERSE3:%.*]] = call <vscale x 1 x ptr> @llvm.experimental.vp.reverse.nxv1p0(<vscale x 1 x ptr> [[TMP12]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP25]])
; CHECK-NEXT:    [[TMP13:%.*]] = ptrtoint <vscale x 1 x ptr> [[DEINTERLEAVED_RESULT_REVERSE3]] to <vscale x 1 x i64>
; CHECK-NEXT:    [[TMP14:%.*]] = bitcast <vscale x 1 x i64> [[TMP13]] to <vscale x 1 x double>
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr [[STRUCT]], ptr [[NEXT_GEP]], i64 -2, i32 0
; CHECK-NEXT:    [[TMP18:%.*]] = zext i32 [[TMP25]] to i64
; CHECK-NEXT:    [[TMP26:%.*]] = mul i64 0, [[TMP18]]
; CHECK-NEXT:    [[TMP27:%.*]] = sub i64 [[TMP18]], 1
; CHECK-NEXT:    [[TMP28:%.*]] = mul i64 -2, [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr double, ptr [[TMP15]], i64 [[TMP26]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr double, ptr [[TMP29]], i64 [[TMP28]]
; CHECK-NEXT:    [[RESULT_REVERSE:%.*]] = call <vscale x 1 x ptr> @llvm.experimental.vp.reverse.nxv1p0(<vscale x 1 x ptr> [[DEINTERLEAVED_RESULT_REVERSE]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP25]])
; CHECK-NEXT:    [[TMP20:%.*]] = ptrtoint <vscale x 1 x ptr> [[RESULT_REVERSE]] to <vscale x 1 x i64>
; CHECK-NEXT:    [[TMP21:%.*]] = bitcast <vscale x 1 x i64> [[TMP20]] to <vscale x 1 x double>
; CHECK-NEXT:    [[RESULT_REVERSE4:%.*]] = call <vscale x 1 x double> @llvm.experimental.vp.reverse.nxv1f64(<vscale x 1 x double> [[TMP14]], <vscale x 1 x i1> splat (i1 true), i32 [[TMP25]])
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = call <vscale x 2 x double> @llvm.vector.interleave2.nxv2f64(<vscale x 1 x double> [[TMP21]], <vscale x 1 x double> [[RESULT_REVERSE4]])
; CHECK-NEXT:    [[TMP22:%.*]] = mul nuw nsw i32 [[TMP25]], 2
; CHECK-NEXT:    call void @llvm.vp.store.nxv2f64.p0(<vscale x 2 x double> [[INTERLEAVED_VEC]], ptr align 8 [[TMP19]], <vscale x 2 x i1> splat (i1 true), i32 [[TMP22]])
; CHECK-NEXT:    [[TMP23:%.*]] = zext i32 [[TMP25]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP23]], [[TMP4]]
; CHECK-NEXT:    [[TMP24:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], [[TMP1]]
; CHECK-NEXT:    br i1 [[TMP24]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[EXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N]], [[PH:%.*]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL5:%.*]] = phi ptr [ [[A]], [[PH]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL6:%.*]] = phi ptr [ [[B]], [[PH]] ]
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[TMP31:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[IV:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = phi ptr [ [[BC_RESUME_VAL5]], [[SCALAR_PH]] ], [ [[TMP34:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = phi ptr [ [[BC_RESUME_VAL6]], [[SCALAR_PH]] ], [ [[TMP35:%.*]], [[LOOP]] ]
; CHECK-NEXT:    [[TMP34]] = getelementptr inbounds [[STRUCT]], ptr [[TMP32]], i64 -1
; CHECK-NEXT:    [[TMP35]] = getelementptr inbounds [[STRUCT]], ptr [[TMP33]], i64 -1
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr [[STRUCT]], ptr [[TMP33]], i64 -1, i32 0
; CHECK-NEXT:    [[TMP37:%.*]] = load ptr, ptr [[TMP36]], align 8
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr [[STRUCT]], ptr [[TMP32]], i64 -2, i32 0
; CHECK-NEXT:    store ptr [[TMP37]], ptr [[TMP38]], align 8
; CHECK-NEXT:    [[TMP39:%.*]] = getelementptr [[STRUCT]], ptr [[TMP33]], i64 -1, i32 1
; CHECK-NEXT:    [[TMP40:%.*]] = load double, ptr [[TMP39]], align 8
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr [[STRUCT]], ptr [[TMP32]], i64 -2, i32 1
; CHECK-NEXT:    store double [[TMP40]], ptr [[TMP41]], align 8
; CHECK-NEXT:    [[IV]] = add nsw i64 [[TMP31]], -1
; CHECK-NEXT:    [[COND:%.*]] = icmp ugt i64 [[TMP31]], 1
; CHECK-NEXT:    br i1 [[COND]], label [[LOOP]], label [[EXIT]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
ph:
  ; By casting %a to %struct2 and using index 2, a maximum
  ; safe vector width is created since %struct only has an element at index
  ; 0 and index 1. In this example, a ptr is the same size as the double since
  ; we're using riscv64, so %b must be two 64 bit elements ahead of %a.
  %b = getelementptr inbounds %struct2, ptr %a, i64 0, i32 2
  br label %loop

loop:
  %0 = phi i64 [%n, %ph], [%iv, %loop]
  %1 = phi ptr [%a, %ph], [%3, %loop]
  %2 = phi ptr [%b, %ph], [%4, %loop]
  %3 = getelementptr inbounds %struct, ptr %1, i64 -1
  %4 = getelementptr inbounds %struct, ptr %2, i64 -1

  ; A[i-2].ptr = B[i-1].ptr
  %5 = getelementptr %struct, ptr %2, i64 -1, i32 0
  %6 = load ptr, ptr %5, align 8
  %7 = getelementptr %struct, ptr %1, i64 -2, i32 0
  store ptr %6, ptr %7, align 8

  ; A[i-2].double = B[i-1].double
  %8 = getelementptr %struct, ptr %2, i64 -1, i32 1
  %9 = load double, ptr %8, align 8
  %10 = getelementptr %struct, ptr %1, i64 -2, i32 1
  store double %9, ptr %10, align 8

  %iv = add nsw i64 %0, -1
  %cond = icmp ugt i64 %0, 1
  br i1 %cond, label %loop, label %exit

exit:
  ret void
}
