; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p670 -force-vectorization %s -S | FileCheck %s

define fastcc i32 @S_unpack_rec(i64 %0) {
; CHECK-LABEL: define fastcc i32 @S_unpack_rec(
; CHECK-SAME: i64 [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[TMP10:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP3:%.*]] = mul i32 [[TMP10]], 2
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 536870912, [[TMP3]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP5:%.*]] = mul i32 [[TMP4]], 2
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = urem i32 536870912, [[TMP5]]
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 536870912, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP12:%.*]] = mul i32 [[TMP11]], 2
; CHECK-NEXT:    [[TMP13:%.*]] = mul i32 [[TMP2]], -8
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    store i64 0, ptr null, align 8
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], [[TMP12]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[TMP2]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i32 536870912, [[TMP2]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[BB14:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[TMP13]], %[[MIDDLE_BLOCK]] ], [ 0, [[TMP1:%.*]] ]
; CHECK-NEXT:    br label %[[BB10:.*]]
; CHECK:       [[BB10]]:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i32 [ [[TMP7:%.*]], %[[BB10]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    store i64 0, ptr null, align 8
; CHECK-NEXT:    [[TMP7]] = add nsw i32 [[TMP6]], -8
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP6]], 1
; CHECK-NEXT:    br i1 [[TMP8]], label %[[BB14]], label %[[BB10]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[BB14]]:
; CHECK-NEXT:    [[TMP15:%.*]] = phi i64 [ [[TMP0]], %[[BB10]] ], [ [[TMP0]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret i32 0
;
  br label %2

2:
  %3 = phi i32 [ %4, %2 ], [ 0, %1 ]
  store i64 0, ptr null, align 8
  %4 = add nsw i32 %3, -8
  %5 = icmp eq i32 %3, 1
  br i1 %5, label %6, label %2

6:
  %7 = phi i64 [ %0, %2 ]
  ret i32 0
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
