; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -passes=loop-vectorize -mtriple riscv64-unknown-linux-gnu -riscv-use-vla-vectorizer -mcpu=sifive-p470  %s| FileCheck %s

%Point = type { %Tensor }
%Tensor = type { [3 x double] }

define void @test(i32 %input, ptr %0) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: i32 [[INPUT:%.*]], ptr [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[INPUT]], 1
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.experimental.get.vector.length.i32(i32 [[TMP1]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i64> @llvm.stepvector.nxv4i64()
; CHECK-NEXT:    [[TMP14:%.*]] = uitofp <vscale x 4 x i64> [[TMP5]] to <vscale x 4 x double>
; CHECK-NEXT:    [[TMP7:%.*]] = fmul reassoc <vscale x 4 x double> [[TMP14]], splat (double 1.000000e+00)
; CHECK-NEXT:    [[INDUCTION:%.*]] = fadd reassoc <vscale x 4 x double> zeroinitializer, [[TMP7]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[EVL_BASED_IV1:%.*]] = phi i32 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT1:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i32 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT1]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 4 x double> [ [[INDUCTION]], [[VECTOR_PH]] ], [ [[STEP_ADD:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = sub i32 [[TMP1]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP8:%.*]] = call i32 @llvm.experimental.get.vector.length.i32(i32 [[AVL]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP11:%.*]] = uitofp i32 [[TMP8]] to double
; CHECK-NEXT:    [[TMP12:%.*]] = fmul reassoc double 1.000000e+00, [[TMP11]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x double> poison, double [[TMP12]], i64 0
; CHECK-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 4 x double> [[BROADCAST_SPLATINSERT]], <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = zext i32 [[EVL_BASED_IV]] to i64
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr [[POINT:%.*]], ptr [[TMP0]], i64 [[TMP9]], i32 0, i32 0, i64 2
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4f64.p0.i64(<vscale x 4 x double> [[VEC_IND]], ptr align 8 [[TMP10]], i64 24, <vscale x 4 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[INDEX_EVL_NEXT1]] = add nuw i32 [[TMP8]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[STEP_ADD]] = call reassoc <vscale x 4 x double> @llvm.vp.fadd.nxv4f64(<vscale x 4 x double> [[VEC_IND]], <vscale x 4 x double> [[DOTSPLAT]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP8]])
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq i32 [[INDEX_EVL_NEXT1]], [[TMP1]]
; CHECK-NEXT:    br i1 [[TMP13]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    br label [[LOOPEXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL1:%.*]] = phi double [ 0.000000e+00, [[ENTRY]] ]
; CHECK-NEXT:    br label [[PREHEADER:%.*]]
; CHECK:       preheader:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], [[PREHEADER]] ]
; CHECK-NEXT:    [[Y:%.*]] = phi double [ [[BC_RESUME_VAL1]], [[SCALAR_PH]] ], [ [[Y_NEXT:%.*]], [[PREHEADER]] ]
; CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[IV]] to i64
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [[POINT]], ptr [[TMP0]], i64 [[CONV]], i32 0, i32 0, i64 2
; CHECK-NEXT:    store double [[Y]], ptr [[ARRAYIDX]], align 8
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[Y_NEXT]] = fadd reassoc double [[Y]], 1.000000e+00
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[IV]], [[INPUT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[LOOPEXIT]], label [[PREHEADER]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       loopexit:
; CHECK-NEXT:    ret void
;
entry:
  br label %preheader

preheader:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %preheader ]
  %y = phi double [ 0.000000e+00, %entry ], [ %y.next, %preheader ]
  %conv = zext i32 %iv to i64
  %arrayidx = getelementptr %Point, ptr %0, i64 %conv, i32 0, i32 0, i64 2
  store double %y, ptr %arrayidx, align 8
  %iv.next = add i32 %iv, 1
  %y.next = fadd reassoc double %y, 1.000000e+00
  %exitcond = icmp eq i32 %iv, %input
  br i1 %exitcond, label %loopexit, label %preheader

loopexit:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]], [[META3:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.isvectorized.tailfoldingstyle", !"evl"}
; CHECK: [[META3]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META3]], [[META1]]}
;.
