; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p470 -S %s 2>&1 | FileCheck %s --check-prefixes=P470
; RUN: opt -passes=loop-vectorize -mtriple riscv64 -mcpu=sifive-p470 -sifive-loop-vectorizer-use-vplan-based-cost-model=false -S %s 2>&1 | FileCheck %s --check-prefixes=P470

; Extracted from 445.gobmk engine/move_reasons.c:1599.
; This loop can be vectorized but not beneficial.
define void @mark_safe_stones(i32 %color, ptr %saved_dragons, ptr %saved_worms, ptr %safe_stones, ptr %board, i8 %0, i8 %1) {
;
; P470-LABEL: define void @mark_safe_stones(
; P470-SAME: i32 [[COLOR:%.*]], ptr [[SAVED_DRAGONS:%.*]], ptr [[SAVED_WORMS:%.*]], ptr [[SAFE_STONES:%.*]], ptr [[BOARD:%.*]], i8 [[TMP0:%.*]], i8 [[TMP1:%.*]]) #[[ATTR0:[0-9]+]] {
; P470-NEXT:  [[ENTRY:.*]]:
; P470-NEXT:    br label %[[FOR_BODY:.*]]
; P470:       [[FOR_BODY]]:
; P470-NEXT:    [[INDVARS_IV11:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ]
; P470-NEXT:    [[CMP1:%.*]] = icmp eq i8 [[TMP0]], 0
; P470-NEXT:    br i1 [[CMP1]], label %[[IF_THEN:.*]], label %[[IF_ELSE22:.*]]
; P470:       [[IF_THEN]]:
; P470-NEXT:    [[TMP2:%.*]] = load i32, ptr [[SAVED_DRAGONS]], align 4
; P470-NEXT:    [[CMP5:%.*]] = icmp eq i32 [[TMP2]], 0
; P470-NEXT:    br i1 [[CMP5]], label %[[IF_THEN17:.*]], label %[[LOR_LHS_FALSE:.*]]
; P470:       [[LOR_LHS_FALSE]]:
; P470-NEXT:    [[TMP3:%.*]] = load i32, ptr [[SAVED_WORMS]], align 4
; P470-NEXT:    [[CMP10_NOT:%.*]] = icmp eq i32 [[TMP3]], 0
; P470-NEXT:    br i1 [[CMP10_NOT]], label %[[IF_ELSE:.*]], label %[[LAND_LHS_TRUE:.*]]
; P470:       [[LAND_LHS_TRUE]]:
; P470-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SAVED_DRAGONS]], align 4
; P470-NEXT:    [[CMP15:%.*]] = icmp eq i32 [[TMP4]], 0
; P470-NEXT:    br i1 [[CMP15]], label %[[IF_THEN17]], label %[[IF_ELSE]]
; P470:       [[IF_THEN17]]:
; P470-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr i8, ptr [[SAFE_STONES]], i64 [[INDVARS_IV11]]
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX19]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[IF_ELSE]]:
; P470-NEXT:    [[ARRAYIDX21:%.*]] = getelementptr i8, ptr [[SAFE_STONES]], i64 [[INDVARS_IV11]]
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX21]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[IF_ELSE22]]:
; P470-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; P470-NEXT:    [[CMP26:%.*]] = icmp eq i32 [[COLOR]], [[CONV]]
; P470-NEXT:    br i1 [[CMP26]], label %[[IF_THEN28:.*]], label %[[IF_ELSE76:.*]]
; P470:       [[IF_THEN28]]:
; P470-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SAVED_DRAGONS]], align 4
; P470-NEXT:    [[CMP33_NOT:%.*]] = icmp eq i32 [[TMP5]], 0
; P470-NEXT:    br i1 [[CMP33_NOT]], label %[[LOR_LHS_FALSE45:.*]], label %[[LAND_LHS_TRUE35:.*]]
; P470:       [[LAND_LHS_TRUE35]]:
; P470-NEXT:    [[CMP40:%.*]] = icmp eq i32 [[COLOR]], 0
; P470-NEXT:    br i1 [[CMP40]], label %[[IF_THEN51:.*]], label %[[LOR_LHS_FALSE42:.*]]
; P470:       [[LOR_LHS_FALSE42]]:
; P470-NEXT:    [[TMP6:%.*]] = load i8, ptr [[SAVED_DRAGONS]], align 1
; P470-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i8 [[TMP6]], 0
; P470-NEXT:    br i1 [[TOBOOL_NOT]], label %[[IF_THEN51]], label %[[LOR_LHS_FALSE45]]
; P470:       [[LOR_LHS_FALSE45]]:
; P470-NEXT:    [[TMP7:%.*]] = load i32, ptr [[BOARD]], align 4
; P470-NEXT:    [[CMP49:%.*]] = icmp eq i32 [[TMP7]], 0
; P470-NEXT:    br i1 [[CMP49]], label %[[IF_THEN51]], label %[[IF_ELSE54:.*]]
; P470:       [[IF_THEN51]]:
; P470-NEXT:    [[ARRAYIDX53:%.*]] = getelementptr i8, ptr [[SAFE_STONES]], i64 [[INDVARS_IV11]]
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX53]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[IF_ELSE54]]:
; P470-NEXT:    [[TOBOOL57_NOT:%.*]] = icmp eq i8 [[TMP1]], 0
; P470-NEXT:    br i1 [[TOBOOL57_NOT]], label %[[IF_ELSE61:.*]], label %[[IF_THEN58:.*]]
; P470:       [[IF_THEN58]]:
; P470-NEXT:    [[ARRAYIDX60:%.*]] = getelementptr i8, ptr [[SAFE_STONES]], i64 [[INDVARS_IV11]]
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX60]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[IF_ELSE61]]:
; P470-NEXT:    [[CMP65:%.*]] = icmp eq i32 [[COLOR]], 0
; P470-NEXT:    [[ARRAYIDX69:%.*]] = getelementptr i8, ptr [[SAFE_STONES]], i64 [[INDVARS_IV11]]
; P470-NEXT:    br i1 [[CMP65]], label %[[IF_THEN67:.*]], label %[[IF_ELSE70:.*]]
; P470:       [[IF_THEN67]]:
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX69]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[IF_ELSE70]]:
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX69]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[IF_ELSE76]]:
; P470-NEXT:    [[ARRAYIDX78:%.*]] = getelementptr i8, ptr [[SAFE_STONES]], i64 [[INDVARS_IV11]]
; P470-NEXT:    store i8 0, ptr [[ARRAYIDX78]], align 1
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[FOR_INC]]:
; P470-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV11]], 1
; P470-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV11]], 400
; P470-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]]
; P470:       [[FOR_END]]:
; P470-NEXT:    ret void
;
entry:
  br label %for.body

for.body:                                         ; preds = %for.inc, %entry
  %indvars.iv11 = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.inc ]
  %cmp1 = icmp eq i8 %0, 0
  br i1 %cmp1, label %if.then, label %if.else22

if.then:                                          ; preds = %for.body
  %2 = load i32, ptr %saved_dragons, align 4
  %cmp5 = icmp eq i32 %2, 0
  br i1 %cmp5, label %if.then17, label %lor.lhs.false

lor.lhs.false:                                    ; preds = %if.then
  %3 = load i32, ptr %saved_worms, align 4
  %cmp10.not = icmp eq i32 %3, 0
  br i1 %cmp10.not, label %if.else, label %land.lhs.true

land.lhs.true:                                    ; preds = %lor.lhs.false
  %4 = load i32, ptr %saved_dragons, align 4
  %cmp15 = icmp eq i32 %4, 0
  br i1 %cmp15, label %if.then17, label %if.else

if.then17:                                        ; preds = %land.lhs.true, %if.then
  %arrayidx19 = getelementptr i8, ptr %safe_stones, i64 %indvars.iv11
  store i8 0, ptr %arrayidx19, align 1
  br label %for.inc

if.else:                                          ; preds = %land.lhs.true, %lor.lhs.false
  %arrayidx21 = getelementptr i8, ptr %safe_stones, i64 %indvars.iv11
  store i8 0, ptr %arrayidx21, align 1
  br label %for.inc

if.else22:                                        ; preds = %for.body
  %conv = zext i8 %0 to i32
  %cmp26 = icmp eq i32 %color, %conv
  br i1 %cmp26, label %if.then28, label %if.else76

if.then28:                                        ; preds = %if.else22
  %5 = load i32, ptr %saved_dragons, align 4
  %cmp33.not = icmp eq i32 %5, 0
  br i1 %cmp33.not, label %lor.lhs.false45, label %land.lhs.true35

land.lhs.true35:                                  ; preds = %if.then28
  %cmp40 = icmp eq i32 %color, 0
  br i1 %cmp40, label %if.then51, label %lor.lhs.false42

lor.lhs.false42:                                  ; preds = %land.lhs.true35
  %6 = load i8, ptr %saved_dragons, align 1
  %tobool.not = icmp eq i8 %6, 0
  br i1 %tobool.not, label %if.then51, label %lor.lhs.false45

lor.lhs.false45:                                  ; preds = %lor.lhs.false42, %if.then28
  %7 = load i32, ptr %board, align 4
  %cmp49 = icmp eq i32 %7, 0
  br i1 %cmp49, label %if.then51, label %if.else54

if.then51:                                        ; preds = %lor.lhs.false45, %lor.lhs.false42, %land.lhs.true35
  %arrayidx53 = getelementptr i8, ptr %safe_stones, i64 %indvars.iv11
  store i8 0, ptr %arrayidx53, align 1
  br label %for.inc

if.else54:                                        ; preds = %lor.lhs.false45
  %tobool57.not = icmp eq i8 %1, 0
  br i1 %tobool57.not, label %if.else61, label %if.then58

if.then58:                                        ; preds = %if.else54
  %arrayidx60 = getelementptr i8, ptr %safe_stones, i64 %indvars.iv11
  store i8 0, ptr %arrayidx60, align 1
  br label %for.inc

if.else61:                                        ; preds = %if.else54
  %cmp65 = icmp eq i32 %color, 0
  %arrayidx69 = getelementptr i8, ptr %safe_stones, i64 %indvars.iv11
  br i1 %cmp65, label %if.then67, label %if.else70

if.then67:                                        ; preds = %if.else61
  store i8 0, ptr %arrayidx69, align 1
  br label %for.inc

if.else70:                                        ; preds = %if.else61
  store i8 0, ptr %arrayidx69, align 1
  br label %for.inc

if.else76:                                        ; preds = %if.else22
  %arrayidx78 = getelementptr i8, ptr %safe_stones, i64 %indvars.iv11
  store i8 0, ptr %arrayidx78, align 1
  br label %for.inc

for.inc:                                          ; preds = %if.else76, %if.else70, %if.then67, %if.then58, %if.then51, %if.else, %if.then17
  %indvars.iv.next = add i64 %indvars.iv11, 1
  %exitcond.not = icmp eq i64 %indvars.iv11, 400
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:                                          ; preds = %for.inc
  ret void
}

; Extracted from engine/aftermath.c:124. Should not be vectorize.
define i32 @aftermath_genmove(i32 %color, ptr %board, ptr %distance) {
; P470-LABEL: define i32 @aftermath_genmove(
; P470-SAME: i32 [[COLOR:%.*]], ptr [[BOARD:%.*]], ptr [[DISTANCE:%.*]]) #[[ATTR0]] {
; P470-NEXT:  [[ENTRY:.*]]:
; P470-NEXT:    br label %[[FOR_BODY:.*]]
; P470:       [[FOR_BODY]]:
; P470-NEXT:    [[INDVARS_IV3:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_INC:.*]] ]
; P470-NEXT:    [[ARRAYIDX:%.*]] = getelementptr [421 x i8], ptr [[BOARD]], i64 0, i64 [[INDVARS_IV3]]
; P470-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; P470-NEXT:    [[CMP2_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; P470-NEXT:    br i1 [[CMP2_NOT]], label %[[FOR_INC]], label %[[IF_ELSE:.*]]
; P470:       [[IF_ELSE]]:
; P470-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; P470-NEXT:    [[CMP7:%.*]] = icmp eq i32 [[COLOR]], [[CONV]]
; P470-NEXT:    br i1 [[CMP7]], label %[[LAND_LHS_TRUE:.*]], label %[[IF_ELSE14:.*]]
; P470:       [[LAND_LHS_TRUE]]:
; P470-NEXT:    [[TMP1:%.*]] = load i32, ptr [[BOARD]], align 4
; P470-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[TMP1]], 0
; P470-NEXT:    br i1 [[TOBOOL_NOT]], label %[[IF_ELSE14]], label %[[FOR_INC_SINK_SPLIT:.*]]
; P470:       [[IF_ELSE14]]:
; P470-NEXT:    br i1 true, label %[[LAND_LHS_TRUE16:.*]], label %[[IF_ELSE41:.*]]
; P470:       [[LAND_LHS_TRUE16]]:
; P470-NEXT:    [[CMP20:%.*]] = icmp eq i32 [[COLOR]], [[CONV]]
; P470-NEXT:    br i1 [[CMP20]], label %[[LAND_LHS_TRUE22:.*]], label %[[LOR_LHS_FALSE:.*]]
; P470:       [[LAND_LHS_TRUE22]]:
; P470-NEXT:    [[TMP2:%.*]] = load i32, ptr [[BOARD]], align 4
; P470-NEXT:    [[CMP25:%.*]] = icmp eq i32 [[TMP2]], 0
; P470-NEXT:    br i1 [[CMP25]], label %[[FOR_INC_SINK_SPLIT]], label %[[LOR_LHS_FALSE]]
; P470:       [[LOR_LHS_FALSE]]:
; P470-NEXT:    br i1 [[CMP7]], label %[[LAND_LHS_TRUE32:.*]], label %[[IF_ELSE41]]
; P470:       [[LAND_LHS_TRUE32]]:
; P470-NEXT:    [[TMP3:%.*]] = load i32, ptr [[BOARD]], align 4
; P470-NEXT:    [[CMP36:%.*]] = icmp eq i32 [[TMP3]], 0
; P470-NEXT:    br i1 [[CMP36]], label %[[FOR_INC_SINK_SPLIT]], label %[[IF_ELSE41]]
; P470:       [[IF_ELSE41]]:
; P470-NEXT:    br label %[[FOR_INC_SINK_SPLIT]]
; P470:       [[FOR_INC_SINK_SPLIT]]:
; P470-NEXT:    [[DOTSINK:%.*]] = phi i32 [ 1, %[[IF_ELSE41]] ], [ 0, %[[LAND_LHS_TRUE]] ], [ 0, %[[LAND_LHS_TRUE32]] ], [ 0, %[[LAND_LHS_TRUE22]] ]
; P470-NEXT:    [[ARRAYIDX40:%.*]] = getelementptr [400 x i32], ptr [[DISTANCE]], i64 0, i64 [[INDVARS_IV3]]
; P470-NEXT:    store i32 [[DOTSINK]], ptr [[ARRAYIDX40]], align 4
; P470-NEXT:    br label %[[FOR_INC]]
; P470:       [[FOR_INC]]:
; P470-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV3]], 1
; P470-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV3]], 400
; P470-NEXT:    br i1 [[EXITCOND_NOT]], label %[[DO_BODY_PREHEADER:.*]], label %[[FOR_BODY]]
; P470:       [[DO_BODY_PREHEADER]]:
; P470-NEXT:    ret i32 0
;
entry:
  br label %for.body

for.body:                                         ; preds = %for.inc, %entry
  %indvars.iv3 = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.inc ]
  %arrayidx = getelementptr [421 x i8], ptr %board, i64 0, i64 %indvars.iv3
  %0 = load i8, ptr %arrayidx, align 1
  %cmp2.not = icmp eq i8 %0, 0
  br i1 %cmp2.not, label %for.inc, label %if.else

if.else:                                          ; preds = %for.body
  %conv = zext i8 %0 to i32
  %cmp7 = icmp eq i32 %color, %conv
  br i1 %cmp7, label %land.lhs.true, label %if.else14

land.lhs.true:                                    ; preds = %if.else
  %1 = load i32, ptr %board, align 4
  %tobool.not = icmp eq i32 %1, 0
  br i1 %tobool.not, label %if.else14, label %for.inc.sink.split

if.else14:                                        ; preds = %land.lhs.true, %if.else
  br i1 true, label %land.lhs.true16, label %if.else41

land.lhs.true16:                                  ; preds = %if.else14
  %cmp20 = icmp eq i32 %color, %conv
  br i1 %cmp20, label %land.lhs.true22, label %lor.lhs.false

land.lhs.true22:                                  ; preds = %land.lhs.true16
  %2 = load i32, ptr %board, align 4
  %cmp25 = icmp eq i32 %2, 0
  br i1 %cmp25, label %for.inc.sink.split, label %lor.lhs.false

lor.lhs.false:                                    ; preds = %land.lhs.true22, %land.lhs.true16
  br i1 %cmp7, label %land.lhs.true32, label %if.else41

land.lhs.true32:                                  ; preds = %lor.lhs.false
  %3 = load i32, ptr %board, align 4
  %cmp36 = icmp eq i32 %3, 0
  br i1 %cmp36, label %for.inc.sink.split, label %if.else41

if.else41:                                        ; preds = %land.lhs.true32, %lor.lhs.false, %if.else14
  br label %for.inc.sink.split

for.inc.sink.split:                               ; preds = %if.else41, %land.lhs.true32, %land.lhs.true22, %land.lhs.true
  %.sink = phi i32 [ 1, %if.else41 ], [ 0, %land.lhs.true ], [ 0, %land.lhs.true32 ], [ 0, %land.lhs.true22 ]
  %arrayidx40 = getelementptr [400 x i32], ptr %distance, i64 0, i64 %indvars.iv3
  store i32 %.sink, ptr %arrayidx40, align 4
  br label %for.inc

for.inc:                                          ; preds = %for.inc.sink.split, %for.body
  %indvars.iv.next = add i64 %indvars.iv3, 1
  %exitcond.not = icmp eq i64 %indvars.iv3, 400
  br i1 %exitcond.not, label %do.body.preheader, label %for.body

do.body.preheader:                                ; preds = %for.inc
  ret i32 0
}
