; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=loop-vectorize -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=512 -prefer-predicate-over-epilogue=predicate-dont-vectorize -scalable-vectorization=only -riscv-use-vla-vectorizer -force-vectorization -vector-primary-lmul-min=3 -vector-primary-lmul-max=3 < %s | FileCheck %s

define void @test() {
; CHECK-LABEL: @test(
; CHECK-NEXT:  for.body264.preheader:
; CHECK-NEXT:    br i1 false, label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 1024, i32 8, i1 true)
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 8 x double> [ insertelement (<vscale x 8 x double> splat (double -0.000000e+00), double 0.000000e+00, i32 0), [[VECTOR_PH]] ], [ [[VP_OP_MERGE:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = sub i64 1024, [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[TMP1]], i32 8, i1 true)
; CHECK-NEXT:    [[VP_OP:%.*]] = call reassoc <vscale x 8 x double> @llvm.vp.fmuladd.nxv8f64(<vscale x 8 x double> zeroinitializer, <vscale x 8 x double> zeroinitializer, <vscale x 8 x double> [[VEC_PHI]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP2]])
; CHECK-NEXT:    [[VP_OP_MERGE]] = call <vscale x 8 x double> @llvm.vp.merge.nxv8f64(<vscale x 8 x i1> splat (i1 true), <vscale x 8 x double> [[VP_OP]], <vscale x 8 x double> [[VEC_PHI]], i32 [[TMP2]])
; CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add nuw i64 [[TMP3]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[INDEX_EVL_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP4]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[TMP6:%.*]] = call reassoc double @llvm.vp.reduce.fadd.nxv8f64(double -0.000000e+00, <vscale x 8 x double> [[VP_OP_MERGE]], <vscale x 8 x i1> splat (i1 true), i32 [[TMP0]])
; CHECK-NEXT:    br label [[FOR_END277_LOOPEXIT:%.*]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 0, [[FOR_BODY264_PREHEADER:%.*]] ]
; CHECK-NEXT:    [[BC_MERGE_RDX:%.*]] = phi double [ 0.000000e+00, [[FOR_BODY264_PREHEADER]] ]
; CHECK-NEXT:    br label [[FOR_BODY264:%.*]]
; CHECK:       for.body264:
; CHECK-NEXT:    [[INDVARS_IV914:%.*]] = phi i64 [ [[INDVARS_IV_NEXT915:%.*]], [[FOR_BODY264]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[YE_0849:%.*]] = phi double [ [[TMP7:%.*]], [[FOR_BODY264]] ], [ [[BC_MERGE_RDX]], [[SCALAR_PH]] ]
; CHECK-NEXT:    [[TMP7]] = tail call reassoc double @llvm.fmuladd.f64(double 0.000000e+00, double 0.000000e+00, double [[YE_0849]])
; CHECK-NEXT:    [[INDVARS_IV_NEXT915]] = add nuw nsw i64 [[INDVARS_IV914]], 1
; CHECK-NEXT:    [[EXITCOND918_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT915]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND918_NOT]], label [[FOR_END277_LOOPEXIT]], label [[FOR_BODY264]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       for.end277.loopexit:
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi double [ [[TMP7]], [[FOR_BODY264]] ], [ [[TMP6]], [[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    ret void
;
for.body264.preheader:
  br label %for.body264

for.body264:
  %indvars.iv914 = phi i64 [ %indvars.iv.next915, %for.body264 ], [ 0, %for.body264.preheader ]
  %ye.0849 = phi double [ %0, %for.body264 ], [ 0.000000e+00, %for.body264.preheader ]
  %0 = tail call reassoc double @llvm.fmuladd.f64(double 0.000000e+00, double 0.000000e+00, double %ye.0849)
  %indvars.iv.next915 = add nuw nsw i64 %indvars.iv914, 1
  %exitcond918.not = icmp eq i64 %indvars.iv.next915, 1024
  br i1 %exitcond918.not, label %for.end277.loopexit, label %for.body264

for.end277.loopexit:
  %.lcssa = phi double [ %0, %for.body264 ]
  ret void
}

declare double @llvm.fmuladd.f64(double, double, double)
