; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

define <vscale x 8 x i8> @vp_nxv8f32(<vscale x 8 x float> %x, <vscale x 8 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_nxv8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfncvt.rtz.xu.f.w v8, v8, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call fast <vscale x 8 x float> @llvm.vp.minnum.nxv8f32(<vscale x 8 x float> %x, <vscale x 8 x float> splat (float 2.550000e+02), <vscale x 8 x i1> %mask, i32 %evl)
  %b = call <vscale x 8 x i8> @llvm.vp.fptoui.nxv8i8.nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %mask, i32 %evl)
  ret <vscale x 8 x i8> %b
}

define <3 x i8> @fixed_v3f32(<3 x float> %x) {
; CHECK-LABEL: fixed_v3f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vfncvt.rtz.xu.f.w v8, v8
; CHECK-NEXT:    vsetvli zero, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0
; CHECK-NEXT:    ret
  %a = tail call fast <3 x float> @llvm.minnum.v3f32(<3 x float> %x, <3 x float> <float 2.550000e+02, float 2.550000e+02, float 2.550000e+02>)
  %b = fptoui <3 x float> %a to <3 x i8>
  ret <3 x i8> %b
}
