; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs \
; RUN:   < %s | FileCheck --check-prefix=CHECK-RV64 %s
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs \
; RUN:   < %s | FileCheck --check-prefix=CHECK-RV32 %s

declare i8  @llvm.riscv.vgetvxrm();
declare void @llvm.riscv.vsetvxrm(i8 %roundmode);

define i8 @readvxrm() nounwind
; CHECK-RV64-LABEL: readvxrm:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    csrr a0, vxrm
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: readvxrm:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    csrr a0, vxrm
; CHECK-RV32-NEXT:    ret
{
  %ret = call i8 @llvm.riscv.vgetvxrm()
  ret i8 %ret
}

define void @writevxrm(i8 %roundmode) nounwind
; CHECK-RV64-LABEL: writevxrm:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    csrw vxrm, a0
; CHECK-RV64-NEXT:    ret
;
; CHECK-RV32-LABEL: writevxrm:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    csrw vxrm, a0
; CHECK-RV32-NEXT:    ret
{
  call void @llvm.riscv.vsetvxrm(i8 %roundmode)
  ret void
}
