; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

; Make sure pairs of to.fixed followed by from.fixed are removed.
define void @foo(i8* %x, i8* %y, i8* %z) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %i2 = bitcast i8* %x to <vscale x 8 x i8>*
  %i3 = tail call <vscale x 8 x i8> @llvm.riscv.vle.nxv8i8(<vscale x 8 x i8> undef, <vscale x 8 x i8>* %i2, i64 8)
  %i4 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %i3)
  %i7 = bitcast i8* %y to <vscale x 8 x i8>*
  %i8 = tail call <vscale x 8 x i8> @llvm.riscv.vle.nxv8i8(<vscale x 8 x i8> undef, <vscale x 8 x i8>* %i7, i64 8)
  %i9 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %i8)
  %i11 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %i4)
  %i13 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %i9)
  %i16 = tail call <vscale x 8 x i8> @llvm.riscv.vadd.nxv8i8.nxv8i8(<vscale x 8 x i8> undef, <vscale x 8 x i8> %i11, <vscale x 8 x i8> %i13, i64 8)
  %i17 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %i16)
  %i19 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %i17)
  %i21 = bitcast i8* %z to <vscale x 8 x i8>*
  tail call void @llvm.riscv.vse.nxv8i8(<vscale x 8 x i8> %i19, <vscale x 8 x i8>* %i21, i64 8)
  ret void
}

; Make sure pairs of from.fixed followed by to.fixed are removed.
; The rest of the codegen is bad because the fixed vector operations get
; scalarized. But we just want to make sure there are no extra stack load/stores
; in the middle of the function.
define void @bar(i8* %x, i8* readonly %y, i8* %z) nounwind {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vle8.v v9, (a1)
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  %i2 = bitcast i8* %x to <8 x i8>*
  %i3 = load <8 x i8>, <8 x i8>* %i2
  %i4 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %i3)
  %i7 = bitcast i8* %y to <8 x i8>*
  %i8 = load <8 x i8>, <8 x i8>* %i7
  %i9 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %i8)
  %i11 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %i4)
  %i13 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %i9)
  %i16 = add <8 x i8> %i11, %i13
  %i17 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %i16)
  %i19 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %i17)
  %i21 = bitcast i8* %z to <8 x i8>*
  store <8 x i8> %i19, <8 x i8>* %i21
  ret void
}

declare <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8>)
declare <vscale x 8 x i8> @llvm.riscv.vle.nxv8i8(<vscale x 8 x i8>, <vscale x 8 x i8>*, i64)
declare <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8>)
declare <vscale x 8 x i8> @llvm.riscv.vadd.nxv8i8.nxv8i8(<vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, i64)
declare void @llvm.riscv.vse.nxv8i8(<vscale x 8 x i8>, <vscale x 8 x i8>*, i64)
