; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+xsfvqmaccdod -verify-machineinstrs \
; RUN:   --riscv-no-aliases < %s | FileCheck %s

declare <vscale x 2 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv2i32.nxv8i8.nxv8i8(
  <vscale x 2 x i32>,
  <vscale x 8 x i8>,
  <vscale x 8 x i8>,
  i32, i32);

define <vscale x 2 x i32> @test_0_nxv2i32_nxv8i8_tu(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_0_nxv2i32_nxv8i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @test_0_nxv2i32_nxv8i8_ta(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_0_nxv2i32_nxv8i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv4i32.nxv8i8.nxv16i8(
  <vscale x 4 x i32>,
  <vscale x 8 x i8>,
  <vscale x 16 x i8>,
  i32, i32);

define <vscale x 4 x i32> @test_1_nxv4i32_nxv16i8_tu(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_1_nxv4i32_nxv16i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @test_1_nxv4i32_nxv16i8_ta(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_1_nxv4i32_nxv16i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv8i32.nxv8i8.nxv32i8(
  <vscale x 8 x i32>,
  <vscale x 8 x i8>,
  <vscale x 32 x i8>,
  i32, i32);

define <vscale x 8 x i32> @test_2_nxv8i32_nxv32i8_tu(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_2_nxv8i32_nxv32i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @test_2_nxv8i32_nxv32i8_ta(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_2_nxv8i32_nxv32i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv16i32.nxv8i8.nxv64i8(
  <vscale x 16 x i32>,
  <vscale x 8 x i8>,
  <vscale x 64 x i8>,
  i32, i32);

define <vscale x 16 x i32> @test_3_nxv16i32_nxv64i8_tu(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_3_nxv16i32_nxv64i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, tu, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @test_3_nxv16i32_nxv64i8_ta(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_3_nxv16i32_nxv64i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    sf.vqmaccu.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmaccu.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 16 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv2i32.nxv8i8.nxv8i8(
  <vscale x 2 x i32>,
  <vscale x 8 x i8>,
  <vscale x 8 x i8>,
  i32, i32);

define <vscale x 2 x i32> @test_4_nxv2i32_nxv8i8_tu(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_4_nxv2i32_nxv8i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @test_4_nxv2i32_nxv8i8_ta(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_4_nxv2i32_nxv8i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv4i32.nxv8i8.nxv16i8(
  <vscale x 4 x i32>,
  <vscale x 8 x i8>,
  <vscale x 16 x i8>,
  i32, i32);

define <vscale x 4 x i32> @test_5_nxv4i32_nxv16i8_tu(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_5_nxv4i32_nxv16i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @test_5_nxv4i32_nxv16i8_ta(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_5_nxv4i32_nxv16i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv8i32.nxv8i8.nxv32i8(
  <vscale x 8 x i32>,
  <vscale x 8 x i8>,
  <vscale x 32 x i8>,
  i32, i32);

define <vscale x 8 x i32> @test_6_nxv8i32_nxv32i8_tu(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_6_nxv8i32_nxv32i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @test_6_nxv8i32_nxv32i8_ta(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_6_nxv8i32_nxv32i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv16i32.nxv8i8.nxv64i8(
  <vscale x 16 x i32>,
  <vscale x 8 x i8>,
  <vscale x 64 x i8>,
  i32, i32);

define <vscale x 16 x i32> @test_7_nxv16i32_nxv64i8_tu(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_7_nxv16i32_nxv64i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, tu, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @test_7_nxv16i32_nxv64i8_ta(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_7_nxv16i32_nxv64i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    sf.vqmacc.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmacc.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 16 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv2i32.nxv8i8.nxv8i8(
  <vscale x 2 x i32>,
  <vscale x 8 x i8>,
  <vscale x 8 x i8>,
  i32, i32);

define <vscale x 2 x i32> @test_8_nxv2i32_nxv8i8_tu(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_8_nxv2i32_nxv8i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @test_8_nxv2i32_nxv8i8_ta(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_8_nxv2i32_nxv8i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv4i32.nxv8i8.nxv16i8(
  <vscale x 4 x i32>,
  <vscale x 8 x i8>,
  <vscale x 16 x i8>,
  i32, i32);

define <vscale x 4 x i32> @test_9_nxv4i32_nxv16i8_tu(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_9_nxv4i32_nxv16i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @test_9_nxv4i32_nxv16i8_ta(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_9_nxv4i32_nxv16i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv8i32.nxv8i8.nxv32i8(
  <vscale x 8 x i32>,
  <vscale x 8 x i8>,
  <vscale x 32 x i8>,
  i32, i32);

define <vscale x 8 x i32> @test_10_nxv8i32_nxv32i8_tu(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_10_nxv8i32_nxv32i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @test_10_nxv8i32_nxv32i8_ta(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_10_nxv8i32_nxv32i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv16i32.nxv8i8.nxv64i8(
  <vscale x 16 x i32>,
  <vscale x 8 x i8>,
  <vscale x 64 x i8>,
  i32, i32);

define <vscale x 16 x i32> @test_11_nxv16i32_nxv64i8_tu(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_11_nxv16i32_nxv64i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, tu, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @test_11_nxv16i32_nxv64i8_ta(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_11_nxv16i32_nxv64i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    sf.vqmaccus.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmaccus.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 16 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv2i32.nxv8i8.nxv8i8(
  <vscale x 2 x i32>,
  <vscale x 8 x i8>,
  <vscale x 8 x i8>,
  i32, i32);

define <vscale x 2 x i32> @test_12_nxv2i32_nxv8i8_tu(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_12_nxv2i32_nxv8i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @test_12_nxv2i32_nxv8i8_ta(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_12_nxv2i32_nxv8i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v9, v10
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv2i32.nxv8i8.nxv8i8(
            <vscale x 2 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 8 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv4i32.nxv8i8.nxv16i8(
  <vscale x 4 x i32>,
  <vscale x 8 x i8>,
  <vscale x 16 x i8>,
  i32, i32);

define <vscale x 4 x i32> @test_13_nxv4i32_nxv16i8_tu(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_13_nxv4i32_nxv16i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @test_13_nxv4i32_nxv16i8_ta(<vscale x 4 x i32> %0, <vscale x 8 x i8> %1, <vscale x 16 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_13_nxv4i32_nxv16i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v10, v12
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv4i32.nxv8i8.nxv16i8(
            <vscale x 4 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 16 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv8i32.nxv8i8.nxv32i8(
  <vscale x 8 x i32>,
  <vscale x 8 x i8>,
  <vscale x 32 x i8>,
  i32, i32);

define <vscale x 8 x i32> @test_14_nxv8i32_nxv32i8_tu(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_14_nxv8i32_nxv32i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @test_14_nxv8i32_nxv32i8_ta(<vscale x 8 x i32> %0, <vscale x 8 x i8> %1, <vscale x 32 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_14_nxv8i32_nxv32i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v12, v16
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv8i32.nxv8i8.nxv32i8(
            <vscale x 8 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 32 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv16i32.nxv8i8.nxv64i8(
  <vscale x 16 x i32>,
  <vscale x 8 x i8>,
  <vscale x 64 x i8>,
  i32, i32);

define <vscale x 16 x i32> @test_15_nxv16i32_nxv64i8_tu(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_15_nxv16i32_nxv64i8_tu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, tu, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 0)

  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @test_15_nxv16i32_nxv64i8_ta(<vscale x 16 x i32> %0, <vscale x 8 x i8> %1, <vscale x 64 x i8> %2, i32 %3) nounwind {
; CHECK-LABEL: test_15_nxv16i32_nxv64i8_ta:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re8.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    sf.vqmaccsu.2x8x2 v8, v16, v24
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.sf.vqmaccsu.2x8x2.nxv16i32.nxv8i8.nxv64i8(
            <vscale x 16 x i32> %0,
            <vscale x 8 x i8> %1,
            <vscale x 64 x i8> %2,
            i32 %3, i32 1)

  ret <vscale x 16 x i32> %a
}
