; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs \
; RUN:   < %s | FileCheck --check-prefix=CHECK-RV64 %s

declare i64 @llvm.riscv.vgetvxrm();
declare void @llvm.riscv.vsetvxrm.i64(i64 %roundmode);

define i64 @readvxrm() nounwind
; CHECK-RV64-LABEL: readvxrm:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    csrr a0, vxrm
; CHECK-RV64-NEXT:    ret
{
  %ret = call i64 @llvm.riscv.vgetvxrm()
  ret i64 %ret
}

define void @writevxrm(i64 %roundmode) nounwind
; CHECK-RV64-LABEL: writevxrm:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    csrw vxrm, a0
; CHECK-RV64-NEXT:    ret
{
  call void @llvm.riscv.vsetvxrm.i64(i64 %roundmode)
  ret void
}

define void @writevxrmimm() nounwind
; CHECK-RV64-LABEL: writevxrmimm:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    li a0, 3
; CHECK-RV64-NEXT:    csrw vxrm, a0
; CHECK-RV64-NEXT:    ret
{
  call void @llvm.riscv.vsetvxrm.i64(i64 3)
  ret void
}
