; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+m,+d,+zfh,+zvfh,+v -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s

declare i64 @llvm.riscv.vsetvli.i64(i64, i64, i64)
declare <vscale x 8 x float> @llvm.vp.load.nxv8f32.p0(ptr, <vscale x 8 x i1>, i32)
declare float @llvm.vp.reduce.fadd.nxv8f32(float, <vscale x 8 x float>, <vscale x 8 x i1>, i32)

define float @sum(i32 %n, ptr %arr, float %s) {
; CHECK-LABEL: sum:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sext.w a2, a0
; CHECK-NEXT:    blez a2, .LBB0_4
; CHECK-NEXT:  # %bb.1: # %vector.body.preheader
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli a3, zero, e32, m1, ta, ma
; CHECK-NEXT:    vfmv.s.f v8, fa0
; CHECK-NEXT:  .LBB0_2: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    slli a4, a2, 2
; CHECK-NEXT:    vsetvli a3, a3, e32, m4, ta, ma
; CHECK-NEXT:    add a4, a1, a4
; CHECK-NEXT:    vle32.v v12, (a4)
; CHECK-NEXT:    vfredosum.vs v8, v12, v8
; CHECK-NEXT:    add a2, a2, a3
; CHECK-NEXT:    bne a2, a0, .LBB0_2
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    vfmv.f.s fa0, v8
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    fmv.w.x fa0, zero
; CHECK-NEXT:    ret
entry:
  %cmp4 = icmp sgt i32 %n, 0
  %wide.trip.count = zext i32 %n to i64
  br i1 %cmp4, label %vector.body, label %for.cond.cleanup

vector.body:                                      ; preds = %for.body.preheader, %vector.body
  %index = phi i64 [ %index.next, %vector.body ], [ 0, %entry ]
  %vec.phi = phi float [ %4, %vector.body ], [ %s, %entry ]
  %0 = sub i64 %wide.trip.count, %index
  %1 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %0, i64 2, i64 2)
  %2 = trunc i64 %1 to i32
  %3 = getelementptr inbounds float, ptr %arr, i64 %index
  %vp.op.load = tail call <vscale x 8 x float> @llvm.vp.load.nxv8f32.p0(ptr align 4 %3, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %2)
  %4 = tail call float @llvm.vp.reduce.fadd.nxv8f32(float %vec.phi, <vscale x 8 x float> %vp.op.load, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %2)
  %index.next = add i64 %index, %1
  %5 = icmp eq i64 %index.next, %wide.trip.count
  br i1 %5, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body, %for.body, %entry
  %sum.0.lcssa = phi float [ 0.000000e+00, %entry ], [ %4, %vector.body ]
  ret float %sum.0.lcssa
}

define float @sum2(i32 %n, ptr %arr) {
; CHECK-LABEL: sum2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sext.w a2, a0
; CHECK-NEXT:    blez a2, .LBB1_4
; CHECK-NEXT:  # %bb.1: # %vector.body.preheader
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vsetvli a3, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, zero
; CHECK-NEXT:  .LBB1_2: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    slli a4, a2, 2
; CHECK-NEXT:    vsetvli a3, a3, e32, m4, ta, ma
; CHECK-NEXT:    add a4, a1, a4
; CHECK-NEXT:    vle32.v v12, (a4)
; CHECK-NEXT:    vfredosum.vs v8, v12, v8
; CHECK-NEXT:    add a2, a2, a3
; CHECK-NEXT:    bne a2, a0, .LBB1_2
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    vfmv.f.s fa0, v8
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB1_4:
; CHECK-NEXT:    fmv.w.x fa0, zero
; CHECK-NEXT:    ret
entry:
  %cmp4 = icmp sgt i32 %n, 0
  %wide.trip.count = zext i32 %n to i64
  br i1 %cmp4, label %vector.body, label %for.cond.cleanup

vector.body:                                      ; preds = %for.body.preheader, %vector.body
  %index = phi i64 [ %index.next, %vector.body ], [ 0, %entry ]
  %vec.phi = phi float [ %4, %vector.body ], [ 0.000000e+00, %entry ]
  %0 = sub i64 %wide.trip.count, %index
  %1 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %0, i64 2, i64 2)
  %2 = trunc i64 %1 to i32
  %3 = getelementptr inbounds float, ptr %arr, i64 %index
  %vp.op.load = tail call <vscale x 8 x float> @llvm.vp.load.nxv8f32.p0(ptr align 4 %3, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %2)
  %4 = tail call float @llvm.vp.reduce.fadd.nxv8f32(float %vec.phi, <vscale x 8 x float> %vp.op.load, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %2)
  %index.next = add i64 %index, %1
  %5 = icmp eq i64 %index.next, %wide.trip.count
  br i1 %5, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body, %for.body, %entry
  %sum.0.lcssa = phi float [ 0.000000e+00, %entry ], [ %4, %vector.body ]
  ret float %sum.0.lcssa
}
