; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs \
; RUN:   --riscv-no-aliases < %s | FileCheck %s

define dso_local void @test(i64 %channel, ptr nocapture readonly %output_shift, ptr nocapture readonly %bias_data, ptr nocapture %output_data) local_unnamed_addr {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a5, a0, e8, m1, ta, ma
; CHECK-NEXT:    beq a5, zero, .LBB0_3
; CHECK-NEXT:  # %bb.1: # %while.body.preheader
; CHECK-NEXT:    addi a4, zero, 0
; CHECK-NEXT:  .LBB0_2: # %while.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    slli a6, a4, 2
; CHECK-NEXT:    vsetvli zero, a5, e32, m4, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    sub a0, a0, a5
; CHECK-NEXT:    add a7, a1, a6
; CHECK-NEXT:    vle32.v v12, (a7)
; CHECK-NEXT:    add a4, a5, a4
; CHECK-NEXT:    add a5, a2, a6
; CHECK-NEXT:    vle32.v v16, (a5)
; CHECK-NEXT:    vmslt.vx v0, v12, zero
; CHECK-NEXT:    add a6, a3, a6
; CHECK-NEXT:    vsetvli zero, zero, e32, m4, tu, mu
; CHECK-NEXT:    vrsub.vi v8, v12, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; CHECK-NEXT:    vmerge.vim v12, v12, 0, v0
; CHECK-NEXT:    vsll.vv v12, v16, v12
; CHECK-NEXT:    vssra.vv v8, v12, v8
; CHECK-NEXT:    vse32.v v8, (a6)
; CHECK-NEXT:    vsetvli a5, a0, e8, m1, ta, ma
; CHECK-NEXT:    bne a5, zero, .LBB0_2
; CHECK-NEXT:  .LBB0_3: # %while.end
; CHECK-NEXT:    jalr zero, 0(ra)
entry:
  %0 = call i64 @llvm.riscv.vsetvli.i64(i64 %channel, i64 0, i64 0)
  %tobool.not20 = icmp eq i64 %0, 0
  br i1 %tobool.not20, label %while.end, label %while.body

while.body:                                       ; preds = %entry, %while.body
  %1 = phi i64 [ %14, %while.body ], [ %0, %entry ]
  %channel.addr.022 = phi i64 [ %sub, %while.body ], [ %channel, %entry ]
  %current_channel.021 = phi i64 [ %add, %while.body ], [ 0, %entry ]
  %add.ptr = getelementptr inbounds i32, ptr %output_shift, i64 %current_channel.021
  %2 = call <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.i64(<vscale x 8 x i32> undef, ptr %add.ptr, i64 %1)
  %3 = call <vscale x 8 x i32> @llvm.riscv.vmv.v.x.nxv8i32.i64(<vscale x 8 x i32> undef, i32 0, i64 %1)
  %4 = call <vscale x 8 x i1> @llvm.riscv.vmslt.nxv8i32.i32.i64(<vscale x 8 x i32> %2, i32 0, i64 %1)
  %add.ptr1 = getelementptr inbounds i32, ptr %bias_data, i64 %current_channel.021
  %6 = call <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.i64(<vscale x 8 x i32> undef, ptr %add.ptr1, i64 %1)
  %8 = call <vscale x 8 x i32> @llvm.riscv.vrsub.mask.nxv8i32.i32.i64(<vscale x 8 x i32> %3, <vscale x 8 x i32> %2, i32 0, <vscale x 8 x i1> %4, i64 %1, i64 0)
  %9 = call <vscale x 8 x i32> @llvm.riscv.vmerge.nxv8i32.i32.i64(<vscale x 8 x i32> undef, <vscale x 8 x i32> %2, i32 0, <vscale x 8 x i1> %4, i64 %1)
  %10 = call <vscale x 8 x i32> @llvm.riscv.vmv.v.v.nxv8i32.i64(<vscale x 8 x i32> undef, <vscale x 8 x i32> %6, i64 %1)
  %11 = call <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> undef, <vscale x 8 x i32> %10, <vscale x 8 x i32> %9, i64 %1)
  %12 = call <vscale x 8 x i32> @llvm.riscv.vssra.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> undef, <vscale x 8 x i32> %11, <vscale x 8 x i32> %8, i64 7, i64 %1)
  %add.ptr2 = getelementptr inbounds i32, ptr %output_data, i64 %current_channel.021
  call void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32> %12, ptr %add.ptr2, i64 %1)
  %sub = sub i64 %channel.addr.022, %1
  %add = add i64 %1, %current_channel.021
  %14 = call i64 @llvm.riscv.vsetvli.i64(i64 %sub, i64 0, i64 0)
  %tobool.not = icmp eq i64 %14, 0
  br i1 %tobool.not, label %while.end, label %while.body

while.end:                                        ; preds = %while.body, %entry
  ret void
}

; Function Attrs: nounwind
declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)

; Function Attrs: nofree nounwind readonly
declare <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>* nocapture, i64)

; Function Attrs: nofree nosync nounwind readnone
declare <vscale x 8 x i32> @llvm.riscv.vmv.v.x.nxv8i32.i64(<vscale x 8 x i32>, i32, i64)

; Function Attrs: nofree nosync nounwind readnone
declare <vscale x 8 x i1> @llvm.riscv.vmslt.nxv8i32.i32.i64(<vscale x 8 x i32>, i32, i64)

; Function Attrs: nofree nosync nounwind readnone
declare <vscale x 8 x i32> @llvm.riscv.vrsub.mask.nxv8i32.i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, i32, <vscale x 8 x i1>, i64, i64)

; Function Attrs: nofree nosync nounwind readnone
declare <vscale x 8 x i32> @llvm.riscv.vmerge.nxv8i32.i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, i32, <vscale x 8 x i1>, i64)

; Function Attrs: nofree nosync nounwind readnone
declare <vscale x 8 x i32> @llvm.riscv.vmv.v.v.nxv8i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, i64)

; Function Attrs: nofree nosync nounwind readnone
declare <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.nxv8i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, <vscale x 8 x i32>, i64)

; Function Attrs: nounwind
declare <vscale x 8 x i32> @llvm.riscv.vssra.nxv8i32.nxv8i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, <vscale x 8 x i32>, i64, i64)

; Function Attrs: nounwind writeonly
declare void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32>, <vscale x 8 x i32>* nocapture, i64)
