; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=512 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-512
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=256 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-256

define void @KnownSize(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    add a1, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    li a0, 504
; MIN-512-NEXT:    add a3, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    add a2, a3, a2
; MIN-512-NEXT:    vse8.v v8, (a3)
; MIN-512-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-512-NEXT:    vse8.v v8, (a2)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a1, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a0, 248
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a1, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a1, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a2, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 2040, i1 false)
  ret void
}

define void @KnownSize1(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize1:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 384
; MIN-512-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize1:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a2, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a0, 128
; MIN-256-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 384, i1 false)
  ret void
}

define void @KnownSize2(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize2:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    add a2, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a2)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize2:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a1, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    add a0, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a2, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 1024, i1 false)
  ret void
}

declare void @llvm.memset.p0.i8.i64(ptr noalias nocapture writeonly, i8, i64, i1 immarg)
