; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-x280 -mattr=+v | FileCheck %s -check-prefix=CHECK-X280
; RUN: llc < %s -mtriple=riscv64 -mcpu=sifive-p470 -mattr=+v | FileCheck %s -check-prefix=CHECK-P470

define void @foo(ptr %input) {
; CHECK-X280-LABEL: foo:
; CHECK-X280:       # %bb.0: # %entry
; CHECK-X280-NEXT:    vsetvli a1, zero, e32, m4, ta, ma
; CHECK-X280-NEXT:    vid.v v8
; CHECK-X280-NEXT:    vsll.vi v8, v8, 6
; CHECK-X280-NEXT:    vluxei32.v v12, (a0), v8
; CHECK-X280-NEXT:    vs4r.v v12, (a0)
; CHECK-X280-NEXT:    ret
;
; CHECK-P470-LABEL: foo:
; CHECK-P470:       # %bb.0: # %entry
; CHECK-P470-NEXT:    vsetvli a1, zero, e32, m4, ta, ma
; CHECK-P470-NEXT:    vid.v v8
; CHECK-P470-NEXT:    vsll.vi v8, v8, 6
; CHECK-P470-NEXT:    vluxei32.v v8, (a0), v8
; CHECK-P470-NEXT:    vs4r.v v8, (a0)
; CHECK-P470-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i32> @llvm.riscv.vid.nxv8i32.i64(<vscale x 8 x i32> poison, i64 -1)
  %1 = tail call <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.i64.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> %0, i64 6, i64 -1)
  %2 = tail call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, ptr %input, <vscale x 8 x i32> %1, i64 -1)
  tail call void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32> %2, ptr %input, i64 -1)
  ret void
}

declare <vscale x 8 x i32> @llvm.riscv.vid.nxv8i32.i64(<vscale x 8 x i32>, i64) #1
declare <vscale x 8 x i32> @llvm.riscv.vsll.nxv8i32.i64.i64(<vscale x 8 x i32>, <vscale x 8 x i32>, i64, i64) #1
declare <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i32.i64(<vscale x 8 x i32>, ptr nocapture, <vscale x 8 x i32>, i64) #2
declare void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32>, ptr nocapture, i64) #3
