; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

define i32 @quux(<8 x i32> %arg, <vscale x 8 x i32> %arg1, i32 zeroext %arg2) {
; CHECK-LABEL: quux:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vmv.s.x v10, zero
; CHECK-NEXT:    vredsum.vs v8, v8, v10
; CHECK-NEXT:    vmv.x.s a1, v8
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a1
; CHECK-NEXT:    vredsum.vs v8, v12, v8
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
bb:
  %call = tail call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> %arg)
  %zext = zext i32 %arg2 to i64
  %call3 = call <vscale x 8 x i32> @llvm.riscv.vmv.s.x.nxv8i32.i64(<vscale x 8 x i32> poison, i32 %call, i64 %zext)
  %call4 = call <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv8i32(<vscale x 8 x i32> %call3, i64 0)
  %call5 = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv8i32.i64(<vscale x 2 x i32> poison, <vscale x 8 x i32> %arg1, <vscale x 2 x i32> %call4, i64 %zext)
  %extractelement = extractelement <vscale x 2 x i32> %call5, i64 0
  ret i32 %extractelement
}

declare <vscale x 8 x i32> @llvm.riscv.vmv.s.x.nxv8i32.i64(<vscale x 8 x i32>, i32, i64) #0
declare <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv8i32.i64(<vscale x 2 x i32>, <vscale x 8 x i32>, <vscale x 2 x i32>, i64) #0
declare <vscale x 2 x i32> @llvm.vector.extract.nxv2i32.nxv8i32(<vscale x 8 x i32>, i64 immarg) #1
declare i32 @llvm.vector.reduce.add.v8i32(<8 x i32>) #1
