; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -mattr=+xsfvfhbfmin -verify-machineinstrs \
; RUN:   < %s | FileCheck %s

define void @store_bf16mf4(<vscale x 1 x bfloat> %value, <vscale x 1 x bfloat>* %dest) {
; CHECK-LABEL: store_bf16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a1, zero, e16, mf4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  store <vscale x 1 x bfloat> %value, <vscale x 1 x bfloat>* %dest, align 2
  ret void
}

define <vscale x 1 x bfloat> @load_bf16mf4(<vscale x 1 x bfloat>* %src) {
; CHECK-LABEL: load_bf16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a1, zero, e16, mf4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = load <vscale x 1 x bfloat>, <vscale x 1 x bfloat>* %src, align 2
  ret <vscale x 1 x bfloat> %0
}

define void @store_bf16mf2(<vscale x 2 x bfloat> %value, <vscale x 2 x bfloat>* %dest) {
; CHECK-LABEL: store_bf16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a1, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  store <vscale x 2 x bfloat> %value, <vscale x 2 x bfloat>* %dest, align 2
  ret void
}

define <vscale x 2 x bfloat> @load_bf16mf2(<vscale x 2 x bfloat>* %src) {
; CHECK-LABEL: load_bf16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a1, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = load <vscale x 2 x bfloat>, <vscale x 2 x bfloat>* %src, align 2
  ret <vscale x 2 x bfloat> %0
}

define void @store_bf16m1(<vscale x 4 x bfloat> %value, <vscale x 4 x bfloat>* %dest) {
; CHECK-LABEL: store_bf16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vs1r.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  store <vscale x 4 x bfloat> %value, <vscale x 4 x bfloat>* %dest, align 2
  ret void
}

define <vscale x 4 x bfloat> @load_bf16m1(<vscale x 4 x bfloat>* %src) {
; CHECK-LABEL: load_bf16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl1re16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = load <vscale x 4 x bfloat>, <vscale x 4 x bfloat>* %src, align 2
  ret <vscale x 4 x bfloat> %0
}

define void @store_bf16m2(<vscale x 8 x bfloat> %value, <vscale x 8 x bfloat>* %dest) {
; CHECK-LABEL: store_bf16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vs2r.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  store <vscale x 8 x bfloat> %value, <vscale x 8 x bfloat>* %dest, align 2
  ret void
}

define <vscale x 8 x bfloat> @load_bf16m2(<vscale x 8 x bfloat>* %src) {
; CHECK-LABEL: load_bf16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl2re16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = load <vscale x 8 x bfloat>, <vscale x 8 x bfloat>* %src, align 2
  ret <vscale x 8 x bfloat> %0
}

define void @store_bf16m4(<vscale x 16 x bfloat> %value, <vscale x 16 x bfloat>* %dest) {
; CHECK-LABEL: store_bf16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vs4r.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  store <vscale x 16 x bfloat> %value, <vscale x 16 x bfloat>* %dest, align 2
  ret void
}

define <vscale x 16 x bfloat> @load_bf16m4(<vscale x 16 x bfloat>* %src) {
; CHECK-LABEL: load_bf16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl4re16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = load <vscale x 16 x bfloat>, <vscale x 16 x bfloat>* %src, align 2
  ret <vscale x 16 x bfloat> %0
}

define void @store_bf16m8(<vscale x 32 x bfloat> %value, <vscale x 32 x bfloat>* %dest) {
; CHECK-LABEL: store_bf16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vs8r.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  store <vscale x 32 x bfloat> %value, <vscale x 32 x bfloat>* %dest, align 2
  ret void
}

define <vscale x 32 x bfloat> @load_bf16m8(<vscale x 32 x bfloat>* %src) {
; CHECK-LABEL: load_bf16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl8re16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = load <vscale x 32 x bfloat>, <vscale x 32 x bfloat>* %src, align 2
  ret <vscale x 32 x bfloat> %0
}
