; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-min-memcpy-size=64 -O3 \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=RV32-MIN-64
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-min-memcpy-size=64 -O3 \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=RV64-MIN-64
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-min-memcpy-size=56 -O3 \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK-MIN-56,RV32-MIN-56
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-min-memcpy-size=56 -O3 \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK-MIN-56,RV64-MIN-56

define void @KnownSize1(ptr nocapture readonly %src, ptr nocapture %dst) {
; RV32-MIN-64-LABEL: KnownSize1:
; RV32-MIN-64:       # %bb.0: # %entry
; RV32-MIN-64-NEXT:    addi sp, sp, -16
; RV32-MIN-64-NEXT:    .cfi_def_cfa_offset 16
; RV32-MIN-64-NEXT:    li a2, 32
; RV32-MIN-64-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; RV32-MIN-64-NEXT:    vle8.v v8, (a0)
; RV32-MIN-64-NEXT:    addi a2, a0, 32
; RV32-MIN-64-NEXT:    vse8.v v8, (a1)
; RV32-MIN-64-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; RV32-MIN-64-NEXT:    vle8.v v8, (a2)
; RV32-MIN-64-NEXT:    addi a2, a1, 32
; RV32-MIN-64-NEXT:    vse8.v v8, (a2)
; RV32-MIN-64-NEXT:    lbu a2, 53(a0)
; RV32-MIN-64-NEXT:    lbu a3, 52(a0)
; RV32-MIN-64-NEXT:    lbu a4, 54(a0)
; RV32-MIN-64-NEXT:    lbu a5, 55(a0)
; RV32-MIN-64-NEXT:    slli a2, a2, 8
; RV32-MIN-64-NEXT:    or a2, a2, a3
; RV32-MIN-64-NEXT:    slli a4, a4, 16
; RV32-MIN-64-NEXT:    slli a5, a5, 24
; RV32-MIN-64-NEXT:    or a4, a5, a4
; RV32-MIN-64-NEXT:    or a2, a4, a2
; RV32-MIN-64-NEXT:    sw a2, 4(sp)
; RV32-MIN-64-NEXT:    lbu a2, 49(a0)
; RV32-MIN-64-NEXT:    lbu a3, 50(a0)
; RV32-MIN-64-NEXT:    lbu a4, 51(a0)
; RV32-MIN-64-NEXT:    lbu a0, 48(a0)
; RV32-MIN-64-NEXT:    slli a2, a2, 8
; RV32-MIN-64-NEXT:    slli a3, a3, 16
; RV32-MIN-64-NEXT:    slli a4, a4, 24
; RV32-MIN-64-NEXT:    or a0, a2, a0
; RV32-MIN-64-NEXT:    or a3, a4, a3
; RV32-MIN-64-NEXT:    or a0, a3, a0
; RV32-MIN-64-NEXT:    sw a0, 0(sp)
; RV32-MIN-64-NEXT:    fld fa5, 0(sp)
; RV32-MIN-64-NEXT:    fsd fa5, 8(sp)
; RV32-MIN-64-NEXT:    lw a0, 12(sp)
; RV32-MIN-64-NEXT:    sb a0, 52(a1)
; RV32-MIN-64-NEXT:    srli a2, a0, 24
; RV32-MIN-64-NEXT:    srli a3, a0, 16
; RV32-MIN-64-NEXT:    srli a0, a0, 8
; RV32-MIN-64-NEXT:    lw a4, 8(sp)
; RV32-MIN-64-NEXT:    sb a0, 53(a1)
; RV32-MIN-64-NEXT:    sb a3, 54(a1)
; RV32-MIN-64-NEXT:    sb a2, 55(a1)
; RV32-MIN-64-NEXT:    srli a0, a4, 24
; RV32-MIN-64-NEXT:    srli a2, a4, 16
; RV32-MIN-64-NEXT:    srli a3, a4, 8
; RV32-MIN-64-NEXT:    sb a4, 48(a1)
; RV32-MIN-64-NEXT:    sb a3, 49(a1)
; RV32-MIN-64-NEXT:    sb a2, 50(a1)
; RV32-MIN-64-NEXT:    sb a0, 51(a1)
; RV32-MIN-64-NEXT:    addi sp, sp, 16
; RV32-MIN-64-NEXT:    .cfi_def_cfa_offset 0
; RV32-MIN-64-NEXT:    ret
;
; RV64-MIN-64-LABEL: KnownSize1:
; RV64-MIN-64:       # %bb.0: # %entry
; RV64-MIN-64-NEXT:    li a2, 32
; RV64-MIN-64-NEXT:    vsetvli zero, a2, e8, m2, ta, ma
; RV64-MIN-64-NEXT:    vle8.v v8, (a0)
; RV64-MIN-64-NEXT:    vse8.v v8, (a1)
; RV64-MIN-64-NEXT:    lbu a2, 55(a0)
; RV64-MIN-64-NEXT:    sb a2, 55(a1)
; RV64-MIN-64-NEXT:    lbu a2, 54(a0)
; RV64-MIN-64-NEXT:    sb a2, 54(a1)
; RV64-MIN-64-NEXT:    lbu a2, 53(a0)
; RV64-MIN-64-NEXT:    sb a2, 53(a1)
; RV64-MIN-64-NEXT:    lbu a2, 52(a0)
; RV64-MIN-64-NEXT:    sb a2, 52(a1)
; RV64-MIN-64-NEXT:    lbu a2, 51(a0)
; RV64-MIN-64-NEXT:    sb a2, 51(a1)
; RV64-MIN-64-NEXT:    lbu a2, 50(a0)
; RV64-MIN-64-NEXT:    sb a2, 50(a1)
; RV64-MIN-64-NEXT:    lbu a2, 49(a0)
; RV64-MIN-64-NEXT:    sb a2, 49(a1)
; RV64-MIN-64-NEXT:    lbu a2, 48(a0)
; RV64-MIN-64-NEXT:    sb a2, 48(a1)
; RV64-MIN-64-NEXT:    addi a0, a0, 32
; RV64-MIN-64-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; RV64-MIN-64-NEXT:    vle8.v v8, (a0)
; RV64-MIN-64-NEXT:    addi a0, a1, 32
; RV64-MIN-64-NEXT:    vse8.v v8, (a0)
; RV64-MIN-64-NEXT:    ret
;
; CHECK-MIN-56-LABEL: KnownSize1:
; CHECK-MIN-56:       # %bb.0: # %entry
; CHECK-MIN-56-NEXT:    li a2, 56
; CHECK-MIN-56-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; CHECK-MIN-56-NEXT:    vle8.v v8, (a0)
; CHECK-MIN-56-NEXT:    vse8.v v8, (a1)
; CHECK-MIN-56-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0.p0.iXLen(ptr align 1 %dst, ptr align 1 %src, iXLen 56, i1 false)
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32-MIN-56: {{.*}}
; RV64-MIN-56: {{.*}}
