; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

declare <vscale x 4 x i1> @llvm.vp.icmp.nxv4i16(<vscale x 4 x i16>, <vscale x 4 x i16>, metadata, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i16> @llvm.vp.sext.nxv4i16.nxv4i1(<vscale x 4 x i1>, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i16> @llvm.vp.select.nxv4i16(<vscale x 4 x i1>, <vscale x 4 x i16>, <vscale x 4 x i16>, i32)
declare <vscale x 4 x i8> @llvm.vp.trunc.nxv4i8.nxv4i16(<vscale x 4 x i16>, <vscale x 4 x i1>, i32)

define <vscale x 4 x i8> @test_nxv4i16_nxv4i8(<vscale x 4 x i16> %x, <vscale x 4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_nxv4i16_nxv4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i16(<vscale x 4 x i16> %x, <vscale x 4 x i16> zeroinitializer, metadata !"sgt", <vscale x 4 x i1> %m, i32 %evl)
  %b = call <vscale x 4 x i16> @llvm.vp.sext.nxv4i16.nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %m, i32 %evl)
  %c = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i16(<vscale x 4 x i16> %x, <vscale x 4 x i16> splat (i16 256), metadata !"ult", <vscale x 4 x i1> %m, i32 %evl)
  %d = call <vscale x 4 x i16> @llvm.vp.select.nxv4i16(<vscale x 4 x i1> %c, <vscale x 4 x i16> %x, <vscale x 4 x i16> %b, i32 %evl)
  %e = call <vscale x 4 x i8> @llvm.vp.trunc.nxv4i8.nxv4i16(<vscale x 4 x i16> %d, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x i8> %e
}

declare <vscale x 4 x i1> @llvm.vp.icmp.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, metadata, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i32> @llvm.vp.sext.nxv4i32.nxv4i1(<vscale x 4 x i1>, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i32> @llvm.vp.select.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 4 x i8> @llvm.vp.trunc.nxv4i8.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i1>, i32)

define <vscale x 4 x i8> @test_nxv4i32_nxv4i8(<vscale x 4 x i32> %x, <vscale x 4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_nxv4i32_nxv4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i32(<vscale x 4 x i32> %x, <vscale x 4 x i32> zeroinitializer, metadata !"sgt", <vscale x 4 x i1> %m, i32 %evl)
  %b = call <vscale x 4 x i32> @llvm.vp.sext.nxv4i32.nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %m, i32 %evl)
  %c = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i32(<vscale x 4 x i32> %x, <vscale x 4 x i32> splat (i32 256), metadata !"ult", <vscale x 4 x i1> %m, i32 %evl)
  %d = call <vscale x 4 x i32> @llvm.vp.select.nxv4i32(<vscale x 4 x i1> %c, <vscale x 4 x i32> %x, <vscale x 4 x i32> %b, i32 %evl)
  %e = call <vscale x 4 x i8> @llvm.vp.trunc.nxv4i8.nxv4i32(<vscale x 4 x i32> %d, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x i8> %e
}

declare <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, metadata, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i64> @llvm.vp.sext.nxv4i64.nxv4i1(<vscale x 4 x i1>, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i64> @llvm.vp.select.nxv4i64(<vscale x 4 x i1>, <vscale x 4 x i64>, <vscale x 4 x i64>, i32)
declare <vscale x 4 x i8> @llvm.vp.trunc.nxv4i8.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i1>, i32)

define <vscale x 4 x i8> @test_nxv4i64_nxv4i8(<vscale x 4 x i64> %x, <vscale x 4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_nxv4i64_nxv4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> zeroinitializer, metadata !"sgt", <vscale x 4 x i1> %m, i32 %evl)
  %b = call <vscale x 4 x i64> @llvm.vp.sext.nxv4i64.nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %m, i32 %evl)
  %c = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> splat (i64 256), metadata !"ult", <vscale x 4 x i1> %m, i32 %evl)
  %d = call <vscale x 4 x i64> @llvm.vp.select.nxv4i64(<vscale x 4 x i1> %c, <vscale x 4 x i64> %x, <vscale x 4 x i64> %b, i32 %evl)
  %e = call <vscale x 4 x i8> @llvm.vp.trunc.nxv4i8.nxv4i64(<vscale x 4 x i64> %d, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x i8> %e
}

declare <vscale x 4 x i16> @llvm.vp.trunc.nxv4i16.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i1>, i32)

define <vscale x 4 x i16> @test_nxv4i32_nxv4i16(<vscale x 4 x i32> %x, <vscale x 4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_nxv4i32_nxv4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i32(<vscale x 4 x i32> %x, <vscale x 4 x i32> zeroinitializer, metadata !"sgt", <vscale x 4 x i1> %m, i32 %evl)
  %b = call <vscale x 4 x i32> @llvm.vp.sext.nxv4i32.nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %m, i32 %evl)
  %c = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i32(<vscale x 4 x i32> %x, <vscale x 4 x i32> splat (i32 65536), metadata !"ult", <vscale x 4 x i1> %m, i32 %evl)
  %d = call <vscale x 4 x i32> @llvm.vp.select.nxv4i32(<vscale x 4 x i1> %c, <vscale x 4 x i32> %x, <vscale x 4 x i32> %b, i32 %evl)
  %e = call <vscale x 4 x i16> @llvm.vp.trunc.nxv4i16.nxv4i32(<vscale x 4 x i32> %d, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x i16> %e
}

declare <vscale x 4 x i16> @llvm.vp.trunc.nxv4i16.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i1>, i32)

define <vscale x 4 x i16> @test_nxv4i64_nxv4i16(<vscale x 4 x i64> %x, <vscale x 4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_nxv4i64_nxv4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> zeroinitializer, metadata !"sgt", <vscale x 4 x i1> %m, i32 %evl)
  %b = call <vscale x 4 x i64> @llvm.vp.sext.nxv4i64.nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %m, i32 %evl)
  %c = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> splat (i64 65536), metadata !"ult", <vscale x 4 x i1> %m, i32 %evl)
  %d = call <vscale x 4 x i64> @llvm.vp.select.nxv4i64(<vscale x 4 x i1> %c, <vscale x 4 x i64> %x, <vscale x 4 x i64> %b, i32 %evl)
  %e = call <vscale x 4 x i16> @llvm.vp.trunc.nxv4i16.nxv4i64(<vscale x 4 x i64> %d, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x i16> %e
}

declare <vscale x 4 x i32> @llvm.vp.trunc.nxv4i32.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i1>, i32)

define <vscale x 4 x i32> @test_nxv4i64_nxv4i32(<vscale x 4 x i64> %x, <vscale x 4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_nxv4i64_nxv4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; CHECK-NEXT:    vnclipu.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> zeroinitializer, metadata !"sgt", <vscale x 4 x i1> %m, i32 %evl)
  %b = call <vscale x 4 x i64> @llvm.vp.sext.nxv4i64.nxv4i1(<vscale x 4 x i1> %a, <vscale x 4 x i1> %m, i32 %evl)
  %c = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> splat (i64 4294967296), metadata !"ult", <vscale x 4 x i1> %m, i32 %evl)
  %d = call <vscale x 4 x i64> @llvm.vp.select.nxv4i64(<vscale x 4 x i1> %c, <vscale x 4 x i64> %x, <vscale x 4 x i64> %b, i32 %evl)
  %e = call <vscale x 4 x i32> @llvm.vp.trunc.nxv4i32.nxv4i64(<vscale x 4 x i64> %d, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x i32> %e
}

declare <4 x i1> @llvm.vp.icmp.v4i16(<4 x i16>, <4 x i16>, metadata, <4 x i1>, i32)
declare <4 x i16> @llvm.vp.sext.v4i16.v4i1(<4 x i1>, <4 x i1>, i32)
declare <4 x i16> @llvm.vp.select.v4i16(<4 x i1>, <4 x i16>, <4 x i16>, i32)
declare <4 x i8> @llvm.vp.trunc.v4i8.v4i16(<4 x i16>, <4 x i1>, i32)

; FIXME: We fail to use vnclip because the VL for the 256 splat doesn't match.
define <4 x i8> @test_v4i16_v4i8(<4 x i16> %x, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_v4i16_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    vmin.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <4 x i1> @llvm.vp.icmp.v4i16(<4 x i16> %x, <4 x i16> zeroinitializer, metadata !"sgt", <4 x i1> %m, i32 %evl)
  %b = call <4 x i16> @llvm.vp.sext.v4i16.v4i1(<4 x i1> %a, <4 x i1> %m, i32 %evl)
  %c = call <4 x i1> @llvm.vp.icmp.v4i16(<4 x i16> %x, <4 x i16> splat (i16 256), metadata !"ult", <4 x i1> %m, i32 %evl)
  %d = call <4 x i16> @llvm.vp.select.v4i16(<4 x i1> %c, <4 x i16> %x, <4 x i16> %b, i32 %evl)
  %e = call <4 x i8> @llvm.vp.trunc.v4i8.v4i16(<4 x i16> %d, <4 x i1> %m, i32 %evl)
  ret <4 x i8> %e
}

declare <4 x i1> @llvm.vp.icmp.v4i32(<4 x i32>, <4 x i32>, metadata, <4 x i1>, i32)
declare <4 x i32> @llvm.vp.sext.v4i32.v4i1(<4 x i1>, <4 x i1>, i32)
declare <4 x i32> @llvm.vp.select.v4i32(<4 x i1>, <4 x i32>, <4 x i32>, i32)
declare <4 x i8> @llvm.vp.trunc.v4i8.v4i32(<4 x i32>, <4 x i1>, i32)

define <4 x i8> @test_v4i32_v4i8(<4 x i32> %x, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_v4i32_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    vmin.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <4 x i1> @llvm.vp.icmp.v4i32(<4 x i32> %x, <4 x i32> zeroinitializer, metadata !"sgt", <4 x i1> %m, i32 %evl)
  %b = call <4 x i32> @llvm.vp.sext.v4i32.v4i1(<4 x i1> %a, <4 x i1> %m, i32 %evl)
  %c = call <4 x i1> @llvm.vp.icmp.v4i32(<4 x i32> %x, <4 x i32> splat (i32 256), metadata !"ult", <4 x i1> %m, i32 %evl)
  %d = call <4 x i32> @llvm.vp.select.v4i32(<4 x i1> %c, <4 x i32> %x, <4 x i32> %b, i32 %evl)
  %e = call <4 x i8> @llvm.vp.trunc.v4i8.v4i32(<4 x i32> %d, <4 x i1> %m, i32 %evl)
  ret <4 x i8> %e
}

declare <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64>, <4 x i64>, metadata, <4 x i1>, i32)
declare <4 x i64> @llvm.vp.sext.v4i64.v4i1(<4 x i1>, <4 x i1>, i32)
declare <4 x i64> @llvm.vp.select.v4i64(<4 x i1>, <4 x i64>, <4 x i64>, i32)
declare <4 x i8> @llvm.vp.trunc.v4i8.v4i64(<4 x i64>, <4 x i1>, i32)

define <4 x i8> @test_v4i64_v4i8(<4 x i64> %x, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_v4i64_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    li a0, 255
; CHECK-NEXT:    vmin.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64> %x, <4 x i64> zeroinitializer, metadata !"sgt", <4 x i1> %m, i32 %evl)
  %b = call <4 x i64> @llvm.vp.sext.v4i64.v4i1(<4 x i1> %a, <4 x i1> %m, i32 %evl)
  %c = call <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64> %x, <4 x i64> splat (i64 256), metadata !"ult", <4 x i1> %m, i32 %evl)
  %d = call <4 x i64> @llvm.vp.select.v4i64(<4 x i1> %c, <4 x i64> %x, <4 x i64> %b, i32 %evl)
  %e = call <4 x i8> @llvm.vp.trunc.v4i8.v4i64(<4 x i64> %d, <4 x i1> %m, i32 %evl)
  ret <4 x i8> %e
}

declare <4 x i16> @llvm.vp.trunc.v4i16.v4i32(<4 x i32>, <4 x i1>, i32)

define <4 x i16> @test_v4i32_v4i16(<4 x i32> %x, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_v4i32_v4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    lui a0, 16
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    vmin.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <4 x i1> @llvm.vp.icmp.v4i32(<4 x i32> %x, <4 x i32> zeroinitializer, metadata !"sgt", <4 x i1> %m, i32 %evl)
  %b = call <4 x i32> @llvm.vp.sext.v4i32.v4i1(<4 x i1> %a, <4 x i1> %m, i32 %evl)
  %c = call <4 x i1> @llvm.vp.icmp.v4i32(<4 x i32> %x, <4 x i32> splat (i32 65536), metadata !"ult", <4 x i1> %m, i32 %evl)
  %d = call <4 x i32> @llvm.vp.select.v4i32(<4 x i1> %c, <4 x i32> %x, <4 x i32> %b, i32 %evl)
  %e = call <4 x i16> @llvm.vp.trunc.v4i16.v4i32(<4 x i32> %d, <4 x i1> %m, i32 %evl)
  ret <4 x i16> %e
}

declare <4 x i16> @llvm.vp.trunc.v4i16.v4i64(<4 x i64>, <4 x i1>, i32)

define <4 x i16> @test_v4i64_v4i16(<4 x i64> %x, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_v4i64_v4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    lui a0, 16
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    vmin.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64> %x, <4 x i64> zeroinitializer, metadata !"sgt", <4 x i1> %m, i32 %evl)
  %b = call <4 x i64> @llvm.vp.sext.v4i64.v4i1(<4 x i1> %a, <4 x i1> %m, i32 %evl)
  %c = call <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64> %x, <4 x i64> splat (i64 65536), metadata !"ult", <4 x i1> %m, i32 %evl)
  %d = call <4 x i64> @llvm.vp.select.v4i64(<4 x i1> %c, <4 x i64> %x, <4 x i64> %b, i32 %evl)
  %e = call <4 x i16> @llvm.vp.trunc.v4i16.v4i64(<4 x i64> %d, <4 x i1> %m, i32 %evl)
  ret <4 x i16> %e
}

declare <4 x i32> @llvm.vp.trunc.v4i32.v4i64(<4 x i64>, <4 x i1>, i32)

define <4 x i32> @test_v4i64_v4i32(<4 x i64> %x, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_v4i64_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vmax.vx v8, v8, zero, v0.t
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    vmin.vx v8, v8, a0, v0.t
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 0, v0.t
; CHECK-NEXT:    ret
  %a = call <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64> %x, <4 x i64> zeroinitializer, metadata !"sgt", <4 x i1> %m, i32 %evl)
  %b = call <4 x i64> @llvm.vp.sext.v4i64.v4i1(<4 x i1> %a, <4 x i1> %m, i32 %evl)
  %c = call <4 x i1> @llvm.vp.icmp.v4i64(<4 x i64> %x, <4 x i64> splat (i64 4294967296), metadata !"ult", <4 x i1> %m, i32 %evl)
  %d = call <4 x i64> @llvm.vp.select.v4i64(<4 x i1> %c, <4 x i64> %x, <4 x i64> %b, i32 %evl)
  %e = call <4 x i32> @llvm.vp.trunc.v4i32.v4i64(<4 x i64> %d, <4 x i1> %m, i32 %evl)
  ret <4 x i32> %e
}
