; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O0 \
; RUN:    < %s | FileCheck --check-prefix=CHECK-O0 %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:    < %s | FileCheck --check-prefix=CHECK-O2 %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:   -riscv-force-tail-undisturbed < %s | FileCheck --check-prefix=FORCE-TU %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:   -riscv-force-mask-undisturbed < %s | FileCheck --check-prefix=FORCE-MU %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:   -riscv-force-tail-undisturbed -riscv-force-mask-undisturbed < %s | \
; RUN:   FileCheck --check-prefix=FORCE-TUMU %s

@scratch = global i8 0, align 16

declare i64 @llvm.riscv.vsetvli(i64, i64, i64)

declare <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64.i64(
  <vscale x 1 x double>,
  <vscale x 1 x double>,
  <vscale x 1 x double>,
  i64, i64)

declare <vscale x 1 x double> @llvm.riscv.vle.mask.nxv1f64.i64(
  <vscale x 1 x double>,
  ptr,
  <vscale x 1 x i1>,
  i64,
  i64)

declare void @llvm.riscv.vse.nxv1f64.i64(
  <vscale x 1 x double>,
  ptr,
  i64)

define void @test_vsetvl_avl(<vscale x 1 x double> %value, ptr %v, <vscale x 1 x i1> %mask, i64 signext %avl) nounwind {
; CHECK-O0-LABEL: test_vsetvl_avl:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    addi sp, sp, -16
; CHECK-O0-NEXT:    csrr a2, vlenb
; CHECK-O0-NEXT:    sub sp, sp, a2
; CHECK-O0-NEXT:    addi a2, sp, 16
; CHECK-O0-NEXT:    vs1r.v v0, (a2) # Unknown-size Folded Spill
; CHECK-O0-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-O0-NEXT:    vmv1r.v v9, v8
; CHECK-O0-NEXT:    vsetvli a1, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    addi a2, sp, 16
; CHECK-O0-NEXT:    vl1r.v v0, (a2) # Unknown-size Folded Reload
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; CHECK-O0-NEXT:    vle64.v v9, (a0), v0.t
; CHECK-O0-NEXT:    # implicit-def: $v8
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vfadd.vv v8, v9, v9
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    csrr a0, vlenb
; CHECK-O0-NEXT:    add sp, sp, a0
; CHECK-O0-NEXT:    addi sp, sp, 16
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_vsetvl_avl:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; CHECK-O2-NEXT:    vle64.v v8, (a0), v0.t
; CHECK-O2-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vse64.v v8, (a0)
; CHECK-O2-NEXT:    ret
;
; FORCE-TU-LABEL: test_vsetvl_avl:
; FORCE-TU:       # %bb.0:
; FORCE-TU-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; FORCE-TU-NEXT:    vle64.v v8, (a0), v0.t
; FORCE-TU-NEXT:    vfadd.vv v8, v8, v8
; FORCE-TU-NEXT:    lui a0, %hi(scratch)
; FORCE-TU-NEXT:    addi a0, a0, %lo(scratch)
; FORCE-TU-NEXT:    vse64.v v8, (a0)
; FORCE-TU-NEXT:    ret
;
; FORCE-MU-LABEL: test_vsetvl_avl:
; FORCE-MU:       # %bb.0:
; FORCE-MU-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; FORCE-MU-NEXT:    vle64.v v8, (a0), v0.t
; FORCE-MU-NEXT:    vsetvli zero, zero, e64, m1, ta, mu
; FORCE-MU-NEXT:    vfadd.vv v8, v8, v8
; FORCE-MU-NEXT:    lui a0, %hi(scratch)
; FORCE-MU-NEXT:    addi a0, a0, %lo(scratch)
; FORCE-MU-NEXT:    vse64.v v8, (a0)
; FORCE-MU-NEXT:    ret
;
; FORCE-TUMU-LABEL: test_vsetvl_avl:
; FORCE-TUMU:       # %bb.0:
; FORCE-TUMU-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; FORCE-TUMU-NEXT:    vle64.v v8, (a0), v0.t
; FORCE-TUMU-NEXT:    vfadd.vv v8, v8, v8
; FORCE-TUMU-NEXT:    lui a0, %hi(scratch)
; FORCE-TUMU-NEXT:    addi a0, a0, %lo(scratch)
; FORCE-TUMU-NEXT:    vse64.v v8, (a0)
; FORCE-TUMU-NEXT:    ret
  %gvl = call i64 @llvm.riscv.vsetvli(
    i64 %avl, i64 3, i64 0)

  %vec = call <vscale x 1 x double> @llvm.riscv.vle.mask.nxv1f64.i64(
    <vscale x 1 x double> %value,
    ptr %v,
    <vscale x 1 x i1> %mask,
    i64 %gvl,
    i64 0)

  %add = call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64.i64(
    <vscale x 1 x double> undef,
    <vscale x 1 x double> %vec,
    <vscale x 1 x double> %vec,
    i64 7, i64 %gvl)

  call void @llvm.riscv.vse.nxv1f64.i64(
    <vscale x 1 x double> %add,
    ptr @scratch,
    i64 %gvl)

  ret void
}
