; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+d,+zfh,+zvfh,+v,+m -target-abi=ilp32 \
; RUN:     -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+d,+zfh,+zvfh,+v,+m -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1>, <vscale x 1 x i64>, <vscale x 1 x i64>, i32)
declare <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1>, <vscale x 1 x double>, <vscale x 1 x double>, i32)
declare <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1>, <vscale x 1 x i64>, <vscale x 1 x i64>, i32)
declare <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1>, <vscale x 1 x double>, <vscale x 1 x double>, i32)

declare <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_add(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_add_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_add_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.mul.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_mul(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_mul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.mul.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_mul_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_mul_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.mul.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_or(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_or:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_or_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_or_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_xor(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_xor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vxor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_xor_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_xor_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vxor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.and.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_and(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vand.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.and.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_and_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_and_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vand.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.and.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.umax.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_umax(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_umax:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmaxu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umax.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_umax_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_umax_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmaxu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umax.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.umin.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_umin(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_umin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vminu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umin.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_umin_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_umin_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vminu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umin.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.smax.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_smax(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_smax:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -9223372036854775808, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smax.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_smax_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_smax_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -9223372036854775808, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smax.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.smin.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_smin(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_smin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 9223372036854775807, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smin.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_smin_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_smin_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 9223372036854775807, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smin.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.sub.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_sub(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_sub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vsub.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.sub.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.shl.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_shl(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_shl:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vsll.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.shl.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.lshr.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_lshr(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_lshr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vsrl.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.lshr.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x i64> @llvm.vp.ashr.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)
define <vscale x 1 x i64> @test_ashr(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_ashr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vsra.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.ashr.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

declare <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x i1>, i32)
define <vscale x 1 x double> @test_fadd(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double -0.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_fadd_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_fadd_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double -0.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

declare <vscale x 1 x double> @llvm.vp.fmul.nxv1f64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x i1>, i32)
define <vscale x 1 x double> @test_fmul(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_fmul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 1.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fmul.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_fmul_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_fmul_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 1.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fmul.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

declare <vscale x 1 x double> @llvm.vp.minnum.nxv1f64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x i1>, i32)
define <vscale x 1 x double> @test_minnum(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_minnum:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0x7FF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.minnum.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_minnum_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_minnum_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0x7FF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.minnum.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

declare <vscale x 1 x double> @llvm.vp.maxnum.nxv1f64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x i1>, i32)
define <vscale x 1 x double> @test_maxnum(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_maxnum:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0xFFF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.maxnum.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_maxnum_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_maxnum_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0xFFF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.maxnum.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

declare <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x i1>, i32)
define <vscale x 1 x double> @test_fsub(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_fsub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, mu
; CHECK-NEXT:    vfsub.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.merge.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x i64> @test_select_add(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_add_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_add_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_mul(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_mul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.mul.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_mul_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_mul_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.mul.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_or(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_or:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_or_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_or_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_xor(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_xor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vxor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_xor_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_xor_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vxor.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_and(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vand.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.and.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_and_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_and_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vand.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.and.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_umax(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_umax:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmaxu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umax.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_umax_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_umax_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmaxu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umax.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_umin(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_umin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vminu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umin.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_umin_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_umin_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vminu.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -1, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.umin.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_smax(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_smax:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -9223372036854775808, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smax.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_smax_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_smax_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 -9223372036854775808, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smax.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_smin(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_smin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 9223372036854775807, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smin.nxv1i64(<vscale x 1 x i64> %x, <vscale x 1 x i64> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_smin_commute(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_smin_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 9223372036854775807, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.smin.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_sub(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_sub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vsub.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.sub.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_shl(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_shl:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vsll.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.shl.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_lshr(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_lshr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vsrl.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.lshr.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x i64> @test_select_ashr(<vscale x 1 x i64> %a, <vscale x 1 x i64> %b, <vscale x 1 x i64> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_ashr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vsra.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x i64> poison, i64 0, i32 0
  %ident = shufflevector <vscale x 1 x i64> %splat, <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x i64> @llvm.vp.select.nxv1i64(<vscale x 1 x i1> %m, <vscale x 1 x i64> %b, <vscale x 1 x i64> %ident, i32 %evl)
  %y = call <vscale x 1 x i64> @llvm.vp.ashr.nxv1i64(<vscale x 1 x i64> %a, <vscale x 1 x i64> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x i64> %y
}

define <vscale x 1 x double> @test_select_fadd(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double -0.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_fadd_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_fadd_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfadd.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double -0.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fadd.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_fmul(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_fmul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 1.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fmul.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_fmul_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_fmul_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 1.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fmul.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_minnum(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_minnum:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0x7FF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.minnum.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_minnum_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_minnum_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfmin.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0x7FF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.minnum.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_maxnum(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_maxnum:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0xFFF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.maxnum.nxv1f64(<vscale x 1 x double> %x, <vscale x 1 x double> %a, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_maxnum_commute(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_maxnum_commute:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfmax.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0xFFF8000000000000, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.maxnum.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}

define <vscale x 1 x double> @test_select_fsub(<vscale x 1 x double> %a, <vscale x 1 x double> %b, <vscale x 1 x double> %c,  <vscale x 1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: test_select_fsub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vfsub.vv v8, v8, v9, v0.t
; CHECK-NEXT:    ret
  %splat = insertelement <vscale x 1 x double> poison, double 0.0, i32 0
  %ident = shufflevector <vscale x 1 x double> %splat, <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
  %x = call <vscale x 1 x double> @llvm.vp.select.nxv1f64(<vscale x 1 x i1> %m, <vscale x 1 x double> %b, <vscale x 1 x double> %ident, i32 %evl)
  %y = call <vscale x 1 x double> @llvm.vp.fsub.nxv1f64(<vscale x 1 x double> %a, <vscale x 1 x double> %x, <vscale x 1 x i1> %m, i32 %evl)
  ret <vscale x 1 x double> %y
}
