; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O0 \
; RUN:    < %s | FileCheck --check-prefix=CHECK-O0 %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:    < %s | FileCheck --check-prefix=CHECK-O2 %s

@scratch = global i8 0, align 16

declare i64 @llvm.riscv.vsetvli(
  i64, i64, i64);

declare i64 @llvm.riscv.vsetvlimax(
  i64, i64);

declare <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64(
  <vscale x 1 x double>,
  <vscale x 1 x double>,
  <vscale x 1 x double>,
  i64, i64);

declare <vscale x 1 x double> @llvm.riscv.vle.nxv1f64(
  <vscale x 1 x double>,
  ptr,
  i64);

declare void @llvm.riscv.vse.nxv1f64(
  <vscale x 1 x double>,
  ptr,
  i64);

define void @test_vsetvl_avl(ptr %v, i64 signext %avl) nounwind
;
; CHECK-O0-LABEL: test_vsetvl_avl:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    vsetvli a1, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    # implicit-def: $v9
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vle64.v v9, (a0)
; CHECK-O0-NEXT:    # implicit-def: $v8
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vfadd.vv v8, v9, v9
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_vsetvl_avl:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-O2-NEXT:    vle64.v v8, (a0)
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vse64.v v8, (a0)
; CHECK-O2-NEXT:    ret
{
  %gvl = call i64 @llvm.riscv.vsetvli(
    i64 %avl, i64 3, i64 0)

  %vec = call <vscale x 1 x double> @llvm.riscv.vle.nxv1f64(
    <vscale x 1 x double> undef,
    ptr %v,
    i64 %gvl)

  %add = call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef,
    <vscale x 1 x double> %vec,
    <vscale x 1 x double> %vec,
    i64 7, i64 %gvl)

  call void @llvm.riscv.vse.nxv1f64(
    <vscale x 1 x double> %add,
    ptr @scratch,
    i64 %gvl)

    ret void
}

define void @test_vsetvl_zero(ptr %v) nounwind
;
; CHECK-O0-LABEL: test_vsetvl_zero:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    vsetivli a1, 0, e64, m1, ta, ma
; CHECK-O0-NEXT:    # implicit-def: $v9
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vle64.v v9, (a0)
; CHECK-O0-NEXT:    # implicit-def: $v8
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vfadd.vv v8, v9, v9
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_vsetvl_zero:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-O2-NEXT:    vle64.v v8, (a0)
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vse64.v v8, (a0)
; CHECK-O2-NEXT:    ret
{
  %gvl = call i64 @llvm.riscv.vsetvli(
    i64 0, i64 3, i64 0)

  %vec = call <vscale x 1 x double> @llvm.riscv.vle.nxv1f64(
    <vscale x 1 x double> undef,
    ptr %v,
    i64 %gvl)

  %add = call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef,
    <vscale x 1 x double> %vec,
    <vscale x 1 x double> %vec,
    i64 7, i64 %gvl)

  call void @llvm.riscv.vse.nxv1f64(
    <vscale x 1 x double> %add,
    ptr @scratch,
    i64 %gvl)

    ret void
}

define void @test_vsetvlmax(ptr %v) nounwind
;
; CHECK-O0-LABEL: test_vsetvlmax:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    vsetvli a1, zero, e64, m1, ta, ma
; CHECK-O0-NEXT:    # implicit-def: $v9
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vle64.v v9, (a0)
; CHECK-O0-NEXT:    # implicit-def: $v8
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-O0-NEXT:    vfadd.vv v8, v9, v9
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_vsetvlmax:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vsetvli a1, zero, e64, m1, ta, ma
; CHECK-O2-NEXT:    vle64.v v8, (a0)
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vse64.v v8, (a0)
; CHECK-O2-NEXT:    ret
{
  %vlmax = call i64 @llvm.riscv.vsetvlimax(
    i64 3, i64 0)

  %vec = call <vscale x 1 x double> @llvm.riscv.vle.nxv1f64(
    <vscale x 1 x double> undef,
    ptr %v,
    i64 %vlmax)

  %add = call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef,
    <vscale x 1 x double> %vec,
    <vscale x 1 x double> %vec,
    i64 7, i64 %vlmax)

  call void @llvm.riscv.vse.nxv1f64(
    <vscale x 1 x double> %add,
    ptr @scratch,
    i64 %vlmax)

    ret void
}

define void @test_gvl_zero(ptr %v) nounwind
;
; CHECK-O0-LABEL: test_gvl_zero:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    # implicit-def: $v9
; CHECK-O0-NEXT:    vsetivli zero, 0, e64, m1, tu, ma
; CHECK-O0-NEXT:    vle64.v v9, (a0)
; CHECK-O0-NEXT:    # implicit-def: $v8
; CHECK-O0-NEXT:    vfadd.vv v8, v9, v9
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_gvl_zero:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-O2-NEXT:    vle64.v v8, (a0)
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vse64.v v8, (a0)
; CHECK-O2-NEXT:    ret
{
  %vec = call <vscale x 1 x double> @llvm.riscv.vle.nxv1f64(
    <vscale x 1 x double> undef,
    ptr %v,
    i64 0)

  %add = call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef,
    <vscale x 1 x double> %vec,
    <vscale x 1 x double> %vec,
    i64 7, i64 0)

  call void @llvm.riscv.vse.nxv1f64(
    <vscale x 1 x double> %add,
    ptr @scratch,
    i64 0)

    ret void
}

define void @test_implicit_vlmax(ptr %v) nounwind
;
; CHECK-O0-LABEL: test_implicit_vlmax:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    # implicit-def: $v9
; CHECK-O0-NEXT:    vsetvli a1, zero, e64, m1, ta, ma
; CHECK-O0-NEXT:    vle64.v v9, (a0)
; CHECK-O0-NEXT:    # implicit-def: $v8
; CHECK-O0-NEXT:    vfadd.vv v8, v9, v9
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_implicit_vlmax:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vl1re64.v v8, (a0)
; CHECK-O2-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vs1r.v v8, (a0)
; CHECK-O2-NEXT:    ret
{
  %vec = load <vscale x 1 x double>, ptr %v

  %add = fadd <vscale x 1 x double> %vec, %vec

  store <vscale x 1 x double> %add, ptr @scratch

  ret void
}
