; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=512 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-512
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=256 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-256

define void @KnownSize(ptr nocapture readonly %src, ptr nocapture %dst) {
; MIN-512-LABEL: KnownSize:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    sub a2, a1, a0
; MIN-512-NEXT:    li a3, 2040
; MIN-512-NEXT:    bgeu a2, a3, .LBB0_2
; MIN-512-NEXT:  # %bb.1: # %backward-pre-loop
; MIN-512-NEXT:    addi a2, a0, 2040
; MIN-512-NEXT:    addi a0, a1, 2040
; MIN-512-NEXT:    li a1, 512
; MIN-512-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    vle8.v v8, (a2)
; MIN-512-NEXT:    sub a0, a0, a1
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    vle8.v v8, (a2)
; MIN-512-NEXT:    sub a0, a0, a1
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    vle8.v v8, (a2)
; MIN-512-NEXT:    sub a0, a0, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    li a1, 504
; MIN-512-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    vle8.v v8, (a2)
; MIN-512-NEXT:    sub a0, a0, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    ret
; MIN-512-NEXT:  .LBB0_2: # %memmove-forward-loop
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    li a3, 504
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    sub a2, a1, a0
; MIN-256-NEXT:    li a3, 2040
; MIN-256-NEXT:    bgeu a2, a3, .LBB0_2
; MIN-256-NEXT:  # %bb.1: # %backward-pre-loop
; MIN-256-NEXT:    addi a2, a0, 2040
; MIN-256-NEXT:    addi a0, a1, 2040
; MIN-256-NEXT:    li a1, 256
; MIN-256-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a1, 248
; MIN-256-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    ret
; MIN-256-NEXT:  .LBB0_2: # %memmove-forward-loop
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    li a3, 248
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i32 2040, i1 false)
  ret void
}

define void @KnownSize2(ptr nocapture readonly %src, ptr nocapture %dst) {
; MIN-512-LABEL: KnownSize2:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 384
; MIN-512-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize2:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    sub a2, a1, a0
; MIN-256-NEXT:    li a3, 384
; MIN-256-NEXT:    bgeu a2, a3, .LBB1_2
; MIN-256-NEXT:  # %bb.1: # %backward-pre-loop
; MIN-256-NEXT:    addi a2, a0, 384
; MIN-256-NEXT:    addi a0, a1, 384
; MIN-256-NEXT:    li a1, 256
; MIN-256-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a1, 128
; MIN-256-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    ret
; MIN-256-NEXT:  .LBB1_2: # %memmove-forward-loop
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    li a3, 128
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i32 384, i1 false)
  ret void
}

define void @KnownSize3(ptr nocapture readonly %src, ptr nocapture %dst) {
; MIN-512-LABEL: KnownSize3:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    sub a2, a1, a0
; MIN-512-NEXT:    li a3, 1024
; MIN-512-NEXT:    bgeu a2, a3, .LBB2_2
; MIN-512-NEXT:  # %bb.1: # %backward-pre-loop
; MIN-512-NEXT:    addi a2, a0, 1024
; MIN-512-NEXT:    addi a0, a1, 1024
; MIN-512-NEXT:    li a1, 512
; MIN-512-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    vle8.v v8, (a2)
; MIN-512-NEXT:    sub a0, a0, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    vle8.v v8, (a2)
; MIN-512-NEXT:    sub a0, a0, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    ret
; MIN-512-NEXT:  .LBB2_2: # %memmove-forward-loop
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize3:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    sub a2, a1, a0
; MIN-256-NEXT:    li a3, 1024
; MIN-256-NEXT:    bgeu a2, a3, .LBB2_2
; MIN-256-NEXT:  # %bb.1: # %backward-pre-loop
; MIN-256-NEXT:    addi a2, a0, 1024
; MIN-256-NEXT:    addi a0, a1, 1024
; MIN-256-NEXT:    li a1, 256
; MIN-256-NEXT:    vsetvli a1, a1, e8, m8, ta, ma
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    vle8.v v8, (a2)
; MIN-256-NEXT:    sub a0, a0, a1
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    ret
; MIN-256-NEXT:  .LBB2_2: # %memmove-forward-loop
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i32 1024, i1 false)
  ret void
}

declare void @llvm.memmove.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg)
