; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN:  llc -mtriple=riscv64 -mattr=+f,+d,+v,+zfh,+xsfvcp \
; RUN:    -verify-machineinstrs < %s | FileCheck %s

define void @test_sf_vc_x_se_e64m1(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_x_se_e64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    sf.vc.x 3, 31, 31, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.x.se.e64m1.i32.i64.i64(i32 3, i32 31, i32 31, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.x.se.e64m1.i32.i64.i64(i32, i32, i32, i64, i64)

define void @test_sf_vc_x_se_e64m2(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_x_se_e64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    sf.vc.x 3, 31, 31, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.x.se.e64m2.i32.i64.i64(i32 3, i32 31, i32 31, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.x.se.e64m2.i32.i64.i64(i32, i32, i32, i64, i64)

define void @test_sf_vc_x_se_e64m4(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_x_se_e64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    sf.vc.x 3, 31, 31, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.x.se.e64m4.i32.i64.i64(i32 3, i32 31, i32 31, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.x.se.e64m4.i32.i64.i64(i32, i32, i32, i64, i64)

define void @test_sf_vc_x_se_e64m8(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_x_se_e64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; CHECK-NEXT:    sf.vc.x 3, 31, 31, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.x.se.e64m8.i32.i64.i64(i32 3, i32 31, i32 31, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.x.se.e64m8.i32.i64.i64(i32, i32, i32, i64, i64)

define <vscale x 1 x i64> @test_sf_vc_v_x_se_e64m1(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_se_e64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 1 x i64> @llvm.riscv.sf.vc.v.x.se.nxv1i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 1 x i64> %0
}

declare <vscale x 1 x i64> @llvm.riscv.sf.vc.v.x.se.nxv1i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 2 x i64> @test_sf_vc_v_x_se_e64m2(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_se_e64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 2 x i64> @llvm.riscv.sf.vc.v.x.se.nxv2i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 2 x i64> %0
}

declare <vscale x 2 x i64> @llvm.riscv.sf.vc.v.x.se.nxv2i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 4 x i64> @test_sf_vc_v_x_se_e64m4(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_se_e64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x i64> @llvm.riscv.sf.vc.v.x.se.nxv4i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 4 x i64> %0
}

declare <vscale x 4 x i64> @llvm.riscv.sf.vc.v.x.se.nxv4i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 8 x i64> @test_sf_vc_v_x_se_e64m8(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_se_e64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i64> @llvm.riscv.sf.vc.v.x.se.nxv8i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 8 x i64> %0
}

declare <vscale x 8 x i64> @llvm.riscv.sf.vc.v.x.se.nxv8i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 1 x i64> @test_sf_vc_v_x_e64m1(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_e64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 1 x i64> @llvm.riscv.sf.vc.v.x.nxv1i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 1 x i64> %0
}

declare <vscale x 1 x i64> @llvm.riscv.sf.vc.v.x.nxv1i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 2 x i64> @test_sf_vc_v_x_e64m2(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_e64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 2 x i64> @llvm.riscv.sf.vc.v.x.nxv2i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 2 x i64> %0
}

declare <vscale x 2 x i64> @llvm.riscv.sf.vc.v.x.nxv2i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 4 x i64> @test_sf_vc_v_x_e64m4(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_e64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x i64> @llvm.riscv.sf.vc.v.x.nxv4i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 4 x i64> %0
}

declare <vscale x 4 x i64> @llvm.riscv.sf.vc.v.x.nxv4i64.i32.i64.i64(i32, i32, i64, i64)

define <vscale x 8 x i64> @test_sf_vc_v_x_e64m8(i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_x_e64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; CHECK-NEXT:    sf.vc.v.x 3, 31, v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i64> @llvm.riscv.sf.vc.v.x.nxv8i64.i32.i64.i64(i32 3, i32 31, i64 %rs1, i64 %vl)
  ret <vscale x 8 x i64> %0
}

declare <vscale x 8 x i64> @llvm.riscv.sf.vc.v.x.nxv8i64.i32.i64.i64(i32, i32, i64, i64)
