; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -target-abi=ilp32d -mattr=+v,+zfh,+zvfh,+f,+d | FileCheck %s -check-prefix=RV32
; RUN: llc < %s -mtriple=riscv64 -target-abi=lp64d -mattr=+v,+zfh,+zvfh,+f,+d | FileCheck %s -check-prefix=RV64

declare <vscale x 2 x half> @llvm.sqrt.nxv2f16(<vscale x 2 x half>) #0
declare <vscale x 4 x half> @llvm.sqrt.nxv4f16(<vscale x 4 x half>) #0
declare <vscale x 8 x half> @llvm.sqrt.nxv8f16(<vscale x 8 x half>) #0
declare <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float>) #0
declare <vscale x 4 x float> @llvm.sqrt.nxv4f32(<vscale x 4 x float>) #0
declare <vscale x 8 x float> @llvm.sqrt.nxv8f32(<vscale x 8 x float>) #0
declare <vscale x 2 x double> @llvm.sqrt.nxv2f64(<vscale x 2 x double>) #0
declare <vscale x 4 x double> @llvm.sqrt.nxv4f64(<vscale x 4 x double>) #0
declare <vscale x 8 x double> @llvm.sqrt.nxv8f64(<vscale x 8 x double>) #0

define <vscale x 2 x half> @sqrt_nxv2f16(<vscale x 2 x half> %a) #0 {
; RV32-LABEL: sqrt_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, %hi(.LCPI0_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI0_1)
; RV32-NEXT:    vfabs.v v10, v8
; RV32-NEXT:    vfmv.v.f v11, fa5
; RV32-NEXT:    flh fa5, %lo(.LCPI0_1)(a0)
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vfmacc.vv v11, v8, v9
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v11
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, %hi(.LCPI0_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI0_1)
; RV64-NEXT:    vfabs.v v10, v8
; RV64-NEXT:    vfmv.v.f v11, fa5
; RV64-NEXT:    flh fa5, %lo(.LCPI0_1)(a0)
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vfmacc.vv v11, v8, v9
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v11
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x half> @llvm.sqrt.nxv2f16(<vscale x 2 x half> %a)
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @sqrt_nxv4f16(<vscale x 4 x half> %a) #0 {
; RV32-LABEL: sqrt_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, %hi(.LCPI1_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI1_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI1_1)
; RV32-NEXT:    vfabs.v v10, v8
; RV32-NEXT:    vfmv.v.f v11, fa5
; RV32-NEXT:    flh fa5, %lo(.LCPI1_1)(a0)
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vfmacc.vv v11, v8, v9
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v11
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, %hi(.LCPI1_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI1_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI1_1)
; RV64-NEXT:    vfabs.v v10, v8
; RV64-NEXT:    vfmv.v.f v11, fa5
; RV64-NEXT:    flh fa5, %lo(.LCPI1_1)(a0)
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vfmacc.vv v11, v8, v9
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v11
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x half> @llvm.sqrt.nxv4f16(<vscale x 4 x half> %a)
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @sqrt_nxv8f16(<vscale x 8 x half> %a) #0 {
; RV32-LABEL: sqrt_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI2_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI2_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI2_1)
; RV32-NEXT:    vfabs.v v12, v8
; RV32-NEXT:    vfmv.v.f v14, fa5
; RV32-NEXT:    flh fa5, %lo(.LCPI2_1)(a0)
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vfmacc.vv v14, v8, v10
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v12, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v14
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI2_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI2_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI2_1)
; RV64-NEXT:    vfabs.v v12, v8
; RV64-NEXT:    vfmv.v.f v14, fa5
; RV64-NEXT:    flh fa5, %lo(.LCPI2_1)(a0)
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vfmacc.vv v14, v8, v10
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v12, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v14
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x half> @llvm.sqrt.nxv8f16(<vscale x 8 x half> %a)
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x float> @sqrt_nxv2f32(<vscale x 2 x float> %a) #0 {
; RV32-LABEL: sqrt_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v10, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v11, v8, v9
; RV32-NEXT:    vfmadd.vv v11, v9, v10
; RV32-NEXT:    vfmul.vf v9, v9, fa5
; RV32-NEXT:    vfmul.vv v9, v9, v11
; RV32-NEXT:    vfabs.v v11, v8
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vfmadd.vv v9, v8, v10
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v11, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v10, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v11, v8, v9
; RV64-NEXT:    vfmadd.vv v11, v9, v10
; RV64-NEXT:    vfmul.vf v9, v9, fa5
; RV64-NEXT:    vfmul.vv v9, v9, v11
; RV64-NEXT:    vfabs.v v11, v8
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vfmadd.vv v9, v8, v10
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v11, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a)
  ret <vscale x 2 x float> %1
}

define <vscale x 4 x float> @sqrt_nxv4f32(<vscale x 4 x float> %a) #0 {
; RV32-LABEL: sqrt_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v12, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmadd.vv v14, v10, v12
; RV32-NEXT:    vfmul.vf v10, v10, fa5
; RV32-NEXT:    vfmul.vv v10, v10, v14
; RV32-NEXT:    vfabs.v v14, v8
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vfmadd.vv v10, v8, v12
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v14, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v12, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmadd.vv v14, v10, v12
; RV64-NEXT:    vfmul.vf v10, v10, fa5
; RV64-NEXT:    vfmul.vv v10, v10, v14
; RV64-NEXT:    vfabs.v v14, v8
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vfmadd.vv v10, v8, v12
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v14, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x float> @llvm.sqrt.nxv4f32(<vscale x 4 x float> %a)
  ret <vscale x 4 x float> %1
}

define <vscale x 8 x float> @sqrt_nxv8f32(<vscale x 8 x float> %a) #0 {
; RV32-LABEL: sqrt_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v12, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v20, v8, v16
; RV32-NEXT:    vfmadd.vv v20, v16, v12
; RV32-NEXT:    vfmul.vf v16, v16, fa5
; RV32-NEXT:    vfmul.vv v16, v16, v20
; RV32-NEXT:    vfabs.v v20, v8
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    vfmul.vv v8, v8, v16
; RV32-NEXT:    vfmadd.vv v16, v8, v12
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v20, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v16
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v12, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v20, v8, v16
; RV64-NEXT:    vfmadd.vv v20, v16, v12
; RV64-NEXT:    vfmul.vf v16, v16, fa5
; RV64-NEXT:    vfmul.vv v16, v16, v20
; RV64-NEXT:    vfabs.v v20, v8
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    vfmul.vv v8, v8, v16
; RV64-NEXT:    vfmadd.vv v16, v8, v12
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v20, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v16
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x float> @llvm.sqrt.nxv8f32(<vscale x 8 x float> %a)
  ret <vscale x 8 x float> %1
}

define <vscale x 2 x double> @sqrt_nxv2f64(<vscale x 2 x double> %a) #0 {
; RV32-LABEL: sqrt_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI6_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI6_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI6_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI6_1)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI6_2)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    fld fa5, %lo(.LCPI6_2)(a0)
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmul.vf v16, v10, fa4
; RV32-NEXT:    vfmadd.vv v14, v10, v12
; RV32-NEXT:    vfmul.vv v10, v16, v14
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmul.vf v16, v10, fa4
; RV32-NEXT:    vfmadd.vv v14, v10, v12
; RV32-NEXT:    vfmul.vv v10, v16, v14
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmul.vf v16, v14, fa4
; RV32-NEXT:    vfmadd.vv v10, v14, v12
; RV32-NEXT:    vfabs.v v8, v8
; RV32-NEXT:    vmflt.vf v0, v8, fa5
; RV32-NEXT:    vfmul.vv v8, v16, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI6_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI6_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI6_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI6_1)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI6_2)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    fld fa5, %lo(.LCPI6_2)(a0)
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmul.vf v16, v10, fa4
; RV64-NEXT:    vfmadd.vv v14, v10, v12
; RV64-NEXT:    vfmul.vv v10, v16, v14
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmul.vf v16, v10, fa4
; RV64-NEXT:    vfmadd.vv v14, v10, v12
; RV64-NEXT:    vfmul.vv v10, v16, v14
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmul.vf v16, v14, fa4
; RV64-NEXT:    vfmadd.vv v10, v14, v12
; RV64-NEXT:    vfabs.v v8, v8
; RV64-NEXT:    vmflt.vf v0, v8, fa5
; RV64-NEXT:    vfmul.vv v8, v16, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x double> @llvm.sqrt.nxv2f64(<vscale x 2 x double> %a)
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @sqrt_nvx4f64(<vscale x 4 x double> %a) #0 {
; RV32-LABEL: sqrt_nvx4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, %hi(.LCPI7_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI7_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI7_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI7_1)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI7_2)
; RV32-NEXT:    vfmv.v.f v16, fa5
; RV32-NEXT:    fld fa5, %lo(.LCPI7_2)(a0)
; RV32-NEXT:    vfmul.vv v20, v8, v12
; RV32-NEXT:    vfmul.vf v24, v12, fa4
; RV32-NEXT:    vfmadd.vv v20, v12, v16
; RV32-NEXT:    vfmul.vv v12, v24, v20
; RV32-NEXT:    vfmul.vv v20, v8, v12
; RV32-NEXT:    vfmul.vf v24, v12, fa4
; RV32-NEXT:    vfmadd.vv v20, v12, v16
; RV32-NEXT:    vfmul.vv v12, v24, v20
; RV32-NEXT:    vfmul.vv v20, v8, v12
; RV32-NEXT:    vfmul.vf v24, v20, fa4
; RV32-NEXT:    vfmadd.vv v12, v20, v16
; RV32-NEXT:    vfabs.v v8, v8
; RV32-NEXT:    vmflt.vf v0, v8, fa5
; RV32-NEXT:    vfmul.vv v8, v24, v12
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nvx4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, %hi(.LCPI7_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI7_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI7_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI7_1)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI7_2)
; RV64-NEXT:    vfmv.v.f v16, fa5
; RV64-NEXT:    fld fa5, %lo(.LCPI7_2)(a0)
; RV64-NEXT:    vfmul.vv v20, v8, v12
; RV64-NEXT:    vfmul.vf v24, v12, fa4
; RV64-NEXT:    vfmadd.vv v20, v12, v16
; RV64-NEXT:    vfmul.vv v12, v24, v20
; RV64-NEXT:    vfmul.vv v20, v8, v12
; RV64-NEXT:    vfmul.vf v24, v12, fa4
; RV64-NEXT:    vfmadd.vv v20, v12, v16
; RV64-NEXT:    vfmul.vv v12, v24, v20
; RV64-NEXT:    vfmul.vv v20, v8, v12
; RV64-NEXT:    vfmul.vf v24, v20, fa4
; RV64-NEXT:    vfmadd.vv v12, v20, v16
; RV64-NEXT:    vfabs.v v8, v8
; RV64-NEXT:    vmflt.vf v0, v8, fa5
; RV64-NEXT:    vfmul.vv v8, v24, v12
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x double> @llvm.sqrt.nxv4f64(<vscale x 4 x double> %a)
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @sqrt_nvx8f64(<vscale x 8 x double> %a) #0 {
; RV32-LABEL: sqrt_nvx8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, %hi(.LCPI8_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI8_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI8_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI8_1)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI8_2)
; RV32-NEXT:    vfmv.v.f v24, fa5
; RV32-NEXT:    fld fa5, %lo(.LCPI8_2)(a0)
; RV32-NEXT:    vfmul.vv v0, v8, v16
; RV32-NEXT:    vfmadd.vv v0, v16, v24
; RV32-NEXT:    vfmul.vf v16, v16, fa4
; RV32-NEXT:    vfmul.vv v16, v16, v0
; RV32-NEXT:    vfmul.vv v0, v8, v16
; RV32-NEXT:    vfmadd.vv v0, v16, v24
; RV32-NEXT:    vfmul.vf v16, v16, fa4
; RV32-NEXT:    vfmul.vv v16, v16, v0
; RV32-NEXT:    vfmul.vv v0, v8, v16
; RV32-NEXT:    vfmadd.vv v16, v0, v24
; RV32-NEXT:    vfmul.vf v24, v0, fa4
; RV32-NEXT:    vfabs.v v8, v8
; RV32-NEXT:    vmflt.vf v0, v8, fa5
; RV32-NEXT:    vfmul.vv v8, v24, v16
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nvx8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, %hi(.LCPI8_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI8_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI8_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI8_1)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI8_2)
; RV64-NEXT:    vfmv.v.f v24, fa5
; RV64-NEXT:    fld fa5, %lo(.LCPI8_2)(a0)
; RV64-NEXT:    vfmul.vv v0, v8, v16
; RV64-NEXT:    vfmadd.vv v0, v16, v24
; RV64-NEXT:    vfmul.vf v16, v16, fa4
; RV64-NEXT:    vfmul.vv v16, v16, v0
; RV64-NEXT:    vfmul.vv v0, v8, v16
; RV64-NEXT:    vfmadd.vv v0, v16, v24
; RV64-NEXT:    vfmul.vf v16, v16, fa4
; RV64-NEXT:    vfmul.vv v16, v16, v0
; RV64-NEXT:    vfmul.vv v0, v8, v16
; RV64-NEXT:    vfmadd.vv v16, v0, v24
; RV64-NEXT:    vfmul.vf v24, v0, fa4
; RV64-NEXT:    vfabs.v v8, v8
; RV64-NEXT:    vmflt.vf v0, v8, fa5
; RV64-NEXT:    vfmul.vv v8, v24, v16
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x double> @llvm.sqrt.nxv8f64(<vscale x 8 x double> %a)
  ret <vscale x 8 x double> %1
}

define <vscale x 2 x half> @rsqrt_nxv2f16(<vscale x 2 x half> %a) #0 {
; RV32-LABEL: rsqrt_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, %hi(.LCPI9_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI9_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI9_1)
; RV32-NEXT:    flh fa4, %lo(.LCPI9_1)(a0)
; RV32-NEXT:    vfmv.v.f v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vfmacc.vv v10, v9, v8
; RV32-NEXT:    vfmul.vf v8, v9, fa4
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, %hi(.LCPI9_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI9_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI9_1)
; RV64-NEXT:    flh fa4, %lo(.LCPI9_1)(a0)
; RV64-NEXT:    vfmv.v.f v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vfmacc.vv v10, v9, v8
; RV64-NEXT:    vfmul.vf v8, v9, fa4
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x half> @llvm.sqrt.nxv2f16(<vscale x 2 x half> %a)
  %2 = fdiv fast <vscale x 2 x half> %splat, %1
  ret <vscale x 2 x half> %2
}

define <vscale x 4 x half> @rsqrt_nxv4f16(<vscale x 4 x half> %a) #0 {
; RV32-LABEL: rsqrt_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, %hi(.LCPI10_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI10_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI10_1)
; RV32-NEXT:    flh fa4, %lo(.LCPI10_1)(a0)
; RV32-NEXT:    vfmv.v.f v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vfmacc.vv v10, v9, v8
; RV32-NEXT:    vfmul.vf v8, v9, fa4
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, %hi(.LCPI10_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI10_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI10_1)
; RV64-NEXT:    flh fa4, %lo(.LCPI10_1)(a0)
; RV64-NEXT:    vfmv.v.f v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vfmacc.vv v10, v9, v8
; RV64-NEXT:    vfmul.vf v8, v9, fa4
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x half> @llvm.sqrt.nxv4f16(<vscale x 4 x half> %a)
  %2 = fdiv fast <vscale x 4 x half> %splat, %1
  ret <vscale x 4 x half> %2
}

define <vscale x 8 x half> @rsqrt_nxv8f16(<vscale x 8 x half> %a) #0 {
; RV32-LABEL: rsqrt_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI11_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI11_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI11_1)
; RV32-NEXT:    flh fa4, %lo(.LCPI11_1)(a0)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vfmacc.vv v12, v10, v8
; RV32-NEXT:    vfmul.vf v8, v10, fa4
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI11_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI11_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI11_1)
; RV64-NEXT:    flh fa4, %lo(.LCPI11_1)(a0)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vfmacc.vv v12, v10, v8
; RV64-NEXT:    vfmul.vf v8, v10, fa4
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x half> @llvm.sqrt.nxv8f16(<vscale x 8 x half> %a)
  %2 = fdiv fast <vscale x 8 x half> %splat, %1
  ret <vscale x 8 x half> %2
}

define <vscale x 2 x float> @rsqrt_nxv2f32(<vscale x 2 x float> %a) #0 {
; RV32-LABEL: rsqrt_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v10, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v11, v8, v9
; RV32-NEXT:    vfmadd.vv v11, v9, v10
; RV32-NEXT:    vfmul.vf v9, v9, fa5
; RV32-NEXT:    vfmul.vv v9, v9, v11
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vfmadd.vv v8, v9, v10
; RV32-NEXT:    vfmul.vf v9, v9, fa5
; RV32-NEXT:    vfmul.vv v8, v9, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v10, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v11, v8, v9
; RV64-NEXT:    vfmadd.vv v11, v9, v10
; RV64-NEXT:    vfmul.vf v9, v9, fa5
; RV64-NEXT:    vfmul.vv v9, v9, v11
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vfmadd.vv v8, v9, v10
; RV64-NEXT:    vfmul.vf v9, v9, fa5
; RV64-NEXT:    vfmul.vv v8, v9, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x float> %ins, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a)
  %2 = fdiv fast <vscale x 2 x float> %splat, %1
  ret <vscale x 2 x float> %2
}

define <vscale x 4 x float> @rsqrt_nxv4f32(<vscale x 4 x float> %a) #0 {
; RV32-LABEL: rsqrt_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v12, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmadd.vv v14, v10, v12
; RV32-NEXT:    vfmul.vf v10, v10, fa5
; RV32-NEXT:    vfmul.vv v10, v10, v14
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vfmadd.vv v8, v10, v12
; RV32-NEXT:    vfmul.vf v10, v10, fa5
; RV32-NEXT:    vfmul.vv v8, v10, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v12, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmadd.vv v14, v10, v12
; RV64-NEXT:    vfmul.vf v10, v10, fa5
; RV64-NEXT:    vfmul.vv v10, v10, v14
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vfmadd.vv v8, v10, v12
; RV64-NEXT:    vfmul.vf v10, v10, fa5
; RV64-NEXT:    vfmul.vv v8, v10, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x float> %ins, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x float> @llvm.sqrt.nxv4f32(<vscale x 4 x float> %a)
  %2 = fdiv fast <vscale x 4 x float> %splat, %1
  ret <vscale x 4 x float> %2
}

define <vscale x 8 x float> @rsqrt_nxv8f32(<vscale x 8 x float> %a) #0 {
; RV32-LABEL: rsqrt_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v16, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v20, v8, v12
; RV32-NEXT:    vfmadd.vv v20, v12, v16
; RV32-NEXT:    vfmul.vf v12, v12, fa5
; RV32-NEXT:    vfmul.vv v12, v12, v20
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    vfmadd.vv v8, v12, v16
; RV32-NEXT:    vfmul.vf v12, v12, fa5
; RV32-NEXT:    vfmul.vv v8, v12, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v16, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v20, v8, v12
; RV64-NEXT:    vfmadd.vv v20, v12, v16
; RV64-NEXT:    vfmul.vf v12, v12, fa5
; RV64-NEXT:    vfmul.vv v12, v12, v20
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    vfmadd.vv v8, v12, v16
; RV64-NEXT:    vfmul.vf v12, v12, fa5
; RV64-NEXT:    vfmul.vv v8, v12, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x float> %ins, <vscale x 8 x float> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x float> @llvm.sqrt.nxv8f32(<vscale x 8 x float> %a)
  %2 = fdiv fast <vscale x 8 x float> %splat, %1
  ret <vscale x 8 x float> %2
}

define <vscale x 2 x double> @rsqrt_nxv2f64(<vscale x 2 x double> %a) #0 {
; RV32-LABEL: rsqrt_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI15_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI15_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI15_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI15_1)(a0)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmadd.vv v14, v10, v12
; RV32-NEXT:    vfmul.vf v10, v10, fa4
; RV32-NEXT:    vfmul.vv v10, v10, v14
; RV32-NEXT:    vfmul.vv v14, v8, v10
; RV32-NEXT:    vfmadd.vv v14, v10, v12
; RV32-NEXT:    vfmul.vf v10, v10, fa4
; RV32-NEXT:    vfmul.vv v10, v10, v14
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vfmadd.vv v8, v10, v12
; RV32-NEXT:    vfmul.vf v10, v10, fa4
; RV32-NEXT:    vfmul.vv v8, v10, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI15_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI15_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI15_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI15_1)(a0)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmadd.vv v14, v10, v12
; RV64-NEXT:    vfmul.vf v10, v10, fa4
; RV64-NEXT:    vfmul.vv v10, v10, v14
; RV64-NEXT:    vfmul.vv v14, v8, v10
; RV64-NEXT:    vfmadd.vv v14, v10, v12
; RV64-NEXT:    vfmul.vf v10, v10, fa4
; RV64-NEXT:    vfmul.vv v10, v10, v14
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vfmadd.vv v8, v10, v12
; RV64-NEXT:    vfmul.vf v10, v10, fa4
; RV64-NEXT:    vfmul.vv v8, v10, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x double> @llvm.sqrt.nxv2f64(<vscale x 2 x double> %a)
  %2 = fdiv fast <vscale x 2 x double> %splat, %1
  ret <vscale x 2 x double> %2
}

define <vscale x 4 x double> @rsqrt_nxv4f64(<vscale x 4 x double> %a) #0 {
; RV32-LABEL: rsqrt_nxv4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, %hi(.LCPI16_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI16_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI16_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI16_1)(a0)
; RV32-NEXT:    vfmv.v.f v16, fa5
; RV32-NEXT:    vfmul.vv v20, v8, v12
; RV32-NEXT:    vfmadd.vv v20, v12, v16
; RV32-NEXT:    vfmul.vf v12, v12, fa4
; RV32-NEXT:    vfmul.vv v12, v12, v20
; RV32-NEXT:    vfmul.vv v20, v8, v12
; RV32-NEXT:    vfmadd.vv v20, v12, v16
; RV32-NEXT:    vfmul.vf v12, v12, fa4
; RV32-NEXT:    vfmul.vv v12, v12, v20
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    vfmadd.vv v8, v12, v16
; RV32-NEXT:    vfmul.vf v12, v12, fa4
; RV32-NEXT:    vfmul.vv v8, v12, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, %hi(.LCPI16_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI16_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI16_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI16_1)(a0)
; RV64-NEXT:    vfmv.v.f v16, fa5
; RV64-NEXT:    vfmul.vv v20, v8, v12
; RV64-NEXT:    vfmadd.vv v20, v12, v16
; RV64-NEXT:    vfmul.vf v12, v12, fa4
; RV64-NEXT:    vfmul.vv v12, v12, v20
; RV64-NEXT:    vfmul.vv v20, v8, v12
; RV64-NEXT:    vfmadd.vv v20, v12, v16
; RV64-NEXT:    vfmul.vf v12, v12, fa4
; RV64-NEXT:    vfmul.vv v12, v12, v20
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    vfmadd.vv v8, v12, v16
; RV64-NEXT:    vfmul.vf v12, v12, fa4
; RV64-NEXT:    vfmul.vv v8, v12, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x double> @llvm.sqrt.nxv4f64(<vscale x 4 x double> %a)
  %2 = fdiv fast <vscale x 4 x double> %splat, %1
  ret <vscale x 4 x double> %2
}

define <vscale x 8 x double> @rsqrt_nxv8f64(<vscale x 8 x double> %a) #0 {
; RV32-LABEL: rsqrt_nxv8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a0, %hi(.LCPI17_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI17_0)(a0)
; RV32-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV32-NEXT:    vfrsqrt7.v v24, v8
; RV32-NEXT:    lui a0, %hi(.LCPI17_1)
; RV32-NEXT:    vfmv.v.f v16, fa5
; RV32-NEXT:    fld fa5, %lo(.LCPI17_1)(a0)
; RV32-NEXT:    vfmul.vv v0, v8, v24
; RV32-NEXT:    vfmadd.vv v0, v24, v16
; RV32-NEXT:    vfmul.vf v24, v24, fa5
; RV32-NEXT:    vfmul.vv v24, v24, v0
; RV32-NEXT:    vfmul.vv v0, v8, v24
; RV32-NEXT:    vfmadd.vv v0, v24, v16
; RV32-NEXT:    vfmul.vf v24, v24, fa5
; RV32-NEXT:    vfmul.vv v24, v24, v0
; RV32-NEXT:    vfmul.vv v8, v8, v24
; RV32-NEXT:    vfmadd.vv v8, v24, v16
; RV32-NEXT:    vfmul.vf v16, v24, fa5
; RV32-NEXT:    vfmul.vv v8, v16, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a0, %hi(.LCPI17_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI17_0)(a0)
; RV64-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV64-NEXT:    vfrsqrt7.v v24, v8
; RV64-NEXT:    lui a0, %hi(.LCPI17_1)
; RV64-NEXT:    vfmv.v.f v16, fa5
; RV64-NEXT:    fld fa5, %lo(.LCPI17_1)(a0)
; RV64-NEXT:    vfmul.vv v0, v8, v24
; RV64-NEXT:    vfmadd.vv v0, v24, v16
; RV64-NEXT:    vfmul.vf v24, v24, fa5
; RV64-NEXT:    vfmul.vv v24, v24, v0
; RV64-NEXT:    vfmul.vv v0, v8, v24
; RV64-NEXT:    vfmadd.vv v0, v24, v16
; RV64-NEXT:    vfmul.vf v24, v24, fa5
; RV64-NEXT:    vfmul.vv v24, v24, v0
; RV64-NEXT:    vfmul.vv v8, v8, v24
; RV64-NEXT:    vfmadd.vv v8, v24, v16
; RV64-NEXT:    vfmul.vf v16, v24, fa5
; RV64-NEXT:    vfmul.vv v8, v16, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x double> @llvm.sqrt.nxv8f64(<vscale x 8 x double> %a)
  %2 = fdiv fast <vscale x 8 x double> %splat, %1
  ret <vscale x 8 x double> %2
}

define <vscale x 2 x half> @sqrt_zero_steps_nxv2f16(<vscale x 2 x half> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    vfabs.v v10, v8
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    vfabs.v v10, v8
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x half> @llvm.sqrt.nxv2f16(<vscale x 2 x half> %a)
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @sqrt_zero_steps_nxv4f16(<vscale x 4 x half> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    vfabs.v v10, v8
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    vfabs.v v10, v8
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x half> @llvm.sqrt.nxv4f16(<vscale x 4 x half> %a)
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @sqrt_zero_steps_nxv8f16(<vscale x 8 x half> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    vfabs.v v12, v8
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v12, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    vfabs.v v12, v8
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v12, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x half> @llvm.sqrt.nxv8f16(<vscale x 8 x half> %a)
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x float> @sqrt_zero_steps_nxv2f32(<vscale x 2 x float> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    vfabs.v v10, v8
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    vfabs.v v10, v8
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a)
  ret <vscale x 2 x float> %1
}

define <vscale x 4 x float> @sqrt_zero_steps_nxv4f32(<vscale x 4 x float> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    vfabs.v v12, v8
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v12, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    vfabs.v v12, v8
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v12, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x float> @llvm.sqrt.nxv4f32(<vscale x 4 x float> %a)
  ret <vscale x 4 x float> %1
}

define <vscale x 8 x float> @sqrt_zero_steps_nxv8f32(<vscale x 8 x float> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    vfabs.v v16, v8
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v16, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    vfabs.v v16, v8
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v16, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x float> @llvm.sqrt.nxv8f32(<vscale x 8 x float> %a)
  ret <vscale x 8 x float> %1
}

define <vscale x 2 x double> @sqrt_zero_steps_nxv2f64(<vscale x 2 x double> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI24_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI24_0)(a0)
; RV32-NEXT:    vfabs.v v12, v8
; RV32-NEXT:    vmflt.vf v0, v12, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI24_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI24_0)(a0)
; RV64-NEXT:    vfabs.v v12, v8
; RV64-NEXT:    vmflt.vf v0, v12, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x double> @llvm.sqrt.nxv2f64(<vscale x 2 x double> %a)
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @sqrt_zero_steps_nvx4f64(<vscale x 4 x double> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nvx4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, %hi(.LCPI25_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI25_0)(a0)
; RV32-NEXT:    vfabs.v v16, v8
; RV32-NEXT:    vmflt.vf v0, v16, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nvx4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, %hi(.LCPI25_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI25_0)(a0)
; RV64-NEXT:    vfabs.v v16, v8
; RV64-NEXT:    vmflt.vf v0, v16, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x double> @llvm.sqrt.nxv4f64(<vscale x 4 x double> %a)
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @sqrt_zero_steps_nvx8f64(<vscale x 8 x double> %a) #1 {
; RV32-LABEL: sqrt_zero_steps_nvx8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, %hi(.LCPI26_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI26_0)(a0)
; RV32-NEXT:    vfabs.v v24, v8
; RV32-NEXT:    vmflt.vf v0, v24, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v16
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nvx8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, %hi(.LCPI26_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI26_0)(a0)
; RV64-NEXT:    vfabs.v v24, v8
; RV64-NEXT:    vmflt.vf v0, v24, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v16
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x double> @llvm.sqrt.nxv8f64(<vscale x 8 x double> %a)
  ret <vscale x 8 x double> %1
}

define <vscale x 2 x half> @rsqrt_zero_steps_nxv2f16(<vscale x 2 x half> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x half> @llvm.sqrt.nxv2f16(<vscale x 2 x half> %a)
  %2 = fdiv fast <vscale x 2 x half> %splat, %1
  ret <vscale x 2 x half> %2
}

define <vscale x 4 x half> @rsqrt_zero_steps_nxv4f16(<vscale x 4 x half> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x half> @llvm.sqrt.nxv4f16(<vscale x 4 x half> %a)
  %2 = fdiv fast <vscale x 4 x half> %splat, %1
  ret <vscale x 4 x half> %2
}

define <vscale x 8 x half> @rsqrt_zero_steps_nxv8f16(<vscale x 8 x half> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x half> @llvm.sqrt.nxv8f16(<vscale x 8 x half> %a)
  %2 = fdiv fast <vscale x 8 x half> %splat, %1
  ret <vscale x 8 x half> %2
}

define <vscale x 2 x float> @rsqrt_zero_steps_nxv2f32(<vscale x 2 x float> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x float> %ins, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x float> @llvm.sqrt.nxv2f32(<vscale x 2 x float> %a)
  %2 = fdiv fast <vscale x 2 x float> %splat, %1
  ret <vscale x 2 x float> %2
}

define <vscale x 4 x float> @rsqrt_zero_steps_nxv4f32(<vscale x 4 x float> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x float> %ins, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x float> @llvm.sqrt.nxv4f32(<vscale x 4 x float> %a)
  %2 = fdiv fast <vscale x 4 x float> %splat, %1
  ret <vscale x 4 x float> %2
}

define <vscale x 8 x float> @rsqrt_zero_steps_nxv8f32(<vscale x 8 x float> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x float> %ins, <vscale x 8 x float> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x float> @llvm.sqrt.nxv8f32(<vscale x 8 x float> %a)
  %2 = fdiv fast <vscale x 8 x float> %splat, %1
  ret <vscale x 8 x float> %2
}

define <vscale x 2 x double> @rsqrt_zero_steps_nxv2f64(<vscale x 2 x double> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x double> @llvm.sqrt.nxv2f64(<vscale x 2 x double> %a)
  %2 = fdiv fast <vscale x 2 x double> %splat, %1
  ret <vscale x 2 x double> %2
}

define <vscale x 4 x double> @rsqrt_zero_steps_nxv4f64(<vscale x 4 x double> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x double> @llvm.sqrt.nxv4f64(<vscale x 4 x double> %a)
  %2 = fdiv fast <vscale x 4 x double> %splat, %1
  ret <vscale x 4 x double> %2
}

define <vscale x 8 x double> @rsqrt_zero_steps_nxv8f64(<vscale x 8 x double> %a) #1 {
; RV32-LABEL: rsqrt_zero_steps_nxv8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x double> @llvm.sqrt.nxv8f64(<vscale x 8 x double> %a)
  %2 = fdiv fast <vscale x 8 x double> %splat, %1
  ret <vscale x 8 x double> %2
}

attributes #0 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-sqrt" }
attributes #1 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-sqrt:0" }
