; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+f,+v,+xsfvfhbfmin < %s \
; RUN:     --verify-machineinstrs | FileCheck %s

define <vscale x 4 x float> @test_from_bf16(<vscale x 4 x i16> %in) nounwind {
; CHECK-LABEL: test_from_bf16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    sf.vfwcvt.f.bf16.v v16, v8
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v8, v16
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x float> asm "sf.vfwcvt.f.bf16.v $0, $1", "={v16},^vr"(<vscale x 4 x i16> %in)
  ret <vscale x 4 x float> %0
}

define <vscale x 4 x i16> @test_to_bf16(<vscale x 4 x float> %in) nounwind {
; CHECK-LABEL: test_to_bf16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    sf.vfncvt.bf16.f.w v16, v8
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v8, v16
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x i16> asm "sf.vfncvt.bf16.f.w $0, $1", "={v16},^vr"(<vscale x 4 x float> %in)
  ret <vscale x 4 x i16> %0
}
