; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs \
; RUN:   | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs \
; RUN:   | FileCheck %s

declare <vscale x 1 x i16> @llvm.riscv.vwadd.w.tu.nxv1i16.nxv1i8.iXLen(
  <vscale x 1 x i16>,
  <vscale x 1 x i16>,
  <vscale x 1 x i8>,
  iXLen);

define <vscale x 1 x i16> @intrinsic_vwadd.w_wv_tu_nxv1i16_nxv1i16_nxv1i8(<vscale x 1 x i16> %0, <vscale x 1 x i16> %1, <vscale x 1 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv1i16_nxv1i16_nxv1i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i16> @llvm.riscv.vwadd.w.tu.nxv1i16.nxv1i8.iXLen(
    <vscale x 1 x i16> %0,
    <vscale x 1 x i16> %1,
    <vscale x 1 x i8> %2,
    iXLen %3)

  ret <vscale x 1 x i16> %a
}

define <vscale x 1 x i16> @intrinsic_vwadd.w_wv_tied_tu_nxv1i16_nxv1i16_nxv1i8(<vscale x 1 x i16> %0, <vscale x 1 x i8> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv1i16_nxv1i16_nxv1i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i16> @llvm.riscv.vwadd.w.tu.nxv1i16.nxv1i8.iXLen(
    <vscale x 1 x i16> %0,
    <vscale x 1 x i16> %0,
    <vscale x 1 x i8> %1,
    iXLen %2)

  ret <vscale x 1 x i16> %a
}

declare <vscale x 1 x i16> @llvm.riscv.vwadd.w.tu.nxv1i16.i8.iXLen(
  <vscale x 1 x i16>,
  <vscale x 1 x i16>,
  i8,
  iXLen);

define <vscale x 1 x i16> @intrinsic_vwadd.w_wx_tu_nxv1i16_nxv1i16_i8(<vscale x 1 x i16> %0, <vscale x 1 x i16> %1, i8 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv1i16_nxv1i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i16> @llvm.riscv.vwadd.w.tu.nxv1i16.i8.iXLen(
    <vscale x 1 x i16> %0,
    <vscale x 1 x i16> %1,
    i8 %2,
    iXLen %3)

  ret <vscale x 1 x i16> %a
}

define <vscale x 1 x i16> @intrinsic_vwadd.w_wx_tied_tu_nxv1i16_nxv1i16_i8(<vscale x 1 x i16> %0, i8 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv1i16_nxv1i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i16> @llvm.riscv.vwadd.w.tu.nxv1i16.i8.iXLen(
    <vscale x 1 x i16> %0,
    <vscale x 1 x i16> %0,
    i8 %1,
    iXLen %2)

  ret <vscale x 1 x i16> %a
}

declare <vscale x 2 x i16> @llvm.riscv.vwadd.w.tu.nxv2i16.nxv2i8.iXLen(
  <vscale x 2 x i16>,
  <vscale x 2 x i16>,
  <vscale x 2 x i8>,
  iXLen);

define <vscale x 2 x i16> @intrinsic_vwadd.w_wv_tu_nxv2i16_nxv2i16_nxv2i8(<vscale x 2 x i16> %0, <vscale x 2 x i16> %1, <vscale x 2 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv2i16_nxv2i16_nxv2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i16> @llvm.riscv.vwadd.w.tu.nxv2i16.nxv2i8.iXLen(
    <vscale x 2 x i16> %0,
    <vscale x 2 x i16> %1,
    <vscale x 2 x i8> %2,
    iXLen %3)

  ret <vscale x 2 x i16> %a
}

define <vscale x 2 x i16> @intrinsic_vwadd.w_wv_tied_tu_nxv2i16_nxv2i16_nxv2i8(<vscale x 2 x i16> %0, <vscale x 2 x i8> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv2i16_nxv2i16_nxv2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i16> @llvm.riscv.vwadd.w.tu.nxv2i16.nxv2i8.iXLen(
    <vscale x 2 x i16> %0,
    <vscale x 2 x i16> %0,
    <vscale x 2 x i8> %1,
    iXLen %2)

  ret <vscale x 2 x i16> %a
}

declare <vscale x 2 x i16> @llvm.riscv.vwadd.w.tu.nxv2i16.i8.iXLen(
  <vscale x 2 x i16>,
  <vscale x 2 x i16>,
  i8,
  iXLen);

define <vscale x 2 x i16> @intrinsic_vwadd.w_wx_tu_nxv2i16_nxv2i16_i8(<vscale x 2 x i16> %0, <vscale x 2 x i16> %1, i8 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv2i16_nxv2i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i16> @llvm.riscv.vwadd.w.tu.nxv2i16.i8.iXLen(
    <vscale x 2 x i16> %0,
    <vscale x 2 x i16> %1,
    i8 %2,
    iXLen %3)

  ret <vscale x 2 x i16> %a
}

define <vscale x 2 x i16> @intrinsic_vwadd.w_wx_tied_tu_nxv2i16_nxv2i16_i8(<vscale x 2 x i16> %0, i8 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv2i16_nxv2i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i16> @llvm.riscv.vwadd.w.tu.nxv2i16.i8.iXLen(
    <vscale x 2 x i16> %0,
    <vscale x 2 x i16> %0,
    i8 %1,
    iXLen %2)

  ret <vscale x 2 x i16> %a
}

declare <vscale x 4 x i16> @llvm.riscv.vwadd.w.tu.nxv4i16.nxv4i8.iXLen(
  <vscale x 4 x i16>,
  <vscale x 4 x i16>,
  <vscale x 4 x i8>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vwadd.w_wv_tu_nxv4i16_nxv4i16_nxv4i8(<vscale x 4 x i16> %0, <vscale x 4 x i16> %1, <vscale x 4 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv4i16_nxv4i16_nxv4i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i16> @llvm.riscv.vwadd.w.tu.nxv4i16.nxv4i8.iXLen(
    <vscale x 4 x i16> %0,
    <vscale x 4 x i16> %1,
    <vscale x 4 x i8> %2,
    iXLen %3)

  ret <vscale x 4 x i16> %a
}

define <vscale x 4 x i16> @intrinsic_vwadd.w_wv_tied_tu_nxv4i16_nxv4i16_nxv4i8(<vscale x 4 x i16> %0, <vscale x 4 x i8> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv4i16_nxv4i16_nxv4i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i16> @llvm.riscv.vwadd.w.tu.nxv4i16.nxv4i8.iXLen(
    <vscale x 4 x i16> %0,
    <vscale x 4 x i16> %0,
    <vscale x 4 x i8> %1,
    iXLen %2)

  ret <vscale x 4 x i16> %a
}

declare <vscale x 4 x i16> @llvm.riscv.vwadd.w.tu.nxv4i16.i8.iXLen(
  <vscale x 4 x i16>,
  <vscale x 4 x i16>,
  i8,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vwadd.w_wx_tu_nxv4i16_nxv4i16_i8(<vscale x 4 x i16> %0, <vscale x 4 x i16> %1, i8 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv4i16_nxv4i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i16> @llvm.riscv.vwadd.w.tu.nxv4i16.i8.iXLen(
    <vscale x 4 x i16> %0,
    <vscale x 4 x i16> %1,
    i8 %2,
    iXLen %3)

  ret <vscale x 4 x i16> %a
}

define <vscale x 4 x i16> @intrinsic_vwadd.w_wx_tied_tu_nxv4i16_nxv4i16_i8(<vscale x 4 x i16> %0, i8 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv4i16_nxv4i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i16> @llvm.riscv.vwadd.w.tu.nxv4i16.i8.iXLen(
    <vscale x 4 x i16> %0,
    <vscale x 4 x i16> %0,
    i8 %1,
    iXLen %2)

  ret <vscale x 4 x i16> %a
}

declare <vscale x 8 x i16> @llvm.riscv.vwadd.w.tu.nxv8i16.nxv8i8.iXLen(
  <vscale x 8 x i16>,
  <vscale x 8 x i16>,
  <vscale x 8 x i8>,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vwadd.w_wv_tu_nxv8i16_nxv8i16_nxv8i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1, <vscale x 8 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv8i16_nxv8i16_nxv8i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v10, v12
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i16> @llvm.riscv.vwadd.w.tu.nxv8i16.nxv8i8.iXLen(
    <vscale x 8 x i16> %0,
    <vscale x 8 x i16> %1,
    <vscale x 8 x i8> %2,
    iXLen %3)

  ret <vscale x 8 x i16> %a
}

define <vscale x 8 x i16> @intrinsic_vwadd.w_wv_tied_tu_nxv8i16_nxv8i16_nxv8i8(<vscale x 8 x i16> %0, <vscale x 8 x i8> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv8i16_nxv8i16_nxv8i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i16> @llvm.riscv.vwadd.w.tu.nxv8i16.nxv8i8.iXLen(
    <vscale x 8 x i16> %0,
    <vscale x 8 x i16> %0,
    <vscale x 8 x i8> %1,
    iXLen %2)

  ret <vscale x 8 x i16> %a
}

declare <vscale x 8 x i16> @llvm.riscv.vwadd.w.tu.nxv8i16.i8.iXLen(
  <vscale x 8 x i16>,
  <vscale x 8 x i16>,
  i8,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vwadd.w_wx_tu_nxv8i16_nxv8i16_i8(<vscale x 8 x i16> %0, <vscale x 8 x i16> %1, i8 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv8i16_nxv8i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v10, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i16> @llvm.riscv.vwadd.w.tu.nxv8i16.i8.iXLen(
    <vscale x 8 x i16> %0,
    <vscale x 8 x i16> %1,
    i8 %2,
    iXLen %3)

  ret <vscale x 8 x i16> %a
}

define <vscale x 8 x i16> @intrinsic_vwadd.w_wx_tied_tu_nxv8i16_nxv8i16_i8(<vscale x 8 x i16> %0, i8 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv8i16_nxv8i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i16> @llvm.riscv.vwadd.w.tu.nxv8i16.i8.iXLen(
    <vscale x 8 x i16> %0,
    <vscale x 8 x i16> %0,
    i8 %1,
    iXLen %2)

  ret <vscale x 8 x i16> %a
}

declare <vscale x 16 x i16> @llvm.riscv.vwadd.w.tu.nxv16i16.nxv16i8.iXLen(
  <vscale x 16 x i16>,
  <vscale x 16 x i16>,
  <vscale x 16 x i8>,
  iXLen);

define <vscale x 16 x i16> @intrinsic_vwadd.w_wv_tu_nxv16i16_nxv16i16_nxv16i8(<vscale x 16 x i16> %0, <vscale x 16 x i16> %1, <vscale x 16 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv16i16_nxv16i16_nxv16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v12, v16
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i16> @llvm.riscv.vwadd.w.tu.nxv16i16.nxv16i8.iXLen(
    <vscale x 16 x i16> %0,
    <vscale x 16 x i16> %1,
    <vscale x 16 x i8> %2,
    iXLen %3)

  ret <vscale x 16 x i16> %a
}

define <vscale x 16 x i16> @intrinsic_vwadd.w_wv_tied_tu_nxv16i16_nxv16i16_nxv16i8(<vscale x 16 x i16> %0, <vscale x 16 x i8> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv16i16_nxv16i16_nxv16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v12
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i16> @llvm.riscv.vwadd.w.tu.nxv16i16.nxv16i8.iXLen(
    <vscale x 16 x i16> %0,
    <vscale x 16 x i16> %0,
    <vscale x 16 x i8> %1,
    iXLen %2)

  ret <vscale x 16 x i16> %a
}

declare <vscale x 16 x i16> @llvm.riscv.vwadd.w.tu.nxv16i16.i8.iXLen(
  <vscale x 16 x i16>,
  <vscale x 16 x i16>,
  i8,
  iXLen);

define <vscale x 16 x i16> @intrinsic_vwadd.w_wx_tu_nxv16i16_nxv16i16_i8(<vscale x 16 x i16> %0, <vscale x 16 x i16> %1, i8 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv16i16_nxv16i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v12, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i16> @llvm.riscv.vwadd.w.tu.nxv16i16.i8.iXLen(
    <vscale x 16 x i16> %0,
    <vscale x 16 x i16> %1,
    i8 %2,
    iXLen %3)

  ret <vscale x 16 x i16> %a
}

define <vscale x 16 x i16> @intrinsic_vwadd.w_wx_tied_tu_nxv16i16_nxv16i16_i8(<vscale x 16 x i16> %0, i8 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv16i16_nxv16i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i16> @llvm.riscv.vwadd.w.tu.nxv16i16.i8.iXLen(
    <vscale x 16 x i16> %0,
    <vscale x 16 x i16> %0,
    i8 %1,
    iXLen %2)

  ret <vscale x 16 x i16> %a
}

declare <vscale x 32 x i16> @llvm.riscv.vwadd.w.tu.nxv32i16.nxv32i8.iXLen(
  <vscale x 32 x i16>,
  <vscale x 32 x i16>,
  <vscale x 32 x i8>,
  iXLen);

define <vscale x 32 x i16> @intrinsic_vwadd.w_wv_tu_nxv32i16_nxv32i16_nxv32i8(<vscale x 32 x i16> %0, <vscale x 32 x i16> %1, <vscale x 32 x i8> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv32i16_nxv32i16_nxv32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl4r.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v16, v24
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x i16> @llvm.riscv.vwadd.w.tu.nxv32i16.nxv32i8.iXLen(
    <vscale x 32 x i16> %0,
    <vscale x 32 x i16> %1,
    <vscale x 32 x i8> %2,
    iXLen %3)

  ret <vscale x 32 x i16> %a
}

define <vscale x 32 x i16> @intrinsic_vwadd.w_wv_tied_tu_nxv32i16_nxv32i16_nxv32i8(<vscale x 32 x i16> %0, <vscale x 32 x i8> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv32i16_nxv32i16_nxv32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v16
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x i16> @llvm.riscv.vwadd.w.tu.nxv32i16.nxv32i8.iXLen(
    <vscale x 32 x i16> %0,
    <vscale x 32 x i16> %0,
    <vscale x 32 x i8> %1,
    iXLen %2)

  ret <vscale x 32 x i16> %a
}

declare <vscale x 32 x i16> @llvm.riscv.vwadd.w.tu.nxv32i16.i8.iXLen(
  <vscale x 32 x i16>,
  <vscale x 32 x i16>,
  i8,
  iXLen);

define <vscale x 32 x i16> @intrinsic_vwadd.w_wx_tu_nxv32i16_nxv32i16_i8(<vscale x 32 x i16> %0, <vscale x 32 x i16> %1, i8 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv32i16_nxv32i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v16, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x i16> @llvm.riscv.vwadd.w.tu.nxv32i16.i8.iXLen(
    <vscale x 32 x i16> %0,
    <vscale x 32 x i16> %1,
    i8 %2,
    iXLen %3)

  ret <vscale x 32 x i16> %a
}

define <vscale x 32 x i16> @intrinsic_vwadd.w_wx_tied_tu_nxv32i16_nxv32i16_i8(<vscale x 32 x i16> %0, i8 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv32i16_nxv32i16_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x i16> @llvm.riscv.vwadd.w.tu.nxv32i16.i8.iXLen(
    <vscale x 32 x i16> %0,
    <vscale x 32 x i16> %0,
    i8 %1,
    iXLen %2)

  ret <vscale x 32 x i16> %a
}

declare <vscale x 1 x i32> @llvm.riscv.vwadd.w.tu.nxv1i32.nxv1i16.iXLen(
  <vscale x 1 x i32>,
  <vscale x 1 x i32>,
  <vscale x 1 x i16>,
  iXLen);

define <vscale x 1 x i32> @intrinsic_vwadd.w_wv_tu_nxv1i32_nxv1i32_nxv1i16(<vscale x 1 x i32> %0, <vscale x 1 x i32> %1, <vscale x 1 x i16> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv1i32_nxv1i32_nxv1i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i32> @llvm.riscv.vwadd.w.tu.nxv1i32.nxv1i16.iXLen(
    <vscale x 1 x i32> %0,
    <vscale x 1 x i32> %1,
    <vscale x 1 x i16> %2,
    iXLen %3)

  ret <vscale x 1 x i32> %a
}

define <vscale x 1 x i32> @intrinsic_vwadd.w_wv_tied_tu_nxv1i32_nxv1i32_nxv1i16(<vscale x 1 x i32> %0, <vscale x 1 x i16> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv1i32_nxv1i32_nxv1i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i32> @llvm.riscv.vwadd.w.tu.nxv1i32.nxv1i16.iXLen(
    <vscale x 1 x i32> %0,
    <vscale x 1 x i32> %0,
    <vscale x 1 x i16> %1,
    iXLen %2)

  ret <vscale x 1 x i32> %a
}

declare <vscale x 1 x i32> @llvm.riscv.vwadd.w.tu.nxv1i32.i16.iXLen(
  <vscale x 1 x i32>,
  <vscale x 1 x i32>,
  i16,
  iXLen);

define <vscale x 1 x i32> @intrinsic_vwadd.w_wx_tu_nxv1i32_nxv1i32_i16(<vscale x 1 x i32> %0, <vscale x 1 x i32> %1, i16 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv1i32_nxv1i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i32> @llvm.riscv.vwadd.w.tu.nxv1i32.i16.iXLen(
    <vscale x 1 x i32> %0,
    <vscale x 1 x i32> %1,
    i16 %2,
    iXLen %3)

  ret <vscale x 1 x i32> %a
}

define <vscale x 1 x i32> @intrinsic_vwadd.w_wx_tied_tu_nxv1i32_nxv1i32_i16(<vscale x 1 x i32> %0, i16 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv1i32_nxv1i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i32> @llvm.riscv.vwadd.w.tu.nxv1i32.i16.iXLen(
    <vscale x 1 x i32> %0,
    <vscale x 1 x i32> %0,
    i16 %1,
    iXLen %2)

  ret <vscale x 1 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.vwadd.w.tu.nxv2i32.nxv2i16.iXLen(
  <vscale x 2 x i32>,
  <vscale x 2 x i32>,
  <vscale x 2 x i16>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vwadd.w_wv_tu_nxv2i32_nxv2i32_nxv2i16(<vscale x 2 x i32> %0, <vscale x 2 x i32> %1, <vscale x 2 x i16> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv2i32_nxv2i32_nxv2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.vwadd.w.tu.nxv2i32.nxv2i16.iXLen(
    <vscale x 2 x i32> %0,
    <vscale x 2 x i32> %1,
    <vscale x 2 x i16> %2,
    iXLen %3)

  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @intrinsic_vwadd.w_wv_tied_tu_nxv2i32_nxv2i32_nxv2i16(<vscale x 2 x i32> %0, <vscale x 2 x i16> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv2i32_nxv2i32_nxv2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.vwadd.w.tu.nxv2i32.nxv2i16.iXLen(
    <vscale x 2 x i32> %0,
    <vscale x 2 x i32> %0,
    <vscale x 2 x i16> %1,
    iXLen %2)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.vwadd.w.tu.nxv2i32.i16.iXLen(
  <vscale x 2 x i32>,
  <vscale x 2 x i32>,
  i16,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vwadd.w_wx_tu_nxv2i32_nxv2i32_i16(<vscale x 2 x i32> %0, <vscale x 2 x i32> %1, i16 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv2i32_nxv2i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.vwadd.w.tu.nxv2i32.i16.iXLen(
    <vscale x 2 x i32> %0,
    <vscale x 2 x i32> %1,
    i16 %2,
    iXLen %3)

  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @intrinsic_vwadd.w_wx_tied_tu_nxv2i32_nxv2i32_i16(<vscale x 2 x i32> %0, i16 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv2i32_nxv2i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.vwadd.w.tu.nxv2i32.i16.iXLen(
    <vscale x 2 x i32> %0,
    <vscale x 2 x i32> %0,
    i16 %1,
    iXLen %2)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.vwadd.w.tu.nxv4i32.nxv4i16.iXLen(
  <vscale x 4 x i32>,
  <vscale x 4 x i32>,
  <vscale x 4 x i16>,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vwadd.w_wv_tu_nxv4i32_nxv4i32_nxv4i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1, <vscale x 4 x i16> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv4i32_nxv4i32_nxv4i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v10, v12
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.vwadd.w.tu.nxv4i32.nxv4i16.iXLen(
    <vscale x 4 x i32> %0,
    <vscale x 4 x i32> %1,
    <vscale x 4 x i16> %2,
    iXLen %3)

  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @intrinsic_vwadd.w_wv_tied_tu_nxv4i32_nxv4i32_nxv4i16(<vscale x 4 x i32> %0, <vscale x 4 x i16> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv4i32_nxv4i32_nxv4i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.vwadd.w.tu.nxv4i32.nxv4i16.iXLen(
    <vscale x 4 x i32> %0,
    <vscale x 4 x i32> %0,
    <vscale x 4 x i16> %1,
    iXLen %2)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.vwadd.w.tu.nxv4i32.i16.iXLen(
  <vscale x 4 x i32>,
  <vscale x 4 x i32>,
  i16,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vwadd.w_wx_tu_nxv4i32_nxv4i32_i16(<vscale x 4 x i32> %0, <vscale x 4 x i32> %1, i16 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv4i32_nxv4i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v10, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.vwadd.w.tu.nxv4i32.i16.iXLen(
    <vscale x 4 x i32> %0,
    <vscale x 4 x i32> %1,
    i16 %2,
    iXLen %3)

  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @intrinsic_vwadd.w_wx_tied_tu_nxv4i32_nxv4i32_i16(<vscale x 4 x i32> %0, i16 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv4i32_nxv4i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.vwadd.w.tu.nxv4i32.i16.iXLen(
    <vscale x 4 x i32> %0,
    <vscale x 4 x i32> %0,
    i16 %1,
    iXLen %2)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.vwadd.w.tu.nxv8i32.nxv8i16.iXLen(
  <vscale x 8 x i32>,
  <vscale x 8 x i32>,
  <vscale x 8 x i16>,
  iXLen);

define <vscale x 8 x i32> @intrinsic_vwadd.w_wv_tu_nxv8i32_nxv8i32_nxv8i16(<vscale x 8 x i32> %0, <vscale x 8 x i32> %1, <vscale x 8 x i16> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv8i32_nxv8i32_nxv8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v12, v16
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.vwadd.w.tu.nxv8i32.nxv8i16.iXLen(
    <vscale x 8 x i32> %0,
    <vscale x 8 x i32> %1,
    <vscale x 8 x i16> %2,
    iXLen %3)

  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @intrinsic_vwadd.w_wv_tied_tu_nxv8i32_nxv8i32_nxv8i16(<vscale x 8 x i32> %0, <vscale x 8 x i16> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv8i32_nxv8i32_nxv8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v12
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.vwadd.w.tu.nxv8i32.nxv8i16.iXLen(
    <vscale x 8 x i32> %0,
    <vscale x 8 x i32> %0,
    <vscale x 8 x i16> %1,
    iXLen %2)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.vwadd.w.tu.nxv8i32.i16.iXLen(
  <vscale x 8 x i32>,
  <vscale x 8 x i32>,
  i16,
  iXLen);

define <vscale x 8 x i32> @intrinsic_vwadd.w_wx_tu_nxv8i32_nxv8i32_i16(<vscale x 8 x i32> %0, <vscale x 8 x i32> %1, i16 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv8i32_nxv8i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v12, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.vwadd.w.tu.nxv8i32.i16.iXLen(
    <vscale x 8 x i32> %0,
    <vscale x 8 x i32> %1,
    i16 %2,
    iXLen %3)

  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @intrinsic_vwadd.w_wx_tied_tu_nxv8i32_nxv8i32_i16(<vscale x 8 x i32> %0, i16 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv8i32_nxv8i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.vwadd.w.tu.nxv8i32.i16.iXLen(
    <vscale x 8 x i32> %0,
    <vscale x 8 x i32> %0,
    i16 %1,
    iXLen %2)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.vwadd.w.tu.nxv16i32.nxv16i16.iXLen(
  <vscale x 16 x i32>,
  <vscale x 16 x i32>,
  <vscale x 16 x i16>,
  iXLen);

define <vscale x 16 x i32> @intrinsic_vwadd.w_wv_tu_nxv16i32_nxv16i32_nxv16i16(<vscale x 16 x i32> %0, <vscale x 16 x i32> %1, <vscale x 16 x i16> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv16i32_nxv16i32_nxv16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl4re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v16, v24
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.vwadd.w.tu.nxv16i32.nxv16i16.iXLen(
    <vscale x 16 x i32> %0,
    <vscale x 16 x i32> %1,
    <vscale x 16 x i16> %2,
    iXLen %3)

  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @intrinsic_vwadd.w_wv_tied_tu_nxv16i32_nxv16i32_nxv16i16(<vscale x 16 x i32> %0, <vscale x 16 x i16> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv16i32_nxv16i32_nxv16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v16
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.vwadd.w.tu.nxv16i32.nxv16i16.iXLen(
    <vscale x 16 x i32> %0,
    <vscale x 16 x i32> %0,
    <vscale x 16 x i16> %1,
    iXLen %2)

  ret <vscale x 16 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.vwadd.w.tu.nxv16i32.i16.iXLen(
  <vscale x 16 x i32>,
  <vscale x 16 x i32>,
  i16,
  iXLen);

define <vscale x 16 x i32> @intrinsic_vwadd.w_wx_tu_nxv16i32_nxv16i32_i16(<vscale x 16 x i32> %0, <vscale x 16 x i32> %1, i16 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv16i32_nxv16i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v16, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.vwadd.w.tu.nxv16i32.i16.iXLen(
    <vscale x 16 x i32> %0,
    <vscale x 16 x i32> %1,
    i16 %2,
    iXLen %3)

  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @intrinsic_vwadd.w_wx_tied_tu_nxv16i32_nxv16i32_i16(<vscale x 16 x i32> %0, i16 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv16i32_nxv16i32_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.vwadd.w.tu.nxv16i32.i16.iXLen(
    <vscale x 16 x i32> %0,
    <vscale x 16 x i32> %0,
    i16 %1,
    iXLen %2)

  ret <vscale x 16 x i32> %a
}

declare <vscale x 1 x i64> @llvm.riscv.vwadd.w.tu.nxv1i64.nxv1i32.iXLen(
  <vscale x 1 x i64>,
  <vscale x 1 x i64>,
  <vscale x 1 x i32>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vwadd.w_wv_tu_nxv1i64_nxv1i64_nxv1i32(<vscale x 1 x i64> %0, <vscale x 1 x i64> %1, <vscale x 1 x i32> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv1i64_nxv1i64_nxv1i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v9, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i64> @llvm.riscv.vwadd.w.tu.nxv1i64.nxv1i32.iXLen(
    <vscale x 1 x i64> %0,
    <vscale x 1 x i64> %1,
    <vscale x 1 x i32> %2,
    iXLen %3)

  ret <vscale x 1 x i64> %a
}

define <vscale x 1 x i64> @intrinsic_vwadd.w_wv_tied_tu_nxv1i64_nxv1i64_nxv1i32(<vscale x 1 x i64> %0, <vscale x 1 x i32> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv1i64_nxv1i64_nxv1i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i64> @llvm.riscv.vwadd.w.tu.nxv1i64.nxv1i32.iXLen(
    <vscale x 1 x i64> %0,
    <vscale x 1 x i64> %0,
    <vscale x 1 x i32> %1,
    iXLen %2)

  ret <vscale x 1 x i64> %a
}

declare <vscale x 1 x i64> @llvm.riscv.vwadd.w.tu.nxv1i64.i32.iXLen(
  <vscale x 1 x i64>,
  <vscale x 1 x i64>,
  i32,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vwadd.w_wx_tu_nxv1i64_nxv1i64_i32(<vscale x 1 x i64> %0, <vscale x 1 x i64> %1, i32 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv1i64_nxv1i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i64> @llvm.riscv.vwadd.w.tu.nxv1i64.i32.iXLen(
    <vscale x 1 x i64> %0,
    <vscale x 1 x i64> %1,
    i32 %2,
    iXLen %3)

  ret <vscale x 1 x i64> %a
}

define <vscale x 1 x i64> @intrinsic_vwadd.w_wx_tied_tu_nxv1i64_nxv1i64_i32(<vscale x 1 x i64> %0, i32 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv1i64_nxv1i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i64> @llvm.riscv.vwadd.w.tu.nxv1i64.i32.iXLen(
    <vscale x 1 x i64> %0,
    <vscale x 1 x i64> %0,
    i32 %1,
    iXLen %2)

  ret <vscale x 1 x i64> %a
}

declare <vscale x 2 x i64> @llvm.riscv.vwadd.w.tu.nxv2i64.nxv2i32.iXLen(
  <vscale x 2 x i64>,
  <vscale x 2 x i64>,
  <vscale x 2 x i32>,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vwadd.w_wv_tu_nxv2i64_nxv2i64_nxv2i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1, <vscale x 2 x i32> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv2i64_nxv2i64_nxv2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v10, v12
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i64> @llvm.riscv.vwadd.w.tu.nxv2i64.nxv2i32.iXLen(
    <vscale x 2 x i64> %0,
    <vscale x 2 x i64> %1,
    <vscale x 2 x i32> %2,
    iXLen %3)

  ret <vscale x 2 x i64> %a
}

define <vscale x 2 x i64> @intrinsic_vwadd.w_wv_tied_tu_nxv2i64_nxv2i64_nxv2i32(<vscale x 2 x i64> %0, <vscale x 2 x i32> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv2i64_nxv2i64_nxv2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v10
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i64> @llvm.riscv.vwadd.w.tu.nxv2i64.nxv2i32.iXLen(
    <vscale x 2 x i64> %0,
    <vscale x 2 x i64> %0,
    <vscale x 2 x i32> %1,
    iXLen %2)

  ret <vscale x 2 x i64> %a
}

declare <vscale x 2 x i64> @llvm.riscv.vwadd.w.tu.nxv2i64.i32.iXLen(
  <vscale x 2 x i64>,
  <vscale x 2 x i64>,
  i32,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vwadd.w_wx_tu_nxv2i64_nxv2i64_i32(<vscale x 2 x i64> %0, <vscale x 2 x i64> %1, i32 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv2i64_nxv2i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v10, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i64> @llvm.riscv.vwadd.w.tu.nxv2i64.i32.iXLen(
    <vscale x 2 x i64> %0,
    <vscale x 2 x i64> %1,
    i32 %2,
    iXLen %3)

  ret <vscale x 2 x i64> %a
}

define <vscale x 2 x i64> @intrinsic_vwadd.w_wx_tied_tu_nxv2i64_nxv2i64_i32(<vscale x 2 x i64> %0, i32 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv2i64_nxv2i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i64> @llvm.riscv.vwadd.w.tu.nxv2i64.i32.iXLen(
    <vscale x 2 x i64> %0,
    <vscale x 2 x i64> %0,
    i32 %1,
    iXLen %2)

  ret <vscale x 2 x i64> %a
}

declare <vscale x 4 x i64> @llvm.riscv.vwadd.w.tu.nxv4i64.nxv4i32.iXLen(
  <vscale x 4 x i64>,
  <vscale x 4 x i64>,
  <vscale x 4 x i32>,
  iXLen);

define <vscale x 4 x i64> @intrinsic_vwadd.w_wv_tu_nxv4i64_nxv4i64_nxv4i32(<vscale x 4 x i64> %0, <vscale x 4 x i64> %1, <vscale x 4 x i32> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv4i64_nxv4i64_nxv4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v12, v16
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.tu.nxv4i64.nxv4i32.iXLen(
    <vscale x 4 x i64> %0,
    <vscale x 4 x i64> %1,
    <vscale x 4 x i32> %2,
    iXLen %3)

  ret <vscale x 4 x i64> %a
}

define <vscale x 4 x i64> @intrinsic_vwadd.w_wv_tied_tu_nxv4i64_nxv4i64_nxv4i32(<vscale x 4 x i64> %0, <vscale x 4 x i32> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv4i64_nxv4i64_nxv4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v12
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.tu.nxv4i64.nxv4i32.iXLen(
    <vscale x 4 x i64> %0,
    <vscale x 4 x i64> %0,
    <vscale x 4 x i32> %1,
    iXLen %2)

  ret <vscale x 4 x i64> %a
}

declare <vscale x 4 x i64> @llvm.riscv.vwadd.w.tu.nxv4i64.i32.iXLen(
  <vscale x 4 x i64>,
  <vscale x 4 x i64>,
  i32,
  iXLen);

define <vscale x 4 x i64> @intrinsic_vwadd.w_wx_tu_nxv4i64_nxv4i64_i32(<vscale x 4 x i64> %0, <vscale x 4 x i64> %1, i32 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv4i64_nxv4i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v12, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.tu.nxv4i64.i32.iXLen(
    <vscale x 4 x i64> %0,
    <vscale x 4 x i64> %1,
    i32 %2,
    iXLen %3)

  ret <vscale x 4 x i64> %a
}

define <vscale x 4 x i64> @intrinsic_vwadd.w_wx_tied_tu_nxv4i64_nxv4i64_i32(<vscale x 4 x i64> %0, i32 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv4i64_nxv4i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m2, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i64> @llvm.riscv.vwadd.w.tu.nxv4i64.i32.iXLen(
    <vscale x 4 x i64> %0,
    <vscale x 4 x i64> %0,
    i32 %1,
    iXLen %2)

  ret <vscale x 4 x i64> %a
}

declare <vscale x 8 x i64> @llvm.riscv.vwadd.w.tu.nxv8i64.nxv8i32.iXLen(
  <vscale x 8 x i64>,
  <vscale x 8 x i64>,
  <vscale x 8 x i32>,
  iXLen);

define <vscale x 8 x i64> @intrinsic_vwadd.w_wv_tu_nxv8i64_nxv8i64_nxv8i32(<vscale x 8 x i64> %0, <vscale x 8 x i64> %1, <vscale x 8 x i32> %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tu_nxv8i64_nxv8i64_nxv8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vl4re32.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v16, v24
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i64> @llvm.riscv.vwadd.w.tu.nxv8i64.nxv8i32.iXLen(
    <vscale x 8 x i64> %0,
    <vscale x 8 x i64> %1,
    <vscale x 8 x i32> %2,
    iXLen %3)

  ret <vscale x 8 x i64> %a
}

define <vscale x 8 x i64> @intrinsic_vwadd.w_wv_tied_tu_nxv8i64_nxv8i64_nxv8i32(<vscale x 8 x i64> %0, <vscale x 8 x i32> %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wv_tied_tu_nxv8i64_nxv8i64_nxv8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, tu, ma
; CHECK-NEXT:    vwadd.wv v8, v8, v16
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i64> @llvm.riscv.vwadd.w.tu.nxv8i64.nxv8i32.iXLen(
    <vscale x 8 x i64> %0,
    <vscale x 8 x i64> %0,
    <vscale x 8 x i32> %1,
    iXLen %2)

  ret <vscale x 8 x i64> %a
}

declare <vscale x 8 x i64> @llvm.riscv.vwadd.w.tu.nxv8i64.i32.iXLen(
  <vscale x 8 x i64>,
  <vscale x 8 x i64>,
  i32,
  iXLen);

define <vscale x 8 x i64> @intrinsic_vwadd.w_wx_tu_nxv8i64_nxv8i64_i32(<vscale x 8 x i64> %0, <vscale x 8 x i64> %1, i32 %2, iXLen %3) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tu_nxv8i64_nxv8i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v16, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i64> @llvm.riscv.vwadd.w.tu.nxv8i64.i32.iXLen(
    <vscale x 8 x i64> %0,
    <vscale x 8 x i64> %1,
    i32 %2,
    iXLen %3)

  ret <vscale x 8 x i64> %a
}

define <vscale x 8 x i64> @intrinsic_vwadd.w_wx_tied_tu_nxv8i64_nxv8i64_i32(<vscale x 8 x i64> %0, i32 %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vwadd.w_wx_tied_tu_nxv8i64_nxv8i64_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, tu, ma
; CHECK-NEXT:    vwadd.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i64> @llvm.riscv.vwadd.w.tu.nxv8i64.i32.iXLen(
    <vscale x 8 x i64> %0,
    <vscale x 8 x i64> %0,
    i32 %1,
    iXLen %2)

  ret <vscale x 8 x i64> %a
}
