; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+f,+v,+xsfvfnrclipxfqf < %s \
; RUN:     --verify-machineinstrs | FileCheck %s

define <vscale x 8 x i8> @sf_vfnrclip_xu_f_qf(<vscale x 8 x float> %a, float %b) nounwind {
; CHECK-LABEL: sf_vfnrclip_xu_f_qf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    sf.vfnrclip.xu.f.qf v8, v8, fa0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i8> asm sideeffect "sf.vfnrclip.xu.f.qf $0, $1, $2", "=^vr,^vr,f"(<vscale x 8 x float> %a, float %b)
  ret <vscale x 8 x i8> %0
}

define <vscale x 8 x i8> @sf_vfnrclip_x_f_qf(<vscale x 8 x float> %a, float %b) nounwind {
; CHECK-LABEL: sf_vfnrclip_x_f_qf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v8, fa0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i8> asm sideeffect "sf.vfnrclip.x.f.qf $0, $1, $2", "=^vr,^vr,f"(<vscale x 8 x float> %a, float %b)
  ret <vscale x 8 x i8> %0
}
