; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs < %s | FileCheck %s

define <vscale x 1 x i1> @vp_set_before_first_nxv1i1(<vscale x 1 x i1> %val, <vscale x 1 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv1i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x i1> @llvm.experimental.vp.set.before.first.nxv1i1(<vscale x 1 x i1> %val, <vscale x 1 x i1> %mask, i32 %evl)
  ret <vscale x 1 x i1> %r
}

define <vscale x 2 x i1> @vp_set_before_first_nxv2i1(<vscale x 2 x i1> %val, <vscale x 2 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv2i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x i1> @llvm.experimental.vp.set.before.first.nxv2i1(<vscale x 2 x i1> %val, <vscale x 2 x i1> %mask, i32 %evl)
  ret <vscale x 2 x i1> %r
}

define <vscale x 4 x i1> @vp_set_before_first_nxv4i1(<vscale x 4 x i1> %val, <vscale x 4 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv4i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x i1> @llvm.experimental.vp.set.before.first.nxv4i1(<vscale x 4 x i1> %val, <vscale x 4 x i1> %mask, i32 %evl)
  ret <vscale x 4 x i1> %r
}

define <vscale x 8 x i1> @vp_set_before_first_nxv8i1(<vscale x 8 x i1> %val, <vscale x 8 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv8i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x i1> @llvm.experimental.vp.set.before.first.nxv8i1(<vscale x 8 x i1> %val, <vscale x 8 x i1> %mask, i32 %evl)
  ret <vscale x 8 x i1> %r
}

define <vscale x 16 x i1> @vp_set_before_first_nxv16i1(<vscale x 16 x i1> %val, <vscale x 16 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x i1> @llvm.experimental.vp.set.before.first.nxv16i1(<vscale x 16 x i1> %val, <vscale x 16 x i1> %mask, i32 %evl)
  ret <vscale x 16 x i1> %r
}

define <vscale x 32 x i1> @vp_set_before_first_nxv32i1(<vscale x 32 x i1> %val, <vscale x 32 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv32i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 32 x i1> @llvm.experimental.vp.set.before.first.nxv32i1(<vscale x 32 x i1> %val, <vscale x 32 x i1> %mask, i32 %evl)
  ret <vscale x 32 x i1> %r
}

define <vscale x 64 x i1> @vp_set_before_first_nxv64i1(<vscale x 64 x i1> %val, <vscale x 64 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv64i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 64 x i1> @llvm.experimental.vp.set.before.first.nxv64i1(<vscale x 64 x i1> %val, <vscale x 64 x i1> %mask, i32 %evl)
  ret <vscale x 64 x i1> %r
}

define <vscale x 128 x i1> @vp_set_before_first_nxv128i1(<vscale x 128 x i1> %val, <vscale x 128 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv128i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v11, v0
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    mv a2, a0
; CHECK-NEXT:    bltu a0, a1, .LBB7_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB7_2:
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; CHECK-NEXT:    vmsbf.m v12, v11, v0.t
; CHECK-NEXT:    vfirst.m a2, v12, v0.t
; CHECK-NEXT:    bltz a2, .LBB7_4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    vsetvli a0, zero, e8, m8, ta, ma
; CHECK-NEXT:    vmclr.m v9
; CHECK-NEXT:    j .LBB7_5
; CHECK-NEXT:  .LBB7_4:
; CHECK-NEXT:    sub a1, a0, a1
; CHECK-NEXT:    sltu a0, a0, a1
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vmsbf.m v9, v8, v0.t
; CHECK-NEXT:  .LBB7_5:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v0, v12
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    ret
  %r = call <vscale x 128 x i1> @llvm.experimental.vp.set.before.first.nxv128i1(<vscale x 128 x i1> %val, <vscale x 128 x i1> %mask, i32 %evl)
  ret <vscale x 128 x i1> %r
}

define <1 x i1> @vp_set_before_first_v1i1(<1 x i1> %val, <1 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v1i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <1 x i1> @llvm.experimental.vp.set.before.first.v1i1(<1 x i1> %val, <1 x i1> %mask, i32 %evl)
  ret <1 x i1> %r
}

define <2 x i1> @vp_set_before_first_v2i1(<2 x i1> %val, <2 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v2i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <2 x i1> @llvm.experimental.vp.set.before.first.v2i1(<2 x i1> %val, <2 x i1> %mask, i32 %evl)
  ret <2 x i1> %r
}

define <4 x i1> @vp_set_before_first_v4i1(<4 x i1> %val, <4 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v4i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <4 x i1> @llvm.experimental.vp.set.before.first.v4i1(<4 x i1> %val, <4 x i1> %mask, i32 %evl)
  ret <4 x i1> %r
}

define <8 x i1> @vp_set_before_first_v8i1(<8 x i1> %val, <8 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v8i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <8 x i1> @llvm.experimental.vp.set.before.first.v8i1(<8 x i1> %val, <8 x i1> %mask, i32 %evl)
  ret <8 x i1> %r
}

define <16 x i1> @vp_set_before_first_v16i1(<16 x i1> %val, <16 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    ret
  %r = call <16 x i1> @llvm.experimental.vp.set.before.first.v16i1(<16 x i1> %val, <16 x i1> %mask, i32 %evl)
  ret <16 x i1> %r
}

define <32 x i1> @vp_set_before_first_v32i1(<32 x i1> %val, <32 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v32i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <32 x i1> @llvm.experimental.vp.set.before.first.v32i1(<32 x i1> %val, <32 x i1> %mask, i32 %evl)
  ret <32 x i1> %r
}

define <64 x i1> @vp_set_before_first_v64i1(<64 x i1> %val, <64 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v64i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <64 x i1> @llvm.experimental.vp.set.before.first.v64i1(<64 x i1> %val, <64 x i1> %mask, i32 %evl)
  ret <64 x i1> %r
}

define <128 x i1> @vp_set_before_first_v128i1(<128 x i1> %val, <128 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v128i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <128 x i1> @llvm.experimental.vp.set.before.first.v128i1(<128 x i1> %val, <128 x i1> %mask, i32 %evl)
  ret <128 x i1> %r
}

define <256 x i1> @vp_set_before_first_v256i1(<256 x i1> %val, <256 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v256i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v11, v0
; CHECK-NEXT:    li a1, 128
; CHECK-NEXT:    mv a2, a0
; CHECK-NEXT:    bltu a0, a1, .LBB16_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    li a2, 128
; CHECK-NEXT:  .LBB16_2:
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; CHECK-NEXT:    vmsbf.m v12, v11, v0.t
; CHECK-NEXT:    vfirst.m a2, v12, v0.t
; CHECK-NEXT:    bltz a2, .LBB16_4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    vmclr.m v9
; CHECK-NEXT:    j .LBB16_5
; CHECK-NEXT:  .LBB16_4:
; CHECK-NEXT:    addi a1, a0, -128
; CHECK-NEXT:    sltu a0, a0, a1
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a0, a0, a1
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vmsbf.m v9, v8, v0.t
; CHECK-NEXT:  .LBB16_5:
; CHECK-NEXT:    vsetivli zero, 1, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v0, v12
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    ret
  %r = call <256 x i1> @llvm.experimental.vp.set.before.first.v256i1(<256 x i1> %val, <256 x i1> %mask, i32 %evl)
  ret <256 x i1> %r
}

define <7 x i1> @vp_set_before_first_v7i1(<7 x i1> %val, <7 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_v7i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %r = call <7 x i1> @llvm.experimental.vp.set.before.first.v7i1(<7 x i1> %val, <7 x i1> %mask, i32 %evl)
  ret <7 x i1> %r
}

define <vscale x 7 x i1> @vp_set_before_first_nxv7i1(<vscale x 7 x i1> %val, <vscale x 7 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: vp_set_before_first_nxv7i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmsbf.m v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    ret
  %r = call <vscale x 7 x i1> @llvm.experimental.vp.set.before.first.nxv7i1(<vscale x 7 x i1> %val, <vscale x 7 x i1> %mask, i32 %evl)
  ret <vscale x 7 x i1> %r
}
