; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -target-abi=ilp32d -mattr=+v,+zfh,+zvfh,+f,+d -riscv-v-vector-bits-min=128 | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -target-abi=lp64d -mattr=+v,+zfh,+zvfh,+f,+d -riscv-v-vector-bits-min=128 | FileCheck %s

define <vscale x 2 x half> @recip_nxv2f16(<vscale x 2 x half> %a) #0 {
; CHECK-LABEL: recip_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vfrec7.v v9, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    vfnmsub.vv v8, v9, v10
; CHECK-NEXT:    vfmadd.vv v8, v9, v9
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 2 x half> %splat, %a
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @recip_nxv4f16(<vscale x 4 x half> %a) #0 {
; CHECK-LABEL: recip_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfrec7.v v9, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI1_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI1_0)(a0)
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    vfnmsub.vv v8, v9, v10
; CHECK-NEXT:    vfmadd.vv v8, v9, v9
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 4 x half> %splat, %a
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @recip_nxv8f16(<vscale x 8 x half> %a) #0 {
; CHECK-LABEL: recip_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v10, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI2_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI2_0)(a0)
; CHECK-NEXT:    vfmv.v.f v12, fa5
; CHECK-NEXT:    vfnmsub.vv v8, v10, v12
; CHECK-NEXT:    vfmadd.vv v8, v10, v10
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 8 x half> %splat, %a
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x double> @recip_nxv2f64(<vscale x 2 x double> %a) #0 {
; CHECK-LABEL: recip_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v10, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI3_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI3_0)(a0)
; CHECK-NEXT:    vfmv.v.f v12, fa5
; CHECK-NEXT:    vmv.v.v v14, v10
; CHECK-NEXT:    vfnmsub.vv v14, v8, v12
; CHECK-NEXT:    vfmadd.vv v14, v10, v10
; CHECK-NEXT:    vmv.v.v v10, v14
; CHECK-NEXT:    vfnmsub.vv v10, v8, v12
; CHECK-NEXT:    vfmadd.vv v10, v14, v14
; CHECK-NEXT:    vfnmsub.vv v8, v10, v12
; CHECK-NEXT:    vfmadd.vv v8, v10, v10
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 2 x double> %splat, %a
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @recip_nxv4f64(<vscale x 4 x double> %a) #0 {
; CHECK-LABEL: recip_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; CHECK-NEXT:    vfrec7.v v12, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI4_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI4_0)(a0)
; CHECK-NEXT:    vfmv.v.f v16, fa5
; CHECK-NEXT:    vmv.v.v v20, v12
; CHECK-NEXT:    vfnmsub.vv v20, v8, v16
; CHECK-NEXT:    vfmadd.vv v20, v12, v12
; CHECK-NEXT:    vmv.v.v v12, v20
; CHECK-NEXT:    vfnmsub.vv v12, v8, v16
; CHECK-NEXT:    vfmadd.vv v12, v20, v20
; CHECK-NEXT:    vfnmsub.vv v8, v12, v16
; CHECK-NEXT:    vfmadd.vv v8, v12, v12
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 4 x double> %splat, %a
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @recip_nxv8f64(<vscale x 8 x double> %a) #0 {
; CHECK-LABEL: recip_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; CHECK-NEXT:    vfrec7.v v24, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI5_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI5_0)(a0)
; CHECK-NEXT:    vfmv.v.f v16, fa5
; CHECK-NEXT:    vmv.v.v v0, v24
; CHECK-NEXT:    vfnmsub.vv v0, v8, v16
; CHECK-NEXT:    vfmadd.vv v0, v24, v24
; CHECK-NEXT:    vmv.v.v v24, v0
; CHECK-NEXT:    vfnmsub.vv v24, v8, v16
; CHECK-NEXT:    vfmadd.vv v24, v0, v0
; CHECK-NEXT:    vfnmsub.vv v8, v24, v16
; CHECK-NEXT:    vfmadd.vv v8, v24, v24
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 8 x double> %splat, %a
  ret <vscale x 8 x double> %1
}

define <vscale x 2 x half> @recip_zero_steps_nxv2f16(<vscale x 2 x half> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 2 x half> %splat, %a
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @recip_zero_steps_nxv4f16(<vscale x 4 x half> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 4 x half> %splat, %a
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @recip_zero_steps_nxv8f16(<vscale x 8 x half> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e16, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 8 x half> %splat, %a
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x float> @recip_zero_steps_nxv2f32(<vscale x 2 x float> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x float> %ins, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 2 x float> %splat, %a
  ret <vscale x 2 x float> %1
}

define <vscale x 4 x float> @recip_zero_steps_nxv4f32(<vscale x 4 x float> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x float> %ins, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 4 x float> %splat, %a
  ret <vscale x 4 x float> %1
}

define <vscale x 8 x float> @recip_zero_steps_nxv8f32(<vscale x 8 x float> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e32, m4, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x float> %ins, <vscale x 8 x float> poison, <vscale x 8 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 8 x float> %splat, %a
  ret <vscale x 8 x float> %1
}

define <vscale x 2 x double> @recip_zero_steps_nxv2f64(<vscale x 2 x double> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 2 x double> %splat, %a
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @recip_zero_steps_nxv4f64(<vscale x 4 x double> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m4, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 4 x double> %splat, %a
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @recip_zero_steps_nxv8f64(<vscale x 8 x double> %a) #1 {
; CHECK-LABEL: recip_zero_steps_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e64, m8, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = fdiv fast <vscale x 8 x double> %splat, %a
  ret <vscale x 8 x double> %1
}

attributes #0 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-div" }
attributes #1 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-div:0" }
