; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK-RV32
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK-RV64

define <2 x i32> @test_mul_combine(<2 x i32> %x) {
; CHECK-RV32-LABEL: test_mul_combine:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-RV32-NEXT:    vsra.vi v8, v8, 15
; CHECK-RV32-NEXT:    ret
;
; CHECK-RV64-LABEL: test_mul_combine:
; CHECK-RV64:       # %bb.0:
; CHECK-RV64-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-RV64-NEXT:    vsra.vi v8, v8, 15
; CHECK-RV64-NEXT:    ret
  %1 = lshr <2 x i32> %x, <i32 15, i32 15>
  %2 = and <2 x i32> %1, <i32 65537, i32 65537>
  %3 = mul <2 x i32> %2, <i32 65535, i32 65535>
  ret <2 x i32> %3
}
