; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v \
; RUN:   -mattr=+zfh,+zvfh -mattr=+d -verify-machineinstrs \
; RUN:   | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v \
; RUN:   -mattr=+zfh,+zvfh -mattr=+d -verify-machineinstrs \
; RUN:   | FileCheck %s

declare <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.iXLen(
  <vscale x 1 x i8>,
  <vscale x 1 x i8>*,
  iXLen);

define <vscale x 1 x i8> @intrinsic_vle_v_tu_nxv1i8_nxv1i8(<vscale x 1 x i8> %dummy, <vscale x 1 x i8> %0, <vscale x 1 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1i8_nxv1i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i8> @llvm.riscv.vle.nxv1i8.iXLen(
    <vscale x 1 x i8> %0,
    <vscale x 1 x i8>* %1,
    iXLen %2)

  ret <vscale x 1 x i8> %a
}

declare <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.iXLen(
  <vscale x 2 x i8>,
  <vscale x 2 x i8>*,
  iXLen);

define <vscale x 2 x i8> @intrinsic_vle_v_tu_nxv2i8_nxv2i8(<vscale x 2 x i8> %dummy, <vscale x 2 x i8> %0, <vscale x 2 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2i8_nxv2i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i8> @llvm.riscv.vle.nxv2i8.iXLen(
    <vscale x 2 x i8> %0,
    <vscale x 2 x i8>* %1,
    iXLen %2)

  ret <vscale x 2 x i8> %a
}

declare <vscale x 4 x i8> @llvm.riscv.vle.nxv4i8.iXLen(
  <vscale x 4 x i8>,
  <vscale x 4 x i8>*,
  iXLen);

define <vscale x 4 x i8> @intrinsic_vle_v_tu_nxv4i8_nxv4i8(<vscale x 4 x i8> %dummy, <vscale x 4 x i8> %0, <vscale x 4 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4i8_nxv4i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i8> @llvm.riscv.vle.nxv4i8.iXLen(
    <vscale x 4 x i8> %0,
    <vscale x 4 x i8>* %1,
    iXLen %2)

  ret <vscale x 4 x i8> %a
}

declare <vscale x 8 x i8> @llvm.riscv.vle.nxv8i8.iXLen(
  <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vle_v_tu_nxv8i8_nxv8i8(<vscale x 8 x i8> %dummy, <vscale x 8 x i8> %0, <vscale x 8 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8i8_nxv8i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i8> @llvm.riscv.vle.nxv8i8.iXLen(
    <vscale x 8 x i8> %0,
    <vscale x 8 x i8>* %1,
    iXLen %2)

  ret <vscale x 8 x i8> %a
}

declare <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.iXLen(
  <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vle_v_tu_nxv16i8_nxv16i8(<vscale x 16 x i8> %dummy, <vscale x 16 x i8> %0, <vscale x 16 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv16i8_nxv16i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i8> @llvm.riscv.vle.nxv16i8.iXLen(
    <vscale x 16 x i8> %0,
    <vscale x 16 x i8>* %1,
    iXLen %2)

  ret <vscale x 16 x i8> %a
}

declare <vscale x 32 x i8> @llvm.riscv.vle.nxv32i8.iXLen(
  <vscale x 32 x i8>,
  <vscale x 32 x i8>*,
  iXLen);

define <vscale x 32 x i8> @intrinsic_vle_v_tu_nxv32i8_nxv32i8(<vscale x 32 x i8> %dummy, <vscale x 32 x i8> %0, <vscale x 32 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv32i8_nxv32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x i8> @llvm.riscv.vle.nxv32i8.iXLen(
    <vscale x 32 x i8> %0,
    <vscale x 32 x i8>* %1,
    iXLen %2)

  ret <vscale x 32 x i8> %a
}

declare <vscale x 64 x i8> @llvm.riscv.vle.nxv64i8.iXLen(
  <vscale x 64 x i8>,
  <vscale x 64 x i8>*,
  iXLen);

define <vscale x 64 x i8> @intrinsic_vle_v_tu_nxv64i8_nxv64i8(<vscale x 64 x i8> %dummy, <vscale x 64 x i8> %0, <vscale x 64 x i8>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv64i8_nxv64i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 64 x i8> @llvm.riscv.vle.nxv64i8.iXLen(
    <vscale x 64 x i8> %0,
    <vscale x 64 x i8>* %1,
    iXLen %2)

  ret <vscale x 64 x i8> %a
}

declare <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.iXLen(
  <vscale x 1 x i16>,
  <vscale x 1 x i16>*,
  iXLen);

define <vscale x 1 x i16> @intrinsic_vle_v_tu_nxv1i16_nxv1i16(<vscale x 1 x i16> %dummy, <vscale x 1 x i16> %0, <vscale x 1 x i16>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1i16_nxv1i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i16> @llvm.riscv.vle.nxv1i16.iXLen(
    <vscale x 1 x i16> %0,
    <vscale x 1 x i16>* %1,
    iXLen %2)

  ret <vscale x 1 x i16> %a
}

declare <vscale x 2 x i16> @llvm.riscv.vle.nxv2i16.iXLen(
  <vscale x 2 x i16>,
  <vscale x 2 x i16>*,
  iXLen);

define <vscale x 2 x i16> @intrinsic_vle_v_tu_nxv2i16_nxv2i16(<vscale x 2 x i16> %dummy, <vscale x 2 x i16> %0, <vscale x 2 x i16>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2i16_nxv2i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf2, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i16> @llvm.riscv.vle.nxv2i16.iXLen(
    <vscale x 2 x i16> %0,
    <vscale x 2 x i16>* %1,
    iXLen %2)

  ret <vscale x 2 x i16> %a
}

declare <vscale x 4 x i16> @llvm.riscv.vle.nxv4i16.iXLen(
  <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vle_v_tu_nxv4i16_nxv4i16(<vscale x 4 x i16> %dummy, <vscale x 4 x i16> %0, <vscale x 4 x i16>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4i16_nxv4i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i16> @llvm.riscv.vle.nxv4i16.iXLen(
    <vscale x 4 x i16> %0,
    <vscale x 4 x i16>* %1,
    iXLen %2)

  ret <vscale x 4 x i16> %a
}

declare <vscale x 8 x i16> @llvm.riscv.vle.nxv8i16.iXLen(
  <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vle_v_tu_nxv8i16_nxv8i16(<vscale x 8 x i16> %dummy, <vscale x 8 x i16> %0, <vscale x 8 x i16>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8i16_nxv8i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i16> @llvm.riscv.vle.nxv8i16.iXLen(
    <vscale x 8 x i16> %0,
    <vscale x 8 x i16>* %1,
    iXLen %2)

  ret <vscale x 8 x i16> %a
}

declare <vscale x 16 x i16> @llvm.riscv.vle.nxv16i16.iXLen(
  <vscale x 16 x i16>,
  <vscale x 16 x i16>*,
  iXLen);

define <vscale x 16 x i16> @intrinsic_vle_v_tu_nxv16i16_nxv16i16(<vscale x 16 x i16> %dummy, <vscale x 16 x i16> %0, <vscale x 16 x i16>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv16i16_nxv16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i16> @llvm.riscv.vle.nxv16i16.iXLen(
    <vscale x 16 x i16> %0,
    <vscale x 16 x i16>* %1,
    iXLen %2)

  ret <vscale x 16 x i16> %a
}

declare <vscale x 32 x i16> @llvm.riscv.vle.nxv32i16.iXLen(
  <vscale x 32 x i16>,
  <vscale x 32 x i16>*,
  iXLen);

define <vscale x 32 x i16> @intrinsic_vle_v_tu_nxv32i16_nxv32i16(<vscale x 32 x i16> %dummy, <vscale x 32 x i16> %0, <vscale x 32 x i16>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv32i16_nxv32i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x i16> @llvm.riscv.vle.nxv32i16.iXLen(
    <vscale x 32 x i16> %0,
    <vscale x 32 x i16>* %1,
    iXLen %2)

  ret <vscale x 32 x i16> %a
}

declare <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.iXLen(
  <vscale x 1 x i32>,
  <vscale x 1 x i32>*,
  iXLen);

define <vscale x 1 x i32> @intrinsic_vle_v_tu_nxv1i32_nxv1i32(<vscale x 1 x i32> %dummy, <vscale x 1 x i32> %0, <vscale x 1 x i32>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1i32_nxv1i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i32> @llvm.riscv.vle.nxv1i32.iXLen(
    <vscale x 1 x i32> %0,
    <vscale x 1 x i32>* %1,
    iXLen %2)

  ret <vscale x 1 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.vle.nxv2i32.iXLen(
  <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vle_v_tu_nxv2i32_nxv2i32(<vscale x 2 x i32> %dummy, <vscale x 2 x i32> %0, <vscale x 2 x i32>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2i32_nxv2i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i32> @llvm.riscv.vle.nxv2i32.iXLen(
    <vscale x 2 x i32> %0,
    <vscale x 2 x i32>* %1,
    iXLen %2)

  ret <vscale x 2 x i32> %a
}

declare <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.iXLen(
  <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vle_v_tu_nxv4i32_nxv4i32(<vscale x 4 x i32> %dummy, <vscale x 4 x i32> %0, <vscale x 4 x i32>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4i32_nxv4i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i32> @llvm.riscv.vle.nxv4i32.iXLen(
    <vscale x 4 x i32> %0,
    <vscale x 4 x i32>* %1,
    iXLen %2)

  ret <vscale x 4 x i32> %a
}

declare <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.iXLen(
  <vscale x 8 x i32>,
  <vscale x 8 x i32>*,
  iXLen);

define <vscale x 8 x i32> @intrinsic_vle_v_tu_nxv8i32_nxv8i32(<vscale x 8 x i32> %dummy, <vscale x 8 x i32> %0, <vscale x 8 x i32>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8i32_nxv8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i32> @llvm.riscv.vle.nxv8i32.iXLen(
    <vscale x 8 x i32> %0,
    <vscale x 8 x i32>* %1,
    iXLen %2)

  ret <vscale x 8 x i32> %a
}

declare <vscale x 16 x i32> @llvm.riscv.vle.nxv16i32.iXLen(
  <vscale x 16 x i32>,
  <vscale x 16 x i32>*,
  iXLen);

define <vscale x 16 x i32> @intrinsic_vle_v_tu_nxv16i32_nxv16i32(<vscale x 16 x i32> %dummy, <vscale x 16 x i32> %0, <vscale x 16 x i32>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv16i32_nxv16i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x i32> @llvm.riscv.vle.nxv16i32.iXLen(
    <vscale x 16 x i32> %0,
    <vscale x 16 x i32>* %1,
    iXLen %2)

  ret <vscale x 16 x i32> %a
}

declare <vscale x 1 x i64> @llvm.riscv.vle.nxv1i64.iXLen(
  <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vle_v_tu_nxv1i64_nxv1i64(<vscale x 1 x i64> %dummy, <vscale x 1 x i64> %0, <vscale x 1 x i64>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1i64_nxv1i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x i64> @llvm.riscv.vle.nxv1i64.iXLen(
    <vscale x 1 x i64> %0,
    <vscale x 1 x i64>* %1,
    iXLen %2)

  ret <vscale x 1 x i64> %a
}

declare <vscale x 2 x i64> @llvm.riscv.vle.nxv2i64.iXLen(
  <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vle_v_tu_nxv2i64_nxv2i64(<vscale x 2 x i64> %dummy, <vscale x 2 x i64> %0, <vscale x 2 x i64>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2i64_nxv2i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x i64> @llvm.riscv.vle.nxv2i64.iXLen(
    <vscale x 2 x i64> %0,
    <vscale x 2 x i64>* %1,
    iXLen %2)

  ret <vscale x 2 x i64> %a
}

declare <vscale x 4 x i64> @llvm.riscv.vle.nxv4i64.iXLen(
  <vscale x 4 x i64>,
  <vscale x 4 x i64>*,
  iXLen);

define <vscale x 4 x i64> @intrinsic_vle_v_tu_nxv4i64_nxv4i64(<vscale x 4 x i64> %dummy, <vscale x 4 x i64> %0, <vscale x 4 x i64>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4i64_nxv4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x i64> @llvm.riscv.vle.nxv4i64.iXLen(
    <vscale x 4 x i64> %0,
    <vscale x 4 x i64>* %1,
    iXLen %2)

  ret <vscale x 4 x i64> %a
}

declare <vscale x 8 x i64> @llvm.riscv.vle.nxv8i64.iXLen(
  <vscale x 8 x i64>,
  <vscale x 8 x i64>*,
  iXLen);

define <vscale x 8 x i64> @intrinsic_vle_v_tu_nxv8i64_nxv8i64(<vscale x 8 x i64> %dummy, <vscale x 8 x i64> %0, <vscale x 8 x i64>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8i64_nxv8i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x i64> @llvm.riscv.vle.nxv8i64.iXLen(
    <vscale x 8 x i64> %0,
    <vscale x 8 x i64>* %1,
    iXLen %2)

  ret <vscale x 8 x i64> %a
}

declare <vscale x 1 x half> @llvm.riscv.vle.nxv1f16.iXLen(
  <vscale x 1 x half>,
  <vscale x 1 x half>*,
  iXLen);

define <vscale x 1 x half> @intrinsic_vle_v_tu_nxv1f16_nxv1f16(<vscale x 1 x half> %dummy, <vscale x 1 x half> %0, <vscale x 1 x half>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1f16_nxv1f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x half> @llvm.riscv.vle.nxv1f16.iXLen(
    <vscale x 1 x half> %0,
    <vscale x 1 x half>* %1,
    iXLen %2)

  ret <vscale x 1 x half> %a
}

declare <vscale x 2 x half> @llvm.riscv.vle.nxv2f16.iXLen(
  <vscale x 2 x half>,
  <vscale x 2 x half>*,
  iXLen);

define <vscale x 2 x half> @intrinsic_vle_v_tu_nxv2f16_nxv2f16(<vscale x 2 x half> %dummy, <vscale x 2 x half> %0, <vscale x 2 x half>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2f16_nxv2f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, mf2, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x half> @llvm.riscv.vle.nxv2f16.iXLen(
    <vscale x 2 x half> %0,
    <vscale x 2 x half>* %1,
    iXLen %2)

  ret <vscale x 2 x half> %a
}

declare <vscale x 4 x half> @llvm.riscv.vle.nxv4f16.iXLen(
  <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vle_v_tu_nxv4f16_nxv4f16(<vscale x 4 x half> %dummy, <vscale x 4 x half> %0, <vscale x 4 x half>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4f16_nxv4f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x half> @llvm.riscv.vle.nxv4f16.iXLen(
    <vscale x 4 x half> %0,
    <vscale x 4 x half>* %1,
    iXLen %2)

  ret <vscale x 4 x half> %a
}

declare <vscale x 8 x half> @llvm.riscv.vle.nxv8f16.iXLen(
  <vscale x 8 x half>,
  <vscale x 8 x half>*,
  iXLen);

define <vscale x 8 x half> @intrinsic_vle_v_tu_nxv8f16_nxv8f16(<vscale x 8 x half> %dummy, <vscale x 8 x half> %0, <vscale x 8 x half>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8f16_nxv8f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x half> @llvm.riscv.vle.nxv8f16.iXLen(
    <vscale x 8 x half> %0,
    <vscale x 8 x half>* %1,
    iXLen %2)

  ret <vscale x 8 x half> %a
}

declare <vscale x 16 x half> @llvm.riscv.vle.nxv16f16.iXLen(
  <vscale x 16 x half>,
  <vscale x 16 x half>*,
  iXLen);

define <vscale x 16 x half> @intrinsic_vle_v_tu_nxv16f16_nxv16f16(<vscale x 16 x half> %dummy, <vscale x 16 x half> %0, <vscale x 16 x half>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv16f16_nxv16f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x half> @llvm.riscv.vle.nxv16f16.iXLen(
    <vscale x 16 x half> %0,
    <vscale x 16 x half>* %1,
    iXLen %2)

  ret <vscale x 16 x half> %a
}

declare <vscale x 32 x half> @llvm.riscv.vle.nxv32f16.iXLen(
  <vscale x 32 x half>,
  <vscale x 32 x half>*,
  iXLen);

define <vscale x 32 x half> @intrinsic_vle_v_tu_nxv32f16_nxv32f16(<vscale x 32 x half> %dummy, <vscale x 32 x half> %0, <vscale x 32 x half>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv32f16_nxv32f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 32 x half> @llvm.riscv.vle.nxv32f16.iXLen(
    <vscale x 32 x half> %0,
    <vscale x 32 x half>* %1,
    iXLen %2)

  ret <vscale x 32 x half> %a
}

declare <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.iXLen(
  <vscale x 1 x float>,
  <vscale x 1 x float>*,
  iXLen);

define <vscale x 1 x float> @intrinsic_vle_v_tu_nxv1f32_nxv1f32(<vscale x 1 x float> %dummy, <vscale x 1 x float> %0, <vscale x 1 x float>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1f32_nxv1f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x float> @llvm.riscv.vle.nxv1f32.iXLen(
    <vscale x 1 x float> %0,
    <vscale x 1 x float>* %1,
    iXLen %2)

  ret <vscale x 1 x float> %a
}

declare <vscale x 2 x float> @llvm.riscv.vle.nxv2f32.iXLen(
  <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vle_v_tu_nxv2f32_nxv2f32(<vscale x 2 x float> %dummy, <vscale x 2 x float> %0, <vscale x 2 x float>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2f32_nxv2f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x float> @llvm.riscv.vle.nxv2f32.iXLen(
    <vscale x 2 x float> %0,
    <vscale x 2 x float>* %1,
    iXLen %2)

  ret <vscale x 2 x float> %a
}

declare <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.iXLen(
  <vscale x 4 x float>,
  <vscale x 4 x float>*,
  iXLen);

define <vscale x 4 x float> @intrinsic_vle_v_tu_nxv4f32_nxv4f32(<vscale x 4 x float> %dummy, <vscale x 4 x float> %0, <vscale x 4 x float>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4f32_nxv4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.iXLen(
    <vscale x 4 x float> %0,
    <vscale x 4 x float>* %1,
    iXLen %2)

  ret <vscale x 4 x float> %a
}

declare <vscale x 8 x float> @llvm.riscv.vle.nxv8f32.iXLen(
  <vscale x 8 x float>,
  <vscale x 8 x float>*,
  iXLen);

define <vscale x 8 x float> @intrinsic_vle_v_tu_nxv8f32_nxv8f32(<vscale x 8 x float> %dummy, <vscale x 8 x float> %0, <vscale x 8 x float>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8f32_nxv8f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x float> @llvm.riscv.vle.nxv8f32.iXLen(
    <vscale x 8 x float> %0,
    <vscale x 8 x float>* %1,
    iXLen %2)

  ret <vscale x 8 x float> %a
}

declare <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.iXLen(
  <vscale x 16 x float>,
  <vscale x 16 x float>*,
  iXLen);

define <vscale x 16 x float> @intrinsic_vle_v_tu_nxv16f32_nxv16f32(<vscale x 16 x float> %dummy, <vscale x 16 x float> %0, <vscale x 16 x float>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv16f32_nxv16f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 16 x float> @llvm.riscv.vle.nxv16f32.iXLen(
    <vscale x 16 x float> %0,
    <vscale x 16 x float>* %1,
    iXLen %2)

  ret <vscale x 16 x float> %a
}

declare <vscale x 1 x double> @llvm.riscv.vle.nxv1f64.iXLen(
  <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vle_v_tu_nxv1f64_nxv1f64(<vscale x 1 x double> %dummy, <vscale x 1 x double> %0, <vscale x 1 x double>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv1f64_nxv1f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 1 x double> @llvm.riscv.vle.nxv1f64.iXLen(
    <vscale x 1 x double> %0,
    <vscale x 1 x double>* %1,
    iXLen %2)

  ret <vscale x 1 x double> %a
}

declare <vscale x 2 x double> @llvm.riscv.vle.nxv2f64.iXLen(
  <vscale x 2 x double>,
  <vscale x 2 x double>*,
  iXLen);

define <vscale x 2 x double> @intrinsic_vle_v_tu_nxv2f64_nxv2f64(<vscale x 2 x double> %dummy, <vscale x 2 x double> %0, <vscale x 2 x double>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv2f64_nxv2f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, tu, ma
; CHECK-NEXT:    vmv2r.v v8, v10
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 2 x double> @llvm.riscv.vle.nxv2f64.iXLen(
    <vscale x 2 x double> %0,
    <vscale x 2 x double>* %1,
    iXLen %2)

  ret <vscale x 2 x double> %a
}

declare <vscale x 4 x double> @llvm.riscv.vle.nxv4f64.iXLen(
  <vscale x 4 x double>,
  <vscale x 4 x double>*,
  iXLen);

define <vscale x 4 x double> @intrinsic_vle_v_tu_nxv4f64_nxv4f64(<vscale x 4 x double> %dummy, <vscale x 4 x double> %0, <vscale x 4 x double>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv4f64_nxv4f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, tu, ma
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 4 x double> @llvm.riscv.vle.nxv4f64.iXLen(
    <vscale x 4 x double> %0,
    <vscale x 4 x double>* %1,
    iXLen %2)

  ret <vscale x 4 x double> %a
}

declare <vscale x 8 x double> @llvm.riscv.vle.nxv8f64.iXLen(
  <vscale x 8 x double>,
  <vscale x 8 x double>*,
  iXLen);

define <vscale x 8 x double> @intrinsic_vle_v_tu_nxv8f64_nxv8f64(<vscale x 8 x double> %dummy, <vscale x 8 x double> %0, <vscale x 8 x double>* %1, iXLen %2) nounwind {
; CHECK-LABEL: intrinsic_vle_v_tu_nxv8f64_nxv8f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, tu, ma
; CHECK-NEXT:    vmv8r.v v8, v16
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %a = call <vscale x 8 x double> @llvm.riscv.vle.nxv8f64.iXLen(
    <vscale x 8 x double> %0,
    <vscale x 8 x double>* %1,
    iXLen %2)

  ret <vscale x 8 x double> %a
}
