# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc %s -o - -mtriple=riscv64 -mattr=+v -run-pass=riscv-insert-writevxrm | FileCheck %s
---
name:  vaadd
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $v8, $v9, $x10

    ; CHECK-LABEL: name: vaadd
    ; CHECK: liveins: $v8, $v9, $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vr = COPY $v8
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vr = COPY $v9
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gprnox0 = COPY $x10
    ; CHECK-NEXT: dead $x0 = PseudoVSETVLI [[COPY2]], 69 /* e8, mf8, ta, mu */, implicit-def $vl, implicit-def $vtype
    ; CHECK-NEXT: [[SwapVXRMImm:%[0-9]+]]:gpr = SwapVXRMImm 2, implicit-def $vxrm, implicit $vxrm
    ; CHECK-NEXT: [[PseudoVAADD_VV_MF8_:%[0-9]+]]:vr = PseudoVAADD_VV_MF8 [[COPY]], [[COPY1]], 4, $noreg, 3 /* e8 */, implicit $vl, implicit $vtype, implicit $vxrm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVAADD_VV_MF8_]]
    ; CHECK-NEXT: WriteVXRM [[SwapVXRMImm]], implicit-def $vxrm
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:vr = COPY $v8
    %1:vr = COPY $v9
    %2:gprnox0 = COPY $x10
    dead $x0 = PseudoVSETVLI %2:gprnox0, 69, implicit-def $vl, implicit-def $vtype
    %3:vr = PseudoVAADD_VV_MF8 %0:vr, %1:vr, 2, $noreg, 3, implicit $vl, implicit $vtype
    $v8 = COPY %3:vr
    PseudoRET implicit $v8
...
---
name: vaadd_inlineasm
tracksRegLiveness: true
body: |
  bb.0.entry:
    liveins: $v8, $v9, $v10, $x10
    ; CHECK-LABEL: name: vaadd_inlineasm
    ; CHECK: liveins: $v8, $v9, $v10, $x10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gprnox0 = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vr = COPY $v10
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vr = COPY $v9
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vr = COPY $v8
    ; CHECK-NEXT: dead $x0 = PseudoVSETVLI [[COPY]], 69 /* e8, mf8, ta, mu */, implicit-def $vl, implicit-def $vtype
    ; CHECK-NEXT: [[SwapVXRMImm:%[0-9]+]]:gpr = SwapVXRMImm 2, implicit-def $vxrm, implicit $vxrm
    ; CHECK-NEXT: [[PseudoVAADD_VV_MF8_:%[0-9]+]]:vr = PseudoVAADD_VV_MF8 [[COPY3]], [[COPY2]], 4, $noreg, 3 /* e8 */, implicit $vl, implicit $vtype, implicit $vxrm
    ; CHECK-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */
    ; CHECK-NEXT: [[SwapVXRMImm1:%[0-9]+]]:gpr = SwapVXRMImm 0, implicit-def $vxrm, implicit $vxrm
    ; CHECK-NEXT: [[PseudoVAADD_VV_MF8_1:%[0-9]+]]:vr = PseudoVAADD_VV_MF8 killed [[PseudoVAADD_VV_MF8_]], [[COPY1]], 4, $noreg, 3 /* e8 */, implicit $vl, implicit $vtype, implicit $vxrm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVAADD_VV_MF8_1]]
    ; CHECK-NEXT: WriteVXRM [[SwapVXRMImm1]], implicit-def $vxrm
    ; CHECK-NEXT: PseudoRET implicit $v8
    %3:gprnox0 = COPY $x10
    %2:vr = COPY $v10
    %1:vr = COPY $v9
    %0:vr = COPY $v8
    dead $x0 = PseudoVSETVLI %3:gprnox0, 69, implicit-def $vl, implicit-def $vtype
    %4:vr = PseudoVAADD_VV_MF8 %0:vr, %1:vr, 2, $noreg, 3, implicit $vl, implicit $vtype
    INLINEASM &"", 1 /* sideeffect attdialect */
    %5:vr = PseudoVAADD_VV_MF8 killed %4:vr, %2:vr, 0, $noreg, 3, implicit $vl, implicit $vtype
    $v8 = COPY %5:vr
    PseudoRET implicit $v8
...
---
name:  fallthrough_basicblock
tracksRegLiveness: true
body:     |
  ; CHECK-LABEL: name: fallthrough_basicblock
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $v8, $v9, $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vr = COPY $v8
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vr = COPY $v9
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gprnox0 = COPY $x10
  ; CHECK-NEXT:   dead $x0 = PseudoVSETVLI [[COPY2]], 69 /* e8, mf8, ta, mu */, implicit-def $vl, implicit-def $vtype
  ; CHECK-NEXT:   [[SwapVXRMImm:%[0-9]+]]:gpr = SwapVXRMImm 2, implicit-def $vxrm, implicit $vxrm
  ; CHECK-NEXT:   [[PseudoVAADD_VV_MF8_:%[0-9]+]]:vr = PseudoVAADD_VV_MF8 [[COPY]], [[COPY1]], 4, $noreg, 3 /* e8 */, implicit $vl, implicit $vtype, implicit $vxrm
  ; CHECK-NEXT:   WriteVXRM [[SwapVXRMImm]], implicit-def $vxrm
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   $v8 = COPY [[PseudoVAADD_VV_MF8_]]
  ; CHECK-NEXT:   PseudoRET implicit $v8
  bb.0.entry:
    liveins: $v8, $v9, $x10

    %0:vr = COPY $v8
    %1:vr = COPY $v9
    %2:gprnox0 = COPY $x10
    dead $x0 = PseudoVSETVLI %2:gprnox0, 69, implicit-def $vl, implicit-def $vtype
    %3:vr = PseudoVAADD_VV_MF8 %0:vr, %1:vr, 2, $noreg, 3, implicit $vl, implicit $vtype
  bb.1:
    $v8 = COPY %3:vr
    PseudoRET implicit $v8
...
