; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;RUN: llc < %s -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=-1 | FileCheck %s

@global = external global double

define void @test_scalable_constant_pointer(<vscale x 4 x double> %arg, i32 zeroext %arg1) {
; CHECK-LABEL: test_scalable_constant_pointer:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    mv a1, a0
; CHECK-NEXT:    bltu a0, a2, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %bb
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:  .LBB0_2: # %bb
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    lui a0, %hi(global)
; CHECK-NEXT:    addi a0, a0, %lo(global)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
bb:
  call void @llvm.vp.scatter.nxv4f64.nxv4p0(<vscale x 4 x double> %arg, <vscale x 4 x ptr> shufflevector (<vscale x 4 x ptr> insertelement (<vscale x 4 x ptr> poison, ptr @global, i32 0), <vscale x 4 x ptr> poison, <vscale x 4 x i32> zeroinitializer), <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %arg1)
  ret void
}

define void @test_scalable_variable_pointer(ptr %arg, <vscale x 4 x double> %arg1, i32 zeroext %arg2) {
; CHECK-LABEL: test_scalable_variable_pointer:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    vsse64.v v8, (a0), zero
; CHECK-NEXT:    ret
bb:
  %tmp = insertelement <vscale x 4 x ptr> poison, ptr %arg, i32 0
  %tmp3 = shufflevector <vscale x 4 x ptr> %tmp, <vscale x 4 x ptr> poison, <vscale x 4 x i32> zeroinitializer
  call void @llvm.vp.scatter.nxv4f64.nxv4p0(<vscale x 4 x double> %arg1, <vscale x 4 x ptr> %tmp3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %arg2)
  ret void
}

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.vp.scatter.nxv4f64.nxv4p0(<vscale x 4 x double>, <vscale x 4 x ptr>, <vscale x 4 x i1>, i32) #0

define void @test_fixed_constant_pointer(<4 x double> %arg, i32 zeroext %arg1) {
; CHECK-LABEL: test_fixed_constant_pointer:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    mv a1, a0
; CHECK-NEXT:    bltu a0, a2, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %bb
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:  .LBB2_2: # %bb
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    lui a0, %hi(global)
; CHECK-NEXT:    addi a0, a0, %lo(global)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
bb:
  call void @llvm.vp.scatter.v4f64.v4p0(<4 x double> %arg, <4 x ptr> <ptr @global, ptr @global, ptr @global, ptr @global>, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, i32 %arg1)
  ret void
}

define void @test_fixed_variable_pointer(ptr %arg, <4 x double> %arg1, i32 zeroext %arg2) {
; CHECK-LABEL: test_fixed_variable_pointer:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    vsse64.v v8, (a0), zero
; CHECK-NEXT:    ret
bb:
  %tmp = insertelement <4 x ptr> poison, ptr %arg, i32 0
  %tmp3 = shufflevector <4 x ptr> %tmp, <4 x ptr> poison, <4 x i32> zeroinitializer
  call void @llvm.vp.scatter.v4f64.v4p0(<4 x double> %arg1, <4 x ptr> %tmp3, <4 x i1> <i1 true, i1 true, i1 true, i1 true>, i32 %arg2)
  ret void
}

; Function Attrs: argmemonly nocallback nofree nosync nounwind willreturn
declare void @llvm.vp.scatter.v4f64.v4p0(<4 x double>, <4 x ptr>, <4 x i1>, i32) #0

attributes #0 = { argmemonly nocallback nofree nosync nounwind willreturn }
