; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v -verify-machineinstrs | FileCheck %s

declare <1 x i8> @llvm.ushl.sat.v1i8(<1 x i8>, <1 x i8>)

define <1 x i8> @ushl_sat_v1i8(<1 x i8> %a, <1 x i8> %b) {
; CHECK-LABEL: ushl_sat_v1i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <1 x i8> @llvm.ushl.sat.v1i8(<1 x i8> %a, <1 x i8> %b)
  ret <1 x i8> %res
}

define <1 x i8> @ushl_sat_v1i8_splat(<1 x i8> %a, i8 %b) {
; CHECK-LABEL: ushl_sat_v1i8_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <1 x i8> undef, i8 %b, i64 0
  %splat = shufflevector <1 x i8> %vec, <1 x i8> poison, <1 x i32> zeroinitializer
  %res = call <1 x i8> @llvm.ushl.sat.v1i8(<1 x i8> %a, <1 x i8> %splat)
  ret <1 x i8> %res
}

declare <2 x i8> @llvm.ushl.sat.v2i8(<2 x i8>, <2 x i8>)

define <2 x i8> @ushl_sat_v2i8(<2 x i8> %a, <2 x i8> %b) {
; CHECK-LABEL: ushl_sat_v2i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <2 x i8> @llvm.ushl.sat.v2i8(<2 x i8> %a, <2 x i8> %b)
  ret <2 x i8> %res
}

define <2 x i8> @ushl_sat_v2i8_splat(<2 x i8> %a, i8 %b) {
; CHECK-LABEL: ushl_sat_v2i8_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <2 x i8> undef, i8 %b, i64 0
  %splat = shufflevector <2 x i8> %vec, <2 x i8> poison, <2 x i32> zeroinitializer
  %res = call <2 x i8> @llvm.ushl.sat.v2i8(<2 x i8> %a, <2 x i8> %splat)
  ret <2 x i8> %res
}

declare <4 x i8> @llvm.ushl.sat.v4i8(<4 x i8>, <4 x i8>)

define <4 x i8> @ushl_sat_v4i8(<4 x i8> %a, <4 x i8> %b) {
; CHECK-LABEL: ushl_sat_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <4 x i8> @llvm.ushl.sat.v4i8(<4 x i8> %a, <4 x i8> %b)
  ret <4 x i8> %res
}

define <4 x i8> @ushl_sat_v4i8_splat(<4 x i8> %a, i8 %b) {
; CHECK-LABEL: ushl_sat_v4i8_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <4 x i8> undef, i8 %b, i64 0
  %splat = shufflevector <4 x i8> %vec, <4 x i8> poison, <4 x i32> zeroinitializer
  %res = call <4 x i8> @llvm.ushl.sat.v4i8(<4 x i8> %a, <4 x i8> %splat)
  ret <4 x i8> %res
}

declare <8 x i8> @llvm.ushl.sat.v8i8(<8 x i8>, <8 x i8>)

define <8 x i8> @ushl_sat_v8i8(<8 x i8> %a, <8 x i8> %b) {
; CHECK-LABEL: ushl_sat_v8i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <8 x i8> @llvm.ushl.sat.v8i8(<8 x i8> %a, <8 x i8> %b)
  ret <8 x i8> %res
}

define <8 x i8> @ushl_sat_v8i8_splat(<8 x i8> %a, i8 %b) {
; CHECK-LABEL: ushl_sat_v8i8_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <8 x i8> undef, i8 %b, i64 0
  %splat = shufflevector <8 x i8> %vec, <8 x i8> poison, <8 x i32> zeroinitializer
  %res = call <8 x i8> @llvm.ushl.sat.v8i8(<8 x i8> %a, <8 x i8> %splat)
  ret <8 x i8> %res
}

declare <16 x i8> @llvm.ushl.sat.v16i8(<16 x i8>, <16 x i8>)

define <16 x i8> @ushl_sat_v16i8(<16 x i8> %a, <16 x i8> %b) {
; CHECK-LABEL: ushl_sat_v16i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <16 x i8> @llvm.ushl.sat.v16i8(<16 x i8> %a, <16 x i8> %b)
  ret <16 x i8> %res
}

define <16 x i8> @ushl_sat_v16i8_splat(<16 x i8> %a, i8 %b) {
; CHECK-LABEL: ushl_sat_v16i8_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vwmulu.vx v10, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v10, 0
; CHECK-NEXT:    ret
  %vec = insertelement <16 x i8> undef, i8 %b, i64 0
  %splat = shufflevector <16 x i8> %vec, <16 x i8> poison, <16 x i32> zeroinitializer
  %res = call <16 x i8> @llvm.ushl.sat.v16i8(<16 x i8> %a, <16 x i8> %splat)
  ret <16 x i8> %res
}

declare <32 x i8> @llvm.ushl.sat.v32i8(<32 x i8>, <32 x i8>)

define <32 x i8> @ushl_sat_v32i8(<32 x i8> %a, <32 x i8> %b) {
; CHECK-LABEL: ushl_sat_v32i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    vsll.vv v12, v8, v10
; CHECK-NEXT:    vsrl.vv v10, v12, v10
; CHECK-NEXT:    vmsne.vv v0, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v12, -1, v0
; CHECK-NEXT:    ret
  %res = call <32 x i8> @llvm.ushl.sat.v32i8(<32 x i8> %a, <32 x i8> %b)
  ret <32 x i8> %res
}

define <32 x i8> @ushl_sat_v32i8_splat(<32 x i8> %a, i8 %b) {
; CHECK-LABEL: ushl_sat_v32i8_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vwmulu.vx v12, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v12, 0
; CHECK-NEXT:    ret
  %vec = insertelement <32 x i8> undef, i8 %b, i64 0
  %splat = shufflevector <32 x i8> %vec, <32 x i8> poison, <32 x i32> zeroinitializer
  %res = call <32 x i8> @llvm.ushl.sat.v32i8(<32 x i8> %a, <32 x i8> %splat)
  ret <32 x i8> %res
}

declare <1 x i16> @llvm.ushl.sat.v1i16(<1 x i16>, <1 x i16>)

define <1 x i16> @ushl_sat_v1i16(<1 x i16> %a, <1 x i16> %b) {
; CHECK-LABEL: ushl_sat_v1i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <1 x i16> @llvm.ushl.sat.v1i16(<1 x i16> %a, <1 x i16> %b)
  ret <1 x i16> %res
}

define <1 x i16> @ushl_sat_v1i16_splat(<1 x i16> %a, i16 %b) {
; CHECK-LABEL: ushl_sat_v1i16_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <1 x i16> undef, i16 %b, i64 0
  %splat = shufflevector <1 x i16> %vec, <1 x i16> poison, <1 x i32> zeroinitializer
  %res = call <1 x i16> @llvm.ushl.sat.v1i16(<1 x i16> %a, <1 x i16> %splat)
  ret <1 x i16> %res
}

declare <2 x i16> @llvm.ushl.sat.v2i16(<2 x i16>, <2 x i16>)

define <2 x i16> @ushl_sat_v2i16(<2 x i16> %a, <2 x i16> %b) {
; CHECK-LABEL: ushl_sat_v2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <2 x i16> @llvm.ushl.sat.v2i16(<2 x i16> %a, <2 x i16> %b)
  ret <2 x i16> %res
}

define <2 x i16> @ushl_sat_v2i16_splat(<2 x i16> %a, i16 %b) {
; CHECK-LABEL: ushl_sat_v2i16_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <2 x i16> undef, i16 %b, i64 0
  %splat = shufflevector <2 x i16> %vec, <2 x i16> poison, <2 x i32> zeroinitializer
  %res = call <2 x i16> @llvm.ushl.sat.v2i16(<2 x i16> %a, <2 x i16> %splat)
  ret <2 x i16> %res
}

declare <4 x i16> @llvm.ushl.sat.v4i16(<4 x i16>, <4 x i16>)

define <4 x i16> @ushl_sat_v4i16(<4 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: ushl_sat_v4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <4 x i16> @llvm.ushl.sat.v4i16(<4 x i16> %a, <4 x i16> %b)
  ret <4 x i16> %res
}

define <4 x i16> @ushl_sat_v4i16_splat(<4 x i16> %a, i16 %b) {
; CHECK-LABEL: ushl_sat_v4i16_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <4 x i16> undef, i16 %b, i64 0
  %splat = shufflevector <4 x i16> %vec, <4 x i16> poison, <4 x i32> zeroinitializer
  %res = call <4 x i16> @llvm.ushl.sat.v4i16(<4 x i16> %a, <4 x i16> %splat)
  ret <4 x i16> %res
}

declare <8 x i16> @llvm.ushl.sat.v8i16(<8 x i16>, <8 x i16>)

define <8 x i16> @ushl_sat_v8i16(<8 x i16> %a, <8 x i16> %b) {
; CHECK-LABEL: ushl_sat_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <8 x i16> @llvm.ushl.sat.v8i16(<8 x i16> %a, <8 x i16> %b)
  ret <8 x i16> %res
}

define <8 x i16> @ushl_sat_v8i16_splat(<8 x i16> %a, i16 %b) {
; CHECK-LABEL: ushl_sat_v8i16_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vwmulu.vx v10, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v10, 0
; CHECK-NEXT:    ret
  %vec = insertelement <8 x i16> undef, i16 %b, i64 0
  %splat = shufflevector <8 x i16> %vec, <8 x i16> poison, <8 x i32> zeroinitializer
  %res = call <8 x i16> @llvm.ushl.sat.v8i16(<8 x i16> %a, <8 x i16> %splat)
  ret <8 x i16> %res
}

declare <16 x i16> @llvm.ushl.sat.v16i16(<16 x i16>, <16 x i16>)

define <16 x i16> @ushl_sat_v16i16(<16 x i16> %a, <16 x i16> %b) {
; CHECK-LABEL: ushl_sat_v16i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vsll.vv v12, v8, v10
; CHECK-NEXT:    vsrl.vv v10, v12, v10
; CHECK-NEXT:    vmsne.vv v0, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v12, -1, v0
; CHECK-NEXT:    ret
  %res = call <16 x i16> @llvm.ushl.sat.v16i16(<16 x i16> %a, <16 x i16> %b)
  ret <16 x i16> %res
}

define <16 x i16> @ushl_sat_v16i16_splat(<16 x i16> %a, i16 %b) {
; CHECK-LABEL: ushl_sat_v16i16_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vwmulu.vx v12, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v12, 0
; CHECK-NEXT:    ret
  %vec = insertelement <16 x i16> undef, i16 %b, i64 0
  %splat = shufflevector <16 x i16> %vec, <16 x i16> poison, <16 x i32> zeroinitializer
  %res = call <16 x i16> @llvm.ushl.sat.v16i16(<16 x i16> %a, <16 x i16> %splat)
  ret <16 x i16> %res
}

declare <1 x i32> @llvm.ushl.sat.v1i32(<1 x i32>, <1 x i32>)

define <1 x i32> @ushl_sat_v1i32(<1 x i32> %a, <1 x i32> %b) {
; CHECK-LABEL: ushl_sat_v1i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <1 x i32> @llvm.ushl.sat.v1i32(<1 x i32> %a, <1 x i32> %b)
  ret <1 x i32> %res
}

define <1 x i32> @ushl_sat_v1i32_splat(<1 x i32> %a, i32 %b) {
; CHECK-LABEL: ushl_sat_v1i32_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <1 x i32> undef, i32 %b, i64 0
  %splat = shufflevector <1 x i32> %vec, <1 x i32> poison, <1 x i32> zeroinitializer
  %res = call <1 x i32> @llvm.ushl.sat.v1i32(<1 x i32> %a, <1 x i32> %splat)
  ret <1 x i32> %res
}

declare <2 x i32> @llvm.ushl.sat.v2i32(<2 x i32>, <2 x i32>)

define <2 x i32> @ushl_sat_v2i32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: ushl_sat_v2i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <2 x i32> @llvm.ushl.sat.v2i32(<2 x i32> %a, <2 x i32> %b)
  ret <2 x i32> %res
}

define <2 x i32> @ushl_sat_v2i32_splat(<2 x i32> %a, i32 %b) {
; CHECK-LABEL: ushl_sat_v2i32_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vwmulu.vx v9, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v9, 0
; CHECK-NEXT:    ret
  %vec = insertelement <2 x i32> undef, i32 %b, i64 0
  %splat = shufflevector <2 x i32> %vec, <2 x i32> poison, <2 x i32> zeroinitializer
  %res = call <2 x i32> @llvm.ushl.sat.v2i32(<2 x i32> %a, <2 x i32> %splat)
  ret <2 x i32> %res
}

declare <4 x i32> @llvm.ushl.sat.v4i32(<4 x i32>, <4 x i32>)

define <4 x i32> @ushl_sat_v4i32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: ushl_sat_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <4 x i32> @llvm.ushl.sat.v4i32(<4 x i32> %a, <4 x i32> %b)
  ret <4 x i32> %res
}

define <4 x i32> @ushl_sat_v4i32_splat(<4 x i32> %a, i32 %b) {
; CHECK-LABEL: ushl_sat_v4i32_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vwmulu.vx v10, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v10, 0
; CHECK-NEXT:    ret
  %vec = insertelement <4 x i32> undef, i32 %b, i64 0
  %splat = shufflevector <4 x i32> %vec, <4 x i32> poison, <4 x i32> zeroinitializer
  %res = call <4 x i32> @llvm.ushl.sat.v4i32(<4 x i32> %a, <4 x i32> %splat)
  ret <4 x i32> %res
}

declare <8 x i32> @llvm.ushl.sat.v8i32(<8 x i32>, <8 x i32>)

define <8 x i32> @ushl_sat_v8i32(<8 x i32> %a, <8 x i32> %b) {
; CHECK-LABEL: ushl_sat_v8i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vsll.vv v12, v8, v10
; CHECK-NEXT:    vsrl.vv v10, v12, v10
; CHECK-NEXT:    vmsne.vv v0, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v12, -1, v0
; CHECK-NEXT:    ret
  %res = call <8 x i32> @llvm.ushl.sat.v8i32(<8 x i32> %a, <8 x i32> %b)
  ret <8 x i32> %res
}

define <8 x i32> @ushl_sat_v8i32_splat(<8 x i32> %a, i32 %b) {
; CHECK-LABEL: ushl_sat_v8i32_splat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sll a0, a1, a0
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vwmulu.vx v12, v8, a0
; CHECK-NEXT:    vnclipu.wi v8, v12, 0
; CHECK-NEXT:    ret
  %vec = insertelement <8 x i32> undef, i32 %b, i64 0
  %splat = shufflevector <8 x i32> %vec, <8 x i32> poison, <8 x i32> zeroinitializer
  %res = call <8 x i32> @llvm.ushl.sat.v8i32(<8 x i32> %a, <8 x i32> %splat)
  ret <8 x i32> %res
}

declare <1 x i64> @llvm.ushl.sat.v1i64(<1 x i64>, <1 x i64>)

define <1 x i64> @ushl_sat_v1i64(<1 x i64> %a, <1 x i64> %b) {
; CHECK-LABEL: ushl_sat_v1i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <1 x i64> @llvm.ushl.sat.v1i64(<1 x i64> %a, <1 x i64> %b)
  ret <1 x i64> %res
}

declare <2 x i64> @llvm.ushl.sat.v2i64(<2 x i64>, <2 x i64>)

define <2 x i64> @ushl_sat_v2i64(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: ushl_sat_v2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vv v10, v8, v9
; CHECK-NEXT:    vsrl.vv v9, v10, v9
; CHECK-NEXT:    vmsne.vv v0, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v10, -1, v0
; CHECK-NEXT:    ret
  %res = call <2 x i64> @llvm.ushl.sat.v2i64(<2 x i64> %a, <2 x i64> %b)
  ret <2 x i64> %res
}

declare <4 x i64> @llvm.ushl.sat.v4i64(<4 x i64>, <4 x i64>)

define <4 x i64> @ushl_sat_v4i64(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: ushl_sat_v4i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vsll.vv v12, v8, v10
; CHECK-NEXT:    vsrl.vv v10, v12, v10
; CHECK-NEXT:    vmsne.vv v0, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v12, -1, v0
; CHECK-NEXT:    ret
  %res = call <4 x i64> @llvm.ushl.sat.v4i64(<4 x i64> %a, <4 x i64> %b)
  ret <4 x i64> %res
}
