; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK,RV64

; Integers

define <vscale x 96 x i1> @vector_interleave_nxv96i1_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b, <vscale x 16 x i1> %c, <vscale x 16 x i1> %d, <vscale x 16 x i1> %e, <vscale x 16 x i1> %f) nounwind {
; CHECK-LABEL: vector_interleave_nxv96i1_nxv16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 12
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmv.v.i v20, 0
; CHECK-NEXT:    vmerge.vim v14, v20, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vim v22, v20, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmv1r.v v16, v23
; CHECK-NEXT:    vmerge.vim v8, v20, 1, v0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 6
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vmv1r.v v17, v9
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vmerge.vim v24, v20, 1, v0
; CHECK-NEXT:    addi a4, sp, 16
; CHECK-NEXT:    vmv1r.v v18, v25
; CHECK-NEXT:    vmv1r.v v0, v11
; CHECK-NEXT:    vmerge.vim v26, v20, 1, v0
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vmv1r.v v19, v27
; CHECK-NEXT:    vmv1r.v v0, v12
; CHECK-NEXT:    vmerge.vim v10, v20, 1, v0
; CHECK-NEXT:    add a2, a0, a1
; CHECK-NEXT:    vmv1r.v v20, v11
; CHECK-NEXT:    vsetvli a3, zero, e8, m1, ta, ma
; CHECK-NEXT:    vsseg6e8.v v15, (a0)
; CHECK-NEXT:    vmv1r.v v15, v22
; CHECK-NEXT:    add a5, a4, a1
; CHECK-NEXT:    vmv1r.v v16, v8
; CHECK-NEXT:    srli a3, a1, 1
; CHECK-NEXT:    vmv1r.v v17, v24
; CHECK-NEXT:    add a6, a5, a1
; CHECK-NEXT:    vmv1r.v v18, v26
; CHECK-NEXT:    add a7, a2, a1
; CHECK-NEXT:    vmv1r.v v19, v10
; CHECK-NEXT:    vsseg6e8.v v14, (a4)
; CHECK-NEXT:    vl1r.v v8, (a0)
; CHECK-NEXT:    add a0, a6, a1
; CHECK-NEXT:    vl1r.v v10, (a6)
; CHECK-NEXT:    add a6, a7, a1
; CHECK-NEXT:    vl1r.v v12, (a4)
; CHECK-NEXT:    add a4, a0, a1
; CHECK-NEXT:    vl1r.v v14, (a7)
; CHECK-NEXT:    add a7, a6, a1
; CHECK-NEXT:    vl1r.v v16, (a4)
; CHECK-NEXT:    add a4, a4, a1
; CHECK-NEXT:    vl1r.v v18, (a7)
; CHECK-NEXT:    add a7, a7, a1
; CHECK-NEXT:    srli a1, a1, 2
; CHECK-NEXT:    vl1r.v v9, (a2)
; CHECK-NEXT:    vl1r.v v17, (a4)
; CHECK-NEXT:    vl1r.v v11, (a0)
; CHECK-NEXT:    vl1r.v v13, (a5)
; CHECK-NEXT:    vl1r.v v19, (a7)
; CHECK-NEXT:    vl1r.v v15, (a6)
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmsne.vi v20, v8, 0
; CHECK-NEXT:    vmsne.vi v9, v16, 0
; CHECK-NEXT:    vmsne.vi v10, v10, 0
; CHECK-NEXT:    vmsne.vi v0, v12, 0
; CHECK-NEXT:    vmsne.vi v11, v18, 0
; CHECK-NEXT:    vmsne.vi v8, v14, 0
; CHECK-NEXT:    vsetvli a0, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vx v9, v20, a1
; CHECK-NEXT:    vslideup.vx v0, v10, a1
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v9, a3
; CHECK-NEXT:    vsetvli a0, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vx v8, v11, a1
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 12
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 96 x i1> @llvm.vector.interleave6.nxv96i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b, <vscale x 16 x i1> %c, <vscale x 16 x i1> %d, <vscale x 16 x i1> %e, <vscale x 16 x i1> %f)
  ret <vscale x 96 x i1> %res
}

declare <vscale x 96 x i1> @llvm.vector.interleave6.nxv96i1(<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>)

define <vscale x 96 x i8> @vector_interleave_nxv96i8_nxv16i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %b, <vscale x 16 x i8> %c, <vscale x 16 x i8> %d, <vscale x 16 x i8> %e, <vscale x 16 x i8> %f) nounwind {
; RV32-LABEL: vector_interleave_nxv96i8_nxv16i8:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v14
; RV32-NEXT:    vmv2r.v v22, v12
; RV32-NEXT:    vmv2r.v v24, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a0, 6
; RV32-NEXT:    mul a1, a1, a0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    vmv1r.v v10, v25
; RV32-NEXT:    vmv1r.v v11, v23
; RV32-NEXT:    vmv1r.v v12, v21
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv1r.v v13, v17
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv1r.v v14, v19
; RV32-NEXT:    vsseg6e8.v v9, (a1)
; RV32-NEXT:    vmv1r.v v9, v24
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vmv1r.v v10, v22
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v11, v20
; RV32-NEXT:    add a4, a3, a2
; RV32-NEXT:    vmv1r.v v12, v16
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v13, v18
; RV32-NEXT:    vsseg6e8.v v8, (a0)
; RV32-NEXT:    vl1r.v v14, (a1)
; RV32-NEXT:    add a1, a6, a2
; RV32-NEXT:    vl1r.v v15, (a5)
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vl1r.v v18, (a5)
; RV32-NEXT:    add a5, a5, a2
; RV32-NEXT:    vl1r.v v19, (a5)
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vl1r.v v16, (a6)
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vl1r.v v12, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1r.v v13, (a6)
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li a7, 12
; RV32-NEXT:    mul a6, a6, a7
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 64
; RV32-NEXT:    vl1r.v v17, (a1)
; RV32-NEXT:    vl1r.v v10, (a4)
; RV32-NEXT:    vl1r.v v11, (a5)
; RV32-NEXT:    vl1r.v v8, (a0)
; RV32-NEXT:    vl1r.v v9, (a3)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a6, a2
; RV32-NEXT:    vs4r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a6)
; RV32-NEXT:    vl8r.v v16, (a2)
; RV32-NEXT:    vl8r.v v8, (a6)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv96i8_nxv16i8:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v14
; RV64-NEXT:    vmv2r.v v22, v12
; RV64-NEXT:    vmv2r.v v24, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a0, 6
; RV64-NEXT:    mul a1, a1, a0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    vmv1r.v v10, v25
; RV64-NEXT:    vmv1r.v v11, v23
; RV64-NEXT:    vmv1r.v v12, v21
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv1r.v v13, v17
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv1r.v v14, v19
; RV64-NEXT:    vsseg6e8.v v9, (a1)
; RV64-NEXT:    vmv1r.v v9, v24
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vmv1r.v v10, v22
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v11, v20
; RV64-NEXT:    add a4, a3, a2
; RV64-NEXT:    vmv1r.v v12, v16
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v13, v18
; RV64-NEXT:    vsseg6e8.v v8, (a0)
; RV64-NEXT:    vl1r.v v14, (a1)
; RV64-NEXT:    add a1, a6, a2
; RV64-NEXT:    vl1r.v v15, (a5)
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vl1r.v v18, (a5)
; RV64-NEXT:    add a5, a5, a2
; RV64-NEXT:    vl1r.v v19, (a5)
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vl1r.v v16, (a6)
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vl1r.v v12, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1r.v v13, (a6)
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li a7, 12
; RV64-NEXT:    mul a6, a6, a7
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 64
; RV64-NEXT:    vl1r.v v17, (a1)
; RV64-NEXT:    vl1r.v v10, (a4)
; RV64-NEXT:    vl1r.v v11, (a5)
; RV64-NEXT:    vl1r.v v8, (a0)
; RV64-NEXT:    vl1r.v v9, (a3)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a6, a2
; RV64-NEXT:    vs4r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a6)
; RV64-NEXT:    vl8r.v v16, (a2)
; RV64-NEXT:    vl8r.v v8, (a6)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 96 x i8> @llvm.vector.interleave6.nxv96i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %b, <vscale x 16 x i8> %c, <vscale x 16 x i8> %d, <vscale x 16 x i8> %e, <vscale x 16 x i8> %f)
  ret <vscale x 96 x i8> %res
}

declare <vscale x 96 x i8> @llvm.vector.interleave6.nxv96i8(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)

define <vscale x 48 x i16> @vector_interleave_nxv48i16_nxv8i16(<vscale x 8 x i16> %a, <vscale x 8 x i16> %b, <vscale x 8 x i16> %c, <vscale x 8 x i16> %d, <vscale x 8 x i16> %e, <vscale x 8 x i16> %f) nounwind {
; RV32-LABEL: vector_interleave_nxv48i16_nxv8i16:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v14
; RV32-NEXT:    vmv2r.v v22, v12
; RV32-NEXT:    vmv2r.v v24, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a0, 6
; RV32-NEXT:    mul a1, a1, a0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    vmv1r.v v10, v25
; RV32-NEXT:    vmv1r.v v11, v23
; RV32-NEXT:    vmv1r.v v12, v21
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv1r.v v13, v17
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv1r.v v14, v19
; RV32-NEXT:    vsseg6e16.v v9, (a1)
; RV32-NEXT:    vmv1r.v v9, v24
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vmv1r.v v10, v22
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v11, v20
; RV32-NEXT:    add a4, a3, a2
; RV32-NEXT:    vmv1r.v v12, v16
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v13, v18
; RV32-NEXT:    vsseg6e16.v v8, (a0)
; RV32-NEXT:    vl1re16.v v14, (a1)
; RV32-NEXT:    add a1, a6, a2
; RV32-NEXT:    vl1re16.v v15, (a5)
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vl1re16.v v18, (a5)
; RV32-NEXT:    add a5, a5, a2
; RV32-NEXT:    vl1re16.v v19, (a5)
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vl1re16.v v16, (a6)
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vl1re16.v v12, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re16.v v13, (a6)
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li a7, 12
; RV32-NEXT:    mul a6, a6, a7
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 64
; RV32-NEXT:    vl1re16.v v17, (a1)
; RV32-NEXT:    vl1re16.v v10, (a4)
; RV32-NEXT:    vl1re16.v v11, (a5)
; RV32-NEXT:    vl1re16.v v8, (a0)
; RV32-NEXT:    vl1re16.v v9, (a3)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a6, a2
; RV32-NEXT:    vs4r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a6)
; RV32-NEXT:    vl8re16.v v16, (a2)
; RV32-NEXT:    vl8re16.v v8, (a6)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv48i16_nxv8i16:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v14
; RV64-NEXT:    vmv2r.v v22, v12
; RV64-NEXT:    vmv2r.v v24, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a0, 6
; RV64-NEXT:    mul a1, a1, a0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    vmv1r.v v10, v25
; RV64-NEXT:    vmv1r.v v11, v23
; RV64-NEXT:    vmv1r.v v12, v21
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv1r.v v13, v17
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv1r.v v14, v19
; RV64-NEXT:    vsseg6e16.v v9, (a1)
; RV64-NEXT:    vmv1r.v v9, v24
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vmv1r.v v10, v22
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v11, v20
; RV64-NEXT:    add a4, a3, a2
; RV64-NEXT:    vmv1r.v v12, v16
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v13, v18
; RV64-NEXT:    vsseg6e16.v v8, (a0)
; RV64-NEXT:    vl1re16.v v14, (a1)
; RV64-NEXT:    add a1, a6, a2
; RV64-NEXT:    vl1re16.v v15, (a5)
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vl1re16.v v18, (a5)
; RV64-NEXT:    add a5, a5, a2
; RV64-NEXT:    vl1re16.v v19, (a5)
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vl1re16.v v16, (a6)
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vl1re16.v v12, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re16.v v13, (a6)
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li a7, 12
; RV64-NEXT:    mul a6, a6, a7
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 64
; RV64-NEXT:    vl1re16.v v17, (a1)
; RV64-NEXT:    vl1re16.v v10, (a4)
; RV64-NEXT:    vl1re16.v v11, (a5)
; RV64-NEXT:    vl1re16.v v8, (a0)
; RV64-NEXT:    vl1re16.v v9, (a3)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a6, a2
; RV64-NEXT:    vs4r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a6)
; RV64-NEXT:    vl8re16.v v16, (a2)
; RV64-NEXT:    vl8re16.v v8, (a6)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 48 x i16> @llvm.vector.interleave6.nxv48i16(<vscale x 8 x i16> %a, <vscale x 8 x i16> %b, <vscale x 8 x i16> %c, <vscale x 8 x i16> %d, <vscale x 8 x i16> %e, <vscale x 8 x i16> %f)
  ret <vscale x 48 x i16> %res
}

declare <vscale x 48 x i16> @llvm.vector.interleave6.nxv48i16(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>)

define <vscale x 24 x i32> @vector_interleave_nxv24i32_nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, <vscale x 4 x i32> %d, <vscale x 4 x i32> %e, <vscale x 4 x i32> %f) nounwind {
; RV32-LABEL: vector_interleave_nxv24i32_nxv4i32:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v14
; RV32-NEXT:    vmv2r.v v22, v12
; RV32-NEXT:    vmv2r.v v24, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a0, 6
; RV32-NEXT:    mul a1, a1, a0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    vmv1r.v v10, v25
; RV32-NEXT:    vmv1r.v v11, v23
; RV32-NEXT:    vmv1r.v v12, v21
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv1r.v v13, v17
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv1r.v v14, v19
; RV32-NEXT:    vsseg6e32.v v9, (a1)
; RV32-NEXT:    vmv1r.v v9, v24
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vmv1r.v v10, v22
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v11, v20
; RV32-NEXT:    add a4, a3, a2
; RV32-NEXT:    vmv1r.v v12, v16
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v13, v18
; RV32-NEXT:    vsseg6e32.v v8, (a0)
; RV32-NEXT:    vl1re32.v v14, (a1)
; RV32-NEXT:    add a1, a6, a2
; RV32-NEXT:    vl1re32.v v15, (a5)
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vl1re32.v v18, (a5)
; RV32-NEXT:    add a5, a5, a2
; RV32-NEXT:    vl1re32.v v19, (a5)
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vl1re32.v v16, (a6)
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vl1re32.v v12, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re32.v v13, (a6)
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li a7, 12
; RV32-NEXT:    mul a6, a6, a7
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 64
; RV32-NEXT:    vl1re32.v v17, (a1)
; RV32-NEXT:    vl1re32.v v10, (a4)
; RV32-NEXT:    vl1re32.v v11, (a5)
; RV32-NEXT:    vl1re32.v v8, (a0)
; RV32-NEXT:    vl1re32.v v9, (a3)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a6, a2
; RV32-NEXT:    vs4r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a6)
; RV32-NEXT:    vl8re32.v v16, (a2)
; RV32-NEXT:    vl8re32.v v8, (a6)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv24i32_nxv4i32:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v14
; RV64-NEXT:    vmv2r.v v22, v12
; RV64-NEXT:    vmv2r.v v24, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a0, 6
; RV64-NEXT:    mul a1, a1, a0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    vmv1r.v v10, v25
; RV64-NEXT:    vmv1r.v v11, v23
; RV64-NEXT:    vmv1r.v v12, v21
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv1r.v v13, v17
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv1r.v v14, v19
; RV64-NEXT:    vsseg6e32.v v9, (a1)
; RV64-NEXT:    vmv1r.v v9, v24
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vmv1r.v v10, v22
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v11, v20
; RV64-NEXT:    add a4, a3, a2
; RV64-NEXT:    vmv1r.v v12, v16
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v13, v18
; RV64-NEXT:    vsseg6e32.v v8, (a0)
; RV64-NEXT:    vl1re32.v v14, (a1)
; RV64-NEXT:    add a1, a6, a2
; RV64-NEXT:    vl1re32.v v15, (a5)
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vl1re32.v v18, (a5)
; RV64-NEXT:    add a5, a5, a2
; RV64-NEXT:    vl1re32.v v19, (a5)
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vl1re32.v v16, (a6)
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vl1re32.v v12, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re32.v v13, (a6)
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li a7, 12
; RV64-NEXT:    mul a6, a6, a7
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 64
; RV64-NEXT:    vl1re32.v v17, (a1)
; RV64-NEXT:    vl1re32.v v10, (a4)
; RV64-NEXT:    vl1re32.v v11, (a5)
; RV64-NEXT:    vl1re32.v v8, (a0)
; RV64-NEXT:    vl1re32.v v9, (a3)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a6, a2
; RV64-NEXT:    vs4r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a6)
; RV64-NEXT:    vl8re32.v v16, (a2)
; RV64-NEXT:    vl8re32.v v8, (a6)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 24 x i32> @llvm.vector.interleave6.nxv24i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, <vscale x 4 x i32> %d, <vscale x 4 x i32> %e, <vscale x 4 x i32> %f)
  ret <vscale x 24 x i32> %res
}

declare <vscale x 24 x i32> @llvm.vector.interleave6.nxv24i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)

define <vscale x 12 x i64> @vector_interleave_nxv12i64_nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c, <vscale x 2 x i64> %d, <vscale x 2 x i64> %e, <vscale x 2 x i64> %f) nounwind {
; RV32-LABEL: vector_interleave_nxv12i64_nxv2i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v14
; RV32-NEXT:    vmv2r.v v22, v12
; RV32-NEXT:    vmv2r.v v24, v10
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a0, 6
; RV32-NEXT:    mul a1, a1, a0
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    vmv1r.v v10, v25
; RV32-NEXT:    vmv1r.v v11, v23
; RV32-NEXT:    vmv1r.v v12, v21
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv1r.v v13, v17
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv1r.v v14, v19
; RV32-NEXT:    vsseg6e64.v v9, (a1)
; RV32-NEXT:    vmv1r.v v9, v24
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vmv1r.v v10, v22
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v11, v20
; RV32-NEXT:    add a4, a3, a2
; RV32-NEXT:    vmv1r.v v12, v16
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v13, v18
; RV32-NEXT:    vsseg6e64.v v8, (a0)
; RV32-NEXT:    vl1re64.v v14, (a1)
; RV32-NEXT:    add a1, a6, a2
; RV32-NEXT:    vl1re64.v v15, (a5)
; RV32-NEXT:    add a5, a1, a2
; RV32-NEXT:    vl1re64.v v18, (a5)
; RV32-NEXT:    add a5, a5, a2
; RV32-NEXT:    vl1re64.v v19, (a5)
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vl1re64.v v16, (a6)
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vl1re64.v v12, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re64.v v13, (a6)
; RV32-NEXT:    csrr a6, vlenb
; RV32-NEXT:    li a7, 12
; RV32-NEXT:    mul a6, a6, a7
; RV32-NEXT:    add a6, sp, a6
; RV32-NEXT:    addi a6, a6, 64
; RV32-NEXT:    vl1re64.v v17, (a1)
; RV32-NEXT:    vl1re64.v v10, (a4)
; RV32-NEXT:    vl1re64.v v11, (a5)
; RV32-NEXT:    vl1re64.v v8, (a0)
; RV32-NEXT:    vl1re64.v v9, (a3)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a6, a2
; RV32-NEXT:    vs4r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a6)
; RV32-NEXT:    vl8re64.v v16, (a2)
; RV32-NEXT:    vl8re64.v v8, (a6)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv12i64_nxv2i64:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v14
; RV64-NEXT:    vmv2r.v v22, v12
; RV64-NEXT:    vmv2r.v v24, v10
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a0, 6
; RV64-NEXT:    mul a1, a1, a0
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    vmv1r.v v10, v25
; RV64-NEXT:    vmv1r.v v11, v23
; RV64-NEXT:    vmv1r.v v12, v21
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv1r.v v13, v17
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv1r.v v14, v19
; RV64-NEXT:    vsseg6e64.v v9, (a1)
; RV64-NEXT:    vmv1r.v v9, v24
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vmv1r.v v10, v22
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v11, v20
; RV64-NEXT:    add a4, a3, a2
; RV64-NEXT:    vmv1r.v v12, v16
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v13, v18
; RV64-NEXT:    vsseg6e64.v v8, (a0)
; RV64-NEXT:    vl1re64.v v14, (a1)
; RV64-NEXT:    add a1, a6, a2
; RV64-NEXT:    vl1re64.v v15, (a5)
; RV64-NEXT:    add a5, a1, a2
; RV64-NEXT:    vl1re64.v v18, (a5)
; RV64-NEXT:    add a5, a5, a2
; RV64-NEXT:    vl1re64.v v19, (a5)
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vl1re64.v v16, (a6)
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vl1re64.v v12, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re64.v v13, (a6)
; RV64-NEXT:    csrr a6, vlenb
; RV64-NEXT:    li a7, 12
; RV64-NEXT:    mul a6, a6, a7
; RV64-NEXT:    add a6, sp, a6
; RV64-NEXT:    addi a6, a6, 64
; RV64-NEXT:    vl1re64.v v17, (a1)
; RV64-NEXT:    vl1re64.v v10, (a4)
; RV64-NEXT:    vl1re64.v v11, (a5)
; RV64-NEXT:    vl1re64.v v8, (a0)
; RV64-NEXT:    vl1re64.v v9, (a3)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a6, a2
; RV64-NEXT:    vs4r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a6)
; RV64-NEXT:    vl8re64.v v16, (a2)
; RV64-NEXT:    vl8re64.v v8, (a6)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 12 x i64> @llvm.vector.interleave6.nxv12i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c, <vscale x 2 x i64> %d, <vscale x 2 x i64> %e, <vscale x 2 x i64> %f)
  ret <vscale x 12 x i64> %res
}

declare <vscale x 12 x i64> @llvm.vector.interleave6.nxv12i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
