; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK

; Integers

define <vscale x 128 x i1> @vector_interleave_nxv128i1_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b, <vscale x 16 x i1> %c, <vscale x 16 x i1> %d, <vscale x 16 x i1> %e, <vscale x 16 x i1> %f, <vscale x 16 x i1> %g, <vscale x 16 x i1> %h) nounwind {
; CHECK-LABEL: vector_interleave_nxv128i1_nxv16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmv.v.i v22, 0
; CHECK-NEXT:    vmerge.vim v24, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vim v16, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v1, v24
; CHECK-NEXT:    vmv1r.v v2, v16
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v26, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vmerge.vim v18, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v3, v26
; CHECK-NEXT:    vmv1r.v v4, v18
; CHECK-NEXT:    vmv1r.v v0, v11
; CHECK-NEXT:    vmerge.vim v8, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v12
; CHECK-NEXT:    vmerge.vim v20, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v5, v8
; CHECK-NEXT:    vmv1r.v v6, v20
; CHECK-NEXT:    vmv1r.v v0, v13
; CHECK-NEXT:    vmerge.vim v10, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v14
; CHECK-NEXT:    vmerge.vim v22, v22, 1, v0
; CHECK-NEXT:    vmv1r.v v7, v10
; CHECK-NEXT:    vmv1r.v v8, v22
; CHECK-NEXT:    vmv1r.v v16, v25
; CHECK-NEXT:    addi a2, sp, 16
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vsseg8e8.v v1, (a2)
; CHECK-NEXT:    vmv1r.v v18, v27
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    add a3, a2, a0
; CHECK-NEXT:    add a4, a1, a0
; CHECK-NEXT:    add a5, a3, a0
; CHECK-NEXT:    add a6, a4, a0
; CHECK-NEXT:    add a7, a5, a0
; CHECK-NEXT:    add t0, a6, a0
; CHECK-NEXT:    vmv1r.v v20, v9
; CHECK-NEXT:    add t1, a7, a0
; CHECK-NEXT:    vmv1r.v v22, v11
; CHECK-NEXT:    vsseg8e8.v v16, (a1)
; CHECK-NEXT:    vl1r.v v8, (a5)
; CHECK-NEXT:    add a5, t0, a0
; CHECK-NEXT:    vl1r.v v12, (t1)
; CHECK-NEXT:    add t1, t1, a0
; CHECK-NEXT:    vl1r.v v14, (a2)
; CHECK-NEXT:    add a2, a5, a0
; CHECK-NEXT:    vl1r.v v10, (a5)
; CHECK-NEXT:    add a5, t1, a0
; CHECK-NEXT:    vl1r.v v16, (a5)
; CHECK-NEXT:    add a5, a5, a0
; CHECK-NEXT:    vl1r.v v17, (a5)
; CHECK-NEXT:    add a5, a2, a0
; CHECK-NEXT:    vl1r.v v18, (a5)
; CHECK-NEXT:    add a5, a5, a0
; CHECK-NEXT:    vl1r.v v13, (t1)
; CHECK-NEXT:    vl1r.v v9, (a7)
; CHECK-NEXT:    vl1r.v v15, (a3)
; CHECK-NEXT:    vsetvli a3, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmsne.vi v16, v16, 0
; CHECK-NEXT:    vmsne.vi v17, v12, 0
; CHECK-NEXT:    vl1r.v v12, (a6)
; CHECK-NEXT:    vmsne.vi v20, v8, 0
; CHECK-NEXT:    vmsne.vi v0, v14, 0
; CHECK-NEXT:    vl1r.v v8, (a1)
; CHECK-NEXT:    vl1r.v v19, (a5)
; CHECK-NEXT:    vl1r.v v11, (a2)
; CHECK-NEXT:    vl1r.v v13, (t0)
; CHECK-NEXT:    vl1r.v v9, (a4)
; CHECK-NEXT:    vmsne.vi v14, v18, 0
; CHECK-NEXT:    vmsne.vi v10, v10, 0
; CHECK-NEXT:    vmsne.vi v11, v12, 0
; CHECK-NEXT:    vmsne.vi v8, v8, 0
; CHECK-NEXT:    srli a1, a0, 2
; CHECK-NEXT:    vsetvli a2, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vx v17, v16, a1
; CHECK-NEXT:    vslideup.vx v0, v20, a1
; CHECK-NEXT:    vslideup.vx v10, v14, a1
; CHECK-NEXT:    vslideup.vx v8, v11, a1
; CHECK-NEXT:    srli a0, a0, 1
; CHECK-NEXT:    vsetvli a1, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v17, a0
; CHECK-NEXT:    vslideup.vx v8, v10, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 128 x i1> @llvm.vector.interleave8.nxv128i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b, <vscale x 16 x i1> %c, <vscale x 16 x i1> %d, <vscale x 16 x i1> %e, <vscale x 16 x i1> %f, <vscale x 16 x i1> %g, <vscale x 16 x i1> %h)
  ret <vscale x 128 x i1> %res
}

declare <vscale x 128 x i1> @llvm.vector.interleave8.nxv128i1(<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>)

define <vscale x 128 x i8> @vector_interleave_nxv128i8_nxv16i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %b, <vscale x 16 x i8> %c, <vscale x 16 x i8> %d, <vscale x 16 x i8> %e, <vscale x 16 x i8> %f, <vscale x 16 x i8> %g, <vscale x 16 x i8> %h) nounwind {
; CHECK-LABEL: vector_interleave_nxv128i8_nxv16i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v28, v22
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vmv2r.v v26, v18
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    add a2, a0, a3
; CHECK-NEXT:    add a4, a1, a3
; CHECK-NEXT:    add a5, a2, a3
; CHECK-NEXT:    vmv1r.v v1, v8
; CHECK-NEXT:    vmv2r.v v24, v14
; CHECK-NEXT:    add a6, a4, a3
; CHECK-NEXT:    vmv2r.v v22, v10
; CHECK-NEXT:    vmv1r.v v2, v22
; CHECK-NEXT:    add a7, a5, a3
; CHECK-NEXT:    vmv1r.v v3, v12
; CHECK-NEXT:    add t0, a6, a3
; CHECK-NEXT:    vmv1r.v v4, v24
; CHECK-NEXT:    add t1, a7, a3
; CHECK-NEXT:    vmv1r.v v5, v16
; CHECK-NEXT:    add t2, t0, a3
; CHECK-NEXT:    vmv1r.v v6, v26
; CHECK-NEXT:    add t3, t1, a3
; CHECK-NEXT:    vmv1r.v v7, v20
; CHECK-NEXT:    add t4, t2, a3
; CHECK-NEXT:    vmv1r.v v8, v28
; CHECK-NEXT:    vmv1r.v v22, v9
; CHECK-NEXT:    add t5, t3, a3
; CHECK-NEXT:    vmv1r.v v24, v13
; CHECK-NEXT:    add t6, t4, a3
; CHECK-NEXT:    vmv1r.v v26, v17
; CHECK-NEXT:    vsseg8e8.v v1, (a0)
; CHECK-NEXT:    vmv1r.v v28, v21
; CHECK-NEXT:    vsseg8e8.v v22, (a1)
; CHECK-NEXT:    vl1r.v v14, (t5)
; CHECK-NEXT:    add t5, t5, a3
; CHECK-NEXT:    add a3, t6, a3
; CHECK-NEXT:    vl1r.v v22, (t6)
; CHECK-NEXT:    vl1r.v v15, (t5)
; CHECK-NEXT:    vl1r.v v23, (a3)
; CHECK-NEXT:    vl1r.v v12, (t1)
; CHECK-NEXT:    vl1r.v v20, (t2)
; CHECK-NEXT:    vl1r.v v13, (t3)
; CHECK-NEXT:    vl1r.v v21, (t4)
; CHECK-NEXT:    vl1r.v v10, (a5)
; CHECK-NEXT:    vl1r.v v18, (a6)
; CHECK-NEXT:    vl1r.v v11, (a7)
; CHECK-NEXT:    vl1r.v v19, (t0)
; CHECK-NEXT:    vl1r.v v8, (a0)
; CHECK-NEXT:    vl1r.v v16, (a1)
; CHECK-NEXT:    vl1r.v v9, (a2)
; CHECK-NEXT:    vl1r.v v17, (a4)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 128 x i8> @llvm.vector.interleave8.nxv128i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %b, <vscale x 16 x i8> %c, <vscale x 16 x i8> %d, <vscale x 16 x i8> %e, <vscale x 16 x i8> %f, <vscale x 16 x i8> %g, <vscale x 16 x i8> %h)
  ret <vscale x 128 x i8> %res
}

declare <vscale x 128 x i8> @llvm.vector.interleave8.nxv128i8(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)

define <vscale x 64 x i16> @vector_interleave_nxv64i16_nxv8i16(<vscale x 8 x i16> %a, <vscale x 8 x i16> %b, <vscale x 8 x i16> %c, <vscale x 8 x i16> %d, <vscale x 8 x i16> %e, <vscale x 8 x i16> %f, <vscale x 8 x i16> %g, <vscale x 8 x i16> %h) nounwind {
; CHECK-LABEL: vector_interleave_nxv64i16_nxv8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e16, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v28, v22
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vmv2r.v v26, v18
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    add a2, a0, a3
; CHECK-NEXT:    add a4, a1, a3
; CHECK-NEXT:    add a5, a2, a3
; CHECK-NEXT:    vmv1r.v v1, v8
; CHECK-NEXT:    vmv2r.v v24, v14
; CHECK-NEXT:    add a6, a4, a3
; CHECK-NEXT:    vmv2r.v v22, v10
; CHECK-NEXT:    vmv1r.v v2, v22
; CHECK-NEXT:    add a7, a5, a3
; CHECK-NEXT:    vmv1r.v v3, v12
; CHECK-NEXT:    add t0, a6, a3
; CHECK-NEXT:    vmv1r.v v4, v24
; CHECK-NEXT:    add t1, a7, a3
; CHECK-NEXT:    vmv1r.v v5, v16
; CHECK-NEXT:    add t2, t0, a3
; CHECK-NEXT:    vmv1r.v v6, v26
; CHECK-NEXT:    add t3, t1, a3
; CHECK-NEXT:    vmv1r.v v7, v20
; CHECK-NEXT:    add t4, t2, a3
; CHECK-NEXT:    vmv1r.v v8, v28
; CHECK-NEXT:    vmv1r.v v22, v9
; CHECK-NEXT:    add t5, t3, a3
; CHECK-NEXT:    vmv1r.v v24, v13
; CHECK-NEXT:    add t6, t4, a3
; CHECK-NEXT:    vmv1r.v v26, v17
; CHECK-NEXT:    vsseg8e16.v v1, (a0)
; CHECK-NEXT:    vmv1r.v v28, v21
; CHECK-NEXT:    vsseg8e16.v v22, (a1)
; CHECK-NEXT:    vl1re16.v v14, (t5)
; CHECK-NEXT:    add t5, t5, a3
; CHECK-NEXT:    add a3, t6, a3
; CHECK-NEXT:    vl1re16.v v22, (t6)
; CHECK-NEXT:    vl1re16.v v15, (t5)
; CHECK-NEXT:    vl1re16.v v23, (a3)
; CHECK-NEXT:    vl1re16.v v12, (t1)
; CHECK-NEXT:    vl1re16.v v20, (t2)
; CHECK-NEXT:    vl1re16.v v13, (t3)
; CHECK-NEXT:    vl1re16.v v21, (t4)
; CHECK-NEXT:    vl1re16.v v10, (a5)
; CHECK-NEXT:    vl1re16.v v18, (a6)
; CHECK-NEXT:    vl1re16.v v11, (a7)
; CHECK-NEXT:    vl1re16.v v19, (t0)
; CHECK-NEXT:    vl1re16.v v8, (a0)
; CHECK-NEXT:    vl1re16.v v16, (a1)
; CHECK-NEXT:    vl1re16.v v9, (a2)
; CHECK-NEXT:    vl1re16.v v17, (a4)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 64 x i16> @llvm.vector.interleave8.nxv64i16(<vscale x 8 x i16> %a, <vscale x 8 x i16> %b, <vscale x 8 x i16> %c, <vscale x 8 x i16> %d, <vscale x 8 x i16> %e, <vscale x 8 x i16> %f, <vscale x 8 x i16> %g, <vscale x 8 x i16> %h)
  ret <vscale x 64 x i16> %res
}

declare <vscale x 64 x i16> @llvm.vector.interleave8.nxv64i16(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>)

define <vscale x 32 x i32> @vector_interleave_nxv32i32_nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, <vscale x 4 x i32> %d, <vscale x 4 x i32> %e, <vscale x 4 x i32> %f, <vscale x 4 x i32> %g, <vscale x 4 x i32> %h) nounwind {
; CHECK-LABEL: vector_interleave_nxv32i32_nxv4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v28, v22
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vmv2r.v v26, v18
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    add a2, a0, a3
; CHECK-NEXT:    add a4, a1, a3
; CHECK-NEXT:    add a5, a2, a3
; CHECK-NEXT:    vmv1r.v v1, v8
; CHECK-NEXT:    vmv2r.v v24, v14
; CHECK-NEXT:    add a6, a4, a3
; CHECK-NEXT:    vmv2r.v v22, v10
; CHECK-NEXT:    vmv1r.v v2, v22
; CHECK-NEXT:    add a7, a5, a3
; CHECK-NEXT:    vmv1r.v v3, v12
; CHECK-NEXT:    add t0, a6, a3
; CHECK-NEXT:    vmv1r.v v4, v24
; CHECK-NEXT:    add t1, a7, a3
; CHECK-NEXT:    vmv1r.v v5, v16
; CHECK-NEXT:    add t2, t0, a3
; CHECK-NEXT:    vmv1r.v v6, v26
; CHECK-NEXT:    add t3, t1, a3
; CHECK-NEXT:    vmv1r.v v7, v20
; CHECK-NEXT:    add t4, t2, a3
; CHECK-NEXT:    vmv1r.v v8, v28
; CHECK-NEXT:    vmv1r.v v22, v9
; CHECK-NEXT:    add t5, t3, a3
; CHECK-NEXT:    vmv1r.v v24, v13
; CHECK-NEXT:    add t6, t4, a3
; CHECK-NEXT:    vmv1r.v v26, v17
; CHECK-NEXT:    vsseg8e32.v v1, (a0)
; CHECK-NEXT:    vmv1r.v v28, v21
; CHECK-NEXT:    vsseg8e32.v v22, (a1)
; CHECK-NEXT:    vl1re32.v v14, (t5)
; CHECK-NEXT:    add t5, t5, a3
; CHECK-NEXT:    add a3, t6, a3
; CHECK-NEXT:    vl1re32.v v22, (t6)
; CHECK-NEXT:    vl1re32.v v15, (t5)
; CHECK-NEXT:    vl1re32.v v23, (a3)
; CHECK-NEXT:    vl1re32.v v12, (t1)
; CHECK-NEXT:    vl1re32.v v20, (t2)
; CHECK-NEXT:    vl1re32.v v13, (t3)
; CHECK-NEXT:    vl1re32.v v21, (t4)
; CHECK-NEXT:    vl1re32.v v10, (a5)
; CHECK-NEXT:    vl1re32.v v18, (a6)
; CHECK-NEXT:    vl1re32.v v11, (a7)
; CHECK-NEXT:    vl1re32.v v19, (t0)
; CHECK-NEXT:    vl1re32.v v8, (a0)
; CHECK-NEXT:    vl1re32.v v16, (a1)
; CHECK-NEXT:    vl1re32.v v9, (a2)
; CHECK-NEXT:    vl1re32.v v17, (a4)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 32 x i32> @llvm.vector.interleave8.nxv32i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, <vscale x 4 x i32> %d, <vscale x 4 x i32> %e, <vscale x 4 x i32> %f, <vscale x 4 x i32> %g, <vscale x 4 x i32> %h)
  ret <vscale x 32 x i32> %res
}

declare <vscale x 32 x i32> @llvm.vector.interleave8.nxv32i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)

define <vscale x 16 x i64> @vector_interleave_nxv16i64_nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c, <vscale x 2 x i64> %d, <vscale x 2 x i64> %e, <vscale x 2 x i64> %f, <vscale x 2 x i64> %g, <vscale x 2 x i64> %h) nounwind {
; CHECK-LABEL: vector_interleave_nxv16i64_nxv2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; CHECK-NEXT:    vmv2r.v v28, v22
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vmv2r.v v26, v18
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    add a2, a0, a3
; CHECK-NEXT:    add a4, a1, a3
; CHECK-NEXT:    add a5, a2, a3
; CHECK-NEXT:    vmv1r.v v1, v8
; CHECK-NEXT:    vmv2r.v v24, v14
; CHECK-NEXT:    add a6, a4, a3
; CHECK-NEXT:    vmv2r.v v22, v10
; CHECK-NEXT:    vmv1r.v v2, v22
; CHECK-NEXT:    add a7, a5, a3
; CHECK-NEXT:    vmv1r.v v3, v12
; CHECK-NEXT:    add t0, a6, a3
; CHECK-NEXT:    vmv1r.v v4, v24
; CHECK-NEXT:    add t1, a7, a3
; CHECK-NEXT:    vmv1r.v v5, v16
; CHECK-NEXT:    add t2, t0, a3
; CHECK-NEXT:    vmv1r.v v6, v26
; CHECK-NEXT:    add t3, t1, a3
; CHECK-NEXT:    vmv1r.v v7, v20
; CHECK-NEXT:    add t4, t2, a3
; CHECK-NEXT:    vmv1r.v v8, v28
; CHECK-NEXT:    vmv1r.v v22, v9
; CHECK-NEXT:    add t5, t3, a3
; CHECK-NEXT:    vmv1r.v v24, v13
; CHECK-NEXT:    add t6, t4, a3
; CHECK-NEXT:    vmv1r.v v26, v17
; CHECK-NEXT:    vsseg8e64.v v1, (a0)
; CHECK-NEXT:    vmv1r.v v28, v21
; CHECK-NEXT:    vsseg8e64.v v22, (a1)
; CHECK-NEXT:    vl1re64.v v14, (t5)
; CHECK-NEXT:    add t5, t5, a3
; CHECK-NEXT:    add a3, t6, a3
; CHECK-NEXT:    vl1re64.v v22, (t6)
; CHECK-NEXT:    vl1re64.v v15, (t5)
; CHECK-NEXT:    vl1re64.v v23, (a3)
; CHECK-NEXT:    vl1re64.v v12, (t1)
; CHECK-NEXT:    vl1re64.v v20, (t2)
; CHECK-NEXT:    vl1re64.v v13, (t3)
; CHECK-NEXT:    vl1re64.v v21, (t4)
; CHECK-NEXT:    vl1re64.v v10, (a5)
; CHECK-NEXT:    vl1re64.v v18, (a6)
; CHECK-NEXT:    vl1re64.v v11, (a7)
; CHECK-NEXT:    vl1re64.v v19, (t0)
; CHECK-NEXT:    vl1re64.v v8, (a0)
; CHECK-NEXT:    vl1re64.v v16, (a1)
; CHECK-NEXT:    vl1re64.v v9, (a2)
; CHECK-NEXT:    vl1re64.v v17, (a4)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 16 x i64> @llvm.vector.interleave8.nxv16i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c, <vscale x 2 x i64> %d, <vscale x 2 x i64> %e, <vscale x 2 x i64> %f, <vscale x 2 x i64> %g, <vscale x 2 x i64> %h)
  ret <vscale x 16 x i64> %res
}

declare <vscale x 16 x i64> @llvm.vector.interleave8.nxv16i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
