; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v -mattr=+no-sink-splat-operands | FileCheck %s --check-prefix=NOSINK

; Make sure we have SEW=8 splats in the preheader and vwmul/vwmaccs in the loop.

define void @wombat(ptr %arg, ptr %arg1, ptr %arg2, i64 %arg3, i32 %arg4, i32 %arg5) {
; CHECK-LABEL: wombat:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    li a6, 0
; CHECK-NEXT:    andi a5, a5, 7
; CHECK-NEXT:    li a7, 8
; CHECK-NEXT:    andi t0, a4, 7
; CHECK-NEXT:    sub t1, a7, a5
; CHECK-NEXT:    sub a7, a7, t0
; CHECK-NEXT:    mul a4, t0, a5
; CHECK-NEXT:    mul a5, a7, a5
; CHECK-NEXT:    mul a7, a7, t1
; CHECK-NEXT:    mul t0, t0, t1
; CHECK-NEXT:    li t1, 32
; CHECK-NEXT:  .LBB0_1: # %bb20
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sub t2, a3, a6
; CHECK-NEXT:    addi t3, a6, 1
; CHECK-NEXT:    vsetvli t2, t2, e8, m1, ta, ma
; CHECK-NEXT:    add t4, a1, t3
; CHECK-NEXT:    vle8.v v9, (t4)
; CHECK-NEXT:    add t4, a0, a6
; CHECK-NEXT:    vle8.v v12, (t4)
; CHECK-NEXT:    add t4, a1, a6
; CHECK-NEXT:    add t3, a0, t3
; CHECK-NEXT:    vle8.v v11, (t3)
; CHECK-NEXT:    add t3, a2, a6
; CHECK-NEXT:    vle8.v v13, (t4)
; CHECK-NEXT:    vwmulu.vx v8, v9, t0
; CHECK-NEXT:    vwmulu.vx v10, v11, a4
; CHECK-NEXT:    vwmaccu.vx v10, a5, v12
; CHECK-NEXT:    vwmaccu.vx v8, a7, v13
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vadd.vx v8, v8, t1
; CHECK-NEXT:    vadd.vv v8, v8, v10
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 6
; CHECK-NEXT:    add a6, a6, t2
; CHECK-NEXT:    vse8.v v8, (t3)
; CHECK-NEXT:    bne a6, a3, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %bb46
; CHECK-NEXT:    ret
;
; NOSINK-LABEL: wombat:
; NOSINK:       # %bb.0: # %bb
; NOSINK-NEXT:    li a6, 0
; NOSINK-NEXT:    andi a5, a5, 7
; NOSINK-NEXT:    li a7, 8
; NOSINK-NEXT:    andi a4, a4, 7
; NOSINK-NEXT:    subw t0, a7, a5
; NOSINK-NEXT:    subw a7, a7, a4
; NOSINK-NEXT:    mul t1, a4, a5
; NOSINK-NEXT:    mul a5, a7, a5
; NOSINK-NEXT:    mul a7, a7, t0
; NOSINK-NEXT:    mul a4, a4, t0
; NOSINK-NEXT:    vsetvli t0, zero, e8, m1, ta, ma
; NOSINK-NEXT:    vmv.v.x v8, t1
; NOSINK-NEXT:    vmv.v.x v9, a7
; NOSINK-NEXT:    vmv.v.x v10, a4
; NOSINK-NEXT:    vmv.v.x v11, a5
; NOSINK-NEXT:    li a4, 32
; NOSINK-NEXT:  .LBB0_1: # %bb20
; NOSINK-NEXT:    # =>This Inner Loop Header: Depth=1
; NOSINK-NEXT:    sub a5, a3, a6
; NOSINK-NEXT:    addi a7, a6, 1
; NOSINK-NEXT:    vsetvli a5, a5, e8, m1, ta, ma
; NOSINK-NEXT:    add t0, a1, a7
; NOSINK-NEXT:    vle8.v v13, (t0)
; NOSINK-NEXT:    add t0, a0, a6
; NOSINK-NEXT:    vle8.v v16, (t0)
; NOSINK-NEXT:    add t0, a1, a6
; NOSINK-NEXT:    add a7, a0, a7
; NOSINK-NEXT:    vle8.v v15, (a7)
; NOSINK-NEXT:    add a7, a2, a6
; NOSINK-NEXT:    vle8.v v17, (t0)
; NOSINK-NEXT:    vwmulu.vv v12, v10, v13
; NOSINK-NEXT:    vwmulu.vv v14, v8, v15
; NOSINK-NEXT:    vwmaccu.vv v14, v11, v16
; NOSINK-NEXT:    vwmaccu.vv v12, v9, v17
; NOSINK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; NOSINK-NEXT:    vadd.vx v12, v12, a4
; NOSINK-NEXT:    vadd.vv v12, v12, v14
; NOSINK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; NOSINK-NEXT:    vnsrl.wi v12, v12, 6
; NOSINK-NEXT:    add a6, a6, a5
; NOSINK-NEXT:    vse8.v v12, (a7)
; NOSINK-NEXT:    bne a6, a3, .LBB0_1
; NOSINK-NEXT:  # %bb.2: # %bb46
; NOSINK-NEXT:    ret
bb:
  %and6 = and i32 %arg5, 7
  %sub7 = sub nuw nsw i32 8, %and6
  %and = and i32 %arg4, 7
  %sub = sub nuw nsw i32 8, %and
  %mul = mul nuw nsw i32 %sub, %and6
  %mul8 = mul nuw nsw i32 %and, %and6
  %mul9 = mul nuw nsw i32 %sub, %sub7
  %mul10 = mul nuw nsw i32 %and, %sub7
  %trunc = trunc i32 %mul9 to i16
  %insertelement = insertelement <vscale x 8 x i16> undef, i16 %trunc, i64 0
  %shufflevector = shufflevector <vscale x 8 x i16> %insertelement, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %trunc11 = trunc i32 %mul10 to i16
  %insertelement12 = insertelement <vscale x 8 x i16> undef, i16 %trunc11, i64 0
  %shufflevector13 = shufflevector <vscale x 8 x i16> %insertelement12, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %trunc14 = trunc i32 %mul to i16
  %insertelement15 = insertelement <vscale x 8 x i16> undef, i16 %trunc14, i64 0
  %shufflevector16 = shufflevector <vscale x 8 x i16> %insertelement15, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %trunc17 = trunc i32 %mul8 to i16
  %insertelement18 = insertelement <vscale x 8 x i16> undef, i16 %trunc17, i64 0
  %shufflevector19 = shufflevector <vscale x 8 x i16> %insertelement18, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  br label %bb20

bb20:                                             ; preds = %bb20, %bb
  %phi = phi i64 [ %add45, %bb20 ], [ 0, %bb ]
  %sub21 = sub i64 %arg3, %phi
  %call = tail call i64 @llvm.riscv.vsetvli.i64(i64 %sub21, i64 0, i64 0)
  %trunc22 = trunc i64 %call to i32
  %getelementptr = getelementptr inbounds i8, ptr %arg1, i64 %phi
  %call23 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr align 1 %getelementptr, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call24 = tail call <vscale x 8 x i16> @llvm.vp.zext.nxv8i16.nxv8i8(<vscale x 8 x i8> %call23, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call25 = tail call <vscale x 8 x i16> @llvm.vp.mul.nxv8i16(<vscale x 8 x i16> %shufflevector, <vscale x 8 x i16> %call24, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %add = add nuw nsw i64 %phi, 1
  %getelementptr26 = getelementptr inbounds i8, ptr %arg1, i64 %add
  %call27 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr nonnull align 1 %getelementptr26, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call28 = tail call <vscale x 8 x i16> @llvm.vp.zext.nxv8i16.nxv8i8(<vscale x 8 x i8> %call27, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call29 = tail call <vscale x 8 x i16> @llvm.vp.mul.nxv8i16(<vscale x 8 x i16> %shufflevector13, <vscale x 8 x i16> %call28, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %getelementptr30 = getelementptr inbounds i8, ptr %arg, i64 %phi
  %call31 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr align 1 %getelementptr30, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call32 = tail call <vscale x 8 x i16> @llvm.vp.zext.nxv8i16.nxv8i8(<vscale x 8 x i8> %call31, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call33 = tail call <vscale x 8 x i16> @llvm.vp.mul.nxv8i16(<vscale x 8 x i16> %shufflevector16, <vscale x 8 x i16> %call32, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %getelementptr34 = getelementptr inbounds i8, ptr %arg, i64 %add
  %call35 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr nonnull align 1 %getelementptr34, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call36 = tail call <vscale x 8 x i16> @llvm.vp.zext.nxv8i16.nxv8i8(<vscale x 8 x i8> %call35, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call37 = tail call <vscale x 8 x i16> @llvm.vp.mul.nxv8i16(<vscale x 8 x i16> %shufflevector19, <vscale x 8 x i16> %call36, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call38 = tail call <vscale x 8 x i16> @llvm.vp.add.nxv8i16(<vscale x 8 x i16> %call37, <vscale x 8 x i16> %call33, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call39 = tail call <vscale x 8 x i16> @llvm.vp.add.nxv8i16(<vscale x 8 x i16> %call29, <vscale x 8 x i16> %call25, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call40 = tail call <vscale x 8 x i16> @llvm.vp.add.nxv8i16(<vscale x 8 x i16> %call39, <vscale x 8 x i16> trunc (<vscale x 8 x i32> shufflevector (<vscale x 8 x i32> insertelement (<vscale x 8 x i32> poison, i32 32, i64 0), <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer) to <vscale x 8 x i16>), <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call41 = tail call <vscale x 8 x i16> @llvm.vp.add.nxv8i16(<vscale x 8 x i16> %call40, <vscale x 8 x i16> %call38, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call42 = tail call <vscale x 8 x i16> @llvm.vp.lshr.nxv8i16(<vscale x 8 x i16> %call41, <vscale x 8 x i16> trunc (<vscale x 8 x i32> shufflevector (<vscale x 8 x i32> insertelement (<vscale x 8 x i32> poison, i32 6, i64 0), <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer) to <vscale x 8 x i16>), <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call43 = tail call <vscale x 8 x i8> @llvm.vp.trunc.nxv8i8.nxv8i16(<vscale x 8 x i16> %call42, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %getelementptr44 = getelementptr inbounds i8, ptr %arg2, i64 %phi
  tail call void @llvm.vp.store.nxv8i8.p0(<vscale x 8 x i8> %call43, ptr align 1 %getelementptr44, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %add45 = add i64 %phi, %call
  %icmp = icmp eq i64 %add45, %arg3
  br i1 %icmp, label %bb46, label %bb20

bb46:                                             ; preds = %bb20
  ret void
}

declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg) #0
declare <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr nocapture, <vscale x 8 x i1>, i32)
declare void @llvm.vp.store.nxv8i8.p0(<vscale x 8 x i8>, ptr nocapture, <vscale x 8 x i1>, i32)
declare <vscale x 8 x i16> @llvm.vp.zext.nxv8i16.nxv8i8(<vscale x 8 x i8>, <vscale x 8 x i1>, i32)
declare <vscale x 8 x i16> @llvm.vp.mul.nxv8i16(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i1>, i32)
declare <vscale x 8 x i16> @llvm.vp.add.nxv8i16(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i1>, i32)
declare <vscale x 8 x i16> @llvm.vp.lshr.nxv8i16(<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i1>, i32)
declare <vscale x 8 x i8> @llvm.vp.trunc.nxv8i8.nxv8i16(<vscale x 8 x i16>, <vscale x 8 x i1>, i32)

define void @spam(ptr %arg, ptr %arg1, ptr %arg2, i64 %arg3, i32 %arg4, i32 %arg5) {
; CHECK-LABEL: spam:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    li a6, 0
; CHECK-NEXT:    andi a5, a5, 7
; CHECK-NEXT:    li a7, 8
; CHECK-NEXT:    andi t0, a4, 7
; CHECK-NEXT:    sub t1, a7, a5
; CHECK-NEXT:    sub a7, a7, t0
; CHECK-NEXT:    mul a4, t0, a5
; CHECK-NEXT:    mul a5, a7, a5
; CHECK-NEXT:    mul a7, a7, t1
; CHECK-NEXT:    mul t0, t0, t1
; CHECK-NEXT:    li t1, 32
; CHECK-NEXT:  .LBB1_1: # %bb20
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    sub t2, a3, a6
; CHECK-NEXT:    add t3, a1, a6
; CHECK-NEXT:    addi t4, a6, 1
; CHECK-NEXT:    vsetvli t2, t2, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v9, (t3)
; CHECK-NEXT:    add t3, a0, a6
; CHECK-NEXT:    vle8.v v11, (t3)
; CHECK-NEXT:    add t3, a0, t4
; CHECK-NEXT:    vle8.v v12, (t3)
; CHECK-NEXT:    add t3, a2, a6
; CHECK-NEXT:    add t4, a1, t4
; CHECK-NEXT:    vle8.v v13, (t4)
; CHECK-NEXT:    vwmulu.vx v8, v9, a7
; CHECK-NEXT:    vwmulu.vx v10, v11, a5
; CHECK-NEXT:    vwmaccu.vx v10, a4, v12
; CHECK-NEXT:    vwmaccu.vx v8, t0, v13
; CHECK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; CHECK-NEXT:    vadd.vv v8, v8, v10
; CHECK-NEXT:    vadd.vx v8, v8, t1
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vnsrl.wi v8, v8, 6
; CHECK-NEXT:    add a6, a6, t2
; CHECK-NEXT:    vse8.v v8, (t3)
; CHECK-NEXT:    bne a6, a3, .LBB1_1
; CHECK-NEXT:  # %bb.2: # %bb46
; CHECK-NEXT:    ret
;
; NOSINK-LABEL: spam:
; NOSINK:       # %bb.0: # %bb
; NOSINK-NEXT:    li a6, 0
; NOSINK-NEXT:    andi a5, a5, 7
; NOSINK-NEXT:    li a7, 8
; NOSINK-NEXT:    andi a4, a4, 7
; NOSINK-NEXT:    subw t0, a7, a5
; NOSINK-NEXT:    subw a7, a7, a4
; NOSINK-NEXT:    mul t1, a4, a5
; NOSINK-NEXT:    mul a5, a7, a5
; NOSINK-NEXT:    mul a7, a7, t0
; NOSINK-NEXT:    mul a4, a4, t0
; NOSINK-NEXT:    vsetvli t0, zero, e8, m1, ta, ma
; NOSINK-NEXT:    vmv.v.x v8, t1
; NOSINK-NEXT:    vmv.v.x v9, a7
; NOSINK-NEXT:    vmv.v.x v10, a4
; NOSINK-NEXT:    vmv.v.x v11, a5
; NOSINK-NEXT:    li a4, 32
; NOSINK-NEXT:  .LBB1_1: # %bb20
; NOSINK-NEXT:    # =>This Inner Loop Header: Depth=1
; NOSINK-NEXT:    sub a5, a3, a6
; NOSINK-NEXT:    add a7, a1, a6
; NOSINK-NEXT:    addi t0, a6, 1
; NOSINK-NEXT:    vsetvli a5, a5, e8, m1, ta, ma
; NOSINK-NEXT:    vle8.v v13, (a7)
; NOSINK-NEXT:    add a7, a0, a6
; NOSINK-NEXT:    vle8.v v15, (a7)
; NOSINK-NEXT:    add a7, a0, t0
; NOSINK-NEXT:    vle8.v v16, (a7)
; NOSINK-NEXT:    add a7, a2, a6
; NOSINK-NEXT:    add t0, a1, t0
; NOSINK-NEXT:    vle8.v v17, (t0)
; NOSINK-NEXT:    vwmulu.vv v12, v9, v13
; NOSINK-NEXT:    vwmulu.vv v14, v11, v15
; NOSINK-NEXT:    vwmaccu.vv v14, v8, v16
; NOSINK-NEXT:    vwmaccu.vv v12, v10, v17
; NOSINK-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; NOSINK-NEXT:    vadd.vv v12, v12, v14
; NOSINK-NEXT:    vadd.vx v12, v12, a4
; NOSINK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; NOSINK-NEXT:    vnsrl.wi v12, v12, 6
; NOSINK-NEXT:    add a6, a6, a5
; NOSINK-NEXT:    vse8.v v12, (a7)
; NOSINK-NEXT:    bne a6, a3, .LBB1_1
; NOSINK-NEXT:  # %bb.2: # %bb46
; NOSINK-NEXT:    ret
bb:
  %and6 = and i32 %arg5, 7
  %sub7 = sub nuw nsw i32 8, %and6
  %and = and i32 %arg4, 7
  %sub = sub nuw nsw i32 8, %and
  %mul = mul nuw nsw i32 %sub, %and6
  %mul8 = mul nuw nsw i32 %and, %and6
  %mul9 = mul nuw nsw i32 %sub, %sub7
  %mul10 = mul nuw nsw i32 %and, %sub7
  %trunc = trunc i32 %mul9 to i16
  %insertelement = insertelement <vscale x 8 x i16> undef, i16 %trunc, i64 0
  %shufflevector = shufflevector <vscale x 8 x i16> %insertelement, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %trunc11 = trunc i32 %mul10 to i16
  %insertelement12 = insertelement <vscale x 8 x i16> undef, i16 %trunc11, i64 0
  %shufflevector13 = shufflevector <vscale x 8 x i16> %insertelement12, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %trunc14 = trunc i32 %mul to i16
  %insertelement15 = insertelement <vscale x 8 x i16> undef, i16 %trunc14, i64 0
  %shufflevector16 = shufflevector <vscale x 8 x i16> %insertelement15, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  %trunc17 = trunc i32 %mul8 to i16
  %insertelement18 = insertelement <vscale x 8 x i16> undef, i16 %trunc17, i64 0
  %shufflevector19 = shufflevector <vscale x 8 x i16> %insertelement18, <vscale x 8 x i16> poison, <vscale x 8 x i32> zeroinitializer
  br label %bb20

bb20:                                             ; preds = %bb20, %bb
  %phi = phi i64 [ %add45, %bb20 ], [ 0, %bb ]
  %sub21 = sub i64 %arg3, %phi
  %call = tail call i64 @llvm.riscv.vsetvli.i64(i64 %sub21, i64 0, i64 0)
  %trunc22 = trunc i64 %call to i32
  %getelementptr = getelementptr inbounds i8, ptr %arg1, i64 %phi
  %call23 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr align 1 %getelementptr, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call24 = zext <vscale x 8 x i8> %call23 to <vscale x 8 x i16>
  %call25 = mul <vscale x 8 x i16> %shufflevector, %call24
  %add = add nuw nsw i64 %phi, 1
  %getelementptr26 = getelementptr inbounds i8, ptr %arg1, i64 %add
  %call27 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr nonnull align 1 %getelementptr26, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call28 = zext <vscale x 8 x i8> %call27 to <vscale x 8 x i16>
  %call29 = mul <vscale x 8 x i16> %shufflevector13, %call28
  %getelementptr30 = getelementptr inbounds i8, ptr %arg, i64 %phi
  %call31 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr align 1 %getelementptr30, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call32 = zext <vscale x 8 x i8> %call31 to <vscale x 8 x i16>
  %call33 = mul <vscale x 8 x i16> %shufflevector16, %call32
  %getelementptr34 = getelementptr inbounds i8, ptr %arg, i64 %add
  %call35 = tail call <vscale x 8 x i8> @llvm.vp.load.nxv8i8.p0(ptr nonnull align 1 %getelementptr34, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %call36 = zext <vscale x 8 x i8> %call35 to <vscale x 8 x i16>
  %call37 = mul <vscale x 8 x i16> %shufflevector19, %call36
  %call38 = add <vscale x 8 x i16> %call37, %call33
  %call39 = add <vscale x 8 x i16> %call29, %call25
  %call40 = add <vscale x 8 x i16> %call39, trunc (<vscale x 8 x i32> shufflevector (<vscale x 8 x i32> insertelement (<vscale x 8 x i32> poison, i32 32, i64 0), <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer) to <vscale x 8 x i16>)
  %call41 = add <vscale x 8 x i16> %call40, %call38
  %call42 = lshr <vscale x 8 x i16> %call41, trunc (<vscale x 8 x i32> shufflevector (<vscale x 8 x i32> insertelement (<vscale x 8 x i32> poison, i32 6, i64 0), <vscale x 8 x i32> poison, <vscale x 8 x i32> zeroinitializer) to <vscale x 8 x i16>)
  %call43 = trunc <vscale x 8 x i16> %call42 to <vscale x 8 x i8>
  %getelementptr44 = getelementptr inbounds i8, ptr %arg2, i64 %phi
  tail call void @llvm.vp.store.nxv8i8.p0(<vscale x 8 x i8> %call43, ptr align 1 %getelementptr44, <vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), i32 %trunc22)
  %add45 = add i64 %phi, %call
  %icmp = icmp eq i64 %add45, %arg3
  br i1 %icmp, label %bb46, label %bb20

bb46:                                             ; preds = %bb20
  ret void
}
