; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=false -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=NOALIGN
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -riscv-v-vector-bits-max=128 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN-VLEN

define void @UnKnownSize(ptr nocapture %dst, i8 %val, i32 signext %n) {
; NOALIGN-LABEL: UnKnownSize:
; NOALIGN:       # %bb.0: # %entry
; NOALIGN-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vmv.v.x v8, a1
; NOALIGN-NEXT:  .LBB0_1: # %memset-forward-loop
; NOALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; NOALIGN-NEXT:    vsetvli a1, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vse8.v v8, (a0)
; NOALIGN-NEXT:    sub a2, a2, a1
; NOALIGN-NEXT:    add a0, a0, a1
; NOALIGN-NEXT:    bnez a2, .LBB0_1
; NOALIGN-NEXT:  # %bb.2: # %memset-post-loop
; NOALIGN-NEXT:    ret
;
; ALIGN-LABEL: UnKnownSize:
; ALIGN:       # %bb.0: # %entry
; ALIGN-NEXT:    vsetvli a3, zero, e8, m8, ta, ma
; ALIGN-NEXT:    bltu a3, a2, .LBB0_2
; ALIGN-NEXT:  # %bb.1: # %entry
; ALIGN-NEXT:    mv a3, a2
; ALIGN-NEXT:  .LBB0_2: # %entry
; ALIGN-NEXT:    andi a4, a0, 15
; ALIGN-NEXT:    li a5, 16
; ALIGN-NEXT:    sub a4, a5, a4
; ALIGN-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; ALIGN-NEXT:    vmv.v.x v8, a1
; ALIGN-NEXT:    bltu a4, a2, .LBB0_4
; ALIGN-NEXT:  # %bb.3: # %entry
; ALIGN-NEXT:    mv a4, a2
; ALIGN-NEXT:  .LBB0_4: # %entry
; ALIGN-NEXT:    vsetvli a3, a4, e8, m8, ta, ma
; ALIGN-NEXT:    sub a1, a2, a3
; ALIGN-NEXT:    vse8.v v8, (a0)
; ALIGN-NEXT:    add a0, a0, a3
; ALIGN-NEXT:  .LBB0_5: # %memset-forward-loop
; ALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-NEXT:    vsetvli a2, a1, e8, m8, ta, ma
; ALIGN-NEXT:    vse8.v v8, (a0)
; ALIGN-NEXT:    sub a1, a1, a2
; ALIGN-NEXT:    add a0, a0, a2
; ALIGN-NEXT:    bnez a1, .LBB0_5
; ALIGN-NEXT:  # %bb.6: # %memset-post-loop
; ALIGN-NEXT:    ret
;
; ALIGN-VLEN-LABEL: UnKnownSize:
; ALIGN-VLEN:       # %bb.0: # %entry
; ALIGN-VLEN-NEXT:    li a4, 128
; ALIGN-VLEN-NEXT:    mv a3, a2
; ALIGN-VLEN-NEXT:    bltu a2, a4, .LBB0_2
; ALIGN-VLEN-NEXT:  # %bb.1: # %entry
; ALIGN-VLEN-NEXT:    li a3, 128
; ALIGN-VLEN-NEXT:  .LBB0_2: # %entry
; ALIGN-VLEN-NEXT:    andi a4, a0, 15
; ALIGN-VLEN-NEXT:    li a5, 16
; ALIGN-VLEN-NEXT:    sub a4, a5, a4
; ALIGN-VLEN-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    vmv.v.x v8, a1
; ALIGN-VLEN-NEXT:    bltu a4, a2, .LBB0_4
; ALIGN-VLEN-NEXT:  # %bb.3: # %entry
; ALIGN-VLEN-NEXT:    mv a4, a2
; ALIGN-VLEN-NEXT:  .LBB0_4: # %entry
; ALIGN-VLEN-NEXT:    vsetvli a3, a4, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    sub a1, a2, a3
; ALIGN-VLEN-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-NEXT:    add a0, a0, a3
; ALIGN-VLEN-NEXT:  .LBB0_5: # %memset-forward-loop
; ALIGN-VLEN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-VLEN-NEXT:    vsetvli a2, a1, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-NEXT:    sub a1, a1, a2
; ALIGN-VLEN-NEXT:    add a0, a0, a2
; ALIGN-VLEN-NEXT:    bnez a1, .LBB0_5
; ALIGN-VLEN-NEXT:  # %bb.6: # %memset-post-loop
; ALIGN-VLEN-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i32(ptr align 1 %dst, i8 %val, i32 %n, i1 false)
  ret void
}

; Size is known, but it is larger than our constant size thresholds.
; Give the size in i64 instead of XLen to make sure that cases is handled.
define void @UnKnownSize2(ptr nocapture %dst, i8 %val) {
; NOALIGN-LABEL: UnKnownSize2:
; NOALIGN:       # %bb.0: # %entry
; NOALIGN-NEXT:    lui a2, 2
; NOALIGN-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vmv.v.x v8, a1
; NOALIGN-NEXT:  .LBB1_1: # %memset-forward-loop
; NOALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; NOALIGN-NEXT:    vsetvli a1, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vse8.v v8, (a0)
; NOALIGN-NEXT:    sub a2, a2, a1
; NOALIGN-NEXT:    add a0, a0, a1
; NOALIGN-NEXT:    bnez a2, .LBB1_1
; NOALIGN-NEXT:  # %bb.2: # %memset-post-loop
; NOALIGN-NEXT:    ret
;
; ALIGN-LABEL: UnKnownSize2:
; ALIGN:       # %bb.0: # %entry
; ALIGN-NEXT:    vsetvli a3, zero, e8, m8, ta, ma
; ALIGN-NEXT:    lui a2, 2
; ALIGN-NEXT:    bltu a3, a2, .LBB1_2
; ALIGN-NEXT:  # %bb.1: # %entry
; ALIGN-NEXT:    lui a3, 2
; ALIGN-NEXT:  .LBB1_2: # %entry
; ALIGN-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; ALIGN-NEXT:    vmv.v.x v8, a1
; ALIGN-NEXT:    andi a1, a0, 15
; ALIGN-NEXT:    li a3, 16
; ALIGN-NEXT:    sub a3, a3, a1
; ALIGN-NEXT:    vsetvli a3, a3, e8, m8, ta, ma
; ALIGN-NEXT:    sub a1, a2, a3
; ALIGN-NEXT:    vse8.v v8, (a0)
; ALIGN-NEXT:    add a0, a0, a3
; ALIGN-NEXT:  .LBB1_3: # %memset-forward-loop
; ALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-NEXT:    vsetvli a2, a1, e8, m8, ta, ma
; ALIGN-NEXT:    vse8.v v8, (a0)
; ALIGN-NEXT:    sub a1, a1, a2
; ALIGN-NEXT:    add a0, a0, a2
; ALIGN-NEXT:    bnez a1, .LBB1_3
; ALIGN-NEXT:  # %bb.4: # %memset-post-loop
; ALIGN-NEXT:    ret
;
; ALIGN-VLEN-LABEL: UnKnownSize2:
; ALIGN-VLEN:       # %bb.0: # %entry
; ALIGN-VLEN-NEXT:    vsetvli a2, zero, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    vmv.v.x v8, a1
; ALIGN-VLEN-NEXT:    andi a1, a0, 15
; ALIGN-VLEN-NEXT:    li a2, 16
; ALIGN-VLEN-NEXT:    sub a2, a2, a1
; ALIGN-VLEN-NEXT:    lui a1, 2
; ALIGN-VLEN-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    sub a1, a1, a2
; ALIGN-VLEN-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-NEXT:    add a0, a0, a2
; ALIGN-VLEN-NEXT:  .LBB1_1: # %memset-forward-loop
; ALIGN-VLEN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-VLEN-NEXT:    vsetvli a2, a1, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-NEXT:    sub a1, a1, a2
; ALIGN-VLEN-NEXT:    add a0, a0, a2
; ALIGN-VLEN-NEXT:    bnez a1, .LBB1_1
; ALIGN-VLEN-NEXT:  # %bb.2: # %memset-post-loop
; ALIGN-VLEN-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 8192, i1 false)
  ret void
}
