; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -mattr=+xsfvfhbfmin -verify-machineinstrs \
; RUN:   < %s | FileCheck %s

define <vscale x 1 x bfloat> @bitcast_i16mf4_bf16mf4(<vscale x 1 x i16> %src) {
; CHECK-LABEL: bitcast_i16mf4_bf16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 1 x i16> %src to <vscale x 1 x bfloat>
  ret <vscale x 1 x bfloat> %0
}

define <vscale x 2 x bfloat> @bitcast_i16mf2_bf16mf2(<vscale x 2 x i16> %src) {
; CHECK-LABEL: bitcast_i16mf2_bf16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 2 x i16> %src to <vscale x 2 x bfloat>
  ret <vscale x 2 x bfloat> %0
}

define <vscale x 4 x bfloat> @bitcast_i16m1_bf16m1(<vscale x 4 x i16> %src) {
; CHECK-LABEL: bitcast_i16m1_bf16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 4 x i16> %src to <vscale x 4 x bfloat>
  ret <vscale x 4 x bfloat> %0
}

define <vscale x 8 x bfloat> @bitcast_i16m2_bf16m2(<vscale x 8 x i16> %src) {
; CHECK-LABEL: bitcast_i16m2_bf16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 8 x i16> %src to <vscale x 8 x bfloat>
  ret <vscale x 8 x bfloat> %0
}

define <vscale x 16 x bfloat> @bitcast_i16m4_bf16m4(<vscale x 16 x i16> %src) {
; CHECK-LABEL: bitcast_i16m4_bf16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 16 x i16> %src to <vscale x 16 x bfloat>
  ret <vscale x 16 x bfloat> %0
}

define <vscale x 32 x bfloat> @bitcast_i16m8_bf16m8(<vscale x 32 x i16> %src) {
; CHECK-LABEL: bitcast_i16m8_bf16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 32 x i16> %src to <vscale x 32 x bfloat>
  ret <vscale x 32 x bfloat> %0
}

define <vscale x 1 x i16> @bitcast_bf16mf4_i16mf4(<vscale x 1 x bfloat> %src) {
; CHECK-LABEL: bitcast_bf16mf4_i16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 1 x bfloat> %src to <vscale x 1 x i16>
  ret <vscale x 1 x i16> %0
}

define <vscale x 2 x i16> @bitcast_bf16mf2_i16mf2(<vscale x 2 x bfloat> %src) {
; CHECK-LABEL: bitcast_bf16mf2_i16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 2 x bfloat> %src to <vscale x 2 x i16>
  ret <vscale x 2 x i16> %0
}

define <vscale x 4 x i16> @bitcast_bf16m1_i16m1(<vscale x 4 x bfloat> %src) {
; CHECK-LABEL: bitcast_bf16m1_i16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 4 x bfloat> %src to <vscale x 4 x i16>
  ret <vscale x 4 x i16> %0
}

define <vscale x 8 x i16> @bitcast_bf16m2_i16m2(<vscale x 8 x bfloat> %src) {
; CHECK-LABEL: bitcast_bf16m2_i16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 8 x bfloat> %src to <vscale x 8 x i16>
  ret <vscale x 8 x i16> %0
}

define <vscale x 16 x i16> @bitcast_bf16m4_i16m4(<vscale x 16 x bfloat> %src) {
; CHECK-LABEL: bitcast_bf16m4_i16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 16 x bfloat> %src to <vscale x 16 x i16>
  ret <vscale x 16 x i16> %0
}

define <vscale x 32 x i16> @bitcast_bf16m8_i16m8(<vscale x 32 x bfloat> %src) {
; CHECK-LABEL: bitcast_bf16m8_i16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ret
entry:
  %0 = bitcast <vscale x 32 x bfloat> %src to <vscale x 32 x i16>
  ret <vscale x 32 x i16> %0
}
