; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple riscv64 -mattr=+v < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,V
; RUN: llc -mtriple riscv64 -mattr=+v,+zvbb < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,ZVBB

; We want to use widening add, sub, macc, or shl.

define <4 x i32> @interleave_addsub_1(<4 x i8> %x, <4 x i8> %y) {
; V-LABEL: interleave_addsub_1:
; V:       # %bb.0:
; V-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; V-NEXT:    vwaddu.vv v10, v8, v9
; V-NEXT:    vwsubu.vv v11, v8, v9
; V-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; V-NEXT:    vwaddu.vv v8, v10, v11
; V-NEXT:    li a0, -1
; V-NEXT:    vwmaccu.vx v8, a0, v11
; V-NEXT:    ret
;
; ZVBB-LABEL: interleave_addsub_1:
; ZVBB:       # %bb.0:
; ZVBB-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; ZVBB-NEXT:    vwaddu.vv v10, v8, v9
; ZVBB-NEXT:    vwsubu.vv v11, v8, v9
; ZVBB-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVBB-NEXT:    vwsll.vi v8, v11, 16
; ZVBB-NEXT:    vwaddu.wv v8, v8, v10
; ZVBB-NEXT:    ret
  %a = zext <4 x i8> %x to <4 x i32>
  %b = zext <4 x i8> %y to <4 x i32>
  %c = add <4 x i32> %a, %b
  %d = sub <4 x i32> %a, %b
  %e = shl <4 x i32> %d, <i32 16, i32 16, i32 16, i32 16>
  %f = or <4 x i32> %e, %c
  ret <4 x i32> %f
}

; Swap add operands
define <4 x i32> @interleave_addsub_2(<4 x i8> %x, <4 x i8> %y) {
; V-LABEL: interleave_addsub_2:
; V:       # %bb.0:
; V-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; V-NEXT:    vwaddu.vv v10, v8, v9
; V-NEXT:    vwsubu.vv v11, v8, v9
; V-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; V-NEXT:    vwaddu.vv v8, v10, v11
; V-NEXT:    li a0, -1
; V-NEXT:    vwmaccu.vx v8, a0, v11
; V-NEXT:    ret
;
; ZVBB-LABEL: interleave_addsub_2:
; ZVBB:       # %bb.0:
; ZVBB-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; ZVBB-NEXT:    vwaddu.vv v10, v8, v9
; ZVBB-NEXT:    vwsubu.vv v11, v8, v9
; ZVBB-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVBB-NEXT:    vwsll.vi v8, v11, 16
; ZVBB-NEXT:    vwaddu.wv v8, v8, v10
; ZVBB-NEXT:    ret
  %a = zext <4 x i8> %x to <4 x i32>
  %b = zext <4 x i8> %y to <4 x i32>
  %c = add <4 x i32> %b, %a
  %d = sub <4 x i32> %a, %b
  %e = shl <4 x i32> %d, <i32 16, i32 16, i32 16, i32 16>
  %f = or <4 x i32> %e, %c
  ret <4 x i32> %f
}

; Try i64 and swap the or operands.
define <4 x i64> @interleave_addsub_3(<4 x i16> %x, <4 x i16> %y) {
; V-LABEL: interleave_addsub_3:
; V:       # %bb.0:
; V-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; V-NEXT:    vwaddu.vv v10, v8, v9
; V-NEXT:    vwsubu.vv v11, v8, v9
; V-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; V-NEXT:    vwaddu.vv v8, v10, v11
; V-NEXT:    li a0, -1
; V-NEXT:    vwmaccu.vx v8, a0, v11
; V-NEXT:    ret
;
; ZVBB-LABEL: interleave_addsub_3:
; ZVBB:       # %bb.0:
; ZVBB-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVBB-NEXT:    vwaddu.vv v10, v8, v9
; ZVBB-NEXT:    vwsubu.vv v11, v8, v9
; ZVBB-NEXT:    li a0, 32
; ZVBB-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVBB-NEXT:    vwsll.vx v8, v11, a0
; ZVBB-NEXT:    vwaddu.wv v8, v8, v10
; ZVBB-NEXT:    ret
  %a = zext <4 x i16> %x to <4 x i64>
  %b = zext <4 x i16> %y to <4 x i64>
  %c = add <4 x i64> %a, %b
  %d = sub <4 x i64> %a, %b
  %e = shl <4 x i64> %d, <i64 32, i64 32, i64 32, i64 32>
  %f = or <4 x i64> %c, %e
  ret <4 x i64> %f
}

; Try i64 and swap the or and add operands.
define <4 x i64> @interleave_addsub_4(<4 x i16> %x, <4 x i16> %y) {
; V-LABEL: interleave_addsub_4:
; V:       # %bb.0:
; V-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; V-NEXT:    vwaddu.vv v10, v8, v9
; V-NEXT:    vwsubu.vv v11, v8, v9
; V-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; V-NEXT:    vwaddu.vv v8, v10, v11
; V-NEXT:    li a0, -1
; V-NEXT:    vwmaccu.vx v8, a0, v11
; V-NEXT:    ret
;
; ZVBB-LABEL: interleave_addsub_4:
; ZVBB:       # %bb.0:
; ZVBB-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVBB-NEXT:    vwaddu.vv v10, v8, v9
; ZVBB-NEXT:    vwsubu.vv v11, v8, v9
; ZVBB-NEXT:    li a0, 32
; ZVBB-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVBB-NEXT:    vwsll.vx v8, v11, a0
; ZVBB-NEXT:    vwaddu.wv v8, v8, v10
; ZVBB-NEXT:    ret
  %a = zext <4 x i16> %x to <4 x i64>
  %b = zext <4 x i16> %y to <4 x i64>
  %c = add <4 x i64> %b, %a
  %d = sub <4 x i64> %a, %b
  %e = shl <4 x i64> %d, <i64 32, i64 32, i64 32, i64 32>
  %f = or <4 x i64> %c, %e
  ret <4 x i64> %f
}

; Negative test, wrong shift amount.
define <4 x i32> @interleave_addsub_5(<4 x i8> %x, <4 x i8> %y) {
; CHECK-LABEL: interleave_addsub_5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vzext.vf2 v10, v8
; CHECK-NEXT:    vzext.vf2 v8, v9
; CHECK-NEXT:    vwaddu.vv v9, v10, v8
; CHECK-NEXT:    vwsubu.vv v11, v10, v8
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vsll.vi v8, v11, 8
; CHECK-NEXT:    vor.vv v8, v8, v9
; CHECK-NEXT:    ret
  %a = zext <4 x i8> %x to <4 x i32>
  %b = zext <4 x i8> %y to <4 x i32>
  %c = add <4 x i32> %a, %b
  %d = sub <4 x i32> %a, %b
  %e = shl <4 x i32> %d, <i32 8, i32 8, i32 8, i32 8>
  %f = or <4 x i32> %e, %c
  ret <4 x i32> %f
}

