; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -target-abi=ilp32d -mattr=+m,+v,+zfh,+zvfh,+f,+d | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -target-abi=lp64d -mattr=+m,+v,+zfh,+zvfh,+f,+d | FileCheck %s

declare <2 x half> @llvm.vp.sqrt.v2f16(<2 x half>, <2 x i1>, i32)
declare <4 x half> @llvm.vp.sqrt.v4f16(<4 x half>, <4 x i1>, i32)
declare <8 x half> @llvm.vp.sqrt.v8f16(<8 x half>, <8 x i1>, i32)
declare <2 x float> @llvm.vp.sqrt.v2f32(<2 x float>, <2 x i1>, i32)
declare <4 x float> @llvm.vp.sqrt.v4f32(<4 x float>, <4 x i1>, i32)
declare <8 x float> @llvm.vp.sqrt.v8f32(<8 x float>, <8 x i1>, i32)
declare <2 x double> @llvm.vp.sqrt.v2f64(<2 x double>, <2 x i1>, i32)
declare <4 x double> @llvm.vp.sqrt.v4f64(<4 x double>, <4 x i1>, i32)
declare <8 x double> @llvm.vp.sqrt.v8f64(<8 x double>, <8 x i1>, i32)

declare <2 x half> @llvm.vp.fdiv.v2f16(<2 x half>, <2 x half>, <2 x i1>, i32)
declare <4 x half> @llvm.vp.fdiv.v4f16(<4 x half>, <4 x half>, <4 x i1>, i32)
declare <8 x half> @llvm.vp.fdiv.v8f16(<8 x half>, <8 x half>, <8 x i1>, i32)
declare <2 x float> @llvm.vp.fdiv.v2f32(<2 x float>, <2 x float>, <2 x i1>, i32)
declare <4 x float> @llvm.vp.fdiv.v4f32(<4 x float>, <4 x float>, <4 x i1>, i32)
declare <8 x float> @llvm.vp.fdiv.v8f32(<8 x float>, <8 x float>, <8 x i1>, i32)
declare <2 x double> @llvm.vp.fdiv.v2f64(<2 x double>, <2 x double>, <2 x i1>, i32)
declare <4 x double> @llvm.vp.fdiv.v4f64(<4 x double>, <4 x double>, <4 x i1>, i32)
declare <8 x double> @llvm.vp.fdiv.v8f64(<8 x double>, <8 x double>, <8 x i1>, i32)

define <2 x half> @sqrt_v2f16(<2 x half> %a, <2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a1, 1024
; CHECK-NEXT:    fmv.h.x fa5, a1
; CHECK-NEXT:    lui a1, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa4, %lo(.LCPI0_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI0_1)
; CHECK-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_1)(a1)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vfmv.v.f v11, fa4
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <2 x half> @llvm.vp.sqrt.v2f16(<2 x half> %a, <2 x i1> %m, i32 %evl)
  ret <2 x half> %1
}

define <4 x half> @sqrt_v4f16(<4 x half> %a, <4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a1, 1024
; CHECK-NEXT:    fmv.h.x fa5, a1
; CHECK-NEXT:    lui a1, %hi(.LCPI1_0)
; CHECK-NEXT:    flh fa4, %lo(.LCPI1_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI1_1)
; CHECK-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    flh fa5, %lo(.LCPI1_1)(a1)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vfmv.v.f v11, fa4
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <4 x half> @llvm.vp.sqrt.v4f16(<4 x half> %a, <4 x i1> %m, i32 %evl)
  ret <4 x half> %1
}

define <8 x half> @sqrt_v8f16(<8 x half> %a, <8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a1, 1024
; CHECK-NEXT:    fmv.h.x fa5, a1
; CHECK-NEXT:    lui a1, %hi(.LCPI2_0)
; CHECK-NEXT:    flh fa4, %lo(.LCPI2_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI2_1)
; CHECK-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    flh fa5, %lo(.LCPI2_1)(a1)
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v11, fa4
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <8 x half> @llvm.vp.sqrt.v8f16(<8 x half> %a, <8 x i1> %m, i32 %evl)
  ret <8 x half> %1
}

define <2 x float> @sqrt_v2f32(<2 x float> %a, <2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    lui a1, 782336
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    lui a1, 2048
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vfmadd.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v10, v11, fa5, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vfmul.vv v9, v10, v9, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; CHECK-NEXT:    vmerge.vim v8, v9, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <2 x float> @llvm.vp.sqrt.v2f32(<2 x float> %a, <2 x i1> %m, i32 %evl)
  ret <2 x float> %1
}

define <4 x float> @sqrt_v4f32(<4 x float> %a, <4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    lui a1, 782336
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    lui a1, 2048
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vfmadd.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v10, v11, fa5, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vfmul.vv v9, v10, v9, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; CHECK-NEXT:    vmerge.vim v8, v9, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <4 x float> @llvm.vp.sqrt.v4f32(<4 x float> %a, <4 x i1> %m, i32 %evl)
  ret <4 x float> %1
}

define <8 x float> @sqrt_v8f32(<8 x float> %a, <8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    lui a1, 782336
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    lui a1, 2048
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfmul.vv v14, v8, v12, v0.t
; CHECK-NEXT:    vmv2r.v v16, v12
; CHECK-NEXT:    vfmadd.vv v16, v14, v10, v0.t
; CHECK-NEXT:    vfmul.vf v12, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v16, v0.t
; CHECK-NEXT:    vfmul.vv v14, v8, v12, v0.t
; CHECK-NEXT:    vfmadd.vv v12, v14, v10, v0.t
; CHECK-NEXT:    vfmul.vf v10, v14, fa5, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vfmul.vv v10, v10, v12, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; CHECK-NEXT:    vmerge.vim v8, v10, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <8 x float> @llvm.vp.sqrt.v8f32(<8 x float> %a, <8 x i1> %m, i32 %evl)
  ret <8 x float> %1
}

define <2 x double> @sqrt_v2f64(<2 x double> %a, <2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI6_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI6_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI6_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI6_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI6_2)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    fld fa5, %lo(.LCPI6_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vfmadd.vv v9, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v10, v11, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v9, v10, v9, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; CHECK-NEXT:    vmerge.vim v8, v9, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <2 x double> @llvm.vp.sqrt.v2f64(<2 x double> %a, <2 x i1> %m, i32 %evl)
  ret <2 x double> %1
}

define <4 x double> @sqrt_v4f64(<4 x double> %a, <4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI7_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI7_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI7_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI7_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI7_2)
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vfmv.v.f v12, fa5
; CHECK-NEXT:    fld fa5, %lo(.LCPI7_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfmul.vv v14, v8, v10, v0.t
; CHECK-NEXT:    vmv2r.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v14, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v14, v8, v10, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v14, v12, v0.t
; CHECK-NEXT:    vfmul.vf v12, v14, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v10, v12, v10, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; CHECK-NEXT:    vmerge.vim v8, v10, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <4 x double> @llvm.vp.sqrt.v4f64(<4 x double> %a, <4 x i1> %m, i32 %evl)
  ret <4 x double> %1
}

define <8 x double> @sqrt_v8f64(<8 x double> %a, <8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI8_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI8_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI8_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI8_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI8_2)
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vfmv.v.f v16, fa5
; CHECK-NEXT:    fld fa5, %lo(.LCPI8_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfmul.vv v20, v8, v12, v0.t
; CHECK-NEXT:    vmv4r.v v24, v12
; CHECK-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; CHECK-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v24, v0.t
; CHECK-NEXT:    vfmul.vv v20, v8, v12, v0.t
; CHECK-NEXT:    vmv.v.v v24, v12
; CHECK-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; CHECK-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v24, v0.t
; CHECK-NEXT:    vfmul.vv v20, v8, v12, v0.t
; CHECK-NEXT:    vfmadd.vv v12, v20, v16, v0.t
; CHECK-NEXT:    vfmul.vf v16, v20, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v12, v16, v12, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; CHECK-NEXT:    vmerge.vim v8, v12, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <8 x double> @llvm.vp.sqrt.v8f64(<8 x double> %a, <8 x i1> %m, i32 %evl)
  ret <8 x double> %1
}

define <2 x half> @sqrt_zero_steps_v2f16(<2 x half> %a, <2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    li a0, 1024
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <2 x half> @llvm.vp.sqrt.v2f16(<2 x half> %a, <2 x i1> %m, i32 %evl)
  ret <2 x half> %1
}

define <4 x half> @sqrt_zero_steps_v4f16(<4 x half> %a, <4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    li a0, 1024
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <4 x half> @llvm.vp.sqrt.v4f16(<4 x half> %a, <4 x i1> %m, i32 %evl)
  ret <4 x half> %1
}

define <8 x half> @sqrt_zero_steps_v8f16(<8 x half> %a, <8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    li a0, 1024
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <8 x half> @llvm.vp.sqrt.v8f16(<8 x half> %a, <8 x i1> %m, i32 %evl)
  ret <8 x half> %1
}

define <2 x float> @sqrt_zero_steps_v2f32(<2 x float> %a, <2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    lui a0, 2048
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <2 x float> @llvm.vp.sqrt.v2f32(<2 x float> %a, <2 x i1> %m, i32 %evl)
  ret <2 x float> %1
}

define <4 x float> @sqrt_zero_steps_v4f32(<4 x float> %a, <4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    lui a0, 2048
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <4 x float> @llvm.vp.sqrt.v4f32(<4 x float> %a, <4 x i1> %m, i32 %evl)
  ret <4 x float> %1
}

define <8 x float> @sqrt_zero_steps_v8f32(<8 x float> %a, <8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfabs.v v12, v8, v0.t
; CHECK-NEXT:    lui a0, 2048
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <8 x float> @llvm.vp.sqrt.v8f32(<8 x float> %a, <8 x i1> %m, i32 %evl)
  ret <8 x float> %1
}

define <2 x double> @sqrt_zero_steps_v2f64(<2 x double> %a, <2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI15_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI15_0)(a0)
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <2 x double> @llvm.vp.sqrt.v2f64(<2 x double> %a, <2 x i1> %m, i32 %evl)
  ret <2 x double> %1
}

define <4 x double> @sqrt_zero_steps_v4f64(<4 x double> %a, <4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI16_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI16_0)(a0)
; CHECK-NEXT:    vfabs.v v12, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <4 x double> @llvm.vp.sqrt.v4f64(<4 x double> %a, <4 x i1> %m, i32 %evl)
  ret <4 x double> %1
}

define <8 x double> @sqrt_zero_steps_v8f64(<8 x double> %a, <8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI17_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI17_0)(a0)
; CHECK-NEXT:    vfabs.v v16, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
  %1 = tail call fast <8 x double> @llvm.vp.sqrt.v8f64(<8 x double> %a, <8 x i1> %m, i32 %evl)
  ret <8 x double> %1
}
define <2 x half> @rsqrt_v2f16(<2 x half> %a, <2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI18_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI18_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI18_1)
; CHECK-NEXT:    flh fa4, %lo(.LCPI18_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI18_2)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI18_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v11, v9
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <2 x half> %ins, <2 x half> poison, <2 x i32> zeroinitializer
  %1 = tail call fast <2 x half> @llvm.vp.sqrt.v2f16(<2 x half> %a, <2 x i1> %m, i32 %evl)
  %2 = call fast <2 x half> @llvm.vp.fdiv.v2f16(<2 x half> %splat, <2 x half>  %1,  <2 x i1> %m, i32 %evl)
  ret <2 x half> %2
}

define <4 x half> @rsqrt_v4f16(<4 x half> %a, <4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI19_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI19_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI19_1)
; CHECK-NEXT:    flh fa4, %lo(.LCPI19_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI19_2)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI19_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v11, v9
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <4 x half> %ins, <4 x half> poison, <4 x i32> zeroinitializer
  %1 = tail call fast <4 x half> @llvm.vp.sqrt.v4f16(<4 x half> %a, <4 x i1> %m, i32 %evl)
  %2 = call fast <4 x half> @llvm.vp.fdiv.v4f16(<4 x half> %splat, <4 x half>  %1,  <4 x i1> %m, i32 %evl)
  ret <4 x half> %2
}

define <8 x half> @rsqrt_v8f16(<8 x half> %a, <8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI20_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI20_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI20_1)
; CHECK-NEXT:    flh fa4, %lo(.LCPI20_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI20_2)
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI20_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v11, v9
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <8 x half> %ins, <8 x half> poison, <8 x i32> zeroinitializer
  %1 = tail call fast <8 x half> @llvm.vp.sqrt.v8f16(<8 x half> %a, <8 x i1> %m, i32 %evl)
  %2 = call fast <8 x half> @llvm.vp.fdiv.v8f16(<8 x half> %splat, <8 x half>  %1,  <8 x i1> %m, i32 %evl)
  ret <8 x half> %2
}

define <2 x float> @rsqrt_v2f32(<2 x float> %a, <2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    lui a1, 782336
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    lui a1, 260096
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v11, v9
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <2 x float> %ins, <2 x float> poison, <2 x i32> zeroinitializer
  %1 = tail call fast <2 x float> @llvm.vp.sqrt.v2f32(<2 x float> %a, <2 x i1> %m, i32 %evl)
  %2 = call fast <2 x float> @llvm.vp.fdiv.v2f32(<2 x float> %splat, <2 x float>  %1,  <2 x i1> %m, i32 %evl)
  ret <2 x float> %2
}

define <4 x float> @rsqrt_v4f32(<4 x float> %a, <4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v10, a1
; CHECK-NEXT:    lui a1, 782336
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    lui a1, 260096
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v11, v9
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <4 x float> %ins, <4 x float> poison, <4 x i32> zeroinitializer
  %1 = tail call fast <4 x float> @llvm.vp.sqrt.v4f32(<4 x float> %a, <4 x i1> %m, i32 %evl)
  %2 = call fast <4 x float> @llvm.vp.fdiv.v4f32(<4 x float> %splat, <4 x float>  %1,  <4 x i1> %m, i32 %evl)
  ret <4 x float> %2
}

define <8 x float> @rsqrt_v8f32(<8 x float> %a, <8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v12, a1
; CHECK-NEXT:    lui a1, 782336
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    lui a1, 260096
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfmul.vv v14, v8, v10, v0.t
; CHECK-NEXT:    vmv2r.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v14, v10
; CHECK-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa5, v0.t
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vfmul.vv v8, v8, v14, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <8 x float> %ins, <8 x float> poison, <8 x i32> zeroinitializer
  %1 = tail call fast <8 x float> @llvm.vp.sqrt.v8f32(<8 x float> %a, <8 x i1> %m, i32 %evl)
  %2 = call fast <8 x float> @llvm.vp.fdiv.v8f32(<8 x float> %splat, <8 x float>  %1,  <8 x i1> %m, i32 %evl)
  ret <8 x float> %2
}

define <2 x double> @rsqrt_v2f64(<2 x double> %a, <2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI24_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI24_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI24_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI24_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI24_2)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v10, fa5
; CHECK-NEXT:    fld fa5, %lo(.LCPI24_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v11, v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; CHECK-NEXT:    vfmul.vf v9, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v11, v9
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <2 x double> %ins, <2 x double> poison, <2 x i32> zeroinitializer
  %1 = tail call fast <2 x double> @llvm.vp.sqrt.v2f64(<2 x double> %a, <2 x i1> %m, i32 %evl)
  %2 = call fast <2 x double> @llvm.vp.fdiv.v2f64(<2 x double> %splat, <2 x double>  %1,  <2 x i1> %m, i32 %evl)
  ret <2 x double> %2
}

define <4 x double> @rsqrt_v4f64(<4 x double> %a, <4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI25_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI25_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI25_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI25_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI25_2)
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vfmv.v.f v12, fa5
; CHECK-NEXT:    fld fa5, %lo(.LCPI25_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfmul.vv v14, v8, v10, v0.t
; CHECK-NEXT:    vmv2r.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v14, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v14, v10
; CHECK-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v14, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <4 x double> %ins, <4 x double> poison, <4 x i32> zeroinitializer
  %1 = tail call fast <4 x double> @llvm.vp.sqrt.v4f64(<4 x double> %a, <4 x i1> %m, i32 %evl)
  %2 = call fast <4 x double> @llvm.vp.fdiv.v4f64(<4 x double> %splat, <4 x double>  %1,  <4 x i1> %m, i32 %evl)
  ret <4 x double> %2
}

define <8 x double> @rsqrt_v8f64(<8 x double> %a, <8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    lui a1, %hi(.LCPI26_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI26_0)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI26_1)
; CHECK-NEXT:    fld fa4, %lo(.LCPI26_1)(a1)
; CHECK-NEXT:    lui a1, %hi(.LCPI26_2)
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vfmv.v.f v16, fa5
; CHECK-NEXT:    fld fa5, %lo(.LCPI26_2)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfmul.vv v20, v8, v12, v0.t
; CHECK-NEXT:    vmv4r.v v24, v12
; CHECK-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; CHECK-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v24, v0.t
; CHECK-NEXT:    vfmul.vv v20, v8, v12, v0.t
; CHECK-NEXT:    vmv.v.v v24, v12
; CHECK-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; CHECK-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v24, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vmv.v.v v20, v12
; CHECK-NEXT:    vfmadd.vv v20, v8, v16, v0.t
; CHECK-NEXT:    vfmul.vf v8, v12, fa4, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v20, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <8 x double> %ins, <8 x double> poison, <8 x i32> zeroinitializer
  %1 = tail call fast <8 x double> @llvm.vp.sqrt.v8f64(<8 x double> %a, <8 x i1> %m, i32 %evl)
  %2 = call fast <8 x double> @llvm.vp.fdiv.v8f64(<8 x double> %splat, <8 x double>  %1,  <8 x i1> %m, i32 %evl)
  ret <8 x double> %2
}

define <2 x half> @rsqrt_zero_steps_v2f16(<2 x half> %a, <2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI27_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI27_0)(a0)
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <2 x half> %ins, <2 x half> poison, <2 x i32> zeroinitializer
  %1 = tail call fast <2 x half> @llvm.vp.sqrt.v2f16(<2 x half> %a, <2 x i1> %m, i32 %evl)
  %2 = call fast <2 x half> @llvm.vp.fdiv.v2f16(<2 x half> %splat, <2 x half>  %1,  <2 x i1> %m, i32 %evl)
  ret <2 x half> %2
}

define <4 x half> @rsqrt_zero_steps_v4f16(<4 x half> %a, <4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI28_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI28_0)(a0)
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <4 x half> %ins, <4 x half> poison, <4 x i32> zeroinitializer
  %1 = tail call fast <4 x half> @llvm.vp.sqrt.v4f16(<4 x half> %a, <4 x i1> %m, i32 %evl)
  %2 = call fast <4 x half> @llvm.vp.fdiv.v4f16(<4 x half> %splat, <4 x half>  %1,  <4 x i1> %m, i32 %evl)
  ret <4 x half> %2
}

define <8 x half> @rsqrt_zero_steps_v8f16(<8 x half> %a, <8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI29_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI29_0)(a0)
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <8 x half> %ins, <8 x half> poison, <8 x i32> zeroinitializer
  %1 = tail call fast <8 x half> @llvm.vp.sqrt.v8f16(<8 x half> %a, <8 x i1> %m, i32 %evl)
  %2 = call fast <8 x half> @llvm.vp.fdiv.v8f16(<8 x half> %splat, <8 x half>  %1,  <8 x i1> %m, i32 %evl)
  ret <8 x half> %2
}

define <2 x float> @rsqrt_zero_steps_v2f32(<2 x float> %a, <2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <2 x float> %ins, <2 x float> poison, <2 x i32> zeroinitializer
  %1 = tail call fast <2 x float> @llvm.vp.sqrt.v2f32(<2 x float> %a, <2 x i1> %m, i32 %evl)
  %2 = call fast <2 x float> @llvm.vp.fdiv.v2f32(<2 x float> %splat, <2 x float>  %1,  <2 x i1> %m, i32 %evl)
  ret <2 x float> %2
}

define <4 x float> @rsqrt_zero_steps_v4f32(<4 x float> %a, <4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <4 x float> %ins, <4 x float> poison, <4 x i32> zeroinitializer
  %1 = tail call fast <4 x float> @llvm.vp.sqrt.v4f32(<4 x float> %a, <4 x i1> %m, i32 %evl)
  %2 = call fast <4 x float> @llvm.vp.fdiv.v4f32(<4 x float> %splat, <4 x float>  %1,  <4 x i1> %m, i32 %evl)
  ret <4 x float> %2
}

define <8 x float> @rsqrt_zero_steps_v8f32(<8 x float> %a, <8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <8 x float> %ins, <8 x float> poison, <8 x i32> zeroinitializer
  %1 = tail call fast <8 x float> @llvm.vp.sqrt.v8f32(<8 x float> %a, <8 x i1> %m, i32 %evl)
  %2 = call fast <8 x float> @llvm.vp.fdiv.v8f32(<8 x float> %splat, <8 x float>  %1,  <8 x i1> %m, i32 %evl)
  ret <8 x float> %2
}

define <2 x double> @rsqrt_zero_steps_v2f64(<2 x double> %a, <2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI33_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI33_0)(a0)
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <2 x double> %ins, <2 x double> poison, <2 x i32> zeroinitializer
  %1 = tail call fast <2 x double> @llvm.vp.sqrt.v2f64(<2 x double> %a, <2 x i1> %m, i32 %evl)
  %2 = call fast <2 x double> @llvm.vp.fdiv.v2f64(<2 x double> %splat, <2 x double>  %1,  <2 x i1> %m, i32 %evl)
  ret <2 x double> %2
}

define <4 x double> @rsqrt_zero_steps_v4f64(<4 x double> %a, <4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI34_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI34_0)(a0)
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <4 x double> %ins, <4 x double> poison, <4 x i32> zeroinitializer
  %1 = tail call fast <4 x double> @llvm.vp.sqrt.v4f64(<4 x double> %a, <4 x i1> %m, i32 %evl)
  %2 = call fast <4 x double> @llvm.vp.fdiv.v4f64(<4 x double> %splat, <4 x double>  %1,  <4 x i1> %m, i32 %evl)
  ret <4 x double> %2
}

define <8 x double> @rsqrt_zero_steps_v8f64(<8 x double> %a, <8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI35_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI35_0)(a0)
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
  %ins = insertelement <8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <8 x double> %ins, <8 x double> poison, <8 x i32> zeroinitializer
  %1 = tail call fast <8 x double> @llvm.vp.sqrt.v8f64(<8 x double> %a, <8 x i1> %m, i32 %evl)
  %2 = call fast <8 x double> @llvm.vp.fdiv.v8f64(<8 x double> %splat, <8 x double>  %1,  <8 x i1> %m, i32 %evl)
  ret <8 x double> %2
}

attributes #0 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-sqrt" }
attributes #1 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-sqrt:0" }
