; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=128 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=128 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK

define <4 x i32> @test_0_0(<4 x i32> %0, <4 x i32> %1) {
; CHECK-LABEL: test_0_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v9, 0
; CHECK-NEXT:    ret
  %3 = extractelement <4 x i32> %1, i64 0
  %4 = insertelement <4 x i32> %0, i32 %3, i64 0
  ret <4 x i32> %4
}

define <4 x i32> @test_0_1(<4 x i32> %0, <4 x i32> %1) {
; CHECK-LABEL: test_0_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, tu, ma
; CHECK-NEXT:    vslidedown.vi v8, v9, 1
; CHECK-NEXT:    ret
  %3 = extractelement <4 x i32> %1, i64 1
  %4 = insertelement <4 x i32> %0, i32 %3, i64 0
  ret <4 x i32> %4
}

define <4 x i32> @test_1_0(<4 x i32> %0, <4 x i32> %1) {
; CHECK-LABEL: test_1_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v9, 1
; CHECK-NEXT:    ret
  %3 = extractelement <4 x i32> %1, i64 0
  %4 = insertelement <4 x i32> %0, i32 %3, i64 1
  ret <4 x i32> %4
}

define <4 x i32> @test_1_1(<4 x i32> %0, <4 x i32> %1) {
; CHECK-LABEL: test_1_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, tu, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 1
; CHECK-NEXT:    vslideup.vi v8, v9, 1
; CHECK-NEXT:    ret
  %3 = extractelement <4 x i32> %1, i64 1
  %4 = insertelement <4 x i32> %0, i32 %3, i64 1
  ret <4 x i32> %4
}
