; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; SIFIVE
; RUN: llc -mtriple=riscv32 -mattr=+m,+v,+zfh,+zvfh -target-abi=ilp32d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+m,+v,+zfh,+zvfh -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s

declare <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double>, <vscale x 16 x double>, metadata, <vscale x 16 x i1>, i32)

define <vscale x 16 x i1> @fcmp_oeq_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_oeq_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"oeq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_oeq_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_oeq_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"oeq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_oeq_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_oeq_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB2_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"oeq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ogt_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ogt_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v16, v24, v16, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v0, v8, v24, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ogt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ogt_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ogt_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB4_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ogt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ogt_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ogt_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB5_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ogt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_oge_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_oge_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v16, v24, v16, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB6_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB6_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v0, v8, v24, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"oge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_oge_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_oge_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB7_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB7_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"oge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_oge_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_oge_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB8_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"oge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_olt_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_olt_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB9_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB9_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"olt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_olt_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_olt_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB10_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB10_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"olt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_olt_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_olt_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB11_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB11_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"olt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ole_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ole_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB12_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB12_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ole", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ole_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ole_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB13_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB13_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ole", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ole_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ole_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB14_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB14_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ole", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_one_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_one_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    srli a1, a3, 3
; CHECK-NEXT:    slli a4, a3, 3
; CHECK-NEXT:    sub a5, a2, a3
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    add a4, a0, a4
; CHECK-NEXT:    vl8re64.v v24, (a4)
; CHECK-NEXT:    sltu a4, a2, a5
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a4, a4, a5
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v6, v16, v24, v0.t
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    vmflt.vv v16, v24, v16, v0.t
; CHECK-NEXT:    vmor.mm v16, v16, v6
; CHECK-NEXT:    bltu a2, a3, .LBB15_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a3
; CHECK-NEXT:  .LBB15_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v17, v24, v8, v0.t
; CHECK-NEXT:    vmflt.vv v8, v8, v24, v0.t
; CHECK-NEXT:    vmor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"one", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_one_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_one_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v25, v16, fa0, v0.t
; CHECK-NEXT:    vmfgt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmor.mm v16, v16, v25
; CHECK-NEXT:    bltu a0, a2, .LBB16_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB16_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v17, v8, fa0, v0.t
; CHECK-NEXT:    vmfgt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"one", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_one_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_one_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v25, v16, fa0, v0.t
; CHECK-NEXT:    vmflt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmor.mm v16, v16, v25
; CHECK-NEXT:    bltu a0, a2, .LBB17_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB17_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v17, v8, fa0, v0.t
; CHECK-NEXT:    vmflt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"one", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ord_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ord_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    srli a1, a3, 3
; CHECK-NEXT:    slli a4, a3, 3
; CHECK-NEXT:    sub a5, a2, a3
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    add a4, a0, a4
; CHECK-NEXT:    vl8re64.v v24, (a4)
; CHECK-NEXT:    sltu a4, a2, a5
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a4, a4, a5
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vv v6, v24, v24, v0.t
; CHECK-NEXT:    vl8re64.v v24, (a0)
; CHECK-NEXT:    vmfeq.vv v16, v16, v16, v0.t
; CHECK-NEXT:    vmand.mm v16, v16, v6
; CHECK-NEXT:    bltu a2, a3, .LBB18_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a3
; CHECK-NEXT:  .LBB18_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vv v17, v24, v24, v0.t
; CHECK-NEXT:    vmfeq.vv v8, v8, v8, v0.t
; CHECK-NEXT:    vmand.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ord", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ord_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ord_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m8, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    vfmv.v.f v24, fa0
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v6, v24, fa0, v0.t
; CHECK-NEXT:    vmfeq.vv v16, v16, v16, v0.t
; CHECK-NEXT:    vmand.mm v16, v16, v6
; CHECK-NEXT:    bltu a0, a2, .LBB19_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB19_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v17, v24, fa0, v0.t
; CHECK-NEXT:    vmfeq.vv v8, v8, v8, v0.t
; CHECK-NEXT:    vmand.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ord", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ord_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ord_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m8, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    vfmv.v.f v24, fa0
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v6, v24, fa0, v0.t
; CHECK-NEXT:    vmfeq.vv v16, v16, v16, v0.t
; CHECK-NEXT:    vmand.mm v16, v6, v16
; CHECK-NEXT:    bltu a0, a2, .LBB20_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB20_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfeq.vf v17, v24, fa0, v0.t
; CHECK-NEXT:    vmfeq.vv v8, v8, v8, v0.t
; CHECK-NEXT:    vmand.mm v0, v17, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ord", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ueq_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ueq_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    srli a1, a3, 3
; CHECK-NEXT:    slli a4, a3, 3
; CHECK-NEXT:    sub a5, a2, a3
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    add a4, a0, a4
; CHECK-NEXT:    vl8re64.v v24, (a4)
; CHECK-NEXT:    sltu a4, a2, a5
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a4, a4, a5
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v6, v16, v24, v0.t
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    vmflt.vv v16, v24, v16, v0.t
; CHECK-NEXT:    vmnor.mm v16, v16, v6
; CHECK-NEXT:    bltu a2, a3, .LBB21_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a3
; CHECK-NEXT:  .LBB21_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v17, v24, v8, v0.t
; CHECK-NEXT:    vmflt.vv v8, v8, v24, v0.t
; CHECK-NEXT:    vmnor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ueq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ueq_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ueq_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v25, v16, fa0, v0.t
; CHECK-NEXT:    vmfgt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnor.mm v16, v16, v25
; CHECK-NEXT:    bltu a0, a2, .LBB22_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB22_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v17, v8, fa0, v0.t
; CHECK-NEXT:    vmfgt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ueq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ueq_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ueq_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v25, v16, fa0, v0.t
; CHECK-NEXT:    vmflt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnor.mm v16, v16, v25
; CHECK-NEXT:    bltu a0, a2, .LBB23_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB23_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v17, v8, fa0, v0.t
; CHECK-NEXT:    vmflt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ueq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ugt_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ugt_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v16, v16, v24, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a2, a1, .LBB24_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB24_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v8, v24, v8, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ugt_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ugt_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB25_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB25_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ugt_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ugt_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB26_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB26_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_uge_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_uge_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v16, v16, v24, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a2, a1, .LBB27_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB27_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v8, v24, v8, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_uge_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_uge_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB28_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB28_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_uge_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_uge_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB29_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB29_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ult_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ult_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v16, v24, v16, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a2, a1, .LBB30_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB30_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vv v8, v8, v24, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ult_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ult_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB31_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB31_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfge.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ult_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ult_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB32_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB32_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfle.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ule_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ule_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v16, v24, v16, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a2, a1, .LBB33_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB33_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vv v8, v8, v24, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ule", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ule_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ule_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB34_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB34_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfgt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"ule", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_ule_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_ule_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    vmnot.m v16, v16
; CHECK-NEXT:    bltu a0, a2, .LBB35_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB35_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmflt.vf v8, v8, fa0, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"ule", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_une_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_une_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB36_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB36_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"une", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_une_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_une_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB37_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB37_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"une", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_une_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_une_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v16, v16, fa0, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB38_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB38_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v0, v8, fa0, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"une", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_uno_vv_nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_uno_vv_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    srli a1, a3, 3
; CHECK-NEXT:    slli a4, a3, 3
; CHECK-NEXT:    sub a5, a2, a3
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    add a4, a0, a4
; CHECK-NEXT:    vl8re64.v v24, (a4)
; CHECK-NEXT:    sltu a4, a2, a5
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a4, a4, a5
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vv v6, v24, v24, v0.t
; CHECK-NEXT:    vl8re64.v v24, (a0)
; CHECK-NEXT:    vmfne.vv v16, v16, v16, v0.t
; CHECK-NEXT:    vmor.mm v16, v16, v6
; CHECK-NEXT:    bltu a2, a3, .LBB39_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a3
; CHECK-NEXT:  .LBB39_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vv v17, v24, v24, v0.t
; CHECK-NEXT:    vmfne.vv v8, v8, v8, v0.t
; CHECK-NEXT:    vmor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"uno", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_uno_vf_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_uno_vf_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m8, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    vfmv.v.f v24, fa0
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v6, v24, fa0, v0.t
; CHECK-NEXT:    vmfne.vv v16, v16, v16, v0.t
; CHECK-NEXT:    vmor.mm v16, v16, v6
; CHECK-NEXT:    bltu a0, a2, .LBB40_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB40_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v17, v24, fa0, v0.t
; CHECK-NEXT:    vmfne.vv v8, v8, v8, v0.t
; CHECK-NEXT:    vmor.mm v0, v8, v17
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %va, <vscale x 16 x double> %vb, metadata !"uno", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @fcmp_uno_vf_swap_nxv16f64(<vscale x 16 x double> %va, double %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: fcmp_uno_vf_swap_nxv16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m8, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    vfmv.v.f v24, fa0
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v6, v24, fa0, v0.t
; CHECK-NEXT:    vmfne.vv v16, v16, v16, v0.t
; CHECK-NEXT:    vmor.mm v16, v6, v16
; CHECK-NEXT:    bltu a0, a2, .LBB41_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB41_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmfne.vf v17, v24, fa0, v0.t
; CHECK-NEXT:    vmfne.vv v8, v8, v8, v0.t
; CHECK-NEXT:    vmor.mm v0, v17, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x double> poison, double %b, i32 0
  %vb = shufflevector <vscale x 16 x double> %elt.head, <vscale x 16 x double> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.fcmp.nxv16f64(<vscale x 16 x double> %vb, <vscale x 16 x double> %va, metadata !"uno", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}
