; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=512 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=4 -O3 \
; RUN:   -riscv-mem-to-rvv-dlen-align=false -verify-machineinstrs < %s | FileCheck %s

define void @KnownSize(ptr nocapture %dst, i8 %val) {
; CHECK-LABEL: KnownSize:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 256
; CHECK-NEXT:    vsetvli a2, a2, e8, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    add a1, a0, a2
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    li a0, 248
; CHECK-NEXT:    add a3, a1, a2
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    add a1, a3, a2
; CHECK-NEXT:    vse8.v v8, (a3)
; CHECK-NEXT:    add a3, a1, a2
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    add a1, a3, a2
; CHECK-NEXT:    vse8.v v8, (a3)
; CHECK-NEXT:    add a3, a1, a2
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    add a2, a3, a2
; CHECK-NEXT:    vse8.v v8, (a3)
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i32 2040, i1 false)
  ret void
}

define void @KnownSize1(ptr nocapture %dst, i8 %val) {
; CHECK-LABEL: KnownSize1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 256
; CHECK-NEXT:    vsetvli a2, a2, e8, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    add a2, a0, a2
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    li a0, 128
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i32 384, i1 false)
  ret void
}

define void @KnownSize2(ptr nocapture %dst, i8 %val) {
; CHECK-LABEL: KnownSize2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    slli a2, a2, 11
; CHECK-NEXT:    vsetvli zero, a2, e8, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:  .LBB2_1: # %memset-forward-loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vsetvli a1, a2, e8, m4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    sub a2, a2, a1
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    bnez a2, .LBB2_1
; CHECK-NEXT:  # %bb.2: # %memset-post-loop
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i32 2048, i1 false)
  ret void
}


declare void @llvm.memset.p0.i8.i64(ptr noalias nocapture writeonly, i8 noalias readonly, i32, i1 immarg)
