; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK,RV64

; Integers

define {<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>} @vector_deinterleave_nxv16i1_nxv128i1(<vscale x 128 x i1> %vec) nounwind {
; CHECK-LABEL: vector_deinterleave_nxv16i1_nxv128i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmv1r.v v9, v0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    vmv.v.i v10, 0
; CHECK-NEXT:    srli a1, a0, 2
; CHECK-NEXT:    sub a2, a0, a1
; CHECK-NEXT:    vsetvli a3, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v0, a2
; CHECK-NEXT:    srli a0, a0, 1
; CHECK-NEXT:    vsetvli a3, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmerge.vim v22, v10, 1, v0
; CHECK-NEXT:    vsetvli a3, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v9, a0
; CHECK-NEXT:    vsetvli a3, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmerge.vim v20, v10, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v16, v10, 1, v0
; CHECK-NEXT:    vsetvli a3, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v9, a1
; CHECK-NEXT:    vsetvli a3, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmerge.vim v18, v10, 1, v0
; CHECK-NEXT:    vsetvli a3, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v8, a2
; CHECK-NEXT:    addi a2, sp, 16
; CHECK-NEXT:    vsetvli a3, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmerge.vim v30, v10, 1, v0
; CHECK-NEXT:    vsetvli a3, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v8, a0
; CHECK-NEXT:    vs8r.v v16, (a2)
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmerge.vim v28, v10, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vim v24, v10, 1, v0
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslidedown.vx v0, v8, a1
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vsetvli a1, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmerge.vim v26, v10, 1, v0
; CHECK-NEXT:    vs8r.v v24, (a0)
; CHECK-NEXT:    vsetvli a1, zero, e8, m1, ta, ma
; CHECK-NEXT:    vlseg8e8.v v16, (a2)
; CHECK-NEXT:    vlseg8e8.v v8, (a0)
; CHECK-NEXT:    vmv2r.v v24, v16
; CHECK-NEXT:    vmv2r.v v26, v18
; CHECK-NEXT:    vmv2r.v v28, v20
; CHECK-NEXT:    vmv2r.v v30, v22
; CHECK-NEXT:    vmv1r.v v25, v8
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmsne.vi v0, v24, 0
; CHECK-NEXT:    vmv1r.v v8, v17
; CHECK-NEXT:    vmsne.vi v8, v8, 0
; CHECK-NEXT:    vmv1r.v v27, v10
; CHECK-NEXT:    vmsne.vi v9, v26, 0
; CHECK-NEXT:    vmv1r.v v10, v19
; CHECK-NEXT:    vmsne.vi v10, v10, 0
; CHECK-NEXT:    vmv1r.v v29, v12
; CHECK-NEXT:    vmsne.vi v11, v28, 0
; CHECK-NEXT:    vmv1r.v v12, v21
; CHECK-NEXT:    vmsne.vi v12, v12, 0
; CHECK-NEXT:    vmv1r.v v31, v14
; CHECK-NEXT:    vmsne.vi v13, v30, 0
; CHECK-NEXT:    vmv1r.v v14, v23
; CHECK-NEXT:    vmsne.vi v14, v14, 0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %retval = call {<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>} @llvm.vector.deinterleave8.nxv128i1(<vscale x 128 x i1> %vec)
  ret {<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>} %retval
}

declare {<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>} @llvm.vector.deinterleave8.nxv128i1(<vscale x 128 x i1>)

define {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} @vector_deinterleave_nxv16i8_nxv128i8(<vscale x 128 x i8> %vec) nounwind {
; CHECK-LABEL: vector_deinterleave_nxv16i8_nxv128i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v8, (a0)
; CHECK-NEXT:    vs8r.v v16, (a1)
; CHECK-NEXT:    vsetvli a2, zero, e8, m1, ta, ma
; CHECK-NEXT:    vlseg8e8.v v0, (a0)
; CHECK-NEXT:    vlseg8e8.v v22, (a1)
; CHECK-NEXT:    vmv2r.v v8, v0
; CHECK-NEXT:    vmv1r.v v9, v22
; CHECK-NEXT:    vmv1r.v v22, v1
; CHECK-NEXT:    vmv2r.v v12, v2
; CHECK-NEXT:    vmv1r.v v13, v24
; CHECK-NEXT:    vmv1r.v v24, v3
; CHECK-NEXT:    vmv2r.v v16, v4
; CHECK-NEXT:    vmv1r.v v17, v26
; CHECK-NEXT:    vmv1r.v v26, v5
; CHECK-NEXT:    vmv2r.v v20, v6
; CHECK-NEXT:    vmv1r.v v21, v28
; CHECK-NEXT:    vmv1r.v v28, v7
; CHECK-NEXT:    vmv2r.v v10, v22
; CHECK-NEXT:    vmv2r.v v14, v24
; CHECK-NEXT:    vmv2r.v v18, v26
; CHECK-NEXT:    vmv2r.v v22, v28
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %retval = call {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} @llvm.vector.deinterleave8.nxv128i8(<vscale x 128 x i8> %vec)
  ret {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} %retval
}

declare {<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>} @llvm.vector.deinterleave8.nxv128i8(<vscale x 128 x i8>)

define {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} @vector_deinterleave_nxv8i16_nxv64i16(<vscale x 64 x i16> %vec) nounwind {
; CHECK-LABEL: vector_deinterleave_nxv8i16_nxv64i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v8, (a0)
; CHECK-NEXT:    vs8r.v v16, (a1)
; CHECK-NEXT:    vsetvli a2, zero, e16, m1, ta, ma
; CHECK-NEXT:    vlseg8e16.v v0, (a0)
; CHECK-NEXT:    vlseg8e16.v v22, (a1)
; CHECK-NEXT:    vmv2r.v v8, v0
; CHECK-NEXT:    vmv1r.v v9, v22
; CHECK-NEXT:    vmv1r.v v22, v1
; CHECK-NEXT:    vmv2r.v v12, v2
; CHECK-NEXT:    vmv1r.v v13, v24
; CHECK-NEXT:    vmv1r.v v24, v3
; CHECK-NEXT:    vmv2r.v v16, v4
; CHECK-NEXT:    vmv1r.v v17, v26
; CHECK-NEXT:    vmv1r.v v26, v5
; CHECK-NEXT:    vmv2r.v v20, v6
; CHECK-NEXT:    vmv1r.v v21, v28
; CHECK-NEXT:    vmv1r.v v28, v7
; CHECK-NEXT:    vmv2r.v v10, v22
; CHECK-NEXT:    vmv2r.v v14, v24
; CHECK-NEXT:    vmv2r.v v18, v26
; CHECK-NEXT:    vmv2r.v v22, v28
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %retval = call {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} @llvm.vector.deinterleave8.nxv64i16(<vscale x 64 x i16> %vec)
  ret {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} %retval
}

declare {<vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>} @llvm.vector.deinterleave8.nxv64i16(<vscale x 64 x i16>)

define {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} @vector_deinterleave_nxv4i32_nxv32i32(<vscale x 32 x i32> %vec) nounwind {
; CHECK-LABEL: vector_deinterleave_nxv4i32_nxv32i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v8, (a0)
; CHECK-NEXT:    vs8r.v v16, (a1)
; CHECK-NEXT:    vsetvli a2, zero, e32, m1, ta, ma
; CHECK-NEXT:    vlseg8e32.v v0, (a0)
; CHECK-NEXT:    vlseg8e32.v v22, (a1)
; CHECK-NEXT:    vmv2r.v v8, v0
; CHECK-NEXT:    vmv1r.v v9, v22
; CHECK-NEXT:    vmv1r.v v22, v1
; CHECK-NEXT:    vmv2r.v v12, v2
; CHECK-NEXT:    vmv1r.v v13, v24
; CHECK-NEXT:    vmv1r.v v24, v3
; CHECK-NEXT:    vmv2r.v v16, v4
; CHECK-NEXT:    vmv1r.v v17, v26
; CHECK-NEXT:    vmv1r.v v26, v5
; CHECK-NEXT:    vmv2r.v v20, v6
; CHECK-NEXT:    vmv1r.v v21, v28
; CHECK-NEXT:    vmv1r.v v28, v7
; CHECK-NEXT:    vmv2r.v v10, v22
; CHECK-NEXT:    vmv2r.v v14, v24
; CHECK-NEXT:    vmv2r.v v18, v26
; CHECK-NEXT:    vmv2r.v v22, v28
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %retval = call {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} @llvm.vector.deinterleave8.nxv32i32(<vscale x 32 x i32> %vec)
  ret {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} %retval
}

declare {<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>} @llvm.vector.deinterleave8.nxv32i32(<vscale x 32 x i32>)

define {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} @vector_deinterleave_nxv4i64_nxv16i64(<vscale x 16 x i64> %vec) nounwind {
; CHECK-LABEL: vector_deinterleave_nxv4i64_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v8, (a0)
; CHECK-NEXT:    vs8r.v v16, (a1)
; CHECK-NEXT:    vsetvli a2, zero, e64, m1, ta, ma
; CHECK-NEXT:    vlseg8e64.v v0, (a0)
; CHECK-NEXT:    vlseg8e64.v v22, (a1)
; CHECK-NEXT:    vmv2r.v v8, v0
; CHECK-NEXT:    vmv1r.v v9, v22
; CHECK-NEXT:    vmv1r.v v22, v1
; CHECK-NEXT:    vmv2r.v v12, v2
; CHECK-NEXT:    vmv1r.v v13, v24
; CHECK-NEXT:    vmv1r.v v24, v3
; CHECK-NEXT:    vmv2r.v v16, v4
; CHECK-NEXT:    vmv1r.v v17, v26
; CHECK-NEXT:    vmv1r.v v26, v5
; CHECK-NEXT:    vmv2r.v v20, v6
; CHECK-NEXT:    vmv1r.v v21, v28
; CHECK-NEXT:    vmv1r.v v28, v7
; CHECK-NEXT:    vmv2r.v v10, v22
; CHECK-NEXT:    vmv2r.v v14, v24
; CHECK-NEXT:    vmv2r.v v18, v26
; CHECK-NEXT:    vmv2r.v v22, v28
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %retval = call {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} @llvm.vector.deinterleave8.nxv16i64(<vscale x 16 x i64> %vec)
  ret {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} %retval
}

declare {<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>} @llvm.vector.deinterleave8.nxv16i64(<vscale x 16 x i64>)
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32: {{.*}}
; RV64: {{.*}}
