; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=false -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=NOALIGN
; RUN: llc -mtriple=riscv32 -mattr=+v,+dlen128b -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN

define void @UnKnownSize(ptr nocapture readonly %src, ptr nocapture %dst, i32 signext %n) {
; NOALIGN-LABEL: UnKnownSize:
; NOALIGN:       # %bb.0: # %entry
; NOALIGN-NEXT:    sub a3, a1, a0
; NOALIGN-NEXT:    bgeu a3, a2, .LBB0_3
; NOALIGN-NEXT:  # %bb.1: # %memmove-backward-pre-loop
; NOALIGN-NEXT:    add a0, a0, a2
; NOALIGN-NEXT:    add a1, a1, a2
; NOALIGN-NEXT:  .LBB0_2: # %memmove-backward-loop
; NOALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; NOALIGN-NEXT:    vsetvli a3, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    sub a0, a0, a3
; NOALIGN-NEXT:    vle8.v v8, (a0)
; NOALIGN-NEXT:    sub a1, a1, a3
; NOALIGN-NEXT:    sub a2, a2, a3
; NOALIGN-NEXT:    vse8.v v8, (a1)
; NOALIGN-NEXT:    bnez a2, .LBB0_2
; NOALIGN-NEXT:    j .LBB0_4
; NOALIGN-NEXT:  .LBB0_3: # %memmove-forward-loop
; NOALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; NOALIGN-NEXT:    vsetvli a3, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vle8.v v8, (a0)
; NOALIGN-NEXT:    sub a2, a2, a3
; NOALIGN-NEXT:    add a0, a0, a3
; NOALIGN-NEXT:    vse8.v v8, (a1)
; NOALIGN-NEXT:    add a1, a1, a3
; NOALIGN-NEXT:    bnez a2, .LBB0_3
; NOALIGN-NEXT:  .LBB0_4: # %memmove-post-loop
; NOALIGN-NEXT:    ret
;
; ALIGN-LABEL: UnKnownSize:
; ALIGN:       # %bb.0: # %entry
; ALIGN-NEXT:    sub a3, a1, a0
; ALIGN-NEXT:    bgeu a3, a2, .LBB0_5
; ALIGN-NEXT:  # %bb.1: # %memmove-backward-pre-loop
; ALIGN-NEXT:    add a3, a0, a2
; ALIGN-NEXT:    andi a3, a3, 15
; ALIGN-NEXT:    bltu a3, a2, .LBB0_3
; ALIGN-NEXT:  # %bb.2: # %memmove-backward-pre-loop
; ALIGN-NEXT:    mv a3, a2
; ALIGN-NEXT:  .LBB0_3: # %memmove-backward-pre-loop
; ALIGN-NEXT:    vsetvli a3, a3, e8, m8, ta, ma
; ALIGN-NEXT:    sub a2, a2, a3
; ALIGN-NEXT:    add a0, a0, a2
; ALIGN-NEXT:    vle8.v v8, (a0)
; ALIGN-NEXT:    add a1, a1, a2
; ALIGN-NEXT:    vse8.v v8, (a1)
; ALIGN-NEXT:    beqz a2, .LBB0_10
; ALIGN-NEXT:  .LBB0_4: # %memmove-backward-loop
; ALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-NEXT:    vsetvli a3, a2, e8, m8, ta, ma
; ALIGN-NEXT:    sub a0, a0, a3
; ALIGN-NEXT:    vle8.v v8, (a0)
; ALIGN-NEXT:    sub a1, a1, a3
; ALIGN-NEXT:    sub a2, a2, a3
; ALIGN-NEXT:    vse8.v v8, (a1)
; ALIGN-NEXT:    bnez a2, .LBB0_4
; ALIGN-NEXT:    j .LBB0_10
; ALIGN-NEXT:  .LBB0_5: # %memmove-forward-pre-loop
; ALIGN-NEXT:    andi a3, a0, 15
; ALIGN-NEXT:    li a4, 16
; ALIGN-NEXT:    sub a3, a4, a3
; ALIGN-NEXT:    bltu a3, a2, .LBB0_7
; ALIGN-NEXT:  # %bb.6: # %memmove-forward-pre-loop
; ALIGN-NEXT:    mv a3, a2
; ALIGN-NEXT:  .LBB0_7: # %memmove-forward-pre-loop
; ALIGN-NEXT:    vsetvli a3, a3, e8, m8, ta, ma
; ALIGN-NEXT:    vle8.v v8, (a0)
; ALIGN-NEXT:    sub a2, a2, a3
; ALIGN-NEXT:    vse8.v v8, (a1)
; ALIGN-NEXT:    beqz a2, .LBB0_10
; ALIGN-NEXT:  # %bb.8:
; ALIGN-NEXT:    add a0, a0, a3
; ALIGN-NEXT:    add a1, a1, a3
; ALIGN-NEXT:  .LBB0_9: # %memmove-forward-loop
; ALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-NEXT:    vsetvli a3, a2, e8, m8, ta, ma
; ALIGN-NEXT:    vle8.v v8, (a0)
; ALIGN-NEXT:    sub a2, a2, a3
; ALIGN-NEXT:    add a0, a0, a3
; ALIGN-NEXT:    vse8.v v8, (a1)
; ALIGN-NEXT:    add a1, a1, a3
; ALIGN-NEXT:    bnez a2, .LBB0_9
; ALIGN-NEXT:  .LBB0_10: # %memmove-post-loop
; ALIGN-NEXT:    ret
entry:
  tail call void @llvm.memmove.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i32 %n, i1 false)
  ret void
}

declare void @llvm.memmove.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg)
