; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v -verify-machineinstrs | FileCheck %s

define void @shufflevector_0_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 24
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, tu, ma
; CHECK-NEXT:    vmv.v.v v12, v8
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v12, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v12, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_0_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_0_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v12, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 0, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vslideup.vi v9, v8, 1
; CHECK-NEXT:    vse64.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlseg2e64.v v8, (a0)
; CHECK-NEXT:    vse64.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    li a2, 24
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 8
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 1
; CHECK-NEXT:    vslidedown.vi v8, v12, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_1_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_1_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 1
; CHECK-NEXT:    vslidedown.vi v8, v12, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 1, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 16(a0)
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 16(a0)
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 16(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 16(a0)
; CHECK-NEXT:    ld a0, 32(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    li a2, 24
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_2_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_2_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 2
; CHECK-NEXT:    vslidedown.vi v8, v12, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 2, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 24(a0)
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 24(a0)
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vslideup.vi v9, v8, 1
; CHECK-NEXT:    vse64.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 24(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 24
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v12, v8, 3, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v12, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 3
; CHECK-NEXT:    vslidedown.vi v8, v12, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_3_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_3_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 24
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vlse64.v v8, (a0), a2
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 3, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 32(a0)
; CHECK-NEXT:    ld a0, 0(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 32(a0)
; CHECK-NEXT:    ld a0, 8(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 32(a0)
; CHECK-NEXT:    ld a0, 16(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 32(a0)
; CHECK-NEXT:    ld a0, 24(a0)
; CHECK-NEXT:    sd a2, 0(a1)
; CHECK-NEXT:    sd a0, 8(a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 32(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_4_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_4_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 4, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v12, 1
; CHECK-NEXT:    vslideup.vi v9, v8, 1
; CHECK-NEXT:    vse64.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v12, 1, v0.t
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v12, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v12, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vslideup.vi v9, v8, 1
; CHECK-NEXT:    vse64.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 40(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v8, v8, 1
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_5_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_5_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v8, 1
; CHECK-NEXT:    vslidedown.vi v10, v8, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 5, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v12, 2
; CHECK-NEXT:    vslideup.vi v10, v8, 1
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v12, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v12, 2
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v12, 2
; CHECK-NEXT:    vslidedown.vi v10, v8, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v10, v8, 2
; CHECK-NEXT:    vslideup.vi v10, v8, 1
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 48(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_6_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_6_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 6, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_0(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v12, 3
; CHECK-NEXT:    vslideup.vi v10, v8, 1
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 0>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_1(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v12, 3, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 1>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_2(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v12, 3
; CHECK-NEXT:    vslidedown.vi v10, v8, 1, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 2>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_3(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 2
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 4
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v10, v12, 3
; CHECK-NEXT:    vslidedown.vi v10, v8, 2, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 3>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_4(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v10, v8, 3
; CHECK-NEXT:    vslideup.vi v10, v8, 1
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 4>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_5(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.i v0, 1
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, mu
; CHECK-NEXT:    vslidedown.vi v8, v8, 3, v0.t
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 5>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_6(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a0, a0, 48
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vslideup.vi v9, v8, 1
; CHECK-NEXT:    vse64.v v9, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 6>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}

define void @shufflevector_7_7(ptr %in, ptr %out) {
; CHECK-LABEL: shufflevector_7_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a0, 56(a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  %0 = load <8 x i64>, ptr %in, align 8
  %1 = shufflevector <8 x i64> %0, <8 x i64> undef, <2 x i32> <i32 7, i32 7>
  store <2 x i64> %1, ptr %out, align 8
  ret void
}
