; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+d,+zfh,+zvfh,+v -target-abi=ilp32d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+d,+zfh,+zvfh,+v -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV64

declare i32 @llvm.vp.first.nxv1i1(<vscale x 1 x i1>, <vscale x 1 x i1>, i32)
define i32 @vp_first_nxv1i1(<vscale x 1 x i1> %m, <vscale x 1 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv1i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv1i1(<vscale x 1 x i1> %op, <vscale x 1 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv1i1_unmasked(<vscale x 1 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv1i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 1 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 1 x i1> %head, <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv1i1(<vscale x 1 x i1> %op, <vscale x 1 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv2i1(<vscale x 2 x i1>, <vscale x 2 x i1>, i32)
define i32 @vp_first_nxv2i1(<vscale x 2 x i1> %m, <vscale x 2 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv2i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv2i1(<vscale x 2 x i1> %op, <vscale x 2 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv2i1_unmasked(<vscale x 2 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv2i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 2 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 2 x i1> %head, <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv2i1(<vscale x 2 x i1> %op, <vscale x 2 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv4i1(<vscale x 4 x i1>, <vscale x 4 x i1>, i32)
define i32 @vp_first_nxv4i1(<vscale x 4 x i1> %m, <vscale x 4 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv4i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv4i1(<vscale x 4 x i1> %op, <vscale x 4 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv4i1_unmasked(<vscale x 4 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv4i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 4 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 4 x i1> %head, <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv4i1(<vscale x 4 x i1> %op, <vscale x 4 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1>, <vscale x 8 x i1>, i32)
define i32 @vp_first_nxv8i1(<vscale x 8 x i1> %m, <vscale x 8 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv8i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> %op, <vscale x 8 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv8i1_unmasked(<vscale x 8 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv8i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 8 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 8 x i1> %head, <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv8i1(<vscale x 8 x i1> %op, <vscale x 8 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1>, <vscale x 16 x i1>, i32)
define i32 @vp_first_nxv16i1(<vscale x 16 x i1> %m, <vscale x 16 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv16i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> %op, <vscale x 16 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv16i1_unmasked(<vscale x 16 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv16i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 16 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 16 x i1> %head, <vscale x 16 x i1> poison, <vscale x 16 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv16i1(<vscale x 16 x i1> %op, <vscale x 16 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1>, <vscale x 32 x i1>, i32)
define i32 @vp_first_nxv32i1(<vscale x 32 x i1> %m, <vscale x 32 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv32i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> %op, <vscale x 32 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv32i1_unmasked(<vscale x 32 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv32i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 32 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 32 x i1> %head, <vscale x 32 x i1> poison, <vscale x 32 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv32i1(<vscale x 32 x i1> %op, <vscale x 32 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv63i1(<vscale x 63 x i1>, <vscale x 63 x i1>, i32)
define i32 @vp_first_nxv63i1(<vscale x 63 x i1> %m, <vscale x 63 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv63i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv63i1(<vscale x 63 x i1> %op, <vscale x 63 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv63i1_unmasked(<vscale x 63 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv63i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 63 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 63 x i1> %head, <vscale x 63 x i1> poison, <vscale x 63 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv63i1(<vscale x 63 x i1> %op, <vscale x 63 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv64i1(<vscale x 64 x i1>, <vscale x 64 x i1>, i32)
define i32 @vp_first_nxv64i1(<vscale x 64 x i1> %m, <vscale x 64 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv64i1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv64i1(<vscale x 64 x i1> %op, <vscale x 64 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv64i1_unmasked(<vscale x 64 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv64i1_unmasked:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v0
; CHECK-NEXT:    ret
entry:
  %head = insertelement <vscale x 64 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 64 x i1> %head, <vscale x 64 x i1> poison, <vscale x 64 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv64i1(<vscale x 64 x i1> %op, <vscale x 64 x i1> %m, i32 %evl)
  ret i32 %a
}

declare i32 @llvm.vp.first.nxv128i1(<vscale x 128 x i1>, <vscale x 128 x i1>, i32)
define i32 @vp_first_nxv128i1(<vscale x 128 x i1> %m, <vscale x 128 x i1> %op, i32 zeroext %evl) {
; RV32-LABEL: vp_first_nxv128i1:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    slli a3, a3, 3
; RV32-NEXT:    mv a2, a0
; RV32-NEXT:    bltu a0, a3, .LBB16_2
; RV32-NEXT:  # %bb.1: # %entry
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB16_2: # %entry
; RV32-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; RV32-NEXT:    vfirst.m a1, v9, v0.t
; RV32-NEXT:    bgez a1, .LBB16_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    sub a1, a0, a3
; RV32-NEXT:    sltu a0, a0, a1
; RV32-NEXT:    addi a0, a0, -1
; RV32-NEXT:    and a0, a0, a1
; RV32-NEXT:    vmv1r.v v0, v8
; RV32-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; RV32-NEXT:    vfirst.m a0, v10, v0.t
; RV32-NEXT:    add a2, a2, a0
; RV32-NEXT:    srai a0, a0, 31
; RV32-NEXT:    or a1, a0, a2
; RV32-NEXT:  .LBB16_4: # %entry
; RV32-NEXT:    mv a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_first_nxv128i1:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    slli a3, a3, 3
; RV64-NEXT:    mv a2, a0
; RV64-NEXT:    bltu a0, a3, .LBB16_2
; RV64-NEXT:  # %bb.1: # %entry
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB16_2: # %entry
; RV64-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; RV64-NEXT:    vfirst.m a1, v9, v0.t
; RV64-NEXT:    bgez a1, .LBB16_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    sub a1, a0, a3
; RV64-NEXT:    sltu a0, a0, a1
; RV64-NEXT:    addi a0, a0, -1
; RV64-NEXT:    and a0, a0, a1
; RV64-NEXT:    vmv1r.v v0, v8
; RV64-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; RV64-NEXT:    vfirst.m a0, v10, v0.t
; RV64-NEXT:    add a2, a2, a0
; RV64-NEXT:    srai a0, a0, 63
; RV64-NEXT:    or a1, a0, a2
; RV64-NEXT:  .LBB16_4: # %entry
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv128i1(<vscale x 128 x i1> %op, <vscale x 128 x i1> %m, i32 %evl)
  ret i32 %a
}

define i32 @vp_first_nxv128i1_unmasked(<vscale x 128 x i1> %op, i32 zeroext %evl) {
; RV32-LABEL: vp_first_nxv128i1_unmasked:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    slli a3, a3, 3
; RV32-NEXT:    mv a2, a0
; RV32-NEXT:    bltu a0, a3, .LBB17_2
; RV32-NEXT:  # %bb.1: # %entry
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB17_2: # %entry
; RV32-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; RV32-NEXT:    vfirst.m a1, v0
; RV32-NEXT:    bgez a1, .LBB17_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    sub a1, a0, a3
; RV32-NEXT:    sltu a0, a0, a1
; RV32-NEXT:    addi a0, a0, -1
; RV32-NEXT:    and a0, a0, a1
; RV32-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; RV32-NEXT:    vfirst.m a0, v8
; RV32-NEXT:    add a2, a2, a0
; RV32-NEXT:    srai a0, a0, 31
; RV32-NEXT:    or a1, a0, a2
; RV32-NEXT:  .LBB17_4: # %entry
; RV32-NEXT:    mv a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_first_nxv128i1_unmasked:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    slli a3, a3, 3
; RV64-NEXT:    mv a2, a0
; RV64-NEXT:    bltu a0, a3, .LBB17_2
; RV64-NEXT:  # %bb.1: # %entry
; RV64-NEXT:    mv a2, a3
; RV64-NEXT:  .LBB17_2: # %entry
; RV64-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; RV64-NEXT:    vfirst.m a1, v0
; RV64-NEXT:    bgez a1, .LBB17_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    sub a1, a0, a3
; RV64-NEXT:    sltu a0, a0, a1
; RV64-NEXT:    addi a0, a0, -1
; RV64-NEXT:    and a0, a0, a1
; RV64-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; RV64-NEXT:    vfirst.m a0, v8
; RV64-NEXT:    add a2, a2, a0
; RV64-NEXT:    srai a0, a0, 63
; RV64-NEXT:    or a1, a0, a2
; RV64-NEXT:  .LBB17_4: # %entry
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:    ret
entry:
  %head = insertelement <vscale x 128 x i1> poison, i1 true, i32 0
  %m = shufflevector <vscale x 128 x i1> %head, <vscale x 128 x i1> poison, <vscale x 128 x i32> zeroinitializer
  %a = call i32 @llvm.vp.first.nxv128i1(<vscale x 128 x i1> %op, <vscale x 128 x i1> %m, i32 %evl)
  ret i32 %a
}

define signext i32 @vp_first_nxv64i1_signext(<vscale x 64 x i1> %m, <vscale x 64 x i1> %op, i32 zeroext %evl) {
; CHECK-LABEL: vp_first_nxv64i1_signext:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; CHECK-NEXT:    vfirst.m a0, v8, v0.t
; CHECK-NEXT:    ret
entry:
  %a = call i32 @llvm.vp.first.nxv64i1(<vscale x 64 x i1> %op, <vscale x 64 x i1> %m, i32 %evl)
  ret i32 %a
}
