; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+f | FileCheck %s

define <vscale x 2 x double> @test_combine_vp_merges(<vscale x 2 x i64> %arg, <vscale x 2 x double> %arg1, <vscale x 2 x double> %arg2, i32 zeroext %arg3) {
; CHECK-LABEL: test_combine_vp_merges:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vmseq.vi v0, v8, 0
; CHECK-NEXT:    vsetvli zero, zero, e64, m2, tu, ma
; CHECK-NEXT:    vmerge.vvm v12, v12, v10, v0
; CHECK-NEXT:    vmv2r.v v8, v12
; CHECK-NEXT:    ret
bb:
  %tmp = tail call <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64> %arg, <vscale x 2 x i64> zeroinitializer, metadata !"eq", <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 %arg3)
  %tmp4 = tail call <vscale x 2 x double> @llvm.vp.merge.nxv2f64(<vscale x 2 x i1> %tmp, <vscale x 2 x double> %arg1, <vscale x 2 x double> %arg2, i32 %arg3)
  %tmp5 = tail call <vscale x 2 x double> @llvm.vp.merge.nxv2f64(<vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x double> %tmp4, <vscale x 2 x double> %arg2, i32 %arg3)
  ret <vscale x 2 x double> %tmp5
}

define <vscale x 8 x i1> @test_vpmerge_i1_alltruemask(<vscale x 8 x i1> %arg1, i32 zeroext %arg2) {
; CHECK-LABEL: test_vpmerge_i1_alltruemask:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vsetvli a1, zero, e64, m8, ta, ma
; CHECK-NEXT:    vid.v v8
; CHECK-NEXT:    vmsltu.vx v8, v8, a0
; CHECK-NEXT:    vmand.mm v0, v8, v0
; CHECK-NEXT:    ret
bb:
  %0 = tail call <vscale x 8 x i1> @llvm.vp.merge.nxv8i1(<vscale x 8 x i1> shufflevector (<vscale x 8 x i1> insertelement (<vscale x 8 x i1> poison, i1 true, i64 0), <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer), <vscale x 8 x i1> %arg1, <vscale x 8 x i1> zeroinitializer, i32 %arg2)
  ret <vscale x 8 x i1> %0
}

declare <vscale x 2 x i1> @llvm.vp.icmp.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>, metadata, <vscale x 2 x i1>, i32)

declare <vscale x 2 x double> @llvm.vp.merge.nxv2f64(<vscale x 2 x i1>, <vscale x 2 x double>, <vscale x 2 x double>, i32)

declare <vscale x 8 x i1> @llvm.vp.merge.nxv8i1(<vscale x 8 x i1>, <vscale x 8 x i1>, <vscale x 8 x i1>, i32)
