; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+v -verify-machineinstrs < %s | FileCheck %s

define <vscale x 4 x i1> @test_vp_xor_icmp_combine(<vscale x 4 x i64> %x, <vscale x 4 x i64> %y, <vscale x 4 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: test_vp_xor_icmp_combine:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmslt.vv v0, v8, v12, v0.t
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 4 x i1> poison, i1 1, i32 0
  %allones = shufflevector <vscale x 4 x i1> %head, <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer
  %icmp = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> %y, metadata !"sge", <vscale x 4 x i1> %mask, i32 %evl)
  %result = call <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1> %icmp, <vscale x 4 x i1> %allones, <vscale x 4 x i1> %mask, i32 %evl)
  ret <vscale x 4 x i1> %result
}

define <vscale x 4 x i1> @test_vp_xor_icmp_combine_not_allones(<vscale x 4 x i64> %x, <vscale x 4 x i64> %y, <vscale x 4 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: test_vp_xor_icmp_combine_not_allones:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmv1r.v v16, v0
; CHECK-NEXT:    vmv.v.i v17, 0
; CHECK-NEXT:    vsetivli zero, 3, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v18, 1
; CHECK-NEXT:    vmv1r.v v19, v17
; CHECK-NEXT:    vsetivli zero, 2, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v19, v18, 1
; CHECK-NEXT:    vsetvli a1, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vand.vi v19, v19, 1
; CHECK-NEXT:    vmsne.vi v0, v19, 0
; CHECK-NEXT:    vmerge.vim v17, v17, 1, v0
; CHECK-NEXT:    vsetivli zero, 3, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v17, v18, 2
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vand.vi v17, v17, 1
; CHECK-NEXT:    vmsne.vi v17, v17, 0
; CHECK-NEXT:    vmv1r.v v0, v16
; CHECK-NEXT:    vsetvli zero, zero, e64, m4, ta, ma
; CHECK-NEXT:    vmsle.vv v8, v12, v8, v0.t
; CHECK-NEXT:    vmxor.mm v0, v8, v17
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 4 x i1> zeroinitializer, i1 1, i32 1
  %notallones = insertelement <vscale x 4 x i1> %head, i1 1, i32 2
  %icmp = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> %y, metadata !"sge", <vscale x 4 x i1> %mask, i32 %evl)
  %result = call <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1> %icmp, <vscale x 4 x i1> %notallones, <vscale x 4 x i1> %mask, i32 %evl)
  ret <vscale x 4 x i1> %result
}

define <vscale x 4 x i1> @test_vp_xor_icmp_combine_different_mask(<vscale x 4 x i64> %x, <vscale x 4 x i64> %y, <vscale x 4 x i1> %mask1, <vscale x 4 x i1> %mask2, i32 zeroext %evl) {
; CHECK-LABEL: test_vp_xor_icmp_combine_different_mask:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmsle.vv v8, v12, v8, v0.t
; CHECK-NEXT:    vmnot.m v0, v8
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 4 x i1> poison, i1 1, i32 0
  %allones = shufflevector <vscale x 4 x i1> %head, <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer
  %icmp = call <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64> %x, <vscale x 4 x i64> %y, metadata !"sge", <vscale x 4 x i1> %mask1, i32 %evl)
  %result = call <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1> %icmp, <vscale x 4 x i1> %allones, <vscale x 4 x i1> %mask2, i32 %evl)
  ret <vscale x 4 x i1> %result
}

define <vscale x 4 x i1> @test_vp_xor_fcmp_combine(<vscale x 4 x double> %x, <vscale x 4 x double> %y, <vscale x 4 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: test_vp_xor_fcmp_combine:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmflt.vv v0, v8, v12, v0.t
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 4 x i1> poison, i1 1, i32 0
  %allones = shufflevector <vscale x 4 x i1> %head, <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer
  %fcmp = call <vscale x 4 x i1> @llvm.vp.fcmp.nxv4f64(<vscale x 4 x double> %x, <vscale x 4 x double> %y, metadata !"uge", <vscale x 4 x i1> %mask, i32 %evl)
  %result = call <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1> %fcmp, <vscale x 4 x i1> %allones, <vscale x 4 x i1> %mask, i32 %evl)
  ret <vscale x 4 x i1> %result
}

define <vscale x 4 x i1> @test_vp_xor_fcmp_combine_not_allones(<vscale x 4 x double> %x, <vscale x 4 x double> %y, <vscale x 4 x i1> %mask, i32 zeroext %evl) {
; CHECK-LABEL: test_vp_xor_fcmp_combine_not_allones:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmv1r.v v16, v0
; CHECK-NEXT:    vmv.v.i v17, 0
; CHECK-NEXT:    vsetivli zero, 3, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.i v18, 1
; CHECK-NEXT:    vmv1r.v v19, v17
; CHECK-NEXT:    vsetivli zero, 2, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v19, v18, 1
; CHECK-NEXT:    vsetvli a1, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vand.vi v19, v19, 1
; CHECK-NEXT:    vmsne.vi v0, v19, 0
; CHECK-NEXT:    vmerge.vim v17, v17, 1, v0
; CHECK-NEXT:    vsetivli zero, 3, e8, mf2, tu, ma
; CHECK-NEXT:    vslideup.vi v17, v18, 2
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, ma
; CHECK-NEXT:    vand.vi v17, v17, 1
; CHECK-NEXT:    vmsne.vi v17, v17, 0
; CHECK-NEXT:    vmv1r.v v0, v16
; CHECK-NEXT:    vsetvli zero, zero, e64, m4, ta, ma
; CHECK-NEXT:    vmflt.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vmxnor.mm v0, v8, v17
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 4 x i1> zeroinitializer, i1 1, i32 1
  %notallones = insertelement <vscale x 4 x i1> %head, i1 1, i32 2
  %fcmp = call <vscale x 4 x i1> @llvm.vp.fcmp.nxv4f64(<vscale x 4 x double> %x, <vscale x 4 x double> %y, metadata !"uge", <vscale x 4 x i1> %mask, i32 %evl)
  %result = call <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1> %fcmp, <vscale x 4 x i1> %notallones, <vscale x 4 x i1> %mask, i32 %evl)
  ret <vscale x 4 x i1> %result
}

define <vscale x 4 x i1> @test_vp_xor_fcmp_combine_different_mask(<vscale x 4 x double> %x, <vscale x 4 x double> %y, <vscale x 4 x i1> %mask1, <vscale x 4 x i1> %mask2, i32 zeroext %evl) {
; CHECK-LABEL: test_vp_xor_fcmp_combine_different_mask:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmset.m v16
; CHECK-NEXT:    vmflt.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vmxnor.mm v0, v8, v16
; CHECK-NEXT:    ret
  %head = insertelement <vscale x 4 x i1> poison, i1 1, i32 0
  %allones = shufflevector <vscale x 4 x i1> %head, <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer
  %fcmp = call <vscale x 4 x i1> @llvm.vp.fcmp.nxv4f64(<vscale x 4 x double> %x, <vscale x 4 x double> %y, metadata !"uge", <vscale x 4 x i1> %mask1, i32 %evl)
  %result = call <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1> %fcmp, <vscale x 4 x i1> %allones, <vscale x 4 x i1> %mask2, i32 %evl)
  ret <vscale x 4 x i1> %result
}

declare <vscale x 4 x i1> @llvm.vp.icmp.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, metadata, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i1> @llvm.vp.fcmp.nxv4f64(<vscale x 4 x double>, <vscale x 4 x double>, metadata, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i1> @llvm.vp.xor.nxv4i1(<vscale x 4 x i1>, <vscale x 4 x i1>, <vscale x 4 x i1>, i32)
