; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=512 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -riscv-mem-to-rvv-dlen-align=false -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-512
; RUN: llc -mtriple=riscv32 -mattr=+v -riscv-v-vector-bits-min=256 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -riscv-mem-to-rvv-dlen-align=false -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-256

define void @KnownSize(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    add a1, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    li a0, 504
; MIN-512-NEXT:    add a3, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    add a2, a3, a2
; MIN-512-NEXT:    vse8.v v8, (a3)
; MIN-512-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-512-NEXT:    vse8.v v8, (a2)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a1, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a0, 248
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a1, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a1, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a2, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i32(ptr align 1 %dst, i8 %val, i32 2040, i1 false)
  ret void
}

define void @KnownSize1(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize1:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 384
; MIN-512-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize1:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a2, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a0, 128
; MIN-256-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i32(ptr align 1 %dst, i8 %val, i32 384, i1 false)
  ret void
}

define void @KnownSize2(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize2:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    add a2, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a2)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize2:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a1, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    add a0, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a2, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i32(ptr align 1 %dst, i8 %val, i32 1024, i1 false)
  ret void
}


declare void @llvm.memset.p0.i8.i32(ptr noalias nocapture writeonly, i8 noalias readonly, i32, i1 immarg)

; Test size given as i64 instead of XLen
define void @KnownSize3(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize3:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    add a1, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    li a0, 504
; MIN-512-NEXT:    add a3, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    add a2, a3, a2
; MIN-512-NEXT:    vse8.v v8, (a3)
; MIN-512-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-512-NEXT:    vse8.v v8, (a2)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize3:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a1, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a0, 248
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a1, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a1, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    add a3, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a2, a3, a2
; MIN-256-NEXT:    vse8.v v8, (a3)
; MIN-256-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 2040, i1 false)
  ret void
}

define void @KnownSize4(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize4:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 384
; MIN-512-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize4:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a2, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    li a0, 128
; MIN-256-NEXT:    vsetvli zero, a0, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 384, i1 false)
  ret void
}

; Test size given as i64 instead of XLen
define void @KnownSize5(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize5:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:    add a2, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a2)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize5:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:    add a1, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    add a0, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a2, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    vse8.v v8, (a2)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 1024, i1 false)
  ret void
}

; Test size given as i64 instead of XLen. Size is larger than our unrolling
; treshold.
define void @KnownSize6(ptr nocapture %dst, i8 %val) {
; MIN-512-LABEL: KnownSize6:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    lui a2, 2
; MIN-512-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vmv.v.x v8, a1
; MIN-512-NEXT:  .LBB6_1: # %memset-forward-loop
; MIN-512-NEXT:    # =>This Inner Loop Header: Depth=1
; MIN-512-NEXT:    vsetvli a1, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vse8.v v8, (a0)
; MIN-512-NEXT:    sub a2, a2, a1
; MIN-512-NEXT:    add a0, a0, a1
; MIN-512-NEXT:    bnez a2, .LBB6_1
; MIN-512-NEXT:  # %bb.2: # %memset-post-loop
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize6:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    lui a2, 2
; MIN-256-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vmv.v.x v8, a1
; MIN-256-NEXT:  .LBB6_1: # %memset-forward-loop
; MIN-256-NEXT:    # =>This Inner Loop Header: Depth=1
; MIN-256-NEXT:    vsetvli a1, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vse8.v v8, (a0)
; MIN-256-NEXT:    sub a2, a2, a1
; MIN-256-NEXT:    add a0, a0, a1
; MIN-256-NEXT:    bnez a2, .LBB6_1
; MIN-256-NEXT:  # %bb.2: # %memset-post-loop
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 8192, i1 false)
  ret void
}
