; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=512 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-512
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=256 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=MIN-256

define void @KnownSize1(ptr nocapture readonly %src, ptr nocapture %dst) {
; MIN-512-LABEL: KnownSize1:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    li a3, 313
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize1:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    li a3, 57
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i64 1337, i1 false)
  ret void
}

define void @KnownSize2(ptr nocapture readonly %src, ptr nocapture %dst) {
; MIN-512-LABEL: KnownSize2:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 512
; MIN-512-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    add a0, a0, a2
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    add a1, a1, a2
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize2:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 256
; MIN-256-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    add a0, a0, a2
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    add a1, a1, a2
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i64 1024, i1 false)
  ret void
}

define void @KnownSize3(ptr nocapture readonly %src, ptr nocapture %dst) {
; MIN-512-LABEL: KnownSize3:
; MIN-512:       # %bb.0: # %entry
; MIN-512-NEXT:    li a2, 237
; MIN-512-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-512-NEXT:    vle8.v v8, (a0)
; MIN-512-NEXT:    vse8.v v8, (a1)
; MIN-512-NEXT:    ret
;
; MIN-256-LABEL: KnownSize3:
; MIN-256:       # %bb.0: # %entry
; MIN-256-NEXT:    li a2, 237
; MIN-256-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; MIN-256-NEXT:    vle8.v v8, (a0)
; MIN-256-NEXT:    vse8.v v8, (a1)
; MIN-256-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i64 237, i1 false)
  ret void
}

declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)
