; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -target-abi=ilp32d -mattr=+m,+v,+zfh,+zvfh,+f,+d | FileCheck %s -check-prefix=RV32
; RUN: llc < %s -mtriple=riscv64 -target-abi=lp64d -mattr=+m,+v,+zfh,+zvfh,+f,+d | FileCheck %s -check-prefix=RV64

declare <vscale x 2 x half> @llvm.vp.sqrt.nxv2f16(<vscale x 2 x half>, <vscale x 2 x i1>, i32)
declare <vscale x 4 x half> @llvm.vp.sqrt.nxv4f16(<vscale x 4 x half>, <vscale x 4 x i1>, i32)
declare <vscale x 8 x half> @llvm.vp.sqrt.nxv8f16(<vscale x 8 x half>, <vscale x 8 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.sqrt.nxv2f32(<vscale x 2 x float>, <vscale x 2 x i1>, i32)
declare <vscale x 4 x float> @llvm.vp.sqrt.nxv4f32(<vscale x 4 x float>, <vscale x 4 x i1>, i32)
declare <vscale x 8 x float> @llvm.vp.sqrt.nxv8f32(<vscale x 8 x float>, <vscale x 8 x i1>, i32)
declare <vscale x 2 x double> @llvm.vp.sqrt.nxv2f64(<vscale x 2 x double>, <vscale x 2 x i1>, i32)
declare <vscale x 4 x double> @llvm.vp.sqrt.nxv4f64(<vscale x 4 x double>, <vscale x 4 x i1>, i32)
declare <vscale x 8 x double> @llvm.vp.sqrt.nxv8f64(<vscale x 8 x double>, <vscale x 8 x i1>, i32)

declare <vscale x 2 x half> @llvm.vp.fdiv.nxv2f16(<vscale x 2 x half>, <vscale x 2 x half>, <vscale x 2 x i1>, i32)
declare <vscale x 4 x half> @llvm.vp.fdiv.nxv4f16(<vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x i1>, i32)
declare <vscale x 8 x half> @llvm.vp.fdiv.nxv8f16(<vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x i1>, i32)
declare <vscale x 2 x float> @llvm.vp.fdiv.nxv2f32(<vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x i1>, i32)
declare <vscale x 4 x float> @llvm.vp.fdiv.nxv4f32(<vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x i1>, i32)
declare <vscale x 8 x float> @llvm.vp.fdiv.nxv8f32(<vscale x 8 x float>, <vscale x 8 x float>, <vscale x 8 x i1>, i32)
declare <vscale x 2 x double> @llvm.vp.fdiv.nxv2f64(<vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x i1>, i32)
declare <vscale x 4 x double> @llvm.vp.fdiv.nxv4f64(<vscale x 4 x double>, <vscale x 4 x double>, <vscale x 4 x i1>, i32)
declare <vscale x 8 x double> @llvm.vp.fdiv.nxv8f64(<vscale x 8 x double>, <vscale x 8 x double>, <vscale x 8 x i1>, i32)

define <vscale x 2 x half> @sqrt_nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a1, 1024
; CHECK-NEXT:    fmv.h.x fa5, a1
; CHECK-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI0_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI0_0)
; CHECK-NEXT:    vsetvli a2, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vlse16.v v11, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI0_1)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    vfabs.v v9, v8, v0.t
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    lui a0, %hi(.LCPI0_0)
; RV32-NEXT:    flh fa4, %lo(.LCPI0_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI0_1)
; RV32-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; RV32-NEXT:    flh fa5, %lo(.LCPI0_1)(a0)
; RV32-NEXT:    vfmv.v.f v11, fa4
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; RV32-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vmv1r.v v0, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    vfabs.v v9, v8, v0.t
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    lui a0, %hi(.LCPI0_0)
; RV64-NEXT:    flh fa4, %lo(.LCPI0_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI0_1)
; RV64-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; RV64-NEXT:    flh fa5, %lo(.LCPI0_1)(a0)
; RV64-NEXT:    vfmv.v.f v11, fa4
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; RV64-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vmv1r.v v0, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x half> @llvm.vp.sqrt.nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @sqrt_nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a1, 1024
; CHECK-NEXT:    fmv.h.x fa5, a1
; CHECK-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI1_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI1_0)
; CHECK-NEXT:    vsetvli a2, zero, e16, m1, ta, ma
; CHECK-NEXT:    vlse16.v v11, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI1_1)
; CHECK-NEXT:    flh fa5, %lo(.LCPI1_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    vfabs.v v9, v8, v0.t
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    lui a0, %hi(.LCPI1_0)
; RV32-NEXT:    flh fa4, %lo(.LCPI1_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI1_1)
; RV32-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; RV32-NEXT:    flh fa5, %lo(.LCPI1_1)(a0)
; RV32-NEXT:    vfmv.v.f v11, fa4
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; RV32-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v0, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    vfabs.v v9, v8, v0.t
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    lui a0, %hi(.LCPI1_0)
; RV64-NEXT:    flh fa4, %lo(.LCPI1_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI1_1)
; RV64-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; RV64-NEXT:    flh fa5, %lo(.LCPI1_1)(a0)
; RV64-NEXT:    vfmv.v.f v11, fa4
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; RV64-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v0, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x half> @llvm.vp.sqrt.nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @sqrt_nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    li a1, 1024
; CHECK-NEXT:    fmv.h.x fa5, a1
; CHECK-NEXT:    vmflt.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI2_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI2_0)
; CHECK-NEXT:    vsetvli a2, zero, e16, m2, ta, ma
; CHECK-NEXT:    vlse16.v v14, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI2_1)
; CHECK-NEXT:    flh fa5, %lo(.LCPI2_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfmadd.vv v12, v8, v14, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    vfabs.v v10, v8, v0.t
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    lui a0, %hi(.LCPI2_0)
; RV32-NEXT:    flh fa4, %lo(.LCPI2_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI2_1)
; RV32-NEXT:    vmflt.vf v10, v10, fa5, v0.t
; RV32-NEXT:    flh fa5, %lo(.LCPI2_1)(a0)
; RV32-NEXT:    vfmv.v.f v14, fa4
; RV32-NEXT:    vfmul.vv v8, v8, v12, v0.t
; RV32-NEXT:    vfmadd.vv v12, v8, v14, v0.t
; RV32-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v12, v0.t
; RV32-NEXT:    vmv1r.v v0, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    vfabs.v v10, v8, v0.t
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    lui a0, %hi(.LCPI2_0)
; RV64-NEXT:    flh fa4, %lo(.LCPI2_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI2_1)
; RV64-NEXT:    vmflt.vf v10, v10, fa5, v0.t
; RV64-NEXT:    flh fa5, %lo(.LCPI2_1)(a0)
; RV64-NEXT:    vfmv.v.f v14, fa4
; RV64-NEXT:    vfmul.vv v8, v8, v12, v0.t
; RV64-NEXT:    vfmadd.vv v12, v8, v14, v0.t
; RV64-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v12, v0.t
; RV64-NEXT:    vmv1r.v v0, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x half> @llvm.vp.sqrt.nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x float> @sqrt_nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    lui a1, 2048
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vmflt.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v11, v8, v10, v0.t
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetvli a2, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v12, a1
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v13, v10
; CHECK-NEXT:    vfmadd.vv v13, v11, v12, v0.t
; CHECK-NEXT:    lui a0, 782336
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v13, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v8, v12, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v10, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    vfmul.vv v11, v8, v9, v0.t
; RV32-NEXT:    vmv.v.v v12, v9
; RV32-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; RV32-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; RV32-NEXT:    vfmul.vv v9, v9, v12, v0.t
; RV32-NEXT:    vfmul.vv v11, v8, v9, v0.t
; RV32-NEXT:    vfmadd.vv v9, v11, v10, v0.t
; RV32-NEXT:    vfmul.vf v10, v11, fa5, v0.t
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v9, v10, v9, v0.t
; RV32-NEXT:    vfabs.v v8, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV32-NEXT:    vmerge.vim v8, v9, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v10, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    vfmul.vv v11, v8, v9, v0.t
; RV64-NEXT:    vmv.v.v v12, v9
; RV64-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; RV64-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; RV64-NEXT:    vfmul.vv v9, v9, v12, v0.t
; RV64-NEXT:    vfmul.vv v11, v8, v9, v0.t
; RV64-NEXT:    vfmadd.vv v9, v11, v10, v0.t
; RV64-NEXT:    vfmul.vf v10, v11, fa5, v0.t
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v9, v10, v9, v0.t
; RV64-NEXT:    vfabs.v v8, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV64-NEXT:    vmerge.vim v8, v9, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x float> @llvm.vp.sqrt.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x float> %1
}

define <vscale x 4 x float> @sqrt_nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    lui a1, 2048
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vmflt.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    vfmul.vv v14, v8, v12, v0.t
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetvli a2, zero, e32, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v16, a1
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vmv2r.v v18, v12
; CHECK-NEXT:    vfmadd.vv v18, v14, v16, v0.t
; CHECK-NEXT:    lui a0, 782336
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v12, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v18, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vfmadd.vv v12, v8, v16, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v10, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    vfmul.vv v14, v8, v12, v0.t
; RV32-NEXT:    vmv.v.v v16, v12
; RV32-NEXT:    vfmadd.vv v16, v14, v10, v0.t
; RV32-NEXT:    vfmul.vf v12, v12, fa5, v0.t
; RV32-NEXT:    vfmul.vv v12, v12, v16, v0.t
; RV32-NEXT:    vfmul.vv v14, v8, v12, v0.t
; RV32-NEXT:    vfmadd.vv v12, v14, v10, v0.t
; RV32-NEXT:    vfmul.vf v10, v14, fa5, v0.t
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v10, v10, v12, v0.t
; RV32-NEXT:    vfabs.v v8, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV32-NEXT:    vmerge.vim v8, v10, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v10, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    vfmul.vv v14, v8, v12, v0.t
; RV64-NEXT:    vmv.v.v v16, v12
; RV64-NEXT:    vfmadd.vv v16, v14, v10, v0.t
; RV64-NEXT:    vfmul.vf v12, v12, fa5, v0.t
; RV64-NEXT:    vfmul.vv v12, v12, v16, v0.t
; RV64-NEXT:    vfmul.vv v14, v8, v12, v0.t
; RV64-NEXT:    vfmadd.vv v12, v14, v10, v0.t
; RV64-NEXT:    vfmul.vf v10, v14, fa5, v0.t
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v10, v10, v12, v0.t
; RV64-NEXT:    vfabs.v v8, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV64-NEXT:    vmerge.vim v8, v10, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x float> @llvm.vp.sqrt.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x float> %1
}

define <vscale x 8 x float> @sqrt_nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vfabs.v v12, v8, v0.t
; CHECK-NEXT:    lui a1, 2048
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    vmflt.vf v12, v12, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v16, v8
; CHECK-NEXT:    vfmul.vv v20, v8, v16, v0.t
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetvli a2, zero, e32, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v24, a1
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vmv4r.v v28, v16
; CHECK-NEXT:    vfmadd.vv v28, v20, v24, v0.t
; CHECK-NEXT:    lui a0, 782336
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v16, v16, v28, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v16, v0.t
; CHECK-NEXT:    vfmadd.vv v16, v8, v24, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v16, v0.t
; CHECK-NEXT:    vmv1r.v v0, v12
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v12, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV32-NEXT:    vmv.v.v v24, v16
; RV32-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV32-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; RV32-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV32-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV32-NEXT:    vfmadd.vv v16, v20, v12, v0.t
; RV32-NEXT:    vfmul.vf v12, v20, fa5, v0.t
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v12, v12, v16, v0.t
; RV32-NEXT:    vfabs.v v8, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV32-NEXT:    vmerge.vim v8, v12, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v12, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV64-NEXT:    vmv.v.v v24, v16
; RV64-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV64-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; RV64-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV64-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV64-NEXT:    vfmadd.vv v16, v20, v12, v0.t
; RV64-NEXT:    vfmul.vf v12, v20, fa5, v0.t
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v12, v12, v16, v0.t
; RV64-NEXT:    vfabs.v v8, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV64-NEXT:    vmerge.vim v8, v12, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x float> @llvm.vp.sqrt.nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x float> %1
}

define <vscale x 2 x double> @sqrt_nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v12, v8, v10, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI6_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI6_0)
; CHECK-NEXT:    vsetvli a2, zero, e64, m2, ta, ma
; CHECK-NEXT:    vlse64.v v14, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI6_1)
; CHECK-NEXT:    fld fa5, %lo(.LCPI6_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vmv2r.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v12, v14, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v12, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v12, v14, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v12, v8, v10, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v12, v14, v0.t
; CHECK-NEXT:    lui a0, %hi(.LCPI6_2)
; CHECK-NEXT:    fld fa4, %lo(.LCPI6_2)(a0)
; CHECK-NEXT:    vfmul.vf v12, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v12, v10, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa4, v0.t
; CHECK-NEXT:    vmerge.vim v8, v10, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI6_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI6_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI6_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI6_1)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI6_2)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    fld fa5, %lo(.LCPI6_2)(a0)
; RV32-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v16, v10
; RV32-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV32-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV32-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV32-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v16, v10
; RV32-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV32-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV32-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV32-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV32-NEXT:    vfmadd.vv v10, v14, v12, v0.t
; RV32-NEXT:    vfmul.vf v12, v14, fa4, v0.t
; RV32-NEXT:    vfmul.vv v10, v12, v10, v0.t
; RV32-NEXT:    vfabs.v v8, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV32-NEXT:    vmerge.vim v8, v10, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI6_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI6_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI6_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI6_1)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI6_2)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    fld fa5, %lo(.LCPI6_2)(a0)
; RV64-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v16, v10
; RV64-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV64-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV64-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV64-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v16, v10
; RV64-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV64-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV64-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV64-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV64-NEXT:    vfmadd.vv v10, v14, v12, v0.t
; RV64-NEXT:    vfmul.vf v12, v14, fa4, v0.t
; RV64-NEXT:    vfmul.vv v10, v12, v10, v0.t
; RV64-NEXT:    vfabs.v v8, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV64-NEXT:    vmerge.vim v8, v10, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x double> @llvm.vp.sqrt.nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @sqrt_nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: sqrt_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v16, v8
; CHECK-NEXT:    vfmul.vv v20, v8, v16, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI7_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI7_0)
; CHECK-NEXT:    vsetvli a2, zero, e64, m4, ta, ma
; CHECK-NEXT:    vlse64.v v12, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI7_1)
; CHECK-NEXT:    fld fa5, %lo(.LCPI7_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmv4r.v v24, v16
; CHECK-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; CHECK-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v16, v16, v24, v0.t
; CHECK-NEXT:    vfmul.vv v20, v8, v16, v0.t
; CHECK-NEXT:    vmv.v.v v24, v16
; CHECK-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; CHECK-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v16, v16, v24, v0.t
; CHECK-NEXT:    vfmul.vv v20, v8, v16, v0.t
; CHECK-NEXT:    vfmadd.vv v16, v20, v12, v0.t
; CHECK-NEXT:    lui a0, %hi(.LCPI7_2)
; CHECK-NEXT:    fld fa4, %lo(.LCPI7_2)(a0)
; CHECK-NEXT:    vfmul.vf v12, v20, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v16, v0.t
; CHECK-NEXT:    vfabs.v v8, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v8, fa4, v0.t
; CHECK-NEXT:    vmerge.vim v8, v12, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_nxv4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, %hi(.LCPI7_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI7_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI7_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI7_1)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI7_2)
; RV32-NEXT:    vfmv.v.f v16, fa5
; RV32-NEXT:    fld fa5, %lo(.LCPI7_2)(a0)
; RV32-NEXT:    vfmul.vv v20, v8, v12, v0.t
; RV32-NEXT:    vmv.v.v v24, v12
; RV32-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; RV32-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; RV32-NEXT:    vfmul.vv v12, v12, v24, v0.t
; RV32-NEXT:    vfmul.vv v20, v8, v12, v0.t
; RV32-NEXT:    vmv.v.v v24, v12
; RV32-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; RV32-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; RV32-NEXT:    vfmul.vv v12, v12, v24, v0.t
; RV32-NEXT:    vfmul.vv v20, v8, v12, v0.t
; RV32-NEXT:    vfmadd.vv v12, v20, v16, v0.t
; RV32-NEXT:    vfmul.vf v16, v20, fa4, v0.t
; RV32-NEXT:    vfmul.vv v12, v16, v12, v0.t
; RV32-NEXT:    vfabs.v v8, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV32-NEXT:    vmerge.vim v8, v12, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, %hi(.LCPI7_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI7_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI7_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI7_1)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI7_2)
; RV64-NEXT:    vfmv.v.f v16, fa5
; RV64-NEXT:    fld fa5, %lo(.LCPI7_2)(a0)
; RV64-NEXT:    vfmul.vv v20, v8, v12, v0.t
; RV64-NEXT:    vmv.v.v v24, v12
; RV64-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; RV64-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; RV64-NEXT:    vfmul.vv v12, v12, v24, v0.t
; RV64-NEXT:    vfmul.vv v20, v8, v12, v0.t
; RV64-NEXT:    vmv.v.v v24, v12
; RV64-NEXT:    vfmadd.vv v24, v20, v16, v0.t
; RV64-NEXT:    vfmul.vf v12, v12, fa4, v0.t
; RV64-NEXT:    vfmul.vv v12, v12, v24, v0.t
; RV64-NEXT:    vfmul.vv v20, v8, v12, v0.t
; RV64-NEXT:    vfmadd.vv v12, v20, v16, v0.t
; RV64-NEXT:    vfmul.vf v16, v20, fa4, v0.t
; RV64-NEXT:    vfmul.vv v12, v16, v12, v0.t
; RV64-NEXT:    vfabs.v v8, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v8, fa5, v0.t
; RV64-NEXT:    vmerge.vim v8, v12, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x double> @llvm.vp.sqrt.nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @sqrt_nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; RV32-LABEL: sqrt_nxv8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 5
; RV32-NEXT:    sub sp, sp, a1
; RV32-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x20, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 32 * vlenb
; RV32-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV32-NEXT:    vmv8r.v v16, v8
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    lui a0, %hi(.LCPI8_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI8_0)(a0)
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    lui a0, %hi(.LCPI8_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI8_1)(a0)
; RV32-NEXT:    vfmv.v.f v24, fa5
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v24, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vv v8, v16, v8, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; RV32-NEXT:    vfmul.vv v24, v8, v24, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vs8r.v v24, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vv v8, v8, v24, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmadd.vv v24, v16, v8, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; RV32-NEXT:    vfmul.vv v24, v8, v24, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vv v16, v8, v24, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmadd.vv v24, v16, v8, v0.t
; RV32-NEXT:    lui a0, %hi(.LCPI8_2)
; RV32-NEXT:    fld fa5, %lo(.LCPI8_2)(a0)
; RV32-NEXT:    vfmul.vf v8, v16, fa4, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v24, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfabs.v v16, v16, v0.t
; RV32-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 5
; RV32-NEXT:    add sp, sp, a0
; RV32-NEXT:    .cfi_def_cfa sp, 16
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_nxv8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -16
; RV64-NEXT:    .cfi_def_cfa_offset 16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 5
; RV64-NEXT:    sub sp, sp, a1
; RV64-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x20, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 32 * vlenb
; RV64-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV64-NEXT:    vmv8r.v v16, v8
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    lui a0, %hi(.LCPI8_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI8_0)(a0)
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    lui a0, %hi(.LCPI8_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI8_1)(a0)
; RV64-NEXT:    vfmv.v.f v24, fa5
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v24, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vv v8, v16, v8, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; RV64-NEXT:    vfmul.vv v24, v8, v24, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vs8r.v v24, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vv v8, v8, v24, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmadd.vv v24, v16, v8, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; RV64-NEXT:    vfmul.vv v24, v8, v24, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vv v16, v8, v24, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmadd.vv v24, v16, v8, v0.t
; RV64-NEXT:    lui a0, %hi(.LCPI8_2)
; RV64-NEXT:    fld fa5, %lo(.LCPI8_2)(a0)
; RV64-NEXT:    vfmul.vf v8, v16, fa4, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v24, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfabs.v v16, v16, v0.t
; RV64-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 5
; RV64-NEXT:    add sp, sp, a0
; RV64-NEXT:    .cfi_def_cfa sp, 16
; RV64-NEXT:    addi sp, sp, 16
; RV64-NEXT:    .cfi_def_cfa_offset 0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x double> @llvm.vp.sqrt.nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x double> %1
}

define <vscale x 2 x half> @sqrt_zero_steps_nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a0, 1024
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v9, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    vfabs.v v10, v8, v0.t
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    vfabs.v v10, v8, v0.t
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x half> @llvm.vp.sqrt.nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @sqrt_zero_steps_nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    li a0, 1024
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v9, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    vfabs.v v10, v8, v0.t
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    vfabs.v v10, v8, v0.t
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x half> @llvm.vp.sqrt.nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @sqrt_zero_steps_nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    li a0, 1024
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    vfabs.v v12, v8, v0.t
; RV32-NEXT:    li a0, 1024
; RV32-NEXT:    fmv.h.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    vfabs.v v12, v8, v0.t
; RV64-NEXT:    li a0, 1024
; RV64-NEXT:    fmv.h.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x half> @llvm.vp.sqrt.nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x float> @sqrt_zero_steps_nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfabs.v v9, v8, v0.t
; CHECK-NEXT:    lui a0, 2048
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v9, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v9
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    vfabs.v v10, v8, v0.t
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    vfabs.v v10, v8, v0.t
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x float> @llvm.vp.sqrt.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x float> %1
}

define <vscale x 4 x float> @sqrt_zero_steps_nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    lui a0, 2048
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    vfabs.v v12, v8, v0.t
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    vfabs.v v12, v8, v0.t
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x float> @llvm.vp.sqrt.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x float> %1
}

define <vscale x 8 x float> @sqrt_zero_steps_nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vfabs.v v12, v8, v0.t
; CHECK-NEXT:    lui a0, 2048
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v12
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    vfabs.v v16, v8, v0.t
; RV32-NEXT:    lui a0, 2048
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    vfabs.v v16, v8, v0.t
; RV64-NEXT:    lui a0, 2048
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x float> @llvm.vp.sqrt.nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x float> %1
}

define <vscale x 2 x double> @sqrt_zero_steps_nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI15_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI15_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfabs.v v10, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v10, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v10
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI15_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI15_0)(a0)
; RV32-NEXT:    vfabs.v v12, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI15_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI15_0)(a0)
; RV64-NEXT:    vfabs.v v12, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 2 x double> @llvm.vp.sqrt.nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @sqrt_zero_steps_nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI16_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI16_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfabs.v v12, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v12, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v12
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v12, v8
; RV32-NEXT:    lui a0, %hi(.LCPI16_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI16_0)(a0)
; RV32-NEXT:    vfabs.v v16, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v12
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v12, v8
; RV64-NEXT:    lui a0, %hi(.LCPI16_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI16_0)(a0)
; RV64-NEXT:    vfabs.v v16, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v12
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 4 x double> @llvm.vp.sqrt.nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @sqrt_zero_steps_nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: sqrt_zero_steps_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI17_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI17_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vfabs.v v16, v8, v0.t
; CHECK-NEXT:    vmflt.vf v0, v16, fa5, v0.t
; CHECK-NEXT:    vfrsqrt7.v v16, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v16
; CHECK-NEXT:    vmerge.vim v8, v8, 0, v0
; CHECK-NEXT:    ret
; RV32-LABEL: sqrt_zero_steps_nxv8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, %hi(.LCPI17_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI17_0)(a0)
; RV32-NEXT:    vfabs.v v24, v8, v0.t
; RV32-NEXT:    vmflt.vf v0, v24, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v16
; RV32-NEXT:    vmerge.vim v8, v8, 0, v0
; RV32-NEXT:    ret
;
; RV64-LABEL: sqrt_zero_steps_nxv8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, %hi(.LCPI17_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI17_0)(a0)
; RV64-NEXT:    vfabs.v v24, v8, v0.t
; RV64-NEXT:    vmflt.vf v0, v24, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v16
; RV64-NEXT:    vmerge.vim v8, v8, 0, v0
; RV64-NEXT:    ret
  %1 = tail call fast <vscale x 8 x double> @llvm.vp.sqrt.nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x double> %1
}
define <vscale x 2 x half> @rsqrt_nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI18_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI18_0)
; CHECK-NEXT:    vsetvli a2, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vlse16.v v10, (a1), zero
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vmv1r.v v11, v9
; CHECK-NEXT:    lui a0, %hi(.LCPI18_1)
; CHECK-NEXT:    flh fa5, %lo(.LCPI18_1)(a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI18_2)
; CHECK-NEXT:    flh fa4, %lo(.LCPI18_2)(a0)
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, %hi(.LCPI18_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI18_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI18_1)
; RV32-NEXT:    flh fa4, %lo(.LCPI18_1)(a0)
; RV32-NEXT:    vfmv.v.f v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9, v0.t
; RV32-NEXT:    vmv1r.v v11, v9
; RV32-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; RV32-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v11, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, %hi(.LCPI18_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI18_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI18_1)
; RV64-NEXT:    flh fa4, %lo(.LCPI18_1)(a0)
; RV64-NEXT:    vfmv.v.f v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9, v0.t
; RV64-NEXT:    vmv1r.v v11, v9
; RV64-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; RV64-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v11, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x half> @llvm.vp.sqrt.nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 2 x half> @llvm.vp.fdiv.nxv2f16(<vscale x 2 x half> %splat, <vscale x 2 x half>  %1,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x half> %2
}

define <vscale x 4 x half> @rsqrt_nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI19_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI19_0)
; CHECK-NEXT:    vsetvli a2, zero, e16, m1, ta, ma
; CHECK-NEXT:    vlse16.v v10, (a1), zero
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v11, v9
; CHECK-NEXT:    lui a0, %hi(.LCPI19_1)
; CHECK-NEXT:    flh fa5, %lo(.LCPI19_1)(a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI19_2)
; CHECK-NEXT:    flh fa4, %lo(.LCPI19_2)(a0)
; CHECK-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, %hi(.LCPI19_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI19_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI19_1)
; RV32-NEXT:    flh fa4, %lo(.LCPI19_1)(a0)
; RV32-NEXT:    vfmv.v.f v10, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v9, v0.t
; RV32-NEXT:    vmv.v.v v11, v9
; RV32-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; RV32-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v11, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, %hi(.LCPI19_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI19_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI19_1)
; RV64-NEXT:    flh fa4, %lo(.LCPI19_1)(a0)
; RV64-NEXT:    vfmv.v.f v10, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v9, v0.t
; RV64-NEXT:    vmv.v.v v11, v9
; RV64-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; RV64-NEXT:    vfmul.vf v8, v9, fa4, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v11, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x half> @llvm.vp.sqrt.nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 4 x half> @llvm.vp.fdiv.nxv4f16(<vscale x 4 x half> %splat, <vscale x 4 x half>  %1,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x half> %2
}

define <vscale x 8 x half> @rsqrt_nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI20_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI20_0)
; CHECK-NEXT:    vsetvli a2, zero, e16, m2, ta, ma
; CHECK-NEXT:    vlse16.v v12, (a1), zero
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vmv2r.v v14, v10
; CHECK-NEXT:    lui a0, %hi(.LCPI20_1)
; CHECK-NEXT:    flh fa5, %lo(.LCPI20_1)(a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI20_2)
; CHECK-NEXT:    flh fa4, %lo(.LCPI20_2)(a0)
; CHECK-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v14, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI20_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI20_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI20_1)
; RV32-NEXT:    flh fa4, %lo(.LCPI20_1)(a0)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v14, v10
; RV32-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; RV32-NEXT:    vfmul.vf v8, v10, fa4, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v14, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI20_0)
; RV64-NEXT:    flh fa5, %lo(.LCPI20_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI20_1)
; RV64-NEXT:    flh fa4, %lo(.LCPI20_1)(a0)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v14, v10
; RV64-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; RV64-NEXT:    vfmul.vf v8, v10, fa4, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v14, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x half> @llvm.vp.sqrt.nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 8 x half> @llvm.vp.fdiv.nxv8f16(<vscale x 8 x half> %splat, <vscale x 8 x half>  %1,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x half> %2
}

define <vscale x 2 x float> @rsqrt_nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v9, v8
; CHECK-NEXT:    vfmul.vv v10, v8, v9, v0.t
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetvli a2, zero, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v11, a1
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vmv1r.v v12, v9
; CHECK-NEXT:    vfmadd.vv v12, v10, v11, v0.t
; CHECK-NEXT:    lui a0, 782336
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v9, v9, v12, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v9, v0.t
; CHECK-NEXT:    vmv.v.v v10, v9
; CHECK-NEXT:    vfmadd.vv v10, v8, v11, v0.t
; CHECK-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v9, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v10, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v11, v8, v9, v0.t
; RV32-NEXT:    vmv.v.v v12, v9
; RV32-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; RV32-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; RV32-NEXT:    vfmul.vv v9, v9, v12, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v9, v0.t
; RV32-NEXT:    vmv.v.v v11, v9
; RV32-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; RV32-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v11, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v9, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v10, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v11, v8, v9, v0.t
; RV64-NEXT:    vmv.v.v v12, v9
; RV64-NEXT:    vfmadd.vv v12, v11, v10, v0.t
; RV64-NEXT:    vfmul.vf v9, v9, fa5, v0.t
; RV64-NEXT:    vfmul.vv v9, v9, v12, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v9, v0.t
; RV64-NEXT:    vmv.v.v v11, v9
; RV64-NEXT:    vfmadd.vv v11, v8, v10, v0.t
; RV64-NEXT:    vfmul.vf v8, v9, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v11, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x float> %ins, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x float> @llvm.vp.sqrt.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 2 x float> @llvm.vp.fdiv.nxv2f32(<vscale x 2 x float> %splat, <vscale x 2 x float>  %1,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x float> %2
}

define <vscale x 4 x float> @rsqrt_nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v12, v8, v10, v0.t
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetvli a2, zero, e32, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v14, a1
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vmv2r.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v12, v14, v0.t
; CHECK-NEXT:    lui a0, 782336
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v12, v10
; CHECK-NEXT:    vfmadd.vv v12, v8, v14, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v12, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v16, v10
; RV32-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV32-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; RV32-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v14, v10
; RV32-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; RV32-NEXT:    vfmul.vf v8, v10, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v14, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v12, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v16, v10
; RV64-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV64-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; RV64-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v14, v10
; RV64-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; RV64-NEXT:    vfmul.vf v8, v10, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v14, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x float> %ins, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x float> @llvm.vp.sqrt.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 4 x float> @llvm.vp.fdiv.nxv4f32(<vscale x 4 x float> %splat, <vscale x 4 x float>  %1,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x float> %2
}

define <vscale x 8 x float> @rsqrt_nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v12, v8
; CHECK-NEXT:    vfmul.vv v16, v8, v12, v0.t
; CHECK-NEXT:    lui a1, 787456
; CHECK-NEXT:    vsetvli a2, zero, e32, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v20, a1
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vmv4r.v v24, v12
; CHECK-NEXT:    vfmadd.vv v24, v16, v20, v0.t
; CHECK-NEXT:    lui a0, 782336
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v12, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v12, v12, v24, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vmv.v.v v16, v12
; CHECK-NEXT:    vfmadd.vv v16, v8, v20, v0.t
; CHECK-NEXT:    vfmul.vf v8, v12, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v16, v0.t
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, 787456
; RV32-NEXT:    vmv.v.x v12, a0
; RV32-NEXT:    lui a0, 782336
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV32-NEXT:    vmv.v.v v24, v16
; RV32-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV32-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; RV32-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV32-NEXT:    vmv.v.v v20, v16
; RV32-NEXT:    vfmadd.vv v20, v8, v12, v0.t
; RV32-NEXT:    vfmul.vf v8, v16, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v20, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, 787456
; RV64-NEXT:    vmv.v.x v12, a0
; RV64-NEXT:    lui a0, 782336
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV64-NEXT:    vmv.v.v v24, v16
; RV64-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV64-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; RV64-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV64-NEXT:    vmv.v.v v20, v16
; RV64-NEXT:    vfmadd.vv v20, v8, v12, v0.t
; RV64-NEXT:    vfmul.vf v8, v16, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v20, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x float> %ins, <vscale x 8 x float> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x float> @llvm.vp.sqrt.nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 8 x float> @llvm.vp.fdiv.nxv8f32(<vscale x 8 x float> %splat, <vscale x 8 x float>  %1,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x float> %2
}

define <vscale x 2 x double> @rsqrt_nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    vfmul.vv v12, v8, v10, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI24_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI24_0)
; CHECK-NEXT:    vsetvli a2, zero, e64, m2, ta, ma
; CHECK-NEXT:    vlse64.v v14, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI24_1)
; CHECK-NEXT:    fld fa5, %lo(.LCPI24_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vmv2r.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v12, v14, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v12, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v16, v10
; CHECK-NEXT:    vfmadd.vv v16, v12, v14, v0.t
; CHECK-NEXT:    vfmul.vf v10, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v10, v10, v16, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v10, v0.t
; CHECK-NEXT:    vmv.v.v v12, v10
; CHECK-NEXT:    lui a0, %hi(.LCPI24_2)
; CHECK-NEXT:    fld fa4, %lo(.LCPI24_2)(a0)
; CHECK-NEXT:    vfmadd.vv v12, v8, v14, v0.t
; CHECK-NEXT:    vfmul.vf v8, v10, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v12, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v10, v8
; RV32-NEXT:    lui a0, %hi(.LCPI24_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI24_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI24_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI24_1)(a0)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v16, v10
; RV32-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV32-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV32-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV32-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v16, v10
; RV32-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV32-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV32-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV32-NEXT:    vmv.v.v v14, v10
; RV32-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; RV32-NEXT:    vfmul.vf v8, v10, fa4, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v14, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v10, v8
; RV64-NEXT:    lui a0, %hi(.LCPI24_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI24_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI24_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI24_1)(a0)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v16, v10
; RV64-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV64-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV64-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV64-NEXT:    vfmul.vv v14, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v16, v10
; RV64-NEXT:    vfmadd.vv v16, v14, v12, v0.t
; RV64-NEXT:    vfmul.vf v10, v10, fa4, v0.t
; RV64-NEXT:    vfmul.vv v10, v10, v16, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v10, v0.t
; RV64-NEXT:    vmv.v.v v14, v10
; RV64-NEXT:    vfmadd.vv v14, v8, v12, v0.t
; RV64-NEXT:    vfmul.vf v8, v10, fa4, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v14, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x double> @llvm.vp.sqrt.nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 2 x double> @llvm.vp.fdiv.nxv2f64(<vscale x 2 x double> %splat, <vscale x 2 x double>  %1,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x double> %2
}

define <vscale x 4 x double> @rsqrt_nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v16, v8
; CHECK-NEXT:    vfmul.vv v20, v8, v16, v0.t
; CHECK-NEXT:    lui a1, %hi(.LCPI25_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI25_0)
; CHECK-NEXT:    vsetvli a2, zero, e64, m4, ta, ma
; CHECK-NEXT:    vlse64.v v12, (a1), zero
; CHECK-NEXT:    lui a1, %hi(.LCPI25_1)
; CHECK-NEXT:    fld fa5, %lo(.LCPI25_1)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vmv4r.v v24, v16
; CHECK-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; CHECK-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v16, v16, v24, v0.t
; CHECK-NEXT:    vfmul.vv v20, v8, v16, v0.t
; CHECK-NEXT:    vmv.v.v v24, v16
; CHECK-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; CHECK-NEXT:    vfmul.vf v16, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v16, v16, v24, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v16, v0.t
; CHECK-NEXT:    vmv.v.v v20, v16
; CHECK-NEXT:    lui a0, %hi(.LCPI25_2)
; CHECK-NEXT:    fld fa4, %lo(.LCPI25_2)(a0)
; CHECK-NEXT:    vfmadd.vv v20, v8, v12, v0.t
; CHECK-NEXT:    vfmul.vf v8, v16, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v20, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v16, v8
; RV32-NEXT:    lui a0, %hi(.LCPI25_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI25_0)(a0)
; RV32-NEXT:    lui a0, %hi(.LCPI25_1)
; RV32-NEXT:    fld fa4, %lo(.LCPI25_1)(a0)
; RV32-NEXT:    vfmv.v.f v12, fa5
; RV32-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV32-NEXT:    vmv.v.v v24, v16
; RV32-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV32-NEXT:    vfmul.vf v16, v16, fa4, v0.t
; RV32-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV32-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV32-NEXT:    vmv.v.v v24, v16
; RV32-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV32-NEXT:    vfmul.vf v16, v16, fa4, v0.t
; RV32-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV32-NEXT:    vmv.v.v v20, v16
; RV32-NEXT:    vfmadd.vv v20, v8, v12, v0.t
; RV32-NEXT:    vfmul.vf v8, v16, fa4, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v20, v0.t
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v16, v8
; RV64-NEXT:    lui a0, %hi(.LCPI25_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI25_0)(a0)
; RV64-NEXT:    lui a0, %hi(.LCPI25_1)
; RV64-NEXT:    fld fa4, %lo(.LCPI25_1)(a0)
; RV64-NEXT:    vfmv.v.f v12, fa5
; RV64-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV64-NEXT:    vmv.v.v v24, v16
; RV64-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV64-NEXT:    vfmul.vf v16, v16, fa4, v0.t
; RV64-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV64-NEXT:    vfmul.vv v20, v8, v16, v0.t
; RV64-NEXT:    vmv.v.v v24, v16
; RV64-NEXT:    vfmadd.vv v24, v20, v12, v0.t
; RV64-NEXT:    vfmul.vf v16, v16, fa4, v0.t
; RV64-NEXT:    vfmul.vv v16, v16, v24, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV64-NEXT:    vmv.v.v v20, v16
; RV64-NEXT:    vfmadd.vv v20, v8, v12, v0.t
; RV64-NEXT:    vfmul.vf v8, v16, fa4, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v20, v0.t
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x double> @llvm.vp.sqrt.nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 4 x double> @llvm.vp.fdiv.nxv4f64(<vscale x 4 x double> %splat, <vscale x 4 x double>  %1,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x double> %2
}

define <vscale x 8 x double> @rsqrt_nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: rsqrt_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 5
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x20, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 32 * vlenb
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    li a2, 24
; CHECK-NEXT:    mul a1, a1, a2
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # Unknown-size Folded Spill
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v24, v8
; CHECK-NEXT:    vfmul.vv v16, v8, v24, v0.t
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v24, (a1) # Unknown-size Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v16, (a1) # Unknown-size Folded Spill
; CHECK-NEXT:    lui a1, %hi(.LCPI26_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI26_0)
; CHECK-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; CHECK-NEXT:    lui a2, %hi(.LCPI26_1)
; CHECK-NEXT:    vlse64.v v16, (a1), zero
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 4
; CHECK-NEXT:    add a1, sp, a1
; CHECK-NEXT:    addi a1, a1, 16
; CHECK-NEXT:    vs8r.v v16, (a1) # Unknown-size Folded Spill
; CHECK-NEXT:    fld fa5, %lo(.LCPI26_1)(a2)
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v24, v0.t
; CHECK-NEXT:    vs8r.v v8, (a0) # Unknown-size Folded Spill
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v24, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmul.vv v24, v24, v8, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v24, (a0) # Unknown-size Folded Spill
; CHECK-NEXT:    vmv.v.v v24, v8
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v16, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmadd.vv v24, v16, v8, v0.t
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v16, v8, v24, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v16, (a0) # Unknown-size Folded Spill
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmul.vv v8, v8, v16, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v8, (a0) # Unknown-size Folded Spill
; CHECK-NEXT:    lui a0, %hi(.LCPI26_2)
; CHECK-NEXT:    fld fa4, %lo(.LCPI26_2)(a0)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v24, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmadd.vv v16, v24, v8, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # Unknown-size Folded Reload
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    vfmul.vv v8, v8, v16, v0.t
; CHECK-NEXT:    vfmul.vf v8, v8, fa4, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 5
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_nxv8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a1, a1, 5
; RV32-NEXT:    sub sp, sp, a1
; RV32-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x20, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 32 * vlenb
; RV32-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV32-NEXT:    vmv8r.v v16, v8
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    lui a0, %hi(.LCPI26_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI26_0)(a0)
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    lui a0, %hi(.LCPI26_1)
; RV32-NEXT:    vfmv.v.f v24, fa5
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    li a2, 24
; RV32-NEXT:    mul a1, a1, a2
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 16
; RV32-NEXT:    vs8r.v v24, (a1) # vscale x 64-byte Folded Spill
; RV32-NEXT:    fld fa5, %lo(.LCPI26_1)(a0)
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vv v8, v16, v8, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV32-NEXT:    vfmul.vv v24, v8, v24, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vv v8, v16, v24, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vs8r.v v24, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV32-NEXT:    vfmul.vv v16, v8, v24, v0.t
; RV32-NEXT:    vs8r.v v16, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 24
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 4
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 16
; RV32-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmadd.vv v16, v24, v8, v0.t
; RV32-NEXT:    addi a0, sp, 16
; RV32-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV32-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV32-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    slli a0, a0, 5
; RV32-NEXT:    add sp, sp, a0
; RV32-NEXT:    .cfi_def_cfa sp, 16
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_nxv8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -16
; RV64-NEXT:    .cfi_def_cfa_offset 16
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a1, a1, 5
; RV64-NEXT:    sub sp, sp, a1
; RV64-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x20, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 32 * vlenb
; RV64-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV64-NEXT:    vmv8r.v v16, v8
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    lui a0, %hi(.LCPI26_0)
; RV64-NEXT:    fld fa5, %lo(.LCPI26_0)(a0)
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    lui a0, %hi(.LCPI26_1)
; RV64-NEXT:    vfmv.v.f v24, fa5
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    li a2, 24
; RV64-NEXT:    mul a1, a1, a2
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 16
; RV64-NEXT:    vs8r.v v24, (a1) # vscale x 64-byte Folded Spill
; RV64-NEXT:    fld fa5, %lo(.LCPI26_1)(a0)
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vv v8, v16, v8, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV64-NEXT:    vfmul.vv v24, v8, v24, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vv v8, v16, v24, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vs8r.v v24, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmadd.vv v24, v8, v16, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV64-NEXT:    vfmul.vv v16, v8, v24, v0.t
; RV64-NEXT:    vs8r.v v16, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 24
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 4
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 16
; RV64-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmadd.vv v16, v24, v8, v0.t
; RV64-NEXT:    addi a0, sp, 16
; RV64-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; RV64-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; RV64-NEXT:    vfmul.vv v8, v8, v16, v0.t
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    slli a0, a0, 5
; RV64-NEXT:    add sp, sp, a0
; RV64-NEXT:    .cfi_def_cfa sp, 16
; RV64-NEXT:    addi sp, sp, 16
; RV64-NEXT:    .cfi_def_cfa_offset 0
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x double> @llvm.vp.sqrt.nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 8 x double> @llvm.vp.fdiv.nxv8f64(<vscale x 8 x double> %splat, <vscale x 8 x double>  %1,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x double> %2
}

define <vscale x 2 x half> @rsqrt_zero_steps_nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI27_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI27_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv2f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv2f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x half> @llvm.vp.sqrt.nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 2 x half> @llvm.vp.fdiv.nxv2f16(<vscale x 2 x half> %splat, <vscale x 2 x half>  %1,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x half> %2
}

define <vscale x 4 x half> @rsqrt_zero_steps_nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI28_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI28_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv4f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv4f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x half> @llvm.vp.sqrt.nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 4 x half> @llvm.vp.fdiv.nxv4f16(<vscale x 4 x half> %splat, <vscale x 4 x half>  %1,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x half> %2
}

define <vscale x 8 x half> @rsqrt_zero_steps_nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI29_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI29_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv8f16:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv8f16:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x half> @llvm.vp.sqrt.nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 8 x half> @llvm.vp.fdiv.nxv8f16(<vscale x 8 x half> %splat, <vscale x 8 x half>  %1,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x half> %2
}

define <vscale x 2 x float> @rsqrt_zero_steps_nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv2f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv2f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x float> %ins, <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x float> @llvm.vp.sqrt.nxv2f32(<vscale x 2 x float> %a, <vscale x 2 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 2 x float> @llvm.vp.fdiv.nxv2f32(<vscale x 2 x float> %splat, <vscale x 2 x float>  %1,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x float> %2
}

define <vscale x 4 x float> @rsqrt_zero_steps_nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv4f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv4f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x float> %ins, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x float> @llvm.vp.sqrt.nxv4f32(<vscale x 4 x float> %a, <vscale x 4 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 4 x float> @llvm.vp.fdiv.nxv4f32(<vscale x 4 x float> %splat, <vscale x 4 x float>  %1,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x float> %2
}

define <vscale x 8 x float> @rsqrt_zero_steps_nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv8f32:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv8f32:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x float> poison, float 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x float> %ins, <vscale x 8 x float> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x float> @llvm.vp.sqrt.nxv8f32(<vscale x 8 x float> %a, <vscale x 8 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 8 x float> @llvm.vp.fdiv.nxv8f32(<vscale x 8 x float> %splat, <vscale x 8 x float>  %1,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x float> %2
}

define <vscale x 2 x double> @rsqrt_zero_steps_nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI33_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI33_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = tail call fast <vscale x 2 x double> @llvm.vp.sqrt.nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 2 x double> @llvm.vp.fdiv.nxv2f64(<vscale x 2 x double> %splat, <vscale x 2 x double>  %1,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x double> %2
}

define <vscale x 4 x double> @rsqrt_zero_steps_nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI34_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI34_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv4f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv4f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = tail call fast <vscale x 4 x double> @llvm.vp.sqrt.nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 4 x double> @llvm.vp.fdiv.nxv4f64(<vscale x 4 x double> %splat, <vscale x 4 x double>  %1,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x double> %2
}

define <vscale x 8 x double> @rsqrt_zero_steps_nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: rsqrt_zero_steps_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI35_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI35_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vfmul.vf v8, v8, fa5, v0.t
; CHECK-NEXT:    ret
; RV32-LABEL: rsqrt_zero_steps_nxv8f64:
; RV32:       # %bb.0:
; RV32-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV32-NEXT:    vfrsqrt7.v v8, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: rsqrt_zero_steps_nxv8f64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; RV64-NEXT:    vfrsqrt7.v v8, v8
; RV64-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = tail call fast <vscale x 8 x double> @llvm.vp.sqrt.nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 %evl)
  %2 = call fast <vscale x 8 x double> @llvm.vp.fdiv.nxv8f64(<vscale x 8 x double> %splat, <vscale x 8 x double>  %1,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x double> %2
}

attributes #0 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-sqrt" }
attributes #1 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-sqrt:0" }
