; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN:  llc -mtriple=riscv64 -mattr=+f,+d,+v,+zfh,+xsfvcp \
; RUN:    -verify-machineinstrs < %s | FileCheck %s

define void @test_sf_vc_xvv_se_e64m1(<vscale x 1 x i64> %vd, <vscale x 1 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_xvv_se_e64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    sf.vc.xvv 3, v8, v9, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.xvv.se.i32.nxv1i64.i64.i64(i32 3, <vscale x 1 x i64> %vd, <vscale x 1 x i64> %vs2, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.xvv.se.i32.nxv1i64.i64.i64(i32, <vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define void @test_sf_vc_xvv_se_e64m2(<vscale x 2 x i64> %vd, <vscale x 2 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_xvv_se_e64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    sf.vc.xvv 3, v8, v10, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.xvv.se.i32.nxv2i64.i64.i64(i32 3, <vscale x 2 x i64> %vd, <vscale x 2 x i64> %vs2, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.xvv.se.i32.nxv2i64.i64.i64(i32, <vscale x 2 x i64>, <vscale x 2 x i64>, i64, i64)

define void @test_sf_vc_xvv_se_e64m4(<vscale x 4 x i64> %vd, <vscale x 4 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_xvv_se_e64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    sf.vc.xvv 3, v8, v12, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.xvv.se.i32.nxv4i64.i64.i64(i32 3, <vscale x 4 x i64> %vd, <vscale x 4 x i64> %vs2, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.xvv.se.i32.nxv4i64.i64.i64(i32, <vscale x 4 x i64>, <vscale x 4 x i64>, i64, i64)

define void @test_sf_vc_xvv_se_e64m8(<vscale x 8 x i64> %vd, <vscale x 8 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_xvv_se_e64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; CHECK-NEXT:    sf.vc.xvv 3, v8, v16, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.sf.vc.xvv.se.i32.nxv8i64.i64.i64(i32 3, <vscale x 8 x i64> %vd, <vscale x 8 x i64> %vs2, i64 %rs1, i64 %vl)
  ret void
}

declare void @llvm.riscv.sf.vc.xvv.se.i32.nxv8i64.i64.i64(i32, <vscale x 8 x i64>, <vscale x 8 x i64>, i64, i64)

define <vscale x 1 x i64> @test_sf_vc_v_xvv_se_e64m1(<vscale x 1 x i64> %vd, <vscale x 1 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_se_e64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 1 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv1i64.i32.i64.i64(i32 3, <vscale x 1 x i64> %vd, <vscale x 1 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 1 x i64> %0
}

declare <vscale x 1 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv1i64.i32.i64.i64(i32, <vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 2 x i64> @test_sf_vc_v_xvv_se_e64m2(<vscale x 2 x i64> %vd, <vscale x 2 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_se_e64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v10, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 2 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv2i64.i32.i64.i64(i32 3, <vscale x 2 x i64> %vd, <vscale x 2 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 2 x i64> %0
}

declare <vscale x 2 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv2i64.i32.i64.i64(i32, <vscale x 2 x i64>, <vscale x 2 x i64>, i64, i64)

define <vscale x 4 x i64> @test_sf_vc_v_xvv_se_e64m4(<vscale x 4 x i64> %vd, <vscale x 4 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_se_e64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v12, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv4i64.i32.i64.i64(i32 3, <vscale x 4 x i64> %vd, <vscale x 4 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 4 x i64> %0
}

declare <vscale x 4 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv4i64.i32.i64.i64(i32, <vscale x 4 x i64>, <vscale x 4 x i64>, i64, i64)

define <vscale x 8 x i64> @test_sf_vc_v_xvv_se_e64m8(<vscale x 8 x i64> %vd, <vscale x 8 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_se_e64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v16, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv8i64.i32.i64.i64(i32 3, <vscale x 8 x i64> %vd, <vscale x 8 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 8 x i64> %0
}

declare <vscale x 8 x i64> @llvm.riscv.sf.vc.v.xvv.se.nxv8i64.i32.i64.i64(i32, <vscale x 8 x i64>, <vscale x 8 x i64>, i64, i64)

define <vscale x 1 x i64> @test_sf_vc_v_xvv_e64m1(<vscale x 1 x i64> %vd, <vscale x 1 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_e64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v9, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 1 x i64> @llvm.riscv.sf.vc.v.xvv.nxv1i64.i32.i64.i64(i32 3, <vscale x 1 x i64> %vd, <vscale x 1 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 1 x i64> %0
}

declare <vscale x 1 x i64> @llvm.riscv.sf.vc.v.xvv.nxv1i64.i32.i64.i64(i32, <vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 2 x i64> @test_sf_vc_v_xvv_e64m2(<vscale x 2 x i64> %vd, <vscale x 2 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_e64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v10, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 2 x i64> @llvm.riscv.sf.vc.v.xvv.nxv2i64.i32.i64.i64(i32 3, <vscale x 2 x i64> %vd, <vscale x 2 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 2 x i64> %0
}

declare <vscale x 2 x i64> @llvm.riscv.sf.vc.v.xvv.nxv2i64.i32.i64.i64(i32, <vscale x 2 x i64>, <vscale x 2 x i64>, i64, i64)

define <vscale x 4 x i64> @test_sf_vc_v_xvv_e64m4(<vscale x 4 x i64> %vd, <vscale x 4 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_e64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v12, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x i64> @llvm.riscv.sf.vc.v.xvv.nxv4i64.i32.i64.i64(i32 3, <vscale x 4 x i64> %vd, <vscale x 4 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 4 x i64> %0
}

declare <vscale x 4 x i64> @llvm.riscv.sf.vc.v.xvv.nxv4i64.i32.i64.i64(i32, <vscale x 4 x i64>, <vscale x 4 x i64>, i64, i64)

define <vscale x 8 x i64> @test_sf_vc_v_xvv_e64m8(<vscale x 8 x i64> %vd, <vscale x 8 x i64> %vs2, i64 %rs1, i64 %vl) {
; CHECK-LABEL: test_sf_vc_v_xvv_e64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; CHECK-NEXT:    sf.vc.v.xvv 3, v8, v16, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 8 x i64> @llvm.riscv.sf.vc.v.xvv.nxv8i64.i32.i64.i64(i32 3, <vscale x 8 x i64> %vd, <vscale x 8 x i64> %vs2, i64 %rs1, i64 %vl)
  ret <vscale x 8 x i64> %0
}

declare <vscale x 8 x i64> @llvm.riscv.sf.vc.v.xvv.nxv8i64.i32.i64.i64(i32, <vscale x 8 x i64>, <vscale x 8 x i64>, i64, i64)
