; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v,+zfh,+zvfh | FileCheck %s --check-prefixes=CHECK,RV64

; Integers

define <vscale x 80 x i1> @vector_interleave_nxv80i1_nxv16i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b, <vscale x 16 x i1> %c, <vscale x 16 x i1> %d, <vscale x 16 x i1> %e) nounwind {
; CHECK-LABEL: vector_interleave_nxv80i1_nxv16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 10
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmv.v.i v12, 0
; CHECK-NEXT:    addi a4, sp, 16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a1, a0, 2
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vmerge.vim v14, v12, 1, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    vmerge.vim v18, v12, 1, v0
; CHECK-NEXT:    add a2, a4, a1
; CHECK-NEXT:    srli a3, a1, 1
; CHECK-NEXT:    vmv2r.v v20, v14
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    vmerge.vim v16, v12, 1, v0
; CHECK-NEXT:    vmv1r.v v21, v18
; CHECK-NEXT:    vmv1r.v v0, v10
; CHECK-NEXT:    vmerge.vim v8, v12, 1, v0
; CHECK-NEXT:    vmv1r.v v22, v16
; CHECK-NEXT:    vmv1r.v v16, v19
; CHECK-NEXT:    add a5, a2, a1
; CHECK-NEXT:    vmv1r.v v23, v8
; CHECK-NEXT:    vmv1r.v v18, v9
; CHECK-NEXT:    vmv1r.v v0, v11
; CHECK-NEXT:    vmerge.vim v24, v12, 1, v0
; CHECK-NEXT:    vsetvli a6, zero, e8, m1, ta, ma
; CHECK-NEXT:    vsseg5e8.v v20, (a4)
; CHECK-NEXT:    vmv1r.v v19, v25
; CHECK-NEXT:    vsseg5e8.v v15, (a0)
; CHECK-NEXT:    vl1r.v v8, (a5)
; CHECK-NEXT:    add a5, a5, a1
; CHECK-NEXT:    vl1r.v v10, (a4)
; CHECK-NEXT:    add a4, a5, a1
; CHECK-NEXT:    vl1r.v v12, (a4)
; CHECK-NEXT:    add a4, a0, a1
; CHECK-NEXT:    vl1r.v v14, (a4)
; CHECK-NEXT:    add a4, a4, a1
; CHECK-NEXT:    vl1r.v v9, (a5)
; CHECK-NEXT:    add a5, a4, a1
; CHECK-NEXT:    vl1r.v v16, (a5)
; CHECK-NEXT:    add a5, a5, a1
; CHECK-NEXT:    srli a1, a1, 2
; CHECK-NEXT:    vl1r.v v11, (a2)
; CHECK-NEXT:    vl1r.v v15, (a4)
; CHECK-NEXT:    vl1r.v v13, (a0)
; CHECK-NEXT:    vl1r.v v17, (a5)
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmsne.vi v8, v8, 0
; CHECK-NEXT:    vmsne.vi v0, v10, 0
; CHECK-NEXT:    vmsne.vi v9, v14, 0
; CHECK-NEXT:    vmsne.vi v10, v12, 0
; CHECK-NEXT:    vsetvli a0, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v8, a1
; CHECK-NEXT:    vslideup.vx v10, v9, a1
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v10, a3
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmsne.vi v8, v16, 0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 10
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 80 x i1> @llvm.vector.interleave5.nxv80i1(<vscale x 16 x i1> %a, <vscale x 16 x i1> %b, <vscale x 16 x i1> %c, <vscale x 16 x i1> %d, <vscale x 16 x i1> %e)
  ret <vscale x 80 x i1> %res
}

declare <vscale x 80 x i1> @llvm.vector.interleave5.nxv80i1(<vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>, <vscale x 16 x i1>)

define <vscale x 80 x i8> @vector_interleave_nxv80i8_nxv16i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %b, <vscale x 16 x i8> %c, <vscale x 16 x i8> %d, <vscale x 16 x i8> %e) nounwind {
; RV32-LABEL: vector_interleave_nxv80i8_nxv16i8:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v16
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv2r.v v18, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a2, a1, 2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv2r.v v16, v8
; RV32-NEXT:    vmv2r.v v22, v16
; RV32-NEXT:    vmv2r.v v24, v18
; RV32-NEXT:    vmv1r.v v26, v20
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v23, v10
; RV32-NEXT:    add a4, a1, a2
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vmv1r.v v25, v14
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v18, v11
; RV32-NEXT:    vsseg5e8.v v22, (a0)
; RV32-NEXT:    vmv1r.v v20, v15
; RV32-NEXT:    vsseg5e8.v v17, (a1)
; RV32-NEXT:    vl1r.v v16, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1r.v v17, (a6)
; RV32-NEXT:    add a6, a3, a2
; RV32-NEXT:    vl1r.v v10, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1r.v v11, (a6)
; RV32-NEXT:    vl1r.v v8, (a0)
; RV32-NEXT:    vl1r.v v9, (a3)
; RV32-NEXT:    vl1r.v v14, (a4)
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a3, 10
; RV32-NEXT:    mul a0, a0, a3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 64
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1r.v v15, (a5)
; RV32-NEXT:    vl1r.v v12, (a6)
; RV32-NEXT:    vl1r.v v13, (a1)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a0, a2
; RV32-NEXT:    vs2r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a0)
; RV32-NEXT:    vl8r.v v16, (a2)
; RV32-NEXT:    vl8r.v v8, (a0)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv80i8_nxv16i8:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v16
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv2r.v v18, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a2, a1, 2
; RV64-NEXT:    add a1, a2, a1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv2r.v v16, v8
; RV64-NEXT:    vmv2r.v v22, v16
; RV64-NEXT:    vmv2r.v v24, v18
; RV64-NEXT:    vmv1r.v v26, v20
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v23, v10
; RV64-NEXT:    add a4, a1, a2
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vmv1r.v v25, v14
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v18, v11
; RV64-NEXT:    vsseg5e8.v v22, (a0)
; RV64-NEXT:    vmv1r.v v20, v15
; RV64-NEXT:    vsseg5e8.v v17, (a1)
; RV64-NEXT:    vl1r.v v16, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1r.v v17, (a6)
; RV64-NEXT:    add a6, a3, a2
; RV64-NEXT:    vl1r.v v10, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1r.v v11, (a6)
; RV64-NEXT:    vl1r.v v8, (a0)
; RV64-NEXT:    vl1r.v v9, (a3)
; RV64-NEXT:    vl1r.v v14, (a4)
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a3, 10
; RV64-NEXT:    mul a0, a0, a3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 64
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1r.v v15, (a5)
; RV64-NEXT:    vl1r.v v12, (a6)
; RV64-NEXT:    vl1r.v v13, (a1)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a0, a2
; RV64-NEXT:    vs2r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a0)
; RV64-NEXT:    vl8r.v v16, (a2)
; RV64-NEXT:    vl8r.v v8, (a0)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 80 x i8> @llvm.vector.interleave5.nxv80i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %b, <vscale x 16 x i8> %c, <vscale x 16 x i8> %d, <vscale x 16 x i8> %e)
  ret <vscale x 80 x i8> %res
}

declare <vscale x 80 x i8> @llvm.vector.interleave5.nxv80i8(<vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)

define <vscale x 40 x i8> @vector_interleave_nxv40i8_nxv8i8(<vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 8 x i8> %c, <vscale x 8 x i8> %d, <vscale x 8 x i8> %e) nounwind {
; CHECK-LABEL: vector_interleave_nxv40i8_nxv8i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a1, a0, 2
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    sub sp, sp, a0
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    add a2, a0, a1
; CHECK-NEXT:    add a3, a2, a1
; CHECK-NEXT:    vsetvli a4, zero, e8, m1, ta, ma
; CHECK-NEXT:    vsseg5e8.v v8, (a0)
; CHECK-NEXT:    vl1r.v v10, (a3)
; CHECK-NEXT:    add a3, a3, a1
; CHECK-NEXT:    vl1r.v v11, (a3)
; CHECK-NEXT:    vl1r.v v8, (a0)
; CHECK-NEXT:    vl1r.v v9, (a2)
; CHECK-NEXT:    add a1, a3, a1
; CHECK-NEXT:    vl1r.v v12, (a1)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a1, a0, 2
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %res = call <vscale x 40 x i8> @llvm.vector.interleave5.nxv40i8(<vscale x 8 x i8> %a, <vscale x 8 x i8> %b, <vscale x 8 x i8> %c, <vscale x 8 x i8> %d, <vscale x 8 x i8> %e)
  ret <vscale x 40 x i8> %res
}

declare <vscale x 40 x i8> @llvm.vector.interleave5.nxv40i8(<vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>)

define <vscale x 20 x i32> @vector_interleave_nxv20i32_nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, <vscale x 4 x i32> %d, <vscale x 4 x i32> %e) nounwind {
; RV32-LABEL: vector_interleave_nxv20i32_nxv4i32:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v16
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv2r.v v18, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a2, a1, 2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv2r.v v16, v8
; RV32-NEXT:    vmv2r.v v22, v16
; RV32-NEXT:    vmv2r.v v24, v18
; RV32-NEXT:    vmv1r.v v26, v20
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v23, v10
; RV32-NEXT:    add a4, a1, a2
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vmv1r.v v25, v14
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v18, v11
; RV32-NEXT:    vsseg5e32.v v22, (a0)
; RV32-NEXT:    vmv1r.v v20, v15
; RV32-NEXT:    vsseg5e32.v v17, (a1)
; RV32-NEXT:    vl1re32.v v16, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re32.v v17, (a6)
; RV32-NEXT:    add a6, a3, a2
; RV32-NEXT:    vl1re32.v v10, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re32.v v11, (a6)
; RV32-NEXT:    vl1re32.v v8, (a0)
; RV32-NEXT:    vl1re32.v v9, (a3)
; RV32-NEXT:    vl1re32.v v14, (a4)
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a3, 10
; RV32-NEXT:    mul a0, a0, a3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 64
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re32.v v15, (a5)
; RV32-NEXT:    vl1re32.v v12, (a6)
; RV32-NEXT:    vl1re32.v v13, (a1)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a0, a2
; RV32-NEXT:    vs2r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a0)
; RV32-NEXT:    vl8re32.v v16, (a2)
; RV32-NEXT:    vl8re32.v v8, (a0)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv20i32_nxv4i32:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v16
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv2r.v v18, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a2, a1, 2
; RV64-NEXT:    add a1, a2, a1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv2r.v v16, v8
; RV64-NEXT:    vmv2r.v v22, v16
; RV64-NEXT:    vmv2r.v v24, v18
; RV64-NEXT:    vmv1r.v v26, v20
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v23, v10
; RV64-NEXT:    add a4, a1, a2
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vmv1r.v v25, v14
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v18, v11
; RV64-NEXT:    vsseg5e32.v v22, (a0)
; RV64-NEXT:    vmv1r.v v20, v15
; RV64-NEXT:    vsseg5e32.v v17, (a1)
; RV64-NEXT:    vl1re32.v v16, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re32.v v17, (a6)
; RV64-NEXT:    add a6, a3, a2
; RV64-NEXT:    vl1re32.v v10, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re32.v v11, (a6)
; RV64-NEXT:    vl1re32.v v8, (a0)
; RV64-NEXT:    vl1re32.v v9, (a3)
; RV64-NEXT:    vl1re32.v v14, (a4)
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a3, 10
; RV64-NEXT:    mul a0, a0, a3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 64
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re32.v v15, (a5)
; RV64-NEXT:    vl1re32.v v12, (a6)
; RV64-NEXT:    vl1re32.v v13, (a1)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a0, a2
; RV64-NEXT:    vs2r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a0)
; RV64-NEXT:    vl8re32.v v16, (a2)
; RV64-NEXT:    vl8re32.v v8, (a0)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 20 x i32> @llvm.vector.interleave5.nxv20i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, <vscale x 4 x i32> %c, <vscale x 4 x i32> %d, <vscale x 4 x i32> %e)
  ret <vscale x 20 x i32> %res
}

declare <vscale x 20 x i32> @llvm.vector.interleave5.nxv20i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)

define <vscale x 10 x i64> @vector_interleave_nxv10i64_nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c, <vscale x 2 x i64> %d, <vscale x 2 x i64> %e) nounwind {
; RV32-LABEL: vector_interleave_nxv10i64_nxv2i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -80
; RV32-NEXT:    sw ra, 76(sp) # 4-byte Folded Spill
; RV32-NEXT:    sw s0, 72(sp) # 4-byte Folded Spill
; RV32-NEXT:    addi s0, sp, 80
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a1, 28
; RV32-NEXT:    mul a0, a0, a1
; RV32-NEXT:    sub sp, sp, a0
; RV32-NEXT:    andi sp, sp, -64
; RV32-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; RV32-NEXT:    vmv2r.v v20, v16
; RV32-NEXT:    addi a0, sp, 64
; RV32-NEXT:    vmv2r.v v18, v12
; RV32-NEXT:    csrr a1, vlenb
; RV32-NEXT:    slli a2, a1, 2
; RV32-NEXT:    add a1, a2, a1
; RV32-NEXT:    add a1, sp, a1
; RV32-NEXT:    addi a1, a1, 64
; RV32-NEXT:    csrr a2, vlenb
; RV32-NEXT:    vmv2r.v v16, v8
; RV32-NEXT:    vmv2r.v v22, v16
; RV32-NEXT:    vmv2r.v v24, v18
; RV32-NEXT:    vmv1r.v v26, v20
; RV32-NEXT:    add a3, a0, a2
; RV32-NEXT:    vmv1r.v v23, v10
; RV32-NEXT:    add a4, a1, a2
; RV32-NEXT:    add a5, a4, a2
; RV32-NEXT:    vmv1r.v v25, v14
; RV32-NEXT:    add a6, a5, a2
; RV32-NEXT:    vmv1r.v v18, v11
; RV32-NEXT:    vsseg5e64.v v22, (a0)
; RV32-NEXT:    vmv1r.v v20, v15
; RV32-NEXT:    vsseg5e64.v v17, (a1)
; RV32-NEXT:    vl1re64.v v16, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re64.v v17, (a6)
; RV32-NEXT:    add a6, a3, a2
; RV32-NEXT:    vl1re64.v v10, (a6)
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re64.v v11, (a6)
; RV32-NEXT:    vl1re64.v v8, (a0)
; RV32-NEXT:    vl1re64.v v9, (a3)
; RV32-NEXT:    vl1re64.v v14, (a4)
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    li a3, 10
; RV32-NEXT:    mul a0, a0, a3
; RV32-NEXT:    add a0, sp, a0
; RV32-NEXT:    addi a0, a0, 64
; RV32-NEXT:    add a6, a6, a2
; RV32-NEXT:    vl1re64.v v15, (a5)
; RV32-NEXT:    vl1re64.v v12, (a6)
; RV32-NEXT:    vl1re64.v v13, (a1)
; RV32-NEXT:    slli a2, a2, 3
; RV32-NEXT:    add a2, a0, a2
; RV32-NEXT:    vs2r.v v16, (a2)
; RV32-NEXT:    vs8r.v v8, (a0)
; RV32-NEXT:    vl8re64.v v16, (a2)
; RV32-NEXT:    vl8re64.v v8, (a0)
; RV32-NEXT:    addi sp, s0, -80
; RV32-NEXT:    lw ra, 76(sp) # 4-byte Folded Reload
; RV32-NEXT:    lw s0, 72(sp) # 4-byte Folded Reload
; RV32-NEXT:    addi sp, sp, 80
; RV32-NEXT:    ret
;
; RV64-LABEL: vector_interleave_nxv10i64_nxv2i64:
; RV64:       # %bb.0:
; RV64-NEXT:    addi sp, sp, -80
; RV64-NEXT:    sd ra, 72(sp) # 8-byte Folded Spill
; RV64-NEXT:    sd s0, 64(sp) # 8-byte Folded Spill
; RV64-NEXT:    addi s0, sp, 80
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a1, 28
; RV64-NEXT:    mul a0, a0, a1
; RV64-NEXT:    sub sp, sp, a0
; RV64-NEXT:    andi sp, sp, -64
; RV64-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; RV64-NEXT:    vmv2r.v v20, v16
; RV64-NEXT:    addi a0, sp, 64
; RV64-NEXT:    vmv2r.v v18, v12
; RV64-NEXT:    csrr a1, vlenb
; RV64-NEXT:    slli a2, a1, 2
; RV64-NEXT:    add a1, a2, a1
; RV64-NEXT:    add a1, sp, a1
; RV64-NEXT:    addi a1, a1, 64
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv2r.v v16, v8
; RV64-NEXT:    vmv2r.v v22, v16
; RV64-NEXT:    vmv2r.v v24, v18
; RV64-NEXT:    vmv1r.v v26, v20
; RV64-NEXT:    add a3, a0, a2
; RV64-NEXT:    vmv1r.v v23, v10
; RV64-NEXT:    add a4, a1, a2
; RV64-NEXT:    add a5, a4, a2
; RV64-NEXT:    vmv1r.v v25, v14
; RV64-NEXT:    add a6, a5, a2
; RV64-NEXT:    vmv1r.v v18, v11
; RV64-NEXT:    vsseg5e64.v v22, (a0)
; RV64-NEXT:    vmv1r.v v20, v15
; RV64-NEXT:    vsseg5e64.v v17, (a1)
; RV64-NEXT:    vl1re64.v v16, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re64.v v17, (a6)
; RV64-NEXT:    add a6, a3, a2
; RV64-NEXT:    vl1re64.v v10, (a6)
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re64.v v11, (a6)
; RV64-NEXT:    vl1re64.v v8, (a0)
; RV64-NEXT:    vl1re64.v v9, (a3)
; RV64-NEXT:    vl1re64.v v14, (a4)
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    li a3, 10
; RV64-NEXT:    mul a0, a0, a3
; RV64-NEXT:    add a0, sp, a0
; RV64-NEXT:    addi a0, a0, 64
; RV64-NEXT:    add a6, a6, a2
; RV64-NEXT:    vl1re64.v v15, (a5)
; RV64-NEXT:    vl1re64.v v12, (a6)
; RV64-NEXT:    vl1re64.v v13, (a1)
; RV64-NEXT:    slli a2, a2, 3
; RV64-NEXT:    add a2, a0, a2
; RV64-NEXT:    vs2r.v v16, (a2)
; RV64-NEXT:    vs8r.v v8, (a0)
; RV64-NEXT:    vl8re64.v v16, (a2)
; RV64-NEXT:    vl8re64.v v8, (a0)
; RV64-NEXT:    addi sp, s0, -80
; RV64-NEXT:    ld ra, 72(sp) # 8-byte Folded Reload
; RV64-NEXT:    ld s0, 64(sp) # 8-byte Folded Reload
; RV64-NEXT:    addi sp, sp, 80
; RV64-NEXT:    ret
  %res = call <vscale x 10 x i64> @llvm.vector.interleave5.nxv10i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b, <vscale x 2 x i64> %c, <vscale x 2 x i64> %d, <vscale x 2 x i64> %e)
  ret <vscale x 10 x i64> %res
}

declare <vscale x 10 x i64> @llvm.vector.interleave5.nxv10i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
