; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple riscv64 -mattr=+v < %s | FileCheck %s --check-prefixes=CHECK

define <4 x i32> @square_diff_1(<4 x i8> %x, <4 x i8> %y) {
; CHECK-LABEL: square_diff_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vwsubu.vv v10, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vwmul.vv v8, v10, v10
; CHECK-NEXT:    ret
  %a = zext <4 x i8> %x to <4 x i32>
  %b = zext <4 x i8> %y to <4 x i32>
  %c = sub <4 x i32> %a, %b
  %d = mul <4 x i32> %c, %c
  ret <4 x i32> %d
}

define <4 x i64> @square_diff_2(<4 x i16> %x, <4 x i16> %y) {
; CHECK-LABEL: square_diff_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vwsubu.vv v10, v8, v9
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vwmul.vv v8, v10, v10
; CHECK-NEXT:    ret
  %a = zext <4 x i16> %x to <4 x i64>
  %b = zext <4 x i16> %y to <4 x i64>
  %c = sub <4 x i64> %a, %b
  %d = mul <4 x i64> %c, %c
  ret <4 x i64> %d
}
