; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mcpu=sifive-x280o < %s | FileCheck %s

define <vscale x 1 x i64> @add_test(ptr %X, i32 signext %value, i64 %N, <vscale x 1 x i64> %Arg) {
; CHECK-LABEL: add_test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vmseq.vx v0, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    vmerge.vim v9, v9, 1, v0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %broadcast.splatinsert = insertelement <vscale x 1 x i32> poison, i32 %value, i64 0
  %broadcast.splat = shufflevector <vscale x 1 x i32> %broadcast.splatinsert, <vscale x 1 x i32> poison, <vscale x 1 x i32> zeroinitializer
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %N, i64 3, i64 0)
  %1 = trunc i64 %0 to i32
  %2 = getelementptr inbounds i32, ptr %X, i64 0
  %vp.op.load = tail call <vscale x 1 x i32> @llvm.vp.load.nxv1i32.p0(ptr %2, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.icmp = tail call <vscale x 1 x i1> @llvm.vp.icmp.nxv1i32(<vscale x 1 x i32> %vp.op.load, <vscale x 1 x i32> %broadcast.splat, metadata !"eq", <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.cast = tail call <vscale x 1 x i64> @llvm.vp.zext.nxv1i64.nxv1i1(<vscale x 1 x i1> %vp.op.icmp, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op = tail call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> %Arg, <vscale x 1 x i64> %vp.cast, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.select = tail call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i64> %vp.op, <vscale x 1 x i64> %Arg, i32 %1)
  ret <vscale x 1 x i64> %vp.op.select
}

define <vscale x 1 x i64> @sub_test(ptr %X, i32 signext %value, i64 %N, <vscale x 1 x i64> %Arg) {
; CHECK-LABEL: sub_test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vmseq.vx v0, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v9, 0
; CHECK-NEXT:    vmerge.vim v9, v9, -1, v0
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vadd.vv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %broadcast.splatinsert = insertelement <vscale x 1 x i32> poison, i32 %value, i64 0
  %broadcast.splat = shufflevector <vscale x 1 x i32> %broadcast.splatinsert, <vscale x 1 x i32> poison, <vscale x 1 x i32> zeroinitializer
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %N, i64 3, i64 0)
  %1 = trunc i64 %0 to i32
  %2 = getelementptr inbounds i32, ptr %X, i64 0
  %vp.op.load = tail call <vscale x 1 x i32> @llvm.vp.load.nxv1i32.p0(ptr %2, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.icmp = tail call <vscale x 1 x i1> @llvm.vp.icmp.nxv1i32(<vscale x 1 x i32> %vp.op.load, <vscale x 1 x i32> %broadcast.splat, metadata !"eq", <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.cast = tail call <vscale x 1 x i64> @llvm.vp.sext.nxv1i64.nxv1i1(<vscale x 1 x i1> %vp.op.icmp, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op = tail call <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64> %Arg, <vscale x 1 x i64> %vp.cast, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.select = tail call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i64> %vp.op, <vscale x 1 x i64> %Arg, i32 %1)
  ret <vscale x 1 x i64> %vp.op.select
}

define <vscale x 1 x i64> @or_test(ptr %X, i32 signext %value, i64 %N, <vscale x 1 x i64> %Arg) {
; CHECK-LABEL: or_test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vmseq.vx v0, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, mu
; CHECK-NEXT:    vor.vi v8, v8, 1, v0.t
; CHECK-NEXT:    ret
entry:
  %broadcast.splatinsert = insertelement <vscale x 1 x i32> poison, i32 %value, i64 0
  %broadcast.splat = shufflevector <vscale x 1 x i32> %broadcast.splatinsert, <vscale x 1 x i32> poison, <vscale x 1 x i32> zeroinitializer
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %N, i64 3, i64 0)
  %1 = trunc i64 %0 to i32
  %2 = getelementptr inbounds i32, ptr %X, i64 0
  %vp.op.load = tail call <vscale x 1 x i32> @llvm.vp.load.nxv1i32.p0(ptr %2, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.icmp = tail call <vscale x 1 x i1> @llvm.vp.icmp.nxv1i32(<vscale x 1 x i32> %vp.op.load, <vscale x 1 x i32> %broadcast.splat, metadata !"eq", <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.cast = tail call <vscale x 1 x i64> @llvm.vp.zext.nxv1i64.nxv1i1(<vscale x 1 x i1> %vp.op.icmp, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op = tail call <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64> %Arg, <vscale x 1 x i64> %vp.cast, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.select = tail call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i64> %vp.op, <vscale x 1 x i64> %Arg, i32 %1)
  ret <vscale x 1 x i64> %vp.op.select
}

define <vscale x 1 x i64> @xor_test(ptr %X, i32 signext %value, i64 %N, <vscale x 1 x i64> %Arg) {
; CHECK-LABEL: xor_test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v9, (a0)
; CHECK-NEXT:    vmseq.vx v0, v9, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, mu
; CHECK-NEXT:    vxor.vi v8, v8, 1, v0.t
; CHECK-NEXT:    ret
entry:
  %broadcast.splatinsert = insertelement <vscale x 1 x i32> poison, i32 %value, i64 0
  %broadcast.splat = shufflevector <vscale x 1 x i32> %broadcast.splatinsert, <vscale x 1 x i32> poison, <vscale x 1 x i32> zeroinitializer
  %0 = tail call i64 @llvm.riscv.vsetvli.i64(i64 %N, i64 3, i64 0)
  %1 = trunc i64 %0 to i32
  %2 = getelementptr inbounds i32, ptr %X, i64 0
  %vp.op.load = tail call <vscale x 1 x i32> @llvm.vp.load.nxv1i32.p0(ptr %2, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.icmp = tail call <vscale x 1 x i1> @llvm.vp.icmp.nxv1i32(<vscale x 1 x i32> %vp.op.load, <vscale x 1 x i32> %broadcast.splat, metadata !"eq", <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.cast = tail call <vscale x 1 x i64> @llvm.vp.zext.nxv1i64.nxv1i1(<vscale x 1 x i1> %vp.op.icmp, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op = tail call <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64> %Arg, <vscale x 1 x i64> %vp.cast, <vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), i32 %1)
  %vp.op.select = tail call <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1> shufflevector (<vscale x 1 x i1> insertelement (<vscale x 1 x i1> poison, i1 true, i32 0), <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer), <vscale x 1 x i64> %vp.op, <vscale x 1 x i64> %Arg, i32 %1)
  ret <vscale x 1 x i64> %vp.op.select
}

declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)

declare <vscale x 1 x i32> @llvm.vp.load.nxv1i32.p0(ptr nocapture, <vscale x 1 x i1>, i32)

declare <vscale x 1 x i1> @llvm.vp.icmp.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, metadata, <vscale x 1 x i1>, i32)

declare <vscale x 1 x i64> @llvm.vp.sext.nxv1i64.nxv1i1(<vscale x 1 x i1>, <vscale x 1 x i1>, i32)

declare <vscale x 1 x i64> @llvm.vp.add.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)

declare <vscale x 1 x i64> @llvm.vp.or.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)

declare <vscale x 1 x i64> @llvm.vp.xor.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i1>, i32)

declare <vscale x 1 x i64> @llvm.vp.merge.nxv1i64(<vscale x 1 x i1>, <vscale x 1 x i64>, <vscale x 1 x i64>, i32)

declare i64 @llvm.vector.reduce.add.nxv1i64(<vscale x 1 x i64>)

declare <vscale x 1 x i64> @llvm.vp.zext.nxv1i64.nxv1i1(<vscale x 1 x i1>, <vscale x 1 x i1>, i32)
