; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=false -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=NOALIGN
; RUN: llc -mtriple=riscv64 -mattr=+v -mcpu=sifive-x280 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN
; RUN: llc -mtriple=riscv64 -mattr=+v -mcpu=sifive-x280 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   --riscv-v-vector-bits-max=512 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN-VLEN
; RUN: llc -mtriple=riscv64 -mattr=+v -mcpu=sifive-p470 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN-VLEN-MALLARD

define void @UnKnownSize(ptr nocapture readonly %dst, i8 %val, i64 signext %n) {
; NOALIGN-LABEL: UnKnownSize:
; NOALIGN:       # %bb.0: # %entry
; NOALIGN-NEXT:    vsetvli zero, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vmv.v.x v8, a1
; NOALIGN-NEXT:  .LBB0_1: # %memset-forward-loop
; NOALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; NOALIGN-NEXT:    vsetvli a1, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vse8.v v8, (a0)
; NOALIGN-NEXT:    sub a2, a2, a1
; NOALIGN-NEXT:    add a0, a0, a1
; NOALIGN-NEXT:    bnez a2, .LBB0_1
; NOALIGN-NEXT:  # %bb.2: # %memset-post-loop
; NOALIGN-NEXT:    ret
;
; ALIGN-LABEL: UnKnownSize:
; ALIGN:       # %bb.0: # %entry
; ALIGN-NEXT:    andi a4, a0, 31
; ALIGN-NEXT:    li a5, 32
; ALIGN-NEXT:    vsetvli a3, zero, e8, m8, ta, ma
; ALIGN-NEXT:    sub a5, a5, a4
; ALIGN-NEXT:    minu a4, a5, a2
; ALIGN-NEXT:    vsetvli a5, a4, e8, m8, ta, ma
; ALIGN-NEXT:    minu a3, a3, a2
; ALIGN-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; ALIGN-NEXT:    vmv.v.x v8, a1
; ALIGN-NEXT:    sub a1, a2, a5
; ALIGN-NEXT:    add a2, a0, a5
; ALIGN-NEXT:    vsetvli zero, a4, e8, m8, ta, ma
; ALIGN-NEXT:    vse8.v v8, (a0)
; ALIGN-NEXT:  .LBB0_1: # %memset-forward-loop
; ALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-NEXT:    vsetvli a0, a1, e8, m8, ta, ma
; ALIGN-NEXT:    vse8.v v8, (a2)
; ALIGN-NEXT:    add a2, a2, a0
; ALIGN-NEXT:    sub a1, a1, a0
; ALIGN-NEXT:    bnez a1, .LBB0_1
; ALIGN-NEXT:  # %bb.2: # %memset-post-loop
; ALIGN-NEXT:    ret
;
; ALIGN-VLEN-LABEL: UnKnownSize:
; ALIGN-VLEN:       # %bb.0: # %entry
; ALIGN-VLEN-NEXT:    andi a4, a0, 31
; ALIGN-VLEN-NEXT:    li a5, 32
; ALIGN-VLEN-NEXT:    sub a5, a5, a4
; ALIGN-VLEN-NEXT:    li a3, 512
; ALIGN-VLEN-NEXT:    minu a4, a5, a2
; ALIGN-VLEN-NEXT:    vsetvli a5, a4, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    minu a3, a2, a3
; ALIGN-VLEN-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    vmv.v.x v8, a1
; ALIGN-VLEN-NEXT:    vsetvli zero, a4, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    sub a1, a2, a5
; ALIGN-VLEN-NEXT:    add a2, a0, a5
; ALIGN-VLEN-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-NEXT:  .LBB0_1: # %memset-forward-loop
; ALIGN-VLEN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-VLEN-NEXT:    vsetvli a0, a1, e8, m8, ta, ma
; ALIGN-VLEN-NEXT:    vse8.v v8, (a2)
; ALIGN-VLEN-NEXT:    add a2, a2, a0
; ALIGN-VLEN-NEXT:    sub a1, a1, a0
; ALIGN-VLEN-NEXT:    bnez a1, .LBB0_1
; ALIGN-VLEN-NEXT:  # %bb.2: # %memset-post-loop
; ALIGN-VLEN-NEXT:    ret
;
; ALIGN-VLEN-MALLARD-LABEL: UnKnownSize:
; ALIGN-VLEN-MALLARD:       # %bb.0: # %entry
; ALIGN-VLEN-MALLARD-NEXT:    vsetvli a3, zero, e8, m8, ta, ma
; ALIGN-VLEN-MALLARD-NEXT:    minu a3, a3, a2
; ALIGN-VLEN-MALLARD-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; ALIGN-VLEN-MALLARD-NEXT:    vmv.v.x v8, a1
; ALIGN-VLEN-MALLARD-NEXT:    andi a1, a0, 63
; ALIGN-VLEN-MALLARD-NEXT:    li a3, 64
; ALIGN-VLEN-MALLARD-NEXT:    sub a3, a3, a1
; ALIGN-VLEN-MALLARD-NEXT:    minu a1, a3, a2
; ALIGN-VLEN-MALLARD-NEXT:    vsetvli a3, a1, e8, m8, ta, ma
; ALIGN-VLEN-MALLARD-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-MALLARD-NEXT:    sub a1, a2, a3
; ALIGN-VLEN-MALLARD-NEXT:    add a0, a0, a3
; ALIGN-VLEN-MALLARD-NEXT:  .LBB0_1: # %memset-forward-loop
; ALIGN-VLEN-MALLARD-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-VLEN-MALLARD-NEXT:    vsetvli a2, a1, e8, m8, ta, ma
; ALIGN-VLEN-MALLARD-NEXT:    vse8.v v8, (a0)
; ALIGN-VLEN-MALLARD-NEXT:    add a0, a0, a2
; ALIGN-VLEN-MALLARD-NEXT:    sub a1, a1, a2
; ALIGN-VLEN-MALLARD-NEXT:    bnez a1, .LBB0_1
; ALIGN-VLEN-MALLARD-NEXT:  # %bb.2: # %memset-post-loop
; ALIGN-VLEN-MALLARD-NEXT:    ret
entry:
  tail call void @llvm.memset.p0.i8.i64(ptr align 1 %dst, i8 %val, i64 %n, i1 false)
  ret void
}

declare void @llvm.memset.p0.i8.i64(ptr noalias nocapture writeonly, i8, i64, i1 immarg)
