; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -verify-machineinstrs  | FileCheck %s --check-prefixes=CHECK
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -verify-machineinstrs  | FileCheck %s --check-prefixes=CHECK
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -relocation-model=pic -verify-machineinstrs  | FileCheck %s --check-prefixes=PIC
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -relocation-model=pic -verify-machineinstrs  | FileCheck %s --check-prefixes=PIC
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -code-model=medium -verify-machineinstrs  | FileCheck %s --check-prefixes=MEDIUM
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -code-model=medium -verify-machineinstrs  | FileCheck %s --check-prefixes=MEDIUM
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v \
; RUN:   -riscv-aggressive-constant-vlse -mattr=+optimized-zero-stride-load \
; RUN:   -code-model=compact -verify-machineinstrs  | FileCheck %s --check-prefixes=COMPACT

define <vscale x 1 x i8> @intrinsic_vmv.v.x_i_nxv1i8(iXLen %0) nounwind {
; CHECK-LABEL: intrinsic_vmv.v.x_i_nxv1i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a1, %hi(.LCPI0_0)
; CHECK-NEXT:    addi a1, a1, %lo(.LCPI0_0)
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; CHECK-NEXT:    vlse8.v v8, (a1), zero
; CHECK-NEXT:    ret
;
; PIC-LABEL: intrinsic_vmv.v.x_i_nxv1i8:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:  .Lpcrel_hi0:
; PIC-NEXT:    auipc a1, %pcrel_hi(.LCPI0_0)
; PIC-NEXT:    addi a1, a1, %pcrel_lo(.Lpcrel_hi0)
; PIC-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; PIC-NEXT:    vlse8.v v8, (a1), zero
; PIC-NEXT:    ret
;
; MEDIUM-LABEL: intrinsic_vmv.v.x_i_nxv1i8:
; MEDIUM:       # %bb.0: # %entry
; MEDIUM-NEXT:  .Lpcrel_hi0:
; MEDIUM-NEXT:    auipc a1, %pcrel_hi(.LCPI0_0)
; MEDIUM-NEXT:    addi a1, a1, %pcrel_lo(.Lpcrel_hi0)
; MEDIUM-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; MEDIUM-NEXT:    vlse8.v v8, (a1), zero
; MEDIUM-NEXT:    ret
;
; COMPACT-LABEL: intrinsic_vmv.v.x_i_nxv1i8:
; COMPACT:       # %bb.0: # %entry
; COMPACT-NEXT:    lui a1, %got_gprel_hi(.LCPI0_0)
; COMPACT-NEXT:    add a1, gp, a1, %got_gprel(.LCPI0_0)
; COMPACT-NEXT:    ld a1, %got_gprel_lo(.LCPI0_0)(a1)
; COMPACT-NEXT:    vsetvli zero, a0, e8, mf8, ta, ma
; COMPACT-NEXT:    vlse8.v v8, (a1), zero
; COMPACT-NEXT:    ret
entry:
  %a = call <vscale x 1 x i8> @llvm.riscv.vmv.v.x.nxv1i8(
    <vscale x 1 x i8> undef,
    i8 9,
    iXLen %0)

  ret <vscale x 1 x i8> %a
}
