# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -o - -mtriple=riscv64 -mattr=v -run-pass=riscv-cleanup-vxrm -verify-machineinstrs %s | FileCheck %s
---
name:            test
alignment:       2
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
registers:
  - { id: 0, class: gpr, preferred-register: '' }
  - { id: 1, class: gpr, preferred-register: '' }
  - { id: 2, class: gpr, preferred-register: '' }
  - { id: 3, class: gpr, preferred-register: '' }
  - { id: 4, class: gpr, preferred-register: '' }
  - { id: 5, class: gpr, preferred-register: '' }
  - { id: 6, class: gpr, preferred-register: '' }
  - { id: 7, class: gpr, preferred-register: '' }
  - { id: 8, class: gpr, preferred-register: '' }
  - { id: 9, class: gpr, preferred-register: '' }
  - { id: 10, class: gpr, preferred-register: '' }
  - { id: 11, class: gpr, preferred-register: '' }
  - { id: 12, class: gpr, preferred-register: '' }
  - { id: 13, class: gpr, preferred-register: '' }
  - { id: 14, class: gpr, preferred-register: '' }
  - { id: 15, class: vrm2, preferred-register: '' }
  - { id: 16, class: vrm2, preferred-register: '' }
  - { id: 17, class: gpr, preferred-register: '' }
  - { id: 18, class: vrm2, preferred-register: '' }
  - { id: 19, class: vrm2, preferred-register: '' }
  - { id: 20, class: gpr, preferred-register: '' }
  - { id: 21, class: vrm2, preferred-register: '' }
liveins:
  - { reg: '$x10', virtual-reg: '%0' }
  - { reg: '$x11', virtual-reg: '%1' }
  - { reg: '$x12', virtual-reg: '%2' }
  - { reg: '$x13', virtual-reg: '%3' }
  - { reg: '$x14', virtual-reg: '%4' }
  - { reg: '$x15', virtual-reg: '%5' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    16
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  maxCallFrameSize: 4294967295
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  hasTailCall:     false
  localFrameSize:  0
  savePoint:       ''
  restorePoint:    ''
fixedStack:
  - { id: 0, type: default, offset: 16, size: 8, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, type: default, offset: 8, size: 8, alignment: 8, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, type: default, offset: 0, size: 8, alignment: 16, stack-id: default,
      isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
stack:
  - { id: 0, name: '', type: default, offset: 0, size: 16, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 1, name: '', type: default, offset: 0, size: 16, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: '', type: default, offset: 0, size: 16, alignment: 16,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
callSites:       []
debugValueSubstitutions: []
constants:       []
machineFunctionInfo: {}
body:             |
  bb.0.entry:
    liveins: $x10, $x11, $x12, $x13, $x14, $x15

    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $x10, $x11, $x12, $x13, $x14, $x15
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x15
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x14
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr = COPY $x13
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gpr = COPY $x12
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[COPY5:%[0-9]+]]:gpr = COPY $x10
    ; CHECK-NEXT: [[SRLI:%[0-9]+]]:gpr = SRLI [[COPY1]], 32
    ; CHECK-NEXT: [[SRLI1:%[0-9]+]]:gpr = SRLI [[COPY]], 32
    ; CHECK-NEXT: [[SRLI2:%[0-9]+]]:gpr = SRLI [[COPY3]], 32
    ; CHECK-NEXT: [[SRLI3:%[0-9]+]]:gpr = SRLI [[COPY2]], 32
    ; CHECK-NEXT: [[SRLI4:%[0-9]+]]:gpr = SRLI [[COPY5]], 32
    ; CHECK-NEXT: [[SRLI5:%[0-9]+]]:gpr = SRLI [[COPY4]], 32
    ; CHECK-NEXT: [[LD:%[0-9]+]]:gpr = LD %fixed-stack.2, 0 :: (load (s64) from %fixed-stack.2, align 16)
    ; CHECK-NEXT: SW [[COPY4]], %stack.0, 8 :: (store (s32) into %stack.0 + 8, align 8, basealign 16)
    ; CHECK-NEXT: SW [[COPY5]], %stack.0, 0 :: (store (s32) into %stack.0, align 16)
    ; CHECK-NEXT: SW killed [[SRLI5]], %stack.0, 12 :: (store (s32) into %stack.0 + 12, basealign 16)
    ; CHECK-NEXT: SW killed [[SRLI4]], %stack.0, 4 :: (store (s32) into %stack.0 + 4, basealign 16)
    ; CHECK-NEXT: [[PseudoVLE32_V_M2_:%[0-9]+]]:vrm2 = PseudoVLE32_V_M2 %stack.0, 4, 5 /* e32 */
    ; CHECK-NEXT: SW [[COPY2]], %stack.1, 8 :: (store (s32) into %stack.1 + 8, align 8, basealign 16)
    ; CHECK-NEXT: SW [[COPY3]], %stack.1, 0 :: (store (s32) into %stack.1, align 16)
    ; CHECK-NEXT: SW killed [[SRLI3]], %stack.1, 12 :: (store (s32) into %stack.1 + 12, basealign 16)
    ; CHECK-NEXT: SW killed [[SRLI2]], %stack.1, 4 :: (store (s32) into %stack.1 + 4, basealign 16)
    ; CHECK-NEXT: [[PseudoVLE32_V_M2_1:%[0-9]+]]:vrm2 = PseudoVLE32_V_M2 %stack.1, 4, 5 /* e32 */
    ; CHECK-NEXT: [[ReadVXRM:%[0-9]+]]:gpr = ReadVXRM implicit $vxrm
    ; CHECK-NEXT: WriteVXRMImm 2, implicit-def dead $vxrm
    ; CHECK-NEXT: [[PseudoVAADD_VV_M2_:%[0-9]+]]:vrm2 = PseudoVAADD_VV_M2 [[PseudoVLE32_V_M2_]], killed [[PseudoVLE32_V_M2_1]], 4, 4, 5 /* e32 */, implicit $vxrm
    ; CHECK-NEXT: SW [[COPY]], %stack.2, 8 :: (store (s32) into %stack.2 + 8, align 8, basealign 16)
    ; CHECK-NEXT: SW [[COPY1]], %stack.2, 0 :: (store (s32) into %stack.2, align 16)
    ; CHECK-NEXT: SW killed [[SRLI1]], %stack.2, 12 :: (store (s32) into %stack.2 + 12, basealign 16)
    ; CHECK-NEXT: SW killed [[SRLI]], %stack.2, 4 :: (store (s32) into %stack.2 + 4, basealign 16)
    ; CHECK-NEXT: [[PseudoVLE32_V_M2_2:%[0-9]+]]:vrm2 = PseudoVLE32_V_M2 %stack.2, 4, 5 /* e32 */
    ; CHECK-NEXT: [[PseudoVAADD_VV_M2_1:%[0-9]+]]:vrm2 = PseudoVAADD_VV_M2 [[PseudoVLE32_V_M2_]], killed [[PseudoVLE32_V_M2_2]], 4, 4, 5 /* e32 */, implicit $vxrm
    ; CHECK-NEXT: WriteVXRM killed [[ReadVXRM]], implicit-def dead $vxrm
    ; CHECK-NEXT: PseudoVSE32_V_M2 killed [[PseudoVAADD_VV_M2_]], [[LD]], 4, 5 /* e32 */
    ; CHECK-NEXT: PseudoVSE32_V_M2 killed [[PseudoVAADD_VV_M2_1]], [[LD]], 4, 5 /* e32 */
    ; CHECK-NEXT: PseudoRET
    %5:gpr = COPY $x15
    %4:gpr = COPY $x14
    %3:gpr = COPY $x13
    %2:gpr = COPY $x12
    %1:gpr = COPY $x11
    %0:gpr = COPY $x10
    %8:gpr = SRLI %4, 32
    %9:gpr = SRLI %5, 32
    %10:gpr = SRLI %2, 32
    %11:gpr = SRLI %3, 32
    %12:gpr = SRLI %0, 32
    %13:gpr = SRLI %1, 32
    %14:gpr = LD %fixed-stack.0, 0 :: (load (s64) from %fixed-stack.0, align 16)
    SW %1, %stack.0, 8 :: (store (s32) into %stack.0 + 8, align 8, basealign 16)
    SW %0, %stack.0, 0 :: (store (s32) into %stack.0, align 16)
    SW killed %13, %stack.0, 12 :: (store (s32) into %stack.0 + 12, basealign 16)
    SW killed %12, %stack.0, 4 :: (store (s32) into %stack.0 + 4, basealign 16)
    %15:vrm2 = PseudoVLE32_V_M2 %stack.0, 4, 5
    SW %3, %stack.1, 8 :: (store (s32) into %stack.1 + 8, align 8, basealign 16)
    SW %2, %stack.1, 0 :: (store (s32) into %stack.1, align 16)
    SW killed %11, %stack.1, 12 :: (store (s32) into %stack.1 + 12, basealign 16)
    SW killed %10, %stack.1, 4 :: (store (s32) into %stack.1 + 4, basealign 16)
    %16:vrm2 = PseudoVLE32_V_M2 %stack.1, 4, 5
    %17:gpr = ReadVXRM implicit $vxrm
    WriteVXRMImm 2, implicit-def dead $vxrm
    %18:vrm2 = PseudoVAADD_VV_M2 %15, killed %16, 4, 4, 5, implicit $vxrm
    WriteVXRM killed %17, implicit-def dead $vxrm
    SW %5, %stack.2, 8 :: (store (s32) into %stack.2 + 8, align 8, basealign 16)
    SW %4, %stack.2, 0 :: (store (s32) into %stack.2, align 16)
    SW killed %9, %stack.2, 12 :: (store (s32) into %stack.2 + 12, basealign 16)
    SW killed %8, %stack.2, 4 :: (store (s32) into %stack.2 + 4, basealign 16)
    %19:vrm2 = PseudoVLE32_V_M2 %stack.2, 4, 5
    %20:gpr = ReadVXRM implicit $vxrm
    WriteVXRMImm 2, implicit-def dead $vxrm
    %21:vrm2 = PseudoVAADD_VV_M2 %15, killed %19, 4, 4, 5, implicit $vxrm
    WriteVXRM killed %20, implicit-def dead $vxrm
    PseudoVSE32_V_M2 killed %18, %14, 4, 5
    PseudoVSE32_V_M2 killed %21, %14, 4, 5
    PseudoRET

...
