; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfh,+zfh,+f,+d -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK

define void @mv_store_f16(ptr nocapture readonly %in, i32 signext %lane, ptr nocapture %out) {
; CHECK-LABEL: mv_store_f16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e16, m2, ta, ma
; CHECK-NEXT:    vrgather.vx v10, v8, a1
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %1 = tail call <vscale x 8 x half> @llvm.riscv.vle.nxv8f16.i64(<vscale x 8 x half> undef, ptr %in, i64 8)
  %conv.i = sext i32 %lane to i64
  %2 = tail call <vscale x 8 x half> @llvm.riscv.vrgather.vx.nxv8f16.i64(<vscale x 8 x half> undef, <vscale x 8 x half> %1, i64 %conv.i, i64 1)
  %3 = tail call half @llvm.riscv.vfmv.f.s.nxv8f16(<vscale x 8 x half> %2)
  store half %3, ptr %out, align 2
  ret void
}

define void @mv_store_f32(ptr nocapture readonly %in, i32 signext %lane, ptr nocapture %out) {
; CHECK-LABEL: mv_store_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e32, m2, ta, ma
; CHECK-NEXT:    vrgather.vx v10, v8, a1
; CHECK-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %1 = tail call <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float> undef, ptr %in, i64 4)
  %conv.i = sext i32 %lane to i64
  %2 = tail call <vscale x 4 x float> @llvm.riscv.vrgather.vx.nxv4f32.i64(<vscale x 4 x float> undef, <vscale x 4 x float> %1, i64 %conv.i, i64 1)
  %3 = tail call float @llvm.riscv.vfmv.f.s.nxv4f32(<vscale x 4 x float> %2)
  store float %3, ptr %out, align 4
  ret void
}

define void @mv_store_f64(ptr nocapture readonly %in, i32 signext %lane, ptr nocapture %out) {
; CHECK-LABEL: mv_store_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m2, ta, ma
; CHECK-NEXT:    vrgather.vx v10, v8, a1
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vse64.v v10, (a2)
; CHECK-NEXT:    ret
entry:
  %1 = tail call <vscale x 2 x double> @llvm.riscv.vle.nxv2f64.i64(<vscale x 2 x double> undef, ptr %in, i64 2)
  %conv.i = sext i32 %lane to i64
  %2 = tail call <vscale x 2 x double> @llvm.riscv.vrgather.vx.nxv2f64.i64(<vscale x 2 x double> undef, <vscale x 2 x double> %1, i64 %conv.i, i64 1)
  %3 = tail call double @llvm.riscv.vfmv.f.s.nxv2f64(<vscale x 2 x double> %2)
  store double %3, ptr %out, align 8
  ret void
}

declare <vscale x 8 x half> @llvm.riscv.vrgather.vx.nxv8f16.i64(<vscale x 8 x half>, <vscale x 8 x half>, i64, i64)
declare half @llvm.riscv.vfmv.f.s.nxv8f16(<vscale x 8 x half>)
declare <vscale x 8 x half> @llvm.riscv.vle.nxv8f16.i64(<vscale x 8 x half>, ptr nocapture, i64)
declare <vscale x 4 x float> @llvm.riscv.vrgather.vx.nxv4f32.i64(<vscale x 4 x float>, <vscale x 4 x float>, i64, i64)
declare float @llvm.riscv.vfmv.f.s.nxv4f32(<vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.riscv.vle.nxv4f32.i64(<vscale x 4 x float>, ptr nocapture, i64)
declare <vscale x 2 x double> @llvm.riscv.vrgather.vx.nxv2f64.i64(<vscale x 2 x double>, <vscale x 2 x double>, i64, i64)
declare double @llvm.riscv.vfmv.f.s.nxv2f64(<vscale x 2 x double>)
declare <vscale x 2 x double> @llvm.riscv.vle.nxv2f64.i64(<vscale x 2 x double>, ptr nocapture, i64)
