; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+f,+xsfvfnrclipxfqf,+zve64f \
; RUN:   -verify-machineinstrs  | FileCheck %s
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+f,+xsfvfnrclipxfqf,+zve64f \
; RUN:   -verify-machineinstrs  | FileCheck %s

declare <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8>, <vscale x 1 x float>, float, iXLen)

define <vscale x 1 x i8> @sf_vfnrclip_x_f_qf_u8mf8_tu(<vscale x 1 x i8> %passthru, <vscale x 1 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8mf8_tu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8> %passthru, <vscale x 1 x float> %0, float %1, iXLen %vl)
  ret <vscale x 1 x i8> %a
}

define <vscale x 1 x i8> @sf_vfnrclip_x_f_qf_u8mf8_ta(<vscale x 1 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8mf8_ta:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v9, v8, fa5
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8> undef, <vscale x 1 x float> %0, float %1, iXLen %vl)
  ret <vscale x 1 x i8> %a
}

declare <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8>, <vscale x 1 x float>, float, <vscale x 1 x i1>, iXLen, iXLen)

define <vscale x 1 x i8> @test_sf_vfnrclip_x_f_qf_u8mf8_tumu(<vscale x 1 x i1> %m, <vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf8_tumu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, tu, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, <vscale x 1 x i1> %m, iXLen %vl, iXLen 0)
  ret <vscale x 1 x i8> %a
}

define <vscale x 1 x i8> @test_sf_vfnrclip_x_f_qf_u8mf8_tamu(<vscale x 1 x i1> %m, <vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf8_tamu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, <vscale x 1 x i1> %m, iXLen %vl, iXLen 1)
  ret <vscale x 1 x i8> %a
}

define <vscale x 1 x i8> @test_sf_vfnrclip_x_f_qf_u8mf8_tuma(<vscale x 1 x i1> %m, <vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf8_tuma:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, <vscale x 1 x i1> %m, iXLen %vl, iXLen 2)
  ret <vscale x 1 x i8> %a
}

define <vscale x 1 x i8> @test_sf_vfnrclip_x_f_qf_u8mf8_tama(<vscale x 1 x i1> %m, <vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf8_tama:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 1 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv1i8.nxv1f32.iXLen(<vscale x 1 x i8> %maskedoff, <vscale x 1 x float> %0, float %1, <vscale x 1 x i1> %m, iXLen %vl, iXLen 3)
  ret <vscale x 1 x i8> %a
}

declare <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8>, <vscale x 2 x float>, float, iXLen)

define <vscale x 2 x i8> @sf_vfnrclip_x_f_qf_u8mf4_tu(<vscale x 2 x i8> %passthru, <vscale x 2 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8mf4_tu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8> %passthru, <vscale x 2 x float> %0, float %1, iXLen %vl)
  ret <vscale x 2 x i8> %a
}

define <vscale x 2 x i8> @sf_vfnrclip_x_f_qf_u8mf4_ta(<vscale x 2 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8mf4_ta:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v9, v8, fa5
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8> undef, <vscale x 2 x float> %0, float %1, iXLen %vl)
  ret <vscale x 2 x i8> %a
}

declare <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8>, <vscale x 2 x float>, float, <vscale x 2 x i1>, iXLen, iXLen)

define <vscale x 2 x i8> @test_sf_vfnrclip_x_f_qf_u8mf4_tumu(<vscale x 2 x i1> %m, <vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf4_tumu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, tu, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, <vscale x 2 x i1> %m, iXLen %vl, iXLen 0)
  ret <vscale x 2 x i8> %a
}

define <vscale x 2 x i8> @test_sf_vfnrclip_x_f_qf_u8mf4_tamu(<vscale x 2 x i1> %m, <vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf4_tamu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, ta, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, <vscale x 2 x i1> %m, iXLen %vl, iXLen 1)
  ret <vscale x 2 x i8> %a
}

define <vscale x 2 x i8> @test_sf_vfnrclip_x_f_qf_u8mf4_tuma(<vscale x 2 x i1> %m, <vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf4_tuma:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, <vscale x 2 x i1> %m, iXLen %vl, iXLen 2)
  ret <vscale x 2 x i8> %a
}

define <vscale x 2 x i8> @test_sf_vfnrclip_x_f_qf_u8mf4_tama(<vscale x 2 x i1> %m, <vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf4_tama:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v9, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 2 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv2i8.nxv2f32.iXLen(<vscale x 2 x i8> %maskedoff, <vscale x 2 x float> %0, float %1, <vscale x 2 x i1> %m, iXLen %vl, iXLen 3)
  ret <vscale x 2 x i8> %a
}

declare <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8>, <vscale x 4 x float>, float, iXLen)

define <vscale x 4 x i8> @sf_vfnrclip_x_f_qf_u8mf2_tu(<vscale x 4 x i8> %passthru, <vscale x 4 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8mf2_tu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v10, fa5
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8> %passthru, <vscale x 4 x float> %0, float %1, iXLen %vl)
  ret <vscale x 4 x i8> %a
}

define <vscale x 4 x i8> @sf_vfnrclip_x_f_qf_u8mf2_ta(<vscale x 4 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8mf2_ta:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v10, v8, fa5
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8> undef, <vscale x 4 x float> %0, float %1, iXLen %vl)
  ret <vscale x 4 x i8> %a
}

declare <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8>, <vscale x 4 x float>, float, <vscale x 4 x i1>, iXLen, iXLen)

define <vscale x 4 x i8> @test_sf_vfnrclip_x_f_qf_u8mf2_tumu(<vscale x 4 x i1> %m, <vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf2_tumu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, tu, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v10, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, <vscale x 4 x i1> %m, iXLen %vl, iXLen 0)
  ret <vscale x 4 x i8> %a
}

define <vscale x 4 x i8> @test_sf_vfnrclip_x_f_qf_u8mf2_tamu(<vscale x 4 x i1> %m, <vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf2_tamu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, ta, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v10, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, <vscale x 4 x i1> %m, iXLen %vl, iXLen 1)
  ret <vscale x 4 x i8> %a
}

define <vscale x 4 x i8> @test_sf_vfnrclip_x_f_qf_u8mf2_tuma(<vscale x 4 x i1> %m, <vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf2_tuma:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v10, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, <vscale x 4 x i1> %m, iXLen %vl, iXLen 2)
  ret <vscale x 4 x i8> %a
}

define <vscale x 4 x i8> @test_sf_vfnrclip_x_f_qf_u8mf2_tama(<vscale x 4 x i1> %m, <vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8mf2_tama:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v10, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 4 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv4i8.nxv4f32.iXLen(<vscale x 4 x i8> %maskedoff, <vscale x 4 x float> %0, float %1, <vscale x 4 x i1> %m, iXLen %vl, iXLen 3)
  ret <vscale x 4 x i8> %a
}

declare <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8>, <vscale x 8 x float>, float, iXLen)

define <vscale x 8 x i8> @sf_vfnrclip_x_f_qf_u8m1_tu(<vscale x 8 x i8> %passthru, <vscale x 8 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8m1_tu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v12, fa5
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8> %passthru, <vscale x 8 x float> %0, float %1, iXLen %vl)
  ret <vscale x 8 x i8> %a
}

define <vscale x 8 x i8> @sf_vfnrclip_x_f_qf_u8m1_ta(<vscale x 8 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8m1_ta:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v12, v8, fa5
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8> undef, <vscale x 8 x float> %0, float %1, iXLen %vl)
  ret <vscale x 8 x i8> %a
}

declare <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8>, <vscale x 8 x float>, float, <vscale x 8 x i1>, iXLen, iXLen)

define <vscale x 8 x i8> @test_sf_vfnrclip_x_f_qf_u8m1_tumu(<vscale x 8 x i1> %m, <vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m1_tumu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, tu, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v12, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, <vscale x 8 x i1> %m, iXLen %vl, iXLen 0)
  ret <vscale x 8 x i8> %a
}

define <vscale x 8 x i8> @test_sf_vfnrclip_x_f_qf_u8m1_tamu(<vscale x 8 x i1> %m, <vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m1_tamu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, ta, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v12, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, <vscale x 8 x i1> %m, iXLen %vl, iXLen 1)
  ret <vscale x 8 x i8> %a
}

define <vscale x 8 x i8> @test_sf_vfnrclip_x_f_qf_u8m1_tuma(<vscale x 8 x i1> %m, <vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m1_tuma:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v12, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, <vscale x 8 x i1> %m, iXLen %vl, iXLen 2)
  ret <vscale x 8 x i8> %a
}

define <vscale x 8 x i8> @test_sf_vfnrclip_x_f_qf_u8m1_tama(<vscale x 8 x i1> %m, <vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m1_tama:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v12, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 8 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv8i8.nxv8f32.iXLen(<vscale x 8 x i8> %maskedoff, <vscale x 8 x float> %0, float %1, <vscale x 8 x i1> %m, iXLen %vl, iXLen 3)
  ret <vscale x 8 x i8> %a
}

declare <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8>, <vscale x 16 x float>, float, iXLen)

define <vscale x 16 x i8> @sf_vfnrclip_x_f_qf_u8m2_tu(<vscale x 16 x i8> %passthru, <vscale x 16 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8m2_tu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v16, fa5
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8> %passthru, <vscale x 16 x float> %0, float %1, iXLen %vl)
  ret <vscale x 16 x i8> %a
}

define <vscale x 16 x i8> @sf_vfnrclip_x_f_qf_u8m2_ta(<vscale x 16 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: sf_vfnrclip_x_f_qf_u8m2_ta:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v16, v8, fa5
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8> undef, <vscale x 16 x float> %0, float %1, iXLen %vl)
  ret <vscale x 16 x i8> %a
}

declare <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8>, <vscale x 16 x float>, float, <vscale x 16 x i1>, iXLen, iXLen)

define <vscale x 16 x i8> @test_sf_vfnrclip_x_f_qf_u8m2_tumu(<vscale x 16 x i1> %m, <vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m2_tumu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, tu, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v16, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, <vscale x 16 x i1> %m, iXLen %vl, iXLen 0)
  ret <vscale x 16 x i8> %a
}

define <vscale x 16 x i8> @test_sf_vfnrclip_x_f_qf_u8m2_tamu(<vscale x 16 x i1> %m, <vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m2_tamu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, mu
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v16, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, <vscale x 16 x i1> %m, iXLen %vl, iXLen 1)
  ret <vscale x 16 x i8> %a
}

define <vscale x 16 x i8> @test_sf_vfnrclip_x_f_qf_u8m2_tuma(<vscale x 16 x i1> %m, <vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m2_tuma:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, tu, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v16, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, <vscale x 16 x i1> %m, iXLen %vl, iXLen 2)
  ret <vscale x 16 x i8> %a
}

define <vscale x 16 x i8> @test_sf_vfnrclip_x_f_qf_u8m2_tama(<vscale x 16 x i1> %m, <vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, iXLen %vl) {
; CHECK-LABEL: test_sf_vfnrclip_x_f_qf_u8m2_tama:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    sf.vfnrclip.x.f.qf v8, v16, fa5, v0.t
; CHECK-NEXT:    ret
entry:
  %a = tail call <vscale x 16 x i8> @llvm.riscv.sf.vfnrclip.x.mask.nxv16i8.nxv16f32.iXLen(<vscale x 16 x i8> %maskedoff, <vscale x 16 x float> %0, float %1, <vscale x 16 x i1> %m, iXLen %vl, iXLen 3)
  ret <vscale x 16 x i8> %a
}
