; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

define <vscale x 4 x i64> @or_nxv4i64_1(<vscale x 4 x i1> %m, <vscale x 4 x i64> %x, <vscale x 4 x i64> %y, i32 zeroext %evl) {
; CHECK-LABEL: or_nxv4i64_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, tu, ma
; CHECK-NEXT:    vor.vv v12, v12, v8
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i64> %x, <vscale x 4 x i64> zeroinitializer, i32 %evl)
  %merge = or <vscale x 4 x i64> %a, %y
  ret <vscale x 4 x i64> %merge
}

define <vscale x 4 x i64> @or_nxv4i64_2(<vscale x 4 x i1> %m, <vscale x 4 x i64> %x, <vscale x 4 x i64> %y, i32 zeroext %evl) {
; CHECK-LABEL: or_nxv4i64_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, tu, ma
; CHECK-NEXT:    vor.vv v12, v12, v8
; CHECK-NEXT:    vmv4r.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i64> %x, <vscale x 4 x i64> zeroinitializer, i32 %evl)
  %merge = or <vscale x 4 x i64> %y, %a
  ret <vscale x 4 x i64> %merge
}

define <vscale x 4 x i1> @or_nxv4i1_1(<vscale x 4 x i1> %m, <vscale x 4 x i1> %x, <vscale x 4 x i1> %y, i32 zeroext %evl) {
; CHECK-LABEL: or_nxv4i1_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m4, ta, ma
; CHECK-NEXT:    vid.v v12
; CHECK-NEXT:    vmsltu.vx v10, v12, a0
; CHECK-NEXT:    vmand.mm v8, v10, v8
; CHECK-NEXT:    vmor.mm v0, v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.merge.nxv4i1(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i1> %x, <vscale x 4 x i1> zeroinitializer, i32 %evl)
  %merge = or <vscale x 4 x i1> %a, %y
  ret <vscale x 4 x i1> %merge
}

define <vscale x 4 x i1> @or_nxv4i1_2(<vscale x 4 x i1> %m, <vscale x 4 x i1> %x, <vscale x 4 x i1> %y, i32 zeroext %evl) {
; CHECK-LABEL: or_nxv4i1_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e64, m4, ta, ma
; CHECK-NEXT:    vid.v v12
; CHECK-NEXT:    vmsltu.vx v10, v12, a0
; CHECK-NEXT:    vmand.mm v8, v10, v8
; CHECK-NEXT:    vmor.mm v0, v9, v8
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i1> @llvm.vp.merge.nxv4i1(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i1> %x, <vscale x 4 x i1> zeroinitializer, i32 %evl)
  %merge = or <vscale x 4 x i1> %y, %a
  ret <vscale x 4 x i1> %merge
}
