; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+m,+v,+f,+d -verify-machineinstrs < %s | FileCheck --check-prefix=CHECK %s

; FIXME: Make sure we don't end up with back to back vsetvli's in the final reduction block.

define float @blas_dot(i64 %0, ptr nocapture readonly %1, i64 %2, ptr nocapture readonly %3, i64 %4) nounwind {
; CHECK-LABEL: blas_dot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a5, a0, e32, m8, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    beqz a5, .LBB0_3
; CHECK-NEXT:  # %bb.1: # %.preheader
; CHECK-NEXT:    mv a6, a0
; CHECK-NEXT:  .LBB0_2: # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vle32.v v16, (a1)
; CHECK-NEXT:    vle32.v v24, (a3)
; CHECK-NEXT:    mul a7, a5, a2
; CHECK-NEXT:    slli a7, a7, 2
; CHECK-NEXT:    add a1, a1, a7
; CHECK-NEXT:    mul a7, a5, a4
; CHECK-NEXT:    sub a6, a6, a5
; CHECK-NEXT:    slli a7, a7, 2
; CHECK-NEXT:    vsetvli zero, zero, e32, m8, tu, ma
; CHECK-NEXT:    vfmacc.vv v8, v16, v24
; CHECK-NEXT:    vsetvli a5, a6, e32, m8, ta, ma
; CHECK-NEXT:    add a3, a3, a7
; CHECK-NEXT:    bnez a5, .LBB0_2
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    vsetvli a1, a0, e32, m8, ta, ma
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v16, 0
; CHECK-NEXT:    vsetvli zero, a0, e32, m8, tu, ma
; CHECK-NEXT:    vfredusum.vs v16, v8, v16
; CHECK-NEXT:    vfmv.f.s fa0, v16
; CHECK-NEXT:    ret
  %6 = tail call i64 @llvm.riscv.vsetvli(i64 %0, i64 2, i64 3)
  %7 = tail call fast <vscale x 16 x float> @llvm.riscv.vfmv.v.f.nxv16f32.f32(<vscale x 16 x float> undef, float 0.000000e+00, i64 %6)
  %8 = tail call i64 @llvm.riscv.vsetvli(i64 %0, i64 2, i64 3)
  %9 = icmp eq i64 %8, 0
  br i1 %9, label %28, label %10

10:                                               ; preds = %10, %5
  %11 = phi i64 [ %26, %10 ], [ %8, %5 ]
  %12 = phi <vscale x 16 x float> [ %20, %10 ], [ %7, %5 ]
  %13 = phi ptr [ %22, %10 ], [ %1, %5 ]
  %14 = phi ptr [ %24, %10 ], [ %3, %5 ]
  %15 = phi i64 [ %25, %10 ], [ %0, %5 ]
  %17 = tail call fast <vscale x 16 x float> @llvm.riscv.vle.nxv16f32(<vscale x 16 x float> undef, ptr %13, i64 %11)
  %19 = tail call fast <vscale x 16 x float> @llvm.riscv.vle.nxv16f32(<vscale x 16 x float> undef, ptr %14, i64 %11)
  %20 = tail call fast <vscale x 16 x float> @llvm.riscv.vfmacc.nxv16f32.nxv16f32(<vscale x 16 x float> %12, <vscale x 16 x float> %17, <vscale x 16 x float> %19, i64 7, i64 %11, i64 0)
  %21 = mul i64 %11, %2
  %22 = getelementptr inbounds float, ptr %13, i64 %21
  %23 = mul i64 %11, %4
  %24 = getelementptr inbounds float, ptr %14, i64 %23
  %25 = sub i64 %15, %11
  %26 = tail call i64 @llvm.riscv.vsetvli(i64 %25, i64 2, i64 3)
  %27 = icmp eq i64 %26, 0
  br i1 %27, label %28, label %10

28:                                               ; preds = %10, %5
  %29 = phi <vscale x 16 x float> [ %7, %5 ], [ %20, %10 ]
  %30 = tail call i64 @llvm.riscv.vsetvli(i64 %0, i64 2, i64 3)
  %31 = tail call fast <vscale x 2 x float> @llvm.riscv.vfmv.v.f.nxv2f32.f32(<vscale x 2 x float> undef, float 0.000000e+00, i64 %30)
  %32 = tail call fast <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv16f32(<vscale x 2 x float> %31, <vscale x 16 x float> %29, <vscale x 2 x float> %31, i64 7, i64 %30)
  %33 = tail call fast float @llvm.riscv.vfmv.f.s.f32.nxv2f32(<vscale x 2 x float> %32)
  ret float %33
}

declare <vscale x 16 x float> @llvm.riscv.vfmv.v.f.nxv16f32.f32(<vscale x 16 x float>,float, i64)
declare <vscale x 16 x float> @llvm.riscv.vle.nxv16f32(<vscale x 16 x float>, ptr nocapture, i64)
declare <vscale x 16 x float> @llvm.riscv.vfmacc.nxv16f32.nxv16f32(<vscale x 16 x float>, <vscale x 16 x float>, <vscale x 16 x float>, i64, i64, i64)
declare <vscale x 2 x float> @llvm.riscv.vfmv.v.f.nxv2f32.f32(<vscale x 2 x float>, float, i64)
declare <vscale x 2 x float> @llvm.riscv.vfredusum.nxv2f32.nxv16f32(<vscale x 2 x float>, <vscale x 16 x float>, <vscale x 2 x float>, i64, i64)
declare float @llvm.riscv.vfmv.f.s.f32.nxv2f32(<vscale x 2 x float>)
declare i64 @llvm.riscv.vsetvli(i64, i64, i64)
