; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zfh,+experimental-zvfh | FileCheck %s

; Test all supported combinations of lowering of vcast.to.fixed and
; vcast.from.fixed intrinsics. CodeGen isn't great as they are each
; turned into copies through the stack and the results fixed side
; gets scalarized. We expect many of these intrinsics to get paired
; up and eliminated only those that aren't paired will become stack
; copies.

define i64 @test_vcast_to_fixed_64_f16m1(<vscale x 4 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %0 = tail call <4 x half> @llvm.riscv.vcast.to.fixed.v4f16.nxv4f16(<vscale x 4 x half> %x)
  %1 = bitcast <4 x half> %0 to i64
  ret i64 %1
}

declare <4 x half> @llvm.riscv.vcast.to.fixed.v4f16.nxv4f16(<vscale x 4 x half>)

define i128 @test_vcast_to_fixed_64_f16m2(<vscale x 8 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %0 = tail call <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv8f16(<vscale x 8 x half> %x)
  %1 = bitcast <8 x half> %0 to i128
  ret i128 %1
}

declare <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv8f16(<vscale x 8 x half>)

define void @test_vcast_to_fixed_64_f16m4(<16 x half>* noalias nocapture sret(<16 x half>) align 32 %agg.result, <vscale x 16 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 16, e16, m4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
entry:
  %0 = tail call <16 x half> @llvm.riscv.vcast.to.fixed.v16f16.nxv16f16(<vscale x 16 x half> %x)
  store <16 x half> %0, <16 x half>* %agg.result, align 32
  ret void
}

declare <16 x half> @llvm.riscv.vcast.to.fixed.v16f16.nxv16f16(<vscale x 16 x half>)

define void @test_vcast_to_fixed_64_f16m8(<32 x half>* noalias nocapture sret(<32 x half>) align 64 %agg.result, <vscale x 32 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    mv a2, sp
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, ma
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a2)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
entry:
  %0 = tail call <32 x half> @llvm.riscv.vcast.to.fixed.v32f16.nxv32f16(<vscale x 32 x half> %x)
  store <32 x half> %0, <32 x half>* %agg.result, align 64
  ret void
}

declare <32 x half> @llvm.riscv.vcast.to.fixed.v32f16.nxv32f16(<vscale x 32 x half>)

define i64 @test_vcast_to_fixed_64_f16mf2(<vscale x 2 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %0 = tail call <2 x half> @llvm.riscv.vcast.to.fixed.v2f16.nxv2f16(<vscale x 2 x half> %x)
  %1 = bitcast <2 x half> %0 to i32
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <2 x half> @llvm.riscv.vcast.to.fixed.v2f16.nxv2f16(<vscale x 2 x half>)

define <vscale x 4 x half> @test_vcast_from_fixed_64_f16m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <4 x half>
  %1 = tail call <vscale x 4 x half> @llvm.riscv.vcast.from.fixed.nxv4f16.v4f16(<4 x half> %0)
  ret <vscale x 4 x half> %1
}

declare <vscale x 4 x half> @llvm.riscv.vcast.from.fixed.nxv4f16.v4f16(<4 x half>)

define <vscale x 8 x half> @test_vcast_from_fixed_64_f16m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <8 x half>
  %1 = tail call <vscale x 8 x half> @llvm.riscv.vcast.from.fixed.nxv8f16.v8f16(<8 x half> %0)
  ret <vscale x 8 x half> %1
}

declare <vscale x 8 x half> @llvm.riscv.vcast.from.fixed.nxv8f16.v8f16(<8 x half>)

define <vscale x 16 x half> @test_vcast_from_fixed_64_f16m4(<16 x half>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_f16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
entry:
  %x = load <16 x half>, <16 x half>* %0, align 32
  %1 = tail call <vscale x 16 x half> @llvm.riscv.vcast.from.fixed.nxv16f16.v16f16(<16 x half> %x)
  ret <vscale x 16 x half> %1
}

declare <vscale x 16 x half> @llvm.riscv.vcast.from.fixed.nxv16f16.v16f16(<16 x half>)

define <vscale x 32 x half> @test_vcast_from_fixed_64_f16m8(<32 x half>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_f16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
entry:
  %x = load <32 x half>, <32 x half>* %0, align 64
  %1 = tail call <vscale x 32 x half> @llvm.riscv.vcast.from.fixed.nxv32f16.v32f16(<32 x half> %x)
  ret <vscale x 32 x half> %1
}

declare <vscale x 32 x half> @llvm.riscv.vcast.from.fixed.nxv32f16.v32f16(<32 x half>)

define <vscale x 2 x half> @test_vcast_from_fixed_64_f16mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = bitcast i32 %tmp.coerce.0.extract.trunc to <2 x half>
  %1 = tail call <vscale x 2 x half> @llvm.riscv.vcast.from.fixed.nxv2f16.v2f16(<2 x half> %0)
  ret <vscale x 2 x half> %1
}

declare <vscale x 2 x half> @llvm.riscv.vcast.from.fixed.nxv2f16.v2f16(<2 x half>)

define i64 @test_vcast_to_fixed_128_f16mf2(<vscale x 2 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
entry:
  %0 = tail call <4 x half> @llvm.riscv.vcast.to.fixed.v4f16.nxv2f16(<vscale x 2 x half> %x)
  %1 = bitcast <4 x half> %0 to i64
  ret i64 %1
}

declare <4 x half> @llvm.riscv.vcast.to.fixed.v4f16.nxv2f16(<vscale x 2 x half>)

define i128 @test_vcast_to_fixed_128_f16m1(<vscale x 4 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
entry:
  %0 = tail call <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv4f16(<vscale x 4 x half> %x)
  %1 = bitcast <8 x half> %0 to i128
  ret i128 %1
}

declare <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv4f16(<vscale x 4 x half>)

define void @test_vcast_to_fixed_128_f16m2(<16 x half>* noalias nocapture sret(<16 x half>) align 32 %agg.result, <vscale x 8 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = tail call <16 x half> @llvm.riscv.vcast.to.fixed.v16f16.nxv8f16(<vscale x 8 x half> %x)
  store <16 x half> %0, <16 x half>* %agg.result, align 32
  ret void
}

declare <16 x half> @llvm.riscv.vcast.to.fixed.v16f16.nxv8f16(<vscale x 8 x half>)

define void @test_vcast_to_fixed_128_f16m4(<32 x half>* noalias nocapture sret(<32 x half>) align 64 %agg.result, <vscale x 16 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %0 = tail call <32 x half> @llvm.riscv.vcast.to.fixed.v32f16.nxv16f16(<vscale x 16 x half> %x)
  store <32 x half> %0, <32 x half>* %agg.result, align 64
  ret void
}

declare <32 x half> @llvm.riscv.vcast.to.fixed.v32f16.nxv16f16(<vscale x 16 x half>)

define i64 @test_vcast_to_fixed_128_f16mf4(<vscale x 1 x half> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    ret
entry:
  %0 = tail call <2 x half> @llvm.riscv.vcast.to.fixed.v2f16.nxv1f16(<vscale x 1 x half> %x)
  %1 = bitcast <2 x half> %0 to i32
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <2 x half> @llvm.riscv.vcast.to.fixed.v2f16.nxv1f16(<vscale x 1 x half>)

define <vscale x 2 x half> @test_vcast_from_fixed_128_f16mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <4 x half>
  %1 = tail call <vscale x 2 x half> @llvm.riscv.vcast.from.fixed.nxv2f16.v4f16(<4 x half> %0)
  ret <vscale x 2 x half> %1
}

declare <vscale x 2 x half> @llvm.riscv.vcast.from.fixed.nxv2f16.v4f16(<4 x half>)

define <vscale x 4 x half> @test_vcast_from_fixed_128_f16m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <8 x half>
  %1 = tail call <vscale x 4 x half> @llvm.riscv.vcast.from.fixed.nxv4f16.v8f16(<8 x half> %0)
  ret <vscale x 4 x half> %1
}

declare <vscale x 4 x half> @llvm.riscv.vcast.from.fixed.nxv4f16.v8f16(<8 x half>)

define <vscale x 8 x half> @test_vcast_from_fixed_128_f16m2(<16 x half>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_f16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %x = load <16 x half>, <16 x half>* %0, align 32
  %1 = tail call <vscale x 8 x half> @llvm.riscv.vcast.from.fixed.nxv8f16.v16f16(<16 x half> %x)
  ret <vscale x 8 x half> %1
}

declare <vscale x 8 x half> @llvm.riscv.vcast.from.fixed.nxv8f16.v16f16(<16 x half>)

define <vscale x 16 x half> @test_vcast_from_fixed_128_f16m4(<32 x half>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_f16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
entry:
  %x = load <32 x half>, <32 x half>* %0, align 64
  %1 = tail call <vscale x 16 x half> @llvm.riscv.vcast.from.fixed.nxv16f16.v32f16(<32 x half> %x)
  ret <vscale x 16 x half> %1
}

declare <vscale x 16 x half> @llvm.riscv.vcast.from.fixed.nxv16f16.v32f16(<32 x half>)

define <vscale x 1 x half> @test_vcast_from_fixed_128_f16mf4(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = bitcast i32 %tmp.coerce.0.extract.trunc to <2 x half>
  %1 = tail call <vscale x 1 x half> @llvm.riscv.vcast.from.fixed.nxv1f16.v2f16(<2 x half> %0)
  ret <vscale x 1 x half> %1
}

declare <vscale x 1 x half> @llvm.riscv.vcast.from.fixed.nxv1f16.v2f16(<2 x half>)
