; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv32 -target-abi=ilp32d -mattr=+v,+m,+zfh,+zvfh,+f,+d -riscv-v-vector-bits-min=128 | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -target-abi=lp64d -mattr=+v,+m,+zfh,+zvfh,+f,+d -riscv-v-vector-bits-min=128 | FileCheck %s

declare <vscale x 2 x half> @llvm.vp.fdiv.nxv2f16(<vscale x 2 x half>, <vscale x 2 x half>, <vscale x 2 x i1>, i32)
define <vscale x 2 x half> @recip_nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: recip_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI0_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrec7.v v10, v8
; CHECK-NEXT:    vfmv.v.f v11, fa5
; CHECK-NEXT:    vmv1r.v v9, v10
; CHECK-NEXT:    vfnmsub.vv v9, v8, v11, v0.t
; CHECK-NEXT:    vfmadd.vv v9, v10, v10, v0.t
; CHECK-NEXT:    vmv1r.v v8, v9
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = call fast <vscale x 2 x half> @llvm.vp.fdiv.nxv2f16(<vscale x 2 x half> %splat, <vscale x 2 x half>  %a,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x half> %1
}

declare <vscale x 4 x half> @llvm.vp.fdiv.nxv4f16(<vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x i1>, i32)
define <vscale x 4 x half> @recip_nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: recip_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI1_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI1_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrec7.v v10, v8
; CHECK-NEXT:    vfmv.v.f v11, fa5
; CHECK-NEXT:    vmv.v.v v9, v10
; CHECK-NEXT:    vfnmsub.vv v9, v8, v11, v0.t
; CHECK-NEXT:    vfmadd.vv v9, v10, v10, v0.t
; CHECK-NEXT:    vmv.v.v v8, v9
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = call fast <vscale x 4 x half> @llvm.vp.fdiv.nxv4f16(<vscale x 4 x half> %splat, <vscale x 4 x half>  %a,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x half> %1
}

declare <vscale x 8 x half> @llvm.vp.fdiv.nxv8f16(<vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x i1>, i32)
define <vscale x 8 x half> @recip_nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: recip_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI2_0)
; CHECK-NEXT:    flh fa5, %lo(.LCPI2_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v12, v8
; CHECK-NEXT:    vfmv.v.f v14, fa5
; CHECK-NEXT:    vmv.v.v v10, v12
; CHECK-NEXT:    vfnmsub.vv v10, v8, v14, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v12, v12, v0.t
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = call fast <vscale x 8 x half> @llvm.vp.fdiv.nxv8f16(<vscale x 8 x half> %splat, <vscale x 8 x half>  %a,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x half> %1
}

declare <vscale x 2 x double> @llvm.vp.fdiv.nxv2f64(<vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x i1>, i32)
define <vscale x 2 x double> @recip_nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: recip_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI3_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI3_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v10, v8
; CHECK-NEXT:    vfmv.v.f v12, fa5
; CHECK-NEXT:    vmv.v.v v14, v10
; CHECK-NEXT:    vfnmsub.vv v14, v8, v12, v0.t
; CHECK-NEXT:    vfmadd.vv v14, v10, v10, v0.t
; CHECK-NEXT:    vmv.v.v v16, v14
; CHECK-NEXT:    vfnmsub.vv v16, v8, v12, v0.t
; CHECK-NEXT:    vfmadd.vv v16, v14, v14, v0.t
; CHECK-NEXT:    vmv.v.v v10, v16
; CHECK-NEXT:    vfnmsub.vv v10, v8, v12, v0.t
; CHECK-NEXT:    vfmadd.vv v10, v16, v16, v0.t
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = call fast <vscale x 2 x double> @llvm.vp.fdiv.nxv2f64(<vscale x 2 x double> %splat, <vscale x 2 x double>  %a,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x double> %1
}

declare <vscale x 4 x double> @llvm.vp.fdiv.nxv4f64(<vscale x 4 x double>, <vscale x 4 x double>, <vscale x 4 x i1>, i32)
define <vscale x 4 x double> @recip_nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: recip_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a1, %hi(.LCPI4_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI4_0)(a1)
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrec7.v v12, v8
; CHECK-NEXT:    vfmv.v.f v16, fa5
; CHECK-NEXT:    vmv.v.v v20, v12
; CHECK-NEXT:    vfnmsub.vv v20, v8, v16, v0.t
; CHECK-NEXT:    vfmadd.vv v20, v12, v12, v0.t
; CHECK-NEXT:    vmv.v.v v24, v20
; CHECK-NEXT:    vfnmsub.vv v24, v8, v16, v0.t
; CHECK-NEXT:    vfmadd.vv v24, v20, v20, v0.t
; CHECK-NEXT:    vmv.v.v v12, v24
; CHECK-NEXT:    vfnmsub.vv v12, v8, v16, v0.t
; CHECK-NEXT:    vfmadd.vv v12, v24, v24, v0.t
; CHECK-NEXT:    vmv.v.v v8, v12
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = call fast <vscale x 4 x double> @llvm.vp.fdiv.nxv4f64(<vscale x 4 x double> %splat, <vscale x 4 x double>  %a,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x double> %1
}

declare <vscale x 8 x double> @llvm.vp.fdiv.nxv8f64(<vscale x 8 x double>, <vscale x 8 x double>, <vscale x 8 x i1>, i32)
define <vscale x 8 x double> @recip_nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #0 {
; CHECK-LABEL: recip_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 5
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x20, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 32 * vlenb
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmv8r.v v24, v8
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    lui a0, %hi(.LCPI5_0)
; CHECK-NEXT:    fld fa5, %lo(.LCPI5_0)(a0)
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v8, (a0) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    vfmv.v.f v16, fa5
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v16, (a0) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    vmv.v.v v16, v8
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vfnmsub.vv v16, v24, v8, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vfmadd.vv v16, v8, v8, v0.t
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vs8r.v v16, (a0) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v16, (a0) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v16, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vfnmsub.vv v16, v8, v24, v0.t
; CHECK-NEXT:    addi a0, sp, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vfmadd.vv v16, v8, v8, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vs8r.v v16, (a0) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    li a1, 24
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v24, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vfnmsub.vv v16, v8, v24, v0.t
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 4
; CHECK-NEXT:    add a0, sp, a0
; CHECK-NEXT:    addi a0, a0, 16
; CHECK-NEXT:    vl8r.v v8, (a0) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vfmadd.vv v16, v8, v8, v0.t
; CHECK-NEXT:    vmv.v.v v8, v16
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 5
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = call fast <vscale x 8 x double> @llvm.vp.fdiv.nxv8f64(<vscale x 8 x double> %splat, <vscale x 8 x double>  %a,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x double> %1
}

define <vscale x 2 x half> @recip_zero_steps_nxv2f16(<vscale x 2 x half> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: recip_zero_steps_nxv2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x half> %ins, <vscale x 2 x half> poison, <vscale x 2 x i32> zeroinitializer
  %1 = call fast <vscale x 2 x half> @llvm.vp.fdiv.nxv2f16(<vscale x 2 x half> %splat, <vscale x 2 x half>  %a,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x half> %1
}

define <vscale x 4 x half> @recip_zero_steps_nxv4f16(<vscale x 4 x half> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: recip_zero_steps_nxv4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x half> %ins, <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
  %1 = call fast <vscale x 4 x half> @llvm.vp.fdiv.nxv4f16(<vscale x 4 x half> %splat, <vscale x 4 x half>  %a,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x half> %1
}

define <vscale x 8 x half> @recip_zero_steps_nxv8f16(<vscale x 8 x half> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: recip_zero_steps_nxv8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x half> poison, half 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x half> %ins, <vscale x 8 x half> poison, <vscale x 8 x i32> zeroinitializer
  %1 = call fast <vscale x 8 x half> @llvm.vp.fdiv.nxv8f16(<vscale x 8 x half> %splat, <vscale x 8 x half>  %a,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x half> %1
}

define <vscale x 2 x double> @recip_zero_steps_nxv2f64(<vscale x 2 x double> %a, <vscale x 2 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: recip_zero_steps_nxv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 2 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 2 x double> %ins, <vscale x 2 x double> poison, <vscale x 2 x i32> zeroinitializer
  %1 = call fast <vscale x 2 x double> @llvm.vp.fdiv.nxv2f64(<vscale x 2 x double> %splat, <vscale x 2 x double>  %a,  <vscale x 2 x i1> %m, i32 %evl)
  ret <vscale x 2 x double> %1
}

define <vscale x 4 x double> @recip_zero_steps_nxv4f64(<vscale x 4 x double> %a, <vscale x 4 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: recip_zero_steps_nxv4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 4 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 4 x double> %ins, <vscale x 4 x double> poison, <vscale x 4 x i32> zeroinitializer
  %1 = call fast <vscale x 4 x double> @llvm.vp.fdiv.nxv4f64(<vscale x 4 x double> %splat, <vscale x 4 x double>  %a,  <vscale x 4 x i1> %m, i32 %evl)
  ret <vscale x 4 x double> %1
}

define <vscale x 8 x double> @recip_zero_steps_nxv8f64(<vscale x 8 x double> %a, <vscale x 8 x i1> %m, i32 zeroext %evl) #1 {
; CHECK-LABEL: recip_zero_steps_nxv8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vfrec7.v v8, v8
; CHECK-NEXT:    ret
  %ins = insertelement <vscale x 8 x double> poison, double 1.000000e+00, i32 0
  %splat = shufflevector <vscale x 8 x double> %ins, <vscale x 8 x double> poison, <vscale x 8 x i32> zeroinitializer
  %1 = call fast <vscale x 8 x double> @llvm.vp.fdiv.nxv8f64(<vscale x 8 x double> %splat, <vscale x 8 x double>  %a,  <vscale x 8 x i1> %m, i32 %evl)
  ret <vscale x 8 x double> %1
}

attributes #0 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-div" }
attributes #1 = { "unsafe-fp-math"="true" "reciprocal-estimates"="vec-div:0" }
