; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m,+d,+zfh,+zvfh,+v,+zbb -target-abi=ilp32d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV32
; RUN: llc -mtriple=riscv64 -mattr=+m,+d,+zfh,+zvfh,+v,+zbb -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV64

declare half @llvm.vp.reduce.fmul.nxv1f16(half, <vscale x 1 x half>, <vscale x 1 x i1>, i32)
define half @vp_reduce_nxv1f16(half %s, <vscale x 1 x half> %v, i32 signext %evl) {
; RV32-LABEL: vp_reduce_nxv1f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    beqz a0, .LBB0_7
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    beq a0, a1, .LBB0_6
; RV32-NEXT:  # %bb.2:
; RV32-NEXT:    cpop a2, a0
; RV32-NEXT:    beq a2, a1, .LBB0_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    clz a1, a0
; RV32-NEXT:    lui a2, %hi(.LCPI0_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI0_0)(a2)
; RV32-NEXT:    neg a1, a1
; RV32-NEXT:    li a2, 1
; RV32-NEXT:    sll a1, a2, a1
; RV32-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; RV32-NEXT:    vfmv.v.f v9, fa5
; RV32-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; RV32-NEXT:    vmv.v.v v9, v8
; RV32-NEXT:    vmv1r.v v8, v9
; RV32-NEXT:    mv a0, a1
; RV32-NEXT:  .LBB0_4:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:  .LBB0_5: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    srli a0, a0, 1
; RV32-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v9, v8, a0
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    bne a0, a1, .LBB0_5
; RV32-NEXT:  .LBB0_6:
; RV32-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; RV32-NEXT:    vfmv.f.s fa5, v8
; RV32-NEXT:    fmul.h fa0, fa5, fa0
; RV32-NEXT:  .LBB0_7:
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_reduce_nxv1f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    beqz a0, .LBB0_7
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    beq a0, a1, .LBB0_6
; RV64-NEXT:  # %bb.2:
; RV64-NEXT:    cpopw a2, a0
; RV64-NEXT:    beq a2, a1, .LBB0_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    clzw a1, a0
; RV64-NEXT:    li a2, 1
; RV64-NEXT:    lui a3, %hi(.LCPI0_0)
; RV64-NEXT:    slli a0, a0, 32
; RV64-NEXT:    negw a1, a1
; RV64-NEXT:    flh fa5, %lo(.LCPI0_0)(a3)
; RV64-NEXT:    sllw a1, a2, a1
; RV64-NEXT:    slli a2, a1, 32
; RV64-NEXT:    srli a2, a2, 32
; RV64-NEXT:    vsetvli zero, a2, e16, mf4, ta, ma
; RV64-NEXT:    vfmv.v.f v9, fa5
; RV64-NEXT:    srli a0, a0, 32
; RV64-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; RV64-NEXT:    vmv.v.v v9, v8
; RV64-NEXT:    vmv1r.v v8, v9
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:  .LBB0_4:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:  .LBB0_5: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    srliw a0, a0, 1
; RV64-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; RV64-NEXT:    vslidedown.vx v9, v8, a0
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    bne a0, a1, .LBB0_5
; RV64-NEXT:  .LBB0_6:
; RV64-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; RV64-NEXT:    vfmv.f.s fa5, v8
; RV64-NEXT:    fmul.h fa0, fa5, fa0
; RV64-NEXT:  .LBB0_7:
; RV64-NEXT:    ret
entry:
  %splat = insertelement <vscale x 1 x i1> poison, i1 -1, i32 0
  %allones = shufflevector <vscale x 1 x i1> %splat, <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer
  %0 = call reassoc half @llvm.vp.reduce.fmul.nxv1f16(half %s, <vscale x 1 x half> %v, <vscale x 1 x i1> %allones, i32 %evl)
  ret half %0
}

define half @vp_reduce2_nxv1f16(half %s, <vscale x 1 x half> %v, i32 signext %evl) {
; RV32-LABEL: vp_reduce2_nxv1f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    srli a0, a0, 3
; RV32-NEXT:    beqz a0, .LBB1_7
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    beq a0, a1, .LBB1_6
; RV32-NEXT:  # %bb.2:
; RV32-NEXT:    cpop a1, a0
; RV32-NEXT:    li a2, 2
; RV32-NEXT:    bltu a1, a2, .LBB1_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    clz a0, a0
; RV32-NEXT:    lui a1, %hi(.LCPI1_0)
; RV32-NEXT:    flh fa5, %lo(.LCPI1_0)(a1)
; RV32-NEXT:    neg a0, a0
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    sll a0, a1, a0
; RV32-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; RV32-NEXT:    vfmv.v.f v9, fa5
; RV32-NEXT:    vsetvli a1, zero, e16, mf4, tu, ma
; RV32-NEXT:    vmv.v.v v9, v8
; RV32-NEXT:    vmv1r.v v8, v9
; RV32-NEXT:  .LBB1_4:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:  .LBB1_5: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    srli a0, a0, 1
; RV32-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v9, v8, a0
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    bne a0, a1, .LBB1_5
; RV32-NEXT:  .LBB1_6:
; RV32-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; RV32-NEXT:    vfmv.f.s fa5, v8
; RV32-NEXT:    fmul.h fa0, fa5, fa0
; RV32-NEXT:  .LBB1_7:
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_reduce2_nxv1f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    srli a0, a0, 3
; RV64-NEXT:    beqz a0, .LBB1_7
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    beq a0, a1, .LBB1_6
; RV64-NEXT:  # %bb.2:
; RV64-NEXT:    cpopw a2, a0
; RV64-NEXT:    beq a2, a1, .LBB1_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    clzw a0, a0
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    lui a2, %hi(.LCPI1_0)
; RV64-NEXT:    negw a0, a0
; RV64-NEXT:    flh fa5, %lo(.LCPI1_0)(a2)
; RV64-NEXT:    sllw a0, a1, a0
; RV64-NEXT:    slli a1, a0, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; RV64-NEXT:    vfmv.v.f v9, fa5
; RV64-NEXT:    vsetvli a1, zero, e16, mf4, tu, ma
; RV64-NEXT:    vmv.v.v v9, v8
; RV64-NEXT:    vmv1r.v v8, v9
; RV64-NEXT:  .LBB1_4:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:  .LBB1_5: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    srliw a0, a0, 1
; RV64-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; RV64-NEXT:    vslidedown.vx v9, v8, a0
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    bne a0, a1, .LBB1_5
; RV64-NEXT:  .LBB1_6:
; RV64-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; RV64-NEXT:    vfmv.f.s fa5, v8
; RV64-NEXT:    fmul.h fa0, fa5, fa0
; RV64-NEXT:  .LBB1_7:
; RV64-NEXT:    ret
entry:
  %0 = call reassoc half @llvm.vector.reduce.fmul.nxv1f16(half %s, <vscale x 1 x half> %v)
  ret half %0
}

declare float @llvm.vp.reduce.fmul.nxv1f32(float, <vscale x 1 x float>, <vscale x 1 x i1>, i32)
define float @vp_reduce_nxv1f32(float %s, <vscale x 1 x float> %v, i32 signext %evl) {
; RV32-LABEL: vp_reduce_nxv1f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    beqz a0, .LBB2_7
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    beq a0, a1, .LBB2_6
; RV32-NEXT:  # %bb.2:
; RV32-NEXT:    cpop a2, a0
; RV32-NEXT:    beq a2, a1, .LBB2_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    clz a1, a0
; RV32-NEXT:    li a2, 1
; RV32-NEXT:    neg a1, a1
; RV32-NEXT:    sll a1, a2, a1
; RV32-NEXT:    lui a2, 260096
; RV32-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; RV32-NEXT:    vmv.v.x v9, a2
; RV32-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; RV32-NEXT:    vmv.v.v v9, v8
; RV32-NEXT:    vmv1r.v v8, v9
; RV32-NEXT:    mv a0, a1
; RV32-NEXT:  .LBB2_4:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:  .LBB2_5: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    srli a0, a0, 1
; RV32-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; RV32-NEXT:    vslidedown.vx v9, v8, a0
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    bne a0, a1, .LBB2_5
; RV32-NEXT:  .LBB2_6:
; RV32-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; RV32-NEXT:    vfmv.f.s fa5, v8
; RV32-NEXT:    fmul.s fa0, fa5, fa0
; RV32-NEXT:  .LBB2_7:
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_reduce_nxv1f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    beqz a0, .LBB2_7
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    beq a0, a1, .LBB2_6
; RV64-NEXT:  # %bb.2:
; RV64-NEXT:    cpopw a2, a0
; RV64-NEXT:    beq a2, a1, .LBB2_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    clzw a1, a0
; RV64-NEXT:    li a2, 1
; RV64-NEXT:    lui a3, 260096
; RV64-NEXT:    slli a0, a0, 32
; RV64-NEXT:    negw a1, a1
; RV64-NEXT:    sllw a1, a2, a1
; RV64-NEXT:    slli a2, a1, 32
; RV64-NEXT:    srli a2, a2, 32
; RV64-NEXT:    vsetvli zero, a2, e32, mf2, ta, ma
; RV64-NEXT:    vmv.v.x v9, a3
; RV64-NEXT:    srli a0, a0, 32
; RV64-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; RV64-NEXT:    vmv.v.v v9, v8
; RV64-NEXT:    vmv1r.v v8, v9
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:  .LBB2_4:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:  .LBB2_5: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    srliw a0, a0, 1
; RV64-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; RV64-NEXT:    vslidedown.vx v9, v8, a0
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    bne a0, a1, .LBB2_5
; RV64-NEXT:  .LBB2_6:
; RV64-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; RV64-NEXT:    vfmv.f.s fa5, v8
; RV64-NEXT:    fmul.s fa0, fa5, fa0
; RV64-NEXT:  .LBB2_7:
; RV64-NEXT:    ret
entry:
  %splat = insertelement <vscale x 1 x i1> poison, i1 -1, i32 0
  %allones = shufflevector <vscale x 1 x i1> %splat, <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer
  %0 = call reassoc float @llvm.vp.reduce.fmul.nxv1f32(float %s, <vscale x 1 x float> %v, <vscale x 1 x i1> %allones, i32 %evl)
  ret float %0
}

define float @vp_reduce2_nxv1f32(float %s, <vscale x 1 x float> %v, i32 signext %evl) {
; RV32-LABEL: vp_reduce2_nxv1f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    srli a0, a0, 3
; RV32-NEXT:    beqz a0, .LBB3_7
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    beq a0, a1, .LBB3_6
; RV32-NEXT:  # %bb.2:
; RV32-NEXT:    cpop a1, a0
; RV32-NEXT:    li a2, 2
; RV32-NEXT:    bltu a1, a2, .LBB3_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    clz a0, a0
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    neg a0, a0
; RV32-NEXT:    sll a0, a1, a0
; RV32-NEXT:    lui a1, 260096
; RV32-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; RV32-NEXT:    vmv.v.x v9, a1
; RV32-NEXT:    vsetvli a1, zero, e32, mf2, tu, ma
; RV32-NEXT:    vmv.v.v v9, v8
; RV32-NEXT:    vmv1r.v v8, v9
; RV32-NEXT:  .LBB3_4:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:  .LBB3_5: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    srli a0, a0, 1
; RV32-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; RV32-NEXT:    vslidedown.vx v9, v8, a0
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    bne a0, a1, .LBB3_5
; RV32-NEXT:  .LBB3_6:
; RV32-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; RV32-NEXT:    vfmv.f.s fa5, v8
; RV32-NEXT:    fmul.s fa0, fa5, fa0
; RV32-NEXT:  .LBB3_7:
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_reduce2_nxv1f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    srli a0, a0, 3
; RV64-NEXT:    beqz a0, .LBB3_7
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    beq a0, a1, .LBB3_6
; RV64-NEXT:  # %bb.2:
; RV64-NEXT:    cpopw a2, a0
; RV64-NEXT:    beq a2, a1, .LBB3_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    clzw a0, a0
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    negw a0, a0
; RV64-NEXT:    sllw a0, a1, a0
; RV64-NEXT:    slli a1, a0, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    lui a2, 260096
; RV64-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; RV64-NEXT:    vmv.v.x v9, a2
; RV64-NEXT:    vsetvli a1, zero, e32, mf2, tu, ma
; RV64-NEXT:    vmv.v.v v9, v8
; RV64-NEXT:    vmv1r.v v8, v9
; RV64-NEXT:  .LBB3_4:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:  .LBB3_5: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    srliw a0, a0, 1
; RV64-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; RV64-NEXT:    vslidedown.vx v9, v8, a0
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    bne a0, a1, .LBB3_5
; RV64-NEXT:  .LBB3_6:
; RV64-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; RV64-NEXT:    vfmv.f.s fa5, v8
; RV64-NEXT:    fmul.s fa0, fa5, fa0
; RV64-NEXT:  .LBB3_7:
; RV64-NEXT:    ret
entry:
  %0 = call reassoc float @llvm.vector.reduce.fmul.nxv1f32(float %s, <vscale x 1 x float> %v)
  ret float %0
}

declare double @llvm.vp.reduce.fmul.nxv1f64(double, <vscale x 1 x double>, <vscale x 1 x i1>, i32)
define double @vp_reduce_nxv1f64(double %s, <vscale x 1 x double> %v, i32 signext %evl) {
; RV32-LABEL: vp_reduce_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    beqz a0, .LBB4_7
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    beq a0, a1, .LBB4_6
; RV32-NEXT:  # %bb.2:
; RV32-NEXT:    cpop a2, a0
; RV32-NEXT:    beq a2, a1, .LBB4_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    clz a1, a0
; RV32-NEXT:    lui a2, %hi(.LCPI4_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI4_0)(a2)
; RV32-NEXT:    neg a1, a1
; RV32-NEXT:    li a2, 1
; RV32-NEXT:    sll a1, a2, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; RV32-NEXT:    vfmv.v.f v9, fa5
; RV32-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; RV32-NEXT:    vmv.v.v v9, v8
; RV32-NEXT:    vmv1r.v v8, v9
; RV32-NEXT:    mv a0, a1
; RV32-NEXT:  .LBB4_4:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:  .LBB4_5: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    srli a0, a0, 1
; RV32-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; RV32-NEXT:    vslidedown.vx v9, v8, a0
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    bne a0, a1, .LBB4_5
; RV32-NEXT:  .LBB4_6:
; RV32-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RV32-NEXT:    vfmv.f.s fa5, v8
; RV32-NEXT:    fmul.d fa0, fa5, fa0
; RV32-NEXT:  .LBB4_7:
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_reduce_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    beqz a0, .LBB4_7
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    beq a0, a1, .LBB4_6
; RV64-NEXT:  # %bb.2:
; RV64-NEXT:    cpopw a2, a0
; RV64-NEXT:    beq a2, a1, .LBB4_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    clzw a1, a0
; RV64-NEXT:    li a2, 1
; RV64-NEXT:    lui a3, %hi(.LCPI4_0)
; RV64-NEXT:    slli a0, a0, 32
; RV64-NEXT:    negw a1, a1
; RV64-NEXT:    fld fa5, %lo(.LCPI4_0)(a3)
; RV64-NEXT:    sllw a1, a2, a1
; RV64-NEXT:    slli a2, a1, 32
; RV64-NEXT:    srli a2, a2, 32
; RV64-NEXT:    vsetvli zero, a2, e64, m1, ta, ma
; RV64-NEXT:    vfmv.v.f v9, fa5
; RV64-NEXT:    srli a0, a0, 32
; RV64-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; RV64-NEXT:    vmv.v.v v9, v8
; RV64-NEXT:    vmv1r.v v8, v9
; RV64-NEXT:    mv a0, a1
; RV64-NEXT:  .LBB4_4:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:  .LBB4_5: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    srliw a0, a0, 1
; RV64-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; RV64-NEXT:    vslidedown.vx v9, v8, a0
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    bne a0, a1, .LBB4_5
; RV64-NEXT:  .LBB4_6:
; RV64-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RV64-NEXT:    vfmv.f.s fa5, v8
; RV64-NEXT:    fmul.d fa0, fa5, fa0
; RV64-NEXT:  .LBB4_7:
; RV64-NEXT:    ret
entry:
  %splat = insertelement <vscale x 1 x i1> poison, i1 -1, i32 0
  %allones = shufflevector <vscale x 1 x i1> %splat, <vscale x 1 x i1> poison, <vscale x 1 x i32> zeroinitializer
  %0 = call reassoc double @llvm.vp.reduce.fmul.nxv1f64(double %s, <vscale x 1 x double> %v, <vscale x 1 x i1> %allones, i32 %evl)
  ret double %0
}

define double @vp_reduce2_nxv1f64(double %s, <vscale x 1 x double> %v, i32 signext %evl) {
; RV32-LABEL: vp_reduce2_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a0, vlenb
; RV32-NEXT:    srli a0, a0, 3
; RV32-NEXT:    beqz a0, .LBB5_7
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    beq a0, a1, .LBB5_6
; RV32-NEXT:  # %bb.2:
; RV32-NEXT:    cpop a1, a0
; RV32-NEXT:    li a2, 2
; RV32-NEXT:    bltu a1, a2, .LBB5_4
; RV32-NEXT:  # %bb.3:
; RV32-NEXT:    clz a0, a0
; RV32-NEXT:    lui a1, %hi(.LCPI5_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI5_0)(a1)
; RV32-NEXT:    neg a0, a0
; RV32-NEXT:    li a1, 1
; RV32-NEXT:    sll a0, a1, a0
; RV32-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; RV32-NEXT:    vfmv.v.f v9, fa5
; RV32-NEXT:    vsetvli a1, zero, e64, m1, tu, ma
; RV32-NEXT:    vmv.v.v v9, v8
; RV32-NEXT:    vmv1r.v v8, v9
; RV32-NEXT:  .LBB5_4:
; RV32-NEXT:    li a1, 1
; RV32-NEXT:  .LBB5_5: # %loop
; RV32-NEXT:    # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    srli a0, a0, 1
; RV32-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; RV32-NEXT:    vslidedown.vx v9, v8, a0
; RV32-NEXT:    vfmul.vv v8, v8, v9
; RV32-NEXT:    bne a0, a1, .LBB5_5
; RV32-NEXT:  .LBB5_6:
; RV32-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RV32-NEXT:    vfmv.f.s fa5, v8
; RV32-NEXT:    fmul.d fa0, fa5, fa0
; RV32-NEXT:  .LBB5_7:
; RV32-NEXT:    ret
;
; RV64-LABEL: vp_reduce2_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a0, vlenb
; RV64-NEXT:    srli a0, a0, 3
; RV64-NEXT:    beqz a0, .LBB5_7
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    beq a0, a1, .LBB5_6
; RV64-NEXT:  # %bb.2:
; RV64-NEXT:    cpopw a2, a0
; RV64-NEXT:    beq a2, a1, .LBB5_4
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    clzw a0, a0
; RV64-NEXT:    li a1, 1
; RV64-NEXT:    lui a2, %hi(.LCPI5_0)
; RV64-NEXT:    negw a0, a0
; RV64-NEXT:    fld fa5, %lo(.LCPI5_0)(a2)
; RV64-NEXT:    sllw a0, a1, a0
; RV64-NEXT:    slli a1, a0, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; RV64-NEXT:    vfmv.v.f v9, fa5
; RV64-NEXT:    vsetvli a1, zero, e64, m1, tu, ma
; RV64-NEXT:    vmv.v.v v9, v8
; RV64-NEXT:    vmv1r.v v8, v9
; RV64-NEXT:  .LBB5_4:
; RV64-NEXT:    li a1, 1
; RV64-NEXT:  .LBB5_5: # %loop
; RV64-NEXT:    # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    srliw a0, a0, 1
; RV64-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; RV64-NEXT:    vslidedown.vx v9, v8, a0
; RV64-NEXT:    vfmul.vv v8, v8, v9
; RV64-NEXT:    bne a0, a1, .LBB5_5
; RV64-NEXT:  .LBB5_6:
; RV64-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; RV64-NEXT:    vfmv.f.s fa5, v8
; RV64-NEXT:    fmul.d fa0, fa5, fa0
; RV64-NEXT:  .LBB5_7:
; RV64-NEXT:    ret
entry:
  %0 = call reassoc double @llvm.vector.reduce.fmul.nxv1f64(double %s, <vscale x 1 x double> %v)
  ret double %0
}
