; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=false -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=NOALIGN
; RUN: llc -mtriple=riscv64 -mattr=+v,+zfh -mcpu=sifive-x280 -riscv-mem-to-rvv=true -riscv-mem-to-rvv-dlen-align=true -riscv-mem-to-rvv-lmul=8 -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s --check-prefixes=ALIGN

define void @UnKnownSize(ptr nocapture readonly %src, ptr nocapture %dst, i64 signext %n) {
; NOALIGN-LABEL: UnKnownSize:
; NOALIGN:       # %bb.0: # %entry
; NOALIGN-NEXT:  .LBB0_1: # %memcpy-forward-loop
; NOALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; NOALIGN-NEXT:    vsetvli a3, a2, e8, m8, ta, ma
; NOALIGN-NEXT:    vle8.v v8, (a0)
; NOALIGN-NEXT:    sub a2, a2, a3
; NOALIGN-NEXT:    add a0, a0, a3
; NOALIGN-NEXT:    vse8.v v8, (a1)
; NOALIGN-NEXT:    add a1, a1, a3
; NOALIGN-NEXT:    bnez a2, .LBB0_1
; NOALIGN-NEXT:  # %bb.2: # %memcpy-post-loop
; NOALIGN-NEXT:    ret
;
; ALIGN-LABEL: UnKnownSize:
; ALIGN:       # %bb.0: # %entry
; ALIGN-NEXT:    andi a3, a0, 31
; ALIGN-NEXT:    li a4, 32
; ALIGN-NEXT:    sub a4, a4, a3
; ALIGN-NEXT:    minu a3, a4, a2
; ALIGN-NEXT:    vsetvli a3, a3, e8, m8, ta, ma
; ALIGN-NEXT:    vle8.v v8, (a0)
; ALIGN-NEXT:    sub a2, a2, a3
; ALIGN-NEXT:    vse8.v v8, (a1)
; ALIGN-NEXT:    beqz a2, .LBB0_3
; ALIGN-NEXT:  # %bb.1:
; ALIGN-NEXT:    add a0, a0, a3
; ALIGN-NEXT:    add a1, a1, a3
; ALIGN-NEXT:  .LBB0_2: # %memcpy-forward-loop
; ALIGN-NEXT:    # =>This Inner Loop Header: Depth=1
; ALIGN-NEXT:    vsetvli a3, a2, e8, m8, ta, ma
; ALIGN-NEXT:    vle8.v v8, (a0)
; ALIGN-NEXT:    add a0, a0, a3
; ALIGN-NEXT:    sub a2, a2, a3
; ALIGN-NEXT:    vse8.v v8, (a1)
; ALIGN-NEXT:    add a1, a1, a3
; ALIGN-NEXT:    bnez a2, .LBB0_2
; ALIGN-NEXT:  .LBB0_3: # %memcpy-post-loop
; ALIGN-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 %dst, ptr align 1 %src, i64 %n, i1 false)
  ret void
}

declare void @llvm.memcpy.p0i8.p0i8.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)
