; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

define <vscale x 2 x i32> @vpmerge_vpxor_nxv2i32(<vscale x 2 x i1> %arg, <vscale x 2 x i1> %arg1, <vscale x 2 x i32> %arg2, <vscale x 2 x i32> %arg3, i32 zeroext %arg4) {
; CHECK-LABEL: vpmerge_vpxor_nxv2i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    ret
  %tmp = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> %arg, <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 %arg4)
  %tmp5 = tail call <vscale x 2 x i32> @llvm.vp.merge.nxv2i32(<vscale x 2 x i1> %tmp, <vscale x 2 x i32> %arg2, <vscale x 2 x i32> %arg3, i32 %arg4)
  ret <vscale x 2 x i32> %tmp5
}

define <vscale x 2 x float> @vpmerge_vpxor_nxv2f32(<vscale x 2 x i1> %arg, <vscale x 2 x i1> %arg1, <vscale x 2 x float> %arg2, <vscale x 2 x float> %arg3, i32 zeroext %arg4) {
; CHECK-LABEL: vpmerge_vpxor_nxv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vmv1r.v v8, v10
; CHECK-NEXT:    vmerge.vvm v8, v9, v10, v0
; CHECK-NEXT:    ret
  %tmp = tail call <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1> %arg, <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), <vscale x 2 x i1> shufflevector (<vscale x 2 x i1> insertelement (<vscale x 2 x i1> poison, i1 true, i32 0), <vscale x 2 x i1> poison, <vscale x 2 x i32> zeroinitializer), i32 %arg4)
  %tmp5 = tail call <vscale x 2 x float> @llvm.vp.merge.nxv2f32(<vscale x 2 x i1> %tmp, <vscale x 2 x float> %arg2, <vscale x 2 x float> %arg3, i32 %arg4)
  ret <vscale x 2 x float> %tmp5
}

declare <vscale x 2 x i1> @llvm.vp.xor.nxv2i1(<vscale x 2 x i1>, <vscale x 2 x i1>, <vscale x 2 x i1>, i32)
declare <vscale x 2 x i32> @llvm.vp.merge.nxv2i32(<vscale x 2 x i1>, <vscale x 2 x i32>, <vscale x 2 x i32>, i32)
declare <vscale x 2 x float> @llvm.vp.merge.nxv2f32(<vscale x 2 x i1>, <vscale x 2 x float>, <vscale x 2 x float>, i32)
