; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt %s -S -riscv-gather-scatter-lowering -mtriple=riscv64 -mattr=+m,+v | FileCheck %s --check-prefixes=CHECK
; RUN: llc < %s -mtriple=riscv64 -mattr=+m,+v | FileCheck %s --check-prefixes=CHECK-ASM

%struct.foo = type { i32, i32, i32, i32 }

; struct foo {
;   int a, b, c, d;
; };
;
; void struct_gather(int * __restrict  A, struct foo * __restrict B) {
;   for (int i = 0; i < 1024; ++i)
;     A[i] += B[i].b;
; }
define void @struct_gather(i32* noalias nocapture noundef %A, %struct.foo* noalias nocapture noundef readonly %B) {
; CHECK-ASM-LABEL: struct_gather:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a2, 0
; CHECK-ASM-NEXT:    csrr a3, vlenb
; CHECK-ASM-NEXT:    srli a3, a3, 1
; CHECK-ASM-NEXT:    li a4, 1024
; CHECK-ASM-NEXT:    li a5, 16
; CHECK-ASM-NEXT:    j .LBB0_2
; CHECK-ASM-NEXT:  .LBB0_1: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-ASM-NEXT:    slli a7, a2, 4
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    addi a7, a7, 4
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    vlse32.v v8, (a7), a5
; CHECK-ASM-NEXT:    slli a7, a2, 2
; CHECK-ASM-NEXT:    add a7, a0, a7
; CHECK-ASM-NEXT:    vle32.v v10, (a7)
; CHECK-ASM-NEXT:    vadd.vv v8, v10, v8
; CHECK-ASM-NEXT:    add a2, a2, a6
; CHECK-ASM-NEXT:    vse32.v v8, (a7)
; CHECK-ASM-NEXT:    beq a2, a4, .LBB0_4
; CHECK-ASM-NEXT:  .LBB0_2: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a4, a2
; CHECK-ASM-NEXT:    bltu a6, a3, .LBB0_1
; CHECK-ASM-NEXT:  # %bb.3: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-ASM-NEXT:    mv a6, a3
; CHECK-ASM-NEXT:    j .LBB0_1
; CHECK-ASM-NEXT:  .LBB0_4: # %for.cond.cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @struct_gather(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [[STRUCT_FOO:%.*]], ptr [[B:%.*]], i64 [[INDEX]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 1024, [[INDEX]]
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP3]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP2]], i64 16, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP7:%.*]] = bitcast ptr [[TMP6]] to ptr
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[TMP7]], <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP_LOAD]], <vscale x 4 x i32> [[VP_GATHER]], <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast ptr [[TMP6]] to ptr
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[VP_OP]], ptr [[TMP8]], <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP4]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP9]], label [[FOR_COND_CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = getelementptr inbounds %struct.foo, %struct.foo* %B, <vscale x 4 x i64> %vec.ind, i32 1
  %4 = sub i64 1024, %index
  %rvl = call i64 @llvm.umin.i64(i64 %4, i64 %2)
  %5 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %6 = trunc i64 %5 to i32
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %3, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %7 = getelementptr inbounds i32, i32* %A, i64 %index
  %8 = bitcast i32* %7 to <vscale x 4 x i32>*
  %vp.op.load = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* %8, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %vp.op = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %vp.op.load, <vscale x 4 x i32> %vp.gather, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %9 = bitcast i32* %7 to <vscale x 4 x i32>*
  call void @llvm.vp.store.nxv4i32.p0nxv4i32(<vscale x 4 x i32> %vp.op, <vscale x 4 x i32>* %9, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %index.next = add i64 %index, %5
  %.splatinsert9 = insertelement <vscale x 4 x i64> poison, i64 %5, i64 0
  %.splat10 = shufflevector <vscale x 4 x i64> %.splatinsert9, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat10
  %10 = icmp eq i64 %index.next, 1024
  br i1 %10, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body
  ret void
}

define void @struct_gather_masked(i32* noalias nocapture noundef %A, %struct.foo* noalias nocapture noundef readonly %B, <vscale x 4 x i1> %m) {
; CHECK-ASM-LABEL: struct_gather_masked:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a2, 0
; CHECK-ASM-NEXT:    csrr a3, vlenb
; CHECK-ASM-NEXT:    srli a3, a3, 1
; CHECK-ASM-NEXT:    li a4, 1024
; CHECK-ASM-NEXT:    li a5, 16
; CHECK-ASM-NEXT:    j .LBB1_2
; CHECK-ASM-NEXT:  .LBB1_1: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB1_2 Depth=1
; CHECK-ASM-NEXT:    slli a7, a2, 4
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    addi a7, a7, 4
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    vlse32.v v8, (a7), a5, v0.t
; CHECK-ASM-NEXT:    slli a7, a2, 2
; CHECK-ASM-NEXT:    add a7, a0, a7
; CHECK-ASM-NEXT:    vle32.v v10, (a7), v0.t
; CHECK-ASM-NEXT:    vadd.vv v8, v10, v8, v0.t
; CHECK-ASM-NEXT:    add a2, a2, a6
; CHECK-ASM-NEXT:    vse32.v v8, (a7), v0.t
; CHECK-ASM-NEXT:    beq a2, a4, .LBB1_4
; CHECK-ASM-NEXT:  .LBB1_2: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a4, a2
; CHECK-ASM-NEXT:    bltu a6, a3, .LBB1_1
; CHECK-ASM-NEXT:  # %bb.3: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB1_2 Depth=1
; CHECK-ASM-NEXT:    mv a6, a3
; CHECK-ASM-NEXT:    j .LBB1_1
; CHECK-ASM-NEXT:  .LBB1_4: # %for.cond.cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @struct_gather_masked(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr [[STRUCT_FOO:%.*]], ptr [[B:%.*]], i64 [[INDEX]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 1024, [[INDEX]]
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP3]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP2]], i64 16, <vscale x 4 x i1> [[M:%.*]], i32 [[TMP5]])
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP7:%.*]] = bitcast ptr [[TMP6]] to ptr
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[TMP7]], <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_OP_LOAD]], <vscale x 4 x i32> [[VP_GATHER]], <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    [[TMP8:%.*]] = bitcast ptr [[TMP6]] to ptr
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i32.p0(<vscale x 4 x i32> [[VP_OP]], ptr [[TMP8]], <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP4]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP9]], label [[FOR_COND_CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = getelementptr inbounds %struct.foo, %struct.foo* %B, <vscale x 4 x i64> %vec.ind, i32 1
  %4 = sub i64 1024, %index
  %rvl = call i64 @llvm.umin.i64(i64 %4, i64 %2)
  %5 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %6 = trunc i64 %5 to i32
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %3, <vscale x 4 x i1> %m, i32 %6)
  %7 = getelementptr inbounds i32, i32* %A, i64 %index
  %8 = bitcast i32* %7 to <vscale x 4 x i32>*
  %vp.op.load = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* %8, <vscale x 4 x i1> %m, i32 %6)
  %vp.op = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %vp.op.load, <vscale x 4 x i32> %vp.gather, <vscale x 4 x i1> %m, i32 %6)
  %9 = bitcast i32* %7 to <vscale x 4 x i32>*
  call void @llvm.vp.store.nxv4i32.p0nxv4i32(<vscale x 4 x i32> %vp.op, <vscale x 4 x i32>* %9, <vscale x 4 x i1> %m, i32 %6)
  %index.next = add i64 %index, %5
  %.splatinsert9 = insertelement <vscale x 4 x i64> poison, i64 %5, i64 0
  %.splat10 = shufflevector <vscale x 4 x i64> %.splatinsert9, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat10
  %10 = icmp eq i64 %index.next, 1024
  br i1 %10, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body
  ret void
}

; void struct_scatter(int * __restrict  A, struct foo * __restrict B) {
;   for (int i = 0; i < 1024; ++i)
;     B[i].b = A[i];
; }
define void @struct_scatter(i32* noalias nocapture noundef readonly %A, %struct.foo* noalias nocapture noundef writeonly %B) {
; CHECK-ASM-LABEL: struct_scatter:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a2, 0
; CHECK-ASM-NEXT:    csrr a3, vlenb
; CHECK-ASM-NEXT:    srli a3, a3, 1
; CHECK-ASM-NEXT:    li a4, 1024
; CHECK-ASM-NEXT:    li a5, 16
; CHECK-ASM-NEXT:    j .LBB2_2
; CHECK-ASM-NEXT:  .LBB2_1: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB2_2 Depth=1
; CHECK-ASM-NEXT:    slli a7, a2, 2
; CHECK-ASM-NEXT:    add a7, a0, a7
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    vle32.v v8, (a7)
; CHECK-ASM-NEXT:    slli a7, a2, 4
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    addi a7, a7, 4
; CHECK-ASM-NEXT:    add a2, a2, a6
; CHECK-ASM-NEXT:    vsse32.v v8, (a7), a5
; CHECK-ASM-NEXT:    beq a2, a4, .LBB2_4
; CHECK-ASM-NEXT:  .LBB2_2: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a4, a2
; CHECK-ASM-NEXT:    bltu a6, a3, .LBB2_1
; CHECK-ASM-NEXT:  # %bb.3: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB2_2 Depth=1
; CHECK-ASM-NEXT:    mv a6, a3
; CHECK-ASM-NEXT:    j .LBB2_1
; CHECK-ASM-NEXT:  .LBB2_4: # %for.cond.cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @struct_scatter(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 1024, [[INDEX]]
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP3]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast ptr [[TMP2]] to ptr
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[TMP6]], <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [[STRUCT_FOO:%.*]], ptr [[B:%.*]], i64 [[INDEX]], i32 1
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i32.p0.i64(<vscale x 4 x i32> [[VP_OP_LOAD]], ptr [[TMP7]], i64 16, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_COND_CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = getelementptr inbounds i32, i32* %A, i64 %index
  %4 = sub i64 1024, %index
  %rvl = call i64 @llvm.umin.i64(i64 %4, i64 %2)
  %5 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %6 = trunc i64 %5 to i32
  %7 = bitcast i32* %3 to <vscale x 4 x i32>*
  %vp.op.load = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* %7, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %8 = getelementptr inbounds %struct.foo, %struct.foo* %B, <vscale x 4 x i64> %vec.ind, i32 1
  call void @llvm.vp.scatter.nxv4i32.nxv4p0i32(<vscale x 4 x i32> %vp.op.load, <vscale x 4 x i32*> %8, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %index.next = add i64 %index, %5
  %.splatinsert9 = insertelement <vscale x 4 x i64> poison, i64 %5, i64 0
  %.splat10 = shufflevector <vscale x 4 x i64> %.splatinsert9, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat10
  %9 = icmp eq i64 %index.next, 1024
  br i1 %9, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body
  ret void
}

define void @struct_scatter_masked(i32* noalias nocapture noundef readonly %A, %struct.foo* noalias nocapture noundef writeonly %B, <vscale x 4 x i1> %m) {
; CHECK-ASM-LABEL: struct_scatter_masked:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a2, 0
; CHECK-ASM-NEXT:    csrr a3, vlenb
; CHECK-ASM-NEXT:    srli a3, a3, 1
; CHECK-ASM-NEXT:    li a4, 1024
; CHECK-ASM-NEXT:    li a5, 16
; CHECK-ASM-NEXT:    j .LBB3_2
; CHECK-ASM-NEXT:  .LBB3_1: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB3_2 Depth=1
; CHECK-ASM-NEXT:    slli a7, a2, 2
; CHECK-ASM-NEXT:    add a7, a0, a7
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    vle32.v v8, (a7), v0.t
; CHECK-ASM-NEXT:    slli a7, a2, 4
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    addi a7, a7, 4
; CHECK-ASM-NEXT:    add a2, a2, a6
; CHECK-ASM-NEXT:    vsse32.v v8, (a7), a5, v0.t
; CHECK-ASM-NEXT:    beq a2, a4, .LBB3_4
; CHECK-ASM-NEXT:  .LBB3_2: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a4, a2
; CHECK-ASM-NEXT:    bltu a6, a3, .LBB3_1
; CHECK-ASM-NEXT:  # %bb.3: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB3_2 Depth=1
; CHECK-ASM-NEXT:    mv a6, a3
; CHECK-ASM-NEXT:    j .LBB3_1
; CHECK-ASM-NEXT:  .LBB3_4: # %for.cond.cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @struct_scatter_masked(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 1024, [[INDEX]]
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP3]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast ptr [[TMP2]] to ptr
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[TMP6]], <vscale x 4 x i1> [[M:%.*]], i32 [[TMP5]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [[STRUCT_FOO:%.*]], ptr [[B:%.*]], i64 [[INDEX]], i32 1
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i32.p0.i64(<vscale x 4 x i32> [[VP_OP_LOAD]], ptr [[TMP7]], i64 16, <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_COND_CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = getelementptr inbounds i32, i32* %A, i64 %index
  %4 = sub i64 1024, %index
  %rvl = call i64 @llvm.umin.i64(i64 %4, i64 %2)
  %5 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %6 = trunc i64 %5 to i32
  %7 = bitcast i32* %3 to <vscale x 4 x i32>*
  %vp.op.load = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* %7, <vscale x 4 x i1> %m, i32 %6)
  %8 = getelementptr inbounds %struct.foo, %struct.foo* %B, <vscale x 4 x i64> %vec.ind, i32 1
  call void @llvm.vp.scatter.nxv4i32.nxv4p0i32(<vscale x 4 x i32> %vp.op.load, <vscale x 4 x i32*> %8, <vscale x 4 x i1> %m, i32 %6)
  %index.next = add i64 %index, %5
  %.splatinsert9 = insertelement <vscale x 4 x i64> poison, i64 %5, i64 0
  %.splat10 = shufflevector <vscale x 4 x i64> %.splatinsert9, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat10
  %9 = icmp eq i64 %index.next, 1024
  br i1 %9, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body
  ret void
}
; void struct_gather_scatter(int * __restrict  A, struct foo * __restrict B) {
;   for (int i = 0; i < 1024; ++i)
;     B[i].b += A[i];
; }
; FIXME: We fail to CSE the address computations for the strided load and
; strided store.
define void @struct_gather_scatter(i32* noalias nocapture noundef readonly %A, %struct.foo* noalias nocapture noundef %B) {
; CHECK-ASM-LABEL: struct_gather_scatter:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a2, 0
; CHECK-ASM-NEXT:    csrr a3, vlenb
; CHECK-ASM-NEXT:    srli a3, a3, 1
; CHECK-ASM-NEXT:    li a4, 1024
; CHECK-ASM-NEXT:    li a5, 16
; CHECK-ASM-NEXT:    j .LBB4_2
; CHECK-ASM-NEXT:  .LBB4_1: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB4_2 Depth=1
; CHECK-ASM-NEXT:    slli a7, a2, 2
; CHECK-ASM-NEXT:    add a7, a0, a7
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    vle32.v v8, (a7)
; CHECK-ASM-NEXT:    slli a7, a2, 4
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    addi a7, a7, 4
; CHECK-ASM-NEXT:    vlse32.v v10, (a7), a5
; CHECK-ASM-NEXT:    vadd.vv v8, v10, v8
; CHECK-ASM-NEXT:    add a2, a2, a6
; CHECK-ASM-NEXT:    vsse32.v v8, (a7), a5
; CHECK-ASM-NEXT:    beq a2, a4, .LBB4_4
; CHECK-ASM-NEXT:  .LBB4_2: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a4, a2
; CHECK-ASM-NEXT:    bltu a6, a3, .LBB4_1
; CHECK-ASM-NEXT:  # %bb.3: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB4_2 Depth=1
; CHECK-ASM-NEXT:    mv a6, a3
; CHECK-ASM-NEXT:    j .LBB4_1
; CHECK-ASM-NEXT:  .LBB4_4: # %for.cond.cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @struct_gather_scatter(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 1024, [[INDEX]]
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP3]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast ptr [[TMP2]] to ptr
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[TMP6]], <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [[STRUCT_FOO:%.*]], ptr [[B:%.*]], i64 [[INDEX]], i32 1
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP7]], i64 16, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_GATHER]], <vscale x 4 x i32> [[VP_OP_LOAD]], <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i32.p0.i64(<vscale x 4 x i32> [[VP_OP]], ptr [[TMP7]], i64 16, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP5]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_COND_CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = getelementptr inbounds i32, i32* %A, i64 %index
  %4 = sub i64 1024, %index
  %rvl = call i64 @llvm.umin.i64(i64 %4, i64 %2)
  %5 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %6 = trunc i64 %5 to i32
  %7 = bitcast i32* %3 to <vscale x 4 x i32>*
  %vp.op.load = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* %7, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %8 = getelementptr inbounds %struct.foo, %struct.foo* %B, <vscale x 4 x i64> %vec.ind, i32 1
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %8, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %vp.op = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %vp.gather, <vscale x 4 x i32> %vp.op.load, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  call void @llvm.vp.scatter.nxv4i32.nxv4p0i32(<vscale x 4 x i32> %vp.op, <vscale x 4 x i32*> %8, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %6)
  %index.next = add i64 %index, %5
  %.splatinsert9 = insertelement <vscale x 4 x i64> poison, i64 %5, i64 0
  %.splat10 = shufflevector <vscale x 4 x i64> %.splatinsert9, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat10
  %9 = icmp eq i64 %index.next, 1024
  br i1 %9, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body
  ret void
}

define void @struct_gather_scatter_masked(i32* noalias nocapture noundef readonly %A, %struct.foo* noalias nocapture noundef %B, <vscale x 4 x i1> %m) {
; CHECK-ASM-LABEL: struct_gather_scatter_masked:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a2, 0
; CHECK-ASM-NEXT:    csrr a3, vlenb
; CHECK-ASM-NEXT:    srli a3, a3, 1
; CHECK-ASM-NEXT:    li a4, 1024
; CHECK-ASM-NEXT:    li a5, 16
; CHECK-ASM-NEXT:    j .LBB5_2
; CHECK-ASM-NEXT:  .LBB5_1: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB5_2 Depth=1
; CHECK-ASM-NEXT:    slli a7, a2, 2
; CHECK-ASM-NEXT:    add a7, a0, a7
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    vle32.v v8, (a7), v0.t
; CHECK-ASM-NEXT:    slli a7, a2, 4
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    addi a7, a7, 4
; CHECK-ASM-NEXT:    vlse32.v v10, (a7), a5, v0.t
; CHECK-ASM-NEXT:    vadd.vv v8, v10, v8, v0.t
; CHECK-ASM-NEXT:    add a2, a2, a6
; CHECK-ASM-NEXT:    vsse32.v v8, (a7), a5, v0.t
; CHECK-ASM-NEXT:    beq a2, a4, .LBB5_4
; CHECK-ASM-NEXT:  .LBB5_2: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a4, a2
; CHECK-ASM-NEXT:    bltu a6, a3, .LBB5_1
; CHECK-ASM-NEXT:  # %bb.3: # %vector.body
; CHECK-ASM-NEXT:    # in Loop: Header=BB5_2 Depth=1
; CHECK-ASM-NEXT:    mv a6, a3
; CHECK-ASM-NEXT:    j .LBB5_1
; CHECK-ASM-NEXT:  .LBB5_4: # %for.cond.cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @struct_gather_scatter_masked(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = sub i64 1024, [[INDEX]]
; CHECK-NEXT:    [[RVL:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP3]], i64 [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[RVL]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = trunc i64 [[TMP4]] to i32
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast ptr [[TMP2]] to ptr
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0(ptr [[TMP6]], <vscale x 4 x i1> [[M:%.*]], i32 [[TMP5]])
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr [[STRUCT_FOO:%.*]], ptr [[B:%.*]], i64 [[INDEX]], i32 1
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP7]], i64 16, <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    [[VP_OP:%.*]] = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> [[VP_GATHER]], <vscale x 4 x i32> [[VP_OP_LOAD]], <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    call void @llvm.experimental.vp.strided.store.nxv4i32.p0.i64(<vscale x 4 x i32> [[VP_OP]], ptr [[TMP7]], i64 16, <vscale x 4 x i1> [[M]], i32 [[TMP5]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP8]], label [[FOR_COND_CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = getelementptr inbounds i32, i32* %A, i64 %index
  %4 = sub i64 1024, %index
  %rvl = call i64 @llvm.umin.i64(i64 %4, i64 %2)
  %5 = call i64 @llvm.riscv.vsetvli.i64(i64 %rvl, i64 2, i64 1)
  %6 = trunc i64 %5 to i32
  %7 = bitcast i32* %3 to <vscale x 4 x i32>*
  %vp.op.load = call <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* %7, <vscale x 4 x i1> %m, i32 %6)
  %8 = getelementptr inbounds %struct.foo, %struct.foo* %B, <vscale x 4 x i64> %vec.ind, i32 1
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %8, <vscale x 4 x i1> %m, i32 %6)
  %vp.op = call <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32> %vp.gather, <vscale x 4 x i32> %vp.op.load, <vscale x 4 x i1> %m, i32 %6)
  call void @llvm.vp.scatter.nxv4i32.nxv4p0i32(<vscale x 4 x i32> %vp.op, <vscale x 4 x i32*> %8, <vscale x 4 x i1> %m, i32 %6)
  %index.next = add i64 %index, %5
  %.splatinsert9 = insertelement <vscale x 4 x i64> poison, i64 %5, i64 0
  %.splat10 = shufflevector <vscale x 4 x i64> %.splatinsert9, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat10
  %9 = icmp eq i64 %index.next, 1024
  br i1 %9, label %for.cond.cleanup, label %vector.body

for.cond.cleanup:                                 ; preds = %vector.body
  ret void
}

declare <vscale x 4 x i64> @llvm.vp.add.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i1>, i32)
define void @test_vpadd(i64 %N, i32 * noundef %A, <vscale x 4 x i32>* %p) {
; CHECK-ASM-LABEL: test_vpadd:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a3, 0
; CHECK-ASM-NEXT:    li a4, 1
; CHECK-ASM-NEXT:    li a5, 4
; CHECK-ASM-NEXT:  .LBB6_1: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a0, a3
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    slli a7, a4, 2
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    vlse32.v v8, (a7), a5
; CHECK-ASM-NEXT:    vs2r.v v8, (a2)
; CHECK-ASM-NEXT:    add a3, a3, a6
; CHECK-ASM-NEXT:    add a4, a4, a6
; CHECK-ASM-NEXT:    bne a3, a0, .LBB6_1
; CHECK-ASM-NEXT:  # %bb.2: # %cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @test_vpadd(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND_SCALAR:%.*]] = phi i64 [ 1, [[ENTRY]] ], [ [[VEC_IND_NEXT_SCALAR:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 [[N:%.*]], [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[TMP2]], i64 2, i64 1)
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[A:%.*]], i64 [[VEC_IND_SCALAR]]
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP5]], i64 4, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    store volatile <vscale x 4 x i32> [[VP_GATHER]], ptr [[P:%.*]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP3]]
; CHECK-NEXT:    [[VEC_IND_NEXT_SCALAR]] = add i64 [[VEC_IND_SCALAR]], [[TMP3]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[TMP6]], label [[CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = add i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = sub i64 %N, %index
  %4 = call i64 @llvm.riscv.vsetvli.i64(i64 %3, i64 2, i64 1)
  %5 = trunc i64 %4 to i32
  %vp.op = call <vscale x 4 x i64> @llvm.vp.add.nxv4i64(<vscale x 4 x i64> %vec.ind, <vscale x 4 x i64> shufflevector (<vscale x 4 x i64> insertelement (<vscale x 4 x i64> poison, i64 1, i32 0), <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer), <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %5)
  %6 = getelementptr inbounds i32, i32 * %A, <vscale x 4 x i64> %vp.op
  %.splatinsert = insertelement <vscale x 4 x i64> poison, i64 %4, i32 0
  %.splat = shufflevector <vscale x 4 x i64> %.splatinsert, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %6, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %5)
  store volatile <vscale x 4 x i32> %vp.gather, <vscale x 4 x i32>* %p
  %index.next = add i64 %index, %4
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat
  %7 = icmp eq i64 %index.next, %N
  br i1 %7, label %cleanup, label %vector.body

cleanup:
  ret void
}

declare <vscale x 4 x i64> @llvm.vp.mul.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i1>, i32)
define void @test_vpmul(i64 %N, i32 * noundef %A, <vscale x 4 x i32>* %p) {
; CHECK-ASM-LABEL: test_vpmul:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a3, 0
; CHECK-ASM-NEXT:    li a4, 0
; CHECK-ASM-NEXT:    li a5, 8
; CHECK-ASM-NEXT:  .LBB7_1: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a0, a3
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    slli a7, a4, 2
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    vlse32.v v8, (a7), a5
; CHECK-ASM-NEXT:    slli a7, a6, 1
; CHECK-ASM-NEXT:    vs2r.v v8, (a2)
; CHECK-ASM-NEXT:    add a3, a3, a6
; CHECK-ASM-NEXT:    add a4, a4, a7
; CHECK-ASM-NEXT:    bne a3, a0, .LBB7_1
; CHECK-ASM-NEXT:  # %bb.2: # %cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @test_vpmul(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND_SCALAR:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[VEC_IND_NEXT_SCALAR:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 [[N:%.*]], [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[TMP2]], i64 2, i64 1)
; CHECK-NEXT:    [[STEP:%.*]] = mul i64 [[TMP3]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[A:%.*]], i64 [[VEC_IND_SCALAR]]
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP5]], i64 8, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    store volatile <vscale x 4 x i32> [[VP_GATHER]], ptr [[P:%.*]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP3]]
; CHECK-NEXT:    [[VEC_IND_NEXT_SCALAR]] = add i64 [[VEC_IND_SCALAR]], [[STEP]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[TMP6]], label [[CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = mul i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = sub i64 %N, %index
  %4 = call i64 @llvm.riscv.vsetvli.i64(i64 %3, i64 2, i64 1)
  %5 = trunc i64 %4 to i32
  %vp.op = call <vscale x 4 x i64> @llvm.vp.mul.nxv4i64(<vscale x 4 x i64> %vec.ind, <vscale x 4 x i64> shufflevector (<vscale x 4 x i64> insertelement (<vscale x 4 x i64> poison, i64 2, i32 0), <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer), <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %5)
  %6 = getelementptr inbounds i32, i32 * %A, <vscale x 4 x i64> %vp.op
  %.splatinsert = insertelement <vscale x 4 x i64> poison, i64 %4, i32 0
  %.splat = shufflevector <vscale x 4 x i64> %.splatinsert, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %6, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %5)
  store volatile <vscale x 4 x i32> %vp.gather, <vscale x 4 x i32>* %p
  %index.next = add i64 %index, %4
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat
  %7 = icmp eq i64 %index.next, %N
  br i1 %7, label %cleanup, label %vector.body

cleanup:
  ret void
}

declare <vscale x 4 x i64> @llvm.vp.shl.nxv4i64(<vscale x 4 x i64>, <vscale x 4 x i64>, <vscale x 4 x i1>, i32)
define void @test_vpshl(i64 %N, i32 * noundef %A, <vscale x 4 x i32>* %p) {
; CHECK-ASM-LABEL: test_vpshl:
; CHECK-ASM:       # %bb.0: # %entry
; CHECK-ASM-NEXT:    li a3, 0
; CHECK-ASM-NEXT:    li a4, 0
; CHECK-ASM-NEXT:    li a5, 8
; CHECK-ASM-NEXT:  .LBB8_1: # %vector.body
; CHECK-ASM-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-ASM-NEXT:    sub a6, a0, a3
; CHECK-ASM-NEXT:    vsetvli a6, a6, e32, m2, ta, ma
; CHECK-ASM-NEXT:    slli a7, a4, 2
; CHECK-ASM-NEXT:    add a7, a1, a7
; CHECK-ASM-NEXT:    vlse32.v v8, (a7), a5
; CHECK-ASM-NEXT:    slli a7, a6, 1
; CHECK-ASM-NEXT:    vs2r.v v8, (a2)
; CHECK-ASM-NEXT:    add a3, a3, a6
; CHECK-ASM-NEXT:    add a4, a4, a7
; CHECK-ASM-NEXT:    bne a3, a0, .LBB8_1
; CHECK-ASM-NEXT:  # %bb.2: # %cleanup
; CHECK-ASM-NEXT:    ret
; CHECK-LABEL: @test_vpshl(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl i64 [[TMP0]], 2
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_IND_SCALAR:%.*]] = phi i64 [ 0, [[ENTRY]] ], [ [[VEC_IND_NEXT_SCALAR:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = sub i64 [[N:%.*]], [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.riscv.vsetvli.i64(i64 [[TMP2]], i64 2, i64 1)
; CHECK-NEXT:    [[STEP:%.*]] = shl i64 [[TMP3]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = trunc i64 [[TMP3]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[A:%.*]], i64 [[VEC_IND_SCALAR]]
; CHECK-NEXT:    [[VP_GATHER:%.*]] = call <vscale x 4 x i32> @llvm.experimental.vp.strided.load.nxv4i32.p0.i64(ptr [[TMP5]], i64 8, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 [[TMP4]])
; CHECK-NEXT:    store volatile <vscale x 4 x i32> [[VP_GATHER]], ptr [[P:%.*]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP3]]
; CHECK-NEXT:    [[VEC_IND_NEXT_SCALAR]] = add i64 [[VEC_IND_SCALAR]], [[STEP]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[TMP6]], label [[CLEANUP:%.*]], label [[VECTOR_BODY]]
; CHECK:       cleanup:
; CHECK-NEXT:    ret void
entry:
  %0 = call <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
  %1 = call i64 @llvm.vscale.i64()
  %2 = shl i64 %1, 2
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %vec.ind = phi <vscale x 4 x i64> [ %0, %entry ], [ %vec.ind.next, %vector.body ]
  %3 = sub i64 %N, %index
  %4 = call i64 @llvm.riscv.vsetvli.i64(i64 %3, i64 2, i64 1)
  %5 = trunc i64 %4 to i32
  %vp.op = call <vscale x 4 x i64> @llvm.vp.shl.nxv4i64(<vscale x 4 x i64> %vec.ind, <vscale x 4 x i64> shufflevector (<vscale x 4 x i64> insertelement (<vscale x 4 x i64> poison, i64 1, i32 0), <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer), <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %5)
  %6 = getelementptr inbounds i32, i32 * %A, <vscale x 4 x i64> %vp.op
  %.splatinsert = insertelement <vscale x 4 x i64> poison, i64 %4, i32 0
  %.splat = shufflevector <vscale x 4 x i64> %.splatinsert, <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
  %vp.gather = call <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*> %6, <vscale x 4 x i1> shufflevector (<vscale x 4 x i1> insertelement (<vscale x 4 x i1> poison, i1 true, i32 0), <vscale x 4 x i1> poison, <vscale x 4 x i32> zeroinitializer), i32 %5)
  store volatile <vscale x 4 x i32> %vp.gather, <vscale x 4 x i32>* %p
  %index.next = add i64 %index, %4
  %vec.ind.next = add <vscale x 4 x i64> %vec.ind, %.splat
  %7 = icmp eq i64 %index.next, %N
  br i1 %7, label %cleanup, label %vector.body

cleanup:
  ret void
}

declare <vscale x 4 x i64> @llvm.experimental.stepvector.nxv4i64()
declare i64 @llvm.vscale.i64()
declare i64 @llvm.umin.i64(i64, i64)
declare i64 @llvm.riscv.vsetvli.i64(i64, i64 immarg, i64 immarg)
declare <vscale x 4 x i32> @llvm.vp.gather.nxv4i32.nxv4p0i32(<vscale x 4 x i32*>, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i32> @llvm.vp.load.nxv4i32.p0nxv4i32(<vscale x 4 x i32>* nocapture, <vscale x 4 x i1>, i32)
declare <vscale x 4 x i32> @llvm.vp.add.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i1>, i32)
declare void @llvm.vp.store.nxv4i32.p0nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>* nocapture, <vscale x 4 x i1>, i32)
declare void @llvm.vp.scatter.nxv4i32.nxv4p0i32(<vscale x 4 x i32>, <vscale x 4 x i32*>, <vscale x 4 x i1>, i32)
