; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v -riscv-v-vector-bits-min=512 -riscv-mem-to-rvv=true -O3 \
; RUN:   -verify-machineinstrs < %s | FileCheck %s

define void @KnownSize(i8* nocapture readonly %src, i8* nocapture %dst) {
; CHECK-LABEL: KnownSize:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 1337
; CHECK-NEXT:    vsetvli a2, a2, e8, m8, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    add a0, a0, a2
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    li a3, 313
; CHECK-NEXT:    vsetvli zero, a3, e8, m8, ta, ma
; CHECK-NEXT:    add a0, a0, a2
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    add a1, a1, a2
; CHECK-NEXT:    vse8.v v8, (a1)
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 1 %dst, i8* align 1 %src, i64 1337, i1 false)
  ret void
}

declare void @llvm.memcpy.p0i8.p0i8.i64(i8* noalias nocapture writeonly, i8* noalias nocapture readonly, i64, i1 immarg)
