; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m,+v -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+m,+v -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK,RV64

declare <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64>, <vscale x 16 x i64>, metadata, <vscale x 16 x i1>, i32)

define <vscale x 16 x i1> @icmp_eq_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_eq_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmseq.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmseq.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"eq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_eq_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_eq_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmseq.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB1_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB1_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmseq.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_eq_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmseq.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB1_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB1_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmseq.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"eq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_eq_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_eq_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmseq.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB2_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB2_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmseq.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_eq_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmseq.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB2_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB2_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmseq.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"eq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_eq_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_eq_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmseq.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB3_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmseq.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"eq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_eq_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_eq_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmseq.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB4_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB4_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmseq.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"eq", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ne_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ne_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmsne.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB5_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmsne.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ne", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ne_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_ne_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsne.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB6_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB6_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsne.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_ne_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsne.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB6_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB6_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsne.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ne", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ne_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_ne_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsne.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB7_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB7_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsne.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_ne_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsne.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB7_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB7_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsne.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"ne", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ne_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ne_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsne.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB8_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsne.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ne", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ne_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ne_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsne.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB9_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB9_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsne.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"ne", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ugt_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ugt_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmsltu.vv v16, v24, v16, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB10_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB10_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmsltu.vv v0, v8, v24, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ugt_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_ugt_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB11_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB11_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_ugt_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsgtu.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB11_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB11_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsgtu.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ugt_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_ugt_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB12_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB12_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_ugt_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsltu.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB12_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB12_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsltu.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ugt_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ugt_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgtu.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB13_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB13_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ugt_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ugt_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB14_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB14_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"ugt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_uge_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_uge_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vv v16, v24, v16, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB15_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB15_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vv v0, v8, v24, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_uge_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_uge_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsleu.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB16_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB16_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsleu.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_uge_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; RV64-NEXT:    vmv1r.v v7, v0
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv.v.x v24, a0
; RV64-NEXT:    srli a0, a2, 3
; RV64-NEXT:    sub a3, a1, a2
; RV64-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslidedown.vx v0, v0, a0
; RV64-NEXT:    sltu a4, a1, a3
; RV64-NEXT:    addi a4, a4, -1
; RV64-NEXT:    and a3, a4, a3
; RV64-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; RV64-NEXT:    vmsleu.vv v16, v24, v16, v0.t
; RV64-NEXT:    bltu a1, a2, .LBB16_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a2
; RV64-NEXT:  .LBB16_2:
; RV64-NEXT:    vmv1r.v v0, v7
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsleu.vv v0, v24, v8, v0.t
; RV64-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a0
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_uge_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_uge_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsleu.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB17_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB17_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsleu.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_uge_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsleu.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB17_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB17_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsleu.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_uge_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_uge_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgtu.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB18_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB18_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_uge_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_uge_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB19_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB19_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"uge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ult_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ult_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmsltu.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB20_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB20_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmsltu.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ult_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_ult_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB21_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB21_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_ult_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsltu.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB21_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB21_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsltu.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ult_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_ult_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB22_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB22_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsltu.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_ult_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsgtu.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB22_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB22_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsgtu.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ult_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ult_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB23_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB23_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsleu.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_ult_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_ult_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgtu.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB24_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB24_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgtu.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"ult", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sgt_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sgt_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmslt.vv v16, v24, v16, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB25_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB25_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmslt.vv v0, v8, v24, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sgt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sgt_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_sgt_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB26_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB26_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_sgt_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsgt.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB26_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB26_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsgt.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sgt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sgt_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_sgt_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB27_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB27_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_sgt_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmslt.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB27_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB27_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmslt.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"sgt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sgt_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sgt_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB28_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB28_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sgt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sgt_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sgt_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB29_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB29_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"sgt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sge_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sge_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vv v16, v24, v16, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB30_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB30_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vv v0, v8, v24, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sge_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_sge_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB31_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB31_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_sge_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; RV64-NEXT:    vmv1r.v v7, v0
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv.v.x v24, a0
; RV64-NEXT:    srli a0, a2, 3
; RV64-NEXT:    sub a3, a1, a2
; RV64-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslidedown.vx v0, v0, a0
; RV64-NEXT:    sltu a4, a1, a3
; RV64-NEXT:    addi a4, a4, -1
; RV64-NEXT:    and a3, a4, a3
; RV64-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vv v16, v24, v16, v0.t
; RV64-NEXT:    bltu a1, a2, .LBB31_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a2
; RV64-NEXT:  .LBB31_2:
; RV64-NEXT:    vmv1r.v v0, v7
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vv v0, v24, v8, v0.t
; RV64-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a0
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sge_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_sge_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB32_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB32_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_sge_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB32_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB32_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"sge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sge_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sge_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB33_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB33_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sge_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sge_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB34_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB34_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"sge", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_slt_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_slt_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmslt.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB35_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB35_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmslt.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"slt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_slt_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_slt_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB36_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB36_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_slt_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmslt.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB36_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB36_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmslt.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"slt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_slt_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_slt_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB37_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB37_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmslt.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_slt_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsgt.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB37_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB37_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsgt.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"slt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_slt_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_slt_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB38_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB38_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"slt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_slt_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_slt_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB39_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB39_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"slt", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sle_vv_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sle_vv_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    slli a1, a1, 3
; CHECK-NEXT:    sub sp, sp, a1
; CHECK-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x08, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 8 * vlenb
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v7, v0
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a1) # vscale x 64-byte Folded Spill
; CHECK-NEXT:    csrr a1, vlenb
; CHECK-NEXT:    vl8re64.v v8, (a0)
; CHECK-NEXT:    slli a3, a1, 3
; CHECK-NEXT:    sub a4, a2, a1
; CHECK-NEXT:    add a3, a0, a3
; CHECK-NEXT:    sltu a0, a2, a4
; CHECK-NEXT:    addi a0, a0, -1
; CHECK-NEXT:    and a4, a0, a4
; CHECK-NEXT:    srli a0, a1, 3
; CHECK-NEXT:    vslidedown.vx v0, v0, a0
; CHECK-NEXT:    vl8re64.v v24, (a3)
; CHECK-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vv v16, v16, v24, v0.t
; CHECK-NEXT:    bltu a2, a1, .LBB40_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:  .LBB40_2:
; CHECK-NEXT:    vmv1r.v v0, v7
; CHECK-NEXT:    addi a1, sp, 16
; CHECK-NEXT:    vl8r.v v24, (a1) # vscale x 64-byte Folded Reload
; CHECK-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vv v0, v24, v8, v0.t
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    .cfi_def_cfa sp, 16
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sle", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sle_vx_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_sle_vx_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v16, v16, v24, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB41_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB41_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v0, v8, v24, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_sle_vx_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e8, mf4, ta, ma
; RV64-NEXT:    vmv1r.v v24, v0
; RV64-NEXT:    csrr a3, vlenb
; RV64-NEXT:    srli a2, a3, 3
; RV64-NEXT:    sub a4, a1, a3
; RV64-NEXT:    vslidedown.vx v0, v0, a2
; RV64-NEXT:    sltu a5, a1, a4
; RV64-NEXT:    addi a5, a5, -1
; RV64-NEXT:    and a4, a5, a4
; RV64-NEXT:    vsetvli zero, a4, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vx v16, v16, a0, v0.t
; RV64-NEXT:    bltu a1, a3, .LBB41_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a3
; RV64-NEXT:  .LBB41_2:
; RV64-NEXT:    vmv1r.v v0, v24
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vx v0, v8, a0, v0.t
; RV64-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a2
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sle", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sle_vx_swap_nxv16i64(<vscale x 16 x i64> %va, i64 %b, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; RV32-LABEL: icmp_sle_vx_swap_nxv16i64:
; RV32:       # %bb.0:
; RV32-NEXT:    addi sp, sp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; RV32-NEXT:    vmv1r.v v7, v0
; RV32-NEXT:    csrr a3, vlenb
; RV32-NEXT:    sw a0, 8(sp)
; RV32-NEXT:    sw a1, 12(sp)
; RV32-NEXT:    addi a1, sp, 8
; RV32-NEXT:    srli a0, a3, 3
; RV32-NEXT:    vlse64.v v24, (a1), zero
; RV32-NEXT:    sub a1, a2, a3
; RV32-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslidedown.vx v0, v0, a0
; RV32-NEXT:    sltu a4, a2, a1
; RV32-NEXT:    addi a4, a4, -1
; RV32-NEXT:    and a1, a4, a1
; RV32-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v16, v24, v16, v0.t
; RV32-NEXT:    bltu a2, a3, .LBB42_2
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    mv a2, a3
; RV32-NEXT:  .LBB42_2:
; RV32-NEXT:    vmv1r.v v0, v7
; RV32-NEXT:    vsetvli zero, a2, e64, m8, ta, ma
; RV32-NEXT:    vmsle.vv v0, v24, v8, v0.t
; RV32-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV32-NEXT:    vslideup.vx v0, v16, a0
; RV32-NEXT:    addi sp, sp, 16
; RV32-NEXT:    .cfi_def_cfa_offset 0
; RV32-NEXT:    ret
;
; RV64-LABEL: icmp_sle_vx_swap_nxv16i64:
; RV64:       # %bb.0:
; RV64-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; RV64-NEXT:    vmv1r.v v7, v0
; RV64-NEXT:    csrr a2, vlenb
; RV64-NEXT:    vmv.v.x v24, a0
; RV64-NEXT:    srli a0, a2, 3
; RV64-NEXT:    sub a3, a1, a2
; RV64-NEXT:    vsetvli a4, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslidedown.vx v0, v0, a0
; RV64-NEXT:    sltu a4, a1, a3
; RV64-NEXT:    addi a4, a4, -1
; RV64-NEXT:    and a3, a4, a3
; RV64-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vv v16, v24, v16, v0.t
; RV64-NEXT:    bltu a1, a2, .LBB42_2
; RV64-NEXT:  # %bb.1:
; RV64-NEXT:    mv a1, a2
; RV64-NEXT:  .LBB42_2:
; RV64-NEXT:    vmv1r.v v0, v7
; RV64-NEXT:    vsetvli zero, a1, e64, m8, ta, ma
; RV64-NEXT:    vmsle.vv v0, v24, v8, v0.t
; RV64-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; RV64-NEXT:    vslideup.vx v0, v16, a0
; RV64-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 %b, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"sle", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sle_vi_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sle_vi_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v16, v16, 4, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB43_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB43_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsle.vi v0, v8, 4, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i64> %vb, metadata !"sle", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}

define <vscale x 16 x i1> @icmp_sle_vi_swap_nxv16i64(<vscale x 16 x i64> %va, <vscale x 16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: icmp_sle_vi_swap_nxv16i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a1, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmv1r.v v24, v0
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a1, a2, 3
; CHECK-NEXT:    sub a3, a0, a2
; CHECK-NEXT:    vslidedown.vx v0, v0, a1
; CHECK-NEXT:    sltu a4, a0, a3
; CHECK-NEXT:    addi a4, a4, -1
; CHECK-NEXT:    and a3, a4, a3
; CHECK-NEXT:    vsetvli zero, a3, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v16, v16, 3, v0.t
; CHECK-NEXT:    bltu a0, a2, .LBB44_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:  .LBB44_2:
; CHECK-NEXT:    vmv1r.v v0, v24
; CHECK-NEXT:    vsetvli zero, a0, e64, m8, ta, ma
; CHECK-NEXT:    vmsgt.vi v0, v8, 3, v0.t
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vslideup.vx v0, v16, a1
; CHECK-NEXT:    ret
  %elt.head = insertelement <vscale x 16 x i64> poison, i64 4, i32 0
  %vb = shufflevector <vscale x 16 x i64> %elt.head, <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
  %v = call <vscale x 16 x i1> @llvm.vp.icmp.nxv16i64(<vscale x 16 x i64> %vb, <vscale x 16 x i64> %va, metadata !"sle", <vscale x 16 x i1> %m, i32 %evl)
  ret <vscale x 16 x i1> %v
}
