; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v | FileCheck %s

define <vscale x 1 x i8> @intrinsic_vsrl_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsrl_vx_nxv1i8_nxv1i8_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 6
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vsrl.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vsrl.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vsrl_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsrl_vx_nxv1i16_nxv1i16_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vsrl.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vsrl.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vsrl_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsrl_vx_nxv1i32_nxv1i32_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vsrl.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vsrl.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i64> @intrinsic_vsrl_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsrl_vx_nxv1i64_nxv1i64_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    vsrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vsrl.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vsrl.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vsra_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsra_vx_nxv1i8_nxv1i8_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 6
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vsra.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vsra.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vsra_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsra_vx_nxv1i16_nxv1i16_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vsra.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vsra.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vsra_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsra_vx_nxv1i32_nxv1i32_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vsra.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vsra.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i64> @intrinsic_vsra_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsra_vx_nxv1i64_nxv1i64_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    vsra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vsra.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vsra.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vsll_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsll_vx_nxv1i8_nxv1i8_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 6
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vsll.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vsll.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vsll_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsll_vx_nxv1i16_nxv1i16_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vsll.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vsll_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsll_vx_nxv1i32_nxv1i32_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vsll.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i64> @intrinsic_vsll_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vsll_vx_nxv1i64_nxv1i64_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    vsll.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vsll.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vsll.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vssrl_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssrl_vx_nxv1i8_nxv1i8_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 6
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vssrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vssrl.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vssrl.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64, i64)

define <vscale x 1 x i16> @intrinsic_vssrl_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssrl_vx_nxv1i16_nxv1i16_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vssrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vssrl.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vssrl.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64, i64)

define <vscale x 1 x i32> @intrinsic_vssrl_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssrl_vx_nxv1i32_nxv1i32_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vssrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vssrl.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vssrl.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64, i64)

define <vscale x 1 x i64> @intrinsic_vssrl_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssrl_vx_nxv1i64_nxv1i64_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    vssrl.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vssrl.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vssrl.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64, i64)

define <vscale x 1 x i8> @intrinsic_vssra_vx_nxv1i8_nxv1i8_i8(<vscale x 1 x i8> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssra_vx_nxv1i8_nxv1i8_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 6
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vssra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vssra.nxv1i8(<vscale x 1 x i8> undef, <vscale x 1 x i8> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vssra.nxv1i8(<vscale x 1 x i8>, <vscale x 1 x i8>, i64, i64, i64)

define <vscale x 1 x i16> @intrinsic_vssra_vx_nxv1i16_nxv1i16_i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssra_vx_nxv1i16_nxv1i16_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vssra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vssra.nxv1i16(<vscale x 1 x i16> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vssra.nxv1i16(<vscale x 1 x i16>, <vscale x 1 x i16>, i64, i64, i64)

define <vscale x 1 x i32> @intrinsic_vssra_vx_nxv1i32_nxv1i32_i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssra_vx_nxv1i32_nxv1i32_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vssra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vssra.nxv1i32(<vscale x 1 x i32> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vssra.nxv1i32(<vscale x 1 x i32>, <vscale x 1 x i32>, i64, i64, i64)

define <vscale x 1 x i64> @intrinsic_vssra_vx_nxv1i64_nxv1i64_i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vssra_vx_nxv1i64_nxv1i64_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    csrwi vxrm, 3
; CHECK-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; CHECK-NEXT:    vssra.vx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i64> @llvm.riscv.vssra.nxv1i64(<vscale x 1 x i64> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 3, i64 %vl)
  ret <vscale x 1 x i64> %a
}
declare <vscale x 1 x i64> @llvm.riscv.vssra.nxv1i64(<vscale x 1 x i64>, <vscale x 1 x i64>, i64, i64, i64)

define <vscale x 1 x i8> @intrinsic_vnsrl_vx_nxv1i8_nxv1i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsrl_vx_nxv1i8_nxv1i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vnsrl.nxv1i8.nxv1i16(<vscale x 1 x i8> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vnsrl.nxv1i8.nxv1i16(<vscale x 1 x i8>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vnsrl_vx_nxv1i16_nxv1i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsrl_vx_nxv1i16_nxv1i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vnsrl.nxv1i16.nxv1i32(<vscale x 1 x i16> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vnsrl.nxv1i16.nxv1i32(<vscale x 1 x i16>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vnsrl_vx_nxv1i32_nxv1i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsrl_vx_nxv1i32_nxv1i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vnsrl.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vnsrl.nxv1i32.nxv1i64(<vscale x 1 x i32>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i8> @intrinsic_vnsra_vx_nxv1i8_nxv1i16(<vscale x 1 x i16> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsra_vx_nxv1i8_nxv1i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 14
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vnsra.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i8> @llvm.riscv.vnsra.nxv1i8.nxv1i16(<vscale x 1 x i8> undef, <vscale x 1 x i16> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i8> %a
}
declare <vscale x 1 x i8> @llvm.riscv.vnsra.nxv1i8.nxv1i16(<vscale x 1 x i8>, <vscale x 1 x i16>, i64, i64)

define <vscale x 1 x i16> @intrinsic_vnsra_vx_nxv1i16_nxv1i32(<vscale x 1 x i32> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsra_vx_nxv1i16_nxv1i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 30
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vnsra.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i16> @llvm.riscv.vnsra.nxv1i16.nxv1i32(<vscale x 1 x i16> undef, <vscale x 1 x i32> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i16> %a
}
declare <vscale x 1 x i16> @llvm.riscv.vnsra.nxv1i16.nxv1i32(<vscale x 1 x i16>, <vscale x 1 x i32>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vnsra_vx_nxv1i32_nxv1i64(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsra_vx_nxv1i32_nxv1i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a0, a0, 62
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vnsra.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, -2
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
declare <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32>, <vscale x 1 x i64>, i64, i64)

define <vscale x 1 x i32> @intrinsic_vnsra_vx_nxv1i32_nxv1i64_63(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsra_vx_nxv1i32_nxv1i64_63:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vnsra.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, 63
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}

define <vscale x 1 x i32> @intrinsic_vnsra_vx_nxv1i32_nxv1i64_127(<vscale x 1 x i64> %0, i64 %1, i64 %vl) nounwind {
; CHECK-LABEL: intrinsic_vnsra_vx_nxv1i32_nxv1i64_127:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vnsra.wx v8, v8, a0
; CHECK-NEXT:    ret
entry:
  %shamt = and i64 %1, 127
  %a = call <vscale x 1 x i32> @llvm.riscv.vnsra.nxv1i32.nxv1i64(<vscale x 1 x i32> undef, <vscale x 1 x i64> %0, i64 %shamt, i64 %vl)
  ret <vscale x 1 x i32> %a
}
