; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+f,+d -riscv-v-vector-bits-min=128 -verify-machineinstrs | FileCheck %s --check-prefix=VLS

; Test all supported combinations of lowering of vcast.to.fixed and
; vcast.from.fixed intrinsics. CodeGen isn't great as they are each
; turned into copies through the stack and the results fixed side
; gets scalarized. We expect many of these intrinsics to get paired
; up and eliminated only those that aren't paired will become stack
; copies.

define i64 @test_vcast_to_fixed_64_i8m1(<vscale x 8 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> %x)
  %1 = bitcast <8 x i8> %0 to i64
  ret i64 %1
}

declare <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8>)

define i64 @test_vcast_to_fixed_64_i16m1(<vscale x 4 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i16m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv4i16(<vscale x 4 x i16> %x)
  %1 = bitcast <4 x i16> %0 to i64
  ret i64 %1
}

declare <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv4i16(<vscale x 4 x i16>)

define i64 @test_vcast_to_fixed_64_i32m1(<vscale x 2 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv2i32(<vscale x 2 x i32> %x)
  %1 = bitcast <2 x i32> %0 to i64
  ret i64 %1
}

declare <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv2i32(<vscale x 2 x i32>)

define i64 @test_vcast_to_fixed_64_i64m1(<vscale x 1 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <1 x i64> @llvm.riscv.vcast.to.fixed.v1i64.nxv1i64(<vscale x 1 x i64> %x)
  %1 = extractelement <1 x i64> %0, i32 0
  ret i64 %1
}

declare <1 x i64> @llvm.riscv.vcast.to.fixed.v1i64.nxv1i64(<vscale x 1 x i64>)

define i128 @test_vcast_to_fixed_64_i8m2(<vscale x 16 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> %x)
  %1 = bitcast <16 x i8> %0 to i128
  ret i128 %1
}

declare <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8>)

define i128 @test_vcast_to_fixed_64_i16m2(<vscale x 8 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i16m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv8i16(<vscale x 8 x i16> %x)
  %1 = bitcast <8 x i16> %0 to i128
  ret i128 %1
}

declare <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv8i16(<vscale x 8 x i16>)

define i128 @test_vcast_to_fixed_64_i32m2(<vscale x 4 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32> %x)
  %1 = bitcast <4 x i32> %0 to i128
  ret i128 %1
}

declare <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32>)

define i128 @test_vcast_to_fixed_64_i64m2(<vscale x 2 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv2i64(<vscale x 2 x i64> %x)
  %1 = bitcast <2 x i64> %0 to i128
  ret i128 %1
}

declare <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv2i64(<vscale x 2 x i64>)

define void @test_vcast_to_fixed_64_i8m4(<32 x i8>* noalias nocapture sret(<32 x i8>) align 32 %agg.result, <vscale x 32 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    mv a2, sp
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    mv a2, sp
; VLS-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; VLS-NEXT:    vse8.v v8, (a2)
; VLS-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; VLS-NEXT:    vle8.v v8, (a2)
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv32i8(<vscale x 32 x i8> %x)
  store <32 x i8> %0, <32 x i8>* %agg.result, align 32
  ret void
}

declare <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv32i8(<vscale x 32 x i8>)

define void @test_vcast_to_fixed_64_i16m4(<16 x i16>* noalias nocapture sret(<32 x i8>) align 32 %agg.result, <vscale x 16 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 16, e16, m4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a1)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i16m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 16, e16, m4, ta, ma
; VLS-NEXT:    vse16.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; VLS-NEXT:    vle16.v v8, (a1)
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv16i16(<vscale x 16 x i16> %x)
  store <16 x i16> %0, <16 x i16>* %agg.result, align 32
  ret void
}

declare <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv16i16(<vscale x 16 x i16>)

define void @test_vcast_to_fixed_64_i32m4(<8 x i32>* noalias nocapture sret(<8 x i32>) align 32 %agg.result, <vscale x 8 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; VLS-NEXT:    vse32.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a1)
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv8i32(<vscale x 8 x i32> %x)
  store <8 x i32> %0, <8 x i32>* %agg.result, align 32
  ret void
}

declare <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv8i32(<vscale x 8 x i32>)

define void @test_vcast_to_fixed_64_i64m4(<4 x i64>* noalias nocapture sret(<4 x i64>) align 32 %agg.result, <vscale x 4 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; VLS-NEXT:    vse64.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a1)
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv4i64(<vscale x 4 x i64> %x)
  store <4 x i64> %0, <4 x i64>* %agg.result, align 32
  ret void
}

declare <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv4i64(<vscale x 4 x i64>)

define void @test_vcast_to_fixed_64_i8m8(<64 x i8>* noalias nocapture sret(<64 x i8>) align 64 %agg.result, <vscale x 64 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    mv a2, sp
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    vse8.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a2)
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    li a1, 64
; VLS-NEXT:    mv a2, sp
; VLS-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; VLS-NEXT:    vse8.v v8, (a2)
; VLS-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; VLS-NEXT:    vle8.v v8, (a2)
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %0 = tail call <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv64i8(<vscale x 64 x i8> %x)
  store <64 x i8> %0, <64 x i8>* %agg.result, align 64
  ret void
}

declare <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv64i8(<vscale x 64 x i8>)

define void @test_vcast_to_fixed_64_i16m8(<32 x i16>* noalias nocapture sret(<32 x i16>) align 64 %agg.result, <vscale x 32 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    mv a2, sp
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, ma
; CHECK-NEXT:    vse16.v v8, (a2)
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a2)
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i16m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    mv a2, sp
; VLS-NEXT:    vsetvli zero, a1, e16, m8, ta, ma
; VLS-NEXT:    vse16.v v8, (a2)
; VLS-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; VLS-NEXT:    vle16.v v8, (a2)
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %0 = tail call <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv32i16(<vscale x 32 x i16> %x)
  store <32 x i16> %0, <32 x i16>* %agg.result, align 64
  ret void
}

declare <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv32i16(<vscale x 32 x i16>)

define void @test_vcast_to_fixed_64_i32m8(<16 x i32>* noalias nocapture sret(<16 x i32>) align 64 %agg.result, <vscale x 16 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i32m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i32m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; VLS-NEXT:    vse32.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a1)
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv16i32(<vscale x 16 x i32> %x)
  store <16 x i32> %0, <16 x i32>* %agg.result, align 64
  ret void
}

declare <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv16i32(<vscale x 16 x i32>)

define void @test_vcast_to_fixed_64_i64m8(<8 x i64>* noalias nocapture sret(<8 x i64>) align 64 %agg.result, <vscale x 8 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i64m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; VLS-NEXT:    vse64.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a1)
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv8i64(<vscale x 8 x i64> %x)
  store <8 x i64> %0, <8 x i64>* %agg.result, align 64
  ret void
}

declare <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv8i64(<vscale x 8 x i64>)

define i64 @test_vcast_to_fixed_64_i8mf2(<vscale x 4 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv4i8(<vscale x 4 x i8> %x)
  %1 = bitcast <4 x i8> %0 to i32
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv4i8(<vscale x 4 x i8>)

define i64 @test_vcast_to_fixed_64_i16mf2(<vscale x 2 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i16mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv2i16(<vscale x 2 x i16> %x)
  %1 = bitcast <2 x i16> %0 to i32
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv2i16(<vscale x 2 x i16>)

define i64 @test_vcast_to_fixed_64_i32mf2(<vscale x 1 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <1 x i32> @llvm.riscv.vcast.to.fixed.v1i32.nxv1i32(<vscale x 1 x i32> %x)
  %1 = extractelement <1 x i32> %0, i32 0
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <1 x i32> @llvm.riscv.vcast.to.fixed.v1i32.nxv1i32(<vscale x 1 x i32>)

define i64 @test_vcast_to_fixed_64_i8mf4(<vscale x 2 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e8, mf4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 48
; CHECK-NEXT:    srli a0, a0, 48
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e8, mf4, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 48
; VLS-NEXT:    srli a0, a0, 48
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv2i8(<vscale x 2 x i8> %x)
  %1 = bitcast <2 x i8> %0 to i16
  %retval.coerce.0.insert.ext = zext i16 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv2i8(<vscale x 2 x i8>)

define i64 @test_vcast_to_fixed_64_i16mf4(<vscale x 1 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 48
; CHECK-NEXT:    srli a0, a0, 48
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i16mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e16, mf4, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 48
; VLS-NEXT:    srli a0, a0, 48
; VLS-NEXT:    ret
entry:
  %0 = tail call <1 x i16> @llvm.riscv.vcast.to.fixed.v1i16.nxv1i16(<vscale x 1 x i16> %x)
  %1 = extractelement <1 x i16> %0, i32 0
  %retval.coerce.0.insert.ext = zext i16 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <1 x i16> @llvm.riscv.vcast.to.fixed.v1i16.nxv1i16(<vscale x 1 x i16>)

define i64 @test_vcast_to_fixed_64_i8mf8(<vscale x 1 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_i8mf8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    andi a0, a0, 255
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_i8mf8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e8, mf8, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    andi a0, a0, 255
; VLS-NEXT:    ret
entry:
  %0 = tail call <1 x i8> @llvm.riscv.vcast.to.fixed.v1i8.nxv1i8(<vscale x 1 x i8> %x)
  %1 = extractelement <1 x i8> %0, i32 0
  %retval.coerce.0.insert.ext = zext i8 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <1 x i8> @llvm.riscv.vcast.to.fixed.v1i8.nxv1i8(<vscale x 1 x i8>)

define <vscale x 8 x i8> @test_vcast_from_fixed_64_i8m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 8, e8, mf2, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e8, m1, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <8 x i8>
  %1 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> %0)
  ret <vscale x 8 x i8> %1
}

declare <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8>)

define <vscale x 4 x i16> @test_vcast_from_fixed_64_i16m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i16m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e16, m1, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <4 x i16>
  %1 = tail call <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v4i16(<4 x i16> %0)
  ret <vscale x 4 x i16> %1
}

declare <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v4i16(<4 x i16>)

define <vscale x 2 x i32> @test_vcast_from_fixed_64_i32m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <2 x i32>
  %1 = tail call <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v2i32(<2 x i32> %0)
  ret <vscale x 2 x i32> %1
}

declare <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v2i32(<2 x i32>)

define <vscale x 1 x i64> @test_vcast_from_fixed_64_i64m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = insertelement <1 x i64> undef, i64 %x.coerce, i32 0
  %1 = tail call <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v1i64(<1 x i64> %0)
  ret <vscale x 1 x i64> %1
}

declare <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v1i64(<1 x i64>)

define <vscale x 16 x i8> @test_vcast_from_fixed_64_i8m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 16, e8, m1, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 16, e8, m2, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <16 x i8>
  %1 = tail call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> %0)
  ret <vscale x 16 x i8> %1
}

declare <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8>)

define <vscale x 8 x i16> @test_vcast_from_fixed_64_i16m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i16m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e16, m2, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <8 x i16>
  %1 = tail call <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v8i16(<8 x i16> %0)
  ret <vscale x 8 x i16> %1
}

declare <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v8i16(<8 x i16>)

define <vscale x 4 x i32> @test_vcast_from_fixed_64_i32m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <4 x i32>
  %1 = tail call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> %0)
  ret <vscale x 4 x i32> %1
}

declare <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32>)

define <vscale x 2 x i64> @test_vcast_from_fixed_64_i64m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <2 x i64>
  %1 = tail call <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v2i64(<2 x i64> %0)
  ret <vscale x 2 x i64> %1
}

declare <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v2i64(<2 x i64>)

define <vscale x 32 x i8> @test_vcast_from_fixed_64_i8m4(<32 x i8>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %x = load <32 x i8>, <32 x i8>* %0, align 32
  %1 = tail call <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v32i8(<32 x i8> %x)
  ret <vscale x 32 x i8> %1
}

declare <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v32i8(<32 x i8>)

define <vscale x 16 x i16> @test_vcast_from_fixed_64_i16m4(<16 x i16>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i16m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 16, e16, m4, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %x = load <16 x i16>, <16 x i16>* %0, align 32
  %1 = tail call <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v16i16(<16 x i16> %x)
  ret <vscale x 16 x i16> %1
}

declare <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v16i16(<16 x i16>)

define <vscale x 8 x i32> @test_vcast_from_fixed_64_i32m4(<8 x i32>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %x = load <8 x i32>, <8 x i32>* %0, align 32
  %1 = tail call <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v8i32(<8 x i32> %x)
  ret <vscale x 8 x i32> %1
}

declare <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v8i32(<8 x i32>)

define <vscale x 4 x i64> @test_vcast_from_fixed_64_i64m4(<4 x i64>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %x = load <4 x i64>, <4 x i64>* %0, align 32
  %1 = tail call <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v4i64(<4 x i64> %x)
  ret <vscale x 4 x i64> %1
}

declare <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v4i64(<4 x i64>)

define <vscale x 64 x i8> @test_vcast_from_fixed_64_i8m8(<64 x i8>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    li a1, 64
; VLS-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetvli zero, a1, e8, m8, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %x = load <64 x i8>, <64 x i8>* %0, align 64
  %1 = tail call <vscale x 64 x i8> @llvm.riscv.vcast.from.fixed.nxv64i8.v64i8(<64 x i8> %x)
  ret <vscale x 64 x i8> %1
}

declare <vscale x 64 x i8> @llvm.riscv.vcast.from.fixed.nxv64i8.v64i8(<64 x i8>)

define <vscale x 32 x i16> @test_vcast_from_fixed_64_i16m8(<32 x i16>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i16m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i16m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetvli zero, a1, e16, m8, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %x = load <32 x i16>, <32 x i16>* %0, align 64
  %1 = tail call <vscale x 32 x i16> @llvm.riscv.vcast.from.fixed.nxv32i16.v32i16(<32 x i16> %x)
  ret <vscale x 32 x i16> %1
}

declare <vscale x 32 x i16> @llvm.riscv.vcast.from.fixed.nxv32i16.v32i16(<32 x i16>)

define <vscale x 16 x i32> @test_vcast_from_fixed_64_i32m8(<16 x i32>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i32m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i32m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %x = load <16 x i32>, <16 x i32>* %0, align 64
  %1 = tail call <vscale x 16 x i32> @llvm.riscv.vcast.from.fixed.nxv16i32.v16i32(<16 x i32> %x)
  ret <vscale x 16 x i32> %1
}

declare <vscale x 16 x i32> @llvm.riscv.vcast.from.fixed.nxv16i32.v16i32(<16 x i32>)

define <vscale x 8 x i64> @test_vcast_from_fixed_64_i64m8(<8 x i64>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_i64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i64m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %x = load <8 x i64>, <8 x i64>* %0, align 64
  %1 = tail call <vscale x 8 x i64> @llvm.riscv.vcast.from.fixed.nxv8i64.v8i64(<8 x i64> %x)
  ret <vscale x 8 x i64> %1
}

declare <vscale x 8 x i64> @llvm.riscv.vcast.from.fixed.nxv8i64.v8i64(<8 x i64>)

define <vscale x 4 x i8> @test_vcast_from_fixed_64_i8mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e8, mf4, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e8, mf2, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = bitcast i32 %tmp.coerce.0.extract.trunc to <4 x i8>
  %1 = tail call <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v4i8(<4 x i8> %0)
  ret <vscale x 4 x i8> %1
}

declare <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v4i8(<4 x i8>)

define <vscale x 2 x i16> @test_vcast_from_fixed_64_i16mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i16mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e16, mf2, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = bitcast i32 %tmp.coerce.0.extract.trunc to <2 x i16>
  %1 = tail call <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v2i16(<2 x i16> %0)
  ret <vscale x 2 x i16> %1
}

declare <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v2i16(<2 x i16>)

define <vscale x 1 x i32> @test_vcast_from_fixed_64_i32mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = insertelement <1 x i32> undef, i32 %tmp.coerce.0.extract.trunc, i32 0
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v1i32(<1 x i32> %0)
  ret <vscale x 1 x i32> %1
}

declare <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v1i32(<1 x i32>)

define <vscale x 2 x i8> @test_vcast_from_fixed_64_i8mf4(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e8, mf4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e8, mf4, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i16
  %0 = bitcast i16 %tmp.coerce.0.extract.trunc to <2 x i8>
  %1 = tail call <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v2i8(<2 x i8> %0)
  ret <vscale x 2 x i8> %1
}

declare <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v2i8(<2 x i8>)

define <vscale x 1 x i16> @test_vcast_from_fixed_64_i16mf4(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i16mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i16
  %0 = insertelement <1 x i16> undef, i16 %tmp.coerce.0.extract.trunc, i32 0
  %1 = tail call <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v1i16(<1 x i16> %0)
  ret <vscale x 1 x i16> %1
}

declare <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v1i16(<1 x i16>)

define <vscale x 1 x i8> @test_vcast_from_fixed_64_i8mf8(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_i8mf8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_i8mf8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e8, mf8, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i8
  %0 = insertelement <1 x i8> undef, i8 %tmp.coerce.0.extract.trunc, i32 0
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v1i8(<1 x i8> %0)
  ret <vscale x 1 x i8> %1
}

declare <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v1i8(<1 x i8>)

define i64 @test_vcast_to_fixed_64_f32m1(<vscale x 2 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv2f32(<vscale x 2 x float> %x)
  %1 = bitcast <2 x float> %0 to i64
  ret i64 %1
}

declare <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv2f32(<vscale x 2 x float>)

define i64 @test_vcast_to_fixed_64_f64m1(<vscale x 1 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <1 x double> @llvm.riscv.vcast.to.fixed.v1f64.nxv1f64(<vscale x 1 x double> %x)
  %bc = bitcast <1 x double> %0 to <1 x i64>
  %1 = extractelement <1 x i64> %bc, i32 0
  ret i64 %1
}

declare <1 x double> @llvm.riscv.vcast.to.fixed.v1f64.nxv1f64(<vscale x 1 x double>)

define i128 @test_vcast_to_fixed_64_f32m2(<vscale x 4 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> %x)
  %1 = bitcast <4 x float> %0 to i128
  ret i128 %1
}

declare <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float>)

define i128 @test_vcast_to_fixed_64_f64m2(<vscale x 2 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv2f64(<vscale x 2 x double> %x)
  %1 = bitcast <2 x double> %0 to i128
  ret i128 %1
}

declare <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv2f64(<vscale x 2 x double>)

define void @test_vcast_to_fixed_64_f32m4(<8 x float>* noalias nocapture sret(<8 x float>) align 32 %agg.result, <vscale x 8 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; VLS-NEXT:    vse32.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a1)
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x float> @llvm.riscv.vcast.to.fixed.v8f32.nxv8f32(<vscale x 8 x float> %x)
  store <8 x float> %0, <8 x float>* %agg.result, align 32
  ret void
}

declare <8 x float> @llvm.riscv.vcast.to.fixed.v8f32.nxv8f32(<vscale x 8 x float>)

define void @test_vcast_to_fixed_64_f64m4(<4 x double>* noalias nocapture sret(<4 x double>) align 32 %agg.result, <vscale x 4 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; VLS-NEXT:    vse64.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a1)
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x double> @llvm.riscv.vcast.to.fixed.v4f64.nxv4f64(<vscale x 4 x double> %x)
  store <4 x double> %0, <4 x double>* %agg.result, align 32
  ret void
}

declare <4 x double> @llvm.riscv.vcast.to.fixed.v4f64.nxv4f64(<vscale x 4 x double>)

define void @test_vcast_to_fixed_64_f32m8(<16 x float>* noalias nocapture sret(<16 x float>) align 64 %agg.result, <vscale x 16 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f32m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; CHECK-NEXT:    vse32.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a1)
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f32m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; VLS-NEXT:    vse32.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a1)
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x float> @llvm.riscv.vcast.to.fixed.v16f32.nxv16f32(<vscale x 16 x float> %x)
  store <16 x float> %0, <16 x float>* %agg.result, align 64
  ret void
}

declare <16 x float> @llvm.riscv.vcast.to.fixed.v16f32.nxv16f32(<vscale x 16 x float>)

define void @test_vcast_to_fixed_64_f64m8(<8 x double>* noalias nocapture sret(<8 x double>) align 64 %agg.result, <vscale x 8 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    mv a1, sp
; CHECK-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; CHECK-NEXT:    vse64.v v8, (a1)
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a1)
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f64m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    mv a1, sp
; VLS-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; VLS-NEXT:    vse64.v v8, (a1)
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a1)
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x double> @llvm.riscv.vcast.to.fixed.v8f64.nxv8f64(<vscale x 8 x double> %x)
  store <8 x double> %0, <8 x double>* %agg.result, align 64
  ret void
}

declare <8 x double> @llvm.riscv.vcast.to.fixed.v8f64.nxv8f64(<vscale x 8 x double>)

define i64 @test_vcast_to_fixed_64_f32mf2(<vscale x 1 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <1 x float> @llvm.riscv.vcast.to.fixed.v1f32.nxv1f32(<vscale x 1 x float> %x)
  %bc = bitcast <1 x float> %0 to <1 x i32>
  %1 = extractelement <1 x i32> %bc, i32 0
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <1 x float> @llvm.riscv.vcast.to.fixed.v1f32.nxv1f32(<vscale x 1 x float>)

define <vscale x 2 x float> @test_vcast_from_fixed_64_f32m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <2 x float>
  %1 = tail call <vscale x 2 x float> @llvm.riscv.vcast.from.fixed.nxv2f32.v2f32(<2 x float> %0)
  ret <vscale x 2 x float> %1
}

declare <vscale x 2 x float> @llvm.riscv.vcast.from.fixed.nxv2f32.v2f32(<2 x float>)

define <vscale x 1 x double> @test_vcast_from_fixed_64_f64m1(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <1 x double>
  %1 = tail call <vscale x 1 x double> @llvm.riscv.vcast.from.fixed.nxv1f64.v1f64(<1 x double> %0)
  ret <vscale x 1 x double> %1
}

declare <vscale x 1 x double> @llvm.riscv.vcast.from.fixed.nxv1f64.v1f64(<1 x double>)

define <vscale x 4 x float> @test_vcast_from_fixed_64_f32m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <4 x float>
  %1 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> %0)
  ret <vscale x 4 x float> %1
}

declare <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float>)

define <vscale x 2 x double> @test_vcast_from_fixed_64_f64m2(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_64_f64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -16
; VLS-NEXT:    .cfi_def_cfa_offset 16
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 2, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 16
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <2 x double>
  %1 = tail call <vscale x 2 x double> @llvm.riscv.vcast.from.fixed.nxv2f64.v2f64(<2 x double> %0)
  ret <vscale x 2 x double> %1
}

declare <vscale x 2 x double> @llvm.riscv.vcast.from.fixed.nxv2f64.v2f64(<2 x double>)

define <vscale x 8 x float> @test_vcast_from_fixed_64_f32m4(<8 x float>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_f32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %x = load <8 x float>, <8 x float>* %0, align 32
  %1 = tail call <vscale x 8 x float> @llvm.riscv.vcast.from.fixed.nxv8f32.v8f32(<8 x float> %x)
  ret <vscale x 8 x float> %1
}

declare <vscale x 8 x float> @llvm.riscv.vcast.from.fixed.nxv8f32.v8f32(<8 x float>)

define <vscale x 4 x double> @test_vcast_from_fixed_64_f64m4(<4 x double>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_f64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -32
; VLS-NEXT:    .cfi_def_cfa_offset 32
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 4, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 32
; VLS-NEXT:    ret
entry:
  %x = load <4 x double>, <4 x double>* %0, align 32
  %1 = tail call <vscale x 4 x double> @llvm.riscv.vcast.from.fixed.nxv4f64.v4f64(<4 x double> %x)
  ret <vscale x 4 x double> %1
}

declare <vscale x 4 x double> @llvm.riscv.vcast.from.fixed.nxv4f64.v4f64(<4 x double>)

define <vscale x 16 x float> @test_vcast_from_fixed_64_f32m8(<16 x float>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_f32m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f32m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 16, e32, m8, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %x = load <16 x float>, <16 x float>* %0, align 64
  %1 = tail call <vscale x 16 x float> @llvm.riscv.vcast.from.fixed.nxv16f32.v16f32(<16 x float> %x)
  ret <vscale x 16 x float> %1
}

declare <vscale x 16 x float> @llvm.riscv.vcast.from.fixed.nxv16f32.v16f32(<16 x float>)

define <vscale x 8 x double> @test_vcast_from_fixed_64_f64m8(<8 x double>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_64_f64m8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -64
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 64
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_64_f64m8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    addi sp, sp, -64
; VLS-NEXT:    .cfi_def_cfa_offset 64
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    mv a0, sp
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    vsetivli zero, 8, e64, m8, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    addi sp, sp, 64
; VLS-NEXT:    ret
entry:
  %x = load <8 x double>, <8 x double>* %0, align 64
  %1 = tail call <vscale x 8 x double> @llvm.riscv.vcast.from.fixed.nxv8f64.v8f64(<8 x double> %x)
  ret <vscale x 8 x double> %1
}

declare <vscale x 8 x double> @llvm.riscv.vcast.from.fixed.nxv8f64.v8f64(<8 x double>)

define i64 @test_vcast_to_fixed_128_i8mf2(<vscale x 4 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i8mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i8mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv4i8(<vscale x 4 x i8> %x)
  %1 = bitcast <8 x i8> %0 to i64
  ret i64 %1
}

declare <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv4i8(<vscale x 4 x i8>)

define i64 @test_vcast_to_fixed_128_i16mf2(<vscale x 2 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i16mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv2i16(<vscale x 2 x i16> %x)
  %1 = bitcast <4 x i16> %0 to i64
  ret i64 %1
}

declare <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv2i16(<vscale x 2 x i16>)

define i64 @test_vcast_to_fixed_128_i32mf2(<vscale x 1 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv1i32(<vscale x 1 x i32> %x)
  %1 = bitcast <2 x i32> %0 to i64
  ret i64 %1
}

declare <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv1i32(<vscale x 1 x i32>)

define i128 @test_vcast_to_fixed_128_i8m1(<vscale x 8 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i8m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv8i8(<vscale x 8 x i8> %x)
  %1 = bitcast <16 x i8> %0 to i128
  ret i128 %1
}

declare <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv8i8(<vscale x 8 x i8>)

define i128 @test_vcast_to_fixed_128_i16m1(<vscale x 4 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i16m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv4i16(<vscale x 4 x i16> %x)
  %1 = bitcast <8 x i16> %0 to i128
  ret i128 %1
}

declare <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv4i16(<vscale x 4 x i16>)

define i128 @test_vcast_to_fixed_128_i32m1(<vscale x 2 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv2i32(<vscale x 2 x i32> %x)
  %1 = bitcast <4 x i32> %0 to i128
  ret i128 %1
}

declare <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv2i32(<vscale x 2 x i32>)

define i128 @test_vcast_to_fixed_128_i64m1(<vscale x 1 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv1i64(<vscale x 1 x i64> %x)
  %1 = bitcast <2 x i64> %0 to i128
  ret i128 %1
}

declare <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv1i64(<vscale x 1 x i64>)

define void @test_vcast_to_fixed_128_i8m2(<32 x i8>* noalias nocapture sret(<32 x i8>) align 32 %agg.result, <vscale x 16 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i8m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i8m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv16i8(<vscale x 16 x i8> %x)
  store <32 x i8> %0, <32 x i8>* %agg.result, align 32
  ret void
}

declare <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv16i8(<vscale x 16 x i8>)

define void @test_vcast_to_fixed_128_i16m2(<16 x i16>* noalias nocapture sret(<32 x i8>) align 32 %agg.result, <vscale x 8 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i16m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv8i16(<vscale x 8 x i16> %x)
  store <16 x i16> %0, <16 x i16>* %agg.result, align 32
  ret void
}

declare <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv8i16(<vscale x 8 x i16>)

define void @test_vcast_to_fixed_128_i32m2(<8 x i32>* noalias nocapture sret(<8 x i32>) align 32 %agg.result, <vscale x 4 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv4i32(<vscale x 4 x i32> %x)
  store <8 x i32> %0, <8 x i32>* %agg.result, align 32
  ret void
}

declare <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv4i32(<vscale x 4 x i32>)

define void @test_vcast_to_fixed_128_i64m2(<4 x i64>* noalias nocapture sret(<4 x i64>) align 32 %agg.result, <vscale x 2 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv2i64(<vscale x 2 x i64> %x)
  store <4 x i64> %0, <4 x i64>* %agg.result, align 32
  ret void
}

declare <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv2i64(<vscale x 2 x i64>)

define void @test_vcast_to_fixed_128_i8m4(<64 x i8>* noalias nocapture sret(<64 x i8>) align 64 %agg.result, <vscale x 32 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i8m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vse8.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i8m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    li a1, 64
; VLS-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; VLS-NEXT:    vse8.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv32i8(<vscale x 32 x i8> %x)
  store <64 x i8> %0, <64 x i8>* %agg.result, align 64
  ret void
}

declare <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv32i8(<vscale x 32 x i8>)

define void @test_vcast_to_fixed_128_i16m4(<32 x i16>* noalias nocapture sret(<32 x i16>) align 64 %agg.result, <vscale x 16 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vse16.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i16m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; VLS-NEXT:    vse16.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv16i16(<vscale x 16 x i16> %x)
  store <32 x i16> %0, <32 x i16>* %agg.result, align 64
  ret void
}

declare <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv16i16(<vscale x 16 x i16>)

define void @test_vcast_to_fixed_128_i32m4(<16 x i32>* noalias nocapture sret(<16 x i32>) align 64 %agg.result, <vscale x 8 x i32> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv8i32(<vscale x 8 x i32> %x)
  store <16 x i32> %0, <16 x i32>* %agg.result, align 64
  ret void
}

declare <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv8i32(<vscale x 8 x i32>)

define void @test_vcast_to_fixed_128_i64m4(<8 x i64>* noalias nocapture sret(<8 x i64>) align 64 %agg.result, <vscale x 4 x i64> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv4i64(<vscale x 4 x i64> %x)
  store <8 x i64> %0, <8 x i64>* %agg.result, align 64
  ret void
}

declare <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv4i64(<vscale x 4 x i64>)

define i64 @test_vcast_to_fixed_128_i8mf4(<vscale x 2 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i8mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i8mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv2i8(<vscale x 2 x i8> %x)
  %1 = bitcast <4 x i8> %0 to i32
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv2i8(<vscale x 2 x i8>)

define i64 @test_vcast_to_fixed_128_i16mf4(<vscale x 1 x i16> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i16mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv1i16(<vscale x 1 x i16> %x)
  %1 = bitcast <2 x i16> %0 to i32
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv1i16(<vscale x 1 x i16>)

define i64 @test_vcast_to_fixed_128_i8mf8(<vscale x 1 x i8> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_i8mf8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 48
; CHECK-NEXT:    srli a0, a0, 48
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_i8mf8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e16, mf4, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 48
; VLS-NEXT:    srli a0, a0, 48
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv1i8(<vscale x 1 x i8> %x)
  %1 = bitcast <2 x i8> %0 to i16
  %retval.coerce.0.insert.ext = zext i16 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv1i8(<vscale x 1 x i8>)

define <vscale x 4 x i8> @test_vcast_from_fixed_128_i8mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i8mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i8mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <8 x i8>
  %1 = tail call <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v8i8(<8 x i8> %0)
  ret <vscale x 4 x i8> %1
}

declare <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v8i8(<8 x i8>)

define <vscale x 2 x i16> @test_vcast_from_fixed_128_i16mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i16mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i16mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <4 x i16>
  %1 = tail call <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v4i16(<4 x i16> %0)
  ret <vscale x 2 x i16> %1
}

declare <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v4i16(<4 x i16>)

define <vscale x 1 x i32> @test_vcast_from_fixed_128_i32mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <2 x i32>
  %1 = tail call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v2i32(<2 x i32> %0)
  ret <vscale x 1 x i32> %1
}

declare <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v2i32(<2 x i32>)

define <vscale x 8 x i8> @test_vcast_from_fixed_128_i8m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i8m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i8m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <16 x i8>
  %1 = tail call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v16i8(<16 x i8> %0)
  ret <vscale x 8 x i8> %1
}

declare <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v16i8(<16 x i8>)

define <vscale x 4 x i16> @test_vcast_from_fixed_128_i16m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i16m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i16m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <8 x i16>
  %1 = tail call <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v8i16(<8 x i16> %0)
  ret <vscale x 4 x i16> %1
}

declare <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v8i16(<8 x i16>)

define <vscale x 2 x i32> @test_vcast_from_fixed_128_i32m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <4 x i32>
  %1 = tail call <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v4i32(<4 x i32> %0)
  ret <vscale x 2 x i32> %1
}

declare <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v4i32(<4 x i32>)

define <vscale x 1 x i64> @test_vcast_from_fixed_128_i64m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <2 x i64>
  %1 = tail call <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v2i64(<2 x i64> %0)
  ret <vscale x 1 x i64> %1
}

declare <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v2i64(<2 x i64>)

define <vscale x 16 x i8> @test_vcast_from_fixed_128_i8m2(<32 x i8>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i8m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i8m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <32 x i8>, <32 x i8>* %0, align 32
  %1 = tail call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v32i8(<32 x i8> %x)
  ret <vscale x 16 x i8> %1
}

declare <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v32i8(<32 x i8>)

define <vscale x 8 x i16> @test_vcast_from_fixed_128_i16m2(<16 x i16>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i16m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i16m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <16 x i16>, <16 x i16>* %0, align 32
  %1 = tail call <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v16i16(<16 x i16> %x)
  ret <vscale x 8 x i16> %1
}

declare <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v16i16(<16 x i16>)

define <vscale x 4 x i32> @test_vcast_from_fixed_128_i32m2(<8 x i32>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <8 x i32>, <8 x i32>* %0, align 32
  %1 = tail call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v8i32(<8 x i32> %x)
  ret <vscale x 4 x i32> %1
}

declare <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v8i32(<8 x i32>)

define <vscale x 2 x i64> @test_vcast_from_fixed_128_i64m2(<4 x i64>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <4 x i64>, <4 x i64>* %0, align 32
  %1 = tail call <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v4i64(<4 x i64> %x)
  ret <vscale x 2 x i64> %1
}

declare <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v4i64(<4 x i64>)

define <vscale x 32 x i8> @test_vcast_from_fixed_128_i8m4(<64 x i8>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i8m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 64
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vle8.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i8m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    li a1, 64
; VLS-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; VLS-NEXT:    vle8.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <64 x i8>, <64 x i8>* %0, align 64
  %1 = tail call <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v64i8(<64 x i8> %x)
  ret <vscale x 32 x i8> %1
}

declare <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v64i8(<64 x i8>)

define <vscale x 16 x i16> @test_vcast_from_fixed_128_i16m4(<32 x i16>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i16m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vle16.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i16m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    li a1, 32
; VLS-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; VLS-NEXT:    vle16.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <32 x i16>, <32 x i16>* %0, align 64
  %1 = tail call <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v32i16(<32 x i16> %x)
  ret <vscale x 16 x i16> %1
}

declare <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v32i16(<32 x i16>)

define <vscale x 8 x i32> @test_vcast_from_fixed_128_i32m4(<16 x i32>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <16 x i32>, <16 x i32>* %0, align 64
  %1 = tail call <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v16i32(<16 x i32> %x)
  ret <vscale x 8 x i32> %1
}

declare <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v16i32(<16 x i32>)

define <vscale x 4 x i64> @test_vcast_from_fixed_128_i64m4(<8 x i64>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_i64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <8 x i64>, <8 x i64>* %0, align 64
  %1 = tail call <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v8i64(<8 x i64> %x)
  ret <vscale x 4 x i64> %1
}

declare <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v8i64(<8 x i64>)

define <vscale x 2 x i8> @test_vcast_from_fixed_128_i8mf4(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i8mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i8mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = bitcast i32 %tmp.coerce.0.extract.trunc to <4 x i8>
  %1 = tail call <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v4i8(<4 x i8> %0)
  ret <vscale x 2 x i8> %1
}

declare <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v4i8(<4 x i8>)

define <vscale x 1 x i16> @test_vcast_from_fixed_128_i16mf4(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i16mf4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i16mf4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e32, mf2, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i32
  %0 = bitcast i32 %tmp.coerce.0.extract.trunc to <2 x i16>
  %1 = tail call <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v2i16(<2 x i16> %0)
  ret <vscale x 1 x i16> %1
}

declare <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v2i16(<2 x i16>)

define <vscale x 1 x i8> @test_vcast_from_fixed_128_i8mf8(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_i8mf8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_i8mf8:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; VLS-NEXT:    vmv.v.x v8, a0
; VLS-NEXT:    ret
entry:
  %tmp.coerce.0.extract.trunc = trunc i64 %x.coerce to i16
  %0 = bitcast i16 %tmp.coerce.0.extract.trunc to <2 x i8>
  %1 = tail call <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v2i8(<2 x i8> %0)
  ret <vscale x 1 x i8> %1
}

declare <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v2i8(<2 x i8>)

define i64 @test_vcast_to_fixed_128_f32mf2(<vscale x 1 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv1f32(<vscale x 1 x float> %x)
  %1 = bitcast <2 x float> %0 to i64
  ret i64 %1
}

declare <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv1f32(<vscale x 1 x float>)

define i128 @test_vcast_to_fixed_128_f32m1(<vscale x 2 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv2f32(<vscale x 2 x float> %x)
  %1 = bitcast <4 x float> %0 to i128
  ret i128 %1
}

declare <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv2f32(<vscale x 2 x float>)

define i128 @test_vcast_to_fixed_128_f64m1(<vscale x 1 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v8, 1
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vslidedown.vi v9, v8, 1
; VLS-NEXT:    vmv.x.s a1, v9
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
entry:
  %0 = tail call <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv1f64(<vscale x 1 x double> %x)
  %1 = bitcast <2 x double> %0 to i128
  ret i128 %1
}

declare <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv1f64(<vscale x 1 x double>)

define void @test_vcast_to_fixed_128_f32m2(<8 x float>* noalias nocapture sret(<8 x float>) align 32 %agg.result, <vscale x 4 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x float> @llvm.riscv.vcast.to.fixed.v8f32.nxv4f32(<vscale x 4 x float> %x)
  store <8 x float> %0, <8 x float>* %agg.result, align 32
  ret void
}

declare <8 x float> @llvm.riscv.vcast.to.fixed.v8f32.nxv4f32(<vscale x 4 x float>)

define void @test_vcast_to_fixed_128_f64m2(<4 x double>* noalias nocapture sret(<4 x double>) align 32 %agg.result, <vscale x 2 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <4 x double> @llvm.riscv.vcast.to.fixed.v4f64.nxv2f64(<vscale x 2 x double> %x)
  store <4 x double> %0, <4 x double>* %agg.result, align 32
  ret void
}

declare <4 x double> @llvm.riscv.vcast.to.fixed.v4f64.nxv2f64(<vscale x 2 x double>)

define void @test_vcast_to_fixed_128_f32m4(<16 x float>* noalias nocapture sret(<16 x float>) align 64 %agg.result, <vscale x 8 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vse32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <16 x float> @llvm.riscv.vcast.to.fixed.v16f32.nxv8f32(<vscale x 8 x float> %x)
  store <16 x float> %0, <16 x float>* %agg.result, align 64
  ret void
}

declare <16 x float> @llvm.riscv.vcast.to.fixed.v16f32.nxv8f32(<vscale x 8 x float>)

define void @test_vcast_to_fixed_128_f64m4(<8 x double>* noalias nocapture sret(<8 x double>) align 64 %agg.result, <vscale x 4 x double> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vse64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vse64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %0 = tail call <8 x double> @llvm.riscv.vcast.to.fixed.v8f64.nxv4f64(<vscale x 4 x double> %x)
  store <8 x double> %0, <8 x double>* %agg.result, align 64
  ret void
}

declare <8 x double> @llvm.riscv.vcast.to.fixed.v8f64.nxv4f64(<vscale x 4 x double>)

define <vscale x 1 x float> @test_vcast_from_fixed_128_f32mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <2 x float>
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v2f32(<2 x float> %0)
  ret <vscale x 1 x float> %1
}

declare <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v2f32(<2 x float>)

define <vscale x 2 x float> @test_vcast_from_fixed_128_f32m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f32m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f32m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <4 x float>
  %1 = tail call <vscale x 2 x float> @llvm.riscv.vcast.from.fixed.nxv2f32.v4f32(<4 x float> %0)
  ret <vscale x 2 x float> %1
}

declare <vscale x 2 x float> @llvm.riscv.vcast.from.fixed.nxv2f32.v4f32(<4 x float>)

define <vscale x 1 x double> @test_vcast_from_fixed_128_f64m1(i128 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f64m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f64m1:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; VLS-NEXT:    vmv.v.x v8, a1
; VLS-NEXT:    vsetvli zero, zero, e64, m1, tu, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
entry:
  %0 = bitcast i128 %x.coerce to <2 x double>
  %1 = tail call <vscale x 1 x double> @llvm.riscv.vcast.from.fixed.nxv1f64.v2f64(<2 x double> %0)
  ret <vscale x 1 x double> %1
}

declare <vscale x 1 x double> @llvm.riscv.vcast.from.fixed.nxv1f64.v2f64(<2 x double>)

define <vscale x 4 x float> @test_vcast_from_fixed_128_f32m2(<8 x float>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_f32m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f32m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <8 x float>, <8 x float>* %0, align 32
  %1 = tail call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v8f32(<8 x float> %x)
  ret <vscale x 4 x float> %1
}

declare <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v8f32(<8 x float>)

define <vscale x 2 x double> @test_vcast_from_fixed_128_f64m2(<4 x double>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_f64m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f64m2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <4 x double>, <4 x double>* %0, align 32
  %1 = tail call <vscale x 2 x double> @llvm.riscv.vcast.from.fixed.nxv2f64.v4f64(<4 x double> %x)
  ret <vscale x 2 x double> %1
}

declare <vscale x 2 x double> @llvm.riscv.vcast.from.fixed.nxv2f64.v4f64(<4 x double>)

define <vscale x 8 x float> @test_vcast_from_fixed_128_f32m4(<16 x float>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_f32m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f32m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; VLS-NEXT:    vle32.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <16 x float>, <16 x float>* %0, align 64
  %1 = tail call <vscale x 8 x float> @llvm.riscv.vcast.from.fixed.nxv8f32.v16f32(<16 x float> %x)
  ret <vscale x 8 x float> %1
}

declare <vscale x 8 x float> @llvm.riscv.vcast.from.fixed.nxv8f32.v16f32(<16 x float>)

define <vscale x 4 x double> @test_vcast_from_fixed_128_f64m4(<8 x double>* nocapture readonly %0) {
; CHECK-LABEL: test_vcast_from_fixed_128_f64m4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vle64.v v8, (a0)
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f64m4:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; VLS-NEXT:    vle64.v v8, (a0)
; VLS-NEXT:    ret
entry:
  %x = load <8 x double>, <8 x double>* %0, align 64
  %1 = tail call <vscale x 4 x double> @llvm.riscv.vcast.from.fixed.nxv4f64.v8f64(<8 x double> %x)
  ret <vscale x 4 x double> %1
}

declare <vscale x 4 x double> @llvm.riscv.vcast.from.fixed.nxv4f64.v8f64(<8 x double>)
