; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs \
; RUN:   < %s | FileCheck --check-prefix=CHECK-RV32 %s

declare i32 @llvm.riscv.vgetvxrm();
declare void @llvm.riscv.vsetvxrm.i32(i32 %roundmode);

define i32 @readvxrm() nounwind
; CHECK-RV32-LABEL: readvxrm:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    csrr a0, vxrm
; CHECK-RV32-NEXT:    ret
{
  %ret = call i32 @llvm.riscv.vgetvxrm()
  ret i32 %ret
}

define void @writevxrm(i32 %roundmode) nounwind
; CHECK-RV32-LABEL: writevxrm:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    csrw vxrm, a0
; CHECK-RV32-NEXT:    ret
{
  call void @llvm.riscv.vsetvxrm.i32(i32 %roundmode)
  ret void
}

define void @writevxrmimm() nounwind
; CHECK-RV32-LABEL: writevxrmimm:
; CHECK-RV32:       # %bb.0:
; CHECK-RV32-NEXT:    li a0, 3
; CHECK-RV32-NEXT:    csrw vxrm, a0
; CHECK-RV32-NEXT:    ret
{
  call void @llvm.riscv.vsetvxrm.i32(i32 3)
  ret void
}

