; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O0 \
; RUN:    < %s | FileCheck --check-prefix=CHECK-O0 %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:    < %s | FileCheck --check-prefix=CHECK-O2 %s
; RUN: llc -mtriple=riscv64 -mattr=+v,+f,+d -verify-machineinstrs -O2 \
; RUN:   -riscv-force-tail-undisturbed < %s | FileCheck --check-prefix=FORCE-TU %s

@scratch = global i8 0, align 16

declare i64 @llvm.riscv.vsetvli(i64, i64, i64)

declare <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64.i64(
  <vscale x 1 x double>,
  <vscale x 1 x double>,
  <vscale x 1 x double>,
  i64)

declare <vscale x 1 x double> @llvm.riscv.vle.mask.nxv1f64.i64(
  <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  i64,
  i64)

declare void @llvm.riscv.vse.nxv1f64.i64(
  <vscale x 1 x double>,
  <vscale x 1 x double>*,
  i64)

define void @test_vsetvl_avl(<vscale x 1 x double> %value, <vscale x 1 x double>* %v, <vscale x 1 x i1> %mask, i64 signext %avl) nounwind {
; CHECK-O0-LABEL: test_vsetvl_avl:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    vsetvli a1, a1, e64, m1, ta, ma
; CHECK-O0-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; CHECK-O0-NEXT:    vle64.v v8, (a0), v0.t
; CHECK-O0-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-O0-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O0-NEXT:    lui a0, %hi(scratch)
; CHECK-O0-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O0-NEXT:    vse64.v v8, (a0)
; CHECK-O0-NEXT:    ret
;
; CHECK-O2-LABEL: test_vsetvl_avl:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    vsetvli a1, a1, e64, m1, ta, ma
; CHECK-O2-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; CHECK-O2-NEXT:    vle64.v v8, (a0), v0.t
; CHECK-O2-NEXT:    vsetvli zero, zero, e64, m1, ta, ma
; CHECK-O2-NEXT:    vfadd.vv v8, v8, v8
; CHECK-O2-NEXT:    lui a0, %hi(scratch)
; CHECK-O2-NEXT:    addi a0, a0, %lo(scratch)
; CHECK-O2-NEXT:    vse64.v v8, (a0)
; CHECK-O2-NEXT:    ret
;
; FORCE-TU-LABEL: test_vsetvl_avl:
; FORCE-TU:       # %bb.0:
; FORCE-TU-NEXT:    vsetvli a1, a1, e64, m1, tu, ma
; FORCE-TU-NEXT:    vsetvli zero, a1, e64, m1, tu, mu
; FORCE-TU-NEXT:    vle64.v v8, (a0), v0.t
; FORCE-TU-NEXT:    vfadd.vv v8, v8, v8
; FORCE-TU-NEXT:    lui a0, %hi(scratch)
; FORCE-TU-NEXT:    addi a0, a0, %lo(scratch)
; FORCE-TU-NEXT:    vse64.v v8, (a0)
; FORCE-TU-NEXT:    ret
  %gvl = call i64 @llvm.riscv.vsetvli(
    i64 %avl, i64 3, i64 0)

  %vec = call <vscale x 1 x double> @llvm.riscv.vle.mask.nxv1f64.i64(
    <vscale x 1 x double> %value,
    <vscale x 1 x double>* %v,
    <vscale x 1 x i1> %mask,
    i64 %gvl,
    i64 0)

  %add = call <vscale x 1 x double> @llvm.riscv.vfadd.nxv1f64.nxv1f64.i64(
    <vscale x 1 x double> undef,
    <vscale x 1 x double> %vec,
    <vscale x 1 x double> %vec,
    i64 %gvl)

  %store_addr = bitcast i8* @scratch to <vscale x 1 x double>*

  call void @llvm.riscv.vse.nxv1f64.i64(
    <vscale x 1 x double> %add,
    <vscale x 1 x double>* %store_addr,
    i64 %gvl)

  ret void
}
