; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=riscv64 -mattr=+zve64f,+f -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -mattr=+zve64f,+f -riscv-v-vector-bits-min=128 -verify-machineinstrs | FileCheck %s --check-prefixes=VLS

; Tests in this file require Zve64f to test <vscale x 1 x float> types

define i64 @test_vcast_to_fixed_64_f32mf2(<vscale x 1 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_64_f32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    slli a0, a0, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_64_f32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e32, mf2, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    slli a0, a0, 32
; VLS-NEXT:    srli a0, a0, 32
; VLS-NEXT:    ret
; VLS32-LABEL: test_vcast_to_fixed_64_f32mf2:
; VLS32:       # %bb.0: # %entry
; VLS32-NEXT:    addi sp, sp, -32
; VLS32-NEXT:    .cfi_def_cfa_offset 32
; VLS32-NEXT:    vsetivli zero, 1, e32, mf2, ta, mu
; VLS32-NEXT:    addi a0, sp, 16
; VLS32-NEXT:    vse32.v v8, (a0)
; VLS32-NEXT:    vsetivli zero, 1, e32, m1, ta, mu
; VLS32-NEXT:    addi a0, sp, 16
; VLS32-NEXT:    vle32.v v8, (a0)
; VLS32-NEXT:    vmv.x.s a0, v8
; VLS32-NEXT:    slli a0, a0, 32
; VLS32-NEXT:    srli a0, a0, 32
; VLS32-NEXT:    addi sp, sp, 32
; VLS32-NEXT:    ret
entry:
  %0 = tail call <1 x float> @llvm.riscv.vcast.to.fixed.v1f32.nxv1f32(<vscale x 1 x float> %x)
  %bc = bitcast <1 x float> %0 to <1 x i32>
  %1 = extractelement <1 x i32> %bc, i32 0
  %retval.coerce.0.insert.ext = zext i32 %1 to i64
  ret i64 %retval.coerce.0.insert.ext
}

declare <1 x float> @llvm.riscv.vcast.to.fixed.v1f32.nxv1f32(<vscale x 1 x float>)

define i64 @test_vcast_to_fixed_128_f32mf2(<vscale x 1 x float> %x) {
; CHECK-LABEL: test_vcast_to_fixed_128_f32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_to_fixed_128_f32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 0, e64, m1, ta, ma
; VLS-NEXT:    vmv.x.s a0, v8
; VLS-NEXT:    ret
; VLS32-LABEL: test_vcast_to_fixed_128_f32mf2:
; VLS32:       # %bb.0: # %entry
; VLS32-NEXT:    addi sp, sp, -32
; VLS32-NEXT:    .cfi_def_cfa_offset 32
; VLS32-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; VLS32-NEXT:    addi a0, sp, 16
; VLS32-NEXT:    vse32.v v8, (a0)
; VLS32-NEXT:    vsetivli zero, 2, e32, m1, ta, mu
; VLS32-NEXT:    addi a0, sp, 16
; VLS32-NEXT:    vle32.v v8, (a0)
; VLS32-NEXT:    addi a0, sp, 24
; VLS32-NEXT:    vse32.v v8, (a0)
; VLS32-NEXT:    ld a0, 24(sp)
; VLS32-NEXT:    addi sp, sp, 32
; VLS32-NEXT:    ret
entry:
  %0 = tail call <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv1f32(<vscale x 1 x float> %x)
  %1 = bitcast <2 x float> %0 to i64
  ret i64 %1
}

declare <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv1f32(<vscale x 1 x float>)

define <vscale x 1 x float> @test_vcast_from_fixed_128_f32mf2(i64 %x.coerce) {
; CHECK-LABEL: test_vcast_from_fixed_128_f32mf2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; CHECK-NEXT:    vmv.s.x v8, a0
; CHECK-NEXT:    mv a0, sp
; CHECK-NEXT:    vsetivli zero, 2, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vle32.v v8, (a0)
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
;
; VLS-LABEL: test_vcast_from_fixed_128_f32mf2:
; VLS:       # %bb.0: # %entry
; VLS-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; VLS-NEXT:    vmv.s.x v8, a0
; VLS-NEXT:    ret
; VLS32-LABEL: test_vcast_from_fixed_128_f32mf2:
; VLS32:       # %bb.0: # %entry
; VLS32-NEXT:    addi sp, sp, -32
; VLS32-NEXT:    .cfi_def_cfa_offset 32
; VLS32-NEXT:    sd a0, 8(sp)
; VLS32-NEXT:    vsetivli zero, 2, e32, m1, ta, mu
; VLS32-NEXT:    addi a0, sp, 8
; VLS32-NEXT:    vle32.v v8, (a0)
; VLS32-NEXT:    addi a0, sp, 16
; VLS32-NEXT:    vse32.v v8, (a0)
; VLS32-NEXT:    vsetivli zero, 2, e32, mf2, ta, mu
; VLS32-NEXT:    addi a0, sp, 16
; VLS32-NEXT:    vle32.v v8, (a0)
; VLS32-NEXT:    addi sp, sp, 32
; VLS32-NEXT:    ret
entry:
  %0 = bitcast i64 %x.coerce to <2 x float>
  %1 = tail call <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v2f32(<2 x float> %0)
  ret <vscale x 1 x float> %1
}

declare <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v2f32(<2 x float>)
