; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=riscv64 -mcpu=sifive-x280 < %s | FileCheck %s

define <vscale x 16 x half> @foo(<vscale x 16 x half> %x, <vscale x 16 x half> %one, i64 noundef %vl) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.h.x fa5, zero
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    lui a0, %hi(.LCPI0_1)
; CHECK-NEXT:    vmv4r.v v16, v8
; CHECK-NEXT:    vfrsqrt7.v v8, v8
; CHECK-NEXT:    vmfne.vf v24, v16, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_1)(a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI0_0)
; CHECK-NEXT:    vfmul.vv v20, v16, v8
; CHECK-NEXT:    vmfne.vf v16, v16, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI0_0)(a0)
; CHECK-NEXT:    vfmsub.vv v20, v8, v12
; CHECK-NEXT:    vfmul.vf v12, v8, fa5
; CHECK-NEXT:    vmand.mm v0, v24, v16
; CHECK-NEXT:    vfnmsac.vv v8, v12, v20, v0.t
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 16 x half> @llvm.riscv.vfrsqrt7.nxv16f16.i64(<vscale x 16 x half> poison, <vscale x 16 x half> %x, i64 %vl)
  %1 = tail call <vscale x 16 x half> @llvm.riscv.vfmul.nxv16f16.nxv16f16.i64(<vscale x 16 x half> poison, <vscale x 16 x half> %x, <vscale x 16 x half> %0, i64 7, i64 %vl)
  %2 = tail call <vscale x 16 x half> @llvm.riscv.vfmsub.nxv16f16.nxv16f16.i64(<vscale x 16 x half> %1, <vscale x 16 x half> %0, <vscale x 16 x half> %one, i64 7, i64 %vl, i64 3)
  %3 = tail call <vscale x 16 x half> @llvm.riscv.vfmul.nxv16f16.f16.i64(<vscale x 16 x half> poison, <vscale x 16 x half> %0, half 0xH3805, i64 7, i64 %vl)
  %4 = tail call <vscale x 16 x i1> @llvm.riscv.vmfne.nxv16f16.f16.i64(<vscale x 16 x half> %x, half 0xH0000, i64 %vl)
  %5 = tail call <vscale x 16 x i1> @llvm.riscv.vmfne.nxv16f16.f16.i64(<vscale x 16 x half> %x, half 0xH7C00, i64 %vl)
  %6 = tail call <vscale x 16 x i1> @llvm.riscv.vmand.nxv16i1.i64(<vscale x 16 x i1> %4, <vscale x 16 x i1> %5, i64 %vl)
  %7 = tail call <vscale x 16 x half> @llvm.riscv.vfnmsac.mask.nxv16f16.nxv16f16.i64(<vscale x 16 x half> %0, <vscale x 16 x half> %3, <vscale x 16 x half> %2, <vscale x 16 x i1> %6, i64 7, i64 %vl, i64 1)
  ret <vscale x 16 x half> %7
}

declare <vscale x 16 x half> @llvm.riscv.vfrsqrt7.nxv16f16.i64(<vscale x 16 x half>, <vscale x 16 x half>, i64)
declare <vscale x 16 x half> @llvm.riscv.vfmul.nxv16f16.nxv16f16.i64(<vscale x 16 x half>, <vscale x 16 x half>, <vscale x 16 x half>, i64 immarg, i64)
declare <vscale x 16 x half> @llvm.riscv.vfmsub.nxv16f16.nxv16f16.i64(<vscale x 16 x half>, <vscale x 16 x half>, <vscale x 16 x half>, i64 immarg, i64, i64 immarg)
declare <vscale x 16 x half> @llvm.riscv.vfmul.nxv16f16.f16.i64(<vscale x 16 x half>, <vscale x 16 x half>, half, i64 immarg, i64)
declare <vscale x 16 x i1> @llvm.riscv.vmfne.nxv16f16.f16.i64(<vscale x 16 x half>, half, i64)
declare <vscale x 16 x i1> @llvm.riscv.vmand.nxv16i1.i64(<vscale x 16 x i1>, <vscale x 16 x i1>, i64)
declare <vscale x 16 x half> @llvm.riscv.vfnmsac.mask.nxv16f16.nxv16f16.i64(<vscale x 16 x half>, <vscale x 16 x half>, <vscale x 16 x half>, <vscale x 16 x i1>, i64 immarg, i64, i64 immarg)

define <vscale x 4 x half> @foo_m1(<vscale x 4 x half> %x, <vscale x 4 x half> %one, i64 noundef %vl) {
; CHECK-LABEL: foo_m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmv.h.x fa5, zero
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vfrsqrt7.v v10, v8
; CHECK-NEXT:    lui a0, %hi(.LCPI1_1)
; CHECK-NEXT:    vmfne.vf v11, v8, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI1_1)(a0)
; CHECK-NEXT:    lui a0, %hi(.LCPI1_0)
; CHECK-NEXT:    vfmul.vv v12, v8, v10
; CHECK-NEXT:    vmfne.vf v8, v8, fa5
; CHECK-NEXT:    flh fa5, %lo(.LCPI1_0)(a0)
; CHECK-NEXT:    vfmsub.vv v12, v10, v9
; CHECK-NEXT:    vmand.mm v0, v11, v8
; CHECK-NEXT:    vfmul.vf v8, v10, fa5
; CHECK-NEXT:    vfnmsac.vv v10, v8, v12, v0.t
; CHECK-NEXT:    vmv.v.v v8, v10
; CHECK-NEXT:    ret
entry:
  %0 = tail call <vscale x 4 x half> @llvm.riscv.vfrsqrt7.nxv4f16.i64(<vscale x 4 x half> poison, <vscale x 4 x half> %x, i64 %vl)
  %1 = tail call <vscale x 4 x half> @llvm.riscv.vfmul.nxv4f16.nxv4f16.i64(<vscale x 4 x half> poison, <vscale x 4 x half> %x, <vscale x 4 x half> %0, i64 7, i64 %vl)
  %2 = tail call <vscale x 4 x half> @llvm.riscv.vfmsub.nxv4f16.nxv4f16.i64(<vscale x 4 x half> %1, <vscale x 4 x half> %0, <vscale x 4 x half> %one, i64 7, i64 %vl, i64 3)
  %3 = tail call <vscale x 4 x half> @llvm.riscv.vfmul.nxv4f16.f16.i64(<vscale x 4 x half> poison, <vscale x 4 x half> %0, half 0xH3805, i64 7, i64 %vl)
  %4 = tail call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f16.f16.i64(<vscale x 4 x half> %x, half 0xH0000, i64 %vl)
  %5 = tail call <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f16.f16.i64(<vscale x 4 x half> %x, half 0xH7C00, i64 %vl)
  %6 = tail call <vscale x 4 x i1> @llvm.riscv.vmand.nxv4i1.i64(<vscale x 4 x i1> %4, <vscale x 4 x i1> %5, i64 %vl)
  %7 = tail call <vscale x 4 x half> @llvm.riscv.vfnmsac.mask.nxv4f16.nxv4f16.i64(<vscale x 4 x half> %0, <vscale x 4 x half> %3, <vscale x 4 x half> %2, <vscale x 4 x i1> %6, i64 7, i64 %vl, i64 1)
  ret <vscale x 4 x half> %7
}

declare <vscale x 4 x half> @llvm.riscv.vfrsqrt7.nxv4f16.i64(<vscale x 4 x half>, <vscale x 4 x half>, i64)
declare <vscale x 4 x half> @llvm.riscv.vfmul.nxv4f16.nxv4f16.i64(<vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, i64 immarg, i64)
declare <vscale x 4 x half> @llvm.riscv.vfmsub.nxv4f16.nxv4f16.i64(<vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, i64 immarg, i64, i64 immarg)
declare <vscale x 4 x half> @llvm.riscv.vfmul.nxv4f16.f16.i64(<vscale x 4 x half>, <vscale x 4 x half>, half, i64 immarg, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmfne.nxv4f16.f16.i64(<vscale x 4 x half>, half, i64)
declare <vscale x 4 x i1> @llvm.riscv.vmand.nxv4i1.i64(<vscale x 4 x i1>, <vscale x 4 x i1>, i64)
declare <vscale x 4 x half> @llvm.riscv.vfnmsac.mask.nxv4f16.nxv4f16.i64(<vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x i1>, i64 immarg, i64, i64 immarg)
