; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=loop-reverse < %s -S | FileCheck %s

; This test is a false positive, it is intended to fail loop reversal.
; Because the non latch exit may produce a memory store that diverges
; with respect to its data and that which is produced via the reversed
; loop, it is illegal to reverse the loop.

define i32 @dict_word2basestr(ptr %word, i64 %call) {
; CHECK-LABEL: define i32 @dict_word2basestr
; CHECK-SAME: (ptr [[WORD:%.*]], i64 [[CALL:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SUB:%.*]] = shl i64 [[CALL]], 32
; CHECK-NEXT:    [[SEXT:%.*]] = add i64 [[SUB]], -4294967296
; CHECK-NEXT:    [[IDXPROM:%.*]] = ashr exact i64 [[SEXT]], 32
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[WORD]], i64 [[IDXPROM]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i8 [[TMP0]], 41
; CHECK-NEXT:    [[CONV:%.*]] = trunc i64 [[CALL]] to i32
; CHECK-NEXT:    [[SUB3:%.*]] = add nsw i32 [[CONV]], -2
; CHECK-NEXT:    [[CMP411:%.*]] = icmp sgt i32 [[CONV]], 2
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP]], i1 [[CMP411]], i1 false
; CHECK-NEXT:    br i1 [[OR_COND]], label [[LAND_RHS_PREHEADER:%.*]], label [[CLEANUP:%.*]]
; CHECK:       land.rhs.preheader:
; CHECK-NEXT:    br label [[LAND_RHS:%.*]]
; CHECK:       land.rhs:
; CHECK-NEXT:    [[I_012:%.*]] = phi i32 [ [[DEC:%.*]], [[FOR_INC:%.*]] ], [ [[SUB3]], [[LAND_RHS_PREHEADER]] ]
; CHECK-NEXT:    [[IDXPROM6:%.*]] = zext i32 [[I_012]] to i64
; CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds i8, ptr [[WORD]], i64 [[IDXPROM6]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX7]], align 1
; CHECK-NEXT:    [[CMP9_NOT:%.*]] = icmp eq i8 [[TMP1]], 40
; CHECK-NEXT:    br i1 [[CMP9_NOT]], label [[IF_THEN13:%.*]], label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[DEC]] = add nsw i32 [[I_012]], -1
; CHECK-NEXT:    [[CMP4:%.*]] = icmp sgt i32 [[I_012]], 1
; CHECK-NEXT:    br i1 [[CMP4]], label [[LAND_RHS]], label [[CLEANUP_LOOPEXIT:%.*]]
; CHECK:       if.then13:
; CHECK-NEXT:    [[I_012_LCSSA:%.*]] = phi i32 [ [[I_012]], [[LAND_RHS]] ]
; CHECK-NEXT:    [[ARRAYIDX7_LCSSA:%.*]] = phi ptr [ [[ARRAYIDX7]], [[LAND_RHS]] ]
; CHECK-NEXT:    store i8 0, ptr [[ARRAYIDX7_LCSSA]], align 1
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       cleanup.loopexit:
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       cleanup:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ [[I_012_LCSSA]], [[IF_THEN13]] ], [ -1, [[ENTRY:%.*]] ], [ -1, [[CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %sub = shl i64 %call, 32
  %sext = add i64 %sub, -4294967296
  %idxprom = ashr exact i64 %sext, 32
  %arrayidx = getelementptr inbounds i8, ptr %word, i64 %idxprom
  %0 = load i8, ptr %arrayidx, align 1
  %cmp = icmp eq i8 %0, 41
  %conv = trunc i64 %call to i32
  %sub3 = add nsw i32 %conv, -2
  %cmp411 = icmp sgt i32 %conv, 2
  %or.cond = select i1 %cmp, i1 %cmp411, i1 false
  br i1 %or.cond, label %land.rhs.preheader, label %cleanup

land.rhs.preheader:                               ; preds = %entry
  br label %land.rhs

land.rhs:                                         ; preds = %land.rhs.preheader, %for.inc
  %i.012 = phi i32 [ %dec, %for.inc ], [ %sub3, %land.rhs.preheader ]
  %idxprom6 = zext i32 %i.012 to i64
  %arrayidx7 = getelementptr inbounds i8, ptr %word, i64 %idxprom6
  %1 = load i8, ptr %arrayidx7, align 1
  %cmp9.not = icmp eq i8 %1, 40
  br i1 %cmp9.not, label %if.then13, label %for.inc

for.inc:                                          ; preds = %land.rhs
  %dec = add nsw i32 %i.012, -1
  %cmp4 = icmp sgt i32 %i.012, 1
  br i1 %cmp4, label %land.rhs, label %cleanup.loopexit

if.then13:                                        ; preds = %land.rhs
  %i.012.lcssa = phi i32 [ %i.012, %land.rhs ]
  %arrayidx7.lcssa = phi ptr [ %arrayidx7, %land.rhs ]
  store i8 0, ptr %arrayidx7.lcssa, align 1
  br label %cleanup

cleanup.loopexit:                                 ; preds = %for.inc
  br label %cleanup

cleanup:                                          ; preds = %cleanup.loopexit, %entry, %if.then13
  %retval.0 = phi i32 [ %i.012.lcssa, %if.then13 ], [ -1, %entry ], [ -1, %cleanup.loopexit ]
  ret i32 %retval.0
}
