; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-reverse -loop-reverse-enable < %s -S | FileCheck %s

; A false positive test which tests escapes of IV.

define i32 @f(ptr dereferenceable(20) %0, i32 %1, i32 %2) {
; CHECK-LABEL: @f(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BYPASS:%.*]] = icmp slt i32 0, [[TMP2:%.*]]
; CHECK-NEXT:    br i1 [[BYPASS]], label [[BB1_PREHEADER:%.*]], label [[END:%.*]]
; CHECK:       bb1.preheader:
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ [[ADD:%.*]], [[BB1]] ], [ [[TMP2]], [[BB1_PREHEADER]] ]
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[PHI]] to i64
; CHECK-NEXT:    [[ADDR:%.*]] = getelementptr inbounds i32, ptr [[TMP0:%.*]], i64 [[ZEXT]]
; CHECK-NEXT:    store i32 0, ptr [[ADDR]], align 4
; CHECK-NEXT:    [[ADD]] = add nsw i32 [[PHI]], -1
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[PHI]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[BB1]], label [[END_LOOPEXIT:%.*]]
; CHECK:       end.loopexit:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi i32 [ [[ADD]], [[BB1]] ]
; CHECK-NEXT:    br label [[END]]
; CHECK:       end:
; CHECK-NEXT:    [[RET_PHI:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[ADD_LCSSA]], [[END_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RET_PHI]]
;
entry:
  %bypass = icmp slt i32 0, %2
  br i1 %bypass, label %bb1, label %end

bb1:                                                ; preds = %bb1, %entry
  %phi = phi i32 [ %add, %bb1 ], [ %2, %entry ]
  %zext = zext i32 %phi to i64
  %addr = getelementptr inbounds i32, ptr %0, i64 %zext
  store i32 0, ptr %addr, align 4
  %add = add nsw i32 %phi, -1
  %cmp = icmp sgt i32 %phi, 0
  br i1 %cmp, label %bb1, label %end

end:                                               ; preds = %bb1
  %ret_phi = phi i32 [ %add, %bb1 ], [ 0, %entry ]
  ret i32 %ret_phi
}
