; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --prefix-filecheck-ir-name CHECK
; RUN: opt -loop-fusion -loop-reverse-enable -passes=loop-simplify,loop-reverse,loop-fusion,newgvn < %s -S 2>&1 | FileCheck %s

@B = common global [1024 x i32] zeroinitializer, align 16

; Check that the first loop is reversed, then fused with the second,
; so that newgvn can reduce the new loop by recognizing similar values.
; Note that if we do not reverse the first loop, newgvn will
; fail to correlate similar values, which given the difference
; of the loop contents is expected. Reversing the first loop
; makes a large difference for performance here.

define void @f(ptr noalias %arg, i64 %arg2) {
; CHECK-LABEL: @f(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[CHECKTMP3:%.*]] = icmp slt i64 0, [[ARG2:%.*]]
; CHECK-NEXT:    br i1 [[CHECKTMP3]], label [[BB5_PREHEADER:%.*]], label [[BB27:%.*]]
; CHECK:       bb5.preheader:
; CHECK-NEXT:    br label [[BB5:%.*]]
; CHECK:       bb5:
; CHECK-NEXT:    [[PHI1:%.*]] = phi i64 [ [[CHECKTMP13:%.*]], [[BB5]] ], [ 0, [[BB5_PREHEADER]] ]
; CHECK-NEXT:    [[CHECKTMP13]] = add nuw nsw i64 [[PHI1]], 1
; CHECK-NEXT:    [[CHECKTMP6:%.*]] = add nsw i64 [[PHI1]], -3
; CHECK-NEXT:    [[CHECKTMP7:%.*]] = add nuw nsw i64 [[PHI1]], 3
; CHECK-NEXT:    [[CHECKTMP8:%.*]] = mul nsw i64 [[CHECKTMP6]], [[CHECKTMP7]]
; CHECK-NEXT:    [[CHECKTMP9:%.*]] = srem i64 [[CHECKTMP8]], [[PHI1]]
; CHECK-NEXT:    [[CHECKTMP10:%.*]] = trunc i64 [[CHECKTMP9]] to i32
; CHECK-NEXT:    [[CHECKTMP11:%.*]] = getelementptr inbounds i32, ptr [[ARG:%.*]], i64 [[PHI1]]
; CHECK-NEXT:    store i32 [[CHECKTMP10]], ptr [[CHECKTMP11]], align 4
; CHECK-NEXT:    [[CHECKTMP24:%.*]] = getelementptr inbounds [1024 x i32], ptr @B, i64 0, i64 [[PHI1]]
; CHECK-NEXT:    store i32 [[CHECKTMP10]], ptr [[CHECKTMP24]], align 4
; CHECK-NEXT:    [[CHECKTMP16:%.*]] = icmp slt i64 [[CHECKTMP13]], [[ARG2]]
; CHECK-NEXT:    br i1 [[CHECKTMP16]], label [[BB5]], label [[BB27_LOOPEXIT:%.*]]
; CHECK:       bb27.loopexit:
; CHECK-NEXT:    br label [[BB27]]
; CHECK:       bb27:
; CHECK-NEXT:    ret void
;
bb:
  %tmp3 = icmp slt i64 0, %arg2
  br i1 %tmp3, label %bb5, label %bb15.preheader

bb5:                                              ; preds = %bb5, %bb
  %phi1 = phi i64 [ %arg2, %bb ], [ %tmp13, %bb5 ]
  %tmp13 = add nuw nsw i64 %phi1, -1
  %tmp6 = add nsw i64 %tmp13, -3
  %tmp7 = add nuw nsw i64 %tmp13, 3
  %tmp8 = mul nsw i64 %tmp6, %tmp7
  %tmp9 = srem i64 %tmp8, %tmp13
  %tmp10 = trunc i64 %tmp9 to i32
  %tmp11 = getelementptr inbounds i32, ptr %arg, i64 %tmp13
  store i32 %tmp10, ptr %tmp11, align 4
  %tmp = icmp sgt i64 %tmp13, 0
  br i1 %tmp, label %bb5, label %bb15.preheader

bb15.preheader:                                   ; preds = %bb5, %bb
  %tmp161 = icmp slt i64 0, %arg2
  br i1 %tmp161, label %bb18, label %bb27

bb18:                                             ; preds = %bb18, %bb15.preheader
  %phi2 = phi i64 [ 0, %bb15.preheader ], [ %tmp26, %bb18 ]
  %tmp26 = add nuw nsw i64 %phi2, 1
  %tmp19 = add nsw i64 %phi2, -3
  %tmp20 = add nuw nsw i64 %phi2, 3
  %tmp21 = mul nsw i64 %tmp19, %tmp20
  %tmp22 = srem i64 %tmp21, %phi2
  %tmp23 = trunc i64 %tmp22 to i32
  %tmp24 = getelementptr inbounds [1024 x i32], ptr @B, i64 0, i64 %phi2
  store i32 %tmp23, ptr %tmp24, align 4
  %tmp16 = icmp slt i64 %tmp26, %arg2
  br i1 %tmp16, label %bb18, label %bb27

bb27:                                             ; preds = %bb18, %bb15.preheader
  ret void
}
