// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f -target-feature +d -target-feature +v \
// RUN: -target-feature +zfh -target-feature +experimental-zvfh \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck --check-prefix=CHECK-RV64 %s
#include <riscv_vector.h>
#include <riscv_ntlh.h>
// CHECK-RV64-LABEL: @test_vluxei8_v_i8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei8_v_i8mf8_ntl_ALL (const int8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei8_v_i8mf4_ntl_ALL (const int8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei8_v_i8mf2_ntl_ALL (const int8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei8_v_i8m1_ntl_ALL (const int8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei8_v_i8m2_ntl_ALL (const int8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vluxei8_v_i8m4_ntl_ALL (const int8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vluxei.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vluxei8_v_i8m8_ntl_ALL (const int8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei16_v_i8mf8_ntl_ALL (const int8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei16_v_i8mf4_ntl_ALL (const int8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei16_v_i8mf2_ntl_ALL (const int8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei16_v_i8m1_ntl_ALL (const int8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei16_v_i8m2_ntl_ALL (const int8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vluxei16_v_i8m4_ntl_ALL (const int8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei32_v_i8mf8_ntl_ALL (const int8_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei32_v_i8mf4_ntl_ALL (const int8_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei32_v_i8mf2_ntl_ALL (const int8_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei32_v_i8m1_ntl_ALL (const int8_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei32_v_i8m2_ntl_ALL (const int8_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei64_v_i8mf8_ntl_ALL (const int8_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei64_v_i8mf4_ntl_ALL (const int8_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei64_v_i8mf2_ntl_ALL (const int8_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei64_v_i8m1_ntl_ALL (const int8_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei8_v_i16mf4_ntl_ALL (const int16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei8_v_i16mf2_ntl_ALL (const int16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei8_v_i16m1_ntl_ALL (const int16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei8_v_i16m2_ntl_ALL (const int16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei8_v_i16m4_ntl_ALL (const int16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vluxei8_v_i16m8_ntl_ALL (const int16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei16_v_i16mf4_ntl_ALL (const int16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei16_v_i16mf2_ntl_ALL (const int16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei16_v_i16m1_ntl_ALL (const int16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei16_v_i16m2_ntl_ALL (const int16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei16_v_i16m4_ntl_ALL (const int16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vluxei16_v_i16m8_ntl_ALL (const int16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei32_v_i16mf4_ntl_ALL (const int16_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei32_v_i16mf2_ntl_ALL (const int16_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei32_v_i16m1_ntl_ALL (const int16_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei32_v_i16m2_ntl_ALL (const int16_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei32_v_i16m4_ntl_ALL (const int16_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei64_v_i16mf4_ntl_ALL (const int16_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei64_v_i16mf2_ntl_ALL (const int16_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei64_v_i16m1_ntl_ALL (const int16_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei64_v_i16m2_ntl_ALL (const int16_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei8_v_i32mf2_ntl_ALL (const int32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei8_v_i32m1_ntl_ALL (const int32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei8_v_i32m2_ntl_ALL (const int32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei8_v_i32m4_ntl_ALL (const int32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei8_v_i32m8_ntl_ALL (const int32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei16_v_i32mf2_ntl_ALL (const int32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei16_v_i32m1_ntl_ALL (const int32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei16_v_i32m2_ntl_ALL (const int32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei16_v_i32m4_ntl_ALL (const int32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei16_v_i32m8_ntl_ALL (const int32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei32_v_i32mf2_ntl_ALL (const int32_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei32_v_i32m1_ntl_ALL (const int32_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei32_v_i32m2_ntl_ALL (const int32_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei32_v_i32m4_ntl_ALL (const int32_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei32_v_i32m8_ntl_ALL (const int32_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei64_v_i32mf2_ntl_ALL (const int32_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei64_v_i32m1_ntl_ALL (const int32_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei64_v_i32m2_ntl_ALL (const int32_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei64_v_i32m4_ntl_ALL (const int32_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei8_v_i64m1_ntl_ALL (const int64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei8_v_i64m2_ntl_ALL (const int64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei8_v_i64m4_ntl_ALL (const int64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei8_v_i64m8_ntl_ALL (const int64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei16_v_i64m1_ntl_ALL (const int64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei16_v_i64m2_ntl_ALL (const int64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei16_v_i64m4_ntl_ALL (const int64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei16_v_i64m8_ntl_ALL (const int64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei32_v_i64m1_ntl_ALL (const int64_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei32_v_i64m2_ntl_ALL (const int64_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei32_v_i64m4_ntl_ALL (const int64_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei32_v_i64m8_ntl_ALL (const int64_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei64_v_i64m1_ntl_ALL (const int64_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei64_v_i64m2_ntl_ALL (const int64_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei64_v_i64m4_ntl_ALL (const int64_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei64_v_i64m8_ntl_ALL (const int64_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei8_v_u8mf8_ntl_ALL (const uint8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei8_v_u8mf4_ntl_ALL (const uint8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei8_v_u8mf2_ntl_ALL (const uint8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei8_v_u8m1_ntl_ALL (const uint8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei8_v_u8m2_ntl_ALL (const uint8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vluxei8_v_u8m4_ntl_ALL (const uint8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vluxei.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vluxei8_v_u8m8_ntl_ALL (const uint8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei16_v_u8mf8_ntl_ALL (const uint8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei16_v_u8mf4_ntl_ALL (const uint8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei16_v_u8mf2_ntl_ALL (const uint8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei16_v_u8m1_ntl_ALL (const uint8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei16_v_u8m2_ntl_ALL (const uint8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vluxei16_v_u8m4_ntl_ALL (const uint8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei32_v_u8mf8_ntl_ALL (const uint8_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei32_v_u8mf4_ntl_ALL (const uint8_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei32_v_u8mf2_ntl_ALL (const uint8_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei32_v_u8m1_ntl_ALL (const uint8_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei32_v_u8m2_ntl_ALL (const uint8_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8mf8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei64_v_u8mf8_ntl_ALL (const uint8_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei64_v_u8mf4_ntl_ALL (const uint8_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei64_v_u8mf2_ntl_ALL (const uint8_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei64_v_u8m1_ntl_ALL (const uint8_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei8_v_u16mf4_ntl_ALL (const uint16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei8_v_u16mf2_ntl_ALL (const uint16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei8_v_u16m1_ntl_ALL (const uint16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei8_v_u16m2_ntl_ALL (const uint16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei8_v_u16m4_ntl_ALL (const uint16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vluxei8_v_u16m8_ntl_ALL (const uint16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei16_v_u16mf4_ntl_ALL (const uint16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei16_v_u16mf2_ntl_ALL (const uint16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei16_v_u16m1_ntl_ALL (const uint16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei16_v_u16m2_ntl_ALL (const uint16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei16_v_u16m4_ntl_ALL (const uint16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vluxei16_v_u16m8_ntl_ALL (const uint16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei32_v_u16mf4_ntl_ALL (const uint16_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei32_v_u16mf2_ntl_ALL (const uint16_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei32_v_u16m1_ntl_ALL (const uint16_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei32_v_u16m2_ntl_ALL (const uint16_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei32_v_u16m4_ntl_ALL (const uint16_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei64_v_u16mf4_ntl_ALL (const uint16_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei64_v_u16mf2_ntl_ALL (const uint16_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei64_v_u16m1_ntl_ALL (const uint16_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei64_v_u16m2_ntl_ALL (const uint16_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei8_v_u32mf2_ntl_ALL (const uint32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei8_v_u32m1_ntl_ALL (const uint32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei8_v_u32m2_ntl_ALL (const uint32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei8_v_u32m4_ntl_ALL (const uint32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei8_v_u32m8_ntl_ALL (const uint32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei16_v_u32mf2_ntl_ALL (const uint32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei16_v_u32m1_ntl_ALL (const uint32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei16_v_u32m2_ntl_ALL (const uint32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei16_v_u32m4_ntl_ALL (const uint32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei16_v_u32m8_ntl_ALL (const uint32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei32_v_u32mf2_ntl_ALL (const uint32_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei32_v_u32m1_ntl_ALL (const uint32_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei32_v_u32m2_ntl_ALL (const uint32_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei32_v_u32m4_ntl_ALL (const uint32_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei32_v_u32m8_ntl_ALL (const uint32_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei64_v_u32mf2_ntl_ALL (const uint32_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei64_v_u32m1_ntl_ALL (const uint32_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei64_v_u32m2_ntl_ALL (const uint32_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei64_v_u32m4_ntl_ALL (const uint32_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei8_v_u64m1_ntl_ALL (const uint64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei8_v_u64m2_ntl_ALL (const uint64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei8_v_u64m4_ntl_ALL (const uint64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei8_v_u64m8_ntl_ALL (const uint64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei16_v_u64m1_ntl_ALL (const uint64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei16_v_u64m2_ntl_ALL (const uint64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei16_v_u64m4_ntl_ALL (const uint64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei16_v_u64m8_ntl_ALL (const uint64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei32_v_u64m1_ntl_ALL (const uint64_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei32_v_u64m2_ntl_ALL (const uint64_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei32_v_u64m4_ntl_ALL (const uint64_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei32_v_u64m8_ntl_ALL (const uint64_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei64_v_u64m1_ntl_ALL (const uint64_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei64_v_u64m2_ntl_ALL (const uint64_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei64_v_u64m4_ntl_ALL (const uint64_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei64_v_u64m8_ntl_ALL (const uint64_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.nxv1f16.nxv1i8.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei8_v_f16mf4_ntl_ALL (const _Float16 *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.nxv2f16.nxv2i8.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei8_v_f16mf2_ntl_ALL (const _Float16 *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.nxv4f16.nxv4i8.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei8_v_f16m1_ntl_ALL (const _Float16 *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.nxv8f16.nxv8i8.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei8_v_f16m2_ntl_ALL (const _Float16 *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.nxv16f16.nxv16i8.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei8_v_f16m4_ntl_ALL (const _Float16 *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vluxei.nxv32f16.nxv32i8.i64(<vscale x 32 x half> poison, ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vluxei8_v_f16m8_ntl_ALL (const _Float16 *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.nxv1f16.nxv1i16.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei16_v_f16mf4_ntl_ALL (const _Float16 *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.nxv2f16.nxv2i16.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei16_v_f16mf2_ntl_ALL (const _Float16 *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.nxv4f16.nxv4i16.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei16_v_f16m1_ntl_ALL (const _Float16 *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.nxv8f16.nxv8i16.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei16_v_f16m2_ntl_ALL (const _Float16 *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.nxv16f16.nxv16i16.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei16_v_f16m4_ntl_ALL (const _Float16 *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vluxei.nxv32f16.nxv32i16.i64(<vscale x 32 x half> poison, ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vluxei16_v_f16m8_ntl_ALL (const _Float16 *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.nxv1f16.nxv1i32.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei32_v_f16mf4_ntl_ALL (const _Float16 *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.nxv2f16.nxv2i32.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei32_v_f16mf2_ntl_ALL (const _Float16 *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.nxv4f16.nxv4i32.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei32_v_f16m1_ntl_ALL (const _Float16 *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.nxv8f16.nxv8i32.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei32_v_f16m2_ntl_ALL (const _Float16 *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.nxv16f16.nxv16i32.i64(<vscale x 16 x half> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei32_v_f16m4_ntl_ALL (const _Float16 *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16mf4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.nxv1f16.nxv1i64.i64(<vscale x 1 x half> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei64_v_f16mf4_ntl_ALL (const _Float16 *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.nxv2f16.nxv2i64.i64(<vscale x 2 x half> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei64_v_f16mf2_ntl_ALL (const _Float16 *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.nxv4f16.nxv4i64.i64(<vscale x 4 x half> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei64_v_f16m1_ntl_ALL (const _Float16 *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.nxv8f16.nxv8i64.i64(<vscale x 8 x half> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei64_v_f16m2_ntl_ALL (const _Float16 *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.nxv1f32.nxv1i8.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei8_v_f32mf2_ntl_ALL (const float *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.nxv2f32.nxv2i8.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei8_v_f32m1_ntl_ALL (const float *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.nxv4f32.nxv4i8.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei8_v_f32m2_ntl_ALL (const float *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.nxv8f32.nxv8i8.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei8_v_f32m4_ntl_ALL (const float *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.nxv16f32.nxv16i8.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei8_v_f32m8_ntl_ALL (const float *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.nxv1f32.nxv1i16.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei16_v_f32mf2_ntl_ALL (const float *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.nxv2f32.nxv2i16.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei16_v_f32m1_ntl_ALL (const float *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.nxv4f32.nxv4i16.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei16_v_f32m2_ntl_ALL (const float *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.nxv8f32.nxv8i16.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei16_v_f32m4_ntl_ALL (const float *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.nxv16f32.nxv16i16.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei16_v_f32m8_ntl_ALL (const float *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.nxv1f32.nxv1i32.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei32_v_f32mf2_ntl_ALL (const float *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.nxv2f32.nxv2i32.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei32_v_f32m1_ntl_ALL (const float *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.nxv4f32.nxv4i32.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei32_v_f32m2_ntl_ALL (const float *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.nxv8f32.nxv8i32.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei32_v_f32m4_ntl_ALL (const float *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.nxv16f32.nxv16i32.i64(<vscale x 16 x float> poison, ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei32_v_f32m8_ntl_ALL (const float *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32mf2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.nxv1f32.nxv1i64.i64(<vscale x 1 x float> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei64_v_f32mf2_ntl_ALL (const float *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.nxv2f32.nxv2i64.i64(<vscale x 2 x float> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei64_v_f32m1_ntl_ALL (const float *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.nxv4f32.nxv4i64.i64(<vscale x 4 x float> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei64_v_f32m2_ntl_ALL (const float *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.nxv8f32.nxv8i64.i64(<vscale x 8 x float> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei64_v_f32m4_ntl_ALL (const float *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.nxv1f64.nxv1i8.i64(<vscale x 1 x double> poison, ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei8_v_f64m1_ntl_ALL (const double *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.nxv2f64.nxv2i8.i64(<vscale x 2 x double> poison, ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei8_v_f64m2_ntl_ALL (const double *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.nxv4f64.nxv4i8.i64(<vscale x 4 x double> poison, ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei8_v_f64m4_ntl_ALL (const double *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.nxv8f64.nxv8i8.i64(<vscale x 8 x double> poison, ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei8_v_f64m8_ntl_ALL (const double *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.nxv1f64.nxv1i16.i64(<vscale x 1 x double> poison, ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei16_v_f64m1_ntl_ALL (const double *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.nxv2f64.nxv2i16.i64(<vscale x 2 x double> poison, ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei16_v_f64m2_ntl_ALL (const double *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.nxv4f64.nxv4i16.i64(<vscale x 4 x double> poison, ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei16_v_f64m4_ntl_ALL (const double *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.nxv8f64.nxv8i16.i64(<vscale x 8 x double> poison, ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei16_v_f64m8_ntl_ALL (const double *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.nxv1f64.nxv1i32.i64(<vscale x 1 x double> poison, ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei32_v_f64m1_ntl_ALL (const double *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.nxv2f64.nxv2i32.i64(<vscale x 2 x double> poison, ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei32_v_f64m2_ntl_ALL (const double *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.nxv4f64.nxv4i32.i64(<vscale x 4 x double> poison, ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei32_v_f64m4_ntl_ALL (const double *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.nxv8f64.nxv8i32.i64(<vscale x 8 x double> poison, ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei32_v_f64m8_ntl_ALL (const double *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m1_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.nxv1f64.nxv1i64.i64(<vscale x 1 x double> poison, ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei64_v_f64m1_ntl_ALL (const double *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m2_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.nxv2f64.nxv2i64.i64(<vscale x 2 x double> poison, ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei64_v_f64m2_ntl_ALL (const double *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m4_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.nxv4f64.nxv4i64.i64(<vscale x 4 x double> poison, ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei64_v_f64m4_ntl_ALL (const double *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m8_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.nxv8f64.nxv8i64.i64(<vscale x 8 x double> poison, ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei64_v_f64m8_ntl_ALL (const double *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei8_v_i8mf8_m_ntl_ALL (vbool64_t mask, vint8mf8_t merge, const int8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei8_v_i8mf4_m_ntl_ALL (vbool32_t mask, vint8mf4_t merge, const int8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei8_v_i8mf2_m_ntl_ALL (vbool16_t mask, vint8mf2_t merge, const int8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei8_v_i8m1_m_ntl_ALL (vbool8_t mask, vint8m1_t merge, const int8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei8_v_i8m2_m_ntl_ALL (vbool4_t mask, vint8m2_t merge, const int8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.mask.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vluxei8_v_i8m4_m_ntl_ALL (vbool2_t mask, vint8m4_t merge, const int8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i8m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vluxei.mask.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vluxei8_v_i8m8_m_ntl_ALL (vbool1_t mask, vint8m8_t merge, const int8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei16_v_i8mf8_m_ntl_ALL (vbool64_t mask, vint8mf8_t merge, const int8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei16_v_i8mf4_m_ntl_ALL (vbool32_t mask, vint8mf4_t merge, const int8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei16_v_i8mf2_m_ntl_ALL (vbool16_t mask, vint8mf2_t merge, const int8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei16_v_i8m1_m_ntl_ALL (vbool8_t mask, vint8m1_t merge, const int8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei16_v_i8m2_m_ntl_ALL (vbool4_t mask, vint8m2_t merge, const int8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i8m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.mask.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vluxei16_v_i8m4_m_ntl_ALL (vbool2_t mask, vint8m4_t merge, const int8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei32_v_i8mf8_m_ntl_ALL (vbool64_t mask, vint8mf8_t merge, const int8_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei32_v_i8mf4_m_ntl_ALL (vbool32_t mask, vint8mf4_t merge, const int8_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei32_v_i8mf2_m_ntl_ALL (vbool16_t mask, vint8mf2_t merge, const int8_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei32_v_i8m1_m_ntl_ALL (vbool8_t mask, vint8m1_t merge, const int8_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i8m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vluxei32_v_i8m2_m_ntl_ALL (vbool4_t mask, vint8m2_t merge, const int8_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vluxei64_v_i8mf8_m_ntl_ALL (vbool64_t mask, vint8mf8_t merge, const int8_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vluxei64_v_i8mf4_m_ntl_ALL (vbool32_t mask, vint8mf4_t merge, const int8_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vluxei64_v_i8mf2_m_ntl_ALL (vbool16_t mask, vint8mf2_t merge, const int8_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vluxei64_v_i8m1_m_ntl_ALL (vbool8_t mask, vint8m1_t merge, const int8_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei8_v_i16mf4_m_ntl_ALL (vbool64_t mask, vint16mf4_t merge, const int16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei8_v_i16mf2_m_ntl_ALL (vbool32_t mask, vint16mf2_t merge, const int16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei8_v_i16m1_m_ntl_ALL (vbool16_t mask, vint16m1_t merge, const int16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei8_v_i16m2_m_ntl_ALL (vbool8_t mask, vint16m2_t merge, const int16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei8_v_i16m4_m_ntl_ALL (vbool4_t mask, vint16m4_t merge, const int16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i16m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.mask.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vluxei8_v_i16m8_m_ntl_ALL (vbool2_t mask, vint16m8_t merge, const int16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei16_v_i16mf4_m_ntl_ALL (vbool64_t mask, vint16mf4_t merge, const int16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei16_v_i16mf2_m_ntl_ALL (vbool32_t mask, vint16mf2_t merge, const int16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei16_v_i16m1_m_ntl_ALL (vbool16_t mask, vint16m1_t merge, const int16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei16_v_i16m2_m_ntl_ALL (vbool8_t mask, vint16m2_t merge, const int16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei16_v_i16m4_m_ntl_ALL (vbool4_t mask, vint16m4_t merge, const int16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i16m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.mask.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vluxei16_v_i16m8_m_ntl_ALL (vbool2_t mask, vint16m8_t merge, const int16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei32_v_i16mf4_m_ntl_ALL (vbool64_t mask, vint16mf4_t merge, const int16_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei32_v_i16mf2_m_ntl_ALL (vbool32_t mask, vint16mf2_t merge, const int16_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei32_v_i16m1_m_ntl_ALL (vbool16_t mask, vint16m1_t merge, const int16_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei32_v_i16m2_m_ntl_ALL (vbool8_t mask, vint16m2_t merge, const int16_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vluxei32_v_i16m4_m_ntl_ALL (vbool4_t mask, vint16m4_t merge, const int16_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vluxei64_v_i16mf4_m_ntl_ALL (vbool64_t mask, vint16mf4_t merge, const int16_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vluxei64_v_i16mf2_m_ntl_ALL (vbool32_t mask, vint16mf2_t merge, const int16_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vluxei64_v_i16m1_m_ntl_ALL (vbool16_t mask, vint16m1_t merge, const int16_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vluxei64_v_i16m2_m_ntl_ALL (vbool8_t mask, vint16m2_t merge, const int16_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei8_v_i32mf2_m_ntl_ALL (vbool64_t mask, vint32mf2_t merge, const int32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei8_v_i32m1_m_ntl_ALL (vbool32_t mask, vint32m1_t merge, const int32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei8_v_i32m2_m_ntl_ALL (vbool16_t mask, vint32m2_t merge, const int32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei8_v_i32m4_m_ntl_ALL (vbool8_t mask, vint32m4_t merge, const int32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei8_v_i32m8_m_ntl_ALL (vbool4_t mask, vint32m8_t merge, const int32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei16_v_i32mf2_m_ntl_ALL (vbool64_t mask, vint32mf2_t merge, const int32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei16_v_i32m1_m_ntl_ALL (vbool32_t mask, vint32m1_t merge, const int32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei16_v_i32m2_m_ntl_ALL (vbool16_t mask, vint32m2_t merge, const int32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei16_v_i32m4_m_ntl_ALL (vbool8_t mask, vint32m4_t merge, const int32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei16_v_i32m8_m_ntl_ALL (vbool4_t mask, vint32m8_t merge, const int32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei32_v_i32mf2_m_ntl_ALL (vbool64_t mask, vint32mf2_t merge, const int32_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei32_v_i32m1_m_ntl_ALL (vbool32_t mask, vint32m1_t merge, const int32_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei32_v_i32m2_m_ntl_ALL (vbool16_t mask, vint32m2_t merge, const int32_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei32_v_i32m4_m_ntl_ALL (vbool8_t mask, vint32m4_t merge, const int32_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vluxei32_v_i32m8_m_ntl_ALL (vbool4_t mask, vint32m8_t merge, const int32_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vluxei64_v_i32mf2_m_ntl_ALL (vbool64_t mask, vint32mf2_t merge, const int32_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vluxei64_v_i32m1_m_ntl_ALL (vbool32_t mask, vint32m1_t merge, const int32_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vluxei64_v_i32m2_m_ntl_ALL (vbool16_t mask, vint32m2_t merge, const int32_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vluxei64_v_i32m4_m_ntl_ALL (vbool8_t mask, vint32m4_t merge, const int32_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei8_v_i64m1_m_ntl_ALL (vbool64_t mask, vint64m1_t merge, const int64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei8_v_i64m2_m_ntl_ALL (vbool32_t mask, vint64m2_t merge, const int64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei8_v_i64m4_m_ntl_ALL (vbool16_t mask, vint64m4_t merge, const int64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_i64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei8_v_i64m8_m_ntl_ALL (vbool8_t mask, vint64m8_t merge, const int64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei16_v_i64m1_m_ntl_ALL (vbool64_t mask, vint64m1_t merge, const int64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei16_v_i64m2_m_ntl_ALL (vbool32_t mask, vint64m2_t merge, const int64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei16_v_i64m4_m_ntl_ALL (vbool16_t mask, vint64m4_t merge, const int64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_i64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei16_v_i64m8_m_ntl_ALL (vbool8_t mask, vint64m8_t merge, const int64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei32_v_i64m1_m_ntl_ALL (vbool64_t mask, vint64m1_t merge, const int64_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei32_v_i64m2_m_ntl_ALL (vbool32_t mask, vint64m2_t merge, const int64_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei32_v_i64m4_m_ntl_ALL (vbool16_t mask, vint64m4_t merge, const int64_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_i64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei32_v_i64m8_m_ntl_ALL (vbool8_t mask, vint64m8_t merge, const int64_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vluxei64_v_i64m1_m_ntl_ALL (vbool64_t mask, vint64m1_t merge, const int64_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vluxei64_v_i64m2_m_ntl_ALL (vbool32_t mask, vint64m2_t merge, const int64_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vluxei64_v_i64m4_m_ntl_ALL (vbool16_t mask, vint64m4_t merge, const int64_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_i64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vluxei64_v_i64m8_m_ntl_ALL (vbool8_t mask, vint64m8_t merge, const int64_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei8_v_u8mf8_m_ntl_ALL (vbool64_t mask, vuint8mf8_t merge, const uint8_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei8_v_u8mf4_m_ntl_ALL (vbool32_t mask, vuint8mf4_t merge, const uint8_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei8_v_u8mf2_m_ntl_ALL (vbool16_t mask, vuint8mf2_t merge, const uint8_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei8_v_u8m1_m_ntl_ALL (vbool8_t mask, vuint8m1_t merge, const uint8_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei8_v_u8m2_m_ntl_ALL (vbool4_t mask, vuint8m2_t merge, const uint8_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.mask.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vluxei8_v_u8m4_m_ntl_ALL (vbool2_t mask, vuint8m4_t merge, const uint8_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u8m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vluxei.mask.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i8> [[BINDEX:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vluxei8_v_u8m8_m_ntl_ALL (vbool1_t mask, vuint8m8_t merge, const uint8_t *base, vuint8m8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i16.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei16_v_u8mf8_m_ntl_ALL (vbool64_t mask, vuint8mf8_t merge, const uint8_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i16.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei16_v_u8mf4_m_ntl_ALL (vbool32_t mask, vuint8mf4_t merge, const uint8_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i16.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei16_v_u8mf2_m_ntl_ALL (vbool16_t mask, vuint8mf2_t merge, const uint8_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i16.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei16_v_u8m1_m_ntl_ALL (vbool8_t mask, vuint8m1_t merge, const uint8_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.nxv16i16.i64(<vscale x 16 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei16_v_u8m2_m_ntl_ALL (vbool4_t mask, vuint8m2_t merge, const uint8_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u8m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vluxei.mask.nxv32i8.nxv32i16.i64(<vscale x 32 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vluxei16_v_u8m4_m_ntl_ALL (vbool2_t mask, vuint8m4_t merge, const uint8_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i32.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei32_v_u8mf8_m_ntl_ALL (vbool64_t mask, vuint8mf8_t merge, const uint8_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i32.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei32_v_u8mf4_m_ntl_ALL (vbool32_t mask, vuint8mf4_t merge, const uint8_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i32.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei32_v_u8mf2_m_ntl_ALL (vbool16_t mask, vuint8mf2_t merge, const uint8_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i32.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei32_v_u8m1_m_ntl_ALL (vbool8_t mask, vuint8m1_t merge, const uint8_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u8m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vluxei.mask.nxv16i8.nxv16i32.i64(<vscale x 16 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vluxei32_v_u8m2_m_ntl_ALL (vbool4_t mask, vuint8m2_t merge, const uint8_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8mf8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vluxei.mask.nxv1i8.nxv1i64.i64(<vscale x 1 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vluxei64_v_u8mf8_m_ntl_ALL (vbool64_t mask, vuint8mf8_t merge, const uint8_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vluxei.mask.nxv2i8.nxv2i64.i64(<vscale x 2 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vluxei64_v_u8mf4_m_ntl_ALL (vbool32_t mask, vuint8mf4_t merge, const uint8_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vluxei.mask.nxv4i8.nxv4i64.i64(<vscale x 4 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vluxei64_v_u8mf2_m_ntl_ALL (vbool16_t mask, vuint8mf2_t merge, const uint8_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u8m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vluxei.mask.nxv8i8.nxv8i64.i64(<vscale x 8 x i8> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vluxei64_v_u8m1_m_ntl_ALL (vbool8_t mask, vuint8m1_t merge, const uint8_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i8.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei8_v_u16mf4_m_ntl_ALL (vbool64_t mask, vuint16mf4_t merge, const uint16_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i8.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei8_v_u16mf2_m_ntl_ALL (vbool32_t mask, vuint16mf2_t merge, const uint16_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i8.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei8_v_u16m1_m_ntl_ALL (vbool16_t mask, vuint16m1_t merge, const uint16_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i8.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei8_v_u16m2_m_ntl_ALL (vbool8_t mask, vuint16m2_t merge, const uint16_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.nxv16i8.i64(<vscale x 16 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei8_v_u16m4_m_ntl_ALL (vbool4_t mask, vuint16m4_t merge, const uint16_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u16m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.mask.nxv32i16.nxv32i8.i64(<vscale x 32 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vluxei8_v_u16m8_m_ntl_ALL (vbool2_t mask, vuint16m8_t merge, const uint16_t *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei16_v_u16mf4_m_ntl_ALL (vbool64_t mask, vuint16mf4_t merge, const uint16_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei16_v_u16mf2_m_ntl_ALL (vbool32_t mask, vuint16mf2_t merge, const uint16_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei16_v_u16m1_m_ntl_ALL (vbool16_t mask, vuint16m1_t merge, const uint16_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei16_v_u16m2_m_ntl_ALL (vbool8_t mask, vuint16m2_t merge, const uint16_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei16_v_u16m4_m_ntl_ALL (vbool4_t mask, vuint16m4_t merge, const uint16_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u16m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vluxei.mask.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vluxei16_v_u16m8_m_ntl_ALL (vbool2_t mask, vuint16m8_t merge, const uint16_t *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i32.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei32_v_u16mf4_m_ntl_ALL (vbool64_t mask, vuint16mf4_t merge, const uint16_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i32.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei32_v_u16mf2_m_ntl_ALL (vbool32_t mask, vuint16mf2_t merge, const uint16_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i32.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei32_v_u16m1_m_ntl_ALL (vbool16_t mask, vuint16m1_t merge, const uint16_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i32.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei32_v_u16m2_m_ntl_ALL (vbool8_t mask, vuint16m2_t merge, const uint16_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vluxei.mask.nxv16i16.nxv16i32.i64(<vscale x 16 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vluxei32_v_u16m4_m_ntl_ALL (vbool4_t mask, vuint16m4_t merge, const uint16_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vluxei.mask.nxv1i16.nxv1i64.i64(<vscale x 1 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vluxei64_v_u16mf4_m_ntl_ALL (vbool64_t mask, vuint16mf4_t merge, const uint16_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vluxei.mask.nxv2i16.nxv2i64.i64(<vscale x 2 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vluxei64_v_u16mf2_m_ntl_ALL (vbool32_t mask, vuint16mf2_t merge, const uint16_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vluxei.mask.nxv4i16.nxv4i64.i64(<vscale x 4 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vluxei64_v_u16m1_m_ntl_ALL (vbool16_t mask, vuint16m1_t merge, const uint16_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vluxei.mask.nxv8i16.nxv8i64.i64(<vscale x 8 x i16> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vluxei64_v_u16m2_m_ntl_ALL (vbool8_t mask, vuint16m2_t merge, const uint16_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i8.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei8_v_u32mf2_m_ntl_ALL (vbool64_t mask, vuint32mf2_t merge, const uint32_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i8.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei8_v_u32m1_m_ntl_ALL (vbool32_t mask, vuint32m1_t merge, const uint32_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i8.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei8_v_u32m2_m_ntl_ALL (vbool16_t mask, vuint32m2_t merge, const uint32_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i8.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei8_v_u32m4_m_ntl_ALL (vbool8_t mask, vuint32m4_t merge, const uint32_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.nxv16i8.i64(<vscale x 16 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei8_v_u32m8_m_ntl_ALL (vbool4_t mask, vuint32m8_t merge, const uint32_t *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i16.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei16_v_u32mf2_m_ntl_ALL (vbool64_t mask, vuint32mf2_t merge, const uint32_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i16.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei16_v_u32m1_m_ntl_ALL (vbool32_t mask, vuint32m1_t merge, const uint32_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i16.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei16_v_u32m2_m_ntl_ALL (vbool16_t mask, vuint32m2_t merge, const uint32_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i16.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei16_v_u32m4_m_ntl_ALL (vbool8_t mask, vuint32m4_t merge, const uint32_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.nxv16i16.i64(<vscale x 16 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei16_v_u32m8_m_ntl_ALL (vbool4_t mask, vuint32m8_t merge, const uint32_t *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei32_v_u32mf2_m_ntl_ALL (vbool64_t mask, vuint32mf2_t merge, const uint32_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei32_v_u32m1_m_ntl_ALL (vbool32_t mask, vuint32m1_t merge, const uint32_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei32_v_u32m2_m_ntl_ALL (vbool16_t mask, vuint32m2_t merge, const uint32_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei32_v_u32m4_m_ntl_ALL (vbool8_t mask, vuint32m4_t merge, const uint32_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vluxei.mask.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vluxei32_v_u32m8_m_ntl_ALL (vbool4_t mask, vuint32m8_t merge, const uint32_t *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vluxei.mask.nxv1i32.nxv1i64.i64(<vscale x 1 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vluxei64_v_u32mf2_m_ntl_ALL (vbool64_t mask, vuint32mf2_t merge, const uint32_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vluxei.mask.nxv2i32.nxv2i64.i64(<vscale x 2 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vluxei64_v_u32m1_m_ntl_ALL (vbool32_t mask, vuint32m1_t merge, const uint32_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vluxei.mask.nxv4i32.nxv4i64.i64(<vscale x 4 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vluxei64_v_u32m2_m_ntl_ALL (vbool16_t mask, vuint32m2_t merge, const uint32_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vluxei.mask.nxv8i32.nxv8i64.i64(<vscale x 8 x i32> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vluxei64_v_u32m4_m_ntl_ALL (vbool8_t mask, vuint32m4_t merge, const uint32_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i8.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei8_v_u64m1_m_ntl_ALL (vbool64_t mask, vuint64m1_t merge, const uint64_t *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i8.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei8_v_u64m2_m_ntl_ALL (vbool32_t mask, vuint64m2_t merge, const uint64_t *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i8.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei8_v_u64m4_m_ntl_ALL (vbool16_t mask, vuint64m4_t merge, const uint64_t *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_u64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i8.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei8_v_u64m8_m_ntl_ALL (vbool8_t mask, vuint64m8_t merge, const uint64_t *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i16.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei16_v_u64m1_m_ntl_ALL (vbool64_t mask, vuint64m1_t merge, const uint64_t *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i16.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei16_v_u64m2_m_ntl_ALL (vbool32_t mask, vuint64m2_t merge, const uint64_t *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i16.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei16_v_u64m4_m_ntl_ALL (vbool16_t mask, vuint64m4_t merge, const uint64_t *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_u64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i16.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei16_v_u64m8_m_ntl_ALL (vbool8_t mask, vuint64m8_t merge, const uint64_t *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i32.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei32_v_u64m1_m_ntl_ALL (vbool64_t mask, vuint64m1_t merge, const uint64_t *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i32.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei32_v_u64m2_m_ntl_ALL (vbool32_t mask, vuint64m2_t merge, const uint64_t *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i32.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei32_v_u64m4_m_ntl_ALL (vbool16_t mask, vuint64m4_t merge, const uint64_t *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_u64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i32.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei32_v_u64m8_m_ntl_ALL (vbool8_t mask, vuint64m8_t merge, const uint64_t *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vluxei.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vluxei64_v_u64m1_m_ntl_ALL (vbool64_t mask, vuint64m1_t merge, const uint64_t *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vluxei.mask.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vluxei64_v_u64m2_m_ntl_ALL (vbool32_t mask, vuint64m2_t merge, const uint64_t *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vluxei.mask.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vluxei64_v_u64m4_m_ntl_ALL (vbool16_t mask, vuint64m4_t merge, const uint64_t *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_u64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vluxei.mask.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vluxei64_v_u64m8_m_ntl_ALL (vbool8_t mask, vuint64m8_t merge, const uint64_t *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.mask.nxv1f16.nxv1i8.i64(<vscale x 1 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei8_v_f16mf4_m_ntl_ALL (vbool64_t mask, vfloat16mf4_t merge, const _Float16 *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.mask.nxv2f16.nxv2i8.i64(<vscale x 2 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei8_v_f16mf2_m_ntl_ALL (vbool32_t mask, vfloat16mf2_t merge, const _Float16 *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.mask.nxv4f16.nxv4i8.i64(<vscale x 4 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei8_v_f16m1_m_ntl_ALL (vbool16_t mask, vfloat16m1_t merge, const _Float16 *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.mask.nxv8f16.nxv8i8.i64(<vscale x 8 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei8_v_f16m2_m_ntl_ALL (vbool8_t mask, vfloat16m2_t merge, const _Float16 *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.mask.nxv16f16.nxv16i8.i64(<vscale x 16 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei8_v_f16m4_m_ntl_ALL (vbool4_t mask, vfloat16m4_t merge, const _Float16 *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f16m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vluxei.mask.nxv32f16.nxv32i8.i64(<vscale x 32 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i8> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vluxei8_v_f16m8_m_ntl_ALL (vbool2_t mask, vfloat16m8_t merge, const _Float16 *base, vuint8m4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.mask.nxv1f16.nxv1i16.i64(<vscale x 1 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei16_v_f16mf4_m_ntl_ALL (vbool64_t mask, vfloat16mf4_t merge, const _Float16 *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.mask.nxv2f16.nxv2i16.i64(<vscale x 2 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei16_v_f16mf2_m_ntl_ALL (vbool32_t mask, vfloat16mf2_t merge, const _Float16 *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.mask.nxv4f16.nxv4i16.i64(<vscale x 4 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei16_v_f16m1_m_ntl_ALL (vbool16_t mask, vfloat16m1_t merge, const _Float16 *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.mask.nxv8f16.nxv8i16.i64(<vscale x 8 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei16_v_f16m2_m_ntl_ALL (vbool8_t mask, vfloat16m2_t merge, const _Float16 *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.mask.nxv16f16.nxv16i16.i64(<vscale x 16 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei16_v_f16m4_m_ntl_ALL (vbool4_t mask, vfloat16m4_t merge, const _Float16 *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f16m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 32 x half> @llvm.riscv.vluxei.mask.nxv32f16.nxv32i16.i64(<vscale x 32 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i16> [[BINDEX:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 32 x half> [[TMP0]]
//
vfloat16m8_t test_vluxei16_v_f16m8_m_ntl_ALL (vbool2_t mask, vfloat16m8_t merge, const _Float16 *base, vuint16m8_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.mask.nxv1f16.nxv1i32.i64(<vscale x 1 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei32_v_f16mf4_m_ntl_ALL (vbool64_t mask, vfloat16mf4_t merge, const _Float16 *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.mask.nxv2f16.nxv2i32.i64(<vscale x 2 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei32_v_f16mf2_m_ntl_ALL (vbool32_t mask, vfloat16mf2_t merge, const _Float16 *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.mask.nxv4f16.nxv4i32.i64(<vscale x 4 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei32_v_f16m1_m_ntl_ALL (vbool16_t mask, vfloat16m1_t merge, const _Float16 *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.mask.nxv8f16.nxv8i32.i64(<vscale x 8 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei32_v_f16m2_m_ntl_ALL (vbool8_t mask, vfloat16m2_t merge, const _Float16 *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f16m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x half> @llvm.riscv.vluxei.mask.nxv16f16.nxv16i32.i64(<vscale x 16 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x half> [[TMP0]]
//
vfloat16m4_t test_vluxei32_v_f16m4_m_ntl_ALL (vbool4_t mask, vfloat16m4_t merge, const _Float16 *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16mf4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x half> @llvm.riscv.vluxei.mask.nxv1f16.nxv1i64.i64(<vscale x 1 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x half> [[TMP0]]
//
vfloat16mf4_t test_vluxei64_v_f16mf4_m_ntl_ALL (vbool64_t mask, vfloat16mf4_t merge, const _Float16 *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x half> @llvm.riscv.vluxei.mask.nxv2f16.nxv2i64.i64(<vscale x 2 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x half> [[TMP0]]
//
vfloat16mf2_t test_vluxei64_v_f16mf2_m_ntl_ALL (vbool32_t mask, vfloat16mf2_t merge, const _Float16 *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x half> @llvm.riscv.vluxei.mask.nxv4f16.nxv4i64.i64(<vscale x 4 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x half> [[TMP0]]
//
vfloat16m1_t test_vluxei64_v_f16m1_m_ntl_ALL (vbool16_t mask, vfloat16m1_t merge, const _Float16 *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f16m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x half> @llvm.riscv.vluxei.mask.nxv8f16.nxv8i64.i64(<vscale x 8 x half> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x half> [[TMP0]]
//
vfloat16m2_t test_vluxei64_v_f16m2_m_ntl_ALL (vbool8_t mask, vfloat16m2_t merge, const _Float16 *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.mask.nxv1f32.nxv1i8.i64(<vscale x 1 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei8_v_f32mf2_m_ntl_ALL (vbool64_t mask, vfloat32mf2_t merge, const float *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.mask.nxv2f32.nxv2i8.i64(<vscale x 2 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei8_v_f32m1_m_ntl_ALL (vbool32_t mask, vfloat32m1_t merge, const float *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.mask.nxv4f32.nxv4i8.i64(<vscale x 4 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei8_v_f32m2_m_ntl_ALL (vbool16_t mask, vfloat32m2_t merge, const float *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.mask.nxv8f32.nxv8i8.i64(<vscale x 8 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei8_v_f32m4_m_ntl_ALL (vbool8_t mask, vfloat32m4_t merge, const float *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.mask.nxv16f32.nxv16i8.i64(<vscale x 16 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i8> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei8_v_f32m8_m_ntl_ALL (vbool4_t mask, vfloat32m8_t merge, const float *base, vuint8m2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.mask.nxv1f32.nxv1i16.i64(<vscale x 1 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei16_v_f32mf2_m_ntl_ALL (vbool64_t mask, vfloat32mf2_t merge, const float *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.mask.nxv2f32.nxv2i16.i64(<vscale x 2 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei16_v_f32m1_m_ntl_ALL (vbool32_t mask, vfloat32m1_t merge, const float *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.mask.nxv4f32.nxv4i16.i64(<vscale x 4 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei16_v_f32m2_m_ntl_ALL (vbool16_t mask, vfloat32m2_t merge, const float *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.mask.nxv8f32.nxv8i16.i64(<vscale x 8 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei16_v_f32m4_m_ntl_ALL (vbool8_t mask, vfloat32m4_t merge, const float *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.mask.nxv16f32.nxv16i16.i64(<vscale x 16 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i16> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei16_v_f32m8_m_ntl_ALL (vbool4_t mask, vfloat32m8_t merge, const float *base, vuint16m4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.mask.nxv1f32.nxv1i32.i64(<vscale x 1 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei32_v_f32mf2_m_ntl_ALL (vbool64_t mask, vfloat32mf2_t merge, const float *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.mask.nxv2f32.nxv2i32.i64(<vscale x 2 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei32_v_f32m1_m_ntl_ALL (vbool32_t mask, vfloat32m1_t merge, const float *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.mask.nxv4f32.nxv4i32.i64(<vscale x 4 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei32_v_f32m2_m_ntl_ALL (vbool16_t mask, vfloat32m2_t merge, const float *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.mask.nxv8f32.nxv8i32.i64(<vscale x 8 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei32_v_f32m4_m_ntl_ALL (vbool8_t mask, vfloat32m4_t merge, const float *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f32m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 16 x float> @llvm.riscv.vluxei.mask.nxv16f32.nxv16i32.i64(<vscale x 16 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i32> [[BINDEX:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 16 x float> [[TMP0]]
//
vfloat32m8_t test_vluxei32_v_f32m8_m_ntl_ALL (vbool4_t mask, vfloat32m8_t merge, const float *base, vuint32m8_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32mf2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x float> @llvm.riscv.vluxei.mask.nxv1f32.nxv1i64.i64(<vscale x 1 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x float> [[TMP0]]
//
vfloat32mf2_t test_vluxei64_v_f32mf2_m_ntl_ALL (vbool64_t mask, vfloat32mf2_t merge, const float *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x float> @llvm.riscv.vluxei.mask.nxv2f32.nxv2i64.i64(<vscale x 2 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x float> [[TMP0]]
//
vfloat32m1_t test_vluxei64_v_f32m1_m_ntl_ALL (vbool32_t mask, vfloat32m1_t merge, const float *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x float> @llvm.riscv.vluxei.mask.nxv4f32.nxv4i64.i64(<vscale x 4 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x float> [[TMP0]]
//
vfloat32m2_t test_vluxei64_v_f32m2_m_ntl_ALL (vbool16_t mask, vfloat32m2_t merge, const float *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f32m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x float> @llvm.riscv.vluxei.mask.nxv8f32.nxv8i64.i64(<vscale x 8 x float> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x float> [[TMP0]]
//
vfloat32m4_t test_vluxei64_v_f32m4_m_ntl_ALL (vbool8_t mask, vfloat32m4_t merge, const float *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.mask.nxv1f64.nxv1i8.i64(<vscale x 1 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i8> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei8_v_f64m1_m_ntl_ALL (vbool64_t mask, vfloat64m1_t merge, const double *base, vuint8mf8_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.mask.nxv2f64.nxv2i8.i64(<vscale x 2 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i8> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei8_v_f64m2_m_ntl_ALL (vbool32_t mask, vfloat64m2_t merge, const double *base, vuint8mf4_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.mask.nxv4f64.nxv4i8.i64(<vscale x 4 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i8> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei8_v_f64m4_m_ntl_ALL (vbool16_t mask, vfloat64m4_t merge, const double *base, vuint8mf2_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei8_v_f64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.mask.nxv8f64.nxv8i8.i64(<vscale x 8 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i8> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei8_v_f64m8_m_ntl_ALL (vbool8_t mask, vfloat64m8_t merge, const double *base, vuint8m1_t bindex, size_t vl, int domain) {
  return vluxei8_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.mask.nxv1f64.nxv1i16.i64(<vscale x 1 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i16> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei16_v_f64m1_m_ntl_ALL (vbool64_t mask, vfloat64m1_t merge, const double *base, vuint16mf4_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.mask.nxv2f64.nxv2i16.i64(<vscale x 2 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i16> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei16_v_f64m2_m_ntl_ALL (vbool32_t mask, vfloat64m2_t merge, const double *base, vuint16mf2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.mask.nxv4f64.nxv4i16.i64(<vscale x 4 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i16> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei16_v_f64m4_m_ntl_ALL (vbool16_t mask, vfloat64m4_t merge, const double *base, vuint16m1_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei16_v_f64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.mask.nxv8f64.nxv8i16.i64(<vscale x 8 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i16> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei16_v_f64m8_m_ntl_ALL (vbool8_t mask, vfloat64m8_t merge, const double *base, vuint16m2_t bindex, size_t vl, int domain) {
  return vluxei16_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.mask.nxv1f64.nxv1i32.i64(<vscale x 1 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i32> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei32_v_f64m1_m_ntl_ALL (vbool64_t mask, vfloat64m1_t merge, const double *base, vuint32mf2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.mask.nxv2f64.nxv2i32.i64(<vscale x 2 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i32> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei32_v_f64m2_m_ntl_ALL (vbool32_t mask, vfloat64m2_t merge, const double *base, vuint32m1_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.mask.nxv4f64.nxv4i32.i64(<vscale x 4 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i32> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei32_v_f64m4_m_ntl_ALL (vbool16_t mask, vfloat64m4_t merge, const double *base, vuint32m2_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei32_v_f64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.mask.nxv8f64.nxv8i32.i64(<vscale x 8 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i32> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei32_v_f64m8_m_ntl_ALL (vbool8_t mask, vfloat64m8_t merge, const double *base, vuint32m4_t bindex, size_t vl, int domain) {
  return vluxei32_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m1_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 1 x double> @llvm.riscv.vluxei.mask.nxv1f64.nxv1i64.i64(<vscale x 1 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i64> [[BINDEX:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 1 x double> [[TMP0]]
//
vfloat64m1_t test_vluxei64_v_f64m1_m_ntl_ALL (vbool64_t mask, vfloat64m1_t merge, const double *base, vuint64m1_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m2_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 2 x double> @llvm.riscv.vluxei.mask.nxv2f64.nxv2i64.i64(<vscale x 2 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i64> [[BINDEX:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 2 x double> [[TMP0]]
//
vfloat64m2_t test_vluxei64_v_f64m2_m_ntl_ALL (vbool32_t mask, vfloat64m2_t merge, const double *base, vuint64m2_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m4_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 4 x double> @llvm.riscv.vluxei.mask.nxv4f64.nxv4i64.i64(<vscale x 4 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i64> [[BINDEX:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 4 x double> [[TMP0]]
//
vfloat64m4_t test_vluxei64_v_f64m4_m_ntl_ALL (vbool16_t mask, vfloat64m4_t merge, const double *base, vuint64m4_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
// CHECK-RV64-LABEL: @test_vluxei64_v_f64m8_m_ntl_ALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    [[TMP0:%.*]] = call <vscale x 8 x double> @llvm.riscv.vluxei.mask.nxv8f64.nxv8i64.i64(<vscale x 8 x double> [[MERGE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i64> [[BINDEX:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]], i64 0), !nontemporal !4
// CHECK-RV64-NEXT:    ret <vscale x 8 x double> [[TMP0]]
//
vfloat64m8_t test_vluxei64_v_f64m8_m_ntl_ALL (vbool8_t mask, vfloat64m8_t merge, const double *base, vuint64m8_t bindex, size_t vl, int domain) {
  return vluxei64_ntl(mask, merge, base, bindex, vl, __RISCV_NTLH_ALL);
}
