// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f -target-feature +d -target-feature +v -target-feature +zfh \
// RUN:   -target-feature +experimental-zvfh -disable-O0-optnone -emit-llvm %s -o - | opt -S -passes=mem2reg | FileCheck --check-prefix=CHECK-RV64 %s
#include <riscv_vector.h>
#include <riscv_ntlh.h>
// CHECK-RV64-LABEL: @test_vse8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8mf8_ntl_PALL (int8_t *base, vint8mf8_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8mf4_ntl_PALL (int8_t *base, vint8mf4_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8mf2_ntl_PALL (int8_t *base, vint8mf2_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m1_ntl_PALL (int8_t *base, vint8m1_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m2_ntl_PALL (int8_t *base, vint8m2_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m4_ntl_PALL (int8_t *base, vint8m4_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m8_ntl_PALL (int8_t *base, vint8m8_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf4_ntl_PALL (int16_t *base, vint16mf4_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf2_ntl_PALL (int16_t *base, vint16mf2_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m1_ntl_PALL (int16_t *base, vint16m1_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m2_ntl_PALL (int16_t *base, vint16m2_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m4_ntl_PALL (int16_t *base, vint16m4_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m8_ntl_PALL (int16_t *base, vint16m8_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32mf2_ntl_PALL (int32_t *base, vint32mf2_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m1_ntl_PALL (int32_t *base, vint32m1_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m2_ntl_PALL (int32_t *base, vint32m2_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m4_ntl_PALL (int32_t *base, vint32m4_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m8_ntl_PALL (int32_t *base, vint32m8_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m1_ntl_PALL (int64_t *base, vint64m1_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m2_ntl_PALL (int64_t *base, vint64m2_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m4_ntl_PALL (int64_t *base, vint64m4_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m8_ntl_PALL (int64_t *base, vint64m8_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8mf8_ntl_PALL (uint8_t *base, vuint8mf8_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8mf4_ntl_PALL (uint8_t *base, vuint8mf4_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8mf2_ntl_PALL (uint8_t *base, vuint8mf2_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m1_ntl_PALL (uint8_t *base, vuint8m1_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m2_ntl_PALL (uint8_t *base, vuint8m2_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m4_ntl_PALL (uint8_t *base, vuint8m4_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m8_ntl_PALL (uint8_t *base, vuint8m8_t value, size_t vl, int domain) {
  return vse8_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf4_ntl_PALL (uint16_t *base, vuint16mf4_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf2_ntl_PALL (uint16_t *base, vuint16mf2_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m1_ntl_PALL (uint16_t *base, vuint16m1_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m2_ntl_PALL (uint16_t *base, vuint16m2_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m4_ntl_PALL (uint16_t *base, vuint16m4_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m8_ntl_PALL (uint16_t *base, vuint16m8_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32mf2_ntl_PALL (uint32_t *base, vuint32mf2_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m1_ntl_PALL (uint32_t *base, vuint32m1_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m2_ntl_PALL (uint32_t *base, vuint32m2_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m4_ntl_PALL (uint32_t *base, vuint32m4_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m8_ntl_PALL (uint32_t *base, vuint32m8_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m1_ntl_PALL (uint64_t *base, vuint64m1_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m2_ntl_PALL (uint64_t *base, vuint64m2_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m4_ntl_PALL (uint64_t *base, vuint64m4_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m8_ntl_PALL (uint64_t *base, vuint64m8_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1f16.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf4_ntl_PALL (_Float16 *base, vfloat16mf4_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2f16.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf2_ntl_PALL (_Float16 *base, vfloat16mf2_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4f16.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m1_ntl_PALL (_Float16 *base, vfloat16m1_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8f16.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m2_ntl_PALL (_Float16 *base, vfloat16m2_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16f16.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m4_ntl_PALL (_Float16 *base, vfloat16m4_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv32f16.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m8_ntl_PALL (_Float16 *base, vfloat16m8_t value, size_t vl, int domain) {
  return vse16_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1f32.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32mf2_ntl_PALL (float *base, vfloat32mf2_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2f32.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m1_ntl_PALL (float *base, vfloat32m1_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4f32.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m2_ntl_PALL (float *base, vfloat32m2_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8f32.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m4_ntl_PALL (float *base, vfloat32m4_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv16f32.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m8_ntl_PALL (float *base, vfloat32m8_t value, size_t vl, int domain) {
  return vse32_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv1f64.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m1_ntl_PALL (double *base, vfloat64m1_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv2f64.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m2_ntl_PALL (double *base, vfloat64m2_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv4f64.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m4_ntl_PALL (double *base, vfloat64m4_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.nxv8f64.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m8_ntl_PALL (double *base, vfloat64m8_t value, size_t vl, int domain) {
  return vse64_ntl(base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, vint8mf8_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, vint8mf4_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, vint8mf2_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, vint8m1_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, vint8m2_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m4_m_ntl_PALL (vbool2_t mask, int8_t *base, vint8m4_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_i8m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_i8m8_m_ntl_PALL (vbool1_t mask, int8_t *base, vint8m8_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, vint16mf4_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, vint16mf2_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, vint16m1_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, vint16m2_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m4_m_ntl_PALL (vbool4_t mask, int16_t *base, vint16m4_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_i16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_i16m8_m_ntl_PALL (vbool2_t mask, int16_t *base, vint16m8_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, vint32mf2_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, vint32m1_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, vint32m2_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m4_m_ntl_PALL (vbool8_t mask, int32_t *base, vint32m4_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_i32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_i32m8_m_ntl_PALL (vbool4_t mask, int32_t *base, vint32m8_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, vint64m1_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, vint64m2_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m4_m_ntl_PALL (vbool16_t mask, int64_t *base, vint64m4_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_i64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_i64m8_m_ntl_PALL (vbool8_t mask, int64_t *base, vint64m8_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i8.i64(<vscale x 1 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, vuint8mf8_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i8.i64(<vscale x 2 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, vuint8mf4_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i8.i64(<vscale x 4 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, vuint8mf2_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i8.i64(<vscale x 8 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, vuint8m1_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i8.i64(<vscale x 16 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, vuint8m2_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32i8.i64(<vscale x 32 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m4_m_ntl_PALL (vbool2_t mask, uint8_t *base, vuint8m4_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse8_v_u8m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv64i8.i64(<vscale x 64 x i8> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 64 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse8_v_u8m8_m_ntl_PALL (vbool1_t mask, uint8_t *base, vuint8m8_t value, size_t vl, int domain) {
  return vse8_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i16.i64(<vscale x 1 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, vuint16mf4_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i16.i64(<vscale x 2 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, vuint16mf2_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i16.i64(<vscale x 4 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, vuint16m1_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i16.i64(<vscale x 8 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, vuint16m2_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i16.i64(<vscale x 16 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m4_m_ntl_PALL (vbool4_t mask, uint16_t *base, vuint16m4_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_u16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32i16.i64(<vscale x 32 x i16> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_u16m8_m_ntl_PALL (vbool2_t mask, uint16_t *base, vuint16m8_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i32.i64(<vscale x 1 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, vuint32mf2_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i32.i64(<vscale x 2 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, vuint32m1_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i32.i64(<vscale x 4 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, vuint32m2_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i32.i64(<vscale x 8 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m4_m_ntl_PALL (vbool8_t mask, uint32_t *base, vuint32m4_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_u32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16i32.i64(<vscale x 16 x i32> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_u32m8_m_ntl_PALL (vbool4_t mask, uint32_t *base, vuint32m8_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1i64.i64(<vscale x 1 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, vuint64m1_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2i64.i64(<vscale x 2 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, vuint64m2_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4i64.i64(<vscale x 4 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m4_m_ntl_PALL (vbool16_t mask, uint64_t *base, vuint64m4_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_u64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8i64.i64(<vscale x 8 x i64> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_u64m8_m_ntl_PALL (vbool8_t mask, uint64_t *base, vuint64m8_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1f16.i64(<vscale x 1 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, vfloat16mf4_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2f16.i64(<vscale x 2 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, vfloat16mf2_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4f16.i64(<vscale x 4 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, vfloat16m1_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8f16.i64(<vscale x 8 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, vfloat16m2_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16f16.i64(<vscale x 16 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m4_m_ntl_PALL (vbool4_t mask, _Float16 *base, vfloat16m4_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse16_v_f16m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv32f16.i64(<vscale x 32 x half> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse16_v_f16m8_m_ntl_PALL (vbool2_t mask, _Float16 *base, vfloat16m8_t value, size_t vl, int domain) {
  return vse16_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1f32.i64(<vscale x 1 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, vfloat32mf2_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2f32.i64(<vscale x 2 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, vfloat32m1_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4f32.i64(<vscale x 4 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, vfloat32m2_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8f32.i64(<vscale x 8 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m4_m_ntl_PALL (vbool8_t mask, float *base, vfloat32m4_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse32_v_f32m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv16f32.i64(<vscale x 16 x float> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse32_v_f32m8_m_ntl_PALL (vbool4_t mask, float *base, vfloat32m8_t value, size_t vl, int domain) {
  return vse32_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv1f64.i64(<vscale x 1 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, vfloat64m1_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv2f64.i64(<vscale x 2 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, vfloat64m2_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv4f64.i64(<vscale x 4 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m4_m_ntl_PALL (vbool16_t mask, double *base, vfloat64m4_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vse64_v_f64m8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vse.mask.nxv8f64.i64(<vscale x 8 x double> [[VALUE:%.*]], ptr [[BASE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vse64_v_f64m8_m_ntl_PALL (vbool8_t mask, double *base, vfloat64m8_t value, size_t vl, int domain) {
  return vse64_ntl(mask, base, value, vl, __RISCV_NTLH_ALL_PRIVATE);
}
