// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +f -target-feature +d \
// RUN:   -target-feature +v -target-feature +zfh -target-feature +experimental-zvfh \
// RUN:   -disable-O0-optnone -emit-llvm %s \
// RUN:   -o - | opt -S -passes=mem2reg | FileCheck --check-prefix=CHECK-RV64 %s
#include <riscv_vector.h>
#include <riscv_ntlh.h>
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, vint8mf8_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, vint8mf8_t v5, vint8mf8_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], <vscale x 1 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8mf8_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, vint8mf8_t v5, vint8mf8_t v6, vint8mf8_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, vint8mf4_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, vint8mf4_t v5, vint8mf4_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], <vscale x 2 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8mf4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, vint8mf4_t v5, vint8mf4_t v6, vint8mf4_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, vint8mf2_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, vint8mf2_t v5, vint8mf2_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], <vscale x 4 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8mf2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, vint8mf2_t v5, vint8mf2_t v6, vint8mf2_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, vint8m1_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, vint8m1_t v5, vint8m1_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], <vscale x 8 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8m1_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, vint8m1_t v5, vint8m1_t v6, vint8m1_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8m2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m2_t v0, vint8m2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8m2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m2_t v0, vint8m2_t v1, vint8m2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], <vscale x 16 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8m2_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m2_t v0, vint8m2_t v1, vint8m2_t v2, vint8m2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv32i8.i64(<vscale x 32 x i8> [[V0:%.*]], <vscale x 32 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8m4_ntl_PALL (int8_t *base, ptrdiff_t bstride, vint8m4_t v0, vint8m4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, vint16mf4_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, vint16mf4_t v5, vint16mf4_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_i16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], <vscale x 1 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_i16mf4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, vint16mf4_t v5, vint16mf4_t v6, vint16mf4_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, vint16mf2_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, vint16mf2_t v5, vint16mf2_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_i16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], <vscale x 2 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_i16mf2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, vint16mf2_t v5, vint16mf2_t v6, vint16mf2_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, vint16m1_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, vint16m1_t v5, vint16m1_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_i16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], <vscale x 4 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_i16m1_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, vint16m1_t v5, vint16m1_t v6, vint16m1_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16m2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m2_t v0, vint16m2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16m2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m2_t v0, vint16m2_t v1, vint16m2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], <vscale x 8 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16m2_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m2_t v0, vint16m2_t v1, vint16m2_t v2, vint16m2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv16i16.i64(<vscale x 16 x i16> [[V0:%.*]], <vscale x 16 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16m4_ntl_PALL (int16_t *base, ptrdiff_t bstride, vint16m4_t v0, vint16m4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, vint32mf2_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, vint32mf2_t v5, vint32mf2_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_i32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], <vscale x 1 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_i32mf2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, vint32mf2_t v5, vint32mf2_t v6, vint32mf2_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, vint32m1_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, vint32m1_t v5, vint32m1_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_i32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], <vscale x 2 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_i32m1_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, vint32m1_t v5, vint32m1_t v6, vint32m1_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32m2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m2_t v0, vint32m2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_i32m2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m2_t v0, vint32m2_t v1, vint32m2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_i32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_i32m2_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m2_t v0, vint32m2_t v1, vint32m2_t v2, vint32m2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8i32.i64(<vscale x 8 x i32> [[V0:%.*]], <vscale x 8 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32m4_ntl_PALL (int32_t *base, ptrdiff_t bstride, vint32m4_t v0, vint32m4_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, size_t vl, int domain) {
  return vssseg5e64_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, vint64m1_t v5, size_t vl, int domain) {
  return vssseg6e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, vint64m1_t v5, vint64m1_t v6, size_t vl, int domain) {
  return vssseg7e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e64_v_i64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], <vscale x 1 x i64> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e64_v_i64m1_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, vint64m1_t v5, vint64m1_t v6, vint64m1_t v7, size_t vl, int domain) {
  return vssseg8e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_i64m2_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m2_t v0, vint64m2_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_i64m2_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m2_t v0, vint64m2_t v1, vint64m2_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_i64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], <vscale x 2 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_i64m2_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m2_t v0, vint64m2_t v1, vint64m2_t v2, vint64m2_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_i64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i64.i64(<vscale x 4 x i64> [[V0:%.*]], <vscale x 4 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_i64m4_ntl_PALL (int64_t *base, ptrdiff_t bstride, vint64m4_t v0, vint64m4_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, vuint8mf8_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, vuint8mf8_t v5, vuint8mf8_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8mf8_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], <vscale x 1 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8mf8_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, vuint8mf8_t v5, vuint8mf8_t v6, vuint8mf8_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, vuint8mf4_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, vuint8mf4_t v5, vuint8mf4_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], <vscale x 2 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8mf4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, vuint8mf4_t v5, vuint8mf4_t v6, vuint8mf4_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, vuint8mf2_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, vuint8mf2_t v5, vuint8mf2_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], <vscale x 4 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8mf2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, vuint8mf2_t v5, vuint8mf2_t v6, vuint8mf2_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, vuint8m1_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, vuint8m1_t v5, vuint8m1_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], <vscale x 8 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8m1_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, vuint8m1_t v5, vuint8m1_t v6, vuint8m1_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8m2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m2_t v0, vuint8m2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8m2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m2_t v0, vuint8m2_t v1, vuint8m2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], <vscale x 16 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8m2_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m2_t v0, vuint8m2_t v1, vuint8m2_t v2, vuint8m2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv32i8.i64(<vscale x 32 x i8> [[V0:%.*]], <vscale x 32 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8m4_ntl_PALL (uint8_t *base, ptrdiff_t bstride, vuint8m4_t v0, vuint8m4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, vuint16mf4_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, vuint16mf4_t v5, vuint16mf4_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_u16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], <vscale x 1 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_u16mf4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, vuint16mf4_t v5, vuint16mf4_t v6, vuint16mf4_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, vuint16mf2_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, vuint16mf2_t v5, vuint16mf2_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_u16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], <vscale x 2 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_u16mf2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, vuint16mf2_t v5, vuint16mf2_t v6, vuint16mf2_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, vuint16m1_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, vuint16m1_t v5, vuint16m1_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_u16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], <vscale x 4 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_u16m1_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, vuint16m1_t v5, vuint16m1_t v6, vuint16m1_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16m2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m2_t v0, vuint16m2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16m2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m2_t v0, vuint16m2_t v1, vuint16m2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], <vscale x 8 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16m2_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m2_t v0, vuint16m2_t v1, vuint16m2_t v2, vuint16m2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv16i16.i64(<vscale x 16 x i16> [[V0:%.*]], <vscale x 16 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16m4_ntl_PALL (uint16_t *base, ptrdiff_t bstride, vuint16m4_t v0, vuint16m4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, vuint32mf2_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, vuint32mf2_t v5, vuint32mf2_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_u32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], <vscale x 1 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_u32mf2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, vuint32mf2_t v5, vuint32mf2_t v6, vuint32mf2_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, vuint32m1_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, vuint32m1_t v5, vuint32m1_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_u32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], <vscale x 2 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_u32m1_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, vuint32m1_t v5, vuint32m1_t v6, vuint32m1_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32m2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m2_t v0, vuint32m2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_u32m2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m2_t v0, vuint32m2_t v1, vuint32m2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_u32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_u32m2_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m2_t v0, vuint32m2_t v1, vuint32m2_t v2, vuint32m2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8i32.i64(<vscale x 8 x i32> [[V0:%.*]], <vscale x 8 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32m4_ntl_PALL (uint32_t *base, ptrdiff_t bstride, vuint32m4_t v0, vuint32m4_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, size_t vl, int domain) {
  return vssseg5e64_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, vuint64m1_t v5, size_t vl, int domain) {
  return vssseg6e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, vuint64m1_t v5, vuint64m1_t v6, size_t vl, int domain) {
  return vssseg7e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e64_v_u64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], <vscale x 1 x i64> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e64_v_u64m1_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, vuint64m1_t v5, vuint64m1_t v6, vuint64m1_t v7, size_t vl, int domain) {
  return vssseg8e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_u64m2_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m2_t v0, vuint64m2_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_u64m2_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m2_t v0, vuint64m2_t v1, vuint64m2_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_u64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], <vscale x 2 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_u64m2_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m2_t v0, vuint64m2_t v1, vuint64m2_t v2, vuint64m2_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_u64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4i64.i64(<vscale x 4 x i64> [[V0:%.*]], <vscale x 4 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_u64m4_ntl_PALL (uint64_t *base, ptrdiff_t bstride, vuint64m4_t v0, vuint64m4_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], <vscale x 1 x half> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, vfloat16mf4_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], <vscale x 1 x half> [[V5:%.*]], <vscale x 1 x half> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, vfloat16mf4_t v5, vfloat16mf4_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_f16mf4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], <vscale x 1 x half> [[V5:%.*]], <vscale x 1 x half> [[V6:%.*]], <vscale x 1 x half> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_f16mf4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, vfloat16mf4_t v5, vfloat16mf4_t v6, vfloat16mf4_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], <vscale x 2 x half> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, vfloat16mf2_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], <vscale x 2 x half> [[V5:%.*]], <vscale x 2 x half> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, vfloat16mf2_t v5, vfloat16mf2_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_f16mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], <vscale x 2 x half> [[V5:%.*]], <vscale x 2 x half> [[V6:%.*]], <vscale x 2 x half> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_f16mf2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, vfloat16mf2_t v5, vfloat16mf2_t v6, vfloat16mf2_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], <vscale x 4 x half> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, vfloat16m1_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], <vscale x 4 x half> [[V5:%.*]], <vscale x 4 x half> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, vfloat16m1_t v5, vfloat16m1_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_f16m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], <vscale x 4 x half> [[V5:%.*]], <vscale x 4 x half> [[V6:%.*]], <vscale x 4 x half> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_f16m1_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, vfloat16m1_t v5, vfloat16m1_t v6, vfloat16m1_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8f16.i64(<vscale x 8 x half> [[V0:%.*]], <vscale x 8 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16m2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m2_t v0, vfloat16m2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv8f16.i64(<vscale x 8 x half> [[V0:%.*]], <vscale x 8 x half> [[V1:%.*]], <vscale x 8 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16m2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m2_t v0, vfloat16m2_t v1, vfloat16m2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv8f16.i64(<vscale x 8 x half> [[V0:%.*]], <vscale x 8 x half> [[V1:%.*]], <vscale x 8 x half> [[V2:%.*]], <vscale x 8 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16m2_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m2_t v0, vfloat16m2_t v1, vfloat16m2_t v2, vfloat16m2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv16f16.i64(<vscale x 16 x half> [[V0:%.*]], <vscale x 16 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16m4_ntl_PALL (_Float16 *base, ptrdiff_t bstride, vfloat16m4_t v0, vfloat16m4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], <vscale x 1 x float> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, vfloat32mf2_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], <vscale x 1 x float> [[V5:%.*]], <vscale x 1 x float> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, vfloat32mf2_t v5, vfloat32mf2_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_f32mf2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], <vscale x 1 x float> [[V5:%.*]], <vscale x 1 x float> [[V6:%.*]], <vscale x 1 x float> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_f32mf2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, vfloat32mf2_t v5, vfloat32mf2_t v6, vfloat32mf2_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], <vscale x 2 x float> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, vfloat32m1_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], <vscale x 2 x float> [[V5:%.*]], <vscale x 2 x float> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, vfloat32m1_t v5, vfloat32m1_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_f32m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], <vscale x 2 x float> [[V5:%.*]], <vscale x 2 x float> [[V6:%.*]], <vscale x 2 x float> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_f32m1_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, vfloat32m1_t v5, vfloat32m1_t v6, vfloat32m1_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4f32.i64(<vscale x 4 x float> [[V0:%.*]], <vscale x 4 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32m2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m2_t v0, vfloat32m2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv4f32.i64(<vscale x 4 x float> [[V0:%.*]], <vscale x 4 x float> [[V1:%.*]], <vscale x 4 x float> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_f32m2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m2_t v0, vfloat32m2_t v1, vfloat32m2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_f32m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv4f32.i64(<vscale x 4 x float> [[V0:%.*]], <vscale x 4 x float> [[V1:%.*]], <vscale x 4 x float> [[V2:%.*]], <vscale x 4 x float> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_f32m2_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m2_t v0, vfloat32m2_t v1, vfloat32m2_t v2, vfloat32m2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv8f32.i64(<vscale x 8 x float> [[V0:%.*]], <vscale x 8 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32m4_ntl_PALL (float *base, ptrdiff_t bstride, vfloat32m4_t v0, vfloat32m4_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, size_t vl, int domain) {
  return vssseg5e64_ntl(base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], <vscale x 1 x double> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, vfloat64m1_t v5, size_t vl, int domain) {
  return vssseg6e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], <vscale x 1 x double> [[V5:%.*]], <vscale x 1 x double> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, vfloat64m1_t v5, vfloat64m1_t v6, size_t vl, int domain) {
  return vssseg7e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e64_v_f64m1_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], <vscale x 1 x double> [[V5:%.*]], <vscale x 1 x double> [[V6:%.*]], <vscale x 1 x double> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e64_v_f64m1_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, vfloat64m1_t v5, vfloat64m1_t v6, vfloat64m1_t v7, size_t vl, int domain) {
  return vssseg8e64_ntl(base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv2f64.i64(<vscale x 2 x double> [[V0:%.*]], <vscale x 2 x double> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_f64m2_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m2_t v0, vfloat64m2_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.nxv2f64.i64(<vscale x 2 x double> [[V0:%.*]], <vscale x 2 x double> [[V1:%.*]], <vscale x 2 x double> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_f64m2_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m2_t v0, vfloat64m2_t v1, vfloat64m2_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_f64m2_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.nxv2f64.i64(<vscale x 2 x double> [[V0:%.*]], <vscale x 2 x double> [[V1:%.*]], <vscale x 2 x double> [[V2:%.*]], <vscale x 2 x double> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_f64m2_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m2_t v0, vfloat64m2_t v1, vfloat64m2_t v2, vfloat64m2_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_f64m4_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.nxv4f64.i64(<vscale x 4 x double> [[V0:%.*]], <vscale x 4 x double> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_f64m4_ntl_PALL (double *base, ptrdiff_t bstride, vfloat64m4_t v0, vfloat64m4_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, vint8mf8_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, vint8mf8_t v5, vint8mf8_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], <vscale x 1 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8mf8_m_ntl_PALL (vbool64_t mask, int8_t *base, ptrdiff_t bstride, vint8mf8_t v0, vint8mf8_t v1, vint8mf8_t v2, vint8mf8_t v3, vint8mf8_t v4, vint8mf8_t v5, vint8mf8_t v6, vint8mf8_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, vint8mf4_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, vint8mf4_t v5, vint8mf4_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], <vscale x 2 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8mf4_m_ntl_PALL (vbool32_t mask, int8_t *base, ptrdiff_t bstride, vint8mf4_t v0, vint8mf4_t v1, vint8mf4_t v2, vint8mf4_t v3, vint8mf4_t v4, vint8mf4_t v5, vint8mf4_t v6, vint8mf4_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, vint8mf2_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, vint8mf2_t v5, vint8mf2_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], <vscale x 4 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8mf2_m_ntl_PALL (vbool16_t mask, int8_t *base, ptrdiff_t bstride, vint8mf2_t v0, vint8mf2_t v1, vint8mf2_t v2, vint8mf2_t v3, vint8mf2_t v4, vint8mf2_t v5, vint8mf2_t v6, vint8mf2_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, vint8m1_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, vint8m1_t v5, vint8m1_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_i8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], <vscale x 8 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_i8m1_m_ntl_PALL (vbool8_t mask, int8_t *base, ptrdiff_t bstride, vint8m1_t v0, vint8m1_t v1, vint8m1_t v2, vint8m1_t v3, vint8m1_t v4, vint8m1_t v5, vint8m1_t v6, vint8m1_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, ptrdiff_t bstride, vint8m2_t v0, vint8m2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, ptrdiff_t bstride, vint8m2_t v0, vint8m2_t v1, vint8m2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_i8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], <vscale x 16 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_i8m2_m_ntl_PALL (vbool4_t mask, int8_t *base, ptrdiff_t bstride, vint8m2_t v0, vint8m2_t v1, vint8m2_t v2, vint8m2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_i8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv32i8.i64(<vscale x 32 x i8> [[V0:%.*]], <vscale x 32 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_i8m4_m_ntl_PALL (vbool2_t mask, int8_t *base, ptrdiff_t bstride, vint8m4_t v0, vint8m4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, vint16mf4_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, vint16mf4_t v5, vint16mf4_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_i16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], <vscale x 1 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_i16mf4_m_ntl_PALL (vbool64_t mask, int16_t *base, ptrdiff_t bstride, vint16mf4_t v0, vint16mf4_t v1, vint16mf4_t v2, vint16mf4_t v3, vint16mf4_t v4, vint16mf4_t v5, vint16mf4_t v6, vint16mf4_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, vint16mf2_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, vint16mf2_t v5, vint16mf2_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_i16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], <vscale x 2 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_i16mf2_m_ntl_PALL (vbool32_t mask, int16_t *base, ptrdiff_t bstride, vint16mf2_t v0, vint16mf2_t v1, vint16mf2_t v2, vint16mf2_t v3, vint16mf2_t v4, vint16mf2_t v5, vint16mf2_t v6, vint16mf2_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, vint16m1_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, vint16m1_t v5, vint16m1_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_i16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], <vscale x 4 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_i16m1_m_ntl_PALL (vbool16_t mask, int16_t *base, ptrdiff_t bstride, vint16m1_t v0, vint16m1_t v1, vint16m1_t v2, vint16m1_t v3, vint16m1_t v4, vint16m1_t v5, vint16m1_t v6, vint16m1_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, ptrdiff_t bstride, vint16m2_t v0, vint16m2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, ptrdiff_t bstride, vint16m2_t v0, vint16m2_t v1, vint16m2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_i16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], <vscale x 8 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_i16m2_m_ntl_PALL (vbool8_t mask, int16_t *base, ptrdiff_t bstride, vint16m2_t v0, vint16m2_t v1, vint16m2_t v2, vint16m2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_i16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv16i16.i64(<vscale x 16 x i16> [[V0:%.*]], <vscale x 16 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_i16m4_m_ntl_PALL (vbool4_t mask, int16_t *base, ptrdiff_t bstride, vint16m4_t v0, vint16m4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, vint32mf2_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, vint32mf2_t v5, vint32mf2_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_i32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], <vscale x 1 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_i32mf2_m_ntl_PALL (vbool64_t mask, int32_t *base, ptrdiff_t bstride, vint32mf2_t v0, vint32mf2_t v1, vint32mf2_t v2, vint32mf2_t v3, vint32mf2_t v4, vint32mf2_t v5, vint32mf2_t v6, vint32mf2_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, vint32m1_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, vint32m1_t v5, vint32m1_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_i32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], <vscale x 2 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_i32m1_m_ntl_PALL (vbool32_t mask, int32_t *base, ptrdiff_t bstride, vint32m1_t v0, vint32m1_t v1, vint32m1_t v2, vint32m1_t v3, vint32m1_t v4, vint32m1_t v5, vint32m1_t v6, vint32m1_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, ptrdiff_t bstride, vint32m2_t v0, vint32m2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, ptrdiff_t bstride, vint32m2_t v0, vint32m2_t v1, vint32m2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_i32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_i32m2_m_ntl_PALL (vbool16_t mask, int32_t *base, ptrdiff_t bstride, vint32m2_t v0, vint32m2_t v1, vint32m2_t v2, vint32m2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_i32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8i32.i64(<vscale x 8 x i32> [[V0:%.*]], <vscale x 8 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_i32m4_m_ntl_PALL (vbool8_t mask, int32_t *base, ptrdiff_t bstride, vint32m4_t v0, vint32m4_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, size_t vl, int domain) {
  return vssseg5e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, vint64m1_t v5, size_t vl, int domain) {
  return vssseg6e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, vint64m1_t v5, vint64m1_t v6, size_t vl, int domain) {
  return vssseg7e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e64_v_i64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], <vscale x 1 x i64> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e64_v_i64m1_m_ntl_PALL (vbool64_t mask, int64_t *base, ptrdiff_t bstride, vint64m1_t v0, vint64m1_t v1, vint64m1_t v2, vint64m1_t v3, vint64m1_t v4, vint64m1_t v5, vint64m1_t v6, vint64m1_t v7, size_t vl, int domain) {
  return vssseg8e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, ptrdiff_t bstride, vint64m2_t v0, vint64m2_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, ptrdiff_t bstride, vint64m2_t v0, vint64m2_t v1, vint64m2_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_i64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], <vscale x 2 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_i64m2_m_ntl_PALL (vbool32_t mask, int64_t *base, ptrdiff_t bstride, vint64m2_t v0, vint64m2_t v1, vint64m2_t v2, vint64m2_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_i64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i64.i64(<vscale x 4 x i64> [[V0:%.*]], <vscale x 4 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_i64m4_m_ntl_PALL (vbool16_t mask, int64_t *base, ptrdiff_t bstride, vint64m4_t v0, vint64m4_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, vuint8mf8_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, vuint8mf8_t v5, vuint8mf8_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8mf8_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i8.i64(<vscale x 1 x i8> [[V0:%.*]], <vscale x 1 x i8> [[V1:%.*]], <vscale x 1 x i8> [[V2:%.*]], <vscale x 1 x i8> [[V3:%.*]], <vscale x 1 x i8> [[V4:%.*]], <vscale x 1 x i8> [[V5:%.*]], <vscale x 1 x i8> [[V6:%.*]], <vscale x 1 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8mf8_m_ntl_PALL (vbool64_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf8_t v0, vuint8mf8_t v1, vuint8mf8_t v2, vuint8mf8_t v3, vuint8mf8_t v4, vuint8mf8_t v5, vuint8mf8_t v6, vuint8mf8_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, vuint8mf4_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, vuint8mf4_t v5, vuint8mf4_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2i8.i64(<vscale x 2 x i8> [[V0:%.*]], <vscale x 2 x i8> [[V1:%.*]], <vscale x 2 x i8> [[V2:%.*]], <vscale x 2 x i8> [[V3:%.*]], <vscale x 2 x i8> [[V4:%.*]], <vscale x 2 x i8> [[V5:%.*]], <vscale x 2 x i8> [[V6:%.*]], <vscale x 2 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8mf4_m_ntl_PALL (vbool32_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf4_t v0, vuint8mf4_t v1, vuint8mf4_t v2, vuint8mf4_t v3, vuint8mf4_t v4, vuint8mf4_t v5, vuint8mf4_t v6, vuint8mf4_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, vuint8mf2_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, vuint8mf2_t v5, vuint8mf2_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv4i8.i64(<vscale x 4 x i8> [[V0:%.*]], <vscale x 4 x i8> [[V1:%.*]], <vscale x 4 x i8> [[V2:%.*]], <vscale x 4 x i8> [[V3:%.*]], <vscale x 4 x i8> [[V4:%.*]], <vscale x 4 x i8> [[V5:%.*]], <vscale x 4 x i8> [[V6:%.*]], <vscale x 4 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8mf2_m_ntl_PALL (vbool16_t mask, uint8_t *base, ptrdiff_t bstride, vuint8mf2_t v0, vuint8mf2_t v1, vuint8mf2_t v2, vuint8mf2_t v3, vuint8mf2_t v4, vuint8mf2_t v5, vuint8mf2_t v6, vuint8mf2_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, size_t vl, int domain) {
  return vssseg5e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, vuint8m1_t v5, size_t vl, int domain) {
  return vssseg6e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, vuint8m1_t v5, vuint8m1_t v6, size_t vl, int domain) {
  return vssseg7e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e8_v_u8m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv8i8.i64(<vscale x 8 x i8> [[V0:%.*]], <vscale x 8 x i8> [[V1:%.*]], <vscale x 8 x i8> [[V2:%.*]], <vscale x 8 x i8> [[V3:%.*]], <vscale x 8 x i8> [[V4:%.*]], <vscale x 8 x i8> [[V5:%.*]], <vscale x 8 x i8> [[V6:%.*]], <vscale x 8 x i8> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e8_v_u8m1_m_ntl_PALL (vbool8_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m1_t v0, vuint8m1_t v1, vuint8m1_t v2, vuint8m1_t v3, vuint8m1_t v4, vuint8m1_t v5, vuint8m1_t v6, vuint8m1_t v7, size_t vl, int domain) {
  return vssseg8e8_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m2_t v0, vuint8m2_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e8_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e8_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m2_t v0, vuint8m2_t v1, vuint8m2_t v2, size_t vl, int domain) {
  return vssseg3e8_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e8_v_u8m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv16i8.i64(<vscale x 16 x i8> [[V0:%.*]], <vscale x 16 x i8> [[V1:%.*]], <vscale x 16 x i8> [[V2:%.*]], <vscale x 16 x i8> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e8_v_u8m2_m_ntl_PALL (vbool4_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m2_t v0, vuint8m2_t v1, vuint8m2_t v2, vuint8m2_t v3, size_t vl, int domain) {
  return vssseg4e8_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e8_v_u8m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv32i8.i64(<vscale x 32 x i8> [[V0:%.*]], <vscale x 32 x i8> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 32 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e8_v_u8m4_m_ntl_PALL (vbool2_t mask, uint8_t *base, ptrdiff_t bstride, vuint8m4_t v0, vuint8m4_t v1, size_t vl, int domain) {
  return vssseg2e8_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, vuint16mf4_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, vuint16mf4_t v5, vuint16mf4_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_u16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i16.i64(<vscale x 1 x i16> [[V0:%.*]], <vscale x 1 x i16> [[V1:%.*]], <vscale x 1 x i16> [[V2:%.*]], <vscale x 1 x i16> [[V3:%.*]], <vscale x 1 x i16> [[V4:%.*]], <vscale x 1 x i16> [[V5:%.*]], <vscale x 1 x i16> [[V6:%.*]], <vscale x 1 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_u16mf4_m_ntl_PALL (vbool64_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf4_t v0, vuint16mf4_t v1, vuint16mf4_t v2, vuint16mf4_t v3, vuint16mf4_t v4, vuint16mf4_t v5, vuint16mf4_t v6, vuint16mf4_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, vuint16mf2_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, vuint16mf2_t v5, vuint16mf2_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_u16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2i16.i64(<vscale x 2 x i16> [[V0:%.*]], <vscale x 2 x i16> [[V1:%.*]], <vscale x 2 x i16> [[V2:%.*]], <vscale x 2 x i16> [[V3:%.*]], <vscale x 2 x i16> [[V4:%.*]], <vscale x 2 x i16> [[V5:%.*]], <vscale x 2 x i16> [[V6:%.*]], <vscale x 2 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_u16mf2_m_ntl_PALL (vbool32_t mask, uint16_t *base, ptrdiff_t bstride, vuint16mf2_t v0, vuint16mf2_t v1, vuint16mf2_t v2, vuint16mf2_t v3, vuint16mf2_t v4, vuint16mf2_t v5, vuint16mf2_t v6, vuint16mf2_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, vuint16m1_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, vuint16m1_t v5, vuint16m1_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_u16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv4i16.i64(<vscale x 4 x i16> [[V0:%.*]], <vscale x 4 x i16> [[V1:%.*]], <vscale x 4 x i16> [[V2:%.*]], <vscale x 4 x i16> [[V3:%.*]], <vscale x 4 x i16> [[V4:%.*]], <vscale x 4 x i16> [[V5:%.*]], <vscale x 4 x i16> [[V6:%.*]], <vscale x 4 x i16> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_u16m1_m_ntl_PALL (vbool16_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m1_t v0, vuint16m1_t v1, vuint16m1_t v2, vuint16m1_t v3, vuint16m1_t v4, vuint16m1_t v5, vuint16m1_t v6, vuint16m1_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m2_t v0, vuint16m2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m2_t v0, vuint16m2_t v1, vuint16m2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_u16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv8i16.i64(<vscale x 8 x i16> [[V0:%.*]], <vscale x 8 x i16> [[V1:%.*]], <vscale x 8 x i16> [[V2:%.*]], <vscale x 8 x i16> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_u16m2_m_ntl_PALL (vbool8_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m2_t v0, vuint16m2_t v1, vuint16m2_t v2, vuint16m2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_u16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv16i16.i64(<vscale x 16 x i16> [[V0:%.*]], <vscale x 16 x i16> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_u16m4_m_ntl_PALL (vbool4_t mask, uint16_t *base, ptrdiff_t bstride, vuint16m4_t v0, vuint16m4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, vuint32mf2_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, vuint32mf2_t v5, vuint32mf2_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_u32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i32.i64(<vscale x 1 x i32> [[V0:%.*]], <vscale x 1 x i32> [[V1:%.*]], <vscale x 1 x i32> [[V2:%.*]], <vscale x 1 x i32> [[V3:%.*]], <vscale x 1 x i32> [[V4:%.*]], <vscale x 1 x i32> [[V5:%.*]], <vscale x 1 x i32> [[V6:%.*]], <vscale x 1 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_u32mf2_m_ntl_PALL (vbool64_t mask, uint32_t *base, ptrdiff_t bstride, vuint32mf2_t v0, vuint32mf2_t v1, vuint32mf2_t v2, vuint32mf2_t v3, vuint32mf2_t v4, vuint32mf2_t v5, vuint32mf2_t v6, vuint32mf2_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, vuint32m1_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, vuint32m1_t v5, vuint32m1_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_u32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2i32.i64(<vscale x 2 x i32> [[V0:%.*]], <vscale x 2 x i32> [[V1:%.*]], <vscale x 2 x i32> [[V2:%.*]], <vscale x 2 x i32> [[V3:%.*]], <vscale x 2 x i32> [[V4:%.*]], <vscale x 2 x i32> [[V5:%.*]], <vscale x 2 x i32> [[V6:%.*]], <vscale x 2 x i32> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_u32m1_m_ntl_PALL (vbool32_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m1_t v0, vuint32m1_t v1, vuint32m1_t v2, vuint32m1_t v3, vuint32m1_t v4, vuint32m1_t v5, vuint32m1_t v6, vuint32m1_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m2_t v0, vuint32m2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m2_t v0, vuint32m2_t v1, vuint32m2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_u32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4i32.i64(<vscale x 4 x i32> [[V0:%.*]], <vscale x 4 x i32> [[V1:%.*]], <vscale x 4 x i32> [[V2:%.*]], <vscale x 4 x i32> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_u32m2_m_ntl_PALL (vbool16_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m2_t v0, vuint32m2_t v1, vuint32m2_t v2, vuint32m2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_u32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8i32.i64(<vscale x 8 x i32> [[V0:%.*]], <vscale x 8 x i32> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_u32m4_m_ntl_PALL (vbool8_t mask, uint32_t *base, ptrdiff_t bstride, vuint32m4_t v0, vuint32m4_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, size_t vl, int domain) {
  return vssseg5e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, vuint64m1_t v5, size_t vl, int domain) {
  return vssseg6e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, vuint64m1_t v5, vuint64m1_t v6, size_t vl, int domain) {
  return vssseg7e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e64_v_u64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1i64.i64(<vscale x 1 x i64> [[V0:%.*]], <vscale x 1 x i64> [[V1:%.*]], <vscale x 1 x i64> [[V2:%.*]], <vscale x 1 x i64> [[V3:%.*]], <vscale x 1 x i64> [[V4:%.*]], <vscale x 1 x i64> [[V5:%.*]], <vscale x 1 x i64> [[V6:%.*]], <vscale x 1 x i64> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e64_v_u64m1_m_ntl_PALL (vbool64_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m1_t v0, vuint64m1_t v1, vuint64m1_t v2, vuint64m1_t v3, vuint64m1_t v4, vuint64m1_t v5, vuint64m1_t v6, vuint64m1_t v7, size_t vl, int domain) {
  return vssseg8e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m2_t v0, vuint64m2_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m2_t v0, vuint64m2_t v1, vuint64m2_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_u64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2i64.i64(<vscale x 2 x i64> [[V0:%.*]], <vscale x 2 x i64> [[V1:%.*]], <vscale x 2 x i64> [[V2:%.*]], <vscale x 2 x i64> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_u64m2_m_ntl_PALL (vbool32_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m2_t v0, vuint64m2_t v1, vuint64m2_t v2, vuint64m2_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_u64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4i64.i64(<vscale x 4 x i64> [[V0:%.*]], <vscale x 4 x i64> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_u64m4_m_ntl_PALL (vbool16_t mask, uint64_t *base, ptrdiff_t bstride, vuint64m4_t v0, vuint64m4_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], <vscale x 1 x half> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, vfloat16mf4_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], <vscale x 1 x half> [[V5:%.*]], <vscale x 1 x half> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, vfloat16mf4_t v5, vfloat16mf4_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_f16mf4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1f16.i64(<vscale x 1 x half> [[V0:%.*]], <vscale x 1 x half> [[V1:%.*]], <vscale x 1 x half> [[V2:%.*]], <vscale x 1 x half> [[V3:%.*]], <vscale x 1 x half> [[V4:%.*]], <vscale x 1 x half> [[V5:%.*]], <vscale x 1 x half> [[V6:%.*]], <vscale x 1 x half> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_f16mf4_m_ntl_PALL (vbool64_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf4_t v0, vfloat16mf4_t v1, vfloat16mf4_t v2, vfloat16mf4_t v3, vfloat16mf4_t v4, vfloat16mf4_t v5, vfloat16mf4_t v6, vfloat16mf4_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], <vscale x 2 x half> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, vfloat16mf2_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], <vscale x 2 x half> [[V5:%.*]], <vscale x 2 x half> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, vfloat16mf2_t v5, vfloat16mf2_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_f16mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2f16.i64(<vscale x 2 x half> [[V0:%.*]], <vscale x 2 x half> [[V1:%.*]], <vscale x 2 x half> [[V2:%.*]], <vscale x 2 x half> [[V3:%.*]], <vscale x 2 x half> [[V4:%.*]], <vscale x 2 x half> [[V5:%.*]], <vscale x 2 x half> [[V6:%.*]], <vscale x 2 x half> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_f16mf2_m_ntl_PALL (vbool32_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16mf2_t v0, vfloat16mf2_t v1, vfloat16mf2_t v2, vfloat16mf2_t v3, vfloat16mf2_t v4, vfloat16mf2_t v5, vfloat16mf2_t v6, vfloat16mf2_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, size_t vl, int domain) {
  return vssseg5e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], <vscale x 4 x half> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, vfloat16m1_t v5, size_t vl, int domain) {
  return vssseg6e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], <vscale x 4 x half> [[V5:%.*]], <vscale x 4 x half> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, vfloat16m1_t v5, vfloat16m1_t v6, size_t vl, int domain) {
  return vssseg7e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e16_v_f16m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv4f16.i64(<vscale x 4 x half> [[V0:%.*]], <vscale x 4 x half> [[V1:%.*]], <vscale x 4 x half> [[V2:%.*]], <vscale x 4 x half> [[V3:%.*]], <vscale x 4 x half> [[V4:%.*]], <vscale x 4 x half> [[V5:%.*]], <vscale x 4 x half> [[V6:%.*]], <vscale x 4 x half> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e16_v_f16m1_m_ntl_PALL (vbool16_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m1_t v0, vfloat16m1_t v1, vfloat16m1_t v2, vfloat16m1_t v3, vfloat16m1_t v4, vfloat16m1_t v5, vfloat16m1_t v6, vfloat16m1_t v7, size_t vl, int domain) {
  return vssseg8e16_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8f16.i64(<vscale x 8 x half> [[V0:%.*]], <vscale x 8 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m2_t v0, vfloat16m2_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e16_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv8f16.i64(<vscale x 8 x half> [[V0:%.*]], <vscale x 8 x half> [[V1:%.*]], <vscale x 8 x half> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e16_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m2_t v0, vfloat16m2_t v1, vfloat16m2_t v2, size_t vl, int domain) {
  return vssseg3e16_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e16_v_f16m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv8f16.i64(<vscale x 8 x half> [[V0:%.*]], <vscale x 8 x half> [[V1:%.*]], <vscale x 8 x half> [[V2:%.*]], <vscale x 8 x half> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e16_v_f16m2_m_ntl_PALL (vbool8_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m2_t v0, vfloat16m2_t v1, vfloat16m2_t v2, vfloat16m2_t v3, size_t vl, int domain) {
  return vssseg4e16_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e16_v_f16m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv16f16.i64(<vscale x 16 x half> [[V0:%.*]], <vscale x 16 x half> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 16 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e16_v_f16m4_m_ntl_PALL (vbool4_t mask, _Float16 *base, ptrdiff_t bstride, vfloat16m4_t v0, vfloat16m4_t v1, size_t vl, int domain) {
  return vssseg2e16_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], <vscale x 1 x float> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, vfloat32mf2_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], <vscale x 1 x float> [[V5:%.*]], <vscale x 1 x float> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, vfloat32mf2_t v5, vfloat32mf2_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_f32mf2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1f32.i64(<vscale x 1 x float> [[V0:%.*]], <vscale x 1 x float> [[V1:%.*]], <vscale x 1 x float> [[V2:%.*]], <vscale x 1 x float> [[V3:%.*]], <vscale x 1 x float> [[V4:%.*]], <vscale x 1 x float> [[V5:%.*]], <vscale x 1 x float> [[V6:%.*]], <vscale x 1 x float> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_f32mf2_m_ntl_PALL (vbool64_t mask, float *base, ptrdiff_t bstride, vfloat32mf2_t v0, vfloat32mf2_t v1, vfloat32mf2_t v2, vfloat32mf2_t v3, vfloat32mf2_t v4, vfloat32mf2_t v5, vfloat32mf2_t v6, vfloat32mf2_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, size_t vl, int domain) {
  return vssseg5e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], <vscale x 2 x float> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, vfloat32m1_t v5, size_t vl, int domain) {
  return vssseg6e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], <vscale x 2 x float> [[V5:%.*]], <vscale x 2 x float> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, vfloat32m1_t v5, vfloat32m1_t v6, size_t vl, int domain) {
  return vssseg7e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e32_v_f32m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv2f32.i64(<vscale x 2 x float> [[V0:%.*]], <vscale x 2 x float> [[V1:%.*]], <vscale x 2 x float> [[V2:%.*]], <vscale x 2 x float> [[V3:%.*]], <vscale x 2 x float> [[V4:%.*]], <vscale x 2 x float> [[V5:%.*]], <vscale x 2 x float> [[V6:%.*]], <vscale x 2 x float> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e32_v_f32m1_m_ntl_PALL (vbool32_t mask, float *base, ptrdiff_t bstride, vfloat32m1_t v0, vfloat32m1_t v1, vfloat32m1_t v2, vfloat32m1_t v3, vfloat32m1_t v4, vfloat32m1_t v5, vfloat32m1_t v6, vfloat32m1_t v7, size_t vl, int domain) {
  return vssseg8e32_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4f32.i64(<vscale x 4 x float> [[V0:%.*]], <vscale x 4 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, ptrdiff_t bstride, vfloat32m2_t v0, vfloat32m2_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e32_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv4f32.i64(<vscale x 4 x float> [[V0:%.*]], <vscale x 4 x float> [[V1:%.*]], <vscale x 4 x float> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e32_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, ptrdiff_t bstride, vfloat32m2_t v0, vfloat32m2_t v1, vfloat32m2_t v2, size_t vl, int domain) {
  return vssseg3e32_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e32_v_f32m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv4f32.i64(<vscale x 4 x float> [[V0:%.*]], <vscale x 4 x float> [[V1:%.*]], <vscale x 4 x float> [[V2:%.*]], <vscale x 4 x float> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e32_v_f32m2_m_ntl_PALL (vbool16_t mask, float *base, ptrdiff_t bstride, vfloat32m2_t v0, vfloat32m2_t v1, vfloat32m2_t v2, vfloat32m2_t v3, size_t vl, int domain) {
  return vssseg4e32_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e32_v_f32m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv8f32.i64(<vscale x 8 x float> [[V0:%.*]], <vscale x 8 x float> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 8 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e32_v_f32m4_m_ntl_PALL (vbool8_t mask, float *base, ptrdiff_t bstride, vfloat32m4_t v0, vfloat32m4_t v1, size_t vl, int domain) {
  return vssseg2e32_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg5e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg5.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg5e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, size_t vl, int domain) {
  return vssseg5e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg6e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg6.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], <vscale x 1 x double> [[V5:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg6e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, vfloat64m1_t v5, size_t vl, int domain) {
  return vssseg6e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg7e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg7.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], <vscale x 1 x double> [[V5:%.*]], <vscale x 1 x double> [[V6:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg7e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, vfloat64m1_t v5, vfloat64m1_t v6, size_t vl, int domain) {
  return vssseg7e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg8e64_v_f64m1_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg8.mask.nxv1f64.i64(<vscale x 1 x double> [[V0:%.*]], <vscale x 1 x double> [[V1:%.*]], <vscale x 1 x double> [[V2:%.*]], <vscale x 1 x double> [[V3:%.*]], <vscale x 1 x double> [[V4:%.*]], <vscale x 1 x double> [[V5:%.*]], <vscale x 1 x double> [[V6:%.*]], <vscale x 1 x double> [[V7:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 1 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg8e64_v_f64m1_m_ntl_PALL (vbool64_t mask, double *base, ptrdiff_t bstride, vfloat64m1_t v0, vfloat64m1_t v1, vfloat64m1_t v2, vfloat64m1_t v3, vfloat64m1_t v4, vfloat64m1_t v5, vfloat64m1_t v6, vfloat64m1_t v7, size_t vl, int domain) {
  return vssseg8e64_ntl(mask, base, bstride, v0, v1, v2, v3, v4, v5, v6, v7, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv2f64.i64(<vscale x 2 x double> [[V0:%.*]], <vscale x 2 x double> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, ptrdiff_t bstride, vfloat64m2_t v0, vfloat64m2_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg3e64_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg3.mask.nxv2f64.i64(<vscale x 2 x double> [[V0:%.*]], <vscale x 2 x double> [[V1:%.*]], <vscale x 2 x double> [[V2:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg3e64_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, ptrdiff_t bstride, vfloat64m2_t v0, vfloat64m2_t v1, vfloat64m2_t v2, size_t vl, int domain) {
  return vssseg3e64_ntl(mask, base, bstride, v0, v1, v2, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg4e64_v_f64m2_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg4.mask.nxv2f64.i64(<vscale x 2 x double> [[V0:%.*]], <vscale x 2 x double> [[V1:%.*]], <vscale x 2 x double> [[V2:%.*]], <vscale x 2 x double> [[V3:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg4e64_v_f64m2_m_ntl_PALL (vbool32_t mask, double *base, ptrdiff_t bstride, vfloat64m2_t v0, vfloat64m2_t v1, vfloat64m2_t v2, vfloat64m2_t v3, size_t vl, int domain) {
  return vssseg4e64_ntl(mask, base, bstride, v0, v1, v2, v3, vl, __RISCV_NTLH_ALL_PRIVATE);
}
// CHECK-RV64-LABEL: @test_vssseg2e64_v_f64m4_m_ntl_PALL(
// CHECK-RV64-NEXT:  entry:
// CHECK-RV64-NEXT:    call void @llvm.riscv.vssseg2.mask.nxv4f64.i64(<vscale x 4 x double> [[V0:%.*]], <vscale x 4 x double> [[V1:%.*]], ptr [[BASE:%.*]], i64 [[BSTRIDE:%.*]], <vscale x 4 x i1> [[MASK:%.*]], i64 [[VL:%.*]]), !nontemporal !4
// CHECK-RV64-NEXT:    ret void
//
void test_vssseg2e64_v_f64m4_m_ntl_PALL (vbool16_t mask, double *base, ptrdiff_t bstride, vfloat64m4_t v0, vfloat64m4_t v1, size_t vl, int domain) {
  return vssseg2e64_ntl(mask, base, bstride, v0, v1, vl, __RISCV_NTLH_ALL_PRIVATE);
}
