// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -no-opaque-pointers -ffreestanding -triple riscv64 -target-feature +v -target-feature +f \
// RUN:   -target-feature +d -target-feature +zfh -target-feature +experimental-zvfh \
// RUN:   -emit-llvm %s -o - | FileCheck %s

#include <riscv_vector.h>

typedef int8_t int8x8_t __attribute__((vector_size(8)));
typedef int16_t int16x4_t __attribute__((vector_size(8)));
typedef int32_t int32x2_t __attribute__((vector_size(8)));
typedef int64_t int64x1_t __attribute__((vector_size(8)));
typedef int8_t int8x16_t __attribute__((vector_size(16)));
typedef int16_t int16x8_t __attribute__((vector_size(16)));
typedef int32_t int32x4_t __attribute__((vector_size(16)));
typedef int64_t int64x2_t __attribute__((vector_size(16)));
typedef int8_t int8x32_t __attribute__((vector_size(32)));
typedef int16_t int16x16_t __attribute__((vector_size(32)));
typedef int32_t int32x8_t __attribute__((vector_size(32)));
typedef int64_t int64x4_t __attribute__((vector_size(32)));
typedef int8_t int8x64_t __attribute__((vector_size(64)));
typedef int16_t int16x32_t __attribute__((vector_size(64)));
typedef int32_t int32x16_t __attribute__((vector_size(64)));
typedef int64_t int64x8_t __attribute__((vector_size(64)));
typedef int8_t int8x4_t __attribute__((vector_size(4)));
typedef int16_t int16x2_t __attribute__((vector_size(4)));
typedef int32_t int32x1_t __attribute__((vector_size(4)));
typedef int8_t int8x2_t __attribute__((vector_size(2)));
typedef int16_t int16x1_t __attribute__((vector_size(2)));
typedef int8_t int8x1_t __attribute__((vector_size(1)));
typedef uint8_t uint8x8_t __attribute__((vector_size(8)));
typedef uint16_t uint16x4_t __attribute__((vector_size(8)));
typedef uint32_t uint32x2_t __attribute__((vector_size(8)));
typedef uint64_t uint64x1_t __attribute__((vector_size(8)));
typedef uint8_t uint8x16_t __attribute__((vector_size(16)));
typedef uint16_t uint16x8_t __attribute__((vector_size(16)));
typedef uint32_t uint32x4_t __attribute__((vector_size(16)));
typedef uint64_t uint64x2_t __attribute__((vector_size(16)));
typedef uint8_t uint8x32_t __attribute__((vector_size(32)));
typedef uint16_t uint16x16_t __attribute__((vector_size(32)));
typedef uint32_t uint32x8_t __attribute__((vector_size(32)));
typedef uint64_t uint64x4_t __attribute__((vector_size(32)));
typedef uint8_t uint8x64_t __attribute__((vector_size(64)));
typedef uint16_t uint16x32_t __attribute__((vector_size(64)));
typedef uint32_t uint32x16_t __attribute__((vector_size(64)));
typedef uint64_t uint64x8_t __attribute__((vector_size(64)));
typedef uint8_t uint8x4_t __attribute__((vector_size(4)));
typedef uint16_t uint16x2_t __attribute__((vector_size(4)));
typedef uint32_t uint32x1_t __attribute__((vector_size(4)));
typedef uint8_t uint8x2_t __attribute__((vector_size(2)));
typedef uint16_t uint16x1_t __attribute__((vector_size(2)));
typedef uint8_t uint8x1_t __attribute__((vector_size(1)));

typedef float float32x2_t __attribute__((vector_size(8)));
typedef double float64x1_t __attribute__((vector_size(8)));
typedef float float32x4_t __attribute__((vector_size(16)));
typedef double float64x2_t __attribute__((vector_size(16)));
typedef float float32x8_t __attribute__((vector_size(32)));
typedef double float64x4_t __attribute__((vector_size(32)));
typedef float float32x16_t __attribute__((vector_size(64)));
typedef double float64x8_t __attribute__((vector_size(64)));
typedef float float32x1_t __attribute__((vector_size(4)));

typedef __fp16 float16x4_t __attribute__((vector_size(8)));
typedef __fp16 float16x8_t __attribute__((vector_size(16)));
typedef __fp16 float16x16_t __attribute__((vector_size(32)));
typedef __fp16 float16x32_t __attribute__((vector_size(64)));
typedef __fp16 float16x2_t __attribute__((vector_size(4)));

// CHECK-LABEL: @test_vcast_to_fixed_64_i8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-NEXT:    store <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x i8>, <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> [[TMP0]])
// CHECK-NEXT:    store <8 x i8> [[TMP1]], <8 x i8>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_vcast_to_fixed_64_i8m1(vint8m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i16>, align 2
// CHECK-NEXT:    store <vscale x 4 x i16> [[X:%.*]], <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i16>, <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv4i16(<vscale x 4 x i16> [[TMP0]])
// CHECK-NEXT:    store <4 x i16> [[TMP1]], <4 x i16>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_vcast_to_fixed_64_i16m1(vint16m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i16m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i32>, align 4
// CHECK-NEXT:    store <vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i32>, <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv2i32(<vscale x 2 x i32> [[TMP0]])
// CHECK-NEXT:    store <2 x i32> [[TMP1]], <2 x i32>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_vcast_to_fixed_64_i32m1(vint32m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i32m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i64>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i64>, align 8
// CHECK-NEXT:    store <vscale x 1 x i64> [[X:%.*]], <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i64>, <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i64> @llvm.riscv.vcast.to.fixed.v1i64.nxv1i64(<vscale x 1 x i64> [[TMP0]])
// CHECK-NEXT:    store <1 x i64> [[TMP1]], <1 x i64>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <1 x i64>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int64x1_t test_vcast_to_fixed_64_i64m1(vint64m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i64m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i8>, align 1
// CHECK-NEXT:    store <vscale x 16 x i8> [[X:%.*]], <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 16 x i8>, <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> [[TMP0]])
// CHECK-NEXT:    store <16 x i8> [[TMP1]], <16 x i8>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int8x16_t test_vcast_to_fixed_64_i8m2(vint8m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i16>, align 2
// CHECK-NEXT:    store <vscale x 8 x i16> [[X:%.*]], <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x i16>, <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv8i16(<vscale x 8 x i16> [[TMP0]])
// CHECK-NEXT:    store <8 x i16> [[TMP1]], <8 x i16>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int16x8_t test_vcast_to_fixed_64_i16m2(vint16m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i16m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-NEXT:    store <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i32>, <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP0]])
// CHECK-NEXT:    store <4 x i32> [[TMP1]], <4 x i32>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int32x4_t test_vcast_to_fixed_64_i32m2(vint32m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i32m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i64>, align 8
// CHECK-NEXT:    store <vscale x 2 x i64> [[X:%.*]], <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i64>, <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv2i64(<vscale x 2 x i64> [[TMP0]])
// CHECK-NEXT:    store <2 x i64> [[TMP1]], <2 x i64>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int64x2_t test_vcast_to_fixed_64_i64m2(vint64m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i64m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x i8> [[X:%.*]], <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x i8>, <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv32i8(<vscale x 32 x i8> [[TMP1]])
// CHECK-NEXT:    store <32 x i8> [[TMP2]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i8>, <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <32 x i8> [[TMP3]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int8x32_t test_vcast_to_fixed_64_i8m4(vint8m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i16> [[X:%.*]], <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i16>, <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv16i16(<vscale x 16 x i16> [[TMP1]])
// CHECK-NEXT:    store <16 x i16> [[TMP2]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i16>, <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <16 x i16> [[TMP3]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int16x16_t test_vcast_to_fixed_64_i16m4(vint16m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i16m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i32> [[X:%.*]], <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i32>, <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv8i32(<vscale x 8 x i32> [[TMP1]])
// CHECK-NEXT:    store <8 x i32> [[TMP2]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i32>, <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <8 x i32> [[TMP3]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int32x8_t test_vcast_to_fixed_64_i32m4(vint32m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i32m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x i64> [[X:%.*]], <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x i64>, <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv4i64(<vscale x 4 x i64> [[TMP1]])
// CHECK-NEXT:    store <4 x i64> [[TMP2]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i64>, <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <4 x i64> [[TMP3]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int64x4_t test_vcast_to_fixed_64_i64m4(vint64m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i64m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 64 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 64 x i8> [[X:%.*]], <vscale x 64 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 64 x i8>, <vscale x 64 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv64i8(<vscale x 64 x i8> [[TMP1]])
// CHECK-NEXT:    store <64 x i8> [[TMP2]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <64 x i8>, <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <64 x i8> [[TMP3]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int8x64_t test_vcast_to_fixed_64_i8m8(vint8m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x i16> [[X:%.*]], <vscale x 32 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x i16>, <vscale x 32 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv32i16(<vscale x 32 x i16> [[TMP1]])
// CHECK-NEXT:    store <32 x i16> [[TMP2]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i16>, <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <32 x i16> [[TMP3]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int16x32_t test_vcast_to_fixed_64_i16m8(vint16m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i16m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i32> [[X:%.*]], <vscale x 16 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i32>, <vscale x 16 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv16i32(<vscale x 16 x i32> [[TMP1]])
// CHECK-NEXT:    store <16 x i32> [[TMP2]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <16 x i32> [[TMP3]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int32x16_t test_vcast_to_fixed_64_i32m8(vint32m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i32m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i64> [[X:%.*]], <vscale x 8 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i64>, <vscale x 8 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv8i64(<vscale x 8 x i64> [[TMP1]])
// CHECK-NEXT:    store <8 x i64> [[TMP2]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i64>, <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <8 x i64> [[TMP3]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int64x8_t test_vcast_to_fixed_64_i64m8(vint64m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i64m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 4 x i8> [[X:%.*]], <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i8>, <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv4i8(<vscale x 4 x i8> [[TMP0]])
// CHECK-NEXT:    store <4 x i8> [[TMP1]], <4 x i8>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int8x4_t test_vcast_to_fixed_64_i8mf2(vint8mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i16>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x i16> [[X:%.*]], <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i16>, <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv2i16(<vscale x 2 x i16> [[TMP0]])
// CHECK-NEXT:    store <2 x i16> [[TMP1]], <2 x i16>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int16x2_t test_vcast_to_fixed_64_i16mf2(vint16mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i16mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i32>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i32>, align 4
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i32> [[X:%.*]], <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i32>, <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i32> @llvm.riscv.vcast.to.fixed.v1i32.nxv1i32(<vscale x 1 x i32> [[TMP0]])
// CHECK-NEXT:    store <1 x i32> [[TMP1]], <1 x i32>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x i32>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int32x1_t test_vcast_to_fixed_64_i32mf2(vint32mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i32mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x i8> [[X:%.*]], <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i8>, <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv2i8(<vscale x 2 x i8> [[TMP0]])
// CHECK-NEXT:    store <2 x i8> [[TMP1]], <2 x i8>* [[RETVAL]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 2 [[TMP3]], i64 2, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int8x2_t test_vcast_to_fixed_64_i8mf4(vint8mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i16>, align 2
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i16>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i16> [[X:%.*]], <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i16>, <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i16> @llvm.riscv.vcast.to.fixed.v1i16.nxv1i16(<vscale x 1 x i16> [[TMP0]])
// CHECK-NEXT:    store <1 x i16> [[TMP1]], <1 x i16>* [[RETVAL]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x i16>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 2 [[TMP3]], i64 2, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int16x1_t test_vcast_to_fixed_64_i16mf4(vint16mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i16mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_i8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i8>, align 1
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i8> [[X:%.*]], <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i8>, <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i8> @llvm.riscv.vcast.to.fixed.v1i8.nxv1i8(<vscale x 1 x i8> [[TMP0]])
// CHECK-NEXT:    store <1 x i8> [[TMP1]], <1 x i8>* [[RETVAL]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 1 [[TMP3]], i64 1, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int8x1_t test_vcast_to_fixed_64_i8mf8(vint8mf8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_i8mf8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-NEXT:    store <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x i8>, <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv8i8(<vscale x 8 x i8> [[TMP0]])
// CHECK-NEXT:    store <8 x i8> [[TMP1]], <8 x i8>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_vcast_to_fixed_64_u8m1(vuint8m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i16>, align 2
// CHECK-NEXT:    store <vscale x 4 x i16> [[X:%.*]], <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i16>, <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv4i16(<vscale x 4 x i16> [[TMP0]])
// CHECK-NEXT:    store <4 x i16> [[TMP1]], <4 x i16>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_vcast_to_fixed_64_u16m1(vuint16m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u16m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i32>, align 4
// CHECK-NEXT:    store <vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i32>, <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv2i32(<vscale x 2 x i32> [[TMP0]])
// CHECK-NEXT:    store <2 x i32> [[TMP1]], <2 x i32>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_vcast_to_fixed_64_u32m1(vuint32m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u32m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i64>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i64>, align 8
// CHECK-NEXT:    store <vscale x 1 x i64> [[X:%.*]], <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i64>, <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i64> @llvm.riscv.vcast.to.fixed.v1i64.nxv1i64(<vscale x 1 x i64> [[TMP0]])
// CHECK-NEXT:    store <1 x i64> [[TMP1]], <1 x i64>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <1 x i64>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint64x1_t test_vcast_to_fixed_64_u64m1(vuint64m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u64m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i8>, align 1
// CHECK-NEXT:    store <vscale x 16 x i8> [[X:%.*]], <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 16 x i8>, <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv16i8(<vscale x 16 x i8> [[TMP0]])
// CHECK-NEXT:    store <16 x i8> [[TMP1]], <16 x i8>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint8x16_t test_vcast_to_fixed_64_u8m2(vuint8m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i16>, align 2
// CHECK-NEXT:    store <vscale x 8 x i16> [[X:%.*]], <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x i16>, <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv8i16(<vscale x 8 x i16> [[TMP0]])
// CHECK-NEXT:    store <8 x i16> [[TMP1]], <8 x i16>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint16x8_t test_vcast_to_fixed_64_u16m2(vuint16m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u16m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-NEXT:    store <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i32>, <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP0]])
// CHECK-NEXT:    store <4 x i32> [[TMP1]], <4 x i32>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint32x4_t test_vcast_to_fixed_64_u32m2(vuint32m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u32m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i64>, align 8
// CHECK-NEXT:    store <vscale x 2 x i64> [[X:%.*]], <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i64>, <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv2i64(<vscale x 2 x i64> [[TMP0]])
// CHECK-NEXT:    store <2 x i64> [[TMP1]], <2 x i64>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint64x2_t test_vcast_to_fixed_64_u64m2(vuint64m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u64m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x i8> [[X:%.*]], <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x i8>, <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv32i8(<vscale x 32 x i8> [[TMP1]])
// CHECK-NEXT:    store <32 x i8> [[TMP2]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i8>, <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <32 x i8> [[TMP3]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint8x32_t test_vcast_to_fixed_64_u8m4(vuint8m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i16> [[X:%.*]], <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i16>, <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv16i16(<vscale x 16 x i16> [[TMP1]])
// CHECK-NEXT:    store <16 x i16> [[TMP2]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i16>, <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <16 x i16> [[TMP3]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint16x16_t test_vcast_to_fixed_64_u16m4(vuint16m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u16m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i32> [[X:%.*]], <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i32>, <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv8i32(<vscale x 8 x i32> [[TMP1]])
// CHECK-NEXT:    store <8 x i32> [[TMP2]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i32>, <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <8 x i32> [[TMP3]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint32x8_t test_vcast_to_fixed_64_u32m4(vuint32m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u32m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x i64> [[X:%.*]], <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x i64>, <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv4i64(<vscale x 4 x i64> [[TMP1]])
// CHECK-NEXT:    store <4 x i64> [[TMP2]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i64>, <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <4 x i64> [[TMP3]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint64x4_t test_vcast_to_fixed_64_u64m4(vuint64m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u64m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 64 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 64 x i8> [[X:%.*]], <vscale x 64 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 64 x i8>, <vscale x 64 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv64i8(<vscale x 64 x i8> [[TMP1]])
// CHECK-NEXT:    store <64 x i8> [[TMP2]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <64 x i8>, <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <64 x i8> [[TMP3]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint8x64_t test_vcast_to_fixed_64_u8m8(vuint8m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x i16> [[X:%.*]], <vscale x 32 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x i16>, <vscale x 32 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv32i16(<vscale x 32 x i16> [[TMP1]])
// CHECK-NEXT:    store <32 x i16> [[TMP2]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i16>, <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <32 x i16> [[TMP3]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint16x32_t test_vcast_to_fixed_64_u16m8(vuint16m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u16m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i32> [[X:%.*]], <vscale x 16 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i32>, <vscale x 16 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv16i32(<vscale x 16 x i32> [[TMP1]])
// CHECK-NEXT:    store <16 x i32> [[TMP2]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <16 x i32> [[TMP3]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint32x16_t test_vcast_to_fixed_64_u32m8(vuint32m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u32m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i64> [[X:%.*]], <vscale x 8 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i64>, <vscale x 8 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv8i64(<vscale x 8 x i64> [[TMP1]])
// CHECK-NEXT:    store <8 x i64> [[TMP2]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i64>, <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <8 x i64> [[TMP3]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint64x8_t test_vcast_to_fixed_64_u64m8(vuint64m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u64m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 4 x i8> [[X:%.*]], <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i8>, <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv4i8(<vscale x 4 x i8> [[TMP0]])
// CHECK-NEXT:    store <4 x i8> [[TMP1]], <4 x i8>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint8x4_t test_vcast_to_fixed_64_u8mf2(vuint8mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i16>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x i16> [[X:%.*]], <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i16>, <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv2i16(<vscale x 2 x i16> [[TMP0]])
// CHECK-NEXT:    store <2 x i16> [[TMP1]], <2 x i16>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint16x2_t test_vcast_to_fixed_64_u16mf2(vuint16mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u16mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i32>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i32>, align 4
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i32> [[X:%.*]], <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i32>, <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i32> @llvm.riscv.vcast.to.fixed.v1i32.nxv1i32(<vscale x 1 x i32> [[TMP0]])
// CHECK-NEXT:    store <1 x i32> [[TMP1]], <1 x i32>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x i32>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint32x1_t test_vcast_to_fixed_64_u32mf2(vuint32mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u32mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x i8> [[X:%.*]], <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i8>, <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv2i8(<vscale x 2 x i8> [[TMP0]])
// CHECK-NEXT:    store <2 x i8> [[TMP1]], <2 x i8>* [[RETVAL]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 2 [[TMP3]], i64 2, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint8x2_t test_vcast_to_fixed_64_u8mf4(vuint8mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i16>, align 2
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i16>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i16> [[X:%.*]], <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i16>, <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i16> @llvm.riscv.vcast.to.fixed.v1i16.nxv1i16(<vscale x 1 x i16> [[TMP0]])
// CHECK-NEXT:    store <1 x i16> [[TMP1]], <1 x i16>* [[RETVAL]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x i16>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 2 [[TMP3]], i64 2, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint16x1_t test_vcast_to_fixed_64_u16mf4(vuint16mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u16mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x i8>, align 1
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i8> [[X:%.*]], <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i8>, <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x i8> @llvm.riscv.vcast.to.fixed.v1i8.nxv1i8(<vscale x 1 x i8> [[TMP0]])
// CHECK-NEXT:    store <1 x i8> [[TMP1]], <1 x i8>* [[RETVAL]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 1 [[TMP3]], i64 1, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint8x1_t test_vcast_to_fixed_64_u8mf8(vuint8mf8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_u8mf8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i8>, <8 x i8>* [[X]], align 8
// CHECK-NEXT:    store <8 x i8> [[X1]], <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i8>, <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP2]]
//
vint8m1_t test_vcast_from_fixed_64_i8m1(int8x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i16>, <4 x i16>* [[X]], align 8
// CHECK-NEXT:    store <4 x i16> [[X1]], <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v4i16(<4 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP2]]
//
vint16m1_t test_vcast_from_fixed_64_i16m1(int16x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i16m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i32>, <2 x i32>* [[X]], align 8
// CHECK-NEXT:    store <2 x i32> [[X1]], <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v2i32(<2 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP2]]
//
vint32m1_t test_vcast_from_fixed_64_i32m1(int32x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i32m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i64>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i64>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i64>, <1 x i64>* [[X]], align 8
// CHECK-NEXT:    store <1 x i64> [[X1]], <1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <1 x i64>, <1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v1i64(<1 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP2]]
//
vint64m1_t test_vcast_from_fixed_64_i64m1(int64x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i64m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <16 x i8>, <16 x i8>* [[X]], align 16
// CHECK-NEXT:    store <16 x i8> [[X1]], <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP2]]
//
vint8m2_t test_vcast_from_fixed_64_i8m2(int8x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i16>, <8 x i16>* [[X]], align 16
// CHECK-NEXT:    store <8 x i16> [[X1]], <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v8i16(<8 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP2]]
//
vint16m2_t test_vcast_from_fixed_64_i16m2(int16x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i16m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i32>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i32>, <4 x i32>* [[X]], align 16
// CHECK-NEXT:    store <4 x i32> [[X1]], <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
//
vint32m2_t test_vcast_from_fixed_64_i32m2(int32x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i32m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i64>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i64>, <2 x i64>* [[X]], align 16
// CHECK-NEXT:    store <2 x i64> [[X1]], <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i64>, <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v2i64(<2 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP2]]
//
vint64m2_t test_vcast_from_fixed_64_i64m2(int64x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i64m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i8>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <32 x i8>, <32 x i8>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <32 x i8> [[X]], <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i8>, <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v32i8(<32 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP2]]
//
vint8m4_t test_vcast_from_fixed_64_i8m4(int8x32_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <16 x i16>, <16 x i16>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <16 x i16> [[X]], <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i16>, <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v16i16(<16 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP2]]
//
vint16m4_t test_vcast_from_fixed_64_i16m4(int16x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i16m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <8 x i32>, <8 x i32>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <8 x i32> [[X]], <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v8i32(<8 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP2]]
//
vint32m4_t test_vcast_from_fixed_64_i32m4(int32x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i32m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <4 x i64>, <4 x i64>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <4 x i64> [[X]], <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i64>, <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v4i64(<4 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP2]]
//
vint64m4_t test_vcast_from_fixed_64_i64m4(int64x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i64m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <64 x i8>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <64 x i8>, <64 x i8>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <64 x i8> [[X]], <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x i8>, <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vcast.from.fixed.nxv64i8.v64i8(<64 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP2]]
//
vint8m8_t test_vcast_from_fixed_64_i8m8(int8x64_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i16>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <32 x i16>, <32 x i16>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <32 x i16> [[X]], <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vcast.from.fixed.nxv32i16.v32i16(<32 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP2]]
//
vint16m8_t test_vcast_from_fixed_64_i16m8(int16x32_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i16m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <16 x i32> [[X]], <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vcast.from.fixed.nxv16i32.v16i32(<16 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP2]]
//
vint32m8_t test_vcast_from_fixed_64_i32m8(int32x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i32m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <8 x i64>, <8 x i64>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <8 x i64> [[X]], <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i64>, <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vcast.from.fixed.nxv8i64.v8i64(<8 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP2]]
//
vint64m8_t test_vcast_from_fixed_64_i64m8(int64x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i64m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i8>, <4 x i8>* [[X]], align 4
// CHECK-NEXT:    store <4 x i8> [[X1]], <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i8>, <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v4i8(<4 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP3]]
//
vint8mf2_t test_vcast_from_fixed_64_i8mf2(int8x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i16>, <2 x i16>* [[X]], align 4
// CHECK-NEXT:    store <2 x i16> [[X1]], <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i16>, <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v2i16(<2 x i16> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP3]]
//
vint16mf2_t test_vcast_from_fixed_64_i16mf2(int16x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i16mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i32>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i32>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i32>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i32>, <1 x i32>* [[X]], align 4
// CHECK-NEXT:    store <1 x i32> [[X1]], <1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <1 x i32>, <1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v1i32(<1 x i32> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP3]]
//
vint32mf2_t test_vcast_from_fixed_64_i32mf2(int32x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i32mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 [[TMP0]], i8* align 8 [[TMP1]], i64 2, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i8>, <2 x i8>* [[X]], align 2
// CHECK-NEXT:    store <2 x i8> [[X1]], <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i8>, <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v2i8(<2 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP3]]
//
vint8mf4_t test_vcast_from_fixed_64_i8mf4(int8x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i16>, align 2
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i16>, align 2
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i16>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 [[TMP0]], i8* align 8 [[TMP1]], i64 2, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i16>, <1 x i16>* [[X]], align 2
// CHECK-NEXT:    store <1 x i16> [[X1]], <1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load <1 x i16>, <1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v1i16(<1 x i16> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP3]]
//
vint16mf4_t test_vcast_from_fixed_64_i16mf4(int16x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i16mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_i8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i8>, align 1
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i8>, align 1
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 1 [[TMP0]], i8* align 8 [[TMP1]], i64 1, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i8>, <1 x i8>* [[X]], align 1
// CHECK-NEXT:    store <1 x i8> [[X1]], <1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = load <1 x i8>, <1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v1i8(<1 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP3]]
//
vint8mf8_t test_vcast_from_fixed_64_i8mf8(int8x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_i8mf8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i8>, <8 x i8>* [[X]], align 8
// CHECK-NEXT:    store <8 x i8> [[X1]], <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i8>, <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v8i8(<8 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP2]]
//
vuint8m1_t test_vcast_from_fixed_64_u8m1(uint8x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i16>, <4 x i16>* [[X]], align 8
// CHECK-NEXT:    store <4 x i16> [[X1]], <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v4i16(<4 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP2]]
//
vuint16m1_t test_vcast_from_fixed_64_u16m1(uint16x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u16m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i32>, <2 x i32>* [[X]], align 8
// CHECK-NEXT:    store <2 x i32> [[X1]], <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v2i32(<2 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP2]]
//
vuint32m1_t test_vcast_from_fixed_64_u32m1(uint32x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u32m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i64>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i64>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i64>, <1 x i64>* [[X]], align 8
// CHECK-NEXT:    store <1 x i64> [[X1]], <1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <1 x i64>, <1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v1i64(<1 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP2]]
//
vuint64m1_t test_vcast_from_fixed_64_u64m1(uint64x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u64m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <16 x i8>, <16 x i8>* [[X]], align 16
// CHECK-NEXT:    store <16 x i8> [[X1]], <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v16i8(<16 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP2]]
//
vuint8m2_t test_vcast_from_fixed_64_u8m2(uint8x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i16>, <8 x i16>* [[X]], align 16
// CHECK-NEXT:    store <8 x i16> [[X1]], <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v8i16(<8 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP2]]
//
vuint16m2_t test_vcast_from_fixed_64_u16m2(uint16x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u16m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i32>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i32>, <4 x i32>* [[X]], align 16
// CHECK-NEXT:    store <4 x i32> [[X1]], <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v4i32(<4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
//
vuint32m2_t test_vcast_from_fixed_64_u32m2(uint32x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u32m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i64>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i64>, <2 x i64>* [[X]], align 16
// CHECK-NEXT:    store <2 x i64> [[X1]], <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i64>, <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v2i64(<2 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP2]]
//
vuint64m2_t test_vcast_from_fixed_64_u64m2(uint64x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u64m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i8>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <32 x i8>, <32 x i8>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <32 x i8> [[X]], <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i8>, <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v32i8(<32 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP2]]
//
vuint8m4_t test_vcast_from_fixed_64_u8m4(uint8x32_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <16 x i16>, <16 x i16>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <16 x i16> [[X]], <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i16>, <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v16i16(<16 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP2]]
//
vuint16m4_t test_vcast_from_fixed_64_u16m4(uint16x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u16m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <8 x i32>, <8 x i32>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <8 x i32> [[X]], <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v8i32(<8 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP2]]
//
vuint32m4_t test_vcast_from_fixed_64_u32m4(uint32x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u32m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <4 x i64>, <4 x i64>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <4 x i64> [[X]], <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i64>, <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v4i64(<4 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP2]]
//
vuint64m4_t test_vcast_from_fixed_64_u64m4(uint64x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u64m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <64 x i8>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <64 x i8>, <64 x i8>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <64 x i8> [[X]], <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x i8>, <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vcast.from.fixed.nxv64i8.v64i8(<64 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 64 x i8> [[TMP2]]
//
vuint8m8_t test_vcast_from_fixed_64_u8m8(uint8x64_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i16>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <32 x i16>, <32 x i16>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <32 x i16> [[X]], <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vcast.from.fixed.nxv32i16.v32i16(<32 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x i16> [[TMP2]]
//
vuint16m8_t test_vcast_from_fixed_64_u16m8(uint16x32_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u16m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <16 x i32> [[X]], <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vcast.from.fixed.nxv16i32.v16i32(<16 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i32> [[TMP2]]
//
vuint32m8_t test_vcast_from_fixed_64_u32m8(uint32x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u32m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <8 x i64>, <8 x i64>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <8 x i64> [[X]], <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i64>, <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vcast.from.fixed.nxv8i64.v8i64(<8 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i64> [[TMP2]]
//
vuint64m8_t test_vcast_from_fixed_64_u64m8(uint64x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u64m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i8>, <4 x i8>* [[X]], align 4
// CHECK-NEXT:    store <4 x i8> [[X1]], <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i8>, <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v4i8(<4 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP3]]
//
vuint8mf2_t test_vcast_from_fixed_64_u8mf2(uint8x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i16>, <2 x i16>* [[X]], align 4
// CHECK-NEXT:    store <2 x i16> [[X1]], <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i16>, <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v2i16(<2 x i16> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP3]]
//
vuint16mf2_t test_vcast_from_fixed_64_u16mf2(uint16x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u16mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i32>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i32>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i32>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i32>, <1 x i32>* [[X]], align 4
// CHECK-NEXT:    store <1 x i32> [[X1]], <1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <1 x i32>, <1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v1i32(<1 x i32> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP3]]
//
vuint32mf2_t test_vcast_from_fixed_64_u32mf2(uint32x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u32mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 [[TMP0]], i8* align 8 [[TMP1]], i64 2, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i8>, <2 x i8>* [[X]], align 2
// CHECK-NEXT:    store <2 x i8> [[X1]], <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i8>, <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v2i8(<2 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP3]]
//
vuint8mf4_t test_vcast_from_fixed_64_u8mf4(uint8x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i16>, align 2
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i16>, align 2
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i16>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 [[TMP0]], i8* align 8 [[TMP1]], i64 2, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i16>, <1 x i16>* [[X]], align 2
// CHECK-NEXT:    store <1 x i16> [[X1]], <1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load <1 x i16>, <1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v1i16(<1 x i16> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP3]]
//
vuint16mf4_t test_vcast_from_fixed_64_u16mf4(uint16x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u16mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x i8>, align 1
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x i8>, align 1
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 1 [[TMP0]], i8* align 8 [[TMP1]], i64 1, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <1 x i8>, <1 x i8>* [[X]], align 1
// CHECK-NEXT:    store <1 x i8> [[X1]], <1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = load <1 x i8>, <1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v1i8(<1 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP3]]
//
vuint8mf8_t test_vcast_from_fixed_64_u8mf8(uint8x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_u8mf8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x float>, align 4
// CHECK-NEXT:    store <vscale x 2 x float> [[X:%.*]], <vscale x 2 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x float>, <vscale x 2 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv2f32(<vscale x 2 x float> [[TMP0]])
// CHECK-NEXT:    store <2 x float> [[TMP1]], <2 x float>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x float>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
float32x2_t test_vcast_to_fixed_64_f32m1(vfloat32m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f32m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x double>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x double>, align 8
// CHECK-NEXT:    store <vscale x 1 x double> [[X:%.*]], <vscale x 1 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x double>, <vscale x 1 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x double> @llvm.riscv.vcast.to.fixed.v1f64.nxv1f64(<vscale x 1 x double> [[TMP0]])
// CHECK-NEXT:    store <1 x double> [[TMP1]], <1 x double>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <1 x double>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
float64x1_t test_vcast_to_fixed_64_f64m1(vfloat64m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f64m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x float>, align 4
// CHECK-NEXT:    store <vscale x 4 x float> [[X:%.*]], <vscale x 4 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x float>, <vscale x 4 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv4f32(<vscale x 4 x float> [[TMP0]])
// CHECK-NEXT:    store <4 x float> [[TMP1]], <4 x float>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x float>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
float32x4_t test_vcast_to_fixed_64_f32m2(vfloat32m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f32m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x double>, align 8
// CHECK-NEXT:    store <vscale x 2 x double> [[X:%.*]], <vscale x 2 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x double>, <vscale x 2 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv2f64(<vscale x 2 x double> [[TMP0]])
// CHECK-NEXT:    store <2 x double> [[TMP1]], <2 x double>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x double>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
float64x2_t test_vcast_to_fixed_64_f64m2(vfloat64m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f64m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x float>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x float> [[X:%.*]], <vscale x 8 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x float>, <vscale x 8 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x float> @llvm.riscv.vcast.to.fixed.v8f32.nxv8f32(<vscale x 8 x float> [[TMP1]])
// CHECK-NEXT:    store <8 x float> [[TMP2]], <8 x float>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x float>, <8 x float>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <8 x float> [[TMP3]], <8 x float>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
float32x8_t test_vcast_to_fixed_64_f32m4(vfloat32m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f32m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x double>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x double>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x double> [[X:%.*]], <vscale x 4 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x double>, <vscale x 4 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x double> @llvm.riscv.vcast.to.fixed.v4f64.nxv4f64(<vscale x 4 x double> [[TMP1]])
// CHECK-NEXT:    store <4 x double> [[TMP2]], <4 x double>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x double>, <4 x double>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <4 x double> [[TMP3]], <4 x double>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
float64x4_t test_vcast_to_fixed_64_f64m4(vfloat64m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f64m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x float>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x float> [[X:%.*]], <vscale x 16 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x float>, <vscale x 16 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x float> @llvm.riscv.vcast.to.fixed.v16f32.nxv16f32(<vscale x 16 x float> [[TMP1]])
// CHECK-NEXT:    store <16 x float> [[TMP2]], <16 x float>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x float>, <16 x float>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <16 x float> [[TMP3]], <16 x float>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
float32x16_t test_vcast_to_fixed_64_f32m8(vfloat32m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f32m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x double>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x double>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x double> [[X:%.*]], <vscale x 8 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x double>, <vscale x 8 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x double> @llvm.riscv.vcast.to.fixed.v8f64.nxv8f64(<vscale x 8 x double> [[TMP1]])
// CHECK-NEXT:    store <8 x double> [[TMP2]], <8 x double>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x double>, <8 x double>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <8 x double> [[TMP3]], <8 x double>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
float64x8_t test_vcast_to_fixed_64_f64m8(vfloat64m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f64m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <1 x float>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x float>, align 4
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x float> [[X:%.*]], <vscale x 1 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x float>, <vscale x 1 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <1 x float> @llvm.riscv.vcast.to.fixed.v1f32.nxv1f32(<vscale x 1 x float> [[TMP0]])
// CHECK-NEXT:    store <1 x float> [[TMP1]], <1 x float>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <1 x float>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
float32x1_t test_vcast_to_fixed_64_f32mf2(vfloat32mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f32mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x half>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x half>, align 2
// CHECK-NEXT:    store <vscale x 4 x half> [[X:%.*]], <vscale x 4 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x half>, <vscale x 4 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x half> @llvm.riscv.vcast.to.fixed.v4f16.nxv4f16(<vscale x 4 x half> [[TMP0]])
// CHECK-NEXT:    store <4 x half> [[TMP1]], <4 x half>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x half>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
float16x4_t test_vcast_to_fixed_64_f16m1(vfloat16m1_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f16m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x half>, align 2
// CHECK-NEXT:    store <vscale x 8 x half> [[X:%.*]], <vscale x 8 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x half>, <vscale x 8 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv8f16(<vscale x 8 x half> [[TMP0]])
// CHECK-NEXT:    store <8 x half> [[TMP1]], <8 x half>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x half>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
float16x8_t test_vcast_to_fixed_64_f16m2(vfloat16m2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f16m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x half>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x half> [[X:%.*]], <vscale x 16 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x half>, <vscale x 16 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x half> @llvm.riscv.vcast.to.fixed.v16f16.nxv16f16(<vscale x 16 x half> [[TMP1]])
// CHECK-NEXT:    store <16 x half> [[TMP2]], <16 x half>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x half>, <16 x half>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <16 x half> [[TMP3]], <16 x half>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
float16x16_t test_vcast_to_fixed_64_f16m4(vfloat16m4_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f16m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x half>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x half> [[X:%.*]], <vscale x 32 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x half>, <vscale x 32 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x half> @llvm.riscv.vcast.to.fixed.v32f16.nxv32f16(<vscale x 32 x half> [[TMP1]])
// CHECK-NEXT:    store <32 x half> [[TMP2]], <32 x half>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x half>, <32 x half>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <32 x half> [[TMP3]], <32 x half>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
float16x32_t test_vcast_to_fixed_64_f16m8(vfloat16m8_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f16m8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_64_f16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x half>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x half>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x half> [[X:%.*]], <vscale x 2 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x half>, <vscale x 2 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x half> @llvm.riscv.vcast.to.fixed.v2f16.nxv2f16(<vscale x 2 x half> [[TMP0]])
// CHECK-NEXT:    store <2 x half> [[TMP1]], <2 x half>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x half>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
float16x2_t test_vcast_to_fixed_64_f16mf2(vfloat16mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_64_f16mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x float>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <2 x float>, <2 x float>* [[X]], align 8
// CHECK-NEXT:    store <2 x float> [[X1]], <2 x float>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x float>, <2 x float>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.riscv.vcast.from.fixed.nxv2f32.v2f32(<2 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP2]]
//
vfloat32m1_t test_vcast_from_fixed_64_f32m1(float32x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f32m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <1 x double>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <1 x double>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <1 x double>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <1 x double>, <1 x double>* [[X]], align 8
// CHECK-NEXT:    store <1 x double> [[X1]], <1 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <1 x double>, <1 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x double> @llvm.riscv.vcast.from.fixed.nxv1f64.v1f64(<1 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x double> [[TMP2]]
//
vfloat64m1_t test_vcast_from_fixed_64_f64m1(float64x1_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f64m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <4 x float>, <4 x float>* [[X]], align 16
// CHECK-NEXT:    store <4 x float> [[X1]], <4 x float>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, <4 x float>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v4f32(<4 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
//
vfloat32m2_t test_vcast_from_fixed_64_f32m2(float32x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f32m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x double>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <2 x double>, <2 x double>* [[X]], align 16
// CHECK-NEXT:    store <2 x double> [[X1]], <2 x double>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x double>, <2 x double>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x double> @llvm.riscv.vcast.from.fixed.nxv2f64.v2f64(<2 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x double> [[TMP2]]
//
vfloat64m2_t test_vcast_from_fixed_64_f64m2(float64x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f64m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x float>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <8 x float>, <8 x float>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <8 x float> [[X]], <8 x float>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x float>, <8 x float>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x float> @llvm.riscv.vcast.from.fixed.nxv8f32.v8f32(<8 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP2]]
//
vfloat32m4_t test_vcast_from_fixed_64_f32m4(float32x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f32m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x double>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <4 x double>, <4 x double>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <4 x double> [[X]], <4 x double>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x double>, <4 x double>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x double> @llvm.riscv.vcast.from.fixed.nxv4f64.v4f64(<4 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x double> [[TMP2]]
//
vfloat64m4_t test_vcast_from_fixed_64_f64m4(float64x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f64m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f32m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <16 x float>, <16 x float>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <16 x float> [[X]], <16 x float>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, <16 x float>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x float> @llvm.riscv.vcast.from.fixed.nxv16f32.v16f32(<16 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x float> [[TMP2]]
//
vfloat32m8_t test_vcast_from_fixed_64_f32m8(float32x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f32m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f64m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x double>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <8 x double>, <8 x double>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <8 x double> [[X]], <8 x double>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x double>, <8 x double>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x double> @llvm.riscv.vcast.from.fixed.nxv8f64.v8f64(<8 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x double> [[TMP2]]
//
vfloat64m8_t test_vcast_from_fixed_64_f64m8(float64x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f64m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x half>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x half>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x half>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <4 x half>, <4 x half>* [[X]], align 8
// CHECK-NEXT:    store <4 x half> [[X1]], <4 x half>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x half>, <4 x half>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x half> @llvm.riscv.vcast.from.fixed.nxv4f16.v4f16(<4 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP2]]
//
vfloat16m1_t test_vcast_from_fixed_64_f16m1(float16x4_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f16m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <8 x half>, <8 x half>* [[X]], align 16
// CHECK-NEXT:    store <8 x half> [[X1]], <8 x half>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x half>, <8 x half>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x half> @llvm.riscv.vcast.from.fixed.nxv8f16.v8f16(<8 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP2]]
//
vfloat16m2_t test_vcast_from_fixed_64_f16m2(float16x8_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f16m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x half>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <16 x half>, <16 x half>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <16 x half> [[X]], <16 x half>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x half>, <16 x half>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x half> @llvm.riscv.vcast.from.fixed.nxv16f16.v16f16(<16 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x half> [[TMP2]]
//
vfloat16m4_t test_vcast_from_fixed_64_f16m4(float16x16_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f16m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f16m8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x half>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <32 x half>, <32 x half>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <32 x half> [[X]], <32 x half>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x half>, <32 x half>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x half> @llvm.riscv.vcast.from.fixed.nxv32f16.v32f16(<32 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x half> [[TMP2]]
//
vfloat16m8_t test_vcast_from_fixed_64_f16m8(float16x32_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f16m8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_64_f16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x half>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x half>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x half>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x half>, <2 x half>* [[X]], align 4
// CHECK-NEXT:    store <2 x half> [[X1]], <2 x half>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x half>, <2 x half>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x half> @llvm.riscv.vcast.from.fixed.nxv2f16.v2f16(<2 x half> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x half> [[TMP3]]
//
vfloat16mf2_t test_vcast_from_fixed_64_f16mf2(float16x2_t x) {
  return __builtin_rvv_vcast_from_fixed_64_f16mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i8>, align 1
// CHECK-NEXT:    store <vscale x 4 x i8> [[X:%.*]], <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i8>, <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv4i8(<vscale x 4 x i8> [[TMP0]])
// CHECK-NEXT:    store <8 x i8> [[TMP1]], <8 x i8>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int8x8_t test_vcast_to_fixed_128_i8mf2(vint8mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i8mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i16>, align 2
// CHECK-NEXT:    store <vscale x 2 x i16> [[X:%.*]], <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i16>, <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv2i16(<vscale x 2 x i16> [[TMP0]])
// CHECK-NEXT:    store <4 x i16> [[TMP1]], <4 x i16>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int16x4_t test_vcast_to_fixed_128_i16mf2(vint16mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i16mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i32>, align 4
// CHECK-NEXT:    store <vscale x 1 x i32> [[X:%.*]], <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i32>, <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv1i32(<vscale x 1 x i32> [[TMP0]])
// CHECK-NEXT:    store <2 x i32> [[TMP1]], <2 x i32>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
int32x2_t test_vcast_to_fixed_128_i32mf2(vint32mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i32mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-NEXT:    store <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x i8>, <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv8i8(<vscale x 8 x i8> [[TMP0]])
// CHECK-NEXT:    store <16 x i8> [[TMP1]], <16 x i8>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int8x16_t test_vcast_to_fixed_128_i8m1(vint8m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i8m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i16>, align 2
// CHECK-NEXT:    store <vscale x 4 x i16> [[X:%.*]], <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i16>, <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv4i16(<vscale x 4 x i16> [[TMP0]])
// CHECK-NEXT:    store <8 x i16> [[TMP1]], <8 x i16>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int16x8_t test_vcast_to_fixed_128_i16m1(vint16m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i16m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i32>, align 4
// CHECK-NEXT:    store <vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i32>, <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv2i32(<vscale x 2 x i32> [[TMP0]])
// CHECK-NEXT:    store <4 x i32> [[TMP1]], <4 x i32>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int32x4_t test_vcast_to_fixed_128_i32m1(vint32m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i32m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i64>, align 8
// CHECK-NEXT:    store <vscale x 1 x i64> [[X:%.*]], <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i64>, <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv1i64(<vscale x 1 x i64> [[TMP0]])
// CHECK-NEXT:    store <2 x i64> [[TMP1]], <2 x i64>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
int64x2_t test_vcast_to_fixed_128_i64m1(vint64m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i64m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i8> [[X:%.*]], <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i8>, <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv16i8(<vscale x 16 x i8> [[TMP1]])
// CHECK-NEXT:    store <32 x i8> [[TMP2]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i8>, <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <32 x i8> [[TMP3]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int8x32_t test_vcast_to_fixed_128_i8m2(vint8m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i8m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i16> [[X:%.*]], <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i16>, <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv8i16(<vscale x 8 x i16> [[TMP1]])
// CHECK-NEXT:    store <16 x i16> [[TMP2]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i16>, <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <16 x i16> [[TMP3]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int16x16_t test_vcast_to_fixed_128_i16m2(vint16m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i16m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x i32>, <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv4i32(<vscale x 4 x i32> [[TMP1]])
// CHECK-NEXT:    store <8 x i32> [[TMP2]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i32>, <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <8 x i32> [[TMP3]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int32x8_t test_vcast_to_fixed_128_i32m2(vint32m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i32m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 2 x i64> [[X:%.*]], <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 2 x i64>, <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv2i64(<vscale x 2 x i64> [[TMP1]])
// CHECK-NEXT:    store <4 x i64> [[TMP2]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i64>, <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <4 x i64> [[TMP3]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
int64x4_t test_vcast_to_fixed_128_i64m2(vint64m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i64m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x i8> [[X:%.*]], <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x i8>, <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv32i8(<vscale x 32 x i8> [[TMP1]])
// CHECK-NEXT:    store <64 x i8> [[TMP2]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <64 x i8>, <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <64 x i8> [[TMP3]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int8x64_t test_vcast_to_fixed_128_i8m4(vint8m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i8m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i16> [[X:%.*]], <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i16>, <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv16i16(<vscale x 16 x i16> [[TMP1]])
// CHECK-NEXT:    store <32 x i16> [[TMP2]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i16>, <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <32 x i16> [[TMP3]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int16x32_t test_vcast_to_fixed_128_i16m4(vint16m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i16m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i32> [[X:%.*]], <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i32>, <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv8i32(<vscale x 8 x i32> [[TMP1]])
// CHECK-NEXT:    store <16 x i32> [[TMP2]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <16 x i32> [[TMP3]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int32x16_t test_vcast_to_fixed_128_i32m4(vint32m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i32m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x i64> [[X:%.*]], <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x i64>, <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv4i64(<vscale x 4 x i64> [[TMP1]])
// CHECK-NEXT:    store <8 x i64> [[TMP2]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i64>, <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <8 x i64> [[TMP3]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
int64x8_t test_vcast_to_fixed_128_i64m4(vint64m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i64m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x i8> [[X:%.*]], <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i8>, <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv2i8(<vscale x 2 x i8> [[TMP0]])
// CHECK-NEXT:    store <4 x i8> [[TMP1]], <4 x i8>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int8x4_t test_vcast_to_fixed_128_i8mf4(vint8mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i8mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i16>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i16> [[X:%.*]], <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i16>, <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv1i16(<vscale x 1 x i16> [[TMP0]])
// CHECK-NEXT:    store <2 x i16> [[TMP1]], <2 x i16>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int16x2_t test_vcast_to_fixed_128_i16mf4(vint16mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i16mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_i8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i8> [[X:%.*]], <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i8>, <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv1i8(<vscale x 1 x i8> [[TMP0]])
// CHECK-NEXT:    store <2 x i8> [[TMP1]], <2 x i8>* [[RETVAL]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 2 [[TMP3]], i64 2, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
int8x2_t test_vcast_to_fixed_128_i8mf8(vint8mf8_t x) {
  return __builtin_rvv_vcast_to_fixed_128_i8mf8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i8>, align 1
// CHECK-NEXT:    store <vscale x 4 x i8> [[X:%.*]], <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i8>, <vscale x 4 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i8> @llvm.riscv.vcast.to.fixed.v8i8.nxv4i8(<vscale x 4 x i8> [[TMP0]])
// CHECK-NEXT:    store <8 x i8> [[TMP1]], <8 x i8>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i8>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint8x8_t test_vcast_to_fixed_128_u8mf2(vuint8mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u8mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i16>, align 2
// CHECK-NEXT:    store <vscale x 2 x i16> [[X:%.*]], <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i16>, <vscale x 2 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i16> @llvm.riscv.vcast.to.fixed.v4i16.nxv2i16(<vscale x 2 x i16> [[TMP0]])
// CHECK-NEXT:    store <4 x i16> [[TMP1]], <4 x i16>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i16>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint16x4_t test_vcast_to_fixed_128_u16mf2(vuint16mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u16mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i32>, align 4
// CHECK-NEXT:    store <vscale x 1 x i32> [[X:%.*]], <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i32>, <vscale x 1 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i32> @llvm.riscv.vcast.to.fixed.v2i32.nxv1i32(<vscale x 1 x i32> [[TMP0]])
// CHECK-NEXT:    store <2 x i32> [[TMP1]], <2 x i32>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i32>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
uint32x2_t test_vcast_to_fixed_128_u32mf2(vuint32mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u32mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i8>, align 1
// CHECK-NEXT:    store <vscale x 8 x i8> [[X:%.*]], <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 8 x i8>, <vscale x 8 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <16 x i8> @llvm.riscv.vcast.to.fixed.v16i8.nxv8i8(<vscale x 8 x i8> [[TMP0]])
// CHECK-NEXT:    store <16 x i8> [[TMP1]], <16 x i8>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint8x16_t test_vcast_to_fixed_128_u8m1(vuint8m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u8m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i16>, align 2
// CHECK-NEXT:    store <vscale x 4 x i16> [[X:%.*]], <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x i16>, <vscale x 4 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x i16> @llvm.riscv.vcast.to.fixed.v8i16.nxv4i16(<vscale x 4 x i16> [[TMP0]])
// CHECK-NEXT:    store <8 x i16> [[TMP1]], <8 x i16>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint16x8_t test_vcast_to_fixed_128_u16m1(vuint16m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u16m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i32>, align 4
// CHECK-NEXT:    store <vscale x 2 x i32> [[X:%.*]], <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i32>, <vscale x 2 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i32> @llvm.riscv.vcast.to.fixed.v4i32.nxv2i32(<vscale x 2 x i32> [[TMP0]])
// CHECK-NEXT:    store <4 x i32> [[TMP1]], <4 x i32>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x i32>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint32x4_t test_vcast_to_fixed_128_u32m1(vuint32m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u32m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i64>, align 8
// CHECK-NEXT:    store <vscale x 1 x i64> [[X:%.*]], <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i64>, <vscale x 1 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i64> @llvm.riscv.vcast.to.fixed.v2i64.nxv1i64(<vscale x 1 x i64> [[TMP0]])
// CHECK-NEXT:    store <2 x i64> [[TMP1]], <2 x i64>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x i64>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
uint64x2_t test_vcast_to_fixed_128_u64m1(vuint64m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u64m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i8> [[X:%.*]], <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i8>, <vscale x 16 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i8> @llvm.riscv.vcast.to.fixed.v32i8.nxv16i8(<vscale x 16 x i8> [[TMP1]])
// CHECK-NEXT:    store <32 x i8> [[TMP2]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i8>, <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <32 x i8> [[TMP3]], <32 x i8>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint8x32_t test_vcast_to_fixed_128_u8m2(vuint8m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u8m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i16> [[X:%.*]], <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i16>, <vscale x 8 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i16> @llvm.riscv.vcast.to.fixed.v16i16.nxv8i16(<vscale x 8 x i16> [[TMP1]])
// CHECK-NEXT:    store <16 x i16> [[TMP2]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i16>, <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <16 x i16> [[TMP3]], <16 x i16>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint16x16_t test_vcast_to_fixed_128_u16m2(vuint16m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u16m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x i32> [[X:%.*]], <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x i32>, <vscale x 4 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i32> @llvm.riscv.vcast.to.fixed.v8i32.nxv4i32(<vscale x 4 x i32> [[TMP1]])
// CHECK-NEXT:    store <8 x i32> [[TMP2]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i32>, <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <8 x i32> [[TMP3]], <8 x i32>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint32x8_t test_vcast_to_fixed_128_u32m2(vuint32m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u32m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 2 x i64> [[X:%.*]], <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 2 x i64>, <vscale x 2 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x i64> @llvm.riscv.vcast.to.fixed.v4i64.nxv2i64(<vscale x 2 x i64> [[TMP1]])
// CHECK-NEXT:    store <4 x i64> [[TMP2]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i64>, <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <4 x i64> [[TMP3]], <4 x i64>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
uint64x4_t test_vcast_to_fixed_128_u64m2(vuint64m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u64m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 32 x i8>, align 1
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <64 x i8>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 32 x i8> [[X:%.*]], <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 32 x i8>, <vscale x 32 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = call <64 x i8> @llvm.riscv.vcast.to.fixed.v64i8.nxv32i8(<vscale x 32 x i8> [[TMP1]])
// CHECK-NEXT:    store <64 x i8> [[TMP2]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <64 x i8>, <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <64 x i8> [[TMP3]], <64 x i8>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint8x64_t test_vcast_to_fixed_128_u8m4(vuint8m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u8m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x i16>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x i16>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x i16> [[X:%.*]], <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x i16>, <vscale x 16 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x i16> @llvm.riscv.vcast.to.fixed.v32i16.nxv16i16(<vscale x 16 x i16> [[TMP1]])
// CHECK-NEXT:    store <32 x i16> [[TMP2]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x i16>, <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <32 x i16> [[TMP3]], <32 x i16>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint16x32_t test_vcast_to_fixed_128_u16m4(vuint16m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u16m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x i32>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i32>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x i32> [[X:%.*]], <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x i32>, <vscale x 8 x i32>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x i32> @llvm.riscv.vcast.to.fixed.v16i32.nxv8i32(<vscale x 8 x i32> [[TMP1]])
// CHECK-NEXT:    store <16 x i32> [[TMP2]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <16 x i32> [[TMP3]], <16 x i32>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint32x16_t test_vcast_to_fixed_128_u32m4(vuint32m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u32m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x i64>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i64>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x i64> [[X:%.*]], <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x i64>, <vscale x 4 x i64>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x i64> @llvm.riscv.vcast.to.fixed.v8i64.nxv4i64(<vscale x 4 x i64> [[TMP1]])
// CHECK-NEXT:    store <8 x i64> [[TMP2]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i64>, <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <8 x i64> [[TMP3]], <8 x i64>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
uint64x8_t test_vcast_to_fixed_128_u64m4(vuint64m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u64m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 2 x i8> [[X:%.*]], <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x i8>, <vscale x 2 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x i8> @llvm.riscv.vcast.to.fixed.v4i8.nxv2i8(<vscale x 2 x i8> [[TMP0]])
// CHECK-NEXT:    store <4 x i8> [[TMP1]], <4 x i8>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint8x4_t test_vcast_to_fixed_128_u8mf4(vuint8mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u8mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i16>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i16> [[X:%.*]], <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i16>, <vscale x 1 x i16>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i16> @llvm.riscv.vcast.to.fixed.v2i16.nxv1i16(<vscale x 1 x i16> [[TMP0]])
// CHECK-NEXT:    store <2 x i16> [[TMP1]], <2 x i16>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i16>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint16x2_t test_vcast_to_fixed_128_u16mf4(vuint16mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u16mf4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x i8>, align 1
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x i8> [[X:%.*]], <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x i8>, <vscale x 1 x i8>* [[X_ADDR]], align 1
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x i8> @llvm.riscv.vcast.to.fixed.v2i8.nxv1i8(<vscale x 1 x i8> [[TMP0]])
// CHECK-NEXT:    store <2 x i8> [[TMP1]], <2 x i8>* [[RETVAL]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x i8>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 2 [[TMP3]], i64 2, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
uint8x2_t test_vcast_to_fixed_128_u8mf8(vuint8mf8_t x) {
  return __builtin_rvv_vcast_to_fixed_128_u8mf8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i8>, <8 x i8>* [[X]], align 8
// CHECK-NEXT:    store <8 x i8> [[X1]], <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i8>, <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v8i8(<8 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP2]]
//
vint8mf2_t test_vcast_from_fixed_128_i8mf2(int8x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i8mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i16>, <4 x i16>* [[X]], align 8
// CHECK-NEXT:    store <4 x i16> [[X1]], <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v4i16(<4 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP2]]
//
vint16mf2_t test_vcast_from_fixed_128_i16mf2(int16x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i16mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i32>, <2 x i32>* [[X]], align 8
// CHECK-NEXT:    store <2 x i32> [[X1]], <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v2i32(<2 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP2]]
//
vint32mf2_t test_vcast_from_fixed_128_i32mf2(int32x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i32mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <16 x i8>, <16 x i8>* [[X]], align 16
// CHECK-NEXT:    store <16 x i8> [[X1]], <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v16i8(<16 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP2]]
//
vint8m1_t test_vcast_from_fixed_128_i8m1(int8x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i8m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i16>, <8 x i16>* [[X]], align 16
// CHECK-NEXT:    store <8 x i16> [[X1]], <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v8i16(<8 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP2]]
//
vint16m1_t test_vcast_from_fixed_128_i16m1(int16x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i16m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i32>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i32>, <4 x i32>* [[X]], align 16
// CHECK-NEXT:    store <4 x i32> [[X1]], <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v4i32(<4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP2]]
//
vint32m1_t test_vcast_from_fixed_128_i32m1(int32x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i32m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i64>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i64>, <2 x i64>* [[X]], align 16
// CHECK-NEXT:    store <2 x i64> [[X1]], <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i64>, <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v2i64(<2 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP2]]
//
vint64m1_t test_vcast_from_fixed_128_i64m1(int64x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i64m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i8>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <32 x i8>, <32 x i8>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <32 x i8> [[X]], <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i8>, <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v32i8(<32 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP2]]
//
vint8m2_t test_vcast_from_fixed_128_i8m2(int8x32_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i8m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <16 x i16>, <16 x i16>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <16 x i16> [[X]], <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i16>, <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v16i16(<16 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP2]]
//
vint16m2_t test_vcast_from_fixed_128_i16m2(int16x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i16m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <8 x i32>, <8 x i32>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <8 x i32> [[X]], <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v8i32(<8 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
//
vint32m2_t test_vcast_from_fixed_128_i32m2(int32x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i32m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <4 x i64>, <4 x i64>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <4 x i64> [[X]], <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i64>, <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v4i64(<4 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP2]]
//
vint64m2_t test_vcast_from_fixed_128_i64m2(int64x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i64m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <64 x i8>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <64 x i8>, <64 x i8>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <64 x i8> [[X]], <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x i8>, <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v64i8(<64 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP2]]
//
vint8m4_t test_vcast_from_fixed_128_i8m4(int8x64_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i8m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i16>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <32 x i16>, <32 x i16>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <32 x i16> [[X]], <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v32i16(<32 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP2]]
//
vint16m4_t test_vcast_from_fixed_128_i16m4(int16x32_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i16m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <16 x i32> [[X]], <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v16i32(<16 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP2]]
//
vint32m4_t test_vcast_from_fixed_128_i32m4(int32x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i32m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <8 x i64>, <8 x i64>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <8 x i64> [[X]], <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i64>, <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v8i64(<8 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP2]]
//
vint64m4_t test_vcast_from_fixed_128_i64m4(int64x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i64m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i8>, <4 x i8>* [[X]], align 4
// CHECK-NEXT:    store <4 x i8> [[X1]], <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i8>, <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v4i8(<4 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP3]]
//
vint8mf4_t test_vcast_from_fixed_128_i8mf4(int8x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i8mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i16>, <2 x i16>* [[X]], align 4
// CHECK-NEXT:    store <2 x i16> [[X1]], <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i16>, <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v2i16(<2 x i16> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP3]]
//
vint16mf4_t test_vcast_from_fixed_128_i16mf4(int16x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i16mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_i8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 [[TMP0]], i8* align 8 [[TMP1]], i64 2, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i8>, <2 x i8>* [[X]], align 2
// CHECK-NEXT:    store <2 x i8> [[X1]], <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i8>, <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v2i8(<2 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP3]]
//
vint8mf8_t test_vcast_from_fixed_128_i8mf8(int8x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_i8mf8(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u8mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i8>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i8>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i8>, <8 x i8>* [[X]], align 8
// CHECK-NEXT:    store <8 x i8> [[X1]], <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i8>, <8 x i8>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vcast.from.fixed.nxv4i8.v8i8(<8 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i8> [[TMP2]]
//
vuint8mf2_t test_vcast_from_fixed_128_u8mf2(uint8x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u8mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i16>, <4 x i16>* [[X]], align 8
// CHECK-NEXT:    store <4 x i16> [[X1]], <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, <4 x i16>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vcast.from.fixed.nxv2i16.v4i16(<4 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i16> [[TMP2]]
//
vuint16mf2_t test_vcast_from_fixed_128_u16mf2(uint16x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u16mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i32>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i32>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i32>, <2 x i32>* [[X]], align 8
// CHECK-NEXT:    store <2 x i32> [[X1]], <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, <2 x i32>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vcast.from.fixed.nxv1i32.v2i32(<2 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x i32> [[TMP2]]
//
vuint32mf2_t test_vcast_from_fixed_128_u32mf2(uint32x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u32mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u8m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x i8>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <16 x i8>, <16 x i8>* [[X]], align 16
// CHECK-NEXT:    store <16 x i8> [[X1]], <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, <16 x i8>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vcast.from.fixed.nxv8i8.v16i8(<16 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i8> [[TMP2]]
//
vuint8m1_t test_vcast_from_fixed_128_u8m1(uint8x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u8m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x i16>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <8 x i16>, <8 x i16>* [[X]], align 16
// CHECK-NEXT:    store <8 x i16> [[X1]], <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, <8 x i16>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vcast.from.fixed.nxv4i16.v8i16(<8 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i16> [[TMP2]]
//
vuint16m1_t test_vcast_from_fixed_128_u16m1(uint16x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u16m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i32>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i32>, <4 x i32>* [[X]], align 16
// CHECK-NEXT:    store <4 x i32> [[X1]], <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, <4 x i32>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vcast.from.fixed.nxv2i32.v4i32(<4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i32> [[TMP2]]
//
vuint32m1_t test_vcast_from_fixed_128_u32m1(uint32x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u32m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i64>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i64>, <2 x i64>* [[X]], align 16
// CHECK-NEXT:    store <2 x i64> [[X1]], <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i64>, <2 x i64>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vcast.from.fixed.nxv1i64.v2i64(<2 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x i64> [[TMP2]]
//
vuint64m1_t test_vcast_from_fixed_128_u64m1(uint64x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u64m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u8m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i8>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <32 x i8>, <32 x i8>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <32 x i8> [[X]], <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i8>, <32 x i8>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vcast.from.fixed.nxv16i8.v32i8(<32 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i8> [[TMP2]]
//
vuint8m2_t test_vcast_from_fixed_128_u8m2(uint8x32_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u8m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <16 x i16>, <16 x i16>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <16 x i16> [[X]], <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i16>, <16 x i16>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vcast.from.fixed.nxv8i16.v16i16(<16 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i16> [[TMP2]]
//
vuint16m2_t test_vcast_from_fixed_128_u16m2(uint16x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u16m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i32>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <8 x i32>, <8 x i32>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <8 x i32> [[X]], <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i32>, <8 x i32>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vcast.from.fixed.nxv4i32.v8i32(<8 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i32> [[TMP2]]
//
vuint32m2_t test_vcast_from_fixed_128_u32m2(uint32x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u32m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i64>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <4 x i64>, <4 x i64>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <4 x i64> [[X]], <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i64>, <4 x i64>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vcast.from.fixed.nxv2i64.v4i64(<4 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x i64> [[TMP2]]
//
vuint64m2_t test_vcast_from_fixed_128_u64m2(uint64x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u64m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u8m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <64 x i8>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <64 x i8>, <64 x i8>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <64 x i8> [[X]], <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <64 x i8>, <64 x i8>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vcast.from.fixed.nxv32i8.v64i8(<64 x i8> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 32 x i8> [[TMP2]]
//
vuint8m4_t test_vcast_from_fixed_128_u8m4(uint8x64_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u8m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x i16>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <32 x i16>, <32 x i16>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <32 x i16> [[X]], <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x i16>, <32 x i16>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vcast.from.fixed.nxv16i16.v32i16(<32 x i16> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x i16> [[TMP2]]
//
vuint16m4_t test_vcast_from_fixed_128_u16m4(uint16x32_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u16m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <16 x i32> [[X]], <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i32>, <16 x i32>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vcast.from.fixed.nxv8i32.v16i32(<16 x i32> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x i32> [[TMP2]]
//
vuint32m4_t test_vcast_from_fixed_128_u32m4(uint32x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u32m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i64>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <8 x i64>, <8 x i64>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <8 x i64> [[X]], <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i64>, <8 x i64>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vcast.from.fixed.nxv4i64.v8i64(<8 x i64> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x i64> [[TMP2]]
//
vuint64m4_t test_vcast_from_fixed_128_u64m4(uint64x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u64m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u8mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x i8>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <4 x i8>, <4 x i8>* [[X]], align 4
// CHECK-NEXT:    store <4 x i8> [[X1]], <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i8>, <4 x i8>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vcast.from.fixed.nxv2i8.v4i8(<4 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 2 x i8> [[TMP3]]
//
vuint8mf4_t test_vcast_from_fixed_128_u8mf4(uint8x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u8mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i16>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i16>, <2 x i16>* [[X]], align 4
// CHECK-NEXT:    store <2 x i16> [[X1]], <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i16>, <2 x i16>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vcast.from.fixed.nxv1i16.v2i16(<2 x i16> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i16> [[TMP3]]
//
vuint16mf4_t test_vcast_from_fixed_128_u16mf4(uint16x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u16mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_u8mf8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x i8>, align 2
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x i8>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 2 [[TMP0]], i8* align 8 [[TMP1]], i64 2, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x i8>, <2 x i8>* [[X]], align 2
// CHECK-NEXT:    store <2 x i8> [[X1]], <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i8>, <2 x i8>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vcast.from.fixed.nxv1i8.v2i8(<2 x i8> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x i8> [[TMP3]]
//
vuint8mf8_t test_vcast_from_fixed_128_u8mf8(uint8x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_u8mf8(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x float>, align 4
// CHECK-NEXT:    store <vscale x 1 x float> [[X:%.*]], <vscale x 1 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x float>, <vscale x 1 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x float> @llvm.riscv.vcast.to.fixed.v2f32.nxv1f32(<vscale x 1 x float> [[TMP0]])
// CHECK-NEXT:    store <2 x float> [[TMP1]], <2 x float>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x float>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
float32x2_t test_vcast_to_fixed_128_f32mf2(vfloat32mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f32mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x float>, align 4
// CHECK-NEXT:    store <vscale x 2 x float> [[X:%.*]], <vscale x 2 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x float>, <vscale x 2 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x float> @llvm.riscv.vcast.to.fixed.v4f32.nxv2f32(<vscale x 2 x float> [[TMP0]])
// CHECK-NEXT:    store <4 x float> [[TMP1]], <4 x float>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x float>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
float32x4_t test_vcast_to_fixed_128_f32m1(vfloat32m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f32m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x double>, align 8
// CHECK-NEXT:    store <vscale x 1 x double> [[X:%.*]], <vscale x 1 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x double>, <vscale x 1 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x double> @llvm.riscv.vcast.to.fixed.v2f64.nxv1f64(<vscale x 1 x double> [[TMP0]])
// CHECK-NEXT:    store <2 x double> [[TMP1]], <2 x double>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <2 x double>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
float64x2_t test_vcast_to_fixed_128_f64m1(vfloat64m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f64m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x float>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x float>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x float> [[X:%.*]], <vscale x 4 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x float>, <vscale x 4 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x float> @llvm.riscv.vcast.to.fixed.v8f32.nxv4f32(<vscale x 4 x float> [[TMP1]])
// CHECK-NEXT:    store <8 x float> [[TMP2]], <8 x float>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x float>, <8 x float>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <8 x float> [[TMP3]], <8 x float>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
float32x8_t test_vcast_to_fixed_128_f32m2(vfloat32m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f32m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x double>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x double>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 2 x double> [[X:%.*]], <vscale x 2 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 2 x double>, <vscale x 2 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x double> @llvm.riscv.vcast.to.fixed.v4f64.nxv2f64(<vscale x 2 x double> [[TMP1]])
// CHECK-NEXT:    store <4 x double> [[TMP2]], <4 x double>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x double>, <4 x double>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <4 x double> [[TMP3]], <4 x double>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
float64x4_t test_vcast_to_fixed_128_f64m2(vfloat64m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f64m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x float>, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x float>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x float> [[X:%.*]], <vscale x 8 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x float>, <vscale x 8 x float>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x float> @llvm.riscv.vcast.to.fixed.v16f32.nxv8f32(<vscale x 8 x float> [[TMP1]])
// CHECK-NEXT:    store <16 x float> [[TMP2]], <16 x float>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x float>, <16 x float>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <16 x float> [[TMP3]], <16 x float>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
float32x16_t test_vcast_to_fixed_128_f32m4(vfloat32m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f32m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x double>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x double>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 4 x double> [[X:%.*]], <vscale x 4 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 4 x double>, <vscale x 4 x double>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <8 x double> @llvm.riscv.vcast.to.fixed.v8f64.nxv4f64(<vscale x 4 x double> [[TMP1]])
// CHECK-NEXT:    store <8 x double> [[TMP2]], <8 x double>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x double>, <8 x double>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <8 x double> [[TMP3]], <8 x double>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
float64x8_t test_vcast_to_fixed_128_f64m4(vfloat64m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f64m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <4 x half>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 2 x half>, align 2
// CHECK-NEXT:    store <vscale x 2 x half> [[X:%.*]], <vscale x 2 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x half>, <vscale x 2 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <4 x half> @llvm.riscv.vcast.to.fixed.v4f16.nxv2f16(<vscale x 2 x half> [[TMP0]])
// CHECK-NEXT:    store <4 x half> [[TMP1]], <4 x half>* [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <4 x half>* [[RETVAL]] to i64*
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, i64* [[TMP2]], align 8
// CHECK-NEXT:    ret i64 [[TMP3]]
//
float16x4_t test_vcast_to_fixed_128_f16mf2(vfloat16mf2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f16mf2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 4 x half>, align 2
// CHECK-NEXT:    store <vscale x 4 x half> [[X:%.*]], <vscale x 4 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 4 x half>, <vscale x 4 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <8 x half> @llvm.riscv.vcast.to.fixed.v8f16.nxv4f16(<vscale x 4 x half> [[TMP0]])
// CHECK-NEXT:    store <8 x half> [[TMP1]], <8 x half>* [[RETVAL]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x half>* [[RETVAL]] to i128*
// CHECK-NEXT:    [[TMP3:%.*]] = load i128, i128* [[TMP2]], align 16
// CHECK-NEXT:    ret i128 [[TMP3]]
//
float16x8_t test_vcast_to_fixed_128_f16m1(vfloat16m1_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f16m1(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 8 x half>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <16 x half>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 8 x half> [[X:%.*]], <vscale x 8 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 8 x half>, <vscale x 8 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <16 x half> @llvm.riscv.vcast.to.fixed.v16f16.nxv8f16(<vscale x 8 x half> [[TMP1]])
// CHECK-NEXT:    store <16 x half> [[TMP2]], <16 x half>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x half>, <16 x half>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    store <16 x half> [[TMP3]], <16 x half>* [[AGG_RESULT]], align 32
// CHECK-NEXT:    ret void
//
float16x16_t test_vcast_to_fixed_128_f16m2(vfloat16m2_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f16m2(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RESULT_PTR:%.*]] = alloca i8*, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 16 x half>, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <32 x half>* [[AGG_RESULT:%.*]] to i8*
// CHECK-NEXT:    store i8* [[TMP0]], i8** [[RESULT_PTR]], align 8
// CHECK-NEXT:    store <vscale x 16 x half> [[X:%.*]], <vscale x 16 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = load <vscale x 16 x half>, <vscale x 16 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = call <32 x half> @llvm.riscv.vcast.to.fixed.v32f16.nxv16f16(<vscale x 16 x half> [[TMP1]])
// CHECK-NEXT:    store <32 x half> [[TMP2]], <32 x half>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    [[TMP3:%.*]] = load <32 x half>, <32 x half>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    store <32 x half> [[TMP3]], <32 x half>* [[AGG_RESULT]], align 64
// CHECK-NEXT:    ret void
//
float16x32_t test_vcast_to_fixed_128_f16m4(vfloat16m4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f16m4(x);
}

// CHECK-LABEL: @test_vcast_to_fixed_128_f16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca <2 x half>, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <vscale x 1 x half>, align 2
// CHECK-NEXT:    [[RETVAL_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store <vscale x 1 x half> [[X:%.*]], <vscale x 1 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load <vscale x 1 x half>, <vscale x 1 x half>* [[X_ADDR]], align 2
// CHECK-NEXT:    [[TMP1:%.*]] = call <2 x half> @llvm.riscv.vcast.to.fixed.v2f16.nxv1f16(<vscale x 1 x half> [[TMP0]])
// CHECK-NEXT:    store <2 x half> [[TMP1]], <2 x half>* [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast i64* [[RETVAL_COERCE]] to i8*
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <2 x half>* [[RETVAL]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 8 [[TMP2]], i8* align 4 [[TMP3]], i64 4, i1 false)
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, i64* [[RETVAL_COERCE]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
float16x2_t test_vcast_to_fixed_128_f16mf4(vfloat16mf4_t x) {
  return __builtin_rvv_vcast_to_fixed_128_f16mf4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f32mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x float>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <2 x float>, <2 x float>* [[X]], align 8
// CHECK-NEXT:    store <2 x float> [[X1]], <2 x float>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x float>, <2 x float>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x float> @llvm.riscv.vcast.from.fixed.nxv1f32.v2f32(<2 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x float> [[TMP2]]
//
vfloat32mf2_t test_vcast_from_fixed_128_f32mf2(float32x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f32mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f32m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x float>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <4 x float>, <4 x float>* [[X]], align 16
// CHECK-NEXT:    store <4 x float> [[X1]], <4 x float>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, <4 x float>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x float> @llvm.riscv.vcast.from.fixed.nxv2f32.v4f32(<4 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x float> [[TMP2]]
//
vfloat32m1_t test_vcast_from_fixed_128_f32m1(float32x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f32m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f64m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x double>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <2 x double>, <2 x double>* [[X]], align 16
// CHECK-NEXT:    store <2 x double> [[X1]], <2 x double>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x double>, <2 x double>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 1 x double> @llvm.riscv.vcast.from.fixed.nxv1f64.v2f64(<2 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 1 x double> [[TMP2]]
//
vfloat64m1_t test_vcast_from_fixed_128_f64m1(float64x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f64m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f32m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x float>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <8 x float>, <8 x float>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <8 x float> [[X]], <8 x float>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x float>, <8 x float>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x float> @llvm.riscv.vcast.from.fixed.nxv4f32.v8f32(<8 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x float> [[TMP2]]
//
vfloat32m2_t test_vcast_from_fixed_128_f32m2(float32x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f32m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f64m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x double>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <4 x double>, <4 x double>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <4 x double> [[X]], <4 x double>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x double>, <4 x double>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x double> @llvm.riscv.vcast.from.fixed.nxv2f64.v4f64(<4 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x double> [[TMP2]]
//
vfloat64m2_t test_vcast_from_fixed_128_f64m2(float64x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f64m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f32m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <16 x float>, <16 x float>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <16 x float> [[X]], <16 x float>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, <16 x float>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x float> @llvm.riscv.vcast.from.fixed.nxv8f32.v16f32(<16 x float> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x float> [[TMP2]]
//
vfloat32m4_t test_vcast_from_fixed_128_f32m4(float32x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f32m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f64m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x double>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <8 x double>, <8 x double>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <8 x double> [[X]], <8 x double>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x double>, <8 x double>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x double> @llvm.riscv.vcast.from.fixed.nxv4f64.v8f64(<8 x double> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x double> [[TMP2]]
//
vfloat64m4_t test_vcast_from_fixed_128_f64m4(float64x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f64m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f16mf2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <4 x half>, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <4 x half>, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x half>* [[X]] to i64*
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP0]], align 8
// CHECK-NEXT:    [[X1:%.*]] = load <4 x half>, <4 x half>* [[X]], align 8
// CHECK-NEXT:    store <4 x half> [[X1]], <4 x half>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x half>, <4 x half>* [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 2 x half> @llvm.riscv.vcast.from.fixed.nxv2f16.v4f16(<4 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 2 x half> [[TMP2]]
//
vfloat16mf2_t test_vcast_from_fixed_128_f16mf2(float16x4_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f16mf2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f16m1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <8 x half>* [[X]] to i128*
// CHECK-NEXT:    store i128 [[X_COERCE:%.*]], i128* [[TMP0]], align 16
// CHECK-NEXT:    [[X1:%.*]] = load <8 x half>, <8 x half>* [[X]], align 16
// CHECK-NEXT:    store <8 x half> [[X1]], <8 x half>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x half>, <8 x half>* [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x half> @llvm.riscv.vcast.from.fixed.nxv4f16.v8f16(<8 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 4 x half> [[TMP2]]
//
vfloat16m1_t test_vcast_from_fixed_128_f16m1(float16x8_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f16m1(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f16m2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <16 x half>, align 32
// CHECK-NEXT:    [[X:%.*]] = load <16 x half>, <16 x half>* [[TMP0:%.*]], align 32
// CHECK-NEXT:    store <16 x half> [[X]], <16 x half>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x half>, <16 x half>* [[X_ADDR]], align 32
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 8 x half> @llvm.riscv.vcast.from.fixed.nxv8f16.v16f16(<16 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 8 x half> [[TMP2]]
//
vfloat16m2_t test_vcast_from_fixed_128_f16m2(float16x16_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f16m2(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f16m4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <32 x half>, align 64
// CHECK-NEXT:    [[X:%.*]] = load <32 x half>, <32 x half>* [[TMP0:%.*]], align 64
// CHECK-NEXT:    store <32 x half> [[X]], <32 x half>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP1:%.*]] = load <32 x half>, <32 x half>* [[X_ADDR]], align 64
// CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x half> @llvm.riscv.vcast.from.fixed.nxv16f16.v32f16(<32 x half> [[TMP1]])
// CHECK-NEXT:    ret <vscale x 16 x half> [[TMP2]]
//
vfloat16m4_t test_vcast_from_fixed_128_f16m4(float16x32_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f16m4(x);
}

// CHECK-LABEL: @test_vcast_from_fixed_128_f16mf4(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca <2 x half>, align 4
// CHECK-NEXT:    [[TMP_COERCE:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca <2 x half>, align 4
// CHECK-NEXT:    store i64 [[X_COERCE:%.*]], i64* [[TMP_COERCE]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <2 x half>* [[X]] to i8*
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64* [[TMP_COERCE]] to i8*
// CHECK-NEXT:    call void @llvm.memcpy.p0i8.p0i8.i64(i8* align 4 [[TMP0]], i8* align 8 [[TMP1]], i64 4, i1 false)
// CHECK-NEXT:    [[X1:%.*]] = load <2 x half>, <2 x half>* [[X]], align 4
// CHECK-NEXT:    store <2 x half> [[X1]], <2 x half>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x half>, <2 x half>* [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 1 x half> @llvm.riscv.vcast.from.fixed.nxv1f16.v2f16(<2 x half> [[TMP2]])
// CHECK-NEXT:    ret <vscale x 1 x half> [[TMP3]]
//
vfloat16mf4_t test_vcast_from_fixed_128_f16mf4(float16x2_t x) {
  return __builtin_rvv_vcast_from_fixed_128_f16mf4(x);
}
